### ISSUE TITLE
Aggregate reports are not immediately displayed in the grid once they are created

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10008]
### Bug Description

Newly created aggregated reports are not immediately displayed in the list of reports.

### Steps to Reproduce

1. Navigate to the mSERS directory, on either the 'Aggregate reporting' or the 'Report Data' tab;
2. Leave the filters on the tab as they are set by default;
3. Open the 'Create new aggregated report' form and fill it in (Epi Week - leave the default value that is the current epi week; set a region district and facility; set values for at least 1 disease);
4. Click 'Save'.

### Actual Behavior

The newly created report is displayed only if the user refreshes the page (either by clicking the reload button in the browser, by navigating back and forth between the mSERS directory and another directory, by clicking Apply filters or Reset filters).

### Expected Behavior

The newly created aggregated report should immediately be displayed in the list of reports.

### Screenshots

GIF of the behavior:
![Reports](https://user-images.githubusercontent.com/96909231/182131355-2be63a76-3754-4e36-ae88-e63eacb2112a.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(6971971); 1.75.0-SNAPSHOT(b464ebb)
* Android version/Browser: Chrome
* Server URL: local machine; test.sormas.netzlink.com
* User Role: Admin+NatUser

### Additional Information

I could not determine which specific ticket from this sprint has caused the behavior. Therefore, the current new ticket was logged. If the developer that will pick it up manages to discover if this behavior is due to another ticket from this sprint, I will discard this one and reopen that ticket.

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.75.0-SNAPSHOT (a6ecbf1).
