### ISSUE TITLE
(Inactive) suffix is not displayed for archived jurisdiction values in aggregate report forms

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10005]
### Bug Description

When a region, district, facility or point of entry are archived, on the pages of the entities that have the respective jurisdiction values set already, the (Inactive) suffix is added.

However, on aggregate reports, this suffix is not displayed.

### Steps to Reproduce

1. Create an aggregate report with a region, district and facility;
2. From the 'Configuration' directory, archive the region, district and facility set at step 1;
3. Navigate back the the report created at step 1 and observe the values associated with the report's jurisdiction.

### Actual Behavior

The '(Inactive)' suffix is not displayed next to the values of the archived region, district, facility, point of entry when opening the edit form of an existing aggregate report.

### Expected Behavior

The '(Inactive)' suffix should be displayed next to the values of the archived region, district, facility, point of entry when opening the edit form of an existing aggregate report.

### Screenshots

Archived values for jurisdiction on a case's page:
![image](https://user-images.githubusercontent.com/96909231/182125261-7ef83146-dfbb-4e95-978c-9014c3f50db6.png)

Archived values for jurisdiction on an aggregated report's page/edit form:
![image](https://user-images.githubusercontent.com/96909231/182125289-da4bcf1b-eac0-464d-9aec-42f75e572014.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(6768c67)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by MateStrysewske** [comment]
I'd assume this to be not relevant because the inactive suffix is specifically used in order to hint at selected infrastructure data not being normally selectable anymore when editing these values. Since the infrastructure dropdowns are read-only in aggregate report forms, this information is not important here.
