### ISSUE TITLE
Add National Clinician user role

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1002]

**Comment by Iheanacho2027** [comment]
Hi Mate. The addition of the national clinician role is critically needed. Can this be done urgently as we are being pressurized for it?

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I'll add it to our current sprint, I think we should still have some capacity left to work on this issue.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 @danieltomaba Could you please briefly describe what the exact purpose of the National Clinician is, i.e. what are their responsibilities and what exactly will they do within SORMAS? Are they basically doing the same work as a Clinician, but should have access to all cases within SORMAS or are they more of an observer role (like the National Observer or District Observer) that has access to the Case Management areas (therapies, treatments, prescriptions, clinical course)?

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym The national clinician role focuses on therapies and treatments of all cases (in this case Lassa fever ) in the whole country. So he/she needs to see all the cases which had therapies and treatments or prescription for all states and LGAs. The question is what the national clinician would do with this information. @Chinedar @Iheanacho2027 Please verify what the national clinician actually does. Does he work with the cases or only looks at it. Hence, we might have to make him a national clinician observer.

**Comment by Iheanacho2027** [comment]
The national clinician supervises entry from different states and uses the case management data for analysis at the national level. This analysis is used for decision making in terms of logistics and management of cases at the treatment centres.

**Comment by Chinedar** [comment]
At the moment, paper forms still come to the national level and the national clinician needs to review and validate and update data, comparing what they enter from the facilities with the forms sent to the national public health institute; NCDC. He/she needs to be a user and not an observer.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] allow to combine with national user role
