### ISSUE TITLE
[mSERS] Rename "New Cases" to "Suspected Cases"

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10026]
### Bug Description

#9605 introduced the 'Suspected Cases' renaming of 'New Cases' in the mSERS directory.

'New Cases' is still visible in the following places:
- [x] 'Report Data' tab of the mSERS directory;
- [x] exports done from 'Aggregate Reporting' and 'Report Data' tabs;
- [ ] ~~from the Data Base - in the 'aggregatereport' table;~~
- [ ] ~~'Help' section (android-app) of the mSERS directory;~~
![image](https://user-images.githubusercontent.com/96909231/182565480-b823fa0f-cb27-4405-ab41-0af5947d760f.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(81bdbe6)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by MateStrysewske** [comment]
@adinaflorea9 Database and help section have to remain this way (same as the first line in the export) because the column is still called "newCases" and will still be called like that going forward, only the caption has changed.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(cfb7eb0).
