### ISSUE TITLE
User Role - When a role is being enable to have at least one right selected

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10033]
### Problem Description
When creating a new Role and making it enable, it can be saved without having a right selected. Because of this behaviour we can assign the new role at the users but having no right on it

### Proposed Change
When a Role is changing the status to enable, to request in a warning message that at least one right should be selected

**Comment by carina29** [comment]
With admin role the message appears after a new User Role was created.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.79.0-SNAPSHOT.

Notes:
1) It was implemented as stated in Carina's comment. After the user role is created, a warning message saying that the user role was created without rights is displayed.
2) The translations have not been fetched from Crowdin yet.

**Comment by roxanamlendea** [comment]
Reopening the ticket because the warning message is displayed even if the new created user role has user rights selected.
![user role](https://user-images.githubusercontent.com/89522688/209778645-1612cfd1-c571-4603-852e-027f52c7753e.gif)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(e14e768).
