### ISSUE TITLE
User Role list - The list grid does not use the available space and cuts off text 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10032]
### Problem Description
The list grid does not use the available space and cuts off text even if the space would allow for the full display of the content.

a. Create a new user role
b. enter a long description
c. check the display on the user roles view

**Comment by carina29** [comment]
This change will be solved in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4462
