### ISSUE TITLE
User Role - User right Sormas UI and Rest should be included automatically when selecting a right [0.5]

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10034]
### Problem Description
 A new Role is created with status Enable and some rights for Case management as example. Admin creates a new User with the new Role. At this point the new User created is not able to login because it has not selected the right dor Sormas UI

### Proposed Change
There can be 3 solutions:
1. To automatically select the rights Sormas UI and Rest when at least one of the other rights is selected
2. To not be able to save the Role without having Sormas UI or Rest selected
3. To have by default selected this right Sormas UI or Rest when a new Role is created

### Implementation Details

When a user is saved without one of those rights selected there should be a warning message displayed

**Comment by MartinWahnschaffe** [comment]
## Alternative Proposal
We should simply get rid of those two user rights. The user rights should be about access to data via the backend and there is no need to care whether a user does this via the web UI or the ReST api (Android, external tools, ...).
