### ISSUE TITLE
User Role - No dropdown appearing if right for "Has associated district user" is checked

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10041]
### Bug Description
Having a role with the right selected "Has associated district user", at User edit/create will not appear any dropdown to select user from district

### Steps to Reproduce
1. Have a Role with this right selected: "Has associated district user"
2. Create a user with the Role above
3. Check in the create/edit form of the User if a dropdown with users appears

### Expected Behavior
A dropdown with users assigned to a district should appear

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by carina29** [comment]
"Has associated district user" checkbox can be selected from Create new user role modal window when the selected jurisdiction level is Community or Facility:

![image](https://user-images.githubusercontent.com/47103965/183379537-7e30e1d5-02f2-4816-a2c9-953f3a2e70be.png)

**Comment by abrudanancuta** [comment]
Validated on the local env with the version: 1.75.0-SNAPSHOT (9566331)
