### ISSUE TITLE
Add health conditions and clinical assessments to mobile app [5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1005]
- [x] Add both sections to the sub menu
- [x] Add all required entities and fields to backend & database
- [x] Add synchronization logic
- [x] Add health conditions view and fragment
- [x] Add clinical assessments view and list fragment
- [x] Add clinical assessment create/edit views
- [x] invalidate cases in the local database so all cases with therapy data are synchronized
- [x] Check whether ClinicalVisits actually need the person (i.e., is it necessary to display all clinical visits of all existing cases of a person similar to follow-up visits?)

We need to think about forcing a synchronization on app start-up (as long as internet connection is available) again, or alternatively after the app has been updated; right now, after updating to the newest version, entering a case will crash because there will be no clinical course. This will obviously also happen when the app update is done manually without internet connection. Also, the app should probably be able to deal with missing embedded ados.

**Comment by blongho** [comment]
Hi, @MateStrysewskeSym  i would like to work on this issue if no one is assigned to it already

**Comment by MartinWahnschaffeSymeda** [comment]
Hi @blongho We have planned working on this already. I think the issue you mentioned before #998 would be a perfect start. Also we already took it out of our implementation planning, so it's free for you to work on it when you have time.

**Comment by blongho** [comment]
@MartinWahnschaffeSymeda ok

**Comment by MateStrysewskeSym** [comment]
- [ ] Update symptoms when clinical visits are transfered and saved to the backend

**Comment by MateStrysewskeSym** [comment]
- [ ] remove getCaseByClinicalCourse method, retrieve case from entity and convert to dto in saveClinicalVisit method instead
