### ISSUE TITLE
Duplicate investigation tasks may be created for cases

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#10053]
Kay sent as a comment to https://github.com/hzi-braunschweig/SORMAS-Project/issues/6748

I tested this feature on test-de2.sormas.netzlink.com, 1.75.0-SNAPSHOT (b1baa08) with TASK_GENERATION* featureconfiugrations enabled and Admin + National User roles and noticed the following:

- When a case is created and contains a case investigation task, a new task of the same type is created whenever changing the existing ones status to `IN_PROGRESS` and saving the case.
    - If this task type is set to in progress, new case investigation tasks should not be created upon saving the case because a user is already working on the existing one.
    - This can also be done for multiple tasks that get set to `IN_PROGRESS`

![additionalCaseInvestigationTask](https://user-images.githubusercontent.com/70317594/182787675-ddf6e0d5-7f47-4ef9-b456-bd8f583ac6b5.gif)

This could lead to many duplicate tasks and get confusing to users. Thus, re-opening the ticket.

_Originally posted by @kwa20 in https://github.com/hzi-braunschweig/SORMAS-Project/issues/6748#issuecomment-1204867395_

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(ea29af6).
