### ISSUE TITLE
Unclear behaviour of "select all sormas data" key option under "database export"

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1007]
The "select all sormas data" key  under database export is redundant and it responds only one direction. eg  choose "select all" and latter choose "select all sormas data" and nothing will change.
It is better we drop the option "select all sormas data"

**Comment by MartinWahnschaffeSymeda** [comment]
This is kind of a bug. When everything is already selected "select all sormas data" should probably deselect the infrastructure data.

**Comment by MartinWahnschaffeSymeda** [comment]
This is kind of a bug. When everything is already selected "select all sormas data" should probably deselect the infrastructure data. I still think this option makes sense and should stay.
