### ISSUE TITLE
S2S_New Right_ S2S_Process [1]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10084]
### Feature Description

A new user right is introduced for S2S because of data protection reasons.
### Proposed Change

- [x] Implementation of right SORMAS_TO_SORMAS_Process
- Name of right: 
S2S_Process
- Description of right: 
Only users with this right are allowed to ~~process received shares and only this user is allowed to~~ see & use the share directory.
- The right is linked to the following roles: 
none

- [x] Change right SORMAS_TO_SORMAS_SHARE
- Name of right: 
S2S_Share
- Description of right: 
>> - Users with this right can initiate a share for a case/contact (is already included in the right).
>> - The rights from S2S_Process must be withdrawn from the right SORMAS_TO_SORMAS_SHARE 
(so a user with the right SORMAS_TO_SORMAS_SHARE can not see the share directory and can not process incoming share request.)
- The right is linked to the following roles: 
none

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by leventegal-she** [comment]
> * The right is linked to the following roles:
>   none

@SahaLinaPrueger does the above mean that no default user role will have right to share and/or process share requests?
Do we need to remove the SORMAS_TO_SORMAS_SHARE right of currently existing user roles?

**Comment by SahaLinaPrueger** [comment]
Yes, that is exactly what is meant.

**Comment by ChristopherRiedel** [comment]
> Yes, that is exactly what is meant.

@SahaLinaPrueger Just to be sure: This then means that on all instances (development, test and production) there will be no more users that can use Sormas2Sormas until someone manually reassigns these rights in user role management. Is this desired? I would actually have expected that the rights would only be removed from DefaultUserRoles, but all users would be able to do everything as before.

**Comment by SahaLinaPrueger** [comment]
@ChristopherRiedel thank you very much for the demand!
If it is possible to only remove the rights from the DefaultUserRoles AND already existing users are able to do everything as before this would be nice. 

So when a new health department gets S2S, first of all no user should be able to operate S2S with the DefaultUserRoles.
If it is possible, that in health departments that already have S2S (and development and test instances), the users that already have S2S rights keep them, so SORMAS_TO_SORMAS_SHARE and SORMAS_TO_SORMAS_Process get automatically, that would be great.

**Comment by ChristopherRiedel** [comment]
@SahaLinaPrueger Yes that's possible. I will make sure it is implemented that way.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.75.0 deployed on test-de2 environment

**Comment by SahaLinaPrueger** [comment]
> If it is possible to only remove the rights from the DefaultUserRoles AND already existing users are able to do everything as before this would be nice.

@AndyBakcsy-she and @ChristopherRiedel tested this on test-de1 and test-de2 (nightly). The DefaultUserRoles (like admin or national doc) still have the rights SORMAS_TO_SORMAS_SHARE and SORMAS_TO_SORMAS_PROCESS. The rights should be removed from the DefaultUserRoles.

**Comment by leventegal-she** [comment]
@SahaLinaPrueger the default user roles doesn't have any S2S related user rights any more, the ones on test-de1 and test-de2  where modified by QA people to be able to test S2S in general.

**Comment by ChristopherRiedel** [comment]
> > If it is possible to only remove the rights from the DefaultUserRoles AND already existing users are able to do everything as before this would be nice.
> 
> @AndyBakcsy-she and @ChristopherRiedel tested this on test-de1 and test-de2 (nightly). The DefaultUserRoles (like admin or national doc) still have the rights SORMAS_TO_SORMAS_SHARE and SORMAS_TO_SORMAS_PROCESS. The rights should be removed from the DefaultUserRoles.

@SahaLinaPrueger I think there was a misunderstanding here. As I have already written: 

>  This then means that on all instances (development, test and production) there will be no more users that can use Sormas2Sormas until someone manually reassigns these rights in user role management.

What we have implemented now is that on new instances there is no user role that has S2S privileges. The corresponding rights have been removed from DefaultUserRoles.
Because the DefaultUserRoles are only a definition in the code (enum), which become UserRoles in the database when the instance is set up.
It is not possible in the previously suggested way to revoke S2S rights only from users on instances without S2S without doing the same for all instances with S2S.

Apart from that, test-de1 and test-de2 are both instances with S2S and should definitely contain the S2S rights.

**Comment by SahaLinaPrueger** [comment]
@ChristopherRiedel and @leventegal-she 

> It is not possible in the previously suggested way to revoke S2S rights only from users on instances without S2S without doing the same for all instances with S2S.

Okay, then we have to revoke S2S rights from all users on all instances. 

(I thought the solution you came up with would be to take the rights away from everyone, but on the instances that already use s2s, the users with the corresponding s2s rights would automatically get a new role that only includes the s2s rights, or something like that. But i was also a bit surprised that this could be made possible. Glad we cleared up that misunderstanding. Please remove the rights as described and I will notify the four S2S-piloting-health-departments, so they can prepare for the update.)

AND as described in 8.1 (Q&A about the user roles) we have to make sure, that the point
> This will also affect existing user roles linked to the default user role.

will be fulfilled.
![image](https://user-images.githubusercontent.com/100844689/192305800-531a2c5f-ddad-46b2-ad72-130c6eedcace.png)

**Comment by SahaLinaPrueger** [comment]
@leventegal-she @ChristopherRiedel 
if you only give the rights 'S2S Process' and the right 'S2S Client' the user can still see the 'share box' with the explanation 'failes to load shares'
![image](https://user-images.githubusercontent.com/100844689/193085200-1ac31fe6-5727-4913-a213-39aa53e13057.png)
I think the user could get confused by reading the word 'failed'. Is it possible to just not show the 'share box' as when none of the S2S rights are given:
![image](https://user-images.githubusercontent.com/100844689/193086405-2b9aab6f-aac1-41ac-a3ac-7c7007b5d196.png)

If this is not possible, can you please change the text and write: _you do not have the right to share data_ ?

**Comment by SahaLinaPrueger** [comment]
@leventegal-she and @ChristopherRiedel 
if you only give the rights 'S2S_Share' and the right 'S2S Client' the user see the 'share box' with the explanation 'failed to load shares' but can share successfully. This is also confusing, can you please delete the text _failed to load shares_ ?
![image](https://user-images.githubusercontent.com/100844689/193087792-8a40848e-dacb-4cb4-857d-92219bcc29ec.png)

And if the user shares data successfully after that the 'share box' does not show the comment, the status and so on. Can you please make the share box visible for the users with the right 'S2S_Share' ? This is also important because the user needs the possibility to revoke the share. Thank you.

For better understanding: This case is already shared:
![new right s2s process](https://user-images.githubusercontent.com/100844689/193090359-6c422c11-15e8-4adf-9e4d-8ab9f262618f.gif)

**Comment by SahaLinaPrueger** [comment]
Additional information: For contacts everything works as it should. 
With right 'S2S_Share' (and S2S Client) the share box shows at the beginning: 'This contact ist not shared' and after sharing all the needed information, you can revoke successfully and so on.
With right 'S2S_Process' (and S2S Client) you cannot see the share box.

**Comment by SahaLinaPrueger** [comment]
I have two more points, but then I am done with this Issue:
1. If you only give a user the right 'S2S_Process' you can accept and reject a share but you cannot revoke. That is wonderful. The point is: You still see the button 'revoke' in the share directory and if you click the button an error message appears. If you do not have the right to revoke the button should not be visible or greyed out.
2. 'S2S_Share' includes the right to initiate a share for a case/contact. So the button 'share' is clickable. The right to view the box should be included in the right View_Case, View_Contact, View_Event participant, View_Travel entry

**Comment by leventegal-she** [comment]
The user with `S2S_Process` right does not have With Ownership/View only filters.

With Ownership/View filters should be visible for all users regardless of user rights, it should only depend on the feature configuration

**Comment by SahaLinaPrueger** [comment]
> The user with S2S_Process right does not have With Ownership/View only filters.
With Ownership/View filters should be visible for all users regardless of user rights, it should only depend on the feature configuration

@leventegal-she Can you explain what do you mean by that?

**Comment by leventegal-she** [comment]
@SahaLinaPrueger I meant the filter added with https://github.com/hzi-braunschweig/SORMAS-Project/issues/9787 was not visible only for the users that had S2S_SHARE right. But it should be visible for any user as long as s2s is configured on the system similarly to the share box like you commented here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/10084#issuecomment-1263238587

**Comment by dragosb-vg** [comment]
Validated on **test-de3**, Version: 1.77.0-SNAPSHOT ([ba98b49](https://github.com/hzi-braunschweig/SORMAS-Project/commits/ba98b49111ac573e8d39f4c856b042f066b018be))
Tested all 'S2S_Process' - 'S2S_Share' rights combination on test-de-3 (with pending/accepted/revoked share requests to & from test-de1)
