### ISSUE TITLE
Automatic archiving of cases & events [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1008]
We need to define the rules that should be used to automatically archive cases with their associated contacts and samples.

A guess from my side would be something like "case has an outcome and was not edited for the last 6 weeks". In combination we would probably need a way to remind users of cases that haven't been touched for some weeks and are missing an outcome.

Please discuss this. The same question goes for events.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] automatically archive every case that has not changed for 10 weeks
- [ ] add a hint to the cases directory (only display the hint when archived cases are displayed)
- [ ] same for events

**Comment by ChristopherRiedelSymeda** [comment]
feature is on featurebranch and has to be merged after code review

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] change < in cron jobs to >=
- [ ] inline lines 786-790 in CasesView / EventsView
- [ ] remove `@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)` for getTempFilesPath

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Change default period to 90 days
