### ISSUE TITLE
User Roles - Notifications text hidden by checkbox

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#10081]
### Bug Description

While creating a new user role, in German language and open the tab notifications, the text is hidden by the checkbox.

![image](https://user-images.githubusercontent.com/78568406/183655734-04fc7a2f-f0fb-4b0b-8419-5901d67928d4.png)

### Steps to Reproduce

1. open user roles notifications
2. select language german

### Expected Behavior

The full text should be visible.

### System Details

* Device:
* SORMAS version: 1.75 snapshot (https://github.com/hzi-braunschweig/SORMAS-Project/commits/cea6a2f735f775d578389686e457977e7c6dcbbd)
* Android version/Browser:
* Server URL:
* User Role:

**Comment by abrudanancuta** [comment]
Validated on the local env with the version: 1.75.0-SNAPSHOT (d312652)
