### ISSUE TITLE
User Role and Rights - A pop-up warning appears for user when changing jurisdiction from Community to None for a used role

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10093]
### Bug Description
A pop-up warning appears for user when changing jurisdiction from Community for a used role

### Steps to Reproduce
1. Have a role created on the jurisdiction level set to Community
2. Use the role above for a user => at this point on the user edit form, the  dropdowns related to jurisdiction appear to be mandatory
3. Go to Role from step 1 and change his jurisdiction to None
4. Go to user from step 2 and remove the jurisdiction from the dropdown and let them empty
5. Save the user
6. Click yes for the next pop-up which is an information

### Expected Behavior
The warning error should not appears, and the user should be saved 

### Screenshots

<img width="768" alt="Screenshot 2022-08-10 at 16 45 27" src="https://user-images.githubusercontent.com/91872179/183933046-77ab88e4-73b3-44dd-bcad-90796862cbcd.png">

### System Details

* Device:
* SORMAS version: 1.75.0- snapshot
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

[Uploading ErrorRoleChange.txt…]()

**Comment by leventegal-she** [comment]
@abrudanancuta 
Could not reproduce on local environment and on https://test.sormas.netzlink.com/sormas-ui

**Comment by abrudanancuta** [comment]
The issue cannot be reproduced. A fix could have been committed from this ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/9645
