### ISSUE TITLE
Fix invalid path in local bean-test artifact

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#10101]
### Problem Description

#9960 introduced a local bean-test artifact because the public repository got shut down. The last commit in that issue fixed an issue with the path in the local IDE which unfortunately broke the build in Jenkins and therefore got commented.

The actual problem is the following warning received when executing maven on sormas-base, e.g. validate

> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for de.symeda.sormas:sormas-widgetset:jar:1.76.0-SNAPSHOT
> [WARNING] 'dependencyManagement.dependencies.dependency.systemPath' for info.novatec:bean-test:jar should not point at files within the project directory, ${project.basedir}/../sormas-base/dependencies/bean-test-0.2.Final.jar will be unresolvable by dependent projects @ de.symeda.sormas:sormas-base:1.76.0-SNAPSHOT, C:\workspaces\SORMAS\sormas-base\pom.xml, line 798, column 17
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for de.symeda.sormas:sormas-serverlibs:pom:1.76.0-SNAPSHOT
> [WARNING] 'dependencyManagement.dependencies.dependency.systemPath' for info.novatec:bean-test:jar refers to a non-existing file C:\workspaces\SORMAS\sormas-base\dependencies\..\sormas-base\dependencies\bean-test-0.2.Final.jar @ de.symeda.sormas:sormas-base:1.76.0-SNAPSHOT, C:\workspaces\SORMAS\sormas-base\pom.xml, line 798, column 17
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for de.symeda.sormas:sormas-base:pom:1.76.0-SNAPSHOT
> [WARNING] 'dependencyManagement.dependencies.dependency.systemPath' for info.novatec:bean-test:jar should not point at files within the project directory, ${project.basedir}/../sormas-base/dependencies/bean-test-0.2.Final.jar will be unresolvable by dependent projects @ line 798, column 17
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING] 

### Proposed Change

Try to find a workaround OR ignore the warning - #10074 will likely lead to a replace of bean-test anyway.

**Comment by JonasCir** [comment]
This broke a clean build of the S2S-Testbed as well...

**Comment by MartinWahnschaffe** [comment]
@StefanKock See updated description. What's your opinion?

**Comment by MartinWahnschaffe** [comment]
Ok. We will have to live with the warning for now. Closing this.
