### ISSUE TITLE
'Campaign data' forms added to a campaign in the mobile app are not synced

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10106]
### Bug Description

If a new 'Campaign data' form is added to a campaign in the mobile app, its synchronization to the web app is not successful, as the user is informed that some data could not be synchronized. If the user does a synchronization from the 'Re-Synchronize Data' button in 'Settings' the newly created form is not saved anymore in the mobile app either.

### Steps to Reproduce

1. In the mobile-app, log in with a Surveillance Officer and navigate to the 'Campaigns' directory;
2. For an existing campaign, click the '+' button in the 'Campaign Data Listing' tab;
3. From the 'Select Campaign Form' pop-up, select a form;
4. In the 'New Campaign Data' form, fill in the mandatory information and save the form;
5. Trigger a synchronization with the server.

### Actual Behavior

The synchronization is not entirely successful as the user is notified that some entities could not be synchronized.
![image](https://user-images.githubusercontent.com/96909231/184119060-f11b8d0d-8000-47c0-9761-d1b186f11856.png)

If a synchronization is triggered from the  'Re-Synchronize Data' button in 'Settings' the newly created form is not saved anymore in the mobile app either.

### Expected Behavior

The synchronization should be successful and the new 'Campaign Data' form should be synchronized to the web app.

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.75.0-SNAPSHOT(d312652)
* Android version/Browser:  Chrome (vaadin-app); Android 11 (android-app)
* Server URL: local machine
* User Role: Surveillance Officer

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe Do you know why we have a creation form and an edit form that are enabled in the mobile app in the first place? There aren't even push endpoints in CampaignResource, and the synchronization logic in the mobile app also doesn't include campaigns (obviously, since there are no endpoints).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest SORMAS version from the development branch - 1.76.0-SNAPSHOT(2fd8529).

**Comment by zohaibhassan122** [comment]
Hi @adinaflorea9,
Can you please help me to understand this issue? and how I can test this if I want to confirm if this issue is fixed?
Feel free to write me a direct message/email.

**Comment by adinaflorea9** [comment]
Hi @zohaibhassan122! Sorry for getting back to you so late.

I will write what the necessary configurations are and some of the steps here, as I seem to not have your email address. 

Unfortunately, from what I remember, or at least from what I have seen in the testing instances that I know about, the 'Campaigns' directory is not enable on them.

First, the necessary configurations to have 'Campaigns' on a testing environment:
- these changes and SQL queries have to be made in the Data Base of the testing environment that you wish to use;
- the file from below contains the steps, queries and data that you need to enable the campaigns:
[Configurations necessary for campaign forms.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10076258/Configurations.necessary.for.campaign.forms.txt)

- after the steps from the file above are successfully completed, you should be able to see in the vaadin-app the 'Campaigns' directory if you are logged in with a user that has rights for that (for example and Admin+National User).
Secondly, in order to create campaigns and the forms and diagrams associated with each campaign:
1. In the 'Configuration' directory, go to the tab 'Areas' and create a new area;
2. In the same directory, in the ''Regions' tab - select the region that you want to be in the area created at step 1;
3. Then in the 'Campaigns' directory, go to the third tab called 'Campaigns';
4. Click on 'New Campaign' and fill in the mandatory information and also add the form and chart(aka the diagram) - the GIF below shows the exact steps:
![Create campaign](https://user-images.githubusercontent.com/96909231/203569710-638312d4-56ac-41ee-b002-3bea799104d3.gif)

5. Then navigate to the 'Campaign data' tab;
6. From the first filter right at the top, make sure that the campaign that you want is selected;
7. Then click on 'New form' - and select Form 1;
8. Fill in the mandatory information as in the GIF below:
![Form fill in](https://user-images.githubusercontent.com/96909231/203570567-dd707efe-c786-4baa-99ed-8310b3b7ad68.gif)

9. If you would also like to see the information from the diagram that was created based on the data from your campaign form - navigate to the 'Dashboard' directory - from the top select 'Campaigns' - and from the filters choose the values that indicate your campaign such as the name of the campaign, the area that you inputted in your form, or the region and district.


Then for the second part, the mobile app:
- in the mobile app, a Surveillance Officer user should have the necessary user rights to see campaigns;
- then the steps to reproduce from the ticket above should lead to the expected behavior written in the ticket.

If there is anything else that is perhaps unclear, or if the information provided here needs more details, please let me know and I will try to help.
