### ISSUE TITLE
Detailed export of samples

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1010]
Based on the request of #909 

- [x] include all fields of the current sample export
- [x] add columns for case: name, age, sex, address, ID, EPID number, date of report, classification, outcome, region, district, community, health facility
- [x] for each pathogen test add the following columns: type of test, date and time, laboratory, result, verified by lab supvervisor. Add numbers to the column name, starting with 1. This will be done for a maximum of 3 tests. If there are more test they are merged into a single column
- [x] export one additional test (one column per field). If there are more than merge all of them into a single column

@hzi-braunschweig Please have a look at my suggestions.

1. Is there anything else needed for the case or person of the sample?
2. Is the way pathogen tests should be exported ok?
3. How should additional test results be exported? Should we export all the fields and also add numbers? This would become a lot of fields.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
1. Is there anything else needed for the case or person of the sample?
I think this is ok for now
2. Is the way pathogen tests should be exported ok?
Yes
3. How should additional test results be exported? Should we export all the fields and also add numbers? This would become a lot of fields.
Yes please ecport all fields with numbers. It would be alot of fields. Thanks

**Comment by MateStrysewskeSym** [comment]
- [ ] split case name
- [ ] include tested disease in "Other pathogen test results" column
- [ ] Add "of latest additional test" to all additional test headers
- [ ] Only display whether there are more additional tests in the "Other additional tests" column
- [ ] Add question marks to Boolean columns
- [ ] Rename pathogen test columns to "Latest pathogen test", "2nd latest pathogen test" and "3rd latest pathogen test"
