### ISSUE TITLE
ERROR: update or delete on table "eventparticipant" violates foreign key constraint "fk_samples_associatedeventparticipant_id" on table "samples"

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10113]
### Bug Description

Error displayed and the deletion job is not successful as 'update or delete on table "eventparticipant" violates foreign key constraint "fk_samples_associatedeventparticipant_id" on table "samples"'.

### Steps to Reproduce

1. Create an event participant for an event that has the disease Covid-19;
2. Add to the event participant a sample for Covid-19 (with a positive test result) and create a resulting Covid-19 case;
3. In the DB - update the 'creationdate' of the event participant (to fit within the deletion period).
4. Wait for the deletion job to run.
 
### Actual Behavior

Deletion job is not successful. Error is displayed:
![image](https://user-images.githubusercontent.com/96909231/184153821-520aacd7-18e2-4330-b801-f5a70e3484a5.png)

### Expected Behavior

Deletion job should be successful.

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(d312652)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser
 
### Additional Information

Logs from the local machine:
[event participant.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9309360/event.participant.txt)

#7930 - observed while testing; created a separate ticket as #7930 is from Sprint 118.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.75.0-SNAPSHOT from the development branch (68389ec).
