### ISSUE TITLE
[DEMIS2SORMAS] When mapping of external ID's fail, choose "other facility"

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10119]
### Problem Description

With #8949 we improved the mapping for the external id's of organizations. 
if no matching id is found, nothing is selected. the field remains empty.
### Proposed Change

however when there is no matching id in the list of organizations the system should choose "other facility" as a standard.
because then the content of the demis message is adapted.

![image](https://user-images.githubusercontent.com/96547924/184352694-4ffdd374-eaac-4f79-a6dc-9d29ebc358aa.png)

### Additional Information

test14.02.sormas.netlink.com
user:admin
adapter: 1.19.0

as i have now noticed, this behavior was specified in #8949. so i have now labeled it as a bug

**Comment by ChristopherRiedel** [comment]
Fixed with this PR: https://github.com/hzi-braunschweig/SORMAS-Project/pull/10141#event-7197108644

**Comment by abrudanancuta** [comment]
Validated together with @FredrikSchaeferVitagroup on his local environment
