### ISSUE TITLE
The missing reporting user validation is not triggered for creating Event

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10110]
### Bug Description
The missing reporting user validation is not triggered for creating Event

### Steps to Reproduce
1. Make a POST for the endpoint to created event( env_url/sormas-rest/events/push)
2. In the body of the request don't add the attribute : reporting user 
[
    {
        "eventTitle": "JustFromAPI",
        "eventLocation": {
            "uuid": "e8ed5a4e-c5af-4ef9-ac6f-3004f2c4eba8",
            "pseudonymized": false,
            "region": {
                "uuid": "XD5CCG-2K2NRA-E7VK75-ME622CX4",
                "caption": "First Region"
            }
        },
        "eventStatus": "EVENT",
        "eventInvestigationStatus": "PENDING",
        "reportDateTime": 1653385889240
    }
]

### Actual Behavior

The request responds with the status code 200 and response body
[
    "TRANSACTION_ROLLED_BACK_EXCEPTION"
]
### Expected Behavior

The request should responds with the status code 400 and response body
"Invalid data",
    "errors": {
        "reportingUser": "You have to specify a valid user from the SORMAS database"
    }

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by JonasCir** [comment]
Ok cause is simple, cleaning this up such that this will not happen again (i.e., also for other entities) will take a little bit of time. 

The root cause is that we simply do not call the validate method when saving. I'm looking for a way to ensure that our custom validation logic runs unconditionally

**Comment by abrudanancuta** [comment]
Validated on test.de with the version 1.76.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/e586c0e11f8525c96f1dbd1a45ec23817463566f)
