### ISSUE TITLE
S2S_ no update of share box in System A after sharing back

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10127]
### Bug Description

After sharing back a case / contact from system B to system A the share box in system A does not get updated. The message is still: "Shared with: System B  - Shared by: user - On: date - Status: Accepted"
### Steps to Reproduce

1. System A: create a case / contact and share it to System B with hand over the ownership
2. System B: accept the case /contact
3. System B: open the case / contact and check the share-box 
   (should include the message: "sent from system A - shared by: user - on: date" )
4. System B: share the case / contact back to system A 
5. System A: accept the case / contact
6. System A: check the share-box 

### Expected Behavior

Step 6: The share box in System A should be updated with the message "sent from system B - shared by: user - on: date"
### Screenshots

on the right side: System A - on the left side: System B
![S2S_no update of share box in System A after sharing back](https://user-images.githubusercontent.com/100844689/184613666-106d765a-19ef-493e-b29b-b7aee79b4abc.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.74.1
* Android version/Browser: Edge
* Server URL: 1402
* User Role: admin

### Additional Information

Maybe fix of #9785 can be helpful to fix this one but idk because change is triggered on a different place in this issue so quite different

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by leventegal-she** [comment]
The case/contact is originally created in System A, so handing back the ownership from B does not mean that on System A is sent from B. It remains shared with B because it remains shared with B, but the owner of it will be System A.

I don't think this is a bug. 

If the the expected behaviour is needed, we need a change request and we have to refine it.

**Comment by SahaLinaPrueger** [comment]
I understand your point. You say the information itself is not wrong, therefore it is not a bug.

Even if the behaviour of the share-box when accepting a case is not the same as when the case is accepted for the first time in a system, the information itself is correct.

I am only worried, that the health departments will think with the current share box, that they shared the case only one time with "no hand over the ownership". They can not see, that the case is shared back. But in principle the effect is the same, system b only has the case for viewing.
And unfortunately with the solution i described the system A will not see, that they shared the case yet one time. So with both solutions information get lost. 

We want to renew the share-box anyway, so let's leave it as it is. If the health authorities are confused, they will get back to us.
