### ISSUE TITLE
Lazy loading for case directory view

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1012]
After migration to Vaadin 8 legacy mode (#802).

- [x] facade methods need to be extended with range parameters (first and count) and sorting parameters
- [x] replace containers with new lazy vaadin 8 container: https://vaadin.com/docs/v8/framework/datamodel/datamodel-providers.html#datamodel.providers
- [x] update grid selection https://vaadin.com/docs/v8/framework/datamodel/datamodel-selection.html#datamodel.selection

Later this also needs to be done for contacts, events, tasks, samples and infrastructure lists.

**Comment by MateStrysewskeSym** [comment]
- [ ] grid export is missing
- [ ] count for filters in cases view is missing
