### ISSUE TITLE
[Events] 'Event Participants' tab is editable when an event is archived and EDIT_ARCHIVED_ENTITIES = false

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10120]
### Bug Description

When 'featuretype' EDIT_ARCHIVED_ENTITIES is set to 'false', archived entities should be red only (not editable).

The 'Event Participants' tab of archived events is currently editable when an event is archived, and 'featuretype' EDIT_ARCHIVED_ENTITIES is set to 'false'.

### Steps to Reproduce

1. In the DB, make sure that the 'featuretype' EDIT_ARCHIVED_ENTITIES is set to 'false';
2. In the UI, open an active event and archive it;
3. Navigate to the 'Event Participants' tab of the event from step 2.

### Actual Behavior

The 'Event Participants' tab is editable.

### Expected Behavior

The 'Event Participants' tab is not editable (is read only) when an event is archived and EDIT_ARCHIVED_ENTITIES = false

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(b836888)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

#9741

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.75.0-SNAPSHOT from the development branch (68389ec).
