### ISSUE TITLE
Aggregate reports do not disappear immediately from the grid once they are deleted

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10128]
### Bug Description
Recently deleted aggregated reports do not immediately disappear from the list; they disappear only after a refresh.

### Steps to Reproduce

1. Navigate to the mSERS directory, and select the 'Report Data' tab;
2. Click on the Edit icon of one of the entries of the grid;
3. Click on the delete button and Save;

### Expected Behavior
The aggregate report should disappear immediately from the grid.

### Actual Behavior
The aggregate report disappears only after a refresh.

### Screenshots

![aggregate report does not disappear instantly](https://user-images.githubusercontent.com/89522688/184623583-708be098-780f-43c5-91ef-fc90876ffbfb.gif)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.75.0-SNAPSHOT (a6ecbf1)
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
Similar to #10008

**Comment by MateStrysewske** [comment]
Likely the same issue as #10008, so I'll add a comment there and close this one.

**Comment by MateStrysewske** [comment]
Edited reports are also not updated immediately, but only after a refresh, see #10246.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(0c95d19).
