### ISSUE TITLE
[Hospitalization] entries should be locked if the button "no" or "unknown" is selected

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10129]
### Bug Description

if "no" or "unknown" have been selected, an entry is still possible.

### Steps to Reproduce

1.open a case
2. choose "hospitalization"
3. when clicking "no" or "unknown" you can still edit the fields below

### Expected Behavior

the fields should not be editable.
### Screenshots

![image](https://user-images.githubusercontent.com/96547924/184627707-545392de-622b-4a2d-9e4d-7b941c0cf647.png)

### System Details

* Device:
* SORMAS version: 1.74.1
* Android version/Browser:
* Server URL: test1402
* User Role: admin

**Comment by MateStrysewske** [comment]
@cmeyerhzi The entries are still supposed to be available, because even if someone wasn't admitted as an inpatient, they could still have been at the hospital for some time, including being submitted to the ICU or being isolated.
