### ISSUE TITLE
Missing filters in case directory

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10136]
### Bug Description

Depending on the logged in user, filters (show more filters) are missing.

For Example if the [Admin National User] is logged in the following filters are missing:
- Only cases with reinfection
- Only cases with fulfilled reference definition
 

### Steps to Reproduce

1.
2.

### System Details

* Device: laptop
* SORMAS version: 1.74.1
* Android version/Browser: Chrome
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Admin National User

**Comment by MateStrysewske** [comment]
@KernB I suppose that the international test server is not set up as a German server. These filters that you mentioned are only available on German systems. Please feel free to reopen this issue when I'm mistaken.
