### ISSUE TITLE
S2S_ duplicate detection does not function under certain circumstances

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10135]
### Bug Description

The duplicate detection does not function if you share a case (with hand over the ownership) to a target system and after that the same case is created.
### Steps to Reproduce

1. share a case X (person X) to a target system with hand over the ownership
2. Accept the case X (person X) on target system
3. create a new case Y (person Y) with the same data as case X (important: - create a new person, do not match the person ; - the responsible jurisdiction of the case X has changed by accepting on target system, so choose the same jurisdiction for case Y as case X has now after acceptance on target system)
4. Go to the case directory and click on "merge duplicates"
5. Click on button "Confirm filters"
6. Look if case X and case Y are mentioned (spoiler: they are not)

Please notice: If you first create case Y (person Y) on target system and then share/accept case X (person X) on target system the duplicate detection shows case X and case Y

### Expected Behavior

Case x and case y should be shown no matter if case y was created bevor acceptance of case x or after acceptance of case x.
### System Details

* Device: Windows 11
* SORMAS version: 1.74.1
* Android version/Browser: Edge
* Server URL: release-de and release-x
* User Role: admin

### Additional Information

Pls check behaviour for contacts and shares with **no** hand over the ownership, too.
Additional information: It is good, that the merge is not possible if the 'not-shared-case' is the leading case. This is not a bug

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by leventegal-she** [comment]
The cases doesn't appear in the merge view because when accepting a case and changing it's responsible district we keep the original district as place of stay district and therefore the system doesn't find it as duplicate because the newly created case does not have place of stay district or it does not have the same as the shared one.

**Comment by leventegal-she** [comment]
> Which solution would you like to implement?
We can't do option 1 because can't save a case with health facility not belonging to the responsible jurisdiction so we must keep the original jurisdiction as place of stay

Also option 2 is a very unintuitive solution

I don't think this is a bug because the place of stay must be set and also the search for duplicate merging works as requested at the time when it was implemented. So to make this kind of change we need a change request and it should be refined.

**Comment by SahaLinaPrueger** [comment]
_The cases doesn't appear in the merge view because when accepting a case and changing it's responsible district we keep the original district as place of stay district and therefore the system doesn't find it as duplicate_

What i do not understand. 
If i perform the following steps the duplicates can be detected: 
1. I create a case in the target system (release-de: responsible jurisdiction: Baden-Württemberg, LK Bodenseekreis)
3. I create a case in the source system (release-x: responsible jurisdiction: Niedersachsen, LK Leer)
4. I send the case from source system to target system and i accept the case on target system. The case changes his responsible jurisdiction automatically to Baden-Württemberg, LK Bodenseekreis)
5. Both cases can be merged

You described, that the shared case keeps the original district as place of stay district. Why does the system finds the duplicates in the steps described above?

**Comment by SahaLinaPrueger** [comment]
My idea would be to include the mechanism that ensures that the cases can be merged (see example in comment) also there when the case is created in target system after the shared case is accepted.

**Comment by leventegal-she** [comment]
> You described, that the shared case keeps the original district as place of stay district. Why does the system finds the duplicates in the steps described above?

It finds it because how the query for duplicates is implemented, when a case has a place of stay region then it checks the place of stay region of the other case to be the same and because the case without place of stay is created earlier the query doesn't check the region of the other case so it finds as a duplicate.

**Comment by SahaLinaPrueger** [comment]
Ah okay, so the duplicate detection is always based on the case that is first in the system.

**Comment by SahaLinaPrueger** [comment]
okay, because the decision should be well-considered, i push the issue into 1.76.

**Comment by SahaLinaPrueger** [comment]
> 1. Don't keep the original responsible jurisdiction (just deleting some code)
> 2. Modify the query for searching duplicates to don't check the place of stay jurisdiction for shared cases (making a complicated query even more complicated and loose a bit in performance)

@leventegal-she we @JaquM-HZI and @Jan-Boehme decided to go with option 1.
Just to clarify: 

Situation now: 
A case has a responsible region X and the _Place of stay of this case DO NOT differs from its responsible jurisdiction_ (so the checkbox is unchecked):
Source system
![image](https://user-images.githubusercontent.com/100844689/187664042-33b97e7f-f411-418b-8c94-8f05174f83e2.png)
 
Then the case will be shared to a target system (Traunstein) with hand over the ownership and in the target system the responsible region X will be shown as _Place of Stay_
Target system
![image](https://user-images.githubusercontent.com/100844689/187668410-788e7405-2558-4fcb-a8a2-68b52606f210.png)

Situation in the future:
target system after share:
just the responsible jurisdiction will be changed automatically to responsible district of target system system
checkbox _Place of stay differs from its responsible jurisdiction_ is unchecked 
![image](https://user-images.githubusercontent.com/100844689/187669334-0373fe4b-89fa-43a1-bb85-a23ceec12580.png)
source system after share:
same (because of sync) -  just greyed out

question 1: Is this correct?

question 2: 
source system bevor sharing:
Checkbox _Place of stay of this case differs from its responsible jurisdiction_ is checked AND the name of another system (Berlin Friedrichshain-Kreuzberg), which is NOT the target system (Traunstein), is filled in as _Place of stay_. 
![image](https://user-images.githubusercontent.com/100844689/187676250-9f4a6087-785e-4524-8957-b7a43a3b7d8a.png)

In the future the target system will take over/keep the checked checkbox _Place of stay of this case differs from its responsible jurisdiction_ AND also take over/keep the name of the system Y in the Place of stay (which is not the target system) 
**as it is currently already implemented**, right? So like this (target system Traunstein after share from source system (Alb-Donau-Kreis):
![image](https://user-images.githubusercontent.com/100844689/187676443-2cc3e7b9-210a-42be-8dbc-bb6e4f17aee7.png)

I ask this, because it is important that this behaviour stays as it is. 

question 3:
source system bevor sharing:
Checkbox _Place of stay of this case differs from its responsible jurisdiction_ is checked AND the name of the target system is filled in as _Place of Stay_. 
![image](https://user-images.githubusercontent.com/100844689/187675873-dbc545c5-2d71-44d7-82e9-e20e2d0a6879.png)

Can we implement that the target system checks if responsible jurisdiction and place of stay is the same and if so uncheck the checkbox.? Because if we do not implement this function and the source system will specify that place of stay differs and also specify the target system as place of stay, we will run in this case into the same situation as now, right?

**Comment by leventegal-she** [comment]
> question 1: Is this correct?
It will not work because the _Health facility_ of the case must belong to the district of the _Place of stay_ if given, otherwise it should belong to the _Responsible jurisdiction_

Not keeping the original jurisdiction and changing the _Responsible jurisdiction_ will result in an invalid case and the case cannot be saved.

> question 2
It is implemented as described

> question 3
Can be implemented, I think it will not have any side effect on the case. @MateStrysewske @MartinWahnschaffe am I right?

**Comment by SahaLinaPrueger** [comment]
@leventegal-she Question 1: Okay so how will the first option _Don't keep the original responsible jurisdiction (just deleting some code)_ will work then? Can you visualize it for me so I can understand? That would be great!
Or does your comment mean that option no. 1 is not feasible and we have to go with option 2?

**Comment by leventegal-she** [comment]
Not keeping the original jurisdiction would look like the image below.

_Place of stay of this case differs from its responsible jurisdiction_ not checked
_Berlin Hospital_ kept even if it's not in the region/district of the case
And trying to save the case fails with the error on the image screenshot

![image](https://user-images.githubusercontent.com/62599627/189619650-d8392562-63f0-46ac-8a92-096dfabf9445.png)

**Comment by SahaLinaPrueger** [comment]
@leventegal-she Can you describe to me how you created the condition? Because if you share a case the facility is currently marked as "other" in target system and the field "facility name and description" appears filled with the name of the facility. So it is not checked whether this facility actually exists in the target system or not.

**Comment by leventegal-she** [comment]
@SahaLinaPrueger I have _Berlin Hospital_ facility on both servers with the same external id

**Comment by SahaLinaPrueger** [comment]
@leventegal-she Okay, so what we want is that the code will be deleted except when a facility is involved. And we need to update the query of searching for duplicates. Both is a change, so i will discard this one and write a change request.
