### ISSUE TITLE
Mobile app crashes when try to change the language before logging in

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#10132]
### Bug Description

When I try to change the language, the mobile app crashes. 
### Steps to Reproduce

1. Install the new apk, and during the initial setup, try to change the language.

### Expected Behavior

It should change the mobile app language.

### Screenshots

https://user-images.githubusercontent.com/8872102/184634585-7e638526-4bab-4ee2-99e3-d80603279753.mp4

### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.74.1
* Android version: 1.74.1
* Android Version: 11
* User Role: Hospital Informant
* Server URL: https://test1402.sormas.netzlink.com/sormas-rest/
### Additional Information

Error Log
[langauge_Change_error_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9337133/langauge_Change_error_log.txt)

FYI: @MartinWahnschaffe , @MateStrysewske @bernardsilenou @BasilKaburi

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server https://test-de.sormas.netzlink.com/sormas-rest/

**Comment by zohaibhassan122** [comment]
When I set any other language than English during the initial setup, then after finishing the setup, App starts with the English language. It should start in the language which I choose during the initial setup.
Can we fix it? 
Screenshots are attached, please let me know if you need further information. 

FYI: @MateStrysewske @MartinWahnschaffe @bernardsilenou 

![Screenshot_20221019-155846_APMIS](https://user-images.githubusercontent.com/8872102/196719740-7aafe61f-3d34-4877-91eb-e0a9f6fd4caf.jpg)
![Screenshot_20221019-161646_APMIS](https://user-images.githubusercontent.com/8872102/196719747-f9fe6633-1d81-4eed-aa99-3fe8f7d59611.jpg)

**Comment by roxanamlendea** [comment]
@zohaibhassan122 This has been like that before #10132. This is because the user language is set to English (or default) in the web app, and the language change in the mobile app is not synced to the web app, so it gets overwritten at that point. 
It would be a change request and it's not related to this ticket.
