### ISSUE TITLE
Evaluate migration to Vaadin 10+ (flow) or Angular

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1014]
- [ ] list pros and cons of Vaadin 10
- [ ] Are there existing guides? What needs to be done?
- [ ] Create issues and a milestone concept
- [ ] consider #1026 and #1027

**Comment by bernardsilenou** [comment]
I suggest that we should put  is up ion the priority list as users in the field with  more than 500 cases on tablet has difficulties synchronizing because app takes long time to do so. Will the migration also improve the speed on tablet with poor internet connectivity?

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou 
No, this is not related to the synchronization.

Can you create an issue to discuss the users situation, please? I think this is an important example. Please give as many details as possible: Where those 500 cases created by the user? Over which time period? how many of those cases still need to be synchronized?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda the situation of 500 cases not synchronized is the one you sorted out. That is what @bernardsilenou was referring to. I need to give @gerardkrause the tablet to take to Nigeria to return it back to the user who had the issue. @Chinedar if you still have synchronization issues please do let @MartinWahnschaffeSymeda and @MateStrysewskeSym know....

**Comment by Chinedar** [comment]
@hzi-braunschweig the synchronization issue is primarily network related. In the absence of good network, the cases take too long to synchronize. 
@MartinWahnschaffeSymeda will this migration improve the import functionality? Currently, it takes a very long time to import cases (especially now there is a request for us to import all the cases of various outbreak data from states where SORMAS is yet to be deployed).

**Comment by MateStrysewskeSym** [comment]
@Chinedar I don't think so, no. Importing cases is a pretty complex process and I don't believe there's a way around it taking some time especially when large numbers of cases are imported at once.

Vaadin 10 has a lot of other benefits and quite a few built-in features that SORMAS might benefit from, like in-line data entry for tables which would allow users to rapidly create cases without the need of opening the case create form. Also, the web app's performance in general should benefit from it (e.g. switching between pages, responsiveness, things like that).

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda good to know the nice benefits of the Vaadin flow. Is there a way then to "dump" the historical data via the back-end? Seeing that this might be the only way to achieve having all the retrospective data in the database over and above the import process.

**Comment by JonasCir** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/1406 as well
