### ISSUE TITLE
[DEMIS2SORMAS] Laboratory is pre-filled

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10144]
### Bug Description

If the provided bsnr and demisLaboratoryId both match an external ID from existing facilities, i.e. laboratories. The laboratory fields should not be pre-filled, but they are.
### Steps to Reproduce

1. Upload a lab message that contains a bsnr and demisLaboratoryId in the Organization ressource which matches one of the external ID's
2. Fetch and process the uploaded message
3. Check the pre-filling of the laboratory fields

### Expected Behavior

If the provided bsnr and demisLaboratoryId both match an external ID from existing facilities, i.e. laboratories. The laboratory fields should not be pre-filled.
You can see the postman.file under "additional information". Maybe something is just wrong there. 

### Screenshots

![DEMIS_Lab is selected](https://user-images.githubusercontent.com/100844689/184930368-80f3da6e-d949-4bb7-a089-4c2aba086748.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.74.1
* Android version/Browser: Edge
* Server URL: 1402
* User Role: admin
* time: 08/16/ 2022 18:04-18:07

### Additional Information

Postman.file: 
[DEMISlab.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9352735/DEMISlab.txt)

labmessage.file:
[DEMISlab.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/9352759/DEMISlab.pdf)

log (application; syslog): i can pass them, if you need

Lab message on SORMAS
![image](https://user-images.githubusercontent.com/100844689/184930790-d9e9f1bb-cfcf-4e85-a113-f4e17b546c19.png)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by FredrikSchaeferVitagroup** [comment]
As discussed with @SahaLinaPrueger, this probably only has to do with how the identifier values are uploaded to the DEMIS server.
As there still are some things unclear, I will not (yet) provide a full explanation here, but close the ticket as invalid.
We will clarify with Gematik, and create another ticket afterwards (if necessary).
