### ISSUE TITLE
Person pages of persons associated only with an immunizations are read only

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10146]
### Bug Description

When a person is associated with only an immunization, the page of the person from the 'Persons' directory is read only.

### Steps to Reproduce

1. Enable the full immunization module;
2. Navigate to the 'Immunizations' directory and create a new immunization;
3. Navigate to the 'Persons' directory and search for the person create via step 2.

### Actual Behavior

The page is read only.

### Expected Behavior

The page should be editable (as long as the immunization is within the jurisdiction of the user logged in).

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(5663e12)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

#9997

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.75.0-SNAPSHOT from the development branch (68389ec).
