### ISSUE TITLE
Can't login using keycloak with newly created users

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#10155]
### Steps to Reproduce

1. Create a new user with admin role on test-de1
2. Try to login with the new user
=> Internal Server Error

### Expected Behavior

Should be able to login with the new user
### Screenshots

1. on test-de2
![Screenshot 2022-08-17 at 17 06 13](https://user-images.githubusercontent.com/62599627/185156356-2f95f6ca-6e64-49a6-96b5-cc144bbdc4e2.png)

2. on local env
![Screenshot 2022-08-17 at 17 08 51](https://user-images.githubusercontent.com/62599627/185156454-48cc295e-c02b-4fd2-bce3-8053dacf2dd5.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

Found while testing the new user roles functionality https://github.com/hzi-braunschweig/SORMAS-Project/issues/4463#issuecomment-1216461809

**Comment by JonasCir** [comment]
Ok keycloak 18.0.1 with recent development in testbed works.
I'll connect to test-de1

**Comment by JonasCir** [comment]
Ok everything seems to work fine on `test-de1` for me @dbe21?

Can you check again and provide me with a reproduction if something goes wrong?

**Comment by JonasCir** [comment]
ah can reproduce now...

**Comment by JonasCir** [comment]
`java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Hex from [Module "deployment.sormas-keycloak-service-provider-1.75.0-SNAPSHOT.jar" from Service Module Loader]`

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup together with Jonas during a Peer testing session.
Newly created user was able to log in

**Comment by abrudanancuta** [comment]
Validated on test.de1 with the version: 1.75.0-SNAPSHOT (a003252)

**Comment by JonasCir** [comment]
@dbe21 thank you :)

**Comment by HolgerReiseVSys** [comment]
I suspect this only happens when the password does not conform to the keycloak password requirements and the sormas-keycloak-service-provider is used as a fallback.
