### ISSUE TITLE
Information related to the 'Recovery' section of an immunization is not cleared

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10156]
### Bug Description

If the 'Means of immunization' for an immunization are updated, and the 'Recovery' section is no longer displayed, the information that was related to the 'Recovery' section is stored  and is displayed again (if the 'Means of immunization' is updated again).

### Steps to Reproduce

1. Create an immunization with the 'Means of immunization' set to 'Recovery';
2. On the immunization's page, in the 'Recovery' section fill in the information for: 'Date of first positive test result' and 'Date of recovery';
3. Save the changes;
4. Navigate to the main list of immunizations and observe the column 'Date of Recovery';
-> it is populated with the date set at step 2.
5. Navigate back to the immunization's page, and update the 'Means of immunization' to 'Vaccination';
6. Navigate back to the main list of immunizations and observe the column 'Date of recovery';
-> it is still populated with the date that was set at step 2.
7. Navigate again to the immunization's page and change the 'Means of immunization' to 'Recovery';
8. Observe the 'Recovery' section.

### Actual Behavior

The information that was inputted in the section 'Recovery' of the immunization remains stored and it is displayed both on the immunization's page and in the main list of immunizations - column - 'Date of recovery'.

### Expected Behavior

The information that was inputted in the section 'Recovery' of the immunization should be cleared (both on the immunization page and in the main list of immunizations - column 'Date of recovery') when the 'Means of immunization' is updated and the page no longer displays the section ''Recovery'.

### Screenshots

GIF of the steps to reproduce:
![Recovery](https://user-images.githubusercontent.com/96909231/185157181-60b46f42-e21c-4fdf-aac4-50788e793826.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(5663e12)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because of the following bug:

1. Create an Immunization with the 'Means of immunization' = 'Recovery'; 
2. Set the 'Date of first positive test result' and 'Date of recovery'; Save.
3. Now update the 'Means of immunization' to 'Vaccination';
4. Change the 'Means of immunization' back to 'Recovery';
-> An error is thrown.
![image](https://user-images.githubusercontent.com/89522688/190166388-495a2466-029f-41d3-a91d-6357738f2380.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT (ee60af7) from the development branch.
