### ISSUE TITLE
Event Participants can be added for an archived Event via Import even if EDIT_ARCHIVED_ENTITIES = false

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10165]
### Bug Description
When 'featuretype' EDIT_ARCHIVED_ENTITIES is set to 'false', the user shouldn't be able to add new Event Participants. However, the user can do that by importing them.
The user can also Export the list of Event Participants.

### Steps to Reproduce

1. In the DB, make sure that the 'featuretype' EDIT_ARCHIVED_ENTITIES is set to 'false';
2. In the UI, open an active event and archive it;
3. Navigate to the 'Event Participants' tab of the event from step 2 and click on Import;
4. Upload a suitable document and click on Start Data Import;
5. Also click on Export;

### Expected Behavior
The 'Import' and 'Export' buttons should be read only in the first place;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/185419269-a3a36ed8-5381-4209-997f-115f43ccc193.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.75.0-SNAPSHOT (68389ec)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Admin, National User

### Additional Information
This bug was found while testing ticket: #10120

Note: can not document an earlier version as on the release testing instances the current version is now 1.75.0. But the issue was reproducible on the earlier versions as the header of the 'Event Participants' tab was not taken into account when the archiving of the event was done.

**Comment by StefanKock** [comment]
This ticket somehow contradicts #9852 to directly create archived event participants for archived events

**Comment by roxanamlendea** [comment]
@StefanKock In my user flow, EDIT_ARCHIVED_ENTITIES = false, in #9852 EDIT_ARCHIVED_ENTITIES = true, so I don't this they are contradicting.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT (21cbfe3) from the development branch.

**Comment by roxanamlendea** [comment]
Reopening the ticket because the 'Bulk Actions' button is no longer enabled in Bulk Edit Mode (the event is not archived).
![image](https://user-images.githubusercontent.com/89522688/195034709-e999db07-daf7-4fd9-9662-7e2aac8289e8.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.76.0-SNAPSHOT (c76bbe1).
