### ISSUE TITLE
Full database export appends the case to case_symptoms [1]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1016]
This may happen with the other files as well.

**Comment by MartinWahnschaffeSymeda** [comment]
It's not possible to do this based on the mechanics we are currently using. In addition I don't think it's a probablem to have this duplicate column.

**Comment by MartinWahnschaffeSymeda** [comment]
Misunderstanding clarified. We need to remove the case columns from the export of the symptoms, epi data, etc. tables. The goal is to make it as easy as possible to merge all those tables into a single one.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] filter symptoms (etc.) by case, instead of joining
- [ ] add therapy, treatments and prescriptions
- [ ] add clinical course with clinical visits
