### ISSUE TITLE
SORMAS NIGERIA SERVER VERY SLOW AND CRASHING!

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1017]
@MartinWahnschaffeSymeda @MateStrysewskeSym @bernardsilenou 
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /sormas-ui/.

Reason: Error reading from remote server

Apache/2.4.18 (Ubuntu) Server at sormas.org.ng Port 443

**Comment by hzi-braunschweig** [comment]
@Chinedar You guys should sit with the NCDC team to decide what cases to archive especially from 2017 and 2018.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Right now the server looks fine (besides the known performance problems of the cases directory). Do you know if something happened that could have lead to the error?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Looks like opening a task for editing takes really long. I think we should create a list of operations that are currently slow. This should help us to find performance issues.

**Comment by MartinWahnschaffeSymeda** [comment]
See #1032

**Comment by faatihi** [comment]
Ghana has started facing same "Proxy Error" issue. 
It's been three weeks and this error occurs at least once nearly everyday. 
We get the server back online by restarting sormas domain.

@hzi-old do you still face this issue?

**Comment by faatihi** [comment]
One observation:

When server is fine and I run:

`curl localhost:6080/sormas-rest/`

I receive:

`HTTP Status 401 - Unauthorized`

which is expected.

However, when this issue occurs and I run same command, I get

`curl: (56) Recv failure: Connection reset by peer`

**Comment by Chinedar** [comment]
@faatihi @bernardsilenou 
try the following...
1) increase ram size (we had this issue with a particular build, whereby every time-out instance sent heartbeats to the server every 2secs, hence clogging apache server)
3) you may want to update to the recent version and see if this is solved 
4) share a screenshot of your apache error and access log

**Comment by MateStrysewskeSym** [comment]
@faatihi Is this still an issue with the newest hotfix?

**Comment by faatihi** [comment]
@Chinedar thanks for the hints. we've increased ram size and updated to recent version.
Things look faster now, especially on the web.

We'll monitor over the week to see if the "Proxy Error" occurs again.

**Comment by faatihi** [comment]
Unfortunately, we still face this issue.
It's not regular as it used to be.
It has happened three times last week.
Twice on Friday evening (at 10 minutes apart), and once on Saturday evening.

**Comment by faatihi** [comment]
I would like to share the server logs, but nothing is logged during the downtime, except for warnings of "sending sms to person without phone number" and "sending email to person without email address".

**Comment by faatihi** [comment]
[ghsurveillance.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4813052/ghsurveillance.zip)

log from apache web server

**Comment by faatihi** [comment]
Please find below, payara's log for 2020-06-24 to 02:20 AM.

[server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/4824724/server.log)

You may search for **[2020-06-24T02:15:16.463+0000]**
That's the last request payara logged before becoming non-responsive.

**Comment by faatihi** [comment]
The server is much stable now.

We did the following:
1. Increased RAM size to 24 GB
2. Increased processor cores to 8
3. Added a background shell script to regularly monitor server for "Proxy Error".
    When error is encountered, the script restarts payara and logs the event.

With these in place, the script has logged two events in these two weeks:-
on 2020-06-24 02:18 AM GMT and on 2020-07-01 10:30 AM GMT.

**Comment by MateStrysewskeSym** [comment]
@faatihi That's a very good idea. We'll continue to try to improve the backend speed and error handling.
