### ISSUE TITLE
Trigger duplicate aggregate report immediately after user selection

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#10174]
### Bug Description

#9039 prevented the creation of duplicate reports. When a national user selects a week that has a report already, they are warned immadielay and provided the option to edit the existing report, this is as expected.
For an informant, the facility is automatically selected, thus pop um message only shows after the creation form has been filled. thus not consistent. 
If the informant saves an empty form, the existing data is replaced by null values
### Steps to Reproduce

1. Connect to web app with informant account
2. create a report for the current week and save
3.  create another report for the same week and provide no entry on the form and save + choose `Edit report` in the pop up message
4. existing data is replaced with null data
5. Repeat 1 to 4 using a national user, the experience is not the same

### Expected Behavior

* Duplicate records are non-zero records, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/9039#issuecomment-1118468629 Thus empty records should biot be considered.  This would prevent the situation of overriding existing records with emty records.
* If there is a report for the user selection, immediately show pop-up + option to edit an existing report, not after the user has entered some values and click safe.
* Another option is for users whose jurisdiction are hard codes in filters like hospitals informant, we can directly present the duplicate data in the edit  to the user.
### System Details

* Device: web
* SORMAS version: 1.74.1
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/#!about
* User Role: hospital informant

**Comment by adinaflorea9** [comment]
@bernardsilenou the behavior that you describe in this ticket was logged by me as a comment: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9039#issuecomment-1180188156

Please note that you mention here that you have tested on release-international where SORMAS version is currently 1.74.1; ticket #9039 that you have referenced here is part of 1.75.0 which has not yet been released; therefore those changes are not on release-international currently.
