### ISSUE TITLE
Error message is displayed when a user tries to access the 'Cases' directory

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10189]
### Bug Description

An error message 'A problem has occurred' is displayed when a user that has the right 'View existing cases' enters the 'Cases directory'.

### Steps to Reproduce

1. Logged in with an admin, create a new user role (use the 'Admin' template + Jurisdiction level 'Nation');
2. When creating the user role clear the following user rights: 
- General: 
*create new quarantine orders;
*perform bulk pseudonomization;
*perform bulk operations in lists;
- Dashboard: - everything;
- Case Surveillance: - everything;
- Case Management: - everything;
- Port Health: - everything;
- Contact Surveillance: - everything;
- Follow-up: 
*edit existing visits;
*create new visits;
*export visits from SORMAS;
- Samples: - perform bulk operations on case samples;
- Statistics: - everything;
- Export: - everything;
- External Systems: - everything;
And add all of the user rights from the section 'Data protection'.

3. Save the new user role;
4. Create a new user with the user role created after step 3;
5. Log in with the user created at step 4 and observe the displayed directories;
6. Log in with the admin that was initially logged in at step 1;
7. Update the user role created after step 3 and add the following rights: 
*view existing contacts;
*create new contacts;
=> the system will automatically also add the 'view existing cases' right (as viewing and creating contacts is dependent on viewing cases);
8. Save the changes, log back in with the user created at step 4 and observe the directories displayed;
9. Click on the 'Cases' directory.   
           
### Actual Behavior

An error message is displayed in the UI and in the server logs:
![image](https://user-images.githubusercontent.com/96909231/186154468-73708c72-5d37-4ba0-bcf5-e1bb4824df1e.png)

Logs from the local server:
[Logs error cases.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9402400/Logs.error.cases.txt)

### Expected Behavior

No error message should be displayed and the user should be able to see the cases that fall within their jurisdiction.

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(84fd6e7)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: can not specify an exact user role; the steps to reproduce describe how it was configured, which template was used and what changes were made to that template.

### Additional Information

If the Actual Behavior here is due to an invalid combination of user rights, it should be discussed if the user role selected for the user that reproducer the behavior should have been able to be saved in the first place or not. 
As when the specific configured user role is saved, there is no error or warning displayed. Therefore, the user that created it believes that they have created a valid user role.

**Comment by FredrikSchaeferVitagroup** [comment]
@adinaflorea9 Could you please try to reproduce this on the latest development branch? I can neither reproduce it myself nor trace the problem in the provided log.
