### ISSUE TITLE
mobile app issues: Symeda server properties showing on the field items on mobile app

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1018]
![WhatsApp Image 2019-03-22 at 12 03 32](https://user-images.githubusercontent.com/19344651/54819176-5a4abc80-4c9b-11e9-88c4-7ac12b11747c.jpeg)
@Chinedar @MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig As far as I can see only the login page is affected.
We will fix this in the sprint.
