### ISSUE TITLE
Some Database Tables are missing in the Database Export View [2]

### ISSUE THREAD

**Issue by FredrikSchaefer** [hzi-braunschweig/SORMAS-Project#10185]
### Bug Description

There are 69 database tables defined in the [DatabaseTable.java](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/java/de/symeda/sormas/api/importexport/DatabaseTable.java), those are available for export in the SORMAS UI. However, there are more than 69 (non history) tables in the SORMAS database, some of which (maybe even all) should be downloadable.

Missing are the tables

- campaign_campaignformdata (is already added)
- person_locations
- task_observer

The following tables are also missing and should be added:
- contacts_visits
- events_eventgroups
- campaign_campaignformmeta
- sharerequestinfo_shareinfo

### Steps to Reproduce

1. Try to download the aforementioned missing tables via the UI
-> it is not possible

### Expected Behavior

It was stated by HZI that some (or even all) of the missing tables should be downloadable via the UI [TBD]

### Acceptance Criteria
Extend the tests to check if all tables of this kind are exported

### System Details

* Device:
* SORMAS version: 1.75.0-SNAPSHOT
* Android version/Browser: Any browser
* Server URL: Any system
* User Role:

### Additional Information

This issue came up as a side note in a discussion with HZI. I don't know how urgent or important this is.

Not all tables defined in the [DatabaseTable.java](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/java/de/symeda/sormas/api/importexport/DatabaseTable.java) are always downloadable via the SORMAS UI. Some are hidden when the related feature is disabled in the feature configuration.

**Comment by dragosb-vg** [comment]
Validated on:
* **local environment** Version: 1.78.0-SNAPSHOT ([d77216d](https://github.com/hzi-braunschweig/SORMAS-Project/commits/d77216d8ba02dd33f65f78530ace6b53b67162fe)) for 'Campaigns' (_campaign_campaignformdata_ and _campaign_campaignformmeta_)

* **de1** Version: 1.78.0-SNAPSHOT ([c38288f](https://github.com/hzi-braunschweig/SORMAS-Project/commits/c38288f70fe4555e169fe4acacf599f67e162dd0)) for the rest of the databases (_person_locations, task_observer, contacts_visits, events_eventgroups, sharerequestinfo_shareinfo_)

- the checkboxes appear in Statistics/Database Export tab
- the CSV documents are generated correctly and populated with data

Please note that their visibility depends on feature module activation (ex. Campaigns feature module) and user rights.

![image](https://user-images.githubusercontent.com/111864167/208089286-ba273333-005b-4c95-8ff9-67785e767daf.png)

![image](https://user-images.githubusercontent.com/111864167/208089142-79de4f5c-de1d-4816-a931-9e67044787c6.png)
