### ISSUE TITLE
Add bulk reassignment of tasks to tasks directory

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1019]
I've changed the user right of "Pammy" to national observer. 
The task is unable to be executed by the BWARI_SO because "ASSIGNED TO" within the tasks created in the BWARI_SO's tablet.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar 
What user rights did "Pammy" have before? Is the task assigned to Pammy or BWARI_SO?

@hzi-braunschweig 
This is likely something we need to discuss. What should happen with tasks when a user assigned to it changes roles?

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda Pammy had "surveillance supervisor" role before in "FCT" and the problem was that the auto generated task for the DSNO kept being assigned to "Pammy".

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar The user should be able to go into the existing tasks and assign them to someone else. Is this possible?

What we probably need is a bulk "re-assign tasks" functionality for admins.

**Comment by Chinedar** [comment]
The later is most preferable to do. It would be great to have bulk
re-assignments of tasks.

**Comment by kwa20** [comment]
Implemented with #3430
