### ISSUE TITLE
When a case has deleted vaccinations too , the existent vaccination can not be deleted

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#10193]
### Bug Description

Bugfix ticket for #9943
When a case has deleted vaccinations too , the existent vaccination can not be deleted because NullPointerException will be thrown.

### Steps to Reproduce

1. Create a vaccination for a newly created case
2.  Delete the vaccination ( any delete reason can be selected, with or without vaccination status update , this will not make any change)
3. Create a new vaccination and try to delete it 
4. This error will appear
![image](https://user-images.githubusercontent.com/47103965/186374544-095ec584-dcf8-4398-acad-a31c4d88b408.png)

### Expected Behavior

No error message should appear.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by dragosb-vg** [comment]
Validated using **test.de**,  Version 1.76.0-SNAPSHOT ([f72f48a](urlhttps://github.com/hzi-braunschweig/SORMAS-Project/commits/f72f48a33abeb92664567b5b62e770c05b40fd11))
- checked adding/deleting multiple vaccinations for cases with different configurations
- checked behavior with different vaccines type and dates

**Comment by dragosb-vg** [comment]
Validated using test.de, Version 1.76.0-SNAPSHOT ([ead8ab7](https://github.com/hzi-braunschweig/SORMAS-Project/commits/ead8ab75260ee824643330d1795e7856527c00c5))
