### ISSUE TITLE
Suggestions for the contact supervisor dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1020]
Here are some suggestions to consider when reviewing contact officers dashboard that came up during the meeting with Nigerian team on March 18, 2019 :

1) Delete the whole section on "Follow-Up Situation" because it classify contacts person based on visits attributes.
2) All Contacts: Delete "NEW" since it has no reference calendar date point. Delete "SYMPTOMATIC"  or do not classify it as part on contact classification because a person can be both confirmed contact and symptomatic at the same time, in this way the portions do not add up to 100%
3) "Under follow up proportions" are not well calculated
4) more on figure, eg under "All Contacts" SYMPTOMATIC is 1 person and under "Contact Follow-Up" converted to case is 0
5) contacts cannot be selected by diseases, we need to add this filter -> #1029

[contactDashboardNigearia.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2996368/contactDashboardNigearia.docx)

_Originally posted by @bernardsilenou in https://github.com/hzi-braunschweig/SORMAS-Project/issues/460#issuecomment-475597692_

**Comment by MartinWahnschaffeSymeda** [comment]
Summary of our discussion today:

* The contact should have the same basic styles as the surveillance dashboard. The count comparison is not needed, so the top part can be tiles only or maybe have another diagram
* The numbers that are shown for the contacts of a disease need to be defined. The basis will be the existing dashboard numbers
* Contact follow-up should be completed once the follow-up duration if over (or passed for a few days)
* We need one or two numbers to show the quality of follow-up: How many days are missing to the end of the incubation period? How many days were done in total? This is something that has to be defined.

**Comment by hzi-braunschweig** [comment]
#contact dashboard review

all contacts review the calculation "all contacts"
review the entire contact dashboard to overhaul
always keep red for confirmed,worst scenario, and up to green for best scenario
unify the colours for "new cases" bar and "epid curve" on the surveillance dashboard
seperate the outbreak functionality...reducing the number of variables to be collected and the status of outbreak in a region. This should be seperated.
the linelist concept should be prioritized for programming
the outbreak fucntionality should not be limited to a push-button function.
the alert of the outbreak should be calculated by mathematical set algorithms...

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 

- [ ] go through the existing contact dashboard and the points listed here and create a mockup

**Comment by MartinWahnschaffeSymeda** [comment]
See #1534
