### ISSUE TITLE
Remove unnecessary queries for embedded entities [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10208]
### Problem Description
When saving a core dto, like a CaseDataDto, the system calls the fromDto method for all sub entities (e.g. SymptomsDto), which executes a service.getByUuid methode to get the entity. This is unnecessary since the entity is already fetched as part of the core entity. Overall it costs quite some performance (https://github.com/hzi-braunschweig/SORMAS-Project/issues/3481#issuecomment-773260588):

> fillOrBuildEntity set hospital/therapy/clinical/maternal/portHealth: 67ms
> fillOrBuildEntity setSymptoms: 12ms

### Proposed Change
Replace the fromDto method in the related facade with a fillOrBuildEntity method that also takes the entity as a parameter.

Note: The "OrBuild" part is not needed here. I'd just do it, to keep it simple and consistent with existing logic like CaseFacadeEjb.fillOrBuildEntity.

Do this for the following methods:

**Important:**

* **When calling this from a freshly created core dto, the uuid needs to be overridden based on the value from the dto. When it's an existing one, the uuid should be validated.**
* **When calling this from a freshly created dto, the system will no longer look for existing sub-entities (e.g. symptoms entity of a case) and instead expect they they also have to be created. This does of course not go for reference dtos.**

- [x] SymptomsFacadeEjb.fromDto
- [x] HospitalizationFacadeEjb.fromDto
- [x] HospitalizationFacadeEjb.fromDto for PreviousHospitalization
- [x] EpiDataFacadeEjb.fromDto
- [x] TherapyFacadeEjb.fromDto
- [x] ClinicalCourseFacadeEjb.fromDto
- [x] MaternalHistoryFacadeEjb.fromDto
- [x] PortHealthInfoFacadeEjb.fromDto
- [x] HealthConditionsMapper.fromDto (just needs to be removed, fillOrBuild already exists).
- [x] SormasToSormasOriginInfoFacadeEjb.fromDto
- [x] LocationFacadeEjb.fromDto

I'd suggest to do the same for the following methods to keep it consistent and error prove for the future:

- [x] TaskFacadeEjb.fromDto
- [x] ActionFacadeEjb.fromDto
- [x] DocumentFacadeEjb.fromDto
- [x] DiseaseConfigurationFacadeEjb.fromDto
- [x] CampaignFormDataFacadeEjb.fromDto
- [x] CampaignDiagramDefinitionFacadeEjb.fromDto
- [x] CampaignFormMetaFacadeEjb.fromDto
- [x] ClinicalVisitFacadeEjb.fromDto
- [x] EventGroupFacadeEjb.fromDto
- [x] ExternalMessageFacadeEjb.fromDto
- [x] TestReportFacadeEjb.fromDto
- [x] FeatureConfigurationFacadeEjb.fromDto
- [x] PopulationDataFacadeEjb.fromDto
- [x] OutbreakFacadeEjb.fromDto
- [x] AggregateFacadeEjb.fromDto
- [x] WeeklyReportFacadeEjb.fromDto
- [x] PathogenTestFacadeEjb.fromDto
- [x] AdditionalTestFacadeEjb.fromDto
- [x] SampleFacadeEjb.fromDto
- [x] SormasToSormasShareRequestFacadeEjb.fromDto
- [x] SystemEventFacadeEjb.fromDto
- [x] PrescriptionFacadeEjb.fromDto
- [x] TreatmentFacadeEjb.fromDto
- [x] UserFacadeEjb.fromDto
- [x] UserRoleFacadeEjb.fromDto
- [x] VaccinationFacadeEjb.fromDto (just needs to be removed, fillOrBuild already exists).
- [x] VisitFacadeEjb.fromDto

**Addition**

- [x] Make sure the related child entities for cases and contacts are fetched when saving or loading the whole entity (as they are mostly lazy)

**Comment by MartinWahnschaffe** [comment]
Creating a new case does not work, because it creates a new LocationDto without UUID.

We need to do the following:

- [ ] Check whether it makes sense that a new dto is created.
- [ ] Gracefully handle OneToOne children not having a uuid. When a new entity is created, automatically assing a uuid. When an existing entity is updated, take the uuid of the existing child entity.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(8f75178).

**Comment by FredrikSchaeferVitagroup** [comment]
[One change](https://github.com/hzi-braunschweig/SORMAS-Project/pull/10591/files#r1005256479) from this ticket breaks saving freshly fetched lab messages.

**Comment by abrudanancuta** [comment]
Validated the fix from this commit https://github.com/hzi-braunschweig/SORMAS-Project/commit/5d603ace78e66180966801d03189151896b55439 on local environment with the version: 1.77.0-SNAPSHOT (5d603ac)

**Comment by dragosb-vg** [comment]
Validated on de1-de2-de3 (general functionality & S2S sharing smoke testing) on Version: 1.76.0-SNAPSHOT ([88d4149](https://github.com/hzi-braunschweig/SORMAS-Project/commits/88d414931e5a4e12ceb71b6b61c12572f0610d85))

**Comment by roxanamlendea** [comment]
While testing another ticket, I stumbled upon the bug below. I talked to @dinua about it and he investigated the cause of the bug, which lead to this ticket, this is why I'm reopening it.

1. Create a Contact and open the Epidemiological Data tab;
2. Set 'Exposure to details known' to = 'Yes' and create an Exposure Entry;
3. Create a resulting Case for the Contact;
4. Open the Epidemiological Data tab of the Case;
-> The 'Exposure to details known' to = 'Yes', but the Exposure entry is not displayed

**Comment by dragosb-vg** [comment]
Validated on 1.77.0 on Version: 1.77.0-SNAPSHOT ([3938969](https://github.com/hzi-braunschweig/SORMAS-Project/commits/393896977092577e637d479abec8327ca7dc0c33))
- 'Exposure entry' is now correctly assigned and displayed when contact is converted to a case.
- Checked additional contact-to-case conversion scenarios
- Re-checked S2S sharing scenarios (using de1-de3 environments)
