### ISSUE TITLE
Provide user rights documentation [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10200]
### Problem Description
The new user role management (#898) allows admins to define which user rights each user role should have. For this they need to understand what each right means and also how user rights are related (#5058).
[SORMAS_User_Rights.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_User_Rights.xlsx) exists but does not cover all aspects of this and is not reachable from within the software and not translated to other languages.

### Proposed Change

1. - [x] In the user role edit view extend the tooltips (added by #10084) to also list which other user rights are needed. Example:

>   Able to delete cases.
>   Needed user rights: View cases, Delete tasks from the system, Delete samples from the system, ...

2. - [x] Extend the [SORMAS_User_Roles.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_User_Roles.xlsx) with another **sheet** that lists all details for the user rights. It should look like the no longer generated [SORMAS_User_Rights.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_User_Rights.xlsx), but also contain columns for the group and the needed user rights. The columns for the default user roles should be removed.
  The original source code can be found here: https://github.com/hzi-braunschweig/SORMAS-Project/pull/9794/files#diff-5407cc1f13fe3347221c88ea06f67963075295fad0120fb92717c955756cd711
![grafik](https://user-images.githubusercontent.com/23217632/187896000-25ade410-e3dc-41be-af28-382606d79a4e.png)
Example of the final document: 
  - [x] In the user roles sheet use a pleasant green for the "yes" cells and not background color at all for the "no" cells. Also don't use those cell borders. It should look like this    
![grafik](https://user-images.githubusercontent.com/23217632/188079685-61c27adb-9b8f-4387-80cf-a0efa37c66d5.png)
  - [x] Remove SORMAS_User_Rights.xlsx from the repository
  - [x] Update https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_CUSTOMIZATION.md#user-role-configuration accordingly

### Already in Place
3. Make a translated version of this Excel document accessible via the user role management

### Out of Scope
4. As an alternative visualization we could generate a markdown text document explaining the user roles, that would look something like this and could be part of the github repository and also be provided as localized information to the user.

> ## Case Surveillance
> ### View existing cases
> Allow users to view cases based on their jurisdiction.
> ### Edit existing cases
> Allow users to edit cases they can view.
>
> Required user right: [View existing cases](View-existing-cases).

- [ ] #10295

### Additional Information

* Could go one step further and also display right hierarchies

**Comment by MartinWahnschaffe** [comment]
@JaquM-HZI Would be great to have your feedback on the above 4 points. Which of those do you think should be implemented. Do you have additional suggestions?

**Comment by JaquM-HZI** [comment]
@MartinWahnschaffe does point 3 mean, translation in english? Than this would be first prio for us. Afterwards I'd like to have both, point 1 and point 2. Is that possible? Thanks

**Comment by MartinWahnschaffe** [comment]
With https://github.com/hzi-braunschweig/SORMAS-Project/issues/4462 the SORMAS_User_Rights.xlsx has now become [SORMAS_User_Roles.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_User_Roles.xlsx) which no longer provides details on the user rights. We need to refine this, before this can be worked on.

**Comment by MartinWahnschaffe** [comment]
Had a meeting with @JaquM-HZI and @SahaLinaPrueger and decided to put the user rights into a separate sheet. I have updated the description above.

**Comment by MartinWahnschaffe** [comment]
@leventegal-she I have added one point:

Update https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_CUSTOMIZATION.md#user-role-configuration accordingly

**Comment by abrudanancuta** [comment]
Validated on test.sormas and test.de with the version 1.76.0-SNAPSHOT (e586c0e)

**Comment by AliciaRaber** [comment]
Tested on test1402.sormas.netzlink.com
