### ISSUE TITLE
Events are pulled even though they have not been modified

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#10228]
### Bug Description

It seems like the mobile app pulls events everytime a synchronization is done even if no events have been modified. This becomes very visible with the new step-by-step synchronization dialog in #9437 (not merged into development yet).

### Steps to Reproduce

1. Trigger a synchronization with at least one event in the system that the mobile user has access to
2.

### Expected Behavior

Events should only be pulled when there have been any modifications to them.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(7cb38eb).
