### ISSUE TITLE
When searching for an entity by the Person's email or other contact detail, no result is fetched

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10229]
### Bug Description
When searching for an entity by the Person's email or other contact detail, no result is fetched.

This issue is reproducible for 'email' on the following pages:
- Cases Directory
- Case Contacts Tab
- Contacts Directory
- Event Participants Tab
It is not reproducible in the Persons Directory and the Immunizations Directory if the entry is set as primary contact detail. 

This issue is reproducible for 'other' on the following pages:
- Cases Directory
- Case Contacts Tab
- Contacts Directory
- Event Participants Tab

### Steps to Reproduce

1. Open the Cases Directory;
2. Make sure you have an entry that has an email or other contact detail filled in;
3. In the 'Person ID/name/contact information fill in the email or other contact detail from step  and click on Apply filters;

### Expected Behavior
The matching result should be fetched;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/187192407-86159af3-b66d-46c5-817f-1b9b220e4c56.png)

![image](https://user-images.githubusercontent.com/89522688/187192340-398c1e0c-7d9b-4c6f-baca-34c1435cc5c2.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local instance
* User Role: admin, NatUser

### Additional Information
#10222

**Comment by dinua** [comment]
With this fix a person is able to search after a person contact (email ,phone, other) , but only after the ones set as primary

**Comment by StefanKock** [comment]
Merge to development broke compilation due to removed joda-time

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT (ee60af7) from the development branch.
