### ISSUE TITLE
'First name' and 'Last name' of persons is visible for users that should not see them

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10243]
### Bug Description

For users that do not have rights to see the first and last name of persons, those names are displayed on the person pages and on the top header of entity pages, where only the UUID of the entity should be displayed for them.

The issue is reproducible in the following directories:
- Persons
- Cases
- Events
- Travel entries
- Immunizations
- In the 'Contacts' directory the header of the entity only displays the UUID (as it should) , but on the 'Contact person' page the first and last name of the person is visible.

### Steps to Reproduce

1. Log in with a user that does not have rights to see personal and sensitive data within their jurisdiction/ or outside their jurisdiction;
2. Navigate to each directory and observe how the first and last name of the persons are displayed in the main list of entities of each directory, and on the person pages of each type of entity.

### Actual Behavior

The first and last name of persons is displayed:
Persons directory:
- main list of persons - correct:
![image](https://user-images.githubusercontent.com/96909231/187422906-19d3c959-6dc2-42a2-804c-f63bbfd5499a.png)

- person page:
![image](https://user-images.githubusercontent.com/96909231/187423032-11a03970-ecaf-4928-8a0f-c70781c8065b.png)

Cases directory:
![image](https://user-images.githubusercontent.com/96909231/187423131-2241f59e-c9d0-4e4b-acb3-3e83131a53c6.png)

### Expected Behavior
 
For the users who see 'Confidential' displayed instead of the first and last name of the person on the main list of entities of each directory, they should see:
- [ ] the fields 'First name' and 'Last name' should display 'Confidential', on person pages;
- [ ] the header of each entity should display only the UUID of the entity, without the names of the associated person.

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(905d765), 1.74.3
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, National Clinician.

### Additional Information

#1158 introduced this feature (check `Pseudonymizer` class).

**Comment by leventegal-she** [comment]
it is caused by https://github.com/hzi-braunschweig/SORMAS-Project/issues/9372

Should revert everything was done there, and a proper fix is needed for that issue.

**Comment by MartinWahnschaffe** [comment]
- [ ] Needs to be picked into the hotfix. Will be done be @MateStrysewske

**Comment by abrudanancuta** [comment]
Validated on local environment having the version: 1.76.0-SNAPSHOT (086571c)
