### ISSUE TITLE
S2S Surveillance Reports should be shareable (along with possibly attached External Messages) [8]

### ISSUE THREAD

**Issue by SORMAS-SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10247]
### Feature Description

prerequisite: #6430 
Currently it is not possible to share physician's reports/ surveillance reports. If you share a case with S2S with hand over the ownership there is no possibility for this. Also the entity 'reports' in general can not be shared. This feature should allow that.

### Proposed Change

- [x] Introduce new properties
1. feature type: SORMAS_TO_SORMAS_SHARE_CASES 
property: SHARE_REPORTS

- [x] change UI of share window 
add a checkbox _share reports_ (see picture below)
- [x] change behaviour of checkboxes (summary: same behaviour as for checkbox samples)

| checkbox | value | behaviour checkbox _share reports_ |
| --- | --- | --- |
| Hand over the ownership | true | is checked and greyed out, _reports_ box surveillance reports AND attached physician's report / lab messages have to be shared with | 
| Hand over the ownership | false | is not checked and not greyed out. So checkbox can be checked BUT if checkbox is checked ONLY the box _reports_ is shared NOT the physician's report/ lab message | 
| Exclude personal data | true | is not checked and not greyed out. So checkbox can be checked BUT if checkbox is checked ONLY the box _reports_ is shared NOT the physician's report/ surveillance reports <br/> PLUS please check which fields have to be excluded (from the _reports_ box). I think only SurveillanceReport.facilityDetails and SurveillanceReport.notificationDetails but i do not have a current manual so please check this. Thank you | 
| Exclude personal data | false | no effect | 
| Share samples | true, false | no effect |
| Share immunization | true, false | no effect |
| Share reports | true, false | by clicking, checkbox gets checked or unchecked depending on the previous status. Exception: checkbox is greyed out because of behaviour mentioned above. If checkbox is greyed out, the checkbox is not clickable. |

- [x] If a share was initiated _with hand over the ownership_ and _share reports: true_ the source system is still able to open the 'edit report' window and is able to read what is written. Furthermore they can open the attached physician's reports/ lab messages
- [x] If a share was initiated hand over the ownership= false and share reports=true, the target system is still able to open the 'edit report' window and is able to read what is written. 
- [x] If a share was initiated hand over the ownership=false and share reports=false, the target system does not receive reports and the source system is still able to open the 'edit report' window and is able to edit. 
- [x] shared physician reports / lab messages should also be shown in both system's message directories.
### Implementation Details

![image](https://user-images.githubusercontent.com/100844689/187450681-b03652df-d53c-4745-a8c3-9b88fca3d8f6.png)

### Additional Information

- [x] Like the entities _samples_ and _vaccination_: As long as a share request has the status _pending_, the source system can edit and change data. The edited and changed data should be synced immediately.
- [x] Sync should work between both systems (similar to how it is done for samples).

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by SahaLinaPrueger** [comment]
>Lab messages can soon be related to surveillance reports, too. Should it be possible to share those as well (in the context of sharing surveillance reports)?

Yes. 

> If so, those lab messages hold references to samples. Should it be possible to share those lab messages without sharing the attached samples?

No, it should not be possible. In general behavior should be like #8950. So lab messages and physician reports are only shared with, if the request is sent _with hand over the ownership_. If a request is sent with hand over the ownership it is mandatory that every checkbox ist checked. If the request is sent _without_ hand over the ownership the user can check the checkboxes _share samples_ and _share reports_ how they want. Both can be sent independently because the lab message and the physician reports are not transferred with. 

> Furthermore, external messages (in general) can have assignees. They can not be transfered to receiving systems. We need to clarify when the assignee should stay and when it should be removed.

Good point, we did not thought about this yet. I think we should leave the assignee and never remove, because that can be used by the health departments to trace who has done what.

**Comment by SahaLinaPrueger** [comment]
Please note: I added two points under _additional information_ for the sake of completeness

**Comment by abrudanancuta** [comment]
Ticket is reopened because "View message" button inside the Surveillance Report is disable after the case was shared
![Screenshot 2023-01-17 at 15 02 48 (2)](https://user-images.githubusercontent.com/91872179/212926497-26036234-5754-41c7-978b-0e96faf167b3.png)

**Comment by abrudanancuta** [comment]
Validated on test enviroments, test.de2, test.de1, test.de3 with the version: 1.79.0-SNAPSHOT (93d49ae)
