### ISSUE TITLE
Aggregate reports created by editing an already existing aggregate report, are not displayed immediately in the grid

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10246]
### Bug Description
The aggregate reports that are created by editing an already existing aggregate report, are not immediately displayed in the grid.

### Steps to Reproduce

1. Open the mSERS directory and select the Report Data tab;
2. Create a New Aggregate Report (set valid values for at least 1 disease);
3. Edit the Aggregate Report created in step 2 and set valid values for another disease;

### Expected Behavior
The entry for the new disease should be displayed immediately.

### Actual Behavior
The entry for the new disease is displayed only after a refresh.

### Screenshots

![aggregate report](https://user-images.githubusercontent.com/89522688/187468556-557e6ee6-6421-4d36-a564-7be15aad449b.gif)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local instance
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Should be done together with #10128, so I'm closing this issue and referring to it in the other one.

**Comment by andrei7bal** [comment]
Fix for this is available in #10128
