### ISSUE TITLE
When using a document template, samples can only be choosen by their ID

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10241]
### Bug Description

When using a document template, samples can only be choosen by their ID. Informations like date, disease, or status are not shown anymore.
### Steps to Reproduce

1.open a case with a sample
2.try to create a quarentine order / document 
3. try to choose a sample

### Expected Behavior

The information as in version 1.73.3 should be displayed again

### Screenshots

![image](https://user-images.githubusercontent.com/96547924/187397208-3647331b-a542-47d6-bd45-d058eccc1af7.png)

### System Details

* Device:
* SORMAS version:1.74.3
* Android version/Browser:
* Server URL:test1402
* User Role:admin

### Additional Information

Was probably overlooked in #8314

**Comment by MateStrysewske** [comment]
Seems like this is an oversight of our toString/caption refactoring.

**Comment by StefanKock** [comment]
I fixed the problem in `QuarantineOrderLayout` and checked other ComboBox if the same problem is in there (especially sibling `EventDocumentLayout` and superclass `AbstractDocgenerationLayout`), but I did not find any other similar problems.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(73ef5ba).
