### ISSUE TITLE
Database export zip files is empty on first try

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1024]
This happens when the csv files are not ready yet. We have to delete old csv files first and then wait for the database export of each file to finish before appending it to the zip.

**Comment by bernardsilenou** [comment]
Nigerian team says all works fine now with 1.38.0 . Maybe we wait until something comes up from the field

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Has this popped up again?
