### ISSUE TITLE
[Reporting Tool] Error during Archive / De-archive cases

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#10259]
### Bug Description
If a new case is created it is possible to archive the case immediately after creation. It is not possible to De-archive the case. The De-archive only works after you have sent the archived case to reporting tool

### Steps to Reproduce

1. Go to cases
2. Click on button "New case"
3. Enter mandatory fields only
4. After case is visible in screen scroll down to "Archive" and press "Archive --> Case gets archived
5. Press button "De-archive" immediately after archieving the case --> Enter a reason in dialog box --> Error message appears
6. Go to section "Reporting tool"
7. Press button "Send to reporting tool" --> Case get reported to reporting tool
8. Scroll down to "De-archive"
9. Press button "De-archive" --> Enter a reason in dialog box --> Case gets De-archived

### Expected Behavior
If you wrongly De-archive the case without sending it should be possible to fix this error without sending the case to reporting tool.

### Screenshots
See attached GIF

### System Details

* Device: EPID Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Edge
* Server URL: test1402.sormas.netzlink.com
* User Role: admin

### Additional Information
Error only occuring on instances with external message adapter activated. Could be possibly an error according to SurvNet or converter.

![Ark, DeArk P1](https://user-images.githubusercontent.com/91321821/187870468-49f9e2a2-c9b8-489c-bb8c-cc4ce757db86.gif)
![Ark, DeArk P2](https://user-images.githubusercontent.com/91321821/187870484-cbe38cc4-4a85-446d-8442-8e2bbc2ceea6.gif)

**Comment by StefanKock** [comment]
Please provide the corresponding stack trace from the log.

**Comment by abrudanancuta** [comment]
Validated together with @leventegal-she on his local environment
