### ISSUE TITLE
Update minimum Android version from 7.0 to 8.0 [0]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10261]
### Problem Description
To implement #6700 we need access to the java 8 time library which is only supported starting Android 8.0 (API version 26). 
Besides this from a security standpoint it would definitely be good to get rid of a few outdated Android devices. 

### Proposed Change
Update minimum version from 24 to 26.
Based on https://apilevels.com/ this still covers a very high amount of available devices:
API 24 is currently supported by 95.1% of devices. API 26 is supported by 91.1%

**Comment by JonasCir** [comment]
@faatihi FYI based on your comment on #6700

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(7cb38eb) - using Android Studio I created 3 new emulators and tried to launch the mobile app:
- Pixel 2 API 24 - Android version 7.0 - failed - ok 
- Pixel C API 25 - Android version 7.1.1 - failed - ok 
- Pixel C API 26 - Android version 8.0 - worked - ok 

In Android Studio, the user is warned that the API level necessary is 26.
