### ISSUE TITLE
Vaadin 8 data binding for forms

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1026]
Resources:

* https://vaadin.com/docs/v8/framework/datamodel/datamodel-forms.html#datamodel.forms and * https://vaadin.com/docs/v8/framework/datamodel/datamodel-fields.html#datamodel.fields
* https://vaadin.com/training/course/view/layouting-basics
* https://vaadin.com/training/course/view/data-binding-and-validation

First we need to define how the architecture should be changed:

* Binder seems to replace FieldGroup
* Can we keep the addField helper methods in AbstractEditForm and create a custom field factory as a helper?
* Does the CommitDiscardWrapper still make sense?
* Should the layouting be changed?
* Field visibility and read-only modes
* Dealing with validation, required and soft-requiered fields

Implementation steps:

1. Clone and change helpers that will still be needed
2. Start with simple forms and migrate one by one to the new components Split into multiple issues that group forms

**Comment by MateStrysewskeSym** [comment]
- [ ] Introduce new DataBinding for UserEditForm
