### ISSUE TITLE
change community name

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10268]
### Problem Description

Traunstein (S2S Pilot Office) would like to have the name of a community changed. 
It concerns the following community:
Gem.fr. Geb. Traunstein
### Proposed Change

Which should be named as follows:
Traunstein, Gm.fr. Geb.

Important: The absence of the 'E' in Gem is not a mistake. It should be 'Gm' and preceded by Traunstein.

**Comment by SahaLinaPrueger** [comment]
@JonasCir @JaquM-HZI

**Comment by JonasCir** [comment]
We can adjust the naming in central, but everybody needs to be aware that this must/will be changed for all GAs then.

**Comment by JonasCir** [comment]
QA: You can check that the name was changed correctly here in this [PR](https://github.com/hzi-braunschweig/SORMAS-central-data/pull/16/files).

**Comment by dragosb-vg** [comment]
Validated on test-de1/test-de2/test-de3 on version 1.76.0-SNAPSHOT ([f0e7ab4)](https://github.com/hzi-braunschweig/SORMAS-Project/commits/f0e7ab4184ca551f3d8f141b93cc42afedc259ba))
Community name was changed from **Gem.fr. Geb. Traunstein** to **Traunstein, Gm.fr. Geb.** in "Jurisdiction Community" for cases/contacts/events forms.

![image](https://user-images.githubusercontent.com/111864167/192255323-e7bfbbca-6e17-4eb4-aaff-f7c8ffc63e14.png)
