### ISSUE TITLE
Replace temporal tables postgres extension with PL/pgSQL function [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10260]
### Problem Description
The temporal tables extension is no longer maintained and only support Postgres up to version 10 (which is only supported until the end of this year): https://github.com/nearform/temporal_tables
In addition it complicates the server setup process and makes it impossible to run SORMAS as a hosted service when the provided Postgres instance does not support custom extensions.

### Proposed Change
https://github.com/nearform/temporal_tables provides a PL/pgSQL function that replicates the same functionality. Based on their performance tests this is 16x slower than the C implementation, which is most likely related to a missing cache functionality.
From my understanding we don't have a performance problem related to writing history data when inserting new data into the database. The performance problems we are currently facing when persisting data are based on other factors - see #4417.

- [x] Include the provided function script into SORMAS backend
- [x] Add statements to create the function both for newly setup systems and for running systems
- [x] Remove the temporal tables **extension** from all setup instructions
- [x] Remove check from StartupShutdownService
- [x] Provide a draft pull request for SORMAS-Docker to adjust it accordingly --> https://github.com/hzi-braunschweig/SORMAS-Docker/pull/485
- [ ] Release notes need to contain information on SQL that needs to be executed.

### Acceptance Criteria
* Existing and newly setup servers no longer rely on the temporal tables extension
* History tables still work as before

### Additional Information

Command to change owner of existing `versioning` trigger function. **Needs to be called before deploying SORMAS into the server.**

```
-- versioning function will be replaced during server backend startup
ALTER FUNCTION public.versioning() OWNER TO sormas_user;
```

Command to drop extension on existing systems. Can be run **after** server was deployed for the first time: 

```
-- needed because `ALTER FUNCTION ... NO DEPENDS ON EXTENSION` is not possible in Postgres 10 and below
DELETE FROM pg_depend
WHERE deptype = 'e'
  AND refobjid = (SELECT oid FROM pg_extension WHERE extname = 'temporal_tables')
  and objid = (SELECT oid FROM pg_proc WHERE proname = 'versioning');

DROP EXTENSION IF EXISTS temporal_tables;
```

**Comment by BarnaBartha** [comment]
Starting with the version this ticket get's released, the temporal tables extension must be removed from the database. For this one needs super user access and execute the following command:
```
drop extension if exists temporal_tables
```

**Comment by JonasCir** [comment]
@BarnaBartha Their [usage](https://github.com/nearform/temporal_tables#usage) section mentions `sys_period` maybe this helps?

**Comment by StefanKock** [comment]
Work on PR #11380 was not finished before feature freeze, so moved to next version

**Comment by MartinWahnschaffe** [comment]
I have provided the script that needs to be executed before deployment, to change the owner of the versioning function. I have considered adding this to the server-update.sh script, but decided against it, because it is only needed once for old systems.
For systems running on docker we will hopefully find a fully automated solution. I will discuss this with @fhauptmann in the context of https://github.com/hzi-braunschweig/SORMAS-Docker/pull/485

**Comment by MartinWahnschaffe** [comment]
Alter FUNCTION is done by https://github.com/hzi-braunschweig/SORMAS-Docker/pull/486 and https://github.com/hzi-braunschweig/SORMAS-Docker/pull/487

We decided to leave remaining fragments of the extension in the database, because they don't cause any problems. Looking for a good way to document this.
