### ISSUE TITLE
Fields do not fit completely in the Line Listing window

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10285]
### Bug Description

At Multi-day contacts, the last field is not completely visible.  In this case the drop down menu cannot be used. A manual input is still possible. 

### Steps to Reproduce

1. Got to the Contact Directory
2. Click the "+ Line Listing" - Button
3.  Select "Multi-day Contact"

### Screenshots

![image](https://user-images.githubusercontent.com/101708230/188604350-e1d5b3c2-bbba-40a5-845a-8b606460cac1.png)

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrom and Edge
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Surveillance Supervisor & Contact Supervisor  AND admin

**Comment by MateStrysewske** [comment]
@KernB What would be your expected behaviour for this issue?

**Comment by MateStrysewske** [comment]
@KernB The only options I see would be to reduce the width of the type of contact and/or relationship to case fields, which would result in the text not being completely displayed in those dropdowns. Would that be fine by you? @JaquM-HZI Would like to hear your opinion as well.

**Comment by MateStrysewske** [comment]
@JaquM-HZI Not sure how easy this is implementable with Vaadin 7 to be honest, we'll have to have a look into it.
