### ISSUE TITLE
"Unbekannt" and "Unknown" is displayed in different drop downs at the same time

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10299]
### Bug Description

"Unbekannt" and "Unknown" is displayed in different Disease Variant drop downs at the same time

Exempels 
- Creating a new case
- Create new event
- Contact Directror
- Case Directory
 

### Steps to Reproduce

1. Select COVID-19 as Disease
2. Select a Disease variant

### Expected Behavior

Only the German or English text is displayed.

### Screenshots

Case directory
![image](https://user-images.githubusercontent.com/101708230/188885555-9955cf3b-6865-4364-a868-5cf2b48c1a52.png)

Create a new case
1. "Disease Variant Details" are visible
![image](https://user-images.githubusercontent.com/101708230/188885758-849a9068-2f8f-4f84-b1ac-20071c2cfd89.png)

2. "Disease Variant Details" aren't visible
![image](https://user-images.githubusercontent.com/101708230/188886035-1002b954-0fbc-4a73-bca5-5f6e4c641a7b.png)

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrome
* Server URL:  https://release-international.sormas.netzlink.com/
* User Role: Admin

**Comment by MateStrysewske** [comment]
@KernB Disease variants are custom values that are added to the database by server admins. There are no default values that are shipped with SORMAS. So in this case, I suspect that somebody added those redundant values to the database manually.
