### ISSUE TITLE
When changing the jurisdiction level at user roles, inconsistent users can be created.

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10305]
### Bug Description

With the user roles, the jurisdiction levels can be changed. A reduction only becomes effective when the user has also been edited. After a change of the user role, empty mandatory fields appear with the user. This happens without any hint when editing the role.

### Steps to Reproduce

1. Create a new user role using e.g. the "Surveillance Supervisor (Default)" template. 
2. Assign a user to this role.
3. Go back to the user role
4. Set the jurisdiction level to "Community" 
5. Login whist the user and check if the user behaves as configured 
![image](https://user-images.githubusercontent.com/101708230/188904800-6d47755b-63a2-4c57-ac71-480a6dc9554d.png)
6. Login a Admin and update the user
![image](https://user-images.githubusercontent.com/101708230/188901615-a9d014de-30ee-46d6-b938-d7e35ec4e4bf.png)

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrome
* Server URL: test1401
* User Role: Admin and other newly created users

**Comment by dragosb-vg** [comment]
Validated on test.sormas on Version: 1.76.0-SNAPSHOT ([5201c4d](https://github.com/hzi-braunschweig/SORMAS-Project/commits/5201c4d1b9bf01c58a3779a6d9ef87442a2f2297)).
User roles can no longer be changed if assigned to at least 1 user (error message is triggered)
![image](https://user-images.githubusercontent.com/111864167/190614609-1b0bb662-3beb-4663-9fb2-0e035bb677ca.png)

**Comment by ChristopherRiedel** [comment]
A unit test that shows the behavior is needed here.
