### ISSUE TITLE
"keine Variant of Concern (VOC)" in drop down menus

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10300]
### Bug Description

"keine Variant of Concern (VOC)" is listed twice in drop downs.  It looks like German and English are mixed here. 

Exempels
- Case Directory
- Creating a new case
- Case
- Event Directory
- Create new event
- Contact Directror
 

### Steps to Reproduce

1. Select COVID-19 as Disease
2. Select a Disease variant

### Screenshots

![image](https://user-images.githubusercontent.com/101708230/188888357-b7afa538-961c-4155-990d-8fc92630688e.png)

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrome
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Admin

**Comment by MateStrysewske** [comment]
See #10299 - I suspect that this value has been added to the database twice since SORMAS doesn't provide any default disease variants.
