### ISSUE TITLE
[Import] Nosocomial outbreak and reinfection not checked when importing via SurvNet

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#10301]
### Bug Description
Nosocomial outbreak was imported via Ansible Job and had to be merged with existing case in SORMAS. Cases has been merged and the checkbox ‘Resulted from nosocomial outbreak’ was not checked. Data in SurvNet was set to <NULL>, data in SORMAS was set to True --> Ambulatory

### Steps to Reproduce
1. Create a SORMAS case with following entries: Nosocomial outbreak box --> Checked. Infection setting --> Ambulatory
2. Create a SurvNet Case with following entries: Nosocomial outbreak NULL, Umfeld NULL
3. Import SurvNet Case to SORMAS
4. Switch to SORMAS
6. Navigate to the case directory 
7. Search for the case "Russel Scoutboy" and open it --> Cases shoud be merged after import
8. Scroll down to section ‘Resulted from nosocomial outbreak’
9. Look for value

### Expected Behavior
If data gets imported from SurvNet to SORMAS with value NULL and existing data in SORMAS, the information in SORMAS should be kept as entered before.

**Same with Reinfection**, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/10303.

### Screenshots
![image](https://user-images.githubusercontent.com/91321821/188894010-13e67e8f-6007-454a-9f42-f81cb7c61e0a.png)

### System Details

* Device: EPID-Laptop NW10051
* SORMAS version: 1.74.3 / Converter 14.1.0
* Android version/Browser: Edge Browser
* Server URL: survnet-import-test.sormas.netzlink.com
* User Role: admin

### Additional Information
Data was imported via Ansible Job. Merge-function was enabled in order to look if the import was processed accordingly. Ticket ID 2022164012 (NLI)

**Comment by JaquM-HZI** [comment]
closed cause it is in wrong repo
