### ISSUE TITLE
Pop up message "Vaccination status update is not translated

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10302]
### Bug Description

Pop up message "Vaccination status update is not translated
The message was introduced with the ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9943

### Steps to Reproduce

1. set the language to "Deutsch"
2. create a case
3. add a relevant vaccination
4. check the vaccination status of the case
5. delete the vaccination
6. set a reason for the deletion
7. the new window appears

### Screenshots

![image](https://user-images.githubusercontent.com/101708230/188893241-7154ad6a-7ebb-461c-9716-a557cacb6925.png)

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser:  Chrome
* Server URL: test1401
* User Role: Admin

**Comment by MateStrysewske** [comment]
Text is translated on 1.76.0. I suspect the translation came in too late to make it into the release of 1.75.
