### ISSUE TITLE
TravelEntryService.getLastTravelEntry: Only fetch one entry in query

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10306]
### Problem Description

During the automated tests, extensions of the runtime have been noticed when opening a travel entry create form. Perhaps this can give an early indication of an issue.

<details>
<summary>Details of finding</summary>

#### Steps to Reproduce

1. Go to test-de
2. Log in as a National User
3. Navigate to Case directory
4. Go into details of any case
5. Navigate do Epidemiological Data ta
6. Click on "New Entry" to create new travel entry
Time required to open travel entry form was around 21 seconds.

Another example
Steps to reproduce: 

1. Go to test-auto
2. Log in as a automation admin
3. Navigate to Case directory
4. Select an option to merge duplicates
5. Filter out f.e. cases with Covid as a disease on top of default set filter to includeonly cases created throughout last month
Waiting time for filtering out the results is longer than it was on 1.75 - 4 min 15 seconds

#### Screenshots

tests performed on test-auto and time when they started failing:
![image](https://user-images.githubusercontent.com/101708230/188917746-21d7bf84-5043-4d76-b3be-42198fec76ef.png)
![image](https://user-images.githubusercontent.com/101708230/188917772-dc210067-039c-48cd-8638-dd1bc189f4c6.png)
![image](https://user-images.githubusercontent.com/101708230/188917780-0065d255-1a6a-4be8-957c-50e2396d0391.png)
![image](https://user-images.githubusercontent.com/101708230/188917803-7c51d400-f597-489b-8a52-262da1582d7e.png)
![image](https://user-images.githubusercontent.com/101708230/188917820-751aaeca-cc43-4b54-a562-6045d5d1d61d.png)
![image](https://user-images.githubusercontent.com/101708230/188917829-caba55cd-0054-4c9d-b3d4-efc9f4e6af48.png)
![image](https://user-images.githubusercontent.com/101708230/188917860-c26a7d79-3588-4a68-b9ef-79b4a6863322.png)

#### System Details

* Device: Automated test 
* SORMAS version: 1.76.0-SNAPSHOT (21880ba) 
* Android version/Browser: Automated test
* Server URL:  test-de, test-auto
* User Role: automation admin, National User

</details>

### Proposed Change

Only fetch one travel entry in `TravelEntryService.getLastTravelEntry` instead of all accessible entries and than only picking the first.

### Acceptance Criteria

- [x] Performance is improved significantly. 21s+ to ~1s or less

### Additional Information

Caused by #6025.

**Comment by KernB** [comment]
**Alternative Steps to reproduce**  - open "Create new travel entry" form
1. Given I log in as a Admin User
2. And I click on the Entries button from navbar
3. And I click on the New Travel Entry button from Travel Entries directory

**Comment by StefanKock** [comment]
I set the `PerformanceLoggingInterceptor = DEBUG` and found some hotspots when invoking `TravelEntryController.getTravelEntryCreateComponent`:

1. **21,0s** for `TravelEntryService.getLastTravelEntry` (the obvious problem here). The code was changed last time about a year ago. It seems that the amount of travel entries in the database causes a problem.
2. 0,7s for `CaseFacadeEjb.getCaseDataByUuid` just to get the `PersonReferenceDto` and `Disease`.
3. 0,3s x2 for `RegionFacadeEjb.getAllActiveByServerCountry`
4. 0,5s for `PersonFacadeEjb.getByUuid` to get the `PersonDto` from `PersonReferenceDto`.
```bash
# last entry on top, oldest entry at the bottom (fetched from Grafana and cleaned)

D150859.349 > Finished in 483 ms: PersonFacadeEjb.getByUuid 
D150859.347 > Finished in 317 ms: PersonService.inJurisdictionOrOwned 
D150859.186 > Finished in 156 ms: FeatureConfigurationFacadeEjb.isPropertyValueTrue 
D150859.029 > Finished in 162 ms: PersonService.getByUuid 

D150858.864 > Finished in 319 ms: RegionFacadeEjb.getAllActiveByServerCountry 
D150858.704 > Finished in 159 ms: CountryFacadeEjb.getServerCountry 
D150858.703 > Finished in 157 ms: CountryService.getByDefaultName 

D150858.540 > Finished in 313 ms: RegionFacadeEjb.getAllActiveByServerCountry 
D150858.383 > Finished in 156 ms: CountryFacadeEjb.getServerCountry 
D150858.382 > Finished in 155 ms: CountryService.getByDefaultName 

D150858.216 > Finished in 723 ms: CaseFacadeEjb.getCaseDataByUuid 
D150858.215 > Finished in 158 ms: CaseService.inJurisdictionOrOwned 
D150857.664 > Finished in 171 ms: CaseService.getByUuid 

D150857.489 > Finished in 21211 ms: TravelEntryFacadeEjb.getDeaContentOfLastTravelEntry 
D150857.488 > Finished in 184 ms: TravelEntryService.inJurisdictionOrOwned 
D150857.303 > Finished in 21025 ms: TravelEntryService.getLastTravelEntry 
```

**Comment by StefanKock** [comment]
Changes are merged, should be retested on test-de with NatUser to check it improved.

**Comment by StefanKock** [comment]
Performance improvement verified on test-de

**Comment by roxanamlendea** [comment]
Verified ticket on local environment and on test-de using the latest version of Sormas 1.76.0-SNAPSHOT from the development branch.
