### ISSUE TITLE
Provide user notifications documentation [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10310]
### Problem Description
We need a documentation for user notifications similarly to what we have for user rights based on #10200 .

### Proposed Change
- [x] Add descriptions to notifications to be shown in the UI when hovering a notification in the user role edit view. The descriptions are provided below.
- [x] Extend [SORMAS_User_Roles.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_User_Roles.xlsx) with another **sheet** that lists all details for the user notifications: enum name, group, caption, description
- [x] In the user roles sheet add a column "Notifications" at the end that stays empty. For each notification type add another column that contains whether the user role is using the notifications type.
- [x] Update https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_CUSTOMIZATION.md#user-role-configuration to also mention notifications.
- [x] In the user roles sheet move the Uuid, Port health user, Has associated district user, Has optional health facility, Enabled columns between Description and a new column "User rights" that stays empty and marks the start of the user rights
- [x] In the generic version of the document (provided on Github) exclude the uuid column

### Implementation Details

- Write every notification type once and write into the cell if SMS, EMAIL, both ("SMS, EMAIL") or none = "" are enabled.

### Additional Information

| Notification type | Group | Caption | Description |	
| -- | -- | -- | -- |
| CASE_CLASSIFICATION_CHANGED | CASES | Case classification changed | Sent to all users associated to the region or responsible region of a case. |
| CASE_INVESTIGATION_DONE | CASES | Case investigation done | Sent to all users associated to the region or responsible region of a case. |
| CASE_LAB_RESULT_ARRIVED | CASES | Case lab result arrived | Sent to all users associated to the region or responsible region of a case when a pathogen test result is entered or modified (non-pending). |
| CASE_DISEASE_CHANGED | CASES | Case disease changed | Sent to all users associated to the region or responsible region of a case when the disease was previously set to 'Unspecified VHF'. |
| CONTACT_LAB_RESULT_ARRIVED | CONTACTS | Contact lab result arrived | Sent to all users associated to the region of a contact when a pathogen test result is entered or modified (non-pending). If the contact has no region the region of the source case is used. |
| CONTACT_SYMPTOMATIC | CONTACTS | Contact symptomatic | Sent to all users associated to the region of a contact when a new symptomatic visit is created and the contact was previously asymptomatic. If the contact has no region the region of the source case is used. |
| CONTACT_VISIT_COMPLETED | CONTACTS | Contact visit completed | Sent to all users associated to the region of a contact and all observer users when a "Contact follow-up" task is completed. If the contact has no region the region of the source case is used. |
| EVENT_PARTICIPANT_CASE_CLASSIFICATION_CONFIRMED | EVENTS | Event participant case classification confirmed | When a case is set to a confirmed classification, this is sent to all responsible users of active events in which the case person participated and which took place no earlier than 30 days before the case was classified. |
| EVENT_PARTICIPANT_RELATED_TO_OTHER_EVENTS | EVENTS | Event participant related to other events | When a new event participant is created, this is sent to all responsible users of active events in which the person also participated and which took place no earlier than 30 days before.
| EVENT_PARTICIPANT_LAB_RESULT_ARRIVED | EVENTS | Event participant lab result arrived | Sent to all users associated to the region of an event participant when a pathogen test result is entered or modified (non-pending). |
| EVENT_GROUP_CREATED | EVENTS | Event group created | Sent to all responsible users of events that are part of a newly created event group. |
| EVENT_ADDED_TO_EVENT_GROUP | EVENTS | Event added to event group | Sent to all responsible users of events that are part of the modified event group. |
| EVENT_REMOVED_FROM_EVENT_GROUP | EVENTS | Event removed from event group | Sent to all responsible users of the removed event and events that are part of the modified event group. |
| LAB_SAMPLE_SHIPPED | SAMPLES | Lab sample shipped | Sent to all users of a laboratory when a sample of that laboratory is shipped. |
| TASK_START | TASKS | Task start | Sent to the assignee of a task and all observer users when the task start date is within the last 10 minutes. |
| TASK_DUE | TASKS | Task due | Sent to the assignee of a task and all observer users when the task due date is within the last 10 minutes. |
| TASK_UPDATED_ASSIGNEE | TASKS | Task assignee updated | Sent to the previous and new assignee of a task. |

**Comment by MartinWahnschaffe** [comment]
@JaquM-HZI Please double check whether this makes sense to you. Adding the configuration of the notifications to the sheet with the user roles next to the user rights, will mean there are even more columns, but from my point of view this would be ok here.

**Comment by JaquM-HZI** [comment]
@MartinWahnschaffe  double checked and it's fine for me. Thanks!

**Comment by MartinWahnschaffe** [comment]
@SahaLinaPrueger @JaquM-HZI Please double-check the descriptions I have provided above for the notification types.
I'd also suggest to rename "Case disease changed" to "Case VHF disease changed" because it is only triggered when an "Unspecified VHF" case disease is changed to something else.
