### ISSUE TITLE
[Import] Variant not choosed correctly

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#10316]
### Bug Description
Reinfection was imported via Ansible Job and had to be merged with existing case in SORMAS. Cases has been merged and the field ‘Variants’ was not entered as in SORMAS case.

### Steps to Reproduce

1. Create a SORMAS case with following entries:

|SORMAS field|Value|
|-|-|
|Disease variant|P.2|

2. Create a SurvNet Case with following entries: 

|SurvNet Field|SurvNet Value|
|-|-|
|Laborangaben verfügbar|Ja|
|Virusvariante|andere/sonstige|
|Details| P.2|

3. Import SurvNet Case to SORMAS
4. Switch to SORMAS
5. Navigate to the case directory
6. Search for the case ‘Pongo Dalmatian’ and open it --> Cases shoud be merged after import
7. Scroll to section ‘Disease’
8. Value is ‘andere/sonstige’

### Expected Behavior
Data from SurvNet should be transferred that value is ‘P.2’ according to the correct variant in SORMAS.

### Screenshots
![image](https://user-images.githubusercontent.com/91321821/189120951-4ba42b51-9021-425a-8d6e-dcf88e410ca9.png)
![image](https://user-images.githubusercontent.com/91321821/189121039-4eade9a8-e297-4ddb-a1b0-a3b3d028564c.png)

### System Details
* Device: EPID-Laptop NW10051
* SORMAS version: 1.74.3 / Converter 14.1.0
* Android version/Browser: Edge Browser
* Server URL: survnet-import-test.sormas.netzlink.com
* User Role: admin

### Additional Information
Data was imported via Ansible Job. Merge-function was enabled in order to look if the import was processed accordingly. Ticket ID 2022164012 (NLI). Probably issue is happen because field is not designated to the dropdown field.

**Comment by JaquM-HZI** [comment]
Closed cause of wrong repo.
