### ISSUE TITLE
[Import] Sex was set to 'Unknown'

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#10318]
### Bug Description
Person with Sex ‘Unknown’ via Ansible Job and had to be merged with existing case in SORMAS. Cases has been merged and the field ‘Variants’ was not entered as in SORMAS case.

### Steps to Reproduce

1. Create a Case in SORMAS with following entries:

|SORMAS field|Value|
|-|-|
|First Name|Ginny|
|Last Name|Weasley|
|Birthdate|11.08.1981|
|Sex|Unknown|

2. Create a SurvNet Case with following entries:

|SurvNet Field|SurvNet Value|
|-|-|
|First Name|Ginny|
|Last Name|Weasley|
|Birthdate|11.08.1981|
|Sex|Female|

3. Import SurvNet Case to SORMAS
4. Switch to SORMAS
5. Navigate to the case directory
6. Search for the case ‘Ginny Weasley’ and open it --> Cases shoud be merged after import
7. Go to tab ‘Case Person’
8. Go to section ‘Sex’
9. Value is ‘Unknown’

### Expected Behavior
Data from SurvNet should be transferred that value is ‘Female’
Hierarchy should follow logically:
male + unknown → male
female + unknown → female
divers + unknown → divers

### Screenshots
![image](https://user-images.githubusercontent.com/91321821/189137095-aa7da507-9e55-4437-823c-92a0ec157aaf.png)

### System Details
* Device: EPID-Laptop NW10051
* SORMAS version: 1.74.3 / Converter 14.1.0
* Android version/Browser: Edge Browser
* Server URL: survnet-import-test.sormas.netzlink.com
* User Role: admin

### Additional Information
Data was imported via Ansible Job. Merge-function was enabled in order to look if the import was processed accordingly. Ticket ID 2022164012 (NLI).

**Comment by JaquM-HZI** [comment]
Closed this because of wrong repository.
