### ISSUE TITLE
Climedo_ Filled symptom diary questionnaires do not reach SORMAS after submission

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10327]
### Bug Description

Registration works fine but the contents of the filled questionnaires do not get entered in SORMAS and no visit is created.
The successfully filled questionnaire does not reach SORMAS. However, registrations of person works with email and phone number.

### Steps to Reproduce

1. Register Person with email or phone number
2. Fill in questionnaire and send it
3. Observe if new visit is created and whether symptoms are adopted 

### Expected Behavior

New visit is created and symptoms are adopted.
### System Details

* Device:
* SORMAS version: 1.75.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

May be related to the new user role concept.
Found out by @kwa20

**Comment by kwa20** [comment]
After re-configuring the External Visits User role I was able to successfully receive a questionnaire. I can't exactly say if the rights combination is the minimum necessary combination for it to work successfully but here the comparison:

|Right|Default (not working) | Adjusted (working)
|:-|:-|:-
EXTERNAL_VISITS | YES | YES
SORMAS_REST | YES | YES
SEE_PERSONAL_DATA_IN_JURISDICTION | YES | YES
SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION | YES | YES
SEE_SENSITIVE_DATA_IN_JURISDICTION | YES | YES
SEE_SENSITIVE_DATA_OUTSIDE_JURISDICTION | YES | YES
VISIT_CREATE | NO | YES
VISIT_EDIT | NO | YES
CONTACT_VIEW | NO | YES
CONTACT_EDIT | NO | YES
PERSON_VIEW | NO | YES
PERSON_EDIT | NO | YES
CASE_VIEW | NO | YES
CASE_EDIT | NO | YES

**Comment by markusmann-vg** [comment]
@kwa20 @SahaLinaPrueger So can this issue be discarded?

**Comment by kwa20** [comment]
@markusmann-vg @FredrikSchaeferVitagroup @SahaLinaPrueger  This issue can't be discarded because it means that the default userrole does not have the sufficient rights for the symptom diary interface to work. Before the update, the EXTERNAL_VSITS_USER was not adjusted, meaning that after the new user role concept has been implemented, the role stopped working. I assume that this will also be the case in production, yes.

**Comment by MartinWahnschaffe** [comment]
I had a look into the log. It looks like saving an external visit (VisitFacadeEjb.saveExternalVisit) calls the VisitFacadeEjb.saveVisit method which then calls checkCreateAndEditRights based on VISIT_EDIT.
This needs to be changed. From my understanding it should not be necessary to have the VISIT_EDIT user right to save an external visit. 
I'd propose that saveExternalVisit does not use saveVisit and instead replicates what it is doing or both use a shared core method.

**Comment by abrudanancuta** [comment]
The ticket will be verified on [ga1.sormas-oegd.de](https://ga1.sormas-oegd.de/) when it will be available on the version 1.76.0 snapshot
