### ISSUE TITLE
[DEMIS2SORMAS] If DiagnosticReport.Code is not "cvdp" the case is not created - lab message not processed

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10324]
### Bug Description

If DiagnosticReport.Code is not "cvdp" the case is not created even if message 'case saved' was displayed.
More detailed: After processing the lab message the error message appears: _An error has occured. An unexpected error occured. Please contact your supervisor or administrator and inform them about it._ After that the message "case saved" appears. But the case is not created in system and the lab message is not processed. 
### Steps to Reproduce

1. Upload a lab message to the DEMIS test server that includes anything other than "cvdp" for the DiagnosticReport.Code. For example: rtvp
2. If the DiagnosticReport.Code is not "cvdp", an error message should appear informing the user that the disease of the lab message could not be identified. Error message: "The tested disease of the lab message could not automatically be determined. Please manually verify that this lab message is about a disease to be dealt with in SORMAS."
3. Click 'continue'
4. Create a case
5. Save the case
6. Check if lab message is processed.

### Expected Behavior

No error message appears. Case can be saved and is visible in the system. Lab message is processed. 
### Screenshots

![5](https://user-images.githubusercontent.com/100844689/189312726-21afcda7-a322-4a64-a35e-fecf5d796053.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.75
* Android version/Browser: Edge
* Server URL: 1402
* User Role: admin

### Additional Information

postman.file: 
[DEMIS.rtvp.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9534070/DEMIS.rtvp.txt)

Maybe something is wrong with the file?

**Comment by abrudanancuta** [comment]
Validated together with @leventegal-she on his local environment
