### ISSUE TITLE
Lazy loading for directory views [3+2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1032]
The following steps need to be done for each of the directory views mentioned below (all except cases). See CaseGrid and CaseFacadeEjb.getIndexList for comparison #1012.

1. Facade get method needs to be extended with range parameters (first and count)
2. Facade get method needs to be extended with sorting parameters
3. replace containers with new lazy vaadin 8 container: https://vaadin.com/docs/v8/framework/datamodel/datamodel-providers.html#datamodel.providers
4. update grid selection https://vaadin.com/docs/v8/framework/datamodel/datamodel-selection.html#datamodel.selection

This needs to be done for 

- [x] contacts
- [x] events
- [x] tasks
- [x] samples
- [x] visits
- [x] event participants
- [x] users
- [x] regions
- [x] districts
- [x] communities
- [x] health facilities

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove manuel column definition for user role and user active status
