### ISSUE TITLE
Endless loading when performing bulk actions on the Event Participants tab of an Event with a large number of Participants

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10322]
### Bug Description
When performing Bulk Actions (eg. Delete) for a large number of Event Participants (17.000 EP), takes such a long time that the server is an infinite loop. 
I waited more than 35 minutes and nothing happened, I had to restart the server.

Logs:
[deleting a huge number of EP.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9532965/deleting.a.huge.number.of.EP.txt)
Unfortunately, the logs don't show anything.

### Steps to Reproduce

1. Open an Event with a large number of Event Participants (eg. 17.000);
2. Navigate to the Event Participants tab;
3. Enter the Bulk Edit Mode and select all the Event Participants;
4. Click on Bulk Actions and then click on 'Delete'
5. Select a reason for deletion;

### Expected Behavior
The deletion should take a reasonable amount of time.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/189288313-3fe7f7b2-1ea4-4854-8844-f4e21e643dc3.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT 
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Admin, NatUser

**Comment by StefanKock** [comment]
#10461 aims to avoid bulk actions with to much data to handle all at once.
