### ISSUE TITLE
The 'Facility Name & Description' should be optional in the creation form.

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10336]
### Bug Description
In the Case creation form, when the 'Place of Stay' = 'Facility' and 'Facility' = 'Other Facility', the 'Facility Name & Description' should be optional.

### Steps to Reproduce

1. Create a new Case and select the Place of Stay details like in the first screenshot;
2. Open the Case page and inspect the 'Facility Name & Description' field.

### Expected Behavior
The 'Facility Name & Description' should be **optional** in the creation form.

### Screenshots
Create New Case form:
![image](https://user-images.githubusercontent.com/89522688/189627160-9465067c-306a-4518-870f-643abc16fd60.png)

Edit Case page:
![image](https://user-images.githubusercontent.com/89522688/189630089-f30485a7-b34d-456d-b528-c25e94958ebb.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0
* Android version/Browser: Chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: Admin, National User

**Comment by MateStrysewske** [comment]
@roxanamlendea I believe it's actually the other way around. If I'm not mistaken, we've removed the requirement from that field on purpose, and the inconsistency would then actually be that it's still required in the creation form.

@MartinWahnschaffe Do you remember what our current take on this should look like?

**Comment by MartinWahnschaffe** [comment]
@MateStrysewske No, unfortunately I have no idea.

**Comment by MateStrysewske** [comment]
Okay, then I'd just decide that we should change the creation form and make the field optional there.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.77.0-snapshot (406c2ee) on test-de.sormas.netzlink.com environment
