### ISSUE TITLE
ability to use a custom application logo

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1033]
Ghana would like to replace the Sormas logo with a custom logo of GHS.
We would also like to add a "Powered by ..." at the footer of the application.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please remember to discuss this

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @faatihi 
I do not think we will be able to remove SORMAS logo from "SORMAS". I would suggest we include the ability to add custom logos to the login page for any of the countries in addition to the SORMAS logo there. About powered by.. what is the reason to have this? And powered by who? :)

**Comment by faatihi** [comment]
@hzi-braunschweig , I think your suggestion about adding custom logo to the login page will be satisfactory. 
For the powered by, we're looking at displaying the tech company that handled the adaptation and implementation of sormas for a country. In the case of Ghana, it is handled by GCNet. So, we would like to have something like Powered by GCNet somewhere in the footer. A placeholder could be provided for  a custom html.

**Comment by faatihi** [comment]
I would like this issue to be tagged with the "Ghana" tag

**Comment by MartinWahnschaffeSymeda** [comment]
See #1194
