### ISSUE TITLE
Consider right EVENT_VIEW (View existing events) in the case directory 

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10346]
### Bug Description

A user without the right EVENT_VIEW (View existing events) can see data about the event in the case directory. 

![image](https://user-images.githubusercontent.com/101708230/189860532-3d174639-c426-4326-93f8-85a222cacd39.png)

### Steps to Reproduce

1.  Log in as Admin and find a user whit hasn't the rights "View existing events" /  EVENT_VIEW 
2.  Login with this user e.g. beke1 / B-Rolle
3.  Open the case directory in the detailed view 

### Expected Behavior

- [ ] Hide the columns related to events. 
- [ ] The data should not be put into the CaseDataIndexDto as-well when the user right is not present

### Screenshots

User roll in the admin view
![image](https://user-images.githubusercontent.com/101708230/189859416-4d5858a4-9ba3-41cc-aebd-ccec883c17db.png)

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser: Chrome
* Server URL: test1401
* User Role: Admin / beke1

**Comment by SahaLinaPrueger** [comment]
Solution as discussed with @MartinWahnschaffe:
UI: Hide columns if EVENT_VIEW is not given
Backend: hide there, too and leave empty

**Comment by roxanamlendea** [comment]
The data is still displayed on the Case Directory - Detailed View for a user with no EVENT_VIEW user rights.

![image](https://user-images.githubusercontent.com/89522688/192549914-6b0a7cbb-07df-42be-93e0-e6b8bb03113e.png)
![image](https://user-images.githubusercontent.com/89522688/192550033-dbdf6c22-5272-4241-bd3a-77d9b4c36ab0.png)

Steps to reproduce:
1. Create a new user role: select Surveillance Officer as Default User Role; then set 'No all' for the Events section;
2. Create a user with the User Role from step 1;
3. Log in with the user and open the Cases Directory in Detailed View.
4. Search the Event-related columns.

**Comment by roxanamlendea** [comment]
erified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT from the development branch.
