### ISSUE TITLE
Missing validations in the backend when data is created via API endpoints

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10343]
### Bug Description
- Travel Entries can be created via API without Point of Entry Details, even if it's a mandatory field.
- Events can be created via API calls without an Event Title, even if it's a mandatory field.
- Samples can be created without the 'Specify other type' being filled in, even though it's a mandatory field.

### Steps to Reproduce

Scenario 1: Travel Entries can be created via API without Point of Entry Details, even if it's a mandatory field.
1. Create a new Person via POST Person endpoint;
2. Create a Travel Entry via POST Travel Entry endpoint, set 'Other airport' as 'pointOfEntry' and leave the 'pointOfEntryDetails' empty;
3. Check the Travel Entry in the UI.

![image](https://user-images.githubusercontent.com/89522688/189680350-00ce98f0-3876-4452-b73d-16bf366441fe.png)
![image](https://user-images.githubusercontent.com/89522688/189680442-19d09940-97cd-499c-886c-eb483ebea2f8.png)

Scenario 2: Events can be created via API calls without an Event Title, even if it's a mandatory field.
1. Create a new Event via POST Event endpoint and in the body, leave the 'eventTitle' empty;
2. Check the Event in the UI

![image](https://user-images.githubusercontent.com/89522688/189681219-de804ce6-244b-4e20-a7d7-ba193e807c94.png)
![image](https://user-images.githubusercontent.com/89522688/189681276-f2daac06-7082-4dae-aff7-0322d20f6ed6.png)

Scenario 3: Samples can be created without the 'Specify other type' being filled in, even though it's a mandatory field.
1. Create a Sample for a Case via POST Sample endpoint, set 'Other' as 'sampleMaterial' and leave the 'sampleMaterialText' empty.
2. Check the Sample in the UI.

![image](https://user-images.githubusercontent.com/89522688/189681912-f70a1dce-f44f-4717-99ae-0eb643c75628.png)
![image](https://user-images.githubusercontent.com/89522688/189682078-d82c038e-0eb7-49f0-bc53-a6d39a6bffe2.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: admin, national user

### Additional Information
Edit by @JonasCir :
* This is similar to issue #10110 . You can take a look at the following PR: #10238
* General approach to fix this is to add `NotNull/NotEmpty` annotations to the DTOs
* Then go to the `validate` method in the corresponding EJB and check for unnecessary not null checks etc. which should removed in the method and be added to the DTO
* Feel free to assign to @JonasCir for review
* Don't forget to mention to add the changes to the release notes. It is a breaking change.

**Comment by adinaflorea9** [comment]
![image](https://user-images.githubusercontent.com/96909231/193032879-e8f9658b-1130-4861-a7f9-2468672cad9a.png)

Samples can not be saved as 'Sample Material' is considered missing.

**Comment by roxanamlendea** [comment]
Reopening the ticket because now Travel Entries can no longer be created in the vaadin app if a Point of Entry is selected.  'Point of Entry Details' should be mandatory only when 'Other airport/seaport/ground crossing/point of entry'.
![point of entry](https://user-images.githubusercontent.com/89522688/193033275-d7d629b1-bd21-486f-b4a9-9eed9477e920.gif)

**Comment by roxanamlendea** [comment]
> ![image](https://user-images.githubusercontent.com/96909231/193032879-e8f9658b-1130-4861-a7f9-2468672cad9a.png)
> 
> Samples can not be saved as 'Sample Material' is considered missing.

The 'Specify other type' should be considered only when 'Type of Sample' = 'Other'

**Comment by JonasCir** [comment]
@andrei7bal I had to revert you PR and restored your branch. Turns out that `sampleMaterial`  and `pointOfEntryDetails` only show up if you select other in the UI. So they are allowed to be blank. Please move the check for both to validate method. If other is select, these fields are required to be not blank otherwise ignore them.
