### ISSUE TITLE
Cases and contacts can be recognized as such in the person directory even if they are not supposed to be recognized 

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10352]
### Bug Description

- persons who have attached cases and contacts can be recognized as cases in the person directory even if they are not supposed to be recognized 
- the quick filter _all_ shows persons who only have one entity as case or one entity as contact
### Steps to Reproduce

1. Log in as an admin
2. Go to the person directory and make sure there are cases and contacts mentioned
3. Create a role _without_ the right to see cases and _without_ the right to see contacts, but with the right to see persons (role described under _additional information_ )
4. Create a user with this role and open the person directory

### Expected Behavior

1. On the left side there is the menu-points _persons_ 
2. On the left side there are _no_ menu-points _cases_ or _contacts_
3. In the person directory the quick filter _case_ and the quick filter _contacts_ are missing
4. Under the quick filter _all_ ONLY the persons should be visible who have at least one entity as _event participant_ or _travel entry_
5. Error message should not appear? 

Additional information: I focus here on cases and contacts but if you see the created user roles below you may recognize that the right VIEW_EVENT PARTICIPANT and VIEW_TRAVEL ENTRY is not given, too. So actually no person or quick filter should be visible.

### Implementation Details

- [ ] In the person directory each quick filter should only be visible when the user has access to the related _VIEW right.
- [ ] As quickfix before implementing #10414: The `PersonAssociation.ALL` option shall only be shown if all other `PersonAssociation` values are allowed.

### Screenshots

Description:
- no quick filter 'contact'
- If i can count i will know there are at least 3 contacts in the system and i also know which persons are the contacts, because i can compare the persons in the quick filter _cases_ with the persons under the quick filter _all_ and the another quick filters are 0
- The error message _Access to the specified resource has been forbidden. Please contact your supervisor or administrator and inform them about it. Please reload the page to see the latest changes_ appears
![user role_1](https://user-images.githubusercontent.com/100844689/190120507-70b98f7e-9b75-4278-9625-14616d334659.gif)

Description: If you click on the quick filter _case_ and if you open a person you cannot see the entity _case_. That is good, but you KNOW that there is the entity because of the shown quick filter
![user role_2](https://user-images.githubusercontent.com/100844689/190123012-71c60f32-efcd-470a-9a11-934b19d9969d.gif)

Description: This is shown with the user role _admin_:
![user role_3](https://user-images.githubusercontent.com/100844689/190124865-67026f20-d2ed-498d-9b3b-4f67e596b960.gif)

### System Details

* Device: 
* SORMAS version: 1.75
* Android version/Browser: Edge
* Server URL: release-x
* User Role: viewcase / password: the default one

### Additional Information

Maybe the right _PERSON_VIEW_ means, that _all_ persons in the systems are shown by adding this filter. 
We have two problems, if the right is defined like this:
1. Why is the quick filter _contacts_ than not visible?
2. What can a user do, if he wants that a user neither can see the case directory nor the persons who ONLY have a case entity in the person directory but do not want to completely abandon the person directory?

user role:
[sormas_benutzerrollen_2022-09-13_case view.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/9564826/sormas_benutzerrollen_2022-09-13_case.view.xlsx)

![image](https://user-images.githubusercontent.com/100844689/190114049-65b79b6c-1551-4fb5-847c-fada7e3b2c97.png)
![image](https://user-images.githubusercontent.com/100844689/190114248-59b6aa82-1546-4c90-b85e-c7332f7cc7ea.png)
![image](https://user-images.githubusercontent.com/100844689/190114326-83f22578-490c-4bfe-ac69-644049fb2cff.png)
![image](https://user-images.githubusercontent.com/100844689/190114446-6bc38c19-8169-4f75-bb3d-fe74b83876ff.png)
![image](https://user-images.githubusercontent.com/100844689/190114631-ef1a56be-2c37-4927-a16c-78a8170eef8d.png)
![image](https://user-images.githubusercontent.com/100844689/190114932-afa422ad-5298-40a3-bb78-026201b03ec3.png)
![image](https://user-images.githubusercontent.com/100844689/190115093-fcf68b15-26b3-428d-abd0-68bf5862f6de.png)
![image](https://user-images.githubusercontent.com/100844689/190115193-ec11ade5-34dc-4c25-a05e-85d6697a19ff.png)

**Comment by MartinWahnschaffe** [comment]
@SahaLinaPrueger For the aspect of not listing persons the user should not have access to, I have created #10414

**Comment by SahaLinaPrueger** [comment]
@MartinWahnschaffe thank you, so this issue is only about: In the person directory each quick filter should only be visible when the user has access to the related _VIEW right.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT (9449ed2) from the development branch.
Because 1.75.3 was already released, I opened new bug reports for the issues that I have found: https://github.com/hzi-braunschweig/SORMAS-Project/issues/10509 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/10511 .
