### ISSUE TITLE
dependencies between the user rights are incomplete

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10362]
### Bug Description

If you click on a specific user right (e.g. Edit existing cases) , dependent user rights (View existing cases, ...) are added automatically. There are user rights for which this link is missing. 

### Steps to Reproduce

First example
1. Take a user role, only the rights "Access Sormas UI" and "View existing cases" are selected
2.  assign it to a user
3. Switch to this user an click on cases
![image](https://user-images.githubusercontent.com/101708230/190347092-13272a0a-8ed1-4049-bf99-e1bdfc69364d.png)

Second example
1. Take a user role, only the rights "Access Sormas UI" is selected, the role is assigned to a user
2. Click on "Yes all" next to Trevel Entries 
3. save the role and switch the user
4. Click on travel Entries and open on travel entry
5. ![image](https://user-images.githubusercontent.com/101708230/190356872-641ea1bc-331e-4c06-b0b8-5b766cf9de61.png)
6. By adding the right ""View existing persons" this can be fixed

### Expected Behavior

Dependent rights should work consistently.

### System Details

* Device: Laptop
* SORMAS version: 1.75.0
* Android version/Browser:  Chrome
* Server URL:  test1401
* User Role:  Admin / BeKeDe - Role: B4

**Comment by MateStrysewske** [comment]
Closed in favour of #10361.
