### ISSUE TITLE
DTOs with `getUuid` should always implement `HasUuid`

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#10364]
### Problem Description
We are in a situation where we have quite an amount of DTOs which have a `uuid` field/implement `getUuid` but do not implement `HasUuuid` which is inconsistent. Additionally, the `uuid` field is duplicated in many DTO. This is bad for two reasons:
* it makes the diff for #9710 much harder as `uuid` is the most basic part of auditing and needs to be included in every audit log line. Introducing an `AbstractUuidDto` allows to configure the audit representation in one place and does not force us to change > 30 files unnecessarily. 
* It makes refactoring for DTOs much harder when we implement #7086

### Acceptance Criteria
The following archunit test passes:
```java
	@ArchTest
	public static final ArchRule testDtosWithUuidFieldMustImplementHasUuid = classes().that()
		.resideInAPackage("de.symeda.sormas.api.(*)..")
		.and()
		.haveSimpleNameEndingWith("Dto")
		.and()
		.containAnyFieldsThat(name("uuid"))
		.should()
		.implement(HasUuid.class);
```

**Comment by StefanKock** [comment]
@JonasCir don't create empty tickets, use ticket templates
