### ISSUE TITLE
Report date of cases created in app is set to 0:00 by default

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1036]
time synchronization issues in SORMAS. When you create  a case on the mobile app, the date shows 15 hours ago.... When you check pgadmin, you see a default (timestamp with time 0:00). This needs to be fixed.

**Comment by MartinWahnschaffeSymeda** [comment]
Just talked about this again. 

- [ ] The date field in the android app should kepp the date that is set via setValue (or a new date) and only adjust the day, month, year of it. The time should be kept.
- [ ] the directory views should not show "reported 5 minutes ago", but "today"

**Comment by MateStrysewskeSym** [comment]
- [ ] Handle empty dates
