### ISSUE TITLE
Annotation-based auditing

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#10377]
### Problem Description

For example, if we change the user name, the action gets log through the auditor, however, the name is not included in the log line. This shows that we need a mechanism which allows us two tweak the representation in the audit log in order to customize the result

### Proposed Change

Introduce an annotation which can be put onto fields and methods to build the representation in the log. All annotated fields/result of the method when called will be included in the log line.

### Acceptance Criteria

- Adjustable representation
- easy to use
- future-proof

**Comment by AndyBakcsy-she** [comment]
Validated ticket in a peer testing session with Jonas

**Comment by StefanKock** [comment]
I removed the usage of `reflections` because we suspect it is causing somehow a blocked deployment on the TEST stage.
Sometimes deployment of sormas-ear seems to not finish, the following log message does not appear:
```
Reflections took 460 ms to scan 2 urls, producing 126 keys and 5557 values (org.reflections.Reflections.java:219)
```

**Comment by StefanKock** [comment]
The deployment with the removed reflection usage did work for instances that failed sometimes in the last days: https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-DeployToTest/392/console
