### ISSUE TITLE
[Configurations Directory] 'Bulk actions' dropdown displayed when it should not 

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10376]
### Bug Description

In the 'Configurations' directory tabs the 'Enter bulk edit mode' - 'Bulk actions' dropdown is present in the 'Continents', 'Subcontinents', 'Countries', 'Areas', 'Regions', 'Districts', 'Communities', 'Facilities' and 'Points of entry' tabs. 

The 2 actions from the 'Bulk actions' dropdown displayed are 'Archive'/'De-Archive' depending on the filter option selected in the filter 'Active/Archive/All' entities from each tab. If 'Active' or 'Archived' are selected, the 'Bulk actions' dropdown is present. If 'All' is selected, the 'Bulk actions' dropdown is no longer displayed.
 
In the 'Areas', 'Facilities' and 'Points of entry' tabs, the 'Bulk actions' **button** is displayed even if 'All' is selected in the filter, and the button is clickable but no action happens. 

### Steps to Reproduce

1. Log in the web-app with an Admin+NatUser;
2. Navigate to the 'Configurations' directory - 'Areas', 'Facilities' and 'Points of entry' tabs;
3. In the 'Active/Archived/All' entities filter select the value 'All';
4. Click on 'Enter bulk edit mode'.

### Actual Behavior

The 'Bulk actions' **button** is displayed when 'All' is selected in the filter, and the button is clickable.

### Expected Behavior

In the 'Areas', 'Facilities' and 'Points of entry' tabs, the 'Bulk actions' should not be displayed when 'All' is selected in the filter, to be consistent with the behavior from the other tabs of the 'Configurations' directory.

### Screenshots

GIF of the steps and the behavior:
![Bulk actions](https://user-images.githubusercontent.com/96909231/190435350-38ad3912-da02-4087-9fd0-13667c26d578.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(5201c4d); 1.75.0 (most likely on even earlier versions too)
* Android version/Browser: Chrome
* Server URL: local machine; https://release-international.sormas.netzlink.com/
* User Role: Admin+NatUser

**Comment by carina29** [comment]
Meanwhile I've worked on this task I found another missing functionality. 
On the mentioned views ( Areas, Facilities and Point of Entry) also the Infrastructure Locked heading functionality is missing.

The Locked infrastructure heading appears when FeatureType.EDIT_INFRASTRUCTURE_DATA feature configuration is not enabled ( the value is false) which would mean that :
 - the import button should not be visible
-  the New Entry button should not be visible 
-  Bulk operations dropdown in Bulk edit mode will be visible only if the selected value is 'Active' 
- Infrastructure locked heading will appear ( see the screenshot)

![image](https://user-images.githubusercontent.com/47103965/208622573-3444c4f2-9f84-44b0-8154-e8d440528223.png)

I've agreed with @adinaflorea9 that this problem will also be fixed for the mentioned views in this bug ticket.

**Comment by dragosb-vg** [comment]
Validated on **test.sormas**(for bulk actions button) and **test-de3**(for locked infrastructure) on Version: 1.78.0-SNAPSHOT ([fe71891](https://github.com/hzi-braunschweig/SORMAS-Project/commits/fe71891c46dddb15794f29892e48706364f92e6e))
Both issues were also checked using the local system on latest development build.

1. 'Bulk actions' button is no longer displayed when 'All points of entry' is selected
- behavior is consistent on all mentioned Configuration' section tabs (_'Areas', 'Facilities', Points of entry'_ tabs)
- behavior is consistent no matter the actions' order (bulk mode button<-> filtering dropdown select)

2. 'Locked infrastructure' warning and functionality limitations are implemented for 'Areas', 'Facilities', Points of entry' tabs of the **Configuration** section.
- 'Locked infrastructure' warning is present (upper left page, in line with page title)
- no import button
- no new entry button
- 'Bulk actions' dropdown visible only for **Active** entities (areas, facilities, points of entry)

![image](https://user-images.githubusercontent.com/111864167/208905929-a5a5e490-68f6-4d31-a2a9-8f85640f5a3c.png)

![image](https://user-images.githubusercontent.com/111864167/208905741-02109c7e-279b-45a1-8b98-309158d58764.png)
