### ISSUE TITLE
[Configuration - Outbreaks] Error message appears in the 'Configuration' directory if outbreaks exist for disabled diseases

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10394]
### Bug Description

When entering the 'Configuration' directory, an error message is displayed if outbreaks exist for diseases which have been disabled in the meantime.

### Steps to Reproduce

1. Log in with an Admin+National User and create outbreaks for a few diseases (AFP and Cholera);
2. In the Data Base, open the 'diseaseconfiguration' table and disable AFP and Cholera (set to 'False': 'primarydiseaae', 'casesurveillanceenabled' and 'aggregatereportingenabled');
3. Save the changes and restart the server;
4. Log back in the app with the same Admin+National User and click on the 'Configuration' directory.

### Actual Behavior

An error message is displayed and only 1 tab of the directory is visible:
![image](https://user-images.githubusercontent.com/96909231/191023199-feb7c859-17e2-4079-92d4-8186d76fda4a.png)

### Expected Behavior

No error message should be displayed; all tabs of the directory should be visible.

In regards to the outbreaks that were created and whose diseases have been disabled, @MateStrysewske and/or @MartinWahnschaffe could you please take a look and specify the expected behavior:
~~- should the diseases still be listed and the outbreaks visible?~~
- the diseases should not be listed (as the behavior currently is) and the outbreaks not be visible.

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(a9b2e5b) - could not determine whether this is reproducible on earlier versions or not as I do not have access to the DB of testing instances in order to disable the diseases
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Logs from the local machine:
[outbreaks.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9599101/outbreaks.txt)

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe I would just ignore diseases that are inactive in this view, i.e. make sure that outbreaks retrieved from the backend for these diseases are not processed any further. What's your take on this?

**Comment by MartinWahnschaffe** [comment]
Agreed. I'd also simply ignore those outbreaks.

**Comment by adinaflorea9** [comment]
Updated the expected behavior according to the comments from above.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.76.0-SNAPSHOT (a4749d0).
