### ISSUE TITLE
'Facility name' field is mandatory in the Case Line Listing

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10395]
### Bug Description
In the Line Listing form on the Cases Directory, the 'Facility name' field is not marked as being mandatory, even though it is.

### Steps to Reproduce

1. Open the Cases Directory and click on 'Line Listing';
2. Fill in the mandatory fields; Select 'Facility Category' = 'Medical Facility'; 'Facility Type' = 'Hospital' and 'Facility' = 'Other Facility'; 
3. Inspect the 'Facility name' field;

### Expected Behavior
The 'Facility name' field should not be mandatory.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/191023354-1751c2b3-d67a-49a7-bfc5-76f2c6665bd2.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.75.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin + national user

**Comment by MateStrysewske** [comment]
@roxanamlendea Updated the expected behaviour because the field should not be mandatory anymore.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.79.0-SNAPSHOT (ff9d227).
