### ISSUE TITLE
Sample can not be edited, deleted or saved

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10392]
### Bug Description

Samples cannot be edited, saved or deleted.  The fields are not accessible and the buttons are inactive.

The behavior is observed in diverse automatic test since September 15th.  

A further check has shown: 
By adding the appropriate user rights the bottons are shown. But they are inactive. 

### Steps to Reproduce

1.   Select or create a user who has all the rights in the Sample Testing section. 
2.   Create a Case
3.   Add a "New Sample"
4.   Open this Sample and try to work with it

### Expected Behavior

The fields should be editable and the buttons should be active. 

### Screenshots

Admin
![image](https://user-images.githubusercontent.com/101708230/190984729-3f9398d7-f99e-4fdc-a464-8e3ce95d0e61.png)
![image](https://user-images.githubusercontent.com/101708230/190985162-8346c7bf-5d36-4d22-a9b5-fa2e53e364d4.png)
BeKe
![image](https://user-images.githubusercontent.com/101708230/191710244-56fb5c72-64b1-469a-9673-0ff26f7668a2.png)
![image](https://user-images.githubusercontent.com/101708230/190989090-32c96a3d-e1ec-409d-84ff-7ff41f8e80b8.png)

![image](https://user-images.githubusercontent.com/101708230/190989583-9466ee63-2470-4230-bd98-32672eb89d70.png)

### System Details

* Device: Laptop
* SORMAS version:  1.76.0
* Android version/Browser:  Chrom and automated tests
* Server URL: test-de and test-auto
* User Role: Admin

### Additional Information

The behavior was confirmed on test-de with the user BeKe and changed user rights.

**Comment by MateStrysewske** [comment]
Have the samples been created by the user you're using? Are they in the same jurisdiction as the user jurisdiction, if the user has a jurisdiction at all (I guess not since it's got the Admin user role)? Does the user have the user rights to see personal/sensitive data?

**Comment by markusmann-vg** [comment]
@roxanamlendea Please recheck wether this can be closed because it's covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/9693

**Comment by KernB** [comment]
The samples were each created with the same user. I repeated the test with my user. For this purpose he got the right "Create new sample". The behavior in still present. I did not change the case or the user between saving and editing. 
The Admin has the Rolls Administrator and National User. At the National Use and me individuell roll  "See personal / sensitive date in jurisdiction" are active.

**Comment by JonasCir** [comment]
Hey I take a look myself: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9693 did not change any logic and was re-reviewed twice now, so I would suggest we keep it closed and I investigate this issue on its own.

**Comment by JonasCir** [comment]
PR is up

**Comment by dragosb-vg** [comment]
Validated on test.sormas on Version: 1.76.0-SNAPSHOT [(cfb8bd9)](https://github.com/hzi-braunschweig/SORMAS-Project/commits/cfb8bd9648ec455b63cec7d1ec2944240a70dd5d)
Samples can be created/deleted/edited with any user with rights.
- checked users with/without Sample testing rights
- checked behavior with user having a custom user role with different configurations (checking various access restrictions).

![image](https://user-images.githubusercontent.com/111864167/192505692-a0733377-7474-45e5-9767-3cf30d1cbdc4.png)
