### ISSUE TITLE
Missing PERSON_VIEW and PERSON_EDIT rights have side effects

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#10409]
### Bug Description

When a user role has the rights to view and edit entities that are connected to persons, it is not required to also select either PERSON_VIEW or PERSON_EDIT rights. Since associated entities like cases, contacts and event participants are dependent on persons, this results in errors and side effects when trying to use the system.

Entities can neither be created, edited or properly navigated through.

### Steps to Reproduce

1. Create a user role that has view, create and edit rights for person associated entities but is missing person view and edit rights
2. Create a user and give them this user role
3. Login as the user and try creating, navigating through and editing associated entities

### Expected Behavior

Person related entity rights should be reliant on either PERSON_VIEW and PERSON_EDIT rights respectively

### Screenshots

Examples:

<img width="679" alt="userRoleTests" src="https://user-images.githubusercontent.com/70317594/191334902-68ec5004-4f8e-4896-b501-cef7a59e17a9.PNG">
<img width="570" alt="userRoleTests2" src="https://user-images.githubusercontent.com/70317594/191334908-ca854b26-4b9a-47c3-9ff3-6781d68b6c7b.PNG">
<img width="882" alt="userRoleTests3" src="https://user-images.githubusercontent.com/70317594/191335094-9ef272fe-e987-4613-9b3c-576a7161aada.PNG">

### System Details

* Device:
* SORMAS version: 1.75.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
This is probably what causes #10361. Added a reference to this issue there, we can probably close this one as soon as #10361 has been tackled.

**Comment by JaquM-HZI** [comment]
@kwa20 so cause 10361 is closed, can we close this one?
