### ISSUE TITLE
[S2S] Add Test Mode to the s2s activation script

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#10400]
### Feature Description

When activating S2S a python script needs to be run in order to align the infractructure data with central data.
Depending on the status of the systems infrastructure data some problems may occur (i.e. when multiple communities or districts exist with the same name and external ID). So we should have a way to test the outcome without actually changing anything.

### Proposed Change

Add a test mode to the python script that simulates every change without actually performing any changes in the database and creates a log file with every problems that have been encountered.

### Additional Information

@JonasCir @SahaLinaPrueger

**Comment by SahaLinaPrueger** [comment]
> creates a log file with every problems that have been encountered.
@JonasCir does this log file show +/- number of the following infrastructure data, if value differs from default value?
Number of active continents: 6
Number of active subcontinents: 27
Number of active countries: 199
Number of active regions: 16
Number of active districts: 432
Number of active communities: 13372

**Comment by AndyBakcsy-she** [comment]
validated ticket with Jonas in a peer testing session
