### ISSUE TITLE
Occupation types let contact and event participant imports fail

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#10404]
### Bug Description

When importing event participants that include an `occupationType` in their associated person, the import fails with the following error message:

_Unexpected error when trying to import this case. Please send your error report file to an administrator and remove this case from your import file._

used files:
[sormas_import_eventparticipant_occupationTypes.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9608339/sormas_import_eventparticipant_occupationTypes.csv) --> error
[sormas_import_eventparticipant_NoOccupationTypes.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9608340/sormas_import_eventparticipant_NoOccupationTypes.csv) --> successful
[sormas_import_contact_occupationType.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9609830/sormas_import_contact_occupationType.csv) --> error
[sormas_import_contact_NoOccupationType.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9609831/sormas_import_contact_NoOccupationType.csv) --> successful

### Steps to Reproduce

1. Create an event with a jurisdiction and import an event participant import file that includes the occupation types.
2. Import a contact with the occupation type being filled.
3. As a control, import the same files with missing occupation types and also try case import files.

### Expected Behavior

The imports should be successful and the occupation type set according to what was specified in the import file.

### System Details

* Device:
* SORMAS version: 1.75.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

When testing this for cases, the import was successful.

**Comment by StefanKock** [comment]
I have a feeling that #10324 is somehow linked to this.

**Comment by carina29** [comment]
Hello all,

I've fixed the problem, the ticket is in review now. 
In case of eventparticipant import there was a problem with the used .csv template too/
In the csv file the values for occupationType were added as firstname (the position was wrong).
I'll attach here the .csv files I've used for contact and eventparticipant import. 
In both cases the creation of the eventparticipants was with success.

Contact import:
[sormas_import_contact_occupationType_laboratory_staff.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9673093/sormas_import_contact_occupationType_laboratory_staff.csv)

![ContactImport2](https://user-images.githubusercontent.com/47103965/192991747-34f0c4b8-3f10-49e5-b10c-92715cc03c79.PNG)

EventParticipant import:
[sormas_import_eventparticipant_occupationTypes.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9673107/sormas_import_eventparticipant_occupationTypes.csv)

![EventParticipantImport1](https://user-images.githubusercontent.com/47103965/192991797-7cfd1291-6cf7-47c8-966b-79399eb0d689.PNG)

![Success](https://user-images.githubusercontent.com/47103965/192992120-65d32a00-a963-4578-ae5b-34ad8d8a9fc2.PNG)

Kind regards, 
                      Carina

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.76 deployed on test-de2 environment. (1.75.3 was already included in the development branch which was deployed to test-de2)
