### ISSUE TITLE
Clarify outcome and present condition [0]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1041]
The current definition of present condition is confusing with the outcome as one can argue that the outcome variable is a variable that is derived from the present condition at any time as the outcome can't be in the future of the current time. A suggestion is to redefine current condition to "Presenting condition" and move it from person tab to case tap. This presenting condition (Alive,) is the **condition at the initial time that the  person was notified at HF**. The outcome will then be the condition at the end (as of current time).

Another option is to drop the outcome, keep the current "present condition" variable and add add the "presenting condition" variable. The outcome will then be a derived variable of the current condition variable. What is your suggestion please?

**Comment by MartinWahnschaffeSymeda** [comment]
In yesterday's meeting we decided to 

- [ ] change the caption "present condition" to "person condition" or "present condition of person" and
- [ ] change the caption of "outcome" to "case outcome" or "outcome of case"
