### ISSUE TITLE
Description and default value for user role properties

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10410]
### Problem Description
When creating a new user role the meaning of the checkboxes "Has optional health facility" and "Port health user" are not clear to users.

![grafik](https://user-images.githubusercontent.com/23217632/191462622-72ae5150-c328-4897-9809-6366f97c5629.png)

### Proposed Change
- [x] Both values should be "false" by default
- [x] Optional health facility should only be checkable when the user role is not on HEALTH_FACILITY jurisdiction level
- [x] Optional health facility should be set to false when it is disabled based on HEALTH_FACILITY
- [x] Change description (tooltip) of the optional health facility field: "Allows to associate a user to a health facility even though the user is not on health facility jurisdiction level. When the user is entering new data, e.g. a case, the place of stay facility will be pre-filled." The captions should remain unchanged.
- [x] Change description (tooltip) of the port health user field: "User is a port health user and can only access cases and related data that is associated to a point of entry in the user's jurisdiction." The captions should remain unchanged.

**Comment by carina29** [comment]
A fix needs to be done for this task: has optional health facility should have false default value. I'll open a PR for the fix

**Comment by dragosb-vg** [comment]
Validated on test.sormas Version: 1.76.0-SNAPSHOT ([692bb57](https://github.com/hzi-braunschweig/SORMAS-Project/commits/692bb57bcb9bab33d7094cd5d9f5c98ef0af43ef))
Optional health facility  & port health user checkboxes are unchecked by default.
Optional health facility is disabled on 'Facility' Jurisdiction level.
Optional health facility is unchecked and disabled according to HEALTH_FACILITY status.
Captions and tooltips are displayed according to specs.
![image](https://user-images.githubusercontent.com/111864167/193275081-77706867-27d4-42f3-ad50-d91dbeae0554.png)
![image](https://user-images.githubusercontent.com/111864167/193273444-6c29c8ee-509e-452c-8448-467214e0ca3c.png)
![image](https://user-images.githubusercontent.com/111864167/193274945-2c0f3a5c-8ffa-4f1a-9a10-1d452c1afeaf.png)
![image](https://user-images.githubusercontent.com/111864167/193275181-a9c561ba-f2ee-4a98-b62f-124ee5c1495b.png)
![image](https://user-images.githubusercontent.com/111864167/193275279-61dbee9e-da6c-47df-991b-91deb9b6ef30.png)
