### ISSUE TITLE
Person directory: Don't include persons based on entity types the user cannot access [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10414]
### Problem Description
#10352 pointed out problems accessing persons related to entities the user should not be able to access.
For example the person directory currently still lists persons related to a case to a user that does not have the right to view cases.

### Proposed Change
Only show persons that are related to entity types the user can access based on activated features and given user rights.

### Acceptance Criteria

- [x] The person directory only shows persons that are part of an activated feature **and** the current user is permitted to access via user rights.
- [x] All similar backend logic is changed according to this.
- [x] The person directory shows the "All" button, also if any association is not permitted for the current user.
- [x] Probable code redundancy with #10352 concerning permitted `PersonAssociation`s was reduced.

### Implementation Details

We need to apply the same logical changes to several methods in the backend:
1. `PersonService.createUserFilter` should not join entity types the user does not have access to (e.g. exclude travelEntryFilter, when the user is not allowed to view travel entries). For consistency the following methods need to be changed in the same way: 
2. `PersonService.getAllAfter`.
3. `PersonService.getAllUuids` (similar to `PersonService.getAllAfter`)
4. `PersonService.getSimilarPersonDtos`
5. `PersonService.inJurisdictionOrOwned`  (uses `PersonJurisdictionPredicateValidator`)
6. `PersonFacadeEjb.count` needs to match `PersonFacade.getIndexList` (that uses `createUserFilter`).

Change in logic: `PersonService.getAllAfter` and `PersonService.getAllUuids` currently contain logic that additionally takes persons by the users district into account. It was clarified with @MartinWahnschaffe that this must be aligned with all other methods: Getting persons just by users district will be dropped.

**Comment by StefanKock** [comment]
@MartinWahnschaffe there is some differences between `PersonService.getAllAfter` and `PersonService.createUserFilter`.

1. `createUserFilter` already checks if `FeatureType.IMMUNIZATION_MANAGEMENT` is not `FeatureTypeProperty.REDUCED`. But this is not considered for 
2. `getAllAfter` additionally takes persons in the users district into account.

More methods I found that go into the same direction:
- `PersonService.getAllUuids` also does it's own logic to find persons (similar to `getAllAfter`).
- `PersonService.getSimilarPersonDtos` looks in every `PersonAssiciation` without considering feature configurations or user rights.

**Comment by StefanKock** [comment]
After discussing my findings with @MartinWahnschaffe we came to the conclusion that this ticket is to big/wide ranging for a hotfix/micro release. There is a high risk of merge conflicts and diverging changes between `development` branch.

**Comment by StefanKock** [comment]
Code review was done, will wait for 1.76.1 to be finished (avoid merge conflicts) and then upstream merge development, recheck tests work and then merge it.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS  from the development branch - 1.77.0-SNAPSHOT(c6512f2).
