### ISSUE TITLE
Replace creation of therapies/clinical courses in StartupShutdownService with SQL script

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1042]
Iterating over all existing cases and creating therapies/clinical courses for them during server deployment makes the deployment fail when there are too many cases in the database. Remove this logic from the code and write SQL script instead.

Additional required actions:
- [x] Add logic to fillEntityFromDto that creates therapies/clinical courses if cases without those are received
- [x] Execute this script on the server as soon as the server update has been done
- [x] After ClinicalCourse has been added to the app, all cases have to be invalidated again -> #1005

**Comment by MartinWahnschaffeSymeda** [comment]
I have updated the 1.17.0 release with the fixed SQL script.
