### ISSUE TITLE
Endless loading of the page when a user with a configured user role clicks on the Tasks Directory

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10426]
### Bug Description
When a user with a configured user role (see the user rights in the attachment from step 1) accesses the Tasks Directory, leads to an endless loading of the page. Even if the user refreshes the page, the endless loading of the page doesn't stop.

### Steps to Reproduce

1. Create a user with the following user rights:
[Config_Admin2.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/9624883/Config_Admin2.xlsx)
2. Login with the user from step 1;
3. Open the Tasks Directory;
-> the server goes into an endless loading; even if the user refreshes the page, the endless loading of the page doesn't stop;
4. Edit the URL with '/login' in order to go to the login page (see the recording);
5. Fill in the username and password of a different user and log in;
-> the cache is not cleared and the user that is logged in, is the user from step 1, not the user from step 5.

### Expected Behavior
No endless loading should occur.

### Screenshots
![tasks directory endless loop](https://user-images.githubusercontent.com/89522688/191728017-5c5bfa77-eef8-4fba-bf91-8f42b8b80705.gif)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role:

### Additional Information
The issue is not reproducible on an older version (1.75.0).

<details>
<summary>Screenshots with the User Rights of the used User Role</summary>

![image](https://user-images.githubusercontent.com/89522688/191955354-0abb4fb5-a858-4eac-aec6-1fb6ed544807.png)

![image](https://user-images.githubusercontent.com/89522688/191955498-c51e1020-7add-4b67-849d-49263a5bee31.png)

![image](https://user-images.githubusercontent.com/89522688/191955700-d4d0f283-4b0c-4dd3-b5bb-1f560a5a49eb.png)

![image](https://user-images.githubusercontent.com/89522688/191955799-c94f5950-4db0-4e34-ba7a-ad2579846420.png)

![image](https://user-images.githubusercontent.com/89522688/191955843-7c922803-56e7-4e67-9e64-17c67e6c6c48.png)

![image](https://user-images.githubusercontent.com/89522688/191955895-0bc9c42b-944c-43a9-ab33-283adb40deda.png)

![image](https://user-images.githubusercontent.com/89522688/191955927-93205b9a-7241-493c-a8e2-41c38252b227.png)

**Comment by MateStrysewske** [comment]
@roxanamlendea Can you please attach screenshots of the user role in the UI? Recreating the user role based on the export file is pretty tedious. :)

**Comment by roxanamlendea** [comment]
![image](https://user-images.githubusercontent.com/89522688/191955354-0abb4fb5-a858-4eac-aec6-1fb6ed544807.png)
![image](https://user-images.githubusercontent.com/89522688/191955498-c51e1020-7add-4b67-849d-49263a5bee31.png)
![image](https://user-images.githubusercontent.com/89522688/191955700-d4d0f283-4b0c-4dd3-b5bb-1f560a5a49eb.png)
![image](https://user-images.githubusercontent.com/89522688/191955799-c94f5950-4db0-4e34-ba7a-ad2579846420.png)
![image](https://user-images.githubusercontent.com/89522688/191955843-7c922803-56e7-4e67-9e64-17c67e6c6c48.png)
![image](https://user-images.githubusercontent.com/89522688/191955895-0bc9c42b-944c-43a9-ab33-283adb40deda.png)
![image](https://user-images.githubusercontent.com/89522688/191955927-93205b9a-7241-493c-a8e2-41c38252b227.png)

**Comment by MateStrysewske** [comment]
Problem: I can't easily reproduce this on my machine. Is there any helpful log output when this happens on yours?

**Comment by roxanamlendea** [comment]
I checked the logs and they don't show anything :(
![tasks directory endless loop](https://user-images.githubusercontent.com/89522688/192518733-55bf2f86-c025-4600-9c38-2297ed5fde9c.gif)

**Comment by roxanamlendea** [comment]
I just noticed that the first screenshot I attached wasn't displayed. I edited the ticket and now it's displayed. The user that I used is a Community Level, your probably has 'None' as Jurisdiction Level, that's why it's not reproducible on your machine.

**Comment by MateStrysewske** [comment]
@roxanamlendea No, I could see that from the Excel file :) I've set up mine to be on Community level as well. Still can't reproduce it; I somehow feel like it's connected to the specific data set that you have on your device. May I ask you to add breakpoints to the TaskFacadeEjb:getIndexList and TaskFacadeEjb:count methods and check whether they're repeatedly called?

**Comment by markusmann-vg** [comment]
@MateStrysewske Please take a look at https://github.com/hzi-braunschweig/SORMAS-Project/issues/10426

**Comment by StefanKock** [comment]
@roxanamlendea please activate the `PerformanceLoggingIntercepter` so that we can see which method(s) take long.

**Comment by roxanamlendea** [comment]
I activate de the PerformanceLoggingIntercepter and I attach the logs. 
[logs with performanceLoggerIntercepter activated.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9718142/logs.with.performanceLoggerIntercepter.activated.txt)

**Comment by BarnaBartha** [comment]
Source: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9334

**Comment by AndyBakcsy-she** [comment]
verified ticket on local setup with hotfix version 1.75.4

**Comment by roxanamlendea** [comment]
I confirm that the issue is no longer reproducible on my local machine with the user role from the description and on the DB that I used when I discovered the endless loop.
