### ISSUE TITLE
[Event Tasks] The mobile app crashes when a Surveillance Officer tries to open the 'Tasks' tab of an event

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10436]
### Bug Description

If a Surveillance Officer tries to open the 'Tasks' tab of an event in the mobile app, the app crashes - either it changes its language to German and then crashes, or it immediately crashes and logs out the user.

### Steps to Reproduce

1. Log into the android app with a Surveillance Officer; 
2. Open an existing event and click on the 'Event tasks' tab.
 
### Actual Behavior

The behavior varies: the user is either kept logged in but the language switches to German; or the app crashes and the user is directly logged out.

### Expected Behavior

The Surveillance Officer should be able to access the tasks tab of events.

### Screenshots

GIF of the behavior:
![Tasks - SurvOff](https://user-images.githubusercontent.com/96909231/191959338-bcc6b9e0-be0f-4e16-a07f-ce4c42714d03.gif)

### System Details

* Device: Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.76.0-SNAPSHOT(https://github.com/hzi-braunschweig/SORMAS-* Project/commit/7cb38ebb29e5d122d925cf3c654b3c368abe6bc1)
* Android version/Browser: Android 11 (android-app)
* Server URL: local machine
* User Role: Surveillance Officer (android app)

**Comment by adinaflorea9** [comment]
Observed today on SORMAS version - 1.76.0-SNAPSHOT(138c03e) - the mobile app crashes even when the Surveillance Officer simply tries to enter the 'Tasks' directory. 

Logs:
[Logs Mobile app - Entering the tasks directory.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9654262/Logs.Mobile.app.-.Entering.the.tasks.directory.txt)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following behavior:

For tasks that were created by a Surveillance Officer (regardless of what entity they are associated with), either in the web app or the mobile app, if the SurvOff updates the task as 'Done' or 'Not executable' in the mobile app, and then clicks again just to open the task (regardless of whether it is before or after a synchronization is triggered), the mobile app crashes and an error is displayed in the logs:
[error task SurvOff.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9682109/error.task.SurvOff.txt)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following: the Surveillance Officer is no longer able to successfully create or edit tasks in the mobile app as the button to save them is no longer displayed, or when clicking on the 'Done' button the task is not saved.

**Comment by MateStrysewske** [comment]
@adinaflorea9 Should be fixed; note that the save option is supposed to not be shown when the user is NOT the creator and the task status is PENDING.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(6697884)
