### ISSUE TITLE
[Quarantine orders - Events] The title of an action associated with an event is not displayed in the generated quarantine order document

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10430]
### Bug Description

The quarantine order document associated with an event does not display the 'Action title' of the action associated with the respective event.

### Steps to Reproduce

1. Open an event and created an associated event action for it (fill in all the sections of the 'Create new action' form);
2. On the event page, create a new quarantine order document;
3. Open the document and observe the section related to the event action.

### Actual Behavior

The section where the event action title should be displayed is empty.

### Expected Behavior

If the action has a title set, then the quarantine order document should also display the action's title in the specified section.

### Screenshots

Screenshot of the template of the quarantine order document for an event:
![image](https://user-images.githubusercontent.com/96909231/191748672-f9898aae-b9da-4a37-8e6b-87393696fc8b.png)

Screenshot of the generated and filled in quarantine order document for an event:
![image](https://user-images.githubusercontent.com/96909231/191753920-f17e17c1-c71a-41c1-92c9-2303c75c2534.png)

Screenshot of the action associated with the event:
![image](https://user-images.githubusercontent.com/96909231/191754053-ef860493-1648-482f-80d1-280476d30b17.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(90f6723); 1.75.1
* Android version/Browser: Chrome
* Server URL: local machine; https://release-international.sormas.netzlink.com/
* User Role: Admin+National User

**Comment by StefanKock** [comment]
@adinaflorea9 I don't get what you say it's wrong. Your screenshot shows the `AD-Action Ttile`.
![grafik](https://user-images.githubusercontent.com/24678567/204766876-2438699b-b096-4972-9313-4e2796f0805c.png)

**Comment by adinaflorea9** [comment]
@StefanKock Thank you for pointing that out! I seem to have been mistaken - the field that I marked as empty in the screenshot is actually related to the 'Comments on execution' field from an action associated with an event - I have rechecked the behavior and everything is in order.

I will close this ticket as discarded.
