### ISSUE TITLE
[Events] Error message is displayed when the 'Facility' is set to 'Other facility' on an event page

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10431]
### Bug Description

If the field 'Facility' is filled with the option 'Other facility' on an event page, or event creation form, an error message is displayed when trying to save.

### Steps to Reproduce

1. Open the 'Create new event' form and fill in the mandatory information;
2. In the field 'Type of Place' select 'Facility';
3. Fill in the fields 'Facility category', 'Facility type', 'Facility' = 'Other facility', 'Facility Name & Description' = Camp;
4. Click 'Save'.

### Actual Behavior
 
An error message is displayed stating that they user did not specify a 'Facility type', even though a valid facility type was specified.

### Expected Behavior

No error message should be displayed as long as valid information was entered in all of the mandatory fields related to a facility.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/191762052-a28f265f-d2d4-4f95-9d34-b21286eb2ade.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(c3b3b1f)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+National User

### Additional Information

The behavior is not reproducible on earlier released versions, but I logged a separate ticket as I could not determine which ticket from the current sprint might have introduced the issue.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.76.0-SNAPSHOT (9449ed2) from the development branch.
