### ISSUE TITLE
Measles cases has option to create contact on app but this dies not show up as a tab in web version

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1043]
CSM, Measles, etc are diseases that we decided to hide the option to create contact as a SO. In Ghana , SORMAS version 1.16.0, the mobile app has option to create contact for all diseases but no option to view then on dashboard. I think this is urgent to correct before the training

**Comment by MartinWahnschaffeSymeda** [comment]
We have found and fixed this in the contet of #1004 and #1006. So it's part of the 1.17.0 release.
