### ISSUE TITLE
Users with access to contacts but no access to samples can't open contacts

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10451]
### Bug Description
When a user with a configured user role (with 'View existing contact' and 'Create new contact' user rights) opens a Contact, he cannot see the Contact page information, and he gets 'A problem has occurred' error message when he creates a new Contact, because he is missing the SAMPLE_VIEW user right.
[logs for opening an existing Contact.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9646590/logs.for.opening.an.existing.Contact.txt)
[logs for creating Contact.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9646592/logs.for.creating.Contact.txt)

### Steps to Reproduce

1. Navigate to the Users Directory, select the 'User Roles' tab and click on 'New User Role';
2. In the 'Create new user role' form, leave the 'User role template' empty', fiil in the Caption and set the 'Jurisdiction Level' to 'Nation'; Save;
3. Select the User Rights as in the screenshots from the Additional Information section;
4. Create a user with the User Role from step 2&3;
5. Log in with the user with the configured user role and open the Contacts Directory;
6. Open an existing Contact;
   -> the user doesn't see the content of the page:
![image](https://user-images.githubusercontent.com/89522688/192288393-54303d4b-58ba-4c75-9cc1-589e28c6fd6c.png)
7. Go back to the Contacts and click on 'New Contact';
8. Fill in the mandatory fields and Save;
  -> the following warning message is thrown:
![image](https://user-images.githubusercontent.com/89522688/192289123-8fe04ae7-cf3b-4d58-97cb-b78c018fb239.png)

### Expected Behavior
Probably the user should not have been able to save the User Role with that specific combination of user rights in the first place (the expected behavior needs to be discussed though)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT (138c03e)
* Android version/Browser: Chrome
* Server URL: local environment 
* User Role: see the screenshots

### Additional Information
<details>
<summary>Screenshots with the User Rights of the used User Role</summary> 

![image](https://user-images.githubusercontent.com/89522688/192287459-1108361e-deb0-4e6f-8d50-1e2e9bd59fe1.png)
![image](https://user-images.githubusercontent.com/89522688/192287543-af888b12-10ca-4f98-903c-8a5d302ddc91.png)
![image](https://user-images.githubusercontent.com/89522688/192287590-7a7fdad9-1841-453f-89f5-bdb93296b3aa.png)
![image](https://user-images.githubusercontent.com/89522688/192287629-56edc846-a0fa-4d18-b7e6-d6ff181b6e4a.png)

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the error message still appears when trying to create contacts through line listing or through the regular 'Create new contact form'.

Logs from the local machine:
[Contact Create.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9715025/Contact.Create.txt)

**Comment by MateStrysewske** [comment]
@sergiupacurariu Can you please take over? :)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(18b7aeb).
