### ISSUE TITLE
User with 'View existing travel entry' and 'Create new travel entry' user rights is unable to view and create Travel Entries

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10450]
### Bug Description
When a user with a configured user role (with 'View existing travel entry' and 'Create new travel entry' user rights) opens a Travel Entry, he cannot see the Travel Entry, and he gets 'A problem has occurred' error message when he creates a new Travel Entry, because he is missing the PERSON_VIEW and EXTERNAL_VISITS user rights.

[logs for opening an existing Travel Entry.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9646093/logs.for.opening.an.existing.Travel.Entry.txt)

### Steps to Reproduce

1. Navigate to the Users Directory, select the 'User Roles' tab and click on 'New User Role';
2. In the 'Create new user role' form, leave the 'User role template' empty', fiil in the Caption and set the 'Jurisdiction Level' to 'Nation'; Save;
3. Select the User Rights as in the screenshots from the Additional Information section;
4. Create a user with the User Role from step 2&3;
5. Log in with the user with the configured user role and open the Travel Entries Directory;
6. Open an existing Travel Entry;
   -> the user doesn't see the content of the page:
   ![image](https://user-images.githubusercontent.com/89522688/192258438-1a8d9e15-0353-45dd-aad9-702a47a8094e.png)
7. Go back to the Travel Entries Directory and click on 'New Travel Entry';
8. Fill in the mandatory fields and Save;
  -> the following warning message is thrown:
  ![image](https://user-images.githubusercontent.com/89522688/192258521-19c7a617-9885-405a-b87e-b874ed8f293f.png)

### Expected Behavior
Probably the user should not have been able to save the User Role with that specific combination of user rights in the first place (the expected behavior needs to be discussed though)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: see the screenshots

### Additional Information
<details>
<summary>Screenshots with the User Rights of the used User Role</summary>    

![image](https://user-images.githubusercontent.com/89522688/192258263-d7cc1abc-c06c-48b3-8404-52f453ffba05.png)
![image](https://user-images.githubusercontent.com/89522688/192258277-abec3b0c-d007-462d-a7a7-673c7fcf9278.png)

**Comment by MateStrysewske** [comment]
@roxanamlendea Is the EXTERNAL_VISITS right really relevant here? i.e. does the error still occur when you give the user the PERSON_VIEW right?

**Comment by dinua** [comment]
@MateStrysewske 
I have analyze the bug and in my opinion it seems fine . I created a role as describe in task and at fist when we try to create a travel entry the error occurred . To be able to create we need to add 2 new rights to the role TRAVEL_ENTRY_EDIT and TASK_VIEW
- TRAVEL_ENTRY_EDIT is needed in save method for travelEntry 
- TASK_VIEW is needed to see the task card in view

I don't know if anything should be done in this task

**Comment by MateStrysewske** [comment]
@dinua It should definitely be possible to create travel entries without the edit right, and also without the task view right; if the task view right is missing, the tasks card should simply not be displayed instead of an error being thrown. The save method should probably also be accessible for users with only the TRAVEL_ENTRY_CREATE right.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.77.0-snapshot(5684630)
