### ISSUE TITLE
[Performance] Filtering out the cases in the Merging Duplicate Cases Directory shouldn't take that long

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10460]
### Bug Description
The problem was described as an alternative scenario in ticket #10306 , but it wasn't in scope there, so a separate issue needed to be opened.
The issue was observed during the automated tests.

### Steps to Reproduce

1. Go to test-auto
2. Log in as a automation admin
3. Navigate to Case directory
4. Select an option to merge duplicates
5. Filter out f.e. cases with Covid as a disease on top of default set filter to include only cases created throughout last month
Waiting time for filtering out the results is longer than it was on 1.75 - 4 min 15 seconds

### Expected Behavior
Waiting time for filtering the results should take a reasonable amount of time.

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-auto.sormas.netzlink.com
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
This is basically what #9054 is about - improving the performance of this section. I'll close this issue right here because it will hopefully be handled in that ticket.
