### ISSUE TITLE
Limit bulk action load for "Edit" bulk actions [5]

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10461]
### Problem Description

When performing the Delete Bulk Action for a large number of Travel Entries (18.240 Travel Entries), takes such a long time that the server is an infinite loop.
I waited more than 40 minutes and nothing happened, I had to restart the server.
Unfortunately, the logs don't show anything.

<details>
<summary>Details</summary>

#### Steps to Reproduce

1. Open the Travel Entries Directory and make sure you have a huge number of Travel Entries 
(I attach a file with 18.240 Travel Entries: [deaimport (18240).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9655050/deaimport.18240.csv)
2. Enter the Bulk Edit Mode and select all;
3. Click on Bulk Actions and then click on 'Delete'

#### Expected Behavior
The deletion should take a reasonable amount of time.

#### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: admin + national user

</details>

### Proposed Change

- Still allow to select as much items as currently possible in the UI, but only process up to 500 entries or 60s (whatever comes first).
- Reload the UI with the leftovers (keep filtering, reselect all entries if possible), show a message how many items were processed in what amount of time and tell the user to continue if he likes to.
- Text message if max entries have been reached: ```The maximum amount of entries that can be processed at the same time have been reached (<maxEntryCount>). There are still (<entryCountLeft>) entries left to process. Do you want to continue the operation?```
- Text message if 60s have been reached: ```The bulk processing has been halted because the maximum amount of runtime has been reached (<maxRuntime>s). (<entryCountProcessed>) entries have been processed so far and there are still (<entryCountLeft>) entries left to process. Do you want to continue the operation?```

### Acceptance Criteria

- [ ] The user can easily continue by starting the bulk operation again.
- [ ] No bulk operation is noticed that still stalls the system.

### Implementation Details

- Create a new helper method that stops the bulk processing after 500 entries or 60s (whatever comes first) for all actions that currently process one entry per backend call. The user experience should be that the user gets an updated list with less entries so he can start the bulk action again to process the next entries.
- Debug logging that which bulk operation was interrupted, with amount of selected and processed entries, and how much time was spend.
- If we find any occurence where 500 entries or 60s still run into a deadlock, we should make the interrupt parameters flexible and lower the entry number where needed.

### Additional Information

- This does not change the architecture to directly speed up bulk operations (which is not easy and sometimes maybe not really possible), but limits the amount of data handled in the same transaction/roundtrip. The aim is to guarantee that operations finish within a defined timeframe instead of stalling to a complete stop.

**Comment by StefanKock** [comment]
The pattern applies in general for all entities that deletion is done one by one. If it's too much data, the system is probably overwhelmed.

**Comment by StefanKock** [comment]
@MartinWahnschaffe: Options:
1. Only allow a certain amount of entries to be processed at the same time: allow to select more but stop after an amount of data (100, 500?).
2. Working with pages in the eager grid to only select a defined amount of data (avoid loading too much data into the grid).
3. Dedicated function for deletion by query (no apperent use case for that).
4. Provide a dialog that shows the progress and allows to stop processing, warn if more than x entries are to be processed.
5. Transaction split per each delete call?

**Comment by StefanKock** [comment]
Discussed with @MateStrysewske: Create a new helper method that stops the bulk processing after 500 entries or 60s (whatever comes first) for all actions that currently process one entry per backend call. The user experience should be that the user gets an updated list with less entries so he can start the bulk action again to process the next entries.

**Comment by MateStrysewske** [comment]
Follow-up issues that will cover other bulk actions that have not been implemented in this issue: #11463 and #11464

**Comment by abrudanancuta** [comment]
The implementation made for this ticket it is like: When entering in bulk Edit mode, and selecting more than 1000 cases to edit, the timeout set is too 180 seconds or processing 500 entries. These settings depend how fast can be done the edit, either reaching 180 seconds first either 500 entries.
The message pop-up will look like this: 
<img width="641" alt="Screenshot 2023-03-05 at 12 41 28" src="https://user-images.githubusercontent.com/91872179/222958466-228ec9b6-8e90-417f-90a6-0d88532ed519.png">

**Comment by abrudanancuta** [comment]
Validated on test-de with the version: 1.81.0-SNAPSHOT (862c1bd)
