### ISSUE TITLE
Immunization Directory needs a long time to open

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10475]
### Bug Description

The immunization directory opens only after a long loading time. Times over 30 sec have been observed.  Since it was observed on an instance with a larger number (>800000 - Counter at the quick filter in the Persons Directory-) of immunizations, we suspect a connection here. 

A longer loading time was also observed when opening the person directory. 

### Steps to Reproduce

1. Click on Immunisations

### System Details

* Device:  Laptop
* SORMAS version: 1.76.0 1d465f0
* Android version/Browser:   Chrom
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Admin

**Comment by markusmann-vg** [comment]
Different performance tickets cover and improve this scenario
