### ISSUE TITLE
[Cases + Samples]National User can no longer edit multiple sections from cases and samples

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10474]
### Bug Description

I: A National User is no longer able to edit multiple sections from a case's page:
- [x] Responsible Jurisdiction;
- [x] Place of Stay;
- [x] Help needed in quarantine
- [x] Report GPS fields;
- [x] Additional relevant pre-existing conditions;
- [x] Follow-up status comment;
- [x] Responsible Surveillance Officer;
- [x] General comment;
- [x] Comments (Symptoms tab);
- [x] Previous hospitalization form (all the fields related to the jurisdiction and the 'Description');
- [x] Epidemiological data - 'Activity as case' - missing button 'New Entry'.

II: A National User is no longer able to edit multiple fields from a sample's page:
- [ ] Purpose of the sample;
- [ ] Date and time the sample was collected;
- [ ] Type of sample;
- [ ] Reason for sampling;
- [ ] Field sample ID;
- [ ] Laboratory;
- [ ] Requested pathogen tests;
- [ ] Requested additional tests;
- [ ] Sent/dispatched fields

III: A National User is no longer able to see the document that are uploaded to cases.

The behavior is reproducible regardless of whether the entities were created by the National User or another user.

### Steps to Reproduce

I and II:
1. Log in the web app with a National User;
2. Observe case pages and sample pages.

III:
1 Log in the web app with a National User;
2. Open a case and from the 'Documents' card, click on the 'New Document' button - 'Start Data Import' and upload any kind of document.

### Actual Behavior

I and II:
The user is not able to edit multiple sections from case pages and samples pages.

III:
The upload is successful, but the documents are not displayed for the National User on the 'Documents' card.

### Expected Behavior

I and II:
The user should be able to edit the sections mentioned in the 'Bug description'.

III:
The documents uploaded successfully should be displayed on the 'Documents' card.

### Screenshots

I and II:
GIF of the behavior:
![Fields not editable](https://user-images.githubusercontent.com/96909231/192978438-724e2f35-5b59-49e9-9803-a323f6ff5784.gif)

III:
GIF of the behavior:
![Documents upload](https://user-images.githubusercontent.com/96909231/194059072-093bd697-a4cd-4278-bd7a-35b825b8b28d.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(3b722ee)
* Android version/Browser: Chrome
* Server URL: local machine and nightly build test instances
* User Role: National User

### Additional Information

The behavior was initially observed during the run of the automated tests.

The behavior is not reproducible on the latest released version 1.75.2. 

The behavior was likely introduced by a ticket during the current sprint, but as it could not be determined which exact issue caused it, this current separate ticket was logged.

**Comment by adinaflorea9** [comment]
As discussed and tested with @dinua currently the behavior reported in the ticket regarding samples is no longer reproducible on our local machines with the latest version of SORMAS 1.76.0-SNAPSHOT(03765a5). Behavior will be re-tested again in case it becomes reproducible.

To be noted - the National User (default) does not have the user right 'Edit samples reported by other users' so they can only completely edit samples that they reported.

**Comment by leventegal-she** [comment]
The first point with editing case section is fixed by https://github.com/hzi-braunschweig/SORMAS-Project/issues/10547

Will be merged into development after the hotfix 1.75.4 release
