### ISSUE TITLE
Issues from the training: Draft version

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1048]
**Training feedback**
@MateStrysewskeSym @MartinWahnschaffeSymeda 
- Add VHFs for Ghana as they work with syndromic surveillance... -> #1075 
- Add No education to (secondary, primary and secondary dropdowns in app) -> #1073 
- Control officers and informants should see previous test done and also be able to provide documentation for rapid tests after they collect samples -> #1109 and #1134
- Change shipped to Sent/Dispatched -> #1072 
- Sample material should be type of samples -> #1110
- ~Provide time and date sample was shipped (Revise the validation rules for sample shipping date/time)~
- ~Add case class filter in weekly report section~ -> This will be part of the mobile dashboard
- USERS SHOULD BE ABLE TO HAVE ACCESS TO THIER OWN USER PROFILE TO UPDATE THEIR DETAILS -> #1091
- On the dashboard card, please separate event surveillance on its own (We need to start talking about the event surveillance dashboard) -> #461 
- On the dashboard, Proportion for disease burden differences (previous/current) and differences chart is required in addition to case count -> #1204
- Change "fatalities" to "Death" -> #1113
- Discussion on "Not yet classified": to think about another synonym
- Comment field for task reply disabled -> is enabled for the user who is allowed to do the task
- Select all (look into it) -> #1094 
- ~Check automatic case classification~ (was deactivated)
- Sex should replace Gender (Ghana label) -> #1114
- SORMAS for other priority Diseases!
        - Anthrax -> #833
        - Rabies -> #834 
        - AFP #1177
        - Polio #1177
- Timeliness and Completeness dashboard for tracking user performance
Use same KPIs for Nigeria All facilities and districts (Reporting units) #904
Task for GHS- Provide other indicators for timeliness and reporting from the GHS
- mobile app dashboard for district and informant levels. They need to see aggregate reports for their neighboring districts by cases. -> #88

**Comment by hzi-braunschweig** [comment]
-[ ] mobile app dashboard for district and informant levels. They need to see aggregate reports for their neighboring districts by cases.

**Comment by Chinedar** [comment]
- Date sample collected cannot be earlier than the date the case presented at the health facility

- when a wrong health facility is chosen on the first page of case creation, once the surveillance officer saves, he/she is unable to change this. Should this not be open for them to edit? 

- Informants in Ghana are trained as surveillance/contact officers. user-right access to be discussed for them.

- Admin needs to be able to edit health facility details on the configuration module. Can only add at the moment (not able to edit region, district and sub-district info at the moment).

- When a contact is converted to a case, all the properties (demographics and symptom details) should auto populate

- (most of my other points are already mentioned above)

**Comment by hzi-braunschweig** [comment]
-[ ] EPID number should not be active for the informant... Only the district level and above can change EPID number

**Comment by faatihi** [comment]
@MartinWahnschaffeSymeda , can I begin working on these issues, or we're waiting on the Refinement Board

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi I think you can take care of #1110, #1112, #1113 and #1114. I think a single pull request with individual commits for each ticket should do - not need for separate pull requests.
We will talk about the remaining issues next Tuesday at the sprint review.

**Comment by faatihi** [comment]
Ok. I'll tackle those.

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi I have refined additional issues:
#1134 Enable informants and officers to create and edit pathogen tests 
#1109 Add rapid testing to mobile app (requieres #1134)
#1066 Add "Rectal swab" as option of sample material.
#1091 Add user settings screen
#1115 When a contact is converted to a case, all the properties (demographics and symptom details) should auto populate

I think you can pick any of those and go forward with it. I'm not sure if the descriptions are detailed enough, so please comment when anything is not clear - Maté or me will try to reply.

**Comment by faatihi** [comment]
OK. I'll keep you all updated

**Comment by MartinWahnschaffeSymeda** [comment]
All points from this now have their own issues on github, so I'll close this,
