### ISSUE TITLE
Improve dev setup documentation [1]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#10480]
### Problem Description

We often got diffuse problems reported that setting up the dev environment. @valentinmikleuvg documented his setup process in a docx file.

### Proposed Solution

- Check the provided document what is different to existing documentation (unfortunately no diff to current documentation given).
- Improve [dev environment setup documentation](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/DEVELOPMENT_ENVIRONMENT.md).

### Additional Information

[SORMAS DEV SETUP .docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/9673165/SORMAS.DEV.SETUP.docx)

Also have a look into https://github.com/hzi-braunschweig/SORMAS-Project/pull/2375 to discuss with @MartinWahnschaffe how to proceed there.

**Comment by MartinWahnschaffe** [comment]
What about https://github.com/hzi-braunschweig/SORMAS-Project/issues/5414 - guess this also needs to be considered here.
