### ISSUE TITLE
Visits are created in the backend but not displayed in the UI for Case Contacts without follow-up

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10484]
### Bug Description
A Visit created for a Contact that has no Follow-up, is created in the backend (can be found in the db), but it is not displayed in the UI.

### Steps to Reproduce

1. Open a Case and select the Contacts tab;
2. Import a Contact that has 'No Follow-up'.
Here you can find an import file: [sormas_import_case_contact.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/9674183/sormas_import_case_contact.csv)
3. Open the Contact and select the Follow-up Visits tab;
4. Create a New Visit;

### Expected Behavior
The expected behavior needs to be discussed.

### Screenshots

![visits not displayed in the ui](https://user-images.githubusercontent.com/89522688/193021593-6d06db1e-96fa-4029-9e35-e3b33e074a49.gif)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local server
* User Role: admin + national user

**Comment by ChristopherRiedel** [comment]
@MateStrysewske and I agree that there is nothing wrong here. However, it is very confusing that visits outside the follow up offset (+/-30 days around the follow up period) can be created but never show up again. Therefore I will make sure that visits can no longer be created for outside the offset.

**Comment by ChristopherRiedel** [comment]
Doesn't seem to be a problem in the android-app.

**Comment by abrudanancuta** [comment]
Validated on test.de2 with the version: 1.79.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/58ddec978d941a6a6d2de0954c6a8c54ff27b033)
