### ISSUE TITLE
Filters on the Persons Directory are not working

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10509]
### Bug Description
The bug was probably introduced with ticket #10352.
On the Persons Directory, when the users uses the filters (the filter dropdowns, not the quick filters), no result is fetched. Nothing happens when the 'Apply filters' button is clicked.

LE: The filters work only after a quick filter is clicked.

### Steps to Reproduce

1. Open the Persons Directory;
2. Make sure that at least one Person has 'Present Condition of Person' = 'Alive';
3. Filter by Present Condition (select 'Alive') and click 'Apply Filters';

### Expected Behavior
The results should be fetched;

### Screenshots
![filtering persons directory](https://user-images.githubusercontent.com/89522688/193573691-287bbc6b-6d6e-4121-8c5b-3cebcae857e8.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.3
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: admin + national user

### Additional Information

Caused by #10352.

**Comment by StefanKock** [comment]
Needs to be picked to 1.75.4

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.76.0-SNAPSHOT (b71a6c3).
