### ISSUE TITLE
Mobile app ui is broken when language at login is not English

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#10504]
### Bug Description

This issue may have the same root cause as #10132
When the language at the point that the user login is not English, the menu items are hidden and the app can not be used, see image below.

### Steps to Reproduce

1. Connect a mobile app to https://release-international.sormas.netzlink.com/
2. Login using a surveillance officer account  + language == English (this works fine)
3. While logged in, change the language to French or German (all works fine)
4. While the language is not English, logout the user account
5. log in to the user account again, the UI is then broken with items hidden. However, synchronization works.
6. Change user language to English after step 5.  ( UI remains broken)
7. Logout  (after point 6 when the app is in English) and login again (UI still remains broken)

### Expected Behavior

Changes in the user language, either while logging in the first time to the app or after that app has been used in another language should not affect the app.
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/193334956-b12f5eda-7819-491b-90ca-f577aa09a8ac.png)

### System Details

* Device: Samsung Galaxy Tab A lite (SM-T220)
* SORMAS version: 
* Android version/Browser: 1.75.2
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: surveillance officer

### Additional Information

The logs from points 1 to 5 are too big to be attached here, they are in the corresponding Jira issue

**Comment by BarnaBartha** [comment]
Source : https://github.com/hzi-braunschweig/SORMAS-Project/issues/898

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0SNAPSHOT(18b7aeb).
