### ISSUE TITLE
'Facility Name & Description' field is not cleared when the Facility Category and Type are changed

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10514]
### Bug Description
'Facility Name & Description' field is not cleared when the Facility Category and Type are changed  on the Event page and in the Travel Entry page

### Steps to Reproduce

1. Open an Event;
2. Scroll down to the Location section and make the following selection:
![image](https://user-images.githubusercontent.com/89522688/193612215-e5b8ec93-eda3-4be7-9a57-ce2b4262c851.png)
3. Save the page;
4. Change the Facility Category and Facility Type;

### Expected Behavior
The 'Facility Name & Description' field should be cleared (like on the Case page);

### Screenshots

![facility description not cleared](https://user-images.githubusercontent.com/89522688/193612571-27614ed8-e4fe-4ce3-85e5-1d85478b375f.gif)

### System Details

* Device: Windows 10
* SORMAS version :Sormas 1.75.2
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin + national user

### Additional Information
Found while testing ticket #10431

**Comment by dragosb-vg** [comment]
Validated on **test-de** on Version: 1.76.0-SNAPSHOT ([ca4b9c5](https://github.com/hzi-braunschweig/SORMAS-Project/commits/ca4b9c5317cb0021b3072f9a63dec85f5f2d6cda))
Facility name is cleared when selecting "Other" for Type of place (Location section) in the Event details

![image](https://user-images.githubusercontent.com/111864167/195540755-0da89eea-25d2-41f1-a1d6-7cecee687553.png)

**Comment by StefanKock** [comment]
I reverted the change to release 1.76.0

**Comment by abrudanancuta** [comment]
I found another case when the facility is not saved:

1. As National Clinician, edit an Immunization
2. Add a Facility Category + Type + Facility
3. Save the edit of the facilities dropdown
4. Check the dropdowns for facility => At this point nothing is saved related to facility

**Comment by carina29** [comment]
@abrudanancuta I've tested the scenario mentioned by you. 
I can reproduce on my side too but this ticket (10514) will fix the problem if the other fields are in place and in the above mentioned scenario none of the fields will be saved. There is another bug.
Please open a ticket for this new bug.

**Comment by abrudanancuta** [comment]
A new ticket was created https://github.com/hzi-braunschweig/SORMAS-Project/issues/10675
