### ISSUE TITLE
Cards on the Person page are not displayed correctly

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10511]
### Bug Description
When users with configured user roles open Persons from the Persons Directory, some Cards are not displayed, or not displayed correctly;

### Steps to Reproduce

1. Make sure you have a Person which has all the entities associated: Case, Contact, Event, Travel Entry, Immunization;
2. Log in with the users described below, open the Person and inspect the cards on the right side of the Person page;

Scenario 1:
The Immunizations and Travel Entries Cards are not displayed, even if the user has _VIEW rights for these entities.
<details>
<summary>Screenshots with the User Rights of the used User Role</summary> 

![image](https://user-images.githubusercontent.com/89522688/193585175-6ba90308-a0ca-4f47-9f62-f163956c974f.png)
![image](https://user-images.githubusercontent.com/89522688/193585246-62a99735-2e03-4292-897c-5274a2b53626.png)
![image](https://user-images.githubusercontent.com/89522688/193585309-10ff2a6e-99f0-4540-84e1-1c3530aa7683.png)
![image](https://user-images.githubusercontent.com/89522688/193585355-35da96db-c225-46a3-af6a-7b289ea0e1b9.png)
![image](https://user-images.githubusercontent.com/89522688/193585414-0d9107e0-34e6-4fc4-bb19-cf6d6a566325.png)
![image](https://user-images.githubusercontent.com/89522688/193585480-03fba248-6a02-483a-905d-e59d50114f11.png)
![image](https://user-images.githubusercontent.com/89522688/193585528-6696ad65-2d6a-487d-8a1c-d7bea1b649d5.png)
![image](https://user-images.githubusercontent.com/89522688/193585570-8d54289f-f61f-424d-80da-4696c61f9814.png)

</p>
</details>

![image](https://user-images.githubusercontent.com/89522688/193581682-95c9b3ee-a548-4e79-aefc-d8b3add73016.png)

Scenario 2:
The Events, Immunizations and Travel Entries Cards are not displayed, even if the user has _VIEW rights for these entities.
<details>
<summary>Screenshots with the User Rights of the used User Role</summary> 

![image](https://user-images.githubusercontent.com/89522688/193587684-da523393-a5ca-4646-856b-5f08f6e914eb.png)
![image](https://user-images.githubusercontent.com/89522688/193587731-366b8fed-74b7-44d5-8098-babda71377ed.png)
![image](https://user-images.githubusercontent.com/89522688/193587784-8ec44f84-0dad-470d-800b-4e66146af498.png)
![image](https://user-images.githubusercontent.com/89522688/193587830-1f8d68b4-6d9f-43c1-b569-8433877faa8f.png)
![image](https://user-images.githubusercontent.com/89522688/193587857-ae8cb542-e2cb-40b8-a34f-47d99bb89018.png)
![image](https://user-images.githubusercontent.com/89522688/193587888-b5e705e7-564d-4a69-8b94-d8e85f74fbab.png)
![image](https://user-images.githubusercontent.com/89522688/193587931-70c51aa9-6177-4fec-aff8-b1f0e8d40c4c.png)
![image](https://user-images.githubusercontent.com/89522688/193587978-f9966987-4ddd-46aa-9bac-96c2a55788ec.png)

</p>
</details>

![image](https://user-images.githubusercontent.com/89522688/193587212-f0e9acd7-94d0-40b3-851d-702b6221c302.png)

Scenario 3:
The Travel Entry Card is not clickable.
<details>
<summary>Screenshots with the User Rights of the used User Role</summary> 

![image](https://user-images.githubusercontent.com/89522688/193588414-052580ee-965a-4bdf-a047-284ebd0d3a1c.png)
![image](https://user-images.githubusercontent.com/89522688/193588446-f7f763b5-af96-462a-8d0a-facbb0b2151b.png)
![image](https://user-images.githubusercontent.com/89522688/193588486-0a136135-141b-4cf7-985a-f2e613e48931.png)
![image](https://user-images.githubusercontent.com/89522688/193588519-a9f76b83-d62e-44d9-ab94-83a151818265.png)
![image](https://user-images.githubusercontent.com/89522688/193588553-305acd23-1413-4971-8e90-f4a4859a8b39.png)
![image](https://user-images.githubusercontent.com/89522688/193588595-2dab1a6b-8081-4e20-a269-00fd122479ca.png)
![image](https://user-images.githubusercontent.com/89522688/193588657-c0eecdc2-4920-45c4-821b-3420de003cf8.png)

</p>
</details>

![image](https://user-images.githubusercontent.com/89522688/193581759-242e9aeb-dac6-483c-b0d0-6008141df807.png)

### Expected Behavior
The Cards should be displayed according to the user rights.

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local environment
* User Role:

### Additional Information
Found these issues when testing the ticket #10352

**Comment by BarnaBartha** [comment]
Source: https://github.com/hzi-braunschweig/SORMAS-Project/issues/898

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the hotfix branch where SORMAS version is 1.75.4-SNAPSHOT(84e1f8a).
