### ISSUE TITLE
Facility is not pre-filled for users with an optional health facility

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10517]
### Bug Description

When the checkbox " Has optional health facility" is checked and the user is related to a certain health faciliy this health facility should be prefilled when the user is for example creating a new case.
### Steps to Reproduce

1.create a new user role
2. check the checkbox "Has optional health facility"
3. create a new user
4. link the user to the created user role and the facility
5.create a case

### Expected Behavior

facility should be prefilled
### Screenshots

![image](https://user-images.githubusercontent.com/96547924/193747151-3a27799d-9762-459d-abfa-5aa25ba6890f.png)

### System Details

* Device:
* SORMAS version: 1.75.2
* Android version/Browser:
* Server URL: test1402
* User Role: admin

**Comment by valentinmikleuvg** [comment]
waiting for more details and an example for expected behaviour when user have optional health facility checked but does not have any facility associated.

**Comment by cmeyerhzi** [comment]
> Hello @cmeyerhzi, the Facility can be manually filled from the UI only if you manually select first the Facility Category and Facility Type. It makes sense to also prefill those two dropdowns with the correspondent values for the default Facility. For our case, the default/prefilled Facility Category is Medical and Facility Type is Hospital. This is the combination of the values when you have a user role with the Checkbox : "has optional health facility".

why the facility itself is not prefilled?

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.77.0-SNAPSHOT (5d603ac)

The main scenario -> Having a User Role with checkbox selected "Has optional health facility" 

1. User Role is assigned to a New User and has choose a Facility in the creation form
- in this scenario when creating a new Case and selecting the Place of stay as Facility then the fields "Facility Description" has Medical as option selected, "Facility type" has Hospital and "Facility" has the one selected when user was created

2. User Role is assigned to a New User and didn't chose a Facility in the creation form
- in this scenario when creating a new Case and selecting the Place of stay as Facility, then the fields: "Facility Description"  "Facility type" and "Facility" are empty
