### ISSUE TITLE
Checkbox "Port health user" for user roles is not working

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10518]
### Bug Description

The checkbox 'Port health user' results in the user being shown a form only for the case origin 'place of entry' instead of the form with the options 'In country' and 'Place of entry' for the mandatory field 'place of entry' when creating a new case.
### Steps to Reproduce

1.
2.

### Screenshots

![image](https://user-images.githubusercontent.com/96547924/193748424-fbb88c98-46cd-4e60-8e92-82d3f15c0314.png)

### System Details

* Device:
* SORMAS version: 1.75.2
* Android version/Browser:
* Server URL: 1402
* User Role: admin

**Comment by MateStrysewske** [comment]
@cmeyerhzi This is expected behaviour. Port health users aren't supposed to create cases outside points of entry.
