### ISSUE TITLE
Required fields when creating burials ignore their value

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1052]
The fields immediately have an error state when the burial creation form is opened and keep their error state even after a value has been entered. After trying to save and then changing values once, it works.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Looks like live validation is disabled after the value is already bound and thus does not affect the fields as it should. A good way to fix this is probably to reset the error state whenever live validation is disabled.

ControlPropertyEditField:422
```
    public void setLiveValidationDisabled(boolean liveValidationDisabled) {
        if (this.liveValidationDisabled != liveValidationDisabled) {
            this.liveValidationDisabled = liveValidationDisabled;
            if (liveValidationDisabled) {
                disableErrorState();
            }
        }
    }
```

In addition I stumbled over a nullpointer:
CaseEditFragent:109
```
        // Button panel
        DiseaseClassificationCriteria classificationCriteria = DatabaseHelper.getDiseaseClassificationCriteriaDao().getByDisease(record.getDisease());
        if (classificationCriteria == null || !classificationCriteria.hasAnyCriteria()) {
            contentBinding.showClassificationRules.setVisibility(GONE);
        }
```
