### ISSUE TITLE
Error message is displayed on the 'Dashboard' in the 'Campaigns' tab

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10527]
### Bug Description

When accessing the 'Campaigns' Dashboard, an error message is displayed.

### Steps to Reproduce

1. In the web app, navigate to the 'Dashboard' directory and click on 'Campaigns'.

### Actual Behavior

An error message is displayed:
![image](https://user-images.githubusercontent.com/96909231/193783133-a2e4fc09-869a-4fa7-8a0c-5d12324d248b.png)

### Expected Behavior

No error message should be displayed.

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(5111f71)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Logs from the local machine server:
[Campaigns error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9704471/Campaigns.error.txt)

**Comment by BarnaBartha** [comment]
@adinaflorea9 Please also provide what you have in your campaign tables
campaignformdata
campaigndiagramdefinition
campaignformmeta
campaigns

Looking at the error log you provided it seems to be something wrong configured in the jsons of the campaign tables diagram definition.

**Comment by adinaflorea9** [comment]
[Configurations necessary for campaign forms.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9721850/Configurations.necessary.for.campaign.forms.txt)

@BarnaBartha in the file above are the steps that I took to configure campaigns on my local machine and I have sent to your email a file that is the backup of my current DB so that you can see exactly what is in all of the tables.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(18b7aeb)
