### ISSUE TITLE
When synchronizing contacts edited in the mobile app, a visit is counted in the 'Pulling modified data' step 4 of the synchronization status indication

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10520]
### Bug Description

When editing contacts in the mobile app and then triggering a synchronization, a visit is counted in the 'Pulling modified data' step 4 of the synchronization, even though no visit was edited and the contact does not have any visits created.

### Steps to Reproduce

1. In the mobile app, edit an existing contact (set the 'Contact classification' to 'Confirmed contact'/'Unconfirmed contact');
2. Save the contact and trigger a synchronization with the server.

### Actual Behavior

A visit is counted in step 4 of the synchronization even though no visit was edited before the synchronization. 

### Expected Behavior

Only the entities that were edited since the last synchronization should be counted in the synchronization status indication.

### Screenshots

GIF of the steps and the behavior:
![Visits](https://user-images.githubusercontent.com/96909231/193763971-3905b5a7-c516-43ac-87e0-46cea74d480d.gif)

### System Details

* Device: Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.76.0-SNAPSHOT(5111f71)
* Android version/Browser:  Android 11 (android-app)
* Server URL: local machine
* User Role: Surveillance Officer

**Comment by andrei7bal** [comment]
Hello! I will put this in waiting since more clarifications are required. Thank you

**Comment by andrei7bal** [comment]
Hello!
I've done the check for all entities, will only be displayed and in sync if the related feature configurations of the entities are also enabled (besieds user rights to view this specific entity). Check for each entity is done as follows:
`CaseDataDto->CASE_SURVEILANCE
ImmunizationDto->IMMUNIZATION_MANAGEMENT
EventDto->EVENT_SURVEILLANCE
EventParticipantDto->EVENT_SURVEILLANCE
SampleDto->SAMPLES_LAB
PathogenTestDto->SAMPLES_LAB
AdditionalTestDto->ADDITIONAL_TESTS
ContactDto->CONTACT_TRACING
VisitDto->CASE_FOLLOWUP OR CONTACT_TRACING
TaskDto->TASK_MANAGEMENT
WeeklyReportDto->WEEKLY_REPORTING
AggregateReportDto->AGGREGATE_REPORTING 
PrescriptionDto->CASE_SURVEILANCE
TreatmentDto->CASE_SURVEILANCE
ClinicalVisitDto->CLINICAL_MANAGEMENT`

Let me know if something is wrong with the above list.
Thanks
