### ISSUE TITLE
Layout lab message directory

### ISSUE THREAD

**Issue by SORMAS-SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10537]
### Bug Description

Lines above buttons like _eye_, _Process_, _download-button_ do not have the same height as the other ones (like _UUID, TYPE, STATUS and so on)
### Steps to Reproduce

1. Go to the lab message directory
2. Observe the lines

### Expected Behavior

Lines have the same height everywhere
### Screenshots

![image](https://user-images.githubusercontent.com/100844689/193871844-2a723ffb-1b99-447f-89c0-af1999a23059.png)

### System Details

* Device:
* SORMAS version: 1.75.3
* Android version/Browser: edge
* Server URL: 1402
* User Role:

### Additional Information

similar to #10535 
a minor bug in my opinion

**Comment by ChristopherRiedel** [comment]
The header of the columns is 2 pixels smaller than the other columns.

**Comment by ChristopherRiedel** [comment]
#10535 seems to be related

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.79.0-SNAPSHOT (1ffadcb)
