### ISSUE TITLE
Disabled user roles are displayed in the list when 'Enabled' appears selected by default

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10538]
### Bug Description
When an admin user accesses the Users Directory -> User Roles, 'Enabled' appears to be set to default. However, the list of user roles contain both enabled and disabled user roles.
If 'Enabled' is selected manually, the disabled user roles are no longer displayed in the list.

### Steps to Reproduce

1. Log in with an Admin user;
2. Open the Users Directory and select the User Roles tab;
3. Make sure you have at least one or two disabled user roles;
4. Inspect the list of user roles and search if the disabled user roles are displayed;

### Expected Behavior
The disabled user roles should not be displayed; should be displayed only when 'Disabled' is selected;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/193994769-8586c9e2-8b71-4d16-b098-46d4b6963106.png)
![image](https://user-images.githubusercontent.com/89522688/193994796-d49e0311-17d6-4464-b37b-e1d4fcaca82b.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0 - SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local server
* User Role: admin

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.76.0-SNAPSHOT(5ebc466).
