### ISSUE TITLE
District Observer is able to edit contacts and immunizations in the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10534]
### Bug Description

The District Observer user is able to edit contacts and immunizations in the mobile app, even though they do not have rights to do so. In the web app, those same entities are not editable (the expected behavior).

### Steps to Reproduce

1. Log into the mobile app with a District Observer;
2. Navigate to the 'Contacts' directory and open an existing contact;
3. Click to edit the contact on the 'pencil' icon at the top of the page;
4. Edit one of the fields, save the contact and trigger a synchronization with the server.

### Actual Behavior

The District Observer is able to edit contacts (and immunizations) successfully.

### Expected Behavior

The contacts and immunizations should be read only for the District Observer in the mobile app (similar to how the other entities are for them, and to how contacts and immunizations are read only for them in the web app).

### Screenshots

GIF of the steps to reproduce and the behavior:
![District Observer edit Contact sync](https://user-images.githubusercontent.com/96909231/193833640-8bf436e8-0fed-45c5-b343-e8ac4d84a4a5.gif)

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.76.0-SNAPSHOT(643e1c7)
* Android version/Browser: Chrome; Android 11 (android-app)
* Server URL: local machine
* User Role: District Observer

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the latest version of Sormas 1.76.0-SNAPSHOT (18b7aeb).
