### ISSUE TITLE
Changing the outcome of the newest case for a person leads to quite unpredictable updates for the PresentCondition of the person

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#10531]
### Problem Description
When setting the Outcome of Case to DECEASED and afterwards the Outcome is changed to UNKNOWN, the PresentCondition on the Person page is not updated (will still be displayed as dead). 
We can easily go into a very unintuitive process/situation with the current implementation.
 
Scenario: 
For a Person, the case gets the outcome of case as deceased and afterwards a new case is created or the "deceased" one is updated to Unknown, in this situation, the PresentCondition remains set to Dead, although the outcome of the case is Unknown. 

### Proposed Change
The outcome of the newest case:
No outcome yet -> no change of PresentCondition of person. 
Recovered -> PresentCondition is Alive 
Deceased -> PresentCondition is set to Dead
Unknown -> PresentCondion should be Unknown.

### Acceptance Criteria
Correct correlation between Outcome of Case and Present condition on the Person page

### Additional Information

Relates to #10496

**Comment by MateStrysewske** [comment]
**Important:** This whole automation is only supposed to be done if the cause of death for the person is set to epidemic disease and the disease is set to the disease of the case in question. Any cases with other diseases are to be ignored for the present condition, and if there is any other or no cause of death set, no case outcome change should influence the present condition whatsoever (unless a case outcome is set to deceased, in which case the present condition should be updated to dead).

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.75.4-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/89dfbb82951ac14f559980b718b4bbb9704d7c43)
