### ISSUE TITLE
S2S_layout share directory

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10535]
### Bug Description

Line does not have the same height everywhere and layout changes greatly depending on filter setting. If it is possible, it would be great if the layout remains the same. Concerns incoming and outgoing.
### Steps to Reproduce

1. Go to the share directory
2. Observe the lines
3. Try different _status_ filter

### Expected Behavior

Lines have the same height everywhere
The layout remains the same no matter which filter is set
### Screenshots

![revision share directory](https://user-images.githubusercontent.com/100844689/192738045-3807fe30-b06e-4ae1-927d-2b5813b13b63.gif)

### System Details

* Device:
* SORMAS version: 1.75.2
* Android version/Browser: edge
* Server URL: test-de2
* User Role:

### Additional Information

Finding from testing #9755

**Comment by abrudanancuta** [comment]
Validated on test.de2 with the version: 1.79.0-SNAPSHOT (edb980c)
The columns which are common after applying a filter keeps the same layout - width
