### ISSUE TITLE
National User can no longer edit multiple sections from cases

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#10547]
### Bug Description

A National User is no longer able to edit multiple sections from a case's page
See description for point I in https://github.com/hzi-braunschweig/SORMAS-Project/issues/10474
### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.75.4-SNAPSHOT (89dfbb8)
