### ISSUE TITLE
S2S_ reduction of possibility to edit person data [1]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10543]
### Feature Description

Important to understand: Since a Person is shared by multiple entities the concept of "ownership" is a bit more complex for Persons. It means that there is no exclusive ownership for Persons, since any system that has ownership of an entity related to the person also needs to be able to edit the person. 

Whether a person is editable in SORMAS currently fully depends on whether the related entity is editable (e.g. whether the case is editable is determined via CaseService.getEditPermissionType). This means the same person may be editable when opened via a Case, but not editable when opened via a Contact that was handed over to another system.
When opening from the Person Directory, the logic is again working differently and looking for any share information, which also leads to inconsistent behavior.

### Proposed Change

- [x] In the future it should ONLY be possible to edit the person under the menu point 'person' if there is at least one entity (case, contact, event participant, travel entry) with ownership in the system. Otherwise the page is greyed out. 
- [x] There is no difference between the person under the **menu point** _person_ and the **tab** _case person /contact person/event participant/travel entry_ according to greying out. If one of these is greyed out, it has to be greyed out everywhere.  If one of these is editable, it has to be editable everywhere. 

I. Example: 

| system | step |
| :--- | :--- |
| Source system: | Only one case/contact/event participant is attached to a person and these entity is 'with ownership' in the source system. This entity will be shared with hand over the ownership to a target system. |
| Target system: | Accepts |
| Source system: | Person is not editable anymore. Not at the menu point 'person' nor in the **tab** _case person /contact person/event participant/travel entry. |

II. Example:

| system | step |
| :--- | :--- |
| Source system: | Two cases/contacts/event participants are attached to a person and these entities ('X' and 'Y') are 'with ownership' in the source system. One of those entities ('X') will be shared with hand over the ownership to a target system. |
| Target system: | Accepts |
| Source system: | Person is still editable in the tab case person/contact person/event participant of the shared entity 'X' and in the not shared entity 'Y' and is also editable at the menu point 'person'. |

III. Example: 

| system | step |
| :--- | :--- |
| Target system: | Received and accepted a case/contact/event participant 'X' to view. Tab case person/contact person/event participant is greyed out. At the menu point 'person' everything is greyed out, too. |
| Target System: | Adds a new case/contact/event participant/travel entry 'Y' 
| Target System: | person in OLD _case person/contact person/event participant_ 'X' is editable and not greyed out anymore. Person is editable at the menu point 'person' and in the new entity 'Y' |

### Implementation Details
* Centralize the logic that determines whether the Person is not shared at all or at least one owned entity exists that also gives the system ownership of the person. This will probabaly replace PersonFacade.isSharedWithoutOwnership
* We should probably also centralize the logic that determines the general edit-ability for the current user. Being able to edit the person in the context of at least one entity means that the User should be able to edit the person from within other entities as-well. Should behave similar to Core*Service.getEditPermissionType
* This central method needs to be used in all core entity views that allow editing the Person (see usages of PersonController.getEditComponent)

### Additional Information

Whether the user is able to see the person at all is not relevant here. We only care about edit/read.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by MartinWahnschaffe** [comment]
@SahaLinaPrueger I have added some more details from implementation perspective.

**Comment by dragosb-vg** [comment]
Validated on **sormas-x->release-de** on Version: 1.77.1.
- Person details in Person menu can be edited ONLY if there is an entity with ownership in the system.
- Person editing behavior is consistent in the Person Menu and the entity Person tab (Case/Contact/Event Participant).
