### ISSUE TITLE
S2S_Changing person sync [1]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10544]
### Problem Description

Person sync is currently active for any shared person and may also override person data in systems that have ownership of the Person. This may lead to loss of data. 

Important to understand: Since a Person is shared by multiple entities the concept of "ownership" is a bit more complex for Persons. It means that there is no exclusive ownership for Persons, since any system that has ownership of an entity related to the person also needs to be able to edit the person.

### Proposed Change

When a person is synced the receiving system needs to check whether it has ownership of the Person itself. Central logic for this should be provided by #10543.

When the receiving system has ownership of the person it should reject the incoming changes.

We also have to take care of samples and immunization. Both should be still synced.

### Implementation Details

* Respond accordingly. Decided how to deal with the response in the sending system.

### Additional Information

Note that it is still valid that the person may be changed related to data from a synchronized case or similar. E.g. when the outcome of the case is set to deceased, this will also update the person.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by dragosb-vg** [comment]
Validated on **test-de1<-> test-de3** on Version: 1.76.0-SNAPSHOT ([a37db54](https://github.com/hzi-braunschweig/SORMAS-Project/commits/a37db54c3c229b2f7782e48a55a8ab5d9f4cae11))
