### ISSUE TITLE
S2S_case editable on two systems, behavior of jurisdiction level wrong if share is without ownership

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10553]
### Steps to Reproduce

0. create a case in source system release-x with jurisdiction level Niedersachsen, LK Leer 21:24
1. share case from source system release-x to target system release-de FOR VIEW 21:24
2. Accept case in target system 21:16
3. Observe behavior of jurisdiction level of source system: Although case was just send to view the jurisdiction level changes to BaWü, LK Bodenseekreis
4. Observe behavior of jurisdiction level of target system: still Niedersachsen, LK Leer (Sync not correct)
5. In source system release-x: uncheck the checkbox: 'Place of stay of this case differs from its responsible jurisdiction' DO NOT SAVE THE CASE just execute directly step 6
6. share case WITH ownership to the same target system as before (release-de) 21:26 (window 'unsaved changes' opens: click 'save changes') 21:27
7. BEFORE accepting in target system check in target system if case is editable -> case is editable
8. reject case in target system -> case still editable in both systems

### Expected Behavior

step 3: jurisdiction level should never change BEFORE case is accepted. Furthermore jurisdiction level does not change if case is shared for view.
step 4: Sync fails
step 7: case should not be editable BEFORE share request is accepted
step 8: case should not be editable if share request is rejected
### Screenshots

![image](https://user-images.githubusercontent.com/100844689/194145670-67178904-8ec6-4071-9bb7-8d5ca20253f1.png)

### System Details

* Device:
* SORMAS version: 1.75.3
* Android version/Browser: edge
* Server URL:
* User Role: admin

### Additional Information

Share contacts without hand over the ownership leads into wrong jurisdiction levels, too.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by adinaflorea9** [comment]
The ticket was tested in a peer to peer call with @JonasCir on his S2S local machine.

As proposed @abrudanancuta I will un-assign myself from the ticket as she would prefer @dragosb-vg to continue testing.

**Comment by dragosb-vg** [comment]
Validated using S2S sharing between **de1-de3** test environments on Version: 1.76.0-SNAPSHOT ([f34a7c8](https://github.com/hzi-braunschweig/SORMAS-Project/commits/f34a7c851f8fa799497e6037ba1ad6b7e6b33243))
Case jurisdiction can no longer be edited on target system before 'sharing with ownership' request is accepted.
- Checked read-only status of jurisdiction for S2S shared cases without handover on receiver end.
- Checked updates on case jurisdiction on different moments during the case sharing / accepting/rejecting process.

(see below read-only jurisdiction fields on target system)
![image](https://user-images.githubusercontent.com/111864167/196212736-47d421a5-d772-4296-afb5-5370aa5fa113.png)
![image](https://user-images.githubusercontent.com/111864167/196212755-920ce5bf-de3e-489c-88da-7973db0951bd.png)

**Comment by SahaLinaPrueger** [comment]
I tested this on 1.76.0 SNAPSHOT (f34a7c8) from test-de1 to test-de2 and there everything was correct. 
Source system before and while sharing and after acceptance of shared request
![image](https://user-images.githubusercontent.com/100844689/196228199-967e31f9-178b-451f-81ea-8d4d5e47de2e.png)

Target system after acceptance:
![image](https://user-images.githubusercontent.com/100844689/196228340-48267210-854e-4fd9-b6ad-fb59470a5e48.png)

@dragosb-vg your second picture shows a shared case in target system where the checkbox _place of stay of this case differs from its responsible region_ was already checked BEFORE sharing _without_ hand over the ownership, right?

**Comment by dragosb-vg** [comment]
Yes, exactly. The change was made on source system, shared(without ownership) and accepted on target machine. 
Its point was to show the sync mechanism works correctly even for different place of stay, and that jurisdiction is read-only before handover is accepted.
