### ISSUE TITLE
Investigate failures reported on release candidates

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#10558]
The client reported a couple of failing tests over release candidates which can be caused by application defects or tests defects

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-release-commit/20/allure/

Sormas version:
**1.75.3**

Investigate all tests marked by customer and provide status.

**Comment by MartinWahnschaffe** [comment]
One thing that may be related to the server lost connection issue and needs to be clarified are the following log entries related to the docker container. There are multiple warnings and this reoccurring error:

**dockerd: time="2022-10-05T01:09:53.913249568+02:00" level=error msg="stream copy error: reading from a closed fifo"**

Log:

<details>
> Oct  5 01:10:55 release-international dockerd: time="2022-10-05T01:10:55+02:00" level=info msg="Firewalld: docker zone already exists, returning"
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.446843465+02:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 pid=106605 runtime=io.containerd.runc.v2
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.446629313+02:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.446612044+02:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.446389901+02:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international NetworkManager[955]: <info>  [1664925055.3496] manager: (vethac88473): new Veth device (/org/freedesktop/NetworkManager/Devices/2469)
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international NetworkManager[955]: <info>  [1664925055.3490] manager: (veth3419fe1): new Veth device (/org/freedesktop/NetworkManager/Devices/2468)
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(vethac88473) entered forwarding state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(vethac88473) entered blocking state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: IPv6: ADDRCONF(NETDEV_UP): vethac88473: link is not ready
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: device vethac88473 entered promiscuous mode
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(vethac88473) entered disabled state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(vethac88473) entered blocking state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international NetworkManager[955]: <info>  [1664925055.3139] device (veth0e91528): released from master device br-1a079e69c940
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered disabled state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: device veth0e91528 left promiscuous mode
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered disabled state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international NetworkManager[955]: <info>  [1664925055.3018] manager: (vethc9e6232): new Veth device (/org/freedesktop/NetworkManager/Devices/2467)
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered disabled state
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.222846417+02:00" level=warning msg="cleanup warnings time=\"2022-10-05T01:10:55+02:00\" level=info msg=\"starting signal loop\" namespace=moby pid=106525 runtime=io.containerd.runc.v2\n"
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.210117237+02:00" level=info msg="cleaning up dead shim"
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.210104249+02:00" level=warning msg="cleaning up after shim disconnected" id=4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 namespace=moby
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international containerd: time="2022-10-05T01:10:55.210045594+02:00" level=info msg="shim disconnected" id=4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848
> 	2022-10-05 01:10:55	
> Oct  5 01:10:55 release-international dockerd: time="2022-10-05T01:10:55.207437591+02:00" level=info msg="ignoring event" container=4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
> 	2022-10-05 01:10:54	
> Oct  5 01:10:54 release-international dockerd: time="2022-10-05T01:10:54.024157073+02:00" level=warning msg="Health check for container 4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 error: OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
> 	2022-10-05 01:10:54	
**> Oct  5 01:10:54 release-international dockerd: time="2022-10-05T01:10:54.022975851+02:00" level=error msg="stream copy error: reading from a closed fifo"
> 	2022-10-05 01:10:54	
> Oct  5 01:10:54 release-international dockerd: time="2022-10-05T01:10:54.020506193+02:00" level=error msg="stream copy error: reading from a closed fifo"**
> 	2022-10-05 01:10:24	
> Oct  5 01:10:23 release-international dockerd: time="2022-10-05T01:10:23.971284316+02:00" level=warning msg="Health check for container 4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 error: OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
> 	2022-10-05 01:10:24	
> Oct  5 01:10:23 release-international dockerd: time="2022-10-05T01:10:23.969965837+02:00" level=error msg="stream copy error: reading from a closed fifo"
> 	2022-10-05 01:10:24	
> Oct  5 01:10:23 release-international dockerd: time="2022-10-05T01:10:23.966989254+02:00" level=error msg="stream copy error: reading from a closed fifo"
> 	2022-10-05 01:10:03	
> Oct  5 01:10:03 release-international systemd: Removed slice User Slice of root.
> 	2022-10-05 01:10:01	
> Oct  5 01:10:01 release-international systemd: Started Session 52969 of user root.
> 	2022-10-05 01:10:01	
> Oct  5 01:10:01 release-international systemd: Created slice User Slice of root.
> 	2022-10-05 01:10:00	
> 	2022-10-05 01:10:00	
> ]]
> 	2022-10-05 01:10:00	
>   D011000.176|     > calculateCaseCompletion finished. 1 cases, 0 s (de.symeda.sormas.backend.common.CronService.java:102)
> 	2022-10-05 01:10:00	
> [2022-10-05T01:10:00.176+0200] [Payara 5.2021.10] [INFO] [] [] [tid: _ThreadID=241 _ThreadName=__ejb-thread-pool9] [timeMillis: 1664925000176] [levelValue: 800] [[
> 	2022-10-05 01:10:00	
> 	2022-10-05 01:10:00	
> ]]
> 	2022-10-05 01:10:00	
>   I011000.002|     > Deleted 3 export files (de.symeda.sormas.backend.common.CronService.java:147)
> 	2022-10-05 01:10:00	
> [2022-10-05T01:10:00.002+0200] [Payara 5.2021.10] [INFO] [] [] [tid: _ThreadID=225 _ThreadName=__ejb-thread-pool5] [timeMillis: 1664925000002] [levelValue: 800] [[
> 	2022-10-05 01:09:53	
> Oct  5 01:09:53 release-international dockerd: time="2022-10-05T01:09:53.914479306+02:00" level=warning msg="Health check for container 4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 error: OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
**> 	2022-10-05 01:09:53	
> Oct  5 01:09:53 release-international dockerd: time="2022-10-05T01:09:53.913249568+02:00" level=error msg="stream copy error: reading from a closed fifo"
> 	2022-10-05 01:09:53	
> Oct  5 01:09:53 release-international dockerd: time="2022-10-05T01:09:53.913235016+02:00" level=error msg="stream copy error: reading from a closed fifo"**
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international NetworkManager[955]: <info>  [1664924963.8069] device (veth0e91528): carrier: link connected
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth0e91528: link becomes ready
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international dockerd: time="2022-10-05T01:09:23+02:00" level=info msg="Firewalld: docker zone already exists, returning"
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.627628124+02:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 pid=105326 runtime=io.containerd.runc.v2
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.627482779+02:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.627473088+02:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.627392901+02:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international NetworkManager[955]: <info>  [1664924963.5332] manager: (veth0e91528): new Veth device (/org/freedesktop/NetworkManager/Devices/2466)
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international NetworkManager[955]: <info>  [1664924963.5326] manager: (vethc9e6232): new Veth device (/org/freedesktop/NetworkManager/Devices/2465)
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered forwarding state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered blocking state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: IPv6: ADDRCONF(NETDEV_UP): veth0e91528: link is not ready
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: device veth0e91528 entered promiscuous mode
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered disabled state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(veth0e91528) entered blocking state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international NetworkManager[955]: <info>  [1664924963.4956] device (vethbe2a02e): released from master device br-1a079e69c940
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(vethbe2a02e) entered disabled state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: device vethbe2a02e left promiscuous mode
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(vethbe2a02e) entered disabled state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international NetworkManager[955]: <info>  [1664924963.4849] manager: (veth33fdd84): new Veth device (/org/freedesktop/NetworkManager/Devices/2464)
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international kernel: br-1a079e69c940: port 5(vethbe2a02e) entered disabled state
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.405960151+02:00" level=warning msg="cleanup warnings time=\"2022-10-05T01:09:23+02:00\" level=info msg=\"starting signal loop\" namespace=moby pid=105242 runtime=io.containerd.runc.v2\n"
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.397077760+02:00" level=info msg="cleaning up dead shim"
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.397066256+02:00" level=warning msg="cleaning up after shim disconnected" id=4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 namespace=moby
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international containerd: time="2022-10-05T01:09:23.397022401+02:00" level=info msg="shim disconnected" id=4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848
> 	2022-10-05 01:09:23	
> Oct  5 01:09:23 release-international dockerd: time="2022-10-05T01:09:23.396407774+02:00" level=info msg="ignoring event" container=4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
> 	2022-10-05 01:09:22	
> Oct  5 01:09:22 release-international dockerd: time="2022-10-05T01:09:22.229169919+02:00" level=warning msg="Health check for container 4c83618f4db2ffb530d2c0423880d3c73a0c405d19daeb8df65cbfe769c3b848 error: OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
</details>

**Comment by rdutu-vg** [comment]
Today's findings:
1. Couldn't see any reported performance problems on daily regression environments.
2. Checked VMs resources, and testing environments are hosted on VMs with same resources as daily checked environments, so I would exclude any potentially issue related to resources.

![image](https://user-images.githubusercontent.com/83643843/194572633-b34dd783-a2b0-4ef7-a952-2ec93f2e0aa2.png)
![image](https://user-images.githubusercontent.com/83643843/194572671-79d5cf0c-e2a7-441d-8b9e-7212de64c305.png)

**Comment by rdutu-vg** [comment]
All failing tests due to user's rights are stable once fix was merged.
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests/960/allure/

@MartinWahnschaffe  managed to find some logs from 502 reproduced issue and we're checking with Netzlink.

**Comment by rdutu-vg** [comment]
I triggered another run with 9 parallel threads after Frank H confirmed that servers are stable.
 A lot of tests are failing due to something that is not related to our tests or application:

![image](https://user-images.githubusercontent.com/83643843/195264034-c2fcd22a-4db8-4aee-aa7a-62017d8fdf35.png)

`
After is failed: invalid session id
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'hzi-dev-build.sormas.netzlink.com', ip: '141.95.21.60', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.18.1.el7.x86_64', java.version: '11.0.9.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0ce9041b513c78c7127bbedd5d4b5400, screenshot {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.212, chrome: {chromedriverVersion: 90.0.4430.212 (e3cd97fc771b..., userDataDir: /tmp/.org.chromium.Chromium...}, goog:chromeOptions: {debuggerAddress: localhost:37453}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:37453/devtoo..., se:cdpVersion: 90.0.4430.212, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0ce9041b513c78c7127bbedd5d4b5400
`

**Comment by rdutu-vg** [comment]
Checked with Frank, our Jenkins is running over a VM without docker, so we cannot adjust the SHM memory in order to see improvements for parallel execution.
We can try to change the browser to see if Firefox might be solution for current parallel execution issue.

**Comment by rdutu-vg** [comment]
![image](https://user-images.githubusercontent.com/83643843/196191220-31ed7ff0-088a-4d63-b75a-b80dae9c1eaf.png)

502 errors stopped to reproduce since 30 September.
Looks like the fix from infrastructure had a great impact over environments stability.

**Comment by rdutu-vg** [comment]
Triggered a new run over release candidates with 9 parallel threads:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-release/224/
![image](https://user-images.githubusercontent.com/83643843/197129975-9af3bb5b-b092-4f48-bdfb-7ea7fee350bf.png)

The performance issues are no longer reproducible. The problem wasn't related to Sormas application.

cc: @markusmann-vg  @abrudanancuta  @MateStrysewske  @MartinWahnschaffe

**Comment by MartinWahnschaffe** [comment]
So running the whole thing is now also a lot faster. That's great!

**Comment by rdutu-vg** [comment]
Indeed, from almost 11 hours to almost 3, and the multiple API requests have no impact over Sormas application, the connection lost error and 502 were not related to Sormas.
