### ISSUE TITLE
Events of a contact: Wrong text if no event is linked

### ISSUE THREAD

**Issue by kathsievers** [hzi-braunschweig/SORMAS-Project#10554]
### Bug Description

There are spelling mistakes in the UI of the german SORMAS version. See screenshots below.

### Steps to Reproduce

1. create new contact in german UI

### Expected Behavior

When creating a new contact without any events it should display 'Kein Ereignis mit dem Kontakt verknüpft'. 

### Screenshots

'für diesen Kontakt'
![image](https://user-images.githubusercontent.com/97029882/194171212-a3982a16-d493-44a3-af67-61184a11fd0e.png)

### System Details

* Device:
* SORMAS version: 1.75.3, ..., 1.52.0
* Android version/Browser:
* Server URL: test1402
* User Role: admin

### Additional Information

@cmeyerhzi fyi

Caused by #3133

**Comment by JaquM-HZI** [comment]
Additional Information:
We don't know why the wrong translation is used for the contact part. For all the others, we need to separate the Description. 
So one part is a bug, the other is a change.

**Comment by StefanKock** [comment]
I reduced the ticket only to screenshot 6. and split out the tasks translation problem to #10594

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.76.0-SNAPSHOT (18b7aeb).
