### ISSUE TITLE
[S2S] Filter directories when navigating from duplicate detection warning dialog [2]

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#10569]
### Feature Description

A duplicate detection is done when accepting a case or contact. 
When a duplicate is found a warning message is displayed with option to navigate to case merge, contact merge, contacts directory or person directory after accepting the share request as described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/9527#issuecomment-1265442536.

### Proposed Change

When the user choses to "accept and navigate" the grids on those pages should be filtered to show only the similar cases, contacts or persons

### Acceptance Criteria

**Accepting case**

1. There is at least one similar case: Case merge overview should show only the similar cases to the ones being accepted
2. From the similar cases at least one similar case that was converted from a contact: Case merge overview should show only the similar cases to the ones being accepted
3. There is at least one similar contact not converted to case: show only those contacts

**Accepting contact**

1. There is at least one similar contact: Contact merge overview should show only the similar contacts to the ones being accepted
2. From similar contacts at least one is converted to case: Contact merge overview should show only the similar contacts to the ones being accepted
3. There is at least one similar case: If there are multiple contacts to be accepted and with multiple similar cases, navigate to contacts directory and show only the contacts with similar cases, otherwise navigate to the contact details so the user can convert it from there

**Accepting case or contact**

There are only similar persons (no similar case and/or contact): Persons directory should show only the similar persons

**Comment by leventegal-she** [comment]
Reopening because the merge cases page loads the grid when opening from the cases page but it shouldn't

**Comment by abrudanancuta** [comment]
Validated on test.de2, de1 with the version: 1.80.0-SNAPSHOT (093fec2)

**Comment by abrudanancuta** [comment]
Verified on test.de2, test.de1 with the version: 1.80.0-SNAPSHOT (d6ffb94)
