### ISSUE TITLE
User without CASE_EDIT rights can click on the 'New Report' button on a case page

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10564]
### Bug Description

A user that does not have rights to edit cases can click on the 'New Report' button on a case page and attempt to create a new report. The creation of the report is not successful (the server logs revealed that the creation is not successful specifically because the user does not have CASE_EDIT rights).

### Steps to Reproduce

1. Create a new user role that has the user rights displayed in the screenshots from 'Additional information';
2. Create a new user with the user role from step 1;
3. Log in the app with the user created at step 2;
4. Open an existing case and click on 'New Report' in the 'Reports' card;
5. Fill in the mandatory information and click 'Save'.

### Actual Behavior

The user is able to click on the 'New Report' button and fill in information. An error message is displayed and the report is not saved.

### Expected Behavior

The user should not be able to click on the 'New Report' button.

### Screenshots

GIF of the behavior:
![Report create](https://user-images.githubusercontent.com/96909231/194322218-fc770ede-93e7-4058-a840-ba049b1f5e92.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(7c72874)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: configured as described in the steps to reproduce and in the screenshots from 'Additional information'

### Additional Information

Logs from the local machine:
[Edit case error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9725102/Edit.case.error.txt)

<details>
<summary>Screenshots of the user rights selected for the user role from step 1</summary>
<br>

![image](https://user-images.githubusercontent.com/96909231/194320087-2d350bc1-6b17-4597-af23-7f479e208904.png)

![image](https://user-images.githubusercontent.com/96909231/194320110-bffa213a-afdd-445d-9257-52b2de4a5b19.png)

![image](https://user-images.githubusercontent.com/96909231/194320127-08110974-c426-4e79-95a1-cdcf045fa56f.png)

</details>

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (f1a24c0).
