### ISSUE TITLE
[Pseudonymization] Mark UI inputs as confidential depending on what rights the user has

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#10560]
### Problem Description

There are separate user rights for seeing personal and sensitive data, on the backend DTO-s are pseudonymized based on those right, so no sensitive data will be pseudonymized if the user has right for seeing sensitive data but no right for personal data.
On the UI (web and mobile) all personal and  sensitive fields are marked as confidential even when the user should se sensitive data but not the personal ones
### Proposed Change

User should see and should be able to edit sensitive data if it has right to see sensitive data but no right to see personal data.
### Implementation Details

In the UI code combine the `Pseudonymizable::isPseudonymized` method and checking whit right the current user has, when creating `UiFieldAccessCheckers` instances 
### Additional Information

Please do it for web and mobile client too

### QA Information
Please check all forms in the web app with a user that has only sensitive/personal access to data; if they have only access to sensitive data, all fields that are only annotated with `@PersonalData` (e.g. person first and last name) should be pseudonymized; if they have only access to personal data, all fields that are only annotated with `@SensitiveData` (e.g. the additional comments of cases) should be pseudonymized. Up until now, there was no proper differentiation between the two, so a user with no access to personal, but access to sensitive data would still see the sensitive data fields being pseudonymized and read only in the UI. Also, there's a differentiation between data IN the user's jurisdiction and OUTSIDE the user's jurisdiction depending on the user role configuration.

**Comment by ChristopherRiedel** [comment]
Please also add a corresponding IN_JURISDICTION constant to PseudonymizableDto.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS  from the development branch - 1.77.0-SNAPSHOT(1d5b2bd). Inconsistencies observed were logged in separate change requests: #10876, #10878, #10913.
