### ISSUE TITLE
POE Supervisor is not able to create cases

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10561]
### Bug Description

A POE Supervisor is no longer able to create cases (through the regular 'Create new case' form, or create a case for a travel entry).

### Steps to Reproduce

1. Log into the web app with a POE Supervisor;
2. Open the 'Create new case' form and fill in the mandatory information;
3. Click 'Save'.

### Actual Behavior

An error message is displayed:
![image](https://user-images.githubusercontent.com/96909231/194305419-8f7a5d0e-f24f-4007-98d8-c6fdf66f274e.png)

The case gets saved but when the user opens it, the page is empty:
![image](https://user-images.githubusercontent.com/96909231/194305547-1fae30a5-2cfc-403e-a49d-61d3bfb4dca6.png)

### Expected Behavior

No error message should be displayed, the case is saved successfully, and when the user opens the case page the case information is visible.

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0-SNAPSHOT(7c72874); and 1.75.3
* Android version/Browser: Chrome
* Server URL: local machine; release-international.sormas.netzlink.com
* User Role: POE Supervisor

### Additional Information

Logs from the local machine:
[Error case create.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9724550/Error.case.create.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.76.0-SNAPSHOT (a4749d01).
