### ISSUE TITLE
De-Archived event participants are not listed in the 'Active event participants' list

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10609]
### Problem Description

When the feature configuration EDIT_ARCHIVED_ENTITIES is set to true, the archived entities are editable.

If an event that has event participants is archived, then one or more if the event participants are de-archived individually, those event participants are still filtered as archived event participants and are not displayed in the 'Active event participants' list.

### Proposed Change

Active event participants should always be displayed on the 'Active event participants' list as well as on the 'All event participants' list.

**Comment by JaquM-HZI** [comment]
@adinaflorea9 why isn't this a bug? If the behavior is just not correct?

**Comment by adinaflorea9** [comment]
@JaquM-HZI I logged this as a change request as it is similar to #9852  which was initially logged as a bug but then it was decided that it is rather a change request.

I can  update this current ticket to be a bug if this is more appropriate.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following - after de-archiving an event participant (while the event is still archived) the respective event participant is still listed in the 'Archived event participants' list - it should be listed only in the 'Active event participants' and 'All event participants' lists.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(c2e4845).
