### ISSUE TITLE
Deletion in bulk mode: German translated window is cut

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10612]
### Bug Description

Deletion in bulk mode: German translated window is cut
### Steps to Reproduce

1. select the german language as setting
2. open the case/ contact directory
3. enter bulk edit mode
4. try to delete in bulk edit mode
5. observe message

### Expected Behavior

the message can be read in full
### Screenshots

![image](https://user-images.githubusercontent.com/100844689/195163526-b1d319b0-1b00-460c-bf92-5ac647764d43.png)

### System Details

* Device:
* SORMAS version: 1.75,4
* Android version/Browser: edge
* Server URL: sormas-x
* User Role: admin

**Comment by MateStrysewske** [comment]
Solution: Give the label a width of 100 %.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (5eb3cdf).
