### ISSUE TITLE
Usage of `IterableHelper.executeBatched` not using batches

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#10624]
### Bug Description

While discussing #10528 I found several usages of `IterableHelper.executeBatched` where the whole collection is used in the batch. With large data these founctions run into `PSQLException: PreparedStatement can have at most 65,535 parameters.`.

I checked all current usages and found these flaws:
| Code  | Causing ticket |
|------ | ---------|
| `CaseFacadeEjb.countCasesWithMissingContactInformation` | #2744 |
| `CaseService.getByPersonUuids` | #4625 |
| `CoreEntityDeletionService.deleteOrphanEntities` | #8010 |
| `PersonService.getByExternalIds` | #7971 |
| `SampleService.deleteAll` (twice) | #4892 |

### Steps to Reproduce

Use large data sets within these methods.

### Expected Behavior

All usages of `IterableHelper.executeBatched` shall not use the given collection within the batch (basically ignoring the lambda parameter).

### System Details

* SORMAS version: 1.75.x and older

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-auto.sormas.netzlink.com/ using SORMAS version - 1.76.0-SNAPSHOT(f34a7c8).
