### ISSUE TITLE
"Facility name & description" field is not saved when creating/editing a new User

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#10632]
**Bug Description**
When creating or editing a user, 'Facility name & description' filed is not saved.

**Steps to Reproduce**
1. Navigate to sormas app 
2. Login as admin user
3. Create a new user by filling all marked mandatory fields
4. Search created user and open it

**Results:**
"Facility name & description" field is not saved

**Expected:**
TBD

**Screenshot:**
![issue](https://user-images.githubusercontent.com/83643843/195605202-bcd6ed6a-0ef7-47a7-8c32-c90c2fd74e67.gif)

**Extra:**
Tests were stable on 11.10.2022
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests/962/allure/#suites/bd663fa712ccafbe2d65d1dd364e02f0/75ebe52ececa9dfd/history
not executed on 12.10.2022, and discovered today during regression check
The issue was introduced by the tickets related to this field which have been fixed in other directories.

System Details
Device: Windows 10
SORMAS version :Sormas 1.76.0
Android version/Browser: Chrome
Server URL: https://test-auto.sormas.netzlink.com / https://test-de.sormas.netzlink.com
User Role: admin

**Comment by adinaflorea9** [comment]
Unsure if the behavior is related or not, but it is also reproducible in the mobile app for cases - information inputted in the field 'Facility name & description' is not saved when creating the case or editing it.

**Comment by StefanKock** [comment]
I debugged the whole roundtrip:
- `LocationDto.facilityDetails` is set and transferred into `Location` (debugged in `LocationFacadeEjb.fromDto`)
- `Location.facilityDetails` is set and transferred into `LocationDto` (debugged in `LocationFacadeEjb.toDto`),
- The value is persisted in the database (`location.facilitydetails`).

It is apperently only a problem in `LocationEditForm`, where #10514 changed something.

**Comment by StefanKock** [comment]
I reopened #10514, therefore closing this ticket as duplicate
