### ISSUE TITLE
Reset present condition cells to "NA" or "Unknown" in mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1063]
Present condition fields on the mobile app do not have the possibility to uncheck after selecting an option. For example if I mistakenly choose "dead" for "present condition" and want to reset it back to Unknown, it is not possible. 
Suggested solutions: Add unknown as an option OR deselect by clicking a second time on a selected field.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make it a spinner field
