### ISSUE TITLE
Visits with Date of Visit > 30 days older than the Case Report Date can be created

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10646]
### Bug Description
When creating a Visit, there's a validation that checks if the Date of the Visit is not more than 30 days older than the Case Report Date. But, there's a workaround for this, and basically, we can have a Case with a Visit older than 30 days than the Case Report Date that is not displayed in the UI.

### Steps to Reproduce

1. Create a Case with the Report Date set to 01 Sept;
2. Add a Visit with the Date of Visit set to 01 Sept;
       -> in the DB, the Visit has the according caze_id set;
3. Change the Case Report Date to the current date (17 Oct, which is >30 days after the Date of Visit);

### Actual Behavior
In the UI, the Visit is not displayed anymore, and in the DB, the caze_id is not assigned anymore. So now, the Visit is no longer found in the UI, and it is only linked to the Person.

### Expected Behavior
The Date of the Visit should not be more than 30 days older than the Case Report Date.
Probably there should be a validation when the user changes the Case Report Date. That way we would avoid having orphan Visits that are not linked to any core entity.
This needs to be discussed though.

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.75.4
* Android version/Browser: Chrome
* Server URL: local environment and test1401.sormas-oegd.de
* User Role: admin + national user

**Comment by MateStrysewske** [comment]
I don't believe there's really anything we need to do here; afaik we have a logic that deletes orphan visits during the night anyway (as long as permanent deletion is enabled). It might make sense to also execute that logic when permanent deletion is disabled in order to clean up the database though; let's discuss this in a refinement session.

**Comment by markusmann-vg** [comment]
won't do as it works as expected
