### ISSUE TITLE
'Facility name & description' has a 'null' displayed in the text of the error message

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10644]
### Bug Description
When the 'Facility name & description' filed is empty an the error message is triggered, the text contains a 'null'.

### Steps to Reproduce

1. Open an Event Participant;
2. Scroll down to the Home Address section;
3. Fill in the Region, District, Facility Category, Facility Type and Facility ('Other facility') fields; leave the 'Facility name & description' field empty;

### Expected Behavior
The 'null' should not be displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/196158691-d657ccac-42e7-4e76-b5c7-3d8b950df987.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.75.4
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin + national user

### Additional Information
Discovered when testing ticket #10515

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(af03687).
