### ISSUE TITLE
Contact visits and symptoms 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1064]
- In registering a new visit, all symptom icons appear red as if there is an error. They should stay blue except  when the user try to save without checking any option for the symptoms
  - Date of symptom onset is visible and can be edited when all symptom are set to NO or Unknown or not selected, First symptom and date should only appear when at least one symptom is set to yes for a contact person or a case person

**Comment by MartinWahnschaffeSymeda** [comment]
In addition °C is not properly shown. Probably an UTF problem.
