### ISSUE TITLE
Automatic return of app to "contact listing field" [0]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1065]
Automatic return of app to "contact listing field". After creating a new contact person, app moves directly to visits rather than moving back to the contact listing field for you to enter more contact persons. The same holds when creating a new visit,  app should return to list of all visits.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] when saving in contact person form it should not go to the visits list. Instead close the contact and go back to the previous activity (likely contact list of case).
