### ISSUE TITLE
Facility dropdowns are not saved when National Clinician edits an Immunization

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10675]
### Bug Description
Facility dropdowns can be edited by National Clinican
### Steps to Reproduce

After discussion
1. As National Clinician edit an Immunization
2. Try to change Facility Category + Facility Type + Facility

Before discussion the bellow steps to reproduce are no more valid
1. As National Clinician, edit an Immunization
3. Add a Facility Category + Type + Facility
4. Save the Immunization with the selected options of the facilities dropdowns
5. Reopen the Immunization and check the dropdowns for facility 

### Actual Behavior
At this point National clinician can edit the Facility fields

### Expected Behavior
Facility Category  and Facility Type should be Read-only and Facility should have the label confidential
Observation: When creating an Immunization with the National Clinician, he should be able to choose Facility Category + Type + Facility

### System Details

* Device:
* SORMAS version: 1.76.0
* Android version/Browser:
* Server URL:
* User Role: National Clinician

**Comment by abrudanancuta** [comment]
After discussion between @carina29 and @MartinWahnschaffe, the steps of reproduce and expected behaviour will be changed because we need to keep the pseudonomization for the Facilities fields for the National Clinician.

**Comment by abrudanancuta** [comment]
The part of Facility Category to be read-only it will be done in this ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/10775

The part of not being able to edit the Facility Type and Facility are done with the actual ticket.

The reason of having splitted like the above mentioned is because the same method of Facility Category to be read- only is used in multiple places in the application and that will be coved by the #10775

**Comment by carina29** [comment]
This bug was solved on hotfix-1.76.1 branch.

**Comment by abrudanancuta** [comment]
Verified on release env with the version 1.76.1
