### ISSUE TITLE
Add relationship details field to contact [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1067]
When creating a contact person for a case, if “relationship with case” is "Other", then a free text should be given to explain. "Contact description" should be changed to “contact person description” since this is a free text that describe the contact person.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou From my understanding "Contact description" does NOT refer to the contact person. It's a description of the contact itself - the opportunity to add more details on how the contact happend. 
But you are right: This is confusing and needs some clarification. We should discuss this.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou From my understanding "Contact description" does NOT refer to the contact person. It's a description of the contact itself - the opportunity to add more details on how the contact happend. 
But you are right: This is confusing and needs some clarification. We should discuss this.

One suggestion: Can you find out what "free text" information is typically needed for a contact and how the "contact description" field is currently used?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add field to enter "other" contact relationship
- [ ] rename "contact description" to " description of how contact took place"
