### ISSUE TITLE
S2S _health department cannot send request because of active registration in climedo ediary

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10680]
### Bug Description

One health department reports that an error message appears if they want to send a specific case.
The error message contains that the cause is that the person is in external follow-up.
Specialty in this health department: 
Climedo is deactivated on server side since begin of 2022. So the case cannot be deactivated on UI anymore. NLI checked and verified that Climedo is not active on the instance. 
The person was registered on climedo the year before by another case.
Specialty of the current case: Case has been determined by CISS. 

### Expected Behavior

If climedo is deactivated on server side there should be no connection anymore and case can be sent via S2S. 
### Screenshots

![image](https://user-images.githubusercontent.com/100844689/196675071-195356cc-4170-461b-ad11-53294ca32853.png)

### System Details

* Device:
* SORMAS version: 1.75.4
* Android version/Browser:
* Server URL: 
* User Role: national user/ admin

### Additional Information

- [ ] Please check if there is still a connection and if so why
- [ ] Please check if the error message is really caused by Climedo and not by CISS
- [ ] Find a way to de-connect the case from climedo or hand it over to climedo

-> Logs will be provided by NLI as soon as they can and handed over to you. Because of data protection reasons logs will not be posted in this Issue.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by FredrikSchaeferVitagroup** [comment]
@SahaLinaPrueger I have no access to that specific instance (in fact, I don't even know which instance is affected).
This means I can not check whether there still is a connection and whether data is still stored on climedo side. This is something to be done with netzlink and climedo.
"_Handing a case over to climedo_" is an option that never existed.

The problem probably is that not all persons were unregistered before the connection to climedo was disabled. Thus, some persons remained in the database with `person.symptomjournalstatus` = `ACCEPTED` or `REGISTERED`. A solution would be to set those values to `UNREGISTERED` (e.g. with a script).

**Comment by FredrikSchaeferVitagroup** [comment]
I will change the type of this ticket to `task`. Behaviour for disabling external journal interfaces was never specified. 
Disabling should already be simple, but probably just was not done correctly on that instance.

**Comment by FredrikSchaeferVitagroup** [comment]
And before you ask how to get that script:

`UPDATE person SET symptomjournalstatus = 'UNREGISTERED' WHERE symptomjournalstatus IN ('ACCEPTED','REGISTERED') RETURNING uuid;`

This command will return the uuid of the modified persons.

**Comment by SahaLinaPrueger** [comment]
@FredrikSchaeferVitagroup ok, so solution would be to run this script on every instance which has deactivated climedo to be sure, that every person in database has person.symptomjournalstatus = unregistered. Thank you.

**Comment by FredrikSchaeferVitagroup** [comment]
@SahaLinaPrueger Yes, I think that is sufficient (along with making sure that the data gets deleted on climedo side).

**Comment by FredrikSchaeferVitagroup** [comment]
Netzlink was approached yesterday. Waiting for reply.

**Comment by SahaLinaPrueger** [comment]
NLI and HZI have tested the script.
10/24/22 on test1402
1. HZI creates a test case and registers the person on climedo (14:00 - 14:04)
2. NLI Deactivates Climedo (14:04 - 14:23)
3. HZI tries to reproduce error of the health department (14:26 - 14:29)
4. NLI executes script (14:29 - 14:31)
5. HZI tests whether script has desired effect (14:31 - 14:36)
6. NLI activates Climedo again (14:38 - 14:51)
7. HZI tests whether Climedo works again (14:53- 14:59) 
7.1 HZI creates a new person and registers him on climedo -> works 
7.2 HZI tries to register a person (not person from step 1 or 7.1) on climedo again, which was registered before step 1) -> did not work (see evidence).
7.3 Hypothesis: Some already deactivated cases seems to be re-activated with re-activating climedo. On the surface the persons seem to be deactivated, but in the background they are active. So if we re-activate Climedo we have to run the script just like when we deactivate climedo to be sure.
8. NLI executes the script again, so we can test the hypothesis from step 7.3 (15:11 - 15:12)
9. HZI tests if script worked 
9.1 HZI tries to register person who already was registered on climedo (step 7.1) -> did not worked.
9.2 HZI tries to register person who already was registered on climedo (step 7.2) -> did not worked.
9.3 Hypothesis: Because the person from step 7.1 has nothing to do with activating or deactivating Climedo, the hypothesis from step 7.3 is not valid. Apparently, the script only refers to the UI. This means that the button is changed on the UI, but the person is still registered in the background. Sharing via S2S seems to work anyway because apparently S2S only queries the UI but does not 'look' at the connection in the background.
This is quite interesting because it solves the S2S problem, but in general there is something not quite complete and the script is only superficial. 

Evidence:

Step 3:
![ClimedoSkriptTestingStep3](https://user-images.githubusercontent.com/100844689/197529203-02e44740-10f9-4d3e-aa5d-bf2fc29f39e7.png)

Step 4:
![image](https://user-images.githubusercontent.com/100844689/197529717-1983a85a-6ed6-4e7a-8262-2f3cb2e76018.png)

Step 5_Part 1:
![ClimedoSkriptTestingStep5](https://user-images.githubusercontent.com/100844689/197529262-47f7a3c7-e130-437f-8328-c3d11eefd200.png)

Step 5_Part 2:
![ClimedoSkriptTestingStep5_Part2](https://user-images.githubusercontent.com/100844689/197529315-d9938e42-c3aa-4968-9163-e698ae7a599e.png)

Step 7.2:
![ClimedoSkriptTestingStep7](https://user-images.githubusercontent.com/100844689/197539959-8d782f05-7252-44c5-b2e3-75cd0d540213.png)

Step 9.1:
![image](https://user-images.githubusercontent.com/100844689/197540156-c023714f-f19a-4848-89e3-abd7274ccde8.png)

Step 9.2:
![image](https://user-images.githubusercontent.com/100844689/197540399-bd997c6c-603c-41b0-a90d-ba17b48e8a9b.png)

**Comment by SahaLinaPrueger** [comment]
@FredrikSchaeferVitagroup because of 9.3: Is there a way to really deregister the person and not just change the button on UI?

**Comment by FredrikSchaeferVitagroup** [comment]
@SahaLinaPrueger The script does not only change a button. It sets the `symptomjournalstatus` of all registered persons to `UNREGISTERED` in the database. This makes SORMAS assume that no person is registered in an external journal.
In your testing, in contrast to that assumption, you keep the persons registered in Climedo. So SORMAS thinks previously registered persons are not registered, and climedo thinks they are. This leads to the symptoms found in your testing.
That why I [said](https://github.com/hzi-braunschweig/SORMAS-Project/issues/10680#issuecomment-1285081817), along with executing the script, it needs to be made sure that the data on climedo side gets deleted as well.

When a health department removes the climedo connection, do they really want to keep the data in climedo? And reuse it later?

I hope you still have the UUIDs of the modified persons on test1402? Otherwise it will be more difficult to fix the broken database state created with your tests.

**Comment by FredrikSchaeferVitagroup** [comment]
> @FredrikSchaeferVitagroup because of 9.3: Is there a way to really deregister the person and not just change the button on UI?

@SahaLinaPrueger It probably is very difficult to do that. I think the only feasible options are to manually deregister the persons in the UI BEFORE disabling the interface, or to make sure that the data gets deleted on climedo side.

**Comment by FredrikSchaeferVitagroup** [comment]
After discussion with @SahaLinaPrueger and cleaning up the state on test1402, I think this ticket can be closed. If there is some more work to do, it can be reopened.
