### ISSUE TITLE
Exposures & Activities as Case - new entry can't be created or edited

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10684]
### Bug Description

In the Epidemiological Date tab (Cases or Contacts) new entry can't be created at Exposures & Activities as a case. 
![Case-Details](https://user-images.githubusercontent.com/101708230/196689502-b575ec0d-2f72-4051-94ac-af3dac8f5885.gif)

If you try to edit an existing entry also an error message appears.

### Steps to Reproduce

1. Open a Case or a Contact
2. Go to the epidemiological data tab
3. Click on "YES" at "Exposure details known" or "Activity as case known"
4. Try to create a "New entry" or edit an existing entry

### System Details

* Device: Laptop
* SORMAS version: 1.76.0
* Android version/Browser: Chrom
* Server URL:  test1401 / release-international
* User Role:  e.g. TestUserInt2 / TestUser11 Contact Officer & Surveillance Officer, ContSup  (Contact Supervisor)

**Comment by AndyBakcsy-she** [comment]
Closing ticket as already merged into the hotfix branch

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the hotfix branch 1.76.1
