### ISSUE TITLE
Possibility to edit a submitted weekly report

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1068]
Retrospective cases can be registered in sormas but  submitted weekly report does not update accordingly and can't also be edited manually, thus submitted weekly report does not match data in database.  We should make weekly reports editable automatically and reflect data  in database.

**Comment by MartinWahnschaffeSymeda** [comment]
As discussed today: A weekly report is a controlling element to improve the completeness of reporting. When a weekly report has been done for a week this report documents what happened in the past and should not be changed. If statistics on number of cases reported within a week and region are needed this should be provided by the statistics section.
