### ISSUE TITLE
Synchronization is being failed in 1.76.0

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#10698]
### Bug Description

Synchronization is being failed after the SORMAS is updated from an older version to 1.76.0. 

### Steps to Reproduce

1. Install the attached older apk, then try to connect with https://release-international.sormas.netzlink.com/sormas-rest/
2. The mobile app will ask for an update, update the app and try to sync,

### Expected Behavior

The app should be able to sync data. 
### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.76.0
* Android version: 1.76.0
* Android Version: 11
* User Role: Hospital Informant
* URL: https://release-international.sormas.netzlink.com/sormas-rest/
### Additional Information

The video, logs, and apk are attached. 
[sync_error_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9829170/sync_error_log.txt)
[sormas-1.60.3-release.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/9829176/sormas-1.60.3-release.zip)
https://user-images.githubusercontent.com/8872102/196933285-c8144bff-2eca-4920-8464-518f5e172b8f.mp4

@MartinWahnschaffe @MateStrysewske @bernardsilenou @roxanamlendea

Reference issue: #10231

**Comment by roxanamlendea** [comment]
@zohaibhassan122 I used the apk you provided and connected to https://release-international.sormas.netzlink.com/sormas-rest/ and I still couldn't reproduce the bug. For me, both initial synchronization and regular synchronization are working.

**Comment by zohaibhassan122** [comment]
Hi @roxanamlendea,
I tried again, and I am still able to reproduce the error, if you have a physical device like a tablet or an android phone, try it there.
The initial sync get failed on immunizations but you are logged in, after that if you go for a regular sync, it also gets failed on immunizations.

I don't think so, that there is any extra step that I am doing.

**Comment by adinaflorea9** [comment]
I have also tried to reproduce the error based on the steps described in the ticket, but was unsuccessful.

However, under the following set of steps the error was reproducible for me as well:
1. In Android Studio, create a new device in the emulator;
2. Once the device is started, delete the existing SORMAS app;
3. Use the APK provided by @zohaibhassan122 (see the Additional Information from this ticket sormas-1.60.3-release.zip) and with drag and drop open it in Google Chrome on the device created at step1;
4. Do the necessary steps for installation and updating the app to the version (as Zohaib also mentioned);
5. In the mobile app, log in using a Hospital Informant; in the web app log in with the same user;
6. In the web app, create a new immunization with vaccination (make sure to set the immunization in the exact jurisdiction of the hospital informant, up to the facility);
7. Trigger a manual synchronization in the mobile app.

Actual behavior:
The synchronization is not successful and an error is displayed in the mobile app UI and in the server logs:
![image](https://user-images.githubusercontent.com/96909231/197193624-37f7a519-83c5-4e75-9508-7f1c6cd7d7cc.png)

Logs from the testing environment:
[logs error sync.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9838847/logs.error.sync.txt)


Additional note:
When the Hospital informant tried to create a vaccination for an immunization created by them in the mobile app, an error that is very similar with the error displayed in the logs during the failed synchronization is displayed in the mobile app UI instead:
![image](https://user-images.githubusercontent.com/96909231/197193956-e6215c56-1353-4f9c-b79a-9fd16666b6c0.png)

The Hospital Informant does have immunization create and edit rights.

**Comment by adinaflorea9** [comment]
Verified part of the ticket on the local machine using the latest SORMAS version from the hotfix branch 1.76.1 (the creation of vaccinations in the mobile app). The other part of the ticket - the update from a previous version to the latest one can not be chinked on my local machine as Android Studio updates the app in a different way.

The update of the mobile app from a previous version to the current one will be checked on the release instance where the issue was initially reproducible, once the hotfix is released.

**Comment by zohaibhassan122** [comment]
Hi @adinaflorea9,
when I am trying to upgrade from an older version to 1.76.1, I am getting an error. App update is not working anymore. It was working with 1.76.0. 

Here are the logs:
[android-debug.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/9927760/android-debug.log)

@MateStrysewske  @JaquM-HZI  @MartinWahnschaffe @bernardsilenou 


![Screenshot_20221103-120707_APMIS](https://user-images.githubusercontent.com/8872102/199705978-d7e72c0f-0a44-4e85-b63a-bda2eef76aa9.jpg)

**Comment by adinaflorea9** [comment]
@zohaibhassan122 Today I have observed the same behavior and discussed it with @MateStrysewske. A ticket will be opened to Netzlink to also check the configurations of the server. Once there is a resolution it will be documented.

**Comment by adinaflorea9** [comment]
Ticket was opened with Netzlink on the 3rd of November. Currently still wafting for a resolution or a response from them.

**Comment by adinaflorea9** [comment]
@zohaibhassan122 I have not received a response from them yet. I will give it another day and tomorrow I will send a follow-up email to them, as it's been the weekend and I logged the request with them on Friday.

**Comment by adinaflorea9** [comment]
@zohaibhassan122 I was able to successfully test this and the update error is no longer reproducible on release-international.sormas.netzlink.com/sormas-rest/. I tried this in Android Studio on devices created in the emulator and on a physical device as well. 

It seems that in the meantime they updated the app version that was on the release-international APK to the correct one and the update works again.
