### ISSUE TITLE
S2S_case/ contacts with lab message cannot be accepted in target system

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10690]
### Bug Description

Sharing a request (case/contact) with an attached lab message with hand over the ownership cannot be accepted in target system.
### Steps to Reproduce

1. share a case with an attached lab message with hand over the ownership
2. try to accept in target system -> error message see under screenshots

### Expected Behavior

shared request with an attached lab message with hand over the ownership can be accepted in target system and lab message can be shared.
### Screenshots

![image](https://user-images.githubusercontent.com/100844689/196875742-44cf0a0f-8932-4c73-a742-dc3a08032ac5.png)

### System Details

* Device:
* SORMAS version: 1.76.0
* Android version/Browser:
* Server URL: 1402 to sormas-x
* User Role:

**Comment by abrudanancuta** [comment]
Steps to reproduce:
1. As National User process a lab message
2. Choose to create new person and new case
3. Open the new created case
4. Choose to share the case with handover
5. Login to the receiver system with National User
6. Go to Share folder and try to accept the case 

Actual result: An error message appears and case cannot be accepted.

Expected results: No error should appear
Test Systems used to reproduce the problem: test-de2 and test-de3, version 1.77.0 - snapshot
Release System used to reproduce the problem: test1402 and release-sormas-x, version 1.76.0

**Comment by SahaLinaPrueger** [comment]
Please note: It should be possible to send the case/contact with the attached lab message from System A to System B and then back again from System B to System A.

**Comment by abrudanancuta** [comment]
Validated on release env with the version 1.76.1
