### ISSUE TITLE
EventInvestigationStatus is inconsistently implemented

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#10700]
### Bug Description

In #10110 the validate method was again used when saving an event. This method requires the EventInvestigationStatus to be not null. Neither the db nor the UI requires this to be set.

### Steps to Reproduce

1.
2.

### Expected Behavior

Either it should be possible to create events without setting an EventInvestigationStatus or the db and the UI should also require the EventInvestigationStatus to be set.

### System Details

* Device:
* SORMAS version: 1.76.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

@cmeyerhzi will provide the information if EventInvestigationStatus is required or not.

**Comment by ChristopherRiedel** [comment]
@cmeyerhzi FYI: The second option (status is required) would mean that we would need a mapping for the suvnet converter. This would maybe also lead us to add the option UNKNOWN to EventInvestigationStatus because I don't see a proper option in EventInvestigationStatus if you don't know the status.

**Comment by cmeyerhzi** [comment]
we have decided that the EventinvestigationStatus should no longer be a required field. so we go with the first option. @JaquM-HZI @ChristopherRiedel

**Comment by AndyBakcsy-she** [comment]
Validated ticket on test-de.sormas.netzlink.com and local setup. 
EventInvestigationStatus  isn't mandatory anymore for creating event
