### ISSUE TITLE
S2S _ Display the full comment in share directory

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10701]
### Bug Description

If you open the share directory you first think that you cannot read a long comment.
It is difficult for a user with no technical understanding to find out how he can read the full comment.

We switched the column with the buttons 'accept' and 'reject' with the column 'comment' because in earlier versions the comment was shown in total and it was annoying for the user to scroll to the right before he could press the buttons 'accept' or 'reject'.
We specified: _Text field as already implemented (1.73.1)_ So we did not asked for that change. 

It is important that the user can read the whole comment without effort, because these are important information.
### Steps to Reproduce

1. share a request with a long comment in the comment field
2. go to the share directory of the source system (outgoing) and try to read the comment 
3. go to the share directory of the target system (incoming) and try to read the comment

### Expected Behavior

You should be able to see the whole long comment by scrolling to the right. 
### Screenshots

You have to go step by step to read the whole comment. If you leave the directory the whole process begins again. 
![read comment_2](https://user-images.githubusercontent.com/100844689/197016675-21794841-5aa3-44d9-9a0b-4a4035ce3fcd.gif)

### System Details

* Device:
* SORMAS version: 1.76.0
* Android version/Browser:
* Server URL: release-sormas-x and release-de
* User Role: admin

### Additional Information

This a behavior that can cause a shit storm. We want to celebrate the implementation of S2S.

**Comment by ChristopherRiedel** [comment]
@SahaLinaPrueger Displaying the whole comment is due to lazy loading not possible. Instead I'll add a tooltip to the comment field as we have it already for the description field of ActivityAsCase.

**Comment by dragosb-vg** [comment]
Validated on **de1**/**de3** and on **release-de** / **test-1402** on Version: 1.76.1.
Case/contact/event sharing comment (for accepted or rejected) are displayed in full length:
- In the Sharing Directory as a tooltip (Incoming/Outgoing)
- In the 'Share' box (sender OR receiver with handover)
![image](https://user-images.githubusercontent.com/111864167/199515413-78d04d03-7523-41ba-8b71-85042ebfa241.png)
![image](https://user-images.githubusercontent.com/111864167/199515616-0e88e7cd-d104-4155-835f-6b9a03d16104.png)
