### ISSUE TITLE
Identifying duplicate entries in the system

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1071]
@MartinWahnschaffeSymeda @MateStrysewskeSym Is there a way we can activate a mechanism to identify duplicates that users have pushed into the database?

We have the dialogue that pops up asking the user entering a possible duplicate whether to proceed or choose an existing person, some users still erroneously push in duplicates. 

Other than a manual eyeballing process of de-duplicating, can we activate a semi-automated process to handle this? 

@hzi-braunschweig

**Comment by MateStrysewskeSym** [comment]
See #408 

We currently don't have such a system in place. It's basically a matter of priority, if this is deemed important enough in one of our sprint meetings we will start to work on it, but so far there always were more pressing things to do.
