### ISSUE TITLE
A Hospital Informant is not able so see and synchronize all immunizations that fall within their responsible jurisdiction

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10710]
### Bug Description

Hospital Informants are not able to see in the web-app all of the immunizations from their jurisdiction, and therefore those are also not synchronized to the mobile app either, unless the Hospital Informant created the immunizations.

### Steps to Reproduce

1. Log into the web app with an Admin+National User and create a case and an immunization that both have the exact jurisdiction of the Hospital Informant (up to the facility);
2. Log into the web app and the mobile app with the Hospital Informant;
3. In the web app, open the case created at step 1 (the case is editable and the immunization associated with it is visible; if opened, it is read only);
4. Navigate to the 'Immunizations' directory and observe the list of immunizations.
5. In the mobile app, trigger a synchronization with the server and observe the immunizations counted, then the immunizations listed in the 'Immunizations' directory.

### Actual Behavior

Step 4: the immunization created at step 1 is not displayed in the list of immunizations, even though it falls under the user's jurisdiction.

Step 5: the immunization created at step 1 is not counted in the synchronization status indication and is not visible in the 'Immunizations' directory, even though it falls under the user's jurisdiction.

### Expected Behavior

The Hospital Informant should be able to see and synchronize all immunizations that are within their responsible jurisdiction.

Just as the behavior is for cases, if the immunization falls under the Hospital Informant's jurisdiction, they should also be able to edit it, as they have the following user rights:
![image](https://user-images.githubusercontent.com/96909231/197513643-3763b011-7b42-4406-b41e-e42dcce66acb.png)

### System Details

* Device: Windows 10; Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.77.0-SNAPSHOT(49b8d0d) - reproducible on earlier versions as well - 1.75.4 and 1.76.0
* Android version/Browser: Chrome; Android 12 (android-app)
* Server URL: local machine
* User Role: Admin+NatUser (vaadin-app); Hospital Informant (android-app)

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the latest version from the development branch 1.77.0-SNAPSHOT.
