### ISSUE TITLE
Add samples card to person view [2]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10714]
### Feature Description

It should to be possible to view samples to a persons within the person view. Therefore, the samples card should be added to the person view. The samples card should display all samples which are connected to a case, contact or event participant. 

### Proposed Change

- [x] add samples card to person view between the cards contact and event. Within the card new samples can be viewed, edited and attached messages viewed. 
- [x] the samples card illustrated all samples connected to cases, contacts and event participants
- [x] the samples can be open, edited and messages viewed (> notebook icon)
- [x] when clicking on the button see samples for this person, the sample directory opens which is filtered for the associated person

### Acceptance Criteria

The samples card is implemented as described above. 

### Implementation Details

- new Backend method `SampleFacade.getByPersonUuid` needed, but without imposing a performance problem of excessive joining.

### Additional Information

![Person view](https://user-images.githubusercontent.com/98821699/205056189-70c12c8b-f54c-42ca-91bd-88642f60601b.png)

**Comment by MartinWahnschaffe** [comment]
@KristinaBorch Thanks for specifying this. A few questions & remarks:

1. Why the differentiation between view and edit? So far when the user has the right to edit the sample, it would open in an editable view. If not, it would be read-only. So we don't need separate buttons/functionalities for this.
2. In the proposed view the user will not be able to see whether the sample is related to a case, contact, etc. Only when the sample is opened, this will be visible, but I guess that's ok.
3. Why should the user be able to jump to the filtered sample directory from here? If there is a good reason: Can we use a much slimmer button? The proposed one implies and important action and takes attention from the user.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
I will add some comments but Kristina will have to confirm them.
- agree with your suggestions. For point 3, will the sample box not contain all the samples of the person? 
- One point that may be obvious is that on the person view, we show all samples linked to all entities of the person, not only case, contact or ep., We also have immunization participants, return travellers, etc and the list may continue to grow.
- Pseidimizaton may also apply ie if a user has full access to one entity of a person and pseudonymized access to another, then the user would not be able to see sensitive data for the sample for the pseudo entity. I am not sure if this is important

**Comment by MartinWahnschaffe** [comment]
> * For point 3, will the sample box not contain all the samples of the person?

Yes, it will have all samples of the person, but show max. 5 at once. It has a paging component to view the other samples as-well.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe @sergiupacurariu 
The pathogen test shown in the sample is the latest pathogen test and does not contain information about the disease tested.  Will it be possible to conclude the tested disease directly under the test result?

**Comment by bernardsilenou** [comment]
No further specifications to add to this  issue

**Comment by sergiupacurariu** [comment]
@bernardsilenou 
your last request is in conflict with this ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/6052.

**Comment by MartinWahnschaffe** [comment]
@sergiupacurariu Is it only in conflict with the intention of the other issue or also with the implementation?

The reason for Bernards comment is the following:
Adding the samples to the person tab with a case for example, would mean that we would also display the samples of other entities in the actual view of the case. So the user would see different samples when switching between the case data view and the case person view. We could address this by either only displaying the samples of the case in the case person tab (which would be inconsistent) or marking the samples that are related to the case. To not have to deal with this, we decided to not show the samples of the person in the case person tab, contact person tab, etc. So only in the person view.

**Comment by adinaflorea9** [comment]
I am reopening the ticket for two minor display issues:

1. In the ticket it is requested that the 'Samples' card to be displayed between the cards for 'Contacts' and 'Events';

2. The info text that is present on the other cards is not present on the 'Samples' card when no samples exist:
![image](https://user-images.githubusercontent.com/96909231/217807347-e484197f-a8a4-4d35-bf2c-237b3a987225.png)

Add text: 'There are no samples for this person'.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.80.0-SNAPSHOT(34ccc5b).

**Comment by MateStrysewske** [comment]
Reopening this issue because the new SampleAssociationType introduced here is displayed as a new option in the sample directory (in the sample association type filter); I believe it shouldn't be shown there in the first place because it does not serve any functional purpose (and doesn't even have a caption). Please make sure that the new association type is not shown anywhere in the UI.
