### ISSUE TITLE
Add filters to sample dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10724]
### Feature Description

Similar to the other dashboard, also the sample dashboard should contain the filters for this epi week, the epi-week before, region and disease. The filter this-epi-week compares the data to the filter epi-week before. 

### Proposed Change

The filters epi week should be the same as on the surveillance and contact dashboard and also works the same. 
- [ ] add epi week filter which is on default set to this epi-week. When clicking on the filter an overview of with quick filter buttons open which allow the user to change the data shown on the dashboard based on the set filter. The options are: (xyz illustrate the associated date)
        1. Costum - when selected another window opens to set a costumed period as shown in the picture below. 
        2. Today: xyz 
        3. Yesterday: xyz 
        4. This epi week: xyz
        5. Last epi week: xyz
        6. This year: xyz
 
![image](https://user-images.githubusercontent.com/98821699/197737104-e929fd8c-3a9e-4e4d-9efb-8e3d31df29fe.png)

- [ ] add a second epi week filter which is on default set to the epi week before. When clicking the button an overview opens which contains the options to filter the dashboard for this epi week or the same pi week last year as shown in the picture below.  

![image](https://user-images.githubusercontent.com/98821699/197738063-784667f1-eb19-46ad-94e7-878e5d2394b9.png)

- [ ] add region filter which contains a list of available regions of the infrastructure data. When clicking the button a drop down opens with the selectable option as shown in the picture below. 
![image](https://user-images.githubusercontent.com/98821699/197738515-0702daf3-98e2-4eda-9927-e42fa8b05f77.png)

- [ ] add disease filter which contains a list with the available disease. When clicking a drop down opens and when selecting a disease the dashboard is filtered for this disease
![image](https://user-images.githubusercontent.com/98821699/197739244-221721c7-da33-4460-b900-b295d869c3aa.png)

- [ ] add reset filters button. when clicking the button, all filters get cleared
- [ ] add apply filters button. When clicking the set filters are applied and related results are shown. 

### Acceptance Criteria

The filters and buttons are implemented as described above.

**Comment by MartinWahnschaffe** [comment]
Merged into https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721 to have a minimal working functionality.
