### ISSUE TITLE
[User Rights] Missing dependencies for the CASE_CREATE user right 

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10735]
### Bug Description
A user with a configured user role that has CASE_CREATE user right, gets an error when creating new Cases, because of a missing dependency. The logs indicate that the **CASE_EDIT** user right is missing.
[user right case_edit.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9859841/user.right.case_edit.txt)

If the user role also has CASE_EDIT user right, he is still unable to create the Case because the **TASK_VIEW** user rights is missing.

### Steps to Reproduce

1. Open the Users Directory, select the 'User Roles' tab and click on 'New User Role';
2. In the 'Create new user role' form, leave the 'User role template' empty', fill in the Caption, and set the 'Jurisdiction Level' to 'Nation'; Save;
3. Select the User Rights as in the screenshots from the Additional Information section;
4. Create a user with the User Role from step 2&3;
5. Log in with the user with the configured user role and open the Cases Directory;
6. Click on 'New Case', fill in the mandatory fields and Save;

### Expected Behavior
If the user has CASE_CREATE rights, he should be able to save the form and the Case should be created;

### Actual Behavior
An error is thrown;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/197763424-a50c28b9-f9e6-4f00-9624-8aebd524ed44.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de and local environment
* User Role: 

### Additional Information
<details>
<summary>Screenshots with the User Rights of the used User Role</summary>    

![image](https://user-images.githubusercontent.com/89522688/197777902-152655a7-7ac8-4f8c-9dbc-a58889c014c4.png)
![image](https://user-images.githubusercontent.com/89522688/197777974-f4e038f9-500e-426d-aed6-c289b9e691e5.png)

**Comment by adinaflorea9** [comment]
The error message is reproducible also for a user that has only CASE_VIEW rights when they navigate between the tabs of a case:
GIF of the user's rights and the behavior:
![Case View Only](https://user-images.githubusercontent.com/96909231/199733682-95c07942-3ea3-49d7-b7bb-4fececa265be.gif)


Logs from the local machine:
[Case View missing Task View.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9929573/Case.View.missing.Task.View.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (b55b8f3).
