### ISSUE TITLE
Add overview of all samples to sample dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10732]
### Feature Description

The sample dashboard should contain an overview of all samples. The overview should be located right below the filters on the left side of the dashboard. The number of samples is always composed by the report date for the expected epi week.  For example when the filter is set to this epi week, the number of all samples is the sum of all samples with report date within this week. Please see the picture below for illustration. 

### Proposed Change

- [ ] add heading All Samples

- [ ] add number of all samples 
- [ ] add linear illustration of all samples divided in to the results pending, positive and negative. The results are displayed in numbers and the percentage is shown in brackets. 

### Acceptance Criteria

The overview of all samples works as described above. 

### Implementation Details

![image](https://user-images.githubusercontent.com/98821699/197768126-3a48b883-a475-4e1b-a5a6-248684ce112a.png)

**Comment by MartinWahnschaffe** [comment]
Merged into https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721 to have a minimal working functionality.
