### ISSUE TITLE
Add overview for count and proportion  for final laboratory results on sample dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10734]
### Feature Description

An illustration of all samples should be added to the sample Dashboard next to the overview of all samples. First an the total number of all positive samples is shown. Below that is a list of positive samples per disease. The arrows next to it demonstrate the development for example compared to the epi week before. This is always dependent on the set filters. The numbers are composed by the number of positive samples based on the report date for the expected epi-week. For example when the filter is set to this epi-week, the number of all positive samples is the sum of all positive samples reported within this epi-week. Please note, the issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/10733 contains the implementation of a description text for the arrows when hovering over them.

### Proposed Change

- [ ] add heading final laboratory result
- [ ] add number and proportion for all categories/enums:  Indeterminate, pending, negative, positive, not done
- [ ] use line or box widget depending on which looks nice

### Acceptance Criteria

* The feature is implemented as described above. 
* The sum of these counts == total number of samples 
* The sum of proportion == 100%

**Comment by bernardsilenou** [comment]
This issue is covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721
