### ISSUE TITLE
Add description text when hovering over the arrows on sample dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10733]
### Feature Description

For improved understanding and interpretation a description text should be added to arrows on the samples dashboard when hovering over it.  The x and y in the description below should be replaced by the number of samples (x) and epi week (y) 

### Proposed Change

- [ ] add description text when hovering over the arrows: 

![Vector1](https://user-images.githubusercontent.com/98821699/197773593-1277bfda-6c76-4d19-9b13-261eca8dfc03.png) = The number of x samples decreased compared to epi week y

![Vector2](https://user-images.githubusercontent.com/98821699/197773836-2c2b95ce-05c5-4033-a2b5-02813e04a1f8.png) = The number of x samples is constant compared to epi week y

![Vector3](https://user-images.githubusercontent.com/98821699/197774016-b587302e-34b7-420d-a4f9-348814146642.png) = The number of x samples increased compared to epi week y

### Acceptance Criteria

The hover works as described above.

**Comment by bernardsilenou** [comment]
Will not be implemented for now
