### ISSUE TITLE
Add overview of all negative samples per disease to sample dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10736]
### Feature Description

An illustration of all negative samples per disease should be added to the sample dashboard next to the overview of all samples. First an the total number of all negative samples is shown. Below that is a list of negative samples per disease. The arrows next to it demonstrate the development for example compared to the epi week before. This is always dependent on the set filters. The numbers are composed by the number of negative samples based on the report date for the expected epi-week. For example when the filter is set to this epi-week, the number of all negative samples is the sum of all negative samples reported within this epi-week. Please note, the issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/10733 contains the implementation of a description text for the arrows when hovering over them.
### Proposed Change

 

- [ ] add heading Negative Samples per Disease
- [ ] add number of all negative samples.
- [ ] add vertical listing of each disease within the set filters with its number of negative samples
- [ ] add arrows next to the number of negative sample per disease wich illustrates the development of negative samples per disease for the set epi week. For Example:
  1. Arrow up: number increased compared to previous epi-week 
  2. Arrow to the right: number stayed constant to previous epi-week
  3. Arrow down: number decreased compared to previous epi-week

### Acceptance Criteria

The feature is implemented as described above. 

### Additional Information

![image](https://user-images.githubusercontent.com/98821699/197778193-00f86d6f-34e5-46ca-84f8-4707ae26fabe.png)

**Comment by bernardsilenou** [comment]
This issue is covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/11411 since the re is a  filter for disease and the list of diseases can be long
