### ISSUE TITLE
Add overview of shipment status to sample dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10740]
### Feature Description

An illustration of shipment status of all samples should be added to the sample dashboard. Therefore, four colored boxes should be added next to specimen condition which contain Information about the samples shipped, not shipped, received and not received. 

### Proposed Change

- [ ] add heading "Shipment Status"
- [ ] add four colored box as followed:
  1. Box 1: shows the total number of shipped samples and has the heading Shipped
  2. Box 2: shows the total number of not shipped samples and has the heading not shipped
  3. Box 3: shows the total number of received samples and has the heading received
  4. Box 4: shows the total number of not received samples and has the heading not received

The boxes illustrate the following: 

- [ ] add number of shipped/not shipped/received/not received samples of this epi-week (always dependent on the set filters of epi week) 
- [ ] add number of shipped/not shipped/received/not received samples of the epi-week before (always dependent on the set filters of epi week) 
- [ ] add arrow which illustrates the development of shipped/not shipped/received/not received samples compared to this epi-week and the epi-week before (always dependent on the set filters of epi week)

### Acceptance Criteria

The feature is implemented as described above. 

### Additional Information

![image](https://user-images.githubusercontent.com/98821699/197788917-6d48f177-2ea1-4428-ad3d-47e4f54c59b2.png)

**Comment by bernardsilenou** [comment]
This issue has been merged into https://github.com/hzi-braunschweig/SORMAS-Project/issues/10738
