### ISSUE TITLE
Add sample status map to sample dashboard [5]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10745]
### Feature Description

A sample status map should be added to the sample dashboard to get a better overview of where samples are located. The map will be similar to the case status map on the surveillance dashboard but specific to the sample dashboard.

### Proposed Change

- [x] add heading Sample Status Map
- [x] Show the location of all samples based on the associated person's address. If that's not given use the report lat/lon as fallback.
- [x] Use a sample icon or at least an cylindrical icon and color them based on their parent entity type.  Suggested colors:
        * case= red
        * contact = yellow
        * ep = sormas dark blue
        * Please have a look at https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721#issuecomment-1434820602 
- [x]  Add button "Layers" (multiple option checkbox) within the map which provides the opportunity to filter the map based on the parent entity type.
        * Show samples for cases, contacts, event participants
        * Suggestion by @MateStrysewske: Add one checkbox per entity type instead of doing it like shown in the screenshot below; users might want to e.g. see all samples connected to cases and contacts, but not events at the same time, which would not be possible with the displayed solution
- [x] Add an information icon such that when the mouse hovers over it, the following text appears; "Samples are shown using the GPS coordinate of the person's home address"
        * Suggestion by @MateStrysewske: Show this icon next to the heading of the section ("Sample Status Map") instead of hiding it in the Layers dropdown because the information is essential to understand what the map is showing
- [x] add button to show map in full screen on the top right of the map
- [x] add button to zoom in and out of the map on the top left of the map 
- [x] Show the sum of counts  in merged icons when zooming. Use an icon that has the same cylindrical outline as the sample icon
- [x] add button the enlarge the map on the top right on the same height as the heading

### Acceptance Criteria

The sample status map is implemented as described above. 

### Additional Information

***Immunization participant can be ignored!***

![image](https://user-images.githubusercontent.com/12996724/215929929-14274454-f9cf-4417-98d7-346bed6273bc.png)

**Comment by bernardsilenou** [comment]
@KristinaBorch  and I have decided to  add these  changes:
-  Replace  the checkbox "show samples" with "show event participant",  This means we would need to add an icon for ep
- Currently, only cases can be shown by home address. The change to be done is to make the filter "by home address" a generic one and not linked to cases only. this will permit users to visualize  any person-related entity (cases, contacts, ep, immunization participant, etc by home address)

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou I guess "immunization participants" refers to event participant of an event with status "screening"?

**Comment by MartinWahnschaffe** [comment]
>     * I'd like to know if we should add the option to view by home address or responsible jurisdiction (or facility if applicable) to [Add sample status map to sample dashboard #10745](https://github.com/hzi-braunschweig/SORMAS-Project/issues/10745)

For now I'd keep it as defined here. We will have a tooltip that describes that the data is based on the person's home address and we also have a tooltip for the filter saying that it's based on the jurisdiction.

>     * A similar situation applies to the map on the contact dashboard, when we click on "show contacts", which data is used here?

It is using the the home address of the related person first. If that's not given it tries the report GPS coordinates. We should do the exact same for the samples.

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.82.0-SNAPSHOT (dd8b900)

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version: 1.83.0-SNAPSHOT (7b5e7d1)
