### ISSUE TITLE
ExternalDataDto needs to implement HasUuid [0.5]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#10750]
### Problem Description

The class ExternalDataDto doesn't implement HasUuid. Therfore an ArchitectureTest has an specific exception for this.

### Proposed Change

Let ExternalDataDto implement HasUuid.
Then remove the exception from ArchitectureTest.

### Additional Information

Needs to be done after #10731 is merged to development with the release of 1.76.1

**Comment by StefanKock** [comment]
> The class ExternalDataDto contains the field uuid which doesn't represent the uuid of ExternalData or something like that. This class is used to update the externalId and the externalToken of multiple entities.

I disagree. If the `uuid` field represent a UUID of any `AbstractDomainObject` I don't see why we should rename it. But at least one comment in `ArchitectureTest` needs to be addressed with this ticket.
