### ISSUE TITLE
Update jackson dependency

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10776]
### Problem Description
Check the link for more details: https://github.com/hzi-braunschweig/SORMAS-Project/security/dependabot/30

**Comment by StefanKock** [comment]
It's coming with payara, so we need update payara or do patching of it.

**Comment by MartinWahnschaffe** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/10499
