### ISSUE TITLE
Create script to artificially age database entries 

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10778]
### Problem Description

We need a possibility to test the automated deletion from 1.76 onwards. It is about data that are 2, 5 or 10 years old on a certain date. 
The corresponding database entries are to be artificially aged via script.   To repeat the test the below mentioned data can be created again. Afterward the script can also be executed again. 

If another approach seems more suitable or anything else could hinder the test, please feel free to contact me. 

When exactly will the job for automatic deletion be started? 

Examples have already been created in the instances https://test1401.sormas-oegd.de/ and https://release-international.sormas.netzlink.com/. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BCAB2~1.KER/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BCAB2~1.KER/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

entitytype | deletionreference | deletionperiod | field | value | comment
-- | -- | -- | -- | -- | --
CASE | CREATION | 3650 | first name | deletion_case |  
CONTACT | CREATION | 3650 | first name | deletion_contact |  
TRAVEL_ENTRY | ORIGIN | 14 | first name | deletion_travel_entries | (DE Only)
EVENT | CREATION | 1825 | titel | deletion_event |  
EVENT_PARTICIPANT | CREATION | 1825 | first name | deletion_event_participant |  
IMMUNIZATION | CREATION | 3650 | first name | deletion_immunisation | (INT Only)

</body>

</html>

**Comment by fhauptmann** [comment]
We need to discuss with developers, what happens when we set creation dates to a date in the past. What happens to history tables and audit database? Will this lead to an inconsistent state? 
Will this apply to all data sets? Or will everything be aged?

**Comment by MateStrysewske** [comment]
@KernB @fhauptmann Replace the dates with the actual values you need. This will of course lead to an inconsistent data state, but I don't think that it will lead to any issues (besides maybe stuff like case ages being calculated wrongly, but since it's about test instances, I don't think it's that bad).

```
UPDATE cases SET creationdate = '2012-11-04' FROM person WHERE cases.person_id = person.id AND person.firstname = 'deletion_case';
UPDATE contact SET creationdate = '2012-11-04' FROM person WHERE contact.person_id = person.id AND person.firstname = 'deletion_contact';
UPDATE travelentry SET creationdate = '2022-10-21' FROM person WHERE travelentry.person_id = person.id AND person.firstname = 'deletion_travel_entries';
UPDATE events SET creationdate = '2017-11-04' WHERE eventtitle = 'deletion_event';
UPDATE eventparticipant SET creationdate = '2017-11-04' FROM person WHERE eventparticipant.person_id = person.id AND person.firstname = 'deletion_event_participant';
UPDATE immunization SET creationdate = '2012-11-04' FROM person WHERE immunization.person_id = person.id AND person.firstname = 'deletion_immunisation';
```

**Comment by KernB** [comment]
@MateStrysewske @fhauptmann  Corresponding entities were created on the release-de and the script was executed. Deleting overnight did not work. Can you please check it? 
Is it possible to start the job manually? It would be good if we had a way to see a result faster.

**Comment by MateStrysewske** [comment]
@KernB No, it's not possible to start the job manually or change its execution time outside of a development machine. It might be possible that the internal calculation of "ten years" slightly differs from the amount of days that you've specified in the table above or something like that. Since the script executed successfully, the creation dates should definitely be updated.

**Comment by KernB** [comment]
@MateStrysewske  Thank you for the check.
Can our backup be imported on a development or QA environment?    

To rule out the possibility that something does not fit together. Here is my configuration: 
- { entitytype: CASE, deletionperiod: 3650, deletionreference: END }
- { entitytype: CONTACT, deletionperiod: 1825, deletionreference: END }
- { entitytype: TRAVEL_ENTRY, deletionperiod: 14, deletionreference: END }
- { entitytype: EVENT, deletionperiod: 1825, deletionreference: END }
- { entitytype: EVENT_PARTICIPANT, deletionperiod: 1825, deletionreference: END }
- { entitytype: IMMUNIZATION, deletionperiod: 3650, deletionreference: END }

To rule out the mentioned slightly differences, is it a good idea to enlarge the values here the next test?

**Comment by MateStrysewske** [comment]
@KernB That would potentially be possible I believe, yes. I don't know exactly for which reason though?

THAT looks like a problematic configuration because I believe the deletion reference `END` means that it counts the amount of days defined by deletion period starting from the latest change date of the entity. You'll need to change that to `CREATION` for the deletion to happen.
