### ISSUE TITLE
[S2S] Sync broken because of occupation type

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10780]
### Bug Description

If a case/contact is shared via S2S and the occupation type is filled in with a value, that does not exist on the other instance this breaks the whole sync of S2S for the person and the case/contact.
There are occupation types present on one system and not present on another because of #10380. 

### Steps to Reproduce

1. share a case/ contact without an occupation type with hand over the ownership
2. accept in target system
3. try if sync works (add/change data (except occupation type) in target system and observe data in source system) 
4. add an occupation type in target system (a value that exists in source system, too) and observe if sync works in source system
5. add an occupation type in target system (a value that do NOT exist in source system) and observe if sync works in source system

### Expected Behavior

Sync should work
### System Details

* Device: Windows 11
* SORMAS version: 1.75.4
* Android version/Browser: Edge
* Server URL: 1402 to release-sormas-x
* User Role: admin

### Additional Information

We have to discuss how to deal with customizable enum values when syncing data:

Here some ideas from @MartinWahnschaffe:

A. Reject the data
B. Accept the data and automatically create an entry in the customizable enums tables - this value would then also be available for other data objects
C. Make the whole customizable enum logic able to deal with values that are not defined in the database.

Besides that I'm wondering whether we should define a full set of occupation types for Germany and reset any different occupation types assigned to persons or migrate those.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI 
Since sync is an important function of S2S, this problem should be solved in 1.76. 

Is it technically the easiest way/ fastes way to introduce a new property that prevents this field from being shared? 
Like #sormas2sormas.ignoreProperty.externalToken=true
#sormas2sormas.ignoreProperty.internalToken=true

**Comment by markusmann-vg** [comment]
Maybe we could add an "UNKNOWN" to the enum of the target system as I don't think we should just add occupation types in another system. A first workaround, where we are trying to exclude the occupation type from sync, will be tested.

**Comment by SahaLinaPrueger** [comment]
We just have to take care about #10544. As long as persons can be edited in two systems and are synced in both systems we have to test what happens with the data if we implement this. 

If it is the easiest/ fastest way for now to stop person sync in the 1.76 that is also ok for me. Just sync of case/contacts/samples/vaccinations have to be implemented and unfortunately the occupation type breaks the whole sync.

**Comment by markusmann-vg** [comment]
@JonasCir & @SahaLinaPrueger 
Excluding the occupation type won't  be done => The mapping to OTHERS and taking over the string is the way to go

**Comment by carina29** [comment]
The fix was merged to hotfix-1.76.1 branch.

**Comment by SahaLinaPrueger** [comment]
@markusmann-vg 
> The mapping to OTHERS and taking over the string is the way to go

What is the meaning of _taking over the string_?
Actual behavior is, that "others" is displayed, but no entry in 'please specify occupation':
![image](https://user-images.githubusercontent.com/100844689/203033979-a2302591-4f17-424c-8984-7c5dbe4b6d48.png)

In some situations (because of sync on both sides) _others_ is displayed on source _and_ target system and the originally occupation type is overwritten.

**Comment by carina29** [comment]
@SahaLinaPrueger, @markusmann-vg 
In this task the problem which caused the broken sync and also an error when the "Accept" (of the shared case) in target system was clicked were solved. 

As it was described in the ticket , this problem happened when the filled in occupation type does not exist on the other target instance. In order to solve the problem when this scenario happened, the "OTHERS"  value was set to the occupation type.

It was not described in the ticket that the "Please specify occupation" field should take the original value of the occupation type, so this requirement was not implemented. 

If you consider that it would be useful, we can create a new ticket for this requirement.  :)
Also some analysis is needed to know what changes needs to be done in order to be possible the filling of the "Please specify occupation" with the original occupation type.
