### ISSUE TITLE
Update to JUnit5

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#10793]
### Problem Description
JUnit5 is out since 2017 and brings the following benefits:

* we get more granularity, and can import only what's necessary
* JUnit 5 allows multiple runners to work simultaneously
* JUnit5 allows Java8+ language features like lambda functions, making tests more powerful and easier to maintain.
* new features for describing, organizing, and executing tests. For instance, tests get better display names and can be organized hierarchically (e.g. https://medium.com/@boonkeat/android-unit-testing-with-junit5-d1b8f9c620b6)
* Allows combination of multiple extensions

Furthermore JUnit5 gives us more freedom of choice and comfort related to replacing our CDI unit testing framework.
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/10074#issuecomment-1294691128

### Proposed Change
Update to JUnit5. This means replacing imports and few clean ups.
The whole process should be done in one step.
Check whether Android app should be updated as-well or separately. -> Separately

### Implementation Details

- [x] org.unit.Test -> org.junit.jupiter.api.Test
- [x] org.junit.Assert.* -> org.junit.jupiter.api.Assertions.*
- [x] org.junit.Assert.assertThat -> org.hamcrest.MatcherAssert.assertThat
- [x] Before -> BeforeEach
- [x] BeforeClass -> BeforeAll
- [x] After -> AfterEach
- [x] ArchUnitRunner no longer needed
- [x] Test(expected=Exception) -> assertThrows
- [x] Some assertions currently have string message first -> is last param instead now
- [x] Use latest WireMock version for Junit5
- [x] CaseFacadeEjbTest: Extract wire mock related tests
- [x] TestContainers Junit5 extension + workaround: https://github.com/testcontainers/testcontainers-java/issues/970#issuecomment-625044008
- [x] Move tests for external surveillance functionality from CaseServiceTest and EventServiceTest into ExternalSurveillanceToolGatewayFacadeEjbTest
- [x] Remove sharing logic from testArchive... test in CaseFacadeEjbTest and EventFacadeEjbTest

**Comment by StefanKock** [comment]
While working on #10801 I noticed that `StartupShutdownServiceTest` has a compile error in my Eclipse because `testcontainers` still relies on JUnit 4: `The type org.junit.runner.Description cannot be resolved. It is indirectly referenced from required .class files`

I tried `@SuppressWarnings("all")` but that did not help. On Jenkins the test `testHistoryTablesMatch` runs successfully (33s).
