### ISSUE TITLE
Add dummy data generation for backend

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1079]

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Config entry "devmode"
- [ ] New view DeveloperView to configuration section that is only visible when devmode is true
- [ ] Form with textfield and two date fields to generate x cases within the time period (default: last 90 days). Optionally a disease

Logic to create the cases:

- [ ] Generate the x cases using the date range and the diease (or all diseases). Use sin function for distribution
- [ ] Use two arrays with at least 10 entries for first and last name. Combine those to double first and last names to have more combinations.
- [ ] Randomly set values for all case fields based on the data type: text, YesNoUnk, date (1-3 days after report), enum

**Comment by MateStrysewskeSym** [comment]
- [ ] Add labels
- [ ] Check whether symptoms are correctly set randomly (and fix if they aren't)

**Comment by MateStrysewskeSym** [comment]
In the long-term, we might need to think about data consistency. Even though this is supposed to be used for testing/development, it's probably desirable that there are no "deceased" cases with living persons, etc.
