### ISSUE TITLE
[Cases] Pop-up to let the user know that the person is already an event participant is triggered twice

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10804]
### Bug Description

When a person is already an event participant and the user links the person's case to that event, a pop-up to let them know that the person is already an event participant of that event is triggered twice.

### Steps to Reproduce

1. Create a contact and a resulting case for it;
2. Link the contact to an event;
3. Then link the case to the same event.

### Actual Behavior

The pop-up that is triggered to let the user know that the person is already an event participant to that event is triggered twice.  This is visible when the user clicks to close the pop-ups.

### Expected Behavior

The pop-up should be triggered only once.

### Screenshots

GIF of the behavior:
![Confirmation](https://user-images.githubusercontent.com/96909231/199258606-ace967bf-aa8d-430a-87a8-3c0d9cbed45c.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0; 1.76.0
* Android version/Browser: Chrome
* Server URL: local machine, https://release-international.sormas.netzlink.com/
* User Role: Admin+NatUser

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.77.0-SNAPSHOT (e768bf7)
