### ISSUE TITLE
When creating a new case check for existing cases to prevent duplicates

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1080]
When I tried to create a case already in the system, the pop-up comes up, so I select the existing person and click on select. This creates another record of the case. 

@MateStrysewskeSym @hzi-braunschweig This looks like a bug. Can you try to reproduce this at your end please? This might account for the high number of duplicate entries we have currently in the system.

**Comment by MateStrysewskeSym** [comment]
@Chinedar This is not a bug, it's intended. We currently don't have a duplicate detection mechanism for CASES on case creation - we only search for PERSONS that have a similar name and thus might already be in the system. Therefore, when you select an already existing person when creating a case, the case is still created, but the person associated with it is not created, but the existing one is picked from the system.

CASES and PERSONS are different entities in the system; a case always has a person, but a person isn't necessarily associated with only one case, but can be associated with many cases, contacts and even events. They're only part of the case, but they aren't identical to the case. This concept seems to cause a lot of misunderstandings not only for users, but also for other people working on SORMAS. We've already identified this as a major problem and will try to find a solution to make this association more clear.

**Comment by Chinedar** [comment]
@Mate I completely understand how the concept works and have trained users
severally on this. What we see now as a major problem (just like you
explained) is that more than one case is always created by users for the
same person resulting in high rate of duplicates within the system. When we
stress the need for users to cancel or desist from creating more than one
case for a person if this is not intended, they simply always click on
"select" thinking this to be the solution.

Hopefully we can get a solution as soon as possible. Data cleaning is
becoming a major challenge. Thanks.

**Comment by MateStrysewskeSym** [comment]
@Chinedar I think the solution is to not only search for duplicate persons, but also already existing cases that match the case the user is about to create and notify them about the possible duplicate. We have this in the backlog and will discuss priorities with HZI on our next sprint meeting.

**Comment by MateStrysewskeSym** [comment]
Done in #757
