### ISSUE TITLE
Edit button on previous hospitalization not responsive

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1081]
When you have information entered for previous hospitalization, you have to click on this severally before it responds for you to edit the information.

**Comment by hzi-braunschweig** [comment]
@Chinedar You are right. Icon position of the edit button shifted. You can also double click on any part of the fields and it would open to edit. 
@MartinWahnschaffeSymeda @MateStrysewskeSym
