### ISSUE TITLE
sending to external reporting tool fails

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10811]
### Bug Description

attempting to send a case or event results in an error message.
it does not matter whether the case is old or new.
bulk mode or standard mode also doesn't matter.
### Steps to Reproduce

1.open a case / event
2. try to send it to reporting tool

### Expected Behavior

should work.
### System Details

* Device: 
* SORMAS version: 1.76.1, 14.3
* Android version/Browser:
* Server URL: test1402, survnet-import-test
* User Role: admin, national user

### Additional Information

[survnet error log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9920428/survnet.error.log.txt)

Was caused by #10731

**Comment by ChristopherRiedel** [comment]
ExternalDataDto needs to implement Serializable.

**Comment by abrudanancuta** [comment]
Validated on release environment test1402 with the version: 1.76.8
