### ISSUE TITLE
[DEMIS2SORMAS] Add a Field for the NotificationBundleId to the External Message and map it when processing [2]

### ISSUE THREAD

**Issue by FredrikSchaefer** [hzi-braunschweig/SORMAS-Project#10826]
### Acceptance Criteria

- [x] Add a field the the ExternalMessage that can hold the NotificationBundleId (a proper name has to be thought of, so that it does not get confused with ExternalMessage.reportId which gets populated with the Composition.identifier.value.
- [x] Map this field to the SurveillanceReport.externalId at the end of processing an external message that is related to a case
- [x] add this field to the documentation (data dictionary...)
- [x] add tests

**Comment by abrudanancuta** [comment]
Verified on local env with the version: 1.78.0-SNAPSHOT (e5b3129)

**Comment by StefanKock** [comment]
Adjusted milestone because it is already merged.
