### ISSUE TITLE
S2S - Outgoing shares - Revoke button is flickering and the list is not loading

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#10835]
### Bug Description
S2S - Outgoing shares - Revoke button is flickering and the list is not loading

### Steps to Reproduce
1. As Admin + NatUser login on a system that has S2S
2. Go to Share directory
3. Select the filter Outgoing
4. Scroll more in the page
5. Apply the filter dropdown Pending

### Actual Behavior
The page is not loading entirely and the Revoke button is flickering

### Expected Behavior
The page should load

### Screenshots

https://user-images.githubusercontent.com/91872179/199735114-67aa1815-6467-4de5-b7b0-41c54043406a.mov

### System Details

* Device:
* SORMAS version: 1.76.1, 1.77.0-snapshot
* Android version/Browser:
* Server URL: test and release environment that have S2S
* User Role: Admin + NatUser

**Comment by JonasCir** [comment]
So the problem is the implementation in `ShareRequestView`:
````java
	@Override
	public void enter(ViewChangeListener.ViewChangeEvent event) {
		gridComponent.reload(event);
	}
```

This will constantly refresh the page.

**Comment by JonasCir** [comment]
@AndyBakcsy-she I think this was verified

**Comment by abrudanancuta** [comment]
Validated on release environments with the version 1.76.3
