### ISSUE TITLE
Filter region/district/community in case directory shows results based on responsible jurisdiction and place of stay

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10834]
### Bug Description

When the place of stay differs from the jurisdiction, the filter district in case directory shows the results based on responsible jurisdiction AND place of stay. 

### Steps to Reproduce

1. Create a case where responsible jurisdiction differs from place of stay
2. Go to case directory 
3.  Set filter region and district to responsible jurisdiction of step 1
4. Observe Results 
5. Set filter region and district to place of stay of step 1
6. Observe results

### Expected Behavior

The filter region/district/community in the case directory shows results only based on responsible jurisdiction. 

### System Details

* Device:
* SORMAS version: 1.76
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

![Jurisdiction differs from place of stay](https://user-images.githubusercontent.com/98821699/199733501-c3622460-ad2f-4355-b0fa-9b3acdd5657e.gif)

**Comment by MateStrysewske** [comment]
@KristinaBorch What's the reasoning behind excluding the place of stay from the filter?

**Comment by KristinaBorch** [comment]
@MateStrysewske The reason is that, some health departments are responsible for several districts and this falsies the number of cases for a district when using the filter. With the issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/10837, we plan to add another filter which allows health departments to decide whether the filter region/district/community should be based on responsible jurisdiction or place of stay.

**Comment by MateStrysewske** [comment]
@KristinaBorch I'll close this issue and move #10837 into the current sprint instead because while implementing this issue here, I had the choice of doing it in a way that would require us to get rid of the work when implementing the dropdown, or basically doing everything in #10837 minus the dropdown itself anyway, so I decided to go with the second choice and add the dropdown while I was already at it. :)
