### ISSUE TITLE
Add filter to choose between responsible jurisdiction and place of stay in case directory [1]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10837]
### Feature Description

As the filter region, district and community is based on the responsible jurisdiction, a filter should be added to decided if the filter region, district and community should show results based on responsible jurisdiction or place of stay when it differs. 

### Proposed Change

- [ ] add filter with drop down to choose between responsible jurisdiction and place of stay when it differs for a case. The filter should be located in front of the region filter in the case directory. And allows users to decide if the results of region, district and community should be shown based on responsible jurisdiction or place of stay. 

### Acceptance Criteria

The filter is implemented as described above.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(1d5b2bd).
