### ISSUE TITLE
Import of population data in SORMAS [3]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1084]
We want to be able to display statistics (like incidence, CFR, number of cases, etc) by sex, age, etc on the dashboard or statistic section in SORMAS. In this regard, we need the yearly population denominators in SORMAS, this means we have to import the population projections for each year by district, age and sex in SORMAS. Two options to discuss in next sprint:
1-Import the projected data for each year
2-Import only data for 2006 and set the projection function to automatically do the projections based on the year chosen by the user.

**Comment by bernardsilenou** [comment]
Here is the data by sex and district to be imported. The is data is for 2006 survey, thus we have do a projection to get the population for the year of interest.

[nigeria_big_data_set_all_states_and_all_districts.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/3171865/nigeria_big_data_set_all_states_and_all_districts.zip)

**Comment by bernardsilenou** [comment]
Attached are is the population data in 2006 by age group
[nigeria_big_data_set_all_states_and_all_districts.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/3232143/nigeria_big_data_set_all_states_and_all_districts.zip)
 and sex

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou I finally managed to create the template for the population data:
[population_data_template.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3285177/population_data_template.xlsx)

**Comment by bernardsilenou** [comment]
I have transformed the data in the suggested format, However the name of columns and their order is not the same as on the template, Is this real important? Is yes, then I will reorder and rename another day.
[popDataByDistrictAndSexNigeria2006.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3311114/popDataByDistrictAndSexNigeria2006.xlsx)
[popDataByDistrictAndSexNigeria2006.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/3311115/popDataByDistrictAndSexNigeria2006.txt)

**Comment by bernardsilenou** [comment]
Nigeria has 772 districts minimum but the attached file has 763. 9 districts are missing. I will investigate this latter

**Comment by hzi-braunschweig** [comment]
Nigeria has 774 districts @bernardsilenou

**Comment by MartinWahnschaffeSymeda** [comment]
Implementation:

- [ ] Population entity: region, district, sex, age group, population, date. Growth rate will stay a part of region and district
- [ ] Generate import template by creating columns that combine sex and age group
- [ ] Import asks for the reference data the data was collected
- [ ] Export all existing data, so users can check what is missing and import it
