### ISSUE TITLE
[Events - User rights - Documents] User without document or quarantine orders view rights can see the ''Document Templates' card on an event

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10851]
### Bug Description

When a user has EVENT_VIEW rights, on the event page, they can see the 'Document Templates' card, even though they do not have rights over documents/quarantine orders.

Additionally, if the user is also given EVENT_EDIT rights, then they can generate new quarantine documents for that event.

### Steps to Reproduce

1. Create a configured user role with the following rights:

<details>

<summary>User rights</summary>

<br>

![image](https://user-images.githubusercontent.com/96909231/200340657-97bf54c2-60f7-429a-adc5-08268f1ea49b.png)
![image](https://user-images.githubusercontent.com/96909231/200341214-fd90159f-c293-4a8e-9c9e-cfaf76e4d672.png)
![image](https://user-images.githubusercontent.com/96909231/200341305-d0b3aa24-d863-49d1-9645-1a546a0e524f.png)
![image](https://user-images.githubusercontent.com/96909231/200341335-41dc294d-63a6-405e-b82b-6c7133ab6fff.png)

</details>

2. Create a user with the user role from step 1;
3. Log in with that user and open an event;
4. Click on the 'Create' button from the 'Document Templates' card;
5. Select a document template from the dropdown and click ''Generate'.

### Actual Behavior

The user can successfully generate and download a new quarantine document for that event.

### Expected Behavior

The user should not be able to see or click on the 'Document Templates' card if they do not have rights for quarantine documents.
 
### System Details

* Device: Windows 10
* SORMAS version: 1.77.0; 1.76.2.
* Android version/Browser: Chrome
* Server URL: local machine; release-international.sormas.netzlink.com
* User Role: Admin+NatUser; Configured user as per screenshots from the ticket

**Comment by dinua** [comment]
I have implement it to be the same as for cases . If the user do not have right QUARANTINE_ORDER_CREATE it will no longer see the card

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(068533b).
