### ISSUE TITLE
[S2S] Sharing a Contact or Case individually should not be possible if the Sample is linked to both entities

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10852]
### Bug Description
The Contact and the Case share cannot be accepted by the receiving instance if they have a Sample which is linked to both entities (was used for the resulting Case).
The issue is not reproducible if a Case is created for the Contact by 'Create a Case for this Contact Person' without a Sample.

### Steps to Reproduce

1. On Sormas A, Create a Contact (and select a Source Case);
2. Add a Sample with a positive Pathogen Test Result and create a resulting Case;
3. Share the Case with 'Hand over the ownership';
4. On Sormas B, try to accept the Case 
-> the Case cannot be accepted because the database does not contain the UUID of the Contact;
![image](https://user-images.githubusercontent.com/89522688/200339682-f216f225-0de5-4435-8546-1f3032cbb69c.png)
5. Go back to Sormas A also share the Contact with 'Hand over the ownership' (in order to be able to share the Contact, you need to share the Source Case first: 'Exclude personal data');
6. Go back on Sormas B and accept the Source Case;
7. Then, try to accept the Contact;
-> the Contact cannot be accepted because the database does not contain the UUID of the Case;
![image](https://user-images.githubusercontent.com/89522688/200341148-a42a2e6f-ef78-45dc-8ba2-7fdf93779881.png)
8. Try to accept the Case again;
-> the Case cannot be accepted because the database does not contain the UUID of the Contact;
![image](https://user-images.githubusercontent.com/89522688/200341307-7ec478d0-389e-4777-a65b-c38315c6e4ac.png)

### Actual Behavior
The user is in a loop and is unable to accept the share for the Contact and for the Case;

### Expected Behavior
Don't be able to share a Contact or Case individually if the Sample is linked to both entities

### System Details

* Device: Windows 10
* SORMAS version: 1.76.2
* Android version/Browser: Chrome
* Server URL: release-sormas-x.sormas.netzlink.com and release-de.sormas.netzlink.com
* User Role: Admin + National User

**Comment by leventegal-she** [comment]
I don't consider this to be a bug, it is a kind of edge case that was never specified and therefore needs to be refined if we automatically send the contact or we let the sample to be saved without contact thus allowing to lose the link to the contact when it will be sent to the same system later.

**Comment by ChristopherRiedel** [comment]
Needs tests.

**Comment by abrudanancuta** [comment]
Validated on test.de1, test.de2 with the version: 1.79.0-snapshot(https://github.com/hzi-braunschweig/SORMAS-Project/commit/e396cf4261bb1bc13971a0eb3d0cbd404c7a5ca7).
The main scenarion for this ticket is:
1. Have a Contact which has a sample with Positive pathogen test
2. Create a resulting Case
3. Try to share the Case with Handover
=> at this point the sharing will return an error, which is expected after having this ticket implemented
<img width="1440" alt="Screenshot 2023-01-27 at 14 03 38" src="https://user-images.githubusercontent.com/91872179/215497225-295e14d8-4a7c-4ef4-b81a-a790840193ee.png">
