### ISSUE TITLE
Bug synchronizing sample

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1086]
> at de.symeda.sormas.api.sample.__SampleFacade_Remote_DynamicStub.saveSample(de/symeda/sormas/api/sample/__SampleFacade_Remote_DynamicStub.java)
> at de.symeda.sormas.api.sample._SampleFacade_Wrapper.saveSample(de/symeda/sormas/api/sample/_SampleFacade_Wrapper.java)
> at de.symeda.sormas.rest.EntityDtoResource.savePushedDto(EntityDtoResource.java:26)
> at de.symeda.sormas.rest.SampleResource.postSamples(SampleResource.java:68)
> 
> Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column
> "associatedcase_id" violates not-null constraint
>   Detail: Failing row contains (429464, WGINYY-IV72CH-7NBMVA-GTFTSJNM, 2019-04-26
> 08:57:34.255785, 2019-04-24 15:04:09.593, null, , 2019-04-19 23:00:00, 2019-04-24
> 15:04:09.594, 178196, BLOOD, , 136527, null, 2019-04-20 15:04:51.807, , null, null, ,
> null, null, null, ["2019-04-26 08:57:34.255785+00",), null, t, f, null, null, null, , t,
> f, , , PENDING, , ).
> Error Code: 0
> Call: INSERT INTO SAMPLES (ID, ADDITIONALTESTINGREQUESTED, CHANGEDATE, COMMENT,
> CREATIONDATE, LABDETAILS, LABSAMPLEID, NOTESTPOSSIBLEREASON, PATHOGENTESTRESULT,
> PATHOGENTESTINGREQUESTED, RECEIVED, RECEIVEDDATE, REPORTDATETIME, REPORTLAT,
> REPORTLATLONACCURACY, REPORTLON, REQUESTEDADDITIONALTESTSSTRING,
> REQUESTEDOTHERADDITIONALTESTS, REQUESTEDOTHERPATHOGENTESTS, REQUESTEDPATHOGENTESTSSTRING,
> SAMPLECODE, SAMPLEDATETIME, SAMPLEMATERIAL, SAMPLEMATERIALTEXT, SAMPLESOURCE,
> SHIPMENTDATE, SHIPMENTDETAILS, SHIPPED, SPECIMENCONDITION, UUID, ASSOCIATEDCASE_ID,
> LAB_ID, REPORTINGUSER_ID, REFERREDTO_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
> ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

**Comment by MartinWahnschaffeSymeda** [comment]
Most likely goes down to the following error report:

Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse
Persistence Services - 2.6.4.qualifier):
org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column
"reportdate" violates not-null constraint
  Detail: Failing row contains (433043, 2019-04-29 07:35:03.152366, 2019-04-29
07:35:03.157, null, CHOLERA, null, null, SQGRBL-QD7RQZ-URWOAD-PY632GY4, null, 136522,
140344, 140344, 422269, 433048, 104449, 104412, 104410, SUSPECT, PENDING, 433047, NO,
433046, NIE-BYS-GBB-19-024, ["2019-04-29 07:35:03.152366+00",), COTTAGE HOSPITAL OTUASEGA,
4.97133333333333294, 6.34579166666666605, , 4.30000019, null, null, null, null, RECOVERED,
2019-04-03 23:00:00, null, , null, null, null, null, null, 2019-04-18 19:15:56.27, 140344,
NOT_CLASSIFIED, f, 433049, 433044, NO, ).
Error Code: 0
Call: INSERT INTO CASES (ID, ARCHIVED, CASEAGE, CASECLASSIFICATION, CHANGEDATE,
CLASSIFICATIONCOMMENT, CLASSIFICATIONDATE, CREATIONDATE, DENGUEFEVERTYPE, DESCRIPTION,
DISEASE, DISEASEDETAILS, EPIDNUMBER, HEALTHFACILITYDETAILS, INVESTIGATEDDATE,
INVESTIGATIONSTATUS, OUTCOME, OUTCOMEDATE, PLAGUETYPE, PREGNANT, RECEPTIONDATE,
REPORTDATE, REPORTLAT, REPORTLATLONACCURACY, REPORTLON, SEQUELAE, SEQUELAEDETAILS,
SMALLPOXVACCINATIONRECEIVED, SMALLPOXVACCINATIONSCAR, SYSTEMCASECLASSIFICATION, UUID,
VACCINATION, VACCINATIONDATE, VACCINATIONDOSES, VACCINATIONINFOSOURCE, CASEOFFICER_ID,
CLASSIFICATIONUSER_ID, COMMUNITY_ID, DISTRICT_ID, HEALTHFACILITY_ID, PERSON_ID, REGION_ID,
REPORTINGUSER_ID, SURVEILLANCEOFFICER_ID, CLINICALCOURSE_ID, EPIDATA_ID,
HOSPITALIZATION_ID, SYMPTOMS_ID, THERAPY_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, ?, ?)

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar 
User KOLOKUMA_SO has multiple cases that don't seem to have a state assigned. I have no idea how this could happen.

Can you please have a look at the users device and see what the data of those cases looks like?

These are the UUIDs:
RMTPZT
UEMYWM
UKEMDR
WGTDMS

**Comment by Chinedar** [comment]
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> I've checked with all the
UUIDs given and none of such records are in the system. We have asked the
user and he says he doesn't have any case entered without a state.
Are these UUIDs for the cases entered without state variable?

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Yes, those users won't be in the system database, because they can't be synchronized. But they are for sure on the device of that user.

If you want to make it easy just do a re-sync on the device of that user.

Note, I'm not the github user with the name martin - so I don't receive any notifications for that...

**Comment by Chinedar** [comment]
ok thanks this is noted. Talking with the user now.
