### ISSUE TITLE
[Exposure - Cases] Error appears when a user tries to open an existing exposure

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10874]
### Bug Description

When a user that has access to only sensitive data an error occurs when trying to open an existing exposure.

<details>

<summary>Screenshots of the user rights</summary>

<br>

![image](https://user-images.githubusercontent.com/96909231/200815799-59d13857-3c6d-4389-bace-67c0ccc92481.png)
![image](https://user-images.githubusercontent.com/96909231/200815828-7dae24f6-6379-4198-be15-55a5bcdc339a.png)
![image](https://user-images.githubusercontent.com/96909231/200815845-7c8bb690-a4fd-4e1e-ab37-fb0627c49aa0.png)
![image](https://user-images.githubusercontent.com/96909231/200815876-d7b2ffd7-c68e-4ef8-8df3-b4c903cdd166.png)
![image](https://user-images.githubusercontent.com/96909231/200815905-8047bd8e-439b-4ce4-bb47-dadf55543cda.png)
![image](https://user-images.githubusercontent.com/96909231/200815933-526be8d1-3835-4e1b-8483-c56f833a0a1f.png)
![image](https://user-images.githubusercontent.com/96909231/200815950-991a2807-47c1-4655-889f-eede757feb0e.png)

</details>

### Steps to Reproduce

1. Log in with an Admin+NatUser and create a case with an exposure;
2. Log in with a user created with the user rights from the screenshots from the bug description;
3. Click to open the exposure created at step 1.

### Actual Behavior

An error appears in the UI:
![error exposures](https://user-images.githubusercontent.com/96909231/200816217-a3f6b574-70d5-4cb8-80f1-bb5cdbee57f0.png)

An error is visible in the logs as well:
[Logs error epi data exposures.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9970440/Logs.error.epi.data.exposures.txt)

### Expected Behavior

The user should be able to successfully open the existing exposure.

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0 
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Configured as per the screenshots from the bug description

**Comment by roxanamlendea** [comment]
Reopening the ticket because of the following finding:

1. Create a Contact in jurisdiction A and add Exposure entries;
2. Log in with a user from jurisdiction B and open the Contact from step 1;
3. Click on the eye icon of the Exposure entry;
-> an error is thrown.

![image](https://user-images.githubusercontent.com/89522688/201929795-7d761cb5-d898-4bfd-a0f9-dcc0ae757ddd.png)

**Comment by MateStrysewske** [comment]
@roxanamlendea That's kinda strange. I can't reproduce this on my system, and the logs don't seem to reflect the current development state (i.e. the line that is shown in the logs producing the error doesn't contain any code that could produce an error). Are you sure you tested this on a system/version that is up-to-date with the development state?

**Comment by roxanamlendea** [comment]
@MateStrysewske Hmmm...I can no longer reproduce it either. When I reopened the ticket I thought I was on the latest version of the development branch, but I was probably mistaken.

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using the latest version of SORMAS - 1.77.0-SNAPSHOT(6aa9136).
