### ISSUE TITLE
Giving informant the possibility to record the result of rapid test

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1087]
The Nigerian and Ghana team confirmed that for diseases like CSM and Cholera, rapid test are usually done at health facilities and informants have the possibility to add the results in SORMAS. Further, for Cholera, not all the samples are sent to reference lab, rapid test is sometime enough.
How can we allow informants to record rapid test results in SORMAS. We do not need to have country specific but a unique solution for both countries. Open discussion

**Comment by MateStrysewskeSym** [comment]
See #1109
