### ISSUE TITLE
[Merging] Merge persons via bulk actions - S2s related changes

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10881]
### Problem Description

The changes were initially addressed in comments to ticket #5606  but they were not included at the time of the estimation of the ticket. Comments were logged initially by @SahaLinaPrueger  and @JaquM-HZI and have been copied into this ticket.

### Proposed Change

**Part I:**
~~I have two more tasks in connection with S2S~~

~~- [ ] would be nice if you could adapt/ add the option to go directly to the 'person merge' if the message: There is at least one similar person in your system. If you accept the request the case/contact maybe will create a person in your system as a duplicate. Please check this after accepting. (https://github.com/hzi-braunschweig/SORMAS-Project/issues/9527) appears. So would be nice if okay, and continue to person directory would be replaced by okay, and continue to merge overview~~

- [ ] please note that person merge has to function similar but not identical to case/contact merge in connection with S2S:

Target System: The leading person in target system can only be the person, who is getting into the target system if the request was shared with ownership .

Target System: The leading person in target system can only be the person, who is getting into the target system if the request was shared without hand over the ownership . But attention: the only prerequisite has to be, that at least one of the entity of the person who already is in target system has to be there with ownership. After merging, (leading person is the person, who is getting into the target system from source system) the person is editable, but the shared case/contact without hand over the ownership is still not editable.
For cases/contacts the behavior is different: If the request was sent without hand over the ownership you cannot merge a case/contact in target system and that is good.

Source System: The leading person in source system can only be the person, who's entity was shared with the target system.
Source System: If an entity of the person was shared with ownership : The leading person in source system can only be the person, who's entity was shared with the target system. The only prerequisite has to be, that at least one of the entity of the person who already is in source system has to be there with ownership. After merging, (leading person can only be the person, who was shared with the target system) the person is still editable, but the shared case/contact with hand over the ownership is still not editable.

Note: If I speak of shared persons I mean a person, who's entity was shared. I know persons cannot be shared.

Part II:
Testing comments (testing ongoing):

For S2S if I want to merge two persons, one shared with ownership and one entered manually, trying to merge the shared person in the manually one ends up in an error. Merging with having the shared case as leading works, but in the sending system, opening the shared case shows an error:
![image](https://user-images.githubusercontent.com/96909231/200841800-57a36f27-be69-4228-a6df-df997238e231.png)

### Additional Information

Assigning the ticket to the Interactions Team Backlog as discussed in the refinement from the 9th of November.

**Comment by SahaLinaPrueger** [comment]
Okay, the first task of part 1 is irrelevant. I see now how person merge via bulk action works on test-de2 and we do not need this task anymore.

BUT we really have to implement the second task. Otherwise the person merge will break S2S Sync. We cannot allow that a feature breaks another feature, right? And Part II is a bug, or not? @JaquM-HZI

**Comment by JaquM-HZI** [comment]
@adinaflorea9 @SahaLinaPrueger I think this is the same as https://github.com/hzi-braunschweig/SORMAS-Project/issues/10992, maybe we move both together?

**Comment by SahaLinaPrueger** [comment]
> For S2S if I want to merge two persons, one shared with ownership and one entered manually, trying to merge the shared person in the manually one ends up in an error.

I cannot reproduce the finding from @JaquM-HZI because at the moment it is not possible to merge shared persons:
![image](https://user-images.githubusercontent.com/100844689/203977420-42659973-5493-4579-ab27-55bfd0fd56f1.png)

If the finding from @JaquM-HZI could have been reproduced, that would have been great, because we do not want that the leading case is the manually entered one. 

> Merging with having the shared case as leading works, but in the sending system, opening the shared case shows an error

According to VG the reason for the error message is: #10957 

>Part 1

As Jaqueline wrote this is within the ticket #10992 

If it is okay for you @adinaflorea9 I would discard this ticket, because all findings have another ticket or the finding is not a bug.

**Comment by adinaflorea9** [comment]
@SahaLinaPrueger and @JaquM-HZI Following your comments from above, I will then discard this ticket as a duplicate.
