### ISSUE TITLE
Variables requested by NCDC & WHO to be added for Yellow fever and Measles

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1088]
WHO is looking to do a pilot with SORMAS in chosen states to enable them take a decision to completely migrate Measles and Yellow Fever data from their own database into SORMAS. 

The attached excel has two sheets and the fields marked yellow are fields not in SORMAS that they have requested to be added. 
[YF-Measles Data entry.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3132063/YF-Measles.Data.entry.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
All the following fields need to be part of the detailed export:

- [ ] add reporting country column to the detailed case export. Use prefix used in epid-code
- [ ] add urban/rural field to location form
- [ ] enable vacination doses for measles and yellow fever
- [ ] add "date received at region level" and "date received at national level". Renamed "reception date" to "date received at district level". Put all fields together in a block with the header "Reception dates of paper form"
- [ ] add "associated with outbreak" as a calculated info the the case and the export

@Chinedar 
Please find discuss: Phone and email   address of clinician, Date Results sent   to the clinician (dd/mm/yyyy), Date district received lab results   (dd/mm/yyyy)

**Comment by MateStrysewskeSym** [comment]
- [ ] We should think about completely removing the former reception date (now date received at district level) from all pieces of logic concerning the "new case date" since the report date is customizable

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda let's go with your suggestion; clinician details (text field) to capture phone and or email address of clinician. If there are further reviews, they will let us know after the release. 
Reception date I believe can go now that we have clear defined dates capturing information flow at various levels.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Thanks! Reception date will be turned into Date received at district/LGA level as we've defined in the last sprint review.

**Comment by MateStrysewskeSym** [comment]
- [ ] Add "Date received at district level" to mobile app
- [ ] Change caption of area type to "Area type (urban/rural)"
- [ ] Add a hint to clinician details (same content as description) OR create an issue if this is too complicated

**Comment by MateStrysewskeSym** [comment]
- [ ] rename diseaseSource in CaseExportDto to disease and disease to diseaseFormatted
