### ISSUE TITLE
Button to trigger automatic deletion

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#10901]
### Problem Description

To test automatic deletion it is often not feasible for developers/testers to wait until the following day to see if the deletion worked.

### Proposed Change

Introduce a button hidden behind the DEV_MODE to trigger `CoreEntityDeletionService.executeAutomaticDeletion()`.

### Implementation Details

 - [x] Use `DeletionConfigurationFacade`
 - [x] Use `@Asynchronous`: UI does not wait, and logic should then be executed with SYSTEM as user.
 - [x] Basic logging to show that it was started and did finish.

The discussed approach does not prevent parallel executions.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(5684630).
