### ISSUE TITLE
[Configuration - Developer tab] Error appears when trying to erase the values from the fields in order to replace it

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#10922]
### Bug Description

When trying to update the values from various fields from the 'Configuration' directory - 'Developer' tab, an error appears.

### Steps to Reproduce

1. Log in with an Admin+NatUser (make sure the Developer mode is enabled on the server from the server properties file);
2. Erase the value from either one of the following fields - 'Number of generated cases', 'Number of generated contacts', 'Number of generated events', 'Min participants per event' (any input field).

### Actual Behavior

An error message appears:
![image](https://user-images.githubusercontent.com/96909231/202150219-a6072c3c-4c58-4b4b-b602-071454db7bb6.png)

### Expected Behavior

No error message should appear.

### Screenshots

GIF of the behavior:
![error dev mode](https://user-images.githubusercontent.com/96909231/202150799-c5e75c45-3a5b-496c-8466-8da341f60779.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0; 1.76.5.
* Android version/Browser: Chrome
* Server URL: local machine; test1402.sormas.netzlink.com
* User Role: Admin+NatUser

### Additional Information

Logs from the local machine:
[logs error developer mode.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10021102/logs.error.developer.mode.txt)

**Comment by StefanKock** [comment]
Reduced severity because it was only an inconvenience in a development feature that can easily be avoided.
