### ISSUE TITLE
adding new vaccines and vaccinemanufacturer to SORMAS [1]

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#10920]
### Problem Description

adding new Covid-19 vaccines to sormas
### Proposed Change

- [x] adding to the vaccine enum

|Type|value|Caption|VaccineManufacturer|
|-|-|-|-|
|Vaccine|MRNA_BIVALENT_BA.1_BIONTECH_PFIZER|mRNA/bivalent BA.1 (BioNTech/Pfizer)|BIONTECH_PFIZER|
|Vaccine|MRNA_BIVALENT_BA.1_MODERNA|mRNA/bivalent   BA.1 (Moderna)|MODERNA|
|Vaccine|VALNEVA|inactivated (Valneva)| VALNEVA (see next task)|
|Vaccine|NUVAXOVID| protein-based, recombinant (Novavax) |NOVAVAX|
|Vaccine|MRNA_BIVALENT_BA.4_5_BIONTECH_PFIZER|mRNA/bivalent   BA.4/5 (BioNTech/Pfizer)|BIONTECH_PFIZER|
|Vaccine|MRNA_BIVALENT_BA.4_5_MODERNA|mRNA/bivalent   BA.1 (Moderna)|MODERNA|

- [x] adding to the vaccinemanufacturer enum

|Type | Value | Caption|
|-- | -- | --|
|VaccineManufacturer|VALNEVA|Valneva|

- [x] Create a dependency between the enums:
If  "inaktiviert   (Valneva)" selected in Vaccine.,Valneva automatically filled in Vaccine.Manufacturer.

**Comment by kwa20** [comment]
@cmeyerhzi @MateStrysewske While translating strings in crowdin I noticed that `Vaccine.MRNA_BIVALENT_BA_4_5_MODERNA` has the caption "mRNA/bivalent BA.1 (Moderna)" and this is indeed what is stated in the table above. I assume this should be "mRNA/bivalent BA.4/5 (Moderna)" though?

<img width="756" alt="Screen Shot 2022-11-18 at 5 08 43 PM" src="https://user-images.githubusercontent.com/70317594/202750500-85ee1fc2-6781-42dd-b70d-c810f6dd74b7.png">

**Comment by StefanKock** [comment]
> @cmeyerhzi @MateStrysewske While translating strings in crowdin I noticed that `Vaccine.MRNA_BIVALENT_BA_4_5_MODERNA` has the caption "mRNA/bivalent BA.1 (Moderna)" and this is indeed what is stated in the table above. I assume this is just a typo and should be "mRNA/bivalent BA.4/5 (Moderna)" though?

Unfortunately this was not found when implementing the ticket or before releasing 1.76.6. I documented this as #10965.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT.
