### ISSUE TITLE
S2S_Comment of share not fully readable in share box

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10930]
### Bug Description

Comment in share box is not fully readable if comment is very long. Neither in source system nor in target system.  
The comment can contain important information so there should be a way to see the whole comment.
### Steps to Reproduce

1. open a case/contact and click on 'share'
2. enter a long comment
3. click on share
4. observe the share box in source system and try to read the whole comment
5. accept the case/contact in target system
6. observe the share box in the target system and try to read the whole comment

### Expected Behavior

Comment should be readable. Should be fully displayed or displayed by howering over it for example with tooltip. 
### Screenshots

source system (if case was shared with ownership)
![image](https://user-images.githubusercontent.com/100844689/202238630-1db21678-ec63-4a84-8159-48afc64f4e28.png)

target system (if case was shared with ownership)
![image](https://user-images.githubusercontent.com/100844689/202238466-604bc496-8c3c-4780-951f-56edd470f0e9.png)

### System Details

* Device:
* SORMAS version: 1.76.5
* Android version/Browser: Edge
* Server URL: test1402 and release-de
* User Role: admin

### Additional Information

The comment was fully displayed in the past:
![image](https://user-images.githubusercontent.com/100844689/202264945-b38bfc4b-904f-415c-bd23-b7c30f59a880.png)

**Comment by JaquM-HZI** [comment]
![image](https://user-images.githubusercontent.com/78568406/202387187-c90a0a09-e892-4dba-94e0-f9f6472d0908.png)
works if there is space between letters
