### ISSUE TITLE
[S2S] share request still visible on source system after case is deleted. Case still visible on source system even though case is deleted

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10931]
### Bug Description

As defined in Issue #10625:
_With deleting that case/contact the share requests on **both** SORMAS instances should be deleted.
This has to be implemented for manual deletion and bulk deletion. For automatic deletion there is no warning message but the share requests are deleted as well._

Unfortunately the share request is still visible on the source system.
### Steps to Reproduce

1. share a case/contact with or without hand over the ownership to a target system
2. delete the case/contact while the status of the share request is still pending
3. go to the share directory of the source system
4. click on the button outgoing
5. observe if the share request you sent is still there -> share request should not be visible
6. click on the eye button and open case7contact -> case/contact opens and is visible although case/contact is deleted

### Expected Behavior

Share request should not be visible in source system after the case/contact is deleted. 
### Screenshots

![Hotfix 1 76 6](https://user-images.githubusercontent.com/100844689/202248799-2d30f9a5-54f5-4f1d-810b-6febea63bf2d.gif)

### System Details

* Device:
* SORMAS version: 1.76.5
* Android version/Browser: Edge
* Server URL: 1402 to release-de
* User Role: admin

**Comment by leventegal-she** [comment]
@SahaLinaPrueger 
Should the manually revoked(when the user clicks on the revoke button) share requests also be deleted on the target system?

**Comment by carina29** [comment]
The fix was merged to hotfix-1.76.6 branch.

**Comment by leventegal-she** [comment]
Reopen because the last commit does not handle correctly the permanent deletion issue

**Comment by dragosb-vg** [comment]
Validated during a peer-testing session with @leventegal-she's on his local system on **hotfix-1.76.6**

The after deleting the shared case/contact/event is no longer displayed in the source system 'Share Directory -> Outgoing tab'.
