### ISSUE TITLE
Add a bulk edit mode to all directories [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1094]

**Comment by MartinWahnschaffeSymeda** [comment]
In general lazy loading and entry selection is just not a good combination.

Idea:

- [ ] add "... all" bulk operations to grids
- [ ] try: when user has checked a grid entry the grid should no longer scroll

**Comment by MateStrysewskeSym** [comment]
- [ ] Add a warning when trying to enter bulk edit mode with > 1000 cases in the list
