### ISSUE TITLE
Incorrect translation for `Vaccine.MRNA_BIVALENT_BA_4_5_MODERNA` results in indistinguishable vaccine entries

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#10965]
### Bug Description

Translation in enum.properties introduced by #10920 is incorrect that now results in an apperently duplicate vaccine but with different meaning in the data:

```bash
# correct translation
Vaccine.MRNA_BIVALENT_BA_1_MODERNA=mRNA/bivalent BA.1 (Moderna)

# incorrect translation
Vaccine.MRNA_BIVALENT_BA_4_5_MODERNA=mRNA/bivalent BA.1 (Moderna)
```

It's in the default translation and at lease in de translation.

### Steps to Reproduce

1.
2.

### Expected Behavior

Change translation properties to:
```bash
Vaccine.MRNA_BIVALENT_BA_4_5_MODERNA=mRNA/bivalent BA.4/5 (Moderna)
```

### System Details

* SORMAS version: 1.76.6 (new in that version).

### Additional Information

- Even it's "only" an inconsistent translation, bringing this to production messes up data consistency.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT.
