### ISSUE TITLE
[Vaccinations] Irrelevant vaccinations are no longer greyed out

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10974]
### Bug Description
When adding an irrelevant Vaccination for a Case / Contact /Event Participant, it still has the info icon that on hover, informs the user that the Vaccination is not relevant, but it is no longer greyed out.

### Steps to Reproduce

1. Make sure that the Reduced Immunization Module is enabled;
2. Create a Contact with the 'Date of Last Contact' set to 01.10.2022 and 'Report Date' set to 02.10.2022;
3. Add a Vaccination with the 'Report Date' and 'Vaccination Date' set to 20.11.2022
4. Inspect the Vaccination Card;

### Expected Behavior
The Vaccination should be greyed-out;

### Actual Behavior
The Vaccination is no longer greyed-out;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/203067252-8d3a21ec-21dd-4b7e-9428-e06643fbfd4e.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0 SNAPSHOT (a0fabc2)
* Android version/Browser:
* Server URL: local environment
* User Role: admin + national user

### Additional Information
The ticket was created as a 'Finding' type so that it could be investigated, because the bug is reproducible only on the current SORMAS version, so it was introduced this sprint. It is not reproducible on the release instance (Sormas 1.76.6).
The bug is not reproducible on the release environments.

**Comment by StefanKock** [comment]
I cannot confirm but I expect that this finding is related to #8463 because `VaccinationListEntry` contains `setEnabled(vaccination.isRelevant());`.

**Comment by sergiupacurariu** [comment]
fixed with changes required by QA for ticket #8463. Here is the PR: https://github.com/hzi-braunschweig/SORMAS-Project/pull/10984
