### ISSUE TITLE
[S2S] Unable to share cases between test environments

### ISSUE THREAD

**Issue by dragosb-vg** [hzi-braunschweig/SORMAS-Project#10989]
### Bug Description

Error message appears when attempting to share cases/contacts/events or when attempting to accept/revoke/reject sharing requests.
Issue is occurring no matter the shared case/contact type and configuration and no matter the sender/receiver servers (de1, de2, de3)
Issue **cannot** be replicated on release environments(1402-test, release-de) on Sormas Version 1.76.7
### Steps to Reproduce

1. Create a new case/contact/event.
2. Click the "Share" button (right pane) 
3. On the open dialog, select an organization.
4. (optional) Select/deselect checkboxes.
5. Add a comment.
6. Push "Share' button.
7. Observe behavior

### Expected Behavior

Pop-up closes and confirmation message appears.
### Screenshots

![share2](https://user-images.githubusercontent.com/111864167/203316362-af204a95-4c2c-4eec-bf86-528ad011eee6.gif)

### System Details

* Device: PC
* SORMAS version: 1.77.0-SNAPSHOT ([3938969](https://github.com/hzi-braunschweig/SORMAS-Project/commits/393896977092577e637d479abec8327ca7dc0c33))
* Android version/Browser: Chrome
* Server URL: https://test-de1.sormas.netzlink.com/
* User Role: admin

### Additional Information

Logs:
[S2S-Error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10067453/S2S-Error.txt)

**Comment by StefanKock** [comment]
Retry this after commit https://github.com/hzi-braunschweig/SORMAS-Project/commit/964827ff3f01d0c36a6413dc3194c274e200be89 is deployed on TEST stage.

**Comment by dragosb-vg** [comment]
The issue is no longer reproducing as of 1.77.0-SNAPSHOT ([47f832f](https://github.com/hzi-braunschweig/SORMAS-Project/commits/47f832f1150ddf346e265adb24a12ba9f99b1e57)).
- checked cases/contacts/events sharing between **de1**-**de3**
- checked multiple accept/revoke/reject cycles.

**Comment by StefanKock** [comment]
Duplicate to #9965
