### ISSUE TITLE
[User Rights] On hovering on the user rights, more details are no longer displayed

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#10986]
### Bug Description
When hovering over the user rights of a User Role, more details about the specific User Rights are no longer displayed.

### Steps to Reproduce

1. Open the Users Directory, select the User Roles tab and open a User Role;
2. Hover on one of the user rights;

### Expected Behavior
On hovering on the user rights, more details should be shown for the specific user right;

### Actual Behavior
On hovering on the user rights, nothing happens;

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0 SNAPSHOT (b64fb46)
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: admin + national user

### Additional Information
The ticket was created as a 'Finding' type so that it could be investigated, because the issue is reproducible only on the current SORMAS version (1.77.0 SNAPSHOT)(b64fb46), so it was introduced this sprint. It is not reproducible on the release instance (Sormas 1.76.7).
The bug is not reproducible on the release environments.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(6fd32e2).
