### ISSUE TITLE
Missing phone and e-mail validation for 'Source of Information' details on Event page[Mobile app]

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#10991]
### Bug Description

Input validation is fixed for the web version but not for the mobile app. The issue description can be found at #7877.

#### Steps to Reproduce

1.
2.

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by zohaibhassan122** [comment]
FYI @roxanamlendea @bernardsilenou  @MartinWahnschaffe @MateStrysewske

**Comment by StefanKock** [comment]
@zohaibhassan122 please keep the description template as a whole and give more information in the future (see [Contributing Guidelines](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/CONTRIBUTING.md)).

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the latest version from the development branch 1.78.0-SNAPSHOT.
