### ISSUE TITLE
Facility dropdowns can be edited by National Clinican

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#10998]
### Bug Description

The Facility Categorie dropdowns can be edited by National Clinican. 
According to the ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/10675, all facility fields should not be editable. 

![image](https://user-images.githubusercontent.com/101708230/203547334-23887df9-ef19-4d0b-a066-cd10bddc6fdc.png)

### Steps to Reproduce

1. As National Clinician edit an Immunization / Person / Case
2. Try to change Facility Category + Facility Type + Facility

### Expected Behavior

Facility Category and Facility Type should be Read-only and Facility should have the label confidential
Observation: When creating an Immunization with the National Clinician, he should be able to choose Facility Category + Type + Facility
The Facility drop downs in the other entities should also be read only.  

### System Details

* Device: Laptop
* SORMAS version:  1.76.7
* Android version/Browser:  Chrom 
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: National Clinician

**Comment by StefanKock** [comment]
@carina29 can this ticket be closed as duplicate to #10775?

**Comment by carina29** [comment]
Yes, sure.

**Comment by carina29** [comment]
Duplicate ticket of #10775.
