### ISSUE TITLE
[S2S] Maintain sync in person merge

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#10992]
### Problem Description

If a person (or an entity of a person) was shared via S2S, then _only the person that was shared via S2S_ can be the leading person during the person merge in the source system _and_ in the target system. Otherwise the sync will break.
### Proposed Change

![Frame 100](https://user-images.githubusercontent.com/100844689/203498743-eaf1920f-4af1-4afc-aa03-52e178c0a8e1.png)

### Implementation Details

Behavior after the person merge: 
- The person is always editable, even if one of the entities (case/contact) taken over by the person merge is only for viewing.
-  The entity remains "view only" after the merge (if the entity was "view only" before).
- Because the person is always editable, the person sync breaks as explained in #10544, but the case/contact sync does not.

### Additional Information

refers to #5606

**Comment by markusmann-vg** [comment]
@SahaLinaPrueger 
How do we want to inform the user, that the received person must be the leading person?
What do we do, when both persons are coming from a share? Assumption: no possibility to merge, hide the buttons, inform the user somehow that those persons cannot be shared.

**Comment by SahaLinaPrueger** [comment]
> How do we want to inform the user, that the received person must be the leading person?

Please note: it's not only about the _received_ person in the target system but also about the _sent_ person in source system. On both sides only the person can be the leading person, who has the shared entity.
