### ISSUE TITLE
Two step `getIndexList` for other entities [5]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#11014]
### Problem Description

getIndexList uses sort distinct on all attributes that are fetched for directory DTOs, which takes more time with more rows to process. The problem gets bigger with more left joins that multiply rows.

### Proposed Change

Improve performance of `getIndexList` methods (by avoiding extensive sorting on all data columns) that fetch data for the following directories that tend to grow heavily over time:

1. `Task`
2. `Sample`
3. `ExternalMessage`
4. `ShareRequest`
5. `Action`
6. `EventGroup`

### Acceptance Criteria

- [x] Performance analysis before/after is documented (with info about given dataset size).
- [x] At least one unit test exists for each getIndexList method.

### Implementation Details

1. Apply this pattern (already given by #11013):
```java
getIndexList {

  // 1. Fetch ids of entries in the window given by limit & offset
  getIndexListIds {
    sortBy
  }

  // 2. Fetch data for the fetched ids
  executeBatched {
    sortBy
  }

  // 3. Post-processing: calculated values, references, collections
  // 4. Pseudonymization
  // 5. Log execution time (DEBUG)
}
```

### Additional Information

- Follow up to #11013
- No other entities are currently considered to where this refactoring is needed.

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using SORMAS version 1.80.0-SNAPSHOT(3391cf9).
