### ISSUE TITLE
[S2S] Documents not deletable after share

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11018]
### Bug Description

Documents not deletable after share.
### Steps to Reproduce

1. create a case/contact and attach documents
2. share a case/contact with hand over the ownership
3. accept in target system
4. observe in source system if document is deletable

### Expected Behavior

document should be deletable
### Screenshots

1.77:
![image](https://user-images.githubusercontent.com/100844689/203825402-051fa185-eb56-4afe-afc6-1dce8f178c83.png)

1.76:
![image](https://user-images.githubusercontent.com/100844689/203825667-8d0fd8ed-1bab-43f5-a680-d04bc04d4c6d.png)

### System Details

* Device:
* SORMAS version: 1.77.0-SNAPSHOT (8d282da)
* Android version/Browser: Edge
* Server URL: test-de1
* User Role: admin

### Additional Information

refers to/ defined in: #9804 
documents rights are given: 
![image](https://user-images.githubusercontent.com/100844689/203825569-3c6dfd23-62e6-4e5b-bee9-8c1e8b200207.png)

**Comment by StefanKock** [comment]
Probably linked to #8463

**Comment by sergiupacurariu** [comment]
this finding was fixed on this branch: https://github.com/hzi-braunschweig/SORMAS-Project/pull/11027
