### ISSUE TITLE
Merged persons should not be listed as event participants in the same event twice

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11016]
### Problem Description

Currently, due to the new person merge functionality introduced with #5606 persons that are event participants in the same event can be merged, which results in the same person being listed twice as event participant in the same event.

As the behavior is when creating event participants for an event, the same person is not permitted to be listed as event participant twice in the same event. So it should be clarified what should happen for persons that were merged as duplicates, where the leading person is now an event participant in the same event twice.

This separate ticket was logged as the behavior desired was not specified in #5606 and since the merge of event participants is not currently implemented as it is for cases or contacts.

### Proposed Change

Two possible proposed changes:

1. Would it be desired that only the information form the event participant of the leading person to remain? And therefore there would be only one entry as event participant for that person after the merge.

2. Would it be desired for the event participants entities to be merged as well when the person merge occurs, but only if the 2 persons are listed as event participants within the same event? Thus leading again to only one entry as event participant for the leading person after the merge.

### Additional Information

Steps to reproduce the scenario described:
1. Open an event and create an event participant;
3. Create a new event participant within the same event, with the exact same details as the one from step 1;
4. In the 'Pick or create person' pop-up select 'Create new person';
5. From the 'Persons' directory, merge the 2 persons associated with the event participants created above.
-> the same person is listed twice as event participant within the same event.

GIF of the behavior:
![Event participant - persons merge](https://user-images.githubusercontent.com/96909231/203814864-2960701f-c373-47fe-a289-e21ef6b3dd6e.gif)

**Comment by adinaflorea9** [comment]
@MateStrysewske could you please take a look over the behavior and the 2 proposed change possibilities listed in the ticket?

**Comment by MateStrysewske** [comment]
@adinaflorea9 That's a pretty tricky one because event participants can have some details (e.g. a jurisdiction) that could lead to unexpected behaviour, e.g. users losing access to the event participant, the involvement description getting lost, etc. I think we have to take this into a refinement session and talk about it.

**Comment by adinaflorea9** [comment]
I am discarding the current ticket as this will be covered in #11360
