### ISSUE TITLE
Persons with incomplete home addresses from different jurisdictions can not be merged 

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11017]
### Problem Description

When using the person merge #5606 to try and merge persons that are from different jurisdictions (in their home address section) a warning appears if one of the persons has an incomplete home address.

A separate ticket has been created as in #5606 it was specified that information from the fields that are not filled in for the leading person should be filled with information from the discarded person. But it was not specified what should be done when the information is conflicting.

The scenario proposed considers 2 persons that are duplicates, one entry could be from a while ago when the person had an incomplete home address from jurisdiction 1, and the second entry for that person in their latest one, and has a complete home address from jurisdiction 2.

Steps:
1. Create a person that has the following home address:
![image](https://user-images.githubusercontent.com/96909231/203816314-555f23bb-0934-4b80-bd98-45c3613c6ed5.png)

2. Create a second person that would be considered a duplicate of the one from step1, but use the following home address:
![image](https://user-images.githubusercontent.com/96909231/203816525-11b2b89a-25b0-4865-bf8c-189ba4820a2d.png)

3. Try to merge the 2 persons and have the person from step 1 as the leading person;
-> the merge is not possible, as the information from the community field from the discarded person can not be migrated into the leading person.
![image](https://user-images.githubusercontent.com/96909231/203816920-3db5afed-22c3-49ef-80f9-4ccdc1399597.png)

### Proposed Change

Two options for the proposed change:

1. Would it be desired for the whole home address to be updated for the leading person when the home address information is from different jurisdictions (different districts, and/or different communities)?

2. Would it be desired for the whole home address to be transferred into the leading person in the form of a 'New entry' in the 'Addresses' section of the leading person?

**Comment by MateStrysewske** [comment]
I consider this a bug because it seems like there's a problem in our implementation, specifically the implementation of location merging. We definitely can't use the logic "if it's empty in the leading entity, copy it over" for jurisdictions here because that will inevitably lead to issues like the one reported here.

We should refine this, but my suggestion would be to go with solution 2, i.e. if the home addresses don't match, copy the home address of the discarded person over to the other addresses of the leading person. Needs to be discussed with HZI though.

**Comment by adinaflorea9** [comment]
@JaquM-HZI and @SahaLinaPrueger does the proposed solution number 2 seem suitable for you?

**Comment by SahaLinaPrueger** [comment]
Nr. 2 is suitable for me. I am just not sure if it would be better to take _home_ as address type or  _other address_, and the description would be _previous home address_
![image](https://user-images.githubusercontent.com/100844689/206219591-ecf2a1a2-6567-4c6a-bdb8-fa0bbde62406.png)
![image](https://user-images.githubusercontent.com/100844689/206216401-f5e8943d-910e-4b7d-8db5-aa1d1f4d859d.png)

_Other address_ makes more sense, but we cannot translate _previous home address_, to other languages because it is a free-text field, right? @JaquM-HZI

**Comment by SahaLinaPrueger** [comment]
@adinaflorea9 We discussed this: We go with solution Nr. 2.
Address Type should be _other address_ and _address name / description_ should be: _adopted from discarded person_
Thank you for suggest solution Nr. 2!

**Comment by adinaflorea9** [comment]
As discussed with @sergiupacurariu I am reopening the ticket due to the following scenarios:

I:

1. Create 2 persons with the same home address (same region, district, and/or community) but different 'Facility category' and 'Facility type' - no new entry in 'Addresses' is created after merge 

2. Create 2 persons with the same home address (same region, district, and/or community), same 'Facility category' but different 'Facility type' - no new entry in 'Addresses' is created 

3. Create 2 persons with the same home address (same region, district, and/or community), same 'Facility category', same 'Facility type', but different 'Facility' - no new entry in 'Addresses' is created 

4. Create 2 persons with the same home address (same region, district, and/or community), same 'Facility category', same 'Facility type', but one person has an actual 'Facility' selected, and the other has 'Other Facility' and the field 'Facility name and description' filled in - no new entry in 'Addresses' is created

5. Create 2 persons with the same home address (same region, district, and/or community), same 'Facility category', same 'Facility type', but 'Other Facility' is selected and the field 'Facility name and description' filled with two different values - no new entry in 'Addresses' is created 


II:
1. 
Person 1 - has the home address in region 1, district 1, community 1 + a facility that belongs to community 1
Person 2 - has the home address in region 1, district 1 + a facility that belongs to district 1
2. Keep person 2 (discard person 1)
-> on person 2 the facility is now set as 'inactive' and the community from person 1 'migrated' into person 2

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(2cbcbbe).
