### ISSUE TITLE
Two step `getIndexList` for CoreAdos [8]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#11013]
### Problem Description

`getIndexList` uses `sort distinct` on all attributes that are fetched for directory DTOs, which takes more time with more rows to process. The problem gets bigger with more left joins that multiply rows.

### Proposed Change

Improve performance of `getIndexList` methods (by avoiding extensive sorting on all data columns) that fetch data for the following directories of CoreAdos that tend to grow heavily over time:
1. `Case`
2. `Contact`
3. `Event`
4. `EventParticipant`
5. `TravelEntry`
6. `Immunization`

Apply the developed pattern for the following CoreAdos to first fetch ids, and then fetch data afterwards.

### Acceptance Criteria

- [ ] Performance analysis before/after is documented (with info about given dataset size).
- [ ] At least one unit test exists at least for each `getIndexList` method.

### Implementation Details

1. Apply this pattern (already used in `PersonFacadeEjb`):
```java
getIndexList {

  // 1. Fetch ids of entries in the window given by limit & offset
  getIndexListIds {
    sortBy
  }

  // 2. Fetch data for the fetched ids
  executeBatched {
    sortBy
  }

  // 3. Post-processing: calculated values, references, collections
  // 4. Pseudonymization
  // 5. Log execution time (DEBUG)
}
```

2. Extract generic pattern to fetch Ids, sortBy or something else that is repeated code (if possible).

### Additional Information

- Follow-up for #8938.
- Other CoreAdos `Campaign` and `DirectoryImmunization` are not considered to be needed to rework.

**Comment by syntakker** [comment]
**Performance analysis for PR #11182:**

Data:
- 1,243,581 persons
- 85,675 cases
- 114,782 contacts
- 11,846 events
- 534 event participants (all in one event)
- 18,239 travel entries
- 2,600,890 immunizations

**Runtime reduction for individual getIndexList methods:**
Case:
1383 ms -> 1047 ms

Contact:
2152 ms -> 1042 ms

Event:
287 ms -> 271 ms

Event participant:
315 ms -> 108 ms

Travel entry:
662 ms -> 131 ms

Immunization:
9613 ms -> 2627 ms

**Measurements**
Perfomancae before refactoring:
![image](https://user-images.githubusercontent.com/5616564/207820963-91d0ac63-4222-4586-b7e8-a2f747a1d5a6.png)

Performance with two-step-getIndexList:
![image](https://user-images.githubusercontent.com/5616564/207821289-399357bc-2cf4-4a61-8024-3bb6600ad63d.png)
