### ISSUE TITLE
Wrong version of xerces fails redeployment of sormas modules.

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#11010]
### Problem Description

Redeploying the application results in failure bacause:
`Caused by: org.apache.xerces.impl.dv.DVFactoryException: DTD factory class org.apache.xerces.impl.dv.dtd.DTDDVFactoryImpl does not extend from DTDDVFactory.`
The issue seems to be a dependency of org.apache.tika.

### Proposed Change

Forcing a recent version of xerces dependency seems to fix the issue, similar to the solution proposed here:
https://stackoverflow.com/questions/5833559/maven-org-apache-xerces-impl-dv-dvfactoryexception

**Comment by StefanKock** [comment]
Related to #9965

**Comment by StefanKock** [comment]
I retested on commit c2e484558f722025b1e7c557505080cd184e382c: 
- Deployment works
- Document validation works

Roundtrip for documents tested:

Downloaded sample template and uploaded it:
![grafik](https://user-images.githubusercontent.com/24678567/204750389-58f77d6f-6afc-467e-ab11-3e4acb4f953f.png)

2. Create Quarantine Order for Case with saving document:
![grafik](https://user-images.githubusercontent.com/24678567/204750236-b163fe7d-230b-4d61-bbd7-2f2ee84bbc98.png)
