### ISSUE TITLE
Fix description of PERFORM_BULK_OPERATIONS_CASE_SAMPLES user right

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11045]
### Bug Description

The PERFORM_BULK_OPERATIONS_CASE_SAMPLES user right is currently used to decide whether users have access to bulk operations on both the sample and case directory. The description, however, does not properly reflect this.

### Steps to Reproduce

1.
2.

### Expected Behavior

Change the description accordingly.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (f408f51).
Note: The translations from Crowdin have not been updated yet.

**Comment by KristinaBorch** [comment]
@roxanamlendea The hover still contains the description case samples instead of cases and samples. Same problem in the export user roles for the column description. Should I open a new bug report, as I guess, it is just something small?
