### ISSUE TITLE
Updating the function to merge a new case to an existing person

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1104]
When a user creates a case that has been created in the system before, SORMAS show a pup-up message to ask the user to either create a new person or associate the new case to an existing person. Since a case can be created my many users, e.g. lab , national, SO, this leads to false duplicate cases. We should program the tool such that if the person information, demographic, disease, calendar time is the same, then the tool should merger the **case and the person**. If the disease is different  and the person is the same, then only the person information will be merged.

**Comment by MateStrysewskeSym** [comment]
This is already covered in issues #757 and #1080
