### ISSUE TITLE
Export filled case investigation form

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1105]
Creation of CIFs on the SORMAS platform using data from cases entered on the platform to populate the CIF, which can therefore be downloaded both on the mobile and web platforms. The created CIF would be the national CIF template.

**Comment by MateStrysewskeSym** [comment]
Idea: Split this into two; first print the case (all fields) the way they are presented in SORMAS right now, later talk about filling the CIF with the case information

**Comment by MateStrysewske** [comment]
Continued in #2906
