### ISSUE TITLE
Cannot filter immunization by ID on Immunization directory page

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11068]
### Problem Description
There is no possibility to filter Immunization by ID in Immunization directory page. After typing an ID of immunization and applying filter the spinner is loading some time (around 50 seconds) and then filtering is stopped without result.

#### Steps to Reproduce
1. Login as Admin User
2. Go to Immunizations
3. Search for an ID immunization
4. Click on APPLY FILTERS button

#### Screenshots
![image](https://user-images.githubusercontent.com/105210214/205016430-4d24f6e9-8c98-4a35-b2c5-6c35bd4a990d.png)
![image](https://user-images.githubusercontent.com/105210214/205020663-8e6dc322-c792-4066-906e-ab63293bfb76.png)

#### System Details
* Device: Windows 10
* SORMAS version: 1.77.0-SNAPSHOT (d20e859)
* Android version/Browser: Chrome
* Server URL: [https://test-auto.sormas.netzlink.com ](url)
* User Role: Admin

### Expected Behavior
Search result (immunization with the searched ID) has been received.

**Comment by StefanKock** [comment]
I verified two things:
1. Immunizations Directory is slow on https://test-auto.sormas.netzlink.com, probably a lot of data present. The same view on https://test.sormas.netzlink.com is fast.
2. Test search for Person.firstName and Person Id (UUID) works, but not for Immunization Id (UUID)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(8bfce2d).
