### ISSUE TITLE
Automatic deletion seems to run into a loop and to only delete cases

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11074]
### Problem Description

When triggering the automatic deletion on the local machine via the button to trigger automatic deletion from the 'Developer' tab in the Configurations directory, or regularly via the CronService job that runs, it seems that only the cases that fit within the timeframe specified in the 'deleteconfiguration' table are deleted, and the contatcs, events, event participants, travel entries and immunizations remain.

Logs from my local machine:
[logs automatic deletion AD.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10132736/logs.automatic.deletion.AD.txt)

Logs from @roxanamlendea 's local machine:
[logs for automatic deletion.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10132740/logs.for.automatic.deletion.txt)

#### Steps to Reproduce

1. In the 'deleteconfiguration' table set the deletion period to 7 days and the deletion reference to 'CREATION' as below:
![image](https://user-images.githubusercontent.com/96909231/205066974-48b94dc0-b1b4-4756-9145-186a55d8980a.png)

2. Trigger automatic deletion from wither the button in the 'Developer' tab or via the scheduled CronService job;
3. Observe the logs and the entries in the UI/or DB.

#### System Details

* Device: Windows 10
* SORMAS version: 1.77.0-SNAPSHOT(8457345)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Expected Behavior

Automatic deletion should run for all entities for which it is configured in the 'deleteconfiguration' table and that fit within the time frame specified.

**Comment by StefanKock** [comment]
> Automatic deletion should run for all entities for which it is configured in the 'deleteconfiguration' table and that fit within the time frame specified.

I don't get the problem. The first log file contains which entities are investigated to be deleted (resulting to 0 fore each). Is there data that would be deletable?

```bash
  D151700.009|     > executeAutomaticDeletion(): Detected deletable entities of type CASE: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:85)
  D151700.011|     > executeAutomaticDeletion(): Detected deletable entities of type CONTACT: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:85)
  D151700.016|     > executeAutomaticDeletion(): Detected deletable entities of type EVENT_PARTICIPANT: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:85)
  D151700.018|     > executeAutomaticDeletion(): Detected deletable entities of type IMMUNIZATION: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:85)
  D151700.021|     > executeAutomaticDeletion(): Detected deletable entities of type TRAVEL_ENTRY: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:85)

  D151700.022|     > executeAutomaticDeletion(): Detected non referenced symptoms: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:102)
  D151700.025|     > executeAutomaticDeletion(): Detected non referenced persons: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:107)
  D151700.026|     > executeAutomaticDeletion(): Detected non referenced sormasToSormasShareRequests: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:112)
  D151700.028|     > executeAutomaticDeletion(): Detected orphan ShareRequestInfo: n=0 (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:121)
  D151700.028|     > executeAutomaticDeletion() finished. 0s (de.symeda.sormas.backend.deletionconfiguration.CoreEntityDeletionService.java:96)
```

**Comment by adinaflorea9** [comment]
@StefanKock Yes, there were supposed to be basically all of the cases, contacts, events and event participants from my DB that had the creation date set to 2021 (and the deletion period was set to delete everything older than 7 days). 

I am noticing now that the deletion job does seem to run, but it takes a whole lot more time than it used to do - and in the logs there are those mentions of:
[2022-12-01T15:08:55.212+0200] [Payara 5.2021.10] [INFO] [] [] [tid: _ThreadID=257 _ThreadName=__ejb-thread-pool2] [timeMillis: 1669900135212] [levelValue: 800] [[
  D150855.211|     > cleared heap usage (net.sf.ehcache.store.disk.Segment.java:709)
]]

[2022-12-01T15:08:55.213+0200] [Payara 5.2021.10] [INFO] [] [] [tid: _ThreadID=257 _ThreadName=__ejb-thread-pool2] [timeMillis: 1669900135213] [levelValue: 800] [[
  D150855.212|     > cleared disk usage (net.sf.ehcache.store.disk.Segment.java:711)
]]


That seemed to go on and on so they gave the impression of a loop. I can not say for sure right now how long the deletion job took to run and delete the entities from my DB (I checked now and they are deleted), but the time frame is more than it used to be. As I let my local machine just run that deletion job and nothing else since I logged this ticket up until right now.

**Comment by StefanKock** [comment]
The logging is changed in code (see latest changes here: ae661552f3103d3050f578734f700b85f376f718), but needs to be adapted on DEV instances manually in `logback.xml`.

I get the impression that ehcache is clearing itself often. Since it's debug level, I'm not worried.
```java
// net.sf.ehcache.store.disk.Segment.clear()
            onHeapPoolAccessor.clear();
            LOG.debug("cleared heap usage");
            onDiskPoolAccessor.clear();
            LOG.debug("cleared disk usage");
```

**Comment by StefanKock** [comment]
So: No loop (except the intended foreach to delete data) and data got deleted. 
The second log file seems to only contain exceptions because a shutdown/undeployment was started when there were still processes active. It might be that the system behaves slower if it's running on a low RAM limit and the L2 cache now reaches that limit.

**Comment by adinaflorea9** [comment]
Alright! thank you for looking into this and explaining it to me, I will therefore, close this ticket as discarded, as the deletion does take place in the end.
