### ISSUE TITLE
NPE exception is thrown which blocks the Survnet import

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#11098]
### Bug Description

NPE exception is thrown which blocks the Survnet import and the compatibility check between Survnet 14.4 and Sormas 1.77.1
The import on Survnet side is failing with this Runtime Exception:
![image](https://user-images.githubusercontent.com/47103965/205660217-e4cd962e-093a-45f4-8dba-f270a7445da7.png)

On Sormas side is visible that the NPE is thrown from CaseFacadeEjb fillOrBuildEntity method, the following line:
target.getHospitalization().setUuid(source.getHospitalization().getUuid());

[NPE_Logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10154977/NPE_Logs.txt)

- [x] source.getHospitalization() should be checked if is different than null, if yes the Uuid can be set.
- [x] do the null check for source.getEpiData() ( set Uuid only when  source.getEpiData() is not null)
- [x] do the null check for and source.getSymptoms  ( set Uuid only when  source.getSymptoms() is not null).

#### Steps to Reproduce

1.
2.

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AndyBakcsy-she** [comment]
Validated ticket on a peer testing session with Carina
