### ISSUE TITLE
Users cannot be created

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#11105]
### Bug Description

When trying to create a user, an error occurs.

#### Steps to Reproduce

1. Log in as an administrator that has the roles Admin and National User
2. Go to users and create a new user
3. Choose the user role combination Admin and National User
4. Enter compulsory fields and save

#### Screenshots

<img width="444" alt="UserCreateError" src="https://user-images.githubusercontent.com/70317594/205708842-4e4fa6ab-be75-41eb-ac52-afe63242e278.PNG">

#### System Details

* Device:
* SORMAS version: 1.77.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

### Expected Behavior

It should be possible to create users

**Comment by StefanKock** [comment]
Please provide log extract

**Comment by MateStrysewske** [comment]
Closing this issue because there hasn't been a response to the request.
