### ISSUE TITLE
Reporter facility is wrongfully displayed as inactive in surveillance reports 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#11106]
### Bug Description

When Surveillance Reports are created as a result of a processed external message, the adopted reporter facility (either matched or other) are wrongfully displayed as inactive.

#### Steps to Reproduce

1. Upload and fetch an external message that either matches or doesn't match a facility in SORMAS
2. Process the message and open the case
3. Check the created surveillance report

#### Screenshots

<img width="393" alt="surveillanceReportsReporterFacility2" src="https://user-images.githubusercontent.com/70317594/205713281-4d7eaf2a-60c9-40b5-81c7-8a54ebd5bb73.PNG">
<img width="392" alt="surveillanceReportsReporterFacility" src="https://user-images.githubusercontent.com/70317594/205713286-b853e09d-e338-42d6-85e7-a97dc05e6ac8.PNG">

#### System Details

* Device:
* SORMAS version: 1.77.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

### Expected Behavior

The reporter facility should not be displayed as inactive when it is not actually archived

**Comment by SahaLinaPrueger** [comment]
Reproduced this for "matching facilities":
1. Add two specific laboraries to the facility configurations in SORMAS and give them unique external ID's
2. Upload a lab message that contains a bsnr in the Organization ressource which matches one of the external ID's ->
Fetch and process the uploaded message -> Check the pre-filling of the laboratory fields
3. Upload a lab message that contains a demisLaboratoryId in the Organization ressource which matches one of the external ID's -> Fetch and process the uploaded message -> Check the pre-filling of the laboratory fields

![facility inactive](https://user-images.githubusercontent.com/100844689/206164853-7e320085-a350-4ccf-8b12-0d5f47fd0fc0.gif)

Also reproduced this for "not matching facilities" (as described above)
Result: The adopted reporter facility (either matched or other) are wrongfully displayed as inactive.
EVEN if there is no single archived facility in the system.

From my point of view, this is a strange behavior and confuses the user. I cannot judge whether it has serious consequences at the moment, except for great confusion. But if the reports via S2S are sharable, I think this can lead to problems.

**Comment by KernB** [comment]
Although the jurisdiction for the laboratory is not a mandatory field, the laboratories are not displayed until the jurisdiction is specified. 

![Edit_report](https://user-images.githubusercontent.com/101708230/206430593-658a8d39-71e6-40ae-8952-25ace1218e00.gif)

**Comment by JonasCir** [comment]
Ok this is a pure UI issue. It makes absolutely no sense, but we currently compute the inactivity for infrastructure objects in the UI with some obscure logic which has nothing to do with the fact whether the object itself is archived or not (i.e., `AbstractEditForm.addInfrastrctureField). In my opinion, the logic should only rely on the archived field of the object and nothing else. This should do the trick. 

The previous method, the code in `SurveillanceReportForm.addFields`, and especially `InfrastructureFieldsHelper.initInfrastructureFields` definitely need a facelift. 

My suggestion is to give this ticket to the application team @markusmann-vg.

**Comment by AndyBakcsy-she** [comment]
Closing finding ticket as there won't be any work don on it
