### ISSUE TITLE
[DEMIS2SORMAS] external message icon not visible for contacts and event participants and converted cases

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11107]
### Bug Description

Processing a lab message and selecting "create a new contact" or "create a new event participant" leads in a created sample without the external message icon (book-symbol). Furthermore even if the contact/ event participant will be converted to a case, the external message icon (book-symbol) is missing.

#### Steps to Reproduce

1. process a lab message
2. create new contact -> observe if external message icon is visible
3. convert contact to a case -> observe if external message icon is visible

#### Screenshots

![no external message icon_2](https://user-images.githubusercontent.com/100844689/205724039-28e06f05-d655-4d09-b4c8-cfa471b4ef79.gif)

#### System Details

* Device:
* SORMAS version: 1.77.1
* Android version/Browser: edge
* Server URL: 1402
* User Role: admin

### Expected Behavior

external message icon is visible if sample was created by processing a lab message
### Additional Information

verified by @kwa20

**Comment by abrudanancuta** [comment]
The issue can be reproduced with the version : 1.78.0-SNAPSHOT (d77216d) on the test env.

Admin doesn't need to create a case from the Contact or Event Participant, the icon on the sample is not visible on the Sample box.

Steps to reproduce:
1. Process a lab message
2. Choose to create a Contact/Event participant
3. Click No for creating a Case
4. Look at the external message icon on the Sample

Actual behaviour: The icon is not visible

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.77.3-SNAPSHOT (6ce1a92)
