### ISSUE TITLE
Event - Send to reporting tool - The button to send an Event of type Cluster to reporting tool is missing

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11115]
### Bug Description
The button to send to reporting tool for an Event of type Cluster is missing

#### Steps to Reproduce
1. As NatUser/Admin go to Events page
2. Create a Cluster type Event
3. Check for button to send to reporting tool

### Actual Behavior
No button displayed for sending a Cluster Event to reporting tool
Also an error appears on the page

### Expected Behavior
Button to send to reporting tool should be displayed for Event type Cluster

#### Screenshots

<img width="1440" alt="Screenshot 2022-12-06 at 13 36 24" src="https://user-images.githubusercontent.com/91872179/205914415-78f0323d-c952-4b41-aa77-60981c34fd39.png">

#### System Details

* Device:
* SORMAS version: 1.77.1
* Android version/Browser:
* Server URL: test1402
* User Role: NatUser, Admin

**Comment by dinua** [comment]
it is no longer reproducible, it was fixed in https://github.com/hzi-braunschweig/SORMAS-Project/issues/11110
