### ISSUE TITLE
Event - Error message appears after creating an event

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11116]
#### Steps to Reproduce
1. As NatUser/Admin create an Event
2. Go back to the vent edit form

### Actual Behavior
An error appears when moving back from Event Participant to Event Tab

### Expected Behavior
No error should appear

#### Screenshots

<img width="1440" alt="Screenshot 2022-12-06 at 13 27 26" src="https://user-images.githubusercontent.com/91872179/205914943-e74bc973-9933-4355-9957-15ee696a62e9.png">

#### System Details

* Device:
* SORMAS version: 1.77.1
* Android version/Browser:
* Server URL: test1402
* User Role: NatUser, Admin

**Comment by carina29** [comment]
it is no longer reproducible, it was fixed in https://github.com/hzi-braunschweig/SORMAS-Project/issues/11110

**Comment by carina29** [comment]
it is no longer reproducible, it was fixed in https://github.com/hzi-braunschweig/SORMAS-Project/issues/11110
