### ISSUE TITLE
Event Actions: column sorting runs into errors

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#11113]
### Bug Description

At Events (Actions), clicking on the column headers `Event Title`, `Event Reporting User`, `Event Responsible User`, `Action Title`, `Action last modified by`, results in an error message.

#### Steps to Reproduce

1. Events > Action Directory
2. Click on any column header listed above (in description) > Error message appears.

#### Screenshots

![image](https://user-images.githubusercontent.com/65529128/205889986-370c11dd-67a8-4109-969f-1eb30fe0c5c5.png)

#### System Details

* Device: Desktop
* SORMAS version: 1.77.1, ..., 1.67.0
* Android version/Browser: Chrome
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: admin, national user

### Expected Behavior

No error messages displayed, content sorted.

### Additional Information

- Caused by #7701 (distinct added)

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.77.3-SNAPSHOT (f03187d)
