### ISSUE TITLE
Error in edit page for a event without case

### ISSUE THREAD

**Issue by dinua** [hzi-braunschweig/SORMAS-Project#11110]
### Bug Description

When an event is open that not have any case associated an error occurred in edit page
It is reproduceble only when the servnet (exernal reporting tool) is active 

#### Steps to Reproduce

1.  In Event Directory create a new Event
2.  Fill the mandatory fields and do not set any case for this event
3.  Go to the edit view for that new event and an error is showed

#### Screenshots

![image](https://user-images.githubusercontent.com/4202109/205874670-bc520c73-2de9-4905-81ef-0ef87a9de04e.png)

#### System Details

* Device: Windows 10
* SORMAS version: 1.78.0; 1.77.1 (on https://test1402.sormas.netzlink.com/)
* Android version/Browser: Browser
* Server URL: local machine and https://test1402.sormas.netzlink.com/
* User Role: National User with admin rights

### Expected Behavior

No error should be displayed

### Additional Information

This bug was introduce by #10833 in class ExternalSurveillanceShareComponent.class , line 61 . It is a NPE for "shareInfoCriteria.getCaze().getUuid()" . Case is null and this is why the error is throwed.

**Comment by adinaflorea9** [comment]
I was able to reproduce the issue only on https://test1402.sormas.netzlink.com/

**Comment by adinaflorea9** [comment]
Verified ticket in a peer to peer testing call with @dinua on his local machine from the hotfix branch 1.77.3.
