### ISSUE TITLE
Add increase/decrease percentage to Disease Burden table on Dashboard

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1112]

**Comment by faatihi** [comment]
![picturemessage_bek3cxjz nvk](https://user-images.githubusercontent.com/1176692/57630607-711bda00-758d-11e9-8067-979ef2816ad7.png)
I think of implementing it this way. Any suggestions

**Comment by MateStrysewskeSym** [comment]
@faatihi I absolutely agree with this approach.

**Comment by faatihi** [comment]
ok

**Comment by MateStrysewskeSym** [comment]
- [ ] Fix percentages

**Comment by faatihi** [comment]
May I know what the problem is with the percentages

**Comment by MateStrysewskeSym** [comment]
@faatihi They're showing the wrong numbers, e.g. when there's an increase from 1 to 4 cases, the displayed percentage is 0.3 %. We'll fix this (because we're going to make a release today or tomorrow), there's nothing you need to do about it.

**Comment by faatihi** [comment]
OK. I'll be more cautious next time.

**Comment by MateStrysewskeSym** [comment]
@faatihi No worries, happens to us as well. ;)

**Comment by MateStrysewskeSym** [comment]
@faatihi Just fyi, the only thing that was missing was to multiply the percentage with 100 to get the actual result.

**Comment by faatihi** [comment]
Noted. Thanks
