### ISSUE TITLE
[S2S] case with attached lab message cannot be accepted in target system

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11122]
### Bug Description

Sharing a case with an attached lab message with hand over the ownership results in the following error message:
![image](https://user-images.githubusercontent.com/100844689/206008945-9598fe57-ff09-4eef-ba4c-fcb6d66ea994.png)

#### Steps to Reproduce

1. process a lab message and open the case (has an attached lab message now/ book-symbol/ icon external lab message)
2. send the case with hand over the ownership to a target system
3. accept in target system

#### System Details

* Device:
* SORMAS version: 1.77.2
* Android version/Browser: edge
* Server URL: 1402 to release-sormas-x
* User Role: admin

### Expected Behavior

As specified in #8950 this should be possible
### Additional Information

could be the same problem as #10690

**Comment by StefanKock** [comment]
Logs needed and maybe the don't have the same version.

**Comment by abrudanancuta** [comment]
Verified in peer testing with @leventegal-she on his local env
