### ISSUE TITLE
[S2S] warning message according to pending share request if case/contact is deleted is incomplete 

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11120]
### Bug Description

As specified in #10625 the warning message should also appear if deletion happens via bulk mode. 
This happend in the 1.76 (just the translation was missing) but not in 1.77.

#### Steps to Reproduce

1. create a case
2. send the case via S2S (do not accept in target system)
3. go to the case directory and delete the case via bulk mode
4. same warning message should appear as if you delete the case manually (_There is a pending share request,..._)
#### Screenshots

message in 1.76 (manual and bulk deletion):
![image](https://user-images.githubusercontent.com/100844689/205997845-7c12d303-345b-4bb6-83ef-5b4e81d129ef.png)

message in 1.77 (manual deletion):
![image](https://user-images.githubusercontent.com/100844689/205998012-c0b3827c-989e-4ce7-ab73-5caef41c77ca.png)

message in 1.77 (deletion via bulk mode):
![image](https://user-images.githubusercontent.com/100844689/205998170-43a330ed-1e83-4afe-ab63-dd756085df74.png)

GIF 1.77
![deletion case pending share request](https://user-images.githubusercontent.com/100844689/205998863-cf340187-e8d1-4afe-a6e5-ec8fed258054.gif)
#### System Details

* Device:
* SORMAS version: 1.77.2
* Android version/Browser: edge
* Server URL: release-de
* User Role: admin

### Expected Behavior

same warning message if deletion is via bulk mode as if deletion is manually

**Comment by AndyBakcsy-she** [comment]
Closing ticket as verified on the latest Sormas version 1.79.0-snapshot (eaef5e2)
