### ISSUE TITLE
[S2S] After sharing an entity, the share card is updated only after refresh

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#11144]
### Problem Description

When sharing an entity, the share card is not updated instantly. It still says that the entity is not shared. The card is updated only after the user refreshes the page.

#### Steps to Reproduce

1. Open a Case in Sormas A and share the Case with Sormas B;
2. Inspect the Share card;

#### Screenshots
![image](https://user-images.githubusercontent.com/89522688/206568375-1fe9b6cd-c4aa-4f9f-80aa-9d12a0d72459.png)

#### System Details

* Device: Windows 10
* SORMAS version: 1.77.3
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and release-de.sormas.netzlink.com
* User Role: admin + national user

### Expected Behavior
The share card should show that the entity was shared with another instance; this is only shown after the user refreshes the page

### Actual Behavior
The share card is not updated instantly. It still says that the entity is not shared. The card is updated only after the user refreshes the page.

**Comment by abrudanancuta** [comment]
There is a work in progress ticket in the current sprint which will be release in the version 1.78.0 https://github.com/hzi-braunschweig/SORMAS-Project/issues/8471
