### ISSUE TITLE
Web app load testing [5+?]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1116]
We need load testing to make sure the performance of the SORMAS web app stays stable with new releases.

Introduction:

* https://vaadin.com/docs/v8/framework/articles/LoadTestingWithGatling.html
* https://gatling.io/docs/current/quickstart/

**Comment by MateStrysewskeSym** [comment]
Generate simulations for the following scenarios:
- [ ] For every directory: open directory and scroll to bottom (User role: National User)
- [ ] Generate a detailed case export (User role: National User)
- [ ] Request all cases
- [ ] Request all persons
- [ ] Request all regions/districts/communities/facilities (to simulate app initialization)
- [ ] Login and open the Dashboard (National User)
- [ ] Generate statistics (without filters, with groupings - all three visualization types)

For every scenario, generate simulations with 1 user, 50 users and 500 users.
