### ISSUE TITLE
[S2S] Share box 'Share with' text field is duplicated after revoking a share request

### ISSUE THREAD

**Issue by dragosb-vg** [hzi-braunschweig/SORMAS-Project#11161]
### Bug Description

After revoking a Share request from the entity share box on the source system, the text line "Shared with" appears duplicated.

#### Steps to Reproduce

1. Create a new case/contact
2. Share the case with another instance (any share type)
3. Refresh page (to see the Revoke button)
4. Push the revoke button.
6. (DO NOT REFRESH) Check the details on the 'Share box. (After refresh, the share box  is displayed correctly.)

#### Screenshots

![doubleText](https://user-images.githubusercontent.com/111864167/207055262-be92da20-0d8c-4796-a86c-03a68efebf58.gif)

#### System Details

* Device: Laptop
* SORMAS version:1.77.3
* Android version/Browser: Chrome
* Server URL: release-de -> ssormas-x
* User Role: admin

### Expected Behavior
Only one instance of 'Shared with' text should be displayed.

### Additional Information

Please note that the issue is replicating also on the test environments after the fixes on #8471. In that case, the "Share with" text is displayed multiple times (see image below).
![image](https://user-images.githubusercontent.com/111864167/207056936-71f1db5b-debe-4dba-8cbd-3d271fbe7e0e.png)

**Comment by abrudanancuta** [comment]
Validated on test.de 2 with the version: 1.79.0-SNAPSHOT (2cf8f52)
