### ISSUE TITLE
Cases are not deleted with automatic deletion if connected to external message or was sent to Survnet

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11176]
### Bug Description
Cases scheduled for  automatic deletion are not deleted if connected to external message or was sent to Survnet

#### Steps to Reproduce

1. Have a Case that was sent to Survnet
2. Modify the creation date of the case to be included in the automatic deletion period( ex: creation date for the case needs change only for the year like 2001)
3. Trigger the automatic deletion
4. Check the case if it was deleted

OBS: The same flow is applying also when a case is created from a lab/physician message

### Actual Behavior
The case is not deleted

#### System Details

* Device:
* SORMAS version: 1.77.3
* Android version/Browser:
* Server URL: test.de2, test1402
* User Role: Admin+NatUser

### Expected Behavior
The case should be deleted

**Comment by abrudanancuta** [comment]
yes, I added at point 5 and 7

**Comment by cmeyerhzi** [comment]
i checked for a case connected with climedo. automatic deletion works.
