### ISSUE TITLE
Processed Messages remain in the system when a case/contact/event participant is soft deleted

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#11174]
### Bug Description

When a case with a processed messages is manually deleted, the message can still be found in the message directory for processed messages. 

#### Steps to Reproduce

1. Process a message and create a new case/contact/event participant
2. manually delete the created case/contact/event participant from Step 1
3. Look for the processed message in the message directory with the quick filter processed

#### System Details

* Device:
* SORMAS version: 1.77.3
* Android version/Browser:
* Server URL: 1402
* User Role:

### Expected Behavior

When a case/contact/event participant is deleted the associated processed message should be deleted, too.

**Comment by abrudanancuta** [comment]
Validated on local env having the hotfix branch.
