### ISSUE TITLE
Can't send Exposures via REST

### ISSUE THREAD

**Issue by FredrikSchaefer** [hzi-braunschweig/SORMAS-Project#11192]
### Bug Description

With version 1.77.3 rolled out, pushing exposures to a case seems broken to me. Did I miss anything?

#### Steps to Reproduce

1. Modify a case you could succesfully POST before by adding this minimal epiData:
```
    "epiData": {
        "exposureDetailsKnown": "YES",
        "exposures": [
            {
            "uuid": "VXDDIF-AYD4CS-TR54BX-VB3O2OT5",  // Using an existing uuid seems to change the exception
            "exposureType": "VISIT"
            }
        ]
    },
```
2. POST again to `{server}/sormas-rest/cases/push`, feel the explosion (Code 500).

#### System Details

* SORMAS version: 1.77.3
* Android version/Browser: Does not apply.
* Server URL: For example [schnischu.sormas.netzlink.com](https://schnischu.sormas.netzlink.com/)
* User Role: User role with rights to access SORMAS-REST and edit cases

### Expected Behavior

Pushing this should work, shouldn't it?

### Additional Information

Sorry, I can't provide server logs anymore. Tried this on SchniSchu at 2022-12-15 13:11:29 and 2022-12-15 13:33:18.

**Comment by leventegal-she** [comment]
@FredrikSchaefer the push endpoint for update with this small amount of data results in deleting other field values that may be set on the UI

**Comment by abrudanancuta** [comment]
Validated on test.de2 with the version: 1.79.0-SNAPSHOT (58ddec9)

**Comment by FredrikSchaefer** [comment]
> @FredrikSchaefer the push endpoint for update with this small amount of data results in deleting other field values that may be set on the UI

@leventegal-she Thank you for the heads up. I just intended to provide a minimal example.
