### ISSUE TITLE
Add additional fields to person (Rubella) [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1119]
These fields should maybe only be displayed for children (needs to be defined):

- [x] Father's name
- [x] Mother's name
- [x] Place of birth (Region/District/Community/Facility)
- [x] Gestation age at birth (weeks)
- [x] Birth weight (number field)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Should these field only be displayed for Rubella?
If they should also be displayed for other diseases: For which diseases and is there another criteria that hides the field (e.g. hide them for people older than 18 years)?

**Comment by MateStrysewskeSym** [comment]
- [ ] Display Mother's name and Father's name for every person < 5 years old (use case age as reference)

**Comment by MateStrysewskeSym** [comment]
- [ ] Always display Mother's name and Father's name (because restricting visibility of these fields based on age is too complicated)

**Comment by MateStrysewskeSym** [comment]
- [ ] Group Nickname, Mother's Maiden Name, Mother's Name, Father's Name, Phone Number and Phone Owner as "Contact information" and move it to the bottom of the person form
