### ISSUE TITLE
Uploaded documents in events cannot be deleted as the button is missing

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#11193]
### Bug Description

When a user uploads a document for an event, the button to delete the document is missing even though the user has the right DOCUMENT_DELETE. 

#### Steps to Reproduce

1. Log in with a user which has the right DOCUMENT_DELETE
2. Go to event directory and open an event
3. upload document 
4. look for delete button

#### Screenshots

![image](https://user-images.githubusercontent.com/98821699/207865095-e7a8e087-8bb9-4f93-b4fa-3192df6febeb.png)

#### System Details

* Device:
* SORMAS version: 1.77.3
* Android version/Browser:
* Server URL: 1401
* User Role:

### Expected Behavior

Uploaded documents should be deleteable when the user has the right DOCUMENT_DELETE

**Comment by SahaLinaPrueger** [comment]
is maybe caused and can be fixed similar to #11052

**Comment by abrudanancuta** [comment]
The bug appeared from this feature https://github.com/hzi-braunschweig/SORMAS-Project/issues/8463
The bug appears for Event and also Travel Entry

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.78.0-SNAPSHOT (c9f486a).
