### ISSUE TITLE
[S2S] Cannot accept shared contact in target system after deleting a contact in source system with handing ownership before acceptance 

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11204]
### Problem Description

After deleting a shared contact in source system with handing ownership before acceptance I cannot accept it in target system, because it is not visible there. Based on [SORDEV-12087](https://jira.sormas-tools.de/browse/SORDEV-12087) it should possible to accept shared contact in target system.
![image](https://user-images.githubusercontent.com/105210214/208083405-b7471729-bd3c-45fe-8c56-a56070e384c6.png)

#### Steps to Reproduce

1. Login as a Admin on "LK Barnim" ("url": "https://test-de1.sormas.netzlink.com/")
2. Create case and collect uuid
3. Create a contact and link previously created case to it
4. Go to created case
5. Click on Share button
6. Select "LK Fulda" organization ("url": "https://test-de2.sormas.netzlink.com/")
7. Add comment
8. Click on Share button
9. Navigate to "LK Fulda  ("url": "https://test-de2.sormas.netzlink.com/")
10. Login as a Admin
11. Click on shares button form navbar
12. Accept first case in Shares Page
13. Go back to "LK Barnim" ("url": "https://test-de1.sormas.netzlink.com/")
14. Navigate to last created contact
15. Click share contact 
16. Select "LK Fulda" organization ("url": "https://test-de2.sormas.netzlink.com/")
17. Check "Hand over the ownership" checkbox
18. Fill comment
19. Click Share button
20. Click on delete contact button
21. Set reason for deletion "Deletion request by affected person according to GDPR"
22. Click Yes
23. Navigate to "LK Fulda  ("url": "https://test-de2.sormas.netzlink.com/")
24. Click on shares button from navbar

**Expected**: There is a possibility to accept shared contact in target system 
**Actual**: There is no shared contact, and no possibilty to accept or reject it.

#### System Details

* Device:
* SORMAS version: test-de1: 1.78.0-SNAPSHOT (c38288f); test-de2: 1.78.0-SNAPSHOT (082313c)
* Android version/Browser: Chrome
* Server URL: https://test-de1.sormas.netzlink.com/, https://test-de2.sormas.netzlink.com/
* User Role: Admin

### Expected Behavior

There is a possibility to accept shared contact with "Hand over the ownership" in target system after deleting it in source system.

**Comment by leventegal-she** [comment]
@hms-sgent It's normal that the request disappears form the target system because it was requested in #10625
