### ISSUE TITLE
[S2S] column 'sender organization' in the share directory should be 'From/ To'

### ISSUE THREAD

**Issue by SORMAS-SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#11219]
### Bug Description

Name of the column _sender organization_ in the share directory should be _From/ To_ as specified in #9755.

#### Steps to Reproduce

1. open the share directory
2. observe the name of the column _sender organization_ 

### Expected Behavior

Name of the column _sender organization_ in the share directory should be _From/ To_
### Additional Information

Background: In the _incoming_ share directory the source system is shown, in the _outgoing_ share directory the target system is shown. As you can see in the comments https://github.com/hzi-braunschweig/SORMAS-Project/issues/9755#issuecomment-1260612621 the name was _From / To_ one day. I do not know why this changed.
Now the health departments are rightfully wondering why the target system is shown on the _outgoing_ share directory because the name of the column is _sender organization_ . 

#### System Details

* Device:
* SORMAS version: 1.77.5
* Android version/Browser:
* Server URL: release-sormas-x / release-de
* User Role: admin/national user

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using the latest version of SORMAS 1.79.0-SNAPSHOT(e396cf4).
