### ISSUE TITLE
Assigned by user is empty when assigning tasks via bulk edit mode

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#11226]
### Bug Description

When assigning tasks via bulk edit mode, the assigned by user is not shown and the field stays empty.

#### Steps to Reproduce

1. Go to task directory and activate bulk edit mode
2. select serveral tasks
3. click on bulk actions and select edit
4. change task assignee and save
5. check task for assigned by

#### System Details

* Device:
* SORMAS version: 1.77.5
* Android version/Browser:
* Server URL: 1402
* User Role:

### Expected Behavior

When assigning tasks via bulk edit mode, the assigning user appears in the field assigned by.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(c8c2964).
