### ISSUE TITLE
Automatic server setup script

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1122]
- [x] define which prerequisits are not part of the script (e.g. postgres)
- [x] what about postgres temporal tables
- [x] what about the application server?
- [x] how to deal with different operating systems?
- [x] ~~possible to provide a linux package?~~

Also have a look at the DHIS2 documentation on this: https://docs.dhis2.org/master/en/implementer/html/installation.html#

The most important part seems to be to get rid of old and uncessary technology & steps:

- [x] migrate to payara 5 #1192
- [x] find better solution for temp & generated directories?

From my point of view the following components should remain prerequisits and thus should not be part of the SORMAS setup script (though we should have a check to make sure they exist):

* operating system
* java (zulu)
* postgres database with temporal tables plugin (potentially optional - see #1191)
* apache web server (production)
* postfix mail server (production)

Readme improvements:

- [x] split to prerequisits, domain setup and web server setup
- [x] explicitely point to git bash for setup script
- [x] remove payara install part
- [x] as_env.conf AS_JAVA is not needed

Script improvements:

- [x] detect system: windows/linux
- [x] create payara linux user
- [x] check JDK version
- [x] download & install payara
- [x] path on windows: space is not working!
- [x] remove serverlibs
- [x] check for database and create if missing
- [x] use /opt/sormas/temp and generated as default paths
- [x] windows: create script to start the domain
- [ ] ~~add check for max prepared transactions~~
- [ ] ~~add apache config as optional part to script~~

**Comment by MateStrysewskeSym** [comment]
- [ ] Set logging directory in server-update.sh
- [ ] Change defaults in sormas.properties

**Comment by MartinWahnschaffeSymeda** [comment]
Ran into a problem with the cacerts.jks file. When using this on a linux server and trying to start the domain, it will ask for a master password that has never been defined.

- [ ] only copy the cacerts.jks on windows dev systems
