### ISSUE TITLE
Wrong amount of users [Event participant]

### ISSUE THREAD

**Issue by pk-sgent** [hzi-braunschweig/SORMAS-Project#11234]
There is a problem with amount of created event participants. Amount of event participants next to "All" button is wrong until click on "Apply Filters" button.

![image](https://user-images.githubusercontent.com/96249076/208875373-f02cbae2-eed2-4885-b838-66cf027040ee.png)

1. Create new event
2. Create new event participant
3. Check amount of event participants next to All button

Env:

test-auto
Version: 1.78.0-SNAPSHOT (fe71891)

**Comment by StefanKock** [comment]
Reopened #10958
