### ISSUE TITLE
NullPointerException when calling Person.isModified() in CaseListAdapter

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1123]
. | NullPointerException  - Root cause: java.lang.NullPointerException: Attempt to invoke virtual  method 'boolean  de.symeda.sormas.app.backend.person.Person.isModified()' on a null  object reference - Stack trace:  de.symeda.sormas.app.caze.list.CaseListAdapter:onBindViewHolder:56 ->  androidx.recyclerview.widget.RecyclerView$Adapter:onBindViewHolder:6890  ->  androidx.recyclerview.widget.RecyclerView$Adapter:bindViewHolder:6932  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryBindViewHolderByDeadline:5852  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryGetViewHolderForPositionByDeadline:6119  ->  androidx.recyclerview.widget.GapWorker:prefetchPositionWithDeadline:286  -> androidx.recyclerview.widget.GapWorker:flushTaskWithDeadline:343  -> androidx.recyclerview.widget.GapWorker:flushTasksWithDeadline:359  -> androidx.recyclerview.widget.GapWorker:prefetch:366 ->  androidx.recyclerview.widget.GapWorker:run:397 ->  android.os.Handler:handleCallback:836 ->  android.os.Handler:dispatchMessage:103 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6258 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - Root cause stack trace:  de.symeda.sormas.app.caze.list.CaseListAdapter:onBindViewHolder:56 ->  androidx.recyclerview.widget.RecyclerView$Adapter:onBindViewHolder:6890  ->  androidx.recyclerview.widget.RecyclerView$Adapter:bindViewHolder:6932  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryBindViewHolderByDeadline:5852  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryGetViewHolderForPositionByDeadline:6119  ->  androidx.recyclerview.widget.GapWorker:prefetchPositionWithDeadline:286  -> androidx.recyclerview.widget.GapWorker:flushTaskWithDeadline:343  -> androidx.recyclerview.widget.GapWorker:flushTasksWithDeadline:359  -> androidx.recyclerview.widget.GapWorker:prefetch:366 ->  androidx.recyclerview.widget.GapWorker:run:397 ->  android.os.Handler:handleCallback:836 ->  android.os.Handler:dispatchMessage:103 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6258 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - User:  RKXF25-ZSKDSF-FVD7VI-I2IDSJNA - System:  https://sormas.org.ng/sormas-rest/
-- | --

**Comment by MateStrysewskeSym** [comment]
Possibly associated with #1086

**Comment by MateStrysewskeSym** [comment]
New exception:

. | NullPointerException  - Root cause: java.lang.NullPointerException: getPerson() is null;  Case: X3ZGRE-U4SC5I-67GLOU-RK6WKL3Q; Position in list: 7; Change date:  Thu Jan 01 01:00:00 GMT+01:00 1970; Creation date: Tue Apr 09 09:58:27  GMT+01:00 2019; Symptoms null?: false - Stack trace:  de.symeda.sormas.app.caze.list.CaseListAdapter:onBindViewHolder:59 ->  androidx.recyclerview.widget.RecyclerView$Adapter:onBindViewHolder:6890  ->  androidx.recyclerview.widget.RecyclerView$Adapter:bindViewHolder:6932  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryBindViewHolderByDeadline:5852  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryGetViewHolderForPositionByDeadline:6119  ->  androidx.recyclerview.widget.RecyclerView$Recycler:getViewForPosition:5958  ->  androidx.recyclerview.widget.RecyclerView$Recycler:getViewForPosition:5954  ->  androidx.recyclerview.widget.LinearLayoutManager$LayoutState:next:2226  -> androidx.recyclerview.widget.LinearLayoutManager:layoutChunk:1557  -> androidx.recyclerview.widget.LinearLayoutManager:fill:1517 ->  androidx.recyclerview.widget.LinearLayoutManager:scrollBy:1331 ->  androidx.recyclerview.widget.LinearLayoutManager:scrollVerticallyBy:1075  -> androidx.recyclerview.widget.RecyclerView:scrollStep:1829 ->  androidx.recyclerview.widget.RecyclerView$ViewFlinger:run:5155 ->  android.view.Choreographer$CallbackRecord:run:907 ->  android.view.Choreographer:doCallbacks:709 ->  android.view.Choreographer:doFrame:641 ->  android.view.Choreographer$FrameDisplayEventReceiver:run:893 ->  android.os.Handler:handleCallback:836 ->  android.os.Handler:dispatchMessage:103 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6258 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - Root cause stack trace:  de.symeda.sormas.app.caze.list.CaseListAdapter:onBindViewHolder:59 ->  androidx.recyclerview.widget.RecyclerView$Adapter:onBindViewHolder:6890  ->  androidx.recyclerview.widget.RecyclerView$Adapter:bindViewHolder:6932  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryBindViewHolderByDeadline:5852  ->  androidx.recyclerview.widget.RecyclerView$Recycler:tryGetViewHolderForPositionByDeadline:6119  ->  androidx.recyclerview.widget.RecyclerView$Recycler:getViewForPosition:5958  ->  androidx.recyclerview.widget.RecyclerView$Recycler:getViewForPosition:5954  ->  androidx.recyclerview.widget.LinearLayoutManager$LayoutState:next:2226  -> androidx.recyclerview.widget.LinearLayoutManager:layoutChunk:1557  -> androidx.recyclerview.widget.LinearLayoutManager:fill:1517 ->  androidx.recyclerview.widget.LinearLayoutManager:scrollBy:1331 ->  androidx.recyclerview.widget.LinearLayoutManager:scrollVerticallyBy:1075  -> androidx.recyclerview.widget.RecyclerView:scrollStep:1829 ->  androidx.recyclerview.widget.RecyclerView$ViewFlinger:run:5155 ->  android.view.Choreographer$CallbackRecord:run:907 ->  android.view.Choreographer:doCallbacks:709 ->  android.view.Choreographer:doFrame:641 ->  android.view.Choreographer$FrameDisplayEventReceiver:run:893 ->  android.os.Handler:handleCallback:836 ->  android.os.Handler:dispatchMessage:103 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6258 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - User:  QGIFEU-O6TW2N-AIYUTB-O3AFSOOQ - System:  https://sormas.org.ng/sormas-rest/
-- | --

**Comment by MartinWahnschaffeSymeda** [comment]
Guess on how this may have happened:

1. User has created case for person
2. User loses access to person because another case was moved
3. Complete sync is done and the person is deleted

Solution:

- [ ] Only delete invalid uuids when all data has been synchronized
- [ ] re-sync data on systems where the problem occured

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Can you please make a re-sync on the device of user QGIFEU?

**Comment by MateStrysewskeSym** [comment]
Happened again:


Fatal Exception: java.lang.NullPointerException
getPerson() is null; Case: S2TJOB-FLQHS4-OAC2UO-FPPPCKNA; Position in list: 2; Change date: Thu Jan 01 01:00:00 GMT+01:00 1970; Creation date: Mon Jun 17 12:56:56 GMT+01:00 2019; Symptoms null?: false
