### ISSUE TITLE
Warning for user login gets triggered even if one of the required rights is selected

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#11256]
### Bug Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/10034 implemented a warning to notify the admin when they create a user who would not be able to login since they're either missing the SORMAS UI or SORMAS REST user right. However, even when one of these is checked, the warning gets triggered upon saving.

#### Steps to Reproduce

1. Create a new user role and check just one of the rights SORMAS UI or SORMAS REST
2. Save the user role configuration and check the message

#### System Details

* Device:
* SORMAS version: 1.78.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

### Expected Behavior

The warning should only get triggered when both of the rights are missing

**Comment by abrudanancuta** [comment]
In the ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/10034 at the Implementation details is mentioned that the warning message appears when one of those rights is not selected. 
The cases that were implemented are:

- If both user rights(Sormas UI and Sormas Rest) are unchecked then the warning message appears
- if Sormas UI checked and Sormas Rest unchecked then the warning message appears
- if Sormas Rest checked and Sormas UI unchecked the warning message appears
- if both user rights selected(Sormas UI and Sormas Rest) then **no** warning message appears

If we want to change the implementation that I explained above, then we need to change the type of this ticket to Change Request

**Comment by MateStrysewske** [comment]
Closing this issue because everything works as specified and I'd actually advise against changing anything about this logic because as soon as we migrate to a different UI technology, the sormas-rest user right will be necessary for all users of the web app anyway.
