### ISSUE TITLE
The sample directory search field is misaligned

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#11263]
### Bug Description

The search field in the sample directory is misaligned.

#### Steps to Reproduce

1. Open the sample directory
2. Check the filter section

#### Screenshots

<img width="460" alt="Screen Shot 2022-12-29 at 10 40 40 AM" src="https://user-images.githubusercontent.com/70317594/209933874-7a8f1975-909a-4fb0-8ce7-09defe01567b.png">

#### System Details

* Device:
* SORMAS version: 1.78.0
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

### Expected Behavior

 The field should be aligned with the other filter fields

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(49b56ea).
