### ISSUE TITLE
Automatic server update script

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1126]
* Should be done based on "convention over configuration": Use defaults for all params, but allow users to change it
* Automatic download of the latest release?

**Comment by MateStrysewskeSym** [comment]
- [ ] Also automatically update audit schema (different EntityManager required)

**Comment by MartinWahnschaffeSymeda** [comment]
Important: On my system the following SQL was needed to make the automatic SQL work:

`ALTER TABLE schema_version OWNER TO sormas_user;`

**Comment by MartinWahnschaffeSymeda** [comment]
Let's get rid of the manual part in the readme

- [ ] add comments from readme to script
- [ ] remove manual part from readme
