### ISSUE TITLE
Not all tasks associated with entities shared via S2S are shared into the receiving system

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11277]
### Problem Description

When cases, contacts and events are shared from one instance to another via S2S not all the associated tasks are shared, regardless of whether the case is share only to view or with ownership handover.

For cases - only the 'Case investigation task' is shared.

For contacts - only the 'Contact investigation task' is shared.

For events - no task is shared.

@SahaLinaPrueger @MateStrysewske is this behavior expected? If not, is it safe to assume that all the tasks associated with a shared case, contact or event should also be shared when the associated entity is shared?

### Additional Information

Logged the ticket as a task and not a finding as I was uncertain if perhaps this is the expected behavior or not. The ticket will be converted of determined that the behavior needs to be changed.

**Comment by SahaLinaPrueger** [comment]
Tasks should never be shared because they are health department specific and the receiving system should not be aware of the internal processes. That tasks are also shared should not be specified anywhere and would be a bug.

**Comment by adinaflorea9** [comment]
@SahaLinaPrueger Thank you! I will update the ticket's description accordingly and will convert it into a bug!

**Comment by adinaflorea9** [comment]
Investigated further the behavior - the investigation tasks of cases and contacts are not actually shared from one instance to another - the tasks are the ones that are automatically generated when an entity is created, so when the case or contact are accepted into the receiving system, the investigation task is generated as well - so it is not the same task that was associated with the entity in the sending system.

I will close this ticket as discarded.
