### ISSUE TITLE
[S2S] Shares do not appear as processed immediately in the 'Shares' directory

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11291]
### Bug Description

Share requests do not appear as processed immediately after they were accepted in the receiving system, if the duplicate detection is triggered for cases and contacts. 

#### Steps to Reproduce

1. Create 2 duplicate cases (or contacts) for the same person;
2. Share both of them via S2S;
3. In the receiving system, accept the first case or contact shared;
4. Then click to accept the second case or contact shared;
5. In the duplicate detection pop-up that gets triggered after step 4, click 'OKAY'.

### Actual Behavior

The share is processed but in the UI it still appears as unprocessed as the 'Accept' or 'Decline' buttons are still visible. If the user clicks on them, a pop-up message informs them that the share request has already been processed. Only after refreshing the page does the share appear as processed in the UI as well.

### Expected Behavior

Just as in the case of the first share request accepted, for the second one the buttons to 'Accept' or 'Decline' it should disappear immediately after the share was processed.

#### Screenshots

GIF of the behavior:
![S2S - processing of shares](https://user-images.githubusercontent.com/96909231/211002396-a269233f-d330-4c77-aa36-874a87a02b60.gif)

#### System Details

* Device: Windows 10
* SORMAS version: 1.79.0; 1.78.0
* Android version/Browser: Chrome
* Server URL:  https://test-de1.sormas.netzlink.com/ and https://test-de2.sormas.netzlink.com/
* User Role: Admin+NatUser

### Additional Information

Labeled as 'minor' as the shares are processed and there is a workaround this - the user can simply refresh the page.

**Comment by abrudanancuta** [comment]
Validated on test.de2, test.de1 with the version: https://github.com/hzi-braunschweig/SORMAS-Project/commits/6697884775123dae962801ab42e1cc0477a35440
