### ISSUE TITLE
Introduce "Restore" bulk action [3]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11327]
### Problem Description

With #8465  the new grid for soft deleted entities was introduced for cases, contacts, events, event participants, immunizations, samples and travel entries. 

In this grid, bulk edit mode and bulk actions are possible. However, among the bulk actions there is currently 'Delete' but no 'Undo Deletion' bulk action, similar to how there is archive and de-archive.

### Proposed Change

Introduce the bulk action 'Undo deletion' in the grids that display soft deleted entities.

### Acceptance Criteria

- [x] An "Undo deletion" bulk action is shown in all directories specified above when filtering by deleted entities
- [x] Clicking the bulk action brings up a pop-up:
  - Caption: "Confirm undo deletion"
  - Content: "Are you sure you want to undo the deletion for all {selected_entry_count} selected {entity_name}s?"
  - Options: "No" and "Yes"
  - Should look similar to the pop-up that appears when e.g. bulk de-archiving cases
- [x] Grid is reloaded after confirming the action; entities for which the deletion has been undone no longer appear in the grid (since it should still be filtered by deleted entities)
- [x] Clicking the bulk action without selecting any entity brings up the usual warning message
- [x] Hide the "Delete" bulk action when filtering cases by deleted cases

### Additional Information
Make sure that the user is always allowed to undelete all the cases in the list (i.e. check whether there's any restriction in this regard for the archive/de-archive bulk action; if yes, we need to have something similar here, if no, we're probably fine).

**Comment by sergiupacurariu** [comment]
The immunization entity will be excluded from this ticket due to missing the bulk edit mode on the immunization grid.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(A14eb26).
