### ISSUE TITLE
[Samples] District of samples associated with cases only is not displayed on the grid

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11326]
### Bug Description

In the 'Samples' directory, for the column 'District' the associated district is not displayed for samples that have only cases associated.

When filtering based on the values from the responsible region and district of the case, the sample is displayed as a result, but the district is still not displayed in the grid.

#### Steps to Reproduce

1. Create a case and add a sample to it;
2. Navigate to the 'Samples' directory and observe the 'District' column values.

### Actual Behavior

The 'District' of samples that have only cases associated is not displayed. 

### Expected Behavior

The district should be displayed for samples that have only cases associated. 

#### Screenshots

GIF of the behavior:
![Sample district](https://user-images.githubusercontent.com/96909231/211836658-03287334-667c-4893-aeda-432cf1516a60.gif)

#### System Details

* Device: Windows 10
* SORMAS version: 1.79.0; 1.78.0
* Android version/Browser: Chrome
* Server URL: local machine; https://release-international.sormas.netzlink.com/
* User Role: Admin+NatUser

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.79.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/1ffadcbebdf84a22cb35eaba31de0e81a1ae71e5)

While testing I observed that if a detailed export is made for Samples, the columns for Region and District of the case have no values in them. For this scenario I will open another ticket. https://github.com/hzi-braunschweig/SORMAS-Project/issues/11398
