### ISSUE TITLE
[DE] Untranslated option in Travel Entry filter 

### ISSUE THREAD

**Issue by pk-sgent** [hzi-braunschweig/SORMAS-Project#11321]
### Problem Description
There is a untraslated option in Travel Entries. In filters (id=relevanceStatus) appears "All active and archived travel entries" option on German language environment

#### Steps to Reproduce

1. Login on German environment 
2. Navigate to Travel Entries
3. Click on combobox with Travel Entry filter options

#### Screenshots

![image](https://user-images.githubusercontent.com/96249076/211804120-5bb4211a-95ef-423a-9654-bebed7d90acf.png)

#### System Details

* Device: Win10
* SORMAS version: Version: 1.79.0-SNAPSHOT (58ddec9)
* Android version/Browser: Google Chrome 109.0.5414.74
* Server URL: https://test-de.sormas.netzlink.com/
* User Role: Automation Admin

### Expected Behavior

Options should be displayed in German

**Comment by adinaflorea9** [comment]
@pk-sgent Translations are not done by the development team - they are updated with an automated job from Crowdin. if the translation for travel entries was not provided yet for that specific term displayed in the filter, the it will of course still be displayed in English. Please recheck this in a few days and see if the translations have been updated.

**Comment by adinaflorea9** [comment]
@pk-sgent - the translations are not hard coded so they are not done by the development team. An automatic job updates them when they are available from Crowdin - so if the translation is not visible in the UI it is because it is not yet available in Crowdin.

**Comment by pk-sgent** [comment]
@adinaflorea9 thank you! So we are waiting for the update

**Comment by adinaflorea9** [comment]
Yes, exactly. This update is however not in the hands of the development team.

**Comment by AliciaRaber** [comment]
This option is also in case directory. If necessary I can update the issue or create a new one.
![Case-untranslated](https://user-images.githubusercontent.com/91321821/228231117-678fa9b4-07ca-4afc-bf42-c301fd6f6ff1.jpg)

**Comment by AliciaRaber** [comment]
Please be so kind and check this issues. Thank you.

**Comment by pk-sgent** [comment]
problem is fixed.
