### ISSUE TITLE
Limit user access to data of a single disease (Rubella) [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1133]
- [x] add a disease field to the user
- [x] only show cases, contacts, events, etc. associated to that disease. Should work automatically by extending the user filter in the backend
- [x] limit all selection fields to this disease. Keep in mind that the user may have created a case that turns out to have another disease, but the user will still be allowed to see that case, because of creating it
- [x] make sure dashboard is filtered

@hzi-braunschweig What about events that are not associated to a disease? Should the user see those events? This may not make sense for Rubella, but the functionality could also be used for another disease (e.g. a user that is dealing with EVD only). Should such a user see all events that are not associated to a specific disease?

**Comment by MateStrysewskeSym** [comment]
- [ ] Show events without a disease to users with a limited disease set

**Comment by MateStrysewskeSym** [comment]
- [ ] Filters in for loop in CaseService and EventService still need to execute or

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Filters seem to have broken user access to cases; this needs to be fixed
