### ISSUE TITLE
Germany is not assigned to Central Europe

### ISSUE THREAD

**Issue by pk-sgent** [hzi-braunschweig/SORMAS-Project#11334]
### Problem Description

Germany is not assigned to Central Europe

#### Steps to Reproduce

1. Log in as a automation admin
2. Navigate to Configuration
3. Click on Coutries Tab
4. Search Germany 

#### Screenshots

![image](https://user-images.githubusercontent.com/96249076/212048934-6e1b1db0-a05a-4d6f-aa6d-f029da7c1ada.png)

#### System Details

* Device: Win10
* SORMAS version: Version: 1.79.0-SNAPSHOT (50d6548)
* Android version/Browser: Google Chrome 109.0.5414.75 
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Automation Admin

### Expected Behavior

Germany should be assigned to Central Europe

**Comment by adinaflorea9** [comment]
@pk-sgent Would you please be able to let me know if there are any failing tests due to this? As I checked all of the testing instances that we have available and as far as I can remember since I have been on the project Germany has always been set in the subcontinent 'Western Europe'.

**Comment by pk-sgent** [comment]
@adinaflorea9 we had that in the test scenario somewhere. Of course we can adjust it to the current state but the 'Western Europe' as a geographic localization for Germany is correct?

**Comment by adinaflorea9** [comment]
As discussed with @pk-sgent the test will be adjusted to have Germany as part of Western Europe as it currently is on all testing instances. Therefore, I will close this ticket as resolved.
