### ISSUE TITLE
Enable informants and officers to create and edit pathogen tests

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1134]
- [x] Add missing fields to the PathogenTest entity
- [x] Trigger repull of all pathogen tests to complete the data (reset change date of all pathogen tests to 0)
- [x] Add PathogenTestListFragment to SampleReadActivity and SampleEditActivity. Ideally PathogenTestListFragment extends BaseEditFragment and is used in both activities - having two list fragements that basically do the same does not make a lot of sense.
- [x] Add PathogenTestReadActivity and -EditActivity with the needed fragments. See web app. Make sure all the sample user rights are properly implemented, especially SAMPLE_EDIT and SAMPLE_EDIT_NOT_OWNED.

Would make sense to also do #1136 in this context

**Comment by faatihi** [comment]
I'm taking this one

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/58629804-ffea5f80-82cc-11e9-99fe-29d4774e265a.png)

I would like some clarification. Is this issue about being able to request for Pathogen Tests to be done? That is, adding tags to the "Requested Pathogen Tests"?

**Comment by MartinWahnschaffeSymeda** [comment]
![grafik](https://user-images.githubusercontent.com/23217632/58704045-f9321a00-83aa-11e9-80f2-4fa01aecf5f7.png)

No, adding additional tags is already possible when you are the user who is creating the sample.

What is requested here is to be able to add acutal pathogen tests instances including test results. The picture above is the section where this is possible in the web app. The same functionality is needed for the android app.

**Comment by faatihi** [comment]
Ok

**Comment by faatihi** [comment]
Hi, everyone,
We have a new developer on board the SORMAS dev team @ GCNet, Ghana - Joshua Opata. 
He and I will be working on the project

**Comment by opatajoshua** [comment]
Hi

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/60193973-14683c00-9828-11e9-9367-14472c28acc4.png)

Here's a mockup showing how PathogenTests is intended to be incorporated on the SampleInformation page

**Comment by faatihi** [comment]
We plan adding a drawer on the page to give access to PathogenTests

**Comment by opatajoshua** [comment]
i am trying to test the user rights implementation on the mobile app "Make sure all the sample user rights are properly implemented, especially SAMPLE_EDIT and SAMPLE_EDIT_NOT_OWNED.". but there is a permission conflict when setting the user permission on the web app. "Surveillance Officer cannot be combined with Lab Officer" 
So i am not able to give the user permission to add and edit pathogens

**Comment by hzi-braunschweig** [comment]
Welcome to the team @opatajoshua . I will add you now as a collaborator to the SORMAS project.

**Comment by opatajoshua** [comment]
Thank you @hzi-braunschweig

**Comment by MartinWahnschaffeSymeda** [comment]
@opatajoshua The surveillance officer is not supposed to be a lab user at the same time. The surveillance officer uses the mobile app, while lab users use the web app.

The point here is that you need to adjust the UserRight enum and give those user rights to the surveillance officer. I just had a look at it: The SAMPLE... rights are already available for the surveillance offer. What is missing is PATHOGEN_TEST_CREATE and PATHOGEN_TEST_EDIT.

**Comment by MartinWahnschaffeSymeda** [comment]
@opatajoshua This is finished now. My commit 1f0de8e contains a few clean up things, but is worth a look I guess.
More importantly, I didn't realize that a very crucial part is missing, when I reviewed your pull request. The database in the mobile app was not updated with the new colums.
Since this was now already on the dev branch I decided to go forward instead of comming back to you. Please have a look at my commit b48e2b3 to make sure I haven't messed up something you built.
