### ISSUE TITLE
Simplify "transfer case" mechanism [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1135]
Instead of having a separate button the user should be allowed to just edit the health facility. When saving the case ask the users whether it was transfered (which will create a previous hospitalization) or a data correction.

**Comment by foyiri** [comment]
my opinion i don not think it will work that way when you edit the health facility what happen to the state where the case is coming from remember each device is configure for one LGA access only

**Comment by MateStrysewskeSym** [comment]
- [ ] Replace dialog button caption/message: Data correction should be Data edit, maybe extend the message to clarify what the user is supposed to do
