### ISSUE TITLE
Split epid number into two fields in the web and mobile UI

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1138]
This should only be done in the user interface, not in the actual data model.

- [ ] Web UI: The logic should automatically detect the fixed part of the epid-number and display it in a field that is only editable for users with admin rights (for now). 
- [ ] The suffix is editable, but restricted to numbers only
- [ ] same in mobile app
- [ ] EPID number should be editable by the informant

**Comment by MateStrysewskeSym** [comment]
Not required anymore, see #1082
