### ISSUE TITLE
Sample Export detailed File doesn't contain the Responsible region and district of the case

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11398]
### Bug Description
Sample Export detailed File doesn't contain the Responsible region and district of the case

#### Steps to Reproduce

1. As NatUser have a Case that has also a sample and pathogen test
2. The case ha Responsible Region and District completed
3. Go to Sample directory
4. Have bulk edit mode selected
5. Choose the case above and make a detailed export
6. Open the file and check for the Region of Case and District of case column
7. Go Back to the Case and edit it
8. Add that Place of stay differs
9. Add other Region and District
10. Go back to samples and make another export for the same case 

### Actual Behavior
At step 6 the columns don't have any value
At step 10 the columns have the values for Region and District of the Place of stay

### Expected Behavior
The Region of Case and District of Case should take the values from the Responsible Region and Responsible Distrcit

#### System Details

* Device:
* SORMAS version: 1.78.0
* Android version/Browser:
* Server URL:
* User Role: NatUser

**Comment by ChristopherRiedel** [comment]
Agreed with @MateStrysewske that the described behavior is not an error in the strict sense, but that when introducing responsible jurisdiction, this should also have been added here.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.81.0-SNAPSHOT(e64c6fd).
