### ISSUE TITLE
Add  counts and proportions for pathogen test results on sample dashboard [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#11411]
### Feature Description

- This issue belongs to https://github.com/hzi-braunschweig/SORMAS-Project/issues/10723
-  With the development of a sample dashboard,  it would be nice to have the pathogen test details shown on it.  So far the surveillance dashboard shows the `final laboratory result` of the latest sample of each case and the sample dashboard show the "final laboratory result" of all samples, which is different from the pathogen test results.

### Proposed Change

-  [x] Add a pathogen test result widget to the sample dashboard. Should consider all pathogen tests of the samples that fall into the filter criteria of the dashboard; the disease the pathogen test is associated with has to be the tested disease of the pathogen test itself, not the disease of the sample
-  [x] Add counts and proportions for all enums of pathogen test results: `positive, negative,pending,Indeterminate`
-  [x] - unit tests

![image](https://user-images.githubusercontent.com/12996724/215190768-b5c27b16-2b00-4739-ae84-d648cfa20e83.png)

### Acceptance Criteria

- Sum of counts for all categories === total number of pathogen tests linked to returned samples
- sum proportion == 100% always

### Additional Information

- It is possible that there can be more pathogen tests than samples (if some samples are tested more than once), this is fine since it is on the sample dashboard.
- the denominator to compute proportion is the total number of pathogen tests, not total number of samples
- Only involve pathogen tests of samples that the user has access to
- How to work with Percentages can be taken from the contact dashboard

**Comment by bernardsilenou** [comment]
This should behave differently from widget shown on surveillance dashboard and should work based on pathogen test not final lab results of sample

**Comment by MateStrysewske** [comment]
@bernardsilenou @MartinWahnschaffe I see some potential for misinterpreting data here, e.g. based on the sentence "Should consider all pathogen tests of the samples that fall into the filter criteria of the dashboard".

Consider the following scenario: A user filters the dashboard by samples for Yellow Fever, i.e. the samples that fall into the criteria will be samples associated to Yellow Fever cases, contacts of Yellow Fever cases and event participants of Yellow Fever events. 

Now, it's possible that a lot of these samples will not only be tested for Yellow Fever, but also other VHFs (I don't know the specifics here and whether it's actually Yellow Fever that is similar to others VHFs, but I think you know what I mean). This means that those samples will have pathogen tests that are tested for OTHER diseases than the disease of the entity associated with the sample. 

If we simply consider all pathogen tests of the samples according to the filters, we might have POSITIVE pathogen tests displayed in this widget that aren't actually positive pathogen tests of the filtered disease, but a different disease that the sample was tested for as well. Similarly, we might end up with A LOT of NEGATIVE pathogen tests that have been performed simply to rule out other diseases.

I'm not sure whether this would be a result we want to end up with, or whether we'd need a different process to determine which pathogen tests to display here and which not.

What's your take on this?

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe @MartinWahnschaffe 
Following this comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721#issuecomment-1432777000
 It means that the other samples which are not yellow fever will not be included since they are cloned  (aliquots) at the moment that the disease of pathogen test is different.  My definition of a clone is a sample with the same attributes as the parent but a different uuid and linked to the parent sample (optional), new entity and old person, is this what happens?

A similar scenario:
 - Some samples (those linked to event participants for which the event has no disease) may not have a disease, thus filtering based on the disease would not include them.  Thus it would be good to consider both the disease of the pathogen test and that of the parent entity of the sample in the global disease filter. If you agree, then we can update  https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721
 -  The workflow for the environmental module (still to come) is that a sample is collected without any disease of parent entity ( e.g. event) + transformed into multiple aliquotes + multiple pathogen tests, each test having a different disease. The idea, for now, is to treat the clones as independent samples in the system.

**Comment by MateStrysewske** [comment]
@bernardsilenou This is not about cloned samples, it's about one sample being tested for multiple diseases, i.e. about having pathogen tests and their results that are not associated with the disease of the sample.

We could get rid of this problem by not interpreting "test results" as pathogen test entities, but as final laboratory results of samples for which the date at which the final laboratory result has been changed falls in the time period specified in the filters (because we track this date); I believe this would probably be more accurat for what we're trying to achieve here, what do you think @bernardsilenou @faatihi?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- The basic dashboard ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721 already has the widget for the final lab result. I think it is what you suggested here https://github.com/hzi-braunschweig/SORMAS-Project/issues/11411#issuecomment-1446012846
- This ticket addresses the situation that one disease can not be associated with a sample. The focus is on the number of pathogen tests done. 
- What about having the option to filter based on two disease types: sample disease | pathogen test disease, similar design as we have for date type: most relevant, symptom onset
-  Lets her from @faatihi

**Comment by bernardsilenou** [comment]
@MateStrysewske 
I had a call with @faatihi and this is the suggestion we have for now. What do you think, please?

Make the disease filter to be a dropdown with three categories (similar to date filter on the surveillance dashboard):
1. Most relevant disease ie extract samples and compute indicators seperately
1.1 Compute indicators for final lab results using disease of sample
1.2 Compute indicators for test results using disease of pathogen test

2. Sample disease
2.1 use the disease of the sample to compute indicators for  final laboratory result
2.2 for samples corresponding to 2.1, use the subset of pathogen test whose disease is the same as user-specified disease and compute indicators for pathogen test

3. Tested disease:
3.1 use disease of pathogen test to compute indicators for pathogen test
3.2 for samples corresponding to 3.1, use the subset of samples whose disease of sample is the same as user specified disease and compute indicators for the final laboratory result

**Comment by MateStrysewske** [comment]
@bernardsilenou Ah yeah, makes sense that we already have that widget, then my suggestion of course doesn't apply.

The solution you proposed seems pretty complicated and very hard to understand for the user to me; how do you feel about completely ignoring samples here, and simply calculating the counts based on the respective tested disease of the pathogen test, since that's a mandatory field anyway? Don't know why I haven't thought about this initially because it seems like the logical solution to me.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- Is your suggestion the same as point 1. here as https://github.com/hzi-braunschweig/SORMAS-Project/issues/11411#issuecomment-1447133228
- Ie for the pathogen test we ignore samples and for the final lab result we use samples

**Comment by MateStrysewske** [comment]
@bernardsilenou I think so, yes

**Comment by bernardsilenou** [comment]
I think it's fine.
@faatihi  what about you, please?

**Comment by faatihi** [comment]
Quote: "_the pathogen test we ignore samples and for the final lab result we use samples_"

@bernardsilenou @MateStrysewske Yes, I agree with this approach. Makes it much easier for users to reason with.

**Comment by carina29** [comment]
I'll reopen this ticket in order to add a styling ( a space between the total number of test results and the text).

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.82.0-SNAPSHOT (dd8b900) and also with @carina29 on her local system
