### ISSUE TITLE
Rename "Test results" to "Final laboratory result" on surveillance dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#11415]
### Problem Description

The surveillance dashboard display "test results"
![grafik](https://user-images.githubusercontent.com/23217632/216012477-8b7ea373-73fd-4876-ae18-0a6a5932208b.png)

The naming is a bit misleading here, because the actual logic does not calculate the number based on (pathogen) tests, but based on the final laboratory result of samples.

Furthermore, when a case has multiple samples it only counts the latest sample result.

### Proposed Change

- [x] Rename the caption on the dashboard to "Final laboratory result" (ideally re-use the field caption)
- [x] Add a tooltip to the dashboard element static "When a case has multiple samples, only the final laboratory result of  the sample  with the latest sample collection date is considered."

### Implementation Details

- [x] Rename internal method to getNewCasesFinalTestResultCountByResultType

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou Please double-check
@markusmann-vg Please define milestone and project(s)

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
Done!

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.81.0-SNAPSHOT(b7b5c65).
