### ISSUE TITLE
Case "Facility name & Description" should not be required in the android app

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#11427]
### Bug Description

Case "Facility name & Description" should not be required in the android app

#### Steps to Reproduce

1. Create a case with:
    * Facility: Other facility 
    * leave Facility name & Description empty
2.  Open the case in the android app

 => the field Facility name & Description is in error and the case can't be saved
#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior

Facility name & Description is not required and the case can be saved without specifying it
### Additional Information

Same thing happens when the Place of stay is set to Home and Facility name & Description is empty

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.80.0-SNAPSHOT(5d30dcd).
