### ISSUE TITLE
No possibility to display archived events in bulk mode

### ISSUE THREAD

**Issue by pk-sgent** [hzi-braunschweig/SORMAS-Project#11421]
### Problem Description

While trying to display archived events in bulk mode error occurs

#### Steps to Reproduce

1. Login as a Admin
2. Navigate to Event Directory
3. Enter to bulk mode edit
4. Change in filters Active Events to Archived Events 

#### Screenshots

![image](https://user-images.githubusercontent.com/96249076/216031101-51cabfaf-e90b-442d-8a9d-5d4853c56625.png)

#### System Details

* Device: Win10
* SORMAS version: Version: 1.80.0-SNAPSHOT (aa149c5)
* Android version/Browser: Google Chrome 109.0.5414.120
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Admin

### Expected Behavior

Use `IterableHelper.executeBatched` for the query that fails according to the logs (provided here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/11421#issuecomment-1411964039) in order to not run into the parameter limit.

**Comment by adinaflorea9** [comment]
I was not able to reproduce the behavior on the local machine where the SORMAS version is exactly the same, and with the same type of user.

However, I was able to reproduce it on test-auto and I have attached the grafana logs below:
[logs events .txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10556844/logs.events.txt)

**Comment by MateStrysewske** [comment]
Looks like we have an issue with parameter limits here; apparently there's a query that we haven't refactored to use `IterableHelper.executeBatched` yet.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the error is still reproducible on the environment noted in the ticket - https://test-auto.sormas.netzlink.com/ on SORMAS version 1.82.0-SNAPSHOT(0cf1e0d).

Steps to reproduce:
1. Log in with the regular admin user that is already created for all test environments (has the user roles of admin+NatUser); 
2. Navigate to the 'Events' directory;
3. Filter for **'Archived events'** or **'All active and archived events'.**

Actual behavior:
Error message appears:
![Filtering](https://user-images.githubusercontent.com/96909231/225275202-f1896b7e-5806-40a7-9c34-445388fae57d.gif)

**Comment by pk-sgent** [comment]
@ChristopherRiedel the problem still occurs on test-auto 
![image](https://user-images.githubusercontent.com/96249076/226316786-6b473bab-d8e9-40ff-ad18-6b66f73ce852.png)

**Comment by ChristopherRiedel** [comment]
> @ChristopherRiedel the problem still occurs on test-auto ![image](https://user-images.githubusercontent.com/96249076/226316786-6b473bab-d8e9-40ff-ad18-6b66f73ce852.png)

I know that. I looked at it again because of @adinaflorea9 comment, but my changes don't seem to have fixed the problem. However, I don't currently know where else the problem might lie.

**Comment by MateStrysewske** [comment]
@ChristopherRiedel Have a look at https://github.com/hzi-braunschweig/SORMAS-Project/issues/11653, pretty sure something's off about the query after your changes.

**Comment by abrudanancuta** [comment]
Validated on test-auto with the version: 1.82.0-SNAPSHOT (4f77f37)
