### ISSUE TITLE
Event participant is not editable in the android app

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#11429]
#### Steps to Reproduce

1. Log into the web app with NatUser
2. Create an event and an event participant
     * Select the same district that SurvOff is limited to 
4. Log into the android app with SurvOff
5. Try yo edit the created event participant

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior

The event participant shoul be editable
### Additional Information

Probably linked to [Extend event participant jurisdiction calculation on mobile app #5903](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5903)

**Comment by MateStrysewske** [comment]
Indeed very likely linked to #5903, i.e. we haven't yet extended the event participant jurisdiction calculation in the mobile app. I'll therefore close this issue.
