### ISSUE TITLE
Event participant address is "null" in the android app

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#11428]
#### Steps to Reproduce

1. Create an event participant in the web app 
2. Set values for Home address region and district
3. Open it in the mobile app
 
=> Observe the Home Address field, In edit mode if you tap on it the app crashes

#### Screenshots

<img width="384" alt="image" src="https://user-images.githubusercontent.com/62599627/216093379-e83ccd9a-c2a8-429b-bafc-f5ea1dbed8d9.png">

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior

The address is displayed correctly and in edit mode the user is able to edit it

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.80.0-SNAPSHOT(5d30dcd).
