### ISSUE TITLE
[DEMIS - External messages] Disease variant for External messages [2]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11449]
### Feature Description

Disease variants need to be extended in the 'External messages' - lab messages. This is part of epic #11447.

Add disease variant field to ExternalMessage and prefill the according field in SORMAS (currently this seems to be retrieved only in the 'Disease variant' field of pathogen tests).

### Proposed Change

The value set from the ExternalMessage.testedDiseaseVariant should be taken from the disease variants which can be configured in the DB - (https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Adding-Disease-Variants-to-a-SORMAS-Server).

- [x] Add diseaseVariant to dto and entity.

- [x] Fields for disease variant need to be added to the UI:
- new column 'Disease variant' on the grid similar to the one in other directories; it should be filled with the disease variant value from the external message;
![image](https://user-images.githubusercontent.com/96909231/216997270-39a0b4d0-d48a-4755-8bc0-4ffc490e8d97.png)

- introduce filter fields based on 'Disease' and 'Disease Variant' (as the ones we already have in the other directories);
![image](https://user-images.githubusercontent.com/96909231/217004987-59144b23-04b6-4bee-97f8-f7c9407edcab.png) ![image](https://user-images.githubusercontent.com/96909231/217005187-deca2393-44f6-4ec9-a084-277ada76c198.png)

- extend it in the pop-up forms that appear while processing the external messages ('Create new case' only as it is the only creation form that contains the field) the disease variant should be prefilled with the variant from the message, alongside with the disease. (This  already happens when reaching the step of processing the associated sample, where the disease variant is already filled with the variant from the message);

### Acceptance Criteria

The user should still be able to edit the disease variant that was prefilled, just as they can currently edit the disease that is also prefilled 
### Additional Information

[#80](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/80) will provide the variant.

**Comment by ChristopherRiedel** [comment]
- [ ] DiseaseVariant of events should also be prefilled

**Comment by abrudanancuta** [comment]
Validated on local env with the version 1.82.0-SNAPSHOT (1eb69c5)
