### ISSUE TITLE
Fix problems in CI process

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1144]
Jenkins promotion process does not work, due to "uncomitted changes" 

Maybe related to maven goal calling sormas-api/pom.xml with

> test
> -Dtest=*Generator
> -e
> -X

**Comment by MartinWahnschaffeSymeda** [comment]
> [ERROR] Failed to execute goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-start (default-cli) on project sormas-base: Error starting release: Error starting release: Working tree has uncommitted changes -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal external.atlassian.jgitflow:jgitflow-maven-plugin:1.0-m5.1:release-start (default-cli) on project sormas-base: Error starting release: Error starting release: Working tree has uncommitted changes
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Error starting release: Error starting release: Working tree has uncommitted changes
> 	at com.atlassian.maven.plugins.jgitflow.mojo.ReleaseStartMojo.execute(ReleaseStartMojo.java:117)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 20 more
> Caused by: com.atlassian.maven.plugins.jgitflow.exception.MavenJGitFlowException: Error starting release: Working tree has uncommitted changes
> 	at com.atlassian.maven.plugins.jgitflow.manager.DefaultFlowReleaseManager.start(DefaultFlowReleaseManager.java:62)
> 	at com.atlassian.maven.plugins.jgitflow.mojo.ReleaseStartMojo.execute(ReleaseStartMojo.java:113)
> 	... 22 more
> Caused by: com.atlassian.jgitflow.core.exception.DirtyWorkingTreeException: Working tree has uncommitted changes
> 	at com.atlassian.jgitflow.core.util.RequirementHelper.requireCleanWorkingTree(RequirementHelper.java:186)
> 	at com.atlassian.jgitflow.core.command.ReleaseStartCommand.call(ReleaseStartCommand.java:75)
> 	at com.atlassian.maven.plugins.jgitflow.manager.DefaultFlowReleaseManager.start(DefaultFlowReleaseManager.java:58)
> 	... 23 more
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
>

**Comment by MartinWahnschaffeSymeda** [comment]
Intersting reads:

* https://ecosystem.atlassian.net/browse/MJF-105
* https://github.com/nvie/gitflow/issues/81

Had a look at .git/jgitflow.log - it says 475 files are modified

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
Looks like calling git status before finishing the promotion does the trick. Not clear why. 
This also explains why it sometimes worked the second time - likely we did a manual "git status" in between.

I have added a call to "git status" to the configuration. The promotion has worked and I have started the release build.

**Comment by MartinWahnschaffeSymeda** [comment]
The last release again had problems with this. Looks like the fix didn't do the trick.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym I'm still wondering whether this is related to our generated data dictionary, etc. I have updated all generated files, so when you do the promotion they should not change this time.

**Comment by MateStrysewskeSym** [comment]
This seems to be working now.
