### ISSUE TITLE
[DEMIS - External messages] Date of result in TestReports [1]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11453]
### Feature Description

'Datum des Ergebnisses' / 'Date of result' is requested to be mapped to 'TestReport.dateOfResult' of external messages as part of #11447. 

### Proposed Change

Currently, in the pathogen test form, we have the fields for 'Date and time of result' but the corresponding information from the external messages is not imported when the messages are processed.

- [x] Add dateOfResult to TestReport

- [x] the information from the dateOfResult field from the external message should be imported into the pathogen test form when the message gets processed;

### Acceptance Criteria

- current date validation for 'Date of result' should be maintained - if the information does not correspond with the other dates from the sample and test result the fields should still be filled with the information imported from the external message, but it should be highlighted in red and the appropriate warning message should appear; 

- the field should remain editable.

**Comment by abrudanancuta** [comment]
Validated on local env with the version 1.82.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/1eb69c5fda4127ce5f7d982aed0876463246e3ec)
