### ISSUE TITLE
[External messages - S2S] External messages can not be shared via S2S as the mandatory field for 'Comment' is not displayed

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11458]
### Bug Description

Although the validation exists (meaning that the error message appears and informs the user that the 'Comment' field is mandatory) the 'Comment' section is not displayed in the 'Share' pop-up, when it is accessed for sharing an external message.
![image](https://user-images.githubusercontent.com/96909231/217267159-80bd6ab1-d487-46ed-92eb-06f5a293d6c1.png)

The 'Comment' section is present in the other flows when the 'Share' pop-up is accessed (such as sharing cases, contacts, events).
![image](https://user-images.githubusercontent.com/96909231/217267340-f3ba6bb1-e44e-4198-b6be-d5b07460d6de.png)

The wording of the error message should be fixed as well:
![image](https://user-images.githubusercontent.com/96909231/217267255-0f47dbb3-e640-4e1f-89af-4792d89c9b71.png)

#### Steps to Reproduce

1. Open an unprocessed external message and click on 'Send to another organization';
2. In the 'Share' pop-up, select an organization and click 'Share'.

### Actual Behavior

The external message can not be shared as the mandatory 'Comment' field is not displayed and can not be filled in.

### Expected Behavior

The 'Comment' field should be displayed. The wording of the error message should be edited to be consistent with how the error message is displayed in the other share flows:
![image](https://user-images.githubusercontent.com/96909231/217268063-a7c7b011-e001-4c10-8fa8-7b374755a261.png)

#### System Details

* Device: Windows 10
* SORMAS version: 1.80.0; 1.78.0
* Android version/Browser: Chrome
* Server URL: https://test-de2.sormas.netzlink.com/  and https://test1402.sormas.netzlink.com/
* User Role: Admin+NatUser

**Comment by abrudanancuta** [comment]
This ticket I propose to close it as duplicate as exists already another one that specifies the same problem
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11393

**Comment by adinaflorea9** [comment]
Closing the ticket as duplicate.
