### ISSUE TITLE
Limit lists for duplicate merging of contacts [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#11469]
### Problem Description
Data used for merging is currently only limited based on the report date filter, but still has to go through big parts of the available data.
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/8697#issuecomment-1106285204

We have already done this optimization for cases: #9054

### Proposed Change

- [x] Limit `ContactFacadeEjb.getContactsForDuplicateMerging` method to fetch a limited number of entries. See
- [x] Add a drop-down that allows the user to define the limit: 50, 100, 500, 1000. Should also reflect in URL. You can re-used what has been implemented for the MergeCasesView (QueryDetails, etc.)

### Acceptance Criteria
- [x] Provide explain analyze with timings of a query that takes at least 30 seconds with the old implementation
- [x] Provide explain analyze with timings of the new query with same filters that should now be significantly faster

### Implementation Details
- [x] Check for useless joins, e.g. comparing the id of the regions of two contacts instead of the region_id
- [x] Try to get rid of distinct. Validate that no One/ManyToMany join is done that introduces duplicate rows
- [x] Check whether indices can be added, e.g. for sorting based on creationDate

**Comment by abrudanancuta** [comment]
Validated on test-de with the version: 1.81.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/862c1bd062d5fb0424dca7ebca1dc470f733c346)
