### ISSUE TITLE
SORMAS to generate complete EPID Number for all cases 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1146]
The TWG of Lassa Fever and WHO has requested that we automatically generate the complete EPID number (down to the serial number). 

Cases are to receive automatic assignment of serial numbers based on successful synchronization with the server. 

Can we discuss this further?

**Comment by danieltomaba** [comment]
@Chinedar @MartinWahnschaffeSymeda I think its a perfect idea. Then WHO can use SORMAS Epid numbers as a standard

**Comment by foyiri** [comment]
[Epid Code.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3222459/Epid.Code.xlsx)
Attached is the complete Epid code for Nigeria

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove existing warning from epid number field
- [ ] Automatically generate epid number suffix on the server whenever a case with an incomplete epid number is saved (incremental numbers)
- [ ] Show a warning in the UI when a case with an identical epid number exists
- [ ] Add "Auto-assign new epid number" button to web UI (only shown when the epid number is a duplicate)

**Comment by MateStrysewskeSym** [comment]
- [ ] Replace SQL to retrieve highest epid number with the following code:

SELECT epidnumber FROM cases WHERE cases.epidnumber LIKE 'NIE-ABS-UMA-19-%' ORDER BY NULLIF(regexp_replace(cases.epidnumber, '\D', '', 'g'), '')::int DESC LIMIT 1

- [ ] Repair error message
- [ ] Make sure that button is displayed when prefix is incomplete
