### ISSUE TITLE
Congenital rubella syndrome

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1147]

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Does Rubella have follow-up and, if yes, for how long?

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Also, please specify which (if any) epidemiological data fields are applicable to Congenital Rubella.

**Comment by hzi-braunschweig** [comment]
Rubella infection is diagnosed by detection of rubella IgM antibodies using ELISA assay.

Countries with high incidence test first for measles and negative specimens are then tested for rubella. Countries with low measles incidence  test the specimen for measles and rubella simultaneously.  . The Region is considering setting target date for rubella elimination.

**Comment by hzi-braunschweig** [comment]
Let's ask a question about measles for epi data. We can discuss this tommorow

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig That's not really an answer to the follow-up question. However, this made me realise that we also need to think about automatic case classification for CRS cases (we can add that later though). Could you please provide criteria for the automatic classification in the exact same style it's presented in the web app when you download the classification criteria document in the "About" section?

**Comment by bernardsilenou** [comment]
The text file has my suggestions. Follow up should be 21 days. we discuss in details today

[Bookshelf_NBK143264.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/3216016/Bookshelf_NBK143264.pdf)
[rubellaSummary.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/3216017/rubellaSummary.txt)

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig @bernardsilenou Please provide definitions for automatic case classification (suspect and confirmed) that are phrased like the ones already in the system (you can download the classification file in the About section of the web app).

**Comment by MateStrysewskeSym** [comment]
We need to talk about case classification for CRS (CDC also has an additional "Infection only" classification, WHO uses a completely different classification style).

**Comment by MateStrysewskeSym** [comment]
- [ ] Enable follow-up for CRS (21 days)
- [ ] Hide epi data tab for CRS cases
- [ ] Add automatic case classification rules for CRS (see attached document)

[cdcCRS.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/3231896/cdcCRS.pdf)

**Comment by MateStrysewskeSym** [comment]
- [ ] Print 1 as ONE
- [ ] The two ONE OFs have both to be displayed as sub xofs with an All Of parent

**Comment by MateStrysewskeSym** [comment]
- [ ] Replace "... when the case meets ALL OF the following requirements" to "... when the case meets the following requirements"
