### ISSUE TITLE
Unexpected error popup occurs while selecting Facility in New Activity as a Case

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11471]
### Problem Description

Unexpected error popup occurs while selecting Faciliy in New Activity as a case in a case's Epidemiological data tab on TEST-DE.

#### Steps to Reproduce

1. Login as a Admin User
2. Navigate to Cases
3. Go to created case
4. Go to Epidemiological data tab
5. Click on YES in Activity Details Known
6. Click on new entry button
7. Choose "Facility" from Facility selection list

#### Screenshots

![image](https://user-images.githubusercontent.com/105210214/217789765-2d028774-0b20-49cc-bb83-088cf2d89d9f.png)

Test passed before every time, failed on 09.02.2023
![image](https://user-images.githubusercontent.com/105210214/217804691-82de24dc-5445-4b96-8c80-5d0d5ae3e054.png)

#### System Details

* Device: Windows 10
* SORMAS version: Version: 1.80.0-SNAPSHOT (cf6272b)
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com/
* User Role: Admin

### Expected Behavior

No error messages should appear and Facility should be selected.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.80.0-SNAPSHOT(34ccc5b).
