### ISSUE TITLE
Annotate backend methods to save and delete user roles with user right annotations

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#11486]
### Bug Description

Annotate backend methods to save and delete user roles with user right annotations.
The annotations are missing from save and delete methods from UserRoleFacadeEjb.

- save requires UserRight._USER_ROLE_EDIT
- delete requires UserRight._USER_ROLE_DELETE

#### Steps to Reproduce

The bug related to the save was found before https://github.com/hzi-braunschweig/SORMAS-Project/issues/11476 was fixed.
After applying the template the user role was also saved but the user does not have edit rights. 

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
For QA purposes:
The above mentioned methods ( save and delete) can be tested with a Postman collection by calling:
 - save method without _USER_ROLE_EDIT right
 - deleted method without _USER_ROLE_DELETE right

**Comment by abrudanancuta** [comment]
Validated on test.de2 with the version: 1.80.0-SNAPSHOT (d6ffb94)
