### ISSUE TITLE
Requested pathogen test to be performed and requested additional test to be performed should not be required field

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1149]
In version 1.20, If the user who created the sample does not select these fields, the interface for the lab to register a test is missing. The interface for "new test result"  should always be displayed but in creating a new result, the user should specify the type of test he/she is creating the result for.

**Comment by MateStrysewskeSym** [comment]
- [ ] Always display pathogen and additional tests
- [ ] Request fields should not be required
