### ISSUE TITLE
NullPointerException in saveAndSnapshot for case created in the app

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1150]
This case is not present in the main database, therefore was created on the app and is still missing an embedded entity.

  | NullPointerException  - Root cause: java.lang.NullPointerException: Attempt to invoke virtual  method 'java.lang.Class java.lang.Object.getClass()' on a null object  reference - Stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:355  -> de.symeda.sormas.app.backend.caze.CaseDao:saveAndSnapshot:401  ->  de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:212  -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:65  ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:33 ->  android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Root cause stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:355  -> de.symeda.sormas.app.backend.caze.CaseDao:saveAndSnapshot:401  ->  de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:212  -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:65  ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:33 ->  android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Entity: Case: RMEKQS-GSBRRW-OB6Y37-AISWSELY -  User: ROMXFD-MIS7ZE-O4F6JS-EA6MSF5M - System:  https://sormas.org.ng/sormas-rest/
-- | --

**Comment by MartinWahnschaffeSymeda** [comment]
This can happen when we add a new embedded to an entity. When the user has not pulled yet, he will still have entities without the new embedded.

- [ ] allow saving of entities that don't have instances for all embedded
