### ISSUE TITLE
Change the upload file size limit on production instances

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#11505]
### Problem Description

This ticket was created only for tracking/testing purposes.

Currently the maximum upload file size limit on the production servers is 20MB ( default value).
On test-de,  test-de1,  test-de2, test-de3, test-auto the upload file size limit was changed to 60MB for this ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/11333

In order to be consistent, all the production servers should have the same, 60MB, maximum upload file size set.
On Netzlink side the following ticket was created for this task:  2023013766

When Netzlink will announce us that 2023013766 was finished, this ticket should be closed.

**Comment by carina29** [comment]
The upload size was adjusted on all the test instances.

**Comment by abrudanancuta** [comment]
Validated on test-de2 and test-de
