### ISSUE TITLE
[Events] Split event participant and person information into separate tabs in event participant pages [3]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11514]
### Feature Description

Currently, in the 'Events' directory there is no specific person page/tab. With the introduction of #6053 and #6052 cards of entities associated with the person were updated and added to entity person pages across directories, with the exception of the 'Events' directory.
 
As discussed when refining #11371  it has been decided to add the 'Event participant person' tab to events.

### Proposed Change

- [x] the new tab should be in the same style as the other person pages in SORMAS;
- [x] the heading for the tab should be between 'Event participant' and 'Event action';
- [x] the person related information from the person page should also be displayed on the 'Event participant person' tab (similar to the other entity person pages in SORMAS);
- [x] the tab should display the entity cards (similar to the other entity person pages in SORMAS);
- [x] on the 'Events' card displayed on the new tab, the event that was used to navigate to the 'Event participant person' tab should be highlighted; hide the edit icon for that specific entry (same behavior as in the other directories);
- [x] the cards should contain the edit/create buttons that were introduced with https://github.com/hzi-braunschweig/SORMAS-Project/issues/6053
- [x] 'Discard' and 'Save' buttons should be visible at the bottom of the page;
- [x] see that the navigation dirtyCheckPop-up is triggered when the user navigates from this tab without saving changes made on the tab;
- [x] see that when a user does not have edit rights (due to jurisdiction or user rights) for the event/event participant that the 'Event participant person' tab is included and is not editable (similar to the behavior in the other directories);
- [x] when the event and/or the event participant is archived, and the 'EDIT_ARCHIVED_ENTITIES' featuretype is set to 'false', the 'Event participant person' tab is also not editable;
- [x] when the event and event participant is shared via S2S the 'Event participant person' tab should be included;
- [x] replace event participant edit form in lab message processor with event participant create form

'Event participant' tab:
- [x] remove from the 'Event participant' tab the 'Person information' that is now displayed on the 'Event participant person' tab;
- [x] the following fields should continue to be displayed on the 'Event participant' tab:
![image](https://user-images.githubusercontent.com/96909231/219645119-d3d6e409-d492-4fbf-9a32-8436e748e9e6.png)
![image](https://user-images.githubusercontent.com/96909231/219645970-9ef971b6-e758-400d-b60d-81663cf30134.png)

- [x] the event participant ID (i.e. UUID) should be displayed below the heading and above the 'Responsible region' and 'Responsible district' fields;

### Acceptance Criteria

- the tab is implemented as described in the 'Proposed change';
- the field validations that are present on other person pages are maintained on the 'Event participant person' tab as well;

**Comment by MateStrysewske** [comment]
Note: This needs to be done by someone who has knowledge about lab messages because it impacts the lab message processing flow.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:

I:
1. Have the featuretype EDIT_ARCHIVED_ENTITIES set to false;
2. Log in the app and archive an event participant;
-> the side cards on the event participant tab are still editable.

II:
1. Have an event and event participant set in jurisdiction 1;
2. Save the URLs;
3. Log in with a user restricted to Jurisdiction 2;
4. Paste the URL of the event and of the event participant;
-> the side cards on the event participant tab are editable; the user can create entities but they are not displayed on the cards;

Expected behavior: The side cards should not be editable.

**Comment by adinaflorea9** [comment]
Disregard the above comment - the issue are believed t be related to #11509 and that ticket was reopened.
