### ISSUE TITLE
Unrelated persons suggested as duplicates during linelisting contact within a case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#11527]
### Bug Description

-Persons that are not similar are suggested during the creation of contacts within a case.

#### Steps to Reproduce

1. Open a case and line list about three contacts, use names such as 111, 222, etc
2. System sometimes suggests persons that do not share similar names or tell you that there are duplicate but the list is empty (See attached images below)

#### System Details

* Device: web
* SORMAS version: 1.81.0-snapshot (7e6f577)
* Android version/Browser:
* Server URL: https://test.sormas.netzlink.com/sormas-ui/#!about
* User Role: national user + admin

### Expected Behavior

- Only similar persons should be suggested
- Duplicate empty lists should not be shown  
- If this is caused by a low value for the name similarity threshold on the server, then it may be good to restrict its value within a range that will not result in the system suggesting persons that are not likely duplicates.
### Additional Information

1. Person's name is 222 222 and Aurelien is suggested as duplicate
![image](https://user-images.githubusercontent.com/12996724/220173996-1cd8f0ec-9896-42c1-a324-d8ea0b9da73b.png)

2. Person's name is 333 333 but random names suggested
![image](https://user-images.githubusercontent.com/12996724/220174736-1c481e48-2ca5-45ba-b094-db02d9b972f8.png)

3. Person's name is 555 but duplicate detection is triggered with an empty list
![image](https://user-images.githubusercontent.com/12996724/220174888-5bf813bd-8011-4a9c-bcfc-bb46f12ba659.png)

**Comment by MateStrysewske** [comment]
#8485 basically broke this. We now always consider fields like UUID and external ID for a similarity search, which makes sense when specifically searching for persons (e.g. in the person directory), but not when searching for similar persons as a result of a case creation or line listing.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.81.0-SNAPSHOT(862c1bd).
