### ISSUE TITLE
Uncheck "Adopt home address ..." when line listing contacts

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#11529]
### Problem Description

When line listing contacts, the checkbox "adopt home address of case person if they live in the same household" is selected by default. It is likely that users may forget to uncheck it when reporting contacts
### Proposed Change

Uncheck the icon by default
### Additional Information

![image](https://user-images.githubusercontent.com/12996724/220177737-8141ba51-e5a5-4047-94e4-3088d3f5baff.png)

**Comment by adinaflorea9** [comment]
@bernardsilenou the prechecking of this checkbox was specifically asked for in this ticket - https://github.com/hzi-braunschweig/SORMAS-Project/issues/7062. Given this, are you sure that it is desired for the checkbox to be unchecked?

Also, do you wish for that uncheck option to be added only for the international version of SORMAS? What about DE specific systems?

**Comment by bernardsilenou** [comment]
@adinaflorea9 @markusmann-vg 
- Generally, it's not a good practice to select optional data fields by default, users have to proactively check them if needed. It is better to have a missing record than a wrong record (likely to occur if a user forgets to uncheck the box, this happened to me)
- Since this was a request, then it would be good to contact the DE users if they agree with this change. I do not think it necessary to make it instance specific unless the DE users insist to keep it checked by default.
- The box is very important to be in all instances, but not to check it by default.

**Comment by adinaflorea9** [comment]
@SORMAS-SahaLinaPrueger @SORMAS-ChristopherMeyer given that the prechecking of that checkbox was requested in ticket #7062 created by Kay Watty, would would please be able to let us know if the change proposed by @bernardsilenou is suitable for DE systems?

**Comment by SORMAS-ChristopherMeyer** [comment]
Hey @bernardsilenou, are the changes you want covered by a specific project?

And I don't quite understand the problem. What is an imaginable situation where a contact lives in the same household but does not have the same home address?

**Comment by bernardsilenou** [comment]
@SORMAS-ChristopherMeyer 
- This ticket is not linked to any project I know, it's just a change that I think may be good to have.
- The issue is not that contacts live in the same household but do not have the same home address. The current implementation assumes that all contacts created through linelise lives in the same household (checkbox selected by default), which is not good because users will then be forced to uncheck the box each time they create contacts that are not in the same household (being the majority of the contacts)
- If the user forgets to uncheck the box when creating contacts that are not in the same household, then home addresses will be adopted from the source case and the user will not even be aware of it.
- The change is to not check the box by default

**Comment by bernardsilenou** [comment]
Maybe those who made the initial request https://github.com/hzi-braunschweig/SORMAS-Project/issues/7062 uses SORMAS to document mainly household contacts. But for instances that document all types of contacts, it's not a good idea

**Comment by MateStrysewske** [comment]
@bernardsilenou The address is only adopted for contacts for which the user specifies "Live in the same household" as relationship with case. I don't think there's any room for wrong records here because, as @SORMAS-ChristopherMeyer said, it's very safe to assume that people living in the same household actually share addresses. Any contacts created through line listing that have no or a different relationship with the case will be created with a clean address.

I'm therefore closing this issue. Feel free to continue the discussion if anything remains unclear.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
-  I now understand how the feature works from your last comment. 
- living in the same household implies the same address, thus the adoption is fine.
- I took it to be a global condition, just like disease, region and district, since it is placed at the top of the table and to be applied to all the records.  The text also does not contain the information that records with other categories for the `relationship with case` are not affected
- Maybe adding a tooltip connecting it to the attribute "relationship with case" would make it more explicit.

**Comment by MateStrysewske** [comment]
@bernardsilenou I honestly think the text contains exactly that information. Adding a tooltip that clarifies that probably wouldn't hurt though, I agree.
