### ISSUE TITLE
Fix certificate errors in payara

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1152]
We again have the problem that one of the expired certificates breaks the console.

**Comment by MateStrysewskeSym** [comment]
@faatihi You'll likely run into the same problem, please replace your cacerts.jks file in the config folder of your SORMAS domain with the file attached to this comment. You don't have to do this on the server, only on your local development system because you'll probably not get any console output otherwise.

[cacerts.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/3223802/cacerts.zip)

**Comment by faatihi** [comment]
Thanks. Will do
