### ISSUE TITLE
Error received at merge duplicate case

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11544]
### Problem Description
Error received at merge duplicate case

#### Steps to Reproduce

1. As NatUser+Admin go to Case directory
2. Click the More button
3. Select Merge duplicates
4. Confirm the pop-up
5. Confirm the filters

### Actual Behavior
An error message appears and no list of cases returned

#### Screenshots

![Screenshot 2023-02-23 at 15 16 33 (2)](https://user-images.githubusercontent.com/91872179/220933071-d7d7581f-f27d-44b2-89d9-45b522f6ed1f.png)

#### System Details

* Device:
* SORMAS version: 1.81.0-SNAPSHOT (e64c6fd)
* Android version/Browser:
* Server URL: test-de2, test-de
* User Role:

### Additional Information

[MergeCaseError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10814402/MergeCaseError.txt)

**Comment by sergiupacurariu** [comment]
This is an old bug that was brought to light by the override of the equals method in the AbstractUuidDto

**Comment by abrudanancuta** [comment]
Verified on local machine with the version: 1.81.0-SNAPSHOT (4afa45f)
