### ISSUE TITLE
SOP for new diseases

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1155]
- [x] define technical SOPS
- [x] adjust/add epidemiological SOPS

**Comment by MateStrysewskeSym** [comment]
We'll start to create a checklist with all the information we need from a technical point of view; HZI will then refine the SOP.

**Comment by MateStrysewskeSym** [comment]
@danieltomaba We have created a guide on GitHub that extensively explains what we need to get new diseases into SORMAS. I think you should discuss how to proceed on this matter with @MartinWahnschaffeSymeda during the next sprint review.

**Comment by MartinWahnschaffeSymeda** [comment]
Add column to define which lines are relevant for the disease (checkbox)
  - make it easy to filter the data dictionary to only fields that are relevant for the disease 
  -> easy review by other people and easy implementation
