### ISSUE TITLE
Case classification is not immediately updated after creating a case through positive pathogen test results

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11555]
### Bug Description

After creating a resulting case for a contact or an event participant, the case's classification is not updated when the case is saved. Rather, the message only appears if the user clicks save again on the case page, or on another page relaed to the case (such as if the user saves an updated on the person page).

#### Steps to Reproduce

1. Create a Covid-19 contact and add to it a sample with a positive final laboratory result and positive pathogen test result;
2. After saving the sample, click 'Yes' in the 'Create case from contact with positive test result?' pop-up;
3. Fill in the mandatory information in the 'Create new case' form and save the new case;
-> the case is saved, the sample with the positive result is on the case page, but the 'Case classification' is not yet updated.
4. Navigate to the 'Persons' directory, open the person associated with the case and the contact from the steps above, and save any change on the page.

#### Screenshots

![Case classification](https://user-images.githubusercontent.com/96909231/220365534-6a1ca43e-2853-4ebe-a8b3-904fb148382b.gif)

#### System Details

* Device: Windows 10
* SORMAS version: 1.80.0; 1.81.0
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Expected Behavior

The case classification should be updated when the case is saved.

### Additional Information

If similar steps are reproduced, but the user does not input the 'Final laboratory result', after saving the sample, a pop-up message appears:
![image](https://user-images.githubusercontent.com/96909231/220358199-aa22ce67-627f-442c-86e5-8c392b70cd4d.png)
Once the user clicks 'Yes' in that pop-up the sample is saved, and the case classification is updated. If the user then goes to click save on the case page, no error message appears.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the part for resulting cases of event participants was not fixed:
![image](https://user-images.githubusercontent.com/96909231/224318595-c69434f1-b7e4-43d3-a8cc-b9cab826e028.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(0cf1e0d).
