### ISSUE TITLE
Update the dependencies for openAPI generation [2]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#11553]
### Problem Description
While working on #10251, it became clear that we need to update the dependencies of the openAPI generation. This has been done as part of #11202, however, as this PR will not land soon, we need to extract the work done there to unblock #10251.

### Proposed Change

- [x] Extract all openAPI related changes from the POMs in #11202.
- [x] Make sure generation sill works.

**Comment by MartinWahnschaffe** [comment]
@JonasCir I have de-activated the ci job. For some reason it is triggered again and again, mixing the order of some of the fields:

https://github.com/hzi-braunschweig/SORMAS-Project/commit/d9ea5219b9a2e61d22f587e957595a5c70c9e3fb
https://github.com/hzi-braunschweig/SORMAS-Project/commit/c4528ae4bf4869a35fba4a7bdffe83deeaa658d9
...

Besides that the openapi canary is no longer working and needs to be updated as-well.
