### ISSUE TITLE
New "PERSON" sample association type is shown in the sample directory

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11564]
### Bug Description

#10714 has introduced a samples card to persons and has added a new sample association type for that purpose. However, this new association type is displayed as a new option in the sample directory (in the sample association type filter) without a caption and unconditionally.

While the value serves a purpose when entering the sample directory through a person by clicking on "See samples for this person", it should not be shown in other situations where no person association exists.

#### Steps to Reproduce

1. Open the sample directory
2. Open the dropdown associated with the sample association type ("All samples") and check its content

#### System Details

* Device: 
* SORMAS version: 1.81.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: localhost
* User Role:

### Expected Behavior

The new sample association type should not be shown in the dropdown when the user has not entered the sample directory through a person.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(afc87b7)
