### ISSUE TITLE
Penetration tests

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1157]

**Comment by MartinWahnschaffeSymeda** [comment]
Overview of the results:

3.1.1 Inadequate hardening of the system #1220
3.1.1.1 File System (CIS-CAT Chapter 1)
3.1.1.2 Network Configuration (CIS-CAT Chapter 3) 
3.1.1.3 Logging (CIS-CAT Chapter 4) 
3.1.1.4 Access, Authentication and Authorization (CIS-CAT Chapter 5) 
3.1.1.5 Operating System Configuration (CIS-CAT Chapter 6) 
3.1.1.6 Implementation of SELinux Rules for Payara

3.2 Findings Vulnerability Testing of Web Services
3.2.1 Cross-Site Scripting in Subpages #1215
3.2.2 Payara administration port unencrypted bound to the outside world #1216
3.2.3 Android app allows backup #1217
3.2.4 Old Payara server version#1192
3.2.5 Obsolete library #1198
3.2.6 Unsafe use of TLS/SSL #1218
3.2.7 Payara-Port bound to the outside world #1216
3.2.8 Default passwords in public setup#1122
3.2.9 Disclosure of the Content Management System #1218
3.2.10 Inappropriate use of the time zone #1219
3.2.11 Sensitive function accessible to all users -> Invalid finding
3.2.12 Missing use of security headers #1218
