### ISSUE TITLE
Add merge confirmation pop-up to contacts view and rephrase content [1]

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11596]
### Problem Description
At the moment when selecting Merge Case a confirmation pop-up appears informing user that the action can take a long time. 
This ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/9054 introduce a limit that user can use to retrieve the list of merging. Having the pop-up at this moment is also not consistent with Merge Contacts where the pop-up is not in place
![Screenshot 2023-03-07 at 13 49 44](https://user-images.githubusercontent.com/91872179/223428787-9d620c41-10ab-4a45-93bd-288f84bca903.png)

### Proposed Change
Since the performance issues should largely have been sorted out now, we should still keep the hint (in order to avoid users running into time-outs in situations where the performance is still bad), but change its text. Also, the hint should be added to the contact merge view for consistency reasons.

**Updated popup content:**

```
Calculating and displaying potential duplicates may take a lot of time under specific circumstances. It is recommended to use the filters on top of this view to reduce the number of cases that have to be compared at the same time, e.g. by choosing a narrow creation date interval and a low result count limit. If the potential duplicates are loading fast, extending these values should be safe.

In order to avoid performance issues when entering this view, potential duplicates are only loaded once you click on "Confirm Filters".
```

### Acceptance Criteria

- [x] The content of the pop-up has been changed to the text specified above
- [x] The same pop-up is also shown when entering the contact merge view.
  - [x] As in the case merge view, the pop-up is only shown when the user enters the view for the first time during their current session; afterwards it's not displayed anymore, but the user is still required to click on "Confirm filters" before the duplicates are loaded

**Comment by leventegal-she** [comment]
>  As in the case merge view, the pop-up is only shown when the user enters the view for the first time during their current session; afterwards it's not displayed anymore, but the user is still required to click on "Confirm filters" before the duplicates are loaded

In the case merge view after closing the warning popup for the fist time and later coming back to the merge view automatically loads the duplicates. Should this behaviour be changed to force the user to confirm the filters to load the duplicates as suggested in the acceptance criteria?

I would say not, once accepted and assumed that it will take long time to load the user should not be forced to click on the confirm button.

@abrudanancuta @MateStrysewske

**Comment by abrudanancuta** [comment]
I agree with your proposal @leventegal-she

**Comment by MateStrysewske** [comment]
@leventegal-she No, that's a mistake on my end then - the behaviour should be as in the case merge view, but there should not be any functional changes to the case merge view.

**Comment by adinaflorea9** [comment]
I am reopening the ticket for a small change: the message that is displayed when entering the 'Merge duplicate contacts' view mentions cases instead of contacts:
![image](https://user-images.githubusercontent.com/96909231/230428207-105d8aa8-769d-453a-8e7f-a52302bab175.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(3e23ad8).
