### ISSUE TITLE
S2S -  400 Error received when sharing a case with Case person having Home address 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11599]
### Bug Description
As NatUser+Admin having a Case with Case person which has at Home address Germany as country, cannot share the case with other health department.

#### Steps to Reproduce

1. Login as NatUser+Admin on test1402
2. Create a Case with mandatory data completed
3. At Case Person tab select Germany as country for Home Address
4. Share the case with LK Leer 

### Actual Behavior
A pop-up with 400 error code appears and the Case is not shared

#### Screenshots

![Screenshot 2023-03-07 at 15 33 04](https://user-images.githubusercontent.com/91872179/223452932-771f4605-b26f-4da9-be21-9c32bc000ce4.png)

#### System Details

* Device:
* SORMAS version: 1.80.0
* Android version/Browser:
* Server URL: test1402, release-sormas-x
* User Role: NatUser+Admin

### Expected Behavior
Case should be possible to be shared

### Additional Information

[Glassfish.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10941992/Glassfish.txt)

**Comment by leventegal-she** [comment]
Could not reproduce on local system with 1.80 and development version, nor on test systems like test-de1, 2,3.

I put in waiting until the next release.

**Comment by abrudanancuta** [comment]
Also a Netzlink ticket was created for further investigations, the ticket number is 2023020389

**Comment by aloesche** [comment]
Just reproduced this again with the following behavior:
- You can share a case from test1402 to LK Leer release-sormas-x if you remove "Deutschland" from case person tab (step 3)
- Exporting Infrastructure data from both systems show that they are equal on infrastructure level:

release-sormas-x | DEU | Deutschland | SubcontinentReferenceDto ad6da763-1194-5419-be74-f3379d3fd4b3 | 21000109 | 276 | Germany
-- | -- | -- | -- | -- | -- | --
test1402 | DEU | Deutschland | SubcontinentReferenceDto ad6da763-1194-5419-be74-f3379d3fd4b3 | 21000109 | 276 | Germany

release-sormas-x	DEU	Deutschland	SubcontinentReferenceDto ad6da763-1194-5419-be74-f3379d3fd4b3	21000109	276	Germany
[test1402](http://test1402.sormas.netzlink.com/)	DEU	Deutschland	SubcontinentReferenceDto ad6da763-1194-5419-be74-f3379d3fd4b3	21000109	276	Germany

**Comment by markusmann-vg** [comment]
@leventegal-she It can be reproduced on the mentioned environments where we have full access. Maybe my two screenshots help finding a solution
![Bildschirm­foto 2023-03-13 um 09 09 54](https://user-images.githubusercontent.com/62540178/224661741-4095ba80-d5ee-4c7a-b028-9c709d03b19e.png)
![Bildschirm­foto 2023-03-13 um 09 08 35](https://user-images.githubusercontent.com/62540178/224661743-b09bd06e-ab5e-499f-b6b4-890ef5ffbeaf.png)

**Comment by markusmann-vg** [comment]
I added the critical label as it blocks the rollout of 1.80

**Comment by abrudanancuta** [comment]
> 

The UUID from the table is belonging to the Subcontinent, which yes is the same for both environments. 

After having a check in the DB for the Germany Country the UUID seems to be different for test1402 and for release-x and release-de.

For test1402 the UUID is 6f51e20f-a727-5010-9b39-fef592fbe358, for release-x and release-de the UUID is 2c5c1849-9d24-5c63-beab-ddb0965c89d8. 

Having the UUIDs different between the system having S2S is causing the problem of 400

**Comment by abrudanancuta** [comment]
The problem was solved  by Netzlink ticket mentioned in above comments(2023020389) on test1402 by configuring the Germany country UUID with the same UUID that is used on the others release environments.
