### ISSUE TITLE
Exported files related to Configuration and Sample use toString instead of getCaption

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11606]
### Bug Description
Exported files contains Reference DTO for some UUIDS columns

#### Steps to Reproduce
1. As NatUser + Admin try to make some exports for Basic type reports

### Actual Behavior
The exported files contains some malformed UUIDS containing Reference DTO
The problem appears at the export entities:

- [x] Sample -> Basic Export
- [x] SubContinents Export
- [x] Countries Export
- [x] Region Export
- [x] District Export
- [x] Communities Export
- [x] Facilities Basic export
- [x] Point of entry Basic export

#### Screenshots

![image](https://user-images.githubusercontent.com/96909231/223716256-b6a47f08-84b4-4df3-9a6f-36869d3a5c4b.png)

#### System Details

* Device: Windows 10
* SORMAS version:1.80.0; 1.81.0
* Android version/Browser: Chrome
* Server URL: local machine; https://release-international.sormas.netzlink.com
* User Role: Admin+NatUser

### Expected Behavior
The exported files should not contain DTO reference as text

**Comment by carina29** [comment]
In case of the entities which extends ReferenceDto, the caption of the value will be displayed ( instead of caption.toString).
Entities which extends ReferenceDto: CaseReferenceDto, EventReferenceDto, ContactReferenceDto, CampaignFormDataReferenceDto, EventParticipantReferenceDto and so on.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(a40aa3a).
