### ISSUE TITLE
Show zero values filter in statistics should consider only records in specified date range

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#11602]
### Bug Description

When a user extract data with report date in range date1 and date1 and generate the epi curve, recorded that do not fall in the time interval are also plotted with zero values.

#### Steps to Reproduce

1. Extract covid cases  with report dates between December 15, 222 and January 31, 2023
2. Plot a bar graph and group by epi week of year
3. click on the filter: show zero values

#### Screenshots

![image](https://user-images.githubusercontent.com/12996724/223558437-9fdce0e7-967d-4481-b085-6b866e0f428d.png)

#### System Details

* Device:
* SORMAS version: 1.80.0
* Android version/Browser: 
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/#!about
* User Role: Admin + national user

### Expected Behavior

Only zero records within date1 and date2 should be shown, not the whole range of dates in the database

**Comment by abrudanancuta** [comment]
Validated on test-de1, test-de2 with the version: 1.83.0-SNAPSHOT (2c8f48b)
