### ISSUE TITLE
Remove case-related hint from final lab results card on samples dashboard

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11619]
### Bug Description

#11415 added a hint to the final laboratory results card on the surveillance dashboard that is very specific to cases. However, this hint is also shown on the samples dashboard where it doesn't make much sense.

#### System Details

* Device:
* SORMAS version: 1.81.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

### Expected Behavior

The hint is only supposed to be shown on the surveillance dashboard.

**Comment by leventegal-she** [comment]
Closing because it is resolved by https://github.com/hzi-braunschweig/SORMAS-Project/issues/10738

**Comment by adinaflorea9** [comment]
As this was fixed as part of #10738 - verified ticket after the commits for #10738 were on development - Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(f854b9c).

I did not close this ticket as duplicate as the removal of that hint was not directly specified in #10738 so we need this for tracking the changes.
