### ISSUE TITLE
[Event Actions] Error appears when clicking on 'Actions' if the user does not have 'Delete events from the system' right

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11638]
### Bug Description

An error message appears when a user who does not have delete event rights clicks on the 'Actions' button at the top of the events directory.

#### Steps to Reproduce

1. Create a user with the following rights regarding events (the behavior is reproducible in any combination of rights that does not include the 'Delete events from the system'):
![image](https://user-images.githubusercontent.com/96909231/224752456-07fdd638-929c-489f-8011-e1c7c64ab20f.png)

2. Log in with the user created at step 1 and click on the 'Actions' tab of the 'Events' directory.

### Actual Behavior

An error message appears:
![image](https://user-images.githubusercontent.com/96909231/224749388-efc0b32c-f501-43a1-a99b-381532595bc3.png)

**Logs from the local machine:**
[Error Actions .txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/10959108/Error.Actions.txt)

### Expected Behavior

No error message should appear. 

#### System Details

* Device: Windows 10
* SORMAS version: 1.80.0; 1.82.0-SNAPSHOT(6dc0dba)
* Android version/Browser: Chrome
* Server URL: local machine, https://test1402.sormas.netzlink.com/ and https://test-de2.sormas.netzlink.com/
* User Role: Admin+NatUser; User configured - has all of the rights except for 'Delete events from the system'  and 'Work with messages'.

**Comment by rdutu-vg** [comment]
Automation task created to cover this defect:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11641

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.82.0-SNAPSHOT(e6522e6).
