### ISSUE TITLE
Use dependency review action [0.5]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#11658]
### Problem Description
We do not have a mechanism which prevents insecure dependencies from flowing in into our code base. We want to be able to reliable audit new dependencies to catch security risk as early as possible.

### Proposed Solution
Use the [dependency-review-action](https://github.com/actions/dependency-review-action#readme) developed by GitHub to stop the described problem from occurring in the future.

### Possible Alternatives
None, we should really take care of this.

### Additional Information
[here](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review) and [here](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review).

**Comment by MartinWahnschaffe** [comment]
Not clear how this differs from what Trivy is already doing.

**Comment by JonasCir** [comment]
@MartinWahnschaffe I just tested it on the PR and I would actually keep the action. It is super fast and it makes the insecure addition of vulnerable dependencies explicit, whily Trivy might fail for insecure dependencies or other things...

**Comment by JonasCir** [comment]
So in the current PR, the dependency review action catched the problem trivy did not
