### ISSUE TITLE
S2S - Merge pop-up error - When trying to merge 2 cases a pop-up error appears

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11689]
### Bug Description

Have 1 case in read only mode(received from a source system). Have 1 case identically in target system with the one received. Try to make the merge on the case from the target system. At this point an error appears

### Reproduction Steps

1. As system A send a case without ownership to system B
2. In system B have a case identically with the case from system A
3. Accept the case from system A
4. Go in the Merge duplicate cases
5. Search for the cases above
6. Try to make the merge on the case from system B

### Expected Behavior

No error message should appear. A warning message should appear that the other case that you want to merge with has read only rights on it and is not possible

### Affected Area(s)

Web app

### SORMAS Version

1.80.0

### Android version/Browser

-

### User Role(s)

NatUser+Admin

**Comment by leventegal-she** [comment]
The server error will be solved by https://github.com/hzi-braunschweig/SORMAS-Project/pull/11742 but I'm not sure the merge should be blocked.

After the fix, the case form system B is updated with data from the readonly on, and the second gets  deleted.
This seems correct to me given the fact that also readonly cases can be deleted.

If the merge should be blocked for this scenario, then a new change request should be created and refined.

**Comment by abrudanancuta** [comment]
Validated on test-de1 and test-de2 with the version: 1.82.0-SNAPSHOT (2864773)
