### ISSUE TITLE
Transmission chain visualization prototype

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1168]
Proposed solution: Use R to build the transmission chain. Setup R on the SORMAS server and call the created R script from the SORMAS backend. The script will provide a png, svg or html/json that is supposed to be visualized on the dashboard.

See also: ~~http://www.rforge.net/JRI/~~ -> seems to be quite old and not maintained.

### Server

- [x] Install R
- [x] Install libraries: epicontacts, outbreaks (later only needed for test script). Windows: Use cmd with admin rights
```
install.packages(c("epicontacts"))
install.packages(c("outbreaks"))
```
- [ ] Define how to set this up on linux
- [ ] Extend setup script & manual

### Backend

- [x] Add config to define where the R executable is located on the system
- [x] Add a backend method to generate the chart JSON for vis/visNetwork using the example script:
```
library(epicontacts)
library(outbreaks)
merskor15 <- make_epicontacts(linelist = mers_korea_2015$linelist,
                              contacts = mers_korea_2015$contacts,
                              directed = FALSE)
g <- plot(merskor15)
htmlwidgets::saveWidget(g, "test.html", selfcontained = FALSE)
```
- [ ] Replace the script with the transmission chain script provided by HZI

### UI

- [ ] Add a transmission chain component with the needed javascript dependencies. See example file: 
[RVisExample.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4250568/RVisExample.zip) / files generated by the script
- [ ] Add the component to the contact dashboard -> replace the map

**Important**: It's possible that we will have to fall back to png output for the first version of the chain.

**Comment by MartinWahnschaffeSymeda** [comment]
Example of a chart generated by R: [Documents.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4250524/Documents.zip)

**Comment by bernardsilenou** [comment]
Please install the following packages also: 
library(GGally)
library(network)
library(sna)
library(ggplot2)
library(RColorBrewer)
library(plotly) #☺ for interactive graphs

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  Attached is the first version of the network script and a txt file explaining how to run it. It work on my system.

**Comment by HolgerReiseVSys** [comment]
@bernardsilenou Could you send teh source code of the the r functions instead of, or in addition to, the compiled ones in the future? That would simplify debugging.

**Comment by HolgerReiseVSys** [comment]
Installing R in Ubuntu:
```bash
sudo apt install libpq-dev
sudo apt install r-base
sudo /usr/bin/R
```
```r
install.packages(c("epicontacts", "outbreaks", "RPostgreSQL", "GGally", "network", "sna"))
```

Enable network diagrams by specifying the Rscript executable in `sormas.properties`:
```properties
rscript.executable=/usr/bin/Rscript
```

**Comment by MateStrysewskeSym** [comment]
The transmission chains need to take the date filter on the dashboard into account, using the following logic:

If ANY contact of a transmission chain is/was active in the specified time frame, display the whole transmission chain.

An "active" contact is defined as follows:

* The contact report date is less than or equal to the start date of the specified time period **AND**
* The follow-up until date is greater than or equal to the end date of the specified time period

In addition, the contact user filter needs to be applied to the script that retrieves the transmission chains as well. Also, we probably need to update the user filter, e.g. by adding the contact person's address when determining which contacts a user is allowed to see.

**Comment by bernardsilenou** [comment]
Suggestion for improvement of transmission chain:
1. Place node in a hierarchical manner based on date of last contact with case. This should be possible for the whole network diagram and for a single transmission chain.
2. Linking the node to the case or contact data such that when a user click on the note, the case data should open. Users should be able to navigate from contact data to the network diagram.
3. Add filters the network diagram by id, case classification, etc
4. Prevent nodes from being so flexible

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I'll try to take care of some of the points I've noted above. Let's talk about how to proceed with this topic tomorrow.

**Comment by MartinWahnschaffeSymeda** [comment]
TODO: Create new issue for the further refinement of the transmission chain

**Comment by MartinWahnschaffeSymeda** [comment]
Futher work done in #1563
