### ISSUE TITLE
[Tasks] Deleting a task after saving changes on it leads to an error message appearing when trying to open it as it is not immediately deleted from the UI

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11681]
### Bug Description

When editing anything on a task form, then clicking 'Delete' the 'Unsaved changes' pop-up is triggered. If the user saves the new changes and then deletes the task, the task is still displayed in the 'Tasks' card. If the user tries to click on it, an error message appears.

The behavior is reproducible for tasks associated with cases, contacts, events and travel entries if the tasks are opened from the associated entity's page (i.e. the case page, the contact page).

### Reproduction Steps

1. Open an existing task from the page of a case, contact, event or travel entry;
2. Make any change on the task form;
3. Click 'Delete';
4. Click 'Save changes' in the 'Unsaved changes' pop-up that appears;
5. Click 'Yes' in the 'Confirm deletion' pop-up that appears;
6. Observe the 'Tasks' card where the task is still listed and click on it.

Actual behavior:
The task is not immediately deleted from the UI and when the user clicks on it an error message appears:
![image](https://user-images.githubusercontent.com/96909231/225927854-86260534-f26f-48ab-8d18-811b11687602.png)

The task is removed from the UI only if the user refreshes the page or clicks 'Save' at the bottom of the entity page.

**Logs from the local machine server at the time of the error:**
[Task error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11002192/Task.error.txt)

### Expected Behavior

Just as in the case of the other tasks that get deleted from the entity pages, the task should immediately be removed from the UI.

### Affected Area(s)

Web app

### SORMAS Version

1.82.0; 1.80.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine; https://test1402.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
I'll discard this bug as irrelevant. This is a very unlikely scenario and a bug that doesn't cause any actual harm, and given that we will have to move away from Vaadin 7/8 at some point in the future, I don't belive we need a fix for this.
