### ISSUE TITLE
[Event participants] Filtering event participants based on 'Final laboratory result' seemingly leads to a loop 

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11699]
### Bug Description

When having an event participant with multiple samples, with multiple 'Final laboratory results' that are identical, filtering the event participants based on 'Final laboratory result' seems to lead to a loop and the filtering is not done.

**Please note that the behavior can be reproduced for all the values possible for the 'Final laboratory result' of samples' an they should all be addressed in the ticket.**

### Reproduction Steps

I:
1. Logged in with an Admin+NatUser create a Covid-19 Event;
2. Add 2 event participants to that event;
3. For event participant 1 create multiple samples (1 with the final laboratory result pending; 1 with the final laboratory result positive; and 1 with the final laboratory result positive and a pathogen test with the test result positive); 
4. Filter the event participants based on the 'Final laboratory result' - value 'Positive'.

Actual behavior: No error is shown in the logs or the UI and the loading spinner is just continuously displayed.

II:
1. Repeat the same steps from part I up to step 2;
2. For one event participant create at least 2 samples with the 'Final laboratory result' set to Pending;
3. For the other event participant create one sample with the 'Final laboratory result' set to 'Pending' and one with the value 'Positive';
4. Filter the event participants based on 'Final laboratory result' - value 'Pending'.

Actual behavior: No error is shown in the logs or the UI and the loading spinner is continuously displayed.

### Expected Behavior

The filtering should get done based on the value selected.

### Affected Area(s)

Web app

### SORMAS Version

1.80.0; 1.82.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine; https://release-international.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
@adinaflorea9 Let's wait for #11697 to be merged; it's possible that this issue will be fixed by my solution there.

**Comment by adinaflorea9** [comment]
@MateStrysewske alright! I'll keep an eye on them and see how the behavior is after #11697  is fixed.
