### ISSUE TITLE
[Events] Event participants get multiplied and one disappears when adding multiple samples to the same event participant

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#11697]
### Bug Description

Event participants get multiplied and one of them disappears when adding multiple samples to the same event participant.

### Reproduction Steps

1. Logged in with an Admin+NatUser create a Covid-19 Event;
2. To the event from step 1, add 2 event participants (eg. Jake Jones and Gregory Smith);
3. To the latest event participant add 2 samples (1 sample with the 'Final laboratory result' set to 'Pending'; one sample with the 'Final laboratory result' set to 'Positive');
4. Observe the list of event participants after saving the latest sample.

Actual behavior: The event participant to which the samples were added to gets listed twice and the other event participant created at step to is no longer listed in the grid. The person associated with the second event participant that is no longer listed exists in the 'Persons' directory and on its person page it is visible clearly that it is still an event participant in the respective event.

**NOTE:** This only happens when the samples have the EXACT SAME date and time (e.g. current date, no time).

GIF of the steps and the behavior:
![Event participants](https://user-images.githubusercontent.com/96909231/226357969-c5e78b13-4263-4e56-a56f-e3c77f8ff61a.gif)

### Expected Behavior

The event participants should not get duplicated when multiple samples are added to them. Also, the other event participants listed should not disappear from the event participants grid as long as they are linked to that event.

### Affected Area(s)

Web app

### SORMAS Version

1.80.0; 1.82.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine; https://release-international.sormas.netzlink.com/

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version:1.82.0-SNAPSHOT (4f77f37)

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version:1.82.0-SNAPSHOT (4f77f37)
