### ISSUE TITLE
Add diseaseVariant determination to LabMessages

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#11704]
### Feature Description

When a lab message (ExternalMessage with type LabMessage) is saved, it should be determined whether the lab message has a DiseaseVariant and if so, which one.

### Added Value/Benefit

The determined DiseaseVariant and its details can then be automatically pre-filled when processing the message.

### Acceptance Criteria

- [x] Determine DiseaseVairant
- [x] Only LabMessages are handled
- [x] Details are also adopted

### Implementation Details

When a lab message (ExternalMessage with type LabMessage) is saved, all TestReports should be examined to see if there is a single variant that has a positive test result. This variant is then set at the ExternalMessage. In this case the DiseaseVariantDetails are also taken over.

### Additional Information

This feature was originally intended to be implemented in the Sormas-Demis adapter ([#80](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/80)), but is now implemented in Sormas for simplicity.

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version: 1.82.0-SNAPSHOT (4f77f37)
