### ISSUE TITLE
Delete buttons are enabled for entities outside the user's jurisdiction

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11710]
### Bug Description

#11509 has introduced logic that enables the delete button even if the user does not have edit rights for the respective entity. However, we now face the situation that the delete button is enabled even if the entity is outside the user's jurisdiction; in this case, a backend check would prevent the deletion and an error message is displayed (except for campaign forms and event actions).

### Reproduction Steps

1. Create user A that is assigned to a jurisdiction and has e.g. the delete cases right, but NOT the edit cases right
2. Create a case outside the user's jurisdiction with user B (e.g. an admin/national user)
3. Open the case with user A; the case should be read-only, but the delete button is enabled
4. Try to delete the case; an error message appears informing the user about the case not being in their jurisdiction

### Expected Behavior

The delete button should not be enabled if the user would not be able to delete the entity in the first place, i.e. we need to check whether it is in the user's jurisdiction or owned by the user on UI level and disable the button if it's not.

### Affected Area(s)

Web app

### SORMAS Version

1.82.0

### Android version/Browser

Any browser

### User Role(s)

e.g. Surveillance Supervisor

### Server URL

localhost

**Comment by adinaflorea9** [comment]
@MateStrysewske Limited disease users can delete entities that are not within their 'disease jurisdiction' on both the released version 1.80.0 and on 1.82.0 - could that be addressed in this ticket as well?

**Comment by MateStrysewske** [comment]
@adinaflorea9 I would prefer to have that in a separate bug issue because it's an individual malfunction.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as in the case of event actions and campaign data forms the 'Delete' button is still enabled for users that are restricted by a jurisdiction different than the jurisdiction of the entity.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(30309b9) and on https://test-de2.sormas.netzlink.com/ and https://test-de1.sormas.netzlink.com/ - 1.83.0-SNAPSHOT(7ab1cd5).
