### ISSUE TITLE
[Merge] Searching for name results in error message

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#11712]
### Bug Description

The case merge options also include search fields for case id, event id, EPID id and description. If you want to search for a name in field "description" a error messages appear. After confirmation of the error messages it is not possible to perform any operation in "merge duplicate cases" screen. After returning to cases and access menu "merge duplicates" it is possible to perform a new search. Also the button "Reset Filters" is not working after displaying of potential duplicates.

If the search term is not deleted after returning to case directory it is not possible to access menu "Merge Duplicates" again. The same error message appears after trying to access merge menu.

### Reproduction Steps

1. Login into SORMAS
2. Go to "Cases"
3. Case directory opens. Click on button "More" and choose "Merge Duplicates"
4. Merge Duplicate Cases Menu is displayed. Confirm message with title "Caution" with button "Okay"
5. Go to field "Event: ID, title, description" and enter any value (letter or number) and click on "Confirm Filters"
6. Error message appears: An error occured. An unexpected error occured. Please contact your supervisor or administrator and inform them about it.
7. Decline error message by clicking on "X"
8. Delete value in field "Event: ID, title, description" and click again on "Confirm Filters" again
9. Nothing happens. Click on button "Back to Case directory"
10. Click again on button "More" and choose "Merge Duplicates"
11. Merge Duplicates Menu is displayed with search results of potential duplicates as choosed before.
12. Enter again a value in field "Event: ID, title, description" and click on "Confirm Filters"
13. Error message appears. Apply it with click on "X"
14. Leave value in field and return to case directory.
15. Click again on utton "More" and choose "Merge Duplicates"
16. Error message appears again. Case duplicate menu does not open.

### Expected Behavior

If in field "Event: ID, title, description" contain a value the search should look for values in SORMAS according to the search term. In search field "ID, EPID number, external ID" it is possible to perform a search when enter a value.

### Affected Area(s)

Web app

### SORMAS Version

Version 1.80.0, sormas-demis-adapter 1.25.0, ifsg-converter 15.0.0

### Android version/Browser

Microsoft Edge

### User Role(s)

Admin

### Server URL

https://test1402.sormas.netzlink.com/

### Additional Information

![image](https://user-images.githubusercontent.com/91321821/226903366-2ba201b8-b837-4930-aacf-2bc71bfe2f4c.png)

![image](https://user-images.githubusercontent.com/91321821/226904140-db406668-8256-4309-bf95-65a397a782c4.png)

**Comment by MateStrysewske** [comment]
The problem here is that #9054 has introduced functionality that makes it impossible to search for duplicates by any event-related information for technical reasons (i.e. the performance improvements only work because of this restriction). 

I'll remove the event search field in this issue, and open a follow-up investigation issue in which we'll have to check whether we can reintroduce it.

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version: 1.82.0-SNAPSHOT (4f77f37)
