### ISSUE TITLE
Community gets displayed with reference instead of entered value

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#11752]
### Bug Description

During entry of a previous hospitalization in SORMAS the community of the accorded district get displayed as the community reference. 

### Reproduction Steps

1. Login into SORMAS
2. Go to Cases
3. Choose a case
4. Got to tab "hospitalization"
5. Scroll down to section "Previous Hospitalizations"
6. Click on section "Was the patient hospitalized or did he/she visit a health clinic previously for this illness" on "Yes"
7. Previous hospitalization open. Choose "new entry"
8. Click on section "Was patient admitted at the facility as an inpatien"? on button "Yes"
9. Enter date of admission
10. Enter date of discharge or transfer
11. Choose a region, district, community and hospital "other"
12. Enter Facility name & description
13. Isolation can be leaved blank
14. Choose on dropdown "Reason for hospitalization" the entry "Reported disease"
15. Stay in intensive care unit can be leave blank.
16. Field "Description" can be leave blank.
17. Click on button "Done"
18. Entry is displayed as in attached picture

![image](https://user-images.githubusercontent.com/91321821/228277309-a510929b-c95c-474d-9f6b-3f8bceff7aa2.png)

### Expected Behavior

Community should be displayed as entered in fields before.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.80.0

### Android version/Browser

Edge

### User Role(s)

Admin

### Server URL

https://test1402.sormas.netzlink.com/

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(2955602).
