### ISSUE TITLE
[Sample Dashboard] Purpose of sample labels get truncated on medium sized screens

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#11756]
### Bug Description

The labels on the boxes under "Purpose of Sample" section are truncated on mid and small sized screens

### Reproduction Steps

1. Open the Sample dashboard
2. Make the browser window narrower then 1500 pixels 
3. Observe the "Purpose of Sample" section

### Expected Behavior

The labels are not truncated

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.82.0

### Android version/Browser

Google Chrome

### User Role(s)

National User

### Additional Information

Currently looks like a screenshot below
![image](https://user-images.githubusercontent.com/62599627/228510601-61b4648b-6e44-4409-ab7a-6380aec0e7ed.png)

Just making the label to split into multiple lines makes it looking strange
![image](https://user-images.githubusercontent.com/62599627/228512132-e1b70e12-5c5f-4d85-be2e-b99e778bde1a.png)

So the section must be enlarged and also the font size of the label should be made smaller

**Comment by MateStrysewske** [comment]
@leventegal-she I'd still let the label split into multiple lines as a fall-back because this WILL be necessary on very small screens with certain languages (e.g. German has significantly longer captions than English).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(44bfee6).
