### ISSUE TITLE
Demis - Create a script to re-establish connection between Sample and External Message 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11763]
### Problem Description

On test-de2, test1402 some Sample lost the connection with the lab message. The same problem appeared in production for some health departments. The reason to have this script is because the problem cannot be reproduced with new data. Only Sample belonging to the year 2022 seem to be affected

### Proposed Solution

The script will re-establish the connection for the most of the Samples

### Additional Information
The script should be run on a specific date range: 29.11.2022 - 06.12.2022
This represents the report date, from the lab message.

**Comment by leventegal-she** [comment]
Prepared some scripts fro verifying and restoring links
``` sql
-- ---------------- VERIFY MISSING LINK ----------------
select count(sr.id) from samplereport sr
                     inner join externalmessage em on sr.labmessage_id = em.id
where
    sr.labsampleid IS NOT NULL
  and sr.labsampleid <> ''
  and em.status = 'PROCESSED'
  and sr.sample_id is null
  and exists(select s.id from samples s where s.labsampleid = sr.labsampleid);
-- ---------------- VERIFY MISSING LINK ----------------

-- ---------------- RESTORE BY HISTORY ----------------
BEGIN;
UPDATE samplereport sr
SET sample_id = (SELECT srh.sample_id FROM samplereport_history srh
                 INNER JOIN samples s on s.id = srh.sample_id
                 WHERE srh.id = sr.id
                   AND srh.labsampleid = sr.labsampleid
                   AND srh.sample_id IS NOT NULL
                 ORDER BY srh.sys_period DESC
                 LIMIT 1)
WHERE sr.sample_id IS NULL
  AND sr.creationdate BETWEEN '2022-11-01' AND '2022-12-06';
COMMIT;
-- ---------------- RESTORE BY HISTORY ----------------

-- ---------------- RESTORE BY labsampleid ----------------
BEGIN;
UPDATE samplereport sr
SET sample_id = (SELECT s.id FROM samples s
                 WHERE s.labsampleid = sr.labsampleid
                 ORDER BY s.creationdate DESC
                 LIMIT 1)
FROM externalmessage em
WHERE
    em.id = sr.labmessage_id
    AND em.status = 'PROCESSED'
    AND sr.sample_id IS NULL
    AND sr.labsampleid IS NOT NULL
    AND sr.labsampleid <> ''
AND sr.creationdate BETWEEN '2022-11-01' AND '2022-12-06';
COMMIT;
-- ---------------- RESTORE BY labsampleid ----------------
```

**Comment by leventegal-she** [comment]
After doing some investigations on **test-de2** and **test1402** has been clarified that we can drop option the restore using history tables.

The missing links can be verified using:
```sql
select (SELECT s.id FROM samples s
                 WHERE s.labsampleid = sr.labsampleid
                     AND (s.deleted IS NULL OR s.deleted = false)
                 ORDER BY s.creationdate DESC
                 LIMIT 1)
FROM samplereport sr
JOIN externalmessage em on em.id = sr.labmessage_id
WHERE
    em.status = 'PROCESSED'
  AND sr.sample_id IS NULL
  AND sr.labsampleid IS NOT NULL
  AND sr.labsampleid <> ''
  AND sr.creationdate BETWEEN '2022-11-29' AND '2022-12-06';
```

The links can be restored using the following script:

```sql
BEGIN;
UPDATE samplereport sr
SET sample_id = (SELECT s.id FROM samples s
                 WHERE s.labsampleid = sr.labsampleid
                   AND (s.deleted IS NULL OR s.deleted = false)
                 ORDER BY s.creationdate DESC
                 LIMIT 1)
FROM externalmessage em
WHERE
        em.id = sr.labmessage_id
  AND em.status = 'PROCESSED'
  AND sr.sample_id IS NULL
  AND sr.labsampleid IS NOT NULL
  AND sr.labsampleid <> ''
  AND sr.creationdate BETWEEN '2022-11-29' AND '2022-12-06';
COMMIT;
```

@MartinWahnschaffe @MateStrysewske Can you please have a look on the above scripts and give a feedback if you see some filter conditions I missed or if you see any problems that running the restore script would cause?

**Comment by AliciaRaber** [comment]
I would propose following change
AND em.messagedatetime BETWEEN '2022-05-26' AND '2022-05-27'

**Comment by MartinWahnschaffe** [comment]
@leventegal-she Looks good to me.

**Comment by leventegal-she** [comment]
After having a feedback on the above queries and some more investigations here is an improved query that takes into account the test type together with the lab sample id.

* Verify possible link between demis message and sample
```sql
select em.uuid AS external_message_id, (SELECT s.uuid
                 FROM samples s
                          LEFT JOIN pathogentest p on s.id = p.sample_id
                 WHERE s.labsampleid = sr.labsampleid
                   AND p.testtype = tr.testtype
                   AND (s.deleted IS NULL OR s.deleted = false)
                 ORDER BY s.creationdate DESC
                 LIMIT 1) as sample_id
FROM samplereport sr
         JOIN externalmessage em on em.id = sr.labmessage_id
         JOIN testreport tr on tr.samplereport_id = sr.id
WHERE em.status = 'PROCESSED'
  AND sr.sample_id IS NULL
  AND sr.labsampleid IS NOT NULL
  AND sr.labsampleid <> ''
  AND em.messagedatetime BETWEEN '2023-04-14 00:00:00.000' AND '2023-04-14 23:59:59.999';
```

* Restore the links the above query generated
```sql
BEGIN;
UPDATE samplereport sr
SET sample_id = (SELECT s.id
                 FROM samples s
                          LEFT JOIN pathogentest p on s.id = p.sample_id
                 WHERE s.labsampleid = sr.labsampleid
                   AND p.testtype = tr.testtype
                   AND (s.deleted IS NULL OR s.deleted = false)
                 ORDER BY s.creationdate DESC
                 LIMIT 1)
FROM externalmessage em
         JOIN samplereport sr1 on em.id = sr1.labmessage_id
         JOIN testreport tr on tr.samplereport_id = sr1.id
WHERE em.id = sr.labmessage_id
  AND em.status = 'PROCESSED'
  AND sr.sample_id IS NULL
  AND sr.labsampleid IS NOT NULL
  AND sr.labsampleid <> ''
  AND em.messagedatetime BETWEEN '2023-04-14 00:00:00.000' AND '2023-04-14 23:59:59.999';
COMMIT;
```

**NOTE:** Please change the date interval as you prefer
**NOTE 2:** This query works best with samples resulted by processing a single demis message

**Comment by abrudanancuta** [comment]
The scenarios that were tested:
1. A lab message coming with 1 Sample and 2 Pathogen test. After processing the lab message will be: 1 Case + 1 Sample + 2 Pathogen tests. Sample connected to Lab message 
2. A lab message coming with 3 Samples: 1 Sample has 2 Pathogen tests, and the other 2 Samples have each 1 Pathogen test. The samples have different UUIDs, the pathogen tests have different UUIDs. After processing the lab message will be: 1 Case with 3 Samples. Sample1 has 2 Pathogen tests and 1 connection to Lab message. Sample2 has 1 Pathogen test and 1 connection to Lab message. Sample3 has 1 Pathogen test and 1 connection to Lab message
3. A lab message coming with 1 Sample  with 1 Pathogen test. After processing the lab message will be: 1 Case + 1 Sample + 1 Pathogen test. Sample connected to Lab message 
4. Two Lab message coming, each of them with the same Sample UUID. In each lab message there is a Pathogen test but has different UUID. When processing the 2nd lab message it will be picket the same person, the same case, the same sample as for the 1st lab message processed. At the end of the process it will be 1 Case, 1 Sample with 2 Pathogen tests in, and the Sample will be connected to 2 Lab messages 
5. Two Lab messages, each of them having different Sample UUID, different Pathogen test. When processing the 2nd lab message it will be picked the same person, the same case, new sample. At the end of the process it will be 1 Case, 2 Samples each of them having 1 Pathogen test. Each sample will be connected to 1 Lab message

OBS: Each scenario has a different person in the lab message

One problem observed: 
The scenario 2: when trying to establish back the connection, for the Sample3 it is not done, it remains without lab message link. The other samples have back the connection to the lab message.
The scenario 2 should not occur because the problem with missing lab message link was observed before having this feature of processing multiple samples in one lab message.
