### ISSUE TITLE
[Messages] Search field for selected search don't apply

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#11790]
### Bug Description

The health department of Bayreuth reported that the search field "Select a different person" do not display.

### Reproduction Steps

1. Login into SORMAS
2. Go to menu "Messages"
3. Search for an unprocessed messages
4. Click on button "Process"
5. Processing starts. Click on checkbox "Select a different person"
6. Search fields open "first name, last name, year of birth, month of birth, day of birth" followed by buttons "Reset" and "Search"
7. You can enter specific data in order to lookup for persons (e.g. preventing duplicates in system)

### Expected Behavior

If you click on the checkbox the fields should appear.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.80.0

### Android version/Browser

Chrome

### User Role(s)

Admin

### Server URL

gesundheitsamt-bayreuth.sormas.bund.de

### Additional Information

![image](https://user-images.githubusercontent.com/91321821/229777010-fbfd4545-bab2-4179-b102-c12544ad6366.png)

I have check this issue via Webex conference and have seen that the option is not available.

**Comment by leventegal-she** [comment]
> I have check this issue via Webex conference and have seen that the option is not available.

This means that the `PERSON_DUPLICATE_CUSTOM_SEARCH` feature is not activated on that system.
Please check with netzlink and activate it.

I've tested the search with the feature activated on my local system, test-de2 and test1402 and I was able to search for persosns.
