### ISSUE TITLE
A problem with required field occurred during creating immunization

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11808]
### Problem Description

While creating immunization I filled a required field (MELDEDATUM is the only one required field in the immunization form) and even more fields and I couldn't save the immunization due to a problem that occured with following description "A problem occured. immunization: This is a required field.". Please take a look at the screenshot:
![image](https://user-images.githubusercontent.com/105210214/230557308-1371ba93-b67d-4ef5-80d1-9344bf95dc1d.png)

### Reproduction Steps

1. Login as a Admin User on test-de
2. Create a new case
3. Click on "New immunization" button ('new vaccination' as the form from the picture is of the reduced immunization module)
4. Fill required field in immunization form
5. Save immunization (vaccination)

### Expected Behavior

Immunization is saved without any error, or additional required field is marked as a required.

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.83.0-SNAPSHOT (925c5e5)

### Android version/Browser

Chrome

### User Role(s)

Admin; Admin+NatUser

### Server URL

https://test-de.sormas.netzlink.com/

### Additional Information
Logs from the local machine:
[logs vaccination.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11178614/logs.vaccination.txt)

**Comment by MateStrysewske** [comment]
For documentation purposes: This was caused by #4959 in this iteration.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(3a8565d) - using both the full immunization module and the reduced immunization module.
