### ISSUE TITLE
Add ReST endpoint to provide effective user rights of a user [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#11818]
### Feature Description

Add a ReST endpoint to provide the user rights of a user based on the user's uuid.

### Added Value/Benefit

A client can easily find out which user rights a user (especially the current one) has without having to check and retrieve all user roles.

### Acceptance Criteria

- [x] Calling the endpoint returns the effective user rights of a single user based on its UUID
- [x] When no UUID is passed, the user rights of the current user are returned
- [x] The endpoint returns a `List<UserRight>`
- [x] User rights are checked (ideally use existing backend methods).
- [x] A unit test covers the backend method logic

### Implementation Details

Suggestion: Add UserResource.getUserRights with url users/rights/{uuid}. 

### Additional Information

I've also added the full UUID of the user to the user edit form, as well as the UUID of the currently logged in user to the user settings popup.

**Comment by carina29** [comment]
Existing scenarios ( for testing):

- 1)  Successfully retrieve own user rights (even if the user does not have USER_VIEW and USERROLE_VIEW rights)

- 2)  Successfully retrieve user rights of other user if the current user has UserRight.USER_ROLE_VIEW and UserRight.USER_VIEW rights

- 3) Prevent users without access (without USER_VIEW and USERROLE_VIEW rights) from retrieving user rights of other users
 The message will be the following: 
"Access to the specified resource has been forbidden. Please contact your supervisor or administrator and inform them about it"

**Comment by MartinWahnschaffe** [comment]
This is a bit of a controversial topic (e.g. discussion here: https://stackoverflow.com/questions/11746894/what-is-the-proper-rest-response-code-for-a-valid-request-but-an-empty-data).

From my point of view we should use a 404 Not found error. 

Using HTTP GET on users/rights/{uuid} with a uuid that does not exist means that the the caller is accessing a resource (via URL) that does not exist, so 404 is the right choice (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404).

Use the empty list, when the user was found, but does not have any user rights.

**Comment by carina29** [comment]
I also agree with @MartinWahnschaffe.
I've also proposed the same responses for the Not found user and the user without rights.

**Comment by abrudanancuta** [comment]
Validated on test-de2 with the version: 1.84.0-SNAPSHOT (52629f1)
