### ISSUE TITLE
District-level users can't change only the responsible region of an event participant

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11819]
### Bug Description

When changing the region of an event participant as a user with an assigned district, and leaving the responsible district empty, a warning message appears that tells the user they will lose access to the event participant when performing the action. However, after confirming the change, the fielids are simply reset. Changing both the region and district works as expected.

### Reproduction Steps

1. Create an event with a national user, and create an event participant with a responsible district
2. Log in with a district-level user with the same assigned district as the event participant
3. Open the event participant and change the region, leave the district empty
4. Confirm that you want to change the jurisdiction even though you would lose access to it
5. The jurisdiction fields are reset

### Expected Behavior

The region and district should be changed according to the user input (only if they are not required of course, because otherwise the district in fact has to be filled in), and the event participant should no longer be editable for the user.

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.83.0-SNAPSHOT

### Android version/Browser

Google Chrome

### User Role(s)

Surveillance Officer

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(53bd473).
