### ISSUE TITLE
Cannot save a new case for created travel entry

### ISSUE THREAD

**Issue by hms-sgent** [hzi-braunschweig/SORMAS-Project#11812]
### Problem Description

When creating a case for travel entry the "Place of state" checkbox is not marked as a mandatory, but when I try to save autofilled data in case form without selected "Place of stay" checkbox the following warning message pops up "A problem has occured. healthFacility: You have to specify a valid health facility". 
![image](https://user-images.githubusercontent.com/105210214/230613034-b5af8d61-678f-4999-ac7f-0f49d5314672.png)

Then I select "place of stay", and fill "Facility category", "facility type" and "type" and try to save the data one more time the following message pops up: "A problem has occured. The data could not be save because it has been changed in the meantime"
![image](https://user-images.githubusercontent.com/105210214/230613109-f33c36d8-7874-4609-ab4f-6177391fbfcf.png)

### Reproduction Steps

1. Login as a National User
2. Go to travel etries
3. Add new travel entry and fill only mandatory fields
4. Click on "New case" for the created travel entry you should see autofilled form
5. Save the form
 -> a problem occured
6. Fill all required data and save the form
-> another problem occured

### Expected Behavior

Health facility should not be required for point of entry cases (i.e. case origin = point of entry).

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.83.0-SNAPSHOT (925c5e5)

### Android version/Browser

Chrome

### User Role(s)

National user

### Server URL

https://test-de.sormas.netzlink.com/

### Additional Information

Logs from the local machine server:

[travel entry case error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11190648/travel.entry.case.error.txt)

**Comment by adinaflorea9** [comment]
@sergiupacurariu The same error is reproducible when creating a regular 'Point of entry' case if no facility or home is specified for the 'Place of stay'.

Steps to reproduce:
1. From the 'Cases' directory, open the 'Create new case form';
2. For 'Case origin' select 'Point of entry';
3. Fill in only the mandatory information and leave the 'Place of stay' as it is (not filled);
4. Save the case.
-> the same error appears stating that the user needs to specify a valid health facility.
