### ISSUE TITLE
Addition of "search" functionality on the SORMAS mobile app

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1182]
There is a need for a search functionality on the mobile app so mobile users can easily search for cases on their domain using names and EPID Numbers just like it is on the web platform. This would greatly reduce the number of duplicate cases which are created regularly on the platform @MartinWahnschaffeSymeda  @SeriousMartin @MateStrysewskeSym @Chinedar

**Comment by MateStrysewskeSym** [comment]
This has already been done and released to the productive systems with #1078.
