### ISSUE TITLE
Error processing template while "Create quarantine order to documents"

### ISSUE THREAD

**Issue by pk-sgent** [hzi-braunschweig/SORMAS-Project#11822]
### Problem Description

There is a problem with creating quarantine order in Contacts -> bulk edit mode -> Create quarantine order to documents with **"Also upload the generated documents to the selected entities" option checked.**

The error is reproducible on any entity page where the generation of quarantine documents is possible and the checkbox for 'Also upload' is checked (cases, events, travel entries). 

### Reproduction Steps

1. Log in as a admin user
2. Navigate to Contacts
3. Enter edit bulk mode
4. Choose two contacts 
5. Click on Bulk Actions -> Create quarantine order to documents with 
6. Check Also upload the generated documents to the selected entities
7. Select "ExampleDocumentTemplateContacts.docx" as a quarantine orded
8. Click on "Create" button

### Expected Behavior

Generated files should be downloaded

### Affected Area(s)

Web app

### SORMAS Version

Version: 1.83.0-SNAPSHOT (f0fe211)

### Android version/Browser

Google Chrome

### User Role(s)

Admin

### Server URL

https://test-auto.sormas.netzlink.com/

### Additional Information

![image](https://user-images.githubusercontent.com/96249076/231129895-b1d6295e-f43c-445a-bab0-6cf7c723f7e4.png)

Logs:

<html>
<body>

  |   | 2023-04-11 12:14:05 | level=info ts=2023-04-11T10:14:05.007733734Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/config.v2.json op=CREATE |  
-- | -- | -- | -- | --
  |   | 2023-04-11 12:14:05 | level=info ts=2023-04-11T10:14:05.005985052Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/hostconfig.json op=CREATE |  
  |   | 2023-04-11 12:14:05 | level=info ts=2023-04-11T10:14:05.003033207Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/.tmp-hostconfig.json658123261 op=CREATE |  
  |   | 2023-04-11 12:14:05 | level=info ts=2023-04-11T10:14:05.002727405Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/.tmp-config.v2.json2454120068 op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:14:00.77311064Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/5270c8a4f7a6ba09d229e815e06e2dccfdf3e212b3617ac490ada9ac9e13a60d/config.v2.json op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:14:00.771591603Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/5270c8a4f7a6ba09d229e815e06e2dccfdf3e212b3617ac490ada9ac9e13a60d/hostconfig.json op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:14:00.769537372Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/5270c8a4f7a6ba09d229e815e06e2dccfdf3e212b3617ac490ada9ac9e13a60d/.tmp-hostconfig.json2788246759 op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:14:00.769220927Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/5270c8a4f7a6ba09d229e815e06e2dccfdf3e212b3617ac490ada9ac9e13a60d/.tmp-config.v2.json739758819 op=CREATE |  
  |   | 2023-04-11 12:14:00 | INFO Payara 5.2021.10  D121400.075\|     > calculateCaseCompletion finished. 0 cases, 0 s (de.symeda.sormas.backend.common.CronService.java:103) |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:13:59.95985854Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/config.v2.json op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:13:59.958526252Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/hostconfig.json op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:13:59.956786496Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/.tmp-hostconfig.json2919450685 op=CREATE |  
  |   | 2023-04-11 12:14:00 | level=info ts=2023-04-11T10:13:59.956517611Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/.tmp-config.v2.json148483631 op=CREATE |  
  |   | 2023-04-11 12:14:00 | {"Timestamp":"2023-04-11T12:14:00.075+0200","Level":"INFO","Version":"Payara 5.2021.10","LoggerName":"","ThreadID":"254","ThreadName":"__ejb-thread-pool6","TimeMillis":"1681208040075","LevelValue":"800","LogMessage":"D121400.075\|     > calculateCaseCompletion finished. 0 cases, 0 s (de.symeda.sormas.backend.common.CronService.java:103)\n"} |  
  |   | 2023-04-11 12:13:58 | level=info ts=2023-04-11T10:13:58.731341392Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/286a3c98c38155b849173bfd9df03371d25130936c61806a95a2c662ef80a426/config.v2.json op=CREATE |  
  |   | 2023-04-11 12:13:58 | level=info ts=2023-04-11T10:13:58.730064806Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/286a3c98c38155b849173bfd9df03371d25130936c61806a95a2c662ef80a426/hostconfig.json op=CREATE |  
  |   | 2023-04-11 12:13:58 | level=info ts=2023-04-11T10:13:58.728295499Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/286a3c98c38155b849173bfd9df03371d25130936c61806a95a2c662ef80a426/.tmp-hostconfig.json4129022326 op=CREATE |  
  |   | 2023-04-11 12:13:58 | level=info ts=2023-04-11T10:13:58.727875803Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/286a3c98c38155b849173bfd9df03371d25130936c61806a95a2c662ef80a426/.tmp-config.v2.json1218418009 op=CREATE |  
  |   | 2023-04-11 12:13:55 | level=info ts=2023-04-11T10:13:54.911220469Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/config.v2.json op=CREATE |  
  |   | 2023-04-11 12:13:55 | level=info ts=2023-04-11T10:13:54.908845004Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/hostconfig.json op=CREATE |  
  |   | 2023-04-11 12:13:55 | level=info ts=2023-04-11T10:13:54.907100131Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/.tmp-hostconfig.json3725107328 op=CREATE |  
  |   | 2023-04-11 12:13:55 | level=info ts=2023-04-11T10:13:54.907033099Z caller=filetargetmanager.go:175 msg="received file watcher event" name=/var/lib/docker/containers/39abc6c385f1d5fb82dffd52750c81298b35cab90621c94723c45cf803d31ad4/.tmp-config.v2.json213799586 op=CREATE |  
  |   | 2023-04-11 12:13:53 | {"Timestamp":"2023-04-11T12:13:53.151+0200","Level":"INFO","Version":"Payara 5.2021.10","LoggerName":"","ThreadID":"84","ThreadName":"http-thread-pool::http-listener-1(5)","TimeMillis":"1681208033151","LevelValue":"800","LogMessage":"E121353.151\|     > Error while reading document variables. (de.symeda.sormas.ui.docgeneration.QuarantineOrderLayout.java:200)\nde.symeda.sormas.api.docgeneneration.DocumentTemplateException: Error processing template.\n\tat de.symeda.sormas.backend.docgeneration.QuarantineOrderFacadeEjb.uploadDocument(QuarantineOrderFacadeEjb.java:92)\n\tat de.symeda.sormas.backend.docgeneration.QuarantineOrderFacadeEjb.getGeneratedDocuments(QuarantineOrderFacadeEjb.java:149)\n\tat de.symeda.sormas.backend.docgeneration.QuarantineOrderFacadeEjb.getGeneratedDocuments(QuarantineOrderFacadeEjb.java:114)\n\tat jdk.internal.reflect.GeneratedMethodAccessor16795.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)\n\tat org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)\n\tat com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)\n\tat com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:35)\n\tat jdk.internal.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat de.symeda.sormas.backend.util.RightsAllowedInterceptor.checkRightsAllowed(RightsAllowedInterceptor.java:111)\n\tat jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:37)\n\tat jdk.internal.reflect.GeneratedMethodAccessor248.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat de.symeda.sormas.backend.audit.AuditLoggerInterceptor.logAudit(AuditLoggerInterceptor.java:158)\n\tat jdk.internal.reflect.GeneratedMethodAccessor247.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)\n\tat com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)\n\tat jdk.internal.reflect.GeneratedMethodAccessor246.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)\n\tat org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)\n\tat jdk.internal.reflect.GeneratedMethodAccessor244.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)\n\tat com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)\n\tat com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)\n\tat com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:205)\n\tat com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)\n\tat com.sun.proxy.$Proxy665.getGeneratedDocuments(Unknown Source)\n\tat jdk.internal.reflect.GeneratedMethodAccessor16794.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:143)\n\tat com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:173)\n\tat com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:528)\n\tat com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:199)\n\tat com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1565)\n\tat com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:128)\n\tat com.sun.corba.ee.impl.protocol.ClientDelegateImpl.invoke(ClientDelegateImpl.java:258)\n\tat com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:188)\n\tat com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:140)\n\tat com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:226)\n\tat de.symeda.sormas.api.docgeneneration.__QuarantineOrderFacade_Remote_DynamicStub.getGeneratedDocuments(de/symeda/sormas/api/docgeneneration/__QuarantineOrderFacade_Remote_DynamicStub.java)\n\tat de.symeda.sormas.api.docgeneneration._QuarantineOrderFacade_Wrapper.getGeneratedDocuments(de/symeda/sormas/api/docgeneneration/_QuarantineOrderFacade_Wrapper.java)\n\tat de.symeda.sormas.ui.docgeneration.DocGenerationController.lambda$showBulkQuarantineOrderDocumentDialog$2(DocGenerationController.java:99)\n\tat de.symeda.sormas.ui.docgeneration.QuarantineOrderLayout.lambda$createStreamResource$6ff486d6$1(QuarantineOrderLayout.java:180)\n\tat com.vaadin.server.StreamResource.getStream(StreamResource.java:143)\n\tat com.vaadin.server.FileDownloader.handleConnectorRequest(FileDownloader.java:167)\n\tat com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:90)\n\tat com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)\n\tat com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:750)\n\tat org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)\n\tat de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:73)\n\tat de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)\n\tat jdk.internal.reflect.GeneratedMethodAccessor509.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)\n\tat org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)\n\tat com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)\n\tat com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)\n\tat com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)\n\tat jdk.internal.reflect.GeneratedMethodAccessor246.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)\n\tat org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)\n\tat org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)\n\tat jdk.internal.reflect.GeneratedMethodAccessor244.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)\n\tat com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)\n\tat com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)\n\tat com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)\n\tat com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)\n\tat com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)\n\tat com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)\n\tat com.sun.proxy.$Proxy914.doFilter(Unknown Source)\n\tat de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)\n\tat de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:66)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)\n\tat de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)\n\tat org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)\n\tat org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)\n\tat com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)\n\tat org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)\n\tat com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)\n\tat com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)\n\tat org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)\n\tat org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)\n\tat org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)\n\tat org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)\n\tat org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)\n\tat org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)\n\tat org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)\n\tat org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)\n\tat org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)\n\tat org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)\n\tat org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)\n\tat org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)\n\tat org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"} |  
  |   | 2023-04-11 12:13:53 | {"Timestamp":"2023-04-11T12:13:53.149+0200","Level":"INFO","Version":"Payara 5.2021.10","LoggerName":"","ThreadID":"84","ThreadName":"http-thread-pool::http-listener-1(5)","TimeMillis":"1681208033149","LevelValue":"800","LogMessage":"E121353.149\|     > javax.validation.ConstraintViolationException: 1 constraint violation(s) occurred during method validation.\nConstructor or Method: public de.symeda.sormas.api.document.DocumentDto de.symeda.sormas.backend.document.DocumentFacadeEjb.saveDocument(de.symeda.sormas.api.document.DocumentDto,byte[]) throws java.io.IOException\nArgument values: [DocumentDto VKR2XF-UJBLVM-MLUGRT-5YZSKHHU, [B@1a3ebd73]\nConstraint violations: \n (1) Kind: PROPERTY\n message: requiredField\n root bean: de.symeda.sormas.backend.document.DocumentFacadeEjb$DocumentFacadeEjbLocal@33305f44\n property path: saveDocument.arg0.mimeType\n constraint: @javax.validation.constraints.NotNull(message=\"requiredField\", payload={}, groups={}) (de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.java:37)\n"} |  
  |   | 2023-04-11 12:13:53 | {"Timestamp":"2023-04-11T12:13:53.142+0200","Level":"INFO","Version":"Payara 5.2021.10","LoggerName":"","ThreadID":"84","ThreadName":"http-thread-pool::http-listener-1(5)","TimeMillis":"1681208033142","LevelValue":"800","LogMessage":"D121353.141\|     > autoload off: VM system will not automatically reload global library macros (org.apache.velocity.runtime.VelocimacroFactory.java:315)\n"} |  
  |   | 2023-04-11 12:13:53 | {"Timestamp":"2023-04-11T12:13:53.141+0200","Level":"INFO","Version":"Payara 5.2021.10","LoggerName":"","ThreadID":"84","ThreadName":"http-thread-pool::http-listener-1(5)","TimeMillis":"1681208033141","LevelValue":"800","LogMessage":"D121353.141\|     > allowInlineLocal = false: VMs defined inline will be global in scope if allowed. (org.apache.velocity.runtime.VelocimacroFactory.java:297)\n"} |  
  |   | 2023-04-11 12:13:53 | {"Timestamp":"2023-04-11T12:13:53.141+0200","Level":"INFO","Version":"Payara 5.2021.10","LoggerName":"","ThreadID":"84","ThreadName":"http-thread-pool::http-listener-1(5)","TimeMillis":"1681208033141","LevelValue":"800","LogMessage":"D121353.141\|     > allowInlineToOverride = false: VMs defined inline may NOT replace previous VM definitions (org.apache.velocity.runtime.VelocimacroFactory.java:274)\n"}

</body>
</html>

**Comment by adinaflorea9** [comment]
The error is reproducible only when the checkbox for 'Also upload the generated documents to the selected entities' is checked.

Additionally, this is reproducible individually on the entity page when trying to upload a newly created quarantine order document if that checkbox is checked.

The issue is reproducible for other entities as well such as cases, and events.

**Comment by MateStrysewske** [comment]
Caused by #4959
