### ISSUE TITLE
S2S - Share box of sample  shared with ownership shows incorrect information

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#11842]
### Bug Description

Share box of sample  shared with ownership shows that it is **owned by** the sender organization but It should say **sent from** the sender orgazation.

### Reproduction Steps

1. Create a case with sample in SROMAS A
2. Send it with ownership to SORMAS B
3. Accept the share request in SORMAS B
4. Navigate to the sample just accepted
5. Observe the share box displays **Owned by** *source organization*

### Expected Behavior

Should display **Sent from** *source organization*

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.83.0-SNAPSHOT

### Android version/Browser

Google Chrome

### User Role(s)

National User

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ and https://test-de3.sormas.netzlink.com/ using SORMAS version 1.84.0-SNAPSHOT(ca97ddb).
