### ISSUE TITLE
Refactor all code occurrences of "Undelete" to "Restore" [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11854]
### Problem Description

#11327 has introduced a number of new strings that use the word "Restore" in favor of "Undelete" because it's less technical and more frequently used in everyday language use. The code still uses the word "Undelete" everywhere though.

### Proposed Change

Replace all occurrences of "Undelete"/"Undeletion" in the code with "Restore"/"Restoration", e.g. "DeleteUndeleteController" should be called "DeleteRestoreController" afterwards.

### Added Value/Benefit

Consistent wording between the UI and the code.

### Acceptance Criteria

- [ ] Searching the code for occurrences of "Undelete" or "Undeletion" brings up on results anymore.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(40ab095).
