### ISSUE TITLE
Case management export function 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1185]
There will be need to have export function for case management and also link it to their case ID

**Comment by Iheanacho2027** [comment]
Please the case management export should be linked with the Case Sn as well

**Comment by MateStrysewskeSym** [comment]
Idea: Add export functions to the case directory:

1. Export prescriptions
2. Export treatments
3. Export clinical course

**Comment by MateStrysewskeSym** [comment]
Done in #1266
