### ISSUE TITLE
Language > Include "Français (Tunisie)" in UI for French (Tunisia)

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#11862]
### Feature Description

Users in Tunisia would like to make use of SORMAS in French (Tunisia). In order to make this visible on the UI, the option for "Français (Tunisie)" needs to be included in the user language (User Settings > Language) dropdown.

The language has been introduced on CrowdIn (https://crowdin.com/project/sormas/fr-tn).

### Added Value/Benefit

This feature would allow localisation of SORMAS UI content based on end user needs.

### Acceptance Criteria

- [x] "Français (Tunisie)" is added to dropdown values found at: User Settings > Language
- [x] "Français (Tunisie)" is placed under "Français (Suisse)" so that all Français languages are grouped alphabetically (see mock-up)
- [x] Tunisian flag thumbnail is added: https://github.com/gosquared/flags/blob/master/flags/flags-iso/shiny/64/TN.png
- [x] Local date and time formats conform to fr-TN, "dd/MM/yyyy", "dd/MM/yyyy HH:mm", "dd/MM"
- [x] SORMAS UI is translated and displayed in the language when it is selected from the list
- [x] Individual system users are able to select and set the language as their language of choice when setting up/configuring a new user (user management)

### Implementation Details

Similar to https://github.com/hzi-braunschweig/SORMAS-Project/issues/4449 with https://github.com/hzi-braunschweig/SORMAS-Project/pull/4759, and https://github.com/hzi-braunschweig/SORMAS-Project/issues/9042 with https://github.com/hzi-braunschweig/SORMAS-Project/pull/9578.

### Mockups

![image](https://user-images.githubusercontent.com/65529128/232535310-fdf6d7a5-3746-4394-8bf0-b35654615c0d.png)

**Comment by bernardsilenou** [comment]
@Candice-Louw @MateStrysewske 
* The versions of a language are growing so fast that it may not look nice from a design perspective.
 I was wondering if we can only show the base language (here Franch) on the UI and determine the version using the country instance in the sormas.properties file. ie if a user chooses Franch, then we load the translations for their country.

**Comment by MateStrysewske** [comment]
@bernardsilenou Please move this to [Discussions](https://github.com/hzi-braunschweig/SORMAS-Project/discussions) as it's not related to this specific issue.

**Comment by adinaflorea9** [comment]
#11877 deals with the buttons that are overlapping the edges of the cards in all 3 French variants.

Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(40ab095).
