### ISSUE TITLE
Filters in merge views only consider the older entry of each case/contact pair

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11872]
### Bug Description

If user will search a case by a name of facility that exists in the view of Merge Cases, the list will be empty

### Reproduction Steps

1. Login as NatUser+Admin
2. Go to Cases
3. Select Merge Duplicates
4. Enter in the search field by "ID, EPID number, external ID, facility" a name of a facility that was returned in the list of cases 
5. Apply the filter

OBS: Before searching by facility make sure that only one facility beside the Home option is returned in the list. For more details look at the screen recorder

https://user-images.githubusercontent.com/91872179/233084042-e20c1606-0caf-4c31-a242-4810f1c273c7.mov

### Expected Behavior

The cases connected to the search facility should be in the list

### Affected Area(s)

Web app

### SORMAS Version

1.81.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

### Server URL

test-de2

**Comment by MateStrysewske** [comment]
This is a general problem of all filters we have in the merge cases and contacts view; apparently the filters only consider the older of the two entries (i.e. the one with the earlier creation date).

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the fact that now soft deleted cases are taken into account as potential duplicates in the merge cases view (one of the cases is active and the potential duplicate is soft deleted).
