### ISSUE TITLE
Filter cases by reporting user (web) [0.5]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1187]
Currently on the web platform, we are unable to identify cases reported by a specific user using the "reported by" search filter of the case directory. For example, cases reported by a DSNO from a particular LGA cant be identified automatically using the "reported by" search filter on the case directory of the web platform, what is currently attainable are aggregated results of cases reported by all "surveillance officers", "hospital informants", "national users" etc as shown in the attached image A. Can we therefore have a situation where the system can automatically generate cases reported by specific users using the ''reported by" search filter on the case directory ?, or design another filter specifically for this purpose. This is very important for analysis of user performance @Chinedar @foyiri @MateStrysewskeSym @MartinWahnschaffeSymeda 
![image A](https://user-images.githubusercontent.com/50739609/59305111-7a35bf00-8c91-11e9-99f0-111b757119e4.PNG)

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 
We would like to implement this filter by using a text field. We could also use a drop down, but this could have a bad influence on the performance, because there are a lot of users in the system.

Would a text field be ok, from your point of view?

**Comment by Iheanacho2027** [comment]
This would be fine for a start

**Comment by Iheanacho2027** [comment]
The text field would be fine for a start
