### ISSUE TITLE
Additional medical information field is skipped during case creation [0]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1188]
When creating a case that additional medical information like vaccination is needed, SORMAS moves from case menu directly to person menu. In this way the vaccination field can easily be missed. I suggest we create a new field for additional medical information or add it somewhere in the current flow.

**Comment by MateStrysewskeSym** [comment]
- [ ] When creating a new case open the case data view afterwards (app and UI)
