### ISSUE TITLE
Case/contact follow-up visit grid displays additional columns when in read-only mode

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#11903]
### Bug Description

When entering the follow-up view of a case or contact in read-only mode, instead of the usual columns, all columns that are part of the DTO are instead added to the grid, resulting in a much higher number of columns and some that should never be displayed in the frontend (e.g. whether or not the visit is pseudonymized or its database ID).

### Reproduction Steps

1. Copy the URL of a case that a user e.g. on district level does not have access to
2. Log in as that district user and enter the case via the URL
3. Open the follow-up view and check the columns in the grid

### Expected Behavior

Only the columns defined in the code should be displayed.

### Affected Area(s)

Web app

### SORMAS Version

1.83.0-SNAPSHOT

### Android version/Browser

Chrome

### User Role(s)

e.g. Surveillance Officer

### Server URL

localhost

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(40a5ac7).
