### ISSUE TITLE
Server setup script suggests execution of sormas-update.sh which has since been renamed

### ISSUE THREAD

**Issue by bkssht** [hzi-braunschweig/SORMAS-Project#11901]
### Problem Description

For the following step during installation
........echo "  - Execute the sormas-update.sh file to populate the database and deploy the server".......

sormas-update.sh file is not present.

### Reproduction Steps

1.run server-setup.sh
2.choose development environment option
...

### Expected Behavior

Change the text in server-setup.sh to "Execute the server-update.sh file [...]".

### Affected Area(s)

Web app

### SORMAS Version

Sormas 1.80.0

### Android version/Browser

Google chrome

### User Role(s)

installation

**Comment by bkssht** [comment]
Hi. Thank you for swift reply. 
I did run "server-update.sh" but it doesn't seem to run database scripts for tables and all.
Could you please let me know if there is any detailed installation guide for Sormas because I have tried installing in on Windows using Git bash and on Ubuntu without success?
Thank you.

**Comment by MateStrysewske** [comment]
@bkssht The database tables are created when you deploy SORMAS for the first time. All existing installation guides are available in this repository and accessible through the main readme file; if you follow them step by step, there should be no issues in successfully setting up a server.

**Comment by bkssht** [comment]
@MateStrysewske Hi, could you please tell me at which point the tables are created. I have run the installation multiple times but each time, only databases are created but tables are not.
![sormas tables](https://user-images.githubusercontent.com/3724264/235178337-caa59e76-2cd8-4abe-a1fb-c00d438e8cba.PNG)

**Comment by MateStrysewske** [comment]
@bkssht The tables are created when the server is started for the first time.
