### ISSUE TITLE
Add "compatible" and "epi-linked" flags to case [2]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1190]
[Kopie von YF-Measles Data entry_gekmARTIN.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3290074/Kopie.von.YF-Measles.Data.entry_gekmARTIN.xlsx)
We need to discuss this

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym See attached our discussion with the WHO guys
-[ ] WHO to talk to   Nigeria Bureau of Statistics for urban rural LGAs/ Use dropdown for place of   residence based on investigator selection
-[ ] Use external lab   user to create confirmation lab test (e,g Dakar, CDC)
-[ ] Compatible: cases classified in 2 dimensions for YF and M, if a lab result is indeterminate for a nigeria lab, then the final classfication is then compatible, if a case of measles is negative from the lab, and the specimen condition is not adequate, it is also called compatible. Epi-linked is only associated to Measles. according to measles tech guide, when there is about 3 or more positive cases from the lab within 30 days in a particular LGA, there is a confirmed outbreak. When this happens, they switch to linelist from casebased data. All linelist data entered within the same 30 days using the date of onset from that same LGA, we classiffy as epi-linked since there is no lab result (measles. cholera). For measles, suspected outbreak, 5 and above case based not lab confirmed cases within the same month and out of 5, lab confirms 3 and above, then it becomes cofirmed outbreak. Case base data stops and linelist starts.

-[ ] Phone and email address of clinician should be split into two fields also needed on the export template
[Kopie von YF-Measles Data entry_gekmARTIN.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3310302/Kopie.von.YF-Measles.Data.entry_gekmARTIN.xlsx)




--

**Comment by MartinWahnschaffeSymeda** [comment]
Notes from last review:

- Add "Final lab classification" to case -> automatically, define rules
- Add information to laboratories whether they are a reference lab
	-> result has priority
	-> when there are multiple reference labs for a sample, positive results have priority
- Non-reference lab results are only presumptive
- Only for specific diseases (VHF)
- Add laboratory information to detailed sample export "Other pathogen tests" column
- Extend sample information in case export (show laboratory and result for each sample) -> most important to allow them to do this stuff manually
- We should probably take the Laboratory field out of the pathogen test (or hide it/make it read only)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Need to go through this with you via phone.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make sure that case and sample export have the sample result and the lab that created it
- [ ] add field "compatible" to case for measles and VHF
- [ ] Calculate compatible: Only for suspected and probable cases. If they have lab results based on the two rules above
- [ ] add field "epi-linked" to case for measles and cholera
- [ ] Automatically calculate it based on the rules above
- [ ] add a filter to the cases directory called "Compatible/epi-linked"
- [ ] add clinician email and clinician phone fields to case

**Comment by MateStrysewskeSym** [comment]
We're still unsure about what's the best way to integrate this. Our thoughts are that:

* Right now, the case export already includes the column "Associated with an outbreak", which pretty much fits the definition of an epi-linked case if we understand it correctly (except for the first three cases of an outbreak); i.e. if the definition in the PDF actually defines a contact as living in the same outbreak district as a confirmed measles case
* Based on that, and considering that the term epi-linked is a very specific for only a few diseases, wouldn't it possibly be a better idea to keep the current status?
* We still don't really understand what Compatible is used for exactly; based on the definition in the PDF, basically all suspect Measles cases are compatible UNLESS a sample was just taken, but not yet tested (which probably is a very short time frame); again, considering this is a very specific term, wouldn't it maybe be better to generalize this (i.e. by adding a filter for "cases without a taken sample") and provide all necessary information in the case export to manually retrieve this information?

We feel like we need to discuss this once more in detail and should do so either during our next sprint review or in a phone call prior to that.

**Comment by MateStrysewskeSym** [comment]
We're still unsure about what's the best way to integrate this. Our thoughts are that:

* The pre-condition of an epi-linked case is basically the outbreak definition of a Measles case; therefore, the trigger to label a case as epi-linked should probably be that there's an outbreak in the same district (which is part of issue #885 and its associated issues)
* Right now, the case export already includes the column "Associated with an outbreak", which pretty much fits the definition of an epi-linked case if we understand it correctly (except for the first three cases of an outbreak); i.e. if the definition in the PDF actually defines a contact as living in the same outbreak district as a confirmed measles case
* Based on that, and considering that the term epi-linked is a very specific for only a few diseases, wouldn't it possibly be a better idea to keep the current status?
* We still don't really understand what Compatible is used for exactly; based on the definition in the PDF, basically all suspect Measles cases are compatible UNLESS a sample was just taken, but not yet tested (which probably is a very short time frame); again, considering this is a very specific term, wouldn't it maybe be better to generalize this (i.e. by adding a filter for "cases without a taken sample") and provide all necessary information in the case export to manually retrieve this information?

We feel like we need to discuss this once more in detail and should do so either during our next sprint review or in a phone call prior to that.

**Comment by MartinWahnschaffeSymeda** [comment]
Discussed this again today:

* The epi-linked classification is inherently the same as an automatic outbreak detection in SORMAS, so we probably need to make this a priority now
