### ISSUE TITLE
Reference DTO with uuid appears at case 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#11916]
### Bug Description

Reference DTO with uuid appears at case previous hospitalization

### Reproduction Steps

![Screenshot 2023-05-02 at 11 36 24](https://user-images.githubusercontent.com/91872179/235632506-b8e8af33-8322-4cf6-9fd3-92e8303b6574.png)

### Affected Area(s)

Web app

### SORMAS Version

1.82.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

**Comment by adinaflorea9** [comment]
Closing ticket as discarded as this was fixed on 1.83.0 with ticket #11752
