### ISSUE TITLE
Provide login details for users on login screen [0.5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1193]
We need to automatically pull the username and password for (SunkSesa) into the login field for the SORMAS helmholtz server. I just found out that many people do not read the information just before the link that takes them to the SORMAS play version. We need to look into this asap @MartinWahnschaffeSymeda @MateStrysewskeSym @bernardsilenou

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Build an example that does this based on #1194
