### ISSUE TITLE
Custom login screen [2]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1194]
@faatihi @MartinWahnschaffeSymeda @MateStrysewskeSym @bernardsilenou @Chinedar @danieltomaba @foyiri 
<img width="959" alt="loginScreen" src="https://user-images.githubusercontent.com/19344651/59667507-26f2cd80-91b7-11e9-82ad-736bf4fd92ee.PNG">

![SORMAS-GHANA-LOGIN-SCREEN_DTA_18062019](https://user-images.githubusercontent.com/19344651/59667474-1c383880-91b7-11e9-82ec-6d18da2ae740.png)
![SORMAS-NIGERIA-LOGIN-SCREEN_DTA_18062019](https://user-images.githubusercontent.com/19344651/59667475-1c383880-91b7-11e9-98c6-00b81393c0bd.png)

**Comment by hzi-braunschweig** [comment]
Revised mockups based on inputs

![image](https://user-images.githubusercontent.com/19344651/59681460-4815e700-91d4-11e9-87c2-36ca116436a1.png)

![image](https://user-images.githubusercontent.com/19344651/59681451-41876f80-91d4-11e9-9ce2-ef6ea9a342bf.png)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add custom HTML template that is automatically filled into the right side of the login page. Default should have power by with HZI, symeda, GIZ, 
- [ ] add custom HTML template that is automatically filled below the login form (e.g. for contact details and default user names of test systems)

Both files should for now only be editable from the server backend.

**Comment by MartinWahnschaffeSymeda** [comment]
Try the following:

- [ ] put the deep blue into the main background (2/3 of the screen) und the login form into it's center
- [ ] use scrollbars when needed
- [ ] put the big sormas logo into the top right

**Comment by MateStrysewskeSym** [comment]
- [ ] right sidebar should be scrollable if the logo section is too big for the screen
- [ ] centralize the full name below the main logo
- [ ] put the bullet points from the mockups above into the right sidebar
