### ISSUE TITLE
The user is unable to see the names of the region, department, community or establishment when reporting instead the reference code is seen

### ISSUE THREAD

**Issue by Tommymbk** [hzi-braunschweig/SORMAS-Project#11959]
### Bug Description

![ScreenShots_Sormas_Statistics](https://github.com/hzi-braunschweig/SORMAS-Project/assets/109162021/c7e977a0-f1bd-491e-9366-f0ef3f729306)
![Sormas_Sc_Satistics](https://github.com/hzi-braunschweig/SORMAS-Project/assets/109162021/77a32cdc-622b-45ff-86e5-44f2c4e3dbc3)
![Sormas_Statistics](https://github.com/hzi-braunschweig/SORMAS-Project/assets/109162021/0dbfe3fc-1ff1-4cd8-8d67-7307a36790bd)

### Reproduction Steps

1. By clicking in statistics, add a filter
2. After selecting an attribute
3. Choose the type of graph;
4. in the Visualization section, we choose the Series: disease, on the x-axis we choose Region/District/Community/Establishments, then we specify the selection either District
5. When we click on generate
![ScreenShots_Sormas_Statistics](https://github.com/hzi-braunschweig/SORMAS-Project/assets/109162021/c96c61eb-b7b8-4e07-8fe1-d998a9ca511f)
    
...

### Expected Behavior

We should see Health Zone names instead of reference codes
![Screenshot](https://github.com/hzi-braunschweig/SORMAS-Project/assets/109162021/499f7aa1-adfe-4149-9630-427dfc49dec1)

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.80.0

### Android version/Browser

Google Chrome

### User Role(s)

Surveillance Officer Statistic, Contact Officer, National user

### Server URL

congo-staging.sormas.netzlink.com

### Additional Information

@bernan

**Comment by Tommymbk** [comment]
@bernardsilenou please assist

**Comment by adinaflorea9** [comment]
Issue is reproducible on 1.84.0 as well.

**Comment by Tommymbk** [comment]
Salut Bernard

Comment le savoir?

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.84.0-SNAPSHOT(52629f1).
