### ISSUE TITLE
Missing map key category

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1196]
I searched mpnkeypox cases from 01/08/2017 to 15/05/2019 and viw cases incidence proportion. I found 4 colors on map but only 3 map keys.  See image
![image](https://user-images.githubusercontent.com/12996724/59978643-d62c0c00-95de-11e9-9d4e-e06a107c4c48.png)

**Comment by hzi-braunschweig** [comment]
@bernardsilenou it does not happen when you are at the default map for case counts. Only when you change to incidence proportion

![image](https://user-images.githubusercontent.com/19344651/60018706-52c8f400-968c-11e9-91df-e4ff7c99d603.png)

![image](https://user-images.githubusercontent.com/19344651/60018737-61171000-968c-11e9-8972-b19dfd34b316.png)

**Comment by MateStrysewskeSym** [comment]
I think this bug has already been fixed with #1178 but has not yet been released to the Nigerian server (because we first need to test the release due to the infrastructure updates it contains).
