### ISSUE TITLE
Vaccination delete without edit rights prevents the Vaccination status update

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#11980]
### Bug Description

Given the following situation:
 - a user having the following rights:
    - cases: Delete right - Yes, Edit right - No
    - immunization and vaccination - Delete right - Yes, Edit rights - no
- feature configuration - Immunization module = 'reduced'

In case a user wants to delete a vaccination that could impact the vaccination status of the case then if the user wants to update the status it will be restricted. This happens because in order to update the vaccination status user must have Case Edit Rights.

### Reproduction Steps
1. Activate "IMMUNIZATION_MANAGEMENT" feature and set Reduced on true;
2. Create a user with the following rights: CASE: View and Delete rights; IMMUNIZATION: View and Delete rights;
3.  With and Admin+NatUser - create a case (or contact/event participant) who has a relevant vaccination;
4. With the user from step 2 open the vaccination and click to delete it;
5. In the pop-up window "Vaccination status update" select "Yes".
Actual behavior:
The vaccination is deleted in the process but the Case vaccination status cannot be updated when the user selects "Yes".

![image](https://github.com/hzi-braunschweig/SORMAS-Project/assets/62688603/3d87d67c-e820-41eb-99c0-ad4d6d9a4698)

Logs from the local machine:
[vaccination logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/11544085/vaccination.logs.txt)

### Expected Behavior
The vaccination status should get updated in this particular flow even though the user does not have edit rights over the case/contact/event participant - (the solution would probably again be to have some kind of a dedicated method that only updates the vaccination status as discussed with @MateStrysewske).

### Affected Area(s)

Web app

### SORMAS Version

SORMAS 1.84.0

### Android version/Browser

Google Chrome

### User Role(s)

Admin+NatUser; Configured user that has the rights described in the steps to reproduce

### Additional Information
In the server logs, regardless of whether the user tries to delete a vaccination associated with a case, or contact or event participant, it is always displayed that the missing rights are CASE_CREATE and CASE_EDIT.

**Comment by adinaflorea9** [comment]
I am reopening the ticket as for contacts and event participants the pop-up to update the vaccination status appears, the user can select yes, but the vaccination status is not updated accordingly.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.84.0-SNAPSHOT(ee25ec7). The issue reported for contacts and event participants will be dealt with in a separate ticket as there the problem is reproducible for both users with or without edit rights.
