### ISSUE TITLE
Add "Not yet defined" disease

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1199]

**Comment by MateStrysewskeSym** [comment]
@danieltomaba Should "Not yet defined" diseases have contact follow-up? I guess no, but what's your take on this question?

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym The contact follow up function should be activated only based on the disease selected. Remember, surveillance officers and contact officers see these POE cases and can continue investigation and contact listing and follow up but for the POE informants, they do not do contact follow up. They are not trained to do so. So the answer to your question is no.
