### ISSUE TITLE
Constraints in entering results of other additional tests [1]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1200]
The system currently restricts users from entering results with decimals in "other additional tests". This shouldnt be so. Attached is an image showing the error 
![Capture additional results](https://user-images.githubusercontent.com/50739609/60263888-bdbb3a80-98d9-11e9-890b-5382c2d64a01.PNG)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] allow decimal data entry for all number fields of the additional test
