### ISSUE TITLE
Adjust handling of time periods on dashboard [1+3]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1203]
Please find below… Software adjustments review – with Gerard

- Previous cases as a label for period to period comparison is ambiguous.
  Change this to "current week vs last week", "today vs yesterday", "current year vs same period last year", "current week vs same week last year"...
- Disease burden information should be defined
  a. "current week vs last week"
  b. "current vs average of last 4 weeks"
  c. "all cases current year vs all cases same period last year"
  d. "current month vs same month last year"
  e. "current week vs same week last year"
- have radio buttons to flip between day, week, month, year. a custom tab check box (compare to exact time period with previous year)
- change custom tab to "select reporting period". the default of the dashboard should then be select reporting period and all cases in the distribution
column one - disease, column 2 - current period, column 3 - comparing period.
- a clear concept on case fatality rate should be defined for all diseases. -> #1184
- cases with confirmed negative result from the lab should be classified as "not a case" -> #1223
- not yet classified- a case entered into the system but yet to be investigated for meeting case definitions.
- review the classification rules in SORMAS
- change "last reported community" to "last reported LGA/district"
- label first then figure/numbers at the end on the disease burden information for better responsiveness
- change "case incidence ratio" to "incidence proportion" (per 100.000) in the map view options -> #1180

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please add some structure to the points above.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig I have reformatted your post now. I hope I got it right. Most points need some clarification, so we should discuss this during the next meeting.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Thanks. i just made a few adjustments but its fine 

REgards

**Comment by MateStrysewskeSym** [comment]
Notes from review:

* depending on the selected time frame offer different options for the comparison time frame. E.g. previous period, same period last year.
* dont do average comparison on dashboard
* remember filters
* explicitely label the resulting packed date
* custom -> select period
* create issue for automatic classification of "not a case"

**Comment by MartinWahnschaffeSymeda** [comment]
![Dashboard](https://user-images.githubusercontent.com/23217632/62142259-43257680-b2ee-11e9-845b-2a102b994e01.jpg)
![DashboardFilter](https://user-images.githubusercontent.com/23217632/62142261-44ef3a00-b2ee-11e9-82d8-c2cf2d1973e7.jpg)

Time period options:

* today: 30/07/19
  - the day before: 29/07/2019
  - same day last year: 30/07/2018
* yesterday: 29/07/2019
  - the day before: 28/07/2019
  - same day last year: 29/07/2018
* current epi-week: Wk 31-2019
  - the epi-week before: Wk 30-2019
  - same epi-week last year: Wk 31-2018
* last epi-week: Wk 30-2019
  - the epi-week before: Wk 29-2019
  - same epi-week last year: Wk 30-2018
* current year: 01/01 - 30/07/2019
  - last year: 01/01 - 31/12/2018
  - same period last year: 01/01 - 30/07/2018
* select period: Wk 29-2019 - Wk 31-2019
  - period before: Wk 26-2019 - Wk 28-2019
  - same period last year: Wk 29-2018 - Wk 31-2018
  - select period: ...

Implementation:

- [ ] time filters and components based on mockup
- [ ] caption and sub-caption for differences chart
- [ ] update tile layout: last report and number of cases of comparison period
- [ ] last reported community -> district
- [ ] remember filters (DashboardCriteria + URL)

**Comment by MateStrysewskeSym** [comment]
- [ ] Switch captions and values in carousel layout
