### ISSUE TITLE
Improve data loading of ReST API [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1207]
Mutliselect dto creation for infrastructure on server:

- [x] region
- [x] district
- [x] community
- [x] healthy facility
- [x] point of entry

See CaseFacadeEjb.getIndexList for an example.
Create unit tests for each multiselect .

Additional ideas:

- don't use orm for initial infrastructure in app?
- use document store in app?
- only transfer fields that have changed on server (diff with history table entry based on last sync time)

**Comment by ChristopherRiedelSymeda** [comment]
For every infrastructure entity:

Starting point: FacilityResource, RegionResource, ... 
- [ ] Adapt Facade method (e.g. FacilityFacadeEjb.getAllByRegionAfter / getAllWithoutRegionAfter):
- [ ] selectIndexDtoFields method: Fill Dto with multiselect (e.g. FacilityDto)
- [ ] Change existing getIndexList method
- [ ] setIndexDtoSortingOrder -> swap out existing code
- [ ] Add test method

**Comment by MateStrysewskeSym** [comment]
- [ ] Only filter facilities by region if regionUuid is not null
