### ISSUE TITLE
Errors on detailed export of SORMAS cases (age group) [0]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1208]
Some errors have been observed on the detailed export functionality for the case listing

1) For some of the exports, the data returned in the age group column is erratic as shown in image A1. Also the format for date of birth doesnt match the data returned i.e. the d.o.b format is year/month/day while the data returned is day/month/year

2) For samples taken twice, the date of sample collection data is returned on the same column as shown in image b1. The date of sample collection data for cases with samples taken twice should be on different columns for easy understanding

Finally, can we have a smart export functionality that allows users to filter and select specific variables they want to export?

[Image A1](https://user-images.githubusercontent.com/50739609/60665376-341ce700-9e5c-11e9-849e-3c1ade54e9c2.png)

![Image B1](https://user-images.githubusercontent.com/50739609/60665388-397a3180-9e5c-11e9-9f66-dc5085868515.png)

 @Chinedar @foyiri @SeriousMartin @MateStrysewskeSym

**Comment by MateStrysewskeSym** [comment]
Just a quick heads-up on your first issue, we'll talk about the rest until our next review and get back to you: The malformed data in the Age Group column is due to Excel automatically formatting its contents; we can't do anything about that.

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 Thanks for the input.

An addition to what Maté said: 

- [ ] we can try to output the age group in a diffent format, so excel does not mess with it. Instead of write "5-7", we can try "5 - 7" - this may solve the problem.

For point 2 I have create #1214. Please have a look at it and leave any comments.

For the smart export funcationality it would be great if you could create a separate issue for it and add some suggestions on how you would like this to look like.

**Comment by Iheanacho2027** [comment]
This is fine Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Martin Wahnschaffe <notifications@github.com> Date: 08/07/2019  16:04  (GMT+01:00) To: hzi-braunschweig/SORMAS-Project <SORMAS-Project@noreply.github.com> Cc: Iheanacho2027 <iheanachodenwigwe@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [hzi-braunschweig/SORMAS-Project] Errors on detailed export of SORMAS cases (#1208) @Iheanacho2027 Thanks for the input.

An addition to what Maté said:



 we can try to output the age group in a diffent format, so excel does not mess with it. Instead of write "5-7", we can try "5 - 7" - this may solve the problem.



For point 2 I have create #1214. Please have a look at it and leave any comments.

For the smart export funcationality it would be great if you could create a separate issue for it and add some suggestions on how you would like this to look like.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/hzi-braunschweig/SORMAS-Project/issues/1208?email_source=notifications\u0026email_token=AMDDTGP3Y2I6WIE7GHBW2TTP6NJPLA5CNFSM4H5ZEZEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZNL7QQ#issuecomment-509263810",

"url": "https://github.com/hzi-braunschweig/SORMAS-Project/issues/1208?email_source=notifications\u0026email_token=AMDDTGP3Y2I6WIE7GHBW2TTP6NJPLA5CNFSM4H5ZEZEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZNL7QQ#issuecomment-509263810",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 Looks like something went wrong with your reply

**Comment by Iheanacho2027** [comment]
"This is fine" was my reply @MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
Adding whitespaces did not work, so I decided to use points instead - eg. "0..4". This works fine

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] use "--" instead
