### ISSUE TITLE
Make sure payara ports are not bound to the internet [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1216]
Admin ports and html ports, e.g. 6048, 6080, 6081. Just close all the ports!

- [ ] Check on the existing servers.
- [x] Update the server setup guide

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Any news on the DHIS2 demo on the sormas server?

**Comment by hzi-braunschweig** [comment]
Hi Martin, please block all ports except port 8087. I am really tied up right now but will back up the DHIS2 database and let you know before the end of the week.


Thanks


Tom-Aba Daniel (MPH B.Sc)
PhD programme “Epidemiology” Braunschweig-Hannover
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de
Office: +495316181-3124
Mobile: +491739136081
________________________________

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Have you been able to backup the DHIS 2 database? Can we remove DHIS2 from the system?

**Comment by MartinWahnschaffeSymeda** [comment]
This is enabled now for sormas.org.ng.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig The DHIS2 server is still running. Should we at least shut it down (but keep it on the system)? I couldn't find where the startup script for the server is.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig The ports are blocked now, with the exception of the needed port for DHIS2. The DHIS2 server is still running. Should we at least shut it down (but keep it on the system)? I couldn't find where the startup script for the server is.

**Comment by hzi-braunschweig** [comment]
Yes please shut it down! @MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig I have looked into this again and realized that the process that is still running is not DHIS2. Instead it's a WSO2 server. Is this used for the device management?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig I have looked into this again and realized that the process that is still running is not DHIS2. Instead it's a WSO2 server. Is this used for the device management?

@MateStrysewskeSym I guess we need a Nagios for monitoring on the system. Worth discussing this with Stefan Winterfeld or Jan.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda We are using the WSO2 server for the MDM server for the Nigeria system. Is this going to be a problem?

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig I guess the problem is that it takes up a lot of ressources and therefore might slow down the server as a whole.

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym But we have had it on the same server for more than 2 years. We have the mdm platform on the same server with the sormas nigeria server. We will have to think about migrating it if you think it will impact this greatly. Please advise further. So the DHIS2 server is not the issue here right?
