### ISSUE TITLE
Import of line listing case data [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1224]
- [x] Collect alternatives to do this

* UI list that supports copy and paste and automatically assigns case fields to the columns of the pasted data
* Provide template with limited field set

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Any news on this?

**Comment by MartinWahnschaffeSymeda** [comment]
Use the fields that are use for the line listing

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please have a look at the following list of fields (the line listing import template):

disease | diseaseDetails | plagueType | dengueFeverType | rabiesType | person.firstName | person.lastName | person.sex | person.birthdateDD | person.birthdateMM | person.birthdateYYYY | epidNumber | reportDate | region | district | community | healthFacility | healthFacilityDetails | symptoms.onsetDate

1. Do we need additional fields for the line listing import?
2. Should we allow import of "other" diseases? If not we don't need the "diseaseDetails" column
3. Do we need the plagueType , dengueFeverType, rabiesType columns to specify the exact type of such a disease?

Import for other health facilities or home is possible using "OTHER_FACILITY" or "NO_FACILITY"

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please have a look at the following list of fields (the line listing import template):

disease | diseaseDetails | plagueType | dengueFeverType | rabiesType | person.firstName | person.lastName | person.sex | person.birthdateDD | person.birthdateMM | person.birthdateYYYY | epidNumber | reportDate | region | district | community | healthFacility | healthFacilityDetails | symptoms.onsetDate

1. Do we need additional fields for the line listing import?
2. Should we allow import of "other" diseases? If not we don't need the "diseaseDetails" column
3. Do we need the plagueType , dengueFeverType, rabiesType columns to specify the exact type of such a disease?
4. Should we allow import of uncomplete birth dates (e.g. only day + month)? If not we can combine the three columns into one colum where the exact DOB is entered

Import for other health facilities or home is possible using "OTHER_FACILITY" or "NO_FACILITY"

**Comment by MartinWahnschaffeSymeda** [comment]
Rough implementation steps:

- [ ] Add method to generate template csv to ImportFacadeEjb
- [ ] Create import guide (simplified version of the existing case import guide)

UI (cases directory)

- [ ] Move existing case import and export classes to ui.caze.import and ui.caze.export package
- [ ] Add layout and importer classes based on existing case import (CaseImportLayout, CaseImporter)
- [ ] Add PopupButton for import options and button for new case line list import: "Line list import"
- [ ] name existing import "detailed import"
- [ ] add unit test for the import

**Comment by ChristopherRiedelSymeda** [comment]
[ ] Merge branch

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] get rid of first line (CaseData)
