### ISSUE TITLE
Wrong GPS coordinates picked by officers [0.5+0.5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1233]
@MartinWahnschaffeSymeda  We need to find a way to restrict wrong gps coordinates to validate error margins only within the country.. Right now we have case coordinates in Pakistan and Egypt for cases meant to be in Nigeria. @Chinedar is correcting this manually now but we need a solution for this.

**Comment by foyiri** [comment]
Not only cases even contact i just saw about three contact out of Nigeria and there are not confirm contact  we will investigate and fix it

**Comment by MateStrysewskeSym** [comment]
This is mostly about health facilities with wrong GPS data because the phones that the first case for these facilities was created on had issues with their GPS modules. This should be manually corrected in the infrastructure management.

**Comment by MateStrysewskeSym** [comment]
First of all, check whether there's an established way to solve this problem. If not:

- [ ] Add maximum and minimum lat and lon coordinates to properties; if generated coordinates are outside these boundaries, dismiss them
