### ISSUE TITLE
POE Tests and Errors (absence of point of entry list on config menu)

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1235]
![image](https://user-images.githubusercontent.com/35563508/61776866-c7aa5d80-adf3-11e9-9c23-67efed529840.png)
![image](https://user-images.githubusercontent.com/35563508/61776875-cb3de480-adf3-11e9-8f17-4abfb23a3994.png)

We can't create a new case without the point of entries showing...

**Comment by Chinedar** [comment]
Ok I see we have to import the template. No problem. Working on this now.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Exactly - however, there's another error that I've just seen: There are no "constant" points of entry in the system right now (the equivalents to "Other health facility"); this will be fixed with the next update though.
