### ISSUE TITLE
Inability to edit "state" and "LGA" variable on imported list of POE and health facility data on config menu

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1236]
The web platform restricts admins from editing data on "state" and "LGA" variable for POE and health facility names imported as a .CSV file to the SORMAS platform. The "LGA" and "State" variables are greyed out as an edit restriction. 

 This error can be seen in the image below
![Image C1](https://user-images.githubusercontent.com/50739609/61803420-fe02cf80-ae29-11e9-94e8-e794ffe4c7ea.JPG)

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 This is currently a necessary restriction that will be addressed in the future (see #436 and #803)
Changing the references of infrastructure means that all entities that use the infrastructure need to be updated. E.g. when changing the district of a health facilty, all cases that reference the health facility have to be changed to the new district.

**Comment by Iheanacho2027** [comment]
Currently, there is a fresh import that was done today and an edit is
needed for one of the entries, you may have to do it via the back end for
us.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig @danieltomaba Could you take care of this? @Iheanacho2027 please get in touch with Daniel and tell him what kind of change you need. Make sure no cases have been created for this point of entry though.
