### ISSUE TITLE
Poor synchronization activity on SORMAS platform

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1237]
Slow synchronization activity on the mobile app is a big problem for the field users in Nigeria. Synchronization takes about 15 minutes or more in many cases and can be very frustrating for them. I suggest the developers test future releases with an emulator that can virtualize mobile network speeds in Nigeria especially poor ones to solve this problem

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Does it actually take 15 minutes for some of them to do a normal synchronization (e.g. by refreshing the case list)? Or are you talking about the initial synchronization when logging in for the first time?

**Comment by Iheanacho2027** [comment]
Both the normal and the initial synchronisation takes a lot of time

**Comment by MartinWahnschaffeSymeda** [comment]
For initial sync that's well known. We have an issue for it here #1207 ad will hopefully have time for it soon.

For normal sync the situation is more complex:
There are multipe levels of sync that can be done. Normally only basic sync is done. When invalid data is detected (e.g. a user has no longer access to a certian case) a more complete sync is done that would definitely take longer. 

Thus it would be good to know what is acutally done and how long it takes.

@MateStrysewskeSym Looks like we need measure the type and duration of sync processes done and collect and analyize this data. I will create an issue for this. Should be a priority for the next sprint.

**Comment by Iheanacho2027** [comment]
With the latest release 1.25.0, we have made some few observations

1) the initial synchronization has improved but could still be made better
2) For some users the initial synchronization on log in, initially keeps prompting the error message "cant communicate with SORMAS server", this error message is overcome after few more attempts are made to log in
3) After log in is completed, cases dont automatically dropdown on the case list menu, multiple synchronizations with a prompt "background synchronization in progress" have to be made before the cases appear on the case list menu
4) Normal synchronization after entry or editing of cases is still quite a challenge for field users having many cases in their domain, it prompts the error message "cant communicate with SORMAS server". Pls note that this challenge is most peculiar to users having high number of cases in their domain

**Comment by Iheanacho2027** [comment]
There are synchronization issues in the latest release 1.28.0. With a 4G internet connection, normal synchronization keeps failing while initial synchronization works partially as old users are unable to see a list of all previously entered cases while in some cases the dropdown for all diseases in the default case information entry page is unavailable. An urgent fix is needed

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I've released a hotfix and updated the server. Syhchronization should work again.

**Comment by Iheanacho2027** [comment]
There is no APK for the hotfix?

**Comment by MartinWahnschaffeSymeda** [comment]
One thing that makes the sync take a lot of time: We have way too many individual calls to sync the infrastructure:

![grafik](https://user-images.githubusercontent.com/23217632/67274631-2057c800-f4c1-11e9-83b0-c6609a0cea35.png)
