### ISSUE TITLE
Measure and report synchronization duration and details in app [5+1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1240]
To keep it simple use firebase performance monitoring:
https://firebase.google.com/docs/perf-mon

- [x] Experiment with this

What needs to be measured:

1. Duration of establishing a connection to the server
2. Duration of sync for "changes" sync in sum and for synchronizeChangedData, pullAndRemoveArchivedUuidsSince, synchronizeChangedData
3. Duration of sync for "complete" sync in sum and for pullMissingAndDeleteInvalidInfrastructure, pullInfrastructure, pushNewPullMissingAndDeleteInvalidData, synchronizeChangedData. It would be good to know in which context each function is called (eg. synchronizeChangedData as part of changes sync vs. complete sync).
4. "CompleteAndRepull" sync ...
5. Important: Distinguish between initial sync and normal sync

Would be great:

6. For each of these functions we also need the details on how long the sub-functions take. E.g. "executeUuidCall(RetroProvider.getUserFacade().pullUuids())", "RegionDtoHelper().pullMissing(regionUuids)", ...
7. Migrate to Firebase  #1256 

Based on #1237

**Comment by MartinWahnschaffeSymeda** [comment]
Notes on things that could speed up sync:

* shorten UUIDS for sync (e.g. use ids?)
* server calculates which entities a user had access to at time X -> identify which entities need to be deleted from the app now
* only change diffs of DTOs (changes since time X)

**Comment by MateStrysewskeSym** [comment]
- [ ] Create custom traces to measure the duration of individual synchronization processes

**Comment by MartinWahnschaffeSymeda** [comment]
See #1237
