### ISSUE TITLE
NullPointer in SurveillanceDiseaseCarouselLayout poll

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1244]
> 2019-07-30 21:34:44,255 ERROR silenou  d.s.sormas.ui.SormasErrorHandler - Unable to invoke
> method poll in com.vaadin.shared.ui.ui.UIServerRpc
> com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method poll in
> com.vaadin.shared.ui.ui.UIServerRpc
> at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
> at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
> at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
> at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
> at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
> at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
> at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
> at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602)
> at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
> at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
> at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
> at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
> at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:589)
> at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:409)
> at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4981)
> at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:657)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
> at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
> at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
> at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
> at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
> at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:609)
> at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
> at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
> at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
> at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
> at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4953)
> at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4941)
> at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
> at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
> at com.sun.proxy.$Proxy512.doFilter(Unknown Source)
> at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown
> Source)
> at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:58)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
> at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
> at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:579)
> at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
> at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
> at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
> at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
> at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
> at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
> at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
> at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
> at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
> at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
> at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
> at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
> at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
> at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.reflect.InvocationTargetException: null
> at sun.reflect.GeneratedMethodAccessor3765.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
> ... 77 common frames omitted
> Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method poll in
> de.symeda.sormas.ui.dashboard.surveillance.SurveillanceDiseaseCarouselLayout$$Lambda$539/1043222268
> failed.
> at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
> at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
> at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
> at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
> at com.vaadin.ui.UI.access$300(UI.java:123)
> at com.vaadin.ui.UI$1.poll(UI.java:201)
> ... 81 common frames omitted
> Caused by: java.lang.NullPointerException: null

**Comment by MateStrysewskeSym** [comment]
This seems to happen when users are in another view, e.g. in the case directory. Maybe we need to make sure that polling is disabled as soon as the dashboard is left.
