### ISSUE TITLE
Discrepancy between filtering from cases directory and statistics section 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1248]
Hi Folks,
I used this criteria to filter data both from cases directory and statistics section:
reporting time: 1 Nov 2017 to 30 May 2019
disease: Lassa
State: Ebonyi
From cases directory, I got 419 cases and from statistics section I got 416 cases. I validated the calculation using R by counting the entries in the database and got 419. What can be the possible reason for this less count in the statistics section?

**Comment by MartinWahnschaffeSymeda** [comment]
Everything's working as intended.
