### ISSUE TITLE
Inability to report cases coming from a particular LGA on SORMAS

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1251]
An error occurs when trying to create a case from ovia north-east LGA in edo state as shown in the image below. This LGA is the only LGA identified so far having this bug, other LGAs having this similar bug which havent been identified may also exist
![bug A](https://user-images.githubusercontent.com/50739609/62585882-ee1bce80-b8b2-11e9-8a36-0727fb398dee.JPG)

**Comment by MateStrysewskeSym** [comment]
I've identified the problem. There was another measles case in the same LGA whose epid number ended with "017." - for some reason, our algorithm to generate a new epid number didn't erase the "." when it tried to retrieve the currently highest epid number for this LGA. I've manually removed the "." from the existing case, so you should not run into this error again, and we'll fix the bug for this upcoming release.
