### ISSUE TITLE
Add a completeness value to the retrospective duplicate detection [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1253]
Very likely a percentage value that shows the ratio of the fields that have been filled in.

Open questions:
* If all fields are taken into account, the percentage value will be very low most of the time; should only a subset (the most relevant) fields be considered? If yes, they need to be defined
* What about the number of contacts, samples, etc.? Should those be incorporated into this completeness value or should there be another value for it?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] define a list of relevant fields:

* investigation done
* has onset date
* has symptom
* has contact
* has sample
* .. TODO

- [ ] calculate completeness value whenever case (or something relevant) is changed. Perist in entity. Don't use in app -> no api change. 
- [ ] use in duplicate mechanism

**Comment by MateStrysewskeSym** [comment]
- [ ] Put all the core data variables in the merge guide
- [ ] Disable confirm button on case creation when nothing has been selected

**Comment by MateStrysewskeSym** [comment]
- [ ] keep a list of hidden case pairs and keep them hidden when doing a manual reload

**Comment by MateStrysewskeSym** [comment]
- [ ] Put a number displaying the amount of duplicates in the list into the filter bar

**Comment by MateStrysewskeSym** [comment]
- [ ] Change caption to "Number of detected potential duplicates:"
