### ISSUE TITLE
Migrate to Firebase [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1256]
The service runs out end of October and we need to use firebase for #1240 anyway.

- [x] Find out what needs to be done

**Comment by MateStrysewskeSym** [comment]
- [ ] Delete project and create a new one to get a new app ID; don't push config file to GitHub

**Comment by MateStrysewskeSym** [comment]
- [ ] Find out whether there's a workaround for not having the google-servies.json file checked in (e.g. dummy file, additional build variant)
