### ISSUE TITLE
Redefining similarity measure in identifying duplicates. [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1269]
The current similarity measures proposed pair of cases with only the same last name but different sex, DOB, onset date, etc. We need to improve this be defining a similarity  measures that takes all the core variables in account and return the measured value for each pair of proposed duplicates in addition to the proportion of completeness.
Good information to read below on Fellegi-Sunter method:
<https://ec.europa.eu/eurostat/cros/content/fellegi-sunter-and-jaro-approach-record-linkage-method_en>
<https://en.wikipedia.org/wiki/Record_linkage#Data_preprocessing>

**Comment by hzi-braunschweig** [comment]
@bernardsilenou  @MateStrysewskeSym  Threshold of 0.7D is ok for now but Bernard noticed some issues which he will highlight now. Please lets update the Nigeria server with 0.7D for now. @bernardsilenou @Chinedar @foyiri Please talk to your guys.. no one should use the duplicate search for now. This is very important. We have been testing it and the algorithm needs some changes. Thanks

**Comment by bernardsilenou** [comment]
After having a detailed test on the duplicate detection  module, which we all know is an integral and delicate function to use, we decided to improve the sensitivity and specificity of the pair of possible duplicates suggested to the user.  Two main issues came up during the testing:
1. Cases with with names meeting the similarity cut of value and having the same state but different sex, LGA, health facility, date of report, etc  were suggested as pairs.
2. Cases with names that does not meet the similarity criteria but heave the same state, LGA, sex, etc were not suggested to the user.
Option 1 can lead to false matching and option 2 can lead to under detection of duplicate cases.
We need to improve the total similarity score not to be driven by the similarity score of the names but also the other variables with different weights for each variable.
For example if the names of 2 cases meets the similarity score cutoff but that of the other variables is zero, then the case should not be suggested to the user. Likewise if the similarity cutoff of the name is not met and all the other variables are 100% similar, then the pair should be suggested to the user.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou @danieltomaba I don't really see how it would be beneficial to suggest case pairs with very different names to the user just because they're in the same health facility in a similar time frame. This would basically suggest all males who were submitted to the same health facility in a specific time frame as duplicates which would lead to a lot of false detections.

The names should always be the leading variable when it comes to detecting duplicates as long as we don't have some unique identifiers in the system because that's basically the only reliable data that actually differentiates those cases from each other.

I suggest we discuss this in detail in our next sprint review.

**Comment by bernardsilenou** [comment]
I absolutely agree with you Maté. I think my point was not well transmitted.
In point 2 above, I said "Cases with names that does not meet the similarity criteria". This does not include dissimilar names. By adding an additional one character to a name or playing with it a bit causes the similarity to be less than 70%  and the pair are not picked up by the algorithm.
 We discuss more in person latter.

**Comment by MateStrysewskeSym** [comment]
Add additional variables to the duplicate detection (only if available for both cases):
* Date of birth / age
* Sex 
* Onset date (period)

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove age
- [ ] Only take out duplicate if Sex AND DOB are different
