### ISSUE TITLE
Make user roles fully configurable

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1271]
We thought it might be good to change the structure of SORMAS in terms of user role rather than personas like Infromant, SO, etc

**Comment by MartinWahnschaffeSymeda** [comment]
General idea is to get rid of fixed user roles and replace them with user rights only that can be combined in a configurable user role.
The default user roles would be based on the existing SORMAS user roles.

**Comment by MartinWahnschaffeSymeda** [comment]
See #898
