### ISSUE TITLE
Lassa Fever Case management variable for export 

### ISSUE THREAD

**Issue by chukwuemekauzoho** [hzi-braunschweig/SORMAS-Project#1275]
@SeriousMartin in reference to #1185  
The case management export has become a serious issue in the Lassa Fever TWG. There's a need to speed up on having a Case management export function just like we have for surveillance export.
The Clinicians have also asked that all the variables (including signs and symptoms) as seen in the form should be exported on a flat table, just like we have for surveillance export. This is urgent.
@SeriousMartin @Chinedar @foyiri 

[Case.Management.Variables.for.SORMAS_14-Jan-2019-vFinal.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3538803/Case.Management.Variables.for.SORMAS_14-Jan-2019-vFinal.docx)

**Comment by MateStrysewskeSym** [comment]
@chukwuemekauzoho That's already been done in this sprint and will be part of the next release: #1266 

Please make sure to always search for similar issues in this repository before opening new ones to avoid duplicates.
