### ISSUE TITLE
Allow users to create and save sets of columns for the export [5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1276]
These need to be defined by disease.

First step:
- [x] Create mockups for UI

Possible solutions:
* Save field selection as String in database (together with user_id and query name)
* Make multiselect customizable
* Potentially don't save field names, but IDs of checkboxes to avoid exports becoming corrupt when the data model changes

**Comment by bernardsilenou** [comment]
Just an idea how it can be done. Attached is a figure from LimeSurvey
![image](https://user-images.githubusercontent.com/12996724/64353280-ca58bf00-cffd-11e9-9550-0d6a39763d3c.png)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou This looks good for the future once we have additional options for the export. For now, I'd like to concentrate on making the selection of the potential columns more user-friendly than in the screenshot you provided.

Mockups:
https://app.moqups.com/3NUENEwuOE/edit/page/a4f39d166
https://app.moqups.com/3NUENEwuOE/edit/page/a6a43c5ca

**Comment by MateStrysewskeSym** [comment]
- [ ] Add radio buttons to the list of export configurations OR add an export button for every row
