### ISSUE TITLE
Aggregated disease reporting with app [5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1277]
For diseases that  do not have a process module in SORMAS, we should add them to the table of aggregated count report, i.e. weekly  aggregate report table. For diseases that are in SORMAS, updating this table will means  adding a new case, for others, it will mean updating the cell count in the table. We should review the interface of other tools to get the best way of categorizing the aggregated counts i.e. either by age group, sex, outcome, etc

**Comment by MartinWahnschaffeSymeda** [comment]
Disease that would be relevant:

* Malaria
* Typhoid fever
* Acute viral hepatitis
* Non-neonatal tetanus
* HIV/AIDS 
* Schistosomiasis
* Soil transmitted helminths
* Trypanosomiasis
* Diarrhea w. dehydration (<5)
* Diarrhoea with Blood (Shigella)
* Snake bite

**Comment by MartinWahnschaffeSymeda** [comment]
Things to define and consider:

1. Define how the weekly report is done. Obvious possibility is to extend the weekly report with a form where users can enter the case counts of the above diseases
2. Is it possible to have aggregated and case-based reporting for a disease at the same time for a single user? 
3. Is it possible to have aggregated and case-based mixed for the country, with one region doing aggregated and one region doing case-based? What about outbreak situations?
4. How do users access the reported numbers? Should they be visible in the dashboard? Should we extend the existing weekly reports view in the web app to also show aggregated case counts for districts/regions (and not only users).
5. The reported case counts probably also need to be accessible in the statistics

**Comment by bernardsilenou** [comment]
Some points I like to comment on:
2. I think it should be possible. However, there should be some logic to make sure that the aggregate count = sum( case based cases) in the same time interval. The challenge that i see here is how time is defined? report date or onset date
3. yes, its possible and this will be useful for outbreak situation just as you said
4. I think we should not sum case based and aggregate reporting. both on dashboard and statistics we should have a way to choosing if we need to view both or just one version

**Comment by MartinWahnschaffeSymeda** [comment]
### Android app

- [ ] add a new view for aggregated reporting "mSERS"
- [ ] list all diseases. For each disease have three text fields: new cases, lab confirmed cases, death cases
- [ ] the report can be submitted any time

### Web app

Data entry can be added later

**Comment by MartinWahnschaffeSymeda** [comment]
### Backend

- [ ] entity holds new case count, lab confirmations, deaths for a disease, epi-week, region and optionally district and health facility. Also the reporting user. It's possible that two users report case counts for the same time frame and district/heath facility. These reported numbers are independent and add up.

### Android app

- [ ] add a new view for aggregated reporting "mSERS"
- [ ] list all diseases. For each disease have three text fields: new cases, lab confirmed cases, death cases
- [ ] the report can be submitted any time

### Web app

Data entry can be added later

- [ ] Create mockup for the web app. Should be a new view available from within the cases view. Ideas: rows are diseases, columns are "new cases, lab confirmations, deaths". Optional filter by region, district, health facility

@hzi-braunschweig What about communities? Do community informants report on community level (not for a health facility)?

**Comment by MateStrysewskeSym** [comment]
- [ ] Try to use retainAll for DiseaseConfigurationFacadeEjb and DiseaseConfigurationCache
- [ ] add comments to getAllDiseases method
- [ ] add unit tests

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Remove 0s from mobile app for diseases where nothing has been entered
