### ISSUE TITLE
Navigation error in mobile app case entry

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1284]
When entering or editing case information in the mobile app prior to the recent release 1.25.0,, the normal route the system takes as the user saves case entry information is : case information → person information → Hospt. Info. → symptom info → Epid info → case contacts → case samples → case tasks

A bug exists in the recent release 1.25.0, as there is a navigation from hospt. info to epid. info whenever the user saves entry information thereby missing the navigation into symptom information. This also applies to the navigation from epid info to case tasks thereby missing the navigation into case contacts and case samples

**Comment by Iheanacho2027** [comment]
Pls note, this bug still exists in the recent release1.26.0, the system still misses the navigation from hospt.info to symptom info, and also from epid info to case contacts and case samples

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Please have a look at the right-hand side; the issue is currently in the "Sprint" project, which means that it has been resolved in the current sprint and will be part of the next release.

**Comment by Iheanacho2027** [comment]
Alright, cool
