### ISSUE TITLE
Re-design the login page for play versions [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1289]
@danieltomaba @hzi-braunschweig Please create mockups for this

**Comment by hzi-braunschweig** [comment]
See mockup as requested
![SORMASPlayMOckup](https://user-images.githubusercontent.com/19344651/64100729-77b4a400-cd6c-11e9-95ab-008c5d26f898.png)
@MateStrysewskeSym @bernardsilenou @ChristopherRiedelSymeda @MartinWahnschaffeSymeda

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/64101972-44274900-cd6f-11e9-86f9-2c6ecd6ab82d.png)
I prefer this one @MateStrysewskeSym

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] Move stylenames to CssStyles
- [ ] Remove default values
