### ISSUE TITLE
Error on Case Management Export

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1301]
An error exists when exporting case management data as shown in image A. The exported zipped file becomes corrupted as shown in image b

![image A](https://user-images.githubusercontent.com/50739609/64818729-90129300-d5a4-11e9-99d0-8688f6dd0c44.JPG)

![Image B1](https://user-images.githubusercontent.com/50739609/64818737-986ace00-d5a4-11e9-89e7-f76489dd19f1.png)

**Comment by MateStrysewskeSym** [comment]
Interestingly, I can reproduce this bug both on the Nigerian system as well as on our demo server, and also on my development system if I switch to the Master branch and use a copy of the demo server database. With the current development version and my development database however, the export works fine. I'll put this on hold until the next release to see how the Nigerian and demo systems behave afterwards. Should the error still persist, I will further investigate it then.

**Comment by MateStrysewskeSym** [comment]
With the new release and on the demo system, this also happens in the Dashboard. The core problem seems to be a NullPointerException at org.hibernate.query.criteria.internal.predicate.CompoundPredicate.renderer(CompountPredicate.java:166).
