### ISSUE TITLE
Wrong calculation of new test result on the SORMAS Dashboard [1]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1302]
Currently on the SORMAS dashboard, number of new test results (positive, negative and pending) for priority diseases are calculated by adding all results entered for a particular case instead of using the the single result on the ''final laboratory result" variable that exists on the sample information page of the entered case. The algorithm needs to be changed @hzi-braunschweig  @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 If I understand you correctly, you want to exclude pathogen tests from the dashboard that are not determining the final lab classification of the sample? I.e., there will never be more than one test result counted for a particular sample on the dashboard?

**Comment by Iheanacho2027** [comment]
Exactly @MateStrysewskeSym

**Comment by MateStrysewskeSym** [comment]
- [ ] Add a "labResultChangeDate" to sample (entity only) that is updated everytime the final laboratory result is changed
- [ ] "New test results" on dashboard counts the number of samples whose labResultChangeDate has changed during the specified period

**Comment by MateStrysewskeSym** [comment]
- [ ] Only count one sample per case
