### ISSUE TITLE
Improve performance of detailed exports [?]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1314]
We have serious issues with the detailed exports to the point where the servers crash when users try to export too many cases at once. This needs to be fixed.

First steps:
- [x] Temporarily remove detailed export from export dropdown
- [x] Don't pre-select checkboxes when creating new export configurations
- [x] Automatically limit case management export to cases with case management data
- [x] Reduce size of chunks that are queried to potentially reduce the load on memory

Ideas to further mitigate the problem:
- [x] Start a new transaction for every chunk of data
- [x] Use read-only mode to not load unnecessary data
- [x] Make single "in" queries for entities like symptoms

**Comment by Iheanacho2027** [comment]
Yes very important, detailed export of above 1,800 cases causes the server to crash while detailed export of between 1000 -1500 cases takes alot of time. Increasing the RAM of the database server could solve this. Additionally in future, we need to start thinking of developing another platform or platforms for migrating archived cases where those cases can't be edited and cases cant be created.
