### ISSUE TITLE
Inability to edit select ward in already created health facility in configurations menu and error in import functionality

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1319]
In the 1.26.1 release as currently loaded in the nigerian server, there is a bug in the import functionality whereby that affects previously imported health facilities and imported cases where health facilities arent included.

For the previously imported health facilities without wards which are asterisked in red as compulsory variables, there is no dropdown for wards as shown in the image A2 below.

![image A2](https://user-images.githubusercontent.com/50739609/65280671-d168ec80-db28-11e9-9a14-251b24a10915.JPG)
 

Also the import functionality allows import of cases which do not contain health facility names instead of rejecting them as an error in the error report as shown in image B2 below

![image b2](https://user-images.githubusercontent.com/50739609/65280721-e9d90700-db28-11e9-9fb7-a1cea970a2c6.JPG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 There is no health facility import, so I don't really know how you were able to get a health facility without a community into your database. It's currently not supported to change the region, district or community of a health facility in retrospection; there is an issue for this: #803 

Your second point is a bug and will be fixed.
