### ISSUE TITLE
Missing therapy information entered previously

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1320]
A case having missing therapy information previously entered before the 1.26.0 release now gives an error message as shown  via the case ID shown in the image below. This is a bug

![c5](https://user-images.githubusercontent.com/50739609/65282126-117d9e80-db2c-11e9-983c-bb3281bcdb50.JPG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Can you have a look at this again? I'm pretty sure that this bug has been resolved with the new version hat has been deployed on the Nigerian server. Does it still exist?

**Comment by Iheanacho2027** [comment]
Yes its fixed and resolved in 1.27.2. A job welldone
