### ISSUE TITLE
Change of navigation bar on case directory and reports menu

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1321]
The current navigation bar on the case directory and reports menu as displayed by the arrow in the first and second image respectively, should be changed to this type of navigation bar (with forward and backward arrows) displayed by the arrow in the third image for easy navigation by field users

![Image D1](https://user-images.githubusercontent.com/50739609/65282890-eeec8500-db2d-11e9-904c-3c3a6f520827.JPG)

![Image D2](https://user-images.githubusercontent.com/50739609/65282919-0461af00-db2e-11e9-9c9a-9fd7b18d3535.JPG)

![Image D3](https://user-images.githubusercontent.com/50739609/65282930-0d528080-db2e-11e9-8e84-b87d40aa5c3f.JPG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Is it possible that something went wrong during image upload? Your images only display scroll bars and I don't really know what this is about.

**Comment by Iheanacho2027** [comment]
The scroll bars displayed by the arrows in the first and second image are the scroll bars for navigation currently available on the case directory and reports menu of the SORMAS platform, its usually not user-friendly scrolling down with those bars when there are lots of cases in the case directory.

I am therefore proposing that those scrolling bars in the first and second image be replaced with the scrolling bar which has forward and arrows as displayed in the third image

**Comment by Iheanacho2027** [comment]
You could open the three images one by one and check the SORMAS platform to properly understand what i mean

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 This is browser-specific. Firefox actually has these arrows to the left and right of the scroll bar while Chrome does not. I don't think this is something we can easily change. Field users can simply switch to another browser if they're unhappy with the way their current browser is handling this.

**Comment by Iheanacho2027** [comment]
Ohk great, didnt know about this but bear in mind that chrome is more commonly used as compared to firefox
