### ISSUE TITLE
Error in CRS limited user account

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1323]
In 1.26.1 currently loaded in the nigerian server, there exist an error in the CRS limited user account where the case contacts displayed shows all the contacts in the system instead of only contacts related to CRS, this is shown in the first image.
![CRS error 2](https://user-images.githubusercontent.com/50739609/65314433-3f93ca80-db8e-11e9-8df2-4ef064bcd1eb.JPG)

Also the cases displayed in the case directory of the CRS limited user account shows all cases in the system instead of only CRS cases and also gives an error message. This is shown in the second and third images

![CRS error 1a](https://user-images.githubusercontent.com/50739609/65314569-7833a400-db8e-11e9-9af2-137e578047ba.JPG)
![CRS error 1b](https://user-images.githubusercontent.com/50739609/65314585-7e298500-db8e-11e9-8700-f93acb76e834.JPG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 The first bug is associate
