### ISSUE TITLE
Import function rejects .CSV file

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1326]
A strange occurence exists as the nigerian server loaded with 1.27.2 rejects a .csv import file while the helmholtz server also loaded on 1.27.2 accepts it

![bbbbb](https://user-images.githubusercontent.com/50739609/65748097-05c94380-e0fb-11e9-8e5c-ee3c8d348d26.JPG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 It should be working again. Apparently, the server was rebooted yesterday in the evening and the payara user did not have write access to the temp directory anymore.

The hard drive on the server probably needs to be set to support acl mode statically:
https://linuxconfig.org/how-to-manage-acls-on-linux

**Comment by Iheanacho2027** [comment]
Yes it's now working
