### ISSUE TITLE
Line listing case entry for mobile app

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1330]
Refine after mockups in #1172 have been done

**Comment by ChristopherRiedelSymeda** [comment]
Review notes:

- [ ] merge with case creation activity
- [ ]  try to reduce it to fit into one screen
- [ ] replace create and clear buttons with buttons in navigation row

**Comment by ChristopherRiedelSymeda** [comment]
Implementation tasks:
- [ ] Add fields and checkbox to fragment_case_new_layout
- [ ] First and last name in one line (see fragment_person_edit_layout)
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by ChristopherRiedelSymeda** [comment]
Merged into development.
Sometimes a graphic error appears in the form of an unfolded spinner. Someone should take another look at this.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] deactivate rapid case entry in app until config is done
- [ ] show save notification

**Comment by Iheanacho2027** [comment]
As a follow up on this, will the rapid case entry on the mobile app later on get activated?, because the feature is currently unavailable on 1.30.1

**Comment by MartinWahnschaffeSymeda** [comment]
Yes, it will. We have to implement #1346 first, though.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Please can you update the Nigeria Server? @Iheanacho2027 has gone through it testing 1.30.1. Thanks

**Comment by bernardsilenou** [comment]
This is a comment after testing version 1.31.0. When a new case is saved, all the field are deleted but the date of report of the previous case is retained. We should not retain any field apart from the disease name

Users with enabled rapid case entry should be able to deactivate it and do normal entry if they want.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou This was already discussed in detail in the last sprint reviews. I believe we even talked about the exact point of users not being able to toggle rapid case entry. It was a specific request that users are forced to use it, and we also already decided to retain as many field values as possible because it's very likely that users will enter cases with the same report date/disease in succession before moving on to other diseases/dates.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym 
I will discuss it with the HZI tomorrow and let  you know.

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym you are right in the sense that users should not be allowed to activate from full entry to line list entry. But we should allow the users who have been activated to do the line list entry by the supervisor to deactivate it back to full entry when he is done. This would avoid a user staying on rapid case entry if the supervisor forgets to activate a deadline for reverting back. I know the system activates an end date but we should allow if the user does the work before the end date.  @bernardsilenou  @MartinWahnschaffeSymeda

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Alright. This is different to how you described it to us when we talked about this feature and I'm not quite sure I understand you completely. I suggest that we talk about this again when we meet next time.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym 
As Daliel mentioned above, the users in districts that have been given the right for rapid case entry should be able to toggle between rapid case entry and full case entry within the time frame that the supervisor has set the rapid case entry. When this time is over, then the users should only be able to do full case entry. Users that have not been activated for rapid case entry will stay with only full case entry and will not be able to toggle.

With respect to date of report, we have to remember that rapid case entry is useful often for retrospective case entry, in this situation, it is unlikely to find many cases with the same date of report. Thus retaining the date of report is prone to error.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] re-add the checkbox that allows users to do rapid case entry. Should be displayed below the disease field if rapid case entry is active
