### ISSUE TITLE
Use build()-method instead of constructor for all DTOs [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1340]
The build methods should always be used to create new entries, because they set the needed default values.
Only exception is when a dto is filled from a database entity.

- [x] ~~Either make the constuctor protected (make sure this works with ReST) **or** make it at least depcreated~~ -> I have looked into this and decided it's not worth the overhead. It would need a lot of LOC just to make sure no one creates a 
- [x] make sure dto build()-methods are used everywhere (except in toDto()-methods)
- [x] add comment to EntityDto class on how this is (NOT) supposed to be used
- [x] Replace the usage of CaseDataDto in the bulk case edit logic with a dedicated CaseBulkEditData
- [x] move actual update logic to it's own method in CaseController
- [x] Replace the usage of ContactDto in the bulk case edit logic with a dedicated ContactBulkEditData

**Comment by MateStrysewskeSym** [comment]
- [ ] Change "buildt" in comment to "build"
