### ISSUE TITLE
Change "RUMOR" to "SIGNAL" under event data in event menu. 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1342]
In Event Based Surveillance, the word **rumor** has been replaced with **signal**. SORMAS is being fully integrated into the connect center so that rumours/signals coming from the public can be immediately logged into SORMAS. 
The Event Based Surveillance team has now requested that the term rumor be changed to signal within the SORMAS platform. 
@hzi-braunschweig

**Comment by bernardsilenou** [comment]
I also agree, "Signal" is the correct name

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Replace the description of Event Status
