### ISSUE TITLE
Make line listing for app configurable [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1346]
defines availablity of rapid case entry in app
  - put in one UI with outbreak config
  - have their own config entities
  - no rapid case entry checkbox, instead an info text
  - ideally configuring users should have to enter how long line listing is supposed to be done
  - default duration for line listing should be 21 days

**Comment by MateStrysewskeSym** [comment]
Mockups:

**First option (label overview)**
Region level: https://app.moqups.com/3NUENEwuOE/view/page/a491312f2
Nation level: https://app.moqups.com/3NUENEwuOE/view/page/ad37c684f

**Second option (grid)**
Region level: https://app.moqups.com/3NUENEwuOE/view/page/afb79a1a4
Nation level: https://app.moqups.com/3NUENEwuOE/view/page/a8df2d96c

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Remove disabled districts from the regional view
- [ ] Add a popup containing a list of all districts in a region (or all districts in all regions with a filter) containing the district name, a checkbox to enable/disable line listing and a date field to edit the end date
- [ ] Add "Edit" buttons below the disease names to open the popup
- [ ] Move the end date of districts below the district name in the (read-only) overview

**Comment by MateStrysewskeSym** [comment]
New mockups:

**Nation level:**
Overview: https://app.moqups.com/3NUENEwuOE/view/page/ad37c684f
Edit popup: https://app.moqups.com/3NUENEwuOE/view/page/aa4abfd26

**Region level:**
Overview: https://app.moqups.com/3NUENEwuOE/view/page/a491312f2
Edit popup: https://app.moqups.com/3NUENEwuOE/view/page/afb79a1a4

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda The issue is basically completed. We need to talk about how we can add visual feedback to the app for users to know that line listing will be enabled.

**Comment by MateStrysewskeSym** [comment]
- [ ] Don't open grid popup when adding a disease on nation level
- [ ] Try to forward the clicked disease to region level
- [ ] Remove changedConfigurations set from edit layout, add method "getChangedConfigurations" to grid
- [ ] Extract "_history" strings to a constant in ADO
- [ ] Remove activeCheckboxes and endDateFields, set values for all configurations and reload instead (and add all configs to changedConfigs)
- [ ] Add HashSet<Config, DateField> cache and use it in addValueChangeListener of check box to avoid reload
- [ ] Add a saveFeatureConfigurations method
