### ISSUE TITLE
Add "reporting user role" filter to statistics [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1348]
- [x] extend criteria with list of user roles
- [x] extend statistics SQL query
- [x] extend available filter options with "reporting user role" (case)

**Comment by MateStrysewskeSym** [comment]
Trying to group by reporting user role throws this error:

´´Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.buildCaseGroupingSelectQuery(CaseStatisticsFacadeEjb.java:971)
	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.buildCaseCountQuery(CaseStatisticsFacadeEjb.java:481)
	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.queryCaseCount(CaseStatisticsFacadeEjb.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)´´

**Comment by ChristopherRiedelSymeda** [comment]
fixed

> Trying to group by reporting user role throws this error:
> 
> ```
> Caused by: java.lang.NullPointerException
> 	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.buildCaseGroupingSelectQuery(CaseStatisticsFacadeEjb.java:971)
> 	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.buildCaseCountQuery(CaseStatisticsFacadeEjb.java:481)
> 	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjb.queryCaseCount(CaseStatisticsFacadeEjb.java:80)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] user report grouping does not work
- [ ] add unit test for this case

**Comment by ChristopherRiedelSymeda** [comment]
> * [ ]  add unit test for this case
that's not feasible in a senseful way
