### ISSUE TITLE
Error message trying to save on the 1.30.1 hot fix  [1]

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1361]
please take a look at this error .when you try to save a case on version 1.30.1 on helmholtz server we need this fix urgently we have training going on in Ghana @danieltomaba @MartinWahnschaffeSymeda @MateStrysewskeSym @Chinedar @bernardsilenou

**Comment by MartinWahnschaffeSymeda** [comment]
@foyiri @Chinedar 
I have tried to create a new case on https://sormas.helmholtz-hzi.de and also edited it.
Works without problems. Since I can't look into the log files of this server, I'll need some more details.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Try to reproduce this by starting with a "very old" apk (1.18) against sormas.symeda.de and then using the automatic update.

**Comment by MartinWahnschaffeSymeda** [comment]
Related to this (happens during startup):


> Fatal Exception: java.lang.RuntimeException
> java.sql.SQLException: Unknown field 'animalVaccinationStatus' from the Android sqlite cursor, not in:[animalCondition, areaConfirmedCases, wildbirds, bats, birds, burialAttended, cattle, closeContactProbableCase, dateOfLastExposure, directContactConfirmedCase, wildbirdsLocation, directContactProbableCase, poultryEat, poultryDetails, poultry, fleaBite, gatheringAttended, otherAnimals, otherAnimalsDetails, percutaneousCaseBlood, placeOfLastExposure, primates, processingConfirmedCaseFluidUnsafe, wildbirdsDetails, rodents, poultrySick, poultryDate, poultrySickDetails, poultryLocation, swine, tickBite, traveled, wildbirdsDate, waterBody, waterBodyDetails, waterSource, waterSourceOther, changeDate, creationDate, id, lastOpenedDate, localChangeDate, modified, snapshot, uuid]

There is a bug in the DatabaseHelper update script. A "break" that should not be there..
Another incident that makes clear we need a unit test for the automatic database update process.

Solution for the bug: 

- [ ] Reproduce it (create a database with the bug)
- [ ] Fix the script and see if the bugged database is corrected
- [ ] Check if it works with healthy databases

**Comment by MartinWahnschaffeSymeda** [comment]
From the stack trace:

> Caused by java.sql.SQLException
> Unknown field 'animalVaccinationStatus' from the Android sqlite cursor, not in:[animalCondition, areaConfirmedCases, wildbirds, bats, birds, burialAttended, cattle, closeContactProbableCase, dateOfLastExposure, directContactConfirmedCase, wildbirdsLocation, directContactProbableCase, poultryEat, poultryDetails, poultry, fleaBite, gatheringAttended, otherAnimals, otherAnimalsDetails, percutaneousCaseBlood, placeOfLastExposure, primates, processingConfirmedCaseFluidUnsafe, wildbirdsDetails, rodents, poultrySick, poultryDate, poultrySickDetails, poultryLocation, swine, tickBite, traveled, wildbirdsDate, waterBody, waterBodyDetails, waterSource, waterSourceOther, changeDate, creationDate, id, lastOpenedDate, localChangeDate, modified, snapshot, uuid]

Problem goes down to a bug in the DatabaseHelper.

- [ ] fix problem
- [ ] test with invalid database
- [ ] test with valid database
- [ ] release hotfix

**Comment by MartinWahnschaffeSymeda** [comment]
Note:

To push an old version of the database to my emulator I had to fix some user permission that seem to have gotten wrong over time. In order to do so, I did the following:

1. Add android SDK Tools to system PATH: C:\Users\mwahn\AppData\Local\Android\Sdk\platform-tools
2. Cmd: adb shell -> Opens linux command line in device
