### ISSUE TITLE
Mobile App does not contain Anthrax and Rabies When app updates automaticaly [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1362]
When the apk file is downloaded and installed manually on tablet, all diseases exist. But when installed automatically:
1 Rabies and anthrax do not exist: Maybe properties field for diseases are not updated for automatic update.
2 app crashes on start up -> #1361

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] When no disease configuration for a certain disease is available do same behaviour as when configruation with null values is available
- [ ] When a disease configuration is modified (during sync) reset the DiseaseConfigurationHelper

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] check whether we really need the ActivityRule in the unit test (since the is no need for UI)
- [ ] add init to DiseaseConfigurationCacheTest 
- [ ] Fix DiseaseConfigurationCacheTest  assertion (use size instead)
- [ ] Add comment to DiseaseConfigurationCache:L46
