### ISSUE TITLE
Automatic suggestion to the user to create a new case of a new disease when one of its samples are positive for the new disease

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1366]
I had a Lassa case with positive lab test for Lassa for one of its samples. SORMAS ask me if I want the final lab classification of the case to be positive and the case classification to be confirmed. This is OK.

When I latter test more samples for dengue and had a positive lab results, SORMAS did not ask me is I want to create a new case for dengue. We agreed in the past that when one of the samples for a case is positive for a new disease, SORMASS should autimatically ask the user if they want to create a new case and transfer all the data from old to new the case. This is the same  algorithm when a case is tested negative for an initial disease and positive fro another disease.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou This is about the web application, right?
Was the "verified by supervisor" field checked? Otherwise the process is currently not triggered.

**Comment by MartinWahnschaffeSymeda** [comment]
See #1435
