### ISSUE TITLE
Case contacts import [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1368]
A case may have a lot of contacts. Thus we need a way to import a list of contacts from within a case. This needs to include automatic duplicate detection.

(split from #1154)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add import feature to case contacts view
- [ ] import similar to case import. All created contacts need to be assigned to the active case
- [ ] evaluate how to implement duplicate detection similar to how it's done for the case import, but restricted to the contacts of the case

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] Merge into development
