### ISSUE TITLE
Automatic assignment of SO for cases created from the web

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1370]
When a DSNO creates a case he should be the one assigned to it.

Also make sure that the following points work afterwards:

* Cases created by localized dsno/dsno are not assigned to the respective dsno by default (see point 4)
* Case investigation task for cases created by localized dsno is assigned to SS, CS, and  Event Officer, this should not be the case. This task should be assigned to the same dsno.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou I can't reproduce the problem. Based on the code, it seems to be impossible that a surveillance officer creates a case in the mobile app without being automatically assigned to it. 

A guess what may have happened:
1. The user did not have the surveillance officer user role
2. The case was created in the web app

**Comment by MateStrysewskeSym** [comment]
See #1376

**Comment by MartinWahnschaffeSymeda** [comment]
Talked about it today. It's actually related to cases created form the web UI.
Suggestion:

- [ ] when the health facility of the case does have an informant use the officer of that informant
- [ ] otherwise pick a random officer of that district

**Comment by MateStrysewskeSym** [comment]
Another observation: When an admin creates a case in a district with a SurvOff, the SurvOff is not assigned as the responsible officer and the task is assigned to the SurvSup instead.
