### ISSUE TITLE
Inconsistent assignment of task

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1376]
This is a an image of a fake Lassa case created by SO, CO on Ghana server: 1.30.1. I realized there are issues with task management and assignment. To reproduce this, you need to create like 6 cases of different diseases in one district having more than one SO. Some cases will be OK and others will have these issues:
1. Responsible district disease control officer is not assigned by default
2. Investigation task is assigned to SS (Luiz), this might be because there is no SO for the case. As a result, the investigation task will appear in the task drawer for the case but not in the task menu for the SO.
3. For some of the case investigation task that appears under task menu,  I clicked on the task and investigate the case and when I returned to set the task to done, it disappeared from the task menu completely. The moment you open a task and latter open the case through the task, the task disappears.

![TaskAssignment](https://user-images.githubusercontent.com/12996724/69483164-3d671a00-0e24-11ea-9248-160191e3a870.jpg)

**Comment by MateStrysewskeSym** [comment]
This is associated with #1370
