### ISSUE TITLE
App: Changing user has to clear cases and similar data [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1378]
From #1375:

When the account of a user is changed, the cases form the old user were carried over and displayed on the view of the new user. Changing the user on a tablet should clear the data and cache on the mobile DB automatically.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] have a look into the history to see why we have done it like that
- [ ] delete production data when user logs out. Keep infrastructure data
- [ ] check for unsubmitted changes and show warning (see re-pull feature)

**Comment by MartinWahnschaffeSymeda** [comment]
Checked why we have done it like that:

When a user's password changes for some reason, the user has to login again and had unsynchronized data, this data would be lost.

- [ ] remember the last user and only clear data when the user changes.

**Comment by ChristopherRiedelSymeda** [comment]
Fix InfoResource
