### ISSUE TITLE
Lab users in Ghana can create cases but not samples and can't see samples sent to them

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1379]
There is a bug with the lab users module that we need to urgently address, see picture attached. The default rules of a lab are no longer respected both on Ghana and HZI server:
1. Lab can not see cases assigned to them
2. Lab can see samples but when you click to open the sample it is blank
3. When the lab tries to create a sample, they get thew warning message seen in figure.
I think this bug is cause by the new developments that area associated with the lab module.

![image](https://user-images.githubusercontent.com/12996724/69586933-5d453c00-0fe4-11ea-95a3-70b071d6e696.png)

**Comment by MateStrysewskeSym** [comment]
@faatihi Do you have any error logs associated with this problem that you can send us via e-mail?

**Comment by MateStrysewskeSym** [comment]
@faatihi Nevermind, I've found the root of the bug.

**Comment by faatihi** [comment]
> @faatihi Nevermind, I've found the root of the bug.

@MateStrysewskeSym should I withdraw this pull request then?

**Comment by MateStrysewskeSym** [comment]
@faatihi I'll have to locally create a hotfix in order to fix this bug and I don't exactly know whether this is easily possible with a pull request, so I'll probably just do the fix myself. So yes, you can withdraw this pull request.

**Comment by bernardsilenou** [comment]
Thanks Maté,
I have given the lab users the supervisors role and some National users in order to begin data entry. When this issue is solve, we will assign the correct user roles. 
@MateStrysewskeSym: When you are done, please let me know how to test again on HZI server.
