### ISSUE TITLE
Background update 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1381]
We notice that when a user try to synchronize  his or her cases it come up with a message that reads background synchronization already in place and the cases are not sync to the server

**Comment by MateStrysewskeSym** [comment]
@foyiri That message is expected when there's already a synchronization in place so things aren't synchronized twice. If the background synchronization is taking extremely long, it's likely that the data on the phone is somehow corrupt and the synchronization is therefore not working at all. Does this user always get this message or only sometimes?

**Comment by foyiri** [comment]
it takes forever and still it will not sync the case see attached screenshot taken 
![Screenshot_20191125-164938_SORMAS](https://user-images.githubusercontent.com/30156507/69634229-17bf5800-1052-11ea-94a6-65f50991d4cc.jpg)

**Comment by foyiri** [comment]
I think this has to do with the update if you are on version 1.30.1 it gives that error message once you update it to version 1.30.2 it works fine i just notice that now

**Comment by MateStrysewskeSym** [comment]
That's good to hear. I'll leave this issue open for a while, please notify us should you encounter this problem again.
