### ISSUE TITLE
Allow Surveillance Officers to use the web application

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1384]
Ghana surveillance officers requested to have a web interface. This is beneficial for the folowing reasons:
1. To be able to export their line list of cases
2. To have a  dashboard at district level
3. To export case forms from SORMAS. It is a requirement fro SOs to keep a copy of all case forms at the district.
4. Cheep and facilitate role out of SORMAS at district level since we will be able to train users and they will latter use their office PC to work. They correctly have a DHIS2 web based account.

**Comment by MartinWahnschaffeSymeda** [comment]
See #1567
