### ISSUE TITLE
Add Epid number and Present condition to line listing [1]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#1386]
![image](https://user-images.githubusercontent.com/19344651/69800250-271ade80-11d5-11ea-8990-b2607d6729f5.png)
@MartinWahnschaffeSymeda @MateStrysewskeSym Please we need to use Epid number as a unique field for each process within SORMAS. So we should never have duplicates of epid mumbers in the database. Right now we have duplicates. We need to also add Epid number and present condition to the line list form. and if the EPID sync btw linelist and casebased is not done, then we may be creating more issue elsewhere

- [x] add both fields to the case creation form in the app. Define where to put it. The epid number is is only available based on the user right CASE_CHANGE_EPID_NUMBER
- [ ] add both fields to the line listing in the web app (see below)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
We do have a problem with the screen width here. The two new fields will be too big.

Option A:
We can remove health facility and ward from line and move it to the shared fields. This means that users that enter cases into the system have to do it per facility

Option B:
We use a horizontal scroll bar.

What do you think?

**Comment by bernardsilenou** [comment]
Nome of the options are good to me. It is good to add the epid number here. Maybe we might not need to add all teh sections n an epid number but just year and number is 19-01, 19-02, etc because the shared fields contain the other parts of an epid number. This will mean at the stage of line listing, the system should check for duplicates usig epid number and other variables and flag them out.

**Comment by MateStrysewskeSym** [comment]
A few quick thoughts on this:

* Even adding only a "small" epid number field will mean that we have to further extend the minimum width of the layout beyond any size that could be displayed by a display with less than Full HD (1920 x 1080) resolution
* Users will probably have a hard time understanding that they're supposed to only enter the last part of the EPID number; this might lead to confusion

**Comment by MartinWahnschaffeSymeda** [comment]
Talked about this yesterday with Bernard. We can ignore the present condition for the web app.
The EPID number should be fully visible, so we have to find a way to get all the fields onto the screen.

Can be done next year.

**Comment by MateStrysewskeSym** [comment]
See above for instructions, but only add epid number. I suggest to simply extend the width of the popup and see whether this works for the users.

**Comment by MateStrysewskeSym** [comment]
- [ ] Epid number in app: check for an empty string in addition to null
- [ ] Rename presentCondtionList to presentConditionList
- [ ] Make sure that epid number field is hidden in app when the user right is missing (probably use goneIf instead of editUserRight)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] line listing does not work for supervisor, because the district field is not filled based on the region of the supverisor

**Comment by MartinWahnschaffeSymeda** [comment]
@ChristopherRiedelSymeda 

- [ ] line listing does not work for supervisor, because the district field is not filled based on the region of the supverisor
- [ ] add year to epid number prefix
- [ ] always update epid number when year of LGA is changed
