### ISSUE TITLE
Lab officer can't work on the NEW SAMPLE module

### ISSUE THREAD

**Issue by Mabayoje** [hzi-braunschweig/SORMAS-Project#1387]
Dear Mate,  I found out that when  Lab officer click on the NEW SAMPLE it comes out with error report. *The error has automatically submitted to the support, but with admin no error.Kindly look into this.

**Comment by MateStrysewskeSym** [comment]
@Mabayoje Hey! Are you working with SORMAS in Nigeria or Ghana?

**Comment by Mabayoje** [comment]
Nigeria

**Comment by MateStrysewskeSym** [comment]
@Mabayoje I've just updated the server with the latest hotfix, the problem should be gone now.

**Comment by Mabayoje** [comment]
I'll check and revert. Thanks 

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 29, 2019 at 12:01 PM, Maté Strysewske<notifications@github.com> wrote:   
@Mabayoje I've just updated the server with the latest hotfix, the problem should be gone now.
