### ISSUE TITLE
Bug in TreatmentGrid.reload

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1389]
> Caused by: java.lang.IllegalArgumentException: Parameter value [%n%] did not match expected type [de.symeda.sormas.api.therapy.TreatmentType (n/a)]
> 	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
> 	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
> 	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90)
> 	at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:55)
> 	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:497)
> 	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:110)
> 	at org.hibernate.query.criteria.internal.compile.CriteriaCompiler$1$1.bind(CriteriaCompiler.java:136)
> 	at org.hibernate.query.criteria.internal.CriteriaQueryImpl$1.buildCompiledQuery(CriteriaQueryImpl.java:360)
> 	at org.hibernate.query.criteria.internal.compile.CriteriaCompiler.compile(CriteriaCompiler.java:166)
> 	at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:3766)
> 	at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:212)
> 	at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:496)
> 	at de.symeda.sormas.backend.therapy.TreatmentFacadeEjb.getIndexList(TreatmentFacadeEjb.java:78)

**Comment by ChristopherRiedelSymeda** [comment]
We have discovered a problem when searching by string in enum values. This doesn't seem to be possible with our previous approach, because it was done with like method, but it doesn't work with strings and enums. Since we haven't found a solution for the problem yet, I have deactivated this function for Treatments and Prescriptions for the time being.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] fix caption of prescription filter
