### ISSUE TITLE
Nigeria helmholtz server is down

### ISSUE THREAD

**Issue by Mabayoje** [hzi-braunschweig/SORMAS-Project#1392]
Can you have a look at helmholtz server can"t access.

**Comment by hzi-braunschweig** [comment]
Ask @bernardsilenou to create an account for you. I had to truncate the whole database when trying to migrate the Ghana infrastructure.

**Comment by hzi-braunschweig** [comment]
@Mabayoje

**Comment by MateStrysewskeSym** [comment]
@Mabayoje Please don't create Github issues for server problems; these should be reserved for feature requests or bug reports.
