### ISSUE TITLE
Aggregated report view in web app (mSERS) [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1397]
Based on #1277 

### Web app

Mockup: https://app.moqups.com/3NUENEwuOE/view/page/a995b8e9c
Data entry can be added later

- [x] Create mockup for the web app. Should be a new view available from within the cases view. Ideas: rows are diseases, columns are "new cases, lab confirmations, deaths". Optional filter by region, district, health facility
- [x] add time filter and export function to mockup
- [x] new mSERS view
- [x] grid as in mockup
- [x] filters: region (only national users), district, facility
- [x] epi week filter component: from year + week, to year + week. Default; This epi week
- [x] export function for grid

### Backend

- [x] provide total case counts based on criteria. AggregatedCaseCountDto similar to CaseCountDto (use StatisticsGroupingKey). Rename CaseCountDto to StatisticsCaseCountDto
- [x] filter case counts based on user roles

**Comment by MateStrysewskeSym** [comment]
- [ ] Try to retrieve the aggregated case numbers directly from the database with a query
- [ ] Add toUrlString and fromUrlString methods to EpiWeek
