### ISSUE TITLE
Separate configuration section of server-update.sh [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1400]
- [x] separate configuration section of server-update.sh
- [x] add default configuration file

**Comment by StefanKock** [comment]
I introduced the server-update.conf , but for automatic updates in continuous delivery there are the following points to discuss:
1. The finishing tail command needs to be optionalised to make the script finish automatically.
2. I do not see how the databases are automatically upgraded by server-update.sh.
3. It would be helpful to disable automatic database backups to not pollute the host with backup on every script run

**Comment by StefanKock** [comment]
I did finish the script. Cleanup and unpacking will not become part of this script.

**Comment by StefanKock** [comment]
Ticket was reviewed with Maté and is now merged to development.
