### ISSUE TITLE
Updating infrastructure data for Accra

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1401]
Due to the splitting of old district to create new once, The infrastructure data needs to be updated with correct district name, sub districts and HF. Here are the names of districts that are not in SORMAS or are in SORMAS but with missing sub districts and HFs:
Tema, Tema West, Okai Koi North, Ayawaso Central, Ayawaso East, Ayawaso North, Ayawaso West.

For districts that existed in the system and have been divided to form new districts, their sub 
districts and hospitals have also changed. Attached is the excel file with updated details.

When adding data for a district, please comment here so that others can choose another district.

[GAR_EPI_Reporting_Facilities_By_Sub-District_bsi_1912.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3928341/GAR_EPI_Reporting_Facilities_By_Sub-District_bsi_1912.xlsx)

**Comment by MateStrysewskeSym** [comment]
We might need to prioritise #436 and #803 because we might run into this issue frequently and it's better if the administrators of the respective servers can do these changes themselves. We'll discuss this today in the roadmap meeting and see whether we can fit it in the current sprint.

**Comment by MartinWahnschaffeSymeda** [comment]
Infrastructure has already been adjusted. We have added #803 and #1412 to the short term roadmap to take care of this for future need.
