### ISSUE TITLE
EPID number duplicate detection on SORMAS [2]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1404]
Currently on the SORMAS platform, when cases from different diseases share the same epid number, the epid number is detected as a duplicate with the error sign (!) in red.  In the Nigerian IDSR system, cases from different diseases can have the same EPID number e.g. a case of measles can have the same EPID number with a case of Yellow fever. The SORMAS Epid number duplicate detection and EPID number automatic assignment should follow the same structure as the Nigerian IDSR system

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig We need your thoughts on this.

**Comment by MartinWahnschaffeSymeda** [comment]
We have to change this in SORMAS - EPID numbers or only unique for the specific disease.

- [ ]  epid number validation has to include the disease
- [ ] epid number generation per disease

**Comment by Iheanacho2027** [comment]
Also, as an observation, in a scenario where two epid numbers e.g (NIE-RRR-SSA-19-025 and NIE-RRR-SSA-19-25) exists, the system sees them as different epid numbers but in reality they are the same

**Comment by Iheanacho2027** [comment]
According to the nigerian IDSR system, the patient number of the Epid number syntax should be three digits, but most times users use only two digit or four digits. 
What is paramount is that if its  two digit, the system should assume it has a zero in front i.e 25 should be considered as 025, and 0025 should be considered as 025

**Comment by hzi-braunschweig** [comment]
> @hzi-braunschweig We need your thoughts on this.

Yes its correct

**Comment by bernardsilenou** [comment]
The number of zeros infrom of the last interger digit does not real matter as you all mentioned, 02,002,00002,  etc is fine.
@MartinWahnschaffeSymeda @MateStrysewskeSym : Does the function that compares duplicate epid numbers account for this? ie NIE-RRR-SSA-19-25, NIE-RRR-SSA-19-0025,  NIE-RRR-SSA-19-000025 should all be the same number in the system.

**Comment by MartinWahnschaffeSymeda** [comment]
Also fixed getHighestEpidNumber (year part was included in comparison)

**Comment by ChristopherRiedelSymeda** [comment]
Doesn't work with incomplete epid numbers (error)

**Comment by Iheanacho2027** [comment]
"According to the nigerian IDSR system, the patient number of the Epid number syntax should be three digits, but most times users use only two digit or four digits.
What is paramount is that if its two digit, the system should assume it has a zero in front i.e 25 should be considered as 025, and 0025 should be considered as 025"

Pls this is yet to be resolved

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 What exactly is missing? I just tried it out and it seemed to work fine for me.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I guess I see what you mean now. Automatically generated epid numbers do in fact use this pattern, but users are free to set an epid number without that restriction. Are you sure that we should force this upon all users?

**Comment by Iheanacho2027** [comment]
What i mean is that currently, if you search by an epid number i.e
NIE-KTS-DMS-19-38 on SORMAS, it should bring out  NIE-KTS-DMS-19-038, and
vice-versa. We can have a situation whereby a user enters an Epid number
such as  NIE-KTS-DMS-19-38, during case entry, and the system automatically
changes it to  NIE-KTS-DMS-19-038  to follow the correct syntax. We also
have situations where users enter Epid numbers like this
"nie-kts-dms-19-38'', the system can automatically capitalize the letters
to have  "NIE-KTS-DMS-19-038"

**Comment by MateStrysewskeSym** [comment]
Oh, I see, you're talking about the search functionality in the case directory? That's something we can have a look into. May I ask you to open a new issue for this request?

**Comment by Iheanacho2027** [comment]
I just observed that this recently included feature doesnt apply to already existing EPID numbers, i.e an EPID number such as NIE-ENS-AGN-20-002 entered for a CRS case is seen as a duplicate because it had already been entered for a lassa case prior to the implementation of this feature
