### ISSUE TITLE
Web UI framework evaluation & prototype

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1406]
We have to replace Vaadin 8 at some point. 

- [ ] Collect all relevant criteria. 
- [ ] Identify all relevant candidates.
- [ ] Pick a framework
- [ ] Build a prototyp. 
- [ ] Define the migration process.

**Comment by JonasCir** [comment]
There is way to smoothly migrate from [vadin 8 to vue.js](https://medium.com/@fezu54/vaadin-8-and-vue-js-a-smooth-migration-b0ef248962d). Components can be moved one after another, easing the transition process. Regarding prototyping, we've worked on a SORMAS-like Vue.js [webapp](https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/tree/master/src/views) in the past, which could serve as the base for the prototype if desired.
