### ISSUE TITLE
Vaccination campaign management prototype

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1409]

**Comment by MartinWahnschaffeSymeda** [comment]
We want to build a first prototype for Polio.

The idea is that the vaccination is done by teams (most likely two people) using paper forms OR the mobile app in the field. When the paper form is used the data would be entered into the system after the campaign day - so the app forms have to be similar to the paper forms.
A vaccination campaign takes multiple days. For example 3 days of vaccination activity, then one day to get an overview on the situation and a last day of follow-up.
The team is working in a part of a region/village that is called cluster. Each house has a unique number that is assigned in preparation of the campaign.

Data schema suggestion:

**VaccinationActivity**
- Province, District, Village, Cluster, Day, Date
- Team number, Cluster Supervisor, Communication Supervisor, Volunteer name 1 & 2, Social Mobilizer name
- (name and address of first house owner?)
- (name and address of last house owner?)
- No. of children vaccinated in streets / madrasahs/ playground/ fields/ masjid/kindergartens
- No. of NOMAD children vaccinated
- (No. of vials received: Full, Open)
- (No. of vials returned: Full, Open, Empty)

**VacciantionVisit**
- house number/id
- Total no. of children 0-5 yrs resident in the house
- Total no. of guest children 0-5 yrs in the house
- Total no. of children 0-5 yrs vaccinated in this house (resident & guest)

**VaccinationMissed**
- house number
- child name, parent name
- Reason: Absent - will return during campaign, absent - will return after campaign, newborn/sick/sleeping, refusal
- Outcome: Found vaccinated, vaccinated by team during revisit

- [ ] create mockups for mobile data entry forms

**Comment by MartinWahnschaffeSymeda** [comment]
Tally sheets list: https://app.moqups.com/3NUENEwuOE/view/page/a43b6d029
Tally sheet header: https://app.moqups.com/3NUENEwuOE/view/page/a7691187d
House child counts: https://app.moqups.com/3NUENEwuOE/view/page/a714b8644
Missed children: https://app.moqups.com/3NUENEwuOE/view/page/a50e69380
Tally sheet footer: https://app.moqups.com/3NUENEwuOE/view/page/adcc89f3d

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda Hi Martin, this is very good. Welldone. Please can you go up one layer and do the same for the cluster supervisor. This is due to the fact that the teams in some areas wont be able to use the mobile devices so that means that the cluster supervisor will have to do the compilation. I have already made the mockups of the cluster supervisor https://app.moqups.com/3NUENEwuOE/view/page/ab6506a23
https://app.moqups.com/3NUENEwuOE/view/page/a7e1e27f6
![image](https://user-images.githubusercontent.com/19344651/73757278-4bf97800-4769-11ea-98b0-5648d549e0b7.png)

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda you also completely left out the AFP case creation within household. That is a strong argument to use SORMAS as a case based system for SIAs. See mockup 
https://app.moqups.com/3NUENEwuOE/view/page/a79812347

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-old I suggested to Gérard to use the existing case create function and he agreed. Is there anything that speaks against using the basic case creation?

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda That works as well. I was thinking about embedding the AFP case creation form into the household information. Also there are some fields that are not in the current form e.g 
![image](https://user-images.githubusercontent.com/19344651/73914679-0d270780-48ba-11ea-9586-13d128812146.png)

**Comment by MartinWahnschaffeSymeda** [comment]
Prototype will remain in branch. See #1532
