### ISSUE TITLE
Archiving of infrastructure data [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1412]
It should be possible to mark the health facility as "deleted", so it can no longer be used for new data entries, but is maintained for existing ones.

See also #803

**Comment by MateStrysewskeSym** [comment]
- [ ] Make `Facility` and `Community` extend `CoreAdo`
- [ ] Make `FacilityService` and `CommunityService` extend `AbstractCoreAdoService` and refactor them accordingly (e.g. add `default` and `active` filters)
- [ ] Add delete functionality to facility/community edit forms and facades
- [ ] Hide deleted facilities/communities from all views and dropdowns
- [ ] Don't allow deletion of facilities if there are cases or users associated with them (also look for other entities that could potentially be relevant for this)
- [ ] Same for communities, but also don't allow deletion if there are facilities in the community

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove methods that use a single uuid from facades, use Collection instead of Set, use Arrays.asList to call these methods
- [ ] Rename queryForAll infrastructure methods to queryActiveForAll
