### ISSUE TITLE
Bug in "follow up visits"under contacts 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1414]
This error pops up when you want to add a visits for a contact. 
![image](https://user-images.githubusercontent.com/35563508/70522741-03935480-1b42-11ea-887a-6a715ee78ec5.png)

**Comment by MartinWahnschaffeSymeda** [comment]
> Caused by: java.lang.NullPointerException: null
> 
>         at de.symeda.sormas.ui.contact.AbstractContactView.refreshMenu(AbstractContactView.java:53)
> 
>         at de.symeda.sormas.ui.utils.AbstractSubNavigationView.enter(AbstractSubNavigationView.java:72)
> 
>         at de.symeda.sormas.ui.contact.ContactVisitsView.enter(ContactVisitsView.java:149)
> 
>         at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:778)
> 
>         at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
> 
>         at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
> 
>         at com.vaadin.navigator.View.beforeLeave(View.java:79)
> 
>         at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
> 
>         at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
> 
>         at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
> 
>         at de.symeda.sormas.ui.MainScreen$2.beforeViewChange(MainScreen.java:187)
> 
>         at com.vaadin.navigator.Navigator.fireBeforeViewChange(Navigator.java:883)
> 
>         at com.vaadin.navigator.Navigator.beforeViewChange(Navigator.java:796)
> 
>         at com.vaadin.navigator.Navigator.performNavigateTo(Navigator.java:762)
> 
>         at com.vaadin.navigator.Navigator.lambda$navigateTo$9a874efd$1(Navigator.java:702)
> 
>         at com.vaadin.navigator.ViewBeforeLeaveEvent.navigate(ViewBeforeLeaveEvent.java:54)
> 
>         at com.vaadin.navigator.View.beforeLeave(View.java:79)
> 
>         at com.vaadin.navigator.Navigator.runAfterLeaveConfirmation(Navigator.java:730)
> 
>         at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:701)
> 
>         at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:678)
> 
>         at com.vaadin.navigator.Navigator$UriFragmentManager.lambda$setNavigator$567eee34$1(Navigator.java:209)
> 
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
>         at java.lang.reflect.Method.invoke(Method.java:498)
> 
>         at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
> 
>         ... 87 common frames omitted
>

**Comment by ChristopherRiedelSymeda** [comment]
@MartinWahnschaffeSymeda When I try to reproduce the error, there is currently no error. Please try to reproduce it locally again.

**Comment by bernardsilenou** [comment]
I tried it now and could reproduce it on hzi server

**Comment by MartinWahnschaffeSymeda** [comment]
Found and fixed.
