### ISSUE TITLE
Error in POE user account

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1419]
This error occurs when the user tries to move from case information to person information in the edit mode. The app crashes or an error message pops up 

![WhatsApp Image 2019-12-12 at 14 11 57](https://user-images.githubusercontent.com/50739609/70715115-e39e9500-1ce9-11ea-9dab-f8a987560339.jpeg)

**Comment by Iheanacho2027** [comment]
Also, @hzi-braunschweig , should the POE informant have case classification rights as it is currently on the mobile app?

**Comment by bernardsilenou** [comment]
Informants do not have case classification right. This is surely a mistake that we will address

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I've probably already encountered this bug a few days ago, it will be resolved in the update that we will roll out next week.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Just for clarification, this happened in a point of entry case, right?

**Comment by Iheanacho2027** [comment]
Yes

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Alright, thanks!

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym the bug related to the App crash in the POE user account still exists after the latest release
