### ISSUE TITLE
Modification of navigation features on case menu in mobile app [0]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1420]
Currently, the navigation features for lassa fever case entry on the mobile app is case information → person information → Hospt. Info. → symptom info → Epid info → case contacts → case samples → case tasks

Can the features be modified to make entry of case samples come before case contacts ?. This is because line listing case contacts is a lengthy activity, and users can forget to enter case samples afterwards @hzi-braunschweig @Chinedar @foyiri @bernardsilenou

**Comment by bernardsilenou** [comment]
You request is logical and important, hope we can implement this issue in the near future, not urgent for now since users can navigate  to any tab using the drawer

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] change order of navigation as requested above
