### ISSUE TITLE
Informants should not be able to edit the case classification

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1422]
Also, @hzi-braunschweig @bernardsilenou , should the POE informant have case classification rights as it is currently on the mobile app?

_Originally posted by @Iheanacho2027 in https://github.com/hzi-braunschweig/SORMAS-Project/issues/1419#issuecomment-565005618_

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda No the POE informant should only be able to create a case (not yet classified), the DSNO will go and investigate and can classify the case as suspect etc.

**Comment by Iheanacho2027** [comment]
This also applies to the health facility informant, they currently can
classify cases

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Any reason you reopened the issue I have fixed?
