### ISSUE TITLE
Inability of users to directly update from older versions to current versions

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1423]
Mobile app users are unable to directly update the SORMAS app from an old version to a current version. Forinstance, users cant directly update from 1.28.0 to 1.30.0 without the app crashing.  This is probably due to change in API infrastructure

**Comment by MartinWahnschaffeSymeda** [comment]
This is very likely related to #1426. Can you please have a look into that issue? We will need your help.
