### ISSUE TITLE
IllegalArgumentException in AppUpdateController

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1426]
Error message:
```
Fatal Exception: java.lang.IllegalArgumentException
Failed to find configured root that contains /storage/0000-0000/Android/data/de.symeda.sormas.app/files/Download/sormas-1.30.3-release.apk
```

Exception stack:
```
androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile (FileProvider.java:744)
androidx.core.content.FileProvider.getUriForFile (FileProvider.java:418)
de.symeda.sormas.app.util.AppUpdateController.installApp (AppUpdateController.java:391)
de.symeda.sormas.app.util.AppUpdateController.access$200 (AppUpdateController.java:46)
de.symeda.sormas.app.util.AppUpdateController$5.call (AppUpdateController.java:238)
de.symeda.sormas.app.component.dialog.AbstractDialog.onPositiveClick (AbstractDialog.java:207)
de.symeda.sormas.app.component.dialog.AbstractDialog$4.onClick (AbstractDialog.java:163)
android.view.View.performClick (View.java:5647)
android.view.View$PerformClick.run (View.java:22465)
android.os.Handler.handleCallback (Handler.java:761)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:156)
android.app.ActivityThread.main (ActivityThread.java:6577)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:986)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:876)
```

Possible solution attempt: https://stackoverflow.com/questions/42516126/fileprovider-illegalargumentexception-failed-to-find-configured-root

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig @Chinedar This bug seems to affect only users with the Huawei MediaPad T3 7. Unfortunately we can't identify who they are because the bug occurs before the user is set. Please try to find out who the affected users are and see whether this issue can be reproduced, i.e. whether it happens everytime they try to update the app or only sometimes.

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda if #1423 is related to #1426 then it applies to all users and not just users with huawei mediapad. From our experience, almost all users including those with tecno P703 mediapad who try to update from a very old version (for example 1.28.0 or 1.27.0) to a recent version (say 1.30.2 or 1.30.3) have app crashes.

**Comment by Iheanacho2027** [comment]
The app crash usually occurs by throwing the user out of the app (when trying to enter a new case), and requesting the default log in pin. This happens continuosly until the app is uninstalled and reinstalled

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 That seems like a totally different issue to me though. The automatic app update only triggers when the app is started, not when it's already up and running. What you're referring to seems like some kind of authentication problem. However, I can't find any logs on Firebase that seem to point towards this. Is there anything that reliably leads to these crashes that we could reproduce?

**Comment by MateStrysewskeSym** [comment]
First attempt at fixing this has been done based on https://stackoverflow.com/questions/46673683/android-fileprovider-failed-to-find-configured-root-that-contains

**Comment by Iheanacho2027** [comment]
Example of the error

![WhatsApp Image 2019-12-19 at 16 47 12](https://user-images.githubusercontent.com/50739609/71187986-6f7f6680-2280-11ea-8c04-8ab32427b893.jpeg)

**Comment by MartinWahnschaffeSymeda** [comment]
Based on crashlytics this crash no longer happens.
