### ISSUE TITLE
Informants should not edit "date received at district" in app

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1437]
Either based on user role or on association to facility/community

**Comment by MartinWahnschaffeSymeda** [comment]
surveillace officer shoulb be able to edit it.

**Comment by ChristopherRiedelSymeda** [comment]
> surveillace officer shoulb be able to edit it.

Have tested it with SanaObas (Surveillance Officer) and SangIbor (Hospital Informant) and it behaves as intended. @MartinWahnschaffeSymeda with which user did you have unexpected behaviour?

**Comment by MartinWahnschaffeSymeda** [comment]
For some reason my test SO has a health facility. So this is not relevant for real life systems.
