### ISSUE TITLE
Incomplete disease list when creating pathogen tests

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1442]
From Bernard in #1415:

This is what I found after testing 1.31.0:
For internal and external test samples, when a new test result is created, tested disease are only west Nile and pneumonia which are diseases for only aggregate reporting. In the drop down field for disease, we should present all diseases here.

**Comment by ChristopherRiedelSymeda** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda 
- [ ] Define if the selectable diseases should be primary and case based.

**Comment by ChristopherRiedelSymeda** [comment]
primary has to be null (primary and non-primary diseases should be selectable)
