### ISSUE TITLE
Addition of a filter on the search directory for orderly arrangement of cases by EPID number

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1446]
I am suggesting that a filter which arranges the list of cases according to the last three digits (patient number) of the EPID number be added to the search directory feature of the mobile app. This will give surveillance officers an idea on where the last count in EPID number entry occurred to prevent duplicate entry of EPID numbers on the platform. This could come in the form "arrange list by EPID number"
 @hzi-braunschweig @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
I've created a general issue (#1450) to add manual sorting to the mobile app and included your request there.
