### ISSUE TITLE
Diseases that are set to inactive disappear from app dropdowns

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1453]
Inactive diseases should still be selected in all dropdowns where they'd been selected previously:

* Case (after #1433)
* Cause of death disease in person
* Event
* Weekly report

The disease probably needs to be added to the dropdown manually, likely similar to what will be done in #1412.

**Comment by faatihi** [comment]
@MateStrysewskeSym is this issue already taken care of?
I see lines of code that address this issue.

**Comment by MateStrysewskeSym** [comment]
@faatihi Not directly, but it's possible that this has been resolved in #1412. Please verify this by creating e.g. an event with a disease, set that disease to inactive afterwards (directly in the database, you need to edit the respective DiseaseConfiguration entry and manually set the change date for the app to synchronize the changes) and see whether it still appears in the disease dropdown of the event or not.

**Comment by faatihi** [comment]
OK. I've gone through with a few scenarios.

The following have already been worked on.

- Case (after #1433)

- Cause of death disease in person (web)

- Event

- Tested Disease in Pathogen Test Result

This is what is left:

- "Cause of death disease in person" hasn't been implemented in sormas-app.

- I do not know how to go about the "Weekly report". Where do I go to test that.

**Comment by MateStrysewskeSym** [comment]
@faatihi Probably nowhere, Weekly Report shouldn't have been included in that list.

**Comment by faatihi** [comment]
Thanks. I'll work on the app version for cause of death.
