### ISSUE TITLE
The symptom table has a primary key field called "id" and also the foreign key called "symptoms_id"

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1459]
We should delete the "symptoms_id" field from the symptoms table in the data base.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou You already brought up this exact issue in the past. The symptoms table does not have a "symptoms_id" field. You're probably talking about the database export where the case table is appended to the symptoms to provide more information.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  
You are right. I now understand the problem. When I export the symptoms table under database export from the front end, the table comes with fields already on the case table. I wish to ask is we can keep the tables exactly as they are in the database under database export. For other export options, we can play with the tables.
I have duplicate names when merging case table with the symptom table exported from front end.

**Comment by MateStrysewskeSym** [comment]
We added the case table to the symptoms table due to a request from HZI. Please discuss this with Daniel and open a new issue if you come to the conclusion that this is necessary.
