### ISSUE TITLE
Editing selected disease on mobile app

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1461]
Currently users aren't allowed to edit the disease they selected previously for a case. Mobile users should be allowed to edit selected data on disease just like it is on the web app

**Comment by foyiri** [comment]
Do you mean changing the disease type

**Comment by Iheanacho2027** [comment]
Yes

**Comment by MateStrysewskeSym** [comment]
Duplicate of #1433
