### ISSUE TITLE
Ask users to request another sample if sample condition is not adequate

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1466]

**Comment by MateStrysewskeSym** [comment]
This would result in the creation of a respective task.

**Comment by MateStrysewskeSym** [comment]
When a user updates the sample condition to "Not adequate" (i.e. it didn't have a sample condition before or the sample condition was set to something else), show a popup that asks whether they want to request a fresh sample.

- [ ] Add an appropriate confirmation popup
- [ ] When the user accepts the request, create a sample collection task and assign it to the responsible surveillance officer of the case
- [ ] If there is no responsible surveillance officer, assign it to a supervisor of the region of the case

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/74530387-cd979580-4f21-11ea-9452-cadbcac2bf77.png)

Looks like somebody is already working on this issue.

**Comment by MateStrysewskeSym** [comment]
@faatihi You can go ahead and duplicate the logic for the mobile app then - I'm pretty sure it's not integrated there yet.

**Comment by faatihi** [comment]
Ok

**Comment by MartinWahnschaffeSymeda** [comment]
Marked as obsolete, because lab users currently can't access the mobile app - so it would not make a lot of sense to add it there.
The requirement has been implemented for the web app a in #254
