### ISSUE TITLE
Change calculation of new sample tests on dashboard [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1472]
The number of new sample tests does not fit to the number of reported cases for the same period. This is related to the fact that the number of new sample tests is calculated based on the sample test date while the number of new cases is based on the date of report.

- [x] use the report date of the related case to calculate the number of sample tests on the dashboard (based on samples final test result. one per case)
- [x] we may have to change the caption or add a description to make sure users understand how this is calculated. Idea: Change caption to "test results" and add tooltip "Test results of the new cases"
- [x] add a unit test to make sure only one sample is counted by case

@bernardsilenou Please double check this.

**Comment by bernardsilenou** [comment]
This is ok and I will like to add some few comments:
We should show cases on dashboard based on date of notification (case report date in SORMAS) as default, (say , [a to b],  with date a<b). Users will have the possibility to change to other dates if they want. The corresponding sample test information on the dashboard will be for only samples corresponding to the cases notified within [a,b], no matter if the date of their results c is in the future  (c>b)  but not with respect to the current calendar date (d). So c should normally be in the interval [a <= c<=d] . This means samples with date of results not falling in the report date interval of the cases shown will appear on the dashboard if they are linked to a case notified within this time interval.

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] Merge on development

**Comment by MateStrysewskeSym** [comment]
- [ ] Test server is showing 0 reported cases, but 3 test results for the current week on the test server

**Comment by ChristopherRiedelSymeda** [comment]
A user filter is needed for the query in SampleService.getNewTestResultCountByResultType. Unfortunately, the user filter for criteria queries cannot be used, since it is a native query and this cannot be changed.

**Comment by MateStrysewskeSym** [comment]
Two possible solutions:
- [ ] Add a "final laboratory result" variable to the case
- [ ] Split the filter - first filter for all cases that are visible for the user and use these results to calculate the test results

**Comment by MateStrysewskeSym** [comment]
- [ ] Try to replace native query with CriteriaQuery
