### ISSUE TITLE
Coronavirus [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1476]
Add Coronavirus as a new disease, including new fields and enum values according to the data dictionary:

[SORMAS_Data_Dictionary_Coronavirus_bsi_200127_jdo.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4123161/SORMAS_Data_Dictionary_Coronavirus_bsi_200127_jdo.xlsx)

**Comment by MateStrysewskeSym** [comment]
- [ ] provide enum string for AreaType.UNKNOWN

**Comment by MateStrysewskeSym** [comment]
- [ ] Anormal -> Abnormal
