### ISSUE TITLE
Data Quality Check Button to show completeness status in the statistcics menu

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1485]
Can we have a summary report/status that shows per disease, missing variables(in %) or variables that have not been filled for a time period? e.g. in a week, month or quarterly. 
This will be calculated as a proportion of total number of variables filled for that time period. 
Can this summary also be segregated by state?

**Comment by MateStrysewskeSym** [comment]
This will later be part of #904.
For now, we'll prioritize #1294 as some kind of a quick solution.
