### ISSUE TITLE
Fix non-unix line endings in server-update.conf

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1489]
Updating a SORMAS server on a linux system is currently not possible because the server-update.conf file has wrong line endings. Converting the file with dos2unix temporarily solves the problem.

**Comment by StefanKock** [comment]
The problem is that for a .conf file an unappropriate rule triggers from .gitattributes.
Solution: Define _eol=lf_ explicitly for server-update.conf

**Comment by StefanKock** [comment]
@MateStrysewskeSym please review and merge the pull request.
