### ISSUE TITLE
ControlSwitchField does not have a visible value after using the hardware back button

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#1492]
The value is stored in the field, but the visual indicator is missing. Clicking on the selected value does not do anything, when clicking on another value, it is selected and the initial value can be selected again.

**Comment by VitaliHZI** [comment]
Hey @MateStrysewske is it up to date? how can we test it?

**Comment by MateStrysewske** [comment]
@VitaliHZI I'm not sure, but I guess it is because we didn't fix it in the meantime. I think the problem appears if you use the hardware back button (so not the software button that has been introduced in an Android version quite some time ago) to navigate back to a previous form (e.g. after moving between the tabs inside a case). If the page you go back to contains a switch field (the one that displays the values next to each other and highlights the selected value with a blue background) that has a value, the visual indicator of the selected value is missing and it appears as if nothing has been selected. This doesn't happen if you use the software back button.

**Comment by MateStrysewske** [comment]
Closing this issue because I can no longer reproduce it.
