### ISSUE TITLE
Error in statistical algorithm for calculating outcome

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1501]
There is an error in the calculation of case counts by outcome when running a tabular visualization on the statistics menu. What is presented on the statistical menu is a wrong reflection of what exists on the case directory @bernardsilenou

**Comment by bernardsilenou** [comment]
@Iheanacho2027  It is not an error. In the case directory; choose °all cases° because the default is active active cases. In statistics section; all cases are considered except those that have been deleted.
@MateStrysewskeSym I realized that some times; the number of cases from statistics and front end differs by about 2 cases. Classify cases on Symeda server with report date from January 1; 2019 to February 5; 2020 and classify by outcome

**Comment by Iheanacho2027** [comment]
@bernardsilenou thats not the issue. Pls filter deceased cases for the year 2019 by report date on the case directory and compare it with the filtered deceased cases on the statistics menu for the year 2019 by report date.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 @bernardsilenou I can't reproduce this on the symeda server. The numbers match up. Can you please give me a precise example of what's wrong?

**Comment by MateStrysewskeSym** [comment]
- [ ] Check whether dashboard and statistics both use startOfDay and endOfDay everywhere

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou This seems to work fine from my side. Please try again to reproduce it on the symeda server and, if it happens again, send me screenshots of the filters you used so I can try to reproduce it myself.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym   I Tried it and all is fine. My mistake is that I did not choose the report date to filter cases in the case menu but used the most relevant date.
As already decided, we should set the report date as default of the "case reference date" field in the case menu and to  date fields on dashboard also.

**Comment by Iheanacho2027** [comment]
Hi Mate, pls close this ticket. I too used a wrong procedure but later
discovered my error. Thanks

**Comment by MateStrysewskeSym** [comment]
Alright! Thanks for the clarification!
