### ISSUE TITLE
Improve case import speed

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1504]
Looking at a server log the average time to import a case is 1 second. This means importing 1000 cases would take 17 minutes. We need to speed this up by a factor of 2-10.

- [ ] investigate what part of the import is taking so much time. Could very likely by related to saving the case.

**Comment by StefanKock** [comment]
On possible problem: _CaseImporter_ calls _CaseImportFacade::importCaseData_ within the same JTA transaction (started by SessionFilterBean) which results in a growing JPA cache the more cases are imported (blowing up the Hibernate cache with more and more newly created entities). The JTA transaction is commited when all imports are done or when a case is a suspected duplicate.
Possible solution: Let _CaseImportFacade::importCaseData_ start a new JTA transaction so every case runs separately to prevent the import becoming slower and slower the more lines are processed.

**Comment by StefanKock** [comment]
After looking through the code I only found two more performance leak suspects:
1. Duplicate detection: _CaseImportFacadeEjb.isPersonSimilarToExisting(Person)_ 
2. Persist case: _CaseImportFacadeEjb.saveImportedEntities(CaseImportEntities)_

**Comment by MateStrysewske** [comment]
Will be handled in other issues (e.g. #2265)
