### ISSUE TITLE
Adding "Pregnancy" variable to all exports

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1506]
The current export do not have the pregnancy variable.

**Comment by bernardsilenou** [comment]
The age of the pregnancy variable should use 9 to 55 yrs  for validation

**Comment by MateStrysewskeSym** [comment]
Which export do you mean? Also, there's no "age of pregnancy" variable in SORMAS right now.

**Comment by bernardsilenou** [comment]
@chukwuemekauzoho can you confirm which export does not have the pregnancy variable?
@MateStrysewskeSym  I meant the age of the person/case with pregnancy set to yes should be in the range 9 to 55, just as a validation rule.  I will check if we already have a validation for the pregnancy variable.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou We should discuss this in a review meeting. In general, I don't think we should add too many restrictions to the app, especially for corner cases like this. Besides, with modern technology and all, it's very well possible for women over 55 to become pregnant.

**Comment by chukwuemekauzoho** [comment]
> @chukwuemekauzoho can you confirm which export does not have the pregnancy variable?
> @MateStrysewskeSym @bernardsilenou  I meant the age of the person/case with pregnancy set to yes should be in the range 9 to 55, just as a validation rule. I will check if we already have a validation for the pregnancy variable.

@bernardsilenou The detailed export does not have the pregancy function.

**Comment by ChristopherRiedelSymeda** [comment]
already done in #1493 
will be available after the next release
