### ISSUE TITLE
User should only be able to generate statistics in his jurisdiction (region/district/community) 

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1509]
As discussed in #1475,

> The Statistics, all users at various levels (Regional, District) can generate a statistics of all the data on the system. We want the users to generate statistics on data concerning their jurisdiction only.

I also saw this note at the bottom of the statistics page,

![image](https://user-images.githubusercontent.com/1176692/74153895-7172ff80-4c09-11ea-9d7b-3898a2ddae78.png)

This means we're aware of this situation.

**Comment by MateStrysewskeSym** [comment]
I'd like to discuss this with HZI before you start working on it. Can you tell me why exactly this is needed?

**Comment by bernardsilenou** [comment]
Some comments:
1. Users are able to generate  statistics in regions that do not belong to them in the current system. But these users can only see and export data in their region or districts.
2. We should not confuse the right of having aggregate report and the right of having case based data. The current German  <https://survstat.rki.de/> tool also allow any person even outside the country to generate summary data from historic surveillance data.
3. When we will latter build the option for user to export the data that are used in obtaining the statistics shown in the statistic section, then we will need to restrict the exported data only to their districts or regions.
@faatihi I will also like to know what is the reason for this request.
