### ISSUE TITLE
Increase minimum supported Android version to 7 [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1519]
In order to use some modern features of Android and Java as a programming language, we should increase the minimum required Android version of SORMAS to 7. In theory, this should be no problem as even the Tecno tablets that are currently being used in Nigeria received an upgrade to this OS version.

According to Firebase, there are a few devices that SORMAS is currently being used on that run Android 5 or 6:

* SM-T585 (Galaxy Tab A) => Update to Android 7 possible
* Nexus 5X => Update to Android 7 possible
* SM-P601 (Galaxy Note 10.1) => Update to Android 7 **not** possible
* SM-G570F (Galaxy J5 Prime) => Update to Android 7 probably **not** possible

The SM-P601 is currently used by 2 users. The SM-6570F is used by 1 user. There's no other device being used that would be unable to continue using SORMAS if we increase our minimum version to Android 7.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Make sure build server is working with it
