### ISSUE TITLE
Linelisting case contacts [5]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1521]
There is a need for a module where basic variables of case contacts can be linelisted. This would help speed up entry of case contacts

**Comment by foyiri** [comment]
I think this will also help in entering contact from state where we are yet to deploy sormas

**Comment by max-hzi** [comment]
Please prioritise this Issue @MateStrysewskeSym , thank you.

**Comment by bernardsilenou** [comment]
@max-hzi : One idea about the line listing is to maintain the region and district for all records. 
 Can your find out from the users if all contacts  of a case have the same region and district always?

**Comment by max-hzi** [comment]
> Can your find out from the users if all contacts of a case have the same region and district always?

Yes, thats **usually** the case. But not 100% of the time of course.

**Comment by Iheanacho2027** [comment]
As you prioritize this, please kindly prioritize  #1851 as it is very important for Nigerian users. A lot of users have said the page by page navigation method for entering a multitude of cases is burdensome.

**Comment by Iheanacho2027** [comment]
As you prioritize this, also kindly prioritize  #1857 as it is very important for Nigerian users. A lot of users have said the page by page navigation method for entering a multitude of cases is burdensome.

**Comment by kwa20** [comment]
This issue has been postponed for a while now but remains very relevant for all users. Therefore, I would like to attract attention to this issue again and propose the following implementation:

**Introduce line listing for contacts**
- The line listing option should be available on the contact directory and the case contact tab
- Line listing option should include shared information including:
    - source case (choose) - pre-filled and uneditable when inside the case contact tab
    - disease - pre-filled and uneditable when case is selected
    - responsible region and district - mandatory when no case is selected
    - Option to adopt the home address of the case person (checkbox) with display of the respective address
- Line listing should include a list of new contacts and allow adding lines for entries 
   - date of report
   - date of last contact with multi day selection option
   - type of contact - in form of a drop down
   - relationship with case
   - person data: first name, last name, date of birth, sex
   - deletion option for lines

<img width="743" alt="Screen Shot 2021-04-02 at 12 11 36 PM" src="https://user-images.githubusercontent.com/70317594/113407876-89c65080-93ae-11eb-90dd-989eb83e2084.png">

@bernardsilenou @MateStrysewske @JaquM @Iheanacho2027 @Candice-Louw Feedback is highly appreciated!

**Comment by bernardsilenou** [comment]
@kwa20 The mockup looks good, just have one minor comment:
- The point on adoption of home address can be taken out and we define a bulk action to add addresses to persons. This feature can only be useful here when all the contacts are living in the same household, but this does happen only for few instances.
- We can add a new issues with different ways of filtering persons: can be names, same source case (for this situation), same events, etc + bulk action to update the person data (can be addresses, tel, etc)

**Comment by kwa20** [comment]
> * The point on adoption of home address can be taken out and we define a bulk action to add addresses to persons. This feature can only be useful here when all the contacts are living in the same household, but this does happen only for few instances.

Contacts inside one household are a very common occurrence, actually, especially if cases are being quarantined and all family members with them. Users have been requesting to be able to easily document families and adopt addresses at the same time and I think this would be an easy way to accommodate this request don't you think? If it doesn't apply the checkbox can easily stay unchecked.

> - We can add a new issues with different ways of filtering persons: can be names, same source case (for this situation), same events, etc + bulk action to update the person data (can be addresses, tel, etc)

Yes to handling bulk actions in another issue.

**Comment by bernardsilenou** [comment]
@kwa20 I understand you and this idea works in terms of covid. 
- what about if the contacts took place at work and we need to adopt the work address from the case?
- apart from address, there can be many other things that we may need to adopt from a parent entity when we link them to others.
- The point that i see with the current solution is to make it more generic and if we decide to add such adoption feature, then it would be nice that we add  at once to all the routs that contacts can get in into the system:  normal,creation of contacts, import, etc.
- The person adding the contacts to the case may not have the right to see the home address of the source case also. We need to consider how this  would be handled.
-   I think it would be good we refine this part further add it at once to all routs that contact can be created in the system. If there any reason that both must be implemented together?

**Comment by bernardsilenou** [comment]
@kwa20 I just read your comment again and think we should have a different ticket to add the adoption of address to all forms for creating contacts.  If that fine by you?

**Comment by kwa20** [comment]
@bernardsilenou considering that this issue has been around for so long I agree yes, we could implement this on a step by step basis.

**Comment by bernardsilenou** [comment]
@kwa20  In order to complete the address types, can we add the option for the user to choose the address type to adopt?
- multiple checkbox options for at least the 3 types that are in the system. 
- if user choose an option, then the address get s displayed as you suggested
- If all 3 options are selected, then all 3 gets adopted
![image](https://user-images.githubusercontent.com/12996724/113633692-acd25800-966d-11eb-9961-3ac149e53cb0.png)

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by kwa20** [comment]
I tested on test-de.sormas.netzlink.com. There seems to be an error when opening the line listing options in the contacts tab of cases

<img width="895" alt="lineListingContactsError" src="https://user-images.githubusercontent.com/70317594/121907830-b8589400-cd2c-11eb-87cf-713d62fb1d48.PNG">

**Comment by alexcaruntu-vita** [comment]
@kwa20 can you please provide the logs?

**Comment by RazvanHodisan** [comment]
Verified on https://test-de.sormas.netzlink.com/ and https://test.sormas.netzlink.com/

**Comment by StefanKock** [comment]
It seems that this ticket broke creating/saving contacts

**Comment by RazvanHodisan** [comment]
Verified on the local environment, Version: 1.61.0-SNAPSHOT

**Comment by kwa20** [comment]
I tested again on test-de.sormas.netzlink.com and noticed that the drop-down values for 'type of contact' and 'relationship with case' cannot easily be read when opened.

Expected: The opened drop-downs expand to the required space to show the full values

<img width="874" alt="lineListingContacts" src="https://user-images.githubusercontent.com/70317594/123133856-7a582000-d450-11eb-84b0-1e2b324dcda0.PNG">
<img width="872" alt="lineListingContacts2" src="https://user-images.githubusercontent.com/70317594/123133860-7c21e380-d450-11eb-9d5b-edb8b7b33e54.PNG">

**Comment by alexcaruntu-vita** [comment]
@kwa20 There is not enough space to display the full text. I played with various widths and we cannot accommodate full text for drop-down values and at the same time have all the fields in one row. However, you can see the full text if you hover over the options.

**Comment by kwa20** [comment]
@alexcaruntu-vita ok, I tried hovering but it didn't work in my case, maybe it's simply not available on the nightly builds yet?
