### ISSUE TITLE
Bulk edit diseases [1]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1524]
### Situation Description
Admins need a way to change the disease of multiple cases at once, e.g. to reassign AFP/Polio cases that have been entered before those diseases got added to SORMAS.

### Feature Description
Extend the bulk edit popup for cases with a disease dropdown.

**Comment by ChristopherRiedelSymeda** [comment]
solution of this issue was comitted with wrong issue number (#1525 )
