### ISSUE TITLE
Allow web users to gather aggregate case data

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1526]
### Situation Description
Web users can currently only see, but not add aggregated case counts.

### Feature Description
Add a new view or popup that allows users to enter aggregated case counts. The UI can probably look pretty similar to the one used in the mobile app.

**Comment by ChristopherRiedelSymeda** [comment]
Entering data is basically possible with the current status. However, if a report is saved for a period for which a report has already been saved, database entries are currently created twice.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] check AGGREGATE_REPORT_CREATE user right in app
- [ ] looks like something went wrong merging this. Check

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] caption of healthfacility and poe in edit/create for
- [ ] create when no entry exists

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Check AGGREGATE_REPORT_EDIT user right in app instead of VIEW user right (app currently only has an edit view)
- [ ] Add informant user roles to the EDIT user right
