### ISSUE TITLE
"Follow-up" view for contact directory

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1533]
We need an alternative view for the contact directory that gives an easy overview of the contact follow up status for the last 8 days.

- [x] Add a switch to the top right of the screen: Contacts, Follow-up
- [x] Columns: Contact ID, Contact Person, Contact officer, Date of last contact, Follow-up until, Column for each of the last 8 days. 
- [x] The day columns should have just a color to represent the visit result: Seen not symptomatic (green), Symptomatic (red), Unavailable (blue), Uncooperative (violet), Not performed (grey)

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] make ContactsView.createFollowUpLegend() nice

**Comment by MartinWahnschaffeSymeda** [comment]
When a contact should not have a visit on a certain day (follow up ended or not begun) the column should have no color.

**Comment by MateStrysewskeSym** [comment]
- [ ] Try to replace the individual day results in ContactFollowUpDto with a single list/array; iterate over this in the grid to avoid redundant code
