### ISSUE TITLE
Cannot create a contact follow up visit

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1536]
### Bug Description
When creating a contact follow up visit, it shows an error message and does not create it.
### Steps to Reproduce
1. click on new contact, create contact, person
2. go to follow up visit, create new visit, hit save and error

### Expected Behavior
Error on hiting save
### Screenshots
![image](https://user-images.githubusercontent.com/19344651/75440111-6f27d980-595b-11ea-9dfb-f8a5df5e051b.png)

### System Details
* Device: Dell
* SORMAS version: 1.33.1
* Android version/Browser:Chrome

**Comment by hzi-old** [comment]
Problem solved when you set contact person to confirmed contact.

**Comment by ChristopherRiedelSymeda** [comment]
Problem was already identified and solved in #1535
