### ISSUE TITLE
Approximate age sometimes not persisted in the database

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1538]
There is an error in the export where some cases have missing age variable due to non-calculation of the age from the date of birth variable. This exists in few exported cases but not all. 

![bug cc](https://user-images.githubusercontent.com/50739609/75446244-54f3f880-5967-11ea-87f3-4a926121a88a.JPG)

**Comment by MateStrysewskeSym** [comment]
The problem is very likely that the approximate age just isn't stored in the database. The export is working fine, but there seems to be a problem with the logic that fills this field.

**Comment by MateStrysewskeSym** [comment]
- [ ] Always calculate approximate age in onPersonChanged

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 We made sure that this won't happen again in the future. We've also identified a few reasons why this might've happened, but not all of them. In any case, unfortunately, the already existing persons that have a birth date but no approximate age will remain that way unless they're manually saved (in which case the approximate age will be re-calculated).
