### ISSUE TITLE
Automatic task defaulted to "Removed"

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1542]
### Bug Description
When you create a case or contact, the automatic task defaults to "Removed" instead of Pending
### Steps to Reproduce
1. Create a new case, open the automatic task
2. Task shown is defaulted to "Removed" and is cross out in the task directory. 

### Expected Behavior
Should be "Pending"
### Screenshots
![image](https://user-images.githubusercontent.com/19344651/75523343-1fedb180-5a0c-11ea-930f-a2620fd74cd8.png)

### System Details
* Device:
* SORMAS version: 1.33.1.
* Android version/Browser: chrome

**Comment by ChristopherRiedelSymeda** [comment]
@hzi-old I cannot reproduce the described behaviour on my development system (1.34.0) or on the symeda demo server (1.33.0). Can you give me more information about the Steps to Reproduce?

**Comment by hzi-old** [comment]
@ChristopherRiedelSymeda Just create a new case, then go to the case tab, look to the left of the case created under task, you will see that it is removed with a line across the text. It automatically defaults to status "Removed" instead of "Pending". Lets have a call if its not clear. Thanks

**Comment by hzi-old** [comment]
@ChristopherRiedelSymeda Ok I just tried to reproduce it, It does not happen in every case. That is strange. It happened to me twice. Ok I will close this for now.
