### ISSUE TITLE
Automatic address geo location

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1543]
### Bug Description
When you create a person for a case or contact, the address geolocation pin (pick a geo location) does not work. Error- "Geo location point not found"
### Steps to Reproduce
1. Create a case, go to case person, add an address by using the geo location pin
2. pick a location and say yes you are at that location

### Expected Behavior
Should automatically pull the long/lat for the selected address. For Germany, since addresses are geo located, we should have addresses automatically store their geo locations. (this was not possible for Nigeria and Ghana but we should activate this for Germany)
### Screenshots
on mobile app
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
The reason for this is probably that the server is still configured for Nigeria, so geo coordinates outside Nigeria will automatically be discarded, resulting in this message. The solution would be to set the server to use the DE locale.

**Comment by MateStrysewskeSym** [comment]
Works for me with a server set to Germany.
