### ISSUE TITLE
Set cleared to No not working for Symptoms- irritability

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1544]
### Bug Description
When you create a visit, and set all cleared to No, it works for all symptoms except "irritability"
### Steps to Reproduce
1. Create a follow up visit, then set all cleared to No
2. When you scroll down, all the symptoms are selected as NO except "Irritability"

### Expected Behavior
All symptoms should be selected based on the action 
### Screenshots
![image](https://user-images.githubusercontent.com/19344651/75524311-ee75e580-5a0d-11ea-81c6-2134da14dfc1.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by ChristopherRiedelSymeda** [comment]
Is already solved by #1531
