### ISSUE TITLE
Longitude and latitude are partially swapped

### ISSUE THREAD

**Issue by ChristopherRiedelSymeda** [hzi-braunschweig/SORMAS-Project#1547]
### Bug Description
Longitude and latitude are partially swapped

### Additional Information
in StatisticsView.generateMap() and DashboardMapComponent

**Comment by fhauptmann** [comment]
Applies to sormas.properties also. Lat and Lon are swapped, if you enter them via properties.

**Comment by HolgerReiseVSys** [comment]
Deployments that make use of the properties `country.center.latitude` and `country.center.longitude` in `sormas.properties` need to swap their values.
This will also affect https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/.env

**Comment by asohh** [comment]
In the Version 1.36.1 the Latitude and longitude are still swapped. I used following line in the sormas.properies:
country.center.latitude=53
country.center.longitude=10


And the map center is in the arabian sea (expected to be in central germany)

**Comment by MartinWahnschaffeSymeda** [comment]
@asohh Sorry, looks like we didn't merge this to the development branch. So for know please keep the variables swapped. I'll update the release notes accordingly.

**Comment by MartinWahnschaffeSymeda** [comment]
@HolgerReiseVSys Please merge this to the development branch

**Comment by HolgerReiseVSys** [comment]
Is merged
