### ISSUE TITLE
Add  the possibility for users to be able to search a case or person based on the person ID shown on the network diagram

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1552]
### Situation Description
Users at front end cant know the person displayed on the network diagram currently.
### Possible Alternatives
- Add the possibility to search the case and contact list using person ID
- When I click on the icon in a network diagram, I should be able to open the case or person data for the icon

**Comment by MartinWahnschaffeSymeda** [comment]
We plan to use the uuid in the network diagram, so this is not needed (see #1563 )
