### ISSUE TITLE
Associate contacts to a region & district

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1561]
### Situation Description
Currently users see all contacts of the cases they are associated to. When a case has contacts in multiple districts/regions, this currently means that the users in those territories can't see the contacts they need to follow-up.

### Feature Description
Give each contact a region and district field, so all users associated to this territory get access to the contact.

In addition to this the users need to get access (maybe limited) to the source case and also be able to add additional contacts to that source case. Even when the source case is associated to another territory.

- [x] Add region and district field to contact
- [x] Adjust contact userFilter to allow users to see contacts within their jurisdiction
- [x] Adjust case userFilter to allow users to see cases with contacts in their jurisdiction

**Comment by chukwuemekauzoho** [comment]
Can we also have contacts that become symptomatic automatically be converted to suspect cases?
this would enable a contact officer in the field to readily line list new contacts of the symptomatic contacts. 
Can we also be able to line list contacts the way we line list for cases? This will make it easier to to create and follow up on contacts @Chinedar @foyiri @bernardsilenou

**Comment by Chinedar** [comment]
can we have an automatic function with the ability to transfer contacts already existing in the system for a source case to another case? @MartinWahnschaffeSymeda @hzi-braunschweig/sormas-docker

**Comment by MartinWahnschaffeSymeda** [comment]
@chukwuemekauzoho @Chinedar These are reasonable requests. Please create an issue for each request and make sure to give as many details as possible, so we thoroughly understand what is needed.

**Comment by foyiri** [comment]
Am not sure about what we agreed on the subject mather

**Comment by MartinWahnschaffeSymeda** [comment]
In the review today we were not sure whether this may confuse users. One option is to take it out again. On the other hand I feel that it's a valuable tool to be able to assign the contact to a region and district that is reponsible for it. My suggestion is as follows:

- [ ] Change the caption to "Responsible region" and "Responsible districts" and move both fields to the bottom of the contact form. This can be in one line with "responsible contact officer" and would be quite consistent
- [ ] Add a tooltip to both fields that says "Users associated to the responsible region/district will be able to access this contact"
- [ ] Remove all "responsible" fields from the contact create form, since they are optional

@danieltomaba @Chinedar @bernardsilenou What do you think about this?

**Comment by Chinedar** [comment]
Hi Martin,

I completely agree we move it down but we retain it. This is an immediate
solution that will help us greatly as things are.
The tooltip is also a good idea! Thanks.

**Comment by Chinedar** [comment]
Please when can we have this feature released? We urgently need this
feature today...so we can distribute these contacts for follow up. At the
moment, these folks are using paper for the over 1000 cases and might
decide on paper use going forward if we cannot deploy this solution today.
Thanks.

**Comment by MartinWahnschaffeSymeda** [comment]
We are releasing this evening and will update the sormas.symeda.de server. This definitely needs testing before we can update the nigerian server.

**Comment by Chinedar** [comment]
Fabulous. We will test tonight and give you go-ahead to update the Nigerian
server. Please do let us know when you have it on symeda for testing.
Thanks
