### ISSUE TITLE
Allow national users to make a case visible to the whole country

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1562]
### Situation Description
It happens that for a case contacts are identified in the whole country (e.g. someone travelling on a plane). In this case we need to have a way to make it easy for people to add now contacts to that case.

### Feature Description
Allow national users to give users in the whole country access to a case. Those users should at least be able to read the case and add contacts to it.

- [x] Add checkbox to case data form
- [x] Extend case userFilter to include cases that have been made visible to the whole country
- [x] Make this a feature so it can be deactivated (e.g. this would likely not be allowed in DE).

**Comment by MartinWahnschaffeSymeda** [comment]
Feature should be disabled by default. 

- [ ] Extend FeatureType enum with a default value. Would be false for line listing, true for all other features, except NATIONAL_CASE_SHARING
- [ ] Update StartupShutdownService.createMissingFeatureConfigrations to use the default value
- [ ] Move createMissingFeatureConfigrations to FeatureConfigurationService

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make sure this is only availbale for region and national users
- [ ] make case readonly for users that would normally not have access

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar I just realize that we have not made those shared cases readonly to other users. This will be a bit more complicated, so we can't add it quickly. Do you think this is a dealbreaker for using this feature in Nigeria or is it ok?

**Comment by Chinedar** [comment]
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> I'd say we roll it out
because it is an emergency, and then we work on making it read-only in the
nearest possible time. I doubt if anybody will be making any changes to a
case they did not enter (except advised otherwise). It is a risk I am
willing to take given the urgency of having this feature out and ready for
the effectiveness of SORMAS being used in this outbreak. Thanks.

**Comment by MateStrysewskeSym** [comment]
- [ ] Create dedicated user right for sharing cases
