### ISSUE TITLE
Enable users of the web app to search for all cases by uuid

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1566]
### Situation Description
It may happen that a user needs to add a contact in his jurisdication that belongs to a case from another jurisdication.

### Feature Description
Users of the web app need to be able to search all case in the country by epid number, external ID or uuid and access those cases (maybe limited) and add contacts.

**Comment by bernardsilenou** [comment]
In version 1,36,1, an SO log-in on the web can make changes to all the fields of a case that is not in their districts or region. If they search a case and make no change to the case data, the case does not appear among their line-list and in case a change is made to the case, the case remain as part of their line listed cases,  this is good,

By making a case public or giving web users the right to search for a case nationally which are technically the same thing tackled from different angles, we should allow the external user to view and make changes to only the contact, visits, and converting the contact to a case.

**Comment by MartinWahnschaffeSymeda** [comment]
See #1617
