### ISSUE TITLE
Allow district users to access the webapp

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1567]
### Situation Description
Currently users like surveillance officer and contact officer can only access the mobile app. In DE those users also need to be able to access the web app, e.g. when doing follow-up "visits" by phone call.

### Feature Description
Allow district users to access the web app. Check the regional user roles to see where this needs to be handled in the UI.

**Comment by ChristopherRiedelSymeda** [comment]
New allowed user roles for web app:
- Surveillance Officer
- Contact Officer 
- Case Officer

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] fix issue references in commit notes
