### ISSUE TITLE
Display "Convert to case" button even when contact is not confirmed

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1570]
### Problem Description
Users often miss this option when they forget to confirm the contact.

### Proposed Change
When the "convert" button is clicked for an unconfirmed contact a popup should asks the user whether to confirm the contact and then convert.

**Comment by MateStrysewskeSym** [comment]
I've decided to only display an information popup that instructs users to confirm the contact before converting it to a case. Everything else would've been relatively complicated. We can revise this when we've switched to a different UI framework.
