### ISSUE TITLE
Add "external ID" text field to case and contact

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1571]
### Situation Description
When an organisation uses mutliple systems to manage cases and contacts it's necessary to be able to have a shared ID and document it for each case/contact.

### Feature Description

- [x] Case: Add next to epid number field
- [x] Contact: Add next to contact ID field

**Comment by MateStrysewskeSym** [comment]
- [ ] Try to move external ID to the epid number line

**Comment by bernardsilenou** [comment]
When in a contact, on the web, on the right side of the screen is a summary of the case that the contact belong to as shown in figure below:
![image](https://user-images.githubusercontent.com/12996724/76529430-8f36bd00-6472-11ea-813d-6080db062e07.png)

Can we also display the unique id of the case here beside the epid number? Countries that don not use epid number will not be able to know the case that the contact belong to, especially if the user tight does not permit the user to see the name of the source case

This mean we also do the same for sample Id?  Do we display the unique id beside the epid number everywhere it appears in the app?

**Comment by bernardsilenou** [comment]
What about making the pid number configurable when setting the server with properties, users can choose to use "epid number" notation "unque case id". I ask this because displaying the epid number in a country that does not use it make it redundant.

**Comment by MartinWahnschaffeSymeda** [comment]
I have added an todo to hide the epid number in de to issue #1600 
We decided to leave the other parts as is.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make external id visible for "de" systems only (web and app)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] For german systems show external id instead of epid number in case information shown in contacts edit view
- [ ] For german systems show external id instead of epid number in cases directory
