### ISSUE TITLE
Inactive users are still able to login

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1574]
### Bug Description
Some users have been disabled in the system. However, those users are still able to log into the system.

### Steps to Reproduce
1. Do one of the following
    a. Pick an inactive user
    b. Pick an active user and disable it
    c. Create a new user and disable it
2. Logout
3. Try logging in as the chosen inactive user

### Expected Behavior
One should not be able to login

### System Details
* Device: HP laptop running Windows 10
* SORMAS version: 1.33.0
* Android version/Browser: Chrome 80 x64

### Additional Information
This behavior is new because, previously (sometime last year, 2019), it used to block inactive users from logging in.

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Thanks a lot. Found and solved the problem.

**Comment by faatihi** [comment]
Don't mention
