### ISSUE TITLE
Add geocoding for addresses

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1576]
### Situation Description
When new cases and contacts are entered by users from an office or facility (mostly using the web app), those cases can't rely on the automatic geocoding done by the app.

### Feature Description
Add automatic geocoding for addresses to the system. Whenever a location is saved and has no geo coordinates, the system should use the address to identify those coordinates.
Only excemption to this is when a user explicitely removes existing geo coordinates from a location.

The geo coding should be done by a web service. Ideally it should be possible to configure which service to be used and the needed credentials individually for each server instance.

To get started we need to be able to use the german BKG service (https://www.bkg.bund.de/SharedDocs/Produktinformationen/BKG/DE/P-2015/150119-Geokodierung.html).

Later on it would be great to also support the open street map geocoding service.

Note #1547!

**Comment by HolgerReiseVSys** [comment]
Location is referenced from Person, Event, EpiDateGathering, EpiDateBurial and User.
When the Location of Person or Event change, the geocoordinates should be refreshed.
In a first step the geocoding should be triggered via a Button on the LocationEditForm.

**Comment by HolgerReiseVSys** [comment]
Connection to the geocoding endpoints requires a working cacerts file, see Issue #1601.
I have taken the cacerts.jks file from a fresh domain and removed expired certificates.
The following script can be run in the git console, bit is extremely system dependent:
```bash
keytool -v -list -keystore cacerts.jks -storepass changeit | iconv -t UTF-8 -f CP1252 | sed -n '/\(^\(Alias\)\|\(^G.\+ 20[0-9][0-9]$\)\)/p' | sed 's/Alias.\+: //' |sed  -e '{
N
s/\n/ @ /
}' | sed 's/^\(.\+\) @.\+\(....\)$/\2 \1/' | sed -e 's/^201./OLD/' -e 's/1^202[01]/OLD/' | sed -n 's/^OLD //p' | xargs -I{} keytool -delete -keystore cacerts.jks -storepass changeit -alias '{}'
````

**Comment by HolgerReiseVSys** [comment]
Automatic geocoding and support for other geocoding services will be addressed in additional issues

**Comment by MartinWahnschaffeSymeda** [comment]
@HolgerReiseVSys Can be merged to the development branch

**Comment by HolgerReiseVSys** [comment]
is merged

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make osgts/ogts consisten (e.g. property)
