### ISSUE TITLE
Add "Diverse" gender [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1581]
### Feature Description
Selecting the gender of a person

### Problem Description
Only "Male" and "Female" are available, even though many countries officially supports a third gender.

### Proposed Change

- [x] Extend the population data accordingly.
No Population data for unknown

English Label = Sex
German Label = Geschlecht

1.Male
2.Female
3.Other => German: Divers // add it in every country
4.Unknown => German: unbekannt 
(5.) NULL

**Comment by MartinWahnschaffeSymeda** [comment]
We have to define what effects this has on the statistics

**Comment by bernardsilenou** [comment]
I think this means sex, not gender. Gender can have many categories but sex can only be male or female only. If this is the case, I suggest we replace the variable with gender rather than sex

**Comment by markusmann-vg** [comment]
Please use these categories for sex in this order.

- Male
- Female
- Unknown
- Other

Thanks,
Bernard

**Comment by markusmann-vg** [comment]
We still have no final decision.
Last status: I sent the KBV-Key as proposal, which is rather official

**Comment by bernardsilenou** [comment]
Lets use 
Male
Female
Other (Divers in German)
Unknown

**Comment by markusmann-vg** [comment]
Migration:
empty => unknown

**Comment by markusmann-vg** [comment]
@bernardsilenou We have to discuss about how we want to proceed with the population data accordingly

**Comment by bernardsilenou** [comment]
> Migration:
> empty => unknown, 
> Yes please. If possible we drop Unknown for sex please. We keep only
Male
Female
Other (Divers in German speaking countries)
I say do because in other fields that we have in SORMAS, empty != unknown.


> Assumption:
> Incidences will only be calculated with male & females ( all others will be left out )
> Perfect solution for now.

**Comment by bernardsilenou** [comment]
All servers should have 
Male
Female
Other ( On German server, Other will be translated to "Divers")

**Comment by markusmann-vg** [comment]
@bernardsilenou : Is this confirmed by Gerard Krause? I would like to receive an official mail about this topic and the HZI decision.

**Comment by bernardsilenou** [comment]
@markusmann-vg 
We had a second look and with servnet and realised they document unkown for sex, this is why we decided to add it also. So I have deleted the old comment and we go with the initial suggestions please.
Male
Female
Other 
Unknown

**Comment by bernardsilenou** [comment]
> @bernardsilenou : Is this confirmed by Gerard Krause? I would like to receive an official mail about this topic and the HZI decision.
For sec categories, yes but for migration concept no, I have not discussed migration with him.

**Comment by markusmann-vg** [comment]
As discussed on the 06th of July with Gerard:
English Label = Sex/Gender 
German Label = Geschlecht

Male
Female
Other => German: Divers // add it in every country
Unknown => German: unbekannt

**Comment by bernardsilenou** [comment]
Perfect!

**Comment by MateStrysewskeSym** [comment]
@markusmann-vg That makes absolutely no sense to me. Sex and gender are two completely different things and shouldn't be mixed.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym you are absolutely right, however we decoded to go with this solution to make everyone happy.
Since sormas is a tool to collect surveillance data, the variable requested by WHO is "sex at birth"  not "Gender". Going with your solution will require that we call the variable "sex at birth" with categories male, female and rarely intersex only.
Users in the field want options for gender to be listed under sex, so that why i think we can label it sex/gender.

**Comment by BarnaBartha** [comment]
As null values until now have been shown on the UI (in some scenarios) as 'Unknown' and we want to support unknown separate from null I've updated the label used for null in the UI to 'Not specified'.

**Comment by MartinWahnschaffeSymeda** [comment]
Reviewed.

**Comment by bernardsilenou** [comment]
I think in future we will end up adding 'unknown' to all variables even if we do not show then on the ui. This will help us to separate them from NULL when the need be
