### ISSUE TITLE
Error in helmholtz server

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1584]
**### Bug Description**
An error occurs in the configuration menu of the helmholtz practice server
@MartinWahnschaffeSymeda @MateStrysewskeSym 

### Screenshots

![ssormas error](https://user-images.githubusercontent.com/50739609/76426376-4536d400-63ab-11ea-98a8-58867a332433.JPG)

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Sorry, we can't do anything about that. I believe it might be associated with the duplicate infrastructure data that's currently present on the HZI server, but we don't have access to it. You'll need to talk to @danieltomaba directly.
