### ISSUE TITLE
Mobile app logs out after update to 1.35.0

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1589]
### Bug Description
The mobile app logs out after automatically updating to 1.35.0
### Steps to Reproduce
1. Update the mobile app and the app closes
2. Reopen the app and it automatically logs out.

### Expected Behavior
Should not log out after automatic update. Error says sormas server is not online. But I use full network internet
### System Details
* Device: Samsung 
* SORMAS version: 1.35.0
* Android version/Browser: Android 10

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-old To which server was the app connected?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-old To which server was the app connected? Did you have to enter the server url as-well?

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda server was connected to symeda server.

**Comment by MartinWahnschaffeSymeda** [comment]
Ok, I found something that could have caused it, if the url was not 100% correct (e.g. whitespaces) and the settings were saved again. Still fells like this is likely not what happened, but I can't manage to reproduce any other problem.

When updating sormas.symeda.de we have to test this again.
