### ISSUE TITLE
Move hospitalization data into case form

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#159]
@stoikkanen @dta16 
In the feedback you sent last friday it says:" Case Data - In this view there is no need for the Hospital information, comes on the hopitalisation –tab and needs to preselected to match the hospital informant’s Health facility"

We have thought about this, but aren't sure if it's a good idea. The case's health facility, community, district and region are core parts of the whole case logic and should probably better stay in the case data form.
I'd suggest to talk about this on Friday.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Good point. I agree. Lets discuss on friday

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] create a moqup
- [ ] move date of admission & discharge and isolation to case data form
- [ ] move previous hospitalizations to case data form. Should be accesible in a popup or extending form

**Comment by MartinWahnschaffeSymeda** [comment]
In the mean-time the hospitalization data has even grown, so it doesn't seem to be a good idea to bring both sections together. Better leave as-is.
