### ISSUE TITLE
Import of health facility data

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#1590]
### Bug Description
When I try to import health facility data I have to set the type to 'PRIMARY'. But data is not shown after import0
### Steps to Reproduce
1. Import a csv file with health facility data
2.If you leave the type column empty the data is not imported
3. If you set type to 'PRIMARY' the data is imported, but it is not shown in the list after import
4. If you execute ''UPDATE facilities set type = NULL where type = 'PRIMARY';" in the database, the facilities are shown

### Expected Behavior
Show the imported facilities in the list after successful import
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
I've just fixed this bug in issue #1582.
