### ISSUE TITLE
Add "high priority" status to contact

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1595]
#1514 # Situation Description
Some contacts should have a high priority to make sure contact follow up is done for them when users have a very high workload.

### Feature Description

- [x] Add "high priority" checkbox to contact. In addition add two new questions:
- [x] "immunosuppressive therapy or basic disease is present" (yes /no/unknown) / "Liegt eine immunsupprimierenden Therapie oder Grunderkrankung vor?"
- [x] yes: text field for specification
- [x] "is the person medically/nursingly active in the care of patients or people over 60 years of age?" / "Ist die Person medizinisch/pflegend in der Betreuung von Patienten oder Menschen über 60 Jahre tätig?"
- [x] When any of those two questions is answered with yes, the high priority checkbox should be automatically set
- [x] the two questions should only be available for "de"
- [x] Add filter option to contacts directory
- [x] automatic tasks create for follow up should have a high priority when the contact is high priority

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda : This question should only be triggered for type 1 contacts, right?

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Not sure. Please check with the HZI team and let us know during the review.
