### ISSUE TITLE
Identify and add backend methods that should have access checks

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1596]
### Problem Description
Currently the backend of SORMAS has no dedicated access checks, which makes it vulnerable to bugs in the UI and ReST interface.

### Proposed Change
Add validation methods to all public methods in the backend that allow to read or edit data in the system.

Add validate**Read**Access(uuid) & validate**Write**Access(uuid) methods to all facades. These methods should do a check based on user rights and throw an exception when the user does not have access.
From my understanding we don't need that for methods that return a list of entries. Those methods already apply the user filter.

See #1591 which contains the logic for case and contact. (timebox 1 day)

- [ ] identify the methods that require access validation and review

### Investigation
@leventegal-she

**Comment by leventegal-she** [comment]
### Investigation Results

#### All methods should be secured: 
  * the ones returning lists should be accessed only if the user has at least **VIEW* user right (e.g. CASE_VIEW in case of CaseFacadeEjb)
  * getByUuid, getReferenceByUuid, save, delete methods should be secured by user right and jurisdiction
  * custom business methods: to be decided for each when implementing
    For example:
    * Methods called from `CronService` should be secured by the *_SYSTEM* user role
    * Public methods not called from outside the facade should be changed to *private* or *protected*

#### Suggestions for implementation
* Use interceptors to have cleaner code, less boilerplate and and secure all methods for read access from single place by adding an interceptor on the facade class
* Improve the performance of user right checking methods. 
* Introduce a base class for the facades, based on `AbstractAdoService` to have all similar methods secured at a common place so on one in the future will forget to secure during the implementation of new facades. This would also be helpful when introducing new modules/features in the future, like new pages for *Campaign*; it would take a lot less time to implement and would be less error-prone.

#### Links
[Interceptor docs](https://docs.jboss.org/ejb3/app-server/tutorial/interceptor/interceptor.html)
[Interceptor binding docs](https://docs.jboss.org/cdi/spec/1.0/html/interceptors.html)
