### ISSUE TITLE
Remove user uuids from backend calls

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1597]
### Problem Description
Manually passing the user uuid to the backend is redundant.
Example: CaseFacade.getAllActiveCasesAfter(Date date, **String userUuid**)

### Proposed Change
Instead use the JEE context to identify the current user.

**Comment by HolgerReiseVSys** [comment]
`UserService::getCurrentUser` already retrieves the `User` from the Context. 
It is, however, not clear if the complete User entity is needed in every case.
It is to be expected that the `User` will be needed several times per request. 
Hence having a caching mechanism is advisable.
A RequestScoped or SessionScoped CDI Bean `CurrentUser` could wrap the access to the User,
its producer method could be located in `UserService`.
`AbstractAdoService`, the Facades etc. could have an `Instance<CurrentUser>` injected.
Having `CurrentUser` in session scope may result in the `UserRole`s being out of sync with those in the Context.

**Comment by HolgerReiseVSys** [comment]
I have noticed there are quite a few methods in the jax-rs resorces that still get the SecurityContext injected; Just want to make sure that they won't be forgotten.

**Comment by HolgerReiseVSys** [comment]
Further refactoring is deferred to #1810
