### ISSUE TITLE
Create new contacts from the contacts list (source case optional) [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1599]
### Situation Description
It often happens that users are confronted with contacts from other areas wihout being able to create the source case of the contact. The source case may be available at a later point in time.

### Feature Description
Allow users to create a new contact from within the contact directory. This mainly means that we need a field that allows to select an existing case - most likely by searching based on uuid, epid number and/or name.

Prerequisits

- add disease field to contact -> #1643

Todos

- [x] Create contact from contact directory (add button)
- [x] Make case optional for contact in backend
- [x] Overhaul all code that works with the contact-case association
- [x] Contact creation and edit form needs a disease field

Addition (24.03): When users decide not to pick a case, they are provided with two fields:

- [x] “Case ID in external system”: A short text field that allows them to provide any ID (e.g. UUID, EPID number, …) of the case in another system. This can later be used to semi-automatically associate the contact to that case.
- [x] “Case or event information”: A  bigger text field that allows the user to add some additional details on the case or event that makes that is the reason to do contact follow up for the person.

Later 

- case search component -> #1645

**Comment by MateStrysewskeSym** [comment]
- [ ] Add case or event information field to contact create forms
- [ ] Move the two new fields between region/district and quarantine information
- [ ] MessagingService: use new constant without case
