### ISSUE TITLE
Invalid cacerts file blocks publish of sormas artifacts

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#1601]
[StackTrace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4339017/StackTrace.txt)
### Bug Description
When setting up a SORMAS system on my windows machine, I ran into the following exception when deploying a sormas- artifact:

java.lang.IllegalStateException: java.security.cert.CertificateException: Unable to initialize, java.io.IOException: DerInputStream.getLength(): lengthTag=92, too big.
	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initStores(SecuritySupportImpl.java:451)
	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initStores(SecuritySupportImpl.java:412)
	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initJKS(SecuritySupportImpl.java:386)
...
Caused by: java.security.cert.CertificateException: Unable to initialize, java.io.IOException: DerInputStream.getLength(): lengthTag=92, too big.
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:198)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:105)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:760)
...
	at com.sun.enterprise.security.ssl.impl.SecuritySupportImpl.initStores(SecuritySupportImpl.java:436)
	... 94 more

### Steps to Reproduce
1. Set up a sormas system with setup guide (Windows, Zulu8, Payara 5.192 or Payara 5.194)
2. Start domain
3. Publish sormas-ear or sormas-ui with Eclipse and Payara Tools 

### Expected Behavior
Publish shoud not throw this exception.

### System Details
* Device: Windows 10
* SORMAS version: 1.35.0
* Android version/Browser: Firefox

### Additional Information
Workaround: Use an empty cacerts.jks (or only on but valid certificate) instead.

**Comment by StefanKock** [comment]
In #1122 the approach was altered from cacerts.jks to cacerts.txt, and the file was altered once again in #1198 (commit cba9d10d3e7b89e588554c518ceca4663f026916).

Possible explanations for problem:
1. Since cacerts.txt is checked in, the line endings are altered by git on windows machine.
2. The file is corrupted because of not intended changes.

**Comment by StefanKock** [comment]
Tried with other states of cacerts.jks:
- Download the file from Github results in another exception: CertificateParsingException: signed overrun, bytes = 521
- Copy from linux (development HEAD) results in exception from above

**Comment by StefanKock** [comment]
I found #1152 with a working cacerts.jks, but in the meantime there are new expired certificates.

**Comment by HolgerReiseVSys** [comment]
For new setups I have removed  ca certs expiring before 2022 from a current cacerts store according to [#1576](https://github.com/hzi-braunschweig/SORMAS-Project/issues/1576#issuecomment-600588321).
This should kick the can down the road until May 2022.

**Comment by StefanKock** [comment]
@HolgerReiseVSys please documented how you did remove certificates in case someone has to do it again.

**Comment by HolgerReiseVSys** [comment]
For new setups I have removed ca certs expiring before 2022 from a current cacerts store according to [#1576](https://github.com/hzi-braunschweig/SORMAS-Project/issues/1576#issuecomment-600588321):

> I have taken the cacerts.jks file from a fresh domain and removed expired certificates.
The following script can be run in the git console, bit is extremely system dependent:
```bash
keytool -v -list -keystore cacerts.jks -storepass changeit | iconv -t UTF-8 -f CP1252 | sed -n '/\(^\(Alias\)\|\(^G.\+ 20[0-9][0-9]$\)\)/p' | sed 's/Alias.\+: //' |sed  -e '{
N
s/\n/ @ /
}' | sed 's/^\(.\+\) @.\+\(....\)$/\2 \1/' | sed -e 's/^201./OLD/' -e 's/1^202[01]/OLD/' | sed -n 's/^OLD //p' | xargs -I{} keytool -delete -keystore cacerts.jks -storepass changeit -alias '{}'
````

The Expression `'s/1^202[01]/OLD/'` would have to be adjusted to match the years to be removed.
