### ISSUE TITLE
UI partly in German although English is selected

### ISSUE THREAD

**Issue by ChristopherRiedelSymeda** [hzi-braunschweig/SORMAS-Project#1606]
### Bug Description
UI partly in German although English is selected
### Steps to Reproduce
1. Server Locale de
2. Import case contact with duplicate person

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/42139870/76952065-cee72400-690c-11ea-907b-7d6b4c87c7df.png)

**Comment by MateStrysewskeSym** [comment]
Seems to work fine now.
