### ISSUE TITLE
Change COV TO COVID-19

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#1610]
The disease for COV need to change to new name COVID-19

**Comment by foyiri** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym I think we need this asap

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] change the caption for the short term

**Comment by Iheanacho2027** [comment]
I dont know if this has been implemented, but just need to notify in case @MartinWahnschaffeSymeda @MateStrysewskeSym are not aware, when creating a new case, on the dropdown for list of diseases on the disease variable, COVID-19 is still seen as Coronavirus (CoV) in the latest release 1.36.1

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda Can you explain why you decided to do this only for the short caption, not for the normal one? I think COVID-19 is the officially used term for the new Coronavirus in any case.

**Comment by MartinWahnschaffeSymeda** [comment]
It was my understanding based on the request to change "COV" to COVID-19. 

- [ ] change disease caption of Coronavirus to COVID-19
