### ISSUE TITLE
"Unsaved changes" warning for the web app [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1613]
### Situation Description
Currently users are not warned about unsaved changes and thus those changes get lost.

### Feature Description
For each form of the web application make sure that the users receives a warning when leaving the form with unsaved changes. The warning should allow the user to either cancel leaving the form, discard the changes or save the changes.
The save option should have a primary button style. The discard option should be next to it with a normal button style. The cancel option can either be a minor button or no button at all (just the close icon in the top right).

**Comment by raghupola-vg** [comment]
As per the discussion in Review, there should be a new button for cancel.
