### ISSUE TITLE
Type of contact is not filtered based on countries specific classification

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1619]
### Feature Description
The type of contact proximity should be different on the German server than the other versions.
Version 1,36,1 on symeda server displayed all possible contact types. We need to hide certain fields and make it possible for users to select more than one of the categories of contact proximity types

**Comment by bernardsilenou** [comment]
This happens only when SO or CO, or informant  is login on the web, All is fine on the mobile interface or when log in as National user

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The altered contact proximities on German servers only apply to COVID-19, not to contacts to cases with any other disease.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  Please have a look at this image. Contact creation for COVID-19 on web, there are duplicate entries. This is on development server. 1,36,2

![image](https://user-images.githubusercontent.com/12996724/77680401-2d0ea980-6f94-11ea-8391-b6b91381113a.png)
