### ISSUE TITLE
Add duplicate detection to infrastructure import

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#1621]
### Bug Description

The duplicate detection is not working, when importing regions:

### Steps to Reproduce
1.Got to settings -> regions
2. Import regions into sormas
3. Import the same region file again

Every regions is listed two times. 

### Expected Behavior
The regions should be detected as duplicates. Only one region should exist.

### System Details
* Device: Web client
* SORMAS version: 1.36.1
* Android version/Browser:

### Additional Information

import file is attachted. 
[sormas_import_region_germany.csv.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4360608/sormas_import_region_germany.csv.txt)

**Comment by bernardsilenou** [comment]
We discussed this issue long but have not made it a priority. Maybe it it time to prioritize duplicate detection for infrastructure data while importing and also while creating them one-by-one,

**Comment by MateStrysewskeSym** [comment]
Just for the record, this is not a bug. It's a feature that has not yet been implemented.

**Comment by bernardsilenou** [comment]
User are allowed to create infrastructure data but  after saving the data, they cant edit it. We should make it editable,

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove booleans from save methods and do a UUID check instead

**Comment by MateStrysewskeSym** [comment]
- [ ] Don't retrieve the DTO twice
