### ISSUE TITLE
Import: Districts externalID is not imported

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#1622]
### Bug Description
When I import districts and submit an externalID, the externalID is not imported. 
### Steps to Reproduce
1. got to settings -> districts
2.import a csv file

external id is empty

### Expected Behavior
external id should be set

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

### Additional Information
please see attached csv file

**Comment by fhauptmann** [comment]
[sormas_import_district_landkreise.csv.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4361182/sormas_import_district_landkreise.csv.txt)

**Comment by MateStrysewskeSym** [comment]
@fhauptmann The external IDs are properly imported, they're just not shown in the list because of a typing error. I've fixed this, you don't need to re-import the districts, the IDs will just show up.
