### ISSUE TITLE
Error on importing district (LGA) of contact

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1625]
### Bug Description
An error occurs when trying to import contacts using the contact import template, the error says "Unexpected error when   trying to import this row. Please send your error report file to an   administrator and remove this row from your import file." This occurs with the presence of variables on the person.district or district column of the import template @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
This error is not only restricted to contacts; in general, importing cases and contacts with persons that have any infrastructure field filled, the importers always use the case or contact infrastructure data as a reference, which does not work when this data differs.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  But in SORMAS,  the region of the contact person or the contact can be different from that of the case.
