### ISSUE TITLE
Contact list search functionality on mobile app [1]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1627]
### Situation Description
Currently, their is no search functionality for contacts listed on the mobile app. This feature is only available for the cases listed.
### Feature Description
search functionality should be enabled for contacts listed on the mobile app. This will enable the users to easily identify a contact for follow-up amongst the hundreds listed.

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda is this likely to come with the next release? 
folks with over 500 contacts in their districts have to scroll all the way to find a contact to be visited. Quite cumbersome. I'd say urgently needed. Thanks.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] don't override FilterDateField.changeVisualState when there are no differences to the super class

Created new issue for keyboard overlap problem #1776
