### ISSUE TITLE
Add ReST interface to allow external addition of contact visits (PIA) [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1628]
### Situation Description

In the current COVID situation it would help a lot if it was possible to use end-user tools to allow them to provide their contact visit information on their own. Thus the contact follow up teams could focus on validating the data and going after the high risk contacts.

### Feature Description

- [x] Create a new ReST Resource: PiaVisitsResource (/piavisits) -> find a more generic name
- [x] create a new user role and limit the access to the resource to this role
- [x] Provide a ReST method to check whether a Contact UUID is valid
- [x] Provide a ReST method to create a visit for a **contact** (currently this is still dependent on the person, but this is impractical from the user's point of view). THis is likely best done by adding a second param for the contact uuid and ignoring the person in the visit
- [x] Provide a getVersion method (see InfoResource)
- [x] Provide a isCompatibleToApi method (see InfoResource). The minimum required version here is specific to the dtos used in this resource! Add a note to getMinimumRequiredVersion in InfoProvider to let developers know that they have to look into this.
- [x] Create a guide on how to use this interface

26.03.2020: Discussed this with Oliver Frietsch - should work as defined.

**Comment by HolgerReiseVSys** [comment]
The existing Resources are restricted to the USER-Role, which is specified in `/sormas-rest/src/main/webapp/WEB-INF/glassfish-web.xml`
The PIA user must not have this role.
For the Vaadin app the USER-Role is specified in `/sormas-ui/src/main/webapp/WEB-INF/glassfish-web.xml`.
It seems to be a bit confusing that these two definitions do not match;
They should probably not be named the same.

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha I just had a discussion with Maté on this.
We realized that it probably does not help a lot ot have the isCompatible method, because many changes in the symptoms won't be relevant for PIA. 

- [ ] Remove isCompatible...
- [ ] getVersion should return the SORMAS api version of the last change of the involved dtos (basically what is currently the MIN... version

**Comment by BarnaBartha** [comment]
The REST API for adding external visits can be used with basic authentication, using username and password of a user having the External Visits User role in Sormas

## Getting API version

### Request:
GET @ {SERVER_URL}/visits-external/version
URL example: http://localhost:6080/sormas-rest/visits-external/version

### Response:
returns the minimal version needed for compatibility with the external rest api of sormas
Example:
` "1.37.0"
`
## Checking contact validity

### Request:
GET @ {SERVER_URL}/visits-external/contact/{contactUuid}/isValid
URL example: http://localhost:6080/sormas-rest/visits-external/contact/{contactUuid}/isValid

### Response:
returns boolean literal
"true" - if contactUuid is valid
"false" - otherwise


## Saving visits
### Request:
POST @ {SERVER_URL}/visits-external/
URL example: http://localhost:6080/sormas-rest/visits-external/
Body example:

```
[
	{
		"contactUuid": "S3CJF2-Y7SCJZ-NQVERG-43CGCDL4",
		"visitDateTime": "2020-04-15T12:55:00.000+02:00", // datetime format yyyy-MM-dd'T'HH:mm:ss.SSSZ 
		"visitStatus": "COOPERATIVE", // can be "UNAVAILABLE" "UNCOOPERATIVE" "COOPERATIVE"
		"visitRemarks": "all is good",
		"reportLat": "49.439557",
		"reportLon": "12.901467",
		"reportLatLonAccuracy": "1",
		"symptoms": {
			"temperature": "37.1",
			"temperatureSource": "NON_CONTACT", // can be "AXILLARY" "ORAL" "RECTAL" "NON_CONTACT"
			"symptomsComments": "lots of symptoms",
			"abdominalPain": "YES",  // can be "YES" "NO" "UNKNOWN"
			"alteredConsciousness": "UNKNOWN", // can be "YES" "NO" "UNKNOWN"
			"anorexiaAppetiteLoss": "UNKNOWN", // can be "YES" "NO" "UNKNOWN"
			"backache": "UNKNOWN", // all other symptoms can be "YES" "NO" "UNKNOWN" ...
			"bedridden": "UNKNOWN",
			"blackeningDeathOfTissue": "NO",
			"bleedingVagina": "YES",
			"bloodInStool": "YES",
			"bloodUrine": "NO",
			"bloodyBlackStool": "YES",
			"buboesGroinArmpitNeck": "NO",
			"bulgingFontanelle": "YES",
			"chestPain": "UNKNOWN",
			"chillsSweats": "NO",
			"confusedDisoriented": "YES",
			"conjunctivitis": "NO",
			"cough": "YES",
			"coughingBlood": "NO",
			"darkUrine": "NO",
			"dehydration": "UNKNOWN",
			"diarrhea": "NO",
			"difficultyBreathing": "NO",
			"digestedBloodVomit": "UNKNOWN",
			"eyePainLightSensitive": "YES",
			"eyesBleeding": "NO",
			"fatigueWeakness": "NO",
			"fever": "YES",
			"fluidInLungCavity": "YES",
			"gumsBleeding": "NO",
			"headache": "UNKNOWN",
			"hearingloss": "NO",
			"hemorrhagicSyndrome": "UNKNOWN",
			"hiccups": "NO",
			"hyperglycemia": "NO",
			"hypoglycemia": "UNKNOWN",
			"injectionSiteBleeding": "NO",
			"jaundice": "UNKNOWN",
			"jointPain": "NO",
			"kopliksSpots": "UNKNOWN",
			"lesions": "UNKNOWN",
			"lesionsDeepProfound": "UNKNOWN",
			"lesionsResembleImg1": "UNKNOWN",
			"lesionsResembleImg2": "UNKNOWN",
			"lesionsResembleImg3": "UNKNOWN",
			"lesionsResembleImg4": "YES",
			"lesionsSameSize": "UNKNOWN",
			"lesionsSameState": "YES",
			"lesionsThatItch": "UNKNOWN",
			"lossSkinTurgor": "UNKNOWN",
			"lymphadenopathyAxillary": "UNKNOWN",
			"lymphadenopathyCervical": "YES",
			"lymphadenopathyInguinal": "UNKNOWN",
			"malaise": "YES",
			"meningealSigns": "NO",
			"musclePain": "YES",
			"nausea": "UNKNOWN",
			"neckStiffness": "NO",
			"noseBleeding": "UNKNOWN",
			"oedemaFaceNeck": "UNKNOWN",
			"oedemaLowerExtremity": "NO",
			"oralUlcers": "YES",
			"otherHemorrhagicSymptoms": "UNKNOWN",
			"otherNonHemorrhagicSymptoms": "UNKNOWN",
			"otitisMedia": "UNKNOWN",
			"painfulLymphadenitis": "NO",
			"palpableLiver": "YES",
			"palpableSpleen": "NO",
			"pharyngealErythema": "UNKNOWN",
			"pharyngealExudate": "YES",
			"rapidBreathing": "NO",
			"redBloodVomit": "YES",
			"refusalFeedorDrink": "YES",
			"runnyNose": "YES",
			"seizures": "YES",
			"sepsis": "UNKNOWN",
			"shock": "NO",
			"sidePain": "NO",
			"skinBruising": "NO",
			"skinRash": "YES",
			"soreThroat": "YES",
			"stomachBleeding": "NO",
			"sunkenEyesFontanelle": "YES",
			"swollenGlands": "YES",
			"throbocytopenia": "NO",
			"tremor": "NO",
			"bilateralCataracts": "NO",
			"unilateralCataracts": "YES",
			"congenitalGlaucoma": "YES",
			"pigmentaryRetinopathy": "YES",
			"purpuricRash": "UNKNOWN",
			"microcephaly": "UNKNOWN",
			"developmentalDelay": "UNKNOWN",
			"splenomegaly": "YES",
			"meningoencephalitis": "UNKNOWN",
			"radiolucentBoneDisease": "UNKNOWN",
			"congenitalHeartDisease": "YES",
			"unexplainedBleeding": "NO",
			"vomiting": "NO",
			"hydrophobia": "YES",
			"opisthotonus": "NO",
			"anxietyStates": "NO",
			"delirium": "YES",
			"uproariousness": "YES",
			"paresthesiaAroundWound": "NO",
			"excessSalivation": "UNKNOWN",
			"insomnia": "NO",
			"paralysis": "YES",
			"excitation": "NO",
			"dysphagia": "UNKNOWN",
			"aerophobia": "UNKNOWN",
			"hyperactivity": "YES",
			"paresis": "UNKNOWN",
			"agitation": "UNKNOWN",
			"ascendingFlaccidParalysis": "UNKNOWN",
			"erraticBehaviour": "YES",
			"coma": "UNKNOWN",
			"convulsion": "YES",
			"fluidInLungCavityAuscultation": "UNKNOWN",
			"fluidInLungCavityXray": "UNKNOWN",
			"abnormalLungXrayFindings": "UNKNOWN",
			"conjunctivalInjection": "YES",
			"acuteRespiratoryDistressSyndrome": "YES",
			"pneumoniaClinicalOrRadiologic": "UNKNOWN"
		}
	}
]
```

### Response:
returns a list of responses corresponding to the received visits list with a status code for each 
Example:
```
[
    "OK",
    "ERROR"
]
```
