### ISSUE TITLE
Automatic GPS loading when an address is registered is not activated on the Muster server

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1629]
### Bug Description
We could pick the gps coordinate before but it does not work now.
### Steps to Reproduce
1. Log to  <https://musterstadt.sormas-oegd.de/sormas-ui/#!contacts/person/RUOLNY-BMSL74-6SZ53Q-FB54SLLU>
2. Creat a case or contact person
3. there is no button to pick the gps coordonate

### System Details
* Device:
* SORMAS version: 1.36.1
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
This has never been possible in the web app because there's no GPS module on desktop devices. You need to use the mobile app to pick the GPS coordinates.

**Comment by bernardsilenou** [comment]
Danke
