### ISSUE TITLE
New feature requests

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1630]
There's been some new requests from GHS

1. Event participants must have follow up information - this is due to the State 
Quarantine being done in Ghana now for all travelers who arrive in the country. They 
are neither cases nor contacts to cases, but they are being quarantined and monitored 
for 14 days. The monitoring involves checking their temperature and signs and 
symptoms everyday for 14 days until they become a case of are discharged from 
quarantine.
   For now, we've asked them to create cases for each of the event persons and leave those
cases as "Not yet classified", while we work on this request.

2. sormas-app: Contact Listing should have  filter/search. The Case Listing view already has this feature. 
   I just found a similar issue #1627

3. One suggestion is to have the possibility of assigning cases to contact officers to 
follow up. Currently we can only assign those cases in the contact officer’s district 
only. Can there be a situation where we can select contacts of a case and assign them 
to a specific contact officer even though the case is not in their district?

4. sormas-app: Dropdown fields should have a search box. When options are so many in these fields, its difficult to find one's option.

I'll open new issues for each of these points once we take a look at them.

**Comment by MateStrysewskeSym** [comment]
@faatihi Please don't open collection issues. Instead, please create one issue per request - it's way easier for us to organise them this way. Thanks!

**Comment by faatihi** [comment]
Yes, this one is for deliberation. I'm doing it this way for management to easily follow issues from a single page. Once these points are regarded as actual issues, I'll open separate issues for them and tag their numbers to the above points.

**Comment by MartinWahnschaffeSymeda** [comment]
I have updated the above description with the numbers of the related issues.

**Comment by faatihi** [comment]
Thanks, @MartinWahnschaffeSymeda
