### ISSUE TITLE
Ability to assign officers to cases that are not in their district

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#1632]
### Situation Description
One suggestion is to have the possibility of assigning cases to contact officers to
follow up. Currently we can only assign those cases in the officer’s district only.

### Feature Description
We need a way to select contacts of a case and assign them to a specific contact officer even though the case is not in their district?

**Comment by MartinWahnschaffeSymeda** [comment]
See #1632. Assigning a contact to another region and district is now possible.
The officers of that district will be selectable in the upcoming release #1579 .
