### ISSUE TITLE
Add contact category and type of contact comment [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1635]
### Situation description
The contact types in SORMAS don't fully reflect the types needed for Germany. In addition users need to be able to now the category of a contact and use this to filter contacts in the directory.

### Feature Description
Add a contact type details and a contact category field to the contact in SORMAS. In addition refine the available list of contact types and automatically set the contact category based on a selected contact type.

Contact type is the ContactProximity. All of the following should **only be visible for Germany**:

- [x] ContactProximityDetails: Type of contact comment field (add bewlow ContactProximity)
- [x] New field ContactCategory
  HIGH_RISK: Category 1 - High risk contact "Kontaktperson der Kategorie I (enger Kontakt)"
  LOW_RISK: Category 2 - Low risk contact "Kontaktperson der Kategorie II (geringes Infektionsrisiko)"
  NO_RISK: Category 3 - No risk contact "Kontaktperson der Kategorie III"
- [x] Change ContactProximity (also give the field in UI full layout width)
   - [x] FACE_TO_FACE_LONG: Personen   mit kumulativ mindestens 15-minütigem Gesichtskontakt -> C1
   - [x] TOUCHED_FLUID: Personen mit direktem Kontakt   zu Sekreten oder Körperflüssigkeiten -> C1
   - [x] AEROSOL: Personen, die aerosolbildenden   Maßnahmen ausgesetzt sind -> C1
   - [x] MEDICAL_UNSAVE: Medizinisches Personal mit   Kontakt zum bestätigten COVID-19-Fall im Rahmen von Pflege oder medizinischer   Untersuchung (≤ 2m), ohne verwendete Schutzausrüstung. -> C1
   - [x] SAME_ROOM: Personen, die sich im selben Raum wie ein bestätigter COVID-19-Fall aufhielten -> C2
   - [x] FACE_TO_FACE_SHORT: Familienmitglieder, die keinen mindestens 15-minütigen Gesichts- (oder Sprach-) kontakt hatten  -> C2
   - [x] MEDICAL_SAME_ROOM: Medizinisches Personal,   welches sich ohne Verwendung adäquater Schutzbekleidung im selben Raum wie   der bestätigte COVID-19-Fall aufhielt, aber eine Distanz von 2 Metern nie   unterschritten hat. -> C2
   - [x] MEDICAL_SAVE: Medizinisches   Personal mit Kontakt ≤ 2 m (z.B. Fall im Rahmen von Pflege oder medizinischer   Untersuchung), wenn eine adäquate Schutzbekleidung während der gesamten Zeit   des Kontakts gemäß Kategorie I getragen wurde -> C3
   - [x] MEDICAL_DISTANT: Medizinisches Personal mit   Kontakt > 2 m, ohne direkten Kontakt mit Sekreten oder Ausscheidungen   der/des Patientin/en und ohne Aerosolexposition -> C3
   - [x] Remove AIRPLANE: Set Details to "Plane"
- [x] When a contact proximity is chosen the system should automatically select the related contact category
- [x] Add the ContactCategory to the ContactsGrid (left side of contact proximity)
- [x] Add a filter to show only contacts of a certain ContactCategory

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] change order of proximities according to list

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] always update the category when the type changes

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] fix bug on using other disease than COVID-19 with ContactProximity

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add the two new fields to the create form as-well
- [ ] trySetContactProximityDetails -> updateContactCategory. Also remove the disease check and do nothing as default action in the switch statement

**Comment by MateStrysewskeSym** [comment]
- [ ] Add missing null check to contact creation form
