### ISSUE TITLE
Server setup: Problem with temporal tables and postgres version

### ISSUE THREAD

**Issue by suhasgopinath** [hzi-braunschweig/SORMAS-Project#1636]
I am from India and we need this urgently during COVID-19. Can you please help me with this error.

I deployed on ubuntu 16.04 - 64 bit and postgres 9.5 (And 10 as well)

First temporal files didnt get updated -> See the error
-------------
pgxn install temporal_tables

INFO: best version: temporal_tables 1.2.0

INFO: saving /tmp/tmphMFgoE/temporal_tables-1.2.0.zip

INFO: unpacking: /tmp/tmphMFgoE/temporal_tables-1.2.0.zip

INFO: building extension

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o temporal_tables.o temporal_tables.c

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o versioning.o versioning.c

versioning.c: In function 'versioning':

versioning.c:249:14: error: incompatible types when assigning to type 'Form_pg_attribute {aka struct FormData_pg_attribute *}' from type 'FormData_pg_attribute {aka struct FormData_pg_attribute}'

  period_attr = tupdesc->attrs[period_attnum - 1];

              ^

versioning.c: In function 'fill_versioning_hash_entry':

versioning.c:502:8: error: incompatible types when assigning to type 'Form_pg_attribute {aka struct FormData_pg_attribute *}' from type 'FormData_pg_attribute {aka struct FormData_pg_attribute}'

   attr = tupdesc->attrs[i];

        ^

versioning.c:514:16: error: incompatible types when assigning to type 'Form_pg_attribute {aka struct FormData_pg_attribute *}' from type 'FormData_pg_attribute {aka struct FormData_pg_attribute}'

   history_attr = history_tupdesc->attrs[history_attnum - 1];

                ^

versioning.c: In function 'insert_history_row':

versioning.c:614:21: warning: implicit declaration of function 'heap_openrv' [-Wimplicit-function-declaration]

  history_relation = heap_openrv(relrv, AccessShareLock);

                     ^

versioning.c:614:19: warning: assignment makes pointer from integer without a cast [-Wint-conversion]

  history_relation = heap_openrv(relrv, AccessShareLock);

                   ^

versioning.c:727:2: warning: implicit declaration of function 'relation_close' [-Wimplicit-function-declaration]

  relation_close(history_relation, AccessShareLock);

  ^

versioning.c: In function 'deserialize_system_period':

versioning.c:762:18: warning: implicit declaration of function 'DatumGetRangeType' [-Wimplicit-function-declaration]

  system_period = DatumGetRangeType(datum);

                  ^

versioning.c:762:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]

  system_period = DatumGetRangeType(datum);

                ^

versioning.c: In function 'modify_tuple':

versioning.c:880:24: warning: implicit declaration of function 'RangeTypeGetDatum' [-Wimplicit-function-declaration]

  Datum   values[1] = { RangeTypeGetDatum(range) };

                        ^

<builtin>: recipe for target 'versioning.o' failed

make: *** [versioning.o] Error 1

ERROR: command returned 2: make PG_CONFIG=/usr/bin/pg_config all

-----------

And then the server-update.sh gave this following error

--> Giving issue on versioning
--> Giving issue on some configfacade.

**Comment by MartinWahnschaffeSymeda** [comment]
> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/**postgresql/12**/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5 -c -o temporal_tables.o temporal_tables.c

See the bold section - looks very much like you are using postgresql 12. 

This may help you to figure out how to start the correct version: https://serverfault.com/questions/800486/how-to-manage-different-versions-of-postgresql-servers-on-the-same-host
