### ISSUE TITLE
Add passport number and national health id to person [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1639]
### Feature Description
Add two new text fields:

- [x] Passport number
- [x] National health ID (caption: National Health Number/Krankenversicherungsnummer)

**Comment by Iheanacho2027** [comment]
Very important for this ticket, can a variable for nationality be included, this is very important to know if the case is a citizen or a foriegn national

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 This issue is already closed; if you have a change request for it, please open a new issue to make sure that we notice it.

In this case, it's even a completely new feature request since we don't have such a field yet.

I've created this issue for you: #1752
