### ISSUE TITLE
Allow searching for a case and contact at once by UUID or name

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#1640]
### Feature Description
There should be an option to search for both contacts and cases at the same time by using a text field, e.g. for UUID and person name. This should only allow users to search for cases and contacts that they have access to (unlike the already existing feature in the case directory that allows searching for any case in the database).

**Comment by bernardsilenou** [comment]
we should include the SSN when searching a person

**Comment by MateStrysewske** [comment]
Will be done in #2108
