### ISSUE TITLE
Refine the "Home or other place" health facility [5+0]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1641]
### Problem Description
Selecting/viewing "Home or other place" under the headline "Health facility" is confusing to some users.

### Proposed Change
Split "Home or other place" from the facility dropdown, e.g. by adding radio buttons with "home or other place", "health facility" => field name "place of stay" to cases that directly allows users to specify that the case has been notified at home, which would then make it optional to specify a health facility.

**Comment by bernardsilenou** [comment]
Is this already on the way to implementation? more refinement may need to be done

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou This will naturally be implemented alongside the addition of the new facility types. The solution will probably be to add another facility type "Home or other place" and remove "Home or other place" from the explicit lists of facilities. Do you agree with this approach?

**Comment by bernardsilenou** [comment]
> @bernardsilenou This will naturally be implemented alongside the addition of the new facility types. The solution will probably be to add another facility type "Home or other place" and remove "Home or other place" from the explicit lists of facilities. Do you agree with this approach?

Perfect!
