### ISSUE TITLE
Case selection component [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1645]
### Situation Description
The case selection component is needed for #1599 (creating contact from the contacts directory).
~~Our idea is to first implement the component and use if for the existing case ID search #1566.~~

### Feature Description

The component can be created based on the existing duplicate case search component.

- [x] Should have a search field to search for a case by epid number, external ID and UUID (see #1566)
- [x] also allow searching for names
- [x] List all matches and allow the user to pick a case
- [x] Add a button "select case" that opens the case search component to pick a case
- [x] Display name and short UUID of case in contact creation form
- [x] Case search component should filter cases by disease defined for the created contact
- [x] Allow user to remove the association. Likely with a minor styled button
- [x] This also needs to be possible from within an existing contact

### Clarifiy

- [x] Do we need a way to filter by disease, region and district? => only disease, region and district would restrict the users too much
- [x] I guess we need a mockup to have an idea on how the user decided to pick a case or not. Maybe there should be an explicit option "external case or event"

**Comment by MateStrysewskeSym** [comment]
- [ ] Change "No source case selected" to "Please select the source case for this contact if known"
- [ ] Restructure case create form: first name, report date and disease, then case selection, then external ID etc.
- [ ] Automatically do a reload when setting or clearing the cases in the grid
- [ ] Give officers the reassign source case user right
