### ISSUE TITLE
Prevent users from editing cases and contacts outside their jurisdiction (App) [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1647]
### Situation Description
Users are able to see data outside their jurisdiction, e.g. the case of a contact that has been assigned to their jurisdiction. This data should not be editable for them.

### Feature Description
Make user unable to enter the edit activity when the data is not in the jurisdiction of the current user. However, it should still be possible to create contacts for read-only cases.

- [x] add backend method to check whether the user can edit the case or contact
- [x] don't allow the user to open the edit activity
- [x] enforce this when saving a case or contact

(See #1591 and https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/doc/UserDataAccess.md)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] case in app: When moving to the other views the edit button appears again
- [ ] the only exemption should be the list of contacts within the case. Users should still be able to create a new contact even when they don't have access to the case
