### ISSUE TITLE
Contact dashboard refinement to discuss

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1648]
### Proposed Change
# Changes on contact dashboard  #

n = number of of days to follow up for a contact person. Date of last contact with the case is the basis to use, if not available, we can use date of report. 
We can give users the option to choose the date type
* Cantact that are not seen on the nth day of visits should be classified as priority for next visit. (optinal)
* Any contact re-exposed to another case must restart their n days of follow-up from the last date of the most recent exposure.

# Performance indicators from WHO situation report #

* Percentage of contacts being traced daily (goal is to reach 100% of contacts) # (corresponds to under "follow-up" in SORMAS) this is OK
* Percentage of contacts followed for all n days (goal is to reach 100% of contacts) # is this a category of 'completed followed-up' in sormas,
* Percentage of new cases arising from registered contacts (goal 100% of cases) ( this is contact converted to case, we have this in SORMAS,
  Should be calculated as number of contacts persons that become cases/ sum of contacts persons)
* Percentage of cases that had contact tracing implemented within 24 hours of case identification (goal is 100% of cases) (Opotinal)
* Percentage of contacts lost to follow-up (we have this alredy)

# Dashboard changes #
 * Use contact person rather that contact for all indicatiors. 
 * Delete the 'compared to' date field at the top of the page. This stays for the surveillance dashboard.
 * Under followup delete categories saying  coorperative,  unavailable, ... never vidsited
 * Delete dynamic arrosw (<, >; etc) by the side of disase name and at different places
 * Under all contacts delete category "New"
   
 - Replace "Visits" with "Follow-up assesment"
  * The number should represent the expected visit for the time fram set at the top of the page
  * Unavailable, coorperative, uncoorperative,   replaced with <- Follow-up done ( with total and proportion)
 
 * New cases not previously known to be contacts <- Move to the surveillance dashboard and name it "cases previously known to be contacts"
 
 *All contacts
     - Symptomatic is a sub category of confirmed contacts, should we not display it as as a proportion using total number of confirmed contacts as the denomominator?
     - What does new contact mean? Which time frame is used to define them?, suggest we delete it 
 
 * "Stopped followed-up"  replace with <- "Follow up days exceeded"
  -Which time frame is used to determine these contact persons? Are they contact persons that 
   were either converted to case, completed follow up, lost to FU, ot canceled FU within the time frame specified by the user ?
  * Does completed follw up means 1. all visits were done or 2. expected n follow up days have passed ?
  * We can sub categorise completed follocwed-up in  0FU, 2FU, 10FU dFU, d is disease specific, eg 14 for COV
  *Converted to case <- denominator should be number of contact persons not number of cases
  
  Question:
  - If a contact person belong to more than one contact with different contact classifucation, which contact category shound we assign to the person?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Could you please provide mockups for your proposed changes?

**Comment by bernardsilenou** [comment]
Suggested changes to contact nomenclature to be consistent with the dashboard. Open for suggestions please:
Contact status:
  * Delete "dropped"
  * Add 
  - Lost to followup
  - Completed followup
  - Canceled followup (dropped)
  - Overdue followup   (add on dashboard also)
  
validate completed followup with followup until date, ie you can only record completed follow up when there is a visit recorded on the followup until date.

Replace "active contact" with "underflow"

Contacts with a visit on the "followup until" date  will not automatically classified as "dropped" but as "Completed followup". 
Contact with with no last visit on followup until date  condition that the followup until date is in the past of the current date are classified as  "Overdue followup". If visits are latter recorded for this contact, then they become completed follow.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou For three of the four contact status additions you proposed we already have the follow-up status that's part of the contact. This would be pretty redundant.

Also, what is "underflow" supposed to mean?

Most of the logic that you describe is already in the system. The exception is that if a visit is missing on the last day of follow-up, we automatically extend the follow-up duration (i.e. we increase the follow-up until date) and keep the follow-up status as "under follow-up".

All in all, I don't really see a reason for these changes...

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I now understand and agree with you. 
I wish to know what you think about this:
In a contact, when the follow up status is set to "lost to follow up", the contacts i classified as dropped. For example a COVID contact visited for the first week and and could not be found for the second week is classified as "lost to followup" but not "dropped". The lost to followup is then a justification whey the last visit was not done for the contact.

I think  we should also give  users the option to directly choose the contact status as "dropped" which will automatically means 'canceled followup'. eg if the source case is classified as not a case
ie the follow up status should depend on the contact status but not the other way round.

**Comment by MateStrysewskeSym** [comment]
Why can't they just set the follow-up status to canceled and add a comment to explain the situation in the first place then? Going the route of setting it to lost to follow-up only for the system to automatically set it to follow-up canceled immediately afterwards seems a bit unnecessary to me, if I understand you correctly.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Our different points of view is coming from the definition and meaning of the contact status "dropped". 
I define dropped contacts as contacts excluded from the list of all contacts for reasons that made them not to meet the criteria of a contact, eg, if the source case tested negative and classified as not a case, false alert after investigation of the contacts, ..

We currently have the following logic:
Lost to followup => dropped and 
cancelled followup => dropped

What I am suggesting is if we can have the following
dropped => cancelled followup
dropped !=>lost to followup
Lost to followup !=> dropped and 
cancelled followup !=> dropped
 We discuss this on Wednesday further

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The current logic is not coming from us, but was defined by HZI. I agree that we should discuss this on Wednesday.

**Comment by bernardsilenou** [comment]
More comment for tomorrows discussion:

**Comment by bernardsilenou** [comment]
lost to followup and converted to case is possible, thus can’t occur in one category	
contact dropped should not be possible to convert to a case later	
Followup should replace visits, also in the comment	
delete new and symptomatic under all contacts	
new cases not previously known to be contact should be labelled “cases resulting from contacts  and moved to surveillance dashboard”.	

Suggested contact Indicators: each contact should count only in one category

contact status	active
	converted to case
	not converted to case
	discarded/dropped
	
followup status (dropped contacts do not contribute to this count)	under followup
	canceled followup
	lost to followup
	overdue followup
	
contact classification	
    unconfirmed
	confirmed
	not a contact

**Comment by bernardsilenou** [comment]
converted to case ==> cancel follow up with reason converted to case

**Comment by MateStrysewskeSym** [comment]
I've moved your comment to #1855
