### ISSUE TITLE
Add direct archiving to contacts and do not archive active contacts when source case is archived

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#1664]
### Situation Description
Currently, contacts can only be archived indirectly by archiving their source case.

### Feature Description
Since we'll now allow the creation of contacts without a source case, we also need to add a way to archive these contacts. Hence, we need to enable archiving for individual contacts.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym 
- I changed the title to include the addition point that when a case is archive, we should not automatically archive all contacts but only archive contact that are not active.
- When follow up of a contact (or also case and event participant) is not active: we can show a popup to ask if user want ti archive the contact when data is saved

**Comment by kwa20** [comment]
Users also start to experience performance issues with increasing number of contacts.

**Comment by bernardsilenou** [comment]
This issue can be implemented with https://github.com/hzi-braunschweig/SORMAS-Project/issues/6844

**Comment by kwa20** [comment]
@MartinWahnschaffe @MateStrysewske I just translated some strings on crowding in regards to archiving contacts and event participants. I think this was implemented through some data security related issue but I wasn't able to find the exact one. I think this issue can therefore  be discarded

**Comment by MartinWahnschaffe** [comment]
Probably thise one https://github.com/hzi-braunschweig/SORMAS-Project/issues/7249

We still need to do something there, since the button caption has to be adjusted as-well and it has to stay "archived" for infrastructure, so we need to split it there.
