### ISSUE TITLE
Allow filtering contacts by responsible region and district [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1665]
### Situation Description
It's currently only possible to filter by region, district and health facility of the source case.

### Feature Description 
Since contacts can now have a region and a district themselves, users should be given the option to filter by these jurisdictions as well (with a fallback to the source case).

- [x] Use the existing filters for the source case region/district and extend their logic
- [x] Remove the health facility filter from the layout
- [x] add an info icon to explain how the filter is working (see case directory for an example)

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Are you using the health facility of source case filter in the contacts directory? We would like to remove it and focus on region and district of the contact (with source case as fallback).

**Comment by Chinedar** [comment]
Yes please remove it. Most case relevant requirements about the source case
can be sorted via the case directory. Source case as fallback is also good
to have. Thanks.

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove regionUuid and districtUuid from ContactIndexDto
