### ISSUE TITLE
"service payara-sormas start" fails directly after installation

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1666]
### Bug Description
On Ubuntu 18.04 starting the sormas service via "service payara-sormas start"
fails:
![grafik](https://user-images.githubusercontent.com/61463838/77555314-67eedf80-6eb7-11ea-938e-204ce6417a7d.png)
Result of systemctl status:
![grafik](https://user-images.githubusercontent.com/61463838/77555458-89e86200-6eb7-11ea-89ec-589a4962444a.png)

Result of journalctl:
![grafik](https://user-images.githubusercontent.com/61463838/77556189-738ed600-6eb8-11ea-94c4-34cdfe262253.png)

### Steps to Reproduce
1. install sormas server accordung to the installation guide
2.  Call "service payara-sormas start"

### Expected Behavior
The domain comes up

### System Details
* SORMAS version: 1.36.1
* Ubuntu 18.04 Server VM in Hyper-V

**Comment by sgatibaru** [comment]
Also facing the same issue..

**Comment by HolgerReiseVSys** [comment]
Seems to be due to dos-style line endings in the payara-sormas init.d script

**Comment by HolgerReiseVSys** [comment]
Added .sh suffix to prevent the build system from changing line endings
