### ISSUE TITLE
Duplicate entry in dropdown "Education" in "Case Person" - German version

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#1668]
### Bug Description
double entry for "kein Schulabschluss" in German version.
In english version we do not have a duplicate

### Steps to Reproduce
1. open Sormas, Login as surveillance office > GERMAN
2.open a case, switch to "FALL PERSON"
3. open the dropdown for "Bildung"

### Expected Behavior
=> no duplicate is expected

### Screenshots
![Bildschirmfoto 2020-03-26 um 08 49 53](https://user-images.githubusercontent.com/62540178/77623268-19395800-6f40-11ea-9b0b-e84d26dcef2a.png)
![Bildschirmfoto 2020-03-26 um 08 57 10](https://user-images.githubusercontent.com/62540178/77623276-1a6a8500-6f40-11ea-8cc0-e221966ba3cc.png)

### System Details
* Device: Desktop
* SORMAS version:1.36.1
* Android version/Browser: Firefox

**Comment by bernardsilenou** [comment]
I think there in no need to have nursery as a category in the first place. Children do not dropout from nursery education.
- We should merge nursery and primary in one category called "primary or nursery"

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Please consider: https://github.com/hzi-braunschweig/SORMAS-Project/issues/1073#issuecomment-487993646

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda I had a look. Merging no education with nursery is not a good idea.
 We can keep the categories as they are. If we need to simple thins, I will suggest we merge nursery and primary categories in to one. But this is not needed now since we have much to do. Lets do the riight translation and keep things as they are.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Good. Can you let the translators know, please?

**Comment by bernardsilenou** [comment]
I informed them already,
Thanks

**Comment by bernardsilenou** [comment]
Already resolved
