### ISSUE TITLE
Case EPID-Number

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#167]
- [x] add new field EPID-number to case entities and dtos (app+web)
- [x] app case data form: insert field as first element + update mockups
- [x] web case data form: update based on mockups
- [x] add column to web cases list + update mockups

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
When a user creates a new case with the same EPID number which already exists in SORMAS, the system saves the same EPID number and only gives an error field message.... We should restrict duplicate Epid numbers.
