### ISSUE TITLE
Rework server-setup.sh

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1673]
# Situation Description
The setup script is not very resilient at the moment.
E.g. required variables are not enforced and result in errors.
Also a custom jdk cannot be specified.

### Feature Description
The setup experience should be smoother.
The location of the JDK should be configurable.

**Comment by RafaelKluender** [comment]
This script does not work ( and neither does the Dockerfile version). Sorry. It does not access files and folders I clearly have permissions for. 
So far, there is no possible way to install Sormas. What a pity.

**Comment by hzi-old** [comment]
@RafaelKluender We are working on this. Sorry about the issues. You will be able to install SORMAS soon. @fhauptmann @HolgerReiseVSys and team are working on this
