### ISSUE TITLE
Add quarantine information to cases

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1675]
### Situation Description
We need the same information concerning quarantine that we already implemented for contacts for cases as well.

### Feature Description
Add the following fields to the case:

- [x] Quarantine
- [x] Start date
- [x] End date

To be discussed: Does this overlap with the Isolation field from the hospitalization information?

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym is quarantine not the same as the isolation variable we already have? I think adding a date field to determine the end of isolation will address this issue

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou I'd guessed that isolation in a health facility is different from being in quarantine, e.g. at home. But there is definitely some common ground. Something that we have to resolve long-term, I guess.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda I think so also, because when creating a case one can choose home as option for hospitalization and latter choose isolation to yes. We think abut this in future
