### ISSUE TITLE
Contact management & follow-up

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1677]

**Comment by Chinedar** [comment]
Need for admin rights to be able to archive dropped contacts (contacts that have exited follow-up) to free up space in the mobile app and what they can see. This should be part of contact management I suppose.

**Comment by MartinWahnschaffe** [comment]
@VitaliHZI My guess is that this was an old epic/placeholder. Closed
