### ISSUE TITLE
Calculate the follow-up period based on the last contact date

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1679]
To allow proper retrospective data entry and distinguishing between last contact date and report date, we need to make sure that the follow-up period is calculated based on the last contact date if available. The report date should remain as a fallback.

**Comment by bernardsilenou** [comment]
The default WHO date to use is the last contact date. Can we have it optional for user to choose either report date, last contact date  or most relevant date ?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou This date is used in the backend to do calculations, not as a filter or anything like that, so no, we'll always do "most relevant date".

**Comment by MateStrysewskeSym** [comment]
- [ ] Rename allowNullValues to readOnlyWhenNull
- [ ] Add case when readOnlyWhenNull is true and source field value is null
