### ISSUE TITLE
Automatic app upgrade refinement 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1684]
### Bug Description
If the server is unrated to a new version and a user opens the tablet, there is no message to inform the users to upgrade the version on their tablet. 
When a version of the app is installed on a new device, say 1,36,1 without a user account logged in and the server is upgraded to a newer version, say 1,36,2. When the mobile device is latter turn on, it does not upgrade to the new version and prevent the user from logging in.
### Steps to Reproduce
1. Clear from the description of the problem
2.
### Expected Behavior
-When there is a SORMAS  app on a mobile device having internet connectivity and pointing to a server that has a newer version, even is the user does not open the SORMAS app, there should be a pop up message asking the user upgrade, If the user reject this message, they should be reminded after say 3 - 4 hours. A user that does not have case to notify with in a time frame that updates are released may not open the SORMAS app and will miss a lot on new updates.

- If there is an older version of the app on a device with no user account logged in, SORMAS should allow the user to upgrade to the newer version. The date that SORMAS is installed on a device is not always the date that it is used the first time or the date that the user accounts are logged on the devices. Upgrade currently work only when there is a user account logged on the device and cases have been created by the user.
- Users with valid user accounts (name and password as generated from the server before or after upgrading the server) but heaving older versions should be allowed to: either forcefully upgrade before logging in or login to their account on the older app version and latter forced to upgrade. This will depend on the version that is easier to implement,
- Upgrading app aversion to a newer version should not log the user out of app
### System Details
* Device: Android 8 tablet
* SORMAS version: 1,36,1 and 1,36,2
* Android version/Browser: 8

**Comment by vallies** [comment]
can get the latest apk , I am not Able to build apk

**Comment by markusmann-vg** [comment]
will be covered with #6529
