### ISSUE TITLE
The display of "FOLLOWUP VISITS" does not show visits recorded after the expected last date of followup

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1687]
### Feature Description
In a situations were a contact person becomes symptomatic (not a case yet) it is a normal practice to follow up on the contact person after the expected follow up period. These visits do not appear on the follow up visits overview
### Proposed Change
I think visits done after the follow up period should also appear on the overview. What do you think please?
### Possible Alternatives
None

**Comment by MateStrysewskeSym** [comment]
This is basically an extension for #1680
