### ISSUE TITLE
Add a guide for feature configurations [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1689]
Add a guide to this repository that explains how configuring features in the database works right now and which features are available.

**Comment by MartinWahnschaffeSymeda** [comment]
Should be part of a guide to configure a server. Could be the starting point.

**Comment by MartinWahnschaffeSymeda** [comment]
I have added the feature configuration to the server customozation guide:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_CUSTOMIZATION.md#feature-configuration
