### ISSUE TITLE
Add case classification filter to contact directory [0.5]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1706]
-->
### Situation Description
Presently, users are able to add contacts to both suspected cases and confirmed cases. For different countries, case definitions allows for this while others do not. 
### Feature Description
A filter on contact directory allowing users to select between "confirmed cases with contacts" and "suspected cases with contacts" is needed. This feature should also impact what is exported based on filter choice. 
### Possible Alternatives
Restrict for Nigeria, addition of contacts to cases that are not confirmed with lab result? To be discussed further.

**Comment by ChristopherRiedelSymeda** [comment]
Unfortunately I mistyped the ticket number at the commit: #1707

**Comment by ChristopherRiedelSymeda** [comment]
- [ ]find solution for too long captions of filters at least in contact directory
