### ISSUE TITLE
Possibility to search contacts by name while in the contact listing of a case [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1711]
### Feature Description
Often, a case can have about 300 contacts and it is difficult for the CO to search the names of a particular contact on the tablet or Web
### Proposed Change
Just like in the contact listing, add the option to search contacts of a case by name of contact person

**Comment by MartinWahnschaffeSymeda** [comment]
We will start with web UI here. The app is more complicated due to UX.
