### ISSUE TITLE
Use separate columns for first and last name in exports [0]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1713]
### Feature Description
Detailed export of cases and contacts

### Problem Description
The detailed exports currently combine first and last name of the case or contact person into one field. German health facilities need these fields to be separate.

### Proposed Change
Split the column into two columns, one for first name, one for last name.

**Comment by MateStrysewskeSym** [comment]
@Chinedar @faatihi Is this okay for Nigeria and Ghana or would you like to keep it the way it is right now, i.e. with only one column for the full name?

**Comment by Chinedar** [comment]
let's have them on separate columns please. Thanks.
