### ISSUE TITLE
Format dates according to the language

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1714]
### Problem Description
Date fields are currently formatted based on a pre-defined format, e.g. using / as a separator.

### Proposed Change
The format should change based on the language set for the respective user. E.g. in Germany, a dot should be used as a separator instead.

**Comment by StefanKock** [comment]
I will do the review

**Comment by StefanKock** [comment]
I talked with @leventegal-she to rebase his work on current development and make changes to support new language finnish. @ChristopherRiedelSymeda agreed to test the new feature on android app and web app after this ticket is merged.

**Comment by StefanKock** [comment]
Reviewed and merged to development
