### ISSUE TITLE
Import contacts in the contacts directory (optionally without case) [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1716]
### Situation Description
The new feature to create contacts without a case will also be used for people that took part in an event (e.g. returning home from a risk region). Sometimes the SORMAS user will already have access to a list of these people, so it would help a lot to get this into the system easily.

### Feature Description
Add the existing case contacts import to the contacts directory. The logic needs to be adjusted, because we are not importing the contacts of a single case.
Add the external case ID and case/event description fields to the import template here. 

Decide whether and how we are able to (semi-)automatically associate a contact to a case based on the provided case ID (e.g. check UUID, epid number and external id field of cases). 
-> We will start by only using the UUID and create additional issues to extend this later on.

- [x] use the existing import (case contacts) and extend it to have additional fields (disease, disease details, case uuid/external case ID and case/event description

**Comment by ChristopherRiedelSymeda** [comment]
We decided to not display the caze field, because its value the case id is not knowable for the user. Instead we use the caseIdExternalSystem to check if it contains a in the system used case uuid. If that is the case, we connect the contact to the case with the given uuid

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add separate section "Importing contacts for cases" to the guide
- [ ] import template: reorder ContactDto fields to have the most important fields (case, disease, ..) at the beginning and the person with it's many fields at the end
