### ISSUE TITLE
Urgent need for a linelist/spreadsheet view showing all the variables (from case to samples details)  [2]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1721]
### Situation Description
The coordinating team do not have immediate overview of all variables which they have tagged important to see, to ensure that the users in the field are entering all necessary information. They usually have to download to achieve this (the custom export does not also provide all variables to be chosen from). This is a huge challenge at the moment as the dashboard does not provide a lot of information per case/contact.
### Feature Description
Need to have a single view of all variables to be able to monitor real-time which important variables are not being captured by users in the field and to call their attention to it before they return from the filed. This feature should be available for both cases and contacts. 
### Possible Alternatives
We can immediately bring into the case directory all the variables in case, case person, hospitalization, symptoms, epidemiological data, contacts (aggregate count for number of contacts added).  
### Additional Information
We need to also make this single view editable for certain high level user rights (admin for a start) to allow for immediate copying or pasting functionalities as can be done on any spreadsheet. This is a deal breaker right now for the continued use of the system in this outbreak.  
@MartinWahnschaffeSymeda @MateStrysewskeSym @hzi-braunschweig/sormas-docker @danieltomaba 

##### to be reviewed
@BarnaBartha

**Comment by MartinWahnschaffeSymeda** [comment]
Hi @Chinedar Can you provide a complete list of the variables that are needed, please?
Showing them should be doable, but making those editable in a spreadsheet will take multiple days.

**Comment by Iheanacho2027** [comment]
We can have three seperate spreadsheet views

1) Spreadsheet view for case directory with all detailed variables 
2) Spreadsheet view for case contacts directory with all detailed person information variables
3) Spreadsheet view for case contact follow up directory with all detailed follow up variables on availability, temperature and symptoms for daily visits

**Comment by Chinedar** [comment]
Hello @Martin Wahnschaffe <m.wahnschaffe@symeda.de> We can focus on
showing them for now. making them editable can be pushed to the backlog as
we focus on more pressing solutions.

I agree with Henry's points above, we can leave off variables that have
other layers or relationships (e.g, travel history can be replaced with
yes/no to show that this has been captured). If this can be done, it should
come as part of the release, then we can wait for it before the Nigerian
server is updated. Quite urgent...since showing them is doable, this will
help a lot if we can have it. Thanks.

**Comment by Chinedar** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda @bernardsilenou @hzi-old This is still as urgent as the time we asked for it. Can we expedite please?

**Comment by Chinedar** [comment]
The urgent variables to bring to the case directory view and contact directory view;
Case: First name, Last name, Age, Sex, LGA, Address, Phone number, Number of Contacts, Reporting user. 
Contacts: First name, Age, Sex, responsible LGA, Address, Phone number, Source case, follow-up status, reporting user.

We have some of these variables already showing, so please let's bring in for view purposes, the others. @MartinWahnschaffeSymeda

**Comment by bernardsilenou** [comment]
I think we need to decide which king of fihure to use in displaying these variables. Line listing the cases with theses limited variables will not help when there are many cases or contacts in my opinion.
What about the following:

**Comment by markusmann-vg** [comment]
In both categories we will be adding a default view and a detailed view. In the detailed view we add the fields mentioned below for contacts and cases.

Views:
- [ ] Add a selection "Default" & "Detailed" to case directory
- [ ] Add Detailed at contacts (CONTACTS | DETAILS | Followups)

Cases
- [ ] Age / Sex / Address(Street) / Zip / City / Phone / Number of contacts, reporting user

Contacts
- [ ] Split contacts directory "name" to 2 columns "First Name" & Last Name
- [ ] Age / Sex / respo. district / Address(Street) / Zip / City / Phone / source case (linked) / reporting user

**Comment by bernardsilenou** [comment]
@markusmann-vg  beside the variable names, can we also add the completeness proportion? This is for detailed view only

**Comment by markusmann-vg** [comment]
@bernardsilenou What would be the logic behind the completeness? Once we have the logic, what does 100% mean and how the weighting is for this index, we can implement it. Please add another issue for this.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Making this editable in-line will be quite complicated at this point, so we won't address it for now.

**Comment by MartinWahnschaffeSymeda** [comment]
Questions by @leventegal-she 
1. "respo. district" is the district of the contact or address?
-> It's the district of the contact. Not the district of the address. 
@Chinedar Should we have a fallback to the district of the source case, if no specific responsible district is defined here?
2. in what position(s) should these columns be added?
@Chinedar Do you have a suggestion on this? How should the old and new columns for cases and contacts be ordered?

**Comment by bernardsilenou** [comment]
@markusmann-vg :Sorry to reply late. The completeness is good to have because we can only see a max of 20 rows on any line list.
completeness for varX = number of rows with non missing values for varX (yes, no, Unknown)/n *100%
n= number of rows in data corresponding to the specified filter

**Comment by bernardsilenou** [comment]
Follow up issue is #1977

**Comment by leventegal-she** [comment]
@markusmann-vg 

There is a UI glitch with so many buttons on the header: in not English languages the buttons overlap the title.

On a screen of  1440 pixels width it looks like:
<img width="1440" alt="Screenshot 2020-05-07 at 09 21 46" src="https://user-images.githubusercontent.com/62599627/81261757-4a2fa100-9045-11ea-89e0-9701a72ab325.png">
<img width="1359" alt="Screenshot 2020-05-07 at 09 31 59" src="https://user-images.githubusercontent.com/62599627/81261988-aeeafb80-9045-11ea-9b9b-bc57b4b4f67b.png">

**Comment by MartinWahnschaffeSymeda** [comment]
First idea based on discussion: 
Cases: Move the line listing into the ... button.
Contacts: Move the bulk-edit into a new ... button.

@Chinedar @bernardsilenou What do you think?

**Comment by MartinWahnschaffeSymeda** [comment]
@leventegal-she Since we haven't gotten feedback I'd say we should go forward with my two suggestions - that will hopefully be good enough for now.

**Comment by MartinWahnschaffeSymeda** [comment]
![grafik](https://user-images.githubusercontent.com/23217632/81542527-1326fb80-9375-11ea-80d4-064ee5689794.png)

![grafik](https://user-images.githubusercontent.com/23217632/81542541-191cdc80-9375-11ea-9c2e-b7c77ea1f8af.png)

- [ ] also move the import to the "..." button

@Chinedar @bernardsilenou Hope this is ok for you

**Comment by Chinedar** [comment]
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> This should be fine. Assuming
that the "detailed" stands for detailed linelist view? And this is
applicable for case, contact, and samples directory?

**Comment by MartinWahnschaffeSymeda** [comment]
Yes, bu only for cases and contacts, since this was not requested and defined for samples, as far as I know.
