### ISSUE TITLE
App crashes when postponing install of update from 1.36.1 to 1.37.0

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1724]
### Bug Description
App crashes when user wishes to download the latest version but install it later.

### Steps to Reproduce
1. Pre-requiste: User has to be using 1.36.1 version of Sormas android app
2. Open the Sormas app, an alert indicating to download a new version is shown, Click on Download
3. Another alert asking to install is displayed, Click on Cancel
4. Try Reopening the app if the app is closed.

### Expected Behavior
The app should not crash and should ask the user to install to proceed further or only install option must be provided to the user if it is mandatory to update the app.

### Screenshots
![AppCrash](https://user-images.githubusercontent.com/62763628/78249781-31d0e180-74ef-11ea-9f80-9b285270e6f5.jpg)

### System Details
* Device: Samsung Galaxy S 10
* SORMAS version: 1.36.1 updated to 1.37
* Android version/Browser: Android version 10

### Additional Information
Adb logs attached.
[appCrashWhileUpdating.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4421052/appCrashWhileUpdating.txt)

**Comment by Iheanacho2027** [comment]
Same issue occurs for 1.37.1, refuses to install

**Comment by MartinWahnschaffeSymeda** [comment]
Seems to be related to:


java.lang.Long.parseLong (Long.java:590)
java.lang.Long.parseLong (Long.java:632)
de.symeda.sormas.app.backend.config.ConfigProvider.getCurrentAppDownloadId (ConfigProvider.java:572)
de.symeda.sormas.app.util.AppUpdateController.updateApp (AppUpdateController.java:113)
de.symeda.sormas.app.rest.RetroProvider.lambda$connectAsyncHandled$4 (RetroProvider.java:314)
de.symeda.sormas.app.rest.-$$Lambda$RetroProvider$usyBYlBJM5j5ZC1vZL362DwMAj0.accept (Unbekannte Quelle:10)
de.symeda.sormas.app.rest.RetroProvider$1.onPostExecute (RetroProvider.java:371)
de.symeda.sormas.app.rest.RetroProvider$1.onPostExecute (RetroProvider.java:348)
android.os.AsyncTask.finish (AsyncTask.java:695)
android.os.AsyncTask.-wrap1
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:712)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6548)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:857)

**Comment by MartinWahnschaffeSymeda** [comment]
Fixed by #1744
