### ISSUE TITLE
Discrepancy between follow up interval of a contact and the colouring of daily visits

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1728]
### Bug Description
The interval of followup is rightly calculated based on onset date of symptom but the coloring on the followups visits is not.
See image for more details
The button that says "SHOW LAST 8 VISITS UNTIL" should be based on the same date unit used to determine the followup interval. In is currently based on report date,
- Have a look at contact by name Linda LUXENBURG in figure below,
### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/78275591-16c39900-7512-11ea-8b15-a44cc6cfb3a0.png)

### System Details
* Device:
* SORMAS version:1,37,1
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
- [ ] Make sure that the colorization is based on the date of last contact
