### ISSUE TITLE
Filter responsible region and district in case contacts directory

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1730]
There is a need for a filter where users can view case contacts in various nigeria states and LGAs on the case contacts sub-menu @bernardsilenou @MartinWahnschaffeSymeda @MateStrysewskeSym .

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Implement filters in case contacts as in contacts directory (#1665)
