### ISSUE TITLE
Removal of filter on case contacts sub-menu

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1731]
There is a filter on the case contacts sub-menu which says "LGA of source case", that filter is invalid as there is only one source case which comes from one LGA rather than different LGAs, i believe the aim was to include "responsible LGA for contact" as requested in #1730 @bernardsilenou @MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
Will be fixed by #1730
