### ISSUE TITLE
Detailed export for case contacts sub-menu

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1733]
### Problem Description
The export functionality currently on the case contacts sub-menu is a basic export. Detailed export is missing
### Feature Description
1. There should be a detailed export on case contacts sub-menu showing all variables including responsible region and district. 

2. The detailed export of the main contact menu of the SORMAS application should have variables for responsible region and district

@bernardsilenou @SeriousMartin @MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls can this be made part of friday's upcoming release?

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] also inform that the export might take a while
