### ISSUE TITLE
not able to build andoird app 

### ISSUE THREAD

**Issue by vallies** [hzi-braunschweig/SORMAS-Project#1735]
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
Hey! Sorry, but we'll need a lot more information to be able to help you. What exactly happens? Why does it fail? What kind of error messages do you get?

**Comment by StefanKock** [comment]
No response since two months.
