### ISSUE TITLE
Covid-19 as Preview

### ISSUE THREAD

**Issue by jakobschumacher** [hzi-braunschweig/SORMAS-Project#1738]
I am thinking About using Sormas for a german local public Health agency for Covid-19. I'd like to see a versoin to Play around with the Covid-19-variant of the Sormas Software.

**Comment by hzi-old** [comment]
https://sormas.helmholtz-hzi.de/sormas-ui/login

**Comment by MateStrysewskeSym** [comment]
@hzi-old The HZI play server is not configured as a German system and hence doesn't include all the features that @jakobschumacher likely wants to test.

@jakobschumacher I'll get back to you as soon as possible.

**Comment by hzi-old** [comment]
@MateStrysewskeSym @jakobschumacher This is configured as a german system https://musterstadt.sormas-oegd.de/sormas-ui/login. Please use this
