### ISSUE TITLE
Outbreak configuration does not give room to add time period

### ISSUE THREAD

**Issue by Pearl-github01** [hzi-braunschweig/SORMAS-Project#1741]

**Comment by MateStrysewskeSym** [comment]
@Pearl-github01 Thanks for your request. Please actually fill in the issue templates that we provide for any feature or bug requests so that we have enough information to work with.

**Comment by VitaliHZI** [comment]
hey @Pearl-github01 can we close this issue or is it still needed. Please provide some more information. Thanks

**Comment by Pearl-github01** [comment]
> hey @Pearl-github01 can we close this issue or is it still needed. Please provide some more information. Thanks

This issue has been resolved long ago so it can be closed. Thanks
