### ISSUE TITLE
Create custom export for contacts [2]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1748]
### Situation Description
We do not have a custom export feature for the contact data at the moment. This is needed. 
### Feature Description
Activate custom export for contact data to enable users download variables of choice. Need to also make the custom saved template public for other users to use what's already pre-determined. 
### Possible Alternatives
Alternative for now is to do detailed download and then select variables of choice.

**Comment by MateStrysewskeSym** [comment]
I've extracted the part with the publically available exports to #1754 because it's a feature on its own.

**Comment by max-hzi** [comment]
Hi, I wanted to raise attention to this issue again as Berlin has been asking for a customisable export.

**Comment by vidi42** [comment]
For the initial version of the custom export we will include as customizable all the fields which are present in the Contact Detailed Export

**Comment by MateStrysewske** [comment]
Export fails for all exports that don't use export configurations and the associated annotations (such as ExportProperty). Responsible code starts at CsvStreamUtils:155.

**Comment by AndyBakcsy-she** [comment]
Validated the custom export functionality on the latest version of SORMAS Version: 1.54.0-SNAPSHOT on test.sormas.netzlink.com

**Comment by mmarzaganov** [comment]
@MateStrysewske @AndyBakcsy-she @StefanKock

Found a UI bug with the custom export function.

When initially creating a custom export, you end up seeing the following:

![custom export for contacts](https://user-images.githubusercontent.com/77120244/105607450-19dc8e00-5d9f-11eb-9474-5972f01bf0b2.png)

The download button is hardly visible and the remaining functional buttons are completely out of view in the list. However, when reloading the page and re-opening the overview/list, the bug disappears:

![grafik](https://user-images.githubusercontent.com/77120244/105607463-337dd580-5d9f-11eb-85de-a05288dd347b.png)

This UI bug returns again, if one deletes the custom export list, reloads the page and creates another custom export.

**Comment by MateStrysewske** [comment]
@mmarzaganov Hey! Yes, we're aware of that, it also happens for the custom case export. Since we will move to a new UI framework in the future, the bug is related to the UI technology we're using right now and this basically only happens the first time a custom export is created (or, as you've said, when the list is completely emptied), it's something that I would personally see as a pretty low priority right now (unless we get reports that users have serious issues with it of course).

**Comment by mmarzaganov** [comment]
@MateStrysewske Agree. If you already have the issue captured then there is nothing more to do right now.
