### ISSUE TITLE
Add samples to contacts [6+2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1753]
### Situation Description
In the current COVID-19 situation, not only cases, but also contacts are tested for the pathogen. Users need to be able to document this.

### Feature Description
~~Add a new "test result" field to contacts. This could have the values "Not yet tested", "Negative", "Positive" and "Unknown". Make sure to give the field a caption that clarifies that this is meant to reflect the testing status for the disease of the contact case.~~
Full sample module needed. See below.

##### to be reviewed by
@MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
Talked to Juliane about this. HZI needs to define whether a simple "result" field is sufficient here or whether we need something more sofisticated, e.g. creating a sample for a contact.

Also see #1638

**Comment by MateStrysewskeSym** [comment]
@hzi-old @bernardsilenou What's the current status here? I'm not sure, did we agree about contacts needing full samples and pathogen tests?

**Comment by faatihi** [comment]
Lab samples of contacts are being collected for testing but they're not recorded in sormas. 
So we need both samples and pathogen tests, and not only the results.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Yes, contacts need full sample and lab test module just as cases. They also need the reduced version of this, see issue #1638

**Comment by markusmann-vg** [comment]
As in cases, we need the same functionality for contacts

Work breakdown structure:
=> impact on code
=> Define work packages 
=> Implementation

**Comment by markusmann-vg** [comment]
Assumption:
When a contact is converted to a case, the sample are still valid for the case

Consider:
- Impact on case or contact deletion

Web first (App will be treated in a seperate ticket)

**Comment by bernardsilenou** [comment]
Normally, when a case is deleted, all the contacts are deleted. In the meantime; if a contact is converted to a case and the source case is deleted, we will delete the contact but keep the resulting case right?
In addition, when the resulting case is deleted and the sources case and contact is still valid, we deleted only the resulting case, right?
Maybe we can address this issue together with this #1822 
On the contact table, we have the resulting_case_id, i do not know what happens to this id when the case is deleted. Should we add another column on the contact table to tell us if a resulting case is deleted?

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha pointed out that we haven't defined how to change the sample directory and the sample edit view.

Sample directory:

- [ ] introduce a new filter that allows to filter "all samples", "case samples" and "contact samples". This filter can be put next to the "active"/"archived samples" filter on the top right of the grid.
- [ ] The disease and diseaseDetails have to be retrieved from the case OR the contact if not case is associated
- [ ] The region and district need to be taken from the case OR the contact (resonsible region/district) OR the case of the contact (when no responsible region/district) is defined. This is a bit tricky...
- [ ] The disease, region and district filters need to be udpdated accordingly

Sample view:

- [ ] Display information on the contact in the top right. Use contact ID (short), contact person, date of last contact, age, sex
