### ISSUE TITLE
Allow specific users to create public custom exports [2]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#1754]
### Situation Description
There are certain custom case (and later contact) exports that are probably interesting for all users who can use this feature.

### Feature Description
Allow users with specific rights (e.g. national users) to make custom export configurations public. Extend the component that lets users choose which export configuration they want to use to contain two lists, one with their own custom exports, one with those that have been made publically available.

- [ ] New user right "Manage public Export configuration"
- [ ] users with the right "Manage public Export configuration" can
- [ ] set reports to public (true/false)
- [ ] edit/delete the report 
- [ ] 2 lists (my exports / shared exports) => extend component [show only, when there is at least 1 export in a list]

**Comment by ManuelaHa** [comment]
Include variables **(Quarantäne Beginn und Ende**)  for custom export

**Comment by cazacmarin** [comment]
@MateStrysewske - which are the users to whom we should set the "Manage public Export configuration" right ?
Currently I added this right to ADMIN, ADMIN_SUPERVISOR and NATIONAL_USER. But I don't know if they are the `good` users which should have this right.

**Comment by MateStrysewske** [comment]
@cazacmarin I think that's a good start - if we get requests to include other user roles, we can add them, but for now, these seem to be fine to me.

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT
Tested on the local environment

**Comment by AndyBakcsy-she** [comment]
@MateStrysewske and @cazacmarin  This functionality is also available for other users than the ones mentioned in the comments, for example, National Clinician and Surveillance Supervisor also have access. Is there a missing configuration setting that I did not do on my local environment?
