### ISSUE TITLE
Language selection option reappears after entering server details and language in the app

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1756]
### Bug Description
on the mobile app, Language selection option appears twice even after selecting the language during initial server configuration.
### Steps to Reproduce
1. Install the Sormas app on a new device
2. Click on the app to access it and enter the server url details and select English language on the settings screen displayed.
3. Click ok
4. See if login screen is displayed

### Expected Behavior
The language selection option must not re-appear as the user has already selected the language.
Selected language must be saved and user should be redirected to the login screen

### Screenshots
![Language option_Settings screen](https://user-images.githubusercontent.com/62763628/78541869-95605500-77f6-11ea-96d3-537ca425914f.png)

### System Details
* Device: Galaxy S 10
* SORMAS version: 1.37.2 observed on previous versions too
* Android version/Browser: Android 10

**Comment by DavidBaldsiefen** [comment]
I knew this problem from the past, however I cannot reproduce it anymore
