### ISSUE TITLE
Epid number only unique within specific disease

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1758]
### Feature Description
The Epid number auto generated should only flag for duplicates when it is re-used for another case under the same disease.
### Problem Description
The epid numbers are currently flagging as duplicates when the same is in use for a different disease. 
### Proposed Change
The epid number should only be unique within one disease and not across all diseases.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Are you sure about that? We've changed the algorithm to this specific request quite some while ago. Please double-check that this is indeed not working as intended.

**Comment by Chinedar** [comment]
yes so I've checked again carefully and this is the case. A case of
covid-19 with a certain epid number (epid number does not exist for any
other covid-19 case) which is the same for a cholera and a measles case (3
cases of 3 different diseases) keeps flagging as a duplicate.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Okay, thanks! We'll take care of it.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] don't consider deleted cases for epid number calculation and for duplicate check

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove unused year subtraction method
