### ISSUE TITLE
Request time-out seems to crash server

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1759]
### Bug Description
See below.

### Steps to Reproduce
1. Open configruation/developer in web UI and generate 1000 cases
2. The request takes too long and will time-out
3. **No other user can connect to the server now** (e.g. delete browser cookies to try).

In contrast, when you do the following the server does not crash
1. Open configruation/developer in web UI and generate 1000 cases
2. Close the browser window or delete the cookies for the active page and reload
3. You can still connect to the server, even though the process is still running and takes a lot of CPU time.

### Expected Behavior
Even when a request takes a lot of time and a time-out happens, other users should still be able to connect to the server.

### System Details
* Device: PC
* SORMAS version: 1.37.2
* Android version/Browser: Firefox 74.0

### Review
@StefanKock

**Comment by MartinWahnschaffeSymeda** [comment]
@raghupola-vg No need to further test this. We are already working on a solution. 
Would be good to have an automatic UI test for this, though.

**Comment by markusmann-vg** [comment]
### 
Yes, that's why I assigned and discussed it with Raghu :)
He was not supposed to come over with a solution or a direct test but to plan automatic tests for it.

**Comment by HolgerReiseVSys** [comment]
This seems to be due to the long-running blocking the VaadinSession.
Calls from the same browser then gradually block all remaining network listeners.
This already happens with one tab, because ewhen the app looses its connection, it repeatedly tries to reconnect.
At the moment the max size of the http-thread-pool is 5. Setting it much higher may mitigate the issue a bit, but is definately no satisfying solution.

**Comment by MartinWahnschaffeSymeda** [comment]
Workaround:

1. Start asadmin for the sormas domain (make sure to use the correct payara path and port, 6048 is default)
`/opt/payara5/bin/asadmin --port 6048`
2. Adjust the max thread pool size
`set configs.config.server-config.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=500`

**Comment by HolgerReiseVSys** [comment]
When exporting, the download is created in `StreamResource::getStream`.
This method is called by `DownloadStream::getStream` while the `VaadinSession` is locked by `FileDownloader::handleConnectorRequest`.
After the `VaadinSession` is unlocked, `DownloadStream::writeResponse` is called, which uses the `InputStream`  from the `StreamResource`.
If the resource intensive part was postphoned to the read operation on the stream, it could run without the session being locked.
This could e.g. be done by extending `FilterInputStream`.

**Comment by HolgerReiseVSys** [comment]
`DownloadUtil::createCsvExportStreamResource` now only creates the download on the first access to the `InputStream`. At this point the `VaadinSesson` is already unlocked.
This probably also has to be done for other `Resources` as well.
 
In `CasesView` and `ContactsView` a modal dialog is shown when an export is initiated.
This prevents the user from modifying the view, which could result in the download failing.
This is not yet implemented for the custom case export.

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda @HolgerReiseVSys @StefanKock This issue was never moved out of the backlog even though it was being worked on. Is this finished or is more work required?

**Comment by HolgerReiseVSys** [comment]
> @MartinWahnschaffeSymeda @HolgerReiseVSys @StefanKock This issue was never moved out of the backlog even though it was being worked on. Is this finished or is more work required?

@MateStrysewskeSym We have applied the solution to the places that seemed to be most relevant.
I assume that we don't get reports in this regard any more?
When the solution has shown to fix the issues, we should make sure that alle occurances are covered.
As the matter is not intuitive, it would be desirable to have a clean api for downloads so we will not run into this again.

**Comment by MateStrysewskeSym** [comment]
@StefanKock Can you confirm that we're not running into this problem anymore?

**Comment by StefanKock** [comment]
There happen still some exceptions with no clear source or defect (a few once a day):
- `IOException: Connection reset by peer`
- `IOException: Connection is closed: Broken pipe`
- `DownloadStream.tryToCloseStream: NPE`
- `DownloadStream.writeResponse: Write timeout exceeded when trying to flush the data`
