### ISSUE TITLE
Payara domain: Review default values for production domains

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1768]
### Feature Description
The payara comes with two default domains (domain1 and production). As far as I can tell we are currently using the default values based on domain1. 

### Problem Description
Some of these default values may not be a good fit for a production domain (e.g. thread pool size).

### Proposed Change
Check all default values of the production domain to adjust the server setup script accordingly.

### Additional information
https://docs.payara.fish/docs/5.201/documentation/payara-server/production-ready-domain.html

**Comment by StefanKock** [comment]
Switch to Payara `production` template is now part of #2453.
