### ISSUE TITLE
Option to attach document like pdf, word, jpeg to cases and contacts (Web-App UI Part) [3]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1771]
### Situation Description
Often, cases usually have associated documents that are not registered in SORMAS. users need to be able to upload associated documents to cases and to contacts.
### Additional Information
See #3283

Phase 1: Web-App only (!) 
Android App out of scope

### Development Specifications:
- [ ] Add the ability to upload documents to cases and contacts (same logic as for events, see #3283)
  - At least add the following Metadata to each file: ID, Filename, Display Name, Type, Size, Author, Upload Date
  - Allowed Files: jpg, png, doc, docx, pdf, xls, xlsx, dot, dotx 10MB (Maybe add more filetypes, but some files like .exe should not be allowed
- [x] Make sure documents are hidden if the user does not have direct access to the case/contact (based on the jurisdiction and/or whether the user is the reporting user; probably matches whether or not the case/contact is pseudonymized)
- [x] Add a list of documents to the right side of cases/contacts (similar to how it's done for events)

**Comment by max-hzi** [comment]
Hi, I would like to rise attention to this issue again. It seems increasingly important to German health departments.

**Comment by carolinverset** [comment]
@ftavin @xavier-calland @olivierleuci @bernardsilenou 

Same need in France. Users really need to be able to attach external documents, in particular to each **investigated event.**
The french team can work on it, if necessary.

**Comment by JonasCir** [comment]
@bernardsilenou @syntakker also interesting for us, as we could store the templates for the quarantine orders properly on the server :+1:

**Comment by ftavin** [comment]
@bernardsilenou @JonasCir @syntakker @carolinverset @xavier-calland 

I think we should keep the distinction between issue [2328](https://github.com/hzi-braunschweig/SORMAS-Project/issues/2328) which is about the technical ability to store the documents somewhere (db, file system, ...) and this specific issue which is about the functionnal ability to attach documents to contacts and cases via the UI, using the mecanism developped in 2328.

If I understand well, the quarantine templates could use the storage (issue 2328) but are not linked to this issue

**Comment by JonasCir** [comment]
@ftavin Perfectly right! I was not aware of #2328. Thanks for the hint :+1:

**Comment by bernardsilenou** [comment]
@ftavin 
Well understood!

**Comment by kwa20** [comment]
Does this issue need further refinement? I think we could use what has been implemented through #3283 and apply it to cases and contacts, can't we? This is increasingly requested by users.

**Comment by carolinverset** [comment]
@kwa20 For our part, this development has been completed and corresponds to the requests of the French teams.
The only option that we considered adding a little later is the possibility of attaching more generic documents (perhaps in the "about" part)
@ftavin @bernardsilenou do you want add something ? 

Merry Christmas to everyone !

**Comment by JonasCir** [comment]
Over the months, I also received a lot of requests. Since we already have a working implementation for events, I think supporting cases and contacts should be straight forward.

**Comment by bernardsilenou** [comment]
I think we would revisit this ticker in January before deciding who (French or German dev team) does the implementation.
@MartinWahnschaffeSymeda @ftavin Is there further refinement needed in addition to the current implementation of #3283 ?

**Comment by Candice-Louw** [comment]
Additional support as a highly requested item, please!

The existing feature of https://github.com/hzi-braunschweig/SORMAS-Project/issues/3283 is great, after fix of https://github.com/hzi-braunschweig/SORMAS-Project/issues/3738 in v. 1.53 it would be awesome to have this for 1.54 if possible, please (no pressure!).

@carolinverset Merry Christmas to you too! 🎄

**Comment by Candice-Louw** [comment]
@carolinverset @ftavin @bernardsilenou - would the French team be willing/able to implement this feature for Cases and Contacts, too, please?

**Comment by Candice-Louw** [comment]
Additonal question to possibly consider: should a seperate feature configuration be introduced i.e. DOCUMENTS_CASES and DOCUMENTS_CONTACTS to ensure optimal user configurability?

**Comment by Candice-Louw** [comment]
In summary, configurable feature, separately for Cases and Contacts.

For Cases -
DOCUMENTS_CASES

For Contacts -
DOCUMENTS_CONTACTS

Behaviour like that of DOCUMENTS feature config. at Events.

Please update the documentation to reflect these feature names and descriptions too.

**Comment by OrgaLandkreisTuebingen** [comment]
The district of Tübingen would also be very happy about the implementation of this functionality, it is crucial!

**Comment by DavidBaldsiefen** [comment]
In a discussion last week we thought that it might make more sense to attach the documents to Persons, and then show those documents in all cases/contacts of that person. Thoughts? It would propably look best in the UI if the "document directory" would be part of the sidebar of the case/contact/person overview.

@bernardsilenou @Candice-Louw

**Comment by OrgaLandkreisTuebingen** [comment]
A good idea from my point of view. Then you just have to make sure that there are no duplicates of persons. Unfortunately, the detection of duplicates is not very elaborated yet.

@DavidBaldsiefen

**Comment by DavidBaldsiefen** [comment]
> A good idea from my point of view. Then you just have to make sure that there are no duplicates of persons. Unfortunately, the detection of duplicates is not very elaborated yet.

Yes, as far as I know that is being improved. But you still wouldn't loose functionality in comparison to when documents are attached to cases, where files will almost certainly be uploaded multiple times (e.g. if a single person is a case twice)

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - makes sense from a visualisation perspective, yes.

Would different jurisdictions have the right to see all documents uploaded to the person for every case/contact/communication/disease, though?  Right now only COVID is active in DE, but in other countries more diseases are already active.  If more than one disease is registered, different documents may need to be uploaded to these specific disease cases/contacts that are unique in these instances. @JaquM @bernardsilenou - please feel free to give input on this?

Does it make sense to have documents specific for Cases (documents specific to the disease case), Contacts (documents specific to the disease contact) and Persons (general documents for the person) rather? (needing to create a separate issue for the Persons then).

@marko-ilmkreis - please feel free to also share your insights on this, please?

**Comment by JaquM** [comment]
I would prefer to do the documents on the case/contact. A quarantine order does not belong to the person, but to that particular case or contact. If a person is contact ten times, not all certificates should be listed with the person. However, it would be worth discussing whether documents can ALSO be added to the person.

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - please keep this to cases and contacts (configurable individually as for event DOCUMENTS) for this issue, please.

**Comment by Marko-ilmkreis** [comment]
@Candice-Louw @JaquM @DavidBaldsiefen I think its a good idea to have the documents seperated for every contact/case of a person. So its not confusing the employees. But it would be very good to have all documents which are belongs to a person at the person directory.

The rights management must be in place for this as well. So if I don't have the right to see the desease generally or the case is not in my juristdiction I should not have the right to see the documents either. If the case/contact is pseudonomized I the user should only see there are documents, but not the title either, because in this can be the name or other details.

**Comment by DavidBaldsiefen** [comment]
## To sum this up:

- [ ] Add the ability to upload documents to cases and contacts, as done in #3283
  - At least add the following Metadata to each file: ID, Filename, Display Name, Type, Size, Author, Upload Date
  - Allowed Files: jpg, png, doc, docx, pdf, 10MB (Maybe add more filetypes, but some files like .exe should not be allowed
- [ ] Make sure documents are hidden if the case/contact is not in the current users jurisdiction
- [ ] The Document-UI should be placed on the right sidebar for the cases/contacts

In Addition, but maybe in another Issue:

- [ ] Add the document view to the person UI and show all documents attached to each related case/contact here.
- [ ] Make sure documents for related cases which are not in the users jurisdiction are hidden / anonymized + disabled

**Comment by Marko-ilmkreis** [comment]
@DavidBaldsiefen great. Thanks. Could you add the document type xls, xlsx (sometime we get these documents from schools and so on) and maybe dot, dotx as well. The last one might be very rare.

**Comment by Marko-ilmkreis** [comment]
> In Addition, but maybe in another Issue:
>     * Add the document view to the person UI and show all documents attached to each related case/contact here.

I would suggest to have the documents for the person not to have on the right side. It might be a long list in future, specially for people working in clusters (schools, child day care, retirement homes). I would prefere a new "tab" for that:

![grafik](https://user-images.githubusercontent.com/74791118/111435411-0eec0d00-8701-11eb-891e-fb747b87dcd7.png)

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen Would your summary address this point:
We also make documents available if the jurisdiction of user is not that of the entity but the user is the reporting user of the document. This can happen when a case is later shared to another jurisdiction, the reporting user in the jurisdiction that shared the case with associated documents should have full access to the documents while other users should have read access only.

**Comment by DavidBaldsiefen** [comment]
> We also make documents available if the jurisdiction of user is not that of the entity but the user is the reporting user of the document. This can happen when a case is later shared to another jurisdiction, the reporting user in the jurisdiction that shared the case with associated documents should have full access to the documents while other users should have read access only.

I am not sure. If I recall correctly, currently if you create a case outside of your jurisdiction you will immediately lose all access, and I would follow the same scheme here. Also, why do you think only the user who uploaded a document should be able to edit (or delete) a document?

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen 
This statement "If I recall correctly, currently if you create a case outside of your jurisdiction you will immediately lose all access,"
I think is not the best solution, I though this was changed.
- The point is that each case has a responsible jurisdiction and a reporting user.
- The restrictions on jurisdiction does not apply to the reporting user. Users are allowed to create a case outside their jurisdiction (similar to transfer ownership), When this happen, the reporting user should have full/ read access to the case while other users in the jurisdiction of the reporting user can have pseudonimized or better still not access to the case.
- So the reporting user of an entity always have full access or read access (in case jurisdiction of entity is different)
- I think we need to hear from @MateStrysewske @MartinWahnschaffe  also.

- About full access to document:
     a. All users in the jurisdiction of the entity having the document   AND
     b. Reporting user of the document ( A user in district A can create a case, attach a wrong or incomplete document and share the case to another district B, this reporting user of the document should then be able to modify it even if the case was shared)

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen  If point b add more complexity in the validation, then maybe we can drop it. @kwa20 @JaquM  what to you think pls?

**Comment by kwa20** [comment]
> So the reporting user of an entity always have full access or read access (in case jurisdiction of entity is different)

This is the current implementation. The only thing users have to be aware of is to filter the directories by including entities from other jurisdictions. Otherwise, reporting users have full access to entities they've created outside of their jurisdiction.

@bernardsilenou I also agree with the other points.

**Comment by DavidBaldsiefen** [comment]
Ok I've updated the description

**Comment by Candice-Louw** [comment]
@DavidBaldsiefen - do you require additional information, or could you confirm that you have all the information you need to proceed with implementation, please?

**Comment by DavidBaldsiefen** [comment]
> @DavidBaldsiefen - do you require additional information, or could you confirm that you have all the information you need to proceed with implementation, please?

I think for now that's all the info we need, but I do not know for when this feature is planned (I hope 1.59)

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Things that are a bit unclear to me/I'd like to verify

* What exactly is "Display name" supposed to store as opposed to file name?
* Am I correct that we'll need to extend the Document entity with the metadata information that is currently missing there?

**Comment by Marko-ilmkreis** [comment]
> @DavidBaldsiefen Things that are a bit unclear to me/I'd like to verify
> 
> * What exactly is "Display name" supposed to store as opposed to file name?


This should the name the file is displayed in the list. Sometimes it might be possible that the file should not saved under the filename. 

Maybe there is a logic, which adopts the file name for display name, but the user can change it.

**Comment by DavidBaldsiefen** [comment]
>     * What exactly is "Display name" supposed to store as opposed to file name?

As said above, it would be nice to attach custom names to documents which are more descriptive than the document-title. I don't think this is a top priority though

>     * Am I correct that we'll need to extend the Document entity with the metadata information that is currently missing there?

I didn't look into the technical part yet, but I would suppose so. In any case we should make most of the metadata optional, so that it doesn't interfere in other processes.

Do you know why this is in the interactions sprint board as opposed to application?

**Comment by JonasCir** [comment]
There is some progress made by the French team with attaching arbitrary files to events. Reusing the same logic for cases and events should be possible without the need to reinvent the wheel https://github.com/hzi-braunschweig/SORMAS-Project/pull/4616

Once the mentioned PR is closed I would like to give this a shot

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on local environment
