### ISSUE TITLE
Split address details into multiple fields in exports

### ISSUE THREAD

**Issue by ManuelaHa** [hzi-braunschweig/SORMAS-Project#1774]

**Comment by markusmann-vg** [comment]
Seems like an extension for:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/1713 
picked by @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] CaseExportDto: split address export data to region, district, "address" (street), city and postalCode.
- [ ] Same for the ContactExportDto

For both DTOs we should no longer have a separate query for the address and instead directly query the needed fields into the constructor.
