### ISSUE TITLE
Cannot import Health facilities or Communities

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#1783]
### Bug Description
When using CSV files to import Health Facilities or Communities, nothing gets imported. Btw. the algorithm treats the table header (name, type,...) as an error. Import only works without the first line. 
And even then, I get a message "Success" but 0 imported and no new entries show up, no matter who complete or incomplete the CSV file is. 
### Steps to Reproduce
1. Click on import, upload a template CSV one single entry with header
2. Error message 
3. Click on import, upload a template CSV with one single entry without the header 
4. Success message, but nothing imported

### Expected Behavior
It should import the CSV file
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by RafaelKluender** [comment]
Here is an error message, that, btw. is not shown entirely on the screen. If you want to read it, you have to press CTRL-A and copy it in an editor: 

The column "CMS Naki Est,Savanes,Kpendjal,Naki Est,Naki Est,10.7179446,0.3598093,Laboratory,true,false,10002" is not part of the imported data type or one of its connected entities. Please remove it fro

**Comment by RafaelKluender** [comment]
here is a screenshot of a "successfull" import
![image](https://user-images.githubusercontent.com/60870770/78888612-461e5c80-7a62-11ea-8b73-31046a60baa4.png)

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Seems like the configuration of your server and your local system don't match. The sormas.properties file needs to be adjusted to the standard CSV separator of the language you're mainly using on your systems. For example, for German systems, that's a ";", for most others, it's a ",". You can resolve this manually by replacing all occurences of "," with ";" in your CSV file before importing it.

Also, the header line is absolutely mandatory for the import. It won't work without it.

**Comment by RafaelKluender** [comment]
Thanks a lot. 
Could you point to where the Sormas.properties files is? I have used docker to run Sormas and did not find such a file on the server.

**Comment by MateStrysewskeSym** [comment]
@fhauptmann Could you assist here I haven't looked into the Docker configuration yet.

**Comment by licks0re** [comment]
@RafaelKluender 

Change the value of the .env file which is at the root of your docker files:

`SEPARATOR=\;`

**Comment by RafaelKluender** [comment]
Now, this did not solve the problem. 
Now at least, I can import some communities. The error for the most of them is that the district name for the communities is not unique. 
Well obviously! There are several communities in one district. 
I guess there is some problem with encoding? 
Also, when you leave a space after a name, it won't work. 
I mean, then the district is saved ad "DISTRICT" 
And you try to import a community that belongs to "DISTRICT "  then it won't work. 

It is all way to fragile guys.

**Comment by RafaelKluender** [comment]
Actually, only communities that belong to a district with a name with special characters like é, à, ô 
WORK. 
As soon as the district has NO special characters, then it does not work. Wow.

**Comment by RafaelKluender** [comment]
And the duplicate feature does not work at all. Not in one single case.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender I'd prefer to keep this an esteeming conversation, please.

The problem with the spaces before or after the infrastructure name has already been solved in the latest release. This has probably not yet been deployed on the server you're working on.

The message "community name is not unique", "district name is not unique" etc. means that the database contains more than one community with the same name in the same district, or more than one district with the same name in the same region. In such a situation, the importer doesn't know (and can't know) which community, district or region to import into and therefore rejects the import. You'll have to check the database for infrastructure data with duplicate names and also include the archived infrastructure data. Duplicates within the same parent jurisdiction (so, e.g. facilities within communities, communities within districts, districts within regions) need to be deleted from the database. 

The duplicate detection during the import works absolutely fine for me.

Could you send us the error report files for the imports that failed for you, please? The more information we get, the more support we can provide.

**Comment by RafaelKluender** [comment]
> 
> 
> @RafaelKluender I'd prefer to keep this an esteeming conversation, please.
> 
> The problem with the spaces before or after the infrastructure name has already been solved in the latest release. This has probably not yet been deployed on the server you're working on.
> 
> The message "community name is not unique", "district name is not unique" etc. means that the database contains more than one community with the same name in the same district, or more than one district with the same name in the same region. In such a situation, the importer doesn't know (and can't know) which community, district or region to import into and therefore rejects the import. You'll have to check the database for infrastructure data with duplicate names and also include the archived infrastructure data. Duplicates within the same parent jurisdiction (so, e.g. facilities within communities, communities within districts, districts within regions) need to be deleted from the database.
> 
> The duplicate detection during the import works absolutely fine for me.
> 
> Could you send us the error report files for the imports that failed for you, please? The more information we get, the more support we can provide.

Thank you for you help, I really appreciate. 
Well it is depressing because I have issues with every step, no matter how easy it is. 
The Sormas installation failed and I am running a docker. I would not dare to run the installation script again, it would probably break the version I have. 

Btw. there was another issue: the whitespaces in the csv files, those that supposed to be removed, were differently encoded, it was not a common whitespace, I had to replace them with a "normal" whitespace. I'll add a small csv file, so you can see it. 
Btw. Sormas cannot import the csv files that it exported. I would assume that during export the correct format is conserved. 

So I have to delete those double entries via command line, because it would not be save to have this feature in the GUI. Alright, thank you. 
The next issue: I cannot find the database. 
1. According to .env file, the user is "sormas_user" and the database is "sormas", but both seem to not exist, I had to use the user "postgres" that had no password, so that had to be configured as well.
2. I had to install postgresql-client and posgresql in order to be able to log into postgresql
3. I had to edit the /etc/postgresql/10/main/pg_hba.conf to be able to login locally
4 Once connected, there was no sormas database, so no way to run the script
5. Version 10 is the only postgresql version installed 
I have spent several days scraping the web for an entire list of health facilities of the country I would like to set up, and now I cannot import.

**Comment by RafaelKluender** [comment]
So github does not support csv files, so I renamed it to .txt
[sormas_import_community_template(4).txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4508762/sormas_import_community_template.4.txt)

**Comment by RafaelKluender** [comment]
And this is the error file, once again renamed into txt: 
[sormas_import_error_report.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4508769/sormas_import_error_report.txt)

**Comment by RafaelKluender** [comment]
If you correct the spaces, you will get the "duplicate" error. 
If you cannot remove entries via GUI, the import feature should not take into account "archived" entries. To me it makes no sense that someone adds information to an archived entry. 

Anyway, then I get this error on a regular basis, although there is nothing wrong with the delimiter: 
The column "﻿name" is not part of the imported data type or one of its connected entities. Please r...

**Comment by RafaelKluender** [comment]
Once I copy paste around, I get an error message, about duplicates. 
[sormas_import_error_report.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4508827/sormas_import_error_report.txt)

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Which version of SORMAS are you running?

As I understand it, you're using Docker to run SORMAS; I hope that @fhauptmann and @HolgerReiseVSys could assist you with the problems you're having. If you're not using Docker, please make sure that you perform every step exactly as described in our server setup guide.

I'll add an issue to not take into account archived infrastructure data during the import. I think it makes sense. We'll do this in the current sprint, so the next SORMAS version will contain this change.

If you have another error report file with the "The column [...] is not part of the imported data type", please attach it here as well.

**Comment by RafaelKluender** [comment]
Seems like the best way is to give the "standard" installation script a try. But it failed constantly a month ago when I tried. 
Is the database structure in the docker version different? Or why do I have no sormas user, etc.? 

There are no error reports with the "... is not part of the imported data type..." because the import does not even begin. No error reports get generated.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender We made some improvements to the script since then, chances are that it's going to run smoother now.

The database structure should be the same, I don't know exactly though. I'm no Docker expert, unfortunately.

Ah, I see - sorry, I forgot about that. Please send me a file that gets rejected then.

**Comment by RafaelKluender** [comment]
I'll give the installation script a shot on a fresh server. 

Dear Maté, please find a file that generates the mentioned error. 
[sormas_import_community_template-2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4509351/sormas_import_community_template-2.txt)

**Comment by RafaelKluender** [comment]
You can try for yourself on my testserver here: 
89.145.162.103/sormas-ui/login

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender I don't have any problems with that file (although I had to change the separators from , to ; on my system); what happens on your system if you do the same?

Your test server seems to be inaccessible for me.

**Comment by RafaelKluender** [comment]
When I change the delimiter to ';' I get the same error. In my '.env' file the delimiter is set to ',' 
(Docker version)
Strange that you cannot access the server: 
https://89.145.162.103/sormas-ui/#!configuration/communities
I have no SSL certificate so you must add a security exception for it to work. 

I think, I will try to run the installation script. It seems that some things don't work on the docker and there is also less support.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender For now, that's true; we've only started to use Docker very recently, especially if you run a server for testing purposes, it's probably safer to do it in the traditional way for now.
