### ISSUE TITLE
Translation of SORMAS into Spanish Ecuador

### ISSUE THREAD

**Issue by JoynalFrametOlimpo** [hzi-braunschweig/SORMAS-Project#1786]
### Situation Description
Currently SORMAS has several languages, but does not support the Spanish language

### Feature Description
Allow Spanish translation

### Possible Alternatives
Use the information provided on the crowdin platform

### Additional Information
Using the crowdin platform, they provided the translation in Spanish, Ecuador. Currently there is 84% ​​and a good advance in the web platform

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda Hi Martin, I created the new language Spanish-Equador on crowdin and it is now 84% completed with the properties file 99% completed. Please kindly include this into the list of languages in SORMAS. Thanks @JoynalFrametOlimpo

**Comment by StefanKock** [comment]
This breaks currently the build:
> [INFO] Build
> Task :app:mergeDebugResources FAILED
/srv/dockerdata/jenkins_new/workspace/sormas-Build/sormas-app/app/src/main/res/values-es_ec: Resource and asset merger: Invalid resource directory name

Problable solution: Use another variable in crowdin.yml:
`translation: '/sormas-app/app/src/main/res/values-%two_letters_code%/%original_file_name%'`
See in https://github.com/crowdin/crowdin-cli-v1/issues/69

@MateStrysewskeSym will fix this soon.
