### ISSUE TITLE
Statistics section in Nigerian server not working

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1788]
### Bug Description
When you go to statistics and load up all the requested variabkles by person, place and time, and hit the generate button, there is an error pop up
### Steps to Reproduce
1. select all variables by person, place and time
2. hit the  generate button error pop up

### Expected Behavior
Should generate table, map or chart
### Screenshots
![image](https://user-images.githubusercontent.com/19344651/78996240-776f5900-7b44-11ea-8e10-22c04af9acaa.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by Iheanacho2027** [comment]
Gender and age group are the affected attributes

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Could you please send me a full screenshot with ALL filters and the groupings so I can reproduce it on my local system?

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Nevermind, already reproduced it.

**Comment by StefanKock** [comment]
Already released, code review: deleted old code in comment since it is active again.
unit test  would have been nice
