### ISSUE TITLE
Bug in duplicate detection

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1789]
### Bug Description
An Epid number shows as a duplicate eventhough it exists for only one case in the case directory

<img width="363" alt="epid bug" src="https://user-images.githubusercontent.com/50739609/79007528-2e051680-7b10-11ea-8b44-bf70aa57e4b5.PNG">

**Comment by Iheanacho2027** [comment]
@bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Are you sure that there's no archived case with the same epid number?

**Comment by MartinWahnschaffeSymeda** [comment]
See #1758
