### ISSUE TITLE
Add "Direct contact with a probable or confirmed case" to detailed export

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1790]
### Bug Description
The variable "direct contact with a confirmed case" comes out empty when detailed export is done, even though data is sufficiently captured for this variable by users. 
### Steps to Reproduce
1. Download the detailed export for case and verify that this column is empty.
2.

### Expected Behavior
All forms of export should return responses already captured for this variable.
### System Details
* Device:
* SORMAS version: 1.37.2
* Android version/Browser: browser

**Comment by MateStrysewskeSym** [comment]
@Chinedar That's not a bug. The field used for COVID-19 is not "Direct contact with a confirmed case" but "Direct contact with a probable or confirmed case", which is not part of the detailed export yet.
