### ISSUE TITLE
Pre Follow-up symptom and temperature information for case contacts

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1793]
### Situation Description
Before contact daily follow-up and monitoring begins, the symptoms and temperature of the contact are always collected on identification and listing. There is no provision for this on the SORMAS platform
### Feature Description
There should be a sub-menu for temperature and symptoms information on identification of contact under the case contacts sub-menu.  @Chinedar @bernardsilenou @hzi-old. This feature request can be added to the product backlog 
### Additional Information

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Just to help me understand - shouldn't contacts that are symptomatic be turned into cases anyway?

**Comment by Chinedar** [comment]
@Henry Henry <iheanachodenwigwe@gmail.com> Once you identify a contact,
collect temperature and check for symptoms, you should have already
line-listed the contact and so this becomes the first "follow-up visit" for
that contact. We might not need to pre follow-up the contacts, except you
are referring to being able to pro-actively line-list the contacts even the
case is yet to be confirmed??

**Comment by Chinedar** [comment]
For the COVID-19 situation, I have observed from the contact identification
form, that they collect symptoms and temperature during idenfication and
listing, which are separate from the ones collected during the 14days
follow up visit. Probably we need more confirmation

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym yes they should be, but follow up is for contacts that are asymptomatic. After due consultation, i believe this request is unnecessary and i agree with @Chinedar. Lets focus on more important requests
