### ISSUE TITLE
Arrow of Drop-Down menue overlaps with Filter-description in "Statistics" 

### ISSUE THREAD

**Issue by Mimsel** [hzi-braunschweig/SORMAS-Project#1795]
### Bug Description

Arrow of Drop-Down menue overlaps with filter-description in "Statistics"

### Steps to Reproduce
1.  Open SORMAS in german version
2.  In Statistik: Add filter "Verlauf der Erkrankung" 

### Expected Behavior
Arrow by the end of the text, not within

### Screenshots
![image](https://user-images.githubusercontent.com/63415956/79204089-493b9300-7e3c-11ea-83d3-da05a7bf58f9.png)

### System Details
* Device:
* SORMAS version: 1.37.1
* Android version/Browser:

**Comment by DavidBaldsiefen** [comment]
This has strong overlap with #2610 , which will be closed in favor of this
