### ISSUE TITLE
External ID disappears when saving a district

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#1796]
### Bug Description
I imported district data. When I change the data of one district under settings -> districts the external ID disappears
### Steps to Reproduce
1. Import district data with external ID
2. Got to settings -> districts
3. Double click one district -> a popup window appears
4. Click on save
5. The external ID of the district is gone

### Expected Behavior
External ID isn't deleted

**Comment by ChristopherRiedelSymeda** [comment]
Was already fixed by #1850
