### ISSUE TITLE
SORMAS license [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#182]
We need to define the license for SORMAS.

- [x] collect all used libraries
- [x] collect license information for all used libraries and other dependencies
- [x] check copied vaadin highcharts addon  -add source link and needed info

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Any updates on this?

**Comment by MartinWahnschaffeSymeda** [comment]
Used libraries, frameworks and technologies - Server side
--------
Payara / Java EE (Server): CDDL 1.1 or CDDL and GPLv2 + the Classpath exception
JUnit (Testing): EPL 1.0
Hamcrest (Testing): BSD
Mockito (Testing): MIT
Postgres (Database): Postgres 
Eclipselink (Database): EPL v1.0 or EDL v1.0
slf4j (Logging): MIT
jcl-over-slf4j (Logging): MIT
jul-to-slf4j (Logging): MIT
slf4j-log4j (Logging): MIT
logback (Logging): EPL v1.0 or LGPL 2.1
Joda time: Apache 2
Vaadin (UI): Apache 2
Highcharts (Charting): CC BY-NC 3.0
Highcharts for Vaadin 7 addon: Apache 2
googlemaps (Maps): Google Maps Terms of Service (https://developers.google.com/maps/terms)
Vaadin googlemaps addon (Maps): Apache 2
Jersey (Rest): CDDL 1.1 or GLPv2

Used libraries, frameworks and technologies - App side
--------
Android: Apache 2, parts in GPLv2
ORM lite (Database): ISC
Retrofit2 (Rest): Apache 2
Google firebase analytics: https://firebase.google.com/terms/analytics
Google analytics: https://www.google.com/analytics/terms/us.html
Google code open beans: Apache 2

Licenses
-----
Apache 2: https://opensource.org/licenses/Apache-2.0
BSD 3: https://opensource.org/licenses/BSD-3-Clause
CC BY-NC 3.0 - Creative Commons Attribution-NonCommercial 3.0 Unported: https://creativecommons.org/licenses/by-nc/3.0/
CDDL 1 - Common Development and Distribution License: https://opensource.org/licenses/CDDL-1.0
EPL 1 - Eclipse Public License: https://opensource.org/licenses/EPL-1.0
EDL 1 - Eclipse Distribution License: http://www.eclipse.org/org/documents/edl-v10.php
GPL 2 - GNU General Public License:  https://opensource.org/licenses/GPL-2.0
ISC: https://opensource.org/licenses/ISC
LGPL 2.1 - GNU Lesser General Public License: https://opensource.org/licenses/LGPL-2.1
MIT: https://opensource.org/licenses/MIT
Postgres (similar to BSD or MIT): https://www.postgresql.org/about/licence/

**Comment by MartinWahnschaffeSymeda** [comment]
This is a good summary of typical licenses: https://choosealicense.com/licenses/

**Comment by MartinWahnschaffeSymeda** [comment]
Daniel and I prefer MPL:


Permissions | Conditions | Limitations
-- | -- | --
Commercial use                                                                                                                                                                  Distribution                                                                                                                                                                  Modification                                                                                                                                                                  Patent use                                                                                                                                                                  Private use | Disclose source                                                                                                                                                                  License and copyright notice                                                                                                                                                                                                                                                                                Same license (file) | Liability                                                                                                                                                                                                                         Trademark use                                                                                                                                                                  Warranty

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] check if there are any possible problems with MPL
- [ ] add the license file (see also https://help.github.com/articles/licensing-a-repository/#disclaimer)
- [ ] remove creative commons info

**Comment by MartinWahnschaffeSymeda** [comment]
After some internet research I couldn't find big pitfalls for the usage of the MPL. I think we should go for it.

**Comment by MartinWahnschaffeSymeda** [comment]
We (Ascenion, Elektro-Datentechnik, HZI, Symeda) decided to go with GPLv3 instead of MPL, because:

* it's more common
* if we allowed people any form of linking, it should better be dynamic linking (e.g. of the API) -> LGPL
* right now there seems to be no need to allow using SORMAS source code to be used in propietary software (server side not included) -> GPLv3

- [ ] Important: If we want to be able to pu part of SORMAS under LGPL long-term, we have to declare this in our contributor guidelines!

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig We need your legal department to send us a copyright notice that we have to include in every file alongside the license notice.

**Comment by MateStrysewskeSym** [comment]
- [ ] add explanation how copyright can be added to source files
