### ISSUE TITLE
Reviews the logic about what happens to the resultingcase_id of a contact when the resulting case id latter deleted

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1822]
### Situation Description
When a contact is converted to a case and the case is latter deleted, the resulting case id on the contact table marked as deleted.
### Possible Alternatives
none

**Comment by VitaliHZI** [comment]
@bernardsilenou is it still needed? I think than we need to describe this issue more in detail.

**Comment by bernardsilenou** [comment]
@VitaliHZI  This issue is  still important to address but it is a duplicate of #4353; I will close this one
