### ISSUE TITLE
Add quarantine status in detail export sheets of contacts and cases [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1823]
### Situation Description
Add the newly added fields to to the details export of contacts.
- Quarantine
- Priority
- Category type
- means quarantine communication
- if help id needed

Quarantine for cases will constituted cases isolated at home using the newly introduced hospitalization variable

**Comment by max-hzi** [comment]
Hi, just a quick question: Will these infos become availible in the customisable export window/ new export configuration?

**Comment by MateStrysewskeSym** [comment]
@max-hzi Good point. We'll make sure to add it there as well!

- [ ] Add the quarantine information to the custom export:

* Add static QUARANTINE_INFORMATION string to CaseExportDto
* Add the annotation @ExportProperty(value = QUARANTINE_INFORMATION, combined = true) to all fields in CaseExportDto that involve quarantine
* Make sure that the custom export form is automatically extended accordingly and test the new export option

**Comment by leventegal-she** [comment]
Header labels in the CSV file needs to be fixed

**Comment by MartinWahnschaffeSymeda** [comment]
@leventegal-she Looks like the @ExportProperty(value = QUARANTINE_INFORMATION, combined = true) is not working correctly here. Instead of three fields it should just have been a single one. Can you have a look at this, please?
