### ISSUE TITLE
Adapt the Case management module (therapy and clinical course) for COVID-19 [2]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1824]
-->
### Feature Description
The attached form, is a bit modified from what we have implemented for Lassa Fever case management (therapy and clinical course tabs). This reduces the cycle requests throughout the admission of patient. Focuses on data collected on admission, management strategy, and discharge details. 
###attached form
[COVID_CASEMGT_FORMS_updated12042020.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4483689/COVID_CASEMGT_FORMS_updated12042020.docx)

##### to be reviewed by
@MartinWahnschaffeSymeda

**Comment by bernardsilenou** [comment]
Here are the changes to do:

### Pre-existing conditions 
* Add
  - Obesity   
  - Current smoker 
  - Former smoker  
  - Chronic lung disease  
  - Asthma    
  - Sickle cell disease 

#### Symptoms
* Add 
  - Wheezing
  - Skin rashes
  - Skin ulcers
  - Inability to walk
  - Bleeding
  - Lymphadenopathy
  - Lost/reduced sense of smell
  - Lost/reduced sense of taste
  - In-drawing of chest wall
  - Cough with sputum
  - Cough with heamoptysis
  
* Remove
  - Rapid breathing
  - cough
  - Malaise
  - Excitation or irrtability
  - Pharyngeal exudate
  
* Relabel
  - "Cinjunctival injection" with "Conjunctivitis"
  -  "Coma" with "Coma/Somnolence"
  
## Complicatinons 
  - Add other complications followed by a text field as in symptoms

**Comment by markusmann-vg** [comment]
**Assumption:** 
Removal of the symptoms will just be removed from the list (frontend) but not the db
No data needs to be migrated

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Just to make sure: The pre-existing conditions are only visible for clinicians, correct?

**Comment by BarnaBartha** [comment]
@bernardsilenou 
For pre-existing conditions:
- "Chronic lung disease" -> we already have "Chronic pulmonary disease", should we rename this or is this a separate one?

For the new symptoms:
- Bleeding -> there are several types, should we use unexplained bleeding?
- Lymphadenopathy -> there are several types Inguinal/Axillary/Cervical which one should be used, or should we add a new one ?

**Comment by bernardsilenou** [comment]
@BarnaBartha 
Maintain only Chronic pulmonary disease please, it was an error

> * Bleeding -> there are several types, should we use unexplained bleeding? Yes please
> * Lymphadenopathy -> there are several types Inguinal/Axillary/Cervical which one should be used, or should we add a new one ? Just add a new one called "Lymphadenopathy", WHO did not specify which type.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  Yes please, I think not only pre-existing conditions but the whole clinical course tab, right?

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Correct

**Comment by BarnaBartha** [comment]
Summary of changes done within this issue:

Pre-existing conditions
Add

	Obesity					- was missing	-> added
	Current smoker			- was missing	-> added
	Former smoker			- was missing	-> added
	Chronic lung disease	        - was missing	-> used chronicPulmonaryDisease		
	Asthma					- was missing	-> added
	Sickle cell disease		         - was missing	-> added	

Symptoms
Add

	Wheezing						- was missing 						    -> added
	Skin rashes						- was present w/o link to Coronavirus   -> added
	Skin ulcers						- was missing					        -> added
	Inability to walk				- was missing					        -> added
	Bleeding						- was present in other forms			-> used unexplained bleeding
	Lymphadenopathy					- was present in other forms			-> added new field Lymphadenopathy
	Lost/reduced sense of smell		- was present
	Lost/reduced sense of taste		- was present
	In-drawing of chest wall		- was missing							-> added
	Cough with sputum				- was missing							-> added
	Cough with heamoptysis			- was missing							-> added


Remove

	Rapid breathing 				- was present	-> removed linking to Coronavirus
	Cough							- was present	-> removed linking to Coronavirus
	Malaise							- was present	-> removed linking to Coronavirus
	Excitation or irrtability		- was present 	-> removed linking to Coronavirus
	Pharyngeal exudate				- was present	-> removed linking to Coronavirus

Relabel

"Cinjunctival injection" with "Conjunctivitis"		-> relabeled
"Coma" with "Coma/Somnolence"						-> relabeled


Complicatinons
Add other complications followed by a text field as in symptoms   -> added Other complications symptom state switch and corresponding text area

**Comment by Chinedar** [comment]
Clinical measurements like: "capillary refill time>2seconds (Yes/No), "malnutrition (Yes/No/Undernutrition/Obesity", Conciousness level (A/V/P/U) have to be captured.  
@MateStrysewskeSym @bernardsilenou These need to be worked in please.

**Comment by MateStrysewskeSym** [comment]
@Chinedar @bernardsilenou Please exactly specify the missing variables and open a new issue for them please. This issue is closed because everything that Bernard had specified has been worked on.

**Comment by MartinWahnschaffeSymeda** [comment]
We need to adjust this for germany and in general:

- [ ] for now re-add cough to the symptoms for COVID. This will also make sense for the other countries, because it allows them update the new cough fields based on the old one
- [ ] Hide the following pre-existing conditions in the UI and app for Germany:
	Obesity
	Current smoker
	Former smoker
	Chronic lung disease
	Asthma
	Sickle cell disease
- [ ] Hide the following symptoms in the UI and app for Germany:
	Wheezing
	Skin rashes 
	Skin ulcers
	Inability to walk
	Bleeding
	Lymphadenopathy
	In-drawing of chest wall
	Cough with sputum
	Cough with heamoptysis 
	
Implementation suggestion:

- We could add another check into the AbstractEditForm.initializeVisibilitiesAndAllowedVisibilities method on whether the field should be hidden by country. This would set the diseaseVisibility variable in the method to false when needed. The implementation of the logic could for now be put into the specific EditForm implementation (e.g. SymptomsForm).
- In the app the same approach can be taken with the BaseFragment.setVisibilityByDisease method

All other Germany specific implementations for COVID will be handled separately.
