### ISSUE TITLE
Add Rest-Endpoints to allow querying of samples and pathogentests via its reference [1]

### ISSUE THREAD

**Issue by stefanspiska** [hzi-braunschweig/SORMAS-Project#1827]
### Situation Description
For the connection to SurvNet it is necessary to get all  samples for a case(list of cases) and then get all pathogentests for a sample(list of samples)
### Feature Description
- Add (analog to  samples/query) a Rest-Endpoint which receives via POST a list of UUIDs and returns a list of samples which satisfy "associatedCase.uuid is in the List of provided  UUIDs".
- Add (analog to  pathogentests/query) a Rest-Endpoint which retrieves via POST a list of UUIDs and returns a list of pathogentests which satisfy "sample.uuid is in the List of provided  UUIDs".
- Add unit tests for the backend methods

**Comment by StefanKock** [comment]
@MartinWahnschaffeSymeda please review this
