### ISSUE TITLE
Landing page has to be preset for every user in-order to avoid "Access denied" message

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1828]
### Bug Description
Landing pages after login are pointed to previously accessed pages and Access denied message appears.
Ex: When a Surveillance supervisor is logged in and access events page, then logs out and logs in as lab officer, Access Denied is displayed as the page still points to events but Lab officer do not have access to events.
Same is the case with other officers who do not have access to certain pages. 

### Steps to Reproduce
1. Login to Demo server as Surveillance Supervisor.
2. Click on events
3. Choose Logout and login as Lab officer and see the page displayed.

### Expected Behavior
Landing page has to be confined to one particular page for all users irrespective of what the previous page is
Ex: Dashboard can be chosen as the landing page for all users
### Screenshots
![Access Denied](https://user-images.githubusercontent.com/62763628/79436382-1545a680-7fd1-11ea-97fd-699d300939cc.PNG)

### System Details
* Device: Windows
* SORMAS version: 1.37.2
* Android version/Browser: Chrome

### Additional Information
Please see the url pointed to on the screenshot attached.

**Comment by HolgerReiseVSys** [comment]
I'm not sure we should change the url the user has entered.
This may be confusing, e.g. when a link is shared by a user with different privileges.
Probably this is primariliy an issue for development and demo use as regular users tend to log in with only a single account.

**Comment by bernardsilenou** [comment]
This is not an issue any more
