### ISSUE TITLE
Add copyright notice for geolocation data [0.5]

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#1829]
### Feature Description
Users can translate address data into geolocations. By licence agreement we are enforced to show a copyright notice. 
### Problem Description
There is no copyright notice. 
### Proposed Change
Add a copyright notice according to licence agreement of the data source. 
### Additional Information
Please come back to me on details. 

### Review
@markusmann-vg 

### Developer Specifications
- add a html-textbox to the "About" Section
- The content should be pulled from the `custom.path` directory configurable in `sormas.properties`
- Make sure the content is properly sanitized to prevent injections
- The whole structure should be reusable, to allow the easy implementation of more html-textboxes (prerequesite for #4766 )
- Once merged, add info on how to add html-files to the wiki. Possibly document the feature elsewhere too

**Comment by MateStrysewskeSym** [comment]
@fhauptmann Can you post a link to the license agreement please?

**Comment by MateStrysewskeSym** [comment]
@fhauptmann Any progress?

**Comment by fhauptmann** [comment]
It should be possible to change this copyright notice depending, which geolocation service is used.

**Comment by HolgerReiseVSys** [comment]
- Where and when shall the notice be displayed?
- What data does the copyright notice relate to? The resulting coordinates?
- How do we make sure the user understands the context of the coyright? I.e. that it does not apply to SORMAS itself.

**Comment by fhauptmann** [comment]
My proposal would be to add a configurable box in the "Info" section of SORMAS. It should be possible to add an HTML-Snippet to display. The Snippet could be read from a file (pach is configured in the sormas.properties) or read from the database. It should be left to the operator, if there is additional information to show. 

In this specific case, we would display this message: 

Geodaten bereitgestellt durch: 
Geokodierungsdienst für Adressen und Geonamen (Bund)
© GeoBasis-DE / BKG,
Deutsche Post Direkt GmbH,
Statistisches Bundesamt,
Wiesbaden (2020)

**Comment by fhauptmann** [comment]
We really need to implement this to fulfill the requirements of the licence.

**Comment by DavidBaldsiefen** [comment]
@fhauptmann by "Info"-Section, do you mean the "About"-Tab of the Menu? 

![image](https://user-images.githubusercontent.com/4655486/123954928-4a0d0600-d9a9-11eb-8e4e-f092ef448eaf.png)

**Comment by DavidBaldsiefen** [comment]
@fhauptmann Is there any copyright notice we want to display by default for all users, or should all notices be custom?
