### ISSUE TITLE
Add Fields for intensive care unit to Hospitalization [1]

### ISSUE THREAD

**Issue by stefanspiska** [hzi-braunschweig/SORMAS-Project#1830]
### Situation Description
In order to make SORMAS more compatible to SurvNet is necessary to add Fields to Hospitalization
### Feature Description
Add the following  Fields to Hospitalization
- hospitalization.icu: Patient is in intensive care unit: Boolean
- hospitalization.icu_start :intensive care unit stay start: Date
- hospitalization.icu_end :intensive care unit stay end: Date

It may be good to add validations

- hospitalization.admissionDate <= hospitalization.icu_start <= hospitalization.icu_end <= hospitalization.dischargeDate

**Comment by bernardsilenou** [comment]
@StefanKock  We will also need the same variables fro cases quarantined at home

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove the AccomodationType field
- [ ] Add a checkbox to document the stay at ICU
- [ ] Add start and end dates for the ICU stay

**Comment by MartinWahnschaffeSymeda** [comment]
Reviewed
