### ISSUE TITLE
Add type of reporting to cases [0.5]

### ISSUE THREAD

**Issue by stefanspiska** [hzi-braunschweig/SORMAS-Project#1833]
### Situation Description
To make SORMAS more compatible with SurvNet is it necessary to add a complex Object Notification to case, describing  how the health department(Gesundheitsamt) was notified of the case 
### Feature Description
Add new complex Object Notification with Fields:

- type: Type of reporting: ValueSet
           - -nicht erhoben- 
           -  -andere/sonstige- 
           - Arzt/Ärztin u.ä. (gemäß §6 (1) 1, 4, 5, §8) 
           - Labor u.ä. (gemäß §7 (1) 2, 3) 
           - Eigene Ermittlung 
           - Gemeinschaftseinrichtung (gemäß §8 (1) 7) 
           - -nicht ermittelbar- 
           - Weiterleitung von einem anderen GA 
          - Gemeinschaftseinrichtung (gemäß §34)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou @Chinedar @hzi-old Do you think that the type of reporting could be of relevance for other countries as well?

**Comment by bernardsilenou** [comment]
In my opinion, it is not needed

**Comment by ChristopherRiedelSymeda** [comment]
@Chinedar @hzi-old Do you agree with bernard?

**Comment by ChristopherRiedelSymeda** [comment]
I will now implement this feature exclusively for Germany
