### ISSUE TITLE
Add feature configurations for automatic task generation [1]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1834]
### Feature Description
On/off- switches to control notifications.

### Problem Description
Health departments in Germany mainly use SORMAS for contact tracing. Therefore, cases are mainly created to add contacts. Only sparse info is added for a case (intentionally). So incomplete cases are no issue. Administrators ask to switch off notifications which are triggered by incomplete cases.

### Proposed Change
Include on/off- switches for different types of notifications.

### Possible Alternatives
Maybe create folders by type of notification, so admins could ignore a certain type.

**Comment by bernardsilenou** [comment]
What so you think about having a a front end bottom for admins to turn off  all automatic notifications (case creation,  daily visits reminder for contacts, ...). Do we not already have such a feature in the propertied file?

**Comment by max-hzi** [comment]
I am not sure if it is a good idea to switch off all notifications as specific notifications might still be required.
What do you mean with propertied file?

**Comment by MateStrysewskeSym** [comment]
- [ ] Add the following feature configurations:

* TASK_GENERATION_CASE_SURVEILLANCE
* TASK_GENERATION_CONTACT_TRACING
* TASK_GENERATION_EVENT_SURVEILLANCE
* TASK_GENERATION_GENERAL

- [ ] When generating a task, check whether the feature configuration associated with the task context is enabled; if not, don't generate the task

**Comment by StefanKock** [comment]
I'll do a review

**Comment by StefanKock** [comment]
Implementation looks good, only made some minor changes that do not touch the functionality
