### ISSUE TITLE
Error displayed when a sample is referred to another laboratory and newly created sample is blank

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1835]
### Bug Description
When a sample from the internal testing is referred to another External laboratory, an error occurs However the new sample is created but shows an empty screen.

### Steps to Reproduce
1. Login and click on Samples.
2. Select a Sample which has the Purpose of sample as "Internal/in house testing" and click on it to edit.
3. Click on Refer to another Laboratory and choose External Laboratory and select any of the labs.
4. Click on Save.

### Expected Behavior
No Error screen must be displayed and sample saved pop-up must be displayed.
Also the newly created sample must not be empty

### Screenshots
![Sample_Referred to another Lab](https://user-images.githubusercontent.com/62763628/79453877-96f5fe00-7fea-11ea-8b62-39cc9fd64cb6.PNG)
![Empty state_Sample](https://user-images.githubusercontent.com/62763628/79453878-98272b00-7fea-11ea-8933-a3d548621ca6.PNG)

### System Details
* Device: Windows 10
* SORMAS version: 1.37.2
* Android version/Browser: Chrome

**Comment by bernardsilenou** [comment]
@raghupola-vg  The purpose of internal samples is not to be refereed but to document in-house or rapid preliminary tests. I f a sample is to be refereed to an external lab, it is better to choose the "external lab testing" as the purpose of the sample.

However I see a bug when an internal sample is refereed and also the data is cleared out. An external sample that is converted to internal sample can later be refereed to an external lab.

**Comment by leventegal-she** [comment]
The following restriction will be added on the sample editing view

- don't allow internal samples to be referred 
- don't allow samples to be changed to internal when they have been referred
