### ISSUE TITLE
ExportFacade.generateDatabaseExportArchive(): Avoid PostgreSQL export directly to file system [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#1836]
### Feature Description
Exporting SQL tables (feature under Statistics -> Database Export in sormas-ui) should not use COPY to Filesystem, because:
1. there are issues that SUPERUSER privilege is required.
2. this requires PostgreSQL Server and Payara to work in the same file system, with makes the docker setup more complicated. 

### Proposed Change

`COPY TO STDOUT` to by Java code managed file or by Stream (in memory). Links to possible solution:
- Short tutorial to `CopyManager`: https://spacanowski.github.io/java/postgres/2016/06/04/postgres-java-copy/
- Hint to `CopyManager`: https://stackoverflow.com/questions/27058454/java-postgresql-copy-with-jpa
- Examples with `CopyManager.copyOut`: https://www.programcreek.com/java-api-examples/?api=org.postgresql.copy.CopyManager
- Example to get `Connection` from the `EntityManager` (specific for JPA Provider and DB Provider): https://stackoverflow.com/a/44214469

### Additional Information
- This export is urgently requested by customers in Germany, where the dockerizes setup is used.
- Feature was developed in #507

**Comment by StefanKock** [comment]
I made a first version, but I would like to have a review for closables and file handling.

Missing: 
1. Deletion of PostgreSQL functions:
`DROP FUNCTION export_database(text, text);`
`DROP FUNCTION export_database_join(text, text, text, text, text, text);`
2. Review code concering zip creation for enhancements.

**Comment by HolgerReiseVSys** [comment]
Instead of reviewing I have continued with the implementaton.
I guess now I need a review:
* The handling of the intermediate csv files was so error prone that I opted for writing directly to the zip.
* The SQL Connection now comes from the EntityManager instead of the DataSource.
* the export is performed while the VaadinSession is unlocked, but an export wait dialog is not yet shown.

**Comment by StefanKock** [comment]
Missing: A frontend test which tests to successfully export all tables (Statistics -> Database Export: Select All and EXPORT: Not notification, but download of a zip file offered)
@raghupola-vg could you take care of that?

**Comment by raghupola-vg** [comment]
Sure @StefanKock 
I do not see a export all feature but a particular filter can be selected and done for now. Will export all be part of the new version?

**Comment by StefanKock** [comment]
There is a "Select all" button to select all tables. This whole export feature is present since at least months and now fixed on development, will be fixed with the next release.

**Comment by raghupola-vg** [comment]
UI test for Export all functionality is completed.

**Comment by StefanKock** [comment]
In case the export functions cannot be deleted, this postgres commands might help:
`\c sormas_db`
`ALTER FUNCTION export_database(text, text)  OWNER TO sormas_user;`
`ALTER FUNCTION export_database_join(text, text, text, text, text)  OWNER TO sormas_user;`
