### ISSUE TITLE
Add Epidemiological data to contacts [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1838]
### Situation Description
It is  a common practice especially for COVID contacts to document the epidemiological data for contacts just as we do for cases. This is needed now for COVID cases but might also be necessary for other diseases that need contact followup.
### Feature Description
Add the Epidemiological data tab to contacts, place it after the visits tab. 
### Additional Information
The epi data from a contact should also be **copied** to the epi data of a case when the contact was converted to a case

**Comment by max-hzi** [comment]
Please prioritise this as high @MateStrysewskeSym

**Comment by bernardsilenou** [comment]
@ChristopherRiedelSymeda is this issue already implemented? I asked because you closed it. I have reopened it and if its already done, please close it back.

**Comment by bernardsilenou** [comment]
I realized it is under progress right now, thanks

**Comment by ChristopherRiedelSymeda** [comment]
- [ ] Move tab to th left of follow-up visits
