### ISSUE TITLE
Allow Finnish translation

### ISSUE THREAD

**Issue by juusotam** [hzi-braunschweig/SORMAS-Project#1840]
### Situation Description

SORMAS does not support the Finnish language

### Feature Description

Allow Finnish translation

**Comment by MateStrysewskeSym** [comment]
@juusotam Hey! As soon as there are some translations added to our Crowdin project (https://crowdin.com/project/sormas/fi#), we'll enable the language in SORMAS.

**Comment by MartinWahnschaffeSymeda** [comment]
Finish translations are complete.

- [ ] add finish to the languages in sormas
- [ ] merge the latest translations
