### ISSUE TITLE
Case Classification Change for GERMAN COVID-19

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#1843]
### Feature Description
Use the abbreviations listed below. The terms "unclassified", "suspected case", "suspected case", "confirmed case" and "no case" are then removed from the German SORMAS.

a.      „nicht klassifiziert“ [A. nicht klassif.]
b.      „klinisch diagnostizierte Erkrankung“ [B. klin-diagnost.]
c.      „klinisch-epidemiologisch bestätigte Erkrankung“ [C. klin-epidem. bestät.]
d.      „klinisch-labordiagnostisch bestätigte Erkrankung“ [D. klin-labor. bestät.]
e.      „labordiagnostisch nachgewiesene Infektion, klinisches Bild nicht erfüllt“ [E. labor. o. klin Bild]
f.       „labordiagnostisch nachgewiesene Infektion, klinisches Bild unbekannt“ [F. klin-labor. unbek. klin. Bild.]
g.      „kein Fall“ [G. kein Fall]
Die Buchstaben Kategorien sind sehr wichtig , das kennen die GÄ

--- english:
a. "not classified" [A. not classified]
b.      "clinically diagnosed disease" [B. klin-diagnost.]
c. "clinically-epidemiologically confirmed disease" [C. clin-epidem. confirms.]
d.      "clinically-laboratory-diagnosed condition."
e.      "laboratory-confirmed infection, clinical picture not fulfilled" [E. labor. o. clin picture]
f.       "Laboratory confirmed infection, clinical picture unknown" [F. klin-laboratory. unknown. clinical picture]
g.      "no case" [G. no case]
The letter categories are very important, as the health departments do know and work with them

2.      No logic besides: the demand of the system for positive corona laboratory test, whether it is a category d-f case 

For the case statistics, the reference definition must be adopted - the RKI is using for the daily publications.  The RKI management report writes: "Only cases are published where a laboratory diagnostic confirmation is available independent of the clinical picture", i.e.: D+E+F everything else must be excluded from the case statistics count, but included in the network representation. VERY IMPORTANT!!!  

### Additional Information
requested by HZI 16.04.2020

**Comment by MartinWahnschaffeSymeda** [comment]
Proposal: Add two new fields for clinical and epidemiological confirmation above the case classification.
The clinical confirmation will be read-only, once we have implemented the automatic logic for it.
We could probably automatically update the SORMAS case classification based on this.

![grafik](https://user-images.githubusercontent.com/23217632/80962589-94c6d880-8e0d-11ea-9782-bf230344d179.png)

TODO: Find out, how this can be done for other diseases and what problems we may run into.

**Comment by markusmann-vg** [comment]
Additional information from the HZI:
Considering Migration

RKI-Definitions:
A. Klinisch diagnostizierte Erkrankung
B. Klinisch-epidemiologisch bestätigte Erkrankung
C. Klinisch-labordiagnostisch bestätigte Erkrankung
D. Labordiagnostisch nachgewiesene Infektion bei nicht erfülltem klinischen Bild
E. Labordiagnostisch nachgewiesene Infektion bei unbekanntem klinischen Bild

old assignments should be treated:
Probable > B

vice versa:
A > suspect
B > probable
C > confirmed
D > confirmed
E > confirmed

**Comment by markusmann-vg** [comment]
Migration:

Nicht klassifiziert             => A
Verdachtsfall                    =>  A
Wahrscheinlicher Fall       => B
Bestätigter Fall                 =>  E
Kein Fall                            => G

Confirmed by Gaby Poggensee

**Comment by bernardsilenou** [comment]
updates from German side:
Use the following classifications: 

        ◦ „nicht klassifiziert“ [0. nicht klassif.]
        ◦ „klinisch diagnostizierte Erkrankung“ [A. klin-diagnost.]
        ◦ „klinisch-epidemiologisch bestätigte Erkrankung“ [B. klin-epidem. bestät.]
        ◦ „klinisch-labordiagnostisch bestätigte Erkrankung“ [C. klin-labor. bestät.]
        ◦ „labordiagnostisch nachgewiesene Infektion, klinisches Bild nicht erfüllt“ [D. labor. o. klin Bild]
        ◦ „labordiagnostisch nachgewiesene Infektion, klinisches Bild unbekannt“ [E. klin-labor. unbek. klin. Bild.]
        ◦ „kein Fall“ [X. kein Fall]

Display as shown in the image, but add a field in which laboratory confirmed is also shown.

![image](https://user-images.githubusercontent.com/12996724/83119860-87310580-a0d0-11ea-9f31-f3e436494b8a.png)

Hide the formulation “probable”, “suspected” and confirmed” in case file.

On the dashboard and transmission chain:
    • Do not show “probable” and “suspected” cases. Only show here laboratory confirmed cases (C-E) summarized in one number.   

Handling of data which are already in the system: 
    • Cases which are already “confirmed cases”  E. klin-labor. unbek. klin. Bild.
    • “probable” and “suspected” cases  need to be clarified

**Comment by markusmann-vg** [comment]
Will be started with: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2230
