### ISSUE TITLE
Add unique IDs to DOM elements for automatic UI testing purposes [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1847]
DOM elements need unique IDs to make sure that changes to the form layout don't break automatic UI tests.

- [ ] Define how to best do this => probably let the field factory generate these IDs for fields in forms; these IDs should be unique for the HTML page, so simply using the field name is probably not sufficient

**Comment by leventegal-she** [comment]
Some details about the code changes:

- introduced AbstractFilterForm(by re-using code from AbstractEditForm) and used on most of the pages.
- the filters on some pages behave a bit differently, there I just added the id-s manually. I didn't want to change the functionality
- Introduced helper functions for button creation to ensure that id is set for them. Changed all buttons to be created using the helper methods
- introduced helper function for bulk actions dropdown creation
