### ISSUE TITLE
Add dummy contact and visit creation to developer options [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#1848]
We need to enable admins of servers with dev mode enabled to also create dummy data for contacts and visits in order to do proper testing.

Create contacts both with (i.e. choose a random case ID from the database) and without cases. Also let some of these contacts have resulting cases.

Potentially: Don't create persons for all of these contacts, but choose existing persons for some of them.

**Comment by StefanKock** [comment]
Looks okay for me, @HolgerReiseVSys did already some refactoring.
