### ISSUE TITLE
Districts Rest-Endpoint dos not return externalID 

### ISSUE THREAD

**Issue by stefanspiska** [hzi-braunschweig/SORMAS-Project#1850]
### Bug Description
Districts Rest-Endpoint dos not return externalID.
### Steps to Reproduce
1. Create district with externalID 
2. Make a Post to /districts/query with body equal to the uuid of the districts

### Expected Behavior
Returned JSON contains externalID Attribute. 
### System Details
* SORMAS version: develop

**Comment by StefanKock** [comment]
Close seems to be missing since 7 days
