### ISSUE TITLE
Labels overlap on Dashboard menu

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1851]
### Bug Description
There is an overlap of UI elements on Dashboard menu.
Please see the attachment.

### Steps to Reproduce
1. Login on web application and click on Dashboard.
2. See the area shown in the screenshot below

### Expected Behavior
There should be no overlap of elements and proper visibility has to be maintained.

### Screenshots
![Dashboard_UI_Overlap](https://user-images.githubusercontent.com/62763628/79560990-de42c400-80a8-11ea-9c5f-208f49987254.PNG)

### System Details
* Device: Windows 10
* SORMAS version: 1.38.0 on Demo server and 1.39.0 on test server
* Android version/Browser: Chrome

**Comment by razvancornita** [comment]
I tested this as @roxanamlendea suggested, with 1496 x 620 resolution, but cannot reproduce it.

![Screenshot 2022-12-23 at 10 25 23](https://user-images.githubusercontent.com/17514879/209300757-5162e698-e901-4274-8a37-a23652efa8e4.png)

**Comment by roxanamlendea** [comment]
I can no longer reproduce it either.
