### ISSUE TITLE
Import region issue

### ISSUE THREAD

**Issue by Stevbreu** [hzi-braunschweig/SORMAS-Project#1853]
### Bug Description
When importing a test-csv I get the following error: 
"invalid value Lower Saxony in column region; entry does not exist in the db."
Niedersachsen but is definitely entered in the database. I have also checked this via psql console. Where is the error?

### Steps to Reproduce
1. Create a test.csv
2. import this csv
3. Stopps with an error

### Expected Behavior
correct import

### Screenshots
test.csv - region
<img width="376" alt="Bildschirmfoto 2020-04-17 um 18 36 17" src="https://user-images.githubusercontent.com/15010128/79592764-c84df700-80da-11ea-8420-094cb5426ba6.png">

error of import
<img width="686" alt="Bildschirmfoto 2020-04-17 um 18 35 46" src="https://user-images.githubusercontent.com/15010128/79592775-cbe17e00-80da-11ea-8772-a30c4e6a488c.png">

Settings Region
<img width="428" alt="Bildschirmfoto 2020-04-17 um 18 37 43" src="https://user-images.githubusercontent.com/15010128/79592792-d3a12280-80da-11ea-91e7-3942cfca7fc0.png">

### System Details
* Device: Ubuntu Server 18.04.3 LTS
* SORMAS Docker VERSION
* SORMAS version: SORMAS Version: 1.37.2
* Android version/Browser: firefox 75.0

**Comment by Stevbreu** [comment]
Find the mistake !!! I am stupid! Sorry

Regard
Steven

**Comment by MateStrysewskeSym** [comment]
@Stevbreu That typo is very easy to miss. Don't worry. ;)
