### ISSUE TITLE
Error occurs when trying to save previous hospitalization

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1856]
### Bug Description
Error occurs when trying to save information on previous hospitalization, on the hospitalization info page.
### Steps to Reproduce
1. Go to hospitalization information page
2. Enter information on previous hospitalization
3. Attempt to save

### Screenshots
<img width="298" alt="hospitalization bug" src="https://user-images.githubusercontent.com/50739609/79632062-d4769a80-8154-11ea-9315-0d52d07e1cb7.PNG">

**Comment by StefanKock** [comment]
[StackTrace trimmed.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4502619/StackTrace.trimmed.txt)

Added a StackTrace concerning this issue

**Comment by MateStrysewskeSym** [comment]
Will be fixed in #1867
