### ISSUE TITLE
Only Cases visible by current User adjusted when saving Person

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1859]
### Bug Description
When a `Person`is modified, *all* its `Case`s may have to be adjusted.
This is done in `PersonFacadeEjb::onPersonChanged`. 
`CaseService.findBy`, however, only returns the `Case`s visible to the current User.
The `user` parameter, set to `null`, is not respected when calling `::createUserFilter`.

### System Details
* SORMAS version: 1.38.0

### Additional Information
This is due to #1597, which was supposed to be a refactoring.

Sidenote: `PersonFacadeEjb::onPersonChanged` calls `caseService.findBy` several times. Is that necessary?

**Comment by MateStrysewskeSym** [comment]
- [ ] Fix failing test

**Comment by StefanKock** [comment]
No findings in code review (except unit tests would have been nice).
