### ISSUE TITLE
Addition of date filters to samples menu of the web application [0.5]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1866]
### Situation Description
There is currently no filter for date of sample collection, shipment, recieved and result on the Samples menu of the samples menu @MartinWahnschaffeSymeda @MateStrysewskeSym 
### Feature Description
Enable to search samples by date. (Remark: We have one German health department asking for the option to also input the date of of result reception, but this is a different issue)

**Comment by max-hzi** [comment]
I was about to create the same issue. Currently it is not possible to limit search results to all positive results from the last week or yesterday.

### Feature Description
Enable to search samples by date. Various dates could be considered here. Best would be to choose which date should be considered (date of sample collection or date of result) via a drop-down menu, after that the date entry fields should appear. (Remark: We have one German health deparment asking for the option to also input the date of of result reception, but this is a different issue)

**Comment by Iheanacho2027** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym @bernardsilenou can this be made priority for the next release?

**Comment by bernardsilenou** [comment]
I think date of sample collection is fine. Date of result will be tricky because a sample can have many results and some of the results each with different date.

**Comment by max-hzi** [comment]
I would like to rise attention to this issue again.
