### ISSUE TITLE
Update old HZI logo (log-in page)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1870]
### Feature Description
Please include the most recent HZI logo in SORMAS.

### Problem Description
The logo currently used is outdated.

### Proposed Change
Please exchange the old logo with the newer HZI logo:
![Helmholtz_HZI_Logo_RGB_DE_nebeneinander](https://user-images.githubusercontent.com/63781233/79748019-f7e44580-830c-11ea-82ad-0e45b230b3b0.jpeg)

**Comment by max-hzi** [comment]
Please prioritise this issue @MateStrysewskeSym

**Comment by HolgerReiseVSys** [comment]
The file was quite large, so I resized it
