### ISSUE TITLE
when you filter contacts or cases by a date range that falls in a week, the filter is automatically converted to "By Epi Week"" [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1874]
### Bug Description
This change of units is confusing to user in the field.
### Steps to Reproduce
1. Filter case listing  from 13 April to 15 April by date
2. the filter automatically change to weeks

### Expected Behavior
- Maintain the units of time chosen by  the user
### System Details
* Device: web
* SORMAS version:  1,38,0
* Android version/Browser:

### Review
@markusmann-vg

**Comment by ChristopherRiedelSymeda** [comment]
scope:
- [ ] add information to criteria
- [ ] get filter selection from criteria instead from until now used method (remove this method?)
