### ISSUE TITLE
Error on disease slider on dashboard

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#1877]
### Steps to Reproduce
1. open the dashboard
2. click on any disease on the slide show. e.g covid 19. Error pop up

### Screenshots
![image](https://user-images.githubusercontent.com/19344651/79796446-d9566c80-8355-11ea-946f-47aac1fead20.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@hzi-old I guess this is about the Nigerian system? @Chinedar You haven't yet added districts to the events on the Nigerian server that for some reason don't have districts assigned. I suspect that this is the same bug.

**Comment by Chinedar** [comment]
The events export returns an error (probably as a result of the same
issue). Would have been helpful to search and identify to fix those errors.
Will continue the manual scroll till we sort all of them out.

**Comment by MateStrysewskeSym** [comment]
@Chinedar It's unfortunate that we don't have a UUID filter on the event list. It probably would be easier to do the changes directly in the database, but I can't do it because I won't miss with production data. Maybe @hzi-old can help with that.

**Comment by Chinedar** [comment]
no worries @Maté Strysewske <m.strysewske@symeda.de> I'll do it directly in
the DB. Thanks.

**Comment by Chinedar** [comment]
@Maté Strysewske <m.strysewske@symeda.de> This has been rectified. The
dashboard slider works just fine now. Thanks.

**Comment by MartinWahnschaffeSymeda** [comment]
See #1931
