### ISSUE TITLE
Editing a case after creating a sample fails

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1882]
### Bug Description
An error occurs when trying to save an edit made on the case information page
### Steps to Reproduce
1. Enter sample information for a fresh case and save
2. Change case classification or/and investigation status 
3. Attempt to save the case information page

### Screenshots
<img width="629" alt="save bug" src="https://user-images.githubusercontent.com/50739609/79864858-152f1780-83d2-11ea-9925-a108ed13ea13.PNG">

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
The issue is that saving a sample triggers onSampleChanged, which in case calls onCaseChanged. We probably have to reload the view after a sample has been created, and need to add a warning message that all changes will be lost.

**Comment by StefanKock** [comment]
Should be reviewed by @MartinWahnschaffeSymeda or @ChristopherRiedelSymeda
