### ISSUE TITLE
Missing German translation during case creation (field "Gesundheitseinrichtung")

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1888]
### Problem Description
There is a missing translation when using SORMAS in German. When a case is created choosing "Neuer Fall" ("New Case"), the drop-down menu for "Gesundheitseinrichtung" ("Health Facility") shows answers in English, not in German as expected. The translation is also missing in "Fallinformationen" - "Fall" ("Case information" - "Case").

### Proposed Change
Change "Other health facility" to "andere Gesundheitseinrichtung" and "Home or other place" to "Zuhause oder anderer Ort"

### Possible Alternatives
n/a

### Additional Information
Sormas Version 1.38.0
Laguage setting: German

**Comment by Candice-Louw** [comment]
Translations completed and synced from CrowdIn.
