### ISSUE TITLE
Exclude certain characters in automatic password generation

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1889]
### Situation Description
Admins create users and SORMAS automatically creates a password. The password is handed to the respective user. This password includes characters which are difficult to distinguish, e.g. I and l (capital i and lower case L), 0 and O (zero and capial o).

### Feature Description
Exclude certain characters used in the automatic password generation: Exclude 0 (zero), o, i and L (all upper cases and lower cases).

### Possible Alternatives
Only exclude I (capital i), O (capital o), l (lower case L) and 0 (zero).

### Additional Information
Not a crucial feature, but a rather a feature of kindness.

**Comment by markusmann-vg** [comment]
this should already be working.
Are you able to reproduce the isse or did you have the case in the near past?

**Comment by max-hzi** [comment]
I can confirm that this is no longer an Issue. Thanks!
