### ISSUE TITLE
No such file or directory Error on installation

### ISSUE THREAD

**Issue by scottboyde** [hzi-braunschweig/SORMAS-Project#1892]
### Bug Description
Error during installation 

setfacl: /opt/sormas/temp : No such file or directory

### Steps to Reproduce
1. Running  sudo -s ./server-setup.sh and Just after Starting Server Setup I get the error

### Expected Behavior
Find Directory  /opt/sormas/temp

### System Details
* Device: ubuntu Server
* SORMAS version: 1.38.0
* Android version/Browser:

### Additional Information

On line 135 of server-setup.sh there is a space between } and end "

setfacl -m u:${USER_NAME}:rwx "${TEMP_DIR} "

**Comment by StefanKock** [comment]
Reviewed
