### ISSUE TITLE
SQL error relation "schema_version" does not exist during Installation 

### ISSUE THREAD

**Issue by scottboyde** [hzi-braunschweig/SORMAS-Project#1893]
### Bug Description
When running ./server-serup.sh I get an error 

psql:setup.sql:14: NOTICE:  relation "schema_version" does not exist, skipping

### Steps to Reproduce
1. run ./server-setup.sh

### System Details
* Device: Ubuntu Server
* SORMAS version: 1.38.0
* Android version/Browser:

### Additional Information

in the server-setup.sh the sql query is 
` cat > setup.sql <<-EOF
245 CREATE USER $DB_USER WITH PASSWORD '$DB_PW' CREATEDB;
246 CREATE DATABASE $DB_NAME WITH OWNER = '$DB_USER' ENCODING = 'UTF8';
247 CREATE DATABASE $DB_NAME_AUDIT WITH OWNER = '$DB_USER' ENCODING = 'UTF8';
248 \c $DB_NAME
249 CREATE OR REPLACE PROCEDURAL LANGUAGE plpgsql;
250 ALTER PROCEDURAL LANGUAGE plpgsql OWNER TO $DB_USER;
251 CREATE EXTENSION temporal_tables;
252 CREATE EXTENSION pg_trgm;
253 GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO $DB_USER;
254 \c $DB_NAME_AUDIT
255 CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
256 COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
257 GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO $DB_USER;
258 ALTER TABLE IF EXISTS schema_version OWNER TO $DB_USER;
259 EOF
`

But should this be as follows its stated in the following

https://github.com/hzi-braunschweig/SORMAS-Project/issues/1514#issuecomment-585185430

**Comment by HolgerReiseVSys** [comment]
This is expected and just a notice.

**Comment by scottboyde** [comment]
It may be a notice but in the databases the table schema_version doesnt exist

**Comment by HolgerReiseVSys** [comment]
This is okay because it is created by the `sormas_schema.sql` script when deploying the sormas EAR
