### ISSUE TITLE
Request for treatment centre configuration on the configurations menu

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1896]
### Situation Description
Due to the possibility of having several treatment centres across a state or region, treatment centres should have user accounts which will depend on treatment centres configured into the system just like laboratories and health facilities
### Feature Description
There should be a configurations platform where admins can create treatment centres in the configurations menu as part of actualization of #1895 #1894 @bernardsilenou @hzi-old

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda @hzi-old. Can this ticket be given priority, this is currently being requested by stakeholders. This includes  #1895 and  #1894  @Chinedar

**Comment by bernardsilenou** [comment]
@Iheanacho2027 Treatment center is just a type of health facilities in the system. Create the treatment center as  a "health facility" and give the user role of "Clinician" to the user.

**Comment by Iheanacho2027** [comment]
@bernardsilenou we need a situation whereby a clinician can be specific to a single treatment facility as practiced currently in Nigeria where there are several treatment centres in a single state. A clinician user account on SORMAS views cases within an entire state. A case officer user account would have been good but a case officer but scanning through the user account, i was of the opinion that the case officer user account is more specific to LGAs and not a health facility

**Comment by bernardsilenou** [comment]
@Iheanacho2027  OK, understand you now. so you need clinicians who only see cases in their hospital and nothing else, right?

**Comment by bernardsilenou** [comment]
this will be right a right added to the default hospital informant role, right?

**Comment by Iheanacho2027** [comment]
Informant's access is mobile. Lets have a role called facility clinician and modify the name of the role "clinician" to "State Clinician". A facility clinician will view all clinical cases within a treatment centre while a state clinician will view all clinical cases within the state. We can modify the user role "case officer" into the role "facility clinician" because i dont really know the use of that role

**Comment by Iheanacho2027** [comment]
*Btw* kindly open the ticket #1895 which you closed, it is very relevant

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Giving users that operate on a health facility level access to the web app is not that trivial right now - we already have an issue for this: #1960 - Once that's done, we can take care of #1895 

Concerning this issue, in which way are treatment centers different from the health facilities that are already used in the system? We will, at some point in the next months, add additional facility types such as medical practices and nursing homes. Treatment centers could then be one of these new types, but until then, you could just create them as normal health facilities (and later change their type).

I've re-opened #1895 - can this issue right here be closed?

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym Cant really say if its related to #1960 because i dont know if the informant's web access will have access to clinical course and case therapy. If the #1960 says informant will be able to operate like a clinician but specific to health facilities on the web, then we can close the ticket

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym Treatment centres in Nigeria are different from health facilities as they are used as isolation centres e.g a hotel can be converted to a treatment centre for the purpose of isolation or quarantine as the case of COVID-19

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym Cant really say if its related to #1960 because i dont know if the informant's web access will have access to clinical course and case therapy. If the #1960 says informant will be able to operate like a clinician but specific to health facilities on the web, then we can close the ticket

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 What I mean is that granting hospital informants access to the web app is a pre-requisite for #1895. #1895 will require a new user role for now, i.e. a hospital informant that also has access to the case management module. We'll take care of that as soon as we've managed to grant informants access to the web app.

**Comment by bernardsilenou** [comment]
@Iheanacho2027 @chukwuemekauzoho  @Chinedar 
- It is not clear if you want to analyse the data by user role (clinician) or by facility (treatment centry). Can you explain the need in details? not the solution.
- Clinicians are regional users and not localized to a fancily, so it is not possible to analyse cases be user roles. It would be better to that by facility, irrespective of the user role.

**Comment by chukwuemekauzoho** [comment]
@bernardsilenou the Lassa fever TWG wants to be able to export and analyze the data by the Lassa fever treatment centers designated on SORMAS. This is currently not feasible even on the case management module. The essence of this is to be able to track the cases by treatment centers they are assigned to during treatment. That option is available.

**Comment by bernardsilenou** [comment]
@chukwuemekauzoho 
What you are asking for is a special use case and would require you to do database export. Lets have a look at this in a  call pls. Schedule one with the team pls.
