### ISSUE TITLE
Don't display hospitalization information for "Home or other place" [0.5]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1900]
### Bug Description
The field 'hospital name' in 'case hospitalization' displays 'Other health facility' or 'Home or other place' if proviously selected as 'health facility' in 'case'. This is contextually wrong as both are not a hospital.

### Steps to Reproduce
1. Open any case with 'health facility' set to 'Home or other place' or 'Other health facility'
2. Navigate to 'hospitalization'
3. Check info displayed in field 'hospital name'

### Expected Behavior
This field should exclusively show the hosital name, i. e. it should not show anything if no hospital is selected as health facility.

### Screenshots
![12412432](https://user-images.githubusercontent.com/63781233/80076526-9dd1c300-854c-11ea-9101-84d6af50aff7.PNG)
![123123123](https://user-images.githubusercontent.com/63781233/80076529-9f02f000-854c-11ea-9171-5c565b780ff2.PNG)

### System Details
* Device: Browser
* SORMAS version: 1.38.0#

### Additional Information
n/a

**Comment by bernardsilenou** [comment]
@max-hzi This issue was realized and we decided to keep it like that just for a while. The reason is because we plan to change the the tab to register HF and separate it from Home and other places at the front end while creating a case.

**Comment by max-hzi** [comment]
Sounds good, thank you for clarification.

**Comment by MateStrysewskeSym** [comment]
@max-hzi It's still a valid point, it'll just take some time until we can do it. I've moved it to the backlog for now.

**Comment by MateStrysewskeSym** [comment]
- [ ] In addition, disable all fields except the previous hospitalization fields
