### ISSUE TITLE
New User role for ReST endpoints

### ISSUE THREAD

**Issue by stefanspiska** [hzi-braunschweig/SORMAS-Project#1905]
### Situation Description
For the SurvNet Integration it es needed to have a system User  who can access all Data via REST
### Feature Description
Create a new User-Role Rest-User who
- can access all Rest-Endpoints
- can see all Cases and associate data

**Comment by markusmann-vg** [comment]
This user should not be able to login via the web or app but only REST

**Comment by HolgerReiseVSys** [comment]
I feel REST_USER is a misnomer.
To me this implies that all users allowed to to use the rest api should have this role.
In this Context USER should actually be named REST_USER.

Also I'm not sure we should grant blanket permissions.
E.g. at the moment the SurvNet Integration only requires read access.

I can see that we don't want to implement duplicate endpoints.
Still we could have another jax-rs application with only the required resources registered.
Having them on a separate path would allow us to not expose the internal api and, if required, evolve them idependently later.

Any thoughts?

**Comment by MateStrysewskeSym** [comment]
@HolgerReiseVSys I'm very open to improvements on this issue. Just wanted to get it out of the way so @stefanspiska can work with it. Can you talk about this topic in the next planning?

**Comment by TexGG** [comment]
Seems you failed somewhere : at some point, the apk try to call "/sormas-rest/users/all/0" and got 403 error. Since the "UserResource.java" only allowing "USER" and not "USER_REST" it seem logical, but it's blocking the "Rest Only User"

**Comment by MateStrysewskeSym** [comment]
@TexGG I'm a bit lost - why would the APK try to access the ReST API as a ReST User and not as a normal user? The ReST User is essentially there for external systems to be able to connect to our API, and these external systems should not have access to SORMAS users.

**Comment by TexGG** [comment]
Nevermind I thought that it was also used for REsT access with APK. But after checking the code, and your response, I was wrong.
