### ISSUE TITLE
Change quarantine input fields for cases and contacts

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1906]
### Feature Description
Subsequent to #1762 , further refinement for quarantine input fields is required for German health departments, as they have caused some confusion. More details below.

### Problem Description
Some health departments struggle with the current input fields for quarantine for both, cases and contacts. We are asking to integrate identical fields for cases and contacts as described below.

### Proposed Change
Add questions concerning home-based quarantine:
Question: "Home-based quarantine possible?" (German: "Häusliche Quarantäne möglich?") with predefined answers: "yes" or "no" (German: "ja" or "nein"); in case of "no", show comment field. In case of "yes" show follow-up question: "Supply ensured?" (German: "Versorgung gewährleistet?") with predefined answers: "yes" or "no" (German: "ja" or "nein"); in case of "no", show comment field. 

In case of quarantine, date entry fields for quarantine start and end are required. Additional date entry fields are required to document quarantine start and end date for both written and oral quarantine order (to accommodate German jurisdiction).

### Possible Alternatives
Unknown.

### Additional Information
n/a

**Comment by MateStrysewskeSym** [comment]
@max-hzi The part about the additional date fields for both written and oral quarantine order seems strange to me. Wouldn't it be enough to have a "date issued" field for both?

**Comment by max-hzi** [comment]
Thank you for your reply. I agree with you, it does seem odd. The request for two separate fields arises from the fact that the two orders are separate processes. First, the quarantine order is given orally, and subsequently, the person receives the order in writing. 
I just got back to Manuela and she confirmed that both dates are usually identical. So I conclude to have separate fields is more precise in terms of documentation, but not essential.

**Comment by MateStrysewskeSym** [comment]
- [ ] Replace OrderMeans with two separate checkboxes: "Quarantine ordered verbally" and "Quarantine ordered by official document"
- [ ] Add two new date fields "Verbal order issued" and "Official document order issued"
- [ ] Add the two new questions and associated comment fields described above

**Comment by markusmann-vg** [comment]
As discussed in the review, @bernardsilenou will come up with a spec how to proceed after discussing with Max

**Comment by max-hzi** [comment]
Hi, so we just discussed this internally again. Please integrate the new quarantine input fields as you suggested in the sprint yesterday. Berlin needs is this way.

There is no doubling in the questions. Maybe we should provide an info button later in time (we will discuss internally beforehand). For now, the discussed changes are fine.

More info:
'Home-based quarantine possible?' is referring to housing conditions/ 'Wohnverhältnisse' (e. g. multiple residents in a small apartment, or immunosuppressed person at home).

'Supply ensured?' refers to the supply situation (e.g. if grocery shopping can be done by a third party).

**Comment by MartinWahnschaffeSymeda** [comment]
Alright. Thanks!

**Comment by max-hzi** [comment]
Is it possible to have the "help needed in quarantine?" textbox removed? This field is now redundant as we have introducted a different field "supply ensured?" as discussed above. Thank you.

**Comment by markusmann-vg** [comment]
Ho do we migrate the data? Should we move all checks that were made at "help needed in quarantine" to the new field to not lose (visible) data

**Comment by bernardsilenou** [comment]
I have no idea for now because this variable "supply ensured" is valid only fro home based quarantine while the "help needed in quarantine" is valid for all types of quarantine. In addition

**Comment by MartinWahnschaffeSymeda** [comment]
Please create a new issues if needed
