### ISSUE TITLE
Add filter in task management to display not yet assigned tasks

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1909]
### Situation Description
It is not possible to filter by task in task management which are not assigned to a user.

### Feature Description
Add a filter to display all tasks with missing assingment to a user.

### Possible Alternatives
Open to suggestions.

### Additional Information
Please include in next sprint as discussed with Minh Tam.

**Comment by MateStrysewskeSym** [comment]
@max-hzi You can sort the task list by assigned user, which will bring all tasks that don't have an assignee to the bottom or top, respectively. The filter is still a nice addition, but since there's a workaround, I'll add this issue to the backlog, not to the current sprint.

**Comment by max-hzi** [comment]
Thank you for the hint - very helpful. I'll spread the word!

**Comment by SahaLinaPrueger** [comment]
'Assigned to' is a mandatory field and as @MateStrysewske described there is an easy workaround. Can we close this issue @max-hzi ? @JaquM-HZI
