### ISSUE TITLE
Check Database Configuration on Startup of EAR

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1913]
### Situation Description
Sometimes when setting up a new system, some instructions concerning the setup of the PostgreSQL server are overlooked.
This tends to results in hard to troubleshoot issues.

### Feature Description
In `StartupShutdownService`, before updating the databases, the database server should be inspected:
* Is the PostgreSQL version supported?
* Is `max_prepared_transactions` set correctly?
* Is the extension `temporal_tables` installed?
* Is the extension `pg_trgm` installed?

Depending on the severity of the issues either a warning can be logged, or the whole deployment process can be interrupted by throwing an exception.

### Possible Alternatives
(or complements)
* Revise the setup instructions
* Check postgres from the setup script
* require pure Docker deployments (which is not necessary appropriate for databases in production environments)

**Comment by StefanKock** [comment]
Reviewed and tested.
