### ISSUE TITLE
ERROR  d.s.s.backend.common.ConfigFacadeEjb 

### ISSUE THREAD

**Issue by scottboyde** [hzi-braunschweig/SORMAS-Project#1925]
Hi

I have recently deployed a sormas server and when someone logs in I get two emails with the following errors. Can these be ignored or is there a specific reason for them, thanks

2020-04-27 11:58:12,218 ERROR PHATest  d.s.s.backend.common.ConfigFacadeEjb - For input string: ""

2020-04-27 11:58:12,214 ERROR PHATest  d.s.s.backend.common.ConfigFacadeEjb - empty String

**Comment by StefanKock** [comment]
Hello, it seems that there is some configuration in `sormas.properties` missing. Please try it again with 1.39.0 (released yesterday), you should get a message now, which configuration parameters are causing these error messages.
