### ISSUE TITLE
Change colour scheme in contact directory/ follow-up visits

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1926]
### Feature Description
Alter the colour scheme currently used in contact directory/ follow-up visits.

### Problem Description
Some health departments have difficulties to distinguish the colours, esp. blue and purple.

### Proposed Change
Change uncooperative to orange for example.

### Possible Alternatives
Alter the entire colour scheme, also suitable for colour blind people.

### Additional Information
n/a

**Comment by ChristopherRiedelSymeda** [comment]
Should just "uncooperative " be orange? If not, please provide a complete list of proposed changes.

**Comment by max-hzi** [comment]
Orange for 'uncooperative' is fine, thank you.

**Comment by bernardsilenou** [comment]
I think we should use another colour. Orange and red are already used in other parts of the tool to means confirmed ans probable cases. In addition, this will still be difficult to differentiate from "seen with signs" category.
@max-hzi what do you think?

**Comment by bernardsilenou** [comment]
@max-hzi  What about using the same colour with higher intensity? Any other colour that is not part of case classification or already used on surveillance or contact dashboard will be good to use.

**Comment by max-hzi** [comment]
Yes lets choose the same colour but with higher intensity!

**Comment by markusmann-vg** [comment]
@max-hzi Please provide the exact RGB-code for the color. Thank you

**Comment by max-hzi** [comment]
My suggestion is rgb(255,25,255).

**Comment by StefanKock** [comment]
From Sprint Review:
1. Same color for table and legend
2. Tooltip in table objects (not just color)

**Comment by StefanKock** [comment]
Code Review: Why doing a switch in `ContactFollowUpGrid::getVisitResultDescription`, when `VisitResult.toString` would do the same?

**Comment by leventegal-she** [comment]
Code Review: OK
