### ISSUE TITLE
When creating a health facility, the community should not be required field. [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1928]
### Feature Description
Some districts do not have communities and this makes it difficult to create a health facility.
For duplicate detection of HF, we should also drop the community variable.
##### to be reviewed by:
@MateStrysewskeSym

**Comment by markusmann-vg** [comment]
- [ ] Adjust filter logic that defines the entries in health facility selection
- [ ] Change community from mandatory to optional

**Comment by ChristopherRiedelSymeda** [comment]
@markusmann-vg The selection of Health Facilities is already possible without specifying a Community.

**Comment by markusmann-vg** [comment]
@ChristopherRiedelSymeda The ticket is about creating not selecting.
