### ISSUE TITLE
Events entered without LGA, crashes the disease slideshow on dashboard

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#1931]
### Bug Description
Users are able to enter Events on Nigerian server without inputing LGA which is a required field. 
### Steps to Reproduce
1. 
2.

### Expected Behavior
This should not be possible. 
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by Chinedar** [comment]
@MateStrysewskeSym this was what you pointed out. Somehow the guys are still able to save without select a district. Keeps crashing the slider on the dashboard.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar This is fixed now (a missing check in the dashboard). For more details on why there are events without district can be found in #1940

**Comment by Chinedar** [comment]
Fabulous, Thanks.
