### ISSUE TITLE
'Search specific case' - Button without function

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1932]
### Bug Description
If I click on the button 'search specific case' (on the top right in the case directory, left to 'line listing'), I can enter the name of a case I would like to display. The search function does not provide any search results and is therefore useless.

### Steps to Reproduce
1. Open case directory
2. Click on 'search specific case' (top right)
3. Enter the name of an existing case

### Expected Behavior
Return the desired case.

### Screenshots
n/a

### System Details
* SORMAS version: 1.38.0

### Additional Information
This field is not essential as cases can be seached with the free text search 'ID, name, EPID number...' field. Maybe this field could simply be removed.

**Comment by markusmann-vg** [comment]
It is not expected to search for a name and therefore you don't get a result.
When I search for CaseID, external ID or Epid-Nr, then I will be redirected to the case directly.

German description:
"Sie können nach Fall-ID, externer ID oder der Epid-Nummer suchen"

**Comment by max-hzi** [comment]
Oh, correct. I did not examine/ reproduce this request thoroughly, my mistake. Sorry. 

We received a couple of confused queries why this button does not work properly whenever a name is entered. But of course, it doesn't work if it requires an ID. Thank you for clarification.
