### ISSUE TITLE
General comment field for contacts [1]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1933]
### Situation Description
There is no comment field for general comments even though there is the urgent need from German health departments.

### Feature Description
Introduce a free text box for comments without character limitation. This free text box should be introduced on the case/ contact information page.
Please name the free text fields 'General comment' / 'Allgemeine Bemerkung'

### Possible Alternatives
n/a

### Additional Information
Health departments are forced to (miss)use existing comment fields which are intented for other comments.

##### reviewed by
@markusmann-vg

**Comment by markusmann-vg** [comment]
@max-hzi Where should the new field (text-area) be positioned on the case data page?

**Comment by max-hzi** [comment]
Thank you for looking into this. My suggestion is to include the new free text box at the very bottom of the page, just above the discard/ save buttons.

**Comment by bernardsilenou** [comment]
@markusmann-vg @max-hzi 
What about the mobile app? Is this needed only for the web app and specifically for Germany?

**Comment by ChristopherRiedelSymeda** [comment]
There is already a text area for it, at least for cases. It is called "Additional details" or "Zusätzliche Details". Maybe the name or positioning can be optimized.

**Comment by max-hzi** [comment]
> There is already a text area for it, at least for cases. It is called "Additional details" or "Zusätzliche Details". Maybe the name or positioning can be optimized.

I think we should have free text boxes with identical descriptions for both, cases and contacts. I did not consider the 'additional details' input field in cases as I thought it refers to the GPS info. But probably that's just my misinterpretation. I suggest renaming the free text field on the 'case'-page to 'General comment' / 'Allgemeiner Kommentar'. 
Concerning the positioning, I still suggest placing the text boxes above the discard/ save buttons as mentioned above.


> What about the mobile app? Is this needed only for the web app and specifically for Germany?

I can imagine the comment fields are equally important for the app, but this is your call.

**Comment by ChristopherRiedelSymeda** [comment]
> I can imagine the comment fields are equally important for the app, but this is your call.
 The "Additional Details" for the case are also available in the app.

**Comment by markusmann-vg** [comment]
So the task is just to rename the field and reposition it.

**Comment by max-hzi** [comment]
> So the task is just to rename the field and reposition it.

Yes, and please introduce this field for contacts as well.

**Comment by markusmann-vg** [comment]
- [ ] add it to contacts
- [ ] reposition and rename

both in Web & App

**Comment by MateStrysewskeSym** [comment]
@ChristopherRiedelSymeda You've added the general contact comment field for the mobile app to a linear layout that is hidden when there is no source case. This needs to be fixed.

**Comment by max-hzi** [comment]
@markusmann-vg Berlin urgently asks for more charaters in the 'additional details'-box. This will be moved and renamed as discussed in this issue, but is it possible to enable more charaters? At least 1024, but best ist 2048 or even 4096. They enter whole stories there.
I also kindly ask to add charaters to the 'follow-up status comment' (shall I create a new issue for this or is this too minor?)
Thank you!

**Comment by bernardsilenou** [comment]
@max-hzi  Create a new issue? This is closed and your request is urgent

**Comment by MateStrysewskeSym** [comment]
@max-hzi Please don't comment on already closed issues as we might not see and therefore react to any requests made in those.
