### ISSUE TITLE
wrong Symeda Logo on Login Page of SORMAS

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#1935]
### Bug Description
On the login page, on the right side "powered by" contains the wron Symeda logo

### Steps to Reproduce
1. start Sormas from Web

### Expected Behavior
see attached logo
![vitagroup_symeda_Logo_rgb](https://user-images.githubusercontent.com/62540178/80498004-80955e00-896b-11ea-8b7c-8a89a63a3845.png)

### Screenshots
![Bildschirmfoto 2020-04-28 um 16 12 34](https://user-images.githubusercontent.com/62540178/80497766-2c8a7980-896b-11ea-9114-d63588f0d6b8.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by StefanKock** [comment]
Reviewed in code and on a TEST stage
