### ISSUE TITLE
Add symptom to COVID-19: Odour and taste disorder

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#1936]
### Situation Description
A common symptom for COVID-19 is missing in 'Case Symptoms' - 'Clinical signs and symptoms'.

### Feature Description
Add the following symptom:
German: 'Geruchs/- Geschmacksstörungen' (as listed by RKI)
English: 'New loss of taste or smell' (as listed by CDC)

### Possible Alternatives
n/a

### Additional Information
Priority: High

**Comment by MartinWahnschaffeSymeda** [comment]
@max-hzi Just to make sure: It's only a single symptom, correct?

**Comment by max-hzi** [comment]
I was also thinking of having them separated, but RKI and CDC report them together. The upside would be exact documentation, probably we should aim for that.

Please add these symptoms:
German: 'Geschmacksstörungen' and 'Geruchsstörungen'
English: 'New loss of taste' and 'New loss of smell'

**Comment by MartinWahnschaffeSymeda** [comment]
@max-hzi We should go as close as possible to what CDC and RKI define. This will make it a lot easier to exchange data in both directions.

**Comment by max-hzi** [comment]
OK, so I just called Juliane to clarify this. Please integrate them separately as described here:
 
> German: 'Geschmacksstörungen' and 'Geruchsstörungen'
> English: 'New loss of taste' and 'New loss of smell'

**Comment by bernardsilenou** [comment]
We did a review last week and decided follow the changes as I mentioned in my comments in issue #1824. I will recommend that we follow my comments there because some symptoms should be dropped also and many others added.

**Comment by MartinWahnschaffeSymeda** [comment]
I checked the SurvNet interface. There it's called "Geschmacksverlust" and "Geruchsverlust".

Implementation:

- [ ] Add symptom lossOfTaste: "New loss of taste" / "Geschmacksverlust"
- [ ] Add symptom lossOfSmell: "New loss of smell" / "Geruchsverlust"
