### ISSUE TITLE
Open read view of case fragements, when user does not have access [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1944]
### Feature Description
The mobile app prevents users from editing cases and contacts outside their jurisdiction #1647

### Problem Description
When opening the case contacts of a non-editable case it's still possible to move to other edit views of the case.

### Proposed Change
When trying to move to an edit view check whether the user has access rights. If not open the read view instead.
Ideally we should implement this in a generic way in the base activities and fragments. Only the logic to check whether the user can access the edit view should need to be implemented in the child elements.

### to be reviewed
@sergiupacurariu

**Comment by markusmann-vg** [comment]
scope:
- [ ] When trying to move to an edit view check whether the user has access rights. If not open the read view instead.

**Comment by MartinWahnschaffeSymeda** [comment]
Making this more generic will be done in #2029
