### ISSUE TITLE
Disease Network Diagram: complete i18n [1]

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1950]
### Feature Description
All labels fo the Disease Network Diagram should be internationalized.

### Problem Description
At the moment this only applies to enum values.
Also on the backend only the default language is taken into account.

### Additional Information
Succeeds #1563

### review
@ChristopherRiedelSymeda

**Comment by ChristopherRiedelSymeda** [comment]
When reviewing, please consider only the first two and the last commit. The others come from ammending.

**Comment by MateStrysewskeSym** [comment]
I can't review this issue because the script doesn't execute for me. Apparently there's a bug in it, but the error message doesn't give any kind of hint about where the problem might lie.
