### ISSUE TITLE
Symptoms tab does not translate when you change the langue after log in

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1955]
### Bug Description
When the user change the language, the captions: clinical measurements, symptoms and complications will retained the previous language. I did not check the other sections of the app but it will be good to check when fixing this bug,
### Steps to Reproduce
1. log to a web account
2. open a case and open symptom tab
3, Change the language and watch what happen to captions

### System Details
* Device: web
* SORMAS version: 1,39,0
* Android version/Browser:

**Comment by bernardsilenou** [comment]
on .symeda server, the caption is always in french, no matter the language setting of the user

**Comment by StefanKock** [comment]
I can confirm this (some sub headlines), but it seems only be a matter for some case views: case, case person, hospitalization, symptoms.

**Comment by MartinWahnschaffeSymeda** [comment]
Very strange. The few captions seem to always stay French on sormas.symeda.de
On the musterstadt server this is not the case.

**Comment by MateStrysewskeSym** [comment]
Fixed with #2209
