### ISSUE TITLE
GPS coordinates are not found and auto selected

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1956]
### Bug Description
No GPS coordinates are found alert is displayed when "Pick current GPS for address" is selected

### Steps to Reproduce
1. Login to the mobile app and Choose Events
2. Click on + icon to create an event.
3. Click on Event Location field, a new Location window opens up
4. Scroll down and select "Pick Current GPS for address" and see if the location is auto selected.

### Expected Behavior
The location and its coordinates has to be auto selected.

### Screenshots
![GPS not selected](https://user-images.githubusercontent.com/62763628/80712043-a2205200-8af1-11ea-9c54-ede9eac44792.png)

### System Details
* Device: Samsung S 10
* SORMAS version: 1.39.0
* Android version/Browser: 10

**Comment by ChristopherRiedelSymeda** [comment]
Did this happen in an emulator or on a real smartphone?
For which country is the server configured?

**Comment by raghupola-vg** [comment]
It is on real smartphone.
Also GPS settings were enabled.

**Comment by ChristopherRiedelSymeda** [comment]
@raghupola-vg For which country is the server configured?

**Comment by raghupola-vg** [comment]
Below is the server link i am using for the app. Not sure for which country is this configuration.
https://sormas.symeda.de/sormas-rest/

**Comment by ChristopherRiedelSymeda** [comment]
First of all, thank you very much for the information. The server (sormas.symeda.de) is configured for Nigeria. There is a function in which the app discards the GPS coordinates which are definitely not in the country (defined in the sormas.properties). So it is normal that you can't get coordinates from this server without faking them.
