### ISSUE TITLE
country.locale from sormas.properties ignored

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#1957]
### Bug Description
When specifying a default locale in sormas.properties, the ui language remains english

### Steps to Reproduce
1. specify e.g country.locale=de-DE
2. restart server
3. make sure the current user has no language set
3. check the ui translation

### Expected Behavior
UI should be translated

### System Details
* SORMAS version: 1.39.0

### Review
@sergiupacurariu

**Comment by MartinWahnschaffeSymeda** [comment]
Ideally we should also support the old format (en_NG)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] unit test
- [ ] make implementation more resilient

**Comment by HolgerReiseVSys** [comment]
I am not sure why 36e6c768c81e583d382502b1df5153e11bc3f5c7 has not been associated with the ticket.

**Comment by HolgerReiseVSys** [comment]
There is still quite some space for improvement.
The unit tests only cover some core aspects.

**Comment by MartinWahnschaffeSymeda** [comment]
Looks good. Also well documented.
