### ISSUE TITLE
Problem on hotfix-finish on local system

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1959]
### Bug Description
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project sormas-app: Execution default of goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke failed: Plugin org.fortasoft:gradle-maven-plugin:1.0.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.fortasoft:gradle-maven-plugin:jar:1.0.8 -> org.gradle:gradle-tooling-api:jar:5.4.1: Failed to read artifact descriptor for org.gradle:gradle-tooling-api:jar:5.4.1: Could not transfer artifact org.gradle:gradle-tooling-api:pom:5.4.1 from/to gradle (http://repo.gradle.org/gradle/libs-releases-local/): Authorization failed for http://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/5.4.1/gradle-tooling-api-5.4.1.pom 403 Forbidden -> [Help 1]

Trying the same with https works, but I have no idea where this is configured.

### Steps to Reproduce

My guess:

1. Remove the gradle tooling api pom from you local maven repository
2. Build the app using maven

### Review
@StefanKock

**Comment by markusmann-vg** [comment]
Start with an investigation and reproduction

**Comment by MartinWahnschaffeSymeda** [comment]
Access to  http://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/5.4.1/gradle-tooling-api-5.4.1.pom is working again. I guess the automatic redirect did not work.

Regardless of this we need to make sure we are only using HTTPS: https://blog.gradle.org/decommissioning-http

**Comment by MartinWahnschaffeSymeda** [comment]
Looks like the gradle-maven-plugin got this wrong:
https://repo1.maven.org/maven2/org/fortasoft/gradle-maven-plugin/1.0.8/gradle-maven-plugin-1.0.8.pom

```
<repository>
<id>gradle</id>
<url>http://repo.gradle.org/gradle/libs-releases-local/</url>
</repository>
```

**Comment by StefanKock** [comment]
That looks promissing. I assume in the meantime https is enforced by a lot of repo servers. 

Likely fix to `sormas-base/pom.xml` (not tested):
```
    <repositories>
        <repository>
            <id>gradle</id>
            <url>https://repo.gradle.org/gradle/libs-releases-local/</url>
        </repository>
    </repositories>
```

**Comment by MartinWahnschaffeSymeda** [comment]
```

	<pluginRepositories>
		<pluginRepository>
			<id>gradle</id>
			<url>https://repo.gradle.org/gradle/libs-releases-local/</url>
		</pluginRepository>
	</pluginRepositories>
```

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Please review and move to done, if the hotfix works out fine.
