### ISSUE TITLE
Web access for community and hospital informant [2]

### ISSUE THREAD

**Issue by juusotam** [hzi-braunschweig/SORMAS-Project#1960]
### Feature Description

Currently, hospital informant role has access only using mobile application. Adding web access for hospital informant would have benefits.

### Problem Description

MDM and MFA is needed for the informant role if spreading the use of the system to a wide range of private enterprises providing elderly care. This adds complexity and costs of the system. The required level of security could be achieved using web interface (+ 3rd party MFA).

### Proposed Change

Hospital informant role could access the system also using web interface. Access would be needed only to features add new case and edit own case?

**Comment by bernardsilenou** [comment]
@juusotam  A surveillance officer (SO) can use the web version. It is also possible to localized a SO to a health facility, in this situation, the SO will be equivalent to a hospital informant. Hope this can serve your purpose?
See attached picture
![image](https://user-images.githubusercontent.com/12996724/80869035-53fc8180-8c9e-11ea-88db-0a26eb7b6e3c.png)

**Comment by juusotam** [comment]
I tried to test this, but the SO role (with health facility set) has access also to other cases in that district. I would like to restrict the access to only cases within that particular health facility.

**Comment by bernardsilenou** [comment]
@juusotam this might be a bug, thanks for pointing that out. Maté must have solved it by now and all will be fine in the next release.
Thanks and sorry for that,

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Actually it's designed that way. An SO always has access to all data in the district. The health facility is just a way to help pre-select the health facility when creating cases, I think.

We should simply consider giving all users access to the web app and decide what implications it would have (e.g. what data would be visible on the dashboard).

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  I now understand you. I had a different thought in mind.
May be we just forget about the dashboard for now and give informants the web access as you suggested.

**Comment by MartinWahnschaffeSymeda** [comment]
Giving community level users access to the web app is also needed for #2267.

The dashboard currently only limits the data by district, so we should not show surveillance and contacts dashboard to those users.

Implementation:

- [ ]  give the following user roles access to the web app: COMMUNITY_INFORMANT, HOSPITAL_INFORMANT (see #1567 for reference)
- [ ] give COMMUNITY_INFORMANT the user right DASHBOARD_CAMPAIGNS_ACCESS
- [ ] Remove DASHBOARD_VIEW user right. Check for any of the other dashboard user rights instead (user should have access to the dashboard when he can see either surveillance, contact or campaigns dashboard and the related feature is enabled).

**Comment by MartinWahnschaffeSymeda** [comment]
As discussed in today's APMS meeting, this can be moved to post-pilot

**Comment by kwa20** [comment]
@MartinWahnschaffeSymeda Replying to your comment on #3433: The user rights for the specific use case would basically resemble the ones from the contact officer excluding the accessibility of cases. However this was a quite specific request. I don't know how exactly app users work with this role currently and changing the rights might influence this. I suggest that adjustments could better be handled by changing the userroleconfig. in the database for that specific case. The most important thing is the restriction down to the community level which will be available when this role gets access to the web app. I think the rest will also be taken care of by  #898 in the future.

**Comment by bernardsilenou** [comment]
@kwa20 The community informant as well as the hospital informant has the right to edit cases and this is one right we cannot take away from them i suppose. I think this needs is very specific and thus important that we push and implement  #2108 faster.

**Comment by kwa20** [comment]
@bernardsilenou denying users the right to edit cases is possible yet specific but could therefore be handled by userrightconfig. in the database as mentioned. The restriction to the community however cannot and is therefore relevant so health departments can accept help from community members that are not allowed to see outside of the community level.

**Comment by bernardsilenou** [comment]
@kwa20 Then lets push to refine and implement #2108 in the first sprint in January, hope this is fine?

**Comment by bernardsilenou** [comment]
I think its base on the boses:  @MartinWahnschaffeSymeda @MateStrysewske @markusmann-vg  to decide on the next steps

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou @kwa20 

Can you please specify what exactly needs to be done and then edit the issue description accordingly? I find it a little bit confusing. What I understood so far is mainly that a user role with Community-Level and Web-Access is needed.

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 @DavidBaldsiefen This issue is about granting access to the web app for Community Informants as well as Hospital Informants only. There won't be any adjustments to user rights or even additions of new user roles here. If anything like that is desired, there needs to be a follow-up issue.

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske The web access was surprisingly uncomplicated. However I checked back with the user and it appears as if the community/hospital informants Userrights won't be sufficient.

Apparently the required user rights would be

- listing cases & contacts in their community
- creating and sending quarantine documents & subsequently change the related quarantine order date
- Editing the case-person and contact-person

Creating new Cases and Contacts does not seem to be a requirement.

**Comment by bernardsilenou** [comment]
> @MateStrysewske The web access was surprisingly uncomplicated. However I checked back with the user and it appears as if the community/hospital informants Userrights won't be sufficient.
> 
> Apparently the required user rights would be
> 
> * listing cases & contacts in their community
> * creating and sending quarantine documents & subsequently change the related quarantine order date
> * Editing the case-person and contact-person
> 
> Creating new Cases and Contacts does not seem to be a requirement.
> 
> Edit: will be handled in #4290

@DavidBaldsiefen 
- What is need is more of a community surveillance officer and community contact officer user roles.
-  One question i can think of is that, the community is not a required field when creating entities. I a case does not have a community registered, then the community user would not have access to the case if it was reported by another user in the same community.
