### ISSUE TITLE
Add sample UUID to sample directory, sample view, sample export and case export [0.5]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1961]
### Situation Description
Currently, the samples menu does not display the local generated SORMAS sample ID to assist users differentiate between several collected samples of a single case. Using the sample ID generated in the lab is not sufficient, as in some nigerian labs, different samples of the same case can have the same ID while for other labs, different samples of the same case have different IDs
### Feature Description
There is a need for the samples menu on SORMAS  to display unique sample IDs for all samples created on the SORMAS platform  @Chinedar @hzi-old @bernardsilenou @MartinWahnschaffeSymeda

**Comment by bernardsilenou** [comment]
I think we need to display the field sample ID for sample in :
1, Sample directory
2, Sample tab while in a case. Maybe beside the case id, see figure attached

![image](https://user-images.githubusercontent.com/12996724/81007106-ee042b80-8e50-11ea-8491-a10641a5d496.png)

**Comment by bernardsilenou** [comment]
Show uuid for: case person, contact person, sample directory, sample information

**Comment by markusmann-vg** [comment]
in scope:
Show uuid for:  sample directory and single sample 

Please create another ticket for Person UUID

**Comment by Iheanacho2027** [comment]
Pls what's the update?

**Comment by bernardsilenou** [comment]
@Iheanacho2027 We would plan it for 1.54 please. It would be good to raise questions like this at the end of each last the sprint so that we can consider them when planning for the coming sprint. The best thing to do is just to provide a list of urgent issues one day before the review.

**Comment by Iheanacho2027** [comment]
I'll do a mail on specific requests. Thanks

**Comment by MateStrysewske** [comment]
I think this was supposed to be implemented already, but for some reason was missed, probably because it wasn't added to the sprint board. We'll take care of it in this sprint.

**Comment by MateStrysewske** [comment]
- [ ] Add the full UUID to the form
- [ ] Add the short UUID to the grid

**Comment by Iheanacho2027** [comment]
@MateStrysewske It's great. Can we also include in the export sheet for samples and cases if possible?

**Comment by bernardsilenou** [comment]
@kwa20 This is the issue. Please can you add a mockup today following the case form style

**Comment by kwa20** [comment]
<img width="655" alt="Screen Shot 2021-01-08 at 6 15 05 PM" src="https://user-images.githubusercontent.com/70317594/104044342-7e172380-51dd-11eb-9b61-121945bf2a53.png">

 @bernardsilenou Since we don't have a report date field for samples but display the date and time, I added it without the entry field option.

**Comment by bernardsilenou** [comment]
@kwa20 Nice desing! I deleted date of report  and shuffle things a bit. Please have a look if all is fine

![image](https://user-images.githubusercontent.com/12996724/104110334-0d543200-52d7-11eb-8795-642dead27a92.png)

**Comment by kwa20** [comment]
@bernardsilenou I'm not sure if we should remove date of report since it's also part of the initial phrase that is displayed on the form (cf. your screenshot in your first comment). I know that it's not a field that is entered manually but it might still be valuable information.

**Comment by bernardsilenou** [comment]
ahhh OK, i now see it. 
But samples do not have a report date. This may either be the system generated date or the date of report of the associated entity.
Please lets check what is this date before deciding.

**Comment by bernardsilenou** [comment]
Its the report date of the case.

**Comment by BarnaBartha** [comment]
@bernardsilenou Are you sure you want to remove the PURPOSE OF THE SAMPLE switch ?

**Comment by bernardsilenou** [comment]
> @bernardsilenou Are you sure you want to remove the PURPOSE OF THE SAMPLE switch ?

Maintain all variables please. I remove only "report date"

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest version of  SORMAS Version: 1.54.0-SNAPSHOT on the test environment
Verified the UuID is included in the sample view + sample directory+ export and also in the Case detailed export

**Comment by raghupola-vg** [comment]
Sample UUID's are now displayed on the mobile app. verified on latest build

**Comment by Iheanacho2027** [comment]
@bernardsilenou as discussed for the purpose of preventing test results duplicate. Can we include tests results UUID to the export and UI view. Sorry dev team that this is coming pretty late

**Comment by bernardsilenou** [comment]
New ticket needed

**Comment by MateStrysewske** [comment]
@Iheanacho2027 Adding pathogen test UUIDs to the grid wouldn't really be a good idea right now, I think. There's definitely not enough space for that, depending on the amount of pathogen tests for the sample with the most pathogen tests. In which way does this contribute to less duplicates being created?

**Comment by Iheanacho2027** [comment]
@MateStrysewske your point is very valid. It's actually needed for my proposal in #1154 based on discussions with @bernardsilenou . Could there be a better way around spotting duplicate pathogen tests?

**Comment by bernardsilenou** [comment]
@Iheanacho2027 you can use pathogen test variables: type of test +disease + date+time ......
When importing samples + pathogen test, these are the variables you have often, except you wan to export and importer the same thing, how does the uuid helps??

**Comment by Iheanacho2027** [comment]
Ok thanks.

**Comment by MateStrysewske** [comment]
@Iheanacho2027 @bernardsilenou I agree that the UUIDs actually don't help at all. What we will need - and this is also the case for the DEMIS adapter that we're currently building - is a functionality that is able to detect duplicate pathogen tests on import. Would this solve this problem for you?

**Comment by Iheanacho2027** [comment]
Can we have both options on board to compare and contrast?
