### ISSUE TITLE
Add CT value to positive PCR/RT-PCR pathogen tests

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1963]
### Situation Description
Currently there is no variable where lab users can input CT and CQ values to positive results of tests performed by PCR/RT-PCR as seen in lab results
### Feature Description
There is need for such a value, your inputs are needed @bernardsilenou @hzi-old @Chinedar

**Comment by bernardsilenou** [comment]
@Iheanacho2027  we had this request in the past not to only record CTvalues but Cq and and other test specific parameters. We decided to add the caption "specify test details" to handle stuffs like this.
Hope this is fair enough?

**Comment by Iheanacho2027** [comment]
@bernardsilenou that works then

**Comment by Iheanacho2027** [comment]
@chinedar @foyiri  pls look at this ticket created earlier

**Comment by Chinedar** [comment]
@Maté Strysewske <m.strysewske@symeda.de> Please let's have this variable
specifically for CT value entry. This can come as an open text for now.

**Comment by MateStrysewskeSym** [comment]
As CQ and CT values are the same, we don't need an additional field here, we only have to make the existing CQ value field visible for PCR/RT-PCR tests.
