### ISSUE TITLE
Change of date format to previous format before 1.39.0 [0]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#1964]
### Problem Description
The date format which previously used to be in dd/mm/yr on export has been changed to mm/dd/yr all in numbers.  This can alter the exported sheet if the date format settings of the user's system isnt in line with the date settings on SORMAS
### Proposed Change
Lets have a date export format of 1st-Mar-2020 and not 1/3/2020 or 3/1/2020 @MateStrysewskeSym  @MartinWahnschaffeSymeda 

<img width="170" alt="bug date" src="https://user-images.githubusercontent.com/50739609/80911804-91a9ea80-8d30-11ea-8f08-64ad501086c2.PNG">

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Change date format to dd/MM/yyyy for Nigeria and Ghana
- [ ] Consider using the short month name (three characters) for csv exports - make sure it works with excel

**Comment by Iheanacho2027** [comment]
Thanks @MartinWahnschaffeSymeda, pls can this be done in a hotfix, users in Nigeria are already complaining.

**Comment by markusmann-vg** [comment]
scope of the ticket:
- [ ] Change date format to dd/MM/yyyy for Nigeria and Ghana
