### ISSUE TITLE
Change date month format in export

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1966]
Proposed by @Iheanacho2027:
Lets have a date export format of 1st-Mar-2020 and not 1/3/2020 or 3/1/2020

- [ ] Consider using the short month name (three characters) for csv exports - make sure it works with excel

_Originally posted in https://github.com/hzi-braunschweig/SORMAS-Project/issues/1964_

**Comment by markusmann-vg** [comment]
we should keep the dd/MM/YYYY format also for export. 
If the shortcut for months is needed, it can easily be done with excel by selecting the columns and change to a custom date format. So it is easy to change 30/04/2020 to 30. April 2020 or others

**Comment by JaquM** [comment]
@MartinWahnschaffe as long as we now can import different date forms, can we close this one?

**Comment by MartinWahnschaffe** [comment]
I think based on the work we did here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3453 this one can be closed.
