### ISSUE TITLE
Allow PIA to inform SORMAS about the status of a contact person in PIA

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1970]
### Situation Description

Extension for #1669

### Feature Description

- [x] ReST interface should receive the following information:
   - UUID of the person
   - Status: PIA account created, account deleted
- [x] Store the status of the PIA account for the contact person

Do we really need account created? This could also be handled within the iframe #1669 
Do we need any other information (e.g. reason for the account deletion)?

**Comment by markusmann-vg** [comment]
Where do we show the PIA status in SORMAS?

**Comment by MartinWahnschaffeSymeda** [comment]
I think we should show it within each contact. The same place we want to display the PIA iframe.

**Comment by o-frietsch** [comment]
Final interface specification:

HTTP-Request
------------
	Endpoint: /sormas-rest/visits-external/contact/[contactUuid]/status
	Method: POST

	URL example: http://localhost:6080/sormas-rest/visits-external/contact/S3CJF2-Y7SCJZ-NQVERG-43CGCDL4/status

	Body example:

		{
			status: “REGISTERED”,
			statusDateTime: "2020-04-15T12:55:00.000+02:00" // datetime format yyyy-MM-dd'T'HH:mm:ss.SSSZ
		}

HTTP-Response:
--------------
	returns boolean literal

		"true" - if contactUuid was valid and status was set
		"false" - otherwise

Possible status codes:
----------------------
	UNREGISTERED: User has not yet sent any state (never sent by PIA, just internal state in SORMAS)
	REGISTERED: After succesfull registration in PIA
	ACCEPTED: User has accepted the In-App confirmation
	REJECTED: User has rejected (declined) the In-App confirmation
	DELETED: User was deleted in PIA (=UNREGISTERED?)

PIA ensures following status changes:
-------------------------------------
	UNREGISTERED -> REGISTERED -> DELETED
	UNREGISTERED -> REGISTERED -> ACCEPTED or REJECTED -> DELETED

**Comment by o-frietsch** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/2083 for UI extensions.

**Comment by o-frietsch** [comment]
The above spec has also been transmitted by email some days ago, this is the same spec.

**Comment by FredrikSchaeferVitagroup** [comment]
I have a question regarding the specification: Is it correct that the contactUuid shall be used here? Don't we use the personUuid?

**Comment by o-frietsch** [comment]
Yes. Sorry, this might be somewhat mixed up on our side, because that ID changed over the time and from our point of view, it's just an ID of whatsoever.

**Comment by FredrikSchaeferVitagroup** [comment]
I have adapted the interface specification to match the personUuid instead of the contactUuid. I've also slightly adapted the format, so it can be handled properly by our interface.

**Comment by Candice-Louw** [comment]
@FredrikSchaefer - would it be possible to have a description of where one would be able to see the state [UNREGISTERED -> REGISTERED -> ACCEPTED or REJECTED -> DELETED] of the Contact Person pertaining to their PIA account status in the SORMAS UI, please?

**Comment by o-frietsch** [comment]
I wrote a feature request for that, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/3037
