### ISSUE TITLE
Date format in Finnish locale

### ISSUE THREAD

**Issue by juusotam** [hzi-braunschweig/SORMAS-Project#1979]
### Bug Description

Date format in 1.39.0 in Finnish locale is wrong: m.d.Y. 

### Expected Behavior

Should be same as in German locale (d.m.Y)

### Screenshots

<img width="809" alt="Screenshot" src="https://user-images.githubusercontent.com/1386805/81135919-9fdf4d00-8f62-11ea-83da-81d1e6503a76.png">

### System Details
* Device: Web
* SORMAS version: 1.39.0
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@juusotam Sorry about that. We recently added explicit date formats to every language in the code, but things got mixed up there. Will be fixed in the next version.
