### ISSUE TITLE
Mobile App update to 1.39.2 fails. Adb logs attached

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#1980]
### Bug Description
App Download fails when trying to update from 1.39.0 to 1.39.2

### Steps to Reproduce
Pre-Requsite:  Make sure current mobile app is running on 1.39.0
1. Open the mobile app
2. App update pop up appears with an option to download or skip. Select Download and see if the download is successful.

### Expected Behavior
App update has to be downloaded and installed to latest version

### Screenshots
![App download Failed](https://user-images.githubusercontent.com/62763628/81149461-8c41df80-8f7e-11ea-8203-aa0f5efe5cbd.png)

### System Details
* Device: Samsung S 10
* SORMAS version: 1.39.0
* Android version/Browser: Android 10

### Additional Information
Note: App can still be used without the necessary of updating to latest version.
Adb logs attached here. 
[appupdateFailedto 1.39.2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4585411/appupdateFailedto.1.39.2.txt)

**Comment by StefanKock** [comment]
I assume you tried to download it from sormas.symeda.de. I forgot to provide the new apk file there. It should work now.
