### ISSUE TITLE
Add Trimester and Postpartum selection to case [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#1981]
### Situation Description
Currently, in case information, we have an option to select yes, no, unknown for pregnancy. 
As the survnet interface also considers the trimester, we should enable the users to also select this, when pregnancy is selected with "yes"

### Feature Description
Pregnancy as a conditional question, when yes is selected another 4 options should be shown with 1st, 2nd, 3rd trimester plus another described field which is Postpartum   (weniger als 6 Wochen). It is not mandatory to add this. Selecting and Deselecting should be possible. When changing the pregnancy status to no or unknown again, the trimester selection should be removed.

### Additional Information

![trimester](https://user-images.githubusercontent.com/62540178/81161144-61aa5380-8f8b-11ea-9f29-6ab8765ce117.png)

### Review

@leventegal-she

**Comment by MartinWahnschaffeSymeda** [comment]
I think we also have to add "Postpartum (weniger als 6 Wochen)" here, when pregnancy is true (it's the period immediately after birth).
It's need for the SurvNet interface.

@markusmann-vg Please double-check
@bernardsilenou @max-hzi Should other countries also see those two fields?

**Comment by ChristopherRiedelSymeda** [comment]
Result from the Planning:
- [ ] Add postpartum as additional field
- [ ] Values for Trimester: First, Second, Third, Unknown
- [ ] Values for Postpartum; Yes, No, Unknown

**Comment by MartinWahnschaffeSymeda** [comment]
@ChristopherRiedelSymeda If possible add postpartum on the right side of pregnancy. Postpartum should follow the same visibility rules as pregnancy (e.g. female only).

**Comment by MateStrysewskeSym** [comment]
- [ ] use setVisibleWhen instead of the custom handleTrimesterField method
