### ISSUE TITLE
Improve handling of release zip file and documentation

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#1982]
### Bug Description
Version 1.39.2 is zipped into additional folder. 
When unzipping as described in the server installation manual, all files end up in 
/root/deploy/sormas/$(date +%F)/**deploy**/
Then the server-update.sh is looking in the wrong (right) folder and does not find the files. 
### Expected Behavior
unzip into: 
/root/deploy/sormas/$(date +%F)
### System Details
* Device: ubuntu 20.04
* SORMAS version: 1.39.2

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender The additional deploy folder has been in the zip files for a long time (possibly since forever, actually). Nothing has changed about that.

However, it probably makes sense to get rid of it because it's redundant.

**Comment by StefanKock** [comment]
I think we should not change the packaging to have everthing in the zip root. When unpacking Zulu or Payara you also do not have it exploded.
So maybe the documentation should be clarified.

**Comment by markusmann-vg** [comment]
- [ ] Fix the documentation & Scripts

**Comment by MartinWahnschaffeSymeda** [comment]
Looks like the relevant part of the documentation is a bit vague: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_UPDATE.md#preparations

Suggestion: 
- [ ] Add a command to the documentation on how to download the zip to the server (wget)
- [ ] Add a command on how to extract the zip file in a way that makes sure the script can be executed as described. Something based on `unzip <target-zip-file> '<folder-to-extract/*>' -d <destination-path> `

**Comment by StefanKock** [comment]
I tried to use the approach with `-d <destination-path>` but the selected files where then nested in `destination-path` and then as inside the zip file (so the `deploy` directory did not disappear like this).

**Comment by MartinWahnschaffeSymeda** [comment]
Review: I think the solution is good. wget does not work on windows git bash, but since it's not part of an automatic process we can ignore this from my point of view. Windows users will most likely manually download and move the files anyway.

**Comment by StefanKock** [comment]
Waiting for release 1.45.0 to be finished.

**Comment by StefanKock** [comment]
Merged to `development`.
