### ISSUE TITLE
Add Pashto and Dari languages to SORMAS [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#1985]
### Situation Description
The languages are already present on crowdin, with no translation being done yet.

### Feature Description
Add the languages to SORMAS.
Also add en-AF for custom wording. Use "cluster" as translation for community.

### Additional Info

- [ ] Check wether the csv. export for translation is working // If not => create follow-up issue to fix it

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba What date format should be used for both languages?
For english the default language format is currently M/d/yyyy (different from Nigeria and Ghana).

**Comment by MartinWahnschaffeSymeda** [comment]
Problem that we will need to solve: For APMS we only need a subset of the translations. How can we let the translators know which fields are relevant?

**Comment by bernardsilenou** [comment]
no idea men

**Comment by AndyBakcsy-she** [comment]
Verified the existence of the new languages on the latest Sormas Version 1.55.0.Snapshot.
Some translations have not yet been completed/implemented:
![image](https://user-images.githubusercontent.com/70562142/107063460-15729500-67e3-11eb-9182-3eb29a8dc824.png)
