### ISSUE TITLE
Allow custom logo and labeling with "powered by SORMAS" [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1987]
### Situation Description
Currently SORMAS already comes with the option to have a custom login page and a custom side bar.

### Feature Description
Allow server instances to use a custom logo on the login page and the side bar of the web app.
When this customization is used enforce a "powered by SORMAS" sub header.

### Additional Information
This will not include a custom logo for the mobile app.

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba Can you provide drafts of how the login page and the web app side bar shall look like for APMS, please?

**Comment by MateStrysewskeSym** [comment]
@danieltomaba Still waiting for mockups for these changes!

**Comment by hzi-old** [comment]
![image](https://user-images.githubusercontent.com/19344651/86015391-8224e600-b9ef-11ea-98bc-9b88a242dfd1.png)

**Comment by hzi-old** [comment]
![6424FD9C-2CD1-4003-82D8-2E6445317AFD](https://user-images.githubusercontent.com/19344651/86015450-949f1f80-b9ef-11ea-90ee-9c18a89e2558.jpeg)

**Comment by hzi-old** [comment]
@markusmann-vg @MateStrysewskeSym

**Comment by MateStrysewskeSym** [comment]
@hzi-old Please send me a mail with the new logo you want to be included

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove the GIZ logo from Powered by when the name of the server is "APMS"

Wait for input by HZI whether the vitagroup and HZI logos should be removed as well

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Please send email to Juliane and Gérard to decide

**Comment by hzi-old** [comment]
@bernardsilenou @MateStrysewskeSym I have sent the email to Gerard. Waiting for response. This is important. I think its a good idea to have powerd by SORMAS and make a linkable to another page that shows all the partners and developer companies etc. I have recieved the same complaint from Ghana as well. Now afghanistan POCs dont want to have all those companies on their front page because its should be a government platform not visible that other companies are involved else they think their data is giong out of Afghanistan.

I will get back to you guys once Gerard responds.

**Comment by bernardsilenou** [comment]
@hzi-old That is a good point. What about putting the logo at the lower right corner with 1/4 its normal size so that it it not too visible. Have a look at this one:
![image](https://user-images.githubusercontent.com/12996724/86297388-7a399180-bbfb-11ea-97f5-e7830cf15eb0.png)

**Comment by hzi-old** [comment]
@bernardsilenou @MateStrysewskeSym This is exactly my point. CDC and other partners are used to these kinds of "powered by" and "designed by" with 1/4 of the size of the login page. What we currently have for SORMAS is really shouting and the afghanistan folks do not like the way it is taking over the whole page. or even half a page. Lets make use of the footer section and integrate our poiwerby and designed by information. Please.

**Comment by MateStrysewskeSym** [comment]
@hzi-old This will take longer then, because it essentially means we have to redesign the whole login page.

**Comment by Candice-Louw** [comment]
Initial feedback from Gérard, per email: Mon, 06-Jul-20, 16:23

"Dear colleagues
The SORMAS for Afghanistan should NOT have any GIZ, NCDC, GHS, BMZ, EU or GCNET logos visible."

**Comment by MateStrysewskeSym** [comment]
For custom branded systems:

- [ ] Push the "powered by" section to the bottom of the sidebar
- [ ] Display the default logos in a smaller size and two in a row

**Comment by Khaliqiii** [comment]
Dear sir/ Madam 
Hope this email finds you well.
My name is Romal khaliqi. I worked for GIZ department as a Assistant in separate task positions. So now I am in danger of taliban. Could you please help me.
