### ISSUE TITLE
Vaccination campaign form data entry [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1993]
### Situation Description

Based on #1991 and #1992 we have a definition of the campaign form and are able to create a new instance and persist the data.

### Feature Description

Create a partly dynamic data entry form based on the CampaignFormDefinition and the mockup in #1989 

This will be a sub section of the "Campaigns" view in SORMAS (see #1984). 

TODO: define more details

**Comment by MateStrysewskeSym** [comment]
Title of popup window to create new form should include the name of the form

**Comment by MateStrysewskeSym** [comment]
- [ ] Add internationalisation support

**Comment by MateStrysewskeSym** [comment]
- [ ] Add creating user

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Add a caption and it's translation to the form.

**Comment by MateStrysewskeSym** [comment]
- [ ] Replace form name in error messages with form ID
- [ ] Fix copyright hint in CampaignsView
