### ISSUE TITLE
Use full path in server-setup.sh

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#1995]
### Situation Description
Currently, in the payara part, there are some relative parts in the server-setup.sh script. As a consequence, when you run it from another directory than
**/root/deploy/sormas/$(date +%F)**
you will get the following errors: 
cp: cannot stat 'sormas.properties': No such file or directory
cp: cannot stat 'start-payara-sormas.sh': No such file or directory
cp: cannot stat 'stop-payara-sormas.sh': No such file or directory
cp: cannot stat 'logback.xml': No such file or directory
cp: cannot stat 'loginsidebar.html': No such file or directory
cp: cannot stat 'logindetails.html': No such file or directory
cp: cannot stat 'demologinmain.html': No such file or directory
cp: cannot stat 'payara-sormas.sh': No such file or directory

However, this directory belongs to root. And as there is no "**sudo cd ...**"
the installation process must run on root (that is disabled on some linux distros). 
So you have to type **sudo su** first. 
Alternatively you could give r-x permissions to the user for all the folders, but this isn't clean and safe. 
### Feature Description
I suggest to use full paths in the sh file so the script can run from everywhere.

**Comment by jabrandes** [comment]
@RafaelKluender, I would like to raise the question why one would want to copy the `server-setup.sh` to somewhere outside the deployment directory. As long as the deployment files are located in the same directory, relative paths should ensure that the setup script knows where to find all the other setup-related files. To my knowledge, the current `server-setup.sh` script installs the server to a base directory specified by absolute path, such that it should be no problem to just move the whole deployment directory if you want to do so.

**Comment by JaquM** [comment]
@RafaelKluender is there still a need for this issue, or can we close this one?
