### ISSUE TITLE
Export entered campaign form data [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1998]
### Situation Description
See #1997 

### Feature Description
It should be possible to export from the list of campaign data (#1997).

- [x] Add an export button to the campaign data list view
- [x] Export the data from the grid as-is, using the GridExportStreamResource (see CasesView)
- [x] Add the soft-required style to the campaign and form filter in the view (see CssStyles.java)
- [x] Add a switch (ComboBox) to the filters to select between "important" and "all columns" (see image below). The switch should be disabled when no form is selected in the filter. It should have a description that says "select which form fields to show, when the list is filtered to a single form."
- [x] Extend the CampaignDataView.createFormMetaChangedCallback to show either only important fields (that's what it is currently doing) or all fields.

![grafik](https://user-images.githubusercontent.com/23217632/89789811-6568eb80-db21-11ea-9d6b-b9483725c632.png)

**Comment by BarnaBartha** [comment]
As discussed with Daniel by default when selected a form we want to show all columns.

**Comment by MateStrysewske** [comment]
Additional request:

- [ ] Allow users to export diagrams to CSV
