### ISSUE TITLE
Import campaign form data [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1999]
### Situation Description
See #1997 and #1998 

### Feature Description
Similar to importing cases and contacts it should be possible to import a csv file with data for one campaign form.
A template that defines the needed format should be downloadable as-well.
Allow custom mappings for yes and no defined in the system or for the imported form (e.g. in the compilation sheets we have seen YES = 1 and NO = 2).

**Comment by MateStrysewske** [comment]
Steps that need to be done for this:

- [ ] Create a CampaignDataImporter class that extends DataImporter
- [ ] Add a generateCampaignDataImportTemplateFiles method to CampaignFormDataFacade
- [ ] The template generation method should generate one file per CampaignFormMeta entity that includes the default meta fields and one column per field defined in the JSON definitions
- [ ] In the UI, users must choose which form they want to import before the import dialog opens (use a dropdown menu just like the one used to create new form data)

**Comment by markusmann-vg** [comment]
It should be possible to export campaign form data, make changes and (re-)import the same file

**Comment by MartinWahnschaffeSymeda** [comment]
One addition: 

- [ ] A user should only be allowed to import data for his own jurisdiction (e.g. a surveillance supervisor only for his own region).

**Comment by MateStrysewske** [comment]
@markusmann-vg That request is out of scope for this issue because it's generally not possible right now, for none of the imports we currently have.

**Comment by danRosca** [comment]
- [ ] validate imported data using the defined type of the form field

**Comment by MartinWahnschaffeSymeda** [comment]
@danRosca One issue that was just discovered: The import popup still has the caption "import contacts". Instead it should be "Import campaign form data".
