### ISSUE TITLE
Mobile vaccination campaign form data entry [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#2001]
### Situation Description
Data entry only exists for web app #1993. Data is synced to the mobile device #3151 and displayed in a list #3161.

### Feature Description

- [x] Add area support to mobile app 
- [x] Create a campaign data activity that will be used to edit and create campaign data
  - [x] Allow the user to select an entry in the campaign data list to open existing campaign data
- [x] Build a fragment that contains the fixed fields that are used by each form: campaign, date, region, etc. (see UI for comparison)
- [x] Retrieve the CampaignFormMeta for the form from the backend
- [x] Dynamically add the needed fields to the fragment (e.g. https://stackoverflow.com/a/38404838). 
  - [x] Fields should just be one per line (in contrast to the implementation of the UI)
  - [x] Fill the fields with the existing data (field binding would be great)
  - [x] Make sure the enter data is saved correctly
- [x] Allow the user to create a new campaign data from the list (+ button in the top right)
  - [x] user will have to pick one of the forms available for the campaign when doing so. This could probably best be done in a popup

**Comment by MartinWahnschaffe** [comment]
- [ ] Initial sync of areas leads to corrupt data
- [ ] Open the campaigns view when user does not have access to cases/contacts, but campaigns. Use settings as fallback when user does not have any access
- [ ] display information on campaign, form, community and date of conflicting form, so the user is able to identify it
- [ ] either: don't display differing json string at all OR build a diff using https://github.com/google/diff-match-patch/tree/master/java and display to the user how the data he entered was changed by the server (additions and removals to the json string)
- [ ] make sure campaign form data list does not contain entries with null values (e.g. {"id":"supervisorName"} should be removed, {"id":"supervisorName","value":"Test"} has to stay)

**Comment by StefanKock** [comment]
@BarnaBartha dropped development and will pick up again in the next sprint.

**Comment by BarnaBartha** [comment]
- [ ] fix empty checkbox dependency issue
- [ ] comment text field not showing on edit form
- [ ] synchronisation from mobile to server failed!

**Comment by MartinWahnschaffe** [comment]
@BarnaBartha Looks like available campaign form metas are not taken from the campaign, but instead by going through the existing entered campaign data forms. This needs to be changed. It currently means that a user is only able to create campaign data for those forms that have been used before.

- [ ] make sure campaignFormMeta is properly synced
- [ ] Use it instead of the current implementation in CampaignFormMetaDao.getAllFormsForCampaign
