### ISSUE TITLE
Provide temporary demo server for vaccination campaign management

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2002]
To support the development for the SIA module for SORMAS, we need a dedicated demo server.
This server should ideally be setup with infrastructure that matches the Polio vaccination campaign scenario in Afghanistan.

**Comment by MartinWahnschaffeSymeda** [comment]
https://test-afghanistan.sormas.netzlink.com/

Next step: Define how the server is supposed to be configured based on https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_CUSTOMIZATION.md

**Comment by MartinWahnschaffeSymeda** [comment]
Configuration of properties:

- Default locale (country.locale): en-AF
- EPID prefix (country.epidprefix): AFG
- Country center/zoom (country.center.latitude, country.center.longitude and map.zoom): To the center of Afghanistan with zoom of 8
- Dev mode (devmode): true
- All other properties set to default values / what is needed based on the server environment (e.g. R, temp paths, etc.)

Database configuration

- Disease configuration can stay as-is
- Feature configuration: Disable AGGREGATE_REPORTING, EVENT_SURVEILLANCE, WEEKLY_REPORTING, CLINICAL_MANAGEMENT. More features will need to be disabled once this is implemented

Users: We just go with the default users. Please use the demologinmain.html template for the login page (has to be put into the sormas custom folder on the server using the name loginmain.html).

@danieltomaba Can you provide the latest data for the Afghanistan provinces (regions in SORMAS), districts and if available clusters (community in SORMAS)?
What about health facilities?

**Comment by MartinWahnschaffeSymeda** [comment]
@asohh 

Configuration of properties:

- Default locale (country.locale): en-AF
- EPID prefix (country.epidprefix): AFG
- Country center/zoom (country.center.latitude, country.center.longitude and map.zoom): To the center of Afghanistan with zoom of 8
- Dev mode (devmode): true
- All other properties set to default values / what is needed based on the server environment (e.g. R, temp paths, etc.)

Database configuration

- Disease configuration can stay as-is
- Feature configuration: Disable AGGREGATE_REPORTING, EVENT_SURVEILLANCE, WEEKLY_REPORTING, CLINICAL_MANAGEMENT. More features will need to be disabled once this is implemented

Users: We just go with the default users. Please use the demologinmain.html template for the login page (has to be put into the sormas custom folder on the server using the name loginmain.html).

@danieltomaba Can you provide the latest data for the Afghanistan provinces (regions in SORMAS), districts and if available clusters (community in SORMAS)?
What about health facilities?

**Comment by asohh** [comment]
We configured the server

**Comment by hzi-old** [comment]
https://drive.google.com/drive/folders/1M15aLTWrrOgUfqbeoU5V_4tFyrVgNeV1 for WHO admin 2 and 3 for Afghnistan adminstrative level units
[fwdwhopolioadminshapefiles.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4724257/fwdwhopolioadminshapefiles.zip)
[GLOBAL_ADM0.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4724258/GLOBAL_ADM0.zip)
[rewhopolioadminshapefiles.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4724261/rewhopolioadminshapefiles.zip)

**Comment by MartinWahnschaffeSymeda** [comment]
I have moved the infrastructure part to another issue.
