### ISSUE TITLE
Only have actuall differences in sub-translation files (crowdin)

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#2006]
### Feature Description
The localization of SORMAS uses property files that have a lanugage tag (e.g. captions_en.properties) and optionally also a sub tag (e.g. captions_en-NG.properties). The file with the sub tag can define country specific differences in the localization. For example districts are called LGA in Nigeria.

### Problem Description
When using crowdin for a sub-translations, those currently contain the complete translation.
We need to make sure that this works as expected when there is also a translation without sub tag available.

### Proposed Change
Put en-NG on crowdin and see how it works.
If the default behaviour is not that it only contains the actual differences we need to ask the crowding team on how to achieve this.

**Comment by JaquM** [comment]
@MartinWahnschaffe is there an update on this issue or still the need?

**Comment by MartinWahnschaffe** [comment]
en-NG and others are on crowdin meanwhile and seem to work. As far as I can tell there are some unnecessary duplicates in some of sub files, but that's not something that needs to be addressed here.
