### ISSUE TITLE
"Mockup" process on how to get SIA data from Excel into SORMAS [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2011]
### Situation Description
The SIA campaigning in Afghanistan takes place in a lot of regions that don't have data connectivity and don't allow usage of mobile phones.
Thus we need to allow users to enter data into Excel forms and then get this data into SORMAS.

### Feature Description
Create an example template for at least one data entry form and define how data would be entered by users and how it would be imported into SORMAS.

See #1999

**Comment by MartinWahnschaffeSymeda** [comment]
Example CSV files for the team monitoring form (comma for en systems):

[TeamMonitoringSemicolon.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4747106/TeamMonitoringSemicolon.txt)
[TeamMonitoringComma.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4747107/TeamMonitoringComma.txt)

**Comment by MartinWahnschaffeSymeda** [comment]
Questions:

1. Who would use the import option. What is a typical use case?
2. What data forms are those users currently using? E.g. is there an aggregated version of the team monitoring form?

**Comment by danieltomaba** [comment]
@MartinWahnschaffeSymeda 
1. The provincial level officers are the key users of the import option when they have data alot of existing data from the different districts already existing in excel. So they will put the data into a csv format and bulk import into the system.  However, an admin level officer at the national level should be able to import retrospective data at any point in time for any SIA period

2. They are using the aggregated version of the monitoring forms which are in excel by clusters. Remember, the paper forms are used from teams, clusters and compiled forms are sent to the districts which are now sent by districts to the provinces where they are entered into excel.
