### ISSUE TITLE
Date format / date caption not congruent

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2019]
### Problem Description
I've been running into the Issue that the date entry fields and captions do not fit to each other (see screenshot) in Sormas for Germany. I would rather have the fields re-arragend to dd-mm.yyyy than making an incorrect translation to match the fields.

### Possible Alternatives
Very welcome.

### Screenshot
A screenshot from case creation. The same issue is also on CASE PERSON, CONTACT PERSON.
![Unbenannt](https://user-images.githubusercontent.com/63781233/81384377-deffd080-9111-11ea-8834-3e8cf8254cd8.PNG)

**Comment by MateStrysewskeSym** [comment]
@max-hzi My initial feeling is that re-arranging the fields based on the date format might be a little bit too much work for now. It's definitely easier to change the caption, even if the order in which the dates are specified isn't really intuitive for German users. Do you think that would be a huge problem?

**Comment by max-hzi** [comment]
No, not a problem at all. Just looking for a clean solution. But I get your point. Shall I adjust the translations in crowdin then?

**Comment by MateStrysewskeSym** [comment]
@max-hzi I'd say so :)

**Comment by max-hzi** [comment]
Done.
