### ISSUE TITLE
Add (district, region) community filter to case  directory [0.5]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2021]
German health departments are increasingly asking for community/ Gemeinde-filter.

### Situation Description
Region and discrict filters are availible in the contact directory, but not in the case directory. A community filter is missing in both directories, but needed by German health departments.

### Feature Description
Add community filter to the case and contact directory. Also introduce region and district to the case directory.

### Possible Alternatives
Open to suggestions.

### Additional Information
Edit: Medium to high priority. Thank you.

**Comment by MartinWahnschaffeSymeda** [comment]
@max-hzi The district and region part of this already exists for cases. It's within the "show more filters" section.

**Comment by max-hzi** [comment]
Oh, correct, thank you. I did oversee this in cases because of the arrangement. Still missing the lower tier community.

**Comment by bernardsilenou** [comment]
Since community is not a required field in creating cases, I think we should limit the filtering options to districts because when filtering by community, the cases without community will be omitted.
@max-hzi if you agree with this then we can close the issue

**Comment by max-hzi** [comment]
@bernardsilenou No, I can't agree with this. The German health departments are explicitly asking for this. 

I am sure that those health departments which work on the community level barely have missings. They need the filter because larger districts/ Landkreise have multiple teams, each of which in charge of a certain community. The filter would considerably facilitate follow-up.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Just because certain cases might not have a community assigned doesn't mean we shouldn't include such a filter, I totally agree with Max here. I've already put it in the short-term roadmap.

**Comment by leventegal-she** [comment]
The community filter will not be added on the contacts directory as there is no direct link between contact and community right now.

**Comment by max-hzi** [comment]
Why not use the community as seen in "contact person"?

**Comment by MartinWahnschaffeSymeda** [comment]
I think this would be confusing, because all of the jursidiction filters are currently based on the responsible region/distrcit/community within the case/contact. Not the jurisidiction of the address of the person.

We could use the community of the case of the contact (if existent) to filter in the contacts directory.

**Comment by max-hzi** [comment]
OK, this is indeed a valid point. 

If we would use the community of the index case this might be problematic, as some contacts are created without case and still need to be filtered by community. What would we suggest the health departments to do?

**Comment by MartinWahnschaffeSymeda** [comment]
Hm. Good point. From my point of view region and district within the case/contact define the responsible jurisdictions.

Would it make sense to have a responsible community? If so, we could add this to the contact. If not we should think about removing the community from the case and instead allow users to filter cases and contacts based on the community in the persons address.

I'd prefer to add an optional responsible community to the contact.

@max-hzi @MateStrysewskeSym @bernardsilenou @Chinedar What do you think?

**Comment by MateStrysewskeSym** [comment]
I second your opinion.

**Comment by max-hzi** [comment]
> I'd prefer to add an optional responsible community to the contact.

I think this is a very good solution!

> In any case we should probably change the caption of the region and district of the case to "responsible region" and "responsible district" to more clearly seperate this from the address of the person.

Yes, this would be very helpful as well. Thank you.

**Comment by Chinedar** [comment]
I agree with Martin's opinion and approach.

**Comment by bernardsilenou** [comment]
@ All: Sorry for not commenting for long.
I agree with Martin also.
I have a worry  about the fact that the top page of line listing view fro cases and contacts is getting overcrowded because each user needs a different kind of filter.
@MartinWahnschaffeSymeda & @MateStrysewskeSym : Is it not possible to have something like a drop down "MORE" where we can all the filters that are useful to a subset of users?

![image](https://user-images.githubusercontent.com/12996724/81872831-dd536400-957a-11ea-8411-ff6a642e18a0.png)

**Comment by max-hzi** [comment]
@bernardsilenou Sorry for jumping onto this, but I think we should keep all filters in one place. Maybe the filters could be reorganised if they become overwhelming. IMO they are OK for now.
Also, this 'more' drop-down menu is not available contact/ case supervisor.

**Comment by MartinWahnschaffeSymeda** [comment]
Moved the part for the contact to a new issue #2104
