### ISSUE TITLE
Post campaign indicator: Reasons of failed lots from failed lot investigation 

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#2051]
Reasons of failed lots from failed lot investigation

**Comment by JaquM** [comment]
@MartinWahnschaffe is there still a need for this issue or can we close this one?

**Comment by MartinWahnschaffe** [comment]
@Candice-Louw @danieltomaba I think we should close this and the other pre/post campaign indicator issues. It doesn't make sense to have github issues for this anyway, because it's something that has to be done in the form/dashboard meta definitions on the specific country server.

**Comment by Candice-Louw** [comment]
Ticket closed - server related request not relevant for GitHub.
