### ISSUE TITLE
Add a column in case and contact table to distinguished imported and non imported cases and contacts and sample,  ,,,

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2052]
### Situation Description
Users want to be able to separate cases and contacts imported from those created manually (Creation mode). 
Ad a front end variable (Creation mode) to allow user to filter cases and contacts

**Comment by MateStrysewskeSym** [comment]
I'd rather have filters than columns in the directories because we don't really have the space for such information that's probably only relevant for a small amount of users. Is that fine for you?

**Comment by JaquM** [comment]
@bernardsilenou  is there still a need for this, or can we close this one?

**Comment by bernardsilenou** [comment]
This need has not been requested by more users, thus would close it.
