### ISSUE TITLE
Also consider indirectly dependent objects when determining when a case was last updated [0.5]

### ISSUE THREAD

**Issue by stefanspiska** [hzi-braunschweig/SORMAS-Project#2059]
### Feature Description
Right now the `{sormas_url}}/cases/all/{since}` endpoint uses the change dates of the directly dependent Objects:
`case; symptoms; hospitalization; ...`  to calculate which cases to return.
### Problem Description
For the survNet Interface it is  needed to also use  the change dates of `patient; sample; pathogentests` . Thus if for example a Patient dies the SurvNet Interface can sent an update.  

### Proposed Change
Either :
- ~~change the current Endpoint include the above objects in its calculation~~
- add a query parameter to the current which controls if the above objects are included  in its calculation
- => add a new Endpoint which works like the old one plus includes the above objects in its calculation
 
### Review
@MateStrysewskeSym

**Comment by HolgerReiseVSys** [comment]
Which of the proposed solutions has been implemented?
Has a new endpoint been implemented? If so, what is its signature?

**Comment by MateStrysewskeSym** [comment]
@sergiupacurariu Please note down your solution in one or two sentences here.

**Comment by sergiupacurariu** [comment]
**Resource description** - returns a list of all cases changed after a given date. 
**Endpoint definition** - "{sormas_url}/cases/allWithExtendedChangeDateFilters/{since}"
**Parameters** - {since} - the milliseconds since January 1, 1970, 00:00:00 GMT.
**Request example** - GET @ "HTTP://localhost:6080/cases/allWithExtendedChangeDateFilters/1591336055381"
**Response example and schema** - 
[
  {
    "creationDate": 1591336254519,
    "changeDate": 1591336255275,
    "uuid": "R2QGG5-WUJEI5-XWHNLY-AC2KCIZU",
    "disease": "EVD",
    "person": {
      "uuid": "R6GYDK-YKC4SC-XSI5D2-6ZMMSMRU",
      "caption": "Case PERSON"
    },
    "epidNumber": "COU-REG-DIS-20-001",
    "reportDate": 1591336250275,
    "reportingUser": {
      "uuid": "SQSHQP-DWGRPO-Y7WWQ5-UCTWCO4Q",
      "caption": "Surv SUP - Surveillance Supervisor"
    },
    "caseClassification": "PROBABLE",
    "investigationStatus": "PENDING",
    "outcome": "NO_OUTCOME",
    "region": {
      "uuid": "WHF6KA-GC6BIB-3E3LWZ-JUTCCJZQ",
      "caption": "Region"
    },
    "district": {
      "uuid": "UYQY7I-SGDP2C-DE2D2F-KLORKBJM",
      "caption": "District"
    },
    "community": {
      "uuid": "XYRCHJ-PBDYMG-KXJZIQ-36J6KGM4",
      "caption": "Community"
    },
    "healthFacility": {
      "uuid": "TAPC6O-6PBWRO-B23CMM-FJG2SCNU",
      "caption": "Facility"
    },
    "hospitalization": {
      "creationDate": 1591336254520,
      "changeDate": 1591336254520,
      "uuid": "UVJE4W-PXNXIA-OFNKHY-7V6USKMU",
      "previousHospitalizations": []
    },
    "symptoms": {
      "creationDate": 1591336254521,
      "changeDate": 1591336254521,
      "uuid": "QTVE6X-LKSRM5-FIDZGA-XBNN2LFA",
      "onsetDate": 1591336250275,
      "symptomatic": false
    },
    "epiData": {
      "creationDate": 1591336254520,
      "changeDate": 1591336254520,
      "uuid": "RQMTFI-GGFXSN-MA5K57-I5LASG3Q",
      "burials": [],
      "gatherings": [],
      "travels": []
    },
    "therapy": {
      "creationDate": 1591336254522,
      "changeDate": 1591336254522,
      "uuid": "Q6JHVT-4IQT3G-IOVTFL-VG6EKOHQ"
    },
    "clinicalCourse": {
      "creationDate": 1591336254519,
      "changeDate": 1591336254519,
      "uuid": "QKKCNB-SAFQRA-443HZS-QHBRCI7Y",
      "healthConditions": {
        "creationDate": 1591336254519,
        "changeDate": 1591336254519,
        "uuid": "QTA77O-FTUYH6-NPB7EO-XSUHCOUM"
      }
    },
    "maternalHistory": {
      "creationDate": 1591336254520,
      "changeDate": 1591336254520,
      "uuid": "VZ6TUC-EZNSLK-UHOSZV-AN4ACDH4"
    },
    "portHealthInfo": {
      "creationDate": 1591336254521,
      "changeDate": 1591336254521,
      "uuid": "SVT3UL-WYJXIY-CVU5ZZ-2MFSSLTQ"
    },
    "caseOrigin": "IN_COUNTRY",
    "sharedToCountry": false,
    "quarantineOrderedVerbally": false,
    "quarantineOrderedOfficialDocument": false,
    "unreferredPortHealthCase": false
  }
]
