### ISSUE TITLE
Split name column in contact directory

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2060]
### Situation Description
One can order first name and last name in the case directory. In the contact directory, these columns are merged in 'contact person'. Therefore, users can only sort by first name in the contact directory.

### Feature Description
Split the column 'contact person' in the case directory into 'first name' and 'last name' in accordance with the case directory.

### Possible Alternatives
n/a

### Additional Information
Medium to high priority.

**Comment by MartinWahnschaffeSymeda** [comment]
Already done in #1721. Will be part of the release.
