### ISSUE TITLE
Show events from case epidemiological data in events menu

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2061]
### Situation Description
When a user enters epidemiological data, he can create an event within the same tab. This event is then tied to the case and does not show in the events menu.

### Feature Description
Show events from case epidemiological data in the events menu. It would also make sense to search for an existing event, so this case can be added to the event.

### Possible Alternatives
Open to suggestions.

### Additional Information
n/a

**Comment by MateStrysewskeSym** [comment]
The "events" from the epidemiological data are not the same as the events on the event directory. When a case is strongly connected to an event, it's possible to convert an event participant into a case which will make this link obvious. The social event attendance information in the epidemiological data are only meant to provide additional information about the case afterwards.

**Comment by max-hzi** [comment]
Too bad, I regard this as counter-intuitive. OK, seemingly irrelevant events may be listed in the epi data of a case. But I can't see a clear difference in the sense. If I add a small birthday party to a case in the epi info tab, I wouldn't be able to link two cases to this small party. Why bother using this field? I think if the event is relevant enough to enter into Sormas, the user should be able to do something with it, like adding other participants or even searching for it.

Other than that, I am not able to find any info within a case that this person attended an event, even if I added an existing case to an event using the duplicate detection function. Would this be worth implementing?

**Comment by MateStrysewskeSym** [comment]
@max-hzi We definitely need some way to show users whether a case has originated from a contact or event, i.e. some kind of source tracing. We already have this in our backlog since it's an important concept in epidemiology.
