### ISSUE TITLE
Add comments to server setup script and guide to not change the database user [0]

### ISSUE THREAD

**Issue by asohh** [hzi-braunschweig/SORMAS-Project#2062]
### Problem Description
If you use a different user for the database than "sormas_user" the deployment of the sormas-base fails, because the username is in the sql statements
### Proposed Change
Read the env (like in other areas of the code, like the contact tracing) and use the user specified in that

OR 

Write comments in server-setup.sh and README that the username shouldn't be changed

**Comment by MateStrysewskeSym** [comment]
@asohh Is there any reason for using a different database user?

I absolutely agree with adding a comment to the server-setup.sh and setup guide.

**Comment by asohh** [comment]
It would be needed if you would run multiple SORMAS installations with one Database Server or if the Person installing SORMAS wouldn't be able to chose the name of the user

But for the moment a comment would work and I'll also add that to the SORMAS-Docker README

Thanks
