### ISSUE TITLE
Travel outside the district

### ISSUE THREAD

**Issue by Jum19-commits** [hzi-braunschweig/SORMAS-Project#2063]
<For the travel outside the district "Case Epidemiological Date", the French Version does not mention the number of days (14) as it is appears in english Version. We Need to retranslate to French from English> 

### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by JaquM** [comment]
@Jum19-commits is this still an existing problem? Otherwise we could close this issue.

**Comment by bernardsilenou** [comment]
There is a new epi data structure, thus this it no longer velid
