### ISSUE TITLE
High availability Sormas

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#2073]
I wonder if someone is running Sormas in a "high availability" configuration, where the database and the application server run on several instances? 
From what I searched, PostgreSQL and Payara are capable of high availability. 
Anyone has ever tried?

**Comment by StefanKock** [comment]
Will be addressed with #2453.

**Comment by StefanKock** [comment]
Since the session state of Vaadin applications is stored on server side (server is stateful), there is more thought to be done than just running parallel instances.
