### ISSUE TITLE
After facility import many entries are missing

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#2076]
I have imported 1240 health facilities. Import was successful with 0 errors. 
Yet in the facility list I only have about 10% of the entire amount of facilities. 
When I try to import again, I get the error that such a facility already exists in this district (no duplicate warning but an error in the csv file. 
So the facilities are somehow there, but invisible. 

Any hints?

**Comment by RafaelKluender** [comment]
It seems, if you fill out the field "type" nothing gets imported. PRIMARY, SECONDARY, TERTIARY, everything did not show up in Sormas, although entries were imported to database.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Yeah, that's currently the case; We need to change that because it's extremely unintuitive and doesn't really make sense. It's basically a workaround for some issues we faced in the backend.
