### ISSUE TITLE
Make sure that dates displayed in the app/webapp are the same

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#208]
Right now, some dates are different (e.g. 02/03 and 03/03), probably because they're set to time 00:00. We need to make sure that this does not happen.

**Comment by MateStrysewskeSym** [comment]
- [ ] review if this is actually a problem (i.e. not associated with different time zones)

**Comment by MartinWahnschaffeSymeda** [comment]
Related to issue #1219
