### ISSUE TITLE
Initialization failing for Singleton StartupShutdownService

### ISSUE THREAD

**Issue by Crankuphigh** [hzi-braunschweig/SORMAS-Project#2082]
### Bug Description
While trying to set up development environment from scratch following the exact steps as mentioned here: [DEVELOPMENT_ENVIRONMENT.dm](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/DEVELOPMENT_ENVIRONMENT.md)

I was able to set up the sormas domain following steps from [this setup](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md)

But while trying to deploy "sormas-ear", "sormas-rest" and "sormas-ui" by adiing them to payara server in eclipse throws an error:
```
Publishing failed
cannot Deploy sormas-ui
deploy is failing=Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService. Please see server.log for more details.
cannot Deploy sormas-ear
deploy is failing=Error occurred during deployment: Exception while preparing the app. Please see server.log for more details.
```

Looking in detail log I found this:
```
Caused by: javax.naming.NamingException: Lookup failed for 'java:global/sormas-ear/sormas-backend/ConfigFacade' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: sormas-ear]

Exception during lifecycle processing
java.lang.NoSuchMethodError: sun.security.ssl.Handshaker.setApplicationProtocols([Ljava/lang/String;)V
```

### Steps to Reproduce
1.use [this](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md) for payara installation and creating sormas domain (with ROOT_PREFIX=/home/admin/Documents)

2.use [this](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/DEVELOPMENT_ENVIRONMENT.md) for coming upto 2nd last "Additional Steps" as mentioed in the doc

### Screenshots
![Screenshot from 2020-05-12 11-04-17](https://user-images.githubusercontent.com/19867331/81746845-c05c5980-94c4-11ea-9e95-8ff35e8330b4.png)

### System Details
* OS: Ubuntu 18.04
* SORMAS version: latest development branch from git

**Comment by MateStrysewskeSym** [comment]
Please have a look at #1765. Your problems are likely related to that issue. There's also a workaround in there.
