### ISSUE TITLE
Show Symptom Journal State for PIA and CLIMEDO in Sormas [2]

### ISSUE THREAD

**Issue by fhauptmann** [hzi-braunschweig/SORMAS-Project#2083]
Show if a contact person has an account in PIA.

**Comment by o-frietsch** [comment]
The plan was to show the PIA button in different colors.

**Comment by o-frietsch** [comment]
See issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/1970 for the status data interface.

**Comment by Candice-Louw** [comment]
Further specifications/guidelines/suggestions from a UI perspective (from the HZI PIA team):

**Contact Directory Overall -**
The health authority staff should be able to see at a glance in the contact directory and follow-up visits whether the symptoms are recorded via the symptom diary.  It should also be possible to sort/filter according to this (if this merits creating a separate issue, please indicate it as such?).

**For the follow-up visits Tab:**
In the Contact Directory > Follow-up Visits Tab > Introduce a new column next to the column "Follow-up until". In this column, display a circle or mobile phone symbol or computer symbol or any other suitable symbol/text (but not a box) if the symptom data is recorded via the symptom diary.

The "day boxes" can use the same colours as in SORMAS:
green (no symptoms), red (symptoms),  grey (not performed, here: by the contact person).

**Comment by FredrikSchaeferVitagroup** [comment]
I think we can leave this to be one issue. Some technical remark:
For the colouring of the button and for 2. in the comment from @Candice-Louw , we use the SymptomJournalStatus from #1970 .

To implement 1.  we can add a new field visitOrigin to visits, that holds an enum of the sort 
USER
EXTERNAL_JOURNAL
Every time a visit is saved, this enum should be set accordingly.

**Comment by markusmann-vg** [comment]
Add visitOrigin to Export / Import
