### ISSUE TITLE
In Sormas one Gesundheitsamt ID should be linked to one PIA study

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2084]
### Situation Description
Every Gesundheitsamt can be assigned to one PIA study.

### Feature Description
Config file where one PIA study ID is mapped to one Gesundheitsamt
Start with 1:1 relation

### Additional Information
What happens when more than one Gesundheitsamt use the same SORMAS instance.
Maybe we can work with the owner of a case, so not the Gesundheitsamt itself is linked to a PIA Study, but every case/contact

**Comment by markusmann-vg** [comment]
When creating a user for Pia with SORMAS the user will be assigned to the Gesundheitsamt (health authority) of the SORMAS user. 

new entity: health authority

**Comment by o-frietsch** [comment]
I'm not sure if this is still an active requirement. As to my knowledge, each GA uses its own PIA, do we really need more than one study then?

**Comment by soja-hzi** [comment]
Can this issue not be closed? We discussed it within the PIA team and cam to the conclusion that it is not relevant anymore.

**Comment by Candice-Louw** [comment]
Issue closed as not relevant anymore.  See https://github.com/hzi-braunschweig/SORMAS-Project/issues/2084#issuecomment-815691388
