### ISSUE TITLE
Bulk edit mode in contact directory triggering incorrectly

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2085]
### Bug Description
Bulk edit mode in the contact directory is unusable if opening a single contact, and returning to the directory.

### Steps to Reproduce
1. Open contact directory
2. Enter bulk edit mode
3. Open a single contact person
4. Go back to contacts list

### Expected Behavior
Sormas should remain in bulk mode, as it does in the case directory.

### Screenshots
Before opening a contact
![1](https://user-images.githubusercontent.com/63781233/81785589-c3743b80-94fe-11ea-8548-b417716b51f6.PNG)

After return to contact directory
![2](https://user-images.githubusercontent.com/63781233/81785646-d0912a80-94fe-11ea-9fdd-9f86ba9f80a8.PNG)

**Comment by MateStrysewskeSym** [comment]
As a workaround, you can click again on the "Leave Bulk Edit Mode" button and then once more on the "Open Bulk Edit Mode" to bring the contact directory back into bulk edit mode.

**Comment by ChristopherRiedelSymeda** [comment]
This appears in all views with bulk edit functionality.
