### ISSUE TITLE
Extend geocoding implementation to also work with geocoding services of French gov and other providers

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2087]
### Feature Description
For Germany we have added the capability to use a geocoding service #1576 .

### Problem Description
The geocoding is currently specific to a German geocoding service.
France will also need this and possibly also other countries that have their own geocoding implementations.

### Proposed Change
Find a more generic approach to configure the geocoding API access.
Have a look into https://geo.api.gouv.fr/adresse
and https://wiki.openstreetmap.org/wiki/DE:Nominatim
to find common patterns and define how to implement it.

Current implementation is done in `GeocodingService `class.

### Possible Alternatives
Just add a hard coded implementation for the French geocoding service.

**Comment by fhauptmann** [comment]
Needed for swiss adaption: 

https://api3.geo.admin.ch/services/sdiservices.html#search

**Comment by markusmann-vg** [comment]
could be sth. for Rafael Kluender?

**Comment by BastianSommers** [comment]
Is it possible to add an additional Option to use the opendata API for geocoding adresses, I think this could help Worldwide , ( even if it's not that accurate.)
( Maybe you can place a note in the Sormas.proberties that the opendata api is not 100% accurate.  ). 

The Health Departmens in Germany with a local Installation can't use the OsgtSEndpoint, because gdz_geokodierung_**bund**__{credentials} can be used only from Federal states like NRW or Hessen.

**Comment by leventegal-she** [comment]
Introduced new server configuration properties.

#### German setup properties
```
geocodingServiceUrlTemplate=https://sg.geodatenzentrum.de/gdz_geokodierung_bund__{credentials}/geosearch.json?query=${street}+${houseNumber},${postalCode}+${city}&filter=typ:haus&count1
geocodingLongitudeJsonPath=$.features[0].geometry.coordinates[0]
geocodingLatitudeJsonPath=$.features[0].geometry.coordinates[1]
```

#### French setup properties
```
geocodingServiceUrlTemplate=https://api-adresse.data.gouv.fr/search?q=${houseNumber}+${street},${postalCode}+${city}&type=housenumber&limit=1
geocodingLongitudeJsonPath=$.features[0].geometry.coordinates[0]
geocodingLatitudeJsonPath=$.features[0].geometry.coordinates[1]
```

#### Swiss setup properties
```
geocodingServiceUrlTemplate=https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=${street}+${houseNumber},${postalCode}+${city}&type=locations&geometryFormat=geojson&limit=1
geocodingLongitudeJsonPath=$.features[0].properties.lon
geocodingLatitudeJsonPath=$.features[0].properties.lat
```
