### ISSUE TITLE
Possibility of users directly updating from older versions to current versions

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2090]
### Problem Description
Currently, mobile app users are unable to directly update the SORMAS app from a very old version to a current version. Forinstance, users cant directly update from 1.37.0 to 1.40.0 without the app crashing. 
We have situations whereby mobile users who havent used the app for sometime decide to activate their use. This means they have to uninstall whatever version is on their device, install the latest version and go through the long process of entering server urls, entering login details and synchronization
### Proposed Change
It would be great, if it were possible to have a feature that makes it possible for a mobile user who is already logged in on an old version, and hasnt used the app for quite sometime, to quickly update from that old version to the most current version and still remain logged in as long as his login details havent changed @Chinedar @foyiri @MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
@Iheanacho2027 Normally that's the case.

The 1.37.0 has a bug that crashes the automatic app update. Those users will have to manually install the latest version. See https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/v1.37.2

You can provide a direct download link to users that they than can open and install on their device:
E.g. for 1.39.2 this would be https://sormas.org.ng/downloads/sormas-1.39.2-release.apk

**Comment by Iheanacho2027** [comment]
Sorry, this is not just for automatic updates but also occurs for manual updates. What i am referring to has been in existence before 1.37.0

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Check firebase log for this problem

@Iheanacho2027 Can you say which exact versions are involved? The user currently has 1.37.0 and not 1.37.2, correct?
To which version is he trying to update? You were saying 1.40.0, but this has been released yesterday evening and not yet rolled out to the Nigerian server. So I guess 1.39.2?

**Comment by Iheanacho2027** [comment]
The user has 1.33.0 and was trying to update manually to 1.39.2. The user installs manually but in the process of navigating to the app, the app crashes. Meaning the user has to uninstall completely and install the latest version. I think this has to do with issues relating to infrastructure framework

**Comment by bernardsilenou** [comment]
No longer a bug in newer versions
