### ISSUE TITLE
Add place of exposure to Sormas (Under refinement)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2093]
### Situation Description
Sormas is missing the feature to document the place of exposure ('Herde'/ 'Ausbrüche').

### Feature Description
We suggest three aspects of implementation:
1. How to proceed with Clusters for case, contacts and event participants - Create event, add place of exposure (address), add participants (including contacts, cases), create a new field for cluster ID ('Herdenschlüssel').
2. How to proceed with Clusters for case, contacts via the epidemiological data tab - Add event in epi data, add place of exposure (address), add participants (including contacts, cases), create a new field for cluster ID ('Herdenschlüssel') (here, further refinement is needed, and we will deliver soon)
3. Clusters configuration - Automatic detection of new Clusters; also add Clusters statistics on district and postcode level. It would also make sense to show new outbreaks on the map

Remarks: 
- Cluster ID should have a link to the event ID (same ID)
- Cluster ID should include info, if contact (C/ K), case (F), participant (P/ T)

### Possible Alternatives
Open to suggestions.

### Additional Information
Further refinements incoming, please understand this post as a basis for discussion. Epi info also coming to contacts in the future (#1838).
[Ausbrüche-SORMAS_Deutschland.pptx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4626241/Ausbruche-SORMAS_Deutschland.pptx)
[Anlegen von Ausbruchsgeschehen_mh.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4626242/Anlegen.von.Ausbruchsgeschehen_mh.docx)

**Comment by bernardsilenou** [comment]
@max-hzi:  By default each event is sormas has an event id, that is used to link all cases and contact persons belonging to the event, although not clearly visible at front end. What is the definition of the outbreak ID you mentioned. Is it something generated by db or user given?

**Comment by bernardsilenou** [comment]
Another point we need to consider is that, the outbreak module in the default configuration tab in sormas is region and district specific but the one mentioned here is case specific. That means outbreak within an outbreak and these cases in the outbreak (linked to a common exposure called event) may come from different regions and district. This is a challenge we have to consider in the implementation. 
I am skeptical in allowing the users to define a set of cases linked to an event as outbreak because if the user is not a notional user, they will not be able to have assess to all the cases that resulted from the event, thus may not be able to classify the event as an outbreak. Maybe we do this automatically based on thresholds.

**Comment by markusmann-vg** [comment]
Translation of: Anlegen von Ausbruchsgeschehen_mh.docx

Creation of clusters under epidemiological data in the cases and contacts, possibly with a list of participants:

Open questions: 

> Should nosocomial outbreaks (§ IfSG 23) still be handled differently?
> Adapt outbreak statistics under Statistics on postal codes?
> Consideration of the IfSG according to §23 (hospitals etc.), 33 (day-care centre), 36 (other facilities, mass accommodation), 42 (ban on employment)


Add epidemiological data under contacts 
Tab structure Field Cluster/location of exposure

1. is a place of exposure known? (yes/no/unknown) if yes continue with number 2
No further processing 
2. if 1 yes, then date of exposure: (dd/mm/yyyy)
3. if 1 yes, where did the exposure take place? 
Add drop-down field with exposure location (see table Category of facility)
 
3.1 This table must be created by the admin with a link to the setting data in the statistics (to avoid duplication)
3.2. field with exact location name (can be created by the admin) or by the employee?
3.3. free text field "additional field" for e.g. class or contact person
4. add cluster ID (compatible with SurvNet stove key) with a note in the code K for contact, F for case, T for participant This is where the link to the events/events should be made. 
Please note: 2 ways must exist. Add from case and contacts or participants to outbreak (link case to outbreak) and under cluster the cases/contacts and participants must be visible and you must be able to add them ("Add case").

**Comment by bernardsilenou** [comment]
@markusmann-vg  I am confused with the specifications here. The epidemiological data for contacts specified here seem to be different from what we have for cases.  Issue #2211 addressed point 1 of this issue, I still need to create 2 other issued for point 2 and 3.

"is a place of exposure known? (yes/no/unknown) if yes continue with number 2
No further processing
if 1 yes, then date of exposure: (dd/mm/yyyy)
if 1 yes, where did the exposure take place?
Add drop-down field with exposure location (see table Category of facility)"

This seem to be what is already documented by the "visited social event" variable. 
Please can we have a final refinement meeting before implementation begin?

**Comment by markusmann-vg** [comment]
Summary from what I read in the documents:

- [ ] Add an option to link a case to an event in the epidemological data, when a case "visited an Event". 
Current situation: An Event can be added as a social event. It does not appear in the list of events
New situation: An Event can be created from the case and will be shown in the list of events as well or the event can be picked from the list of existing events. 
An Event (ID, which is unique) can also have a new or updated ClusterID.

- [ ] Add epidemological data to contacts, including the events & Adjust the fields (remove some from contacts which are not needed)

- [ ] Create or assign a new Cluster ID to contacts & cases

- [ ] Add a ClusterID to an event in the events list

Can you confirm this as a starting point for implementation? @bernardsilenou

**Comment by bernardsilenou** [comment]
> Summary from what I read in the documents:
> 
> * [ ]  Add an option to link a case to an event in the epidemological data, when a case "visited an Event". 
OK
>   Current situation: An Event can be added as a social event. It does not appear in the list of events  
OK
>   New situation: An Event can be created from the case's or contact's epidemiological data and will be shown in the list of events as well or the event can be picked from the list of existing events. 
OK
>   An Event (ID, which is unique) can also have a new or updated ClusterID. not ok, cluster/ outbreak is a separate entity by itself and will appear in the menu bar. Will confirm this after discussing with team by tomorrow please.
> * [ ]  Add epidemiological data to contacts, including the events & Adjust the fields (remove some from contacts which are not needed) OK, keep animal contact, events, travel history, etc
> * [ ]  Create or assign a new Cluster ID to contacts & cases,  
OK
Similar to the event entity, we will have a cluster/outbreak entity where we can link cases and contacts to, A clear distinction between outbreak and events will be done  tomorrow please.
> * [ ]  Add a ClusterID to an event in the events list 
OK, since event it a person related entity, the condition her will be that for persons who belongs to a cluster, we add the cluster id in the event, What about if the person belongs to more than one cluster? 
> 
> Can you confirm this as a starting point for implementation? @bernardsilenou

**Comment by bernardsilenou** [comment]
Few comments from last comment:
Create or assign a new Cluster ID to contacts & cases,
_OK, this is actually the uuid of the event that the case or contact is related to_ 

Similar to the event entity, we will have a cluster/outbreak entity where we can link cases and contacts to, A clear distinction between outbreak and events will be done tomorrow please.
_There is still no clear method/functionality that the "cluster/outbreak" entity can document  that the current updated event entity can't. We begin with the implementation of event only for now as described. Outbreak will be a separate menu on its own if we latter decide to implement it._

**Comment by bernardsilenou** [comment]
- When creating an Event, either from a case or event tab, 
* Region and district should be chosen before type of place
* If type of place is "Hospital", show drop down all hospitals in the system for user to chose just as we have for case creation. Then the same thing for schools,

**Comment by bernardsilenou** [comment]
This is update as at today, final refinement is on next Monday.

We will use the event class to manage: events, screening and clusters (consisting of types: nosocomial, non-nosocomial, household, others)
Some definitions and suggested model:
1.The event class is used to hold cases, contacts, event participants, who had a "common exposure" or a common activity (eg screening)
2, The event entity has 2 main classes for now: Events (consisting of many status) and Screening
3. When creating a new event, we specified the type of event: screening or Event
4. If event type = screening, then document event participants with additional attributes:
sample, results, just as we have for cases.
4,1 If sample is positive for the same disease as disease of the screening event, create a case and link it to the screening event.
5. If event type = Event, and
if not yet Investigated, then status = Signal, attributes = event participants
if investigated, User then can set the status to Event or Not an Event
If status = Not an event, then no option to add participants and make them cases
If number of confirmed cases linked to event is >=d ( d == 2 for now for all diseases), then
status = Cluster
If event status == cluster, then
cluster type = Non-nosocomial cluster, Nosocomial cluster, household cluster, Others
If cluster cluster type == Nosocomial
Add optional parameter which when set to true, all events participants are created as contacts with all cases in the event and followup of contacts is based on the symptom onset date of the most recent case in the cluster or date f last contact.
6. Some event like festivals runs for more than a day, thus add Event start date ---- Event end date
7. Extent type of place with the following types:
Hospital/Clinic replaces hospital
Private practitioner/therapeutical institution
Household
Churches
Institutes/ Working place
Retirement and nursing homes
Kindergarten/Nursery/Day care centre
Schools/ Universities
Residential institutions/ homes
Holiday Camps
Prisons
Sports facilities
