### ISSUE TITLE
Introduce contact category Ia and Ib (Sormas Germany)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2094]
### Situation Description
There are three contact catagories availible in Sormas, and for Germany these are differenciated in I, II and III. In fact, category I has two sub-categories, Ia and Ib. These can't be entered into Sormas.

Link: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Grafik_Kontakt_HCW.pdf?__blob=publicationFile

### Feature Description
Provide the option to choose contact Ia or Ib. This could be relised by showing a new field if contact catagory I is chosen. The user would be able to click on Ia or Ib, and also have a free text field to enter further information.

### Possible Alternatives
Open to suggestions.

**Comment by markusmann-vg** [comment]
Is it true that
former I => Ia
former II => Ib
former III => III

If so, you can change it in translations. @max-hzi

**Comment by max-hzi** [comment]
Unfornutaley, these are new categories and do not replace former ones.

> Kontaktkategorie I
> -	Personen, die aerosolbildenden Maßnahmen ausgesetzt sind
> -	Personen mit kumulativ mindestens 15-minütigem Gesichtskontakt
> -	Personen mit direktem Kontakt zu Sekreten oder Körperflüssigkeiten
> 
> Kategorie 1A: 
> Medizinisches Personal mit Kontakt mit Sekreten, gegenüber Aerosolen von COVID-19-Fällen im Rahmen von Pflege oder medizinischer Untersuchung (>= 2 m)  ohne verwendete Schutzausrüstung
> Kategorie 1B: 
> Medizinisches Personal <= 2 m, ohne Schutzausrüstung mit direktem Kontakt zu COVID 19 Fällen und bei möglicher Aerosolbildung
> 
> Kontaktkategorie II (abgeleitet von Beispielhafte Konstellation)
> -	Personen, die sich im selben Raum wie ein bestätigter Fall aufhielten 
> -	Medizinisches Personal, welches sich ohne Verwendung adäquater Schutzbekleidung im selben Raum wie der bestätigte Fall aufhielt, aber eine Distanz von 2 Metern nie unterschritten hat
> 
> Kontaktkategorie III
> -	Medizinisches Personal ohne verwendete Schutzausrüstung und Distanz immer > 2 m sowie bei keiner Exposition gegenüber Sekreten, Körperflüssigkeiten oder Aerosolen 
> -	Medizinisches Personal mit verwendeter Schutzausrüstung und < 2 m Abstand
>

**Comment by bernardsilenou** [comment]
@max-hzi @markusmann-vg  Juliane sent an email with further details on how to proceed with these categories last Friday

**Comment by bernardsilenou** [comment]
@markusmann-vg: This table is the refined categories at May 20, 2020. Its from Juliane
[Contact_classification_20200515.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4674574/Contact_classification_20200515.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Add the two new ContactCategory values for Ia and Ib. 

Value | German | English
-- | -- | --
HIGH_RISK_MED | Kontaktperson der Kategorie Ia (enger medizinischer Kontakt) | High risk mecical contact
MEDIUM_RISK_MED | Kontaktperson der Kategorie Ib (begrenzter medizinischer Kontakt) | Medium risk mecical contact

- [ ] Rename/add the two new ContactProximity fields. Use only for Germany (as other ContactProximities already do).

Value | German | Kategorie | English translation
-- | -- | -- | --
MEDICAL_UNSAVE | Medizinisches Personal mit hohem   Expositionsrisiko, z.B. ungeschützte relevante Exposition zu Sekreten,   Exposition gegenüber Aerosolen von COVID-19-Fällen | Kat. Ia | medical personnel with a high   risk of exposure, e.g. unprotected relevant exposure to secretions, exposure   to aerosols from COVID-19 cases
Missing | Medizinisches Personal mit begrenzter Exposition, z.B. mit   Kontakt < 2m zu COVID-19-Fällen ohne Schutzausrüstung, ≥15 Min   face-to-face Kontakt (ohne Exposition wie unter Ia beschrieben) | Kat. Ib | medical personnel with limited   exposure, e.g. with contact < 2m to COVID-19 cases without protective   equipment, ≥ 15min face-to-face contact (without exposure as described under   Ia)

@bernardsilenou @max-hzi Please double-check my summary

**Comment by max-hzi** [comment]
Looks fine to me, I asked Juliane for clearance just to be sure.

**Comment by MateStrysewskeSym** [comment]
Review: @ChristopherRiedelSymeda
