### ISSUE TITLE
Adjust COVID-19 symptoms & health conditions as needed for Germany [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2097]
### Feature Description
The current COVID-19 defintion in SORMAS is mostly the same for all countries. There are a few exceptions already for symptoms we added recently (#1824).

### Problem Description
The German system has a much more limited set of symptoms, etc. which needs to be implemented to make sure users are not confused and are able to enter all needed data.
In addition this is needed for the interface towards RKI SurvNet.

### Proposed Change

These are the changes needed for German SORMAS systems.

#### Symptoms needed

- [x] Hide all symptoms that are not in this list. Exception: other symptoms
- [x] Add the missing symptoms. Please double check that they are really missing and we did not miss any existing symptom.
- [x] For "allgemeine Krankheitszeichen" add a description to the field:

> Allgemeine Krankheitszeichen, definiert als mindestens zwei der vier folgenden Kriterien: 
> - Frösteln, 
> - schweres Krankheitsgefühl, 
> - Kopfschmerzen,
> - Muskel-, Glieder- oder Rückenschmerzen. 

SurvNet | Caption de | Caption en | Exists in SORMAS
-- | -- | -- | --
Symptom0103 | Halsschmerzen | Sore throat | (case.)symptoms.soreThroat
Symptom0130 | Husten | Cough | (case.)symptoms.cough
Symptom0158 | Lungenentzündung (Lugenentzündug) |  Pneumonia | pneumoniaClinicalOrRadiologic
Symptom0225 | Schnupfen | Runny nose | (case.)symptoms.runnyNose
Symptom0394 | Akutes schweres Atemnotsyndrom (ARDS) | Acute respiratory distress syndrome (ARDS) | (case.)symptoms.acuteRespiratoryDistressSyndrome
Symptom0393 | Beatmungspflichtige Atemwegserkrankung |  Respiratory disease requiring ventilation |
Symptom0064 | Kurzatmigkeit in Ruhe (Dyspnoe) | Difficulty breathing (Dyspnea) | (case.)symptoms.difficultyBreathing
Symptom0088 | Fieber | Fever | (case.)symptoms.fever
Symptom0101 | Allgemeine Krankheitszeichen |  General signs of disease |
Symptom0062 | Durchfall | Diarrhea | (case.)symptoms.diarrhea
Symptom0416 | Geruchsverlust | Lost/reduced sense of smell | (case.)symptoms.lossOfSmell
Symptom0417 | Geschmacksverlust | Lost/reduced sense of taste | (case.)symptoms.lossOfTaste
Symptom0245 | Herzrasen (Tachykardie) |  Fast heart rate (Tachycardia) |
Symptom0418 | Beschleunigte Atmung (Tachypnoe) | Rapid breathing (Tachypnea) | (case.)symptoms.rapidBreathing
. | Sauerstoffsättigung   <94% | Oxygen saturation <94% |
. | Übelkeit/Erbrechen | Nausea/Vomiting | (case.)symptoms.nausea
. | Schüttelfrost | Chills | (case.)symptoms.chillsSweats

@max-hzi Can you check with Juliane and Gaby how to deal with "allgemeine Krankheitszeichen"? I feel this is a bit vague and wonder if we could use our "other symptoms" field for it that also allows the user to add some details.

#### Pre-existing conditions (clinical course / health conditions)

- [x] Hide all health conditions that are not in this list (except "other...")
- [x] Add the missing health condition for "Immundefizienz,   inkl. HIV". The existing HIV and immundeficiency fields need to be hidden for Germany
- [x] Make sure the captions for Germany match the captions below

SurvNet | Caption | Exists in SORMAS
-- | -- | --
Risk0004 | Herz-Kreislauf-Erkrankung (inkl. Bluthochdruck) | (case.)clinicalCourse.healthConditions.cardiovascularDiseaseIncludingHypertension
Risk0005 | Diabetes | (case.)clinicalCourse.healthConditions.diabetes
Risk0006 | *Chronische* Lebererkrankung | (case.)clinicalCourse.healthConditions.chronicLiverDisease
Risk0007 | neurologische/neuromuskuläre Erkrankung | (case.)clinicalCourse.healthConditions.chronicNeurologicCondition
Risk0008 | Immundefizienz,   inkl. HIV | 
Risk0009 | Nierenerkrankung | (case.)clinicalCourse.healthConditions.chronicKidneyDisease
Risk0010 | Chronische   Lungenerkrankung (z.B. COPD) | (case.)clinicalCourse.healthConditions.chronicPulmonaryDisease
Risk0011 | Krebserkrankung | (case.)clinicalCourse.healthConditions.malignancyChemotherapy

@max-hzi I understand that we have to create a new field for "Immundefizienz, inkl. HIV" and can't use the existing two fields: "HIV" and "Immunodeficiency other than HIV". 
Is this correct?

**Comment by MartinWahnschaffeSymeda** [comment]
@max-hzi Please also double-check: Is it correct that SORMAS Germany should ONLY show the symptoms and pre-conditions listed above to users?

**Comment by MartinWahnschaffeSymeda** [comment]
I have updated the description based on feedback from Gaby.

**Comment by MartinWahnschaffeSymeda** [comment]
Reviewed. Fixed two small issues

**Comment by MateStrysewskeSym** [comment]
- [ ] Hide new symptoms from servers with a different locale than German
