### ISSUE TITLE
Implement deletion concept for contacts and event participant's information 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2101]
### Feature Description
**For contact persons and exposed persons (e.g. air passengers from risk regions)**

**What is deleted?** 
- surname and first name,
- date of birth and
- address of main residence or habitual abode d) addresses of other places of residence (including hospitals etc.), [Reason: derivation of § 11 and 12 IfSG].

**What is not deleted?** 
Gender
3-digit postcode of places of residence and stay
year and month of birth
link between case and contact persons
all data transmitted according to §11 and 12 IfSG [Reason: the data is transmitted anyway according to §11 and 12 IfSG and therefore obviously classified by the legislator as unobjectionable under data protection law. In addition, they are also classified as significant for the national level, from which it can also be deduced that they are not subject to deletion for long-term studies].

**When is deletion about to happen?** 
On the 1st working day of one month after the end of the double incubation period, but at the latest on the 1st working day two months after a data set on the contact person or exposed person was first created. 

Reason: Since it cannot be assumed that after more than three incubation periods it will become known that a contact person converts to a case, a particularly short deletion period applies here, also because no findings to be used in the sense of the IfSG are to be expected beyond this period. The justification for the significantly shorter period compared to the cases is that, on the one hand, these are not persons from whom a risk of infection has been assumed and, on the other hand, for whom there is no obligation to register with a doctor (i.e. release from the obligation of medical confidentiality)].

**Comment by max-hzi** [comment]
I'd like to share some thoughts from Gaby:

> For contact persons and exposed persons (e.g. air passengers from risk regions)
- As screening will be included in SORMAS, please include screened persons

> - address of main residence or habitual abode d) addresses of other places of residence (including hospitals etc.), [Reason: derivation of § 11 and 12 IfSG].
To my opinion the address of the hospital does not need to be deleted.

**Comment by max-hzi** [comment]
Once again I'd like to document some info from Gérard:

The health departments should be able to set a few essential configurations of the deletion periods for personal identifying data.

**Comment by MartinWahnschaffe** [comment]
Deletion will be fully configurable on field level. See https://github.com/hzi-braunschweig/SORMAS-Security/issues/11
I'm closing this, because the implementation needs to be sliced differently.
