### ISSUE TITLE
Add responsible community to contact [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2104]
As discussed here https://github.com/hzi-braunschweig/SORMAS-Project/issues/2021#issuecomment-627890951_

- [x] add "responsible community" drop down to contact (not mandatory)
- [x] rename caption of region, district and community of case to "responsible ..."
- [x] same for the filters used in case directory of app and UI
- [x] add a filter to the contact directory

**Comment by max-hzi** [comment]
This issue does not cover the need for the community filter. Content-wise, I ask for it in the initial issue #2021. So we're covered, right? Just to be sure. Thanks!

**Comment by MartinWahnschaffeSymeda** [comment]
Ah. Good point. I have added the filter to the list above.
