### ISSUE TITLE
Rerun server-setup

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#2105]
Currently, when changes to the dashboard are desired, for instance a different focal point of the map, it is necessary to rerun the "server-setup" script. 
Doing so, we overwrite the entire settings that we already made. That's a shame. 
Will this also make me loose the server costumisation (list of regions, districts, and so on)?

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender That's not true. All you have to do is change the respective properties in the sormas.properties file. This is mentioned in the server setup guide.

**Comment by RafaelKluender** [comment]
You mean, just change it without having to rerun server-setup.sh? 
That does not work for me.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender You probably need to restart your domain afterwards, but it's absolutely not necessary to rerun the setup script.

**Comment by RafaelKluender** [comment]
Well, I just restart the whole machine and it has no effect on the coordinates?

**Comment by RafaelKluender** [comment]
What is more annoying than the map is that I also enabled "R" in sormas.properties and it does not show up. 
Which of those sormas.properties files does need to be updated? 
The most recent one, or that from the very first deployment? 
Remember that "sormas-update" generates a new folder, each time a new version comes out.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender You need to change the sormas.properties file in the opt/domains/sormas folder. That folder does not change during updates.

For the submission chains to show up, you first need to select a disease to filter the contact dashboard by and then click the "Please maximize [...]" button at the bottom of the page.

**Comment by RafaelKluender** [comment]
Indeed, the folder is specified here: 
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md

I have overseen that, I apologize. 
Many thanks.

**Comment by MateStrysewskeSym** [comment]
@RafaelKluender Not a problem, I'm glad that it's working now.

**Comment by RafaelKluender** [comment]
Actually not all settings in sormas.properties seem to be taken into account. 
I can change the zoom settings, but changing the latitude and longitude does not change the map view. The map is always centred around the point I initially set during the installation.
