### ISSUE TITLE
Add a section about changing properties to the server customisation guide

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2109]
#2105 made me realise that we need to have a dedicated guide on GitHub that explains how the properties file can be adjusted and explain in a bit more detail what the individual variables do.

**Comment by MartinWahnschaffeSymeda** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/commit/b80ea7b0d0f9ef8416832ad5f881a307807272c1#diff-ca5f43d9ae2e2e07749c5f494e0a61db
