### ISSUE TITLE
Cancel follow-up when a contact is converted to a case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2115]
### Bug Description
when a contact is converted to case, the followup  in not cancelled automatically. If you latter play with the follow up  and contact classification options, save the contact each time you change the followup information after you have converted the contacts to a case (case1), the button "convert this contact to a case" is  reactivated and the contact and status if set to "active". You can then convert the contact to another case (case 2) again.
When contacts to case1 are deleted, case 1 do not show on transmission chain because it is not need in the system as resulting from a contact
When there are contacts to case1, it appears normally on transmission chain
I write more points latter, just needed to note in down
### Steps to Reproduce
1. see above
2.

### Expected Behavior
We need to consider the options in issue 1648 while updating the logic here
1, contact converted to case should allow the user to revert this action which will mean deleting the case and any other data that follows
2

### System Details
* Device: web
* SORMAS version: 1,40
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I can't reproduce the problems you're describing. The button "convert this contact to a case" never re-appears for me after I've created a resulting case, no matter how often I change the contact classification or follow-up information.

From my understanding, the only thing that currently needs to be done about this issue right here is that contact follow-up is automatically canceled when the contact is converted to a case. If you have more details on how I can reproduce the problems you're talking about, please add them here.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I did the same thing and all was fine, I found nothing this time

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Okay, good!

**Comment by MartinWahnschaffeSymeda** [comment]
Reviewed
