### ISSUE TITLE
Add uuid to all entity (person, visits,) views just as we have in case contact view

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2116]
### Situation Description
For axample

![image](https://user-images.githubusercontent.com/12996724/82050985-55c03f00-96b9-11ea-889a-b81ab79d6a99.png)

![image](https://user-images.githubusercontent.com/12996724/82051087-8dc78200-96b9-11ea-9b8e-e8f0eaf6dc92.png)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The person UUID is not referenced anywhere in the UI. Why should the user see it?

**Comment by bernardsilenou** [comment]
A user created a person associated to event, contact and a case and want to be sure that it is the same person. Since we will soon have the search function for persons, I think is will be good to show it. We already show it for persons associated to event.

**Comment by bernardsilenou** [comment]
Was implemented in another issue
