### ISSUE TITLE
Download of all cases and samples crashes instance

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#2118]
### Bug Description
Download of cases and samples (records over 20,000), crashes the instance of user. Seems like the analytics of calling values of several variables from multiple tables is the major issue here. From the DB, this takes several minutes. From the front-end, this download never comes through. Thinking we can set up separate defined tables that will receive incremental pull from all other necessary tables and the defined tables receive the instruction when users want to export from the front-end.    
### Steps to Reproduce
1. 
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
In a centralized db as used in Nigeria, I think we should not allow users to download the whole db at front end. 
We may need a quarry interface like the statistics section that users can run quarries and download just what they need conditioned on their user rights. We can also restrict them from downloading data with more that 3 yrs old.

**Comment by Chinedar** [comment]
@Silenou, Bernard <Bernard.Silenou@helmholtz-hzi.de> I agree. Am even
referring to just COVID-19 cases. We have over 33,000 records of cases
which have dependents on so many other tables in the DB.

**Comment by MateStrysewskeSym** [comment]
@Chinedar You've already opened #2000 which is basically the same issue. We're going to look into ways to increase the export speed. In the meantime, please try to export data in smaller chunks.
