### ISSUE TITLE
Double rows as header names for detailed case import of cases

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2119]
### Feature Description
I downloaded the template for detailed case import and found double role names as header. See picture attached
@MateStrysewskeSym Is this a  bug?
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/82150145-4fb49480-9858-11ea-82c4-4e702152e33c.png)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou No, it's been like this since we've added the option to import samples via the detailed case import.
