### ISSUE TITLE
In all importation template, date fields should be consistent

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2120]
### Feature Description
The DOB is recorded in 3 fields while the date of report is one field. We should use one field for all date types 

person.birthdateDD | person.birthdateMM | person.birthdateYYYY

**Comment by MateStrysewskeSym** [comment]
The date of birth needs to be split into three variables because, for countries like Nigeria, people sometimes do not know their exact birth date. Having a year is way better than having a wrong or no birth date at all.
