### ISSUE TITLE
Merge option when importing cases

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2121]
### Problem Description
We heave a pick and skip but no merge option when duplicate case is detected during case import. See figure attached
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/82152044-159ac100-985f-11ea-8e22-87c1b02387e7.png)

**Comment by MateStrysewskeSym** [comment]
The merge option is displayed directly below the "Pick".
