### ISSUE TITLE
Reject import data when dates have an incomplete date format

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2122]
### Bug Description
I have attached 2 images, one is the data I imported and the other is how it shows up on the case directory. Date formats such as 15/05/20 are imported as 15/05/0020.
@MateStrysewskeSym @markusmann-vg 
Since the formatting of variables ( date, regions, districts, ,,,) of the exported data is different from that of the imported template, what is your opinion about filling the first 2 or 3 rows of each importation template (case, contact, etc). The user will then have to delete these first 3 rows when importing.
Providing an empty template to users together with the data dictionary is not user friendly and prone to errors like this one. 
### Steps to Reproduce
1. Import this attached excel data on .symeda server
2.

### System Details
* Device:
* SORMAS version: 1,40,1
* Android version/Browser:

### Additional Information
![image](https://user-images.githubusercontent.com/12996724/82152733-a378ab00-9863-11ea-865c-568288e401b8.png)

[sormas_import_error_report (2).xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4640492/sormas_import_error_report.2.xlsx)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I think I'd rather provide an example file that they can have a look at than fill the template with example data because that forces you to always delete these rows even if you're familiar with the way the import works. Can you open an issue?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou @MartinWahnschaffeSymeda @markusmann-vg I'm not sure how to handle this issue. My problem is that "20" could relate to both 1920 and 2020.

We could assume that it's 2020 by default, but that is prone to errors because we can't really decide that in a reliable way since SORMAS can also contain dates in the future. Because of that, my feeling is that we should validate the date formats used during the import and reject dates that don't have a full format.

What is your take on this?

**Comment by bernardsilenou** [comment]
I think we should force the user to specify the 4 digit on the import template. To be safe when we come with importation of historic data fro example

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Alright, thanks!

- [ ] Validate date formats during import and make sure that four digits are used for years; if not, refuse to import the row and add it to the error report file with a custom error message
