### ISSUE TITLE
Duplicate detection during line listing does not show information about the created case [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2123]
### Feature Description
When saving a line list of cases, the system suggest duplicate but does not present the information of the case that is being imported in the dialog box.
### Proposed Change
- For each duplicate detection: case creation, case importing, contact imparting, etc We should present the source data together with the list of similar data found in the system.

@markusmann-vg 
During Planning: Take the data from detailed import (duplicate detection)

### Additional Information
![image](https://user-images.githubusercontent.com/12996724/82162205-f0c83d00-98a2-11ea-85a5-3085aa6f9806.png)

### Review
@sergiupacurariu

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym we still have problems related to this issue.
When creating cases from line listing, system does not trigger duplicate case detection.
version 1,44,0

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou That doesn't have anything to do with this issue.

**Comment by bernardsilenou** [comment]
OK

**Comment by bernardsilenou** [comment]
I will create a new one
