### ISSUE TITLE
Import guide refinement [0]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2131]
### Feature Description
The import guide and import template for detailed case import is not self explanatory. This cause challenges in importing data
### Proposed Change
1. Add a sentence in the import guide to explain that that first row in the header of the import template is an explanation of the entity where the data on the second row belongs to and will be ignored during the importation process.
2, For the column reportDate, symptoms dates and other dates,  specify the date format, eg  (mm/dd/yyyy)  not (M/d/yyyy). We can also use the description row 1 for this
# Possible Alternatives
3. Add a sample import template with 3 or 2 cases on first row so users can see how to follow and fill their own data on the table.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I think the only important point here now is creating an import template with dummy data. I created issue #2146
You are the one to decide if we keep this issue still open?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Yes, I think this is still useful.

**Comment by MartinWahnschaffeSymeda** [comment]
TODO in this issues is point 1:

-[ ] Add a sentence in the import guide to explain that that first row in the header of the import template is an explanation of the entity where the data on the second row belongs to and will be ignored during the importation process.

For 2. see #2537 and for 3. #2146
