### ISSUE TITLE
Translation text fro case guide in original English version is missing a section

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2132]
### Bug Description
In crowdin, the english text should be:
Completeness is a measurement of how much vital data has already been entered into the case. This is composed of the following, weighted by their importance:<br/><ul><li>Has the case been classified?</li><li>Has the case been investigated?</li><li>Has at least one sample been taken?</li><li>Has at least one symptom been documented?</li><li>Has at least one contact been created?</li><li>Is there an outcome for the case?</li><li>Does the case have a birth date or age?</li><li>Does the case have a sex?</li><li>Has an onset date been specified?</li></ul>You can use this measurement to get an idea about which case you should use as the one that remains active when merging. However, please make sure that you still have a detailed look at both cases to avoid mistakes.<br/><br/>The <i>Calculate Completeness</i> button on top can be used to calculate the completeness values for all cases in the table. This is only necessary if there are cases in the list that do not yet have a completeness value. Normally, this value is automatically updated whenever the details of a case or one of its contacts or samples change.

The missing section is:
You can use this measurement to get an idea about which case you should use as the one that remains active when merging. However, please make sure that you still have a detailed look at both cases to avoid mistakes.<br/><br/>The <i>Calculate Completeness</i> button on top can be used to calculate the completeness values for all cases in the table. This is only necessary if there are cases in the list that do not yet have a completeness value. Normally, this value is automatically updated whenever the details of a case or one of its contacts or samples change.

See figure

### Steps to Reproduce
1. Open case guide in English and in French
2.

### Expected Behavior
Add the missing section in the English version in crowdin
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

### Additional Information
![image](https://user-images.githubusercontent.com/12996724/82210933-4129b400-9910-11ea-82c0-140e3d9402c7.png)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I don't see a problem here. The string exists in the original strings.properties file and the text is also displayed on the demo server. What exactly is missing?

**Comment by bernardsilenou** [comment]
Open case guide on .symeda server, use English, German and latter change your language to French, the French version has extra text that is not in the English and German text.
There is a text somewhere that has not need updated, I do not know the cause of this right now

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The text is there. Please attach a screenshot of your whole screen with the English version of the guide open to this issue.

**Comment by bernardsilenou** [comment]
OK
![image](https://user-images.githubusercontent.com/12996724/82443025-0c009b80-9aa1-11ea-89a4-ad8cbb85feb3.png)


![image](https://user-images.githubusercontent.com/12996724/82442573-37cf5180-9aa0-11ea-9a29-d89358f082c2.png)


![image](https://user-images.githubusercontent.com/12996724/82442673-64836900-9aa0-11ea-9a7b-ff516326c87c.png)

**Comment by bernardsilenou** [comment]
The extra text in the French version also appears in the merge guide. This is probably a translation problem and should be deleted, right?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Ah, now I see! Sorry, I've actually went into the wrong view (the merge duplicates view). The additional text in French actually does not belong here, right. The English and German versions are fine. Can you go ahead and delete the additional text from the French translation, please?

**Comment by bernardsilenou** [comment]
ok, thanks
