### ISSUE TITLE
Spanish Cuban version proposed

### ISSUE THREAD

**Issue by urrape** [hzi-braunschweig/SORMAS-Project#2138]
### Situation Description
The present spanish version is created for Ecuador.
### Feature Description
A new spanish version contextualized to Cuba
### Possible Alternatives
Ageneral Spanish version not specific to any country
### Additional Information
I worked in the Spanish-Ecuador version but there are local uses of the languages that we need to adapt for the Cuban context. For example the names of political divisions.

**Comment by MateStrysewskeSym** [comment]
@urrape I've added Cuban Spanish to our Crowdin project: https://crowdin.com/project/sormas/es-cu#

Please feel free to add translations there!

**Comment by urrape** [comment]
> @urrape I've added Cuban Spanish to our Crowdin project: https://crowdin.com/project/sormas/es-cu#
> 
> Please feel free to add translations there!

Can you copy the content of the Spanish-Ecuador version in the Crowdin project, where we already worked to complete the spanish version? Then we can use the work done and adapt to the Cuban context the translation, but not loosing what have been already advanced.

Thanks in advance
pedro

**Comment by MateStrysewskeSym** [comment]
@urrape Unfortunately I don't know if that's possible. I did, however, add Spanish as a language; all translations for Spanish should also be automatically applied to all dialects of Spanish, including Cuban and Ecuador. If you put all the translations into the Spanish project and then overwrite the regional alterations in the dialect projects, you should have way less effort in the long term.

**Comment by MateStrysewskeSym** [comment]
- [ ] Fix "Suomi" accidentally being changed to "Suom"
