### ISSUE TITLE
"CaseDataDto is older than current version on server" during case import

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2141]
### Bug Description
When importing the same cases more than once and choosing to override changes, the import dialog labels these cases as errors and adds them to the error report with the message "CaseDataDto is older than current version on server". However, the existing cases are still overridden with the changes from the imported ones.

### Steps to Reproduce
1. Import a case using the detailed case import
2. Change the first or last name of the case person
3. Import the same file again and choose to pick and override the existing case

You may need to repeat step 3 in order for the bug to occur.

### Expected Behavior
The error message should not appear in the first place.

**Comment by MateStrysewskeSym** [comment]
Can't reproduce this anymore. Maybe it was fixed by another issue. This issue will be re-opened should the problem occur again.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I have the error again. Please import the attached  file on symeda server, its an excel file.

[sormas_import_case_templateTest.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4717101/sormas_import_case_templateTest.xlsx)

**Comment by MateStrysewskeSym** [comment]
Review: @MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
I have extended the comment with a todo.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  I still keep getting this error message with 1,41,0

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Sure. It has been fixed 5 hours ago and will be part of the next release.

**Comment by bernardsilenou** [comment]
vielen dank
