### ISSUE TITLE
Explain how to use "no and other facility" for case import [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2152]
### Problem Description
The case import does currently not explain how to do this.
For other health facility users have to enter the string OTHER_FACILITY
For home or other place: NO_FACILITY

### Proposed Change
Add a highlighted section to the import guide that explains how to do it.

### Additional Information
#2146

**Comment by Iheanacho2027** [comment]
It should be part of the data dictionary right?

**Comment by MateStrysewskeSym** [comment]
The data dictionary is automatically generated, so it would be difficult to add it there.

**Comment by MartinWahnschaffeSymeda** [comment]
I'd suggest to add code to the generator that puts those constants into the data dictionary in a similar way we are listing the values of enums.

**Comment by MartinWahnschaffeSymeda** [comment]
@ChristopherRiedelSymeda I have added two comments to the commit.
Once that is resolved you can move the issue to done.
