### ISSUE TITLE
Investigate Keycloak for Sormas

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#2153]
Try to setup OAuth2 for Sormas with local keycloak server using the existing connector and by checking the sample app:
https://git.vitasystems.dev/hip/oidc-glassfish-connector
https://git.vitasystems.dev/hip/oidc-glassfish-connector-sampleapp

Investigate changes required on sormas-ui, i.e. Vaadin with OAuth2

Investigate what integrating OAuth2 on android app takes
https://github.com/openid/AppAuth-Android

Useful links:
https://www.keycloak.org/docs/4.8/authorization_services/#_overview_architecture
https://vaadin.com/blog/implementing-sign-in-with-google-s-oauth-2-services

**Comment by StefanKock** [comment]
Keycloak is integrates since months
