### ISSUE TITLE
Bug on POE national user accounts

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2155]
### Bug Description
The case directory of the POE national user account shows an empty or null value even when there are cases within the user's jurisdiction (which is the entire nation) @bernardsilenou @MartinWahnschaffeSymeda @MateStrysewskeSym 
### Steps to Reproduce
1. Login as a POE national user
2. Navigate to the case directory

### Screenshots
<img width="822" alt="poe bug" src="https://user-images.githubusercontent.com/50739609/82513670-94b42180-9b0b-11ea-8daa-3f5034d1ee04.PNG">

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda @BarnaBartha @StefanKock @bernardsilenou this error still exists in the latest release

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls help me reopen this ticket

**Comment by MateStrysewskeSym** [comment]
Review will be taken care of by @MartinWahnschaffeSymeda
