### ISSUE TITLE
can't select covid 19 on dashboard slideshow

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2175]
### Bug Description
Filtering by this year on the dashboard, and trying to select covid 19 on the slideshow pops an error
### Steps to Reproduce
1. Filter by this year on the dashboard
2. Select COVID-19 on slideshow

@MateStrysewskeSym @MartinWahnschaffeSymeda 
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Will be fixed with the new release. See #2150.
