### ISSUE TITLE
Increase character length of free text fields

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2180]
### Feature Description
I'm referring to #1933, which introduced new free text boxes ('general comment') to cases and contacts. Please increase character length, best would be 2048 or even 4096.

### Problem Description
German health departments want to tell a story in some text boxes and therefore need more space.

### Proposed Change
Increase characters in the new comment fields introduced in #1933 . Please also add more characters to the 'follow-up status comment'.

**Comment by MartinWahnschaffeSymeda** [comment]
See #580
