### ISSUE TITLE
VAADIN running in debug mode and exceeding maximum connection pool

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#2183]
### Feature Description
Why is the vaadin running on debug mode? should it not be running on production mode?  
### Problem Description
Looks like the instance is exceeding maximum connection pool size based on the error in the screenshot...
![error1](https://user-images.githubusercontent.com/35563508/82920362-17573980-9f6f-11ea-97ba-a2a25074b433.PNG)
![vaadin_debug_mode](https://user-images.githubusercontent.com/35563508/82920372-1920fd00-9f6f-11ea-9fab-bed630ba25b6.PNG)

**Comment by JonasCir** [comment]
I just noticed that Vaadin is still running in debug mode which also might degrade performance. Not sure about the maximum connection pool though. @Seal33 Maybe put a small fix for this together? :)

**Comment by JonasCir** [comment]
@Seal33 mentioned that Debug mode can be actually quite useful. One solution could be to tie the vaadin debug mode with the DEVMOD server property and mention it in the docs.

**Comment by Seal33** [comment]
Debug mode can be disabled by adding
```
<context-param>
	<description>Vaadin Production Mode</description>
	<param-name>productionMode</param-name>
	<param-value>true</param-value>
</context-param>
```
to `sormas-ui/src/main/webapp/WEB-INF/web.xml` and `sormas-rest/src/main/webapp/WEB-INF/web.xml`

To access debug mode, you can go to your-url/sormas-ui/?debug.
However I've noticed that this is neither possible on the official demoversion, nor on the current tetstserver for Version 1.5. So it seems like production Mode is automatically disabled on these builds?

@Chinedar what console output are we looking at in your screenshots? I couldn't find those lines anywhere on my local build.

**Comment by JonasCir** [comment]
You see this in your logs after you firstly accessed the UI. Happens for me for mvn builds and Docker.

**Comment by Seal33** [comment]
I would suggest simply disabling the Vaadin-Debug mode in both web.xml files, and leaving a note somewhere in a README on how to enable it again. I ran into some very unreliable behavior locally, where debug mode was sometimes enabled and sometimes disabled with nothing set in the web.xml. If the debug mode is used regulary by some devs, we can always bind it to devmode afterwards with a separate issue. However for now it doesn't seem to me like it is a much used feature.

@JonasCir is there a specific README you would recommend where I could add the description?

**Comment by JonasCir** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_DEV_SETUP.md would be my first guess
