### ISSUE TITLE
Don't allow event participant list to contain the same person twice

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2188]
### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/82934803-63fd3d80-9f8c-11ea-916c-91aa5ac97250.png)

### System Details
* Device:
* SORMAS version: 1,40,1
* Android version/Browser:

**Comment by Fede923** [comment]
Hi, would a check for id be plausible?

**Comment by bernardsilenou** [comment]
@Fede923  Yes please,  it possible to check for the same person uuid among the list of event participants within the event and retain a warning message that person already exist  with in the event

**Comment by Fede923** [comment]
Hi, i see that the part of the events participants, in events section, has already been changed. Can you try if duplicate participants are still allowed?

I attach a screen of the current situation.

![Schermata del 2020-08-02 22-09-51](https://user-images.githubusercontent.com/16584902/89131522-afdcdd80-d50d-11ea-9740-3e11e39766e4.png)


Thx

Federico

**Comment by bernardsilenou** [comment]
@Fede923 Thanks for pointing it out, we will correct it in new release

to do:
- add a method for duplicate event participant detection. We can use just  look fro duplacate person uuid, ir if recommend all persons uuid in event  == person id of event participant being created.
work flow
1. When creating a an event participant, call the duplicate person detection ( this works fine)
2. After person is selected, call the duplicate event participant method
3. Add an icon called "merge duplicates"on event participant directory just as we have for cases.  

Goal of this issue is point 2, I will move point 3 to another issue
