### ISSUE TITLE
Event participants can't be deleted through bulk action

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2189]
### Bug Description
 Event persons cant be deleted by bulk action
### Steps to Reproduce
1.
2.

### Expected Behavior
- deletion persons should be possible
- If the person is linked to a case or contact, then  "deleted !=t" on the person table. We can add a variable on event table and set it to true, eg "personEventDeleted == t". If the person is not linked to any other entity in the db other than the respective event, then we can  additionally set deleted ==t on the person table.
### System Details
* Device:
* SORMAS version: 1,40,1
* Android version/Browser:

**Comment by max-hzi** [comment]
Walk-around: When the bug occurs, select one of the pre-set filters (all, officer tasks, my tasks). From there, everything works as expected.
