### ISSUE TITLE
Remove Firebase user reporting [1] 

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2190]
### Feature Description
The SORMAS app currently allows users to send text messages to the FIrebase service to report on technical problems.

### Problem Description
We can't gurantee that users won't send sensitive data.

### Proposed Change
Remove this feature, since there isn't a proper way to forward those reports to the repsponsible people in the country anyway.

### Possible Alternatives
Replace the report with something else #1355

### Review
@ChristopherRiedelSymeda

**Comment by MateStrysewskeSym** [comment]
Review: @leventegal-she

**Comment by leventegal-she** [comment]
Review: OK
