### ISSUE TITLE
Event participants only show upon page refresh

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2197]
### Problem Description
Whenever a new participant is added to an event, the page 'event participants' requires a refresh to show the new participant.

### Proposed Change
Automatically refresh the page when a new participant is added, as also new cases or contacts show up in the respective directory directly.

**Comment by bernardsilenou** [comment]
@max-hzi  same as #2186

**Comment by max-hzi** [comment]
True, I did not find this issue. Thanks.
