### ISSUE TITLE
Headings are not properly translated in languages other than the server language

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2198]
### Problem Description
The columns 'sex' and 'approximate age' show up in English (Version 1.39.1). Translations are not availible in the Crowdin tool.

### Proposed Change
Translate:
 'sex' to 'Geschlecht'
'approximate age' to 'Alter'

Edit: Futher translation missing on the top right.
'on' to 'am'
![Unbenannt](https://user-images.githubusercontent.com/63781233/83005565-3efede00-a011-11ea-9fd5-9d339406b9f2.PNG)

**Comment by bernardsilenou** [comment]
![image](https://user-images.githubusercontent.com/12996724/83006338-5e4a3b00-a012-11ea-85fd-4bc3a8c5f879.png)

**Comment by bernardsilenou** [comment]
@max-hzi  it it not already translated as you want?

**Comment by max-hzi** [comment]
My issue is that it does not show up correctly in Sormas.

**Comment by bernardsilenou** [comment]
Pleae retranslate it and save in crowdin.
@MateStrysewskeSym  will hen pull the latest translation and I hope it will be fine in the new release

**Comment by max-hzi** [comment]
Ok, I retranslated them; what about the terms '**approximate** age' and 'on'?

**Comment by bernardsilenou** [comment]
where does approximate age appear at front end? its the back end variable of age if i remember well.

**Comment by bernardsilenou** [comment]
we do no translate back end variables

**Comment by max-hzi** [comment]
![Unbenannt](https://user-images.githubusercontent.com/63781233/83022939-8e9ed300-a02c-11ea-95f1-69d1cbbc963b.PNG)

**Comment by bernardsilenou** [comment]
@max-hzi  I now understand you. It does not look like a translation problem. I think it is because the the backend column names used on the tables are not formatted.  
What we have to do is to relabel the headers of the table, "APPROXIMATE AGE"<--"AGE" 
@MateStrysewskeSym  am i right.

**Comment by MateStrysewskeSym** [comment]
Seems to be a general problem with headings, see #2209

**Comment by bernardsilenou** [comment]
More figure: I am logged in with English us, captions are either in =French or German
![image](https://user-images.githubusercontent.com/12996724/83439948-593b2080-a444-11ea-9f84-279a3e106f54.png)

![image](https://user-images.githubusercontent.com/12996724/83440015-74a62b80-a444-11ea-8fea-f52aa22b32d8.png)

![image](https://user-images.githubusercontent.com/12996724/83440098-a3240680-a444-11ea-99ea-2757e5bbb343.png)

**Comment by ChristopherRiedelSymeda** [comment]
The cause of the problem is the declaration of the headings directly in the html layout.These layouts are (probably) cached on the server and therefore internationalization does not work anymore.
