### ISSUE TITLE
Pull case ID if existing case is added to event

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2199]
### Situation Description
Existing cases can be added to events (duplicate search detects existing case). Sormas does not show the existing case ID in the participant directory. Instead, a new case can be created. This does not make sense as it is already a case.

### Feature Description
Sormas should show the existing case ID from this person in the participant directory.

**Comment by bernardsilenou** [comment]
@max-hzi  i created similar issue yda.
 I think for all case creation, either from event, contact, importation, new creation, etc we need to trigger the duplicate case detection method, and if a duplicate is found  and confirmed by the user, then we do the link and merge the two case data using the case that already exist in the db as reference.

**Comment by bernardsilenou** [comment]
see #2187

**Comment by max-hzi** [comment]
@MateStrysewskeSym I don't think my request is dealt with in #2187. In that issue its about event person to case conversion. In this issue here I am requesting to add an existig case to an event and show the ID in the event participant table.

**Comment by MateStrysewskeSym** [comment]
@max-hzi That's exactly what #2187 is about, alongside #2033.
