### ISSUE TITLE
Saving an new positive sample result for internal sample trigger automatic case classification

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2205]
### Bug Description
I know this is not the initial idea, but is this really a problem? Maybe we allow it as it is and when we will latter includes disease specific test types in SORMAS, then we can reactivate that only specific type of test should rigger it.
@MateStrysewskeSym ??
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I don't quite get the problem here. This is definitely not a bug, if anything it's a change request to exclude internal samples from the automatic case classification. We can't decide whether this should be changed or not. Maybe check back with Juliane and come up with a decision.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  We are saying the same thing. This request "it's a change request to exclude internal samples from the automatic case classification" was implemented long ago but it is not working now.
My question is do we need this constrain in the first place tight now?
I was think we can let it as it is

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I agree, but I'd like to know in which GitHub issue we removed internal samples from automatic case classification? As far as I know, we never did something like that.
