### ISSUE TITLE
Unified code formatting for java classes

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2206]
### Situation Description
Currently there are no clear rules how to format and sort code. Since we are using different IDEs and coding culture, reviewing code and merge/rebase is sometimes quite a mess. To get rid of that, the development team wants unified agreed rules how to format code.

### Feature Description

Scope of this ticket: .java files

1. Decide how the Java code shall look like.
2. Have **automatic** code formatting in Eclipse, IntelliJ and Android Studio be the same (or best: identical) rules.
3. Have same import order and rules for java classes.
4. Have documented rules how to setup your Git project and IDE workspace.
5. Document coding guidelines that can not be automated by IDE formatters.
6. Unified code formatting at one distinct point in time on all affected files to get rid of edit wars and be able to activate "Format all lines" as save action in IDE.
    - Review automated code formatting and apply `@formatter:off` for now messed up paragraphs.
    - Delete blank lines before closing brackets }.

### Additional Information

- Concept of shared profiles for code formatting is proven: Defined by Eclipse, imported in IntelliJ an Android Studio.
- Formatting rules of other vitagroup products will be used as a starting point (aligned and agreed over years).
- Coding guidelines documented in readme (to be clarified).
- When formatting the code: Maybe shortly before release (only few feature branches, less likely to need a hotfix to be merged into reformatted code)

**Comment by StefanKock** [comment]
I formatted all Java files **except sormas-app** and reviewed all touched classes, did manual improvements and deactivated code formatting where it really messed up the readability.

Next step: Proceed with code formatting of _sormas-app_ .

**Comment by StefanKock** [comment]
Formatting of sormas-app will happen together with @MateStrysewskeSym

**Comment by xavier-calland** [comment]
Wouldn't it be nice to have non-IDE specific tools for code style check and formatting?
Tools like [Spotless](https://github.com/diffplug/spotless) can be integrated into the build / check process and provide reformatting actions.
Furthermore, it's always possible to import style code rules into the IDE.

**Comment by StefanKock** [comment]
Code formatting for all java files is done and on development.

@xavier-calland thanks for the hint, we might look into it.
