### ISSUE TITLE
bug in sample directory for 1.41.0

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2210]
### Bug Description
The samples directory brings out a blank output for all diseases @Chinedar 
### Steps to Reproduce
1. go to samples directory
2. filter by all diseases

### Screenshots
<img width="791" alt="new bug" src="https://user-images.githubusercontent.com/50739609/83199876-f8f16980-a139-11ea-99c2-fc58b502e64d.PNG">

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by Iheanacho2027** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym this happens only with users who see almost 50,000 samples. Sometimes switching from the samples directory to the case directory may constitute this error. You may have to take a closer look at this.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 I can't reproduce this on the Nigerian server with a user that has access to > 60,000 samples. I'd need a specific list of all the steps that I need to perform in order to encounter this problem.

**Comment by Iheanacho2027** [comment]
This issue existed in 
1.41.0 and was resolved with 1.41.1, don't know how

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 Alright, good to know!
