### ISSUE TITLE
Creating an new entity called Outbreaks and defining its relation to cases, contacts and events

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2211]
### Situation Description
It is a common practice to define an outbreak within an outbreak. This outbreak is a relationship or mapping that  defines a cluster within the whole population. This cluster is defined by the user and could contain all the entities existing in the system such as cases, contacts, events, etc. The basic sett (menge) are the cases. This description if mainly on cases.
### Feature Description
We will add a new tab in the menu called "Outbreak" and place it below Event. We may need to rename the outbreak we have under configuration in order not to get users confused.
1 Attributes of outbreak/cluster in relation to cases. 
1,1 outbreak identifiers: Name,disease, region, district, outbreak epid number (“Häufungsschlüssel”), description, lat, long, date of report, reporting user, outbrekuuid, responsible SO. We will add the logic on how to generate the outbreak epid number latter, for now we just use a text field for users write it down.
1,2 Outbreak status: Active, closed, dropped
1,3 Outbreak type: Nosocomial, Non-nosocomial, Unknown
1,4 case tab to create cases. These cases will be tagged with the uuid of the cluster and used to filter them from the case table
1,5 For cases belonging to an outbreak, display their outbreak uuid in their case information view

1,5 All contacts linked to cases in a cluster will also have the respective cluster uuid on their contact table and contact information view
1,7 All cases in a cluster that initially resulted from events will also have the respective cluster uuid on their event participant table 

1,8 It should be possible to assign existing cases to existing outbreaks and build the link

Filtering variables:
Outbreak identifiers, status, type,,,,

Export options:
export of list of outbreaks
export of cases per outbreak
detail export of associated cases and contacts per outbreak

Import options
Importation of cases per outbreak

**Comment by max-hzi** [comment]
Further stage of #2093 (shall I close that issue?)

**Comment by MateStrysewskeSym** [comment]
No, should be left open because it's a different feature.

**Comment by bernardsilenou** [comment]
@markusmann-vg  @max-hzi @MateStrysewskeSym This issue is a detail description of point 1 in #2093 
Since we plan to work on #2093 in this sprint, we should begin programming as described here. The first step can be to have working methods to create an outbreak entity and liking cases to them. 
I will write a separate issue to detail refine  point 2 and 3 of issue #2093 
What i am writing is a combination of a report written by Julian after having a design thinking meeting with the team.

**Comment by JaquM-HZI** [comment]
@bernardsilenou is this still relevant in your opinion?

**Comment by bernardsilenou** [comment]
@JaquM-HZI the current event entity can be used for this purpose. I think we can close it
