### ISSUE TITLE
Letter/ certificate of quarantine automation

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2214]
### Situation Description
The German health departments have to issue attests for home-based quarantine for contact persons so that they are excused from work. Some sort of automation of this function is missing.

### Additional Information
A personal request from Gérard, please find his mail from 17.05.2020 (Markus and Martin were included). When will this feature possibly become available? Gérard would like to forward that info to the ministry of finance.

**Comment by JonasCir** [comment]
@syntakker can this be closed?

**Comment by syntakker** [comment]
@JonasCir I think so.
