### ISSUE TITLE
Remove slf4j dependency from sormas-base

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2218]
### Feature Description
We currently have a dependency to slf4j in sormas-base.

### Problem Description
Slf4j can't be used in sormas-api, because it does not work with sormas-app.

### Proposed Change
Move the dependency to sormas-ui, sormas-rest and sormas-backend.

### Possible Alternatives
Exclude it for sormas-api

**Comment by StefanKock** [comment]
@MartinWahnschaffeSymeda please review, it's already merged on development

**Comment by MartinWahnschaffeSymeda** [comment]
Looks good
