### ISSUE TITLE
Increase the search field reloading delay to 4 seconds

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2225]
### Bug Description
When Alphabets are typed on the search functionality, they disappear and reappear, and also changes to other alphabets not selected by the user, in a very unstable manner. This makes it annoying for the web users
### Steps to Reproduce
1. Go to case directory
2. Play around with alphabets on the search functionality

@MateStrysewskeSym @MartinWahnschaffeSymeda @bernardsilenou 

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
It could no reproduce it, All works fine for me.  Add more information please
Change your web browser and see it it helps

**Comment by Iheanacho2027** [comment]
Try to reproduce on the nigerian server.

**Comment by bernardsilenou** [comment]
@Iheanacho2027  I now understand, the responsiveness time is to short, the ui respond to every activity or text  that the user type.
@MateStrysewskeSym  will handle it

**Comment by MateStrysewskeSym** [comment]
We've already tackled this problem in the past by adding a delay before the user input is actually applied. If this delay is still not large enough, we basically have two options:

a.) Increase the delay between user input and the input being applied to the filters; this will make it better for users who type slowly, but might be confusing for fast typers
b.) Completely remove the responsiveness of the input field and adding a button to manually apply the input; I don't really know if that's better UX, and it might also be hard to tell whether this button is associated only with the input field or with all filters.

Which one do you prefer?

**Comment by Iheanacho2027** [comment]
This issue started before the release of 1.41.0. Please whatever was the case before the release of this version, users in Nigeria have asked we should retain it @MateStrysewskeSym

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 As far as I know, we didn't change anything about this logic in one of the last releases.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  Can we go for option "a" and see it it gets better?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou How long would you like the delay to be?

**Comment by bernardsilenou** [comment]
Since Nigeria has many cases, I think 6 seconds or more will be fine

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The amount of cases doesn't really matter I think. If we set the delay to 6 seconds, that means that the UI will not show any reaction for six seconds after the user has finished typing into the search field. I'm afraid that's going to be too much...

**Comment by bernardsilenou** [comment]
OK, Lets reduce it then please, but not less than 4 seconds.
Play on the Nigerian ui and see how it behaves, type slowly

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym @bernardsilenou With 1.42.3, its better, but still not very ok. Play with the search bar on both the configurations and users menu, then compare it with the search bar in the case directory. Can the field reloading delay that exists on the search bar of the case directory, be just as exact as what pertains in the search bar of the configurations and users menu

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 We haven't worked on this yet - that's probably why it's not okay yet. ;)

**Comment by bernardsilenou** [comment]
Similar to #2542

**Comment by Iheanacho2027** [comment]
Pls can this ticket be reopened @bernardsilenou This problem wasnt solved by #2542, this "disappear and reappear" action still happens in 1.50.0 even with the presence of apply filter. I was hoping that the presence of the apply filter is to make the textbox and other filters static as long as the apply filter button hasnt be touched

**Comment by MateStrysewske** [comment]
@Iheanacho2027 I can't reconstruct that problem anymore. There is no automatic update anymore after the introduction of the "Apply filters" buttons, and thus I don't see any issues with entered text disappearing when it's typed in too slowly anymore.
