### ISSUE TITLE
Add Case-Classification for Germany [3]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2230]
### Situation Description
The case classification which we use for SORMAS does not fit the needs of German authorities. 

### Feature Description
There are new Case Classifications, that will be manually set by the user. The logic and automatic setup will be added later, when the requirements are clear.
For now we need to add the following case classifications for the German system:

„nicht   klassifiziert“ [0. nicht klassif.] | 0 | NOT_CLASSIFIED
-- | -- | --
„klinisch diagnostizierte   Erkrankung“ [A. klin-diagnost.] | A | SUSPECT
„klinisch-epidemiologisch   bestätigte Erkrankung“ [B. klin-epidem. bestät.] | B | PROBABLE
„klinisch-labordiagnostisch   bestätigte Erkrankung“ [C. klin-labor. bestät.] | C | CONFIRMED
„labordiagnostisch   nachgewiesene Infektion, klinisches Bild nicht erfüllt“ [D. labor. ohne klin.  Bild] | D | CONFIRMED_NO_SYMPTOMS
„labordiagnostisch   nachgewiesene Infektion, klinisches Bild unbekannt“ [E. labor. und unbek. klin. Bild.] | E | CONFIRMED_UNKNOWN_SYMPTOMS
„kein Fall“ [X. kein Fall] | X | NO_CASE

The migration of the old cases is described in the attached excel.
There is a logic for the migration which has to be considered, wether an old case will be classified into 0 or A

[caseclassification.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4715046/caseclassification.xlsx)

Pages that have to be considered for that change:
-----
Cases

OUT OF SCOPE:
####################
Dashboard - no 0,A,B - (C;D;E   as confirmed in one number)
Transmission Chain - no 0,A,B   - (C;D;E as confirmed in one number)
####################
----

![grafik](https://user-images.githubusercontent.com/23217632/83609333-6fe59280-a57e-11ea-82c5-3b296dbc6766.png)

**Comment by MartinWahnschaffeSymeda** [comment]
Unclear:

1. How should the new clinical, epidemiological and lab confirmation fields be filled/migrated
2. How should the three fields and the case classification interact? We need to make sure that there is no inconsistent data in the system that would later need to be migrated

**Comment by markusmann-vg** [comment]
A. Klinisch diagnostizierte Erkrankung | B. Klinisch-epidemiologisch bestätigte Erkrankung | C. Klinisch-labordiagnostisch bestätigte Erkrankung | D. Labordiagnostische nachgewiesene Infektion, klinische Bild nicht erfüllt  Andere Symptome | D. Labordiagnostische nachgewiesene Infektion, klinische Bild nicht erfülltAsymptomatisch | E. Labordiagnostisch nachgewiesene Infektion, klinisches Bild unbekannt
-- | -- | -- | -- | -- | --
Klinik COVID-19 Symptome | Ja | Ja | ja |   |   |  
Klinik andere Symptome |   |   |   | ja |   |  
Klinik asympt./keine Symptome |   |   |   |   | ja |  
Klinik unbekannt |   |   |   |   |   | ja
Epidemiologisch bestätigt |   | Ja |   |   |   |  
Epidemiologisch nicht bestätigt |   |   |   |   |   |  
Labor negativ |   |   |   |   |   |  
Labor positiv |   |   | ja | ja | ja | ja
Kein Laborergebnis | ja |   |   |   |   |

**Comment by markusmann-vg** [comment]
![Bildschirmfoto 2020-06-03 um 12 57 45](https://user-images.githubusercontent.com/62540178/83629145-e217a080-a599-11ea-9cf1-78bab895ee59.png)

**Comment by markusmann-vg** [comment]
**Migration rule:**
We migrate all cases that were not classified to 0
=> There will be no old unclassified cases which will be migrated to A

**Comment by markusmann-vg** [comment]
[#2230-COVID_19_Übertragung in RKI Falldefinitionskategorien_GaPo_20200609.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4818855/2230-COVID_19_Ubertragung.in.RKI.Falldefinitionskategorien_GaPo_20200609.xlsx)

**Comment by markusmann-vg** [comment]
We should add a error message for selected combinations, which are not valid

**Comment by bernardsilenou** [comment]
This is the corrected mockup

![image](https://user-images.githubusercontent.com/12996724/85617497-a08d8900-b65f-11ea-978d-516c3c9399e7.png)

**Comment by markusmann-vg** [comment]
[CaseClassification#2230.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4835592/CaseClassification.2230.xlsx)

**Comment by markusmann-vg** [comment]
[CaseClassification#2230.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4835603/CaseClassification.2230.xlsx)

**Comment by markusmann-vg** [comment]
[CaseClassification.2230.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4836000/CaseClassification.2230.xlsx)

**Comment by markusmann-vg** [comment]
What are the possible dropdown options?

**Comment by bernardsilenou** [comment]
Will confirm from survnet and respond latter today pls

**Comment by bernardsilenou** [comment]
The categories are: yes, no, unknown, and NA when not selected. See picture please. The captions have been changed slightly, thus we need to translate accordingly.
![image](https://user-images.githubusercontent.com/12996724/86008425-09d31a80-ba19-11ea-956d-082a4ecbe44a.png)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Thanks!

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  Danke

Just a note: For the German form , we display NA and Unknown just as we do for symptoms

**Comment by BarnaBartha** [comment]
@markusmann-vg @MateStrysewskeSym 
Can you please confirm the following:

-  the "Kategorie der Falldefinition" = "Detaillierte Fallklassifizierung" = "Case classification" and that it becomes a dropdown instead of an option group? In @bernardsilenou comment I see it as a dropdown but in the moqups (https://app.moqups.com/3NUENEwuOE/edit/page/afc481082) it is still an optionGroup. 
- the "Klinisches bild erfullt" is a dropdown for the YES NO UNKNOWN enum 
- do we have to consider the CaseClassification.2230.xlsx for the migration or only for validation on edit later? If it has to be considered for the migration what happens to a confirmed case form the db that does not have any of the corresponding to C symptoms true ?
- "We should add a error message for selected combinations, which are not valid" - which are those combinations ? (i am guessing if clinicallyConfirmed epidemiologicallyConfirmed labConfirmed are all YEs than the case classification cannot be X ("kein-fall" / no case - as that makes no sense) - we need more specifics here

**Comment by markusmann-vg** [comment]
a.) confirmed
b.) confirmed 
c.) just for the validation and edit later part
d.) You can use the validation checks, if the check shows, that a check should not be able to make, we throw an error message and reset the checkmark

**Comment by BarnaBartha** [comment]
English translations

„nicht   klassifiziert“ [0. not classified] | 0 | NOT_CLASSIFIED
-- | -- | --
„klinisch diagnostizierte   Erkrankung“ [A. clin-diagnost.] | A | SUSPECT
„klinisch-epidemiologisch   bestätigte Erkrankung“ [B. clin-epidem. confirmed] | B | PROBABLE
„klinisch-labordiagnostisch   bestätigte Erkrankung“ [C. clin-labor. confirmed] | C | CONFIRMED
„labordiagnostisch   nachgewiesene Infektion, klinisches Bild nicht erfüllt“ [D. labor. w/o clin. picture] | D | CONFIRMED_NO_SYMPTOMS
„labordiagnostisch   nachgewiesene Infektion, klinisches Bild unbekannt“ [E. labor. and unknown clin. picture] | E | CONFIRMED_UNKNOWN_SYMPTOMS
„kein Fall“ [X. no case] | X | NO_CASE

**Comment by BarnaBartha** [comment]
* Migration script for German servers to migrate 0 -> A where it shuold.
```
UPDATE cases
SET caseclassification = 'SUSPECT'
FROM cases c
         LEFT JOIN symptoms s ON c.symptoms_id = s.id
WHERE c.disease = 'CORONAVIRUS' and c.caseclassification = 'NOT_CLASSIFIED'
  and (s.pneumoniaclinicalorradiologic = 'YES' or
       s.difficultybreathing = 'YES' or
       s.sorethroat = 'YES' or
       s.cough = 'YES' or
       s.runnynose = 'YES' or
       s.respiratorydiseaseventilation = 'YES' or
       s.acuterespiratorydistresssyndrome = 'YES');
```
Note: as discussed this does not include the migration C -> D / E, but if needed such script can be provided.

* Migration script needed when a German server becomes a non-german server
For example locale is changed from de -> en. 
```
UPDATE cases
SET caseclassification = 'CONFIRMED'
FROM cases c
WHERE c.caseclassification = 'CONFIRMED_NO_SYMPTOMS' or c.caseclassification = 'CONFIRMED_UNKNOWN_SYMPTOMS'
```
Note that this should not be the case for productive systems but it is a common scenario for development systems.
