### ISSUE TITLE
Changes in follow-up date triggers pop-up window to ask for changes for quarantine end date [1]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2233]
### Feature Description
When the follow-up time is changed manually a pop-up window should ask if the quarantine end time shall also be adjusted automatically. When ”yes” is clicked, the quarantine end date should be changed to the same end date as the follow-up end date. In case of "no", quarintine end date should remain untouched.

**Comment by markusmann-vg** [comment]
reducing and extending the follow-up date, which might change the quarantine end date is possible
When the quarantine end date is also extended, then the checkbox (quarantine end date extended) is ticked and stored in the db.

**Comment by bernardsilenou** [comment]
@markusmann-vg  This suggested refinement is related to issues #2426 #2235 . I think its good to see the complete story while implementing any of these issues.
1. Use the followup until date as reference date for quarantine end date. Cases will also have followup until date based on issue #2488 
2. Set default value of quarantine end date == followup until date
3. Followup until date is not possible to be reduced, thus can only be extended. If over written and extended, ask is user want to extend the quarantine end date, if yes, then match it to followup until date and set "quarantine period extended" which we can now call "quarantine period modified" to "Extended"
4. Contrary to followup until date, quarantine end date can be reduced and also increased from its default and expected value. 
4.1 If quarantine end date is reduced  from its default followup until date, show dialog box to ask user if they want to reduce it from it expected end date. if yes, then set "quarantine period modified" to "reduced" and do not modify followup until date.

4.2 If quarantine end date is increased  from its default followup until date, show dialog box to ask user if they want to increase it from it expected end date. if yes, then set "quarantine period modified" to "extended" AND also ask if they want to extend the followup until date, if yes then extend accordingly.
