### ISSUE TITLE
Quarantine end field to suggest end of follow-up date [1]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2235]
### Feature Description
When the quarantine field is activated, the “quarantine end” field should suggest the same end date as the follow-up end. If the quarantine end date is changed manually, a pop up window should ask if the follow-up end date should be adjusted as well. If “yes” is clicked, the follow-up end date should be changed to the quarantine end date. In case of "no", the follow-up date should remain untouched (similar to #2233).

**Comment by markusmann-vg** [comment]
Do together with #2233

**Comment by vlad-ciucescu** [comment]
As per @bernardsilenou 's comment in #2233 

>  4.1 If quarantine end date is reduced from its default followup until date, show dialog box to ask user if they want to reduce it from it expected end date. if yes, then set "quarantine period modified" to "reduced" and do not modify followup until date.

> 4.2 If quarantine end date is increased from its default followup until date, show dialog box to ask user if they want to increase it from it expected end date. if yes, then set "quarantine period modified" to "extended" AND also ask if they want to extend the followup until date, if yes then extend accordingly.

The quarantine extended checkbox implemented in #2264 now shows either "quarantine period reduced" or "quarantine period extended" based on how the date was modified.
This also implies changes to the database to store the new "quarantine period reduced" status, and a new filter.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOT
