### ISSUE TITLE
Can not connect to SORMAS Server after Sync

### ISSUE THREAD

**Issue by shaneelprakash2910** [hzi-braunschweig/SORMAS-Project#2242]
### Bug Description
After the successful app update and connection to SORMAS server, the system prompt an error message stating that "Could not connect with SORMAS Server. Try again later "

### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/63214786/83612900-24130780-a5d7-11ea-880d-1e46d14fbebb.png)

### System Details
* Device: Tablet - Alcatel - Android version 9.0
* SORMAS version: 1.41.1
* Android version/Browser: Android version 9.0

**Comment by MateStrysewskeSym** [comment]
@shaneelprakash2910 Are you trying to connect to a local server or to a production server? Are you sure that the server was online and reachable when the app tried to connect to it?

**Comment by shaneelprakash2910** [comment]
Hi Mate,

Yes, we were connecting to the remote Tablets using TeamViewer, and this
guarantees that the internet was well and fine.

The tablets were pointing to the production server. We had about 7
incidents from the field.

Kind Regards,
SP

**Comment by MateStrysewskeSym** [comment]
Have you tried it again afterwards? The error message suggests that it's a temporary connection problem - did anyone, by chance, change the server URL in the settings?

**Comment by shaneelprakash2910** [comment]
Yes, we tried couple of times.

I had the same perception earlier but when I tried it gave me the same
error.

**Comment by MateStrysewskeSym** [comment]
@shaneelprakash2910 Does this happen for every tablet you're using or are there tablets that are still able to connect?

**Comment by shaneelprakash2910** [comment]
So far we had 7 such incidents.

I am yet to get the feed back from other users.

**Comment by bernardsilenou** [comment]
@shaneelprakash2910 Please keep some of the tablets with you and we will have a look tonight,

**Comment by fhauptmann** [comment]
I just tested webserver hardening. But SSLlabs report says web server cipher suites and encryption algorithms are supported from Android 4.4.2 upwards.

**Comment by shaneelprakash2910** [comment]
Thanks Bernard.

Calling you at 9am.

Kind Regards,
SP

**Comment by bernardsilenou** [comment]
no longer a bug
