### ISSUE TITLE
Event location not properly shown on the dashboard map

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2248]
### Steps to Reproduce
1. Create an event
2. Add lat and long
3, Visualize on map on dashboard

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Works for me. Please note that only events that are associated with a disease show up in the dashboard, and only if the respective is selected in the slide show. You also have to enable the map layer.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I tested and the event show on the map now. I realised that the location of the event is not the lat and long recorded to the event. I also realised that event also appear on the map when they do not have any lat and long. 
We decided sometime in the past to show entities without lat and long using the centriods of their district. Entities show up on map at a position that are not close to their districts.
We also prevented entities that do not fall in the boarder of the country from showing up on the map, but i do not thing this has any affect on this.
Please can you also check to be sure i am not missing something?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I'll have a look at it.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I've fixed the manually entered latitude and longitude not being shown correctly on the map. Concerning the districts, that heavily depends on whether there is an appropriate geo shape for the district in question. Did you test this on the Nigerian or on a demo server?

We don't prevent entities outside the border from showing up in the map; what we do is that we don't allow automatic GPS coordinates to be collected in the mobile app if they're outside the country. That, for example, doesn't affect events created in the web app.

**Comment by bernardsilenou** [comment]
> @bernardsilenou I've fixed the manually entered latitude and longitude not being shown correctly on the map. Concerning the districts, that heavily depends on whether there is an appropriate geo shape for the district in question. Did you test this on the Nigerian or on a demo server?

I tested on .symeda and also on the French test server, I found the same thing.
> 
> We don't prevent entities outside the border from showing up in the map; what we do is that we don't allow automatic GPS coordinates to be collected in the mobile app if they're outside the country. That, for example, doesn't affect events created in the web app. 

(thanks for clarity, this is a perfect solution)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Neither our demo nor the French test server have shape files because those are currently only available for Nigeria and Ghana, so that's probably the problem.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Ohhhh that should absolutely be the cause.
One questions for my understanding please. If I have the right lar and long picked form the google maps, based on the new  solution that the system uses the lat and long provided and only fall back when it is missing. Will missing shape files then matter?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou It's currently not possible because we don't yet have a shape file import and we can't ship shape files for all possible countries with SORMAS.

If an event has a latitude and longitude, the shape files never matter and the event will always be displayed according to the geo coordinates.
