### ISSUE TITLE
Delete button on line listing window not fully shown depending on the language

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2258]
### Bug Description
There is an additional random box on the first line of the ui for line listing of cases, it appears only when the language setting is French. 
### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/83794432-4b80d780-a69e-11ea-9861-0972332f111d.png)

### System Details
* Device:
* SORMAS version: 1,41,0
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
You mean the one to the right? I think that's the button to delete the row, not a random box. We're having serious problems with layouting the line listing window when it comes to internationalisation because the amount of fields we need to display.
