### ISSUE TITLE
Fonction EFFACER est KO

### ISSUE THREAD

**Issue by Emond-Fuseau** [hzi-braunschweig/SORMAS-Project#2259]
Bonjour,

Il n'est pas possible de supprimer des "cas" ou des "contacts". En effet, quand on clique sur le bouton "effacer", nous avons le message d'erreur ci-dessous : ("Une erreur s'est produite. L'erreur a été automatiquement signalée au support.")
![image](https://user-images.githubusercontent.com/65915564/83799048-7d496c80-a6a5-11ea-9e80-6acfa9a98803.png)

Merci par avance de votre aide.

Bien cordialement,

Jeanne-Marie Emond-Fuseau
* Device:
* SORMAS version: 1.40.1
* Android version/Browser:

**Comment by bernardsilenou** [comment]
envoyez-moi un numéro pour vous appeler s'il vous plaît

**Comment by bernardsilenou** [comment]
Passez à 1,41,1 s'il vous plaît

**Comment by MateStrysewskeSym** [comment]
@Emond-Fuseau Hey! We only provide support in English on this GitHub (unless Bernard is able to help out).

**Comment by Emond-Fuseau** [comment]
Bonjour Bernard,


Vous pouvez me joindre au n° dans ma signature.

?

Bien cordialement,



Jeanne-Marie Emond | Consultante Sénior

CGI Grand-Ouest

Immeuble Energies - 3, avenue de Belle Fontaine - 35510 Cesson-Sévigné

M. : +33 (0)7 76 78 95 72

jeanne-marie.emond@cgi.com<mailto:prenom.nom@cgi.com> | cgi.fr<http://www.cgi.fr/>


________________________________
De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : jeudi 4 juin 2020 20:33
À : hzi-braunschweig/SORMAS-Project
Cc : EMOND, Jeanne-Marie (DSSIS/EXTERNES); Author
Objet : Re: [hzi-braunschweig/SORMAS-Project] Fonction EFFACER est KO (#2259)


envoyez-moi un numéro pour vous appeler s'il vous plaît

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hzi-2Dbraunschweig_SORMAS-2DProject_issues_2259-23issuecomment-2D639071615&d=DwMFaQ&c=BMMjOd5rMwijTOshDELeaSyLbdw3FGdGqNcuGNpHb2g&r=u2pe4TQ-fgIt5kapr5eOoUl0SHTwE9jDvm7NMWQVehauQ4XErB4xP6mjZh4DV0jl&m=Ygwing0byYNFqOP3KMNr1dyCQ3YGSlT02vYIUzfXvIo&s=i7NTlrdBPUMHI5_oK8x815YBD6Oef0FQe-T-aZwYyg4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APW4VLBAREDHBDFNLSJTGKDRU7ZKPANCNFSM4NS4S7CA&d=DwMFaQ&c=BMMjOd5rMwijTOshDELeaSyLbdw3FGdGqNcuGNpHb2g&r=u2pe4TQ-fgIt5kapr5eOoUl0SHTwE9jDvm7NMWQVehauQ4XErB4xP6mjZh4DV0jl&m=Ygwing0byYNFqOP3KMNr1dyCQ3YGSlT02vYIUzfXvIo&s=NClj03KQG8wUF4sOl-pdSAZESCs7kVl0tKSRNdUuqVk&e=>.

________________________________

Les ministères sociaux agissent pour un développement durable.

Préservons l'environnement : n'imprimons que si nécessaire !

**Comment by bernardsilenou** [comment]
Assurez-vous que la dernière version de SORMAS est installée sur le serveur. Comme Maté l'a mentionné, les problèmes de github doivent être communiqués en anglais pour que vous obteniez une assistance optimale.
Si vous rencontrez toujours des difficultés, envoyez un message et je vous appellerai lundi prochain.
Merci

**Comment by Emond-Fuseau** [comment]
?Bonjour Bernard,


Nous avons migré sur la v.1.42.3 en formation aujourd'hui et avons toujours les mêmes problèmes --> ex.: message d'erreur: "une erreur s'est produite - l'erreur a été automatiquement signalée au support" quand on clique sur le bouton "effacer":

[cid:d7467284-ca0a-46a2-84bb-d900a7d3c271]?


Merci par avance de votre retour.


Bien cordialement,


Jeanne-Marie Emond-Fuseau

________________________________
De : Silelou Bernard Chawo <notifications@github.com>
Envoyé : vendredi 5 juin 2020 21:46
À : hzi-braunschweig/SORMAS-Project
Cc : EMOND, Jeanne-Marie (DSSIS/EXTERNES); Mention
Objet : Re: [hzi-braunschweig/SORMAS-Project] Fonction EFFACER est KO (#2259)


Assurez-vous que la dernière version de SORMAS est installée sur le serveur. Comme Maté l'a mentionné, les problèmes de github doivent être communiqués en anglais pour que vous obteniez une assistance optimale.
Si vous rencontrez toujours des difficultés, envoyez un message et je vous appellerai lundi prochain.
Merci

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hzi-2Dbraunschweig_SORMAS-2DProject_issues_2259-23issuecomment-2D639807294&d=DwMFaQ&c=BMMjOd5rMwijTOshDELeaSyLbdw3FGdGqNcuGNpHb2g&r=u2pe4TQ-fgIt5kapr5eOoUl0SHTwE9jDvm7NMWQVehauQ4XErB4xP6mjZh4DV0jl&m=z_WSWk7uOeWjtprTplNN5J1o3ppYnzghm0XSjDPTyQo&s=gEGriTjYA1BalMrpGAgGVmQ41qXya2w2Axx03c2ACTo&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APW4VLH7X6JMAFWINNP6F2LRVFKTFANCNFSM4NS4S7CA&d=DwMFaQ&c=BMMjOd5rMwijTOshDELeaSyLbdw3FGdGqNcuGNpHb2g&r=u2pe4TQ-fgIt5kapr5eOoUl0SHTwE9jDvm7NMWQVehauQ4XErB4xP6mjZh4DV0jl&m=z_WSWk7uOeWjtprTplNN5J1o3ppYnzghm0XSjDPTyQo&s=uVXT6ndZj5PQVylhdFajfVAhHYeY7cTF4hISkl6tefg&e=>.

________________________________

Les ministères sociaux agissent pour un développement durable.

Préservons l'environnement : n'imprimons que si nécessaire !

**Comment by StefanKock** [comment]
Due to merge issues, this problem with concerning french language when deleting objects, see #2342. It should be fixed (again) in version 1.43, when new translations are joined.

**Comment by bernardsilenou** [comment]
@Emond-Fuseau The problem has been solved in the new release scheduled today. Change your language to English and all will be fine. When you will have the new release, you can then change the language back to French
