### ISSUE TITLE
User roles and responsibilities in APMS

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#2267]
[SIA Data Collection Roles and Responsibilities 9Mar2020.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4736647/SIA.Data.Collection.Roles.and.Responsibilities.9Mar2020.docx)
@MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
That's very helpful. I have extracted all entries that relate to one of the forms we plan to implement in the pilot for the intra-campaign phase:

Role | Level | Data Collection   Tools Completed | Which   organization collects this data | Which   organization enters and house the data
-- | -- | -- | -- | --
Provincial Polio Officer (PPO) | Provincial | Household   monitoring checklist/ICM | WHO | WHO/EOC
. | . | Team monitoring checklist | WHO | WHO/EOC
. | . | Supervisor monitoring   checklist | WHO | WHO/EOC
. | . | Revisit day checklist:   Cluster coordinator  daily   compilation sheet days 1-3 and 5 | WHO | WHO/EOC
District Coordinator | District | ???? |   |  
Cluster Supervisor | Cluster to District | Cluster   supervisor compilation sheet days 1-3 and 5 | EOC/WHO | EOC/WHO

Questions on this:

1. What does "Cluster to District" mean?
2. Is this list missing a data entry form needed for the pilot?
3. Can any of the forms be entered by another user role? If so, we need a complete list.
4. Is the PPO entering every single monitoring list into the system? E.g. there could be 100+ teams within one province, each having one team monitoring form, right?

**Comment by hzi-old** [comment]
Questions on this: @MartinWahnschaffeSymeda 

What does "Cluster to District" mean?
***It means that the cluster level supervisors fill out information of compiled teams and submit it to the district level. The district level compiles information by clusters and submit it to the Province. At the provincial level, all data compiled is by clusters and districts. Lowest level being clusters. ***
Is this list missing a data entry form needed for the pilot?
**** We need to compare with the form list that Ben sent to you. ****
Can any of the forms be entered by another user role? If so, we need a complete list.
For data entry purpose, I will suggest that the forms can be entered by any of the user roles, just like case creation in SORMAS. But other functionalities and views based on user rights and roles.***
Is the PPO entering every single monitoring list into the system? E.g. there could be 100+ teams within one province, each having one team monitoring form, right?
****The PPO does not enter team level data into the system. He takes the compiled data by cluster level and enters into the system by districts. E.g Number of clusters with missed children, Number of refusals by clusters in a district etc. **** You can have almost 6000 clusters in one province.

@MartinWahnschaffeSymeda We will get information from the country about the missing roles and ??? in the table.  I have forwarded to Ben. 

Regards

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba Thanks. I'd like to go into more detail on the PPO:
I'm looking at the example of the team monitoring form as it's created in this mockup:
https://app.moqups.com/3NUENEwuOE/view/page/aebb40307

When the PPO is the one entering this form into the system on cluster level we would have to change the form, right?! Would this mean that for every yes/no question we would instead have one field with total number of teams and then e.g. a field: 1) Number of teams with at least one team member resident of same area (villages)?

**Comment by MartinWahnschaffeSymeda** [comment]
Looking at the compilation sheets we have for provincial and national users, it became clear that data is not entered into the system in an aggregated way. Instead those sheets contain a list, with each row being the actual data of one paper/Excel form (e.g. for a single team). See also #2011 

We should look into the user roles again, once we have a basic implementation of the campaign data entry and the dashboard.

**Comment by MartinWahnschaffeSymeda** [comment]
The user roles should work as is, based on their limitation to specific jurisdictions. 

What needs to be done is to have only logins for the following user roles on the login page of the demo system:

Cluster Coordinator = Community level (Community Informant in SORMAS)
District Coordinator = District level (Surveillance Officer in SORMAS)
Provincial Coordinator = Region level (Surveillance Supervisor in SORMAS)
National Coordinator = National Level (National user in SORMAS)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] give cluster coordinator access to the web app

**Comment by MartinWahnschaffeSymeda** [comment]
Since #1960 is the only remaining thing for this and has been moved to post-pilot, I will close this one.
