### ISSUE TITLE
Campaign form schema definition [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2268]
### Situation Description
Multiple forms are used to entered data during a vaccination campaign. The content of these forms can change from campaign to campaign and should ideally be configurable.

### Feature Description

- [x] Create a CampaignFormDefinition entity that will hold:

- a unique id of the form (e.g. vaccinationHouseToHouse) 
- a language code - leaving this empty means that the json field contains the full form definition and English captions
- a list of CampaignFormElement as defined below. Should be stored as a json field matching the examples provided below.

- [x] Create a CampaignFormElement class:

- type: string based on a list of structing types (label, section) and values types (integer, string, yesno, later maybe enum)
- id: string - only needed for value types and labels (so they can be translated)
- caption: the caption in English or the defined language. Can have basic HTML elements (bold, italic, headers, line break)
- style: special styles to apply to the field:
  * inline: Will put the caption above the field and display the field in line with others. Default for integer, string and enum fields.
  * row: Will put the caption on the left side of the field. Default for yesno fields.
  * first: Make sure the field is the first in line - will start a new line if not.
  * col-1, col-..., col-12. Width of the field. 12 represents the full screen width (as in the [Bootstrap grid layout](https://getbootstrap.com/docs/4.5/layout/grid/)). All fields have a default of col-4. When combined with the row style, it defines how big the field should be, with the caption taking the remaining space in the row.
- dependencyParentField, dependencyParentValues: Only show this field when the parent field has one of the defined values

Additional properties not needed now (type = "enum"):

- typeValues: array of possible values for the field
- typeCaptions: array of strings containing the captions of all those values 

Note that type and type values are ignored for translation entries.

- [x] Create Services, Facades, DTOs that allow to access this definition. 
- [x] Create a unit test that takes the json in the example and correctly loads it into dtos.

An example of this has been defined here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/1991#issuecomment-639486603
And an translation example here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/1991#issuecomment-639524028

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda Yes.
