### ISSUE TITLE
Add performance indicators to Dashboard, each with min. max, median and mean:

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2274]
### Situation Description
Performance indicators of timeliness are missing
### Feature Description
- Time from date of symptom onset to date of notification
- Time from date of lab sample taken to date of lab result entered in system
- Time from date of notification to date of first visit of all contacts of the respective case
- Time from date of lab sample taken to date of lab result entered in system
- Time from date of symptom onset to first date of presenting to health facility
- Time from date of hospitalization (stationary care) to  date of discharge from stationary care
- Percent of cases admitted to stationary care at health facility (this means only those who are kept at health facility for treatment at least one night)

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou We already have an issue for KPI: #904. Please add additional indicators there.

**Comment by bernardsilenou** [comment]
Thanks, I forgot already
