### ISSUE TITLE
Schema migration is broken since sql code formatting

### ISSUE THREAD

**Issue by xavier-calland** [hzi-braunschweig/SORMAS-Project#2277]
With recent code formatting in https://github.com/hzi-braunschweig/SORMAS-Project/commit/b90693e3f7022d45cc213f5e4139102cce6e6c56#diff-ec7c690ec7725a5d3c12e991ddcd4742 @ChristopherRiedelSymeda , sql migration is not working.

### Steps to Reproduce
1. start application with an empty database

### Expected Behavior

Tables creation

### Additional Information

`de.symeda.sormas.backend.common.StartupShutdownService:updateDatabase()` reads sql file line by line searching for lines matching `SCHEMA_VERSION_SQL_PATTERN` https://github.com/hzi-braunschweig/SORMAS-Project/blob/ae887db97d0555257c2dfd1452bb216d9dda5a19/sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java#L101-L104

Now INSERT commands are on 2 lines (e.g. https://github.com/hzi-braunschweig/SORMAS-Project/blob/ae887db97d0555257c2dfd1452bb216d9dda5a19/sormas-backend/src/main/resources/sql/sormas_schema.sql#L648-L649), so it never matches `SCHEMA_VERSION_SQL_PATTERN` and no sql commands are executed.

### Proposal

* change sql file format : keep `INSERT INTO schema_version (…) VALUES (…);` on one line 
* throw an exception if there're sql lines in `nextUpdateBuilder` after reading all the lines in the file (when exiting `while (scanner.hasNextLine())  {…}`) to be sure all sql lines are executed

**Comment by StefanKock** [comment]
In #1984 there were many non-java files formatted (I assume by accident).

**Comment by MateStrysewskeSym** [comment]
@StefanKock Can you correct this please? I'll update the guide with a hint that "Do not format other file types" should be ticked in IntelliJ.

**Comment by StefanKock** [comment]
I reverted the commit that messed up a lot of non--Java files and merged it to development.
