### ISSUE TITLE
Error displayed when Tasks menu item is accessed from a National Clinician login

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2283]
### Bug Description
When Tasks is accessed from a National Clinician login an error is displayed.

### Steps to Reproduce
1. Login to https://test.sormas.netzlink.com/sormas-ui/login as National Clinician
2. Click on Tasks menu item

### Expected Behavior
No error must be displayed when Tasks is accessed.

### Screenshots
![Tasks_NatClin account](https://user-images.githubusercontent.com/62763628/84149574-f9a2cd80-aa60-11ea-9361-7f2b9ce72ae3.PNG)

### System Details
* Device:
* SORMAS version:1.42.0 Snapshot
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
Seems like this has been resolved already. Can't reproduce it, neither on the Netzlink test system nor on my local system.
