### ISSUE TITLE
Setup demo server with infrastructure for AFG

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2294]
Posted by Daniel:

https://drive.google.com/drive/folders/1M15aLTWrrOgUfqbeoU5V_4tFyrVgNeV1 for WHO admin 2 and 3 for Afghnistan adminstrative level units
[fwdwhopolioadminshapefiles.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4724257/fwdwhopolioadminshapefiles.zip)
[GLOBAL_ADM0.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4724258/GLOBAL_ADM0.zip)
[rewhopolioadminshapefiles.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/4724261/rewhopolioadminshapefiles.zip)

_Originally posted by @hzi-old in https://github.com/hzi-braunschweig/SORMAS-Project/issues/2002#issuecomment-638258249_

Next step:
Finalize mapping of SORMAS entities to the jursidiction levels in AFG.

Based on the needed user roles (#2267) I'd suggest the following:

* AFG region -> SORMAS area
* AFG province -> SORMAS region
* AFG district -> SORMAS district
* AFG campaign cluster -> SORMAS community

**Comment by MartinWahnschaffeSymeda** [comment]
@bn1010 Sorry, can you post the merged file with the infrastructure/regions for Afghanistan here again? I couldn't find it anymore.

**Comment by MartinWahnschaffeSymeda** [comment]
[Area_Region_District_Children.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5224799/Area_Region_District_Children.txt)

**Comment by nliakm** [comment]
Import files for area, region, district and community:
[sormas_import_area_template.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5225787/sormas_import_area_template.txt)
[sormas_import_region_template.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5225790/sormas_import_region_template.txt)
[sormas_import_district_template.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5225789/sormas_import_district_template.txt)
[sormas_import_community_template.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5225788/sormas_import_community_template.txt)

**Comment by hzi-old** [comment]
[Afghanistan_Districts_Provinces_wRegions.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5226603/Afghanistan_Districts_Provinces_wRegions.xlsx)
@MartinWahnschaffeSymeda
