### ISSUE TITLE
Answers to Questions from in country Afghanistan (Concept)

### ISSUE THREAD

**Issue by danieltomaba** [hzi-braunschweig/SORMAS-Project#2298]
@MartinWahnschaffeSymeda 
***Questions on each form***
1. Who will most likely enter it, where and when? Who can alternatively enter it, where and when? ***Answer*** From team to provincial and national level people, during the camping days, at relevant areas ( team, cluster, zone, district, province).
2. For which forms is it possible that data is entered on a higher level (e.g. aggregated for the whole district)? 
**Answer*** From cluster level forms.
3. Which fields (data entry boxes) are mandatory?
System may have option to warn users when leaving a field blank but still allow blank entry. 
***Great Idea, it is needed.***
4. Are there limitations in terms of the user's jurisdiction? E.g. a user should not be able to enter data for another province? 

***Answer*** If possible, it will be good, if it can be designed that national level users can have access to forms of all provinces and provincial level and district level users can have access to their relevant province and district. However, I am wondering how to apply it, when we do not have any specific identification code for the users.

****Questions on the campaign data list****
https://app.moqups.com/3NUENEwuOE/view/page/a86bc1ba5 https://app.moqups.com/3NUENEwuOE/view/page/ad33c5c37
1. Which columns should be shown for each form in the list of entered forms? 
***Answer*** The columns currently shown is fine and needed to be shown. 

****Questions Team Monitoring Checklist****
https://app.moqups.com/3NUENEwuOE/view/page/aebb40307
1. Please provide an example for “Agency/Org” 
*****Answer**** e.g: NEOC, WHO, UNICEF
2. Is one comment field needed for every for every form on the question, or would one comment field for the whole form be acceptable? 
***Answer**** For whole form but the comment field need to have space for > 250 words
3. Should there be aggregated data entry (e.g. sum of all teams of a cluster)?
***Answer**** Yes  E.g. The total number of: question 1=yes, number question 1=no, number question 1=unknown

*****Questions HH Monitoring Checklist****
https://app.moqups.com/3NUENEwuOE/view/page/a91d838de
1. For "vaccination teams going house to house", is this to confirm whether house to house visiting is possible given the situation in that area? 
***Answer*** In areas with security and where permission can be taken for H2H campaign, the H2H visiting is possible. Where the permission is not given or the security is not good. We use cite to cite/ massjed to massjed campaign approach or health facility to health facility campaign. 

2. Should there be aggregated data entry (e.g. sum of all teams of a cluster)? 
***Answer*** Yes, the HH monitoring checklist are compiled into one form. The HH monitoring is conducted based on cluster sampling approach. We usually select and monitor some houses of each team and each cluster during the campaign days. Usually all houses and all teams are not monitored. 

****Questions Aggregated HH Tally Sheet****
https://app.moqups.com/3NUENEwuOE/view/page/aff46b0e2
1. Are cluster supervisor and communication supervisor APMS users? => could be users. 
***Answers*** Yes they are users: Idea: text field proposing based on users in the system, but allowing the user to enter custom data
2. Tally Sheet fields vs. daily reporting? Clarify: Is the need to build data entry forms from the aggregate view, or from tally sheet view which looks at household data compared to daily reporting which looks at compiled data.  
***Answer*** From tally sheet view

**Comment by MartinWahnschaffeSymeda** [comment]
Moved your asnwers to #1989
