### ISSUE TITLE
DOB and age field retain error message when data is registered and saved

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2301]
### Bug Description
This happen only on the web, when the age/ DOB field is registered and saved, we get an error message
### Steps to Reproduce
1. Connect to https://uat-sormas.gov.fj/sormas-ui/
2. create a case and latter change the DOB or age

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/84330238-2a7d2280-ab87-11ea-8a99-e6e6efac6854.png)

### System Details
* Device:
* SORMAS version: 1,42,0
* Android version/Browser: brawser

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym

**Comment by MateStrysewskeSym** [comment]
Fixed this also for a lot of other fields.
