### ISSUE TITLE
Report lat and long automatically filled when user create a case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2305]
### Bug Description
The lat and long of a case are filled in with random values when a case is created.
### Steps to Reproduce
1. Log on symeda server and create a case
2. latter check the lat and long  of the case

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/84382206-a2c8ff80-abea-11ea-8eb3-a39c1309b5ff.png)

### System Details
* Device: web
* SORMAS version: 1,42
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda 
These recorded values for lat and long then prevents you from saving the case data

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  This only happen to cases created using: Abia and aba north, Maybe there is a default shape file loaded with wrong lat and long?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou This is not a bug. See #1525.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I got it. But why does it retain a warning message? the red exclamation mark

**Comment by MateStrysewskeSym** [comment]
That's a bug fixed in the latest hotfix.
