### ISSUE TITLE
Rework pseudonymization

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2309]
### Problem Description
PersonFacadeEjb.isPersonInJurisdiction performs three extra queries per person to check whether the user is allowed to see personal details, which is really bad for performance.

### Proposed Change
One possible fix would be to no longer synchronize persons individually, but together with the case, contact or event participant they belong to.

#1158

**Comment by MartinWahnschaffeSymeda** [comment]
Even with PersonFacadeEjb.isPersonInJurisdiction simply returning true now, the whole thing is really slow.
The reason for this is that there is ONE querry for EACH user rights check.

See the log of hibernate querries for one call to persons/all/0 with ~600 persons
[persons_all_pseudo_select_fetch.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4769000/persons_all_pseudo_select_fetch.txt)

As a hotfix we have to take out the whole pseudonymization. Ideally for persons, cases and contacts.

If I do this, it results in the following querries:

[persons_all_select_fetch.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4769014/persons_all_select_fetch.txt)

This is still a lot of stuff - mostly the querries for locations. I have create a separate issue on that #2311

**Comment by leventegal-she** [comment]
Affected by the pseudonimization right now: Case, Contact, Person, Sample, Visit

Options for improving the queries
1. Get a flag that tells for each objects wether it should or should not get pseudonymized in the same query
2. Separate queries: all that should not get pseudonomyzed + all that should get pseudonimyzed
3. Second query to get uuids that should get pseudonymized

Starting point could be the persons get all query
* Measure the improvement with a few 100 items
* Measure the actual pseudonymization(PseudonymizationService) and improve if needed

**Comment by StefanKock** [comment]
Me and Barna are trying two different approaches as proff of concept:
- Barna will try no 1.: boolean flag in JPA-Entity
- I will try no 3.: Get all uuids where the user is allowed to see `@PersonalData`

We agreed to implement it for `Case`/`CaseFacadeEjb`:
- `getIndexList(...)` (many)
- `getByUuids(List<String> uuids)` (many)
- `getCaseDataByUuid(String uuid)` (one)

**Comment by markusmann-vg** [comment]
- [ ] Reactivate pseudonymization and test it
- [ ] Placeholder text: "not accessible due to user right's" // "keine Berechtigung"
