### ISSUE TITLE
Make SORMAS translateable [X+0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#231]
Based on the technical preparations that have been done in the past SORMAS is now ready to be translated. It’s necessary to define a process that allows professional and voluntary translators to help with the internationalization of SORMAS. This likely includes identifying and setting up a ser-vice platform that allows user to do the actual translation and to provide the documentation that explains the process.

- [x] make sure all parts of the mobile and web app are using translatable resources #900
- [x] check whether it's possibe for users to translate the mobile app on their own -> it's not
- [x] prepare the process to hand out translation resources to a translation service -> crowdin
- [x] write a guide on how to do translation and update the system

**Comment by MartinWahnschaffeSymeda** [comment]
See #900

**Comment by MartinWahnschaffeSymeda** [comment]
I have imported a first fileset to POEditor to have a try with it:
https://poeditor.com/projects/view?id=243499

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou @hzi-braunschweig 
Please have a try with the frensh translation of SORMAS on crowdin. The platform looks very promising and they are free of charge for open source projects: https://crwd.in/sormas-open

**Comment by bernardsilenou** [comment]
The colour orde of the  the epi curve bars from below to top should be confirmed, probable, suspected and not yet calssified for all the bars.
