### ISSUE TITLE
Prevent text fields that should only contain numbers from throwing errors in MaxLengthValidator

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2310]
Text fields that only contain numbers (e.g. report coordinates, age, weight, ...) throw an error whenever something is typed in because the MaxLengthValidator that is applied to every TextField can't convert the number value to a String to do its validation.

The current quick fix is that the Validator is removed from all these fields manually. Ideally, this should be an automated process or there should be code that prevents the Validator from running for these fields.

**Comment by StefanKock** [comment]
I just also wrote this change request with more details, see #2370.
Closing this as duplicate.
