### ISSUE TITLE
EventParticipant has no associated Person

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#2320]
### Bug Description
App users of a specific district were unable to synchronize.
I debugged the app and found a `null constraint exception` from sqlite.

It turned out there's a record in `eventparticipant` table that has it's `person_id` set to `null`.
I deleted this record and users were able to synchronize.

Postgres is fine with `person_id` being `null` because the field is set to nullable.
On the other hand, sqlite complains because the field is set to non-nullable. ie `canBeNull = false`.

### Suggestion
In the web app, `person_id` of `eventparticipant` table should be set to non-nullable.

**Comment by MateStrysewskeSym** [comment]
@faatihi Do you have any idea how such a situation could develop? The web UI certainly doesn't allow users to create event participants without persons. Can you please confirm that there is an event participant without a person_id in the web (!) database? The alternative would be that, for some reason, the person wasn't synchronized to the mobile app, but the event participant was.

**Comment by faatihi** [comment]
Yes, there was an event participant without a person_id in the web database.
I have no idea how that happened.

We had the error when the mobile app tried storing the participant in sqlite but participant's person_id was null from postgres.

I think when we configure the person_id to not accept null, this wouldn't happen again.
Or, at least it will throw an error in the web UI when that happens.

**Comment by MateStrysewskeSym** [comment]
@faatihi Alright, thanks! I'll add a backend check to make sure that event participants without a person are rejected.
