### ISSUE TITLE
Case search does not work as expected

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#2329]
### Bug Description
Source case search on contact creation does not work when search field is empty
### Steps to Reproduce
1. Make sure you have at least one case
2. Go to contacts -> create new contact -> choose case
3. Press search case -> results in 0 cases
4. Add space to the search field and press search case -> results in cases being found

### Expected Behavior
Searching with nothing in search field should be the same as searching with ' ' (space)

### System Details
* Device: Browser
* SORMAS version: 1.43.0-SNAPSHOT
* Android version/Browser: Chrome in MacOS

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
