### ISSUE TITLE
Add getQuarantineEndDates method to ExternalVisitResource [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2330]
- [x] Create a method to retrieve a list of ContactQuarantineEndDtos that contain two fields: person UUID and quarantine end date (which is the latest quarantine end date of any contact of this person); does not use a filter for now

**Comment by o-frietsch** [comment]
The integrating developer found some problem or maybe misunderstanding, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/2657 .
