### ISSUE TITLE
Document read-only query hint [1]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2332]
### Problem Description

The query hint `ModelConstants.HINT_HIBERNATE_READ_ONLY` is rarely used, and sometimes pointless.

### Proposed Change
1. Rename constant to `ModelConstants.READ_ONLY` or `ModelConstants.HINT_READ_ONLY` for better readability when using it.
2. Add Javadoc:
```
A query hint to make JPA entities loaded as read-only to avoid caching and dirty checks. Usage:

"List<JpaEntity> resultList = em.createQuery(cq).setHint(ModelConstants.READ_ONLY, true).getResultList();"

Note: This does not have any effect on Multiselect-Queries directly into DTOs.
```
3. Remove usages on non-Entity queries.

### Additional Information
Hibernate documentation: https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html

**Comment by AndyBakcsy-she** [comment]
Verified ticket while looking through the code
