### ISSUE TITLE
Epidemiological data (Event and travel history) of a case cannot be edited.

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2333]
### Bug Description
New data cannot be recorded and old  data already recorded looks bizarre and cannot be edited also.
### Steps to Reproduce
1.Add event and travel history to a case
2. edit the event and travel history of a case with recorded data

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/84805938-4ceac200-b005-11ea-9f13-fb1dfa8ffaca.png)

![image](https://user-images.githubusercontent.com/12996724/84806200-9cc98900-b005-11ea-9652-b9a75c7f32e0.png)

### System Details
* Device: web
* SORMAS version: 1,42,3
* Android version/Browser:

**Comment by StefanKock** [comment]
Fixed in #2317
