### ISSUE TITLE
Documenting a sample from a contact with positive final lab result does not trigger automatic conversion of contact to case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2334]
### Bug Description
Not sure if this is a bug bug or had not been implemented for contacts.
### Steps to Reproduce
1.
2.

### Expected Behavior
-1, If a  final lab result of a sample from a contact is positive, system should ask the user want to create a case and link it as resulting case for this contact.
-2, If user choose yes, then system should provide interface to create a case, convert the contact to a case and transfer all contact attributes like samples, epid data, etc to the case
- 3, 1 and 2 should only be triggered if the disease of the rest result is the same as that of the source case. 
-4, If the disease is different but the final lab result is positive, system should ask if user want to create a new was but do not link it as resulting from the contact. If user chooses, yes, then system should create a new case but create no resulting_case_id on the contact table.
### System Details
* Device:1,42,3
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  relabel if needed pls.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou It's not a bug, but a feature that we haven't yet introduced for contact samples. See #2143.

**Comment by bernardsilenou** [comment]
Danke
