### ISSUE TITLE
[EPIC] Event entity refinement

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2340]
### Feature Description
This feature is in follow up of #2093 and  #2211. A lot of discussions have taken place and the basic idea had fallen back to adapt the basic event object by adding new attributes and methods to it. I have attached images for clarity.
@markusmann-vg we can begin implementation with the information mentioned here.
### Proposed Change
1 Event directory
1,1 Add more filtering options for: Regions, district, status, fromDate,  nonsocial, setting
1,2 In the field ID, description, add option to search events by person first name ad last name. This method will retain the list of  all events that the person is an event participant.

2 Event information, see  eventInformation figure
2,1 add tart and end date
2,2 Add cluster and  screening as categories to status. Rename 'not an event' with 'Discarded Event'
2,3 Add a text field to hold "FIELD EVENT ID" ( this is not event uuid but user specified unique id of the event, similar to epid number for cases). We will latter implement the logic to automatically generate this id, for now we just use a free text.
2,4 Add attribute nosocomial: yes, no, unknown. We do not show this field if status == screening. More validations with type of place will follow in a future issue.
2,5 Add source of information type attribute under source of information: use drop down with categories: Not applicable, media/news, hotline/ person, Mathematical model, Unknown
2,6 add rules  in the ui to display the  respective variable shown in figure (first name, last name, emails, web sites, media name, others+ free text)
2,7 Add "setting" to type of place. 
2,8 Add a new variable called typeOfPlaceDetails with caption "Details". This varaible will hold details of the type of place. For example if type of place == "Means of transport", then display "typeOfPlaceDetails" as drop down with categories plane, train, bus, ship, plane"". You can see attached excel file for categories to use.
2,9 Move region, district and community just above type of place. When a user choose type of place, the field address or landmark show present a drop down of all the addresses in the system based on the region, district, community and type of place variables. Selecting this should automatically fill in the post code, city and area type. Users should also be able to search the address by typing the name in the ''address or landmark' field. If type of place == others or unknown, there shown be no address on the drop down and users should be able to directly type the address ( name, post code, city, etc)

3 Screening information: see screeningInformation image
3,1 This is just a copy of the 'event information' entity defined in 2 with modified form for the ui by replacing events prefixes with screening 
3,2 Add "FIELD SCREENING ID"
3,3 Remove nosocumial
3,4 Remove source of information type and replace source of information with Contact person information
3,5 Keep all methods and attributes as defined in 2,7 - 2,9. Further refinement can be done latter if the need be.

4 Event participant and screening participant: see image eventParticipantScreeningparticipant
4,1 Both Event and screening participants are the  same entities and share the same attributes and methods
4,2 Above or beside involvement description, add the following ids: "FIELD EVENT ID", "FIELD SCREENING ID", event uuid, person uuid, case uuid. If the event participant is not linked to a case, then display ''Create case'. 
4,3 Add sample and  pathogen test
4,3 Add method to convert event participant to case based on lab result. Details can be found in event management description

### Additional Information
Screen shots

![eventInformation](https://user-images.githubusercontent.com/12996724/85594342-230a4e80-b648-11ea-9342-024e2a28520d.png)

###

![screeningInformation](https://user-images.githubusercontent.com/12996724/84942812-b7722f80-b0e3-11ea-8316-c8336acc0cbc.png)
###
![eventParticipantScreeningparticipant](https://user-images.githubusercontent.com/12996724/84942860-cc4ec300-b0e3-11ea-9518-1db7086facf8.png)

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym @markusmann-vg @MartinWahnschaffeSymeda 
Please let us know if more clarification is needed.

5. Methods for event, case and contact management:
5,1 Importation method for event  participants. This also applies to screening participants by default
5,2 Exportation method for event  participants. This also applies to screening participants by default
5,3 For a cluster or event, If type of place details == “home/household” (Household cluster) , then all event participants are defined as contacts to the first case in the event. System should ask if the other household members are also contacts for this new case AND if the follow-up time needs to be extended based on onset of the symptoms of the most recent case in the event. This should happen when an event participant is converted to a case (the second, third, … case if event, but no the first).
5,4 If disease of event  = disease of test result and final lab result  = positive, then trigger method to convert event participant to case and link resulting case to event. If diseases are different, trigger case creation but do not convert event person to case and do not link case as resulting from event.
5,5 If disease of screening  = disease of test result and final lab result  = positive, then trigger method to convert screening participant to case and link resulting case to screening. If diseases are different, trigger case creation but do not convert screening person to case and do not link case as resulting from screening.

5,6 Method to link cases, contacts, to event or screening from the case or contact information by specifying the event uuid of field event id (Häufungsschlüssel).
5,7 Method to convert event/ screening participants to contacts. This is more complex as it will require the user to search search for the source case just as we do when we create contacts from contact directory.
5,8 Search options on event or screening directory using screening or event id, participant name or id
5,9 Have the event and screening IDs shown in the case (and also for contacts) data (Have the cluster ID shown in the epidemiological data of a case (and also for contacts) and also in the small square of the right corner where the name of the case appears)

**Comment by bernardsilenou** [comment]
The attached document contains the categories of type of place

/home/bsi17/Dropbox/sormas_2020/sormasDevelopment/GermanSpecifications/Migration_Epidemiological data_GaPo_20200611_jdo_bsi.xlsx

**Comment by bernardsilenou** [comment]
@markusmann-vg  One point from our meeting today was to add more attributes to collect when  nosocumial == t. We reviewed the list from Gaby and realized that some of the variables are related to those in the above excel table (type of place). We decided to do more refinement and include it in future sprints.

**Comment by bernardsilenou** [comment]
@markusmann-vg  More event management details with mockups is mentioned in issue #2033. 
Currently, when we create cases from contacts or event participants entity, this does not trigger the the duplicate search method. Since Event management is one of the top in this sprint, I suggest we begin with these 2 points:
a. Retrospectively assign cases to events (#2033, point 2)
b. Trigger duplicate case detection method and build the link when creating cases  from events or from contacts
All refinement are in issue #2033, point 1,1 , 2 and 5,1

**Comment by markusmann-vg** [comment]
We splitted the stories for the events refinement:
 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2391
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2392
 
We have to clarify, how a SORMAS user can search for a participant’s name in an event. The event’s list is public, so everyone can see an event, but we guess that the event’s participants list is not public.
Pls. confirm that the participants list is public, so we can add the search for first name and last name.
 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2393
 
Converting an event participant to a case is already possible.
 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2394
 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2395
