### ISSUE TITLE
Event creation from epidemiolocigal data causes error message

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2343]
### Bug Description
Event creation from epi data is not possible and leads to an error message.

![event](https://user-images.githubusercontent.com/63781233/85001391-e58f5800-b153-11ea-80a8-d462b04b76d3.PNG)

### Steps to Reproduce
1. Open a case, go to epi data tab
2. Set 'visited a social event' to 'yes'

### Expected Behavior
Event creation should be possible without error message.

### System Details
* Device: Web
* SORMAS version: 1.42.3

**Comment by MateStrysewskeSym** [comment]
Fixed in #2317
