### ISSUE TITLE
Place of residence input fields in contact person occasionally ignore the number 6

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2344]
### Bug Description
This is probably a hard nut to crack; the bug is hardly reproducible and only occurs once in a while. And it vanishes into thin air. Some of us ran into the phenomenon that the input fields for 'place of residence' case person ignores the number 6. 

### Steps to Reproduce
(how we ran into the bug)
1. Open a contact, navigate to the 'case person' tab
2. Go to place of residence fields
3. Adress or postal code ignore the number 6.

Every other input would work as expected.

### System Details
* Device: Web
* SORMAS version: 1.42.3 and also a previous version (uncertain).
* Browser: Various, definitely with Firefox

**Comment by StefanKock** [comment]
- I cannot reproduce this in Firefox or Chrome.
- I looked into the code of `PersonEditForm` and `LocationEditForm` and cannot find any custom logic (Listeners, Validators) that could produce such a behaviour, it is all plain Vaadin/GWT.

I vote for a broken keyboard. Network latency would usually also not skip characters (and not specific ones).

**Comment by max-hzi** [comment]
> I vote for a broken keyboard

Probably I should have mentioned that the 6 can be entered everywhere else, e. g. in the browser search bar or any website. Plus, this behaviour was observed by at least two users with different computers.
I cannot reproduce it at the moment. As mentioned above, this problem occurs very seldomly.
