### ISSUE TITLE
Remove export rights from Observer roles

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2363]
### Proposed Change
From #2361, its important that observers do not have access to export data on SORMAS  @bernardsilenou

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 What's the exact reasoning behind this? Since they can see data, why shouldn't they be allowed to export it?

**Comment by Iheanacho2027** [comment]
@MateStrysewskeSym with an exported excel file, they can easily share data without authorization

**Comment by bernardsilenou** [comment]
I agree with @Iheanacho2027 , just as the name implies, they should only observe the system. No right to make changes nor export any entry from the system.
