### ISSUE TITLE
Getting Duplicates when performing detail contacts export

### ISSUE THREAD

**Issue by shaneelprakash2910** [hzi-braunschweig/SORMAS-Project#2371]
### Bug Description

When trying to export any data on SORMAS to csv, the row count matches with the number of data in SORMAS but some data are missing while some data have 4, 3 or 2 copies or in other words duplicates.

### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/63214786/85388293-07486f00-b59a-11ea-8e13-033b3bb2ed56.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by StefanKock** [comment]
Please report the SORMAS version you are using.

**Comment by bernardsilenou** [comment]
1,42,3
I tested but did not reproduce this error, all was fine for me. @shaneelprakash2910 please check if you are not making an error

**Comment by shaneelprakash2910** [comment]
Hi Bernard,

How you downloading the data?

If you have time, i can show it over a call.

The problem is sometimes it ok but sometimes its giving duplicates.

And this differs between users as well.

Kind Regards,
SP

**Comment by bernardsilenou** [comment]
Can we have a look at regular meeting time?


________________________________

**Comment by shaneelprakash2910** [comment]
Ok sure.

Tomorrow..

**Comment by MateStrysewskeSym** [comment]
@StefanKock We've already experienced this problem in the past: #1548. I guess the cause could be a similar one this time?

**Comment by StefanKock** [comment]
> Please report the SORMAS version you are using and what export function(s) you are using (click path).

@shaneelprakash2910 please document what export does cause these duplications and if this behaviour is stable reproducable (same uuids) when exported several times.

**Comment by shaneelprakash2910** [comment]
Hi,

Attached are examples of duplicate records we get when we detail download from SORMAS. 

[Duplicates in SORMAS Examples.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4842972/Duplicates.in.SORMAS.Examples.xlsx)

**Comment by MateStrysewskeSym** [comment]
@StefanKock That means it happens in the contact list.

@shaneelprakash2910 Do you also have this problem when exporting cases from the case directory or is it working fine there?

**Comment by StefanKock** [comment]
> 
> 
> > Please report the SORMAS version you are using and what export function(s) you are using (click path).
> 
> @shaneelprakash2910 please document what export does cause these duplications and if this behaviour is stable reproducable (same uuids) when exported several times.

@shaneelprakash2910 I am asking again which export is used: There are three buttons for contact exports (see below) and each of it uses another logic to retrieve the data.
![grafik](https://user-images.githubusercontent.com/24678567/85981792-13db2600-b9e5-11ea-98c7-a850d1985417.png)

**Comment by shaneelprakash2910** [comment]
Cases seems to be fine at the moment.

**Comment by StefanKock** [comment]
Reviewed.
