### ISSUE TITLE
Disable automatic addition of tasks

### ISSUE THREAD

**Issue by adrien605** [hzi-braunschweig/SORMAS-Project#2382]
**Feature Description**

During an import or creation of a contact or a case, tasks are added automatically.

**Problem Description**

We do not have the option to prevent the automatic addition of tasks. During our process it would be easier to manually add spots. Automatic tasks can prevent us from closing cases.

**Proposed Change**

Have the ability to disable automatic addition of tasks

**Possible Alternatives**
/
**Additional Information**
/

**Comment by MateStrysewskeSym** [comment]
@adrien605 You can disable task creation in the database by editing the respective entries in the "featureconfiguration" table. The automatic task creation during case/contact creation can be turned off by disabling "TASK_GENERATION_CASE_SURVEILLANCE" and "TASK_GENERATION_CONTACT_TRACING". Note that this also disables automatic task creation e.g. for daily follow-up tasks.
