### ISSUE TITLE
How do I configure the server-setup.sh to use OpenJDK (https://openjdk.java.net/)?

### ISSUE THREAD

**Issue by Quietghost** [hzi-braunschweig/SORMAS-Project#2390]
We are trying to install the SORMAS Server on SLES 15 VM and we are using the followin java distribution - I installed the JDK:

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (IcedTea 3.15.0) (build 1.8.0_242-b08 suse-3.30.2-x86_64)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

How do I configure "AS_JAVA" in the  server-setup.sh to use this? I always get the following error:

ERROR: No Java JDK found in the path specified in /opt/payara5/glassfish/config/asenv.conf. Please adjust the value of the AS_JAVA entry.

**Comment by MateStrysewskeSym** [comment]
@Quietghost This message usually only occurs if you have multiple Java instances installed on the same machine. The error message should tell you pretty precisely what you need to do though: specify the JDK path in the AS_JAVA variable in the asenv.conf file.

**Comment by Quietghost** [comment]
Thanks for your answer and it seems to work now, although I installed zulu-8 but do I have to specify the path it here already or later in the asenv.conf:

**server-setup.sh**
# The Java JDK for the payara server (note that spaces in the path are not supported by payara at the moment)
#AS_JAVA_NATIVE='C:\zulu-8'
#AS_JAVA_NATIVE='/opt/zuu-8'

or what does this option do? And it means that it auto-detects the installed JDK?

**Comment by MateStrysewskeSym** [comment]
@Quietghost I can't answer that for sure because it's been some time since the server setup script was written and I'm not sure whether I wrote this part. What it should hopefully do is to add the AS_JAVA(_NATIVE) variable to the asenv.conf file; however, I think you would need to remove the "#" in front of the AS_JAVA_NATIVE line in order for this to work.

**Comment by Quietghost** [comment]
@MateStrysewskeSym Thanks for the answer - and explaining how to uncomment a comment ;) ... hmmm if it should add a variable to the asenv.conf file it is not working.

But anyway we got it to work so I will close this issues and thanks again for the fast response.
