### ISSUE TITLE
Add duplicate detection for "converting an event participant to a case" [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2394]
### Situation Description
Currently there is not duplicate detection, when converting an event participant to a case

### Feature Description
When converting an event participant to a case, we will check, if the case already exists. As we already have the duplicate detection, we will reuse the functionality but improve it to directly use the person ID to check for existing cases

**Comment by bernardsilenou** [comment]
Just to remind that the date to use here should be different from the normal duplicate case detection.
The date of report or symptom onset if available of the duplicate case should fall in   d +- 5  days after the date of  the event AND date of report of duplicate case and new case should also be  < d +- 5 days. d = incubation period of disease.

This helps us to validate that the case is as a result of the event exposure else is just  case of the the same person but not linked to the event.

**Comment by markusmann-vg** [comment]
@bernardsilenou Please create a new issue for your last comment. This is a big change and should be treated in another story!

**Comment by ChristopherRiedelSymeda** [comment]
@bernardsilenou Moreover, such a scheme should not be introduced across the board for all diseases, as this is highly dependent on the disease in question.

**Comment by bernardsilenou** [comment]
@markusmann-vg OK
@ChristopherRiedelSymeda I do not quit understand your last point. In my last comment, i used the incubation period d which will take care of variability between diseases.
The point i was making is that i do not think we should implement the default duplicate detection we have when converting an event participant to a case or converting a contact to a case. Remember we not only looking for duplicate cases here, but we are linking the cases as resulting from the event or contact. I think the date of event or date of contact should be considered in addition.
If you do not consider the date of event, you will link a person who was already a case before attending the event as resulting from the event and this will mess up most of the events created in hospitals.

**Comment by ChristopherRiedelSymeda** [comment]
@bernardsilenou You may be right, but the incubation period is of course not the same for all diseases, so we should not generally take 5 days as a standard.
