### ISSUE TITLE
Add samples to Event Participants [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2395]
### Feature Description
Add the functionality of adding samples and pathogen tests to events participants (as we did it for contacts)
+
additionally requirement: 
If there is a positive lab result, the user should automatically be asked wether the event participant should be converted to a case

Edit view for event participants needed 

1st phase WEB only // mobile: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2397

**Comment by BarnaBartha** [comment]
Sample directory

- [ ]  add an associated eventParticipant column to samples
- [ ]  extend sample filter & SampleAssiciationType
- [ ]  extend sample selections & grid based on the new SampleAssociationType
- [ ]  extend sample filters -  disease region district can have the path through eventParticipant

Sample view

- [ ] display information on eventParticipant in the top right (ask Maté what exactly to show)
- [ ] add navigation possibility to the eventParticipant

Sample participant view

- [ ] convert the existing modal form to a view for eventParticipant (e.g. EventParticipantDataView)
- [ ] add samples layout to the EventParticipantDataView
- [ ] add logic for converting eventParticipant to case for positive test result
 
Other tasks

- [ ] extend pathogen test logic and handle notifications when pathogen tests of a sample corresponding to an event participant are changed
- [ ] extend the sormas_schema with the needed changes
- [ ] also adapt the android app db and make sure synchronisation works
- [ ] 
- [ ] extend and add tests to cover all this

**Comment by MateStrysewskeSym** [comment]
@BarnaBartha Looks good!

I think the information displayed about event participants in the sample view should include:
* Event ID
* Event Disease
* Event Date
* Person ID
* First name
* Last name
* Age
* Sex

**Comment by BarnaBartha** [comment]
- [ ]  fix sorting by event participant on sample grid
- [ ]  fix caption for empty samples on event participant info
- [ ]  highlight menu when in event participant details page
- [ ]  missing menu tab for event participant detail
- [ ]  check edit of event participants if it works
