### ISSUE TITLE
Identification and Tracking of multiple infections or reinfections of persons

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2400]
### Situation Description
We should make sure to build a measure to what extend people can get infected more than once. System should monitor and measure the extend of one person to me two cases of different diseases at the same time AND two cases of the same disease at different time.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  I think we may need 2 phase validation process when crating a cases:

1, Duplicate person detection (as we had in the past)
2, Duplicate case detection, conditioned on the person. Here the most important variable will be time, thus we will only count two cases as duplicates if the time interval between the onset of the 2 cases is less than the incubation period of the disease, else reinfection. 
If point 1 is true and disease of point 2 is different, then we have multiple infection.

**Comment by Iheanacho2027** [comment]
This can be done by adding a variable in the Case form asking if the person has tested positive before. I feel the system checking this might make entry slower and also make processes like import complicated

**Comment by bernardsilenou** [comment]
The idea behind this issue is not to ask people if they got infected before but to have that data in the system. This is not limited to reinfection but to also confections and infection of multiple diseases at different times

**Comment by bernardsilenou** [comment]
The current duplicate person detection already handle this, so I think we can close this issue now
