### ISSUE TITLE
Add duplicate person detection to case creation

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#2403]
Currently, duplicate detection in case creation is only based on contacts, not cases. We need to extend the case creation to also check for persons first and for cases afterwards, just like we do it for contacts.

This involves that cases should only be checked for duplicates with exactly the same person.

Also needs to be adjusted for case import.

**Comment by Iheanacho2027** [comment]
I feel this will make sessions like import slower.

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 That's likely true, but it's necessary for the extended event module that's currently in development.

**Comment by MateStrysewskeSym** [comment]
Apparently the case selection is not triggering.

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls note that import has been made very slow with this

**Comment by bernardsilenou** [comment]
@Iheanacho2027 continue with #2539 pls
