### ISSUE TITLE
Implementation of a functionality “merge the duplicates” for contacts (duplication of the functionality available for cases)

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2409]
### Feature Description

**Implementation of a « completeness » column (measure of the level of completeness of the contact sheet) within the “Repertoire des contacts” table and within the list of contacts detected as duplicates.**

**Proposition to add new filters for the following fields :**

- Date of creation of the contact 
- Type of disease
- ID, name, n°EPID, etc…
- Region, department

**implementation of a check box : “display duplicates with different regions”**

**Implementation of the following buttons :**
•	Merge (with a message inviting to confirm the choice) 
•	Choose (with a message invitation to confirm the choice) 
•	Hide 

### Additional Information
Screenshot
![image](https://user-images.githubusercontent.com/65449450/86093374-228e0f80-baaf-11ea-88be-a6ed9ae8f0ec.png)

**Comment by bernardsilenou** [comment]
@carolinverset Concerning the filters you mentioned, we already have them.

**Comment by carolinverset** [comment]
@MateStrysewske @bernardsilenou @benchaabaner
Do you think there is a chance that the pull request for this issue will be merged in version 1.52. It would be really great and would help us a lot in France.

**Comment by MateStrysewske** [comment]
@carolinverset I will have a look at it; whether or not we can integrate it in 1.52 basically depends on the amount of necessary changes to it. We'll try!

**Comment by carolinverset** [comment]
@MateStrysewske 
**VIELEN TAUSEND DANK !**

**Comment by MateStrysewske** [comment]
@carolinverset Unfortunately the pull request wasn't updated again after I sent my change requests earlier today; that means we'll have to delay the feature to the next release.

**Comment by benchaabaner** [comment]
Hi @MateStrysewske, we are currently updating the PR. Most of the changes have been resolved.

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @MateStrysewske 

this issue will no longer be developped by CGI and my team will restart the development from scratch

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
