### ISSUE TITLE
Development of additional repository categories

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2416]
### Situation Description

Repositories’ loading appears crucial to facilitate, standardize and structure data entry by contact tracing teams. 9 repository categories are loaded into SORMAS current version, mainly related to geography and administrative structure of the country (“regions”, “districts”, “community”), hospitals and biology laboratories. 

### Feature Description

Additional repositories development is however required to allow the loading of the prioritized tables or API listed below.

- API “ADRESSES” referencing all known postal addresses in France

- API “SIRENE” referencing companies (included closed businesses), associations and penal institutions registered in the SIRENE database created in 1973. 

- FINESS tables of institutions providing accommodation and care to elderly and dependent persons and institutions providing medical and social care (in French “Etablissements médico-sociaux”).

- Primary and secondary education institutions

**Comment by bernardsilenou** [comment]
@carolinverset I wish to ask how these API will be used in the system? Will they show up when creating a case OR as address of of an event? This issue is very similar to the list of facilities in issue #2340

**Comment by carolinverset** [comment]
@bernardsilenou 
Yes, mainly in the event section. Our users need to complete the community name after selecting the type of place. The entry must be standardized for the statistical studies that will be made. The API query would normalize the names entered and also automatically implement the address, postal code and municipality of the community. We can talk about it at our 4 p.m. meeting. Best regards.

**Comment by bernardsilenou** [comment]
@carolinverset I got it. Issue #2340 will address this point. There will be a drop down variable called "facility type" followed by address for schools, private homes, companies, etc
