### ISSUE TITLE
During case creation, the data for the case being created should also be presented among list of duplicates

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2421]
### Feature Description
The list of duplicate cases are presented to the user without the source case, this males it very difficult to decode especially when you have a many duplicates
### Proposed Change
The top row in the figure should be the data for the case being created so that users can compare with the others. Both on web and mobile app
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/86300345-d81da780-bc02-11ea-8f2d-229b38dfd277.png)

**Comment by bernardsilenou** [comment]
A similar module like in case import will be good:
![image](https://user-images.githubusercontent.com/12996724/86301489-53cd2380-bc06-11ea-857c-d1e6194509b0.png)

**Comment by MateStrysewskeSym** [comment]
Already implemented.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym is this implemented in the mobile app also? I did not find it in 1,43,2

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Not quite sure right now; however, I see an issue on the mobile app in regards to space if we also display the details of the created case. Do you think it's really necessary there? Hopefully whoever enters the case should have its basic details (name, sex, birth date) in mind, right?

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Yea, thats true. I think we go as you say, its better option
