### ISSUE TITLE
Implement user groups to enable task assignment to user groups

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2423]
### Situation Description
Multiple requests for user groups have been forwarded to us so that users can assign a task to a group of users (e. g. a department) vs. to an individual user.

### Feature Description
The admin should be able to create user groups and add users to these groups. This user group assignment should be included in the 'Create new user' window, so new users can be added to a group right away.

In the process of task assignment, the user should be able to assign the task to an existing group.

The user would see his 'Group assignments' in the Task management by clicking on a filter equivalent and right next to 'My tasks': 
![2624645](https://user-images.githubusercontent.com/63781233/86350778-7c373b00-bc63-11ea-84fc-379ae97372cc.PNG)

**Comment by ChristopherRiedelSymeda** [comment]
When preparing the issue, please have #898 in mind!

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske @MartinWahnschaffeSymeda  This need is being requested often. Since @898 in not yet implemented, how do we go about this please?

**Comment by bernardsilenou** [comment]
@Candice-Louw

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't think it makes sense to implement this issue without doing #898 first.

**Comment by MartinWahnschaffeSymeda** [comment]
I think we can handle this independent from #898. UserGroups should be separate from UserRoles. There could be restrictions in terms of which users can join a group or stuff like that, but in general groups should be managed independent from roles.

What we need is a draft that define how user groups are managed and assigned. @HZI?

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda Many thanks for this vital information. We would come up with something by the end of this week.

**Comment by Candice-Louw** [comment]
@bernardsilenou - this has been requested again...

**Comment by bernardsilenou** [comment]
@Candice-Louw  I still do not know the extent that we are in implementing issue #898 and  others.

@MartinWahnschaffe @MateStrysewske  Can we not still implement this ticket without implementing #898 ? 
By creating a group entity  that is a collection of certain users of the same user role and jurisdiction.
Similar to the grouping of event proposed by #4256
    * Through the user management, you can do bulk action to select certain users with the same users role + jurisdiction and create a group.
    * Meta data for user group == group_name+ uuid+ role (adopted from the users in the group)
    * Task assignment or emails send to group == sent to all users in the group
    * If you open the group entity, you can add or delete users
    * A user can belong to > one group
    * Add a user group directory and  display it beside user management : each record = uuid, name, role, number of users in the group
    * add filters for group is, role, etc
    * Clicking on group uuid would open the group and show each user in it

**Comment by Candice-Louw** [comment]
Further information:

A lot of health authorities are currently splitting up the work into very small parts, comparable to an assembly belt. Therefore, they have reorganized the more or less open team structure into groups. Regarding the task management they need an option to assign tasks to the whole group instead of an individual user.
 
Ideally would be an hierarchically task management arrangement that would allow to assign tasks to an overarching group. Each member of this group should be able to select tasks and solve them individually. Subsequently, the solved tasks should be tagged accordingly to avoid duplication of work. Redundancies must be avoided – as soon as a person has opened a task, this should be marked accordingly so that the team does not work on the same task at the same time.

In addition, the team members must be able to track who worked on the task and when, in order to be able to clarify questions.

**Comment by bernardsilenou** [comment]
@Candice-Louw You mentioned some additional vital points on task management. In order not to be overloaded, I think we should create another ticket on documenting task history and keep this one on user group + the current task module.

**Comment by Marko-ilmkreis** [comment]
We would also thumb up for having groups of users. We are using for the purpose to delegate tasks to a group a dummy user. We assign the task to this "user" and the group knows what they have to search for. But thats not very nice and handy.

I would also prefer that a user can belong to more than one group, if possible.

**Comment by kwa20** [comment]
Sorry, I just found this issue after having created https://github.com/hzi-braunschweig/SORMAS-Project/issues/6622 and subsequent issues. @MateStrysewske @MartinWahnschaffe If it's fine with you, could we close this issue in favour of the latest ones?
