### ISSUE TITLE
Add city and post code and Phone Number to freetext filter in case and contact directory [2]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2426]
### Situation Description
Several health departments in Germany require a filter for cities and post codes.

### Feature Description
Add city and post code filter to the case and contact directory. 

Furthermore, we received very positive feedback on the City-column in the detailed contact overview. Is it possible to add this column to the case directory as well?

Edit: Looking at #2385 , maybe the filters should be added after implementation of the address directory, so we could have some sort of drop-down filter. What do you think?

**Comment by markusmann-vg** [comment]
- [ ] Extend freetext search with Postcode and City
- [ ] Description of field (search will be extended)
- [ ] All filters will have a tool tip, describing whats behind

**Comment by markusmann-vg** [comment]
=> +49 (0) 681 - 76568 
after processing the search string:
=> instring? $test = 49068176568 match "6568"

numbers only, then search for phone and zipcodes

**Comment by bernardsilenou** [comment]
> => +49 (0) 681 - 76568 
> after processing the search string:
> => instring? $test = 49068176568 match "6568" 

For a national instance, is it not common to find many people with the same last 4 digit? Is last 6 digits possible after transforming initial string?

> numbers only, then search for phone and zipcodes

**Comment by BarnaBartha** [comment]
@bernardsilenou Yes, will be using the last 6 digits for phone number filter.
