### ISSUE TITLE
Follow the actions of an event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2434]
### Feature Description

Have a functionality for creating a user action for an "event".
It would be interesting to be able to list the different actions carried out by having access to a “follow-up of actions” (the names of screenshot will be change)  tab and by being able to enter these in a simple editor.
Once the event has been entered, when you edit it in the list of events, you should be able to enter, in addition to the tasks, actions around this event.
For this, we could add an "action" object which can, like tasks, be attached to the EVENT context.
By clicking on the "+ New action" button, the user sees a pop-up allowing him to enter an action around the event being edited.

- The entry is attached to the user (who is therefore the author) and includes the fields as described in the model above. The status can take 3 values (completed, in progress, to do) and the priority too (low, normal, high).

- Basic input formatting capabilities must be implemented allowing the user to highlight or format part of the content if necessary (see Figure 2).

- The only context to be implemented at the moment is the "Event" context, but as for tasks, it may be necessary to provide for the extension of this functionality to other contexts.

This tab which lists the actions also allows you to enter a new action. There would be a summary of the number of actions (to do, initiated, completed) in the "event" tab and the detailed description of each action in the "action tracking" tab.
For each action, the following fields appear: Description, status 

### Additional Information
Screenshots

![image](https://user-images.githubusercontent.com/65449450/86483796-16c37700-bd55-11ea-8139-3476d7ac8d1d.png)

![image](https://user-images.githubusercontent.com/65449450/86483816-22af3900-bd55-11ea-9030-a59fdd059422.png)

![image](https://user-images.githubusercontent.com/65449450/86483829-2c38a100-bd55-11ea-9987-c4fc2e91ef5d.png)

**Comment by MateStrysewskeSym** [comment]
@carolinverset What's the substantial difference to a task?

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym This is technically a collection of task (follow up activities) linked to the event. The benefit that i see with this design is that we will be able to have a followup tab with all the activities or tasks linked to the event

**Comment by carolinverset** [comment]
@MateStrysewskeSym @bernardsilenou 
The events are monitored by the investigation teams. Each investigator must plan, undertake and follow several actions around the event by writing down the different stages. In addition, he can also make a url link to a document / attachment he obtained during the investigation
Unlike tasks that are assigned to a particular user, the "event tracking" tab allows a single person to formalize all steps of their investigation of contact tracing
