### ISSUE TITLE
Hide Animal contacts from epidemiological data (cases, contacts) (Germany)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2442]
### Proposed Change
Hide the animal contacts from the epi data tabs as they are irrelevant for Germany. Please also have the epi tab within the contacts in mind (#1838)

### Additional Information
I'd also like to raise attention to #1186.

**Comment by bernardsilenou** [comment]
@max-hzi  I think  #1186 still has some time to be implemented, maybe after September
We do not need to hid only animal contact but format the whole epi data sector with the new information that research is telling us about COVID. Gaby was researching on this, I think we should use her findings and apply it for all the instances of sormas.
I will followup on her.
Can you also ask the users to provide us with the data types that they want to collect, in case they have an idea?

**Comment by max-hzi** [comment]
@bernardsilenou I already have that info from Gaby, now awaiting internal clearance. This will be a different issue. Thank you.

**Comment by bernardsilenou** [comment]
Super, will be waiting to have a look at the findings.
Thanks

**Comment by bernardsilenou** [comment]
@max-hzi  what do you mean by "this will be a different issue". Is it not still about changes to the epid data sector? I am confused pls

**Comment by max-hzi** [comment]
We can hide the animal contacts immediately, the other adjustments are still under refinement and I will open a new issue as soon I receive sufficient info.

**Comment by bernardsilenou** [comment]
ok, I understand now. 
what about programming time? since we do not have the method to easily hide things, this will cause some programming time.
What do you think about pushing the other stuffs and and complete the refinement in the coming week and we do the programming in one step.

**Comment by max-hzi** [comment]
To my understanding the issue concerning animal contacts is not critical and under those circumstances, we should wait and refine all together.

**Comment by kwa20** [comment]
#2676 replaced this issue and was previously implemented. Therefore, I'll close this issue as a dublicate

**Comment by JonasCir** [comment]
@kwa20 It's still open? :D

**Comment by kwa20** [comment]
Sorry I wasn't able to close it with the GitHub mobile app :D. Thank you!
