### ISSUE TITLE
Input fields for case person/ place of residence don't show up (reason unknown)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2444]
### Bug Description
We have a problem in one health department in Germany which I am unable to reproduce.
They have two users with the roles admin, contact supervisor, surveillance supervisor. Both have created an index case, both in their respective region, and one created a case in the same district, the other user in another district.
For both users place of residence (case person) does not show properly, the input fields are missing, but the headings appear.

### System Details
* Device: Web
* SORMAS version: 1.43.2

**Comment by bernardsilenou** [comment]
@max-hzi  admins user role goes well with National user not regional user like supervisors. My suspect is that the user role assignment is the issue. 
@MateStrysewskeSym  Should we no prevent the combination between admins and national users?

**Comment by MateStrysewskeSym** [comment]
@max-hzi I can't reproduce this. I'd need more details and ideally a prepared scenario on the Netzlink demo server that I can use to get to the bottom of the problem.

**Comment by max-hzi** [comment]
I see, so for which additional info could I ask for? As stated, I am also unable to reproduce.

**Comment by MateStrysewskeSym** [comment]
@max-hzi I don't really know - since you're in touch with them, it would be ideal if you could create the same scenario on the demo server together with them because right now, I don't really have an idea how this could happen.

@leventegal-she Could you have a quick look at this issue and see whether you have an idea? Is there anything in the jurisdiction logic that could cause this?

**Comment by max-hzi** [comment]
@MateStrysewskeSym @leventegal-she The problem vanished this morning, no issue with the input fields whatsoever. I suggest we close this issue and keep it in mind, so in case it appears we can reopen. Thank you.
