### ISSUE TITLE
creation of a field relating to the type of risk of an event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2446]
### Situation Description
In a context of an investigation around an event, the investigators classify the event according to the type of risk : cluster, chain of viral transmission, grouping of cases ...

It would be a complementary variable compared to the status of the event which can be: event, not a event, signal.

### Feature Description
Therefore, we propose to create a new variable (drop-down list) to define the type of risk that corresponds to the reported event with the following methods:

### Additional Information
Screenshot 

![image](https://user-images.githubusercontent.com/65449450/86797214-b2175d80-c06f-11ea-845b-28f4bfeaf380.png)

**Comment by bernardsilenou** [comment]
@carolinverset Please can we discuss and refine this further in the meeting tomorrow?
In the current release that will be published tomorrow, a lot of similar attributes have been added to the event entity.  For example the event status is extended to include clusters and screening.

**Comment by bernardsilenou** [comment]
This may not still be important since events now have a "risk level"
