### ISSUE TITLE
Type of Place and District drop down selections under New event creation are buggy on the UI

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2447]
### Bug Description
Drop downs for **Type of Place** and **District** appear at other positions of the page when clicked on them and UI appears bad. User has to scroll the web page to view it correctly.

Note: This happens only when the **Source Type** is selected as Media/News and Hotline/Person as they have additional fields.

### Steps to Reproduce
1. Login to Sormas and Click on events
2. Select Create New Event and Choose screening or Cluster (Might appear on other tabs too)
3. Select the Source Type as Media/News or Hotline/Person
4. Now try selecting the Type of Place and notice where the drop down is shown.
5. Do the same with District selection.

### Expected Behavior
The drop downs must appear at the right place and the web page must not be flickered/moved. 

### Screenshots
![Drop downs_New event](https://user-images.githubusercontent.com/62763628/86800079-f35d3c80-c072-11ea-8994-60de648aebca.PNG)

### System Details
* Device:
* SORMAS version: 1.44.0- snapshot
* Android version/Browser: Chrome

**Comment by raghupola-vg** [comment]
Generic issue on all forms where the forms are larger than the regular screen size. It impacts the UI tests and also it is a bad and annoying user experience for the end user on smaller screens.

**Comment by MateStrysewskeSym** [comment]
@raghupola-vg How bad is this for automatic UI tests? Can you work around it with relative ease? Considering that we'll move to another framework for the UI at some point, I'd like to only tackle this if it's really inevitable.

**Comment by raghupola-vg** [comment]
@MateStrysewskeSym At the moment we have a work around in place and it solves the current purpose. If there are near future plans as described then i wouldn't recommend to invest much time here.

**Comment by AndyBakcsy-she** [comment]
This is also reproducible on SORMAS Version: 1.49.0-SNAPSHOT

**Comment by kwa20** [comment]
Since this is really annoying for users and interferes with their work, we should fix this problem rather sooner than later.

**Comment by DavidBaldsiefen** [comment]
I've identified a potential fix which would also solve this problem when creating contacts and cases (# 3601) (it should work in any form really). However, it is a quite "general" change which might also affect parts of the UI where one does not expect it, so it would need thorough testing.

I will create a Pull Request.

**Comment by kwa20** [comment]
This problem also occurs when processing a lab message through the DEMIS interface.

**Comment by AndyBakcsy-she** [comment]
Ticket seems to be fixed on the latest version of  SORMAS
Version: 1.55.0-SNAPSHOT validated on the local environment
