### ISSUE TITLE
Make calender date field compulsory 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#2452]
### Feature Description
Make date field to use the calendar drop-down compulsory when adding data to sormas

### Problem Description
We notice that when users in the field enter data and that which has to do with date section there type it directly to the box and when you export data out of the platform it comes with a different date format 

### Proposed Change
It will be good to make date to use the calendar drop-down compulsory

**Comment by ChristopherRiedelSymeda** [comment]
@foyiri Wouldn't it be the better option, if there is a problem, to make sure that the date format is the same for all input forms? This would give users the greatest possible flexibility.

**Comment by MateStrysewskeSym** [comment]
I agree with Christopher. We should make sure that date fields only accept correct date formats to prevent malformed data to be entered.

**Comment by foyiri** [comment]
Great so we have to agree on which date format to use even when you are
exporting data because currently it picks it picks the date format of you
keyboard

**Comment by MateStrysewskeSym** [comment]
Follow-up issue: #2455

Both the input format for date fields as well as the date formats in exports should be according to the chosen locale of the user.
