### ISSUE TITLE
Add facility fields to location and refactor occupation facilities for persons [5]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#2456]
### Feature Description

- [x] Add facility fields to location to location forms

- [x] migrate existing occupation facilities 

- [x] remove occupation facility

=> Prerequisite: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2746

**Comment by bernardsilenou** [comment]
@ChristopherRiedelSymeda 
- Are you talking about the occupation facility of a case who  is a health care worker or "relationship to a case" for a contact person?
- Why only fro health care workers? I think will be good to have it for other occupations also like lab staffs, butcher, students/pupil, ...

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou That's exactly what this issue is about

**Comment by bernardsilenou** [comment]
Refinement copied from duplicate issue #2562 

Rename "place of residence" to "address"
Add drop down for type of address: home, place of residence, place of work, other. Other leads to free text field
Add "new entry " using the same logic we have when creating a new social event under epidemiological data tab. There is no limit to number to addresses the can be created
Separate recording of "address or landmark" in to street name, number, apartment number
If type of address == place of work, ask fro company name and profession / function of person in the company

![image](https://user-images.githubusercontent.com/12996724/88903421-f8697200-d253-11ea-8b8b-6c446fac3cbc.png)

**Comment by ChristopherRiedelSymeda** [comment]
This issue will now be implemented independently from #2562.

**Comment by bernardsilenou** [comment]
@ChristopherRiedelSymeda I was thought we have to implement just one of the issues but not both. If we have to implement #2562, then do we still need to implement #2456 ?

**Comment by ChristopherRiedelSymeda** [comment]
This issue is postponed in favor of #2562.

**Comment by markusmann-vg** [comment]
Prerequistite #2718

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
