### ISSUE TITLE
Add date of birth to detailed contact export [0,5]

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2462]
### Situation Description
DoB is missing in the detailed contact export.

### Feature Description
Add DoB column to the detailed contact export sheet, on the left to the age column.

DoB should also become available in the custom export as soon as it is implemented (#1748).

**Comment by markusmann-vg** [comment]
- [ ] Enhance the documentation as well (New added fields should be added to the export)
