### ISSUE TITLE
Add filters to database export

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2463]
### Situation Description
As the number of cases increases in a country, it becomes difficult to export the whole database. In addition, it is not a good practice for users to export cases that have been for more than 3 years at once.
### Feature Description
add filters to database export. We can start with creation date.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The database export is specifically a functionality for admins that we had introduced as a workaround as long as more user-friendly exports were missing. I think that we should actually get rid of this functionality at some point because it exports the data unformatted and not really readable. Do you think it's worth putting much effort into this?

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  the SORMAS-Stats app uses data exported from the front end database export. Since we must not install it on the same server that SROMAS is running, we though this solution may be helpful. The challenge we have now is that for servers like Nigeria, database export takes so long to export and some times it does not work at all.
The app uses almost all the tables we have under database export which are not found in the normal export.
Maybe you may have a better idea how to connect a second application to use the data in the sormas db. 
The basic point is that the app works on the unformulated sormas db and has no user right for now. 

I suggest we keep the database export and add a filter by time and disease only on certain tables like cases, contacts, samples, person.

Can we have a short call on it when you are free please? I think there may be a better solution

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I doubt we can make this a priority right now, so I'd prefer to discuss this when it actually becomes relevant (i.e. when it will make it into the next sprint).

**Comment by bernardsilenou** [comment]
OK, better in September

**Comment by kwa20** [comment]
@bernardsilenou Is this still a relevant issue, especially in regards to Sormas Stats?

**Comment by bernardsilenou** [comment]
This need may come up again, but for now it is not urgent. I would close it.
