### ISSUE TITLE
Replace the categories of  the variable "presentcondition" with their category names in db

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2465]
### Feature Description
The variable "presentcondition" on the person table in  the db have values 0,1,2 rather than their front end categories (alive , death, buried). Ifs difficult to work with the db when categorical variables do not have their real names.
### Proposed Change
Categorical variables should be named as they appear at from end, this prevent miss interpretations and other users do not need to contact the data dictionary all the time they use them.

**Comment by kwa20** [comment]
Closing this issue because the variable now has descriptive db values
