### ISSUE TITLE
Add "Amtseigene ID" (health department specific ID) to cases and contacts

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2467]
### Situation Description
For a federal state in Germany a health department specific ID is urgently needed. 

### Feature Description
Add a health department specific ID field (called "Amtseigene ID" in German) should be added next to the external ID.

For cases, the input field for the new ID should be added in the right side of the externe ID.

### Additional Information
Mockups:

Suggestion, how to arrange in cases:
![amts](https://user-images.githubusercontent.com/63781233/87282919-0cdc0980-c4f5-11ea-8534-c52776d65844.PNG)

Suggestion, how to arrange in contacts:
![amtsk2](https://user-images.githubusercontent.com/63781233/87282862-f930a300-c4f4-11ea-895d-40debd4ac106.png)

**Comment by max-hzi** [comment]
I just talked to Bernard and we decided some critical info should be added for clearance: The new ID (input field) should be understood as **discrict-given ID for the local management,** it's nothing of relevance for other health departments.

**Comment by kwa20** [comment]
Will be done with #5224
