### ISSUE TITLE
App crashing when opening contacts view

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2474]
### Bug Description
-  There are double tabs for Epidemiological data for contacts on web
- Opening contacts on tablet crashes mobile app
-
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:1,44
* Android version/Browser:

**Comment by bernardsilenou** [comment]
This may be due to the fact that event participants are added to the web but not the mobile app

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Have you synchronized the mobile app before opening the contacts view?

**Comment by bernardsilenou** [comment]
Yea i did immediately after upgrade, I test again

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  All tabs sync with server well but contacts crashes app

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Which server did you use to test this?

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou And if you used the symeda demo server, which user did you login as?

**Comment by bernardsilenou** [comment]
HZI_SO, surveillance officer and contact officers roles

**Comment by MateStrysewskeSym** [comment]
Resulting from #1838

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I created a hotfix, but unfortunately it seems like we're having some significant problems with configurations right now. I'll look into it tomorrow. The bug you're describing can be fixed by making a full re-sync (from the settings menu) in the mobile app. I know that this is not ideal in case of low bandwidth; we'll try to find a better solution.

**Comment by bernardsilenou** [comment]
Thanks Maté,
I have no urgent need from the field to upgrade servers using the mobile app now. I think its better we wait and see how it goes.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I have not done a complete re-sync yet. App upgraded to 1,44,2 but I still face the same issue.
Can you have a look at the log on .symeda server from 15:00 to 15:25 today?
I will install a fresh apk on a different tablet and see how it works.
Do you think we can have a solution or complete resync must be done by users?

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Still testing using the same tablet, I could create cases, contacts, epidemiological data to contacts, etc all works fine and sync with db. It is possible to open contact information by going through the case data.  BUT when passing through the contact on the menu bar, the app crashes. The bug now lies in the contact directory of the mobile app

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I did a signed in on another tablet and was requested to upgrade, I did so contact directory in is not accessible. We just need to add a notice to all mobile user to re-sync if they face challenges. Ur the one to close the issue if this is fine by u

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou I think we found a solution. I will create another hotfix today that should finally solve the problem.
