### ISSUE TITLE
Refinement of detailed sample export

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2482]
### Feature Description
In detailed sample export some of the variables are mixed up in one column. For example there is a column on the export table for samples called "Sex of case/contact/event participant person", "Address of case/contact/event participant person". This does not help the user to easily use the table after exporting it.

I suggest we use this logic for all fields that have merged:

add a column called "entity type" that the sample belong to. Categories will be: case, contact, event participant
rename "Sex of case/contact/event participant person" to just sex
split address in to different columns
Fields like case region, contact region will just be one column called "region" the is inherited from the entity type that the sample as associated to.
caseuuid becomes entity uuid and contain uuids for cases, contacts and event participant
This is just a recommendation open for discussion and further refinement will surely be needed.

**Comment by kwa20** [comment]
@bernardsilenou is this issue still relevant? The sex column is now called "personSex" and "sex of case/contact/event participant person" is merely the description

**Comment by bernardsilenou** [comment]
This may not be important since samples have a uuid to allow users to identity their source entities.
