### ISSUE TITLE
Add an indicator on contact followup table to identify the user who registered the visits.

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2483]
### Situation Description
Visits are copied to all contacts that the contact person is associated to. This is fine.

The user doing the visit is not informed that the visit are copied to other contacts. This is a nice to have but not important, the important point missing is the fact that on the visits table, we can not tell who did which visit.

It will be good to have the user who did the visit as a column in the visit table so that the responsible contact officer is not confused when they see a new visit on their tablet.

Or we can add any indicator for the users to know that visits are carried over from one contact to another. Maybe even send a task to inform the SO?

![image](https://user-images.githubusercontent.com/12996724/87409884-e20db600-c5c5-11ea-845a-10a69642f9c7.png)

**Comment by max-hzi** [comment]
What I suggest to the German health departments as a walk-around is to use the visit remarks.

**Comment by bernardsilenou** [comment]
@max-hzi Good idea. I did not get any request from the field about this before creating it, so if the users are fine then no need to implement it now

**Comment by kwa20** [comment]
I'll close this issue in favour of #3621 since the column "visit origin" is referenced there which didn't exist at the time when this issue was written.
