### ISSUE TITLE
Show 'follow-up complete' (Follow-up status) after last follow-up call

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2484]
### Situation Description
For contacts which have undergone successful follow-up and their last day of follow-up lies in the past, the follow-up status remains to show 'under follow-up'. This confuses.

### Feature Description
For contacts which underwent the complete follow-up, the follow-up status should show 'follow-up complete' instead of 'under follow-up'.

**Comment by MateStrysewskeSym** [comment]
@max-hzi This should already be the case. Are you sure that a follow-up visit was created for the last day of expected follow-up? If not, the follow-up period is automatically extended by one day until a new visit has been created.

**Comment by max-hzi** [comment]
Your're right. Will tell the department to double-check if they conducted a call on the last day of FU. Please tag as obsolete. Thanks.
