### ISSUE TITLE
Occasional code on whole screen after log-in (Sormas CH)

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2496]
### Bug Description
After log-in, this screen appears in the Swiss system occasionally ('screenshot' received from swiss collegue, blurred due to sensitive data shown):

![Screenshot Login](https://user-images.githubusercontent.com/63781233/87769091-6312ba80-c81d-11ea-9aac-12674cb4f462.jpg)

### Steps to Reproduce
1. Log in

### System Details
* SORMAS version: 1.43.2

**Comment by MateStrysewskeSym** [comment]
Looks like a ReST call is made instead of the UI being built. This feels like a server configuration issue to me. @HolgerReiseVSys Do you have any idea what could cause this?

**Comment by Candice-Louw** [comment]
This happens due to the 2FA put in place by USP on CH servers, so closing ticket, thank you.
