### ISSUE TITLE
Single page case entry view

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2497]
### Feature Description
As an alternative to #1857, we can have a single page entry view per case where users can enter variables in pages such as (case, case person, Hospitalization, symptoms and epid data), on a single page

**Comment by MateStrysewskeSym** [comment]
@Iheanacho2027 This was at some point part of the system but was taken out per request because it wasn't used at all and wasn't really that user-friendly in the first place.

**Comment by kwa20** [comment]
Since this issue hasn't seen any action is a very long time, I'll close it.
