### ISSUE TITLE
Allow retrospectively link a case to an event and link an event participant to a case on Android app - follow up [3]

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#2505]
Situation Description
Feature Description
Allow retrospectively link a case to an event
When a case is linked to an event, the case will automatically be an event participant as well.
The link between a case and an event will be done on the case view and not in the epidemiological data.

1.) Implement for Android app
Linking a case to an event will follow this process:
Cases => Select a Case => Go to events in the case view => Search for an event => Select an event => SAVE OR
Cases => Select a Case => Go to events in the case view => Search for an event => If you do not find the event => Create the event on the spot with the mandatory event fields (adding more details can be done in the Events area) => SAVE

Remark: The case will also be added as an event participant

2.) Implement on Web app and Android app
link an event participant to a case (from the events view), which already exists and which are the same person
Introduce the logic, that when you want to add an event participant, you can search for persons in the system
add more details to event's participants form to add duplicate detection (sex, date of birth)

out of scope
3.)
add an event participant with the CaseID to an event (from events view)

Possible Alternatives
Additional Information

**Comment by bernardsilenou** [comment]
We should keep in mind to validate and permit the linking only if:
- disease of event == diseases of case
When a case is linked to an event, the case will automatically be an event participant as well **that has been converted to the case**.

**Comment by MateStrysewskeSym** [comment]
Changes to the event user filter:
- [ ] Only synchronize events of the user's region to the mobile app (remove district filter)
- [ ] Synchronize all events associated with cases the user has access to to the mobile app
