### ISSUE TITLE
System does not suggest all available duplicate persons in the db during data import

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2506]
### Feature Descriptio
Attached is a file to import on .symeda server. There are 2 cases in db with names napoleon hill and earl nightingale. For both cases the case persons are different but have the same name. Since the case uuid of the person was not displayed on the person data, i verified this by changing personal attributes in one and it did not update in the other.
During importing this sample data, system suggest only one of the persons as duplicate person. Some times both person are suggested.

### Proposed Change
If multiple persons matches the person similarity check, then all of the similar persons with different person uuid should be suggested as duplicate person to user during case creation.
### Additional Information
One earl nightingale is suggested when there are 2 earls in the db with the same name.
System should suggest all personID that matches the person similarity criteria. 

![image](https://user-images.githubusercontent.com/12996724/87937491-24873500-ca95-11ea-8dea-4d736539d55c.png)

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym  I could not attach the sample csv file here, so i will send by email

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou The reason why only one Earl Nightingale is suggested to you is that the two persons in the database have different birth dates and you've specified a birth date for the imported case. Therefore, the Earl Nightingale with a different birth date is ignored for the duplicate detection.

**Comment by bernardsilenou** [comment]
Aaakwanifeh!
Thanks bro, that was the cause. The bypassing of checking duplicate case when persons matches was the main issue as you earlier mentioned.
