### ISSUE TITLE
Date filters reset after navigating between directory and contact information

### ISSUE THREAD

**Issue by max-hzi** [hzi-braunschweig/SORMAS-Project#2513]
### Bug Description
The date filters reset in some instances when opening a contact and then going back to the directory. This problem is hardly reproducable and I did not experince it myself.

### Steps to Reproduce
1. Open contact directory
2. Go to follow-up visits
3. Filter by date 'new contacts from...' '...to'
4. Open existing contact
5. Navigate back to directory
6. (See that date filters are reset by the system)

### Expected Behavior
Date filters should not reset automatically.

### System Details
* SORMAS version: 1.44.3
*Browser: Firefox, regardless of browser privacy mode

### Additional Info
Apparently this problem affects all the other date filters, too. I will try to option more info.

**Comment by bernardsilenou** [comment]
Duplicate of #3029
