### ISSUE TITLE
Display specified form fields in the campaign data list

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2515]

**Comment by MateStrysewskeSym** [comment]
Added list element definitions to campaign form meta that are then displayed as columns in the grid.

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove customColumns in CampaignDataGrid
- [ ] Move code in formMetaChangedCallback to separate method
- [ ] Remove campaignFormListElements column and instead put the information which elements should be displayed in the grid by adding a new property "important" that can be set to true
