### ISSUE TITLE
Campaign diagram visualization [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2526]
### Situation Description

For campaigns data is collected in forms with custom fields. The data collected needs to be visualized in a diagram on the dashboard.

Mockups and information on example indicators that need to be visualized can be found in #2004.

The campaign diagram definition already exists in the backend. See #2525

#### Dashboard preparation

- [x] Hide the surveillance and contacts dashboard views when the corresponding module is not activated
- [x] Add a "Campaigns" view to the dashboard (similar to surveillance and contacts), to be shown when the module is active
- [x] Add a campaign selection drop down to the dashboard as in the mockup: https://app.moqups.com/3NUENEwuOE/view/page/ada0707cf
- [x] Add area, region, district drop downs to the dashboard that will be used as data filters. Region is only shown when area is selected, etc.

#### Diagram in dashboard

- [x] Display one diagram for each diagram definition that exists in the backend (later this will be replaced by a definition of which diagrams should be shown for a certain campaign. For now only column charts are needed. Use the highcharts component used for the other diagrams in the dashboard.
- [x] Each series element will result in a query. The source is the CampaignFormData table. 
- [x] The result is grouped by the jurisdiction below the one that currently filters the data (e.g. area when no filter is active, or region when filtered by area). This is used for the x-axis
- [ ] The result is filtered by time and jurisdiction.

**Comment by MateStrysewskeSym** [comment]
This issue shouldn't be picked up before we've clarified the JSON definition for the database.

**Comment by MartinWahnschaffeSymeda** [comment]
Further todos:

- [x] change database type of CampaignDataForm data to json to make it queryable
- [x] change hibernate-types json mapping type to JsonBinary
- [ ] ignore "old" auditing for json data
- [ ] disable hypersistence banner
- [ ] disable campaign data unit tests related to json (due to problems with h2)

Example INSERT statement:

```
INSERT INTO campaigndiagramdefinition(id, uuid, changedate, creationdate, diagramid, diagramtype)
	VALUES (nextval('entity_seq'), overlay(overlay(overlay(
		substring(upper(REPLACE(CAST(CAST(md5(CAST(random() AS text) || CAST(clock_timestamp() AS text)) AS uuid) AS text), '-', '')), 0, 30) 
		placing '-' from 7) placing '-' from 14) placing '-' from 21), now(), now(), 'vaccinationMonitoring', 'COLUMN');
```

Example diagram definition (can be used with data form definition from wiki https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Campaign-Form-Definition#examples

```
[{"fieldId":"childrenLivingInHouses","formId": "vaccinationMonitoring"},
{"fieldId":"missedChildren","formId":"vaccinationMonitoring"}]
```

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha I had a problem trying to change data in a campaign data form - they were not saved. Turns out the problem was the implementation of equals/hashCode in CampaignFormDataEntry. I have removed that part and now it works.
I'm note sure why it was needed, so if you run into problems related to this, you now where it's coming from.
