### ISSUE TITLE
Campaign dashboard definition [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2527]
### Situation Description

For campaigns a dashboard is needed to visualize the entered data. The visualization of a single diagram is done in #2526.

Now a definition of how the dashboard should look like is needed. Mockups:
https://app.moqups.com/3NUENEwuOE/view/page/ada0707cf
https://app.moqups.com/3NUENEwuOE/view/page/aab33f609

#### Backend

- [x] Create a CampaignDashboardElement class with the following fields: 
  * diagram (as defined in #2525)
  * tabId: An id/name of a tab. All elements with the same tabId would be shown on the same tab within the dashboard. For now not translated
  * order: A number that is used to order the elements within the tab
  * width in % of dashboard width -> sum of over 100% would move the chart into the next line
  * height in % of screen height -> sum of over 100% would add scroll bars
- [x] Add a dashboardElements field to the Campaign entity. Should be a JSON field in the database
- [x] Create Services, Facades, DTOs that allow to access this definition.

#### Dashboard

- [x] Load the dashboard elements list and add the needed diagrams to the dashboard
- [x] Implement tabs for the dashboard.
- [x] Pre-select the last campaign that has already been started (e.g. when today is the 09.09, select the campaign that started 01.08, not the one that will start 01.10).

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha I have added one todo: Pre-select the last campaign that has already been started (e.g. when today is the 09.09, select the campaign that started 01.08, not the one that will start 01.10).

**Comment by BarnaBartha** [comment]
- [ ] add / remove css grid styles dynamically
- [ ] hide tab switcher when only one tab

**Comment by BarnaBartha** [comment]
- [ ] fix height and width issues for all scenarios within the dashboard

**Comment by MartinWahnschaffeSymeda** [comment]
Note: Make sure that the dashboard works fine on a 1280×720px screen (14" display).

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Dynamically resize charts, when screen size changes
- [ ] Make sure charts take the exact height defined (e.g. 90%)
- [ ] Reduce header font size to better fit on small screens

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha Please have a look/review at/of my last commit: https://github.com/hzi-braunschweig/SORMAS-Project/commit/3d373f1b204b4e91a156db21af2bf459a1425e36
