### ISSUE TITLE
Add a percentage visualization to campaign diagrams [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2528]
### Situation Description

Based on #2525 and #2526 the system is able to visualize campaign data in absolute numbers on the campaigns dashboard.

Users need to be able to also display these numbers as relative/percentage values.

https://app.moqups.com/3NUENEwuOE/view/page/ada0707cf

### Feature Description

- [x] add a "total" column to the CampaignDiagramDefinition entity that contains a list of CampaignDiagramSeries. The total is calculated by summarizing those series. When the series has only a formId, count the number of forms
  Example A:
```
[{
	"formId": "teamMonitoringFrom",
}]
```

  Example B:
```
[{
	"fieldId": "numberOfResidentChildren",
	"formId": "h2hCompilationForm",
}, {
	"fieldId": "numberOfNomadChildrenVaccinated",
	"formId": "h2hCompilationForm",
}]
```
- [x] Display percentage in diagram. Add a backend method that calculates the total values grouped by the chosen jurisdiction
- [x] Add an option to the diagram options to switch between total and percentage (see mockup)

**Comment by MateStrysewske** [comment]
- [ ] When "total" is defined, show percentage values, otherwise show total values (don't provide an option to switch for now)

**Comment by MartinWahnschaffeSymeda** [comment]
For the switch we can either use the highcharts menu like this: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/menuitemdefinitions/

Or we can try to add another element that floats above the chart, e.g. on the top-left. Since we may also have to switch to another visualization type (e.g. horizontal vs. vertical bars), the menu is probably the better war.

**Comment by MateStrysewske** [comment]
- [ ] Use parameters for formIds and fieldIds to avoid SQL injection
- [ ] Example B needs to be implemented, i.e. multiple reference values that are summed up

**Comment by MateStrysewske** [comment]
- [ ] Diagram definition should allow setting total values/percentage as default

**Comment by AndyBakcsy-she** [comment]
Moving the issue to the Done lane as this can't yet be verified using the UI as it is only a DB modification
