### ISSUE TITLE
Add more information to the import templates [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2537]
### Situation Description

Currently data can be imported into the system using CSV files (e.g. cases, contacts, facilities). The system provides a template for each import that is filled with data by the user doing the import. For some fields this is currently difficult, because user's aren't sure what format has to be used for the data (e.g. date format) - see #2131.

### Feature Description

We need to add more information to the import templates to simplify the process for users, e.g. to make sure they don't always have to look into the data dictionary.

- [x] Allow comment lines in import files. Suggestion is to use "##" (without the quotation marks) as a prefix in the line. These lines should be ignored when importing.
- [x] Add a comment line to the import templates that contains the captions of the import fields in the server language. Ideally this should be implemented  in a generic way to have it for all existing imports: cases, contacts, facilities, etc.
- [x] Add a comment line to the import template that defines the data format for each column/field.
  - Date: "Date: DD/MM/YYYY"
  - String: "Text"
  - Enum: "YES, NO, UNKNOWN" // yes, for some enums, this will have a lot of values
  - Region/District/...: "Name of .."
  - Number: "Number"
- [x] For disease make sure to limit the enum values to the applicable ones (e.g. that support case based data entry)

### Additional Information

Will simplify #1999

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda Thanks fro putting all these issues in an organised format. I think we need to work on this as soon as we can. New users are facing a lot of challenge.
