### ISSUE TITLE
About page >"What's new?" link to GitHub releases broken/incorrect

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2538]
### Bug Description
URL to GitHub release details page is broken/incorrect | About > “What’s New?” > [404 Page not found error](https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/releases%2Fversion-1.44.0)

### Steps to Reproduce
1. Main menu > About (/sormas-ui/#!about)
2.  "What's new?" (/sormas-ui/#!about)
3. 404 Page not found error (https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/releases%2Fversion-1.44.0)

### Current Link Formats (not working)
V1.44.0: https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/releases%2Fversion-1.44.0
V1.43.0: https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/releases%2Fversion-1.43.0
...

### Expected Link Formats
V1.44.0: https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/v1.44.0
V1.43.0: https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/v1.43.0
…

### Screenshots
<img width="972" alt="20200724_ALL_GitHubReleasePageErrorURL" src="https://user-images.githubusercontent.com/65529128/88383683-43463e00-cdab-11ea-896c-bbe29429ebf9.png">

### System Details
* SORMAS version: 1.44.3
* Browser: ALL

**Comment by bernardsilenou** [comment]
@Candice-Louw  it works perfect for me.

**Comment by StefanKock** [comment]
Background: The tagging pattern changed in September 2019 with 1.27.0 without keeping this feature in mind,
