### ISSUE TITLE
Extremely long importation time for cases and contacts 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2539]
### Bug Description
- Users reported that the import module is now very slow. In 30 min, they are able to import only 230 contacts. Report from the field:
We have 3 environments, installed in Docker mode:
- a TRAINING environment in which there are around 2000 cases
- a RECIPE / QUALIFICATION environment: the database is a copy of the PRODUCTION database
- a PRODUCTION environment in which there are approximately 45,000 cases and 85,000 contacts.
There are around 750 users declared active on the PRODDUCTION environment.
NameSimilarityThreshold parameter is set to 0.9, thus very few duplicates are identified.
 
The response times for importing into the PROD environment have always been quite long, but at the moment it has become very long. 
 
We tested the import in the TRAINING environment: it is very fast. In the RECIPE environment, it is a little slower but still better than in the PRODUCTION environment.
### Steps to Reproduce
1.Generate random cases (100000) and contacts (200000) on server
2. Export 500 cases and prepare an import template, delete 450 of the 500 cases exported from the. Thus we are left with 50 duplicates
3. Reinstall these 450 cases and measure time it takes, look at logs, RAM performance, etc

### Expected Behavior
-System should be able to import abut 1000 cases in 15 min if there are no duplicates.
### Screenshots

Memory info during importation via htop.

![image](https://user-images.githubusercontent.com/12996724/88380934-bd73c400-cda5-11ea-8d41-72ec93185a46.png)

### System Details
* Device: web
* SORMAS version: 1,44,3
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym Hoow can we do a  simulation to diagnose the time it takes to import cases. Can I use .Symeda server for this?

**Comment by MateStrysewskeSym** [comment]
This is probably associated with the way we're checking for duplicates. We moved this out of the database because H2 doesn't have a similarity detection functionality and thus we couldn't test the code, but that doesn't matter if the function is not really usable otherwise.

We likely have to re-enable duplicate detection in the database and see how much of an effect this will have.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I think so also, I just had a meeting with the French team and went through the import processes.
It takes long, approximately 30 seconds for some cases with no DOB. An additional test also shows that during the import process, the server is not overloaded, this matches the fact that the delay is not related to the db but the code. Hope we improve it in this release.

**Comment by bernardsilenou** [comment]
@markusmann-vg @leventegal-she 
- Have we done any test after the improvement? If not, can we do it on the test server before the release?
-the testing will only make sense with many cases and contacts in the system,  with duplicates. Suggestion:
1.Generate random cases (500000) and contacts (500000) on server
2. Export 500 cases and prepare an import template, delete 400 of the 500 cases exported from the server. Thus we are left with 100 duplicates in the import template.
3. Re-import the 400 cases and measure time it takes

- Please let me know if i can do such a testing and on wish server?
- If the improvement does not significantly reduce the time, then we may consider dropping the whole duplicate person detection method in the 1,47.

**Comment by StefanKock** [comment]
@leventegal-she measured about half time per case to import with the changes made (on his machine 2s to 1s per case).

**Comment by StefanKock** [comment]
I talked with @MateStrysewskeSym about switching off duplicate person detection but this is not possible because this is a prerequsit part of the duplicate case detection. But the improvements already made should help to reduce the time spent per case (hopefully enough).

**Comment by StefanKock** [comment]
Missing part still now is performance improvement for contact import. I think this should be split into a new ticket when we see how case import performs after this ticket is released.

**Comment by leventegal-she** [comment]
Also the database can be a bottleneck, the CPU usage of the DB on my macbook is getting higher and higher during a longer import with few hundred of cases
