### ISSUE TITLE
Developer tab is missing on docker versions

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2541]
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/88400118-23714300-cdc8-11ea-8bda-d217b7bb4834.png)

**Comment by bernardsilenou** [comment]
@fhauptmann Any idea why it is missing.  I wanted to test the performance of the import module on .muster and did not find this feature to generate huge data.

**Comment by JonasCir** [comment]
@bernardsilenou 
You can enable the DEVMODE by setting the corresponding variable in [.env](https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/.env#L42) before starting the docker-compose.
