### ISSUE TITLE
Add "Apply" button to filters on dashboards and directories [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2542]
### Feature Description
On the contact dashboard for example, when you choose a disease, the system begins filtering immediately. This forced the user to wait for each step and it can really be long on systems with hundreds of thousand of cases.
### Proposed Change
- Add a global activation button to trigger filters supplied by the user.
- Also trigger filter when user click the enter key on keyboard
- Do not trigger filter when user supply an option to a cell alone, they must click the global  filter icon or enter key.
### Possible Alternatives
- 

### Support or Review
@leventegal-she

**Comment by bernardsilenou** [comment]
Comment from issue #2566 
With the "Apply filter" button, the system would allow users to comfortably type and select their options in filters, before bringing out results. The results of selection will be displayed after the user types or selects, then click on the "Apply filter" button. The "Apply filter" button should be besides "Reset filter" button. This would solve #2225

**Comment by bernardsilenou** [comment]
This solution will also solve issue #2225

**Comment by markusmann-vg** [comment]
@bernardsilenou 
Which directories are you referring to?

**Comment by bernardsilenou** [comment]
@markusmann-vg Thanks for that. I agree with you.
dashboards : case and contact
case directory
contact directory
event directory
samples directory
