### ISSUE TITLE
Selection widget is displayed Empty for New form selection - Afghanistan Campaign

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2547]
### Bug Description
New Form for Campaign data is shown as empty selection and the window has the header as null.

### Steps to Reproduce
1. Login to https://test-afghanistan.sormas.netzlink.com/ as national user or any other user.
2. Select Campaigns and click on Campaign data
3. To the top right, New form option is displayed. Click on it and see if the options are displayed with content.
4. click on the empty selection and see the header of the pop up window.

### Expected Behavior
The option displayed under new form should no show empty field and the pop-up window header should have a proper name without displaying null

### Screenshots
![Afghanistan campaign form](https://user-images.githubusercontent.com/62763628/88533546-c0b9ba80-d006-11ea-8509-91e0a845a2b0.PNG)
![campiagn form header](https://user-images.githubusercontent.com/62763628/88533548-c1525100-d006-11ea-963f-786eae603634.PNG)

### System Details
* Device:
* SORMAS version: 1.45.0
* Android version/Browser:

**Comment by MateStrysewskeSym** [comment]
The reason is very likely that the form in question does not have an ID or, if the newest version has been deployed, name. This will not be an issue once there's a UI for creating forms because these fields will be mandatory.
