### ISSUE TITLE
Creation of a window with information on the entry rules to be observed in terms of GDPR

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2550]
### Feature Description

**- Creation of a window appearing after the user has logged in with information on the entry rules to be observed in terms of GDPR**

Window characteristics:

> a) Launch of the window each time SORMAS is opened
> b) Close the window by clicking on an ok button
> c) No electronic signature by the user: simple information window

Window content 

“In accordance with the principle of data minimization imposed by the GDPR, you must ensure that you enter here only objective data absolutely necessary for the processing of the file. In particular, you must not enter genetic or biometric data, philosophical, political, religious, trade union opinions, sexual life or orientation, racial or ethnic origin, offenses, convictions, security measures, criminal record ... or any other data that does not would not be related to the health survey”

**- More succinct GDPR reminder when entering information in the comments fields**

The user gets a reminder of the entry rules when the cursor is placed on a comment field. A pop up is then displayed with the following text: "Reminder: All comments entered must comply with GDPR rules as described during connection."

All of the fields concerned are listed below:

![image](https://user-images.githubusercontent.com/65449450/88538065-febadc80-d00e-11ea-98b0-3c6ac47b24cc.png)

**Comment by carolinverset** [comment]
For monitoring : @benchaabaner @Emond-Fuseau @OlivierLeuci

**Comment by MateStrysewskeSym** [comment]
@carolinverset Would it really be necessary to display this popup every time the user logs in? I could imagine that to be pretty annoying. I'm also not sure about the popup when hovering over comment fields, mainly because it would interfere with field descriptions that are also displayed on hover.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym in our last sprnt with the French team, your exact worry was raised and we could not find a solution to it. I also think it will really be annoying to remind users all the time they login to the system.
- One suggestion was to show it after every n times the user logged in
- After the first login and later when user changed passwords. But with the keycloack issue, this may not be a good idea.
-Maybe someone can suggest a better solution?

**Comment by bernardsilenou** [comment]
@ChristopherRiedelSymeda This is a good one.  @MateStrysewskeSym is this solution OK with you? if yes then we can confirm commencement of implementation tomorrow by French team during the sprint.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou Sounds good to me.

**Comment by benchaabaner** [comment]
Having a checkbox could be a good idea ! 
So how about : 

1. showing a popup after login. This popup will contain a checkbox which says "I have read the information, the window should not be shown again" with an OK button 

- If the box is checked, then the popup will not appear again to the user ( an attribute set to false linked to the user ? ) 

- If the text within the popup changes, then we will show the popup again to all users ( is this something that can be automated ? or we will have to do it manually by setting all the users attribute to true again ? ) 

2. The popup when hovering over comment fields :  I understand that you already have descriptions that are shown so can we add just below this description a small sentence that will remind the user of the GDPR terms ? 
And can this sentence be set up to appear only to France's users ?

**Comment by bernardsilenou** [comment]
@benchaabaner This feature will appear for everyone. However, we can play with the translations to make sure they are not the same for each country

**Comment by bernardsilenou** [comment]
this is a  what happens when i login to my crowdine account after being away for about a month.
![image](https://user-images.githubusercontent.com/12996724/88924593-c7009e80-d273-11ea-9875-c90029dbffee.png)

**Comment by benchaabaner** [comment]
@bernardsilenou @MateStrysewskeSym @carolinverset 
we have developed the first part of this feature :

1. showing a popup after login. This popup will contain a checkbox which says "I have read the information, the window should not be shown again" with an OK button
If the box is checked, then the popup will not appear again to the user.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/68555878/91545434-53f55100-e921-11ea-9968-98fa57b0a983.png)

2. we still need validation on the second part of the feature : can we add our GDPR message below the fields descriptions ?

**Comment by bernardsilenou** [comment]
@benchaabaner This is good job, thanks
Please can you make a mockup where you want to add the text for the second part? I cant picture what you mean.

**Comment by bernardsilenou** [comment]
@MateStrysewske We discussed the option to add the RGDP message to the comment field. For users who do not need to have this message, we will manage with translations hopefully.
Hope this is fine by you?
Of other users complain after the implementation, then we can take it out or add it as a configuration
Thanks

**Comment by benchaabaner** [comment]
@MateStrysewske @carolinverset @bernardsilenou 

We have validated the second part of this feature : add the RGDP message to the comment field description.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
