### ISSUE TITLE
Create default campaign indicator definitions

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#2553]
### Feature Description

Provide the JSON definitions for the following indicators:

Indicator category | # | Specific indicator | Data Source | Calculation | Admin level | Dashboard Design | Comment
-- | -- | -- | -- | -- | -- | -- | --
-- | 1(put on hold for the dashboard | Percentage of teams monitored as per micoplan | ICM Team monitoring Checklist | Team as per microplan (Y)/# teams monitored(Y+N)*100 | Cluster | Columnx axis:Org unity axis: Percentage | Data entry for each team at the cluster level
Missed Children | 2 | Missed children: numbers/Percentages and reasons for missed (absent, refusal, NSS, ignored by team, team didn't come) | Admin Data Days 1-3 AND From ICM HH Monitoring Checklist | # of each reason/total # of children checked*100 | Cluster | Stacked bar (Count)y:# of missed children ( Reasons)x: Org unit | Toggle between Percentage and count
-- | 3 | Proportion Missed children found by monitor and not recorded by teams | ICM HH Monitoring Checklist | # missed children found by monitor and not recorded by teams/Total # of Missed children found by monitor*100 | Cluster | ColumnY Axis: Percentage of missed children foundX Axis: Org unit | 
-- | 4 | Proportion of Missed children recovered during and after campaign and remaining missed (by reason missed) | HH tally sheet; Days 1-3 and day 5 | misseed children recovered days 1-3, recovered day 5, remaining missed)/ target pop | Cluster | Stacked barx: org unity: Percentage 100 ( Vacc day 1-3, Recovered day 1-3, recovered day 5,Remaining missed) | by reason will demonstrate which reason for missed children is hardest to recover
-- | 5 | Percentage HH not revisited by team | ICM revisit | # of HH not revisited(N)/ HH not revisited (Y+N) | Cluster | Columnx: org unitY: Percentage |  
-- | 6 | Missed and poorly covered areas (for immediate action during campaign) | ICM HH Monitoring Checklist | (# HH missed in a monitored area/7 HH)/number of areas monitored (# children missed in a monitored area/ 7 HHs)/number of areas monitored | Cluster | Side by Side Columnx axis: org unity axis: Percentage missed area and Percentage poorly covered | Possibility of using short code or USSD to collect data?
-- | 7 | Percentage of teams visited by supervisor | ICM Team Monitoring Checklist | # of team visited by supervisor/total # of teams checked | Cluster | Columnx: org unitY: Percentage |  
Finance | 8 | Percentage of vaccinators not paid during past campaign | To be added to team monitoring form | # of vaccinators not paid (Y)/# of vaccinator not paid (Y+N) | Cluster | Columnx: org unitY: Percentage |  
-- | 9 | Number of campaigns with no payment | To be added to team monitoring form | Count of campaigns with no payment | Cluster | stacked barX: org unity: Percentage |  
--  | 10 | Chronic refusals (add indicator for tracking chronic refusals) | ICN Data |   |   |   |  
-- | 11 | Remote monitoring results on missed children |   |   |   |   |  

10. and 11 are not final

### Mockups
https://app.moqups.com/3NUENEwuOE/view/page/ada0707cf
https://app.moqups.com/3NUENEwuOE/view/page/aab33f609

Source of the diagrams provided by Ben:
[Intracampaign_Indicators_26May2020_BN.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/4730703/Intracampaign_Indicators_26May2020_BN.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba I was going through the indicators to see how they would be implemented based on the dashboard concept and ran into a few problems that we need to discuss:

1. Indicator 1 "Percentage of teams as per micoplan" uses "Team as per microplan (Y)". The Team Monitoring Form I have seen does not contain this question and I wasn't able to find one that has it in the google docs folder. Can you point me to the correct form?
2. Indicator 4 uses the "target pop" as reference value. How would this be calculated? I guess by adding the values of "Number of children 0-5 years resident in the houses" and "Number of nomad children 0-5 yrs vaccinated"? (see https://app.moqups.com/3NUENEwuOE/view/page/aff46b0e2) This would probably not be 100% accurate...

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda Indicator 1: Put on hold for now. We will get back to you. 

@MartinWahnschaffeSymeda Indicator 4: How is the target population calculated for Afghanistan- Not census data, SIA data is bigger. Talk to Hassan. NID target has not changed for years.
