### ISSUE TITLE
Performance is degraded and Request timeout appears when multiple cases are pushed to Sormas

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2554]
### Bug Description
When the application has more than 2000 cases, the time taken is more than 60 seconds and request time out occurs while pushing additional cases.

### Steps to Reproduce
1. 
2.

### Screenshots
For high number of cases:
starting cases
found 5405 rows
Time: 62.353
loading sample data ...
found 5405 rows
------------
generated 1 cases
pushing data 1...
status push: 200(OK)
found 5406 rows
Time: 49.422
cases finished

for less cases:
![de Test stage](https://user-images.githubusercontent.com/62763628/88567761-35f1b380-d038-11ea-9bd5-3db4c7ccc418.PNG)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@raghupola-vg  Thanks for this detailed diagnostics. Very similar to issue #2539

**Comment by Jan-Boehme** [comment]
@bernardsilenou @raghupola-vg 
The associated issue #2539 has been resolved.
Is the problem still occuring or can this one be closed as well?
