### ISSUE TITLE
Add filter for "follow up status"  of cases to case directory [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2561]
### Situation Description
Users wish to be able to distinguish contact and cases that are still "active" (Under followup) and "inactive" (followup completed) in order to measure work load. Similar to the filter for followup status for contacts, we need to add a similar one for cases. This will be done after merging the follow up module for cases to main branch.
### Additional Information
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/06

**Comment by bernardsilenou** [comment]
This will be implemented only after merging 
https://github.com/hzi-braunschweig/SORMAS-Project/pull/2488

**Comment by ChristopherRiedel** [comment]
Feature is already there.
