### ISSUE TITLE
Person address refinement - Phase1 [5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2562]
### Feature Description
- In the current system, we have 2 address: one for the entity (event, case) and another for the "place of residence" of the associated person. There is the need to record multiple addresses of a person entity. therse addressed will be classifeid in to categories like place of work, residence, home, other. Fir each of these types, a slightly different from will be used since attributes may differ, eg  for work place, company name is needed but not for home.
### Proposed Change
Using the person entity:

![image](https://user-images.githubusercontent.com/12996724/88669911-c38add00-d0e4-11ea-8c78-c547be71cb26.png)

1. Rename "place of residence" to "address"
2. Add drop down for type of address: home, place of residence, place of work, other. Other leads to free text field
3. Add "new entry " using the same logic we have when creating a new social event under epidemiological data tab. There is no limit to number to addresses the can be created
4. Separate recording of "address or landmark" in to street name, number, apartment number
5. If type of address == place of work, ask fro company name and profession / function of person in the company

**Comment by bernardsilenou** [comment]
ref: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/9

**Comment by ChristopherRiedelSymeda** [comment]
@bernardsilenou isn't this somehow the same topic as in #2456 ? We should definitly not do both.

**Comment by bernardsilenou** [comment]
@ChristopherRiedelSymeda It is the same thing, I now see.
The only difference here is the design, we will not validate the facility based on occupations but as an address to the person entity.

**Comment by ChristopherRiedelSymeda** [comment]
This issue will now be implemented independently from #2562.

**Comment by ChristopherRiedelSymeda** [comment]
Tasks:
- [ ] Divide address field into 3 fields (street, house number and additional information)
- [ ] Migrate data from address field to street field
- [ ] Replace old address fields with list as for the previous hospitalizations in hospitalization
- [ ] Create new Enum PersonAddressType
- [ ] Add PersonAddressType to Location entity
- [ ] Make PersonAddressType selectable when creating a new address and display it in the list
- [ ] Addresses mus be deletable

**Comment by ChristopherRiedelSymeda** [comment]
PersonAddressType:
Home
Place of residence (Swiss only)
place of exposure (Swiss only)
place of work
event location (Swiss only)
other address
