### ISSUE TITLE
Making disease incubation period configurable based on server instance

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2563]
### Feature Description
The current follow up period (14 for COVID-19  and 21 fro Lassa) is disease specific and the same for all instances. There is a need to have disease specific management configurations per server instances. Some countries need to use 10 days of followup of contacts rather than the default 14 days.
### Proposed Change
- Add a parameter in sotmas.properties file for users to specify the incubation period for COVID. If null, use default disease parameters, else use  server specified.
- We can add this parameter only for COVID for now

**Comment by bernardsilenou** [comment]
ref: 
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/5

**Comment by MateStrysewskeSym** [comment]
This is already possible by using the diseaseconfiguration table in the database.

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym I created this issue because in Swiss, they do 10 days follow-up instead of the regular 14. My questions is if this can be changed on a specific server? I am lost here, thanks

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou As I said, it can be configured in the diseaseconfiguration table in the database, which is of course part of the server.

**Comment by bernardsilenou** [comment]
Many thanks, Got it
