### ISSUE TITLE
Add pre-existing conditions to contacts [3]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2564]
### Situation Description
- We currently document pre-existing conditions for cases documented under the clinical course module. It is of need to document this information for contacts. This is important to identify contacts that need special needs base on the their medical conditions. 
### Feature Description
-  Add a drop down variable just above General comment to the contact called preexisting conditions
- if yes, then display preexisting conditions as in clinical course
- If contact becomes a case, transfer the preexisting conditions to the case
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/88684738-7400dd00-d0f5-11ea-9ff9-f689ab9554ef.png)

![image](https://user-images.githubusercontent.com/12996724/88686096-035ac000-d0f7-11ea-9b6f-46522b699b4b.png)

**Comment by bernardsilenou** [comment]
ref: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/24

**Comment by bernardsilenou** [comment]
German instance has a variable called "immune suppressive therapy/basic disease present". This is a limited way of assessing the pre-existing conditions for the contact person. A possible solution is to refine this veritable as explained in this issue.

We have to remember to maintain categories of pre-existing conditions since they differ from country to country.

![image](https://user-images.githubusercontent.com/12996724/88909380-4f267a00-d25b-11ea-8628-006dc55f111f.png)

**Comment by markusmann-vg** [comment]
In scope:
- [ ] Add pre-existing conditions to contacts
- [ ] Copy pre-existing conditions to case, when the contact is converted to a case

@bernardsilenou 
When we remove the immunsuppresive therapy from here and just add the pre-existing conditions, what are we doing with old data, where immunsuppresive therapy was set to [yes,no, unknown]?


out of scope:
- [ ] migration

**Comment by bernardsilenou** [comment]
@markusmann-vg Good comment, I discussed with Gaby and we decided to migrate/ map "immune suppressive therapy..." to immune deficiency including HIV. This happens only on  German instance,  international is fine
Thanks
