### ISSUE TITLE
Day and month of birth captions are shown in the UI

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2569]
### Steps to Reproduce
1. Login to Sormas application with valid credentials
2. Select Cases or Contacts and click on Case Person or contact Person respectively.
3. See the Date of birth text displayed

### Expected Behavior
~~The text should not overlap on the other fields and may be it should just be "Year of Birth"~~

### Screenshots
![DOB_text overlap](https://user-images.githubusercontent.com/62763628/88800502-90aa1d00-d1a8-11ea-8863-70baa9e93d37.PNG)

### System Details
* Device:
* SORMAS version: 1.46.0
* Android version/Browser:

**Comment by ChristopherRiedelSymeda** [comment]
No, the first caption is correct, the other two should not be displayed, this is the error here.

**Comment by MateStrysewskeSym** [comment]
Solution is probably to manually remove the caption where it's not needed (also check the mobile app)

**Comment by FredrikSchaeferVitagroup** [comment]
By the way: shouldn't the intended caption be DATE OF BIRTH (YEAR / MONTH / DAY) instead of DATE OF BIRTH (MONTH / DAY / YEAR)? The order would then match the order you enter the date in the fields.
