### ISSUE TITLE
Duplicate contact detection among contacts in db

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2571]
### Situation Description
We currently can control duplicate contacts during contact creation but not among contacts that exist in the db.
### Feature Description
- Just as we have for cases, add the option to search for duplicate contacts among contacts in the db

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym French team is working on it and we expect the pull request by Monday

**Comment by MateStrysewskeSym** [comment]
Duplicate of #2350. @bernardsilenou Please search the repository for similar issues before submitting new ones.
