### ISSUE TITLE
Save alert is popped up before actual user confirmation for campaign archives

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2580]
### Bug Description
When a Campaign is selected and clicked on Archive or De-archive, the save confirmation alert is popped up before the user confirms on the confirmation pop-up window.

### Steps to Reproduce
1. Login to test-afghanistan.netzlink.com (ex: as National user)
2. Click on Campaigns and select a campaign.
3. at the bottom of the pop-up window, click on archive option.
4. see that the "Campaign saved" alert is already displayed although the confirmation pop-up window is displayed with Yes and No options.

### Expected Behavior
Alert has to be displayed after user gives a confirmation on the confirmation window

### Screenshots
![Campaign archive confirmation](https://user-images.githubusercontent.com/62763628/88939868-55cae680-d287-11ea-98c4-c8a0ba09745e.PNG)

### System Details
* Device:
* SORMAS version: 1.46.0
* Android version/Browser:

### Additional Information
Same for de-archive option

**Comment by MartinWahnschaffe** [comment]
Actually this is working the same way it is done for other entities. Before archiving the entity is saved to make sure that any data that may have been changed is not lost.
