### ISSUE TITLE
"set cleared to unknown" button on symptom information page

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2584]
### Feature Description
Just like there is a "set cleared to no" button on symptom information page, there should also "set cleared to unknown" button to accomodate for situations where symptom variables are unknown

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS-Version: 1.50.0-SNAPSHOT

**Comment by AndyBakcsy-she** [comment]
linking new issue #3121
