### ISSUE TITLE
Give surveillance supervisors the right to merge and delete entities in their jurisdiction.

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2587]
### Proposed Change
-  Surveillance supervisors should be able to do the following to entities: cases, contacts, events in their region only.
  1. merge duplicates: system will search an proposed only possible duplicate cases in their region
  2. Delete entities: This should only apply to entities they create (reporting user) or in their region

**Comment by Iheanacho2027** [comment]
#2316 will be more preferable because not every surveillance supervisor might be good or active in data management just like practiced in Nigeria. This role should be given to specific users so we do not have cases or wrong deletion of cases or merging of duplicates

**Comment by Iheanacho2027** [comment]
I suggest we close this ticket and focus on #2316

**Comment by bernardsilenou** [comment]
> #2316 will be more preferable because not every surveillance supervisor might be good or active in data management just like practiced in Nigeria. This access should be given to specific users so we do not have cases or wrong deletion of cases or merging of duplicates.

I understand you now, so we then have to wait for the next 2 sprint  and address the user right management issue that will permit admins to decide who can do what.
