### ISSUE TITLE
Introduce new contact field "returning traveler" for contact in contact tab [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2603]
### Feature Description
There is a need for countries to document returning travelers and follow up on them. We can't use event in this situation because for returning travelers, even though coming out of the same flight may be coming from different countries. Creating them as contact without a case does not also tell us when there is no case. The idea is to create returning travelers as contacts without a case with category "returning travelers"
 
### Proposed Change
-  Add contact category: Contact with source case/ Returning traveler  (Reiserückkehrer)
- Add filter for this variable
- Adjust the contact form accordingly by hiding fields that are related to source case when contact type is returning traveler. More refinement will follow on the form changes.

**Comment by bernardsilenou** [comment]
We need to add the contact type field on the forms when creating contact while in a case and also from the contact directory

**Comment by bernardsilenou** [comment]
contact category and contact type already exist, so we need a new name to classify returning treavellers

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym any suggestion?

**Comment by JonasCir** [comment]
@bernardsilenou I wrote you an email regarding this matter. 

I advocate to use a single event for a flight and similar here. The property which groups these persons together is that they returned with the same plane, the country is an additional detail. 
Also I had a discussion with a GA which now hands out registration forms for returning travelers and they searched for a way to insert the collected data into SORMAS. In this case, they could create an event for each day (eg., trav-return-2020-08-27) and add all persons who registered that day to it.

The thing is that I want to avoid that (passive) returning travelers mix with (active) contact data of live cases. Technically travelers are not real contacts, so mixing them in the same table could make it harder for users to keep overview.

**Comment by bernardsilenou** [comment]
- We discussed today and one simple solution we though of is to add a variable called "returning traveller" (yes, no unknown, NA default) to the contact entity form.
- Details about the travel will be documented under api data tab (the new exposure entity)
@MateStrysewske what do you think?

**Comment by Candice-Louw** [comment]
Please include a filter for this value on the Contacts Directory too, please.

Proposed per Bernard's description - 
![image](https://user-images.githubusercontent.com/65529128/93808032-c0771d80-fc4b-11ea-9f2a-db47b29dcce2.png)

**Comment by markusmann-vg** [comment]
- [ ] Add yes/no/unknown field to contact
- [ ] Add filter to contact directory

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
