### ISSUE TITLE
Add english version for Afghanistan locale [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2604]
### Situation Description
Same way we have it for Nigeria, etc.

### Feature Description

- [x] Define what names should be used for infrastructure
- [x] Define what names should be used for user roles
- [x] Add needed property files - see Ghana and Nigeria for reference -> add to crowdin
- [x] Merge latest translations
- [x] Add to language enum

#### User roles
Cluster Coordinator = Community level (Community Informant in SORMAS)
District Coordinator = District level (Surveillance Officer in SORMAS)
Provincial Coordinator = Region level (Surveillance Supervisor in SORMAS)
National Coordinator = National Level (National user in SORMAS)

#### Infrastructre
Province (Region in SORMAS)
Cluster (Community in SORMAS)

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba Can you provide the names that are supposed to be used for the user roles?

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda 
Cluster Coordinator = Community level     (Community Informant in SORMAS)
District Coordinator = District level     (Surveillance/Contact Officer in SORMAS)
Provincial Coordinator = State level     (Surveillance or Contact Supervisors in SORMAS)
Regional Coordinator = Area level (Zones) (Area Supervisor in SORMAS-New)
National Coordinator = National Level  (National user in SORMAS)
Hub Coordinator = Supranational level (International user in SORMAS)
Admin = Admin level

**Comment by MateStrysewskeSym** [comment]
This should definitely be done in Crowdin!
