### ISSUE TITLE
Re-activate validation of german case classification

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#2609]
### Feature Description
In #2230 we have implemented a case classification for german systems that also includes a validation.

### Problem Description
This validation has been deactivated in #2599, because it wasn't properly usable - cases could not be saved when the validation fails, e.g. because no symptoms are entered.

### Proposed Change
Discuss how to resolve this.

Also:

- [ ] Migration: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2230#issuecomment-658720032

**Comment by JaquM** [comment]
It will be done with the #4770 so I'll close this one.
