### ISSUE TITLE
Increase dialog box in statistics section when filtering by case classification

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2610]
### Steps to Reproduce
1. Filter by confirmed cases with positive lab result
2. 

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/89544054-f24e3500-d801-11ea-8caa-8abdd8d6d7da.png)

### System Details
* Device:
* SORMAS version: 1,45
* Android version/Browser:

**Comment by DavidBaldsiefen** [comment]
Closed in favor of #1795
