### ISSUE TITLE
Add filters and search method on Events directory based on person (and source type variables) [1]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2619]
### Situation Description
Users are unable to search by source type and personal identifiers of event participants.
### Feature Description
Add source name and phone number to the search box filter which has ID and description as shown by the arrow in the image below

![image](https://user-images.githubusercontent.com/50739609/89865589-ee296b00-dba5-11ea-862f-47dacb8e46e7.png)

**Comment by bernardsilenou** [comment]
- In the search box add all personal identifiers (name, phone number, ....) used in case directory
- Add filter for DOB ( year, month and day) just as in case directory. This will increase the sensitivity.
- The result of the search is a **rank** list of all event with event participant that meet the criteria of the filter. Highest similarity at the top of the list.
- Users will then be able to open the event and when they open the event participant tab, the table of rank event participants that meet the criteria should be shown to user.  This means we need to implement search within event participant first.
- If users need to navigate back to open another event, they do not need to search again, thus we keep the cache of previous search.

**Comment by bernardsilenou** [comment]
linked to ##1631

**Comment by markusmann-vg** [comment]
@bernardsilenou your requirements are trested here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3397

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas v1.57.0-snapshot on local environment
