### ISSUE TITLE
[SORMAS2SORMAS] Add encryption [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2626]
### Feature Description
- Encryption/Decryption is needed for the binary data which is sent from one Sormas Instance to another one.
- After setting up the local keystore (#2621) and truststore (#2622), encrypted data can be shared between SORMAS instances which have agreed to communicate (#2622, #2623)
- Provide an encryption/decryption service for encrypting/decrypting data sent to/received from a certain SORMAS instance

**Comment by HolgerReiseVSys** [comment]
I have [added some crypto utils](/hzi-braunschweig/SORMAS-Project/compare/feature-2626-SORMAS2SORMAS-crypto)
