### ISSUE TITLE
Infrastructure management for "other" health facilities [0,5+X]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#263]
See #238 and #232 

We need an interface that allows listing all "other" health facilities and based on that create a new health facility or replace "other" with an existing health facility. This should also incorporate bulk operations (selecting multple cases at once).
Unclear if this should be part of the infrastructe view or the cases grid.

- [x] create a mockup

**Comment by MateStrysewskeSym** [comment]
see https://app.moqups.com/symeda/3NUENEwuOE/edit/page/af3e50623

**Comment by MateStrysewskeSym** [comment]
- [ ] add "edit" moqup: Should list all facility options of the selected community. User can either pick one of them or create a new facility

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] consider previous hospitalizations and laboratories (do #440 first)
- [ ] use facility grid instead of button list to show more details

**Comment by MartinWahnschaffeSymeda** [comment]
This is now possible without a dedicated screen by using bulk edit facilities (see #577)
