### ISSUE TITLE
[SORMAS2SORMAS] Add an option to comment your push

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2630]
### Feature Description
Add an option to send a comment, when transferring data to another SORMAS instance

### Additional Information
=> What about the request for a transfer
=> What about the bulk sending / Can we add the comment there as well

**Comment by kwa20** [comment]
@markusmann-vg Does this issue diverge from the current implementation? 

<img width="187" alt="commentShare" src="https://user-images.githubusercontent.com/70317594/115237574-01b9a800-a11d-11eb-814c-68e205043280.PNG">

If so, I'd use this to add specification, if not I'd create a new one.

**Comment by MateStrysewske** [comment]
@markusmann-vg Why is this issue closed?

**Comment by markusmann-vg** [comment]
@MateStrysewske Already done with a previous issue
