### ISSUE TITLE
Filter by CASE ID in case directory returns too many results

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2632]
### Bug Description

When searching for cases by Case ID (first 6 chars), and when searching for contacts by Contact ID (first 6 chars), many results are returned as opposed to only 1 result.  This means users have to scroll through lists of results again to find the right entry.

Cases > Case Directory > Enter Case ID (first 6 chars) in filter "ID, name, EPID number, facility..."
Contacts > Contact Directory > Enter Contact ID (first 6 chars) in filter "ID, name, case ID, case name, per..."

If a case ID contains only letters (A-Z), the correct result is returned.
As soon as a case ID contains a number (0-9), many results are returned (see screenshots).

Possibly related to update: [https://github.com/hzi-braunschweig/SORMAS-Project/issues/2396](https://github.com/hzi-braunschweig/SORMAS-Project/issues/2396)

### Steps to Reproduce
1. Cases | Contacts
2. Case Directory | Contact Directory
3. Enter Case ID (first 6 chars) in Filter "ID, name, EPID number, facility..." | Enter Contact ID (first 6 chars) in filter "ID, name, case ID, case name, per..."

### Current Behavior
Many results are returned after entering first 6 chars which means users need to scroll through the results to find the required entry.

### Expected Behavior
Only 1 result is returned in search that matches the first 6 chars of Contact ID | Case ID (regardless of letter or number)

### Screenshots
<img width="540" alt="20200811_IDSearch" src="https://user-images.githubusercontent.com/65529128/89911886-3cfcf200-dbf2-11ea-8355-d36e727331eb.png">

### System Details
* Device: Desktop/Web
* SORMAS version: 1.46
* Browser: All

**Comment by bernardsilenou** [comment]
@Candice-Louw if you do not use all characters while filtering by case Id, there is no way the system will know that u are using the case id, thus is considers it as the name and will use the similarity logic rather than exact match.
We should recommend to uses to use the complete id if their goal is to filter by id

**Comment by Candice-Louw** [comment]
This was recommended to the users, but the result is the same.

Findings substantiated by your own, new bug report, to the same issue: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2787

@bernardsilenou - please close this issue since your new report is in essence the same problem that was originally reported here.
