### ISSUE TITLE
Multiple samples on event officers view

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2635]
### Bug Description
When an event officer account create a sample and rest result in one step, there are multiple versions of the sample. This does not happen when with admin or national user
### Steps to Reproduce
1. Log in as event officer role only
2. create a sample with positive lab result fro event participant
3. Convert event participant to case
4. Go back to event participant from and view the sample
5. See figs

### System Details
* Device:web
* SORMAS version: 1,46
* Android version/Browser: firefox

**Comment by bernardsilenou** [comment]
![image](https://user-images.githubusercontent.com/12996724/89948702-dcd47300-dc26-11ea-92a1-0c0f46a41b8b.png)

**Comment by bernardsilenou** [comment]
This may be related to #2557

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym any comment on this

**Comment by MateStrysewske** [comment]
This also happens for tasks on cases.

**Comment by bernardsilenou** [comment]
@Candice-Louw Please add the issue with multiple samples here please

**Comment by MateStrysewske** [comment]
@bernardsilenou I can't reproduce this. Can you confirm that this still happens on 1.47.0?

**Comment by bernardsilenou** [comment]
@MateStrysewske I just tested on test1401 on 1,47,1 and found the same thing. 
This happen with **event officer role**
In addition, when the sample result is positive and you choose the option to create a case, system retains error but still create a case wth a blanc case from tab 
![image](https://user-images.githubusercontent.com/12996724/92143947-486cc300-ee16-11ea-85a5-7d3853b87cb2.png)

Is there any right that prevent event officers from classifying cases or creating pathogen test?

**Comment by Candice-Louw** [comment]
**Server used** (https://test1401.sormas-oegd.de/sormas-ui/) -

ADMIN: Administrator, Benutzer importieren, Nationale*r Benutzer*in

Same behaviour when using the default National User login:  Benutzer importieren, Nationale*r Benutzer*in

<img width="535" alt="20200906MultiTasks" src="https://user-images.githubusercontent.com/65529128/92314283-f8d4f580-efd5-11ea-9faa-7919e8b984ba.PNG">
<img width="534" alt="20200906MultiTasks2" src="https://user-images.githubusercontent.com/65529128/92314284-fb374f80-efd5-11ea-8b4c-b41412d8d229.PNG">



<img width="532" alt="20200906MultiTasks3" src="https://user-images.githubusercontent.com/65529128/92314331-89133a80-efd6-11ea-9f7c-0e9c7237a5ff.PNG">

**Comment by MateStrysewske** [comment]
@Candice-Louw The problem with multiple tasks being displayed has already been resolved. What I can't reproduce is the problem with multiple samples being created/shown.

**Comment by MateStrysewske** [comment]
@bernardsilenou I can reproduce it now (though not the error you've encountered lately).
