### ISSUE TITLE
Provide a Button in ContactDataView to link to a symptom diary in Climedo [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#2639]
### Situation Description

Health departments use/want to use SORMAS alongside with Climedo. When a user is in the ContactDataView, he wants to be able to 
- quickly create a Patient in the Climedo system for the Contact currently opened in SORMAS
- quickly jump to the according Contact's symptom diary in Climedo if one exists.

### Feature Description

For this a button labeled "Symptom diary" is to be implemented that shows in the ContactDataView if there is an URL to a Climedo system defined in the domain's sormas.properties.

If the user clicks that button, a new tab in his browser shall open that calls a link containing the defined URL and the Contact Person's Uuid. How exactly the link is supposed to look like shall be discussed with Climedo developers.

The by-this-link-called Climedo system can then check if there already exists a Patient for the ContactPerson. If no, it can start a patient creation procedure. If yes, it can show the according symptom diaries. This logic is to be communicated to Climedo developers.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOOT
