### ISSUE TITLE
Extend AbstractContactView.getReferenceByUuid(...) to also handle Person.uuid values [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#2640]
### Situation Description

Health departments use/want to use SORMAS alongside with Climedo. Whe a user looks at a Patient in Climedo, he wants to be able to quickly open the according Contact in SORMAS. For this, Climedo calls the URL [server-adress]/sormas-ui/#!contacts/data/[Uuid]. But since the only Uuid available to the Climedo system is the Person.uuid, a logic has to be implemented to handle these calls accordingly. So far, only Contact.uuid's can be handled.

### Feature Description

The method AbstractContactView.getReferenceByUuid(...) shall first check if there exists a Contact with the Uuid given as parameter. if none is found, it shall look if a Person exist with that Uuid. If yes, it shall return a reference to the newest Contact related to that Person.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS-Version: 1.49.0-SNAPSHOOT
