### ISSUE TITLE
Add place of residence filters to statistics [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2642]
### Situation Description
There are health authorities which need to report the cases filtered by the place of residence. This is currently not possible. In the future we want to add this functionality / filter to the statistics section. Right now we have to deliver a quick workaround

### Feature Description
To the detailed export of cases we should add the place of residence from the person so that this export can be filtered by community, zip code or city of the person's place of residence for example.

**Comment by BarnaBartha** [comment]
@markusmann-vg The case directory free text filter allows a user to search for city and postcode, maybe we want to extend this? 
We need a definition of place of residence, currently the detailed case export contains region / district / community / city / address / postal code / gps coordinates of address. Do we want to merge these or some of these into one column called place of residence ?

**Comment by markusmann-vg** [comment]
The place of residence can be taken from the "case person" and should be merged in the export

**Comment by bernardsilenou** [comment]
> @markusmann-vg The case directory free text filter allows a user to search for city and postcode, maybe we want to extend this?
> We need a definition of place of residence, currently the detailed case export contains region / district / community / city / address / postal code / gps coordinates of address. Do we want to merge these or some of these into one column called place of residence ?

Please keep all address items in separate columns

**Comment by BarnaBartha** [comment]
After discussing what we want to achieve with this story, we agreed on extending the filter possibilities on the statistics part:
![Screenshot 2020-08-18 at 13 28 34](https://user-images.githubusercontent.com/8166805/90504428-b7c98e00-e159-11ea-87b0-1df4d44ce3f1.png)

**Comment by bernardsilenou** [comment]
@BarnaBartha The place of residence of the person belongs to a region and district which can be different from the that of the case,  I suggest we use the list: place of residence: region, district, community, city, postcode address to make filtering faster, prevent errors when the same place of residence exist in 2 regions.
