### ISSUE TITLE
Enable the usage of population data in campaign diagrams [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2644]
### Situation Description
Campaign diagrams currently purely rely on campaign form data.

### Feature Description
In addition to that we need to be able to use population data as reference value for percentage charts (#2528 needs to be done first).

- [x] define what needs to be implemented, once #2528 is done.
- [x] Add a field called "populationGroup" of data type AgeGroup to the CampaignDiagramSeries
- [x] When the field is set, instead of querying for data of a campaign form, query for the population of that age group within the given region/district. 
- [x] Log a warning, when populationGroup and formId are both defined for the CampaignDiagramSeries
- [x] When no data is available inform the user ~~and switch the diagram back to absolute numbers~~ by showing a text below the chart that says for which regions/districts population data is missing.

Example diagram definition:

camaigndiagramseries JSON

```
[
  {"fieldId":"childAbsent","formId":"icHouseholdMonitoring"}
]
```

campaigndiagramtotal JSON

```
[
  {"populationGroup":"AGE_0_4"}
]
```

Population data for Afg is available here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2645#issuecomment-692669390

**Comment by MateStrysewske** [comment]
- [ ] Warning is not displayed below the chart when there is no population data present for the specified age group
