### ISSUE TITLE
Setup demo server with example population data

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2645]
In order to use it as a reference value in percentage charts (see #2644), we need to have population data available.

To make sure that this is working as expected we should put gather example data for a few districts in at least two regions and put them into the APMS demo server. This can be done using the existing import mechanism in the configuration section of the web app.

**Comment by hzi-old** [comment]
@MartinWahnschaffeSymeda See as requested
[Target_Admin cov_Missed children data.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5196280/Target_Admin.cov_Missed.children.data.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba @asohh 
You can use the following CSV to import population data on the system:
[Target_Admin.cov_Missed.children.data.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5224671/Target_Admin.cov_Missed.children.data.txt)

On my system there were some districts that did not match. Hopefully you can fix that and provide the complete set of areas, regions and districts (and clusters?) here.
