### ISSUE TITLE
[FRENCH TEAM] Updating the case symptoms based on visit symptoms (case follow-up) [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2651]
### Situation Description
#1886 has added follow-up visits to cases.

### Feature Description
When a new visit is created for a case, the symptoms of the case should automatically be updated.
See clinical visits for comparison.

**Comment by bernardsilenou** [comment]
The same as point 6 of  #2678

**Comment by bernardsilenou** [comment]
I deleted the comment in issue #2678, so we maintain this issue now

**Comment by bernardsilenou** [comment]
@markusmann-vg  @xavier-calland is working on this in this sprint
