### ISSUE TITLE
Add data of follow-up visits to case export [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2653]
### Situation Description
#1886 has added follow-up visits to cases.

### Feature Description
We want to have the same information that is included in a contacts export also for the case export:

- number of visits
- last cooperative visit was symptomatic
- date of last cooperative visit
- symptoms of last cooperative visit

This has already been implemented, but is commented out, since pseudonymization is not implemented for it yet.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  In terms of "number of visits", do we also count visits when case is converted from contact or just visits while a case, It will be good to have 2 types: all visits and visits while the person is a case

**Comment by bernardsilenou** [comment]
Since many visits is often done in one day and the expected number of visit is 1 per day, In order not to have false statistics, we should add a column of: all visits and another for sum of visits per day with only the one visit selected per day.

**Comment by markusmann-vg** [comment]
- [ ] uncomment the code
- [ ] check the code for sensitive data (comment and staff)
