### ISSUE TITLE
Quarantine end dates list is empty

### ISSUE THREAD

**Issue by o-frietsch** [hzi-braunschweig/SORMAS-Project#2657]
### Bug Description

The interface described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/2330 doesn't seem to return any entries.

### Steps to Reproduce
1. Call the interface in https://github.com/hzi-braunschweig/SORMAS-Project/issues/2330 .
2. Inspect the result which is an empty array.

### Expected Behavior

The array should not be empty.

**Comment by o-frietsch** [comment]
In first go, an end date for all people should be delivered.
In second go, only people with a known PIA account should be considered, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/1970

**Comment by bernardsilenou** [comment]
> In first go, an end date for all people should be delivered.

I think this option is better. We should use the default followup until date for all entities (case, contacts).
> In second go, only people with a known PIA account should be considered, see #1970

**Comment by o-frietsch** [comment]
There have been data protection worries about the first solution, because PIA gets some data which it doesn't need (i.e. end dates for people that don't have PIA accounts).

**Comment by bernardsilenou** [comment]
@o-frietsch  Understood. In sormas, we can automatically fill "quarantine end date" with "followup until date" and only push this date to users who have PIA account according to  point 2. The goal is to always match quarantine end date to followup until date and users can override quarantine end date if needed.

**Comment by Candice-Louw** [comment]
@fhauptmann @markusmann-vg Part of the MVP for PIA-SORMAS, CH  | Prio Super Hoch (v. 1.47.0) | Related to #1970 and #2330

**Comment by markusmann-vg** [comment]
@FredrikSchaefer will pick it up as fast as possible, when he's done with the other urgent tasks.
Latest Maté can take care of it beginning next week.

**Comment by markusmann-vg** [comment]
and one remark: 
 @MateStrysewskeSym  closed https://github.com/hzi-braunschweig/SORMAS-Project/issues/2330 on 17 Jun  // I am honestly surprised that this bug is encountered so late?

**Comment by FredrikSchaeferVitagroup** [comment]
I cannot reproduce this bug. Therefore I want to trace it down with questions to @o-frietsch 

- Did you use UNIX timestamps as parameter (e.g. like https://currentmillis.com/)? And were there really QuarantineEndDates after the time you specified as parameter? I know that the method returns an empty array when there is just no matching result found. I'm sorry if  this question sound a little silly, but sometimes the error is in basic things like that.

- Where did you try it: which server, and what exact request does not work?

**Comment by RobYed** [comment]
@FredrikSchaeferVitagroup I have actually made the requests which are returning empty arrays.

The request URL was
https://sb.sormas.netzlink.com/sormas-rest/visits-external/quarantineEndDates/0

As you can see I chose zero for the timestamp in order to really get all results. I also tested it with 1577833200000, which is the beginning of 2020. Both without any results.

I sorted out authorization problems as an issue. When I use wrong credentials, I get an unauthorized error.

**Comment by FredrikSchaeferVitagroup** [comment]
Thanks for the info. What user did you authenticate with?

**Comment by RobYed** [comment]
The user was the technical "sormas-pia-user"

**Comment by FredrikSchaeferVitagroup** [comment]
I've tested the functionality with the SurvSup account, and it works. Of course, I had to create contacts which have a quarantine end date first.
Maybe that is not an issue of functionality, but of user rights.
It may be that there are just no matching contacts that the sormas-pia-user is allowed to see.
I now gave the sormas-pia-user more rights (it also has the National User role now). Can you try again? I don't have the sormas-pia-user's password...

**Comment by RobYed** [comment]
@FredrikSchaeferVitagroup Thanks! This indeed was the problem. I now get 14 results back 👍 

How can we assure that rights are set correctly on all stages?

**Comment by FredrikSchaeferVitagroup** [comment]
I don't know yet, since the National User role is definitely not an appropriate right for the sormas-pia-user to have in a production system. I will come back to you about that, probably on monday. 
For now, the sormas-pia-user will keep it's rights in the demosystem.

**Comment by MateStrysewskeSym** [comment]
The solution for this problem is to add the REST_EXTERNAL_VISITS_USER role to the list of users that see all contacts by adding it to the first if clause in the contact user filter method (line 847).
