### ISSUE TITLE
Dashboard > Incorrect "New Cases" calculation/visualisation

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2662]
### Bug Description
DE case classifications (D. labor. ohne klin. && E. labor. und unbek. klin. Bild.) are not included in the dashboard overview statistics ( X New Cases, "CONFIRMED" sub-section count) nor in the epidemiological curve for "confirmed cases".

Users are finding this confusing and reporting that the system is not working/calculating correctly.

Caused by: #2230 (see "out of scope" statement)

Case classification full name | Code | Var
-- | -- | --
„klinisch-labordiagnostisch bestätigte Erkrankung“ [C. klin-labor. bestät.] | C | CONFIRMED
„labordiagnostisch nachgewiesene Infektion, klinisches Bild nicht erfüllt“ [D. labor. ohne klin. Bild] | D | CONFIRMED_NO_SYMPTOMS
„labordiagnostisch nachgewiesene Infektion, klinisches Bild unbekannt“ [E. labor. und unbek. klin. Bild.] | E | CONFIRMED_UNKNOWN_SYMPTOMS

- [ ] C, D and E should be counted as 'Confirmed' (collectively) and indicated on the dashboard at: X New Cases, "CONFIRMED" sub-section count.

- [ ] C, D and E should be indicated as 'Confirmed' (collectively) and indicated on the dashboard in the Epidemiological Curve. 

### Steps to Reproduce
1. Dashboard > Scroll to X New Cases (X confirmed, x probable, x suspect, x not a case, x not yet classified)
2. Cases > Open existing case/create new case > Scroll to "Case classification" > select (confirmed case with no symptoms - D. labor. ohne klin. ||  confirmed case with unknown symptoms - E. labor. und unbek. klin. Bild.) > Save
3. View Dashboard > Case not included in "Confirmed" case count, nor "Confirmed" epidemiological curve

### Expected Behavior
- [ ] C, D and E should be counted as 'Confirmed' (collectively) and indicated on the dashboard at: X New Cases, "CONFIRMED" sub-section count.

- [ ] C, D and E should be indicated as 'Confirmed' (collectively) and indicated on the dashboard in the Epidemiological Curve. 

### Screenshots
Dashboard >
<img width="813" alt="20200817_Dashboard" src="https://user-images.githubusercontent.com/65529128/90415633-ab89f600-e0b1-11ea-823f-d912b431875a.png">

### System Details
* SORMAS version: 1.46.0

**Comment by bernardsilenou** [comment]
@ChristopherRiedelSymeda @MateStrysewskeSym @markusmann-vg @GabrielePoggensee 
Please lets have a look at this in this sprint. Users are confused and worried while numbers are not adding up and cases are missing

**Comment by BarnaBartha** [comment]
@markusmann-vg 
If something is not within the scope of a ticket does not mean it becomes later a bug. This needs to be estimated by the team.

**Comment by bernardsilenou** [comment]
@markusmann-vg Since this has not been estimated, I suggest we take it to next sprint because we plan to create a collection of minor issues linked to dashboard and it may to estimate all of them in one goal for next sprint.

**Comment by bernardsilenou** [comment]
Please also verify that C, D and E are indicated as 'Confirmed' (collectively)  in statistics section

**Comment by markusmann-vg** [comment]
Will be treated with: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3004
