### ISSUE TITLE
Add a Date of Birth to already existing person information during import

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2663]
### Feature Description
Date of birth information should be among the information list for the already existing person, just as it is for the person about to be imported during import. This will help to make good judgements based on comparison of Age and Date of birth information used simultaneously
### Possible Alternatives
![image](https://user-images.githubusercontent.com/50739609/90476485-80d78600-e121-11ea-9b29-d4eb737c07d9.png)

**Comment by MartinWahnschaffe** [comment]
See #4003
