### ISSUE TITLE
Add input assistant and plausibility check

### ISSUE THREAD

**Issue by MOONROC-LHD** [hzi-braunschweig/SORMAS-Project#2666]
**### Situation Description**
At the moment, the following errors can occurr when inserting data:
- `Quarantine end date` before `Quarantine start date`
- Year of any kind of date fields can be for example 0139, 8482, 0202, 2222 or else (see `Meldedatum`, `Untersuchungsdatum`, `quarantine end date` etc.)

Also, almost every data point has to be inserted manually

**### Feature Description**
Integrate plausibility check for the above mentioned cases.
Additionally:
- autofill fields `federal state`, `district` and `city` after input of `postcode`
- add option to retrieve contact or adress data from another case or contact person (in case of family members or inhabitants of community facilities)
- as soon as contact and adress fields for custodians (#2658) are available: add a tick box to transmit adress data from patient to custodian

**Comment by KristinaBorch** [comment]
The date validation for quarantine was implemented by https://github.com/hzi-braunschweig/SORMAS-Project/issues/4559 and also the year validation is already implemented. Your additional feature request for automatic filling of address fields will probably be implemented by https://github.com/hzi-braunschweig/SORMAS-Project/issues/2385 and taking over addresses for example people living in the same household will probably be implemened by https://github.com/hzi-braunschweig/SORMAS-Project/issues/8804. 
Is your request herewith done and can we close the issue?

**Comment by MOONROC-LHD** [comment]
done, you can close, thanks

Am Do., 12. Mai 2022 um 10:43 Uhr schrieb KristinaBorch <
***@***.***>:
