### ISSUE TITLE
Adjust Covid-19 Symptoms for Switzerland 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2669]
### Situation Description

The exisitng symptoms for COVID-19 need to be adjusted for CH systems.

### Feature Description

Adjust the symptoms for SORMAS CH to match the following definitions:

SORMAS CH German | SORMAS CH English | SORMAS symptoms – Data dictionary
-- | -- | --
Fieber | Fever | fever
Allgemeines   Krankheitsgefühl | General signs   of disease | generalSignsOfDisease
Fiebergefühl | Feverish   feeling | Missing
Schüttelfrost   oder Schwitzen | Chills | chillsSweats
Gesteigerte   Müdigkeit | Increased   fatigue | Missing
Allgemeine   Schwäche | General weakness | ~~Fatigue/general weakness~~ **Missing**
Kopfschmerzen | Headache | Headache
Muskel- oder   Gliederschmerzen | Muscle pain | Muscle pain
Verwirrtheit | Confused/disoriented | confusedDisoriented
Schnupfen (laufende oder verstopfte Nase) | Runny nose | runnyNose
Halsschmerzen | Sore throat | soreThroat
Trockener Husten ohne Auswurf | Dry cough without sputum | Missing
Husten mit Auswurf | Cough with sputum | coughWithSputum
Husten mit blutigem Auswurf | Coughing with heamoptysis| **coughWithHeamoptysis**
Rasche Atmung | Rapid breathing | rapidBreathing
Schwierigkeiten beim Atmen | Difficulty breathing | difficultyBreathing
Kurzatmigkeit | Difficulty in brealthing | difficultyBreathing
Atemnot in Ruhe oder bei Anstrengung | Breathlessness   at rest or during exertion | Missing
Druck auf der Brust | Pressure on   the chest | Missing
Brustschmerzen | Chest pain | chestPain
Blaue Lippen | Blue lips | Missing
Allgemeine Kreislaufprobleme | General   blood circulation problems | Missing
Erhöhte Herzfrequenz (Herzrasen) | Tachycardia | **Fast heart rate (Tachycardia)**
Herzstolpern | Palpitations | Missing
Schwindel (beim Aufstehen aus dem Sitzen und Liegen) | Dizziness   (when standing up from a sitting or lying position) | Missing
Blutdruck zu hoch oder zu tief (gemessen) | Blood   pressure too high or too low (measured) | Missing
Übelkeit | Nausea | nausea
Erbrechen | vomiting | Vomiting
Bauchschmerzen | Abdominal pain | abdominalPain
Durchfall | Diarrhea | Diarrhea
Kein Urinlösen mehr | Urinary retention | Missing
Geruchstörung oder Verlust des Geruchssinns | Loss of smell | lossOfSmell | lossOfSmell
Geschmacksstörung oder Verlust des Geschmackssinns | Loss of taste | lossOfTaste
Hautausschlag | Skin rash | skinRash

- [x] add Fiebergefühl | Feverish   feeling
- [x] add Allgemeine   Schwäche | General weakness
- [x] add Gesteigerte   Müdigkeit | Increased   fatigue
- [x] add Trockener Husten ohne Auswurf | Dry cough without sputum
- [x] add Atemnot in Ruhe oder bei Anstrengung | Breathlessness   at rest or during exertion
- [x] add Druck auf der Brust | Pressure on   the chest
- [x] add Blaue Lippen | Blue lips
- [x] add Allgemeine Kreislaufprobleme | General   blood circulation problems
- [x] add Herzstolpern | Palpitations
- [x] add Schwindel (beim Aufstehen aus dem Sitzen und Liegen) | Dizziness   (when standing up from a sitting or lying position)
- [x] add Blutdruck zu hoch oder zu tief (gemessen) | Blood   pressure too high or too low (measured)
- [x] add Kein Urinlösen mehr | Urinary retention
- [x] Make sure the exact symptoms above or used for COVID-19 on CH systems
- [x] Make sure the captions are correct for CH

### Additional Information
[SORMAS CH_Symptome_deutsch_english_variableName.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5095812/SORMAS.CH_Symptome_deutsch_english_variableName.docx)

**Comment by MartinWahnschaffeSymeda** [comment]
Still missing:

- [ ] add symptoms to app
- [ ] make sure export is working correct

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda I think we may have some of the symptoms already in our db. I will check and add by the end of today.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou The list already has notes on which symptoms are already in the db (see third column).

**Comment by markusmann-vg** [comment]
The PIA synchronisation should be in another story and will be done by Conventic.
