### ISSUE TITLE
[SORMAS2SurvNet] Germany: Add externalId to Person [0.5]

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#2670]
### Feature Description
Add Person.externalId in domain model
and show it in PersonEditForm on German systems

**Comment by bernardsilenou** [comment]
@MateStrysewskeSym @markusmann-vg 
@fuatse 2 from zinger Sytems wish to work on this issue in this sprint. Please can you confirm that it is fine

**Comment by fuatse** [comment]
@bernardsilenou I already worked on this just and issued a pull request just in case :-)

**Comment by bernardsilenou** [comment]
@fuatse Wow, thats fast, @MateStrysewskeSym will have a look.

**Comment by bernardsilenou** [comment]
@fuatse Do you have any other issue in mind for the next step? can I suggest some?

**Comment by fuatse** [comment]
@bernardsilenou Yes please!
