### ISSUE TITLE
Error occurs during statistical generation of charts

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2675]
### Bug Description
An error occurs when trying to generate charts in the statistics menu
![image](https://user-images.githubusercontent.com/50739609/90715509-5c56e780-e2a2-11ea-9aa4-43e52d8d2aaa.png)

**Comment by ChristopherRiedelSymeda** [comment]
@Iheanacho2027 Which version do you use?

**Comment by Iheanacho2027** [comment]
1.46.0

**Comment by MateStrysewske** [comment]
@Iheanacho2027 is this still happening?

**Comment by Iheanacho2027** [comment]
Nah bro. It's resolved

**Comment by MateStrysewske** [comment]
Thanks!
