### ISSUE TITLE
Hide animal contact from epi data for Covid-19 [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2676]
### Feature Description
- Hide the animal contact form on epi data. Further refinement of epi data will follow in another issue.
### Additional Information
Take this whole section out from api data form on all instance. For COVID-19 only

![image](https://user-images.githubusercontent.com/12996724/90782611-58a57e00-e2ff-11ea-901d-8b238332ddaf.png)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOT
