### ISSUE TITLE
Allow Surveillance Supervisors and Lab Managers to see Archived, Active and All cases

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2679]
### Problem Description
The dropdown that shows archived, active and all cases are not available on the surveillance supervisor and lab manager user accounts, just as it is in the user accounts of the surveillance supervisor, national user and clinicians. Surveillance supervisors should see active, archived and all cases within their jurisdiction because they are the ones who coordinate and supervise case data entry in their regions

**Comment by bernardsilenou** [comment]
@Iheanacho2027  I could see them with 1,50 when logged in as supervisor. Please signal in case it happens again.

![image](https://user-images.githubusercontent.com/12996724/96636073-0d1e4900-131d-11eb-93d9-a9838a74ed17.png)

**Comment by Iheanacho2027** [comment]
Yes it's now rectified with 1.50.0
