### ISSUE TITLE
Show visits on 'followup visits' of contacts and cases based on recent date and time of visit. [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2682]
### Feature Description
- When there are many followup visits done on a day, use the most recent visit based on date and time of visit; Not the date and time of creation in sormas. The current setting used creation date and this gives a wrong interpretation.

**Comment by markusmann-vg** [comment]
- [ ] We colorize the visits based on state of the latest visit of the day and not based on the first visit that was created day on that day.

**Comment by AndyBakcsy-she** [comment]
Verified this issue on SORMAS Version: 1.48.0-SNAPSHOT
