### ISSUE TITLE
Community is a required when creating health facility but red star is missing

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2683]
### Proposed Change
- Add red star to community
- male community a non required variable

![image](https://user-images.githubusercontent.com/12996724/90910381-8231d880-e3d7-11ea-925d-4fad275c8093.png)

**Comment by fuatse** [comment]
Hello @bernardsilenou , I just checked this and you can create a facility without specifying the community which means the field is currently not required. Do you mean it should be made mandatory ?

**Comment by bernardsilenou** [comment]
@fuatse I suggest community sound not be a required field when creating a health facility. It did not work on the dev system. I will test it again later. Thanks for the information.

**Comment by bernardsilenou** [comment]
community is not required
