### ISSUE TITLE
[EPIC] Epidemiological data refinement 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2688]
### Feature Description
The current epi data section was designed at the early stage of COVID when we had little or no knowledge of the disease. It is now time to throw out certain variables, add more and migrate others. This issue describe how the epid data tab will look like for all diseases.The forms presented here is only for COVID. 
### Proposed Change
See attachments
[epiDataRefinemant_Git_200828.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5208228/epiDataRefinemant_Git_200828.docx)

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske  Here are the migration documents put together by Gabby and me. All is ready for implementation now.
[Epidemiological data_type of place.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5168497/Epidemiological.data_type.of.place.xlsx)
[Epidemiological data_ Management.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5168498/Epidemiological.data_.Management.docx)
[Mapping for travelled outside of district.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5168499/Mapping.for.travelled.outside.of.district.docx)
[Epidemiological data_mapping old data.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5168500/Epidemiological.data_mapping.old.data.docx)
[Data mapping for social gathering.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5168501/Data.mapping.for.social.gathering.docx)

**Comment by GabrielePoggensee** [comment]
Draft mock-up
[Draft_mock_up_epidemiological data_200911.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5207497/Draft_mock_up_epidemiological.data_200911.docx)

**Comment by bernardsilenou** [comment]
@GabrielePoggensee Thanks for the updated document.
@GabrielePoggensee @markusmann-vg  I have short comment from the last document attached by @GabrielePoggensee . What are you suggestions on these:

- For caption called "Entry mask (source case), Details of contact": 
This is a filter to the contact table of all contacts that resulted to this case. It is good that we use the same form when creating a contact to be consistent because this is actually a contact creation process and retrospectively linking a case to its source case (source case can exist in db or not). We also have to remember to implement the "source tracing issue" first before this one because they both need the same methods. Have a look at my comment on August 3 to issue #389 

- For caption "Activities" I suggest we order them with more frequent options first on the drop-down: work, Travel, gathering, Party,,, (@GabrielePoggensee is this fine by you?)

- For caption "Drop-down  (facility type)" is this needed for exposure, considering the fact that many exposure activities may not take place in a facility? eg visits (this is a home), travel, animal contact, ....My suggestion is to exclude it and us the same design that we have for event entity. We can later in a refinement stage use the similar design as when creating cases that will permit up to then add facility type (@GabrielePoggensee is this fine by you?)

**Comment by GabrielePoggensee** [comment]
@bernardsilenou 
Activities: ok
Facility type: the setting (type of place) has to be included in SORMAS DE because this is a necessary adaption for the interface to SurvNet or other softwares.

**Comment by markusmann-vg** [comment]
New form for epidemiological data #2946 
Type of place in exposure details entry mask #2947
Replace gatherings with exposure (subsequently to be merged with travels) #2948
Data migration of epidemiological data #2949
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2994
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2993

**Comment by kwa20** [comment]
@markusmann-vg Closing this issue since the initially related issues are all closed
