### ISSUE TITLE
[IMIS] Local dev setup using maven-cargo

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2695]
### Feature Description
Setup of a local development
 server using maven-cargo-plugin. Setup is reduced to two steps:
- docker-compose up (database
 setup using the docker image)
- mvn cargo:run (install
 payara server, deploy artifacts start server)
The
 implementation of this task includes the integration of serverlib dependency artifacts in the maven build process, generating a dependency jar as well as a zip artifact.

**Comment by MartinWahnschaffeSymeda** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-cargoserver/README.md
