### ISSUE TITLE
[IMIS] Document generation for quarantine  decrees

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2696]
### Feature Description
Quarantine documents are generated from docs templates, defined placeholders are replaced by case data. The mechanism provides both a mapping from data available in SORMAS to predefined placeholders as well as ‘free’ placeholders which values are provided by the individual SORMAS
 user (e.g., room number of the officer). These user-provided values will be cached client-side.

The service for document generation is complemented by a mechanism to manage templates and a persistence service to store generated documents for a case.
The generalisation of case-related document filing to arbitrary documents has to be kept in mind (see issue #1771).

**Backend**:
- Pick a template engine
 to generate a document
- A service to persist,
 read and delete a template from the DB
- A service to generate
 a document from a template and a list of key/value pairs

**UI**:
- UI element to allow to
 generate a document from a templates
- UI element for the admin
 console to upload and manage templates

**Comment by akuckartz** [comment]
Maybe you should contact Stadt Köln which did something like that for DiKoMa.

**Comment by bernardsilenou** [comment]
@markusmann-vg what about ding it in r and link it to sormasui using any of the following r packages: rmarkdown, sweave or knitr

**Comment by JonasCir** [comment]
@akuckartz Good point, we already talked to them :)
@bernardsilenou  We already started to implement it in Java and we would like to stick to it. Further, no one of our team is familiar with R.

**Comment by JonasCir** [comment]
Just to clarify, we already investigated the issue and talked to several GAs about their requirements. Implementation is in progress :+1:

**Comment by AndyBakcsy-she** [comment]
Verified issue on the latest version of SORMAS Version: 1.51.0-SNAPSHOT

**Comment by MateStrysewske** [comment]
- [ ] Allow national users to generate quarantine documents (will be done by me)

**Comment by AndyBakcsy-she** [comment]
Validated the new functionality for the National User availability.
