### ISSUE TITLE
Again wrong placeholder in strings_fr-CH.properties

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#2700]
### Bug Description
As in #2342: _confirmationDeleteEntity_ in strings_fr-CH.properties is again wrongly containing _%d_ as placeholder. It seems that integrated translations reverted the change on 2020-07-10.

### Steps to Reproduce
1. Select Language fr-CH
2. Try to delete an entity (a contact maybe).

### System Details
* SORMAS version: 1.46.x, 1.47.0-SNAPSHOT

**Comment by StefanKock** [comment]
@MateStrysewskeSym please have a look on this and make sure this is stays fixed concerning incoming translations.

**Comment by MateStrysewskeSym** [comment]
@StefanKock no way to make sure it stays fixed. It's correct in Crowdin, however. I'll fix it again.
