### ISSUE TITLE
Event participant list adjustment [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2701]
### Proposed Change
- Use different columns for first name and last name
- Add sum of records at the top of the directory
- Add person identifier filters/search just as we have on the case directory: name, dob, phone number, .....
- Add column for "test result" (only final lab result): indeterminate, pending, negative, positive, NA/ No sample (when no sample was taken)
use the final lab result of the sample. If there are may results or samples, then use logic as described in #1860 on 28th July. 
- add filters for variables: converted to case (caseid) and positive sample test results.

**Comment by markusmann-vg** [comment]
**out of scope for this implementation, as we don't have yet the final lab result:**
- Add column for "test result" (only final lab result): indeterminate, pending, negative, positive, NA/ No sample (when no sample was taken)
- use the final lab result of the sample. If there are may results or samples, then use logic as described in #1860 on 28th July.
- add filters for variables: converted to case (caseid) and positive sample test results.
=> NEW ISSUE NEEDED

**in scope:**
- Use different columns for first name and last name
- Add sum of records at the top of the directory (Persons involved will be replace by "All (x)" from generic approach)
- Add person identifier filters/search just as we have on the case directory: name, dob, phone number, .....

**Comment by bernardsilenou** [comment]
@markusmann-vg 
- I create another issue for the filters #2730 
- We do not have final lab result for entity but we have for the sample always. I was thinking if we can just use this for now since that what we use for all other sections of the system.
