### ISSUE TITLE
Detailed export of event participants [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2702]
### Feature Description
- Use the same format as detailed export of cases.
- Include event meta data (this is the same for all persons), person variables + sample variables (+ tests results)
- Basic option (only variables show on the page) should be possible also
- It should be possible to export different event participants data and stack them. Thus it make sense to export the meta data also.
- add option to merge with case data ( (event participant + event meta data) left-joint with case data, keeping all event participant)

**Comment by bernardsilenou** [comment]
It should be possible to also export event participant from event directory also. Selecting a list of event to export should apply the same logic here and stack tables together.

**Comment by markusmann-vg** [comment]
**out of scope:**
add option to merge with case data ( (event participant + event meta data) left-joint with case data, keeping all event participant)

**Comment by sergiupacurariu** [comment]
@bernardsilenou Could you be more specific what event meta-data should include? Is event uuid enough or we need to add additional fields from events?

**Comment by bernardsilenou** [comment]
@sergiupacurariu 
event id, event status,   event  date (put begin and end dates in separate variables, NA for single day event), disease,  type of place, region, district , address, description

**Comment by bernardsilenou** [comment]
For person, you can use: uuid, name, tel, dob, sex, involvement description, National health id, Home address.region, Home address.district

**Comment by bernardsilenou** [comment]
Test summary:
- Add event participant id before person id on detailed export
- It will be nice to follow this column order to arrange columns on the exported data (mainly detailed export): event participant + event meta data, since the goad is on the event participant not the event. This will be the order: event participant id, person id, person identifiers, event identifiers
- On basic export: rename uuid to "EVENT PARTICIPANT ID", please do  the same on the web form

**Comment by raghupola-vg** [comment]
Event Participant Id is missing in the detailed Export. Please add this.
Also see if other requests from Bernard can be fulfilled easily.

**Comment by raghupola-vg** [comment]
Tested on today's build and everything works fine.
