### ISSUE TITLE
Data editing should be possible when converting contacts or event participants to case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2703]
### Problem Description
- DOB and sex are not editable
### Proposed Change

![image](https://user-images.githubusercontent.com/12996724/91223832-8173ac00-e721-11ea-8a24-3e62fb7258bf.png)

**Comment by bernardsilenou** [comment]
Disease should not be editable, others should be editable

**Comment by ChristopherRiedelSymeda** [comment]
@bernardsilenou Should this fields always be editable or only when the fields don't have values?

**Comment by bernardsilenou** [comment]
> @bernardsilenou Should this fields always be editable or only when the fields don't have values?

Only when it does not have values. Danke

**Comment by markusmann-vg** [comment]
- [ ] make the fields editable, when the value is NULL

**Comment by AndyBakcsy-she** [comment]
Verified on SORMAS Version: 1.48.0-SNAPSHOT
