### ISSUE TITLE
Add option to remove event from a case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2706]
### Problem Description
- To link a case from an event, we need to open the event and delete the event participant
### Proposed Change
- Just as we have for contacts, add the icon next to the event called "Remove Event" or just a delete icon
- Chen you click on the icon, there should be a pop up asking if user want to un-link the case as resulting from the event.
### Additional Information

![image](https://user-images.githubusercontent.com/12996724/91229834-c9e39780-e72a-11ea-99a4-affe4e282cab.png)

**Comment by VitaliHZI** [comment]
already implemented
