### ISSUE TITLE
App performance & progress dialog when server is offline [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#271]
The app is running extremely slow when the server is offline because it tries to reconnect whenever a list is loaded, resulting in a few seconds of inactivity (and a black screen in the process). Also, the progress dialog indicator doesn't spin in this case.

**Comment by MateStrysewskeSym** [comment]
- [ ] server connection has to be asynchronous
- [ ] handle possible problems when opening a case while the synchronization is still in process/find out whether this is actually a problem; possible solution could be to wait for the synchronization to finish before allowing users to enter an entity and to not try to reconnect to the server for a specified amount of time after a ConnectionException.

**Comment by MartinWahnschaffeSymeda** [comment]
See #689
