### ISSUE TITLE
HideForCountries annotations should actually check the country and not the language

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#2711]
### Problem Description
We're using the HideForCountries and HideForCountriesExcept annotations to automatically hide/show fields based on the country locale specified in the server properties. Right now, the code doesn't actually check the country part of the locale, but the language part. This means that it's currently impossible to e.g. show or hide fields for servers in Switzerland.

### Proposed Change
The logic that uses the annotations should primarily check the country part of the locale and only check the language part if the country part is not present.

**Comment by MateStrysewskeSym** [comment]
Should be reviewed by @MartinWahnschaffeSymeda

**Comment by MateStrysewskeSym** [comment]
- [ ] refactor isGermanServer() according to the changes already done in this issue

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Move logic to a dedicated method, e.g. isCountry(string locale, string countryCode)

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewske Please introduce a constant for "de" and "ch".
