### ISSUE TITLE
Correct translation of occupation categories and inclusion of new categories

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2718]

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewskeSym 
Please at your earliest availability, lets have a call to specify  this issue. Urgent attention is needed.
Danke

**Comment by markusmann-vg** [comment]
@GabrielePoggensee Please provide a complete list for the new occupation categories

**Comment by GabrielePoggensee** [comment]
The mapping of occupations is faulty, new variables need to be created and the data need to be migrated to the new variables

![image](https://user-images.githubusercontent.com/68693446/92923272-76b25a00-f437-11ea-81e4-40285a2b305e.png)

**Comment by MateStrysewske** [comment]
@GabrielePoggensee How are we supposed to properly migrate the data for this? "Child" for example has been a value since the inception of this field and we can't just change the name to "Civil servant" because it has already been used for children.

**Comment by GabrielePoggensee** [comment]
To explain my table.  It does not imply that existing variable should be renamed, in the last column the variables to be newly created are listed (heading new variables needed/change of mapping). 

Examples: 
"Beamter/civil servant" has be mapped to "child", which is not correct, therefore a new variable needs to be created to take care of the civil servants.
"Angestellter" has been mapped to "hunter", again a new variable "employee" needs to be created. 

"Selbstständiger/business man" has been mapped with butcher. Correctly it should have been mapped to "business man"

**Comment by MateStrysewske** [comment]
@GabrielePoggensee Understood! Are there more variables that we are supposed to add to this field?

**Comment by bernardsilenou** [comment]
@MateStrysewske Until now I do not still understand how we want to solve this issus. For a country that uses bothe French and German, the back end variable for child is mapped to child (in French) and soldier (in German), how will a simple migration help?

**Comment by bernardsilenou** [comment]
Maybe just adding the new occupation categories and correction the translations is wall we can do for now

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't have a clear solution for this, but I fear there's nothing we can really do about. We have to make sure that countries that used the correct translations aren't negatively impacted by this.

Countries that used wrong translations will probably have to use a mixture of a migration strategy and a manual correction.

**Comment by bernardsilenou** [comment]
@MateStrysewske OK, it is better to be late than never, so we add the new categories and correct all translations. I understand

**Comment by kwa20** [comment]
@bernardsilenou @MateStrysewske I came across this problem in the last few days and suggest that we pick it up again. I checked on Crowdin to see when the variables have been translated last and it apparently was 10 months ago. You'll know better than me but I think that the faulty translations existed right from the start when german health departments started using Sormas. This also means that people have been selecting options according to the faulty translations since then. 

We might be able to fix this problem by adding the variables that were incorrectly translated as proposed above, which would also mean that we make the already existing selection options available to german users in a proper way. We could then use a script on german servers to update the data base entries according to the initial faulty translations to conform to users selection intentions (e.g. CHILD -> CIVIL_SERVANT). Since german users never saw e.g. child as an option in the first place, they will then have this variable with the proper translation simply "added" as a selection option and no other international users will be impacted.

**Comment by bernardsilenou** [comment]
@kwa20 your solution is similar to what I also proposed. The additional challenge that I can see is that for servers having bilingual users like Swiss (French + German), we may additionally need the manual correction as @Maté suggested because the French translation is correct. 
@Candice-Louw  Please can you find out if the there is a possibility that some servers may have have had German and French/ English users using the system at the same time in Swiss?

**Comment by kwa20** [comment]
@bernardsilenou As far as I know, the swiss systems use switzerland specific occupation variables so this might actually not be that much of a problem. @Candice-Louw Please correct me if I'm mistaken.

**Comment by Candice-Louw** [comment]
@bernardsilenou @kwa20 - Correct - the Swiss servers have their own (independent) dataset (https://github.com/hzi-braunschweig/SORMAS-Project/issues/2978) for occupations as specified by the BAG.  These are only visible on Swiss servers and the German values are hidden (https://github.com/hzi-braunschweig/SORMAS-Project/issues/3703).  The translations are done seperately and theoretically, the CH servers shouldn't be affected by the changes made here.

**Comment by kwa20** [comment]
@MateStrysewske Do you know how this fix would be affected by #5015 ?

**Comment by MateStrysewske** [comment]
@kwa20 Not really - it's possible that this issue can be solved in an easier way with #5015 because it would allow German servers to define their own values and then properly map the existing ones, but I'm not sure.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by markusmann-vg** [comment]
Covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/5015
