### ISSUE TITLE
Translation is not shown for Confidential data 

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2722]
### Bug Description
When the Sormas language is selected to English, the "confidential data/personal data" is still displayed in german.

### Steps to Reproduce
1. Login to sormas application as SurvSup(surveillance supervisor) and change the language to English.
2. Select Cases/contacts and see if the personal data (first name, last name, etc) are shown as confidential data instead of the german word "Vertraulich"

### Expected Behavior
Confidential data has to be shown when the language is set to English.

### Screenshots
![Confidential data](https://user-images.githubusercontent.com/62763628/91413805-53db4f80-e854-11ea-9319-21a6289ffaad.PNG)

### System Details
* Device:
* SORMAS version: 1.47.0.snapshot
* Android version/Browser:

**Comment by MateStrysewske** [comment]
I think a reload of the page should get rid of that problem. Can you confirm this behaviour?

**Comment by bernardsilenou** [comment]
Has been implemented in recent versions
