### ISSUE TITLE
Add Task Creation on contact creation [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2724]
### Situation Description
Problem: For the cases, tasks are automatically created during import (one per case). For contacts, tasks are not created automatically.

### Feature Description
Requirement: For contact tracing, the automatic creation of tasks for the contacts is also necessary during import. Is there a possibility to execute the import in a way that one task is created per contact? Here it is even more important because more than 100 return travelers have to be imported as contacts every day and with the help of the tasks these can then be processed.

**Comment by markusmann-vg** [comment]
Current situation:
=> contact follow-up tasks are automatically created at 00:00:01 and not directly after import.

"If Switzerland would like to have a contact investigation task, this would be needed to be implemented"

**Comment by bernardsilenou** [comment]
I think what we need to do now is to:
- keep the contact followup task creation at 00:00:01
- Activate case/contact investigation task during importation. This should only happen for new entities, not when they are merged. 
- If report date of the entity is say >30 days in the past of the creation date, then we do not need to generate the automatic task.

**Comment by MateStrysewske** [comment]
Actual task:
- [ ] Create a contact investigation task when a new contact is saved and its report date is within the last 30 days

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOT
