### ISSUE TITLE
Add field: SwissCOVID-App (for Switzerland and COVID only) [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2725]
### Feature Description
At "Case Person" add two checkboxes:

- [ ] Has COVID app

- [ ] COVID code was generated and delivered

**Comment by ChristopherRiedel** [comment]
@markusmann-vg Should this only be displayed when the person is opened via the tab in the case?

**Comment by bernardsilenou** [comment]
@markusmann-vg I do not understand this design:
1. Should we not add these variables to the case, contact and event participant instead? How will having it on the person help us?
2. For contacts, we have the variable "contact identification source" (see fig) which we added for a similar goal. What about having this same variable for cases with the corresponding drop down categories. This way, it will be beneficial to all the sormas instances.
![image](https://user-images.githubusercontent.com/12996724/91992739-c5c00700-ed34-11ea-9c95-32c4c593c502.png)
