### ISSUE TITLE
Add number of event participants to event directory [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2728]
### Feature Description
Show another column in the table with the number of event participants. In the app it should be shown in the event details page.

**Comment by bernardsilenou** [comment]
@markusmann-vg  this is not already captured in #2701 ?

**Comment by vlad-ciucescu** [comment]
@bernardsilenou are you referring to this part?

> Add sum of records at the top of the directory

That refers to the total number of event participants in the event participants tab, and it will displayed above the table rows (Instead of "Persons involved").
The ticket here refers to the events directory, and implies that a we will display for each event (i.e. on each row) the number of participants for that event.

Please correct me if I am wrong.

**Comment by kwa20** [comment]
This is mentioned in the Release notes for 1.48.0 but is not visible on the test server (test1401.sormas-oegd.de).

**Comment by MateStrysewske** [comment]
@kwa20 Had a look at it on the server mentioned by you and it works absolutely fine. Note that the event participants list is only shown when opening an event and navigating to the respective tab.

**Comment by MateStrysewske** [comment]
@kwa20 Sorry, I misread the title of this issue. This is not part of the 1.48.0 release - what we've done there is to add the number of displayed event participants to the list of event participants inside an event. This issue right here is currently in development.

**Comment by AndyBakcsy-she** [comment]
Reopening issue on SORMAS Version: 1.49.0-SNAPSHOT as this created a new issue: 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2901

**Comment by bernardsilenou** [comment]
Summary of test:
sum should be reactive (rendering is missing and there may be some logic error)
Assume initial sum == n
When 1 event participant (ep) is deleted, sum does not change, remains n ( should be n-1)
when a new ep is added, sum  became n+1   (  should be n-1+1)
when all ep are deleted, sum is n ( should be 0)

**Comment by bernardsilenou** [comment]
sorting by participant count and source type retains error

**Comment by MateStrysewske** [comment]
@bernardsilenou I think the wrong numbers should go away if you reload the page, right?

**Comment by bernardsilenou** [comment]
I thought the same but is does not.
Have a look at this event:
server: https://test.sormas.netzlink.com/sormas-ui/#!events/?userFilterIncluded=true&dateFilterOption=DATE
event is:  VWAVHT-X3PSBD-6MR454-5LHRCJN4

**Comment by StefanKock** [comment]
Is the Sprint milestone correct? 1.48 was released two weeks ago.

**Comment by vlad-ciucescu** [comment]
@StefanKock the ticket was reopened afterwards. Should we update it to 1.50?

**Comment by StefanKock** [comment]
I think it should represent which (latest) release version this tickt is contributing to.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOT
