### ISSUE TITLE
Add variables on date of investigation and date of outcome to detailed export for cases [0.5]

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2733]
### Problem Description

There is no variable for date of investigation and date of outcome for the detailed case export. This makes it difficult for users to check the number of outcomes by recoveries and deaths that occurred within a particular time period. Same applies to the date of investigation

**Comment by bernardsilenou** [comment]
@Iheanacho2027 Can Nija dev team can handle this issue?

**Comment by kathsievers** [comment]
ISSUE TRACKER COMMENT

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.77.0-SNAPSHOT (8457345)
