### ISSUE TITLE
Updating the case symptoms based on visit symptoms (converting contact to case)

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2738]
### Feature Description
The symptom of a case = sum of baseline + followup +clinical course symptoms

### Proposed Change
- When contact become a case, set baseline symptoms = sum of visit symptoms done within the incubation period (d) of the disease (symptoms of followup visits with report date of visit within d days of report date of case)
- symptoms initially set to true always stay true

**Comment by bernardsilenou** [comment]
@xavier-calland

**Comment by xavier-calland** [comment]
@bernardsilenou can you tell me how I get the incubation period of a disease ?

Is it `Disease.defaultFollowUpDuration` (which is 14 for COVID) ?

**Comment by bernardsilenou** [comment]
@xavier-calland Yes please

**Comment by bernardsilenou** [comment]
@xavier-calland but is the followup duration specified in server configuration is not the disease default, then we use the number of days specified in server configuration:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_CUSTOMIZATION.md#disease-configuration

![image](https://user-images.githubusercontent.com/12996724/91995251-dd4cbf00-ed37-11ea-8e11-3ed573141d97.png)

**Comment by xavier-calland** [comment]
Currently, case symptoms are initialized using the last visit of the contact.

See `CaseController.getCaseCreateComponent`
https://github.com/hzi-braunschweig/SORMAS-Project/blob/2319d7c7c88b2e812acb77f4ade8904dd50d2e37/sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java#L315-L327

Can you confirm that this needs to change to use all visits during the incubation period?

**Comment by bernardsilenou** [comment]
@xavier-calland  I vote that we change it because the last visit can be 30 days before the date of report of the case. Our initial assumption for implementing it like this was that contacts were converted to cases on the day of the last visit, but this is not always true in real life.
My suggestion:
- initial case symptom == sum of all visit.symptoms where date of visit is in (case report data -/+ incubation period)
- Symptoms that occur long (< incubation period) before the report date of the case will not be counted as symptom of the case

**Comment by xavier-calland** [comment]
OK, thanks.
