### ISSUE TITLE
[CI error] cannot find symbol symbol: class PersonIndexDto

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#2739]
### Bug Description
Last commit on `develop` (47ab02a) fails with
```
[ERROR] /home/travis/build/hzi-braunschweig/SORMAS-Project
/sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionGrid.java:[31,35] cannot find symbol
  symbol:   class PersonIndexDto
  location: package de.symeda.sormas.api.person
```
See [travis](https://travis-ci.org/github/hzi-braunschweig/SORMAS-Project/builds/722018575#L10475)
@MateStrysewskeSym

**Comment by JonasCir** [comment]
@ChristopherRiedelSymeda maybe a fallout from #2736?

**Comment by JonasCir** [comment]
Identified: 44cdb6b421a90bfdae8f3a6d9879be965826cbdd removes `PersonIndexDto.java` in the merge

**Comment by JonasCir** [comment]
In cc39e6a1c1ecf425d966faafb107a87cdc7e37a5 `PersonIndexDto.java` was accidentally removed by merge

**Comment by ChristopherRiedelSymeda** [comment]
> In [cc39e6a](https://github.com/hzi-braunschweig/SORMAS-Project/commit/cc39e6a1c1ecf425d966faafb107a87cdc7e37a5) `PersonIndexDto.java` was accidentally removed by merge

Unfortunately this is not correct, PersonIndexDto was removed intentionally. I will remove the import and close this issue.

**Comment by JonasCir** [comment]
@ChristopherRiedelSymeda my bad then :)
