### ISSUE TITLE
Improve automatic auditing of JPA entities

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#274]
Improvements to #209:
  1. Delete `@AuditedCollection` and replace the usage by `@AuditedAttribute`.
  2. `EntityInspector`: Add `@ManyToMany` with `mappedBy` to ignored properties.
  3. Enhance unit test: Add test for `@OneToMany` without `mappedBy`.

**Comment by MateStrysewskeSym** [comment]
We've also fixed an issue where the auditor would automatically load all visits/contacts for contacts/visits from the database everytime it would access the entity by adding the AuditedIgnore annotation.

**Comment by StefanKock** [comment]
Fixed in v1.42.1
