### ISSUE TITLE
Add phone number and email to entity creation forms (case, contact, event participants) on web only [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2743]
### Proposed Change
- Add on forms for: case, contact, event participant
- Only on web app
![image](https://user-images.githubusercontent.com/12996724/91593938-58415e80-e961-11ea-8839-9b15b0e53269.png)

**Comment by john1496** [comment]
Helllo, I want to find out if the fields are going to be compulsory

**Comment by bernardsilenou** [comment]
@john1496 Not compulsory please, Thanks

**Comment by john1496** [comment]
@bernardsilenou Thanks, got it.

**Comment by AndyBakcsy-she** [comment]
Should these fields also have verifications in the backend?
From a QA point of view: the Phone Number Filed should only accept phone numbers and the Email field should only accept emails.

**Comment by MateStrysewske** [comment]
Valid point. I don't think it's a priority right now (given the huge list of priorities), but definitely something we should do in the future. We even have some kind of phone number validation already in the user form if I'm not mistaken.

**Comment by AndyBakcsy-she** [comment]
Linking new feature request for the validation of these fields: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2910

**Comment by bernardsilenou** [comment]
Test result:
Feature works fine for cases and contact creation but it is missing for event participants

**Comment by AndyBakcsy-she** [comment]
@bernardsilenou , isn't this the right place to add phone and email? in the Edit Event Participant field?
![image](https://user-images.githubusercontent.com/70562142/93765289-4cbe1c00-fc1d-11ea-8f7d-41b6d7e201ee.png)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOT

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she I think for now, this is not a big deal. The initial need for this request was that the users wanted to add these information in the initial dialog box (create new person) when creating an event participant. For now, they have to save and go to next tab that takes time.

In addition, we will soon have different tabs for event participant entity and the event participant person entity as we introduce followup and pseudonimization to event participants. At this point it will be valuable to have it at the initial creation.
