### ISSUE TITLE
Person address refinement - Phase 2 [2]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#2746]
### Situation Description
Continuation of #2562 
### Feature Description

- [x] Add addresses to person in the app
- [x] Synchronization (includes adjusting the user filters in the web backend)

**Comment by raghupola-vg** [comment]
For Mobile App, the person address types show the swiss only fields too. For swiss only fields refer comments under #2562)
 
![Address types for mobile app shows swiss types too](https://user-images.githubusercontent.com/62763628/93863438-c7417700-fcc3-11ea-9e24-58ca8749a809.png)

**Comment by raghupola-vg** [comment]
Tested on today's build on mobile app and the changes are visible.
