### ISSUE TITLE
Campaign diagram visualisation refinement [2]

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#2753]
Campaign diagram visualisation needs some improvement and cleanup

- [x]  add area condition - region of campaign form data should be within the area (each region can have an area but area is not linked to campaigndataform directly)
- [x] check data type of field --- do a count data type
- [x] extract caption directly from json with query 
- [x] when we have several stacks show stack on the diagram
- [x] outline (with a border line) empty diagrams

**Comment by BarnaBartha** [comment]
![image](https://user-images.githubusercontent.com/8166805/92222751-2459c200-eea8-11ea-8766-ec023e02f0f3.png)

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda What about having a table with certain indicators or the same numbers as on the figures at the top of the figures, just as we have on the contact dashboard? This may be an additional feature

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Yes, that's a good suggestion, but definitely a separate feature.

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha I'll look into the PR today. One request related to this. Please use the colors as we ae using them in the statistics (see StatisticsView:581):

		hcjs.append("colors: ['#FF0000','#6691C4','#ffba08','#519e8a','#ed254e','#39a0ed','#FF8C00','#344055','#D36135','#82d173'],");

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha Another request:

- [ ] When an area filter is active the regions list should only contain regions within that area.
