### ISSUE TITLE
Validate number of created/updated entities in saveWithSnapshot

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#276]
- [ ] Throw an exceptiton if entity is not properly updated or created. 
- [ ] Check if the reason is the changedate and customize the exception in this case

**Comment by MartinWahnschaffeSymeda** [comment]
Looks like we have already done this at some point and then dropped it again, because an entity that was not modified would also return 0 (see #1124). In addtion the Android ORM/database is very likely to be replaced soon, so it does not make sense to put work into this.
