### ISSUE TITLE
Detailed case export is not working

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#2763]
### Bug Description
Probably because of the facility type changes.

**Comment by AndyBakcsy-she** [comment]
Verified this issue on SORMAS Version: 1.48.0-SNAPSHOT
The Reports can be downloaded and opened. 
The Netzlink test server shows an error message but the file is still downloaded and can be opened. (based on Mate's comment, this is because some DB configurations on the Netzlink server)

**Comment by bernardsilenou** [comment]
@MateStrysewske  The bug is back, I tested on test.netzlink (1,49) and symeda (1,48,2) dev servers and it did not work. French users have the same issue.
![image](https://user-images.githubusercontent.com/12996724/93797274-4ee3a300-fc3c-11ea-802c-297855f7253a.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou Please do not reopen issues.
