### ISSUE TITLE
Similarity detection seems to be working highly inaccurately

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#2764]
There are way too many absolutely unrelated similarities coming up.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Please lets set the default value for similarityThreshold to be very high, event 0.8

**Comment by MateStrysewske** [comment]
@bernardsilenou 0.8 will result in no duplicates being detected. We've already reworked the system to be more restrictive.
