### ISSUE TITLE
Migrate healthFacility to facilityType = hospital on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2767]
### Bug Description
1. drop down of hospital name does not appear when facility type = hospital
2. when old case data is edited, bug at facility

### Steps to Reproduce
1. Create a case on mobile app
2. Edit an old case on mobile app

### Expected Behavior
- Migrate old data accordingly
- Show facility names on drop-down

### System Details
* Device: samsung
* SORMAS version:1,47
* Android version/Browser: 9

**Comment by bernardsilenou** [comment]
similar to #2762

**Comment by MateStrysewske** [comment]
I don't know what the problem is here. The hospital name (or, rather, facility name) only appears when "Other facility" is chosen in the "Facility" dropdown, as always.
