### ISSUE TITLE
Changes to facility management when creating a case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2771]
### Steps to Reproduce
1. Creat a case at home,
2. when place of stay = home is latter changed to facility, the former data are stilled referenced by the entity and prevent the user from making the change. The facility name previously registers is copied to the place description when the place of stay is home

### Expected Behavior
- Facility captions in mobile app do not match captions in web, eg facility name and description (mobile) = place description (web), The same captions should be used
- When a case is created at home and later changed to facility, system should ask is user want to transfer the case or edit the data + necessary steps to be taken based on the option chosen.
-Data referenced when place of stay == home should not be referenced by data registered when place of stay == facility ie
description for other facility != description for home

- Cases with place of stay ==  home cannot be created on web app. After activating place type == "facility", you can then create a case at home. Works fine on mobile app

### System Details
* Device:
* SORMAS version:1,47
* Android version/Browser:

### Additional Information
![image](https://user-images.githubusercontent.com/12996724/91892523-1717ba00-ec93-11ea-81c4-54eeff5eb752.png)

**Comment by bernardsilenou** [comment]
#similar to #2762

**Comment by MateStrysewske** [comment]
It doesn't make sense to "transfer" a case from home to a facility because there is no point in creating a previous hospitalization when the case was at home (as the case was not hospitalized).

**Comment by MateStrysewske** [comment]
The captions of the mobile and web app are the same. Whether it's called "Place description" or "Facility name & description" depends on what has been chosen in the dropdowns before.

**Comment by MateStrysewske** [comment]
The problem with case creation is fixed in #2762. Everything else works fine for me.

**Comment by bernardsilenou** [comment]
> It doesn't make sense to "transfer" a case from home to a facility because there is no point in creating a previous hospitalization when the case was at home (as the case was not hospitalized).

OK. Only data correction should be possible in this case

**Comment by AndyBakcsy-she** [comment]
Verified on SORMAS Version: 1.48.0-SNAPSHOT
