### ISSUE TITLE
Event meta data should not be confidential to users not have the right to edit the event

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2773]
### Problem Description
- Users should be able to see the complete meta data for events not in their jurisdiction

### Proposed Change
- Make event meta data read only but not confidential

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg  Any objection to this issue?

**Comment by MateStrysewske** [comment]
What exactly do you mean with meta data? Which data are you referring to?

**Comment by tabotkevin** [comment]
@bernardsilenou It will be nice if screenshots are provided where ever possible as it will really visually help to understand 
 and narrow down the issue.

**Comment by bernardsilenou** [comment]
Sorry guys, I was in a hast when creating this issue. 
When a surveillance supervisor for example log in the system, they should be able to see data on all events in the system but they should not be able to edit event entity (meta data) for events that they did not create or not in their region.
Here is a screenshot when for a surveillance supervisor:

![image](https://user-images.githubusercontent.com/12996724/92009242-84395700-ed48-11ea-8fc2-d58b7b87f0b7.png)

![image](https://user-images.githubusercontent.com/12996724/92010328-f8c0c580-ed49-11ea-8ec6-06d219f321d6.png)

For even participant, the current implantation is fine

**Comment by bernardsilenou** [comment]
@markusmann-vg Please can you check if this is in conflict with the data security laws?
The reason for not making this confidential is that when a surveillance officer want to link a case to an event, they are presented with many event having confidential variables for them to choose. How can they choose among what they cant even see. 
For variables like house number, community, street number, I think we should always keep them confidential.

**Comment by bernardsilenou** [comment]
![image](https://user-images.githubusercontent.com/12996724/92011452-5d305480-ed4b-11ea-8e98-e09baddb47ee.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske Understood. This means users will not be able to link cases to events outside their jurisdiction except the event uuid is somehow communicated to them, right?

**Comment by MateStrysewske** [comment]
Exactly.
