### ISSUE TITLE
Creation a new gathering for a case/ contact on mobile app clone the same entity

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2774]
### Bug Description
- When creating a new gathering, dialog box does not closes when you click on ok. Each activation of the "ok" icon on dialog box clone the same gathering entity.

### Steps to Reproduce
1. Create a new gathering on mobile app
2.  have a look at OK icon and attending gathering icon

### Expected Behavior
- The issue  here is that the OK icon not working well, even though many versions of the same entity appear on the mobile interface during creation, only one version is saved and sync with the db.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/91898631-50085c80-ec9c-11ea-95aa-ecd3b99319e8.png)

Web version does not look good also
![image](https://user-images.githubusercontent.com/12996724/91900601-37e60c80-ec9f-11ea-95e1-60ff02ad9474.png)

### System Details
* Device:
* SORMAS version: 1,47
* Android version/Browser:

**Comment by MateStrysewske** [comment]
There's no problem with the web version; the user is simply not allowed to change that field as long as there is at least one entry in the list (to avoid unintended data loss).

**Comment by bernardsilenou** [comment]
@MateStrysewske Understood. Thus only mobile has an issue
