### ISSUE TITLE
Optimize person similarity/duplication check [2]

### ISSUE THREAD

**Issue by xavier-calland** [hzi-braunschweig/SORMAS-Project#2782]
`CaseImportFacadeEjb.isPersonSimilarToExisting` is loading all `PersonNameDto` to check is there is at least one person found.

https://github.com/hzi-braunschweig/SORMAS-Project/blob/8111953ace9f25c6c76d82c946f03982e682d83d/sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java#L657

(Since https://github.com/hzi-braunschweig/SORMAS-Project/commit/6d6c6ca3cb1b54c91459366d9b690d5dc0303fbb#diff-9bff4212db31823712b223ec3668854aR657 there's no use of `PersonNameDto` fields.)

Using methods in Service that return boolean can improve memory usage and performance.

**Comment by bernardsilenou** [comment]
follow up from #2539

**Comment by markusmann-vg** [comment]
included in here:
- [ ] check wether the query itself causes performance problems

**Comment by MartinWahnschaffeSymeda** [comment]
Copied from #2839 
> changes:
> 
>     * the existing 3 similarity queries were transformed into a single query
> 
>     * a trigram index on person was added
> 
>     * the similarity function was changed to "%" operator (the tests between these 2 approaches returned the same results). The reason for this switch is that the operator "%" works better with the above index.
> 
>     * similarity check improvement is 9 - 10x
> 
>     * overall import process 3 - 4x
