### ISSUE TITLE
Page load time is longer on latest version and a loading screen is displayed for a while.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2784]
### Bug Description
The loading time between entering the credentials and displaying the dashboard is longer when logged in as any of the users.
A white screen with loading symbol is displayed for a while. At times it takes atleast 8 to 10 seconds for the page to load completely.

### Steps to Reproduce
1. Login to Test environment https://test.sormas.netzlink.com/ as one of the users and see the time taken to display the dashboard
2. Logout and try logging in as an other different from the one used in step 1 and observe the delay.

### Expected Behavior
The login time should not be too long and should be responded quickly.
 
### Screenshots
![Longer Loading time](https://user-images.githubusercontent.com/62763628/91994304-c063bc00-ed36-11ea-8149-6f0e84249360.png)

### System Details
* Device:
* SORMAS version: 1.48.0
* Android version/Browser: Chrome version 85.0

**Comment by bernardsilenou** [comment]
No longer an issue
