### ISSUE TITLE
Filter case directory by case uuid does not work

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2787]
### Steps to Reproduce
1. 
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/92007212-ee9cc800-ed45-11ea-99e5-c44de77db843.png)

### System Details
* Device:1,47
* SORMAS version:
* Android version/Browser:

**Comment by Iheanacho2027** [comment]
Yeah this was a problem along with search by EPID number in 1.46.0, I checked 1.47.0 but it all works fine.

**Comment by danRosca** [comment]
I looked into this issue but I was not able to reproduce it

**Comment by bernardsilenou** [comment]
tested on nightly build all was OK
