### ISSUE TITLE
Error on detailed view of case directory (Version 1.47.0)

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2790]
### Bug Description
An error exists when a user clicks on detailed view of the case directory

![image](https://user-images.githubusercontent.com/50739609/92044824-f4f76800-ed76-11ea-8c25-385d6c31d114.png)

**Comment by MateStrysewske** [comment]
@Iheanacho2027 Please check the repository for similar issues (use the search functionality) before opening new ones. This has already been reported twice and was fixed in the hotfix yesterday.
