### ISSUE TITLE
Export diagrams to CSV

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#2794]
### Situation Description
Diagrams on the dashboards currently can be exported to multiple image formats, but not to CSV.

### Feature Description
Allow users to export diagrams to CSV. First step is to find out whether this can be done easily by simply enabling some properties in the HighCharts code. If that's not the case, some design thinking might be necessary.

**Comment by MartinWahnschaffeSymeda** [comment]
Turns out, we only have to 

- [ ] enable the export-data module of highcharts.

Since I had to add the js file anyway, I took the opportunity to 

- [ ] update to Highcharts 8.2.0 and jQuery v3.5.1

I have tested this on the dashboard and in the statistics and it seems to work fine.

**Comment by raghupola-vg** [comment]
Tested and works fine.
