### ISSUE TITLE
Date validation fails when creating a visit for a contact with a date earlier than the report date

### ISSUE THREAD

**Issue by xavier-calland** [hzi-braunschweig/SORMAS-Project#2797]
### Bug Description

Date validation fails when creating a visit for a contact with a date earlier than the report date.

### Steps to Reproduce
1. Create a contact (report date is today)
2. Add a visit with an earlier date
3. Click "Save" button
→ Error: An error has occurred The error was automatically reported to the support.

### Expected Behavior

Save form without error

### System Details
* Device: Browser
* SORMAS version: 1.47
* Browser: any

### Additional Information

Bug from https://github.com/hzi-braunschweig/SORMAS-Project/commit/fef08a219560d608fbd996bc011a4a4400bb84e4#diff-50789c99ceb572437365f69e8701a0c7R151

use of `caze` variable even while creating a visit for a contact.

**Comment by xavier-calland** [comment]
@MateStrysewske PR coming soon.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.48.0-SNAPSHOT
This functionality works as expected.
