### ISSUE TITLE
Refactor email/sms notification system to work with future configurable user roles [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#2805]
### Feature Description
We want to allow admins to configure user roles according to their needs #898

### Problem Description
Some user roles are still used to decide which users are supposed to receive email & sms notifications, e.g. when the classification of a case is changed.

### Proposed Change

- [ ] Add a new enum to contain all types of notifications, as listed below
- [ ] For each user role define which email notifications are active by default (add to the UserRole enum, later this will be part of the configuration).
- [ ] For each user role define which sms notifications are active by default (add to the UserRole enum, later this will be part of the configuration).

For all usages for MessagingService.sendMessage, replace the logic that defines the recipients with the logic described for the message subjects (MessageSubject enum):

- [ ] CASE_CLASSIFICATION_CHANGED
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR, CONTACT_SUPERVISOR
  User is directly associated to the region of the case ~~or is responsible for the case~~
- [ ] CASE_UNSPECIFIED_DISEASE_CHANGED (rename DISEASE_CHANGED)
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR, CONTACT_SUPERVISOR
  User is directly associated to the region of the case ~~or is responsible for the case~~
- [ ] CASE_INVESTIGATION_DONE
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR
  User is directly associated to the region of the case ~~or is responsible for the case~~
- [ ] CASE_LAB_RESULT_ARRIVED (split the existing LAB_RESULT_ARRIVED. Unify with LAB_RESULT_SPECIFIED)
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR
  User is directly associated to the region of the case ~~or is responsible for the case~~
- [ ] CONTACT_LAB_RESULT_ARRIVED
  Roles: SURVEILLANCE_SUPERVISOR, CONTACT_SUPERVISOR
  User is directly associated to the region of the contact ~~or is responsible for the contact~~
- [ ] EVENT_PARTICIPANT_LAB_RESULT_ARRIVED
  Roles: EVENT_OFFICER
  User is directly associated to the region of the event ~~or is responsible for the event~~
- [ ] LAB_SAMPLE_SHIPPED
  Roles: LAB_USER, EXTERNAL_LAB_USER
  User is directly associated to the laboratory of the sample
- [ ] TASK_START
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR, CONTACT_SUPERVISOR, EVENT_OFFICER, POE_SUPERVISOR, NATIONAL_USER
  Task assignee
- [ ] TASK_DUE
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR, CONTACT_SUPERVISOR, EVENT_OFFICER, POE_SUPERVISOR, NATIONAL_USER
  Task assignee
- [ ] VISIT_COMPLETED
  Roles: SURVEILLANCE_SUPERVISOR, CASE_SUPERVISOR, CONTACT_SUPERVISOR
  User is directly associated to the region of the contact ~~or is responsible for the contact~~
- [ ] CONTACT_SYMPTOMATIC
  Roles: SURVEILLANCE_SUPERVISOR, CONTACT_SUPERVISOR
  User is directly associated to the region of the contact ~~or is responsible for the contact~~
- [x] EVENT_PARTICIPANT_CASE_CLASSIFICATION_CONFIRMED -> Already depends on responsible user of event

### Notes

The definitions above are based on the existing code. It's likely that some of this will be changed in the near future.

Later each user should be allowed to decide which notifications to receive and how (email, UI, SMS).

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  Very good point!
Can we also extend this to the cases, contacts and event participants? notification for mainly their lab results?

**Comment by MartinWahnschaffeSymeda** [comment]
Yes, but let's move this to a separate issue do be done after this one. THis one will only put existing functionality into a proper extendable implementation.

**Comment by vidi42** [comment]
To test email sending we can use https://ethereal.email/

**Comment by MartinWahnschaffe** [comment]
* New types that also have to be handled accordingly EVENT_PARTICIPANT_CASE_CLASSIFICATION_CONFIRMED, EVENT_PARTICIPANT_RELATED_TO_OTHER_EVENTS - give those to the three supervisor roles and the EVENT_OFFICER
* EVENT_GROUP_CREATED, EVENT_ADDED_TO_EVENT_GROUP, EVENT_REMOVED_FROM_EVENT_GROUP. Give those to the EVENT_OFFICER
* If possible keep the existing MessageSubject and rename it to NotitificationType

**Comment by abrudanancuta** [comment]
A separated ticket was created for the case EVENT_PARTICIPANT_LAB_RESULT_ARRIVED = 8445
