### ISSUE TITLE
[SORMAS2SurvNet] Add new fields from SurvNet Interface to SORMAS

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2807]
In the SORMAS Mapping table there are a lot of fields, that are currently missing in SORMAS.
To be able to send and receive a full dataset we need to add the missing fields to the cases and contacts to the SORMAS UI, the SORMAS app and the SurvNet Interface.

[aenderungen.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5173563/aenderungen.docx)
[contact_missing_fields.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5173564/contact_missing_fields.docx)
[person_missing_Fields.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5173565/person_missing_Fields.docx)

https://jira.vitagroup.ag/browse/SOR-272

**Comment by markusmann-vg** [comment]
Exposition. FromDate | will be added in  SORMAS by the applications team
Exposition. UntilDate | will be added in  SORMAS by the applications team

**Comment by bernardsilenou** [comment]
> Exposition. FromDate | will be added in SORMAS by the applications team
> Exposition. UntilDate | will be added in SORMAS by the applications team

- These dates are the once we would add on the newly to be  introduced exposure entity ?
- If there are may exposures leading to multiple dates, then we can just use min (Exposition. FromDate )  and max ( Exposition. UntilDate ) of the dates among all the exposures to push to survenet

**Comment by FredrikSchaeferVitagroup** [comment]
Does that relate to #3312?

**Comment by markusmann-vg** [comment]
yes, will be treated by https://github.com/hzi-braunschweig/SORMAS-Project/issues/3312
