### ISSUE TITLE
Import > Contact converted to Case: incorrect classification/labelling

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2811]
### Problem Description
Import problem:

1. Although the ContactStatus was set to CONVERTED in the import file for the contacts which are also a case, the contact entries are displayed as deleted and not converted.  However, for all these cases the system has placed the following note in the Tracking Status Comment field:
followUpComment: "[System] Tracking was automatically aborted because the contact was converted to a case".

2. No reference case can be specified during import, which then causes ContactService to automatically set the contact to Dropped.

### Proposed Change
1. If followUpComment says that the contact has been converted into a case, change the contact status (contactStatus) to "converted into case".

On the one hand this is otherwise incorrectly recorded in Sormas and on the other hand it is important for the evaluations/statistics.

2. There is currently no possibility to specify a case UUID to which the contact was converted (this will have to be made possible)
Or:
Remove the need that a converted contact must have a case.

**Comment by MateStrysewske** [comment]
@Candice-Louw Is this still an issue with the current version? There's an issue that sounds very similar to me that was recently taken care of: #2641

**Comment by Candice-Louw** [comment]
No feedback on this yet.

**Comment by MateStrysewske** [comment]
Just tested this on my system and it's working.
