### ISSUE TITLE
Saving editied case information when place of stay is home results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2813]
### Bug Description

After creating and saving a case, where home has been selected for place of stay, further editing of case information and subsequent saving results in an error. You are asked to check facility type. Saving will only work when place of stay selection and place describtion have been reedited.

### Steps to Reproduce

1.Create a case with place of stay being home.
2.When redirected to the case information, feel free to edit any editional fields except place of stay and place description.
3.Try saving. When error occurred, reedit place of stay and place description and save again.

### Expected Behaviour

When place of stay and place description have been entered in initial case creation window, reediting should not be necessary in case information for then being able to save.

### System Details
* Device:
* SORMAS version: 1.47.1
* Android version/Browser: Chrome

**Comment by bernardsilenou** [comment]
![image](https://user-images.githubusercontent.com/12996724/92247293-4e6eac80-eec7-11ea-8cc4-6aa5e595b933.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske I created this case in figure above as an admin+national user role and  automatic task is cloned. Similar to #2635 

- Add "HOME"  as value of facilityType in data dictionary
- set facilityType = "HOME" when place of stay = home ( case creation + import)
OR
- make facilityType non-required when place of stay = home

**Comment by ChristopherRiedel** [comment]
@kwa20 and @bernardsilenou are you sure you are using 1.47.1? This is a known bug in 1.47.0 (#2762) but it should be fixed in 1.47.1

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.48.0-SNAPSHOT
Creating a Case with Facility type home or facility is working as expected. 
Changing the facility type also works.
