### ISSUE TITLE
Contacts > Spelling correction on new contact creation form [0]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2814]
### Feature Description
Correction of EN language on create new contact form (this can't be done through CrowdIn).

ContactProximity.MEDICAL_DISTANT 
and
ContactProximity.MEDICAL_SAFE
in
sormas-api/src/main/resources/enum.properties

### Problem Description
Contacts > Create new Contact > Choose "disease of source case" as COVID-19 > Type of Contact selection appears:
Last two options: "Medical personnel at save proximity..." and "Medical personnel at save proximity..." 

### Proposed Change
Second last and last options should read:
"Medical personnel at **safe** proximity..."

### Additional Information
<img width="415" alt="20200905SaveProximity" src="https://user-images.githubusercontent.com/65529128/92303084-fc369580-ef71-11ea-95e0-58f00116c71c.png">

**Comment by markusmann-vg** [comment]
Cannot be done in Crowdin

**Comment by StefanKock** [comment]
> Cannot be done in Crowdin but should be

The default language cannot be altered via crowdin, therefore a valid ticket.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(5e5b8ae).
