### ISSUE TITLE
Dashboard > New Events > Add missing "Cluster" and "Screening" sub-sections

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2815]
### Feature Description
After implementation of https://github.com/hzi-braunschweig/SORMAS-Project/issues/2391, the dashboard is displaying only partial Event information.

Feature Request:
Dashboard > New Events section > Addition of missing "Cluster" and "Screening" sub-elements (Event types).

### Problem Description
When a new Event, of type 'cluster' or 'screening' is created, it is not visible on the Dashboard summary under the "New Events" section (no sub-section created for it).

### Proposed Change
Include "Cluster" and "Screening" on the Dashboard.

Cluster: Red (same red as for event)
Screening: Orange (same orange as for signal)

### Additional Information
<img width="215" alt="20200905EventsElements" src="https://user-images.githubusercontent.com/65529128/92303436-102fc680-ef75-11ea-81d4-fc20c31ad6ee.png">

**Comment by bernardsilenou** [comment]
Better to be implemented together and considering comments mentioned in  #3004

**Comment by bernardsilenou** [comment]
@Candice-Louw was closing this ticket a mistake?
What you mentioned here is not in #3004, it will be good to copy your description over to the other issue?

**Comment by bernardsilenou** [comment]
I would combine this ticket with #3004 and summarize all the changes there.
