### ISSUE TITLE
Case Classification filter in case directory doesn't match with the country specific classifications

### ISSUE THREAD

**Issue by gtmdipen** [hzi-braunschweig/SORMAS-Project#2816]
### filter case classification
<img width="1287" alt="Screen Shot 2020-09-05 at 21 02 49" src="https://user-images.githubusercontent.com/33200588/92308189-bacad800-efbb-11ea-8c68-612ca3ba5e07.png">

**Comment by bernardsilenou** [comment]
@gtmdipen  Can you pleas explain following the instructions?

**Comment by MateStrysewske** [comment]
@gtmdipen I don't really know what your request is about. Please choose a more descriptive title and add more context to your entry post. As Bernard already said, please use the template that is provided to you when creating an issue.

**Comment by gtmdipen** [comment]
As per the posted screenshot : The cases are classified under the  **Confirmed case with no symptoms.**  However in the filter there is no option for Confirmed case with no symptoms. 
Therefore, the cases are not visible in the filter. 

I am using version 1.47.1

**Comment by MateStrysewske** [comment]
@gtmdipen I see, that makes sense!

**Comment by gtmdipen** [comment]
Using here in Nepal

**Comment by MateStrysewske** [comment]
Was the server set up as a German server at some point? The case classification "Confirmed case with no symptoms" should not appear for you, so the dropdown is fine. I'm wondering why you have cases in your system that are classified like this.

**Comment by gtmdipen** [comment]
Yes. This was setup as a german server. later it was updated to Nepalese.

**Comment by MateStrysewske** [comment]
@gtmdipen Alright, then that's the problem here and everything works as intended.
