### ISSUE TITLE
Laboratories configuration missing in configurations menu of 1.47.1

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2817]
### Bug Description
The configuration for laboratories is missing on the configurations menu for 1.47.1 as available on the symeda server. This means new laboratories cannot be created on version 1.47.1
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@Iheanacho2027  See figure below:
![image](https://user-images.githubusercontent.com/12996724/92327114-b8b65700-f057-11ea-88c6-ed2f9aab2869.png)

**Comment by Iheanacho2027** [comment]
Thanks alot
