### ISSUE TITLE
OTHER_FACILITY reference not working on import template (1.47.1)

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2818]
### Bug Description
On inclusion of "HOSPITAL" as facility type, the system on import rejects "OTHER_FACILITY" as a health facility
### Steps to Reproduce
1.On the import template, type "HOSPITAL" under the column variable "facilityType", 
2. Type "OTHER_FACILITY" under the column variable "healthfacility"

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewske** [comment]
OTHER_FACILITY is not a valid facility type. You have to choose one of the facility types specified in the data dictionary. OTHER_FACILITY is supposed to go into the facility column if the facility in question does not exist in the database.

**Comment by Iheanacho2027** [comment]
Pls this is not invalid @MateStrysewske. As explained above, i included "HOSPITAL" as facilitytype and "OTHER_FACILITY" as healthfacility then put the name of the facility in the healthfacilitydetails column. I could share with you the template if you wish. Kindly reopen the ticket

**Comment by MateStrysewske** [comment]
@Iheanacho2027 You had stated before that you had used "OTHER_FACILITY" as facilitytype, which is why I closed the issue. Your new description makes more sense.
