### ISSUE TITLE
Cases > "Place of stay" not indicated or validated as mandatory when creating new case with case origin as "point of entry"

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2819]
### Bug Description
When creating a new case, the user does not have to specify "Place of Stay" (not indicated or validated as a mandatory field) when creating a Case with "Case Origin" set as "Point of Entry".

This Case can be saved/created without the "Place of Stay" information.  This results in the creation of a Case that is missing important tabs and features including "Therapy", "Contacts", "Hospitalization" ability to add Samples and ability to edit case information...

### Steps to Reproduce
1. Create new Case
2. Set "Case Origin" to "Point of Entry"
3. Do not select any value at "Place of Stay"
4. Fill out other mandatory fields and Save/create Case
5. Case is created with missing information and functionalities

### Expected Behavior
"Place of Stay" selection should be mandatory (as it is with "In-country" case origin).  Validation should not allow user to create Case without filling this in (red star added to field name to indicate it as mandatory too, please?).

### Screenshots
<img width="733" alt="20200906CaseErrors1" src="https://user-images.githubusercontent.com/65529128/92314720-e8277e00-efdb-11ea-9566-496bf5f1b44c.PNG">
<img width="920" alt="20200906CaseErrors2" src="https://user-images.githubusercontent.com/65529128/92314721-eb226e80-efdb-11ea-89b1-cfdeea760a71.PNG">

### System Details
* SORMAS version: 1.47.1 - Web
* Serv: https://test1401.sormas-oegd.de/sormas-ui/

**Comment by bernardsilenou** [comment]
@Candice-Louw The reason is because POE cases do not have a "place of stay" by design since they are often recorded at airport, sea and land boarders. After creating a POE case, you have to move (transfer) them to a district.

**Comment by Candice-Louw** [comment]
My mistake. Thank you!
For anyone else who will come across this issue - "Refer Case to ..."can be used to convert the case.

**Comment by kwa20** [comment]
@bernardsilenou when point of entry is selected in case origin, the possibility to select facility or home as the place of stay should be completely disabled. Even though the selection is grey, respective fields can still be selected and make the corresponding entry fields appear. This unfortunately becomes problematic when health departments mistakingly create cases that way.

**Comment by bernardsilenou** [comment]
@kwa20 Thanks for the comment. I will create another issue because there are many changes to be done.
- Maybe we need to allow POE cases to have a "place of stay" because some POE may have a health facility or if a case is identified at an POE and later go home, it may be good to record all this data in one step.

**Comment by bernardsilenou** [comment]
continue to #2897
