### ISSUE TITLE
HF informant cant edit name of case person after case creation (Mobile App 1.47.1 )

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2820]
### Bug Description
After a case is created by a HF informant, He/She isnt allowed to edit the name of the case person as shown below

### Steps to Reproduce
1. Create a case on the HF informant user account by entering all details on case and person information
2. Try editing first name and Last name

### Screenshots
![image](https://user-images.githubusercontent.com/50739609/92322462-3adb5700-f029-11ea-97b8-20ae812a89ca.png)

### System Details
* Device: 
* SORMAS version: 1.47.1
* Android version/Browser:

**Comment by MateStrysewske** [comment]
Same problem appears e.g. for the address and other fields that should be editable.

**Comment by MateStrysewske** [comment]
Can't reproduce this; If I create a case as a hospital informant, I can edit the names as expected. Can you send me screenshots of the case information page for this example case so I can try to track down the problem?

**Comment by Iheanacho2027** [comment]
From the image below, its greyed out 
![image](https://user-images.githubusercontent.com/50739609/92394640-cc29f680-f119-11ea-92b4-59420873d4c7.png)

**Comment by MateStrysewske** [comment]
@Iheanacho2027 I need the case information page please, not the person information; especially the jurisdiction part.

**Comment by MateStrysewske** [comment]
@Iheanacho2027 The reason for this behaviour is that on the demo server, someone edited the user rights for informants but did not give them the right to see and edit personal and sensitive data in their own jurisdiction.
