### ISSUE TITLE
HF informant are allowed to assign EPID numbers and classify cases on 1.47.1

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2821]
@bernardsilenou I would like to know if it's an error or an agreed decision to allow HF informants to assign EPID numbers and classify cases on 1.47.1, as shown in the image below

![image](https://user-images.githubusercontent.com/50739609/92322591-10d66480-f02a-11ea-8860-8ede29a142d3.png)

-->

**Comment by bernardsilenou** [comment]
@Iheanacho2027 
- HI should not be able to assign EPID numbers
- Concerning classification,  I think we have always allowed HI to classify cases. My suggestions is that, HI should be able to classify as "suspected" and probable but not as confirmed. How is it done in Nigeria?

**Comment by Iheanacho2027** [comment]
I agree with your suggestions on classification @bernardsilenou

**Comment by MateStrysewske** [comment]
@bernardsilenou I'm pretty sure that HF weren't allowed to classify cases. This bug is probably caused by the recent pseudonymization additions.

**Comment by MateStrysewske** [comment]
@Iheanacho2027 Can't reproduce this problem, on my local system, as a hospital informant, I'm not allowed to edit epid numbers and case classifications as expected. Are you sure that you're logged in as a hospital informant?

**Comment by Iheanacho2027** [comment]
I am logged in as a hospital informant on symeda 1.47.1
![image](https://user-images.githubusercontent.com/50739609/92394335-46a64680-f119-11ea-87fe-ef97e02f9b40.png)

**Comment by MateStrysewske** [comment]
@Iheanacho2027 Okay, I'll try to reproduce it with this user on my system as well. I'll have to change the password for that however.

**Comment by MateStrysewske** [comment]
@Iheanacho2027 The reason for this behaviour is that on the demo server, someone edited the user rights for informants in the database and gave them the user rights to classify cases and change epid numbers.
