### ISSUE TITLE
HF informant cant edit a case after sychronization occurs and case data is uploaded to server (Mobile app 1.47.1)

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2822]
After a HF informant enters a case and synchronizes successfully, He/She can no longer edit or make any input to that case i.e the person symbolizing edit is no longer active. I would like to know if this is deliberate or a bug @bernardsilenou 
-->

**Comment by bernardsilenou** [comment]
The same cause root cause as in #2823
