### ISSUE TITLE
HF informant cant enter information on Place of residence and other biodata info

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2823]
### Bug Description
The variables on place of residence information and biodata information like day of birth (DD), Nickname, Mother's maiden name, mother's name, father's name, phone number are all greyed out. Probably this is related to #2351 

![image](https://user-images.githubusercontent.com/50739609/92323185-8cd2ab80-f02e-11ea-8695-fdc2e83c359a.png)

![image](https://user-images.githubusercontent.com/50739609/92323198-a4119900-f02e-11ea-899b-1a6f380123e7.png)

### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by bernardsilenou** [comment]
@Iheanacho2027 Pls can you confirm if the district of the informant is the same as that of the case?

**Comment by Iheanacho2027** [comment]
Yes it is, the case was created by the HF informant

**Comment by Iheanacho2027** [comment]
You can test and see

**Comment by bernardsilenou** [comment]
@Iheanacho2027  OK, this means is a bug. Thanks

**Comment by MateStrysewske** [comment]
Same as #2820.
