### ISSUE TITLE
Case contacts sub-menu shows on HF Informant user account (1.47.1)

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2824]
### Bug Description
HF  Informants are allowed to list contacts on the 1.47.1. This shouldnt be as they do not partake in contact tracing
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by MateStrysewske** [comment]
Once again, I can't reproduce this problem. Are you sure you're logged in as hospital informant?

**Comment by Iheanacho2027** [comment]
![image](https://user-images.githubusercontent.com/50739609/92398513-9a685e00-f120-11ea-98d3-9d2aef7fb2e4.png)

**Comment by MateStrysewske** [comment]
@Iheanacho2027 The reason for this behaviour is that on the demo server, someone edited the user rights for informants in the database and gave them the user rights to view and edit contacts.
