### ISSUE TITLE
Sample Information Sub-menu should exist in case contacts on mobile app just as it is on the web

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2826]
### Situation Description
There is no means for surveillance officer to enter samples for case contacts on the mobile app just the way it is on the web app
### Feature Description
There should be a functionality for entering samples of case contacts on the mobile app just as there is on the web app

**Comment by MateStrysewske** [comment]
Duplicate of #2133. @Iheanacho2027 Please search the already existing issues before opening new ones.
