### ISSUE TITLE
Cases and contacts not in user's jurisdiction or not related to the user shows up in the case and contact directory (mobile app)

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#2827]
### Bug Description
@bernardsilenou Several cases and contacts not related to a user or not from a user's jurisdiction shows up in the user's account as confidential. Users should only see cases which are within their jurisdiction.

![image](https://user-images.githubusercontent.com/50739609/92338940-6868e480-f0ab-11ea-87c3-dfaa3deed1d8.png)

### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version: 1.47.1
* Android version/Browser:

**Comment by MateStrysewske** [comment]
Are the cases linked to contacts or event participants that the user is allowed to see?

**Comment by Iheanacho2027** [comment]
No they aren't

**Comment by MateStrysewske** [comment]
Have the cases been shared with the whole country (there is a checkbox in the case data form on the web UI that allows this)?

**Comment by Iheanacho2027** [comment]
Oh i see. Merci @MateStrysewske
