### ISSUE TITLE
Add multiple email addresses to person entity (case, contact, event )

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2828]
### Situation Description
Similar to #2744 , with more external applications connecting to SORMAS (PIA specifically), it becomes more important to be able to record multiple email addresses in a structured way.

### Feature Description
- Add 2 more fields to capture other email addresses.
- Show these fields only after selecting "multiple email addresses".
- Migration: use email address 1 as formal/primary email address variable. If more than one email address was entered in this field, then users have to manually transfer them to email address 2 and/or 3 respectively.
<img width="854" alt="20200907MultipleEmailAddresses" src="https://user-images.githubusercontent.com/65529128/92357197-b6034280-f0e7-11ea-9516-1eae40f17dbc.png">

### Possible Alternatives
1. Entering multiple email addresses in the free-text field (separated by ";" or "," or whatever) - but this results in errors when being transferred to external applications where only 1 email address is expected/required and no validation or string processing is done.

2. Create HashSet for email addresses similar to what was done for Person multiple addresses (private Set<Location> addresses = new HashSet<>(); ) issue: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2562

### Additional Information
@o-frietsch - please add any additional information from a PIA perspective that may have been missed.

**Comment by o-frietsch** [comment]
Nothing to add from a team perspective. From my personal point of view, I'd suggest not to implement three email inputs. As a general rule, an IT feature should always be available
- not at all
- exactly once
- unlimited

My advice would thus be to add a list of mail addresses, with [+] and [-] buttons (and to add them to a seperate db table, not add some columns to an existing). Why should there be exactly three addresses, at maximum? This will end up with people adding multiple mail addresses into the last input field...

**Comment by Candice-Louw** [comment]
Closed with implementation of https://github.com/hzi-braunschweig/SORMAS-Project/issues/2744 in 1.58 - thank you! :)
