### ISSUE TITLE
Hide icon "share case with whole country" from case form for internation instance

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2831]
### Problem Description
This cases much confusion to users. In addition, the initial goal for having this implementation was because we could not create contact without a source case in the past. This is not the case now and contacts and cases are now allowed to have different regions and districts.
### Proposed Change
![image](https://user-images.githubusercontent.com/12996724/92380485-8c5b1300-f109-11ea-8e2b-945a46ce2051.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou This is a feature that can be turned off in the database.
