### ISSUE TITLE
Some data of the EventParticipant Person are not saved

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#2838]
### Bug Description
Some data of the EventParticipant Person are not saved
### Steps to Reproduce
1. Open an event participant
2. Fill out a field (e.g. Nickname)
3. Save

### System Details
* SORMAS version: 1.48.0-SNAPSHOT
* Android version/Browser: Firefox

**Comment by MateStrysewske** [comment]
Fixed in #2789
