### ISSUE TITLE
Street column on event participant additional address list should be pseudonymized

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#2841]
### Steps to Reproduce
1. Open an event participant
2. Add a new address to the Addresses list, with street and house number
3. Login with a user with a different jurisdiction
4. Open the previously edited event participant
  => in the Street column the actual street and number is displayed
### Expected Behavior
City column should be pseudonymized and the *Confidential* placeholder should be shown
### Screenshots
<img width="863" alt="Screenshot 2020-09-08 at 13 49 08" src="https://user-images.githubusercontent.com/62599627/92467359-24c0c880-f1da-11ea-872c-55175d2ef07c.png">
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

### Additional Information
- [ ] Check other places where person data is displayed
- [ ] Check the mobile app too

**Comment by raghupola-vg** [comment]
Cannot verify on mobile app due to synchronization issue. Works fine on Web
