### ISSUE TITLE
Mobile app stop oepning after installing 1.47.1 update on Helmholtz

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#2842]
### Bug Description
The mobile app stop opening after installing the 1.47.1 update on Helmholtz
it has been noticed that anytime you update the mobile application to version 1.47.1
this was not happening before .

### Steps to Reproduce
1.Install the older version of sormas mobile app
2.Login with any user account on the mobile app
3. It will prompt you for the update to version 1.47.1
4.Install the update the application will close 
5. Try reopening the mobile application it will shut itself down
* Device: Techno Droip pad 7
* SORMAS version:1.47.1
* Android version/Browser:

**Comment by foyiri** [comment]
@bernardsilenou @MartinWahnschaffeSymeda @fhauptmann @MartinWahnschaffeSymeda @Chinedar This fix is needed as we are currently deploying sormas to two-state in Nigeria and anytime with try to synchronize during the training it prompts us to update to the newer version

**Comment by bernardsilenou** [comment]
@foyiri sormas.helmholtz server has not been up to date for some time now. 
Please test the same tablet on sormas.symeda if the same thing occur. I think this is a server issue

**Comment by MateStrysewske** [comment]
@bernardsilenou The Helmholtz server is on 1.47.1, so it's up-to-date. I'll have a look at the problem right now.

**Comment by MateStrysewske** [comment]
@foyiri Please send me an email with the login details of a mobile user that I can use for testing. I don't have admin access to the Helmholtz server.

**Comment by bernardsilenou** [comment]
@foyiri  Any update on this?

**Comment by bernardsilenou** [comment]
This is resolved in versions as from 1.58
