### ISSUE TITLE
Empty entries can be created for Gathering and Travel outside district fields

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2846]
### Bug Description
Users can create Empty entries for Gathering and Travel outside fields without entering any data.
Clicking on New entry and then clicking on Done creates empty entries.
 
### Steps to Reproduce
1. Login to sormas and Click on Cases.
2. Pick a Case and Select Epidemilogical Data tab
3. Select Yes for Attend a Gathering menu item and click on New Entry
4. Do not enter any fields and click on Done.
5. Do the same for Travel outside of District within last 14 days menu item
6. See if the empty entries are created.

### Expected Behavior
Done button has to be disabled unless user enters data on at least one of the fields.

### Screenshots
![Emty entries can be created](https://user-images.githubusercontent.com/62763628/92486376-4e82eb00-f1ec-11ea-9c4f-0bd7262c3ab0.PNG)

### System Details
* Device:
* SORMAS version: 1.48.0
* Android version/Browser:

**Comment by MateStrysewske** [comment]
I think this is not crucial enough to be worth to be fixed while we're still on Vaadin.

**Comment by bernardsilenou** [comment]
This may create empty records in the db. 
@MateStrysewske  Can we not just make the date of events for all the 3 entities a required field? Such that if nothing is registered, the entry is not saved

**Comment by MateStrysewske** [comment]
@bernardsilenou I just don't really see a reason for it. Users will hardly create travels or gatherings with completely empty data because why should they?

Besides, gatherings and travels will be removed from the system soon as well because we're replacing them with the new exposures.
