### ISSUE TITLE
Travel end Validation statement is Wrong

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2849]
### Bug Description
When the travel end date is selected before the date of Travel, the validation error message/statement is wrong and misleading.

### Steps to Reproduce
1. Login to Sormas and select Cases menu item
2. Pick a Case and Click on Epidemiological data.
3. Scroll to "Traveled Outside of Distrcit....." menu and select Yes
4. Click on New entry and select a start date.
5. At the End date field, select a date before the start date and see the error message displayed.

### Expected Behavior
The Text has to be "Travel End has to be after or on the same day as Travel Start"

###Actual Behavior
the error text is wrong, the positions of the word "start" and "end" are interchanged which misleads the message. PFA screenshot

### Screenshots
![Travel End validation statement](https://user-images.githubusercontent.com/62763628/92488258-97d43a00-f1ee-11ea-9cf4-dffff603bb33.PNG)

### System Details
* Device:
* SORMAS version: 1.48.0
* Android version/Browser:

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
