### ISSUE TITLE
Table content and headers overlap in case list

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#2853]
### Bug Description
In case overview, table content is overlapping with some of the headers when scrolling

### Steps to Reproduce
1. Navigate to https://demoversion.sormas-oegd.de/sormas-ui/#!cases/?dateFilterOption=DATE
2. In the cases table, scroll down
3. Watch the two rightmost headers "ENDE DER QUARANTÄNE" and "VOLLSTÄNDIGKEIT"

### Expected Behavior
Table content and headers should not overlap

### Screenshots
![image](https://user-images.githubusercontent.com/5616564/92590680-eb04c600-f29c-11ea-8ff2-feb3faf61e1e.png)

### System Details
* Device: Linux PC
* SORMAS version: 1.46.0
* Android version/Browser: Firefox

**Comment by Seal33** [comment]
The issue seems to only appear if side-scrolling in the table is enabled and necessary. In that case, only those lines "out of sight" when scrolled all to the left are affected. If your screen is wide enough to show the whole table, the bug will not appear.

**Comment by syntakker** [comment]
Duplicate of #2812
