### ISSUE TITLE
Extend campaign management form [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2855]
### Situation Description
The current campaign management only allows defining name, description and time range for a campaign.

### Feature Description
We need to allow users to define which of the available campaign forms in the system should be used for the campaign

- [x] Add a list of CampaignFormMeta references to the Campaign entity and the dto
- [x] Extend the CampaignEditForm to allow users to edit which campaign forms to use
- [x] Extend the CampaignEditForm to allow users to define the list of CampaignDashboardElements to be shown in the dashboard (see #2527)

See https://app.moqups.com/3NUENEwuOE/view/page/ae3d74ef8

**Comment by BarnaBartha** [comment]
- [ ] when adding a new chart - definition of a new tab id should be possible
