### ISSUE TITLE
Campaign data directory lacks spacing between filters and grid

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#2856]
### Bug Description
On campaign data directory when only the reset filters and apply filters are on a new line there is no spacing between the filter layout and the grid.

### Expected Behavior
Add spacing as on other forms

### Screenshots
![image](https://user-images.githubusercontent.com/8166805/92685215-e3e2c400-f33f-11ea-8977-e3ccdb725f28.png)

**Comment by MartinWahnschaffe** [comment]
Works for me. Looks like this was fixed in the context of another issue.
