### ISSUE TITLE
Important Changes related to PenTest Results - Part I [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2859]
### Feature Description
Description can be found here:
https://wiki.vitagroup.ag/pages/viewpage.action?pageId=24059852

Check in all list views in the UI!

**Comment by markusmann-vg** [comment]
The document is updated

**Comment by BarnaBartha** [comment]
For handling XSS on UI check and fix all cases of:
- [ ] html renderer
- [ ] labels with html content mode
