### ISSUE TITLE
Contacts > Add new contact classification: "Returning traveler" in Contact tab

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2862]
### Situation Description
The number of returning travelers with infection increases (in some countries, 60% of the workload), therefore a new Contact status  “Returning traveler” is introduced.

### Feature Description
Returning Traveler (en) | Reiserückkehrer (de-*)

![image](https://user-images.githubusercontent.com/65529128/92720372-cb38d500-f364-11ea-9cf7-644cc8eaa4a8.png)

New contact type also filterable on the Contact Directory, please.
![image](https://user-images.githubusercontent.com/65529128/92732902-5753f800-f377-11ea-91d2-79b037aa3980.png)

**Comment by JonasCir** [comment]
@bernardsilenou and I had a discussion about this a while ago. We also discussed the option of creating a new contact type for returning travelers, however, this likely breaks the mental model of the people working with SORMAS as there is no proper index case. I think returning travelers and similar needs proper, native handling. 

As @bernardsilenou and me already worked on this, is there a way to schedule a call and discuss this? Doing this via comments is cumbersome :)

**Comment by JonasCir** [comment]
Related to #2603

**Comment by Candice-Louw** [comment]
@JonasCir Thank you for the info - email okay?  candice.louw[at]helmholtz-hzi.de
