### ISSUE TITLE
REST API SORMAS IMPORT

### ISSUE THREAD

**Issue by flefevre-ext** [hzi-braunschweig/SORMAS-Project#2863]
Greetings

We have been contacted in order to solve a problem with the implementation of a REST API in SORMAS.

Despite the information provided (below), we can't understand what we are talking about.

Can you help us?

"We are currently working on setting up an automatic import of cases and contacts.

These imports will be done through the apis exposed by the editor.

We managed to consume the apis on the development environment but we encounter problems on the recipe environment: frd315R02FEL

it would be necessary to install on the server the module allowing the operation of the API.

The following link describes the problem.

https://github.com/hzi-braunschweig/SORMAS-Project/issues/2516

You need to create a dedicated REST user in SORMAS and then use its credentials as HTTP Basic Auth in your requests. I'll revise this issue discussion later and update the docs with everything which turned out to not clear so far.

Here is the link to the online documentation:

https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-rest/README.md"

**Comment by JonasCir** [comment]
@flefevre-ext  Happy to help :) 
Can you specify:
1.  what exactly you are trying to achieve and
1. and what issues do you face right now?

**Comment by JonasCir** [comment]
The editor is only for testing and debugging and is not intended for production use :)

**Comment by flefevre-ext** [comment]
Actually, we've just been asked to solve a problem we are not really aare of.
Our client just asked us to intall maven in a container and run the installation of the API.
I'm not sure of how I should do it.

Please be assured that I want to help to.

Thank you Jonas.

**Comment by JonasCir** [comment]
The point is that you cannot really _install_ the API, it is shipped as part of the normal SORMAS application. If you want to talk to the API of a SORMAS instance programmatically, you likely want to use a REST client that was generated from the openAPI specification. 

I think you should check back with your customer and clarify the task, the requirements/what they want to achieve and the problems at hand. I am happy to help, but right now I don't have enough information :)

**Comment by benchaabaner** [comment]
@JonasCir 
We are trying to consume the sormas APIs from an external application. 
On the development environment, we were able to call the APIs using the openAPI specification. 
The problem we're having is when we try to call the APIs on the recipe environment : frd315R02FEL. There is no maven on the container so we cannot follow the openAPI specification. Is there any other way to do that ?

**Comment by JonasCir** [comment]
You can download a [release](https://github.com/hzi-braunschweig/SORMAS-Project/releases/tag/v1.48.1) which contains the specification under the `openapi` folder from which you can generate the API client on the consuming container. In your final deployment, you might want to make sure that the SORMAS server and the container client are both on the same version to avoid incompatibilities.

**Comment by bernardsilenou** [comment]
@JonasCir Will it be possible for us to have a call with the French developer working on this ticket tomorrow?
Please let me know when you are free and we will make the time.
A lot of cases need to be pushed in the the db this week but development is blocked. We urgently need external help from someone from netzlink.
Thanks

**Comment by JonasCir** [comment]
I am not affiliated with Netzlink, however, I successfully pushed cases with the REST API in the past, so I am happy to help. I dropped you a mail @bernardsilenou.

**Comment by JonasCir** [comment]
@flefevre-ext Does everything work as expected now? Can this issue be closed? :smiley:
