### ISSUE TITLE
graph of disease transmission chains is no longer displayed

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2865]
-->
### Bug Description

The graph of disease transmission chains is no longer displayed. However, only 4746 cases and 18943 contacts are loaded in the database.
The graph loads infinitely but never displays. An error message appears. 

### Steps to Reproduce
1.dashboard
2.select contact and covid
3.click to "please maximise to view the disease transmission chains"

### Expected Behavior
graph display

### Screenshots
![image](https://user-images.githubusercontent.com/65449450/92750110-0a781d80-f387-11ea-841b-02f81b97bac5.png)

### System Details
* Device:
* SORMAS version: 1.47.1
* Android version/Browser:

**Comment by MateStrysewske** [comment]
@carolinverset The screenshot is way too small to see the error message. Can you upload it again in a better quality, please?

**Comment by carolinverset** [comment]
![image](https://user-images.githubusercontent.com/65449450/92879813-a9475d00-f40d-11ea-80b0-aebcd9c11491.png)

I'm sorry, the message is written in french despite the English configuration. 
It is written "you can wait until the page is reachable or exit"

**Comment by carolinverset** [comment]
@MateStrysewske the last comment was for you. Sorry !

**Comment by MateStrysewske** [comment]
Ah, okay, thanks!

**Comment by HolgerReiseVSys** [comment]
I assume that this is already adressed by #2476, which is in review at the moment.
