### ISSUE TITLE
Don't show delete button in create forms of embedded entities in app

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#2871]
### Bug Description
Don't show delete button in create forms of embedded entities in app
### Screenshots
![Screenshot_002](https://user-images.githubusercontent.com/42139870/92920025-d9085c00-f431-11ea-8711-a241423c689b.png)
### System Details
* Device: Emulator
* SORMAS version: 1.49.0-SNAPSHOT
* Android version/Browser: 7.0

### Additional Information
Remove this at least for:
- Previous Hospitalizations
- Gatherings
- Travels
- check for other occurences

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT after update from 1.49.0
