### ISSUE TITLE
Case | Case Person | GPS/Location icon is clickable but nothing happens 

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2872]
### Bug Description
While Creating a Case and going to the Case person page, next to the gps location fields the "Location" icon is clickable and does nothing

### Steps to Reproduce
1. Create a case
2. Go to the Case Person page
3. Scroll down to the GPS location fields (GPS Latitude and Longitude)
4. Click on the 2 Icons in front of these 2 Fields ( the Location icon and the Eye icon)

### Expected Behavior
While clicking on the Icons, actions should happen on the page + warning/error messages should be displayed in case other steps are needed. 
For example, the Eye icon displays a map with the coordinates that were given in the GPS Longitude and GPS Latitude fields. An error message should be displayed requiring these fields to have values.
The Location Icon does nothing when clicked. In the case this icon is not needed it should be removed from the page.
<img width="1426" alt="GPS_buttons" src="https://user-images.githubusercontent.com/70562142/92927701-b16fbe80-f446-11ea-826a-e28719da196a.png">

### System Details
* Device:
* SORMAS version: 1.49.0-SNAPSHOT
* Android version/Browser:

### Additional Information

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she  Is this still an issue? if not can you close pls?

**Comment by AndyBakcsy-she** [comment]
@bernardsilenou The ticket is still a valid one. Nobody worked on it yet. I would leave it until it is taken and decided if it will get fixed or not

**Comment by Jan-Boehme** [comment]
@AndyBakcsy-she @bernardsilenou 
Just tested this in version 1.58.3 and it works as intended. Seems like it was fixed too when another issue has been resolved.

You can click on the pin to fetch the GPS coordinates and the eye to display a small map with the exact location of those coordinates. If the exact address can't be determined the location is displayed in the center of the ZIP-codes region.

**Comment by bernardsilenou** [comment]
@Jan-Boehme I can not tell for now but since nobody worked on in, I do not think anyone would go in a plane that suddenly start working after a failure. Better we go with Andys suggestion and keep it open for now.

**Comment by JaquM-HZI** [comment]
tested on 1.75.4 and it works as expected
