### ISSUE TITLE
Some contact type selections result in missing follow-up until date and dropping of contact if classification is confirmed

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2873]
### Bug Description
When a new contact is created and either one of the types of contacts seen below is selected, the follow-up status will be put to "no follow-up" and the follow-up until date will be missing. Furthermore, if contact classification is put to confirmed contact, contact status will automatically be "dropped" after saving.

Types of contacts where applicable:
 - Face-to-face contact for less than 15 minutes
 - Medical personnel at save proximity (>2 meters), or with protective equipment
 - Medical personnel at save proximity (>2 meters), without direct contact with secretions or excretions of the patient and without aerosol exposure

### Steps to Reproduce
1. Create a new contact where the type of contact is any of the types mentioned above. 
2. Check follow-up status section for status and follow-up until date.
3. Change the contact classification to confirmed contact and save.
4. Check the contact status.

### Expected Behavior
Selected types of contact should allow normal calculation of follow-up until date. Contact should also stay active if confirmed contact has been selected as the contact classification.

### Screenshots
![Kontaktstatus](https://user-images.githubusercontent.com/65529128/92944636-89875780-f454-11ea-855f-dcac304947e9.PNG)
![Nachverfolgung bis](https://user-images.githubusercontent.com/65529128/92944648-8d1ade80-f454-11ea-8d72-a385f514dff8.PNG)

### System Details
* Device:
* SORMAS version: 1.48 (also present in 1.46)
* Android version/Browser: Firefox

**Comment by MateStrysewske** [comment]
@kwa20 We'll need to discuss this because part of what you've described is intentional behaviour.

**Comment by Candice-Louw** [comment]
@bernardsilenou - could you please confirm if this is the expected behaviour?

**Comment by bernardsilenou** [comment]
@Candice-Louw As Maté mentioned, it was programmed like this, certain contact categories with low risk did not require followup.
@MateStrysewske  I suggest we just take out all forms of validation between contacts types, categories and followup by default. We have filter for contact category and types on the contact directory, so users can use that to filter high risk contact to call for the day. I just realized the filter does not work, will add an issue

**Comment by bernardsilenou** [comment]
No longer needed since this was the initial configuration. If there is a need to change this, then we need to add a configuration in another issue to determine they type of contacts to have followup.
