### ISSUE TITLE
Contact Directory | Double clicking on Contact Classification opens the contact

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2874]
### Bug Description
Some fields of the Contact Directory act like a link without a visual description that clicking there will act like a link
### Steps to Reproduce
1. Open the Netzlink environment and log in as National User
2. Go to Contacts 
3. Click on the row for any of the contacts under Contact Classification Column
4. Double click on the same place

### Expected Behavior
Clicking somewhere else than where the ID of the contact is displayed and underlined as a link should not open the contact

### Actual Behavior
The Contact is opened when double-clicking. It seems that the row is being selected thus the opening of the contact happens.
 
### Screenshots
![Contact_directory_contact_classification_doubleclicking](https://user-images.githubusercontent.com/70562142/92929093-afa6fa80-f448-11ea-84b1-90eebc2dc97a.jpg)

### System Details
* Device:
* SORMAS version: 1.49-SNAPSHOT
* Android version/Browser:Chrome

**Comment by MateStrysewske** [comment]
That's intended behaviour. Double-clicking is supposed to open the entity as an alternative to clicking on the link.
