### ISSUE TITLE
New apply filter button is being ignored in event participants

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2877]
### Bug Description
System will start filtering list before "apply filter" button is used in event participants. 
### Steps to Reproduce
1. Open any event and go to event participants. 
2. Start entering dates or names in the filters.

### Expected Behavior
List should only filter for selected filteroptions when "apply filter" button is used.
### System Details
* Device:
* SORMAS version: 1.48
* Android version/Browser: Firefox

**Comment by bernardsilenou** [comment]
- This issue is also with "apply date filter" icon on directories: case, contact
- Bug was newly introduced after version  1.47.1
- Reactivity does not apply to directory sum. eg see image

![image](https://user-images.githubusercontent.com/12996724/93217533-7c76ab00-f769-11ea-9918-c49295433821.png)

**Comment by bernardsilenou** [comment]
I did  a quick test and realized the 2 apply filter icons have some form of conflict. Can we take out the apply date filter and just go with apply filter? or keep both but use the dame backed variable with activation from both icons?

![image](https://user-images.githubusercontent.com/12996724/93218661-c318d500-f76a-11ea-9564-277ecb314803.png)

**Comment by vlad-ciucescu** [comment]
Hello @bernardsilenou 
Both options are possible, but I would suggest that we do this in a new ticket, since it is not related to the previous bugs, but it is rather a change request.

**Comment by vlad-ciucescu** [comment]
@bernardsilenou 
Update: by fixing the bug we actually reach the situation you described in the second option: 
> keep both but use the dame backed variable with activation from both icons

The 'Apply Date Filter' button really becomes redundant, so I would suggest that we remove it altogether.

**Comment by bernardsilenou** [comment]
@vlad-ciucescu  Thanks for the clarification. We then keep both icons for now since there is much work to do.

**Comment by bernardsilenou** [comment]
Tested and all was ok

**Comment by raghupola-vg** [comment]
- Reset filter option is not displayed for Events and Samples when more filters is selected and a date is picked and clicked on apply date filters.
- Apply date filter is not redundant yet.
Tested on version 1.49.0

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.49.0-SNAPSHOT
Reset button is working, Apply filters only shows the results after it is clicked. 
Functionality is working as expected
