### ISSUE TITLE
Samples | For any user except National User the app hangs while opening the Samples page

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2881]
### Bug Description
Going to the Samples page, for most users, makes the App unresponsive.
### Steps to Reproduce
1. Open the Netzlink environment and log in with any user except the National User
2. Click on Samples 
3. Check behavior 

### Expected Behavior
The Samples page should open fast

### System Details
* Device:
* SORMAS version: SORMAS Version: 1.49.0-SNAPSHOT
* Android version/Browser: Chrome

**Comment by bernardsilenou** [comment]
No longer a bug with newer versions
