### ISSUE TITLE
Task Management sorting by 'Assigned to' and 'Created by' results in error message

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2883]
### Bug Description
Regarding the Sormas version 1.48.1 which was uploaded yesterday, I report the following BUG: when I am in the task management, it is currently not possible to sort by 'Assigned to' and 'Created by'. If you click on it an error message opens. This is a big problem for us (Switzerland) because the Contact Tracers need these functions for the daily tracing.

### Steps to Reproduce
1. Tasks
2. Click on "Assigned to" or "Created by" column header in the table

### Expected Behavior
Values sorted and displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/93204218-01f06000-f756-11ea-8ecc-0fe76fb74d30.png)
![image](https://user-images.githubusercontent.com/65529128/93204343-3bc16680-f756-11ea-9ea4-3befce3afbc1.png)

### System Details
* Device:
* SORMAS version: 1.48.1
* Android version/Browser:

**Comment by AndyBakcsy-she** [comment]
Verified this issue on SORMAS Version: 1.49.0-SNAPSHOT
