### ISSUE TITLE
[QA] Performance Test Plan [Timebox: 3d]

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2886]
### Feature Description
Performance testing is needed on the Sormas Project thus, the creation of a Test Plan is the first logical step towards this

Needed Tasks:
- [x] Create a Draft of the Performance Test Plan
- [x] Gather reviews from involved stakeholders
- [x] Decide/Discuss/Suggest what the Performance testing Environment should look like
- [x] Suggest Test Data creation model 
- [x] Decide/Discuss on what functionality or which flows need to be tested first in a Performance/Load environment
- [ ] Decide on which KPI's to take into consideration when talking about performance-related issues
- [ ] Investigate Tool related Infos:
- [ ] Licensing 
- [ ] Integration with JMeter
- [ ] Continous Integration set-up
- [x] Creation of  first/basic Test cases for the Performance Test environment #3075 
- [x] Creat Test Data for the Environment #3076 

 ### Possible Alternatives

**Comment by AndyBakcsy-she** [comment]
Created the first draft of the Performance Test Plan + Test Data creation Model

**Comment by AndyBakcsy-she** [comment]
Discussed during the Meeting from 29.09.20 about what the performance environment should look like,
Suggested the first script to be implemented 
Requested further information regarding the Initial state of the database
Requested further information regarding the usage patterns for different countries.

**Comment by AndyBakcsy-she** [comment]
#3075 Linking this issue with the implementation of the First script

**Comment by JonasCir** [comment]
@AndyBakcsy-she
Hi, I plan to make some adjustments to DB layout in the future and it would be great to measure the performance impact of them. I have some questions:

1.  Will performance measurement be available to each developer in form of a script to measure times locally?
1.  Will performance measurement integrated into the CI such that the performance impact of PRs can be monitored?
1. Are there plans to store performance results (with regard to a defined test set) such that they can be visualized/used to keep track of the general trend?

**Comment by JonasCir** [comment]
And I don't if this adds value, but keeping track of how much storage is consumed by the DB might also be interesting :D

**Comment by AndyBakcsy-she** [comment]
@JonasCir  Please don't check in the changes for the DB until we have at least one script measuring performance. 
for question 2, the answer is Yes, we will be looking at how to post the results in Jenkins /Github or maybe on some Confluence page so that the values are public. 
The scripts will be included in the Testing Repo.

**Comment by JonasCir** [comment]
Alright, I'll postpone my work on this :D Thanks for the answer!

**Comment by StefanKock** [comment]
What is the progress on this topic? It is now the third sprint where this ticket is planned in.

**Comment by AndyBakcsy-she** [comment]
Closing issue as the Test plan was done and published to github, First scenario was automated but we are havin problems with the differences between the import and export files. 
Will create new issues for next steps of this issue.
