### ISSUE TITLE
External Lab officer experiences bugs when filtering for samples and cannot see associated case column

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2898]
### Bug Description
External Lab officer does not see the "associated case" column in the sample directory.

Furthermore, errors occur when trying to filter for "contact samples" or "event participant samples". After exiting the error message, any subsequent attempts to filter fail as well, even for "all samples" and "case samples", which was initially possible.
After exiting the error message and switching to another menu item, External Lab Officer is unable to reopen samples. To do so they have to log out and back in again.
 
### Steps to Reproduce
1. create cases and contacts plus respective samples as e.g. admin and create an external lab officer that is assigned to appropriate regions to be able to see and work on these samples.
2. Log in as the external lab officer and go to samples.
3. check for "associated case column".
4. initially filter for all and case samples, then filter for contact and/or event participant samples.
5. After exiting error message, switch menu item and try reopening samples.

### Expected Behavior

External Lab officer should be able to see the column "associated case".

They should also be able to properly filter and move between menu items.

### System Details
* Device:
* SORMAS version: 1.48.0
* Android version/Browser: Chrome

### Additional Information
tested on test1401.sormas-oegd.de
<img width="1267" alt="Screen Shot 2020-09-16 at 10 05 27 PM" src="https://user-images.githubusercontent.com/70317594/93389313-4837e300-f86c-11ea-8df3-e59c7d690c89.png">
<img width="1274" alt="Screen Shot 2020-09-16 at 10 06 59 PM" src="https://user-images.githubusercontent.com/70317594/93389348-5685ff00-f86c-11ea-93bb-dc6e196ed0fa.png">
<img width="1275" alt="Screen Shot 2020-09-16 at 10 08 41 PM" src="https://user-images.githubusercontent.com/70317594/93389391-643b8480-f86c-11ea-9e0b-50a6f61238a5.png">

**Comment by MateStrysewske** [comment]
It's expected behaviour that external lab users don't see cases. Actually, it's a bug that they are allowed to see the contacts and event participants. At least that's how we were told to implement it so far. External lab users are supposed to work in laboratories in other countries.
