### ISSUE TITLE
Cases and Contacts > Display 3 missing symptoms for COVID-19 for Switzerland

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2899]
### Feature Description
Display missing symptoms for COVID-19, for Switzerland (CH).

### Problem Description
COVID-19 symptoms were recently adjusted for Switzerland - https://github.com/hzi-braunschweig/SORMAS-Project/issues/2669.

Three symptoms are not visible on 'Clinical signs and symptoms' masks for Cases and Contacts, including:
1.  Allgemeines Krankheitsgefühl = General signs of disease (Symptoms.generalSignsOfDisease)
2.  Erhöhte Herzfrequenz (Herzrasen) = Fast heart rate (Symptoms.fastHeartRate)
3.  Hautausschlag = Skin rash (Symptoms.skinRash)

### Proposed Change
Include these variables in all Clinical Signs and Symptoms lists/masks for COVID-19, for CH (Swiss) systems.

### Further information
Full list of symptoms for COVID-19 for Switzerland:
SORMAS CH German | SORMAS CH English | SORMAS symptoms – Data dictionary
-- | -- | --
Fieber | Fever | Symptoms.fever
Allgemeines   Krankheitsgefühl | General signs of disease | Symptoms.generalSignsOfDisease
Fiebergefühl | Feverish feeling | Symptoms.feverishFeeling
Schüttelfrost oder Schwitzen | Chills | Symptoms.chillsSweats
Gesteigerte Müdigkeit | Increased fatigue | Symptoms.fatigue
Allgemeine Schwäche | General weakness | Symptoms.weakness
Kopfschmerzen | Headache | Symptoms.headache
Muskel- oder Gliederschmerzen | Muscle pain | Symptoms.musclePain
Verwirrtheit | Confused/disoriented | Symptoms.confusedDisoriented
Schnupfen (laufende oder verstopfte Nase) | Runny nose | Symptoms.runnyNose
Halsschmerzen | Sore throat | Symptoms.soreThroat
Trockener Husten ohne Auswurf | Dry cough without sputum | Symptoms.coughWithoutSputum
Husten mit Auswurf | Cough with sputum | Symptoms.coughWithSputum
Husten mit blutigem Auswurf | Coughing with heamoptysis | Symptoms.coughWithHeamoptysis
Rasche Atmung | Rapid breathing | Symptoms.rapidBreathing
Schwierigkeiten beim Atmen | Difficulty breathing | Symptoms.difficultyBreathing
Kurzatmigkeit | Difficulty in brealthing | Symptoms.difficultyBreathing
Atemnot in Ruhe oder bei Anstrengung | Breathlessness at rest or during exertion | Symptoms.breathlessness
Druck auf der Brust | Pressure on the chest | Symptoms.chestPressure
Brustschmerzen | Chest pain | Symptoms.chestPain
Blaue Lippen | Blue lips | Symptoms.blueLips
Allgemeine Kreislaufprobleme | General blood circulation problems | Symptoms.bloodCirculationProblems
Erhöhte Herzfrequenz (Herzrasen) | Tachycardia | Symptoms.fastHeartRate
Herzstolpern | Palpitations | Symptoms.palpitations
Schwindel (beim Aufstehen aus dem Sitzen und Liegen) | Dizziness (when standing up from a sitting or lying position) | Symptoms.dizzinessStandingUp
Blutdruck zu hoch oder zu tief (gemessen) | Blood pressure too high or too low (measured) | Symptoms.highOrLowBloodPressure
Übelkeit | Nausea | Symptoms.nausea
Erbrechen | vomiting | Symptoms.vomiting
Bauchschmerzen | Abdominal pain | Symptoms.abdominalPain
Durchfall | Diarrhea | Symptoms.diarrhea
Kein Urinlösen mehr | Urinary retention | Symptoms.urinaryRetention
Geruchstörung oder Verlust des Geruchssinns | Loss of smell | Symptoms.lossOfSmell
Geschmacksstörung oder Verlust des Geschmackssinns | Loss of taste | Symptoms.lossOfTaste
Hautausschlag | Skin rash | Symptoms.skinRash

**Comment by MateStrysewske** [comment]
Skin rash is already enabled (the English caption is "Maculopapular rash") for Swiss servers.

**Comment by raghupola-vg** [comment]
Tested on today's build and the new symptoms are now available.
