### ISSUE TITLE
Contacts > Remove/hide COVID app check-boxes

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2900]
### Feature Description
At "Contact Person" (only) remove/hide two check-boxes:

- [ ]  Has COVID app
- [ ] COVID code was generated and delivered

![image](https://user-images.githubusercontent.com/65529128/93405803-4bdc6180-f88e-11ea-91b1-c63793ca66f2.png)

### Additional Information
Feature originally requested (for CH) for Cases only (#2725 ).

**Comment by raghupola-vg** [comment]
Tested on today's build and works fine.
