### ISSUE TITLE
Events | Participant Count column not translated in any language

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2901]
### Bug Description
The Participant Count field on the Event Page is not translated to other languages. 
### Steps to Reproduce
1. Open the Test environment from Netzlink (https://test.sormas.netzlink.com/sormas-u)
2. Go to Settings and change the language
3. Go to the Event page (Ereingnise in the case of german language)
4. Check the last column: Participant Count is displayed. 

### Expected Behavior
Consistent Translation of all fields should be applied. This column's header should also be translated to all languages supported by the app

### Screenshots
![participant_count](https://user-images.githubusercontent.com/70562142/93458923-a1922780-f8e9-11ea-964b-c9105cc9c36d.jpg)

### System Details
* Device:
* SORMAS version: SORMAS-Version: 1.49.0-SNAPSHOT
* Android version/Browser:

**Comment by BarnaBartha** [comment]
No longer reproducible. Issue probably was because of not yet updated captions.
