### ISSUE TITLE
Contact Address appends null to every contact 

### ISSUE THREAD

**Issue by Aldriin** [hzi-braunschweig/SORMAS-Project#2903]
### Bug Description

While viewing the detailed contact information there is a null displayed after every contact address. 

### Steps to Reproduce
1. Log in into SORMAS with Admin Account
2. Go to contact Tab
3. Switch to detailed display

### Expected Behavior
No null after address

### Screenshots
![grafik](https://user-images.githubusercontent.com/59454035/93464539-9b03b000-f8e9-11ea-8c64-482456eab1f9.png)

### System Details
* Device: Windows 10 Enterprise
* SORMAS version: 1.48.1
* Android version/Browser: Firefox 78.1.0esr (64-Bit)

**Comment by Aldriin** [comment]
Seems to be associated with the way data was imported. Data imported with the new template works fine.

**Comment by MateStrysewske** [comment]
@Aldriin There's probably an issue with the way the captions are generated, so it's still some kind of a bug.
