### ISSUE TITLE
Adding a "title of the action" field in the text editor available in the tab follow actions

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2905]
### Situation Description
To date, the actions are described in the "action monitoring" tab. Each action can be described via two blocks of text, without limitation in terms of characters. In order to make the best use of the elements entered, in particular in the context of an action monitoring table, it is useful to complete the action text editor with a "title of the action" field

### Feature Description
For each event and each action entered in the "action monitoring" tab, complete the "text editor" component with a "title of the action" field to be placed above the "description" field.
The field is also to be added to the list of event actions (above the date of the action)

### Additional Information

@xavier-calland @bernardsilenou

**Comment by xavier-calland** [comment]
@carolinverset 
Is the field mandatory?
Do we need to initialize this value (and how) for all existing actions in database?

**Comment by xavier-calland** [comment]
@ftavin

**Comment by carolinverset** [comment]
@xavier-calland @ftavin
Making it mandatory seems difficult to me. One solution would be to recommend entering the field by setting it to soft required (dark border without the asterisk)

**Comment by ftavin** [comment]
@bernardsilenou can you add fr label to this issue too ? thanks !

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
