### ISSUE TITLE
Addition of an event actions directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2907]
### Situation Description
To date, SORMAS does not offer a synthetic view of the events and the actions taken as part of their investigation.

### Feature Description

**Development of a detailed view for monitoring all the actions of the events.**

Like what exists for cases (default view / detailed view), the proposed development concerns the events directory which would be supplemented by a synthetic view of all the actions associated with the different events. 

This view will allow users to access all events and their associated actions:
- Event identifier 
- Title of the event (cf issue #2904)
- date of signal 
- event status: cluster, signal, event, dropped 
- Action: "action title" field ( cf issue #2905 )
- Action: date of creation of the action and date of last modification (min/max)
- Action: status of the action 

**Filters to be provided in the detailed view "Actions"**

Like all the other tabs, some "Filters" help users to select information based on different criteria:
- Region (of the event)
- Department (of the event)
- Municipality (of the event)
- Identifier or title of the event
- Signal date (min / max) (of the event)
- Status of the event
- Status of the investigation
- Status of the action
- Date of modification of the action

**Features to be provided in the detailed and default view "Actions"**

For reporting purposes, from the events directory (default view and detailed view), provide the function "basic export" allowing to export the only information displayed after selection of filters

### Additional Information

@xavier-calland @bernardsilenou

**Comment by xavier-calland** [comment]
@ftavin

**Comment by ftavin** [comment]
This functionnality was validated by @bernardsilenou on today's meeting with @carolinverset

+ can we add the fr label ?

**Comment by xavier-calland** [comment]
@MateStrysewske I am working on this issue.
Review of #2924 and #2926 would be appreciated as this issue depends on fields added in these PR.

**Comment by carolinverset** [comment]
@xavier-calland  @ftavin 
After discussions with the teams, it would be essential to also have the field of the priority level of the action and the name of the person in charge of the investigation. Is it possible ?

**Comment by ftavin** [comment]
@carolinverset in the case directory, where we have a similar functionnality (default/detailled view), the filters selected in a view are still active when you switch to the other view.

If we want to have the same here (the filters applied to the events are still active when you switch to actions view), we need to have the same filters in both views (only concerning events, we will add action filters in the actions view)

Are you ok with that ? (this means more filters on events than you originaly asked in the issue)

**Comment by carolinverset** [comment]
@ftavin 
Personally i am ok with implementing additional filters in the event part. I think the filters make it easier to find information and save time in using SORMAS. 
Best regards

**Comment by carolinverset** [comment]
@xavier-calland @ftavin 
Following the discussion with the French teams, it would be important to have the "priority leve of the actionl" field  in the detailed view of the actions. 


In addition, I propose to discuss tomorrow with @bernardsilenou the possibility of integrating a field allowing the name of the person in charge of the investigation to be identified (perhaps by using the field "responsible surveillance officer")

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.50.0-SNAPSHOT
