### ISSUE TITLE
 Have a filter in the case directory to target cases linked to an event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2908]
### Situation Description
The case directory can be filtered by region, department, identifier, etc. Conversely, no filter can be used to filter on the possible involvement in a given event.

### Feature Description
In the directory of cases, it is proposed to
- Create two columns: event ID and event description (first 20 characters) (or "event title" when #2904 will be done)
- add a filter allowing to filter the cases according to the possible implication to a given event (via ID event or keyword of the description field) It is therefore a text field (like the filter "ID, name, EPID number, institution, person's telephone / postal code / city ”)

The filter works as follows: For a case to be identified as linked to an event, the case (its ID) must be present in "EventParticipant.resultingCase" of the event in question.

In the following example, a filter on Event 1 would display Case 1, not Case 2.
![image](https://user-images.githubusercontent.com/65449450/93567714-5e8a8f80-f98f-11ea-8662-0bf29166aaa3.png)

The following columns are to be added in the detailed view, the detailed export ("event" export group):

- title of the event (if field added)
- event code
- event status

### Additional Information

@xavier-calland @bernardsilenou

**Comment by xavier-calland** [comment]
@ftavin

**Comment by bernardsilenou** [comment]
@carolinverset We agreed to do the same thing on the contact directory.  contact person  == eventParticipant Person. This is just a reminder to add the other issue and link it to this one.

**Comment by bernardsilenou** [comment]
Just short clarification:
- When filtering the case directory, the person of the case (case person) == person of the event participant (event participant person)
- If the case resulted from a contact, then the person of the contact  is the same as the person of the case. However, we do not need to condition on the contact person here.

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou we just checked with @xavier-calland and we noticed that the following situation is possible with the data model : a single "case" can be the "resulting-case" of several "event-participant".

If this occurs, how are we supposed to populate the 3 new columns for that case ?

**Comment by bernardsilenou** [comment]
> @carolinverset @bernardsilenou we just checked with @xavier-calland and we noticed that the following situation is possible with the data model : a single "case" can be the "resulting-case" of several "event-participant".

This is true. It is the same thing with contacts, a single case can result from several contacts. It will be better to address this in detail in a separate issue. For now, we can just show the most recent event id (in terms or end date of event) on the case directory table. When users open the case form, of course they will see all the associated events. Searching by event id, title, ... will consider all the other events liked to the case.

We see what the others have to say also

 > If this occurs, how are we supposed to populate the 3 new columns for that case ?

**Comment by ftavin** [comment]
thank you @bernardsilenou for your response
as the dates of the event are not mandatory, what do we do if they are not filled ?

In addition, I talked with @carolinverset and we think it could be nice to have a visual indication when a case is linked to multiple events. This information could be materialized with a special character (like * or #) before or after the event name or via an additional column "number of events"

**Comment by ftavin** [comment]
@bernardsilenou 

our suggestion :
- if the end date is not filled we use the start date, if they are both empty, we use the date of report (which is automaticaly filled)
- an additional column is more practical for the user (a symbol would need a legend above the list and the use of a number is more precise)

**Comment by ftavin** [comment]
note : the suggestions on my previous comment were validated during today's meeting with @bernardsilenou and @carolinverset

**Comment by bernardsilenou** [comment]
@ftavin @MateStrysewske @carolinverset 
For cases and contact, we have at least one mandatory date (report date). This help us to have correct statistics especially when we have retrospective data entry in the db.
For events we do not gave a required date variable. Is it necessary to add a report date to events OR make the event date required field?
This is not a big issue for now because majority of events have "date of event"

**Comment by xavier-calland** [comment]
@MateStrysewske I am working on this issue, a PR will be coming soon.
