### ISSUE TITLE
Add phone number and email validation forms  (Case, Contact, Event Participant)

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2910]
### Feature Description
Add on forms for: case, contact, event participant
Only on web app
![phoneNumber_email_Validation](https://user-images.githubusercontent.com/70562142/93588547-3e20fc00-f9b4-11ea-8b72-da18bbf08684.jpg)

Phone Forms should only accept phone number alike entries while Email Forms should only accept Email-alike entries.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT

**Comment by MateStrysewske** [comment]
- [ ] Use validation in case and contact creation forms

**Comment by AndyBakcsy-she** [comment]
Verified the issue on Case and Contact creation forms on SORMAS Version: 1.51.0-SNAPSHOT

**Comment by AdrianMichaelis** [comment]
With minors we often use the phone number field as follows:  

`Mother: 1234 567 890 Father: 9876 5432` 

Not being able to enter values like that from now on is **not** a problem. 
However, I am worried about what will happen with **existing data** in this field once 1.50.1 goes live. Phone numbers disappearing from our records would be catastrophic. 

I'm unable to confirm the outcome of retroactive validation on the test server. Can anyone enlighten me?

**Comment by ChristopherRiedel** [comment]
> With minors we often use the phone number field as follows:
> 
> `Mother: 1234 567 890 Father: 9876 5432`
> 
> Not being able to enter values like that from now on is **not** a problem.
> However, I am worried about what will happen with **existing data** in this field once 1.50.1 goes live. Phone numbers disappearing from our records would be catastrophic.
> 
> I'm unable to confirm the outcome of retroactive validation on the test server. Can anyone enlighten me?

I can assure you, there will be no data disappearing with the new feature. However, the feature will cause that if an existing person is opened with entered data as described by you, it will not be possible to save the person without changing the data in the phone number field.

**Comment by AdrianMichaelis** [comment]
@ChristopherRiedel Thank you for the quick reply! And for setting my mind at ease
