### ISSUE TITLE
Synchronization from the Sormas App to the Web does not work

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2911]
### Bug Description
Synchronization from a mobile device to the web does not work.
### Steps to Reproduce
1. Download the app and install it on an Android Phone
2. Link the app to the Netzlink server and connect with the Survailane Officer user
3. Create a new Case on the Phone (mobile app)
4. Complete the process of creating the case by filling all the required information
5. Swipe from up towards down so that the synchronization starts.

### Expected Behavior
The synchronization should happen in a matter of seconds and if the user opens the Web app the newly created case should be visible after the synchronization.

### Actual results
The synchronization takes soo much time or it does not work at all so that the app freezes in the synchronization process.
The newly created Case does not get synced to the server.
The synchronize icon is displayed for the newly created case but does not work

### System Details
* Device: OnePlus 6T
* SORMAS version: SORMAS Version: 1.49.0-SNAPSHOT

* Android version/Browser: 10

### Additional Information
New cases created on the web, get synchronized to the app.

**Comment by MateStrysewske** [comment]
Can you please confirm this on at least another server? I don't have these problems on my dev machine.

**Comment by raghupola-vg** [comment]
Issue is only with Netzlink test server. (https://test.sormas.netzlink.com/).
Tested with Swiss server and the sync works fine.
