### ISSUE TITLE
Version 1.48.1 does not trigger auto update of the mobile app on earlier versions

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2915]
### Bug Description
Mobile app is on 1,47 and connected to sormas.symeda server on 1,48,1.  
Cases can be sync with db but server does not prompt the client to upgrade
### Steps to Reproduce
1.
2.

### Expected Behavior
- Each  time the app is sync with server, users should be promoted to update.
### System Details
* Device: android Samsung 
* SORMAS version: 1,48,1
* Android version/Browser: 9

**Comment by MateStrysewske** [comment]
@bernardsilenou Does this also happen on other servers?

**Comment by bernardsilenou** [comment]
@MateStrysewske no production server that uses the mobile app is on this version. We just need to address the issue in the 1,49

**Comment by MateStrysewske** [comment]
@bernardsilenou I'm asking about other test systems.

**Comment by bernardsilenou** [comment]
@MateStrysewske All my mobile apps are connected to the symeda system. I cant test on other systems now. I  will test with the new release 1,49 and see if it works. I will also connect other mobile devices to other test servers for future testing

**Comment by bernardsilenou** [comment]
included in 1,49

**Comment by MateStrysewske** [comment]
@bernardsilenou Is this still a problem?

**Comment by bernardsilenou** [comment]
I do not know any production server on this version and cannot test it now. I suggest we close the ticket
