### ISSUE TITLE
Symptoms refinement for general signs of disease [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2916]
### Feature Description

The general signs of disease need to be split into four individual symptoms in order to conform to symptoms in the symptom diaries PIA and Climedo. 

### Problem Description

Symptoms in the symptom diaries differ from the ones already existing in SORMAS.

### Proposed Change

The general signs of disease (symptoms.generalSignsOfDisease) should be split into four symptoms. The general signs of disease should not be shown anymore and be replaced by the following:

- shivering (new symptom)
- headache (Symptoms.headache)
- feeling ill (new symptom)
- muscle pain (Symptoms.musclePain)

<img width="1253" alt="Screen Shot 2020-09-19 at 6 00 03 PM" src="https://user-images.githubusercontent.com/70317594/93671771-21fd8780-faa6-11ea-96fd-4ccbd1a04443.png">

### Additional Information
This change also includes symptoms shown in the follow-up tabs for cases and contacts when adding new visits.

**Comment by MateStrysewske** [comment]
I suspect this is for German servers? Headache, feeling ill and muscle pain are already part of the system and simply have to be enabled. Shivering could be added to the list of symptoms, but may be too close to chills and sweats. @bernardsilenou Do you have input on this?

**Comment by bernardsilenou** [comment]
@MateStrysewske I agree with you:
- This is only fro German servers
- Shivering and chills are very close but not the same thing. Some times people just want to see the exact words. So if we do not have shivering, then we should add among list of symptoms and activate fro German server only.
-Translations may not fully handle it, so better we add shivering

**Comment by kwa20** [comment]
@MateStrysewske This was my concern intially as well. Gaby said that they differentiate between really shaking, increased target value of temperature and muscle contractions (Chills or sweats) and feeling cold at the beginning of getting sick (shivering).

**Comment by Candice-Louw** [comment]
> I suspect this is for German servers? Headache, feeling ill and muscle pain are already part of the system and simply have to be enabled. Shivering could be added to the list of symptoms, but may be too close to chills and sweats. @bernardsilenou Do you have input on this?

@MateStrysewske @bernardsilenou This will be for Swiss servers too, please.  They make use of PIA and I believe the PIA API will be reliant on this change.

@o-frietsch - Please feel free to give input on this from a PIA perspective.

**Comment by markusmann-vg** [comment]
In Scope: Spliiting the symptoms as described for Switzerland and Germany

**Comment by MartinWahnschaffeSymeda** [comment]
Since general signs of disease has only been used form de and ch anyway, we can either delete the symptom after it has been migrated (or simply rename it to "feeling ill" in classes and database).

Important: On Android (SQLite) renaming and dropping of columns is not easily possible so you can just leave the field as-is. I'd suggest the rename the field in the entity and add a @DatabaseField annotation that contains the different columnName (see. EPiData.directContactDeadUnsafe for an example).

**Comment by AndyBakcsy-she** [comment]
Verified issue on the Swiss environment on  SORMAS Version: 1.50.0-SNAPSHOT
