### ISSUE TITLE
Editing Tasks takes too long

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2921]
### Bug Description
Editing Tasks takes 15 Secs until a task is opened with national user or admin.
Editing a task as a contact supervisor

### Steps to Reproduce
1. https://test1401.sormas-oegd.de/
2. Login as Contact supervisor
3. open case
4. edit a task => opens immediately
5. log out / log in as national user or admin
6. open case => busy indicator => it takes up to 15 seconds before I can edit the task

### Expected Behavior
No matter what role, tasks should open up as fast as if you are logged in as Contact supervisor

### System Details
* Device:
* SORMAS version: 1.48.1
* Android version/Browser: chrome & firefox

**Comment by StefanKock** [comment]
I was able to reproduce this with case https://test1401.sormas-oegd.de/sormas-ui/#!cases/data/WLZIWH-OPEGEI-B4VNQA-57UVSGOE (edit and create).
Notable directly in the form: 16 vs. 274 available assignees, maybe that is the performance issue

**Comment by StefanKock** [comment]
> Notable directly in the form: 16 vs. 274 available assignees, maybe that is the performance issue

Looking into _TaskEditForm_ I see three suspects for this performance issue (which might combine to worsten the problem):
1. Line 128: _addValueChangeListener_ to update the possible assignees: Check whether this runs on form binding for each field. 
2. Line 141: Determining the district and region calls _CaseFacade::getCaseDataByUuid_ which might lead do longer loading time with pseudymization.
3. Line 193: _assigneeUser.setItemCaption(user, taskController.getUserCaptionWithPendingTaskCount(user));_ generates caption with assigned tasks for each of the 270+ users.

**Comment by MateStrysewske** [comment]
@StefanKock Thanks! Your third suspect is indeed the main problem here.

- [ ] Use a single query to retrieve the task counts of all users in the list instead of an individual query per user
- [ ] Remove the logic from TaskGrid and instead directly select the task count when retrieving the index list from the backend

**Comment by MateStrysewske** [comment]
- [ ] uuid list isn't actually used in getPendingTaskCountPerUser

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
Did multiple tests on the test.sormas.netzlink.com environment and did not encounter any lag in opening/editing any tasks
