### ISSUE TITLE
Have a filter in the contact directory to target contact linked to an event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#2922]
@ftavin @xavier-calland @bernardsilenou  @olivierleuci

### Situation Description
The contact directory can be filtered by region, department, identifier, etc. Conversely, no filter can be used to filter on the possible involvement in a given event.

### Feature Description
In the directory of contact, it is proposed to
- Create two columns: event ID and event description (first 20 characters) (or "event title" when #2904 will be done)
- add a filter allowing to filter the contact according to the possible implication to a given event (via ID event or keyword of the description field) It is therefore a text field (like the filter "ID, name, EPID number, institution, person's telephone / postal code / city ”)

Like the cases (issue #2908 )

**Comment by ftavin** [comment]
@carolinverset  To be more specific on the "involvement in a given event" for a contact : we consider a contact to be involved in an event if both the person corresponding to the contact AND the case linked to the contact are involved in this event. Am I right ?

**Comment by ftavin** [comment]
@carolinverset examples (provided by @xavier-calland)
![Filtre contact _ événement](https://user-images.githubusercontent.com/15834125/93745203-6d717c00-fbf3-11ea-9ac7-b1b421ab72be.png)
with example 1, filter on event 1 returns no contacts, filter on event 2 returns no contacts
with example 2, filter on event 1 returns contact 1, filter on event 2 returns no contacts

**Comment by xavier-calland** [comment]
@bernardsilenou @MateStrysewske can you confirm too?

**Comment by bernardsilenou** [comment]
@carolinverset 
> * Create two columns: event ID and event description (first 20 characters) (or "event title" when #2904 will be done)

- I vote for event title
- I hope we add these 2 variables to detailed view only, right? My reason is the this variables will be missing for most of the contacts

> * add a filter allowing to filter the contact according to the possible implication to a given event (via ID event or keyword of the description field) It is therefore a text field (like the filter "ID, name, EPID number, institution, person's telephone / postal code / city ”)

- Add filter by keywords of the event title 
- Add filter by "belonging to any event", this can just be a small checkbox at the top of the contact directory table just as we have for "only high priority contacts"
- Filtering based on "person's telephone / postal code / city ” will be more complicated because these are person related not event related. These filters already exist based on the contact person but do not have anything to do with the events.  I hope it is fine to not add them? The final list of variable will be eventid, title, description, region, district

> 
> Like the cases (issue #2908 )
> 
> ### Possible Alternatives
> ### Additional Information

**Comment by bernardsilenou** [comment]
> @carolinverset To be more specific on the "involvement in a given event" for a contact : we consider a contact to be involved in an event if both the person corresponding to the contact AND the case linked to the contact are involved in this event. Am I right ?

To me we should us these conditions instead:
- The additional constrain that the case (source case or resulting case) must be linked to the event is not needed for contacts.
- We consider a contact to be involved in an event if the person uuid referenced by the event participant == person uuid of the contact person. If the contact resulted to a case, then the uuid of the case person is by default the uuid of the contact person.
- In the case directory, we need this condition: We consider a case to be involved in an event if the person uuid referenced by the event participant == person uuid of the case person.

**Comment by bernardsilenou** [comment]
with example 1, filter on event 1 returns no contacts **(good)**, filter on event 2 returns no contacts **(I think this should return contact 1)**
with example 2, filter on event 1 returns contact 1, filter on event 2 returns no contacts  **(ok)**

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset

What would be expected, accordingly to our discussion last wednesday, is that a contact is listed in the contacts of an event if (and only if) the person of the source case was also involved in the event

**Comment by bernardsilenou** [comment]
@ftavin II think I may heave not understood this conclusion in the last meeting. I do not think we should only limit to contacts whose source case is also in the event as the default filter. We can use the default as all contacts and add the second filter for "only contacts with source case in event"

**Comment by ftavin** [comment]
@bernardsilenou of course, this could be done that way
@carolinverset what do you think about this proposition ?

**Comment by ftavin** [comment]
@bernardsilenou 's suggestions were validated during today's meeting with @carolinverset 

@bernardsilenou, @carolinverset  can you add fr label to this issue too ? thanks !

**Comment by ftavin** [comment]
@MateStrysewske : @alexandre-gille is working on this issue
