### ISSUE TITLE
Inform Climedo about changes in person data

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#2925]
### Situation Description

Right now, data about a person is only fetched once by climedo when a new patient (which relates to a contact person in SORMAS) is created. It may happen, that person data is updated afterwards. In such cases, climedo is to be informed about that.
This may be relevant if, for example, the emailaddress is first mistyped in SORMAS, and then corrected.

### Feature Description

This feature has to be properly defined first. It might make sense to use the SymptomJournalStatus variable defined in #1970 , so that SORMAS knows about which persons climedo needs to be kept up to date. 

- What should happen if the contact is converted to a case?

- Climedo might provide a PUT-Interface for updates in person data. How does this eventually look like?

- About what changes in person data should SORMAS inform climedo? One reasonable answer would be: about changes in any data so far transmitted to climedo. At the state of this writing, that would be firstname, lastName, birthDate, phoneNo, eMail, sex (and Uuid, which should never change). Planned is to also send followUpEnd dates.

**Comment by FredrikSchaeferVitagroup** [comment]
There are updates on the exchange protocol.
![image](https://user-images.githubusercontent.com/67001822/94110569-1d88f400-fe43-11ea-9a63-e676a31364dd.png)
The data update request will be empty because as we agreed, once climedo receives it, it will fetch the person data with the GET for personal data in the [ExternalVisitsRessource ](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-rest/src/main/java/de/symeda/sormas/rest/ExternalVisitsResource.java) for now.

**Comment by vlad-ciucescu** [comment]
Implementation is done, but waiting on CLIMEDO side to update their auth API/ implementation to handle updating person data. Afterwards we will also test our implementation and close this.

**Comment by vlad-ciucescu** [comment]
We are nou able to authenticate in CLIMEDO, notify them about changes in relevant person data and get a response after they updated their data.

**Comment by vlad-ciucescu** [comment]
@AndyBakcsy-she this is a backend-only story in SORMAS, changes may only be seen in the CLIMEDO UI. They haven't completely finished implementing their side.
