### ISSUE TITLE
Regional District/community filters do not turn active after selecting a Region. Apply Filters button has to be clicked explicitly every time.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2933]
### Bug Description
The district/community filter is inactive/disabled after selecting a region.
It is active only after clicking on Apply filters.

### Steps to Reproduce
1. Login to Sormas as Lab officer/ National User
2. Select Samples Directory
3. From the filters available on top, select the "Responsible region" filter and pick a region.
4. See if the district filter next to it is turned active and is selectable.

### Expected Behavior
The district/community filters must be active after selecting a region without the need of clicking on Apply filter.
 
### Screenshots
![District filter not active unless clicked on apply filters](https://user-images.githubusercontent.com/62763628/93789996-d1676500-fc32-11ea-8094-b07a51825bed.PNG)

### System Details
* Device:
* SORMAS version: 1.49.0
* Android version/Browser:

### Additional Information
User has to click apply filter multiple times to choose different region filters.
An example is shown above in screenshots, but this issue is everywhere on the application where the regional filters are present.

**Comment by MateStrysewske** [comment]
- [ ] Changing the region (for example) adds the districts of the newly selected region to the district dropdown, but doesn't remove the districts of the formerly selected region

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.49.0-SNAPSHOT
