### ISSUE TITLE
 Campaign data aggregation view [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#2937]
### Situation Description
Campaign form data can be entered into the system, but currently only seen in a list view or visualized on the dashboard.

### Feature Description
In addition to the dashboard visualization, we also need a table view that aggregates the entered campaign form data for a campaign by a jurisdiction (e.g. by cluster as in the screenshot below)

E:g. this would mean that for number fields the sum is calculated and for yes/no fields the number of yes values.

- [x] Add a new view to the campaigns section between "campaign data" and "campaigns" that should be called "campaign statistics"
- [x] User the same filters as user in campaign data
- [x] No "import" and "new form" buttons
- [x] Add "grouping" field with the following options: area (AF: region), region (AF: province), district, community (AF: cluster). Default value should be area.
- [x] The data is grouped by campaign, form and the grouping jurisdiction selected by the user
- [x] Display the columns as in the table below. When grouped by area or region, also show the area column
- [x] count the number of forms for each group
- [x] show all numbers fields of the forms. Summarize the total number for the grouping
- [x] show all yes/no fields of the forms. Display the number of "yes" answers
- [x] allow the user to export the shown data

Implementation suggestions:

- [x] Do all grouping and counting directly in an SQL statement. Otherwise the performance will be too bad to work with real data
- [x] Use lazy loading
- [x] Use a new dto that contains the fixed fields (campaign, form, area, region, district, community, form count) and an object array that contains the aggregated data for the custom fields

![grafik](https://user-images.githubusercontent.com/23217632/98945428-cb835700-24f2-11eb-8761-de6052c2ad63.png)

**Comment by StefanKock** [comment]
Removed milestone, since this ticket is not mandatory for 1.58
