### ISSUE TITLE
Link event error when no event exists for case disease

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#2938]
### Steps to Reproduce
1.GoTo case detail
2. Make sure there is no event with the case disease
3.Link an event
4.An error message is displayed

### Expected Behavior
Event creation form should be displayed

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.49.0-SNAPSHOT
Event Form is displayed and the process works as expceted
