### ISSUE TITLE
Error at Custom date filter for current month on Dashboard contacts. - Swiss only

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#2944]
### Bug Description
On Swiss servers, when a custom date filter is selected and current month is selected as range, an error is displayed.

### Steps to Reproduce
1. Login to Sormas at https://sb-ch.sormas.netzlink.com/ as national user
2. Select Dashboard and click on contacts on the top right corner.
3. Select the filter on the left and choose Custom.
4. Select "By Date" and From date as Start of the month(1 Sep)  and To date as "Current date"  and Apply custom filter.
5. Click on Apply Filters and see if the changes are sen without any errors.

### Expected Behavior
There should be no errors displayed when the custom filtering is done.

### Screenshots
![Error at contacts custom filter - Swiss only](https://user-images.githubusercontent.com/62763628/93900995-5798af80-fcf6-11ea-9269-9cb57e5dcae8.PNG)

### System Details
* Device:
* SORMAS version: 1.49.0 - Swiss instance
* Android version/Browser:

**Comment by MateStrysewske** [comment]
@raghupola-vg If this only happens on the system you've tested it on and can't easily be reproduced on our dev systems, we'll need error logs.

**Comment by sergiupacurariu** [comment]
the issue comes from the fact that I did not consider "Quarantine start" could be blank.

**Comment by AndyBakcsy-she** [comment]
verified this issue on the same environment on SORMAS Version: 1.49.0-SNAPSHOT
Moving the issue to the Done lane as it is unreproducible anymore
