### ISSUE TITLE
New form for epidemiological data [8]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2946]
### Feature Description
[EPIC] Epidemiological data refinement #2688
### Proposed Change
Assuming that the preexisting epidemiological data tab will be reworked, the following is needed to create a refined epidemiological data tab:

**Exposure investigation:**
This section answers questions regarding the exposure of the case/contact during the incubation period, starting off with an option to select whether or not details of exposures are known. When "yes" is selected, an entry option for exposure details should appear that depicts a list of all entered exposure details. New entries should be able to be added at the top right of the list. Clicking "new entry" should open an entry mask.

Entry mask:
- Here, exposure date and a description should initially be added, followed by selection options of activities. These are separated into drop down menus describing the type of activity, broken down into further options and free text fields. In the "Details", multiple selections should be possible. When selecting "Contact to a positively tested case", drop down options should appear that represent the entered source cases names in "Source Case: Contact Data". This is only applicable for the cases entity. Finally, the location of the exposure and the type of place should be specified. The country drop down menu should display such country at the top, that the SORMAS instance belongs to. When selecting "airplane" ("flight") as the type of place, flight information should be added in additional fields.

Find the extended facility types list for "type of place (setting) below (referenced in #1637, Maté's comment, Jun 24).

Refer to mappings and migrations here:
Type of place in exposure details entry mask #2947
Replace gatherings with exposure (subsequently to be merged with travels) #2948
Data migration of epidemiological data #2949

General indicators of exposure are given in selection options below the exposure details. These should be visible independent of the details above (i.e. if no is selected). Here, general indicators can be added as a questionnaire for the user.

**Source case: Contact data**
This section allows to draw connections between cases, which hasn't been possible before, and should therefore only appear in the epi data tab of cases. Here, "contact data" describes the instance of the contact itself (i.e. the exposure to other cases). If the contact to the source case is known ("yes" was selected), a list should appear where all the details of contacts to the source case can be added.

Entry mask:
- The entry mask opening here should be the same one as for the creation of new contacts. This follows the logic that every case has initially been a contact to the source case. The connection between cases (case has been chosen here) is being drawn in the background, therefore, the user should not be redirected to the contact entity but stay on the epi data form.
### Additional Information
[EpiDataMockUp_201006.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/5337213/EpiDataMockUp_201006.pdf)
[Migration_Epidemiological.data_GaPo_20200611_jdo_bsi.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5278675/Migration_Epidemiological.data_GaPo_20200611_jdo_bsi.xlsx)

Also find which options should be shown per disease on the new epi data tab here:
[Epi data all diseases_GaPo_kwa_201006.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5337231/Epi.data.all.diseases_GaPo_kwa_201006.xlsx)

**Comment by bernardsilenou** [comment]
@kwa20 This is good explanation. We discuss the contact later please, i have a question

**Comment by bernardsilenou** [comment]
@kwa20 The updated mock is good. I have this minor comment at the "source case contact data" section. 
When users click on new, we directly open the contact creation form, while in the form, they can then choose the source case or create a contact without one. System should prefill this form with the case person meta data

![image](https://user-images.githubusercontent.com/12996724/94204376-6bdcd800-fec1-11ea-926d-e688dd0040ac.png)

**Comment by GabrielePoggensee** [comment]
Change the following value (expressed as risk)/add values

Change " > 1,5 m" in "less than 1,5 m" 

Add
- more than 15 min face-to-face contact
- contact to a laboratory confirmed  COVID-19 case

![image](https://user-images.githubusercontent.com/68693446/94233662-86866f80-ff08-11ea-83e7-243f12dc3f87.png)

**Comment by GabrielePoggensee** [comment]
Add
- Other protective measures. 
If yes, then free text field

**Comment by markusmann-vg** [comment]
out of scope: Sourve tracing (see Source Case: Contact Data in the mockup)
We should treat that with issue #389

**Comment by markusmann-vg** [comment]
@Candice-Louw Please provide the list of countries, which should be included here (What lists do we use for International, Switzerland, Germany?)

**Comment by GabrielePoggensee** [comment]
Germany: country list of the RKI
CH: country list of BAG
Internatinal: country list of WHO (is mentioned in issue #2688)

**Comment by bernardsilenou** [comment]
list of countries
https://www.who.int/data/gho/data/countries

**Comment by Candice-Louw** [comment]
CH | Switzerland | BAG - Risk areas (14.09.2020) 

https://www.bag.admin.ch/bag/de/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/empfehlungen-fuer-reisende/quarantaene-einreisende.html

(en)
Albania
Andorra
Argentina
Armenia
Aruba
Austria
Bahamas
Bahrain
Belize
Occupied Palestinian Territory
Bolivia
Bosnia and Herzegovina
Brazil
British Virgin Islands
Cabo Verde
Chile
Costa Rica
Dominican Republic
France
Gibraltar
Guyana
Honduras
India
Iraq
Israel
Qatar
Colombia
Kosovo
Croatia
Kuwait
Lebanon
Libya
Maldives
Malta
Moldova
Monaco
Montenegro
Namibia
North Macedonia
Panama
Paraguay
Peru
Romania
San Marino
Sint Maarten
Spain
Suriname
Trinidad and Tobago
Czech Republic
Turks and Caicos Islands
Ukraine
United Arab Emirates
United States of America (including Puerto Rico, U.S. Virgin Islands, and Guam)

---

**Comment by bernardsilenou** [comment]
> out of scope: Sourve tracing (see Source Case: Contact Data in the mockup)
> We should treat that with issue #389

This new epi data tab has 2 main sections: exposures and contact.
The contact part is technically the source tracing for retrospective contact creation.

**Comment by kwa20** [comment]
I have included an updated version of the mock-up and an excel sheet describing which options should be shown per disease.

**Comment by markusmann-vg** [comment]
out of scope:
countries as they will follow

**Comment by MateStrysewske** [comment]
* Migration addition: Set "Contact to source case known" to yes for every case that is the resulting case of at least one contact

**Comment by Iheanacho2027** [comment]
@bernardsilenou pls kindly remember to include #2585 in this refinement as promised. Thanks

**Comment by MateStrysewske** [comment]
@Iheanacho2027 The new epi data form will have a lot less Yes/No/Unknown fields, so #2585 shouldn't be necessary anymore

**Comment by MateStrysewske** [comment]
- [ ] Disease should not be editable when creating a source contact
