### ISSUE TITLE
Type of place details in events entities [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2947]
### Feature Description
[EPIC] Epidemiological data refinement #2688
New form for epidemiological data #2946
### Problem Description

(...) please find facility descriptions in the attached file.
### Additional Information
[Epidemiological.data_type.of.place_200920.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5263433/Epidemiological.data_type.of.place_200920.xlsx)

**Comment by markusmann-vg** [comment]
We should not implement another type of place but use the same type of place which we have in the events section.

**Comment by bernardsilenou** [comment]
@markusmann-vg The settings under the current event entity is not our final goal. We had to halt the implementation in order the first complete the facility implementation. It will be better to just use the exact categories of event now and later refine the type of place variable. If we program point 1 and 2, you mentioned above, we then have to take them out again in the next sprint.
Do you agree with this also?

**Comment by bernardsilenou** [comment]
We can implement this in the next sprint

**Comment by Candice-Louw** [comment]
MED - Epi Data

Assuming implementation of: 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2946
and
https://github.com/hzi-braunschweig/SORMAS-Project/issues/2947,
additional values (https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/36) need to be introduced for the CH MED.

---

To fulfill this, in the entry mask (exposure details), the following appears for "Type of Place":
Variable mapping CH BAG MED - 

Sequence     /Reihenfolge | Name | Ortstypen (für Angabe      bekannter oder möglicher   Expositions- bzw. Infektionsorte) | Types of places (for information   on      known and possible sites of exposure |  | SORMAS var
-- | -- | -- | -- | -- | --
31 | other_exp_loc_type_yn | andere (Details im unteren Feld angeben) | Other (specify details in the field below) |  | ?
29 | other_exp_loc_type_yn | sonstige Freizeitaktivität draussen | Other outdoor leisure activities |  | ?
30 | other_exp_loc_type_yn | sonstige Freizeitaktivität drinnen | Other indoor leisure activities |    | ?
3 | exp_loc_type_work_place | Arbeitsplatz (falls untere Kategorie zutrifft, diese bevorzugen) | Workplace (if lower category applies, prefer this one) |    | ?
27 | exp_loc_type_army | Armee, Zivilschutz | Army, civil defence |    | ?
28 | exp_loc_type_asyl | Asylzentrum | Asylum Centre |    | ?
4 | exp_loc_type_club | Club / Bar | Club / Bar |    | ?
1 | exp_loc_type_hh | Eigener Haushalt | Household |    | ?
22 | exp_loc_type_shop | Einkaufen (Läden/Markt) | Shopping (Shops / Market) |    | ?
21 | exp_loc_type_massage | Friseur, Massage o.ä. | Hairdresser, massage or similar |    | ?
8 | exp_loc_type_high_school | Hochschule / Sekundarstufe II / Weiterbildungsstätte | University / secondary level II / further education institution |    | ?
16 | exp_loc_type_hotel | Hotel oder andere Unterkunft | Hotel or other accommodation |    | ?
2 | exp_loc_type_gathering | Im Haushalt von Freunden / Familie | In the household of friends / family |    | ?
20 | exp_loc_type_child_home | Kinderheim, Behindertenheim | Children's home, home for the disabled |    | ?
23 | exp_loc_type_cinema | Kino / Theater / Konzert | Cinema / theatre / concert |    | ?
6 | exp_loc_type_childcare | Krippe | Nursery |    | ?
18 | exp_loc_type_medical | medizinische Versorgung (Spital, Arzt etc) | Medical care (hospital, doctor etc) |    | ?
7 | exp_loc_type_school | Obligatorische Schule / Kindergarten | Compulsory school / kindergarten |    | ?
19 | exp_loc_type_nursing_home | Pflege- / Altersheim | Nursing / old people's home |    | ?
26 | exp_loc_type_erotica | Prostitutionsdienste | Prostitution Services |    | ?
14 | exp_loc_type_flight | Reise Ausland (inkl. Flug o.Ä.) [open "Flights"   mask] | Travel abroad (incl. flight or similar) [open "Flights" mask]. |    | ?
15 | exp_loc_type_flight | Reise Schweiz | Travel Switzerland |    | ?
24 | exp_loc_type_religion | Religiöses/Beerdigungen | Religious/funerals |    | ?
5 | exp_loc_type_restaurant | Restaurant | Restaurant |    | ?
17 | exp_loc_type_school_camp | Schul- oder Ferienlager | School or holiday camp |    | ?
10 | exp_loc_type_outdoor_sport | Sport im Freien | Outdoor sports |    | ?
11 | exp_loc_type_indoor_sport | Sport in der Halle | Sport in the hall |    | ?
12 | exp_loc_type_less_300 | Veranstaltung / Feier < 300 Pers. | Event / Party < 300 Pers. | include freetext  | ?
13 | exp_loc_type_more_300 | Veranstaltung / Feier > 300 Pers. | Event / Party > 300 Pers. | include freetext  | ?
9 | exp_loc_type_choir | Verein (ohne Sport) | Club (without sport) |    | ?
25 | exp_loc_type_zoo | Zoo, Gärten | Zoo, Gardens |    | ?
28 | exp_loc_type_prison | Justizvollzugsanstalt | Prison |    | ?

**Comment by markusmann-vg** [comment]
Type of place details in Exposure will be done in https://github.com/hzi-braunschweig/SORMAS-Project/issues/2946

**Comment by markusmann-vg** [comment]
@Candice-Louw:
Please check with @GabrielePoggensee  the facility list that we have for Germany as this is based on the RKI and how we could proceed there (In best case we can achieve this with just translations)
If other facility types are needed we have to discuss how we want to proceed. One possibility is that we - based on the locale - we change the enums. 
However this is another good example, why they should have their own fork!

**Comment by markusmann-vg** [comment]
In Scope for this story:
We extend the "type of place" with the things that are needed like, for example
flight number, flight date, seat number when flight was selected

- [ ] We add the enums for "means of  transport"

We implement new fields for
- [ ] means of transport =>Aircraft (entry mask aircraft/flight), Ship/ferry, Train, Bus, Other => Free text
- [ ] when means of transport is selected then show number, date, seat number

**Comment by MateStrysewske** [comment]
MeanOfTransport is already present; only "Other" is missing, will be added in #2948

**Comment by MateStrysewske** [comment]
- [ ] New fields also need to be added to the app

**Comment by raghupola-vg** [comment]
Seat number is removed on web app.
Mobile app has the new fields.
Verified on Test environment
