### ISSUE TITLE
Migrate burials, gatherings and travels to exposures [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2948]
### Feature Description
[EPIC] Epidemiological data refinement #2688
### Proposed Change
Since the epidemiological data tab will experience a heavy rework, data previously entered under gatherings and travels will have to be migrated to the activity section in the exposure details list. Entry options for gatherings and travels will now appear in the drop down menu for the type of activity.

relevant mappings can be obtain in the attached documents for gatherings and travels respectively.
### Additional Information
[Mapping.for.travelled.outside.of.district.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5263466/Mapping.for.travelled.outside.of.district.docx)

[Data.mapping.for.social.gathering.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5263469/Data.mapping.for.social.gathering.docx)

[Epidemiological.data_mapping.old.data (1).docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5283812/Epidemiological.data_mapping.old.data.1.docx)

**Comment by bernardsilenou** [comment]
@markusmann-vg  Just fro clarification: 
This issue is not a stand alone issue but further explanation of the migration concept of #2688.

**Comment by bernardsilenou** [comment]
@markusmann-vg  I discussed with Kay and updated this issue. It is about migration of all the variables found in the epi data for covid. Other diseases can stay as they are for now.
The tab for gathering and travels are the same for all diseases, so can be replaced bu the newly introduced evetn entity for all diseases.

**Comment by MateStrysewske** [comment]
* Create a new entity called Exposure and migrate Burials, Gatherings and Travels
* Exposures linked to the epi data of a case have a list of contact UUIDs that define the contacts that took part in this exposure; store this as JSON
* UI: The list of exposures gets a column with the number of contacts linked to them; clicking on a row in that column automatically filters the list of source contacts
* UI: The list of source contacts also gets a column with the UUID of the exposure it's linked to, clicking on a row in that column will highlight the exposure in the list of exposures
* List of source contacts should be directly beneath the list of exposures

**Comment by markusmann-vg** [comment]
> @markusmann-vg I discussed with Kay and updated this issue. It is about migration of all the variables found in the epi data for covid. Other diseases can stay as they are for now.
> The tab for gathering and travels are the same for all diseases, so can be replaced bu the newly introduced evetn entity for all diseases.

Hi Bernard, this is not the way how we should proceed. We need to do it for every disease or we cannot won't do it as it would be like hiding the trashbin behind a shelf.

**Comment by bernardsilenou** [comment]
@markusmann-vg This is done now.

**Comment by markusmann-vg** [comment]
linked to https://github.com/hzi-braunschweig/SORMAS-Project/files/5337213/EpiDataMockUp_201006.pdf

**Comment by MateStrysewske** [comment]
- [ ] Add changeDate = 0 condition to migration script in app
