### ISSUE TITLE
Data migration of epidemiological data [8]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2949]
### Feature Description
[EPIC] Epidemiological data refinement #2688

Migration of non list fields in epi data

### Proposed Change
Since the epi data tab experiences a rework, old data will have to be migrated.

Please find the mapping in the attached file.
### Additional Information
[Epidemiological.data_mapping.old.data.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5263476/Epidemiological.data_mapping.old.data.docx)
[SORMAS_International_Epidemiological data_mapping_201004.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5339147/SORMAS_International_Epidemiological.data_mapping_201004.docx)

**Comment by markusmann-vg** [comment]
[Migration_Epidemiological.data_GaPo_20200611_jdo_bsi.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5282065/Migration_Epidemiological.data_GaPo_20200611_jdo_bsi.xlsx)

**Comment by markusmann-vg** [comment]
This issue is not ready for implementation as it describes ONLY Covid-19 (Germany / Switzerland)

Please provide Migration-Concept for ALL the diseases and not for COVID-19 only.

**Comment by bernardsilenou** [comment]
I have combined this issue with @2948
@The migration concept for all the disease will be complex to manage in a single issue, so we do disease by disease.

**Comment by MateStrysewske** [comment]
@bernardsilenou It actually makes sense to separate this into two issues from a development point of view.

**Comment by markusmann-vg** [comment]
Please discuss with HZI SORMAS International, as we have to have a migration concept for ALL available data, which can be found in the epidemiological data section and how they can be mapped to the new concept. 
Remark:
Cases can have several exposures, contacts just one exposure

**Comment by kwa20** [comment]
I have included the mapping for SORMAS international above.

**Comment by markusmann-vg** [comment]
- [ ] Create new fields 
- [ ] Migrate old data
- [ ] Clean up

**Comment by bernardsilenou** [comment]
@markusmann-vg cases and contacts can have several exposures in the epi data tab (upper section).
In the epi data tab  for a contact, the lower section on contact information is not shown since it is the contact itself. For cases, we show all contacts that have resulted to the case

**Comment by MateStrysewske** [comment]
Mockup: https://github.com/hzi-braunschweig/SORMAS-Project/files/5337213/EpiDataMockUp_201006.pdf

**Comment by MateStrysewske** [comment]
Open question: How should the exposures be exported? A lot of information that was directly inside the epi data before will now be part of the exposures; should we just export information about all exposures? If yes, which fields are relevant for the export? How should this be formatted?

**Comment by bernardsilenou** [comment]
My suggestion:
For detailed case and contact export, we do not export the exposure entity itself but just the individual  disease specific variables  on the epi data tab, eg  
exposure = yes/no/ unknown
contacts: tes no unknown
post exposure prophylaxis = yes not  unknown
If users need the full exposure entity, then they need to do db export

**Comment by bernardsilenou** [comment]
We can use the same variables and variable order as in detailed case export. We can then do additional export specification when the new epi data design  is all working well

**Comment by MateStrysewske** [comment]
Automatic case classification needs to be adjusted.

**Comment by bernardsilenou** [comment]
That is true Maté, 
We can migrate any epi data variable needed for case classification (eg "epidemiological confirmation") to "exposure details know" == yes OR contact with source case known == Yes

**Comment by MateStrysewske** [comment]
There's no way to properly migrate information associated with having contact to a specific type of case, e.g. contact to confirmed case or contact to probable case, because we can't create source cases for these contacts. Because of that, these variables will remain part of the epi data as individual YesNoUnknown fields.

**Comment by bernardsilenou** [comment]
@MateStrysewske since we do no longer want to collect data on these variables in future, what  about migrating  both variables: contact to confirmed case or contact to probable case to "contact with source case known" == yes, But with no entry in the the table "details of contact with source case known".
Keeping all 3 variables: "contact to confirmed case" or "contact to probable case" and "contact with source case known"  seem very similar

**Comment by MateStrysewske** [comment]
@bernardsilenou Can you confirm that none of the countries that are using SORMAS right now need these variables anymore and that they're all fine with losing the data for all existing cases in the database?

**Comment by MateStrysewske** [comment]
- [ ] Disease should not be editable when creating a source contact

**Comment by StefanKock** [comment]
Migration script does not work, blocker issue.

**Comment by MateStrysewske** [comment]
- [ ] Detailed export fails when there is an exposure with type burial where one of the Yes/No values is set
