### ISSUE TITLE
Detailed case and contact exports are missing the community for the person address [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2950]
### Bug Description
The community of the person address is missing in the detailed cases and contacts exports. 
### Steps to Reproduce
1. Go to cases and contacts and conduct detailed exports.
2. Check for the community column in the exported files.

### Expected Behavior
Exports should include a column containing the community of the person address.
Also include this in the custom case export.
### Screenshots
<img width="784" alt="Screen Shot 2020-09-22 at 10 37 31 PM" src="https://user-images.githubusercontent.com/70317594/93936469-89296f00-fd26-11ea-9c47-c6bf1605daf1.png">
<img width="1008" alt="Screen Shot 2020-09-23 at 9 33 56 AM" src="https://user-images.githubusercontent.com/70317594/93981430-4300f980-fd80-11ea-93a2-8471ebcf59e8.png">

### System Details
* Device:
* SORMAS version: 1.48.2
* Android version/Browser: Chrome

**Comment by kwa20** [comment]
This is now also true for the introduced event participant detailed export.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
