### ISSUE TITLE
Cases > Minimal Essential Data (MED) for Switzerland [3]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2959]
### Situation Description
In order to fulfill the Minimal Essential Data (MED) requirement for the BAG in Switzerland, additional fields and variables need to be introduced to SORMAS: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/102

This is part 1.  Part 2 is for CONTACTS: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2960

### Feature Description

The following is required for CASES:

NOTE:
In the Swiss context-
Cases go into Isolation
Contacts go into Quarantine

---

1. 
Cases > Open Case > Case Information:

New field (CH only) -
"Case-ID ISM" (en) | "Fall-ID ISM" (de-CH)
Next to or under the existing "External ID" field.
Data Type: Integer

---

2.  
Cases > Open Case > Case Information:

New field (CH only) -
"Reason for COVID-19-Test" (en) | "Grund für COVID-19-Test" (de-CH)
Data Type: Dropdown/enum
Values (en | de-CH):
- Presence of symptoms | COVID-19-Test durchgeführt aufgrund von Symptomen.
- Screening during outbreak investigation | COVID-19-Reihentest im Rahmen einer Ausbruchsuntersuchung.
- Cohort Screening | COVID-19-Test durchgeführt aufgrund eines COVID-19-Kohorten-Screenings.
- Requirement of employer | COVID-19-Test durchgeführt auf Wunsch des Arbeitgebers.
- During quarantine, as requested by the Canton | COVID-19-Test durchgeführt während der Quarantäne auf Wunsch des Kantons.
- After first contact with Contact Tracing (already symptomatic) | COVID-19-Tests durchgeführt nach Erstkontakt mit klassischem Contact Tracing (bereits symptomatisch).
- Due to SwissCovidApp notification | COVID-19-Tests durchgeführt aufgrund einer SwissCovidApp-Meldung.
- Other reason | Anderer Grund für den COVID-19-Test

If "Other reason | Anderer Grund für den COVID-19-Test" > Display free-text field.

---

3.  
Cases > Open Case > Case Information:

(All CH only)

New section/heading -
"First contact with Contact Tracing" (en) | "Erstkontakt mit kantonaler Contact-Tracing-Stelle" (de-CH)

New field -
"Type of contact" (en) | "Art des Kontaktes" (de-CH)
Data Type: Drop-down/enum
Values: Telephone, SMS, E-Mail

New field -
"Date of Contact" (en) | "Datum des Kontaktes" (de-CH)
Data Type: Date

---
4.  Cases > Open Case > Case Information:

=> https://github.com/hzi-braunschweig/SORMAS-Project/issues/2977

5.  
Cases > Open Case > Case Information:

New field (CH only) -
"Reason why the case was in quarantine before this isolation." (en) | "Grund weshalb der COVID-19-Fall vor der Isolation in Quarantäne war." (de-CH)
Data Type: Dropdown/enum
Values (en | de-CH):
- Identified by contact tracing | Identifiziert durch klassisches Contact Tracing
- Entry from risk area | Einreise aus Risikostaat
- SwissCovidApp notification | SwissCovidApp-Meldung
- Other reason | Anderer Grund

If "Other reason | Anderer Grund" > Display free-text field.

---

6.
Cases > Open Case > Case Information:

New field (CH only) -
"Reason for end of isolation" (en) | "Grund des Ende der Isolation" (de-CH)
Data Type: Dropdown/enum
Values (en | de-CH):
- Recovered | Genesung
- Died | Tod
- Lost to Follow-up | Lost to Follow-up
- Other | Anderer

If "Other | Anderer" > Display free-text field.

---

7.

Berufsgruppen / occupations

=> https://github.com/hzi-braunschweig/SORMAS-Project/issues/2978

8.
Cases > Open Case > Case Information > Quarantine field

=> https://github.com/hzi-braunschweig/SORMAS-Project/issues/2977

---
9.
Location Adjustments

=> https://github.com/hzi-braunschweig/SORMAS-Project/issues/2979

**Comment by markusmann-vg** [comment]
I assigned it to the Interactions team as this is a prerequisite for the full export into the Swiss System

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
