### ISSUE TITLE
Contacts > Minimal Essential Data (MED) for Switzerland [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2960]
### Situation Description
In order to fulfill the Minimal Essential Data (MED) requirement for the BAG in Switzerland, additional fields and variables need to be introduced to SORMAS: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/103

This is part 2.

Part 1 is for CASES: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2959

NOTE:
In the Swiss context-
Cases go into Isolation
Contacts go into Quarantine

### Feature Description

The following is required for CONTACTS:

---

~~1.~~

~~Removed - will no longer be displayed.~~

---

2.
Contact > Open Contact > Contact Information:

New field (CH only) -
"Reason for end of quarantine" (en) | "Grund des Ende der Quarantäne" (de-CH)
Data Type: Dropdown/enum
Values (en | de-CH):
- Asymptomatic after 10 days | Asymptomatisch nach 10 Tagen
- Isolated as Case | Isoliert als Fall
- Lost to follow-up | Lost to follow-up
- Other | Anderer

If "Other | Anderer" > Display free-text field.

---

3.
Same as for Cases -->

Die Liste der Berufe muss angepasst werden.
Will be done with: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2978

---

4. 
Same as for Cases -->

For Contacts and Cases (Switzerland only) - adapt the field "Quarantine" (QuarantineType.X)
NEW values are introduced in the drop-down-menu: (en | de-CH):
Hospital | Spital
Hotel | Hotel
Asylum Accommodation | Asylzentrum

Will be done with: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2978

---

5.
Same as for Cases -->

Contact > Open Contact > Contact Person > Addresses

For the working place, place of exposure, place of event - the name of the company/institution/place of exposure or event needs to be documented.
New field:
“Address specification” for all values of address type.
Data Type: Free-text
It should be possible to filter according to this new “Address specification” field.

Will be done with: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2979

**Comment by markusmann-vg** [comment]
I assigned it to the Interactions team as this is a prerequisite for the full export into the Swiss System

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.50.0-SNAPSHOT
