### ISSUE TITLE
Allow resetting Yes/No and other OptionGroup fields to no value [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2963]
### Feature Description
OptionGroup fields allow users to select values like "yes", "no", etc.

### Problem Description
It's currently not possible to reset the field to no value.

### Proposed Change
Allow the user to click the value again (e.g. "yes") to un-select it.

**Comment by markusmann-vg** [comment]
By default you can reset the selection by clicking it again.
As there are some fields with dependencies, this option should be disabled (like home or facility)
others do not have a dependency like symptoms.

Check the settings of the option fields, where the NULL selection is not supposed to be allowed.

**Comment by ChristopherRiedel** [comment]
Only allow reseting when field isn't required.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
The functionality of changing the values of these fields works as expected and has been tested. One issue has been found but it does not require to reopen this issue.
This functionality was also verified on the Contact page as well

**Comment by MateStrysewske** [comment]
- [ ] The facility/home selector in cases doesn't work anymore. When opening a case, the field is not filled in and clicking on any of the values results in an exception. (sormas-ui)

**Comment by AndyBakcsy-she** [comment]
Another issue was logged for this problem  #3258

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT

**Comment by AndyBakcsy-she** [comment]
Verified issue on the latest SORMAS Version: 1.51.0-SNAPSHOT
