### ISSUE TITLE
Refactor field dependencies on grid filters [2]

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#2967]
### Feature Description
On directory pages the dependencies of filter fields are handled in two methods: `applyDependenciesOnFieldChange` and `applyDependenciesOnNewValue`.

It was designed to work with automatic form submit, but now with the new *Apply Filter* button it became too complicated.
### Problem Description
The code for applying dependencies between fields is too complicated and there are a lot of duplicated code. 
See `CaseFilterForm`

### Proposed Change
- [x] Eliminate duplicated code
- [ ] Make easier maintain the dependencies

**Comment by AndyBakcsy-she** [comment]
Validated the issue on SORMAS Version: 1.52.0-SNAPSHOT
 No new changes have been introduced with this fix.It seems everything is working as before.
