### ISSUE TITLE
Filters get automatically applied when you remove all the filters

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#2968]
### Bug Description
On directory pages when you remove the last filter the grid gets reloaded without clicking the apply button
### Steps to Reproduce
1. Go to Cases directory
2. Select a *Disease*
3. Click on *Apply Filters*
4. Select the empty line in the *Disease* combo to clear the value
 => the grid gets reloaded

### Expected Behavior
The grid should not reload until you click on *Apply Filters*
### System Details
* Device:
* SORMAS version:
* Android version/Browser:

**Comment by vlad-ciucescu** [comment]
Cannot reproduce anymore
