### ISSUE TITLE
Add facility related selection options to contacts and search option in directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#2970]
### Feature Description
Analogous to the case entity, add place of stay and related facility type entry options as **non**-compulsory fields to the contact information. Users should also be able to then search for facilities in the contact directory.
### Additional Information
<img width="719" alt="Screen Shot 2020-09-23 at 6 00 42 PM" src="https://user-images.githubusercontent.com/70317594/94040326-17563180-fdc9-11ea-8b8f-0cd2529c7b6b.png">
<img width="708" alt="Screen Shot 2020-09-23 at 6 13 40 PM" src="https://user-images.githubusercontent.com/70317594/94040352-1f15d600-fdc9-11ea-8189-b30ecb72c46f.png">
<img width="1067" alt="Screen Shot 2020-09-23 at 6 04 43 PM" src="https://user-images.githubusercontent.com/70317594/94040426-3bb20e00-fdc9-11ea-986e-158aaf8fd5e1.png">

**Comment by bernardsilenou** [comment]
@kwa20 I think when a contact reached the point were a facility is needed, then they should be converted to a case.
What is the motivation for adding facilities to contacts please?

**Comment by kwa20** [comment]
@bernardsilenou Under facility category and type we have several options where multiple people can in principle be accommodated. If a contact can be associated to a case through a facility, health departments would like to be able to select facilities and be able to search for them in the directory. These contacts might not be able to be converted yet since e.g. associated cases can still be under investigation. I think apart from that, contacts could also live in facilities (e.g. residence -> retirement home) and this selection might be nice as an addition to the address.

**Comment by markusmann-vg** [comment]
Place of stay or facilities to contacts can be added to the person and there it should be, so this story is obsolete.
