### ISSUE TITLE
Include "place of stay" in bulk edit [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2972]
### Feature Description
Bulk edit currently looks like this and only allows to assign cases to a facility:

![grafik](https://user-images.githubusercontent.com/23217632/94113326-05b36f00-fe47-11ea-8a41-ab29f12b843e.png)

### Problem Description

When adding the new "place of stay" field to the case this was not added to the bulk edit options

![grafik](https://user-images.githubusercontent.com/23217632/94113451-2da2d280-fe47-11ea-9739-46fc40f50aaa.png)

### Proposed Change

Include the place of stay field in the bulk edit form.

**Comment by danRosca** [comment]
The entity field in which the 'place description' is saved is pseudonymized when edited. It needs to be discussed how should the application handle this

**Comment by MartinWahnschaffeSymeda** [comment]
Discussed this with Markus. When the health facility details field (for an "other health facility" or for "home") becomes visible AND there is at least one pseudonymized case in the list of bulk edited cases, the user should see the following info (at least bold, ideally with a warning icon):

For <number of cases> of the bulked edited cases you have only limited access to the sensitive data. For those cases the value you put into "<name of field>" will be ignored.
