### ISSUE TITLE
Setup ga1 and test system environments with different systems to have it ready for showcases [8]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2976]
### Situation Description
Currently there is no enviroment on which the whole set of systems are running and can be presented:
- SORMAS with Keycloak
- Climedo
- PIA
- SurvNet

### Feature Description
When the 2 environments are setup, we can 

0. Login with keycloak and show the keycloak processes (like password forgotten) 
1. send and receive cases and contacts between 2 SORMAS instances (ga1 => ga2)

- [x] create keycloak & Sormas ReST-users and the pairing users on CLIMEDO and PIA

2. Create users for Climedo in SORMAS
3. Receive Symptoms from Climedo and display them in the contacts follow-ups in SORMAS
4. Create users for PIA in SORMAS
5. Receive Symptoms from PIA and display them in the contacts follow-ups in SORMAS
6. Show the status of the PIA user in SORMAS
7. Show with text (or icon) in the contacts follow-up when symptoms were sent by PIA or Climedo
8. Send a minimal dataset for cases from SORMAS to SurvNet and show on the survnet client, that the case was sent
(optional)
9. Integrate the IMIS functionality for the quarantine documents download (should be enableble by feature configuration)

**Comment by vidi42** [comment]
Waiting for #2844 or #2745 to be merged in development

**Comment by vidi42** [comment]
## Current status
When the 2 environments are setup, we can 

- [x] 0. Login with keycloak and show the keycloak processes (like password forgotten) 
- [x] 1. send and receive cases and contacts between 2 SORMAS instances
- [x] 2. Create users for Climedo in SORMAS
- [x] 3. Receive Symptoms from Climedo and display them in the contacts follow-ups in SORMAS
- [ ] 4. Create users for PIA in SORMAS
- [ ] 5. Receive Symptoms from PIA and display them in the contacts follow-ups in SORMAS
- [ ] 6. Show the status of the PIA user in SORMAS
- [x] 7. Show with text (or icon) in the contacts follow-up when symptoms were sent by PIA or Climedo
- [ ] 8. Send a minimal dataset for cases from SORMAS to SurvNet and show on the survnet client, that the case was sent
(optional)
- [x] 9. Integrate the IMIS functionality for the quarantine documents download (should be enableble by feature configuration)

**Comment by vidi42** [comment]
Outdated and most of the points are already covered
