### ISSUE TITLE
Change the list of occupations for Switzerland / Create Annotations for hide/show enums [3]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2978]
### Situation Description

For Switzerland only - type of occupation:

- [x] Do the mapping 

- [x] add the new fields to the enum 

- [x] Build the annotations for hiding/showing the enums for countries

Kategorie | de-CH (Verkürzte Bezeichnung ZH) | English
-- | -- | --
G | Handel; Reparaturgewerbe | G. Wholesale and retail trade; repair services
C | Verarbeitendes   Gewerbe/Herstellung von Waren | C. Manufacturing industry /manufacture of goods
F | Baugewerbe/Bau | F. Construction industry /building
H | Verkehr und Lagerei | H. Transport and storage
Q | Gesundheits- & Sozialwesen | Q. Health & social services
P | Erziehung & Unterricht | P. Education & teaching
I | Gastgewerbe/Beherbergung & Gastronomie | I. Hotels and restaurants /accommodation & gastronomy
R | Kunst, Unterhaltung & Erholung | R. Arts, entertainment & recreation
O | Öffentliche Verwaltung, Verteidigung; Sozialversicherung | O. Public administration and defence; social services/security
K | Finanz- & Versicherungswesen | K. Finance & insurance
J | Information & Kommunikation | J. Information & communication
M | Dienstleistung: freiberuflich, wissenschaftl., techn. | M. Service: freelance, scientific, technical
N | Dienstleistung: sonstige wirtschaftliche | N. Service: other economic activities
S | Dienstleistung: sonstige | S. Service: other
L | Grundstücks- und Wohnungswesen | L. Real estate and housing
D | Energieversorgung | D. Energy supply
E | Wasserversorgung; Abwasser- und Abfallentsorgung | E. Water supply; sewerage and waste management
U | Exterritoriale Organisationen & Körperschaften | U. Exterritorial organisations & bodies
A | Land- & Forstwirtschaft, Fischerei | A. Agriculture & forestry, fisheries
B | Bergbau & Gewinnung von Steinen/Erden | B. Mining & quarrying
T | Private Haushalte mit Hauspersonal | T. Private households with domestic staff

If possible - please display the values in this given order in the enum.

**AND**

For Contacts and Cases (Switzerland only) - adapt the field "Quarantine" (QuarantineType.X)
NEW values are introduced in the drop-down-menu: (en | de-CH):
- Hospital | Spital
- Hotel | Hotel
- Asylum Accommodation | Asylzentrum

### Additional Information
Please provide an updated list with the associated variable names that each value is mapped to so that this may be recorded by HZI and communicated to Netzlink.

**Comment by vidi42** [comment]
For more information https://www.kubb-tool.bfs.admin.ch/

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.50.0-SNAPSHOT

**Comment by Candice-Louw** [comment]
@vidi42 -> Pre-release walk-through and review with CH colleague @rafaelpaffenholz on 12.10.2020.

Request: If possible, please list first value in QuarantineType.X as "Home" as it would be used in 95% of situations and is easier to enter when it is the first value. (Is it possible to append the new Swiss-only values at the end of the list as opposed to the start?  If not, no problem - please just let me know so I may inform them.)

![image](https://user-images.githubusercontent.com/65529128/95838923-a9a38280-0d42-11eb-811b-15387edef30c.png)

**Comment by vidi42** [comment]
@Candice-Louw 
Updating the order of QuarantineType.Home to be the first one will change it for all server languages, but it can be done.
Also, sure, the Swiss only values can be added at the end of the list, but I think it makes sense to have None, Unknown and Other at the end of the list since those are very generic options.

So this is the order they will appear in:
HOME,
INSTITUTIONELL, - for CH only
HOSPITAL, - for CH only
HOTEL, - for CH only
ASYLUM_ACCOMMODATION,
NONE,
UNKNOWN,
OTHER;
