### ISSUE TITLE
Extend the person/Event address information [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2979]
### Feature Description

Cases > Open Case > Case Person > Addresses

9.1
Add new value to address type: “place of isolation” => for all servers

9.2
For the working place at person level, 
place of exposure and place of event

ENUM: Person.addressType

![Bildschirmfoto 2020-09-24 um 13 20 04](https://user-images.githubusercontent.com/62540178/94138801-f1806980-fe68-11ea-8f70-9b75918263b8.png)

the name of the company/institution/place of exposure or event needs to be documented. => for all servers

9.3
New field:
“Address specification” for all values of address type.
Data Type: Free-text
It should be possible to filter according to this new “Address specification” field.
@Candice-Louw Can you please provide an example and why not use additional information? We could also add a new filter for additional information. This filter will be added to case, contact and event directories

**Comment by Candice-Louw** [comment]
Using "Additional information" as proposed would work, thank you.

If possible: please place this at a more prominent position (as one would typically do when writing a letter).  This is to ensure that this field is not overlooked.

Example for "Place of Work":

![image](https://user-images.githubusercontent.com/65529128/95742252-fc703200-0c8f-11eb-99cb-526fe488a603.png)

The data will be used in the CH MED (original post: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/102) for the:

**Place of work details ("work_place_X")** - 
![image](https://user-images.githubusercontent.com/65529128/95744543-c3d25780-0c93-11eb-8a41-de4ba5e4d2c6.png)

**Place of Exposure/Event ("exp_loc_X")** -
![image](https://user-images.githubusercontent.com/65529128/95744841-4fe47f00-0c94-11eb-994d-b417e5205ee2.png)

**Place of Isolation ("iso_loc_X")** -
![image](https://user-images.githubusercontent.com/65529128/95744927-7efaf080-0c94-11eb-81d6-2f09d4e3473b.png)

For the country variables that are requested to be part of these variable sets, please see: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2994 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/2993

**Comment by bernardsilenou** [comment]
@Candice-Louw to me i suggest we keep the additional information at the end instead and give it more txt space just as the general comment field we have for cases. It sound good to ask for additional information after asking for all possible information.
What do you think about that?

@Candice-Louw @markusmann-vg  I do not understand what the users wish to obtain by implementing this issue. My wory is the fact that an address has a type as "place of isolation" or "place of exposure". 
We isolate cases, contact and event participants but not persons. So if a person has an address type "place of isolation", does that mean all associated entities of the person (cases (disease can be multiple), contacts, ...) were isolated at that location? If not, then how would the information be interpreted?

My thinking was that when we create a new exposure/ event and give any location to the exposure/ event, then that address is the address of exposure/ event which can in fact be a place of work, eg party at work. Similarly, If a case is isolated, then we ask for the location of isolation and infer it as the address of isolation wish can also just be the home of the case person.

**Comment by Candice-Louw** [comment]
@bernardsilenou - updated approach as discussed last week:

![image](https://user-images.githubusercontent.com/65529128/97988049-00055d80-1de5-11eb-873c-e14ebccb2cf1.png)

```Address Name/Description``` is introduced.
```Additional Information``` stays where it is.

---

### Additional Information

The new address types (place of isolation, place of exposure, place of work) are currently only visible on CH systems. 
 This is required for their Minimal Essential Data.

**Comment by markusmann-vg** [comment]
- [ ] Show AddressTypeDetails for all AddressTypes excluding AddressType "home""

- [ ] Caption for the field should be "Address name / description" to what is shown when it's "Other"

**Comment by raghupola-vg** [comment]
Newly added Address type is lost on the Mobile app when added and synchronized

**Comment by raghupola-vg** [comment]
Retested on the latest build and the app synchronization works fine.
