### ISSUE TITLE
Add area field to campaign data forms [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2982]
### Feature Description
Currently campaign data forms allow users to pick region (province), district and community (cluster).

### Problem Description
Afghanistan has over 30 provinces, so it would be good to pick the area first.

### Proposed Change

- [x] add area field to the campaign data form. Don't add it to the entity and dto!
- [x] allow the user to pick either the area or region first. When an area is picked, limit the regions to those of the area. When a region is picked, automatically select the area of the region
- [x] Don't show the field when INFRASTRUCTURE_TYPE_AREA feature is not enabled.

**Comment by AndyBakcsy-she** [comment]
verified issue on SORMAS Version: 1.50.0-SNAPSHOT
