### ISSUE TITLE
Add an icon to unlink cases from events

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#2984]
### Feature Description
When a case is mistakenly linked to the event, it is impossible to break this link without deleting the case. There are users who have retrospectively and linked cases to wrong events and are blocked from correcting this link. They can not also delete the case because it has been for long in the system and has many contacts
### Proposed Change
- Add a delete icon on the case form to break the association between the case and event 
- Add a description of what  this icon means when you hover the mouse on it : "Unlink this case as resulting from this event" (this is optional. We can also use an information box saying "Unlink event", by this way we need no description. This second option may not look good design wise since there is a pencil icon by the side)
- When users click on the unlink icon, show a dialog box saying "Are you sure you want to unlink this case from this event" : yes, no, cancel. 
- If yes, then break the link but maintain the case and event participant in their respective tables. This is a similar method that is called when the case associated to an event is deleted, but in this case, we do not delete the case that was initially set at resulting from event. 
- Please also hard delete the resulting case id on the event participant table or the other way round.
- Show a message saying "Case was was successfully unlinked from event"
### Possible Alternatives
- Will add more points soon, need to run

### Additional Information

![image](https://user-images.githubusercontent.com/12996724/94201290-18b45680-febc-11ea-915f-9eb38675fad5.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg This is urgent for us to implement in order to allow users clean up data

**Comment by carolinverset** [comment]
@ftavin it's up to you

**Comment by AndyBakcsy-she** [comment]
Verified on the latest version of sormas 1.58.0-snapshot
