### ISSUE TITLE
Import of countries should be possible [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#2993]
### Situation Description
Lists from RKI, BAG, WHO will be provided
From these examples we should create a template which can be imported as e.g. the facilities can be imported right now.

**Comment by markusmann-vg** [comment]
DE | Germany
Kopie von SurvNet3MetaPublikationCVD.xlsx

CH | Switzerland
do-d-14-ISO_country_code-2019_Länderliste.pdf

International
https://www.who.int/data/gho/data/countries

**Comment by markusmann-vg** [comment]
linked to https://github.com/hzi-braunschweig/SORMAS-Project/issues/2994

**Comment by markusmann-vg** [comment]
As a contracted we add:

DE | Germany
[SurvNet3MetaPublikationCVD.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5390673/SurvNet3MetaPublikationCVD.xlsx)
.xlsx

CH | Switzerland
https://www.bfs.admin.ch/bfsstatic/dam/assets/7626604/master (Ländercode BFS)

**Comment by markusmann-vg** [comment]
- [ ] Add country like we do it for regions
- [ ] Countries should also be translatable

@MartinWahnschaffeSymeda:
Please support the technical approach

**Comment by vidi42** [comment]
Country:
- ID
- code (ISO CODE 3)
- default name
- externa ID (ex. BFS code)
- UNO-code

Internationalization:
- translation files based on the ISO CODE 3

Import:
- trough CSV (similar to region)
- option to import full list of countries automatically

Add/Update UI for countries (similar to regions)

**Comment by MateStrysewske** [comment]
- [ ] Filtering by country does not work properly

**Comment by MateStrysewske** [comment]
- [ ] CountryResource is completely missing from sormas-rest which makes the Android app unable to synchronize any data with the backend
