### ISSUE TITLE
How to Capture additional Adresses in a case and get the column in the export?

### ISSUE THREAD

**Issue by SandroChristensen** [hzi-braunschweig/SORMAS-Project#2995]
Hello SORMAS Team

I work with SORMAS in Switzerland (Kanton Bern).
I would like to record the different exposures of a case. For that, I want to add these exposures as additional exposures in the case under cases -> case person -> adresses.

I have done that in the test version with a test data and now want to export this exposure, but I cannot find the subsequent column. Could you please help me? 

Best
Sandro

**Comment by MateStrysewske** [comment]
Hey @SandroChristensen, the addresses aren't meant to store exposures. These will be added to the epidemiological data of cases in one of the next sprints.

The list of addresses will be added to the detailed case export in the near future as well, but again, these aren't meant to store the data that you want to document.

**Comment by SandroChristensen** [comment]
Thank you for the quick Response @MateStrysewske

**Comment by SandroChristensen** [comment]
@MateStrysewske Can you tell me more about this sprint with the epidemiologcal data of cases? (maybe the link to the rigth GitHub discussion about it). I would like to inform me in more Detail about it.

Thanks and kind regards
Sandro Christensen

**Comment by MateStrysewske** [comment]
#2688 is the epic issue for all the tasks associated with rebuilding the epi data. It's a pretty big issue, but getting the exposures into the system will probably be one of the first tasks we'll take, potentially already in this sprint.
