### ISSUE TITLE
Cases and Contacts > Display "External ID" field [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#2996]
### Feature Description
The field for "External_ID" is visible on the `Cases > Open Case > Case` and `Contacts > Open Contact > Contact` tabs for DE systems only.

### Problem Description
These fields are requested for Switzerland at both Cases and Contacts (same setup as for DE).

### Proposed Change
Make "External ID" field visible for Cases and Contacts for CH configuration and include the column "External ID" in the Cases and Contacts overview tables.  If possible, please include this in the export (detailed/custom/db) too.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT
Validated the presence of the External ID for Cases and Contacts + the 2 exports

**Comment by MateStrysewske** [comment]
Needs to be added to the upcoming hotfix; what's missing is that the epid number should be hidden from Swiss systems as well.
