### ISSUE TITLE
Case Epidemiological data - fields are not aligned  

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#2998]
### Bug Description
The Fields on the Epidemiological data page should be aligned as they are on the Symptoms page
### Steps to Reproduce
1. Open a Case
2. Go to the Epidemiological Data page
3. Check the alignment of the fields

### Expected Behavior
All fields should be aligned 

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/94398414-2e50a700-016e-11eb-9b9b-b2316d0dec31.png)

### System Details
* Device:
* SORMAS version: SORMAS Version: 1.50.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/sormas-ui/#!about
* User Role: National User

**Comment by bernardsilenou** [comment]
No applicable anymore due to the new epi data interface
