### ISSUE TITLE
Replace createTable scripts in DatabaseHelper onUpgrade with proper table definitions

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3001]
### Bug Description
Updating the mobile app to latest available test version crashes the app.

### Steps to Reproduce
1. Make sure the device has version 49.0 snapshot of Sormas under Server (https://test.sormas.netzlink.com) and logged in user (SurvOff)
2. Open the mobile app and see that the new version is offered and available to download.
3. Click on download and install the version.
4. After the installation is complete, try launching the Sormas app

### Expected Behavior
The new version of Sormas should be accessible after updating and should not crash.

### Screenshots
![App crash after updatng to Version 50 0 snapshot](https://user-images.githubusercontent.com/62763628/94415326-b5f1e200-017d-11eb-8f33-c8888c676ea3.jpg)

### System Details
* Device: Samsung S 10
* SORMAS version: update from 49.0 to 50.0 snapshot
* Android version/Browser: 10
* Server URL: https://test.sormas.netzlink.com
* User Role: SurvOff

### Additional Information
adb logs attached.
[appcrash_Version49.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5291280/appcrash_Version49.txt)

**Comment by MateStrysewske** [comment]
Probably relevant part from the logs:

`09-28 11:16:51.595 I/am_crash( 1041): [24969,0,de.symeda.sormas.app,818429508,android.database.sqlite.SQLiteException,duplicate column name: quarantineReduced (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE contacts ADD COLUMN quarantineReduced boolean DEFAULT false;,SQLiteConnection.java,-2]`

**Comment by MateStrysewske** [comment]
Upgrading from 1.48.2 to 1.49.0 and 1.49.0 to 1.50.0-SNAPSHOT works fine on my dev system.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT updating from 1.49 to 1.50 on the mobile device. 
Updating the app worked as expected. 
The initial synchronization takes a long time on the other hand.(This might be a separate issue)

**Comment by faatihi** [comment]
Hi, all.

I've seen many similar issues.
They get closed without a lasting solution.
Ghana is now facing this issue.
We're upgrading from 1.42.3 to 1.56.1 (yeah, sorry, we're way back).

After digging into `DatabaseHelper.java`, I realized `TableUtils.createTable` is called (many times) in `onUpgrade`.
IMHO, this should not be allowed. This is because, the resulting table is non-deterministic.
The resulting table varies per the compiled version of the app.

An example is, let's say in version 1.43.0, a new entity (say, `Entity01`) is added.
`TableUtils.createTable` is then used to create the corresponding table in `onUpgrade`.
And then in version 1.45.0, we add a new column (say, `Age`) to the entity.
An `alter table add column` statement is then added in `onUpgrade`.

If an app is being upgraded from version 1.42.0 to 1.45.0, what then happens is;
From 1.42.0 to 1.43.0, the call to `TableUtils.createTable` results in our table already having the column, `Age`.
Then 1.43.0 to 1.44.0 upgrades successfully.
But then, 1.44.0 to 1.45.0 fails because we're trying to add a column that already exists.

**Comment by bernardsilenou** [comment]
@faatihi Thanks for the feedback, @MateStrysewske  would decide if we reopen the issue.

**Comment by MateStrysewske** [comment]
@faatihi I don't see a general problem with this because the DatabaseHelper only upgrades versions based on the current database version of the application, so it never executes a particular upgrade script twice. Do you have a specific example where this fails for you?

**Comment by faatihi** [comment]
Yes, it is clear that the DatabaseHelper doesn't execute a particular upgrade script twice.
But what happens is, some of the scripts create table that would already contain columns of future versions.

In Ghana's example, version 1.42.3 has version 207 of sqlite db version.
We're upgrading to 1.56.1 which is sqlite db version 274.
1. When DatabaseHelper upgrades, it runs scripts starting from 207.
2. But when it gets to 209, the script in this version has this line:
   `TableUtils.createTable(connectionSource, Event.class);`
   This means the table that is going to be created from above line will be up to date with db version 274.
   If the script had run a raw command like `getDao(Event.class).executeRaw("CREATE TABLE events ...")`,
   the resulting table will rightly be of db version 209.
3. Now, when it gets to 217, there's this statement:
    `getDao(Event.class).executeRaw("ALTER TABLE events ADD COLUMN pseudonymized boolean;");`
    It tries to add a column named `pseudonymized `.
    But remember version 209 already created a table that already includes this column
4. The app then crashes leaving an exception in the debug log:
   `error: duplicate column pseudonymized. statement: 'ALTER TABLE events ADD COLUMN pseudonymized boolean;'`

I hope I've explained the situation much better this time

**Comment by MateStrysewske** [comment]
@faatihi Aaah, yes, now I understand! That's indeed a pretty significant problem and I'm not exactly sure how we can fix that for the older app versions. The solution clearly is to not use `TableUtils.createTable` - even though that's way more comfortable - but to manually write the table definition as you've suggested, but this won't be possible retrospectively for older app versions anymore... I honestly don't know if there's another solution than uninstalling the app on your mobile devices and re-installing the latest version. I'll have a discussion with @MartinWahnschaffe about it though.

**Comment by faatihi** [comment]
Thank you, @MateStrysewske 

A little favor though; If I go through and rectify all instances of `TableUtils.createTable` in `onUpdate`, would you include it in an upcoming release?
I would be glad we do this, so the whole country doesn't have to stand still.

**Comment by MateStrysewske** [comment]
@faatihi We're currently discussing how feasible that is. It's probably necessary for every `TableUtils.createTable` to check out the repository at that point in time and then adjust the script based on the status of the respective table at that point in time. Would be a lot of effort, but probably fix the problem.

If you would do this, that would of course be great. We would of course include it! We currently have a release scheduled for next Wednesday/Thursday - do you think you would be able to do it until then?

**Comment by faatihi** [comment]
I already started marking the various check points for correction.
I'll be able to do that for all instances of this bug (They're 10 as of v1.56.1).

Next wednesday may not be feasible for me.
I may have to target one following next week's release.

Aside:
I've been having compilation troubles with Android Studio when I change sormas versions.
Something about `BR` not defined.
If this doesn't come up a lot, I'll be able to meet Wednesday

**Comment by MateStrysewske** [comment]
@faatihi I think you could as well use the GitHub repository to check out the entities at the various points in time by checking out the respective release tag that introduced the schema_version. That way you wouldn't have to switch versions on your local machine so often? So e.g. https://github.com/hzi-braunschweig/SORMAS-Project/tree/v1.42.3 for 1.42.3 etc.

**Comment by MateStrysewske** [comment]
I'll reopen this issue and rename it accordingly so that you can push your changes referencing this issue

**Comment by faatihi** [comment]
Thanks
