### ISSUE TITLE
Symptom „fever“ transmitted from PIA shown in free text field

### ISSUE THREAD

**Issue by GabrielePoggensee** [hzi-braunschweig/SORMAS-Project#3002]
# Problem Description
When a user of PIA enters fever = “yes” the symptom “fever” is shown in the comment field. In the list there is not entry for fever. 
### Proposed Change
The symptom fever must be shown in the list as “yes”.  Remove the entry in the comment free text field.

**Comment by tabotkevin** [comment]
@GabrielePoggensee is there like a screenshot of where to find this issue is found?

**Comment by GabrielePoggensee** [comment]
The issue has been solved. The symptom "Fever" appears in SORMAS CH in the free-text field of the follow-up entry mask which has been renamed for Switzerland: first symptom.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
