### ISSUE TITLE
Surveillance and contact dashboard indicators update [3]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3004]
### Bug Description
The indicators on the dashboard are difficult to easily understand. Some case indicators appear on contact dashboard, Some filters do not work and the time frame used to calculate  the indicators are not the same.
We need to refine their calculations and captions to give users the correct numbers.
### Steps to Reproduce
1.
2.

### Expected Behavior
- Surveillance dashboard should use the total number of cases  reported within the specified time filter provided by the user as denominator while total number of contacts for contact dashboard.
- All  indicators should be based on this set of cases
- sum of individual case classification categories == total New cases,  (this is an old issue, maybe it was not just corrected?) 
- custom filter is not respinsive on contact dashboard for example
More on screen shot
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/94499753-c9449200-01fd-11eb-8466-2c263c19f220.png)

![image](https://user-images.githubusercontent.com/12996724/94500704-525cc880-0200-11eb-80c1-ebbf4518dea1.png)

### System Details
* Device: web
* SORMAS version: 1,49
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
Related: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2815

### Development Specifications
**Surveillance Dashboard**
* Add the missing event states to the "New events" section; "Outbreak" should be red, change "Event" to orange and "Signal" to yellow, use `$s-neutral-color` for "Screening"
* Adjust the date filters for the events that are counted on the Dashboard if needed. The date of the event needs to be included in the selected time filter:
    * If only the start or end date of the event are specified: filter start<= event start date <= filter end
    * If both the start and end date of the event are specified: filter start <= event end date && event start date <= filter end
    * If neither the start nor the end date of the event are specified: filter start <= event report date <= filter end
* Add the missing case classifications `CONFIRMED_NO_SYMPTOMS` and `CONFIRMED_UNKNOWN_SYMPTOMS` to the "New cases" section and the epidemiological curve; these should only be visible in Germany
* Make sure that cases classified as one of these classifications are showing up as confirmed cases on the map (seems like right now they're shown as not yet classified)
* Make sure that "Cases in quarantine" only counts the cases in quarantine among the "New cases" and not based on its own query; the logic is similar to the event date filters, i.e. filter start <= quarantine start/end <= filter end if only one date is filled in or filter start <= quarantine end && quarantine start <= filter end if both dates are filled in
* Rename "Contacts converted to case" to "Cases resulting from contacts"; the number should show the amount of cases among the cases returned for "New cases" that are set as the resulting case of a contact; make sure that this is a distinct count because one case can be the resulting case of multiple contacts, but should only be counted once anyway
* Check why the "last reported district" in the disease carousel layout and the "last report" in the disease overview cards sometimes don't match; the logic should be the same for both, i.e. the district of the case with the latest report date among the cases displayed on the dashboard (see #5185)
* Exclude cases with the classification "Not a case" from all figures on the dashboard except the classification overview in the disease carousel layout (i.e. still display the "not a case" label there)
* Add "Unknown" to the epidemiological curve mode "Alive or Dead"; color grey, include all cases where person present condition is empty

**Contact Dashboard**
* Contacts should not be counted based on the new cases, but purely based on their report dates; this will make sure that contacts without source cases are also included
* Quarantine calculation needs to adhere to the same logic as for cases (see above)
* Make sure that the "Contacts per case" counts are correct; it's possible that no changes are required here, but it would be good to play around with it a bit and ensure that everything works as expected

**Comment by markusmann-vg** [comment]
- [ ] Update the dashboard in regards to German case classification.
- [ ] Check impact on the transmission chain visualization

@bernardsilenou Regarding your sec. screenshot: 
The dashboard is not computed from filters you applied in contacts or case directories!

**Comment by markusmann-vg** [comment]
Take into consideration: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2662

**Comment by bernardsilenou** [comment]
While going dong some more testing, i realized that what you get by filtering on the directory may not match what is on the dashboard. This is partially cased by the date types used. 
@kay I would be good that we compare the filters on each directors and dashboard to identity bugs and link them to this issue.
We can then work on correcting them in 1,53.

**Comment by bernardsilenou** [comment]
Possible suggestions:
1. Use report date as default to all calculations and filters
2. Events
   2.1 Dashbard  = 17 events and directory = 16
   2.2 const for events status on directory matches the total count. Dashboard does not have counts for cluster and screening, so i count not tell where the difference in counts is coming from. 

![image](https://user-images.githubusercontent.com/12996724/98849692-e783eb80-2453-11eb-8e21-5bbd9162cc58.png)

![image](https://user-images.githubusercontent.com/12996724/98849957-53665400-2454-11eb-807d-7c15dba50b51.png)

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske @kwa20 @Candice-Louw 
Here is a summary of issue #2815 and this issue. I know the ticket had much changes but i put all in one because it would be nice to nave the overall vision before implementing.

Since the dashboard is computed directly from db, it would be good to have it such that if a user filter on directors (archived + unarchived), on dashboard or stats, they should have the same counts.

@markusmann-vg In relation to the German case classifications, did not have a look on how it may affect statistics. Since this may involve configuration issues, I would suggest that we implement this now and handle that in the next sprint. The ticket is already much to do.

**Comment by bernardsilenou** [comment]
A. Surveillance dashboard
1. Event indicators
* Include "Cluster" and "Screening" counts.
Cluster: Red (same red as for event)
Screening: Orange (same orange as for signal)
* Report date of event should be editable just as for cases. Report date should not be taken as the system date but user has to specify it just as for cases. This is better for consistency. Should remain a required field. We can just use a date variable rather than than date-time for simplicity or just show only the date component on forms.
* The default time t, to filter event == date of event or start date <= t<= end date (for multi day event). If missing, then t== report date.  This is similar logic we use for cases, onset date else report date. The dashboard and directory does not use the same date type and causes counts not to match: directory uses  date of event (OK) while dashboard uses date entity sync with severer (to be changed).
*  event counts are independent of the cases, ie we can have an event showing on the dashboard even if the case linked to the event is not shown since the report date of the case does not fall in the time interval  specified. Other indicators like samples, quarantine should depend on the case count.
2. Case indicators
*New cases: add confirmed cases with no symptoms and confirmed with unknown symptoms in the count of confirmed cases.
* cases in quarantine should be computed on the subset of cases returned by the file not on the whole case table. Time filter should only apply to the cases not to the date that the case was placed on quarantine.
* cases being placed in quarantine == subset of cases in quarantine (as computed above) with quarantine start date (not date of sync with server) == current system date (today). Maybe rename to  “cases placed in quarantine today”
* rename “contact converted to case” to “cases resulting from contacts”. “contact converted to case” applies to the contact dashboard but not surveillance dashboard. Compute  case resulting from contacts  as == number of cases (among the cases returned by filter) with resulting from contact == true. I am not sure if we already implement the ticket to set on the case table, the variable representing if the case “result_ from_contact” to Null when the contact is deleted after being converted to case. If not, then a second validation should be after getting the number of cases resulting from contact, we need to also check and drop cases if the source contact was deleted on the contact table.
“cases resulting from contacts” is actually = N - (the indicator on the contact dashboard called “new cases not previously known to be contact”). 
cases resulting from contacts +  cases not previously known to be contact == N


B. Contact dashboard
* Also as on surveillance dartboard, maybe remove apply filter related to custom filter alone. It confuses the user and does nothing. Just one apply filter should be enough, just as on contact directory.
* date types used to filter number contact counts on directory and on dashboard are not the same. I could not tell the date type used but I could confirm that it does not used neither the report date, last contact date or most relevant date. I suspect it may be using the report date of the associated cases of the contact which is not the optimum.
Just as the  disclaimer says, filter contact dashboard using report date of contact only, no matter the report date of source case nor last contact date of contact.

* map does not filter entities based on the date type used. We implemented like this in the past to be able to always show something on the map but it would be good to change. Filter the map by default. 

* Migrate “new cases previously known to be contacts” to “cases resulting from contacts” on surveillance dashboard as described in section A.2. We do not need to compute both indicators, we keep “cases resulting from contacts” ons surveillance dashboard and delete ““new cases previously known to be contacts””

* Recompute “contact in quarantine” and “contact placed in quarantine” (rename to contacts placed in quarantine today) using the similar logic as in section A.2 as a subset of all contacts returned by filter.
contact in quarantine = does not depend on date  of start of quarantine
placed in quarantine today == if quarantine start date == today, irrespective if date recorded sync with server, created or modified.

* contact per case:  I could not test this indicator but would be good to have a look at the code based on the new changes: ie group data returned by filter by unique source case uuid (that have not been deleted, excluding contacts with no source case) + count + min,max, avg of the vector of counts.

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  Pls can you have a second look?

**Comment by JonasCir** [comment]
@bernardsilenou Why not putting it into SORMAS-Stats? What is the timeline of this?

**Comment by bernardsilenou** [comment]
@JonasCir These refinement are for indicators we already have in SORMAS. As you said, for other indicators, we would implement in sormas-stats. This is for the current sprint.

**Comment by JonasCir** [comment]
alright got it :) Thanks for the clarification!

**Comment by bernardsilenou** [comment]
Please have a look at #3352 for further refinement on date types

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou I agree with your changes and the need to improve the dashbords. They are currently not self-explaining for the users. One Health office said yesterday in the exchange ""Staff were shocked by the dashboard and then afraid to use it". I totall NOT agree with that and its a sole meaning. But it must be improved. 

I would suggest the following additionally:

* the case status map should show all cases in isolation and maybe renamed to "case status map (all cases in isolation)". On the other side there good raeasons for showing only the cases from the selected period. 
* for Germany plese remove "Last reported district" and "Outbreak Districts" as they are not needed for the locval Health Offices. The same is for "Last report:" one top left.
* for the future please make also the figures clickable. So o.g. if I click on "cases in quarantine", the case directory opens with the filters set to see the cases in quarantine

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis Thanks for this wonderful suggestions and helpful feedback.

You are very correct that we do not need to show "last reported district" on DE servers. The motivation for keeping this is that if SORMAS is latter used at a Bundesland  or national level, then it may be needed. This point and the other 2 pints would be migrated to another issue.

**Comment by MateStrysewske** [comment]
#4175 is a pre-requisite for this.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't really get this point. Could you explain that to me?
"map does not filter entities based on the date type used. We implemented like this in the past to be able to always show something on the map but it would be good to change. Filter the map by default."

"Migrate “new cases previously known to be contacts” to “cases resulting from contacts” on surveillance dashboard as described in section A.2. We do not need to compute both indicators, we keep “cases resulting from contacts” ons surveillance dashboard and delete “new cases previously known to be contacts”" -> I don't agree. Contact supervisors ONLY have access to the contact dashboard, not the surveillance dashboard, and this number is a very important performance indicator (as a high count of cases not resulting from contacts indicates an inefficient contact tracing). Are you sure we want to remove this?

Apart from that, any objections to this specification?

**Surveillance Dashboard**
* Add the missing event states to the "New events" section; "Outbreak" should be red, change "Event" to orange and "Signal" to yellow, use `$s-neutral-color` for "Screening"
* Adjust the date filters for the events that are counted on the Dashboard if needed. The date of the event needs to be included in the selected time filter:
    * If only the start or end date of the event are specified: filter start<= event start date <= filter end
    * If both the start and end date of the event are specified: filter start <= event end date && event start date <= filter end
    * If neither the start nor the end date of the event are specified: filter start <= event report date <= filter end
* Add the missing case classifications `CONFIRMED_NO_SYMPTOMS` and `CONFIRMED_UNKNOWN_SYMPTOMS` to the "New cases" section; these should only be visible in Germany
* Make sure that "Cases in quarantine" only counts the cases in quarantine among the "New cases" and not based on its own query; the logic is similar to the event date filters, i.e. filter start <= quarantine start/end <= filter end if only one date is filled in or filter start <= quarantine end && quarantine start <= filter end if both dates are filled in
* Rename "Contacts converted to case" to "Cases resulting from contacts"; the number should show the amount of cases among the cases returned for "New cases" that are set as the resulting case of a contact; make sure that this is a distinct count because one case can be the resulting case of multiple contacts, but should only be counted once anyway

**Contact Dashboard**
* Contacts should not be counted based on the new cases, but purely based on their report dates; this will make sure that contacts without source cases are also included
* Quarantine calculation needs to adhere to the same logic as for cases (see above)
* Make sure that the "Contacts per case" counts are correct; it's possible that no changes are required here, but it would be good to play around with it a bit and ensure that everything works as expected

**Comment by bernardsilenou** [comment]
@MateStrysewske My explanation of 
_"map does not filter entities based on the date type used. We implemented like this in the past to be able to always show something on the map but it would be good to change. Filter the map by default."_
* Connet to test 1401 today and open dashboard (https://test1401.sormas-oegd.de/sormas-ui/#!cases/data/X4OOUD-RUKB4U-6KS6ER-UWBHSA5U)
* default week is 1/25 to 1/29 and there are cases on map
* go through the map icon and open one of the cases by clicking the map icon
* You would find some nodes that neither of their relevant dates fall in the specified time 
* Although you can filter the map by the date on the map. The default map should filter by the date spcified in main filter even of the count is less than the threshold.
* Similarly, on the epi curve we should remove also the default counts (7 if i can remember) we add at the beginning. If there is no data to plot, then we plot NA.

**Comment by MateStrysewske** [comment]
@bernardsilenou Ah, okay. I understand. The map is like that for a reason. It is a reflection of the CURRENT state of the situation because that's a lot more useful than having a "historic" map. That historic map can be generated in the statistics. I don't think we should change that.

Concerning the epi curve - which default count are you talking about?

**Comment by bernardsilenou** [comment]
> @bernardsilenou Ah, okay. I understand. The map is like that for a reason. It is a reflection of the CURRENT state of the situation because that's a lot more useful than having a "historic" map. That historic map can be generated in the statistics. I don't think we should change that.
>
Thats ok, I raised this point because some users want to see only results that occurred within the time filter #4099.
We handle this change in #4099 with a configuration then.
> Concerning the epi curve - which default count are you talking about?

The epi curve fro the current week 5 (25 - 29), when grouped by week gives you 6 bars before the right week.
The change is to have just one bar, when grouped by  day, then 7 bars. A prerequisite for this can be the issue on epi week computation.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't really understand the reasoning behind such a change. The epi CURVE is supposed to display the evolution of the state over time, i.e. over the last few weeks, days, months, whatever has been chosen there. Only displaying one single bar (of the current week) would completely take away the purpose of an epi curve whatsoever.

**Comment by bernardsilenou** [comment]
@MateStrysewske I see from both sides. 
The point is that some users do not want to see counts, tables, figures, maps, etc outside their time filter.
_The epi CURVE is supposed to display the evolution of the state over time_ This is correct, conditioned that  this time falls in the filter interval specified by the user. We want to give users the option to only see evolution over a week if they wish.
For very wide time interval (60 yrs), then evolution over weeks may not help also. So its all relative.

Choosing a 7 days interval and grouping by weeks does not sound good, but should be possible. In addition showing bars for weeks that does not fall in the time interval is also not good for all users, e.g they may want to export the graph and use in their report, in that case we should only export cases in the time of the filter.

This new specification would would satisfy all the users I suppose based on comment from other issues I have read.

**Comment by MateStrysewske** [comment]
@bernardsilenou There's actually a checkbox called "Always show at least 7 entries" in the "Groupings" dropdown that can be unchecked to get exactly what you've defined. It's on by default which I think should stay that way.

**Comment by bernardsilenou** [comment]
@MateStrysewske Your the best Bro! I cant imagine I did not see it, but could recall that we designed something like that and though it was hard coded. I also confirm that it is OK as it is.
Thanks

**Comment by kwa20** [comment]
@bernardsilenou Are we also taken into consideration the display of the correct case classifications on the map?

**Comment by bernardsilenou** [comment]
@kwa20 For D and E case classification, they would all show as confirmed cases on map since we are adding them among the confirmed counts. But there all would have just one map key "red circle", I think we should not add more configuration details on the map

**Comment by Candice-Louw** [comment]
@markusmann-vg - why this is on refine, please?  Do you need anything additional from HZI's side?

**Comment by bernardsilenou** [comment]
@MateStrysewske How do we summarize this one pls? It was assigned to you in your absence.

**Comment by MateStrysewske** [comment]
@bernardsilenou I'll take care of that next week ;)

**Comment by MateStrysewske** [comment]
Specifications are here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3004#issuecomment-769799072

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske, @bernardsilenou, @Candice-Louw thanks for the work on this issue so far. Sorry, but I have to give also my two cents to this:

It would be great if here the cases could be grouped by the status:
![grafik](https://user-images.githubusercontent.com/74791118/110784837-766e0c80-826a-11eb-88aa-236abfdeb0cb.png)

CONFIRMED - CONFIRMED_NO_SYMPTOMS - CONFIRMED_UNKNOWN_SYMPTOMS
SUSPECT - PROBABLE
NOT_CLASSIFIED - NO_CASE

And in my understanding not_cassified and no_case should not counted for the total amount of cases here:

![grafik](https://user-images.githubusercontent.com/74791118/110786114-0791b300-826c-11eb-888f-1a7da67d2ef7.png)
![grafik](https://user-images.githubusercontent.com/74791118/110786120-095b7680-826c-11eb-849c-76cfb5311cef.png)

As they are listed in the case directory, but are no case really. But I understand that there can be different views. Maybe @heineltp   @Lisa-GAmannheim and @OrgaLandkreisTuebingen can share their views as well.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis 
- With respect to the need to have the categories like CONFIRMED_UNKNOWN_SYMPTOMS, this would come in another issue on configuring the dashboard based on the sormas instance. These categories only exist in the DE instance only. 
- no_case is just to measure the sensitivity of the surveillance system. 
- not_classified is to measure your work load to be done or how users are using the system. Normally the goal is to have 0 count here. Agree that we do not also need it for your report. Thus there are confirmed cases on the  not_classified category.

The dashboard is just a representation of the situation at hand.

**Comment by bernardsilenou** [comment]
Additional bugs or inconsistencies:
**A. Surveillance dashboard**
1. Last report (info box of a single disease) and last reported district (lower disease specific surveillance dashboard) do not match. Last report district should be calculated as district with the most recent case based on report date of the case. Last report district can only be 0 or none if the the total cases in the specified time interval == 0. Since this is about surveillance dashboard, then entity type to determine the last report district should be the case, not task or events. 
2. For cases, contacts, events, test results, etc, sum of categories should be == total new entities no matter the filter options. This point was already mentioned above i think. For cases, add confirmed with symptom and confirm without symtom in the count for confirmed cases. For events add counts for signal and other statuses,  Same for test results, 
![image](https://user-images.githubusercontent.com/12996724/114399710-85194d80-9ba1-11eb-908c-8bc441430480.png)

3. On epi curve by outcome (alive/ death), the sum of bar counts != total new cases. This is probably because entities with missing outcomes are omitted. Suggest to add the counts for missing and stack on the bars also with grey colour. Since this is not a bug, then we can migrate to another issuue if  needed. The time used here is report date and this is fine, no need to change to date of outcome.

**B. Contadt dashboard**
4.Same as on surveillance dashboard, totoal == sum of categories

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Point 2 and 4 in comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/3004#issuecomment-817813801, are not in the dev specification because i just updated it. Would you add or point 4 is an issue by its own?  At least we can add point 2.

**Comment by MateStrysewske** [comment]
@alexcaruntu-vita I've added two additional points to the development specifications (last two points under "Surveillance Dashboard") according to Bernard's requests

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.61.0-SNAPSHOTdeployed on est-de.sormas.netzlink.com environment
