### ISSUE TITLE
Avoid duplicates when importing campaign data [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3005]
### Feature Description
Based on #1999 data can be imported for campaigns.

### Problem Description
There is currently no check on whether the "same form" has already been entered into the system. It's likely that duplicates are created.

### Proposed Change

- [x] Make sure that for each combination of **Campaign**, **CampaignFormMeta**, **Date** and **Community** (cluster) only one form exists in the system.
- [x] Show a dialog when a duplicate is detected (as we do for cases) and let the user chose:
1. Skip duplicate
2. Override duplicate
- [x] Display the data of the existing form in the dialog: Campaign, form name, Date and Community, creating user, creationDate
- [x] Make sure that import of the same form in the same import also fails on the second entry.

**out of scope:**
We probably need the ability to define custom unique fields for a campaign form, that allow to have multiple form data for one cluster. An example for this would be the team id, when there are multiple teams collecting data within one cluster.

@bn1010 @danieltomaba Please confirm on whether the "team id" use case makes sense and if there are other use cases needed.

**Comment by bn1010** [comment]
According to AFG, this would be a sufficient condition: [Province code+ district code +cluster Number +team number +day +Month + year and Name of campaign]. Assuming cluster has a UID, Province and district codes would seem redundant.

**Comment by MartinWahnschaffeSymeda** [comment]
Let's leave the team number (custom unique field) out for now.

**Comment by StefanKock** [comment]
I created #3521 to also consider duplicate detection when manually creating campaign data.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] When importing "yes-no" data ("yes", "no", "true", "false"), it should be converted to Boolean before saving
- [ ] Don't convert the wrong imported data in the UI (CamaignFormBuilder).

**Comment by MateStrysewske** [comment]
- [ ] Remove creating user and creation date from new campaign form data
- [ ] Change "Cancel" to "Cancel import"
