### ISSUE TITLE
Chart fullscreen has black background

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3006]
### Bug Description
When using the fullscreen option of a chart the whole background of the chart becomes black.

### Steps to Reproduce
1. Go to statistics and create any type of chart
2. Click to view in fullscreen option of the chart

![grafik](https://user-images.githubusercontent.com/23217632/94521452-5f90ac00-022e-11eb-88d3-7475b7c8b240.png)

### Expected Behavior

Background should be white

### System Details
* Server URL: https://test.sormas.netzlink.com/sormas-ui/
* User Role: National user

**Comment by DavidBaldsiefen** [comment]
The "View fullscreen" option seems to have been removed in the meantime (1.62.0)
