### ISSUE TITLE
Category and type of a facility should not be editable [0]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#3011]
### Problem Description
Currently in the configuration you can change the category and type of a facility after its creation. This cannot be allowed, because it can cause many different and serious problems.
### Proposed Change
Make facility category and facility type not editible after creation.

**Comment by StefanKock** [comment]
Merged so closed ...

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
