### ISSUE TITLE
Personal data is not always correctly pseudonymized

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3013]
### Bug Description
It seems like there are cases in which personal data is not correctly pseudonymized (see "Steps to Reproduce"). The font is italic, but the value is not "Confidential" like it should be, but the actual value of the field is shown.

This e.g. affects the first and last name and the telephone number of the person.

### Steps to Reproduce
1. Create a Contact Supervisor in Region A
2. Create a case in Region B
3. Create an event in Region A for the case
4. Log in as the contact supervisor and enter the person form of the case; first and last name, day of birth and phone number aren't pseudonymized correctly

**Comment by MateStrysewske** [comment]
The problem isn't that the details are shown - that actually makes sense because the user has access to the person via the event. The actual problem is that "Confidential" is shown in fields that are empty even though it shouldn't (because the person isn't confidential to the user).

This is because the case itself is outside the user's jurisdiction and whether or not "Confidential" is shown depends on that fact, not on whether the person is available to the user or not.

**Comment by MateStrysewske** [comment]
Has already been fixed by @leventegal-she and will be merged into the development branch soon.

**Comment by MateStrysewske** [comment]
Fixed by PR #2721

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
