### ISSUE TITLE
Change default print behaviour with browser

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3020]
### Situation Description

If, on any SORMAS screen, you use the browser built-in print function (like with Ctrl+P), the print result is the original page, with no adaptation for the printing process.

A long-term solution for printing will be the use of the template mecanism from #2696 to export the various screens as .doc files.

### Feature Description

A short-term alternative is to specify in the css a specific behavior for printing, using the "@media print" tag.
Current issues with the default print result are (can be completed via contributions in comments) :
- the left menu is useless
- the pages are truncated due to the scroll bar mecanism

This solution would be directly efficient for every screen. That's why this short term solution and the template mecanism would be complementary : the short term define the default print behavior for every pages while the template mecanism permits to create specific .doc exports for somes screens.

### Additional Information

**Note :** it is not possible to be sure this will fix every printing issue but it will almost enhance the result for many screens. As the original need is linked to event screen and its actions an effort will be done to fix specific problems with those screens.

**Note 2 :** the html structure of tables induced by Vaadin is really complex and our tests show that it will be difficult to make them printable (in addition, their width will not help). However, most of the pages with tables provides export functionnality that are good alternatives to direct printing. That's why we will not correct their printing behavior in this issue.

@xavier-calland @carolinverset

**Comment by AndyBakcsy-she** [comment]
Checked this behavior on Sormas version 1.50.SNAPSHOOT
