### ISSUE TITLE
From the events directory, access the filtered case directory on involvement in a given event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3021]
### Situation Description
To date, the directory of cases cannot be filtered on a possible involvement in an event. Issues # 2908 and # 2922 makes possible to filter cases based on the title of the event. To complete these developments, it would useful to have a function allowing access to the list of cases involved in an event from the "event" part and more precisely from the event file. The user could then very easily access to the exactly list of cases involved in an event (via a filter on the id)

### Feature Description
It is proposed to create a link allowing the user to access, from the event file, directly to the case directory which will then be automatically filtered on the only cases of the event. This link would be represented by a button located below the “task” and “actions” blocks.

It complements the function allowing the filtering of the case directory according to the involvement in an event. This offers greater flexibility in terms of managing the events and cases involved.

Finally, this feature would have the advantage of not having to search, copy and paste the event ID it in the search block of the case directory. 

### Additional Information
![image](https://user-images.githubusercontent.com/65449450/94585949-f71eea80-0280-11eb-9b41-4e4657a8e4b1.png)

@ftavin @xavier-calland @olivierleuci @bernardsilenou

**Comment by ftavin** [comment]
@carolinverset  What about a second link, with the same behavior but leading to the contacts directory filtered on the event ?

**Comment by carolinverset** [comment]
@ftavin  Yes ! of course, it would be nice to have the same behavior for cases and contacts directory.

**Comment by xavier-calland** [comment]
@MateStrysewske I'm working on it. I'll propose a PR when #2974 is merged.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
