### ISSUE TITLE
Automatic task generation for contacts is triggered every time after editing the contact information

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3025]
### Bug Description
The newly introduced task generation for contacts works after initially creating a contact. However, tasks are additionally generated every time after editing the contact information. A possibly resulting overload on t
### Steps to Reproduce
1. create a new contact and check for initial task generation.
2. edit this contact's information page, save and check tasks.

### Expected Behavior
The initially generated task should only be created once when the contact has been created. 
### Screenshots
<img width="624" alt="Screen Shot 2020-09-30 at 10 35 46 AM" src="https://user-images.githubusercontent.com/70317594/94662511-c6829380-0308-11eb-86cc-a759b3cd112e.png">

### System Details
* Device:
* SORMAS version: 1.49
* Android version/Browser: Chrome, Firefox
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she I created a contact on https://test.sormas.netzlink.com/ and the initial  contact investigation task was not generated. Please can you verify this also?
Expected behavior:
- The first time the contact entity is created, create a contact investigation task
- Create subsequent daily followup tasks if today's date is <= followup until date

**Comment by AndyBakcsy-she** [comment]
@bernardsilenou I rechecked this functionality and it works as expected on the specified environment. 
When a new contact is created, a new Contact investigation task is also created.
![image](https://user-images.githubusercontent.com/70562142/95165339-739b5700-07b4-11eb-82f2-2b88e7d97af0.png)
