### ISSUE TITLE
Columns in directories show error when trying to sort

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3026]
### Bug Description
Several directory columns result in an error when trying to sort them by clicking its header. These include:
- Address (contact directory, detailed view)
- Source type (event directory)
- Participant Count (event directory)
### Steps to Reproduce
1. Go to the directories mentioned above.
2. Click the headers to try and sort them.

### Expected Behavior
Click on the header should sort the list by the selected column.
### Screenshots
<img width="1061" alt="Screen Shot 2020-09-30 at 10 49 29 AM" src="https://user-images.githubusercontent.com/70317594/94664204-ea46d900-030a-11eb-9962-b8edbdf895b6.png">
<img width="1066" alt="Screen Shot 2020-09-30 at 10 50 54 AM" src="https://user-images.githubusercontent.com/70317594/94664220-ef0b8d00-030a-11eb-82bd-4a08aa9dc634.png">

### System Details
* Device:
* SORMAS version: 1.49
* Android version/Browser: Chrome, Firefox
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin

**Comment by raghupola-vg** [comment]
Sorting on Event Participants column is disabled/removed. All other sorting works fine.
