### ISSUE TITLE
Tick box: "Share this case with the whole country" should not be shown on german and swiss servers

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3027]
### Feature Description
There is a new tick box in the case directory called "Share this case with the whole country". 
### Problem Description
This will be confusing to users on the german and swiss servers since this button would not do what it implies.
### Proposed Change
Hide this tick box on german and swiss servers.
### Additional Information
<img width="731" alt="Screen Shot 2020-09-30 at 10 55 42 AM" src="https://user-images.githubusercontent.com/70317594/94665341-4d853b00-030c-11eb-88a4-b219d00ad8bc.png">

Release Candidate 1.49
test1401.sormas-oegd.de

**Comment by MateStrysewske** [comment]
This check box isn't new, it's been in the system for quite a while now. Also, it can be disabled in the featureconfigurations table in the database.
