### ISSUE TITLE
Test result not adopted when directly entered in entry mask of sample

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3028]
### Bug Description
When a test result is entered directly in the entry mask for the sample creation, it isn't adopted in the final laboratory result and not shown on the associated information tab.
### Steps to Reproduce
1. Go to any contact or case information and create a sample.
2. While in the entry mask, tick the box "Create test result for this sample now" and precede entry of required fields. 
3. Save and check the sample status in the associated information tab as well as the final laboratory result field in the sample information.

### Expected Behavior
When the test result is entered directly in the entry mask for samples, result should be adopted and shown in associated information tabs as well as the final lab result.
### Screenshots
<img width="952" alt="Screen Shot 2020-09-30 at 11 36 24 AM" src="https://user-images.githubusercontent.com/70317594/94669957-38130f80-0312-11eb-8a8b-6cc1778379d3.png">
<img width="454" alt="Screen Shot 2020-09-30 at 11 38 44 AM" src="https://user-images.githubusercontent.com/70317594/94670011-48c38580-0312-11eb-928a-9dfde559a3ab.png">
<img width="1071" alt="Screen Shot 2020-09-30 at 11 39 14 AM" src="https://user-images.githubusercontent.com/70317594/94670032-4f51fd00-0312-11eb-98c6-999d0b743558.png">

### System Details
* Device:
* SORMAS version: 1.49
* Android version/Browser: Chrome, Firefox
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin

**Comment by AndyBakcsy-she** [comment]
verified issue on SORMAS Version: 1.50.0-SNAPSHOT
