### ISSUE TITLE
Apply filter button resets previously adjusted date interval in follow-up views

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3029]
### Bug Description
When more filters have been selected after adjustments of the date have been made in follow-up views, pressing the apply filter button resets the previously adjusted dates.
### Steps to Reproduce
1. Go to the case or contact follow-up view and change the date interval.
2. Select any filters above afterwards and hit the apply filter button.

### Expected Behavior
Changed date interval should not reset when hitting the apply filter button but stay as adjusted.
### Screenshots
<img width="1066" alt="Screen Shot 2020-09-30 at 11 57 43 AM" src="https://user-images.githubusercontent.com/70317594/94671505-42360d80-0314-11eb-97a5-799e1caa4631.png">

### System Details
* Device:
* SORMAS version: 1.49
* Android version/Browser: Chrome, Firefox
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin

**Comment by ChristopherRiedel** [comment]
This is not a bug, it is a feature request. The selected period is not part of the filters and is not considered by the criteria.

**Comment by kwa20** [comment]
That the period selection is not considered by the apply filter and executed independently is fine. I think the problem lies in the changes of dates being resetted when the apply filter button is hit. If the apply filter does not consider the period, I think it should leave the period untouched if it has previously been adjusted.

**Comment by StefanKock** [comment]
Removed bug label since it is already labeled as change request.

**Comment by MateStrysewske** [comment]
I agree with @kwa20 about his initial classification as a bug and will adjust the labels accordingly. This is definitely unintended behaviour (even though it's not caused by an implementation error or anything like that).

**Comment by DavidBaldsiefen** [comment]
I think this is already fixed, as I cannot reproduce in 1.59-SNAPSHOT. @kwa20 Can you please confirm if you still encounter this issue?

**Comment by kwa20** [comment]
@DavidBaldsiefen Seems like it yes, I could not reproduce it anymore either
