### ISSUE TITLE
Cases and Contacts > Preexisting conditions visibility CH

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3030]
### Feature Description
For Cases and Contacts, a list of preexisting conditions exist.  The visibility differs based on each server's configuration settings.

### Problem Description
Currently, Switzerland is seeing the preexisting conditions for non-DE servers - many of these irrelevant to COVID.

### Proposed Change
Show the same preexisting conditions for Cases and Contacts for Swiss servers as for German servers.

### Additional Information
International/current list:
https://user-images.githubusercontent.com/68859880/92265010-7833cd80-eedf-11ea-9884-660bfe1bd880.png

Wished for list:
https://user-images.githubusercontent.com/68859880/92265241-8b469d80-eedf-11ea-86c3-f7aab50f0eb5.png

**Comment by bernardsilenou** [comment]
@Candice-Louw this should be a bug because the pre-existing conditions should normally respect the server instance

**Comment by MateStrysewske** [comment]
@bernardsilenou It's not a bug because from what I can tell, we never received definitions on which conditions should be disabled for Switzerland.

**Comment by Candice-Louw** [comment]
The Swiss servers are configured to display "SORMAS-international" values by default.  SORMAS-DE values have to be explicitly defined/requested (as is the case here).  Thank you for making the change! 👍

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT on the Swiss env.
