### ISSUE TITLE
From the events directory, access the filtered contacts directory on involvement in a given event

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3034]
### Situation Description

To date, the directory of contacts cannot be filtered on a possible involvement in an event. Issue #2922 makes possible to filter contacts based on the title of the event. To complete these developments, it would be useful to have a function allowing access to the list of contacts involved in an event from the "event" screen. The user could then very easily access to the exactly list of contacts involved in an event (via a filter on the id)

### Feature Description

It is proposed to create a link allowing the user to access, from the event file, directly to the contact directory which will then be automatically filtered on the only contacts of the event. This link would be represented by a button located below the “task” and “actions” blocks.

It complements the function allowing the filtering of the contact directory according to the involvement in an event. This offers greater flexibility in terms of managing the events and contacts involved.

Finally, this feature would have the advantage of not having to search, copy and paste the event ID it in the search block of the contact directory.

### Additional Information

This issue is the same mecanism as #3021 but applied to contacts

@carolinverset @xavier-calland @bernardsilenou

**Comment by ftavin** [comment]
@MateStrysewske : @alexandre-gille is working on this issue

**Comment by bernardsilenou** [comment]
@alecandre-gille  Please can you add a mockup? I read the issue bit i am not sure i understood how it will look.
Thanks

**Comment by ftavin** [comment]
@bernardsilenou this is the same mecanism than #3021 but applied to contacts

A button "See contacts for this event" will be added to the event information screen, just under "See cases for this event" (cf. actual version on your test server or the following screenshot)

![Event info 01](https://user-images.githubusercontent.com/15834125/95596030-27b70f00-0a4d-11eb-87ee-b9321d44ae49.PNG)

Clicking this button will lead to the contact directory, filtered on the event (like the other button do for cases in the following screenshot)
![Event info 02](https://user-images.githubusercontent.com/15834125/95596203-6056e880-0a4d-11eb-9901-aad572ed807c.PNG)

cc @alexandre-gille

**Comment by bernardsilenou** [comment]
@ftavin  Now i got it. Perfect link
Thanks

**Comment by AndyBakcsy-she** [comment]
I am seeing the button on the Event page and it brings the user to the contacts page + filters based on the UUID of the event. 
The PROBLEM is that even though the event has multiple contacts, only the Contacts which have a Case + the Case is linked to that specific event will be displayed.
Shouldn't all Contacts from that event be displayed?

**Comment by ftavin** [comment]
@AndyBakcsy-she  We need a precise exemple on the test server to reproduce and understand what you are talking about.

Can you give me an event id ?

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she All contacts are displayed by default, unless to check the option "only contacts with source case linked to the specified event"  in the contact directory

**Comment by AndyBakcsy-she** [comment]
for example, @ftavin  this Event from the Test environment: 
https://test.sormas.netzlink.com/sormas-ui/#!events/data/UCZGMC-L27RNR-ERYAFE-7SANSK4Q 
For this event, the filter will display only 3 Contacts but the Event has actually 5 Event Participants. 
The checkbox is not selected by default.

**Comment by ftavin** [comment]
@AndyBakcsy-she It seems you are making a confusion between event participant and contacts here.

The event have 5 participant but only 3 of them are contacts

**Comment by raghupola-vg** [comment]
This issue is tested, all contacts related to the event are displayed correctly and works as expected.
