### ISSUE TITLE
Information concerning contacts in event participant screens

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3035]
### Situation Description

In the event participant screens (list of participants + details of an event participant), there are no informations on the fact that the person is or not a contact regarding this particular event.

### Feature Description

This feature consists in three new elements :
- a new column in the list of participant of an event, after the case id, which indicates the number of time the person is a contact involved in this event (could be more than 1 if there are multiples cases in the same event)
- the list of the contacts in the detail of an event participant with the following informations for each :
-> **still to be determined via the issue comments**
- a button in the detail of an event participant that gives the hability to create a contact concerning the current person
-> this contact will be automaticaly considered involved in he current event
-> the cases suggested as "source case" will be limited to the cases of the current event

@carolinverset @xavier-calland @bernardsilenou

**Comment by bernardsilenou** [comment]
The need for this request is similar to issue #2727. Among the list of event participants, users want to know which of the event participant persons are linked to contacts.

**Comment by bernardsilenou** [comment]
> ### Feature Description
> This feature consists in three new elements :
> 
In this first phase of the implementation, we decided to limit the relationship to only entities that belong to the event in question. In a later issue, we would generalize it to include contacts or cases that are not also in the event in question.

> * add a new column in the "event participants page",  after the case id, which indicates the number of time the person is a contact involved in this event (could be more than 1 if there are multiples cases in the same event)

This is computed as: sum of contacts of this event participant person WHERE source case of contact == any of the resulting cases of the event. In a future issue we will drop the where constrain and include all contacts and add a parameter for this condition.

> * the list of the contacts in the detail of an event participant with the following informations for each :
>   -> **still to be determined via the issue comments**

At the right of the event participant form,  we can add an  information box called "Contact" + blue icon on the right hand side called '"Create contact". This is similar to what we have on the case form, that permit us to link the case to an event. 
It will be nice to also have a similar box for the case information, similar to what we have on the "contact information page" for a contact that has a source case. An event participant can be linked to 3 contacts and later result to a case ( from an event participant rather then any of the contacts)
For every method that leads to linking 2 entities, we should also consider to include the option to unlink them. I added a suggested mockup on how to unlink cases from events in issue #2984

I have attached a suggested mockup based on  the new event participant entity mentioned here #3003 

![image](https://user-images.githubusercontent.com/12996724/95140521-65771780-076f-11eb-8594-87b4d9d06904.png)

**Comment by bernardsilenou** [comment]
@ftavin I suggest we start by separation the event participant entity from the person entity and add the 2 boxes on the right that links it to the resulting case and associated contacts. We must not add all the variables related to quarantine and followup in this issue.
@MateStrysewske  Do you have any objection to this specification?

**Comment by MateStrysewske** [comment]
@bernardsilenou Event participants and persons are already two separate entities. Also, we don't need to specifically link the contacts to the event since we have the cases resulting from the event as a reference. Therefore, when creating a contact for an event participant from this screen, we probably have to force the users to select a source case (and filter the list of possible source cases to those resulting from the event).

**Comment by ftavin** [comment]
@bernardsilenou I'm ok with your remarks. Regarding development priorities, do you know if the separation is scheduled to be done in a short while ? I agree that both devs should not be done in the same time to avoid merging conflicts but I don't think the order of the devs is important (we can add contacts infos on the tab first, then move the person infos or move the the person infos first and then add contacts infos on the tab)

@carolinverset are you ok with this specification ?

**Comment by bernardsilenou** [comment]
> @bernardsilenou Event participants and persons are already two separate entities. Also, we don't need to specifically link the contacts to the event since we have the cases resulting from the event as a reference. Therefore, when creating a contact for an event participant from this screen, we probably have to force the users to select a source case (and filter the list of possible source cases to those resulting from the event).

Thanks for this excellent and concise information Maté, We definitely should not directly link the contact to the event.
When i say separation of event participant entity from the person entity, I am referring to just the form design, not the back end. Just to have a look as on the case form. This is not so important for now i suppose.

Another challenge i can see with the fact that we limit the source case to be in the event is that if an event participant person is linked to a contact whose source case is not in  the event, then when we open the the event participant form, there will be no contact information. I hope users will not be confused with this?

**Comment by bernardsilenou** [comment]
@ftavin This implementation is not on our list in this sprint. You can go on with implementing the box "link contact" and add it on the current event participant form.
If possible, please add the icon with text "create case for this event participant" on the event participant form. We currency only have it on the event participant table table and when you  open the event participant from of an EP that has resulted to a case, you have no idea of the case.

**Comment by bernardsilenou** [comment]
@MateStrysewske @ftavin What do you think about this please:
When an EP person  becomes a case as a result of the contact, then this resulting case is not seen in the system as a resulting case from the EP. I hope uses would be able to understand this?
If a user open a contact through this newly designed EP form, convert the contact to a case, then come back and open the EP form again, nothing would have change

**Comment by MateStrysewske** [comment]
I actually think that there should be a visible link between the EP and the case if the case resulted from a contact that originated in that specific event.

In general we need more links between cases, contacts and events of the same person. This will definitely help with the person <-> case problem.

**Comment by ftavin** [comment]
@MateStrysewske : @alexandre-gille is currently working on this issue, a PR will be done this week

**Comment by bernardsilenou** [comment]
Carolin recommended to use the icon of #2984 to unlink

**Comment by ftavin** [comment]
@bernardsilenou : @alexandre-gille is using the trash icon already available in SORMAS, you can see on the screenshot below how it looks like in his WIP :
![image](https://user-images.githubusercontent.com/15834125/97318053-bf996300-186b-11eb-8159-5d5c2377cd5b.png)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT
