### ISSUE TITLE
Strange behaviour for text filters in contact and case directory

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3047]
### Bug Description
It seems like the text filters (filtering by name, ID, etc.) in the contact and case directories sometimes result in cases/contacts appearing in the list that don't really seem to belong there. This can be observed on https://test.sormas.netzlink.com/.

This is not necessarily a bug, but we need to find out why the unrelated cases/contacts appear in the lists.

### Steps to Reproduce
1. Log in as National User
2. Navigate to the contact directory and type in "Aurelius-T5nhZA" - one seemingly unrelated contact appears in the list
3. Navigate to the case directory and type in the same name - one seemingly unrelated case appears in the list

**Comment by MateStrysewske** [comment]
Found the source: The text filters can also filter for phone numbers. What's done there is that everything that's not part of a usual phone number is excluded from the search term. This includes letters; so for the search term mentioned above, the system searches for any case that has a phone number with the digit 5 in it (since that's the only character that remains after all illegal characters are excluded).

My suggestion is to not exclude letters from the text filter for the phone number search. It makes sense to exclude special characters (such as / and +) as well as blank spaces from the term because those are commonly used in phone numbers and removing them ensures that the phone number is still found even if it's written in a different format, but by not excluding letter we would make sure that a situation like this one doesn't occur. If someone enters a search term that contains letters, they probably don't want to search for a phone number anyway.

@bernardsilenou @markusmann-vg What do you think?

**Comment by markusmann-vg** [comment]
I follow and confirm your suggestion. Just exclude ("-", " ", "/", "+", "'") from the search string.

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.50.0-SNAPSHOT
