### ISSUE TITLE
Error accessing Cases as POE Supervisor

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3053]
### Bug Description
When a user logs in as POE Supervisor and access Cases, an error is popped up.

### Steps to Reproduce
1. Login to Sormas (https://test.sormas.netzlink.com/) as POE supervisor
2. Click on Cases to access case directory

### Expected Behavior
No error must be displayed  and cases must be accessible.
 
### Screenshots
![Error at POE supervisor_Cases](https://user-images.githubusercontent.com/62763628/94915658-8f011c00-04ad-11eb-8ff2-eb0af2bab16a.PNG)

### System Details
* Device:
* SORMAS version: 1.50.0 -snapshot
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/
* User Role: POE Supervisor

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
