### ISSUE TITLE
Bulk de-archiving doesn't work anymore

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3058]
### Bug Description
When viewing only archived cases, the bulk edit options list "archive" instead of "de-archive" which makes it impossible to bulk de-archive cases. This is probably also true for events.

**Comment by StefanKock** [comment]
I reviewed this, works now as expected for cases and also for events as @MateStrysewske suspected.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
