### ISSUE TITLE
x-axis labels sometimes disappear

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3065]
### Bug Description
x-Axis bottom label is hidden when chart has not enough width space

![grafik](https://user-images.githubusercontent.com/23217632/95086651-07bbde80-0721-11eb-8682-8d3d7dbd4f15.png)

### Expected Behavior

- [x] Rotate stack labels when multiple stacks are used: 'rotation: 45, x:30'
- [x] When this happens the margin of the legend needs to be increased to 60

Example: https://jsfiddle.net/w9xm5607/

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha I checked this on the test system and realized that I forgot one important point:

-  [ ] besides rotating the stackLabels also set allowOverlap to true

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
