### ISSUE TITLE
Create Case for a Contact in the android app does not work as expected

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#3066]
### Steps to Reproduce
1. Login with SurvOff in the app
2. Create a confirmed contact 
3. Tap the button "Create a case for this contact person" at the bottom of the activity
=> Issue 1. Dialog for select or create contact is displayed
=> Issue 2. Select the suggested person and tap the "Select"  button =>  error message "Please select a person...." is displayed

### Expected Behavior
Issue 1. The contact person should be used without asking to select or create
Issue 2. It should consider the selected person. => It's probably a general issue, please check the behaviour on case creation for example

### System Details
* Device: Pixel 3 Android emulator
* SORMAS version: 1.50
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
@leventegal-she  did you succeed to login as national user on app? Only district user roles: informants and officers should be able to use the mobile app. If you succeed to log in as NatUser on the mobile app in the first place, then that should be a bug.

**Comment by leventegal-she** [comment]
@bernardsilenou You're right, I'm not able to login with national user, I logged in with SurvOff. I fix the description

**Comment by MateStrysewske** [comment]
Issue 1 is fixed, issue 2 can't be reproduced. Doesn't seem to be a general problem.

**Comment by AndyBakcsy-she** [comment]
Verified issue using the app upgraded to SORMAS Version: 1.50.0-SNAPSHOT
