### ISSUE TITLE
Expression fields for campaign data forms [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3067]
### Situation Description
Currently campaign data forms can only have fields that manually have to be entered by the user.

### Feature Description
For the field "poorly covered area?" (yes/no) it would be better to calculate it based on the number entered for "Missed children based on recall" (>=2) and "Number of houses team did not visit" (>=2).

### Possible Alternatives
Users have to manually enter the information.

**Comment by MartinWahnschaffeSymeda** [comment]
Suggested solution:

- [ ] Add an optional "expression" property to campaign form field definitions. When used, the field becomes read-only and is calculated based on the expression.
- [ ] To evaluate the expression the Spring expression language library is used. It provided support for typical logic and math operators (https://docs.spring.io/spring-framework/docs/5.3.2/reference/html/core.html#expressions-operators) and also for using other fields as variables (https://docs.spring.io/spring-framework/docs/5.3.2/reference/html/core.html#expressions-ref-variables).
In the future this could be extended with a lot of additional features, like custom functions and more.
- [ ] When a form contains at least one expression field, do the following, whenever a non-expression field value is changed:
Build an EvaluationContext that contains the values of all expression fields. 
Update the value of the expression field using ExpressionParser.getValue(context).
If possible implement this in a function based approach to make it re-usable in the backend and the android app.
- [ ] This should work for text, number and yes-no (Boolean) fields. 
- [ ] Update the wiki (https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Campaign-Form-Definition) and provide an example with math operators (+, -, ..) and an example with logic operators (e.g. ''#missedChrildren >= 2''). Also a link to the relevant parts of the Spring expression language docs.


Out of scope:
* Add a method to the backend that re-evaluates all data that has already been entered into the system, when an expression is modified or added.

**Comment by ssferrazza** [comment]
**QA Notes**

- Added new fields to `CampaignFormElement` to store `expression`
- Functionality summarized in new class `ExpressionProcessor`
- Added Unit Tests (`ExpressionProcessorTest`) to verify the requirements

**Comment by MartinWahnschaffe** [comment]
@ssferrazza Looks very good. Two things that we should address:

- [ ] When hovering over the calculated field we need to give the user a clue why the field is read-only. Add a tooltip that says "Calculated based on: ..." with the names of the fields that are used to calculate it.
- [ ] We should automatically calculate the field the moment the form is opened, not only when a source field is changed.
