### ISSUE TITLE
Activate user popup shown when creating user

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#3071]
### Bug Description
Create a user with an admin and get two modal windows stacked.

### Steps to Reproduce
1. Login with admin
2. Create any type of user
3. See two stacked modals

### Expected Behavior
Only the password layer should be shown when Keycloak is not the Authorization Provider.
Only the activation layer should be shown when the system is using Keycloak to authenticate users.

### System Details
* SORMAS version: 1.50-SNAPSHOT
* Server URL: test.sormas.netzlink.com, test-de.sormas.netzlink.com
* User Role: admin

**Comment by tabotkevin** [comment]
@vidi42 I just tried to replicate this issue, I didn't see two stacked modals. Maybe I am missing something.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
