### ISSUE TITLE
[QA] Performance Test Scenario 2 implementation

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3075]
### Feature Description
Create the first Test script for the Scenario 2 from the[ Performance Test Plan](https://wiki.vitagroup.ag/display/SORMAS/Performance+Testing?flashId=1448187187)

Investigate if Creating API tests in Katalon can be done with the Free license. 
Check if The first Performance script can use existing methods from the e2e UI tests.
Start Implementing the first scenario, step by step.
Measure the times for the Rest calls that create cases/contacts.

### Possible Alternatives
1. Use the existing UI tests with added logic so that the cases/contacts get created 
2. Use Postman for the REST calls 
3. Use Jmeter for the calls ( in the case where Katalon and Postman cannot be used )

**Comment by StefanKock** [comment]
Ticket is outdated after a framework of performance tests was implemented
