### ISSUE TITLE
Separate follow-up until date calculation configurability for cases and contacts [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3100]
### Problem Description
Health departments face the problem that the legislator determined different quarantine/isolation periods for cases and contacts. Since this is connected to the follow-up period and its calculation, the configured calculation in the database doesn't fit either the contacts quarantine period or case isolation period. When users try to reduce the follow-up period, they are limited to the minimal configured period. They then either have to extend every follow-up manually for each case or drop the follow-up for every contact after the quarantine end.
### Proposed Change
Separate the configurability for the follow-up until date calculation for cases and contacts (e.g. 10 days for contacts and 14 days for cases). These values can then be adapted depending on what the legislator determines the minimal quarantine or isolation period to be, without giving the user too much freedom.
### Possible Alternatives
Users could also be given the option to overwrite the follow-up until date and set it to any desired time, meaning that they could reduce it to their liking.

**Comment by bernardsilenou** [comment]
@kwa20 Please can we further refine this in any of our next meetings?

**Comment by kwa20** [comment]
@bernardsilenou Can we remove the "refine" label? I think this is fine after our discussion, isn't it?

**Comment by bernardsilenou** [comment]
1. Use the incubation period of the disease to calculate the followup until date as currently in the system. 
2. Add a new variable to disease configuration called " case follow-up duration" and assign it by default to the incubation period of the disease
3 Add a parameter "case follow-up duration" to server configuration and if set to a date other than the incubation period of the disease, then use the server value in all calculations
3. For all followup other than for cases (eg event participant), use the "contact follow-up duration" in the calculations

**Comment by ChristopherRiedel** [comment]
@bernardsilenou  I would suggest to store the case follow-up duration as the modified follow-up duration in the database in the disease configuration.

**Comment by markusmann-vg** [comment]
Split the configurable follow-up default (minimum days) to
a.) cases
b.) contacts
c.) event participants

**Comment by Candice-Louw** [comment]
Step 2: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3243
