### ISSUE TITLE
Address column in contact detailed view should be split into street, house number and additional information [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3101]
### Feature Description
Address column in contact detailed view.

### Proposed Change
The address column in the contact view should be split into street, house number and additional information. This will provide consistency with the case detailed view and provide more sorting options.

**Comment by markusmann-vg** [comment]
**Reorder** in Detail
Postal Code / City / Street (fka address) / additional information

- [ ] add addit. info column
- [ ] rename address to street
- [ ] reorder
- [ ] Check export
