### ISSUE TITLE
Add "send quarantine order" to task types

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3103]
### Situation Description
Users would like to create tasks that instruct the sending of quarantine orders.
### Feature Description
Add "send quarantine order" as a task type option in the drop-down when creating tasks through contacts or cases.

**Comment by JonasCir** [comment]
FYI: See #2696 . The implementation of the quarantine order document generation should land soon, current progress [here](https://github.com/ImisDevelopers/SORMAS-Project/tree/feature-2696-document-generation-quarantine). Once the changes land, we should discuss how to combine this new feature with the task type you described.

**Comment by MateStrysewske** [comment]
Will be done in #3568
