### ISSUE TITLE
Special characters aren't properly displayed

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3109]
### Bug Description
Examples (person form): "Facility name &amp; description", "Occupation &amp; education"; also German Umlauts aren't properly displayed anymore.

**Comment by MateStrysewske** [comment]
Also, HTML labels don't work anymore

**Comment by MateStrysewske** [comment]
Might be because of the changes in #2859

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
