### ISSUE TITLE
Incorrect behavior on Person forms related to Facility fields

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#3110]
### Bug Description
There are a few issues related to "Facility Category", "Facility Type", "Facility", "Facility name & description"

- [x] Bug 1
### Steps to Reproduce
1. Go to Person form - Home address 
2. "Facility category" and "Facility type" are selected. 
3. Save the form
4. Person is saved but the "Facility category" and "Facility type" are not and become empty after saving

### Expected Behavior
1. the fields should remain unchanged after save.

- [x] Bug 2
### Steps to Reproduce
1. Go to Person form - Home address
2. select "Facility category", "Facility type" and "Facility" and save
3. try to update "Facility category", "Facility type" combo
4. values are available in combo but no matter what value is chosen the combo remains to the initial value

### Expected Behavior
1. should be possible to update values and save

- [x] Bug 3
### Steps to Reproduce
1. Go to Person form - Home address 
2. select "Facility category", "Facility type" and "Facility" and save
3. update Region, District or Community to something which is outside the selected "Facility" infrastructure
4. "Facility category", "Facility type" and "Facility" don't change
5. Save possible
6. After saving the "Address" infrastructure is different from "Facility" infrastructure

### Expected Behavior
1. Address and Facility infrastructure should be the same

### System Details
* Device:
* SORMAS version:1.50.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
