### ISSUE TITLE
Cases | Detailed Export gives an error message

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3112]
### Bug Description
The Detailed Export does not work as expected
### Steps to Reproduce
1. Open test.sormas.netzlink.com environment and log in
2. Go to Cases and click on Export. Select Detailed Export
3. Check the web page for error messages. 
4. Open the downloaded file

### Expected Behavior
There should be no error message + the downloaded file should contain the requested data

###Actual Results
The downloaded .csv file is empty 
The server gives an error message

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/95459320-24a01e00-097c-11eb-8f55-707f2047db9f.png)

### System Details
* Device: Windows 
* SORMAS version: SORMAS Version: 1.50.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/sormas-ui/#!about
* User Role:

**Comment by MateStrysewske** [comment]
See #2936.
