### ISSUE TITLE
Custom Case Export Download Button is not displayed as expected

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3113]
### Steps to Reproduce
1. Open Sormas and go to Cases
2. Click on Export and select Custom Case Export
3. Select some of the fields to be exported, give a name to the export and click on Save
4. On the next pop-up try and download the newly created custom report

### Expected Behavior
The button should be visible and should work as expected. The layout on the pop-up should be auto-calculated based on the resolution.

### Actual Behavior
The buttons are shifted outside of the visible panel from the pop-up.

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/95460936-439faf80-097e-11eb-8d7a-2bc9c8558d70.png)

### System Details
* Device:
* SORMAS version: SORMAS Version: 1.50.0-SNAPSHOT
* Android version/Browser: chrome
* Server URL: 
* User Role:https://test.sormas.netzlink.com

**Comment by MateStrysewske** [comment]
Visual bug that only happens directly after creating the first entry in this table. When you close and re-open the window, everything is displayed fine. Won't be fixed because it's not crucial and won't be a problem once we migrate to a different UI framework.
