### ISSUE TITLE
New automatic task generation for contacts is not configurable

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3115]
### Bug Description
The task generation for contacts that was introduced in the last update is not configurable as for cases.
### Steps to Reproduce
1.
2.

### Expected Behavior
Task generation should be configurable
### System Details
* Device:
* SORMAS version: 1.49.1
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role:

**Comment by MateStrysewske** [comment]
Caused by #2724

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
