### ISSUE TITLE
HTML Tag visible on Case Symptoms page

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3117]
### Bug Description
Development tags are displayed on the Symptoms page

### Steps to Reproduce
1. Open https://test-de.sormas.netzlink.com/sormas-ui/ and open a Case
2. Go to the symptoms page
3. Check the text under clinical signs and symptoms

### Expected Behavior
No development tags should be visible

### Screenshots

![image](https://user-images.githubusercontent.com/70562142/95480618-c16eb580-0994-11eb-83da-ab0cfe072610.png)

### System Details
* Device:
* SORMAS version: SORMAS Version: 1.50.0-SNAPSHOT
* Android version/Browser: Chrome 
* Server URL: https://test-de.sormas.netzlink.com/sormas-ui/

* User Role:

### Additional Information
this is also visible on https://test.sormas.netzlink.com 
Under Cases click on Export and select one type from the list. 

![image](https://user-images.githubusercontent.com/70562142/95481194-67babb00-0995-11eb-8a66-544ddbfddf86.png)

**Comment by MateStrysewske** [comment]
Duplicate of #3109
