### ISSUE TITLE
Cannot configure new facility due to read only fields

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#3119]
## Bug Description
No new facility can be added due to mandatory fields being readOnly in the create form. There is a workaround for this at the moment by using Facility import.

### Steps to Reproduce
1. Go to Configuration -> Facilities -> New Entry
2. Mandatory fields "Facility category" and "Facility type" are readOnly and empty
3. On save "Facility type" is requested but cannot be changed so saving is not possible

### Expected Behavior
The mandatory fields should not be readOnly to make saving a new Facility possible.

### System Details
* SORMAS version: 1.50.0

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT
Admin users can create new facilities and the category+type are not read-only anymore
