### ISSUE TITLE
"Set cleared to unknonw" button should also be translated to other languages

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3121]
### Steps to Reproduce
1. Open Test.sormas.netzlink.com and go to Cases
2. Change the language to german
3. Open one Case and go to the Symptoms page
4. Check the language of the new button

### Expected Behavior
Translations should be consistent on every page for all Languages.
### Actual Behavior
The Set cleared to Unknown button should be translated as well in all languages
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/95551971-7ac0a000-0a14-11eb-8ed4-bf2f4e12a100.png)

This is visible also when Spanish is selected:
![image](https://user-images.githubusercontent.com/70562142/95553925-038d0b00-0a18-11eb-9bb7-eb99d013d8b6.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
This has not been included for the Franch language.

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she Translations are handled via Crowdin and aren't done by us.
