### ISSUE TITLE
Fail to deploy build from source

### ISSUE THREAD

**Issue by GRADeS-Gwen** [hzi-braunschweig/SORMAS-Project#3127]
Since early September, we build and deploy daily from Sormas sources (developement branch). It worked well until we got error a few days ago. Our script was developped so that it will not deploy if there was a build error, so we did not saw the error last week. It was an error on our script that made th build failed. After we corrected it, the build worked on the lasts commits from the "development" branch, but we got errors after deployment. I tried to get the last commit that work and it seem it is the "538c2423aa59bdbf38839e69061814e68a7848a5" from 24/09. I tried more recent commit and got the deployment errors. It seem that it worked well on 1.49-snaphsot, but faild since it is in 1.50-snapshot.

Here is the log from today deployment try : [server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/5355857/server.log)

If you could help use to solve our dev environement runtime, that would

 be nice.

Best regard.

**Comment by MateStrysewske** [comment]
Hey, we haven't encountered this issue on our dev systems, so it doesn't seem to be a general problem. Have you tried another mvn-install?

**Comment by GRADeS-Gwen** [comment]
Does not work any better. Here is my process to deploy, maybe I need to correct something:
```
git checkout development
git pull
mvn -B install --file ./sormas-base/pom.xml
systemctl stop payara-sormas
rm -f /opt/domains/sormas/autodeploy/*
mv */target/*.[ew]ar /opt/domains/sormas/autodeploy/
systemctl start payara-sormas
```
nb: I used generally "package" and not "install" but the result seems to be the same.

The result of the mvn-install is:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for sormas-base 1.51.0-SNAPSHOT:
[INFO]
[INFO] sormas-base ........................................ SUCCESS [  1.172 s]
[INFO] sormas-widgetset ................................... SUCCESS [  2.934 s]
[INFO] sormas-api ......................................... SUCCESS [ 11.005 s]
[INFO] sormas-backend ..................................... SUCCESS [09:51 min]
[INFO] sormas-ear ......................................... SUCCESS [  2.535 s]
[INFO] sormas-rest ........................................ SUCCESS [  7.301 s]
[INFO] sormas-ui .......................................... SUCCESS [01:03 min]
[INFO] sormas-serverlibs .................................. SUCCESS [  9.987 s]
[INFO] sormas-cargoserver ................................. SUCCESS [  0.656 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:30 min
[INFO] Finished at: 2020-10-15T10:21:47+02:00
[INFO] ------------------------------------------------------------------------
```

And I join the log from the server. [server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/5384136/server.log)

I there anything to change or tweak maybe in my process ?

**Comment by MateStrysewske** [comment]
Gonna tag @HolgerReiseVSys here because he has more knowledge about payara than I do and @leventegal-she because there's an exception message in that log that hints at the PseudonymizableDto being the issue; however, since it works for other developers, I guess there's not really a problem with the code there. Seems more like a server/setup issue.

**Comment by leventegal-she** [comment]
Hi @GRADeS-Gwen, did you try to do `mvn clean`.

Can you please try to build your project with the following command?

```
mvn -B clean package --file ./sormas-base/pom.xml
```

**Comment by GRADeS-Gwen** [comment]
it worked ! It was so simple ... I am ashmed of myself ...

on my deployment script, should I use "clean package" on each build ? (we build every night)

**Comment by leventegal-she** [comment]
Yes, it is recommended to use clean before building the new sources.

`install` does the same as package plus puts the packages in your local maven repository.

Your script just copies the packages from the target folders into the payara domain so it is enough to use  "clean package"

**Comment by GRADeS-Gwen** [comment]
Thank you for you advise, I will do that.
