### ISSUE TITLE
Filter by responsible surveillance officer does not work

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3128]
### Steps to Reproduce
1. Create a case in a district with responsible surveillance officer account
2. Assign the case to your responsible officer 
3. Filter the case directory and the field is empty

### Expected Behavior
- Cases, contacts and events directories should be possible to be filtered based on the responsible SO
- When a region and district is selected, this should also limit the number of SO accounts displayed in the drop-down

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/95607868-a1a2c480-0a5c-11eb-9b12-a12560824a89.png)

### System Details
* Device: web
* SORMAS version: 1,49,1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.50.0-SNAPSHOT

**Comment by markusmann-vg** [comment]
Only done for cases => Contacts and Event directories will have to be added

**Comment by StefanKock** [comment]
> Only done for cases => Contacts and Event directories will have to be added

This ticket was delivered in Sprint 94, so reopen is not valid. I created a follow-up ticket: #3590
