### ISSUE TITLE
Information box on sample and event form is not translated

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3131]
### Steps to Reproduce
1.
2.

### Expected Behavior
- Should be translated to the user specified language
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/95662651-c8362d80-0b38-11eb-9e6d-dd757364a107.png)

### System Details
* Device: web
* SORMAS version: 1,49,1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
Only affects samples and events as far as I can tell.

**Comment by StefanKock** [comment]
Minor problem and not easy to resolve.
