### ISSUE TITLE
Add cluster and screening counts on surveillance dashboard

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3132]
### Feature Description
- Cluster and screening statuses are part of event but not shown on dashboard
### Proposed Change
- Add counts for cluster and screening
- Use red  and follow this order
![image](https://user-images.githubusercontent.com/12996724/95663169-311fa480-0b3d-11eb-96eb-38b6ca9df38f.png)

**Comment by Candice-Louw** [comment]
Duplicate of: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2815 ?

**Comment by bernardsilenou** [comment]
@Candice-Louw Yes please, thanks for correction
