### ISSUE TITLE
Attach a contact to an event (from the contacts directory)

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3133]
### Situation Description
To date, users can link a case to an event from the case directory. This feature does not exist for contacts.

### Feature Description
Like the cases, develop in the case file a data block to include the list of events in which the contact is involved. 
Same information as the block integrated in the case sheet: description of the event, region, district, municipality, date of the event. I only propose to replace the description of the event with the title of the event which will be available from v 1.50.
All events in which the contact has been involved will be displayed. A check mark will restrict the events to those for which the contact and its zero case is involved.

This block will also integrate a button to attach a contact to an event, or conversely, to break this link (in the event of improper handling for example)

### Additional Information
![image](https://user-images.githubusercontent.com/65449450/95724221-5d8b0c00-0c76-11eb-83fb-7fa379d0ade9.png)

@ftavin @olivierleuci @bernardsilenou

**Comment by bernardsilenou** [comment]
@carolinverset This sounds good. One point i would like to recommend is that issue #3035 restrict the linking of event participants to contacts only when case 0 is also in the event. Before we implement this issue, it would be good to extend issue #3035 to include also contacts whose case 0 is not in the event.
In summary:
1. We implement issue  #3035 as it it
2. We implement a generalized version of  issue  #3035 with the optional parameter to link event participants to contact whose source case is not on the event
3. Implement this issue

**Comment by ftavin** [comment]
@MateStrysewske : @alexandre-gille is now working on this one (a PR was submited yesterday for 3035)

**Comment by MateStrysewske** [comment]
Follow-up issue: #3566

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT
