### ISSUE TITLE
Cases > "Clinical Signs and Symptoms" reordering [3]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3152]
### Feature Description
The existing SORMAS Symptoms are requested to be grouped and reordered according to the different medical systems.

### Problem Description
Currently, "Clinical Signs and Symptoms" for Cases (Cases > Open Case > Symptoms) for are listed in a random order which makes entering and working with the entries troublesome.

![image](https://user-images.githubusercontent.com/65529128/95828316-20398380-0d35-11eb-9ae0-c125fa0ef5ed.png)

This is the same for Cases + Contacts > Follow-up > Masks (https://github.com/hzi-braunschweig/SORMAS-Project/issues/2668)
Original CH posts: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/107 & https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/8

### Proposed Change

Group and sort the symptoms according to the different medical systems:

![image](https://user-images.githubusercontent.com/65529128/95825724-9a680900-0d31-11eb-9722-0aa77eeb9ef7.png)

![image](https://user-images.githubusercontent.com/65529128/95825821-bc618b80-0d31-11eb-914c-8fe5a6f8a79b.png)

![image](https://user-images.githubusercontent.com/65529128/95826342-70631680-0d32-11eb-8923-9f7b784d1321.png)

![image](https://user-images.githubusercontent.com/65529128/95826435-938dc600-0d32-11eb-9f3a-9b325064aa90.png)

### Additional Information
Related to: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2668
CH post: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/107

**Comment by bernardsilenou** [comment]
@Candice-Louw  I think this grouping is very important for all instances. 
Are all the symptoms fro covid for all servers listed here? , If not can can you help to group them also?
Thanks

**Comment by ChristopherRiedel** [comment]
@Candice-Louw Since the symptoms are displayed for all countries, it is not easy to sort the symptoms according to the specifications of a single country. Other countries may prefer a different order or grouping.

**Comment by JonasCir** [comment]
@Candice-Louw Maybe HZI can help to refine this and roughly group the symptoms. I think having them organized and placed under a label would really help people to navigate this page :)

**Comment by bernardsilenou** [comment]
@Candice-Louw  yea, we need to do do as you say. Another challenge i can see is the fact that if we organize the list of symptoms; we may need to do for all symptoms and the category names may differ from disease to disease. When we meet next week we can discuss further how to go about it

**Comment by markusmann-vg** [comment]
- [ ] Sections need to be hidden, when there is no symptom

@Candice-Louw Please provide a definition for all the symptoms to which sections they belong.

**Comment by Candice-Louw** [comment]
General \| Allgemein |  
-- | --
public static final String FEELING_ILL = "feelingIll"; | public static final String WEAKNESS = "weakness";
public static final String SHIVERING = "shivering"; | public static final String HEADACHE = "headache";
public static final String FEVERISHFEELING = "feverishFeeling"; | public static final String MUSCLE_PAIN = "musclePain";
public static final String CHILLS_SWEATS = "chillsSweats"; | public static final String BEDRIDDEN = "bedridden";
public static final String FATIGUE = "fatigue"; | public static final String FATIGUE_WEAKNESS = "fatigueWeakness";
public static final String MALAISE = "malaise"; | public static final String FEVER = "fever";
public static final String JOINT_PAIN = "jointPain"; | public static final String BACKACHE = "backache";




Respiratory \| Atemwege |  
-- | --
public static final String RUNNY_NOSE = "runnyNose"; | public static final String BREATHLESSNESS = "breathlessness";
public static final String SORE_THROAT = "soreThroat"; | public static final String CHEST_PRESSURE = "chestPressure";
public static final String COUGH_WITHOUT_SPUTUM = "coughWithoutSputum"; | public static final String CHEST_PAIN = "chestPain";
public static final String COUGH_WITH_SPUTUM = "coughWithSputum"; | public static final String BLUE_LIPS = "blueLips";
public static final String COUGH_WITH_HEAMOPTYSIS = "coughWithHeamoptysis"; | public static final String FLUID_IN_LUNG_CAVITY = "fluidInLungCavity";
public static final String RAPID_BREATHING = "rapidBreathing"; | public static final String FLUID_IN_LUNG_CAVITY_AUSCULTATION = "fluidInLungCavityAuscultation";
public static final String DIFFICULTY_BREATHING = "difficultyBreathing"; | public static final String FLUID_IN_LUNG_CAVITY_XRAY = "fluidInLungCavityXray";
public static final String ABNORMAL_LUNG_XRAY_FINDINGS = "abnormalLungXrayFindings"; | public static final String IN_DRAWING_OF_CHEST_WALL = "inDrawingOfChestWall";
public static final String ACUTE_RESPIRATORY_DISTRESS_SYNDROME = "acuteRespiratoryDistressSyndrome"; | public static final String PNEUMONIA_CLINICAL_OR_RADIOLOGIC = "pneumoniaClinicalOrRadiologic";
public static final String COUGH = "cough"; | public static final String WHEEZING = "wheezing";
public static final String COUGHING_BLOOD = "coughingBlood"; | public static final String RESPIRATORY_DISEASE_VENTILATION = "respiratoryDiseaseVentilation";
  | public static final String OXYGEN_SATURATION_LOWER_94 = "oxygenSaturationLower94";




Cariovascular \| Herz-Kreislauf |  
-- | --
public static final String BLOOD_CIRCULATION_PROBLEMS = "bloodCirculationProblems"; | public static final String DIZZINESS_STANDING_UP = "dizzinessStandingUp";
public static final String FAST_HEART_RATE = "fastHeartRate"; | public static final String HIGH_OR_LOW_BLOOD_PRESSURE = "highOrLowBloodPressure";
public static final String PALPITATIONS = "palpitations"; | public static final String OEDEMA_FACE_NECK = "oedemaFaceNeck";
public static final String CONGENITAL_HEART_DISEASE = "congenitalHeartDisease"; | public static final String OEDEMA_LOWER_EXTREMITY = "oedemaLowerExtremity";
public static final String CONGENITAL_HEART_DISEASE_DETAILS = "congenitalHeartDiseaseDetails"; |  
public static final String CONGENITAL_HEART_DISEASE_TYPE = "congenitalHeartDiseaseType"; |  




Gastrointestinal \| Magen-Darm |  
-- | --
public static final String NAUSEA = "nausea"; | public static final String DIARRHEA = "diarrhea";
public static final String VOMITING = "vomiting"; | public static final String URINARY_RETENTION = "urinaryRetention";
public static final String ABDOMINAL_PAIN = "abdominalPain"; | public static final String RED_BLOOD_VOMIT = "redBloodVomit";
public static final String DEHYDRATION = "dehydration"; | public static final String STOMACH_BLEEDING = "stomachBleeding";
public static final String ANOREXIA_APPETITE_LOSS = "anorexiaAppetiteLoss"; | public static final String BLOODY_BLACK_STOOL = "bloodyBlackStool";
public static final String REFUSAL_FEEDOR_DRINK = "refusalFeedorDrink"; | public static final String BLOOD_IN_STOOL = "bloodInStool";
  | public static final String DIGESTED_BLOOD_VOMIT = "digestedBloodVomit";




Urinary tract/Kidney |  
-- | --
public static final String URINARY_RETENTION = "urinaryRetention"; | public static final String BLOOD_URINE = "bloodUrine";
public static final String DARK_URINE = "darkUrine"; |  



Nervous System |  
-- | --
public static final String AEROPHOBIA = "aerophobia"; |  
public static final String AGITATION = "agitation"; |  
public static final String ASCENDING_FLACCID_PARALYSIS = "ascendingFlaccidParalysis"; | public static final String HYPERACTIVITY = "hyperactivity";
public static final String DELIRIUM = "delirium"; | public static final String UPROARIOUSNESS = "uproariousness";
public static final String CONVULSION = "convulsion"; | public static final String OPISTHOTONUS = "opisthotonus";
public static final String ERRATIC_BEHAVIOUR = "erraticBehaviour"; | public static final String MENINGOENCEPHALITIS = "meningoencephalitis";
public static final String EXCITATION = "excitation"; | public static final String PARALYSIS = "paralysis";
public static final String HYDROPHOBIA = "hydrophobia"; | public static final String TREMOR = "tremor";
public static final String DYSPHAGIA = "dysphagia"; | public static final String ANXIETY_STATES = "anxietyStates";
public static final String PARESIS = "paresis"; |  




Skin \| Haut |  
-- | --
public static final String SKIN_RASH = "skinRash"; | public static final String LESIONS_ALL_OVER_BODY = "lesionsAllOverBody";
public static final String PURPURIC_RASH = "purpuricRash"; | public static final String LESIONS_ARMS = "lesionsArms";
public static final String SKIN_ULCERS = "skinUlcers"; | public static final String LESIONS_DEEP_PROFOUND = "lesionsDeepProfound";
public static final String BLACKENING_DEATH_OF_TISSUE = "blackeningDeathOfTissue"; | public static final String LESIONS_FACE = "lesionsFace";
public static final String LESIONS = "lesions"; | public static final String LESIONS_LEGS = "lesionsLegs";
  | public static final String LESIONS_PALMS_HANDS = "lesionsPalmsHands";




Other \| Weitere |   |  
-- | -- | --
public static final String LOSS_OF_SMELL = "lossOfSmell"; | Other, other clinical signs and symptoms + freetext |  
public static final String LOSS_OF_TASTE = "lossOfTaste"; | public static final String LOSS_SKIN_TURGOR = "lossSkinTurgor"; |  
public static final String PALPABLE_LIVER = "palpableLiver"; | public static final String LYMPHADENOPATHY = "lymphadenopathy"; |  
public static final String BILATERAL_CATARACTS = "bilateralCataracts"; | public static final String LYMPHADENOPATHY_AXILLARY = "lymphadenopathyAxillary"; |  
public static final String BLEEDING_VAGINA = "bleedingVagina"; | public static final String LYMPHADENOPATHY_CERVICAL = "lymphadenopathyCervical"; |  
public static final String BUBOES_GROIN_ARMPIT_NECK = "buboesGroinArmpitNeck"; | public static final String LYMPHADENOPATHY_INGUINAL = "lymphadenopathyInguinal"; |  
public static final String BULGING_FONTANELLE = "bulgingFontanelle"; | public static final String NECK_STIFFNESS = "neckStiffness"; |  
public static final String COMA = "coma"; | public static final String NOSE_BLEEDING = "noseBleeding"; |  
public static final String CONGENITAL_GLAUCOMA = "congenitalGlaucoma"; | public static final String ORAL_ULCERS = "oralUlcers"; |  
public static final String CONJUNCTIVITIS = "conjunctivitis"; | public static final String OTHER_HEMORRHAGIC_SYMPTOMS = "otherHemorrhagicSymptoms"; |  
public static final String DEVELOPMENTAL_DELAY = "developmentalDelay"; | public static final String OTHER_NON_HEMORRHAGIC_SYMPTOMS = "otherNonHemorrhagicSymptoms"; |  
public static final String EXCESS_SALIVATION = "excessSalivation"; | OTHER_NON_HEMORRHAGIC_SYMPTOMS_TEXT |  
public static final String EYES_BLEEDING = "eyesBleeding"; | public static final String OTITIS_MEDIA = "otitisMedia"; |  
public static final String EYE_PAIN_LIGHT_SENSITIVE = "eyePainLightSensitive"; | public static final String PAINFUL_LYMPHADENITIS = "painfulLymphadenitis"; |  
public static final String GLASGOW_COMA_SCALE = "glasgowComaScale"; | public static final String PALPABLE_SPLEEN = "palpableSpleen"; |  
public static final String GUMS_BLEEDING = "gumsBleeding"; | public static final String PARASTHESIA_AROUND_WOUND = "paresthesiaAroundWound"; |  
public static final String HEARINGLOSS = "hearingloss"; | public static final String PHARYNGEAL_ERYTHEMA = "pharyngealErythema"; |  
public static final String HICCUPS = "hiccups"; | public static final String PHARYNGEAL_EXUDATE = "pharyngealExudate"; |  
public static final String INABILITY_TO_WALK = "inabilityToWalk"; | public static final String PIGMENTARY_RETINOPATHY = "pigmentaryRetinopathy"; |  
public static final String INJECTION_SITE_BLEEDING = "injectionSiteBleeding"; | public static final String RADIOLUCENT_BONE_DISEASE = "radiolucentBoneDisease"; |  
public static final String INSOMNIA = "insomnia"; | public static final String SIDE_PAIN = "sidePain"; |  
public static final String JAUNDICE = "jaundice"; | public static final String SPLENOMEGALY = "splenomegaly"; |  
public static final String JAUNDICE_WITHIN_24_HOURS_OF_BIRTH = "jaundiceWithin24HoursOfBirth"; | public static final String SUNKEN_EYES_FONTANELLE = "sunkenEyesFontanelle"; |  
public static final String KOPLIKS_SPOTS = "kopliksSpots"; | public static final String SWOLLEN_GLANDS = "swollenGlands"; |  
  | public static final String THROBOCYTOPENIA = "throbocytopenia"; | Needs to be: THROMBOCYTOPENIA = "thrombocytopenia";
  | public static final String UNEXPLAINED_BLEEDING = "unexplainedBleeding"; |  
  | public static final String UNILATERAL_CATARACTS = "unilateralCataracts"; |

**Comment by JonasCir** [comment]
Thank you @Candice-Louw

**Comment by fhauptmann** [comment]
Desicion: 

- introduce grouping
- have the UI display the symtoms grouped
- sort description alphabetically (displayed language) in group

**Comment by markusmann-vg** [comment]
Agreed with Maté that we do not do the alphabetical order as this is not yet implemented
