### ISSUE TITLE
Display the list of campaign data for a campaign in the mobile app [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3161]
### Situation Description
#3150 and #3151 synchronize all needed campaign data to the mobile device.

### Feature Description

The following elements are needed in the mobile app:

- [x] add a menu entry for campaigns when the feature is enabled
- [x] add an activity to list all campaign data entries
  - [x] should by default show the data of one campaign. pre-select the last campaign that has already started
  - [x] display the name of the campaign in the header, or "all campaigns" when no campaign is selected
  - [x] each list entry should show form name, date, region, district, cluster
- [x] add filters to the list, e.g. like the ones we have for cases
  - [x] campaign
  - [x] campaign form

**Comment by StefanKock** [comment]
Taken out of Sprint 97 in favor for #3152

**Comment by MartinWahnschaffe** [comment]
Meeting results:

- [ ] Change "Campaign listing" to "Campaign data" - in other words have the same name as the campaign data view in the UI: https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!campaign
- [ ] Display date as form date
- [ ] Remove "Mark all" from the contextual menu from the top right. Replace the contextual menu with a sync icon only
