### ISSUE TITLE
Allow custom series name for campaign diagrams [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3163]
### Feature Description
Currently campaign diagrams use the name of the field to display the related series in the dashboard.

### Proposed Change
Extend the campaign diagram definition to also have an optional name for each series. This will mostly used to provide a shorter name that is displayed in the chart - especially in the legend.

- [x] Extend the CampaignDiagramSeries with an optional caption property
- [x] When creating a diagram for the dashboard, check if a caption is defined and if so, apply it to the series
- [x] Extend the Wiki page for defining campaign diagram series

Out of scope: This does not include translation.

Example:

```
[
{"fieldId":"childrenLivingInHouses","formId": "vaccinationMonitoring","caption":"Children in houses"},
{"fieldId":"missedChildren","formId":"vaccinationMonitoring","caption":"Missed children"}
]
```

**Comment by tomabadaniel** [comment]
We need to be able to allow one series name that appears in multiple forms to show only one unique value in the legend of the diagram. Custom series name change alone wont fix this. A clear example is Days 1-3 and Revisits having the same legend names like Absent, Absent, Refusal, Refusal respectively. This needs to show only one legend value per diagram if its the same series name

<img width="952" alt="duplicate legend values" src="https://user-images.githubusercontent.com/60390281/97875763-e252ce00-1ce8-11eb-93a5-47c87f4324f7.png">

**Comment by MartinWahnschaffe** [comment]
@tomabadaniel As discussed today, we will keep the legend entries for now and go with custom colors #2895 and custom series names #3163
