### ISSUE TITLE
Some events are not suggested after searching when trying to link cases to events

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3164]
### Bug Description
When trying to link a case to an event, not all the existing events are suggested when the event description is searched for. This seems to mainly apply for newly created events.
### Steps to Reproduce
1. create a case and an event independently. 
2. Link case to event through the case information.
3. Search for the event that you have created.
4. Check whether it appears in the list below.

### Expected Behavior
Searching for event description should display associated event.
### Screenshots
<img width="1055" alt="Screen Shot 2020-10-13 at 3 23 25 PM" src="https://user-images.githubusercontent.com/70317594/95870437-c359bf80-0d6c-11eb-8f4d-82f6a36e8929.png">
<img width="1086" alt="Screen Shot 2020-10-13 at 3 22 43 PM" src="https://user-images.githubusercontent.com/70317594/95870453-cbb1fa80-0d6c-11eb-9e9e-b2b61a74e22a.png">

### System Details
* Device:
* SORMAS version: 1.49.1
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin

**Comment by bernardsilenou** [comment]
@kwa20  I can see from your figure that the event has no disease, thus this is expected to happen. Please add a disease to the event  and give it about 2 min to sink with db and try to link case again

**Comment by kwa20** [comment]
@bernardsilenou you're right! It appears when adding the disease. I'd like to get in touch with the health department that experienced this kind of problem and see if that also fixes their problem before closing this issue.

**Comment by bernardsilenou** [comment]
@kwa20 OK,
We thought of making the disease compulsory but this does not match with real life situations, especially when it is just a signal and  we may have no information about the disease at the time that the signal was created. It was deliberately designed like this. I have not tested, but you should not be able to convert an event participant to case if the event has no disease, your first have to assign a disease to the event. So it works in both directions

**Comment by kwa20** [comment]
Converting a participant into a case is possible when the event has no disease. Disease will be pre-selected.
<img width="717" alt="Screen Shot 2020-10-14 at 7 48 06 AM" src="https://user-images.githubusercontent.com/70317594/95948960-f4c89e80-0df1-11eb-852f-205dd73fed8e.png">
<img width="778" alt="Screen Shot 2020-10-14 at 7 48 55 AM" src="https://user-images.githubusercontent.com/70317594/95948968-f98d5280-0df1-11eb-96e5-259af5b9b12e.png">
