### ISSUE TITLE
Extremely long time to load the dashboard

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3167]
### Feature Description
- We want to reduce the time needed to load information on the dashboard. We would load important indicators first and display the dashboard to the user while loading other indicators latter. It was suggested to:
- not load the map at initial loading of the dashboard
- alternatively give only regional users the assess to the dashboard in case the delay may be due to many users assessing the dashboard at the same time.

### Problem Description
- On centralized servers with hundreds of thousands of entities, it takes more than 5 min to load the dashboard. The default dashboard time is the past 7 days but this may still result in thousand of cases and contacts especially when using sormas at the country level. 
### Proposed Change
- Run a performance test to diagnose the cause and do necessary changes like "not loading map at initial loading of the dashboard".
- Apply changes to both surveillance and contact dashboards

**Comment by MartinWahnschaffeSymeda** [comment]
As a first step we should do the following: 

- [ ] Don't show the map when there are more than 100 cases or contacts
- [ ] Instead provide a button to "display map"
- [ ] Add an entry to the properties file that allows to enable this behaviour. For now it should be disabled by default. This will allow us to have a test in one of the countries that suffer from bad dashboard performance.

**Comment by HolgerReiseVSys** [comment]
> As a first step we should do the following:
> 
>     * [ ]  Don't show the map when there are more than 100(0) cases or contacts
> 
>     * [ ]  Instead provide a button to "display map"

Maybe we should use this approach for the network diagram, too (with extremely low threshold)
