### ISSUE TITLE
Add feature configuration for outbreak [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3171]
### Feature Description
Enabling the "outbreak"-mode for a district allows users to enter data in a reduced data entry mode for some diseases.

### Problem Description
The feature and configuration section for it should not be visible on systems that don't make use of this.

### Proposed Change
- [x] Add the OUTBREAKS feature type
- [x] Configuration/Outbreaks should only be visible when it's active
- [x] Only show data in outbreak mode in UI when feature is enabled (look for usages of OutbreakFacade.hasOutbreak and Disease.useSimpleViewForOutbreaks

by default the feature is enabled

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT
