### ISSUE TITLE
Import campaign form data template is not as expected. All fields are in a single row

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3173]
### Bug Description
The import template for campaigns is incorrect and all fields are shown in the first row and first column.
 
### Steps to Reproduce
1. Login to APMS as National Cordinator
2. Select Campaigns and click on Import at the top right 
3. Select any of the import forms and select a campaign and click on download import template
4. Open the downloaded csv and see if the fields are placed in different rows and columns.

### Expected Behavior
The fields in the import template has to be in an organized manner separated into respective rows per field/category

### Screenshots
![import template_campaigns](https://user-images.githubusercontent.com/62763628/95962889-42033b00-0e07-11eb-8758-e1e82f9ef4b7.PNG)

### System Details
* Device:
* SORMAS version: 1.50.snapshot
* Android version/Browser: chrome and firefox
* Server URL: https://test-afghanistan.sormas.netzlink.com/
* User Role: National Coordinator / Provisonal / District

**Comment by raghupola-vg** [comment]
#1999

**Comment by danRosca** [comment]
Concluded along with @raghupola-vg that this issue is not reproducible.
