### ISSUE TITLE
[CLIMEDO Integration] Umlauts are displayed incorrectly on the ga1 environment

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3176]
### Bug Description
All German umlaut letters (ä, ö, ü) are displayed incorrectly on the ga1 instance.

### Steps to Reproduce
1. Open https://ga1.sormas-oegd.de/sormas-ui
2. Change language to German
3. Open any page with text containing umlauts

### Screenshots
![image](https://user-images.githubusercontent.com/65336966/95973417-4d149600-0e1c-11eb-84ed-c881524b88f7.png)

**Comment by MateStrysewske** [comment]
Which version is that system on?

**Comment by vlad-ciucescu** [comment]
1.50, development was recently merged into the climedo_integration branch

**Comment by MateStrysewske** [comment]
Can you confirm that #3109 is part of the state that the server is on? The problem was fixed in that issue and it's working absolutely fine on my system.

**Comment by vlad-ciucescu** [comment]
It seems that the bug was fixed after development was merged into climedo_integration. 
Perhaps we should leave this issue open until the climedo_integration branch is updated and the bug is also fixed on this environment?

**Comment by MateStrysewske** [comment]
No, since the bug was already fixed in the mentioned issue. :)
