### ISSUE TITLE
[CLIMEDO Integration] Trigger CLIMEDO update when updating person data/followup data from mobile app

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3178]
### Situation Description
Currently, when updating person data or contact followup up date in the webapp, CLIMEDO is notified to fetch the updated data.

### Feature Description
The same functionality should be implemented in the mobile app when modifying person data or contact follow up date.

**Comment by markusmann-vg** [comment]
should work as is....
data we send: first name, last name, birthdate, gender, phone number, email, followupenddate

**Comment by vlad-ciucescu** [comment]
Updating person data from mobile app triggers the update in CLIMEDO
