### ISSUE TITLE
Create a documentation for the SORMAS external journal REST API [2]

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3180]
### Situation Description
The SORMAS REST API used by external journals is found in `ExternalVisitResource`. This is used by PIA and CLIMEDO and may be used by other symptom journals in the future.

### Feature Description
To make adoption in the future easier, create a documentation for this REST API detailing the endpoints, the data models etc. 

### Possible Alternatives
Swagger is set-up in SORMAS. If the endpoints and classes are properly annotated, the Swagger page of the ExternalVisitsResource can serve as documentation.

**Comment by FredrikSchaeferVitagroup** [comment]
We discussed this previously. It was decided to use the swagger page as documentation, because that updates automatically in case of changes. 
The way to read this information is described in the readme and documentation tags are written in the ExternalVisitsRessource.
What is left to do here?

**Comment by vlad-ciucescu** [comment]
I created these following the request in our review. If the Swagger page is sufficient then I am fine with closing this, but the question is if we can share only the Swagger documentation of the External Visits Resource? As far as I know the Swagger page documents all SORMAS REST methods.

**Comment by markusmann-vg** [comment]
[Vorlage_Spezifikation_Schnittstelle.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5390329/Vorlage_Spezifikation_Schnittstelle.docx)

**Comment by vidi42** [comment]
will be covered by #3372
