### ISSUE TITLE
Remove the GET quarantineEndDates from ExternalVisitsRessource [0]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3182]
### Problem Description

This is deprecated and replaced by the GET followUpEndDates, which shall be used from all external symptom journals.
Conventic just confirmed that this adaption was merged into their development branch on 13.10.2020. SInce it takes time for them to release, this issue should be taken care of in november 2020.

### Proposed Change

Just remove the GET quarantineEndDates and all methods solely used by it.

### Possible Alternatives

Would be to leave it. This might be problematic because SORMAS then offers more information than necessary which might lead to data protection issues and misunderstanding as well as misuse of the followUpUntil and quarantineEndDate.

**Comment by markusmann-vg** [comment]
linked to https://github.com/hzi-braunschweig/SORMAS-Project/issues/3195

**Comment by FredrikSchaeferVitagroup** [comment]
> linked to #3195

Yes, but this change has clearly been communicated and adaptions took place on conventic side.

**Comment by AndyBakcsy-she** [comment]
Moving the issue to the Done Lane as the changes can be seen only in the Code.
