### ISSUE TITLE
Timeout during data export

### ISSUE THREAD

**Issue by TomHutter** [hzi-braunschweig/SORMAS-Project#3185]
### Bug Description

Contact export ob about 13.000 contacts is not possible. After a long time a error message appears (attached). 

### Steps to Reproduce
1. export contacts by clicking on export in "Kontaktverzeichnis"

### Screenshots

![Screenshot_20201014_174750](https://user-images.githubusercontent.com/1071037/96013592-bc52b000-0e45-11eb-9ead-653401433eb3.png)

### System Details
* Device: sormas-docker: 2.11.0
* SORMAS version: 1.49.1
* Android version/Browser: --
* Server URL: https://rhein-sieg-kreis.sormas-oegd.de
* User Role: unknown

### Additional Information
attached Java stack trace

[time_out_exception.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/5379403/time_out_exception.log)

**Comment by MateStrysewske** [comment]
#3137 will hopefully also have a positive impact on this issue.

**Comment by nliakm** [comment]
We found out, that the timeout happens after exactly 5 minutes. The payara has some timeouts defined in the domain.xml.
As a workaround, we changed the following values from 300 to 0 and the export was succesful afterwards:
```
      <transaction-service tx-log-dir="${com.sun.aas.instanceRoot}/logs" timeout-in-seconds="300">
        <property name="xaresource-txn-timeout" value="300"></property>
      <transaction-service automatic-recovery="true" tx-log-dir="${com.sun.aas.instanceRoot}/logs" timeout-in-seconds="300">
        <property name="xaresource-txn-timeout" value="300"></property>
```

**Comment by MartinWahnschaffe** [comment]
The slowness of the export is adressed in #4316 and #4307
