### ISSUE TITLE
[CLIMEDO Integration] Add follow-up date validation for persons to be registered/updated in CLIMEDO

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3187]
### Situation Description
* Besides the person data, the follow up until date of the contact is also sent to CLIMEDO when the person is registered or updated. 
* CLIMEDO accepts follow up dates starting from the current date up to 42 days later (to be confirmed). 
* Currently, there is no validation of this date on SORMAS side. 
* Requests to CLIMEDO fail if the follow up until date is not in the previously mentioned interval.

### Feature Description
* if the person is not yet registered in CLIMEDO, validate the follow up until date when the Patient diary button is clicked and display a warning popup if the date is invalid.
* if the person is already registered in CLIMEDO, validate the follow up until date when it is changed in the contact page and display a warning popup if the date is invalid.

### Additional Information
The same logic is used in the case of person data. Please check the `isPersonExportable` method in `ExternalJournalService`.

**Comment by markusmann-vg** [comment]
won't do !

**Comment by bernardsilenou** [comment]
@vlad-ciucescu  soma cases may be sick for a long time and the followup until date in sormas can be extended from the default 14 days to more than 42 days

**Comment by MateStrysewske** [comment]
@bernardsilenou We've just talked about this in our planning and decided to not implement this change request because of the exact reason that you specified.
