### ISSUE TITLE
[CLIMEDO Integration] Updating person email/phone number to one already existing in CLIMEDO leads to data inconsistency

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3188]
### Bug Description
* CLIMEDO requires that an email/phone number is used by a single patient
* Fixing bug #3162 has introduced an asynchronous operation in the person update flow. This means that the person data is saved and persisted in the SORMAS database and afterwards a separate thread continues the update flow with CLIMEDO.
* It is possible in this way to update a person with an email/phone number which is already used by another patient in CLIMEDO. This email/phone number will be persisted in the SORMAS database.
* CLIMEDO is notified separately of the update and they retrieve the updated data, but it is rejected, because the email/phone number is already in use.
* Data between SORMAS and CLIMEDO is now inconsistent since the new data was refused by CLIMEDO

### Steps to Reproduce
1. Open https://ga1.sormas-oegd.de/sormas-ui
2. Open the contacts directory and open a contact with the status 'REGISTERED'
3. Open the person data tab
4. Change the email or phone number of the person to one which is already in use in CLIMEDO (Check [here](https://ga1.climedo.de/de/studies/5f60d22772f71c001158cea6/data))
5. Save the changes. The person data is updated in SORMAS.
6. Go to the CLIMEDO page by clicking the Patient diary button. Select the patient. The data was not updated.

### Expected Behavior
After pressing the save changes button in SORMAS, a popup notifies the user that the email/phone number is already in use in CLIMEDO and that they should provide another one.

### Additional Information
The PUT request done from SORMAS to CLIMEDO fails with the following response:
`{
    "success": false,
    "message": "A patient with same email already exist",
    "_id": "5f85abd480d12a001114b8a1"
}`
However, this PUT request is done in a separate thread (since #3162 was fixed). For this reason, no error is displayed in the UI and the data in SORMAS remains saved.

**TBD**: 
* solving this issue requires a new endpoint from CLIMEDO which informs us whether the email/phone number is already taken. This endpoint should be called when pressing the save changes button in the person details.
* another option is that person data is sent directly from SORMAS to CLIMEDO in the PUT request. This would mean that the asynchronous logic is no longer needed and the error from CLIMEDO can be processed immediately.

**Comment by markusmann-vg** [comment]
Workaround until the Climedo side delivers the API Extension:
- [ ] Check if persons marked as registered do have the same mail address in Climedo and SORMAS 
- [ ] Discuss with CLIMEDO how this situation can be handled
- [ ] Solve the issue

**Comment by AndyBakcsy-she** [comment]
Verified issue on :SORMAS Version: 1.52.0-SNAPSHOT using the https://ga1.sormas-oegd.de/sormas-ui/ environment
Tried to save the email address for a registered contact, by typing the same address from another registered contact. An Error message was displayed : The email is already in use in the system journal Email validation works as expected. 

Phone Number validation is still pending due to environment setup .
