### ISSUE TITLE
Event location refinement

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3190]
### Bug Description
- This is not a bug but might just be incorrect specification.  For the  event entity, the type of place is not related to the recently added facility categories, types and names. We need a validation between categories of "type of place" and those of "facility category", "facility type", etc
### Steps to Reproduce
1. Create an event  with type of place == transport/ home
2. system ask you for facility categories that are not related to means of transport

### Expected Behavior
-See comments in screenshot
- we may need to migrate some of the options is facility type like hospitals, festivities etc

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/96055629-db246700-0e84-11eb-9bf5-3e6b77d88534.png)

### System Details
* Device:
* SORMAS version: 1,50
* Android version/Browser: web
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
Attached is the initial document to use, here you can fine all the levels and options. I would have to talk to @GabrielePoggensee  to know what was decided

[Prop_typeofplace_sormas.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5381445/Prop_typeofplace_sormas.xlsx)

**Comment by MateStrysewske** [comment]
Will be done in #3617
