### ISSUE TITLE
Introduce a SORMAS eXtra-Layer instance for analyzing anonymized data from other SORMAS Instances

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3191]
### Situation & Feature Description
In some countries we have the situation that the SORMAS Instances are separated from a SORMAS central instance. That's why we introduced the SORMAS 2 SORMAS Interface.

With the SORMAS 2 SORMAS Interface we want wo send data time controlled to another central SORMAS Instance, that will be called SORMAS eXtral Layer

SORMAS eXtra-layer should be created in a showcase environment on xl.sormas-oegd.de
- Data (cases & contacts) from **ga1** & **ga2** should be send to **xl** automatically ( 8am & 18am )
- This data must be pseudonymized data (only year of birth, only the first 3 digits from the city code)
- SORMAS eXtra-layer will **delete all data** automatically ( 7.55 am & 17.55 am )
- By clicking on a case or contact in the transmission chain visualization the district of the case or contact has to be shown

### Possible Alternatives
Phase 2: - During the transport the UUIDs must be 100% anonymized => meaning that there must not be any chance to re-identify the sent contacts & cases // The relation which is needed for the transmission chain must be persisted
- birth year => every one between 40 and 50 will be 45

**Comment by bernardsilenou** [comment]
@markusmann-vg should we not add events also? The updated transmission chain has events included


![image](https://user-images.githubusercontent.com/12996724/96180352-95be7300-0f32-11eb-81b9-7da8344f5d0c.png)

**Comment by MartinWahnschaffe** [comment]
Closing this issue. SORMAS XL is a dedicated project, thus should not be an issue in this repository.
