### ISSUE TITLE
Automatic user creation from environment variables

### ISSUE THREAD

**Issue by weber-software** [hzi-braunschweig/SORMAS-Project#3194]
### Situation Description
For sormas-sb deployments there is a special user required that is used to access sormas from the sb.
This user needs to be created manually right now which makes fully automatic sormas-sb deployments impossible.

### Feature Description
It would be great to have the option to specify this user and password using environment variables and get them created by sormas on startup.

### Possible Alternatives
An alternative would be to have a command inside the sormas docker image that could be executed to create that user.
But the proposed solution is definitely preferred.

### Additional Information

@vidi42 told me to mention @markusmann-vg

**Comment by vidi42** [comment]
Implemented by #3355
