### ISSUE TITLE
 Adjust the print style sheet

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3197]
@ftavin @bernardsilenou @olivierleuci

### Problem Description
By using the internet browser to print event information, some information is not reproduced on the printed document. This is particularly the case for variables which, after selection, appear on a blue background. The blue background is not reflected in the printed document.
It would seem that the problem comes from the fact that by default the option "print the page backgrounds" is not checked.

### Proposed Change
Develop SORMAS to avoid the user having to activate this option in his browser and have the default printing of the page backgrounds.

### Additional Information
![image](https://user-images.githubusercontent.com/65449450/96103521-18feab00-0ed8-11eb-8dd4-0dad8af66448.png)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT
