### ISSUE TITLE
Dashboard | Epidemiological Curve panel, on the Chart Context menu selecting the "View Data Table" option values get displayed outside the panel

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3200]
### Steps to Reproduce
1. Open test.sormas.netzlink.com environment and go to the Dashboard
2. On the Epidemiological Curve panel click on the Context menu button(the 3 stripes)
3. Select the View Data Table
4. Check what gets displayed under this panel

### Expected Behavior
Values should be displayed in a user friendly way
### Actual Behavior
The values are overlapping with the Panel and are also displayed underneath it
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/96135822-4eb98900-0f04-11eb-838c-54248c74fcf3.png)

### System Details
* Device:
* SORMAS version: SORMAS Version: 1.51.0-SNAPSHOT
* Android version/Browser: Chrome/Mozilla
* Server URL: https://test.sormas.netzlink.com
* User Role: any

**Comment by DavidBaldsiefen** [comment]
The relevant button (View Data Table) seems to have been removed in the meantime (1.62.0)
