### ISSUE TITLE
In the "actions" view (EVENT), change the title "event directory" to "action directory"

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3206]
### Feature Description
To date, the title of the event directory is the same whether you are browsing the events view or the actions view. However, 
it is not the same informatione: in the events directory, the user has a view by event while in the action view, information is presented at the level of each action.
Having the same title in both views is a risk of misinterpretation and leads to confusion.

### Proposed Change
It is proposed to change the title of the actions view: replace "event directory" by "action directory"

### Additional Information

@ftavin @bernardsilenou @olivierleuci

**Comment by bernardsilenou** [comment]
![image](https://user-images.githubusercontent.com/12996724/96303161-40e62f80-0ffa-11eb-90b7-eaa9e5204f70.png)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT
Using the test.sormas.netzlink.com environment.
