### ISSUE TITLE
Case | Epidemiological Data | Adding a new entry for "attended a gathering" will disable the yes/no/unknown buttons

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3209]
### Steps to Reproduce
1. Open a Case and go to Epidemiological Data
2. Click on Yes under Attended a Gathering
3. Select the date and click on Done
4. Check the Yes/No/Unknown buttons

### Expected Behavior
The user should be able to change its selection 
### Actual behavior
The user is unable to change the selection once the entry has been added

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/96264936-7c1e3980-0fcd-11eb-87a9-83f10847a5b2.png)

### System Details
* Device:
* SORMAS version:SORMAS Version: 1.51.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com
* User Role:

### Additional Information
The same behavior can be seen under: Traveled outside of district with a new Entry, the buttons become disabled.

**Comment by MateStrysewske** [comment]
This is expected behaviour to prevent users from deleting all data in these lists by accidentally clicking on "No" and saving.
