### ISSUE TITLE
Allow turning off email/SMS notification per server [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3211]
### Feature Description
When email notification is activated in the system, users are notified for every change in the system. Such changes are: task assignment, case classification, new sample test result, and so on
### Problem Description
- This is overwhelming for user to get enormous emails
### Proposed Change
- Add server specific changes for task assignment. Add parameters for
* Task assignment (it would be nice to trigger this email if date of task onset ==  current date OR current date -1 )
* Others changes, ie sample test result, case classification, (this is the current default setting)
### Possible Alternatives
- Al ideal solution would be to have parameters fro each possible change line case classification, test results. But this is not needed for now.

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg

**Comment by carolinverset** [comment]
@ftavin
