### ISSUE TITLE
[SORMAS2SORMAS] Sharing a case/contact together with the ownership with another SORMAS instance should also change the responsible region, district, ...

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3213]
### Feature Description
When a case/contact is send to another SORMAS Instance the responsibe region, district etc. should be taken over from the SORMAS Instance to which the case/contact was sent to.
Condition: Only when the ownership is also handed over
![Bildschirmfoto 2020-10-19 um 08 26 05](https://user-images.githubusercontent.com/62540178/96409216-33d96400-11e5-11eb-8cfa-4693318cf79f.png)

### Additional Information

Region and District should be aligned with all SORMAS X users and the IfSG-Applications (SurvNet)

**Comment by vidi42** [comment]
@markusmann-vg 

1. Is it correct that the responsible district is not necessarily is the same as the on of the Facility where the person is currently in?

2. When the ownership has been transferred to another system, how do we make sure that the correct region and district are assigned to the case? (is it done on the sender or on the receiver side?)

Proposal 1: 
When the person is sharing the a case, we can ask the person to choose the region and district they want to assign the case to on the receiver system, if they are different from the original ones.

Proposal 2:
Allow systems to define their default Region and District which overwrite the values for received cases.

**Comment by bernardsilenou** [comment]
@vidi42  @markusmann-vg has the final say on this but i would like to comment:
The  responsible district with read and write rights at any point in  should be one, and either that of the sender or that of the receiver.
- When the sender share the case, we should also force the sender to also share the ownership. So the sender jurisdiction looses edit write on the case
- "The responsible district is not necessarily  the same as the on of the Facility where the person is currently in". If you are talking about where the case person currently is, then the responsible district should be that of the facility of the case but not necessarily that of the address of the case person. It does not make sense to have one district taking care of a case and another being the responsible district of the same case. If this happens, then  the case if often transferred  and this is what we need to atain in this issue.

**Comment by markusmann-vg** [comment]
Prequisite: Decouple Place of stay from the responsible jurisdiction =>
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3254

**Comment by markusmann-vg** [comment]
Discarded because of #3254
