### ISSUE TITLE
Make the event title mandatory in place of event description

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3223]
### Feature Description
cf. #2904 
### Problem Description
When replacing the description column with title in the event directory, all previously entered events are no longer easily identified since the descriptions haven't been migrated to the titles. A user would have to open each event individually to see its context.
### Proposed Change
Migrate all previous description entries to the event titles. If the limited character count for titles is problematic for long descriptions, display (...) in the titles (and directory column) and show the rest in the description.

I also propose to make the title field compulsory rather than the description field.
### Possible Alternatives
Leave the description column in the event directory.
### Additional Information
Version: 1.50.0
Server: test1401.sormas-oegd.de

<img width="1067" alt="Screen Shot 2020-10-19 at 4 47 16 PM" src="https://user-images.githubusercontent.com/70317594/96467086-da942380-122a-11eb-8612-4e09e55b27e0.png">

**Comment by bernardsilenou** [comment]
@kwa20 I agree with you:
- make title compulsory and description not
- clone description and set is as title if the events that has no title. If there is a validation on character length for the tittle, clone the first n characters from the description as title
- set a max default column width for title (see figure)


![image](https://user-images.githubusercontent.com/12996724/96655518-02c07700-133e-11eb-81e5-18e1f4ccceec.png)

**Comment by markusmann-vg** [comment]
Can we do it with an SQL-Script:
Migrate (Copy) all old Event descriptions to the event Titles.
Best case: 
Copy the first 75 chars of the description and paste it to the title. If the description is longer than 75 char, we show the first 75 chars plus a "..." in the title. 
This way they can find the events again and see the detailed description, when clicked on.

**Comment by MateStrysewske** [comment]
* Only do this if there is no title yet
* Change date also has to be adjusted to the current date to make sure that the data is properly synchronized

**Comment by MateStrysewske** [comment]
This has been fixed directly in the database for the servers where this was a problem.

**Comment by kwa20** [comment]
@MateStrysewske Could we however still make the title field compulsory rather than the description? This might have gotten lost maybe.

**Comment by MateStrysewske** [comment]
@kwa20 Makes sense, I'll reopen and relabel the issue accordingly

**Comment by MateStrysewske** [comment]
- [ ] Make the event title mandatory
- [ ] Event description should not longer be mandatory

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
