### ISSUE TITLE
Deletion of campaigns no longer working

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3224]
### Bug Description
Admins currently can't delete existing campaigns.

### Steps to Reproduce
1. Login as admin
2. Open the edit view of a campaign
3. No delete button is shown

### Expected Behavior
- [x] Make sure admins can delete campaigns again

### Additional Information
Looks like the edit view for campaigns used the CampaingController.createOrEditCampaign method in the past, but is now no longer doing so.

- [ ] rename the method to make clear that it is only used when creating campaigns
- [ ] move the logic that was applied to edit forms to the CampaignView (or find another solution)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
