### ISSUE TITLE
Changing the area in a campaign data form needs to load the related regions

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3225]
### Bug Description
Currently it's possible the select an invalid combination of area and region in a campaign data form.

### Steps to Reproduce
1. Create a new campaign data form (ide
2. Select an area (e.g. Central)
3. Select a region of the area 
4. Change the area

### Expected Behavior
The region field value should be cleared and the list of available regions needs to be updated to those of the area.

### System Details
* Server URL: https://test-afghanistan.sormas.netzlink.com/

### Additional Information
During the APMS review we had a situation where regions where not ordered alphabetically, but I was not able to reproduce this. Please have a look at how the data that goes into the drop-down is order, too.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
