### ISSUE TITLE
Phone number should not be copied to the email field when converting contact to case

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3239]
### Bug Description
- When the email is missing, they  phone number is copied in the place holder for email
- This then leads to bug when email validation is called
### Steps to Reproduce
1. Create a contact with a phone number and no email
2. Convert the contact to case

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/96657316-2c7b9d00-1342-11eb-9fa9-3507752095f8.png)

### System Details
* Device:
* SORMAS version:  release candidate 1,50
* Android version/Browser: web
* Server URL:
* User Role: national user + admin

**Comment by kwa20** [comment]
This also happens, when creating cases for event participants.

**Comment by JonasCir** [comment]
Fixed by open PR https://github.com/hzi-braunschweig/SORMAS-Project/pull/3252

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
Both scenarios work as expected now ( Contact converted to case and Event Participant converted to Case )
