### ISSUE TITLE
Detailed case export does not work

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3244]
### Steps to Reproduce
1.
2.

### Screenshots

![image](https://user-images.githubusercontent.com/12996724/96714749-e73b8780-13a2-11eb-9616-79031069b08b.png)

### System Details
* Device: web
* SORMAS version: 1,50
* Android version/Browser:
* Server URL: test 1401
* User Role: admin + national user

**Comment by MateStrysewske** [comment]
Very likely caused by the database not being updated after 1.47.1.
