### ISSUE TITLE
APMS Global Menu Customization based on in-country request

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#3245]
### Feature Description
Re-ordered the global menus to customized to fit the Afghanistan MoH framework
### Problem Description
The Afghanistan MoH have raised complaint about the inability to understand how the SORMAS specific global menu applies to their framework. 
### Proposed Change
https://app.moqups.com/3NUENEwuOE/view/page/ac3242c2f
![D7727DD6-A29F-42EB-8678-3F3149501DB5](https://user-images.githubusercontent.com/19344651/96910195-19b1b700-146d-11eb-971f-7b46da155ff0.jpeg)
@MartinWahnschaffeSymeda 
### Possible Alternatives
![DDCBBA3C-7067-4332-ADD0-4F47F9D2E74A](https://user-images.githubusercontent.com/60390281/97436923-2153de80-18f9-11eb-8654-2998e11381a4.jpeg)

**Comment by MateStrysewske** [comment]
@hzi-old Please don't assign issues to us.

**Comment by MartinWahnschaffeSymeda** [comment]
@tomabadaniel Any reason you have moved this? See #3368

**Comment by MartinWahnschaffeSymeda** [comment]
As discussed today this is no longer needed due to #3368 and the addition of the pre & post-pilot dummy switch.
