### ISSUE TITLE
Correct GDPR text in English and adjust all translations

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3248]
### Bug Description
- The last few words has grammatical  errors: "or any other data that does not would not be related to the health survey."
- on test 1401, the Frence translation is not incorporated from crowdin even though it was translated before the release candidate was built. The German translations was pulled from crowdin.
### Steps to Reproduce
1.
2.

### Expected Behavior
Use this text:
In accordance with the principle of data minimization imposed by the GDPR, you must ensure that you enter here only objective data absolutely necessary for the processing of the file. In particular, you must not enter genetic or biometric, philosophical, political, religious data, union opinions, sexual life or orientation, ethnic origin, offenses, convictions, security measures, criminal record ... or any other data that is not related to public health surveillance.
- All translations should be pulled from crowdin
### System Details
* Device:
* SORMAS version: 1,50
* Android version/Browser: web
* Server URL: test 1401
* User Role: national user + admin

**Comment by bernardsilenou** [comment]
@MateStrysewske  Carolin told me that there are issues related to pulling the French translations from crowdin. I would correct the France translation now, please can you check  if there is ready an issue? The German translation seem fine

**Comment by MateStrysewske** [comment]
My suspicion is that the translation was not submitted via Crowdin, but was manually taken care of in the pull request - which absolutely makes sense. When the new translations from Crowdin were then pulled, the French translation was overwritten with the default. I don't know for sure if that's the case though. We'll have to observe the behaviour in this regard in the future, right now I can't really say for sure what caused the issue.

**Comment by MateStrysewske** [comment]
@xavier-calland @mouloud-mala The problem with the French translations is that Crowdin overrides the development branch with its own changes. When you develop something and manually add the French strings to the properties files, Crowdin also creates these properties and uses the default English string for it, and this English string then overrides the French string that you've added during development. There might be a way to change that, but in general I recommend that you add the French translations of the strings to Crowdin as well (or exclusively, i.e. don't add them to the properties files manually except when you need that for development).

**Comment by bernardsilenou** [comment]
Tested on test.sormas.netzlink. and translations were pulled on crowdin

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
