### ISSUE TITLE
Missing error message when creating contacts out of case contact tab

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3249]
### Bug Description
When compulsory entries are missing in the contact creation form out of the case contact tab, error message is missing or hidden behind the creation form and no interaction with the window is possible. Not being able to possibly close the error message as expected might prevent the interaction with the the creation mask. Reloading the page seems like the only option. 
### Steps to Reproduce
1. Open any case and go to the contact tab.
2. create a contact and purposefully leave a compulsory entry field empty. Save.

### Expected Behavior
When compulsory entries are missing, error message should be displayed. When closing the error message normal interaction with the creation window should be possible.
### Screenshots
<img width="947" alt="Screen Shot 2020-10-21 at 4 56 20 PM" src="https://user-images.githubusercontent.com/70317594/96740121-d0a42900-13c0-11eb-8e67-2843fb903bee.png">

### System Details
* Device:
* SORMAS version: 1.50
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
@kwa20 I tested and it works fine for me. The cause of this may be because your device do not have a full dh. Can you test with another monitor and confirm if this is the cause?

![image](https://user-images.githubusercontent.com/12996724/96747618-c554fb80-13c8-11eb-9b13-332246b66560.png)

**Comment by MateStrysewske** [comment]
I'd also like you to confirm this on at least another system; this bug seems really weird to me and didn't occur for anyone else that I know of so far.

**Comment by kwa20** [comment]
We have tested again on another computer. Everything worked fine this time.

- User role: admin + national user
- test1401.sormas-oegd.de (1.50)
- browser: chrome

A simple difference I can think of would be macOS Mojave (missing error) vs. Windows 10 (works fine).

**Comment by markusmann-vg** [comment]
@AndyBakcsy-she Please spend max. 2 hrs to reproduce it

**Comment by kwa20** [comment]
I tested again on the HZI computer (Windows 10, test1401, admin and national user, firefox, 1.50) and experienced the same issue as described above.

**Comment by AndyBakcsy-she** [comment]
I could not reproduce this issue on sormas version 1.51.0-Snapshoot, and SORMAS Version: 1.48.2

**Comment by StefanKock** [comment]
Confirmed on test-de with SurvSup in DE language

**Comment by raghupola-vg** [comment]
Tested on latest version and issue is not reproduced. (verified on Firefox browser)
