### ISSUE TITLE
Check for duplicate event participant when retrospectively linking a case to an even

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3250]
### Feature Description
System checks for duplicate event participant (ep) each time a new ep is created. System create an event participant when a case is linked to an event but do not check for duplicate ep.
### Problem Description
A person can exist and be linked in the db to ep and a case at the same time. When a user retrospectively link the case to the event, system creates a new ep using the same person.
### Proposed Change
- Check for duplicate person when linking a case to an event 
### Additional Information
See horse shoe in the immage

![image](https://user-images.githubusercontent.com/12996724/96793729-31515700-13fd-11eb-9236-7d9d2b0fedf7.png)

**Comment by kwa20** [comment]
I'm closing this issue as a duplicate since it has been solved in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3392
