### ISSUE TITLE
As a user of SORMAS I want to be able to send SMS in a single or bulk mode for cases [3]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3253]
### Feature Description
process flow:
Step_1. Initial situation: Several cases are mass-imported into SORMAS. The data set of an case SHALL usually contains the mobile phone number

Step_2. Request: The Contact Tracer informs cases to go into isolation. The message is transmitted as follows:

SMS: Length of the message is limited, not personalised and can be sent to case either individually or as a bulk operation.

Step_3. Further process: The Contact Tracer contacts the IP by telephone to perform the contact tracing.

Add a Button => Send SMS with default text with a button and confirmation 
Optional: Hide button as long as
- there is no phone number
- no positive test result (@Candice-Louw Are there other restrictions?)

When an SMS is sent, we show a label with "SMS sent at dd.mm.yyyy hh:mm"

- [x] Feature configuration 
- [x] Add the possibilty to add a freetext to the sms 
- [x] Add the right to a role to send sms

Flow:
Filter your cases list
click on bulk sms
get info of the cases that do not have a phone number 
1.) continue => Free text for sending sms
2.) go back => correct the cases 

### Additional Information

out of scope:
- [ ] Admin: Include in the DB-Export / out iNotificationLog (type of notification should be treated)

**Comment by markusmann-vg** [comment]
@Candice-Louw Bulk Actions are currently available for Admins / Who will be sending the SMS in the swiss context

**Comment by BarnaBartha** [comment]
- [ ] add information of last 5 SMS messages sent to the case data view ( containing who sent it and when)

- [ ] show the number of characters, when writing  the message (Example: 45 / 160 => 1 message)
If the text is longer than 160 we show (Example: 225 / 160 => 2 messages)

**Comment by MateStrysewske** [comment]
- [ ] There's a lot of margin in the "Send new SMS" popup, would be great to reduce that a bit
- [ ] Add spacing between the warning about cases not having a valid phone number and the rest of the layout; display an exclamation mark icon to the left of the message (like e.g. in the new epi data form)
- [ ] Move "number of messages" to a new line
- [ ] Add a blank space between the colons and the numbers
- [ ] Seems like "No. of messages sent" has two colons
- [ ] Remove the milliseconds from the overview of the sent SMS

**Comment by BarnaBartha** [comment]
- [ ] show only user name for the sent sms-es not both name and roles
