### ISSUE TITLE
Error when editing campaign dashboard grid

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#3259]
### Bug Description
Error when editing campaign dashboard grid on https://test-afghanistan.sormas.netzlink.com/
### Steps to Reproduce
1. Go to https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!campaign/data/UT5HKR-3GDBCA-MYIOXL-J35PSLR4
2. Edit the campaign dashboard grid

### Expected Behavior
Grid is editable.

### Screenshots
![image](https://user-images.githubusercontent.com/8166805/96875105-87ff7500-147f-11eb-96f2-8b93b80fde92.png)

### System Details
* Device: 
* SORMAS version: 1.51.1-SNAPSHOT
* Android version/Browser: Chrome on MacOS
* Server URL: https://test-afghanistan.sormas.netzlink.com
* User Role: National coordinator

### Logs
[sormas-21102020.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/5422955/sormas-21102020.log)

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha This is the log:

> [2020-10-29T18:24:56.117+0430] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=73 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1603979696117] [levelValue: 800] [[  E182456.010|     > Cannot provide an id for a null item. (de.symeda.sormas.ui.SormasErrorHandler.java:78)java.lang.NullPointerException: Cannot provide an id for a null item.at java.base/java.util.Objects.requireNonNull(Objects.java:246)at com.vaadin.data.provider.DataProvider.getId(DataProvider.java:132)at com.vaadin.server.KeyMapper.refresh(KeyMapper.java:192)at com.vaadin.data.provider.DataCommunicator$ActiveDataHandler.generateData(DataCommunicator.java:192)at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:481)at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:461)at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:383)at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:339)at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
> at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1606)at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448)at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)at jdk.internal.reflect.GeneratedMethodAccessor294.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4796)at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)at jdk.internal.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationI
> nterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)at jdk.internal.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4768)at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4756)at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)at com.sun.proxy.$Proxy657.doFilter(Unknown Source)at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:76)
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
> at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
> at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)at java.base/java.lang.Thread.run(Thread.java:834)]][2020-10-29T18:24:56.630+0430] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=74 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1603979696630] [levelValue: 800] [[  E182456.629|     > Cannot provide an id for a null item. (de.symeda.sormas.ui.SormasErrorHandler.java:78)java.lang.NullPointerException: Cannot provide an id for a null item.at java.base/java.util.Objects.requireNonNull(Objects.java:246)at com.vaadin.data.provider.DataProvider.getId(DataProvider.java:132)at com.vaadin.server.KeyMapper.refresh(KeyMapper.java:192)at com.vaadin.data.provider.DataCommunicator$ActiveDataHandler.generateData(DataCommunicator.java:192)at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:481)at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:461)at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:383)at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:339)at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
> at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1606)at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448)at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)at jdk.internal.reflect.GeneratedMethodAccessor294.invoke(Unknown Source)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4796)at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)at jdk.internal.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
> at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)at jdk.internal.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4768)at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4756)at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
> at com.sun.proxy.$Proxy657.doFilter(Unknown Source)at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:76)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
> at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
> at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)at java.base/java.lang.Thread.run(Thread.java:834)]]

From my understanding it's the same problem we already had, right?
I guess we have to introduce a mechnanism that makes sure that the loaded data is valid as-well and give a clear error message to the user
