### ISSUE TITLE
Roles and Processes for Ebola Outbreak (lessons learned from users in the field)

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#326]
@MartinWahnschaffeSymeda @MateStrysewskeSym @Krisistis 

**Contact tracing officer**
I want to be able to enter demographic data on contacts during my first visit (name, age, sex, occupation, home address, occupational address, marital status, primary phone number, alternate phone numbers, education status, kind of residence [compound (several households), flat, single rooms self-contained, single rooms not self-contained, sharing toilets with other households)], nationality. 
I want to be able to enter symptoms and temperature on a daily basis and I want the system to inform the contact tracing supervisor when there are symptoms or temperature => 38.0 C. 
 I want the system to provide me daily with a list of contacts I need to visit.
I want the system to record GPS  coordinates of the contacts daily. 
I need to have information about the case (name and outcome, relationship of the contact to the case) for all the contacts I have to visit. 
I want to be able to inform the system during the first visit about the type of contacts the contact had. I want to have a list of type of contacts to enter the information (e.g., slept in the same room, etc). 
I want to have the temperature pattern of the contact in a graph daily. 
I want the system to alert me when I enter a temperature  38.0 C or higher (mistakenly entered temperature) and ask me to reconfirm.
I want to able to enter the information on reasons for loss to follow up (e.g. contact is travelling (time, destination), contact went underground (no information on his/her whereabouts)) to make the contact tracing supervisor aware about this fact for necessary action.
I want the system to inform the contact tracing supervisor and the responsible contact tracing officer about the new location of a contact. 
I want to be informed about contacts I need to follow up from other places now residing in my LGA.
I want the system to inform me about the number of days the contact has been already followed up. 
I want to be able to enter the information, that the contact was not seen, and the system to inform the contract tracing supervisor to initiate appropriate action.

I want to be able to enter the information that symptoms and temperature were collected by phone. 
I want to be able to inform the system that a contact is not cooperative and I want the system to inform the contact tracing supervisor to take appropriate action (e.g., inform community leader, inform strike force, evacuation in the quarantine center). 
I want the system to inform contact tracing supervisors to initiate discharge proceeding protocol one week ahead of the discharge (21 days) (e.g, letter of discharge). 
I want the system to notify the contact tracing supervisor of the psycho-social need of the contact prior to discharge.
I want to be able to enter information on sign of depression of a contact and I want the system to inform the contact tracing supervisor to initiate appropriate action (information to the case management supervisor). 
I want to be able to enter a new contact I have identified.
I want to be able to have a checklist of topics which need to be covered with new contacts (e.g., basic hygiene) (GaPo: input needed from Nigeria).

 
**Contact tracing supervisor**
I want to be able to inform the case management supervisor about a suspected case to take appropriate measures (picking and decontamination of premises)
I want the system to flag contact tracers who have collected information only by phone for more than 2 days. 
I want the system to give a meeting prompt to the contact tracing team daily.
I want to be able to enter the names of contact tracers present at the meeting.
I want to be able to enter reasons for not attending the daily meeting. 
I want to know daily how many contacts are supposed to be seen that day and how many contacts were seen.
I want to have a daily report on: number of contact supposed to be seen, how many seen (%), number of symptomatic contacts, new contacts registered, number of symptomatic contacts that were picked, number of symptomatic contacts that were negative and discharged from isolation, number of contacts that completed follow up, projection of contacts to be followed up for the next 7 days, ratio of contact tracers to contacts. 
I want to know how many contact tracers are available.
I want to be able to enter contact tracers into a staff list (name, address, phone number).
I want to be able to enter the information on the start and end date when a contact tracer joined the team. 
I want to be informed immediately about a new laboratory confirmed case. 
I want to be informed immediately about any death of a health care worker. 
I want to have a daily list of contacts to be followed up and to be able to assign contact tracers to contacts. 
I want to have a report on contacts lost to follow-up (not seen for 48 hours). 
I want to have a daily report on difficult contact (contact refusing to be seen, to give information on their temperature and symptoms).
I want to be informed immediately when a suspected case tested negative to stop contact tracing (second result after 48 to 72 hours of first testing).
I want the system to provide an epicurve daily on newly identified confirmed cases,  suspect cases etc. 
I want the system to provide the daily follow-up rate. 
I want to be able to inform other states about contactsthey need to follow up (e.g, prepared email). 
I want to be able to inform case management about suspected cases to be picked up. 
I want to have a map with the location of contacts including the cases. 
I want to have a summary of contacts generated by each case.
I want to have a graphical presentation of the transmission chain.
I want to have a daily summary of contacts needing psycho-social support. 
I want to be able to inform the case management supervisor about contacts needing psycho-social support.  
I want the system to take the coordinates of the contacts location daily to be sure that he was visited. 
I want to know whether one caller has called repeatedly.

**Epi/rumour manager supervisor**
I want to be able to log in rumours (call, mail, person) (time, place, name, reason, type of rumour, source (health care worker, public, port health) which are to be investigated (artifact: alert investigation form). 
I want the system to provide me a daily list of all rumours. 
I want to be able to fill in the check list for each call or mail (GaPo: I am looking for this checklist).
I want to enter the information on the outcome of every rumour. 
I want to have a report of the number of rumours investigated (%). 
I want to have the summary of the outcome of the rumour investigation (number of suspected cases identified).
I want to get information whether recommended actions have been carried out (e.g. picking of suspected case). 
I want to have a summary of rumours discarded. 
I want to be able to initiate an investigation of a rumour. 
I want to be able to inform case management and the contact tracing supervisor about a suspected case. 
I want to have a daily, weekly, monthly graph on the location from where rumours were reported. 
Rumour officer
I want to be able to enter the name, address, age, sex etc of the suspected case. 
I want to be able to enter any history of contact with a suspected case, history of travel to infected zone, history hospital attendance, occupation (health care worker, others), relation of health care worker), symptoms, temperature
I want to be able to inform the Epi/rumour supervisor about the outcome of the investigation (rumour dropped, further investigation needed, or person should be picked).

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
Please move this to the wiki

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please go through this and identify potential features/adjustments
