### ISSUE TITLE
Developer mode case generation should respect disease and country annotations

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3260]
### Bug Description
"Dead animal Exposure" field gets created although it is not displayed
### Steps to Reproduce
1. On the local environment log in with admin and go to Configuration
2. Use the Developer page to auto-generate Contacts and Cases
3. Open one of the Cases and try to edit and Save some Epidemiological data

### Expected Behavior
The user should be able to change and Save epi data
### Actual Behavior
Dead animal exposure date cannot be in the future is the displayed error message
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/96879738-11fe0c80-1485-11eb-9f98-7aa92fd5651a.png)

### System Details
* Device:
* SORMAS version: SORMAS Version: 1.51.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: localhost
* User Role:

### Additional Information
this issue might be fixed together and linked to #3247

**Comment by MateStrysewske** [comment]
This is a general problem not only tied to this one specific field; what we need to do is make sure that fields that aren't relevant for the disease in question and for the country the server is running in are not automatically filled in during case generation.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.51.0-SNAPSHOT
