### ISSUE TITLE
Case | Symptoms |Epi Data | Yes/No/Unknown selection implementation seems different

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3261]
### Bug Description
The way the user needs to click on the yes/no/unknown values on the Symptoms page is different than on the Epi Data or other pages where this option is available
### Steps to Reproduce
1. Open/Create a Case
2. Go to Symptoms and start selecting some Clinical Signs (The user must click twice in order for the selection to be visible 
3. Go to Epi Data page and do the same.
4. Observe the difference, the user only needs to click once on the desired selection in order for this to be highlighted.

### Expected Behavior
On the Symptoms page the user should only click once to be able to change the existing value.

### Actual Behavior
The values get changed only when there is a double click
This can bring errors while users edit or create clinical signs
### System Details
* Device:
* SORMAS version: SORMAS Version: 1.51.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: localhost/test.sormas.netzlink.com
* User Role: any role

### Additional Information
This issue is linked to issue #2963

**Comment by DavidBaldsiefen** [comment]
@AndyBakcsy-she Can you confirm if this is still happening? I couldn't reproduce this on 1.59.0-SNAPSHOT
