### ISSUE TITLE
Setup Jenkins for execution of Sormas UI automation tests.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3262]
### Situation Description
The test scripts are ready and needs to be integrated as part of CI/CD pipeline

### Feature Description
Install the necessary Katalon plugin on Jenkins and create a project to execute the automation tests before every release.

Required plugin on Jenkins: Katalon Testops plugin
 
### Additional Information
[Jenkins Automation Project Setup.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/5437982/Jenkins.Automation.Project.Setup.pdf)

**Comment by JonasCir** [comment]
Hi @raghupola-vg just for my understanding: Will these UI automation tests (partially) replace the manual testing which is done before each release?

**Comment by raghupola-vg** [comment]
@JonasCir  Partially yes, but this would only cover parts of the UI bugs that would be fixed by the devs. The manual testing which is done before each release focuses mainly on the features and other functional aspects.

**Comment by raghupola-vg** [comment]
@StefanKock Attached the required details for the project setup as a PDF to the ticket.

**Comment by StefanKock** [comment]
@raghupola-vg Against which instance(s) of SORMAS-Project are these tests suppose to run?

**Comment by raghupola-vg** [comment]
@StefanKock 
1. The tests are executed on test.sormas.netzlink.com instance but this is defined inside the Katalon global test configs.
2. It is not updated, and the xvfb is not a necessary field. The rest of the doc is the same except the Katalon version which should be 6.3.3 and the command arguments must be changed as per the document attached in the ticket above.  I will update the git hub read me too after initial execution

**Comment by StefanKock** [comment]
I will clarify the installation on the Jenkins host on friday

**Comment by raghupola-vg** [comment]
Jenkins jobs are scheduled and works fine with Chrome browser.
Separate ticket will be created for Firefox browser
