### ISSUE TITLE
[CLIMEDO Integration] Add the CLIMEDO Functionality to cases 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3265]
### Situation Description
Currently the symptom diary can only be used for contacts. With this story we extend the functionality to cases

### Feature Description
Add the functionality of creating users, sync personal data and endfollowupdate, and receive data from Symptom Journal for cases and the follow-up for cases

**Comment by FredrikSchaeferVitagroup** [comment]
So we add a followUpUntil to cases?

Also we should probably do something similar to #3294 for cases.

**Comment by vlad-ciucescu** [comment]
It is true that without a follow-up date for cases this makes little sense. We should refine this a bit and see how we can proceed.

**Comment by FredrikSchaeferVitagroup** [comment]
Currently, the follow up for a contact automatically gets cancelled when a the contact is converted to a case. This may be relevant here.

**Comment by FredrikSchaeferVitagroup** [comment]
There is follow up for cases already. It's just disabled by default. You can enable it in the featureconfiguration table of the database.

**Comment by FredrikSchaeferVitagroup** [comment]
I have made some changes that will probably influence this issue. They can be found [here](https://github.com/hzi-braunschweig/SORMAS-Project/commit/13f21a2491410571cfa102ade9fd756d8fbd1c18).

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS
Version: 1.55.0-SNAPSHOT
