### ISSUE TITLE
Validate Phone number and Email-Address in SORMAS before the handover to PIA [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3266]
### Feature Description
Validate the Phone-Nr and Email Address directly when entering or at least when you click on save.

### Problem Description
Current situation:
When the Email-Address or Phone number is not valid (for example the Country code is missing) it is possible to save the contact in SORMAS. However, when you click on the CLIMEDO Button, an error message appears, that the phone number or mail is not valid.  

### Proposed Change
see feature description

**Comment by markusmann-vg** [comment]
- [ ] do the validation when clicking on the PIA / Climedo button (already done for Climedo) and show the error message when the email and phone is not valid

- [ ] Check wether the validation is ok for PIA as well

**Comment by markusmann-vg** [comment]
Prerequisite for this issue:
- Having a proper and working test-environment

**Comment by soja-hzi** [comment]
Can this issue not be closed? We discussed it within the PIA team and cam to the conclusion that it is not relevant anymore.

**Comment by Candice-Louw** [comment]
Issue closed as it is not relevant anymore - see https://github.com/hzi-braunschweig/SORMAS-Project/issues/3266#issuecomment-815691528
