### ISSUE TITLE
Allow laboratory level users to see personal data of cases/contacts/event participants

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3267]
### Situation Description
The Nigerian lab users need access to the personal and sensitive details of a case. Right now, SORMAS prevents this under all circumstances because in general, lab users should not need access to this data. Because of that, we shouldn't generally change this behaviour, but rather think about a way to allow or prevent this access on a server-by-server basis. Possible options would be to add a new user right or a server property.

**Comment by bernardsilenou** [comment]
@MateStrysewske I suggest we go with severer property and when this property == T, then lab users have full access to all entities whose sample is assign to the same lab as the lab user account

**Comment by bernardsilenou** [comment]
@MateStrysewske @MartinWahnschaffeSymeda  Please can we move this to 1.51, even if it requires dropping another issue initially planned.
Identification of entities in  Nigeria mainly by name and the lab users have been blocked now for more than a week

**Comment by MateStrysewske** [comment]
@bernardsilenou We'll take care of it!

**Comment by MateStrysewske** [comment]
@bernardsilenou Which data exactly should the users be able to see? All data of cases with samples assigned to their laboratory irrespective of the jurisdiction? Only data of cases in the region of their laboratory? Or only datda of cases in the district of their laboratory?

**Comment by bernardsilenou** [comment]
@MateStrysewske As we already discussed:
All data of cases with samples assigned to their laboratory irrespective of the jurisdiction
Most countries have a reference labs that get samples all over the country

**Comment by MateStrysewske** [comment]
@bernardsilenou @Iheanacho2027 You can manually change this behaviour on the Nigerian server by editing the user rights of the lab officer in the database. You need to add the SEE_SENSITIVE_DATA_OUTSIDE_JURISDICTION and SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION user rights for this user role - that will allow them to view the personal and sensitive details of the cases they are allowed to see.

**Comment by bernardsilenou** [comment]
@Chinedar

**Comment by Chinedar** [comment]
@MateStrysewske @bernardsilenou Thanks! will implement and see.
