### ISSUE TITLE
Campaign Data Form dropdown issue

### ISSUE THREAD

**Issue by danRosca** [hzi-braunschweig/SORMAS-Project#3268]
### Bug Description
Campaign Data Form dropdown does not work
### Steps to Reproduce
1. Go to Campaign Data view
2. Select a campaign from the campaign dropdown
3. Select a form from the form dropdown
### Expected Behavior
Error pop-up will show up
(NullPointerException in CampaignDataGrid.java line 94)
### System Details
* Device:
* SORMAS version:
* Android version/Browser:Chrome
* Server URL:
* User Role:

**Comment by DavidBaldsiefen** [comment]
@danRosca is this still happening?
