### ISSUE TITLE
Add a "cluster criticality level" variable when cluster is selected

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3271]
### Situation Description

Since version 1.46, SORMAS offers to distinguish signals, events, clusters and screening. The users regret not being able to further qualify the clusters and propose to complete the event part with an additional variable which would specify the level of criticality of the cluster.

### Feature Description

In the "EVENT" part, when the user selects "cluster" in the status of the event, it is proposed to make visible an additional variable "criticality level" (like the nosocomial risk which also appears when theuser select “cluster”). The modalities of this variable would be as follows: limited risk, moderate risk and high risk.

### Additional Information
@ftavin @bernardsilenou @olivierleuci

**Comment by bernardsilenou** [comment]
@carolinverset  Thanks for introducing this new variable. This is similar to the contact category variables that qualify the risk of infections.
- Can we use Risk level to replace criticality level? since most of the categories are about risk
- It would be good to add unknown also: limited risk, moderate risk,  high risk, unknown. Default value == NA
- An optional point is if we can add a definition of what it means by risk categories, eg  what does high risk mean? many contacts in the event? many cases in the cluster?, or just if the user think there is a high chance that infections will spread to health participants

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @OlivierLeuci
No problem to rename the new variable to "risk lever". I also think that the "unknown" modality is relevant. It would also be interesting for this "unknown" modality to be the default modality.

I approach the teams in France to obtain the definitions and complete the ticket during the day.

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin @olivierleuci

Here are the definitions used by the French authorities to define the level of criticality of a cluster. These definitions therefore apply to all regions of France.

- low risk: people exposed to transmission have not moved away from the place of exposure;

- moderate risk: at least one person exposed to transmission has moved remotely (outside the district);

- high risk:> 4 people exposed to transmission moved outside the district.

**Comment by bernardsilenou** [comment]
@carolinverset The default value for almost all variable in NA, This is set at the back-end. Unknown  is chosen when the user read the question but do not have the answer. But when they do not even click on the tab, then it is saved as NA

**Comment by carolinverset** [comment]
@bernardsilenou 
This seems good for me. ok, i've understand

**Comment by bernardsilenou** [comment]
> @carolinverset 
> Here are the definitions used by the French authorities to define the level of criticality of a cluster. These definitions therefore apply to all regions of France.
> 
These management rules can be implemented if needed. Maybe in another issue? :

> * low risk: people exposed to transmission have not moved away from the place of exposure;

eventStatus == cluster and jurisdiction of event == responsible jurisdiction of all event participants.

> * moderate risk: at least one person exposed to transmission has moved remotely (outside the district);

eventStatus == cluster and sum of ( event participant whose  responsible jurisdiction != jurisdiction of event) >= 1 and <=4 .

> * high risk:> 4 people exposed to transmission moved outside the district.

eventStatus == cluster and sum of ( event participant whose  responsible jurisdiction != jurisdiction of event) > 4 

Bonus validation:  eventStatus == cluster only if at least one resulting case exist

**Comment by bernardsilenou** [comment]
@BasilKaburi Please can you add this definitions to glossary?

**Comment by BasilKaburi** [comment]
Sure thing!

Thanks

Basil

________________________________

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT on local environment
