### ISSUE TITLE
Add the columns "dates of symptoms" and "date of sampling" in the detailed view of cases

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3272]
### Situation Description

In the context of monitoring clusters, French scientists agree that a cluster is under control when no new case is recorded within 14 days of the last positive case in the cluster. Version 1.50 will have the functionality to access, from the event, the case directory directly filtered only on cases related to the event. Adding the two columns "date of symptom onset" and "date of sample" in the detailed view will allow users to have this information.

### Feature Description
Complete the detailed view of the case directory with these two complementary variables to allow better monitoring and management of clusters.

Variables to display in column in the case directory :

- Symptom onset date = symptoms.onsetDate

- Collection date = Sample.sampleDateTime

### Additional Information

@ftavin @bernardsilenou @olivierleuci

**Comment by ftavin** [comment]
@carolinverset if the case has multiple samples, which one should be considered ? The first one ? The last one ?

**Comment by carolinverset** [comment]
@ftavin the last one. he most recent date. 

perhaps it would be good to indicate the number of samples for the same person

**Comment by ftavin** [comment]
in a new column or in the same as the date, using parentheses ?

exemple : **10/23/2020 (2)**

**Comment by carolinverset** [comment]
I really like the idea of ​​keeping the date and putting the number of samples in brackets

**Comment by AndyBakcsy-she** [comment]
Verified the issue on SORMAS Version: 1.53.0-SNAPSHOT
Found out that the displaying of multiple samples has been implemented differently 
When there are multiple samples for one day, they are all displayed instead of incrementing the number in the brackets [] as Carolin mentioned in the last comment. 
![image](https://user-images.githubusercontent.com/70562142/101791715-857adc80-3b0c-11eb-8939-ca5f03936029.png)

**Comment by StefanKock** [comment]
Check again count @MateStrysewske

**Comment by AndyBakcsy-she** [comment]
Revalidated the issue on SORMAS Version: 1.53.0-SNAPSHOT on local environment
