### ISSUE TITLE
Develop the mechanism that alerts the absence of an email in the task function

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3273]
### Situation Description
To date, if the sending email notification setting is activated in the properties file, the user designated to perform a task receives an email on the date and time specified in the task.
When, by mistake, the email address of this user is not entered, no error message specifies that the email does not exist. Therefore, user A who created the task thinks he has notified a task to person B but person B does not receive the notification by email. Therefore, there is a risk that the task will not be performed since the user has not been informed.

### Feature Description
It is proposed to develop a mechanism that alerts the person who creates a task on the absence of the email address of the user designated to perform a task. This message could take the following form: "Please note, the user designated to perform the task does not have an email address and, therefore, will not receive a notification."

### Additional Information
@ftavin @bernardsilenou @MateStrysewske @olivierleuci

**Comment by bernardsilenou** [comment]
If the user assigned to a task nas not email address in the system and email notification is activated in the sormas.properties file, then inform the user creating the task. 
Suggested text: "The user account that this task is assigned to has no email address. Please update the user count in order for the user to get notified about this task "

**Comment by AndyBakcsy-she** [comment]
Verified this issue by creating Tasks and assigning them to users that do not have emails set up.
Validated this on SORMAS Version: 1.52.0-SNAPSHOT
