### ISSUE TITLE
Develop the export function of the task directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3275]
### Situation Description

To date, the dashboard cannot be exported. An export of this data nevertheless represents an advantage in terms of reporting and management of actions linked to contact-tracing.

### Feature Description

It is proposed to develop the basic and detailed export functionality for tasks, like what SORMAS offers in the other parts (event / case / contact)

### Additional Information
@ftavin @bernardsilenou @olivierleuci

**Comment by bernardsilenou** [comment]
@carolinverset @Candice-Louw Please can you add the list of variables and their order to be exported?
- variables for basic export and 
- variables for detailed export

**Comment by carolinverset** [comment]
I suggest the following order for basic and detailed export

- associated link
- SORMAS ENTITY (new variable -> #3279)
- Task Typ
- ENTITY NAME (new variable -> #3279)
- Suggested Start
- Due Date
- GEOGRAPHIC LEVEL TO WHICH THE TASK REFERS (new variable -> #3279)
- Assigned to
- Comments on execution
- Created by
- Comments on task
- Task Status

What to you think about ?

**Comment by bernardsilenou** [comment]
@Candice-Louw Please can you add more variables in case this list is not complete?

**Comment by carolinverset** [comment]
> @carolinverset @Candice-Louw Please can you add the list of variables and their order to be exported?
> 
> * variables for basic export and
> * variables for detailed export

@bernardsilenou @ftavin @olivierleuci
after reflection, the French teams propose to keep only the detailed export. We think that the number of variables is too low to justify two types of export?

**Comment by ftavin** [comment]
@carolinverset : if there is only one export with the columns of the board I think this is the "basic export". A detailed one would add variables that are not on the board

in your listing the "Priority" column is missing, is this normal ?

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @olivierleuci
indeed, luckily you are here to correct my mistakes.
So, yes this is the basic export and yes to add the priority level in the export. Sorry!

**Comment by Candice-Louw** [comment]
@bernardsilenou @carolinverset - Great suggestions, thank you! Nothing to add. 👍

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske  French dev team work on this for 1,52

**Comment by alexandre-gille** [comment]
Hi,

Could you give us the list of user roles allowed to perform tasks' exports, if you don't mind ?

For the time being, I put the same roles as the task view right without the xxxx_OBSERVER ones, but that's probably not exactly what you want.

**Comment by AndyBakcsy-she** [comment]
Verified the Basic Export of the Tasks on  SORMAS Version: 1.52.0-SNAPSHOOT
