### ISSUE TITLE
Develop additional filters in the TASKS Management

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3278]
### Situation Description

The task directory has very few filters and columns. Its use is currently limited: it’s for example not possible to filter the tasks over a given period, neither on a given region, nor on the SORMAS environment concerned by the task (case / contact / event).
It is proposed to complete the existing filters on the task directory in order to facilitate navigation and the identification of tasks relating to a person, to an event, to a given spatio-temporal area.

### Feature Description

The additional filters are:
-	Dates or period of the task 
-	Region / department of the case / contact / event concerned by the task
-	SORMAS environment concerned by the task: case/contact/event/general
-	Case or contact ID search / Event title
-  "Assigned to" and "Created by" 

### Possible Alternatives
A free-text filter that allows searching for keywords in/across all fields. 

### Additional Information

@ftavin @olivierleuci @bernardsilenou

**Comment by kwa20** [comment]
@carolinverset @bernardsilenou @Candice-Louw If we want to filter by assignee and creator it might also be useful to be able to filter by userrole too since people might generally assign entity related tasks to specific roles.

In addition to that, the option to bulk re-assign tasks could save a lot of time when changes would have to be made. If you agree, I could create a separate issue for this as a second step to this one.

**Comment by bernardsilenou** [comment]
@kwa20 The dev team started working on this last week. We hope they can include this, If not, then we may need to treat it in another ticket.

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou for the "Dates or period of the task" filter, should we filter on the "suggested start date", the "due date", both (two filters) or both (with the same filter) ?

**Comment by carolinverset** [comment]
@ftavin 
From a functional point of view, I think having both filters is interesting because they will allow supervisors:
- filter the tasks to be carried out from a date and thus have visibility in terms of workload
- filter on tasks that are due and therefore ensure that they have all been completed
@bernardsilenou  what do you think? do you agree with this analysis?

**Comment by ftavin** [comment]
ok, so you would prefer the "two filters" version, is that correct ?

@bernardsilenou can you give some feedback on that point ? @alexandre-gille needs this last info to finish the dev

**Comment by bernardsilenou** [comment]
I also think 2 different input option is better

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou ok, we'll do the same mecanism as for contacts dates :
![Capture](https://user-images.githubusercontent.com/15834125/99516020-002d5d80-298e-11eb-98ca-b663212c3fe5.PNG)

(for tasks the listbox will allow to chose between "suggested start date" et "due date")

**Comment by carolinverset** [comment]
@ftavin 
perfect !!

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT
