### ISSUE TITLE
Add additional variables and filters to task directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3279]
### Situation Description

To date, the number of columns available in the task dashboard is quite limited and does not offer reading of information by geographic level for example

### Feature Description

For a better use of the task dashboard, additional columns are needed, namely: 
- The geographical level to which the task refers (region, district) 
- The SORMAS  entity  associated to the task, ie "task context" (case / contact / event / general) 
- The title of the event concerned by the task (empty for others)

### Additional Information
@ftavin @bernardsilenou @olivierleuci

**Comment by bernardsilenou** [comment]
@Candice-Louw Please can you add more variables that are needed for other users?
@carolinverset I think adding a column just for the title of the event will lead to many blank cells. A more generic variable that applies to both case, contacts and events would be better:
For example "entity name" = name of person (for case and contact) or title of event (for event)

**Comment by carolinverset** [comment]
Thank you @bernardsilenou for your proposal which I fully approve. It is very interesting to have an "entity name" variable which would be more generic. OK for France

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin @olivierleuci
To obtain the same visual as in the other parts of SORMAS, we propose to create two columns (region and district) instead of creating one which concatenates the two pieces of information.
Ok for everyone?

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske French dev team work on this for 1,52

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset 

informations corresponding to the column "entity name" (cf. Bernard's comment) already exists in the "associated link" column (except for event title which was developped recently)

![image](https://user-images.githubusercontent.com/15834125/99057545-3b015100-259c-11eb-934d-15b661112148.png)

should we :
- add an entity name column, as you propose (effect : information will be duplicated)
- just change the associated link column to have the event title for events (no duplication of information)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 
In my opinion, the entity concerned by the task must appear in an independent column. To date, unless I am mistaken, this information appears inside the associated link variable. It is not possible to sort the tasks on the task entity. I agree with François's proposal (screenshot above)

**Comment by ftavin** [comment]
@carolinverset ok, we'll make a new separated column !

(my screenshot is not a mockup, it's what we currently have after adding one of the new columns (task context))

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou

The sort capacity on the new column "entity name" is not trivial because this field is linked to multiple entity types (case, contact or event).

The version proposed by @alexandre-gille in this pull request does not permit to sort on this column.

He tried to implements the sort function but the result is not perfect : data is sorted separately for contacts, cases and events so it only make sense if the user already filtered the board on the task context

Is it ok for you if we stick to this version (no sorting on entity name) for 1.52 ? That would allow us to discuss on the implementation of this sort function in a future issue. Or do you prefer to have the imperfect sort meanwhile ?

**Comment by bernardsilenou** [comment]
@faatihi To me if we have a filter for the entity name, then that is fine for now.  Its Carolin to decide for now

**Comment by ftavin** [comment]
@MateStrysewske 

discussed with @carolinverset and @bernardsilenou on today's meeting :
concerning the problem of redundant information, the column "entity name" is created for 1.52 and a new issue will be created for a future version in order to reduce the complexity of the "associated link" column and remove redundancy

**Comment by bernardsilenou** [comment]
@ftavin @carolinverset  I had a call with @MateStrysewske and he is very occupied to be able to work on this today and also the proposed solution of adding and removing some variables latter was not encouraged.
In order not to waist time, I will suggest that we do not add the column "entity name" in 1.52  as earlier discussed but refine it in another issue. I just realized that general tasks are not linked to an entity, thus the "entity name" is missing. Hope this is fine by you for now?

**Comment by ftavin** [comment]
@bernardsilenou @MateStrysewske @carolinverset 

ok, so can we at least add the event title in the "associated link" column ? (only for tasks linked to an event of course)

Right now for event the column is : UUID (desease - status - date)

If we combine event title + desease + status + date it will be too long and confuse so I would suggest :
- when event has a title : UUID (event title)
- when event has no title : UUID (desease - status - date)

**Comment by AndyBakcsy-she** [comment]
Validated this issue on : SORMAS Version: 1.52.0-SNAPSHOOT
