### ISSUE TITLE
Campaign management configuration feature does not allow adding of new form ids within new form definitions

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#3290]
### Bug Description
After each new campaign is created, the user has to configure all charts and forms. The feature does not allow new campaign data charts and even when changed from the database, the whole dashboard view buttons dissapear leaving only one category.
### Steps to Reproduce
1. The system should be able to duplicate an existing campaign configuration for future campaigns
2. The feature should allow new data charts and forms to be added to the system.

### Screenshots
![73543BFE-70EB-4C60-B106-740ABE15F250](https://user-images.githubusercontent.com/19344651/97207131-074abc80-1790-11eb-9a02-8cf0c72009e8.jpeg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!campaign/data/UT5HKR-3GDBCA-MYIOXL-J35PSLR4
* User Role:

**Comment by MateStrysewske** [comment]
@hzi-old Again, please don't assign developers to issues. We decide internally who takes care of what and will then choose the assignee once they take over the issue.

Also, the first point is out of scope for a bug issue. What will be done here is the fix for the second point.

**Comment by tomabadaniel** [comment]
![C690F87F-ED1A-4148-9298-CC87F410F343](https://user-images.githubusercontent.com/60390281/97326633-94eae280-184a-11eb-8b52-732b5c55a166.jpeg)

**Comment by tomabadaniel** [comment]
@BarnaBartha This is also a problem

**Comment by MateStrysewske** [comment]
@tomabadaniel Please give us more details about what you did to make this happen so we can try to reproduce it.

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha  This needs to be reworked. The logic now takes all diagrams that have been used in any campaign.
What it should do instead is to take all diagrams that have been defined in the database (campaigndiagramdefinition).

**Comment by BarnaBartha** [comment]
- [ ] extend validation to show specific message of what is null
- [ ] validate diagramId exists in the definitions
- [ ] do validation only on save of campaign (not load also)
- [ ] do validation on campaign dashboard as well (do not try showing diagram if not valid)
