### ISSUE TITLE
Cases and Contacts > Include email address in detailed and custom export [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3291]
### Situation Description
As a contact tracer, I would like to see each Person's email address in exported lists in order to be able to follow-up with them/communicate important isolation/quarantine information.

Currently, this information is not included in any export which requires contact tracers to copy-paste email addresses from external systems and match them with SORMAS exports.

### Feature Description
Inlude the following details in any **Detailed Export** and **Custom Export**:
Email address

### Additional Information
In this context, a 'Person' would include a Case, a Contact and an Event Participant (as well as all the associated exports [detailed, custom, DB] possible for each).

**Comment by bernardsilenou** [comment]
* Consider pseudonymization in exportation

**Comment by AndyBakcsy-she** [comment]
Verified issue on https://ga1.sormas-oegd.de/sormas-ui/ on SORMAS Version: 1.52.0-SNAPSHOT
