### ISSUE TITLE
Show areas in campaign diagrams by default for national users

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#3292]
### Bug Description
On the default dashboard page, the default admin unit is the provinces camoflaged as "regions" This should not be the case. The default view when no region is selected should be regions (Area) when a specific region is selected then the provinces can show
### Steps to Reproduce
1. Set default admin unit as regions (Central, Eastern, Western etc)
2. When a region is selected, then and only then should a province for that region show

### Expected Behavior
@MartinWahnschaffeSymeda @MateStrysewske 
### Screenshots
![572F3B2D-82FB-4785-BB59-9C80D8D86B54](https://user-images.githubusercontent.com/19344651/97221028-c3ad7e00-17a2-11eb-943e-120e0fb194a5.jpeg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
@hzi-old I have a comment about this bar chart:
- There are many categories on one bar and the colours similar
- What about using multiple graphs and for each, we use one variable for colouring?
- Should we have a call to discuss it?

**Comment by ChristopherRiedel** [comment]
@hzi-old Something must be wrong with your explanations, you are mixing up areas and regions.

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba I also don't get it. The "region" field in your screenshots is the SORMAS area field, exactly as you are requesting

![grafik](https://user-images.githubusercontent.com/23217632/97269578-08cac200-182e-11eb-8e97-6ddbf0f5fbed.png)

**Comment by MateStrysewske** [comment]
This view has been refactored anyway, so this issue is outdated.

**Comment by MateStrysewske** [comment]
If the user is working on area level, the campaign diagrams on the dashboard should be grouped by area instead of region by default.
