### ISSUE TITLE
[External Journal] Inform External Journal about canceled or completed follow-ups [2]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3294]
### Situation Description

SORMAS has a followUpStatus. This can for example be set to CANCELLED. If SORMAS is used alongside climedo, the latter probably needs to be informed about such a change. There should not be a reason to send further questionnaires. This might also be true if a contact is converted to a case, but this is not confirmed yet.

### Feature Description

The idea is to add a followUpStatus to the JournalPersonDto. It can be
```
FOLLOW_UP,
COMPLETED,
CANCELED,
LOST,
NO_FOLLOW_UP; 
```
This should be FOLLOW_UP if any contact of the related person is has this status. 
If there are just CANCELLED contact follow ups for the person, the contactStatus should also be CANCELLED. The same applies for any other possible follow up status values.
If there are various follow up status values for one person, but none of  them is FOLLOW_UP, the status for the external symptom journals should be NO_FOLLOW_UP.
If a changed contactStatus is saved, SORMAS should check if a notification of a related climedo instance is necessary and trigger it in case.

This feature should be verified with HZI before implementation. Also climedo should be informed about this.

**Comment by FredrikSchaeferVitagroup** [comment]
In the contactView, there also is a button to cancel follow up. The same as above should be considered for this button.

**Comment by FredrikSchaeferVitagroup** [comment]
There is a followUpStatus for Contacts and for Cases.  It's an enum with the following values:
`FOLLOW_UP,
COMPLETED,
CANCELED,
LOST,
NO_FOLLOW_UP;`
We should use this to synchronize with climedo, and make sure that the followUpStatus is updated in any reasonable situation 
- [ ] when a Contact is dropped
- [ ] when a Contact is converted to a Case in a system that has Case follow up disabled
- [ ] when a Case classification is set to 'Not a case' in a system with Case follow up enabled. Here, we need to make sure that we don't unreasonably cancel Person's follow up. Imagine a Person has a Contact. The Contact is the converted to a Case. Because of that, the Contact follow up is disabled. Now the Case classification is set to 'Not a case' which disables the person's case follow up as well. We should not have a Person who had a valid (yet converted) Contact and no follow up at all.

**Comment by FredrikSchaeferVitagroup** [comment]
Climedo has something like a followUpStatus, as well as a way to update it via API. They sent it to us.
The follow up status may also be relevant for the followUpEndDates/{since} API endpoint in the ExternalVisitsResource, which is used by PIA.

**Comment by markusmann-vg** [comment]
Error handling should be considered

**Comment by FredrikSchaeferVitagroup** [comment]
If there is a synchronization error, that is written to the server log. For the terms of this issue, that should suffice. For more extensive error handling, we should create a new, more general issue...

**Comment by FredrikSchaeferVitagroup** [comment]
@Candice-Louw  Could you please verify that this feature is acceptable from HZI side?

**Comment by bernardsilenou** [comment]
@markusmann-vg Since we are planning to change the categories of the contact status and followup status, is this not going to affect this story in the near future?

**Comment by bernardsilenou** [comment]
@FredrikSchaefer Few comments from my side
> FOLLOW_UP,
> COMPLETED,
> CANCELED,
> LOST,
> NO_FOLLOW_UP; 
> 
> This should be FOLLOW_UP if any contact of the related person is has this status.
> If there are just CANCELLED contact follow ups for the person, the contactStatus should also be CANCELLED. The same applies for any other possible follow up status values.
> If there are various follow up status values for one person, but none of them is FOLLOW_UP, the status for the external symptom journals should be NO_FOLLOW_UP.
> If a changed contactStatus is saved, SORMAS should check if a notification of a related climedo instance is necessary and trigger it in case.
> This feature should be verified with HZI before implementation. Also climedo should be informed about this.

All the logic sounds good. If i get it right, this sum up to one check: if at least one followup status of all contacts of the person == FOLLOW_UP,
