### ISSUE TITLE
Check whether campaign totals map has the value referenced in the totals definition

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3295]
### Problem Description
If the definition of the series totals contains a fieldId that is not present in the referenced form, the dashboard will throw an undefined error right now when trying to view the percentage values for the chart in question because the totalValuesMap built in CampaignDashboardDiagramComponent is empty in that case. 

### Proposed Change
Show a custom error message when this happens that tells the user that the totals of the series could not be calculated, including the name of the diagram.

**Comment by MartinWahnschaffeSymeda** [comment]
Actually the problem also occurs when no data has been entered in the campaign data form for the series of the total definition.

This means when for the grouping key no result exists in the total map, we have to display "0" in the chart.

**Comment by MateStrysewske** [comment]
Can't reproduce the error found by @MartinWahnschaffeSymeda. Seems to work fine from here.
