### ISSUE TITLE
False calculated Hotspots

### ISSUE THREAD

**Issue by SPoC-Netzlink** [hzi-braunschweig/SORMAS-Project#3297]
### Bug Description

There are massive problems with the generation/calc. of the geocoordinates.
As an example:

Adress:
Jägerstraße 6 in 41564 Kaarst
(First screenshot)

Calculated Longitude/Latitude:
51.2187
6.60631

Seemingly this leads to an wrong adress as the output is:
Kaarster Str. 6 in 41564 Kaarst

As seen in the second screenshot, this could be the cause for Hotspots at a wrong location.
Additionaly: When an adress isn't resolved correct, the related pointer on map is pinned to an completly unrelated position.

### Steps to Reproduce
See above

### Screenshots

![image](https://user-images.githubusercontent.com/70514373/97290006-40466800-1848-11eb-9137-f74d315a8bea.png)

![image](https://user-images.githubusercontent.com/70514373/97290916-7fc18400-1849-11eb-833c-969599e9d791.png)

### System Details
* Device: PC
* SORMAS version: 1.49.1
* Android version/Browser: Aktueller Edge
* Server URL: 
* User Role: Administrator / Surveilance Officer / Doctor

**Comment by leventegal-she** [comment]
Can't reproduce.

Note there are different coordinates on the first screenshot and in the Bug description, and the ones on the screenshot are the right coordinates for the address set in the form.
