### ISSUE TITLE
Cascade admin unit on dashboard creates an error for Central region- Parwan Province

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3304]
### Bug Description
Cascade admin unit on dashboard creates an error for Central region- Parwan Province
### Steps to Reproduce
1. Go to dashboard, select region central and select province Parwan
2. An error pops up on the screen

### Expected Behavior
No errors should show on the screen
### Screenshots
![ED1B1C92-7C6A-4554-8292-1DB23FE427DF](https://user-images.githubusercontent.com/60390281/97316360-08d3bd80-1840-11eb-8867-c4e76d5291c7.jpeg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba Can you provide a log, please?

**Comment by MartinWahnschaffeSymeda** [comment]
Most likely same as #3295

**Comment by MateStrysewske** [comment]
Alternative is #3292, in any way it's very likely that this issue will be resolved by one of those two.
