### ISSUE TITLE
Overlap of data table on charts

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3305]
### Bug Description
Overlap of data table on charts
### Steps to Reproduce
1. Click on dashboard and go to the menu icon on the chart, select data tables
2. Data table shows on top of the next chart
@MartinWahnschaffeSymeda 
### Expected Behavior
Pop up data table for the chart should show instead of on top of the next chart
### Screenshots
![73C2549F-3E69-427C-9B83-688A9A368176](https://user-images.githubusercontent.com/60390281/97340770-93291b00-185a-11eb-8038-4155a406c7eb.jpeg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MartinWahnschaffeSymeda** [comment]
This is an integrated feature of the chart that we can't adjust easily.  We should remove the option from the list. If users are interested in the data they can still download it as excel or csv file.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] disable this feature
