### ISSUE TITLE
"No Data" placeholder on dashboard charts [0.5]

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3306]
### Problem Description
When no data is available the campaign dashboard currently shows empty charts.

![415D73AD-3741-425B-A9A7-836A4CAD7D70](https://user-images.githubusercontent.com/60390281/97356887-51569f80-186f-11eb-8248-17611827ad9b.jpeg)

### Proposed Change
- [ ] When no data is available show a "No data available" label on the x-axis label (check if a dummy value is needed to show the x-axis) (another option is for eg. http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/no-data-to-display/no-data-pie/) - important is to include the placeholder within the chart not to break the diagrams layout done by css grid

**Comment by ChristopherRiedel** [comment]
Hello @tomabadaniel, I would be very grateful if you could provide more information than a title and a screenshot in this issue.
