### ISSUE TITLE
Make date fields in sample creation mask and information non-compulsory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3308]
### Feature Description
Sample entry mask and Sample Information
### Problem Description
Currently, checking the boxes "sent/dispatched" and "received" in the sample creation form requires the additional entry of a date. However, users sometimes do not know such dates (probably because these fields are edited in the health departments and not in laboratories) but would still like to document that the sample was sent and received. When test results have been entered, these boxes cannot be checked when the date is unknown and then shows incorrectly on the overview.

Also include the date and time of the result.
### Proposed Change
Make these fields non-compulsory to allow documenting that the sample was sent and received, independent of the date.
### Additional Information
<img width="761" alt="Screen Shot 2020-10-22 at 8 31 12 PM" src="https://user-images.githubusercontent.com/70317594/97358951-4d8d4200-189c-11eb-90c4-600cae8e7289.png">

### Development Specifications
- on the sample form, make the following fields non-compulsory:
  - date sample was sent
  - date sample was received
- on the pathogentest form, make the following field non-compulsory:
  - date of result

**Comment by bernardsilenou** [comment]
@kwa20 I think date of result should be compulsory, are users creating results without knowing the date of the results?

**Comment by kwa20** [comment]
@bernardsilenou When users receive (to be entered) test results from laboratories they might not necessarily know the date of the result since this might differ from the date they receive the information about the test result itself. If the date might describe either or then I think it could stay compuslory. I know that ideally, labs enter respective test results themselves but this is not actually happening on all productive systems.

**Comment by bernardsilenou** [comment]
@kwa20 the variable "date and time of result" = date the lab result was confirmed/reported/ end of experiment,  as reported by the lab. 
I suggest that we inform the users to ask the lab to provide the date of results to them.

**Comment by kwa20** [comment]
@bernardsilenou I would still make this an optional field then because when the rate of new infections increases rapidly, users will want to just enter the result and procede with e.g. isolation measures for cases etc. They might not have time to contact any lab for missing dates to then enter results and might then tend to just enter any date, even if its inaccurate. They can still add this information later then.

**Comment by StefanKock** [comment]
Self-estimated with 1 by @DavidBaldsiefen
