### ISSUE TITLE
HTTP Status 404 when trying to access API

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#3315]
I have tried: 

- IP/sormas-rest/target/swagger.yaml
- IP/sormas-rest
- IP/sormas-rest/cases/uuids

**Comment by RafaelKluender** [comment]
I solved it, it was an error in the apache configuration. It is working now. 
Proper setting: 
`ProxyPass /sormas-rest http://localhost:6080/sormas-rest`
`ProxyPassReverse /sormas-rest http://localhost:6080/sormas-rest`

**Comment by JonasCir** [comment]
@RafaelKluender Quick follow up question: Was the error in your deployment or did you use SORMAS-Docker?
