### ISSUE TITLE
Quarantine order download does not reliably start

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3317]
### Bug Description
Download of a generated quarantine order document does not reliably start.

### Steps to Reproduce
1. Got to Fallinformation -> Fall for a case where quarantine is "Häuslich" or "Institutionell"
2. Click "Erstellen" in the Falldokumente box
3. Choose a template and click "Erstellen"

The download of the generated document starts sometimes, but not reliably.

### Expected Behavior

Document download should reliably succeed.

### System Details
* Device: Test system Nightly build
* SORMAS version: 1.51.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: https://test-de.sormas.netzlink.com
* User Role: Contact Supervisor

**Comment by syntakker** [comment]
In the modal window to create a document, there seems to be a race condition between creating a FileDownloadResource and closing the modal window.
The solution is not to close the modal window automatically (as it is done in other download features).

**Comment by syntakker** [comment]
This bug is probably not reproducible in a local setup with low latency.

**Comment by ChristopherRiedel** [comment]
Hello @syntakker, it would be nice if you would not use english words in github issues in the future. Thanks in advance.

**Comment by syntakker** [comment]
@ChristopherRiedel Ok. In this specific case, I did so since the installation of the test system I referred to is configured to use German language by default.
