### ISSUE TITLE
Add percentage sign to y-axis labels

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3320]
### Feature Description
All the charts on the dashboard do not have an axis label . This should be a default option in high charts. Please include this. 
### Problem Description
![3F43D605-0394-4B18-86D6-51F3713A651B](https://user-images.githubusercontent.com/60390281/97436543-8d821280-18f8-11eb-9c49-3c49da9af472.jpeg)

### Proposed Change
All the charts on the dashboard do not have an axis label . This should be a default option in high charts. Please include this.

**Comment by MartinWahnschaffeSymeda** [comment]
Discussed this today in the review. What we should do is:

- [ ] for percentage charts display eiter a percentage sign next to the numbers OR add a label to the axis that makes clear there are percentage values.

**Comment by bernardsilenou** [comment]
- It is better to give the full name and unit ie "Proportion (%)" for proportions in percentages
- Just "Count" for raw counts

**Comment by MartinWahnschaffeSymeda** [comment]
See #3663
