### ISSUE TITLE
Correct import template comment and data dictionary description for healthFacility

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3325]
### Feature Description
Import templates and data dictionary
### Problem Description
In the import templates and data dictionary, comments and descriptions for the healthFacility field mention that the name of the facility is to be provided here. However, the values OTHER_FACILITY or NO_FACILITY are actually needed.
### Proposed Change
Change the comment in the import template to depict the appropriate values and move the description in the data dictionary one row below to the field healthFacilityDetails.
### Additional Information
<img width="545" alt="Screen Shot 2020-10-28 at 9 21 16 PM" src="https://user-images.githubusercontent.com/70317594/97494766-1041b680-1967-11eb-9bc9-e3008663fab8.png">
<img width="963" alt="Screen Shot 2020-10-28 at 9 28 39 PM" src="https://user-images.githubusercontent.com/70317594/97494787-16d02e00-1967-11eb-8780-5882ecc093dc.png">
<img width="907" alt="Screen Shot 2020-10-28 at 9 20 08 PM" src="https://user-images.githubusercontent.com/70317594/97494805-1df73c00-1967-11eb-96a8-97c21c6b4a39.png">

**Comment by bernardsilenou** [comment]
@kwa20 did your further check the facility category that is missing on the import template? It would be good to add it here in case you find something.

**Comment by ChristopherRiedel** [comment]
@kwa20 
OTHER_FACILITY and NO_FACILITY are only further options for the healthFacility field. Normally, the name of the facility is specified here. If the case is at home NO_FACILITY is specified and if the case is in a facility that is not in the system OTHER_FACILITY is specified. So the description is correct.

**Comment by kwa20** [comment]
@ChristopherRiedel Thanks for the clarification. Could we add "OTHER_FACILITY" and "NO_FACILITY" to the comments in the import template next to "name of facility"? I think this will already help a lot.

**Comment by bernardsilenou** [comment]
The french users asked me if they can add a third row to hold information like this

**Comment by ChristopherRiedel** [comment]
@kwa20 If there is a need for this please open an issue for it :)

@bernardsilenou I don't get this

**Comment by kwa20** [comment]
@ChristopherRiedel No problem. You can find it here #3398 :)
