### ISSUE TITLE
Region selector is empty when editing Campaign Data Form

### ISSUE THREAD

**Issue by danRosca** [hzi-braunschweig/SORMAS-Project#3334]
### Bug Description
In Campaign Data Form view the Region dropdown is empty
### Steps to Reproduce
1.Go to Campaign Data view
2. Edit a Campaign Data Form

### Expected Behavior
Region drop down should already have a value (like the rest of the mandatory fields)
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
Duplicate of #3336
