### ISSUE TITLE
Developer Option | Configuration | Creation of Cases and Contacts is dependent on multiple fields and this should be changed

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3337]
### Bug Description
This issue details the dependencies which should be fixed in order for people to use the Developer options without workarounds
### Steps to Reproduce
Issue # 1
1. Go to the Developer Options under Configuration when logged in as Admin 
2. Try and Generate some Cases/Contacts without selecting the Disease of Case/Contact

Issue # 2
1. Try and Generate some new Contacts without selecting all the Checkboxes
2. Select only one of the checkboxes and try to Generate Contacts

### Expected Behavior
In the case of issue 1.
Creation of Cases/Contacts should not be dependent on the selection of a Disease of Case/Contact

In the case of issue 2.
Users should be allowed to generate Contacts independently of which and how many checkboxes have been selected

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MartinWahnschaffeSymeda** [comment]
We should (taken from #3247)

Use the Case/ContactGenerationConfig and move the code that is doing the actual generation to the backend
Do the generation in batches of ~50 cases/contacts and use @transactional(REQUIRES_NEW) for each batch

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.57.0-snapshot

**Comment by StefanKock** [comment]
This ticket does not improve the performance/speed of the software, I therefore removed the label.
