### ISSUE TITLE
Developer Option | Configuration | Creating more than 180 Cases returns an error on the server

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3338]
### Prerequisites
Go to Configuration and create a Custom Region, District and Facility

### Steps to Reproduce
1.On the Developer page Select Start+End Date for the generation of cases, the Disease of the Case, the Region and District (select the custom created ones)
2. Try and generate more than 180 Cases at one time

### Expected Behavior
The given number of Cases should be created.
### Actual Behavior 
An error message is displayed
Attached is the server log file
### Screenshots
[server_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5458305/server_log.txt)

### System Details
* Device:
* SORMAS version: 1.51
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: admin

**Comment by DavidBaldsiefen** [comment]
Worked for me on 1.55-SNAPSHOT. Regardless of this, the generation should be moved to the backend though.

**Comment by DavidBaldsiefen** [comment]
As mentioned in #3337 , the generation of contacts/cases/events should be moved to the backend to improve the generators performance.

**Comment by DavidBaldsiefen** [comment]
@AndyBakcsy-she I think this can be closed, can you repeat the test locally? It took a while locally, but didn't produce errors or timeouts
