### ISSUE TITLE
Long loading times when opening case directory (standard/detailed view)

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3340]
### Bug Description
Users (productive systems) experience long loading times when opening the case diretory (standard and detailed view). This does not seem to be directly related to the number of cases in the database (reports mention roughly 1000 cases up to 5000 cases, possibly more). Loading takes up to 1 min or even longer. 
### Steps to Reproduce
1. Select cases in the menu bar.
2. Navigate trough standard and detailed view.

### Expected Behavior
Loading should not take longer than a couple of seconds.
### System Details
* Device:
* SORMAS version: 1.50.0
* Android version/Browser:
* Server URL:
* User Role: admin, surveillance supervisor, contact supervisor (combinations might be different between health department experiencing this problem)

### Additional Information
This problem occured on productive servers after updating to the version 1.50.0 and is NOT reproducable on the test and demo servers (test1401, musterstadt)
possibly relates to #3341

**Comment by MartinWahnschaffeSymeda** [comment]
Next steps:

1. Netzlink will record a postgres log of all queries that are done between the time the user opens the case directory and it finally show, including time stamps. This log will then have to be investigated to look for possible explanations on the slow performance
2. We need to create a list of all code files that are involved in the process of loading and displaying the case directory. For all those files create a diff between 1.49 and 1.50 and see if there is anything that could explain the slow performance

**Comment by MateStrysewske** [comment]
Code files that are involved in the process of loading and displaying the case directory:

* CasesView
* CaseFilterForm
* CaseCriteria
* AbstractCaseGrid
* CaseGrid
* CaseIndexDto
* CaseFacadeEjb (getIndexList)
* CaseListCriteriaBuilder
* CaseJoins
* Pseudonymizer
* CaseJurisdictionChecker
* CaseService (createUserFilter, createCriteriaFilter)

**Comment by MateStrysewske** [comment]
#3137 will fix this

**Comment by bernardsilenou** [comment]
@MateStrysewske Do we still need to work on plan B? getting a pseudonimyze dom db

**Comment by MateStrysewske** [comment]
I suspect you mean setting up a test database with the pseudonymised data from the DB of a GA? If so, no, we don't need that anymore.

**Comment by MartinWahnschaffeSymeda** [comment]
Explanation: The combination of the missing index for the case visits and the newly introduced "distinct" in the case query lead to a drastic slow-down in the query execution.
