### ISSUE TITLE
Long loading times and timeouts during detailed and custom exports

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3341]
### Bug Description
Users (productive servers) experience long loading times and timeouts during detailed and custom exports. This seems to escalate quickly when trying to export higher numbers of cases (e.g. a few thousand more). 

A user reported this issue while using 6 fields (custom export options) for performing a custom export.
### Steps to Reproduce
1. Perform custom and detailed exports of cases.
2.

### Expected Behavior
Loading time should work and take a tolerable amount of time.
### System Details
* Device:
* SORMAS version: 1.50.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
possibly relates to #3340

**Comment by sergiupacurariu** [comment]
fixed with this #3137
