### ISSUE TITLE
Cannot create Event Actions on latest development branch

### ISSUE THREAD

**Issue by Seal33** [hzi-braunschweig/SORMAS-Project#3348]
### Bug Description
On the latest development branch, event actions can no longer be created

### Steps to Reproduce
1. Go to the Event Directory
2. Click on any Event
3. Switch to "Event Actions"
4. Click on Create => "An Error has Occured"

### Expected Behavior
Open Event Action - Creation Popup

### System Details
* Device: Linux / Ubuntu
* SORMAS version: Latest development Build (last commit 8f03159)
* Android version/Browser: Firefox
* Server URL: local
* User Role: Confirmed with Admin, SurvOff, SurvSup

**Comment by AndyBakcsy-she** [comment]
Verified issue on the latest version of SORMAS Version: 1.51.0-SNAPSHOT
