### ISSUE TITLE
Campaign dashboard: Allow user to switch from column to bar chart [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3349]
### Situation Description
The campaign dashboard charts are currently all column charts.

### Feature Description
Users should be able to switch the chart type to bar chart.

- [x] Place the option to switch in the hamburger menu of the chart (change caption depending on which chart type is currently displayed, similar to percentage/total values)
- [x] DiagramType defines what is default

**Comment by MartinWahnschaffeSymeda** [comment]
For now just implement the switch and keep the height as-is for now. Automatically adjusting the height should probably be done post-pilot.

**Comment by MateStrysewske** [comment]
- [ ] Make sure that the diagram type that is displayed on the Dashboard when opening it is according to the value of the "diagramType" column in the database
