### ISSUE TITLE
Case classifications D and E not shown on epidemiological curve

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3353]
### Bug Description
The case classifications "confirmed case with no symptoms" (D) and "confirmed case with unknown symptoms" (E) are not shown as confirmed cases on the epidemiological curve.
### Steps to Reproduce
1. create a case and alter their case classification between all confirmed options.
2. check the epidemiological curve after each respective save.

### Expected Behavior
Epidemiological curve should show all confirmed cases including the ones without or with unknown symptoms.
### Screenshots
<img width="529" alt="Screen Shot 2020-11-01 at 8 49 52 PM" src="https://user-images.githubusercontent.com/70317594/97812825-6c1c8000-1c84-11eb-8aa1-43b6f09259d6.png">

### System Details
* Device:
* SORMAS version: 1.50.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
related to #3352

**Comment by MateStrysewske** [comment]
Not really a bug, but an addition to the existing feature.

**Comment by bernardsilenou** [comment]
The same as the second point of #2662, initially planned fro 1,50. Please have a look at more comments on  #2662 before implementation

**Comment by markusmann-vg** [comment]
will be done in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3004
