### ISSUE TITLE
Wrong dates displayed (and sometimes calculated) on dashboard

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3354]
### Bug Description
The dates or date period that is filtered for on the surveillance dashboard does not get properly adopted in the "Difference in Number of Cases" section.
### Steps to Reproduce
1. Select various combinations of date or date period comparisons to filter the dashboard.
2. Check the displayed dates underneath "Difference in Number of cases".

### Expected Behavior
The date displayed underneath "Difference in Number of cases" should conform to the date that was filtered for. 
### Screenshots
<img width="883" alt="Screen Shot 2020-11-01 at 9 01 03 PM" src="https://user-images.githubusercontent.com/70317594/97813221-efd76c00-1c86-11eb-8845-2feb3d3b3163.png">
<img width="813" alt="Screen Shot 2020-11-01 at 9 03 51 PM" src="https://user-images.githubusercontent.com/70317594/97813224-f6fe7a00-1c86-11eb-983a-647d72860269.png">
<img width="831" alt="Screen Shot 2020-11-01 at 9 05 01 PM" src="https://user-images.githubusercontent.com/70317594/97813227-fbc32e00-1c86-11eb-946b-09aa628d1b47.png">

### System Details
* Device:
* SORMAS version: 1.50.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
- The epi week of 2 different years must not be the same date date interval
- Epi week can either start on Sundays on Mondays
- We should choose one system (preferably starting on Sunday) and use it all over

**Comment by kwa20** [comment]
@bernardsilenou I would prefer to make the week interval dependent on the server because week intervals (sunday-saturday or monday-sunday) should be consistent throughout the system and conform the standard of the country.

**Comment by AndyBakcsy-she** [comment]
Verified issue on the latest SORMAS Version: 1.51.0-SNAPSHOT

**Comment by MateStrysewske** [comment]
For epi weeks, this actually isn't just a display bug. When the current epi week (which is the default filter for the dashboard) isn't a complete week (e.g. because it's Thursday), the comparison period is wrongly calculated which results in wrong comparison data on the whole dashboard.
