### ISSUE TITLE
Migrate to the newest Firebase version

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3356]
The version of Google Crashlytics we're using is deprecated starting on the 15th of November. We need to migrate our app to the new repositories and update our code:

https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

**Comment by AxelNennker** [comment]
Fixed by https://github.com/hzi-braunschweig/SORMAS-Project/pull/3627

**Comment by AxelNennker** [comment]
Fixed by https://github.com/hzi-braunschweig/SORMAS-Project/pull/3838
