### ISSUE TITLE
Campaign basics feature should show the diagram series caption name not the id for selection

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3363]
### Feature Description
Currently when you create a diagram series for selection in the front end campaign basics, the id names are what is shown for selection. This could cause confusion to someone who did not create the campaign charts in the first place. 
### Problem Description
![4561BD4C-76C1-44F1-AE1F-9F103DBE8476](https://user-images.githubusercontent.com/60390281/97876826-5c378700-1cea-11eb-9ce6-17aa57e80638.jpeg)

### Proposed Change
Please use clear caption names in the diagram chart column instead of the ids

**Comment by MartinWahnschaffeSymeda** [comment]
Yes, we also thought so and have already added this to #3290. See https://github.com/hzi-braunschweig/SORMAS-Project/issues/3290#issuecomment-719534736
