### ISSUE TITLE
Unique legend names for multiple form field ids used in one diagram

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3364]
We need to be able to allow one series name that appears in multiple forms to show only one unique value in the legend of the diagram. Custom series name change alone wont fix this. A clear example is Days 1-3 and Revisits having the same legend names like Absent, Absent, Refusal, Refusal respectively. This needs to show only one legend value per diagram if its the same series name

<img width="952" alt="duplicate legend values" src="https://user-images.githubusercontent.com/60390281/97875763-e252ce00-1ce8-11eb-93a5-47c87f4324f7.png">

_Originally posted by @tomabadaniel in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3163#issuecomment-720485591_

**Comment by MartinWahnschaffe** [comment]
@tomabadaniel As discussed today, we will keep the legend entries for now and go with custom colors #2895 and custom series names #3163. So I have moved this to post-pilot.
