### ISSUE TITLE
Add second hierarchy layer for campaign chart tabs [3]

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3368]
### Situation Description

The campaign dashboard currently allows to group charts in different tabs. Based on feedback we realized that we will need another hierarchy layer to do this grouping.

### Feature Description

- [x] Add on optional subTabId to the CampaignDashboardElement
- [x] When a sub tab is defined for a tab, the element shown in the picture below should be displayed (it's the SubMenu we are using to select the disease sub-dashboard on the surveillance dashboard)
- [x] add the field to the campaign edit form
- [x] The CampaignDashboardDataProvider should only load the actual diagram data for the active tab / sub-tab (currently it seems to be loading everything whenever it's opened).

![grafik](https://user-images.githubusercontent.com/23217632/98217508-dfefae80-1f4a-11eb-9835-a2aa3d9ff992.png)

**Comment by tomabadaniel** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3245

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba I'd like to rename this ticket to "Add second hierarchy layer for campaign chart tabs". Ok?

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba FYI: I have updated your original description of the ticket.
