### ISSUE TITLE
[External Journal] Provide API information at runtime [0.5]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3372]
### Situation Description

Symptom journals like PIA have API relevant information stored in questionnaires. This means those systems could adapt to some API changes without deploying a new software version. For this, they need information from SORMAS.

What the Conventic developers have in mind is the following scenario: a new symptom is added to visits in SORMAS. This change is released so that external symptom journals have the possibility to upload visits with the new symptom. Now users want to do exactly that, but they have to wait for a new PIA version to be released and deployed to their system.

### Feature Description

If SORMAS would provide information about the structure of the ExternalVisitDto (including all of its symptoms) at runtime, users were able to add a new symptom to a questionnaire, independent of the PIA version they use. This would facilitate and speed up the process of reporting new symptoms with external symptom journals.

- [ ] Implement a new SORMAS-external-visits-API GET endpoint to provide all information about all endpoints of the External Visits controller. This information can be extracted from the swagger.json automatically generated a build time. Methods to extract this info are already implemented in the ExternalVisitsResourceTest in #3358.

### Possible Alternatives

We could force PIA to stick to the API versions we provide, and release matching PIA versions. This would keep the above scenario more complicated and slow.

### Additional Information

We can not make SORMAS-external-visits-API and PIA versions totally independent of each other. In other scenarios, e.g. if a non backward compatible major version of the SORMAS-external-visits-API is released, PIA still has to adapt and be deployed accordingly. This feature shall just facilitate the process to adapt PIA to new minor versions of the SORMAS-external-visits-API.

**Comment by FredrikSchaeferVitagroup** [comment]
Because of the sheer number of symptoms, it would probably make sence to also transmit the @HideForCountries and @Diseases annotations.

**Comment by markusmann-vg** [comment]
estimation is based on the assumption of having swagger set up.
