### ISSUE TITLE
Android app cannot be accessed and it force closes

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3375]
### Bug Description
Downloading the available update on an Existing app or downloading the new app and installing it also force closes.
 
### Steps to Reproduce
1. Download the latest available version of Sormas app from (test.sormas.netzlink.com/downloads/release)
2. Install the app and try connecting to the server (test.sormas.netzlink.com) as Surveillance officer

### Expected Behavior
The app should accept the login credentials and should be accesisble.
It should not force close and throw an error.

### Screenshots
![App force closes](https://user-images.githubusercontent.com/62763628/98016805-b6297100-1dfe-11eb-875e-8740e9d6a90a.png)

### System Details
* Device: All android devices (tested on Nokia 7 Plus and Samsung S 10)
* SORMAS version: 1.51.0-snapshot
* Android version/Browser: Android version 10
* Server URL: test.sormas.netzlink.com/sormas-rest/
* User Role: SurvOff

### Additional Information
Adb logs attached 
[sormascrash.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5482833/sormascrash.txt)
[sormascrash_take2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5482836/sormascrash_take2.txt)

**Comment by MateStrysewske** [comment]
Another problem is that the synchronization fails. I suspect this might happen when the campaigns feature is deactivated. Will test it.

**Comment by MateStrysewske** [comment]
Yet another problem: The app tries to re-create the campaign table due to typos in the code which will make the app crash when it's first started.
