### ISSUE TITLE
About > Documents > Remove/Hide "Technical Manual (PDF)" link [0]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3380]
### Problem Description
The "current" technical manual is tremendously outdated and reflects negatively on the timeliness and accuracy of information provided in SORMAS.

### Proposed Change
Please hide/remove this link for:
* CH servers
* DE servers (@kwa20 - please correct me if this has changed)

@bernardsilenou - please could you give your input on which other servers this should be applied to?  Would it be an option to remove this completely from all SORMAS versions until we have a more updated document ready from HZI's side?

**Comment by ChristopherRiedel** [comment]
@Candice-Louw Wouldn't it be better to update the manual?

**Comment by Candice-Louw** [comment]
@ChristopherRiedel - Ideally, yes. 😃 

With the different variations in systems and numerous language requests, the tough part is finding and coordinating the resources responsible for providing updated versions, reviewing and keeping them updated regularly, and then to provide a translated version for each of the requested languages in each of the countries and different regions that may request it.

Hiding this is (fingers crossed) a temporary solution only.

Will discuss with the whole team tomorrow on possible alternatives, but for the CH systems, if possible, the request is to rather hide it, please.

**Comment by ChristopherRiedel** [comment]
@Candice-Louw Shozuld we then hide it for everyone, due to it's tremendously outdated?

**Comment by Candice-Louw** [comment]
@ChristopherRiedel - Yes, please - discussed it with @bernardsilenou and @kwa20 to hide/remove from SORMAS for all. Also included it in the sprint priority list for 97 (will be sent to Markus) if possible to do it that soon already, please.  Else thereafter is perfect.

**Comment by bernardsilenou** [comment]
We do not delete but just hide it until we have the updated version

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.53.0-SNAPSHOT
