### ISSUE TITLE
Created a new JSON form definition for Remote Monitoring and form does not show on the list

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3381]
### Bug Description
Created a new JSON form definition for Remote Monitoring and form does not show on the list
### Steps to Reproduce
1. 
2.

### Screenshots
![EC043271-1ED0-4C9D-B0EB-86475CCB0664](https://user-images.githubusercontent.com/60390281/98061184-4e345400-1e19-11eb-8ef6-6042af952d47.jpeg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
[
  {
    "type": "label",
    "id": "RemoteMonitoring",
    "caption": "<h2>Remote Monitoring Data Collection Form</h2>"
  },
  {
    "type": "section",
    "id": "RMDemographics"
  },
  {
    "type": "label",
    "id": "RMDemographics",
    "caption": "<h3>Remote Monitoring Demographics</h3>"
  },
  {
    "type": "male-female",
    "id": "RMGender",
    "caption": "Gender (Male/Female):"
  },
     

  {
    "type": "on-off",
    "id": "RMPhoneStatus",
    "caption": "Is the phone number active and available?",
    "styles": [
      "row"
    ]
  },
   {
    "type": "yes-no",
    "id": "RMVaccTeamVisitVillage",
    "caption": "Did the vaccination team visit your village/area during the last three days?:"
  },
  {
    "type": "yes-no",
    "id": "RMVaccTeamVisitHousePolioDrops",
    "caption": "Did the vaccination team visit your house to administrate polio drops to your U5 years old children?:"
  },
  
  {
    "type": "number",
    "id": "RMTotalNumberU5Children",
    "caption": "Total number of U5 years children in the family",
    "styles": [
      "row"
    ]
  },
    {
    "type": "number",
    "id": "RMTotalNumberUnvaccU5Children",
    "caption": "Total number of unvaccinated U5 years children",
    "styles": 
      "row"
    
  }
  ]
]

**Comment by MartinWahnschaffeSymeda** [comment]
@danieltomaba You need to add any form that is needed to the campaign itself. I have done this now for the October 2020 campaign and it works.
