### ISSUE TITLE
[External Journal] Setup proper External Journal API versioning [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3383]
### Situation Description

External journals are dependent on our API defined in the ExternalVisitsResource. Their developers need to be informed about APi changes. This process and the necessary documents, structures and procedures are supposed to be setup with this issue. Some preliminary work has been done (there are unit test for the API in #3358 , there is some documentation in the ExternalVisitsResource and generated in #3180).

### Feature Description

What is left to do:
~~- [ ] define a sensible version number for the API in the ExternalVisitsResource~~
~~- [ ] add a comment to that version number that explains how to increase it. it is supposed to be as follows: There are major and minor versions of the API (just concerning the external visits).
Within a major version, the latest minor version is compatible with all minor versions before. This is only the case when a new optional field is added.
Otherwise, the major version changes. I think we can not provide several major API versions with dedicated paths at the same time, because it would be too complex (we would need different versions of a DTO for example).~~
~~- [ ] setup and document a standardized way to inform external developers about API changes. Maybe we could use one of our gitter channels for that. It probably makes sense to have a document with descriptions and explanations (as provided as example in #3358), that we provide an updated version of for each (or at least each major) API change. We should also define a time period we give external development teams before we release major API changes.~~
See: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3383#issuecomment-748080102 bellow

**Comment by FredrikSchaeferVitagroup** [comment]
Another option to make the API publicly available, found by @vidi42, may be https://swagger.io/tools/swaggerhub/

**Comment by JonasCir** [comment]
@MateStrysewske @MartinWahnschaffeSymeda 

> External journals are dependent on our API defined in the ExternalVisitsResource. Their developers need to be informed about APi changes. This process and the necessary documents, structures and procedures are supposed to be setup with this issue

This also applies to the French team in general for cases and contacts

**Comment by vidi42** [comment]
Suggest a new process for Clients of the External Journal API
* suggest a tool / way they can use to watch changes on the swagger resource json
* exchange current process from a PUSH notification from SORMAS side with a more PULL oriented check from client side

**Comment by FredrikSchaeferVitagroup** [comment]
According tools to monitor changes might be

- https://app.github-file-watcher.com/ looks very easy to use, but might be limited to monitor master branches (which would not be feasible)
- https://github.com/DevScoreInc/samples/tree/master/github-file-monitor

We also need to clarify which file to monitor.[ This swagger.json](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-rest/src/test/resources/swagger.json) is not really nice for people only interested in the visits-external API endpoints because it describes all other API endpoints, too. Should we upload another file into our repo containing the information of the auto generated runtime API documentation of the external visits resource (`[server-url]/sormas-rest/openapi.json`)?

**Comment by JonasCir** [comment]
Hi,
the file watcher is needed b/c the third party developers needs a head-up that something in the API changed right?
At the moment, the generated sources are not under version control in the first place.

**Comment by FredrikSchaeferVitagroup** [comment]
> the file watcher is needed b/c the third party developers needs a head-up that something in the API changed right?

Exactly.
> At the moment, the generated sources are not under version control in the first place.

Yes and no. There is a rudimentary kind of version control. Most of the times, when you change something affecting the exernal visits API endpoints, [this test](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-rest/src/test/java/de/symeda/sormas/rest/ExternalVisitsResourceTest.java) will fail requesting you to adapt the API version number and update the test resource.

**Comment by StefanKock** [comment]
Automatic commit to development is still open.

**Comment by StefanKock** [comment]
Will hopefully make it to 1.59, but is not mandatory.
