### ISSUE TITLE
[SORMAS2SORMAS] Sending and receiving shared data should be possible [3]

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#3388]
### Situation Description

Currently there is no possibility to update and send back the shared data.

### Feature Description

Implement synchronization:

- [ ] Match embedded object by UUIDs when receiving back
- [ ] ? Delete/Archive data on the receiving system after sending back

### Additional Information
Acceptance Criteria:
use case:
1. GA 1 creates a case
2. sends it to GA 2 with ownership
3. GA 2 adds a sample to the case
4 GA 2 sends it back to GA1 with sample and ownership

**Comment by AndyBakcsy-she** [comment]
Tried to validate this issue on https://test-de1.sormas.netzlink.com/sormas-ui/#!cases/data/WQRXQF-RTHICW-3V6VNM-5FESSAGU . Shared this case with https://test-de2.sormas.netzlink.com/sormas-ui  and edited some of the fields on the case. 
On step 4  the following error message was displayed:

![image](https://user-images.githubusercontent.com/70562142/100381771-5ea7ab00-3022-11eb-90d9-a8a16da72e97.png)

**Comment by leventegal-she** [comment]
@AndyBakcsy-she  Seems like you didn't test on the latest version.
Sending back a case works by using the *Return case* button.

**Comment by AndyBakcsy-she** [comment]
Verified this issue one more time on the right sormas version: SORMAS Version: 1.53.0-SNAPSHOT
