### ISSUE TITLE
Add event participant duplicate detection when linkinig a case to an event [0.5]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3392]
### Situation Description

Situation: a person is event participant. Now that person also is a case. When you link that case to the event the person already is event participant of, what currently happens is that a new event participant is created and added to the event, even though the person already is event participant. After that the person appears as an event participant twice. Once as only event participant (this one was there first), and once as an event participant related to a case (this one was created when linking the case to the event).

### Feature Description

There should be a duplicate detection that automatically uses the already existing event participant for that person, if any exists.

**Comment by kwa20** [comment]
This was mentioned as a comment in #3168. Includes screenshot if desired.

**Comment by FredrikSchaeferVitagroup** [comment]
I fixed the behaviour.
Should I also write a database fix for already existing duplicates in systems in use?

**Comment by FredrikSchaeferVitagroup** [comment]
We discussed internally that there should not be a database update for that.

**Comment by raghupola-vg** [comment]
Tested and works as expected.
