### ISSUE TITLE
Adopt facility address in respective forms

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3394]
### Situation Description
Issue #3390 will introduce the extension of facilities by their addresses. When this has been implemented, the adoption of such deposited addresses will serve as an immense entry effort minimization for users when a deposited facility has been selected in respective forms.
### Feature Description

- Adopt deposited addresses in respective fields when a deposited facility is selected. These include home address and addresses on person forms (cases, contacts, event participants) plus the event location. 

### Additional Information
prerequisite: #3390

**Comment by kwa20** [comment]
Automated adoption of facility contact information (#3931) could be addressed together with this issue.

**Comment by herrling-LRA-KYF** [comment]
It will also be nice if we could set a name for the facility management .

**Comment by MateStrysewske** [comment]
Was taken care of in #4028.

@herrling-LRA-KYF I don't really understand what you mean here - can you elaborate?

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske I mean the name of the management of the facility / "Einrichtungsleitung"
