### ISSUE TITLE
Add values to healthFacility in import template comments

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3398]
### Feature Description
case import template
### Problem Description
the healthFacility column in the case import template only mentions the "name of facility" as an entry possibility in the comments. However, when something other than a facility from the deposited infrastructure data is desired to be imported, the values "NO_FACILITY" or "OTHER_FACILITY" would be applicable. Users are a bit confused as to why some imports fail.
### Proposed Change
Add "NO_FACILITY" and "OTHER_FACILITY" to the comments next to "name of facility"
### Additional Information
<img width="545" alt="Screen Shot 2020-10-28 at 9 21 16 PM" src="https://user-images.githubusercontent.com/70317594/98229731-90b17a00-1f5a-11eb-8027-06fa70e58c7f.png">
<img width="907" alt="Screen Shot 2020-10-28 at 9 20 08 PM" src="https://user-images.githubusercontent.com/70317594/98229744-95762e00-1f5a-11eb-969a-6732e895601e.png">

**Comment by syntakker** [comment]
@kwa20  Would you opt for `NO_FACILITY`, `OTHER_FACILITY`, `<text>`? Or do you think it is better to insert the list of facilities that are configured in the current instance from which the import template is generated (this would explain what to do in depth)?
For both option we should try to make clear that it is critical to have the same combination of name/description and facilityType.

**Comment by syntakker** [comment]
These three issues should be considered together:
#3398, #3755, #3739

**Comment by kwa20** [comment]
@syntakker If it is possible to insert the whole list of facilities, this would need to change consecutively with every additional entry of facilities in the infrastructure data. Just using 'name of facility' might therefore be the easy solution. If we consider listing all deposited facilities, this might get a bit messy when deposited facilities accumulate over time. The advantage would be that facility names are already referenced as usable variables. In both cases, NO_FACILITY and OTHER_FACILITY should be mentioned first.
