### ISSUE TITLE
Task and sample list in case data view is not readable for long descriptions

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3403]
### Bug Description
In case data view: 
- the tasks list is not readable for long descriptions
- text part interfere with each other
- the edit icon (pen) is hard to notice

### Steps to Reproduce
1. Navigate to a case
2. Add tasks with a long descritpion

### Expected Behavior
- the texts in the task overview should be shortened and fit the layout
- for a mor intuitive handling, the description should be clickable to view a task

### Screenshots
![image](https://user-images.githubusercontent.com/5616564/98248246-f7dc2800-1f74-11eb-94ef-0c5879b8e5fe.png)

Setting language to German makes the issue worse. The task assignee string exceeds now the box, strings interfere in the samples box:

![image](https://user-images.githubusercontent.com/5616564/98249394-7a191c00-1f76-11eb-8f3c-76a131921150.png)

### System Details
* Device: Linux PC
* SORMAS version: 1.51.0
* Android version/Browser: Firefox
* Server URL: local
* User Role: admin

**Comment by MateStrysewske** [comment]
@syntakker I disagree with making the description clickable because that prevents selecting and copying the text. The edit button should be obvious enough, especially if there's no text overlapping anymore which might distract users too much to notice it.

**Comment by syntakker** [comment]
@MateStrysewske ok.

**Comment by syntakker** [comment]
After commit 9381de2, the tasks box still does not display cleanly.

- if the language is German, there are still some strings interfering with their box. Consider choosing shorter translations, if possible 
- long descriptions are hard to read in a narrow column. Consider making the description wider or using the full width and arranging other information below
- if the language is English, the text interferes with the tiny pen icon. Consider moving the icon to the upper right corner

![image](https://user-images.githubusercontent.com/5616564/98401206-96e04d00-2065-11eb-9b7f-aa6b077e3773.png)

![image](https://user-images.githubusercontent.com/5616564/98401019-4cf76700-2065-11eb-9570-18cd58e6aa45.png)
...
![image](https://user-images.githubusercontent.com/5616564/98401052-597bbf80-2065-11eb-969e-f5b1db8ae81e.png)

**Comment by raghupola-vg** [comment]
Tested on latest deploy. "Assigned to" Text goes beyond the Margin and slightly overlaps the pen icon. Please adjust these.

**Comment by syntakker** [comment]
@danRosca have you done a fix for the last two comments in another PR?
On the current development branch, the issue persists as described above:
![image](https://user-images.githubusercontent.com/5616564/99789896-9941ad00-2b23-11eb-81b6-dd0c756ef60f.png)

Please close issues only if either they are fixed or you have commented the reason to close it.

**Comment by raghupola-vg** [comment]
The Status and Prio values are left aligned for Tasks and for events and other sections they are to the right.
It looks inconsistent.
![left aligned - Prio and status](https://user-images.githubusercontent.com/62763628/100124667-3e3dec00-2e7c-11eb-99ae-b8c7a5d0a849.PNG)

**Comment by AndyBakcsy-she** [comment]
Validated this issue on SORMAS Version: 1.52.0-SNAPSHOT
