### ISSUE TITLE
Dots on the map disappear after maximizing the epi curve

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3406]
### Bug Description
When the Epi curve is maximized and minimized again, dots previously shown on the map disappear. This is true for the maps on the surveillance and contact dashboards.
### Steps to Reproduce
1. Open the dashboard.
2. Maximize the epi curve.
3. Minimize the epi curve.
4. Check the map again for displayed cases/contacts.

### Expected Behavior
Dots on the map should consistently be displayed on the map.
### System Details
* Device:
* SORMAS version: 1.50.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT using the test.sormas.netzlink.com environment.
