### ISSUE TITLE
SurvNet Adaptations - Create new field „PatientExpositionRole” in the new Epidata form [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3407]
### Feature Description

**Germany only**
Create new field „Accomodation and work in facility” for persons
Cases > Open Case information
Contacts > Open Contact information

--Block 2-- for de-only
“Rolle als “| “in the role of” [SurvNet field name: PatientExpositionRole]
Data Type: Dropdown/enum
Values (de-de) | (en)
• Nicht erhoben | data not collected
• nicht ermittelbar| unknown
• tätig bei | working at
• untergebracht in | accommodated in
• betreut in | cared for in
• andere/sonstige | other
-- End of Block 2--

**out of scope**

--Block 1--
New fields (only DE)-
Heading” Einrichtungen” | “Facilities”
“Unterbringung und Tätigkeit in Einrichtung (de-de) | “Accommodation and work in facility” (en) [SurvNet field name: Exposition]
Next to or under the existing field "Zuständiges Bundesland" (de-de) | “Responsible region” (en)
“Von … bis” | “from … to” [SurvNet field names: FromDate, UntilDate]
Data Type: Date
**MM: Will be treated with the new Epidata and can be mapped when we have the new epidata**
---End of Block 1-----

-- Block 3 --
“Art der Einrichtung” | “Kind of organization“ [SurvNet field name: KindOfOrg, referenceData Adressen]
Data Type: Dropdown/enum
Values (de-de) | (en)

-nicht erhoben-
-nicht ermittelbar-
Einrichtung gemäß § 23 IfSG
o Krankenhaus
o Einrichtung für ambulantes Operieren
o Vorsorge- oder Rehabilitationseinrichtung, in der eine den Krankenhäusern vergleichbare medizinische Versorgung erfolgt
o Dialyseeinrichtung
o Tagesklinik
o Entbindungseinrichtung
o Behandlungs- oder Versorgungseinrichtung, die mit einer der in den Nummern 1 bis 6 genannten Einrichtungen vergleichbar ist
o Arztpraxis
o Zahnarztpraxis
o Praxis sonstiger humanmedizinischer Heilberufe
o Einrichtung des ÖGD zur Diagnostik, Prävention, Therapie
o ambulanter Pflegedienst, der ambulante Intensivpflege in Einrichtungen, Wohngruppen oder sonstigen gemeinschaftlichen Wohnformen erbringt
o Rettungsdienst
Gemeinschaftseinrichtung gemäß § 33 IfSG
o Kindertageseinrichtung (z.B. Kita)
o Kindertagespflege
o Schule
o Heim
o Ferienlager
o Kinderhort
o sonstige Ausbildungseinrichtung
Einrichtung gemäß § 36 IfSG
o voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung
 älterer Menschen
 behinderter Menschen
 pflegebedürftiger Menschen
o Obdachlosenunterkunft
o Gemeinschaftsunterkunft für Asylsuchende u.a.
o sonstige Massenunterkunft
o Justizvollzugsanstalt
o ambulanter Pflegedienst
o aufsuchende ambulante Hilfen
**MM: Will be treated with the new Epidata and can be mapped when we have the new epidata**
---End of Block 1-----

**Comment by GabrielePoggensee** [comment]
IfSG relevant, the data are reported daily by the RKI


![image](https://user-images.githubusercontent.com/68693446/99516960-1851ac80-298f-11eb-8c18-5b909435911d.png)
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Nov_2020/Archiv_November.html

**Comment by StefanKock** [comment]
Removed Milestone Sprint 96 because it was not finished (and not in the Sprint Backlog)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT
