### ISSUE TITLE
SurvNet Adaptations - Create new field “Date of first contact” for contacts [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3408]
### Feature Description
Contacts > open Contact information

New field -
“Datum des ersten Kontaktes“ (de – de) | „Date of first contact” (en)
Next (left) to the field “Datum des letzten Kontakts“ (de – de) | „Date of last contact” (en)
Data Type: Date

**Comment by bernardsilenou** [comment]
@markusmann-vg This will be useful to all instances. Can we activate it for all users? Here is a mockup

![image](https://user-images.githubusercontent.com/12996724/98363492-5960cd00-202f-11eb-9aa4-4c88ed000c37.png)


Default display == date of last contact and unchecked box for multiple day contact

**Comment by MateStrysewske** [comment]
- [ ] Fix DatabaseHelper (DATABASE_VERSION has not been increased leading to app crashing when trying to access contacts)
