### ISSUE TITLE
SurvNet Adaptations - Create new field “Reporting district” for cases and contacts [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3410]
### Feature Description
Contacts > Open contact information
Cases > Open case information

New field (only DE) –
“Meldelandkreis” (de – de) |”reporting district” (en) [SurvNet field name: ReportingCounty]
(The reporting district can be different from the competent district)

Data Type: Dropdown/enum
Values (de-de) | (en)
• Namen der Landkreise (ganz Deutschland) | name of districts (prefill with the district of the reporting user)

### Additional Information

![Bildschirmfoto 2020-12-09 um 15 31 09](https://user-images.githubusercontent.com/62540178/101642788-afac9b80-3a33-11eb-9192-4cfd22217864.png)

**Comment by bernardsilenou** [comment]
@markusmann-vg How does this differ from the "responsible district". When an entity is "transferred / data correction" the new responsible district is interpreted as the reporting district. My suggestion is that we map this variable to responsible jurisdiction for all entities.

**Comment by kwa20** [comment]
@markusmann-vg Is the reporting district not basically the district that the Sormas instance belongs to, which sends the case to the survnet instance and eventually to the higher health institutions?

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.54.0-SNAPSHOT
