### ISSUE TITLE
SurvNet Adaptations - Create new field “Salutation” for persons [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3411]
### Feature Description
Create new field “Salutation” for persons 

New fields (only DE)-
“Anrede”(de-de) | “Salutation” (en) [SurvNet field name: Salutation]
Place new field under the field “name”, it serves as a text block for letters

If possible, the user should be able to create a customized salutation .

Data Type: Dropdown/enum
Values (de-de) | (en)
• Sehr geehrter Herr| dear Sir
• Sehr geehrte Frau | dear Madame
• Sehr geehrte Familie | dear family
• Sehr geehrte Erziehungsberechtigte des Kindes | dear guardian of the child
• Sehr geehrte Dame, sehr geehrter Herr | dear Sir and Madame

**out of scope:**
If possible, the user should be able to create a customized salutation.

**Comment by GabrielePoggensee** [comment]
Not IfSG-relevant. Nice to have for the quarantine orders.

**Comment by kwa20** [comment]
@syntakker This field will solve the request to be able to change the sex into a salutation in the quarantine orders. We would just have to make this field available.

**Comment by syntakker** [comment]
@kwa20 Done :-)
Adressing the properties in a document template is generic, so new properties are available automatically (person.salutation). This applies to all further extensions, too.
Not working yet is the resolution of custom salutations (see https://github.com/hzi-braunschweig/SORMAS-Project/pull/3604#discussion_r536596657)
