### ISSUE TITLE
SurvNet Adaptations - Create new field “name of guardians” for persons [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3413]
### Feature Description
Cases > Open Case-person
Contacts > Open Contact-person
Events > Open Event-participants

Place the field under the field “Staatsangehörigkeit” | “Nationality”. 
Data Type: string

New field –
“Namen der Erziehungsberechtigten” (de-de) | „Name of the guardians“ (en) [SurvNet field name: NamesofGuardians]

**Comment by bernardsilenou** [comment]
@markusmann-vg  This is similar to #2744 It would be good to refine both. Some German users also need name and contact information of  legal guardians which can be mother, father, friends, organization, etc
The new generic design for #2744 may handle all these needs. @kwa20 would add a mockup

**Comment by GabrielePoggensee** [comment]
Not IfSG-relevant, but needed for the local health departments (e.g., quarantine order)

**Comment by kwa20** [comment]
@GabrielePoggensee @markusman-vg this would go hand in hand with #2744

**Comment by vidi42** [comment]
- [ ] Rename the field to `namesOfGuardians`

- [ ] Update translations

**Comment by AndyBakcsy-she** [comment]
Validated issue on the last version of SORMAS-Version: 1.53.0-SNAPSHOT on https://test-de1.sormas.netzlink.com/ environment.
