### ISSUE TITLE
SurvNet Adaptations - Add new pathogen test “IgA serum antibody” to the list of pathogen tests [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3415]
### Feature Description

 Add new pathogen test “IgA serum antibody” to the list of pathogen tests

Case/contact > new sample > Pathogen test

New value –
Date Type: Dropdown
Add new pathogen test: “IgA Serumantikörper” | “IgA serum antibody” [SurvNet: SeroStatus IgA]

**Comment by GabrielePoggensee** [comment]
IfSG relevant: § 11 (1) 1 d: serostatus

Data are transmitted to RKI

**Comment by markusmann-vg** [comment]
we do it for all countries

**Comment by cazacmarin** [comment]
New pathogen test was added successfully.

**Comment by JonasCir** [comment]
@cazacmarin The PR  #3860 was closed with unmerged commits, is this issue really resolved? :)

**Comment by cazacmarin** [comment]
Thanks @JonasCir - my bad. Don't know why I supposed that `Close with Merge` was pressed!

**Comment by JonasCir** [comment]
All good, thanks for your work @cazacmarin, we really need to make progress with SurvNet :)
