### ISSUE TITLE
Add new community facility value for Germany to ReportingType [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3417]
### Feature Description
Refine field “type of reporting” for cases

Case > case information > type of reporting

Change values (only DE) –
- [ ] Add a new value “Gemeinschaftseinrichtung § 34“.
- [ ] New Caption for „community facility“ in Germany to „Gemeinschaftseinrichtung … § 8“ [SurvNet field name: NotificationType]

Data Type: Dropdown/enum
Values (de-de) | (en)
• nicht erhoben- | data not collected
• -nicht ermittelbar- | unknown
• Arzt/Ärztin | doctor
• Labor | Laboratory
• Eigne Ermittlungen | own determination
• Gemeinschaftseinrichtung gemäß § 8 (1) 7 IfSG | Community facility (§ 8 IfSG)
• Gemeinschaftseinrichtung gemäß § 34 IfSG | Community facility (§ 34 IfSG)
• Weiterleitung von einem anderen GA | Forwarding
• Krankenhaus | Hospital or stationary care

**Comment by GabrielePoggensee** [comment]
IfSG relevant - § 9: Definition of notification data to be reported to the local health department

SurvNet: Data not transmitted to state and public health authority

**Comment by JonasCir** [comment]
I'll give this a shot

**Comment by JonasCir** [comment]
@markusmann-vg @GabrielePoggensee I know how to implement the fields mentioned by Markus, however, I am confused about 

>  SurvNet: Data not transmitted to state and public health authority

Does this mean, the fields need to be present in SORMAS, but the fields are never exported to SurvNet at all?

**Comment by JonasCir** [comment]
Blocked on https://github.com/hzi-braunschweig/SORMAS-Project/issues/3653

**Comment by kwa20** [comment]
<img width="345" alt="Screen Shot 2021-01-15 at 11 29 54 AM" src="https://user-images.githubusercontent.com/70317594/104714131-1c970d80-5725-11eb-80ba-03c8608466c6.png">

"not raised" (nicht erhoben) is basically the same as an empty entry or null value and I think should therefore be removed.

**Comment by bernardsilenou** [comment]
@kwa20 You are right. 
- To be consistent with other sections, I would additionally say we rename "not determinable" to "unknown" 
- delete "not raised" option and migrate old records to unknown (ie not determinable)

**Comment by kwa20** [comment]
<img width="412" alt="Screen Shot 2021-01-31 at 1 41 31 PM" src="https://user-images.githubusercontent.com/70317594/106384240-144bfd00-63ca-11eb-8c6c-ef2b911e456b.png">
 Do this issue together with #4165 -> laboratory (DEMIS)

**Comment by bernardsilenou** [comment]
@kwa20 I thougth we decided to add a variable "laboratory name" when lab is chosen 
"laboratory name"  == demis + others, Just as we have in sample
Drop-down with all namse of labs  in the system
![image](https://user-images.githubusercontent.com/12996724/106394438-dddba580-63fc-11eb-9be9-a0d2828b00a2.png)

**Comment by kwa20** [comment]
@bernardsilenou DEMIS is not actually a laboratory so it might not work like that

**Comment by bernardsilenou** [comment]
@kwa20 Thats right, Thanks,
 Then what about removing "laboratory" from the name and just put DEMIS in the drop-down?

**Comment by kwa20** [comment]
@bernardsilenou The way it works is that laboratories report test results through the DEMIS system. Therefore, it is technically still a report of a laboratory but a laboratory report via DEMIS, which SurvNet differentiates.

**Comment by leventegal-she** [comment]
Changing the labels in the translation files needs to be done via Crowdin

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of Sormas version 1.56.0 
 on https://test1402.sormas-oegd.de/sormas-ui/
