### ISSUE TITLE
Add case identification source field to cases [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3420]
### Feature Description

Adapt field (DE only) -
“Fallinformationsquelle” (de – de) |“case identification source“ (en) [SurvNet field name; KnownBy]
Place new field next to case classification

Data Type: Dropdown/enum
New Values (de-de) | (en)

nicht erhoben- | data not collected
-nicht ermittelbar- | unknown
Kontakterfassungs-App Contact tracking app – same hierarchy as presently implemented
Verdachtsmeldung | Suspicion report
Kontaktpersonennachverfolgung | contact tracing
Testung/Reihenuntersuchung | Screening
o Bei Aufnahme in Krankenhaus | on admission in a hospital
o Bei Aufnahme in Pflegeeinrichtung | on admission in care home
o Bei Aufnahme in Erstaufnahmeeinrichtung | on admission in a asylum seeking centre
o Einreise aus Risikogebiet| on entry from risk area
o Bei Mitarbeitenden im Gesundheitswesen| employee in health sector
o In Bildungseinrichtungen (z.B. Kita, Schule) | educational institutions (e.g. day nursery, school
o Sonstiges

### Additional Information

[SurvNet_Anpassungen_missing_fields_201023.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5499753/SurvNet_Anpassungen_missing_fields_201023.docx)

DiseaseKnownBy | Nicht   Ermittelbar | -1
DiseaseKnownBy | Nicht Erhoben | 0
DiseaseKnownBy | Ausbruchsuntersuchung | 5
DiseaseKnownBy | Corona Warn App | 10
DiseaseKnownBy | Kontaktpersonennachverfolgung | 40
DiseaseKnownBy | Testung Reihenuntersuchung | 20
DiseaseKnownBy | Testung   Reihenuntersuchung → Bei Aufnahme In Krankenhaus | 60
DiseaseKnownBy | Testung Reihenuntersuchung → Bei Aufnahme In   Pflegeeinrichtung | 61
DiseaseKnownBy | Testung   Reihenuntersuchung → Bei Aufnahme In Erstaufnahmeeinrichtung | 62
DiseaseKnownBy | Testung Reihenuntersuchung → Bei Einreise Aus Risikogebiet | 50
DiseaseKnownBy | Testung   Reihenuntersuchung → Bei Mitarbeitenden Im Gesundheitswesen | 63
DiseaseKnownBy | Testung Reihenuntersuchung → In Bildungseinrichtung Z B   Kita Schule | 64
DiseaseKnownBy | Testung   Reihenuntersuchung → Sonstiges | 65
DiseaseKnownBy | Verdachtsmeldung | 30
DiseaseKnownBy | Andere Sonstige | 999999

- [x] Add to custom and detailed export

**Comment by markusmann-vg** [comment]
@Candice-Louw  What's the difference between contact tracing and Suspicion report and how will they use it?

**Comment by GabrielePoggensee** [comment]
Correction: This field is only for **cases**

Suspicious report: Notification from  a physician of a suspicious case. 

Definition by the Robert Koch-Institute:
The suspicion of COVID-19 is justified if at least one of the following two constellations is present in a person

-People with any COVID-19 compatible symptoms AND contact with a confirmed case of COVID-19

-Occurrence of two or more pneumonias (pneumonia) in a medical facility, nursing home or old people's home where an epidemic link is probable or suspected, even if the pathogen has not been detected

**Comment by bernardsilenou** [comment]
I read the title and the comments and it sound as if the options are rather related  to the variable "Type of reporting" for cases

**Comment by kwa20** [comment]
I agree with @bernardsilenou. This will be a change of the 'type of reporting' field rather than a new field.

**Comment by kwa20** [comment]
After having another look, changes in 'type of reporting' will be taken care of by #3417. I also cannot find the referenced fields in SurvNet.

**Comment by kwa20** [comment]
data not collected should not be a separate variable because it's the same as "null".

**Comment by kwa20** [comment]
Put the field underneath "type of reporting" instead of next to case classification.

**Comment by kwa20** [comment]
@markusmann-vg I saw DATA_NOT_COLLECTED as a variable option coming through in crowdin but this is basically null in SORMAS and therefore a duplicate variable.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on local environment

**Comment by kwa20** [comment]
Missing values: 

- "Ausbruchsuntersuchung" -> outbreak investigation
- "Andere Sonstige" -> other (first hierarchy)

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as it needs more work

**Comment by raghupola-vg** [comment]
- [ ] Add to custom and detailed export  needs to be implemented

**Comment by raghupola-vg** [comment]
Verified on latest version 1.57.0-snapshot on German servers. Works fine.
