### ISSUE TITLE
Event participant import

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3426]
### Situation Description

Users in France would like to import event particpants.

### Feature Description

ter analysis, the french developers team propose the following specification :

1. addition of an import button in the list of participants of an event
2. this button asks to load a csv file (a popup explains the process and allows you to download a template as is usually the case in SORMAS for other imports)
3. once the file is loaded we start the import.
4. for each line we check if the person indicated already seems in base :

- if similar person (s): a popup is displayed with the list of people. The user then chooses a person from the list * or can decide to finally create a new person (or to go to the next line without doing anything)
- otherwise: we create a new person with the information from the file
- in all cases the person selected or created is associated with the event with the "involvement description" indicated in the file

5. After checking for duplicate person and choosing or creating a new person, we check for duplicate event participant

- if found, merge both
- if not found, create new event participant (similar to case creating)

The mandatory columns of the import file will be: person.firstName, person.lastName and eventParticipant.involvementDescription.

### Additional Information

This is a sub-functionnality of #1642 (we will not work on event import)

@carolinverset @bernardsilenou

**Comment by ChristopherRiedel** [comment]
@ftavin The event participant duplicate detection is currently under development (#3392).
