### ISSUE TITLE
Users > Clicking on column header 'User Roles' doesn't order/sort values

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3427]
### Bug Description
Clicking on table column headers generally allows one to group/sort entries.  Clicking the 'User Roles' column header does not sort/group any values (non-responsive header).  This sort function is used by administrators to keep track of user role groups and quantities.

### Steps to Reproduce
As Admin user, navigate to >
1. Users Tab
2. User Management
3. Click 'User Roles' table heading

### Expected Behavior
Values are sorted.  Currently - values are not sorted (non-responsive column header).

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/98376442-c8482100-2043-11eb-9b8f-68b20dcddba9.png)

### System Details
* Device: Web
* SORMAS version: 1.50
* Android version/Browser: Chrome/Firefox
* Server URL: https://release-ch.sormas.netzlink.com
* User Role: admin

### Additional Information
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/141

**Comment by markusmann-vg** [comment]
With the current implementation this is not possible. 
Will need some refacturing on the backend side. Why is it important? With this knowledge we can provide a workaround.
