### ISSUE TITLE
Improve readability of long button captions in toolbars

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3429]
### Problem Description

In Case Directory and Contact Directory: the label of the bulk mode button is too long in German, French and Spanish. Consider choosing shorter translations (e.g., "Massenbearbeitungsmodus akt..." -> "Massenbearbeitung").
This option is available for user admin only. It is shown when clicking the "More" button (translated to "Mehr" / "Plus" / "Más" in the affected languages).

#### Steps to Reproduce

1.
2.

#### Screenshots

![image](https://user-images.githubusercontent.com/5616564/98437051-a0a69680-20df-11eb-8044-d24ce3479eae.png)
![image](https://user-images.githubusercontent.com/5616564/98437059-bddb6500-20df-11eb-9ce2-793b0a38d8d9.png)
![image](https://user-images.githubusercontent.com/5616564/98437075-d8154300-20df-11eb-8665-6ecac92dd920.png)

#### System Details

* Device: Linux PC
* SORMAS version: 1.52.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: local
* User Role: admin

### Proposed Change

Additionally set caption as description to show text as tooltip.

### Acceptance Criteria

- [ ] The full button caption is visible or accessible.

### Implementation Details

Discuss: What buttons to change/improve?

Ideas how to improve: 
- Set caption as description also (tooltip). Relevant classes : `CasesView.addCommonCasesOverviewToolbar`, `ButtonHelper.createIconButton`.
- set ellipses (...) via CSS to abbreviate long button caption
- Line break within the button (more height for the button)
- more button width

Dismissed:
- Provide caption as alt text or something else that serves also screenreader technologies: Not directly possible on API of vaadin Button

**Comment by Candice-Louw** [comment]
@syntakker - The translations to any language other than English is done independently.

HZI is primarily reponsible for the de-DE translations for example.  Most of the time we only retrospectively realise that translations are incorrect or do not fit in their containers.  It would be helpful to please know where exactly this appears (is it only a specific page/mask?) and we could make the change in CrowdIn. :)  It should then be visible in the next version.

Related for de-DE and de-CH: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3434

**Comment by syntakker** [comment]
It is visible to user admin only in the Case Directory and the Contact Directory under the "More" button. I updated the description accordingly.

**Comment by StefanKock** [comment]
An option could be, that the button caption is also set as button description (which should result in a tooltip). 
Relevant classes : `CasesView.addCommonCasesOverviewToolbar`, `ButtonHelper.createIconButton`.

I would consider this as a change

**Comment by StefanKock** [comment]
I removed this ticket from the Sprint Backlog because it was not commited for Sprint 121 today

**Comment by StefanKock** [comment]
@andrei7bal says he's quite far, so we will pick it again into the Sprint

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.78.0-SNAPSHOT (2abb74a)
The caption is now displayed when hovering over the buttons.

**Comment by StefanKock** [comment]
@roxanamlendea could you check the acceptance criteria and give similar screenshots how it's now fixed?

**Comment by roxanamlendea** [comment]
![captions](https://user-images.githubusercontent.com/89522688/207834060-a0690107-f23c-4b40-b894-78096a06db22.gif)
