### ISSUE TITLE
Introduce bulk edit option for tasks

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3430]
### Situation Description
Bulk actions tasks
### Feature Description
The option to bulk edit tasks (reassign, priority and status change) might be useful for users when many changes for tasks have to be made. This feature should serve as an addition (second step implementation) to the newly to be added filters that are planned for the task management (#3278 ).

- Add options to archive and edit tasks alongside being able to delete them.
- Editing should allow changing of assignee and priority as well as the task status.

### Additional Information
<img width="631" alt="Screen Shot 2021-02-23 at 8 36 25 AM" src="https://user-images.githubusercontent.com/70317594/108813981-583db680-75b2-11eb-8887-d9b887fba487.png">

**Comment by bernardsilenou** [comment]
@carolinverset @ftavin any comment

**Comment by kwa20** [comment]
Add archiving as an option (cf. 4060)

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou same need in France (including archiving)

@kwa20 : can you edit your original description to include archiving (text + mockup) ?

**Comment by kwa20** [comment]
@ftavin @carolinverset I've update the original description. Does that look fine for you?

**Comment by carolinverset** [comment]
@kwa20 @ftavin 
Perfect ! Thank you very much

**Comment by bernardsilenou** [comment]
@MateStrysewske @MartinWahnschaffe  Question related to archiving of tasks please: Should we allow the archiving of tasks linked to parent entities (case, contact, ep) that are active? I though we only archive child entities through their parents but bot the other way round.

**Comment by MateStrysewske** [comment]
I don't see a reason to not do it. One possible use case would be to get rid of "old" tasks for a case that has been active for a while and has a lot of done tasks in order to not flood the task list with tasks that have already been performed.

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @MateStrysewske 
Our team will do the dev on this one !

**Comment by Marko-ilmkreis** [comment]
@ftavin will ths be implemented in the next sprint?

**Comment by ftavin** [comment]
@Marko-ilmkreis
as you can see a pull request is in progress so it is likely to be integrated in the next version (1.59)

**Comment by Marko-ilmkreis** [comment]
@ftavin Ok, Thanks. As its not linked to an sprint I thought there might be a delay.

**Comment by maxiheyner** [comment]
Isse Tracker Comment

**Comment by MateStrysewske** [comment]
* ReST endpoint to retrieve archived tasks is missing

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
