### ISSUE TITLE
Introduce a Community Officer user role

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3433]
### Situation Description
Considering the rising number of cases during the pandemic, health departments start recruiting more and more people to help with contact tracing and related work. For data security reasons, those people are not supposed to see personal or sensitive data outside of a community. Thus, users request the implementation of a community officer role whose restriction reaches down to the community level.
### Feature Description
Introduce a **Community Officer** user role that can be restricted to a specific community. This role could have the same rights as a Contact Officer, the only difference being that they are restricted to a specific community rather than a district only.

Further specific adjustments per health department could be made through user role configurations, if needed at all (e.g. disabling access to cases).

**Comment by markusmann-vg** [comment]
@MartinWahnschaffeSymeda Could we solve this issue, when #898 is implemented?

**Comment by MartinWahnschaffeSymeda** [comment]
@kwa20 @markusmann-vg Actually we do already have a community informant and facility informant user role that are most likely exactly what is needed here.

The only missing part would be the access to the web UI as described in #1960. We originally wanted to have this for APMS, but have now postponed it for the post-pilot phase.

**Comment by bernardsilenou** [comment]
@kwa20 Even though we have the community informant role, the community is not a required field when creating entities. This means they will only see entities with non missing value for community.

**Comment by kwa20** [comment]
@MartinWahnschaffeSymeda If I understand correctly after reading #1960, even with web access, the community is only a pre-selection but not an actual restriction right? I'm afraid this would not be enough to conform to data security guidelines.

@bernardsilenou Would there be any harm in making the field compulsory? If yes, maybe there is an option to make the obligation of entry server dependent (i.e. configurable)?

**Comment by bernardsilenou** [comment]
@kwa20 As Martin already suggested, you do not need to worry about user right restriction. It will work out fine. The community informants only see end edit entities in their community. We may adjust their rights if needed.
Making community required is possible but i think we need to discuss with the uses to be sure that this is what they need and also import the all communities in the system.
For the international system, it is not needed to make community a required variable, thus we need to add a parameter to configure this i suppose

**Comment by kwa20** [comment]
@bernardsilenou I think making this compulsory is logical since this might be important for users wanting to use this restriction but a hinderance for others who don't.
@MartinWahnschaffeSymeda Would it be difficult to add the web UI access before #898 is implemented? Would the Community Informant then also have to be combined with another user role? When trying to create it now, it asks for an associated officer, so I'm assuming this is due to not having web UI access.

**Comment by MartinWahnschaffeSymeda** [comment]
@kwa20 Giving the community and hospital informant access to the UI can be done independently from #898.

Please have a look into https://github.com/hzi-braunschweig/SORMAS-Project/raw/development/sormas-api/src/main/resources/doc/SORMAS_User_Rights.xlsx to check if there are any user rights the community and hospital informant currently don't have, but will need for your use case. Ideally we will not have to combine any user roles here.

The associated officer is needed, for stuff like the automatic tasks. This user is responsible for the informant and all the cases reported by the informant.

I'd suggest to move the discussion over to #1960 now and will close this one as being a duplicate.
