### ISSUE TITLE
Cases and Contacts > Symptoms & Follow-Up Visits > "Set cleared to Unknown" text partially cut off

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3434]
### Feature Description
The "Set cleared to Unknown" button was recently introduced and has been well received. https://github.com/hzi-braunschweig/SORMAS-Project/issues/2584

In languages where the translation is longer (de-DE and de-CH for example), however, the text gets cut off at the end (despite it being translated fully in CrowdIn).  This confuses users and makes the UI translation look incomplete.

![image](https://user-images.githubusercontent.com/65529128/98547701-db9ffa00-2298-11eb-971e-d4d91a70e4c0.png)
![image](https://user-images.githubusercontent.com/65529128/98544994-143dd480-2295-11eb-8a46-122395cc3ec3.png)

Can also be seen in picture 2 here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3121

### Problem Description
Cases and Contacts > Open Case/Contact > Open Symptoms Tab or Follow-Up Visits Mask > "Set cleared to Unknown"

### Proposed Change
Allow margins of the text components to be bigger/fluid, allow text overflow, or allow right-aligning text (or any other viable solution, please).

**Comment by Candice-Louw** [comment]
@syntakker - is this something you (or someone on the team/community) could possibly help with maybe, please?

**Comment by syntakker** [comment]
@Candice-Louw I can have a look at it, but rather in the end if this week.

**Comment by Candice-Louw** [comment]
@syntakker - should we consider shortening the translation as a temporary workaround?

Leer auf "Unbekannt" / Leer auf "Nein" ..?

**Comment by syntakker** [comment]
@Candice-Louw I can do the fix today. Can we still get it into the next release then?

**Comment by syntakker** [comment]
@Candice-Louw Fixed in PR #3538

**Comment by Candice-Louw** [comment]
@syntakker - Thank You! You rock! 🚀 Thank you also for approving this, Maté. 👍

**Comment by AndyBakcsy-she** [comment]
Vaidated issue on SORMAS Version: 1.52.0-SNAPSHOT
