### ISSUE TITLE
NullableOptionGroup breaks field dependencies

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3438]
### Bug Description
The new NullableOptionGroup does not work with FieldHelper methods like setVisibleWhen, setRequiredWhen etc. because the value comparison fails (e.g. it compares "Yes" to a set that contains "Yes").

We probably need to extend all affected methods in FieldHelper to differentiate between NullableOptionGroups and all other fields; if the field is a NullableOptionGroup, `getNullableValue` should be called instead.

Alternatively (and even better) the NullableOptionGroup could be extended by overriding getValue and allow that method to return the first value from the set, but that could have side effects.

**Comment by kwa20** [comment]
@MateStrysewske Here are some examples that I found where dependencies fail that I think relate to this issue:

**Entering symptoms (either tab or visits):**
<img width="716" alt="Screen Shot 2020-11-11 at 7 38 02 PM" src="https://user-images.githubusercontent.com/70317594/98851286-55c9ad80-2456-11eb-9a55-ab1a0d03928e.png">

**Selecting yes for travels and gatherings in epi data:**
<img width="707" alt="Screen Shot 2020-11-11 at 7 37 11 PM" src="https://user-images.githubusercontent.com/70317594/98851361-6da13180-2456-11eb-92a0-2591d4d6c372.png">

**Contact category (either creation for or contact information):**
<img width="540" alt="Screen Shot 2020-11-11 at 7 40 16 PM" src="https://user-images.githubusercontent.com/70317594/98851411-83165b80-2456-11eb-92df-e0ab645e7e9c.png">

**Previous hospital visits:**
<img width="725" alt="Screen Shot 2020-11-11 at 7 51 12 PM" src="https://user-images.githubusercontent.com/70317594/98852062-6890b200-2457-11eb-92df-2caa09347bf1.png">

@bernardsilenou You might want to check additional dependencies shown on international servers (e.g. animal contacts in epi data, possibly more)

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT
Validated the issue for Ebola Virus disases ( multiple field dependencies) + Covid 
Also verified if the NullableOptionGroup for Contacts is working as expected.
