### ISSUE TITLE
[DEMIS2SORMAS] Get Lab-Results from DEMIS Importer into SORMAS

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3440]
### Situation Description
@HolgerReiseVSys has the source code of the DEMIS Importer. The DEMIS system is used to send Lab-Results directly to the health departments. Normally this data is saved in SurvNet and might 
a.) lead to a new case
b.) updates a case

### Feature Description

1. Part of the story
------------------
Investigate the DEMIS Importer and create a work breakdown structure, so that development can start

**Comment by FredrikSchaeferVitagroup** [comment]
The RKI states that DEMIS uses[ this FHIR-profile](https://simplifier.net/covid-19labormeldung) for imports. It might give hints about what to expect for data coming from DEMIS.

**Comment by FredrikSchaeferVitagroup** [comment]
The referencing issues are not yet ready to implement, but should be ready for a planning session. That's why I consider this issue done now.
