### ISSUE TITLE
Make all dropdown fields filter for substrings [1]

### ISSUE THREAD

**Issue by chThie** [hzi-braunschweig/SORMAS-Project#3445]
## Feature Description
The drop-down fields in Sormas forms (like e.g. "New Case") accept a given set of valid values.  
One can either click on the field to choose one of the values with the mouse or type it in via keyboard.  
When using the keyboard, the set of valid values is filtered by the typed input. 

## Problem Description: 
**Not all (but some) drop-down fields filter for substrings of valid entries.**
The ones which do not, just filter for entries which begin with the same letters as the input.

![dropdown-filter](https://user-images.githubusercontent.com/34276062/98671399-79a4ca80-2354-11eb-903a-7e3296603cc5.gif)

### Steps to Reproduce (German language demo version)
-> https://demoversion.sormas-oegd.de/sormas-ui 

1. Go to e.g. "Fälle"->"Neuer Fall".
2. Click into the drop-down "Zuständiges Bundesland" and choose "Nordrhein-Westfalen".
3. Click into the drop-down and type "Borken" to look for the district "LK Borken".
4. => No valid entries are suggested, since the field does not filter for substrings. If you type "LK Bork", the entry is suggested.  

If you try something similar in the field for "Geschlecht" (e.g. by typing a substring of "Männlich", like "nli"), this field filters by substring.

## Proposed Change: 
**All dropdown fields should also filter by substrings** instead of just by the letters they are starting with.

## Additional Information:
The district in this example just starts with "LK" because of the german short cut for "Landkreis", which means district.   

The corresponding classes seem to be `v-filterselect` and `v-filterselect-input`, but I can not identify why the fields are acting in a different way. 

There are a few related issues concerning drop-down field input which I will link here:  #3443 #3444 #3445.
They are created in consultation with @kwa20, based on feedback of German public health departments.

Look into `SormasFieldGroupFieldFactory`, have `ComboBoxWithPlaceholder` and maybe other subclasses in mind.

## Developer Specifications

- Use `FilteringMode.CONTAINS` everywhere `ComboBox` is used

**Comment by chThie** [comment]
## Steps to Reproduce (English language play version)
-> https://sormas.helmholtz-hzi.de/sormas-ui

1. Go to e.g. "Cases"->"New case".
2. Click into the drop-down "Responsible region".
3. Type "River" to look for the region "Cross River".
4. => No valid entries are suggested, since the field does not filter for substrings. If you type "Cro", the entry is suggested.  

If you try something similar in the field for "Sex" (e.g. by typing a substring of "Female", like "ema"), this field filters by substring.

**Comment by Candice-Louw** [comment]
Notes:
+ Please make search non-case sensitive (i.e. search in uppercase or lowercase values should return results in both)
+ Please ignore white space where necessary (i.e. at the start of the search string)

**Comment by StefanKock** [comment]
From refinement (resulted to a 1): 
- Change all ComboBoxes to `Filtering.CONTAINS`
- Out of scope: Ignoring special characters

**Comment by DavidBaldsiefen** [comment]
Apparently Vaadin 7 and Vaadin 8 ComboBoxes are randomly used. The V8 `ComboBox` does not contain a `setFilteringMethod`, so I will need to investigate which method is used here by default, and if it can be changed

**Comment by StefanKock** [comment]
See [Javadoc for V8 ComboBox](https://javadoc.io/static/com.vaadin/vaadin-server/8.13.0/com/vaadin/ui/ComboBox.html#setDataProvider-com.vaadin.ui.ComboBox.CaptionFilter-com.vaadin.data.provider.ListDataProvider-), there is a new pattern with [ComboBox.CaptionFilter](https://javadoc.io/static/com.vaadin/vaadin-server/8.13.0/com/vaadin/ui/ComboBox.CaptionFilter.html). But ComboBox L425 already contains a `toLowerCase & contains` filter.

**Comment by DavidBaldsiefen** [comment]
We decided it would make sense to implement a `ComboBoxHelper` similar to the `ButtonHelper`, to streamline the code and make changes in the future more easy. However, we need to decide if that Helper should use V7 or V8 ComboBoxes, as I don't think the mix we currently see in the code is very good practise

**Comment by VGitVlad** [comment]
Validated ticket on Sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment
