### ISSUE TITLE
Missing GEO Button

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3447]
### Bug Description
The Geo button is missing on any person form.
### Steps to Reproduce
1. Open any person form (cases/contact/event participants)
2. Check the home address and addresses fields.

### Expected Behavior
Geo button should be available and selectable.
### Screenshots
<img width="753" alt="Screen Shot 2020-11-11 at 11 33 17 AM" src="https://user-images.githubusercontent.com/70317594/98801482-242ef300-2412-11eb-92c6-4a4fe02842fe.png">

### System Details
* Device:
* SORMAS version: 1.51.0
* Android version/Browser: Chrome, Firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Is the geo service correctly set up on this system (in the properties)?

**Comment by kwa20** [comment]
@MateStrysewske Were there any adjustments that would have had to be made when updating from 1.50.0 to 1.51.0?

**Comment by MateStrysewske** [comment]
@HolgerReiseVSys @FredrikSchaeferVitagroup @vlad-ciucescu Can one of you guys answer that question?

**Comment by vlad-ciucescu** [comment]
@MateStrysewske It is not related to anything I worked on

**Comment by kwa20** [comment]
Could be fixed by adjusting the variables in the sormas properties.
