### ISSUE TITLE
Change geocoding server for switzerland

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3452]
### Feature Description
Use:
geo.admin.ch sein (API siehe api3.geo.admin.ch)

### Additional Information
Consider: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2087

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] check whether what we have built in #2087 is working with api3.geo.admin.ch and provide an example of how to use it.

**Comment by markusmann-vg** [comment]
@leventegal-she Might be a good one for you ;-)

**Comment by MartinWahnschaffeSymeda** [comment]
Swiss setup properties

```
geocodingServiceUrlTemplate=https://api3.geo.admin.ch/rest/services/api/SearchServer?searchText=${street}+${houseNumber},${postalCode}+${city}&type=locations&geometryFormat=geojson&limit=1
geocodingLongitudeJsonPath=$.features[0].properties.lon
geocodingLatitudeJsonPath=$.features[0].properties.lat
```

**Comment by markusmann-vg** [comment]
@asohh Please take a look and take care of the configuration

**Comment by nliakm** [comment]
Added the configuration add tested it succesfully.

**Comment by vidi42** [comment]
Since this was just about configuration I will close the ticket
