### ISSUE TITLE
Import and Export formats has to be similar so that they can be reused [3]

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#3453]
### Problem Description
For the moment, exported file formats (for cases and contacts) cannot be used for importing as the files are in different formats and cannot be reused.
The export is formatted to be human-readable while the import directly has to reference the field names to work.

### Proposed Change
Both import and export formats has to be ~~similar~~ equal so that they can be reused (exported from one system and imported in an other system)

Relies on #comment #2537 and #3455

- [ ] Include the field property as the first line of the export, so the import know which field the data belongs to
- [ ] Make the second line that has the field captions a "comment line" with two hashtags

This is should be done for

- [ ] all infrastructure types: country, area, region, district, community, facility
- [ ] events
- [ ] contacts
- [ ] cases
- [ ] campaign data

What needs to be checked:

- [ ] cases: would it work to import detailed exports, custom exports and sample exports
- [ ] contacts: would it work to imported detailed an follow-up exports?

### Additional Information
Consider to change, extend the popup hint
"You can also use an export file instead of the template, please don't use an outdated export to import data as this may fail"

**Comment by MartinWahnschaffeSymeda** [comment]
@raghupola-vg I have refined the issue

**Comment by MartinWahnschaffeSymeda** [comment]
This is really important for performance tests

**Comment by leventegal-she** [comment]
@MartinWahnschaffe 
Date values in export are formatted based on the user language while the import accepts only a few fixed date formats.

It's not clear which date format to use first while parsing dates during import. 
eg. 01/11/2020 matches both mm/dd/yyyy and dd/mm/yyyy so just trying to parse with the first format and if it fails then trying the second one could lead to wrong date values imported

**Comment by MartinWahnschaffe** [comment]
The relevant method seems to be DateHelper.parseDateWithException. I'd suggest the following:

1. Try the format defined for the user's language (see Language.dateFormat). Use this as base format for the following two points.
2. Try the other two types of separators (.-/)
3. If the user's date format uses "yy" also try "yyyy" and vice-versa.

Note: This means that we will still do not support something like "12 Dec 2020", but from my point of view that's fine.

@MateStrysewske What do you think?

**Comment by leventegal-she** [comment]
@MartinWahnschaffe, @MateStrysewske 
Currently it's not possible to import the birth date of the persons because it is exported as a date(like) string but the import requires separate fields for day, month and year.

Do you have a solution or workaround for this in mind?

**Comment by MateStrysewske** [comment]
@leventegal-she The only solution I can think of right now is to extend the importers to be able to specifically handle birth dates, and then just treat the string like any other date in the file if that is possible
