### ISSUE TITLE
Pre-fill facility type and category options on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3457]
### Bug Description
It is not clear if this is a bug or motion. I labelled it but hoping we can correct it during the hot-fix phase.
The default predefined options for faculty as specified in the initial issue were implemented only for the web app.
### Steps to Reproduce
1. Create a case on mobile app
2.

### Expected Behavior
When place of stay == facility,  set facility category == medical facility and facility type == hospital
### System Details
* Device: Samsung galaxy
* SORMAS version: 1.51
* Android version/Browser: 10
* Server URL:
* User Role: SO

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0 app
