### ISSUE TITLE
Add set clear to unknown to mobile app [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3458]
### Feature Description
The button "set clear to unknown" was added to the web app but not on the mobile app 
we can use a fluid row with 3 columns just as we have for the clinical confirmation variable
### Problem Description
affected screens:

- [ ] symptoms 

### Proposed Change
- Add the set clear to unknown  button on mobile app.

**Comment by AndyBakcsy-she** [comment]
Verified the existence and the functionality of the "set clear to unknown" button on the mobile app 
Tested on personal Android device with an upgrade from version 1.52.0 to 1.54.0-SNAPSHOT

**Comment by raghupola-vg** [comment]
"Set clear to No" button is not fully visible on the Mobile app.
It is good to have it's own row for the buttons text to be fully visible.
![Set cleared to no button is not fully visible](https://user-images.githubusercontent.com/62763628/104911269-e35fd700-598a-11eb-86d2-7f50e05ea14f.png)
