### ISSUE TITLE
Admin Surveillance Supervisor cannot delete cases

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3460]
### Bug Description
The newly introduced Admin Surveillance Supervisor does not seem to be able to delete cases as suggested in the user rights document.
### Steps to Reproduce
1. Open or create a new case.
2. Scroll to the bottom of the case information form and look for delete.

### Expected Behavior
This role should be able to delete cases.
### Screenshots
<img width="667" alt="Screen Shot 2020-11-11 at 6 24 57 PM" src="https://user-images.githubusercontent.com/70317594/98843652-8d7f2800-244b-11eb-833d-19ab308b9bb4.png">

### System Details
* Device:
* SORMAS version: 1.51.0
* Android version/Browser: Chrome, Firefox
* Server URL: test1401.sormas-oegd.de
* User Role: Admin Surveillance Supervisor

**Comment by MateStrysewske** [comment]
Cause for this issue is that we're currently explicitely checking whether the user has the Admin user role, not whether they have the user right to delete cases.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT using the Admin Surveillance Supervisor role
