### ISSUE TITLE
[External Journal] Improve the i18n of the interface [0.5]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3463]
More precisely, it happens here (`PersonFacadeEjb`, L. 323, called whenever an existing person is saved):
```java 
	private void handleExternalJournalPerson(PersonDto existingPerson, PersonDto updatedPerson) {
		SymptomJournalStatus status = existingPerson.getSymptomJournalStatus();
		if (SymptomJournalStatus.REGISTERED.equals(status) || SymptomJournalStatus.ACCEPTED.equals(status)) {
			ExternalPersonValidation validationResult = externalJournalService.validatePatientDiaryPerson(updatedPerson);
			if (!validationResult.isValid()) {
				throw new ValidationRuntimeException(validationResult.getMessage());
			}
		}
		// 5 second delay added before notifying of update so that current transaction can complete and new data can be retrieved from DB
		final ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
		Runnable notify = () -> externalJournalService.notifyExternalJournalPersonUpdate(existingPerson, updatedPerson);
		executorService.schedule(notify, 5, TimeUnit.SECONDS);
	}
```
In `ExternalJournalService.validatePatientDiaryPerson` the validation of phone numbers appears to be quite strict:
```java
		if (StringUtils.isNotEmpty(email)) {
			EmailValidator validator = EmailValidator.getInstance();
			validEmail = validator.isValid(email);
		}
		if (StringUtils.isNotEmpty(phone)) {
			validPhone = false;
			PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
			try {
				Phonenumber.PhoneNumber germanNumberProto = phoneUtil.parse(phone, "DE");
				validPhone = phoneUtil.isValidNumber(germanNumberProto);
			} catch (NumberParseException e) {
				logger.warn("NumberParseException was thrown: " + e.toString());
			}
		}
		boolean validBirthdate = true;
```
especially it seems that only valid German phone numbers are accepted?

_Originally posted by @syntakker in https://github.com/hzi-braunschweig/SORMAS-Project/issues/3451#issuecomment-725451992_

**Comment by FredrikSchaeferVitagroup** [comment]
The post above shows that the external journal interface currently is not internationalized and that this irritates non german users.
The purpose of this issue is to either internationalize the interface, or to at least write explaining comments where only german systems are considered.

**Comment by vlad-ciucescu** [comment]
> Also, interface related error messages seem to be only available in german.

If you are referring to the validation messages (such as `externalJournalPersonValidationEmail`, `externalJournalPersonValidationPhone`), these will be translated through Crowdin.

If you are referring to the messages displayed during registration, such as:
![image](https://user-images.githubusercontent.com/65336966/98956221-6f2b3200-2508-11eb-83cd-559bf56d2958.png)

These come directly in German from CLIMEDO and we cannot translate them, we simply display them. The only option here would be that CLIMEDO sends us language keys instead of messages, for which we can then add translations in our system.

>  at least write explaining comments where only german systems are considered.

The validation is done only with German format since the external journals are only used for Germany (as far as I know). If needed for other countries we can make this configurable. I agree that a comment there might be useful to inform why the validation is made for German numbers

**Comment by FredrikSchaeferVitagroup** [comment]
The validation message are okay so far.
What irritates the user here is the fact that only german phone numbers are accepted.

**Comment by vlad-ciucescu** [comment]
@FredrikSchaefer in this case we validate for Climedo, which accepts German phone numbers.
It is true that SORMAS accepts any kind of phone number and if external journals aren't used, we don't validate the number like that. But if we want to register a person in Climedo, then the number must be a valid phone number.

**Comment by vidi42** [comment]
Regarding the phone number issue, as discussed for #3266 we should just make sure to apply the validation when clicking the button for Climedo / PIA and display an error message which tells the user that the number has to be in the external system's required format.

**Comment by vlad-ciucescu** [comment]
The validation is done in the following cases currently:

- if the person is not registered in the external journal, when the button is clicked.
- if the person is registered in the external journal, when saving the contact/case after updating -> it has to be done now or it leads to data inconsistencies between the systems

**Comment by FredrikSchaeferVitagroup** [comment]
I think what irritated @syntakker in #3451 is that numbers are assumed to be german.
I asked the climedo developers. They also accept phone numers for other countries.
We could maybe adapt this.
I think part of the problem here might be missing documentation. For example: core developers might know that the only patient diary linked to SORMAS currently is (the german) climedo. Other developers might not. That's why german messages and phone number assumptions appear irritating to them. Maybe we should make things more clear via code comments.

**Comment by vidi42** [comment]
- [ ] Add JavaDoc describing the current functionality for External Journal (ex validations for phone numbers)
