### ISSUE TITLE
Use translated text related to GDPR in app according to users language

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3469]
### Bug Description
There are 3 text messages related to GDPR that are not pulled from crowdin.
### Steps to Reproduce
1. Connect to a server with version 1.50 or 1.51 with a new user account
2. A pop up message will appear thee first time you login
### Expected Behavior
The popup message should be in the users defined language  

Pull translations from crowdine

### Screenshots
French Swiss, from https://test.sormas.netzlink.com/sormas-ui/ on 1,52
![image](https://user-images.githubusercontent.com/12996724/98931193-04fd9780-24de-11eb-8688-378302979a50.png)

### System Details
* Device:
* SORMAS version: 1.51
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
@MateStrysewske This may just be that the translations have not been pulled. The goal fro creating it is that we do not forget to consider it in the release.

**Comment by MateStrysewske** [comment]
@bernardsilenou I can't pull translations from Crowdin for the hotfix. If there's any specific text you want me to manually translate for the hotfix, please send it to me via mail. I'll copy the French GDPR text over to Swiss-French.

**Comment by MateStrysewske** [comment]
@bernardsilenou Just realised that the Swiss-French translation is still correct in the main release (1.51.0), and thus also in the hotfix. Which other languages are affected?

**Comment by bernardsilenou** [comment]
Thanks Maté, I will send today.

**Comment by bernardsilenou** [comment]
@MateStrysewske I found not other txt apart from the GDPR that you have already done. All is good.
