### ISSUE TITLE
Showing charts in full screen has black background

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3473]
### Bug Description

Showing charts in full screen has black background. 

### Steps to Reproduce
1. Go to the dashbord (e.g. campaigns)
2. Click the options icon of a chart (three stacked bars) and select "view in full screen"

### Expected Behavior

Background should be white.

### Screenshots

![grafik](https://user-images.githubusercontent.com/23217632/98942646-a0970400-24ee-11eb-8cc7-607dd17a73bc.png)

### System Details
https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!dashboard

**Comment by StefanKock** [comment]
Was not part of Sprint 96

**Comment by MartinWahnschaffeSymeda** [comment]
@BarnaBartha We have the same issue for the epi curve on the surveillance dashboard and for the charts in the statistics.

Switching the background color to white by default would make it look bad on the surveillance dashboard, because there it is intended to have a blueish background. For the statistics the full-screen chart currently is also not working properly. So my suggestion would be:

- [ ] don't allow the full-screen option for charts in the statistics and on the surveillance dashboard. 

![grafik](https://user-images.githubusercontent.com/23217632/102223718-5c2fc700-3ee5-11eb-8e33-6aec9b6ef723.png)
