### ISSUE TITLE
Archiving campaigns currently not working and campaign data still shown

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3477]
### Feature Description
It was already possible to archive campaigns.

### Problem Description
Currently as an admin when editing a campaign I can only delete, but not archive it.

In addition the campaign data of archived and deleted campaigns is still shown in the campaign data view, when no campaign is selected. 

### Proposed Change

- [x] make sure archiving of campaigns is working
- [x] make sure archived and deleted campaigns don't show in any drop-down that allows to select the campaign (should already be working, just make sure it really works)
- [x] make sure campaign data of archived and deleted campaigns is not shown in the campaign data list, when no campaign is selected

**Comment by AndyBakcsy-she** [comment]
Verified this issue on SORMAS Version: 1.52.0-SNAPSHOT
