### ISSUE TITLE
Add setting to disable audit log of properties [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3479]
### Situation Description
Currently SORMAS comes with two audit/history systems. Once is the audit log, that logs all changes to an external database, including who changes it. The other are the postgres history tables that automatically create a history entry whenever a table row is modified. Ideally we would use only the later one, but this is currently not possible, because it misses information on who changed the data.

Still it looks like we are running into performance problems on big systems, so it would be good to have a setting in the properties file to disable the audit log.

### Feature Description

- [x] Add a setting to  the properties file to disable the attribute logging of the audit log (we have the history tables for this anyway), but be enabled be default.
- [x] Change Auditor.getValueContainerOf to not inspect the attributes when disabled
- [x] The information on whether the property audit log is enabled or disabled needs to be cached!

**Comment by kwa20** [comment]
@MartinWahnschaffeSymeda Would it be possible to not only have the possibility to enable/disable the audit log but also reduce the logging of imports overall, so not every individual entry is logged but rather the import itself? Disabling the audit log might not be an option for some users due to data security regulations. However, these users should also benefit from this change.

**Comment by JonasCir** [comment]
Random thought, but would it be possible to somehow delay the audit logging/make it asynchronous and execute it after the heavy lifting has been done?

**Comment by StefanKock** [comment]
I looked through symeda auditlog, all known performance improvements are applied latest with #329.

**Comment by MateStrysewske** [comment]
Disabling the audit log is not the right approach to solve the problems here. We rather need an improvement due to the reasons outlined by @kwa20.

**Comment by StefanKock** [comment]
Overlaps concerning finding performance impact with #3481.

**Comment by StefanKock** [comment]
Logging that an entity is changed is not that costly (according to tests by @HolgerReiseVSys), but the attribute inspect (twice: at load and at persist).

Possible solution: Change `Auditor.getValueContainerOf` to not inspect the attributes (as feature configuration).

**Comment by MartinWahnschaffeSymeda** [comment]
@StefanKock @MateStrysewske I have updated the feature description based on your feedback. Does this work for you?

**Comment by StefanKock** [comment]
Description fits for me.

**Comment by StefanKock** [comment]
In 39a3bfa the imports in `AuditContextProducer` are reordered. Please make sure you order them as intended (check IDE setup).
