### ISSUE TITLE
Translations > Missing variables

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3485]
### Bug Description
Certain strings are not translated in SORMAS, despite all values having been saved and translated in CrowdIn.  For some of these variables, there seems to be no associated/existing listing in CrowdIn to translate.

### Steps to Reproduce
Set language to de-DE or de-CH for example.  English variables show up.

1. Cases and Contacts > Open Case/Contact > Follow-up > "Symptomatic", "Temperature"
![image](https://user-images.githubusercontent.com/65529128/99197319-140c7000-2792-11eb-9cff-8175f0546975.png)

2. Cases and Contacts > Open Case/Contact > Person > Addresses > "Postalcode", "AddressType"
![image](https://user-images.githubusercontent.com/65529128/99197487-1fac6680-2793-11eb-851f-a47800fd360a.png)

3. Cases > Open Case > Therapy > "Prescription Period", "Prescription Route", "Treatment Route"
![image](https://user-images.githubusercontent.com/65529128/99197548-7fa30d00-2793-11eb-861b-b3270b4ad8a1.png)

4. Cases > Custom Export > 
![image](https://user-images.githubusercontent.com/65529128/99197734-854d2280-2794-11eb-87d3-1bbe26159ee4.png)

5. Samples >
![image](https://user-images.githubusercontent.com/65529128/99198142-f1308a80-2796-11eb-8337-087ce93c09d2.png)

6. Info > "About" + "Documents"
![image](https://user-images.githubusercontent.com/65529128/99198599-0824ac00-279a-11eb-8c6b-c32e68bf32d0.png)

7. Contacts > Follow-up View > "Report Date"
![image](https://user-images.githubusercontent.com/65529128/99290852-2d1f2a80-283f-11eb-9fe2-da7718e59b48.png)

### Expected Behavior
Translated strings.

### System Details
* Device: Web
* SORMAS version: 1.51.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de and https://sb-ch.sormas.netzlink.com/
* User Role: admin, national user

### Additional Information
Possibly related: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3131

@kwa20 @bernardsilenou @syntakker - Please add anything that I may have missed?

**Comment by kwa20** [comment]
This one also exists on the case status map layers.

<img width="548" alt="Screen Shot 2020-11-15 at 11 50 32 PM" src="https://user-images.githubusercontent.com/70317594/99199222-da416680-279d-11eb-9254-3ae28566609e.png">

**Comment by Candice-Louw** [comment]
@MateStrysewske - please don't push this one back too far if possible, please...  It is visually quite impactful on the system users (who remind us of these mistakes in the SORMAS ticket systems quite often).  We would also need a few days to do the translations in CrowdIn and then make sure that they sync properly for it to have the desired effect.  Asked from Gérard directly on 09.12.2020 too.

**Comment by raghupola-vg** [comment]
Tested on latest deploy and all mentioned translations above looks fine,  except number 6. About and Documents and 
number 5. Samples (Associated Contact and Associated Event Participant)

**Comment by BarnaBartha** [comment]
@raghupola-vg This needs to be retested once crowdin updates go in.
