### ISSUE TITLE
[DEMIS2SORMAS] Setup a LabMessage and a LabMessageFacade

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3486]
### Situation Description

German healtch facilities use [DEMIS ](https://www.rki.de/DE/Content/Infekt/IfSG/DEMIS/DEMIS_node.html) to exchange lab results. These need to be imported into SORMAS.

### Feature Description

#3487 and #3488 require the LabMessageDto and the LabMessageFacade class. Those two shall be implemented here.

The LabMessageDto class shall hold all the information relevant to SORMAS (especially #3488) that is available in a message from a demis-server. 

If there is some crucial information in a demis-message that can not yet be stored in SORMAS, it should be added to a related entity (probably Sample, Person, or PathogenTestResult). That crucial information shall of course also be contained in the LabMessageDto.

It is necessary to also implement a LabMassageFacade which is responsible for persisting the LabMesage as an Entity in the database and provide backend methods.

### Open Questions

- What data is to be stored in an ExternalLabMessage? An incomplete list below:
    - personFirstName : String
    - personFastName : String
    - birthDateDD : Integer
    - birthDateMM : Integer
    - birthDateYYYY : Integer
    ....

The LabMessageDto and the LabMessage (which represents the LabMessageDo as an entity) hold fields from several entities (like Person, Sample...). Some of the fields have identical names. e.g. there may be the firstName of the Person the Sample was taken from, and the firstName of the responsible LabOfficer. Thats why the naming of fields in the LabMessage shall have the name of the related entity as prefix (e.g. personFirstName and labOfficerFirstName).

### Additional Information

This issue results out of #3440.

**Comment by JonasCir** [comment]
> How to integrate the DEMIS importer application into SORMAS instances?

Could we add a dedicated container to the stack which handles the DEMIS importing and writes the data into the database? By this we could separate 'national' import logic from the main stack and don't ship the logic to other countries.

**Comment by FredrikSchaeferVitagroup** [comment]
In a discussion with HZi it came out that almost all the information from DEMIS must be transmitted and stored in SORMAS, as the messages are not always transmitted to the Gesundheitsamt that needs to report the messages cosequences (e.g. new case), but to the Gesundheitsamt that is responsible for the area of the reporting laboratory. Thus, the labMessage shall be transferred via SORMAS2SORMAS to the Gesundheitsamt that needs to report.

**Comment by MateStrysewske** [comment]
Further refinement:

* The LabMessage/LabMessageDto classes should contain fields for the data that is necessary to a) build the grid of lab messages that will be implemented in #3488, b) build the filters for this grid and c) are required to build the resulting entities in SORMAS (e.g. person first and last name and sample date time)
* All additional information that will not be displayed in SORMAS outside of lab messages will be stored as JSON in an additional "labMessageDetails" field; the content of this field will later be used to display all the details of the lab message in a generic way

**Comment by FredrikSchaeferVitagroup** [comment]
Covered by the implementations for this issue is 

- linking to an external labmessage adapter and requesting new labmessages as well as html representations for labmessages from it
- viewing labmessages in a directory, basic sorting and filtering
- creating a person, case, sample and pathogenTestResult out of a labmessage via processing in UI
- person and case duplicate detection
