### ISSUE TITLE
[DEMIS2SORMAS] sormas-demis module

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3487]
### Situation Description

German health facilities use [DEMIS ](https://www.rki.de/DE/Content/Infekt/IfSG/DEMIS/DEMIS_node.html) to exchange lab results. These need to be imported into SORMAS.

### Feature Description

The initial purpose of this new module is to have a `ExternalLabMessageFacadeEjb` with a `public List<ExternalLabMessage> getNewLabMessages()` which returns not formerly fetched messages from a DEMIS server, converted to ExternalLabMessages. 
There exists a tool called demis importer, from which code fragments can be used to fulfill this task. It is available @FredrikSchaeferVitagroup. 
The getNewLabMessages() should throw appropriate exceptions when calls to a DEMIS server fail.
The ExternalLabMessageFacade and ExternalLabMessage are defined in #3486.

Further methods from the ExternalLabMessageFace of course also need to be implemented. 

### Open Questions

- Which fields in the message from demis map to which fields in the ExternalLabMessage?

### Additional Information

Preriquisite: #3486.

This issue results out of #3440.

**Comment by vidi42** [comment]
Moved to internal system
