### ISSUE TITLE
[DEMIS2SORMAS] Enable users to convert ExternalLabMessages to assigned PathogenTestResults

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3488]
### Situation Description

#3486 and #3487 enable users to import and parse lab results from [DEMIS](https://www.rki.de/DE/Content/Infekt/IfSG/DEMIS/DEMIS_node.html) via ExternalLabMessages. Now users need to be able to process these ExternalLabMessages so that their data is integrated into the SORMAS workflow.

### Feature Description

There shall be an ExternalLabMessage directory implemented that lists all ExternallabMessages. The user shall be able to select a ExternalLabMessage and process it. 

![Message_Directory](https://user-images.githubusercontent.com/67001822/99248123-45c01e00-2808-11eb-9168-98feab8c8a91.png)

Each ExternalLabMessge contains data about a Person, a Sample, a Laboratory and a PathogenTestResult. At the end of processing an ExternLabMessage, this data should be related to existing or put into new entities of a Person, Sample, Laboratory and PathogenTestResult in SORMAS.

The first step for that is to relate the ExternalLabMessage to a Person. The already implemented person duplicate detection shall be used to check if the person already exists in SORMAS. 

If so, the 'Pick or Create Person' from the contact and case creation shall be opened. If the user decides to pick an existing person, another view shall display all Contacts, Cases and Event Participants related to that person. The user can then decide which Contact, Case or EventParticipant the ExternalLabMessage's sample data to assign to. The user should also be able to create a new Case, Contact or Eventparticipant for that Person here. 

![Assign_PathogenTestResult](https://user-images.githubusercontent.com/67001822/99366940-93489380-28b9-11eb-8fb1-520b0f4ef574.png)

SORMAS should also check if a Sample similar to the one generated with data of the ExternalLabMessage is already assigned to any Contact, Case or EventParticipant related to the person. If so, SORMAS should reccomend to assign the ExternalLabMessage's PathogenTestResult to it. 
Based on the user's selection, SORMAS should assign the ExternalLabMessage's PathogenTestResult data to some Contact, Case or EventParticipant, creating a new Sample for that entity if necessary.

If there is no Person existing in SORMAS, the user shall be able to select to create either create a Case, a Contact or an EventParticipant. After that is finished, the ExternalLabMessage's Sample and PathogenTestResult shall be assinged to the created entity.

Once the PathogenTestResult is saved related to some entity (be it a Contact, Case or EventParticipant), the ExternalLabMessage's status should be set to processed. It should by default then not be viewed in the ExternalLabMessage directory (user should ba able to remove a default filter to also see processed messages).

Each time the ExternalLabMessage directory is opened, the ExternalLabMessageFacade.getNewLabMessages() shall be called and the results shall be included into the grid of ExternalLabMessages displayed.

### Open Questions

- One problem may be that an ExternalLabMessage contains data of a laboratory that can not be found in SORMAS. In this case, theoretically an admin user has to create a matching laboratory first before the ExternalLabMessage can be processed. How do we handle this? I think this could be problematic in a health departments workflow, as it might stall the processing of ExternalLabMessages which probably is expected to happen quick and frequently.
- Which users shall be able to see and process ExternalLabMessages? As a first setup we could enable this feature for Surveillance Supervisors and National Users. But this has probably to be more precisely defined later. Is it anyone who can edit Cases? What about users who can just edit Contacts?

### Additional Information

Preriquisites: #3486, #3487.

This issue results out of #3440.

**Comment by FredrikSchaeferVitagroup** [comment]
What is not yet considered in the ticket is that viewing the original lab message's content (from the LabMessage.labMessageDetails) may be necessary for processing lap messages. For example: whether a PathogenTestResult is positive or not is currently decided on several fields in a lab message from DEMIS. This decision seems to be made by a person, and there is no clear logic behind it. Hence users processing lab messages need to be able to see the original messages content  at relevant steps (or even any step) of the processing.
We plan to have a method in every external module providing lab messages that takes a lab message as input and returns a detailed html representation of the message.

**Comment by MartinWahnschaffe** [comment]
@ChristopherRiedel Please introduce the user right for NATIONAL_USER and SURVEILLANCE_SUPERVISOR for now.

**Comment by ChristopherRiedel** [comment]
This issue is now being used to make a start on this matter. This part will be released in 1.54.0. Everything else will be done in another release. The follow up issue for this is #4058
