### ISSUE TITLE
Permanent delete function in DB

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3499]
### Situation Description

In France, the law requires the deletion of data older than 3 months.
To date, SORMAS only allows data to be soft deleted but does not allow you to delete entities permanently.
Pedestrianization is not a solution because the law requires that pseudonymize entities should also be hard deleted after 12 months. Since entities are reference by others, a simple qsl quarry cannot guarantee a perfect deletion without harming other entities that are still active.

### Feature Description
In general, 
- it would be important to have a bulk deletion function to specific users only. Maybe create a specific user role for this action.
- user should be able to filter the directory and bulk delete.
- for control purposes, there should be a double validation rule with the text like "permanent delete" that the user has to type in order to carry out the task
- when an entity (case, contact, event ) is deleted, system should only deleted associated entities (person, sample) that are not linked to other entities that should not be deleted.
- there should be server parameter to configuration
### Possible Alternatives
sql quarry to do such a task
### Additional Information

@bernardsilenou @olivierLeuci

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  @MateStrysewske  @JonasCir  
Any recommendation?

**Comment by JonasCir** [comment]
@carolinverset 
There is also this issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/2100

**Comment by MartinWahnschaffe** [comment]
See also #4156 and #4223

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe  Do we still need to work on this issue and add a configuration for it or https://github.com/hzi-braunschweig/SORMAS-Project/issues/3499#issuecomment-779750483 is enough?

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou I can't answer this. This question would go to the users/countries that need this.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
@carolinverset just confirmed that this is not still an urgent need for France, I would close the ticket for now.

**Comment by carolinverset** [comment]
Yes it's OK to close... sorry for the late answer !
