### ISSUE TITLE
Version increased on fetch for entities using hibernate-types

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#3502]
### Bug Description
The changedate (version) for entities that contain json's and save them using hibernate-types is increased on get even if there is no update.

### Steps to Reproduce

- Edit an existing campaign
- Change something about the campaign data charts, so validation fails, when saving (eg. empty tab name)
- Fix the problem and try to save again
- "The data could not be saved, because it has been changed in the meantime"

### Expected Behavior
- save should be possible after fixing the problem

### Additional Information
The issue is there for all entities having json and using the hibernate-types
Similar issue described here:
https://github.com/vladmihalcea/hibernate-types/issues/203
Although using the latest hiernate-types does not solve the issue still.

**Comment by StefanKock** [comment]
The linked reported defect uses _jsonb_ and has also a @TypeDef on the class. I do not know if this might be the reason the reported defect is not fixed in our setup.

**Comment by MateStrysewske** [comment]
@StefanKock Very likely yes, the fix they did explicitely targets the jsonb type, not json.

**Comment by MartinWahnschaffeSymeda** [comment]
There were two problems:

1. Campaign data form did not reload after saving -> added refresh UI
2. POJOs stored as json did not have an implementation of equals. It looks like either hibernate or hibernate-types unnecessarily created now instances of those POJOs. Those aren't equal to the original objects, so hibernate thinks there has been a change.
