### ISSUE TITLE
Campaign data forms unexpected behaviour when editing/creating campaign.

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#3503]
### Bug Description
When I add two rows to the campaign data forms and try to define them, something strange happens. It looks like one of the row gets selected (blue background) and then I can't delete them anymore and going to the dropdown of the other row pre-selects the value that I have selected for the other row.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] enabled buffered mode to workarround not working edit buttons
- [ ] Disabled selection for abstracteditablegrid
- [ ] Changed dashboard elements grid form binding to the diagram id
- [ ] Added refresh to CampaignFormsGridComponent to updated after value is picked
