### ISSUE TITLE
Using bulk action "edit" on pseudonymized case causes error

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#3504]
### Steps to Reproduce
1. Enter bulk edit mode
2. select pseudonymized case
3. click bulk action "edit"

### System Details
* Device: PC
* SORMAS version: 1.52.0-SNAPSHOTö
* Android version/Browser: Firefox
* User Role: admin

**Comment by MateStrysewske** [comment]
Seems like this is already fixed.
