### ISSUE TITLE
Selecting "place of stay" in bulk edit form causes error

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#3505]
### Steps to Reproduce
1. enter bulk edit mode
2. select case
3. select bulk action "edit"
4. select "change facility"
5. select place of stay

### System Details
* Device: PC
* SORMAS version: 1.52.0-SNAPSHOT
* Android version/Browser: Firefox
* User Role: admin/national user

**Comment by saeedkhawaja** [comment]
FYI 
@mar-ro 
@ClaudeMarksteinerCSI

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.52.0-SNAPSHOT on local machine 
The error does not show anymore. 
However, changing the Facility while being in bulk edit mode logged in as the admin and saving, afterwards logging in with the Nat User and reopening the case, it seems the changes are not saved.
