### ISSUE TITLE
It's possible to proceed in bulk edit to change the facility without selecting one

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#3506]
### Steps to Reproduce
1. enter bulk edit mode
2. select case 
3. select bulk action "edit"
4. select "change facility"
5. hit save

### Expected Behavior
Dont be able to proceed without "place of stay"

### System Details
* Device: PC
* SORMAS version: 1.52.0-SNAPSHOT
* Android version/Browser: Firefox
* User Role: admin/national user

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.52.0-SNAPSHOT
