### ISSUE TITLE
Add "Date of outcome" to Detailed Export for Cases [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3514]
### Feature Description
The field "Course of disease" for **Cases** is included in the **Detailed export**. In addition, it should also be possible to export the corresponding date field **"Date of the course of the disease" ("Date of outcome")**.

![image](https://user-images.githubusercontent.com/62540178/99528638-e21c2900-299e-11eb-9f76-640bcd895cfe.png)

**Comment by AndyBakcsy-she** [comment]
Validated issue on local environment on SORMAS Version: 1.54.0-SNAPSHOT

**Comment by mmarzaganov** [comment]
@markusmann-vg date of outcome appears to be still an issue, as I cannot export this column, even when specifically marking the field via custom case export. I have also confirmed that all the cases I picked had a reported outcome with a date.

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she @vlad-ciucescu I did a test but did not find the outcome date in the exported data, only  "Date of death (M/d/yyyy)" was present:
Serverver: https://release-international.sormas.netzlink.com/sormas-ui/
version 1.54.1

I would reopen the issue since we are still testing 1.54

**Comment by bernardsilenou** [comment]
I added some refinement that may help here #4016
@MateStrysewske I realized the date of outcome is auto populated with the current date when not provided by the user. I think we should change this. Use default as NA, else use user provided outcome date/ date of death of the person is cause of death == disease of case.
If outcome == recover, then user only date provided by user or is remain NA.

**Comment by MateStrysewske** [comment]
@bernardsilenou 1.54.0 was already released. Please don't reopen issues that have already been released. If there is still a problem with this, open a new one.

**Comment by bernardsilenou** [comment]
Ok, I would open a bug request then and link to this one.
