### ISSUE TITLE
SurvNet - Bulk Action for sending multiple cases to Survnet instance [2]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#3517]
@markusmann-vg please add the details

### Feature Description
Reuse bulk edit from SORMAS2SORMAS

As a user of SORMAS with the right to send a case to the survnet instance, 
I want to use the bulk action to send cases from my (filtered) case directory to my Health department's Survnet instance

### Additional Information
Instead of sending one package, every case is an individual package, which has to be downloaded, unpacked and imported in SurvNet

**Comment by markusmann-vg** [comment]
- [ ]  Trigger same action as for single case // 

![Bildschirmfoto 2020-12-18 um 12 59 13](https://user-images.githubusercontent.com/62540178/102612524-23842d80-4131-11eb-824c-db07fa667842.png)

Additional info:
- Validate if all selected cases are COVID-19 Cases
- Validate that you are the owner of the case (and it was not sent to another sormas instance with ownership)
- Error management (If we cannot send all, the sending fails! We should tell the user, which case(s) was/were responsible why the transport failed)

**Comment by bernardsilenou** [comment]
@markusmann-vg  Is this about multiple case or single case or both ?? 
I do not get it but have some suggestions:
Can we not automatically control for
_"Validate that you are the owner of the case (and it was not sent to another sormas instance with ownership)"_
Using the jurisdiction of the user and that of the entity??

For _"Validate if all selected cases are COVID-19 Cases"_ : A required variable with caption "choose disease" (dropdown) + backend filter for this disease only may be more generic

**Comment by vidi42** [comment]
The way communication with SurvNet works at the moment is that any number of cases is synchronized in a single batch, which makes it impossible to pin point which case was responsible in case of a failed transfer.

This is a known issue and should be handled separately from this issue.

**Comment by AndyBakcsy-she** [comment]
Is there an environment where this ticket could be validated?
