### ISSUE TITLE
SurvNet - Add confirmation popup when you want to send a case to SurvNet [0.5]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#3518]
@markusmann-vg please add the details and translations

### Feature Description
Assumption: Basic confirmation popup with Yes/No options.

**Comment by HolgerReiseVSys** [comment]
The gateway may set the external id of the case, 
so this should only be possible when the case is saved.
Afterwards the form may have to be reloaded.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest SORMAS Version: 1.56.0 using https://test1402.sormas-oegd.de/sormas-ui environment.
