### ISSUE TITLE
Prototype integration of LBDS in SORMAS app [8]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3522]
### Situation Description
An Low-Bandwidth-Data-Synchronization is being developed to send data from mobile app to the server based on SMS.
LBDS will be running as an app on it's own on the Android device and receive and send intents to do the actual communication.
API to be used: https://github.com/crowdcode-de/lbds-android-messaging

### Prerequisits

@gorefest We will need the following things to implement this and try whether it's working

- [x] The lbds-android-messaging package via maven central

Question: Is there any way we can try whether this is working, once we start to implement it? Or should we just add it and you will try to make it work?

### Feature Description

- [x] Create a class that receives LbdsResponseIntents
- [ ] Update the https://github.com/crowdcode-de/lbds-android-messaging project with the name of the actual class that will receive the intents from LBDS. Can be commited by @MartinWahnschaffeSymeda
  **still a typo in class name `LbdsRecevierComponent`. This has to be changed synchronously in the lbds service app**
- [x] Include a button in the dev mode view of the app that allows sending all ~~the first~~ unsynchronized cases
- [x] Use the CaseDataDto and PersonDto, but only send the required fields of the case and person. Leave all other fields empty. Make sure the generated JSON does not create empty attribute entries. 
- [x] ~~To identify which persons have to be sent, check for persons with "modified" set to true, that at the same time are associated to a case (case.person_id). Among these persons identify the ones that have changes in the essential data (as listed below). You can identify the changes by comparing the modified version of the person with the unmodified snapshot that can be retrieved with AbstractAdoDao.querySnapshotByUuid (when no snapshot is returned, it means that the person has not been sent to the server before).~~
- [x] ~~To identify which cases need to be sent, check for cases with "modified" set to true. Then also compare the essential fields of the case, as done for the person OR add a new date field that contains the info when the data was sent last via LBDS~~
- [x] ~~While the persons and cases are being sent via LBDS, we need to somehow store which data is currently being send. Once the data has been sent, we have to either update the existing snapshot with the values of the essential fields that have been sent OR create a snapshot based on an empty case and fill it with the sent values. There is currently no mechanism for this, so this will be quite difficult.~~
  **to be solved
  **sent requests are persisted in the LBDS service app and processed upon receiving a response**
- [ ] ~~Process http response from LBDS and update snapshots / modified flag accordingly~~
  ~~**modified flag is reset, snapshot has to be written**~~
- [x] Show LBDS buttons only if the LBDS app is installed
- [x] Make an additional SORMAS-LBDS URL configurable for debugging purposes
- [x] Use encryption to store LBDS credentials and secrets
- [x] Document usage and installation + debug setup
- [x] Create a table to persist times of sent and received objects. Table name: LbdsSync, Columns: Uuid, lbdsSent, lbdsReceived. This table provides the criteria whether or not to send an object via LBDS and replaces the criteria stated above.
- [x] To be send via LBDS are: new Cases for which no LBDS response has been received, new Persons of these cases for which no LBDS response has been received.
- [x] Show a notification when LBDS messages for cases or persons  are sent or received

Difficulties related to the whole process

1. LBDS is async (minutes/hours), this means that it can easily happen that a user changes the data while it's still being sent
2. We are only sending a part of the data, so after it's sent, we only know a partial snapshot of the truth on the server
3. We can't pull data before sending, which means that when sending changed data this may conflict with changed data on the server. Currently this is denied based on the change date (TOO_OLD) -> for now only send NEW cases via LBDS

-> @syntakker will create process charts to have a better discussion basis for this

The following fields should be sufficient:

* Person: uuid, first name, last name, sex
* Case: uuid, person reference (uuid), disease, report data, reporting user (uuid), region, district, facility type, health facility (uuid)

### Limitations of the Prototype

- Prototype only sends new cases, not changes of existing ones
- Sending must be done via the hidden developer area in the settings
- Persons and cases must be sent separately
- A bit more data sent than necessary -> #5891

**Comment by gorefest** [comment]
I just deployed lbds-http-android and lbds-android-messaging. It can be found in maven central from 25.11.2020 with coordinates 

```  <groupId>io.crowdcode.sormas.lbds</groupId>
    <artifactId>lbds-http-android</artifactId>
    <version>1.0.0</version>
    <packaging>aar</packaging>
```

and 

```    <groupId>io.crowdcode.sormas.lbds</groupId>
    <artifactId>lbds-android-messaging</artifactId>
    <version>1.0.0</version>
    <packaging>aar</packaging>
```

**Comment by gorefest** [comment]
@MartinWahnschaffeSymeda Please drop me a note when you have adapted the component name in lbds-android-messaging so I can make a new release.

**Comment by gorefest** [comment]
@MartinWahnschaffeSymeda I added a prototype for handling RSA Key Exchange (KEX) and deployed a new version to maven central. Take a look at https://search.maven.org/search?q=lbds please. The convention is to have a bidirectional handshake. A Request always will contain the incoming public key to be replaced, a response can be recognized by having both keys in position. We should set this up bi-di.

**Comment by StefanKock** [comment]
Cannot be finished for 1.59

**Comment by StefanKock** [comment]
Moved this ticket to Application Team, handover is planned

**Comment by StefanKock** [comment]
Put on waiting to work on more urgent topics

**Comment by VitaliHZI** [comment]
Hey all, how far are we here?

**Comment by syntakker** [comment]
@VitaliHZI With workarounds for known LBDS bugs, I'm able to send data to the SORMAS server and receive the http response via LBDS.
Identified bugs on the LBDS side are communicated , waiting for those to be fixed.

**Comment by syntakker** [comment]
Updated feature specification.
