### ISSUE TITLE
Cases > "New EPID number" button visible on CH test server

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3526]
The EPID number was hidden for CH system Cases and Contacts in 1.51.1 as part of the hotfix (BIG THANK YOU from the CH colleagues for that btw! 🎉 ): https://github.com/hzi-braunschweig/SORMAS-Project/issues/2996

On the HZI test server with CH Konfig (https://release-ch.sormas.netzlink.com/), the field and button are hidden (image right). ✔️ 
On the CH test server (test.sormas.ch), the "Generate New EPID Number" Red button is visible (left). ❓ 

![image](https://user-images.githubusercontent.com/65529128/99549471-f4f02700-29b9-11eb-8344-da1d74e332be.png)

The button should also be hidden (like the actual entry field is hidden) on CH systems.

@AndyBakcsy-she - I'm not sure what type of occurrence this is?  Config related?  Code related?  Unrelated? (Did the merge on the pull request happen in time as this was a late request?)

Both servers are running 1.51.1 and accessed by users with the same access rights.

Please let me know if you need more info as I can confirm this on the CH test server (test.sormas.ch)?  Please also let me know if I should create a bug report for this?  Or should I advise them to wait and see what happens at the next release (it may fix itself)..?

**Comment by MateStrysewske** [comment]
@Candice-Louw Turned it into a bug report because it basically is one. We simply forgot to also remove the logic that displays or hides this button when the epid number isn't supposed to be used at all.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS-Version: 1.52.0-SNAPSHOT

**Comment by Candice-Louw** [comment]
@MateStrysewske , @AndyBakcsy-she | Could you please confirm if this was part of the 1.52.1 release or only for 1.53?  On the official Swiss test system (test.sormas.ch) the button is still visible (but not on our HZI CH test system).  I'm not sure how to proceed.

![image](https://user-images.githubusercontent.com/65529128/101891523-70508d00-3ba2-11eb-8f26-a89ff5171c61.png)
![image](https://user-images.githubusercontent.com/65529128/101892627-e9041900-3ba3-11eb-8638-a9e6de0eb240.png)

**Comment by MateStrysewske** [comment]
Should've been resolved in 1.52.0; I will check it again!

**Comment by MateStrysewske** [comment]
@Candice-Louw Hopefully fixed in #3757

**Comment by Candice-Louw** [comment]
@MateStrysewske - Thank you!
