### ISSUE TITLE
Incorrect display of the list of modalities of the facility type variable (event)

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3536]
### Bug Description
To date, when the user opens an event and does not select any facilty category, the facility type variable proposes the entire list of modalities. It seems to us that the field should be displayed only after the selection of a modality of the facility category field.

### Steps to Reproduce
1.opening of an event for which the facility category is empty
2. the facility type field proposes all the modalities whereas it should be hidden, grayed out, or empty

### Expected Behavior
when an event opens, the facility type variable remains hidden as long as the facility category is not defined.

### System Details
* Device: 
* SORMAS version: 1.51.1
* Android version/Browser:
* Server URL: https://test1401.sormas-oegd.de/
* User Role:admin

### Additional Information
@bernardsilenou @ftavin @olivierleuci @emond-fuseau

**Comment by bernardsilenou** [comment]
@carolinverset I can see with you that we need to refine and validate the options of type of place and facility.
There are duplicate information. The categories of type of place, eg public places, hospital, festivities are either categories or type of a facility.
![image](https://user-images.githubusercontent.com/12996724/100032558-959a7880-2df8-11eb-9179-1d2aec3caefc.png)

![image](https://user-images.githubusercontent.com/12996724/100032964-77814800-2df9-11eb-81f7-c1e2fd764f5e.png)

**Comment by MateStrysewske** [comment]
Will be done in #3617
