### ISSUE TITLE
Investigate migrating off Travis and/or optimizing builds, particularly for pull requests

### ISSUE THREAD

**Issue by tbroyer** [hzi-braunschweig/SORMAS-Project#3541]
Travis is queuing builds (for pull requests for instance) for quite a long time before they're run. Add to that build times of 20 minutes per job (with 2 jobs for JDK 8 and JDK 11, this means an execution time of 20 to 40 minutes, depending on parallelization of the builds). All in all, you can wait for hours for a build, that's quite a long feedback loop, especially for pull requests!

Moreover, Travis used to provide unlimited builds for open source project, but this has changed earlier this month and projects now only have 1000 build minutes per month: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

With 40 minutes per build, that's only 25 builds per month. With a minimum of 2 builds per pull request (one for the pull request, then one for the branch once the pull request is merged), that limits you to only 12 pull requests per month before you consume the 10000 free credits from Travis.

Analyzing what makes a build take that long, the longest submodules are:
 * ui with around 1:30 build time, mostly spent in tests
 * widgetset with around 2:15 build time, mostly spent in actually building the widgetset with the vaadin-maven-plugin.
 * backend with around 12:00 build time, mostly spent in tests

Ideas for improving the status quo:
* move off Travis to another provider with more allocated build time, and hopefully shorter build queues. GitHub Actions is entirely free for public repositories (and offers 2000 free build minutes for private repos), and Circle CI gives 400000 credits to open source projects, which amounts to 40000 build minutes per month!
* shorten the feedback loop for pull requests:
  * make the build fail faster, for example by splitting short and long tests (Maven has built-in `test` and `integration-test` phases specifically for that usecase: https://maven.apache.org/ref/3.6.3/maven-core/lifecycles.html). Actually, I'm not even sure there are "fast" tests in SORMAS, due to most tests setting up an EJB environment and H2 database; I'm rather new to the codebase though, so I might very well be wrong.
  * possibly avoid some long-running tasks that are known to be time-consuming (e.g. `vaadin:compile` if there's no change in the widgetset submodule; and/or backend tests if there's no change in the backend or api submodules). This requires caching the results from the previous build (ideally, the build for the base commit common to the PR branch and target branch) and/or migrating off Maven towards a build tool with built-in incremental build support (e.g. Gradle).
  * to save some build minutes, maybe split the build in two: a fast build for fast feedback loop for "obvious" mistakes (compile, check formatting –this is another subject of improvement–, run fast tests), and a second build for longer tasks, that could be triggered only after a first code review (e.g. adding a label or approving the PR, or mentioning a GitHub bot in a PR comment)

**EDIT(2020-12-09):** updated GitHub Actions pricing, it's actually entirely free for public repositories.

**Comment by JonasCir** [comment]
Any personal experience/comments @MichaelSp ? :)

**Comment by MichaelSp** [comment]
Yes, indeed. @tbroyer very nice write up. Slow builds and slow CI/PR turnaround time is painful. 

Gradle: I'd like to have some commitment from core dev-team before diving into a new build-system like gradle. That's to much work to just be neglected.

The best approach is to split into `unit-test` and `integration-test` like suggested and maybe split even the long-running into a few batches to run them in parallel, if that's possible with the CI-system.

I have no experience with circle-ci. Seems to have the best free-plan. But given the importance of this project, there should be money available for a proper CI system if the free plan is not sufficient.

Relevant in this context: #3543

**Comment by MartinWahnschaffeSymeda** [comment]
Hi. Thanks a lot for the input and suggestions!

Moving to gradle is not an option at this point. Too much of the infrastructure (the CI on github is just one part of it) currently relies on it to quickly replace it. It would make sense to collect information on what exactly would have to be done, though, so we can decide on pros and cons and if it's pro, have a migration path.

Splitting the tests doesn't make a lot of sense, since almost all backend tests are "slow" tests anyway. What should be done there is to investigate on how to speed up the backend testing. testcontainers is one relevant buzzword here.

For now we will move to circle-ci and limit this to the part where it is actually needed, the pull requests: #3571

**Comment by StefanKock** [comment]
> Splitting the tests doesn't make a lot of sense, since almost all backend tests are "slow" tests anyway.

More relevant is that we are using this as a quality gate so all tests have to run successful.

**Comment by MichaelSp** [comment]
My thought-process was to split the tests into batches, not to skip them, but to execute all of them in parallel batches.

**Comment by Seal33** [comment]
If I understand [this ](https://github.com/pricing) correctly, GitHub Actions are entirely free (read: unlimited build minutes) for public repositories.

See also [here](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions).

**Comment by tbroyer** [comment]
Thanks @Seal33, I indeed missed that information, which is great news; I updated my original write-up.

**Comment by Seal33** [comment]
@tbroyer Yes and thank you!

We've just opened a PR implementing GitHub Actions in addition to Travis, to try out if they are suited for this Project (which I think they are) #3732

**Comment by JonasCir** [comment]
we moved to GitHub actions and I think this can be closed @DavidBaldsiefen ?

**Comment by DavidBaldsiefen** [comment]
I think we can consider builds for pull-requests optimized :D
