### ISSUE TITLE
Changes made in the bulk mode to facility  are not saved

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3551]
### Steps to Reproduce
1. Enter bulk edit mode while logged in as Admin
2. Select One case
3. Select bulk action "edit"
4. Select "change facility"
5. Select place of stay and chooses some options
6. Log in with Nat User and open the same case
7. Check if the changes to Facility /Place of stay have been saved.

### Expected Behavior
The new Place of stay should reflect on the case that was edited. 

### System Details
* Device: Windows PC
* SORMAS version: SORMAS Version: 1.52.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: admin/ natuser

### Additional Information
this is maybe linked to #3505

**Comment by MateStrysewske** [comment]
I actually get an error message when trying to do that.

**Comment by MateStrysewske** [comment]
Fixed in #2949
