### ISSUE TITLE
Introduce feature type "TASK" to allow disabling of tasks in SORMAS [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3552]
### Problem Description
For some use cases (e.g. SORMAS for APMS in Afghanistan) tasks are confusing users and should not be usable by them.

### Proposed Change
- [x] add feature type TASK
- [x] Disable Tasks view and all task components (in case, contact, event) based on the feature
- [x] Make sure that no tasks are generated at all

- [x] Task Generation/notification features depend on the enabling/disabling

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT
