### ISSUE TITLE
Cannot filter countries by name

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3554]
### Bug Description
Filtering by country name does not work in the countries tab.

### Steps to Reproduce
1. Open the configuration directory
2. Open the countries tab
3. Write the name of a country in the search field and press enter

### Expected Behavior
The country with the given name is found

### Actual behavior
No result is found

### Additional Information
Filtering works only by ISO or UNO code.

**Comment by MateStrysewske** [comment]
Should be handled in #2993

**Comment by vlad-ciucescu** [comment]
Will actually not be handled in #2993 since this will be a little more complicated to fix.

**Comment by DavidBaldsiefen** [comment]
Will be handled with #6091 (PR #6114 )
