### ISSUE TITLE
database export should include Sormas user IDs

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#3557]
When using the Export feature on the Sormas GUI, I have realised that the generated output contains the IDs of entries in the database tables (obviously). 
However these are meaningless for the end user. In the case where someone exports TASKs, he also wants to know who the assigned user is. However, there is only the database ID of the assigned user. Moreover, the users table gets not exported. 

In the end, using the export tool it is not possible to find out the assigned user of a task.

**Comment by bernardsilenou** [comment]
@RafaelKluender Thanks for raising this point, we will raise the priority level and possibly add it in the next 2 sprints. It is similar to #1460.
I will link both issues and close this one.
