### ISSUE TITLE
Add a detailled export in actions view with event description

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3563]
### Situation Description

The actions view in the event directory only has a basic export.

### Feature Description

We wish to create a detailled export that includes the event description (this value will not be added as a column in the view).

@bernardsilenou @carolinverset

**Comment by AndyBakcsy-she** [comment]
verified issue on local environment on SORMAS Version: 1.54.0-SNAPSHOT
