### ISSUE TITLE
Add task types to contacts [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3568]
### Feature Description
Task types for respective entities (e.g. contacts, cases, events)
### Problem Description
Currently, there are less task types available when creating tasks associated to contacts than to cases.
### Proposed Change
To have task types more in line with the ones that already exist for cases, the following task types should be added when creating tasks associated to contacts:
- quarantine management (for cases and contacts)
- send quarantine order (for cases and contacts)
- contact management
- source case tracing
- sample collection
### Additional Information
<img width="394" alt="Screen Shot 2020-11-24 at 11 45 59 AM" src="https://user-images.githubusercontent.com/70317594/100084188-be4b5e00-2e4a-11eb-9a0f-0809a894c4ff.png">

This could go hand in hand with adding #3103 (applicable for contacts and cases)

**Comment by kwa20** [comment]
@JonasCir Would you agree that #3103  could be part of this issue?

**Comment by bernardsilenou** [comment]
> @JonasCir Would you agree that #3103 could be part of this issue?

* I think #3103 can be merged with this one
* I will not name the task type as "put contact under quarantine" or "send quarantine order" because it is a specific situation of the quarantine options (put is quarantine, removed from quarantine, etc). Can we call it something like "Quarantine management"? free test will then explain what to do.

**Comment by kwa20** [comment]
@bernardsilenou Would be fine by me. We might however need two strings for cases and contacts since they would need to be translated differently in some languages.

**Comment by Marko-ilmkreis** [comment]
As a local Health Authority we would agree that we need a task for "sending Quarantine order" for cases and contacts. In our office we have a special team which is printing and sending this orders and therefore it would be good to have that kind of tasks.

**Comment by JonasCir** [comment]
@Marko-ilmkreis Thanks for the insight, very useful! In case you have further insights into the process and how SORMAS could help you to speed things up, please leave a comment in #3103
@kwa20 Yes I also think #3103 has to be included here, however, I want to keep it open as separate ticket to track the progress there

**Comment by kwa20** [comment]
@JonasCir Yes, I referenced the issue in this one for it to be implemented simultaneously.

**Comment by kwa20** [comment]
Also include #3842 with the implementation of this issue.

**Comment by MateStrysewske** [comment]
@kwa20 #3842 is an issue that is unrelated to this one and should be done separately.

**Comment by kwa20** [comment]
@MateStrysewske that's ok. Do you know how the customizable enum issue influences the task types? Will these then be default values?

**Comment by MateStrysewske** [comment]
@kwa20 Right now they won't influence them, but I would like to discuss this further in #3880 because that's about adding a task type configuration - and I hope there's a way to integrate this with the new customizable enums.

**Comment by DavidBaldsiefen** [comment]
@kwa20 
Does `contact managment` in this case mean an entirely new task type, or is it enough to just add `contact tracing` as task type to contacts, which already exists for cases?

**Comment by kwa20** [comment]
@DavidBaldsiefen contact tracing rather describes the tracing of contacts to the existing cases. Contact management describes the management of the contacts that either exist or have been traced. This could mean to take some form of measure to handle contact persons in some way.

**Comment by VGitVlad** [comment]
Validated ticket on Sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment

**Comment by kwa20** [comment]
@DavidBaldsiefen Do you know if there is a delay of translations appearing in crowdin? I saw that the values are already present on nightly build servers but did not find strings to translate yet.

**Comment by DavidBaldsiefen** [comment]
> @DavidBaldsiefen Do you know if there is a delay of translations appearing in crowdin? I saw that the values are already present on nightly build servers but did not find strings to translate yet.

I am not really familiar with that process, sorry. Maybe @fhauptmann knows more?
