### ISSUE TITLE
Switch from travis-ci to circle-ci and limit builds to pull requests

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3571]
### Problem Description
As described by @tbroyer in #3541 

### Proposed Change
Move from travis-ci to circle-ci.

- [ ] Ask HZI (@fhauptmann) to create an account on circle-ci for an open source project which should come with 400.000 credits per month
- [ ] Setup automatic builds for pull requests. No longer use this for every commit
- [ ] Only build on java 11

- [ ] Switch to circle-ci

**Comment by markusmann-vg** [comment]
I will take care of the 1st point

**Comment by vidi42** [comment]
Obsolete due to #3730
