### ISSUE TITLE
Only show facility and POE configuration views when needed based on other active features [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3572]
### Feature Description
Currently the configuration views for facilities and POE are always shown, even when all features that make use of the are disabled.

### Problem Description
The views are confusing to users of the campaign system in APMS.

### Proposed Change
- [x] only show facilities configuration view when CASE_SURVEILANCE or EVENT_SURVEILLANCE or aggregated reporting is enabled (CONTACT_TRACING and SAMPLES_LAB require CASE_SURVEILLANCE anyway)
- [x] only show POE configuration view when CASE_SURVEILANCE  is enabled.

Extension:

- [x] same for Countries
- [x] same for line listing
- [x] same for Statistics

**Comment by AndyBakcsy-she** [comment]
Verified ticket on SORMAS Version: 1.53.0-SNAPSHOT
