### ISSUE TITLE
Prevent Blind SQL Injection [3]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#3578]
### Description
Using the https://pen1.sormas-oegd.de:443/sormas-rest/cases/push REST endpoint to create a case
with an invalid UUID allows to make a SQL injection in the function 

```
de.symeda.sormas.backend.contact.ContactFacadeEjb.getNonSourceCaseCountForDashboard

public int getNonSourceCaseCountForDashboard(List<String> caseUuids) {

		if (CollectionUtils.isEmpty(caseUuids)) {
			// Avoid empty IN clause
			return 0;
		}

		Query query = em.createNativeQuery(
			String.format(
				"SELECT DISTINCT count(case1_.id) FROM contact AS contact0_ LEFT OUTER JOIN cases AS case1_ ON (contact0_.%s_id = case1_.id) WHERE case1_.%s IN (%s)",
				Contact.RESULTING_CASE.toLowerCase(),
				Case.UUID,
				QueryHelper.concatStrings(caseUuids)));

		BigInteger count = (BigInteger) query.getSingleResult();
		return count.intValue();
}
```

### Steps to Reproduce
1. Using the following request, a case is created with an invalid UUID:
**Request**
```
POST /sormas-rest/cases/push HTTP/1.1
Host: pen1.sormas-oegd.de
Connection: close
Authorization: Basic U3Vydk9mZjpTdXJ2T2Zm
Content-Type: application/json
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/86.0.4240.111 Safari/537.36
Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;
q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,de;q=0.8
Content-Length: 2861
[
ERNW Enno Rey Netzwerke GmbH Tel. +49 – 6221 – 48 03 90 Page 35
Carl-Bosch-Str. 4 Fax +49 – 6221 – 41 90 08
69115 Heidelberg VAT-ID DE813376919
BIC: GENODE61WNM IBAN: DE40670923000033145934
 {
 "creationDate": 1603797391019,
 "changeDate": 1603797391019,
 "uuid": "'><img src onerror='alert(1);",
[…]
```
**Response**
```
HTTP/1.1 200 OK
[…]
["OK"]
```

2. After navigating in the UI to the contacts supervisors’ dashboard, an error will be reported to the user as
shown in the below screenshot. The error seems to be resulted from the SQL error occurred by injecting the
invalid UUID.

![image](https://user-images.githubusercontent.com/3462897/100203205-f74b0780-2f0a-11eb-93c5-e99ad2538054.png)

### Expected Behavior
The Injected SQL is escaped and doesn't get interpreted.

### Proposed solution
- [ ] Avoid sql injection by rewriting it to parameter(s) and use batching to avoid parameter overflow (_IterableHelper.executeBatched_)
- [ ] Check that there is no html injection for UUID in the UI

### System Details
* SORMAS version: 1.48.2
* Server URL:  https://pen1.sormas-oegd.de:443
* User Role: Contact Supervisor

**Comment by markusmann-vg** [comment]
All user-supplied data must be checked and validated, so that no SQL code is included into database
commands. Proper input validation via Regular Expressions can help to mitigate this attack vector. Therefore,
a list of allowed characters should be defined. This list should not include any characters that are handled in a
special way by the database.
Additionally, prepared statements can be used to create SQL queries that are not vulnerable to SQL Injection.
Any kind of string concatenation must be avoided, instead parameterized queries must be constructed.
Further information can be found at:
o https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html
