### ISSUE TITLE
Contacts > Contacts without "Responsible Region" and "Responsible District" are not visible in the Contact Directory Default View

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3583]
### Bug Description
After implementation of https://github.com/hzi-braunschweig/SORMAS-Project/issues/2137, Contacts without "Responsible Region" and "Responsible District" are not shown in the Contact Directory Default View anymore.

This results in massive amounts of Contacts not being visible to contact tracers unless they use these workarounds:
1. Adjust all user roles to include the National User role right (not ideal as additional data can then be seen).
2. As a National User, everytime the Contacts Directory is opened, the contact tracers have to add the filter "Show Contacts outside this jurisdiction" (not ideal as not all are aware of this and where to find it).

Mass editing of Contacts can't be done to adjust the region/district etc. yet.  Would each Contact have to be updated by hand to include this information?

Are there other solutions to this, please?

Thousands of contacts are 'disappearing' from the contact tracers' view and they are starting to produce double entries to 'fix' this which results in bad data quality and inefficient operation (Kt. Bern @rafaelpaffenholz ).

### Steps to Reproduce
1. Contacts > New Contact (Responsible Region and Responsible District are compulsory - expected)
![image](https://user-images.githubusercontent.com/65529128/100212876-2ca52480-2f0e-11eb-87c3-5cdb1a5f41a5.png)

2. Choose Source Case to link to Contact > Confirm (Responsible Region and Responsible District are NOT compulsory anymore - not expected?)
![image](https://user-images.githubusercontent.com/65529128/100212982-51999780-2f0e-11eb-91c9-ae7d3485c153.png)

3. Remove Case > (Responsible Region and Responsible District are compulsory - expected)
![image](https://user-images.githubusercontent.com/65529128/100213056-742bb080-2f0e-11eb-9a11-f004e3451e72.png)

4. When a Contact is saved with a source Case, the Responsible Region and Responsible District are not recorded.  The "null" values which are allowed for Contacts for these fields are not taken into consideration during the display in the list.

### Expected Behavior
+ Contact Tracers should be able to view all Contacts - even those with a null value - without user role adjustment.
+ Responsible Region and Responsible District should be made compulsory (could affect prior data negatively)
+ Make this feature configurable (?)
+ Alternatively, a bulk edit mode should be available for Contacts to assign a Responsible Region and/or District.

### System Details
* Device: Web
* SORMAS version: 1.51.1+
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/ and https://test.sormas.ch/
* User Role: Kontaktleitung specifically, but likely applicable to all roles that are assigned a jurisdiction.

### Additional Information
Please provide another workaround or best solution proposal as this is negatively influencing Contact tracing operations in real-time, on large scale.

**Comment by bernardsilenou** [comment]
@Candice-Louw 
- I did a test and realized that the users need to check activate the box "include contacts from other regions" to see the contacts as temporal situation.
- It will not be good to make the jurisdiction a required field fro contacts associated to cases.

**Comment by bernardsilenou** [comment]
We can use a similar logic as for event participants jurisdiction because this is technically the same thing.
replace event with cases and event participant with contact as explained in #2902.

If a contact is linked to a case and has no jurisdiction assigned that is different from that of the case, then the contact should not be considered as external to all users in the jurisdiction of the case.

**Comment by kwa20** [comment]
@bernardsilenou @Candice-Louw @MateStrysewske What if we would automatically adopt the region and district of the source case if one has been chosen? This could still be changed when applicable but it might be true for the majority of contacts. Then these contacts would at least be shown by default for users in the jurisdiction without having to filter for contacts outside of their jurisdiction.

**Comment by MateStrysewske** [comment]
@Candice-Louw @bernardsilenou @kwa20 We'll temporarily disable this new logic for the upcoming release because fixing it requires a bit more work and a rewrite of some backend logic. We'll go with the approach outlined by @kwa20, but it's not trivial to do this change.

#3591 is the issue about this temporary change, and we'll take care of this issue here in the next sprint.

**Comment by bernardsilenou** [comment]
> @bernardsilenou @Candice-Louw @MateStrysewske What if we would automatically adopt the region and district of the source case if one has been chosen? This could still be changed when applicable but it might be true for the majority of contacts. Then these contacts would at least be shown by default for users in the jurisdiction without having to filter for contacts outside of their jurisdiction.

I just want to emphasizes that this solution will be in relation to user right ie who has full assess to the contact, but not assigning the jurisdiction of the case to the contact in the db. 
We then keep the responsible jurisdiction as NA if not registered.

**Comment by bernardsilenou** [comment]
@kwa20 I hope this is what you meant also?

**Comment by sergiupacurariu** [comment]
@Candice-Louw @bernardsilenou @kwa20 

-after I discussed with Mate I added here the logic that will be implemented:
Logic to be implemented (show contacts in the grid when)
--
- Include contacts from other jurisdiction checkbox is **OFF**
-- contacts from the same jurisdiction with user's
-- contacts created by other users; no responsible jurisdiction; linked to a case from user jurisdiction
 
 
- Include contacts from other jurisdiction checkbox is **ON**. Add besides above
-- contacts created by the user, no matter the jurisdiction
-- contacts created by other users; no responsible jurisdiction; linked to a case created by user

**Comment by bernardsilenou** [comment]
Some users will have pseudonymize personal data while users like reporting user will have read only when Include contacts from other jurisdiction checkbox is ON, right?

**Comment by AndyBakcsy-she** [comment]
Validated this issue on SORMAS Version: 1.54.0-SNAPSHOT based on Sergiu's comment. 
All 4 scenarios have been validated.
