### ISSUE TITLE
"Email/phone already in use" when accessing Climedo eDiary from SORMAS

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3599]
### Bug Description
Clicking the "Climedo eDiary" button for a person registered in Climedo shows an error that their email/phone is already in use.
### Steps to Reproduce
1. Go to the contacts directory
2. Open a contact with a person registered in Climedo
3. Click the "Climedo eDiary" button

### Expected Behavior
A new tab opens, showing the Climedo page for that person.

### Actual Behavior
An error message appears in SORMAS that the email/phone of the person is already in use

### Screenshots
https://www.loom.com/share/002ab54da1834cc9aac9cd2a5a9fa55b

### System Details
* Server URL: ga1.sormas-oegd.de
* User: NatUser

**Comment by AndyBakcsy-she** [comment]
Verified the ticket on SORMAS Version: 1.52.0-SNAPSHOT on ga1.sormas-oegd.de
