### ISSUE TITLE
"Session expired" when accessing Climedo eDiary from SORMAS

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3600]
### Bug Description
Clicking the "Climedo eDiary" button for a person registered in Climedo opens the Climedo page, but immediately afterwards a login popup appears.
### Steps to Reproduce
1. Go to the contacts directory
2. Open a contact with a person registered in Climedo
3. Click the "Climedo eDiary" button

### Expected Behavior
A new tab opens, showing the Climedo page for that person.

### Actual Behavior
A new tab opens, showing a login popup for Climedo

### Screenshots
![image](https://user-images.githubusercontent.com/65336966/100366783-f4830c00-3009-11eb-880c-f1ee39ac88e8.png)

### System Details
* Server URL: ga1.sormas-oegd.de
* User: NatUser

**Comment by vlad-ciucescu** [comment]
Authentication seems to be done correctly on SORMAS side, waiting for an answer from Climedo if there is a problem on their side.

**Comment by FredrikSchaeferVitagroup** [comment]
The climedo developers reported this issue to be resolved from their side.

**Comment by AndyBakcsy-she** [comment]
Verified issue on  SORMAS Version: 1.53.0-SNAPSHOT
