### ISSUE TITLE
Migrate users from SORMAS Authentication to Keycloak automatically [3]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#3602]
### Situation Description
At the moment the SORMAS system supports enabling authentication trough Keycloak (#2745) , however this is mostly designed to be done for new systems, where there are no active users. 

An automated migration already exists for default users like admin, NatUser, etc which activates them in Keycloak at server startup with their default credentials.

However for non-default (external users) there is not automated mechanism, only a manual one:
1. An admin logs into the SORMAS Web app
2. Goes trough each user which it wants to migrate and fills their email address and saves them
3. The users will receive an email to activate their account and setup a new password

Since already running systems might have multiple users, an automated process is needed to fulfil this tasks.

### Feature Description
An automated script which can import all existing SORMAS users into Keycloak and allow them to access their account trough it.

#### Restrictions
Since the passwords in SORMAS are hashed they cannot be imported into Keycloak, so the users will have to setup new passwords.
If the users don't have an email address they will not be able to receive an email notification to setup their accounts.

### Possible Alternatives
1. Keep the manual approach

2. An automated startup script which goes trough all existing users and imports them into Keycloak with a random password.
Advantages: users which have an email address will receive an email to activate their account and setup a password
Disadvantages: users which don't have an email address still have to be manually filled by an admin with an email address

3. External script which can be run at any time by a DevOps person to activate users with a predefined password and provide users with the possibility to change their email address once logged in.
Advantages: Password can be communicated to the users and they don't need to have an email address setup upfront
Disadvantages: The passwords have to be communicated to each user otherwise individually, otherwise risk having users guessing passwords for other users

### Additional Information
Manual approach will be available for any of the alternatives.

**Comment by vidi42** [comment]
In scope of this story
- [ ] Add UI field for users to change their email in settings panel (bellow language) - only when Keycloak is active as Authentication Provider
- [ ] Create scripts for migrating users into Keycloak

**Comment by markusmann-vg** [comment]
@vidi42 Please provide a documentation how it's done and how it is possible to import encrypted passwords

**Comment by JonasCir** [comment]
Heads up @vidi42 : There is also https://github.com/hzi-braunschweig/SORMAS-Project/pull/3837 about to land which fixes security issues

**Comment by vidi42** [comment]
@JonasCir Thanks for the heads up.
We already have this in plan for the Next Sprint with #3766

**Comment by AndyBakcsy-she** [comment]
Validated the issue on SORMAS Version: 1.54.0-SNAPSHOT using test-de2.sormas.netzlink.com environment and the keycloak admin console.
Created multiple users on sormas side and verified if the users are displayed in keycloak console. 
Edited these users and checked if the changes are visible after syncronisation
