### ISSUE TITLE
Contact directory quarantine filter shows more values than expected

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3603]
### Feature Description
Quarantine contact directory filter
### Problem Description
The quarantine filter in the contact directory displays more values than what can be selected in the contact information. These are likely values that were introduced for the Swiss systems.
### Proposed Change
Only show values that can actually be selected in the contact information since values in the filter will only produce empty directories.
### Additional Information
<img width="371" alt="quarantine" src="https://user-images.githubusercontent.com/70317594/100389358-7b95ab80-302d-11eb-83f0-94983c325580.PNG">
<img width="266" alt="quarantine2" src="https://user-images.githubusercontent.com/70317594/100389363-7d5f6f00-302d-11eb-9041-c33795b6e6f8.PNG">

version: 1.51.1
server: test1401.sormas-oegd.de

**Comment by kwa20** [comment]
@Candice-Louw can you verify that these are Switzerland specific values?

**Comment by Candice-Louw** [comment]
@kwa20 - Can confirm as Swiss values, yes: https://github.com/hzi-braunschweig/SORMAS-Project/issues/2978 (pt.2 at the bottom https://github.com/hzi-braunschweig/SORMAS-Project/issues/2978#issuecomment-707635413)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT on local environment
