### ISSUE TITLE
Error when opening cases/contacts/events with tasks without a task status

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3609]
### Bug Description
Some cases on productive systems don't show the right bar that dislayes functionalities like tasks, samples, events, documents. Navigating back to the case information produces an error message.
### Steps to Reproduce
1. Open a case where this information is not visible (still not sure how to determine/reproduce this)
2. Navigate to any other tab of the case (i.e. Case Person)
3. Navigate back to the tab for the Case
4. Error message appears

### Expected Behavior
The right task bar should always be shown (excluding Documents because of dependencies)
### Screenshots

![Screenshot 2020-11-26 090014](https://user-images.githubusercontent.com/70317594/100441231-6d37a600-30a6-11eb-8d1f-9c38ebe5ed42.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser: 
* Server URL: productive systems
* User Role: admin, national user, supervisors, lab officer, clinician

**Comment by Candice-Louw** [comment]
@MateStrysewske -
[server.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5607777/server.txt)

Error occurred at 11.05 when accessing a Case on this server.
Error occurred at 11.06 when accessing a Case on this server.

**Comment by MateStrysewske** [comment]
@kwa20 @Candice-Louw Unfortunately, for some reason, there's no proper logging for this bug which makes it really hard for me to investigate it. Can you have a look at the affected cases and try to figure out what is different about them compared to cases where it works?

**Comment by Candice-Louw** [comment]
@MateStrysewske - From Kt. BE: Data Processing teams claim that in all these cases it seems that a first task could be set on import (all of these cases are imported, then tasks are set by contact tracers by hand), because otherwise they would never have been processed by a Contact Tracer, but that the error might have occurred later (e.g. when completing a task).

**Comment by MateStrysewske** [comment]
@Candice-Louw I'm not sure if I understand correctly. Does that mean that after the case was imported, the sidebar was displayed and the users could successfully create a task for it, and the error only occurred later? If that's the case, unfortunately that's not really an answer to my question because I'd need to know what the difference compared to other cases is right now (not earlier).

**Comment by Candice-Louw** [comment]
@MateStrysewske - additional information (which may not be particularly helpful, but posting it anyway):
Cases > Open Case with missing right bar (no error shown) > Refresh page > Error shown and GDPR message pops up (if not already accepted by user).

![image](https://user-images.githubusercontent.com/65529128/101337460-ffe0fd80-387b-11eb-8544-475a8d4de7c4.png)

**Comment by MateStrysewske** [comment]
@Candice-Louw Does that mean that the user in question didn't receive this popup directly after they logged in?

**Comment by Candice-Louw** [comment]
@MateStrysewske - User did receive the message when logging in.  They only closed the window (x in the corner).  So, they did not select "Ich habe diese Informa..." nor did they click "Bestätigen".

**Comment by Candice-Louw** [comment]
@MateStrysewske - confirmed:
It is possible to set Tasks with no task status.  For all Cases where the Task status is missing (filter in Task directory by Task status) the right bar is not shown.

![image](https://user-images.githubusercontent.com/65529128/101340342-e2ae2e00-387f-11eb-87c9-a5c93cecbb69.png)

![image](https://user-images.githubusercontent.com/65529128/101340270-c6aa8c80-387f-11eb-901e-fe6b22bf77ff.png)

Temp workaround suggested Kt.e - filter by task status and handle these cases as a special group for follow-up calls.

**Comment by MateStrysewske** [comment]
@Candice-Louw Great, thanks! That's the issue! I suggest that we make the task status required so that this doesn't happen again?

**Comment by kwa20** [comment]
@MateStrysewske @Candice-Louw I just reproduced it! Great effort finding it! Yes, let's make it required.
![rightBarBug](https://user-images.githubusercontent.com/70317594/101341835-f78bc100-3881-11eb-9940-2fb5bfd824a9.JPG)

**Comment by raghupola-vg** [comment]
All tasks status are now marked as mandatory and the issue is now resolved

**Comment by StefanKock** [comment]
Workaround for missing Task.status: Go into the Task and set a status.
