### ISSUE TITLE
Export BAG (contacts & cases) should be triggered automatically [3]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3610]
### Situation Description
Currently the export for Switzerland is triggered manually.

### Feature Description

- [ ] Create BAG user role who is allowed to access the Rest-API
- [ ] Create Rest-Endpoint for the full export 
- [ ] Result should be the csv in response 
- [ ] Consider memory and performance (Delete cache / local storage)

**Remark:**
We keep the manual export

**Comment by leventegal-she** [comment]
From now on BAG export is available only for users with `BAG User` role.

Introduced rest endpoints for export:
1. `sormas-rest/bagexport/cases`
2. `sormas-rest/bagexport/contacts`
