### ISSUE TITLE
Cases and Contacts > "External ID" Filter & External Token [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3613]
### Situation Description
As a contact tracer that gets labs results from an external system, I record this ID in the External ID field in SORMAS, and would also like to be able to filter/search for this External ID & External Token

![image](https://user-images.githubusercontent.com/65529128/100456476-b563c200-30c0-11eb-8c87-5da8fecda3d4.png)

### Feature Description
Include a filter/search functionality for the External ID & External Token on the Case directory.  It could be included in one of the existing filter search boxes, or created seperately (as this is a locale-dependent field/variable (DE & CH), this may influence the decision).

### Additional Information
This ID is visible on both the Cases and Contacts directory.  The main request is to include this filter on the Case directory first (as priority), please.  If possible, also include this on the Contacts directory.  If not, a seperate Issue will be created for this.

**Comment by maxiheyner** [comment]
@markusmann-vg ; @StefanKock ; @Candice-Louw is it possible to make this filter available on all other directories (samples and events), too? This was asked for several times, the last days...

**Comment by Candice-Louw** [comment]
@maxiheyner - this would have to be a separate Issue, please. :)

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT using test-de.sormas.netzlink.com environment.
Using the "Id, name,case ID,.. " filter box and searchinf for External ID's and External Tokens, works on the Cases and Contacts page

**Comment by bernardsilenou** [comment]
Please can we also activate external id and external token for all instances? 
It is missing on the international server https://release-international.sormas.netzlink.com/sormas-ui/
If there a configuration that has not been activated?
