### ISSUE TITLE
Link Facility Category and Facility Type to the Type of Place field

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3617]
### Feature Description

In the Event screen, the **Type of Place** field allows to select several types including _Facility_.

Later on this screen, two fields, **Facility Category** and **Facility Type**, are available and linked (the category determine the options proposed by the facility type list).

### Problem Description

You can select any **Type of place** (for instance _Means of Transport_) and still select a **Facility Category** and a **Facility Type** (for instance _Care facility_ + _Holiday Camp_)

A second problem is that the **Type of place** contains an _Hospital_ option, which is a **Facility type** (**Category** _Medical Facility_).

### Proposed Change

1. The **Type of place** should be placed under the **Region**/**District**/... line to show that it is now linked to the **Facility Category** and **Facility Type** fields.

![move](https://user-images.githubusercontent.com/15834125/100461337-f65fd480-30c8-11eb-8610-c9f3176e88f8.png)

2. The **Facility Category** and **Facility Type** fields should be disabled if the selected **Type of place** is not _Facility_.

3. The data already present in the database should be modified as follow (migration included in the development of this issue) :

- if the **Type of place** is _Hospital_ and **Facility Category/Facility Type** are blank : the **Type of place** is changed to _Facility_, the **Facility category** is set to _Medical Facility_ and the **Facility type** is set to _Hospital_
- else if there is a **Facility category** and a **Facility type** selected : no change for them but the **Type of place** is set to _Facility_ (we suppose that the good information is the detailled one, that is the one in **Facility Type/Facility Category**)
- else : no change

4. The Event Directory filters are completed with filters on the **Facility Category**, **Facility Type** and **Facility** if the **Type of Place** filter is set to _Facility_

@carolinverset @bernardsilenou

**Comment by kwa20** [comment]
I agree that having hospital in two places does not make a lot of sense. If we remove hospital from the type of place, we should keep the filters on the event directory in mind. I suggest to add facility related filters to the event directory to account for that change.

<img width="506" alt="eventDirectoryFilters" src="https://user-images.githubusercontent.com/70317594/100486765-af440480-3105-11eb-9a0a-9d2b11602902.PNG">

**Comment by bernardsilenou** [comment]
This issue is a variant of #3190 and #3536. We may need to merge 3 of them to have a final refinement.
@ftavin I also agree with your comments.
@kwa20 We do not have these filters for case directories and others, Would it not be better create a new issue for this for all the directories?

**Comment by bernardsilenou** [comment]
- Options for type of place: 
* facility
* home
* means of transport 
* other + free text
* unknown
- if type of place == facility
  * show and give write options for facility category, type, etc
@MateStrysewske ???

**Comment by kwa20** [comment]
@bernardsilenou we do have such filters in the case directory. For contacts, such filters are not applicable since we don't enter facilities in the contact information. The only spot where facilities occur now is in the reworked epi data. The exposure entered in the contact however will become a lot more interesting when that contact is converted into a case.
<img width="854" alt="facilityFilters" src="https://user-images.githubusercontent.com/70317594/100525127-4a98b080-31be-11eb-97f1-92c2d5f59cad.PNG">

**Comment by bernardsilenou** [comment]
@kwa20 Thanks for that, I forgot they only show when a jurisdiction is chosen. Of course, we need to add the filters. It @ftavin  to decide if we do it in this ticket or in another

**Comment by ftavin** [comment]
@bernardsilenou I would suggest to close the 2 bug issues with a comment that gives the link to this one.

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset

I added the filters on event directory to the initial description.

@alexandre-gille is starting working on this issue in order to have it on 1.53 so we shouldn't change it anymore if possible

**Comment by bernardsilenou** [comment]
@MateStrysewske Is this specification ok by you also?

**Comment by MateStrysewske** [comment]
I completely agree with the specifications, yes. HOSPITAL should be removed as a type of place because it's redundant, all other types of place should stay (saying that explicitely because Bernard forgot FESTIVITIES in his list).

**Comment by ftavin** [comment]
thank you @MateStrysewske for your feedback !

**Comment by MateStrysewske** [comment]
#3680 needs to be done after this issue has been resolved.

**Comment by ftavin** [comment]
@MateStrysewske help !

@alexandre-gille is having a hard time with this issue : in the original conception, the type of place field is not part of the "Location" form.

if we want to move type of place between the region/disctrict/... line and the facility category/type/... line, we need to add it to the Location form which is used on multiple screens... (not counting that the type of place data is in the event table and the rest is on the location one)

what would you suggest ?

note : there will be the same problem for issue #3680

**Comment by MateStrysewske** [comment]
I'd remove the requirement to move the type of place field between region/district/... and facility category/type/... then; I don't think it's necessary to achieve what we want to achieve with this issue, and there are some locations that really don't need this field, so I wouldn't want to add it to the location.

**Comment by ftavin** [comment]
thank you for your feedback

@carolinverset @bernardsilenou are you ok with that point ?

**Comment by bernardsilenou** [comment]
I would have been nice to have but i think is not worth the effort. I agree with @MateStrysewske  comment

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 
I'm also agree with this solution. thank you !

**Comment by raghupola-vg** [comment]
Tested on both Web and Mobile.
