### ISSUE TITLE
Details for the Type of place "Means of Transport" in Events

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3618]
### Situation Description

In the Event screen, when you select _Means of Transport_ as the **Type of place** for the event, you can't add details like the type of transport (plane, train, unicorn, ...) or the transport references (flight number, train car, name of the unicorn...).

### Feature Description

The selection of the option _Means of Transport_ as the **Type of place** for an event should allow to detail the **Mean of transport** (list) and some **References** (free text) like for Cases/Epidemiological Data/Exposure (see screen below)

![Capture](https://user-images.githubusercontent.com/15834125/100463609-67ed5200-30cc-11eb-9fa9-67fcbf619ec5.PNG)

Note : there is no use for the **Seat number** field in events (multiple person are involved in an event).

@carolinverset @bernardsilenou

**Comment by bernardsilenou** [comment]
@ftavin  Looks good

**Comment by AndyBakcsy-she** [comment]
Verified issue on the local environment on SORMAS Version: 1.54.0-SNAPSHOT

**Comment by MateStrysewske** [comment]
- [ ] Remove Seat Number from events (just mark the field as deprecated in the Android app, no need to remove the column)
