### ISSUE TITLE
Display username in visit origin [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3621]
### Feature Description
Visit origin column in the case and contact follow-up tabs.
### Problem Description
So far, the visit origin column only differentiates between 'created by user' and 'external journal'. 
### Proposed Change
Instead of just displaying created by user, the username of the user who created the new visit should be displayed. This will help in internal communication between users, especially when there is a lot of staff working on contact/case tracing. Use the `getShortCaption` method of UserReferenceDto to make sure that the role is not included.

### Additional Information
<img width="193" alt="visitOriginUserName" src="https://user-images.githubusercontent.com/70317594/100490047-80835980-3118-11eb-90b8-5659f1ce8761.PNG">

**Comment by Marko-ilmkreis** [comment]
@kwa20 yes, thats what i suggested in #3910. I would appreciate if it would be enabled soon.

**Comment by heineltp** [comment]
Hello, what is the acutal state of this issue ? This feature is also very important for us.

**Comment by kwa20** [comment]
@JaquM @maxiheyner We might want to re-prioritize this issue again since it seems rather simple yet very valuable
