### ISSUE TITLE
Campaigns > Archived Campaign causes Dashboard error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3622]
### Bug Description
When creating a new campaign (with a campaign data form and a campaign data chart defined) and archiving the campaign (as the most recent campaign created), results in an error when navigating back to the Dashboard (no data displayed).

### Steps to Reproduce
1. Campaigns > Campaigns > New Campaign (make use of the ```November 2020 Training Campaign``` on the test server)
2. Set up and complete all data for this Campaign
3. View this in the Dashboard
4. Archive this Campaign
5. View the Dashboard (error message displayed, no data)

6. De-archive the Campaign > error message disappears and data displays on Dashboard again

### Expected Behavior
Dashboard should display data only from the most recent Campaign and its associated data if it is not ```Archived```.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/100521011-4f02a080-31a1-11eb-8d4a-6997f0506fbc.png)

### System Details
* Device: Web/Desktop
* SORMAS version: 1.52.SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!dashboard
* User Role: National Coordinator

**Comment by MateStrysewske** [comment]
We also have similar problems in other places:
* Campaign data overview crashes when there is no active campaign in the system
* Dashboard crashes when there is no active campaign in the system
* Dashboard crashes when last campaign is archived (=> exclude archived campaigns from this logic)
