### ISSUE TITLE
Allow contacts to be converted to cases that already exist [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3623]
### Bug Description
When converting a second contact to a case, duplication recognition gets triggered when a case for the same person does already exist. However, when this case is selected, the second contact does not actually get converted and the contact status remains 'active contact' instead of 'converted to case'
### Steps to Reproduce
1. create a contact and contact person.
2. convert this contact into a new case.
3. create another contact for the same person.
4. convert this new contact to the same case.
5. check status of the newly created and converted contact.

### Expected Behavior
When another contact of the same person has been converted into an existing case, the status should be changed accordingly. Furthermore, the contact information should provide a link to the case the contact was converted to 'Open case of this contact person'.
### Screenshots
<img width="853" alt="contactsConvert" src="https://user-images.githubusercontent.com/70317594/100528420-09fc5f80-31dd-11eb-976b-4af1d24f8d48.PNG">
<img width="841" alt="contactsConvert2" src="https://user-images.githubusercontent.com/70317594/100528421-0c5eb980-31dd-11eb-972b-118c6f0b1fbc.PNG">
<img width="677" alt="contactsConvert3" src="https://user-images.githubusercontent.com/70317594/100528422-0e287d00-31dd-11eb-8186-5481af0e4afb.PNG">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: Firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 This actually is a bigger change because it requires us to rewrite a significant amount of code. I'd like to not include that in the hotfix because it has the potential to break quite a lot of things. Is it okay for you if we do it for the next release?

**Comment by kwa20** [comment]
@MateStrysewske That's a tough decision. The main thing I'm worried about is that with the newly imlemented option to link event participant to contacts, many contacts can be created between event participants where participants became cases. So in a cluster, all the resulting contacts can not be converted to the same case and people might create cases for each of those contacts resulting in many more cases being reported then persons actually being a case at that time.

e.g. in a classroom of 20 students, 3 were confirmed as cases. All the other 17 students then had 3 contacts to these cases respectively. When the other students become cases now, users might end up with 51 instead of 17. Realistically, this might also happen over time, so we'd have 3 x 17 contacts, then 4 x 16 contacts, 5 x 15 contacts, etc.

**Comment by bernardsilenou** [comment]
I hope this will be true only when all the variables for duplicator case detection are satisfied:
same region, district, disease, difference in onset date or report date of less than 30 days

**Comment by MateStrysewske** [comment]
@kwa20 I very well understand that problem; if it's absolutely necessary to have this changed in the hotfix, we have to do it. In theory, the associations could be set retrospectively after the next release, but I understand if that's not a valid option because it would mean too much work for the GAs.

So long story short, we need to put this into the hotfix, right?

**Comment by kwa20** [comment]
@MateStrysewske I would very much appreciate that, especially since the health departments might only get updated to the next release version (1.53) after the holiday period.

**Comment by kwa20** [comment]
@MateStrysewske I tried this in version and it did not work. The following error occurrs:

I created a case through the first contact and tried to convert the second contact (same person).

![FallKonvertierung2](https://user-images.githubusercontent.com/70317594/101761820-e68abc00-3adc-11eb-8bde-4a4ce63818c9.JPG)
![FallKonvertierung](https://user-images.githubusercontent.com/70317594/101761822-e8547f80-3adc-11eb-8541-2920f70ba6d7.JPG)

**Comment by kwa20** [comment]
@MateStrysewske FYI: I just checked this also through the epi data. There it works through duplicate recognition as long as I choose the same source case.

**Comment by kwa20** [comment]
@MateStrysewske I investigated further and the error message occurs, when no responsible region and district is selected for the contact. This is due to these fields not being compulsory, if a source case is chosen.

**Comment by MateStrysewske** [comment]
@kwa20 Thanks for figuring that out!

**Comment by AndyBakcsy-she** [comment]
Validated this issue on the latest version of SORMAS Version: 1.53.0-SNAPSHOT
Created the second contact with the same name as the first. 
Validated the link to open the case as well
