### ISSUE TITLE
Cases converted from contacts have disabled 'contacts with source case known' buttons

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3625]
### Bug Description
when contacts have been converted into cases, the 'contacts to source case known' function is disabled in the epi data tab.
### Steps to Reproduce
1. create a contact.
2. convert that contact into a case.
3. open the epi data tab of that case.
4. check the functionality 'contacts with source cases known'.

### Expected Behavior
Functionality should be enabled to enter as many contacts to source cases as applicable. 

<img width="318" alt="SourceCaseContacts2" src="https://user-images.githubusercontent.com/70317594/100540397-80c94500-323d-11eb-8e70-8fec0d0730dd.PNG">

### Screenshots
<img width="427" alt="ConvertedToCaseEpi2" src="https://user-images.githubusercontent.com/70317594/100540757-a5beb780-323f-11eb-9968-b156fecb95b1.PNG">

<img width="854" alt="ConvertedToCaseEpi" src="https://user-images.githubusercontent.com/70317594/100528991-08ce3100-31e3-11eb-8861-2b9a36df9540.PNG">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
#3623

**Comment by bernardsilenou** [comment]
What do we do in  a situation that the source case in unknown  but the contact is known and became a case? eg, converting a returning traveler contact to a case.
- still set contact with source case known == Yes in epi data and variable related to source case will be set to unknown

**Comment by raghupola-vg** [comment]
Contacts with source case known buttons are still disabled on Epi data tab.
Tested on version 1.53.0-snapshot

**Comment by raghupola-vg** [comment]
Tested on latest deploy on test systems and works fine.
