### ISSUE TITLE
Hide "EPID Number" in forms and grids for DE and CH [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3629]
### Feature Description
As a contact tracer I would like to see and record only information relevant to a specific case based on the configuration of the server SORMAS is running on.

### Problem Description
For DE and CH servers specifically, when creating a new Case (Cases > New Case > Create New Case form), users are requested to enter the ``` EPID NUMBER``` despite this field not being visible/used anywhere else.

DE
![image](https://user-images.githubusercontent.com/65529128/100550395-08cd4000-327a-11eb-8485-1e59c05cf597.png)

CH
![image](https://user-images.githubusercontent.com/65529128/100550379-eaffdb00-3279-11eb-8db6-3311b5809144.png)

### Proposed Change
- Hide/remove this field in the Case create form (as on data form) for DE and CH servers (as well as any other countries where the EPID number is not in use).
- hide it on CasesView, Linelisting and Sample Directory
- Put ```External ID``` on Case Creation form at the place of the EPID number.

### Additional Information
Refinement of: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3526

**Comment by bernardsilenou** [comment]
@Candice-Louw  What about adding a server config parameter fro this?

**Comment by kwa20** [comment]
Also hide in Linelisting and Sample Directory:
![linelistingEpidNumber](https://user-images.githubusercontent.com/70317594/100880542-259d8980-34ad-11eb-97c6-7f8cf12ab314.JPG)
![samplesEpidNumber](https://user-images.githubusercontent.com/70317594/100880409-fab33580-34ac-11eb-8d09-014b604f1475.JPG)

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of SORMAS
Version: 1.55.0-SNAPSHOT on test-de.sormas.netzlink.com
