### ISSUE TITLE
Implement PUT requests to ReST API so items can be updated

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Project#3645]
### Situation Description
Currently the API containts GET and POST methods. It allows to create new entries like persons, cases, contacts, etc. 
### Feature Description
Sometimes other systems have a more complete information on a patient (more info about address, phone numbers, etc.) Those cannot be updated using the API because it has no PUT requests

### Additional Information
1.51.2

**Comment by lebiku** [comment]
@MateStrysewske This is an important requirement for us too. Is there any prediction when this feature is going to be addressed? We have certain process information altered in external systems we cannot automatically update in Sormas, leading to a lot of manual work for our analysts.

**Comment by MateStrysewske** [comment]
@RafaelKluender @lebiku Using the POST method with an entity that already exists on the server will in fact update that entity with the information from the submitted entry. This will also override changes that have been made on the SORMAS system in the meantime, but if you only submit the information that you actually want to be changed, the API is already capable of doing that right now.

**Comment by Candice-Louw** [comment]
@baenik - could you please see if this would be a solution to your request in https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/156 ?

**Comment by baenik** [comment]
@Candice-Louw - Danke, ja die Lösung würde für uns funktionieren.

**Comment by MartinWahnschaffe** [comment]
What still should be done:

Add a description to the generated swagger file. It should explain that:

1. POST is used to do both create and update of entities
2. When new data is posted, it is possible to pass a UUID that can later be used to retrieve and update the data. The description should refer to the existing Java reference code in DataHelper.createUUID and to the existing generate_base32_uuid postgres function.
3. The description should mention that the api was originally created to be used by the SORMAS android app for data synchronization

**Comment by herrling-LRA-KYF** [comment]
is the update via rest working right now? If i post an existing person with his uuid and with a different lastName, i get an error (tested via postman). tested for a single person and for a person referenced in an eventparticipant
{
        "uuid": "6d767696-3ddb-4ffb-a566-baff52fc806e",
        "firstName": "bbb",
        "lastName": "ccc",
        "sex": "MALE"
    }  ==>  "OK"
----------------------------------------------------------------------------
 {
        "uuid": "6d767696-3ddb-4ffb-a566-baff52fc806e",
        "firstName": "aaaa",
        "lastName": "ccc",
        "sex": "MALE"
    } ==> "ERROR"

**Comment by lebiku** [comment]
Post of person (update) has been working for us. However, with the API v 1.58.3 we had to refactor our code a little. Contact detail (Email, Phone) is linked on a ContactDetail List. We had to reflect these changes since v1.57.3. Maybe you have to adjust your Post Json as well.

**Comment by kwa20** [comment]
@herrling-LRA-KYF It looks like you're trying to use a different kind of uuid than what is used in Sormas. They usually look like this (screenshot from database export):

<img width="558" alt="casesDBexportUuid" src="https://user-images.githubusercontent.com/70317594/115687852-df14d280-a35a-11eb-87c6-fc13c7f6e2a2.PNG">

**Comment by herrling-LRA-KYF** [comment]
@kwa20 i generate a uuid v4. in our backend i use https://github.com/thenativeweb/uuidv4#readme.
For testing in postman, i generate it over:  https://www.uuidgenerator.net/version4

Which type of uuid is the right one? Isn't it a uuid v4?

I only have the problem while trying to change data. If i post new data its worked as expected.

**Comment by kwa20** [comment]
@herrling-LRA-KYF Unfortunately I don't know much about this topic myself but I would expect having to reference the exact uuid when changing an existing entry. @MateStrysewske @MartinWahnschaffe You would definitely know better than me.

**Comment by herrling-LRA-KYF** [comment]
@kw20 i use the exact uuid when changing a person. Steps to reproduce via POSTMAN:

:  POST  url:XXX.sormas.bund.de/sormas-rest/persons/push
Body:

[
    {
        "uuid": "bd9544e3-9eed-443b-9276-70333b04b540",
        "firstName": "TESTER",
        "lastName": "Test11",
        "sex": "MALE"
    }
]
-->	Response:
[
    "OK"
]


same POST with following Body:

[
    {
        "uuid": "bd9544e3-9eed-443b-9276-70333b04b540",
        "firstName": "TESTER",
        "lastName": "Neu55",
        "sex": "MALE"
    }
]
-->	Response:
[
    "ERROR"
]

POST with new value :
[
    {
        "uuid": "bd9544e3-9eed-443b-9276-70333b04b540",
        "firstName": "TESTER",
        "lastName": "Test11",
        "sex": "MALE",
        "salutation":"MR"
    }
]
-->	Response:
[
    "ERROR"
]

**Comment by MateStrysewske** [comment]
@kwa20 While it's definitely better to use a UUID according to the format that SORMAS is using, I don't think there would be errors inside the ReST API when a different format is used. Not completely sure though.

@herrling-LRA-KYF I think the problem with your requests is that you try to update a person that is not associated with any entity in the database. If you would try to query for that person, you would get a result, but the result would be pseudonymised, e.g. first and last name would be empty. If you try to update a person that you don't have real access to (because nobody has when the person does not have a connected entity), there's a NullPointerException while trying to restore the pseudonymised values during the person save process.

@MartinWahnschaffe I'm not sure how to handle this. I think it's good that the savePerson call fails in this case because the user doesn't have the right to update the person, but we should probably make sure that we return a proper error message. What's your opinion?

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske  sorry for spamming you ;-)

I created a Event, a Person, and an eventparticipant --> after that i qeure the person --> all is fine. Then i try to change the person --> ERROR

POST  sormas.bund.de/sormas-rest/events/push

[{
    "uuid": "06851209-cfd9-4ee2-832e-c5e120344c10",
    "externalId": "TEST",
    "eventStatus": "SCREENING",
    "eventTitle": "TEST",
    "eventDesc": "Sondershausen",
    "reportDateTime": "2021-04-07T11:34:51.039Z",
    "reportingUser": {
        "uuid": "XKHEAF-WL7IWE-PVB4N2-54PT2HJU"
    },
    "startDate": "2021-04-23T11:34:51.039Z",
    "eventLocation": {
        "uuid": "d3cd6af3-1a27-4b6a-8cf8-8d89e5943fb9",
        "city": "Sondershausen",
        "postalCode": "99706",
        "street": "Markt 8"
    }
}]
-->OK

POST .sormas.bund.de/sormas-rest/persons/push
[
    {
        "uuid": "bd9544e3-9eed-443b-9276-70333b04b540",
        "firstName": "TESTER",
        "lastName": "Test11",
        "sex": "MALE
    }
]
-->OK

POST sormas.bund.de/sormas-rest/eventparticipants/push
[
    {
        "uuid": "0c485e04-2b70-4b1c-8da6-2680b134076d",
        "event": {
            "uuid":"06851209-cfd9-4ee2-832e-c5e120344c10"
        },
        "person": {
            "uuid":"bd9544e3-9eed-443b-9276-70333b04b540"
        },
        "involvementDescription":"positiv/negativ/ungültig"
    }
]
-->OK

QUERY PERSON looks fine and with data (nothing anonym)

TRY TO CHANGE PERSON
POST .sormas.bund.de/sormas-rest/persons/push
[
    {
        "uuid": "bd9544e3-9eed-443b-9276-70333b04b540",
        "firstName": "TESTER",
        "lastName": "Test11",
        "sex": "MALE",
        "salutation":"MR"
    }
]
-->	ERROR

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF The error is indeed the same in this case. I think the reason is that there are integral parts missing in that request (e.g. the address). The ReST API currently does not support POST, only PUSH - so you're expected to provide a full person with that request, not only a few fields. Querying for the person, changing the fields you need to change in the data you get as a result and then pushing the changed data will work.

Supporting POST is definitely something we need to do, and as far as I'm concerned, it's something that the Angular team is currently working on.

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske thank you very much, while posting the whole person with other field or additional fields it is working. When overwriting fields you have to set a new changeDate.
Maybe you could all this info in the swagger documentation
