### ISSUE TITLE
"Other facility" can't be properly imported for locations

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3646]
### Bug Description
When trying to import facilities in the home address section on the person form, an error occurs.

Error: invalid value 'OTHER_FACILITY' in the column person.address.facility

This might be due to the fact that OTHER_FACILITY relates to the place of stay in caseData. The entry for the facility drop-down field is inferred by that, though, since it is also filled with 'other facility' accordingly and then shows the additionally provided facility details in facility name and description.

Even when depositing the facility in the infrastructure data and subsequently using this facility name as a value in the import facility column, the error remains. However, when the field is left empty, the import is successful and the entered facilityDetails show up when selecting 'other facility' in the drop-down field afterwards.

### Steps to Reproduce
1. import a case with the person.address.facility field entered.
2. check import result and error report.
3. Repeat again with entered facilityDetails and go to person form.
4. Select other facility and check details field.

### Expected Behavior
Field would be expected to work with either a value representing 'other facility' or the deposited infrastructure name.
### Screenshots
<img width="433" alt="LocationFacilityImport" src="https://user-images.githubusercontent.com/70317594/100672435-3988a480-3362-11eb-83d2-3186992252d8.PNG">
<img width="421" alt="LocationFacilityImport2" src="https://user-images.githubusercontent.com/70317594/100671325-97b48800-3360-11eb-82ee-30efd0927f9d.PNG">
<img width="466" alt="personFacility" src="https://user-images.githubusercontent.com/70317594/100671327-98e5b500-3360-11eb-9638-028a5cf5b325.PNG">
<img width="464" alt="personFacility2" src="https://user-images.githubusercontent.com/70317594/100671334-9aaf7880-3360-11eb-82b9-83e2204bd73a.PNG">

### System Details
* Device:
* SORMAS version: 1.51.1/1.52.0
* Android version/Browser: chrome, firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
Tested and import works fine now
