### ISSUE TITLE
Contact index list performance issues related to visit count

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#3650]
### Problem Description
On some of the German systems one export batch can take 8 seconds.
The best candidate for the reason why this is slow is the visits subquery: 

> (select (select count(visits18_.contact_id) from contacts_visits visits18_ where contact17_.id = visits18_.contact_id) from Contact contact17_ where contact17_.id=contact0_.id) as col_31_0_

### Proposed Change
My suggestion is to change the query in ContactListCriteriaBuilder.buildIndexCriteria that seems to unnecessarily do another sub select on Contact, though it could directly use the Contact of the main query.

Ideally the resulting query part should look something like this:

> (select count(visits18_.contact_id) from contacts_visits visits18_ where visits18_.contact_id=contact0_.id) as col_31_0_

It is possible that I'm wrong here and we need to find another solution to replace the whole sub-query OR that the slow part is something else in the query below.

### Additional Information

> duration: 7883.296 ms  execute <unnamed>: select distinct contact0_.uuid as col_0_0_, person1_.firstName as col_1_0_, person1_.lastName as col_2_0_, case3_.uuid as col_3_0_, contact0_.disease as col_4_0_, contact0_.diseaseDetails as col_5_0_, person4_.firstName as col_6_0_, person4_.lastName as col_7_0_, region12_.uuid as col_8_0_, district13_.uuid as col_9_0_, community14_.uuid as col_10_0_, contact0_.lastContactDate as col_11_0_, contact0_.contactCategory as col_12_0_, contact0_.contactProximity as col_13_0_, contact0_.contactClassification as col_14_0_, contact0_.contactStatus as col_15_0_, contact0_.followUpStatus as col_16_0_, contact0_.followUpUntil as col_17_0_, person1_.symptomJournalStatus as col_18_0_, user15_.uuid as col_19_0_, user16_.uuid as col_20_0_, contact0_.reportDateTime as col_21_0_, case3_.caseClassification as col_22_0_, user5_.uuid as col_23_0_, region6_.uuid as col_24_0_, district7_.uuid as col_25_0_, community8_.uuid as col_26_0_, facility9_.uuid as col_27_0_, pointofent10_.uuid as col_28_0_, contact0_.changeDate as col_29_0_, contact0_.externalID as col_30_0_, 
> (select (select count(visits18_.contact_id) from contacts_visits visits18_ where contact17_.id = visits18_.contact_id) from Contact contact17_ where contact17_.id=contact0_.id) as col_31_0_ from Contact contact0_ left outer join Person person1_ on contact0_.person_id=person1_.id left outer join Location location2_ on person1_.address_id=location2_.id left outer join cases case3_ on contact0_.caze_id=case3_.id left outer join Person person4_ on case3_.person_id=person4_.id left outer join users user5_ on case3_.reportingUser_id=user5_.id left outer join Region region6_ on case3_.region_id=region6_.id left outer join District district7_ on case3_.district_id=district7_.id left outer join Community community8_ on case3_.community_id=community8_.id left outer join Facility facility9_ on case3_.healthFacility_id=facility9_.id left outer join PointOfEntry pointofent10_ on case3_.pointOfEntry_id=pointofent10_.id left outer join Person person11_ on case3_.person_id=person11_.id left outer join Region region12_ on contact0_.region_id=region12_.id left outer join District district13_ on contact0_.district_id=district13_.id left outer join Community community14_ on contact0_.community_id=community14_.id left outer join users user15_ on contact0_.contactOfficer_id=user15_.id left outer join users user16_ on contact0_.reportingUser_id=user16_.id where contact0_.region_id=$1 and (case3_.archived=$2 or case3_.archived is null) and contact0_.deleted=$3 and (lower(contact0_.uuid) like $4 or lower(person1_.firstName) like $5 or lower(person1_.lastName) like $6 or lower(case3_.uuid) like $7 or lower(person11_.firstName) like $8 or lower(person11_.lastName) like $9 or regexp_replace(person1_.phone, $10, $11, $12) like $13 or lower(location2_.city) like $14 or lower(location2_.postalCode) like $15) order by contact0_.changeDate desc limit $16 offset $17
>

**Comment by StefanKock** [comment]
@HolgerReiseVSys directed me to #3137 with a maybe similar problem that proposed an index on the foreign key column.

**Comment by MartinWahnschaffeSymeda** [comment]
Yes, but due to the strange subquery I'm pretty sure that the index won't be sufficient.

**Comment by StefanKock** [comment]
To not clash with schema_version on development branch, @MateStrysewske and I decided to not include an SQL index here.

**Comment by MartinWahnschaffeSymeda** [comment]
Ok. Todos:

- [ ] Prepare INDEX statement and provide it to parties that will need it upfront
- [ ] Simplify the criteria query as mentioned above

**Comment by StefanKock** [comment]
I discussed and reviewed the changes by @MateStrysewske and added a unit test.

**Comment by MateStrysewske** [comment]
Index will be created in #3673
