### ISSUE TITLE
Text cutoff in Epidemiological Data

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3659]
### Bug Description
In Case -> Epidemiological Data resp. Contact ->Epidemiological Data:
Texts are cut off for the languages German and French.
In French, there are furthermore texts that are not translated yet.

### Steps to Reproduce
1. Set language to German or French
2. Navigate to Epidemiological Data in a Case or Contact

### Screenshots
![image](https://user-images.githubusercontent.com/5616564/100869435-55dd2c00-349d-11eb-9114-c74315954d92.png)
![image](https://user-images.githubusercontent.com/5616564/100869584-8a50e800-349d-11eb-8373-0f53ffb842e3.png)

### System Details
* Device: Linux PC
* SORMAS version: 1.53.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: test-de.sormas.netzlink.com
* User Role: Case Supervisor

**Comment by adinaflorea9** [comment]
Verified ticket on test-de.sormas.netzlink.com, using the latest version of Sormas 1.68.0-SNAPSHOT.
