### ISSUE TITLE
Unique constraint missing for uuid column on documents [0]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3661]
### Proposed Change
- [x] Add UNIQUE constraint to the uuid column of the documents database table.

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of Sormas 1.57.0-snapshot 
![image](https://user-images.githubusercontent.com/70562142/107548119-f1de8e80-6bd6-11eb-8921-b32b3b2e7a82.png)
