### ISSUE TITLE
The High Charts axis labels should be activated on all charts on the dashboard [0.5]

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3663]
### Bug Description
For all charts shown on the dashboard, it is standard practice to have the axis labels shown on the Y-axis and X-axis. Right now all the charts do not show any axis labels
### Steps to Reproduce
1. Go to dashboard, view charts and no axis labels is shown for all the charts
2.

### Expected Behavior
All charts should have axis labels. This is related to issue #3320 and #3065
### Screenshots
![D1CDD456-F1B0-4D77-A87D-07BD0BA4B7E3](https://user-images.githubusercontent.com/60390281/100881591-1baf6280-347c-11eb-9ba7-b1ea479c371a.jpeg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
@danieltomaba Can we use the actual numbers on the axis rather than using k?
- For ease of interpretation, It is good that the bars that we stack correspond to one variable only and then group by the categories or levels of the variable. eg missed Vs non-missed on one bar, same house vs different houses on same bar etc
- If we use proportions on y axis, then we can also add the total counts, maybe below the table, near to legend

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] For y-axis use "Aggregated number" as caption
- [ ] For x-axis use "Province" (or whatever the current grouping is) as caption. When the chart has multiple bars per grouping the caption has to go to the top of the chart, where the names of the regions are located as-well.

@danieltomaba Ok?

**Comment by BarnaBartha** [comment]
- [ ] when changing filters related to jurisdiction (all filters of campaign dashboard except the actual campaign) stay on the same tab & subTab

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] remove the space for the bars (26%) instead of (26 %)
- [ ] Automatically scale the y axis to the actual visible numbers
- [ ] Use "count" instead of "aggregated number"
- [ ] Use one decimal place for values below 2%

**Comment by MartinWahnschaffeSymeda** [comment]
Refinements after reviewing this again:

- [ ] Show % in tooltips for percentage charts
- [ ] Add toggle to enable/disable data labels. Disable by default
- [ ] Move javascript function adding into campaign chart component
