### ISSUE TITLE
All SORMAS related roles shown on the users module should be taken out of the APMIS and the relevant roles renamed

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#3664]
### Feature Description

![21D4B94C-0DA0-4B8D-8895-ACB669AC0BBC](https://user-images.githubusercontent.com/60390281/100884409-6ed6e480-347f-11eb-9e8f-a681a2d229df.jpeg)

### Problem Description
Right now under users, you have so many user roles that are not related to APMIS users.  This confuses the admin users to have so many user roles to select from not related to the user roles that he needs to set up. 
### Proposed Change
Remove SORMAS related users and have only the following for APMIS:
Hub User (no ability to change or add any data. Only readonly view but allowed to export, manipulate data and can see multiple countries)
WHO User (no ability to change or add any data. Only readonly view but allowed to export, manipulate data)
UNICEF User (no ability to change or add any data. Only readonly view but allowed to export, manipulate data)
NEOC Admin (Read, Write, Execute)
NEOC user (no ability to change or add any data. Only readonly view but allowed to export, manipulate data)
National Supervisor (RWE)
National Observer (R)
Regional Supervisor(RWE)
Regional Observer (R)
Provincial Supervisor(RWE)
District Supervisor(RWE)
Cluster Supervisor(RWE)

**Comment by MartinWahnschaffeSymeda** [comment]
Functionality for this will be provided by #3716.

@danieltomaba You can already use crowdin to rename the user roles that are needed in the en-af language.

**Comment by MartinWahnschaffe** [comment]
@danieltomaba You can use the following script to configure the available user roles on the test system now:

```
DO $$
DECLARE 
	_roleEnabled boolean := false;
	_roleId bigint;
	_uuid varchar;
	_userRole varchar;
	_userRoles varchar[] := array['ADMIN_SUPERVISOR', 'HOSPITAL_INFORMANT', 'CASE_SUPERVISOR', 'CASE_OFFICER', 'CONTACT_SUPERVISOR', 'CONTACT_OFFICER', 'EVENT_OFFICER', 'LAB_USER', 'EXTERNAL_LAB_USER', 'NATIONAL_CLINICIAN, 'POE_INFORMANT', 'POE_SUPERVISOR', 'POE_NATIONAL_USER', 'IMPORT_USER', 'REST_EXTERNAL_VISITS_USER', 'REST_USER', 'SORMAS_TO_SORMAS_CLIENT', 'BAG_USER'];


BEGIN

	FOREACH _userRole IN ARRAY _userRoles
	LOOP

		SELECT id FROM userrolesconfig WHERE userrole = _userRole INTO _roleId;
		
		IF(_roleId is null) 
			THEN 
				_uuid = overlay(overlay(overlay(
                            substring(upper(REPLACE(CAST(CAST(md5(CAST(random() AS text) || CAST(clock_timestamp() AS text)) AS uuid) AS text), '-', '')), 0, 30)
                            placing '-' from 7) placing '-' from 14) placing '-' from 21);
        		INSERT INTO userrolesconfig (id, uuid, changedate, creationdate, userrole, sys_period, enabled) 
				VALUES (nextval('entity_seq'), _uuid, now(), now(),_userRole, NULL, _roleEnabled);
			ELSE
				UPDATE userrolesconfig SET  changedate =  now(), enabled = _roleEnabled WHERE id = _roleId;
		END IF;		
	END LOOP;
END
$$ LANGUAGE plpgsql
```

You may have to adjust the initial list of user roles that are disabled. This is the current list of all user roles:
```

ADMIN
NATIONAL_USER
SURVEILLANCE_SUPERVISOR
ADMIN_SUPERVISOR
SURVEILLANCE_OFFICER
HOSPITAL_INFORMANT
COMMUNITY_INFORMANT
CASE_SUPERVISOR
CASE_OFFICER
CONTACT_SUPERVISOR
CONTACT_OFFICER
EVENT_OFFICER
LAB_USER
EXTERNAL_LAB_USER
NATIONAL_OBSERVER
STATE_OBSERVER
DISTRICT_OBSERVER
NATIONAL_CLINICIAN
POE_INFORMANT
POE_SUPERVISOR
POE_NATIONAL_USER
IMPORT_USER
REST_EXTERNAL_VISITS_USER
REST_USER
SORMAS_TO_SORMAS_CLIENT
BAG_USER
```
