### ISSUE TITLE
[CLIMEDO interface] Phone number is sent in the wrong format

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3669]
### Bug Description

Climedo gets the number as entered by users in SORMAS, which often is not in an international format.
Climedo requires the phone number in an international format. It makes sense to generally send a phone numbers like that.

**Comment by vlad-ciucescu** [comment]
At the moment on ga1 updating phone numbers in SORMAS does not synchronise them in CLIMEDO. There is no validation error in SORMAS. For other fields it works. The error in the logs is the following:
`{"success":true,"message":"Personeninformationen erfolgreich aktualisiert","errors":{"phone":"Ungültige Mobiltelefon-Nummer"}}`

I tried with phones in different formats:

- +1-541-754-3010
- +496211218490
- 0496211218490

(With this contact: https://ga1.sormas-oegd.de/sormas-ui/#!contacts/person/Q3TCUW-LVYSAY-YQABM7-K4J5SL5I)

Another strange behaviour is that for "+496211218490" the call to `visits-external/person/V6UJC6-5UXX5X-IJTGPT-2SCUKDHA` returns ` "phone": "+49 621 1218490"`, but for "0496211218490" it returns `"phone": "+49 4962 11218490"`.

**Comment by AndyBakcsy-she** [comment]
reopening issue until this behaviour is clarified/fixed

**Comment by FredrikSchaeferVitagroup** [comment]
We can not have the synchronization with climedo as the task of an issue when work from climedo has to be done. We can just make sure that our side works. From the log, it seems that climedo can't parse the phone number.

The behaviour for the 0496211218490 seems correct to me, as international numbers have to either start with 0049 ot +49. 
049 refers to local code then, so +49 49... is the correct internation format (important for [these](https://deutschland-in-zahlen.de/vorwahl.php?vwahl=49)).

So what is supposed to be done in this reopened ticket?

**Comment by vlad-ciucescu** [comment]
If you consider that this is a problem entirely on Climedo side, then we can close this, but they should be informed about this.

**Comment by AndyBakcsy-she** [comment]
Closing issue as verified on SORMAS Version: 1.53.0-SNAPSHOT
Based on the gathered information, this issue can be closed.
