### ISSUE TITLE
Create exposures for empty travel/burial/gathering lists

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3674]
### Bug Description
Two exposures are created from a single travel.

![image](https://user-images.githubusercontent.com/12996724/101073139-4cd48380-359f-11eb-9bd3-8999bff5db07.png)
### Steps to Reproduce
1.
2.

### Expected Behavior
- If there is a travel recorded, create only one exposure entity
- if travel outside district  == yes and no record registered, create the  empty exposure entity without dates, see fig below

![image](https://user-images.githubusercontent.com/12996724/101073474-d421f700-359f-11eb-8c01-92f55f629d9d.png)

### System Details
* Device: web
* SORMAS version: 1.52
* Android version/Browser: local system
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
I will add comments related to epi data to this issue:
Rhere is this text in exposure entity of animal contacts activity type 
"Automatic epi data migration based on selected kinds of exposure; this exposure may be merged with another exposure with animal contact"
Can we use
Automatic epi data migration based on selected kinds of exposure. This exposure may be merged with another exposure of activity type animal contact.

**Comment by bernardsilenou** [comment]
There is also an addition empty burial exposure, similar to travel. This does not happen when migrating gathering.
![image](https://user-images.githubusercontent.com/12996724/101085516-d1c79900-35af-11eb-8d2c-8658a8921e77.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou If you open the burial exposure, the field "Has had direct physical contact with the (deceased) case at a funeral" should be set to "Yes"; that's the migration of the former "directcontactdeadunsafe" epi data field.

**Comment by MateStrysewske** [comment]
@bernardsilenou The additional travel is not created because "Traveled outside of district" is set to Yes, but because the field "areaconfirmedcases" was set to Yes in the old epi data.
