### ISSUE TITLE
Migrate event description to event title

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3676]
### Bug Description
Issue #3223 implemented the cloning of event description to title. I upgraded my local docker system from 1.50 to 1,52 but this migration was not effective.
### Steps to Reproduce
1.
2.

### Expected Behavior
Can we do it with an SQL-Script:
Migrate (Copy) all old Event descriptions to the event Titles.
Best case:
Copy the first 75 chars of the description and paste it to the title. If the description is longer than 75 char, we show the first 75 chars plus a "..." in the title.
This way they can find the events again and see the detailed description, when clicked on.

### System Details
* Device:
* SORMAS version: 1,52
* Android version/Browser:
* Server URL: local system
* User Role:

**Comment by bernardsilenou** [comment]
@MateStrysewske Is this caused by the fact that i skipped 1,51? Do we need to do something about this?

**Comment by MateStrysewske** [comment]
@bernardsilenou The SQL script was added to the release notes. There shouldn't be any production systems active right now that still have a problem with this (and if they have, they can simply execute the script), so I think adding it to the automatic database update script at this point isn't necessary.
