### ISSUE TITLE
Adjust facility selection options for home address

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3679]
### Feature Description
Home address
### Problem Description
In the facility fields in home address, the fields still present options that do not make sense as a home address.
### Proposed Change
Change the facility selection options according to #3237 for home address also.
### Additional Information
<img width="708" alt="Screen Shot 2020-12-03 at 11 15 17 PM" src="https://user-images.githubusercontent.com/70317594/101095010-95029e80-35bd-11eb-967e-e03987676a34.png">

**Comment by MateStrysewske** [comment]
The home address will be removed from the UI in the next version, so there will only be the address list at that point. That should automatically fix this.
