### ISSUE TITLE
link facility category and type to type of place in exposures [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3680]
### Feature Description
Epi data tab, exposures
### Problem Description
In the exposures, we can select a type of place and facilities. A selection option in type of place however is facility. These fields can also contradict each other when for example choosing hospital as type of place and campsite in facility type. Moreover, hospital is a selection option in type of place but also occurs in the facility fields.
### Proposed Change
Adjust the type of place and facility fields in the location of exposures according to #3617.
### Additional Information
<img width="767" alt="Screen Shot 2020-12-03 at 11 29 14 PM" src="https://user-images.githubusercontent.com/70317594/101096833-705bf600-35c0-11eb-8341-64e36f251e26.png">

**Comment by MateStrysewske** [comment]
Will be done after #3617

**Comment by MateStrysewske** [comment]
Like written above: This can basically done in the same way as it was done in #3617

**Comment by raghupola-vg** [comment]
verified on Test environment on latest deploy both on App and Web and facility fields are now available in Exposures.
