### ISSUE TITLE
Don't allow multiple exposure entries for contacts

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3681]
### Bug Description
Multiple entries of exposures are possible for contacts. However, contacts can only ever have one exposure whereas contact persons could have been exposed to multiple cases described by the respective contacts. If the contact person would become a case, all these exposures would have to be adopted in the epi data exposures of the resulting case after all contacts have been converted to that case, assumed that all these contacts took place during the same incubation period of the disease. 
### Steps to Reproduce
1. Go to the epi data tab of a contact.
2. Make as many entries of exposures as you want.

### Expected Behavior
Only one exposure entry should be possible for a contact
### Screenshots
<img width="732" alt="Screen Shot 2020-12-03 at 11 41 36 PM" src="https://user-images.githubusercontent.com/70317594/101097932-5f13e900-35c2-11eb-8490-09a386f32898.png">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
@kwa20  This is a complex one, It all depends on how we look at it.
In reality, contact is actually one of the many exposures that a person can have.
These multiple exposures liked to the contacts can be interpreted as exposures liked to the contact person although the management and other measures are linked to the contact.

**Comment by kwa20** [comment]
@bernardsilenou Don't you think we should emphasize the difference between the contact person and the contact here? Since we're in the contact of that person, this really describes how the person was exposed to the disease through the contact to the specific source case. In the long run we could think of accumulating all the exposures that the person ever had in the person entity where it would make more sense. Otherwise, exposures entered in every contact to that person would also have to be adopted everywhere else.

**Comment by bernardsilenou** [comment]
@kwa20 What you said is correct, its all a matter of test of the information flow. I think the reason for not designing it as you mentioned is that a person can be linked to many cases, contacts, events, ... at a time each of different and unrelated diseases. Looking at all of this information from the person form will be overwhelming. Lets discuss further tomorrow and think on how to separate things better.

**Comment by MateStrysewske** [comment]
@kwa20 @bernardsilenou I agree with Kay and would actually suggest to change this for the hotfix because otherwise we might end up with "corrupt" data on production systems.

**Comment by MateStrysewske** [comment]
Actually I'm not so sure after I've thought about it for a few moments; because the exposures aren't necessarily directly linked to the contact event or the individual case, right? They're more linked to the person as in everything that could be of relevance when it comes to evaluating the contact or case. Maybe this actually needs to be discussed in a bit more detail.

**Comment by kwa20** [comment]
@MateStrysewske I think when inside the contact, the exposure in the epi data describes how the person was exposed to the source case via the contact, which the user is in right now. Logging exposures by the person would mean, that all exisitng exposures would have to be adopted in every contact that belongs to the person and happened in the incubation period (cf. visits). However, its not easy to infer afterwards what exposure describes the contact of the person to that specific source case in the current entity. 

Furthermore, all the single exposures per contact of the person would be adopted in the case of that person (when the person becomes a case), e.g. a person in an event had 5 contacts to 5 different cases. The individual exposures of the contacts would result in 5 exposures inside the case. People can then infer that one of these exposures likely led to that person becoming a case. Logging every exposure of that person would just be too much accumulation and hard to interpret. This would be more logical to possibly implement in #3560.

**Comment by MateStrysewske** [comment]
- [ ] Do this for the mobile app

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT

**Comment by AndyBakcsy-she** [comment]
Closing issue as it was verified and fixed
