### ISSUE TITLE
Disappearing apply/reset filter button when filtering task status 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3683]
### Bug Description
By default, the task status filter is set to pending, which initially shows all pending tasks in the directory. When the empty entry is selected, the apply/reset filter button disappear, which makes displaying all tasks impossible.
### Steps to Reproduce
1. go to the task directory.
2. choose the empty entry in the task status field.
3. check for the apply/reset buttons

### Expected Behavior
apply/reset filter buttons should not disappear when leaving the task status filter empty.
### Screenshots
<img width="1119" alt="Screen Shot 2020-12-04 at 12 55 24 AM" src="https://user-images.githubusercontent.com/70317594/101104911-7f48a580-35cc-11eb-8bbb-23471dacc5fa.png">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
Tested and works fine. Apply and Reset filters are displayed all the time(irrespective of filter selected) now.
