### ISSUE TITLE
Linking cases to source cases leads to error when sex of resulting case is missing

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3685]
### Bug Description
I want to link case A to case B:
- data for case A can be saved with missing sex, including person data all worked fine.
- When case A is linked to case B through epi data, system showed error, asking for sex for case A
- All works fine after providing sex fro case A even when sex for case B is missing
- Sex is required when creating entities; cases, contact, event participants but can later be deleted and entity saved without any error. Is this ok like this?
### Steps to Reproduce
1. 
2.

### Expected Behavior
- do not check for sex when linking cases
- check for sex when the person form is open and about to be saved

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/101107031-b7061c00-35d1-11eb-90c6-32da2a843204.png)

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: browser
* Server URL: test1401
* User Role:

**Comment by bernardsilenou** [comment]
- Since contact is immediately converted to case, set contact classification  to confirmed contact.
This is to be consistent with prospective contact  conversion to case.

**Comment by MateStrysewske** [comment]
@bernardsilenou My suggestion is that we display a custom error message if the sex is missing that asks the user to enter the sex for case A; the reason for this problem is that sex wasn't a mandatory field before, but it is now, so we can't just ignore it.

**Comment by AndyBakcsy-she** [comment]
Verified this issue on local environment on  SORMAS Version: 1.53.0-SNAPSHOT
