### ISSUE TITLE
Prompts for bulk actions in contacts have wrong heading

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3686]
### Bug Description
When bulk editing contacts to cancel follow-up or set to lost to follow-up, the heading of the prompts show 'confirm deletion'
### Steps to Reproduce
1. go to the contact directory.
2. select contacts and use bulk actions to either cancel or set to lost to follow-up.
3. check headings.

### Expected Behavior
headings should be associated to the actual action.
### Screenshots
<img width="268" alt="Screen Shot 2020-12-04 at 2 25 02 AM" src="https://user-images.githubusercontent.com/70317594/101110167-b9b83f80-35d8-11eb-991a-ee76eea2f723.png">
<img width="480" alt="Screen Shot 2020-12-04 at 2 24 32 AM" src="https://user-images.githubusercontent.com/70317594/101110173-be7cf380-35d8-11eb-934b-aeec3db47048.png">
<img width="402" alt="Screen Shot 2020-12-04 at 2 25 29 AM" src="https://user-images.githubusercontent.com/70317594/101110187-c2a91100-35d8-11eb-8ccf-11e83c8ccdf1.png">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Verified issue on the latest  SORMAS Version: 1.53.0-SNAPSHOT
