### ISSUE TITLE
persons shown as confidential on the contact directory are not pseudonymized in person form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3687]
### Bug Description
On the contact directory, persons are shown as confidential that are not pseudonymized on the person form.
### Steps to Reproduce
1. go to the contact directory as a user with regional restrictions.
2. look for a contact person who is shown as confidential.
3. open the contact and go to the person form.
4. check person info for pseudonymization.

### Expected Behavior
Contacts shown as confidential on the directory should also be pseudonymized on the person form.
### Screenshots
<img width="1097" alt="Screen Shot 2020-12-04 at 3 44 34 AM" src="https://user-images.githubusercontent.com/70317594/101115417-a068c080-35e3-11eb-8bb9-87495b4cba58.png">
<img width="809" alt="Screen Shot 2020-12-04 at 3 43 45 AM" src="https://user-images.githubusercontent.com/70317594/101115423-a494de00-35e3-11eb-9a1c-551cf6d50500.png">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: surveillance supervisor

**Comment by MateStrysewske** [comment]
@kwa20 Can you check what the correct behaviour would be in this case? Should the person be pseudonymized or only "read-only"? I.e. which view shows the wrong behaviour, the directory or the edit form?

**Comment by kwa20** [comment]
@MateStrysewske I think the correct display would be read-only but non-confidential. The contact is outside of the users jurisdiction, therefore read-only, but is a contact to a case in the users jurisdiction, therefore, non-pseudonymized.

**Comment by bernardsilenou** [comment]
@kwa20 The reason for not using read-only is that the law does not allow users who are not in the jurisdiction of the contact to see person information of the contact person. This is one of the main reason why we introduced Pseudonimization in addition to of read only access. 

There are 3 types of user access:
1. If the contact has no jurisdiction assigned, even though they have an associated case, then  only the users in the jurisdiction of the case has full access (read + write) to the contacts.
2. For contacts with assigned jurisdiction, no matter if they have a source case or not,  only users in the jurisdiction of the contact should have full access to the contact.
3. If the contact has a jurisdiction assigned and:
   3.1  this is the same as that of the case, then number 1 or 2 applies
   3.2  If different from that of the case, then all users in jurisdiction of the case  (except reporting user) has no write access but 
          have partial read access to the contact ie all personal data for the contact should be set as confidential on all directories 
          and forms and other variables should be read only. However, the reporting user  of the contact (not that of the case) will 
          have read access only and see the name of the contact. The contact will appear in the view of all the users in the 
          jurisdiction of the case as external contact with the rights to personal data as defined here.

**Comment by kwa20** [comment]
@MateStrysewske According to what @bernardsilenou described, this actually means that the personal data above should be confidential. So the display of the directory above is correct (confidential since the contact is outside of the users jurisdiction but has a case in the users jurisdiction) but the the person information is displayed incorrectly (personal data should be pseudonymized).

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 The likely reason why the person is not pseudonymised inside the person form is that the user has access to another case, contact or event participant of that person that lies within their jurisdiction. The directory ignores that, but the person edit form actually checks whether the user is allowed to see the personal details of the person, not of the associated case, contact or event participant.

Is your latest decision still correct under these circumstances?

**Comment by bernardsilenou** [comment]
@MateStrysewske Very good point. This means the current implementation is fine by me.

**Comment by MateStrysewske** [comment]
@kwa20 What do you say?

**Comment by kwa20** [comment]
@MateStrysewske I had another look and the person here has a case outside of the users (surveillance supervisor) jurisdiction with no links to any event. When filtering for the case in the case directory, it never shows. The only time you can find the contact person is through the contact directory and the contacts tab from the case that actually lies in the users jurisdiction. Therefore, I still think the person information here should be confidential because the person in question has no connected entity that belongs to the users jurisdiction.

**Comment by MateStrysewske** [comment]
@kwa20 Can you tell me which system and which user you're using to test this?

**Comment by kwa20** [comment]
@MateStrysewske Sent you the log ins via mail. server: test1401.sormas-oegd.de 

Just realized something else too. The case of the person in question got converted from the contact that the restricted user could already see because the source case is in the users jurisdiction. With the new epi data, the resulting case is now also connected to the source case, so theoretically the case should also be shown to the user, however, pseudonimized since it is still outside of the users jurisdiction.

**Comment by MateStrysewske** [comment]
The logic generally works, but it seems like the person is not correctly pseudonymised inside a contact of a case that the user has access to.

**Comment by bernardsilenou** [comment]
> @MateStrysewske Sent you the log ins via mail. server: test1401.sormas-oegd.de
> 
> Just realized something else too. The case of the person in question got converted from the contact that the restricted user could already see because the source case is in the users jurisdiction. With the new epi data, the resulting case is now also connected to the source case, so theoretically the case should also be shown to the user, however, pseudonimized since it is still outside of the users jurisdiction.

@kwa20 I did not understand this point, can you create another issue for this?
