### ISSUE TITLE
[DEMIS2SORMAS] Setup an ExternalLabMessageFacade interface

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#3696]
### Feature Description
#3487 and #3488 require the ExternalLabMessageFacade class. This shall be implemented here.

The ExternalLabMessageFacade shall define methods required for modules providing LabMessages with data from external systems (such as DEMIS). Especially a `public List<LabMessage> getNewLabMessages()` which returns not formerly fetched messages from an server, converted to LabMessages.
### Additional Information
This issue results out of #3440.

**Comment by vidi42** [comment]
@FredrikSchaeferVitagroup please add the tasks that still remain once those are clear
To be closed together with #3488

**Comment by FredrikSchaeferVitagroup** [comment]
Merged in #4023.
