### ISSUE TITLE
Person duplication recognition does not trigger for persons with archived entities [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3704]
### Bug Description
When a new case or contact is created for a person in the database, person duplication recognition does not trigger when previously existing entities for that person are archived. This is problematic because individuals are then created as multiple persons in the system. Previously entered information to that person (e.g. addresses, contact information) also can't be adopted. Furthermore, there is no option to merge duplicate persons yet.
### Steps to Reproduce
1. archive entities for a person that already exists in the database.
2. create a new case/contact for the same person and enter details that should trigger duplicate detection.
3. check whether duplication recognition triggers upon creation.

### Expected Behavior
Independent of archived entities, person duplication recognition should always trigger to ensure that only one person is created in the system for any individual.
### Screenshots

<img width="1106" alt="Screen Shot 2020-12-06 at 11 11 40 PM" src="https://user-images.githubusercontent.com/70317594/101294769-f9ba3500-3819-11eb-8511-36497bd8a8ca.png">
<img width="750" alt="Screen Shot 2020-12-06 at 11 12 08 PM" src="https://user-images.githubusercontent.com/70317594/101294776-fd4dbc00-3819-11eb-871a-7659bfcc64a8.png">
<img width="752" alt="Screen Shot 2020-12-06 at 11 26 52 PM" src="https://user-images.githubusercontent.com/70317594/101294900-a5638500-381a-11eb-8499-fda49afb2149.png">

### System Details
* Device:
* SORMAS version: 1.52; 1.51.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de; musterstadt.sormas-oegd.de
* User Role: admin, national user

### Additional Information
- We should not show persons without undeleted data
- add feature configuration for it 

### Development Specifications
* Add a new property to the SERVER SETTINGS section of sormas.properties and a corresponding ConfigFacade entry
  * Name: `duplicatechecks.excludepersonsonlylinkedtoarchivedentries`
  * Default: false
  * Possible Values: true, false
  * Description: Excludes persons that are only related to archived cases, contacts or event participants when searching for duplicate persons during case, contact or event participant creation. Setting this value to true might increase performance during imports and entity creation, but will likely lead to more duplicate persons in the system.
* When searching for similar persons during case, contact or event participant creation, don't filter for active cases, contacts or event participants unless the new property has been set to yes

**Comment by bernardsilenou** [comment]
This does not work on test1401 but works fine on my local system also on 1,52 with the default docker settings.
@MateStrysewske Is there any configuration for this? since it worked fine on my system

**Comment by MateStrysewske** [comment]
If I remember correctly, doing it this way was a specific request from HZI at some point because they wanted to reduce the number of potential duplicate persons. I'd agree that we should revert this again, but would like to have the confirmation that this is indeed fine.

**Comment by kwa20** [comment]
@MateStrysewske Doesn't the duplicate recognition not triggering actually result in more duplicate persons occurring? I think reverting this would be very important so hopefully any person in the system is only ever created once. @bernardsilenou mentioned that excluding persons with archived entities might have been done due to performance reasons.  Would that be an issue? Maybe there is a way to keep a stable performance while also ensuring good data quality.

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske The reason why we decided to exclude persons linked to archives entities was a way of improving performance. I suggest we do not quickly revert it but test and make sure it will have no effect on performance. You know there can be production servers with hundred of millions of persons.

My recommendation will be to add a server configuration for this. One solution may not work for all the instances because the law in some countries that i am aware of prevent health officials to track and link entities to the same person over time.

Do you have any idea whey archived  persons are considered on my local system but not on the test servers? This is something to investigate.

**Comment by MateStrysewske** [comment]
@bernardsilenou Are you sure that there is no active entities related to the persons on your system? No case, contact or event participant?

**Comment by bernardsilenou** [comment]
@MateStrysewske That was my initial thought when Kay told me of this issue. Both of us did a test twice on my system and could reproduce it.

**Comment by kwa20** [comment]
@MateStrysewske @bernardsilenou This is quite important to the users, so if it was changed in the past, we should revert it if possible. If it leads to possible performance issues, the logic from #3787 might help to reduce queries of the respective database tables. If necessary, might might even use other available data like address fields to narrow down the possible duplicate suggestions.

**Comment by bernardsilenou** [comment]
@kwa20 
- use of address for duplicate person detection will be a challenging one since there can be many addresses per person and most countries do not register the address of persons in sormas.
- lets do a test tomorrow with 1,52,1 on different servers please

**Comment by kwa20** [comment]
@bernardsilenou Is the dob considered for person duplicate recognition? If not, this should resolve the performance issue if we consider unarchived entities as well.

**Comment by bernardsilenou** [comment]
@kwa20 dob is considered when available.

**Comment by bernardsilenou** [comment]
@MateStrysewske Any further refinement needed?

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske
Summary:
- Persons linked to archived entities  should be considered for duplicate person detection as a default setting. This would then imply that archived entities are also considered.
- Add a configuration to exclude them
