### ISSUE TITLE
Contacts > Set "Last update date" in DB of Contact if changes have been made on the Contact Person [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3706]
### Feature Description
As a contact tracing reporter, I would like to keep track of Contacts and when changes are made to their information (Contact and Contact Person)(i.e. when this is updated) so that external systems may be implemented to automatically log and keep track of these changes (for communication purposes for example telephone call scheduling, SMS, automated emails etc.).

### Problem Description
When saving a mutation on an existing contact person, only the contact person is updated, not the contact. The behavior is different in the cases. If a "case person" is changed, the case is also updated and is at the top of the case directory list.

This is requested for Contacts too - please see attachment for detailed example: [Fehlerdokumentation_Kontaktperson.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5649789/Fehlerdokumentation_Kontaktperson.docx)

This is requested so that the automation of the contact process may be done. With the current state, it is not possible  to determine subsequent changes on the contact person.

### Proposed Change
Please handle the behavior of the last update date in the same way as in the cases. In this way, we can also determine mutations on a contact that were only made on the person of the contact using the update date.

### Additional Information
Original request: https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/157

### Development Specifications
* In the contact index list, use the change date of the associated person if it's newer than the contact change date

**Comment by markusmann-vg** [comment]
@Candice-Louw 
you have written: ". If a "case person" is changed, the case is also updated and is at the top of the case list."
This is not the current default behavior.

What is the expected behavior regarding the directory?

**Comment by Candice-Louw** [comment]
@markusmann-vg

User flow:

Cases > Case Directory > Open Case "First Last" in the middle of the directory list > Edit Case "First Last" **Case** info and save > Back to Case Directory > Case "First Last" is at the top of the list (with last change date updated)
✔️ 

similar

Cases > Case Directory > Open Case "First Last" in the middle of the directory list > Edit Case "First Last" **Case Person** info and save > Back to Case Directory > Case "First Last" is at the top of the list (with last change date updated)
✔️ 

AND

Contacts > Contact Directory > Open Contact "First Last" in the middle of the directory list > Edit Contact "First Last" **Contact** info and save > Back to Contact Directory > Contact "First Last" is at the top of the list (with last change date updated)
✔️ 

BUT

Contacts > Contact Directory > Open Contact "First Last" in the middle of the directory list > Edit Contact "First Last" **Contact Person** info and save > Back to Contact Directory > Contact "First Last" is NOT at the top of the list (with last change date NOT updated)
🚫

---

Expected behaviour:
That 🚫 behaves the same as the ✔️ instances and updates the last change date after a change on the Contact Person details too.

---

Current workaround used in Kt. BE is to edit the comment field on the Contact every single time a change is made to the Contact Person information so that the Contact last change date may be updated in the database.  If the contact tracers forget to update the comment, though, there is no way to detect that the contact has been updated and the new values would not be captured.

**Comment by Candice-Louw** [comment]
@baenik - could you please confirm whether this is still a requirement from you side, or if you have found a workaround, please?

**Comment by Candice-Louw** [comment]
Possibly related (Case.changeDate/Contact.changeDate): https://github.com/hzi-braunschweig/SORMAS-Project/issues/6080

**Comment by Alexandru-Pirvu** [comment]
The fact that for cases it works correctly is actually a side effect of some other logic. If that logic would be changed, the case directory would have the same behavior as the contacts directory.

The changes will apply the fix also for cases.
