### ISSUE TITLE
Can not run maven install sormas-base on development due to test error

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3711]
### Bug Description

The backend CaseStatisticsFacadeEjbTest does not pass due to an error. As this seems to happen on my local machine as well as in the travis builds of my pull requests, it seems to be a general problem. The test reports:

`
Test set: de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjbTest

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.82 s <<< FAILURE! - in de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjbTest
testQueryCaseCount(de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjbTest)  Time elapsed: 1.29 s  <<< ERROR!
org.hibernate.exception.GenericJDBCException: could not extract ResultSet
	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjbTest.testQueryCaseCount(CaseStatisticsFacadeEjbTest.java:76)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: 
Fehler beim Aufruf eine benutzerdefinierten Funktion: "epi_week(null): null"
Exception calling user-defined function: "epi_week(null): null"; SQL statement:
SELECT COUNT(*) AS casecount , epi_week(cases.outcomeDate) AS groupA, null::text AS groupB FROM cases LEFT JOIN symptoms ON cases.symptoms_id = symptoms.id LEFT JOIN person ON cases.person_id = person.id WHERE (cases.deleted = false OR cases.deleted IS NULL ) AND (CAST(EXTRACT(YEAR FROM symptoms.onsetDate)  AS integer)) IN (?,?) AND (cases.caseAge IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)) AND cases.region_id IN (?) GROUP BY groupA ORDER BY groupA NULLS LAST [90105-200]
	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjbTest.testQueryCaseCount(CaseStatisticsFacadeEjbTest.java:76)
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.caze.CaseStatisticsFacadeEjbTest.testQueryCaseCount(CaseStatisticsFacadeEjbTest.java:76)`

### Steps to Reproduce
1. Checkout the development branch
2. Run maven install on sormas-base module

### Expected Behavior

Succesful build.

**Comment by StefanKock** [comment]
Duplicate to #2920, intermediate defect is fixed.
