### ISSUE TITLE
./server-setup.sh: 23: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by chrisseiner** [hzi-braunschweig/SORMAS-Project#3714]
As the title states: This is what i get on a clean Ubuntu 20.04. Everything else up to this point works fine.
 since the script references /bin/bash I really don't know the problem with the redireciton oeprator.
![Screenshot from 2020-12-07 11-18-49](https://user-images.githubusercontent.com/53100692/101338967-053f4780-387e-11eb-8980-1b534e7fb087.png)

**Comment by chrisseiner** [comment]
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.

was used.

**Comment by JonasCir** [comment]
Hi, I'm not certain what causes this.
In the meantime, you could checkout sormas-cargoserver as an [alternative](https://github.com/hzi-braunschweig/SORMAS-Project/tree/development/sormas-cargoserver) to build the project. Feel free to ask if you need help :)

**Comment by chrisseiner** [comment]
Hey JonasCir,

thank you for your reply. I'd like to use the version stated above and not read into other ways to run the system. Is there really no way to tell whats going on with the code? The error occurs, where the system is supposed to create the log file

**Comment by chrisseiner** [comment]
I fount the error!
The Setup-Script was running in a z-shell. I thought the crunchbang would change that but it didn't!

**Comment by JonasCir** [comment]
Alright then, I'm glad it worked out! I'm going to close this issue.
