### ISSUE TITLE
[CLIMEDO Integration] Allow use of the same contact details when only the First Name is different [1]

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#3718]
### Feature Description
Persons in SORMAS can be registered in as CLIMEDO patients.

### Problem Description
CLIMEDO offers the feature to register multiple family members to the same email address, but SORMAS does not allow this, even if the persons have the same last name. The check for email duplication will fail in SORMAS.

### Proposed Change
Allow multiple persons in SORMAS to use the same email address to register in CLIMEDO if they have the same last name (belong to the same family).

### Additional Information

- Checking for email duplication already implies retrieving the person data from CLIMEDO. No additional overhead will be necessary.
- Consider the improbable case in which two persons have the same last name, same emails but are not in the same family?

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest SORMAS Version: 1.53.0-SNAPSHOT on https://ga1.sormas-oegd.de/sormas-ui environment.
