### ISSUE TITLE
 Actions directory - the name of the person who wrote the action does not appear when creating the action

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3719]
### Bug Description
In the event part, followed by actions, it is possible to describe an action carried out within the framework of the investigation. After creating the action, it goes to the actions directory. Contrary to what is expected, the person who wrote the action does not appear in the directory under the "action replying user" field. His name only appears after modifying or completing the action.

### Steps to Reproduce
1. create an action
2. save an action
3. in the directory, the name does not appear

### Expected Behavior
1. create an action
2. save an action
3. in the directory, the name should appear

### System Details
* Device:
* SORMAS version: 1.51.1
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
@ftavin @bernardsilenou

**Comment by ftavin** [comment]
Ok, it seems that the column is based on the "last modified by" value.

If empty it should use the "created by" value.

**Comment by ftavin** [comment]
@carolinverset it appears that we have different things here :
- the creator of the action
- the last person that modified the action
- the last person that modified the comment of the action
(note sure those two last are separate values in DB but non-creator can only modify comments)

Shouldn't we have differents columns for those concepts ? Or at least rename the column ? "Action replying user" isn't clear enough (and it's worst in french : "Utilisateur répondant de l'action")

**Comment by MateStrysewske** [comment]
I'll move this to the next sprint since it's not clearly defined yet. I want to say that adding additional columns is always a bit problematic because of space limitations. Users using the application on a smaller screen will run into problems.

**Comment by ftavin** [comment]
@carolinverset we still need to discuss this issue (my questions are above Mate's comment)

**Comment by carolinverset** [comment]
Yes I agree with Mate's comment. In fact, multiplying the columns may interfere with the correct reading of the information. I think it would be better to keep a column that shows the name of the person who last modified the action. If no one has modified the action, then the name of the person who created the action appears
@ftavin @MateStrysewske

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou  @MateStrysewske  then we should find a better name for that column...

**Comment by MateStrysewske** [comment]
I'd say something like "Last modified by" would be fine?

**Comment by alexandre-gille** [comment]
First thing first, just to be sure, should this `Last modified by` column display:
 a) The last user than modified the action. If not present, the user that created it.
 b) The last user than modified the reply part of the action. If not present, the user that created it.


Secondly the current `replyingUser` thing is kinda inconsistent.

It actually just store the last user that modified anything on the action. Even if it's just the actual creator of the action that amended a little typo just after creating it, while still being labelled under `action replying user`. What was it supposed to do in the first place ?

In the actions summary of an event it's displayed like that :

![image](https://user-images.githubusercontent.com/72074103/102498696-98e0f700-407a-11eb-9dd8-424196e85b18.png)

So here if we put aside the property name and column label and just take it for what it actually is - literally just the last person who edited anything on it -, it could make sense. If not, then it's misleading.

Besides, if we look into action's detail its position (that and the property name and column label even if it's not displayed on this form) let us think that it's only related to the reply part while it indeed isn't under the hood.

![image](https://user-images.githubusercontent.com/72074103/102498489-528b9800-407a-11eb-914e-9104806e2fca.png)

This `replyingUser` field should either tally with the last user that modified the given action or the last user that modified the reply part of the given action. But it can't be both.


So, what should I do ?

If we stick with `it's the last user that modified the given action`, I'll just rebrand this field and its labels to avoid confusion.
Even if the way it's displayed in the action edit form would still be a bit misleading.

If it really is supposed to be `the last user that modified the reply part`, I'll amend his behavior to actually be populated only if the reply part was modified by the user submitting the changes.

Depending on the answer to the first question I'll then use it as our lastModifiedBy field or create a dedicated one.


Sorry in advance if the post or/and my english isn't really intelligible. The problem actually is quite simple to solve but not to explain in writing !

**Comment by carolinverset** [comment]
@alexandre-gille @ftavin @bernardsilenou 
In general, and in my opinion, the following principle must be kept: whatever the modification made to the action, the name to be entered in the column of the action directory will be that of the person who made the last modification. It doesn't matter if the modification concerns the dates, the upper or lower block (comment) of the action.
Therefore, I also  propose to change the name of the column of the action directory and to name it in the way proposed by Alexandre "last modified by".
Is it ok for everybody?

**Comment by ftavin** [comment]
seems good to me

**Comment by MateStrysewske** [comment]
@ftavin @alexandre-gille Do you want to take care of the implementation? The development works that has been done on this issue so far isn't a proper solution and I'll close the associated pull request. If you have no capacities, I'll try to do it myself. :)

**Comment by ftavin** [comment]
@MateStrysewske I confirm that we have this issue referenced in our backlog. We will do our best to do it for 1.54

**Comment by MateStrysewske** [comment]
@ftavin Thanks! :)

**Comment by AndyBakcsy-she** [comment]
Validated issue on the last version of SORMAS Version: 1.54.0-SNAPSHOT
