### ISSUE TITLE
Contact directory and dashboards data not properly displayed for Admin role

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3723]
### Bug Description
When an admin only user is logged in, contacts and dashboards don't display the proper numbers and entries. Contact data is mostly missing on the dashboard and the directory and events are not shown on the surveillance dashboard.
### Steps to Reproduce
1. Log in as an admin only and check the dashboards.
2. Compare the displayed numbers, graphs, etc. to a combined role admin + national user.
3. Repeat for the contact directory.

### Expected Behavior
All data should be accessable with the admin role, the only difference being that personal and sensitive data is pseudonymized for admin only users.
### **Admin:**
![AdminContacts](https://user-images.githubusercontent.com/70317594/101486167-8836cf80-395c-11eb-9e0f-9f05e792e1be.JPG)
![AdminContactsDashboard](https://user-images.githubusercontent.com/70317594/101486180-8a992980-395c-11eb-821b-0470f2657622.JPG)
![AdminSurveillanceDashboard](https://user-images.githubusercontent.com/70317594/101486187-8cfb8380-395c-11eb-9ea6-199ec8f75c0e.JPG)

### **Admin + National User:**
![AdminNationalUserContacts](https://user-images.githubusercontent.com/70317594/101486217-984eaf00-395c-11eb-93c8-909757700fd1.JPG)
![AdminNationalUserContactsDashboard](https://user-images.githubusercontent.com/70317594/101486223-9ab10900-395c-11eb-988e-34fcbe465e0a.JPG)
![AdminNationalUserSurveillanceDashboard](https://user-images.githubusercontent.com/70317594/101486229-9c7acc80-395c-11eb-9a5a-6e4de26d7ec0.JPG)

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, admin + national user

**Comment by bernardsilenou** [comment]
@kwa20  Our initial design was that admin role only does not see these entities in the first place, thus such outcome is expected.
Was it latter changed? Please check the user right table and let us know.

**Comment by kwa20** [comment]
@bernardsilenou According to the user rights table, the admin role should have access to the mentioned data.

**Comment by bernardsilenou** [comment]
@kwa20 This means we need to investigate this further then.
@MateStrysewske were you aware if admins should have full access to this data?

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 Admins don't have access to this data by default, no. They are technically able to see cases, contacts etc., but in reality, since they don't have a jurisdiction, they will probably only see cases that were shared with the whole country and depending contacts, or those that they created themselves.

**Comment by kwa20** [comment]
@bernardsilenou We should then think about how to properly display this because it does not make sense the way it is now and only causes confusion.

**Comment by bernardsilenou** [comment]
@kwa20 I understand you and the only time we can think about adjusting such view is after covid crisis.
As @MateStrysewske mentioned, that is the same thinking i had in mind.
