### ISSUE TITLE
Adding new fields to cases and contacts breaks loading contact details

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#3725]
### Bug Description
Adding new fields to cases and contacts breaks loading contact details.
PSQLException is thrown

```
Caused by: org.postgresql.util.PSQLException: ERROR: target lists can have at most 1664 entries
```

### Steps to Reproduce
1. Open contacts view
2. Open contact details

### Expected Behavior

Loading contact details should not throw exception.

### System Details
* SORMAS version: 1.53.0-SNAPSHOT

### Additional Information
Did until now only happen on a feature branch because the newly added attributes surpassed the threshold of 1664 columns of a complex outer join cascade.

**Comment by StefanKock** [comment]
Explanation for this problem: Because of the default `fetch=FeatchTypeEAGER` of `@ManyToOne` loading the _SormasToSormasShareInfo_ built a Cartesian product which blew up to over 1664 columns.

**Comment by AndyBakcsy-she** [comment]
Verified issue on SORMAS Version: 1.53.0-SNAPSHOT
