### ISSUE TITLE
[SurvNet Interface] Mapp relevant fields for case classification calculation [INVESTIGATION]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3727]
### Situation Description
To correctly calculate the case classification in SurvNet, which is relevant for reporting cases to the higher health institutions, several entries in different fields are necessary. Firstly, data about the clinical information (symptoms) is needed to determine the clinical confirmation. Confirmed would mean, that symptoms are present that are relevant for the specific disease. Secondly, information about lab results are needed to determine, whether a case is confirmed by laboratory diagnostics. Lastly, information about the epidemiological confirmation is needed. 

Transfer of symptoms itself exists.
### Feature Description
Mapp the following fields to the SurvNet instance when transfering data from SORMAS to SurvNet:

**Clinical:**
 

- SORMAS: all symptoms set to unknown -> SurvNet: "nicht ermittelbar" or "Nein, keine klinischen Informationen verfügbar"

- SORMAS: all symptoms or at least one set to no -> SurvNet: "Ja, aber ohne Symptomatik, die für die gemeldete Krankheit bedeutsam ist"

- SORMAS: at least one of the following symptoms is set to yes: Sore throat, Cough, Pneumonia, Runny nose -> SurvNet: "Ja, mit Symptomatik, die für die gemeldete Krankheit bedeutsam ist"

- SORMAS: any other symptom set to yes -> SurvNet: "Ja"

**Laboratory diagnostics:**

- SORMAS: positive test result with type of test "Culture" -> SurvNet: "Laborangaben verfügbar: Ja"7"Labormethoden: Erregerisolierung (kulturell)

- SORMAS: positive test result with type of test "PCR" -> SurvNet: "Laborangaben verfügbar: Ja"/"Labormethoden: Nukleinsäure-Nachweis (z.B. PCR)

**Epidemiological**
 

- SORMAS: Epidemiological confirmation set to yes -> SurvNet: "Epid. Bestätigung erfüllt (manuell)" tick

### Additional Information
![KlinSurvNet2](https://user-images.githubusercontent.com/70317594/101504142-2b92df00-3973-11eb-9584-8a19611c9219.jpg)
![LabEpiSurvNet2](https://user-images.githubusercontent.com/70317594/101504151-2d5ca280-3973-11eb-95ee-b422b087318b.jpg)

**Comment by kwa20** [comment]
@markusmann-vg @HolgerReiseVSys

**Comment by markusmann-vg** [comment]
@HolgerReiseVSys 
Tasks
- [ ] Please investigate what fields are missing

**Comment by JonasCir** [comment]
RKI Definition how to compute the fields: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Falldefinition.pdf?__blob=publicationFile

**Comment by kwa20** [comment]
@markusmann-vg @HolgerReiseVSys I will close this issue because it's no longer applicable due to parallel implementations.
