### ISSUE TITLE
Introduce GitHub Actions for CI

### ISSUE THREAD

**Issue by Seal33** [hzi-braunschweig/SORMAS-Project#3730]
### Feature Description

Switching from Travis CI to GitHub Actions provides an immediate solution to the very slow CI process.

This Issue and linked PR would not disable Travis CI, but enable GitHub Actions in addition, so that the results can be evaluated and compared later on.

### Problem Description

The current Travis CI process is very slow, in part due to CI processing queuing up for a lot of time.
Build minutes are also limited as announced last months (#3541) . In comparison, GitHub offers unlimited build minutes for public repositories ([source](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions))

This is of particular high risk as currently, PRs get regulary merged without the CI process finishing, posing security and stability risks (of the last 50 commits to development branch, none passed the tests, probably because most didn't even start) (see #3711 )

### Proposed Change

Enabling and integrating GitHub Actions is a fast and streamlined solution. It also opens up a whole lot of possibilities due to the full GitHub integration, like disabling merging for PRs whose tests failed.

In addition, the tests for JDK8 and JDK11 run fully parallel and finished nearly twice as fast as the current Travis CI (total 16:09min vs 27:05min)

### Additional Information

[Example Build with GitHub Actions](https://github.com/ImisDevelopers/SORMAS-Project/actions/runs/410539795)

[Travis CI Build for comparison](https://travis-ci.org/github/hzi-braunschweig/SORMAS-Project/builds/748367014)

[GitHub Actions Documentation](https://docs.github.com/en/free-pro-team@latest/actions)

**Comment by MartinWahnschaffeSymeda** [comment]
@JonasCir Thanks a lot for the PR!
I think we should take this opportunity to only do builds for Java 11. We are using Java 11 since July now and should phase out the active support for Java 8 (see #2617).

From my point of view it would also make sense to remove the travis ci integration as part of this. Having two build systems active would be a waste of server times for them.

**Comment by JonasCir** [comment]
Thank you Martin! I'll update the PR now.

**Comment by MartinWahnschaffeSymeda** [comment]
@HolgerReiseVSys mentioned that it should be sufficient to call mvn test instead of mvn verify. This would save at least the time to build the widgetset and since we don't have any integration tests that are run here, we wouldn't loose anything.

@JonasCir What do you think?

**Comment by JonasCir** [comment]
@MartinWahnschaffeSymeda I'll give it try thanks
Also see: https://github.com/hzi-braunschweig/SORMAS-Project/pull/3778
Travis is still active maybe, you need to go to travis website and disable it there

**Comment by MartinWahnschaffeSymeda** [comment]
Should be deactivated now

**Comment by JonasCir** [comment]
Another comment: In the last time there were multiple incidents where failing branches were still merged to development. I would suggest to enable settings/branches/Branch protection rules and checkbox require status check to pass before merging
