### ISSUE TITLE
Add feature configuration for the "GDPR Consent Popup"

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#3731]
### Situation Description
There are SORMAS users who do not want the lightbox popup to appear. 
With the feature configuration it can be enabled/disabled

**Comment by MateStrysewske** [comment]
* Call the configuration GDPR_CONSENT_POPUP
* Default should be off
* Don't show the GDPR consent popup when the feature is disabled

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest released version on local environment
