### ISSUE TITLE
Rename serverlibs to domainlibs module, change packaging [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3733]
### Problem Description

Dependabot requires a pom.xml to evaluate your Java dependencies. It had expected to find one at the path: /sormas-base/dependencies/serverlibs.pom/pom.xml.

![grafik](https://user-images.githubusercontent.com/23217632/101635237-f6959380-3a29-11eb-8d53-58f4ee35dcf3.png)

Additionally, also IntelliJ does not like a POM that it not named `pom.xml`

### Proposed Solution

- We probably have to change our serverlibs.pom to `sormas-domainlibs/pom.xml` (pom.xml file as a module beside the others), rename the module to `sormas-domainlibs`.
- Move also the assemblyLibJar.xml and assemblyZip.xml into that subdirectory.
- Refactor it also in Ant scripts to still be able to deploy on local DEV system (rename target to deploy-domainlibs).
- Check that nothing breaks in Shell scripts.

### Possible Alternatives

- Keep naming `serverlibs` to not have too much refactoring with all the packaging and setup.

**Comment by StefanKock** [comment]
One remark here: If Dependabot only wants to find dependencies, this change is not needed since all dependencies are listed `sormas-base/pom.xml`. Considering this I do not see a benefit doing this.

**Comment by JonasCir** [comment]
@tbroyer FYI regarding `serverlibs.pom`

**Comment by tbroyer** [comment]
Thanks for the ping @JonasCir.

IntelliJ IDEA doesn't quite like the `serverlibs.pom` either. In #3728 I also renamed it to `pom.xml` for that reason; and I see no reason for not naming it `pom.xml`. Might be even better to maybe move it around too, say, to a `sormas-serverlibs/pom.xml` at the root of the project next to the other `sormas-base`, `sormas-api`, etc. modules.

**Comment by JonasCir** [comment]
Also, fixing this will improve maven package caching in the CI see https://github.com/hzi-braunschweig/SORMAS-Project/pull/3732
