### ISSUE TITLE
Error when sorting facilities or regions (by facility type or population)

### ISSUE THREAD

**Issue by chThie** [hzi-braunschweig/SORMAS-Project#3737]
### Bug Description
Sorting some columns in the "Configurations" menu results in an error.
The affected columns are "Facility Type" in the "Facilities" tab and "Population" in the "Regions" tab.

### Steps to Reproduce
1. Go to "Configurations".
2. Click the "Regions" (or "Facilities") tab.
3. Click on the column title "Population" (or "Facility Type") to sort it.
4. -> "An error has occurred".

### Expected Behavior
The columns should be sorted as expected: "Population" numerically and "Facility Type" probably alphabetically.

### Screenshots
![regions_bug](https://user-images.githubusercontent.com/34276062/101655129-872b9e00-3a41-11eb-833a-cb23ebdb982a.png)
![facilities_bug](https://user-images.githubusercontent.com/34276062/101655135-898df800-3a41-11eb-9ef9-c204de394a35.png)

### System Details
* SORMAS version: 1.52.1 (Release Candidate) and 1.51.1 (Latest Release)
* Android version/Browser: Firefox
* Server URL: https://demoversion.sormas-oegd.de (1.51.1) and Testserver(1.52.1)
* User Role: combined role (Surveillance Supervisor + Contact Supervisor + Clinician)

**Comment by StefanKock** [comment]
Just reproduced on https://test.sormas.netzlink.com/sormas-ui/#!configuration/regions with 1.53.0-SNAPSHOT

**Comment by StefanKock** [comment]
I found these three issues:
```
# Region population column (not a field directly in Region entity)
... 
Caused by: java.lang.IllegalArgumentException: population
	at de.symeda.sormas.backend.region.RegionFacadeEjb.getIndexList(RegionFacadeEjb.java:155)
...
```

```
# District population column (not a field directly in Region entity)
... 
Caused by: java.lang.IllegalArgumentException: population
	at de.symeda.sormas.backend.region.DistrictFacadeEjb.getIndexList(DistrictFacadeEjb.java:154)
...
```
```
# Facility facilityType (attribute not mapped for sorting)
...
Caused by: java.lang.IllegalArgumentException: type
	at de.symeda.sormas.backend.facility.FacilityFacadeEjb.getIndexList(FacilityFacadeEjb.java:435)
...
```

**Comment by StefanKock** [comment]
Sorting by `Facility.type` enabled, no sorting by population (more complex data model).

**Comment by AndyBakcsy-she** [comment]
Verified issue on local environment on the latest SORMAS Version: 1.53.0-SNAPSHOT version
