### ISSUE TITLE
Improve documentation of facility import in the Data Dictionary

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3739]
### Bug Description

The documentation of type `FacilityReference` describes only the special strings NO_FACILITY and OTHER_FACILITY. The Data Dictionary does not cover the import of configured facilities.

### Expected Behavior

 The use of the name of a facility configured in SORMAS should be documented here

### System Details
* SORMAS version: 1.53.0-SNAPSHOT

**Comment by chThie** [comment]
Only slightly related, but users struggle with the documentation of the health facility field, since it is required even if the imported case does not stay at a health facility ("NO_FACILITY"), which is not intuitive: #3755

**Comment by syntakker** [comment]
@chThie not just slightly related, but exactly this issue :-) I was in contact with one of them.
See description of the pull request https://github.com/hzi-braunschweig/SORMAS-Project/pull/3740#issue-535548756,
This explanation is (or will be) shown in the Data Dictionary in two places: case and person. It also describes how to import stays in existing health facilities.

**Comment by kwa20** [comment]
@syntakker @chThie #3398

**Comment by syntakker** [comment]
These three issues should be considered together:
#3398, #3755, #3739

**Comment by syntakker** [comment]
These three issues should be considered together:
#3398, #3755, #3739

**Comment by AndyBakcsy-she** [comment]
Vaidated the changes in the Data Dictionary document on the latest version of SORMAS Version: 1.54.0-SNAPSHOT
