### ISSUE TITLE
 Modify the "responsible surveillance officer" field in an event file

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3751]
### Feature Description

To date, the event directory has a lot of information characterizing the event, the people involved in the event and the actions carried out.

In a context of strong viral spread, the number of events to be investigated is large. In order to facilitate the distribution of the signals to be investigated between the different investigators, we suggest displaying the name of the person in charge of the investigator (by modifying the "Responsible surveillance Officer" field)

### Problem Description

To date, only the names of people with the "responsible surveillance officer" profile appear in the drop-down list. However, in France, the persons in charge of the investigation are at the regional level and therefore have the contact supervisor profile.

### Proposed Change

- Modification of the “responsible surveillance officer” field which to date does offer the option for only “Surveillance Officer”. We suggest that this list be supplemented by the "surveillance supervisor" role in addition, in order to be able to display the name of the person in charge of investigating the event.

- In terms of the events directory:
o we modify the Surveillance Agent filter to have the label "responsible user" and it proposes the list of agents and supervisors (with the possibility of entering the first letters as in the creation of a task for example)
o add a "responsible user role" filter on the supervisor or agent role.
o If you select a role, it limits the people proposed by automatic completion in the responsible user filter but you can search for a person without having indicated a role beforehand
- Integration of this field in all exports

### Additional Information
@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
* on event information form, replace responsible surveillance officer with a generic name called "responsible user"
* This drop down will display the names of all users in the jurisdiction of the event with any of the following roles: surveillance officer, surveillance supervisors.
* It should be possible to also search the name of the user here and choose the right one. 
* Order the names with surveillance officers in the district of the event at top of list, other SO and then supervisors follow.

* On event directory
* Add another filter for responsible user role
* replace filter for responsible surveillance officer with responsible user 
* Both filters should be able to work together or independently, ie if i first filter by  responsible user role, then the options presented in responsible user should have the corresponding roles else not.

* add responsible user and user role to export

NB even though event are public, only users in the jurisdiction of the event can be assigned as responsible users.

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin @emond-fuseau

In my opinion, this is not a problem. This will make it possible to visualize the events which have not yet been attributed to an investigator and thus facilitate the distribution of the signals to be investigated between people. Perhaps it would be possible to provide for the empty field in the filter? What do you think ?

**Comment by bernardsilenou** [comment]
It should be possible to filter entities with NA values for the variable used for filtering (responsible user and responsible user role == NA).

**Comment by carolinverset** [comment]
> It should be possible to filter entities with NA values for the variable used for filtering (responsible user and responsible user role == NA).

@bernardsilenou @ftavin
Yes i'm agree with you !

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske Any further refinement from you?

**Comment by MateStrysewske** [comment]
@Chinedar Is this fine for you as well? Or should we rather make this configurable because it would be problematic for Nigeria to have Contact Supervisors in this list?

**Comment by bernardsilenou** [comment]
@MateStrysewske @Chinedar  Since this is only about events that are open to everyone, i do not see any issue for now.
For cases and contacts, this solution will not be good for Nigeria.

**Comment by bernardsilenou** [comment]
for cases and contact we may need to make it configurable, but we are not there yet. 
We wait to hear from Chinedu also before proceeding to implementation.

**Comment by Chinedar** [comment]
@MateStrysewske @bernardsilenou best we make it configurable. The prompt associated with investigating events cannot be going out to contact supervisors. Maybe later, when this is agreed nationally, but for now, it will not be suitable.

**Comment by bernardsilenou** [comment]
@Chinedar we already send out investigation tasks to supervisors in case there is no officers in the district. This is not my main worry. 
You know the event officer role is a regional user role, similar to supervisors, if we do not include supervisors on this list, then then we are somehow limiting them from being the responsible person of the event. We should have a reason why we add a limitation to a user role, tight?
There is also this associated issue: #3794 which makes it more logical to have the supervisors in the list of responsible users.
I will call you later, its better to discuss by phone.

**Comment by Chinedar** [comment]
@bernardsilenou so if I get you clearly, the supervisor at the regional level becomes aware of all events in all the districts within his/her region? Then this is fine. I've looked at #3794 as well.

**Comment by bernardsilenou** [comment]
In summary:
1. We implement for event as it is: ie responsible surveillance officer is rename responsible user and has options to choose a surveillance officer or a supervisor
2. In case there is a need to have a similar logic for cases, contacts or event participants, then we absolutely need to add a parameter to configure this.

The optimum option would be 2, but this may need more changes to be done that we may not have the resources for now. For example we would need to rename all responsible surveillance officers to responsible users for also cases and contacts.

Hope everyone give a thumb up!

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg Dev France plan to work on this story for 1.54

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin

Do you see a downside to adding the name of the person responsible for the event in the events and actions directory? This would make these two pages even more useful.
thanks for your quick return

**Comment by bernardsilenou** [comment]
@carolinverset Just as on case directory, I think we can add the "reporting user" and "responsible user"

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou The developper has just finished the dev this afternoon, I think this confirmation is a bit late if we want to have it on time for 1.54 (end of PR validation on thursday...)
I propose to create a separate issue to have these columns in 1.55 and keep this issue as it for 1.54

**Comment by carolinverset** [comment]
@ftavin 
yes i'm agree with you. I'll create a new issue pour the second part of this work

**Comment by MateStrysewske** [comment]
@ftavin @carolinverset @alexandre-gille It's very likely that we won't have an internal feature freeze on Thursday this time around, but rather on Friday or maybe even Monday because of some very important things that we need to take care of during this sprint. That also means that we can again use Friday as the deadline for anything coming in from France, so we have a bit more time. :)

**Comment by ftavin** [comment]
@MateStrysewske thank you for this excellent news ! (but you should not have informed @alexandre-gille, he works way better under pressure !)

**Comment by MateStrysewske** [comment]
@bernardsilenou Quoting you:
`Order the names with surveillance officers in the district of the event at top of list, other SO and then supervisors follow.`

While I agree that it makes sense for specific countries to also assign supervisors to events, I don't think it makes any sense to be able to assign surveillance officers from different districts. The whole purpose of jurisdictions is to divide responsibilities, and adding other SOs would render that system pretty much obsolete. Is there any specific reason why you suggested to do it exactly like this?

**Comment by MateStrysewske** [comment]
Also @bernardsilenou @carolinverset What's the exact purpose of the "responsible user role" filter in the events directory? What exactly would you use that for?

**Comment by MateStrysewske** [comment]
@bernardsilenou @Chinedar About the configuration: Right now, Event Officers can't be assigned to events as their responsible user. I suspect that is the case for a reason, i.e. they're responsible for REPORTING the event, but NOT for investigating it. If that's not the case and the process is actually different, it's been implemented in the wrong way the whole time.

I'm not sure whether there was a potential misunderstanding between you two - this issue means that Surveillance Supervisors will be assignable as the responsible users for events. It's not about getting notified about their existence or anything like that. Is that still fine for you @Chinedar, or do you think we need a configuration to turn that on/off because of your first comment in this issue?

**Comment by Chinedar** [comment]
@Mate Strysewske <mate.strysewske@vitasystems.de>
Yes, the event officers are responsible for reporting the event and not
investigating it. This process is correct.
For the issue at hand, this is fine by me. thanks.

**Comment by MateStrysewske** [comment]
@bernardsilenou @carolinverset Any updates concerning my questions?

**Comment by carolinverset** [comment]
Sorry @MateStrysewske to have failed to answer. 

Initially, French users did not report the need for this filter. I think that the purpose was to reduce proposed the list of responsible usernames. In France, most of the users have the same profile so there will be no impact for us. It was a suggestion from @bernardsilenou if I'm not mistaken

**Comment by MateStrysewske** [comment]
Okay, I would suggest to remove that filter then because I don't really think it's necessary right now - there are only two possible user roles that can be assigned to events anyway. Is that fine for you?

**Comment by bernardsilenou** [comment]
@MateStrysewske Are you talking about replacing filter for responsible surveillance officer with filter for responsible user (surveillance officer + supervisor)? If Yes, then that is fine.

I also think there is no need to add the event officer among option to be selected as responsible user.

**Comment by MateStrysewske** [comment]
@bernardsilenou That doesn't answer my question, unfortunately. Again, this is a quote from you:

> Order the names with surveillance officers in the district of the event at top of list, other SO and then supervisors follow.

According to this, the list of potential responsible users for an event should consist of
a) surveillance supervisors
b) surveillance officers of the event's district
c) surveillance officers from OTHER districts

I don't think that's a good idea because it contradicts our jurisdiction system. I would suggest to only include surveillance supervisors of the event's region and surveillance officers of the event's district. My question was why exactly you suggested this specific change.

**Comment by bernardsilenou** [comment]
@MateStrysewske Sorry for that adding "other SO" was a mistake, I do not also think we should do that. Please drop it.
Since SO's are the often the default responsible users, can we use this order:
a) surveillance officers of the event's district
b) surveillance supervisors in event region

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.55.0.snapshot on the Web. 
Remaining for validation the mobile app

**Comment by raghupola-vg** [comment]
Tested and Verified also on Mobile app.
