### ISSUE TITLE
[SORMAS2SORMAS] Trying to share samples results in an error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3762]
### Bug Description
When  'share samples' is selected in the share window, trying to send it results in an '400 bad request' error.
### Steps to Reproduce
1. open a case with a sample.
2. select 'share sample' in the share window and hit share.

### Expected Behavior
case should be shared with the sample (and pathogen test result).
### Screenshots
<img width="731" alt="Screen Shot 2020-12-13 at 12 45 04 PM" src="https://user-images.githubusercontent.com/70317594/102010872-1afeb200-3d41-11eb-8b3d-884f03a71b05.png">

<img width="299" alt="Screen Shot 2020-12-13 at 12 30 07 PM" src="https://user-images.githubusercontent.com/70317594/102010846-ebe84080-3d40-11eb-9a8b-defe92a14535.png">

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de; release-de.sormas.netzlink.com
* User Role: admin, national user

**Comment by vidi42** [comment]
Cannot reproduce with 1.53.0-SNAPSHOT. This will be solved in the next release
