### ISSUE TITLE
[SORMAS2SORMAS] Introduce Re-selecting an instance to re-share data [5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3763]
### Situation Description
When data has been shared with another instance already, the selection option disappears from the drop down menu. It is, therefore, impossible to re-share an updated version or even hand over the ownership retrospectively.
### Feature Description
Introduce the option to re-select and re-share data with another Sormas instance. This will allow users to update the case data that they've previously sent and for example share samples plus test result if they haven't been available previously. Users can then also hand over the ownership of the case retrospectively if applicable for any reason. If the data has been shared before, the user should have to go through a prompt to verify that overwriting the sent data is desired.

This feature should be disabled when the ownership has initially been handed over and only be available again, if the receiving Sormas instance returns the case.

### Screenshots
<img width="1056" alt="Screen Shot 2020-12-13 at 12 34 08 PM" src="https://user-images.githubusercontent.com/70317594/102011040-138bd880-3d42-11eb-9119-6343e38f46a3.png">
<img width="1055" alt="Screen Shot 2020-12-13 at 12 36 05 PM" src="https://user-images.githubusercontent.com/70317594/102011047-18e92300-3d42-11eb-83ab-9b6fb5138a72.png">

**Comment by vidi42** [comment]
This seems to have been implemented like this on purpose. It's similar on Contacts as well.
@markusmann-vg any idea why this behavior was intended? And is this request still a Bug or more of a Change Request

**Comment by markusmann-vg** [comment]
As we don't have versioning yet or merging processes included, you cannot share a case again with the same instance you already shared it with. Please add a new story for this use case. @kwa20

**Comment by kwa20** [comment]
@markusmann-vg I have adjusted this issue to be a feature request. I hope that is fine.

**Comment by markusmann-vg** [comment]
- [ ] check wether "send case to another instance and send it back" can be reused for updating a case on the recipient side

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.54.0-SNAPSHOT
