### ISSUE TITLE
Update dependencies of sormas-app [3]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#3765]
### Problem Description

The tech stack of sormas-app is a bit behind and needs specific addressing apart now after #3584.

### Proposed Change

1. Update gradle version to 7.x ~~6.x~~ and gradle plugins.
2. See commit abc4802 about reduced compile dependencies.
3. Check all other dependencies.

**Comment by MartinWahnschaffe** [comment]
I have updated the description above - we should directly use the latest gradle 7.x. See #6699

**Comment by StefanKock** [comment]
Jenkins build fails:
```
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project sormas-app: Execution default of goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke failed: Plugin org.fortasoft:gradle-maven-plugin:1.0.8 or one of its dependencies could not be resolved: Could not find artifact org.gradle:gradle-tooling-api:jar:7.0.3 in gradle (https://repo.gradle.org/gradle/libs-releases-local/) -> [Help 1]
```

**Comment by StefanKock** [comment]
All CI problems solved.
