### ISSUE TITLE
Update to Keycloak 12 [3]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#3766]
### Problem Description

Update to Keycloak 12 when available, see https://github.com/keycloak/keycloak/releases.

### Proposed Change

1. Update Maven dependencies concerning Keycloak and review open points of #3580.
2. Push relevant infos to SORMAS-Docker for update to Keycloak 12.

**Comment by JonasCir** [comment]
https://github.com/keycloak/keycloak/releases
Seems to be released
