### ISSUE TITLE
[SurvNet Interface] Entering external Id results in an error when trying to send data to SurvNet

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3767]
### Bug Description
When an external Id is entered in a case, sending case data to the SurvNet results in an error.
### Steps to Reproduce
1. Create a case without entering the external Id.
2. Send case data to the corresponding SurvNet instance.
3. Enter an external Id and save.
4. Try sending data again.

### Expected Behavior
Sending the external Id to the SurvNet instance should be possible and appear as the 'Aktenzeichen' in SurvNet.
### Screenshots
<img width="602" alt="Screen Shot 2020-12-14 at 9 20 37 AM" src="https://user-images.githubusercontent.com/70317594/102057724-aa15d380-3dee-11eb-97e2-b285a44a0626.png">

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by HolgerReiseVSys** [comment]
This has already been fixed in deveopment.
For the moment the externalId field only supports the GUID and not the "Aktenzeichen".

**Comment by kwa20** [comment]
Error message does not occur anymore but external ID doesn't reach SurvNet

**Comment by JonasCir** [comment]
@kwa20 If this is a problem, could either reopen or file a new issue :)
