### ISSUE TITLE
HtmlHelper: Improve handling of tag attributes and unit tests [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#3768]
### Problem Description

1. `V7UuidRenderer.encode` this is still vulnerable to HTML injection: "<a title='" + HtmlHelper.cleanHtml(value) + "'>" . Same for V7CaseUuidRenderer, ReferenceDtoHtmlProvider, CaseUuidRenderer, UuidRenderer and also maybe other classes. 
2. No unit test at all for all this stuff before and now.
3. Constant `HtmlHelper.EventActionWhitelist` violates code convention.

### Proposed Change

1. Idea: New method `HtmlHelper.cleanHtmlAttribute("title", value)`.
2. Add unit tests at least to all methods tackled by this ticket.
3. Change constant to capaitalized letters: `EVENTACTION_WHITELIST`.

**Comment by Seal33** [comment]
1. What do you mean "vulnerable to HTML injection: """? Are titles inside <a>-Tags not allowed to be empty?
I see generally missing sanitizing in CaseUuidRenderer, V7CaseUuidRenderer and UuidRenderer.

2. What kind of tests would you suggest? Maybe calling the methods with invalid html and checking if the returned string is properly cleaned?

3. You're right, this should be an easy fix

**Comment by StefanKock** [comment]
Waiting for Github CI to finish, and then I will merge this.
