### ISSUE TITLE
Replace labels with new Android captions where possible [?]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#377]
- [ ] check with which fields this is possible
- [ ] remove label from these fields and also remove the surrounding linear layout

**Comment by MartinWahnschaffeSymeda** [comment]
Let's wait with this until Orson has submitted the pull request for the app design changes

**Comment by MartinWahnschaffeSymeda** [comment]
This is no longer valid. The new design doesn't allow us to use android style field captions.
