### ISSUE TITLE
Nullable action status creates error in event actions tab

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3771]
### Bug Description
The action status is nullable and creates an error where the event actions tab will appear empty (his issue is similar to #3609).
### Steps to Reproduce
1. Go to any event.
2. Create an action, deselect the action status and save.
3. Navigate to the event actions tab.

### Expected Behavior
The action status should not be nullable to prevent this error.
### Screenshots
<img width="610" alt="Screen Shot 2020-12-14 at 12 53 01 PM" src="https://user-images.githubusercontent.com/70317594/102080698-32a46c00-3e0f-11eb-9286-ad32dd8f30d0.png">
<img width="1110" alt="Screen Shot 2020-12-14 at 12 52 44 PM" src="https://user-images.githubusercontent.com/70317594/102080666-27e9d700-3e0f-11eb-84c1-9a647fe3bc05.png">
<img width="365" alt="Screen Shot 2020-12-14 at 12 52 35 PM" src="https://user-images.githubusercontent.com/70317594/102080677-2d472180-3e0f-11eb-9a9c-65f97142ef5a.png">

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
@bernardsilenou @ftavin @carolinverset This is something I think you in particular should be aware of since you use this feature a lot. I also did not find a work around for this one yet because you can only edit the actions inside of the event action tab which makes re-selecting the status impossible after the error occurred.

@MateStrysewske This might be more serious than initially expected.

**Comment by bernardsilenou** [comment]
@kwa20 Thanks for finding this bug. 
We would correct this bug but in 1,53 I hope. It is not too bad to do a hotfix for this only.
We may need to migrate  Null action statuses to pending

**Comment by raghupola-vg** [comment]
Tested and issue is Fixed on latest version
