### ISSUE TITLE
Evaluate sortability for generated properties

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#3772]
### Situation Description

Currently, generated properties such as participant count and case count on the event overview are not sortable. This is true in many other cases too.

### Feature Description

It should be evaluated wether (and how) these properties can be made sortable.

### Additional Information

See #2016 too.

Relevant for #3367

**Comment by StefanKock** [comment]
Scope of this ticket needs to be better defined. Is it only about events?

**Comment by StefanKock** [comment]
The problem with the sorting not in the database is likely, that it does not really sort deeply with lazy loading as a user might expect. As far as I can see it, this approach sorts only the chunk currently requested.

**Comment by DavidBaldsiefen** [comment]
@StefanKock 
> The problem with the sorting not in the database is likely, that it does not really sort deeply with lazy loading as a user might expect. As far as I can see it, this approach sorts only the chunk currently requested.

Yes that is correct, however as a user i would think that the list i currently see is also the list that will be sorted if i click on one of the columns. Does it make an actual difference though? As far as i can see the returned list can (in theory) be infinetely large at the moment. I would see the bigger problem if we had pagination for example.

> Scope of this ticket needs to be better defined. Is it only about events?

It was inspired by the specific requested use case where Events couldn't be sorted by participant, case and deathcount. My original way was to find a general approach that could be used in other cases with similar problems too, but I found that the getIndexList-Methods are often too specific, so that it might make sense to use this issue just for the event properties (and keep it in mind if the problem comes up anywhere else)

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen As a user, I expect the whole list to be sorted, e.g. if I'm looking at the case directory with 20,000 entries, I expect the sorting to take into account all these 20,000 entries. This works fine with in-database sorting, but it won't work with sorting the result of the query because that result will only contain a subset of the 20,000 entries due to the lazy loading. As a result, only that subset will be sorted, and that will result in false sorting.

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske I am not sure. If I, as a user, set some filters etc. and then receive a resulting subset of the total database containing all the entries which fit my filters, I would expect that sorting only sorts that subset. Or does the `getIndexList` method only show _some_, but not _all_ entries fitting my filters? Then of course it would make a difference if I sort the table afterwards.

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Yes, getIndexList only loads some of the entries depending on the amount of entries in the list because it's lazy-loaded. If the user scrolls down in the list, the next set of entries is loaded again, and so on.

**Comment by DavidBaldsiefen** [comment]
Ah, now I understand the problem. Then I guess you're right and it won't work. Do you happen to know at what amount of entries the next dataset is loaded? Then I would just test it out locally

**Comment by DavidBaldsiefen** [comment]
I will close this as no solution was found.
