### ISSUE TITLE
Change layout of case information and menu bar [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3776]
### Feature Description
Case information and menu bar.
### Problem Description
Some fields are placed in sections on the case information that would fit better in other positions in regards to meaning and workflow.

### Proposed Change

- To be more logically associated with other fields on the case form, switch the position of 'prohibition to work' and 'nosocomial outbreak' including the related fields. Leave 'sharedToCountry' in between the two.
- Move 'blood/organ/tissue donated' down to additional medical information.
- Move the responsible surveillance officer underneath the follow-up status comment because it's currently placed under additional medical information.
- Move reinfection plus date of previous reinfection underneath the disease.
- Move the persons menu button in between tasks and cases. This better fits the workflow of users.

### Additional Information
<img width="1151" alt="Screen Shot 2021-03-08 at 3 06 23 PM" src="https://user-images.githubusercontent.com/70317594/110332136-3ddaf280-8020-11eb-8e55-ee3de40f236c.png">
<img width="598" alt="Screen Shot 2021-03-08 at 2 30 42 PM" src="https://user-images.githubusercontent.com/70317594/110331271-323afc00-801f-11eb-917b-7b1a91e0fd9c.png">
<img width="965" alt="Screen Shot 2021-03-08 at 2 39 38 PM" src="https://user-images.githubusercontent.com/70317594/110331443-69a9a880-801f-11eb-8e40-faa987144cc7.png">
<img width="186" alt="Screen Shot 2021-03-08 at 2 51 59 PM" src="https://user-images.githubusercontent.com/70317594/110331470-73cba700-801f-11eb-85ec-e4e26ed73ae3.png">

**Comment by kwa20** [comment]
As part of this issue, also reposition the newly introduced Blood/Organ/Tissue donation field to the additional medical information below the vaccination section.

**Comment by kwa20** [comment]
@JaquM Any further additions?

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.59.0-SNAPSHOT on test-de.sormas.netzlink.com
