### ISSUE TITLE
The ExternalJournalService.shouldNotify() does not work as expected

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3779]
### Bug Description

The method checks whether an external journal needs to be notified about changes of person data. When a relevant field is updated within a Contact, the method should return true. Currently, it does not. One can therefore also see that updates of relevant data in SORMAS is not forwarded to climedo.

### Expected Behavior

The method should return true if relevants fields were updated.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

The method is probably called too late. It needs the previous relevant person data, as well  as the updated relevant person data.

**Comment by AndyBakcsy-she** [comment]
Validated issue by checking that when dropping a contact in sormas, the status is changed in climedo to ineligible.
Used the latest version of SORMAS Version: 1.53.0-SNAPSHOT
