### ISSUE TITLE
Responsible Region and District are not mandatory for contacts

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3784]
### Bug Description

For Contacts the entering of the responsible region and the district are not mandatory if you are entering the contact at case contacts:

![grafik](https://user-images.githubusercontent.com/74791118/102183666-7a2e0500-3eae-11eb-9a70-cf6ceca15674.png). 

If this entries are missing the user cannot see the contact in the list unless they haven "national"-rights.

### Steps to Reproduce
1. Open a case
2. Go to the contacts tab
3. entering a new contact

### Expected Behavior

The fields must be mandatory and contacts without a responsible region and district must be visible for all users.

### System Details
* SORMAS version: 1.52.1
* Android version/Browser: FF 83.0

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis This is expected behaviour. The responsible region and district are only mandatory if the contact does not have a source case; otherwise, if there's nothing filled in for the responsible region and district, the region and district of the case is taken instead.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Then it is a bug that this function is not working. I just tested it and took a case where the region and district are filled:

![grafik](https://user-images.githubusercontent.com/74791118/102186671-3ee20500-3eb3-11eb-8646-f1b42846e757.png)

I went to contacts and new contact

![grafik](https://user-images.githubusercontent.com/74791118/102186726-53be9880-3eb3-11eb-94df-e4156b9ab231.png)

the fields are nor pre-filled with the data of the case:

![grafik](https://user-images.githubusercontent.com/74791118/102186803-72bd2a80-3eb3-11eb-839e-35baf11701f0.png)

and are also not used afterwards, they stayed empty:

![grafik](https://user-images.githubusercontent.com/74791118/102187724-a9e00b80-3eb4-11eb-8c02-5b509ceaaf50.png)

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis The fields are not pre-filled because it's still possible to set a different responsible region and district for a contact than for its source case. Again, if the contact fields are not filled in, the system will use the responsible region and district of the case by default for all calculations. If the contact has a source case AND the responsible region and district of the contact are filled in, these will be used instead since they overwrite what's specified in the case.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske I got it. Then it might not clear and self explaining for the users why the fields are empty. Thanks for your time and explantation.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis That's true - there's a lot of room for improvement in terms of user experience and ease-of-use that we will take care of next year. :)
