### ISSUE TITLE
Merge duplicates should require sex AND date of birth to be equal [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3787]
### Feature Description
Duplicate detection for retrospective merging considers some properties of the cases. Among others the sex and date of birth.

### Problem Description
Currently the case is considered possible duplicate when sex OR date of birth are available and equal.

### Proposed Change
Instead the logic should be an AND.
So when two cases of the same sex have a different date of birth, they should not be considered possible duplicates.

### Additional info
Consider "unknown" / should not conflict with male or sth. else

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Please confirm.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  
- two cases of the same sex but different date of birth should not be considered possible duplicates.
- for two cases with missing data (NA) for one of the variables like sex for one of the cases, then this variable should not be considered in duplicate detection.
