### ISSUE TITLE
Adopt the source case in the associated exposure after case conversion [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3788]
### Feature Description
epidemiological data in cases
### Problem Description
When contacts with a source case and an entered exposure are converted to cases, the exposure does not have the source case listed in the exposure entry right away. However, when we have a source case chosen for a contact, we can infer that the contact person was exposed to that source case during this exposure, because this is the only exposure that can be described in regards to this specific contact.
### Proposed Change
When a contact is linked to a source case and has an entered exposure in the epi data tab, automatically adopt the source case as 'name of the source case' in the subsequent exposure entry in the resulting case after conversion.
### Additional Information
<img width="1107" alt="Screen Shot 2020-12-15 at 11 32 45 AM" src="https://user-images.githubusercontent.com/70317594/102204829-a0619e00-3eca-11eb-934d-c0f97c866a63.png">

**Comment by DavidBaldsiefen** [comment]
@kwa20 How would you handle contacts with multiple exposures?

**Comment by kwa20** [comment]
@DavidBaldsiefen Inside each contact, there should only be one exposure able to be entered because it describes the exposure details concerning this one contact situation. I think it's fine then?

If a person had multiple contacts with the same source case, this should be fine right?

**Comment by MateStrysewske** [comment]
Exactly, contacts can only have one exposure. The only situation in which that's not true is if the contact existed before we introduced that limit, but we introduced it pretty soon after the initial feature.
