### ISSUE TITLE
Add detailed and custom task export [3]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3792]
First of all, thanks for the new feature of task export!!!

### Feature Description

The task export should be enclose more personal details of the case/contact. We would need the phone number, address, dob.

### Problem Description

Our department für organizing the tests is using the tasks to do it. They would need the dob, address and phone number to be exported together with the task. Otherwise the have to look up it every morning manually.

### Proposed Change

Exporting of the mentioned fields.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis Thanks fro creating this request. I have a question.
Task are usually assigned users of the system and can be related to cases, contacts, events and general (not linked to any specific entity). 
You request to have the phone number and address of the entity that the task is related to. If this is an event or general task, then this will be missing.
Please can you explain whey this is needed? I thought you would have asked for the address of the user that the task was assigned to.
Thanks

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou thats a good point. We currently uses tasks only for cases and contacts. 

e.g. the investigation officer creates a task for taking a probe on 18.12.2020 by a mobile team. This task is assigned to a user called "Mobile", as the team which is organizing the routing of the mobile swap teams shifts every day (part of the Rescue Departement).
To organize the tour the can now filter (thanks!!) the user and the due date. Then they write the details in Excel, finding out the phone number and address.

**Comment by kwa20** [comment]
@bernardsilenou With this request we should actually consider a detailed export for tasks alongside the basic one and refine all the things that should be included. As you mentioned, this will likely differ depending on the referred entity but also differ considering the diversity of task types and their implications.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis 
I just want to make sure i understand you well.
You have a user in the system called "Mobile" and you assign tasks to this user to collect sample of a case called "Ben".
Your goal is to export the task assigned to "Mobile"+ 
1. email, dob, address and phone number of "Mobile"
2. email, dob, address and phone number of  "Ben"

Do you need 1 or 2 or both ?
If it is 2, do you not also need the name of the contact person "Ben"? Ofcourse this will depend if psudonymize or not.

**Comment by Marko-ilmkreis** [comment]
The option 2 would be the best, but the name of the contact person is not 
needed in our case.

Many thanks for your help.

Am 15. Dezember 2020 15:45:52 schrieb Silelou Bernard Chawo 
<notifications@github.com>:

**Comment by bernardsilenou** [comment]
In summary
- Add detailed export for contact
- List of variables to be added to the basic export list: 
  - email
  - dob
  -  home address (region, district, community, postal code, city)
  - phone number
 
of persons linked to the entity (case, contact, event participants) of the task.

@kwa20 , @Candice-Louw @Candice-Louw  any more variables to add ?

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou @kwa20 @Candice-Louw ist there any way to push this for the next sprint?

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  we have noted it down and would consider it when planning for 1.56

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou Is there any update on this issue? We urgently need this function.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  @Candice-Louw 
I have added this ticket to be considered in the next planning meeting with a priority to it. It was not considered in the last planning as initially suggested.
I can only give you an estimated time after the planning. In about 2 weeks time. In case you get no feedback in the next 2 weeks, then just tag Candice or me

**Comment by markusmann-vg** [comment]
The solution will be done in a detailed export and **not in the basic export** as the basic export exports the list, which is shown in the UI.
Once a detailed export of tasks is available, we can also provide a custom export for tasks.

**Comment by Marko-ilmkreis** [comment]
@markusmann-vg That was the request ;.) We did not asked to replace the basic export, but to have a detailed one. This issue  is now very old. Is there any way to have it soon?
