### ISSUE TITLE
The swagger docu is not structured anymore

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3797]
### Bug Description

The auto generated swagger.yaml in the sormas-rest/target/ is not structured anymore. Every endpoint is listed under the default controller. This makes it hard to use the docu and stalls https://github.com/hzi-braunschweig/SORMAS-Project/issues/3649. 

### Steps to Reproduce
1. In you dev-system, run a sormas-base maven install.
2. Check the swagger.yaml, for example by uploading its content to https://editor.swagger.io/

### Expected Behavior

The swagger.yaml should be structured as before, for example visible in the /deploy/openapi/sormas-rest.yaml of the previous release https://github.com/hzi-braunschweig/SORMAS-Project/releases/download/v1.51.1/sormas_1.51.1.zip

**Comment by vlad-ciucescu** [comment]
Fixed in https://github.com/hzi-braunschweig/SORMAS-Project/pull/3798

**Comment by AndyBakcsy-she** [comment]
Verified on local environment on latest  SORMAS Version: 1.53.0-SNAPSHOT
