### ISSUE TITLE
Cases > Import > followUpComment not imported/visible

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3801]
### Bug Description
When importing data for Cases through the Import (CSV) feature, the `followUpComment` field is not imported to the appropriate SORMAS ´´Follow-up Status Comment´´ textbox (not visible) in the UI.

### Steps to Reproduce
1. Cases >Import > Detailed Import
2. Import Successful 
3. Data for "Follow-up Status Comment" doesn't display

### Expected Behavior
Data entered in import template shows up.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/102242483-63ad9b00-3efa-11eb-9cc3-478fc3c4cd5a.png)
![image](https://user-images.githubusercontent.com/65529128/102241921-ceaaa200-3ef9-11eb-8f1f-77eee8d8eec7.png)

### System Details
* Device: Web/PC
* SORMAS version: 1.52.1
* Android version/Browser: Chrome
* Server URL: https://release-ch.sormas.netzlink.com/
* User Role: admin

### Additional Information
Example template: Using Zürich as configured region, district and community (please use CH-configured server to test if this data is used) -
[20201211_IF_export_v1-3-2_20201208-202500_rec-49_AID2sormas_.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/5697197/20201211_IF_export_v1-3-2_20201208-202500_rec-49_AID2sormas_.zip)

**Comment by StefanKock** [comment]
Suspect: `CaseImportFacadeEjb.buildEntities` does not map the attribute correctly, but I am not confident to understand this quickly to be fixed in time. Additionally, CaseImportTest fails on my system probably due to whitespace in workspace path.

**Comment by raghupola-vg** [comment]
Verified on latest test environment and import with follow up status comment works fine.
