### ISSUE TITLE
Add quarantine related filters to the case directory [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3815]
### Situation Description
Currently, we only have the 'quarantine end' filter available in the case directory. Since quarantine can also be entered for cases, additional related filters are requested, which are already present in the contact directory.
### Feature Description
Add existing quarantine related filters from the contact directory also to the case directory:

* Quarantine status
* Checkbox "Help needed in quarantine"

**Comment by kwa20** [comment]
The filter shows CH specific values on instances with other locales:


Case tab:
<img width="213" alt="valuesQuarantineCase" src="https://user-images.githubusercontent.com/70317594/145822017-b1818bd0-cb02-4eb3-af89-238ed817a4d5.PNG">

Case directory:
<img width="370" alt="valuesQuarantineCaseDirectory" src="https://user-images.githubusercontent.com/70317594/145822018-e607c69f-a16f-47f9-bfb0-a9645dbfab6f.PNG">

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.67.0-SNAPSHOT from the development branch.
