### ISSUE TITLE
[SORMAS2SORMAS] When sending and receiving shared data, some of the modified fields don't get shared back 

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#3817]
### Bug Description
Modifying some of the fields on the second server do not move to the first server after a return of the modified case

### Steps to Reproduce
1. GA 1 creates a case
2. Send it to GA 2 with ownership
3. GA 2 adds a sample and a Task to the case and modifies lots of data (including also the region/district Facility)+ adds addresses contacts , hospitalization, epi data, symptoms.
4 GA 2 sends it back to GA1 with sample and ownership ( using the Return button on the Case page under the Event Panel)

### Expected Behavior
All modified filds should be synced back 
### Screenshots
![Differences_when_sharing_cases 1](https://user-images.githubusercontent.com/70562142/102467019-76d67d00-4058-11eb-8b95-524bcfcee6a5.jpg)
![Differences_when_sharing_cases 2](https://user-images.githubusercontent.com/70562142/102467035-7a6a0400-4058-11eb-9ba5-34467a589b2e.jpg)
![Differences_when_sharing_cases 3](https://user-images.githubusercontent.com/70562142/102467048-7d64f480-4058-11eb-9c61-0ab166e28aea.jpg)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
this might be related to #3608

**Comment by AndyBakcsy-she** [comment]
Trying to share to case one more time from GA1 to GA2 brings up an error message:
![image](https://user-images.githubusercontent.com/70562142/102468685-8656c580-405a-11eb-9c89-82e0d3cff800.png)

**Comment by raghupola-vg** [comment]
tested and the data is now visible after case is returned. works fine.
