### ISSUE TITLE
Error in epidemiological data for users without a language set

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3826]
### Bug Description
The source contact list in the new epidemiological data section returns an error when a user without a user language tries to access it. The reason is the following line of code (SourceContactListEntry:108):

`new Label(DateHelper.formatLocalDate(contact.getLastContactDate(), UserProvider.getCurrent().getUser().getLanguage()));`

This should rather be:

`new Label(DateHelper.formatLocalDate(contact.getLastContactDate(), I18nProperties.getUserLanguage()));`

**Comment by AndyBakcsy-she** [comment]
verified on local environment on SORMAS-Version: 1.54.0-SNAPSHOT
