### ISSUE TITLE
Adding the dob to the person details on right top

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3827]
### Feature Description

The date of birth (plus age) should shown on every page of the person (contact and case).

### Problem Description

Currently the short information, which person is open shows only the name, but not the date of birth:

![grafik](https://user-images.githubusercontent.com/74791118/102580130-4f39f000-40fe-11eb-93c3-7a47b8e82747.png)

### Proposed Change

As there could be many persons with same or similar names it would be nice to see the date of birth and age on one view, not only by opening the person details.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis 
Please can you have a look at version 1.53 here 
https://test.sormas.netzlink.com/sormas-ui/
It would be good if you can work with this design and add a bigger screenshot of what you mean

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou 

![grafik](https://user-images.githubusercontent.com/74791118/102613336-9510ab80-4132-11eb-81e1-b2bd18571642.png)

The new design looks very good!

It would be a good idea if you could add the dat of birth between the name and the case ID on the top. So that it looks like

UserC TEST to case Gen1 Case - 01.01.2000 (UOQENM)

**Comment by bernardsilenou** [comment]
I got it now and it makes sense because we can heve two people with the same name.

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou @kwa20 do you think we can have this feature in 1.53? It would be very helpful.

**Comment by kwa20** [comment]
@bernardsilenou @Marko-ilmkreis I agree that it'll help differentiating people with the same name. However, I'm not sure if the date's location makes sense. The heading describes the entity itself, in this example the contact, therefore it could be mistaken for the date of last contact. I would therefore suggest to put it behind the contact persons name. Since it'll get quite lengthy then, we could also think about only showing it, when persons with the same name exist in the database.

**Comment by bernardsilenou** [comment]
@kwa20 The DOB would only show if the entity is linked to a person, thus not need for events. The issue with confusing dob with last contact date is bot a big issue because  dob would always be in the past, thus speak for itself.
I think your suggestion to directly attach dob after the name of the person is good.

**Comment by MateStrysewske** [comment]
I'm not quite sure about this. It's true that the DOB is always in the past, but so is the last contact date/report date. This will start to get confusing when either a) the person is very young (take Congenital Rubella as an example) or b) the user is looking at a case/contact from several years ago for some reason.

**Comment by Marko-ilmkreis** [comment]
Maybe a solution could be to write "dob." or for German "geb." before the date in smaller letters, so its clear.

**Comment by bernardsilenou** [comment]
The French team raised the need to have dob also at the header, thus the same request from two different angles.
@Marko-ilmkreis  Please can you add a mockup based on your last comment so that the Franch dev team can have a look?
@ftavin @carolinverset

**Comment by Marko-ilmkreis** [comment]
Here are two mockups. One is with written word dob (or geb in German.) and the second with a '*' as the international sign for dob. The star had the nice affect that its short and understandable without any translation.

![mockup englisch](https://user-images.githubusercontent.com/74791118/103769936-77de4700-5025-11eb-8f7d-55ec1046e103.png)
![mockup stern](https://user-images.githubusercontent.com/74791118/103769937-7876dd80-5025-11eb-846a-626daada0e8a.png)

**Comment by MateStrysewske** [comment]
I like the solution with the star!

**Comment by carolinverset** [comment]
Great. thank you bcp for these mockup.
I also plead for the second version with *.
Do you confirm that the purpose is to insert the dob for cases, contacts and people participating in the event?

In any case, having the dob is a frequent request in France with a large number of homonyms 

So, THANK YOU !! 

@ftavin @bernardsilenou

**Comment by Marko-ilmkreis** [comment]
@carolinverset yes, wo would need it for cases, contacts, participants and in future for the person entity.

**Comment by bernardsilenou** [comment]
If possible, can we use date formats like 01.Jan.2020 in order not to confuse users who a familiar with other date formats

**Comment by kwa20** [comment]
@bernardsilenou I assumed this will just conform to what the date format for the selected language is.

**Comment by bernardsilenou** [comment]
OK, then all is fine

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest version of SORMAS Version: 1.54.0-SNAPSHOT on the test.sormas.netzlink.com environment
