### ISSUE TITLE
Fragen zur Erreichbarkeit des technischen Supports für den 3rd-Level SORMAS-Support

### ISSUE THREAD

**Issue by SPoC-Netzlink** [hzi-braunschweig/SORMAS-Project#3828]
Sehr geehrte Damen und Herren,
für den Betrieb unserer technischen Hotline für SORMAS benötigen wir dringend Informationen von Ihnen. Es wäre gut, wenn Sie uns möglichst schnell eine Rückmeldung geben können.

1. Wie lautet die Support-E-Mail Adresse für den 3rd-Level-Support für SORMAS?
2. Wie ist die telefonische Erreichbarkeit für den 3rd-Level Support (Support-Nummer)?
3. Gibt es über Weihnachten, Silvester und zwischen den Fest eine Notfallbesetzung? 
4. Welchen SLA-können sie uns zur zusichern? 
  
Vielen Dank! Bei Fragen können Sie mich gern kontaktieren.

Mit freundlichen Grüßen
Lutz Ludwig
IT Service Manager 
____________________ 
Netzlink Informationstechnik GmbH
IT-Campus Westbahnhof
Westbahnhof 11
D-38118 Braunschweig
Telefon: +49 531-7073430
Telefax: +49 531-7073459
eMail: lludwig@netzlink.com
www.netzlink.com

**Comment by MateStrysewske** [comment]
@SPoC-Netzlink This doesn't belong in our development GitHub. As far as I know, we've already received your questions and have either answered them or will answer them soon.
