### ISSUE TITLE
[DEMIS2SORMAS] Deletion concept for DEMIS messages

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#3830]
### Situation Description

SORMAS is able to import labMessages from DEMIS. Downloading 1816 messages from a demis test server and storing the in the SORMAS db increase the db size from 53MB to 63MB. As several thousand labmessages per week might be a realistic scenario, it may be necessary to delete old labmessages under certain circumstances (e.g. the deleted labMessages should be processed).

Also, there may be a data protection requirement to delete labMessages from demis after a certain period of time. This should be clarified with HZI. In this regard, it should be kept in mind that labMessages may later not only be used for DEMIS imports. So if it is decided to delete labMessages after a certain period of time, this time period should be configurable, as labMessages from other systems may have other regulations.

### Feature Description

- [ ] determine if and when labMessages should be deleted
- [ ] implement a configurable approach to fulfill the deletion concept

### Possible Alternatives

One could also think about additionally shrinking the size of a labMessage.

**Comment by FredrikSchaeferVitagroup** [comment]
I asked HZI and got the general deletion concept for SORMAS-X as orientation for when to delete lab messages.
That probably is not feasible, as labmessages are not meant to be only for german systems.

I propose to delete labmessages after a configurable period of time which defaults to 90 days.
Maybe we should somehow warn before deleting unprocessed labmessages?

Also, manual deletion of person data should be possible. This probably means, that if a user wants to manually delete data of a specific person, labMessages are also affected. We probably need to store the relation of labMessages and persons (or related Cases, Contacts and EventParticipants).

Like that, we should also meet the demand of the deletion concept for SORMAS-X.

**Comment by bernardsilenou** [comment]
@FredrikSchaefer I do not know it I understand you well, I have these comment about this phrase 
"_Also, manual deletion of person data should be possible. This probably means, that if a user wants to manually delete data of a specific person, labMessages are also affected._".

- lab messages + samples even though they come from and are link to a person, their deletion is not determined by the person but by their associated entities (can be more then one for a contact that become a case as a result of of a positive lab test)
- the only instance when we delete a person is when we delete the last entity referenced by the person

- Deleting the entity delete the associated samples + messages, Is this what you meant?

**Comment by markusmann-vg** [comment]
Will be done with: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4553
