### ISSUE TITLE
hospitalizedPreviously can be deselected with exisiting entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3836]
### Bug Description

hospitalizedPreviously (YES) can be deselected even when an entry has been made in the subsequently appearing list. De-selecting or Re-selecting to NO or UNKNOWN results in the entry being gone (possibly deleted?)

### Steps to Reproduce
1. Open any case and select YES for hospitalizedPreviously.
2. Make an entry and save.
3. De-select YES or Re-select.
4. Select YES again and check the entry.

### Expected Behavior
The YES/NO/UNKNOWN field should be disabled when an entry exists in the list and only be enabled again when all entries are deleted.
### Screenshots
<img width="558" alt="hopitilizedYes" src="https://user-images.githubusercontent.com/70317594/102615319-fd14c100-4135-11eb-9511-7aefbf29afbf.PNG">
<img width="468" alt="hospitalizedNo" src="https://user-images.githubusercontent.com/70317594/102615325-fede8480-4135-11eb-8795-648efa0bf472.PNG">
<img width="469" alt="hospitalizedYesAgain" src="https://user-images.githubusercontent.com/70317594/102615329-00a84800-4136-11eb-9ff8-60f1253972e9.PNG">

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
tested on latest version and issue is Fixed.
