### ISSUE TITLE
Add task type filter to Task Management [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3842]
### Problem Description

Thus far, it is not possible to filter the task management directory by task types.

### Proposed Change

Add a task type filter that allows filtering the directory by task type next to task context

### Acceptance Criteria

When the task context is selected in the directory the according task types can be selected as well. 

### Additional Information

The task types are dependent on the task context, 
If you preselect the context you should only see the available types from this context
If you do not select a context you can see all the available types

**Comment by Marko-ilmkreis** [comment]
This feature is still requested, especially with the high rates of infection currently and the workload in the health offices.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(5150221).
