### ISSUE TITLE
ENLARGE your action description and comment

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#3848]
**Note :** despite its title this issue is not a spam ;)

### Feature Description

In the events, actions have two fields for description and comments. Those fields are Rich Text fields.

### Problem Description

The maximum size in the database for those fields is 4096 characters. This is not enough for the users with or without formating (but the formating induce hidden characters so the problem is even worst with it)

### Proposed Change

This two fields should be changed to type Text in the database, or at least have a bigger number of characters if we want to limit the size.

@carolinverset @bernardsilenou @MateStrysewske

**Comment by bernardsilenou** [comment]
Thumb up form my side. 
I think we just need to think of performance issues before deciding on the option to use.

**Comment by ftavin** [comment]
@MartinWahnschaffeSymeda can you give your opinion on the two options ?

**Comment by bernardsilenou** [comment]
Dev France plan to work on this story for 1.54

**Comment by MateStrysewske** [comment]
@ftavin "text" is definitely the way to go here. This should be the default anyway.

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest version of SORMAS Version: 1.54.0-SNAPSHOT
