### ISSUE TITLE
Show latest test result for event participants [2]

### ISSUE THREAD

**Issue by chThie** [hzi-braunschweig/SORMAS-Project#3853]
### Feature Description
In the _event participants_ view for a single event it should be possible to see the latest test result of each participant.

<img width="1440" alt="participants-test-result" src="https://user-images.githubusercontent.com/34276062/102781044-4d3e8e00-4397-11eb-9802-6074f891f28e.png">

- [x] Add the column (result & (sample date)) 
- [x] Add the filter

### Problem Description
When a contact officer handles an event, the _event participants_ list does not show which test results the participants have.
One has to click on every participant to find out which ones were tested positive, since they should probably prioritized for follow-up calls. 
### Proposed Change
Create a column ("Latest Test Result") in the event participants view, that shows the result/status (_positive/negative/pending/indeterminate_) of the latest test result for each participant.
If no test is registered yet, show "None" or, better: "Not tested yet".

This column should (at least optionally) be included in the export of the list.
### Additional Information
This issue is created in consultation with @kwa20, based on feedback of German public health departments.

=> Use the final lab result that has a result of the latest sample (sample date)

**Comment by bernardsilenou** [comment]
I would suggest we add a filter for this variable rather than a new column, since this directory is based on the event participant while the test results are related to samples. We would need to describe the use cases before deciding i suppose.

**Comment by kwa20** [comment]
@bernardsilenou @chThie I like the approach to add a filter instead because we can then also easily apply it to other entities like cases and contacts.

**Comment by chThie** [comment]
I think the request was based on the use case of contact officers handling a local event and wanting to have an overview where they can see the test status for their event participants. They want to be able to export it as well.

By adding a filter you mean a filter field at the top where one can filter for e.g. positive cases? That would not exactly match what the health department asked for I think, since it does not allow to show an overview.

Could we add a button “Show test results” to the event participants view that jumps into the sample directory and filters it by the event, so that we see a list of the participants’ test results?

**Comment by bernardsilenou** [comment]
@chThie From your last comment, it seam as the users need to do some form of a basic analysis to get what they want. Adding a filter would not solve the needs of the users.
@kwa20 I would suggest we implement the issue on adding the "event participant directory" + detailed export of this directory.
The detailed export would include the latest 3 samples and their final lab results

**Comment by kwa20** [comment]
@bernardsilenou @chThie This issue is not necessarily related to an analysis but rather associated with a workflow of mass entering data. Events are entered which have a very high number of event participants. These events are often large screenings with thousands of participants. Therefore, work forces are split to either enter laboratory results of these participants or create cases for the positive tested persons. The column/filter would enhance this process by allowing the users to sort/filter the list by the status of the latest test result (which would be the final test result by the way). I actually think that we should add both, the filter and the column because sorting might not be enough.

I agree that implementing the event participant directory would make sense in relation to this issue, however, implementing this one first might be much easier.

**Comment by bernardsilenou** [comment]
@kwa20 Understood. 
1. Do the users  always know the event that the ep belongs?
2. After filtering by latest lab result, the users may also need a filter for event participant status, ie  "active", "converted to case", "closed". Such that combining these 2 filters would help them to know the ep with positive lab results that have not been converted to cases. If yes, then I see the  need to add the ep stutus attribute to the ep entity.
3. Here is the summary:
     - Add the ep statuts to  ep: active, converted to case, closed, when ep is linked to a case, set satus to converted to case 
     (and vice versa). Just as we have for  contacts
     - Add columns for ep status, on the ep directory (For recent test result, it would be good to have just a filter since it is not a direct attribute of the the ep entity, we should also think of performance issues)
     - Add filters for ep status and test result on the ep sub directory within the event

**Comment by bernardsilenou** [comment]
@kwa20 These are just comments i can think of now but I think it would be nice that we have a followup discussion in person

**Comment by Candice-Louw** [comment]
@Marko-ilmkreis - would this approach be sufficient from your perspective, or would you like to add additional information, please?

**Comment by Marko-ilmkreis** [comment]
@Candice-Louw In my opinion it would be more helpful to have the row with the test result then the filter. This gives an better overview for the user. Maybe the performance issues can be handled better if we introduce for the ep also a detailed view of the list, like for contacts and cases.

**Comment by JaquM** [comment]
I would also show the date of this sample in addition to the result. Events are often tested multiple times, so the date is very important here.

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as there is an error : 
Predicate pathogenTestResultWhereCondition = cb.equal(subRoot.get(Sample.ASSOCIATED_EVENT_PARTICIPANT), eventParticipant.get(EventParticipant.ID));
