### ISSUE TITLE
Text in german language cut off in epi data view

### ISSUE THREAD

**Issue by chThie** [hzi-braunschweig/SORMAS-Project#3856]
### Bug Description
In the epidemiological data view of cases the text of the german language version is cut off and a part of it is not readable.

### Steps to Reproduce (german language setting)
1. Go to _"Fälle"_ (cases).
2. Click on a case. 
3. Switch to the _"Epidemiologische Daten"_ (epi data) tab.

One text reads _"Bitte dokumentieren Sie ALLE relevanten direkten Expositionen (z.B. besuchte Versammlungen, Reisen, Tierkontakte usw.) während d"_ and _"er Inkubationszeit:"_ is cut off.
Another one _"Wohnen oder Arbeiten in einem Gebiet mit hohem Übertragungsrisiko der Krankheit, z.B. in geschlossenen Wohn- und Cam"_ and _"p-ähnlichen Umgebungen"_ is cut off.

### Expected Behavior
If the text is too long for the line (since it is limited to save space for the box displaying the source case), it should break.
So we should probably use multi-line fields with a limited width and a flexible height for the texts.

### Screenshots
<img width="1370" alt="german text cut off" src="https://user-images.githubusercontent.com/34276062/102800742-92bd8400-43b4-11eb-8813-bf0e47b6f0d6.png">

### System Details
* OS: Mac OS 
* SORMAS version: 1.52.1
* Android version/Browser: Firefox
* Server: demoversion.sormas-oegd.de
* User Role: -

**Comment by Candice-Louw** [comment]
Duplicate of: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3659 ?

**Comment by chThie** [comment]
> Duplicate of: #3659 ?

Yes, sorry. Forgot to search for this before creating the issue. Will close this one.
