### ISSUE TITLE
Case follow-up date is not updated if the report date is changed after creation

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3864]
### Bug Description

- a) If a case is saved and the report date changes in the past (e.g. misstyping) the follow-up-date is not updated.

- b) If you try to fix it manually, you must first save case with the new report date and afterwards you can overwrite the follow-up date manually. If you do it in once there will be an error.

### Steps to Reproduce

for a)
1. create a case and set the report date on 21.12.2020
2. open the case and set the report date on 01.12.2020 for the test
3. the follow-up-date is not updated
4. set the report date on 23.12.2020 - > the date is updated

for b)
1. create a case and set the report date on 21.12.2020
2. open the case and set the report date on 01.12.2020 and try to set the follow-up-date on 26.12.2020

### Expected Behavior

The follow-up date should be updated in any case automatically.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/102967872-26956a00-44f3-11eb-8f1a-ae1ed87231b7.png)
![grafik](https://user-images.githubusercontent.com/74791118/102967865-24331000-44f3-11eb-9351-7262c861f67f.png)

### System Details
* SORMAS version: 1.54-snapshot and 1.52.1

**Comment by AndyBakcsy-she** [comment]
Validated both scenarios on the latest version of SORMAS Version: 1.54.0-SNAPSHOT
