### ISSUE TITLE
Wrong title for confirmation dialog of cancelling follow-up by bulk edit

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3869]
### Bug Description

If you cancel up the follow-up by bulk-edit for contacts it shows a confirmation deletion dialog, in English and German. This is consusing.

### Steps to Reproduce
1. open contact list
2. enter bulk edit mode
3. mark contacts and select "cancel follow up"

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/102991817-45f3bd80-451a-11eb-8b2b-82ddc3c57b17.png)
![grafik](https://user-images.githubusercontent.com/74791118/102992107-e4801e80-451a-11eb-963d-2cf7688290fe.png)

### System Details
* SORMAS version: 1.52.1

**Comment by kwa20** [comment]
@Marko-ilmkreis thanks for the feedback. This issue was resolved with #3686.
