### ISSUE TITLE
Contacts > Contact Directory > Filter by 'Symptom Journal Status' inaccurate results

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3870]
### Bug Description
When filtering Contacts (follow-up visits view) by 'Symptom Journal Status', results include values outside the desired filter.

### Steps to Reproduce
1. Contacts > Contact Directory > Follow-up Visits view
2. Show more filters > Add any filter for 'Symptom Journal Status' > Apply Filters
3. Results are not filtered

### Expected Behavior
Results include only Contacts with the associated Symptom Journal Status.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/103003204-a7bf2200-4530-11eb-9785-cd2160b99f8f.png)

### System Details
* Device: Web/PC
* SORMAS version: 1.52.1, 1.53
* Android version/Browser: Chrome
* Server URL: https://release-de.sormas.netzlink.com/
* User Role: admin

### Additional Information
Tested for the PIA Symptomtagebuch.

**Comment by bernardsilenou** [comment]
Can someone tell me the where I can find the issue with the meaning/definitions of the categories of the symptom journal status?? 
I do not get the difference between the default state (NA) and "unregistered".  Should unregistered not be unknown??
What does deleted status mean?
I have a feeling we need to restructure these categories
Thanks

**Comment by bernardsilenou** [comment]
I talked with @Candice-Louw  and now understand the meaning of the variable.
-In order to be consisted with naming used for contact status (#1855), It would be good to rename Deleted to "Closed" and keep all the other names as they are.
- fix the bug in the filter

**Comment by Candice-Louw** [comment]
@bernardsilenou - https://github.com/hzi-braunschweig/SORMAS-Project/issues/1970

Possible status codes:
UNREGISTERED: User has not yet sent any state (never sent by PIA, just internal state in SORMAS)
REGISTERED: After succesfull registration in PIA
ACCEPTED: User has accepted the In-App confirmation
REJECTED: User has rejected (declined) the In-App confirmation
DELETED: User was deleted in PIA (=UNREGISTERED?)

PIA ensures following status changes:
UNREGISTERED -> REGISTERED -> DELETED
UNREGISTERED -> REGISTERED -> ACCEPTED or REJECTED -> DELETED

**Comment by AndyBakcsy-she** [comment]
validated the filter functionality on SORMAS Version: 1.54.0-SNAPSHOT on https://ga1.sormas-oegd.de/sormas-ui
