### ISSUE TITLE
Contacts > Contact Directory > Empty date range 'From... to' results in error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3871]
### Bug Description
Removing the dates 'from... to' for Contacts (follow-up visits view), results in an error.

### Steps to Reproduce
1. Contacts > Contact Directory > Follow-up Visits view
2. Remove dates in 'From... To'
3. Error

### Expected Behavior
No error / warning message / other proposed solution?

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/103007942-9546e780-4534-11eb-8c26-4864cbee0003.png)

### System Details
* Device: PC/Web
* SORMAS version: 1.53
* Android version/Browser: Chrome
* Server URL:  https://release-de.sormas.netzlink.com/
* User Role: admin

### Additional Information
Tested with PIA Symptomtagebuch configuration.

**Comment by bernardsilenou** [comment]
I think we should show an error massage saying "Please specify a valid date range"

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest version of SORMAS Version: 1.54.0-SNAPSHOT
