### ISSUE TITLE
Missing lastContactDate in contact import results in missing follow-up calculation

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3873]
### Bug Description
Contacts can be imported with a missing date of last contact. This, however, is stated as a required field for the import. If this field is left empty, the calculation does not fall back to the report date and just never gets calculated until the lastContactDate is given.
### Steps to Reproduce
1. Import contacts without a lastContactDate
2. Check Follow-up section

### Expected Behavior
Follow-up should also be calculated when contacts were imported, conform to how it is done via a normal contact creation.
### Screenshots
<img width="435" alt="contactImportFollowUp" src="https://user-images.githubusercontent.com/70317594/103018640-e01d2b00-4545-11eb-8ea8-68437d493a46.PNG">
<img width="278" alt="contactImportFollowUp2" src="https://user-images.githubusercontent.com/70317594/103018643-e14e5800-4545-11eb-8b71-47d16a1f7a5f.PNG">

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
* date of last contact should not be a required field when importing contacts because it is not required when creating contacts from front end.
* Recalculate followup until date each time the contact, case or event participant entity is saved (initial creating + update). 
* The same need as in #3864, thus implement both as one

**Comment by kwa20** [comment]
@bernardsilenou you're right, the problem here is not lastContactDate not being a required field but the missing initial calculation of the follow-up when the contact was created via import

**Comment by raghupola-vg** [comment]
Tested by importing a contact and works fine on latest build.
