### ISSUE TITLE
mSERS > Configuration to enable/disable feature

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#3876]
### Feature Description
![image](https://user-images.githubusercontent.com/65529128/103087380-9553ef80-45e7-11eb-8dc8-5b410c806290.png)

### Problem Description
The mSERS (Aggregate Reporting) feature is seldomly used in central European contexts.

### Proposed Change
Hide this/make configurable to have the feature deactivated and not visible similar as done for Tasks https://github.com/hzi-braunschweig/SORMAS-Project/issues/3552 and Outbreaks https://github.com/hzi-braunschweig/SORMAS-Project/issues/3171

**Comment by kwa20** [comment]
@Candice-Louw mSERS can be enabled/disabled with the already existing feature configuration AGGREGATE_REPORTING.

**Comment by Marko-ilmkreis** [comment]
@kwa20 is it also possible to disable "Meldungen" with the existing feature configuration?

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Could you please tell us the English term of what exactly you're referring to?

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske the english term is Reports:

![grafik](https://user-images.githubusercontent.com/74791118/103638085-b2c07c00-4f4c-11eb-8b91-39633571d5a7.png)

**Comment by MateStrysewske** [comment]
WEEKLY_REPORTING is the feature configuration that can be used to disable this part of the app.

**Comment by Candice-Louw** [comment]
@Marko-ilmkreis - please could you send me your contact details when convenient? 😄 candice.louw@helmholtz-hzi.de

**Comment by nk-designz** [comment]
@kwa20 
Could you please tell me why these options aren't available in the UI?
To me this doesn't look like a thing meant for system administrators.
Thanks :)

**Comment by MateStrysewske** [comment]
@nk-designz Basically because we didn't have the opportunity to build a UI for it yet. It's definitely planned to allow users to configure this from the UI in the future, of course.

**Comment by Candice-Louw** [comment]
@rafaelpaffenholz - configuration changes that may be of interest for Kt. BE (and further CH) servers.  Please try on test server first, though.

**Comment by Candice-Louw** [comment]
@michadavid - I believe 'Reports' is what you would also like to have hidden on your servers, right?  (WEEKLY_REPORTING needs to be set to 'f')

**Comment by michadavid** [comment]
@rafaelpaffenholz, do you agree?
