### ISSUE TITLE
Add an entity line to the database export files [0.5]

### ISSUE THREAD

**Issue by GD-ZH** [hzi-braunschweig/SORMAS-Project#3879]
### Bug Description

I noticed that in the Sormas export "visit_symptoms.csv" several columns are named exactly the same! These are:
•	id
•	changedate
•	creationdate
•	uuid
•	sys_period
 
In addition, the duplicated columns contain different content. I have attached an excerpt from the table where this can be seen.
 
Luckily, these symptoms seem to be related to the contact persons, which we have not used yet. In the other exported tables, this problem is not present.
 
Can you please check and correct this issue?

### Steps to Reproduce
1. Statistics
2. Download Database

### System Details
* Device: Laptop
* SORMAS version: 1.52.1
* Android version/Browser: Microsoft Edge, Version 87.0.664.66 
* Server URL: https://zh.sormas.ch/sormas-ui/#!statistics/database-export
* User Role: Admin, National User

### Additional Information
[visit_symptoms.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5747822/visit_symptoms.xlsx)

**Comment by MateStrysewske** [comment]
The second occurrence of these columns are the id, change date, creation date, ... of the visit itself for reference purposes. This was requested at some point in the past. We probably have to add an entity line to the CSV files to make it more obvious where individual columns belong.

**Comment by vlad-ciucescu** [comment]
Does the entity line mean a new row containing the names of the entities to which each column belongs?

**Comment by MateStrysewske** [comment]
@vlad-ciucescu Exactly

**Comment by AndyBakcsy-she** [comment]
Validated issue on the latest version of SORMAS Version: 1.54.0-SNAPSHOT on ga1 enironment
