### ISSUE TITLE
Filter on event directory to filter events linked to a facility

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3887]
### Situation Description
When the type of place variable in connection with the block will be reviewed (issue # 3617) and the API call (issue # 2416) will provide the names of facility in a standardized way , the event directory can be filtered on the "facility type", facility category ". The text search field will also make it possible to search for all the signals relating to the same facility based on its name.
The idea is to further refine this management of the event directory by proposing the development below.

### Feature Description
From the event file, create a button / link allowing access to the event directory automatically filtered on all the signals coming from the same facility (see link allowing access from the event page to the case / contact directory automatically filtered on the event)
This development can only be done after the finalization of issues #3617 and #2416

### Additional Information
@ftavin @bernardsilenou

**Comment by ftavin** [comment]
@carolinverset do you really want "filtered on all the signals coming from the same community" as you say in the feature description or "filtered on a facility" as you say in the title ? (I think the 2nd one is the good one)

**Comment by carolinverset** [comment]
@ftavin 
Google translate made me a joke :-)
YES I'm talking about a filter on the facility.

**Comment by ftavin** [comment]
@carolinverset can you edit the initial description to correct this point ?

**Comment by bernardsilenou** [comment]
@markusmann-vg, @MateStrysewske  Dev France works on this for 1.54

**Comment by AndyBakcsy-she** [comment]
VAlidated ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on test.sormas.netzlink.com
Filtering on Facility will display the events associated to that facility
