### ISSUE TITLE
Enhance availability of pathogen test information [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3890]
### Feature Description
pathogen tests of samples; samples in entities; sample directory
### Problem Description
Thus far, users have to navigate to every individual sample to get details of their pathogen tests. This is a pesky process and does not provide a good overview of the documented pathogen tests.

Furthermore, the CT/CQ-value, which is important information for PCR's and CQ Value detection tests, is quite hidden inside the individual pathogen test results. This value aids in inferring the viral load and should therefore be made more readily available to users.
### Proposed Change
To make information about pathogen tests more readily available and minimize the navigation the users have to undertake to gather information, I propose the following changes:

- When inside entities (i.e. cases, contacts, event participants), samples should display information about the latest pathogen test if this information is available (latest = testDateTime). If the pathogen test was a PCR or CQ Value detection test, the CT/CQ value should also be shown if available. The number of tests that were done for this sample should also be shown.

- When inside of a sample, PCR or CQ value detection tests should also display the CT/CQ value if available.

- In the sample directory, columns should be added for "latest pathogen test" and "number of tests". According to what was mentioned previously, PCR and CQ value detection tests should also display the CT/CQ value in parentheses. Columns should be sortable.

### Additional Information
<img width="665" alt="pathogenTestInfo" src="https://user-images.githubusercontent.com/70317594/103370379-f2aadd80-4acc-11eb-813e-b63472edfd8d.PNG">

### Development Specifications
* Add the following information to the sample list entries in cases, contacts and event participants (probably requires some moving around of existing entries to make sure that the entries don't take too much vertical space):
    * The number of pathogen tests associated to that sample
    * A "Latest (created) pathogen test" heading, and below that:
        * The type of test
        * The date of the test
        * If the test type is PCR_RT_PCR or CQ_VALUE_DETECTION, show the CQ value
* Add the following information to the pathogen test list entries in samples (only if available):
    * CQ Value
    * Tested disease variant
* Add two columns to the sample directory (make sure that the columns are sortable or, if not possible, sorting is disabled for them):
    * Latest (created) pathogen test (shows the test type and, if available, the CQ value in brackets)
    * Number of tests

**Comment by Iheanacho2027** [comment]
In addition, the generic name of "laboratory" be changed to "laboratory/facility" in order to state where Rapid Antigen tests were conducted. This is because rapid antigen tests are not necessarily conducted in labs, they can be conducted in homes, military facilities etc @bernardsilenou @Chinedar

**Comment by kwa20** [comment]
We might want to consider adding facility selection options to samples then.

**Comment by bernardsilenou** [comment]
@Iheanacho2027 For samples we only need facilities that can do any of the pathogen test, thus may not be good to have all facilites as options to the sample. If there is a local test unit in a community for rapid test, I would suggest that you  just create them in the system as a lab.
There is already a filter for the lab on sample directory that we can use

**Comment by Marko-ilmkreis** [comment]
@kwa20 Thank you for this issue. If this could be implemented it would be very good. As mentioned in #4495 , the user currently does not have a good overview about the results and ct-value.

**Comment by maxiheyner** [comment]
@kwa20 The user asks for displaying the virus variant next to "positive" of pathogen samples, too.

**Comment by kwa20** [comment]
@maxiheyner Showing the disease variant in pathogen tests or samples is another issue I suppose because this would require variant documentation is respective entities. Thus far, we only document the variant in the case information.

**Comment by bernardsilenou** [comment]
@maxiheyner Please do not forget to create an issue for that. 
Showing variant on the case and not on pathogen test is not consistent.

**Comment by maxiheyner** [comment]
@bernardsilenou #4633 is now ready :)

**Comment by markusmann-vg** [comment]
@kwa20 We consider the "latest" to be the last created.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT on test-de.sormas.netzlink.com environment

**Comment by kwa20** [comment]
@AndyBakcsy-she @ChristopherRiedel I tested this ssue on test-de2.sormas.netzlink.com and received an error when trying to sort the 'number of test results' column. It was also not clear to be how the latest pathogen test column is being sorted, I didn't receive an error for this column though.

<img width="866" alt="NumberOfTestsSortingError" src="https://user-images.githubusercontent.com/70317594/126970653-326e2fc3-fa2c-4141-8cf7-fb7244555fa4.PNG">

**Comment by StefanKock** [comment]
@ChristopherRiedel is working on disabling the sorting for the corresponding columns because a query sorting is not possible.
