### ISSUE TITLE
Variable for "set all symptoms cleared to No" in import template doesnt work in 1.53.0 (follow-up on #2030)

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#3894]
### Bug Description
As a follow-up for #2030, I noticed that the variable "symptomatic" has been added to the import dictionary but doesnt reflect during the import exercise. Pls can this be made to take effect as its needed urgently
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
#2030 hasn't actually been implemented yet.
