### ISSUE TITLE
No "bulk edit" mode on Admin surveillance supervisor account  

### ISSUE THREAD

**Issue by Iheanacho2027** [hzi-braunschweig/SORMAS-Project#3904]
### Bug Description
The bulk edit mode is missing on the admin surveillance supervisor user account both on the samples and case directory
### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version: 1.53.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AndyBakcsy-she** [comment]
Reopening issue as This was not implemented for Admin Surveillance Supervisor

**Comment by cazacmarin** [comment]
Closes #3904

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest version of SORMAS Version: 1.54.0-SNAPSHOT

**Comment by kwa20** [comment]
Admin Surveillance Supervisor has bulk edit access in samples directory but no rights to delete samples. Since this is the only bulk action available thus far, it does not serve any purpose this way.
