### ISSUE TITLE
Expression fields for campaign data forms in Android app [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#3905]
### Situation Description
Requires #3067 and #2001

### Feature Description
Implement #3067 for the Android app.
Define implementation todos once #3067 is done.

**Comment by StefanKock** [comment]
Not mandatory for 1.59

**Comment by BarnaBartha** [comment]
Handle https://github.com/hzi-braunschweig/SORMAS-Project/issues/2001#issuecomment-824905844
