### ISSUE TITLE
When converting event participant into contact or case, alert the user if the disease of the event is not indicated

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#3919]
### Situation Description
The transformation of a person participating in an event into contact results in the opening of a window asking to specify the characteristics to be inserted in the contact file, including illness. If the disease was not specified in the description of the event, this field will be empty and cannot be modified, even though it is a mandatory field.

### Feature Description
Since the disease of the event cannot be a mandatory field, we propose to develop an alert message asking the user to specify the illness of the event.

### Additional Information
@ftavin @bernardsilenou @olivierleuci

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou
Proposition for the text of the alert:
_It is not possible to create cases from an event participant if the desease of the event has not been set_

**Comment by bernardsilenou** [comment]
I added the option to do the same for cases
_It is not possible to create a contact from an event participant if the disease of the event has not been set_
and 
_It is not possible to create cases from an event participant if the disease of the event has not been set_

We also show the same warning if the user want to link a case to an event that has no disease
_It is not possible to link a case to an event if the disease of the event has not been set_

**Comment by carolinverset** [comment]
@bernardsilenou @ftavin 
ok for me. Thank you very much !

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she The contact part is probably not actually testable because we don't display events in the list of events that can be linked with a different disease than the contact's disease anyway.

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on test.sormas.netzlink.com 
Alert message was displayed when converting event participants from events with no diseases into cases.
