### ISSUE TITLE
Inconsistent behaviour of "show more/less filters" button

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#3923]
### Bug Description
The behaviour of the "show more/less filters" button is inconsistent. After applying a filter, the button says "show more filters" while all filters are still shown anyway.

![image](https://user-images.githubusercontent.com/5616564/103795690-93a61500-5046-11eb-9131-f293906c5692.png)

Besides this, the "apply filters" and "reset filters" buttons are hard to find among the filter inputs. It would help to have a layout row of their own for these buttons.
When switching to German, the layout is broken by an overflow of the line. Now there is a line break between these two buttons:

![image](https://user-images.githubusercontent.com/5616564/103795994-f697ac00-5046-11eb-8f30-fe33e47b8482.png)

### Steps to Reproduce
1. Go to case list
2. click "show more filters"
3. specify filter criteria and click "apply filters"

### System Details
* Device: Linux PC
* SORMAS version: 1.54.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: localhost
* User Role: any

**Comment by alexcaruntu-vita** [comment]
A fix for the layout for apply and reset buttons was provided [here](https://github.com/hzi-braunschweig/SORMAS-Project/pull/4146)

**Comment by raghupola-vg** [comment]
Verified on version 1.58.0-snapshot and issue is Fixed.
