### ISSUE TITLE
Update to 1.52.1

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3926]
### Bug Description
Hello,

We have an issue when updating to to 1.52.1.
Sormas stoped at the query bellow:

Updating database to version 281... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)

UPDATE epidata SET contactwithsourcecaseknown = 'YES' FROM cases WHERE cases.epidata_id = epidata.id AND (SELECT COUNT(id) FROM contact WHERE contact.resultingcase_id = cases.id) > 0

We use sormas, apache2 in container with external bdd in another server

The same update in another environment take 30min

### Steps to Reproduce
1.
2.

### System Details
* Device:
* SORMAS version:1.52.1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
@MateStrysewske @MartinWahnschaffeSymeda

**Comment by carolinverset** [comment]
@Abdi-Abdallah

**Comment by MateStrysewske** [comment]
@bernardsilenou Can you please append the whole stack trace?

**Comment by Abdi-Abdallah** [comment]
Hello,

We restored the database and restarted the update yesterday  by modifying the "start_period" and update hangs at "Updating database to version 275".
Please see the stack trace:


[dockerlog.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/5780544/dockerlog.log)


![F416E57C](https://user-images.githubusercontent.com/71712614/103872256-71f07080-50ce-11eb-9c04-db21dbdfe690.PNG)
![EDB50F4D](https://user-images.githubusercontent.com/71712614/103872285-7d439c00-50ce-11eb-98ad-7bea8209ec57.PNG)


Best regards,

Fayçal Abdi

**Comment by MateStrysewske** [comment]
@Abdi-Abdallah That doesn't seem related to the problem that Bernard reported; this somehow looks like the server isn't able to do anything in the database at all, because version 275 is not very computation-heavy...

**Comment by Abdi-Abdallah** [comment]
Hello,

Update hangs on version 275 when startup_delai is unchanged.
Sormas-docker always restarting 

CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                            PORTS                NAMES
c55032f7ecbe        hzibraunschweig/sormas-application:2.14.0   "/start-server.sh"       2 hours ago         Up 3 minutes (health: starting)   6048/tcp, 6080/tcp   sormas-docker_sormas_1

Yesterday, we fixed "start_period: 1200s", and update hangs at 281.

Best regards,
Fayçal Abdi

**Comment by carolinverset** [comment]
@olivierleuci : In view of the deployment of version 1.52.1 in production in BFC

**Comment by Abdi-Abdallah** [comment]
Hello,

We restart update after applying "start_period: 900s", and sormas is restaring

sormas_1    | [2021-01-07T11:58:16.870+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017096870] [levelValue: 800] [[
sormas_1    |   I115816.869|     > Starting automatic database update... (de.symeda.sormas.backend.common.StartupShutdownService.java:558)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T11:58:16.903+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017096903] [levelValue: 800] [[
sormas_1    |   I115816.903|     > Updating database to version 275... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T11:58:16.925+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017096925] [levelValue: 800] [[
sormas_1    |   I115816.925|     > Updating database to version 276... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T11:58:16.969+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017096969] [levelValue: 800] [[
sormas_1    |   I115816.969|     > Updating database to version 277... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T11:58:16.986+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017096986] [levelValue: 800] [[
sormas_1    |   I115816.985|     > Updating database to version 278... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T11:58:17.001+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017097001] [levelValue: 800] [[
sormas_1    |   I115817.001|     > Updating database to version 279... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T12:00:41.625+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017241625] [levelValue: 800] [[
sormas_1    |   I120041.625|     > Updating database to version 280... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
sormas_1    | [2021-01-07T12:01:32.842+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=116 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610017292842] [levelValue: 800] [[
sormas_1    |   I120132.841|     > Updating database to version 281... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]
sormas_1    |
autoheal_1  | 07-01-2021 11:13:33 Container /sormas-docker_sormas_1 (ba0dacceea90) found to be unhealthy - Restarting container now with 30s timeout
autoheal_1  | 07-01-2021 11:13:33 Restarting container ba0dacceea90 failed
sormas-docker_sormas_1 exited with code 137
sormas_1    | Waiting for sormas to start .......
sormas_1    | Successfully started the domain : sormas
sormas_1    | domain  Location: /opt/domains/sormas
sormas_1    | Log File: /opt/domains/sormas/logs/server.log
sormas_1    | Admin Port: 6048
sormas_1    | Command start-domain executed successfully.
sormas_1    | Configuring domain and database connection...
sormas_1    | No jvm-options were deleted (perhaps they never existed in the configuration)

After this automatic restart, update hangs on:

sormas_1    | [2021-01-07T12:15:00.196+0100] [Payara 5.2020] [INFO] [] [] [tid: _ThreadID=119 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610018100196] [levelValue: 800] [[
sormas_1    |   I121500.196|     > Updating database to version 275... (de.symeda.sormas.backend.common.StartupShutdownService.java:598)
sormas_1    | ]]




Best regards,
Fayçal Abdi

**Comment by MateStrysewske** [comment]
@Abdi-Abdallah I'm a bit confused by the timestamps; how long does the script try to update to database version 281 before it times out?

**Comment by Abdi-Abdallah** [comment]
Hello,

The sormas container restart automatically after 900s.
Yestarday, we set this value to "3000s" and he was  hangs at "Updating database to version 281"

Best regards,
Fayçal Abdi

**Comment by MateStrysewske** [comment]
@Abdi-Abdallah Can you tell how many a) cases and b) contacts you have on this server?

**Comment by MateStrysewske** [comment]
@Abdi-Abdallah Do you have direct database access? If so, please execute the following SQL script and try whether it works afterwards: `CREATE INDEX IF NOT EXISTS idx_contact_resultingcase_id ON contact USING hash (resultingcase_id);`
If you don't have direct database access yourself, please forward this instruction to someone who does.

**Comment by Abdi-Abdallah** [comment]
hello,

Here are the 2 counts
sormas=# select count(*) from cases; 
  count 
--------- 
 1000265 
(1 row)
sormas=# select count(*) from contact; 
 count 
-------- 
 817287 
(1 row)

Best regards,

Fayçal

**Comment by Abdi-Abdallah** [comment]
Hello,

Update is working after  upduting index.
we have this three warnings:

ormas_1    |
sormas_1    | [2021-01-07T14:14:53.716+0100] [Payara 5.2020] [WARNING] [] [javax.enterprise.system.core.security] [tid: _ThreadID=122 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610025293716] [levelValue: 900] [[
sormas_1    |   No Principals mapped to Role [SURVEILLANCE_OFFICER].]]
sormas_1    |
sormas_1    | [2021-01-07T14:14:53.717+0100] [Payara 5.2020] [WARNING] [] [javax.enterprise.system.core.security] [tid: _ThreadID=122 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610025293717] [levelValue: 900] [[
sormas_1    |   No Principals mapped to Role [CONTACT_OFFICER].]]
sormas_1    |
sormas_1    | [2021-01-07T14:14:53.718+0100] [Payara 5.2020] [WARNING] [] [javax.enterprise.system.core.security] [tid: _ThreadID=122 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1610025293718] [levelValue: 900] [[
sormas_1    |   No Principals mapped to Role [CASE_OFFICER].]]
sormas_1    |


Thanks you

Best regards,
Fayçal Abdi

**Comment by MateStrysewske** [comment]
@Abdi-Abdallah Great, thanks for the feedback! The warnings shouldn't negatively affect your server.

**Comment by GRADeS-Gwen** [comment]
The index creation also helped us to apply the update to 1.52.1 from 1.51.1. Without it, it took forever.
Our DBA also suggested us to optimise the request "281" like that : 
`UPDATE epidata SET contactwithsourcecaseknown = 'YES' FROM cases WHERE cases.epidata_id = epidata.id AND exists (SELECT 1 FROM contact WHERE contact.resultingcase_id = cases.id);`

Best regards,
Gwenaël

**Comment by MateStrysewske** [comment]
@GRADeS-Gwen Thanks for the suggestion!
