### ISSUE TITLE
Search of samples by name doesn't show event participants

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3930]
### Bug Description

If you enter an sample for a event participant it is in the list of samples can can be filtered by sample-date, but not by name. This is required as this is the only option to find a person within an event if you do not know on which they participated. 

### Steps to Reproduce
1. open en event and entering an participant
2. entering a sample for the person
3. going to samples directory 
4. enter the name in the field 
![grafik](https://user-images.githubusercontent.com/74791118/103883909-1d54f180-50de-11eb-9953-793e61cdc136.png)
5. the result is empty 
![grafik](https://user-images.githubusercontent.com/74791118/103883943-29d94a00-50de-11eb-9ed5-0df89560467c.png)
6. If you search by sample-dates, they are shown
![grafik](https://user-images.githubusercontent.com/74791118/103884063-5725f800-50de-11eb-9c4d-3fc1a5d9e3a0.png)

### Expected Behavior

Samples of event participants should be shown if you search them by name.

### System Details
* Device: Win10
* SORMAS version: 1.54-snaphot (https://test.sormas.netzlink.com) 
* Android version/Browser: FF 84

**Comment by kwa20** [comment]
cf. #2705

**Comment by JaquM** [comment]
@Marko-ilmkreis is this still relevant? Cause now there are the different columns, including the event participants.

**Comment by Marko-ilmkreis** [comment]
@JaquM as far as I see this can be closed by now.
