### ISSUE TITLE
Add phone number and email address to facilities

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3931]
### Situation Description
Thus far, it is not possible to deposit contact information for facilities in SORMAS. However, this will be very useful in case users have to contact facilities where entities are referenced, for whatever reason.
### Feature Description
Add "facility contact information" (should include phone number and email address) to the facility infrastructure data (including import template) and as fields in respective entities where facilities are referenced. The addresses list should also display the facility and facility contact information (phone number + email) so that users don't have to individually open the addresses to look for desired entries.
When facility contact information is deposited in the infrastructure data, such entries should automatically be adopted in respective fields in related entities after selecting the corresponding facility (cf. #3394).

This issue would be implemented as a follow-up step of #3390 
### Additional Information
Creation form in Configurations:
<img width="387" alt="Screen Shot 2021-01-07 at 11 14 41 AM" src="https://user-images.githubusercontent.com/70317594/103882820-a5d29280-50dc-11eb-86c0-6486c511868f.png">
Import template for facility infrastructure data:
<img width="714" alt="Screen Shot 2021-01-07 at 11 33 21 AM" src="https://user-images.githubusercontent.com/70317594/103882834-abc87380-50dc-11eb-83b0-4f43258ac8c7.png">
Facility infrastructure overview:
<img width="1105" alt="facility infrastructure3" src="https://user-images.githubusercontent.com/70317594/103882876-baaf2600-50dc-11eb-86f2-0104d95f7d01.png">
Adresses list on person forms:
<img width="733" alt="Screen Shot 2021-01-07 at 12 01 39 PM" src="https://user-images.githubusercontent.com/70317594/103885696-b1c05380-50e0-11eb-82b0-f143195e8781.png">
Place of stay in case information:
<img width="623" alt="Screen Shot 2021-01-07 at 12 05 17 PM" src="https://user-images.githubusercontent.com/70317594/103885713-b8e76180-50e0-11eb-9c99-55e280f4ccc0.png">

**Comment by kwa20** [comment]
@Lucas-Walter-GA-Tuebingen Here the follow-up issue for facility infrastructure data. Any feedback is appreciated.

**Comment by Lucas-Walter-GA-Tuebingen** [comment]
This is exactly what we need.

**Comment by bernardsilenou** [comment]
Dev France would refine and work on this for 1.54

**Comment by kwa20** [comment]
We should probably rename the headers for these fields to "facility phone number" and "facility email address" for it to not be confused with the persons contact information.

**Comment by kwa20** [comment]
Already implemented in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4755 and #4027. Additional minor differences were not requested anymore.
