### ISSUE TITLE
Add a general comment field to person entity[1]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3936]
**Issue description is outdated, please ignore everything except the development specifications**

### Bug Description

If you converting a contact into a case the general comment is not transferred and must copied manually.

### Steps to Reproduce
1. write something into the general comment
![grafik](https://user-images.githubusercontent.com/74791118/103988072-c3ac0000-518d-11eb-9836-1356458043dd.png)

2. transfer the contact into a case, the comment is empty
![grafik](https://user-images.githubusercontent.com/74791118/103988365-4b920a00-518e-11eb-9c6c-c54447a11252.png)

### Expected Behavior

The comment should be transferred into the case.

### System Details

* SORMAS version: 1.54.0-SNAPSHOT
* Server URL: https://test.sormas.netzlink.com
* User Role: Contact Supervisor

### Development Specifications
* Add a new `additionalDetails` field to persons (caption: "General comment"; `@SensitiveData` annotation)
* Add this field to the bottom of the person form and fragment (similar to how it's displayed for cases, i.e. don't show the caption of the field, but add a heading with the caption above it)
* Vaadin app: Create a `ResizableTextAreaWrapper` that allows users to extend the size of the new field; please have a look at `TextFieldWithMaxLengthWrapper` that does this (used for event description) - however, the new field should not have a max length

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis I don't actually know whether this should be the case. The general comment of a contact could very well have information that is very specific to the contact event and doesn't provide any value for the case, and vice versa. @bernardsilenou @kwa20 What's your take on this?

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske our colleagues are writing informations regarding the family in this field. So that they know who are other family members which are in quarantine. 

In my opinion it shouldn't be a problem to convert this field. If the information is not needed if could be deleted easily. Maybe a solution might be that the fiel is transferred with a prefix stating that this comes from the former contact.

**Comment by kwa20** [comment]
@MateStrysewske @Marko-ilmkreis This change was actually requested a few times. Since this field can be filled with many different entries, I understand the need for it and the advantage of not having to reenter or copy paste relevant info. However, I agree that this should not be done automatically for every conversion because adopting entries might not be desired everywhere.

Therefore, we could add a notification during the conversion of a contact to ask the user, if they want to adopt entries of the general comment field in the case that will be created.

**Comment by MateStrysewske** [comment]
@kwa20 I like that solution! Please make sure to prioritise this issue as it's not a bug and has to be fit into our schedule.

**Comment by Marko-ilmkreis** [comment]
If it would be possible to have a confirmation dialog that would be great.

**Comment by kwa20** [comment]
Notification upon case conversion:
<img width="589" alt="Screen Shot 2021-01-08 at 1 54 40 PM" src="https://user-images.githubusercontent.com/70317594/104017904-40a09f00-51b9-11eb-99d9-0868f0f9abee.png">

- Show notification when contact is being converted into a case.
- Only show this notification if entries were made in the general comment field of the contact.
- When a contact is being converted into an existing case via duplicate recognition, do not overwrite entries in the case but only add information below if "yes" was selected in the notification window.
- If this feature is not wanted elsewhere for any reason, make this a configurable change. @bernardsilenou @Candice-Louw Could you give feedback on whether this notification is also desired by other users?

**Comment by kwa20** [comment]
@MateStrysewske @Marko-ilmkreis I unfortunately cannot change the title. Could we make it conform to my last comment? e.g.: "Add option to adopt general comment entries upon case conversion"

**Comment by MateStrysewske** [comment]
@kwa20 I'd suggest to maybe not use a popup but a checkbox in the creation window that can be ticked? That's less annoying for users that generally don't want to use this feature.

**Comment by kwa20** [comment]
@MateStrysewske Great idea! I like this alternative a lot. We could only show this checkbox during a conversion process then. If this is harder to do we could also disable it (grey it out) in the normal case creation process.

**Comment by bernardsilenou** [comment]
Sorry to get late in the conversation.
- I also agree with the proposed solution and would like ask if we can extent the feature thus:
    * add general comment to person
    * trigger the same logic when converting event participant to case
   
- Maybe this is for another ticket since we do not yet have the general comment field for ep

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou when a general comment to person is introduced it should be shown a in the case person/contact person section of each case/contact referring to that person.

Maybe introduding this new field would solve the problems mentioned be me in this ticket. So the users can enter general informations to the person there and it will be shown every time, also after converting a contact into a case.

The current fiel with general comments stays like it is. Maybe a rename could be useful to make clear that its a general comment to that case or that contact only.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis I strongly support the last comment you made and would prefer we go with this solution. It would also be good that this information is easily visible on the new to be introduce overall person information page.

**Comment by kwa20** [comment]
@bernardsilenou @Marko-ilmkreis can we summarize this issue to finalize the specification? We might have to rename the title and reference the summary. My suggestions:

- Add a general comment field to persons.
- Make this field expandable as seen in the event description (helpful for clarity).

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
