### ISSUE TITLE
The temperature source is not transferred correctly from PIA to SORMAS

### ISSUE THREAD

**Issue by irinajanzen-hzi** [hzi-braunschweig/SORMAS-Project#3944]
### Bug Description
The temperature source is not transferred correctly from PIA to SORMAS.

### Steps to Reproduce
1. Create a contact person in SORMAS and create login details for the external symptom diary PIA (SORMAS-SB).
2. Fill out the COVID-19-questionnaire as a contact person in PIA and give an answer for temperature source.
3. In the call overview the temperature source is not correctly displayed:

False:
If a participant says in PIA that the temperature source was “axillary” in SORMAS it says “oral” (see screenshots).
If a participant says in PIA that the temperature source was “rectal” in SORMAS it says “axillary”.
If a participant says in PIA that the temperature source was “oral” in SORMAS it says “non_contact”.

Correct:
If a participant says in PIA that the temperature source was “non_contact” in SORMAS it says “non_contact”.

### Expected Behavior
The given answer as temperature source in PIA is correctly transferred and displayed in SORMAS ("oral" -> "oral" and so on)

### Screenshots

![PIA_Temperaturmessung_Angabe_axilar_210108](https://user-images.githubusercontent.com/75681434/104028559-266ebd00-51c9-11eb-9be4-bd051f95f548.PNG)

![SORMAS_Temperaturmessung_Anzeige_oral_210108](https://user-images.githubusercontent.com/75681434/104029265-0ee40400-51ca-11eb-99fd-6fe63b8d5428.PNG)

### System Details
* Device: PC
* SORMAS version: 1.53.0
* PIA version: 1.10
* Android version/Browser: Firefox 68.11.0esr (64-Bit)
* Server URL: https://release-de.sormas.netzlink.com 
* User Role: Contact Supervisor

### Additional Information
Contact person login details: 
name: VJHE-8741187993 
password: xpEyPp9*.NG5 (or none)

**Comment by MateStrysewske** [comment]
@FredrikSchaefer I'd suspect that this is a bug in PIA, not in SORMAS because I can't really imagine how this could possibly get mixed up in our code. Can you confirm or is this something we need to fix?

**Comment by irinajanzen-hzi** [comment]
@Candice-Louw @kwa20 fyi.

**Comment by irinajanzen-hzi** [comment]
I'll ask the PIA developers for an inspection to confirm if PIA or SORMAS causes the bug

**Comment by ghdoergeloh** [comment]
I cannot reproduce this issue. I tried it on our release system: SORMAS R 1.52.1 + PIA RC 1.11.0
I selected axilar in PIA and received axilar in SORMAS. Since R 1.8.0 there were not many changes in PIA. The only functional change I could find was the addition of `otherComplications`, `otherComplicationsText` and `shivering` to the mapping.

The only Thing I could imagine is, that the mapping inside the questionnaire is not valid.

This is the mapping in PIA

```
      switch (value) {
        case 0:
          target[key] = 'NON_CONTACT';
          break;
        case 1:
          target[key] = 'NON_CONTACT';
          break;
        case 2:
          target[key] = 'ORAL';
          break;
        case 3:
          target[key] = 'AXILLARY';
          break;
        case 4:
          target[key] = 'RECTAL';
          break;
      }
```

And the mapping in the questionnaire setting should be the same:

![image](https://user-images.githubusercontent.com/7148036/104197432-50242000-5425-11eb-80c2-4643e6f1cd41.png)

**Comment by ghdoergeloh** [comment]
I had a second look on your image and it looks like it is the setting of your questionnaire @irinajanzen-hzi 
You need to set the right code:
kontaktlos: 0/1
oral: 2
axilar: 3
rectal: 4

**Comment by irinajanzen-hzi** [comment]
Thanks @ghdoergeloh you're right, the settings were wrong in the questionnaire. Is it enough if I set the code 0 for "kontaktlos" or do I need to set the code 1 as well?

**Comment by ghdoergeloh** [comment]
just 0 is fine

**Comment by irinajanzen-hzi** [comment]
Okay perfect, I changed the settings and everything works as it should. Thanks for the support.
