### ISSUE TITLE
[SurvNet Interface] Usability improvements [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3947]
### Situation Description
Thus far, it is not possible to see how many times and when data was sent to the SurvNet instance. Further, no information or filter options are available on the directory in regards to the interface. Bulk-sending would also heavily improve usability.
### Feature Description
To improve usability and the overall workflow of using the SurvNet interface, the following things should be implemented:

- ~~Add the number of transmissions and the date of last transmission to the SurvNet Interface box in the case information.~~ -> to be done as part of #4771 
- Add a toggle for "only cases not yet transmitted to SurvNet" and   "only cases already transmitted to SurvNet". 
- Add filter "only cases changed since last transmitted to SurvNet".

Only show these filters when the SurvNet interface is configured.
- Add "Last SurvNet transmission" to the date filters in the case directory filters. Users should then be able to display cases by their date of last SurvNet transmission in a desired time period..
- Add the columns "Date of last SurvNet transmission" and "SurvNet transmission count" next to date of report. 
- ~~Add a bulk action option to the case directory to send many cases to the SurvNet instance at once.~~

### Additional Information

Pls. Consult @JonasCir or @HolgerReiseVSys  when you pick this one up

@markusmann-vg : In UI "SurvNet" should be replaced with "Reporting-SW" 

<img width="697" alt="Screen Shot 2021-01-08 at 8 00 29 PM" src="https://user-images.githubusercontent.com/70317594/104053920-698e5780-51ec-11eb-89ef-d79da55dd644.png">

<img width="906" alt="Screen Shot 2021-02-01 at 3 30 39 PM" src="https://user-images.githubusercontent.com/70317594/106472224-c2c37100-64a2-11eb-99a2-9ee5671a51f5.png">

<img width="710" alt="Screen Shot 2021-01-08 at 7 30 28 PM" src="https://user-images.githubusercontent.com/70317594/104053513-aefe5500-51eb-11eb-8800-bbdfd886ca9d.png">

<img width="415" alt="Screen Shot 2021-01-08 at 7 43 14 PM" src="https://user-images.githubusercontent.com/70317594/104053532-b9205380-51eb-11eb-964b-3994bc5a76ac.png">

**Comment by kwa20** [comment]
@HolgerReiseVSys @markusmann-vg 

@Johannes-Schmidt-GA-RT Feel free to give feedback on this.

**Comment by Johannes-Schmidt-GA-RT** [comment]
@kwa20 I think this looks very good. In the case directory we dont need necessarily the count, its it is only important whether it was transmitted. A transmission should also be entered during the initial import.

**Comment by kwa20** [comment]
bulk action handled in #3517

**Comment by kwa20** [comment]
@Johannes-Schmidt-GA-RT I think a problem we might face with transmitting data to SurvNet directly after an import is that there is no step in between to verify what will be transmitted. Do you think think filter options and a bulk action might suffice?

**Comment by Johannes-Schmidt-GA-RT** [comment]
@kwa20 Is there a possibility to transfer all data to SurvNet and retrieve it there immediately after importing from SurvNet? It's about being able to transfer all cases to SurvNet every day with bulk processing. For this purpose, all cases should be transferred once.

**Comment by StefanKock** [comment]
The whole data model and process needs to be thought throw together with/by Interactions. And it needs to be considered that transmission information is also relevant for events.

Better exclude the bulk action to another ticket: Maybe this one about transmission information, and #4257 about bulk action.

**Comment by kwa20** [comment]
@leventegal-she the strings for the filters include references of "surveillance tool", (e.g. Only cases changed since last shared with external surveillance tool), correct? I could handle it with translations but in other parts of the system it's referenced as reporting tool. Maybe we should keep it consistent?

**Comment by leventegal-she** [comment]
@kwa20 I will change all to "reporting tool" because "external surveillance tool" is too long and in some places they don't fit.

Thanks for pointing out this issue.

**Comment by leventegal-she** [comment]
* Added history of transfers instead of counting the transfers on the Case and Event detail pages
* Filters and columns added as requested on the Case directory, for Events there is another ticket

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas version 1.59.0-snapshoot on test-de1.sormas.netzlink.com environment

**Comment by kwa20** [comment]
I noticed that the column "Surveillance tool status" is not sortable on the case directory

<img width="500" alt="surveillanceToolStatus" src="https://user-images.githubusercontent.com/70317594/114877206-5ac4cb80-9dff-11eb-9f10-e48cf49881b0.PNG">

@leventegal-she I couldn't find "Surveillance tool status" or "reporting tool status" on crowdin for retranslation, not sure if I'm too impatient

**Comment by MateStrysewske** [comment]
@kwa20 We can't make the column sortable unfortunately, because it's generated in a separate query, but we'll make it unsortable to get rid of the error.
