### ISSUE TITLE
[SurvNet Interface] Limit the transmission of cases to the persons registration

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3948]
### Feature Description
SurvNet Interface - transmission of cases
### Problem Description
German health departments only report cases to the higher health institutions which are registered in their district. Often enough, cases are documented in SORMAS with a responsible region and district conform to the one of the health department but the case persons registration district differs from the responsible district. Health departments take care of such cases, however, reporting of such cases has to be done by the district that the person is registered in. Rather then sending this case data to their own SurvNet instance, the Sormas2Sormas function should be used to send this case to the department that is supposed to report the case instead. 

If users have the possibility to send cases to their own instances that other health departments are supposed to report, cases might be reported to the higher health institutions multiple times. This is critical because it would potentially increase and produce a false number of reported cases.

### Proposed Change
A limitation should be added to only allow transmission of cases to the own SurvNet instance that are registered in the departments' district. There also needs to be a way to assign an instance to a district that can be used as reference for this verification.

- If the persons home address district conforms to the district of the assigned district to the instance, normally send data to the SurvNet instance.
- If the user tries to send data to the SurvNet instance without the home address district being entered, show the following notification: "No district in the home address of the person has been entered to verify the transmission. Please check your entries."
- If the user tries to send case data to the SurvNet instance where the persons home address lies outside of the assigned district, show the following error message: "The persons home address does not conform to the district of the SurvNet instance. The case is not able to be transmitted due to risk of erroneous transmission to higher health institutions."

### Possible Alternatives
- If the persons home address lies outside of the assigned district, the SurvNet interface could stay hidden in the case information.
- If the persons home address lies outside of the assigned district, the transmission button could be greyed out and a mouseover could show the following text: "The persons home address does not conform to the district of the SurvNet instance. The case cannot be transmitted due to risk of erroneous transmission to higher health institutions."

**Comment by kwa20** [comment]
New reporting district field could be used as reference field instead (cf. #3410)

**Comment by bernardsilenou** [comment]
@kwa20 This topic was raised and discussed in early 2020. This was the reason why we added responsible jurisdiction to all entities because some departments / countries reported by the address of the person (which can be many) and others by where the entity (case) is based (jurisdiction of the hospital if case person was admitted).
- The GE users just need to make sure that all entities residing in their jurisdiction has the responsible jurisdiction set to theirs. When pushing data to SurvNet, we only push entities having the responsible jurisdiction as that of the GE.
- The GE users then need to use Sormas2Sormas  and push all other entities to their respective jurisdiction

I do not know if my comments is the solution but this sounds like something we need to discuss internally.

**Comment by kwa20** [comment]
@bernardsilenou We will still run into a problem:
- departments need to take care of persons currently staying in their district but registered somewhere else. Therefore, they need to be able to edit data and put themselves as responsible region/district to avoid pseudonymization. Such cases can then still be sent to SurvNet, even if they would need to be transmitted by other departments. Possible limitation check for transmission: responsible district = person home address district.
- We absolutely have to make sure that under no circumstances, inappropriate data is sent to the higher health institution to not hurt the reporting system. I'm afraid that we cannot rely on people to enter correct data all the time.

**Comment by bernardsilenou** [comment]
@kwa20 Understood you. Please lets refine this on Monday in person or virtually

**Comment by kwa20** [comment]
Not relevant anymore
