### ISSUE TITLE
Cases > Follow-Up Directory > Empty date range 'From... To' results in error

### ISSUE THREAD

**Issue by alexcaruntu-vita** [hzi-braunschweig/SORMAS-Project#3949]
### Bug Description
Removing the dates 'from... to' for Cases (Follow-up view), results in an error.
### Steps to Reproduce

1. Cases > Case Directory > Follow-up view
2. Remove dates in 'From... To'
3. Error

### Expected Behavior
Show an error massage saying "Please specify a valid date range".
### Screenshots
<img width="1279" alt="range error" src="https://user-images.githubusercontent.com/76100512/104068582-e120ae80-520d-11eb-8647-23754c3f4b4c.png">

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by raghupola-vg** [comment]
Tested and works fine on latest deploy.
