### ISSUE TITLE
Contact classification chart does not properly update when selected on contact dashboard

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3954]
### Bug Description
When "contact classification" is selected as data, the graph on the contact dashboard does not properly update and still shows the previously selected graph (e.g. follow-up status).
### Steps to Reproduce
1. Open the contact dashboard.
2. Select contact classification in data underneath the graph.
3. Check adequacy of the graph

### Expected Behavior
When selecting contact classification, contact classification chart should be displayed
### Screenshots
<img width="481" alt="contactDashboard" src="https://user-images.githubusercontent.com/70317594/104126795-dde90800-535e-11eb-8acf-c5c8e64d0340.PNG">

### System Details
* Device:
* SORMAS version: 1.53.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
Issue is Fixed. Chart is updated correctly on latest build.
