### ISSUE TITLE
[SurvNet Interface] Sending case data again produces new cases in SurvNet instead of updating existing ones

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3960]
### Bug Description
When cases are sent to SurvNet again, the existing case in SurvNet is not updated but a new case is created instead.
### Steps to Reproduce
1. Send a case to SurvNet again that has already been sent at least once.
2. Check the resulting cases in SurvNet.

### Expected Behavior
A case that already has been sent to SurvNet should be updated instead of newly created.
### Screenshots
<img width="672" alt="Screen Shot 2021-01-11 at 9 32 56 AM" src="https://user-images.githubusercontent.com/70317594/104159821-50ee8f00-53f0-11eb-9361-2ccdf5647c12.png">
<img width="835" alt="Screen Shot 2021-01-11 at 9 30 54 AM" src="https://user-images.githubusercontent.com/70317594/104159845-58ae3380-53f0-11eb-9425-99322fba4d52.png">

### System Details
* Device: 
* SORMAS version: 1.53.0/1.52.1
* SurvNet converter: 1.0
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by HolgerReiseVSys** [comment]
Should be fixed as the exteral id is synced back by defaut now
