### ISSUE TITLE
Samples for event participants are not shown

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3965]
### Bug Description

I had this morning the report that a user entered a sample to event participant on the weekend and the other colleagues were not able to edit it as it was greyed out. They had to enter a new sample and fill in the result there.

All colleagues of our health office having the same rights:

![grafik](https://user-images.githubusercontent.com/74791118/104185652-88bbfd80-5415-11eb-8f62-33b52f53a6bd.png)

I tested it today and opened a test-event and entered a participant and a sample with my own role. After saving there were no sample shown:
![grafik](https://user-images.githubusercontent.com/74791118/104185817-cb7dd580-5415-11eb-9ed4-7ec68917edcc.png)

I logged in with a test user and the same rights link me an the sample is shown:

![grafik](https://user-images.githubusercontent.com/74791118/104186164-55c63980-5416-11eb-83bc-09cc0bdaff51.png)

Here the rights of both users:

![grafik](https://user-images.githubusercontent.com/74791118/104186204-62e32880-5416-11eb-9322-bfaf73780cf4.png)

In the sample list is this sample not shown for both users.

I tried also by entering the sample with the test user, but the result is the same. Its not shown for me.

I took also all rights away from my user, saved, logged off and login again. Its still the same.

### System Details
* Device: PC
* SORMAS version: 1.52.1
* Android version/Browser: FF/Edge

**Comment by Marko-ilmkreis** [comment]
I found out that the difference between the test user and me is that I had in user settings selected "Covid 19" and the test user not:

![grafik](https://user-images.githubusercontent.com/74791118/104596911-f154e580-5674-11eb-8d13-69692c0b6347.png)


If I remove the desease from my user as well, I can see the samples. Is there a failure were samples event participants not get the Covid-19 flag? I found also no option to set it manually.

Colleagues reported to me that they had problems that samples were shown for evenparticipiants but greyd out.

@MateStrysewske

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis There's probably some filters that aren't working correctly with a limited disease set at the user. You shouldn't be required to set a limited disease to any user in a German system because as far as I know, Covid-19 is the only disease that's available in these systems anyway. Thanks for the information though, this will surely help us to fix this problem!

**Comment by Marko-ilmkreis** [comment]
Thank you for the information, our users always have Covid-19 preset.

I have done some tests in our live system.And after a few times of revoking and granting rights, the samples are now also displayed to my own user again. 

However, I was able to reproduce the problem of my colleagues that samples are displayed greyed out.I have created samples under my user (administrator, ReST user, national clinician, national user) and these are only displayed greyed out for the test user (monitoring manager, doctor, contact manager).  This user has set the district Thuringia and Covid-19, so thats not the reason.

It seems to me that the rights management of the samples for event participants is somewhat buggy.

![grafik](https://user-images.githubusercontent.com/74791118/104689480-dfba1f00-5702-11eb-82a3-d9a24f0a63a5.png) (greyed out sample)

![grafik](https://user-images.githubusercontent.com/74791118/104689627-23ad2400-5703-11eb-9151-7307a504cbb3.png)
(event participant)

**Comment by Marko-ilmkreis** [comment]
@sergiupacurariu this is a very annoying bug. One user enters the taken sample and the other user who needs to enter the result one day later cannot do this because its greyed out. I would request to assign it to a Sprint.

**Comment by kwa20** [comment]
I can also reproduce this on test1401 (1.53):

National User (+ Covid limited)
<img width="462" alt="nationalUserCovid" src="https://user-images.githubusercontent.com/70317594/105512654-acaef700-5cd1-11eb-97c5-7b4a3b8736aa.PNG">


National User
<img width="450" alt="nationalUserNoCovid" src="https://user-images.githubusercontent.com/70317594/105512674-b46e9b80-5cd1-11eb-8706-7a50ab6ff5ae.PNG">

**Comment by sergiupacurariu** [comment]
@kwa20 could you give me more information regarding those 4 samples you are not able to see with the Covid limited user? Like:
- what type is the user who created the event
- what type is the user who created the event participant
- what type of users created the samples marked with red in your example
- if possible would be nice a print screen with the event, event participant, and one of the red marked samples.
I'm asking all of these because I cannot reproduce this behavior on my end. Thanks!

**Comment by kwa20** [comment]
@sergiupacurariu I cannot reproduce the faulty directory display for the national user after updating to 1.54.0. As a national user, I can now see the samples on the directory and edit pathogen tests, even if I wasn't the creating user. However, this is still bugged for users with regional restrictions, e.g. Surveillance Supervisor.

Here some further information:

- the user who created the event and event participant was admin + national user.
- the user who created the sample was the national user (the one mentioned in the previous comment).
- As a Surveillance Supervisor (TestUser2), I cannot see the name of the event participant in my jurisdiction on the sample directory, even though I should.
- As a Surveillance Supervisor (TestUser2), I cannot edit samples belonging to event participants in my jurisdiction, even though I should.

TestUser2
<img width="351" alt="userTestUser2" src="https://user-images.githubusercontent.com/70317594/105705165-1ae0fd00-5f10-11eb-9639-4d805c8cd476.PNG">

<img width="729" alt="SurvSupervisorSampleGrey4" src="https://user-images.githubusercontent.com/70317594/105704946-d0f81700-5f0f-11eb-873a-b2c122168a96.PNG">
<img width="664" alt="SurvSupervisorSampleGrey3" src="https://user-images.githubusercontent.com/70317594/105704954-d35a7100-5f0f-11eb-85d0-3992e2612d52.PNG">
<img width="811" alt="SurvSupervisorSampleGrey2" src="https://user-images.githubusercontent.com/70317594/105704962-d5243480-5f0f-11eb-9c3b-2bfb6691d667.PNG">
<img width="779" alt="SurvSupervisorSampleGrey" src="https://user-images.githubusercontent.com/70317594/105704968-d6556180-5f0f-11eb-9ab5-7905527e3ec4.PNG">


I hope this helps. Please let me know if you need anything else or if something is unclear.

**Comment by sergiupacurariu** [comment]
@kwa20 The behavior you are describing happens because the sample jurisdiction is linked to events instead of event participants. 
The jurisdiction for samples will be changed to mimic what was implemented for event participants.

**Comment by kwa20** [comment]
@sergiupacurariu Does that mean that if the jurisdiction of the event participant is not given it will fall back to the event jurisdiction too? The event in the screenshot is in the jurisdiction of the user (TestUser2) who was not able to edit the sample. If the event participant jurisdiction is not given as a reference for the sample (probably often the case because it's not compulsory), do you think we might have a similar problem?

**Comment by sergiupacurariu** [comment]
@kwa20 Yes, if the jurisdiction of an event participant is not given the fall back is towards the event jurisdiction.  We need to do the same thing for samples. 
Also in case of event participants if you want to add one to an event outside your jurisdiction the responsible jurisdiction will be filled automatically with your current jurisdiction so it will be still accessible to you. If you still want to change it you will be noticed that you might lose the access to that event participant. A lot more safety checks around event participants creation.
Samples will be considered having the same jurisdiction like the event participant they are linked to. This will be implemented in this ticket.

**Comment by Marko-ilmkreis** [comment]
Maybe this could include in the hotfix for the bug which causes errors by updating to 1.53?

**Comment by raghupola-vg** [comment]
verified on version 1.55.0-Snapshot
