### ISSUE TITLE
[SurvNet Interface] external ID does not get transmitted to SurvNet

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3969]
### Bug Description
When an external ID is entered in SORMAS, it does not get transferred to SurvNet upon transmitting case data. However this is necessary in order to identify cases that were transmitted to SurvNet. Otherwise, there is no way to infer which case in SurvNet belongs to which case in Sormas, especially since there is no personal data being transmitted.
### Steps to Reproduce
1. enter an external ID in Sormas and send case data to SurvNet.
2. Check the "Aktenzeichen" in SuvNet for an external ID reference.

### Expected Behavior
Aktenzeichen should display the external ID entered in SurvNet.
### System Details
* Device:
* SORMAS version: 1.53.0
* SurvNet converter: 1.0
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by JonasCir** [comment]
@kwa20 How does this relate to https://github.com/hzi-braunschweig/SORMAS-Project/issues/3524?

**Comment by HolgerReiseVSys** [comment]
synchronizing the external id should now be enabled by default
