### ISSUE TITLE
Referring samples to other laboratories is no longer working

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#3974]
### Bug Description
Seems like it's currently not possible to refer samples to other laboratories, at least under specific circumstances (or there's missing feedback to the user why it's not possible). I tried to refer one of the samples in my system to a different laboratory as the admin user; I could open the sample creation dialog and click on save, but there was no sample created afterwards.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske had you tried to login as a different user? I had the same issue yesterday and open #3965 as an new created user was able to see the sample.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Yep, tried that, and also checked the database. The two issues aren't associated with each other.

**Comment by MateStrysewske** [comment]
I could create the referral sample today, but the reference wasn't properly stored in the original sample. Fixed that problem.

**Comment by AndyBakcsy-she** [comment]
Verified issue on test.sormas.netzlink.com on the latest version of  SORMAS Version: 1.54.0-SNAPSHOT
