### ISSUE TITLE
Date of classification for a case should be editable

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#3975]
### Feature Description
The date of classification is taken as the current date that the entity sync with the server. For retrospective data entry which happens all the time, this is not the case. Users may want to edit this date.

### Problem Description
date of classification:
*  should be editable
*  default should be NA and user has to provide a date. 
* add to import template
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/104304792-21ad5000-54cc-11eb-8902-f659dc3fbcb4.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske @Chinedar @kwa20  Any objection?

**Comment by bernardsilenou** [comment]
We have a similar design for the date of investigation also, it not provided, then we use the current date of change. I think we should just leave it blank but need to get feedback from others

**Comment by MateStrysewske** [comment]
@bernardsilenou Leaving it blank by default does not necessarily work because of automatic case classification. Also, this will potentially overwrite the date if additional information is added retrospectively if automatic case classification is triggered again. Apart from that, I don't have any objections.

**Comment by Chinedar** [comment]
@Silenou, Bernard <Bernard.Silenou@helmholtz-hzi.de> this should assume the
date of classification automatically, either by automatic classification or
manual classification. I suggest it also retains the first and initial
date, in case the automatic case classification is triggered again.

**Comment by bernardsilenou** [comment]
This change is not important to be implemented for now.
If user latter requested the need to be able to edit the date of classification, we can then revisit the ticket
