### ISSUE TITLE
Make String "./." optional for empty variables in printed documents

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3991]
If you are using the function for printing documents every empty field is set as "./.". This means for every field which might be empty or only used for some persons you have to set an if clause in Word.  Which is very annoying for two reasons:

* most of the times you have to update the field manually to get it working
* sometimes for unknown reason the function failed, SORMAS shows a message that there was an error and the complete word-file is emtpy

e.g. we need to use the field $case.person.address.additionalInformation for people which are living in retirement homes to adress an c/o. As this doesn't affect all cases/contacts we have  to have to if clauses.  One for the line feed (only line feed of field is not empty or "./") and on for the field itself (If its "./" leave it blank, if not print the data).

The best would be to leave every field which is empty just empty.

**Comment by Marko-ilmkreis** [comment]
I discovered that the failure of the function might be belong to the length of the field description.

e.g. this works
![grafik](https://user-images.githubusercontent.com/74791118/104552956-0e1ff780-563a-11eb-8c16-660100aa4704.png)

and the same with the field $case.person.address.additionalInformation  runs into the error. Word cuts the lentgh of the field if displaying it:

![grafik](https://user-images.githubusercontent.com/74791118/104553138-69ea8080-563a-11eb-873d-d6fb537c97ac.png)

Here is an excample-file: 
[case.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5812692/case.docx)

**Comment by syntakker** [comment]
The intention of the default placeholder was to provide a solution that fits most of the use cases, both in providing visible feedback for missing values and inserting something that produces an acceptable output. "./." seemed a reasonable choice to me.

An option would be to make the default placeholder customizeable. This requires to specify how this is done, e.g. on an per-instance basis via some config. Do you have a suggestion?

**Comment by Marko-ilmkreis** [comment]
@syntakker In my opinion a placeholder is not needed. Maybe the solution could be a config for the placeholder, which also allows to have none.

**Comment by syntakker** [comment]
@Marko-ilmkreis Ok. I still see arguments to have a visible indication when a mergefield is intentionally left empty (both for the creator and the receiver), but making it configurable is no problem.
I would do this via the `sormas.properties` file where all the configuration for the instance is defined. Would this do for you?

**Comment by Marko-ilmkreis** [comment]
@syntakker that would be fine. We could than ask Netzlink to set it for us. Do you think it is possible to have it for the current sprint?

**Comment by syntakker** [comment]
@Marko-ilmkreis I'm working on it :-)

**Comment by Marko-ilmkreis** [comment]
@syntakker Thank you!

**Comment by syntakker** [comment]
@Marko-ilmkreis one question: do you use nested fields - i.e. a mergefield inside an if-statement - only to blank out empty variables, or for other purposes, too?

**Comment by Marko-ilmkreis** [comment]
@syntakker Sorry for teh later reply. I wasn't in office on Friday. We are using nested fields also for the salutation in an if-statement.

e.g.
`{ IF { MERGEFIELD    $case.person.sex }="Weiblich" "Frau"   "Herrn"}`

**Comment by syntakker** [comment]
@Marko-ilmkreis thank you for the feedback!

**Comment by syntakker** [comment]
Implemented in  #4171.

**Comment by AndyBakcsy-she** [comment]
For testing porpuses all fieleds in the template should be filled for one case and then all fields should reflect in the generated template. The fields that were left out should be marked with ./.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of Sormas 1.57.0-snapshot

**Comment by Marko-ilmkreis** [comment]
@syntakker When the version is released, how can we set the string, via server configuration?

**Comment by syntakker** [comment]
One possibility is to prefix individual placeholders by an exclamation mark, which means if the variable is empty, it will not be displayed at all.
Setting a new replacement string for empty values globally is done by adding it to the `sormas.properties` on the server:
```
docgeneration.nullReplacement=./.
```
(This is the default replacement)
See also issue #4404.
