### ISSUE TITLE
Import of Contacts links to events if person is event participant

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#3999]
### Bug Description

I´m currently importing returned traveler from the last year. The import works fine so far without one point.

If the person already has a person entity and is event participant the pop-up show and asks if this is the same person. If I mark yes, the person is imported as a contact, but linked to the event. 

![grafik](https://user-images.githubusercontent.com/74791118/104570394-24d24880-5652-11eb-9513-a9d43dd88465.png)

This is wrong, because the person is a returned traveler AND event participant. The only solution is to check that a new person entity is generated.

### System Details
* Device:
* SORMAS version: 1.52.1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis This isn't technically a bug as that's the way the linking between contacts and events is working right now. It's not actually a "hard" link in the database, but it's generated. We have an issue that will take care of making sure that one contact can only be linked to one event, and that this link needs to be set manually (#3677), but until that's implemented there's nothing we can do about this, unfortunately.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Many thanks for explaining, but then its for the users an unexpected behavior which better be mentioned in the pop-up where asking if this is the same person.
