### ISSUE TITLE
Add ReST-Method to check for duplicate cases [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4004]
### Situation Description
In order to send data from other reporting systems to SORMAS we need to be able to detect potential duplicates that have already been imported or manually created.

### Feature Description

- [x] Introduce a new CasePersonDto that holds a CaseDataDto and a PersonDto. This should not extend EntityDto (it does not have it's own uuid)
- [x] Add a new getDuplicateCases method to the CaseResource that takes a CasePersonDto as parameter
- [ ] Return a list of all CasePersonDto that fulfil at least one of the following three criteria:
* A case has the same externalId
* A case has the same externalToken
* A case hast the same first name, last name, date of birth, sex (null is considered equal to any sex), disease, reportDate (ignore time), district

Do all string based comparisons lower-case and trim start/end whitspaces

**Comment by JonasCir** [comment]
@mmarzaganov The idea is that we use a function to determine the list off all person/cases that match a given person/case, where _match_ is defined by the previous bullet points. In case we have a match and can do an automatic merge, we merge, otherwise we import and users might have do manual de-duplication for the remaining duplicates.
@MartinWahnschaffe please correct me if I'm wrong

**Comment by MartinWahnschaffe** [comment]
Exactly. The merging will take place in the SurvNet converter, so it is not relevant for the implementation of this ticket.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe This specification has a similar logic to the meeting we had witht Nigerian team on sample import module.
@Chinedar @Iheanacho2027  you can use specification above.

@MartinWahnschaffe I hope you meant in your last point: A case has similar first name, last name, based on name similarity threshold, ... ie not exact name

**Comment by bernardsilenou** [comment]
Is this elated to #2549 ?

**Comment by MateStrysewske** [comment]
@bernardsilenou No

**Comment by mmarzaganov** [comment]
@MartinWahnschaffe @MateStrysewske It appears that duplicate recognition on SORMAS cannot handle Umlauts.

Example: One case has a Frank Müller und another one has Frank Mueller then duplicate recognition/merging will not work; even if all other variables are the same (e.g. gender, report date, district etc).

I am not sure, if this requires a separate issue ticket. Please advise.

**Comment by MateStrysewske** [comment]
@mmarzaganov This is almost certainly caused by Excel messing with the file encoding. The file needs to be encoded in UTF-8 _without_ BOM. As far as I know, the duplicate detection works well with Umlauts as long as the imported files are encoded properly.
