### ISSUE TITLE
CI failure due to testDetectAnnotationChangesFast

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#4006]
### Bug Description
```
Error:  Failures: 
Error:    AuditorTest.testDetectAnnotationChangesFast:289 
Expected: a value less than <1000000L>
but: <1701741L> was greater than <1000000L>
```
Quoting @HolgerReiseVSys: "Seems not really surprising, as it depends on hardware and scheduling"

### Steps to Reproduce
See recent CI [failures](https://github.com/hzi-braunschweig/SORMAS-Project/pull/4000/checks?check_run_id=1700854077#step:5:819)

### Expected Behavior
Test passes

### System Details
CI

**Comment by DavidBaldsiefen** [comment]
Can this be closed @JonasCir ?

**Comment by JonasCir** [comment]
Yes never showed up again and parameters of the test were slightly adjusted at some point in time,
