### ISSUE TITLE
Refining the consistency of the sex field as a required field for both web and mobile app versions

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#4007]
### Feature Description
When creating persons linked to entities (cases, contact event participant), sex is a required field in the web version, but not on the mobile app. On the web version also, sex as a required field is not consistent for all forms.

### Problem Description
This causes errors when converting e.g. an event person to a case.

### Proposed Change
Could we consider making all sex fields required  fields on  both mobile app + web versions?
The “Unknown” option for sex can be selected by fieldworkers to allow them proceed with data collection (thus, in situations when sex is not known).

**Comment by MartinWahnschaffe** [comment]
Addition: It's currently also possible to push a person without sex into the system via ReST. We should either validate the dto properties based on their annotations or at least make the field also required in the database.

**Comment by MartinWahnschaffe** [comment]
Done in #6248
