### ISSUE TITLE
Creation date filter in case duplicate merging does not work as expected

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4008]
### Bug Description
In the case duplicate merging view cases are not correctly filtered based on their reportDate.

### Steps to Reproduce
1. Take a case that has been created yesterday or before that
2. Create a new case with a similar name, disease, district, so the case duplicate merging should identify them as potential duplicates
3. Go to the case duplicate section and set the creation date filter to today. The cases will not show
4. When you adjust the creation date filter to the creation date of the first case, they will show

### Expected Behavior
The cases should show at step 3 and also at step 4.

The reason it does not work is that filter on the creation date of case A in combination with the filter on the creation date of case A being before the creation date of case B. The second aspect is done to make sure that both cases only appear once in the duplicate list. 

		Predicate creationDateFilter = cb.lessThan(root.get(Case.CREATION_DATE), root2.get(Case.CREATION_DATE));

What needs to be done is probably something like this:

- [x] When the creation date from/to are set the creationDateFiter needs to receive an OR with a check if root2 is outside of the filtered creation date range.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.55.0-SNAPSHOT
