### ISSUE TITLE
[SurvNet Interface] Add fields to events in regards to outbreaks

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4013]
### Situation Description
To be able to transmit outbreaks to SurvNet, some fields and variables need to be implemented in Sormas, specifically in the events.
### Feature Description

1. 

 Add a "measures" drop-down field to event actions above the event action creation form:
Include the following variables:
- (null)
- prohibition of entry and work for case persons (Betretungs- und Tätigkeitsverbote für Fälle)
- sample collection (Probenentnahme)
- forwarding to the national reference centre (Versand an das NRZ)
- active follow-up of contact persons (Aktive Nachverfolgung von Kontaktpersonen)
- verification of vaccination or immunization status (Überprüfung des Impf- oder Immunstatus)
- conduct post-exposure prophylaxis vaccination (Durchführung von Riegelungsimpfung)
- closure of facility (Schließung einer Einrichtung)
- prohibition of entry and work of contact persons (Betretungs- Tätigkeitsverbote von Ansteckungsverdächtigten)
- population information about outbreak (Informationen der Bevölkerung über den Ausbruch)
- other > (title used for specification)

[an action with the corresponding measure equals one entry in SurvNet; when multiple actions are present in Sormas, use earliest date to transmit to SurvNet ("Datum des Beginns erster Maßnahmen")].

2.

Add field "primary mode of transmission" (Primärer Übertragungsweg)
Include the following variables:
- unknown (Unbekannt)
- primarily via animal (hauptsächlich über Tier)
- primarily via environment (hauptsächlich über Umwelt)
- primarily via food (hauptsächlich über Lebensmittel)
- primarily from human to human (hauptsächlich von Mensch zu Mensch)
- primarily vector borne (hauptsächlich Vektorübertragen)

3.

~~Add means of transport variables to events~~ => Already in the system

4.

Add "dispersed" (verstreut) as variable in type of place

5.

Add (yes/no/unknown) "outbreak is transregional" (Ausbruch ist überregional)

6.

~~Add drop-down field "infectionpath/ -source/ -vehicle/ med. procedure" (Infektionsweg/ -quelle/ -Vehikel/ med. Prozedur) underneath nosocomial outbreak in events~~

### Additional Information
<img width="349" alt="eventActionsMeasures2" src="https://user-images.githubusercontent.com/70317594/104611832-d76fce80-5685-11eb-97fd-f219757f3057.PNG">
<img width="520" alt="eventFields3" src="https://user-images.githubusercontent.com/70317594/104612506-90360d80-5686-11eb-9edb-07bfe5082240.PNG">

**Comment by MateStrysewske** [comment]
@kwa20 What's the wording we should be using? Right now the event status that defines an outbreak is called "Cluster". Should we still go with something like "Type of outbreak" or should we continue using the word Cluster? If we use the word Outbreak, wouldn't it potentially make sense to rename Cluster to Outbreak?

And concerning the last point "infectionpath/ -source/ -vehicle/ med. procedure" - I don't understand what that's supposed to track and how the provided values are in any way related to the caption. Can you please explain?

**Comment by MateStrysewske** [comment]
@kwa20 Also, which of these fields are supposed to be German-only and which should be visible for all countries?

**Comment by MateStrysewske** [comment]
@kwa20 Also, what's the workflow between action measure and title? For example, should the measure be displayed in the grid instead of the title? Does that mean the title should no longer be required, but the measure should be (and the title only when "Other" was selected)? Or can the grid stay as it is right now? That would require users to type in duplicate information however when they perform an action that is also part of the measure list.

**Comment by MateStrysewske** [comment]
@kwa20 And are you sure "dispersed" is the right wording? "Scattered" sounds a bit more fitting to me.

**Comment by kwa20** [comment]
@MateStrysewske Cluster and Outbreaks are apparently more or less synonyms. After checking again, we might actually call the "type of outbreak" "primary mode of transmission" with the mentioned variables.  This might actually be more fitting.

"infectionpath/ -source/ -vehicle/ med. procedure" is a field, that gets only enabled, when "yes" is selected in nosocomial. It provides information about the confirmation of the path of infection. It is theoretically also connected to the evidence of such confirmation. Additional fields for evidence are however not mentioned yet, because it's too much at the moment. (germany only) - all other fields would be relevant internationally (@bernardsilenou)

regarding event actions: I think title should stay, because it's non-compulsory, measures would be an additional drop-down field. We could think of making the title disappear when a variable other than "other" is selected in measures. However, I'm not sure if thats necessary since it's non-compulsory.

"scattered" is also fine for me.

**Comment by kwa20** [comment]
@MateStrysewske new info: we exclude "infectionpath/ -source/ -vehicle/ med. procedure"  for now.

**Comment by AndyBakcsy-she** [comment]
Validated this ticket on the Web using test.sormas.netzlink.com on the latest version of SORMAS Version: 1.54.0-SNAPSHOT

Found out that the translations are not implemented for No.2 and 4 from the feature description.
![image](https://user-images.githubusercontent.com/70562142/104846076-5ad92c00-58e1-11eb-9ceb-af78bb4083bc.png)

**Comment by JonasCir** [comment]
@AndyBakcsy-she Should this issue be reopened then?

**Comment by AndyBakcsy-she** [comment]
Validated the changes on the latest version of the app using the mobile phone and could not find the "Measures" dropdown. 
Shouldn't this be implemented also on the app?

**Comment by AndyBakcsy-she** [comment]
@JonasCir  I think we should wait on @MateStrysewske to answer and give his feedback.

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she There are no event actions in the mobile app, so of course the Measure field is not present there.

@JonasCir Translations have to come in via Crowdin. If we do them in the code, they will get overridden by the default (English) translations again when we pull changes from Crowdin.

**Comment by kwa20** [comment]
I can confirm that everything was translated on Crowdin
