### ISSUE TITLE
[DEMIS2SORMAS] Show error messages to the user [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#4017]
### Situation Description

Currently, errors in the demis adapter are written to the log or not noted at all. There is just the standard error message shown to the user, and this not even in all cases. This has to be changed. 

### Feature Description

In this issue, the ExternalLabResultsFacade and related classes shall be enabled to receive error messages and output them to the user.

### Additional Information

The [ExternalJournalService.validatePatientDiaryPerson(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/c4b8713faa58f1596a9eb7973dd341813cd980bc/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L325) might help get an idea of how to implement this.

This issue should probably be picked together with implementing the forwarding of error messages in the demis-adapter.

**Comment by FredrikSchaeferVitagroup** [comment]
This issue is related to https://jira.vitagroup.ag/browse/SOR-721.

**Comment by vlad-ciucescu** [comment]
Some errors related to fetching messages are not handled correctly
Related to https://jira.vitagroup.ag/browse/SOR-898

**Comment by MateStrysewske** [comment]
@vlad-ciucescu This issue has already been released. Please open a new issue if there's any further work needed.
