### ISSUE TITLE
Jurisdiction and desease should be pre-filled depending on the user

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4018]
### Situation Description

The users have to select the jurisdiction and desease many times of the day. This is very time consuming,

### Feature Description

The jurisdiction and desease of the current user should be pre-filled in any field of cases, contacts, events, even participants, even for adresses as the user in most of the times only enter data from their own area.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis The jurisdiction is prefilled for survaillance officer (SO) account. For data entry, users can user a SO account.
There is another issue #3507  where higher users can configure their account but we did not just have time to work on it.
Hope this is a fair workaround for now?

**Comment by markusmann-vg** [comment]
will be covered by #3507
