### ISSUE TITLE
[SurvNet Interface] Ordering events as super- and subordinate to transmit to SurvNet

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4020]
### Situation Description
the transmission of event clusters is necessary to transmit outbreak information to SurvNet. The difficulty of transmitting outbreak information is the differing structure in Sormas and SurvNet (folder structure). This is especially the case, when cases in Sormas are linked to multiple events, which is not possible in SurvNet. 

### Feature Description
Add the possibility to link events to each other and decide whether events are superordinates or subordinates of other events. This would be required to decide about the ordering of events to conform to the folder structure of SurvNet. The case would be linked to the subordinate event (outbreak) in SurvNet. This is due to cases showing up in all superordinate events, even if they are not explicitly linked.

### Possible Alternatives
If we leave the Sormas structure as it is, we would need to decide about criteria to order events upon transmission to SurvNet. 
1)  If a case is linked to multiple events, the structure would be based on the earliest event date (superordinate) and goes down to the lates event date (subordinate). Use report date if event date is not available. In SurvNet, the case would be linked to the subordinate event (outbreak). This is due to cases showing up in all superordinate events, even if they are not explicitly linked. If events started on the same date, let either the user decide which event should be superordinate or subordinate. 

2) Leave the decision of the event structure to the user when they transmit data to SurvNet. Order the outbreaks  in SurvNet as decided in the decision window upon transmission and link the case to the subordinate event (outbreak) in SurvNet.

**Comment by MateStrysewske** [comment]
Important: Make sure that an event can not have a superordinate event that is also a subordinate event of the event itself or one of its subordinate events.

**Comment by MateStrysewske** [comment]
- [ ] Swap subordinate and superordinate events

**Comment by MartinWahnschaffe** [comment]
Out-of-scope refinements we could do:

* Before linking an event only show the "discard" confirmation form, when the user has actually made changes
* When unlinking ask the user for confirmation

**Comment by AndyBakcsy-she** [comment]
Validated ticket on test.sormas.netzlink.com on the latest version of SORMAS Version: 1.54.0-SNAPSHOT

**Comment by MateStrysewske** [comment]
- [ ] Don't allow adding events with a later date as a superordinate or events with an earlier date as a subordinate event
