### ISSUE TITLE
Add location information to facilities

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#4027]
### Situation Description

On the location blocks in SORMAS (can be found in event and person-related entities), you can select facilities from a list and you can indicate an address just below. We would like to add location information to facilities so that the selection of a facility automaticaly fills the address fields.

This feature will be split in two issues :
- add location information to facilities (the present issue)
- facility selection fills location fields (#4028)

### Feature Description

We need to add to the facility entity the following informations : (all are optional)
- street
- house number
- additional information
- postal code
- area type

The new fields will not be shown in the list (configuration pane) but will be added to a new "detailled export".
The import mechanism will be modified to include the new fields (still optional)

### Additional Information

Later, phone and email address could be added as aked in #3931 but this will not be done in this issue.

@carolinverset @bernardsilenou

**Comment by bernardsilenou** [comment]
@markusmann-vg Dev France would work on this for 1.55

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.58.0-SNAPSHOT on test.sormas.netzlink.com
Validated on web app and mobile app

**Comment by herrling-LRA-KYF** [comment]
Will this feature also be available in Germany or just in France?

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF This feature will be available for all countries using SORMAS.
