### ISSUE TITLE
facility selection fills location fields

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#4028]
### Situation Description

On the location bloc in SORMAS (can be found in event and person-related entities), you can select facilities from a list and you can indicate an address just below. We would like to add location information to facilities so that the selection of a facility automaticaly fills the address fields.

This feature will be split in two issues :
- add location information to facilities (#4027)
- facility selection fills location fields (the present issue)

### Feature Description

The selection of a facility on a location block will automaticaly copy the facility's location information to the corresponding fields of the block (street, house number, additional information, postal code, city, area type, latitude, longitude) if at least one of them is filled on the facility side. If there is already information on the fields, it is replaced by the facility's information.

Afterward, the user is still free to edit this information which will still be stored in the corresponding entity : if the address of the facility changes later, the address of the event/case/contact should not change.

### Additional Information

This issue has to be done AFTER #4027 because of the need for the new fields.

@carolinverset @bernardsilenou

**Comment by bernardsilenou** [comment]
@markusmann-vg Dev France would work on this for 1.55
