### ISSUE TITLE
[SurvNet Interface] Change title of role field in exposures and add new field [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4036]
### Feature Description
Case/Contacts > Epi Data > Exposures > Exposure Details > in the role of
### Problem Description
For the SurvNet interface, role descriptions are required. Thus far such role description do not exist in an exposure and the current "in the role of" field does not fit for this purpose considering its variables.
### Proposed Change
- Add the variable "Unknown" to type of activity (exposureType).

- Move the "in the role of" field to "care/accommodation/work in facility" in #4163 

- Add a drop-down "role" field under exposure details with the following variables:
  - (null)
  - passenger / Passagier
  - staff / Personal
  - nursing staff / Pflegepersonal
  - medical staff / Medizinisches Personal 
  - visitor / Besucher
  - guest / Gast
  - customer / Kunde
  - conservatee / Betreute
  - patient / Patient
  - educator / Erzieher
  - trainee teacher / Ausbilder
  - pupil / Schüler
  - student / Student
  - parent / Eltern
  - teacher / Lehrkraft
  - unknown / Unbekannt
  - other / Sonstige

### Additional Information
<img width="418" alt="Screen Shot 2021-01-28 at 4 01 54 PM" src="https://user-images.githubusercontent.com/70317594/106156772-3d7a4c80-6182-11eb-8433-199b3b92a525.png">

**Comment by MateStrysewske** [comment]
Requires refinement in #4163

**Comment by MateStrysewske** [comment]
* Add "Unknown" to `ExposureType`
* Rename `PatientExpositionRole` to `ExposureRole`
* Replace the values of `ExposureRole` with the values above
* Write an SQL migration script that maps the values as follows (only relevant for test systems):
    * NOT_COLLECTED => null
    * UNKNOWN => UNKNOWN
    * WORKING_AT => STAFF
    * ACCOMMODATED_IN => GUEST
    * CARED_FOR => PATIENT
    * OTHER => OTHER

@kwa20 Is this fine for you?

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of Sormas Version 1.57.0-snapshot on local environment.

**Comment by raghupola-vg** [comment]
"Role" field on Mobile app has to be under the Exposure Details.

**Comment by raghupola-vg** [comment]
Verified the changes on Mobile App on version 1.57.0-Snapshot
