### ISSUE TITLE
[SurvNet Interface] Add fields next to type of place [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4038]
### Situation Description
Additional variables are needed for the SurvNet interface. Therefore, additional drop-down fields could be added. The reason for separating this from the facility type is that all these variables could be environmental subgroups of the business variable in facility type and we don't have a categorized subgroup of facility types.
### Feature Description

1. 

Add a "work environment" drop down field next to type of place (applicable for exposures and events) that appears when "workplace" is selected in facility category with the following variables:
  - (null)
  - unknown
  - open space office
  - food sector
  - building sector
  - logistics center
  - other

2.

~~Add commerce as a variable to type of place and a "commerce" drop down field next to type of place which appears when "commerce" is selected and include the variables:~~ 

Add a new facility category called "commerce" and two new facility types called "retail" and "wholesale" for this category

3.
Add "local public transport" variable to the means of transport field. Enable subsequent connection number.
  
### Additional Information
1.
<img width="744" alt="Screen Shot 2021-01-27 at 4 27 04 PM" src="https://user-images.githubusercontent.com/70317594/106013345-a4cdc900-60bc-11eb-9408-c4ebb30c1916.png">

2.
<img width="702" alt="Screen Shot 2021-01-27 at 4 25 52 PM" src="https://user-images.githubusercontent.com/70317594/106013395-b31be500-60bc-11eb-8000-7acbb1db32f5.png">

**Comment by kwa20** [comment]
In consolidation with @bernardsilenou : Other option would be to introduce "commerce" with the variables retail, wholesale, food sector, other.

**Comment by kwa20** [comment]
Other option to consider for 2.: Put work environment next to type of activity when "work" is selected.

**Comment by kwa20** [comment]
After discussing with @MateStrysewske @HolgerReiseVSys and @Candice-Louw, adding "commerce" as a facility category with facility types "retail" and "wholesale" would be a better solution.

**Comment by MateStrysewske** [comment]
@kwa20 What is "local public transport" supposed to track?

**Comment by kwa20** [comment]
@MateStrysewske SurvNet differentiates between intercity busses (Fernbus) and local public transport (Öffentlicher Nahverkehr) here. Besides busses within a city, this could technically also include metro, tram etc. I guess the main differences would be timeframe and consistency of number of people.

**Comment by MateStrysewske** [comment]
@kwa20 Okay, makes sense!

**Comment by raghupola-vg** [comment]
Verified on latest version 1.57.0-snapshot on test environment.
