### ISSUE TITLE
[SurvNet Interface] Change type of activity section [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4039]
### Feature Description
exposures in epi data

### Problem Description
Some variables are needed in regards to the SurvNet interface. 
### Proposed Change

- Add the following variables to "type of gathering":

  - demonstration
  - carnival
  - fair
  - sporting event

- ~~Add "leisure" as a variable in Type of activity.~~

### Additional Information
<img width="834" alt="Screen Shot 2021-01-15 at 4 53 49 PM" src="https://user-images.githubusercontent.com/70317594/104748666-474b8b00-5752-11eb-939c-b31a7aa1fee2.png">

**Comment by kwa20** [comment]
@bernardsilenou Would you say we just add leisure by itself then? My problem was that I was missing a variable for leisure and thought that sport would basically be a subset of leisure. Migrating it later if we have more variables for leisure makes sense though.

**Comment by bernardsilenou** [comment]
@kwa20 Thats what I meant, your design is perfect when we have a prior more than one categories

**Comment by MateStrysewske** [comment]
@kwa20 I think we agreed to keep "Leisure" out of the system for now because it's basically redundant, right? That would mean we'd only have to implement the first proposed change (adding the new gathering types).

**Comment by kwa20** [comment]
@MateStrysewske yes, the idea was also to then map the corresponding entry in survnet to "other" type of activity and leisure as the entry in the subsequent free text.

**Comment by DavidBaldsiefen** [comment]
If nothing needs to be do be done about "Leisure" for now (assuming the mapping takes place in another issue?) PR #4211 would implement the new types.

**Comment by raghupola-vg** [comment]
tested on version 1.55.0-snapshot and the changes are done.
