### ISSUE TITLE
 import events from a csv file

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4041]
### Situation Description
To date, it is possible to enter events manually but signals cannot be imported via a csv file within the HMI.
It often happens that the Health Insurance transmits information relating to events identified in the region via an excel file.
The development of an import module based on a csv file, shared with the AM, would facilitate the import of this information

### Feature Description
Develop a module for importing events in SORMAS from the GUI:
-	Creation of an import file in csv format. It would be built on the basis of the columns that are offered for entry when manually creating an event. The mandatory columns would be equivalent to the mandatory fields of the input form within the application.
-	Development of import mechanics in SORMAS

### Additional Information
@ftavin @bernardsilenou @olivierleuci @emond

**Comment by bernardsilenou** [comment]
What i can think of is to:
- extend  the event participant template (ep) with meta data of the event: eventuuid, date of event, status, investigation status, disease, title,.........This means each record in the table is an ep, meta data for event would be repeated.
- add duplicate event detection method using:
- title similarity (we can use the same threshold as in name similarity of person or add a new parameter for this)
- exact match for the following if provided in both pairs: start date, end date, event status, source type, disease, region, district, community, externalid, event uuid. If one of the pairs is missing any of this variables, then we do not consider the variable in the computation.
- If event uuid is provided for a record, then no need to call duplicate event detection. It may be good to do group import by event uuid, such that we do not need to call the duplicate event detection for each record to be imported, all participants with the same eventuuid/ meta data whould require just one call of the duplicate event detection method. 
- After grouping, we can then call the duplicate eventt participant method among ep in the group
- If event already  exist + user validation, add participants to it, If not create a new event.

This logic is similar to the import of cases with samples; with cases being events and samples the event participants

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 Further refinement?

**Comment by kwa20** [comment]
@bernardsilenou Just a minor comment. Adding the event uuid would only be applicable for the event participant import since it'll be automatically generated for events. However, this will also only make sense if we enable the import of event participants directly from the event directory because event participants can only be imported inside of an event so far anyway.

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset

Bernard, I think your specification is good as it permits to import events directly with their participants but it may be also bad as it does not permit to import event without any participant (maybe this is not a problem, this is up to Carolin to tell us the initial need)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 

I agree with both of you :-)
On the one hand, it would be great to be able to import the characteristics of an event and at the same time the list of participating people.

But on the other hand, it would be a problem not to be able to import events without people attending the event. It happens that information on the people involved is transmitted later.

Isn't there a technical way to make the import of events + people involved possible but not to make the import of pp compulsory?

**Comment by kwa20** [comment]
@carolinverset @ftavin @bernardsilenou I would suggest to make two kinds of imports available on the event directory. One being the import template specifically for events and a second being the one for event participants with a column to reference the event uuid. The later will basically be the one already found inside an event under event participants with the difference that event participants from many events can be imported with the event uuid as a reference.

If we end up with an event participant directory at some point, we could move the general event participant import to this directory.

**Comment by MateStrysewske** [comment]
@carolinverset @ftavin The way importing cases with samples works is that the sample columns are the last columns in the import file, and they're completely ignored if there hasn't been anything filled in for them. If the user wants to import multiple samples, they can just copy & paste the columns to the right. So it's basically exactly what you described - it's possible to import samples alongside cases, but it's optional. The same approach would work for event participants.

**Comment by ftavin** [comment]
@MateStrysewske ok so this would be a perfect solution for this issue too !

**Comment by syntakker** [comment]
Findings from Internal Review:
The following should be excluded from the import template:

- person.symptomJournalStatus (also present in Eventparticipant import)
- sormasToSormasOriginInfo.*
- ownershipHandedOver

ImportFacadeEjb:
- L. 231, 251: Check for PERSON_COLUMNS_TO_REMOVE misses since prefix is not respected
- L. 623, 629: prefix == null || prefix.isEmpty() => StringUtils.isEmpty (not introduced in this task)

EventImportEntities, PersonFacadeEjb:
- unused imports

EventImportFacadeEjb:
- code formatting
