### ISSUE TITLE
Personalized export of people participating in the event

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4043]
### Situation Description

To date, lack of a personalized export for the part participating in the event. 

### Feature Description

This personalized export would be: 

- Configurable and modifiable by all users (each user configures their own export) like personalized exports in cases or contacts for example 

- Configurable by a supervisor knowing that this configuration, once recorded, appears for all users and cannot be modified by them (formatting of a personalized export allowing to standardize the export to be used to communicate information to an institutional partner for example)

### Additional Information
@ftavin @olivierleuci @bernardsilenou  @emond

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 
I think the second mecanism ("Configurable by a supervisor knowing that this configuration, once recorded, appears for all users and cannot be modified by them") should not be done via the event participant screen but in a new configuration pane.

It seems logical that the configuration of such exports should be done directly in the configuration part and should not needs to go to the event participant screen of a particular event

This pane would only permits to configure event participant exports at first but could be used in the future to configure other types of global custom exports.

Don't you think this should be split to another issue ?

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou  on the custom export configuration popup there is a "share to public" option that can be used instead of the second mecanism (the shared export is usable but can't be edited by other users)
