### ISSUE TITLE
Limit the information exported to  the lines selected in the list of the directory 

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4044]
### Situation Description

To date, the basic export makes it possible to export the lines displayed in the various directories, including those of the participants in the event;
It would be useful to be able to manually select the lines to include in the export.

### Feature Description

The detailed export created by issue #4043 would have an option to limit exports to all selected lines in the directory. In the event that no row is selected; then the export will concern all the lines displayed on the screen
### Additional Information

@ftavin @bernardsilenou @olivierleuci @emond

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou

To keep consistency in the app I would suggest the following specification :

> When we are on Bulk Edit mode, the exports are limited to the selected lines, or all the lines if no lines at all are selected.
> The following screens are concerned :
> - cases (and the contacts of a case sub-screen)
> - contacts (and the follow-up visits sub-screen)
> - events (and the event participants sub-screen)
> - samples
> 
> Note : the event participant subscreen is always in bulk edit mode

**Comment by bernardsilenou** [comment]
@markusmann-vg @MateStrysewske I  think this belong to sprint 101 ?

**Comment by MateStrysewske** [comment]
Basic export fails at least for events when logged in as a user who has no access to bulk operations. Might be failing for other directories as well.

**Comment by vidi42** [comment]
Just saw this issue. I already provided a fix for the Basic Export fail as part of #4656

**Comment by MateStrysewske** [comment]
@vidi42 Sorry, I've just seen your comment and have already pushed a fix as well. I think the fix you provided probably doesn't solve the problem though because it now ALWAYS assumes that the view is in multi-select mode which could again result in errors (when the grid is not actually in multi-select mode).

Again, sorry for not noticing earlier!

**Comment by vidi42** [comment]
No problem. I closed the PR
