### ISSUE TITLE
 display the risk level for all event statuses (not just cluster)

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4047]
### Feature Description

To date, the "criticality level" variable only appears for events classified as clusters. The terms are as follows.-
 - NA (default value)
- Low risk
- Moderate risk
- High risk

### Problem Description

After discussion with users, it was deemed relevant to extend this variable to all event statuses.

### Proposed Change

The request therefore consists in showing the "critical level" variable with the 4 defined modalities (NA / low risk / moderate risk / high risk) in all the status of the event. Thus, the field will appear regardless of the status selected: signal, event, screening or cluster.

### Additional Information
@bernardsilenou @ftavin @emond @olivierleuci

**Comment by kwa20** [comment]
should go with #3951

**Comment by ftavin** [comment]
@kwa20 @carolinverset @bernardsilenou 

we should keep two differents issues

This one first, to change the event screen (we just remove the condition on the field)

Then #3951 will be done to add a separate column with this data and the corresponding filter

**Comment by AndyBakcsy-she** [comment]
Validated this ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on the local environment
