### ISSUE TITLE
birth day filter does not initially get enabled on contact directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4051]
### Bug Description
The birth day filter stays disabled on the contact directory, even if birth year and month have been entered. It only becomes enabled when the apply button is hit in between.
### Steps to Reproduce
1. Open contact directory and fill birth year and month filters.
2. Check birth day filter.
3. hit apply and check again.

### Expected Behavior
birth day filter should become enabled when birth month is selected without having to hit apply in between.
### Screenshots
<img width="575" alt="Screen Shot 2021-01-17 at 12 47 12 AM" src="https://user-images.githubusercontent.com/70317594/104827509-aac2df00-585e-11eb-9666-cbf0ee98544e.png">

### System Details
* Device:
* SORMAS version: 1.53.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by DavidBaldsiefen** [comment]
What's the reason it's not enabled by default anyway? I know that the birth date is not always known, but the user doesn't have to use that filter anyway.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS
Version: 1.55.0-SNAPSHOT on the local environment
