### ISSUE TITLE
Expanding the chart or the map on the contact dashboard as contact officer results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4052]
### Bug Description
Expanding the chart or the map on the contact dashboard as contact officer results in error.
### Steps to Reproduce
1. Log in as a contact officer. Open the contact dashboard and expand the chart and map respectively.
2. Check error message.

### Expected Behavior
charts and map should expand in the normal format and not result in an error.
### Screenshots
<img width="847" alt="contactDashboardError" src="https://user-images.githubusercontent.com/70317594/104845891-0b423280-58d8-11eb-8a12-25e5a4041e5c.PNG">
<img width="849" alt="contactDashboardError2" src="https://user-images.githubusercontent.com/70317594/104845895-0e3d2300-58d8-11eb-9757-7aa511ea39ad.PNG">

### System Details
* Device:
* SORMAS version: 1.52.1/1.53.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de; musterstadt.sormas-oegd.de
* User Role: contact officer

**Comment by bernardsilenou** [comment]
@kwa20 I think this may be a user role issue. The dashboard is technically not for the contact officer role alone but combined with the surveillance officer. The map by default always show cases but contact officer role alone has no full right to these cases, this may be the cause.
- Combining with SO, all works fine
- Maybe we need to adjust the map layers to be a able to show only  contacts.

**Comment by kwa20** [comment]
@bernardsilenou The error also occurs with the combination role

**Comment by bernardsilenou** [comment]
@kwa20 I confirmed it also happen with both user roles. In the first trial i clicked on the "view full-screen" icon instead
![image](https://user-images.githubusercontent.com/12996724/104853315-4bb5a680-5900-11eb-8341-dd7c92f4b107.png)

**Comment by raghupola-vg** [comment]
verified on latest deploy on version 1.55.0-snapshot and issue is Fixed.
