### ISSUE TITLE
scroll bar covers last entry in exposure list when using mozilla firefox

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4053]
### Bug Description
When using mozilla firefox, the scroll bar of the exposure list in epi Data covers the last entry
### Steps to Reproduce
1. Open Sormas in mozilla firefox version 68.
2. Check the exposure list in epi Data.

### Expected Behavior
List should be displayed normally and not be covered by the scrollbar.
### Screenshots
<img width="438" alt="exposureDisplayError" src="https://user-images.githubusercontent.com/70317594/104846665-f1a2ea00-58db-11eb-80be-c05e0b428ec7.PNG">

### System Details
* Device: Windows 10 Enterprise
* SORMAS version: 1.52.1/1.53.0
* Android version/Browser: Mozilla firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by DavidBaldsiefen** [comment]
@kwa20 Can you guess how large the scrollbar is in pixels (height)? The easiest solution I see is to add some padding to the bottom of the table. That would also give this solution the highest reliability, as I presume this issue depends strongly on the used browser, display size etc.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com
