### ISSUE TITLE
typeOfAnimalDetails does not get enabled in exposures

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4054]
### Bug Description
When "Other" is selected as the type of animal in regards to animal contacts, the subsequent field "Type of animal details" does not get enabled.
### Steps to Reproduce
1. create an exposure with animal contact as type of activity.
2. Select other as type of animal and check if type of animal details field appears.

### Expected Behavior
When "other" is selected as type of animal, the type of animal details field should appear to give the user an option to specify the type of animal.
### Screenshots
<img width="501" alt="typeOfAnimalDetailsBug" src="https://user-images.githubusercontent.com/70317594/104847112-77279980-58de-11eb-9910-e35791432b44.PNG">

### System Details
* Device:
* SORMAS version: 1.52.1/1.53.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de; musterstadt.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 Please verify your findings on a server that runs the current development version (i.e. test.sormas.netzlink.com). This issue has alreay been fixed.

**Comment by kwa20** [comment]
@MateStrysewske Can verify that the details field appears (tested on test.sormas.netzlink.com)
