### ISSUE TITLE
Case officer receives an error when trying to enter a new exposure

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4055]
### Bug Description
The case officer role receives an error when trying to enter a new exposure in the epi data tab. This seems to be unrelated to a previous error where a missing language setting resulted in this error (#3826).
### Steps to Reproduce
1. Log in as a case officer.
2. Go to the epi data tab of any entity.
3. Try adding a new exposure.

### Expected Behavior
Case officers should e able to add new exposure entries.
### Screenshots
<img width="596" alt="caseOfficerExposureBug" src="https://user-images.githubusercontent.com/70317594/104849155-8ad7fd80-58e8-11eb-8558-2a75cfba9a4d.PNG">
<img width="350" alt="caseOfficerLanguageSetting" src="https://user-images.githubusercontent.com/70317594/104849158-8ca1c100-58e8-11eb-91c7-af6162e715dc.PNG">

### System Details
* Device:
* SORMAS version: 1.52.1/1.53.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on the test.sormas.netzlink.com environment
