### ISSUE TITLE
User feedback from document generation

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#4057]
### Feature Description

Requested by users for document generation:

- sample and pathogen tests can be chosen, data is available in templates
- current user data is available
- generation of quarantine orders for event participants
- separation of document templates for cases, contacts, event participants

Already implemented in other issues:
- improved error handling (#3222)
- custom placeholders for empty variables, variables not displayed when empty (#3991)
- printable documents for events including event actions (#2906)
- code quality issues fixed (#3480)

**Comment by syntakker** [comment]
Implemented in  #4171.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas version 1.55.snapshot

**Comment by raghupola-vg** [comment]
When a Quarantine order /event handout is created, the document name is saved only with first 5 letters of the UUID and skipping the last letter.
For ex: if an event id is VAW3OD when a quarantine template is generated, it saves as VAW3O_xxxxxxxx.xxx.
It should be saved as VAW3OD_xxxxxx.xxx

**Comment by syntakker** [comment]
Finding from @kwa20: When there is only one sample or pathogen test, it should be preselected in the respective ComboBox.

**Comment by StefanKock** [comment]
Findings needed to be fixed, that's why the milestone is appropriatly change to Sprint 100.

**Comment by syntakker** [comment]
Feedback from Review @StefanKock: `DataHelper.getShortUuid` should not be graceful for Uuids that are too short.

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of Sormas Version 1.57.0-snapshot
