### ISSUE TITLE
[DEMIS2SORMAS] Follow up for lab message processing [5]

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#4058]
### Situation Description
Follow-up of #3488 
### Feature Description
Needed Features:
- [x] Creation of Contacts
- [x] Creation of Event Participants
- [x] Selection of Contacts
- [x] Selection of Event Participants
- [x] Selection of Sample
- [x] Selection of Test

**Comment by raghupola-vg** [comment]
Verified on version 1.57.0-snapshot on test-de2 instance and it works fine.
