### ISSUE TITLE
[SurvNet Interface] Add variables to facility type [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4066]
**FINAL LIST 08.03.2021**: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4066#issuecomment-792699527

### Situation Description
Some further variables are needed for the facility types in order to subsequently map them for the SurvNet interface.

confer 1. in #3312 
### Feature Description
Add the following variables to the facility types (preceding variables conform to facility categories):

- Ambulatory surgery facility: _MEDICAL_FACILITY > AMBULATORY_SURGERY_FACILITY_ (Einrichtung für ambulantes Operieren)
- Dialysis facility: _MEDICAL_FACILITY > DIALYSIS_FACILITY_ (Dialyseeinrichtung)
- Day hospital: _MEDICAL_FACILITY > DAY_HOSPITAL_ (Tagesklinik)
- Maternity facility: _MEDICAL_FACILITY > MATERNITY_FACILITY_ (Entbindungseinrichtung)
- Medical practice: _MEDICAL_FACILITY > MEDICAL_PRACTICE_ (Arztpraxis)
- Dental practice: _MEDICAL_FACILITY > DENTAL_PRACTICE_ (Zahnarztpraxis)
- Other medical practice: _MEDICAL_FACILITY > OTHER_MEDICAL_PRACTICE_ (Praxis sonstiger humanmedizinischer Heilberufe)
- Diagnostic, preventative, therapeutic  facility: _MEDICAL_FACILITY > DIAGNOSTIC_PREVENTATIVE_THERAPEUTIC_FACILITY_ (Einrichtung des ÖGD zur Diagnostik, Prävention, Therapie)
- Emergency medical services: _MEDICAL_FACILITY > EMERGENCY_MEDICAL_SERVICES_ (Rettungsdienst)
- Elderly care facility: CARE_FACILITY > ELDERLY_CARE_FACILITY (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung älterer Menschen)
- Disabled person habitation: _CARE_FACILITY > DISABLED_PERSON_HABITATION_ (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung behinderter Menschen)
- Care recipient habitation: _CARE_FACILITY > CARE_RECIPIENT_HABITATION_ (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung pflegebedürftiger Menschen)
- Visiting ambulatory aid: _CARE_FACILITY > VISITING_AMBULATORY_AID_ (aufsuchende ambulante Hilfen)
- After school facility: EDUCATIONAL_FACILITY > AFTER_SCHOOL (Kinderhort)

**Comment by Marko-ilmkreis** [comment]
@kwa20 as I usually work in an alien authority the name "Heim" for asylum seekers is wrong. There are generally two types of places where they live (beside own flats or shares flats):
1) Erstaufnahmeeinrichtung (initial registration facility or reception facility), where they are living the first few weeks or months. They are usually organzied by the region. (https://www.bamf.de/EN/Themen/AsylFluechtlingsschutz/AblaufAsylverfahrens/Aufnahmeeinrichtung/aufnahmeeinrichtung-node.html)
2) Gemeintschaftsunterkünfte (common housing), where are the living on district/city level.

**Comment by kwa20** [comment]
@Marko-ilmkreis Thanks for the feedback! The difficulty I had was finding a translation for the already in SurvNet existing variable "Heim", which I did not want to get confused with "Home". I agree that asylum is not the best option, especially since we already have corresponding variables for the facilities you mentioned in the system. We could basically describe "Heim" as a community facility, although community facility seems to me as a general term which "Heim" is a part of. Calling it "Community home" could be an option, although it might suggest something else in english.

**Comment by kwa20** [comment]
@markusmann-vg this issue should be postponed and #4163 implemented instead due to "exposition" being a totally misleading field name in SurvNet. This would only be needed when we eventually allow depositing of addresses with corresponding facility types.

**Comment by markusmann-vg** [comment]
@kwa20 

Elderly care facility: CARE_FACILITY > ELDERLY_CARE_FACILITY (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung älterer Menschen)

We already have:
ELDERLY_DAY_CARE => Should those be merged to one and if so to what?

Wouldn't it be confusing to have both?

**Comment by kwa20** [comment]
@markusmann-vg After discussing with @JaquM we will have to review the issue again and see how it fits into the requirements.

**Comment by Candice-Louw** [comment]
Final list: 08.03.2021:

FINAL list 08.03.2021:

**#Num | English description | SORMAS_PATH | SurvNet Name (Catalogue Tab)**

---

MEDICAL_FACILITY >

---

1. Ambulatory surgery facility: _MEDICAL_FACILITY > AMBULATORY_SURGERY_FACILITY_ (Einrichtung für ambulantes Operieren) 
2. Dialysis facility: _MEDICAL_FACILITY > DIALYSIS_FACILITY_ (Dialyseeinrichtung)
3. Day hospital: _MEDICAL_FACILITY > DAY_HOSPITAL_ (Tagesklinik)
4. Maternity facility: _MEDICAL_FACILITY > MATERNITY_FACILITY_ (Entbindungseinrichtung)
5. Medical practice: _MEDICAL_FACILITY > MEDICAL_PRACTICE_ (Arztpraxis)
6. Dental practice: _MEDICAL_FACILITY > DENTAL_PRACTICE_ (Zahnarztpraxis)
7. Other medical practice: _MEDICAL_FACILITY > OTHER_MEDICAL_PRACTICE_ (Praxis sonstiger humanmedizinischer Heilberufe)
8. Diagnostic, preventative, therapeutic  facility: _MEDICAL_FACILITY > DIAGNOSTIC_PREVENTATIVE_THERAPEUTIC_FACILITY_ (Einrichtung des ÖGD zur Diagnostik, Prävention, Therapie)
9. Emergency medical services: _MEDICAL_FACILITY > EMERGENCY_MEDICAL_SERVICES_ (Rettungsdienst)

---

CARE_FACILITY >

---

10. Elderly care facility: CARE_FACILITY > ELDERLY_CARE_FACILITY (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung älterer Menschen)
11. Disabled person habitation: _CARE_FACILITY > DISABLED_PERSON_HABITATION_ (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung behinderter Menschen)
12. Care recipient habitation: _CARE_FACILITY > CARE_RECIPIENT_HABITATION_ (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung pflegebedürftiger Menschen)
13.  Visiting ambulatory aid: _CARE_FACILITY > VISITING_AMBULATORY_AID_ (aufsuchende ambulante Hilfen)

@markusmann-vg -
Please keep both:
CARE_FACILITY > ELDERLY_CARE_FACILITY (voll- oder teilstationäre Einrichtung und besondere Wohnform zur Betreuung und Unterbringung älterer Menschen)
and
ELDERLY_DAY_CARE (Senioren Tagespflege)

**Comment by Candice-Louw** [comment]
@MateStrysewske - please see if this is sufficiently refined for implementation?

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.58.0-snapshot
