### ISSUE TITLE
Retrospective duplicate detection & resolving [2+3]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#408]
@MartinWahnschaffeSymeda 
We have a problem with duplicate records, where first name, last name repeats itself after picking or matching person. Also when there is a mistake in a letter or word, it saves as a new case, whereas it was only the same case. E.g Taiwo Edito is a case, and another person created Taiwo Edoto, but it is one and the same person due to spelling error. Can we have an algorithm that checks based on 5 key indicator match (first name, last name, date of birth or age, district, region and if possible health facility to match), then call out for duplicates

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Please can you include an active/inactive function to all cases so that atleast for now, we can deactivate cases which appear as duplicates after moving case from one lga to another or duplicates. This would go a long way to solve inaccurate case counts due to duplicates. Especially now that we have not yet classified and not a case on the dashboard

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 
Quickfix: there is a delete function in the new version for admins (see #383).

In additon to this we need two things:
1. A way to further reduce duplicated, by making the name/birthdate comparison more fault-tolerant by applying a similarity algorithm (#432)
2. Build an interface that allows searching for duplicates in cases and contacts and merging them together.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] create a mockup on how to do duplicate detection

**Comment by MartinWahnschaffeSymeda** [comment]
Inspiration:

* ![grafik](https://user-images.githubusercontent.com/23217632/60902518-0aa2f780-a270-11e9-9e48-fdf52772ee1a.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I like this concept... We should talk about it during our next sprint..next tuesday

**Comment by MartinWahnschaffeSymeda** [comment]
Thoughts:

* query should be based on the existing case query (with filters and sorting)
* it joins with all cases that fullfill the following criteria:
  * disease and LGA is equal
  * report date is within same date range (e.g. +/- one month)
  * name is similar: would be great to use the same or a similar algorithm as we are using when creating a case. May be difficult to implement in SQL
* I would ignore date of birth and health facility for now
* query does paging (10 per page or so). Put results into a container -> "Load more"
* display either in TreeGrid or a custom component

![grafik](https://user-images.githubusercontent.com/23217632/61131289-1af9e300-a4b9-11e9-9700-e5990ff158e8.png)

**Comment by MartinWahnschaffeSymeda** [comment]
Main todos:

1. Add logic to return a number of case duplicate pairs based on #757 search algorithm. Likely a list of CaseDuplicateDto[2].
2. Display pairs in tree grid and do page based loading of additional cases
3. Do merge #1232 

Optional todos:

4. Switch pair entries to have the "better" one first

**Comment by MateStrysewskeSym** [comment]
- [ ] Don't use pagination for now; we might not need it
- [ ] Add a "Dismiss" button that removes the case in question from the container (will appear again on next reload, but might help with data management)

**Comment by MateStrysewskeSym** [comment]
- [ ] Make sure report date is empty by default
- [ ] Make similarity reference value configurable (properties)
- [ ] Case creation: add checkbox column (or radio buttons ideally)
- [ ] Change "Dismiss" to "Hide"
- [ ] Take out investigation status, outcome and point of entry from the grid

**Comment by MateStrysewskeSym** [comment]
- [ ] Change Long value in getCasesForDuplicateMerging to actual calculation
- [ ] Change query to retrieve CaseIndexDtos by using two queries that return a list (one with all parent elements, one with all child elements)
