### ISSUE TITLE
Immunizations module

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4081]
Pre-requisite for this to be released: #5986

Linked issues:
I: Immunization entity #4756 [5]
II: Vaccination entity #4763 [3]
II: Immunization overview and forms #4764  [5]
II: Immunization overview and forms (app) #5827 [5]
III: Immunization list for person forms #5828 [2]
III: Immunization list for cases, contacts and event participants #5905 [5]
III: Vaccination lists and create/edit forms #5843 [3]
III: Immunization automation #5946 [1]
IV: Vaccination refactoring #5909 [5]
V: Link recovery immunizations to recovered cases #5969 [2]

Follow-up issues:
Make the Vaccine and VaccineManufacturer enums configurable #5830 
Move information about vaccination being enabled to the diseaseconfiguation table #5831

### Situation Description
An Immunization (consisting of various vaccinations) module (especially for COVID-19) is highly requested for SORMAS.

In order to produce a minimal viable product, as fast as possible, to support international audiences making use of SORMAS, resources from the RKI (SurvNet) [DE], BAG MED [CH], FHIR7, and CDC have been consulted in an attempt to provide a module that may possibly address basic user needs.

Feedback welcome.

There are numerous steps/components that make up this request:
1. Allow vaccines to be configured in the Configurations (this will minimise data entry mistakes and speed up data capturing)
2. Introduce the Immunizations module functionality
3. Add Immunizations details to Case, Contact and Event Participant entities
4. Add Immunizations details to the Person entity

#### Overall mockup (as on 19.01.2021)

![image](https://user-images.githubusercontent.com/65529128/105061706-1c2aa980-5a7a-11eb-8a64-1681864eecae.png)

### Feature Description

**1. Allow vaccines to be configured in the Configurations**

Values:
Vaccine name, vaccine type, vaccine code, producer, external ID

---

**2. Introduce the Immunization module functionality** [please see Overall mockup (as on XX.XX.2021) on the top of the page for the latest version pertaining to UI specifications]
- new menu item with icon similar to that of a syringe (https://fontawesome.com/icons/syringe?style=solid for example) 
- the module has to be configurable in the database settings (i.e. can be switched on/off per instance)

---

**3. Add Immunization details to Case, Contact and Event Participant entities**

![image](https://user-images.githubusercontent.com/65529128/105025022-0e126400-5a4d-11eb-8f85-b26b829cc484.png)
- See #4137 for specifications on this element.

- Allow COVID-19 to show the 'Additional medical information' box with the 'Vaccination status for this disease' box (as is existing for Measles for example for Cases right now). 

![image](https://user-images.githubusercontent.com/65529128/105026381-bf65c980-5a4e-11eb-83e4-32b991b10ae8.png)

- If 'Vaccinated' is chosen, the '+ New Immunization' box on the right side becomes visible.

---

**4. Add Immunization details to the Person entity**

![image](https://user-images.githubusercontent.com/65529128/105037953-0491f780-5a5f-11eb-993e-fe33b49e8d9f.png)

Based on development of #3560 , also include Immunizations as a list element for the Person entity (viewing all Immunizations and adding/creating new Immunizations for all diseases).

---

### Additional Information
Data mappings (as on 19.01.2021)

Variable in UI | CH (MED) BAG | DE (SurvNet) RKI/BMG | INT (FHIR7) | Explanation/notes
-- | -- | -- | -- | --
Vaccination Status for this disease [added to the Case, Contact and Event Participant entities] | vacc_yn, Impfung, Wurde eine COVID-19-Impfung durchgeführt?, codelistElement, 1=ja, 2=nein, 3=unbekannt | 'StatusVaccination' "Jemals geimpft?": Select from Catalogue 'Status4' Status4 -1 = "-nicht ermittelbar-" 0 = "-nicht erhoben-" 10 = "Nein" 20 = "Ja" | Immunization.status, code, yes no unknown. | Vaccinated (1CH, 20DE), Unvaccinated (2CH, 10DE), Unknown (3CH, -1DE), Null (0DE)
Vaccine Name [added to the Vaccination Entity] | vacc_name, Name des verwendeten Impfstoffs, CharacterString | 'Vaccine' "Impfstoff": Select from Catalogue 'VaccineCVD' VaccineCVD  -1 = "-nicht ermittelbar-"  0 = "-nicht erhoben-"  201 = "mRNA (BioNTech / Pfizer)"  202 = "mRNA  (Moderna)"   203 = "vektorbasiert (Astra Zeneca)"  204 = "vektorbasiert (Johnson&Johnson bzw. Janssen-Cilag)"  205 = "rekombinant, adjuvantiert (Sanofi - GSK) 6. rekombinant, adjuvantiert (Novavax)" | Immunization.vaccineCode Code | If 'Other' is selected, show free-text field.
Vaccination Count [added to the Immunization entity] | vacc_dose, Anzahl der erhaltenen Impfdosen, Integer | 'VaccinationCount' "Anzahl der Impfungen": Select from Catalogue 'Number10'  -1 = "-nicht ermittelbar-" 0 = "-nicht erhoben-" 1-10 | - | Vaccination Count auto calculated based on the number of Vaccinations for this Immunization]
Date of first vaccination [added to the Immunization entity] | vacc_dt_first, Datum der ersten COVID-19-Impfung,date(yyyy-mm-dd) | - | One dateTime in Immunization.date | Date of first vaccination from the list of vaccinations on the Immunization list
Date of last vaccination [added to the Immunization entity] | vacc_dt_last, Datum der letzen COVID-19-Impfung,date(yyyy-mm-dd) | 'VaccinationDate' "Datum der letzten Impfung": Date field | -  | Date of last vaccination from the list of vaccinations on the Immunization list

**Comment by Marko-ilmkreis** [comment]
Thanks for the lot of work. 

I asked the relevant colleagues of our health departement about the vaccinations. They told me, that for us it makes only sense to fill in the vaccination if we have a contact or case. According to what we know we are only allowed to save the vaccinations of that persons, but not for all vaccinated persons if they are not a case, contact or event participant. This persons would have to proof the vaccination by the vaccination pass or similar. For that reason it would be good if there could be a check-box like

[_] Vaccination proofed / Impfung nachgewiesen 

or a pull-down-menu with

Vaccination proofed / Impfung nachgewiesen
Vaccination not proofed / Impfung nicht nachgewiesen
Vaccination will be proofed / Impfung wird nachgewiesen/Wurde zum Nachweis der Impfung aufgefordert


This might be special for Thuringia where the vaccinations are organized by the Association of Health Insurance Doctors in behalf of the state. Other states are organizing it by themself and having maybe lists of all vaccinated persons.

**Comment by Candice-Louw** [comment]
@Marko-ilmkreis - thank you for the feedback! [20.01.2021] This will be planned to be incorporated into the design.

**Comment by Candice-Louw** [comment]
WISH | DE:
Further wish from GA Fürth, Günzburg, Kelheim (Schulung and ticket system) - a map that shows in which village, district etc. there are already vaccinated cases and contacts.

Comment: this would only be possible at a later stage after the basic functionality of the module has been defined and is operational.  Could also be possible through the use of https://github.com/hzi-braunschweig/SORMAS-Stats once complete.

**Comment by Candice-Louw** [comment]
WISH | DE:
Dear Sormas team,
For the case processing in Sormas we need data fields for vaccination. The following fields are required:

- Vaccinated? (Yes No)
- Number of vaccinations (integer)
- Date of the last vaccination (date)
- Vaccine (selection list, centrally specified or configurable by the health department, should contain vaccines that are already in development in addition to those already approved - free text if necessary)

**Comment by bernardsilenou** [comment]
@Candice-Louw 
We already have vaccination documentation in the system for vaccine preventable diseases like measles (https://release-international.sormas.netzlink.com/sormas-ui/)
- We just need to refine it and activate for covid. This is how it looks  
![image](https://user-images.githubusercontent.com/12996724/105505088-d31c6480-5cc8-11eb-838f-2c79d5d781f2.png)

- As @Marko-ilmkreis  mentioned, if the goal is to document the vaccination status of the case, contact, ep, then we just need to add all the remaining variables and activate this for COVID. We did not include it initially because covid had no vaccine then.
- Since the immunization module presented in the other issue is more generic, I would suggest that we to not link them for now. When the immunization module would be ready, then we can then map data from immunization to the vaccination part of the case.

**Comment by bernardsilenou** [comment]
@Candice-Louw 
can we migrate this to a new issue? not to get confused with the main immunization ticket

**Comment by Candice-Louw** [comment]
@Johannes-Schmidt-GA-RT : Please feel free to add any additional comments/input/feedback.

**Comment by Johannes-Schmidt-GA-RT** [comment]
@Candice-Louw We don't need it in great detail. @bernardsilenou suggestion would be almost enough for us, the only thing missing is the vaccine that was vaccinated. This is all the information SurvNet needs.

**Comment by Candice-Louw** [comment]
@Johannes-Schmidt-GA-RT - great, thank you for the feedback!

**Comment by Candice-Louw** [comment]
@tobiasschellhorn @carolinverset @ftavin : Please feel free to add any additional comments/input/feedback.

**Comment by bernardsilenou** [comment]
I have added a summary for changes to be made for vaccination status here #4137.
We can then maintain this ticket for immunization module.

**Comment by Candice-Louw** [comment]
GK 23-Jan-21 00:17:

„Comirnaty“  is the commercial name of the vaccine produced by the company BioNtec; its international nonpropriotory name (INN) is „tozinameran“

Every medical product usually has a commercial name and a INN. 
Different companies can produce the same INN either under a different or under the same commercial name. 
Also the same Product can be marketed by the same company under different commercial names in different countries. And of course one and the same company can potentially produce more than one type of vaccine against COVID, so that the only truly identifying name is the INN, which is why it was invented. Unfortunately the INN is not alway used. 

So for identifying a vaccine it would be best to offer four fields
À) commercial name
B) INN
C) Company producing it
D) batch number „Chargen Nummer“

**Comment by Candice-Louw** [comment]
Won't be introduced for Person-only entities.

**Comment by Candice-Louw** [comment]
Reopened per discussion 02.03.2021

**Comment by bernardsilenou** [comment]
@MateStrysewske @Candice-Louw @JaquM @kwa20 
- In preparation against next Monday, I would suggest that we pick the main items here to create a very basic version that can be implemented in a sprint ie no management process module, import, etc ie just the entities  + links.
- In summary we would need 3 entities: 
     - immunization (mimicking contact)
     - vaccination  (mimicking followup visits for contacts)
     - immunization directory + detail export + basic filters:
     
- vaccinations are just "followup" of the immunization entity, thus 1 --> n
- I a contact person or ep is vaccinated after their 14 day followup, then we do not need to come back and register this information to the contact. Or for someone who is neither a case, contact or ep who got involved in the immunization program of the GE.

**Comment by bernardsilenou** [comment]
@Candice-Louw  @kwa20 just realized  that having the location/ facility attached to the vaccination would make things complex. In the new issue #4756  I added the facility to the immunization. If a person is to be immunized, then there can be only one responsible jurisdiction/ facility. If a vaccine has many doses, then they must get both doses at the same facility or document one of the two as the responsible facility, hope this is fine?

**Comment by kwa20** [comment]
@MateStrysewske @JaquM  Here some comments and further specifications for this module. These cover multiple sub-issues.

Entity https://github.com/hzi-braunschweig/SORMAS-Project/issues/4756:
- Add means of immunization field as selectable fields that subsequently enable sections (not null) - entity form and creation form (like seen for case origin)
    - Vaccination - enables vaccinations section and expected number of vaccinations field (default selection)
    - Recovery - enables recovery section
    - Vaccination/Recovery - enables vaccinations and recovery section
    - Other - enables subsequent free text field to specify other means of immunization

<img width="544" alt="meansOfImmunization" src="https://user-images.githubusercontent.com/70317594/123072061-807cdb00-d415-11eb-9a17-8ee44c220ac8.PNG">

- Add Immunization `startDate`, immunization `endDate` - defines the period in which the immunization is happening until the person acquires immunization
- Add `ImmunizationManagementStatus`: `scheduled`, `ongoing`, `completed`, `canceled`
    - `scheduled`: current date is before the startDate OR (current date is after startDate AND number of vaccinations = 0)
    - `ongoing`: current date is >= startDate AND number of vaccinations is >= 1 AND number of vaccinations is unequal to the expected number of vaccine doses
    - `completed`: number of vaccination entries equals the number of expected vaccine doses
    - `canceled`/`resume`: button to cancel which enables a free text to provide a reason for cancellation; button to resume immunization if previously canceled

- Add `ImmunizationProtectionStatus`: `pending`, `acquired`, `notAcquired`, `expired` - (non-editable) determines the protection status of the immunization for the disease
    - `pending`: If `immunizationManagementStatus` equals `scheduled` OR `ongoing`
    - `acquired`: If immunizationManagementStatus equals `completed`
    - `notAcquired`: If immunizationManagementStatus equals `canceled` - has to revert back to pending
    - `expired`: If current date is after the `validUntil` date
- Add Immunization `validFrom` and `validUntil` dates - defines the protection time frame of the aquired immunization; enabled when immunization equals acquired

<img width="503" alt="immunizationStatus" src="https://user-images.githubusercontent.com/70317594/123074922-09951180-d418-11eb-8e7e-b441cb64d46b.PNG">
<img width="470" alt="immunizationStatus3" src="https://user-images.githubusercontent.com/70317594/123074669-cd61b100-d417-11eb-8c34-e3e30b77c451.PNG">

- Add checkbox to freely overwrite the immunization status; if checked, make status editable

<img width="411" alt="immunizationStatus2" src="https://user-images.githubusercontent.com/70317594/123072955-4829cc80-d416-11eb-9a15-197cf247de81.PNG">

- Add a recovery section
   - Date field for 'Date of first positive test result'
   - Date of recovery
   - Option to link a case: Opens pop-up to select a case for same disease and same person or alternatively create; when linked, show case uuid and option to navigate

<img width="289" alt="recoveryImmunzation" src="https://user-images.githubusercontent.com/70317594/123077682-8fb25780-d41a-11eb-8b0d-a0978d4e3912.PNG">

Add the following feature configurations:
- IMMUNIZATIONS (true/false) - enables/disables the Immunization module
- IMMUNIZATION_MANAGEMENT_STATUS_AUTOMATION (true/false) - enables automatic calculation for immunization management status as seen above; if false, immunization management status is always editable (default true if IMMUNIZATION enabled)

Directory refinements:
-Add columns for (all sortable alphabetically):
    - Means of immunization
    - Immunization Management Status (instead of immunization complete in mock-up)
    - Immunization Protection Status
    - Last vaccination type
    - Date of recovery
- Add date period filters with filterable dates for:
    - report date
    - endDate
    - validUntil date
    - date of recovery
    - last vaccination date
    - first vaccination date

**Comment by Marko-ilmkreis** [comment]
@kwa20 have you planned to calculate the date of recovery based on the existing data in Sormas if the person was already a case? If yes, please show then the calculated dates for #5394 (for Germany only).

**Comment by MartinWahnschaffe** [comment]
Closing this, since the core module is already implemented. Follow-up issues are not done yet, but are not considered part of this epic.
