### ISSUE TITLE
Improve EventParticipant contact count queries

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4084]
### Feature and Problem Description

The queries used for determining the amount of contacts (with and without source cases in event) for each eventparticipant are relatively slow, which could lead to problems with large events.

### Proposed Change

Improve Queries.

### Additional Information
This is a screenshot of the current query used to determine contact counts where the source case is in the event: 

![image](https://user-images.githubusercontent.com/4655486/105162127-8000b100-5b12-11eb-993c-5e19321b324e.png)

**Comment by DavidBaldsiefen** [comment]
This is the suggested new query for event participants with source in event:

![image](https://user-images.githubusercontent.com/4655486/105162775-56945500-5b13-11eb-8fcf-d5b511088c30.png)

The other query only got slightly shorter, but its estimated cost (according to pgAdmin) and average runtime on my DB are also slightly better.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on the test.sormas.netzlink.com environment

**Comment by AndyBakcsy-she** [comment]
adding multiple contacts to the same Person would increase the contact count;
Person participant & source case is participant the contact count increases as vell
