### ISSUE TITLE
Samples | Bulk Edit mode for Admin Surveillance Supervisor account does not work and gives an error message

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4087]
### Steps to Reproduce
1. Log in with Admin Surveillance Supervisor 
2. Go to Samples
3. Select Bulk mode and select one or more samples 
4. Select delete and click on ok

### Expected Behavior
The samples should be deleted

### Actual Behavior
An error message is generated when the user tries to switch the focus from the pop-up window
### Screenshots
[server_error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5842033/server_error.txt)

### System Details
* Device:
* SORMAS version:SORMAS Version: 1.54.0-SNAPSHOT
* Android version/Browser:Chrome
* Server URL: test.sormas.netzlink.com
* User Role: Admin Surveillance Supervisor (Username: AB_ContSup)

### Additional Information
This issue is maybe related to #3904 

The Problem might be related to the UserRole that does not have sufficient Rights.
Similar issues is seen on the Cases page when the Bulk Edit mode is entered and any Action is taken

**Comment by Marko-ilmkreis** [comment]
Maybe is also related to #3965 and the rights management for the samples needs a review

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Nope, this bug is caused by the Admin Surveillance Supervisor not having the right to delete samples. We'll fix this for version 1.55.0.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Thanks. I had hope to solve our issue too.

**Comment by DavidBaldsiefen** [comment]
Maybe also related to #4281 ?

**Comment by syntakker** [comment]
After discussion with @MateStrysewske, the admin surveillance supervisor is granted the right to delete samples (the only option for bulk editing here).

Further cleanup:
Added null check in `SampleService.createUserFilter`, since its use in `SampleFacadeEjb.count` indicates that a possible  invocation with `criteria` null is intended:
```java
		...
		Predicate filter = sampleService.createUserFilter(cq, cb, joins, sampleCriteria);
		if (sampleCriteria != null) {
			Predicate criteriaFilter = sampleService.buildCriteriaFilter(sampleCriteria, cb, joins);
			filter = CriteriaBuilderHelper.and(cb, filter, criteriaFilter);
		}
		...
```

**Comment by raghupola-vg** [comment]
Tested on version 1.57.0-snapshot and issue is Fixed.
