### ISSUE TITLE
Error is displayed when region filter is removed after filtering for the responsible Contact officer/Surveillance Officer.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4093]
### Bug Description
An Error is displayed when the region filter is removed after filtering with the responsible contact officer on contacts Directory or surveillance officer on Case directory.

### Steps to Reproduce
1. Login to Sormas Web app as SurvSup
2. Access Case directory by clicking on Cases
3. Click on Show more filters - Select a responsible district and community -  Select the Responsible Surv Officer and click on apply filters.
4. Now Click on Responsible district field and remove the filter. An error is displayed as shown in the screenshot below.
5. Repeat steps 3 and 4 for Contacts Directory. - Same issue is observed.

### Expected Behavior
No error must be displayed and the data must be displayed/updated as per selected filters only after apply filters is clicked.
 
### Screenshots
![remove region or district filter when respondible officer is selected](https://user-images.githubusercontent.com/62763628/105197461-ed293c00-5b3c-11eb-8ba2-bfc2361560a2.PNG)

### System Details
* Device:
* SORMAS version: 1.54.0- Snapshot
* Android version/Browser: Chrome and Firefox
* Server URL: https://test.sormas.netzlink.com
* User Role: SurvSup or ContSup

### Additional Information
On the Events Directory the filters are auto reset without any error

**Comment by AndyBakcsy-she** [comment]
Verified Ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on the local environment
