### ISSUE TITLE
The quarantine end date can be set before its starting date

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4096]
### Feature Description
Case & contact data sheets 
### Problem Description
The quarantine and isolation end date can be set before the starting date. 
![353844DD-DFA1-4100-9AE4-9A86B2C3050C](https://user-images.githubusercontent.com/76884029/105323407-63c04b00-5bca-11eb-8589-8be54abf222a.jpeg)

### Proposed Change
Disable the option to set end date before start date to prevent contradictory time periods.

**Comment by bernardsilenou** [comment]
@kwa20 Lets have a review on this please

**Comment by bernardsilenou** [comment]
No longer in newer versions
