### ISSUE TITLE
Solve encryption problems of HUAWEI Mediapad T3 [1+X]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#410]
- [ ] find a solution
- [ ] re-activate forced encryption

Tasks

- [x] contact Huawei support
- [x] ask the community for help (try to find a working image)

Reset options: http://www.hardreset.info/devices/huawei/huawei-mediapad-t3-7/

Vendor: hw 
Country: meafnaf
Bootloader/Kernel: BG2-U01C199B002_BOOT/KERNEL
AP Version: System 5.0.0.57(0UVO)

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Let's have a phone call to discuss how to proceed with the Huawei devices

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Had another try with this today. I can't even make the system run after having done a factory reset. It keeps restarting the sign up process. Neither skipping, nor using a google ID nor huawei ID worked.

LineageOS doesn't seem to have a version for the mediapad T3 7.

Any progress on your side?

**Comment by hzi-braunschweig** [comment]
Dear Martin,

What is the way forward with this? Is there a way we can secure the app with the current tablets which we have bought? Thanks


Tom-Aba Daniel (MPH B.Sc)
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de
Mobile: +495316181-3124
________________________________

**Comment by MartinWahnschaffeSymeda** [comment]
Sent an email to HUAWEI support:

as part of a large-scale project, we are currently testing the HUAWEI MediaPad T3 7 (BG2-U01) as the hardware to be used (we already own 400 T3 devices). Unfortunately, there are problems with resetting the devices and encryption.

Here's what we did:
1. Update to the current version
2. Select "encrypt device" via the settings.
3. The device then restarts itself several times and then advances to enter the blocking pattern. 
4. Then "password correct, but data corrupt. need to reset tablet" appears.
5. The tablet would then be reset and must be set up.
6. Setup is now not possible. No matter if we choose "set up as new" or "restore a backup". In both cases, the question "Cloud" is followed by the EMUI logo and the process starts again from the beginning ("select language").

This means that it is currently not even possible to use the device unencrypted.
We ask for your support in solving the problem.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Any response from Huawei yet?

**Comment by MartinWahnschaffeSymeda** [comment]
No answer from Huawei yet. I have tried the support chat today. Say suggested to do a factory reset, etc. which is not working.

Result: We should send the malfunctioning devices (that can't be setup anymore) in.

**Comment by MartinWahnschaffeSymeda** [comment]
I had a look into the technology I identified to encrypt the database itself: https://github.com/sqlcipher/android-database-sqlcipher. 

There is no clean way to integrate it into the app the way it is currently build. The main reason being that we use ormlite to map entities to the database schema. There is a port of ormlite that comes with SQLCipher, but it is maintained by a single person, so it's quite likely that this will be dropped in the long-term (https://github.com/Andoctorey/ormlite-sqlcipher). I wouldn't suggest to use it at this point.

A long-term alternative could be to use couchbase or mongodb lite versions for the android app. We need to figure out how well their performance is. Couchbase seems to be using SQLite under the hood.

BTW: I had a look at the Sync Gateway function of Couchbase again. It is somehow possible to selectively define which data is accessible to a user and synchronized. The basic concept seems to be the same we have chosen. During push the server rejects all documents that have been changed by other users in the meantime. During pull it is only possible to let either the server or the client win (fixed). There doesn't seem to be a way to do field-based conflict handling during pull replication on mobile devices: https://blog.couchbase.com/document-conflicts-couchbase-mobile/.

@hzi-braunschweig I remember you said there is a new version for the tablet. Have you had a try with the encryption?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda This is great news. I think we should use couchDB if this helps to encrypt the database itself on the mobile app because, i tried to encrypt the tablet which had the latest updated version and it only formatted the tablet to a new one and was not encrypted.

**Comment by MartinWahnschaffeSymeda** [comment]
It's just a long-term option. We need to carefully evaluate this. In addition we should at least wait until MongoDB for Android is out of beta, since this may be another option. 
This would only be a replacement for the SQLite database on mobile devices and have no influence on the synchronization process and the server backend.

**Comment by hzi-braunschweig** [comment]
Ok then.

Tom-Aba Daniel (B.Sc MPH)
Doktorand
PhD Epidemiology Programme, Hannover Medical School (MHH),
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by MartinWahnschaffeSymeda** [comment]
See #905
