### ISSUE TITLE
Exposure tables are styled badly

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4110]
### Bug Description

- [ ] The first column is offset by 1 pixel because there is no header
- [ ] Sorting a column leads to part of the grid being removed and the text style changing

### Steps to Reproduce
1. Go to a case -> epi data

### Expected Behavior

Don't do this.

### Screenshots
![image](https://user-images.githubusercontent.com/4655486/105480848-92135880-5ca6-11eb-85e0-35a3f644c004.png)
![image](https://user-images.githubusercontent.com/4655486/105480875-9a6b9380-5ca6-11eb-9f99-b0baf486f44d.png)

### System Details

* SORMAS version: 1.54
* Android version/Browser: Firefox

**Comment by DavidBaldsiefen** [comment]
Maybe #4053 can be solved in the same run, too.

**Comment by Toap777** [comment]
This bug seems to exist because of the css classes "v-table-header-cell", "v-table-header-cell-asc" and "v-table-header-cell-desc" applie different styles to the table header. Should be fixed by defining custom css. But this is only the "quick and dirty way".

**Comment by Toap777** [comment]
![grafik](https://user-images.githubusercontent.com/44776957/106304017-1cd1f580-625b-11eb-9760-cc91823dbb7e.png)

I could fix the second issue manually by adding the styles "text-transform, font-weigt and border bottom" manually to the ".sormas .v-table-caption-container" group. 
If you dont sort the table this styles are added by the rule 

.sormas .v-table .v-table-header .v-table-header-cell .v-table-caption-container {
	text-transform: uppercase;
	font-weight: 600;
	border-bottom: 2px solid #CDD8EC;
}
which is not while  sorting. I can edit css to fix this issue, but i dont have any summary of the css structure, so dont know if I will break something.

**Comment by DavidBaldsiefen** [comment]
@Toap777 I think `v-tables` are only used in 3 or 4 parts of the code, as most charts use `v-grid`. You can try editing the corresponding files in sormas and then just check each place induvidually, if anything breaks (I doubt it). You can find out where Vaadin Tables are used by using ctrl+shift+f in IntelliJ and checking where the `AbstractTable` class is used (I think it was named like that). Good find!
