### ISSUE TITLE
Don't automatically load duplicates when switching to the case merge duplicates view [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4111]
### Problem Description
The case merge duplicates view can be very slow when there are a lot of potential duplicates (currently the view opens with the creation date filter set to the last 30 days, but this can still be a lot). This especially annoying when a user mistakenly opens the view.

### Proposed Change
- [ ] Don't automatically load the cases. Instead make the user confirm the selected filters first
- [ ] Display a big label "Loading duplicates may take a few minutes. Please confirm the selected filters." instead of the grid in the center of the screen.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
