### ISSUE TITLE
CQ/CT value field does not get enabled during result entry in sample creation window [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4125]
### Bug Description
When entering a pathogen test result in the sample creation window, the cq/ct value field does not get enabled when PCR or cq value detection were selected as the type of test. This also affects the DEMIS interface.
### Steps to Reproduce
1. Add a new sample in any entity.
2. Add a test result in the same process.
3. Select either PCR or cq value detection as the type of test.
4. Check for subsequent cq/ct value field.

### Expected Behavior
When PCR or cq value detection were selected as the type of test, the cq/ct value field should get enabled. This should also be true when processing lab messages through the DEMIS interface.
### Screenshots
<img width="475" alt="cq ctValueMissing" src="https://user-images.githubusercontent.com/70317594/105725988-dfebc300-5f29-11eb-9dcc-d70d06068869.PNG">
<img width="329" alt="cq ctValueMissing2" src="https://user-images.githubusercontent.com/70317594/105726021-e9752b00-5f29-11eb-8de4-128a2155276b.PNG">

### System Details
* Device:
* SORMAS version: 1.54.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
I just happen to see this issue now now, If it not to late, can we migrate cq value detection to PCT, its duplicate.
CQ value detection is not a type of test but threshold af a PCR test.
@MateStrysewske @kwa20  Any idea why this was added as a type of test?

**Comment by kwa20** [comment]
@bernardsilenou judging from when it was translated on crowdin, it has been around for at least a year.

**Comment by bernardsilenou** [comment]
@kwa20 OK, not bad just duplicate, in case we have to map type of test to external systems, then we just need to check both entries. If not possible to be handles in this issue, then we can create a new one.

**Comment by MateStrysewske** [comment]
@bernardsilenou It's very likely that it was added as a type of test because we were requested to do so ;)

**Comment by bernardsilenou** [comment]
@MateStrysewske I also think so, do we need a new ticket to merge it with PCR? I checked with other and decision is to remove it.

**Comment by MateStrysewske** [comment]
@bernardsilenou Yes, that would be good

**Comment by raghupola-vg** [comment]
Tested on version 1.55.0-Snapshot on test environment and an Error appears while saving the test result.
![Error at CQ_CT value field](https://user-images.githubusercontent.com/62763628/106872741-ede0d700-66d3-11eb-8ba4-a3d7eb87d53a.PNG)

**Comment by raghupola-vg** [comment]
Also when the "Result verified by Lab Supervisor" option is not selected or any other field such as Type of Test, Date and Time is not selected, the error message doesn't provide the details. 
Expected: Provide a proper error message to the user indicating the cause of the error.
![Missing correct Error details for Result verified selection](https://user-images.githubusercontent.com/62763628/106875536-0f8f8d80-66d7-11eb-9efa-3e2b85cbae92.PNG)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.55.0-snapshot on local environment
