### ISSUE TITLE
Sormas2Sormas Button to synchronize is overlapping in DE

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4127]
### Bug Description

The button to synchronize the case with other health offices is overlapping (see screenshot). The resolution is 1920x1200 on a 24" screen.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/105806757-d489ad80-5fa4-11eb-9dbd-3a1fd8fd4505.png)

### System Details
* Device: Win10
* SORMAS version: 1.55 snapshot
* Android version/Browser: Firefox/Edge
* Server URL: https://test-de1.sormas.netzlink.com

**Comment by Marko-ilmkreis** [comment]
The same is with subordinate events in German:

![grafik](https://user-images.githubusercontent.com/74791118/105811737-5a115b80-5fad-11eb-9808-602df58c21f9.png)

**Comment by kwa20** [comment]
I'll close this issue because Sormas 2 Sormas has already been changed in a way that makes this issue no longer applicable
