### ISSUE TITLE
Contact directory summary

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#413]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
![image](https://user-images.githubusercontent.com/19344651/32980731-71969914-cc6c-11e7-9148-b245b4e8455d.png)

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/32980765-fa0252ac-cc6c-11e7-9e53-75971ff570f2.png)

**Comment by MartinWahnschaffeSymeda** [comment]
See #460

**Comment by MartinWahnschaffeSymeda** [comment]
Short-term fix: #463

**Comment by MateStrysewskeSym** [comment]
I think we should discuss whether we actually still need this.
