### ISSUE TITLE
Sorting "facility" in the user management results in error and subsequently disables editing of users

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4130]
### Bug Description
Sorting "facility" in the user management results in error and subsequently disables editing of users when the error message was closed. The page then has to be reloaded.
### Steps to Reproduce
1. Go to the user management as an admin.
2. Try sorting the facility column.

### Expected Behavior
Facility column should be sortable without receiving an error message and subsequently disable editing of users.
### Screenshots
<img width="1116" alt="Screen Shot 2021-01-26 at 11 48 22 AM" src="https://user-images.githubusercontent.com/70317594/105836131-0d3d7d00-5fcd-11eb-8388-bcd07a5be58f.png">

### System Details
* Device:
* SORMAS version: 1.54.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on the local environment
