### ISSUE TITLE
Event search

### ISSUE THREAD

**Issue by TheGaHTK** [hzi-braunschweig/SORMAS-Project#4136]
Dear Sormas-Team,

if we create an event we have to add them first as contatc and connect them after that to the event, otherwise we are not able to search for them and find them without knowing the specific event.

It would be great, if we could find people inside events without adding them twice by connecting both databases or any other methode.

Thank you very much and stay healthy.

Best regards

Julian

**Comment by Marko-ilmkreis** [comment]
@TheGaHTK This will come when the issue #3560 (General Person entity) is introduced. We are all waiting on it. Its very important for us.
