### ISSUE TITLE
Activate vaccination status for COVID-19 cases, contacts and event participant [3]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4137]
### Situation Description
* The case form for vaccine preventable diseases has the "additional medical information" section containing information about the vaccination status of the case person. Since COVID-19 did not have a vaccine, we did not activate these vaccine related variables. 
### Feature Description
* Add/adjust these fields for cases, contacts and event participants (start with cases and push that to a feature branch, continue with contacts and then event participants); all fields EXCEPT vaccine name and manufacturer need to be visible for all diseases that vaccinationStatus is currently enabled for, plus Covid-19; vaccine name and manufacturer are only visible for Covid-19

* Add the new fields to the detailed and custom case export, the detailed contact export and the detailed event participant export

* List of variables to capture (all countries, all instances):
    - vaccination status for this diseases:  vaccinated/unvaccinated/unknown (this already exists)
	if  vaccination status == vaccinated, show the following additional variables in this order:
    - date of first vaccination	
    - date of last vaccination (exist already)
	- source of vaccination information: vaccination card/ oral communication/ no evidence, unknown (this exist but  no evidence and unknown options are to be added)
	- `VaccineName`: drop down with options: (options for covid only, other diseases has only others + free txt. 
	If possible this list should be configurable for users to upload what they want, else just hard code it for now.)
	     - Pfizer–BioNTech 
	     - Moderna 
	     - Oxford–AstraZeneca
	     - Ad26.COV2.S 
	     - NVX-CoV2373 
	     - Sanofi - GSK	    
        - Unkown             
	     - Other (free txt)
  
	 - `VaccineManufacturer`: dropdown with options; this should have a reference to a vaccine name, selecting a vaccine name automatically selects the associated manufacturer (relation will be specified in a comment by @Candice-Louw below)
	   - AstraZeneca
	   -  Johnson & Johnson
	   -  Moderna
	   -  Novavax
	   -  Pfizer & BioNTech
	   -  Sanofi & GlaxoSmithKline
	   - Unknown
	   -  others + free text
	    
	 - number of valid doses= rename to "vaccine dose"; add a validator to this field that prevents saving when anything but integers from 1 to 10 (or empty) are typed in; keep the type of the field because existing servers will have values with strings in here
	 
	 - INN (description: International non-proprietary name): free txt
	 - Batch number:  free txt	 	 
	 - UNI code (description: Unique ingredient identifier code): free txt
	 - ATC code: free txt
	
### Additional Information
Final mockup:
![image](https://user-images.githubusercontent.com/65529128/106485870-569c3980-64b1-11eb-9008-2560451af577.png)

**Comment by kwa20** [comment]
@HolgerReiseVSys @JonasCir @markusmann-vg Also relevant for the SurvNet Interface.

**Comment by HolgerReiseVSys** [comment]
> @HolgerReiseVSys @JonasCir @markusmann-vg Also relevant for the SurvNet Interface.

@kwa20 Is this compatible and complete?

| | |
|-|-|
StatusVaccination | Jemals geimpft?
VaccinationCount | Anzahl der Impfungen
VaccinationDate | Datum der   letzten Impfung
Vaccine | Impfstoff

| Vaccine |
|-|
-nicht ermittelbar-
-nicht erhoben-
mRNA (BioNTech / Pfizer)
mRNA  (Moderna)
vektorbasiert (Astra Zeneca)
vektorbasiert (Johnson&Johnson bzw. Janssen-Cilag)
rekombinant, adjuvantiert (Sanofi - GSK) 6. rekombinant, adjuvantiert (Novavax)

**Comment by kwa20** [comment]
@bernardsilenou could we add the "type" (e.g. mRNA) in parentheses behind the name? the manufacturer field could be filled depending on the vaccine name too right?

@HolgerReiseVSys Yes, I think it's fine, we can map the vaccine name to the SurvNet variables.

**Comment by HolgerReiseVSys** [comment]
> @HolgerReiseVSys Yes, I think it's fine, we can map the vaccine name to the SurvNet variables.
How is VaccinationCount covered?
Also, how would we map vaccine "others"?

**Comment by kwa20** [comment]
@HolgerReiseVSys We can't since SurvNet does not have a corresponding field. I guess we would have to map it to "nicht ermittelbar" since SurvNet doesn't consider other entries. If it comes from SurvNet, "nicht ermittelbar" would always be unknown.

**Comment by bernardsilenou** [comment]
> @bernardsilenou could we add the "type" (e.g. mRNA) in parentheses behind the name? the manufacturer field could be filled depending on the vaccine name too right?
> 
I did not realize that the names already exist in SurvNet. Yes we can add mRNA to the vaccine name. One thing we need to maintain is the name of the company. I would edit the name in the specification with mRNA in bracket since it just the type not a name.


> @HolgerReiseVSys Yes, I think it's fine, we can map the vaccine name to the SurvNet variables. We would only need an unknown variable to map to "nicht ermittelbar".

**Comment by Candice-Louw** [comment]
@marko-ilmkreis @TheGaHTK @Johannes-Schmidt-GA-RT - please feel free to provide feedback/input? @marko-ilmkreis : would you still need the '[_] Vaccination proofed / Impfung nachgewiesen' field to be added for use in Thüringen?

**Comment by Marko-ilmkreis** [comment]
That looks very good and logic for me. Good approach! We wouldn't need the "Vaccination proofed" as the "source of vaccination information" is still planned. I have the suggestion that this field is mandatory if vaccination status == vaccinated. 

If then "source of vaccination information" == vaccination card the following fields should be mandatory:

- vaccine name
- number of valid doses
- date of first vaccination
- date of last vaccination

This details could be get from the vaccination card.

The question is, what happens if the details are not full readable (doctors handwriting :-)). Maybe a checkbox close to "source of vaccination information: vaccination card" with "[_] details of vaccination not given by card" or similar

**Comment by AxelNennker** [comment]
A few remarks:
- coding information like mRNA into the value of a field is usually not a good idea. My opinion is, if the information is needed then it should be in its own field in the database. If it is not needed then leave it out. Coding extra information into values leads to troubles in the future. Usually it is known from the vaccines name which kind of vaccine it is.
- I suggest to have an autocomplete in free text fields. That might lead to fewer variations and misspellings of values.
- Having synonyms resolved in free text fields might be good feature: Gam-COVID-Vac Lyo and Sputnik V
- A warning sent to Sormas admins if free text entry is entered would help keep the number of free text entries low. The Sormas admin might add the value to the list of know values. I think free text values are a sign that there needs to be a review or of users using the free text in an unintended way. This is not always a bad thing but should be reviewed.

Does the 'Technische Spezifikation Impfpass' need to be concidered?
https://mio.kbv.de/pages/viewpage.action?pageId=34668999

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis I disagree with making any of this mandatory. In general, our experience is that we should be very careful with adding mandatory fields because it is always possible that some information is missing, for whatever reason.

@kwa20 @bernardsilenou Any feedback to the suggestions by @AxelNennker?

@AxelNennker Point 2 and 4 make sense and should be done at some point, but are out of scope right now, unfortunately.

**Comment by MateStrysewske** [comment]
@bernardsilenou Will Nigeria and Ghana be okay with renaming the "number of valid doses" field?

**Comment by bernardsilenou** [comment]
@AxelNennker I agree with you not to add the type to the name. The reason whey I did not add the type was to minimize data collection because the "Unique Ingredient Identifier (UNII) code:" is the most important and if we know UNII, name, etc, then we can deduce the type, just as as you said. I would also suggest we just drop it out.
@kwa20 when translation we should use the same names as in SurvNet.
I did not understand the issue with autocomplete for free txt. If we know the options that users would type, then we would not make them as free txt in the first place.

**Comment by bernardsilenou** [comment]
@Candice-Louw @MateStrysewske Total number of vaccinations or vaccine dose or number of vaccine dose is the same thing. Let me have a look at some WHO forms and validate the name. We can then translate accordingly RKI

**Comment by Candice-Louw** [comment]
RKI-SurvNet requirements 01.02.2021 -

SurvNet var | Title de-DE
|-|-|
StatusVaccination | Jemals geimpft? 
VaccinationCount | Anzahl der Impfungen
VaccinationDate | Datum der letzten Impfung
Vaccine | Impfstoff

| Vaccine |
|-|
-nicht ermittelbar-
-nicht erhoben-
mRNA (BioNTech / Pfizer)
mRNA  (Moderna)
vektorbasiert (Astra Zeneca)
vektorbasiert (Johnson&Johnson bzw. Janssen-Cilag)
rekombinant, adjuvantiert (Sanofi - GSK)
rekombinant, adjuvantiert (Novavax)

**Comment by bernardsilenou** [comment]
On NCDC form its called "Number of vaccine doses", while on CDC form its called "Vaccine Dose" and defined as the "number of vaccine"
The reason why I suggested a change in the name was that there is also an administration code, and the last integer of the code is the vaccination dose, eg 91300, 0001A and 0002A fro Pfizer-BioNTech vaccine. Not everyone would be able to read the dose from the administration code.
Whats your suggestion of using the same field for administration code?
If it make sense,then we keep it as it is
it not then we name it "Vaccine Dose" or "Number of vaccine doses" + validation to fall in 0 to 10 (I do not know if we have a disease in the system that need more then 10 doses)

**Comment by Candice-Louw** [comment]
@bernardsilenou - the datatype from RKI/SurvNet is Integer, ranging from 1-10:
'VaccinationCount' "Anzahl der Impfungen": Select from Catalogue 'Number10'  -1 = "-nicht ermittelbar-" 0 = "-nicht erhoben-" 1-10
For the BAG, type Integer is also required:
vacc_dose, Anzahl der erhaltenen Impfdosen, Integer

For DE and CH it would make more sense to split the fields, please.

**Comment by bernardsilenou** [comment]
@Candice-Louw I have deleted the administration code because not user asked for it. Please have a second look.

**Comment by Candice-Louw** [comment]
@bernardsilenou - great, thank you!  @MateStrysewske - please let us know if there is anything else you need specified.

**Comment by kwa20** [comment]
<img width="953" alt="Screen Shot 2021-02-01 at 3 00 57 PM" src="https://user-images.githubusercontent.com/70317594/106468606-71b17e00-649e-11eb-83db-77acb57f2dbb.png">

**Comment by bernardsilenou** [comment]
@kwa20 Good mockup
Unique Ingredient Identifier (UNII)  == International non-proprietary name (INN), please can you drop International non-proprietary name (INN)?

**Comment by kwa20** [comment]
@bernardsilenou fine for me. Should we make it INN/UNII Code or just scratch one of them?

**Comment by bernardsilenou** [comment]
It would be good to use the full name name not only code,
Unique Ingredient Identifier (UNII) is what is used on the the wilipedia description page of all the vaccines.
<https://en.wikipedia.org/wiki/Pfizer%E2%80%93BioNTech_COVID-19_vaccine>

I can stress on using the full name not only the codes, any of them does not harm.

**Comment by Candice-Louw** [comment]
@bernardsilenou - this came straight from G:

GK 23-Jan-21 00:17:

„Comirnaty“ is the commercial name of the vaccine produced by the company BioNtec; its international nonpropriotory name (INN) is „tozinameran“

Every medical product usually has a commercial name and a INN.
Different companies can produce the same INN either under a different or under the same commercial name.
Also the same Product can be marketed by the same company under different commercial names in different countries. And of course one and the same company can potentially produce more than one type of vaccine against COVID, so that the only truly identifying name is the INN, which is why it was invented. Unfortunately the INN is not alway used.

So for identifying a vaccine it would be best to offer four fields
À) commercial name
B) INN
C) Company producing it
D) batch number „Chargen Nummer“

Is this in line with what you propose i.e. using only UNII?  Then we remove INN and have only field UNII?

**Comment by bernardsilenou** [comment]
@Candice-Louw @kwa20 Now we got !
UNII is a unique code that corresponds to the INN (molecule name), eg 5085ZFP6SJ corresponds to TOZINAMERAN, the vaccine Pfizer–BioNTech.
Conclusion: We keep both.

@kwa20 Please can you make this minor change on the moc:
 * Give the full names + code of the variables: Unique Ingredient Identifier (UNII), International non-proprietary name (INN), so users can easily translate and understand. Hope we have space for that.
 *  Swap positions of INN and ATC code, INN is a name an all the others that follow are codes

**Comment by Candice-Louw** [comment]
![image](https://user-images.githubusercontent.com/65529128/106485870-569c3980-64b1-11eb-9008-2560451af577.png)

**Comment by MateStrysewske** [comment]
@Candice-Louw Does it actually make sense to have dropdowns for both the vaccine name and the manufacturer? Doesn't one vaccine also map to one manufacturer? An alternative could be to show the manufacturer just for information purposes, but selecting "Pfizer–BioNTech" as the vaccine name and "Moderna" as the manufacturer doesn't seem to make sense.

**Comment by Candice-Louw** [comment]
@MateStrysewske @leventegal-she  - Agreed. However, drop-downs may make sense in this context >

Logic:
- Select vaccine name from drop-down > Auto-fill manufacturer drop-down (where possible)

- Select "other" vaccine name from drop-down > fill free-text field > select existing manufacturer from drop-down

- Select "other" vaccine name from drop-down > fill free-text field > select "other" manufacturer from drop-down > fill free-text field

Or?

**Comment by Candice-Louw** [comment]
@bernardsilenou - would it make sense to have the vaccine name (list) and the manufacturer (list) in roughly the same order then?

**Comment by MateStrysewske** [comment]
@Candice-Louw Yes, I guess that makes sense.

Further refinements:

* `VaccineManufacturer` enum should have a reference to a `VaccineName` entry, selecting that vaccine name would automatically select the associated manufacturer in the dropdown
* Add a validator to the field indicating the vaccination doses that prevents saving any value except integers from 1 to 10 (or empty)

**Comment by MateStrysewske** [comment]
@Candice-Louw Can you please provide the associations of vaccine names and manufacturer?

**Comment by bernardsilenou** [comment]
@All, Sorry to join the conversation late, was in a meeting.
I think your specifications are perfect.
@MateStrysewske   question pls
* These vaccine related variables newly added would appear for all vaccine preventable diseases, right?
* The enums and refernces defined here applied to only COVID since for other disease we would have NA + other ?

**Comment by Candice-Louw** [comment]
VaccineName | VaccineManufacturer | INN | type | UNII | Brand Name/other names |
|--|--|--|--|--|--|
Pfizer–BioNTech COVID‑19 vaccine | BioNTech/Pfizer | tozinameran |  mRNA | 5085ZFP6SJ | Comirnaty | -
Moderna COVID-19 Vaccine | Moderna | - | mRNA | EPK39PL4R4 | mRNA-1273
Oxford–AstraZeneca COVID-19 vaccine | AstraZeneca | - | vectorbased | B5S3K2V0G8 | -
Ad26.COV2.S | Johnson & Johnson | - | vectorbased |  JT2NS6183B | -
Novavax COVID-19 vaccine | Novavax | - | adjuvanted recombinant | - | -
No Vaccine (delay in development till end of 2021) | Sanofi-GSK  | - | adjuvanted recombinant | - | -

**Comment by MateStrysewske** [comment]
@bernardsilenou Exactly; and yes, vaccine name and manufacturer are only visible for Covid-19
@Candice-Louw Thanks!

**Comment by Candice-Louw** [comment]
@leventegal-she - please note the change of the variable in the first column, last row - from "No vaccine (...)" to "Sanofi-GSK".

**Comment by Candice-Louw** [comment]
@leventegal-she 
Please feel free to email me directly if it is easier - candice.louw[at]helmholtz-hzi.de
Apologies for the back-and-forth on this.

**Comment by MateStrysewske** [comment]
Follow-up issue: #4266

**Comment by AndyBakcsy-she** [comment]
Validated the web Implementation of this ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT  on the local environment.
Cases,Contacts, Event Participant  - OK
Mobile app  should be tested only for cases

**Comment by raghupola-vg** [comment]
Tested on Mobile app for Cases and above issue logged.
