### ISSUE TITLE
Case directory summary

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#414]
![image](https://user-images.githubusercontent.com/19344651/32980756-c4c7e660-cc6c-11e7-951c-798eb67ec2ab.png)
@MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
Short-term fix: #463

**Comment by MateStrysewskeSym** [comment]
I think we should discuss whether we actually still need this.
