### ISSUE TITLE
Thanks for the work!

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4148]
This could be closed. :-)

 Its just to say Thank you for the great work auf the developer team of Sormas. Nevermind if from HZI or the attending companies.

Thank you to @Candice-Louw @bernardsilenou @MateStrysewske @kwa20 @syntakker @JonasCir @DavidBaldsiefen  @MartinWahnschaffe and the other not mentioned by me.

**Comment by kwa20** [comment]
@kwa20 Thanks a lot for the encouraging words!

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Thank you so much! :)

@kwa20 It's kinda funny that you tagged yourself :D

**Comment by kwa20** [comment]
@MateStrysewske My mistake! :D

**Comment by DavidBaldsiefen** [comment]
![grafik](https://user-images.githubusercontent.com/4655486/105984448-6b846180-609a-11eb-8756-e1f22fde00b2.png)

**Comment by Marko-ilmkreis** [comment]
> 
> 
> ![grafik](https://user-images.githubusercontent.com/4655486/105984448-6b846180-609a-11eb-8756-e1f22fde00b2.png)
> 

That is so funny :-) Thank you @kwa20 for the mistake and @da for the picture!

**Comment by JonasCir** [comment]
@Marko-ilmkreis Thank you for the kind words!
We are super happy that you contribute to this project :) The insight and comments you provide really help us to understand what is need. So also a big "Thank you" to you.  Share the word that SORMAS is open source and encourage people to contribute!

**Comment by JonasCir** [comment]
Also @Marko-ilmkreis : There is a [gitter](https://gitter.im/SORMAS-Project) chat where you can reach out to single devs and contributors if need be :)

**Comment by Marko-ilmkreis** [comment]
@JonasCir Thank you for the hint with gitter!

I think mainly the "normal" colleagues in the health offices didn't know what open source mean and  for others it may be a problem to decribe feedbacks in English. Its really time for a possibility to interact together (health offices, OEGD, HZI) on a closed community in Germany. This would be a very good base to discuss important changes on Sormas and to get a more qualified feedback. As I had nothing to do with our health office until November  (working ususally in the alien authority and having an IT-background).

**Comment by Candice-Louw** [comment]
Thank you @Marko-ilmkreis for the kind and encouraging words! 🎈  It is much appreciated.  Thank you also for being ready to share knowledge, feedback and respond to the many questions we have.  Your contributions are highly valued.
