### ISSUE TITLE
[SurvNet Interface] Add subcategories for case classification

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4152]
### Situation Description
The RKI introduced subcategories for the case classification which depend on the type of test that was performed for cases. Such are differentiated by PCR, Culture and Antigen detection test.
### Feature Description
Introduce a drop-down field called "subcategory" next to case classification that gets enabled when either confirmed, confirmed with no symptoms or confirmed with unknown symptoms were selected. This feature is only applicable for germany.

confirmed > 
- (null)
- C1. PCR or culture
- C2. Antigen detection test

confirmed with no symptoms > 
- (null)
- D1. PCR or culture 
- D2. Antigen detection test

confirmed with unknown symptoms > 
- (null)
- E1. PCR or culture
- E2. Antigen detection test

<img width="779" alt="Screen Shot 2021-01-27 at 11 37 07 PM" src="https://user-images.githubusercontent.com/70317594/106063535-a1f0c980-60f8-11eb-9eff-33882f43f929.png">

<img width="777" alt="Screen Shot 2021-01-27 at 11 18 38 PM" src="https://user-images.githubusercontent.com/70317594/106062868-ac5e9380-60f7-11eb-95f7-246f322879f3.png">

### Possible Alternatives
We could also just introduce two variables as C1., D1., E1. PCR or culture; C2., D2., E2,. Antigen detection test. The separated version would be less messy of a string though.

**Comment by MateStrysewske** [comment]
@kwa20 I don't know if I agree with adding this to SORMAS. I think this information should be calculated by looking at the pathogen tests performed on the case in question. Do you think that's possible?

**Comment by kwa20** [comment]
@MateStrysewske I generally agree. Are we then talking about a mere informative "field" in SORMAS, meaning that depending on the performed tests (only considering positive results), the respective classification would be shown? (e.g. case (symptomatic) has a linked sample with a positive test, test type = PCR; C1. shown next to case classification C.?)

If all 3 test were performed (unlikely but possible), C,D, E1. should be shown since it fulfills the reference definition in SurvNet, whereas C, D, E2. doesn't.

**Comment by kwa20** [comment]
@MateStrysewske I talked to the RKI and the differentiation is not specifically visible in the categories in SurvNet, so I agree that we might not implement this for now and see if it applies in the future. They do however show whether the reference definition is fulfilled or not. We also got feedback from users that would like to see this differentiation of 1 and 2, that was the initial reason to create this issue. I'll let you know when I clarified this.

**Comment by bernardsilenou** [comment]
I just happen to fall on this one now:
- I agree with @MateStrysewske not link the case classification with the pathogen tests of a sample of the case.
- the case classification is a derived varaible bases on users opinion + final lab classification of pathogen tests of samples of the case. 
- For one case, there can be many samples and each sample has many and different test types, thus a clerically confirmed case can be linked to all the test types described above.

**Comment by kwa20** [comment]
I'll close this issue due to its current irrelevance
