### ISSUE TITLE
Provide SQL statements to delete cases and contacts from the database [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4156]
### Problem Description
In France we have a lot of cases and contacts in the system that are no longer relevant and need to be fully deleted.

### Proposed Change
- [x] Provide an SQL statement that deletes a set of contacts, including all child data (e.g. tasks, samples)
- [x] Provide an SQL statement that deletes a set of cases, including their contacts and all child data

History tables don't need to be included here.

Important: Actual deletion of data will lead to problem when the mobile app or other data synchronization mechanisms are used on the same system. For the given use case this is not relevant and can be ignored.

**The goal of this issue is NOT to provide a fully fledged deletion mechanism for data!**

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
I think we may also need:
Provide an SQL statement that deletes a set of events, including all child data (e.g. e_tasks, e_actions, event participants, ep_samples, etc)
