### ISSUE TITLE
[Climedo Integration] Contacts > Follow-up visits > Comment field not transferred

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4161]
### Bug Description
SORMAS updates introduced erroneous mappings to/from the Climedo app. The following mapping is proposed to correct this. @FredrikSchaeferVitagroup should know what to make of the below :-)

eDCOV19Q-20200916_first_symptom_description -> comments
eDCOV19Q-20200916_symptoms_otherquestions -> visit remarks
eDCOV19Q-20200916_other_symptoms_description -> "andere Symptome angeben"

### Steps to Reproduce
1. Use Climedo Symptom diary to transfer symptoms with a comment to SORMAS
2. View the entries in SORMAS:
Contacts > Open Contact > Follow-up visits > New Visit/Edit Visit
3. 'Comments' field is empty

### Expected Behavior
Comments and additional fields should be transferred and visible.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/106149232-50891e80-617a-11eb-8009-f1aee6b93af5.png)

### System Details
* Device: Web
* SORMAS version: 1.53+
* Android version/Browser: All
* Server URL: https://test1402.sormas-oegd.de/sormas-ui/
* User Role: admin

### Additional Information
@ErikMarzHZI - please provide additional screenshots in the comments below.

**Comment by ErikMarzHZI** [comment]
Here is the sentence written into the supposedly linked comment field:

![phone](https://user-images.githubusercontent.com/77120244/106152716-11f56300-617e-11eb-820b-8daa28aa7920.jpg)

Here the empty comment field on SORMAS after submission of the sentence above:

![climedo](https://user-images.githubusercontent.com/77120244/106152801-23d70600-617e-11eb-8579-910bae293f0f.jpg)

**Comment by FredrikSchaeferVitagroup** [comment]
SORMAS already provides all the fields for upload. It's now on climedo to implement the synchronization. They already reached out to us and are probably working on it.
I see nothing to do here from our side (except for later verifying that the field is filled by climedo).

**Comment by Candice-Louw** [comment]
@FredrikSchaefer - thank you for the feedback. :)  Will communicate this as such.

**Comment by FredrikSchaeferVitagroup** [comment]
@Candice-Louw Thank you for the bug report. It is very valuable to us that you check for correct mapping and display of fields between climedo and SORMAS as that is something we can not properly do ourselves.

**Comment by Candice-Louw** [comment]
Climedo team feedback: 05.02.2021- 
You can also close the ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4161. We have fixed that on our end.
