### ISSUE TITLE
[SurvNet Interface] Add "via DEMIS" field when laboratory is selected as type of report

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4165]
### Situation Description
SurvNet notes whether a laboratory report comes from DEMIS with a yes and no field.
### Feature Description
Enable a yes/no/unknown field called "via DEMIS" when laboratory is selected as a type of reporting. If a case is created through the lab messages (DEMIS) interface, this should be set automatically.

Also remove "not raised" from the variable list of "type of place" since it is the same as "null" and migrate previous entries to "null". 
### Additional Information
<img width="595" alt="Screen Shot 2021-01-28 at 12 00 03 PM" src="https://user-images.githubusercontent.com/70317594/106160264-ed04ee00-6185-11eb-83bd-bb5b179898f6.png">

**Comment by bernardsilenou** [comment]
@kwa20 What about adding another drop down variable called laboratory name: DEMIS + other+ unknown.
other labs may add in future and it would be easier to just add on the list.
This variable may also be useful for international instance and there are usually many labs

**Comment by kwa20** [comment]
@bernardsilenou yes, that would actually be more simple. We do have other and unknown (called "not determinable" thus far). We might just add the variable laboratory (DEMIS) then and only show it for german servers. This variable would also then be pre-filled if the case was created through the lab message.

**Comment by kwa20** [comment]
Do this issue in #3417

**Comment by kwa20** [comment]
obsolete as of 1.56.1 with a new issue created for that field in #4562
