### ISSUE TITLE
Adapt the text search filter so that it is less case sensitive

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4168]
### Problem Description
In France, many names or cities-names have accents. SORMAS 'text search filters are very sensitive to case and stress. Users find it difficult to filter different directories on names that include accents.

### Proposed Change
We are proposing an adaptation of SORMAS to make filters less sensitive to emphasis and box.

### Additional Information
@bernardsilenou   @ftavin can you complete with technical details

**Comment by ftavin** [comment]
@MateStrysewske

@alexandre-gille had a look on this feature and propose the use of the postgresql unaccent additional module (https://www.postgresql.org/docs/9.1/unaccent.html). I believe the case sensitive part is already possible directly with vanilla postgresql.

We would have to :
- add this module to postgresql
- change the code of the queries triggered by filters

Should we add a parameter in the configuration file to give the choice to activate or not this functionnality ? (if we do, we should not force the install of unaccent to postgresql and let the DB administrator do it if needed)

Note : we don't have a solution in mind for accents insensitive filters in the mobile app right now as it uses a specific database for offline mode. As France does not use the mobile app, could this be later issue if we don't find a solution quickly ?

**Comment by MateStrysewske** [comment]
@ftavin I think this change makes sense for basically all possible servers. We're living in a globalised world, so it's very likely that people with accents in their names are living in countries where native names don't have them. So from my perspective, we don't need a feature configuration for that.

**Comment by ftavin** [comment]
@MateStrysewske @bernardsilenou @carolinverset 
The development is done for the web side but is really not trivial for the android app.

Should we split this in two issues (web and android) to allows this to be included for web in 1.58 (France who asked for it does not use android app) ?

**Comment by MateStrysewske** [comment]
@ftavin I'm absolutely fine with splitting it in two issues, yes!

**Comment by StefanKock** [comment]
@MateStrysewske please document assignee, project and milestone - version for this ticket.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
