### ISSUE TITLE
Make event report date editable [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4175]
### Feature Description
Events have both a report date as well as an event date. Unlike the event date, the report date is not editable.

### Problem Description
Since the event date is not mandatory, we have to fall back to the report date when we want to filter events by date, e.g. for the dashboard. This is problematic for things like retrospective data.

### Proposed Change
- [x] Make the event report date editable. It needs to be a mandatory field to make sure that it can't be empty.
- [x] Add a `validate` method to `EventFacadeEjb` that is called during `saveEvent` that ensures that the report date is not empty (similar process as for cases)
- [x] Add date validation: 
    - Date of report <= Current date
    - Event start date <= Date of report

**Comment by MateStrysewske** [comment]
This is a prerequisite for #3004.

**Comment by bernardsilenou** [comment]
At event creation, users has to provide the report date just as in case creation. @kwa20 @MateStrysewske

**Comment by bernardsilenou** [comment]
@MateStrysewske Sine the specification is the summary, I added a point on date validation. Hope this is OK?

**Comment by MateStrysewske** [comment]
@bernardsilenou Adjusted it a little. We can't force the event end date to be before the report date because that would prevent users from creating ongoing events that are scheduled to be over at a specific point in time (e.g. festivals).

**Comment by bernardsilenou** [comment]
@MateStrysewske You are right, that is why i added the condition that the multiday event ==t. Because if multiday event == f, then the date of event is mapped to the end date. if multiple day event ==f, then the end date is always NA

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.60.0-snapshot on local environment setup
