### ISSUE TITLE
Include versionings of configured interfaces/extensions [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4177]
### Situation Description
Thus far, users cannot easily infer what versioning is implemented for a divers number of configured interfaces/extensions. Knowing the versioning would help a lot when trying to identify potential bugs or complications.
### Feature Description
When respective interfaces or extensions for interfaces are configured, display the versioning of them on the "About" page on the SORMAS UI. These include the Survnet converter, DEMIS adapter, climedo and Sormas-SB.
### Additional Information
<img width="222" alt="Screen Shot 2021-01-29 at 3 04 28 PM" src="https://user-images.githubusercontent.com/70317594/106285026-416ea300-6244-11eb-9ebf-5a681a71b8a1.png">

- [ ] Only show the elements when the according 3rd party is configured (SurvNet/Climedo/Demis/Pia)
- [ ] Add an indicator, when the 3rd party is accessible (red x or green checkmark)

@markusmann-vg 
We can only provide this information from DEMIS-Adapter and SurvNet Converter 
**out of scope:**
Climedo and PIA have to provide a rest-endpoint where we can get the info from

**Comment by JonasCir** [comment]
We could introduce `/info/version` routes in SurvNet converter, DEMIS and Climedo services which get queried when the about page is opened. Since everything is running inside one deployment, this should work fine

**Comment by StefanKock** [comment]
I think the overview of versions of products is not to be solved within SORMAS, but by operations (already started by Netzlink).

**Comment by vidi42** [comment]
DEMIS Adapter should also send it's name, so it's not the hardcoded as the DEMIS Adapter version in the UI.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Even though it's considered out of scope now, one remark reagarding retrieving the versions of external journals:

Users can already open the UI of Climedo an PIA from within SORMAS. They should be able to find the version information there. For Climedo I know that this is already possible. I am not sure if it is really worth the effort to transmit the external journal version to SORMAS and display it there.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Good point. I mainly added them back then to not forget about them but SurvNet Converter and DEMIS Adapter are the most important versions anyway. I would be fine with taking out the external journal versionings for this issue, especially if they're available through Climedo or PIA anyway

**Comment by FredrikSchaeferVitagroup** [comment]
Ticket for related changes of the SORMAS-DEMIS-adapter: [#48](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/48)

**Comment by AndyBakcsy-she** [comment]
Validated  ticket on the latest version of sormas 1.67.0-snapshot deployed on test-de1.sormas.netzlink.com environment.
![image](https://user-images.githubusercontent.com/70562142/149098987-1b3e8085-4e95-445a-a849-1d1c2a4b69e1.png)
