### ISSUE TITLE
Add an option to generate Events in DevMode

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4185]
### Situation Description

Currently, the DevMode can be used to generate random cases and contacts for testing and showcase purposes. The same would be needed for events, as it can be quite a lot of work to generate events manually and then fill each with participants.

### Feature Description

Add the same for events, with an option to fill the events with participants.

### Possible Alternatives

In theory, SORMAS data-gen could be used, but that is quite elaborate.

**Comment by DavidBaldsiefen** [comment]
This should be done with #3338 and #3337 in mind.

**Comment by JonasCir** [comment]
Hm I mean we already have a docker-compose in `sormas-cargo` and the `data-generator` already works in Docker, see [here](). I also have access to the data-generator Docker repo, but did not use it so far. I could publish the docker image and include it in the cargo server just for the sake of testing. What do you think @DavidBaldsiefen and @MartinWahnschaffe ?

**Comment by DavidBaldsiefen** [comment]
@JonasCir The problem with the SORMAS-data-generator is that it does not fill the events with eventparticipants which then also generate cases and contacts among those participants. Also, data-gen is about generating realistic data, while DevMode should at least have the option to be deterministic (#3233), so that it can be used for performance testing.

**Comment by JonasCir** [comment]
data-gen is deterministic :) You are right about hte participants but this could be implemented

**Comment by DavidBaldsiefen** [comment]
> data-gen is deterministic :)

Oh nice, that is very good to know! Does it use some kind of seed?

> You are right about the participants but this could be implemented

That would be great. For now I have already almost finished the event generation using devmode, as I need it desperately for #4088 . However we should definetely consider how data-gen could be combined with DevMode to prevent duplicate code work from being done. That should be done in a seperate issue, however, as devmode will have some semi-large rework done this sprint (see linked issues above)

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of Sormas  1.57.0-snapshot
