### ISSUE TITLE
[SurvNet Interface] Add Reason for hospitalization [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4187]
### Feature Description
cases > hospitalization 
### Problem Description
Thus far it is not documented whether a case was hospitalized due to the reported disease or because of another reason. This however is needed for transmitting data to SurvNet. (cf. #3312)
### Proposed Change
Add a "reason for hospitalization" drop-down field to the hospitalization tab. Also include this in the previous hospitalization creation window and additionally add information about the intensive care unit to this section.

drop-down should include the variables:
- (null)
- reported disease
- other reason
- unknown

selecting other would enable another field to specify the other reason.

In the process, move the date of isolation field to the left to be more in line with the other fields on the form.
### Additional Information
<img width="659" alt="Screen Shot 2021-01-30 at 7 23 03 PM" src="https://user-images.githubusercontent.com/70317594/106368850-32bfe300-634d-11eb-97be-f4e149594ce3.png">
<img width="433" alt="Screen Shot 2021-01-30 at 7 19 31 PM" src="https://user-images.githubusercontent.com/70317594/106368851-381d2d80-634d-11eb-83e3-04a75b113fd8.png">

 SurvNet mapping:

- null  |  nicht erhoben
- reported disease  |  Hospitalisiert aufgrund der gemeldeten Krankheit
- other reason  |  Hospitalisiert aufgrund einer anderen Ursache als der gemeldeten Krankheit
- unknown  |  Hospitalisiert Ursache ist unbekannt, nicht ermittelbar

fill "Hospitalisiert zur Isolation" in SurvNet when isolation is set to yes in Sormas and the resaon of hospitalization is the reported disease.

**Comment by MateStrysewske** [comment]
* Add the new fields to both Hospitalization as well as PreviousHospitalization
* Extend the code that turns hospitalizations into previous hospitalizations when transferring cases to also include these new fields

**Comment by kwa20** [comment]
@AndyBakcsy-she I could also verify the reason for hospitalization field on test.sormas.netzlink.com but couldn't verify the "stay in ICU" fields in the previous hospitalizations yet.
