### ISSUE TITLE
Follow-up until date calculation issues

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4191]
### Bug Description
I tried to reduce to followup until from expected date Fen 14 to Feb 11, system told me it is not possible, I  then deactivated override followup to revert back to default nut error message appears. System told me that the date is not correct but does  not tell me the correct date and also pervert me from saving the form.
### Steps to Reproduce
1. create a contact
2. click on override followup
3. set it to a date shorter begore followup until date
4. deactivate override followup
5. save the data
6. 

### Expected Behavior
* If user specified followup until date does returned false when validated and override followup == false, set followup until to the default value and allow user to be able to save the form.
*  add and always show the expected followup until date in the warning message, red box
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/106393510-c9e17500-63f7-11eb-991a-5f62fa262591.png)

### System Details
* Device: web
* SORMAS version: 1.54.1
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: admin + national user

**Comment by StefanKock** [comment]
I think this should be investigated that is not a fully broken functionality on 1.55

**Comment by bernardsilenou** [comment]
@kwa20 @vitali  Maybe this may be solved by implementing #3243. 
Currently it is an important bug.

**Comment by kwa20** [comment]
@bernardsilenou is this still happening with the recalculation of the follow-up duration done in #4241 ?

**Comment by bernardsilenou** [comment]
@kwa20 I have not tested, would have a look.

**Comment by Jan-Boehme** [comment]
Just tested this. It is still happening.

**Comment by bernardsilenou** [comment]
Tested on https://test.sormas.netzlink.com/sormas-ui/  and found important bugs to address in 1.59:
- expected followup until is overridden when followup until is modified. Expected followup until should be calculated based on onset date and fall back on report date. Confirm that this computation works fine.
-  How it should work: when users override followup until, we only modify followup until. In this way, we can compare both dates to see the additional days
![image](https://user-images.githubusercontent.com/12996724/115022570-d84f1100-9ebd-11eb-8a7c-63f312adcdba.png)
- when overrride followup is deactivated , then both expected followup until and followup until falls back to the default value 2/24/2021.  To me this works fine.
- Contacts also have similar and more issues:
- eg when you deactivate override followup until, then dates do not fall back to default values. If you then provide the date of last contact, this date is not used as priority to recompute the default values of followup untill.

**Comment by MateStrysewske** [comment]
@bernardsilenou There were indeed quite some problems with the logic and a number of associated UI and backend issues. What I've fixed:

* Automatically reset follow-up until to expected follow-up until when "overwrite follow-up until" is unchecked
* Automatically extend follow-up until to expected follow-up until when contact/case start date is changed
* Expected follow-up until date is now always correctly calculated and does not take into account the currently filled in follow-up until date
* Automatically uncheck "Overwrite follow-up until" when the date is automatically changed to a later date than the current follow-up until date
* Set cases/contacts to "Follow-up completed" when there's a cooperative visit on the day of follow-up until OR later (until now it had to be the exact day of follow-up until)

This should cover everything you've mentioned.

**Comment by kwa20** [comment]
@MateStrysewske @bernardsilenou I noticed that the follow-up until date for contacts can never exceed the expected until date even when overwrite is selected. It also does not work when extending the follow-up after extending the quarantine.

**Comment by MateStrysewske** [comment]
@kwa20 I can't reproduce that behaviour. Manually extending the follow-up until date works perfectly fine for me. Can you attach some screenshots that show what you've described please?

**Comment by kwa20** [comment]
@MateStrysewske Sure can. I also forgot to mention that I tested on test-de2.sormas.netzlink.com

<img width="335" alt="contactFollowUpExtend" src="https://user-images.githubusercontent.com/70317594/115524544-8972f400-a28e-11eb-8a77-a3767a7245e8.PNG">
<img width="437" alt="contactFollowUpExtend2" src="https://user-images.githubusercontent.com/70317594/115524551-8bd54e00-a28e-11eb-9081-74db85004a63.PNG">

Before saving
<img width="441" alt="contactFollowUpExtend3" src="https://user-images.githubusercontent.com/70317594/115524587-98f23d00-a28e-11eb-85ef-3972b2a25513.PNG">

After saving
<img width="439" alt="contactFollowUpExtend4" src="https://user-images.githubusercontent.com/70317594/115524595-9abc0080-a28e-11eb-9a7e-6490fbde85f6.PNG">

I for some reason could not reproduce this on test.sormas.netzlink.com or test-de1.sormas.netzlink.com yet

**Comment by kwa20** [comment]
@MateStrysewske I noticed that the contact where this behaviour occurs is registered in PIA. This interface is only configured on test-de2. I could also validate that with a new contact on the same system which is not registered in PIA it does not happen. This might potentially also happen with Climedo I suppose

**Comment by MateStrysewske** [comment]
@FredrikSchaeferVitagroup Do you have an idea how this is caused and how it could be fixed?

**Comment by FredrikSchaeferVitagroup** [comment]
I just tried on https://ga1.sormas-oegd.de/ (connected to climedo), the bug does not seem to appear there.
Whenever a contact gets saved, there is a [check for the need to update data on external journals](https://github.com/hzi-braunschweig/SORMAS-Project/blob/76fb898d53ca3b0c8b7f8c78a9154bfeb357cb8b/sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java#L300).

I suspect it might be related to that, but I can not see how.

**Comment by FredrikSchaeferVitagroup** [comment]
I just tried this with another contact on test-de2 (Mr Schnitt Lauch). For the unregistered, registered and accepted state related to PIA I can always manually change the follow up end date. So I am not sure if the external journal really is the cause of the problem.
