### ISSUE TITLE
Do not override data on forms with data stores in the cache of the browser of the user

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4192]
### Feature Description
case >case person
### Problem Description
Sort question please:
On my browser, details of my name, phone, address etc is saves in my cache memory.
When I then open a case > person and enter my name or tell or email or any, additional contact information,
 then some personal data like name, email of the personal data is overwritten on the form. If I then mistakenly save this form, then the person data is changed.
To me this can lead to error in case the user is not vigilant.
### Proposed Change
Do not fill any data stored in cache in form when form is open

**Comment by bernardsilenou** [comment]
@MateStrysewske is this worth a change?

**Comment by MateStrysewske** [comment]
This is a browser feature, we can't do anything about it.
