### ISSUE TITLE
Rest api returns 200 OK but empty json despite 4265 records in samples

### ISSUE THREAD

**Issue by geraldschwarz** [hzi-braunschweig/SORMAS-Project#4193]
```
[2021-01-31T20:50:35.389+0100] [Payara 5.2020] [SEVERE] [] [org.glassfish.jersey.server.wadl.internal.generators.WadlGeneratorJAXBGrammarGenerator] [tid: _ThreadID=82 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1612122635389] [levelValue: 1000] [[
  Failed to generate the schema for the JAX-B elements
com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
Class has two properties of the same name "otherComplications"
        this problem is related to the following location:
                at public de.symeda.sormas.api.symptoms.SymptomState de.symeda.sormas.api.symptoms.SymptomsDto.getOtherComplications()
                at de.symeda.sormas.api.symptoms.SymptomsDto
                at public de.symeda.sormas.api.symptoms.SymptomsDto de.symeda.sormas.api.visit.ExternalVisitDto.getSymptoms()
                at de.symeda.sormas.api.visit.ExternalVisitDto
        this problem is related to the following location:
                at public de.symeda.sormas.api.symptoms.SymptomState de.symeda.sormas.api.symptoms.SymptomsDto.otherComplications
                at de.symeda.sormas.api.symptoms.SymptomsDto
                at public de.symeda.sormas.api.symptoms.SymptomsDto de.symeda.sormas.api.visit.ExternalVisitDto.getSymptoms()
                at de.symeda.sormas.api.visit.ExternalVisitDto
Class has two properties of the same name "otherComplicationsText"
        this problem is related to the following location:
                at public java.lang.String de.symeda.sormas.api.symptoms.SymptomsDto.getOtherComplicationsText()
                at de.symeda.sormas.api.symptoms.SymptomsDto
                at public de.symeda.sormas.api.symptoms.SymptomsDto de.symeda.sormas.api.visit.ExternalVisitDto.getSymptoms()
                at de.symeda.sormas.api.visit.ExternalVisitDto
        this problem is related to the following location:
                at public java.lang.String de.symeda.sormas.api.symptoms.SymptomsDto.otherComplicationsText
                at de.symeda.sormas.api.symptoms.SymptomsDto
                at public de.symeda.sormas.api.symptoms.SymptomsDto de.symeda.sormas.api.visit.ExternalVisitDto.getSymptoms()
                at de.symeda.sormas.api.visit.ExternalVisitDto

        at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:76)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:441)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:273)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
        at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:25)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:358)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
[...] 

```
### Bug Description
The Docker instance reports 200 OK at samples but the json is not filled. The problem is that this query follows the same principle as the call/retrieval of persons/cases/contacts, but unfortunately, the response data is empty.

The stacktrace suggests, that it is caused by a an ambigious "otherComplicationsText" and "otherComplications"-object
(both variable and getter are on public visibility modifier)

### Steps to Reproduce
1. Install Sormas on actually version
2. Insert some Persons / Cases / Contacts / Samples
-> in our testcase 4265 Samples on 300 Contacts
3. call the api on sormas-rest/samples/all/1
4. result in a empty json [{}] and Status 200

### Expected Behavior
a json with 4265 rows of samples 

### Screenshots
![grafik](https://user-images.githubusercontent.com/61940721/106399115-07a1c600-6417-11eb-8df9-1105bd4e1dfb.png)
![grafik](https://user-images.githubusercontent.com/61940721/106399672-5866ee00-641a-11eb-9ad6-1c1da647e9cc.png)

System Details

    Device: Sormas Docker on Debian
    SORMAS version: SORMAS-Version: 1.54.1
    Android version/Browser: 
    Server URL: https://sormas.cov19.digital/sormas-rest/users/all/2020 (only via VPN)
    User Role: national user and rest user

**Comment by 346L3** [comment]
#4196 does not fix the main issue (HTTP Code 200 OK with empty JSON response), the exceptions raised seem to be a different issue we encountered by chance.
The fix from #4196 fixes the exception + stacktrace, but the response from the REST-API to /samples/uuids and /samples/all/{since} is still completely empty.
Both users I tried for the REST API can view all samples in the GUI (sormas-ui) without issues - so it shouldn't be a permission problem either. Other GETs (person, case, ...) also work without issue. How can we debug this further?

**Comment by MateStrysewske** [comment]
@346L3 I can't reproduce the problem on my local system; tried it with both a surveillance officer and a national user/rest user and I get a perfectly fine response. I don't know whether this might have anything to do with Docker or any other configuration issue. @JonasCir @StefanKock Do you have an idea what we could do to get to the bottom of this problem?

**Comment by freezweb** [comment]
the SQL DUMP from the buggy Sormas Database
[public.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/5928517/public.zip)

**Comment by freezweb** [comment]
in Version: 1.56.1 is the same issue

**Comment by JonasCir** [comment]
`sormas-rest/samples/all/1` only shows samples associated to cases, but not for contacts. Not sure what causes this and if it is a permission problem. I'll continue to look into this.

**Comment by freezweb** [comment]
Hi @JonasCir , we send the SamplesDTO.lab field with the folowing code.
And i can read the right lab_id in the lab_id field on Database.

SamplesDTO.lab.uuid = toarray_search(New struct_settings, "sormas_labor_uuid").varchar

**Comment by JonasCir** [comment]
Thanks for the info @freezweb . Can you tell me if your samples are connected to cases or contacts (or both) ?

**Comment by freezweb** [comment]
@JonasCir the samples are all on contacts

**Comment by JonasCir** [comment]
Ok I identified the root cause:
`SampleService.getAllActiveSamplesAfter` executes the following SQL statement (more or less):
```sql
select distinct sample.id as id, sample.changeDate as changeDate
from samples AS sample
    left outer join cases _case on sample.associatedCase_id=_case.id
where
      _case.archived=false
  and sample.deleted=false
order by sample.changeDate desc;
```

The problem is the ` _case.archived=false` 'where' clause which basically removes all samples associated to contacts from the result set. 
The following query joins with contacts and yields the desired result (I think).
```sql
select distinct sample.id as id, sample.changeDate as changeDate
from samples AS sample
    left outer join cases _case on sample.associatedCase_id=_case.id
    left outer join contact cnt on sample.associatedcontact_id=cnt.id
where
      (_case.archived=false or cnt.deleted=false)
    and sample.deleted=false
order by sample.changeDate desc;
```
I need to check back with the team on how to resolve this
