### ISSUE TITLE
Date of report of a case should not trigger error message related to followup untill date

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4194]
case > followup
### Bug Description
When report date of a case is corrected by going many days backward, there is an error related to followup until date.
Error message does not tell me when the expected followup should end so that I can adjust it.
### Steps to Reproduce
1. Create a case today
2. check when followup ends
3. Change report date to 1 Jan 2021
4. Save case and you would find error message related to followup

### Expected Behavior
- I think showing an error message is over-killing it, I suggest we show just an a red warning ! sign or use orange colouring like on mobile app
- when user hover over followup until variable, there is a message explaining the cause of the error. we can add information about the expected new followup until date (expected new followup until date and suggest user to correct this) to permit the user to override and set the new end of followup date.
- I do not know how to put this in words but i know you would understand and maybe come out with something better when you try is out.
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/106409868-d985ab80-6441-11eb-8018-27c846f0fbda.png)

### System Details
* Device:web
* SORMAS version: 1.54.1
* Android version/Browser:
* Server URL: test 1401
* User Role: national user + admin

**Comment by kwa20** [comment]
@bernardsilenou This error message might also be related to the symptom onset date being entered retrospectively and results in the expected follow-up duration not being met.

**Comment by bernardsilenou** [comment]
This would be resolved by implementing #3243
