### ISSUE TITLE
[SORMAS2SORMAS] Add filter to show cases and contacts received by other health departments [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4203]
### Situation Description
Thus far, it is not easily inferable if cases or contacts were shared by other health departments when looking at the cases and contacts directory.
### Feature Description
Add filters to both directories that show the cases/contacts received by and sent to other health departments.
![image](https://user-images.githubusercontent.com/62540178/107352454-274a8580-6acc-11eb-8fe1-acfee65c1386.png)

**Comment by syntakker** [comment]
@kwa20 to make sure: the implementation filters for cases or contacts that have been received from or sent to another SORMAS instance. Whether ownership is handed over or not is ignored.

**Comment by AndyBakcsy-she** [comment]
Validated this ticket on the latest version of SORMAS
Version: 1.57.0-SNAPSHOT
