### ISSUE TITLE
A future date for the case field "PROHIBITION TO WORK UNTIL" gives an error message.

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#4207]
### Bug Description
First, when creating a case requiring prohibition from work, an error message results if the last day away from work  is in the future. Second, the error message is consistent with the issue and reads: "Prohibition to work until has to be before or on the same day as Prohibition to work from" (date of start of prohibition).

### Steps to Reproduce
1. Create a new case (COVID-19).
2. Under the variable "PROHIBITION TO WORK" select "Yes".
3. In the  field "PROHIBITION TO WORK UNTIL", enter a date in the future relative to the date entered in the preceding field "PROHIBITION TO WORK FROM".

### Expected Behavior
1. End of prohibition to work should be possible to accept dates in future of the current date
2. The error message when prohibition to work is set in future should be changed to "Probibition to work until should be on the same day or after prohibition to work from date". It is good to tell users of what the variable should hold not what is should not hold.

### Screenshots

![Screenshot_20210130-114852_SORMAS](https://user-images.githubusercontent.com/71414361/106540780-ea492680-6500-11eb-9b9f-8089810e6428.jpg)

@ Benard Silenou
### System Details
* Device: Samsung Galaxy Tab S6 Lite 
* SORMAS version: 1.54.1
* Android version/Browser: 10 
* Server URL: https://test1401.sormas-oegd.de/sormas-rest/

### Additional Information
Similar issue raised before (# 3409)

**Comment by kwa20** [comment]
This issue seems to only occur on the mobile app since I could not reproduce it on the browser.

**Comment by BasilKaburi** [comment]
@kwa20: You are correct. This issue occurred on the mobile app. Sorry, I should have specified that.

**Comment by raghupola-vg** [comment]
Wrong Error message is displayed when the "Prohibition to work until" date is selected with a preceding date.
Displayed error message: Prohibition to work until has to be **before** or on the same day as Prohibition to work from (PFA screenshot)
Expected error message: Prohibition to work until has to be **after** or on the same day as Prohibition to work from
![Wrong error message displayed](https://user-images.githubusercontent.com/62763628/107796737-7b6a9980-6d5a-11eb-98f0-63499754aecb.png)

**Comment by raghupola-vg** [comment]
verified on latest build and above mentioned issue is Fixed on version 1.57.0-snapshot
