### ISSUE TITLE
[CLIMEDO Integration] Add a query key parameter to the URL called to open a patient diary page [0]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#4210]
### Feature Description

As there were some changes on climedo-side, the url to open a patient diary has to be adapted. 
One more query parameter (queryKey=sicFieldIdentifier) needs to be added in addition to (q=personUUID) for faster search response:
 - Example of a final redirection link: https://ga1.climedo.de/de/studies/5f8d6fe6ec880f001126f3e7/data?q=R53QUE-GXVLBA-VGRGL6-BJA4KADA&queryKey=sicFieldIdentifier

### Additional Information

This has to be done in the openPatientDiaryPage(...) method, which can probably soon be found in the ExternalJournalUtil class.

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of SORMAS Version: 1.55.0-SNAPSHOT on ga1 environment
