### ISSUE TITLE
Add "Date of outcome" to Detailed Export for Cases: refinement

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4214]
### Bug Description
Issue  #3514 was meant to added the outcome date to detail export of cases.
### Steps to Reproduce
1. Do detailed export of a case
2. check for outcome date

### Expected Behavior
- add outcome date to export.

- Recommendations on how outcome and outcome date should be computed:
   - The date of outcome is auto populated with the current date when not provided by the user. This should remain as NA is missing. 
   - Use default value of outcome date as NA, else use user provided outcome date/ date of death of the person is cause of death == disease of case.
   - If outcome == recover, then uses only date provided by user or if missing, maintain NA.
   - it present condition of person == death or buried and cause of death  == disease of case, do not copy over date of death to date of outcome. The reverse can be true, ie if outcome date is registered, then copy it to date of death/buried of the person.
### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@bernardsilenou Your second point in "Expected Behavior" exceeds the scope of this issue, which is a bug issue about the date of outcome not being shown in the export. Anything else should go into a separate issue.

**Comment by bernardsilenou** [comment]
@MateStrysewske Perfect, I was  thinking that we address it as a change rather than a bug fix. I would add a new  issue

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas version 1.57.0-snapshot
