### ISSUE TITLE
[SurvNet Interface] Trigger automatic SurvNet Export when a case was "deleted" in SORMAS

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#4215]
### Situation Description
SurvNet needs the information when a case was deleted in SORMAS
As it is not possible to send a new version of the case to SurvNet it has to be automatically triggered that the case with the information "deleted" is exported to the SurvNet Instance

**Comment by JonasCir** [comment]
I take a look

**Comment by vidi42** [comment]
This ticket will only cover the actual deletion of a case from SORMAS.
The ownership handover should be tackled separately, since that use case may need a different representation in SurvNet

**Comment by markusmann-vg** [comment]
@JonasCir @vidi42 
The same has to be applied, when an event from type cluster is deleted.
If needed, please create another story for it and send me the issue number.

**Comment by AndyBakcsy-she** [comment]
no able to test on the test1402.sormas-oegd.de environment
