### ISSUE TITLE
[SurvNet Interface] changes cannot be saved after initially sending data to SurvNet

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4216]
### Feature Description
SurvNet interface button.
### Problem Description
When a case was initially sent to SurvNet with the button on the case form, changes that are being made afterwards cannot be saved. Users have to navigate out of the case first to then make changes again because a prompt appears informing the user of not being able to save changes since the data has changed in the meantime. The change that is being made is the depositing of the Guid in the external Id field.
### Proposed Change
To prevent having to discard changes that could not be saved, reload the page after the initial transmission to SurvNet so the user can then see the saved Guid and make further edits if desired, which can subsequently then be saved.
### Additional Information
<img width="335" alt="SurvNetChanges" src="https://user-images.githubusercontent.com/70317594/106670040-d2c77780-65ac-11eb-9d7d-d200a8a3ef89.PNG">

**Comment by kwa20** [comment]
This issue might be taken care of by #3518. @HolgerReiseVSys Can you confirm that?

**Comment by HolgerReiseVSys** [comment]
> This issue might be taken care of by #3518. @HolgerReiseVSys Can you confirm that?
@kwa20 the commit looks like it, but I didn't try it out.

**Comment by kwa20** [comment]
Cannot reproduce this issue after checking again with 1.62.3 (Sormas) and 8.2.0 (Converter)
