### ISSUE TITLE
Faulty export/ custom export display on cases and contacts directories

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4230]
### Bug Description
when initially creating a custom export configuration, the button display is hidden on the right side of the window. Furthermore, the export option buttons are cropped in some languages.
### Steps to Reproduce
1. Go to cases or contacts directories.
2. Select export and check the button display.
3. Choose custom export where no previous configurations have been saved.
4. save an initial configuration and check the display.

### Expected Behavior
Buttons should be fully visible.
### Screenshots
<img width="559" alt="customExportContacts" src="https://user-images.githubusercontent.com/70317594/106753958-a7846d00-662c-11eb-9149-23cdf0d77b01.PNG">
<img width="128" alt="exportsDisplay" src="https://user-images.githubusercontent.com/70317594/106753965-aa7f5d80-662c-11eb-89db-ac1766b7b620.PNG">
<img width="146" alt="exportsDisplay2" src="https://user-images.githubusercontent.com/70317594/106753968-ac492100-662c-11eb-8f78-1cc4a9ed6598.PNG">

### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 This has been reported multiple times, so there's at least two duplicate issues for it. It's not easily fixable with Vaadin, and considering that we're currently developing an Angular app, I consider this as "wontfix".

**Comment by kwa20** [comment]
@MateStrysewske Ok thanks, sorry I didn't find the matching issue.
