### ISSUE TITLE
[SurvNet Interface] Trigger automatic SurvNet Export when an event of type cluster was "deleted" in SORMAS

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#4235]
### Situation Description
SurvNet needs the information when an event of type cluster was deleted in SORMAS.

Reuse the same approach from 
https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/1
and
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4215

**Comment by vidi42** [comment]
Covered by https://github.com/hzi-braunschweig/SORMAS-Project/pull/4258
