### ISSUE TITLE
[Symptom Journal] Introduce the PIA (Symptom Journal) button for case persons [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4236]
### Situation Description
Thus far, the symptom journal PIA is only available for contacts. However, this feature is also highly requested for cases. 
### Feature Description
Introduce the PIA button for case persons in order to provide an interface point for a case follow-up with the symptom journal, including syncing of person data and receiving data from the symptom journal.

**Comment by kwa20** [comment]
@FredrikSchaefer @soja-hzi @jkheise @irinajanzen-hzi @ghdoergeloh

**Comment by FredrikSchaeferVitagroup** [comment]
It came out that this feature is already implemented in a way with #3265. 
I have created a commit that cleans up. Also, this feature has never been tested. That's why there shall be the usual procedure with pull request and testing lane.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Do we clearly differentiate between Symptom journal [PIA] and Patient diary [CLIMEDO] on the back end? This has caused some problems before so I just wanted to mention it to raise awareness.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 No, we do not clearly differentiate. And we should not, as many functions are identical.
Of course we need to make sure that the things that are handled differently are really independent of each other. 
For this, we now **really need a test instance linked to a PIA system**. We have communicated this need to netzlink several times, the last time being just yesterday.
