### ISSUE TITLE
[SurvNet Interface] Outcome deceased results in error when trying to transmit data to SurvNet

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4237]
### Bug Description
When the outcome of a case is set to deceased, trying to transmit data to SurvNet results in an error. This happens with converter version 2.10.0
### Steps to Reproduce
1. Set the outcome of a case to deceased and save.
2. Try transmitting data to SurvNet.

### Expected Behavior
Data should be successfully transmitted.
### Screenshots
<img width="681" alt="deceasedSurvNetError" src="https://user-images.githubusercontent.com/70317594/106785891-3950a200-664e-11eb-917c-58ecb6d1c773.PNG">

### System Details
* Device:
* SORMAS version: 1.54.1
* SurvNet converter: 2.10.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
@HolgerReiseVSys @JonasCir @markusmann-vg

**Comment by HolgerReiseVSys** [comment]
Fixed in 2.10.1
