### ISSUE TITLE
Case follow-up until date is not recalculated when a symptom onset date is specified

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4241]
:exclamation: **See here for what needs to be done in this issue:** https://github.com/hzi-braunschweig/SORMAS-Project/issues/4241#issuecomment-790537648

### Bug Description
This is a followup issue of  #3864
There is a bug in the logic to compute and recompute followup. These points are to help to diagnose the cause.

* If the report date of a case is decreased, the FU date moves accordingly, however a warning sign (!) appears and when the case form is saved, an error message appears. System recompute the report date, depending on if the new date is in future or past of the old date but does not override the initial default computed followup until date. 
* After setting the report date to the correct date, you can not still save the data because the old value for followup until is used to validate if user save the data. I think "overriding follow" is the cause of this bug.
* Initially, we had a constrain that symptom onset date  must be <= report date of case. This validation was latter removed because it is only correct for symptomatic cases. For asymptomatic  or "delay symptomatic cases" report date <= symptom onset date. This change breaks when computing the followup until for cases when report date <= symptom onset date.
* If you create a case today with  report dates == today followup until is computed 14 days from today. 
* When onset date is set to 7 days in past, followup until is not recomputed. => onset date does not trigger re-computation of followup.
* When report date is set to 7 days in past, followup until is recomputed, => report date determines re-computation of followup
* When onset date is increased by 3 days, error arise and the whole followup is broken and no date can be modified on form. I do not  know the cause of this.
* When the report date is increased, the FU date is not changed and there's an error message ("should be later than duration"), one has to overwrite the FU date.
* If one manually overwrite the FU date and set it to the same value as the one automatically computed based on initial report date at case creation (today), one can then modify data on case. Users may not know the initial followup until date.
* Computation of followup until at case creation uses symptom onset (when not NA) but re computation is only based on report date. Create a case with symptom onset == today and report date == 10 days in past returned error on followup until date when you re-save the case form.
* Followup until date for contacts does not updated when last contact date or report date is modified after initial creations of contact.

### Steps to Reproduce
**Scenario 1: cases followup**
1. Create a confirmed covid case (Jim) with report date == January 1, 2021 and symptom onset date == NA (this is a scenario when the case is asymptomatic but has a positive lab results)
2. Check the followup until date. this should be Jan 15, and when increasing or decreasing the report date, the followup until date is recomputed accordingly. This works fine.
3. Assume Jim got fever and headache on Feb 2, record this symptom + onset date == Feb 2 and save
4. Open the case tab for Jim and look at the followup until date (red exclamation)
5. Save the case form == error message that does not tell you what to do because I can see that report date is still Jan 1. This message should inform me that the new followup is now computed based on symptom onset date and tell the exact date of the standard followup.
6. You are now blocked from editing this case data. Main case is that followup recalculation should account for asymptomatic cases: report date, of date of lab diagnosis < onset date.

1. dkfksf
2. sfsf

### Expected Behavior
* assume the relevant date for cases = (onset date, report date), symptom onset date = priority if not NA.
* The expected followup until date should be computed and recomputed based on the available relevant date as provided by the user. Saving the case form should override the followup until date with the newly computed value. Validation with followup until should be based on the newly computed followup until date. 
* While waiting to implement a configuration, we can use only report date as a default to compute followup until.
* Newly computed default followup based on most available date (report date, onset date, etc) should automatically override initial computed followup until without setting "override followup" to True. "override followup" is only needed to be set to true when expected system computed followup until date != followup until date provided by user.

### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser:
* Server URL: 
* https://release-international.sormas.netzlink.com/sormas-ui/
* https://test1401.sormas-oegd.de/sormas-ui/
* User Role: national user + admin

**Comment by bernardsilenou** [comment]
Suggestion on how followup until should  be computed based on the default settings:
* #4138 is  about introducing a configuration for new rules that does not apply with what what i would write here
**Cases**
* Consider these 2 variables: expected followup until (EFU) and user defined FU (UFU)
   - expected followup until (EFU) = report date + incubation period (d), we do not need to use use onset date.
   - UFU = followup until date provided by user when "override followup until" == True.
   -  While "override followup until" == false:
       -  recompute FU until based on modified report date and if 
       - if FU == EFU, do nothing
       - if FU != EFU,  set FU as new EFU
       - use EFU for all followup management processes
   - If "override followup until" == True  and UFU >= EFU, use user UFU for all followup management processes, 
   - If "override followup until" == True  and UFU < EFU, show warning message  "followup until date can not be less than the 
    the standard followup duration of the disease which is EFU, starting from the report date)

* *Contacts**
* date = (date of last contact,report date) use the earliest/ smallest date that is not NA
   - expected followup until (EFU) = date + incubation period (d).
   - UFU = followup until date provided by user when "override followup until" == True.
   -  While "override followup until" == false:
       -  recompute FU until based on modified report date and if 
       - if FU == EFU, do nothing
       - if FU != EFU,  set FU as new EFU
       - use EFU for all followup management processes
   - If "override followup until" == True  and UFU >= EFU, use user UFU for all followup management processes, 
   - If "override followup until" == True  and UFU < EFU, show warning message  "followup until date can not be less than the 
    the standard followup duration of the disease which is EFU, starting from the report date)

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 @Candice-Louw 
I suggest we should agree on the default computation before adding the configuration #4138.
Please have a look if I may have forgotten something.

**Comment by bernardsilenou** [comment]
@MateStrysewske  @MartinWahnschaffe @markusmann-vg  @kwa20 @Candice-Louw 
The summary of this ticket is to adjust the default computation of followup until date for cases + contacts + their quarantine dates.
My comment on Feb 4 is just a suggestion on how the algorithm can be adjusted.

Associated issues to this are:
 #4198 
#3243 
#4138

**Comment by bernardsilenou** [comment]
These are some general comments from #2772. I migrated them here in order to close #2772.
* Each time these dates are changed, recalculate the followup until date for cases, contacts and event participants
* Show a dialog box to inform users of this change when data is saved
* Reclassify entity status and follow up status accordingly
* Do not delete visits even if they fall outside the newly calculated followup interval

**Comment by MateStrysewske** [comment]
To summarise, this issue is about the follow-up until date not being properly recalculated when a symptom onset date is specified, but the validation already taking that date into account. The needed change is to make sure that in the logic in CaseFacadeEjb that updates the follow-up status and end date, the symptom onset date is used as the basis of the calculation if available, and the report date only as a fallback.

**Comment by bernardsilenou** [comment]
@MateStrysewske I do not know if this is in your summary already, we decided to add the sample collection date if provided:
-  Case: If onset date is not provided, we fall back to sample collection date and if not provided, we fall back to report date
- We only recalculate followup until when the date with greater priority is modified

**Comment by bernardsilenou** [comment]
I saw it here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3243#issuecomment-790539130 So my last comment is not valid then.
