### ISSUE TITLE
Text search on directories(configuration, cases, event participants, contacts etc) loses focus: Refined

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4242]
### Bug Description
This is a followup of #3835 about searing free txt fields. The bug still exist.
The effect is significant when you are typing at the same time that the system is doing some filtering. 
Go to free txt field, clear all text, press enter key and immediately start typing a name, observer how letters disappear.

* While typing in any search field a letter sometimes immediately disappears, vary the typing speed in order to observe it. 
* When deleting (backspace), a letter sometimes immediately reappears.
* In the contact and event directory, but not in the case directory: When deleting the whole search query, the list is immediately updated (to the full list) before pressing "enter". For performance purposed, its better to reload the directory only if users click on reset filter, just as on the directory.
* Changing the focus from a search filed to elsewhere doesn't apply the filter which is sometimes a bit confusing, e.g. when deleting the search field in the case list. This point has revered been specified, I don't know if we need to add it?
### Steps to Reproduce
1.
2.

### Expected Behavior
-Suggested solution only: 
do not begin lazy loading of page or filtering when focus is on any entry of the filters and nothing has been supplied by user.
### System Details
* Device:
* SORMAS version: 1.54.1 
* Android version/Browser:
* Server URL:
* User Role: https://test1401.sormas-oegd.de/sormas-ui/
* https://release-international.sormas.netzlink.com/sormas-ui/

**Comment by StefanKock** [comment]
@bernardsilenou I re-tested this on https://test.sormas.netzlink.com with 1.64.0-SNAPSHOT, it's not reproducable anymore.

**Comment by bernardsilenou** [comment]
@StefanKock 
I would close the ticket then. We may have resolved it in the past.
