### ISSUE TITLE
Avoid creating ScheduledExecutorService for every single delayed task [1]

### ISSUE THREAD

**Issue by jbellmann** [hzi-braunschweig/SORMAS-Project#4243]
### Feature Description

In current implementations of [CaseFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java#L1668), [ContactFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java#L351) and [PersonFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java#L368) a new ScheduledExecutorService is created whenever a new Task should be scheduled for delayed execution.

### Problem Description

I'm not quite sure my knowledge about EJB environments is outdated but I remember a rule that it's not recommended to create threads programmatically. Instead use something provided by the EJB environment/container.

But with current implementation for every single invocation a new ScheduledExecutorService with new ThreadFactory is created that will also create a new Thread when the task has to be executed.

So in case of massive imports and possible invocation of this method this can lead to a massive bunch of Threads created to execute delayed tasks at once. Massive Thread management can lead to heavy CPU consumption I guess and low performance.

### Proposed Change
My proposed change would be to inject a ManagedScheduledExecutorService into these EJBs and reuse the environment provided mechanism to schedule delayed tasks and maybe avoid massive creation of new threads.

### Additional Information

It's about invocation of `ExternalJournalService.notifyExternalJournalPersonUpdate(JournalPersonDto)`

**Comment by StefanKock** [comment]
I looked over that code, added appropriate labels and have some remarks:

1. There should better encapsulation, the above mentioned EJBs should not all take care this scheduling.
2. `ExternalJournalService.notifyExternalJournalPersonUpdate` contains three conditions that are often not met looking how most instances are used. And it would even be better to check before if symptom journal or patient dairy is connected before checking the data.
