### ISSUE TITLE
Case | Case Person | Changing the date of death in the Case view, it will not update the date on the Person view 

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4248]
### Bug Description
Updating the date of deceased on the Case view does not update on the Person view
### Steps to Reproduce
1. Open a case and set the outcome of case to deceased 
2. Go to Person View and check the date 
3. Update the date on the Case view and check it again on the Person view.

### Expected Behavior
The dates should be updated

###Actual Behavior
The dates do not get updateted

### System Details
* Device:Windows 
* SORMAS version: SORMAS Version: 1.55.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: NatUser

### Additional Information
Changing the outcome of the case will not reflect on the Person View

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of SORMAS Version: 1.58.0-SNAPSHOT on the test.sormas.netzlink.com environment

**Comment by bernardsilenou** [comment]
How logic should work:
* Validation between outcome of case and present condition of person should be activated only if (outcome = diseased) AND (present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case)
 - If outcome of a case == death or buried then set  present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case. If date of outcome is know, then assign it to date of death of person. You can override previous data.
 - if present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case, then  set outcome = diseased. If date of death in not null, then assign it to date of outcome.
- else do not validate outcome or date of outcome with  present condition of person.

@kwa20 If this is fine by you then we can create a change request.

**Comment by kwa20** [comment]
@bernardsilenou very good yes, just one addition: If the person has two or more cases for one disease (reinfection) the previous cases cannot have the outcome = deceased since the case person could not have been reinfected then obviously. This is further logic and should probably result in another issue.
