### ISSUE TITLE
Case | Staff of Armed Forces is not sent to SurvNet

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4252]
Bug Description
Setting the Staff of armed forces on sormas and sending the case to Survnet does not work

Steps to Reproduce
1. Open a case and set the Staff of Armed forces 
2. Send the Case to Survnet

Actual Behavior
The selected values are not synchronized to SurvNet

Expected Behavior
The values of this field should be sent to SurvNet 

System Details
Device:Windows
SORMAS version: SORMAS Version: 1.55.0-SNAPSHOT
Android version/Browser: Chrome
Server URL: test1402.sormas-oegd.de
User Role: NatUser

**Comment by HolgerReiseVSys** [comment]
@AndyBakcsy-she Could not reproduce.
This has been added to v1.7.0 of the converter. What ist the Version on the system?

**Comment by JonasCir** [comment]
@AndyBakcsy-she please try again on test1402.sormas-oegd.de
This is the source of truth instance!

**Comment by AndyBakcsy-she** [comment]
Closing ticket as fixed.
After the last Converter update to to version 2.10.1, the issue is not reproducible anymore on the test1402.sormas-oegd.de

**Comment by AndyBakcsy-she** [comment]
The tests were done only on the side of Sormas, without validating the result on SurvNet

**Comment by JonasCir** [comment]
@AndyBakcsy-she If it is working in SORMAS it's fine. Problems with the converter go to the private repo
