### ISSUE TITLE
[SurvNet Interface] Add filters and indicators  to send events to SurvNet [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4257]
### Situation Description
Thus far, events can only be sent individually to the SurvNet instance. This is pesky when a lot of data has to be processed and might lead to events not being transmitted because people might forget to send the data. 
### Feature Description
As proposed for cases (#3947)

~~- Introduce a bulk action option to send many events to SurvNet at once.
    - Show a notification when events are included that do not have a cluster status.~~
- Add filters for what is going to be implemented for cases also for events. (Only show when SurvNet interface is configured)
    - "only events not yet transmitted to SurvNet"
    - "only events already transmitted to SurvNet"
    - "only events changed since last transmitted to SurvNet"
    - Last SurvNet transmission date filter
    - Add Date of last SurvNet transmission to the events directory
- Add indicators in the SurvNet button section of events ("number of transmissions" and "date of last transmission")

**Comment by StefanKock** [comment]
Adjust ticket slicing to these transmission information: Mixing bulk action should not mix with heavy load feature #3947

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test-de1.sormas.netzlink.com environment
