### ISSUE TITLE
Regionally restricted users have a faulty event participant case creation link for some events

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4260]
### Bug Description
Users that are regionally restricted (e.g. supervisors, officers) do not see the case creation link in the event participant view for pseudonymized event participants of events outside of their jurisdiction. Despite that, the hidden link can be clicked nonetheless and opens the creation window. When trying to enter case data and save, an error occurs since the name cannot be entered since it would normally be adopted.
### Steps to Reproduce
1. Log in as a regionally restricted user.
2. Open an event outside of your jurisdiction.
3. open the event participant (list should contain participants outside of your jurisdiction).
4.  Click where you would normally find the case creation link.

### Expected Behavior
Since the case creation link does not serve any purpose for users trying to create cases for pseudonymized event participants, not only hide the link but also disable the option to select it.
### Screenshots
<img width="606" alt="SurvOffEpCaseCreate" src="https://user-images.githubusercontent.com/70317594/106961148-7778bf00-673d-11eb-81d7-4a821495065c.PNG">

### System Details
* Device:
* SORMAS version: 1.54.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: supervisors, officers

**Comment by StefanKock** [comment]
Removed milestone, because it was not addressed in Sprint 101

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
