### ISSUE TITLE
Persons pushed via REST don't appear when queried

### ISSUE THREAD

**Issue by keppla** [hzi-braunschweig/SORMAS-Project#4261]
### Bug Description

I push a new person via the rest api. I then try to list the UUIDS, to see if the new person exists, to no avail.

### Steps to Reproduce
I first use the restapi to push a person to my freshly instantiated server

    export creds=redacted:redacted
    export apiurl=https://sormas.recklinghausen.triplet.gmbh/sormas-rest

    curl -X POST \
        --user $creds \
        --header 'Content-Type: application/json' \
        -d @- \
        $apiurl/persons/push << JSON
        [
            {
                "uuid": "XXXXXX-XXXXXX-XXXXXX-XXXALICE",
                "firstName": "Alice",
                "lastName": "Arkham",
                "sex": "OTHER"
            }
        ]
    JSON

the server answers: `["OK"]`.

I then try to list the UUIDS:

    curl -k --user $creds $apiurl/persons/uuids

**Expected result**: `["XXXXXX-XXXXXX-XXXXXX-XXXALICE"]`
**Observed result**:  `[]`

The user seems to be present in the database:

     select id, uuid, firstname, lastname from person;
     id  |             uuid              | firstname |  lastname  
     -----+-------------------------------+-----------+------------
     122 | XXXXXX-XXXXXX-XXXXXX-XXXALICE | Alice     | Arkham
     124 | XXXXXX-XXXXXX-XXXXXX-XXXXXBOB | Bob       | Baumeister

### System Details
* SORMAS version: 1.53.0
* Android version/Browser: curl
* Server URL: https://sormas.recklinghausen.triplet.gmbh
* User Role: Überwachungsbeauftragte*r, ReST Benutzer*in, Administrator (sorry, don't know the english titles)

**Comment by JonasCir** [comment]
@keppla Thanks for opening the issue. I do my best to look into this as soon as possible, but in the meantime you could head over to this [blog post](https://railslove.com/stories/digitalisierung-im-gesundheitsdienst-so-integrierst-du-die-sormas-api/) and see if this helps you.

**Comment by keppla** [comment]
@JonasCir thanks for answering!
I actually found that blog post by myself :) The potential bug i reportet resulted from trying to follow it's steps, so while the blog post is helpful in general, im afraid it doesnt help me with the issue.

**Comment by JonasCir** [comment]
Understood, then I need to investigate :)

**Comment by MateStrysewske** [comment]
I think this is basically the same as #4193, so I'll close this issue, investigation will take place in the existing one.
