### ISSUE TITLE
Processing of Lab Messages results in error message

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4268]
### Steps to Reproduce
1. Open an environment where there are Lab Messages available 
2. Go to Samples and select Lab Messages
3. Select one Lab Mesage and click on process
4. Select Create new Case on the pop-up window
5. Fill in all the information required, click on Save and do the same for the next screen

### Expected Behavior
The pprocess should work without any issues. 

###Actual Behavior
The user receives the following message and the server logs the message attached to this ticket
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/107011933-05d25c80-67a1-11eb-9af4-0c4c63dca367.png)

### System Details
* Device: Windows
* SORMAS version: SORMAS Version: 1.55.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: NatUser
[serverlog.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/5931273/serverlog.txt)

**Comment by FredrikSchaeferVitagroup** [comment]
Should be resolved by this commit: https://github.com/hzi-braunschweig/SORMAS-Project/pull/4259.
Please verify again after the next nightly build on test-de2.sormas.netzlink.com

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she Any update?
@FredrikSchaefer If Andy confirms that the issue is already resolved, please close this issue, remove all labels and label it with "Duplicate"

**Comment by AndyBakcsy-she** [comment]
It kind of gotten worse: 
![image](https://user-images.githubusercontent.com/70562142/107202287-b3907600-6a02-11eb-90d0-d01a7a5c2f59.png)

**Comment by AndyBakcsy-she** [comment]
It works now and I will then mark it as duplicate, as @Maté Strysewske suggested.
