### ISSUE TITLE
Add population data to Communities

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4271]
### Situation Description

Right now, population data can only be imported for regions and districts. However, especially for the statistics page, it can sometimes be useful to also have population data on a community-basis.

### Feature Description

- [ ] Add column `community_id` to `populationdata`
- [ ] Add column `Community` in import&export template, which can be empty optionally
- [ ] If a region&district filter is set in statistics view, show all communities with their respective incidence

### Additional Information

If working on this, one may also consider implementing #3984 by either adding a small table showing the most important population data information (Region, District, Community, Growthrate and total Population) or improving the notice to be more clear.

This Issue is based on a user request.

**Comment by stephan-2** [comment]
Inzidenzen sind aussagekräftiger als reine Fallzahlen. Von großer Wichtigkeit für Städte und Gemeinden.

**Comment by MateStrysewske** [comment]
@stephan-2 Hey! Please use English when communicating in this repository.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by kwa20** [comment]
@DavidBaldsiefen @MateStrysewske I could verify this issue on test-de.sormas.netzlink.com for the import and export. Columns for growth rate and population in the community configurations sections would have to be handled in another issue I suppose?

**Comment by MateStrysewske** [comment]
@kwa20 Yes, I think so. :)
