### ISSUE TITLE
Add the possibility to export the entire Database

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4272]
### Situation Description

Currently, the database export only allows the user to export specific tables as .csv-files.
However some users have set up individual processes locally which require far more complex data access, including access to the database. With some of the users losing direct database access when the servers are being moved to central locations, it would be really helpful if they could manually download the entire database (e.g. on a daily basis), to continue using them locally until required processes are implemented in SORMAS.

### Feature Description

Use a tool like [pg_dump](https://www.postgresql.org/docs/10/app-pgdump.html) to allow database export.
Ideally, also allow end users to automatically download the database, e.g. using cronjobs.
The produced file should be compressed before transfer.

### Additional Information

We should consider the performance implications of such a feature, as well as the potential filesize of the export. How large can a database be until this solution fails to be useful?

One user reported that the local production database produced a pg_dump of around 600MB. Of course this will only grow with time going on, so we should expect zipped files to potentially be multiple gigabytes in size.

This issue is based on a user request.

**Comment by DavidBaldsiefen** [comment]
@JonasCir @MartinWahnschaffe Thoughts?

**Comment by MartinWahnschaffe** [comment]
I think this is nothing that should be included directly in SORMAS. Anyone how operates a SORMAS server can set up a cron job that regularly creates a pg dump of the whole database and puts it into a folder where someone that is allowed to access all the data can take it.

**Comment by JonasCir** [comment]
@MartinWahnschaffe The standard sormas docker compose stack already features a dumper which saves the complete DB every 30 minutes

**Comment by DavidBaldsiefen** [comment]
> 
> 
> I think this is nothing that should be included directly in SORMAS. Anyone how operates a SORMAS server can set up a cron job that regularly creates a pg dump of the whole database and puts it into a folder where someone that is allowed to access all the data can take it.

That is good to know. Does that pose a potential issue in Germany though, when the servers are hosted by Netzlink so users don't have direct access?

**Comment by stephan-2** [comment]
@MartinWahnschaffe Fast alle Gesundheitsämter erstellen individuelle Berichte. Hierfür ist ein Zugriff auf eine Datenbank unabdingbar. Ein direkter Zugriff auf die Datenbank ist beim zentralen Hosting in Deutschland zurzeit nicht vorgesehen. Die Bereitstellung des Dumps per cronjob ist daher sehr wichtig.

**Comment by stephan-2** [comment]
Um die Größe des Dumps zu minimieren könnte auf den Export von History-Tabellen verzichtet werden (am besten optional per Konfiguration).

**Comment by markusmann-vg** [comment]
@fhauptmann I guess this is a Netzlink topic. Please take into consideration.
