### ISSUE TITLE
Vaccination Fields should have validations

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4276]
### Steps to Reproduce
1. Create a Case with Vaccination
2. Set the dates of the first and last vaccination the wrong way. Use dates from a year when Covid was not existent for example. 
3. Use a float number like 1.345 for the Vaccine dose field

### Expected Behavior
These fields should have validations for this kind of scenario.
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/107082074-54611480-67fc-11eb-8409-5e9283e8c0fe.png)

### System Details
* Device:Windows
* SORMAS version: Sormas version 1.55.0-snapshot
* Android version/Browser: chrome
* Server URL: Localhost
* User Role: NatUser

### Additional Information
this ticket is related to #4137

**Comment by DavidBaldsiefen** [comment]
> Use dates from a year when Covid was not existent for example.

How would you fix this? Is this checked elsewhere? Of course it should be checked that first date <= last date, but I don't know if it makes sense to make a general date check fin regards of when Covid started spreading or when vaccinations were released

**Comment by DavidBaldsiefen** [comment]
Should dates in the future be allowed for first & last day of vaccination? E.g., the day of vaccination is already planned

**Comment by bernardsilenou** [comment]
> > Use dates from a year when Covid was not existent for example.
> 
> How would you fix this? Is this checked elsewhere? Of course it should be checked that first date <= last date, but I don't know if it makes sense to make a general date check fin regards of when Covid started spreading or when vaccinations were released


@DavidBaldsiefen  
- The "additional medical information" tab applies to all vaccine preventable diseases, so it better to only validate that " first date <= last date" and also that none should be in future of the current date.
-  This similar issues was raised in sample sections. Users wanted to be able to document samples to be collected. The solution was for users to user the task management in case they plan to document data scheduled to be collected in future. All data on case form and other entities are observed data, not data scheduled to be collected.
- Hope this helps

**Comment by bernardsilenou** [comment]
Just to confirm that this validation in not in 1.56. Was this merged without added in this version ??

**Comment by DavidBaldsiefen** [comment]
> Just to confirm that this validation in not in 1.56. Was this merged without added in this version ??

These validators are not in 1.56, but they might be merged today to be in 1.57

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on local environment
