### ISSUE TITLE
Add E-Mail templates with custom attachments to be created and sent from within SORMAS

### ISSUE THREAD

**Issue by heineltp** [hzi-braunschweig/SORMAS-Project#4278]
### Situation Description
Wir versenden jeder neu erfassten Person standardmäßig Informationen per Email.

### Feature Description
Vorlagen anlegen wie bei Q-Bescheiden mit Platzhaltern für Name, Isodatum etc.
Versand per Email aus Sormas heraus notwendig.

### Possible Alternatives
Keine

### Additional Information
Für Rückfragen: philippe.heinelt@lrasw.de

**Comment by DavidBaldsiefen** [comment]
@syntakker I think we already considered it in the past. Maybe you can tell the current situation in regards to sending emails from SORMAS?

**Comment by MateStrysewske** [comment]
@heineltp Please exclusively use English in this repository, especially when opening issues. There are a lot of people working on SORMAS that don't speak German. Please reopen this issue with an English description.

**Comment by DavidBaldsiefen** [comment]
@syntakker @heineltp I created an english version here: #4286

**Comment by heineltp** [comment]
@DavidBaldsiefen Thank you for your Support
@MateStrysewske I will try to improve my English language to do so. So we nead to deal with bad or unspecific or probably Wrong bug descriptions or Feature requests. We will see.

**Comment by MateStrysewske** [comment]
@heineltp We don't expect anyone who creates issues here to speak perfect English, don't worry :) it's important though that every team member (and everyone else who's interested in this project) has a chance to understand what the issue is about.

**Comment by Marko-ilmkreis** [comment]
@heineltp you can also try the translator https://www.deepl.com/translator, which is much better then google. You can change the translastion and define our own glossar.
