### ISSUE TITLE
Standardaufgaben vom Admin vordefinieren und vom User auswählbar machen

### ISSUE THREAD

**Issue by heineltp** [hzi-braunschweig/SORMAS-Project#4279]
### Situation Description
Arbeitsschritte und Aufgaben müssen zur Standardisierung der Abläufe und Unterstützung neuer und aushelfender Mitarbeiter vorformuliert werden können.

### Feature Description
Im Adminbereich Aufgaben die vom User ausgewählt werden können für alle Bereiche vordefinieren können.
Der User kann dann bei "Neue aufgabe hinzufügen" aus der Auswahl wählen.

### Possible Alternatives
Keine

### Additional Information
Für Rückfragen: Philippe.Heinelt@lrasw.de

**Comment by kwa20** [comment]
@heineltp Thank you for your contribution. Since this is a duplicate issue of #3880, I'll close this one. You're welcome to comment on the linked issue.
