### ISSUE TITLE
Drop-down list for "Source of Vaccination Information" is not displayed on Android app

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4285]
### Bug Description
An empty list is displayed for the Source of Vaccination drops down field.
 
### Steps to Reproduce
1. Login to Sormas Android app as Surveillance Officer
2. Pick a Covid-19 case and Click on the edit icon
3. Scroll down to Additional Medical Information
4. In the Source of Vaccination Information field, Click on the drop down selector and see if the list is displayed. 

### Expected Behavior
All the values in the list must be displayed correctly.
 
### Screenshots
![Empty list for Source of Vaccination](https://user-images.githubusercontent.com/62763628/107194168-fdbc2c00-69ef-11eb-8ea8-6f2dffe1e076.png)

### System Details
* Device: Samsung S 10
* SORMAS version: 1.56.0-Snapshot
* Android version/Browser: Android version 10
* Server URL: https://test.sormas.netzlink.com
* User Role: SurvOff

### Additional Information
#4137

**Comment by DavidBaldsiefen** [comment]
I guess it has to do with `// TODO [vaccination info] integrate vaccination info` in `CaseEditFragment.java`?

Interestingly, I was also unable to enter a vaccine name or manufacturer locally despite having selected "Vaccinated":

![image](https://user-images.githubusercontent.com/4655486/107254951-16503480-6a38-11eb-87e7-5d96c5a8ed1d.png)

**Comment by raghupola-vg** [comment]
> I guess it has to do with `// TODO [vaccination info] integrate vaccination info` in `CaseEditFragment.java`?
> 
> Interestingly, I was also unable to enter a vaccine name or manufacturer locally despite having selected "Vaccinated":
> 
> ![image](https://user-images.githubusercontent.com/4655486/107254951-16503480-6a38-11eb-87e7-5d96c5a8ed1d.png)

May be you selected a Non covid case. that is the reason you do not see the Vaccine name and Manufacturer fields.

**Comment by raghupola-vg** [comment]
@DavidBaldsiefen May be you selected a Non covid case. that is the reason you do not see the Vaccine name and Manufacturer fields.

**Comment by DavidBaldsiefen** [comment]
> May be you selected a Non covid case. that is the reason you do not see the Vaccine name and Manufacturer fields.

That was it, thanks!

**Comment by DavidBaldsiefen** [comment]
Ok I actually fixed it, by just uncommenting all the relevant lines in `CaseEditFragment.java`

@leventegal-she Is there a reason you had these lines disabled?

**Comment by leventegal-she** [comment]
> Ok I actually fixed it, by just uncommenting all the relevant lines in `CaseEditFragment.java`. The data seems to be saved in the database just fine.
> 
> @leventegal-she Is there a reason you had these lines disabled?

It was commented by mistake

**Comment by raghupola-vg** [comment]
Verified issue on version 1.57.0-Snapshot and issue is resolved.
