### ISSUE TITLE
[DEMIS2SORMAS] The labmessage HTML overlaps with creation forms

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#4291]
### Bug Description

In the SORMAS-UI, the HTML-representation of a labMessage from DEMIS (generated by the `DemisLabResultsAdapter.convertToHTML(...)`) is assumed to have a width of at most 550 px. When the with of the generated HTML exceeds this width, it overlaps the creation forms shown side-by-side when processing a labMessage.

### Steps to Reproduce
1. Fetch new labMessages from the DEMIS Testserver (some of the new messages contain more detailed entries, which result in a HTML representation exceeding a width of 550 px).
2. Click on process on any newly fetched labMessage
3. Select "Create New Case" in the newly opened "Pick or Create Entry" view.
4. Notice the overlap. If there is no, repeat steps 1-3 for other newly fetched messsages until you see an overlap.

### Expected Behavior

The labMessage view and the CaseCreateForm should not overlap. To archieve this, the HTML representation of the labMessage shall not exceed a width of 550 px.

### Screenshots

![image](https://user-images.githubusercontent.com/67001822/107203129-53e29c80-69fb-11eb-9af5-d34a6c56950e.png)

### System Details
* Device: Windows 10
* SORMAS version: 1.57.0-Snapshot
* Android version/Browser: Chrome
* Server URL: local system

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I could also reproduce this on 1.56.0 for contact and sample creation form.

**Comment by vlad-ciucescu** [comment]
The HTML is generated using the templates from Demis, so we actually don't have much control over the content. 
I think an alternative here would be to put the html inside a panel with a fixed size and add a horizontal scroll bar if the content is wider than 550px.

**Comment by FredrikSchaeferVitagroup** [comment]
We could manipulate the html-string we create with help of the XSLT-files before handing it from the adapter to SORMAS.
There seems to be a quite simple approach to do that with `max-width: 550px;` in the style definition.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS
Version: 1.57.0-SNAPSHOT on test-de2.sormas.netzlink.com

**Comment by FredrikSchaeferVitagroup** [comment]
It came out that sometimes the result notes by far exceed a width of 550px. This is still displayed:
![image](https://user-images.githubusercontent.com/67001822/107739999-66661a00-6d0a-11eb-83d6-927d7f6ce5f2.png)

**Comment by FredrikSchaeferVitagroup** [comment]
Merge a fix via https://git.vitasystems.dev/sormas/sormas-demis-adapter/-/merge_requests/11.
