### ISSUE TITLE
Translations > Include Czech language

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4299]
### Situation Description
SORMAS usage in the Czech Republic requires Czech to be included as a language.

### Feature Description
- [x] 1. Include the language in CrowdIn for Czech 
- [x] 2. Ensure that future translation syncs include a push of the Czech (cze) SORMAS translation file(s).
- [x] 3. Once sufficient translation has been done in CrowdIn, include Czech as a language in the SORMAS UI (separate Issue will be created for this).

### Additional Information
![image](https://user-images.githubusercontent.com/65529128/108027938-43e64080-702b-11eb-91cc-9b49d687dcbb.png)

**Comment by Candice-Louw** [comment]
@trendspotter - please could you verify this?

**Comment by trendspotter** [comment]
yes, thank You for help!

**Comment by Candice-Louw** [comment]
- [x] Part 1 - Czech translations from CrowdIn synced to SORMAS project.

![image](https://user-images.githubusercontent.com/65529128/107498420-0c434880-6b94-11eb-9a82-95fad17ad31b.png)

**Comment by Candice-Louw** [comment]
- [ ] Part 2 - Introduce CZ into the SORMAS UI as a translation option in the dropdown.

Translation status (10.02.2021): 7%.
![image](https://user-images.githubusercontent.com/65529128/107499083-d0f54980-6b94-11eb-9c4f-93985a01be27.png)

**Comment by Candice-Louw** [comment]
@trendspotter - which value should be displayed in the Menu item, please?

Český?
Something else?

![image](https://user-images.githubusercontent.com/65529128/107501536-d2744100-6b97-11eb-806e-c1ba459e1c8b.png)

**Comment by trendspotter** [comment]
Čeština 
is better :)

**Comment by Candice-Louw** [comment]
@trendspotter - the translation tool is currently blocked.  We are aware of it and am working on fixing it.  Apologies for the inconvenience!

**Comment by Candice-Louw** [comment]
@trendspotter - the translation tool is fixed again. 😄 Thank you for your patience.  Please do continue the great translation work!

**Comment by Candice-Louw** [comment]
@trendspotter - closing this issue and opening a new issue (#4449) to include the language in the UI.  Thank you for the great translation work!  Please keep going.
