### ISSUE TITLE
Sync error after auto upgrade from 1.53 to 1.54.1 on tablet

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4300]
### Bug Description
- Tablet on 1.53 was to connected to server and server was then upgraded and many changes made from the server side. 
- 1.53 was on tablet and upgrade to 1.54.1 was successful and user account was still logged-in on tablet
- tablet could not sync with server after upgrade, red sync error massage sync failed: trey again latter.
- re-sync failed with red error message.
- there was not sync conflicts
- NB: while tablet was on 1.53 and server on 1.54.1, records were edited from both ends and tablet could not communicate with server.
- Manual installation of 1.54.1 on the tablet was OK
- A second observation with another tablet: a user on version 1.53 who has been logged on device could not sync when server was on 1.54.1. The message to upgrade was ask but i refused to upgrade.
### Steps to Reproduce
1.
2.

### Expected Behavior
- After upgrade of version on device to server version, as long as user account logged on tablet is valid, then tablet should be able to sync with the server.
- If user refuse to upgrade, all previous versions should be possible to sync with server
### System Details
* Device: samsung 
* SORMAS version: 1.54.1
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: Hospital informant

**Comment by bernardsilenou** [comment]
@MateStrysewske I contacted another colleague and was told that the tablet could sync on the same day the upgrade was done. But today, we tried and it could not.

**Comment by bernardsilenou** [comment]
@fhauptmann do you know if there was any change on server that may be related to this issue?
test1401 is on 1.56 already.

**Comment by fhauptmann** [comment]
Hi, I'm not aware of any change, that would prevent synchronization

**Comment by MateStrysewske** [comment]
@bernardsilenou @fhauptmann There's once again an additional test without an associated sample ID on that system, which is why the synchronisation fails. I don't know how that happened, but removing any additional test without a sample ID from the database will likely fix the synchronisation issues.

**Comment by bernardsilenou** [comment]
@MateStrysewske  This can explain why it worked and failed after some day.
@fhauptmann  This means both test systems: test1401 and release-international are down. 
Please who in netzlink can have a look at this? Since this is the second time its happening, then there is surely a hidden cause for us to find.

**Comment by bernardsilenou** [comment]
@fhauptmann @kwa20 I manually installed 1.56 on a tablet and point it to https://test1401.sormas-oegd.de/sormas-ui/.
Login was successful, infrastructure data and entities existing in db were pull on the device but device could  not sync after that. This is additional validation that the bug is coming from the server side.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Can we keep this ticket or #3436 open ? There is still an issue with the lest servers. We then close it when Netzlink resolve the issue.

**Comment by MateStrysewske** [comment]
@bernardsilenou I'd prefer to handle this via Netzlink's ticket system because there's nothing we can really do about it here. I don't see any possibility of an additional test without a sample ID being created within SORMAS.

**Comment by bernardsilenou** [comment]
@MateStrysewske  @fhauptmann @markusmann-vg 
As I already commented here #4471, I got the data on release-international test server from netzlink and could not find an additional or pathogen test without a sample.

- 1.57 automatically upgraded perfectly but tablet could not still sync.

- How do we go about testing the mobile app please?  If we do not get this solved then it would not be possible to validate the mobile app.
- For now, I think  we can test 1.57 on https://test.sormas.netzlink.com/sormas-ui/ . My  worry is that if I test on this server, I may also produce the same kind of wrong data that may break the mobile part. Is it OK for you if i reproduce the same situation on this server?

**Comment by MateStrysewske** [comment]
@bernardsilenou I will test this again on the server that has the problems next week and see whether I can figure out the problem on the mobile app part.

**Comment by bernardsilenou** [comment]
Ok @MateStrysewske 
@AndyBakcsy-she  Can I test the mobile app on  https://test.sormas.netzlink.com/sormas-ui/  ?

**Comment by StefanKock** [comment]
Might be related to #4193

**Comment by MateStrysewske** [comment]
See #4603

**Comment by MateStrysewske** [comment]
Very likely resolved by #4193
