### ISSUE TITLE
Typing ID does not get enabled when entering test results directly in sample creation form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4301]
### Bug Description
When directly adding the test result in the sample creation form, the typing Id field does not get enabled when selecting an appropriate test. This is also true for the DEMIS interface.
### Steps to Reproduce
1. Go to a case, contact or event participant.
2. Create a sample and directly enter a pathogen test result.
3. Either choose PCR, Screening or DNA Microarray as a type of test.
4. Check for the typing Id field.

### Expected Behavior
typing Id should get enabled for any pathogen test creation option.
### Screenshots
<img width="545" alt="missingTypingId" src="https://user-images.githubusercontent.com/70317594/107284029-73121600-6a5d-11eb-8e5d-abd0c58ef9b3.PNG">
<img width="473" alt="missingTypingId2" src="https://user-images.githubusercontent.com/70317594/107284032-74dbd980-6a5d-11eb-8856-b2910ec87a89.PNG">
<img width="466" alt="missingTypingId3" src="https://user-images.githubusercontent.com/70317594/107284037-76a59d00-6a5d-11eb-9cc9-4c5870d65447.PNG">

### System Details
* Device:
* SORMAS version: 1.56.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
@MateStrysewske Can you tell me how the pathogen test creation form differs from the direct entry section of tests through the sample creation form? On the UI it just looks like an extension with the test form but it seems as if we need to specify that when changes are being made to the pathogen tests, the direct entry through samples needs to be taken into consideration additionally. I'm just not sure how they differ.

**Comment by MateStrysewske** [comment]
@kwa20 We basically have to manually add the fields to the sample creation form, yes, and that's something that's very easy to miss when implementing issues, so ideally this would be part of the issue definition. We'll also try to keep it in mind.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on the local environment
