### ISSUE TITLE
Error generated on form selection on filter- APMIS campaign data directory

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#4303]
### Bug Description
Please note that when you are in the campaign data directory and select a form from the dropdown filter, an error occurs.
### Steps to Reproduce
1. Open the campaign data directory and select any form from the filter 
2. An error occurs

### Expected Behavior
No error should be expected
### Screenshots
![7D4FC0FB-5960-42FF-BCC0-BB455C033B01](https://user-images.githubusercontent.com/60390281/107293617-fb7ebf80-6a39-11eb-8844-41eef9637729.jpeg)
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
Seems like this is already fixed in the latest version.
