### ISSUE TITLE
Add indexes to sormas database [0.5]

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#4307]
### Situation Description
The database lacks indexes and they are only added once we see a problem.
Indexes should be added everywhere where there is potential improvement by adding them.
### Feature Description
As a rule of thumb try to keep the indexes to a minimum, but:
- add index on columns that are being used in where clauses
- add index on columns that you use to join on.

**Comment by DavidBaldsiefen** [comment]
Adding too much indexes may slow down the database in other places though, especially whenever lists are modified (insert). I wouldn't suggest adding more than 1 index per table whenever it's not necessary

**Comment by MartinWahnschaffe** [comment]
@BarnaBartha Statements we found in the slow query logs from Ghana that my be related to this.
Please make sure that the indices that would speed those statements up are included.

1.  CaseFacade.count for a lab officer (associated via related sample.lab)

> select count(case0_.id) as col_0_0_ from cases case0_ left outer join users user1_ on case0_.reportingUser_id=user1_.id left outer join users user2_ on case0_.surveillanceOfficer_id=user2_.id left outer join users user3_ on case0_.caseOfficer_id=user3_.id left outer join Person person4_ on case0_.person_id=person4_.id left outer join users user5_ on case0_.reportingUser_id=user5_.id left outer join Region region6_ on case0_.region_id=region6_.id left outer join District district7_ on case0_.district_id=district7_.id left outer join Community community8_ on case0_.community_id=community8_.id left outer join Facility facility9_ on case0_.healthFacility_id=facility9_.id where (case0_.id in (select sample10_.associatedCase_id from samples sample10_ where sample10_.lab_id=$1) or case0_.id in (select contact11_.caze_id from Contact contact11_ left outer join users user12_ on contact11_.reportingUser_id=user12_.id left outer join users user13_ on contact11_.contactOfficer_id=user13_.id where user12_.id=$2 or user13...

2. Pathogen tests of a sample. Very strange that this is slow - maybe the system was slowed down by a running process. Still likely that adding an index will speed this up:

> select pathogente0_.id as id1_25_, pathogente0_.changeDate as changeDa2_25_, pathogente0_.creationDate as creation3_25_, pathogente0_.uuid as uuid4_25_, pathogente0_.deleted as deleted5_25_, pathogente0_.cqValue as cqValue6_25_, pathogente0_.fourFoldIncreaseAntibodyTiter as fourFold7_25_, pathogente0_.lab_id as lab_id18_25_, pathogente0_.labDetails as labDetai8_25_, pathogente0_.labUser_id as labUser19_25_, pathogente0_.sample_id as sample_20_25_, pathogente0_.serotype as serotype9_25_, pathogente0_.testDateTime as testDat10_25_, pathogente0_.testResult as testRes11_25_, pathogente0_.testResultText as testRes12_25_, pathogente0_.testResultVerified as testRes13_25_, pathogente0_.testType as testTyp14_25_, pathogente0_.testTypeText as testTyp15_25_, pathogente0_.testedDisease as testedD16_25_, pathogente0_.testedDiseaseDetails as testedD17_25_ from PathogenTest pathogente0_ where pathogente0_.deleted=false and pathogente0_.sample_id=$1 order by pathogente0_.testDateTime desc

3. Previous hospitalizations of a hospitalization. Very strange that this is slow - maybe the system was slowed down by a running process. Still likely that adding an index will speed this up:

> select previousho0_.hospitalization_id as hospita13_31_0_, previousho0_.id as id1_31_0_, previousho0_.id as id1_31_1_, previousho0_.changeDate as changeDa2_31_1_, previousho0_.creationDate as creation3_31_1_, previousho0_.uuid as uuid4_31_1_, previousho0_.admissionDate as admissio5_31_1_, previousho0_.community_id as communi10_31_1_, previousho0_.description as descript6_31_1_, previousho0_.dischargeDate as discharg7_31_1_, previousho0_.district_id as distric11_31_1_, previousho0_.healthFacility_id as healthF12_31_1_, previousho0_.healthFacilityDetails as healthFa8_31_1_, previousho0_.hospitalization_id as hospita13_31_1_, previousho0_.isolated as isolated9_31_1_, previousho0_.region_id as region_14_31_1_, community1_.id as id1_6_2_, community1_.changeDate as changeDa2_6_2_, community1_.creationDate as creation3_6_2_, community1_.uuid as uuid4_6_2_, community1_.archived as archived5_6_2_, community1_.district_id as district8_6_2_, community1_.externalID as external6_6_2_, community1_.name as name7_6_2_, dist
