### ISSUE TITLE
[SurvNet Interface] Add bulk action  to send events to SurvNet

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#4311]
### Situation Description
Situation Description
Thus far, events can only be sent individually to the SurvNet instance. This is pesky when a lot of data has to be processed and might lead to events not being transmitted because people might forget to send the data.

### Feature Description

- Introduce a bulk action option to send many events to SurvNet at once.
- Show a notification when events are included that do not have a cluster status.

**Comment by MateStrysewske** [comment]
Duplicate of #4257
