### ISSUE TITLE
Task notifications should be sent to users at the right time 

### ISSUE THREAD

**Issue by Emond-Fuseau** [hzi-braunschweig/SORMAS-Project#4334]
Hello,
We are encountering a problem with the sending of the notification of tasks  related to event, case and contact  to users.
User have been receiving tasks by email in the past but currently, tasks are sent at the wrong time as explained below.,
Here is a description of the problem:
- We create a task (on an event, a case or a contact, it doesn't matter, the problem is the same on all the perimeters) with, for example, the following criteria:
o The task is created on 08/02 at 11:49 a.m. (start of task)
o Its deadline is 10/02 at 12 noon (due date of task)
- We designate a user (with an email) as responsible for the task
- The user receives the notification when "Task should start" and "Overdue task"  at the same time.
- These notifications are sent at the time of the due date, that is, in our example, 10/02 around 12 noon.

**Expected behavior**
- The user should receive a "Task to start" notification on 02/08, within ~ 5 minutes of the creation of the task, i.e. around 11:54 a.m. at the latest, indicating that a task is assigned to him
- The user must then receive an "Overdue task" notification on 02/10 at 12 noon, reminding him that a task is assigned to him

This operation is very problematic for users in France who receive an alerts daily when the task must be completed ... It is necessary to distinguish the two notifications:
- Sending notification of the "Task to start" = when the task is created
- Sending the notification of the "Overdue task" = at the time of the deadline

Thank you in advance for solving this problem.

Best regards,

Jeanne-Marie

@carolinverset
@bernardsilenou
@ftavin

**Comment by bernardsilenou** [comment]
@Emond-Fuseau, @ftavin Please can you add the version that this happens?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
This is a bug in the recent version because all works perfect in the past:
In summary we have to send task messages  if task status == pending:
1. On same day and immediately when the task is created (consider time here, since automatic 00:00 rule would not apply here)
2. On the date of suggested start
3. On due date

**Comment by Emond-Fuseau** [comment]
@bernardsilenou Oui, il s'agit de la version 1.52.1.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't see a change in the code that would have caused this in one of the most recent versions, but we'll have a look at it anyway. Please note that we don't send messages when a task is created. There's one message when a task is supposed to be started and one when it's reached its due date.

**Comment by Emond-Fuseau** [comment]
Hello Mate,

Thank you for your reply. However, it seems to us that the behavior was different before and that the notifications were sent in 2 separate times. This is all the more important since the user must be warned of his task before it comes "due", otherwise he is always late.

**Comment by Emond-Fuseau** [comment]
Hello Mate,

Thank you for your reply. However, it seems to us that the behavior was different before and that the notifications were sent in 2 separate times. This is all the more important since the user must be warned of his task before it comes "due", otherwise he is always late.

**Comment by Emond-Fuseau** [comment]
@bernardsilenou @MateStrysewske 
Hello Mate!

Thank you for your reply. However, it seems to us that the behavior was different before and that the notifications were sent in 2 separate times. This is all the more important as the user must be notified of his task before it is "due", otherwise he is always late.

But maybe this setting could be done locally and it was this solution that had been chosen for France? 
Is it possible to make a specific setting?

**Comment by Emond-Fuseau** [comment]
@bernardsilenou @MateStrysewske 

Hello!

Thank you for your reply. However, it seems to us that the behavior was different before and that the notifications were sent in 2 separate times. This is all the more important as the user must be informed of his task before it is "due", otherwise he is always late.

But maybe this setting could be done locally and it was this solution that had been chosen for France?
Is it possible to make a specific setting?

**Comment by bernardsilenou** [comment]
@MateStrysewske @markusmann-vg  I got informed from @carolinverset that this did not happen today, so maybe a wrong setting was done at the server side.  We should not allocate resources on investigation this until the bug is experienced again. If nothing happen after a month, then we can just close the ticket.

**Comment by MateStrysewske** [comment]
@bernardsilenou Okay, I'll move it out of the current sprint then for now.

**Comment by bernardsilenou** [comment]
No more feedback that this occurs again.
