### ISSUE TITLE
Merging cases with exposures duplicates their locations and sets them on both exposures

### ISSUE THREAD

**Issue by nliakm** [hzi-braunschweig/SORMAS-Project#4338]
### Bug Description
While updating the productive servers from 1.52.1 to 1.54.1, a few sormas servers failed after the step:
`Updating database to version 309... (de.symeda.sormas.backend.common.StartupShutdownService.java:590)`

[sormas.log.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/5961447/sormas.log.zip)

**Comment by bernardsilenou** [comment]
@nliakm We informed other international servers to upgrade to 1.54.1. Do you think this issue may apply to them also ?

**Comment by nliakm** [comment]
@bernardsilenou We have to investigate this further. Seems like only with a specific data constallation, this problem happens. This also occured on musterstadt.sormas-oegd.de (this was on 1.53 before, but had the exact same error message). Maybe we can provide a database dump to the developers.

**Comment by MateStrysewske** [comment]
I suspect the following to lines of code are responsible for this:

```
UPDATE location SET facilitytype = 'HOSPITAL' WHERE facilitytype IS NULL AND (SELECT typeofplace FROM exposures WHERE location_id = location.id) = 'HOSPITAL';
UPDATE exposures SET typeofplace = 'FACILITY' WHERE (SELECT facilitytype FROM location WHERE id = exposures.location_id) IS NOT NULL;
```

We probably need to attach an updated script to the release notes that server admins can execute prior to the update in order to fix this. The relevant error message is `org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression`.

**Comment by MateStrysewske** [comment]
@nliakm Can you please execute (or ask someone to execute) the following script in the database of one of the affected servers and pass the results to me?

```
SELECT location_id, COUNT(location_id)
FROM exposures
GROUP BY location_id
HAVING COUNT(location_id)>1
```

**Comment by nliakm** [comment]
@MateStrysewske 
Output from the servers:

```
 location_id | count 
-------------+-------
       10797 |     2
        7746 |     2
(2 rows)
```
```
 location_id | count 
-------------+-------
      101110 |     2
      101382 |     2
(2 rows)
```
```
 location_id | count 
-------------+-------
       68864 |     2
(1 row)
```

**Comment by MateStrysewske** [comment]
@nliakm Thanks! It seems like some faulty data sneaked its way into the server, either because there were manual database operations (unlikely) or because the migration script we'd written that created exposures from epidemiological data has errors, or maybe because we have some problems with duplicate case merging or case cloning.

I have prepared a script that can be used to correct the wrong data, which will then make sure that the update to the new version will work, but ideally I'd like to find out why this happened in the first place. Could you please execute the following scripts on one or both of the servers and give me the results?

Server 1:

```
SELECT disease FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (10797, 7746);
SELECT deleted FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (10797, 7746);
```

Server 2:
```
SELECT disease FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (101110, 101382);
SELECT deleted FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (101110, 101382);
```

**Comment by nliakm** [comment]
@MateStrysewske 
Server 1:
```
sormas=> SELECT disease FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (10797, 7746);
   disease   
-------------
 CORONAVIRUS
 CORONAVIRUS
 CORONAVIRUS
 CORONAVIRUS
(4 rows)

sormas=> SELECT deleted FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (10797, 7746);
 deleted 
---------
 t
 f
 f
 t
(4 rows)
```
Server 2:
```
sormas=> SELECT disease FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (101110, 101382);
   disease   
-------------
 CORONAVIRUS
 CORONAVIRUS
 CORONAVIRUS
 CORONAVIRUS
(4 rows)

sormas=> SELECT deleted FROM cases LEFT JOIN exposures ON exposures.epidata_id = cases.epidata_id LEFT JOIN location ON location.id = exposures.location_id WHERE location.id IN (101110, 101382);
 deleted 
---------
 f
 f
 t
 t
(4 rows)
```

**Comment by MateStrysewske** [comment]
We've identified how this happened: When merging two cases where the secondary case (i.e. the case that gets merged into the other and then deleted) has an exposure, the exposure is cloned and copied to the new case, but its location is not cloned. Instead, the reference is copied into the new exposure, which means that both exposures (the one associated with the deleted case and the new one associated to the case that remains active) reference the same location. That's not a problem when using the application in general, but it will make any SQL script that relies on locations only being associated with one exposure failing.

To fix this, we will:
* Make sure that locations are properly cloned when merging cases
* Provide an SQL script that will remove duplicate location references from exposures of deleted cases

This SQL script will automatically run when updating to 1.57.0, and it can additionally be executed manually on any server that can't be updated to 1.54.1 right now.
