### ISSUE TITLE
Listing samples for a lab officer can be slow [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4346]
### Problem Description
Listing the samples for a lab officer seems to get all samples for all cases where the user has access to at least one sample of the case. So the query goes from sample to case to sample.

### Proposed Change
From my understanding for the user jurisdictions LABORATORY and EXTERNAL_LABORATORY, we should only list samples that are associated to the user's laboratory.

This would mean that the additional filters based on the sampleAssociationType in SampleService.createUserFilter would not have to be done for those two user jurisdiction types.

@bernardsilenou Could you validate whether this would be sufficient? Is there a use case where a lab user needs to have access to the other samples of a case/contect/event participant that are not associated to the user's lab?

**Comment by StefanKock** [comment]
@MartinWahnschaffe can please be more specific which class and method one has to look on?

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe  You are right. 
- I also think this is enough: ` we should only list samples that are associated to the user's laboratory.` This should also be  the  same for the case directory of the lab officer.
- If a case is in the jurisdiction of the lab and the ample of the case is not assigned to the lab, then the lab user has no access to the sample nor the case. If the case is not in the jurisdiction of the sample and the sample is assigned to the lab, then the lab has full access to both case and sample.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.58.0-SNAPSHOT on test.sormas.netzlink.com
The Slowliness for the LAb Officer user was not observable. 
Samples/Cases created outside of jurisdiction were not accsesible

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she @MartinWahnschaffe @MateStrysewske 
I had a look at the lad officer role on https://test.sormas.netzlink.com/sormas-ui/ on 1.58 and found the following.
Lab officers only see cases with samples assigned to their labs :+1:  However,
 - case directory was pseudonymized
 - case form and sample are read access only
 - you can only edit pathogen test through the sample directory 
 - associated entity person names (case, contact, ep) are hidden.

This is not OK for the international instance. As long as the sample if associated to the lab, lab officers in the lab should have full access on the case, contact and event participant. I can not tell if all these points are related to configuration or bug. 

For samples linked to event participant, lab officer can not edit pathogen and additional pathogen test
![image](https://user-images.githubusercontent.com/12996724/110040409-0d0a6d00-7d43-11eb-954b-9e34fb443035.png)

For samples linked to a contact that (is also linked to an event) 
   - Lower part of sample in formation can be edited :+1:  But the the upper part, specifically purpose of sample can also be edited thus resulting to a bug :-1:  Purpose of sample should be read only as long as the lab user is not the reporting user. Creation of pathogen test was OK :+1: 

Just realized contacts and ep menu are hidden, would create an issue for that.

Do you know if there is any configuration that netzlink need to adjust on the the international test instance?

**Comment by StefanKock** [comment]
@bernardsilenou please document your findings not related to the ticket topic in a new ticket.

**Comment by bernardsilenou** [comment]
I did a test on https://test.sormas.netzlink.com/sormas-ui/ and lab officers only see samples assigned to their lab.
The bug does not exist anymore when the purpose of sample if edited. However, then goal was to make this variable read only `Purpose of sample should be read only as long as the lab user is not the reporting user.`
- Sample with uuid TIJCZM-5Q7TCV-KHJ5WS-ZW2OCNE4 is assigned to Voreingestelltes Labor, but a lab officer in this lab could not edit the sample, any idea why?
- Other issues would lab, would be handled in #4694

**Comment by MateStrysewske** [comment]
@ssferrazza Can you please check why the sample mentioned by Bernard does not appear in the sample list of the LabOfficer user on the test system?

**Comment by ssferrazza** [comment]
@MateStrysewske sure, I check this

**Comment by bernardsilenou** [comment]
@ssferrazza The lab officer can see but can not edit. The goal is to find out why?

**Comment by MateStrysewske** [comment]
Replace the code in SampleJurisdictionHelper:38-41 with the code from SampleJurisdictionChecker:36-40 and remove that code from SampleJurisdictionChecker
