### ISSUE TITLE
[SORMAS 2 SORMAS] Send and receive Events [5]

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#4348]
### Situation Description
Implement SORMAS 2 SORMAS for Events

### Feature Description
- [ ] Send and receive Events
- [ ] Add option to send event participants
- [ ] Add filter to show only sent/received events and participants
- [ ] Add bulk action for sending multiple events

**Comment by MateStrysewske** [comment]
Pushing events from the mobile app to the web backend doesn't work anymore because the field name `isOwnershipHandedOver` in EventDto is wrong. I'll provide a fix for this soon.

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of sormas 1.58.0-snapsot on test-de1 and test-de2.sormas.netzlink.com environments.
