### ISSUE TITLE
External visits user role prevents viewing tasks

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4351]
### Bug Description
Holding the external visits user role leads to a complete loss of the tasks at the task management view. 
Self assigned tasks, as well as tasks of other users are not shown in the task management. 
### Steps to Reproduce
1. Create a user that holds the external visits user role (plus contact supervisor, clinician, surveillance supervisor)
2. Create a task and assign it to this above mentioned user
3. Login with user (1.) and take a look at the task management view 
4. Login as admin and remove the external visits user role from user (1.) 
5. Login with user (1.) and take a look at the task management view 

### Expected Behavior
Since the external visits user role is not coupled to any user right, the person holding this role (plus e.g. contact supervisor, clinician, surveillance supervisor) should be able to see all user-related tasks, as well as tasks assigned to other users. 
### Screenshots
The user holds the "external visits user" role
<img width="721" alt="image" src="https://user-images.githubusercontent.com/76884029/107643979-1e49e780-6c77-11eb-928f-6ba9e536c735.png">
and is not able to see self assigned tasks, as well as tasks of other users
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/76884029/107644186-66690a00-6c77-11eb-9311-0b62b80116b7.png">
Removing the role of the external visits user...
<img width="722" alt="image" src="https://user-images.githubusercontent.com/76884029/107645245-c44a2180-6c78-11eb-9791-f0d514e060d5.png">
enables the view all tasks and...
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76884029/107644477-c495ed00-6c77-11eb-9142-37e130a9ea6e.png">
self assigned tasks.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76884029/107644557-dd9e9e00-6c77-11eb-827f-5e7b5c816c09.png">

### System Details
* Device: desktop pc
* SORMAS version: 1.52.1; 1.54.1; 1.56.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/
* User Role: external visits user role (plus contact supervisor, clinician, surveillance supervisor

**Comment by MateStrysewske** [comment]
@maxiheyner The external visits user is not supposed to be a user of the SORMAS application. Its sole purpose is for authentication with the interface that allows to push information from external symptom diaries/journals to the SORMAS database.
