### ISSUE TITLE
Filtering by case origin results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4354]
### Bug Description
When trying to filter by the case origin on the cases directory, an error appears.
### Steps to Reproduce
1. Open the cases directory
2. filter by case origin

### Expected Behavior
filtering should work fine.
### Screenshots
<img width="614" alt="filterBug" src="https://user-images.githubusercontent.com/70317594/107661587-b3ee7280-6c89-11eb-8da7-703420a6d862.PNG">

### System Details
* Device:
* SORMAS version: 1.56.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
Verified on version 1.57.0-snapshot on Test instances and issue is Fixed.
