### ISSUE TITLE
Covid variant should also appear on the international instance

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4357]
### Bug Description
Disease variant is missing on international instance
### Steps to Reproduce
1. Create a covid case on https://release-international.sormas.netzlink.com/sormas-ui/

### Expected Behavior
- Covid variant should also appear on the international instance
- It must not be added to the mobile app, we can  add it latter, but for the web app we need it on 1.56
### System Details
* Device: web
* SORMAS version: 1.56
* Android version/Browser:
* Server URL:
* User Role: admin + national user

**Comment by Candice-Louw** [comment]
+CH instances, please.

**Comment by MateStrysewske** [comment]
@bernardsilenou @Candice-Louw The disease variants are not exclusive to any locale. I suppose there haven't been any variants added to the database on that server.

**Comment by Candice-Louw** [comment]
Guide to adding new values in the database for disease variants: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/GUIDE_ADD_NEW_DISEASE_VARIANT.md
