### ISSUE TITLE
Typing id and specify test details value fields does not get enabled during result entry in sample creation window

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4358]
### Feature Description
#4125 added specific pathogen test variables to the form. However, it was not  clearly specified because some variables are still missing.
### Problem Description
- Information: 
        * addition attributes of  PCR or Cq value detection == `typing id`, `qc/ct value`, `specify test details`
        * addition attributes of  sequencing or DNA Microarray == `typing id`, `specify test details`
- some of the attributes are missing on the forms when creating a new pathogen test (both for sample that exist or while creating a sample).
### Proposed Change
- If type of test == PCR or Cq value detection,  add `typing id`, `qc/ct value`, `specify test details` . Cq value detection is a duplicate of PCR, so we would latter migrate Cq value detection to PCR and delete Cq value detection enum
-  If type of test == sequencing or dna microarray,  add `typing id`, `specify test details` 
- Add these attributes on both forms: sample+pathogen test  or pathogen test only

**Comment by bernardsilenou** [comment]
@MateStrysewske Please can you schedule this ticket in the current or next sprint? The urgency is that the data collected depends on the path of the user.

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou 
Should the qc/ct value field only be shown if the test type is PCR or CQ Value Detection **and** is positive? Currently, the field is disabled if the testresult is negative or undefined

**Comment by MateStrysewske** [comment]
@bernardsilenou This is working perfectly fine, both when creating a pathogen test directly while creating a sample as well as when creating a pathogen test for an existing sample. Please keep in mind that the QC/CT value field only appears for POSITIVE PCR tests, maybe that lead to some confusion here.

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen   _qc/ct value field should only be shown if the test type is PCR or CQ Value Detection and is positive? Currently, the field is disabled if the testresult is negative or undefined_  We can leave it as it is since for negative results this number is large and may not be useful. My main point here was that qc/ct value field should only be shown PCR or CQ Value Detection.

**Comment by bernardsilenou** [comment]
@MateStrysewske Your reason for closing the issue is not what I was saying. I was adding the  variables that are missing when creating sample+ pathogen test at the same time and when editing pathogen test. I would rename the issue, sorry for that.

This is an example of mismatch

![image](https://user-images.githubusercontent.com/12996724/107827748-c0f18b80-6d87-11eb-896f-95d03469a135.png)

![image](https://user-images.githubusercontent.com/12996724/107827849-debef080-6d87-11eb-80b1-9d0366260d74.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou Again, this is working perfectly fine. I don't know which server you're testing on, maybe it hasn't been updated to the latest version yet. On https://test.sormas.netzlink.com everything is working as intended.

**Comment by bernardsilenou** [comment]
@MateStrysewske I did a test on https://test1401.sormas-oegd.de/sormas-ui/ and on https://release-international.sormas.netzlink.com/sormas-ui/. Both are on 1.56.1 and it did  not work.
On https://test.sormas.netzlink.com , on 1.57, it works perfectly. It is a version issue. I thought is was to be merged on 1.56.1.
Thanks

**Comment by MateStrysewske** [comment]
@bernardsilenou Alright :) please always do your testing on the latest development version, otherwise the risk of duplicate bug reports is way higher (as we can see in this issue right here).
