### ISSUE TITLE
[SurvNet Interface] External ID field has to be hidden on creation form when SurvNet  interface is configured [0.5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4360]
### Feature Description
greyed out external Id field for adoption of SurvNet Guid.
### Problem Description
The external Id field can be filled in the case creation form but is greyed out in the case information since it's used to adopt the SurvNet Guid when the interface is configured. When the external Id now has been filled in the creation form and saved, it can not be deleted anymore to subsequently allow the adoption of the Guid.
### Proposed Change
When the SurvNet interface is configured, the external Id has to be hidden in case creation forms. This includes creating cases through the DEMIS interface.

In the process, also hide external Id of persons when the SurvNet interface is configured.
### Additional Information
<img width="516" alt="Screen Shot 2021-02-12 at 10 46 52 AM" src="https://user-images.githubusercontent.com/70317594/107754479-d3d17500-6d21-11eb-9e3c-855af9b7aaab.png">
<img width="577" alt="Screen Shot 2021-02-12 at 10 48 20 AM" src="https://user-images.githubusercontent.com/70317594/107754491-d8962900-6d21-11eb-9f69-dd6178e134d1.png">
@MateStrysewske

**Comment by kwa20** [comment]
@JaquM @markusmann-vg

**Comment by vidi42** [comment]
> In the process, also hide external Id of persons when the SurvNet interface is configured.
@kwa20 Should we hide the external Id for persons in the Edit Form? Because as far as I know there is no create form specific for Persons. I might be wrong though

**Comment by JaquM** [comment]
@vidi42 
 Yes, hide the external ID for persons as well.

**Comment by Alexandru-Pirvu** [comment]
@kwa20 The event creation form also contains the external id field, uneditable. Should we remove it from there also?
<img width="930" alt="Screenshot 2021-03-22 at 15 45 11" src="https://user-images.githubusercontent.com/27289028/111999387-98e30e00-8b25-11eb-8e93-479e66942ab5.png">

**Comment by kwa20** [comment]
@Alexandru-Pirvu If it's uneditable it's fine, actually, because the problem only occurs when entries are being made on the creation form that cannot be changed or removed later on. This won't be the case for events then.
