### ISSUE TITLE
Multiday event dates are not correctly validated in android app

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4362]
### Bug Description

The validators for multiday events are faulty in the android app

### Steps to Reproduce
1. Log into the android app
2. Open Event directory
3. Create a new event
4. Select "Multiday Event" checkbox
5.1 Select dates in the future
5.2 select endDate<startDate

### Expected Behavior

Step 5.1 should not throw an error. Step 5.2 should throw an error

### System Details
* Device: Emulated Pixel2
* SORMAS version: 1.57.0-Snapshot
* Android version/Browser: Android 11.0 API 30
* Server URL:
* User Role: Surveillance Officer

### Additional Information

See reference for implementation here: https://github.com/hzi-braunschweig/SORMAS-Project/pull/4317

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot
