### ISSUE TITLE
Add reportDate to pathogen test

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4363]
### Feature Description

- [ ] Add field to entity, dto and UI (put below reporting user)
- [ ] Also for mobile app

Field is NOT mandatory

**Comment by kwa20** [comment]
@MartinWahnschaffe I think the reportDate, i.e. date when the test result was reported by the lab to the health department, should go with the pathogen test.

<img width="440" alt="Screen Shot 2021-02-12 at 12 46 08 PM" src="https://user-images.githubusercontent.com/70317594/107764442-814b8500-6d30-11eb-96ed-cf952e9545f5.png">

**Comment by MartinWahnschaffe** [comment]
@kwa20 Thanks a lot - I somehow managed to mix up the screenshots.
@cazacmarin Please put the report date between test result and test result details in a new line

**Comment by kwa20** [comment]
@MartinWahnschaffe I think the usual process would be to enter when the test result was reported and then what the result and its specifications were. I think we should therefore place it at the top of the pathogen test result.

**Comment by kwa20** [comment]
@MartinWahnschaffe Also, just so I don't forget. This field should appear not only in the pathogen test creation form but also in the direct entry option inside the sample creation form and DEMIS processing form. @MateStrysewske  noted that there are slight differences between the forms that lead to new fields not being added to such forms because they were forgotten during development

**Comment by bernardsilenou** [comment]
@kwa20 @MartinWahnschaffe 
- Is there a specific reason whey we need to know when the health departments was informed of each pathogen test results?
- For the international instance the most important date is the date of result. Users do not report pathogen test results back to health departments ie they do not track the date results move from lab, districts, national level etc.
-  Can we add this variable to the DE instance only? I see a likelihood that users may use the report date to mean the date that the lab is reporting the result which is technically the same as  date of test result.

**Comment by kwa20** [comment]
@bernardsilenou to provide some explanation: Among others, German health authorities use this date to estimate the delay of reporting. This date basically describes the date when the report is issued to the health departments which hopefully is the date of the test result but might not necessarily be due to delays. Since we don't have laboratories directly using Sormas in Germany unfortunately, this type of reporting usually goes through a whole process.

**Comment by bernardsilenou** [comment]
@kwa20 still some question please:
- delay in reporting is date from when till when ? Is this  the date result was sent by lam - date lab did the test ?
- date and time of results in reality is the date that the lab officially declared the result.
- If the goal is to know the delay from when the lab declared the result till when it gets to the GE, then we should be talking about date received at district, right? and a lab officer should not be able to edit this date

**Comment by kwa20** [comment]
@bernardsilenou 
- date of report in that case would be the date where the reporter filed the report (not to be confused with the date of report of the case)
- the dates regarding the paper forms do not really fit the german use cases very well and are therefore not used as far as I know.

**Comment by MartinWahnschaffe** [comment]
@kwa20 @bernardsilenou What's the result of your discussion. Should we include the field for Germany only?

**Comment by MartinWahnschaffe** [comment]
For now we will

- [ ] make the field "GErmany" only in the vaadin ui
- [ ] Hide the field in the mobile app
- [ ] Add the field to the sample list information within the case (Germany only, as-well)

**Comment by AndyBakcsy-she** [comment]
verified ticket on the latest version of Sormas version 1.57.0-snapshot on local environmet

**Comment by raghupola-vg** [comment]
On test instances Report date is not visible on Case view, Event Participant view, Lab messages processing view and so the issue is reopened.

**Comment by raghupola-vg** [comment]
verified issue on German test instances. On android app the field is still visible.

**Comment by cazacmarin** [comment]
@raghupola-vg 
Hello Raghu.
Conversation from Martin.
If, we are not able to make the field visible only for DE on mobile app, we need apply it on mobile on future versions.
Field is visible only for DE on mobile app.

I'm closing the ticket :slightly_smiling_face:
