### ISSUE TITLE
Sorting event risk column in actions directory results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4375]
### Bug Description
When trying to sort the event risk level column in the actions directory an error occurs.
### Steps to Reproduce
1. Go to the actions directory
2. sort the event risk level column

### Expected Behavior
Sorting the event risk level column should work fine.
### Screenshots
<img width="717" alt="actionsDirectoryRiskError" src="https://user-images.githubusercontent.com/70317594/107849962-00a78a00-6dff-11eb-8a70-e403237b352f.PNG">

### System Details
* Device:
* SORMAS version: 1.56.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on local environment
