### ISSUE TITLE
Filtering the sampels directories by contacts and event participants samples results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4377]
### Bug Description
Filtering the sample directory by contact samples and event participant samples results in error.
### Steps to Reproduce
1. Go to the sample directory
2. Filter by contact and event participant samples

### Expected Behavior
Filtering for the respective filters should work fine
### Screenshots
<img width="852" alt="contactSamplesError" src="https://user-images.githubusercontent.com/70317594/107878203-55b3d080-6ed1-11eb-8f35-3df1fe394a26.PNG">
<img width="852" alt="epSamplesError" src="https://user-images.githubusercontent.com/70317594/107878205-577d9400-6ed1-11eb-9eaf-18224dec3946.PNG">

### System Details
* Device:
* SORMAS version: 1.56.0/1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on local environment
