### ISSUE TITLE
Source case cannot be chosen when creating contacts through the event participant form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4380]
### Bug Description
When a contact is being created through the event participant form for an event participant person that already has a linked case, the option to choose a source case is missing.
### Steps to Reproduce
1. Go to an event and add an event participant.
2. Go to the event participants form and create a contact without saving. Check whether you can choose a source case.
3. Navigate back to the event participant list and create a case through the create button in the list. Save.
4. Go back to the event participants form and create a contact again, check whether a source case can be chosen.

### Expected Behavior
A source case should always be able to be chosen when creating a contact.
### Screenshots
<img width="390" alt="chooseCaseEp" src="https://user-images.githubusercontent.com/70317594/107886739-3e410b80-6f02-11eb-99a2-b4d5231ecba1.PNG">
<img width="394" alt="chooseCaseEp2" src="https://user-images.githubusercontent.com/70317594/107886742-3f723880-6f02-11eb-86b0-4bd66765a392.PNG">

### System Details
* Device:
* SORMAS version: 1.56.0/1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 Are you sure that the source case is not automatically chosen?

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.57.0-SNAPSHOT on local environment
