### ISSUE TITLE
[DEMIS Interface] Make Lab message and creation forms independently scrollable [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4381]
### Feature Description
Lab messages DEMIS interface. 
### Problem Description
When scrolling through the lab message during the processing, the creation forms get scrolled out of view because the lab message is longer than the creation forms. This makes it harder and more time consuming to compare and make entries.
### Proposed Change
During the processing, make the lab message and creation forms (and duplicate detection forms) independently scrollable to enhance user friendliness and efficiency.
### Additional Information
Implementation suggestion by @MartinWahnschaffe : Put the left side component into another verticallayout that has a fixed height matching the height of the form on the right side. This should than automatically add scrollbars for the inner component that display the lab message description.

**Comment by MartinWahnschaffe** [comment]
Suggestions: Give the full layout a fixed height, approx. matching the right component, so the left component will get a scrollbar.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.58.0-snapshot
