### ISSUE TITLE
Quarantine Order Templates is not fully displayed

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4384]
### Bug Description

The Quarantine Order Templates- window has a scrollbar since 1.54.1, which is not suitable for users.

### Steps to Reproduce
1. Open Configuration -> Document Templates

### Screenshots
![grafik](https://user-images.githubusercontent.com/74791118/107918741-8267f680-6f6a-11eb-82ce-2167022d4472.png)

### System Details
* Device: Win 10 / Android 9
* SORMAS version: 1.54.1
* Android version/Browser: FF 85, Edge,  FF Android Browser
* Server URL: own instance
* User Role: Admin

**Comment by MateStrysewske** [comment]
I think the relatively simple solution here is to simply increase the width of the whole view because it's pretty narrow right now.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske I just discovered, that this problem is gone with the new document-handling in 1.57-snapshot

![grafik](https://user-images.githubusercontent.com/74791118/108064190-9c820180-705c-11eb-82e4-77cc4591254b.png)

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Thanks for the heads-up!
