### ISSUE TITLE
Users on district level and below can't filter the case directory by jurisdiction

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4389]
### Bug Description
Users on district level or below (currently not implemented) can currently not filter cases by jurisdiction. All jurisdiction fields are disabled when only everything above and including their own jurisdiction level should be disabled (so for district-level users, region and district should be pre-selected and disabled).

### Expected Behavior
Enable filter fields below the user's jurisdiction level. E.g. surveilance officers need to be able to filter by community and health facility.

**Comment by raghupola-vg** [comment]
Verified on test environment with version 1.58.0-Snapshot with user role SurvOff.
