### ISSUE TITLE
[Angular] Cases Table

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4393]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
- Clicking on the menu item "Cases" will take the user to the "Cases" page
- Implement the table structure based on the current implementation: https://test.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE (must include the same columns)
- Implement the required design (please consult):
-- https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/g01Qdpx
-- https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/52nm8ay
- The table should use the lazy load feature as per the current implementation 
- The table should be responsive based on the decided breakpoints. *NOTE* The table won't change for lower res displays

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by Marko-ilmkreis** [comment]
The new design looks very good! Thanks!

**Comment by Marko-ilmkreis** [comment]
@laurentiustanvitagroup is it planned to have a testserver for that? I would like to show the new design to our colleagues to get their feedback.

In my opinion it is a big step forward, but I also know that the users sometimes are does not like changes in the UI ;)

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis There will be a test server at some point when the new application is usable in some way, but we don't exactly know when that will be the case yet
