### ISSUE TITLE
[Angular] Column picker (select / deselect) [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4395]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
- Implement the column picker section as per the design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/g01Qdpx
- this dropdown should be in the table component
- it should receive the columns array and at first, all columns are selected
- we should implement this multi select in a custom component, custom-multiselect in the shared module, using the angular material multiselect and customizing the style to look just like in the design. We will use the same custom multi-select component for other locations of the dropdown
- also the functionality should be implemented : if you deselect a column, it should dissapear from the table and 
vice versa
-  The user preferences should be saved in the local storage (as long as the keycloack session is still used) (Note: Please investigate if this is viable, if the keycloack session is to short, it might be best not to work on this feature now, and added later).
- In the local storage we should store the key and not the translated name of the column.

Note: We need to make use of the functionality to have the ability to make certain columns "untouchable" (the ones containing a link (i.e ID)).
Note: If an option from the multi-select length is too long, we should display "..." and not force the item on two rows.

Notes: (From @MateStrysewske)
1. I'd say any column that is currently part of the grid in the selected view option (users can currently switch between Standard, Detailed and Follow-up overview) and that is NOT integral to the functionality of the grid (e.g. if you'll use a specific column to allow users to enter the case, as simply clicking on a row should NOT open it, that column should not be deselectable).
2. Every column that is currently part of the selected view option.

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
