### ISSUE TITLE
Bulk action | Sending to SurvNet returns error message + confirmation message

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4401]
### Steps to Reproduce
1. open test1402.sormas-oegd.de 
2. Go to cases 
3. Select bulk actions and choose Send to SurvNet
4. Check the messages

### Expected Behavior
There should either be one error message or one successful message. 
Please check the attached screenshot
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/107987337-7ade3700-6fd6-11eb-82c4-e51ac5452ada.png)

### System Details
* Device:
* SORMAS version:1.56.1
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: SurvOff

**Comment by kwa20** [comment]
I could also reproduce this problem with the 3.3.0 converter
