### ISSUE TITLE
Field names "$!case.quarantineOrderedVerballyDate" in documents templates

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4404]
In the new templates (SORMAS-Project/sormas-ui/src/main/resources/ExampleDocumentTemplateCases.docx ) the fieldname for the verbally ordered quarantine is written with an "!" at the beginning

`$!case.quarantineOrderedVerballyDate`

Is this right, as in the data dictionary the "!" is missing in the field names and at the present for the documents also not needed.

**Comment by syntakker** [comment]
The meaning of the prefix exclamation mark is that the variable is not displayed if it is empty.
So if `case.quarantineOrderedVerballyDate` is empty, `$!case.quarantineOrderedVerballyDate` is not displayed at all, i.e., especially not the placeholder for empty values "./.".
If there is data for `case.quarantineOrderedVerballyDate` it is displayed as before.

**Comment by Marko-ilmkreis** [comment]
@syntakker Great Thank you!

**Comment by syntakker** [comment]
You're welcome! Thank you for your feedback :-) See also explanation in #3991.

**Comment by Marko-ilmkreis** [comment]
@syntakker I just write in this issue again, because I don't want to open a new one.

I uploaded to https://test-de1.sormas.netzlink.com/ these to file for contacts and cases:
[Adressfeld - Kontakt.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5987934/Adressfeld.-.Kontakt.docx)
[Adressfeld - Fall.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5987935/Adressfeld.-.Fall.docx)

If I generate a document, I get the following error in the file:

![grafik](https://user-images.githubusercontent.com/74791118/108051550-52445480-704b-11eb-87a5-bb3c3dd44265.png)
Here is the output: [VWBK7E_Adressfeld - Fall.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/5987942/VWBK7E_Adressfeld.-.Fall.docx)

The reason for the error is the line feed with the switch \f at the field $!contact.person.address.additionalInformation. This is to make sure that there is no empty line at the address-field.

For now we are living with this empty line, but maybe you have a suggestion to eliminate it.
