### ISSUE TITLE
Add external ID and external Token to the events directory and also make those fields searchable

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4408]
### Situation Description
Thus far, external Id and Token are not shown on the events directory and cannot be searched for.
### Feature Description
Add columns for the external Id and Token to the events directory and add them as searchable options.

cf. #3613 
### Additional Information
<img width="1110" alt="Screen Shot 2021-02-16 at 12 12 22 PM" src="https://user-images.githubusercontent.com/70317594/108055496-5757d280-7050-11eb-893e-2d64fcda3f07.png">

**Comment by carolinverset** [comment]
Very important for french user too. 
Thank you very much !!!

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by kwa20** [comment]
Issue tracker comment

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by bernardsilenou** [comment]
@Alexandru-Pirvu Thanks for rapid implementation from users. They needed it in 1.58

**Comment by bernardsilenou** [comment]
@Alexandru-Pirvu  Just to validate if you did not add any validation to have this fields fro DE instance only

**Comment by Alexandru-Pirvu** [comment]
@bernardsilenou The new columns and the filter will be available for all instances

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of 1.58.0-snapshot on test.sormas.netzlink.com
