### ISSUE TITLE
Investigate performance improvements when persisting data [2TB]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#4417]
### Problem Description

Follow up to #3481 and #4153: Develop ideas how to decrease the time spent for persisting data that needs to be created very often (usually case, contact or event participant).

### Topics to be investigated

- [x] Consider Hibernate 2nd level cache with NONSTRICT_READ_WRITE strategy for entities like Region/District/Community/User/etc https://www.baeldung.com/hibernate-second-level-cache
  -> #10214
- [x] Investigate where we can replace eager with lazy loading
  -> #10293
  -> Infrastructure entities always eagerly fetch their parent (e.g. District.region). This might by done lazily, but once we use the L2 cache for those, it wouldn't make a difference.
- [x] Reduce additional queries currently done to fetch sub entities and referenced entities when saving an entity. 
  E.g. by extending ReferenceDTO with id and version(changeDate) so that when mapping a relation in the DTO-to-Entity mapping we can just create the minimal detached relation entity that gets attached by Hibernate automatically, and don't fetch all the related entities if nothing is being done with them. (this is a major change in the project that affects a bit also the android app but would improve significantly all the saves)
  -> #10208
  -> ~~#10210~~
- [x] Investigate where DTO selections can be reduced to a smaller DTO for side components 
  -> Already done in #6811. Only thing left is the PathogenTestDto missing a PathogenTestListEntryDto, but I don't think this is needed.
- [x] Consider Hibernate batch insert/update - evaluate if this can be done only for the import part
  -> Not relevant for us. Import and receiving of multiple cases via ReST is saving each received "main" entity in a dedicated transaction, so rollback is done independently.

### Deliverable

New tickets that are refined enough to address performance improvements.

### Additional Information
Detailed measuring for fillOrBuildEntity: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3481#issuecomment-773260588

**Comment by markusmann-vg** [comment]
@MartinWahnschaffe to discuss it again with @StefanKock

**Comment by MartinWahnschaffe** [comment]
Resulting tickets have been assigned to the epic #7734

- #10208
- #10214
- #10210 (should not be done now)
 
and to the epic #7372

- #10293
