### ISSUE TITLE
Case directory: allow searches on the "External ID" and "External reference" fields

### ISSUE THREAD

**Issue by Emond-Fuseau** [hzi-braunschweig/SORMAS-Project#4419]
Hello!

The "External token" / "External reference" field has been added to the "case" and "contact" files, which is very valuable for users.

On the other hand, users cannot search on this field in the case directory (for the contacts directory, this works).

It would therefore be advisable to add, at the level of the case directory, a search field which would take into account the "External ID" and "External reference" fields of the "case" file. This will allow the user to search for these values.

Thanks in advance.

Best regards,

Jeanne-Marie

@bernardsilenou

**Comment by Candice-Louw** [comment]
Hallo @Emond-Fuseau - could you please see if https://github.com/hzi-braunschweig/SORMAS-Project/issues/3613 would solve this request?

**Comment by bernardsilenou** [comment]
@Candice-Louw your right, it a duplicate.
@Emond-Fuseau I would close the issue and we continue with #3613
