### ISSUE TITLE
[Angular] Legacy login

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4422]
### Situation Description
In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
We need to support the legacy login (without any Keycloack integration) as to enable developers to have an easier time in setting up their environment locally.

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by alexandrudanpop** [comment]
Done.
https://github.com/hzi-braunschweig/SORMAS-Angular/pull/48
