### ISSUE TITLE
Set the creation of default user accounts to disabled by default [0]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4431]
### Feature Description
#4129 has introduced a property that allows disabling the creation of default users.

### Problem Description
Default users are a potential security risk because server admins might forget to delete them/change their credentials, which could allow unauthorized users to get access to production systems. This violates the "Security by Default" paradigm.

### Proposed Change
Change the default user creation to be disabled by default

**Comment by JonasCir** [comment]
@MateStrysewske Should we use the chance and rename the property to disable default entities because it also avoids the creation of default region and district? It's a little bit of misnomer :)

**Comment by MateStrysewske** [comment]
@JonasCir Totally makes sense in that case, yes

**Comment by ay-kay** [comment]
I just came across this issue. Please allow me to add some follow-up questions:

1. When are the changes summarized in this issue expected to be released (1.58)?

2. 9ca8a6ac2cede24ea4f7dd6590493ef207d37752 results in no default users being created. However, this does not seem to affect the default admin user ("admin"), which is still being created using a [hardcoded](https://github.com/hzi-braunschweig/SORMAS-Project/blob/6021c3ff9f4a743b06c24496ead83b456baf9354/sormas-backend/src/main/java/de/symeda/sormas/backend/common/StartupShutdownService.java#L317-L320) password ("sadmin"). Is this correct?

3. If an administrator logs in using this default admin account, SORMAS does not seem to force the administrator to change the default password. Is this correct?

4. Any default logins created during previous installations remain valid, without notifying administrators about the presence of these accounts, e.g., during the update process or within the application. Is this correct?

5. Do you have plans to address any of these concerns?

**Comment by MateStrysewske** [comment]
@ay-kay 

1. Yes, exactly
2. Yes, the admin user still needs to be created because otherwise there's no way to access the system
3. Yes, there's no such mechanism right now
4. Yes, even though administrators should be aware of their existence because a) they're mentioned in our guides and b) I suppose they've at least used the user directory once
5. 3.) could probably be addressed in the future; I think that's a valid change

**Comment by DavidBaldsiefen** [comment]
Please Ignore this Comment :) I need to test the GitHub API

```
<!--
### Issuetracker-Description-DE [Erstellen von Standard-Nutzern]
Es kann nun konfiguriert werden, ob beim Installieren einer SORMAS-Instanz Standardnutzer erstellt werden sollen.
### End-Description-DE
-->
```

**Comment by andreasmayer** [comment]
We noticed this issue and would like to offer our support. 

We are a research group at Heilbronn University of Applied Sciences focusing on Medical Informatics with specialization on cyber security and secure software development (please see https://education.highmed.org/modules/offered-modules/secure-sw-development-for-medical-devices). 

Are you generally interested in external contributions? We would then propose to contribute a first check that prompts admins with default passwords to generate a new password. If our joint work proves to be beneficial, we could also imagine further contributions. If interested, please let us know and we will prepare a pull request.

Simon Schweizer, Maximilian Westers, Richard Zowalla and Andreas Mayer

**Comment by MateStrysewske** [comment]
#4690

**Comment by DavidBaldsiefen** [comment]
@andreasmayer 
Thank you for contributing! Please also read the [Contritbuting-Guidelines](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/CONTRIBUTING.md) and [Development Environment Guidelines](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/DEVELOPMENT_ENVIRONMENT.md)

**Comment by JonasCir** [comment]
@andreasmayer Thanks for reaching out! You can also take a look at `sormas-cargoserver` module for an easier dev setup
