### ISSUE TITLE
Add disease variant filter to the contact directory and variant to source case box [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4437]
### Situation Description
Users cannot filter for disease variants on the contact directory. This, however, might be desired when trying to filter for contacts that took place with source cases with disease variants due to higher infectiousness etc.
### Feature Description

- Add the disease variant filter to the contact directory to allow users to further filter by not only disease but also disease variant.
- Add the disease variant of the source case in parentheses after the disease in the case box on the contact information.
- The disease variant filter is only enabled, when a disease with variants is selected

### Additional Information
<img width="1114" alt="Screen Shot 2021-02-17 at 1 54 00 PM" src="https://user-images.githubusercontent.com/70317594/108208975-05837b00-712a-11eb-98a1-e51ade2139f1.png">
<img width="806" alt="Screen Shot 2021-03-24 at 12 27 57 PM" src="https://user-images.githubusercontent.com/70317594/112303471-9bb43f00-8c9c-11eb-8172-c50789867b35.png">

**Comment by maxiheyner** [comment]
Issue Tracker Comment




Add the disease variant of the source case in parentheses after the disease in the case box on the contact information.
The disease variant filter is only enabled, when a disease with variants is selected

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as the Disease variant is not displayed on the Contact part.

**Comment by Alexandru-Pirvu** [comment]
@MateStrysewske Yes, I just realized the implementation shows the uuid where only the name should be shown. Thanks for the heads up, I will create a PR fixing this.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.60.0-snapshot on local environment
