### ISSUE TITLE
[SurvNet Interface] Care/accommodation/work in facility (Android) [1]

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#4445]
split out from #4163  please check that ticket for detailed requirements

**Comment by raghupola-vg** [comment]
verified on version 1.58.0-snapshot on Android app.

**Comment by bernardsilenou** [comment]
@raghupola-vg  What is the main change that  is to be done for this ticket please? It is not clear to me how to test it.
Thanks

**Comment by MateStrysewske** [comment]
@bernardsilenou The main issue is linked in the issue description

**Comment by bernardsilenou** [comment]
verified on version 1.58.0-snapshot on Android app.
