### ISSUE TITLE
If clause not usable by the document generation with long field-names

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4447]
@syntakker We are trying to use an if clause for the document generation together with the field contact.person.address.additionalInformation. In our example we use it for a line feed if the field is filled, to avoid emtpy lines if the field is empty.
The original if clause in word is:

![grafik](https://user-images.githubusercontent.com/74791118/108316642-745de400-71bd-11eb-84a8-f02916d349de.png)

After generating the document this error occurs:
![grafik](https://user-images.githubusercontent.com/74791118/108316674-8049a600-71bd-11eb-92b2-cbcc6694fb3f.png)

The problem comes from the long field name. With other if clauses and shorter field names are nor problems.

I know that this might be only a problem for us, but maybe you have a hint how to solve. I read that velocity can use if clause by itself, but I did not found the right configuration to use in word for long field names.

**Comment by syntakker** [comment]
So it's the additional characters introduced by "case" -> "contact" and the exclamation mark "!" which hit the limit of merge field size?
A possibility would be to make the "person" available directly, so it would be "person.address.additionalInformation". Would make sense anyways if we are near the size limit.

**Comment by Marko-ilmkreis** [comment]
No, its unfortunately the long name of additionalInformation. I just tested it and word only displays 40 digits:

![grafik](https://user-images.githubusercontent.com/74791118/108333292-13400b80-71d1-11eb-8637-90602f10fa23.png)

Here the complete string:
![grafik](https://user-images.githubusercontent.com/74791118/108333289-12a77500-71d1-11eb-8863-098a383ab25b.png)

Because of this it looks like that is not handable by the document generation. It might be idea to have fields where the total lenght not exceed 40 digits.

**Comment by syntakker** [comment]
@Marko-ilmkreis "person.address.additionalInformation" has 37 characters :-) Can you check if this is still truncated, if we can drop the prefix "contact."? I would then make "person" available as a root entity, so it is accessible directly, not via "contact.person".
I would apply the same to "case" and especially "eventParticipant", where there are probably a lot of variables which would hit the size limit anyways.

**Comment by Marko-ilmkreis** [comment]
@syntakker Yes, if I drop person its "short" enough to get fully displayed and it should work. Great idea. Thanks.

**Comment by syntakker** [comment]
@Marko-ilmkreis just to make sure: "contact" would be dropped, not "person" :-)
Ok, just seen your update :-)
Another advantage would be that templates can use the same person-related sections for each of "case", "contact", "eventParticipant".
Thanks a lot for your feedback!

**Comment by Marko-ilmkreis** [comment]
> Another advantage would be that templates can use the same person-related sections for each of "case", "contact", "eventParticipant".

That is the much bigger advantange than the fix of the long fields. :-)

**Comment by Marko-ilmkreis** [comment]
Just to say: WOW, how fast this issue was solved and closed! Thanks @syntakker

**Comment by syntakker** [comment]
Thank you for your feedback :-) This is super valuable for us.
