### ISSUE TITLE
Display contact details for the event source "Institutional partner"

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4450]
### Feature Description
To date, the fields used to enter the name and the telephone and electronic contact details are only accessible by selecting "hotline / person" in the type source field.
 
![image](https://user-images.githubusercontent.com/65449450/108329068-631cd380-71cd-11eb-92dc-26d3ea1b9202.png)

By selecting “institutional partners”, these four fields are hidden.
 
![image](https://user-images.githubusercontent.com/65449450/108329116-657f2d80-71cd-11eb-8e06-31658c05015b.png)

### Proposed Change

The block relating to names and telephone and electronic contact details would be displayed as soon as the "institutional partners" modality is selected so as to provide the contact details of the contact person within the institution that transmitted the information.

### Additional Information
@bernardsilenou @ftavin  @olivierleuci

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.58.0-SNAPSHOT on test.sormas.netzlink.com
Ticket was validated on the web app
