### ISSUE TITLE
Include the external token in the search field

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4451]
### Situation Description
A new “external tocken” field has been integrated into SORMAS. It is very useful but would be even more so if this field could also integrate the textual search filter made available to users in the various directories (cases, contacts and events in particular).

### Feature Description
Integrate the "external tocken" variable in the textual search filters so as to allow users to search for a case, a contact or an event from an identifier entered in the "external tocken" field

### Additional Information
@bernardsilenou @ftavin @olivierleuci

**Comment by Candice-Louw** [comment]
@carolinverset - would this be related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/3613?

**Comment by MateStrysewske** [comment]
@Candice-Louw Yes, definitely. That means I'll close this issue as a duplicate. @carolinverset That means that it's already implemented for the case and contact directories and only needs to be done for the event directory, which should be handled in #4408.
