### ISSUE TITLE
Event participant with additional pathogen test can not be deleted

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4471]
### Bug Description
Following issue #4300, we did not find any process in the server that may create an additional test without a sample. 
 We then hypothesized that the data may have been created from the front end. I did different combinations and got 2 instances where the sample of an event participant could not be deleted and returned error, see figure.
### Steps to Reproduce
1. create pathogen test and additional test of a sample  of an ep
2. do not convert the ep to case when pop up appear in case the disease is different
3. delete the ep

### Expected Behavior
- no error message should appear
- system should navigate back to ep page ##2748
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/108451988-03bfd180-7268-11eb-8847-f3275cbd8bd0.png)

### System Details
* Device: web
* SORMAS version: 1.56.1 and 1.57
* Android version/Browser: 
* Server URL:  https://release-international.sormas.netzlink.com/sormas-ui/
               https://test.sormas.netzlink.com/sormas-ui/
* User Role: national user + admin

**Comment by bernardsilenou** [comment]
@MateStrysewske I think this may be related to why the mobile app breaks.

**Comment by MateStrysewske** [comment]
@bernardsilenou So the event participate actually gets deleted, but there's an error message popping up anyway?

**Comment by bernardsilenou** [comment]
@MateStrysewske The do not get deleted, the command leads to wrong action and nothing happens.
I would look in the additional test table today and give more feedback if i find something strange.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Contrary to your initial hypothesis, I did not find any pathogen test or additional pathogen  test without an associated sample in the db. Please can you check again?
Do you think this bug can also be the issue with the mobile app?
Here are the details of one of the ep that can not be deleted:
server: https://release-international.sormas.netzlink.com/sormas-ui/
event part == test JOHN (RRH2CO)
with  sample_id = QCJQ4E-Y7TD3Q-KAKLCH-VRVD2LZA
and additional test id == QZZW7Y-PMW2WD-KRYMGL-SB7FSGQY

**Comment by ChristopherRiedel** [comment]
I reproduced this on release-international.sormas.netzlink.com

**Comment by ChristopherRiedel** [comment]
[server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/6060973/server.log)
Log of the occuring error

**Comment by raghupola-vg** [comment]
Tested on version 1.58.0-Snapshot and issue is Fixed.
