### ISSUE TITLE
[SurvNet Interface]  GatheringType > Add "CONCERT" [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4474]
### Situation Description
The current Exposure.GatheringType does not include a "CONCERT" variable.  The existing "MUSICAL" and "CARNIVAL" values are not sufficient to address this category.

### Feature Description
Add "CONCERT" as variable to the Exposure.GatheringType enum. [all servers, please - NOT only DE servers]

### Additional Information
![image](https://user-images.githubusercontent.com/65529128/108721225-0d745e00-7522-11eb-9616-2ddc79d283de.png)

https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/32

SurvNet Mapping:

Veranstaltung -> Musikveranstaltung Konzert | 182

**Comment by raghupola-vg** [comment]
verified on test environment both on Mobile and Web on version 1.58.0-Snapshot.
