### ISSUE TITLE
No prompt for saving unsaved data if the address was changed

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4477]
### Bug Description

If you change the address in the person tab of contacts/cases and leave the form there is no dialog asking if unsaved data should be saved or discard.

It works if you change the name. Then a dialog is asking what to do with unsaved data.

Maybe this comes from the solution of #3014 .

### Expected Behavior

It should be asked every time the user changes data what to do.

### System Details
* Device: Win10
* SORMAS version: 1.58.-snapshot and 1.56.1
* Android version/Browser: FF
* Server URL: https://test-de1.sormas.netzlink.com and own instance
* User Role: every user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of  SORMAS
Version: 1.58.0-SNAPSHOT on test.sormas.netzlik.com
