### ISSUE TITLE
Entering the ct value of a samples causes error 

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4479]
### Bug Description

If you entering a sample result in Sormas 1.56.1 with a , as seperator, you get this error:
![grafik](https://user-images.githubusercontent.com/74791118/108496421-4bffe380-72aa-11eb-81fb-b426f5e358ef.png)

This looks like fixed in 1.58-snapshot. But in this version a comma would be accepted and brings a wrong value at the end:

Entered value:

![grafik](https://user-images.githubusercontent.com/74791118/108496619-9a14e700-72aa-11eb-875f-f733d3276382.png)

Value after leaving the field

![grafik](https://user-images.githubusercontent.com/74791118/108496652-a8fb9980-72aa-11eb-8a2b-4db2954d3196.png)

### Expected Behavior

Both should be accepted a "," and a "." and hold the entered value

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Sorry, for some reason I missed this issue. Will move it to the current sprint!

**Comment by heineltp** [comment]
We have the Problem that we cant add all 4 incoming CT values.
Does the upcoming version fix that problem, too?

Text would be XX/XX -,. XX/XX

**Comment by bernardsilenou** [comment]
@MateStrysewske Do we then make the field a free txt ?

**Comment by MateStrysewske** [comment]
So in general, the separator used should be based on the user language. If that's German, for example, a "," should be allowed, when it's English, a "." would have to be used as the separator.

@bernardsilenou @heineltp No, that's not fixed in this issue. Currently the CQ value field is a field that only accepts decimal numbers. Altering that would be a separate change request.

**Comment by bernardsilenou** [comment]
> We have the Problem that we cant add all 4 incoming CT values.
> Does the upcoming version fix that problem, too?
> 
> Text would be XX/XX -,.; XX/XX

@heineltp  Do you mean that the results you get from a PCR test has more than one CT value?

**Comment by heineltp** [comment]
Yes we always get 2 values - each with 2 numbers

**Comment by bernardsilenou** [comment]
@heineltp  OK, this variable was initially designed to handle only one ct value (the estimate).
- Can there be more than 2? whats is the range please ? This would help us to know if we need to make it a free txt to enter values like 25/26 - 24/26 OR to have another variable for the second value.
- 25/26 - 24/26 shows as if the values in the result is an interval or range, not  the exact estimate, is this right?
- Any information on the interpretation of these 2 values would be helpful.

**Comment by Marko-ilmkreis** [comment]
We only get one ct-value. Here is screenshot from an detail we got by fax:

![grafik](https://user-images.githubusercontent.com/74791118/112154684-cf339280-8be4-11eb-846a-9c666a902858.png)

**Comment by heineltp** [comment]
I will try to organise an example until tomorrow

**Comment by heineltp** [comment]
Good morning.
Here is a cut out of a demis result

f
![ct value](https://user-images.githubusercontent.com/78640369/112263773-26327980-8c70-11eb-8b7a-1866094a3901.png)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot
