### ISSUE TITLE
Add vaccination status filters and columns to case and contact directories and event participants view [1]

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4482]
### Situation Description
The GAs urgently need a filter and sorting option on the vaccination status of cases, contacts and event participants. 
### Feature Description
Add a column and a filter field at the detailed view of case and contact directory for the vaccination status. Add an additional filter field and column for the vaccination status at the event participants view for events. 
Might look like this for cases:

Might look like this for contacts:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76884029/108551023-99527400-72ef-11eb-9a4f-e5bba5b46b84.png">
Might look like this for event participants in events:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76884029/108551086-b2f3bb80-72ef-11eb-87c1-e11db8b371a2.png">

### Development Specifications
* Add a "Vaccination status" filter to the filter forms in the case, contact and event participant directories (not in the first row for cases and contacts)
* Add a "Vaccination status" column to the case and contact directories (to the right of symptom journal status)  and the event participant list (rightmost column)

**Comment by bernardsilenou** [comment]
@maxiheyner Nice idea!, I have minor comments to make:
1. since we already have a filter for disease and the records can be linked to different diseases,  the it would be good to just use the name `vaccination status`
2. add NA/ NULL as a category in filter. This would help us to know how many entities has NA as vaccination status. You can use the enum `Missing` that would correspond to NA. For filter on variables  that uses NA as default, then I think it would be good that we always have an option for filtering them.

**Comment by maxiheyner** [comment]
@bernardsilenou  thanks for your suggestions!

**Comment by MateStrysewske** [comment]
@bernardsilenou There's no way to filter by empty vaccination status with a dropdown filter. We would need an additional checkbox for that ("Only cases without a vaccination status"). If something like that is needed, it would need to go into a separate issue.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Ok, then we can go with default filter options and address the additional need when adding the option for multiple category option to a filter.  
I think there is no need to add "Only cases without a vaccination status" for now, the idea I was thinking of is to  add it as a category to all variables that takes NA as default. So better in a different issue.

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske @bernardsilenou 

Should the vaccination-filter-option "Unknown" also map to cases where the vaccination-value is not "Unknown", but `null`? That might be more intuitive to the users

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen "Unknown" and null are semantically different (because "Unknown" bears the information that the field was filled in but could not be answered, while null means that the information is missing completely), so no, they should not be mixed up

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske @bernardsilenou 

Should the Column + Filter Caption still be "Vaccination Status for this disease"? I would prefer a shorter caption, e.g. just "Vaccination". Especially the table would stay much more readable that way, as the column would be more compact.

**Comment by JaquM** [comment]
@DavidBaldsiefen 
I would say just "vaccination" should be enough.

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen See the development specifications. I'd go with "Vaccination Status" because it's a bit more clear than "Vaccination".

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on local environmet
