### ISSUE TITLE
Develop an issuetracker to communitcate issue progress outside of GitHub

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4483]
### Situation Description

A lot of health departments in germany (and stakeholders in general) have a high interest in knowing the current progress of specific features. Right now, the only way to find out the current state of an issue is to check out GitHub, or to contact the HZI. However, GitHub is not very user-friendly for people with no or little experience in software development. It is also problematic that all issues are written in english.

### Feature Description

The issuetracker will use GitHubs API to fetch issue data. The gathered information is then formatted to html, so that it can be displayed on a website (such as sormas-oegd.de)
It will fetch issues based on their label (`de-public`) and then determine progress information based on the issues position in the project boards. The custom label allows the project managment to determine which issues are of special interest, and need to be displayed on their website.
The issue title and description for the website need to be configurable by commenting in the issue or editing the issue description in GitHub. In order not to hinder normal workflow too much, it needs to be possible to make those comments "hidden". It is also necessary that it is configurable who can edit the description and who cannot (based on GitHubs account id).

### Additional Information

For now, this issuetracker is of main interest for german health departments. However, it should be developed with high reusability in mind, so that it can be easily adapted for other languages, websites or even projects.

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen  After fetching issues on main git repo, how would translation be done?

**Comment by DavidBaldsiefen** [comment]
> After fetching issues on main git repo, how would translation be done?

There will be an option to provide a custom description in another language via comment.
For example, if I comment under an issue a section like this:

```
This comment will update the issuetracker-description
# Issuetracker-DE[Issuetracker für SORMAS-Website]
Diese Funktion entwickelt einen Issuetracker für die SORMAS-Website.
# Issuetracker-END
The description is now updated.
```

The generated html would only contain the title `Issuetracker für SORMAS-Website` and description `Diese Funktion entwickelt einen Issuetracker für die SORMAS-Website.`

Most notably, this allows the translation in multiple languages, and also custom content which is catered to the stakeholders interests.

**Comment by DavidBaldsiefen** [comment]
I think this issue can be closed now that the issuetracker is published at https://www.sormas-oegd.de/sormas-software/

If follow-up work needs to be done I would open up another issue.

@markusmann-vg @maxiheyner @kwa20
