### ISSUE TITLE
Change history

### ISSUE THREAD

**Issue by hamedhedayat** [hzi-braunschweig/SORMAS-Project#4485]
for better traceability, it is important to know who did what or when to have the right contact in case of inconsistencies.
And also automatic acquisition of user names who wrote the comments or changed something.

**Comment by MateStrysewske** [comment]
@hamedhedayat Hey! First of all, thanks for submitting this issue. However, please use one of our issue templates and provide all requested information when doing this, and please also give us a bit more details. I don't really know what exactly you're requesting us to do based on your description.

I'll close this issue and would like to ask you to resubmit it with a more extensive description that is according to the issue template.
