### ISSUE TITLE
Information transfer from contact to case

### ISSUE THREAD

**Issue by hamedhedayat** [hzi-braunschweig/SORMAS-Project#4486]
### Situation Description
currently when converting contact to case, new case is created based on contact and comments and information are not transferred from contact to case and comment history should be transferred so that you know what happened to contact earlier.
### Feature Description
comments, information transferred from contact to case when contact is converted to case.

**Comment by Marko-ilmkreis** [comment]
There is the issue #3936 regarding the handle of gerenal informations during converting contacts into cases.
