### ISSUE TITLE
Extend Community Officer Role

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4488]
### Feature Description

- [x] Community officers should see all tasks associated with their community
- [x] Community officers should be able to create tasks which are assigned to superior officers (#4582)
- [x] Community officers should have access to community statistics
- [x] Add Community Officer as default entity

### Additional Information

These points were requested by a user.

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen Some comments please:

> ### Feature Description
> * [ ]  Community officers should see all tasks associated with their community

Since community officers are not responsible for the hospital informants, they would see only their task. The surveillance officer who is responsible for a district is the person who sees all the tasks of every user in the district. 

> * [ ]  Community officers should be able to create tasks which are assigned to superior officers

A similar need was implemented in #4048. I think we should just make this feature generic to all user roles, i.e top-down and bottom-top task assignment  + configuration for it. @MateStrysewske what to you think?

> * [ ]  Community officers should have access to community statistics
> 
Do you mean dashboard or statistics menu?
> ### Additional Information
> These points were requested by a user.

**Comment by MateStrysewske** [comment]
@bernardsilenou Would be fine by me, probably makes sense to not restrict this to region-level users.

**Comment by DavidBaldsiefen** [comment]
> Do you mean dashboard or statistics menu?

statistics, limited to the users community (so basically case numbers)

> A similar need was implemented in #4048. I think we should just make this feature generic to all user roles, i.e top-down and bottom-top task assignment + configuration for it.

Agreed.

> Since community officers are not responsible for the hospital informants, they would see only their task. The surveillance officer who is responsible for a district is the person who sees all the tasks of every user in the district.

I am not completely sure what you mean, but I will check beck with the user who requested this

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen  Since statistics section is only to generate statistics (counts, charts, tables, maps, etc) but not to have access to case-based data, thus all  users can access to statistics outside their region or district.

Is there a reason why the community officer should be blocked from knowing the amount of cases in the neighboring districts?

**Comment by DavidBaldsiefen** [comment]
> Is there a reason why the community officer should be blocked from knowing the amount of cases in the neighboring districts?

No, I will ask the user to make sure. For me it's fine if the CO can see all statistics; At the moment he cannot see any though

**Comment by DavidBaldsiefen** [comment]
> Community officers should see all tasks associated with their community

@bernardsilenou @MateStrysewske 

I need some clarification here. If I understood it correctly, the user requested the possibility to see all tasks in his community, even those assigned to other community-level users in the same community.
Currently, the community officer can only see tasks directly assigned to him.

Is that something we could implement, or would it go against our general task-system?

**Comment by bernardsilenou** [comment]
> > Community officers should see all tasks associated with their community
> 
> @bernardsilenou @MateStrysewske
> 
> I need some clarification here. If I understood it correctly, the user requested the possibility to see all tasks in his community, even those assigned to other community-level users in the same community.
> Currently, the community officer can only see tasks directly assigned to him.
> 
> Is that something we could implement, or would it go against our general task-system?

- I did a test on 1.57.2 and the community informant can see the task assign the them (my task) and task assigned to other community officers in the same community (officers task). If the user is a surveillance officer, then they would see their task and task of other surveillance officers in the same district. 
- I also find out that the community  officer can not see task assigned to surveillance officer  in the district of the community and it works fine.

**Comment by DavidBaldsiefen** [comment]
>    I did a test on 1.57.2 and the community informant can see the task assign the them (my task) and task assigned to other community officers in the same community (officers task). If the user is a surveillance officer, then they would see their task and task of other surveillance officers in the same district.

But should the community officer be able to see tasks assigned to other community officers or community informants in the same community? This sounds like he should be able to see those, too

>    I also find out that the community  officer can not see task assigned to surveillance officer  in the district of the community and it works fine.

Yes, that makes sense

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen 
_But should the community officer be able to see tasks assigned to other community officers or community informants in the same community? This sounds like he should be able to see those, too_
Yes please. I used community informant in my text, its a typing error, this should be community officer.

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of test.sormas.netzlink.com
