### ISSUE TITLE
Prompt for saving data even when no data were changed for EP

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4491]
### Bug Description

In #3014 were this fixed for contacts/cases. But it still appears in event participants. Like in #3014 it only appears if gps-data are entered.

### Steps to Reproduce
1. open an event participant and try to go back to the event directory.
2. make sure that gps-data are entered
2. The windows appears even if there were no data changed.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/108686101-3e8a6980-74f5-11eb-8fe5-c671a5d9f25f.png)

### System Details
* Device: Win 10
* SORMAS version: 1.56.1 and 1.58-snapshot
* Android version/Browser: FF
* Server URL: own instance and https://test-de1.sormas.netzlink.com/

**Comment by syntakker** [comment]
Fixed by PR #4585 for issue #4477.

**Comment by raghupola-vg** [comment]
Tested on version 1.58.0-snapshot on latest deploy and issue is Fixed.

**Comment by syntakker** [comment]
@raghupola-vg the fix has not even been merged :-) However, the circumstances to reproduce the the bug are quite special, see PR #4585 for a description.

**Comment by syntakker** [comment]
Fixed by PR #4585.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas version 1.58.0-snapshot on test.sormas.netzlink.com
