### ISSUE TITLE
Not able to enter a result of a sample

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4493]
### Bug Description

If we enter a sample for an event participant and save it without reporting the result, we will not be able to enter the result later. The field for the final lab result is greyed out:

![grafik](https://user-images.githubusercontent.com/74791118/108692439-e5becf00-74fc-11eb-9b92-da0ed35ebc3e.png)

I tried a second time and generated a test event and in our instance it is reproducible. Also the same user who saved the sample cannot enter the result. The only option is to click on "Refer to another lab" and then enter the result.

On the test server https://test-de1.sormas.netzlink.com/ the error does not occur. I am not sure if the bug has been fixed since 1.56.1 as I have not found any issue to it.

### Steps to Reproduce
1. create an event and an participant
2. enter a sample without result
3. try to enter an result

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  Which version did this occur please?
I could not reproduce it on 1.56.1 also. I

**Comment by Marko-ilmkreis** [comment]
On 1.56.1 - strange thing. I first also thought that something was not entered correctly. I checked, but the desease and the district of the event and person was entered correctly. Allm involved users having the same rights (me: 
![grafik](https://user-images.githubusercontent.com/74791118/108705118-2e7e8400-750d-11eb-983f-8572b7f91a23.png), testuser: 
![grafik](https://user-images.githubusercontent.com/74791118/108705186-4524db00-750d-11eb-9d91-57014e325158.png)

For all users is Covid19 set as desease.

I just entered a new event with a new user. Thse same result.

![grafik](https://user-images.githubusercontent.com/74791118/108705466-acdb2600-750d-11eb-90b2-8eef4427d081.png)
![grafik](https://user-images.githubusercontent.com/74791118/108705476-b06ead00-750d-11eb-8b33-6fc886a82dc3.png)
![grafik](https://user-images.githubusercontent.com/74791118/108705538-c11f2300-750d-11eb-8ff7-71dfe5e79c4a.png)

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis Thanks
@StefanKock @MateStrysewske I suspect this issues and #4471 has the same root cause. Maybe good to look at both together.

**Comment by ChristopherRiedel** [comment]
I cannot reproduce the behavior described. I have tried it both, locally and in multiple test instances. Additionally, I have tried to find out in the code under which circumstances this behavior can occur. I could not find an explanation for the described behavior, according to my estimation there is no place in the code where this field is explicitly set readonly.

**Comment by Marko-ilmkreis** [comment]
@ChristopherRiedel may it help to get an log file from our instance where the error occur?

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis I can't reproduce this as well. Server logs probably won't help because there's not really an "error" that would be thrown somewhere. I suspect this has been fixed by another change in the meantime. I'll move it out of the sprint for now. Can you please get back to us and tell us whether this still happens after the production systems have been updated to a newer version?

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske We are moving next week to ITZ Bund and next week the new release is announced by HZI. After both I will test again and give a feedback. Thanks!

**Comment by VitaliHZI** [comment]
@Marko-ilmkreis is this Bug fixed now?

**Comment by Marko-ilmkreis** [comment]
@VitaliHZI it is fixed now. Thanks for asking.
