### ISSUE TITLE
Showing ct-result 

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4495]
This is a follow-up of #4479 based on the feedback of my colleagues.

### Feature Description

The colleagues asking about showing the ct-value in the person/case/contact/ep, so they can see it on one view and must not enter every result manually.

![grafik](https://user-images.githubusercontent.com/74791118/108695349-7945cf00-7500-11eb-81d3-205c90613661.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis This is technically a duplicate issue of #3890. I would very much appreciate your feedback over there and further specifications if necessary
