### ISSUE TITLE
Bulk Action for sending multiple Events to SurvNet [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#4496]
### Situation Description
Situation Description
Thus far, events can only be sent individually to the SurvNet instance. This is pesky when a lot of data has to be processed and might lead to events not being transmitted because people might forget to send the data.

### Feature Description
- Introduce a bulk action option to send many events to SurvNet at once.
- Show a notification when events are included that do not have a cluster status.

### Additional Information
We already have a bulk action "Send cases" to survnet from cases directory

**Comment by vidi42** [comment]
Waiting for #4348

**Comment by AndyBakcsy-she** [comment]
Validated this ticket on the latest version of sormas 1.58.0-snapshot. 
Survnet converter might not be correctly configured with test-de1.sormas.netzlink.com as at the end of this process an error message was received.

**Comment by vidi42** [comment]
The converter is configured "correctly", however it only supports latest SORMAS stable release (1.57.x). At the moment is not possible to test the integration with the converter on `test-de1`.
