### ISSUE TITLE
Add a bulk action in the task directory to archive multiple tasks

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4501]
### Situation Description 
To date, it is not possible to manually archive tasks 

### Feature Description 
We propose to create a bulk action allowing to: 
- open the task directory in bulk edit mode 
- select several tasks 
- archive the selected tasks.

### Additional Information
@bernardsilenou @ftavin @emond

**Comment by bernardsilenou** [comment]
@carolinverset @MateStrysewske @kwa20 
For tasks related to cases, contact or events, when these entities are archived, then the tasks are also archived. This prevent us from having an active case with an archived task. 
- For general task that are not linked to entities, then it make make sense to archive them through the task repository.
-  Should we limit this feature only to general tasks or to all task types?

**Comment by kwa20** [comment]
@carolinverset @bernardsilenou This is technically a duplicate issue of #3430 I suggest we move further specifications to that issue if that's fine by you?
