### ISSUE TITLE
Event - follow-up of actions: attach documents at the level of the action carried out

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4502]
### Situation Description
To date, users can attach documents at the event level. Users express the need to have this functionality at the action level (event action tab) to facilitate the readability of information.

### Feature Description
Creation of a button in the “event action” tab to attach one or several documents to each action carried out during the investigation.

### Additional Information
@ftavin @bernardsilenou @emond

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @MateStrysewske
Our team will do the dev on this one !

**Comment by ftavin** [comment]
Note : as in #4504 the need is to allow the upload of multiple documents at a time

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on local environment. 
Documents Feature should be enabled in the Feature Configuration Table.
