### ISSUE TITLE
Show sample 

### ISSUE THREAD

**Issue by hamedhedayat** [hzi-braunschweig/SORMAS-Project#4503]
### Feature Description
samples > rapid test must already be displayed on the main page without opening sample as shown in pictures
![schnelltest](https://user-images.githubusercontent.com/51338210/108720881-a8b90380-7521-11eb-93ee-5fab7b6cb9d9.jpg)
Also be PCR test the CT value and sample-id should be shown without opening sample as shown in pictures
![pcr](https://user-images.githubusercontent.com/51338210/108720911-af477b00-7521-11eb-910f-1eaa3dcffe05.jpg)

### Problem Description
It is always necessary to open the sample to see if the sample is fast test or not and also what ct value the sample has and it is much time-consuming

**Comment by kwa20** [comment]
@hamedhedayat Thank you very much for your feedback! This is technically a duplicate issue of #3890. Feel free to comment or give more input over at the existing issue. I will close this issue.
