### ISSUE TITLE
Event - attachment function: attach multiple documents at the same time

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4504]
### Situation Description
To date, it is possible to upload one document at a time in the event part. In order to save time in managing events, users have the need to import several documents at the same time.

### Feature Description
Develop the possibility of selecting several documents in its explorer in order to import all the documents referring to an event at once.

### Additional Information
@bernardsilenou @ftavin @emond

**Comment by bernardsilenou** [comment]
Since the future goal is to have  this feature also for cases and contacts as in #4282
It would be good that we consider adding a meta data while attaching documents to entities. A similar meta data for cases is defined here #4282

**Comment by Candice-Louw** [comment]
Please keep https://github.com/hzi-braunschweig/SORMAS-Project/issues/1771 in mind.

**Comment by ftavin** [comment]
> Since the future goal is to have this feature also for cases and contacts as in #4282
> It would be good that we consider adding a meta data while attaching documents to entities. A similar meta data for cases is defined here #4282

I'm not sure this is the good approach. We have a generic low-level file storage mechanism. If you need some specific additional informations on a specific type of documents (here reports), you can use the generic mechanism and add specific meta-data in a dedicated block but I don't think this is a good idea to add these meta-data to all documents (or to try to add a generic meta-data configuration mechanism which will lead to more complexity)

**Comment by bernardsilenou** [comment]
@ftavin Since the goal of this issue is not the meta data part and the issue on meta data was not also mainly to attach documents, then it implies we focus on this issue for now and think of combining the complete document management latter.
Thanks for the recommendation

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset @MateStrysewske
Our team will do the dev on this one !
