### ISSUE TITLE
[DEMIS Interface] Don't allow simultaneous processing of the same labMessage [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#4509]
### Situation Description

Currently, several users can process the same labMessage simultaneously. This may result in several cases being created from just one labMessage. This shall be avoided.

### Feature Description

Whenever a button for processing a labMessage (including the PROCESS button in the labMessageGrid) is clicked, SORMAS should check whether the labMessage.processed is set to true in the database. If so, a warning popup shall inform the current user that the message has already been processed (in the meantime) and it shall not be possible to continue/save. If a contact/case/eventParticipant was already created by the current user, the deletion of that entity shall be proposed.

### Possible Alternatives

The approach described above has the downside that person duplicates may be created that (as of now) can not be removed. This requires specific (bad) user behavoiur, though, as there already is a person duplicate detection in place. Also, this approach might appear not very user friendly, as some users might start processing the same labMessage, andall but one then have to discard their progress.

An alternative would be to somehow lock the processing of a labMessage once one user starts it. This could for example be done by replacing the labMessage.processed with a status (NOT_PROCESSED, IN_PROGRESS, and PROCESSED) and only allowing labMessages with status NOT_PROCESSED to be processed. It would be necessary to make sure then, that, whenever the processing of a labMessage is cancelled, the status is set back to NOT_PROCESSED. This may be tricky.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot
