### ISSUE TITLE
[CLIMEDO Integration] Comment field in ediary questionnaire not shown in Sormas

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#4512]
### Bug Description
The comments entered in the 'Other problems' text field when completing a questionnaire in Climedo do not get transferred to SORMAS or are not displayed in the Visits view.

### Steps to Reproduce
1. Register a patient in Climedo
2. Go to their Climedo diary page and complete a questionnaire for one of the days, making sure to also add details in the free text field.
3. Go to their SORMAS page, follow-up visits sections and open the external visit previously created

### Expected Behavior
In SORMAS, in the Comments field, the details added in Climedo should be visible.

### Actual Behavior
The Comments field is always empty.

### Additional Information
The comments may be saved in the `visitRemarks` field of the `ExternalVisitDto`. This value does not seem to be used anywhere.

**Comment by Candice-Louw** [comment]
Related: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4161

**Comment by vlad-ciucescu** [comment]
@Candice-Louw 
If I understand correctly, this was determined to be an issue on Climedo side and was already fixed?
This bug was forwarded to me from the Climedo team a few days ago.

**Comment by FredrikSchaeferVitagroup** [comment]
Yes, the comments should be saved in the visitRemarks. In our test system, it shows when transferred trom climedo
![image](https://user-images.githubusercontent.com/67001822/108956835-ac0ed500-7670-11eb-8cc1-425156dc08e4.png)
We should trace back who reported this issue from which instance. Maybe they still use an old climedo version without the fix.

**Comment by FredrikSchaeferVitagroup** [comment]
In the code that ExternalVisitDto.getVisitRemarks is getting used in the [VisitFacadeEjb.saveExternalVisit(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/c57ac9f234ac2d4ca18edac90156c22014b7242f/sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java#L222). It makes perfect sense there and should normally be displayed.

**Comment by vlad-ciucescu** [comment]
In the latest version, the comments on the Climedo side are indeed displayed in the 'Visit remarks' field in SORMAS. The comments field remains empty (which is correct). 
In climedo:
![image](https://user-images.githubusercontent.com/65336966/110444108-4e917400-80c5-11eb-97e5-b1c2af9a338b.png)

In sormas:
![image](https://user-images.githubusercontent.com/65336966/110444044-41748500-80c5-11eb-9bb2-ad12a8135acd.png)

**Comment by AndyBakcsy-she** [comment]
The field has been removed on Climedo's side. 
Marking ticket as obsolete.
