### ISSUE TITLE
[CLIMEDO Integration] Cancelling the follow-up for a person does not update the status to CANCELLED

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#4517]
### Bug Description
It is possible to stop follow-up for a person by going to their case/contact page and clicking on cancel follow-up

### Steps to Reproduce
1. Register a SORMAS person in CLIMEDO. Their status is now `REGISTERED`
2. Go to their page in SORMAS and press on 'Cancel follow-up'

### Expected Behavior
The new status of the person is `CANCELLED`

### Actual Behavior
The status remains `REGISTERED`

**Comment by FredrikSchaeferVitagroup** [comment]
I don't think that is a bug. There are two different status variables involved. One is the FollowUpStatus, the other is the SymptomJournalStatus. REGISTERED is a SymptomJournalStatus related to a Person. It indicates that a Person is registered in a symptom journal.
The followUpStatus relates to a Contact or Case and is about the follow up.
I don't see why the the Person.SymptomJournalStatus should be set to anything new when the follow up of a related Case or Contact is cancelled. The Person remains registered in the symptom journal. It is on the symptom journal to delete an account and then update the SymtpomJournalStatus.

**Comment by vlad-ciucescu** [comment]
It is true, the two things are actually not related
