### ISSUE TITLE
[CLIMEDO Integration] Batch enroll contacts/cases into the external journal

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#4518]
### Situation Description
There is currently no way to enroll more than one person at a time in the external journal. The use has to access each person individually in SORMAS and enroll them.

### Feature Description
Provide an option to enroll multiple persons at the same time. 
Multiple cases/contact should be selectable in their respective directories and then enrolled at the same time using a button.

### Additional Information
**tbd: how are persons with missing or invalid data handled?**

**Comment by Candice-Louw** [comment]
Related/duplicate: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4481
