### ISSUE TITLE
[CLIMEDO Integration] Converting a contact to a case does not update the follow-up duration in Climedo

### ISSUE THREAD

**Issue by vlad-ciucescu** [hzi-braunschweig/SORMAS-Project#4519]
### Bug Description
After converting a confirmed contact to a case, the Climedo patient is not updated with the latest follow-up duration
### Steps to Reproduce
1. Register a person from a contact as a patient in Climedo
2. Make the contact confirmed.
3. Convert the contact to a case.

### Expected Behavior
The follow-up duration in Climedo matches that of the case

### Actual Behavior
The follow-up duration stays the same in Climedo

### Additional Information
Although it may seem to be a problem on Climedo, this can be a problem on the SORMAS side, since we notify Climedo of the update to the follow-up date

**Comment by AndyBakcsy-she** [comment]
Reopening issue as the follw-up duration is not updated on the Climedo side.

**Comment by vlad-ciucescu** [comment]
On SORMAS side the follow up dates are updated correctly when converting from contact to case. The correct date is also returned by the API. The only potential problem on SORMAS side would be if we do not notify Climedo of the update at the right time.
Waiting for Climedo to investigate if the followup date is not updated correctly on their side.

**Comment by StefanKock** [comment]
What's the status on this ticket: Does this block v1.58.0 or not?

**Comment by vlad-ciucescu** [comment]
It doesn't block the release. As I wrote in my other comment, I told the Climedo team about this and should also see if they find something on their side.

**Comment by StefanKock** [comment]
If nothing more needs to be changed on our side and everything is merged, then please close the ticket.

**Comment by DraganMileski** [comment]
@FredrikSchaeferVitagroup guys this is still not working on ga1. I checked Climedo and i find no issue there. If you send us a PUT request on /external-data/:personUUID (and this person has incremented lastFollowUpEndDate) as a result of the conversion from contact -> case then we will just update the last follow up end date in climedo (same as if you just update it for a contact in Sormas and send PUT request to climedo for an update) Please check it out and see where the bug is.

**Comment by markusmann-vg** [comment]
@FredrikSchaeferVitagroup

**Comment by FredrikSchaeferVitagroup** [comment]
This ticket was for sprint 101, so it should remain closed. Follow up ticket is #5155.
