### ISSUE TITLE
It should be possible to document hospitalization information for all medical facility categories

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4520]
### Bug Description
- Hospitalization information can not be documented when facility type = other medical or rehab. However previous hospitalization can be documented.
### Steps to Reproduce
1.
2.

### Expected Behavior
- Activate hospitalization and previous hospitalization when facility category == medical, no matter the facility type. @kwa20 @Candice-Louw  Please check  if this is fine.
### System Details
* Device:
* SORMAS version: 1.57
* Android version/Browser:
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin + national user

**Comment by kwa20** [comment]
@bernardsilenou I don't think that all stays in medical facilities count as hospitalizations. As the name implies, I think this is really reduced to people being in the hospital and therefore fine.

**Comment by bernardsilenou** [comment]
@kwa20 I absolutely agree with you.
Putting my question in other words: is there any of the facility types: rehap, hospital, other medical facility that hospitalization does not occur in? Currently it is only possible for hospital. What about people in retirement homes who got sick.

**Comment by MateStrysewske** [comment]
@bernardsilenou People in retirement homes are not hospitalised. So aren't people in rehab facilities. I would think that hospitalisation is strictly about being admitted to a hospital.

**Comment by bernardsilenou** [comment]
OK, I would close the ticket with the reason that hospitalization is strictly when the facility type is a hospital.
