### ISSUE TITLE
Person directory doesn't show all persons when logged in as Surveillance Supervisor

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4521]
### Bug Description
All persons are not displayed in Person directory when logged in as Surveillance Supervisor

### Steps to Reproduce
1. Login to Sormas as Surveillance Supervisor
2. Access Case directory and pick a case (Ex: Donald)
3. Access Person directory and search for Donald, see if the person is displayed.

### Expected Behavior
All the persons must be displayed in Person directory for Surveillance Supervisor 

### System Details
* Device: 
* SORMAS version: 1.58.0-snapshot
* Android version/Browser: Chrome and Firefox
* Server URL: https://test.sormas.netzlink.com/
* User Role: Surv Sup

### Additional Information
When logged in as National User, all persons are visible.

**Comment by bernardsilenou** [comment]
This is the same for hospital informant on web app.
- The case list of HI contained 17 cases while the person  list for just 2 persons: one case (also found in the case directory), + one event participant. The ep was not reported by the HI, thus should not appear in the person view (bug). The event was in the region + district of the HI but not in the Health facility of the HI.
- condition for a HI to have access to person to show on person view :  
    - person is linked to a case with facility of case === facility of HI  or
    - person is linked to an ep with facility of event == facility of HI  (same region + district is not enough) and
    -  no need to control for reporting user since HI only report entities in their facility

@kwa20 @Candice-Louw  I think we should check this issue with all  the user roles to be sure that  persons shown correspond to the user role.
- In this scenario, I could find a person in the person directory but have pseudonymize access to the ep (nug). We should only find persons liked to entities that the user account has full access or read access.
- Maye we create another issue for this? did not plan to write much .

**Comment by kwa20** [comment]
I could verify the same problem with officer roles. The problem seems to be missing address data. The person then does not appear in the directory even when the case jurisdiction fits the one of the user.

**Comment by MateStrysewske** [comment]
@kwa20 Yes, the person directory so far is filtered based on whether or not the person's home address fits the jurisdiction of the user, which doesn't really make sense. Will be changed for 1.58.0.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of SORMAS
Version: 1.58.0-SNAPSHOT

**Comment by MateStrysewske** [comment]
Extending the event participant jurisdiction filter has the very negative side effect that synchronisation with the mobile app now breaks if there's an event in a different region than the app user's that includes an event participant from the region of the app user.
