### ISSUE TITLE
Investigate the items from the Re-test from the BSI 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#4526]
### Feature Description
We received a new report from the BSI Penetration-Test. There are some medium and minor or even information issues, that we have to take care of. Some of them are partially fixed and need to be checked, what we can do about the missing parts.
With this task, we should deliver a list of new issues and  a clear view of the tasks where we are in charge of and the tasks where e.g. Netzlink is responsible.

### Additional Information
- The document can be provided by @markusmann-vg https://wiki.vitagroup.ag/display/SORMAS/2021-02+PenTest+results
- Vulnerabilities already assessed and sorted out are documented here: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-base/dependencies/check-suppressions.xml

**Comment by StefanKock** [comment]
We could update `resteasy` libs from 3.9.1 to 3.15.1, but it is uncertain if this will still work for `keycloak-admin-client`.

```
<!-- sormas-base/pom.xml -->

        <resteasy.versions>3.15.1.Final</resteasy.versions>

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxb-provider</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
```

@vidi42 what do you think?

**Comment by vidi42** [comment]
@StefanKock 
Since it's just a minor version increase which seem to address mostly bugfixes (https://resteasy.github.io/) I think it's safe to upgrade `resteasy` and don't break the `keycloak-admin-client` which anyway uses `resteasy 3.13.2.Final`

We should also consider upgrading the `keycloak-admin-client` to `12.0.4`

**Comment by StefanKock** [comment]
#4601 and #4707 are the result of this ticket.
