### ISSUE TITLE
Add a feature configuration for superordinate and subordinate grouping of events [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4527]
### Feature Description
- There is a need to group events  in hierarchy (#4239) or in non-hierarchy (#4256)
- It is unlikely that users of an instance may need to have both options activated. Some users do not also need any of them.
### Proposed Change
-  Add a feature configuration for superordinate and subordinate grouping of events
-  The feature configuration fro non-hierarchical grouping would be handled in #4256 
### Development Specifications
* Add a new feature type `EVENT_HIERARCHIES`; server feature, enabled by default, depending on the EVENT_SURVEILLANCE feature type
* If disabled, don't show the "superordinate" and "subordinate" components in the event view, and also remove the superordinateEvent_id column from the import template (ImportFacadeEjb.generateEventImportTemplateFile)

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't really understand what exactly this configuration should handle. Could you describe your request in a bit more detail please?

**Comment by bernardsilenou** [comment]
@MateStrysewske Sorry I did not explain. The suggestion is to have a configuration that remove the feature or icon from the UI because having #4256 and the  current super-ordinate and subordinate clustering may confuse users. 
That is we add a configuration for users to define the type of grouping they want to activate.  Do you have a better solution?

**Comment by MateStrysewske** [comment]
@bernardsilenou No, understood!

**Comment by bernardsilenou** [comment]
Suggested change to do:
- To add an entry in the `featureconfiguration` table called something like EVENT_GROUPS_SUPERORDINATE
- When set to false, this would then hide the ui element and deactivate the feature

**Comment by bernardsilenou** [comment]
@carolinverset

**Comment by carolinverset** [comment]
@bernardsilenou Thank you. This will be more readable for users.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.61.0-snapshot on local environment
