### ISSUE TITLE
Handling of special characters / country specific characters / Umlauts in search

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#4530]
### Problem Description

When searching for a name in the case view, only exact matches are found.
So when searching for Müller, neither Muller nor Mueller would be found, Grossmann does not match with Großmann, Rene does not match with René, Yağmur Çelik does not match Yagmur Celik and some Vietnamese names such as Thường can be irretrievable once entered into the system.

With Demis this problem becomes more salient, as Demis messages often contain names with special characters that have to be described to Latin characters manually.

Also, this has led to situations where our database contained duplicates that were not easily discernible.

### Proposed Change

Country specific characters should be mapped in the search to their Latin character equivalent (As in e.g. https://docs.oracle.com/cd/E29584_01/webhelp/mdex_basicDev/src/rbdv_chars_mapping.html ), with the exceptions of ä, ö, ü, ß being mapped to ae, oe, ue add ss.

### Possible Alternatives

Handling of special characters as wildcards during search might be acceptable (Müller would find Mueller but also Möller).

**Comment by StefanKock** [comment]
Solved by  #4168
