### ISSUE TITLE
Error message misleading when choosing quarantine without prohibition to work

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#4532]
### Bug Description

When selecting quarantine in effect without having selected a value for prohibition of work, an error message pops up stating that validations of dates related to prohibition to work are violated. It is hard to see which fields have to be corrected, since the faulty fields are not even displayed in this setting.

Options are:
1. Support mandatory relations between quarantine and prohibition to work by preselecting values for the relevant fields **or**
2. Make the error message clearer (something like "Select a value for prohibition to work if quarantine is in effect", depending on what the actual relation between both is)

It should also be made sure that the validation is complete, i.e., that the value for prohibition of work is checked in the validation if it is mandatory.

### Steps to Reproduce
1. In a case, select quarantine in effect:
  ![image](https://user-images.githubusercontent.com/5616564/109010601-43474d00-76b0-11eb-971f-239a5ee9a611.png)
2. save. Error message:
  ![image](https://user-images.githubusercontent.com/5616564/109010851-96210480-76b0-11eb-875e-3145a69b7b17.png)

### System Details
* Device: Linux PC
* SORMAS version: 1.55.0, still present in 1.58.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: localhost
* User Role: Contact Supervisor (with admin rights)

**Comment by MateStrysewske** [comment]
Seems to me like this is not a general problem, but that for this specific field, prohibition to work was set to "Yes" earlier, wrong dates were added and then the value from prohibition to work was removed again. In that case, the dates should also be deleted to make sure that there's no validation executed on them. I don't think this is associated with the quarantine fields - at least that would really surprise me.

**Comment by syntakker** [comment]
After a closer look: The issue is caused by the test data generated by the generator in Configuration -> Developer.
From the database for the case in question:
```
|prohibitiontowork|prohibitiontoworkfrom|prohibitiontoworkuntil|
|-----------------|---------------------|----------------------|
|                 |2021-01-04 00:00:00  |2021-01-02 00:00:00   |

```
The error message was indeed as accurate as it could be.

**Comment by syntakker** [comment]
See #4540

**Comment by raghupola-vg** [comment]
re-verified on de test environment and the prohibition to work fields are reset when cleared.

**Comment by StefanKock** [comment]
As stated by @syntakker this was not a software defect but unplausible data, so I removed the bug label.
