### ISSUE TITLE
Unknown sex should map to all other sexes in duplicate detection [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4533]
### Bug Description
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3787 introduced the requirement that sex has to be equal in order for duplicates to be suggested. However, "unknown" is supposed to not conflict actual entries for definite sexes. When a person is created whose sex is unknown, duplicate persons with a known sex are not suggested. This causes a lot more duplicates to be created that can also not be merged retrospectively. 

For the DEMIS interface, this is especially problematic since laboratories often send data with unknown sexes. Already existing subsequent entities like persons, cases or samples can thus also not be reached because they're not suggested.
### Steps to Reproduce
1. Create a case with a person already in the system and set the sex to unknown. Save.
2. Check duplicate detection.

### Expected Behavior
When the sex is unknown, all similar persons should be suggested, no mater what sex they have entered.
### System Details
* Device:
* SORMAS version: 1.56.1/1.57.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de/test1402.sormas-oegd.de
* User Role: admin, national user

### Additional Information
@MartinWahnschaffe @JaquM

**Comment by bernardsilenou** [comment]
@kwa20  Unknown and NA are  not considered since they are both missing data categories. So only male, female, diverse should be used. Hope you agree also?

**Comment by ChristopherRiedel** [comment]
`Predicate sexFilter = cb.or(
			cb.or(cb.isNull(person.get(Person.SEX)), cb.isNull(person2.get(Person.SEX))),
			cb.equal(person.get(Person.SEX), person2.get(Person.SEX)));`
This has to be adjusted (CaseFacadeEjb line 1360ff.)

**Comment by MartinWahnschaffe** [comment]
Looks good.

BTW: #3787 did not introduce that sex has to be equal - this was there before. It just removed the option to by-pass the sex by having no or the same date of birth.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.58.0-SNAPSHOT on test.sormas.netzlink.com

**Comment by kwa20** [comment]
@AndyBakcsy-she Can you tell me how you tested this one? I couldn't verify this on the nightly build systems yet. I've tested on test-de.sormas.netzlink.com and test.sormas.netzlink.com and on both instances the person duplicated detection was skipped. The following is an example issue for test-de:

<img width="545" alt="Screen Shot 2021-03-16 at 2 58 33 PM" src="https://user-images.githubusercontent.com/70317594/111321821-95a0db80-8668-11eb-9c6f-cfe8d3c0cfcd.png">

**Comment by AndyBakcsy-she** [comment]
@kwa20 If I remembered correctly and If I did the correct steps right now, I was able to validate this ticket in the case of 2 Persons with the Unknown Sex. 
Case1 set sex to Male and afterwards edit the case and set the sex to unknown.
Create Case2 from the start with the same First/Last Name, same reporting time, same age and set the Sex to unknown. 
In this case the duplicate detection pop-up is displayed.
![image](https://user-images.githubusercontent.com/70562142/111373170-424c7e80-86a4-11eb-87d3-4d322758dc53.png)

**Comment by JaquM** [comment]
@AndyBakcsy-she 
But duplicate detection should be extended if only one person has specified Unknown and the other has specified Male/Female/Diverse as their Sex.

**Comment by bernardsilenou** [comment]
@AndyBakcsy-she I also did a test on https://test.sormas.netzlink.com/sormas-ui/, and to me the method is not working correctly. I would explain how I think it should be and you can all correct me pls:
- Unknow is not a category of sex (male, female, other)  but a category of missing data. So Unknown and NA are all missing data and should all be mapped to NA.
- The general rule when creating cases or contacts is that, if sex = male, female or other, and this value is available in both the person being created and  all other persons with similar name in the system, then only suggest persons with the same values (male, female or other) as duplicate.
- If sex == NA, Unknown, for the persons that is about to be created, then suggest all persons with similar names as duplicate irrespective of their sex, thus sex is not considered here. This is the current situation with event participant person detection.

- In the figure attached by @AndyBakcsy-she  above, Unknown is considered as a category for sex, ie if there are 2 persons with name john in the system and John1 has a sex == Unknown and John2 has sex = Male, Then during case creation of a case person (John3) with sex == Unknown/ NA, then both John1 and John2 should be suggested as duplicates. If John3 has a sex == Male, then only John2 should be suggested as duplicate

**Comment by MateStrysewske** [comment]
I can confirm that this isn't working properly. I'll reopen it.

**Comment by JonasCir** [comment]
I cannot reproduce with the latest `development` branch. If either case has `sex==UNKNOWN` they are considered by the logic as duplicate if the rest of the criteria is fulfilled. And I cannot select an empty value for sex in the UI as it is a required field.
