### ISSUE TITLE
In Configuration -> Developer: implausible case data generated

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#4540]
### Bug Description
For prohibition to work, implausible data is generated by the test data generator which fails in later validations.
From the data base for one of the generated cases:
```
|prohibitiontowork|prohibitiontoworkfrom|prohibitiontoworkuntil|
|-----------------|---------------------|----------------------|
|                 |2021-01-04 00:00:00  |2021-01-02 00:00:00   |
```

`prohibitiontoworkuntil` cannot be before `prohibitiontoworkfrom`.

See also #4532.

### Steps to Reproduce
1. Go to Configuration -> Developers
2. Generate cases
3. Good luck. Since test data is random, the bug may or may not reproduce

### Expected Behavior
Enforce `prohibitiontoworkuntil` to be on the same day or after `prohibitiontoworkfrom`. If possible, make it consistent with the value of `prohibitiontowork` wether or not dates are generated here.

### System Details
* Device: Linux PC
* SORMAS version: 1.58.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: local
* User Role:

**Comment by DavidBaldsiefen** [comment]
One could probably sneak this in #4391 , seems like an easy fix

**Comment by MateStrysewske** [comment]
Moved to #4391
