### ISSUE TITLE
Extend QuarantineType and FacilityType with additional options [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4549]
Summary and implementation details: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4549#issuecomment-789569437

### Situation Description
For the CH MED V2 (https://github.com/hzi-braunschweig/SORMAS-Project/issues/3570), additional values are requested to be included in the existing MED.

### Feature Description
---
1. For **Case.CovidTestReason.X** enum: [CH only enum]
---

**Existing** -
PRESENCE_OF_SYMPTOMS
OUTBREAK_INVESTIGATION_SCREENING
COHORT_SCREENING
REQUIREMENT_OF_EMPLOYER
DURING_QUARANTINE
AFTER_CONTACT_TRACING
SWISS_COVID_APP_NOTIFICATION
OTHER_REASON

**New addition** (please insert this above/before "OTHER_REASON" in the list) -
var | Title en/de-CH | Description en/de-CH
-- | -- | --
CONVENIENCE_TEST | COVID-19 Convenience Test / COVID-19-Test Convenience | Convenience Test (asymptomatic person: convenience test at the request of the case for a trip, participation in an event etc.) / Convenience Test (asymptomatische Person: auf Antrag des Falles für eine Reise, Teilnahme an einer Veranstaltung usw.)

---
2. For **Case.QuarantineReason.X** enum: [CH only enum]
---

**Existing** -

IDENTIFIED_BY_CONTACT_TRACING
ENTRY_FROM_RISK_AREA
SWISS_COVID_APP_NOTIFICATION
OTHER_REASON

**New addition** (please insert this above/before "SWISS_COVID_APP_NOTIFICATION" in the list) -
var | Title en/de-CH | Description en/de-CH
-- | -- | --
OUTBREAK_INVESTIGATION | Outbreak Investigation / Ausbruchsuntersuchung | 

---
3. For **FacilityType.X** enum: [for all - unless it breaks the SurvNet converter, in which case, only CH please]
---
**New additions** 
Paths:
TypeOfPlace.FACILITY, FacilityTypeGroup.CATERING_OUTLET, FacilityType.BAR
Values: "Bar" (de-*) / "Bar" (en-*)

TypeOfPlace.FACILITY, FacilityTypeGroup.LEISURE_FACILITY, FacilityType.NIGHT_CLUB
Values: "Night club, dance club, discotheque" (en-*) / "Diskothek, Tanzclub, Nachtclub" (de-*)

---
4. Contacts > Contact > Reason for Covid-19 Test [CH only]
(create new dropdown - similar to what is available for Cases)
---

![image](https://user-images.githubusercontent.com/65529128/109187125-e1f7aa80-7791-11eb-9179-d63435561971.png)

var BAG | Title de-CH | Description de-CH | | |
-- | -- | -- | -- | --
test_reason_symptoms | COVID-19-Test Symptome | COVID-19-Test durchgeführt   aufgrund von Symptomen | codelistElement | 1=ja
test_reason_quarantine | COVID-19-Test Quarantäne Empfehlung | COVID-19-Test durchgeführt gemäss Quarantäne Empfehlung | codelistElement | 1=ja
test_reason_quarantine_end | COVID-19-Test Ende der Quarantäne | COVID-19-Test durchgeführt für Ende der Quarantäne | codelistElement | 1=ja
other_test_reason | COVID-19-Test anderer Grund | COVID-19-Test durchgeführt aus anderem Grund | CharacterString |  show free-text

---
5. Cases & Contacts > Epidemiological data > Expositionsdetails (based on feedback from CH BAG on 03.03.2021)
---

Values to be included on the Exposition Mask under **GatheringType**.X enum, for CH-only, please:

BAG var | Title | Value | Show free-text
-- | -- | -- | --
exp_loc_type_less_300 | Öffentliche oder private Veranstaltung <300 Personen | 1=ja | Veranstaltung spezifizieren in exp_loc_type_less_300_detail
exp_loc_type_more_300 | Öffentliche oder private Veranstaltung >300 Personen | 1=ja | Veranstatlung spezifizieren in exp_loc_type_more_300_detail

![image](https://user-images.githubusercontent.com/65529128/109807179-d559d300-7c25-11eb-8f9f-d56d74999708.png)

### Additional Information
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/168

**Comment by MateStrysewske** [comment]
The first part (reason for testing) is outsourced to #4555

**Comment by MateStrysewske** [comment]
4.) will not be done because we'll move that field from the case to the sample, where it can also be used for contacts

**Comment by Candice-Louw** [comment]
@MateStrysewske - outsourcing to #4555 will cause a clash.  This mentioned enum is already existing on CH servers only.  Introducing #4555 would possibly cause double entries/dropdowns on CH configured servers.

**Comment by MateStrysewske** [comment]
Summary:

* Extend the `QuarantineReason` enum with a new value: `OUTBREAK_INVESTIGATION` (caption: "Outbreak Investigation")
* Extend the `FacilityType` enum with two new values:
    * `BAR` (caption: "Bar") - FacilityTypeGroup `CATERING_OUTLET`
    * `NIGHT_CLUB` (caption: "Night club, dance club, discotheque") - FacilityTypeGroup `LEISURE_FACILITY`

**Comment by Candice-Louw** [comment]
@MateStrysewske - last minute feedback from BAG introduced # 5 to this issue that wasn't there previously (apologies):

---
5. Cases & Contacts > Epidemiological data > Expositionsdetails (based on feedback from CH BAG on 03.03.2021)
---


Values to be included on the Exposition Mask under **GatheringType**.X enum, please (for CH only?):

BAG var | Title | Value | Show free-text
-- | -- | -- | --
exp_loc_type_less_300 | Öffentliche oder private Veranstaltung <300 Personen | 1=ja | Veranstaltung spezifizieren in exp_loc_type_less_300_detail
exp_loc_type_more_300 | Öffentliche oder private Veranstaltung >300 Personen | 1=ja | Veranstatlung spezifizieren in exp_loc_type_more_300_detail

**Comment by MateStrysewske** [comment]
@Candice-Louw I'd prefer to add an additional field to exposures that is only active for exposures of type Gathering and that is called "More than 300 attendees" because that allows users to still specify the actual type of gathering (otherwise this information is lost). Do you agree with that change?

**Comment by Candice-Louw** [comment]
Yes, thank you. 👍

**Comment by MateStrysewske** [comment]
Updated the summary

**Comment by raghupola-vg** [comment]
Tested on web and Mobile app on version 1.58.0-snapshot
