### ISSUE TITLE
Add delete option to LabMessages [2]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#4553]
It should be possible to delete the laboratory messages received via the DEMIS-Sormas interface. This is necessary for the organization of messages received erroneously twice.

- Add the mass edit mode to the area and enter delete as selection
- make it possible for user role admin and national user only

@kwa20 @Candice-Louw is there anything you would add?

**Comment by kwa20** [comment]
@JaquM it might also make sense to add an archive option for processed lab message. This could work the same way as for contacts where lab messages are being archived when the case is archived. Adding this as a manual option separately to allow the option to archive independently is debatable.

**Comment by bernardsilenou** [comment]
@kwa20 @JaquM 
- Is this the normal soft delete or permanent?
- Is archiving not enough? if a lab message was  processed and linked to a case in the system, Is there still a need to  have the option to delete the lab message?
- From my understanding, most of the lab messages are not wrong data and would lead to the creation of a case in the system. If this is true, then it would be better to only archive them. Delete means is a wrong data/ error data and would not be considered in any analysis or statistics latter.
- We can add another condition that delete should be possible only if the lab message is not linked to any underrated entity.

**Comment by kwa20** [comment]
@bernardsilenou I think your last condition is a good idea since this mainly includes unprocessed lab messages. I think either way a soft delete option is fine.

**Comment by JaquM** [comment]
@bernardsilenou @kwa20  Messages are also mistakenly sent multiple times, these duplicate messages cause chaos in the administration, which is why an actual deletion would make sense.

**Comment by markusmann-vg** [comment]
Single deletion of a lab message is done in the Detail's view of the Lab Message (bottom left)
Bulk Action to delete will be done as bulk modes in cases/contacts

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot
