### ISSUE TITLE
Filters cannot be applied/doesn't work as expected when bulk edit mode is enabled

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4558]
### Bug Description
When bulk edit mode is enabled, filers do not work as expected.
No response is received when a filter is applied. It works only if user leaves Bulk edit mode.

### Steps to Reproduce
1. Login to Sormas as admin
2. Select Case or contact directory
3. Click on More option present on the top right corner and select Enter Bulk edit mode
4.  Select a disease and try applying the filters. See if the filter is correctly applied.

### Expected Behavior
Filters should be correctly applied even in Bulk edit mode or a proper error information must be displayed to the user

### Actual Behaviour
At the moment when a filter is applied no error is displayed and the correct filter results are also not fetched
 
### System Details
* Device:
* SORMAS version: 1.58.0-snapshot
* Android version/Browser: Chrome and Firefox
* Server URL: test.sormas.netzlink.com
* User Role: admin

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot on test.sormas.netzlink.com environment
