### ISSUE TITLE
SamplesDTO.lab is marked as required 

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#4560]
### Bug Description
Found while working on #4193

SamplesDTO.lab is marked as required in openAPI description however, it is possible to create an inhouse sample with no lab in SORMAS (the column is also nullable in the DB). 

### Steps to Reproduce
1. Create a case/contact
2. Add an inhouse test sample. No lab needs to be specified 

### Expected Behavior
The generated openapi client can retrieve samples from the API. Fix is to remove the annotation from the client

### Screenshots
Nullable in DB
![db](https://user-images.githubusercontent.com/20031875/109323664-01570c00-7854-11eb-8a91-3fc4682cb06f.png)
Emtpy lab in samples overview
![lab](https://user-images.githubusercontent.com/20031875/109323668-01efa280-7854-11eb-9923-5e662a9510a0.png)
How to create it
![new](https://user-images.githubusercontent.com/20031875/109323669-01efa280-7854-11eb-8799-0cc714f93a4b.png)

### System Details
* Device:
* SORMAS version: tested on 1.57 and 1.56.1
* Android version/Browser:
* Server URL:
* User Role: SurvOff

**Comment by bernardsilenou** [comment]
For internal/inhouse sample, the facility of the case is the SamplesDTO.lab when creating samples from ui.
For contacts and ep that do not have a facility, we should just disactivate the inhouse option for them. @MateStrysewske  is this right?

**Comment by MateStrysewske** [comment]
@bernardsilenou Considering that it will soon be possible to buy Covid-19 tests in pharmacies or supermarkets, I don't think we should restrict the usage of inhouse sampling because it will be needed for this scenario.

**Comment by JonasCir** [comment]
Add samples for cases, contacts, and event participants and fetch them with this python script:
```python 
r = requests.get('http://localhost:6080/sormas-rest/samples/all/1', auth=('SurvOff', 'SurvOff'), verify=False)
pprint(r.json())
```
Before this fix only samples of cases were returned, now, all a samples are returned.
