### ISSUE TITLE
[SurvNet Interface] Add "via DEMIS" to pathogen tests [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4562]
### Situation Description
In SurvNet, users need to document whether lab messages came in via DEMIS. Therefore, a field is needed to document this which can be mapped to SurvNet during the export and initial import.
### Feature Description
Add a checkbox "via DEMIS" to pathogen tests.

- This checkbox should be added to pathogen tests AND the sample creation forms in the section where test results can directly be entered.
- When creating pathogen tests through the lab messages (DEMIS) interface, this checkbox should automatically be checked and greyed out to not allow contradictory entries.
- make this field DE only

**Start: Out of scope for the interaction Team**
### Mapping

Map this field to SurvNet in the following way:
**Import:**
- check the box in Sorma, when the corresponding pathogen test to the lab message has "via DEMIS" checked in SurvNet.

**Export:**
- check the "via DEMIS" (NotificationViaDEMIS) field in the respective laboratory report in SurvNet when checked in Sormas.
**End: Out of scope for the interaction Team**

### Additional Information
pathogen tests
<img width="584" alt="Screen Shot 2021-02-26 at 11 13 50 PM" src="https://user-images.githubusercontent.com/70317594/109365409-654bf580-7891-11eb-9883-39b29b9d42fc.png">

sample creation forms with direct test entry
<img width="964" alt="Screen Shot 2021-02-26 at 11 20 10 PM" src="https://user-images.githubusercontent.com/70317594/109365431-6d0b9a00-7891-11eb-81c9-0f49b1e7981a.png">

greyed out when processing lab messages
<img width="268" alt="Screen Shot 2021-02-26 at 11 22 42 PM" src="https://user-images.githubusercontent.com/70317594/109365438-71d04e00-7891-11eb-8338-b839a20c444d.png">

We do not add the field in the UI of the Android App, only in the mobile data model.

**Comment by markusmann-vg** [comment]
via DEMIS => via LIMS
If a LabMessage was sent through S2S it is also checked with => via LIMS

**Comment by FredrikSchaeferVitagroup** [comment]
> via DEMIS => via LIMS
> If a LabMessage was sent through S2S it is also checked with => via LIMS
> 
> Will only be applied to new messages

@kwa20 : does this align with the requirements of the SurvNet export and initial import?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup yes, since we treat our pathogen tests as laboratory reports, this aligns with requirements of the SurvNet export and initial import, meaning that a checked box will lead to a laboratory report in SurvNet where DEMIS is checked and vice versa.

**Comment by raghupola-vg** [comment]
Tested on web app on version 1.58.0-Snapshot and Via LIMS is displayed on Pathogen tests window.
to be verified on Mobile app @AndyBakcsy-she

**Comment by kwa20** [comment]
@markusmann-vg @FredrikSchaeferVitagroup What is the difference between LIMS and DEMIS? I can only find the string for LIMS in crowdin but not for DEMIS and would just translate it as needed.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 `LIMS` stands for `Laboratory Information Management System` and is the term we want to use in SORMAS instead of DEMIS. We should keep the labMessage functionality generic, as countries other than germany want to use it, too.
You could add the term DEMIS in the translation for germany.
