### ISSUE TITLE
[SurvNet Interface] Add checkbox "probable infection environment" to exposures [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4564]
### Situation Description
After consultation with the RKI, the InfectionEnvironmentSetting in SurvNet and the exposures in Sormas differ conceptually from each other by either asking the user to document ALL relevant exposures during the incubation period or only the probable ones, where the user is very sure, that this infection setting led to the infection.
### Feature Description

- Add a checkbox called "probable infection environment" to individual exposures in epiData.
- Add info "mouse overs" to elaborate on the field on the main form as well as the individual checkboxes.
- Make this field and the info mouse over DE only.
- Show the mouse over info next to exposure details known only when the SurvNet interface is configured.
- Show the last sentence in the info box in exposures only when the SurvNet interface is configured.

### Mapping

**Export:**
- When the checkbox is checked, transmit the exposure as an infectionEnvironmentSetting entry to SurvNet.

**Import:**
- During the initial import, all transmitted data from SurvNet need to have the box checked in order to allow resending it via the export.
- if exposures get merged in any way, checking this box should always be favoured over a non-checked box.

### Additional Information
<img width="515" alt="Screen Shot 2021-02-27 at 7 27 41 PM" src="https://user-images.githubusercontent.com/70317594/109396997-c082f400-7934-11eb-8770-859396e9984b.png">
<img width="678" alt="Screen Shot 2021-03-09 at 1 22 25 PM" src="https://user-images.githubusercontent.com/70317594/110470054-ad151d00-80da-11eb-94fb-fce3f1b3a206.png">

**Comment by kwa20** [comment]
@JaquM @ErikMarzHZI One thing we need to consider is how we handle previous entries. Users that have been using Sormas before will not have checked this box and will also not go back to each exposure to decide whether to check it or not.

Options to consider:
- at least one exposure (if any exist) should be checked when sending data to SurvNet. When the case will be sent to SurvNet and exposures exist without one having this box checked, inform the user about the situation and ask, whether they want to proceed. Problem: Sending data via bulk action will basically ask the user to go through all selected cases and check the entries. This is very pesky.

- Decide upon criteria to at least check one existing exposure for existing cases.

**Comment by bernardsilenou** [comment]
@kwa20 @JaquM  
Question pls:
- From my understanding, the exposures user document in SORMAS are probably exposures, ie exposures they think may have lead to the infection or those that the law ask them to document.
- In reality, a person can not tell  which of their different  exposures is associated to the infection, we can only know the associated once after analyzing all the documented exposures.
- What is the issue if all exposures are transferred to SurvNet? Better to have more than less

**Comment by kwa20** [comment]
@bernardsilenou I totally agree with you! I don't quite understand the statement either but what they told us is that they specifically ask their users to only document the probable infection environment (which for them should be merely one entry or maybe two). The way they explained it to us sounds more like they want to document the most probable infection environment rather than all probable ones. After I asked how users should decide what the most probable infection environment was, I didn't get a clear answer. I also think that if the case person had 5 close contacts to source cases, how does anyone decide what the most probable of them all was...

**Comment by bernardsilenou** [comment]
@kwa20 
Based on the comments in the meeting today, I think the point lacking are the following: 
- only one exposure should be possible to set as probable infection environment. Users can change to another one when creating a new exposure with  pop up informing them that this is the selected option and old one would be unchecked.
- If there is only one exposure, then set probable infection environment == true
- When a previously probable infection environment is deleted, then set the other one left to true, If more than one is left, then user has to chose the one to set to true
-  add an icon o new column on the list of exposures to identify the probable one. On  this table, user would also be able to check another exposure as probable
![image](https://user-images.githubusercontent.com/12996724/109648187-9ca0f780-7b5a-11eb-898f-0094d2033d50.png)

**Comment by Candice-Louw** [comment]
@JaquM - if all previously existing exposures are deleted (for whatever reason) in SORMAS, should "nicht ermittelbar" be transmitted to SurvNet, or should all the entries be deleted entirely (set to "nicht erhoben"?)

![image](https://user-images.githubusercontent.com/65529128/110220940-45d44e80-7ec9-11eb-87e5-c536a5126c6c.png)

**Comment by JaquM** [comment]
@Candice-Louw - If something is deleted in Sormas it should also be deleted completely in SurvNet.

**Comment by Candice-Louw** [comment]
Last imput:
SurvNet leaves it for the local health worker to consider an exposure to be probable. Yet scientifically and epidemiologically such an assessment cannot be done without relying on epidemiological comparative analysis (e.g. case control, cohort, case series studies) and will tend to over-weight those exposures that for whatever reason happen to be most discussed at a point time, but that does not mean they are most probably the source) For this reason SORMAS will maintain the possibility to document any exposure, regardless whether it is considered probable or not. As recent developments will add the upload of so called contact or exposure documentation apps, this SORMAS approach will gain even more justification. For this reason The SORMAS concept needs to be translated to the reduced SurvNet concept. In case SORMAS has more exposures , during which their status of being probable or not was no (yet) documented, it is better to err on the side of additional exposures added to SurvNet rather than on the side of unnecessarily retaining exposures to the exportation process to SurvNet.

**Comment by MateStrysewske** [comment]
Updated implementation details based on Bernard's comment:

* Add a new field to exposures: `probableInfectionEnvironment` (boolean) - only for German instances
* Add the field as a checkbox to the exposure forms below UUID and reporting user
    * Add an info icon next to the field with the following text: `"Probable infection environment" should be checked if you are sure that this exposure was the most probable infection environment for this case. Only one exposure can be marked as the probable infection environment at the same time, and that exposure will be transmitted to SurvNet.`
    * If the user sets an exposure as the probable infection environment (PIE) and saves it, check whether any of the other exposures are already set as the PIE; if so, display a popup with the following text: `This case already contains an exposure that has been marked as the probable infection environment. Setting this exposure as the probable infection environment will remoe that mark from the other exposure. Do you want to set this exposure as the probable infection environment of the case?`; if 'Yes', save as usual and set `probableInfectionEnvironment` at the other exposure to false and save that one as well; if 'No', set `probableInfectionEnvironment` of the current exposure to false and continue the saving process
* Add a checkmark icon to the exposure table, next to the type of activity, for the exposure that has been set as the PIE, and display the type of activity in bold (similar to how it's done for risk area already)

@bernardsilenou I think the additional processes that you've specified aren't really necessary. If there's only one exposure for a case in SORMAS, the SurvNet converter should just transmit it to SurvNet, no matter whether it has been marked as the probable infection environment or not.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of 1.58.0-snapshot on test-de.sormas.netzlink.com
