### ISSUE TITLE
[Event Groups] Event directory impacts

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#4570]
### Situation Description

This issue is part of a larger package, the management of Event Groups, which was first discussed on the issue #4256.

It finally appeared that the feature is to complex to be made with a unique issue that's why it will finally be done through 4 issues :
- #4571  : [Event Groups] Event group screen
- #4570  : [Event Groups] Event directory impacts (this issue)
- #4572  : [Event Groups] Event screen impacts
- #4573  : [Event Groups] Event groups view

**Note : the global functionnality should be (de)activable using a unique parameter.**

**User rights**
When a user tries to add/remove event(s) to a group (creation of the group/modification of the group)
- if the user is at national level: always ok
- if the user is at regional level: blocked with an error message if one of the events to add/remove is not from its region

When a user tries to act on a group of events (change the title, delete it or archive it)
- if the user is at national level: always ok
- if the user is at regional level: only ok if all the events of the group are from his region

### Feature Description

This issue lists the changes requested on the events view of the event directory. The actions view should not be modified.

From the events directory we want to be able to create a group :
- in bulk-edit mode
- the relevant events will be selected using the checkboxes
- a new bulk-action named "Group" will be added
- this action opens a popup which asks for the title of the group (+ validate / cancel buttons)
- after creation of the group the user is not redirected but the directory is refreshed

On the directory we add a new column:
- empty if event is not part of any group
- ID of the group created most recently (technical date of creation of the group) with redirection to the group's screen on click ( #4571 )
- an optional asterisk behind the ID indicates that this event is part of other groups
- a tooltip when hovering over the ID indicates the group title

We also add a filter on the group
- restricts the lines on entering an ID or a keyword from the title of the group
- if an event has several groups, it is kept if at least one of its groups matches the filter criteria (not necessarily the group displayed in the column)

Of course the group ID column is also present in the exports.

@bernardsilenou @carolinverset @MateStrysewske

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Please can you have a look at these four issues if all is fine by you. They are planned for next sprint.

**Comment by MateStrysewske** [comment]
@bernardsilenou @ftavin All four issues look fine to me, no objections!

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
