### ISSUE TITLE
[Event Groups] Event screen impacts

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#4572]
### Situation Description

This issue is part of a larger package, the management of Event Groups, which was first discussed on the issue #4256.

It finally appeared that the feature is to complex to be made with a unique issue that's why it will finally be done through 4 issues :
- #4571  : [Event Groups] Event group screen
- #4570  : [Event Groups] Event directory impacts
- #4572  : [Event Groups] Event screen impacts (this issue)
- #4573  : [Event Groups] Event groups view

**Note : the global functionnality should be (de)activable using a unique parameter.**

**User rights**
When a user tries to add/remove event(s) to a group (creation of the group/modification of the group)
- if the user is at national level: always ok
- if the user is at regional level: blocked with an error message if one of the events to add/remove is not from its region

When a user tries to act on a group of events (change the title, delete it or archive it)
- if the user is at national level: always ok
- if the user is at regional level: only ok if all the events of the group are from his region

### Feature Description

This issue lists the changes requested on the event screen.

A block named "Event Groups" will be added on the right which lists the different groups and indicates for each:
- title
- group ID with redirection to the group screen on click ( #4571 )
- number of events in the group
- button to remove the event from this group
- button to access the events directory (event view) filtered on the group ID

The block must also have a button to attach the event to an existing group (button with pop-up for selecting an event using a search by ID or keyword)

@bernardsilenou @carolinverset @MateStrysewske

**Comment by kwa20** [comment]
@ftavin Just a minor question: 

> - button to access the events directory (event view) filtered on the group ID

Wouldn't that have the same effect as just opening the group itself?

**Comment by bernardsilenou** [comment]
@kwa20  It would not be the same because while in a group, you only see information about the group: id; tittle number of event 
 , etc which are missing on the event directory

**Comment by ftavin** [comment]
@kwa20 the event directory provides more information and actions concerning the events. We think both are interesting.
