### ISSUE TITLE
[Event Groups] Event groups view

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#4573]
### Situation Description

This issue is part of a larger package, the management of Event Groups, which was first discussed on the issue #4256.

It finally appeared that the feature is to complex to be made with a unique issue that's why it will finally be done through 4 issues :
- #4571  : [Event Groups] Event group screen
- #4570  : [Event Groups] Event directory impacts
- #4572  : [Event Groups] Event screen impacts
- #4573  : [Event Groups] Event groups view  (this issue)

**Note : the global functionnality should be (de)activable using a unique parameter.**

**User rights**
When a user tries to add/remove event(s) to a group (creation of the group/modification of the group)
- if the user is at national level: always ok
- if the user is at regional level: blocked with an error message if one of the events to add/remove is not from its region

When a user tries to act on a group of events (change the title, delete it or archive it)
- if the user is at national level: always ok
- if the user is at regional level: only ok if all the events of the group are from his region

### Feature Description

This issue exposes the creation of a new view named "Groups" on the event directory (in addition to the events view and the actions view)

In this view, each row corresponds to a group.
The desired columns are:
- group ID with redirection to the group screen on click ( #4571 )
- group title
- number of events in the group

The desired filters are:
- group title ID or keyword
- region / county / city / date / ID / keyword from the title (data in events: we keep the group if at least one of its events matches the filter)

Basic export only (= displayed columns)

@bernardsilenou @carolinverset @MateStrysewske

**Comment by bernardsilenou** [comment]
@ftavin Thanks for the detailed and professional refinement.
One question is the the user who has full assess to the group data.  Since the group may contain events from different jurisdictions.
Maybe you already explained it in one of the issues.
@carolinverset should we allow grouping of events from different regions?
We can activate this feature only for national users OR restrict that only events from the same regions can be grouped and allow the module for surveillance supervisors also.

**Comment by carolinverset** [comment]
Yes, it is important to be able to link the events of two or more different regions (eg: a passenger having chained several flights).

We can apply the same reasoning as for attaching cases from another region to an event:
- only the national user will be able to link the events of different regions.
- the surveillance supervisor + contact supervisor can link events within the same region

@ftavin @bernardsilenou @emond-fuseau
