### ISSUE TITLE
IterableHelper.executeBatched used without batching the input list

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#4580]
### Bug Description

Overlooked in #3253: `CaseFacadeEjb.countCasesWithMissingContactInformation` uses `IterableHelper.executeBatched` but the lambda still uses the method parameter `caseUuids`. This will fail if `caseUuids` exceed 32767.

### Expected Behavior

Use the lambda parameter `e`, rename it to `batchedUuids`

### System Details
* SORMAS version: 1.57.0 and earlier

**Comment by StefanKock** [comment]
I stumbled by chance over this one, maybe there other similar bugs.

**Comment by syntakker** [comment]
There were some more sketchy usages. Especially this one, which duplicates the result list if it hits the margin between batch size (32000) and parameter limit (32767):

```java
			IterableHelper.executeBatched(
				personUuids,
				ModelConstants.PARAMETER_LIMIT,
				batchedPersonUuids -> eventParticipants.addAll(getEventParticipantsByPersonUuids(personUuids)));
```
