### ISSUE TITLE
Allow all user roles to assign tasks to users with a higher jurisdiction

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4582]
### Feature Description

As implemented with #4048 for regional->national users, allow community-level users to also assign tasks to regional-level users.

### Additional Information

- Use the FeatureType `ASSIGN_TASKS_TO_HIGHER_LEVEL`
- Check only for users Jurisdiction Level, **not** for specific roles. Because of the upcoming user role rework, this feature should be as generic as possible

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Is it necessary that community-level users can directly assign tasks to region-level users, or would it be fine if they could assign them to district-level users (who then in turn would be allowed to assign tasks to region-level users)? Because if we do it that way, we can implement it generically as in that every user is allowed to assign tasks to users of the jurisdiction level above them.

**Comment by DavidBaldsiefen** [comment]
> @DavidBaldsiefen Is it necessary that community-level users can directly assign tasks to region-level users, or would it be fine if they could assign them to district-level users (who then in turn would be allowed to assign tasks to region-level users)? Because if we do it that way, we can implement it generically as in that every user is allowed to assign tasks to users of the jurisdiction level above them.

I think that would be fine and makes sense. But I van check back with the user who requested this @stephan-2

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske Do you think it makes sense to limit the users of the next-higher jurisdiction level to those whose jurisdiction also "contains" my jurisdiction? E.g. only district-users when their district also contains my community.

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen That sounds like a very good idea, yes!

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of 1.58.0-snapshot on test.sormas.netzlink.com
