### ISSUE TITLE
Improve exposure table display [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4589]
### Feature Description
(cases/contacts) > epiData > exposures
### Problem Description
When exposures are entered in the table, the display of entries on the form do not provide detailed information. Therefore, users usually have to open the individual exposures to really understand the content.

**Current display:**
<img width="724" alt="Screen Shot 2021-03-02 at 2 38 53 PM" src="https://user-images.githubusercontent.com/70317594/109660775-8a7a8580-7b69-11eb-84b6-62c510dccf55.png">
The description shows what has been entered in the respective exposure.
### Proposed Change

- Display the lower hierarchical entries in the overview table if available. This should include:
    - "Type of activity" (gatheringDetails > gatheringType > exposureType, habitationDetails > habitationType > exposureType, exposureTypeDetails > exposureType). 
    - "type of place" 
        -  Facility (facility, facilityDetails > facilityType > typeOfPlace). When facility is available also keep the facilityType displayed.
        - Means of transport (Values, MeansOfTransportDetails > "Means of transport")
        - (typeOfPlaceDetails > "other")
- In the case of animal contacts, put the type of animal in parentheses after animal contact since the type of animal by itself does not make sense as a type of activity.
- Add "Role" (exposureRole) to the overview table.

**Improved display:**
<img width="780" alt="Screen Shot 2021-03-02 at 3 13 34 PM" src="https://user-images.githubusercontent.com/70317594/109661126-ef35e000-7b69-11eb-84a8-3dfcc2d8db5c.png">
The description shows what has been entered in the respective exposure.

**Comment by kwa20** [comment]
@JaquM @bernardsilenou @maxiheyner

**Comment by bernardsilenou** [comment]
@kay :+1:  as long as there is space, I think we should add

**Comment by maxiheyner** [comment]
@kwa20 looks complete, thank you.

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
