### ISSUE TITLE
Add Stay in ICU fields in previous hospitalizations [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4591]
### Bug Description
#4187 introduced additional Stay in ICU fields in previous hospitalizations. When entering previous hospitalizations, stay in ICU fields are not enabled.
### Steps to Reproduce
1. Go to cases. Go to hospitalizations.
2. Enter a previous hospitalization.

### Expected Behaviour
Stay in ICU fields should be enabled for previous hospitalizations.

**SPECIFICS:**
Cases > open case > Hospitalization tab > Previous Hospitalizations section > New Entry
Add "Stay in the intensive care unit?" as:
Yes/No/Unknown | If yes, show --> start date selector, end date selector

Related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/1830 , as developed by @stefanspiska, but now applied to the new entries for "previous hospitalization" list.

![image](https://user-images.githubusercontent.com/65529128/110211389-aa29ea80-7e96-11eb-90fe-7f51c7687928.png)

### Screenshots
<img width="450" alt="Screen Shot 2021-03-02 at 6 09 49 PM" src="https://user-images.githubusercontent.com/70317594/109687270-5f049480-7b83-11eb-96ce-920d51ba7d46.png">

### System Details
* Device:
* SORMAS version: 1.57.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/31

**Comment by AndyBakcsy-she** [comment]
Verified on the latest version of Sormas 1.58.0-snapshot on test.sormas.netzlink.com
