### ISSUE TITLE
Add additional fields to hospitalization [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4593]
### Situation Description
Thus far, some fields are available on the hospitalization form but not in the previous hospitalizations and vice versa. These fields are not only required for the SurvNet interface but also make sense to add in the respective section to provide consistency between current and previous hospitalizations and prevent data loss. 
### Feature Description

- Add a description field to hospitalization. This field should be mapped to the description field in previous hospitalization when the case is being transferred.
- Add "Was patient admitted at the facility as an inpatient?" boolean field to previous hospitalizations. Thus far, this entry is lost when the case is transferred and users cannot infer whether the previous hospitalization was outpatient or inpatient.
- Add date of isolation to previous hospitalizations.
- make sure that the new fields are filled based on the current hospitalization when a case is transferred

### Additional Information
<img width="697" alt="Screen Shot 2021-03-02 at 9 57 53 PM" src="https://user-images.githubusercontent.com/70317594/109716285-f75f4100-7ba4-11eb-95b6-5db5add213ae.png">
<img width="399" alt="Screen Shot 2021-03-11 at 9 40 52 AM" src="https://user-images.githubusercontent.com/70317594/110759465-eb7f1900-824d-11eb-8e97-7fc1270a2e2c.png">

**Comment by kwa20** [comment]
@JaquM

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe We should probably think about getting rid of the previous hospitalizations completely and instead using full hospitalizations in the context of this issue.

**Comment by MartinWahnschaffe** [comment]
Yes, I like that idea. This would mean the list of previous hospitalizations would no longer be a part of the hospitalization but instead of the case. Maybe we can even find a way to only have a list of hospitalizations and leave it to the UI to distinguish between a current hospitalization and previous ones.

**Comment by bernardsilenou** [comment]
Good point https://github.com/hzi-braunschweig/SORMAS-Project/issues/4593#issuecomment-919823308
- We can distinguish the current from previous hospitalization by comparing most relevant date with date of visit/ admission. 
- Sort the list according to date date of visit/ admission with  recent dates at the top
