### ISSUE TITLE
Person directory breaks when person is linked to an event without a disease

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4596]
### Steps to Reproduce
1.  Create an event participant in a event with a disease B
2. Add the same person in another event with disease B
3. Look for person is person in person directory, all ok
4. set disease to one of the events to NA+ go back to person directory and open the person form. == person linked to nothing
5. This also happened when person is added to an event with no disease

### Expected Behavior
- Person directory should confider disease == NA and show 
- Person directory should should not show persons without associated links

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/109742430-4b7f1b00-7bcf-11eb-8e70-631ab6660bf4.png)

When person is linked to a contact + later linked to an event part with our a disease, then whole event Icon disappear.
![image](https://user-images.githubusercontent.com/12996724/109744538-c433a680-7bd2-11eb-9a91-7e0ea7953fe1.png)

### System Details
* Device:
* SORMAS version:  1.57
* Android version/Browser: web
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/#!persons/data/SKJWBN-6LRJTQ-PXYJLA-7K5R2D64
* User Role: National user + admin

**Comment by bernardsilenou** [comment]
@MateStrysewske havign event without a disease seem to be breaking methods in the system. Maybe we enforce the disease of the event as  suggested in another issue ?
- Users can choose `Not Yet Defined` if disease is unknown
- At server end, we add `Not Yet Defined` in addition to `COVID-19` for instances that uses sormas for covid only

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou I would additionally also suggest to show persons without links in the directory as well.

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't think that events without a disease are a good option. We should just make sure that we sort out the problems that are associated with them.

**Comment by Marko-ilmkreis** [comment]
I can only repeat myself and suggest that the field desease becomes a mandatory field to fill in. Ideally, I would also preset it with Covid19 if no other disease is activated on the server. Any field that users don't have to fill in helps us more than voluntary fields ;-)
