### ISSUE TITLE
Do not considering deleted event participants when filtering events 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4597]
### Steps to Reproduce
1. Create person1 as ep in event 1 and event 2
2. Search for person in event directory == OK
3. Now open each event + ep and delete the person1
4. Search for person in event directory, you still find the events but person is not in ep

### Expected Behavior
Filter should only consider events with evet_participant.deleted   == "false"
### System Details
* Device:
* SORMAS version: 
* Android version/Browser: 1.57
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/#!events/
* User Role: admin + national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.58.0-snapshot on local environment
