### ISSUE TITLE
Users on district level and below don't receive task notification mails

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4598]
### Bug Description
Email notification does not work when a surveillance supervisor assigns a task to a surveillance officer

### Steps to Reproduce
1. Create two profiles: one = surveillance supervisor; the other = surveillance officer
2. Check that the email addresses are correctly entered in "'users"
3. Log in with the surveillance supervisor profile
4. Open an event and respectively assign a task to the two created people (surveillance supervisor and surveillance officer)
5. Only one notification is sent: the one assigned to the surveillance supervisor

### Expected Behavior
Two notifications should be received

### System Details
* Device:
* SORMAS version: 1.56.1
* Android version/Browser:
* Server URL: https://sormas.test.esante-bfc.fr/ (test environnement région Bourgogne Franche Comté)
* User Role: admin, surveillance supervisor, contact supervisor

### Additional Information
@bernardsilenou @emond-fuseau @ftavin

**Comment by MateStrysewske** [comment]
@carolinverset Is it possible that one of the tasks (the one for which no notification was sent) had an earlier start date?

**Comment by carolinverset** [comment]
@MateStrysewske 
Both tasks have the same starting date.
I created them afterwards.

**Comment by DavidBaldsiefen** [comment]
The Problem is this check in `TaskFacadeEjb`, which is done on new/due tasks before sending a notification:

```java
if (task.getAssigneeUser() != null && task.getAssigneeUser().isSupervisor() || task.getAssigneeUser().getUserRoles().contains(UserRole.`NATIONAL_USER))
```

When I remove the supervisorcheck it works fine. @MateStrysewske Do you know why this check is here?

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Can't recall that anymore, no. @bernardsilenou Any idea?

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen No idea also

**Comment by MartinWahnschaffe** [comment]
The reason was that officers and informants have traditionally been using the Android app and receive notifications directly via the app.
@bernardsilenou If we enable emails and SMS now for all users, this would affect Nigeria. Do you know whether they are using SMS notifications at all?

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe @bernardsilenou Maybe we need new user properties that determine whether or not the user receives sms or email notifications? I'm not sure whether just changing this is a good idea because of what Martin has mentioned.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe @MateStrysewske 
Thanks for this points,
This is not a problem for Nigeria if users get notification by email and through the application. Many of the users who uses the mobile app do not even have or check emails regularly.

I Agree with @MateStrysewske that we should add a property but one for sms and another for email, based on the reason that not all users have email and sms. 

Some supervisors also mentioned that even if they have emails, they may also like to get notifications by sms for immediate action.

**Comment by MateStrysewske** [comment]
Okay, if it's not a problem for Nigeria, we can go with the solution implemented by David for now and then add the properties suggested by me at a later point in time. Is that fine for you @bernardsilenou?
