### ISSUE TITLE
Adding additional tests to Samples breaks the Mobile app Synchronization

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4603]
### Bug Description
When an entry is made for addition test in Samples which are created for event participant, the Mobile app Synchronization fails.
 
### Steps to Reproduce
1. Login to Sormas web app as admin
2. Access Samples Directory and Pick a Sample which has Associated Event Participant.
3. On the right side, add a test result under Additional Tests box/view
4. On the Mobile app refresh in order to synchronize and see if the sync is successful.

### Expected Behavior
Mobile app Synchronization should not fail when additional tests are added to the event participant samples  

### Screenshots
![Sync Fails](https://user-images.githubusercontent.com/62763628/109784724-a6366800-7c0b-11eb-9362-c6064f725523.png)
![Additional test for Event Participant Samples](https://user-images.githubusercontent.com/62763628/109784735-a898c200-7c0b-11eb-93ab-f2067e9a5eb6.PNG)

### System Details
* Device:
* SORMAS version: 1.58.0-snapshot
* Android version/Browser: Chrome and Firefox. Android 10
* Server URL: test.sormas.netzlink.com
* User Role: Admin on Web app and Surveillance Officer on Mobile app

### Additional Information
When the Additional test result is deleted, the sync works fine.
Issue observed only when the additional test results is added to Event Participant samples and not to any other samples

**Comment by MateStrysewske** [comment]
#4300 is very likely related to this and will be the issue that we'll use - I'll link this one for further reference and additional information.
