### ISSUE TITLE
Translate captions in data dictionary depending on the user language setting [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4607]
### Situation Description
Thus far, Sormas only provides the data dictionary in the english language. However, users might need the data dictionary captions in another languages to maximize the usability.
### Feature Description
Translate the captions in the data dictionary depending on the user language setting. 

### Additional Information
Examples in data dictionary:
<img width="747" alt="Screen Shot 2021-03-03 at 1 29 33 PM" src="https://user-images.githubusercontent.com/70317594/109806262-cb83a000-7c24-11eb-933d-05d3ce67c4cb.png">
<img width="620" alt="Screen Shot 2021-03-03 at 1 30 05 PM" src="https://user-images.githubusercontent.com/70317594/109806275-cfafbd80-7c24-11eb-8af1-2b4215dadffc.png">

### Development Specifications
* Create new `InfoFacade` **(name should be discussed)** and `InfoFacadeEjb` classes
* Add a method called `generateDataDictionary` to the new facade that returns a File, can take an optional file path and move the generation code from the `DataDictionaryGenerator` class in the test package; the test class should call the facade method with the file path that is currently used there instead; calling this method with an empty file path should create a file in the temp directory with the name "data_dictionary_{random_long}"
* The new method should generate the data dictionary based on the user language (or in default English if it's called from the test class)
* In the AboutView in the UI, don't retrieve the default data dictionary, but call the `generateDataDictionary` method with an empty file path and let the user download/open the returned file instead

**Comment by MateStrysewske** [comment]
@kwa20 This is a significant change because if I'm not mistaken, the data dictionary is currently generated during the build process, so providing it with translations is not trivial. Just mentioning it for further reference.

**Comment by bernardsilenou** [comment]
@kwa20 Such a change is risky because if the translations is wrong or incomplete in the users language, then the data entry would be wrong. 
The person doing the import should learn and work with the English captions in my opinion.

**Comment by RazvanHodisan** [comment]
Verified on Version: 1.61.0-SNAPSHOT, https://test.sormas.netzlink.com/

**Comment by vidi42** [comment]
Found an issue with Data Dictionary downloaded in French.
![image](https://user-images.githubusercontent.com/3462897/121906939-4421ee80-cd34-11eb-96e5-cf4fb0656f1c.png)

Seems that Excel has an issue with table names which contain special characters:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" ref="A1:K11" displayName="Participant_à_l'événement" name="Participant_à_l'événement" id="156">
   <autoFilter />
   <tableColumns count="11">
      <tableColumn name="Champ" id="1" />
      <tableColumn name="Type" id="2" />
      <tableColumn name="Protection des données" id="3" />
      <tableColumn name="Légende" id="4" />
      <tableColumn name="Description" id="5" />
      <tableColumn name="Requis" id="6" />
      <tableColumn name="Nouvelle maladie" id="7" />
      <tableColumn name="Maladies" id="8" />
      <tableColumn name="Épidémies" id="9" />
      <tableColumn name="Pays ignorés" id="10" />
      <tableColumn name="Pays exclusifs" id="11" />
   </tableColumns>
   <tableStyleInfo name="TableStyleLight1" showColumnStripes="false" showRowStripes="true" showLastColumn="false" showFirstColumn="false" />
</table>
```

SORMAS takes care of whitespaces when building the Excel file and replaces them with `_`.
The same should be done for punctuation characters as well since when building an Excel file by hand that's the same approach that Excel applies in the background.

**Comment by RazvanHodisan** [comment]
Verified on Version: 1.61.0-SNAPSHOT, https://test.sormas.netzlink.com/
