### ISSUE TITLE
[Angular] Case page

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4608]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/v8RJ4M8
German system: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/JnJybpG

- The section including: Case data, Additional information, etc - represents links (anchors to the form below)
- The separation between section is represented by the spacing (48) between form elements
- NOTE: Please make sure that all of the fields present in the form abide by the rules of the previous implementation (consult test site for more information)
- Make sure to include all of the existing fields

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by cristinacoza** [comment]
UI/UX review done
