### ISSUE TITLE
[Angular] Notifications module

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4610]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/ZOVy1RG
- This module should include only the general applied notifications. If we deal with specific modals/notifications these will be treated separately 
NOTE: When hitting "Esc" the modals should be closed

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by danielrus** [comment]
Waiting for project structure refactor to see if additional changes are needed.

**Comment by danielrus** [comment]
Integrated with new structure. Done.
