### ISSUE TITLE
[Angular] Case person tab

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4613]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/JnAk81b
German system: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/paK59ao

- Address "Show more" should expand the list to show multiple items
- @cristinacoza , please update the design for the address cards as to include a delete action ("X"). Deleting a card needs to be confirm via a dialog box.
- NOTE: Please make sure that all of the fields present in the form abide by the rules of the previous implementation (consult test site for more information)
- Make sure to include all of the existing fields

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by cristinacoza** [comment]
UI/UX Review done

**Comment by cristinacoza** [comment]
UI/UX review done
