### ISSUE TITLE
[Angular] Case person tab Contact modal [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4614]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/4agAA5d
- The same modal is used for both "Add" and "Edit", of course changing the title from "Add" to "Edit" and prepopullating the fields while on edit. 

Note: This will handle just the form without the coordinates (geo-location functionality).
Note: Add a uniques identifier to the dynamic form ("Save / Discard").

### Possible Alternatives
N/A
### Additional Information
N/A

### Story Points: 5 POINTS

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good (there is a minor styling issues for the contact card that will be added to UI bug list)

**Comment by RobertoDascalu** [comment]
after adding multiple addresses or contacts ,when you try to close 1 address or contact ,all addresses and contacts get closed
![image](https://user-images.githubusercontent.com/102517557/160420913-05399d96-52cd-4a37-bda5-25fc17fb9949.png)
![image](https://user-images.githubusercontent.com/102517557/160421042-8b97603e-fa2c-4ffe-aab2-e3bafb4f2191.png)

**Comment by RobertoDascalu** [comment]
Testing done - issue fixed
