### ISSUE TITLE
[Angular][Backend] Investigate current "Save" flow on Sormas

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4615]
### Situation Description
- We need to understand how the current save is performed on Sormas in view of adding the save functionality to the new implementation.
### Feature Description
- Investigate how "save" for a case is performed for the current Sormas implementation
- Investigate if we are dealing with a "master" case entity, or rather, multiple entities 

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by marius2301** [comment]
In the current implementation  there is not possibility to update the object partially, the whole object is saved.  After the discussion we had with Mate, the idea is that we can implement, on the backend, a patch (partial update) if there is really benefic for the front end. We should decide in the next meeting
