### ISSUE TITLE
Add the user who assigned the task to task entity [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4621]
### Situation Description
- users get task but do not know the person who assigned the task
### Feature Description
- Beside associated entity, show in read only mode the `Assigned by` user
- Add a filter on the task directory for this variable
### Development Specifications
* When saving a task and the assigned user has been changed, set the current user as assignedBy (in`TaskFacadeEjb#saveCase` and in `TaskDao`)

**Comment by bernardsilenou** [comment]
@max-hzi

**Comment by MateStrysewske** [comment]
@bernardsilenou Can you tell me why we need a filter for this? What's the use case for using it?

**Comment by bernardsilenou** [comment]
@MateStrysewske I can't remember the use case that caused me to open this issue, It was a request from DE users, thus may still be valid and also applies to non-DE users. Possible use cases that I can come up now are:
1. I as a surveillance supervisor get a task and  I need to call the specific user who assigned the task to me to get more information. Users in a region or districts usually have the mobile numbers of one another, so b seeing the name of the user, I can then call them.
2. I as a surveillance supervisor belonging to a team or surveillance supervisor  among many teams and wish to first work on all the tasks that are sent to me from my direct boss (surveillance supervisor), thus I would need a filter to see all the task sent to me by boss

**Comment by kathsievers** [comment]
ISSUE TRACKER COMMENT

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT

**Comment by MateStrysewske** [comment]
@sergiupacurariu The new field is written in lowerspace in the Android app database upgrade script, which leads to errors when using the app because SQLite is case-sensitive. Please fix :)

The column should be called `assignedByUser_id` instead.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (0bd6842) on both vaadin app and android app.

Note: For the old Tasks, the 'Assigned by' is empty. It gets populated only when a user changes the Assigned User.
For the new created Tasks (except the Tasks that are automatically created when a new Case is created), the 'Assigned by' gets populated with the name of the user that made the assignment.

**Comment by JaquM-HZI** [comment]
I tested on test-de2: d20e85915ca981469b948e4898c3aac2437c83c4
Unfortunately there seems to be a problem with the translation it is done in crowdin (as `captions.properties` Task.assignedByUser) but is not displayed:
![image](https://user-images.githubusercontent.com/78568406/204525844-efac7e0e-63ad-4dc5-ac0c-2365c8ca7581.png)

**Comment by roxanamlendea** [comment]
@JaquM-HZI the translations have been fetched from crowdin today, so after the next deploy, should be updated on the testing instances as well.
