### ISSUE TITLE
Set up SORMAS X (eXchange) keycloak server [CONCEPT]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4626]
### Situation Description
When SORMAS instances are sending data to each other they need to be able to authenticate. Currently this is done by having a special user in each instance and sharing the login information for that user with all other instances, which is a lot of work to maintain.

### Feature Description

We need to replace this with a solution where the authentication is handled by a central keycloak. @vidi42 has created a draft of how this could work.

- [x] Set this up in a local or test environment
- [ ] Create setup guidelines
- [x] Define what may have to be changed in SORMAS or the per SORMAS keycloak instances

**Comment by JonasCir** [comment]
@MartinWahnschaffe 
Here is my update:
Next steps are:

- [ ] Configure the Keycloak automatically and setup client and resources (I already figured this out how to do it in the UI but we need to do this in an automated fashion via API)
- [ ] Patch SORMAS (library support is there and documentation on this is extensive)
- [ ] Test and refine :)

Branch is `concept/4626-keycloak-s2s`. Commit 8aeae12 provides a working starting environment for S2S in general that is based on Docker. I highly recommend to use it @MartinWahnschaffe or @vidi42 if you continue to work on Consul. It was a real pain to get to this point and it will safe you a lot of time :)
