### ISSUE TITLE
Set up a prototype Consul service discovery server for SORMAS2SORMAS

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4627]
### Situation Description
We need to have a central place that provides information on which SORMAS servers exists and how they are configured. Currently, whenever a new server is added, all other servers have to be updated with the new information.

Ideally a new server would self-register at a central place and all other servers could access this information whenever needed.

### Feature Description

*Consul* is a distributed, highly available service discovery and configuration system. See [Introduction to using Consul](https://www.digitalocean.com/community/tutorials/an-introduction-to-using-consul-a-service-discovery-system-on-ubuntu-14-04) and [Consul Getting Started](https://www.consul.io/docs/install).
 * [Consul for service discovery / registry](https://www.consul.io/docs/discovery/services) it should be possible to register new services via an API
 * [Consul Key/Value](https://www.consul.io/docs/dynamic-app-config/kv) for storing the certificates and needed configuration

Todos

- [ ]  Set up a local Consul server
- [ ]  Register two sormas instances (can be one the existing S2S test instances) as services
- [ ]  Define what meta information is needed and include it for the server (e.g. server name, some kind of ID)
- [ ]  Find a way to include the certificate - most likely put it into Consul KV
- [ ]  Access the Consul service from a local sormas instance to list the available S2S instances

**Comment by MartinWahnschaffe** [comment]
Closely related: #4626

**Comment by SahaLinaPrueger** [comment]
@MartinWahnschaffe is this issue still necessary or can it be closed?

**Comment by JonasCir** [comment]
This can be closed. We never used Consul but went with server descriptors stored centrally in `etcd`.
