### ISSUE TITLE
Enable voc documentation in pathogen test results and link the result to cases and samples  

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4633]
### Situation Description
Virus VOCs (variants of interest = disease variants of Covid19) can be documented at case form, the user can sort and filter for vocs.
### Feature Description
Enable the "disease variants" dropdown for pathogen test results, too, when "sequencing" or "PCR/RT-PCR" as test type and "positive" as test result was enabled. Adding the voc within the pathogen test result section shall enable automatic displaying the disease variant at the case form and as sample view "POSITIVE plus DISEASE VARIANT" at the case and the sample. 

Might look like this:
![image](https://user-images.githubusercontent.com/76884029/109995231-67d5a180-7d0e-11eb-9ba0-408152d1481e.png)

**Comment by bernardsilenou** [comment]
@maxiheyner  
Minor womment:
- I wish to ask if we can exclude the voc from the sample. Reason being that the sample can be shared by different pathogen tests, one test having an VOC for covid and another test is for a disease X that has no VOC. 
- Can we add it to the pathogen test  + case only ?
- If variant is recorded to the pathogen test and any of the cases linked to the sample has the same disease as that of the pathogen test, then we copy the variant to the case. But not vice versa

- I do not know if this is a major issues @MateStrysewske  ?

**Comment by maxiheyner** [comment]
@bernardsilenou Having the voc directly choosable at the sample is indispensable. More and more users need it. Can you please give feedback @MateStrysewske ? Thanks in advance.

**Comment by MateStrysewske** [comment]
@bernardsilenou @maxiheyner If I understood the initial issue correctly, it's not about adding the VOC to the sample entity, but adding it to the pathogen test and then displaying the VOC in the sample list when viewing a case, right?

**Comment by bernardsilenou** [comment]
@MateStrysewske @maxiheyner 
I thing this comment from @MateStrysewske is a middle solution that works without physically addint VOC to the sample entity. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4633#issuecomment-791512807
-  If the the sample is then connected to a disease that has no variant, we hid VOC on the sample from.
- @maxiheyner  would this be fine by you?

**Comment by maxiheyner** [comment]
@bernardsilenou @MateStrysewske  yes sounds fine, thank you!

**Comment by kwa20** [comment]
@maxiheyner @JaquM  I think this issues might also be covered with #5029. If so, we could close this after it has been verified.

**Comment by maxiheyner** [comment]
realized with 1.59
