### ISSUE TITLE
Prevent tasks from being saved when they have a specific task context but no associated entity

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4634]
### Bug Description
An error message appears when opening Tasks by a user with a specific user role (National User, National Clinician, National Observer) - alone or in combination with other roles.

### Steps to Reproduce
1. Log in to test.sormas.ch (with user role combination including any of National User, National Clinician, National Observer)
2. Click on "Tasks"
3. Error message appears on Task Directory, no tasks displayed

furthermore

4. Clear the error message (click the "x", click the "x" again, error message(s) disappear)
5. Filter by one region and apply filter
6. Directory displays Task from this region

### Expected Behavior
Tasks should be displayed and error message should not appear.

### Screenshots
1,2,3:
![image](https://user-images.githubusercontent.com/65529128/109876715-60f95100-7c72-11eb-9f14-dd8c6d6bc1c2.png)

4,5,6:
![image](https://user-images.githubusercontent.com/65529128/110008218-c1909880-7d1b-11eb-99a3-86531c14ff4e.png)

### System Details
* Device: 
* SORMAS version: 1.56.1
* Android version/Browser: Chrome
* Server URL: test.sormas.ch
* User Role: admin + (user role including any of National User, National Clinician, National Observer)

### Additional Information
Stack trace attached (thank you @nliakm!) - 
[sormas-ch.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/6086974/sormas-ch.log)
 
Error reproduced on 04.03.2021, test.sormas.ch, exact times + user role combinations: 
16.35 - Admin, national clinician
16.38 - national observer, admin
16.39 - national user, national clinician, admin

**Comment by MateStrysewske** [comment]
@Candice-Louw I don't know how it happened, but I think that there's at least one task on that server that has the task context "Contact", but no associated contact. At least that's what the error logs are telling me. Can you please verify that's the case? If so, the respective task needs to be deleted. I don't see any way in which this can happen on a production system without direct database manipulation - if there is such a way, it's apparently very rare because we didn't have this problem on any other server yet if I recall correctly.

**Comment by Candice-Louw** [comment]
@lebiku - please could you see if you are able to find the Task that has no associated Contact on the test.sormas.ch instance?  I believe the PowerApp you work on is plugging directly in to SORMAS?

I would really appreciate your help as I can't find the Task that has no associated Contact and this problem is holding back the rollout of 1.56.1 to CH, but may be due to database issues rather than functional issues?

**Comment by lebiku** [comment]
@Candice-Louw  @MateStrysewske I just checked test.sormas.ch and be.sormas.ch and we have tasks of type contact with missing corresponding contacts in both systems. In test.sormas.ch its about 70 and in the production environment its about 1000 entries. I expect a misbehaviour in our export criteria sometimes, but coudn't reconstruct it yet. I'll look into that and prevent future tasks with missing reference. But how can we cleanup the database? I only see tasks in the csv export, but don't see them in the UI.

**Comment by bernardsilenou** [comment]
@lebiku Thanks fro this information:
Please do you know how those tasks happened to be in the system in the first place?
You can have a look at the variable `creatoruser_id` and can also merge it with the user table

**Comment by lebiku** [comment]
@bernardsilenou Yes, we created some tasks (via the API) where the respective Sormas Contact Case Id or Case Id was missing. These result in errors in the GUI or query. If we filter by district / region (Bern). We get results, because in all those cases the contact or case is linked.

**Comment by MateStrysewske** [comment]
@lebiku What you could do is to either delete these tasks or reassign them to TaskContext.GENERAL to get rid of the errors:

`DELETE FROM task WHERE taskcontext = 'CONTACT' AND contact_id IS NULL;`

or

`UPDATE task SET taskcontext = 'GENERAL' WHERE taskcontext = 'CONTACT' AND contact_id IS NULL;`

What we should do to prevent this from happening again in the future is to add validation to the task saving process that rejects tasks that have task context CASE, CONTACT or EVENT but no associated entity.

**Comment by Candice-Louw** [comment]
@syntakker - there was another report of this happening on the test.sormas.ch server (version 1.59.2). LOG: 
[serverlog-25052021.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/6545744/serverlog-25052021.log)

Would you be able to check if it is the same thing that is happening, please?  If not, please let me know and I create a new issue. If yes, please let me know so I may ask the devs to clean the entries on the DB (and which SQL command to use for it, please?) that are causing the issue.

**Comment by Candice-Louw** [comment]
@lebiku - would you be able to inspect the data on the test.sormas.ch server to see if this is recurring, please?  The behaviour is exactly the same on the system 27.05.2021 as it was when reporting this bug on 04.03.2021.
