### ISSUE TITLE
Selecting a country name should should allow users to select jurisdiction of person

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4637]
### Bug Description
Issue #2994 added the option to auto fill the country name with that of the server local.
Selecting a country name prevents users from selecting the region + district of the address of the person
### Steps to Reproduce
1. Open a case person on the test server https://test1401.sormas-oegd.de/sormas-ui/
2.  Country is not autofill
3. Chose the country to be Germany (I hope this is what was used to setup the server) or any other country
4. Facility data can not be edited
5.

### Expected Behavior
1. enforce country of server when setting up a server
2. create this county as a country in the country list in the system
3. users should not be able to create the same country at front end
3. map this country to all country fields in the system
### System Details
* Device:
* SORMAS version: 1.47
* Android version/Browser:
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/ 
* User Role: national user + admin

**Comment by bernardsilenou** [comment]
@kwa20 
Is there a reason why users are restricted from documenting jurisdictions when the country is not the same as that on server?
I though we can allow them to enter free txt https://github.com/hzi-braunschweig/SORMAS-Project/issues/2994#issuecomment-770745969

**Comment by MateStrysewske** [comment]
@bernardsilenou I'm pretty sure the country name has not been properly set to the properties on that server. In that case, all jurisdiction fields are disabled when any country is selected, and that's expected behaviour. Just confirmed that it's working on my local system.

**Comment by bernardsilenou** [comment]
Task for netzlink then.
@kwa20 @Candice-Louw  @JaquM  To remind them when upgrading production servers

**Comment by bernardsilenou** [comment]
@kwa20 @MateStrysewske 
 Do you think is good to hide the jurisdiction and only show is when country is the same as server local?
Users may see variable but can not enter data an may think it is a bug. If you agree then I would add an issue for it.

**Comment by MateStrysewske** [comment]
@bernardsilenou I think you can find arguments for both approaches. I'd suggest to wait and see how the users respond to the current approach and only change something about it if we get feedback that it's confusing.
