### ISSUE TITLE
Detailed case export returns error

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4638]
### Bug Description
This happen on test1401 but not on release-international not on nightly build server
### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/110024605-9fecdc80-7d2e-11eb-9b68-7edbd34b3a39.png)

### System Details
* Device:
* SORMAS version: 1.47
* Android version/Browser: 
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin + national user

**Comment by MateStrysewske** [comment]
@bernardsilenou If you're experiencing export errors on a test system, please consult Netzlink and ask them for error logs before opening bug issues. We can't do anything about them without stack traces.

**Comment by bernardsilenou** [comment]
Closed because it works fine with 1.57.1
