### ISSUE TITLE
Introduce feature configuration for person management [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4649]
### Feature Description
The last update introduced the general person directory that is available as a menu entry in the main menu.

### Problem Description
The directory is visible and usable even if all feature types that are making use of the person entity are disabled. If that's the case, the person directory should also be inaccessible and be removed from the main menu.

### Proposed Change
Don't show the person directory when none of the following feature types are enabled:
* CASE_SURVEILANCE
* EVENT_SURVEILLANCE

This is sufficient because contact tracing depends on case surveillance to be active.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas version 1.58.0-snapshot on local environment
