### ISSUE TITLE
Case can be saved successfully when a future date is selected for Date of Symptom onset

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4651]
### Bug Description
When a future date is selected for "Date of Symptom Onset", although an error indication is displayed on the field the case can be saved successfully.
 
### Steps to Reproduce
1. Login to Sormas with any user role and access Case directory
2. Pick a case and access Symptoms tab
3. Select any symptom with yes and scroll to the field "Date of Symptom Onset" at the bottom
4. Pick a future date and try to save the case 

### Expected Behavior
Case should not be saved when the future date is selected or when any field has an error displayed.

### Screenshots
![future date for Date of Symptom onset-Case saved](https://user-images.githubusercontent.com/62763628/110135902-56080300-7dcf-11eb-9441-3d027f561665.png)

### System Details
* Device:
* SORMAS version: 1.58.0-Snapshot
* Android version/Browser: Chrome and Firefox
* Server URL: test.sormas.netzlink.com
* User Role: any role (ex: SurvSup)

**Comment by DavidBaldsiefen** [comment]
Closed in favor of #4928
