### ISSUE TITLE
Event Participants disappear as the save prompt is not displayed after adding samples to event participant.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#4653]
### Bug Description
Event participants are not displayed in the UI when user adds a sample to an event participant an leave without explicitly saving it.
Added sample is also not displayed in Samples directory

### Steps to Reproduce
1. Login to Sormas as SurvSup or any other user
2. Access Event directory and pick an event
3. Go to Event Participants tab and add a participant.
4. Access the Event Participant and add a sample.
5. Click on other menu options such as cases/contacts without explicitly clicking on save.
6. Go back to event and see if the newly added event participant is visible. Also check for the added sample.

### Expected Behavior
Event participants should not be disappeared from the ui.
May be a save prompt must be displayed before user is navigated to other menu.
 
### Screenshots
![EP count](https://user-images.githubusercontent.com/62763628/110147647-3a572980-7ddc-11eb-9f93-579546812da8.PNG)
![No event participants visible](https://user-images.githubusercontent.com/62763628/110147661-3cb98380-7ddc-11eb-912b-7d5abf325118.PNG)

### System Details
* Device:
* SORMAS version: 1.58.0-Snapshot
* Android version/Browser: Chrome and Firefox
* Server URL: test.sormas.netzlink.com
* User Role: Any role (Ex: SurvSup)

### Additional Information
Event Participant count is updated but the event is not visible.
Added sample is also not visible in the sample directory.

**Comment by MateStrysewske** [comment]
Very likely associated with recent user filter changes.

**Comment by MateStrysewske** [comment]
Also consider #4657

**Comment by syntakker** [comment]
Fixed by #4676.
The following problems persist:
- More than one samples with equal dates lead to multiple entries for the same event participant, if there is no later sample
- deletion of samples is ignored

**Comment by raghupola-vg** [comment]
Verified on latest deploy on test environment with version 1.58.0-Snapshot and issue is Fixed.
