### ISSUE TITLE
Event Participants are disappearing from the list of an event once a pathogen test is added

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#4657]
### Steps to Reproduce
1. Open test.sormas.netzlink.com
2. Go to Events and create a new event
3. Create a new Event Participant
4. Open the event participant 
5. Create a new Sample for that event participant and create a test result 
6. Go back to the event Participants list 

### Expected Behavior
The Test result should be saved and displayed at the end of the event participants list.

### Actual Behavior
The Event Participant is unlinked from the Event  and not shown anymore in the Event Participant list
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/110219112-e759a100-7ec5-11eb-9cad-a3fbcdfd6ce1.png)

![image](https://user-images.githubusercontent.com/70562142/110218904-eb38f380-7ec4-11eb-933c-5874a17ce0f2.png)

### System Details
* Device: Windows 10 
* SORMAS version: SORMAS Version: 1.58.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: NAtUser

### Additional Information
This issue is linked to  #3853

**Comment by MateStrysewske** [comment]
This sounds very similar to #4653, so I'm closing this one.
