### ISSUE TITLE
user location fields overlap

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4660]
### Bug Description
When creating or editing users as an admin, location information fields, symbols and headers overlap. 
### Steps to Reproduce
1. Go to users
2. create or edit a user

### Expected Behavior
Buttons, symbols and headers should be properly displayed.
### Screenshots
<img width="305" alt="overlapLocationUser" src="https://user-images.githubusercontent.com/70317594/110250532-f733bc80-7f7b-11eb-8ddd-ab51f851b4ea.PNG">

### System Details
* Device:
* SORMAS version: 1.57.0/1
* Android version/Browser:
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by StefanKock** [comment]
Proposal: Increase the width to 2/3 (make `LocationDto.details` field smaller).

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.65.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
