### ISSUE TITLE
exposures are being deleted upon case merging

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4661]
### Bug Description
When merging cases, the exposures of the case that will be discarded are not being merged with the remaining case but deleted.
### Steps to Reproduce
1. Create a case and enter an exposure
2. Create a duplicate case and enter a different exposure

### Expected Behavior
When cases are being merged, additional exposures should be adopted rather than deleted.
### Screenshots
<img width="450" alt="exposureMerge" src="https://user-images.githubusercontent.com/70317594/110252445-c48ec180-7f85-11eb-987a-fcd911cce2a4.PNG">
<img width="469" alt="exposureMerge2" src="https://user-images.githubusercontent.com/70317594/110252465-d53f3780-7f85-11eb-8558-a2eecbfda8d7.PNG">
<img width="827" alt="exposureMerge3" src="https://user-images.githubusercontent.com/70317594/110252455-c9ec0c00-7f85-11eb-86ae-277e972ca1a2.PNG">

After merging:
<img width="452" alt="exposureMerge4" src="https://user-images.githubusercontent.com/70317594/110252458-cc4e6600-7f85-11eb-97f9-99b5b401852b.PNG">

### System Details
* Device:
* SORMAS version: 1.57.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
verified on version 1.57.2 on test1401.sormas-oegd.de and 1.58.0 on test environment.
Issue is Fixed.
