### ISSUE TITLE
Surveillance reports facility options are limited

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4662]
### Bug Description
When entering facilities in surveillance reports, the facility options are limited.
### Steps to Reproduce
1. Open or create a case
2. Add a surveillance report
3. enter facilities

### Expected Behavior
All possible facility options should be available.

### Screenshots
<img width="362" alt="facilitiesReports" src="https://user-images.githubusercontent.com/70317594/110252808-77135400-7f87-11eb-9b29-2996fbe0779c.PNG">

### System Details
* Device:
* SORMAS version: 1.57.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
Verified on 1.57.2 version on test1401.sormas-oegd.de and issue is Fixed.
