### ISSUE TITLE
Missing caption for activity type in case activities table

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4663]
### Bug Description
when enabling the activity as case table, type of activity is displayed as a variable rather than a string.
### Steps to Reproduce
1. Go to epi data in cases
2. select yes under activity details known

### Expected Behavior
column header shows the correct string

### Screenshots
<img width="433" alt="activityAsCaseType" src="https://user-images.githubusercontent.com/70317594/110253332-10dc0080-7f8a-11eb-88e0-d6181276b8a0.PNG">

### System Details
* Device:
* SORMAS version: 1.57.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by alexcaruntu-vita** [comment]
I am not able to reproduce this with the latest build.

**Comment by MateStrysewske** [comment]
Seems to be fixed already
