### ISSUE TITLE
vaccination field validation missing for contacts and event participants

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4665]
### Bug Description
The fixed vaccination validation (cf. #4276 ) is missing for contacts and event participants
### Steps to Reproduce
1. Go to contacts and event participants
2. Enter contradicting vaccination information

### Expected Behavior
last vaccination date should only be allowed to be set after or on the same day as the first vaccination date. Vaccination dose should only allow integer values independent of the delimiter.
### Screenshots
<img width="443" alt="vaccinationValidation" src="https://user-images.githubusercontent.com/70317594/110254119-0cb1e200-7f8e-11eb-8db2-4d40f4518c2b.PNG">

### System Details
* Device:
* SORMAS version: 1.57.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot on local environment
