### ISSUE TITLE
Sorting responsible and reporting user columns on event directory result in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4666]
### Bug Description
Trying to sort the responsible and reporting user columns on the event directory results in error
### Steps to Reproduce
1. Go to the event directory
2. Sort the responsible and reporting user columns

### Expected Behavior
sorting should work fine.
### Screenshots
<img width="843" alt="userColumnEventsError" src="https://user-images.githubusercontent.com/70317594/110254248-b2fde780-7f8e-11eb-8e25-fbb3f3fa1930.PNG">

### System Details
* Device:
* SORMAS version: 1.57.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by raghupola-vg** [comment]
Verified on version 1.58.0-Snapshot and issue is Fixed.
