### ISSUE TITLE
[SurvNet Interface] Events > Add new field "Internal ID" [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4668]
### Situation Description
The concept of generating an automatic "Herd Identification number" for outbreaks based on international standards is required.

### Feature Description
Events > Open Event > Introduce "Internal ID" (en-) / "Name im Gesundheitsamt" (de-) field [DE only]:
![image](https://user-images.githubusercontent.com/65529128/110285721-f6367580-7fe3-11eb-9714-739c2c7c1783.png)

Initially - this field will be a free-text and filled in by hand.

### Additional Information
SurvNet Mapping (Field Tab):

IdField | FieldName | Code | Schema2 | Schema3 | Schema4 | IdParent | DataTypeName | FieldTypeName | Sort | XmlName | GuiText | GuiTextShort
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
202 | NameGA | Outbreak | 1 | 1 | 1 | 0 | String255 | Simple | 2 | NameGA | Name im Gesundheitsamt | NameGA

![image](https://user-images.githubusercontent.com/65529128/110293084-6649f900-7fee-11eb-93bd-e13d357e921d.png)

**Comment by AndyBakcsy-she** [comment]
Verifid ticket on the latest version of sormas 1.58.0-snapshot on web
