### ISSUE TITLE
Hide CRS-related fields on German servers

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4675]
### Bug Description
Fields usually hidden on german servers are not hidden anymore on the person information form.
### Steps to Reproduce
1. Go to the person directory
2. Open any person in the list

### Expected Behavior
Fields should be hidden on the person information form for german servers.
### Screenshots
<img width="1012" alt="Screen Shot 2021-03-08 at 2 19 14 PM" src="https://user-images.githubusercontent.com/70317594/110327045-c1451580-8019-11eb-9bd6-0e36b1df510b.png">

### System Details
* Device:
* SORMAS version: 1.57.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
@kwa20  @Candice-Louw  I thought these fields were added on DE instance, 
I think these fields are not needed for the Internationale instance also.
Are they CH specific?

**Comment by kwa20** [comment]
@bernardsilenou They are disease specific and were apparently implemented for Congenital Rubella (CRS).

**Comment by bernardsilenou** [comment]
@kwa20 I remember now, thanks

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.58.0-snapshot on local environment
