### ISSUE TITLE
[SurvNet Interface] Allow deletion of SurvNet cases while keeping the case in Sormas [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4683]
### Situation Description
When cases are wrongfully sent to SurvNet or e.g. responsibility of case reporting changes, cases can not easily be deleted through the Sormas interface to SurvNet and if a deletion is performed in SurvNet itself, users don't see it in Sormas. 
### Feature Description
Introduce the option to delete cases in SurvNet through the SurvNet interface in Sormas. This will also improve clarity about the history of transmissions and deletions of cases through the interface. Users then don't have to open SurvNet to check on the status of the case.

### Additional Information
<img width="698" alt="Screen Shot 2021-03-08 at 6 09 25 PM" src="https://user-images.githubusercontent.com/70317594/110356288-5f48d800-803a-11eb-90a4-17117f5308e3.png">
Screenshot includes transmission info of the usability improvements (#3947 ).
@JaquM

**Comment by bernardsilenou** [comment]
@kwa20 I am not sure if I full understand this need. However I do not think it is good to delete entities in another system while connect in another system.
Can the users not connect to survnet and delete the wrongly shared cases?

**Comment by bernardsilenou** [comment]
@kwa20 This is good information. I did not know that the cases have read access only after being push to own ServNet instance.
So all entities like events, contacts are also read only?
I also think it is better to manage entities in sormas only. But if entities can be managed and deleted in ServNet also, then it would not be good to delete entities in ServNet  through SORMAS.
Is it not possible to  extend the api to be able to get the information of deleted cases in SurvNet, and inform the sormas user? ie deletion only happen in SurvNet and SORMAS can then get this information when it sync with SurvNet and inform the SORMAS user.

**Comment by MartinWahnschaffe** [comment]
* The functionality to delete the case is already implemented in the backend and on the survnet converter side: SurvnetGatewayFacade.deleteCases/Events
* The functionality to "log" the deletion in SORMAS is implemented as part of  #4771

This means the look will be a bit different from the mockup above. I suggest to:

- [ ] Put the delete button right next to the send button
- [ ] When clicked the user should have to confirm that the case should really be deleted in SurvNet
- [ ] Call the delete method and update the UI. Based on #4771 it should already show the correct state

### unclear
When do we show the button? One option would be to only show it when the case has been sent from SORMAS to SurvNet. This would mean that it does not show when the case was manually created in SurvNet or was initially imported into SORMAS from SurvNet. 
Another option is to show the button when the externalId is not empty.

@JaquM Will ask whether deleting a case and then sending it again might cause any trouble in SurvNet

**Comment by JaquM** [comment]
@MartinWahnschaffe 
Talked to RKI: there is no expected problem with sending the case again after deleting.

**Comment by leventegal-she** [comment]
Blocked by https://github.com/hzi-braunschweig/SORMAS-Project/issues/3947

**NOTE**: The delete affects the getting *SurvNet transfer info* added by the above ticket.
<img width="710" alt="Screen Shot 2021-01-08 at 7 30 28 PM" src="https://user-images.githubusercontent.com/70317594/104053513-aefe5500-51eb-11eb-8800-bbdfd886ca9d.png">

**Comment by markusmann-vg** [comment]
New Column: Action
updated / deleted

behind the date of last transmission

Count includes update & delete actions

**Comment by leventegal-she** [comment]
* Delete button added right next to the send button on the detail pages
* A new status column  added on the Case directory
* Count and filters include update & delete actions

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the last version of sormas 1.59.0-snapshot on test-de1.sormas.netzlink.com
