### ISSUE TITLE
Login as PoeInf returns HTTP Status 403 - Forbidden

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#4686]
### Bug Description
Login as PoeInf returns HTTP Status 403 - Forbidden. Much worse, any subsequent login as another user returns HTTP Status 403, too.

### Steps to Reproduce
1. Login as PoeInf => HTTP Status 403 - Forbidden
2. try to login as any other user => HTTP Status 403 - Forbidden

### System Details
* Device: Linux PC
* SORMAS version: 1.58.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: test-de.sormas.netzlink.com
* User Role: PoeInf

**Comment by syntakker** [comment]
The reason was that PoeInf is a known user, but has no access to the web app. So after successful login, the page to be shown next is forbidden. Since neither the session was terminated nor PoeInf was logged out, this state persisted for subsequent tries to login with different credentials (unless cookies are manually deleted in the browser).
Digging in history showed that a respective check was already there at some point, but was lost in the course of some refactoring.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the last version of sormas 1.58.0-snapshot
