### ISSUE TITLE
Prompt default users to change their password on login

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4690]
### Situation Description
During server setup, server administrators can configure SORMAS to generate a number of default users that are useful for testing and development purposes. However, these users also have default passwords and thus are a potential security breach, especially if administrators forget to disable these users on production systems.

Default user generation is turned off by default, but there's still a mandatory admin user with a standard password generated.

### Feature Description
The new feature should present a prompt at login to any of the standard users using their standard password (as is defined in `StartupShutdownService:createDefaultUsers`) to change their password. The password changing logic can be the same as when editing a user from the user directory.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.59.0-snapshot on local environment
