### ISSUE TITLE
Android app: Hospitalization fields are always editable

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#4701]
### Bug Description
Hospitalization fields are always editable in the Android app. Moreover, they are not cleared after a transfer.

**Comment by DavidBaldsiefen** [comment]
When shouldn't they be editable?

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen They should only be editable when the case is currently located in a hospital. I think we already have this logic properly implemented for the web app, so it probably only has to be applied to the mobile app as well.

**Comment by DavidBaldsiefen** [comment]
While working on this I noticed that the detailed facility fields as well as the field specifying wether the case is currently at home or in a facility randomly go missing:

How it should look:
![image](https://user-images.githubusercontent.com/4655486/111181459-4b5b2400-85ae-11eb-8594-f61799579107.png)
How it actually looks:
![image](https://user-images.githubusercontent.com/4655486/111181526-5dd55d80-85ae-11eb-801c-0a32519f06ac.png)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot
