### ISSUE TITLE
[DEMIS Interface] Introduce option to download lab messages [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4703]
### Situation Description
Users that process lab messages through the DEMIS interface would also like to have the opportunity to download these messages.
### Feature Description
Introduce the option to download the lab messages. For that, add a button to the directory for that purpose. This should independent of the status of the lab messages (processed, unprocessed). The downloaded format should ideally be PDF. Messages should always be downloadable independent of their status.

### Additional Information
<img width="703" alt="Screen Shot 2021-03-09 at 8 39 01 PM" src="https://user-images.githubusercontent.com/70317594/110528215-2ed76b80-8118-11eb-8554-4826b6401f78.png">

- [ ] Add errorhandling if the adapter cannot be accessed nor a proper html file was generated

**Comment by vidi42** [comment]
https://github.com/microsoft/playwright-java as a suggestion for generating PDFs from HTML

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by vidi42** [comment]
DEMIS Adapter part to be done in https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/9
