### ISSUE TITLE
Button overlapping in events (German)

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4706]
### Bug Description

In the German-language systems, the buttons overlap in the events. In addition, there is no uniform definition of where the buttons are positioned. In the case of tasks, actions and parts, they are placed next to the descriptions/labels, while in the case of superordinate and subordinate events, they are placed below them.

![grafik](https://user-images.githubusercontent.com/74791118/110613984-26bc1200-8192-11eb-9e96-ff9b98ef3a2d.png)

**Comment by Marko-ilmkreis** [comment]
Its in few parts a duplicate of #4127

**Comment by kwa20** [comment]
@Marko-ilmkreis The first one was bugging me a lot as well so I've retranslated it to "Hochladen" for now. Just for your information.

**Comment by Marko-ilmkreis** [comment]
@kwa20 Thanks for let me know. I understand that this issue (and the other similar) is nothing which has any priority regarding as its not a really bug in meaning of any function. And I know as well that this ui will be replaced (soon?).

**Comment by kwa20** [comment]
This issue should be resolved by the re-placement of the buttons.
