### ISSUE TITLE
Update dependencies (1.65) [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#4707]
### Proposed Change

Update at least the following dependencies:

- [x] keycloak-admin-client 12.0.1 -> 12.0.4 => https://github.com/hzi-braunschweig/SORMAS-Project/issues/5901
- [x] resteasy 3.9.1 -> 3.15.1
- [x] json-path 2.4.0 -> 2.6.0
- [x]  docx4j-docx-anon 8.2.8 -> 8.3.1
- [ ] ~poi-ooxml 3.17 -> 4.1.2~ -> has breaking changes, split out to #6830
- [x] spring-context 4.0.3.RELEASE -> 4.3.30.RELEASE
- [x] jsoup 1.13.1 -> 1.14.2
- what else?

(check for latest updates when taking this ticket into the sprint)

### Additional Information
- Out of scope: Updates unique for sormas-app (see #3765)
- Uncertain if major update of `poi-ooxml` will work (smoothly)
- Updating `spring-context` will likely work (but do it also for `sormas-app`)

<details>
<summary>Risk with update of "resteasy" to break with "keycloak-admin-client"</summary>

We need to update `resteasy` libs from 3.9.1 to 3.15.1, but it is uncertain if this will still work for `keycloak-admin-client`.

```
<!-- sormas-base/pom.xml -->

        <resteasy.versions>3.15.1.Final</resteasy.versions>

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxb-provider</artifactId>
            <version>${resteasy.versions}</version>
        </dependency>
```

</details>

**Comment by StefanKock** [comment]
I changed the tasks in in the description back to a bullet point list due to spacy rendering and easier copy-paste option for git comments.

**Comment by BarnaBartha** [comment]
- [ ] decide if we need major version increase of poi-ooxml -> needs major refactor of data dictionary generation
- [ ] test android app with android sdk 24 with spring context 4.3.30
