### ISSUE TITLE
Low bandwidth data synchronization (LBDS)

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#471]
@MartinWahnschaffeSymeda 

Same issue as #470

**Comment by MartinWahnschaffeSymeda** [comment]
Basic question is: How can we update the SORMAS app when there is no connectivity.

Options:

1. Manual update of the SORMAS app (copy latest version via SD card or bluetooth)
2. Use some kind of local hotspot that pushes the latest version and also synchronizes data (#470). Unclear whether this is possible with MDM.

**Comment by MartinWahnschaffeSymeda** [comment]
See #3522

**Comment by VitaliHZI** [comment]
Hello Team, 
if we have already another Issue for this topic, why we dont close this issue? 
For me it is a dublicate, same like  #1787 

Or is there a reason, why we keep this open? 

BR 
Vitali

**Comment by bernardsilenou** [comment]
@VitaliHZI 
From @MartinWahnschaffe comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/1787#issuecomment-613258962
The main goal is the same but the technology are different, thats why both are still open.

**Comment by MartinWahnschaffe** [comment]
With the prototype being implemented in #3522 and potential follow-up work defined in #7528, I'll close this one.
