### ISSUE TITLE
Creating a sample and a test result forces errormessage

### ISSUE THREAD

**Issue by heineltp** [hzi-braunschweig/SORMAS-Project#4723]
Hallo,

bei Adding a spample and a testresult to a event participant all in the first sample window does not work in our instance.
Adding a sample in step one without any testresult, saving this and adding the testresult as a step two works.

Via Support they told me it may be a bug in our instance because in the testenvironment it may work.

userroles testet: every role with the right to mangage samples, admin, nationaluser, etcpp.

Probably some could test this problem and tell me if we are the only concerned instance...?

Thank you.

**Comment by MateStrysewske** [comment]
@heineltp Hey! This issue was already reported here: #4493 

We can't reproduce it on a test instance or on our local development machines. My suggestion is to see whether the next update to a newer version will fix this problem.

**Comment by heineltp** [comment]
okay thank you for your message, i will see and report.
