### ISSUE TITLE
Import script for facilities

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#4728]
### Situation Description

For scenarios where multiple SORMAS intances are used per country (e.g. one per district in Germany), there is a need to have a shared facility list. For now we will address this by importing the same list of facilities into all instances.

Problem: Importing facilities via the UI currently does not allow to update data of existing facilities, since there is no clear identifier.
Furthermore the authorities have a need to make sure that all SORMAS instances do have the facilities and thus prefer not to rely on every single SORMAS admin having to import the data.

### Feature Description

- [x] Provide an SQL script that allows to import facilities into SORMAS that are provided as CSV, following the import schema used in the UI import functionality.
- [x] The script needs to check for existing facilities based on the external ID. If the facility already exists it is supposed to update/override the facility with the values from the import file
- [x] Import lines that do not have an external ID should be ignored and ideally logged
- [x] persist script under `sormas-backend/utils`

*Important*: The data is supposed to be imported as soon as possible (ideally already into 1.57), so the new fields added in #4027 may not be there yet, but should be included when re-importing the data for 1.58.
This should also be updated when #3931 and #4066 are implemented.

### Possible Alternatives
* Provide a centralized architecture to distribute facilities to SORMAS instances. Before further considering this, it would need to be defined which country-wide data sources exists for hospitals, laboratories, doctors offices, schools and other relevant facility types. In addition to this a country wide unique identifier to be used as external ID would be very helpful when exchanging data with external systems.
* Extend the UI import functionality to allow automatic merging based on external ID and manual merging based on similar names.

### Additional Information

CSV Template that also include the fields introduced with #4755 and #3931.
[sormas_import_facility_template.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6161770/sormas_import_facility_template.txt)

**Comment by kwa20** [comment]
Take #4755 into consideration for re-import.
