### ISSUE TITLE
Make configurable the tabs of the cases, contacts or events sections 

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4733]
### Situation Description
The CNIL asks the Ministry to limit free text fields which increase the risk of entering personal and sensitive data. During its inspection, it issued a recommendation (which it would be good to be able to implement) consisting in hiding the tabs of the cases / contacts and event parts that are not used (eg: hospitalization, clinical course, etc.) in order to control this risk.

### Feature Description

We suggest making the tabs that each user want to display or  to hide, configurable in a configuration file.

We could imagine that a certain number of tabs are always displayed and not configurable (ex : case or person case) but that the display of the other tabs are configurable (like what exists for actions of the event for example).

Below is the list of tabs that we propose to make configurable:

- CAS: Hospitalization, symptoms, epidemiological data, therapy, clinical course, follow up

- CONTACT: epidemiological data, follow up visits

- EVENT: event actions

### Additional Information
@ftavin @bernardsilenou @emond-fuseau @olivierleuci

**Comment by ftavin** [comment]
@carolinverset for the event actions part, isn't this feature already configurable ?

And @bernardsilenou told us about a new tab "laboratory messages" (not sure of the exact name) that is to come in the sample part, is it already under development ?

**Comment by carolinverset** [comment]
> @carolinverset for the event actions part, isn't this feature already configurable ?
> 
> And @bernardsilenou told us about a new tab "laboratory messages" (not sure of the exact name) that is to come in the sample part, is it already under development ?

@ftavin 
I'm not very sure but I think so :  I think I remember having asked the IT specialist to activate this feature during its implementation several months ago.

**Comment by MateStrysewske** [comment]
@ftavin There's a feature configuration for the new lab messages that is turned off by default. And I don't see a feature configuration for event actions - I think we discussed it at some point, but decided that they make sense for every instance that uses events and so dismissed it. Not a hundred percent sure though.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Dev France would work for this in 1.59

**Comment by ftavin** [comment]
Note : by default, tabs will be activated

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest build of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
