### ISSUE TITLE
Task Notification: include the identifier of the event, case or contact in the form of a hypertext link

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4734]
### Situation Description
When a task is assigned to a SORMAS user, a notification can be sent to him. To date, this notification specifies the nature of the task and the identifier of the case / contact / event associated with the task.
In the context of an epidemic recovery, the number of notifications sent can quickly become large and users waste a lot of time going from messaging to SORMAS to identify the right event to investigate.

### Feature Description
In order to facilitate access to the events to be investigated (but also to the case and contact), it is proposed to replace the identifier with a hypertext link allowing direct access to the event sheet concerned by the task.

If :
- the user is connected to SORMAS, he will be directed directly to the file concerned by the task
- the user is not connected to SORMAS, he will first be oriented towards the authentication windows and then, after having entered the login and password, on the form concerned by the task.

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by bernardsilenou** [comment]
@MateStrysewske  Dev France would work for this in 1.59
