### ISSUE TITLE
@ SORMAS Nigeria: Error in updating Negative result for a particular district (FCT)

### ISSUE THREAD

**Issue by Mabayoje** [hzi-braunschweig/SORMAS-Project#4735]
### Bug Description
Problem: Importing Negatives result for a particular district in Nigeria (FCT) is given critical error 
Furthermore  when updating Result to NEGATIVE using Create test for this sample now option it gives error message for the same district (FCT)
### Steps to Reproduce
1.
2.

### System Details
* Device: web
* SORMAS version:
* Android version/Browser: chrome
* Server URL:
* User Role: All
![FCT Bug](https://user-images.githubusercontent.com/54799249/110813156-85fc4e00-8288-11eb-8d61-d276e2547c4f.PNG)
![fct bug import](https://user-images.githubusercontent.com/54799249/110813197-914f7980-8288-11eb-85e5-f731b1260668.PNG)

**Comment by MateStrysewske** [comment]
@Mabayoje Nigeria is currently using a very outdated version of SORMAS. I've already investigated this issue and it doesn't appear on my development system using the recent version, so I suspect this will go away as soon as Nigeria's moving to an updated SORMAS version.
