### ISSUE TITLE
Do not consider a white space only as a name

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4739]
### Bug Description
- White space is taken as data
- duplicate detection also accept this value and suggest duplicates with persons having real names
### Steps to Reproduce
1. Create/ edit a contact/ case/ep and in the space of name, type the space key only
2. save the data
3. all works fine

### Expected Behavior
- At entity creation, white space should not be considered as data
- Check that duplicate detection of person is working well.  Normally white spaces are deleted before matching the strings.
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/110905289-8806f100-830a-11eb-886e-38ee3c95317f.png)

![image](https://user-images.githubusercontent.com/12996724/110905419-bb498000-830a-11eb-8ec1-226b196e7650.png)

### System Details
* Device:
* SORMAS version: 1.57.2
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: surveillance supervisor + contact supervisor

**Comment by JonasCir** [comment]
**Implementation Note**
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/4937
We now use java validation annotation. I think the best way to do it is to make use of NotBlank annotations where it makes sense in the code base and not just only NotNull

**Comment by MateStrysewske** [comment]
Should be taken care of in #4959 in the next sprint.
