### ISSUE TITLE
Person directory contains pseudonymized persons for users without accessibility restrictions

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4743]
### Bug Description
Persons with not associated entity show up in the person directory.
### Steps to Reproduce
1. Connect to system with a user that has full access to all entities, National user
2. go to person directory, and look for pseudonymized persons, normally there should be done
3. open the person form and check if thy are linked to any entity 

### Expected Behavior
- The person directory should only show persons linked to entities that have not been deleted
- Pseodonymization should not affect national user
### Screenshots
![image](https://user-images.githubusercontent.com/12996724/110910425-9b698a80-8311-11eb-8ac0-a8fd1457172f.png)

![image](https://user-images.githubusercontent.com/12996724/110910604-dd92cc00-8311-11eb-84ff-bdfe29122722.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
   https://test1401.sormas-oegd.de/sormas-ui/#!persons
* User Role: surveillance supervisor + contact supervisor and admin+ national user

**Comment by Marko-ilmkreis** [comment]
In my opinion the person directory should show all persons the user has the right to see. Even if they are not linked to an entity.

**Comment by kwa20** [comment]
@bernardsilenou I think the confusing part is the pseudonymization of persons even for users wihtout any regional restrictions.

**Comment by MateStrysewske** [comment]
I agree with @Marko-ilmkreis - in reality this won't really happen too often anyway, especially once we have the deletion concept, because then persons will get deleted alongside their last case/contact/event participant if I'm not mistaken.

The pseudonymization part is strange though. I'll change the issue title accordingly.

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  
I quote you `In my opinion the person directory should show all persons the user has the right to see`.Do you mean that it is the entity that determines the right ?: either the person is linked to an entity in the jurisdiction of the user or the user is the reporting user of the entity linked to the person. I also agree with you.

@MateStrysewske  @kwa20 
Are these persons linked to entities that have been deleted ?

If yes, then Questions pls:
1. If a user has full access (read + write) to a case for example, then they see the person in person directory :+1:  Then if this case is deleted, what to we do:
   1.1  show person in full access mode
   1.2  show person in read access mode
   1.3  show person in pseudonymize access mode

2. If a user has read access  to a case for example, then they see the person in person directory with read access only:+1:  Then if this case is deleted, what to we do:
   2.1  show person in read access mode
   2.2  show person in pseudonymize access mode

3. If a user has pseudonymize access  to a case for example, then they see the person in person directory with pseudonymize access only:+1:  Then if this case is deleted, what to we do:
   3.1  show person in pseudonymize access mode

My response is that when all the entities of a person are deleted then we can just soft delete the person also. Is there a reason whey we keep them?

**Comment by bernardsilenou** [comment]
@MateStrysewske I just had a look at the person table and the is no variable `deleted`, was it removed ? 
Does that mean soft deleted entities persons are considered in duplicate detection and other person related stuffs?
I am confused

**Comment by Marko-ilmkreis** [comment]
If the person is not linked to an entity, the person should be shown for the same rights the user have. I agree that this might be a very rare case. Whats about integrating a filter for "person without any contact/case/ep" and the option for the admin to delete it?

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis 
I do not understnd you, please can you explain what you mean by "same rights the user have"?

> If the person is not linked to an entity, the person should be shown for the same rights the user have. I agree that this might be a very rare case. Whats about integrating a filter for "person without any contact/case/ep" and the option for the admin to delete it?

- You know the person and user tables are not the same, the person search is only for persons not users.
- My suggest is that if all entities of a person are deleted (not archived), then the person should also be deleted. It is for the same reason that we do not document data for persons who are not linked to entities. If at least one of the entities of a person is archived even for many years, then we keep the person

**Comment by Marko-ilmkreis** [comment]
@bernardsilenou Yes I know that these are different tables. I meant that if an entity is not visible for the user oder pseudonymized it must be the same for person itself.  Sorry for the misunterstanding.

I agree that the person must be deleted if all entities are deleted too.

**Comment by MateStrysewske** [comment]
@bernardsilenou Persons never had the "deleted" flag so far. Once the proper deletion concept is implemented, this will happen naturally. However, it will at some point be a very rare case that a case with a NEW person is accidentally created. We'll also have retrospective duplicate detection for persons in the near future.

There's two ways how we can handle situations like those described by you as a general rule:

* If a person is NOT linked to any NON-DELETED case, contact or event that the user is allowed to access, DON'T show it in the person directory
* Always show persons that the user has access to, but if there's no link to any NON-DELETED case, contact or event, use the person's address to determine whether the user has access or not

Which solution do you prefer @bernardsilenou @Marko-ilmkreis?

**Comment by Marko-ilmkreis** [comment]
>  However, it will at some point be a very rare case that a case with a NEW person is accidentally created.

I think in our instance might be a lot of duplicates. With the current, limited details of the duplicate person popup (#4003) the colleagues are by any doubts creating a new person.  

>     * Always show persons that the user has access to, but if there's no link to any NON-DELETED case, contact or event, use the person's address to determine whether the user has access or not

I would prefer that one if the duplicate detection goes the same way. Otherwise the user would be confused by showing a duplicate and the person directory does not list the person.

**Comment by kwa20** [comment]
@MateStrysewske @bernardsilenou @Marko-ilmkreis

 Summary of things that cause this problem:

- Pseudonymized persons are displayed on the person directory when they have no linked entities.
    - This is likely the case because the person db table does not have a deleted column that tags persons as deleted. This was previously not relevant because persons were only shown in association with the entity. 
    - Since persons cannot be hard deleted yet, we could 
    - a) either add this to the person table and hide those marked as TRUE or
    - b) just exclude persons without linked entities from the person directory.

The actual deletion should be handled in #2100, #2101, #2102

**Comment by kwa20** [comment]
@MateStrysewske Judging from the additional information in https://github.com/hzi-braunschweig/SORMAS-Project/issues/6035, this does not to occur anymore. Is this issue still relevant then?

**Comment by MateStrysewske** [comment]
No, that's true - actually #6035 is a fix for this problem, so it's technically a duplicate - however, since it describes the problem more precisely from a development point of view, I'll close this issue here.
