### ISSUE TITLE
Duplicate check: Display other attributes to clearly identify a person

### ISSUE THREAD

**Issue by julia-eggers** [hzi-braunschweig/SORMAS-Project#4745]
### Situation Description
[This request is reported on behalf of the Gesundheitsreferat München.]

- Large health offices, such as the Gesundheitsreferat München, record numerours people in the person database that share the same firstname and lastname (e.g. "Hans Müller")
-  Currently, when creating a new case/contact in SORMAS the duplicate check uses attributes (e.g. firstname, lastname, age, gender, city) that are not meaningful enough to clearly identify whether a person already exists in the person database. For example, there are multiple "Hans Müller", male, aged 59 years, living in Munich. The user can not distinguish these people by looking at the results table of the duplicate check (see screenshot below).

### Feature Description
- The duplicate check should display the following attributes to let the user clearly identify a person: Lastname, firstname, gender, date of birth, zip code, city, community, street. 

### Additional Information
![image](https://user-images.githubusercontent.com/79311833/110925685-ca88f780-8323-11eb-9341-16b63e661ca2.png)

**Comment by MateStrysewske** [comment]
Hey! We have a very similar request that will be released with the upcoming version here: #4003.

I'll add zip code and street to the list of things we need to integrate there - date of birth is already part of the updated list.
