### ISSUE TITLE
Diseasevariant by new case

### ISSUE THREAD

**Issue by buelentakcay** [hzi-braunschweig/SORMAS-Project#4751]
**Description:** It is described in the SORMAS version 1.56.1 manual from 08.03.2021 in the **_section "2.1.2 New case"_**, that in the SORMAS **_web app_** version 1.56.1 next to the field **_"disease"_** in the **_field D (disease variant)_** if necessary a _**"mutation variant"**_ can be entered.
But upon checking, I found that the **_"D (disease variant)"_** field is not present in SORMAS version 1.56.1.

**Expected Behavior:** In the popup Create new case, an input field "Disease variant" is expected....

<img width="390" alt="sormas-web-app-new-case-version-1 56 1" src="https://user-images.githubusercontent.com/13380691/110954999-6842ed80-8349-11eb-9d7d-b80abd2a9e93.PNG">
<img width="173" alt="sormas-web-app-version-1 56 1" src="https://user-images.githubusercontent.com/13380691/110955019-6e38ce80-8349-11eb-8a2b-3822042d0f33.PNG">
<img width="102" alt="sormas-db-schema-version-1 56 1" src="https://user-images.githubusercontent.com/13380691/110955044-742eaf80-8349-11eb-9c79-a28399e59f62.PNG">
<img width="229" alt="sormas-handbook-version-1 56 1" src="https://user-images.githubusercontent.com/13380691/110955059-78f36380-8349-11eb-8e94-61beee0c13d2.PNG">
<img width="502" alt="sormas-handbook-new-case-version-1 56 1" src="https://user-images.githubusercontent.com/13380691/110955078-7e50ae00-8349-11eb-8dc4-24c267a73f2a.PNG">

**Comment by MateStrysewske** [comment]
@buelentakcay Hey! The disease variant first has to be added to the database, as described in this guide: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/GUIDE_ADD_NEW_DISEASE_VARIANT.md
