### ISSUE TITLE
Add contact person details to facilities [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4755]
### Situation Description
Thus far, users cannot deposit contact person details in regards to facilities. However, this is useful when trying to get in touch with the facility staff or specific contact persons.
### Feature Description

- Add contact person details to facilities. Include first name, last name, phone number and email address.
- Add contact person details to the import templates.
- Add facility contact person details to location sections in home address, addresses, events, exposures, activities as case. Place them underneath the respective addresses (cf. screenshot). Only show them, when a facilityType is selected.
- Adopt entries of such fields when a respective facility with deposited contact information is selected in the respective location sections.

### Additional Information
<img width="355" alt="Screen Shot 2021-03-12 at 5 50 34 PM" src="https://user-images.githubusercontent.com/70317594/110979734-48b9be00-8365-11eb-9e15-877a3fa973d8.png">
<img width="701" alt="Screen Shot 2021-03-12 at 7 01 41 PM" src="https://user-images.githubusercontent.com/70317594/110979864-756dd580-8365-11eb-9f27-2802ab21c7f2.png">

### Development Specifications
* Add new fields to the Facility and Location entities:
    * `contactPersonFirstName` (text; caption: Contact person first name)
    * `contactPersonLastName` (text; caption: Contact person last name)
    * `contactPersonPhone` (text; caption: Contact person phone number)
    * `contactPersonEmail` (text; caption: Contact person email address)
* Add the new fields to the facility export
* Add these new fields to the facility and location forms and fragments; only show them in locations when a facility type has been selected
* Add the new fields to the logic that automatically fills a location based on the selected facility

**Comment by bernardsilenou** [comment]
@kwa20  Can we not call it the facility phone number and facility email? I am not sure if we can document the name of a person as an attribute of a facility, because every sormas user  that link an entity to the facility would see the contact persons name.

**Comment by kwa20** [comment]
@bernardsilenou we would actually have both, I just didn't mark it in the square because it'll be done in another issue. Couldn't we use the location of this facility as pseudonymization for these fields for different users?

**Comment by bernardsilenou** [comment]
@kwa20 It it the case that can tell us if the facility should be pseodonymize,  but a user in BS can create a case in a facility in Berlin, so the GE user in BS has full access to the case and that implies all the facility information in Berlin. The BS user had no right to know the name of the contact person in the hospital in Berlin. They should only know the contact of the hospital and  if they later decide to share contact, then that is  due to cordial understanding but not the system should show them the contact.

**Comment by bernardsilenou** [comment]
If the users absolutely need to know the contact details of the contact person in facilities, then they can create their internal phone db or even excel table and tore this information after talking with the facilities.

**Comment by JaquM** [comment]
@bernardsilenou 
In Germany, the law requires that the responsibility for reporting lies with the head physician in the laboratory, for example. This name must be given, including contact details. Therefore, there is a need for Germany to record this data as well within, at least for laboratory facilities. The corresponding contact data are sent in the DEMIS message and should be transmitted.

**Comment by bernardsilenou** [comment]
@JaquM Thanks for the information. Since this is required by law, then perfect, we add please to all facilities and activate for DE instance only.
My comment only applies if it is not required by law.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by kwa20** [comment]
Contact person detailed fields are not hidden in events, exposures and activities as case when something other than facility was selected in type of place

<img width="435" alt="eventsContactPersonAddress" src="https://user-images.githubusercontent.com/70317594/115113830-7f9a7980-9f8c-11eb-8806-2d1ceb9974ef.PNG">

**Comment by MateStrysewske** [comment]
@sergiupacurariu This needs to be fixed; please also check whether it's a problem in the mobile app

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot
