### ISSUE TITLE
Immunizations I: Entities, DTOs and backend logic [5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4756]
### Situation Description
#4081 introduces the full immunization module 
### Feature Description
- [ ]  Add an immunization entity in db with the following attributes:
- disease: required
- report date:  required
- external id free text
- responsible region (optional), district (optional), community
- immunization facility:  we use the default facility class as for case creation without home as option.  We exclude home here because the goal is to capture the organization providing the immunization.
- - expected number of dose  (positive Integer, required adn same validation as for cases 1:10 )
- immunizationStartDate (required)
- immunizationEndDate (required if number of dose >1 and set to end date if dose == 1)
- number of days between doses  (required if number of dose >1): would be used for  immunization followup, but not in this ticket
- immunizationStatus(required, ongoing as default state): ongoing | canceled| completed |
- has person been infected with this disease before? yes |no | unknown if yes
- date of last infection
- general comment
- 
- [ ] Add a form to create new immunization as in figure
   - Trigger duplicate person detection method when creating a new immunization.
   - Duplicate immunization detection
        - After calling duplicate person detection, check for duplicate immunization using the following:
        ` disease, date of report, immunizationStartDate, region, district, facility`.
    This is the same method for duplicate case detection by just replacing symptom onset date with  immunisationStartDate
- It should be possible to create multiple immunization per person but if the disease is the same, then both should not overlap based on end dates.
- Link and display immunization on the person form, just as we have for cases and contacts
### Additional Information
@kay The positions if the text in figures are just for demo, we can place them right 
![image](https://user-images.githubusercontent.com/12996724/110981036-d9dd6480-8366-11eb-9108-8c85fdbee746.png)

![image](https://user-images.githubusercontent.com/12996724/110977358-6174a480-8362-11eb-8150-ce38b86066e2.png)

### Development Specifications
* Add a new `ImmunizationStatus` enum with the following values: `PENDING`, `ACQUIRED`, `NOT_ACQUIRED`, `EXPIRED`
* Add a new `MeansOfImmunization` enum with the following values: `VACCINATION`, `RECOVERY`, `VACCINATION_RECOVERY`, `OTHER`
* Add a new `ImmunizationManagementStatus` enum with the following values: `SCHEDULED`, `ONGOING`, `COMPLETED`, `CANCELED`
* Add a new `Immunization` entity extending `CoreAdo` and the corresponding Dto class with the following fields (in the mobile app, make sure to add the entity to all code in DatabaseHelper that creates, clears or drops the tables):
  * `disease` (not null)
  * `person_id` (not null)
  * `reportDate` (not null)
  * `reportingUser_id`
  * `archived` - boolean
  * `deleted` - boolean
  * `meansOfImmunization` - varchar(255)/MeansOfImmunization (not null)
  * `meansOfImmunizationDetails` - text
  * `immunizationStatus` (not null) - varchar(255)/ImmunizationStatus
  * `managementStatus` - varchar(255)/ImmunizationManagementStatus
  * `externalId` - text
  * `responsibleRegion_id`
  * `responsibleDistrict_id`
  * `responsibleCommunity_id`
  * `country_id`
  * `startDate`
  * `endDate`
  * `validFrom` - date
  * `validUntil` - date
  * `numberOfDoses` - integer
  * `previousInfection` - varchar(255)/YesNoUnknown
  * `lastInfectionDate`
  * `additionalDetails` - text
  * `positiveTestResultDate`
  * `recoveryDate`
  * `relatedCase_id`
* Add basic Facade and Service methods that are necessary for synchronization
* Add a ReST resource with the basic synchronization methods (`getAllImmunizations`, `getByUuids`, `postImmunizations`, `getAllUuids`, `getDeletedUuidsSince`)
* Extend the synchronization logic in the mobile app; always synchronize immunizations AFTER persons (because they have a person reference); don't forget `pullAndRemoveDeletedUuidsSince`
* Pseudonymization is based on the responsible jurisdiction of the immunization
* Users can access all immunizations in their jurisdiction
* Extend the person user filter and getAllAfter method as well as the person resource methods that allow users to retrieve persons they have access to; users also need to have access to persons that are related to immunizations they can access
* Add a new feature configuration: `IMMUNIZATION_MANAGEMENT` , DISABLED by default
* Add new user rights: `IMMUNIZATION_MANAGEMENT_ACCESS` (all user roles that have access to CASE_VIEW), `IMMUNIZATION_VIEW` (all user roles that have access to CASE_VIEW), `IMMUNIZATION_CREATE` (all user roles that have access to CASE_CREATE), `IMMUNIZATION_EDIT` (all user roles that have access to CASE_EDIT), `IMMUNIZATION_DELETE` (all user roles that have access to CASE_DELETE), `IMMUNIZATION_ARCHIVE` (all user roles that have access to CASE_ARCHIVE)

**Comment by bernardsilenou** [comment]
@kwa20 @Candice-Louw  ?

**Comment by kwa20** [comment]
@bernardsilenou I think we only have this specified for COVID right now don't we? Wouldn't we have to specify it for other diseases too? Otherwise the current implementation might be enough for a first step.

**Comment by bernardsilenou** [comment]
@kwa20 Now it is only for COVID, bet we would design it to be generic for all vaccine preventable  diseases. We would add a disease configuration latter.
If nothing major, then I would add the other 2 entities tomorrow. Danke!

**Comment by bernardsilenou** [comment]
@kwa20 I mean the immunization directory and immunization tab beside person form (all ui) and vaccinations entity (which would be what we already have in the db)
have a look at last comment in #1481

**Comment by jesseangelis** [comment]
add country of immunization of top of region and district and set the default value to the server country

**Comment by MateStrysewske** [comment]
@jesseangelis What would be the reason for adding the country to this entity? Shouldn't the jurisdiction fields at the Immunization entity be primarily used to determine who's responsible to manage it (and can therefore see the associated person)?

**Comment by bernardsilenou** [comment]
> @jesseangelis What would be the reason for adding the country to this entity? Shouldn't the jurisdiction fields at the Immunization entity be primarily used to determine who's responsible to manage it (and can therefore see the associated person)?

@MateStrysewske The motivation for this is because in the immunization passport, the country is mentioned, e.g if a person returned to the country while already immunized in another country. Just like events, the region and district of the location is no longer required since the country is not the same as that of the server.

Since this is not a core data for the immunization, it would be good if we put it at the end  of the form instead.

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 I read the specification and have 2 main comments, hope they are useful and not too late:

On figure: create new immunization
  - drop varaibles: 
       - date of symptom onset (becuse most of them would not be cases at the time of data collection)
	   - present condition of person (since we do not immunize death people)
	   - external id 
  - add
	   - report date
	   - immunizationStartDate 
	   - immunizationEndDate
	   - expected number of dose 
	   - country of immunization (similar to case origin and set to default server country)   

Development Specifications
  - `Add a new ImmunizationStatus enum with the following values: , NOT_ACQUIRED, EXPIRED`
  - Is `NOT_ACQUIRED` the opposit of `ACQUIRED` ? Since its not good to  negate a category to get another one,
  Can we just use something like unaquired = {NOT_ACQUIRED or EXPIRED}. 
  - An immunized person can have a known or unknown status, but not  pending, right?
  So categories for ImmunizationStatus can then be ACQUIRED, UNACQUIRED, UKNOWN

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 I read the specification and have 2 main comments, hope they are useful and not too late:

On figure: create new immunization
  - drop varaibles: 
       - date of symptom onset (becuse most of them would not be cases at the time of data collection)
	   - present condition of person (since we do not immunize death people)
	   - external id 
  - add
	   - report date
	   - immunizationStartDate 
	   - immunizationEndDate
	   - expected number of dose 
	   - country of immunization (similar to case origin and set to default server country)   

Development Specifications
  - `Add a new ImmunizationStatus enum with the following values: , NOT_ACQUIRED, EXPIRED`
  - Is `NOT_ACQUIRED` the opposit of `ACQUIRED` ? Since its not good to  negate a category to get another one,
  Can we just use something like unaquired = {NOT_ACQUIRED or EXPIRED}. 
  - An immunized person can have a known or unknown status, but not  pending, right?
  So categories for ImmunizationStatus can then be ACQUIRED, UNACQUIRED, UKNOWN

**Comment by MateStrysewske** [comment]
@bernardsilenou The mockups are pretty outdated - please refer to the creation form issue and post your suggestions there if they're still valid after checking the development specifications (#4764)

NOT_ACQUIRED and EXPIRED are two semantically very different statuses. EXPIRED means that immunization has been acquired at some point, but is no longer valid. NOT_ACQUIRED means that immunization has never been acquired in the first place.

PENDING means that immunization is currently in the process of being acquired, e.g. for Covid-19, you need (most of the time) two vaccinations before you've acquired immunization. You'd have the PENDING status before you get your second vaccination.

Please consult @kwa20 and @JaquM internally if you have further suggestions and verify that they are in line with their definitions.

**Comment by StefanKock** [comment]
Was merged yesterday

**Comment by MateStrysewske** [comment]
Synchronization is broken because there are methods defined in ImmunizationFacadeRetro that aren't implemented in ImmunizationResource (getAllArchivedSince and getAllDeletedSince).

**Comment by MateStrysewske** [comment]
Please change the data type of the `meansOfImmunizationDetails` and `additionalDetails` fields from `varchar(512)` to `text` as specified in the issue description

**Comment by StefanKock** [comment]
Still a PR open, was accidently closed by automation
