### ISSUE TITLE
[SurvNet Interface] Make activityAsCase compatible for IfSG reporting (DE only) [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4761]
See here for implementation details: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4761#issuecomment-800337829

### Feature Description
Case > epiData > activityAsCase
### Problem Description
The newly added element activityAsCase turns out to only partially fulfill the requirements of needed variables to allow a proper and clear mapping to the SurvNet interface. The mapping would be quite complicated and not very intuitive for users to fill when being used to a different structure and set of values.
### Proposed Change

- Hide "type of activity" only on german servers. Instead, show the following field:
- Add a DE only enum "Activity" with the following values:
    - Working at
    - Accommodated in
    - Cared for in
    - Unknown

- Hide "Role" only on german servers.
- Hide "type of place" only on german servers. Instead, show the following field:
- Add a DE only enum "Facility (IfSG)" in the location section with the following values:
    - Facility (§ 23 IfSG)
    - Community facility (§ 33 IfSG)
    - Facility (§ 36 IfSG)
    - Unknown
- Always show facility fields for this element on german servers.

- Show "Activity" and "Facility (IfSG)" on the overview table instead of "type of activity" and "type of place".
- Don't make any field compulsory. If this is not possible, make "Activity" the single compulsory field.

### Additional Information
Updated:
<img width="524" alt="Screen Shot 2021-03-18 at 9 44 18 AM" src="https://user-images.githubusercontent.com/70317594/111597597-9c496300-87ce-11eb-81bf-f79796853256.png">

<img width="694" alt="Screen Shot 2021-03-14 at 6 46 06 PM" src="https://user-images.githubusercontent.com/70317594/111080628-99651e80-84ff-11eb-8141-4c06c8ca7226.png">

**Comment by bernardsilenou** [comment]
@kwa20 
The variable `type of activity`, `Role` and additional categories under `type of place` were added in SORMAS because of DE.
If they are no longer needed, then I think it would be better that we reconfigure the exposure. Before we hide a variable, we have to make sure that the variables that we are hiding and all its options are absolutely needed for another instance.
What do you think please?

**Comment by kwa20** [comment]
@bernardsilenou the only field that was really added overall was "roles", type of activity and type of place belonged to the usual Sormas exposures before as well. The initial plan to keep it close to exposures was to make it available to all users and not make a whole element DE only. However, we unfortunately face the problems described above now and it's hard to proceed like we have it now. If we make this DE only, I'd prefer to disentangle it.

**Comment by Candice-Louw** [comment]
@bernardsilenou - From a non-DE point of view, it makes sense to make the "IfSG" and "Activity" sections DE-only as proposed, as it is very much German law that dictates these requirements.  The two fields are also related to each other in the SurvNet mapping, and they are relevant only for DE instances/law.  From a CH perspective, using the other values as they currently are, is perfect.

In summary - 

**Two enums are added and visible only on DE servers:**
1. 
Add a DE only enum "Activity" with the following values:
Working at
Accommodated in
Cared for in
Unknown

2.
Add a DE only enum "Facility (IfSG)" in the location section with the following values:
Facility (§ 23 IfSG)
Community facility (§ 33 IfSG)
Facility (§ 36 IfSG)
Unknown

**Existing fields are hidden on DE servers:**
"Type of Activity"
"Role"
"Type of Place"

**Update the columns in the overview/list for DE servers to display only:**
1. and 2., Date, Address, Description

Showing the existing values for other instances stays as is.

**Comment by MateStrysewske** [comment]
This needs to be refined (by us for now) because I'm heavily against adding enums that are only used in one country if we can avoid it.

**Comment by kwa20** [comment]
@MateStrysewske I think we already have country specific enums for CH too right? Is the problem the naming of the enum header and values? We could make the naming more generic in english and then adjust it through translation in the DE context.

**Comment by bernardsilenou** [comment]
@kwa20 
When i say variables were added I mean in at lest one year time in the past. Some of the categories/ enums you find under type of place, and type of activities were added because of DE. 
Can we not have an internal refinement on this? I have a feeling that we need to redefine the the activity as a case entity in case ti does not address the need it was meant for.

**Comment by MateStrysewske** [comment]
Implementation details:

* Add `CARED_FOR` as a new value to `ActivityAsCaseType`; only visible for German systems
* Add `FACILITY_23_IFSG` ("Facility (§ 23 IfSG)"), `COMMUNITY_FACILITY` ("Community facility (§ 33 IfSG)") and `FACILITY_36_IFSG` ("Facility (§ 36 IfSG)") as new values to `TypeOfPlace`; only visible for German systems
* Hide AcvitityAsCaseDto.role on German systems (by adding the `@HideForCountries` annotation to the field)
* Only show the following ActivityAsCaseType values for German systems: WORK, HABITATION, CARED_FOR, UNKNOWN
* Don't show the new type of place value in any place in the applications EXCEPT for the activity as case forms; in those, for German systems, ONLY show the following values: FACILITY_23_IFSG, COMMUNITY_FACILITY, FACILITY_36_IFSG, UNKNOWN
* All of the TypeOfPlace values above (except for UNKNOWN) need to enable the facility fields in the location

Captions (for the fields and table columns, which are calculated based on the field captions) need to be taken care of in Crowdin.

@kwa20 @Candice-Louw Is that okay for you?

**Comment by kwa20** [comment]
@MateStrysewske Looks good to me! If I understand correctly, these adjustments will also then be independent of other similar enums like type of place or type of activity in events or exposures right? For example: I would be able to translate exposureType.HABITATION in a slightly different way than activityAsCase.HABITATION?

**Comment by MateStrysewske** [comment]
@kwa20 ExposureType and ActivityAsCaseType are two different enums already, yes. We'll not introduce a new enum for the IfSG elements though. TypeOfPlace is re-used in both exposures and activities as case and thus can't be named individually.

**Comment by kwa20** [comment]
@MateStrysewske @syntakker Just noticed this on the mock-up, could we please also keep OTHER displayed in ActivityAsCaseType?

**Comment by syntakker** [comment]
@kwa20 @MateStrysewske but otherwise this issue is ready for implementation?

**Comment by kwa20** [comment]
@syntakker Sorry, yes :)

**Comment by syntakker** [comment]
@MateStrysewske `ActivityAsCaseDto.role` already has annotation `@HideForCountriesExcept`, with `@HideForCountries` it would not be available at all anymore.
So I would suppose the property can be removed?

**Comment by MateStrysewske** [comment]
@kwa20 Do you remember why we set the role to be only visible for Germany in exposures? Doesn't really sound like a good idea to me in hindsight since it might be relevant information for other countries as well. Do you agree with making the role field available for all countries in exposures, and available for all countries except Germany in activities as case?

**Comment by kwa20** [comment]
@MateStrysewske I think we might've done it because it was initially related to specific german needs but I agree that the roles might be relevant to everyone. So yes, I think we should go with your suggestion.

**Comment by MateStrysewske** [comment]
@syntakker See my last comment :)

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of Sormas 1.58.0-snapshot on the test-de.sormas.netzlink.com environment
