### ISSUE TITLE
Cases and Contacts > Translation adjustments for CH MED V2

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4762]
### Feature Description
For the CH MED V2, new translations are required to adjust to the MED V2 as stipulated by the BAG.

### Problem Description
Change the following values in the SORMAS UI:

Table_case
·         Testgrund: Variabeln Namen neu (pcr_reason -> test_reason), pcr_reason_other und pcr_reason_ct gelöscht, neu: test_reason_convenience
·         Neue Variable exp_type
·         Neue Variable: exp_loc_dt
·         **reason_quar: Coding neu: 1=Kontakt zu bestätigtem Fall**, 2=Einreise aus Risikostaat, 3=Ausbruchsuntersuchung, 4= SwissCovidApp-Meldung, 5=anderer Grund
·         Neue Variable: onset_iso_dt
·         **reason_end_of_iso: Coding neu: 1=Erfüllt die definierten Kriterien**, 2=Tod, 3=Lost to follow-up, 4=anderer
·         Neue Variable: vacc_yn 
·         Neue Variable: vacc_name
·         Neue Variable: vacc_dt_first
·         Neue Variable: vacc_dt_last

Table_contact:
·         Neue Variabeln:
·         exp_type
·         test_reason_symptoms
·         test_reason_quarantine
·         test_reason_quarantine_end
·         other_test_reason
·         exp_loc_dt
·         **reason_end_quar: Coding neu: 1=Nicht symptomatisch am Ende der vorgeschriebenen Zeitspanne**, 2=Isoliert als Fall, 3=Lost to follow-up, 4=anderer**
·         Neue Variable: vacc_yn 
·         Neue Variable: vacc_name
·         Neue Variable: vacc_dt_first
·         Neue Variable: vacc_dt_last

### Additional Information
Adjustment required based on: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4549

**Comment by Candice-Louw** [comment]
Updates made in CrowdIn and tested on nightly-build server on 15.03.2021.

IP:
![image](https://user-images.githubusercontent.com/65529128/111091198-7142e300-8532-11eb-9e09-ddf53e9b0707.png)
![image](https://user-images.githubusercontent.com/65529128/111091215-8586e000-8532-11eb-91cc-a2626341c796.png)

KP:
![image](https://user-images.githubusercontent.com/65529128/111091237-9a637380-8532-11eb-9396-6e752740f1fa.png)

**Comment by MateStrysewske** [comment]
@Candice-Louw Since translations don't have anything to do with this repository, would it be possible for you to document these issues somewhere else?
