### ISSUE TITLE
Immunizations II: Vaccination entity [3]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4763]
### Situation Description
Issue #4081 introduces the general immunization entity. An immunization is associated to a person, and has one or more vaccination entities. If we assume that immunization is like contacts, then vaccinations are like followup visits of the contact.
Would be good to read the associated issues before working on this.
### Feature Description
- [x]  Add a vaccination entity in the db and link it to Immunization. The relationship is 1 immunization -> n vaccination
- Activate this for covid only for now and for all instances. But this is a module to be later activated for all vaccine preventable diseases.
- [x]  Attributes of vaccination
- Use the `additional medical information section`, exactly as for cases. We can use the same ‘class/ object’ 
- Pregnancy: yes no unknown (remember the validation that exist)
- Postpartum
- Trimester 
- `date of report` (validation: should not be in future of current date) 
- `date of dose expiration` ( can be current date or in future but not after expected end of immunization)
- vaccine name
- manufacturer
- vaccine type
- vaccine dose
- inn (international nonpropriotory name)
- batch number
- uni code
- atc code
- source of vaccination

### Development Specifications
* Add a new `Vaccination` entity (since there is already a Vaccination enum that will be removed in the refactoring issue, call the class VaccinationEntity for now, table should already be called Vaccination though) extending AbstractDomainObject and the corresponding Dto class with the following fields (in the mobile app, make sure to add the entity to all code in DatabaseHelper that creates, clears or drops the tables); most of them can be copied over from the VaccinationInfo class
  * immunization_id (not null)
  * healthConditions_id (not null)
  * reportDate (not null)
  * reportingUser_id
  * vaccinationDate
  * vaccineName - varchar(255)/Vaccine
  *  otherVaccineName - text
  * vaccineNameDetails - text
  * vaccineManufacturer - varchar(255)/VaccineManufacturer
  * vaccineManufacturerDetails - text
  * otherVaccineManufacturer - text
  * vaccineType - text
  * vaccineDose - text
  * vaccineInn - text
  * vaccineBatchNumber - text
  * vaccineUniiCode - text
  * vaccineAtcCode - text
  * vaccinationInfoSource - varchar(255)/VaccinationInfoSource
  * pregnant - varchar(255)/YesNoUnknown
  * trimester - varchar(255)/Trimester
* Mobile app entity needs the annotation `@EmbeddedAdo` to synchronize them automatically alongside immunizations
* Extend the immunization entity and DTO with vaccination lists (loaded via mapping, see e.g. epi data <-> exposure relation; make sure that orphanRemoval is true)
* Extend the change date filters of immunizations to take into account the associated vaccinations
* Add Facade and Service classes with the necessary methods; synchronization methods are not necessary because vaccinations don't have their own ReST resource
* Pseudonymization is based on the immunization

**Comment by bernardsilenou** [comment]
Before implementing this, we need to first add the feature to define vaccinations without the need to have a new sormas version, similar to what we have for disease variant.

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  Question pls:
When creating vaccinations for cases and contacts, with this new model, the users would then need to document the facility of the immunizations which can be different from that of the case. When creating a case, the goal is to document the facility of case, not to additionally ask for the immunization facility.
Can you think of a better solution rather than making the facility of the immunization optional when the person is linked to either a case, contact or ep?

**Comment by MateStrysewske** [comment]
@bernardsilenou I would actually always make the infrastructure fields for immunizations optional anyway.

**Comment by DavidBaldsiefen** [comment]
I have made some changes to the specifications, @MateStrysewske please comment if you disagree:

New field: `otherVaccineManufacturer` (text)

Changed field names: 

`inn` -> `vaccineInn`
`batchNumber` -> `vaccineBatchNumber`
`uniiCode` -> `vaccineUniiCode`
`atcCode` -> `vaccineAtcCode`

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Looks good to me!

**Comment by DavidBaldsiefen** [comment]
Reopened due to missing columns in the Database:

```
vaccineType (text)
vaccineDose (text)
```

These need to be added both in `sormas_schema.sql` and `DatabaseHelper.java`

**Comment by MateStrysewske** [comment]
Reopened because of a bug in `setVaccineManufacturerDetails` in the Android app (parameter is assigned to itself).

**Comment by MateStrysewske** [comment]
Additionally, the following code in VaccinationFacadeEjb.toDto can lead to a NPE:

`dto.setReportingUser(entity.getReportingUser().toReference());`

Should actually be:

`dto.setReportingUser(UserFacadeEjb.toReferenceDto(entity.getReportingUser()));`
