### ISSUE TITLE
Notification to the responsible user when an event is integrated into a group 

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4767]
### Situation Description
Development related to #4570 #4571 #4572 #4573 consisting of grouping events together.

### Feature Description

Development consists of sending a notification to all the users responsible for the events included in a group.
More specifically, when the user responsible for event B creates a group for events A, B and C, users for events A and C will receive an email notification indicating:
- The title and ID of the group created
- The list of events integrated into the group
- The list of recipients of the notification sent by the system

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 
should the same notification be sent when an event is added to an existing group ?

**Comment by bernardsilenou** [comment]
@ftavin I suggest we send the notification when event is added or dropped from a group.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Dev France would work for this in 1.59

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 
I think it would be interesting to add the name of the user who created the group to the notification.

**Comment by carolinverset** [comment]
> @carolinverset @bernardsilenou
> I think it would be interesting to add the name of the user who created the group to the notification.

Absolutely :-) !!

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 
Regarding the addition or removal of an event in an existing group, should we notify the responsible users of all the events of the group or just the one of the added/removed event?

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @emond-fuseau
I think it is relevant to inform all users when the scope of the group changes, whether for the addition or deletion of an event.

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 

So I propose the following texts for the notifications:

```
Subject : Creation of an Event Group
New Event Group #TITLE# (#REF#) created by #USER#.

Here is a summary of the Events contained in the Event Group:
* Event #REF# (responsible user : #USER#)
* Event #REF# (responsible user : #USER#)
```

```
Subject : Event added to Event Group

Event #REF# added to Event Group #TITLE# (#REF#) by #USER#.

Here is a summary of the Events now contained in the Event Group:
* Event #REF# (responsible user : #USER#)
* Event #REF# (responsible user : #USER#)
```

```
Subject : Event removed from Event Group

Event #REF# removed from Event Group #TITLE# (#REF#) by #USER#.

Here is a summary of the Events now contained in the Event Group:
* Event #REF# (responsible user : #USER#)
* Event #REF# (responsible user : #USER#)
```
