### ISSUE TITLE
Manually triggered calculation of case classification [3]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#4770]
Further informations in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4770#issuecomment-832503288

### Situation Description
For Germany only, the case classification should be calculated according to the RKI standards, when clicking a button "calculate" which is next to the case classification

The calculation must be based on the information available in each case. 
Belongs to #3004
### Feature Description
 
|Case category| Case definition |Description| Calculation basis|
|-|-|-|-|
|B.| Clinical-epidemiologically confirmed disease|Clinical picture of COVID-19, without laboratory diagnostic evidence but with epidemiological confirmation.| Clinical picture fulfilled 	but no positive sample (positive rapid antigen detection WITHOUT laboratory can be positive)|
|C.|Clinical-laboratory diagnostic confirmed disease|Clinical picture of COVID-19* and laboratory diagnostic evidence by nucleic acid detection or pathogen isolation (C1) or laboratory diagnostic evidence by antigen detection (C2)|	 Clinical picture fulfilled 	AND 	Positive PCR sample 	OR 	Positive antigen detectionfrom laboratory 	OR 	Positive pathogen isolation |
|D.|Laboratory-diagnostically proven infection if the clinical picture is not fulfilled|	Laboratory diagnostic evidence by nucleic acid detection or pathogen isolation (D1) or laboratory diagnostic. Detection by antigen detection (D2) in the presence of a known clinical picture that does not meet the criteria for COVID-19|	Clinical picture NOT fulfilled (all other symptoms without the ones for clinical picture) 	AND 	Positive PCR sample 	OR  Positive antigen detection from laboratory 	OR  Positive pathogen isolation |
|E.|Laboratory-diagnostically proven infection with unknown clinical picture|	Laboratory diagnostic detection by means of nucleic acid detection or pathogen isolation (E1) or laboratory diagnostic detection by means of antigen detection (E2) in the absence of information on the clinical picture (not ascertainable or not collected).|  Clinical picture unknown AND  Positive PCR sample 	OR  Positive antigen detectionfrom laboratory OR  Positive pathogen isolation |
|

*Clinical picture: 
at least one of the following symptoms:

- Acute respiratory symptoms of any severity:
      - cough
      - pneumoniaClinicalOrRadiologic
      - acuteRespiratoryDistressSyndrom
      - respiratoryDiseaseVentilation
      - difficultyBreathing
- new-onset loss of smell or taste:
     - lossOfTaste
     - lossOfSmell
- disease-related death

### Additional Information
@kwa20 

To do:
=> Remove validation 
=> Add "calculate" option
=> In Germany automatic caseclassification = false

### Development Specifications
* Extend the CaseClassificationFacadeEjb.buildCriteria method with ClassificationCriteriaDto for the two case classifications CONFIRMED_NO_SYMPTOMS and CONFIRMED_UNKNOWN_SYMPTOMS; only consider them for German servers
* Add a new extension of ClassificationCriteriaDto called `ClassificationAllSymptomsCriteriaDto` which is passed the SymptomsDto and a SymptomState and goes through all symptoms where the `@Diseases` annotation contains the disease in question and checks whether the value matches the given SymptomState; the eval method returns true if all symptoms match the SymptomState and false if at least one symptom does not match the SymptomState; should also be possible to call this criteria with null in which case it verifies that all symptoms have no value
* Extend the CaseClassificationFacadeEjb.buildCriteria method with code to build the classification criteria for CORONAVIRUS according to the following specifications; only do this for German servers
  * **SUSPECT:** at least one of the following symptoms: `pneumoniaClinicalOrRadiologic`, `difficultyBreathing`, `cough`, `runnyNose`, `respiratoryDiseaseVentilation`, `acuteRespiratoryDistressSyndrome`, `lossOfTaste`, `lossOfSmell`
  * **PROBABLE:** suspect + either epidemiological confirmation = YES (use ClassificationCaseCriteriaDto) or case is linked to an event with EventStatus CLUSTER (new ClassificationCriteriaDto needed for this)
  * **CONFIRMED:** suspect + a positive test result for CORONAVIRUS with the pathogen test types `PCR_RT_PCR`, `ANTIGEN_DETECTION` , `ISOLATION` or `SEQUENZING`
  * **CONFIRMED_NO_SYMPTOMS:** a positive test result (see above) and EITHER all symptoms that are enabled for Covid-19 set to false (use the new ClassificationAllSymptomsCriteriaDto) OR at least one of the following symptoms set to true: `fever`, `generalSignsOfDisease`, `diarrhea`, `fastHeartRate`, `rapidBreathing`, `oxygenSaturationLower94`, `vomiting`, `chillsSweats`
  * **CONFIRMED_UNKNOWN_SYMPTOMS:** a positive test result (see above) and all symptoms that are enabled for Covid-19 set to unknown or null (use the new ClassificationAllSymptomsCriteriaDto)
* Remove the (currently unused) logic that validates the case classification for Covid-19 cases on German systems
* Add a "Calculate" button next to the case classification that can be pressed to manually trigger a re-calculation of the case classification (same logic that is called when saving a case); this button should be visible irrespective of whether or not automatic case classification is turned on for the server; should only be visible if the user has the user right CASE_CLASSIFY

**Comment by JonasCir** [comment]
Hm I feel there is a duplicate for this one already :)

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by maxiheyner** [comment]
- Add a checkbox to avoid sending this case to SurvNet - in GERMAN call this box please "Senden an Meldesoftware erfolgt in anderem Landkreis".
- Implement a logic that checking this box leads to a warning for the user that "this case actively is prevented from sending to SurvNet". 
- Add a bulk action function to prevent the checked cases from sending to SurvNet (name this action "Senden an Meldesoftware erfolgt in anderem Landkreis")
- Add a filter for cases which are not supposed to be send to SurvNet (checked - see above) at the case directory
- Prevent also these cases that are part of an event cluster from sending to SurvNet when this mentioned box is checked

**Comment by markusmann-vg** [comment]
The comment from @maxiheyner is covered by a new issue and is NOT part of this one!
https://github.com/hzi-braunschweig/SORMAS-Project/issues/5324

**Comment by MateStrysewske** [comment]
@JaquM I've updated the development specifications based on the currently disabled case classification validation logic for German systems. I guess the clinical picture part is not up-to-date. Can you please update the clinical picture for Covid-19 based on the exact symptoms that we have in the system?

**Comment by JaquM** [comment]
@MateStrysewske I've updated the exact symptoms
Everything else is up-to-date.

**Comment by MateStrysewske** [comment]
@JaquM Thanks! Can you check whether the development specifications I have added to the initial issue are correct and complete? Not sure whether the "clinical picture not fulfilled" part means that ONLY the symptoms of the clinical picture should be set to false/unknown/null (sounds like it) or whether ALL symptoms possibly related to Covid-19 should be false/unknown/null (like it's implemented in the unused validation right now)?

**Comment by kwa20** [comment]
@MateStrysewske @JaquM I noticed some inconsistencies which we should refine:

- SUSPECT is not category B. but category A., the specification for the calculation, however, is the correct one.
- Add a calculation for PROBABLE (category B.):  suspect condictions + `epidemiologicalConfirmation` = YES and/or a link to an event of `eventStatus` = CLUSTER
- I think implementing the automatic calculation also being triggered when saving would result in users being able to edit the case classification only for it to be changed again upon saving the case. This could cause confusion. How would we handle that?

**Comment by MateStrysewske** [comment]
@kwa20 The automatic case classification during save can be disabled on German systems (probably is already). If it's enabled and the user has overwritten the classification manually, the automatic classification will never overwrite it with a lower value again (only with a higher one). I think NO_CASE overwrites everything in that logic already.

**Comment by kwa20** [comment]
I just tested this issue on the nightly build server and found the following things:
- classifications 'confirmed - no symptoms' and 'confirmed - unknown symptoms' do not get properly calculated either automatically nor via manual trigger.
    - if all symptoms are set to 'no' or 'unknown', the case classification is set to 'not yet classified'.
    - if at least one symptom is set to either 'no' or 'unknown', the case classification is set to 'not yet classified'.

- I also couldn't find many of the strings in the info pop-up available on crowdin. @sergiupacurariu Do you think we could add them so I can adjust some translations there, please? 

- I further noticed that the calculation now contradicts the setting of confirmed cases when entering a positive test result. When a user enters a positive test result for a case, they're asked if they want to confirm the case. The case is then set to confirmed, even if entered data in symptoms should classify them as either 'confirmed - no symptoms' or 'confirmed - unknown symptoms'. I'm not sure if this could be handled with this calculation or if this needs to be an issue purely related to the other pop-up in samples. Please let me know :)

**Comment by StefanKock** [comment]
Found by @syntakker : Minor finding: Automated recalculation for case classification is not triggered when a cluster event is unlinked (for classification "suspect" + cluster event => "probable", unlink cluster event =>"suspect")

**Comment by sergiupacurariu** [comment]
When a cluster event is unlinked from a case, the case is not saved. The automatic calculation is triggered only if the case is saved. In case the event is unlinked the user could use the "Calculate case classification" button to manually trigger the calculation.

**Comment by JaquM** [comment]
@sergiupacurariu we please need to add "sore throat / pharyngitis" as symptom for the clinical picture.
I'm sorry for this last minute change.

**Comment by sergiupacurariu** [comment]
@JaquM In the classification rules we have two sets of symptoms: 
- **first set:** - Pneumonia (clinical or radiologic), Difficulty breathing/Dyspnea, Cough, Runny nose, Respiratory disease requiring ventilation, Acute respiratory distress syndrome, New loss of taste, New loss of smell. This set is used for: suspect, probable and confirmed
- **second set:** - Fever, Diarrhea, Fast heart rate (Tachycardia), Rapid breathing, Oxygen saturation < 94 %, Vomiting, Chills or sweats. This set is used for Confirmed classification - Unknown symptoms.
Please let me know if this new symptom goes in both sets or only in one of them. Thank you!

**Comment by JaquM** [comment]
@sergiupacurariu the first set please

**Comment by RazvanHodisan** [comment]
Verified on Local and https://test-de.sormas.netzlink.com/, Version: 1.61.0-SNAPSHOT
