### ISSUE TITLE
Age is not sorted properly in list of EP

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4774]
### Bug Description

If you click on the header of the age in the list of the EP the numbers are wrongly sorted as in these screenshot:

![grafik](https://user-images.githubusercontent.com/74791118/111158647-936f4c00-8598-11eb-8d0e-479f7af057a3.png)

As its working fine in the list of contacts and cases, it could be a bug or a missing configuration.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.58.0-snapshot on test.sormas.netzlink.com
