### ISSUE TITLE
Add continent and subcontinent entities [2]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4775]
### Situation Description
Concept issue: #4658 

For exposures (and later maybe for other use cases), users need to be able to not only specify a country, but also a continent or subcontinent in case they don't know the exact name of the country they have traveled to or have traveled to multiple countries.

### Feature Description
Add two new entities to SORMAS:

- [x] Add a new `Continent` entity that extends `InfrastructureAdo`
    * Fields: `defaultName` (text), `externalId` (text)
- [x] Add a new `SubContinent` entity that extends `InfrastructureAdo`
    * Fields: `defaultName` (text), `externalId` (text), `continent` (reference)
- [x] Add a new field to the `Country` entity: `subContinent` (reference)
- [x] Add facades and services for the new entities
- [x] Add logic to synchronize the new entities to the mobile app; this includes extending the InfrastructureSyncDto

**Comment by Candice-Louw** [comment]
@BarnaBartha - please note minor grammatical changes to some of the subcontinents for consistency for example "Northeast Africa/Asia/Europe" (new) vs. "North Eastern Africa/Asia/Europe" (old).  The sheet has been updated with these.

Old | New
--  | --
North Eastern | Northeast
North Western | Northwest
South Eastern | Southeast
South Western | Southwest

Apologies for the tardiness.  In the interest of time, if not possible to change for English, no problem.

List of countries to subcontinents (using updated values) here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4782#issuecomment-801263814
