### ISSUE TITLE
Add continent and subcontinent information to user interface [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4776]
### Situation Description
Concept issue: #4658 
Pre-requisite: #4775

For exposures (and later maybe for other use cases), users need to be able to not only specify a country, but also a continent or subcontinent in case they don't know the exact name of the country they have traveled to or have traveled to multiple countries.

### Feature Description
Extend the user interface (only web app) with the following elements:

- [x] Add a `Subcontinents` view to the Configuration menu (to the left of Countries)
    * Add a grid containing all subcontinents in the database
    * Add a button to create a new subcontinent
    * Add an edit form that is used when editing an existing subcontinent or when creating a new one; Continent needs to be read-only when editing an existing entry
    * Add bulk-editing controls
- [x] Add a `Continents` view to the Configuration menu (to the left of Subcontinents)
    * Add a grid containing all continents in the database
    * Add a button to create a new continent
    * Add an edit form that is used when editing an existing continent or when creating a new one
    * Add bulk-editing controls
- [x] Extend the edit form for countries with a new field that contains the `subContinent`; read-only when editing an existing entry
- [x] Extend the country grid with a column containing the subcontinent
- [x] Add two translation property files: `continents.properties` and `subcontinents.properties` that contain the English names for the continents and subcontinents; use the default name as the identifier, e.g. continent.AMERICA.name and subcontinent.NORTH_AMERICA.name (see this sheet for a list of continents and subcontinents that we're using: https://docs.google.com/spreadsheets/d/1ejttFVpS9HEavP2kWM5lrHgLS1T4j38tSDaKQBbLBpI/edit?usp=sharing)
- [x] Extend `I18nProperties` with methods to retrieve a continent/subcontinent name by its default name (similar to `getCountryName`)
- [x] Use this method to display the translated name in the UI

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version deployed 1.58.0-snapshot on test.sormas.netzlink.com
