### ISSUE TITLE
Add imports for continents and subcontinents and extend infrastructure imports [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4782]
### Situation Description
Concept issue: #4658 
Pre-requisite: #4775 & #4776

For exposures (and later maybe for other use cases), users need to be able to not only specify a country, but also a continent or subcontinent in case they don't know the exact name of the country they have traveled to or have traveled to multiple countries.

### Feature Description
We need import and default import functionalities for the new entities and also need to extend the existing infrastructure import to allow users to associate countries with subcontinents by re-importing them.

- [x] Add a checkbox to the import layout of infrastructure imports: "Overwrite existing entries with imported data"; place it above the "Start import" button
    * Add an info icon next to it that displays the following text on hover: "Select this option if existing data should be overwritten with data from the import file. If an existing entry (based on the name) is found, all data will be updated with the content of the import file (if available). If no existing entry is found, a new one will be created."
- [x] When this checkbox is checked, during the import, if an existing entry is found (e.g. because the logic searches for a health facility with the same name in the specified district), instead of rejecting the entry and adding it to the error log, update the existing entry in the database with the information from the import file; only do this if the import file contains data for the respective field (i.e. don't overwrite existing data with null)
- [x] Replace `sormas_import_all_countries.csv` with an updated version that associates all countries with an appropriate subcontinent; the file will be provided by @JaquM and @Candice-Louw 
- [x] Add an import functionality for continents and subcontinents (similar to the existing import functionalities for infrastructure data)
- [x] Add a default import for continents and subcontinents similar to the default import for countries; defaults can be taken from this sheet: https://docs.google.com/spreadsheets/d/1ejttFVpS9HEavP2kWM5lrHgLS1T4j38tSDaKQBbLBpI/edit?usp=sharing

[sormas_import_all_countries.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6149871/sormas_import_all_countries.zip)

**Comment by Candice-Louw** [comment]
Updated file: 
[sormas_import_all_countries_CL.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6158202/sormas_import_all_countries_CL.zip)

Not sure if the integrity (UTF-8) was maintained, so raw list below.

Notes:
+ Ivory Coast - CIV - Western Africa = is in SurvNet list, not in SORMAS list.  Please see if I missed it or if new var needed?  Will create issue if instructed.
+ Kosovo - XXK - Southeast Europe = is in SurvNet list, not in SORMAS list.  Please see if I missed it or if new var needed? Will create issue if instructed.

SurvNet converter team:
+ New Caledonia (NCL)[SORMAS]  falls under France [SurvNet]: 0 . 1. 41129032 . Neukaledonien .  . 3815 . 17187 . 1025 . 17155 . 21000518
+ Greenland (GRL)[SORMAS] falls under Denmark [SurvNet]
+ Tokelau (TKL)[SORMAS] falls under New Zealand [SurvNet]


defaultName | externalId | isoCode | unoCode | archived | subContinent
-- | -- | -- | -- | -- | --
Afghanistan | 8501 | AFG | 4 | FALSE | Southern Asia
Albania | 8201 | ALB | 8 | FALSE | Southeast Europe
Algeria | 8304 | DZA | 12 | FALSE | Northwest Africa
Andorra | 8202 | AND | 20 | FALSE | Western Europe
Angola | 8305 | AGO | 24 | FALSE | Southwest Africa
Antigua and Barbuda | 8442 | ATG | 28 | FALSE | Central America
Argentina | 8401 | ARG | 32 | FALSE | South America
Armenia | 8560 | ARM | 51 | FALSE | Middle East
Australia | 8601 | AUS | 36 | FALSE | Australia (subcontinent)
Austria | 8229 | AUT | 40 | FALSE | Central Europe
Azerbaijan | 8561 | AZE | 31 | FALSE | Middle East
Bahamas | 8402 | BHS | 44 | FALSE | Central America
Bahrain | 8502 | BHR | 48 | FALSE | Southwest Asia
Bangladesh | 8546 | BGD | 50 | FALSE | Southern Asia
Barbados | 8403 | BRB | 52 | FALSE | Central America
Belarus | 8266 | BLR | 112 | FALSE | Eastern Europe
Belgium | 8204 | BEL | 56 | FALSE | Western Europe
Belize | 8419 | BLZ | 84 | FALSE | Central America
Benin | 8309 | BEN | 204 | FALSE | Western Africa
Bhutan | 8503 | BTN | 64 | FALSE | Southern Asia
Bolivia (Plurinational State of) | 8405 | BOL | 68 | FALSE | South America
Bosnia and Herzegovina | 8252 | BIH | 70 | FALSE | Southeast Europe
Botswana | 8307 | BWA | 72 | FALSE | Southern Africa
Brazil | 8406 | BRA | 76 | FALSE | South America
Brunei Darussalam | 8504 | BRN | 96 | FALSE | Southern Asia
Bulgaria | 8205 | BGR | 100 | FALSE | Southeast Europe
Burkina Faso | 8337 | BFA | 854 | FALSE | Western Africa
Burundi | 8308 | BDI | 108 | FALSE | Eastern Africa
Cabo Verde | 8319 | CPV | 132 | FALSE | Western Africa
Cambodia | 8518 | KHM | 116 | FALSE | Southeast Asia
Cameroon | 8317 | CMR | 120 | FALSE | Central Africa
Canada | 8423 | CAN | 124 | FALSE | North America
Central African Republic | 8360 | CAF | 140 | FALSE | Central Africa
Chad | 8356 | TCD | 148 | FALSE | Central Africa
Chile | 8407 | CHL | 152 | FALSE | South America
China | 8508 | CHN | 156 | FALSE | Eastern Asia
Colombia | 8424 | COL | 170 | FALSE | South America
Comoros | 8321 | COM | 174 | FALSE | Eastern Africa
Congo (Brazzaville) | 8322 | COG | 178 | FALSE | Central Africa
Cook Islands | 8682 | COK | 184 | FALSE | Oceania
Costa Rica | 8408 | CRI | 188 | FALSE | Central America
Croatia | 8250 | HRV | 191 | FALSE | Southern Europe
Cuba | 8425 | CUB | 192 | FALSE | Central America
Cyprus | 8242 | CYP | 196 | FALSE | Southeast Europe
Czech Republic | 8244 | CZE | 203 | FALSE | Central Europe
Democratic People's Republic of Korea | 8530 | PRK | 408 | FALSE | Eastern Asia
Democratic Republic of the Congo | 8323 | COD | 180 | FALSE | Central Africa
Denmark | 8206 | DNK | 208 | FALSE | Northern Europe
Djibouti | 8303 | DJI | 262 | FALSE | Eastern Africa
Dominica | 8440 | DMA | 212 | FALSE | Central America
Dominican Republic | 8409 | DOM | 214 | FALSE | Central America
Ecuador | 8410 | ECU | 218 | FALSE | South America
Egypt | 8359 | EGY | 818 | FALSE | Northeast Africa
El Salvador | 8411 | SLV | 222 | FALSE | Central America
Equatorial Guinea | 8301 | GNQ | 226 | FALSE | Central Africa
Eritrea | 8362 | ERI | 232 | FALSE | Northeast Africa
Estonia | 8260 | EST | 233 | FALSE | Northern Europe
Eswatini | 8352 | SWZ | 748 | FALSE | Southern Africa
Ethiopia | 8302 | ETH | 231 | FALSE | Eastern Africa
Fiji | 8602 | FJI | 242 | FALSE | Oceania
Finland | 8211 | FIN | 246 | FALSE | Northern Europe
France | 8212 | FRA | 250 | FALSE | Western Europe
Gabon | 8311 | GAB | 266 | FALSE | Central Africa
Gambia | 8312 | GMB | 270 | FALSE | Western Africa
Georgia | 8562 | GEO | 268 | FALSE | Middle East
Germany | 8207 | DEU | 276 | FALSE | Western Europe
Ghana | 8313 | GHA | 288 | FALSE | Western Africa
Greece | 8214 | GRC | 300 | FALSE | Southeast Europe
Greenland | 8413 | GRL | 304 | FALSE | Northern Europe
Grenada | 8441 | GRD | 308 | FALSE | Central America
Guatemala | 8415 | GTM | 320 | FALSE | Central America
Guinea | 8315 | GIN | 324 | FALSE | Western Africa
Guinea-Bissau | 8314 | GNB | 624 | FALSE | Western Africa
Guyana | 8417 | GUY | 328 | FALSE | South America
Haiti | 8418 | HTI | 332 | FALSE | Central America
Honduras | 8420 | HND | 340 | FALSE | Central America
Hungary | 8240 | HUN | 348 | FALSE | Central Europe
Iceland | 8217 | ISL | 352 | FALSE | Northern Europe
India | 8510 | IND | 356 | FALSE | Middle East
Indonesia | 8511 | IDN | 360 | FALSE | Southeast Asia
Iran (Islamic Republic of) | 8513 | IRN | 364 | FALSE | Middle East
Iraq | 8512 | IRQ | 368 | FALSE | Middle East
Ireland | 8216 | IRL | 372 | FALSE | Northern Europe
Israel | 8514 | ISR | 376 | FALSE | Middle East
Italy | 8218 | ITA | 380 | FALSE | Southern Europe
Jamaica | 8421 | JAM | 388 | FALSE | Central America
Japan | 8515 | JPN | 392 | FALSE | Eastern Asia
Jordan | 8517 | JOR | 400 | FALSE | Middle East
Kazakhstan | 8563 | KAZ | 398 | FALSE | Central Asia
Kenya | 8320 | KEN | 404 | FALSE | Eastern Africa
Kiribati | 8616 | KIR | 296 | FALSE | Oceania
Kuwait | 8521 | KWT | 414 | FALSE | Middle East
Kyrgyzstan | 8564 | KGZ | 417 | FALSE | Central Asia
Lao People's Democratic Republic | 8522 | LAO | 418 | FALSE | Southeast Asia
Latvia | 8261 | LVA | 428 | FALSE | Northern Europe
Lebanon | 8523 | LBN | 422 | FALSE | Middle East
Lesotho | 8324 | LSO | 426 | FALSE | Southern Africa
Liberia | 8325 | LBR | 430 | FALSE | Western Africa
Libya | 8326 | LBY | 434 | FALSE | Northern Africa
Liechtenstein | 8222 | LIE | 438 | FALSE | Central Europe
Lithuania | 8262 | LTU | 440 | FALSE | Northern Europe
Luxembourg | 8223 | LUX | 442 | FALSE | Western Europe
Madagascar | 8327 | MDG | 450 | FALSE | Southeast Africa
Malawi | 8329 | MWI | 454 | FALSE | Southeast Africa
Malaysia | 8525 | MYS | 458 | FALSE | Southeast Asia
Maldives | 8526 | MDV | 462 | FALSE | Southern Asia
Mali | 8330 | MLI | 466 | FALSE | Western Africa
Malta | 8224 | MLT | 470 | FALSE | Southern Europe
Marshall Islands | 8617 | MHL | 584 | FALSE | Oceania
Mauritania | 8332 | MRT | 478 | FALSE | Northwest Africa
Mauritius | 8333 | MUS | 480 | FALSE | Southeast Africa
Mexico | 8427 | MEX | 484 | FALSE | North America
Micronesia (Federated States of) | 8618 | FSM | 583 | FALSE | Oceania
Monaco | 8226 | MCO | 492 | FALSE | Southern Europe
Mongolia | 8528 | MNG | 496 | FALSE | Central Asia
Montenegro | 8254 | MNE | 499 | FALSE | Southeast Europe
Morocco | 8331 | MAR | 504 | FALSE | Northwest Africa
Mozambique | 8334 | MOZ | 508 | FALSE | Southeast Africa
Myanmar | 8505 | MMR | 104 | FALSE | Southeast Asia
Namibia | 8351 | NAM | 516 | FALSE | Southern Africa
Nauru | 8604 | NRU | 520 | FALSE | Oceania
Nepal | 8529 | NPL | 524 | FALSE | Southern Asia
Netherlands | 8227 | NLD | 528 | FALSE | Western Europe
New Caledonia | 8606 | NCL | 540 | FALSE | Oceania
New Zealand | 8607 | NZL | 554 | FALSE | Oceania
Nicaragua | 8429 | NIC | 558 | FALSE | Central America
Niger | 8335 | NER | 562 | FALSE | Western Africa
Nigeria | 8336 | NGA | 566 | FALSE | Western Africa
Niue | 8683 | NIU | 570 | FALSE | Oceania
North Macedonia | 8255 | MKD | 807 | FALSE | Southeast Europe
Norway | 8228 | NOR | 578 | FALSE | Northern Europe
Oman | 8527 | OMN | 512 | FALSE | Southwest Asia
Pakistan | 8533 | PAK | 586 | FALSE | Southern Asia
Palau | 8619 | PLW | 585 | FALSE | Oceania
Panama | 8430 | PAN | 591 | FALSE | Central America
Papua New Guinea | 8608 | PNG | 598 | FALSE | Oceania
Paraguay | 8431 | PRY | 600 | FALSE | South America
Peru | 8432 | PER | 604 | FALSE | South America
Philippines | 8534 | PHL | 608 | FALSE | Southeast Asia
Poland | 8230 | POL | 616 | FALSE | Eastern Europe
Portugal | 8231 | PRT | 620 | FALSE | Western Europe
Puerto Rico | 8433 | PRI | 630 | FALSE | North America
Qatar | 8519 | QAT | 634 | FALSE | Southern Asia
Republic of Korea | 8539 | KOR | 410 | FALSE | Eastern Asia
Republic of Moldova | 8263 | MDA | 498 | FALSE | Southeast Europe
Romania | 8232 | ROU | 642 | FALSE | Southeast Europe
Russian Federation | 8264 | RUS | 643 | FALSE | Northeast Europe
Rwanda | 8341 | RWA | 646 | FALSE | Eastern Africa
Saint Kitts and Nevis | 8445 | KNA | 659 | FALSE | Central America
Saint Lucia | 8443 | LCA | 662 | FALSE | Central America
Saint Vincent and the Grenadines | 8444 | VCT | 670 | FALSE | Central America
Samoa | 8612 | WSM | 882 | FALSE | Oceania
San Marino | 8233 | SMR | 674 | FALSE | Southern Europe
Sao Tome and Principe | 8344 | STP | 678 | FALSE | Southwest Africa
Saudi Arabia | 8535 | SAU | 682 | FALSE | Middle East
Senegal | 8345 | SEN | 686 | FALSE | Western Africa
Serbia | 8248 | SRB | 688 | FALSE | Southeast Europe
Seychelles | 8346 | SYC | 690 | FALSE | Eastern Africa
Sierra Leone | 8347 | SLE | 694 | FALSE | Western Africa
Singapore | 8537 | SGP | 702 | FALSE | Southeast Asia
Slovakia | 8243 | SVK | 703 | FALSE | Central Europe
Slovenia | 8251 | SVN | 705 | FALSE | Central Europe
Solomon Islands | 8614 | SLB | 90 | FALSE | Oceania
Somalia | 8348 | SOM | 706 | FALSE | Eastern Africa
South Africa | 8349 | ZAF | 710 | FALSE | Southern Africa
South Sudan | 8363 | SSD | 728 | FALSE | Central Africa
Spain | 8236 | ESP | 724 | FALSE | Southern Europe
Sri Lanka | 8506 | LKA | 144 | FALSE | Southern Asia
State of Palestine | 8550 | PSE | 275 | FALSE | Middle East
Sudan | 8350 | SDN | 729 | FALSE | Northeast Africa
Suriname | 8435 | SUR | 740 | FALSE | South America
Sweden | 8234 | SWE | 752 | FALSE | Northern Europe
Switzerland | 8100 | CHE | 756 | FALSE | Central Europe
Syrian Arab Republic | 8541 | SYR | 760 | FALSE | Middle East
Tajikistan | 8565 | TJK | 762 | FALSE | Central Asia
Thailand | 8542 | THA | 764 | FALSE | Southeast Asia
Timor-Leste | 8547 | TLS | 626 | FALSE | Southeast Asia
Togo | 8354 | TGO | 768 | FALSE | Western Africa
Tokelau | 8684 | TKL | 772 | FALSE | Oceania
Tonga | 8610 | TON | 776 | FALSE | Oceania
Trinidad and Tobago | 8436 | TTO | 780 | FALSE | Central America
Tunisia | 8357 | TUN | 788 | FALSE | Northern Africa
Turkey | 8239 | TUR | 792 | FALSE | Middle East
Turkmenistan | 8566 | TKM | 795 | FALSE | Central Asia
Tuvalu | 8615 | TUV | 798 | FALSE | Oceania
Uganda | 8358 | UGA | 800 | FALSE | Eastern Africa
Ukraine | 8265 | UKR | 804 | FALSE | Eastern Europe
United Arab Emirates | 8532 | ARE | 784 | FALSE | Southwest Asia
United Kingdom of Great Britain and   Northern Ireland | 8215 | GBR | 826 | FALSE | Northern Europe
United Republic of Tanzania | 8353 | TZA | 834 | FALSE | Eastern Africa
United States of America | 8439 | USA | 840 | FALSE | North America
Uruguay | 8437 | URY | 858 | FALSE | South America
Uzbekistan | 8567 | UZB | 860 | FALSE | Central Asia
Vanuatu | 8605 | VUT | 548 | FALSE | Oceania
Vatican City | 8241 | VAT | 336 | FALSE | Southern Europe
Venezuela (Bolivarian Republic of) | 8438 | VEN | 862 | FALSE | South America
Viet Nam | 8545 | VNM | 704 | FALSE | Southeast Asia
Yemen | 8516 | YEM | 887 | FALSE | Middle East
Zambia | 8343 | ZMB | 894 | FALSE | Southern Africa
Zimbabwe | 8340 | ZWE | 716 | FALSE | Southern Africa

**Comment by syntakker** [comment]
@Candice-Louw which of the numbers in [this spreadsheet](https://docs.google.com/spreadsheets/d/1ejttFVpS9HEavP2kWM5lrHgLS1T4j38tSDaKQBbLBpI/edit?usp=sharing) are the correct external IDs for default continents and subcontinents?

From your screenshots [here](https://github.com/hzi-braunschweig/SORMAS-Project/issues/4658#issuecomment-800128842) I would assume it's the fourth column (410000XX), is this correct?

**Comment by HolgerReiseVSys** [comment]
> @Candice-Louw which of the numbers in [this spreadsheet](https://docs.google.com/spreadsheets/d/1ejttFVpS9HEavP2kWM5lrHgLS1T4j38tSDaKQBbLBpI/edit?usp=sharing) are the correct external IDs for default continents and subcontinents?
> 
> From your screenshots [here](https://github.com/hzi-braunschweig/SORMAS-Project/issues/4658#issuecomment-800128842) I would assume it's the fourth column (410000XX), is this correct?

To me it looks like column K would be correct, which seems to match the SurvNet IdIndex (e.g. 31000005 for Afrika).

**Comment by syntakker** [comment]
@HolgerReiseVSys are you sufficiently sure to confirm? :-)

**Comment by syntakker** [comment]
@stefanspiska confirmed that external ID for continents and subcontinents should be column K in https://docs.google.com/spreadsheets/d/1ejttFVpS9HEavP2kWM5lrHgLS1T4j38tSDaKQBbLBpI/edit#gid=0
