### ISSUE TITLE
Add a country field to regions [5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#4784]
### Situation Description
Concept issue: #4658 

For exposures (and later maybe for other use cases), users need to be able to not only specify a country, but also a continent or subcontinent in case they don't know the exact name of the country they have traveled to or have traveled to multiple countries.

### Feature Description
Beyond the definitions above, it should also be possible to create regions in other countries and allow users to select those when specifying locations in other countries.

- [x] Add a new `country` field to the `Region` entity
- [x] Extend the region edit form with the new field; read-only when editing an existing region UNLESS the country is empty
- [x] Extend the region grid with a column containing the region's country
- [x] Remove the code that makes region, district, community and health facility read-only when selecting a different country than the server country; this impacts the location and event forms; however, these fields still need to be optional in that case (this impacts the event form)
- [x] Change all code occurrences where region dropdowns are filled to the following pattern:
    * If NO country is selectable (e.g. case or contact jurisdiction), fill the region dropdown with all regions that are either in the server country or have no country
    * If a country is selectable (e.g. locations, events), use the logic above if no country or the server country is selected, otherwise fill the dropdown with the regions from the selected country
- [x] Add a version-specific database upgrade script to `StartupShutdownService.upgrade` that assigns all existing regions to the server country (if specified)

**Comment by maxiheyner** [comment]
Issue tracker comment
