### ISSUE TITLE
App eating alot of battery power

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#479]
@MartinWahnschaffeSymeda 

Please we need to address this issue

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
Can you quantify this, please? 

1. Which device (TECNO or Huawei or both)?
2. How are the devices used? Is this daily use or training use?
3. How long does a completely charged battery last?
4. What percentage of battery power is consumed by SORMAS?

**Comment by MartinWahnschaffeSymeda** [comment]
We still need more precise data on the current situation so we can compare before and after.

- [ ] reduce MDM GPS poll (once an hour)
- [ ] reduce GPS poll time

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar During the EAB meeting I heard that this is still an issue. Do you have approximate values on how long the battery typically lasts in the field?

**Comment by Chinedar** [comment]
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> When the app is running in
the background, the device batteries last for about 6 hours and go down. We
mention in training and supervision the need for them to close the app if
its not in use. That way the battery can last for more than 12 hours.

**Comment by MateStrysewskeSym** [comment]
- [ ] in terms of synchronization and gps polling the app should behave the same in background as when not activate at all
- [ ] reduce gps poll and auto-sync time (15 minutes?)

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar We will reduce GPS polling and data sync frequency. This should help a lot. I remember that there is also a GPS poll interval done by the mobile device management. Please change this interval as well or even deactivate it.

**Comment by Chinedar** [comment]
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> Great! we will reduce the
time interval...if it doesn't help, then we can deactivate it completely.
Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
See also: https://www.google.com/events/io/io14videos/64bf2234-4bcb-e311-b297-00155d5066d7
