### ISSUE TITLE
[External Journals] Provide a standardized documentation for External Journals so other systems can adhere to it [TB 2d]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#4799]
As SORMAS supports integration of External Journals by providing an API for this, we also need a documentation on how to use that API.
This way we target to standardize the workflow in a similar fashion we do the integration at the moment with other External Journal Systems.

- [x] Describe the dataflow that needs to happen between SORMAS and External Journal system
- [x] Add the documentation to the swagger documentation of the externalVisitsResource

**Comment by FredrikSchaeferVitagroup** [comment]
@irinajanzen-hzi

**Comment by FredrikSchaeferVitagroup** [comment]
We should use the climedo approach as a standard, as it is more advanced than the PIA approach and conventic wants to change to seamless integration.

**Comment by StefanKock** [comment]
documentation can be seen here: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/openapi/external_visits_API.json and https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/openapi/external_visits_API.yaml
