### ISSUE TITLE
Add a filter for the relationship with case at contact directory [1]

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4807]
### Situation Description
The user needs to filter the contact directory for the "relationship with case" to track family members, colleagues at work etc. 
Currently this search is rather complicated through filtering by name for family members or addresses. 
### Feature Description
Add a filter option for the relationship with case. Enable an enum including " live in the same household, other family or friend, work in the same environment, provided medical care for the case and other" and add an additional column for "relationship with case" next to type of contact.

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of sormas 1.60.0-snapshot on local envrionment.

**Comment by maxiheyner** [comment]
Issue Tracker Comment
