### ISSUE TITLE
Add a filter and additional column to track reinfected cases [1]

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#4816]
### Situation Description
Reinfection of a case (yes, no, unknown) can be documented, but a filter and separate column for this is missing so far. 
### Feature Description
Add a filter function for reinfected cases using a checkbox at the default and detailed case directory view. 
might look like this: 
![image](https://user-images.githubusercontent.com/76884029/111610539-c0f80780-87db-11eb-9d18-01f260ee025d.png)
and add a column to the detailed case view, which might look like this:
![image](https://user-images.githubusercontent.com/76884029/111611201-7aef7380-87dc-11eb-9e3e-c8a27e70cba7.png)

**Comment by bernardsilenou** [comment]
- [ ] This is a DE only variable, are the directories configured as DE only?
- [ ] @maxiheyner Would suggest we put the column anywhere after the health facility since this is not a core variable but an additional information of the case.

**Comment by vlad-ciucescu** [comment]
Do we add this to the detailed export too?

**Comment by maxiheyner** [comment]
@vlad-ciucescu yes, please.

**Comment by vlad-ciucescu** [comment]
Is it acceptable to have the new column after 'Investigation Status' and not before it?

**Comment by vlad-ciucescu** [comment]
To validate:

- be sure that the system is German (if testing locally, set `country.locale=de` in `sormas.properties`)
- open an existing case or create a new one. The disease must be Covid19
- set a value for the reinfection field
- save the case
- open the detailed cases view
- after the "Outcome of case" column, the new "Reinfection" column should be present and show the status for cases with the value set.

Aditionally, set the `country.locale` to something else (e.g. `ch`) and check that the column no longer appears.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest Validated on the latest version of sormas 1.58.0-snapshot on test-de.sormas.netzlink.com
