### ISSUE TITLE
Notification to the responsible user when a participating person is part of other events

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4817]
### Situation Description

Development in connection with # 4570 # 4571 # 4572 # 4573 consisting of grouping events together.

### Feature Description

Development consists of sending a notification to all event responsible user when a person participating in their event is attached to other events.
The objective is to be able to speed up the identification of chains of contamination and to take measures to limit the spread.

Eg:
Report date: 01/01/2021 => responsible user a: Event A -> Participant person α
Report date: 02/01/2021 => responsible user b: Event B -> Participant person α.

-> On 02/01/2021, the responsible users for events A and B will receive a notification informing that the person is involved in events A and B and that an exchange between user a and b should make it possible to rule on the need whether or not to link events A and B.

Content of the notification:
- person ID
- List of events to which the person is linked
- List of users responsible for the various events, recipients of the notification.

This notification will only be sent if:
- The disease is the same for the different events
- The events are reported in a space-time of 30 days

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by ftavin** [comment]
@bernardsilenou @carolinverset

I can't remember if we had solved the fact of not being able to give the identity of the responsible users other than by their id (we were not sure we could send user's names by mail)

**Comment by bernardsilenou** [comment]
@ftavin for the list of responsible users, I think we can put their name in the notification since they are all colleagues and users of the system. For the event participant, we exclude the name.

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @emond-fuseau
Yes I also think that it is possible to leave the name of the responsible user. This is essential for the management of the group afterwards (important to be able to contact each other to see if the events are related)

**Comment by bernardsilenou** [comment]
@MateStrysewske  Dev France would work for this in 1.59

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou 

I have a doubt, this feature applies to all persons, not only confirmed cases ?

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @emond-fuseau
Yes exactly. The underlying idea is to identify events that are linked so if a person, whatever their status, participates in several events, the responsible users must be warned so that they can check whether or not the events are to be linked. .

**Comment by richardbartha** [comment]
**The responsible users for events A and B will receive a notification** does not work correctly only the responsible person of the first event where the participant was registered is being notified currently.

**Comment by BarnaBartha** [comment]
@carolinverset @aponcon-atolcd Can you please check this again?

**Comment by aponcon-atolcd** [comment]
Hi @richardbartha and thanks for your tests.
Can I have more information about the events you've created?

For information here are the rules for these notifications:

- the events should be related to the same disease
- the events should be reported in a space-time of 30 days
- they are only sent to responsible users that have an email address
- the notification targeting the user that made the action will just be ignored (this rule is there for all types of notification)

**Comment by richardbartha** [comment]
Hi @aponcon-atolcd! 
I created the events with NatUser having responsible users as SurvOfficer and SurvSupervisor for the two events, both responsible users had email address but notification was sent only to the responsible person of the event where the participant was added first. Having a participant attend 3 events then the first 2 responsible persons of the events will be notified the last one where he is getting added will not receive any notification. The other bullet points were ok regarding the disease, time space, last point in my case the person adding the new participant is not the same person who is responsible for the event, maybe because of this this was missed. I hope this clarifies your questions, but feel free to ask more if not. Also found some other bug during this validation, but that is another story [#5559](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5559)

**Comment by bernardsilenou** [comment]
@aponcon-atolcd 
On the server that you are testing, are all the different types of notifications activated? ie the configuration table in the db and also the sormas.properties file.

**Comment by bernardsilenou** [comment]
We have to be sure that the server is rightly configured, many of our test servers may not rightly configured for this purpose since the configuration in the db is set to false by default

**Comment by aponcon-atolcd** [comment]
Hi
I understand better what the issue is about now. The issue is that the event where the last participant was added was just filtered out intentionally but by reading again at the issue it's indeed a mistake.

I'll create a PR fixing this issue in the afternoon.
