### ISSUE TITLE
Show the type of lists in the data dictionary [1]

### ISSUE THREAD

**Issue by ErikMarzHZI** [hzi-braunschweig/SORMAS-Project#4836]
### Feature Description

SORMAS data dictionary

### Problem Description

Since certain fields are circumstantially generated as DTOs, these need to be listed and classified accordingly in the data dictionary. Currently this is not the case and as such, it would be beneficial to have a dedicated column that helps the viewer differentiate on the aforementioned basis. 

### Proposed Change

Create a new column that displays the DTO of the respective field, where applicable. 

### Additional Information

Once the column is added, make sure that all DTOs are included in the data dictionary and linked accordingly.

### Development Specifications
* The actual DTO fields already have a value in the "Type" column by now; this should be fine
* What is missing are lists types, because for those, the "Type" column is currently empty; make sure that for these fields, the Type column contains "List of XXX" (internationalized) with the name of the Dto (- the Dto suffix, so as it's done for other fields in the data dictionary right now) or the data type. This e.g. includes addresses and personContactDetails for persons, exposures or activitiesAsCase for epidemiological data, or requestedPathogenTests and requestedAdditionalTests for samples

**Comment by ErikMarzHZI** [comment]
@MateStrysewske any comments or refinements? 

Since we are already making greater changes to the data dictionary, we should consider implementing #4607.

**Comment by bernardsilenou** [comment]
@ErikMarzHZI  What is the meaning of DTO please?

**Comment by ErikMarzHZI** [comment]
@bernardsilenou it means data transfer object
