### ISSUE TITLE
Remove VIEW_ARCHIVED user rights [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4838]
### Feature Description
All user roles now have the web interface but for some users like: surveillance + contact officers, lab officers, community officer, hospital informant this is missing. This is not needed on the mobile app because db limitation.
### Problem Description
- Add icon to show archived entities to users roles that do not have it
- Add to directories for:  tasks, case, contact, event, samples
### Additional Information
![image](https://user-images.githubusercontent.com/12996724/111812320-4cef5980-88d8-11eb-9039-322eb49c7979.png)

### Development Specifications

- Remove the XXX_VIEW_ARCHIVED user rights and use the respective XXX_VIEW user rights instead

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 @JaquM   This is similar to the issue that Christin mentioned in last sprint review (about reinfection). To consider archived entities when filtering + duplicate detection
To do:
- Add the drop-down to show archived entities to all users roles on web
-  Consider archived entities for all duplicate detection and match accordingly to the option selected by user. If user choose only active, then logic should exclude archived. But During creation and import of new entities, archived + active should be considered.

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou Do I understand it correctly that these are somewhat two issues? In that case, I would split this up into two tickets, one for 1) and one for 2)+3)

1) Add the option to view archived entities to all web users

2) include archived entities in the duplicate detection (this is currently **not** the case) *when creating or importing new entities*

3) In the "Merge Duplicates" Mode of the case directory (as far as I know, it only exists here), add a checkbox "Do not consider archived cases"

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen  Just to mention that this is only for the web app. On mobile app, we remove all archived entities. eg a Hospital informant connected to the mobile app would not have access to archived entities but would do so when connected on web app.

**Comment by MateStrysewske** [comment]
@bernardsilenou The two things mentioned in this issue are semantically very different and should not be tackled in one single issue. Please open a new issue for the second part (including archived entities during duplicate detection) and update the prioritisation accordingly.

**Comment by MateStrysewske** [comment]
@bernardsilenou Does this mean that EVERY user role that has the XXX_VIEW user right should also have the XXX_VIEW_ARCHIVED user right? i.e. every user who can access the case directory should also be allowed to access the archived cases?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Yes please, but for the web app only.

**Comment by RazvanHodisan** [comment]
Verified on local env and https://test.sormas.netzlink.com/
