### ISSUE TITLE
[Sormas@DEMIS] Add columns in Lab Massage Directory [0.5]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#4841]
### Situation Description
Columns should be added to facilitate the distribution and clarity of DEMIS messages received.
### Feature Description
Add the following columns: 
Name of the reporter (laboratory), postal code of the reporter(laboratory), postal code of the patient.
### Additional Information
@kwa20

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.59.0-snapshot on test-de2.sormas.netzlink.com
