### ISSUE TITLE
Link the person Id on the event participant list to the respective person form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4842]
### Feature Description
event participant list > person Id column
### Problem Description
Thus far, the person Id on the event participant lists display the uuid of the person but don't allow navigation.
### Proposed Change
Use the displayed uuid of the person on these forms to navigate to the respective person forms in the person directory.

### Additional Information
<img width="843" alt="EpPersonLink" src="https://user-images.githubusercontent.com/70317594/111921262-f6c71580-8a93-11eb-868d-d696a37778d2.PNG">
<img width="674" alt="EpPersonLink2" src="https://user-images.githubusercontent.com/70317594/111921305-2f66ef00-8a94-11eb-81b9-63f77ebf71c2.PNG">

**Comment by OrgaLandkreisTuebingen** [comment]
The district of Tübingen would also like this feature!

**Comment by kwa20** [comment]
Discarding this issue since it was fixed via https://github.com/hzi-braunschweig/SORMAS-Project/issues/9921
