### ISSUE TITLE
[DEMIS Interface] Introduce option to reject lab messages [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4851]
### Situation Description
Often enough, users get lab messages that mistakingly reached them and are not supposed to be processed by their system. The lab message interface should allow sorting of such messages to a specific location without having to delete them directly. This might be relevant for further use in communication with the intended recipient.
### Feature Description

- Add the option to set the state of a lab messages to "UNCLEAR" or "FORWARDED" in the lab message details and on the processing step AND NOT  on the directory
- Add a list of "UNCLEAR" lab messages as a filter option
- Add a list of "FORWARDED" lab messages as a filter option
- "UNCLEAR" messages should still be able to be processed in case they were mistakingly labeled as rejected.
- When the lab message is sent via SORMAS 2 SORMAS, the lab message should automatically be set to the state "FORWARDED"
- Check for parallel processing / forwarding

### Possible Alternatives
- Rejected lab messages could have to be recovered first before being able to be processed again. However, this would include more clicks and navigation.
### Additional Information
<img width="958" alt="Screen Shot 2021-03-22 at 4 45 50 PM" src="https://user-images.githubusercontent.com/70317594/112017649-190d7180-8b2e-11eb-8d30-baa667e92b89.png">

**Comment by kwa20** [comment]
@JaquM please add if I missed anything.

**Comment by bernardsilenou** [comment]
@kwa20 
- If the lab messages were sent by error, then why not just add an option to delete them as we do for other entities ? 
- Is there a need to keep  them in the system?

**Comment by kwa20** [comment]
@bernardsilenou Often enough users still need them for further purposes and communication with other health departments even when they were intended for other parties. In this way, they can sort them from the relevant ones and delete them once they've clarified rejected lab messages if desired.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @JaquM I think this issue heavily relates to #3742 and #4423. Rejected lab messages would basically be stored in the designated table until they are either forwarded or eventually deleted. Otherwise they'd stay available for further use. I'm not sure how #3742 is implemented yet until I've tested but if the acceptance and rejection method proposed in #4423 is implemented, lab messages could be stored in the rejected table until they've been accepted by the other instance and will then move to the forwarded list.

This comment is mainly to spark the discussion and see if me need to specify further adjustments for the future.

**Comment by FredrikSchaeferVitagroup** [comment]
Is it really a good idea to have the option to reject lab messages?

- rejecting a lab message leads to the impression that this messages was not accepted by the sormas instance and that this denial was communicated to somewhere (e.g. the external lab message system). This is a wrong impression. 
- lab messages hold information that needs to be processed quickly. Parking rejected lab messages in a seperated state may look nicer for users responsible for processing lab messages, but it may divert from the fact that those lab message need attention and action.

Those two aspects may lead to many lab messages residing in this rejected state. Should they not either be processed or sent to another sormas instance?

**Comment by FredrikSchaeferVitagroup** [comment]
Would it help to have an invalid state for lab messages?

**Comment by JaquM** [comment]
The important point is to get the messages for which you are not responsible out of the main overview but still be able to process them later.

**Comment by FredrikSchaeferVitagroup** [comment]
Another important point is to not loose information of lab messages that are moved out of view by rejection and then not dealt with because users wrongly assumed that someone else takes care of them. Or am I wrong here?
Please keep in mind that lab messages are exclusively sent to one recipient by DEMIS and deleted after a certain amount of time (in SORMAS and in DEMIS). Also consider that a new DEMIS release improved the routing of information on DEMIS-side.

**Comment by JaquM** [comment]
Yes, but in areas with many hospitals, about 1/4 receive reports that they are not responsible for processing. The organization of the GAs must be supported, we can do this better than prevent errors by people in the GAs. Therefore, please introduce this option, whether it says rejected or "unclear responsibility" is not important.

**Comment by FredrikSchaeferVitagroup** [comment]
@JaquM I don't know if I understand your comment correctly. A feasible approach might be to add two new states: `unclear responsibility` and `manually forwarded`. Like this, users would have four ways to move lab messages out of what you call main view (I assume you mean the list of unprocessed lab messages):

1. Process a lab message (it is then set to processed)
2. Send it to another dempartment via SORMAS2SORMAS (it then completely disappears from the sending instance).
3. Manually forward it (and set the state of the labMessage to `manually forwarded`)
4. Mark it with `unclear responsibility` to deal with it later.

**Comment by kwa20** [comment]
@FredrikSchaefer @JaquM  Vitagroup Are we making sure that lab messages that are forwarded to another instance are processed on the receiving end? Unless users can be certain that someone took over the responsibility of the lab message, it shouldn't be deleted I think. This will also be covered by #4423 I believe? 

When we have the statuses "manually forwarded" and "forwarded via Sormas2Sormas", we should probably only have the overall subdivision of forwarded. We would end up with messages that can have the status "unprocessed", "processed", "unclear responsibility " ("waiting" or "clarify" could be an alternative cause it's lengthy) and "forwarded". The Processed column could be renamed to "status" and then display the different statuses depending on what action took place.

For this issue, I suggest we leave it as it is and simply need to decide which label we choose.

**Comment by markusmann-vg** [comment]
![image](https://user-images.githubusercontent.com/62540178/112991456-6b224880-9167-11eb-9f78-87519d8499b0.png)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test-de2.soromas.netzlink.com environment
