### ISSUE TITLE
[DEMIS Interface] visualize respective lab messages in sample and pathogen test sections [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4853]
### Situation Description
Users that processed lab messages through the interface cannot easily go back to the respective lab message that was processed in order to create resulting cases, contacts, event participants, samples and pathogen tests. 
### Feature Description

- To enhance the usability of the lab messages interface, link entities to the lab messages that lead to their creation and visualize the messages directly in the respective entity.
- Use the eye icon in pathogen and sample lists to either show the lab message for the respective pathogen test or the lab message to the latest pathogen test (if processed through the interface) for samples.

### Additional Information
<img width="619" alt="Screen Shot 2021-03-22 at 5 36 05 PM" src="https://user-images.githubusercontent.com/70317594/112025100-20844900-8b35-11eb-9611-81793cdc315b.png">
@JaquM

**Comment by vlad-ciucescu** [comment]
postponed for next sprint

**Comment by FredrikSchaeferVitagroup** [comment]
Considering the latest news about demis messages, we probably need to change the specification of this ticket: The point is that several lab messages can influence the same contact, case, event participant sample and even pathon test. This is probable to become a typical scenario, for example when first a positive COVID test result is sent via DEMIS, and then later the disease variant is specified in another message (this will probably soon become part of a pathogen test result, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/4633).

Showing just the latest or just the creating lab message is highly irritating then. That's why I suggest to directly take into consideration that each entity may have several lab messages. I suggest to initially always show the latest lab message assigned to an entity, but to have small arrow buttons that allow users to switch to older lab messages. Like so:

![Mockup](https://user-images.githubusercontent.com/67001822/113252957-d33a7100-92c4-11eb-9f1c-0dccd8d28751.png)

**Comment by FredrikSchaeferVitagroup** [comment]
Also, lab message can be deleted. Is this taken into consideration here?

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 What is also not really clear is what is supposed to be the **latest** lab message. From which date shall we determine this?
There are several options, for example the creation date in SORMAS, which should represent the date when the message arrived at the health department (as DEMIS notifications are usually fetched in batches, this date may be very similar for many lab messages).

I propose to use the date that shows as "Letzte Aktualisierung" in the screenshots, which should be the date when the notification arrived at the DEMIS server.

**Comment by maxiheyner** [comment]
Issue tracker comment

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I really like the idea to be able to flip through all the related lab messages! I didn't know that was possible and would be way better.

In the future, we'll try to show the latest pathogen test in the sample box on the information form. This will be the most recent pathogen test of the sample and determined by the testDateTime. I think the initially shown lab message should be the one that belongs to the displayed pathogen test before flipping through other related messages. Since this is merely dependent on the date association, we would not have to wait for the implementation until #3890

**Comment by FredrikSchaeferVitagroup** [comment]
> In the future, we'll try to show the latest pathogen test in the sample box on the information form. This will be the most recent pathogen test of the sample and determined by the testDateTime. I think the initially shown lab message should be the one that belongs to the displayed pathogen test before flipping through other related messages. Since this is merely dependent on the date association, we would not have to wait for the implementation until #3890

@kwa20 Yes, this seems to make sense. What now if there are several labMessages related to that most recent pathogen test? I guess we then need to sort by some date.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I think in that case we should use "Letzte Aktualisierung" then as you proposed earlier.

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as the lab message is displayed the wrong way.
![image](https://user-images.githubusercontent.com/70562142/115670034-a3293f80-a351-11eb-831c-3fb9bbfafb54.png)

**Comment by FredrikSchaeferVitagroup** [comment]
@AndyBakcsy-she Can you please specify on which instance you tested? This most probably happens because of misconfiguration, not because of faultiy implementation.

**Comment by FredrikSchaeferVitagroup** [comment]
The xml representation of the lab message you see in the screenshot you posted always shows when the demis adapter could not be used to convert the lab message into a html. Most often this happens because the adapter is not properly configured.

**Comment by vidi42** [comment]
@AndyBakcsy-she Since the release process was already started for 1.59 I suggest opening a new bug for this with more details if it turns out to be an implementation issue and not a configuration one.
