### ISSUE TITLE
[SORMAS2SORMAS] Allow bulk sync of data once they are shared [5]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#4858]
### Situation Description

At the moment the SORMAS 2 SORMAS share feature support Bulk sharing of data between instance, but once an entity was shared with an instance it can only be resynced with the instance because share and sync work slightly different that's one reason it is separated on the details page.

### Feature Description

Implement Sync action in the bulk actions for supported entities.

Open points that should be discussed:

* in bulk mode the user can select some shared cases but also some unshared => how to proceed in this case? should we separate the share and sync actions here too?
* sync preselects previously used options => what options to reuse in bulk mode if some cases where shared with samples and others without samples
* Is this only relevant for still owned entities, because one looses edit rights once the data is sent to another instance.

**Comment by MateStrysewske** [comment]
@vidi42 Concerning your discussion points:

* I think "Sync" should be an independent option in the bulk options dropdown (not hidden behind the "Edit" bulk action)
* If we take the Sormas2SormasShareInfo of every individual case when clicking on that "Sync" option, we shouldn't have a problem, right? I don't think the "Sync" bulk option should bring up any kind of popup that allows the user to make additional configurations, it should just sync the case based on the selections when it was initially shared

Concerning the third point, I can't really answer that - but I guess so?

**Comment by markusmann-vg** [comment]
Now that we have n automatic sync, whenever data was changed, we do not need the bulk mode anymore. Sync button is no longer available.
