### ISSUE TITLE
Demis-Field IMS missing in Sormas

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4859]
### Feature Description

According to the information from the RKI in out current application we have to fill in the field IMS, which we get from the laboratory after the final sequenzing of the sample.

The field is discribed in the newsletter from RKI (https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/DESH/CorSurV_Brief_Gesundheitsamt.pdf?__blob=publicationFile) and is mandatory to submit from the lab to the RKI and health office.

Maybe Sormas needs a field to save this data too.

Sorry for the short description.

**Comment by JaquM** [comment]
@Marko-ilmkreis 
The entry is already covered with the Typing ID field for sequencing, or do you think there needs to be another field?

**Comment by Marko-ilmkreis** [comment]
@JaquM Yes, thats the field. I close this issue. Sorry for this.
