### ISSUE TITLE
Date of Birth of persons can be in the future

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4868]
### Bug Description

Title says it all.

### Steps to Reproduce
1. Go to a person (either via person directory, or via a case)
2. Set a birthdate in the future

### Expected Behavior

Disallow this.

### Screenshots

![image](https://user-images.githubusercontent.com/4655486/112298891-85f04b00-8c97-11eb-8426-69cef212e3f5.png)

### Additional Information

This issue may be related to #4651

**Comment by MateStrysewske** [comment]
Additionally, add validation to the backend that prevents illegal birth dates from being saved.

**Comment by MateStrysewske** [comment]
Also needs to be applied to case creation, contact creation and line listing form

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on local environment
