### ISSUE TITLE
pseudonymized for REST-API

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#4871]
Hi guys,
I created an event, a person and a eventparticipant via the rest-api. (POSTMAN)
I got a "OK".
I logged in as my normal user and i see all the data of the generated user.
I set -->' "pseudonymized": true ' for person and eventparticipant .

Why i see the clear name, if i set pseudonymized": true?

my normal sormas user:
* Administrator Überwachungsleitung, Kontaktleitung, Überwachungsleitung, Administrator, Laborbeauftragte*r

my rest user: 
* ReST Benutzer*in, Ereignisbeauftragte*r

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF The "pseudonymized" attribute is supposed to signalise to the mobile app or the frontend that the received data is pseudonymized. It has no use when pushing data into the system - whether or not a user can see the personal data is purely based on the user's role and jurisdiction.
