### ISSUE TITLE
[Lab Messages] improve the display of lab messages [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#4881]
### Feature Description

In the last sprint, there were improvements made on how lab messages are displayed in #4381 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/4742.

### Problem Description

#4742 left two UI parts in a state that should be improved.

### Proposed Change

1. When the xml representation of a labMessage is shown instead of the html representation, it has a vertical scrollbar. This scrollbar is just visible when completely scrolling down the xml-panel. Instead, the vertical scroll bar should be visible all the time.
2. When the html representation of the labMessage is shown while processing, it has a vertical scroll bar with very little effect. That vertical scroll bar should not show.

**Comment by FredrikSchaeferVitagroup** [comment]
I noticed one more thing. When creating an event participant while processing a lab message, when the UI is in german, a button is cut off:

![image](https://user-images.githubusercontent.com/67001822/116527017-80ab9f00-a8da-11eb-9e10-beeae679aad4.png)

There should probably be a scroll bar.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as the button is still cut off when creating an event participant
![image](https://user-images.githubusercontent.com/70562142/128494501-96cc9f81-6bff-45c8-9368-c24b9e1b49f5.png)

**Comment by AndyBakcsy-she** [comment]
The steps to reproduce this:

1. Make sure Sormas language is set to german
2. Open Samples and go to Lab Messages
3. Click on Verabeiten/Process for one of the lab messages 
4. Select create new Person and on the next screen select Neuen Erignisteilnehmer erstellen ( new event participant )
5. Check the buttons 
Actual:
One button is shifted to the right and seems cut-off:

Note:
This is only happening for sormas in german + lab messages. Creating Event Participants from some other place does not reproduce this behaviour

**Comment by AndyBakcsy-she** [comment]
Closing ticket as another one was opened for the issues found.
