### ISSUE TITLE
Add export of the user role configuration to the user section

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#4882]
### Situation Description
We already have a generated document that shows which user rights each user role has.
Given that user roles can be re-configured in the database, this document does not always reflect the actual configuration of a SORMAS instance.

### Feature Description
- [ ] Move the UserRightsGenerator logic to the backend and extend it to include user role configurations done for the instance
- [ ] Keep a class in test that generates the default user roles and rights, as currently done.
- [ ] Translate the user rights and user roles into the language of the exporting user
- [ ] Add an "export user roles" button to the users section that should be available for all users that are allowed to create new users

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of sormas 1.59.0-snapshot on test-de2.sormas.netzlink.com

**Comment by StefanKock** [comment]
Temp file blocks release promotion: `sormas-backend/tmp/sormas_temp_userrights_2021-04-22_1215104159.xlsx`

**Comment by StefanKock** [comment]
It was also missing in the Final Release promotion of Jenkins job sormas-Build, that the now to `sormas-backend` moved *Generator classes have to be executed (is directly called on the module POM `sormas-backend/pom.xml`).

That the promotion failed yesterday might be linked to this ticket too, but was not investigated further after we noticed that the user rights and data dictionary generation was moved out of the automation.
