### ISSUE TITLE
Don't show the Mass-Geo-Coordinate button when no sufficient configuration is provided

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#4883]
### Feature Description

If no configuration for GPS localization is provided, the button introduced with #3545 shouldn't be shown

**Comment by DavidBaldsiefen** [comment]
Actually now that I think abozt it, I might have already implemented it that way. Maybe @JonasCir or @syntakker can check quickly?

**Comment by ChristopherRiedel** [comment]
This is already done
