### ISSUE TITLE
Calendar SORMAS-Project

### ISSUE THREAD

**Issue by Samtner** [hzi-braunschweig/SORMAS-Project#4887]
### Situation description
We operate a testing center attached to the health system these appointments for PCR testing must be managed by the Internal Laboratory. 
### Description of the function
At the moment, it would look like we give the lab a task and they perform the test. Then in Sormas create a sample and when the result comes from the external lab marry them. 
### Possible alternatives
Integrate a Java calendar (e.g. [Open Source] daypolit). With which you can manage the appointments and can also create the samples. Without the time effort to intervene in each contact individually.
### Additional information
We have between 10 and 600 tests a day and currently solve this with Access and Exel.

**Comment by MateStrysewske** [comment]
@Samtner Is this similar to #3106?

**Comment by Samtner** [comment]
Yes, it is based on the same problem

**Comment by MateStrysewske** [comment]
@Samtner Okay, I'll close this issue then and link it in the one I've mentioned.
