### ISSUE TITLE
Facility name and description does not get adopted to previous hospitalization upon case transfer

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4893]
### Bug Description
When the case's place of stay is in a hospital and other facility, the facility name and description field does not get adopted to previous hospitalizations when transferring the case. This leads to a missing entry of a compulsory field in previous hospitalizations and potentially corrupt data
### Steps to Reproduce
1. Create a case and set the current place of stay to hospital, other facility
2. Enter hospitalization data
3. Edit the case's place of stay and transfer the case
4. check the resulting entry in previous hospitalizations

### Expected Behavior
the facility name and description should get adopted in previous hospitalizations
### Screenshots
<img width="341" alt="previousHospitalizationAdoptionBug" src="https://user-images.githubusercontent.com/70317594/112615015-4144eb00-8e22-11eb-83b2-fc9bcf11411e.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on local environment
