### ISSUE TITLE
ct/cq value validation takes place even if the field is disabled or empty

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4896]
### Bug Description
When a test result is entered directly while creating the sample, the ct/cq values gets validated even though the field is either disabled or empty. This prevents the user from saving the data
### Steps to Reproduce
1. Create a sample and directly enter the test result
2. Intentionally either leave the ct/cq value field empty or choose a test type which doesn't enable the ct/cq value field

### Expected Behavior
Since the field is optional, saving should be possible without entries and the validation should only take place with existing entries.
### Screenshots
<img width="498" alt="ctValueBug" src="https://user-images.githubusercontent.com/70317594/112628931-e916e480-8e33-11eb-9552-dd188acd599f.PNG">
<img width="511" alt="ctValueBug2" src="https://user-images.githubusercontent.com/70317594/112629404-938f0780-8e34-11eb-848c-1270300658ff.PNG">

Lab messages interface:
<img width="800" alt="ctValueBug3" src="https://user-images.githubusercontent.com/70317594/112643665-e2dd3400-8e44-11eb-8fee-64da5f2aea4f.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on local environment
