### ISSUE TITLE
Setting missing geo coordinates results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4897]
### Bug Description
When setting the missing geo coordinates on the person directory, an error occurs
### Steps to Reproduce
1. Go to the person directory
2. select "set missing geo coordinates" and continue

### Expected Behavior
Action should set missing geo coordinates successfully
### Screenshots
<img width="367" alt="setMissingGeoError" src="https://user-images.githubusercontent.com/70317594/112631365-15803000-8e37-11eb-8a0d-4aa0d1c1a2e5.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
the test environment probably contains many persons without an address entered. This might be something to take into consideration.

**Comment by BarnaBartha** [comment]
@MateStrysewske the "test1401.sormas-oegd.de" i cannot find as test/demo system we use in the wiki to be able to check if geocoding service is specified there or not. Locally i cannot reproduce this issue. Do we know for sure geocoding service is set up for that server?

**Comment by markusmann-vg** [comment]
Maybe it's not. I will ask it tomorrow if that can be confirmed for the system they tested

**Comment by kwa20** [comment]
@BarnaBartha @markusmann-vg I can generate coordinates on individual forms on that system so I think it should be configured.

**Comment by bernardsilenou** [comment]
The same class of  bug as #4912, both can be addressed as one

**Comment by syntakker** [comment]
I cannot reproduce the issue locally either.

**Comment by MateStrysewske** [comment]
Feature will be temporarily disabled due to performance problems and should be revisited together with #4938

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske I think this as well as #4912 can be moved back to the backlog now

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen My expectation is that it might actually be resolved with the last update. @kwa20 Do you know whether this still happens?

**Comment by kwa20** [comment]
@MateStrysewske @DavidBaldsiefen As far as I can see there seems to be no error anymore when generating the coordinates. I'll close it
