### ISSUE TITLE
[Climedo Interface] Deleting entities in Sormas does not lead to the deletion in Climedo

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4898]
### Bug Description
#4830 enabled the possibility to delete cases or contacts in Sormas which leads to the deletion in Climedo. This, however, is not the case. Data remains in Climedo after deleting entities in Sormas.
### Steps to Reproduce
1. Register a person (case/contact) in the symptom journal
2. delete all entities for that person in Sormas
3. Check the corresponding climedo instance for the previously deleted entity

### Expected Behavior
When the respective entities for the person are deleted in Sormas, the person should also be deleted in Climedo

### Screenshots
<img width="1009" alt="Screen Shot 2021-03-26 at 1 44 02 PM" src="https://user-images.githubusercontent.com/70317594/112637289-44e66b00-8e3e-11eb-8f1f-20b3971593c8.png">

<img width="508" alt="wandaPersons" src="https://user-images.githubusercontent.com/70317594/112637056-0b156480-8e3e-11eb-9e2f-9839272fbcd5.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 This doesn't really sound like it's problem on our side if the notification mechanism from #4830 works as it's supposed to work. @FredrikSchaeferVitagroup can you verify whether this requires an action from our side?

**Comment by kwa20** [comment]
@MateStrysewske The notification you're talking about is likely something not displayed for a user but directed to the climedo instance right? So I wouldn't expect a notification to pop up?

**Comment by MateStrysewske** [comment]
@kwa20 Exactly. If those notifications aren't working properly, that's something we need to fix. If they are working as expected, it would mean that there's missing logic at Climedo that responds to these notifications, and that would mean that there's nothing we can do about it.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 As far as I am aware, what is described as expected behaviour here was never specified and is questionable (needs to be discussed).
#4830 is about informing external journals about changes in person data (e.g. follow up status) when cases/contacts get deleted. It is not about automatically deleting those persons from the external journal. Removing persons from the external journal can be done from within SORMAS, but manually (see https://github.com/hzi-braunschweig/SORMAS-Project/issues/4516).

And yes, there is no feedback from climedo systems regarding success of updating data from SORMAS. I am also not aware of any such functionality for registered persons.

So, from my point of view, there is nothing to to here as bugfix. The expectations mentioned here are or might be useful features, so they might be turned into feature requests @kwa20 ?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I see, thank you. To clarify, what is expected behaviour in #4830 would be that when I delete entities in Sormas that were under follow-up, the person info does not get deleted in climedo but rather the associated person would no longer receive questionnaires from the symptom journal because there is no entity under follow-up anymore?

I guess we could turn this into a feature request but would probably then have to specify that deleting should only take place if all related entities for that person that are under follow-up were deleted. If the person in question no longer receives questionnaires it's probably fine as it is though.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 It is supposed to be just as you described.

Yes. Deleting the persons from climedo would be an option if there are no cases/contacts for that person anymore. As far as I know, there is a deletion concept in the making which should explain when which data has to be removed from where? It may be a good idea to wait for that before implementing automatic deletion processes.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @MateStrysewske Ok got it. I could now see whether this is the case after one day has passed after registration and deletion and it seems that deleting entities under follow-up in Sormas does not cancel the questionnaires coming in through Climedo.

Entities and subsequently person deleted in Sormas:
<img width="670" alt="Screen Shot 2021-03-27 at 10 27 46 AM" src="https://user-images.githubusercontent.com/70317594/112716611-9eef3b00-8ee7-11eb-9ffc-86ef7bb0ee52.png">

person under follow-up in climedo:
<img width="1080" alt="Screen Shot 2021-03-27 at 10 26 05 AM" src="https://user-images.githubusercontent.com/70317594/112716613-a44c8580-8ee7-11eb-886e-8d1987fdee8b.png">

Day 2 is today, the entity was deleted yesterday.

person details:
<img width="421" alt="Screen Shot 2021-03-27 at 10 32 23 AM" src="https://user-images.githubusercontent.com/70317594/112716662-f8f00080-8ee7-11eb-85bc-31578a858831.png">

**Comment by FredrikSchaeferVitagroup** [comment]
I could reproduce this behaviour on https://ga1.sormas-oegd.de/. Fetching the person data for a registered person without a contact/case via REST (as climedo does), I get `followUpStatus: null` and `latestFollowUpEndDate: null`. I think this is the appropriate answer. Maybe Climedo does not interpret these values as expected.

One could argue that followUpStatus: `NO_FOLLOW_UP` would be more logical here. Speaking against `NO_FOLLOW_UP` is that `null` is closer to the actual state of the person. Returning NO_FOLLOW_UP seems a bit like making up data when there actually is none. @MateStrysewske Do you have an opinion about that?

**Comment by MateStrysewske** [comment]
@FredrikSchaeferVitagroup null seems like the better solution to me as well since there's actually no entity associated with the person that could have follow-up.

**Comment by FredrikSchaeferVitagroup** [comment]
> @FredrikSchaeferVitagroup null seems like the better solution to me as well since there's actually no entity associated with the person that could have follow-up.

Okay. I will communicate this to climedo today.

**Comment by FredrikSchaeferVitagroup** [comment]
@DraganMileski just informed me that climedo will soon be able to automatically stop follow up when retrieving `followUpStatus: null` and `latestFollowUpEndDate: null`. This should resolve the issue.

The fix shall be available on https://ga1.sormas-oegd.de/ by April 2nd and rolled out in their release next week.
