### ISSUE TITLE
Bulk selection boxes are missing for case contacts

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4902]
### Bug Description
When in the contact tab of cases, the bulk selection boxes are unavailable which makes it impossible to perform bulk actions
### Steps to Reproduce
1. Log in as user with bulk editing rights
2. Open a case with multiple contacts
3. Try performing a bulk action

### Expected Behavior
contacts in the list should be able to be selected individually to then perform bulk actions on.
### Screenshots
<img width="763" alt="bulkEditCaseContacts" src="https://user-images.githubusercontent.com/70317594/112661058-66ebe780-8e56-11eb-834c-c8e4b08885dc.PNG">
<img width="768" alt="bulkEditCaseContacts2" src="https://user-images.githubusercontent.com/70317594/112661065-681d1480-8e56-11eb-9874-789b391abc7d.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.59.0-snapshot on local environment
