### ISSUE TITLE
Continent and subcontinent fields are not hidden when no entries exist in configurations

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4903]
### Bug Description
When no entries exist for continents and subcontinents, fields are still displayed in respective forms.
### Steps to Reproduce
1. Go to configurations and make sure that there are no entries for continents and subcontinents
2. Go to epiData and check exposures for respective fields

### Expected Behavior
Fields should be hidden if no entries exist
### Screenshots
<img width="851" alt="continentsNoEntries" src="https://user-images.githubusercontent.com/70317594/112661900-55570f80-8e57-11eb-8382-ed981b9ac7cf.PNG">
<img width="847" alt="subcontinentsNoEntries" src="https://user-images.githubusercontent.com/70317594/112661904-57b96980-8e57-11eb-8dd9-058049b68b3a.PNG">
<img width="491" alt="continentSubcontinentNotHidden" src="https://user-images.githubusercontent.com/70317594/112661908-58ea9680-8e57-11eb-9575-4241a171eedc.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of Sormas 1.59.0-snapshoot on local environment
