### ISSUE TITLE
Multiple columns in configurations result in an error while sorting

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4908]
### Bug Description
Multiple columns in configurations result in an error when trying to sort them. Such include:
|Column|Tab|
|:--------|:---|
|Name|Continents|
|Name|Subcontinents|
|Subcontinent|Countries|
|Country|Regions|
### Steps to Reproduce
1. Go to configurations and the respective tabs
2. Sort the respective columns

### Expected Behavior
All columns should be sortable
### Screenshots
<img width="670" alt="countryColumnSort" src="https://user-images.githubusercontent.com/70317594/112678105-d7046880-8e6a-11eb-85c6-7dac98ad3ee5.PNG">
<img width="630" alt="subcontinentColumnSort" src="https://user-images.githubusercontent.com/70317594/112678117-d9ff5900-8e6a-11eb-9b13-2e1691689dd5.PNG">
<img width="605" alt="subcontinentNameSort" src="https://user-images.githubusercontent.com/70317594/112678129-dc61b300-8e6a-11eb-9837-5c93d96c132b.PNG">
<img width="620" alt="continentNameSort" src="https://user-images.githubusercontent.com/70317594/112678148-e1266700-8e6a-11eb-841f-4a3469532f52.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest version of Sormas 1.59.0-snapshot on local environment
