### ISSUE TITLE
Events > "Type of place" filter displays too many values

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4909]
### Bug Description
In the Event Directory, the "Type of place" filter allows filtering for IfSG relevant places, even on non-DE configured servers. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4761

### Steps to Reproduce
1. Events > Event Directory
2. Show more filters > Type of place
3. XX (XX IfSG) listings visible (3x)

### Expected Behavior
IfSG values should only be visible on DE servers.

### Screenshots
![image](https://user-images.githubusercontent.com/65529128/112694283-610bfb80-8e82-11eb-84b7-bfabc25b27b4.png)

### System Details
* Device: Web
* SORMAS version: 1.58
* Android version/Browser: Chrome
* Server URL: test-ch
* User Role: admin + national user

### Additional Information
@syntakker

**Comment by kwa20** [comment]
These values should also be hidden on german servers actually since they're not part of the events.

**Comment by syntakker** [comment]
@kwa20 Yes, they are invisible on all instances everywhere except for the ActivityAsCase form on German instances. The visibility chercker for the filter bar was missing.

**Comment by Candice-Louw** [comment]
Thank you @syntakker ! :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest version of Sormas 1.59.0-snapshot on local environment
