### ISSUE TITLE
Link to case classification rule document is broken

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4915]
### Steps to Reproduce
1.
2.

### Screenshots
![image](https://user-images.githubusercontent.com/12996724/112707618-fb813480-8eac-11eb-80f3-eafd1b059828.png)

### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by syntakker** [comment]
Cannot reproduce locally nor on test-de.sormas.netzlink.com.
@bernardsilenou which system are you testing on?

**Comment by bernardsilenou** [comment]
@syntakker I did it on test1401 and test 1402
I just tried on https://release-international.sormas.netzlink.com/sormas-ui/ and it works fine.
This may be due to server configuration at netzlink, so we can close the ticket.
