### ISSUE TITLE
Missing strings for column headers in event participant tab

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4917]
### Bug Description
On the event participant list, newly added columns "pathogen test result" and "sample date time" are untranslated and strings are unavailable to be translated
### Steps to Reproduce
1. Open any event and go to the event participant tab
2. Set the language of the system to something other than english
3. check the column headers

### Expected Behavior
column header should be available for translation and eventually translated
### Screenshots
<img width="276" alt="missingStringsEp" src="https://user-images.githubusercontent.com/70317594/112717134-efb46300-8eea-11eb-959b-3a11b81f04c0.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com
