### ISSUE TITLE
Typing error in facility types

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4918]
### Bug Description
The facility type "Refugee accommodation/ initial reception facility" is misspelled as **Refrugee...**
### Steps to Reproduce
1. Go to configurations
2. Select Residence in facility category
3. open the facility type drop-down

### Expected Behavior
Refugee...
### Screenshots
<img width="319" alt="refrugeeTypingError" src="https://user-images.githubusercontent.com/70317594/112717750-e62cfa00-8eee-11eb-9212-c2362a6dd32b.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the local environment on the latest version of sormas 1.59.0-snapshot

**Comment by kwa20** [comment]
@AndyBakcsy-she I just noticed that accommodation is still misspelled. Should this be a separate issue?

**Comment by DavidBaldsiefen** [comment]
@kwa20 should have been fixed here https://github.com/hzi-braunschweig/SORMAS-Project/pull/5186

**Comment by kwa20** [comment]
@DavidBaldsiefen perfect, thank you!
