### ISSUE TITLE
Unsaved changes prompt appearing on person form without changes being made

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4920]
### Bug Description
When navigating out of the person forms, the unsaved changes prompt appears even though no changes have been made. This only appears when geo coordinates are entered.
### Steps to Reproduce
1. Open a person form where geo coordinates are entered, otherwise, enter geo coordinates and save.
2. Navigate out of the form

### Expected Behavior
The unsaved changes prompt should only appear when changes have actually been made.
### Screenshots
<img width="612" alt="unsavedChangesPromptWithoutChanges" src="https://user-images.githubusercontent.com/70317594/112721893-b1c53800-8f06-11eb-94ed-baee3e4921ec.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin + national user, community officer

**Comment by syntakker** [comment]
In a first attempt, I could not reproduce. It sounds a bit like this issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/3014#issuecomment-746082371
@kwa20 what's your setting? In terms of:
- browser language
- SORMAS user language
- SORMAS server locale

**Comment by kwa20** [comment]
@syntakker It seems like the same issue, yes.

- browser language: german, english
- user language: english, german
- server locale: germany

I tried the combinations and the difference is the browser language. If it's set to german, the prompt is triggered even though no changes have been made.

**Comment by syntakker** [comment]
I tried to reproduce with any of the combinations you listed, the bug did not manifest. I also tried on test-de.sormas.netzlink.com, same result.
However, given the number of bugs that cannot be reproduced locally or on other instances (this, #4897, #4905,  #4922) might be a sign that test1401 is cursed.

**Comment by syntakker** [comment]
@markusmann-vg  can we get the `sormas.properties` from test1401.sormas-oegd.de?

**Comment by kwa20** [comment]
@syntakker You can probably not reproduce it because test-de.sormas.netzlink.com does not have geo coordinate generation configured. I guess this might have an impact.

**Comment by syntakker** [comment]
Ok, I tried to reproduce on the person tab in a case. I'll try again in the person directory.

**Comment by kwa20** [comment]
@syntakker case person tab should also suffice for reproducing it as long as geo coordinates were generated. At least that's where it happened on my end

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of 1.59.0-snapshot on local environment
