### ISSUE TITLE
Inconsistent pseudonymization for community officer on person directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4921]
### Bug Description
When opening the person directory as a community officer, persons that the user should not be allowed to see are not pseudonymized. Further, these persons also appear in filtered lists that don't seem to have a related entity that the user has access to.
### Steps to Reproduce
1. Log in as a community officer
2. check persons and their respective entities outside the users jurisdiction
3. Navigate to these entities and check person forms and lists there
4. Compare filtering of the person directory with the entities that the users has access to

### Expected Behavior
The community officer should only see the persons on the directory that they have access to. Otherwise, these persons should also be pseudonymized. The filter should not show entity relations that the user doesn't see inside of the person form.
### Screenshots
Person form (seen as community officer):

<img width="671" alt="ComOffPseudo" src="https://user-images.githubusercontent.com/70317594/112722095-cce47780-8f07-11eb-8572-3b6a1268c6a5.PNG">

Event participant person form:

<img width="666" alt="ComOffPseudo2" src="https://user-images.githubusercontent.com/70317594/112722096-ceae3b00-8f07-11eb-9182-f35c8acf71e2.PNG">

Event participant tab:

<img width="842" alt="ComOffPseudo3" src="https://user-images.githubusercontent.com/70317594/112722100-cfdf6800-8f07-11eb-88c1-c37b742b050b.PNG">

Filtered person directory:

<img width="494" alt="wrongFiltering" src="https://user-images.githubusercontent.com/70317594/112722102-d372ef00-8f07-11eb-9de1-0192213ba2a7.PNG">

Person form (seen as admin + national user): _compare with first screenshot_

<img width="684" alt="wrongFiltering2" src="https://user-images.githubusercontent.com/70317594/112722107-d66ddf80-8f07-11eb-967b-32acf5f4341d.PNG">

### System Details

* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by RazvanHodisan** [comment]
Validated on 1.60.0-SNAPSHOT.
