### ISSUE TITLE
Any case contacts exports result in an error and produce empty files

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4923]
### Bug Description
When trying to export case contacts, all export options result in an error and produce empty files, if any can be opened at all
### Steps to Reproduce
1. Go to a case and the contacts tab (case should have contacts)
2. Perform any available export

### Expected Behavior
Exports should be successful
### Screenshots
<img width="847" alt="exportFail" src="https://user-images.githubusercontent.com/70317594/112726341-2dca7a80-8f1d-11eb-9452-3cc22a4912b5.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox 
* Server URL: test1401.sormas-oegd.de, test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.59.0-snapshot on local environment
