### ISSUE TITLE
Filtering on any directory doesn't work properly when the bulk edit mode is enabled

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4924]
### Bug Description
When the bulk edit mode is enabled on any directory, filters cannot be applied properly. Only exiting the bulk edit mode then displays the filtered directory list in a correct way.
### Steps to Reproduce
1. Go to any directory (e.g. task management)
2. Enable the bulk edit mode
3. Set filters and click apply
4. check for the execution of filters
5. leave the bulk edit mode and check the list again

### Expected Behavior
Filtering normally should be possible in the bulk edit mode.
### Screenshots
filtering in bulk edit mode with region as an example:

<img width="847" alt="bulkFiltersTasks" src="https://user-images.githubusercontent.com/70317594/112728183-59059780-8f26-11eb-8b0c-7f19204839c8.PNG">

another example: numbers in filter buttons are not updated according to filters

<img width="849" alt="bulkFilterBug" src="https://user-images.githubusercontent.com/70317594/112728604-6754b300-8f28-11eb-9aa1-dcf64a97b666.PNG">
<img width="846" alt="bulkFilterBug2" src="https://user-images.githubusercontent.com/70317594/112728607-691e7680-8f28-11eb-8d58-b6aa2348a968.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
This is related to #4558 and was supposed to be fixed there. We'll have to have another look at it.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshoot
