### ISSUE TITLE
Sorting columns result in error on contact directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4925]
### Bug Description
When trying to sort columns columns on the contact directory (default and detailed view), an error occurs.
default view: first name, last name
detailed view: first name, last name, sex, age, district, postal code, city, street, house number, additional information, primary phone number, source case, reporting user

### Steps to Reproduce
1. Go to the default and detailed view on the contact directory
2. Sort first and last name columns

### Expected Behavior
Columns should be sortable
### Screenshots
<img width="713" alt="contactNameSortError" src="https://user-images.githubusercontent.com/70317594/112752312-c53dd500-8fd2-11eb-8b3c-5a777bff2ac9.PNG">

not all included on screenshot!

<img width="848" alt="contactNameSortError2" src="https://user-images.githubusercontent.com/70317594/112752587-0b476880-8fd4-11eb-9b20-566196b2f1e1.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de, test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.59.0-snapshot deployed on test.sormas.netzlink.com
