### ISSUE TITLE
Merging of cases produces multiple primary contact details

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4926]
### Bug Description
When cases are merged whose persons both have primary contact details, both details remain primary in the merged person and lead to erroneous case (detailed) and person directories
### Steps to Reproduce
1. create duplicate cases with primary contact details each
2. merge these cases and then navigate to case (detailed view) and person directories
3. then, check the contact details of the person

### Expected Behavior
When cases and associated persons are merged, the adopted contact details should lose their primary status so that data remains valid. Only the details of the chosen case (person) should remain primary when multiple exist for one type.
### Screenshots
<img width="817" alt="personDirectoryError" src="https://user-images.githubusercontent.com/70317594/112755295-523b5b00-8fe0-11eb-9ad9-28114929e3f7.PNG">
<img width="845" alt="errorCaseDetailedView" src="https://user-images.githubusercontent.com/70317594/112755379-b8c07900-8fe0-11eb-8618-4100d50fee01.PNG">
<img width="843" alt="caseMergePhone" src="https://user-images.githubusercontent.com/70317594/112755299-57000f00-8fe0-11eb-83e7-405f9d250e49.PNG">
<img width="470" alt="multiplePrimaries" src="https://user-images.githubusercontent.com/70317594/112755662-f1ad1d80-8fe1-11eb-93ce-6bc6af06489e.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by vidi42** [comment]
To check for duplicates: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4922#issuecomment-809265204

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of Sormas 1.59.0-snapshot on local environment
