### ISSUE TITLE
Sorting of primary phone number results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4927]
### Bug Description
When users try to sort the primary phone number column on the case directory (detailed view), an error occurs.
### Steps to Reproduce
1. Go to the detailed view of case directory
2. sort the primary phone number column

### Expected Behavior
column should be sortable
### Screenshots
<img width="846" alt="caseDetailedViewSortError" src="https://user-images.githubusercontent.com/70317594/112755524-4f8d3580-8fe1-11eb-9f8e-e0d3dcc051c9.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
