### ISSUE TITLE
Event ID shows up too many times in custom export for event participants

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4929]
### Bug Description
When creating a new configuration for the event participant export, the event ID shows up too many times.
### Steps to Reproduce
1. Open an event and go to the event participant tab
2. Create a new custom export configuration
3. Check selection options

### Expected Behavior
Event ID should only appear once and the other three should be event participant Id, case Id or person Id.
### Screenshots
<img width="384" alt="eventParticipantExport" src="https://user-images.githubusercontent.com/70317594/112762700-5deb4980-9001-11eb-9de3-406e653a9f90.PNG">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 This is a UI problem because the property captions are wrongly calculated. It's definitely annoying, but nothing that we should consider a blocking issue for this release. I'll move it to 1.59.0.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
