### ISSUE TITLE
ContactDto.contactClassification is not required in the API

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#4937]
### Bug Description
It is possible to post a contact to the API which has no `contactClassification` field. However, this triggers NPEs down the pipeline. 

### Expected Behavior
The API requires and **validates** that this field is present. Just adding an `@Required` annotation establishes a contract, but a client is still free to ignore this. 

In the long term, we need to make sure that all fields that are annotated as required are also validated in the API and if they are missing, the request needs to return an error @vidi42

### System Details
* SORMAS version: latest develop

**Comment by MateStrysewske** [comment]
Coming from #4739, we should use `NotBlank` instead of `NotNull` for text fields, e.g. person first and last name, to make sure that it's not possible to enter only whitespaces for those fields.

**Comment by JonasCir** [comment]
@MartinWahnschaffe This is b/c our own `@Required` annotation does nothing (unlike `@NotNull` etc.) why we deprecated the usage of it some time ago. I did a quick search and we use it on 76 DTO fields in `sormas-api`. My proposal is to just to remove it. The person doing it should take a look at #4961.
