### ISSUE TITLE
[Symptom Journal] Cancel external follow-up button is non-reactive when using PIA

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4943]
### Bug Description
After registering persons in the PIA symptom journal, the "cancel external follow-up" does not react.
### Steps to Reproduce
1. Open a case/contact person and register them in PIA
2. Select the symptom journal button again and try cancelling the follow-up

### Expected Behavior
Canceling the follow-up should cancel the external follow-up and notify the user about the successful (or unsuccessful) cancellation.
### Screenshots
<img width="1100" alt="Screen Shot 2021-03-29 at 5 44 51 PM" src="https://user-images.githubusercontent.com/70317594/112870251-4de56f80-90be-11eb-8bce-8681ff44e566.png">

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: chrome
* Server URL: release-de.sormas.netzlink.com
* User Role: admin, antional user

**Comment by kwa20** [comment]
@jkheise @soja-hzi @irinajanzen-hzi

**Comment by FredrikSchaeferVitagroup** [comment]
The button is not reactive because SORMAS (and its developers) don't know of a API endpoint in PIA to delete persons.
So we need to either get specification from conventic of how to externally delete a person in PIA, or hide the button for instances connected to PIA.

**Comment by ghdoergeloh** [comment]
Follow-up in PIA is asynchronously connected to the SORMAS API, which calculates the "Latest Follow-up End Date".A daily job requests this information from SORMAS and stops tracking if this date is in the past or there is no date ( null ) (so this behavior depends on the returned values from SORMAS). Another option to cancel follow-up is not implemented yet.

**Comment by FredrikSchaeferVitagroup** [comment]
Then I suggest to do nothing but to show a popup window stating:

`The external journal has not yet provided a function to unregister persons from within SORMAS. Please manually delete the person from the external journal.`

If a person gets deleted manually, PIA needs to set the symptom journal status to DELETED via the ``/visits-external/person/{personUuid}/status`` API endpoint. @ghdoergeloh Is this already implemented?

**Comment by ghdoergeloh** [comment]
Usually users are not deleted manually in PIA.

Based on the Latest-Follow-Up-End-Date which is queried by a daily job at SORMAS, it is checked whether a user should continue to receive questionnaires. If the date supplied by SORMAS is in the past, or if no date is supplied (null), the user will not receive any further questionnaires.

When all questionnaires have been answered and sent to SORMAS, the user is deleted and the DELETED status is sent to SORMAS.

**Comment by FredrikSchaeferVitagroup** [comment]
@ghdoergeloh Yes, but this issue is not about cancelling follow up in general (which is what the follow up end date and the follow up status is about). It is about cancelling follow up in PIA (and continuing it manually). So just setting the follow up end date to `null` would be wrong.

And I have seen the option to manually delete a person in PIA. So is my suggested approach feasible? It is subject to change anyway when PIA starts using the seamless integration into SORMAS.

**Comment by ghdoergeloh** [comment]
Ah okay, now I understand the issue. I have not tested deleting a person in PIA on a SORMAS-System, but I think it should work and also send a DELETED message to sormas.

**Comment by FredrikSchaeferVitagroup** [comment]
@ghdoergeloh Could you maybe check this? I tried on https://test-de2.sormas.netzlink.com/, but I could just get as far as this:
![image](https://user-images.githubusercontent.com/67001822/116844994-efdc0880-abe4-11eb-8e12-025895712834.png)
There should be a way to delete persons from pia...

**Comment by FredrikSchaeferVitagroup** [comment]
@ghdoergeloh Also it is not just important to know if the possibility to delete theoretically exists, but also if it can be done on production instances (and what is required if not).

**Comment by jkheise** [comment]
@FredrikSchaeferVitagroup @ghdoergeloh the ability to manually delete contact person or cases in SORMAS-SB exists and works well. Its a crucial feature when contacts or cases wish to revoke the use of PIA. 
![SORMAS-SB withdrawl](https://user-images.githubusercontent.com/77160218/116847196-5879b400-abea-11eb-95fd-e7dc4a71c983.png)
But it´s a little bit inconvenient and would definitely be nice to have the button in SORMAS to cancel the follow-up. Until we get that implemented, I think Fredrik's suggestion with the pop up window is a good idea.
