### ISSUE TITLE
The new Continent/Subcontinent/Country fields are not mapped when sharing S2S

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#4946]
### Bug Description
The new Continent/Subcontinent/Country fields are not mapped when sharing S2S.
### Steps to Reproduce
1. Update a case by setting the country of the person and add exposure and activity as case with country
2. Share with another SORMAS instance
=> Continent/Subcontinent/Country fields are empty on the second SORMAS instance

### Expected Behavior
Continent/Subcontinent/Country fields on the second SORMAS instance should have the same values as on the fist one 
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.61.0-SNAPSHOT 
using the test-de1 and test-de2.sormas.netzlink.com environments for S2S sinchronisation
