### ISSUE TITLE
`Apply Filters` is not working for `Bulk Edit Mode` for Sample tab with ~5K records

### ISSUE THREAD

**Issue by cazacmarin** [hzi-braunschweig/SORMAS-Project#4947]
### Bug Description
When entering in `Bulk Edit Mode` and trying to delete only COVID samples, by applying DISEASE filter for COVID, and pressing `Apply Filters` button, samples were not filtered and all samples are still reported. If user will select all of them in order to delete, all samples will be deleted, and not only COVID one.

### Steps to Reproduce
1. This issue is happening only on DB with a lot of Records.
2. Restore attached DB witch contains ~5K samples. ~3.5K samples are with disease COVID and ~1.5k - with disease Monkeypox
3. Start the application. Login with user admin(default password)
4. Navigate to samples tab. Enter in `Bulk Edit Mode`
5. Select `COVID-19` Disease and press `Apply Filters` button.

### Expected Behavior
Only `COVID-19` samples should be displayed. 

### System Details
* SORMAS version: 1.59
* User Role: admin

### Additional Information
Attached DB on which the problem has been simulated.
[sormas_dump_23.03.2021_4907SAMPLES_with_1000_additionalTestsLinkedToThem.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6227392/sormas_dump_23.03.2021_4907SAMPLES_with_1000_additionalTestsLinkedToThem.zip)

### Workaround
If the filter was applied, and only after user is entering in bulk mode, than only filtered records will be displayed.

**Comment by leventegal-she** [comment]
Couldn't reproduce using the database dump provided even with ~10k samples the filters work without issues.
