### ISSUE TITLE
[Angular] Case Hospitalisation tab

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4948]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/p/hospitalization-case-tab
German system: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/Vro8Zr8

- The date picker only shows up when the user has selected "Yes".

NOTE: Hospital field: "health_facility" (**other_facility** -> then you need to fall back to the "health facility details"). If other facility is selected -> display the "health facility details", else the name filed of the facility.

For this task we will ignore the right hand side cards section (these will be resolved in a future task).

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by cristinacoza** [comment]
UI/UX review done.
Looks good, just a note: for some reason the hospitalisation page background is white and it should be Neutral 50 (#F5F7FA)
