### ISSUE TITLE
[Angular] Case Symptoms tab [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4949]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/p/symptoms-case-tab
German System: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/YG58EGL

- We will be using dynamic forms
- Include the dropdown value options functionality existing in the curent Sormas (it's dynamic based on what you fill in the above form - only the selected values will show up in the dropdown).
- NOTE: The "select all" option will be something custom (we will be injecting a custom component in the dynamic form).

### Possible Alternatives
N/A
### Additional Information
N/A

### Story Points: 3 POINTS

**Comment by cristinacoza** [comment]
UI/UX Review Done, everything looks good!
