### ISSUE TITLE
[Angular] Case Follow up tab [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4952]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes

### Feature Description
Design: 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/5FB2F5AC-B3C6-4163-81FA-E79C61622DF3

@MateStrysewske - can we bring all of the follow up entries on one call ? How many items can there be ? (10', 100', >1000')

For this task we can ignore the quick action: Add / Edit Visit (this will be done a future task).

NOTE: Task dependent on: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5710

### Possible Alternatives
N/A

### Additional Information
N/A

### Story Points: 2 POINTS

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup For contacts, there usually won't be more than ~30 follow-up entries; it may be more if more than one follow-up call is made on one day, but that's very rare. For cases, it can be more, but it's basically impossible that it's more than 100 (and even that will most likely not happen) - so yeah, I don't think we need lazy loading for those.

**Comment by laurentiustanvitagroup** [comment]
*Review Done*
Task is completed and it looks as per the design. It can now be move to "Done".
