### ISSUE TITLE
[Angular] Case Clinical Course (Pre Existing Conditions) tab [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4953]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/p/clinical-course-case-tab
German System: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/7yax0y8

- The upper part will be using Dynamic forms
- The second part (table) will be a new component (ignored in this task)

### Possible Alternatives
N/A

### Additional Information
N/A

### Story Points: 2 POINTS

**Comment by cristinacoza** [comment]
UI/UX review Done
