### ISSUE TITLE
[Angular] Tasks (basic structure)

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#4955]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes

### Feature Description
Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/p/tasks
- This task should focus only on the basic structure:
- "Tasks" module with components (only creating them)
- Routing and Sub-routing
- The baseline services (extending the base-service).

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by cristinacoza** [comment]
UI/UX Review done
