### ISSUE TITLE
Enforce DTO fields marked as @Required to be present in the request

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#4959]
### Bug Description
Currently we have the possibility to annotate DTO fields as required. However, as of now this is purely cosmetic and used by openAPI to create a contract which fields must be included in a correct request. Any (malicious) client is of course free to send whatever he likes and therefore is able to trigger exceptions and store malformed data which cannot be retrieved properly.

### Steps to Reproduce
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/4937 as example. There are more severe issues where you can store cases/contacts via the API, but cannot open the details page or do not show up at all in the list views because of NPEs.

### Expected Behavior
The API checks the request body properly for missing fields and returns HTTP 400 (Bad Request) in case a required filed is not provided.

**Comment by JonasCir** [comment]
```
@POST
@Path("/push")
public List<PushResult> postCases(@Valid List<CaseDataDto> dtos) {
    return savePushedDto(dtos, FacadeProvider.getCaseFacade()::saveCase);
}
```
We already have a validation in place, however, `@Required` is not registered as custom validator. [Here](https://docs.oracle.com/javaee/7/tutorial/bean-validation-advanced001.htm#GKFGX) is described how to create them.

**Comment by MateStrysewske** [comment]
Coming from #4739, we should use `NotBlank` instead of `NotNull` for text fields, e.g. person first and last name, to make sure that it's not possible to enter only whitespaces for those fields.

**Comment by StefanKock** [comment]
Considered by @vidi42 and @MateStrysewske to be dropped out of 1.60 due to imposed breaking changes.

**Comment by adinaflorea9** [comment]
Verified that the issue reported initially in #11812 have been fixed with the commit added #11837 using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(fd74525).

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe Also: https://github.com/hzi-braunschweig/SORMAS-Project/issues/11822

**Comment by MartinWahnschaffe** [comment]
Todos to fix the problems:

- [ ] Set default value for mime-type in frontend #11822
- [ ] On event import only add event group to the list when referencing column has an actual value #11846

**Comment by adinaflorea9** [comment]
Verified ticket after the latest changes related to quarantine orders and event import were added, using the latest version of SORMAS from the development branch - 1.83.0-SNAPSHOT(30309b9).
