### ISSUE TITLE
Changes to event entity on mobile app [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4962]
### Feature Description
- New events are placed at the bottom 
### Proposed Change
1. Newly created and edited entities should be at the top 
2. On the event directory, under the event status, replace description with title. 
3. The duration or time since report date is random,  two envent created at the same time, one shows 19 hre ago and another show the 15 min ago. @MateStrysewske  what does this date mean pls? I suggest we use date of event  and fall back to report date here and sort them accordingly.
4.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas on  mobile phone

**Comment by VitaliHZI** [comment]
I tested on my Mobile Tablet and can not confirm that this bug is resolved. Number 2 of the description of the issue is not resolved. I see not the title i still see the Description in the app. 

If only number 1 were in scope than its ok.

**Comment by MateStrysewske** [comment]
@VitaliHZI The second point is basically a change request, I think that's why we overlooked it when implementing this bugfix. I'll open a separate issue for it.

**Comment by MateStrysewske** [comment]
#5286

**Comment by VitaliHZI** [comment]
Ok than its fine for me. Thanks.
