### ISSUE TITLE
Mobile app should sync bidirectionally with server

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#4963]
### Bug Description
- sync shows successful but all entities are sent to the server
### Steps to Reproduce
1. Create a case on server side using surveillance officer role
2. Check if the case is on the mobile app using the same role, case is not there
3. Repeat same for contacts, this time create the contact  + case on from the mobile app
4. Check if it is on the server

### Expected Behavior
- All entities should sync in both directions
### System Details
* Device: samsung
* SORMAS version: 1.58.1
* Android version/Browser: 9
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: surveillance officer + contact officer

**Comment by bernardsilenou** [comment]
The is something abnormal about POE cases during sync process, they return a warning message on the mobile app when created from the web, good  to investigate why.

**Comment by bernardsilenou** [comment]
@vidi42  Is there a reason why you dropped this issue?
We need this in order to approve 1.59

**Comment by MateStrysewske** [comment]
@bernardsilenou Readded it

**Comment by MateStrysewske** [comment]
@bernardsilenou I've created a Surveillance Officer + Contact Officer on that server and had absolutely no problems to sync cases from web to app and a case + contact from app to web. Can you please confirm that there is actually a bug?

**Comment by bernardsilenou** [comment]
@MateStrysewske which version should I test please? 1.59  for 1.58.3 ?

**Comment by bernardsilenou** [comment]
@MateStrysewske I openned this bug about 1.58.1 connected on https://release-international.sormas.netzlink.com/sormas-ui/
My tablet is on 1.58.1 and server is on 1.58.3, auto update does not work, internet connection is perferct, I got the message "try again later"
After choosing update later and entered pin, I immaterially got the red flash error message and it immediately disappeared. App function normally but when either sync or resync, I got "background sync in process" and got blocked there.
Restart the device but same situation.
I  had some unsync entities on the mobile app while server was till on 1.58.1
I can set fresh installation on another tablet to test if the synchronization is working with 1.58.3, but would like to keep this tablet at this state so that we can get the auto update working. 

- The main point with this issue is that when a case/ contact  is created on the district of the surveillance officer from the web and you sync the tablet, then you get sync successfull but but some of the data were not transferred to the tablet. For entities created on the tablet, all worked fine.
- After getting sync successful, did you check that all contact / ep crated from the web  were updated on the mobile app? If yes, then we may need to focus now on auto update to1.58.3.
- Any other thing that i can do?

**Comment by MateStrysewske** [comment]
@bernardsilenou I installed 1.58.3 on my device and had no problems with synchronisation, neither from web nor from app, and all entities were successfully transferred, yes.

**Comment by MateStrysewske** [comment]
@bernardsilenou Please forward me the login details of the user you're using via mail

**Comment by bernardsilenou** [comment]
@MateStrysewske OK,  I would ask Netzlink and also setup a fresh installation of 1.58.3 and get back to you. Thanks

**Comment by bernardsilenou** [comment]
> @bernardsilenou Please forward me the login details of the user you're using via mail

Just realized you asked for login not log :), I send now pls

**Comment by bernardsilenou** [comment]
@MateStrysewske For a fresh installation of 1.58.3 of another SO in the same district, all works fine.
The other user with 1.58.1 still cannot sync nor auto update.
What we need to do now is to get the data documented on  the tablet with 1.58.1 to sync with the server without lost of data that is on the tablet.
Can you think of a better solution in such a scenario? tablet cant sync but has data documented when it was offline.

**Comment by MateStrysewske** [comment]
@bernardsilenou I have no way of testing it with 1.58.1 because the server is already on 1.58.3, so the app forces me to download and install 1.58.3 before I can log in. I also can't see any critical error in Firebase (only some "connection already established" reports which are fine).

I would either need physical access to the device, or you would need to request log files from the timestamp when the synchronization fails; maybe those contain error messages that can tell us what the problem might be.

**Comment by MateStrysewske** [comment]
@bernardsilenou Requesting logs from Netzlink could be the easier and more comfortable solution ;)

**Comment by MateStrysewske** [comment]
Closed because no development since April
