### ISSUE TITLE
User with the roles Contact Supervisor, Clinician, Surveillance Supervisor cannot create cases from event participants

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#4965]
Sorry for this issue, but maybe you having a hint for me. We are having the problem that the normal users, which are having the roles "Contact Supervisor, Clinician, Surveillance Supervisor" are not having the button to create an case from an event participant

![grafik](https://user-images.githubusercontent.com/74791118/113093097-85076e00-91ef-11eb-8596-7603a655d9db.png)

With my roles (National User, National Clinician, Admin, ReST User), I see the button:

![grafik](https://user-images.githubusercontent.com/74791118/113093126-92bcf380-91ef-11eb-9868-070a9c3bc69c.png)

As far as I remember the users used the function in the past. Was there a change?

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis You can only create cases for event participants that are somehow tied to your jurisdiction; so either because the event participant has been assigned to your jurisdiction or because it is connected to another entity that you have access to. If you'd set the responsible jurisdiction of the two event participants to the jurisdiction of the user, you would be able to create cases for them.

If that's problematic, please consider discussing this with @kwa20 and @bernardsilenou.

**Comment by Marko-ilmkreis** [comment]
Thanks for the answer, I just checked it. The event is linked to us:

![grafik](https://user-images.githubusercontent.com/74791118/113112733-ce64b700-9209-11eb-82d0-bb1b5b1eaa3c.png)

But the jurisdiction for the ep was empty:

![grafik](https://user-images.githubusercontent.com/74791118/113112774-dcb2d300-9209-11eb-83ba-aa9b823589ae.png)

The datas were also not pseudomized when it was not set to our district.

But even when I fill it with data

![grafik](https://user-images.githubusercontent.com/74791118/113112807-e5a3a480-9209-11eb-891e-3645e828c4d2.png)

the user did not have the option to create a case from ep.

The user is having the rights for our region:

![grafik](https://user-images.githubusercontent.com/74791118/113113108-4337f100-920a-11eb-818e-63518609e0dc.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis @MateStrysewske I think this issue is the same as described in #4260. We should aim for fixing this rather soon.

**Comment by MateStrysewske** [comment]
Yes, seems so. I'll close this one and move #4260 to the current sprint.
