### ISSUE TITLE
Mass activate / deactivate user accounts

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4966]
### Situation Description
To date, SORMAS accounts cannot be changed en masse.
The administrator is therefore forced to open each user file and deactivate the account by clicking on the "active" check mark.

### Feature Description
We are proposing to develop the "bulk edition" mode in the user directory, then two bulk actions to deactivate and activate the previously selected accounts in bulk.

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by bernardsilenou** [comment]
@MateStrysewske  Please can you comment, dev France wish to plan this for 1.49

**Comment by MateStrysewske** [comment]
No objections!

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
