### ISSUE TITLE
Transform several PPs into contact from the directory of event participants

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#4969]
### Situation Description
To date, the number of participants in an event and especially a cluster can be very high. The transformation of event participants into contact is very time-consuming and takes place person by person.

### Feature Description
We want to add a bulk-action to the list of event participants plus a  "line-list contact creation" action.
This action opens a pop-up that asks: (inspired by the popup for creating a new contact from the screen of an event participant).

• Common information, namely:

- disease of the source case (mandatory, pre-filled depending on the event, not editable)
- source case with choice button (not compulsory)
- responsible region (mandatory if no source case selected)
- responsible department (mandatory if no source case selected)

• Information specific to each participant (one line per participant, presentation close to the "line-list" entry of cases)

- first name of the contact (pre-filled, not editable)
- contact name (pre-filled, not editable)
- date of the report (required)
- date of last contact (not compulsory) (with possibility of contact over several days as currently)
- type of contact (not compulsory) => in the form of a drop-down list
- relation to the case (not compulsory)

### Additional Information
@ftavin @bernardsilenou  @emond-fuseau

**Comment by bernardsilenou** [comment]
@kwa20 Please have a look at this feature we discussed about. 
If it can be added directly to  contact directory and directory of contact within a case.

**Comment by kwa20** [comment]
@bernardsilenou @carolinverset I think that would be a really nice issue to support users in processing a lot of data quickly. I do think that it would be similar to implementing line listing for contacts in general (should be done with #1521) but there are some differences to be taken into account like person data which would already be available through the event participant person. We could even think of providing a line listing option for cases in the event participant tab but that should be done in a separate issue.

It could look something like this maybe:

**Comment by carolinverset** [comment]
Thank you @kwa20 for your interesting proposal. There is just one element missing I think : the difficulty arises for clusters with a very large number of contacts.

In France, we have developed the function for importing lists of participating people to prevent teams from re-entering all this information which is often available in excel files sent by partners.
From this imported list, we want to offer a bulk edition from the directory of event participants and a bulk action to transform a large number of participating events into contacts with one click. This bulk action opens a pop-up allowing to define the contact and to modify only the individual information to the participants (date of notification for example).
If I understand correctly, in your proposal and your mock-up, you will have to enter all the first and last names of all the contacts, which is very time-consuming and impossible for the teams.

I am therefore joining you to create this line listing functionality in the directory of participating events, but you have to complete it to obtain a pre-established list from the names of the participating events imported via a csv file and selected in bulk-edition mode.

@ftavin is on vacation until Tuesday but maybe it would be possible for him the next week to propose a mock-up to better visualize our proposal?

@bernardsilenou what do you think about ?

**Comment by kwa20** [comment]
@carolinverset Indeed, my initial mock-up only displays the line-listing part, so this is mainly the template for using this  during the bulk action. Personal data of the selected entries previously selected from the list would then be adopted. Here a more complete version:

<img width="751" alt="Screen Shot 2021-04-02 at 9 11 21 AM" src="https://user-images.githubusercontent.com/70317594/113391773-54ad0480-9394-11eb-84be-20ea619adfcb.png">
<img width="870" alt="Screen Shot 2021-04-02 at 9 27 55 AM" src="https://user-images.githubusercontent.com/70317594/113392677-c9347300-9395-11eb-8c35-71c9bf7cc3b5.png">

**Comment by carolinverset** [comment]
@kwa20, Great ! this is exactly what I was thinking.
Thank you very much !!

@ftavin @bernardsilenou @emond-fuseau

**Comment by ftavin** [comment]
@carolinverset the mockup corresponds to our vision, this is perfect, thank you a lot @kwa20 !

If I am right, if we want to match to the mockup we need to add the date of birth and sex to the issue description.

Initially we also wished to have the contact classification field (default "unconfirmed contact") which is not on the issue description nor on the mockup, do we still need it ?

**Comment by bernardsilenou** [comment]
@ftavin 
- DOB and sex are essential variable, so we should add please.
- For small screens, addition of new variables would not fit on a single line. So suggest we do not add contact classification. Users can do that with bulk actions I suppose

**Comment by kwa20** [comment]
@MateStrysewske @StefanKock @carolinverset @ftavin @bernardsilenou I noticed that if sex is not entered for event participants, the bulk action to create multiple contacts at once fails because the not null condition is not met. It is however not possible to just enter the sex in the line listing pop-up because it's disabled. Users would have to open each individual ep for adjustment.

<img width="848" alt="errorBulkCreateContact" src="https://user-images.githubusercontent.com/70317594/127646763-78d54cb0-d740-4abe-85d7-8753edcfc174.PNG">

Possible solutions I could think of:
1. Disable fields in pop-up only if they are not null
2. Make event participant person sex compulsory as well (as for cases/contacts) - potentially difficult because all existing ep's with missing sex will contradict this condition

Since this was already released in 1.62, I could create another issue if we can decide upon the best solution.

**Comment by MateStrysewske** [comment]
@kwa20 I would vote for making sex required in the UI - we did this for case and contact persons retrospectively as well. The only problem that this brings up is when someone tries to edit the event participant in question and it has an empty sex, but in that case they just have to update it to "Unknown". Would be great if you could create an issue for that!
