### ISSUE TITLE
REST API - POST doesn't work

### ISSUE THREAD

**Issue by MarcusSeidl** [hzi-braunschweig/SORMAS-Project#4973]
Hope someone can help ....
When I try via Postman to create a new country (or community, ....) via the REST API using a POST query (e.g. http://localhost:6080/sormas-rest/country/query) and this body
{
  "defaultName": "TestCountry",
  "externalId": "9999",
  "isoCode": "TCY",
  "unoCode": "999",
  "archived": false
}
I always get an error 400 saying:
Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of START_OBJECT token
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream);

How can I solve this issue - any help is appreciated. Thanks!

**Comment by JonasCir** [comment]
Hm I encountered a similar error in the past. Try to post an array of objects to the API i.e, `[{your_json_object}]`.

**Comment by MarcusSeidl** [comment]
Thanks #JonasCir!
I changed the body of the POST request:
[{
  "defaultName": "TestCountry",
  "externalId": "9999",
  "isoCode": "TCY",
  "unoCode": "999",
  "archived": false
}]
Now comes the error:
Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
Or should I write the body different?

**Comment by MateStrysewske** [comment]
@MarcusSeidl Hey! The `/query` endpoints don't support pushing new entries into the database, their purpose is to retrieve the data of a list of UUIDs that you post to them. There is currently no way to get infrastructure data into the system using the ReST API.

**Comment by MarcusSeidl** [comment]
Thanks for your help!

The query requests work the way you explained.

I assume push request should support pushing new entries into the database!? I tried following POST request:

http://localhost:6080/sormas-rest/persons/push

As body:
[
    "first_name":"Alex",
    "last_name": "Seidl",
    "sex": "MALE"
]

The error I receive:
Cannot construct instance of `de.symeda.sormas.api.person.PersonDto` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('first_name')
at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 2, column: 5] (through reference chain: java.util.ArrayList[0])

Any help? Thanks in advance!
Marcus

Von: Maté Strysewske ***@***.***>
Gesendet: Donnerstag, 1. April 2021 09:14
An: hzi-braunschweig/SORMAS-Project ***@***.***>
Cc: Seidl Marcus ***@***.***>; Mention ***@***.***>
Betreff: Re: [hzi-braunschweig/SORMAS-Project] REST API - POST doesn't work (#4973)


@MarcusSeidl<https://github.com/MarcusSeidl> Hey! The /query endpoints don't support pushing new entries into the database, their purpose is to retrieve the data of a list of UUIDs that you post to them. There is currently no way to get infrastructure data into the system using the ReST API.

**Comment by JonasCir** [comment]
Not certain if it is a typo but you need 
```json
As body:
[{
    "first_name":"Alex",
    "last_name": "Seidl",
    "sex": "MALE"

}]
 
```
Currently you are missing the braces inside the array.

**Comment by MarcusSeidl** [comment]
Thanks -this helped!

**Comment by JonasCir** [comment]
Great :)
