### ISSUE TITLE
[SORMAS 2 SORMAS] Receiving instances can edit person data in person directory that was sent with read access only

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4975]
### Bug Description
When users send data via Sormas 2 Sormas without handing over the ownership, the receiving instance can edit data through the person directory even though it should be read access only
### Steps to Reproduce
1. Send e.g. a case to another Sormas instance without handing over the ownership
2. open the case in the receiving instance and check case information and case person forms
3. Check the same case person also in the person directory

### Expected Behavior
When sharing data without handing over the ownership, the receiving instance should not be able to edit through the person directory.
### Screenshots
<img width="668" alt="S2SreadAccess" src="https://user-images.githubusercontent.com/70317594/113193275-14e50080-9260-11eb-900b-6b2f57b2e363.PNG">
<img width="483" alt="S2SreadAccess2" src="https://user-images.githubusercontent.com/70317594/113193282-16162d80-9260-11eb-85a6-cc1dd4fbb23b.PNG">
<img width="669" alt="S2SreadAccess3" src="https://user-images.githubusercontent.com/70317594/113193285-17475a80-9260-11eb-8578-cb3b827cac3e.PNG">

### System Details
* Device:
* SORMAS version: 1.58.1
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de, release-de.sormas.netzlink.com
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test-de1 and test-de2 environments
