### ISSUE TITLE
Country lists only display countries in one subcontinent

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4981]
### Bug Description
When selecting a country in the event section, only the countries of a single subcontinent is displayed. This seems to be the subcontinent that either the server locale is set to or that is deposited as country.name in the properties.
### Steps to Reproduce
1. Import all default infrastructure data
2. Open or create an event
3. Check countries in the drop-down list

### Expected Behavior
The full country list should be displayed in events since we don't show continent and subcontinent fields there.
### Screenshots
<img width="437" alt="countryListEvents" src="https://user-images.githubusercontent.com/70317594/113268518-c1ae9480-92d7-11eb-80f4-ce08f89a8dd9.PNG">

### System Details
* Device:
* SORMAS version: 1.58.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
This might potentially affect all other locations as well when there are no continent/subcontinent dropdowns displayed (so basically everywhere except exposures/activities as case)

**Comment by kwa20** [comment]
@MateStrysewske I checked on person forms and all countries are actually displayed there.

**Comment by Candice-Louw** [comment]
@MateStrysewske @kwa20 - same bug occurs for Case Person and Contact Person Addresses, but only on the multi-entries variant, not the default (in-line) addresses:

![image](https://user-images.githubusercontent.com/65529128/113315632-c726d180-930d-11eb-8a00-239988e6f9b9.png)
![image](https://user-images.githubusercontent.com/65529128/113315405-8af37100-930d-11eb-8705-b62c96611b7d.png)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
