### ISSUE TITLE
Disable externalId in person forms when SurvNet is configured

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4985]
### Problem Description
When the SurvNet interface is configured, the external Id is completely hidden on person forms.
### Steps to Reproduce
1. Configure the SurvNet interface
2. Navigate to person forms
3. check the external Id field

### Proposed change
external Id should not be hidden but rather greyed out 

<img width="439" alt="externalIdInterface" src="https://user-images.githubusercontent.com/70317594/113312326-78c40380-930a-11eb-96a1-e784122d1bf0.PNG">

### Screenshots
<img width="496" alt="externalIdInterface2" src="https://user-images.githubusercontent.com/70317594/113312369-7f527b00-930a-11eb-8df6-3757c9a918ff.PNG">

### System Details
* Device:
* SORMAS version: 1.58.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 This was specifically requested by you in issue #4360

**Comment by kwa20** [comment]
@MateStrysewske I guess this was a misunderstanding then. This should then be a change request for the external Id to rather be greyed out than completely hidden.

**Comment by Jan-Boehme** [comment]
So this would mean the external ID can not be edited when the SurvNet interface is in use?

That may cause some problems because I know of a few departments of health that use the external ID field to store IDs from other related systems like document management software or directly generate hyperlinks to other systems from the CSV export using the external ID in the URL.

**Comment by kwa20** [comment]
@Jan-Boehme Yes, the external Id would be used to specifically refer to the unique Id in the reporting system (e.g. SurvNet). If the external Id is filled, it would be migrated to the more flexible external Token. If this field is filled as well, the Id should be added with a delimiter.

**Comment by Jan-Boehme** [comment]
I see. Thanks for the clarification.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.59.0-SNAPSHOT on test-de1.sormas.netzlink.com environment

**Comment by kwa20** [comment]
@AndyBakcsy-she I also tested on test-de1 but on my end it looks like this:
<img width="234" alt="externalIdPerson2" src="https://user-images.githubusercontent.com/70317594/114433867-9cb4fe00-9bc2-11eb-89b7-086091d6e906.PNG">
The title is there but the field is still missing.

Expected would be the same as seen on the case tab:
<img width="215" alt="externalIdPerson" src="https://user-images.githubusercontent.com/70317594/114433937-b5bdaf00-9bc2-11eb-951d-3046ca694951.PNG">

**Comment by MateStrysewske** [comment]
@ChristopherRiedel I suspect you set the field to read-only. The correct approach (as stated both in the issue title and description) is to set it to disabled.
