### ISSUE TITLE
Subcontinent and continent headers are not available for translation on crowdin

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#4987]
### Bug Description
Headers for newly introduced fields continent and subcontinent are not available for translation.
### Steps to Reproduce
1. Go to exposures and check for continent and subcontinent fields 
2. Change the language to be something other than English
3. check headers of these fields

### Expected Behavior
Field headers should be available for translation
### Screenshots
<img width="386" alt="continentSubcontinentTranslation" src="https://user-images.githubusercontent.com/70317594/113326316-cb58ec00-9319-11eb-9f6a-b716e14515cc.PNG">

### System Details
* Device:
* SORMAS version: 1.58.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
* Add `continent` and `subcontinent` as generic caption properties (i.e. not with a prefix, but in the same way as region, district, country, etc.)

**Comment by AndyBakcsy-she** [comment]
The code change has been made. 
Although the 2 headers are not yet translated, the ticket can be marked as verified on last version of sormas 1.59.0-snapshot
