### ISSUE TITLE
Contacts converted to Cases > No Case links can be recorded (Epidemiological Data)

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#4992]
### Feature Description
It should also be possible for people who were in quarantine before they became positive to record contacts to existing index cases and then to link them in the exposure details

### Problem Description
If a person exists in SORMAS as a contact person and is then tested positive, the contact person is mutated into a case (aka "Re-Entry"). Under "Epidemiological data", the option to record "Contacts with a known index case" is deactivated and gray:
![image](https://user-images.githubusercontent.com/9933294/113112883-fce29200-9209-11eb-93c4-e327352ff0dc.png)

### Proposed Change
Record exposure details for people who were already in quarantine when they became positive. This includes that we can link contacts with known index cases on the exposure mask. This is currently not possible.

### Additional Information
https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/183

**Comment by MateStrysewske** [comment]
@Candice-Louw That looks like a bug. The field should indeed be read-only, but it should be set to "Yes" automatically and the contact list should be shown on the right side. I'll investigate this.

**Comment by MateStrysewske** [comment]
@Candice-Louw I can't reproduce this behaviour on my local system. Can you please give me a very detailed description of every step that I need to perform that leads to this problem on the affected server? Also please check whether there are any errors logged in the server logs when entering the epidemiological data screen for a case where this behaviour occurs for.

**Comment by Candice-Louw** [comment]
@MateStrysewske - this seems to have been fixed/changed in the 1.58.2 version that was updated on Tuesday evening and cannot be reproduced anymore, thank you.  Confirmed with @michadavid on the CH test system.
