### ISSUE TITLE
Using Phone-Number for document creation

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5003]
@syntakker Could you please help me out and tell me, how can I call the details of the primary contact (e.g. phone number) for a person? I have not found anything about it in the data dictionary.

**Comment by syntakker** [comment]
The primary phone number is still available as `person.phone`. The underlying method `getPhone()` resolves the primary phone number among the list of phone numbers, if there are several.
The same applies for `emailAdress`, which resolves the primary email, too.
I'll have a look why this is not documented in the Data Dictionary.

**Comment by Marko-ilmkreis** [comment]
@syntakker Thanks this works. I just double checked and its not written in the dictionary.
