### ISSUE TITLE
Filtering of tasks produces an error if no task status is selected

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5008]
### Bug Description

If you are filtering the task directory and selecting the following is produces an error:

Task status - change from pending to blank
date - set any data range

If the task status is set to pending, the filter is set properly without error.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/113841972-8bb75780-9792-11eb-8953-b08618a435cd.png)

### System Details
* Device: Win10
* SORMAS version: 1.58.2 and 1.59.0-snapshot
* Android version/Browser: FF
* Server URL: https://test-de1.sormas.netzlink.com and own instance

**Comment by Marko-ilmkreis** [comment]
I discovered, that when you switch to the tab "Officer tasks" it works

![grafik](https://user-images.githubusercontent.com/74791118/113842780-5101ef00-9793-11eb-8da3-b564a971e77b.png)

switching back to all brings the error again.

**Comment by kwa20** [comment]
@MateStrysewske @Marko-ilmkreis This issue also seems to be affected by the date filter period being set. When I don't have a date period filtered on the directory, setting the task status to null and filtering works.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot on test.sormas.netzlink.com environment
