### ISSUE TITLE
Add personcontactdetail table to database export section

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#5009]
### Bug Description
When doing a bulk database export [Statistics -> Database Export] no contact information (Email and phone number) for cases/contacts is exported.

### Steps to Reproduce
1.  Statistics -> Database Export -> Select All -> Export

### Expected Behavior
A Table containing contact information linked to the persons in person.csv should appear.

### Additional Information
This is quite urgent for us, as we use bulk exports for sending all the necessary emails to every case that has been contacted on a specific day. A workaround is possible, but quite time-consuming.

### Development Specifications
* Add the new personcontactdetail table to the database export section as a sub-checkbox of the person table; use the caption "Contact details"

**Comment by MateStrysewske** [comment]
Thanks for your report!

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sorams 1.59.0-snapshot on test.sormas.netzlink.com.
Downloaded the export and validated the contents.
