### ISSUE TITLE
Web UI currently not opening/working on mac systems

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#501]
Some of the supervisors and national users only have mac laptops and are unable to login at the moment.

**Comment by MartinWahnschaffeSymeda** [comment]
Can you provide a version for the OS and safari browser?

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Is this still a thing?

**Comment by Chinedar** [comment]
This is no longer a thing! We can close this. It works well on Mac systems
now. Kudos.
