### ISSUE TITLE
[Angular] Update the Case page with the latest design changes [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5010]
### Situation Description
- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.
- Need to make the icons rounded

### Feature Description
Updated designs:
https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/ELenvyo
https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/g01r34x
https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/a/jg47JKG
 
### Possible Alternatives
N/A

### Additional Information
N/A

### Story Points: 2 POINTS

**Comment by cristinacoza** [comment]
UI/UX review done, everything looks good
