### ISSUE TITLE
Person contact details can't be deleted

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5012]
### Bug Description
Deleting person contact details seems to work at the first glance, but reloading the person page brings it back to the list of person contact details, i.e. it's not actually deleted from the database.

### Steps to Reproduce
1. Open a person with at least one contact detail or create one
2. Open the contact detail and delete it
3. Save the form
4. Reload the page

### Expected Behavior
Contact details should be deleted from the database.

**Comment by AndyBakcsy-she** [comment]
Validated on the latest version of Sormas 1.59.0-snapshot on test-de.sormas.netzlink.com environment
