### ISSUE TITLE
Move edit columns in configuration views to the left side, to have it consistent

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#5017]
### Problem Description
In the configuration views the edit columns are currently on the right side. In all other views the column to edit/open an entry is on the left side. This is inconsistent. It is preferred to have it on the left side, to avoid side-scrolling issues.

### Proposed Change
- [ ] Move edit column in all configuration views to the left side
- [ ] Add "edit" caption to the column, as we have it in the campaign data view
- [ ] Add "edit" caption to the task edit column as-well

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com
