### ISSUE TITLE
Custom system CSV file name missing for population export and all imports

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#5018]
### Expected Behavior
- [x] use custom system name in population export file name
- [x] import template file names should also use custom system name, as export files do

Quick fixes:

- [x] Missing translation for area in regions list
- [x] Districts configuration short name should be "Districts" not "District"

**Comment by syntakker** [comment]
Further refactoring is proposed in #5119, which was omitted for now due to the proximity of the release and the risk of introducing errors.

**Comment by DavidBaldsiefen** [comment]
May this be related to #5143?
