### ISSUE TITLE
Country filter and column should not be visible in configuration view when no surveillance feature is enabled

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#5019]
### Bug Description
Currently the countries, sub-continents and continents view in configuration are only visible when a surveillance feature is enabled. The same check is missing for the country filters and the columns in the other configuration views.

### Expected Behavior
- [x] Add an isAnySurveillanceEnabled method to the feature configuration that contains the current check for "any surveillance feature"
- [x] Add an isCountryEnabled method that does the same for now (but may be changed later)
- [x] Use both methods in the AbstractConfigurationView
- [x] Add the missing checks to isCountryEnabled for the country filter and column in the other configuration views

### Screenshots
![grafik](https://user-images.githubusercontent.com/23217632/113988753-101be000-9850-11eb-8361-41c39e0b6889.png)

**Comment by syntakker** [comment]
Findings: Country column is still visible on the Regions grid
