### ISSUE TITLE
[Angular] Failing tests after the backend setup was finalised [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5026]
### Bug Description
- After the work performed on the backend setup (of Sormas) for the Angular team, there seems to be an issues with some tests failing (login)

### Steps to Reproduce
1. Decomment the currently commented tests
2. RUN: npm run e2e
3. Notice the tests failing error

test fails at : "can login using Keycloak" from ./e2e/src/app.e2e-spec.ts ... we commented the code that was failing and we will need to fix this code so it won't fail

### Expected Behaviour
- The tests should pass as in the past.

### System Details
* Device: N/A
* SORMAS version: 
* Android version/Browser:  N/A
* Server URL:  local environment
* User Role:  N/A

### Additional Information
test fails at : "can login using Keycloak" from ./e2e/src/app.e2e-spec.ts ... we commented the code that was failing and we will need to fix this code so it won't fail

### Story Points: 5 POINTS

**Comment by horia-ardelean-vg** [comment]
I've added a new environment specifically for the e2e tests and updated it to match the configuration that was previously, but it seems the test that is failing is expecting the sormas angular application to log into keycloak which doesn't happen.

This should be investigated by a developer to see what is happening during the test.
