### ISSUE TITLE
Rename "Andere Bildungseinrichtung" to "Andere Bildungs- & Betreuungeinrichtung"

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#5036]
While talking to @JaquM about another issue we realized that the german localization for one of the facility types should be renamed to better match the facility category.

Please rename "Betreuungs- und Bildungseinrichtung" --> "Andere Bildungseinrichtung" to "Betreuungs- und Bildungseinrichtung" --> "Andere Betreuungs- und Bildungseinrichtung" for the german localization.

Thank you.

**Comment by JaquM** [comment]
already changed the translation in crowdin, so I'll close this issue.
