### ISSUE TITLE
Disable warning for double used external token

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5037]
### Feature Description

Introduce a configuration, which allows to use the same external token multiple times without warnings.
### Problem Description

The external token uses a duplicate check, but in our health department, all persons of the same event are filed in one file. Therefore, the same file number is entered several times. Each time, this warning appears.

![grafik](https://user-images.githubusercontent.com/74791118/114267342-2e720f00-99fb-11eb-9147-753a557a4215.png)

### Proposed Change

Introduce a configuration, which allows to use the same external token multiple times without warnings.

**Comment by JaquM** [comment]
@Marko-ilmkreis With the connection of the SurvNet interface, this field is necessarily filled with the external token from SurvNet, so the warning is essential.

**Comment by Marko-ilmkreis** [comment]
@JaquM There might be then an error in the translation of the field names in the German version.

The field external token is translated as "file number" and the field "external id" as "external id". In the last change history the HZI informed the users that the field "external id" will be used by Survnet.

![grafik](https://user-images.githubusercontent.com/74791118/114267794-1b147300-99fe-11eb-94c4-5b0222c4ada7.png)
Source: [https://www.sormas-oegd.de/download/3314/](url)

Which field should be used for the file-number of the case/contact/ep?

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske is there an update on this issue?

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis I can't really provide feedback here because it's basically about wording and internal processes in German GAs, so I'd request further input by @JaquM or @kwa20.

**Comment by kwa20** [comment]
@Marko-ilmkreis sorry for getting back to you this late but here a little elaboration on this subject: The external Id will be used to adopt the GUID of the corresponding entity in SurvNet. This will either happen during the initial import or upon sending data to SurvNet. This Id is the unique reference that allows us to reliably reference data across systems. It is therefore also not editable when the interface will be connected. The external Token (Aktenzeichen) is also corresponding to the "Aktenzeichen" in SurvNet which means that it will also be transmitted upon sending data. The "Aktenzeichen" is flexible yet supposed to be unique and according to the RKI used for more user friendly referencing with higher health institutions. The RKI also requires this field to be editable which unfortunately somewhat contradicts the requirement of uniqueness. Thus, the message is supposed to indicate duplicate entries for this field across the system.

Judging from your screenshot, the external Token field is used for another purpose than what the "Aktenzeichen" field is used for in relation to the interface requirement. This seems to me like a requirement of additional fields for use of internal purposes? If so, maybe we could refine this with #5098?

**Comment by Marko-ilmkreis** [comment]
@kwa20 Maybe we can discuss this today as well? In the meeting yesterday (Erfahrungsaustausch) there was the request from serveral health offices to have a field for a file number/own marker of the case which must be searchable from the directory and listed in the directory. The planned converting into the general comment field (#5148) does not help to fulfil this request.

**Comment by kwa20** [comment]
@Marko-ilmkreis I've created #5224 and #5225 in regards to our discussion. If you think that these issues can solve this problem we could close this issue and implement the others.

**Comment by Marko-ilmkreis** [comment]
@kwa20 Yes, we can then close this issue.
