### ISSUE TITLE
Unsaved changes prompt triggered on event forms when geo coordinates entered

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5039]
### Bug Description
The unsaved changes prompt is triggered on event forms when geo coordinates are entered and no edits have been made.
### Steps to Reproduce
1. Go to any event or create one.
2. Enter the location and generate geo coordinates, save.
3. Navigate to different tabs.

### Expected Behavior
The prompt should only be shown when actual changes have been made.
### Screenshots
<img width="392" alt="unsavedChangesPromptEvents" src="https://user-images.githubusercontent.com/70317594/114305915-68fea900-9ada-11eb-8b09-d432ab35d80f.PNG">
<img width="159" alt="unsavedChangesPromptEvents2" src="https://user-images.githubusercontent.com/70317594/114305919-6ac86c80-9ada-11eb-8140-9486978606c7.PNG">

### System Details
* Device:
* SORMAS version: 1.58.3
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information
cf. #3014

**Comment by MateStrysewske** [comment]
@kwa20 For some reason I can't reproduce the problem on my local system (even with the settings that I used to reproduce the other "unsaved changes" warnings that weren't supposed to be there in the first place). I have however provided a potential fix. We'll have to see whether it successfully solves the issue. I'm pretty sure it won't make it worse at least. :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.59.0-snapshot
