### ISSUE TITLE
case contacts not initially shown in list after import

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5040]
### Bug Description
When on the contacts tab in the case, imported contacts don't initially appear after the import.
### Steps to Reproduce
1. Open or create a case and go to the contacts tab.
2. Import contacts.
3. check the list after a successful import.
4. navigate out of the tab and back.

### Expected Behavior
The imported contacts should appear in the list after the successful import without having to navigate.
### Screenshots
<img width="465" alt="caseContactImport" src="https://user-images.githubusercontent.com/70317594/114306140-31dcc780-9adb-11eb-911b-1ab539955a82.PNG">

**Before navigation:**
<img width="849" alt="caseContactImport2" src="https://user-images.githubusercontent.com/70317594/114306142-343f2180-9adb-11eb-8ca0-1eeabd5a631d.PNG">

**After navigation:**
<img width="843" alt="caseContactImport3" src="https://user-images.githubusercontent.com/70317594/114306143-35704e80-9adb-11eb-8326-83bf1c99a461.PNG">

### System Details
* Device:
* SORMAS version: 1.58.3
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by StefanKock** [comment]
Is this a general reload problem after import or only happening for cases?
Hint: It might be a JTA transaction topic: When the data is not yet persisted in the database, the UI cannot load it within the same roundtrip.

**Comment by leventegal-she** [comment]
@StefanKock It is not a generic reload problem.

**Comment by vidi42** [comment]
PR #5100 merged
