### ISSUE TITLE
Statistics Map does not display any regions/districts

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5048]
### Bug Description
Statistics map not working
### Steps to Reproduce
1. Open any environment and go to the statistics tab
2. Add a filter for Region/District/Community/Facility 
3. Select all regions and districts
4. Set the Visualization type to Map and Click on Generate
 

### Expected Behavior
The map should display something as long as there are cases on that environment also in the cases when "Show zero values" checkbox is selected
### Actual Behavior
The map does not display anything

### System Details
* Device:
* SORMAS version: 1.59.0-snapshot
* Android version/Browser: Chrome/Firefox
* Server URL: any or use test.sormas.netzlink.com or test-de1.sormas.netzlink.com
* User Role: NAtUser

### Additional Information
This ticket might be related to the same issue from #4864 and #4565

**Comment by DavidBaldsiefen** [comment]
@JonasCir any chance you can take a quick look at this?

**Comment by JonasCir** [comment]
I have no valid regions and district data for Germany anymore :(

**Comment by DavidBaldsiefen** [comment]
Then that is propably also the reason this doesn't work anymore... is there some issue for that?

**Comment by DavidBaldsiefen** [comment]
I cannot reproduce this locally with a clean build
