### ISSUE TITLE
[DEMIS Interface] The uuid and message date of lab message can be edited when the message is not properly displayed

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5049]
### Bug Description
When lab messages are not properly displayed, the uuid and the message date can be edited and sent to other organizations that are reachable via Sormas 2 Sormas. However, the uuid and message date does not seem to change upon sending.
### Steps to Reproduce
1. Improperly configure the lab message interface so that messages are not properly displayed
2. View the lab message
3. Change the uuid and the message date
4. send entry via Sormas 2 Sormas

### Expected Behavior
The uuid and message date should not be editable.
### Screenshots
<img width="322" alt="labMessageDisplayError" src="https://user-images.githubusercontent.com/70317594/114448974-83b54880-9bd4-11eb-9cc1-e2e472d30b84.PNG">
<img width="321" alt="labMessageDisplayError2" src="https://user-images.githubusercontent.com/70317594/114448979-857f0c00-9bd4-11eb-9d8e-6e6c6bb990a4.PNG">

**After "Sent to another organization" was selected:**
<img width="847" alt="labMessageDisplayError3" src="https://user-images.githubusercontent.com/70317594/114448983-8748cf80-9bd4-11eb-84c1-60a5ce3372ed.PNG">

**Lab message in other instance**
<img width="316" alt="labMessageDisplayError4" src="https://user-images.githubusercontent.com/70317594/114450148-ee1ab880-9bd5-11eb-9e4a-3090e1164ec6.PNG">

### System Details
* Device:
* SORMAS version: 1.59.0 - SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de1.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
This undesired behaviour just shows when the demis adapter can not be found, e.g. when `interface.demis.jndiName=` in the `sormas.properties` is wrongly specified.
