### ISSUE TITLE
SORMAS cannot be build from source

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#5053]
### Bug Description
SORMAS cannot be freshly build from source on latest `development`. 

### Steps to Reproduce
1. Get a fresh system or build inside Docker
```
FROM openjdk:11

RUN apt update && apt upgrade -y
RUN apt install maven -y

RUN java -version
COPY . /srv/

WORKDIR /srv/sormas-base
RUN mvn install -DskipTests

```
with `docker build -t local/sormas-docker .
`
2. Installation process hangs during dependency download

### Expected Behavior
Build passes

### Additional information
With cached packages it will work of course :)

**Comment by StefanKock** [comment]
I do not get it, what this build approach is about: SORMAS-Project is not meant to be built with Docker.

**Comment by StefanKock** [comment]
Hypothesis: Problem with some dependencies when they are not already cached in the local maven repo.

**Comment by JonasCir** [comment]
Hm works now, who knows...
