### ISSUE TITLE
Error on campaigns statistics view on APMIS system

### ISSUE THREAD

**Issue by danieltomaba** [hzi-braunschweig/SORMAS-Project#5055]
### Bug Description

Open the dashboard, click on the campaigns tab, click on the campaigns statistics and then the error appears
### Steps to Reproduce

1. Open the dashboard, 
2. click on the campaigns tab
3. click on the campaigns statistics and then the error appears

### Screenshots

<img width="2045" alt="Screen Shot 2021-04-13 at 09 13 19" src="https://user-images.githubusercontent.com/50736373/114558474-b1cc7400-9c38-11eb-964b-2538ca6fbcea.png">

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@danieltomaba Can you please attach logs with the error? We'll likely need those to identify its cause. Thank you!

**Comment by danieltomaba** [comment]
[error logs-apmis.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6325310/error.logs-apmis.txt)

**Comment by MateStrysewske** [comment]
The error was caused by an invalid database entry.
