### ISSUE TITLE
Implement user right dependencies [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#5058]
### Problem Description
Some user rights depend on each other (e.g. ~~edit rights always depend on the related view right.~~ CONTACT_CONVERT depends on CASE_EDIT/CREATE). This should be reflected in the code and validated for each user role.

Depends on #4461, needed for #4463
See also https://github.com/hzi-braunschweig/SORMAS-Project/issues/898#issuecomment-671336289

### Proposed Change

- [x] Add a requiredUserRights param to the constructor of the UserRight enum
- [x] For any entity related user right the _VIEW user right is requiered
- [x] CONTACT_CONVERT requires CASE_CREATE and CONTACT_EDIT
- [x] CONTACT_VIEW requires CASE_VIEW (e.g. for visits)
- [x] Deletion user rights require the deletion user rights of child entity
  * CASE_DELETE needs DOCUMENT_DELETE, TASK_DELETE, SAMPLE_DELETE, VISIT_DELETE, PERSON_DELETE, TREATMENT_DELETE, PRESCRIPTION_DELETE, CLINICAL_VISIT_DELETE and IMMUNIZATION_DELETE
  * SAMPLE_DELETE needs PATHOGEN_TEST_DELETE
  * CONTACT_DELETE needs DOCUMENT_DELETE, TASK_DELETE, SAMPLE_DELETE, VISIT_DELETE, PERSON_DELETE and ACTION_DELETE
  * CAMPAIGN_DELETE needs CAMPAIGN_FORM_DATA_DELETE
  * EVENT_DELETE needs DOCUMENT_DELETE, TASK_DELETE, EVENT_PARTICIPANT_DELETE
  * EVENT_PARTICIPANT_DELETE needs DOCUMENT_DELETE, SAMPLE_DELETE, PERSON_DELETE 
  * TRAVEL_ENTRY_DELETE needs DOCUMENT_DELETE, TASK_DELETE
- [x] EXTERNAL_MESSAGE_PROCESS needs CASE_CREATE, CASE_EDIT (physician's report results in a case) and CONTACT_CREATE, CONTACT_EDIT, EVENTPARTICIPANT_CREATE, EVENTPARTICIPANT_EDIT, SAMPLE_CREATE, SAMPLE_EDIT, PATHOGEN_TEST_CREATE, PATHOGEN_TEST_EDIT, IMMUNIZATION_CREATE, IMMUNIZATION_EDIT
- [x] CASE_SHARE requires CASE_VIEW
- [x] Create a cached helper method in UserRight that provided the flattened required user rights of any user right (e.g. CONTACT_CONVERT requires CASE_CREATE)
- [x] Remove CONTACT_CLASSIFY and CONTACT_ASSIGN since they are not used at all. Also needs to be removed from the database
- [x] Validate the user rights when saving a user role
- [x] flush the `UserCache` when a `UserRole` is updated. See `UserListener` class in User.java for an example of how to do this.

This will also allow us to do validation when implementing #4463

Note: Currently the constructor of UserRight still takes a collection of user roles. This will be removed by #4461.

**Comment by abrudanancuta** [comment]
Existing Roles in the system need a migration of user rights

**Comment by abrudanancuta** [comment]
When an existing user or new user changes his language then a pop-up error appears and his action is blocked

**Comment by adinaflorea9** [comment]
Behavior initially reported by @kwa20 in #9937.

As per @dinua 's comment (https://github.com/hzi-braunschweig/SORMAS-Project/issues/9937#issuecomment-1205150712) I am adding the behavior reported here so that it can be checked once #5058 is completed.

Steps to reproduce:
1. Log into the app with any user that is not an admin;
2. From the 'User settings' try to change the language.
=> error message is displayed.

Server logs:
[user language.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9259415/user.language.txt)



Note: behavior is reproducible for all users (other than admins), regardless of whether a language was set or not for the user when they were created.

**Comment by abrudanancuta** [comment]
> Behavior initially reported by @kwa20 in #9937.
> 
> As per @dinua 's comment ([#9937 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/9937#issuecomment-1205150712)) I am adding the behavior reported here so that it can be checked once #5058 is completed.
> 
> Steps to reproduce:
> 
> 1. Log into the app with any user that is not an admin;
> 2. From the 'User settings' try to change the language.
>    => error message is displayed.
> 
> Server logs: [user language.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9259415/user.language.txt)
> 
> Note: behavior is reproducible for all users (other than admins), regardless of whether a language was set or not for the user when they were created.

The behaviour is reported in the comment above and will be fixed when the ticket will be back in testing

**Comment by abrudanancuta** [comment]
Validated on local env with the version 1.75.0-SNAPSHOT (d312652)

**Comment by AliciaRaber** [comment]
Tested on test1402.sormas.netzlink.com 1.75.2
CASE_DELETE needs DOCUMENT_DELETE, TASK_DELETE, SAMPLE_DELETE, VISIT_DELETE, PERSON_DELETE 
Complete
TREATMENT_DELETE, PRESCRIPTION_DELETE, CLINICAL_VISIT_DELETE and IMMUNIZATION_DELETE
Complete
SAMPLE_DELETE needs PATHOGEN_TEST_DELETE
Complete
CONTACT_DELETE needs DOCUMENT_DELETE, TASK_DELETE, SAMPLE_DELETE, VISIT_DELETE, PERSON_DELETE and ACTION_DELETE
Complete
CAMPAIGN_DELETE needs CAMPAIGN_FORM_DATA_DELETE
Complete
EVENT_DELETE needs DOCUMENT_DELETE, TASK_DELETE, EVENT_PARTICIPANT_DELETE
Complete
EVENT_PARTICIPANT_DELETE needs DOCUMENT_DELETE, SAMPLE_DELETE, PERSON_DELETE
Complete
TRAVEL_ENTRY_DELETE needs DOCUMENT_DELETE, TASK_DELETE
Complete
 EXTERNAL_MESSAGE_PROCESS needs CASE_CREATE, CASE_EDIT  and CONTACT_CREATE, CONTACT_EDIT, EVENTPARTICIPANT_CREATE, EVENTPARTICIPANT_EDIT, SAMPLE_CREATE, SAMPLE_EDIT, PATHOGEN_TEST_CREATE, PATHOGEN_TEST_EDIT, IMMUNIZATION_CREATE, IMMUNIZATION_EDIT
Complete
 CASE_SHARE requires CASE_VIEW
Complete
