### ISSUE TITLE
[SurvNet Interface] Add evidence fields for event clusters [5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5061]
### Situation Description
The SurvNet interface requires additional fields in order to be mapped to SurvNet for the interface to provide data quality expected by higher health institutions.

### Feature Description
Add epidemiological and laboratory diagnostic evidence fields to events of type cluster including subsequent check boxes (DE only):

- Only show these fields for events with the disease COVID-19

---

- Add an `epidemiological evidence` yes/no/unknown and subsequent check boxes - field should only be shown when HUMAN_TO_HUMAN is selected in DiseaseTransmissionMode
    - Study
        - Case-control study
        - Cohort study
    - Explorative survey of affected people
        - Contact to sick person
        - Contact to contaminated materials
    - Descriptive analysis of ascertained data
        - Temporal: temporal occurrence of diseases suggest common infection source
        - Spatial: Most of the cases were at the same location during the assumed infection period
        - Person: cases were in direct or indirect contact with each other
    - Suspicion
        - expressed by the diseased person
        - expressed by the health department

- Only show first hierarchy of check boxes when YES was selected for `epidemiological evidence`
- Only show second hierarchy when respective first hierarchical fields are checked

---

- Add a `laboratory diagnostic evidence` boolean (yes/no/unknown) and subsequent check boxes - field should only be shown when HUMAN_TO_HUMAN is selected in DiseaseTransmissionMode
    - Verification of at least two infected or diseased persons
        - Compliant pathogen fine typing
    - Impression test
    - Water sample
    - Other
    - Pathogen fine typing compliant with the one of cases

- Only show first hierarchy of check boxes when YES was selected for `laboratory diagnostic evidence`
- Only show second hierarchy when respective first hierarchical fields are checked

### Possible Alternatives
Follow a modular approach for `evidence `that allows adding mentioned fields in a hierarchical fashion and differing field types. This approach would probably be more sustainable in the long run

### Additional Information
<img width="359" alt="outbreakEvidence2" src="https://user-images.githubusercontent.com/70317594/114601619-ffc39500-9c95-11eb-84a9-07286f21871d.PNG">

Mapping:
https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/115

**Comment by kwa20** [comment]
@JaquM

**Comment by bernardsilenou** [comment]
@kwa20  Should we review this as dissected ?

**Comment by StefanKock** [comment]
I proposed @BarnaBartha to map the checkbox values as enum constants and store them into on SQL text column (keyword: JPA AttributeConverter). This integrates also in bean-test setup. As with JSON columns the querying is also not straight forward but doable if needed in the future.

**Comment by vidi42** [comment]
When testing the sending of Cluster Events to SurvNet an exception seems to be thrown when the SurvNet Converter is communicating back with SORMAS.
```
Caused by: org.postgresql.util.PSQLException: ERROR: could not identify an equality operator for type json
```
and it points to the following line as the cause
```
at de.symeda.sormas.backend.event.EventFacadeEjb.getAllActiveEventsAfter(EventFacadeEjb.java:161)
```

This seems to be cauzed by the recently introduced JSON fields
```
-- 2021-04-29 Add evidence fields for event clusters #5061
ALTER TABLE events ADD COLUMN epidemiologicalevidence varchar(255);
ALTER TABLE events ADD COLUMN epidemiologicalevidencedetails json;
ALTER TABLE events ADD COLUMN laboratorydiagnosticEvidence varchar(255);
ALTER TABLE events ADD COLUMN laboratorydiagnosticEvidencedetails json;
```

A possible solution would be changing their type from `json` to `jsonb` as suggested here https://stackoverflow.com/a/43719269/2524448.

I tested this locally and it works for the aforementioned issue, but not sure what implications it has for the functionality of this ticket.

**Comment by BarnaBartha** [comment]
@vidi42 Using jsonb for the columns does not affect the tickets functionality, thus i have changed the types.

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest version of sormas 1.60.0-snapshot on test-de.sormas.netzlink.com environment
