### ISSUE TITLE
cases>case directory>filter by "symptom journal status" inaccurate results

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#5062]
### Bug Description
When filtering Cases (follow-up visits view) by 'Symptom Journal Status', results include values outside the desired filter.

### Steps to Reproduce
Cases > Case Directory > Follow-up Visits view
Show more filters > Add any filter for 'Symptom Journal Status' > Apply Filters
Results are not filtered

### Expected Behavior
Results include only Cases with the associated Symptom Journal Status.

### Screenshots

<img width="960" alt="image" src="https://user-images.githubusercontent.com/76884029/114604457-3058fe00-9c99-11eb-9a36-30d6e8510171.png">

### System Details

* Device: web
* SORMAS version: 1.58.2
* Android version/Browser: Edge
* Server URL:
* User Role: admin, surveillance supervisor, contact supervisor & surveillance supervisor, contact supervisor & clinician

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of sormas 1.59-0-snapshot on ga1.sormas.netzlink.com environment
