### ISSUE TITLE
Provide a search alternative aside from the duplicate recognition [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5078]
### Situation Description
Users face the problem that lab messages coming in through the DEMIS interface are often either not sufficiently filled or do not trigger the duplicate detection properly because they include erroneous entries.

### Feature Description
To allow users to find and select duplicate persons that could not be detected by the duplicate detection, add the option in the duplicate detection window and entity creation window to search for a person.

- Add a "Search Person" button to the duplicate detection form
- Add a "Search Person" button to the entity creation form when processing a lab message
    - When selecting the "Search Person" button, a window analogous to the choose case window should open up that allows the user to search for persons in the system that they have access to. Users should be able to search by name, person ID, external ID and external Token. The info section on the window should include the following text:

_Use the text field below to search for any person in the system you have access to.  You can search by name, person ID, external ID and external Token. When you‘re done, click on “Search Person“ to see a list of persons that match the text that you have entered. Select a person in the list and click on “Confirm“ to choose the selected person._

_Selecting a person will disregard the person information provided in the lab message. Before confirming the person you should make sure that the selected person is indeed a duplicate of the person mentioned in the lab message._

- Add a checkbox "Create a new person" to this window to also be able to create a new person if no matching person was found during the search.
    
    - Selecting this checkbox should disable and grey out the search field, button and result list.
    - Selecting this checkbox and clicking confirm should trigger the same action as performing the same action on the duplicate detection window. 

- When a person was selected from the list and confirm was selected, the subsequent entities should be created for the existing person.

### Possible Alternatives
Decouple the person duplicate detection for the processing of lab messages to be more conservative than the regular person duplicate detection in order to allow duplicates to be suggested even when incoming lab messages have a poor data quality.

### Additional Information
**Existing pick or create person window:**
<img width="634" alt="LabMessageDuplicateSearchPerson" src="https://user-images.githubusercontent.com/70317594/114738121-f8f55a80-9d47-11eb-8962-71d86f28b8f3.PNG">

**Select Person window which opens after selecting "Search Person":**
<img width="501" alt="LabMessageDuplicateSearchPerson2" src="https://user-images.githubusercontent.com/70317594/114738129-fb57b480-9d47-11eb-9193-5fd444bf6a0e.PNG">

@JaquM 

### Development Specifications
* Check wether the umlaut tolerance is active for this use case (ü equals ue)
* Add a new option to the "Select or create person" window between the two existing options: "Select a different person"
* Add a feature configuration for this
* Search should only show the persons you have access to
* Add elements below this new option that are only visible when the option is selected:
  * A text field for first name
  * A text field for last name
  * A search bar which allows to search for UUID, external ID and external token of persons (add a placeholder String that contains these fields)
  * A "Search" button next to the search bar
  * A grid below these two elements that is updated when the "Search" button is clicked and that behaves exactly like the already existing grid (i.e. use another PersonSelectionGrid)
* Extend PersonSimilarityCriteriaDto with a `uuidExternalIdExternalTokenLike` field that allows to search these three columns (use the new ilike/unaccentedilike features) when retrieving the MatchingNameDtos
* When the new option is selected, deselect and disable the grid for the first option
* Add a "reset" button to get back to 1st duplicate detection results

**Comment by FredrikSchaeferVitagroup** [comment]
Would it help to also lower the criteria for the person duplicate detection, so that it finds more persons?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I guess for most persons it would yes, although I'm not quite sure if e.g. a mismatched day of birth would prevent the suggestion of a less similar name. What I like about being able to search is that users at least have an alternative to fall back on in case persons are not suggested as duplicates for any reason.

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by MateStrysewske** [comment]
@kwa20 I would suggest to not split this into multiple components, but to instead add another option to the already existing "Pick or create person" window that says "Search for a different person"; selecting this button would then activate the search bar, search button and additional grid below it (I don't think the info text would be necessary in this case). If the option is not selected, those elements should be hidden. Selecting this option should unselect and disable the "Select a matching person" grid. When building the "Pick or create person" window, it should be configurable whether or not this additional option is shown, and it should (for now) only be shown when processing lab messages.

This has the advantage that we don't need a decoupled new window whose content we need to transfer to the original window in some way, and I think it makes for a better user flow. What do you think?

**Comment by kwa20** [comment]
@MateStrysewske Sounds good to me! It would also prevent overlays of multiple pop-ups which is nice. Would this then be a feature configuration in the database? 

> and it should (for now) only be shown when processing lab messages.

If it's not much more work, I'd even prefer to make this available in every 'Select a matching person' view because that would solve a lot of issues and requests that users have in the process.

**Comment by MateStrysewske** [comment]
Fine by me :)

**Comment by Candice-Louw** [comment]
Info from @VitaliHZI and @vidi42:
PERSON_DUPLICATE_CUSTOM_SEARCH in DB needs to be enabled to make use of this feature.

**Comment by kwa20** [comment]
The search for different persons seems to be partially restricted by the name similarity threshold. This seems quite unintuitive and like a bit of a hindrance since it would not really prevent the user to eventually select any person but makes searching more difficult.

<img width="568" alt="personSearch" src="https://user-images.githubusercontent.com/70317594/123615077-404a9d80-d805-11eb-899e-7758a751c60d.PNG">
<img width="564" alt="personSearch2" src="https://user-images.githubusercontent.com/70317594/123615083-42146100-d805-11eb-9a20-cc400d187346.PNG">

Would we be able to lift this constraint?

**Comment by markusmann-vg** [comment]
@kwa20 If there is a different behavior needed or wanted, pls. describe it and add a story for it.  Thank you

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest version of Sormas 1.62.0-snapshot using test-de2 environment
