### ISSUE TITLE
Change Request: Bulk Edit @ Task Management

### ISSUE THREAD

**Issue by Scotchomani** [hzi-braunschweig/SORMAS-Project#5079]
**Feature Description:** 
Enable more options to Bulk Edit Tasks in the Task Management
**Problem Description:**
Sometimes Tasks must be changed e.g. the task Owner of multiple Tasks changes. if i want to change the owner we 
need to actually open every Task. instead of bulk editing the tasks.
**Proposed Change:**
-> Allow Bulk Edit of tasks with the option to apply changes for multiple tasks. e.g. Owner, Task Finished, Priority, Task Type

**Comment by MateStrysewske** [comment]
@Scotchomani Hey, thanks for your submission! Issue #3430 is basically the same request as this one and is already in development. If there are additional fields that you'd like to see added to the bulk edit feature for tasks, could you please add a comment to that issue? Thanks!
