### ISSUE TITLE
Login > Security Alert > "Remind me later" option error

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5080]
### Bug Description

Login using a default (username, password) combination and selecting to change it later, displays the default error message in SORMAS on every page (and no data being visible/accessible at all).

### Steps to Reproduce

1. Login using default username, password
2. Security Alert > Remind me later
3. SORMAS opens, but Error message on every single page

### Expected Behavior

1. No error message and data visible (Question - is there a limit to the number of times a user could log in using the default credentials?  This should be clearly communicated to the users if it is the case, please).
OR
2. Custom error message introduced indicating that data is not visible/accesssible due to default login details having been used. 
OR
3. Other approaches/suggestions, please?

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/114765134-15ec5680-9d65-11eb-853d-cd99091bd070.png)

### System Details

* Device: Web
* SORMAS version: 1.59 Snapshot
* Android version/Browser: Chrome
* Server URL: https://test-ch.sormas.netzlink.com/
* User Role: admin

### Additional Information

https://github.com/hzi-braunschweig/SORMAS-Project/pull/4875
@rzo1 @Snorzze @schwzr

**Comment by schwzr** [comment]
@Candice-Louw

We can reproduce this bug on the server url you mentioned. However, using the current snapshot version / development branch using [cargoserver](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-cargoserver/README.md) I cannot reproduce the error.

Do you have any server logs regarding the error?

There is no limit to the number of times a user could log in using the default credentials.

Additionally, an option (disabled by default) to disable the default password check for such public demo servers would probably be useful.

**Comment by Candice-Louw** [comment]
@schwzr - thank you for the feedback.

1. Logs requested - will post them here once available (may take some time).
2. Good to know, thank you.
3. Yes, this is a good idea, thank you for the suggestion.

Addition: Should I keep this bug report open until the logs are available and this can be confirmed?  I can't pinpoint another change that may have caused this error - apologies in advance if it is not related.

Please feel free to get in touch directly: candice.louw@helmholtz-hzi.de

**Comment by MateStrysewske** [comment]
@Candice-Louw It's fine to keep it open

**Comment by rzo1** [comment]
@Candice-Louw I can confirm the observation of @schwzr - local `cargo:run` does not show the error dialog. Log files would be indeed very helpful in finding the root cause of the error in the demo deployment.  Do we have another demo instance (with a SNAPSHOT deployment) available to check?

**Comment by Candice-Louw** [comment]
@rzo1 @Snorzze @schwzr - please could you reproduce the error on the server and record the time, now, please?  It is needed for the logs, please?  I don't have the new admin password that was generated...

**Comment by rzo1** [comment]
The new password is `yFLg8BF5rhFM`. The "funny" thing: I cannot reproduce it on the https://test-ch.sormas.netzlink.com/ instance (but saw it yesterday). Could you give it a try?

**Comment by Candice-Louw** [comment]
Thank you @rzo1 @Snorzze @schwzr - can't reproduce it anymore either.

Checked with @nliakm : "in 1.59 a new postgres extension is needed - it wasn't added correctly during the update.  It is added now."  Error is not appearing anymore.

@MateStrysewske - if fine by you, please feel free to close the issue. :)

Thank you all for the great feature and brilliantly fast assistance!

**Comment by rzo1** [comment]
The extension also messed up our local dev setup (with previous data). Might be necessary to provide a clear migration path from 1.58 to 1.59 for end users / sys admins, so potential problem srelated to this postgres extension do not appear in a roll-out.

**Comment by Candice-Louw** [comment]
@vidi42 @StefanKock - new postgres extension was discussed briefly during one of the tech daily meetings - pinging you in for info.

**Comment by MateStrysewske** [comment]
@rzo1 I also tweeted about the necessary change for developers with our SORMASDev Twitter account. Please make sure to follow that one to get notified about changes like these in the future :)

**Comment by rzo1** [comment]
Thanks for the hint @MateStrysewske ! Followed :)
