### ISSUE TITLE
Add a configuration option to skip default password check for demo servers

### ISSUE THREAD

**Issue by schwzr** [hzi-braunschweig/SORMAS-Project#5081]
### Situation Description
PR #4875 prompts users with a default password or administrators with systems that have default passwords to change them on every login. While this is intended for every system that is currently in production or will probably be used in production in the future, this feature makes the use of public demo servers a lot harder.

### Feature Description
There should be a configuration option that allows to disable the default password check. For security reasons, it (the skip) should be disabled by default.

**Comment by Candice-Louw** [comment]
Thank you very much!
