### ISSUE TITLE
Bulk action for facilities results in error

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5083]
### Bug Description

If you want to archive facilities is results in an error.

### Steps to Reproduce

1. Open facilites-cirectory
2. activate bulk-edit and try to archive one or more facilities
3. you see the error message below.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/114815513-96877300-9db6-11eb-8547-b29dad1bf067.png)

![grafik](https://user-images.githubusercontent.com/74791118/114815612-da7a7800-9db6-11eb-8b4a-5d3dde29d734.png)

### System Details

* SORMAS version: 1.58.3 and 1.59.-snapshot
* Server URL: own instance and https://test-de1.sormas.netzlink.com
* User Role: admin

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.60.0-snapshot deployed to test.sormas.netzlink.com environment
