### ISSUE TITLE
Persons are hidden in the directory if they are not linked to an entity

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5084]
### Bug Description

In the new directory of persons, a number of persons are anonymised. This is basically correct if the users do not have permission to view this data.
However, *no* normal user of our Sormas instance can see the data of the persons. Even as a National User, only if the user has Sormas2Sormas permissions can they see the details of the person. I noticed that there is no case, contact or ep linked to these persons.

I suspect that this is also the reason why the persons are anonmised. However, it confuses users when they see the anonymised records.

I see three options to solve the problem:
a) the anonymised persons are hidden in the person directory. Especially if there is no entity linked, or
b) people who are neither a contact nor a case or an ep will be deleted by script in one of the next updates.
c) persons who are neither a contact nor a case or an ep are still displayed with the complete personal data. 

I would prefer option b, as these persons would have to be deleted in our system for data protection reasons.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/114817204-e0258d00-9db9-11eb-9e3e-9a625078de9f.png)
![grafik](https://user-images.githubusercontent.com/74791118/114817217-e451aa80-9db9-11eb-91a9-f7e0660316df.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by kwa20** [comment]
@Marko-ilmkreis I think this is the same problem as described in #4743. Let's continue commenting there I suppose?

**Comment by Marko-ilmkreis** [comment]
@kwa20 yes, you are right. I close this and we discuss in #4743 .
