### ISSUE TITLE
Cases | Filters | Date of Birth filter missing information

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5086]
### Bug Description
The Text is not displayed on filter

### Steps to Reproduce
1. Open any environment and log in with NatUser for example
2. Go to Persons Tab and check the Filters area
3. Check the consistency of what is shown on the Filters side.

### Expected Behavior
The text "Date of Birth" should be displayed
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/114828604-cb092800-9dd2-11eb-88a4-2ce11f1a1bc4.png)

### System Details

* Device:
* SORMAS version: 1.59.0-snapshot
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: NatUser

### Additional Information
![image](https://user-images.githubusercontent.com/70562142/114828590-c5abdd80-9dd2-11eb-88c8-50547ccf3f2c.png)

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she That's unfortunately a Vaadin-related problem that, from my understanding, is hard to fix. The birth day field is disabled in your case, and only gets enabled once year and month have been filled in. At that point, the placeholder text should appear. Afaik it's not easily possible to also display the placeholder text on disabled fields (and it's probably not worth to invest time to look into it at this point).
