### ISSUE TITLE
Community field produces error in case of an import

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5093]
### Steps to Reproduce

1. Create a case and for that case set the community based on the region and district
2. Export the case
3. Import the file 

### Expected Behavior
The user should be able to import the file

### Actual Behavior
The user receives an error message saying that the community is not accepted.

### System Details

* Device: Windows
* SORMAS version: 1.59.0.snapshot
* Android version/Browser:
* Server URL: any
* User Role: NAtUser

**Comment by leventegal-she** [comment]
Couldn't reproduce. Tested locally and on test-de2.sormas.netzlink.com.
