### ISSUE TITLE
Invalid place of stay on case create form will still create new persons

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5095]
### Bug Description

When creating a new case, not selecting any facility leads to a prompt asking the user to enter a valid place of stay before proceeding. However, despite the prompt, a person will already be saved to the database. This leads to a lot of dead entries, as well as duplicates.

### Steps to Reproduce

1. Go to case tab & create new case
2. Fill out all mandatory fields except for place of stay
3. Press save. No case will be created, but now a new person will appear in the database

### Expected Behavior

Do not make any changes to the database unless all fields are valid

### System Details

* Device:
* SORMAS version: 1.59.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role: admin

**Comment by StefanKock** [comment]
Problem is already longer in the system. And we should consider how to remove data without associated case.
