### ISSUE TITLE
[Angular] Add cards on the Case Person page. Add "new card" button [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5104]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Add cards list for address and contact on the Case Person page,
- Add buttons which enables you to add new cards (without action)

Note: We will show all addresses including "Home".

https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKEW8Pn

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by sandorbanvitagroup** [comment]
UI / UX review done. @cristinacoza approved it.
