### ISSUE TITLE
[Lab Message] Make person first- and lastName editable when processing a lab message [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5130]
### Feature Description

Sometimes, the name of a person has typos or errors when transmitted by an external lab message system. When processing a lab message, users want to correct these errors/typos.

### Problem Description

... but the person first- and lastName is not editable when creating a new case/contact for processing a lab message.

### Proposed Change

Make those fields editable.

### Additional Information

When creating an event participant while processing a lab message, the name seems to be already editable.
Check if the duplicate detection is properly working, when the name was changed (maybe completely different)

**Comment by maxiheyner** [comment]
Issue Tracker Comment

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test-de1.sormas.netzlink.com environment
