### ISSUE TITLE
Cases > Detailed Import accepts empty space at vaccination doses

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5131]
### Bug Description

In cases in which the number of vaccination doses was imported via a detailed import, and a space is put in front of the number in the import file, a space also appears in the corresponding field in SORMAS. As a result, the case can no longer be saved without manually editing the field first to remove the blank space. ~~There are no spaces in the corresponding column in the imported csv file.~~

### Steps to Reproduce

1. Import via CSV

### Expected Behavior

Import values without the leading " " entry.

### Screenshots

![impfdosenbug](https://user-images.githubusercontent.com/68844760/115259177-ef963480-a131-11eb-903c-310ef1ac1f4e.png)

### System Details

* Device: Web
* SORMAS version: 1.58.3
* Android version/Browser: Chrome/Firefox
* Server URL: http://stable-release-ch.sormas.netzlink.com/
* User Role: admin, national user, rest

**Comment by Alexandru-Pirvu** [comment]
@Candice-Louw I can't reproduce it. Can you provide a csv import file for which this error reproduces?

**Comment by pSinnigerLU** [comment]
I upload a file you can reproduce it with. Maybe it is because the values are quoted in my file that you have not been able reproduce.
[repfile.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6363459/repfile.zip)

**Comment by Candice-Louw** [comment]
@Alexandru-Pirvu - file uploaded.  Please let me know if I need to create a new issue (bug/feature request?) to ignore whitespace during imports?

**Comment by Alexandru-Pirvu** [comment]
@Candice-Louw We can keep this issue for ignoring whitespaces at imports.

**Comment by FredrikSchaeferVitagroup** [comment]
To validate this issue: try to import a case with a whitespace before or after a number (between 1 and 9) as the value for vaccination doses and check whether you can open and save that case without SORMAS complaining about the invalid value for vaccination doses.

**Comment by raghupola-vg** [comment]
Validated on version 1.60.0-snapshot and issue is fixed.
