### ISSUE TITLE
[DEMIS2SORMAS] Prepare SORMAS to handle new DEMIS base profile

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5136]
### Situation Description & Motivation

The RKI and Gematik released new profiles for DEMIS-notifications [here](https://simplifier.net/demis). They shall be used in production soon. SORMAS needs to be able to handle messages with both, the current and the new profile.

#### Use cases

The new base profiles are designed to be also used with diseases other than COVID19. The current plan is that SORMAS is just going to receive COVID19 related demis notifications, though.

### High-Level Explanation

RKI promised to continously extend documentation and provide more detailed examples of the new profiles in April 2021.

Currently, there following changes are identified, that SORMAS has to be able to deal with: 

- Part of the new profile is the [DiagnosticReport (Laborbericht)](https://simplifier.net/demis/laboratoryreport). There are several fields relevant for the new mapping.
- Also new: lifecycle management of messages.

### Timeline

The new profiles are supposed to be supported with 1.66.0. The new DEMIS profiles are planned to go live on 2021, Dec. 15th.

### Tasks

Regarding the [DiagnosticReport (Laborbericht)](https://simplifier.net/demis/laboratoryreport):

- [x] #5137
- [x] #5139
- [ ] #5140
- [x] #5539
- [x] #5159

Regarding the lifecycle-management

- [x] #5138

It probably is a good idea to have #5553 done before the new profiles go live.

Two more open tickets were identified. They are not considered mandatory, but are closely related to handling the new profiles:

- [ ] #7206
 - [x] [#12](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/12)

### Additional Information

To distinguish between old and new profile, Gematik recommends to look for the [DiagnosticReport](https://simplifier.net/demis/laboratoryreport) resource. It is supposed to be only and always in demis notifications of the new profile.

**Comment by FredrikSchaeferVitagroup** [comment]
This should be looked at by @kwa20 and @JaquM

**Comment by kwa20** [comment]
@Jan-Boehme this might also be interesting for you

**Comment by StefanKock** [comment]
#5140 is not done

**Comment by FredrikSchaeferVitagroup** [comment]
Two more open tickets were identified. They are not considered mandatory, but are closely related to handling the new profiles:

- [ ] #7206 
- [ ] [#12](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/12)

**Comment by herrling-LRA-KYF** [comment]
Is there a possibility to verify that the lab message is a mutation message by adding a new colomn or an icon?

**Comment by FredrikSchaeferVitagroup** [comment]
@herrling-LRA-KYF Thank you for your input. I am not sure if I understand your question correctly.

What is a mutation message for you? I guess it's a lab message containing information about a disease variant?

What is verification for you? From the way you describe it, I guess that you want to filter for lab message in the lab message directory (where all lab messages are listed).

It would probably help us better understand your requirement if you created a feature request [here](https://github.com/hzi-braunschweig/SORMAS-Project/issues/new/choose).

If I'm right with my guesses, implementing this in a reliable way may be difficult or impossible. The problem is  that disease variants are not transmitted via fixed values in DEMIS notifications. Instead there may also values like `Variant B.1.1.7 could not be detected`, which make a full mapping difficult to impossible. I don't know if filtering is of real value for just partly mappable data.

Some mapping of disease variants if defined in #7209.
