### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: DiagnosticReport.code [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5137]
### Situation Description

This issue is part of #5136.

Preriquisite: [#20](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/20).

### Feature Description

The new profiles for demis notifications hold the "Meldetatbestand" in the DiagnosticReport.Code.

It shall be mapped to the tested disease of all pathogen tests created from the related lab message.

### Possible Alternatives

- SORMAS could assume that the test disease is always CORONAVIRUS, as only COVID19 related demis notifications shall be transmitted to SORMAS. This would mean to rely on the correct routing of demis notifications which may be a bad idea.

**Comment by FredrikSchaeferVitagroup** [comment]
@Jan-Boehme 

Thank you for the response.

Currently, the disease is determined from [Composition](https://simplifier.net/covid-19labormeldung/notificationlaboratorysarscov2).title. We should probably replace this mapping with the one proposed here.

What shall be done with the DEMIS notifications that don't have this node or have a value different from cvdp? You imply that they shall not be imported. Does that mean the adapter shall just drop them? I don't think that this is a good idea. The data qualitiy of DEMIS notifications has not been the best so far and this approach would risk that some relevant notifications get lost. Instead, I propose to import those messages and warn the user when the LabMessage.testedDisease == null (-> when the adapter could not map the disease, which is when DiagnosticReport.code[0].coding[0].code[0] is anything other that cvdp). The warning could be something like "The tested disease of the lab message could not automatically be determined. Please manually verify that this lab message is about a disease to be dealt with in SORMAS." One could think about making this a germany only warning. What do you think about that?

**Comment by Jan-Boehme** [comment]
@FredrikSchaeferVitagroup

Yeah, I was thinking about that too. According to the documentation DiagnosticReport.code.coding.code has cardinality of 1..1 so it should always be there and have the correct value but there's probably no guarantee that the reporting source has implemented their reports according to the specification.

So importing them anyway with a warning message when the node does not exist or is another value than "cvdp" seems like the sensible thing to do.
The documentation is also ambiguous about where the code should be placed.

At one point is says that the code is placed at DiagnosticReport.code and at another at DiagnosticReport.code[0].coding[0].code[0]. The latter seems to be the correct way of implementing it judging from the example and the documented cardinality.
So we should do multiple checks. Could look something like this:

```
String codeValue = "";
codeValue = NodeExists(DiagnosticReport.code) ? DiagnosticReport.code.value : "";
codeValue = NodeExists(DiagnosticReport.code[0].coding[0].code[0]) ? DiagnosticReport.code[0].coding[0].code[0].value : "";
codeValue = toLowerCase(trim(codeValue));

if(codeValue == "cvdp") {
    //Import lab message as CORONAVIRUS
} else {
    //Show warning message and let the user select one of the configured diseases on this instance from a dropdown menu
}
```

This is also only relevant for german instances as DEMIS is a german only way of transmitting lab messages, isn't it?

**Comment by Jan-Boehme** [comment]
Found the list of all possible values for "Meldetatbestand".

Is not really relevant for the concrete issue but just for documentation's sake here it is:
https://simplifier.net/guide/ImplementierungsleitfadenfrDEMIS/Meldetatbestand-duplicate-2

**Comment by FredrikSchaeferVitagroup** [comment]
> This is also only relevant for german instances as DEMIS is a german only way of transmitting lab messages, isn't it?

@Jan-Boehme Yes, DEMIS is just used in germany. Lab messages are currently only used in germany, but shall be universal.

We can do the germany specific part in the demis-adapter, and the general part in SORMAS. 

Proposal: When processing a lab message, if the labMessageDto.testedDisease == null, the warning message should always show up (no matter if a german system or not).

In the adapter, it can then be:

```
String codeValue = "";
codeValue = NodeExists(DiagnosticReport.code) ? DiagnosticReport.code.value : "";
codeValue = NodeExists(DiagnosticReport.code[0].coding[0].code[0]) ? DiagnosticReport.code[0].coding[0].code[0].value : "";
codeValue = toLowerCase(trim(codeValue));

if(codeValue == "cvdp") {
    labMessage.setTestedDisease(Disease.CORONAVIRUS);
}
```
