### ISSUE TITLE
ReST Users should not be able to get tasks assigned

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5142]
### Feature Description
Tasks for ReST Users 

### Problem Description
Thus far, the ReST User requires a combination of users to function properly and get (restricted) access to the system. These combination roles are usually user roles which are actively used to work in the system. Since this user is not actually used by someone to login and work in the system, it's a hindrance that tasks can automatically or manually assigned to this user.

### Proposed Change
To prevent tasks being assigned to users that are not actively used by persons but fulfill another purpose, prevent the assigning of tasks to users that have a ReST User role attached.

**Comment by MateStrysewske** [comment]
Is this a pressing issue? Because it would automatically be solved with the user roles configuration feature.

**Comment by kwa20** [comment]
@MateStrysewske I think fixing this with the user roles configuration feature would be good. Would additional user roles next to the ReST User no longer be necessary?

**Comment by MateStrysewske** [comment]
@kwa20 Exactly; server admins could just directly assign the necessary user rights or jurisdiction to the ReST user
