### ISSUE TITLE
Default (Sub)Continent/Country import throws Exception

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5143]
### Bug Description
Title says it all

### Steps to Reproduce

1. As Admin, go to the configuration tab and import default continents
2. See the exception

### System Details

* Device:
* SORMAS version: 1.59.0-SNAPSHOT
* Android version/Browser:
* Server URL: test-de1.sormas.netzlink.com
* User Role: admin

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on local environment and on test.performance.sormas.netzlink.com
Verified that the import starts and ends without any error being thrown.
At the moment the import does not happen but this seems to related to another ticket #4905
