### ISSUE TITLE
Source case search doesn't fetch results when searched using the name.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#5147]
### Bug Description
While creating a new contact and searching for the source case using the case name, the results are not fetched.

### Steps to Reproduce

1. Login to Sormas application as SurvSup or any other user
2. Select Contacts menu and try creating a new contact
3. Click on the choose case button and try searching with an available case name (Ex: Angular, American, Gen1)
4. See if the results are shown

### Expected Behavior

The search results must be fetched and displayed when searched by a case name.

### System Details

* Device:
* SORMAS version: 1.59.0
* Android version/Browser:
* Server URL: test.sormas.netzlink.com
* User Role: SurvSup/NatUser

### Additional Information

The search field looks for the reporting user instead of the case name.

**Comment by MateStrysewske** [comment]
The problem is that we're searching for the first and last name of the reporting user rather than the case in CaseService. That needs to be corrected.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
