### ISSUE TITLE
[CLIMEDO Integration] Converting a contact to a case does not update the follow-up duration in Climedo

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5155]
@FredrikSchaeferVitagroup guys this is still not working on ga1. I checked Climedo and i find no issue there. If you send us a PUT request on /external-data/:personUUID (and this person has incremented lastFollowUpEndDate) as a result of the conversion from contact -> case then we will just update the last follow up end date in climedo (same as if you just update it for a contact in Sormas and send PUT request to climedo for an update) Please check it out and see where the bug is.

_Originally posted by @DraganMileski in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4519#issuecomment-821201806_

**Comment by FredrikSchaeferVitagroup** [comment]
This is a follow up ticket of the bug mentioned in the description. It might be that the [PUT request mentioned in the issue description](https://github.com/hzi-braunschweig/SORMAS-Project/blob/66672869e324d88a690fc7c047c4729a00755efb/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L262) is not sent to climedo when a contact is converted to a case.

**Comment by FredrikSchaeferVitagroup** [comment]
To verify this issue, please convert a contact to a case on https://ga1.sormas-oegd.de/ and see if the follow up end date gets updated in climedo. For that, it is necessary to have to follow up end date different in the contact and in the resulting case.

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as the follow up end date does not get updated.

**Comment by FredrikSchaeferVitagroup** [comment]
I investigated, and it looks all good on SORMAS-side. I will get in touch with the climedo developers, maybe something is wrong on their side.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on ga1 environment

**Comment by mariusclimedo** [comment]
Hi, question: would this also solve the case when a person is registered as a case, completes the first follow-up via Climedo and then is registered as a second case again later? I.e. not converting a contact to a case, but an additonal case.

**Comment by Alexandru-Pirvu** [comment]
@mariusclimedo Hi Marius, the case you described is also covered.
