### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: DiagnosticReport.conclusionCode [2]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5159]
### Situation Description

This issue is part of #5136.

Preriquisite: [#20](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/20).

Related demis-adapter ticket is [#17](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/17) (it's a dummy ticket holding no additional information).

### Feature Description

The new profiles for demis notifications hold a "Kodiertes Gesamtergebnis" in the DiagnosticReport.conclusionCode. This most probably relates to the Sample.pathogenTestResult. This shall be mapped.

- [ ] Add a sampleOverallTestResult to the labMessageDto and -Entity.
- [ ] In the demis adapter, transfer the DiagnosticReport.conclusionCode to the lab message.
- [ ] Transfer the LabMessage.sampleOverallTestResult to the SampleDto.pathogenTestResult when processing a lab message, and show this in the UI.
- [ ] Add this fields to related unit tests in the demis adapter and SORMAS project.
- [ ] reenable showing the test result of a lab message in the index list by using the LabMessage.sampleOverallTestResult. A starting point to look at would be the LabMessageFacadeEjb.getIndexList

### Additional Information

According to [this profile](https://simplifier.net/demis/laboratoryreportcvdp), DiagnosticReport.conclusionCode can have [two values](https://simplifier.net/demis/conclusioncode) (and probably can be null). It is pretty clear that
pathogenDetected = PathogenTestResultType.POSITIVE
pathogenNotDetected = PathogenTestResultType.NEGATIVE

### Open Questions

- Shall the DiagnosticReport.conclusionCode also be transferred to the SampleDto.pathogenTestResult when the [DiagnosticReport.status](https://simplifier.net/demis/laboratoryreportcvdp) is set to preliminary? Issue for the DiagnosticReport.status is #5551. ANSWER: Yes. Also ask to update the sample result if necessary.

**Comment by Jan-Boehme** [comment]
@FredrikSchaeferVitagroup 

I'd say yes to using the conclusionCode as testResult even if the diagnosticReport is only marked as "preliminary". Otherwise we may run the risk of people being tested positive but not being processed properly because the sending lab just forgot to set the correct value.

Maybe this is something to discuss in our video meeting on wednesday with @kwa20 and @JaquM
