### ISSUE TITLE
Enable Vaadin push for long-going processes and notifications

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#516]
In order to use vaadin push for SORMAS UI we need to have a seperate Login UI that works without push. The reason being that vaadin uses AtmosphereRequests instead of ordinare HttpRequests and thisway we don't have access to methods like login(username,pw) (see https://github.com/vaadin/framework/issues/4401).

Best way to do this is to register a servlet on /login and redirect all requests to /* when the user is not logged in yet.

**Comment by MartinWahnschaffeSymeda** [comment]
Since we plan to move to a pure javascript framework mid-term, this is no longer needed.
