### ISSUE TITLE
Changing case outcome back from Deceased wont make person alive

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5170]
### Bug Description

Changing a case-outcome back from recovered won't always change the persons condition to alive

### Steps to Reproduce

1. Go a case which is set to Deceased
2. Change outcome to Recovered or Unknown
3. The case should be changed correctly, but the cases person is still set to dead

### Expected Behavior

Change the person accordingly

### Additional Information

Discovered while investigating #5099, so possibly related

Edit: Maybe also related to #4964

**Comment by MateStrysewske** [comment]
Should be handled in #4964
