### ISSUE TITLE
Location of the person directory in menu / order of the menu

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5171]
### Bug Description

I've seen in the 1.59-snapshot that "person" was moved in the new Sormas-version and I'am not sure if this was wanted:

![grafik](https://user-images.githubusercontent.com/74791118/115548243-889a8c00-a2a7-11eb-9d39-630a6cccc119.png)

As the cases are most important the order should be:

case
contact
person

Otherwise the current (old) orde is also fine.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL: https://test-de1.sormas.netzlink.com
* User Role:

**Comment by MateStrysewske** [comment]
This was specifically requested in #3776, yes

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Thanks. I havent seen it before!
