### ISSUE TITLE
Display an informative error message when user does not have the rights to create event groups

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5175]
### Bug Description

Issue #4570 added the possibility to create event groups.
All web users have read access to events but only users with write access to all events in a group can create or edit the meta data of a group. This results to an error message when a user try to create an event group without having write access to all events in the group. However, users should be able to add events that they have full access to into a group that already exist but they do not have full access to the meta data of the group (ie all events in the group)
### Steps to Reproduce

1.  Create a user with surveillance officer and national user role
2. Create an event group using events in a jurisdiction that is not in the jurisdiction if the surveillance officer
3. You get a error 

### Expected Behavior

If a user try to create a group without having full access to all events in the group, show a warning message like `You do not have the right to create this groups because you do not have full access to all events selected.`
### System Details

* Device:
* SORMAS version: 1.49
* Android version/Browser:
* Server URL: https://test.sormas.netzlink.com/sormas-ui/
* User Role:

**Comment by bernardsilenou** [comment]
@ftavin

**Comment by MateStrysewske** [comment]
@bernardsilenou It's not possible to create a user with both the Surveillance Officer & National User roles. Logging in only as a surveillance officer, I'm not really able to reproduce this error because the buttons to add the event to an event group is greyed out if I have read-only access to it. I'm not really sure what to do in order to reproduce this issue because the "steps to reproduce" you've provided don't work for me.

**Comment by bernardsilenou** [comment]
@MateStrysewske  Thanks for the correction, It is about creating a user with admin and surveillance officer roles. And this is not an issue since the jurisdiction is determined by the SO role as they only see entities in the district. Do you think we need to change this?
@ftavin I just tried to see if I can reproduce the error we had today but I could not, all works fine. 

I would close the ticket then, we can open again of ti shows up
