### ISSUE TITLE
SERVER_SETUP.md needs update and verification (test setup on Linux host)

### ISSUE THREAD

**Issue by gitisara** [hzi-braunschweig/SORMAS-Project#5183]
### Bug Description

SERVER_SETUP.md instructions no longer builds the system as claimed and expected.

Considering the Fact that Second Wave of COVID-19 Increased the Demand of SORMAS as per WHO recommendations for their Local level Micro containment zones. The Need of  **_Simplified , Verified ,Minified_**  & Wherever Possible with Server Requirements suggestion has also Increased.

Typically SORMAS have been adopted by State Level Governments having No Urgency and Plenty of Tech force at their Dispose.
But Local Administrations have lack of Dev Ops Teams or SORMAS patrons.
Unverified Instructions from New User's context is a painful to use this beautiful piece of art.

Request Contributors for helping hand in making the onboarding smooth so more people can be saved. 
(Similar to what  BigBlueButton Army did recently for Education)  
### Steps to Reproduce

1.Create EC2 Instance ( With All port open @ Ubuntu 18.04 ) / LOCAL
2.Follow the SERVER_SETUP.md
3. Accessing IP: 6080/6081/6048 (Without Apache2)
4: Accessing IP:80/443 (With Apache2)
5: No Response 

### Expected Behavior

SORMAS should be function as it is on Docker Image.
### System Details

* Device: AWS t3a.medium (2v 4GB : No Firewall) / LOCAL i5 | Ubuntu 18.04 x64
* SORMAS version: 1.58.3
* Android version/Browser: Chrome 90.0.4430.85 
* Server URL:
* User Role:

### Additional Information

Diagnostics Insights : 
-DOCKER Image runs fine
-Payara 5 & Apache2 Default Page reachable
-sormas-ui not being built and possibly many other components 
-Same output on LOCAL and CLOUD
- Installing "Temporal Tables" displays warning related versioning.io (Tried from Git to make without warnings , successful but no change in output)
-postgres phase displays warnings about "schema"

**Comment by fhauptmann** [comment]
Following up to this I would recommend mentioning SORMAS-Docker as the recommended way to set up SORMAS, as it is used most widely in different environments. Setting it up is much easier then following the guides to set up SORMAS the 'classical' way.

**Comment by DavidBaldsiefen** [comment]
This is probably related to #5053 

Maybe it is also related to the missing `unaccent`-extension for psql on fresh installs?

**Comment by gitisara** [comment]
> Following up to this I would recommend mentioning SORMAS-Docker as the recommended way to set up SORMAS, as it is used most widely in different environments. Setting it up is much easier then following the guides to set up SORMAS the 'classical' way.

yes , But Docker have limitations , especially when it comes to Deep Customization as per different structures of governments and policy. Also Its hard to scale and under performing in typical Government servers of Developing Nation.

**Comment by StefanKock** [comment]
There might be overlappings with #5230

**Comment by StefanKock** [comment]
I tested the server-setup.sh script as part of #5230 and did not find any implementation errors in the script. I did not test server-update.sh since I did my testing on Windows.

**Comment by StefanKock** [comment]
I moved this down in the Backlog column because it is not clear to do with this ticket.

**Comment by gitisara** [comment]
> I tested the server-setup.sh script as part of #5230 and did not find any implementation errors in the script. I did not test server-update.sh since I did my testing on Windows.

Please test the fresh installation on bare ubuntu server. to reproduce the error started.

**Comment by StefanKock** [comment]
In the recent days I fixed some flaws in https://github.com/hzi-braunschweig/SORMAS-Project/commits/development/docs/SERVER_SETUP.md

**Comment by StefanKock** [comment]
No open problems known, closing this ticket.
