### ISSUE TITLE
Inconsistent information for last report and last report district on dashboard

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#5185]
### Bug Description
At the dashboard **sometimes** the variables for last report and last report district appear inconsistent. 
Personal communication to Vitagroup revealed that this is unexpected behavior. 
### Steps to Reproduce

1.Enter dashboard
2.check variables "last report" and "last report district"

### Expected Behavior
Both variables (last report AND last report district should be consistent. 

### Screenshots
![image](https://user-images.githubusercontent.com/76884029/115671655-082d6700-a34b-11eb-97f5-212e5c0f8543.png)
case for Sachsen-Anhalt - Dessau-Roßlau
![image](https://user-images.githubusercontent.com/76884029/115673002-6c9cf600-a34c-11eb-84be-0aad08b07155.png)

![image](https://user-images.githubusercontent.com/76884029/115672127-8427af00-a34b-11eb-9e51-1a70a4d0dd78.png)
case for Baden-Württemberg - Biberach
![image](https://user-images.githubusercontent.com/76884029/115672187-986bac00-a34b-11eb-84f1-7bd55493f36a.png)
![image](https://user-images.githubusercontent.com/76884029/115672201-9b669c80-a34b-11eb-913a-3e78fb3de43c.png)

### System Details

* Device:
* SORMAS version: 1.58.3
* Android version/Browser:
* Server URL: https://musterstadt.sormas-oegd.de/
* User Role: admin

**Comment by MateStrysewske** [comment]
This will be handled in #3004
