### ISSUE TITLE
Make facility selection on LocationForm more intuitive

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5188]
### Situation Description
Currently, if a user selects a correct `facilityTypeGroup` and `FacilityType` on the LocationForm, a list of available Facilities will only appear if a district is specified:

![image](https://user-images.githubusercontent.com/4655486/115691999-dc1be100-a35e-11eb-8dcf-b6da6e221f9f.png)

Also, it is not possible to define a custom facility with these presets.

### Feature Description

- [ ] Add a visual indicator to the facility field if no district is selected, that informs the about the reason
- [ ] ~~Always enable the selection of "Other Facility"~~

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen I suspect it's not that easy. There's quite some logic in the backend that relies on facilities being associated with a district, and allowing users to specify a facility without specifying a district might break that logic. We'll need to properly investigate this once we pick it up.

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske Yes I was also not sure about the second part. I would still add the indicator though, as it was something I really stumbled upon this morning (wondering why no facility is shown)

**Comment by DavidBaldsiefen** [comment]
**For Testing**: You need a location form where the district/facility field is not mandatory, as that warning would override the information indicator. For example, the location part of the exposuresform could be used for validation.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment.
On the Epidemiological tab of a case, Exposure entry, The warning is displayed when trying to select Facility.
