### ISSUE TITLE
Prompt to update case disease variant is not shown when processing lab messages

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5190]
### Bug Description

The recently introduced feature that asks users to update the disease variant of a case when a positive pathogen test with a different disease variant is saved (#5029) does not work when processing lab messages.

### Steps to Reproduce

1. Process a lab message
2. Enter a pathogen test with a different disease variant than the selected case and save

### Expected Behavior

The users should be asked to update the disease variant of the case

### System Details

* Device:
* SORMAS version: 1.59.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by FredrikSchaeferVitagroup** [comment]
Does the popup show at all? Even when I manually create samples and pathogen tests, I can't get the popup to show. 
When I check in the database, the column diseasevariant_id in the cases table always just contains `null` values.

Also, the [CaseDataDto.setDiseaseVariant(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/22c2afb94709493a0518e7e92009f4eaba3088f5/sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java#L802) seems to be only called two times, none of which set's the disease variant initially.

The disease variant of a case does not seem to show anywhere in the UI.

Am I missing something here?

**Comment by MateStrysewske** [comment]
@FredrikSchaeferVitagroup You need to add disease variants to your database according to this guide: https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Adding-Disease-Variants-to-a-SORMAS-Server
