### ISSUE TITLE
Add event groups to database export [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5191]
### Feature Description

The Statistics -> Database Export view allows users with the respective rights to export the direct contents of the database tables.

### Problem Description

The new event groups have not yet been added to the database export, so there's currently no way to export them.

### Proposed Change

Add event groups to the database export functionality.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com
