### ISSUE TITLE
Lab Messages are displayed in an xml format all the time

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5193]
![image](https://user-images.githubusercontent.com/70562142/115717900-4a729a80-a383-11eb-9a7c-b3a6c89706cd.png)
### Steps to Reproduce

1. Open test-de2.sormas.netzlink.com env and go to samples
2. Open Lab messages and click on the Eye icon 
3. Check how the lab messages are displayed

### Expected Behavior
The lab messages should be interpreted as HTML and be displayed as before

### Actual Behavior
The XML display of lab messages is enabled once there are problems with the Converter setup.
The same issue can be seen also when a Lab Message gets processed or when an associated lab message is opened.
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/115717941-565e5c80-a383-11eb-9f34-2291120fc1e2.png)
### System Details
* Device: windows
* SORMAS version: 1,59.0-snapshot
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: NatUser

### Additional Information
![image](https://user-images.githubusercontent.com/70562142/115717941-565e5c80-a383-11eb-9f34-2291120fc1e2.png)

**Comment by FredrikSchaeferVitagroup** [comment]
That is not a bug in SORMAS. It's a fallback when the adapter can not be found. test-de2.sormas.netzlink.com was misconfigured.
