### ISSUE TITLE
[Angular] Columns to be draggable in any overview page [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5197]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to be able to drag and drop columns from any table (overview page)
- The user preferences should be saved in the local storage (as long as the keycloack session is still used) (Note: Please investigate if this is viable, if the keycloack session is to short, it might be best not to work on this feature now, and added later).

### Possible Alternatives

N/A

### Additional Information

N/A

### Story Points: 5 POINTS

**Comment by cristinacoza** [comment]
UI/UX review done - looks good
