### ISSUE TITLE
[Angular] Table height to stretch to full-height [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5198]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- The table's height should be full page (as to reach the bottom of the page).
- This should be applicable only on overview pages (Cases, Tasks, etc) - wherever large/long tables are used.

### Possible Alternatives

N/A

### Additional Information

N/A

### Story Points: 5 POINTS

**Comment by cristinacoza** [comment]
UI/UX review done, everything looks good
