### ISSUE TITLE
[Angular] mSERS: Implement different table variant [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5206]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- In the "table" component we need to use a param (i.e "table_1", "table_2") as to be able to display different variants of tables
- Consult design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/p/msers (only the listing)

### Possible Alternatives

N/A

### Additional Information

N/A

### Story Points: 2 POINTS

**Comment by cristinacoza** [comment]
UI/UX review Done
