### ISSUE TITLE
[Angular] Case Port Health tab (German version) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5207]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/ab0bd823-c1cb-40e0-bf80-54ad7cdfce11/p/port-health (the basic structure)
- Based on the point of entry the form below will contain different elements (please consult the german system for more details)
-

**Comment by cristinacoza** [comment]
UI / UX review Done. Everything looks good!
