### ISSUE TITLE
Follow-up until date cannot be extended when there are visits before the original follow-up until date

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#5212]
### Bug Description

When a contact's follow up date is extended by selecting the checkbox "overwrite follow-up" it is only possible to extend once/to a particular date and not beyond.
There is no error message displayed and contact is shown as saved but the date is not extended.

### Steps to Reproduce

1. Login to Sormas as Contact Sup or any other user
2. Select contacts directory and pick a contact (Ex: UserB test)
3. Select the checkbox to overwrite follow up date and pick a future date (Ex: June 2022) and save the contact
4. See if the selected date is displayed after saving.

### Expected Behavior

The selected date is not displayed and no proper error message is displayed.
In addition the contact is shown as saved successfully.

### Screenshots

Follow up date before overwriting:
![Follow up untill date current](https://user-images.githubusercontent.com/62763628/115737894-da691200-a38c-11eb-90e5-acb94e51403d.PNG)

Current selection:
![current selection](https://user-images.githubusercontent.com/62763628/115737922-e05ef300-a38c-11eb-8b7a-26bc4795eed8.PNG)

After selecting and saving:
![Follow up date after saving the contact](https://user-images.githubusercontent.com/62763628/115737968-e5bc3d80-a38c-11eb-8956-5641049dbe59.png)

### System Details

* Device:
* SORMAS version: 1.59.0 and 1.60.0
* Android version/Browser:
* Server URL: test.sormas.netzlink.com
* User Role: ContSup or any other user

### Additional Information

Issue is relatable to #4191

**Comment by bernardsilenou** [comment]
- Suggest we validate the allowed number of days for extension to be <= 2* incubation period., ie expected followup + 2*incubation period.
- Show a warning message if user extend beyond this date and ask user to choose another date.
- We cannot validate extension period on a fixed date because for diseases like Tuberculosis, the follow up may be extended for a year while for others like COVID, it would be a data error to remind the user to correct.

**Comment by MateStrysewske** [comment]
@bernardsilenou This issue is about a bug that makes it impossible to extend the follow-up until date in some cases. It's not about introducing or changing any logic.

**Comment by syntakker** [comment]
I had some trouble reproducing the error: the relevant part is that the contact / case has visits. The subsequent calculation to adjust the FollowUpUntil date accordingly fails.

**Comment by raghupola-vg** [comment]
Tested on version 1.60.0 Snapshot and issue is Fixed.
