### ISSUE TITLE
contacts>follow-up view> filter dropdown for responsible contact officer is empty

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#5216]
### Bug Description
The dropdown to filter for responsible contact offers remains empty. Hence, search function is not available.

### Steps to Reproduce

1. go to contact directory
2.choose follow-up view
3. try to filter for the responsible contact officer - the dropdown is empty

### Expected Behavior
All available contact officers (of the instance) should be presented here.

### Screenshots
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/76884029/115839152-a9372300-a41a-11eb-9707-ed2fce27bfda.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/76884029/115839327-d1bf1d00-a41a-11eb-9dec-5aba8e2f3f72.png">

### System Details
* Device:
* SORMAS version: 1.58.3
* Android version/Browser:
* Server URL:https://test1401.sormas-oegd.de
* User Role: admin

**Comment by MateStrysewske** [comment]
@maxiheyner Why was this issue closed?

**Comment by maxiheyner** [comment]
@MateStrysewske because it's no bug. It is working...
