### ISSUE TITLE
Name of source case does sometimes not show in the ExposuresField

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5218]
### Bug Description

This seems to happen just in some cases, but then seems to be persistent (just reloading the page does not change the behaviour).

There *might* be some correlation with the users language setting. This could not be reliably reproduced though

### Steps to Reproduce

1. Chose a source case from a contact
2. Convert that contact to a case
3. Add an exposure
4. Add the source case to the exposure.
5. Click on DONE.
Sometimes, the Name of source case column is empty after that.

### Expected Behavior

The Name of source case should show the appropriate name of the source case.

### Screenshots

Below there is an exposure that caused this behaviour:

![image](https://user-images.githubusercontent.com/67001822/115848036-bf95ac80-a423-11eb-92d4-b7c5ec7c6553.png)
![image](https://user-images.githubusercontent.com/67001822/115848144-db994e00-a423-11eb-8000-19b287436565.png)

And the ExposuresField

![image](https://user-images.githubusercontent.com/67001822/115848299-fec3fd80-a423-11eb-9983-489a225bfbe3.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.60.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local dev system
* User Role: National User

**Comment by DavidBaldsiefen** [comment]
I am unable to reproduce this right now. However, I would keep this open for now, as the issue definetely occured recently. The logs were empty when that happened

**Comment by DavidBaldsiefen** [comment]
I could reproduce this (or something very similar) again; Steps to take:

1. Add an exposure
2. Select "Animal Contact" as type of contact without entering anything else
3. An error shows up. You can press done again to save or change the type of contact
4. The list will now show an entry with empty fields
![image](https://user-images.githubusercontent.com/4655486/122064646-97a64200-cdf1-11eb-9d25-44c023e86420.png)

**Comment by ChristopherRiedel** [comment]
> I could reproduce this (or something very similar) again; Steps to take:
> 
> 1. Add an exposure
> 2. Select "Animal Contact" as type of contact without entering anything else
> 3. An error shows up. You can press done again to save or change the type of contact
> 4. The list will now show an entry with empty fields
>    ![image](https://user-images.githubusercontent.com/4655486/122064646-97a64200-cdf1-11eb-9d25-44c023e86420.png)

This has nothing to do with the original issue. I've created a new one for this (#5815).
