### ISSUE TITLE
Events > Event Directory > 'Groups' column not sorting/ordering

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5222]
### Bug Description

The column 'Groups' does not sort in the Event Directory view.

### Steps to Reproduce

1. Events > Event Directory
2. Click Column heading 'Groups'
3. No ordering

### Expected Behavior

Ordering of column entries should be done.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/115892646-a4dd2b00-a457-11eb-80f3-a7d1ca4133ac.png)

### System Details

* Device: Desktop
* SORMAS version: 1.59
* Android version/Browser: Chrome
* Server URL: https://stable-release-ch.sormas.netzlink.com/
* User Role: admin

### Additional Information

@bernardsilenou @aponcon-atolcd - not sure if this is intended behaviour, if you could please confirm?  If it is intended behaviour, please close the issue. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4573

**Comment by bernardsilenou** [comment]
@ftavin We forgot to specify this is the main issue.

**Comment by MateStrysewske** [comment]
@Candice-Louw @bernardsilenou This is intentional and unfortunately can't be changed because the column is a generated one, i.e. sorting can't be done directly in the database.
