### ISSUE TITLE
Merging duplicate cases should not lead to duplicate external token warning

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#5226]
### Bug Description

Merging duplicate cases always leads to duplicate external token warning if the reference case has an empty external token field and the reference case has not.

Background / Steps to reproduce:
Two days ago we our SormasX rollout took place.
Because of unexpected behaviour in the Survnet data import, we ended up with a lot of duplicate cases in our Sormas instance.
Those duplicate cases always look like this:
- case 1 [Previous SORMAS entry]: External ID: empty, External Token: empty, External token (case person): empty
- case 2 [Imported from Survnet]: External ID: Survnet case guid, External Token: Survnet "Aktenzeichen", External token  (case person): AddPers2021-1234 (Suvnet Person Aktenzeichen)

When merging cases and choosing case 1 as reference, Sormas copies the fields mentioned from case 2 to case 1 and then deletes case to. 
This leads to:
A) duplicate external token warning in case view
B) duplicate external token warning in case person view
C) The same survnet guid being used in the active merged case and the deleted case

### Expected Behavior
When merging two cases:
  For fields external id, external token (case), external token (person)
  If field is filled in both case1 and case2:
    Keep contents of case2 field before deleting
  If field is empty in case1:
    copy contents from case2 to case1
    empty contents of field in case2
    then delete case2

(case1 being the reference case, case2 the one that ends up deleted after merging)

### System Details
* SORMAS version: Version: 1.58.3
* Migration from Survnet to SORMAS done, SORMAS2Survnet interface activated.

**Comment by MateStrysewske** [comment]
Hey! I'd like to keep this going in #5149 because we already have a discussion there. I don't know whether actively removing the value from the deleted case is a good idea because it means we're actively manipulating data. If that's the solution though, we can also take care of it in the existing issue.
