### ISSUE TITLE
Prevent a double-click on buttons [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5227]
### Situation Description

A lot of web users double click links and form buttons. 
Currently it is possible to click on buttons with a double click. This might lead to problems with e.g. sending a case to the reporting system. 
The problem isn't that they click form buttons twice, the problem is whatever server side processing is going on doesn't know how to handle a double submit. 

### Feature Description

After a button is clicked, the button should fade out so that it's apparent that the button was clicked.

### Implementation
1. Use below given source code, include this in `ButtonHelper`.
2. Refactor every usage of direct instantiation of any `Button` instance to be created by `ButtonHelper`. Check also for Button subclass usage.

### Additional Information

There is no fast forward way for this in Vaadin. In similar products, we use this pattern for every Button or subclass of it:

```
Buttons.preventExtraClicks(new Button("my button not to be double clicked"));

//...

public final class Buttons {

	private Buttons() {
		// Hide Utility Class Constructor
	}

	static final Button.ClickListener ENABLE_LISTENER = (Button.ClickListener) event -> event.getButton().setEnabled(true);

	public static <B extends Button> B preventExtraClicks(B button) {

		button.setDisableOnClick(true);
		button.addClickListener(ENABLE_LISTENER);
		return button;
	}

	public static <B extends Button> B removeExtraClickProtection(B button) {

		button.setDisableOnClick(false);
		button.removeClickListener(ENABLE_LISTENER);
		return button;
	}
}
```

**Comment by StefanKock** [comment]
From a user perspective, this is not a new feature, but a change to the existing architecture.

**Comment by MateStrysewske** [comment]
Implementation should not be picked up before #5252 has been done. Part of the work will already be done in that issue (i.e. introducing the general logic and applying it to the buttons used to send data to Survnet).

**Comment by DavidBaldsiefen** [comment]
In this suggested implementation, the button will get re-enabled after another click (so 3 clicks in quick succession would act like a double click). An alternative would be to add a timeout (i.e. 2 seconds) after each click. However that could also be misleading, e.g. if the server is still loading something and suddenly a button gets re-enabled.
