### ISSUE TITLE
Add multiple variables to detailed and custom export [2]

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#5229]
### Feature Description
The user asked for multiple variables, that are missing so far in detailed and custom case export. These are the following:
1. sequelae (YES; NO; UNKNOWN) & sequelae details (text)
2. symptoms
3. clinicianName, clinicianPhone, clinicianEmail
4. reportingUser & responsibleUser, as name in one column with separate user role in another column
5. status and date of investigation
6. help needed in quarantine - text
7.  add the symptom journal status to exports for contacts
8. prohibition to work (YES/NO/UNKNOWN) and from/until dates

### Problem Description
So far many important variables are missing within detailed and custom export. 
### Proposed Change
Add the variables mentioned above to detailed and custom export.

**Comment by MateStrysewske** [comment]
Hey!

> symptoms
These are already part of the detailed and custom case export. They're also part of the detailed contact export as "Symptoms at last cooperative visit". What exactly are you missing here?

> reportingUser & responsibleUser, as name in one column with separate user role in another column
What would be the reason to combine them in one single column? Also, reporting user is automatically filled in during import; the purpose of this field is to contain the user that created the case in SORMAS

> status and date of investigation
Investigation status is already there, but date is missing

> provide a custom PERSON and a custom TASK export (providing all available variables from the db)
This would require two separate issues

**Comment by maxiheyner** [comment]
@MateStrysewske Hey!

symptoms
These are already part of the detailed and custom case export. They're also part of the detailed contact export as "Symptoms at last cooperative visit". What exactly are you missing here?
**Is it possible to show only the symptoms that were checked to get a better overview and to limit the number of columns?**

reportingUser & responsibleUser, as name in one column with separate user role in another column
What would be the reason to combine them in one single column? Also, reporting user is automatically filled in during import; the purpose of this field is to contain the user that created the case in SORMAS
**sorry this was misleading: the user wants to have the reporting user as name and user role in separate columns AND the responsible user as name and user role in seperate columns.** 
status and date of investigation
Investigation status is already there, but date is missing
**the date would be also of interest for the user**
provide a custom PERSON and a custom TASK export (providing all available variables from the db)
This would require two separate issues
**ok**

**Comment by MateStrysewske** [comment]
@maxiheyner 

> Is it possible to show only the symptoms that were checked to get a better overview and to limit the number of columns?

Currently not, no. Would be a feature we would need to add.

> sorry this was misleading: the user wants to have the reporting user as name and user role in separate columns AND the responsible user as name and user role in seperate columns.

Understood!

**Comment by maxiheyner** [comment]
@MateStrysewske Currently not, no. Would be a feature we would need to add.
Yes please this would be a nice feature

next points:
1. the "names of the guardians" should be included to detailed export for cases and contacts
2. within the detailed export of cases the users recognized that, when paragraphs within free text fields are used, several lines are produced within the export file - is it possible to prevent this?

**Comment by markusmann-vg** [comment]
@maxiheyner 

- Person export will be covered with https://github.com/hzi-braunschweig/SORMAS-Project/issues/6206

- We discussed internally, that showing only the checked symptoms could be a new feature for the custom export and therefore you should create a new issue.  

- "within the detailed export of cases the users recognized that, when paragraphs within free text fields are used, several lines are produced within the export file - is it possible to prevent this?" => will not be covered with this issue and a new issue should be created
