### ISSUE TITLE
Improve documentation for developer setup

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#5230]
### Feature Description

It should well documented and easy to do, to set up a developing instance of SORMAS on a developers own machine.

### Problem Description

Starting point: Findings by @cazacmarin documented here: https://github.com/hzi-braunschweig/SORMAS-Project/pull/4083/files

### Proposed Change

To be reviewed and refined by @cazacmarin and @StefanKock 

### Additional Information

The `sormas-base/dev-setup` caused lately confusion (highly duplicated to `sormas-base/setup`), should be taken into account too how we want to handle this.

**Comment by cazacmarin** [comment]
I did a commit instead merge directly on development, as the DEVELOPMENT_ENVIRONMENT.md file was moved till the moment when work was done on it.
