### ISSUE TITLE
Add case followup information on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5237]
### Bug Description

- There is not case followup information on the mobile app
-  I do not know know if this feature was not just added to the mobile app.
### Steps to Reproduce

1.
2.

### Expected Behavior

Add a followup tab to cases on the mobile app, similar to that of contacts

### System Details

* Device: Android 7
* SORMAS version: 1.59
* Android version/Browser:
* Server URL:
* User Role: surveillance officer + contact officer

**Comment by MateStrysewske** [comment]
Duplicate of #2650
