### ISSUE TITLE
Abnormal behavior with editing followup  information of contacts on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5238]
### Bug Description

When you enter a visit to a contact, you get the message "visit safe successfully" before you are asked to register the symptoms. This message should only show after saving the symptoms.
When you edit a visit, it does not ask you to edit symptoms but show a  "save successful message" immediately after saving the tab on "available and cooperative", thus impossible to edit symptoms. System should present symptoms for editing also.
### Steps to Reproduce

1. Edit a visit of a contact on the mobile app
2.

### System Details

* Device:    Android 7
* SORMAS version: 1.59
* Android version/Browser:
* Server URL:
* User Role:    surveillance officer + contact officer

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou do you have any information on whether this bug is new or if it already existed for some time? The more I keep digging into this, the more bugs I find, however it feels like this should never have worked in the first place so I'm not sure if I'm going in the right direction

**Comment by bernardsilenou** [comment]
@DavidBaldsiefen  
- Sorry to reply so late, last week was tight on my side.
- I did not test the followup logic for long so I can not tell if this was a new bug.
- Is there something that i still need to have a look at? or you could get too the root cause?

**Comment by DavidBaldsiefen** [comment]
@bernardsilenou it should be fixed now, thank you :)
