### ISSUE TITLE
Add "Not done" as a new final laboratory results for samples (2)

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5240]
### Bug Description

#4219 added not done as a category of final lab result of a sample. This change is missing  in 1.59
This has affected #5029. Variants of the case can be set to NA even when there is a pathogen test of the sample having a variant of the disease of the case.
### Steps to Reproduce

1. Create a sample and have a look at final lab results, there is no option for not done
2.

### Expected Behavior

- https://github.com/hzi-braunschweig/SORMAS-Project/issues/4219#issue-799959190
- 
### System Details

* Device:
* SORMAS version:1.59
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: admin + national user

**Comment by MateStrysewske** [comment]
@bernardsilenou "Not done" is removed as an option when there is at least one pathogen test for the sample that is not set to "Pending". In any other case, it can be selected.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
ohhh merde! I how can I forget that! thanks
