### ISSUE TITLE
Hospital informants should have access to events in their facility or districts

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5242]
### Bug Description

- Hospital informant (HI) connected through the web app does not see events in their jurisdiction or facility
- Hospital informant connected through mobile app sea few events in their district. The logic on which event that they should see is not clear.

### Steps to Reproduce

1. Log in on web and on app using a hospital informant
2. Have a look on event directory, directories do not present the same events 

### Expected Behavior

1. HI should have read access to all events in the districts of their felicity + write access to add ep in those events
2. HI should have read and  write access to events and ep in their facility
3. HI should be able to create events  in their facility @MateStrysewske is there any reason that we should not allow them ? There can be a nosocomail outbreak in a hospital.

### Screenshots

![image](https://user-images.githubusercontent.com/12996724/116153700-04516a00-a6e8-11eb-9fdf-25acf94a9876.png)

### System Details

* Device:
* SORMAS version:1.59
* Android version/Browser: Android 7 + web
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: Informant

### Development Specifications
* Adjust the event user filter for users on facility level and grant them access to all events in the district of their facility

**Comment by bernardsilenou** [comment]
Should be implemented together with #4838

**Comment by MateStrysewske** [comment]
@bernardsilenou Hospital Informants are currently not supposed to create events. This has been defined like this by HZI, I can't tell you the reason. 

The user filter for events indeed does not properly include community- and facility-based users, so that's something we need to fix.

**Comment by bernardsilenou** [comment]
@MateStrysewske Thanks for the info. Agree with you that we keep the right as it is and only adjust the filter. 
On mobile and even on web app we can push only events in the district/ or facility to the users view in order not to overload the mobile app.
