### ISSUE TITLE
Add customizable enum configurations [5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5247]
### Situation Description

A lot of the fields used in SORMAS are based on hard-coded enum values. With more and more countries using SORMAS, we have an increased amount of requests that ask us to extend these values or hide some of the existing ones. These requests are often very specific to the country they're coming from and aren't applicable to any other country, which requires us to add additional code that controls the visibility based on the server locale. Additionally, it makes it necessary for us to implement all these changes in the first place even though they are very specific and don't necessarily contribute to the overall picture of SORMAS. It also means that users who need these values always have to wait for new versions until they can use them.

### Feature Description

This issue is about adding a customizable enum configuration system that can then be used to invidiualize the selectable values per server. Existing enums can then be migrated to this new system when the need arises.

* Add a `customenums` database table. This table will contain one row per customized enum value, and it contains these values for all enum types in the system. It has the following columns:
    * `datatype` (text): The name of the referenced enum, e.g. OCCUPATION_TYPE
    * `value` (text): The enum value like it would be defined in a Java enum (e.g. HEALTHCARE_WORKER)
    * `caption` (text): The caption in the default language of the server (e.g. "Healthcare worker")
    * `translations` (json): Optional translations for additional languages; same pattern as for campaign form translations
    * `diseases` (text): Comma-separated list of diseases that should use this field; if empty, it will be used for all diseases
    * `description` (text): A description of the value, e.g. for usage in the data dictionary or to display it in the UI when we add a frontend for this feature
    * `descriptiontranslations` (json): Optional description translations for additional languages
    * `properties` (json): Further configuration of this specific enum value; see below for an explanation
* Add an abstract `CustomizableEnum` entity class with fields reflecting the database columns above (+ a `defaultValues` json field); enums (read: enumerations, not Java enums) will then extend this class and add custom properties
* Classes extending CustomizableEnum and that should come with default values should have JSON added to the defaultValues field that can be read into the database if the custom_enums table does not contain values for this class
* Add a `CustomizableEnumsCache` that will be built on server startup and can be used to retrieve the data stored in the database for all customizable enums without the need to access the database everytime it's used

**Example:**
Let's say we want to customize the current OccupationType enum. This is what needs to be done in order to do so:

1. Change the current enum to a class that extends CustomizableEnum: `public class OccupationType extends CustomizableEnum`
2. Add fields to this new class that represent additional properties. This will not be needed for all customizable enums, but it is required for OccupationType because in the person form, there are some fields whose visibilities or captions depend on the selected occupation type. The following properties would be added:
    * `hasFacilityDetails` (boolean)
    * `hasOccupationDetails` (boolean)
    * `occupationDetailsCaption` (String)
3. Add JSON to the defaultValues field that define all occupation types that are currently part of the core SORMAS
4. Adjust the UI: Update the data type of the occupationType dropdown in the person form, and change the current logic that checks for specific occuption types when determining the visibility/caption of the depending fields:
    * e.g. the `toggleOccupationMetaFields` method could be replaced by one single value change listener on the occupationType dropdown, the content being something like `setVisible(value.hasFacilityDetails(), PersonDto.OCCUPATION_DETAILS)`
    * likewise, instead of `updateOccupationFieldCaptions` that needs a switch statement to determine the caption based on the selected occupation type, the same listener from above could be extended by something like `setCaption(value.getOccupationDetailsCaption())`

**Comment by StefanKock** [comment]
Mentioned in the Planning: Replace DiseaseVariants with this approach, keep current implementation as default (meant to be non-breaking for german systems).

**Comment by StefanKock** [comment]
Redefined as change because the user does not have any benefit from it.

**Comment by MateStrysewske** [comment]
* Replace converters in the CustomizableEnumValue class with "json" annotations where possible
