### ISSUE TITLE
[SurvNet Converter] Validate the mappings and the Converter Modell against the SORMAS API

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5259]
### Situation Description
create a Test which * checks out a configurable version o_f_ the SORMAS api
Validate that the dtos and enums of the SORMAS api a compatible to dose in the converter

https://jira.vitagroup.ag/browse/SOR-1293

**Comment by StefanKock** [comment]
Seems to be a duplicate to https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/113

**Comment by JonasCir** [comment]
Looks like it :) My PR in the internal repo still needs to be merged by Holger

**Comment by vidi42** [comment]
Closed as it's not affecting the SORMAS Project in any way.
