### ISSUE TITLE
Some urgent issues from the field- Case fatality rates, contact follow up and dashboard by state filter

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#526]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
1.	The calculation for case fatality rate as seen on the dashboard is incorrect (it looks to me that the denominator used was all the cases- suspected, confirmed, not a case e.t.c), so in a way underestimating the situation.(check appendix 1). I think limiting the denominator to confirmed cases only is in order
2.	Calculation of the day to complete follow up as seen on the contact supervisor's platform is also wrong (check appendix 2)
3.	Converting a contact to a case function on the contact officer's app is not working yet. This is very important in this ongoing outbreak and priority should be placed on it.
4.	There is also a need to include the function of moving the contact of a case to another LGA, different from the LGA where the contact was made or the case is
5.	Same with a case too, there is a need to include the function of moving a case to another LGA (those are the real scenarios on ground now)
6.	Also, I realized it is only health facilities that do weekly and zero reports for now, it should also be included for surveillance officers( in real life they do weekly reporting)
7.	For the Contact supervisor's platform, under follow up status of a contact, there is no place to indicate "completed follow-up", only "follow-up cancelled" and "lost to follow-up" (check appendix 3) 
![appendix 1](https://user-images.githubusercontent.com/19344651/37596960-2e3b06de-2b7e-11e8-8a13-6be55e7e2c63.PNG)
![appendix 2](https://user-images.githubusercontent.com/19344651/37596962-2e6b28b4-2b7e-11e8-9969-0ae0e3482550.png)
![appendix 3](https://user-images.githubusercontent.com/19344651/37596963-2e96d27a-2b7e-11e8-93ae-434fcd73b551.PNG)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Can you revise this please and see what is still up to date?

**Comment by hzi-braunschweig** [comment]
@Chinedar @foyiri Please can you test this right now in the field. It is important

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar @foyiri I expect this is resolved? If so, please comment and close this issue.

**Comment by Chinedar** [comment]
This is resolved.
