### ISSUE TITLE
Saving case-events in the android app causes the app to crash

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5262]
### Bug Description
Creating case-events in the android app causes the app to exit.

### Steps to Reproduce

1. Create a case.
2. Go to Case Events
3. Create a new Event and save

### Expected Behavior
Don't crash

### System Details

* Device:
* SORMAS version: 1.60.0-SNAPSHOT
* Android version/Browser: Android 11.0
* Server URL:
* User Role: Surveillance Officer

**Comment by af-pwo** [comment]
Fixed

Samsung Galaxy S9
Android 10
Version 1.60.0
test.sormas.netzlink.com/sormas-rest
User: SurvOff
