### ISSUE TITLE
Adjusting the follow-up period after extending the quarantine does not save changed entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5263]
### Bug Description
When the quarantine of cases or contacts is extended and the follow-up until date adjusted accordingly, the changed until date is not actually saved.

### Steps to Reproduce

1. Enter a quarantine period for a case/contact, save.
2. extend the quarantine and adjust the follow-up accordingly. Check the follow-up until date.
3. Save the case/contact and check the follow-up until date again.

### Expected Behavior
The follow-up until date should be adjusted accordingly.

### Screenshots
Initial values:
<img width="438" alt="followUpAdjust" src="https://user-images.githubusercontent.com/70317594/116397523-f9512380-a826-11eb-9af5-d44eda73ae34.PNG">
extended quarantine:
<img width="356" alt="followUpAdjust2" src="https://user-images.githubusercontent.com/70317594/116397527-fb1ae700-a826-11eb-8b2e-e7d2eb4fb2f7.PNG">
Extending of follow-up:
<img width="389" alt="followUpAdjust3" src="https://user-images.githubusercontent.com/70317594/116397531-fc4c1400-a826-11eb-9e2a-69d38e09f77e.PNG">
Values after selecting yes in pop-up:
<img width="464" alt="followUpAdjust4" src="https://user-images.githubusercontent.com/70317594/116397537-fe15d780-a826-11eb-8983-48c8bcdd63f3.PNG">
Values after saving:
<img width="448" alt="followUpAdjust5" src="https://user-images.githubusercontent.com/70317594/116397543-ff470480-a826-11eb-9279-7c125afb5f8e.PNG">

### System Details

* Device:
* SORMAS version: 1.59.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test-de.sormas.netzlink.com
