### ISSUE TITLE
Clicking discard does not close the pathogen test window while editing

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5267]
### Bug Description
When editing a pathogen test, the window does not close when discard is select as seen for other similar windows (e.g. tasks or surveillance reports).
### Steps to Reproduce

1. Open any sample and edit an existing pathogen test.
2. click discard.

### Expected Behavior
Clicking discard should also close the pathogen test window as seen for other windows.
### System Details

* Device:
* SORMAS version: 1.59.0
* Android version/Browser: firefox, chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by DavidBaldsiefen** [comment]
@kwa20 Do you mean the sample edit view? Popup windows (like the pathogen test _result_ popup) are supposed to be closed when pressing discard; However entire views (Like case view, contact view, or sample view) are only supposed to revert back to their original state when pressing discard. Of course that could be changed for the sample view, but then it would be inconsistent

**Comment by kwa20** [comment]
This would be the pop-up pathogen view.
<img width="698" alt="pathogenEditView" src="https://user-images.githubusercontent.com/70317594/116678787-08acaa00-a9aa-11eb-8378-81e66e035442.PNG">

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.60.0-SNAPSHOT using test.sormas.netzlink.com environment
