### ISSUE TITLE
Missing data dictionary entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5271]
### Bug Description
Some tables are missing in the data dictionary. Such include:

- personContactDetails
- activitiesAsCase
- previousHospitalizations

### Steps to Reproduce

1. Download the data dictionary
2. Check available data

### Expected Behavior
The data dictionary should include the whole Sormas data model

### System Details

* Device:
* SORMAS version: 1.59.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by syntakker** [comment]
See also #5389.

**Comment by VGitVlad** [comment]
Validated ticket on Sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment"
