### ISSUE TITLE
Filter for the report date of events [1]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5273]
### Feature Description

Introducing an filter for the report date of events.

### Problem Description

Events can only filtered by the event date and the evolution date of the event. Sometimes it is needed that we filter it by the report date.

Currently we have to open the directory then, scrolling to right, sorting by the report date and than can see the events for a relevant date. If you then open the event and going back to the directory the sorting is gone. Its very time consuming.

### Proposed Change

Introduce a filter similar to the filter of cases, where you have a multi-filter for dates.

### Development Specifications
* Add the report date to the event reference date dropdown of the general date filter in the event directory
* Extend the criteria filter backend method to include the report date if it's selected

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.

**Comment by kwa20** [comment]
@alexcaruntu-vita the 'report date' does not seem to get translated or be availabe for translation on crowdin
<img width="497" alt="eventReportDateTranslation" src="https://user-images.githubusercontent.com/70317594/147927706-59a2390d-4502-47b5-b25a-d23b3eefbdcb.PNG">

**Comment by MateStrysewske** [comment]
@kwa20 The translation is available, but simply wasn't merged yet. Will be fixed with the noon deploy.
