### ISSUE TITLE
Person case not visible when navigating from pseudonymized person to view it's cases in the case directory

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#5277]
### Bug Description

Case list is empty when navigation from pseudonymized person by using the **"See cases for this person"** button
### Steps to Reproduce

1. Create a case in the default region
2. Add a contact on a second region to the new case
3. Login with a user on the second region
4. From the person directory open the person of the case created at step 1. (it should be a pseudonymized one)
5. Click on the **"See cases for this person"**  button
=> the list of cases in the case directory is empty

### Expected Behavior

The created case should be shown in the case directory, it also should be pseudonymized

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
The *Include cases from other jurisdictions* filter should be active when navigating from person details to cases

**Comment by RazvanHodisan** [comment]
Validated on https://test.sormas.netzlink.com, version: 1.60.0-SNAPSHOT
