### ISSUE TITLE
Bad wrapping in duplicate merging mode for cases

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#5278]
### Bug Description
The Filters in the duplicate merging mode for cases are badly wrapping on my local system. It should not be necessary to scroll to the side, independently of the screens resolution, browser used etc.

### Screenshots
![image](https://user-images.githubusercontent.com/4655486/116536903-d33e8880-a8e5-11eb-96e6-bb2df92bfd4c.png)

### System Details

* Device:
* SORMAS version: 1.60.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL:
* User Role:

**Comment by VGitVlad** [comment]
Validated ticket on sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment
