### ISSUE TITLE
[LabMessages] Contact details get lost when creating an event participant while processing lab messages

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5279]
### Bug Description

When creating an event participant for an existing person while processing a lab message, contact details that are not in the lab message, but exists for the person already, are not kept. They don't show in the event participant creation form called [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/22c2afb94709493a0518e7e92009f4eaba3088f5/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java#L368).

### Steps to Reproduce

1. Create a person with a contact detail. The person should have a name that appears in an unprocessed lab message.
2. Process that lab message. Select the just created person and create a new event participant.
-> The contact detail does not show.

### Expected Behavior
The contact detail should show.

### System Details

* Device: Windows 10
* SORMAS version: 1.60.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local dev system
* User Role: National User

**Comment by FredrikSchaeferVitagroup** [comment]
As of now, there are only lab messages with a positive pathogen test result fetched. The creation of an event participant via processing a lab message is therefore quite unlikely (positive test results should always lead to cases). That's why I think this issue is not very urgent.

Generally, when SORMAS provides the option to create event participants from lab messages, this should work correctly, though.

**Comment by FredrikSchaeferVitagroup** [comment]
The bug does not seem to be reproducible anymore.

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de2.sormas.netzlink.com
