### ISSUE TITLE
Date of last contact in Multi-day Contact mode can be set in the future

### ISSUE THREAD

**Issue by VitaliHZI** [hzi-braunschweig/SORMAS-Project#5283]
### Bug Description
Future Date of Last Contact can be saved on the second try.  (on Multi Day Concact)

### Steps to Reproduce

1. Go to contacts 
2. Click on new contact 
3. Fill out all mandatory fields 
4. Choose Multi day Contact
5. Choose Date of Last Contact in the future 
6. Click save (error disappears)
7. Click again save 

### Expected Behavior
Date of Last Contact is not possible to set in future. 

### Screenshots
First click on save: ![image](https://user-images.githubusercontent.com/79860634/116549620-012bc900-a8f6-11eb-911c-104f203befa0.png)
Second click on save: 
![image](https://user-images.githubusercontent.com/79860634/116549745-27e9ff80-a8f6-11eb-9dc1-ebce28dc920e.png)

### System Details

Device:
SORMAS version: 1.59.0 RC
Android version/Browser: Google Chrome
Server URL: https://release-international.sormas.netzlink.com/ or https://test1401.sormas-oegd.de/sormas-ui/login
User Role: admin, national user

**Comment by VitaliHZI** [comment]
Same behavior also for creating events

**Comment by DavidBaldsiefen** [comment]
> Same behavior also for creating events

I will add that to the PR

**Comment by DavidBaldsiefen** [comment]
@VitaliHZI could you explain the exact problem please? From my understanding, saving events with end days in the future should be allowed

**Comment by VitaliHZI** [comment]
@DavidBaldsiefen  ok than just fix the bug on the contact side. I will clarify the event point and create a new bug, if its wrong. In my eyes as a user, if it's ok, then at least there shouldn't be an error or the red exclamation mark next to the field. ;)

**Comment by DavidBaldsiefen** [comment]
I agree there shouldn't be a warning then. I will look into it

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS Version: 1.60.0-SNAPSHOT deployed on test.sormas.netzlink.com environment
