### ISSUE TITLE
[DEMIS2SORMAS] Map variant specific Nucleic acid detection methods [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5285]
> @FredrikSchaeferVitagroup Can you add instructions on how to extend the sample creation process when processing lab messages to also include these new fields if that's possible?

- [x] The testReport and -Entity need to be extended by a `testPcrTestSpecification` field holding the enum value `PCRTestSpecification`
- [x] The value needs to be transferred from the testReportDto to newly created or selected PathogenTest when processing a labMessage

_Originally posted by @FredrikSchaeferVitagroup in https://github.com/hzi-braunschweig/SORMAS-Project/issues/5029#issuecomment-820413769_

SORMAS-DEMIS-adapter counterpart is [#11](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/11).

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 This issue is marked as todo for the coming sprint, but still lacking specification. Could you please provide it?

**Comment by JaquM** [comment]
@FredrikSchaeferVitagroup do you need any more than described in #11 ?

**Comment by FredrikSchaeferVitagroup** [comment]
Ah,okay. Thank you, that should suffice. I overlooked this, the ticket structure was confusing me a little.

**Comment by abrudanancuta** [comment]
The dropdown for PCR/RT-PCR Test specification doesn‘t display the values VARIANT_SPECIFIC or N501Y_MUTATION_DETECTION if using the Demis values in the Observation.code.coding.code

Steps to reproduce:
1. Prepare the JSON body with one of the codes specific to VARIANT_SPECIFIC or N501Y_MUTATION_DETECTION based on the [mapping table](url
[DEMIS2SormasMapping.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/8140547/DEMIS2SormasMapping.xlsx)
) at the Observation.code.coding.code
2. Send the JSON script to process
3. As National user go to Samples-> Lab messages -> Fetch
4. Process the last notification received
5. Select create contact
6. Check the Processed sample at the dropdown for "PCR/RT-PCR Test specification"

**Actual result**
The dropdown "PCR/RT-PCR Test specification" is not prefiled with VARIANT_SPECIFIC or N501Y_MUTATION_DETECTION(depending of the code sent)

**Expected result**
The dropdown "PCR/RT-PCR Test specification"should be prefiled with VARIANT_SPECIFIC or N501Y_MUTATION_DETECTION(depending of the code sent)

Here is the JSON that I used

[ObservationChange.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8140609/ObservationChange.txt)

Here is the printscreen where can be seen the code 96752-1 which is for VARIANT_SPECIFIC
<img width="1440" alt="Screenshot 2022-02-24 at 14 48 47" src="https://user-images.githubusercontent.com/91872179/155704442-017f8c3c-06e9-43b6-b842-9216d17653df.png">

**Comment by leventegal-she** [comment]
Fixes done on the DEMIS adapter side are linked to  https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/52

**Comment by abrudanancuta** [comment]
Validated on the local env with the version 1.69.0-snapshot(f42cb7c)
