### ISSUE TITLE
Replace event description with event title in event list [0.5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5286]
### Feature Description

The event list in the Android app currently displays the event description.

### Problem Description

An event title field has been introduced some time ago that is now mandatory, while the description is optional.

### Proposed Change

Replace event description with event title in the list of events.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on android phone connected to test.sormas.netzlink.com environment
