### ISSUE TITLE
Integrate Pashtu and Dari into Crowdin

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#5304]
@markusmann-vg @MartinWahnschaffe We have uploaded the translations for Pashtu and Dari. Please can you include it in the SORMAS core so we can have access to it? Thanks

**Comment by MartinWahnschaffe** [comment]
PR has been merged: https://github.com/hzi-braunschweig/SORMAS-Project/pull/5208
