### ISSUE TITLE
Event participants - export configuration - label error

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5312]
### Bug Description
When you are in an event and want to create a personalized export for the event participants, SORMAS offers a list of variables to select. The event ID appears 4 times. This is a label error because once the export has been carried out, we have 4 different IDs (persons, event participant, event ..)

### Steps to Reproduce
1. event
2. event participants
3. export
4. custom export
5. new export configuration

### Expected Behavior
correct label : personID, eventparticipantID, eventID

### Screenshots
![image](https://user-images.githubusercontent.com/65449450/117006802-28650a80-ace9-11eb-9bf3-e95734cf81dd.png)

### System Details

* Device:
* SORMAS version: 1.58.3
* Android version/Browser: chrome
* Server URL: https://sormas.test.esante-bfc.fr/sormas-ui/#!dashboard/surveillance
* User Role: admin

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by MateStrysewske** [comment]
@carolinverset This has been fixed in 1.59.0, see #4929
