### ISSUE TITLE
Make the release notes easier to read

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5313]
### Situation Description

To date, during a version upgrade, SORMAS offers the list of features embedded in the new version.

This list seems to be produced automatically and does not easily identify:
- the new configurable functionalities in the various configuration files.
- the different notifications to activate or not

### Feature Description
In the part framed in red, we think it would be relevant to add two related paragraphs:

- new configurable functionalities in the various configuration files (specifying in which file the adjustment can be carried out)

- new notifications that can be activated or not

![image](https://user-images.githubusercontent.com/65449450/117008972-8e529180-aceb-11eb-99c4-d71cc4c1ff54.png)

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by MateStrysewske** [comment]
@carolinverset You're right, they've been missing from the release notes frequently. I've added the new feature configurations to the 1.59.0 release notes, and we'll make sure to integrate them in the future.

**Comment by carolinverset** [comment]
@MateStrysewske Super !! Thank you very much !!
