### ISSUE TITLE
Incompatibilities in the Case import template between version 1.56 and newer versions of Sormas

### ISSUE THREAD

**Issue by aponcon-atolcd** [hzi-braunschweig/SORMAS-Project#5328]
### Bug Description
The CSV import Case feature had 2 properties that are no longer available:  `reportingType` and `Person.generalPractitionerDetails`. Sormas won't fail when trying to import them but will just ignore them.

### Steps to Reproduce
1. Create a CSV file to import Cases compatible with version 1.56
2. The CSV import file should have a Case with the property `reportingType` and a Person with `Person.generalPractitionerDetails`
3. Try to import it into Sormas with Import Case Feature
4. The import will be ok but these 2 columns will be ignored as they don't exist anymore in their respective entity.

### Expected Behavior
Importing these 2 properties was working before. We need to ensure to make them available either by ensuring a backward compatibility if possible. Or at least we should provide another mean to import them.

### System Details
* SORMAS version: Tested on a version 1.60, but the issue appeared starting from 1.57 for the `reportingType` and from 1.58 for the `Person.generalPractitionerDetails`
* Server URL: Tested on https://test.sormas.netzlink.com/sormas-ui/#!cases/
* User Role: Admin, National User

### Additional Information

These properties were moved to new entity types since these features:

- https://github.com/hzi-braunschweig/SORMAS-Project/issues/2744
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/4282

Currently these properties are now included into new entity types (that are not available in the import template):  

- `reportingType` is now included into `SurveillanceReport`
- `Person.generalPractitionerDetails` seems to be included into `PersonContactDetail`, renamed as `additionalInformation`

@bernardsilenou @carolinverset @ftavin

**Comment by carolinverset** [comment]
Thanks @aponcon-atolcd for the issue. 
This adaptation of the import file is essential for France. Without it, we cannot upgrade and will get stuck in version 1.57.
Also do you have an idea of ​​which version could embed this adjustment?
Thank you very much in advance for your reply

@ftavin @bernardsilenou @MateStrysewske @emond-fuseau

**Comment by bernardsilenou** [comment]
@carolinverset 
Thanks for this feedback. The team would have a look on it and comment soon.

**Comment by carolinverset** [comment]
@bernardsilenou 
to be more precise and after discussion with annick, we are essentially missing the values ​​that theese fields must take (which was previously in free text and whose content is now imposed). If we can get this information, we will be released
Thank you very much !!!

**Comment by bernardsilenou** [comment]
@carolinverset 
The team is still working on deciding the best way forward. We would send you an email tomorrow with the possible suggestions.
Sorry for the inconveniences.

**Comment by bernardsilenou** [comment]
@carolinverset @maxiheyner 
In case it happen that this need is no longer relevant, please indicate so that we can drop it from the planning; It is currently planned for sprint 104.

**Comment by JaquM** [comment]
@carolinverset is there any update? Is there still anything to do?

**Comment by carolinverset** [comment]
@JaquM Yes this issue can be closed. 
Thank you !
