### ISSUE TITLE
[SORMAS 2 SORMAS] Symptom journal registrations are shared

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5333]
### Bug Description
When a case or contact is shared via Sormas 2 Sormas, symptom journal registrations are shared as well and the person seemingly remains registered in the other instance, disregarding which external journal is used. This should not happen because the follow-up is done locally and could cause potential complications when shared between instances.

### Steps to Reproduce

1. Open or create a case/contact
2. Register the person in the external symptom journal (either PIA or Climedo)
3. Share the entity with another Sormas instance (either without or with handing over ownership)

### Expected Behavior
The registration in an external symptom journal should be ignored when sharing data via Sormas 2 Sormas.

### Screenshots
<img width="759" alt="diaryAndShare" src="https://user-images.githubusercontent.com/70317594/117197434-1c13a700-ade8-11eb-8328-76dab4630dae.PNG">
<img width="762" alt="diaryAndShare2" src="https://user-images.githubusercontent.com/70317594/117197436-1cac3d80-ade8-11eb-9d4e-a60e3ded2a34.PNG">

### System Details

* Device:
* SORMAS version: 1.59.1
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de, release-de.sormas.netzlink.com
* User Role: admin, national user

### Additional Information
@Candice-Louw @FredrikSchaeferVitagroup @markusmann-vg 
We should specify how external Journals should be handled with S2S. Things to consider:
- Should a case/contact be able to be shared with or without handing over the ownership while under external follow-up?
- If not, how do we prompt the user?
- Should external follow-up be somehow continued in the other system when handing over ownership? (likely very complicated)

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 @Candice-Louw Which instance is responsible for the follow up, is it always the one with ownership?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I think it should be yes, however, registrations in external symptom journals should also not be shared then because this could have strange side effects. When users are trying to share data and hand over ownership, we should inform them when such entities are still under follow-up. This will be a separate issue I believe but for this one it's mainly important to reduce side effects

**Comment by FredrikSchaeferVitagroup** [comment]
Proposal:

- When case/contact is shared without handing over ownership: transmit the symptom jounal status, but disable the external journal button on the receiving instance (be it a PIA or Climedo button). As stated in the comments, the health department with ownership should be responsible for the follow up.
- Generally only enable the external journal button on the instance with ownership (so when a case/contact is shared with ownership handed over, the button should be disabled on the sending instance)
- Don't allow sharing a contact/case with handing over ownership when the symptom journal status is set to REGISTERED or ACCEPTED (= when the person is enrolled in an external journal). Error message `The person is under external follow up.` 

For this approach, we need to be sure that it cancelling external follow up (= deleting the person in the external journal) updates the symptom journal status to DELETED. I know that for climedo this is the case. @ghdoergeloh Can you please confirm that for PIA (we need to be sure now)?

**Comment by FredrikSchaeferVitagroup** [comment]
What is a little ugly about this approach is that external follow up is person based. So when there are several contacts/cases for one person using an external journal, and only one of them is supposed to be shared while the external follow up shall continue, this becomes cumbersome. The user would need to unregister the person from the journal, share the one case/contact, and re-register the person in the journal afterwards.

But this is a rather unlikely edge case, or?

**Comment by JaquM** [comment]
@kwa20 
When the full handover takes place, the follow-up should also be handed over, that means terminated in old ownership Ga and option for new GA to start it again.
If a contact is handed over but other active contacts remain in the system, a note should appear asking if all contacts should be handed over. However, this only applies to contacts. 
Currently, contacts do not have to be reported, i.e. one is responsible and the other reports only in cases where only one is involved. If a person is a case, he or she should no longer be in the system as an active contact, but should be converted or the contact terminated. 
In the case of a complete case transfer, the follow-up should therefore be automatically terminated.
When transferring contacts, the user should be asked whether the other active contacts should also be transferred and if not, the follow-up will only be cancelled for the one transferred contact and continued for the person.

**Comment by FredrikSchaeferVitagroup** [comment]
@JaquM I think we have to clearly distinguish between follow up status and symptom journal status here. To me, it is not really clear when to set what status when trying to understand your comment.

What do you mean by "full handover": Handover of the ownership, or handover of all contacts/cases related to one person?

Maybe this topic is worth a small meting?

**Comment by FredrikSchaeferVitagroup** [comment]
After discussion with @JaquM and @kwa20 the apporach proposed [above](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5333#issuecomment-836253499) seems to feasible for now.

**Comment by georgeginguta** [comment]
Issue fixed, you are unable to move a case if it is registered to PIA or Climedo.
![image](https://user-images.githubusercontent.com/83694188/121309477-e5f7a480-c90a-11eb-94b2-ad431eda4bdd.png)
