### ISSUE TITLE
Sorting for Responsible Region, district and community columns throws an error.

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#5341]
### Bug Description

Error displayed when filter is applied on Responsible Region, district and community columns in detailed view.

### Steps to Reproduce

1. Login to Sormas as SurvSup or any other user
2. Click on the Case tab and select detailed view on the top right
3. Scroll to the right in the columns displayed and try to sort on the Responsible Region, district and community columns 

### Expected Behavior

Sort should work fine without any error displayed

### Screenshots

![Sort-resposnible region](https://user-images.githubusercontent.com/62763628/117286528-99333080-ae69-11eb-8b6d-878418b4f482.PNG)

### System Details

* Device:
* SORMAS version: 1.60.0-snapshot
* Android version/Browser:
* Server URL: test.sormas.netzlink.com
* User Role: any

### Additional Information

#3254

**Comment by MateStrysewske** [comment]
@raghupola-vg Since the issue that caused this is part of this sprint, please don't open a new issue, but comment on the existing one and reopen it.
