### ISSUE TITLE
Filter using SampleID would not return the desired result

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5344]
### Bug Description

Searching for a valid SampleID will not return any results.
### Steps to Reproduce

1. Go on the Samples page.
2. Enter or Copy & Paste a sample id from the list.
3. Click on Apply Filter.

### Expected Behavior
The result should be displayed in the list if the sample id exist

### Screenshots
![image](https://user-images.githubusercontent.com/53563072/117306994-d9ee7200-ae88-11eb-8a67-f4c2253b8859.png)
![image](https://user-images.githubusercontent.com/53563072/117307084-effc3280-ae88-11eb-886f-1a13c8ea9276.png)

### System Details

* Device: 
* SORMAS version: 1.60.0- snapshot
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/
* User Role: NatUser

**Comment by VGitVlad** [comment]
Validated ticket on Sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment
