### ISSUE TITLE
"An error has occurred"  message after initial login

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5348]
### Bug Description

After upgrading my local instance to 1.59.1, I get a warning message as shown in figure. No menu item is accessible apart from "About". Thus, not possible to create cases or any other entity

### Steps to Reproduce

1. put a new image: git pull
2. docker-compose down + up to get a new version of 1.59.1
3. log in with the admin or admin+national user role 
4. When logging in, do not reset the default passwords, click on remind me later.
4. Navigate through the menu items and all results to error messages

### Expected Behavior

Default local installation should work without error.
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/117343678-d1a43000-aea4-11eb-9b95-cae6ba4ece9d.png)

### System Details

* Device: Ubuntu 18.04 with SORMAS Docker setup
* SORMAS version: 1.59.1
* Android version/Browser:
* Server URL: Local instance
* User Role: Admin+ national user

**Comment by bernardsilenou** [comment]
@fhauptmann  Please can you also upgrade your local instance and comment if all works fine?

**Comment by MateStrysewske** [comment]
@bernardsilenou Sorry, there's nothing we can do about bug reports like these without error logs because we have no idea what might cause this problem

**Comment by bernardsilenou** [comment]
@MateStrysewske  This is a section of the server logs when the error occured, mainly at the end of the file.
Hope this helps
[logError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6441327/logError.txt)

**Comment by MateStrysewske** [comment]
"function unaccent(character varying) does not exist" - looks like you forgot to enable the unaccent extension (see release notes).
