### ISSUE TITLE
Import Katalon Studio Scripts to Selenium Framework

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5351]
### Scope

- [x] Investigate what was already done using Katalon in terms of User Flows 
- [x] Analyze and suggest next steps for integrating the same User Flows on to the new Automation Framework
- [x] Sync up with @raghupola-vg and get the desired information
- [x] Sync up with @BojteTamas and coordinate the next steps

### Possible Alternatives
Work on a Migration/transition Confluence Page to have everything as transparent as possible and get it approved

**Comment by BojteTamas** [comment]
After I take a look as well into the Katalon framework and talk with @rdutu-vg , we agreed that we can't use the selectors or steps from there and we will write from scratch everything, because taking step by step from Katalon will take more time.

**Comment by rdutu-vg** [comment]
Research done. 
Agreed with Tamas to use the scripts only as test steps and write all the code from scratch.
