### ISSUE TITLE
External Token is validating data from deleted records

### ISSUE THREAD

**Issue by cazacmarin** [hzi-braunschweig/SORMAS-Project#5353]
### Bug Description
External Token is validating data from deleted records

### Steps to Reproduce

1. Create a case and set External Token to `Test`
2. Delete this case
3. Create another case and set External Token to `Test`
4. `External Token` already exists message will appear
5. Same for other places where External Token is used

### Expected Behavior
If there is no case in the system with External Token = value, such message should not appear.

### Screenshots
![image](https://user-images.githubusercontent.com/6985315/117409731-32218480-af1a-11eb-8186-b731719e7ade.png)

### System Details
* SORMAS version:1.60.0
* User Role:admin

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.60.0-snapshot on test.sormas.netzlink.com environment
