### ISSUE TITLE
Tests are failing for external pull requests during actions/checkout

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5355]
### Bug Description

Tests can currently not be performed on external pull requests. They all fail during actions/checkout@v2 with the following error message: "Input required and not supplied: token"

### Expected Behavior

External pull requests should be automatically verified by GitHub CI.

**Comment by StefanKock** [comment]
I assume it has something to do with #3383, see https://github.com/hzi-braunschweig/SORMAS-Project/commit/125adc96fdade9e69911c29d498e1331d088ada0

**Comment by JonasCir** [comment]
@JonasCir bad style to have lowercase env vars :)
