### ISSUE TITLE
Using the filter to search for a SampleID does not return any results

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5356]
### Bug Description
Created a new case, added a sample for the case and a sample ID was generated. Went on the Samples page and searched for the SampleID.

### Steps to Reproduce

1. Created a new case.
2. Added a sample for the case.
3. Went on the sample page and used the filter search for the Sample.
4. Entered the first 6 characters to search. 
5. Entered the complete Sample ID
In both cases no results were returned.

### Expected Behavior
Searching by SampleID should return the sample.

### Screenshots
![image](https://user-images.githubusercontent.com/53563072/117432470-14ace480-af33-11eb-8f44-effa3bd8270d.png)
![image](https://user-images.githubusercontent.com/53563072/117432521-242c2d80-af33-11eb-81eb-5bac8c234cb0.png)

### System Details

* Device:
* SORMAS version:1.60.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL:https://test.sormas.netzlink.com/
* User Role: NatUser

**Comment by MateStrysewske** [comment]
Hey! You created the same issue 20 hours ago: #5344
