### ISSUE TITLE
[Case] Case Person tab - no email format validation

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#5361]
**Bug Description**
Contact Person email address field from Case Person tab has no format validation

**Steps to Reproduce**
1. Open Test.sormas.netzlink.com 
2. Open Cases
3. Create new case or edit any existing case
4. Go to Case Person tab
5. Input any random string into field
6. Save

**Expected behavior:**
User shouldn't be allowed to save using an invalid email format

**Actual behavior:**
User can input any data into mentioned email field and save

**Screenshots**
![email_field](https://user-images.githubusercontent.com/83643843/117448727-c3f3b680-af47-11eb-9be3-253973742f50.PNG)

**System Details**
Device:Windows
SORMAS Version: 1.60.0-SNAPSHOT
Android version/Browser: Chrome
Server URL:  https://test.sormas.netzlink.com/
User Role: NatUser

**Comment by DavidBaldsiefen** [comment]
Same for the contact person phone number

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as the Contact Person Phone Number validation has only been implemented for numbers. 
Special characters & too many spaces should also not be accepted as valid phone numbers
![image](https://user-images.githubusercontent.com/70562142/118045669-e4c16f00-b380-11eb-802b-f9d183396c51.png)

**Comment by DavidBaldsiefen** [comment]
@AndyBakcsy-she this applies to all phonenumber-validators, as currently phone numbers are only checked for the letters a-z. This could propably be improved, but I would suggest doing that in a seperate issue as there is some ground for additional disccussion (e.g. some special characters like `/` `+` `-` should stay allowed)

**Comment by AndyBakcsy-she** [comment]
Yes, @DavidBaldsiefen, you are right, I have rushed into opening the ticket as I did not think about all other places where Phone validation is needed.
