### ISSUE TITLE
contact>contact-to-case conversion> contact details on creation form get lost

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#5383]
### Bug Description
Contact details from creation from during converting a contact into a case get lost. True for email and phone number.

### Steps to Reproduce

1. convert a contact into case, document phone number and email on creation form
2.check for contact details in case person data --> none of both is displayed

### Expected Behavior
Documented contact details should appear at the case person contact information table. 

### Screenshots
<img width="779" alt="image" src="https://user-images.githubusercontent.com/76884029/117649009-4621ec00-b18f-11eb-9576-353e0b2e4ed4.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/76884029/117649078-5fc33380-b18f-11eb-9560-5e328d9bd9b1.png">

### System Details

* Device:
* SORMAS version: 1.58.3 and 1.59.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/
* User Role: admin

**Comment by AndyBakcsy-she** [comment]
Validted ticket on the latest version deployed on test environment
