### ISSUE TITLE
REST API ECONNRESET 

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#5419]
Hey guys,

since yesterday we have big problems with the REST API.

while calling our SORMAS instance (bund) via different POST and/or GET calls, often we get the followiong back:

- "Error: read ECONNRESET"
- 
trying to call the same request a few Minutes or seconds later, all is fine.

This happens since yesterday. all the weeks before we have no problems with it.
It is the same SORMAS Version (1.58.3).
I have tried to call Netzlink but the told me that netzlink not Supports API Rest questions/problems. 
But in my opinion that have to be a server issue because all the weeks before it was working with the same code.

I also tried it with POSTMAN and gets the same issues.

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF I agree that this sounds like a server issue. Maybe someone else from the team has experienced something similar in the past - thinking about @MartinWahnschaffe, @HolgerReiseVSys or @StefanKock here.

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske do you have some news for me?

I found out that is first call gets this error. 
Every next call works fine, but after a few minutes i also get this error. The following requests working fine, ... and so on.

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF Unfortunately not - I've forwarded the request to Netzlink and the HZI again. Have you opened a ticket in their ticket system? If not, please do so, and please forward the ticket number to me so that I can pass it to them.

**Comment by herrling-LRA-KYF** [comment]
I opended a ticket to Netzlink and HZI last wednesday.

From Netzlink i got no response until today. (2021448047 )
HZI Tickt was closed on friday without any response ((SORMASDE-8735) ECONNRESET REST-API)

**Comment by herrling-LRA-KYF** [comment]
HZI closed the ticket because it is an issue for Netzlink and forwarded this to the Netzlink-Team. They told me I should write a mail to vitagroup  if Netzlink not response me.

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF Thanks! I'm gonna forward this information to them and push them to respond.

**Comment by hzi-old** [comment]
Hi @herrling-LRA-KYF can you please give us more details, what you are trying to do here. Please give us some source code or specific commands that you execute to further diagnose this issue.

**Comment by herrling-LRA-KYF** [comment]
@hzi-old  it was on every request. for example: (tried with backand written in NestJS but also with POSTMAN)

GET --> https://landratsamt-kyffhaeuserkreis.sormas.bund.de/sormas-rest/pathogentests/uuids

* with Basic Authorization

the first response was: "read ECONNRESET" after that, all request were working fine exactly for 1 minute. After one minute i got the same error.

Today someone from the HZI was calling me for clarify the situation and told me that it is not possible to get temporary credentials for some"test Instance" and told me to catch a timestamp and send this to Netzlink and also to "dr. Hoffmann"

I few minute before i also called Netzlink and they told me that sounds like a problem from "BUND" and someone of these guys sets the "wrong check" . And he cant help me for this because its an REST API issue and Netzlink not supports this.

Curiously ... I tried to get the timestamp after all this calls and .... it was working, there was no error anymore (after one week).

So guys, I guess we can close these issue. Thx for al your help.
