### ISSUE TITLE
RESTApi Sample

### ISSUE THREAD

**Issue by fleckandreas** [hzi-braunschweig/SORMAS-Project#5425]
Hey, i want to create a new sample for an existing contact via RestAPI with following syntax, but just get an "error". Can anyone help me with the correct json-syntax, thx

`curl -u restapiuser:*** --location --request POST 'https://mysormasdomain/sormas-rest/samples/push' \
--header 'Content-Type: application/json' \
--data-raw '[
{ 
"uuid": "T3CMLA-Y6LMLG-466Z26-52ADCPSS", -- Ist neu
"associatedContact": {
"uuid": "T3CMLA-6QNMGK-VTGOU7-52ADCPBI" -- Existiert
},
"labSampleID": "",
"sampleDateTime": 1620697500000, 
"sampleMaterial": "NASAL_SWAB",
"samplePurpose": "EXTERNAL",
"lab": {
"uuid": "SORMAS-CONSTID-OTHERS-FACILITY",
"caption": "Andere Einrichtung",
"externalId": null
},
"labDetails": "TESTGEG",
"shipmentDetails": "",
"comment": "ddddd",
"shipped": false,
"received": false,
"pathogenTestResult": "PENDING",
"pathogenTestingRequested": false,
"additionalTestingRequested": false,
"requestedPathogenTests": [],
"requestedAdditionalTests": [],
"samplingReason": "CONTACT_TO_CASE",
"ownershipHandedOver": false
}
]'`

**Comment by MateStrysewske** [comment]
@fleckandreas Hey! As you can see when you paste that JSON in an online validator (e.g. https://jsonformatter.curiousconcept.com/#), it's not valid. I suspect the reasons are the two comments that you added to the actual JSON. They prevent it from being parsed correctly.

**Comment by fleckandreas** [comment]
Hi, thx, but i wrote the two comments only here and not in the program

**Comment by MateStrysewske** [comment]
@fleckandreas Ah okay. Checked it again, you're missing two required properties: reportDateTime and reportingUser, so e.g. like this:

```
"reportDateTime": 1620697500000,
"reportingUser":{
    "uuid": "Q3QJUG-MJDED5-2DZCZ3-WVKYSJIQ"
}
```

**Comment by fleckandreas** [comment]
Great - works fine! Where can i find the required properties for push-requests?

**Comment by MateStrysewske** [comment]
@fleckandreas Have a look at the main readme, there's a short explanation about how to retrieve and view the ReST API documentation.
