### ISSUE TITLE
Changing Infrastructure Data- Transfer the case to a facility in another district.

### ISSUE THREAD

**Issue by felix84-ed** [hzi-braunschweig/SORMAS-Project#5435]
### Bug Description
If you change the place of stay (e.g. transferred to another hospital), you will be asked to change the infrastructure data of the case and then the "old" hospital is published in the list of previous hospitalizations.
But this does not happen if the new hospital is in another district. 
You have to do a little workaround: Place of Stay -> Home -> Changing the Infrastructure Data -> Place of Stay -> new Hospital.

### Steps to Reproduce

1. Place of Stay is already a facility.
2. Change the Place of Stay to a hospital (Facility) in another district.

### Expected Behavior

After transferring a case to a new facility in another district, you should confirm the changing.
### System Details

* Device:
* SORMAS version: 1.58.3
* Android version/Browser: 
* Server URL:
* User Role: Admin

**Comment by MateStrysewske** [comment]
@felix84-ed I can't reproduce this on my development system, I get the request to decide whether I've done a case transfer or only edited the data as I should, and the previous hospitalization is correctly created. Could you attach some screenshots that depict your process?

**Comment by felix84-ed** [comment]
strange, now it works.
So, we can close the "issue"
