### ISSUE TITLE
Event Participants Filters not displayed anymore

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5445]
### Steps to Reproduce
1. Open the Events tab
2. Select one Event or create a new event
3. Go to Event Participants 
4. Check the Filters section

### Expected Behavior
Previous Filters on the Event Participant Page should be displayed

### Screenshots
How it used to look:
![image](https://user-images.githubusercontent.com/70562142/118299795-dfcbff00-b4e9-11eb-9c8b-26ed92187cb2.png)

and 
How it looks now:

![image](https://user-images.githubusercontent.com/70562142/118299830-ee1a1b00-b4e9-11eb-8acd-37f7b00b6a11.png)

### System Details

* Device: Windows
* SORMAS version: 1.60.0-snapshot
* Android version/Browser: Chrome/Brave
* Server URL: localenvironment + version 1.59.2 (test1402.sormas-oegd.de
* User Role: NatUser

**Comment by sergiupacurariu** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/pull/5392 - this is the PR that generated the bug

**Comment by RazvanHodisan** [comment]
Valdiated on local 1.60.0-SNAPSHOT
