### ISSUE TITLE
Case directory becomes unusable after disabling a feature configuration

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5446]
Steps to Reproduce
1. Open PgAdmin and connect to DB
2. Disable from featureconfiguration table the View_Tab_Cases_Therapy field
3. Reload the server on the local environment
4. Go to Cases

Expected Behavior
Cases Directory should load without any problems

Actual Behavior:
Please see the attached log file
Cases directory is not displaying any more cases.
### Screenshots
![image](https://user-images.githubusercontent.com/70562142/118310125-db5a1300-b4f6-11eb-98b9-4917588d162e.png)

### System Details

* Device: windows
* SORMAS version: 1.60.0-snapshot
* Android version/Browser: chrome
* Server URL: localhost
* User Role: NatUser

### Additional Information
[serverlog .txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6480456/serverlog.txt)
This ticket might be related to #4733

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she Unrelated to the feature configurations. According to the logs, you have a customizableenumvalue in your database which contains an illegal list of diseases. Did you manually add any entries to that table on your local system?

**Comment by AndyBakcsy-she** [comment]
Closing ticket because the issue was produced by an old customizable enum value.
