### ISSUE TITLE
Validation for health facility occurs after selecting the place of stay at home

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5447]
### Bug Description
When creating a new case by default the place of stay filter is for facility. After completing the required fields and switching from Facility to Home the following validation error message occurs.

### Steps to Reproduce

1. Create a new case
2. Complete the required fields.
3. Switch  from facility to home
4. Press save

### Expected Behavior
Since I don't need to add the health facility I should not recive this error when adding a new case. 
### Screenshots
![image](https://user-images.githubusercontent.com/53563072/118436699-ed4fd780-b6e9-11eb-9e57-de52d7d4c00b.png)

### System Details

* Device:
* SORMAS version:1.60.0-SNAPSHOT
* Android version/Browser:
* Server URL:https://test.sormas.netzlink.com/sormas-ui/#!about
* User Role:NatUser

**Comment by DavidBaldsiefen** [comment]
@RazvanHodisan I cannot reproduce this right now. Could you specify the steps taken? Did you first select facility, fill out the facilityfields, and then switch back to home? Or did you ignore these fields before selecting home?

**Comment by RazvanHodisan** [comment]
@DavidBaldsiefen I'm no longer able to reproduce this either with the steps mentioned above.

**Comment by VitaliHZI** [comment]
The bug is not fixed see here https://github.com/hzi-braunschweig/SORMAS-Project/issues/5736. please fix it ;)
