### ISSUE TITLE
Allow the admin surveillance supervisor to delete and archive events

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5450]
### Situation Description

To date, there is an “Admin Suveillance Supervisor” profile which gives greater rights than those of the supervisory supervisor. It would be desirable for the user of this profile to be able to archive or delete events, which is not the case today.

### Feature Description
Add a role to the supervisor supervisor administrator; that of deleting and archiving events. 

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by bernardsilenou** [comment]
@MateStrysewske  
Dev France plan to work on this in this sprint

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT on test.sormas.netzlink.com env.
