### ISSUE TITLE
New REST API endpoint to query person data by external ID [2]

### ISSUE THREAD

**Issue by stefan-ho** [hzi-braunschweig/SORMAS-Project#5453]
### Situation Description
When data is transferred from SORMAS to SurvNet or other IfSG applications via the SurvNet Webservice only pseudonymized information is transferred. However, health departments need the personal information of the data to be available in the IfSG application.

To give the manufacturers of IfSG applications an option to retrieve regarding personal information from SORMAS based on a shared unique ID, the REST API should provide the data by the externalId which is the shared identifier in both systems.

### Feature Description
A new REST API endpoint for PERSONS should be provided that can be queried by the externalId of a person.

### Development Specifications
* Add a `getByExternalIds` endpoint to PersonResource that takes a list of Strings
* Add a `getByExternalIds` method to PersonFacade that works similar to the `getByUuids` method, but filters by external Ids instead

**Comment by Alexandru-Pirvu** [comment]
Added a new endpoint: **POST** _/persons/query/byExternalIds_. It runs similar to the _/persons/query_, but the given list of uuids in the request body is considered as a list of _externalIds_.

For validation, make a POST request to the new endpoint. The request body should contain a list of externalIds, e.g.:
`[
    "UXKEA3-Q36HWK-C263KM-75IOSPBA", "SMC2U5-GGCI4T-ZZEEKV-JRGCCEZA"
]`.
The response should contain a list of entities whose external ids match the ones from the request body.
