### ISSUE TITLE
Contact directory - updates for some fields

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5455]
Issue 1: 
 Contact directory, detailed view,  
 Type of Contact -if multiple pick the closest contact proximity" should just be "Type of Contact" in the contact grid column

Issue 2:
Move the positioning of "Relationship with Case" next to "Type of Contact"  on the Contact directory field

### System Details

* Device:
* SORMAS version: 1.60.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by DavidBaldsiefen** [comment]
Review findings I will also handle in this ticket: disable sorting for `Vaccination` and `RelationToCase` Columns

**Comment by VGitVlad** [comment]
Validated ticket on Sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment
