### ISSUE TITLE
Allow users to select the used delimiter when importing files [1]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5459]
### Feature Description

Up to a certain point in the past, importers failed when the user tried to import a file with CSV separators that didn't match the separator defined in the sormas.properties file. The error was something like "invalid column column1;column2;column3;...".

### Problem Description

Right now, there is no initial error when trying to import such a file; instead, e.g. for the infrastructure import, the imported RegionDto will just be empty except for the UUID, and the system will try to save that empty region (which then throws an exception).

### Proposed Change

Add a dropdown to every import popup that allows users to select the delimiter they want to use for the import file. Default should be the csv separator that is defined in the properties file. Values should at least include:
* ,
* ;
* tab

**Comment by ChristopherRiedel** [comment]
Error when no delimiter is chosen; Error while importing default infrastructure

**Comment by vidi42** [comment]
For the default option include in brackets the caption for the separator: ex: Default (Semicolon)

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com
