### ISSUE TITLE
Lab messages processing failure

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#5461]
### Bug Description

Lab messages cannot be processed if country locale is not DE. 
### Steps to Reproduce

1. Activate lab messages future 
2. Try to process lab messages with country.locale different from de-DE

### Expected Behavior

Lab messages processing should be possible once the lab messages future is activated regardless of country locale, since this can change in the future and others might also use it.
### Screenshots

![image](https://user-images.githubusercontent.com/83635257/118626581-47749980-b7cb-11eb-958f-71a654712b58.png)

### System Details

* Device: Windows
* SORMAS version:
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: NatUser

**Comment by MateStrysewske** [comment]
Actually this is a problem on all servers. Right now I can't even save persons because I get a NullPointerException. This is very problematic and needs to be fixed in this sprint.

**Comment by MateStrysewske** [comment]
e.g. PersonController contains this line: `ExternalJournalSyncResponseDto responseDto = FacadeProvider.getExternalJournalFacade().notifyExternalJournal(existingPerson);` and then accesses the responseDto without a null check. It will be null if the external journal service is not set up though.

**Comment by MateStrysewske** [comment]
Also there are notifications displayed even if the service is not set up; the whole code behaves as if the external journal is always used.

**Comment by MateStrysewske** [comment]
@Alexandru-Pirvu I think the responsible code has been introduced by you

**Comment by MateStrysewske** [comment]
I'll move my findings to the responsible issue: #5233
