### ISSUE TITLE
Indexes by `deleted` flag on all containing entities should be applied

### ISSUE THREAD

**Issue by cazacmarin** [hzi-braunschweig/SORMAS-Project#5465]
### Situation Description
Indexing is required for table columns which is often use in the system. 

### Feature Description
After performing task `#4892-Identify performance problems in deleting multiple samples` which was approved by Barna, he recommend to add the indexing for all entities which are containing `deleted` flag. As system is loading only `non-deleted` records, this index will help a lot.

**Comment by cazacmarin** [comment]
In order to test this case if indexes has been created, in PGADMIN next tables should be checked:
Index name: `idx_cases_deleted` - table name: `cases`
Index name: `idx_contact_deleted` - table name: `contact`
Index name: `idx_events_deleted` - table name: `events`
Index name: `idx_samples_deleted` - table name: `samples`
Index name: `idx_pathogentest_deleted` - table name: `pathogentest`
Index name: `idx_campaigns_deleted` - table name: `campaigns`
Index name: `idx_eventparticipant_deleted` - table name: `eventparticipant`
Index name: `idx_documents_deleted` - table name: `documents`
like in the next image:
![image](https://user-images.githubusercontent.com/6985315/119253588-9c912080-bbba-11eb-98b9-a94fd453a7e4.png)

**Comment by AndyBakcsy-she** [comment]
Validated that the indexes are available in the last version of sormas deployed locally. 1.61.0-snapshot
