### ISSUE TITLE
Don't take over the pathogen test result during sample creation if the tested disease is different than the case/contact/event disease

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5466]
### Bug Description

When creating a new sample and creating a pathogen test at the same time, the pathogen test result will be taken over as the final laboratory result of the sample no matter what. This is not supposed to happen when the tested disease of the pathogen test differs from the disease of the case/contact/event that the sample is associated with.

### Steps to Reproduce

1. Create a case with disease A
2. Create a new sample for that case, create a pathogen test at the same time, set its result to positive and its tested disease to disease B

### Expected Behavior

The final laboratory result of the sample should NOT be updated when the disease of the pathogen test differs from the disease of the case/contact/event.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by DavidBaldsiefen** [comment]
Currently, when you add a pathogentest-result of disease B to a sample _after_ the sample was already created, a popup will appear asking the user to create a new case. I think this should also be used here

**Comment by VGitVlad** [comment]
Validated ticket on Sormas version 1.60.0-snapshot on test.sormas.netzlink.com environment
