### ISSUE TITLE
Add JsonIgnore annotation to ContactReferenceDto.getCaptionAlwaysWithUuid

### ISSUE THREAD

**Issue by Sphinx31** [hzi-braunschweig/SORMAS-Project#5469]
Hello,
as my ongoing work on an ReST-API automatisation script , i discovered some more "shortCaption" problems. If you remember the first one (https://github.com/hzi-braunschweig/SORMAS-Project/issues/5181).

What i do:
I have a list of uuids from cases and contacts via an excel-list. Foreach entry (uuid) i setup an array and "ask" the api to give me these cases and later the contacts.
This works fine so far.
I manipulate the data i recived as follow: i just enter a specific Text to the "additionalDetails" fields for the specific uuids i got.

Now my json is ready for upload, i send the server the manipulated json.
I expect now, that the server will "take" **his** own data without problems back but this is not allways the case.

I discovered several field problems that prevents the server from taking back his data.
These fields are:
"shortCaption" fields (on three nodes, i will give a list what i discovered so far below)
"captionAlwaysWithUuid" fields

The nodes i found the "shortCaption" fields:
1. -> "reportingUser"."shortCaption"
2. -> "classificationUser"."shortCaption"
3. -> "epiData"."exposures"[0]."reportingUser"."shortCaption"
4. -> "followUpStatusChangeUser"."shortCaption" (**not in the json below**)

5. -> "epiData"."exposures"[0]."contactToCase"."captionAlwaysWithUuid"

we are running the Sormas-Version 1.59.1 and today evening an update to 1.59.2 is planned

### Bug Description
Error or Bad Request recived when sending the json back to the server.

### Steps to Reproduce
Send this (prepared) dataset to the serverendpoint -> /sormas-rest/cases/push  <-. This are fakedata. In this json i wrote for your search purposes this text: "the shortcaption entry here caused a problem"

-------- json beginn ---------
[
    {
        "creationDate": 1620131538179,
        "changeDate": 1621344976096,
        "uuid": "XXYYZZ-MF7K5S-N7F7AB-UM4DSBAI",
        "pseudonymized": false,
        "disease": "CORONAVIRUS",
        "diseaseVariant": {
            "uuid": "N7F7AB-ZVYVHL-N7F7AB-CRYFDT5Y",
            "caption": "B.1.1.7 - 501Y.V1"
        },
        "person": {
            "uuid": "N7F7AB-N7F7AB-N7F7AB-XXXNCIIQ",
            "caption": "Maria Musterfrau",
            "firstName": "Maria",
            "lastName": "Musterfrau"
        },
        "reportDate": 1620079200000,
        "reportingUser": {
            "uuid": "UABXXX-TLHXXX-CXZXXX-XXXNCIIQ",
            "caption": "Max Mustermann - Importierender Benutzer, Nationale*r Benutzer*in, Nationale*r Arzt/Ärztin",
            "firstName": "Max",
            "lastName": "Mustermann",
            "shortCaption": "Max Mustermann - the shortcaption entry here caused a problem"
        },
        "caseClassification": "CONFIRMED",
        "caseIdentificationSource": "OTHER",
        "classificationUser": {
            "uuid": "UABXXX-TLHXXX-CXZXXX-XXXNCIIQ",
            "caption": "Max Mustermann - Importierender Benutzer, Nationale*r Benutzer*in, Nationale*r Arzt/Ärztin",
            "firstName": "Max",
            "lastName": "Mustermann",
            "shortCaption": "Max Mustermann - the shortcaption entry here caused a problem"
        },
        "classificationDate": 1620131570169,
        "laboratoryDiagnosticConfirmation": "YES",
        "investigationStatus": "DONE",
        "investigatedDate": 1619992800000,
        "outcome": "RECOVERED",
        "outcomeDate": 1621288800000,
        "region": {
            "uuid": "V5AW3H-PWQHYV-LBKIZU-AU42CBIU",
            "caption": "Nordrhein-Westfalen",
            "externalId": "13000005"
        },
        "district": {
            "uuid": "QB43V4-JKW255-GNA5CL-POFNKO2M",
            "caption": "LK Gütersloh",
            "externalId": "11005754"
        },
        "community": {
            "uuid": "TU5GBM-JWOHCU-4OFORM-OUHCCGAY",
            "caption": "Harsewinkel",
            "externalId": null
        },
        "healthFacility": {
            "uuid": "SORMAS-CONSTID-ISNONE-FACILITY",
            "caption": "Zuhause oder anderer Ort",
            "externalId": null
        },
        "vaccination": "UNVACCINATED",
        "hospitalization": {
            "creationDate": 1620131538183,
            "changeDate": 1621344976097,
            "uuid": "WHF6CY-6BICA6-5KQV7Y-K3MUKFKI",
            "previousHospitalizations": []
        },
        "symptoms": {
            "creationDate": 1620131538186,
            "changeDate": 1621333257493,
            "uuid": "UGMRZD-VQMWGA-WMS3YM-KIJZCLCA",
            "pseudonymized": false,
            "chillsSweats": "YES",
            "cough": "YES",
            "diarrhea": "NO",
            "difficultyBreathing": "NO",
            "fever": "NO",
            "headache": "YES",
            "musclePain": "YES",
            "nausea": "NO",
            "onsetDate": 1619820000000,
            "onsetSymptom": "Kopfschmerzen",
            "otherNonHemorrhagicSymptoms": "NO",
            "rapidBreathing": "NO",
            "runnyNose": "YES",
            "soreThroat": "NO",
            "symptomatic": true,
            "symptomsComments": "neg. Befund liegt vor",
            "acuteRespiratoryDistressSyndrome": "NO",
            "pneumoniaClinicalOrRadiologic": "NO",
            "lossOfTaste": "NO",
            "lossOfSmell": "NO",
            "respiratoryDiseaseVentilation": "NO",
            "feelingIll": "YES",
            "fastHeartRate": "NO",
            "oxygenSaturationLower94": "NO",
            "shivering": "NO"
        },
        "epiData": {
            "creationDate": 1619857069301,
            "changeDate": 1621344976097,
            "uuid": "RSOPQX-BGOP46-6UA7NG-OVWAKEEM",
            "pseudonymized": false,
            "exposureDetailsKnown": "UNKNOWN",
            "activityAsCaseDetailsKnown": "NO",
            "contactWithSourceCaseKnown": "YES",
            "highTransmissionRiskArea": "NO",
            "largeOutbreaksArea": "NO",
            "exposures": [
                
                {
                    "creationDate":  1619607732801,
                    "changeDate":  1619607732802,
                    "uuid":  "QB4HUH-42LHPS-TIBFFA-DC6BSGFA",
                    "pseudonymized":  false,
                    "reportingUser":  {
                                          "uuid":  "QKP5SH-4JS2MP-4DGQ23-I7T2SEEU",
                                          "caption":  "Fritz Fuchs - Überwachungsleitung, Importierender Benutzer, Arzt/Ärztin",
                                          "firstName":  "Fritz",
                                          "lastName":  "Fuchs",
                                          "captionAlwaysWithUuid": "the shortcaption entry here caused a problem"
                                      },
                    "probableInfectionEnvironment":  false,
                    "startDate":  1618956000000,
                    "endDate":  1618956000000,
                    "description":  "Keks war zu Besuch",
                    "exposureType":  "OTHER",
                    "exposureTypeDetails":  "Familie",
                    "location":  {
                                     "creationDate":  1619607732802,
                                     "changeDate":  1619607732802,
                                     "uuid":  "SNJC6F-CJF67O-LINROE-V6ZESLZU",
                                     "pseudonymized":  false,
                                     "region":  {
                                                    "uuid":  "V5AW3H-PWQHYV-LBKIZU-AU42CBIU",
                                                    "caption":  "Nordrhein-Westfalen",
                                                    "externalId":  "13000005"
                                                }
                                 }
                },
                {
                    "creationDate":  1619607732799,
                    "changeDate":  1619607732800,
                    "uuid":  "R6GDLY-VAA2MW-XQ5DKM-YGGKKEHA",
                    "pseudonymized":  false,
                    "reportingUser":  {
                                          "uuid":  "QKP5SH-4JS2MP-4DGQ23-I7T2SEEU",
                                          "caption":  "Fritz Fuchs - Überwachungsleitung, Importierender Benutzer, Arzt/Ärztin",
                                          "firstName":  "Fritz",
                                          "lastName":  "Fuchs",
                                          "shortCaption":  "Fritz Fuchs"
                                      },
                    "probableInfectionEnvironment":  false,
                    "startDate":  1618783200000,
                    "endDate":  1618783200000,
                    "description":  "Hundesalon Welpenschön",
                    "exposureType":  "OTHER",
                    "exposureTypeDetails":  "Freizeit",
                    "location":  {
                                     "creationDate":  1619607732800,
                                     "changeDate":  1619607732800,
                                     "uuid":  "QABMX7-RWJVH7-GBPD2Y-KHTKCB4Y",
                                     "pseudonymized":  false,
                                     "region":  {
                                                    "uuid":  "V5AW3H-PWQHYV-LBKIZU-AU42CBIU",
                                                    "caption":  "Nordrhein-Westfalen",
                                                    "externalId":  "13000005"
                                                }
                                 },
                                 "indoors":  "YES",
                                 "wearingMask":  "YES",
                                 "wearingPpe":  "YES",
                                 "contactToCase":  {
                                                    "uuid":  "WXNGXW-EXH6XB-XZL6ET-5XBEKL3Q",
                                                    "caption":  "Petrus Rechte to case Frida Rechte",
                                                    "contactName":  {
                                                                        "firstName":  "Petrus",
                                                                        "lastName":  "Rechte"
                                                                    },
                                                    "caseName":  {
                                                                        "firstName":  "Frida",
                                                                        "lastName":  "Rechte"
                                                                        },
                                                    "captionAlwaysWithUuid":  "Petrus Rechte to case Frida Rechte (YYYXXXZZZ)"
                                                                                  }
                                                            }
                
            ],
            "activitiesAsCase": []
        },
        "therapy": {
            "creationDate": 1620131538187,
            "changeDate": 1620131538187,
            "uuid": "V7CSPF-GH4S4H-4WXAOZ-EEIF2O6Y"
        },
        "clinicalCourse": {
            "creationDate": 1620131538182,
            "changeDate": 1620131538182,
            "uuid": "VNDWSH-ZAHXLY-PNQUW7-5YCTCBBI",
            "healthConditions": {
                "creationDate": 1619857069301,
                "changeDate": 1620132566183,
                "uuid": "VS6YDQ-ZK6XBG-LX4MNJ-JLATKFP4",
                "pseudonymized": false,
                "diabetes": "NO",
                "chronicLiverDisease": "NO",
                "malignancyChemotherapy": "NO",
                "chronicPulmonaryDisease": "YES",
                "chronicKidneyDisease": "NO",
                "chronicNeurologicCondition": "NO",
                "cardiovascularDiseaseIncludingHypertension": "NO",
                "immunodeficiencyIncludingHiv": "NO",
                "otherConditions": "Asthma bronchiale"
            }
        },
        "maternalHistory": {
            "creationDate": 1620131538184,
            "changeDate": 1620131538184,
            "uuid": "QF4PUZ-Q53N3Z-VSRUHU-S4O2CHNE",
            "pseudonymized": false
        },
        "portHealthInfo": {
            "creationDate": 1620131538185,
            "changeDate": 1620131538185,
            "uuid": "UA56TB-6QFCTS-4HR4EP-QY4JSPTI"
        },
        "caseOrigin": "IN_COUNTRY",
        "additionalDetails": "Dies ist ein Testeintrag",
        "sharedToCountry": false,
        "nosocomialOutbreak": false,
        "quarantine": "HOME",
        "quarantineFrom": 1620079200000,
        "quarantineTo": 1621202400000,
        "quarantineOrderedVerbally": true,
        "quarantineOrderedOfficialDocument": true,
        "quarantineOrderedVerballyDate": 1620079200000,
        "quarantineOrderedOfficialDocumentDate": 1621288800000,
        "quarantineHomePossible": "YES",
        "quarantineHomeSupplyEnsured": "YES",
        "quarantineExtended": false,
        "quarantineReduced": true,
        "quarantineOfficialOrderSent": false,
        "followUpStatus": "CANCELED",
        "followUpComment": "Indexfall = XY3QPA\nEntlassung",
        "followUpUntil": 1621029600000,
        "overwriteFollowUpUntil": false,
        "ownershipHandedOver": false,
        "wasInQuarantineBeforeIsolation": "YES",
        "reportingDistrict": {
            "uuid": "QB43V4-JKW255-GNA5CL-POFNKO2M",
            "caption": "LK Gütersloh",
            "externalId": "11005754"
        },
        "notACaseReasonNegativeTest": false,
        "notACaseReasonPhysicianInformation": false,
        "notACaseReasonDifferentPathogen": false,
        "notACaseReasonOther": false,
        "followUpStatusChangeDate": 1621288800000,
        "followUpStatusChangeUser": {
            "uuid": "ULWJY3-ULWJY3-KJZPMC-QRZLSFHY",
            "caption": "Daniel Holger Graf - Importierender Benutzer, Arzt/Ärztin, Kontaktleitung, Überwachungsleitung",
            "firstName": "Daniel Holger",
            "lastName": "Graf",
            "shortCaption": "Daniel Holger Graf - the shortcaption entry here caused a problem"
        }
    }
]

-------- json end ---------

**Comment by MateStrysewske** [comment]
@Sphinx31 Hey! For shortCaption, this has already been fixed for the upcoming version 1.60.0. We'll also fix it for getCaptionAlwaysWithUuid.
