### ISSUE TITLE
More possibilities to "log" information

### ISSUE THREAD

**Issue by Sphinx31** [hzi-braunschweig/SORMAS-Project#5472]
### Situation Description
we use the "additionalDetails" field in a Case or Contact to "log" some specific information such as when we send the quarantine data to the regulatory agency and conversional details frome phone calls.
Some of the cases or contacts are filled with more or less information but the problem is the limitation of 4096 characters to this field.
It would be great to have an option to extend or an new field for this type of information.

**Comment by MateStrysewske** [comment]
Will be handled in #3953
