### ISSUE TITLE
Client -> Server Connection loss when some special character combinations are written in any textfield

### ISSUE THREAD

**Issue by Sphinx31** [hzi-braunschweig/SORMAS-Project#5475]
### Bug Description
In some rare cases we want with first attempt change some text in the additionalDetails fields via a ReST-API request. As this request was recieved with an Error status, we did the research and come along that a case was filled with data ( via an import we estimate ) that are not possible, if this case was entered via UI in the webform.

The case fields "isolationdetails" (only show up when the "Isolation"-Dropdown is set to "Sonstiges" were data present. At the same time there was data present for the Isolationdates.
If you try to click through this you determine thats not possible to set both datas.

A Second problem we find was, that in these Fields are text: some example text "," another part of "," the same example text
Notice the combination ","
In the ReST-API get request, we could see that these "," are escaped like this \",\"
So far so good but in the UI it was not possible to save such an dataset until we deleted the "," combination
(also this problem came up in the any text field someone can wrtie to) 

### Steps to Reproduce

1. Navigate to a case or contact
2. write MORE as one combination of "," to any textfield a user can write to

### System Details
* SORMAS version: 1.59.1

**Comment by MateStrysewske** [comment]
@Sphinx31 I don't fully understand your problem. Can you give me a concrete example value that I could put into one of the additionalDetails fields in order to reproduce the problem?

**Comment by StefanKock** [comment]
No feedback received
