### ISSUE TITLE
Do not prepare messages if they wont be sent [2]

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#5477]
### Problem Description

Current design of the message service will not send a message based on the feature type of the message subject, this is wrong as queries and logic is executed in cases when nothing is done with that information, thus impacting performance.
### Proposed Change

Move the logic the decides not to send the message based on the MessageSubject relatedFeatureType to before the message content is queried and prepared. (see de.symeda.sormas.backend.common.messaging.MessageService)

**Comment by StefanKock** [comment]
Proposal from sprint planning: Hand over a function/lambda instead of raw parameters with precompiled message, basically replacing the current calls of sendMessage invocations.
