### ISSUE TITLE
[Angular][DevOps] Translation script [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5478]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

1. Create a script (NodeJS) which would concatenate the existing translation files (1 file per language) and convert it into a .JSON file
2. Properties files would be pulled from the development branch
3. We need this for local development

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by horia-ardelean-vg** [comment]
**Work done:**
* created a new NodeJs script that parses the translations from Sormas-Projects
* added a new docker image definition that pulls the translation property files from the Sormas-Project repository and runs the translation script mentioned above
* added some documentation that explains how the import process works and how to run it locally
* pull request is [here](https://github.com/hzi-braunschweig/SORMAS-Angular/pull/120)

**Comment by danielrus** [comment]
Script is working and translation files are generate correctly. But the default 'en' file is empty. We would need it to be generated as well, if possible.

**Comment by horia-ardelean-vg** [comment]
**Work done:**
* changed the current behavior to pick up all the properties files that do not have a language suffix and set them as property files for English
* pull request is [here](https://github.com/hzi-braunschweig/SORMAS-Angular/pull/132)
