### ISSUE TITLE
[Angular] Refactor translations [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5480]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

1. Go through everything we have until now and check / change the keys or add new keys
2. Investigate if translations are provided for dynamic data like: Classification status: "not_confirmed". (done, pending, approved, etc).

NOTE: :" CaseClassification.CONFIRMED_NO_SYMPTOMS = Confirmed case with no symptoms " (CaseClassification = key & CONFIRMED_NO_SYMPTOMS = Value)

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done, everything looks good!
