### ISSUE TITLE
At contact import, disease is not validated. A wrong disease value is inserted for that contact.

### ISSUE THREAD

**Issue by cazacmarin** [hzi-braunschweig/SORMAS-Project#5491]
### Bug Description
At contact import, disease is not validated with diseases present in the application.

### Steps to Reproduce
1. Import a contact which do have a wrong disease. For example `M.pneumoniae`
2. A new disease will be added in the list of all diseases.
3. Wrong disease will be imported in the system.

### Expected Behavior
1. No new disease should be added to the list of all diseases.
2. Should be reported the error that wrong disease has been reported.

### Screenshots
![image](https://user-images.githubusercontent.com/6985315/118934968-a402c080-b953-11eb-8edf-898e311d0ed5.png)
![image](https://user-images.githubusercontent.com/6985315/118935384-2a1f0700-b954-11eb-82af-22cd0d15ebd8.png)

### System Details
* Device:
* SORMAS version: 1.60

* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
Attached is the Contact file used for import.
[sormas_kontakte_2021-05-04_- cu bug de M.pneumoniae.csv.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6513646/sormas_kontakte_2021-05-04_-.cu.bug.de.M.pneumoniae.csv.zip)

**Comment by cazacmarin** [comment]
There is such Disease as M.PNEUMONIAE and C.PNEUMONIAE in the Disease enum. Misunderstanding appeared when:
1. Editing a contact, we cannot chose M.PNEUMONIAE disease. This disease is existing but is not displayed in the combo-box list of diseases. Like other 35 out of 55 diseases. 
2. M.PNEUMONIAE = M_PNEUMONIAE - it means that if in the excel file we have dots and underscore at least in the disease column, it will be treated as the same value of disease.
Based on that, I'm closing this issue.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas on local environment

**Comment by vidi42** [comment]
Follow-up ticket opened regarding importing entities with inactive diseases https://github.com/hzi-braunschweig/SORMAS-Project/issues/5781
