### ISSUE TITLE
Converting Eventparticipant to Case not working

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#5494]
### Bug Description
Hi guys,

since 1.59.x it is not possible to convert an eventparticipant to a case.

### Steps to Reproduce

1.from eventparticipant list in an event:
* clicking on an empty place of the Case-ID (red circle on Screenshot)
* nothing happens 
2.

### Expected Behavior
in 1.58.x it was possible to convert the eventparticipant to a case.

### Screenshots
![Screenshot (4)_LI](https://user-images.githubusercontent.com/79255722/118941206-c693da00-b951-11eb-9246-7298cf5e5503.jpg)

### System Details
1.59.2
User Role: Administrator, Laborbeauftragte*r, Administrator Überwachungsleitung, Überwachungsleitung, Kontaktleitung

**Comment by MateStrysewske** [comment]
Hey @herrling-LRA-KYF, if you don't see a "Create" link there, you don't have the permissions to create a case for that event participant. Being able to click on the cell even if nothing was displayed was actually a bug that we fixed.
