### ISSUE TITLE
Default value for disease if only one is used by the server [2]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5496]
### Feature Description

Setting the deafult value for all fields, where the desease is entered to Covid19, if the server is used for this desease only.

### Problem Description

At a lot of points the user has to enter the disease, even if the server is only used for C19. This is produces a lot of clicks every day for every user.

### Proposed Change

Set the value for every disease-field to Covid19 if the system has only this desease enabled.

I know that this could be handled also in the issue #3507, but there is a) no progress and b) has every user to set this in every field by himself. More user-friendly is this variant.

**Comment by kwa20** [comment]
- Pathogen test disease is not covered when directly adding upon sample creation.
- disease of source case is not covered in contact line listing


<img width="475" alt="diseasePrefill" src="https://user-images.githubusercontent.com/70317594/132107481-643c780c-254d-4b04-80d3-29c8a34ecd1f.PNG">
<img width="320" alt="diseasePrefill2" src="https://user-images.githubusercontent.com/70317594/132107479-ed7123f5-7c14-458f-a433-c7b67a579998.PNG">

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
