### ISSUE TITLE
[Angular] "Persons" base line structure [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5502]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

Please consult the design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/PGlPqEW

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review - Done, everything looks good
