### ISSUE TITLE
[Angular][BackEnd] Reports [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5505]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/7c29014a-db26-4054-9dc5-2e56a633fbd2

- Implement the pagination, filtering and sorting for Reports similar to what was done for Cases

Note: Please investigate if there is additional work required (apparently we need different content based on the logged in user). Is this functionality already in place ?

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup I think your feature description has a copy & paste problem here :)

Concerning your question - yes, there's a different based on whether you log in as a user on national level or a user on regional level (or below); national users see a different grid by default that the regional level users don't have access to.

**Comment by MateStrysewske** [comment]
Additionally, pagination/lazy loading is not needed here as the amount of rows in each grid is very limited (amount of regions in the systems or amount of surveillance officers within a single region)

**Comment by marius2301** [comment]
Thus there is required to have a new endpoint that return all the reports based on a filter criteria and maybe a sorting list.

**Comment by marius2301** [comment]
Due to the fact that there are a small number of reports there is no need to add the pagination.
