### ISSUE TITLE
Unclear error message when saving visit will exceed max. char size of symptomcomments column

### ISSUE THREAD

**Issue by nliakm** [hzi-braunschweig/SORMAS-Project#5506]
### Bug Description
When trying to save a new visit under follow-up of a case, it will fail because the field "symptomcomments" will have more than 512 characters. This leads to a generic error message not understandable for the UI user.

### Steps to Reproduce
1. Create and save a new visit (person available and cooperative) and add a comment with less than 512 characters.
2. Open a new visit and enter in the comment field less than 512 characters but enough that the characters from the last visit and this combined will be > 512. Try to save and the generic message will pop up.

### Expected Behavior
When this problem occurs, the error message should explain the problem (like its happening, when one enters more than 512 characters directly into the comments field).
Or
Due to the fact, that every time a new visit with comment is saved, the text of that comment will be append to the "symptomcomments" column, the max. char length should be greater than 512 characters.

### Screenshots
![Screenshot from 2021-05-20 14-31-54](https://user-images.githubusercontent.com/22243466/118979372-af1c1780-b978-11eb-8d59-aa4c053859f5.png)
### System Details
* SORMAS version: 1.59.2
### Additional information
Stacktrace:
[SQL-512-too-long.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6515936/SQL-512-too-long.txt)

**Comment by maxiheyner** [comment]
@nliakm this bug was reported by a GA, after typing less than 512 characters.

**Comment by nliakm** [comment]
@maxiheyner Correct. They wanted to add a visit with a comment that had 7 characters. The comment field in symptoms already hat 509 characters at that time. So after saving the new visit, it would be more than 512 characters and this triggered the described error message.

**Comment by RazvanHodisan** [comment]
Validated on https://test.sormas.netzlink.com/ 
1.61.0-SNAPSHOT

**Comment by cazacmarin** [comment]
![image](https://user-images.githubusercontent.com/6985315/121668670-32caaf00-cab4-11eb-987a-6ca424d8a609.png)
