### ISSUE TITLE
[Automation][API] Implement POST cases test 

### ISSUE THREAD

**Issue by alinapopaiustina** [hzi-braunschweig/SORMAS-Project#5512]
Implement automated test for API enpoint @POST @path /cases/push from Case controller.
This API call will be also integrated in UI automated tests as data setup step.

Considering the above plus the fact that the request body is big and has nested objects, static data will be used (saved in a json file as test resourse) and some json properties values will be changed dynamically.

**Comment by StefanKock** [comment]
Discussed the different approaches with @alinapopaiustina @BojteTamas @MartinWahnschaffe @StefanKock:

JSON data objects (Alina, https://github.com/hzi-braunschweig/SORMAS-Project/pull/5655): 
+ Nested data for a test case in one JSON / less files
+ better readability of JSON instead in Java (depends on the developer who looks on the code)
+ Data better replacable when you want to run a test against a different instance
- hierarchy needs to be maintained in JSON and Java code

Java POJOs (Tamas, https://github.com/hzi-braunschweig/SORMAS-Project/pull/5683): 
+ Type safety
+ easier to refactor
+ less duplication for reused POJO patterns
+ test framework extends better over time
+ JSON parts still modifiable after Java generated JSON body

Conclusion: Follow usually the Java POJO approach (this ticket), but the JSON data approach can be an idea to be combined in the future (but with less boilerplate code).
