### ISSUE TITLE
Download and Remove document buttons overlay the name of the document

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5513]
### Bug Description
Upload a document which has la longer name. The  document name is not fully visible after the upload.
### Steps to Reproduce

1. Go to Cases/Contacts.
2. Select a case or a contact.
3. Add a bew Document with a longer name.

### Expected Behavior
The name should be fully visible.

### Screenshots
![image](https://user-images.githubusercontent.com/53563072/119116098-9707cf00-ba30-11eb-8109-0302864e4036.png)

### System Details

* Device:
* SORMAS version: Version: 1.61.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/
* User Role: NatUser

**Comment by GA-LKGI** [comment]
After starting the document import, our button is completely losse on the page. 

System details:
-	Sormas Version: 1.59.2
-	Browser: Edge 
-	User Role: administrator
![Unbenannt](https://user-images.githubusercontent.com/84182213/119118481-86545a80-ba2a-11eb-9222-eb0af0a8ccf0.jpg)

**Comment by roxanamlendea** [comment]
I can still reproduce it. ![image](https://user-images.githubusercontent.com/89522688/134313288-3285f1f2-3f67-48a4-bc68-9f006ffab50f.png)

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.65.0-SNAPSHOT
