### ISSUE TITLE
Submit documents in the “About” section

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5517]
### Situation Description

Today the documents deposited in the "about" part are not configurable and no other document can be deposited by the server administrator.
 
 
![image](https://user-images.githubusercontent.com/65449450/119164601-e237d700-ba5c-11eb-9373-75eb1974dbfc.png)

### Feature Description

We propose to develop the functionality allowing the server administrator to submit generic documents such as instructions for use or regulatory information in the "about" part. This part already has a "documents" section. The idea would be to make it configurable so that each central administrator can make documents available.

Only central administrators will be able to upload documents in this part, directly via the configuration files.
Users will only be able to upload the document but will not be able to upload documents in this part.

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by Marko-ilmkreis** [comment]
@carolinverset this is very similar to #4766 I think. Maybe they can solved together.

**Comment by DavidBaldsiefen** [comment]
This is already implemented: https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Customizing-the-Login-and-About-Pages#about-page

Do you have suggestions where we could document this further?
