### ISSUE TITLE
[Climedo Integration] Unable to add to Climedo a case that has an address

### ISSUE THREAD

**Issue by georgeginguta** [hzi-braunschweig/SORMAS-Project#5521]
### Bug Description

When creating a new Case and adding an address, the case will not be imported to Climedo.

### Steps to Reproduce

1. Create a case/ Save/ Add an address
2. Export to Climedo.

### Expected Behavior

The case should be added to Climedo and we should be able to see the address in Climedo
![Case with address](https://user-images.githubusercontent.com/83694188/119338429-a8531480-bc98-11eb-8e7a-2a7b95a9db52.JPG)
![Error when trying to send the case to Climedo](https://user-images.githubusercontent.com/83694188/119338431-aa1cd800-bc98-11eb-8a6f-37b05726d93d.JPG)

### System Details

* Device: Web
* SORMAS version:
* Android version/Browser:
* Server URL: https://ga1.sormas-oegd.de/
* User Role: admin

**Comment by FredrikSchaeferVitagroup** [comment]
The synchronization of addresses with climedo was never specified. So I don't aggree with the expected behaviour described above. 
It must be possible to register a person with an address, though.

**Comment by georgeginguta** [comment]
Issue is fixed.

System Details
Device: Web
SORMAS version: 1.60.1 Snapshot
Android version/Browser: Chrome
Server URL: https://ga1.sormas-oegd.de/

**Comment by georgeginguta** [comment]
Issue is fixed. I was able to add to Climedo Registry a user that has an address.
System Details
Device: Web
SORMAS version: 1.60.0 Snapshot
Android version/Browser: Chrome
Server URL: https://ga1.sormas-oegd.de/
