### ISSUE TITLE
Add Region (Areas) filter for Campaign data in APMIS

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#5524]
### Bug Description

For all filters and dropdown options of admin org units (Areas, Regions, Districts, Communities) in the case of APMIS (Regions, Provinces, Districts and Clusters), The Region entity is not displayed in the filter for campaign data. This needs to be show as country folks want to filter campaign data by region and then export. 
### Steps to Reproduce

1. Go to https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!campaign/?campaign=UT5HKR-3GDBCA-MYIOXL-J35PSLR4
2. On the filter tab, you will notice that region filter is missing.

### Expected Behavior

Region filter should be before Province filter.
### Screenshots

![DD1A3D22-B5F9-4365-BBA4-1607C5E8C5B5](https://user-images.githubusercontent.com/60390281/119436211-bc733200-bce9-11eb-8f8f-05fdb18566a4.jpeg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MartinWahnschaffe** [comment]
@danieltomaba Hi, this is not a bug, it was intended to build it like that (at least from our side).
