### ISSUE TITLE
Addition of an "event identification source" field in the Event part

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5526]
### Situation Description
To date, contact tracing is essentially based on a top-down logic by deploying forward-tracing. In order to be more efficient, forward tracing is commonly supplemented by backward-tracing in order to identify a superspreader or superspreader events.
SORMAS proposes in the case directory the field "source identification case" and we propose to duplicate this field in the event bet.

### Feature Description
- Develop the "event identification source" field in the event sheet in order to define whether the event is identified and investigated in an ascending or descending logic. 
This field could take the form of a drop-down list with the following modalities: backward-tracing; forward-tracing, unknown. 
It could be located to the right of the "event management status" field

- Addition of a variable in the events directory
- Adding a filter based on this variable in the event directory
- Addition in the various exports

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by bernardsilenou** [comment]
@kwa20  any comment on this?

**Comment by kwa20** [comment]
@carolinverset @bernardsilenou If I understand correctly, the desired field is supposed to be coherent with the case identification source field and contact identification source field. If so, the source of information section is pretty much what resembles this already. If the field is supposed to provide a direction of how the event is supposed to be managed or investigated, we might want to refine this further. To me, this sounds like it would potentially relate to tasks and actions?

**Comment by ftavin** [comment]
@carolinverset @bernardsilenou in addition can you tell if this new field should be added :
- to the event directory ? (can be used to order ?)
- to the filters ?
- to exports ? (which ?)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @tbroyer
Very important field, consequently thank you for:

- add it as a column in the event and actions directory with the possibility of sorting on this field
- also add the filter (event and actions directory) to reduce the directory to only the observation of a selected variant
- add it in all exports (events and actions)

**Comment by ftavin** [comment]
@bernardsilenou can you confirm this is ok for you as soon as possible ?

**Comment by bernardsilenou** [comment]
@ftavin @carolinverset @kwa20 
I just had a look at event attributes and realized that the new variable `event identification source` has the same meaning as `source type`, which is to know how the event was identified.

I would suggest that we add the new enums: `backward-tracing`; `forward-tracing`, `unknown` to the source type and rename source type to `event identification source` or just `identification source`

Then add it to all export + filters as need.

**Comment by ftavin** [comment]
@bernardsilenou I think @tbroyer already started working on this issue. We should avoid complete modification of issues after their validation as it leads to waste of development time... (and that can be irritating for the developer)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou @tbroyer 
I see a difference between type of source which corresponds rather to the origin of the signal, the person or the model having made it possible to identify the signal. In France, the source of the signal allows us to indicate if it is a territorial collectivity or the health insurance which transmitted the signal (with the possibility of indicating the name of the person who transmitted the signal to us) and the distinction between the backward and forward tracing which corresponds more to the way in which is identified and investigated the event

I think it is important to separate these two information because an event can be identified in a backward logic and have been identified by different partners.  And it is important to know who identified the signal AND in what logic

**Comment by bernardsilenou** [comment]
@carolinverset @ftavin 
Then we do as you suggest, add as a new variable please.

**Comment by carolinverset** [comment]
Thank you very much @bernardsilenou

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest deployed  SORMAS Version: 1.62.0-SNAPSHOT on test.sormas.netzlink.com
