### ISSUE TITLE
Event links are lost during case duplicate merging

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5529]
### Bug Description
When a case is discarded while merging duplicate cases, the remaining case does not adopt existing event links of the discarded case.

### Steps to Reproduce

1. Intentionally create duplicate cases.
2. Only link one of the duplicate cases to an event.
3. Open the duplicate cases merge window.
4. Merge the duplicate cases and select the case that is not linked to any event.

### Expected Behavior
The link of the discarded case should remain in the case that is kept as the leading case. Otherwise, this information is lost.

### Screenshots
Case duplicate 1 (to be discarded)
<img width="667" alt="lostLinkMerge" src="https://user-images.githubusercontent.com/70317594/119485059-edd61700-bd56-11eb-9f4e-f0b5305ce169.PNG">

Case duplicate 2 (remaining)
<img width="662" alt="lostLinkMerge4" src="https://user-images.githubusercontent.com/70317594/119485075-f29acb00-bd56-11eb-8d94-78449374ea6d.PNG">

Person view
<img width="666" alt="lostLinkMerge5" src="https://user-images.githubusercontent.com/70317594/119485082-f3cbf800-bd56-11eb-8555-7da7dfb487b3.PNG">

Merge duplicate cases view
<img width="845" alt="lostLinkMerge6" src="https://user-images.githubusercontent.com/70317594/119485091-f4fd2500-bd56-11eb-80bc-be30b27c49ad.PNG">

### System Details

* Device:
* SORMAS version: 1.59/1.60
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

Also add Unit Tests for this bug

**Comment by MateStrysewske** [comment]
Also happens for duplicate contact merging

**Comment by MateStrysewske** [comment]
Doing it for contacts is out of scope for this issue because it would likely require us to also merge the persons. See #5704

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS: 1.61.0-SNAPSHOT on test.sormas.netzlink.com
