### ISSUE TITLE
Update case classification and sample information on the case form when a new sample is saved

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5531]
### Bug Description

- When a new sample + positive pathogen test is registered in one step, the sample information on case form remain as "pending" and user is not asked to automatically classify the case as confirmed.
### Steps to Reproduce

1. Create a covid case
2. Add a sample + lab result + variant to the pathogen test
3. Choose OK to all popups 
4. Return to case and check the case classification  and sample form on right

### Expected Behavior

- If pathogen test of the same disease is created, ask user to update  the following if different
          - final lab result
          - variant
          - case classification
- Show updated information on sample (positive)  and  case classification (confirmed) on case form

### Screenshots

![image](https://user-images.githubusercontent.com/12996724/119526335-98623000-bd7f-11eb-9214-68e02f7bb410.png)

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: National user + admin

**Comment by richardbartha** [comment]
**Does not seem to work correctly!** 
From my understanding as written by @bernardsilenou in the description importing a lab result and having a positive pathogen test with different disease variant then the case itself it should still work.
@bernardsilenou **can you confirm this is this how it should work ?** 
Currently it only works if the case and pathogen test are the same variant else the classification will be in not yet classified and lab result will still be in pending state!

**Comment by ChristopherRiedel** [comment]
> **Does not seem to work correctly!**
> From my understanding as written by @bernardsilenou in the description importing a lab result and having a positive pathogen test with different disease variant then the case itself it should still work.
> @bernardsilenou **can you confirm this is this how it should work ?**
> Currently it only works if the case and pathogen test are the same variant else the classification will be in not yet classified and lab result will still be in pending state!

This is probably not true, but @AndyBakcsy-she will test it again.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment of Sormas 1.60.1-snapshot using the hotfix branch
