### ISSUE TITLE
New Contact should not adopt the events of former contacts/ep

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5534]
### Bug Description

When a new contact is entered, it should not be linked to events in which the person was previously a participant.

The link can then only be broken by deleting the ep. The other way is always to save a new person and not use the same person for the contact.

Both solutions are not practical.

Cases have the correct behavior because they are not automatically linked to the events.

### Steps to Reproduce

1. Search for a contact were the person is linked to an event
2. enter a new contact and select use the same person in the duplicate detection

### System Details
* SORMAS version: 1.59.2
* Server URL: own instance

**Comment by kwa20** [comment]
@Marko-ilmkreis I think this is a limitation that still exists due to the contact - event link being person based rather than contact based at the moment. This previously also occurred in what you mentioned in #3999 and will likely be handled with #3677 (and #3560)

**Comment by MateStrysewske** [comment]
@kwa20 is correct - we need a refactoring of the whole feature which will also fix this problem.
