### ISSUE TITLE
After editing a case Person and contact Person you need to refresh the page in order to see the changes

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5535]
### Bug Description
On the Case Person page, if I edit any field then I click save, the changes will be displayed only after I refresh the page or I leave and return to the Page.

### Steps to Reproduce

1. Select a Case from Cases
2. Go to Case Person
3. Change the Present Condition of Person to alive or any other option
4. Click Save

### Expected Behavior
After I click save I should see the changes made on the page.

### System Details

* Device:
* SORMAS version: Version: 1.61.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/
* User Role: NatUser

### Additional Information
This also applies for the Contacts page. If you go to Contacts > select a contact and go to Contact Person page and make a change you will need to refresh in order to see the changes.

**Comment by Candice-Louw** [comment]
Same happens when updating Contact Details.

**Comment by alexcaruntu-vita** [comment]
Not reproducible with the latest build.

**Comment by RazvanHodisan** [comment]
Verified on the latest build.
