### ISSUE TITLE
Set cleared to buttons should not be dependent on clear all button.

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5536]
### Feature Description
If I go on the Symptoms Page and I set cleared to no all the listed symptoms will be set as no. Same applies for set cleared to unknown.

### Problem Description
As a user if I missclick and I set  cleared to no all the symptoms I will have to Clear All first then set them to unknown and vice versa.

### Proposed Change
If I click on Set cleared to no sympoms button the click to unknown the changes should be reflected in the UI. 

### Additional Information
At the moment this is not possible:
![image](https://user-images.githubusercontent.com/53563072/119617294-5df1a500-be0a-11eb-9606-914e374f0f38.png)

This would be the steps which needs to be taken in order to Set them to Unknown
![image](https://user-images.githubusercontent.com/53563072/119617366-7497fc00-be0a-11eb-8a10-9c84365aa5e6.png)

**Comment by kwa20** [comment]
Hi @RazvanHodisan, this is intentional behaviour because the "Set cleared to no/unknown" buttons should only take into consideration the unselected fields. The advantage is that open fields can easily be completed without changing already entered data. I would therefore close this issue.
