### ISSUE TITLE
Importing community population data results in error on district page

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5537]
### Bug Description
When community population data is successfully imported, the district page shows an error.

### Steps to Reproduce

1. Go to population in configurations and import data for communities in any district
2. Navigate to the district page

### Expected Behavior
Successful population data imports should not result in errors on the district page

### Screenshots
<img width="850" alt="populationDataImportError" src="https://user-images.githubusercontent.com/70317594/119620838-bd00eb00-be05-11eb-91c3-92313e18e8b0.PNG">

### System Details

* Device:
* SORMAS version: 1.59/1.60
* Android version/Browser: firefox
* Server URL: release-sormas-x.sormas.netzlink.com, survnet-import-test.sormas.netzlink.com
* User Role: admin, national user

**Comment by kwa20** [comment]
If I re-import the data with zeros only, the display seems to go back to normal. Maybe numbers are tried to be aggregated in districts which does not function properly and causes this problem.

**Comment by kwa20** [comment]
Further investigation showed that a discrepancy in total counts likely produces the error. The sum of community population data probably has to match the district counts. Here some examples:

**Works:**

populations data export:
<img width="550" alt="populationDataError" src="https://user-images.githubusercontent.com/70317594/121353445-29afd580-c92e-11eb-8e17-fc3b169e1bb2.PNG">

district configurations:
<img width="851" alt="populationDataError2" src="https://user-images.githubusercontent.com/70317594/121353452-2ae10280-c92e-11eb-897a-246cd44e1e0d.PNG">

**Does not work:**

population data export:
<img width="511" alt="populationDataError4" src="https://user-images.githubusercontent.com/70317594/121353463-2e748980-c92e-11eb-9cea-7b9f7a457168.PNG">

district configurations:
<img width="775" alt="populationDataError3" src="https://user-images.githubusercontent.com/70317594/121353456-2c122f80-c92e-11eb-90d8-7f0632c5ae52.PNG">

**Comment by MateStrysewske** [comment]
@kwa20 I think we should handle this gracefully, right? i.e. make sure that the system can deal with community population data that does not fully cover the district population data?

**Comment by kwa20** [comment]
@MateStrysewske yes, that would be nice

**Comment by DavidBaldsiefen** [comment]
@kwa20 FYI the bug actually wasn't caused by the system calculating any sums, but by the district-population data using an incomplete query on the database. As far as I can tell the system does not care whether any population data adds up correctly at all (which makes sense in my opinion; the system should be able to rely on the user importing correct population data). This also means that if I only import community population data, the district will have no population present

**Comment by RazvanHodisan** [comment]
Validated on https://test.sormas.netzlink.com/,  Version: 1.61.0-SNAPSHOT
