### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: Allow LabMessages to lead to several PathogenTestResults [3]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5539]
### Situation Description

This issue is part of #5138. 

Counterpart in the adapter side: [#19](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/19)

In the future profile of DEMIS notifications, there may be several Observations (which map to PathogenTestResults).
SORMAS needs to be able to handle that. 

### Feature Description

Make a LabMessage hold several tests:

- [x] Create a new TestReport entity and Dto. It needs a dedicated database table. The TestReport shall hold all attributes that currently are in a labMessage and are specific to a PathogenTestResult. Those attribute's names all start with `test`, e.g. `LabMessage.testType`, `LabMessage.testDateTime` or `LabMessage.testedDisease`.
- [x] One labMessage shall be able to hold one or several testReports
- [x] Migrate the current values in the sormas-db and drop the columns in the labmessage table. OPEN QUESTION: What to do about the labmessage_history table?

Adapt the processing (**out of scope, moved to ticket #5899**):
- [ ] When processing a labMessage with just one testReport, use the same workflow as before
- [ ] When a new sample is created while processing a labMessage with several testReports, create a prefilled PathogenTest for each testReport. Allow the user to add additional PathogenTests or to remove some, but require at least one PathogenTest to be created (see mockup below)
- [ ] When an existing sample is selected while processing a labMessage with several test reports, forward to a view similar to the mockup, but just with all existing PathogenTests shown. The testReports from the labMessage must be transformed manually. This is shall be facilitated in the future.

Adapt the referencing (**in scope**)
- [ ] Currently, lab messages hold reference to a maximum of one pathogen test. They must now be able to hold reference to several. The lab message dto and entity must be adapted accordingly, as well as the getForSample(...) and getByPathogenTestUuid(...) in the [LabMessageFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java). EDIT: @FredrikSchaeferVitagroup  moved the reference to the test teport. Each report can now refer to one pathogen test. This makes more sense, because it can be used in the lifecycle management.

### Possible Alternatives

It would be imagineable to leave some attributes related to tests in the labMessage (instead of moving them to testReports). For example `testLabName`, because DEMIS notifications currently are always sent by exactly one laboratory. It may be semantically more clear and future proof when all attributes are moved to testReports, though.

An alternative for processing several testReports would be to give them a status attribute (like the one for labMessages [unprocessed, processed) and process them one by one. This would probably involve more clicks and might be more confusing.

### Additional Information
![Mockup_Multiple_Tests](https://user-images.githubusercontent.com/67001822/119632231-e96e3480-be10-11eb-9595-c388383b57f7.png)

**Comment by kwa20** [comment]
@JaquM @Jan-Boehme If the new DEMIS structure can point to multiple pathogen tests, we need to reconsider how we map lab reports to SurvNet because this will inevitably cause the creation of multiple lab reports in SurvNet when in reality, only one lab report led to multiple pathogen tests.

**Comment by JaquM** [comment]
Are several samples really sent in one DEMIS message or only several test procedures for one sample? Because then the mapping would only have to be extended if necessary.

**Comment by FredrikSchaeferVitagroup** [comment]
@JaquM As far as I know, there can only be one sample per DEMIS notification. But in the new profiles there can be several results for that one sample.

**Comment by Jan-Boehme** [comment]
Result from meeting between Fredrik, Christopher, Kay, Candice and Jan:

Having all pathogen test results as one list in the UI is the better solution than processing them one by one after each other.

**Comment by FredrikSchaeferVitagroup** [comment]
This ticket has to be split, 1. create testReport and migrate data [3], 2. Process multiple testReports [3]

**Comment by FredrikSchaeferVitagroup** [comment]
So far, I was not able to finish this. What I know is currently missing

- test reports via S2S.
- when saving a LabMessageDto, its TestReportsDtos should also automatically be saved. Maybe there is a validation necessary, that the references (testReport.labMessage) is set correctly.
