### ISSUE TITLE
Resulting case does not initially show event links when converting multiple entities at once

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5544]
### Bug Description
When converting multiple entities into the same case (cf. #4321), additional links are not initially shown, especially for linked events.

### Steps to Reproduce

1. Convert multiple event participations and contacts of one person into the same case.
2. Choose to convert all additional entities.
3. Check the event links in the case.
4. Reload the case page.

### Expected Behavior
All links should initially be shown.

### Screenshots
Contact to be converted
<img width="665" alt="convertMultipleCaseDisplay" src="https://user-images.githubusercontent.com/70317594/119659972-01ed4780-be2f-11eb-9856-67be09788b36.PNG">

Converting all additional entities
<img width="385" alt="convertMultipleCaseDisplay2" src="https://user-images.githubusercontent.com/70317594/119659978-031e7480-be2f-11eb-9c6e-92a3a38a611b.PNG">

Resulting initial case view
<img width="682" alt="convertMultipleCaseDisplay3" src="https://user-images.githubusercontent.com/70317594/119659984-044fa180-be2f-11eb-9e4f-0cdfafbbd6c9.PNG">

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by RazvanHodisan** [comment]
Verified on test-de, Version: 1.61.0-SNAPSHOT
