### ISSUE TITLE
API Endpoint to update the external token and ExternalID in a case, contact, event and person [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5545]
### Situation Description
With every new field in SORMAS we have to check differences in the converter when we want to write back the case.
With this Rest Endpoint we can avoid the conflicts

### Feature Description
Create API Endpoint to update the external token and ExternalID in a case, event and persons 

Support for a list of entities to avoid making multiple calls to SORMAS

### Additional Information
Please consult @laurentiustanvitagroup from the Angular Team as he's working on sth. that could be related

**Comment by HolgerReiseVSys** [comment]
This should fill empty fields, but never change existing values.
If fields would change, the whole request should probably be reverted.

**Comment by Alexandru-Pirvu** [comment]
Is the API supposed to update both externalId and externalToken at once or should the fields also be set sepparately?

**Comment by HolgerReiseVSys** [comment]
This should be done at once. It might be a good idea to just keep the original value of a field if it were to be set to null.
