### ISSUE TITLE
Introducing the header of the table into the column data cells as a property

### ISSUE THREAD

**Issue by BojteTamas** [hzi-braunschweig/SORMAS-Project#5546]
## Situation Description
In order to identify the elements from data cells it's very hard because there is no property related to the column header.
### Feature Description
Introduce the column header into each data cell in order to identify easier the elements of the table. See the pictures : 
Before: 
![image](https://user-images.githubusercontent.com/9676903/119675124-716e3180-be45-11eb-9057-833090030ca8.png)
After
![Pasted_Image_26_05_2021__17_13](https://user-images.githubusercontent.com/9676903/119675490-c1e58f00-be45-11eb-9476-52c98da3c6df.png)

**Comment by StefanKock** [comment]
@BojteTamas 
- I think the correct HTML tag is `headers` (see https://www.htmlquick.com/reference/tags/td.html#attributes).
- We currently use Vaadin 8 Grid for list views, and a lot of Vaadin 7 Grids for selects or dialog stuff. For both I've not yet found if and how it is possible to add tags like this.

**Comment by BojteTamas** [comment]
> @BojteTamas
> 
> * I think the correct HTML tag is `headers` (see https://www.htmlquick.com/reference/tags/td.html#attributes). Is this approach technical standard or could one also look into screen reader tags (aria).
> * We currently use Vaadin 8 Grid for list views, and a lot of Vaadin 7 Grids for selects or dialog stuff. For both I've not yet found if and how it is possible to add tags and values like this.

It doesn't mater which is the tag, we need only a property which contains the header name. In other softwares they are using test-id. `header` was provided only as example

**Comment by StefanKock** [comment]
I found that the `td headers` tag is present in `com.google.gwt.dom.clientTableCellElement` with `setHeaders` (refers to https://www.w3.org/TR/1999/REC-html401-19991224/struct/tables.html#adef-headers ), that is wrapped by `com.vaadin.client.widget.escalator.FlyweightCell` and `com.vaadin.client.widget.grid.RendererCellReference` (and respective v7 classes). But I haven't found how to set this through Vaadin API or how to extend Vaadin classes (probably client side).

**Comment by Mihai-Bota** [comment]
Fixed this in PR: https://github.com/hzi-braunschweig/SORMAS-Project/pull/5809/files

Created this helper function which will take the width of the header which is always the same as the column one and match any children column:

// always needs the raw header value from the DOM, not the stylized one (the one displayed in UI)
public String getValueFromTableRowUsingTheHeader(String headerValue, int rowIndex) {
  By header = By.xpath("//div[contains(text(), '" + headerValue + "')]/ancestor::th");
  scrollToElement(header);
  String style = getAttributeFromWebElement(header, "style");
  By selector = By.cssSelector("[style*='" + style.substring(style.length() - 17) + "']");
  return baseSteps.getDriver().findElements(selector).get(rowIndex).getText();
}

**Comment by Mihai-Bota** [comment]
added jira ticket for logging: https://jira.vitagroup.ag/browse/SOR-1686
