### ISSUE TITLE
Event investigation status labels do not get selected on first try

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#5547]
### Bug Description

When creating a new event clicking on any investigation status label beside the already selected on does not select the clicked label on first try only after clicking second time. Not a huge bug, but UI tests already fail because of it :)
### Steps to Reproduce

1.
2.

### Expected Behavior

Clicking on a label that label should be selected on first try.
### System Details

* Device: windows
* SORMAS version: 1.61.0-SNAPSHOT
* Android version/Browser: chrome
* Server URL: https://test-performance.sormas.netzlink.com/
* User Role: NatUser

**Comment by af-pwo** [comment]
Device: Windows 10
SORMAS version: 1.61.0-SNAPSHOT
Android version/Browser: Opera Version: 76.0.4017.177
Server URL: https://test-performance.sormas.netzlink.com/
User Role: NatUser

QA passed.

Label in creating new event selected on first click.
