### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: Preliminary Test Results [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5551]
### Situation Description

Preriquisite: #5539, [#20](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/20).

Adapter part: [#12](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/12)

There are pathogen tests that require confirmatory tests. For example a quick test can initiate a PCR test.
The new DEMIS profile is able to report the preliminaty as well as the confirmatory test result. 

As a user, I want to be able to mark and recognize preliminary test results, also when processing lab messages.

### Feature Description

- [ ] Add a boolean attribute called `preliminary` to PathogenTests (also in the UI, see mockup below).
- [ ] Also add it to testReports of a lab message
- [ ] Always transfer the preliminary value from testReport to PathogenTest when processing a lab message.

### Possible Alternatives

It might be an option to just add preliminary positive as PathogenTestResultType. Would preliminary negative also be necessary?

### Open Question

- What to do with the related sample's PathogenTestResult when the PathogenTestResult is preliminary? ANSWER: leave the standard approach (ask the user to update the sample result).

### Additional Information

![Mockup_Preliminary_Test-Result](https://user-images.githubusercontent.com/67001822/119800933-83031800-bedd-11eb-8235-192a2954efd5.png)

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
