### ISSUE TITLE
[Climedo] Contradictory error messages prevent proper use of the interface

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5554]
### Bug Description
When a person is seemingly registered in the symptom journal, person contact details cannot be properly deleted to be potentially used again elsewhere. Trying to cancel the external follow-up however is also not possible because the registered person is nowhere to be found in the external journal. These error messages contradict each other and cannot be easily fixed because users are neither able to cancel the external follow-up (un-register the person) or edit the person contact details properly).

### Steps to Reproduce

1. Register a person in Climedo
2. After registration, delete the person in Climedo by opening the instance and taking the person out of the study and patient section.
3. Go back to the related entity in Sormas and try to cancel the external journal and delete the person contact details

### Expected Behavior
If the person gets deleted in Climedo, the person should become un-registered in Sormas to allow editing of data.

### Screenshots

<img width="609" alt="climedoError" src="https://user-images.githubusercontent.com/70317594/119815889-586c8b80-beec-11eb-85f2-618a2a2524ac.PNG">
<img width="514" alt="climedoError2" src="https://user-images.githubusercontent.com/70317594/119816745-5b1bb080-beed-11eb-9d20-c3685acc49e3.PNG">

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup This is the issue we just talked about. This might have to be fixed by Climedo by sending an unregistered status to Sormas when patients are deleted in Climedo itself.

**Comment by FredrikSchaeferVitagroup** [comment]
Yes, the problem most probably is that climedo does not update the SympromJournalStatus via the `POST /visits-external/person/{personUuid}/status` endpoint when someone deletes the patient from within climedo.

@mariusclimedo: Could you maybe implement this feature?

So I don't see much to do here from SORMAS side. In my opinion, what should be done in such a case is to manually set the person's SymptomJournalStatus to DELETED in the sormas-db. One could think about adding an option to manually set the SymptomJournalStatus of a person in the SORMAS-UI, but I think it will do more harm than help.

**Comment by mariusclimedo** [comment]
We will have a look and get back to you with our assessment of it.

**Comment by StefanKock** [comment]
One finding in `ExternalJournalUtil` to be fixed: `showPatientDiaryResultPopup(result, Captions.patientDiaryCancelError);` (missing I18n lookup).

**Comment by StefanKock** [comment]
Summary: This ticket fixed missing labels in error dialogs. Missing features or misleading messages have to be addressed on the Climedo side.

**Comment by AndyBakcsy-she** [comment]
This issue is still reproducible. 
@FredrikSchaeferVitagroup  do you have any updates on the status of this?

**Comment by StefanKock** [comment]
> This issue is still reproducible.
> @FredrikSchaeferVitagroup do you have any updates on the status of this?

If the error message is not fixed on the Climedo side, it will still happen, see https://github.com/hzi-braunschweig/SORMAS-Project/issues/5554#issuecomment-851331372

**Comment by FredrikSchaeferVitagroup** [comment]
Climedo is currently releasing a new version. It might be worth to recheck on https://ga1.sormas-oegd.de, as they seems to have their new version linked to it.
