### ISSUE TITLE
Place of stay icon appear two times on case creation form on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5556]
### Bug Description

- Place of stay icon is appear two times on case creation form on mobile app
### Steps to Reproduce

1. Log in with surveillance officer account
2. Create a covid case, under "disease" and under "region",  you would find "place of stay"

### Expected Behavior

Delete the second occurrence of place of stay
### System Details

* Device: samsung, A9
* SORMAS version: 1.60
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: surveillance + contact officer

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of android app 1.61.0-snapshot on test.sormas.netzlink.com environment
