### ISSUE TITLE
[Sormas2Sormas] Returning cases without contacts or samples leaves contacts and samples disabled in both instances

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5562]
### Bug Description
When a received case with ownership is returned to the sender without the initially received contacts or samples, contacts and samples are left disabled in both instances.

### Steps to Reproduce

1. Handover a case with ownership and include contacts and samples
2. Return the case with ownership excluding the samples and contacts

### Expected Behavior

If ownership is not returned for samples and contacts, the returning instance has to remain full access to all contacts and samples.
### Screenshots

Share
<img width="201" alt="s2sSend" src="https://user-images.githubusercontent.com/70317594/119864330-d2b40480-bf1a-11eb-8dca-1375393d4ed6.PNG">

Return
<img width="223" alt="s2sSend2" src="https://user-images.githubusercontent.com/70317594/119864335-d3e53180-bf1a-11eb-8257-af2028e7d8d0.PNG">

Contacts
<img width="672" alt="s2sSend3" src="https://user-images.githubusercontent.com/70317594/119864340-d5165e80-bf1a-11eb-803c-6952e94bc843.PNG">
<img width="670" alt="s2sSend4" src="https://user-images.githubusercontent.com/70317594/119864345-d6478b80-bf1a-11eb-8698-96db06a02977.PNG">

Samples
<img width="668" alt="s2sSend6" src="https://user-images.githubusercontent.com/70317594/119864353-d9427c00-bf1a-11eb-8260-96bddf341c7b.PNG">
<img width="673" alt="s2sSend7" src="https://user-images.githubusercontent.com/70317594/119864358-da73a900-bf1a-11eb-9e00-160ba5012caf.PNG">

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de, release-de.sormas.netzlink.com
* User Role: admin, national user

**Comment by leventegal-she** [comment]
During the implementation of accept/reject functionality a few things changed. The current situation is that doesn't matter what options are select when returning everything gets returned so the objects will be editable on the original system and readonly on the receiving system.

This doesn't seem to be the best way of handling return but I think it would make more sense to return everything than returning only the case.

My suggestion for closing this ticket would be:
**For now**: make all options disabled and check the ones that were checked when sharing the case

**For long term**: create a ticket and specify the required behaviour answering questions like: 
* do we allow returning only the case, or with samples but no contacts, or with contacts but no samples?
* do we include the associated objects (contacts, samples) created on the receiving system if the options are checked or we add a separate option for them? Maybe return all that came with the initial share without setting any options and if the options are checked then send also the new objects created on the receiving system.

@markusmann-vg @MateStrysewske @MartinWahnschaffe @kwa20

**Comment by markusmann-vg** [comment]
@leventegal-she 
Let's go with your first approach:
For now: make all options disabled and check the ones that were checked when sharing the case

**Comment by AndyBakcsy-she** [comment]
Validated the requested implementation scenario on the latest SORMAS Version: 1.62.0-SNAPSHOT using test-de1 and test-de2 environments
