### ISSUE TITLE
[Angular] Create short ID based on entity UUID for all tables. [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5564]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

1. Create short ID based on entity UUID for all tables.
2. We need to make them blue (clickable). The link text should be the first part of the UUID as per the legacy Sormas implementation.

This should be implemented accross the board: 

- cases: Case ID, latest event ID la detailed view
- tasks - associated link te duce la case, 
- persons - Person ID deschide person page
- contacts - contact ID (takes you to the contacts), on the detailed views (Source case ID) from the source, opens the case which is the source for the respective contact, Latest event ID 
- Contacts follow-up - Contact ID
- event - Event ID
- event groups - Group ID
- Samples - Sample ID 
- Sample/Lab messages - The "Processed" colum. Opens a modal with a "pick" / "Create Person".
- Users - UUID
- follow-up - edit visit, clinical assessments - edit clinical assessment and edits for configurations for almost all the tabs , continents, subcontinent, countries, regions, districts, etc
- in events, there is the event group

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by bernardsilenou** [comment]
Maybe we can use the first 6 characters? XYV2I3
