### ISSUE TITLE
[Angular][Backend] Make sure that data returned for tables is correct (Events, Contacts, Persons, etc)[2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5566]
### Steps to Reproduce

1. Go to the Events page
2. Notice that 3 events are returned (using test site d2)
3. Go to the actual test site and notice that only a single event is visible.

Are the other two events archived and we erroneously pull them with the valid one ? 
@marius2301 please discuss with @danielrus for more details / demo

### Expected Behavior

1. We should return only the valid data (the one that is also returned on the existing legacy Sormas test site).

### Screenshots

N/A

### System Details

* Device: ALL
* SORMAS version: 1.60.0
* Android version/Browser: ALL
* Server URL: https://test-de2.sormas.netzlink.com/sormas-ui/login
* User Role: All that can see events

**Comment by marius2301** [comment]
If there is no filter assigned the endpoint returns all the events - there is no filtering on the person jurisdiction level. Also the archive events are returned too. 
Thus, to keep how the search criteria works the front end should always supply a filter. 
- If the events that are archived should not be returned then the call should contains a filter with the settings “relevanceStatus”:“ACTIVE”.

**Comment by marius2301** [comment]
When there is a filter on the request the userfilter criteria is added (which filter the entities per user jurisdiction). The conclusion after the discussion with Mate is to leave it like it is in the backend and the frontend to call always the endpoint with  a filter different from null.

**Comment by laurentiustanvitagroup** [comment]
Based on the discussion with Mate, we will need to check on the BE if the filter is empty. A new task will be raised for this.
