### ISSUE TITLE
Review of new SORMAS app design implementation [5+X]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#558]
In the context of the new app design implementation (#490) a lot of new components, layouts and also concepts have been introduced. While this highly improves the usability and visual appeal of the app it also comes with a higher complexity. A review of the implementation needs to be done to identify possible bugs and problems and to define refactorings with the goal of high maintainability and stability.

In addition the feature branch should be merged into the development branch.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
Can you please provide the test checklist you are using for app testing?

**Comment by MartinWahnschaffeSymeda** [comment]
- [x] clean-up strings.xml
- [x] ChangesOnly
- [x] Case querryUuid
- [ ] startActivity, finish -> return in all activities // maybe no longer relevant
- [ ] dengue in CaseDataEditForm, CaseNewForm
```
        FieldHelper.initSpinnerField(binding.caseDataDengueFeverType, DengueFeverType.class);

                if (field.getValue() == Disease.DENGUE) {
                    binding.caseDataDengueFeverType.setVisibility(View.VISIBLE);
                } else {
                    binding.caseDataDengueFeverType.setVisibility(View.GONE);
                }
```
- [ ] meningeal signs, monkeypox, symptoms onset in SymptomsEditForm
`		binding.symptomsMeningealSigns		`
`        binding.symptomsLesionsOnsetDate.setVisibility(symptomState == SymptomState.YES ? View.VISIBLE : View.GONE);`
```
        } else {
            binding.symptomsMonkeypoxLayout.setVisibility(View.GONE);
        }
```
- [ ] similar persons in case creation, contact creation, EventParticipantNewActivity
```
                    List<PersonNameDto> existingPersons = DatabaseHelper.getPersonDao().getPersonNameDtos();
                    List<Person> similarPersons = new ArrayList<>();
                    for (PersonNameDto existingPerson : existingPersons) {
                        if (PersonHelper.areNamesSimilar(contact.getPerson().getFirstName() + " " + contact.getPerson().getLastName(),
                                existingPerson.getFirstName() + " " + existingPerson.getLastName())) {
                            Person person = DatabaseHelper.getPersonDao().queryForId(existingPerson.getId());
                            similarPersons.add(person);
                        }
                    }
```
- [ ] contactCase in ContactEditActivity, ContactEditDataForm, ContactEditPagerAdapter, ContactNewActivity
```
                // not null, because contact can only be created when the user has access to the case
                Case contactCase = DatabaseHelper.getCaseDao().queryUuidBasic(caseUuid);
                contact.setCaseUuid(caseUuid);
                contact.setCaseDisease(contactCase.getDisease());
```
				
```
            LabelField associatedCaseLabel = binding.contactAssociatedCase;
            associatedCaseLabel.setValue(DataHelper.getShortUuid(contact.getResultingCaseUuid()));
            final Case resultingCase = DatabaseHelper.getCaseDao().queryUuidReference(contact.getResultingCaseUuid());
            if (resultingCase != null) {
                associatedCaseLabel.makeLink(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        showCaseEditView(resultingCase);
                    }
                });
            }
            binding.contactCreateCase.setVisibility(View.GONE);
```
- [ ] resulting case uuid in EventParticipantsListArrayAdapter
```
        TextView uuid = (TextView) convertView.findViewById(R.id.eventParticipant_uuid_li);
        uuid.setText(DataHelper.getShortUuid(eventParticipant.getUuid()));
```
```

        if (eventParticipant.getResultingCaseUuid() != null) {
            TextView caseStatus = (TextView) convertView.findViewById(R.id.eventParticipant_case_li);
            Case caze = DatabaseHelper.getCaseDao().queryUuidBasic(eventParticipant.getResultingCaseUuid());
            caseStatus.setText(caze != null ? caze.getInvestigationStatus().toString() : "");
        }
```
- [ ] EventsActivity new case
- [ ] other lab SampleEditForm
```
       binding.sampleLab.addValueChangedListener(new PropertyField.ValueChangeListener() {
            @Override
            public void onChange(PropertyField field) {
                TextField labDetailsField = binding.sampleLabDetails;
                Facility selectedLab = (Facility) field.getValue();

                if (selectedLab != null && selectedLab.getUuid().equals(FacilityDto.OTHER_LABORATORY_UUID)) {
                    labDetailsField.setVisibility(View.VISIBLE);
                } else {
                    labDetailsField.setVisibility(View.GONE);
                }
            }
        });
```

```
        binding.sampleDateTime.initialize(this);
        FieldHelper.initSpinnerField(binding.sampleMaterial, SampleMaterial.class);
        FieldHelper.initSpinnerField(binding.sampleSampleSource, SampleSource.class);
        if (binding.getSample().getAssociatedCase().getDisease() != Disease.NEW_INFLUENCA) {
            binding.sampleSampleSource.setVisibility(View.GONE);
        }
```

```
                binding.sampleSampleSource.setEnabled(false);
                binding.sampleLabDetails.setEnabled(false);
```
				
- [ ] dev clicks in SettingsForm
```
    private final int SHOW_DEV_OPTIONS_CLICK_LIMIT = 5;

    private SettingsFragmentLayoutBinding binding;
    private int versionClickedCount;

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        binding = DataBindingUtil.inflate(inflater, R.layout.settings_fragment_layout, container, false);

        binding.configServerUrl.setValue((String)ConfigProvider.getServerRestUrl());

        binding.configRepullData.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                repullData();
            }
        });

        binding.sormasVersion.append(" " + InfoProvider.getVersion());
        binding.sormasVersion.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                versionClickedCount++;
                if (versionClickedCount >= SHOW_DEV_OPTIONS_CLICK_LIMIT) {
                    binding.devOptions.setVisibility(View.VISIBLE);
                }
            }
        });

        return binding.getRoot();
    }

    @Override
    public void onResume() {
        super.onResume();

        versionClickedCount = 0;
        binding.devOptions.setVisibility(View.GONE);

        boolean hasUser = ConfigProvider.getUser() != null;
        binding.configChangePIN.setVisibility(hasUser ? View.VISIBLE : View.GONE);
        binding.configRepullData.setVisibility(hasUser ? View.VISIBLE : View.GONE);
        binding.configSyncLog.setVisibility(hasUser ? View.VISIBLE : View.GONE);
        binding.configLogout.setVisibility(hasUser ? View.VISIBLE : View.GONE);
    }
```
	
`                if (e.getAppUrl() != null && !e.getAppUrl().isEmpty()) {`

**Comment by MartinWahnschaffeSymeda** [comment]
## Severe Bugs
- [x] check why initial synchronizing on app start takes longer than before
- [x] infrastructure data in dropdowns is not properly sorted by name
- [x] duplicates in infrastructure dropdowns
- [x] remove logout button from menu
- [ ] read-mode does not hide fields (e.g. symptoms) by disease
- [ ] same for epi data fields (animal contacts)
- [ ] symptoms read form for monkeypox does not contain lesions details field

## Minor Bugs
- [ ] drawer menu items are cropped

## Missing Functionality
- [ ] validation is either very basic (samples) or non-existing (cases)
- [ ] numbers in main menu and filter menu are dummy data

## Code Maintainability
- [ ] symptoms apparently don't use the annotations anymore, but instead the Symptom class where every single symptom has a custom class with ~ 30 lines of code that also defines where it should be used for diseases
- [ ] labels are taken from strings_forms.xml file instead of properties

## Usability
- [ ] auto-close non-essential notifications (e.g. case saved, successfully synchronized)
- [ ] close navigation after selecting section
- [ ] read -> write: stay in same section
- [ ] allow user to navigate back to read-mode
- [ ] back navigation no longer working (e.g. from case back to task)
- [ ] sync indicator is not hidden after sync is done in background
- [ ] lists do not visualize which entries have unread changes
- [ ] remove image from main menu? (either find replacement or decrease header height)

**Comment by MateStrysewskeSym** [comment]
Next steps:

Fix severe bugs:
- [ ] getActivityCommunicator often returns null and leads to crashes
- [ ] cases are not showing when starting the app. Doing sync then crashes the app (see above)

Adjustments:
- [ ] remove unnecessary Epid classes
- [ ] use I18nProperties for labels
- [ ] add default values to component classes and remove them from the layouts
- [ ] add dependencies to property field

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym TeboPropertyField.getPropertyId should be working again. Biggest problem with this are the field ids which mostly don't have the name of the property in the dto class, but something with a prefix (e.g. txtFirstName instead of firstName for PersonDto).
