### ISSUE TITLE
Counts on dashboard and contact directory should be the same

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5589]
### Bug Description

#3004 implemented some changes to the dashboard for cases and contacts. Some  changes were not implemented maybe
### Steps to Reproduce

1. Go to contact dash board and filter for a particular time; I used 1 to 31 May.
2. Go to contact directory and do the same filter. Choose report date
3. The counts to do not match

### Screenshots

![image](https://user-images.githubusercontent.com/12996724/120235008-6eb27880-c259-11eb-82a7-b01d12925b9c.png)

![image](https://user-images.githubusercontent.com/12996724/120235144-b76a3180-c259-11eb-90b9-46c67d959663.png)

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: 
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/#!dashboard/contacts
* User Role: National user + admin

**Comment by VitaliHZI** [comment]
Hey @bernardsilenou do you see this issue as critical? Than we would put it in 1.60.1 or is it enough in 1.61.0 and we can start to release the 1.60.1

**Comment by bernardsilenou** [comment]
@VitaliHZI No, no need to add to the hotfix branch. We can address in future release. 
Thanks

**Comment by MateStrysewske** [comment]
@bernardsilenou The contact dashboard shows the active contacts in the given time period while the contact directory, when filtered by contact date, shows the new contacts from this time period, so both are semantically different, and so far, that has been on purpose (and makes sense in my opinion). If you need this logic to be changed, we need a change request for it.

**Comment by bernardsilenou** [comment]
@MateStrysewske Thanks for this clarification, I did not know this is the situation. 
@kwa20  This may also be the cause of the difference in counts for cases we discussed last week. 

The change request can be:
 -  to show all archived and active entities (case, contacts, events on dashboard)
 -  to exclude deleted entities only

If you agree, then can some create issue for it?
