### ISSUE TITLE
Introduce a reference definition for cases [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5594]
### Situation Description

German health departments use a reference definition in order to further classify cases. This reference definition is used for later analysis by higher health authorities. 
### Feature Description

Introduce a **'Reference definition'** field for COVID-19 cases that is uneditable and computed on save (DE only). This field will have the values
- fulfilled
- not fulfilled

Computation follows closely what is specified for confirmed case classifications in #4770. What defines whether the reference definition is fulfilled or not is the pathogen test types. Therefore, `fulfilled` is automatically applied if the classification criteria for the respective case classification CONFIRMED, CONFIRMED_NO_SYMPTOMS or CONFIRMED_UNKNOWN_SYMPTOMS is met; however, the test types `ANTIGEN_DETECTION` and `RAPID_TEST` are NOT to be taken into account here. 

Implementation suggestion: In CaseFacadeEjb.onCaseChanged, after calculating the case classification and only on German instances and for CORONAVIRUS cases, check whether it's one of the three CONFIRMED classification AND the case has at least one positive pathogen test result for CORONAVIRUS of the test types PCR_RT_PCR, ISOLATION or SEQUENCING. If so, set the reference definition to fulfilled, otherwise to not fulfilled.

<img width="721" alt="referenceDefinition" src="https://user-images.githubusercontent.com/70317594/120289006-1b741080-c2c1-11eb-871e-bed96dc1612d.PNG">

Further, add a checkbox filter on the case directory that filters cases according to their reference definition (DE only): 
- "Only show cases with fulfilled reference definition"
    - if unchecked, show all cases as usual
    - if checked, only show cases with fulfilled reference definition

Add an additional number to the surveillance dashboard (DE only) in the disease carousel layout for CORONAVIRUS only, underneath "Cases resulting from contacts" (see Kay's screenshot below); call it "Reference definition fulfilled" and count the number of cases where reference definition == fulfilled.

### Additional Information

@JaquM

**Comment by maxiheyner** [comment]
Issue Tracker Comment
Erfülltes klinisches Bild durch Setzen auf „Ja“ bei Covid-19-assoziierten Symptomen (siehe Aufzählung unten) UND positiver PCR-Nachweis ODER  positive Erregerisolation bzw. Sequenzierung.

D1.
Labordiagnostischer Nachweis bei nicht erfüllter Klinik
Labordiagnostischer Nachweis durch Nukleinsäurenachweis oder Erregerisolation (D1) bei Vorliegen einer Klinik, welche nicht die Kriterien von COVID-19 erfüllt.
Klinisches Bild ist NICHT erfüllt (alle anderen Symptome außer COVID-19 betreffende) UND positive PCR Probe ODER positive Erregerisolation bzw. Sequenzierung

E.
Labordiagnostischer Nachweis bei unbekannter Klinik
Labordiagnostischer Nachweis durch Nukleinsäure-detektion oder Erregerisolation (E1) bei nicht feststellbarem oder nicht erfasstem klinischem Bild.  
Unbekanntes klinisches Bild UND positive PCR Probe ODER positiver Erregerisolation bzw. Sequenzierung 

Klinisches Bild (mind. eines der folgenden Symptome trifft zu): 
Akute respiratorische Symptome jedweder Schwere: Husten, Lungenentzündung (klinisch oder radiologisch), Akutes Atemnotsyndrom (ARDS), Respiratorische Insuffizienz, die eine assistierte Beatmung erfordert, Schwierigkeiten beim Atmen/Dyspnoe, Geruchsverlust, Geschmacksverlust, Halsentzündung/ Pharyngitis, krankheitsbedingter Tod### End-Description-DE -->

**Comment by MateStrysewske** [comment]
@kwa20 Should the filter really be added to the dashboard or were you referring to the case directory?

**Comment by kwa20** [comment]
@MateStrysewske I think that was the request, yes. I do, however, see a few challenges here which I didn't think about. The filter would technically exclude all non-confirmed cases by default. An alternative could be to just add the total number of cases fulfilling the reference definition in the filtered time period here:

<img width="558" alt="referenceDefinitionDashboard" src="https://user-images.githubusercontent.com/70317594/127023119-b9c89be7-e5af-4788-8285-82d5d7c8587b.PNG">
@JaquM What do you think?

Adding it to the cases directory as well would make total sense though. Would that be much to add to this issue?

**Comment by MateStrysewske** [comment]
@kwa20 I'd prefer to go with your alternative approach then (i.e. add it as an additional number to the carousel layout). And we can do the directory filter as well.

**Comment by sergiupacurariu** [comment]
Clarifications needed:
- How do we calculate the "Reference definition" field when the case classification is set manually and the other conditions are not met?
- A new field will be added to the Cases table. Do we need to run the calculation on the existing cases?

**Comment by MateStrysewske** [comment]
@kwa20 In Germany, the classification criteria currently is only checked when users manually request it by clicking on a button and there's no automatic calculation, right? When exactly should the reference definition be updated? Should it follow the same rules or should it be updated every time a case is saved (which could potentially have a negative impact on performance)?

Also, what if the user has manually overwritten the classification with one of the confirmed classifications? Should we still do a full calculation for the reference definition or should we take the confirmed classification as a fact and just check whether there's a pathogen test with one of the valid test types?

**Comment by kwa20** [comment]
> the classification criteria currently is only checked when users manually request it by clicking on a button and there's no automatic calculation, right?

There actually is an automatic calculation but if the user has changed the calculation manually, they would be able to trigger it again and get the results of the defined criteria.

> When exactly should the reference definition be updated? 

If it follows the same rules I think this would also always be triggered when saving a case.

> Also, what if the user has manually overwritten the classification with one of the confirmed classifications? Should we still do a full calculation for the reference definition or should we take the confirmed classification as a fact and just check whether there's a pathogen test with one of the valid test types?

I think we can just take overwritten classifications as a "fact" because the classification will then at least always be conform to the classification, if the classification is recalculated and therefore different, the reference definition would also be adjusted accordingly.

@JaquM This would mean that theoretically, users could change classifications manually which then don't fulfill the reference definition but after sending to SurvNet show up as fulfilled. This is not really a logical use case so I would count on user responsibility in this case. Do you see any problem with that?

**Comment by JaquM** [comment]
@MateStrysewske 
Please do a full calculation for the reference definition.

**Comment by MateStrysewske** [comment]
@sergiupacurariu That means:

* Whenever the case classification is calculated, also calculate the reference definition (if it's a German server and a CORONAVIRUS case)
* Reference definition needs to be calculated independent of the case classification, i.e. we can't use the case classification as a basis; ideally, whenever the case classification is calculated alongside the reference definition, we could use the calculated classification as a basis (so that we don't have to do it twice) and only do the additional check whether there's a positive pathogen test with the valid test types (as defined above)

**Comment by kwa20** [comment]
@MateStrysewske I forgot an important criteria in this issue which I am not sure is covered by the initial specification:

If `caseClassification` = `NO_CASE`, the reference definition has to always be set to not fulfilled

**Comment by kwa20** [comment]
@bernardsilenou I don't think that's possible unfortunately because cases in the reporting tool need to be updated with the information of not being a case if sent already and the reference definition in the reporting tool only has two values itself.
