### ISSUE TITLE
Initial Import Error Log Addition

### ISSUE THREAD

**Issue by af-rka** [hzi-braunschweig/SORMAS-Project#5600]
### Feature Description

While initial import of cases from SurfNet -> SORMAS, errors and exceptions might occur which and are logged.
### Problem Description

To be able to add skipped cases by hand, health deparments need to identify the cases in SurfNet via SurfNet ID. Current log is includes SORMAS ID only. E.g.: '653. ÜBERSPRINGE Fall#FORGOK-HB75GN-LFR7IY-T53MTR6A: Could not save entries: ERROR'. To have a better understanding when exactly these errors occured, a timestamp would be ideally.
### Proposed Change

Please add the SurfNet-ID and a timestamp to the log entries as well.
### Possible Alternatives

/
### Additional Information

StackTrace of the error above will be handled in a separate ticket.

**Comment by ChristopherRiedel** [comment]
This issue belongs into another repository.
