### ISSUE TITLE
[DEMIS2SORMAS] Automatically prefill PathogenTest.testType [1]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5604]
### Situation Description

A DEMIS notification profides information about the PathogenTest.testType in the [Observation.code.coding](https://simplifier.net/covid-19labormeldung/pathogendetectionsarscov2). As becomes visible there, the possible values are shown in [https://simplifier.net/covid-19labormeldung/laboratorytestsarscov2](https://simplifier.net/covid-19labormeldung/laboratorytestsarscov2). This information should be prefilled to the PathogenTest.testType when processing lab messages.

Related adapter ticket: [#11](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/11).

### Feature Description

The tes report entity already has a `.testType` attribute.

- [ ] Automatically transfer this attribute's value to the related PathogenTestDto.testType when processing lab messages.

**Comment by FredrikSchaeferVitagroup** [comment]
@Jan-Boehme @kwa20 @JaquM Could you please provide a mapping specification ([https://simplifier.net/covid-19labormeldung/laboratorytestsarscov2](https://simplifier.net/covid-19labormeldung/laboratorytestsarscov2) to [PathogenTestType](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/java/de/symeda/sormas/api/sample/PathogenTestType.java)?

**Comment by Jan-Boehme** [comment]
@FredrikSchaeferVitagroup @JaquM 

Here is the mapping for every LOINC code from the linked documentation

<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/janbo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/janbo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





Code | Display | PathogenTest.testType
-- | -- | --
96756-2 | SARS-CoV-2 (COVID-19) S gene codon N501= [Presence]   in Specimen by Molecular genetics method | SEQUENCING
94307-6 | SARS-CoV-2   (COVID-19) N gene [Presence] in Specimen by Nucleic acid amplification using   CDC primer-probe set N1 | PCR_RT_PCR
94308-4 | SARS-CoV-2 (COVID-19) N gene [Presence] in Specimen   by Nucleic acid amplification using CDC primer-probe set N2 | PCR_RT_PCR
94309-2 | SARS-CoV-2   (COVID-19) RNA [Presence] in Specimen by NAA with probe detection | PCR_RT_PCR
94310-0 | SARS-like coronavirus N gene [Presence] in Specimen   by NAA with probe detection | PCR_RT_PCR
94311-8 | SARS-CoV-2   (COVID-19) N gene [Cycle Threshold #] in Specimen by Nucleic acid   amplification using CDC primer-probe set N1 | PCR_RT_PCR
94312-6 | SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in   Specimen by Nucleic acid amplification using CDC primer-probe set N2 | PCR_RT_PCR
94313-4 | SARS-like   coronavirus N gene [Cycle Threshold #] in Specimen by NAA with probe   detection | PCR_RT_PCR
94314-2 | SARS-CoV-2 (COVID-19) RdRp gene [Presence] in   Specimen by NAA with probe detection | PCR_RT_PCR
94315-9 | SARS-related   coronavirus E gene [Presence] in Specimen by NAA with probe detection | PCR_RT_PCR
94316-7 | SARS-CoV-2 (COVID-19) N gene [Presence] in Specimen   by NAA with probe detection | PCR_RT_PCR
94500-6 | SARS-CoV-2   (COVID-19) RNA [Presence] in Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94502-2 | SARS-related coronavirus RNA [Presence] in   Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94509-7 | SARS-related   coronavirus E gene [Cycle Threshold #] in Specimen by NAA with probe   detection | PCR_RT_PCR
94510-5 | SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in   Specimen by NAA with probe detection | PCR_RT_PCR
94511-3 | SARS-CoV-2   (COVID-19) ORF1ab region [Cycle Threshold #] in Specimen by NAA with probe   detection | PCR_RT_PCR
94532-9 | SARS-related coronavirus+MERS coronavirus RNA   [Presence] in Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94533-7 | SARS-CoV-2   (COVID-19) N gene [Presence] in Respiratory specimen by NAA with probe   detection | PCR_RT_PCR
94534-5 | SARS-CoV-2 (COVID-19) RdRp gene [Presence] in   Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94558-4 | SARS-CoV-2   (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay | RAPID_TEST
94559-2 | SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in   Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94565-9 | SARS-CoV-2   (COVID-19) RNA [Presence] in Nasopharynx by NAA with non-probe detection | PCR_RT_PCR
94639-2 | SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in   Specimen by NAA with probe detection | PCR_RT_PCR
94640-0 | SARS-CoV-2   (COVID-19) S gene [Presence] in Respiratory specimen by NAA with probe   detection | PCR_RT_PCR
94641-8 | SARS-CoV-2 (COVID-19) S gene [Presence] in Specimen   by NAA with probe detection | PCR_RT_PCR
94642-6 | SARS-CoV-2   (COVID-19) S gene [Cycle Threshold #] in Respiratory specimen by NAA with   probe detection | PCR_RT_PCR
94643-4 | SARS-CoV-2 (COVID-19) S gene [Cycle Threshold #] in   Specimen by NAA with probe detection | PCR_RT_PCR
94644-2 | SARS-CoV-2   (COVID-19) ORF1ab region [Cycle Threshold #] in Respiratory specimen by NAA   with probe detection | PCR_RT_PCR
94645-9 | SARS-CoV-2 (COVID-19) RdRp gene [Cycle Threshold #]   in Specimen by NAA with probe detection | PCR_RT_PCR
94646-7 | SARS-CoV-2   (COVID-19) RdRp gene [Cycle Threshold #] in Respiratory specimen by NAA with   probe detection | PCR_RT_PCR
94647-5 | SARS-related coronavirus RNA [Presence] in Specimen   by NAA with probe detection | PCR_RT_PCR
94660-8 | SARS-CoV-2   (COVID-19) RNA [Presence] in Serum or Plasma by NAA with probe detection | PCR_RT_PCR
94745-7 | SARS-CoV-2 (COVID-19) RNA [Cycle Threshold #] in   Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94746-5 | SARS-CoV-2   (COVID-19) RNA [Cycle Threshold #] in Specimen by NAA with probe detection | PCR_RT_PCR
94756-4 | SARS-CoV-2 (COVID-19) N gene [Presence] in   Respiratory specimen by Nucleic acid amplification using CDC primer-probe set   N1 | PCR_RT_PCR
94757-2 | SARS-CoV-2   (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid   amplification using CDC primer-probe set N2 | PCR_RT_PCR
94758-0 | SARS-related coronavirus E gene [Presence] in   Respiratory specimen by NAA with probe detection | PCR_RT_PCR
94759-8 | SARS-CoV-2   (COVID-19) RNA [Presence] in Nasopharynx by NAA with probe detection | PCR_RT_PCR
94760-6 | SARS-CoV-2 (COVID-19) N gene [Presence] in   Nasopharynx by NAA with probe detection | PCR_RT_PCR
94763-0 | SARS-CoV-2   (COVID-19) [Presence] in Specimen by Organism specific culture | CULTURE
94764-8 | SARS-CoV-2 (COVID-19) whole genome [Nucleotide   sequence] in Isolate or Specimen by Sequencing | SEQUENCING
94765-5 | SARS-related   coronavirus E gene [Presence] in Serum or Plasma by NAA with probe detection | PCR_RT_PCR
94766-3 | SARS-CoV-2 (COVID-19) N gene [Presence] in Serum or   Plasma by NAA with probe detection | PCR_RT_PCR
94767-1 | SARS-CoV-2   (COVID-19) S gene [Presence] in Serum or Plasma by NAA with probe detection | PCR_RT_PCR
94819-0 | SARS-CoV-2 (COVID-19) RNA [Log #/volume] (viral   load) in Specimen by NAA with probe detection | PCR_RT_PCR
94845-5 | SARS-CoV-2   (COVID-19) RNA [Presence] in Saliva (oral fluid) by NAA with probe detection | PCR_RT_PCR
95209-3 | SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in   Respiratory specimen by Rapid immunoassay | RAPID_TEST
95406-5 | SARS-CoV-2   (COVID-19) RNA [Presence] in Nose by NAA with probe detection | PCR_RT_PCR
95409-9 | SARS-CoV-2 (COVID-19) N gene [Presence] in Nose by   NAA with probe detection | PCR_RT_PCR
95425-5 | SARS-CoV-2   (COVID-19) N gene [Presence] in Saliva (oral fluid) by NAA with probe   detection | PCR_RT_PCR
95521-1 | SARS-CoV-2 (COVID-19) N gene [#/volume] (viral   load) in Respiratory specimen by NAA with probe detection | PCR_RT_PCR
95522-9 | SARS-CoV-2   (COVID-19) N gene [Log #/volume] (viral load) in Respiratory specimen by NAA   with probe detection | PCR_RT_PCR
95608-6 | SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory   specimen by NAA with non-probe detection | PCR_RT_PCR
95823-1 | SARS-related   coronavirus E gene [Presence] in Saliva (oral fluid) by NAA with probe   detection | PCR_RT_PCR
95824-9 | SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in   Saliva (oral fluid) by NAA with probe detection | PCR_RT_PCR
96091-4 | SARS-CoV-2   (COVID-19) RdRp gene [Presence] in Saliva (oral fluid) by NAA with probe   detection | PCR_RT_PCR
96119-3 | SARS-CoV-2 (COVID-19) Ag [Presence] in Upper   respiratory specimen by Immunoassay | ANTIGEN_DETECTION
96120-1 | SARS-CoV-2   (COVID-19) RdRp gene [Presence] in Lower respiratory specimen by NAA with   probe detection | PCR_RT_PCR
96121-9 | SARS-related coronavirus E gene [Presence] in Lower   respiratory specimen by NAA with probe detection | PCR_RT_PCR
96122-7 | SARS-related   coronavirus E gene [Presence] in Upper respiratory specimen by NAA with probe   detection | PCR_RT_PCR
96123-5 | SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Upper   respiratory specimen by NAA with probe detection | PCR_RT_PCR
96448-6 | SARS-CoV-2   (COVID-19) N gene [Presence] in Saliva (oral fluid) by Nucleic acid   amplification using CDC primer-probe set N1 | PCR_RT_PCR
96741-4 | SARS-CoV-2 (COVID-19) variant [Type] in Specimen by   Sequencing | SEQUENCING
96751-3 | SARS-CoV-2   (COVID-19) S gene mutation detected [Identifier] in Specimen by Molecular   genetics method | SEQUENCING
96752-1 | SARS-CoV-2 (COVID-19) S gene mutation [Presence] in   Specimen by Molecular genetics method | SEQUENCING
96763-8 | SARS-CoV-2   (COVID-19) E gene [Presence] in Respiratory specimen by NAA with probe   detection | PCR_RT_PCR
96764-6 | SARS-CoV-2 (COVID-19) E gene [Cycle Threshold #] in   Respiratory specimen by NAA with probe detection | PCR_RT_PCR
96765-3 | SARS-CoV-2   (COVID-19) S gene [Presence] in Saliva (oral fluid) by NAA with probe   detection | PCR_RT_PCR
96757-0 | SARS-CoV-2 (COVID-19) S gene codon N501Y [Presence]   in Specimen by Molecular genetics method | SEQUENCING
96755-4 | SARS-CoV-2   (COVID-19) variant interpretation in Specimen Narrative | SEQUENCING
96797-6 | SARS-CoV-2 (COVID-19) RNA [Presence] in   Oropharyngeal wash by NAA with probe detection | PCR_RT_PCR
96742-2 | SARS-CoV-2   (COVID-19) IgG Ab [Mass/volume] in Serum or Plasma by Immunoassay | IGG_SERUM_ANTIBODY
96603-6 | SARS-CoV-2 (COVID-19) S protein RBD neutralizing   antibody [Presence] in Serum or Plasma by Immunoassay | NEUTRALIZING_ANTIBODIES
94562-6 | SARS-CoV-2   (COVID-19) IgA Ab [Presence] in Serum or Plasma by Immunoassay | IGA_SERUM_ANTIBODY
94768-9 | SARS-CoV-2 (COVID-19) IgA Ab [Presence] in Serum,   Plasma or Blood by Rapid immunoassay | IGA_SERUM_ANTIBODY
95427-1 | SARS-CoV-2   (COVID-19) IgA Ab [Titer] in Serum or Plasma by Immunofluorescence | IGA_SERUM_ANTIBODY
94720-0 | SARS-CoV-2 (COVID-19) IgA Ab [Units/volume] in   Serum or Plasma by Immunoassay | IGA_SERUM_ANTIBODY
94761-4 | SARS-CoV-2   (COVID-19) IgG Ab [Presence] in DBS by Immunoassay | IGG_SERUM_ANTIBODY
94563-4 | SARS-CoV-2 (COVID-19) IgG Ab [Presence] in Serum or   Plasma by Immunoassay | IGG_SERUM_ANTIBODY
94507-1 | SARS-CoV-2   (COVID-19) IgG Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay | IGG_SERUM_ANTIBODY
95429-7 | SARS-CoV-2 (COVID-19) IgG Ab [Titer] in Serum or   Plasma by Immunofluorescence | IGG_SERUM_ANTIBODY
94505-5 | SARS-CoV-2   (COVID-19) IgG Ab [Units/volume] in Serum or Plasma by Immunoassay | IGG_SERUM_ANTIBODY
95416-4 | SARS-CoV-2 (COVID-19) IgM Ab [Presence] in DBS by   Immunoassay | IGM_SERUM_ANTIBODY
94564-2 | SARS-CoV-2   (COVID-19) IgM Ab [Presence] in Serum or Plasma by Immunoassay | IGM_SERUM_ANTIBODY
94508-9 | SARS-CoV-2 (COVID-19) IgM Ab [Presence] in Serum,   Plasma or Blood by Rapid immunoassay | IGM_SERUM_ANTIBODY
95428-9 | SARS-CoV-2   (COVID-19) IgM Ab [Titer] in Serum or Plasma by Immunofluorescence | IGM_SERUM_ANTIBODY
94506-3 | SARS-CoV-2 (COVID-19) IgM Ab [Units/volume] in   Serum or Plasma by Immunoassay | IGM_SERUM_ANTIBODY
95411-5 | SARS-CoV-2   (COVID-19) neutralizing antibody [Presence] in Serum by pVNT | NEUTRALIZING_ANTIBODIES
95410-7 | SARS-CoV-2 (COVID-19) neutralizing antibody [Titer]   in Serum by pVNT | NEUTRALIZING_ANTIBODIES
94661-6 | SARS-CoV-2   (COVID-19) Ab [Interpretation] in Serum or Plasma | ANTIBODY_DETECTION
95825-6 | SARS-CoV-2 (COVID-19) Ab [Presence] in DBS by   Immunoassay | ANTIBODY_DETECTION
94762-2 | SARS-CoV-2   (COVID-19) Ab [Presence] in Serum or Plasma by Immunoassay | ANTIBODY_DETECTION
94769-7 | SARS-CoV-2 (COVID-19) Ab [Units/volume] in Serum or   Plasma by Immunoassay | ANTIBODY_DETECTION
96896-6 | SARS   coronavirus 2 (COVID-19) clade [Type] in Specimen by Molecular genetics   method | SEQUENCING
96895-8 | SARS-CoV-2 (COVID-19) lineage [Identifier] in   Specimen by Molecular genetics method | SEQUENCING
96898-2 | SARS-CoV-2   (COVID-19) N gene [Cycle Threshold #] in Oropharyngeal wash by NAA with probe   detection | PCR_RT_PCR
96899-0 | SARS-CoV-2 (COVID-19) ORF1ab region [Cycle   Threshold #] in Oropharyngeal wash by NAA with probe detection | PCR_RT_PCR
95424-8 | SARS-CoV-2   (COVID-19) RNA [Presence] in Respiratory specimen by Sequencing | SEQUENCING
94822-4 | SARS-CoV-2 (COVID-19) RNA [Presence] in Saliva   (oral fluid) by Sequencing | SEQUENCING
96900-6 | SARS-CoV-2   (COVID-19) S gene [Cycle Threshold #] in Oropharyngeal wash by NAA with probe   detection | PCR_RT_PCR
95609-4 | SARS-CoV-2 (COVID-19) S gene   [Presence] in Respiratory specimen by Sequencing | SEQUENCING

**Comment by FredrikSchaeferVitagroup** [comment]
It seems that the testType is already migrated from the testReport to the pathogenTest. This is also present in unit tests, so no code changes should be necessary here on SORMAS side.

Because this ticket included some work (specification) and to get it tested, I will close this issue instead of discarding it.

**Comment by mario-kuehne** [comment]
First test in combination with https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/11

_Tested with_

- Sormas 50d3572f484550530a36db18f914f1536e85d302 (development branch)
- Sormas-Demis-Adapter a6518609c730e642e583a7c8dee4af87688a0c0a (feature branch)
- Demis-Adapter 2.0.1
- Demis-Importer 1.7.0
- Demis (Demis-Test_Environment Release 1.2.0)

_Test workflow_

- Put JSON into Demis-Adapter that contains specific test code (`erregerNachweise` -> `demisTestCode`). 
  - e.g.: 95209-3 
    - should be mapped to PathogenTest.testType `RAPID_TEST` (see mapping table https://github.com/hzi-braunschweig/SORMAS-Project/issues/5604#issuecomment-853091435)
    -  or `ANTIGEN_DETECTION` (see Mapping table https://github.com/hzi-braunschweig/sormas-demis-adapter/files/7985416/DEMIS2SormasMapping_220202_kwa.xlsx))
- Demis-Adapter sends notification to Demis Backend
- Fetch lab Messages in Sormas UI (e.g. as NatUser) so that Demis-Importer can fetch Demis notification and Sormas-Demis-Adapter converts notification into LabMessage
- Open fetched LabMessage to show details and check TestReport.testType by debugging (contains 'Antigen detection test (rapid test)')
- Process LabMessage -> Create case -> Create new sample => 'Type of Test' field is prefilled with 'Antigen detection test (rapid test)'

**Comment by mario-kuehne** [comment]
Retested in combination with [#11](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/11)

See https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/11#issuecomment-1033760344
