### ISSUE TITLE
Create and configure CI pipeline for performance testing - Jenkins integration

### ISSUE THREAD

**Issue by tamasvlad** [hzi-braunschweig/SORMAS-Project#5608]
### Problem Description
We want to create and configure CI pipeline for the available performance tests - Jenkins integration

### Proposed Solution
Create a dedicated Jenkins job for sormas-performance-tests

We need to install the following on the machine where this job will be executed:
- Java 11
- [Download and extract apache Jmeter binaries](https://jmeter.apache.org/download_jmeter)

Execution: (After build is completed and all functional tests are executed)
From the Jmeter bin folder execute the following from the command line:  jmeter -n -t PathToTheJMXFile\SormasPoc.jmx -l PathWhereTheResultsWillBeSaved\Results.csv -e -o PathToTheFolderWhereTheHtmlReportWillBeSaved

After execution is completed we want to be able to load the HTML Report located  PathWhereTheHtmlReportWillBeSaved/index.html

**Comment by StefanKock** [comment]
I was looking into running jmeter on Jenkins without the need to install JMeter on the host, but to provide it by Maven. Links:
- How to: http://www.testingdiaries.com/jmeter-with-jenkins/, https://blog.codecentric.de/2013/12/jmeter-tests-mit-maven-und-jenkins-automatisieren/
- Maven plugin: https://github.com/jmeter-maven-plugin/jmeter-maven-plugin
- Found problems: structure not prepared for Maven, Jenkins currently uses Maven 3.3.9 which is too old for current plugin version.

So for now, I will place JMeter manually on the host, looking into this guide whenever needed: https://www.jenkins.io/doc/book/using/using-jmeter-with-jenkins/

**Comment by StefanKock** [comment]
Installed JMeter on the Jenkins host:
```bash
cd /srv/dockerdata/jenkins_new/
mkdir jmeter
cd jmeter
wget https://ftp.halifax.rwth-aachen.de/apache//jmeter/binaries/apache-jmeter-5.4.1.zip
mv apache-jmeter-5.4.1 5.4.1
rm -f apache-jmeter-5.4.1.zip
cd ..
chown jenkins:jenkins jmeter
```

I created a [Jenkins job](https://jenkins.sormas.netzlink.com/job/sormas-RunE2ePerformanceTests/) as documented, but it fails:
```
Error in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'/srv/dockerdata/jenkins_new/workspace/sormas-RunE2ePerformanceTests/sormas-e2e-performance-tests/SormasPoc.jmx'. 
Cause:
CannotResolveClassException: com.tag.jmeter.ext.config.PropertyReader

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/com.tag.jmeter.ext.config.PropertyReader
line number         : 15
version             : 5.4.1
-------------------------------
An error occurred: Error in NonGUIDriver Problem loading XML from:'/srv/dockerdata/jenkins_new/workspace/sormas-RunE2ePerformanceTests/sormas-e2e-performance-tests/SormasPoc.jmx'. 
Cause:
CannotResolveClassException: com.tag.jmeter.ext.config.PropertyReader

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/com.tag.jmeter.ext.config.PropertyReader
line number         : 15
version             : 5.4.1
-------------------------------
```

**Comment by tamasvlad** [comment]
1. For Jenkins setup one more step need to be done in order to support parametrized execution:

- Download the property file reader external library from:
  [tag-jmeter-extn-1.1.zip](#https://www.vinsguru.com/download/87/?_ga=2.188716968.1652712557.1623012940-501989637.1623012940)
-  Place the downloaded jar in the JMETER_HOME/lib/ext foler.

2. Execution command line need to be updated in order to execute the desired scenario:
/srv/dockerdata/jenkins_new/jmeter/5.4.1/bin/jmeter -n -t SormasPoc.jmx -Jmodule=daily-build-scenario -l target/Results.csv -e -o target/report

**Comment by StefanKock** [comment]
Report is now generated, but `content-security-policy` rules block access within the Jenkins job workspace. Problem raised towards hoster.

**Comment by StefanKock** [comment]
Generated report is now accessible here: https://jenkins.sormas.netzlink.com/job/sormas-RunE2ePerformanceTests/ws/sormas-e2e-performance-tests/target/report/index.html

**Comment by StefanKock** [comment]
Open: Review the current state with @tamasvlad

1. Should we integrate it with the Performance Plugin?
2. How to we get comparison over several executions?
3. Maybe switch off "wipe out workspace" in Jenkins?

**Comment by StefanKock** [comment]
> 
> 
> Open: Review the current state with @tamasvlad
> 
>     1. Should we integrate it with the Performance Plugin?

Is now in use. Job gets now unstable if a test fails.

>     2. How to we get comparison over several executions?

Is provided by Performance Plugin, see https://jenkins.sormas.netzlink.com/job/sormas-RunE2ePerformanceTests/26/performance/ 

>     3. Maybe switch off "wipe out workspace" in Jenkins?

Performance results are possible either way.
