### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: Enable SORMAS to relate lab messages to each other [2]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5622]
### Situation Description

The new DEMIS profiles include a lifecycle management of DEMIS notifications (some overview of that is given in #5138). This means DEMIS notifications can soon relate to each other, for example one DEMIS notification can extend information from a previous one. Theoretically, this could possibly be handled by the current duplicate detections called when processing lab messages. For the processing user, it would be much more convenient (and less prone to errors), if SORMAS would propose 'shortcuts'.

For example, if there is a lab message that relates to another lab message already processed, the user should not need to go through the person, case/contact/event-participant, and sample selections. Instead, a popup could propose to directly go to the related sample. The user should be able to follow that proposal, or process the lab message the usual manual way.

### Feature Description

- [x] Add a String attribute called reportId to the lab message dto and entity. 
- [x] Lab messages related to each other should have the same reportId. This should be documented somewhere in the code.
- [x] Whenever a user starts processing a lab message, when this lab messages reportId is not null, SORMAS needs to automatically search for already processed lab messages with the same reportId. Therefore, provide an getByReportId(...) in the labMessageFacade.

### Additional Information

The demis-adapter needs to fill the new reportId attribute, probably with the Composition.identifier.value. The related adapter ticket is [#14](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/14).

**Comment by FredrikSchaeferVitagroup** [comment]
The problem with this approach is that lab messages relating to each other may also be intended to update person/case/contact/sample information.

**Comment by StefanKock** [comment]
Not mandatory for 1.62 and likely to interfere with other ticket(s)

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @Jan-Boehme Do we know the exact caption of this attribute in Demis? I had a look at the simplifier but could not really tell for sure how this Id is called. I suspect it to be the "Meldungsnummer" but translated the string as "Melde-ID" for now.
