### ISSUE TITLE
OPTION A: Report automatically to the reporting system when a case was sent to another instance of SORMAS [3?]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5630]
### Situation Description
Currently SurvNet is not informed, when a case was sent with the Sormas 2 SORMAS interface.
As this might lead to wrong numbers in the reporting system, we would need to inform Survnet about the status.
As we did when a case was deceased, we need to do it automatically, when a case was sent together with the ownership.

### Feature Description
With different events, we need to trigger automatically the SurvNet Converter to generate a transportfile, which can be read and imported in SurvNet

Accept Flow:
1. A case is sent from SORMAS A to SORMAS B
2. This case is in the state "pending" as long as SORMAS B did not accept or decline the transmission
3. The state pending has to be synched with SurvNet by triggering the converter with the information
4. Once the case was accepted by SORMAS B, SORMAS A sends the information "submitted" to SurvNet

Decline Flow:
1. A case is sent from SORMAS A to SORMAS B
2. This case is in the state "pending" as long as SORMAS B did not accept or decline the transmission
3. The state pending has to be synched with SurvNet by triggering the converter with the information
4. The transmission was declined by SORMAS B, SORMAS A triggers automatically the SurvNet Converter with the information to remove the state "pending" to SurvNet

### Additional Information
In the scope is just the send single and bulk action to send cases to another SORMAS Instance. Events of type cluster will be treated in another story

=> Should only be executed when the SurvNet Interface is configured

linked to:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4423 & 
 https://github.com/hzi-braunschweig/SORMAS-Project/issues/4119  
 
 Converter Ticket:
 https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/167

**Comment by Jan-Boehme** [comment]
@markusmann-vg  According to tests done by HZI and RKI if a case is sent to another instance via S2S which had been shared with the reporting tool before the converter automatically sends a discard request to the old survnet instance and the case then needs to be shared manually again on the "new" instance. This behaviour works as expected and means this issue can be closed, right?

**Comment by Jan-Boehme** [comment]
Closed this issue as it was implemented as described above
