### ISSUE TITLE
[Contacts][Edit][Performance Environment] Overwrtting followup does not save even when validated (only for automation)

### ISSUE THREAD

**Issue by Mihai-Bota** [hzi-braunschweig/SORMAS-Project#5634]
### Bug Description
This issue occurs in the https://test-performance.sormas.netzlink.com environment

### Steps to Reproduce
1. Create a contact than edit the contact. 
2. In the editing section check the "Overwrite follow-up until date" 
3. Update the FOLLOW-UP UNTIL * mandatory date box to a valid date (+15 days from current date)
4. Press the Save Button and receive an update notice "Contact data saved"
Actual Result:
FOLLOW-UP UNTIL * mandatory date box shall display the saved date.

### Expected Behavior
FOLLOW-UP UNTIL * mandatory date box shall be updated to the new added date

### Screenshots
![image](https://user-images.githubusercontent.com/46056983/120496512-4bf1a280-c3c6-11eb-840d-8c7aa7dddb4d.png)

### System Details

* Device: anything that supports web application, (e.g. windows OS, Google Chrome browser/Firefox/Edge)
* SORMAS version: 1.6-
* Android version/Browser:
* Server URL: https://test-performance.sormas.netzlink.com // performance environment
* User Role: any role that can create/edit contacts. I've used a national admin. Here is the URL (login with national admin). Notice that the URL could deprecate over time: https://test-performance.sormas.netzlink.com/sormas-ui/#!contacts/data/XBJLUP-OBS7UR-G55DGS-3NLSKP6Y

### Additional Information
![image](https://user-images.githubusercontent.com/46056983/120496512-4bf1a280-c3c6-11eb-840d-8c7aa7dddb4d.png)

**Comment by MateStrysewske** [comment]
Seems like this only occurs during automation tests, not when doing it manually. Moved to the next sprint because it shouldn't be a problem for production systems.

**Comment by syntakker** [comment]
@Mihai-Bota could not reproduce. Can you confirm the error still persists?
@MateStrysewske can you provide further information about the setting in which the error occurred for automation tests?

**Comment by MateStrysewske** [comment]
@syntakker Unfortunately not because I haven't tested it myself. Maybe @RazvanHodisan, @AndyBakcsy-she or @roxanamlendea could try it out again and check whether the problem still exists?

**Comment by syntakker** [comment]
@MateStrysewske I managaed to reproduce the problem. The cause seems to be that the followup status is `NO_FOLLOW_UP` and the end date to overwrite is cleared at some point, but not the checkbox.
I would assume it does not make sense to show the followup date fields, if there is no followup?

**Comment by roxanamlendea** [comment]
I couldn't reproduce it with covid19 selected as disease, but I could reproduce it with measles / anthrax / acute flaccid paralysis etc. selected.

**Comment by MateStrysewske** [comment]
@syntakker Showing the fields is fine - I guess the solution would then be to also clear overwriteFollowUpUntil when we clean the follow-up until date.

**Comment by syntakker** [comment]
@MateStrysewske currently the follow-up until date is reset upon saving for diseases that do not have a followup:
```java
		if (!diseaseConfigurationFacade.hasFollowUp(disease) || (contactProximity != null && !contactProximity.hasFollowUp())) {
			contact.setFollowUpUntil(null);
			if (changeStatus) {
				contact.setFollowUpStatus(FollowUpStatus.NO_FOLLOW_UP);
				statusChangedBySystem = true;
			}
		} else ...
```
The minimal solution would be to reset the checkbox, too (this has to happen either way):
```java
		if (!diseaseConfigurationFacade.hasFollowUp(disease) || (contactProximity != null && !contactProximity.hasFollowUp())) {
			contact.setFollowUpUntil(null);
			contact.setOverwriteFollowUpUntil(false);
			if (changeStatus) {
				contact.setFollowUpStatus(FollowUpStatus.NO_FOLLOW_UP);
				statusChangedBySystem = true;
			}
		} else ...
```
Then, however, it is possible to overwrite the follow-up until date (check the checkbox and enter date), but both inputs will be gone after saving (without explanation). I therefore would advocate to make these fields invisible if there is no follow-up.

**Comment by MateStrysewske** [comment]
@syntakker Fine by me :)

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com
