### ISSUE TITLE
Tasks > Task directory not displaying

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5636]
### Bug Description

An error message appears when opening Tasks. Similar behaviour to: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4634

### Steps to Reproduce

1. Open task directory

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/120503330-80b02a80-c3c3-11eb-8bb6-aa6ae3960c0c.png)

### System Details

* Device: PC
* SORMAS version: 1.59.2
* Android version/Browser: Chrome
* Server URL: test.sormas.ch
* User Role: admin, national user

### Additional Information

Logs from 25.05.2021:
[serverlog-25052021.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/6585454/serverlog-25052021.log)

NullPointerException in [ContactJurisdictionHelper.java:31](https://github.com/hzi-braunschweig/SORMAS-Project/blob/v1.59.2/sormas-api/src/main/java/de/symeda/sormas/api/utils/jurisdiction/ContactJurisdictionHelper.java)

**Comment by MateStrysewske** [comment]
@BarnaBartha Can you please check whether this is still a problem after your refactoring of the jurisdiction logic?

**Comment by BarnaBartha** [comment]
@MateStrysewske i have modified my db to contain a task with task context contact and no associated contact (as mentioned here https://github.com/hzi-braunschweig/SORMAS-Project/issues/4634#issuecomment-792730251) but the grid still works. Of course it works also if i do not manipulate the db. Should we check on that test system? Or do we have access to that db?

**Comment by MateStrysewske** [comment]
@BarnaBartha Based on the server logs and the associated code, to me it looks like `contactJurisdiction` is null when passed to ContactJurisdictionHelper; since you probably get rid of the code though (since jurisdiction checks are now done in the database), chances are that the bug no longer exists in the first place, that's why I was asking :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest deployed version of  SORMAS: 1.61.0-SNAPSHOT on test.sormas.netzlink.com
