### ISSUE TITLE
Setting a default country in sormas.properties should automatically create the country in configurations

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5641]
### Situation Description

Country was introduces in configuration. System allows only districts  in the  country  configured on the server to be imported on the server. This is validation is done based on the name of the country used to set the server. Since the user configuraing the system is not the user setting up the server, this makes it impossible to configure the system. Import template for district returned errors like `Invalid value  "Regionn Name" in column region; Region is not in server country`
### Feature Description

- When  a country is configured on the server (COUNTRY_NAME= NameOfCountry), then a corresponding country should be created in country configuration and tag as `server country`
-  Add a documentation in server setup to inform users that infrastructure data can be imported in server country only
-  Font end admins should be able to change the country name, thus validation can use but the country uuid to determine the server country.

### Possible Alternatives

System can force the user setting the server to also create a country for the server

**Comment by bernardsilenou** [comment]
I would add more information on how to reproduce the bug later today

**Comment by Candice-Louw** [comment]
@Juliane-D @bernardsilenou @stephaneghozzi - "Regionn Name" - is this correct? Is the error in the import file 'Regionn' instead of 'Region'?  Please attach the upload file you used when this bug occured to rule this out as a reason.

**Comment by bernardsilenou** [comment]
@Candice-Louw  It is just a place holder for the region name in the import template. We would get more information from netzlink tomorrow before knowing the next steps. For now, the district data has been imported. Thanks

**Comment by bernardsilenou** [comment]
Refinement continue in #5669
