### ISSUE TITLE
Suggestion: For statistics use only date of onset instead of falling back to date of report

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#565]
@hzi-braunschweig Please discuss
This would make it much clearer.
In addition a filter "show cases without onset date" would be added to the case directory.
Same for contact (last contact date)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Hey guys,  

I had a long discussion with Gerard about this and I think we have a solution to our problem. The following explains the process:
- [ ] The default for all data related to aggregate counts within SORMAS for the dashboard, epi curve and statistics should be epi week.
- [ ] This means that we need to add a select drop-down field for epi week of reporting during case creation which provides the date of report and "epi week of report" (from epi week 1-52).
- [ ] Users should be able to edit the "date of report" after the system automatically generates it. in addition to that, we need to allow users to select an epi week of report (required fields) during data entry especially for retrospective data entry with missing onset dates. 
- [ ]  This means that, epi week of reporting should be used when date of onset is missing which should be provided as required field.
- [ ] So for the **statistics**, We should be able to stratify and aggregate cases by week of report (default), month of report and by day of report (which shows only cases for which the date of onset is provided and shows as a disclaimer total number of cases within SORMAS by epi week of which XX cases by date of report. (Please use below for calculation as well as display on top of the statistics as a disclaimer)

**Week of reporting**
E.g Cases of "Diseases" in  "Region" or "District" from "epi-week" to "epi week" "Year": Total number of cases =300 by week of reporting

**Month of reporting**
E.g Cases of "Diseases" in  "Region" or "District" from "month" to "month", "Year": Total number of cases =300 by month of reporting

**Day of reporting**
E.g Cases of "Diseases" in  "Region" or "District" from "Day" to "Day","Month", "Year": **Disclaimer**: Total number of cases =**300**. Number of cases with date of report (complete date of onsets) =**250**
![image](https://user-images.githubusercontent.com/19344651/39364983-1f3e9562-4a30-11e8-951a-2680a6fb8d32.png)

This should also apply for the Maps
**Week of reporting**
E.g Cases of "Diseases" in  "Region" or "District" from "epi-week" to "epi week" "Year": Total number of cases =300 by week of reporting

![image](https://user-images.githubusercontent.com/19344651/39365043-53b551fa-4a30-11e8-8a0c-cac5e5b90cb8.png)

**Comment by MateStrysewskeSym** [comment]
Notes from discussion:

* report date should probably be renamed to creation date or system date
* a new field "report date" would then be needed
* creation date will no longer be used for statistics
* report week will be added as required field that has to be entered when creating a new case
* for statistics then use: onset date > report date > report week
* reception date can be prefilled with the report date

**Comment by MartinWahnschaffeSymeda** [comment]
See #890 and #891
