### ISSUE TITLE
Regionally restricted users cannot create case IDs from eps added by other users

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#5651]
### Bug Description
Regionally restricted users cannot convert event participant to cases if they are not the user that reported the respective event participant – the creation link is missing in the event participant table (empty field). This is also true for participants belonging to their responsible district but that have been added by another user. However, they are allowed to convert participants to cases who do belong to a different responsible district but have been added by themselves.

### Steps to Reproduce
1.	create event X as surveillance supervisor of district Y 
2.	add event participant 1 (first name, last name, no further info)
3.	add event participant 2 (first name, last name, responsible region/district Y)
4.	add event participant 3 (first name, last name, responsible region/district Z)
5.	log in as national user, go to event X and add event participant 4 (first name, last name, responsible region/district Y)
6.	log in as surveillance officer of district Y, go to event X and add event participant 5 (first name, last name, responsible region/district Y)
7.	try to convert the event participants to cases by clicking “create” in the event participant table/ column case ID
8.	result:
a) the surveillance officer only has a creation link for event participant 5 (added by himself), all other lines are empty – he cannot convert participant 1, 2 and 4 from his district to a case
b) the surveillance supervisor has a creation link for event participant 1, 2 and 3 but not participant 4 and 5 (both from his district but added by a different user; empty field); But he can convert participant 3 (different responsible district) to a case; if he clicks on create, a window opens “create new case” in which the region is reset from district Z to district Y (the district of the reporting user) – even if you chose “home” as place of stay
c) the national user has a creation link for all event participants

### Expected Behavior
Event participants should be able to be converted to a case depending on their regional affiliation/ A regionally restricted user should be able to convert event particpants to cases irrespective of the reporting user as long as the event participant belongs to his district.

### Screenshots

![image](https://user-images.githubusercontent.com/76884029/120623457-097ca400-c460-11eb-8830-89087b887d1f.png)
![image](https://user-images.githubusercontent.com/76884029/120623515-14cfcf80-c460-11eb-9399-9ed88dc8c5c4.png)
National user
![image](https://user-images.githubusercontent.com/76884029/120623553-1c8f7400-c460-11eb-8e26-a4a1c63db0a8.png)
Surveillance officer
![image](https://user-images.githubusercontent.com/76884029/120623577-22855500-c460-11eb-9b7b-486d6a881e85.png)
Surveillance supervisor
![image](https://user-images.githubusercontent.com/76884029/120623728-45176e00-c460-11eb-9465-dc6f9f812d62.png)

### System Details
Device: PC
* SORMAS version: 1.59.2 and 1.60
* Android version/Browser: Edge
* Server URL: test1401; public health agencies
* User Role: problem occurs e.g. with surveillance supervisor, surveillance officer, clinician, event officer, community officer or combinations such as surveillance officer+contact officer; 

### Additional Information
Bug was reported by three different public health agencies, all using SORMAS 1.59.2, Edge and combinations of different user roles such as: admin/contact supervisor/surveillance supervisor/ clinician or contact supervisor/import user/surveillance supervisor/clinician
This bug is related to Github issue  #4965
And partly to #5494 and #4260

**Comment by kwa20** [comment]
Further information
- Event participant jurisdiction does not seem to be taken into consideration for pseudonymization: If event region equals jurisdiction of user, event participants with differing jurisdiction can still seen by users without being the reporting user
- Even if the jurisdiction of the event participant equals the users jurisdiction, conversion to cases is not possible when reporting user differs from the current one

**Comment by RazvanHodisan** [comment]
Verified on test.sormas Version: 1.62.0-SNAPSHOT
