### ISSUE TITLE
Disease variants are not correctly converted to customizable enums

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#5652]
### Bug Description
The script to migrate disease variants to customizable enums is not correctly converting the `name` to `value` since it's not replacing all the white spaces to `_`.

The reason for this is because the expression `UPPER(REGEXP_REPLACE('this has multiple spaces', ' ', '_'))` it's only replacing the first occurrence of a white space because it's missing the optional `'g'` flag as the 4th parameter.
It should be `UPPER(REGEXP_REPLACE('this has multiple spaces', ' ', '_', 'g'))`.

### Expected Behavior
The disease variants in customizableenums have all white spaces replaced by `_`.

This has to either be adjusted in the `sormas_schema.sql` script or trough a custom script which can be used to fix this.

### System Details
* SORMAS version: 1.60.0

### Additional Information
See https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/147#issuecomment-853726455 for more info.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment
