### ISSUE TITLE
Change the responsible officers in cases and contacts to be a responsible user instead

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5656]
### Feature Description

Cases / Contacts > Responsible Surveillance / Contact Officer
### Problem Description

Thus far, only officer user roles can be assigned to cases and contacts. Furthermore, these responsible users are also automatically set during the creation and changed if jurisdictions or sometimes even locations are changed. This causes all sorts of problems from tasks being randomly assigned to someone else and responsible users changing without people noticing.

Considering the upcoming changes in the user management (cf. #898 and subsequent issues), officer roles will also likely not stay consistent throughout many different instances. Especially localized systems often require divergent configurations to the default user roles which are currently in place.
### Proposed Change

To accommodate different needs in association to the user management and assigning users responsibilities, change the responsible officer fields in cases and contacts in the following way:
- Rename the field 'Responsible User'
- Make it possible to assign any user that has full access to the respective entity to be the responsible user, independent of a specific user role
- Make the automated filling of this field upon entity creation or edits configurable
    - if turned off, the 'Responsible User' field should not be filled unless a user actively assigns a user 
- limit the selection of users to active users and exclude the inactive ones
- If the case or contact is edited in a way so that the responsible user would lose access to this entity, prompt the editing user about the consequences and give them the option to either proceed or discard the changes. 

**Implications on user management**

- When a user is turned inactive and is still assigned to active cases or contacts, prompt the admin and show a list of the respective entities in a pop-up window. Give them the option to 
    - either bulk reassign the entities to another active user (radio button - if clicked, show responsible user drop-down with user options that have access to all respective entities)
    - Proceed without reassigning
    - Cancel the process of de-activation
    - Export the list of associated entities (should be executable independent of the other actions)
- When users are turned inactive via bulk action and some included users are assigned to active entities, prompt the admin with a pop-up that informs that about the number of users that are still assign to active entities
    - Display the list of users that are still assigned to active entities and give the admin options to either
    - Proceed without reassigning
    - Proceed but exclude the listed users from de-activation
    - Cancel the entire bulk action
    - Export the list of users (should be executable independent of the other actions)

**Comment by bernardsilenou** [comment]
additional comment on how responsible user can be sampled:
- In the district of the entity, system randomly choose with replacement among surveillance officers each time a new entity is created either manually or imported. If there is only one surveillance officer, then this user is chosen all the time.
- If there is no surveillance officer, it randomly choose among surveillance supervisors in the region of the entity.
- Users can then manually reassign it to any surveillance officer or supervisor in the region of the entity.

**Comment by StefanKock** [comment]
It needs at least do be considered that a distinct user right needs to exist to define users that are allowed to be assigned as responsible user (that's what the OFFICER is currently for).

**Comment by MartinWahnschaffe** [comment]
Implementation is part of #2804
