### ISSUE TITLE
Missing fields from Contact view for contacts created from Cases contacts tab

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#5658]
**Description:**
Disease of source case, Case ID in external system and Case or event information fields are missing from Contacts create/edit page for Contact created from Cases.

Steps to reproduce:
1. Go to Cases
2. Open any existent Case
3. Navigate contacts tab
4. Create new Contact
5. View created contact from Contacts 

**Expected results:**
Contact page should have all fields
**Actual results:**
Disease of source case, Case ID in external system and Case or event information fields are missing

Screenshots:
![contact from cases](https://user-images.githubusercontent.com/83643843/120665307-52e6e680-c494-11eb-8882-7ec28564d408.PNG)
![created contact](https://user-images.githubusercontent.com/83643843/120665335-58dcc780-c494-11eb-913a-f66804deffe0.PNG)

Environment: 
https://test-performance.sormas.netzlink.com/
Browser:
Chrome

**Comment by MateStrysewske** [comment]
@rdutu-vg That is intended behaviour. Those fields are only relevant if no source case has been selected.
