### ISSUE TITLE
When logging out with 2 tabs open, you can't log back in

### ISSUE THREAD

**Issue by georgeginguta** [hzi-braunschweig/SORMAS-Project#5660]
### Bug Description

When you are logged in and have 2 tabs open with the same application, and you log out from one, you can't log back in as you can only see a white screen.
### Steps to Reproduce

1. Login with NatUser (tab 1)
2. Open a second tab (tab 2) to the same address and log out from this tab
3. Try to login with a wrong login in tab 2 (eg: username: admin: password: wrong_password)
4. Go back to the first tab (tab 1) and try to click on Cases, as expected you will not be able to.
5. Try to login back in tab 1 with an existing user.

### Expected Behavior

When accessing the link again, you should be able to login

### System Details

* Device: Web
* SORMAS version: 1.60.1 Snapshot
* Android version/Browser: Firefox or Chrome
* Server URL:  https://test-performance.sormas.netzlink.com/ or https://test.sormas.netzlink.com/
* User Role: NatUser

### Additional Information

You can log back in after you delete the cookie for this address

**Comment by StefanKock** [comment]
I don't see this ticket valid. After doing one of this three actions after the communication error pops up, I was able to re-login properly.
- Click on communication error popup
- Click on _Logout_
- Refresh page (F5)

![grafik](https://user-images.githubusercontent.com/24678567/121142363-33591080-c83c-11eb-9a1d-13a234dea845.png)

And if it is valid in some edge cases, I consider the severity quite low.

**Comment by MateStrysewske** [comment]
@StefanKock Agreed
