### ISSUE TITLE
New disease variant system erroneously  displays cases with disease variants as being changed / needing to be sent to survnet again

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#5662]
### Bug Description
The migration of disease variants for cases to the new customizable enums updates the change date of the affected cases.
As a result those cases are shown on the case directory when filtering by cases that have changes not yet sent to survnet.

The idea of setting the change date is probably to trigger a sync to the mobile app. From my understanding this is not needed here, because the mobile app is doing a migration on it's own.

### Suggested change

- [ ] Don't update the change date during the SQL migration of this

This needs to be tested by rolling back to a previous version, creating a few cases with disease variants, synchronizing them to the android app and then doing the migration.

**Comment by vidi42** [comment]
@BarnaBartha If this ticket requires the update on `sormas_schema.sql`, can you also consider adjusting for this https://github.com/hzi-braunschweig/SORMAS-Project/issues/5652?

**Comment by DavidBaldsiefen** [comment]
@BarnaBartha @ChristopherRiedel 
Can this ticket be closed?

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment setup using 1.60.0 build and migrating to 1.61.0-snapshot (latest version)
