### ISSUE TITLE
country.name does not consider all deposited formats deposited in country infrastructure data

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5669]
### Bug Description

when defining a country.name in the properties, only specific formats can be read. This is a problem when countries are missing in the standard import (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4782#issuecomment-801263814) or were generally added to the list. These countries, to count as the server country, need to be set according to the deposited value. However, the properties file does not allow spaces, quotations marks, apostrophes or special characters. This leads to country names having to be adjusted in undesired ways in order to allow importing of districts.
### Steps to Reproduce

1. Add "Côte d'Ivoire" as a country in configurations
2. Set country.name="Côte d'Ivoire"
2. Import regions and districts. (Only the district import should through an error saying that the region is not in server country.)
3. Change the country name to "Cote_dIvoire" in configurations
4. Set country.name=Cote_dIvoire
5. Import districts again

### Expected Behavior

Any deposited country should be able to be set as country.name and still maintain its proper caption
### Screenshots

<img width="599" alt="IvoryCoastProperties" src="https://user-images.githubusercontent.com/70317594/120790990-e7545600-c533-11eb-951f-e250a0954f49.PNG">

### System Details

* Device:
* SORMAS version: 1.58.3/1.60
* Android version/Browser: firefox
* Server URL: https://test-inhp-ci.sormas.netzlink.com/
* User Role: admin, national user

### Additional Information

tested country.name options

|country.name|result|
|:--------------|:------|
"Côte d'Ivoire"|fail
Côte d'Ivoire|fail
Ivory Coast|fail
Ivory_Coast|success
Côte_d'Ivoire|fail
Côte_dIvoire|fail
Cote_dIvoire|success
"Ivory Coast"|fail

error report:
[sormas_import_error_ivorycoast(1).txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6597996/sormas_import_error_ivorycoast.1.txt)

district import template:
[sormas_import_district_template_ivoryCoast(1).txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6598051/sormas_import_district_template_ivoryCoast.1.txt)

### Possible solutions
[These should merely be suggestions with the limited knowledge I have about the technical details]

- Allow text in between "" to be read in the properties file
- Add country references to lower hierarchy infrastructure (might also have the advantages that these hierarchies can be imported at all for other countries then set in country.name)
- restructure infrastructure so that each line has its own value independent of the name which then will be used as a caption. E.g. when creating an entry for Côte d'Ivoire, the entry produces a value that conforms to the needed format COTE_DIVOIRE and would then be referenced in the properties file.

**Comment by kwa20** [comment]
@bernardsilenou @Juliane-D here the bug report for the ivory coast issue.

@MartinWahnschaffe @Candice-Louw @T-Hundt for your information.

**Comment by bernardsilenou** [comment]
@kwa20  I would vote for the option to not use the name of  server country but a some form of a code; So when server is initialize, there is a code assign to the server country + country created as a country in the system. If user then change the name of the country, then code  is not changed.
When importing data or using other logics, we then compare with the uuid of the server country rather than the name.

**Comment by MartinWahnschaffe** [comment]
Looks like we have to make sure the country name also supports white spaces and other signs and/or is validated if there are good reasons to not allow this.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe @kwa20 
The same error also occur when importing facilities. `Invalid value ABIDJAN 2 in column region; Region is not in server country` even after importing region as a region in server country. 
What about adding a colum on infrastructure data import template to specify the uuid of the country and use this uuid in all logics. The logic to map the facilities to their country seam not to be working well.

**Comment by bernardsilenou** [comment]
@kwa20  A short term solution can be to set the country name to just a string "CoteDivoir", and rename the country name in the regions data, maybe this may help to allow us import facilities.

**Comment by StefanKock** [comment]
`country.name` is used for technical selection in code but also shown to the user, it's likely we need to seperate this. Needs to be looked into and specified

**Comment by kwa20** [comment]
@MartinWahnschaffe I guess another problem that occurs at the same time is that no infrastructure data below the region hierarchy can be imported for any other countries besides the deposited server country right? I'm not sure if we can account for that by allowing the country.name to allow additional formats.

**Comment by MateStrysewske** [comment]
@kwa20 No, that shouldn't be a problem. If you have a region associated to a different country, you should be able to import districts for that region.

@MartinWahnschaffe @StefanKock Is it difficult to "simply" allow whitespaces for the country.name property? That would indeed be (by far) the best solution in my eyes. Also, this is a critical bug that needs to be resolved in the upcoming release.

**Comment by kwa20** [comment]
@MateStrysewske when I try importing data for a region in a different country I get this error message. Do you know what the reason for this could be?

[test_import_districts_otherCountries_Error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6655145/test_import_districts_otherCountries_Error.txt)

**Comment by MateStrysewske** [comment]
@kwa20 Ooh, okay, I see - looks like we disabled it then. Can't tell why though... @MartinWahnschaffe Do you recall anything related to this?

**Comment by StefanKock** [comment]
I defined `country.name=Bundesrepublik Deutschland` in sormas.properties, that was correctly read into SORMAS:
![grafik](https://user-images.githubusercontent.com/24678567/122047570-97ea1180-cde0-11eb-803e-4bebe6f21d42.png)

When taking the given in example `Côte d'Ivoire` in UTF-8 encoding it fails:
![grafik](https://user-images.githubusercontent.com/24678567/122048116-2e1e3780-cde1-11eb-8a82-ab4c5da2b432.png)

When making sure that `sormas.properties` is written in ISO-8859-1/ANSI it works:
![grafik](https://user-images.githubusercontent.com/24678567/122049633-eef0e600-cde2-11eb-8721-e2fa58eb1b35.png)

For me it looks more like an encoding problem. Some research showed that [from JDK 9 on, the encoding is UTF-8 per default, but has a fallback](https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm#JSINT-GUID-974CF488-23E8-4963-A322-82006A7A14C7). [Here](https://en.wikipedia.org/wiki/.properties#cite_note-1) is a statement, that encoding special characters as `\uHHHH` helps encode characters in an ISO-8859-1 encoded file.

**Comment by leventegal-she** [comment]
Implemented a hot fix + opened https://github.com/hzi-braunschweig/SORMAS-Project/issues/5821
