### ISSUE TITLE
DOCUMENT format is not working

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#5674]
### Steps to Reproduce
When trying to format the Month of a person with '\# "00" ', it is not working. It will display: '9 \# "00".' (when the month is september)

### Expected Behavior
The month should display: 09

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF Can you add a few more details to this issue please? Which section of the app does it affect in particular (since we have multiple document sections)? Can you please attach a screenshot showing the problem?

**Comment by MateStrysewske** [comment]
Closed because there hasn't been any update since June.
