### ISSUE TITLE
Computation of cases in quarantine and cases placed in quarantine: refinement

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#5677]
### Bug Description

#3004 updated the logic in computing the indicators on the surveillance dashboard. However is is not clear how the indicators: cases in quarantine or placed in quarantine are computed. Did not look at the code but the results shows that previous logic is still being used.
### Steps to Reproduce

1. Select a specific week and create cases
2. Set some of this cases in quarantine. For some give a start end end date and for others give not date
3. Go back to the dashboard and check if counts matches what you expected

### Expected Behavior

Suggested change
-   Case is quarantine  = cases returned by filters (ie New cases) | Condition that quarantine start and end date fall in the interval (including end dates) of the date( from, todate) specified by user. Ie count of subset of New cases for which this condition is true.
- Cases placed in quarantine =  New cases | Condition that quarantine start == current system date (current calendar date no matter the date filter supplied by user)
### System Details

* Device:
* SORMAS version: 1.60.1
* Android version/Browser:
* Server URL: My local system
* User Role: admin + national user

**Comment by bernardsilenou** [comment]
@kwa20 @VitaliHZI @JaquM 
 - Since this is an old bug, then its not necessary to be considered as a bug for 1.60.1

**Comment by MateStrysewske** [comment]
@bernardsilenou I don't really agree with your suggested changes. I think the logic is working as intended:

* "Cases in quarantine" counts all cases among the new cases that have been in quarantine in the specified time frame
* "Cases placed in quarantine" counts all cases among the new cases where the quarantine start date lies within the specified time frame

**Comment by bernardsilenou** [comment]
@MateStrysewske I think both options are right, just different definitions of `Placed in quarantine`
When you say "`cases that have been in quarantine`, I understand it as either start or end date of quarantine fall in the specified time frame. Is this right?
My understanding was that the users wanted to know the number of cases placed in quarantine on daily bases, but this may be wrong.

Based on your definition, I do not understand why both indicators are needed since the denominator are cases occurring in the time interval, a case can not be in quarantine before they become cases.

@kwa20 @JaquM  
Please can you give some definitions of these indicators and how users are using it?

**Comment by MateStrysewske** [comment]
@bernardsilenou Cases can definitely be in quarantine before they become cases, e.g. because they were a contact before or they were routinely placed in quarantine because they were a returning traveler, so the two variables are semantically different. It's also possible that a case is only put in quarantine a week or so after they were recorded as a case (for whichever reason, might depend on the disease, or maybe the note to get in quarantine was sent too late). In both cases, the two numbers would differ from each other. If people want to find out how many cases were put into quarantine at a specific date, they can filter the dashboard by that date and look at the "cases placed in quarantine" value.

**Comment by bernardsilenou** [comment]
@MateStrysewske  I also agree with this https://github.com/hzi-braunschweig/SORMAS-Project/issues/5677#issuecomment-861485158 . 
The only point that is not still not clear to me is that we conditioned the denominator of the counts on dashboard to be based on New cases only. So things that happen before this time does not count.
Please can I call you after the sprint ?

**Comment by MateStrysewske** [comment]
Exactly, the data only considers the cases that were created in the specified time frame. And yes, sure.
