### ISSUE TITLE
Confirmed cases without or unknown symptoms are displayed as healthy on the network diagram

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5678]
### Bug Description

Confirmed cases without or unknown symptoms are displayed as healthy on the network diagram.
### Steps to Reproduce

1. Create confirmed cases with unknown or without symptoms
2. Check the network diagram

### Expected Behavior

Confirmed cases without symptoms or unknown symptoms should also be displayed like other confirmed cases. Otherwise, introduce new colours for asymptomatic cases and cases with unknown symptoms.
### Screenshots

<img width="803" alt="networkdiagramError" src="https://user-images.githubusercontent.com/70317594/120817700-390bd900-c552-11eb-9ff3-64edb49acd20.PNG">
<img width="361" alt="networkdiagramError2" src="https://user-images.githubusercontent.com/70317594/120817706-3ad59c80-c552-11eb-877c-613e2410c732.PNG">

### System Details

* Device:
* SORMAS version: 1.59.2/1.60.1
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by DavidBaldsiefen** [comment]
Is there any notable benefit to differentiating between symptomatic and asymptomatic cases based on the color/icon? If not I would just display them identically, as more colors/icons might make the network diagram less clear/readable

**Comment by kwa20** [comment]
@DavidBaldsiefen I think it could be nice to have it consistent with how it is displayed on the dashboard in different shades of red. If that is not feasible I'd say red very much suffices.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS: 1.61.0-SNAPSHOT on test.sormas.netzlink.com
