### ISSUE TITLE
SormasToSormasRestClient should handle authentication automatically

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#5679]
### Problem Description

This is a spin off from #5599, I want to keep the PRs small and easy to review.

While working on #5597, I noticed a lot of potential for code cleanup and deduplication which once resolved would make my life easier.

### Proposed Change

`SormasToSormasRestClient` puts the burden of providing the correct authorization header for the S2S request on the developer at the call site. With the token based approach around the corner, we just want to call the REST API without worrying about the underlying details. Further, the certificate based S2S approach will also talk to an endpoint of S2S, which is yet another call side that has to take care of running authentication correctly. 

Clearly, this introduces code duplication around a security critical feature which we should avoid.

---

First try: #5693 (closed)
First part: https://github.com/hzi-braunschweig/SORMAS-Project/pull/5697
Second part: #5724

**Comment by leventegal-she** [comment]
Accept/reject functionality has broken
