### ISSUE TITLE
Differenciate strings for confirmed cases and confirmed contacts on dashboard

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5685]
### Feature Description

Dashboard captions for confirmed cases and confirmed contacts.
### Problem Description

The dashboard uses the same string to display confirmed cases and contacts. This is a problem because in some languages, case classification 'confirmed' and confirmed contact do not have the same translation.
### Proposed Change

Split the strings for confirmed cases and confirmed contacts on the dashboard in order to allow differing translations.
### Additional Information

<img width="353" alt="confirmedDashboard" src="https://user-images.githubusercontent.com/70317594/120979683-2245cc00-c776-11eb-8c23-78e4a9fdc976.PNG">
<img width="260" alt="confirmedDashboard2" src="https://user-images.githubusercontent.com/70317594/120979688-2376f900-c776-11eb-8e52-84d29a68f265.PNG">

**Comment by StefanKock** [comment]
I added this to the current sprint, becaused it already caused problematic translations.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of  SORMAS Version: 1.61.0-SNAPSHOT on test.sormas.netzlink.com environment.
