### ISSUE TITLE
Configurations > Countries > Sub-continent association change DE [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5689]
### Feature Description

In the countries list (Configurations > Countries >), Germany is currently associated with the sub-continent of Western Europe.  This should be Central Europe instead.

### Problem Description

After introduction of https://github.com/hzi-braunschweig/SORMAS-Project/issues/4782, sub-continents were associated with countries.  Germany should fall under Central Europe.

### Proposed Change

Change Germany sub-continent association to Central Europe i.e.

defaultName | externalId | isoCode | unoCode | archived | subContinent
-- | -- | -- | -- | -- | --
Germany | 8207 | DEU | 276 | FALSE | Central Europe

### Additional Information

Please migrate existing entries to update the sub-continent automatically to 'Central Europe' if the country 'Germany' was selected in existing data.  This would be applicable to locations and addresses pertaining to facilities, exposures (epi data) etc. where the entries may already have been used in connection with one another.

SurvNet Converter team (if applicable to mapping change):
CatalogueName | UseShortName | IsHierarchical | IdItem | ItemName | ISO | Sort | IdCatalogue2Item | IdCatalogue | IdParent | IdIndex | IsDeleted | Schema2 | Schema3 | ChangeStatus | Schema4 | Schema5 | Schema6 | Schema7 | Schema8 | English
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
World | 0 | 1 | 41000001 | Europa | EUR | 2990 | 17001 | 1025 | 0 | 31000003 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | Europe
World | 0 | 1 | 41000008 | Mitteleuropa | &nbsp; | 2991 | 17008 | 1025 | 17001 | 41000008 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | Central Europe
World | 0 | 1 | 10100017 | Deutschland | D | 0 | 20422 | 1025 | 0 | 21000109 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | Germany

Connected to (prefereable to be done at same time as):
https://github.com/hzi-braunschweig/SORMAS-Project/issues/5680 and #5774

**Comment by markusmann-vg** [comment]
Deliverable:
- Change the association in the SORMAS UI / DB
- Provide a script to be able to migrate

**Comment by MateStrysewske** [comment]
* Change association in `sormas_import_all_countries.csv`
* If the entry exists in the database (check by matching ISO code), change the association of the country in the database
* Change the subcontinent (and subsequently continent) ID in every location entity that references the country
