### ISSUE TITLE
Error on the dashboard when selecting dead or alive filter.

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5698]
### Bug Description
When  I select the filter dead or alive the following error occurs.

### Steps to Reproduce

1. Go to the dashboard.
2. Select Covid-19
3. Set the filter to Alive or Dead

### Expected Behavior
For the rest of the diseases the following error doest not occur, only for Covid-19

### Screenshots
![image](https://user-images.githubusercontent.com/53563072/121128462-19b3cb00-c834-11eb-9219-9e5d17d24816.png)

### System Details

* Device:
* SORMAS version: 1.61.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL:https://test.sormas.netzlink.com/
* User Role: NatUser

**Comment by MateStrysewske** [comment]
@RazvanHodisan Can you please request error logs for this? We need them to be able to reproduce this bug.
