### ISSUE TITLE
Always allow app start when an older but compatible version is installed

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#570]
It may be necessary to install an old, but compatible app version, especially for the transition to the new app design.

**Comment by MartinWahnschaffeSymeda** [comment]
Scenarios:

1. Trying to connect (whenever data is exchanged) with incompatible version 
-> ask for update
  a) User updates -> everything is fine
  b) User is logged in and cancels -> allow offline usage
  c) User is not logged in and cancels -> close app
2. On app start wit compatbile but old version 
-> ask for update
  a) User updates -> everything is fine
  b) User cancels -> everything is fine
