### ISSUE TITLE
Reports of the discarded case are not added to the merged case 

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#5706]
### Bug Description

Reports of the discarded case are not merged with the remaining case regardless of the type of reporting. 
### Steps to Reproduce

1. Create two Cases with a similar name, same date of birth and same sex
2. Add different reports to the cases 
3. Merge the cases 

### Expected Behavior

Reports from the discarded case, should be visible in the Report section of the merged case 
### Screenshots

Case 1: Remaining case (hospital and doctor report) 
![image](https://user-images.githubusercontent.com/83459190/121162671-6a382200-c84e-11eb-9616-846bfea20a39.png)

Case 2 : Discarded case (forwarding and community facility report) 
![image](https://user-images.githubusercontent.com/83459190/121163046-c0a56080-c84e-11eb-9479-ddbaa1ed539b.png)

Merged case: Reports of case 2 are missing 
![image](https://user-images.githubusercontent.com/83459190/121163796-5f31c180-c84f-11eb-9194-09f26712fe3c.png)

### System Details

* Device:
* SORMAS version: 1.59 / 1.60 
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de
* User Role: Admin, National user

**Comment by RazvanHodisan** [comment]
Verified on https://test-de.sormas.netzlink.com/ Version: 1.61.0-SNAPSHOT
