### ISSUE TITLE
[Angular] Selected menu button should remain selected if you enter case profile or etc [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5709]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Selected menu button should remain selected if you enter case profile or etc. + in case profile, the selected tab should be highlighted
- Please consider menu / sub-menu for Case

Note: This should work for all such occurrences (not just the mentioned ones).

### Possible Alternatives

N/A
### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review - Done - for the Case tabs there are some inconsistencies with the UI that Adrian will fix in a new task (link to be added after the task is created)
