### ISSUE TITLE
[Angular] Therapy tab: Search and Sorting (on the case entity) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5711]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKEW80n
- The sorting and filtering will be done on the FE side without the BE
_- TBD: When searching by string, whenever you write something, only the items that include the searched item should be displayed (after the third key with a time-out of a couple of ms's)._

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
