### ISSUE TITLE
[Angular][Backend] Therapy tab: provide therapies based on the therapy ID [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5712]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKEW80n
- The endpoint should return an array for: "Prescriptions" and "Treatments"

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by marius2301** [comment]
I made an endpoint to return treatments and one to return prescriptions using the existing   treatmentCriteria and prescriptionCriteria which have a therapy uuid not a case uuid. I think we need the therapy uuid.
