### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: Automatically propose to correct entities related to a reportId [5]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5714]
### Situation Description

With the new DEMIS profiles, it becomes possible to send correction of data previously sent via DEMIS notifications. As a user, I want to be able to process this correction in SORMAS. I want to do this with as few clicks as possible while always seeing the relevant data for making decisions about which values are the correct ones to save and how to proceed processing lab messages.

### Feature Description

Preriquisite: #5622 , #5539, #5713

When a user starts processing a lab message, SORMAS should check if there are already processed lab messages with the same reportId. If there are any, SORMAS should (1.) determine the related person, samples and pathogenTests and (2.) try to closer relate them to the lab message currently to be processed. 
About (1.): Pathogen tests associated to the reportId are stored in processed lab messages. Samples related can be found through those pathogen tests. Persons can be found via the cases /contacts /event participants related to those samples. There should always just be one person related to one reportId. 
To (2.) closer relate one sample to the currently to be processed lab message, SORMAS should check if one of the found sample's labSampleId is identical to the labMessage's labSampleId. This would indicate a close relation. To closer relate pathogen tests to the lab message, SORMAS should compare the pathogen tests externalId to the test results externalId.

When entities with a close relation according to (2.) are found, SORMAS should check whether there are differences between values in the entities and values in the lab message. This would indicate that there are corrections transmitted via DEMIS.

When there are differences found, show a panel with two forms for the changed entity, side by side. The left one with the caption "Previous [Entity] Information" (e.g. Previous Person Information) and all fields disabled. None of the fields should be highlighted, they should all have the same frame color.
The right one with the caption "Updated [Entity] Information" (e.g. Updated Person Information) and all fields editable. None of the fields should be highlighted (with darker blue frame), except the ones changed. When the user edits a fields, it should become highlighted. When the user reverts changes in a field, it should become non-highlighted.

![Entity_correction](https://user-images.githubusercontent.com/67001822/121135976-61872200-c835-11eb-8ac9-9227c0d1dbca.png)

At the bottom of the panel, there should be 4 buttons: `CANCEL`, `DISCARD ALL AND CONTINUE`,  `SAVE AND CONTINUE` and `VIEW LAB MESSAGE` (use the info icon as in other places).
`CANCEL` should cancel the lab message processing, `DISCARD ALL AND CONTINUE` should leave the entitiy as shown on the left hand side form and either continue with the next changed entity (if any) or with processing new entities to be created for the lab message (if any, e.g. new PathogenTests). `SAVE AND CONTINUE` should save the entitiy as shown on the right hand side form and either continue with the next changed entity (if any) or with processing new entities to be created for the lab message (if any, e.g. new PathogenTests).
`VIEW LAB MESSAGE` shows the Lab message notification HTML.

If instead nothing is there to continue with, a windows should show asking "No other new or changed information could automatically be determined from the lab message. Do you want to manually add or edit more information? Left of that question, the HTML representation of the lab message should show, so that the user can decide based on the lab message information. The user should have the option to go back to the previous window, choose `NO` and `YES`. If the user chooses `NO`, the processing should be finished, setting the labMessageStatus to `PROCESSED`. If the user choses `YES`, the user should be directed to the (already existing) pick or create entity window for chosing a case, contact or event participant.

When any panel is too big to fit the users screen, it must be scrollable horizontally and/or vertically.

### Possible Alternatives

Suggestions welcome!

### Additional Information

To reach this UI #5729 has to be started first

**Comment by FredrikSchaeferVitagroup** [comment]
Additionally, add the eye icon to view the lab message (as in the directory).

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
