### ISSUE TITLE
[Angular] On the case page, on the right sidebar display: Events , Samples, Tasks [8]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5715]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/4a2zPwA
- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/93425D81-F862-4DC7-979D-DF3731385D9E
- Note: We will implement only the first three sub-sections: Samples, Events, Tasks
- Note: This should have a base component that takes care of all of the functionalities. Each section should be exapandable only resolutions lower than (840px)
- Note: We need to investigate on / if how we can retrieve the required content (example: for tasks / contacts we have it already caze - UUID). For samples we have "case associated" (this should work)

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX Review Done - Everything looks good
