### ISSUE TITLE
[Angular] Add new task (follow the "add new case" example) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5716]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/L0P4goL
- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/KvE0PO2
- Note: both the case / event / contact task form and the general task form should be implemented
- Note: when creating a task from the case / event / contact page, the case ID should be automatically pre-filled
- Note: this should be done unde a shared component

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/Ux review Done (some styling issues mentioned in the "UI inconsistencies" task, will be resolved there)
