### ISSUE TITLE
[Angular] Add new event (follow the "add new case" example) [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5717]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WK4W3G2
- Note: We should only implement the base line structure of the form
- Note: the developer that actually implements this task, needs to consult the current implementation

**Comment by cristinacoza** [comment]
UI/UX review - Done - There are some inconsistencies with the current SORMAS that Adrian will fix in a new task (link to be added)
