### ISSUE TITLE
[Angular] Add new contact (follow the "add new case" example) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5719]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/KvE0Pke
- Note: We need to investigate from where else can a user create a "new contact"
- Note: @cristinacoza please provide all such locations (add a link)
- Add new contact locations: 
---Contact page - add new contact: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlbgW9n
--- Epidemiological data tab (case tab): contact with source case - New Contact: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1OPj2w
--- Contact tab (case tab): Add new contact: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/KvE0Pke
--- Event participant tab (event tab) : on the right sidebar - Contacts - New contact: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnvDR7z
--- Lab message ( on samples page): on the Lab message table - process - 
Pick or create person -  select create new person - pick or create entry - Create new contact: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/jgo0dE0

- Note: this should be done unde a shared component

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good!
