### ISSUE TITLE
[Angular] Add new sample (follow the "add new case" example) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5720]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ygy9aEE
- Note: @cristinacoza please provide all such locations (add a link)
- Add new sample locations: 
--- Case or contact : Right sidebar - Add new sample 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ygy9aEE
--- Event participants (event tab) - Event participant: Right sidebar - Add new sample (same as Case or contact add new sample) 
--- On Sample page - Refer sample to another laboratory (same form, different title) 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/QbjDJdx
--- Contact - Right sidebar - Add new sample (same as Case or contact add new sample) 

- Note: this should be done unde a shared component
- Note: the "Pathogen / Additional tests" will be implemented in another task (ignore the entire "Tests section")
- Note: Please consult the current Sormas implementation for exact behaviour
- Note: ignore the sample id (automatically generated)

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review - Done, Everything looks good! (apart from some styling issues that will be resolved in the "UI inconsistencies" ticket)
