### ISSUE TITLE
Merged cases can have two exposures marked as probable infection environment 

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#5721]
### Bug Description

After merging cases with exposures marked as probable infection environment, both exposures are listed in the exposure list of the merged case as probable infection environment
### Steps to Reproduce

1. Create two Cases with a similar name, same Date of birth and same Sex
2. Go to the Epidemiological Data tab and enter for each case an exposure marked as probable infection environment 
3. Merge the cases 

### Expected Behavior

Only the exposure of the leading case should be marked as probable infection environment 
### Screenshots

Case 1: Remaining case 
![image](https://user-images.githubusercontent.com/83459190/121188073-096a1300-c869-11eb-9e13-92f58b25b882.png)

Case 2: Discarded case 
![image](https://user-images.githubusercontent.com/83459190/121188412-5fd75180-c869-11eb-8b48-f4d652d1dfc1.png)

Merged Case: 
![image](https://user-images.githubusercontent.com/83459190/121188894-d7a57c00-c869-11eb-8d22-0f1785e39580.png)

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de
* User Role: Admin, National User

### Developer Specifications

When merging cases, check if both cases have an Exposure marked as `probableInfectionEnvironment`. If yes, set the Exposure of the second (non-lead) case to `probableInfectionEnvironment=false`

**Comment by StefanKock** [comment]
I'm not sure if this is a `bug`or rather a `change` request. This data should be editable afterwards, so there is a workaround. 
Also what comes to my mind: Having already two parallel cases should happen rarely, how much of an edge case is then the described scenario?

**Comment by JaquM** [comment]
@StefanKock  unfortunately, it probably happens several times a day. 
Since it should just be possible to have one as probable infection environment, unfortunately it is a bug.

**Comment by RazvanHodisan** [comment]
Verified on Chrome,Version: 1.61.0-SNAPSHOT, environment https://test-de.sormas.netzlink.com/
