### ISSUE TITLE
Documents of the discarded case / contact get lost while merging 

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#5722]
### Bug Description

Documents (any kind of file) of the discarded case / contact are not merged with the remaining case / contact during the merging process. Only the documents of the remaining case / contact are displayed in the document section. 
### Steps to Reproduce

For Cases:
1. Create two cases with a similar name, same date of birth and same sex
2. For the first case: Add any file to documents 
3. For the second case: Add a different file to documents 
4. Merge the cases

For Contacts:
1.  Create two Contacts with a similar name, same date of birth and sex and link both to the same Source Case
2. For the first contact: Add any file to documents 
3. For the second  contact: Add a different file to documents 
4. Merge the contacts 

### Expected Behavior

Documents of the discarded case / contact should be added to the document section of the merged case / contact 
### Screenshots

Example for case merge: 

Case 1: Remaining Case 
![image](https://user-images.githubusercontent.com/83459190/121197024-40dcbd80-c871-11eb-9e06-d958c326d91a.png)

Case 2: Discarded Case 
![image](https://user-images.githubusercontent.com/83459190/121197248-72ee1f80-c871-11eb-833d-3ff8b554c911.png)

Merged Case: Documents of case 2 are missing 
![image](https://user-images.githubusercontent.com/83459190/121197600-bb0d4200-c871-11eb-9444-bacd4b8751ae.png)

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de
* User Role: Admin, National user

**Comment by RazvanHodisan** [comment]
For cases this works but for Contacts I'm not able to test due to #5952

**Comment by RazvanHodisan** [comment]
Verified on test-de,  Version: 1.61.0-SNAPSHOT
