### ISSUE TITLE
Comment fields are not merged

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#5723]
### Bug Description

While merging contacts or cases, all available comment field are not merged together. Only comment fields, that have been left empty, will adapt the comments of the discarded case or contact. 
### Steps to Reproduce

For Cases: 
1. Create two cases with a similar name, same Date of birth and same Sex
2. For the first case: Type in the comment fields of the Case Tab or Case Person Tab
3. For the second case: Fill the same comment fields in the chosen Tab with different Text 
4. Merge the cases

For Contacts: 
1. Create two contacts with a similar name, same date of birth and sex and link both to the same Source Case
2. For the first contact: Type in the comment fields of the  Contact Tab or Contact Person Tab
3. For the second contact: Fill the same comment fields in the chosen Tab with different Text 
4. Merge the contacts 

### Expected Behavior

Information in the comment fields from the discarded Case / Contact should be added to the Comment sections of the Merged Case / Contact 
### Screenshots

Example : Follow up status comment filled and general comment

Case 1: Follow up status comment filled and general comment empty 
![image](https://user-images.githubusercontent.com/83459190/121202217-68ce2000-c875-11eb-8515-e4cdd972b688.png)

Case 2: Follow up status comment and general comment both filled 
![image](https://user-images.githubusercontent.com/83459190/121201904-2d335600-c875-11eb-84e7-893c83e64632.png)

Merged Case: 
![image](https://user-images.githubusercontent.com/83459190/121202913-f6aa0b00-c875-11eb-8873-cdcd750edef9.png)

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de
* User Role: Admin, National User

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS: 1.61.0-SNAPSHOT on test.sormas.netzlink.com
