### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: Shortcuts [3]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5729]
### Situation Description

Preriquisite: #5622, #5713, #5539

The new DEMIS profiles introduce lifecycle management, so that demis notifications can relate to each other. This means also lab messages need to relate to each other (foundation for that is #5622). When lab messages get processed, entities like samples and pathogen tests are created out of that. When a lab messages gets processed that relates to a previously processed lab message, it can mostly be related to the previously created entities. 
As a user, when processing such a lab messages, I want to automatically be proposed to jump to those related entities, if there are any. This reduces the risk of errorneous processing and the number of clicks necessary. 

### Feature Description

For the demis lifecycle management, there are five scenarios (+sub scenarios) defined (see #5138). It it not clear whether they will in practice be mixed up or not. Anyway, they should boil down to three kinds of shortcuts in SORMAS:

1. There is a procesed lab message with the same reportId and a sample with the same labSampleId as the in the lab message. The sample and the processed lab message are related. There are no matching pathogen tests (a matching pathogen test has the same externalId as one of the (non processed) lab messages test report). This is the case for scenario 2 (all sub scenarios), 3b, and 3c. In this case, when the process button for a lab message is clicked, a popup should show asking `A lab message with the same report ID was already processed. It is related to a sample also referenced in this lab message. Do you want to directly open that sample?`. It should be possible to either chose `YES`, `NO` or cancel the processing. If chosen `YES`, a sample form should open with all the existing and new pathogen tests attached (a form very similar to the one specified in #5899 ). If chose `NO`, the processing should continue as if no already processed lab message with the same reportId and no matching sample was found.
2. Identical to 1., but there is at least one matching pathogen test found. In this case, popup question should be `A lab message with the same report ID was already processed. It is related to one or more pathogen tests also referenced in this lab message. Do you want to directly open those pathogen tests?`. This shortcut applies in scenario 4.
3. There is no related processed lab message, but a sample with the same lab sample id as in the lab message. There are no matching pathogen tests (a matching pathogen test has the same externalId as one of the (non processed) lab messages test report). In this case the popup question should be `The sample referenced in this lab message already exists. Do you want to directly open that sample?`. This shortcut applies in scenario 2b, 3a and 3b (if second test is positive).

The correction of data, as specified in #5714, should always be done first, before taking one of those shortcuts.

### Open questions

- When lab messages get completely deleted, some shortcuts may get lost. Should lab messages instead be archieved? This would allow another shortcut for messages forwarded via S2S. **ANSWER**: lab message should not get completely deleted anymore (but archived instead). When a user starts processing a lab message related to another lab message marked as forwarded (either manually or via S2S, a popup shall inform the user about this. `Another related lab message was marked as forwarded/manually forwarded. Do you want to continue processing this lab message?` Answer options should be `YES` and `CANCEL`
- When demis notifications don't stick to the definition of lifecycle scenarios or lab messages get deleted, there are other shortcuts possible. For example one like 3., but with matching pathogen tests. Should they also be taken into consideration? Answer: No.

### Possible Alternatives

Suggestions welcome!

### Additional Information

Out of scope for this ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5729#issuecomment-860528432

**Comment by Jan-Boehme** [comment]
> When lab messages get completely deleted, some shortcuts may get lost. Should lab messages instead be archieved? This would allow another shortcut for messages forwarded via S2S.
If I understand it correctly the lab message is the only way to get a reference to the entities which were created from it. If we want to implement lifecycle management I don't think we can afford to completely delete them anymore.

> When demis notifications don't stick to the definition of lifecycle scenarios or lab messages get deleted, there are other shortcuts possible. For example one like 3., but with matching pathogen tests. Should they also be taken into consideration?
Personally I am not a big fan of trying to compensate for someone else not sticking to defined interface specifications.
If the lifecycle data is not send correctly we should handle it like it is a completely new lab message.
@kwa20 what is your opinion on this? I sometimes tend to be too stubborn regarding such issues.

**Comment by FredrikSchaeferVitagroup** [comment]
It can not be possible to process lab messages having unprocessed predecessors: When (at least one) previous and unprocessed lab message with the same reportId exists, a popup shall inform the user `An earlier unprocessed lab message with the same report id exists, which needs to be processed first. Do you want to directly jump to processing the earlier lab message?` The user should be able to either cancel the processing, or click `YES`. If clicked `YES`, SORMAS should jump to processing the earliest unprocessed lab message.

**Comment by vidi42** [comment]
> It can not be possible to process lab messages having unprocessed predecessors: When (at least one) previous and unprocessed lab message with the same reportId exists, a popup shall inform the user `An earlier unprocessed lab message with the same report id exists, which needs to be processed first. Do you want to directly jump to processing the earlier lab message?` The user should be able to either cancel the processing, or click `YES`. If clicked `YES`, SORMAS should jump to processing the earliest related and unprocessed lab message.

@FredrikSchaeferVitagroup please open a separate ticket for this scenario

**Comment by FredrikSchaeferVitagroup** [comment]
As, with the implementation of #5899, the way lab messages are processed changed, all shortcuts now always lead to the same form. The shortcuts cound therefore be simplified. That is what I implemented:

In case of scenario 1. and 2. from above, a popup asks `A lab message with the same report ID was already processed. It is related to a sample also referenced in this lab message. Do you want to directly open that sample?` There is the option the chose either `YES` or `NO`, and to close the popup. When the user choses `YES`, a sample edit form with all existing and new pathogen tests attached is opened. When the user choses `NO`, the processing continues as if there was no related sample found.

In case of scenario 3. from above, the behaviour is identical, just the message displayed to the user differs. It asks `The sample referenced in this lab message seems to already exist. Do you want to directly open that sample? There were no processed related lab messages found.`

Also, I've implemented the check for forwarded lab messages close to what was described above:
When a user starts processing a lab message related to another lab message marked as forwarded (either manually or via S2S, a popup shall inform the user about this. `There exists at least one other lab message with the same report id that was forwarded. Do you want continue processing this lab message?` Answer options should be `YES` and `CANCEL`. When the user choses `YES`, the processing continues. When the suer choses `CANCEL`, the popup closes.

**Comment by FredrikSchaeferVitagroup** [comment]
To verify this issue, a good starting point is to check whether the behaviour described in [this comment](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5729#issuecomment-966928943) shows in the UI.
