### ISSUE TITLE
[Angular] Case "View Options" and "Bulk edit" dropdowns [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5734]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- at cases, implement the "view option" dropdown and the "Bulk edit mode" dropdown.
- these 2 dropdowns should be in the table component
- the "Bulk edit mode" should be disabled and should be enabled only when at least one row is selected
- when selecting the value from the dropdowns, a method with a console.log will do for now
- Note: Only the dropdowns should be implemented (not the actual functionality)
- Note: This should first be done in the table component (we can provide several params to mark which action is enabled, like deleted - enabled).

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good
