### ISSUE TITLE
[Angular][Backend][SPIKE] Investigate how the Create Case/Sample/Etc and Person works from the BE point of view [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5735]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Focus on Case / person creation flow
- Note: This tasks needs to document how exactly we can create the case and how the "person" entity is created and linked to the case.
- Note: We need to also investigate the current design and legacy Sormas

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by marius2301** [comment]
For the moment we need the uuid in order to cerate entities. This will change and the uuid would be accepted null and the backend will generate it.
