### ISSUE TITLE
Wrong error message, while trying to save a case. [Place of stay problem]

### ISSUE THREAD

**Issue by VitaliHZI** [hzi-braunschweig/SORMAS-Project#5736]
### Bug Description

Wrong error message, while trying to save a case. 

### Steps to Reproduce

1. Go to cases
2. Create new case
3. chose first "place of stay" Facility
4. let the fields free
5. let the fields region and district free
6. save (correct error message displayed)
7. change "place of stay" to home
8. Fill out region and district
9. Click save 
10. Error message "A problem has occured. You have to specify a valid health facilty." and you can not save the case. 

### Expected Behavior

You should be able to save the case
### Screenshots

![image](https://user-images.githubusercontent.com/79860634/121370761-456ea800-c93d-11eb-8130-d1c107409109.png)

### System Details

* Device: Windows 10, 
* SORMAS version: 1.60.2
* Android version/Browser: Google Chrome
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui or https://test1401.sormas-oegd.de/sormas-ui/login
* User Role: admin + national user

**Comment by kwa20** [comment]
Further findings: If data has been entered in this specific order, the system seems to validate the facility field regardless of having changed the place of stay to home. Region and district seem to play a key role here since entering them before changing the place of stay does not result in an error.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT on test.sormas.netzlink.com environment

**Comment by maxiheyner** [comment]
Exactly this bug was found again in version 1.62.3 and can be reproduced on https://test1401.sormas-oegd.de as admin using Chrome.

**Comment by MateStrysewske** [comment]
@maxiheyner Please don't reopen issues that have already been released, but create a new issue instead. Also, please check whether the same bug still happens 1.64.0 (as that's the current development version).
