### ISSUE TITLE
[Angular] Case "More dropdown" [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5737]
### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlDa3Yl
- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1Ox22g
- Note: The "Export case" has sub-items (Basic export, Detailed export, Case management export, etc). When clicking the arrow the list should expand / colapse
- Note: we need to also implement the "Custom export" which opens a modal (see the above design). Only use dummy data for now
- Note: We need to reuse the cards component on the dropdown (the style shouldn't be directly in the export page)\
- @cristinacoza , please update the card "delete" from the bin to an "X"

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good
