### ISSUE TITLE
[Angular] Case import functionality [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5738]
### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlDa3Yl
- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/R1dyvke
- Note: We implement just the basic structure, dummy content (what is in the design)
- Note: The download functionality should work, and enable the user to download an empty pdf / img (something to exemplify that the download works).
- Note: Enable the upload field and add the basic csv validation (check for the csv format).

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX Review Done - Everything looks good
