### ISSUE TITLE
[Angular] Implement "edit case" modal [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5739]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/9PReOvW opened from: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlDa3Yl
- the same user flow (nothing is pre-filled) regardless of the user selects 1 or more cases
-  it should also support bulk edit
- it should use the add-base-modal component and the add-base-modal should be refactored and become add-edit-base-modal
- it should make use of the dynamic form
- the backend "update request" should remain as an array
- when the "edit" window is opened nothing is checked and no data below the checkboxes is displayed. (the data below the checkbox is displayed only when the checkbox is active).

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by MateStrysewske** [comment]
Just for clarification - bulk editing is the exact use case of this form, it is not used anywhere else in the application

**Comment by cristinacoza** [comment]
UI/UX review Done - Everything looks good except some styling issues that will be resolved in the "UI inconsistencies" ticket
