### ISSUE TITLE
[Angular][Backend][SPIKE] Investigate how and why the Event ID is generated before an Event is created [1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5746]
### Problem Description

SPIKE - We need to understand the functionality and user flow of the Event creation

### Proposed Solution

- @marius2301 , please investigate and discuss with @MateStrysewske or @MartinWahnschaffe how and why is the event ID generated before the event is actually created. We need to understand if this is done in a separate call, or if it's done in the FE without checking the DB for the event ID uniquness.
- We need to document this flow. Please describe it in a comment on this task, or alter the task description, pointing out the exact logic behind it.
- REFERENCE: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WK4W3G2

### Possible Alternatives

- Maybe there isn't really a need to generate the event ID, and then we can simply ignore it. (or it can be done upon actually submitting the event).

### Additional Information

N/A

**Comment by MateStrysewske** [comment]
Please refer to #4891 - we might have to prioritise that issue in order to make sure that it's possible to create entities through the ReST API without specifying a UUID.
