### ISSUE TITLE
Make fields in previous hospitalizations non-compulsory by adding an option "unknown" [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5748]
### Feature Description

Currently, region, district and hospital are compulsory fields in previous hospitalizations. This causes some problems when initially importing data from SurvNet when regional information are missing in the import file. 

<img width="650" alt="previousHospitalizationsCompulsory" src="https://user-images.githubusercontent.com/70317594/121495113-9e8c1980-c9d9-11eb-85b6-2ed24fd2dcf1.PNG">

### Problem Description

If data is imported through the converter that does not lead to these fields being filled, detailed exports can not be done properly because these fields include corrupt data. 
### Proposed Change

Make these fields non-compulsory. This should usually not be affected by transferring cases because the place of stay location is still compulsory.
### Possible Alternatives

Somehow introduce always available values like UNKNOWN for infrastructure data so fields can be set if this information is missing in import files.
### Additional Information

https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/162

**Comment by vidi42** [comment]
@kwa20 in your proposed change, are you suggesting to make them optional as a generic change, or just when the entities originate from the SurvNet converter import?

**Comment by kwa20** [comment]
@vidi42 I would suggest to make them optional in general as seen in for example addresses in persons.

**Comment by MateStrysewske** [comment]
I don't really agree with this change request. The hospital is a compulsory field because a previous hospitalization without an associated hospital would not be very helpful. The region and district are compulsory subsequently because they are needed in order to filter for the hospital. If this is a problem for SurvNet, it should be taken care of in the converter, but we shouldn't provoke reduced data quality in SORMAS just because of that.

**Comment by markusmann-vg** [comment]
@MateStrysewske If those fields are not mandatory in the database, we might approach the feature request by leaving the decision to the user when he saves the previous hospitalization. So when it's not entered, the user gets a notification that we recommend to enter all data, but he's also able to overrule by clicking "ok".  Maybe this is an approach for "de-servers" only?

**Comment by MateStrysewske** [comment]
@kwa20 Does SurvNet contain previous hospitalizations without any facility information? Or is it just the region and district that are missing?

**Comment by kwa20** [comment]
@MateStrysewske In SurvNet, hospitalizations are not split into current and previous and any hospitalizations can indeed have missing information for either location or facility.

**Comment by MateStrysewske** [comment]
@Chinedar I'd like to have your opinion on this. Would making all fields of previous hospitalizations optional have a negative impact on data quality?

**Comment by Chinedar** [comment]
No, I think it's fine if it's optional with the "unknown" option added as
well.
