### ISSUE TITLE
Users with superior jurisdiction incorrect for users with health facility

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#5752]
### Bug Description

In `UserFacadeEjb.getUsersWithSuperiorJurisdiction`, users with a health facility are handled incorrectly: the returned result contains contains users from the same district as, but different communities than the health facility.

Additionally, the method may return a `null` value instead of an empty list, forcing developers to implement `null` checks when using the method.

### Steps to Reproduce
The (erroneous) behaviour is covered in test `UserFacadeEjbTest.testGetReferencesByRoleAndJurisdiction`.

### Expected Behavior
Users with jurisdiction level `COMMUNITY` from communities other than the health factory's should be excluded.
The method `UserFacadeEjb.getUsersWithSuperiorJurisdiction` should return an empty list rather than `null` if no users are found.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RazvanHodisan** [comment]
Verified on local Version: 1.61.0-SNAPSHOT
