### ISSUE TITLE
Crash when entering NewCaseActivity

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#576]
This only happened for user U2NBLL so far. When they click on the + button to create a new case, the app synchronizes and then crashes. There are Google Analytics crash reports for version 0.18.2.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar 
Does it happen exactly the moment you press the + button? Or sometime after that will entering name, etc. for the new person?

Have you tried to re-synchronize data (possible in the settings section)?

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar In addition - is this somehow related to transfering a case? I have an error message for that user that occured when trying to transfer a case - not during creation.

**Comment by Chinedar** [comment]
Sorry I'll find out about this. I don't I lodged this very issue.

Thanks.

**Comment by hzi-braunschweig** [comment]
Chinedu,
Its Ferdinand that logged it. I have asked him to provide more details. Please remind him that all errors and issues should be logged in via GitHub.


Regards

Tom-Aba Daniel (B.Sc MPH)
Doktorand
PhD Epidemiology Programme, Hannover Medical School (MHH),
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by Chinedar** [comment]
Oh ok,

Let me call him and get more details.

Thanks!

**Comment by MartinWahnschaffeSymeda** [comment]
See #581 and #582

**Comment by MartinWahnschaffeSymeda** [comment]
May be related to #586 , but I can't say for sure. Waiting for additional information.
