### ISSUE TITLE
Setting contacts to "no contact" / Cancelling follow up in bulk edit mode can lead to data loss

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#5763]
### Bug Description

When setting a contacts status to "NOT A CONTACT" the field "FOLLOW-UP STATUS COMMENT" is overwritten by the message 
"[System] Follow-up automatically canceled because contact was dropped"
The original contents of this field are lost.
Similar: When cancelling follow up the message "Canceled by User Name using bulk action" overwrites the fields contents.

The field can contain potentially important data and should not be overwritten, especially without a warning. This behaviour can lead to unnoticed and undocumented data loss.

### Expected Behavior

The original contents of the field should be kept in any case.

A) [Preferred] The status message is appended or prepended to the existing contents
B) No message is inserted, the previous contents of the field are left unchanged 

Being able to see in what way the follow-up was cancelled is a "nice to have", but losing potentially important data is a no-go.

### System Details
* SORMAS version: Version: 1.59.2
* User Role: Admin for bulk edit / any other user for "Not a contact"

**Comment by MateStrysewske** [comment]
Option a) is definitely the way to go here, and something that we've already implemented in other places of the application as well, so we can basically reproduce that behaviour.

**Comment by FredrikSchaeferVitagroup** [comment]
To test the implementation, check for behaviour a) mentioned above.

**Comment by RazvanHodisan** [comment]
Verified on test-de, Version: 1.61.0-SNAPSHOT
