### ISSUE TITLE
Bulk transfer/edit cases health facility [1]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#577]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
We mentioned this before that the admin should also be able to move cases from one LGA to the other because of retrospective data entry. We discussed this and said a case by case basis would be better but now from discussions with the admin guys in the field, there are situations where the cases were created at the national level and were set to other health facilities because they could not find the right health facility which may have been put into a wrong ward. Now the admin has over 400 cases under "Other health facility" which he needs to transfer to a newly created health facility. Hence the need to have the move case under bulk operations. 

![image](https://user-images.githubusercontent.com/19344651/39304659-ab5117e0-495a-11e8-8daf-ffdf24da0a7d.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
Hallo Martin, yes it is still important to move existing cases from other health facility to newly created health facilities based on the new release with that functionality. However, 400 cases were not transferred to 1 hospital. The problem was that 400 cases were distributed across several other health facilities so if admin can do batch transfer then this would help

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Ok. We discussed this again and came to the following important conclusions:

* the system must distinguish between transfering cases and editing the health facility (to correct wrong entered data, without changing hospitalization data)
* bulk changing health facilities needs to reflect this by letting the user choose which of the two operations he wants to do
* within a single case it should probably also be possible to edit the health facility without to correct wrong data (instead of transfering which changes the admission data and adds a previous hospitalization)

@hzi-braunschweig Is this correct? Anything to add?

**Comment by hzi-braunschweig** [comment]
We need to revisit this issue @MartinWahnschaffeSymeda  @MateStrysewskeSym bulk edit mode for health facility is very important.

**Comment by hzi-braunschweig** [comment]
> Ok. We discussed this again and came to the following important conclusions:
> 
> * the system must distinguish between transfering cases and editing the health facility (to correct wrong entered data, without changing hospitalization data)
> * bulk changing health facilities needs to reflect this by letting the user choose which of the two operations he wants to do
> * within a single case it should probably also be possible to edit the health facility without to correct wrong data (instead of transfering which changes the admission data and adds a previous hospitalization) #1135
> 
> @hzi-braunschweig Is this correct? Anything to add?

Yes this is fine @MartinWahnschaffeSymeda

**Comment by MateStrysewskeSym** [comment]
- [ ] Add the required fields (region, district, community, facility, facility details) to popup that opens up when clicking on "Edit..." in the bulk actions dropdown
- [ ] Region, district, facility and (if visible) facility details are required when the checkbox is checked
- [ ] When these fields have been filled in and the user submits, ask whether they want to merely edit the data or actually move the cases (same as when doing this for a single case) and replicate the already existing functionality from the CaseController

**Comment by ChristopherRiedelSymeda** [comment]
@MateStrysewskeSym Should be reviewed  and has to be merged afterwards

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] save dialog is shown before "edit or transfer" dialog
