### ISSUE TITLE
Configurations > Countries > Sub-continent association change NCL [0.5]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5774]
### Feature Description

In the countries list (Configurations > Countries >), New Caledonia is currently associated with the sub-continent of Oceania. This should be Western Europe instead.

### Problem Description

After introduction of #4782, sub-continents were associated with countries. New Caledonia should fall under Western Europe.

### Proposed Change

Change New Caledonia sub-continent association to Western Europe i.e.
defaultName | externalId | isoCode | unoCode | archived | subContinent
-- | -- | -- | -- | -- | --
New Caledonia | 8606 | NCL | 540 | FALSE | Western Europe

### Additional Information

Please migrate existing entries to update the sub-continent automatically to 'Central Europe' if the country 'Germany' was selected in existing data. This would be applicable to locations and addresses pertaining to facilities, exposures (epi data) etc. where the entries may already have been used in connection with one another.

SurvNet Converter team (if applicable to mapping change):

CatalogueName | UseShortName | IsHierarchical | IdItem | ItemName | ISO | Sort | IdCatalogue2Item | IdCatalogue | IdParent | IdIndex | IsDeleted | Schema2 | Schema3 | ChangeStatus | Schema4 | Schema5 | Schema6 | Schema7 | Schema8 | English
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
World | 0 | 1 | 41000001 | Europa | EUR | 2990 | 17001 | 1025 | 0 | 31000003 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | Europe
World | 0 | 1 | 41000030 | Westeuropa | &nbsp; | 3778 | 17030 | 1025 | 17001 | 41000030 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | Western Europe 
World | 0 | 1 | 41129000 | Frankreich | FRA | 3791 | 17155 | 1025 | 17030 | 21000150 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | France
World | 0 | 1 | 41129032 | Neukaledonien | &nbsp; | 3815 | 17187 | 1025 | 17155 | 21000518 | 0 | 1 | 1 | No   Change | 1 | 1 | 1 | 1 | 1 | New Caledonia
Staat | 0 | 0 | 10102268 | Neukaledonien | &nbsp; | 11173 | 12537 | 1013 | 0 | 21000518 | 0 | 1 | 1 | No Change | 1 | 1 | 1 | 1 | 1 | New Caledonia

Connected to (prefereable to be done at same time as):
#5680 and #5689

**Comment by MateStrysewske** [comment]
* Change association in `sormas_import_all_countries.csv`
* If the entry exists in the database (check by matching ISO code), change the association of the country in the database
* Change the subcontinent (and subsequently continent) ID in every location entity that references the country
