### ISSUE TITLE
Events can be linked to pseudonymised cases

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5775]
### Bug Description

Users with pseudonymised, but edit access to cases can link events to them. This results in a pop-up being presented to the user during the event participant creation that contains mandatory first and last name fields which are, however, empty (since the user is not allowed to access the name) and disabled.

### Steps to Reproduce

1. Open a pseudonymised case that you have edit access to
2. Link an existing event to the case

### Expected Behavior

It should still be possible to link events to these cases, but the event participant creation window should probably hide the first and last name fields (and make them non-mandatory); the whole process should still work afterwards, i.e. the event should be successfully linked, but no personal information about the involved person should be shown throughout the process.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RazvanHodisan** [comment]
Verified on test-de, version Version: 1.61.0-SNAPSHOT
