### ISSUE TITLE
OPTION B: Report automatically that a case was deleted to the reporting system when a case was sent and accepted to another instance of SORMAS [1]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#5779]
### Situation Description
Currently SurvNet is not informed, when a case was sent with the Sormas 2 SORMAS interface.
As this might lead to wrong numbers in the reporting system, we would need to inform Survnet about the status.
As we did when a case was deceased, we need to do it automatically, when a case was sent together with the ownership.

### Feature Description
With different events, we need to trigger automatically the SurvNet Converter to generate a transportfile, which can be read and imported in SurvNet

Accept Flow:
1. A case is sent from SORMAS A to SORMAS B
2. This case is in SORMAS in the state "pending" as long as SORMAS B did not accept or decline the transmission
3. The state "DELETED" has to be synched with SurvNet by triggering the converter with the information

Decline Flow: nothing to do on our side! See use case 2

### Additional Information
In the scope is just the send single and bulk action to send cases to another SORMAS Instance. Events of type cluster will be treated in another story

=> Should only be executed when the SurvNet Interface is configured

linked to:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4423 & 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/4119  
 

### Additional Info
Use Case 1 
1.) Transfer of a case preview with responsibility from SORMAS A to SORMAS B
2.) SORMAS B accepts taking over the case and informs SORMAS A / SORMAS B "downloads" the case from SORMAS A and creates it in SORMAS B
3.) SORMAS A sends case to SurvNet A with status "deleted"
4.) SurvNet A sends case to LS BL 1(Regional office of Federal state) with status "deleted"
5.) SORMAS B can now send the case to SurvNet B
6.) SurvNet B can now send to LS BL 1 (Regional office of Federal state)

-----------------

Use Case 2
1.) Transfer of a case with ownership from SORMAS A to SORMAS B
2.) SORMAS B declines to accept the case and informs SORMAS A
3.) SurvNet will not be informed in this use case

**Comment by leventegal-she** [comment]
> SORMAS A sends case to SurvNet A with status "deleted"

How to specify "status "deleted"" when sending cases to survnet?
Currently CaseDataDto and EventDto has flag "ownershipHandedOver"  that is used from web and app. Could it be used in the convertor too? @HolgerReiseVSys
