### ISSUE TITLE
Allow surveillance supervisors and contact supervisors to access bulk-edition in the event directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5782]
### Feature Description

Evolution of the rights allowing to use the bilk-edition mode

### Problem Description

To date, the bulk-edition mode of the event directory is not accessible to the "surveillance supervisor" and "contact supervisor" profiles.
However, this profile is the most widely used in France and it is therefore important for users to be able to access the various bulk-actions

### Proposed Change

-	Make the bulk-edition mode accessible to surveillance supervisors and contact supervisors 
-	Allow surveillance supervisors and contact supervisors to “group”, “archive” and “modify” events. The “delete” bulk-action will remain accessible only to administrators and / or national users.

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 @Chinedar Is this fine for all of you?

**Comment by kwa20** [comment]
@MateStrysewske Would be fine with me.

**Comment by Chinedar** [comment]
yea fine by me. Thanks
