### ISSUE TITLE
Event directory - add the event management status in the "edit" bulk action

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5783]
### Proposed Change
In the event directory, several bulk actions are defined, including the one allowing you to mass modify the event status and the investigation status. 

We propose to : 

- adapt the pop-up that is displayed by clicking on bulk-action "modify" 
- add the "event management status" field to the two pre-existing fields: event category and "survey status".

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by bernardsilenou** [comment]
@carolinverset  I did not understand the meaning of the last point `"survey status"` Maybe we discuss it tomorrow?
For the management status, it  is good to add to bulk edit.

**Comment by carolinverset** [comment]
> @carolinverset I did not understand the meaning of the last point `"survey status"` Maybe we discuss it tomorrow?
> For the management status, it is good to add to bulk edit.

Sorry @bernardsilenou it's google translate fault :) i meant "event category and investigation status"

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.63.0-SNAPSHOT on test.sormas.netzlink.com environment
