### ISSUE TITLE
Adding a contact for a responsible region will not be displayed for the Community Officer

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5788]
### Bug Description
Added Contacts by Listing them and from New Contact. The responsible region was the one for which the Community Officer has access to. However after addign them and refreshig the page, only 1 contact was visible, the one added with the National user by selecting a case and adding it from Contacts.

### Steps to Reproduce
1. Log in with NatUser
2. Add contacts from the Contacs page by listing them or from New Contact.
3. Add the resposible region (reg4) and the district (dist4)
4. Log in with the Community Officer.

### Expected Behavior
If contacts are added for a region where the Community Officer has access to he should be able to see them

### Screenshots
![image](https://user-images.githubusercontent.com/53563072/122003095-48ddb580-cdbb-11eb-8c98-28ce2d89721b.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role: NatUser, Communiti Officer (CommOff2 /  oPEx7eob9tQT)

### Additional Information
The only Contact visible (RHB. BHR) was added from Cases.

**Comment by MateStrysewske** [comment]
@RazvanHodisan Did you also add a responsible community to the contacts? Because if I'm not totally mistaken and nothing has changed over the last weeks, community officers only have access to data within their community, so all data inside their region that is not directly associated with their community would not be visible for them.

**Comment by RazvanHodisan** [comment]
Ideed, that seems to be the case and it is not a bug, I was under the impression that if the District has only 1 Community created and only 1 community officer  assinged to that District, the user will see those contacts.
