### ISSUE TITLE
Ensure New UI design follows strict rules and algorithms of old design

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#579]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Please we need to ensure that every rule, logic and algorithm including user rights, required fields (with the red star) and views which works on the current Symeda mobile app should be transferred to the new UI design. What I see right now on the new UI does not follow the Symeda mobile app rules. 

@MartinWahnschaffeSymeda Please can you discuss this with Orson during  integration phase if neccessary?

Informant view of menu
![image](https://user-images.githubusercontent.com/19344651/39304922-ad33dfe2-495b-11e8-8774-9aeb9302621d.png)

![image](https://user-images.githubusercontent.com/19344651/39305071-1a09692a-495c-11e8-9535-08c73f41e763.png)

![image](https://user-images.githubusercontent.com/19344651/39305147-55aac26c-495c-11e8-85a2-c3b890856bdf.png)

![image](https://user-images.githubusercontent.com/19344651/39305220-9869fafa-495c-11e8-95f8-3ae431cf7697.png)

![image](https://user-images.githubusercontent.com/19344651/39305250-ab5a5344-495c-11e8-8eab-bfa392a13818.png)

![image](https://user-images.githubusercontent.com/19344651/39305268-c20588de-495c-11e8-85b4-118d088793f6.png)

**Contact officer**
![image](https://user-images.githubusercontent.com/19344651/39306937-ccb90b2a-4961-11e8-80a3-fadec16f070e.png)
![image](https://user-images.githubusercontent.com/19344651/39307148-5a1b5cde-4962-11e8-8bec-22b2e81edb51.png)
Contact officer cannot eidt contact personal information

![image](https://user-images.githubusercontent.com/19344651/39307245-966d3572-4962-11e8-8b25-78e9a8808361.png)

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Clsoign this, because in the meantime we have much more detailed tickets
