### ISSUE TITLE
Investigate automated tests failure from Jenkins job

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#5791]
Due to errors related to Chrome version thrown in Jenkins while trying to execute automated tests, please try to downgrade chrome version in order to see if this could be a fix.
We tried to update Chrome to v90 which is the latest version on the Jenkins machine, but it didn't work as the local setup works on v91.

## TODO

- [x] Adjust the tests to run on lower versions of chrome or on version 90.

**Comment by rdutu-vg** [comment]
Started to look into webdrivermanager documentation to see how we can setup a specific version of Chrome.
I'll keep the thread posted to provide the status of the ticket.

**Comment by rdutu-vg** [comment]
Chrome error was fixed due to periodic updates. 
The new problem that we're investigating is:  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileTestJava'.

**Comment by raghupola-vg** [comment]
@rdutu-vg This investigation will be in waiting until the chrome driver version on jenkins machine is updated and verified.
