### ISSUE TITLE
[DEMIS2SORMAS] Too long values are cut off in the html representation of a lab message

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#5793]
### Bug Description

As the ticket heading says. This can be quite problematic, because it might block users from being able to process lab messages as they may not be able to see all the information relevant.

### Steps to Reproduce

1. Open a lab message with a quite long value in any attribute
-> the value is cut off (example: see the Bezeichnung field below)

### Expected Behavior

The value should be readable by using a horizontal scrollbar. Alternatively, automatic line breaks could be inserted. If code changes are done in the demis-adapter, please create a ticket in the [adapter project](https://github.com/hzi-braunschweig/sormas-demis-adapter).

### Screenshots

![image](https://user-images.githubusercontent.com/67001822/120335014-6c036200-c2f1-11eb-9e90-9bac3803ad91.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.60.1-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local dev system
* User Role: NatUser

**Comment by FredrikSchaeferVitagroup** [comment]
For testing this, please reach out to me.

**Comment by AndyBakcsy-she** [comment]
Validated ticket using Sormas Version 1.62.0-snapshot on test-de2 environment.

**Comment by AndyBakcsy-she** [comment]
Closing this ticket as it was already delivered with version 1.61 
I have created another issue #6174
