### ISSUE TITLE
Eza North Ebonyi state

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#581]
I notice that on Eza North LGA Ebonyi state tablet when he tries to create new case it take him to synchronization all the time 
Secondly the cases enter from the back end on his device all shows other health facility 
Even though the cases are from Eza North LGA there were all admitted to FETHA in Abakaliki LGA
I tried to move the case to Abakaliki LGA with the health facility but could not

**Comment by MartinWahnschaffeSymeda** [comment]
Please go to settings and do a "re-synchronize data". This will take a while, but might resolve the issue.
Let me know if that helps.

**Comment by MartinWahnschaffeSymeda** [comment]
@foyiri How did you try to move the case? Using the web app or the mobile app?
Can you give an example for a case where the transfer was not possible (only provide the SORMAS case ID - no names).

**Comment by MartinWahnschaffeSymeda** [comment]
From an old version - no longer valid.
