### ISSUE TITLE
[Angular][Bug] UI inconsistencies [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5810]
### Bug Description

- There are a couple of UI issues that need to be fixed (please see below)
1. Whenever cards are displayed, we need them all the be the same size (we need to take the biggest size, and format all smaller ones to the larger one, so they look consistent)
2. Text should use ellipses when viewing them on smaller screens and the entire text doesn't fit (across the board)
3. @cristinacoza , please add any additional issues you noticed. Thank you!
- The close icon for the Add new case dialog should be the one provided in the design (icon name: Highlight Off - https://fonts.google.com/icons?selected=Material+Icons&icon.query=off )
Design here: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Ax0Zp71

- The dynamic form sections should be aligned and the highlight should be edge to edge
Design here: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/4a2zPwA

<img width="1558" alt="Screenshot 2021-06-15 at 15 36 11" src="https://user-images.githubusercontent.com/78347216/122194110-cf6ac380-ce9d-11eb-83bd-ceeb11e2ddad.png">

- Update the style for the top part of the Case page: Case info, Case tabs and bookmarks
Design here: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/4a2zPwA

Some paddings in the Dinamic form are inconsistent with the design 
![Screenshot (17)](https://user-images.githubusercontent.com/78347216/123932915-956be800-d99a-11eb-955b-21e2749a4f1d.png)
It should be like this : 
<img width="1041" alt="Screenshot 2021-06-30 at 11 58 01" src="https://user-images.githubusercontent.com/78347216/123933007-a583c780-d99a-11eb-9fbd-93600293b1aa.png">
For more details regarding the dinamic form paddings, see the design here: 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP8GOYa

The labels above the selection fields shoud not be wider than the selection field below. 
you should see the complete text in a tooltip on hover, like in the image: 
<img width="578" alt="Screenshot 2021-06-30 at 12 06 17" src="https://user-images.githubusercontent.com/78347216/123934042-95b8b300-d99b-11eb-9b97-e47779cc7489.png">
For the tooltips see design: 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm9VkaO

### Steps to Reproduce

1. Go on any page and resize the window. You will see that some texts will overlap
2. Go to any page where there are cards, and if the addresses are not equal in length you will notice that the card sizes differ.

### Expected Behavior

1. Text should not overlap
2. Cards should all have the same size on the page.

### Screenshots

![Bildschirmfoto 2021-06-15 um 14 34 28](https://user-images.githubusercontent.com/77488672/122190253-5453de00-ce9a-11eb-9714-f2602b143287.png)
![Bildschirmfoto 2021-06-15 um 14 20 59](https://user-images.githubusercontent.com/77488672/122190259-55850b00-ce9a-11eb-921d-fffa5d02e4c0.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good!
