### ISSUE TITLE
[Angular] Add a "today" action for all date fields on the site [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#5811]
### Situation Description

In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to add an option for "today" for each date field on the site
- The "today" action should set the date to the current date upon the user clicking it
Note: When having an empty filed DON'T default to the current date. The user must input the date manually or click "today" if he wants to set the current date.

### Possible Alternatives

A recommendation: 
![Bildschirmfoto 2021-06-15 um 14 17 35](https://user-images.githubusercontent.com/77488672/122190772-cb897200-ce9a-11eb-9625-a111bbaeb146.png)

Note: If you have a better alternative, feel free to implement it as such.

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good!
