### ISSUE TITLE
Creating an exposure with type "animal contact" leads to error

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#5815]
### Bug Description

Creating an exposure with type "animal contact" with no further information leads to error

### Steps to Reproduce

1. Add an exposure
2. Select "Animal Contact" as type of contact without entering anything else
3. An error shows up. You can press done again to save or change the type of contact
4. The list will now show an entry with empty fields

### System Details

* SORMAS version: 1.61.0-SNAPSHOT

**Comment by RazvanHodisan** [comment]
Verified with NatUser on https://test-de.sormas.netzlink.com/
