### ISSUE TITLE
Immunization II: Overview and add/edit form for mobile app [5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5827]
### Situation Description

Concept issue for immunizations: #4081

### Feature Description

For all the new elements, ONLY show them if the `IMMUNIZATION_MANAGEMENT` feature configuration is enabled.

#### Overview
* Add a new "Immunizations" main menu entry after Samples that contains a list of immunizations
* Only accessible for users with the `IMMUNIZATION_MANAGEMENT_ACCESS` user right
* Show the following information:
  * Immunization UUID
  * First name
  * Last name
  * Means of immunization
  * Management status
  * Immunization status
  * Immunization period (defined by start and end date)
* Add filters for disease, immunization status, immunization start and immunization end
* If only one disease is active in the system, pre-select that disease
* The list always needs to be filtered by a single disease and shows the data from the most recent immunization for that disease; if no disease has been selected, don't show the list, but instead a hint with the following text: "Please select a disease to display the immunization overview."
* Add a "+" action that allows to create new immunizations

#### Creation form
Refer to #4764 for a description of the creation form; it should basically look and work identical in the mobile app

#### Edit form
Refer to #4764 for a description of the edit form; it should basically look and work identical in the mobile app; mobile app does not need the delete and archive options

**Comment by BarnaBartha** [comment]
- [ ] make externalId no longer mandatory
- [ ] fix facility update issue
- [ ] make text visible on popup for duplicate immunization
