### ISSUE TITLE
Contacts with source case not shown when multiple entities converted at once

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5841]
### Bug Description

When converting multiple entities at once through an event participant, contacts with source case are not shown in epi Data.
### Steps to Reproduce

1. Create an event participant in any event
2. Create confirmed contacts for the same person
3. Create a case for this person through the event participant list and make sure that all entities fall into the incubation period
4. Agree to converting all other entities as well upon case creation
5. check the epi data tab in the resulting case for the associated contacts

### Expected Behavior

Contacts with source case should be properly displayed
### Screenshots

<img width="530" alt="convertMultipleParticipant" src="https://user-images.githubusercontent.com/70317594/122382335-1b833a00-cf6a-11eb-93aa-4e5f327f1444.PNG">

### System Details

* Device:
* SORMAS version: 1.60.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

### Additional Information

cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4321

**Comment by MateStrysewske** [comment]
Value is probably not set correctly, which is why the field is disabled (because there are source contacts) but the source contacts are not displayed (because the value is not set to "Yes")

**Comment by MateStrysewske** [comment]
@alexcaruntu-vita We just realised that we also need database migration for cases which already have this issue, i.e. cases that have source contacts, but have this field not set to "Yes" need to set it to "Yes". We've already done such a migration once in the past, so you only have to copy & paste that code over to a new database version. The existing code is in version 281.

**Comment by RazvanHodisan** [comment]
Verified on test-de and local, Version: 1.61.0-SNAPSHOT
