### ISSUE TITLE
Add TravelEntries to tasks [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5844]
### Situation Description

Concept issue for travel entries: #5489

### Feature Description

Allow the creation of tasks associated with travel entries and add a list of connected tasks to travel entries.

* Extend the `TaskContext` enum with a new value `TRAVEL_ENTRY` (now connected feature type)
* Add a `travelEntry` field to the task entities and DTO
* Allow the task type `OTHER` to be created for travel entries in the `TaskType` enum
* Extend the task edit form, including adding logic that decides which users can be set as assignee (users of all user roles except admin that have a matching jurisdiction)
* Extend the task directory (including extending the free text filter)
* Add a list of tasks to the right side of the travel entry form, includuing a create option
* Extend `TaskService.createUserFilter` to allow users to see tasks associated with travel entries they have access to
* Extend the delete method in TravelEntryService to delete tasks associated with a travel entry that gets deleted
* Same for the mobile app -> follow-up issue #6618

**Comment by MateStrysewske** [comment]
@kwa20 Which user roles should be allowed to be set as task assignees for travel entries? Also, are there any specific task types that we should add?

**Comment by kwa20** [comment]
@MateStrysewske I think being able to set all user roles aside from admins would be fine. For task types, I cannot think of anything in particular to add than what we have already. Adding specific types might also become obsolete after the implementation of https://github.com/hzi-braunschweig/SORMAS-Project/issues/3880

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS: 1.64.0-SNAPSHOT on local environment

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
