### ISSUE TITLE
Add documents and document templates to TravelEntries [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5845]
### Situation Description

Concept issue for travel entries: #5489

### Feature Description

Allow users to upload documents to travel entries and to add document templates related to travel entries to the system.

(Disclaimer: Since I'm not that familiar with these functionalities, there might be missing instructions)

* Extend the `DocumentRelatedEntityType` enum with a new value `TRAVEL_ENTRY`
* Add a list of documents to the right side of the travel entry view
* Extend the `DocumentWorkflow` enum with a new value `QUARANTINE_ORDER_TRAVEL_ENTRY`
* Add a new section to `DocumentTemplatesView` for the new document workflow type
* Extend `DocumentTemplateUploadLayout` accordingly
* Extend `QuarantineOrderDocumentsComponent` with a new `addComponentToLayout` method that allows to add a component for an associated travel entry, and use that new method to add a list of quarantine documents to the right side of the travel entry view

**Comment by kwa20** [comment]
Prerequisite for the upload of documents provided by persons through DEA

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
