### ISSUE TITLE
Mocks for S2SRest Client are broken and default to noops at the call site

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#5850]
### Bug Description
Mocks for the S2S Rest client are not working correctly. The lambdas in `thenAnswer` are silently ignored.

Take a look at `SormasToSormasCaseFacadeEjbTest.testShareCase` for example. The arguments of the `post` function have been changed in the past and the test has not been updated (e.g., the first argument of the invocation is now the id, not the URL), so this assertion should fail (what it doesn't). If you place a breakpoint in the lambda, it will never be hit.

TheREST  client gets correctly injected into `AbstractSormasToSormasInterface`, but the call to `post` in `AbstractSormasToSormasInterface.shareEntities` is basically a noop as the `thenAnswer` of the mock is never executed. 

Interestingly, the Mocks for the S2S config (i.e., `mockDefaultServerAccess`) work perfectly fine.

### Steps to Reproduce
1. Run `SormasToSormasCaseFacadeEjbTest.testShareCase`. Although the assertions in `thenAnswer` are wrong, the test passes.

### Expected Behavior
Test passes, but with `thenAnswer` being called.

--- 
@StefanKock any idea?

**Comment by DavidBaldsiefen** [comment]
The changes made here revealed that some of the tests were no longer up-to-date with actual methods in the backend. To ensure the same QA tests are performed, an additional `SormasToSormasEncryptionServiceTest` should be created
