### ISSUE TITLE
Refine the split of jurisdiction and place of stay [5]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5852]
### Feature Description

The place of stay was recently split into the jurisdiction of the case and the place of stay. This was implemented to allow users to enter case data properly where the cases place of stay differs from its jurisdiction.
### Problem Description

The split of place of stay now makes the reporting district field obsolete because the jurisdiction of the case will always be the district that reports the case. The problem that arises now is that the fallback for the mapping to SurvNet considers the place of stay when reporting district is missing and does not consider the jurisdiction if different from the place of stay. This results in health departments reporting for other districts which is incorrect.

### Proposed Change

- Move the jurisdiction above the place of stay (these should stay compulsory) and put the check boxes underneath the location fields
- Always enable the jurisdiction fields and make them the default entry
- Revert the logic of the checkbox "Responsible jurisdiction of this case differs from its place of stay" and enable additional region, district and community fields under the place of stay if selected. Otherwise, leave them disabled.
- When unchecked, the jurisdiction serves as the location information
- Add the jurisdiction also to the case creation form with the same logic in association with place of stay
- **If feasible (tbd):** Remove the field reporting district and migrate the districts to the jurisdiction districts, fill the region according to the respective region references

**Updated specifications:**
* Move the responsible jurisdiction above the place of stay; move the checkboxes between the jurisdiction fields and the "Place of stay" heading
* Always enable the responsible jurisdiction fields and make them mandatory
* Write database migration script that for each case in the system:
  * If the responsible jurisdiction fields are empty AND "reporting district" is empty OR the same as the place of stay district, copy the place of stay region, district and community over to the responsible jurisdiction fields AND clear the place of stay region, district and community
  * If the responsible jurisdiction fields are empty and "reporting district" is NOT empty AND differs from the place of stay district, copy the reporting district over to the responsible district and also fill in the responsible region with the region of the reporting district (reporting region is not stored in the case, so this requires to consult the district table)
  * If the responsible jurisdiction is filled in, no migration is needed
* Remove the "responsible district" field from cases (no database script needed in the mobile app because SQLite doesn't support DROP COLUMN, just remove the field from the data model)
* Change the caption of the checkbox "Responsible jurisdiction of this case differs from its place of stay" to "Place of stay of this case differs from its responsible jurisdiction"; if unchecked, the place of stay region, district and community should be hidden, cleared, and made optional; if checked, the place of stay region, district and community should be visible, and region and district need to be mandatory;
* Place of stay facility- and point of entry-related fields need to stay as they are right now, i.e. they stay mandatory even if the place of stay does not differ from the responsible jurisdiction, so no need to change anything about those
* Add the responsible jurisdiction to the case creation forms (i.e. case creation forms need to work exactly as the edit forms in regards of jurisdiction fields), both in web and mobile
* Adjust the line listing form and logic - use responsible region, district and community instead of place of stay region, district and community
* Change all backend logic to incorporate these changes, i.e. responsible jurisdiction is always present and adjusted place of stay is optional; if I'm not mistaken, logic about task and user assignments don't need to be changed because they already prioritise users from the responsible jurisdiction over those from the place of stay; however, there's probably a ton of other logic that needs to be adjusted; for example when calculating the jurisdiction for contacts - those fall back to the place of stay of the case if they're emtpy, but now have to fall back to the responsible jurisdiction of the case
* Make sure that case import works accordingly, i.e. it's required to specify a responsible region and district, and a place of stay facility, but it's not necessary to specify a place of stay region and district (probably need to change the validation logic in CaseFacadeEjb)
* If the place of stay region, district or community is referenced in the UI, e.g. in grids (case directory), change it to the responsible region, district or community
 
### Additional Information

Example where place of stay equals jurisdiction:
<img width="480" alt="jursidictionPlaceOfStay2" src="https://user-images.githubusercontent.com/70317594/122423373-29e34d00-cf8e-11eb-965f-394e7f311dd2.PNG">

Examples for differing locations
<img width="485" alt="jursidictionPlaceOfStay" src="https://user-images.githubusercontent.com/70317594/122423368-28b22000-cf8e-11eb-8f20-af365769d616.PNG">

<img width="479" alt="jursidictionPlaceOfStay3" src="https://user-images.githubusercontent.com/70317594/122423386-2b147a00-cf8e-11eb-9281-9c12cdd7c3ff.PNG">

**Comment by kwa20** [comment]
@markusmann-vg @MateStrysewske @JaquM FYI

**Comment by MateStrysewske** [comment]
@kwa20 I've added updated (and more extensive) specifications to the proposed change. I have no idea what we should do about the line listing (and line listing import), can you please propose a change here, i.e. how it should look like? Apart from that, are you fine with the proposed specifications? I'll talk to Levi now and discuss whether the database migration is possible.

**Comment by kwa20** [comment]
@MateStrysewske 

> Write database migration script that for each case in the system:

> If the responsible jurisdiction fields are empty and "reporting district" is NOT empty, copy the reporting district over to the responsible district and also fill in the responsible region with the region of the reporting district (reporting region is not stored in the case, so this requires to consult the district table). Further, check the box "

Under this point, I would maybe add the following:
- If the responsible jurisdiction fields are empty and "reporting district" is NOT empty **AND differs from the district in place of stay**, copy the reporting district over to the responsible district and also fill in the responsible region with the region of the reporting district (reporting region is not stored in the case, so this requires to consult the district table). Further, check the box "Place of stay of this case differs from its responsible jurisdiction" and set the region and district in place of stay according to the previously set region and district in place of stay that differed from reporting district.

Considering line listing, I guess that using the responsible region and district instead of region and district would work. We don't give users the option to specify that the jurisdiction differs from the place of stay while using the line listing feature but this is also what it was like before. We assume that it matches and users could still change it on the respective case information.
There are plans to adjust and extend the line listing feature for cases in the future but this should definitely be done in a separate issue.

Everything else looks good to me

**Comment by kwa20** [comment]
I tested on test-de.sormas.netzlink.com and noticed that if facility is selected under place of stay, the facility cannot be chosen if the place of stay does not differ from the jurisdiction.

<img width="444" alt="jursidictionPoS" src="https://user-images.githubusercontent.com/70317594/123648283-1d31e500-d829-11eb-9e81-ecb19f11ce11.PNG">
<img width="449" alt="jursidictionPoS2" src="https://user-images.githubusercontent.com/70317594/123648300-1f943f00-d829-11eb-979f-94746ffd2cea.PNG">

This would be necessary in order to allow valid data entry for cases in facilities.

**Comment by MateStrysewske** [comment]
@leventegal-she @alexcaruntu-vita also observed that changing the responsible district does not correctly update the responsible community dropdown - can you check that as well?
