### ISSUE TITLE
Statistics > Database Export > Countries.csv contains location information

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5853]
### Bug Description

Database export: Instead of the country list, the locations list is downloaded.

### Steps to Reproduce

1. Statistics > Database Export
2. Select 'Countries' > Export > Countries.csv downloads, but contains locations data

### Expected Behavior

Countries data in countries.csv file

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/122449015-afbec280-cfa5-11eb-8980-97d267a557f1.png)
![image](https://user-images.githubusercontent.com/65529128/122449224-eac0f600-cfa5-11eb-83d7-d3bc214b4e73.png)

### System Details

* Device: 
* SORMAS version: 1.60.2
* Android version/Browser: Google Chrome
* Server URL: stable-release-ch.sormas.netzlink.com
* User Role: admin, national user

**Comment by michadavid** [comment]
Thank you internationalizing this issue, @Candice-Louw

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of SORMAS: 1.61.0-SNAPSHOT on test.sormas.netzlink.com
