### ISSUE TITLE
Reset Filter does not work when user switches the view from Groups to Events

### ISSUE THREAD

**Issue by raghupola-vg** [hzi-braunschweig/SORMAS-Project#5862]
### Bug Description

Reset filters on events view does not work when a user searches for a group in the Groups view and then switches back to Events View without clicking on Reset filters, 

### Steps to Reproduce

1. Login to Sormas as NatUser
2. Click on events and switch to Groups view
3. Search for a group and then switch to Events view without clicking on Reset filters
4. The same filter is carried/seen on Events view as well.
5. Try clicking on Reset filters while on Events view and see if the filters are reset. (It can be reset only when user goes back to Groups view and use the rest filter and back to events view and clicking on Reset filter) 

### Expected Behavior

Reset filters should work seamlessly even when different views are changed

### System Details

* Device:
* SORMAS version: 1.61.0-Snapshot
* Android version/Browser: chrome
* Server URL: test-performance.sormas.netzlink.com
* User Role: NatUser

**Comment by af-pwo** [comment]
Version: 1.61.0-SNAPSHOT
Opera Version:76.0.4017.177

QA passed.

Filters reset seamlessly in events and group view.
