### ISSUE TITLE
Statistics > Database export > `Place of Stay` not exported for Cases

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5867]
### Bug Description

Not sure if bug, or change - 
The field "Place of stay" in the Case mask is not included in Statistics > Cases (select all) "cases.csv"  export.
![image](https://user-images.githubusercontent.com/65529128/122576091-a25f1200-d051-11eb-9497-da24349d87fe.png)

### Steps to Reproduce

1. Statistics > Database Export
2. Select 'Cases' > Export

### Expected Behavior

Place of stay data included in export.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/122575805-61ff9400-d051-11eb-8a33-fce84140ae5d.png)

### System Details

* Device:
* SORMAS version: 1.60.2
* Android version/Browser: Chrome
* Server URL: stable-release-ch.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

https://github.com/hzi-braunschweig/SORMAS-Switzerland/issues/198

**Comment by MateStrysewske** [comment]
@Candice-Louw Place of stay is a generated field based on the facility; it is not actually part of the database, which is why it also can't be exported.

**Comment by michadavid** [comment]
@MateStrysewske thank you for the answer. Can you please tell us the field name(s) used to deduce the value of "Place of stay"?

**Comment by MateStrysewske** [comment]
@michadavid It purely depends on the `healthFacility` field. If its value is the id of the static facility `NO_FACILITY`, opening a case will select the place of stay "Home". In any other case, "Facility" will be selected.
