### ISSUE TITLE
Sample synchronization issues

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5877]
### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by bernardsilenou** [comment]
@obinna-h-n  @Chinedar @foyiri  
Please can you upgrade and let us know if the issues address in version 1.60.3 resolved the issues mentioned in #6064 .
We would need this feedback from you in order to decide on the next steps.
Thanks
