### ISSUE TITLE
Legend values overlapping and squeezing the charts

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#5883]
### Bug Description

We had requested to have a customizable legend values that allow us define multiple values and colors for the same legend value.  Instead of repeating the same set of variables for the same legend value or color. 
### Steps to Reproduce

1.
2.

### Screenshots

![2529AADF-8FEE-41AF-BB99-F614016D9285](https://user-images.githubusercontent.com/60390281/122769731-d2393000-d272-11eb-86a7-3319cc9bf3d3.jpeg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@tomabadaniel The feature that you described has been added to the system quite some time ago. What exactly is missing?

**Comment by MateStrysewske** [comment]
Not a bug because it's referring to a feature that has not yet been implemented (#3364)
