### ISSUE TITLE
Facility category and type filters do not filter on case directory [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5889]
### Bug Description

Trying to filter for facility category or facility type does not result in any filtering of the list on the case directory.
### Steps to Reproduce

1. Navigate to the case directory
2. Select a facility category and apply the filters
3. Select a facility type and apply filters

### Expected Behavior

facility category and facility type should filter for the respective selection according to the place of stay of the case.
### Screenshots

<img width="842" alt="facilityTypeFilterIssue" src="https://user-images.githubusercontent.com/70317594/122793428-7e066e00-d2bb-11eb-8ef3-81b1e7ac5036.PNG">
<img width="846" alt="facilityCategoryFilterIssue" src="https://user-images.githubusercontent.com/70317594/122793445-8363b880-d2bb-11eb-8d0c-865f2a665f8f.PNG">

### System Details

* Device:
* SORMAS version: 1.59.2/1.60.2/
* Android version/Browser:
* Server URL: test1401.sormas-oegd.de, musterstadt.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 The filters you mentioned are currently only there in order to be able to select a facility, they don't serve a filtering purpose themselves. This would be a new feature.

**Comment by abrudanancuta** [comment]
Validated on **test-de.sormas.netzlink.com** with this version 1.67.0-SNAPSHOT
