### ISSUE TITLE
Synchronization icon still visible after case is successfully synchronized.

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#590]
The synchronization icon is still visible on the informant's app after case has been successfully synched and reflects in the server. The informant does not know whether the case has synched or not until he/she calls.

**Comment by MartinWahnschaffeSymeda** [comment]
From an old version - no longer valid.

**Comment by hzi-braunschweig** [comment]
synchronization succesful on app but synchronization icon still remains unnsynchornized for ghana app

**Comment by MateStrysewskeSym** [comment]
I think the problem is that the list is still not properly reloaded.

**Comment by MateStrysewskeSym** [comment]
- [ ] move "moveAround" call to after invalidate
