### ISSUE TITLE
IMS not visible on DEMIS in Sormas

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#5902]
If I compare the DEMIS message from Sormas with the one from SurvNet, I recognized that the Typing ID is not visible in Sormas but in SurvNet.

On SurvNet there are more fields under "sample" as on SORMAS.

### Feature Description
Please add the Typing ID on the visible DEMIS message and autofill it on the pathogen field "Typing ID".

**Comment by Marko-ilmkreis** [comment]
@herrling-LRA-KYF is this not the field Typing-ID (Typisierungs-ID) as mentioned in #4859?

![image](https://user-images.githubusercontent.com/74791118/122896383-4f36d900-d349-11eb-8ef7-185108923ae6.png)

**Comment by herrling-LRA-KYF** [comment]
@Marko-ilmkreis yes it is, but I not have this on the DEMIS message from Sormas, but I saw this on the DEMIS message from SurvNet:

SORMAS:
![sormas](https://user-images.githubusercontent.com/79255722/122897459-51e5fe00-d34a-11eb-98b7-9bbdd667a565.jpg)

SURVNET:
![survNet](https://user-images.githubusercontent.com/79255722/122897473-54485800-d34a-11eb-97d2-d65f8f20c221.jpg)

**Comment by Marko-ilmkreis** [comment]
@herrling-LRA-KYF we don't use DEMIS with Sormas, but is the field typing-ID filled by Sormas/Demis and its "only" not shown at the message? Or is Sormas not mapping it and therefore not filling the field and not showing in the message?

**Comment by herrling-LRA-KYF** [comment]
@Marko-ilmkreis Both. Its not shown at the message and not mapped to the field.

**Comment by FredrikSchaeferVitagroup** [comment]
The two problems described here (1. The typing Id is not transferred to SORMAS, 2. The typing Id does not show in the HTML representation of a lab message) will probably be solved by the two issues mentioned above.

**Comment by markusmann-vg** [comment]
covered with 
- [DEMIS2SORMAS] Automatically prefill Typing Id #5917 
- [DEMIS2SORMAS] Handle New Profile: Convert new profile messages to HTML [2] hzi-braunschweig/sormas-demis-adapter#23

**Comment by herrling-LRA-KYF** [comment]
seems that this is not fixed at the moment.
We got a DEMIS message via survnet with "typing id" and in SORMAS there are no information about the "typing id".

SORMAS:
![image](https://user-images.githubusercontent.com/79255722/133575995-cc18a32c-1b44-42cb-8c9e-75742e27d774.png)

**Comment by kwa20** [comment]
@herrling-LRA-KYF @FredrikSchaeferVitagroup This might be due to the 1.63 version not having been updated on german systems yet. The milestones of the mentioned issues are suggesting an implementation in 1.63/1.8
