### ISSUE TITLE
Immunizations III: Immunization list for cases, contacts and event participants [5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5905]
### Situation Description

Concept issue for immunizations: #4081

### Feature Description

Extend the case, contact and event participant forms with a list of immunizations with matching disease associated to that person.

For all the new elements, ONLY show them if the `IMMUNIZATION_MANAGEMENT` feature configuration is enabled.

#### Web app
* Add another card to the right side of the cases (after events), contacts (after samples) and event participant (after contacts) form; behaves exactly like the other lists
* Only accessible for users with the `IMMUNIZATION_VIEW` user right
* Show the following information for individual list entries:
  * Immunization UUID
  * Means of immunization
  * Management status
  * Immunization status
  * Immunization period (defined by start and end date)
* As defined above, only show immunizations that match the case/contact/ep disease; DON'T show this list at all for event participants that are associated with an event that has no disease set
* Allow the user to open the edit form of the immunization by clicking on an edit icon to the right
* Add a "New immunization" button that opens the immunization creation form (only accessible for users with the `IMMUNIZATION_CREATE` user right); hide the person and disease fields (set the disease information to the case disease information), make all of them non-mandatory and directly assign the case/contact/ep person to the new immunization (immunization duplicate detection still needs to take place)

#### Mobile app
* Add new tabs for Immunizations to cases, contacts and event participants (same locations as above)
* List items should contain the same information and behave similar to the definitions for the web app; open immunizations by tapping on the item (no need for a dedicated edit button)
* Make sure that it's consistend with other sub lists in the mobile app

**Comment by kwa20** [comment]
@MateStrysewske I think rather than just having a new immunizations button, we would rather need a link option that also allows the creation of new immunizations for users to also be able to link existing immunizations without having to go through duplicate detection, similar as seen for events
