### ISSUE TITLE
Non standard date format [2]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#591]
Date formats  are not consistent- for example in hospitalization, date of admission and date of isolation have different formats on .symeda server. We have to check all the date fields and choose a standard format.
Best,
Bernard

**Comment by MartinWahnschaffeSymeda** [comment]
Looks like the date format changes are causing a bug in android. Now selects year 18 instead of 2018.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] date field should accecpt dates entered in other formats as well (e.g. 15/08/2018, 15/08/18, 15.08.18, ...)

**Comment by MartinWahnschaffeSymeda** [comment]
Making the date field accept other formats as well is a lot of work and nt worth it right now.

Besides this we have the problem that some mobile devices (e.g. the tecno) can't select nigerian english as language and thus not set the correct date format. I had to change this back to a static format of dd/MM/yyyy now. This needs to be changed when we do internationalization of SORMAS (see #231).
