### ISSUE TITLE
Cases with the outcome "unkown" are shown in the dashboard-map for the wrong epi week

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5915]
### Bug Description

Some cases are shown in the map of the dashboard, even if the report date is not within the selected period and the outcome is set to unknown.

It seems like that the date of the unknown outcome is set to the date you select the outcome, but not shown and not editable in the case. 

![image](https://user-images.githubusercontent.com/74791118/123048459-b95d8580-d3fe-11eb-80ac-95d520060cbf.png)

![image](https://user-images.githubusercontent.com/74791118/123048484-be223980-d3fe-11eb-933b-28e41bfbc290.png)

### Steps to Reproduce

1. create a case with a report date long time ago
2. set the outcome to unknown
3. It should shown in the map 

### Expected Behavior

Cases with unkown outcome should only shown for the epi-week/date of the report date or the date of first symptoms.

### System Details
* SORMAS version: 1.59.2
* User Role: National user, Admin

### Development Specifications

Show the outcome date field when the outcome "Unknown" is selected (also in the mobile app) and make sure that cases with "Unknown" outcome and an outcome date don't appear on the dashboard map when the date filters are set to after the outcome date

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Since "Unknown" is a final outcome as well (just not a desirable one), I'd suggest that we should also enable the date field for this outcome. Would that be a satisfying solution for you as well?

**Comment by Marko-ilmkreis** [comment]
> I'd suggest that we should also enable the date field for this outcome. Would that be a satisfying solution for you as well?

@MateStrysewske Yes, this would be helpful. Thank you.

**Comment by DavidBaldsiefen** [comment]
@Marko-ilmkreis is there a defined symptom onset for your case? I tried it myself, and while your assumption that the outcome-date is set to the current date is correct, the outcome-date should not be relevant for the map-filter.

**Comment by Marko-ilmkreis** [comment]
@DavidBaldsiefen There is a sympom onset-date, but is also in the past:

![image](https://user-images.githubusercontent.com/74791118/123069279-ec117900-d412-11eb-93ca-bb89ec6f1df5.png)

**Comment by DavidBaldsiefen** [comment]
@Marko-ilmkreis I see, the reason is you are using the "Show epidemiological situation" checkbox which takes the outcome into consideration. I will then proceed with the fix proposed above

![image](https://user-images.githubusercontent.com/4655486/123069943-97bac900-d413-11eb-9232-f57393cd4030.png)

**Comment by Marko-ilmkreis** [comment]
@DavidBaldsiefen in 1.59.2 this function is not available. We are still waiting on 1.60.3 ;-)

![image](https://user-images.githubusercontent.com/74791118/123071168-b66d8f80-d414-11eb-912b-5689c0358e3d.png)

**Comment by DavidBaldsiefen** [comment]
I see. That makes perfect sense, as the point of the checkbox is actually to use the "old" (current for you) calculation method :)

**Comment by RazvanHodisan** [comment]
Verified on test-de, Version: 1.61.0-SNAPSHOT
