### ISSUE TITLE
[DEMIS2SORMAS] Automatically prefill Typing Id

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#5917]
### Situation Description

A DEMIS notification prorvides a "Typisierungs-ID" as `Specimen.processing.extension:transactionID`. It relates to the `PathogenTest.typingId` in SORMAS, and should automatically transferred to this attribute when processing lab messages.

### Feature Description

- [ ] add a testTypingId to the LabMessage dto and entity (or to the TestReport dto and entity if already implemented).
- [ ] automatically transfer its value to the `PathogenTest.typingId` when processing lab messages

### Additional Information

The adapter part is to be done in [#21](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/21)

### Open Question

- The typing Id field does only show for specific test types in SORMAS (`PathogenTestType.PCR_RT_PCR`, `PathogenTestType.DNA_MICROARRAY` and `PathogenTestType.SEQUENCING`). Should SORMAS check whether a testTypingId in a lab message (or test report) goes along with one of those test types?
ANSWER: Yes

**Comment by Marko-ilmkreis** [comment]
@FredrikSchaeferVitagroup This issue is simlar to #5902.

**Comment by FredrikSchaeferVitagroup** [comment]
@Marko-ilmkreis Yes, thank you. We looked a #5902 and decided to create two tickets out of it (one for showing the typing id in a lab message, and this one for automatically transferring it). I would have mentioned this in #5902, but you were just too fast for me :)

**Comment by FredrikSchaeferVitagroup** [comment]
@JaquM Could you please link the ticket for showing the typing id in a lab message, once you created it?

**Comment by herrling-LRA-KYF** [comment]
@FredrikSchaeferVitagroup what is the status here?

**Comment by FredrikSchaeferVitagroup** [comment]
@herrling-LRA-KYF So far, this issue has not been prioritized. This is usually done by members of the HZI, if appropriate.  @JaquM might be able to go forward here.

**Comment by FredrikSchaeferVitagroup** [comment]
Work on this issue can't be started until the open question in [#21](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/21) is answered.

**Comment by herrling-LRA-KYF** [comment]
can't open this question (Link)

**Comment by FredrikSchaeferVitagroup** [comment]
@herrling-LRA-KYF : I'm sorry, the question refers to something that is not public at the moment. It is to be dealt with by a member of the HZI.
