### ISSUE TITLE
[SORMAS2SORMAS] Log API errors

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#5924]
### Situation Description

When sharing information (S2S) by making use of the API, error messages are generic in nature and not written to the database.  This makes finding the cause of an error difficult.

### Feature Description

Allow API error messages to be written to the database so that logs may be requested to determine the cause of a particular error.

### Possible Alternatives

Open to alternative suggestions.

### Additional Information

![image](https://user-images.githubusercontent.com/65529128/123084261-37cb1f00-d421-11eb-82d8-6169884d4b66.png)

**Comment by JonasCir** [comment]
Hm I think this could be possibly closed @SahaLinaPrueger @Candice-Louw ?

Errors got more descriptive over time and they are now properly logged so we can follow up on what went wrong.

If we encounter isolated cases where an error is not descriptive, we can still track it separately.

**Comment by Candice-Louw** [comment]
Closing as alternative approach to solve this has been proposed by @JonasCir in comment above.
