### ISSUE TITLE
New Login Page Design [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#593]

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig How exactly should the login page look like. Please provide a mockup picture.

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/43323802-e769b336-91b2-11e8-85b7-474217ef1d88.png)
@MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
Ok, we will put this into the next sprint. Bugs & stability have priority now

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] implement design as in mockup
- [ ] on small screens the left part should be displayed below the form (as in the current design)

Ignore the "remember me" for now.

**Comment by MartinWahnschaffeSymeda** [comment]
Just realized that we are still using the oldschool LoginForm. This has to be replaced with our own implementation.

**Comment by MateStrysewskeSym** [comment]
Duplicate of #1194
