### ISSUE TITLE
Add disease variant details field [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#5935]
### Situation Description

Users would like to add further information to disease variants, which are not intended to become their own value in the disease variant drop-down field. These could include many things like e.g. specific mutations, codes, etc.
### Feature Description

To accommodate this need, introduce a disease variant details freetext field
- This field should only get enabled by determined values in the disease variant field. Therefore, add an option in the customizableenumvalue table to determine which values enable the subsequent free text field.
- The field should be hidden otherwise
- Add this details field also to pathogen tests as 'tested disease variant details'
- When the user decides to adopt the variant in the case, also migrate the tested disease variant fields to the details field in the case.
- Extend exports
### Additional Information

<img width="498" alt="variantDetails" src="https://user-images.githubusercontent.com/70317594/123230635-bedace80-d4d7-11eb-9649-8d3a0975478e.PNG">
<img width="340" alt="variantDetails3" src="https://user-images.githubusercontent.com/70317594/123237937-622ee200-d4de-11eb-8748-5c2e27319f70.PNG">

This field will be mapped to SurvNet

**Comment by MateStrysewske** [comment]
- [ ] Extend the Wiki article with instructions on how to set properties
