### ISSUE TITLE
Insertion of the investigation start and end dates in the detailed export of the event directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5938]
### Situation Description
To date, when doing a detailed export of the event directory, the variables 
- investigation start date
- investigation end date 

do not appear.

### Feature Description

Add these two variables in the detailed export

### Additional Information
@ftavin @bernardsilenou

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
