### ISSUE TITLE
Action directory - insertion of the date of the action in the directory of actions

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5939]
### Situation Description

There are three types of dates referring to the action:
- the date of creation of the action
- the date of modification of the action
- the date of the action

The actions directory only shows the creation and modification dates. The date of the action is not shown.

### Feature Description

- Add the date of the action in the actions directory, with the possibility of sorting.
- Add a filter to filter the directory of actions on actions planned or carried out on a day
- Add this information in the basic and detailed exports.

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by AndyBakcsy-she** [comment]
The ticket #6571 is related to this one.,
