### ISSUE TITLE
Addition of a "Specific risk" field in the events file to define a media or political risk for example

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#5940]
### Situation Description

To date, an event can be defined according to its epidemiological risk (risk level => high, moderate, low). In addition, there is another risk which, to date, cannot be mentioned by the teams: it is a media or political risk for example.

The two risks are completely independent: a cluster with a high epidemiological risk may or may not have any media risk. It is therefore not possible to complete the drop-down list with additional modalities because users need to define both epidemic risk and other types of risk including, for example, media risk.

### Feature Description

We propose :
• rename the “risk level” variable to “epidemiological risk level”
• create an variable "other specific risk" which would take the form of a drop-down list with configurable modalities for each server.

This data should appear on the events directory (but not actions directory) and be used to sort/filter (+ basic and detailed export)

### Possible Alternatives

Create an “other specific risk” variable in drop-down list format with four modalities defined in the code:
- media risk,
- political risk,
- other risk,
- unknown

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by ftavin** [comment]
@carolinverset I was wondering if this field should be multi-valued (an event can have both media and political risk for example)

Note : you omit to specify that this data should appear on the events directory (but not actions directory) and be used to sort/filter (+ basic and detailed export)

**Comment by carolinverset** [comment]
@ftavin @bernardsilenou 

Ah yes, you are right. Do you see a solution for a type of variable allowing both the basic configuration to allow other countries to define themselves the type of risk and the selection of several modalities?

Without basic configuration, we could have imagined several checkboxes as in the contact directory (see screenshot) but that may be complicated with the possibility of configuring, right?

Maybe other users have ideas too?

thank you !

ps : I add the omissions in the initial ticket

**Comment by bernardsilenou** [comment]
@ftavin I think with the configurable drop-down fields, I am not sure if we can have multiple options 
@MateStrysewske  any suggestion?

**Comment by MateStrysewske** [comment]
Customizable enums unfortunately won't work with multi-value selection. The feature could probably be extended accordingly though, since the columns are essentially only text columns and could just as well contain a list of enum values that would then be parsed. The default representation for such a field would then probably be a list of checkboxes because we currently don't have a dropdown component hat supports multiple selections.

**Comment by carolinverset** [comment]
@MateStrysewske @bernardsilenou @ftavin @emond-fuseau
Following this morning's meeting, we recommend staying on a drop-down list whose modalities can be configured in the database. It will then be possible to imagine four modalities: 

- political risk, 
- media risk, 
- political and media risk
- autre

Is it ok for you ?

**Comment by MateStrysewske** [comment]
@carolinverset Yes, fine by me - if you want to go ahead and implement this, make sure to use the customizable enum feature please. Let me know if you have any questions on how to use the system.

**Comment by MateStrysewske** [comment]
Leftovers:
* Update specific risk list depending on the selected disease
* Don't show the field in the app's read fragment if it's not filled in
