### ISSUE TITLE
Merge Duplicate Contacts page does not return any results.

### ISSUE THREAD

**Issue by RazvanHodisan** [hzi-braunschweig/SORMAS-Project#5952]
### Bug Description
Created 2 contacts with same name and birthday. Tried to look for the contacts to merge them but no results are listed.

### Steps to Reproduce

1. Created 2 contacts.
2. Wento into the Merge Duplicate Contacts page

### Expected Behavior
The page should return the available duplicates which can be merged.

### Screenshots
![image](https://user-images.githubusercontent.com/53563072/123400265-3d09a480-d5ae-11eb-9388-5b92f23f9c16.png)
![image](https://user-images.githubusercontent.com/53563072/123400291-4266ef00-d5ae-11eb-862d-9c985db8619d.png)

### System Details

* Device:
* SORMAS version: Version: 1.61.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com/
* User Role: admin

**Comment by DavidBaldsiefen** [comment]
I think I had this recently and the issue was that both contacts needed to be associated to the same case. So maybe this is actually intended behaviour? @MateStrysewske

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Thanks! I wasn't aware of that anymore.
