### ISSUE TITLE
Replace the vitagroup logo in the standard sidebar

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5954]
### Feature Description

The sidebar contains three logos in the "powered by" section.

### Problem Description

The vitagroup logo is not up-to-date anymore.

### Proposed Change

Replace the logo with the current version.

**Comment by RazvanHodisan** [comment]
Verified on test-de and local on  Version: 1.61.0-SNAPSHOT
