### ISSUE TITLE
Detailed population & incidence statistics [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#598]
In addition to the case counts the statistics should show the case incidence (cases per population).

Important: The filters and groupings need to be applied to the reference population as well. This is relevant for region, age and gender!

There may be goupings/filters where the necessary population data is not available. In this case it's not possible to show the incidence (e.g. gender combined with age grouping).

- [x] add population data to regions and districts: males, females, under 1, 1-4, 5-14, 15+ #1084
- [x] get population data for country/regions/districts with filters and groupings
- [x] calculate incidence
- [x] add checkbox/select to switch between case count and case incidence.
- [x] update the map legend accordingly
- [x] either include null results in the query and display them as N/A in the table or display a hint that tells the user which data is missing
- [x] if filtering by year, use the highest selected year as the reference for projected population calculation
- [x] if the reference date for projected population calculation is not the current year, display a hint to the user specifying the reference date
- [x] make sure that total values are correctly calculated for the table and charts (potentially hide the total value in stacked columns)
- [x] disable pie and stacked column as visualization options for incidence
- [x] crop incidence to two decimal digits

Required but maybe optional for now:
- [x] Merge age groups that the data is filtered/sorted by if possible
- [x] Allow users to choose the divisor for the calculation (dropdown or text field next to checkbox)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig What is the progress with the population data for Nigeria? As far as I remember we are supposed to add data split by sex and age group. Which age groups will be available?
What about Ghana?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
Ghana had released their population data stratified by sex and age groups. I will send that to you again as I had sent it to you in October last year. For nigeria, I will follow up with them to see how far they have entered the data from the paper base.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Totals are calculated correctly now.
I did have time to fully update the map and chart with this.
Feel free to give me a phone call..

**Comment by MartinWahnschaffeSymeda** [comment]
Next steps:

- [ ] include zero case count param in query
- [ ] include all population results in query - even for entries without cases (full join on population info)
- [ ] make sure adding zero values for missing entries works

**Comment by MartinWahnschaffeSymeda** [comment]
Refactorings:

- [ ] use apache commons pair with hashmap instead of nested maps
- [ ] use StatisticsGroupinKey instead of object for the hashmap pair
- [ ] rename test method to population query

**Comment by MateStrysewskeSym** [comment]
- [ ] Repair unit test
