### ISSUE TITLE
Don't show delete button in campaign creation form

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#5984]
### Bug Description
Can lead to NullPointerException at de.symeda.sormas.backend.common.AbstractCoreAdoService.delete(AbstractCoreAdoService.java:19).

**Comment by DavidBaldsiefen** [comment]
Could you elaborate on how to reproduce the NPE?

**Comment by MartinWahnschaffe** [comment]
Hm, interesting. I saw a NullPointer related to deleting campaigns and I saw that we have the delete button in the create form, so I was expecting that this is related.

Anyways, the goal for this issue is to not show the delete (and also not the archive) button in the campaign create form. E.g. you can login as admin and go to https://test-afghanistan.sormas.netzlink.com/sormas-ui/#!campaign/campaigns, then press the create button to see this.

**Comment by DavidBaldsiefen** [comment]
@MartinWahnschaffe alright, I marked you as reviewer :)
