### ISSUE TITLE
Transfer to SurvNet: Mutations of the SARS-CoV-2 Delta variant not shown

### ISSUE THREAD

**Issue by ThomasVitus** [hzi-braunschweig/SORMAS-Project#5985]
If selected in SORMAS, mutations of the of SARS-CoV-2 Delta variant don't show up correctly in Survnet. They are just being shown in SurvNet as "Other" plus being mentioned in the comment section. They could be specifically selected in SurvNet, but the transfer from SORMAS to Survnet is not working here.

**Comment by leventegal-she** [comment]
This seems to be a configuration issue.
The converter does "B.1.617.2" from sormas map to "16172" in SurvNet.

If in SurvNet it is shown as "Other" it means in sormas the Delta variant has a wrong value.

@HolgerReiseVSys @ThomasVitus, @markusmann-vg  can you please make sure SORMAS is configured properly?

**Comment by markusmann-vg** [comment]
I asked @kwa20 to take a look. I checked the Schema Version and also the mapping table and it should be linked correctly. As you said: 
Survnet: 16172 // Sormas: B.1.617.2

**Comment by markusmann-vg** [comment]
Works on test environement

**Comment by kwa20** [comment]
@ThomasVitus Can you please check if the "B.1.617.2" variant is correctly deposited in the customizable enum value table? In order for it to be mapped correctly, the value should exactly be as described in quotation marks above. 
- You can check the values by exporting the customizable enum value table in statistics/data base export. 
- In the export, check the column "customizableenumvalue" for "B.1.617.2"

**Comment by ThomasVitus** [comment]
@kwa20 Yep, the "B.1.617.2" variant is correctly deposited and transferred to SurvNet, thnx.

**Comment by HolgerReiseVSys** [comment]
This issue may be due to #6327

**Comment by HolgerReiseVSys** [comment]
This ticket may be due to #6327
