### ISSUE TITLE
Setting missing geo-coordinates runs into an error

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#5992]
### Bug Description

We were trying to set the missing geo-coordinates several time, but it always run into an error/time-out after approx. 15 sec. We don't know were the error comes from as the error message is very unspecific.

We are having 3713 cases without coordinates, for the contacts and ep there is no filter to show it. After using the function 10 times the number of cases hasn't changed, so there are not set any geo-coordinate.

Maybe there are:

* addresses not compatible
* errors in addresses

But I think the tool should just skip this errors and not stop itself.

Maybe @DavidBaldsiefen can help?

### Steps to Reproduce

1. open person directory
2. use the set missing geo-coordinates

### Screenshots

![image](https://user-images.githubusercontent.com/74791118/123769831-fb3c6f00-d8c9-11eb-92f5-f576c93947b8.png)
![image](https://user-images.githubusercontent.com/74791118/123770535-a64d2880-d8ca-11eb-84fd-ac6c67fb7a67.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by Marko-ilmkreis** [comment]
Is missed to mention, that it occurs in 1.59.2 on our own instance at ITZ Bund. As I don't have access to an test-server with working geo-coordinate-setting I cannot test it anywhere else.

**Comment by DavidBaldsiefen** [comment]
@Marko-ilmkreis Do you have access to serverlogs?
It could be possible that the server runs into a timeout when trying to evaluate illegal addresses. This exception used to be caught but I can see now that that `exceptionHandler` was removed, probably by accident

**Comment by Marko-ilmkreis** [comment]
@DavidBaldsiefen Unfortunately now, but I will request the server-logs from Netzlink

**Comment by DavidBaldsiefen** [comment]
Does individually setting coordinates using the needle-button still work?

**Comment by Marko-ilmkreis** [comment]
Yes, that is working fine without any problems.

**Comment by DavidBaldsiefen** [comment]
I tried and it seems to be a uncaught timeout. I already have a fix ready, however if there are a lot of "illegal addresses", each timeout will add another ~10 seconds to the process, so the entire process might take quite some time

**Comment by Marko-ilmkreis** [comment]
@DavidBaldsiefen That is no problem. We can make the first run outside the working hours and so the system has all the time to finish

**Comment by RazvanHodisan** [comment]
Verified on test-de, Version: 1.61.0-SNAPSHOT
