### ISSUE TITLE
Unexpected error occurred 

### ISSUE THREAD

**Issue by horatiu-cosma** [hzi-braunschweig/SORMAS-Project#5996]
### Bug Description

Unexpected error occurred when when edit button is clicked 

### Steps to Reproduce

1. navigate to  https://test-performance.sormas.netzlink.com/sormas-ui/#!contacts/visits/9206c26c-3fb7-4b82-b131-393f13325bf1        or choose another contact with follow-up visit attached 
2. click Edit 

### Expected Behavior

Edit page should be displayed

### Screenshots

![image](https://user-images.githubusercontent.com/83694844/123784053-b6bbce00-d8df-11eb-84b7-f175049d32ab.png)

### System Details

* Device: chrome
* SORMAS version:
* Android version/Browser:
* Server URL:    https://test-performance.sormas.netzlink.com/sormas-u
* User Role:  NatUser

### Additional Information

 ps.   might be related to : https://github.com/hzi-braunschweig/SORMAS-Project/issues/5951

**Comment by MateStrysewske** [comment]
This has likely been resolved with #5951 - I don't encounter any of the two on my local system anymore. Test systems aren't deployed yet and still failing because of that.
