### ISSUE TITLE
Case creation improvements (Feedback from test scenarios 140518)

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#600]
Case creation

- [x] Automatically calculate unit of age when age is selected
- [x] For pick address, replace address, landmark to address or landmark
- [x] Select state or "enter value" as default not "Abia" as the name in the drop down. Also for LGA ,ward and city
- [x] ~~pick GPS coordinate ("Are you currently at case person home?"). hide when not selected (yes)~~ see next comment
- [x] When did the patient visit the hospital? date?
- [x]  Was patient admitted at the health facility? (yes, no , unknown) date of admission and date of discharge
- [ ] ~~Is patient still hospitalized? Yes/no/dontknow. If No, date of discharge appears.~~ -> would require changes in data model

Bug

- [x] After creating previous hospitalization, and saved, error showed "case could not be saved due to internal error"
(worked after refreshing)
- [x] Sort symptoms by alphabetical order. 
- [x] under symptoms creation- date of onset field automatically appears when trying to enter comment field
- [x] Event does not work for surveillance officer. 

Other

- [x] apply GPS question for all addresses
- [x] for animal contacts, under text information- the incubation period should be defined by the incubation period (7 days for Lassa, 21 days for Ebola) automatically. -> #698
- [ ] Think about adding blood transfusion
- [x] For message. NO contact persons/samples have been entered, to add a contact person/sample, please press the plus button at the top right of the tool bar

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] instead of the GPS "guard" field, change the button caption to something like "pick GPS of home address"
- [ ] admitted to health facility -> was patient admitted at the health facility?
- [ ] don't pre-select the region for locations
