### ISSUE TITLE
Epidemiological Data, Transfer to SurvNet: Contacts with Source Case don't show up

### ISSUE THREAD

**Issue by ThomasVitus** [hzi-braunschweig/SORMAS-Project#6000]
**Contacts with source case known**
If you choose "Yes" but do not have a case linked to the "Epidemiological Data"-page, it will lead to "Source case unknown" in SurvNet. We only have a case that we can link to the "Exposure investigation" if that case lies in our jurisdiction. But in all other circumstances we cannot use this feature properly, without creating a lot "Not a case"-cases.

This problem could be solved if the "Yes"-Field also leads to a "Source case known" in SurvNet.

**Comment by ThomasVitus** [comment]
![Screenshot_2021-06-29 SORMAS](https://user-images.githubusercontent.com/86602055/123915486-d8b95d00-d980-11eb-8631-afbedbfd1c85.png)

**Comment by MateStrysewske** [comment]
@vidi42 @markusmann-vg @HolgerReiseVSys Sounds like a converter issue to me?

**Comment by HolgerReiseVSys** [comment]
@MateStrysewske Yes, this is related to te converter, but should still remain in this project,
@ThomasVitus Could you please provide the original German term for "Source case unknown" and maybe a screenshot?

**Comment by ThomasVitus** [comment]
"Source case unknown" = "Kontakte mit Indexfall unbekannt" 

Screenshot ...

![Screenshot_2021-06-30 SORMAS](https://user-images.githubusercontent.com/86602055/123933298-87b26480-d992-11eb-95e9-a8cee938e63a.png)

**Comment by HolgerReiseVSys** [comment]
@ThomasVitus I thought this was about a field in SurvNet, and not in SORMAS?

**Comment by ThomasVitus** [comment]
@HolgerReiseVSys Yes, you are right. The SurvNet-wording in German is: "Enger Kontakt mit einem Fall ab 14 Tage vor Erkrankungsbeginn".

Here are the screenshots from SurvNet: 

1.) "Source case known" and linked within "Epidemiological Data" in SORMAS will lead to that result in SurvNet
![Index bekannt_verlinkt](https://user-images.githubusercontent.com/86602055/123960048-23ea6480-d9af-11eb-85c5-8055df253ff1.png)

2.) "Source case known" without providing a case in "Epidemiological Data" in SORMAS will lead to this
![Index bekannt_nicht verlinkt](https://user-images.githubusercontent.com/86602055/123960331-762b8580-d9af-11eb-8830-607d9fc6bae6.png)

**Comment by HolgerReiseVSys** [comment]
@ThomasVitus This works as designed and specified. 
Knowing about contacts with index cases does not necessarily imply that these were close contacts and took place within the last 14 days.
Feel free to get in contact with @kwa20 to discuss possible adjustments.
