### ISSUE TITLE
Separation of responsible region and districts breaks the logic for  POE cases

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6016]
### Bug Description

POint of entry cases can not be created without setting "place of stay of this case differs from responsible jurisdiction == True".
- point of entry (POE) of a case is validated using region and district (ie when place of stay of this case differs from responsible jurisdiction == True).  
- when creating POE cases, POE in the responsible region are not suggested as drop down options in "point of entry"
This should be based on the responsible region and district.
### Steps to Reproduce

1. Create a POE case
2. Under POE, the names are POE linked to the responsible jurisdiction are not suggested to user
3. set `place of stay of this case differs from responsible ` to true and choose same region and district, now you have the names of PEO suggested
4. When saving the case, do not choose place of stay since this is not required for POE cases.
6. During this process of editing or referring the case, system keeps showing the warning message "A problem has occurred: data could not be saved because it was edited in the meantime" This error appears when the same user is editing the form.
7. In case edit form, the place of stay (region, district , etc) cannot be edited. It should be possible to edit it. (this one is an old bug I think so)

### Expected Behavior

- Use responsible jurisdiction when filtering enums for "point of entry"
- if "place of stay of this case differs from responsible jurisdiction == True", then suggest POE in both regions in the dropdown for point of entry
### System Details

* Device:
* SORMAS version: 1.61
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: admin + national user

**Comment by bernardsilenou** [comment]
This issues still need further investigation. I could edit a POE case, created in version 1.58 without place of stay on the web but not on the mobile app.

**Comment by kwa20** [comment]
For reference:
<img width="520" alt="Screen Shot 2021-07-03 at 3 45 18 PM" src="https://user-images.githubusercontent.com/70317594/124356361-f4896100-dc15-11eb-9e81-de05f9a9ca9f.png">
<img width="516" alt="Screen Shot 2021-07-03 at 3 45 59 PM" src="https://user-images.githubusercontent.com/70317594/124356364-f81ce800-dc15-11eb-88d2-889851779dae.png">

**Comment by DavidBaldsiefen** [comment]
> In case edit form, the place of stay (region, district , etc) cannot be edited. It should be possible to edit it. (this one is an old bug I think so)

@bernardsilenou is this also hotfix-relevant if this is an old issue?

**Comment by kwa20** [comment]
@DavidBaldsiefen Since the point of entry sections will experience some major changes quite soon (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/5489), I don't think it would be hotfix relevant since it will possibly be handled with such anyway.

Sorry for answering for you @bernardsilenou
