### ISSUE TITLE
DEA TravelEntry form [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#6025]
### Situation Description

Concept issue for travel entries: #5489

### Feature Description

All elements are only visible on German systems

#### Edit form
* Add a DEA view class that consists of two tabs ("Travel Entry" and "Person") and that is opened when accessing a specific travel entry from the directory
* Read-only for users without the `TRAVEL_ENTRY_EDIT` user right
* Edit rights are based on the responsible jurisdiction and point of entry jurisdiction of the travel entry
* Add a DEAForm that contains UI components for the TravelEntryDto fields
  * Reporting user is read only
  * `Recovered`, `Vaccinated` and `Tested negative` are checkboxes and hidden if no disease has been selected
  * The value of `deaContent` is parsed into a list of text fields; the `CampaignFormBuilder` class can be used as a reference on how to do this, but probably can't be re-used; create a `DEAFormBuilder` class instead that reads the JSON and can also build JSON based on the fields again when the user saves
* Edit form needs to include archive and delete options (only for users with the `TRAVEL_ENTRY_ARCHIVE` and `TRAVEL_ENTRY_DELETE` user right, respectively)
* Responsible jurisdiction and point of entry fields should behave like the responsible jurisdiction and place of stay fields for cases, i.e. add a checkbox "Point of entry jurisdiction differs from responsible jurisdiction" that shows the point of entry region and district fields, point of entry always needs to be required and either depends on the point of entry jurisdiction fields if available or falls back to the responsible jurisdiction fields otherwise

#### Create form
* Reuse the edit form for the create form
* Add person fields, same as when creating a case
* Add a "New travel entry" button to the travel entry directory that opens this form
* Only accessible for users with the `TRAVEL_ENTRY_CREATE` user right
* Use duplicate person detection on save; duplicate travel entry detection is not needed
* Hide the "New travel entry" button if no travel entry has been imported into the system yet; if at least one travel entry is available, build the text fields for the DEAFormBuilder based on the `deaContent` captions of the latest travel entry

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Please allow also the document upload for the travel entries. We are getting from the persons the proof of vaccination, of test and of recovery. So it would be good to have them into the entry available.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis We have to deliver a simplified version of the travel entries as soon as possible to have it in place for the summer vacations. Unfortunately, we won't be able to include document upload in this initial version. It is, however, planned for the future.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Okay, Should I open a new issue for that? If it don't comes for the summer vacations (the current 1.60.3 is still not released in Germany) maybe you can consider to release it together.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Sorry for replying so late, I missed your comment for some reason. We already have an issue for that in place: #5845
