### ISSUE TITLE
Link DEA TravelEntries to cases [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#6026]
### Situation Description

Concept issue for travel entries: #5489 

### Feature Description

Only show these new elements on German systems

#### Cases
* Add a "Resulting case" infobox to the right side of the travel entry form (similar to the source case infobox when opening a contact; should be the topmost element)
* Infobox should contain the same fields as the source case infobox of contacts minus the disease, plus a link to open the case (only if the user has the `CASE_VIEW` user right)
* If the resulting case of the travel entry is null, show a "Create resulting case" button instead; clicking on the button brings up the case creation window in a similar state as when converting a contact to a case (e.g. disease is filled in and disabled, first and last name are filled in and disabled, birth date and sex are filled in and disabled if available)
  * Case origin should be set to "Point of entry" by default, and the point of entry (and region and district or responsible region and district, depending on what is available) be filled in; however, it should still be possible to switch back to "In-country"
  * Create button should only be visible for users with the `CASE_CREATE` user right
* Add a "Travel entries" list to case epi data underneath source contacts
  * Only accessible for users with the `TRAVEL_ENTRY_VIEW` user right
  * Show the following information for individual list entries:
    * Travel Entry UUID
    * Point of entry
  * Allow the user to open the edit form of the travel entry clicking on an edit icon to the right
  * Add a "New travel entry" button that opens the travel entry creation form (only accessible for users with the TRAVEL_ENTRY_CREATE user right); hide the person fields, make all of them non-mandatory and directly assign the case person to the new travel entry
* Only show the resulting case infobox or the creation button when the disease is not null

**Comment by syntakker** [comment]
@MateStrysewske isn't it the user right `TRAVEL_ENTRY_VIEW` rather than `POINT_OF_ENTRY_VIEW` for which the travel entry list in case epi data should be shown?

**Comment by MateStrysewske** [comment]
@syntakker Yes, totally right

**Comment by syntakker** [comment]
@MateStrysewske Another question: Is the criterion to show a travel entry in case epi data that the case is their resulting case or that the travel entry's person is the same as the case's person?

**Comment by bernardsilenou** [comment]
@MateStrysewske @JaquM 
- I have not read all the issues related to ravel entities, but this specification is DE only.
Is  ravel entities DE only or just this link to cases? 
- Another point is the validation when crating/ linking the case, maybe it was already explained in another issue but I did not see it here, something like  onset date of case >= date of travel return  and  onset date of case <= date of travel return  + 30 
- Travel entities does not have a disease, thus multiple linkage should be possible, right? but not multiple linkage of the same disease.

**Comment by bernardsilenou** [comment]
> @MateStrysewske Another question: Is the criterion to show a travel entry in case epi data that the case is their resulting case or that the travel entry's person is the same as the case's person?
> I would assume it's the same person?

@syntakker  Sorry to reply in place of Maté,
- It should not be ` that the travel entry's person is the same as the case's person`
- It should be ` that the travel entry's person is the same as the case's person and the case is a resulting case of the travel entity`, similar to converting contacts to case.
- A person can be linked to one travel entity and 2 cases at the same time, but only one of the cases is linked to the travel entity. 
- In the case entity table in the db, we may need a new entry called returningTravellerId and set to null by detault, and replace with returning traveller id when linked to the case.

**Comment by syntakker** [comment]
@bernardsilenou so the workflow then might look like this:
1. one or several travel entries are registered for a person
2. the person becomes a case (e.g., by creating a case for one of the travel entries)
3. the case view shows the travel entry that has been converted to the case, but not the others?

I wonder if it would not make sense to show other travel entries as well, possibly restricted by a time period.
Otherwise additional travel entries might go unnoticed for people who took several flights in the time of there infection, in case not all of those travel entry are manually linked to this case (hindered a bit by the tedious workflow: case -> go to person to find all travel entries -> edit each of those individually to establish the link to the case)

**Comment by MateStrysewske** [comment]
@bernardsilenou This is DE only because it's completely customised towards DEA for now, yes. No validation is possible in the first version because the date of returning travel is part of the JSON information that we collect, it's not a dedicated field. Travel entries do have a disease because proper follow-up is only possible if there's a distinct disease set.

Concerning the questions by @syntakker, I agree that the travel entries list on a case should only show the travel entries where the case has been set as the resulting case, not all travel entries that are associated with the case person.

**Comment by bernardsilenou** [comment]
@MateStrysewske Thanks for the feedback. I did not know that it is completely customised towards DEA. I discuss further with @JaquM

**Comment by bernardsilenou** [comment]
@syntakker  The points listed in  https://github.com/hzi-braunschweig/SORMAS-Project/issues/6026#issuecomment-882273538  looks good.
Similar to contact view, when a contact is linked to a case, we only show the contact of the person linked to the case, not all the contacts of the person. It is fine that we only show the travel entity linked to the case. If users need to see all entities of the person, then they need to go through the person view.

I think your suggestion is perfect for the travel entity directory, we can show all travel entities but not on case view.

I am not 100% sure if I understood you. Just commenting from my interpretation

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.62.0-SNAPSHOT tested on test-de1.sormas.netzlink.com environment
