### ISSUE TITLE
Internal token field is not searchable on case and person directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6027]
### Bug Description

The internal token field introduced in https://github.com/hzi-braunschweig/SORMAS-Project/issues/5224 is not searchable on the case and person directories.
### Steps to Reproduce

1. Open or create a case and enter an internal token for case and person, save.
2. Go to the respective directory and search the respective internal tokens, check the search results.

### Expected Behavior

all internal tokens should be searchable on the respective directories.
### Screenshots

<img width="703" alt="internalTokenSearch3" src="https://user-images.githubusercontent.com/70317594/124095475-00302880-da5a-11eb-9037-5c8a0323a512.PNG">
<img width="641" alt="internalTokenSearch4" src="https://user-images.githubusercontent.com/70317594/124095477-00c8bf00-da5a-11eb-90bb-a8cf11bbc9b7.PNG">
<img width="452" alt="personInternalTokenSearch" src="https://user-images.githubusercontent.com/70317594/124095509-09b99080-da5a-11eb-8a85-4364a5462465.PNG">
<img width="494" alt="personInternalTokenSearch2" src="https://user-images.githubusercontent.com/70317594/124095484-02928280-da5a-11eb-8ea8-1c02cc45a819.PNG">

### System Details

* Device:
* SORMAS version: 1.61.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Developer Specifications
- Add search for internal token to all freetext search fields

**Comment by DavidBaldsiefen** [comment]
Is this really a bug or a feature? (Does not really make a big difference from an implementation-perspective). It feels like this was not defined as intended behaviour

**Comment by kwa20** [comment]
@DavidBaldsiefen This is a bug based on the issue description

> This field should be searchable on all respective directories (by including it into the already existing main search fields)

**Comment by Marko-ilmkreis** [comment]
@kwa20 @DavidBaldsiefen we are using very often the text search for the external token (which is currently used for internal references. It its easy to implement maybe is can ne moved for the 1.61.1?

**Comment by DavidBaldsiefen** [comment]
@Marko-ilmkreis usually we only implement urgent changes in hotfixes.

I am a bit confused by your request though. Do you want the text search field to search for internal _and_ external tokens?

**Comment by Marko-ilmkreis** [comment]
Sorry, I updated the comment above to make it more clear.
