### ISSUE TITLE
Person directory includes persons that have no entity associations

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#6035]
### Bug Description

The person directory currently includes persons that are not associated to any case, contact or event participant. This should not be the case - persons without any entity association should be excluded here.

### Steps to Reproduce

1. Create a person without any entity association, e.g. via ReST
2. Check whether the person appears in the person directory (maybe as a national user to make sure that other filters aren't preventing this)

### Expected Behavior

Persons without entity associations should not appear in the person directory - a possible fix is to change the PersonService.createUserFilter method to NOT include persons where case == null, contact == null and event participant == null (currently the logic explicitely includes those persons).

### System Details

* Device:
* SORMAS version: 1.61.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

This was found in #5999 and comes currently not to affect because auf checking for deleted flags. But when immunizations or travel entries are in the system, they will leak into the person directory (and maybe without any jurisdiction check).

**Comment by DavidBaldsiefen** [comment]
> a possible fix is to change the PersonService.createUserFilter method to NOT include persons where case == null, contact == null and event participant == null 

It is not clear if these changes might have unforseen consequences in other parts of the code, as it will affect _every_ instance where `PersonFacade.getIndexList()` is called. An alternative solution might be to add a custom PersonCriteria-Parameter called `excludePersonsWithoutAttachedEntitities`, which can then be manually set to `true` in `PersonGrid.setLazyDataProvider()` to achieve the same result

Thoughts @MateStrysewske ?

**Comment by StefanKock** [comment]
The persons feature is intended to show persons of cases, contacts and event participants, nothing else. That other person objects might show up has to be avoided, so no need for a configuration.

**Comment by DavidBaldsiefen** [comment]
Wouldn't that mean that every person without a case/contact/ep would then effectively be lost and should be deleted to prevent dead database entries?

**Comment by DavidBaldsiefen** [comment]
Alright, I fixed the tests.

**Comment by StefanKock** [comment]
Related unit tests are failing on hotfix branch:
- PersonFacadeEjbTest.testGetIndexListByPresentCondition
- PersonFacadeEjbTest.testGetIndexListPersonNotConsideredIfAssociatedEntityDeleted
