### ISSUE TITLE
Mark cases as sent to the reporting tool after the initial import

### ISSUE THREAD

**Issue by Alexandru-Pirvu** [hzi-braunschweig/SORMAS-Project#6038]
### Feature Description
Complementary task for [Import] Mark cases as sent to the reporting tool after the initial import #191
Initial import upon rollout of SurvNet interface should mark imported entities as shared with SurvNet

### Problem Description
When data is initially imported into Sormas, cases are not marked as sent to the reporting tool which leads to them wrongfully appearing on the directory when filtering with reporting tool associated filters.

### Proposed Change
Enhance the **/push** endpoint for _cases_ and _events_ to be able to also create the necessary surveillance info upon SurvNet import

**Comment by HolgerReiseVSys** [comment]
@Alexandru-Pirvu Wouldn't it make more sense to have e.g. a separate `ExternalSurveillanceToolGatewayResource` and let the converter manage those?
To me this is a corner case which we should not interweave with the saving of cases etc.
Also, this would facilitate managing permissions.

**Comment by Alexandru-Pirvu** [comment]
> @Alexandru-Pirvu Wouldn't it make more sense to have e.g. a separate `ExternalSurveillanceToolGatewayResource` and let the converter manage those?
> To me this is a corner case which we should not interweave with the saving of cases etc.
> Also, this would facilitate managing permissions.

That is also an option I considered, but chose to use the classic _push_ API with an added parameter because it would preserve the generic implementation on the converter part (e.g. when constructing URLs). Considering this, do you still think it would be a good idea to have a separate _resource_ for external surveillance tool import?

**Comment by HolgerReiseVSys** [comment]
I don't think architectual considerations for SORMAS should be influenced by implementation details in the converter to this extent.
I have not yet looked at it, but I suppose #182 is in a similar position.

**Comment by HolgerReiseVSys** [comment]
@Alexandru-Pirvu I have performed an initial import. The share infos have the change date 500 to 6000 ms after that of the corresponding case. This means that the `onlyEntitiesChangedSinceLastSharedWithExternalSurvTool` filter still includes the imported cases.
For events the changedate offset seems OK (millis before the event).

**Comment by HolgerReiseVSys** [comment]
I have consulted the history, looks like the completeness calculation is the culprit.
```sql
with c as (
	select 'history' t, id, changedate, completeness from cases_history
	union select 'cases', id, changedate, completeness from cases
	union select 'shareinfo', caze_id, changedate, null from externalshareinfo)
select *  from c order by c.id, c.changedate;
```
| t | id | changedate | completeness  | 
| -- | -- | -- | -- | 
| history | 354 | 2021-07-06 15:39:47.329 | 0.3 | 
| shareinfo | 354 | 2021-07-06 15:39:47.611 |  | 
| cases | 354 | 2021-07-06 15:39:48.592 | 0.45 | 

`onCaseChanged` is triggered again when samples are added.
But also when a companion case is added (due to person change) and when later adding contacts.

Maybe the change infos should be added in bulk after the import of cases and events.

**Comment by HolgerReiseVSys** [comment]
@Alexandru-Pirvu Looks like the branch is based on SORMAS 1.60, but it needs to be a hotfix for 1.61.
Also, in that version the completeness calculation is done in an asynchronous batch job.
This may lead to concurrency issues, so we may have to take control of that during import.

**Comment by HolgerReiseVSys** [comment]
@Alexandru-Pirvu Seems like there will be a ticket for the hotfix soon that calculating the completeness will not modify the changedate any more

**Comment by kwa20** [comment]
@Alexandru-Pirvu @HolgerReiseVSys Do you know if already imported data is also touched? I guess that might be tricky. If not, would there be a way to retrospectively mark cases and events as shared with SurvNet which have already been imported?

**Comment by HolgerReiseVSys** [comment]
> @Alexandru-Pirvu @HolgerReiseVSys Do you know if already imported data is also touched? I guess that might be tricky. If not, 
would there be a way to retrospectively mark cases and events as shared with SurvNet which have already been imported?
@kwa Not as part of this ticket. Probably an update script would be needed that adds share infos to the imported cases.
The end of the initial import would maybe have to be specified, so the changedate of the share infos can be set accordingly.
