### ISSUE TITLE
[Angular][Bug][DevOps] Translations: Due to having duplicate key, some of the get overwritten [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6039]
### Bug Description

- Translations: Due to having duplicate key, some of the get overwritten

### Steps to Reproduce

1. @sandorbanvitagroup  please provide an example of a text where this happens

### Expected Behavior

- Current custom translations will remain on a single level (on the main level)
- Each Sormas project translation file will have it's own section in the translation JSON

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by horia-ardelean-vg** [comment]
**Work done:**

- updated the translations script to include translations on a multi level system where the first level is composed with the file names (i.e. file named `captions.en.properties` will result in key `captions`
- custom angular translation are in the same format on the first level of the resulting translation files
- pull request is [here](https://github.com/hzi-braunschweig/SORMAS-Angular/pull/164)

**Comment by horia-ardelean-vg** [comment]
**Work done**

- fixed an issue where the language name was getting replaced in the translation category resulting in the conversion from `enum` to `um`
- pull request is [here](https://github.com/hzi-braunschweig/SORMAS-Angular/pull/167/files)

Moved back to code review for the new pull request.
