### ISSUE TITLE
Get missing district shapes for nigeria

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#604]
- [x] list missing shapes

**Comment by MartinWahnschaffeSymeda** [comment]
> No shape for districts found: Ado Ekiti, Ado Odo/Ota, Ahoada East, Aiyedaade, Ajeromi/Ifelodun, Akoko North East, Anambra East, Ankpa, Apapa, Asari-Toru, Atakunmosa East, Auyo, Awka North, Awka South, Babura, Bassa, Birnin Kudu, Birniwa, Burutu, Damboa, Danko/Wasagu, Dutse, Egbado South, Ekiti East, Ekiti West, Fika, Gabasawa, Garki, Gaya, Gudu, Gwer East, Ibadan North West, Ibadan South West, Ibarapa East, Ibarapa North, Ido-Osi, Ifelodun, Ife North, Ife South, Ikara, Ilaje, Ilesha East, Irepodun, Irepodun, Itu, Jere, Jibia, Kajuru, Kankia, Kibiya, Kiri Kasamma, Lagos Island, Lagos Mainland, Lapai, Madobi, Magama, Maiyama, Makarfi, Maru, Michika, Mikang, Minjibir, Nassarawa, Ndokwa West, Njaba, Nkwerre, Obi, Obi Nwga, Obowo, Obudu, Odigbo, Ohimini, Okrika, Oluyole, Ondo East, Ondo West, Orolu, Ovia North-East, Ovia South-West, Owan East, Owerri North, Rimi, Silame, Sokoto South, Song, Surulere, Takai, Taura, Toto, Tudun Wada, Udung Uko, Ukwa West, Ushongo, Wudil, Yagba East, Zurmi, Zuru

@hzi-braunschweig 
We need to find a way to add shapes for these districts or a way to display that some districts aren't visible.
