### ISSUE TITLE
[Angular] Bulk Edit task form (follow the "edit case" example) [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6042]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yY4GJY
- As we are dealing with bulk edit, all checkboxes (are closed)
- No data is pre-filled as we are dealing with a bulk edit form

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - there are some inconsistencies with the UI that @adriandumavitagroup  will fix a new task
