### ISSUE TITLE
[Angular] Edit task  [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6043]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/AxLmejr
- Almost Identical with the "Add new task" (as such we can make use of the already developed "Add new task"). The actual development will take into account the investigation done under: 

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX done- everything looks good
