### ISSUE TITLE
[Angular][SPIKE] Investigate the differences and similarities between create / edit entities across the board [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6044]
### Problem Description

- We need to understand how similar are the forms for add / edit entities across the board

### Proposed Solution

- Based on this, we will decide the best technical approach (duplicate the forms, use only one form with a param that defines if it is "edit" or "create")
- Please document on this task all of the findings (if too many, please create a google doc and export it as a pdf on this task)

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by danielrus** [comment]
[contacts.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6791933/contacts.pdf)
[tasks.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6791934/tasks.pdf)
[events.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6791935/events.pdf)
[users.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6791936/users.pdf)
[samples.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6791937/samples.pdf)
[persons.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6791938/persons.pdf)

**Comment by danielrus** [comment]
I've attached pdfs outlining the differences between create / edit forms across the platform

**Comment by danielrus** [comment]
We discussed the differences internally, with the angular team, and the conclusion was it is best to keep add and edit forms separate - there are plenty of differences in some cases, both of structure and layout to justify separate components for add and edit; also, an effort to optimize this by unifying add and edit forms would required another layer of complexity over the dynamic form (which is already complex enough).
