### ISSUE TITLE
[Angular] Edit Events (follow the "edit case" example) [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6045]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/7y51mQZ
- As we are dealing with bulk edit all checkboxes (and content) is hidden / closed

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - there are some inconsistencies with the UI that @adriandumavitagroup  will fix in a new task
