### ISSUE TITLE
[Angular] Users page, LIST [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6047]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/09vbLEG
- Even if we don't have the backend end point available we can hard-code some data
- This task focuses only on the table view (the right side)
- Create the "Users" module, service, serialiser

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good
