### ISSUE TITLE
[Angular] Users page, FILTERS [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6049]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/09vbLEG
- This task will focus only on the left side of the page (the filter)

### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
