### ISSUE TITLE
Contact mobile app not working well. fields disappearing

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#605]
Contact officer app not working well
![image](https://user-images.githubusercontent.com/19344651/40122802-ec71529c-5924-11e8-9a94-d3497a76694d.png)

**Comment by MartinWahnschaffeSymeda** [comment]
More information please: Sormas version? Device type? Android version? When does this happen?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig We need more information on this, please!

**Comment by MartinWahnschaffeSymeda** [comment]
From an old version - no longer valid.
