### ISSUE TITLE
[Angular] Create User (follow the "add case" example) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6050]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/41A5EEB1-2DA8-489C-839E-F8D777662B36
- We need to include the geolocalisation icons as well (without any action)
 
### Possible Alternatives

N/A

### Additional Information

N/A

**Comment by cristinacoza** [comment]
UI/Ux review Done - everything looks good!
