### ISSUE TITLE
Add information to the entity cards on the person form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6054]
### Feature Description

Entity cards (cases, contacts, events) on the person form

<img width="599" alt="personForm" src="https://user-images.githubusercontent.com/70317594/124384817-5065ef80-dcd3-11eb-8b4e-e086312bc12e.PNG">

### Problem Description

Some relevant information are not displayed when linked entities are displayed on the general person form.
### Proposed Change

For **cases**:
- Add the symptom onset date if given

For **contacts**:
- Add the date of report
- Add the last contact date if given

For **events**:
- Add the date of event if given

**Comment by kwa20** [comment]
@ChristopherRiedel @Johannes-Schmidt-GA-RT @Marko-ilmkreis @ThomasVitus For your information. Please feel free to provide feedback or mention more contributors who I forgot to include.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(d20e859).

Checked information displayed and updated on the entity cards from the person page for persons and entities shared via S2S on test-de2 and test-de3 - 1.77.0-SNAPSHOT(d20e859).
