### ISSUE TITLE
[Angular] Person detailed view (main section) [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6056]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Myx7Yga
- We need to also include the "Add new address" and "Add new contact" buttons without any actual action behind it.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by laurentiustanvitagroup** [comment]
As confirmed by @marius2301 , this is already developed and it should work.

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good
