### ISSUE TITLE
Remove Event and Sample menus from Contact officer instance

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#606]
@MartinWahnschaffeSymeda 

![image](https://user-images.githubusercontent.com/19344651/40125799-1418aafa-592c-11e8-8fc4-9d7c1a662771.png)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Remove Event and Sample menus from Contact officer instance (maybe necessary to change the user rights)
- [ ] hide contacts for diseases without follow-up
- [ ] #660

**Comment by MartinWahnschaffeSymeda** [comment]
For the app this means: Only show entries in the list where the user is allowed to edit the entry type.
Reason: The contact officer should probably still be able to view samples from within a case. Or to view an event when linked from another entity.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig What about case officers and informants?

**Comment by MartinWahnschaffeSymeda** [comment]
During review we decided that contact officers should still see events.
Removing the samples from the menu would require another seperate user right, so we decided that it's not so crucial to remove it from the app menu and just leave it the way it is.
