### ISSUE TITLE
Cases > Case > `Don't share case with external reporting tool` visible on non-DE systems

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6069]
### Bug Description

Cases > Case > `Don't share case with external reporting tool` visible on international servers despite SORMAS2SurvNet not being a config option.  I may cause some confusion...

### Expected Behavior

Checkbox should only show up if SORMAS2SurvNet is configured/active/an option.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/124493400-e2462900-ddb5-11eb-9929-5876b1d78f8a.png)

### System Details

* Device: PC
* SORMAS version: 1.61
* Android version/Browser: Chrome
* Server URL: https://stable-release-ch.sormas.netzlink.com/sormas-ui/#!cases/data/WALMM3-HISBPI-LDOCDR-QKSFSGLE and https://release-international.sormas.netzlink.com/
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest builld 1.62.0-snapshot on local environment
