### ISSUE TITLE
Cases > Case > Unsaved changes prompt triggered when `Case-ID ISM` filled out

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6070]
### Bug Description

The question "Confirm changes" appears if the case has at least a 4-digit number in the `Case ID ISM` field (CH systems only) - even if nothing has been changed.

### Steps to Reproduce

1. Cases > Case > Case-ID ISM filled out (at least 4 digits)
2. Leave the page (go back to the overview or switch to another tab for this case)
3. The message "Confirm changes" appears

### Expected Behavior

The question "Confirm changes" should only appear if something has changed.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/124554680-82dc2d80-de36-11eb-8c41-4fc4c98c9564.png)

### System Details

* Device: PC
* SORMAS version: 1.61
* Android version/Browser: Chrome
* Server URL: https://stable-release-ch.sormas.netzlink.com/sormas-ui/#!cases/data/WALMM3-HISBPI-LDOCDR-QKSFSGLE
* User Role: admin, national user

### Additional Information

The message does not appear if only a 1-, 2- or 3-digit number is entered. From a 4-digit number, 1000 separators also appear (' or . depending on the browser/system)

![image](https://user-images.githubusercontent.com/65529128/124554171-f598d900-de35-11eb-8e00-1dc81e3dca38.png)
![image](https://user-images.githubusercontent.com/65529128/124554195-fdf11400-de35-11eb-98b7-819f6b8d7222.png)
![image](https://user-images.githubusercontent.com/65529128/124554331-237e1d80-de36-11eb-9f58-ab55f3af9ab4.png)

Possibly related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/5648 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/3014

**Comment by DavidBaldsiefen** [comment]
I could not reproduce this on my local instance (1.62.0-SNAPSHOT), as well as on https://stable-release-ch.sormas.netzlink.com (1.61.0). Do you have any more info on how to reproduce this?

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen In order to reproduce this, you need to set your operating system to English (i.e. change the language to English and also set the formats used to English formats so that it uses . as decimal separator) while using a browser that is set to German (or another language that uses , as decimal separator)

**Comment by MateStrysewske** [comment]
The problem is basically the same problem that we also have with the GPS fields; the solution might be to turn the field in to an AccessibleTextField (see CommitDiscardWrapperComponent.addDirtyHandler which takes care of handling this logic)
