### ISSUE TITLE
Add missing fields to history tables

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#6078]
### Bug Description

There are (mostly recently added) fields in the database that have not been added to the respective history tables. For cases, these include:

- classificationdate
- classificationuser_id
- creationversion
- denguefevertype
- diseasevariant
- responsiblecommunity_id
- responsibledistrict_id
- responsibleregion_id
- sormastosormasorigininfo_id
- and some only in cases_history:
- covidtestreason
- covidtestreasondetails
- diseasevariant_id
- reportingtype

Other tables need to be investigated.

### Expected Behavior

History tables should include these fields; extend the history tables accordingly

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by DavidBaldsiefen** [comment]
Additional missing fields found:

- contact
  - vaccinationinfo_id
  - sormastosormasorigininfo_id

- eventparticipant
  - region_id
  - district_id
  - vaccinationinfo_id
  - sormastosormasorigininfo_id

- labmessage
  - status

- samples
  - sormastosormasorigininfo_id

- events, person, symptoms
  - a whole bunch, TBD
