### ISSUE TITLE
Missing dependencies for app build

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#6081]
### Bug Description
Nightly app build fails:
```
* What went wrong:
Could not determine the dependencies of task ':app:transformClassesAndResourcesWithR8ForRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not find io.crowdcode.sormas.lbds:lbds-http-android:1.2.7.
     Required by:
         project :app
   > Could not find io.crowdcode.sormas.lbds:lbds-android-messaging:1.4.4.
     Required by:
         project :app
```
Reason: `io.crowdcode.sormas.lbds:lbds-http-android:1.2.7` and `io.crowdcode.sormas.lbds:lbds-android-messaging:1.4.4` are not available from Maven Central.

### Expected Behavior
All external dependencies should be available from Maven Central.
For the dependencies in questions the available versions are:
- `io.crowdcode.sormas.lbds:lbds-http-android:1.2.9`
- `io.crowdcode.sormas.lbds:lbds-android-messaging:1.4.6`, this version is currently being deployed to Maven Central. The deployment process may take some hours to complete. After discussion with @MartinWahnschaffe, we will nevertheless choose this version (and not push an intermediate solution for the next hours).

### System Details

* Device:
* SORMAS version: 1.62.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by syntakker** [comment]
`io.crowdcode.sormas.lbds:lbds-android-messaging:1.4.6` is available now (tested in local build).

**Comment by StefanKock** [comment]
This is not to be considered as a bug because it is unfinished #3522 within the sprint.
