### ISSUE TITLE
Change the german translation for 'Only cases marked as 'Don't share with reporting tool''

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6084]
### Bug Description

Unfortunately, the filter translation for 'Only cases marked as 'Don't share with reporting tool'' was not re-translated in time to display the corrected german translation. To minimize confusion, it would be great if this could be fixed manually.
### Steps to Reproduce

1. Set the user language to german
2. check the filters on the case directory (make sure that the reporting tool interface is configured)

### Expected Behavior

Translation should be the following
<img width="325" alt="filterReportingToolTranslation2" src="https://user-images.githubusercontent.com/70317594/124746294-feb2a480-df20-11eb-9ce7-55323b2be02c.PNG">

### Screenshots

<img width="352" alt="filterReportingToolTranslation" src="https://user-images.githubusercontent.com/70317594/124746347-096d3980-df21-11eb-9642-ed23a82a5779.PNG">

### System Details

* Device:
* SORMAS version: 1.61.0
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role:

**Comment by kwa20** [comment]
@StefanKock As discussed via email :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on latest version of  SORMASVersion: 1.62.0-SNAPSHOT on test-de1 environment
