### ISSUE TITLE
Duplicate detection during region import does not work

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6089]
### Bug Description

#1621 added duplicate detection for infrastructure data.
Importing infrastructure results in duplicate data in the system.
### Steps to Reproduce

1. export region data on a server
2. re-import the exported regions but do not choose `override existing entries with imported data`.  This create duplicate entries even if the name and epid code are the same. 
3. Import a region with the same name as a region in the system but with another country. You get the error message `The database already contains a region with this name.`

### Expected Behavior

- If `override existing entries with imported data` == t and duplicate are identified, merge the two records using the one being imported as the reference
- If `override existing entries with imported data` == f  and duplicate are identified,  do not import and add the entry to the import error report.
- Two regions with the same name but different countries, continents, etc should not be considered as duplicates. Duplicate should consider the parent/ higher administrative unit.

### Screenshots

![image](https://user-images.githubusercontent.com/12996724/124833035-d9a04f00-df7d-11eb-8887-33829a4d3833.png)

![image](https://user-images.githubusercontent.com/12996724/124833104-f472c380-df7d-11eb-8778-bbdfbec5e207.png)

### System Details

* Device:
* SORMAS version: 1.61
* Android version/Browser:
* Server URL:  https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: admin

**Comment by vidi42** [comment]
As @MateStrysewske pointed out here https://github.com/hzi-braunschweig/SORMAS-Project/pull/6161#pullrequestreview-711648600, this change is much more complex and affects how multiple flows are working.
This doesn't look like a bug anymore, but more as a change to the initial countries ticket which didn't specify how region name uniqueness should be treated once countries were introduced.

I opened a CR for this https://github.com/hzi-braunschweig/SORMAS-Project/issues/6190 and will close this ticket as it will be covered by that one.
