### ISSUE TITLE
Infrastructure data import should accept comma or semicolon separators

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6090]
### Steps to Reproduce

1. Download import template for region or region export. This downloaded file comes as ".csv" with ";" separator
2. When this template if modified and saved as ".csv" with "," separator, import results in error and there in.

### Expected Behavior

- Import should accept UTF-8 with both "," and ";" no matter the language of the user or server

### Screenshots

Meggage after importing file with "," separator
![image](https://user-images.githubusercontent.com/12996724/124836320-1589e300-df83-11eb-9f96-814cb3dbec47.png)
 
### System Details

* Device:
* SORMAS version: 1.61
* Android version/Browser:
* Server URL:  https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: admin

**Comment by bernardsilenou** [comment]
@VitaliHZI @kwa20  
I think this is the reason why the import did not work today. Please can you test and confirm.

**Comment by MateStrysewske** [comment]
@bernardsilenou This is not a bug. We need to specifically know the separator (just like Excel for example also needs to specifically know it) so that we can decide when an entry ends and the next one starts. The expected separator can be configured in the properties file. Altering this functionality would basically be a new feature - please discuss it internally and open a feature issue if it's still something we need.

**Comment by bernardsilenou** [comment]
@MateStrysewske  @kwa20 
Thanks for the response. I think what I was thinking is not what was implemented. My question is:
The import guide explains that if "," or ";" is not a delimiter, then it should be in " "
I though the import module had a method to scan and automatically determine the delimiter and then use it. If this is not the case, then we can add a dropdown at the import dialog box for the user to specify the delimiter.
Having it in the expected configuration in the properties file only is not a good idea since the person importing the data has no idea or access to the properties file.

I would go for a solution to add a `delimiter` with enums: ",", ";" and set it to the default value as that in the properties file. Then use the one specified at the front end for importing.
If you also agree then I can add an issue for it. This would apply to import for all entities.

**Comment by MateStrysewske** [comment]
Having a dropdown to select the delimiter sounds like a good idea, yes!
