### ISSUE TITLE
Allow country grid to be filtered and sorted by translated name

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6091]
### Bug Description

Infrastructure data edit form for country does not get updated on directory after editing.
### Steps to Reproduce

1. Edit the name of a country and save. One name is maintain on the directory and new name on the form
2. When edited the UNO code, it got updated on directory (this is OK)
3. Filter by name of country does not suggest all countries having the specified character, eg "cot" in the the filter does not suggest "Cote_dIvoire" as a country, but "c" does.

### Expected Behavior

- Directory should be reloaded after changing the name
- Check whether there's an easy fix for the filtering problem - likely not
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/124839445-1a519580-df89-11eb-90db-53ff064ba2d9.png)

### System Details

* Device:
* SORMAS version: 1.61
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: admin

**Comment by MateStrysewske** [comment]
Please note that

* the filtering might be based on the default country name, i.e. the English one - since we're doing filtering and sorting directly in the database, there is currently no way to change that
* changing parent infrastructure data is not possible right now because it has serious implications and requires a lot of work

I've changed the issue description accordingly.

**Comment by DavidBaldsiefen** [comment]
1. The Display name is currently based on the ISO-Code - as far as I can see in _every_ part of the code. What could be done for the infrastructure directory, is compare the manual name with the iso-code based default english name, and when it's different display the manualname instead. The "problem" will still occur in other parts of the software though
2. Considering the almost always limited amount of countries, it would be possible to always eager-load _all_ the data, and then filtering/sorting based on that data. This code could also be reused in other parts of the project, however it will almost certainly lead to performance problems whenever it is used on tables containing several thousand entries

Thoughts @MateStrysewske ?

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen I agree with both suggestions, limited to the country directory of course

**Comment by AndyBakcsy-she** [comment]
Reopening issue as there seems to be a small problem.
Searching for ISO Code and Country Name only works when using lower case letters. 
Searching for Andorra or AND will not return results. Doing the same for andorra or and will populate the Countries Grid

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.62.0-snapshot on local environment
