### ISSUE TITLE
 Access to the event groups directory with a surveillance supervisor & contact supervisor profile

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#6093]
### Bug Description

Version 1.59 includes the functionality to group events. This feature is not open to surveillance supervisor & contact supervisor.
Users with this profile cannot access the group directory, nor attach an event from its file to an existing group. An error message appears.

### Steps to Reproduce

1. Profil surveillance supervisor & contact supervisor profile
2. In the event directory, click on "groups"

![image](https://user-images.githubusercontent.com/65449450/124874197-b9957d80-dfc7-11eb-81fa-d8642817d316.png)
![image](https://user-images.githubusercontent.com/65449450/124874659-43454b00-dfc8-11eb-991f-c0837be47474.png)

### Expected Behavior

Directory accessible to surveillance supervisor & contact supervisor profile

### System Details

* Device:
* SORMAS version: 1.59
* Android version/Browser: PC
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/#!users
* User Role: surveillance supervisor & contact supervisor profile

### Additional Information
@bernardsilenou @aponcon-atolcd @ftavin @emond-fuseau

**Comment by MateStrysewske** [comment]
@carolinverset I can't reproduce this problem, neither on the server you specified nor on my local development machine. Can you tell me which user exactly you used on the test server?

**Comment by carolinverset** [comment]
On the server : https://test1401.sormas-oegd.de/sormas-ui/#!users : 

Same problem with two users : 

1) user = caro 
![image](https://user-images.githubusercontent.com/65449450/124887970-f7010780-dfd5-11eb-8c37-c73126f3b39b.png)

2) user = CaroVers_Reg
![image](https://user-images.githubusercontent.com/65449450/124892211-f5d1d980-dfd9-11eb-9b86-dd14d992e0b6.png)

thank you for your help !

**Comment by MateStrysewske** [comment]
@carolinverset I've just requested the server logs and will look into it

**Comment by aponcon-atolcd** [comment]
Hi
The issue is reproducible if the current user is limited to a specific disease.
A pull request will be available asap.

@MateStrysewske

**Comment by MateStrysewske** [comment]
@aponcon-atolcd Hey! Thanks! There's no pull request needed because we will integrate it into the upcoming minor version that's gonna be released today, so I'm about to fix it right now :)
