### ISSUE TITLE
Add RAPID_TEST as a criteria for case classification calculation

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6096]
### Feature Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/4770 Case classification for COVID
### Problem Description

The RAPID_TEST turned out to be a requirement for the case classification calculation of confirmed COVID cases and is not yet accounted for.
### Proposed Change

- Add RAPID_TEST as a criteria for the calculation of the case classifications for positive test results of CORONAVIRUS
    - CONFIRMED
    - CONFIRMED_NO_SYMPTOMS
    - CONFIRMED_UNKNOWN_SYMPTOMS
- Add Rapid test as criteria in the info box

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas on local environment 1.62.0-snapshot
