### ISSUE TITLE
Add zero or weekly reporting for surveillance officer [5]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#610]
Need for surveillance officer app and contact officer app to be able to do zero report or weekly report. 

This is obtainable in the IDSR for their level.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig This makes sense, especially when no informants are participating. We need to discuss how exactly this should work. Especially how it interacts with the reports done by informants (there may be a few informants)

**Comment by MartinWahnschaffeSymeda** [comment]
The officer currently only sees the weekly reports done by related informants. It's necessary he/she also confirms a weekly report on district level.

Data to be confirmed:

  * number of cases reported
  * number of pending investigations
  * number of unclassified cases

The officer should be allowed to enter missing cases (or to make sure the informants have entered all missing cases), to do case investigations and to classifiy cases. #890 is crucial for this purpose. Weekly reports should no longer count cases reported in the next week.

Note: While informants confirm the weekly report each Monday (at best) it's likely that officers need some additional time - e.g. until Wednesday. We need to define at what point(s) to notify the user.

- [ ] create a mockup for this.
- [ ] make sure app users get notified to do the weekly report

// based on phone call with Daniel 21/11/18

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Two questions:

1. How should the number of cases be counted for a surveillance officer?
  For the informant it is simply the total number of cases reported by the exact user for the disease.
  For officers it could be
  A) The number of cases reported by him and all informants associated to him
  B) The number of cases reported in the district. 
  B would not work with multiple officers in the same district, so I expect we should implement A?
2. Contact officers don't to weekly reports on cases, right? At least as long as they aren't surveillance officers at the same time.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
Yes I agree with A. for contact officers, its only task related to contact visits that are important so its not applicable to them. However, if an officer has both functions as a contact and surveillance officer, then yes he will be able to report weekly.

**Comment by MartinWahnschaffeSymeda** [comment]
Discussed this today:

- [ ] users should get a daily notification when the report has not been submitted yet
- [ ] users should be allowed to create cases via the case directory even when the report has not been submitted
- [ ] it should be possible to retrospectively submit reports
- [ ] date of report submission should be shown to officers and supervisors
- [ ] number of pending investigations and unclassified cases should not be part of the report, because they can't be clearly associated to the week of report. Instead they could be shown on a dashboard.

**Comment by MartinWahnschaffeSymeda** [comment]
Remarks from review

- [ ] App: Replace "cases - 0" with "Number of cases by disease" caption
- [ ] Re-add the "add missing case" button. Date of report should be left empty so the user has to enter it. Also add a description
