### ISSUE TITLE
Add values to vaccineName to cover combination vaccinations

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6100]
### Situation Description

Thus far, we can only collect vaccine names for vaccinations where executed with one type of vaccine if multiple doses are required. However, due to recent discussion about vaccine usage and availability, many people are vaccinated with a combination of vaccines.
### Feature Description

Add two values to vaccineName to cover a frequent combination of vaccines for the current implementation
- Combination AstraZeneca/BionTech
- Combination AstraZeneca/Moderna

### Additional Information

Mapping to reporting tools handled in (https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/195)

**Comment by Candice-Louw** [comment]
Related> https://github.com/hzi-braunschweig/SORMAS-Project/issues/5759

**Comment by kwa20** [comment]
@Candice-Louw Thank you! @MateStrysewske Feel free to choose Candice's issue as leading and close this one

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas on local environment 1.62.0-snapshot
