### ISSUE TITLE
Setting diagram definition percentage default "as true" throws an error when org units are selected on the dashboard

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#6111]
### Bug Description

When you set the percentage default as true on pgadmin for a specific campaign diagram definition, the assigned chart will then show the values as percentages as the default instead of as count values. And setting totals column to the target population ([
  {"populationGroup":"AGE_0_4"}
]). The error shows when you select a region or province and you get the error that "Atleast part of the percentage part of the diagram could not be calculated, Please check diagram definitions for errors".
![B2CD44B2-7006-4041-B276-DBC2B93FD376](https://user-images.githubusercontent.com/60390281/125308178-ae5f8c00-e2fe-11eb-9d89-32e698a4d489.jpeg)

### Steps to Reproduce

1. Go to dashboard, click on tab ADMIN-DAY 1, select any region to filter chart. 
2. An error popup appears with the following error message "Atleast part of the percentage part of the diagram could not be calculated, Please check diagram definitions for errors".
3. If you use count value as a default, the error does not appear when you filter by region or toggle from count to percentage on the chart.
### Expected Behavior

No errors should appear
### Screenshots

![C25FF3C8-4907-4862-A06E-113ECAA2B80D](https://user-images.githubusercontent.com/60390281/125309144-81f83f80-e2ff-11eb-9be8-ca02d5192817.jpeg)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

@MartinWahnschaffe

**Comment by tomabadaniel** [comment]
#Diagram definition
[

  {
    "fieldId": "NumberofchildrenyearsDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Number of Children"
    
  },
  {
    "fieldId": "NumberofhousesvisitedDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Houses Visited"
  },
  {
    "fieldId": "childrenyearsresidentinthehouseDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Resident in Houses"
  },
 {
    "fieldId": "guestinthehouseDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Guests in Houses"
  },
  {
    "fieldId": "vaccinatedinhousesDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Vaccinated in Houses"
  },
  {
    "fieldId": "vaccinatedoutsideofhousesDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Vaccinated outside of Houses"
  },

    {
    "fieldId": "NomadVaccinatedDay1",
    "formId": "DailyCompSheet",
    "stack": "Day 1",
    "caption": "Nomad Children Vaccinated"
  }
]

#Total series column

 [
  {"populationGroup":"AGE_0_4"}
]


#Form definition for the diagrm
[
  {
    "type": "label",
    "id": "DailyCompSheet",
    "caption": "<h2>Day 1- Daily Compilation Sheet</h2>"
  },
  

{
    "type": "section",
    "id": "Day1"
  },
  {
    "type": "text",
    "id": "ClusterName",
    "caption": "Cluster Name:"
  },
{
    "type": "number",
    "id": "ClusterNumber",
    "caption": "Cluster Number"
  },
 {
    "type": "label",
    "id": "VaccineRecordDay1",
    "caption": "<h3>Vaccine Record</h3>"
  },

  {
    "type": "number",
    "id": "NoofFullvialsreceivedDay1",
    "caption": "Full vials received"
  },
  {
    "type": "number",
    "id": "NoofFullvialsreturnedDay1",
    "caption": "Full vials returned",
    "styles": [
      "row"
    ]
  },
  {
    "type": "number",
    "id": "NoofFullvialsusedDay1",
    "caption": "Full vials used (received - returned)",
"expression": "NoofFullvialsreceivedDay1 - NoofFullvialsreturnedDay1",
    "styles": [
      "row",
      "col-3"
    ]
  },
  

  {
    "type": "section",
    "id": "VaccinationInformationSection1"
  },
  {
    "type": "label",
    "id": "targetchildrenandvaccinatedDay1",
    "caption": "<h3>Target Children and Vaccinated</h3>",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofchildrenyearsDay1",
    "caption": "Children 0-5 years Vaccinated by Transit Teams (campaign based)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofhousesvisitedDay1",
    "caption": "Houses visited",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   {
    "type": "number",
    "id": "childrenyearsresidentinthehouseDay1",
    "caption": "Under 5 years Children  Resident in the House",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "guestinthehouseDay1",
    "caption": "Under 5 year Children guests in the House",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
     {
    "type": "number",
    "id": "vaccinatedinhousesDay1",
    "caption": "Under 5 years Children Vaccinated in Houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "vaccinatedoutsideofhousesDay1",
    "caption": "Under 5 years Children Vaccinated Outside of Houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
       {
    "type": "number",
    "id": "NomadVaccinatedDay1",
    "caption": "Nomad Children 0-5 yrs vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "section",
    "id": "NonVaccinationSection1"
  },
  {
    "type": "label",
    "id": "NonVaccinatedchildrenDay1Label",
    "caption": "<h3>Children Non-Vaccination Information</h3>"
  },
  {
    "type": "number",
    "id": "RemainingAbsentDay1During",
    "caption": "Remaining  Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "vaccinatedAbsentDay1During",
    "caption": "Found Vaccinated Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "teamAbsentDay1",
    "caption": "Vaccinated by team Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "FoundVaccinatedAbsentDay1After",
    "caption": "Found vaccinated Absent (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
        {
    "type": "number",
    "id": "VaccinatedbyteamAbsentDay1After",
    "caption": "Vaccinated by team Absent  (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
         {
    "type": "number",
    "id": "NumberRemainingAbsentDay1After",
    "caption": "Remaining  Absent (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
          {
    "type": "number",
    "id": "NumberRecordedNewbornDay1",
    "caption": "Recorded Newborn, Sleep,Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
           {
    "type": "number",
    "id": "NumberVaccinatedNewbornDay1",
    "caption": "Found vaccinated Newborn, Sleep, Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
             {
    "type": "number",
    "id": "VaccinatedByTeamNewbornDay1",
    "caption": "Vaccinated by Team Newborn, Sleep, Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
              {
    "type": "number",
    "id": "RecordedRefusalDay1",
    "caption": "Recorded  Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                {
    "type": "number",
    "id": "VaccinatedRefusalDay1",
    "caption": "Vaccinated by Team Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                  {
    "type": "number",
    "id": "RemainingRefusalDay1",
    "caption": "Remaining Refusals",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   
                  {
    "type": "number",
    "id": "TotalChildrenVaccinatedDay1",
    "caption": "Total Children vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                   {
    "type": "number",
    "id": "AFPcaseDay1",
    "caption": "AFP cases",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
  {
    "type": "label",
    "id": "DailyCompSheetDay2",
    "caption": "<h2>Day 2- Daily Compilation Sheet</h2>"
  },
  

{
    "type": "section",
    "id": "Day2"
  },
  
 {
    "type": "label",
    "id": "VaccineRecordDay2",
    "caption": "<h3>Vaccine Record</h3>"
  },

  {
    "type": "number",
    "id": "NoofFullvialsreceivedDay2",
    "caption": "Full vials received"
  },
  {
    "type": "number",
    "id": "NoofFullvialsreturnedDay2",
    "caption": "Full vials returned",
    "styles": [
      "row"
    ]
  },
  
  {
    "type": "number",
    "id": "NoofFullvialsusedDay2",
    "caption": "Full vials used (received - returned)",
"expression": "NoofFullvialsreceivedDay2 - NoofFullvialsreturnedDay2 ",
    "styles": [
      "row",
      "col-3"
    ]
  },
  

  {
    "type": "section",
    "id": "VaccinationInformationSection"
  },
  {
    "type": "label",
    "id": "targetchildrenandvaccinatedDay2",
    "caption": "<h3>Target Children and Vaccinated</h3>",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofchildrenyearsDay2",
    "caption": "Children 0-5 years Vaccinated by Transit Teams (campaign based)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofhousesvisitedDay2",
    "caption": "Houses visited",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   {
    "type": "number",
    "id": "childrenyearsresidentinthehouseDay2",
    "caption": "Number of children  0-5 years resident in the house",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "guestinthehouseDay2",
    "caption": "Number of children  0-5 years guest in the house",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
     {
    "type": "number",
    "id": "vaccinatedinhousesDay2",
    "caption": "Number of children 0-5 years vaccinated in houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "vaccinatedoutsideofhousesDay2",
    "caption": "Number of children 0-5 yrs vaccinated outside of houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
       {
    "type": "number",
    "id": "NomadVaccinatedDay2",
    "caption": "Number of nomad children 0-5 yrs vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "section",
    "id": "NonVaccinationSection"
  },
  {
    "type": "label",
    "id": "NonVaccinatedchildrenDay2Label",
    "caption": "<h3>Children Non-Vaccination Information</h3>"
  },
  {
    "type": "number",
    "id": "RemainingAbsentDay2During",
    "caption": "Remaining  Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "vaccinatedAbsentDay2During",
    "caption": "Found vaccinated Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "teamAbsentDay2",
    "caption": "Vaccinated by team Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "FoundVaccinatedAbsentDay2After",
    "caption": "Found vaccinated Absent (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
        {
    "type": "number",
    "id": "VaccinatedbyteamAbsentDay2After",
    "caption": "Vaccinated by team Absent  (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
         {
    "type": "number",
    "id": "NumberRemainingAbsentDay2After",
    "caption": "Remaining  Absent (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
          {
    "type": "number",
    "id": "NumberRecordedNewbornDay2",
    "caption": "Recorded Newborn, Sleep,Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
           {
    "type": "number",
    "id": "NumberVaccinatedNewbornDay2",
    "caption": "Found vaccinated Newborn, Sleep, Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
             {
    "type": "number",
    "id": "VaccinatedByTeamNewbornDay2",
    "caption": "Vaccinated by Team Newborn, Sleep, Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
              {
    "type": "number",
    "id": "RecordedRefusalDay2",
    "caption": "Recorded  Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                {
    "type": "number",
    "id": "VaccinatedRefusalDay2",
    "caption": "Vaccinated by Team Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                  {
    "type": "number",
    "id": "RemainingRefusalDay2",
    "caption": "Remaining Refusals",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   
                  {
    "type": "number",
    "id": "TotalChildrenVaccinatedDay2",
    "caption": "Total Children vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                   {
    "type": "number",
    "id": "AFPcaseDay2",
    "caption": "AFP cases",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "label",
    "id": "DailyCompSheetDay3",
    "caption": "<h2>Day 3- Daily Compilation Sheet</h2>"
  },
  

{
    "type": "section",
    "id": "Day3"
  },
  
 {
    "type": "label",
    "id": "VaccineRecordDay3",
    "caption": "<h3>Vaccine Record</h3>"
  },

  {
    "type": "number",
    "id": "NoofFullvialsreceivedDay3",
    "caption": "No of Full vials received"
  },
  {
    "type": "number",
    "id": "NoofFullvialsreturnedDay3",
    "caption": "No of Full vials returned",
    "styles": [
      "row"
    ]
  },
 {
    "type": "number",
    "id": "NoofFullvialsusedDay3",
    "caption": "Full vials used (received - returned)",
"expression": "NoofFullvialsreceivedDay3 - NoofFullvialsreturnedDay3 ",
    "styles": [
      "row",
      "col-3"
    ]
  },
  

  
  {
    "type": "section",
    "id": "VaccinationInformationSection3"
  },
  {
    "type": "label",
    "id": "targetchildrenandvaccinatedDay3",
    "caption": "<h3>Number of Target Children and Vaccinated</h3>",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofchildrenyearsDay3",
    "caption": "Number of children 0-5 years vaccinated by Transit Teams (campaign based)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofhousesvisitedDay3",
    "caption": "Number of houses visited",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   {
    "type": "number",
    "id": "childrenyearsresidentinthehouseDay3",
    "caption": "Number of children  0-5 years resident in the house",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "guestinthehouseDay3",
    "caption": "Number of children  0-5 years guest in the house",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
     {
    "type": "number",
    "id": "vaccinatedinhousesDay3",
    "caption": "Number of children 0-5 years vaccinated in houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "vaccinatedoutsideofhousesDay3",
    "caption": "Number of children 0-5 yrs vaccinated outside of houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
       {
    "type": "number",
    "id": "NomadVaccinatedDay3",
    "caption": "Number of nomad children 0-5 yrs vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "section",
    "id": "NonVaccinationSection3"
  },
  {
    "type": "label",
    "id": "NonVaccinatedchildrenDay3Label",
    "caption": "<h3>Children Non-Vaccination Information</h3>"
  },
  {
    "type": "number",
    "id": "RemainingAbsentDay3During",
    "caption": "Remaining  Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "vaccinatedAbsentDay3During",
    "caption": "Found vaccinated Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "teamAbsentDay3",
    "caption": "Vaccinated by team Absent (return during campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "FoundVaccinatedAbsentDay3After",
    "caption": "Found vaccinated Absent (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
        {
    "type": "number",
    "id": "VaccinatedbyteamAbsentDay3After",
    "caption": "Vaccinated by team Absent  (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
         {
    "type": "number",
    "id": "NumberRemainingAbsentDay3After",
    "caption": "Remaining  Absent (return after campaign)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
          {
    "type": "number",
    "id": "NumberRecordedNewbornDay3",
    "caption": "Recorded Newborn, Sleep,Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
           {
    "type": "number",
    "id": "NumberVaccinatedNewbornDay3",
    "caption": "Found vaccinated Newborn, Sleep, Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
             {
    "type": "number",
    "id": "VaccinatedByTeamNewbornDay3",
    "caption": "Vaccinated by Team Newborn, Sleep, Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
              {
    "type": "number",
    "id": "RecordedRefusalDay3",
    "caption": "Recorded  Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                {
    "type": "number",
    "id": "VaccinatedRefusalDay3",
    "caption": "Vaccinated by Team Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                  {
    "type": "number",
    "id": "RemainingRefusalDay3",
    "caption": "Remaining Refusals",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   
                  {
    "type": "number",
    "id": "TotalChildrenVaccinatedDay3",
    "caption": "Total Children vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                   {
    "type": "number",
    "id": "AFPcaseDay3",
    "caption": "AFP cases",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "label",
    "id": "DailyCompSheetDay4",
    "caption": "<h2>Day 4- Daily Compilation Sheet</h2>"
  },
  

{
    "type": "section",
    "id": "Day4"
  },
  
 {
    "type": "label",
    "id": "VaccineRecordDay4",
    "caption": "Vaccine Record"
  },

  {
    "type": "number",
    "id": "NoofFullvialsreceivedDay4",
    "caption": "No of Full vials received"
  },
  {
    "type": "number",
    "id": "NoofFullvialsreturnedDay4",
    "caption": "No of Full vials returned",
    "styles": [
      "row"
    ]
  },
  {
    "type": "number",
    "id": "NoofFullvialsusedDay4",
    "caption": "Full vials used (received - returned)",
"expression": "NoofFullvialsreceivedDay4 - NoofFullvialsreturnedDay4 ",
    "styles": [
      "row",
      "col-3"
    ]
  },
  

  
  {
    "type": "section",
    "id": "VaccinationInformationSection4"
  },
  {
    "type": "label",
    "id": "targetchildrenandvaccinatedDay4",
    "caption": "<h3>Number of target children and vaccinated</h3>",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofchildrenyearsDay4",
    "caption": "Number of children 0-5 years vaccinated by Transit Teams (campaign based)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "NumberofhousesvisitedDay4",
    "caption": "Number of houses visited",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   {
    "type": "number",
    "id": "childrenyearsresidentinthehouseDay4",
    "caption": "Number of children  0-5 years resident in the house",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "guestinthehouseDay4",
    "caption": "Number of children  0-5 years guest in the house",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
     {
    "type": "number",
    "id": "vaccinatedinhousesDay4",
    "caption": "Number of children 0-5 years vaccinated in houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "vaccinatedoutsideofhousesDay4",
    "caption": "Number of children 0-5 yrs vaccinated outside of houses",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
       {
    "type": "number",
    "id": "NomadVaccinatedDay4",
    "caption": "Number of nomad children 0-5 yrs vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "section",
    "id": "NonVaccinationSection4"
  },
  {
    "type": "label",
    "id": "NonVaccinatedchildrenDay4Label",
    "caption": "<h3>Children Non-Vaccination Information</h3>"
  },
  {
    "type": "number",
    "id": "RemainingAbsentDay4During",
    "caption": "Remaining  Absent (return during campaign) [Days 1-3]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  {
    "type": "number",
    "id": "vaccinatedAbsentDay4During",
    "caption": "Found vaccinated Absent (return during campaign) [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
    {
    "type": "number",
    "id": "teamAbsentDay4",
    "caption": "Vaccinated by team Absent (return during campaign) [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
      {
    "type": "number",
    "id": "FoundVaccinatedAbsentDay4After",
    "caption": "Found vaccinated Absent (return after campaign) [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
        {
    "type": "number",
    "id": "VaccinatedbyteamAbsentDay4After",
    "caption": "Vaccinated by team Absent  (return after campaign) [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
         {
    "type": "number",
    "id": "NumberRemainingAbsentDay4After",
    "caption": "Remaining  Absent (return after campaign) [Days 1-3]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
          {
    "type": "number",
    "id": "NumberRecordedNewbornDay4",
    "caption": "Recorded Newborn, Sleep,Sick",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
           {
    "type": "number",
    "id": "NumberVaccinatedNewbornDay4",
    "caption": "Found vaccinated Newborn, Sleep, Sick [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
             {
    "type": "number",
    "id": "VaccinatedByTeamNewbornDay4",
    "caption": "Vaccinated by Team Newborn, Sleep, Sick [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
              {
    "type": "number",
    "id": "RecordedRefusalDay4",
    "caption": "Recorded  Refusal",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                {
    "type": "number",
    "id": "VaccinatedRefusalDay4",
    "caption": "Vaccinated by Team Refusal [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                  {
    "type": "number",
    "id": "RemainingRefusalDay4",
    "caption": "Remaining Refusals [Day 4]",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   
                  {
    "type": "number",
    "id": "TotalChildrenVaccinatedDay4",
    "caption": "Total Children vaccinated",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
                   {
    "type": "number",
    "id": "AFPcaseDay4",
    "caption": "AFP cases",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
  {
    "type": "number",
    "id": "MissedVaccChildren",
    "expression": "(teamAbsentDay1+teamAbsentDay2+teamAbsentDay3)+(VaccinatedByTeamNewbornDay1+VaccinatedByTeamNewbornDay2+VaccinatedByTeamNewbornDay3)+(VaccinatedRefusalDay1+VaccinatedRefusalDay2+VaccinatedRefusalDay3)",
    "caption": "Recorded Missed Children Vaccinated on the same day by the Teams during Revisit (Days 1-3)",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
  {
    "type": "number",
    "id": "MissedVaccChildrenDay4",
    "expression": "teamAbsentDay4+VaccinatedByTeamNewbornDay4+VaccinatedbyteamAbsentDay4After+VaccinatedRefusalDay4",
    "caption": "Recorded Missed Children Vaccinated on Day 4 by the Teams during Revisit",
    "styles": [
      "row",
      "col-3"
    ]
  },
  
   {
    "type": "number",
    "id": "TotalVaccChildren",
    "expression": "TotalChildrenVaccinatedDay1+TotalChildrenVaccinatedDay2+TotalChildrenVaccinatedDay3+TotalChildrenVaccinatedDay4",
    "caption": "Children Vaccinated during SIA by Teams",
    "styles": [
      "row",
      "col-3"
    ]
  },

    {
    "type": "number",
    "id": "OPVWastageTotal",
    "caption": "Wastage (Recieved-(Used+Returned)/Received)/100",
"expression": "((NoofFullvialsreceivedDay1+NoofFullvialsreceivedDay2+NoofFullvialsreceivedDay3+NoofFullvialsreceivedDay4)  - (NoofFullvialsreturnedDay1+NoofFullvialsreturnedDay2+NoofFullvialsreturnedDay3+NoofFullvialsreturnedDay4)/(NoofFullvialsreceivedDay1+NoofFullvialsreceivedDay2+NoofFullvialsreceivedDay3+NoofFullvialsreceivedDay4))/100",
    "styles": [
      "row",
      "col-3"
    ]
  }

]

**Comment by StefanKock** [comment]
@tomabadaniel please provide system details and exception log

**Comment by tomabadaniel** [comment]
@StefanKock  Do you still need the system details and exception log? Seems you have moved this issue to Sprint Backlog

**Comment by tomabadaniel** [comment]
https://test-afghanistan.sormas.netzlink.com/sormas-ui/login#!campaign/data/UT5HKR-3GDBCA-MYIOXL-J35PSLR4
[logfileJuly15.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6822690/logfileJuly15.txt)

**Comment by MateStrysewske** [comment]
@tomabadaniel Can you please trigger the bug on the test server and request exception logs from that exact time (about 5 minutes before and after you triggered the bug, but not more)? I can't easily reproduce it on my local system. Thanks!

**Comment by MateStrysewske** [comment]
Error evaluating expression: OPERATOR_NOT_SUPPORTED_BETWEEN_TYPES / EL1030E:(pos 0): The operator 'SUBTRACT' is not supported between objects of type 'null' and 'null' (de.symeda.sormas.ui.campaign.expressions.ExpressionProcessor.java:99)

Error evaluating expression: OPERATOR_NOT_SUPPORTED_BETWEEN_TYPES / EL1030E:(pos 0): The operator 'ADD' is not supported between objects of type 'null' and 'null' (de.symeda.sormas.ui.campaign.expressions.ExpressionProcessor.java:99)

Error evaluating expression: PROPERTY_OR_FIELD_NOT_READABLE / EL1008E:(pos 2): Property or field 'NoofFullvialsreceivedDay1' cannot be found on object of type 'java.util.HashMap' - maybe not public? (de.symeda.sormas.ui.campaign.expressions.ExpressionProcessor.java:99)

**Comment by MateStrysewske** [comment]
@tomabadaniel So the problem occurs if you have an expression in the form that adds or subtracts the values of two other fields and at least one of these fields is left empty. The question is - how should we deal with this situation? I have two possible solutions in mind, but I need you to decide which route to go (or make an alternative suggestion if you have a better idea):

1. Ignore the expression calculation if at least one of the fields is empty, because semantically, empty != 0; the calculated field would then have no value.
2. Treat empty values as 0. Would lead to the calculcated fields still being populated, but makes the assumption that empty == 0, which could be semantically wrong.

**Comment by MateStrysewske** [comment]
@MateStrysewske On second thought, the errors you are experiencing are probably totally unrelated to the errors I found in the logs because those were no exceptions, and while I get the same errors from the logs, I don't get the exception on the dashboard... that means I, unfortunately, still don't really have an idea what causes them because I didn't find any exceptions in the error logs and still can't reproduce them on my local system

**Comment by tomabadaniel** [comment]
@MateStrysewske  I have been locked out of the server because I dont have VPN access to the server anymore. Please can you ask Netzlink to provide this? I have sent them an email that I have been locked out. Frank has not responded to me yet. Since Yesterday.  Thanks

**Comment by tomabadaniel** [comment]
@MateStrysewske So i just got back access to the server. See requested JSON definition. 

[
  {
    "fieldId": "TotalVaccChildren",
    "formId": "DailyCompSheet",
    "stack": "H2H",
    "caption": "Children Vaccinated During SIAs by Teams (H2H)"
    
  },
  {
    "fieldId": "TotalVaccChildren",
    "formId": "M2MS2SSheet",
    "stack": "M2M/S2S",
    "caption": "Children Vaccinated During SIAs by Teams (M2M & S2S)"
  },
  {
    "fieldId": "TotalVaccChildren",
    "formId": "OPVHF2HFCompSheet",
    "stack": "HF2HF",
    "caption": "Children Vaccinated During SIAs by Teams (HF2HF)"
  },
  
    {
    "fieldId": "TotalVaccChildren",
    "formId": "DailyCompilationSheetOLD",
    "stack": "H2H(OLD)",
    "caption": "Children Vaccinated During SIAs by Teams (H2H-OLD)"
  }
  ]

**Comment by MartinWahnschaffe** [comment]
@tomabadaniel Hi Daniel, I tried this definition together with total json definition `[{"populationGroup":"AGE_0_4"}]` and this works fine for me. Could you please make sure that the campaignseriestotal column does not contain anything else (e.g. stack definitions)?

**Comment by MartinWahnschaffe** [comment]
@tomabadaniel I found the probem
