### ISSUE TITLE
Missing values in detailed case export

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#6112]
### Bug Description

**Comparison case view (Case) vs. case detailed export template
Missing in case detailed export template:**

 - Reporting User
- Date of Investigation
- Sequelae
- Describe Sequelae
- Prohibition to Work
- Prohibition to Work from
- Prohibition to Work until
- Responsible Jurisdiction
- Place of stay
- Place Description
- Checkbox: Responsible jurisdiction of this case differs from its place of stay
- Home-Based Quarantine possible?
- Home-Based quarantine_Comment
- Supply Ensured
- Supply Ensured_Comment
- Follow-Up Status Comment 
- Responsible Surveillance Officer
- Date Received at District Level
- Date received at Region level
- Date received a National Level
- General Comment

**Comparison case view (Hospitalization) vs. case detailed export template
Missing in case detailed export template:**

- Reason For Hospitalization
- Stay in The Intensive Care Unit
- Start of the stay
- End of the Stay
- Isolation
- Date of Isolation
- Was the Patient Hospitalized or did he/she visit a health clinic previously for this illness?

**Comparison case view (Epidemiological Data) vs. case detailed export template
 Missing in case detailed export template:**

- Exposure Investigation
- Activity Details known
- Residing or working in an area with high risk of transmission
- Residing or travelling to countries/territories/areas experiencing larger outbreaks

 
**Comparison case view (Therapy) vs. case detailed export template**

- Content is missing entirely in the export template

**Comparison case view (Clinical Course) vs. case detailed export template**

- Content is missing entirely in the export template

### Steps to Reproduce

1. open case directory
2. choose cases for detailed export
3. compare exported values with available values in Sormas

### Expected Behavior

All available values should be available in detailed export

### System Details

* Device:
* SORMAS version: 1.60/1.61
* Android version/Browser:
* Server URL:
* User Role: admin/national user

**Comment by MateStrysewske** [comment]
@JaquM The detailed export was never designed to include every single value that is associated with a case, but a large subsets of the most relevant values. I would like to ask you to refine which of these values are actually necessary for the export (as more information <=> less clarity). Also, concerning e.g. the therapy and clinical course sections, we would need you to define how exactly that information should be integrated into the export.

**Comment by JaquM-HZI** [comment]
I close this and open a change request
