### ISSUE TITLE
Contacts detailed export missing values 

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#6113]
### Bug Description

**Values that are missing in the detailed_export_template compared to Contact (Contact tab)**

- Internal Token
- Case ID in External System (or is this SourceCaseUuid?)
- Case or Event information
- Additional Information on the type of contact
- Contact Category
- Relationship with case
- Description on how contact took place
- Prohibition to Work (with Beginning and End date)
- Home-Based Quarantine possible?
- High Priority Contact
- Pre-Existing Conditions (entirely missing)
- Immunosupressive therapy or basic disease is present
- Is the person medically/nursingly active in the care of patients or people over 60 years of age?

 
**Values that are missing in the detailed_export_template compared to Contact (Contact Person Tab)**

 - Passport Number
- National Health ID
- Internal Token
- Education
- Area Type (Urban/Rural)
- Community Contact Person
- Nickname
- Mother's maiden name
- Mother's name
- Father's name
- Name of Guardians

 
**Values that are missing in the detailed_export_template compared to Contact (Epidemiological Data)**

- Everything is missing here

### Steps to Reproduce

1. Open contact directory
2. select contacts for export
3. compare export template to available values in Sormas

### Expected Behavior

All available values should be included in detailed contact export.

### System Details

* Device:
* SORMAS version: 1.60/1.61
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@JaquM The detailed export was never designed to include every single value that is associated with a contact, but a large subsets of the most relevant values. I would like to ask you to refine which of these values are actually necessary for the export (as more information <=> less clarity). Also, concerning e.g. the epidemiological data section, we would need you to define how exactly that information should be integrated into the export.

**Comment by JaquM-HZI** [comment]
I close this and open a new one as change request
