### ISSUE TITLE
[SORMAS2SORMAS] Shares > Share Requests > Response Comment (reject/accept) [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6122]
### Situation Description

When a receiving SORMAS instance rejects a shared entity in 'Shares', a prompt shows up asking if the user is sure that they would like to reject the entity.  The sending SORMAS instance does not know:

1. That the entity was rejected by the receiving instance (it is not kept in the history list).
2. The reason for rejecting the entity by the receiving SORMAS instance.

Current rejection message:
![image](https://user-images.githubusercontent.com/65529128/125603805-4a0dbebe-3f61-4113-a1b1-48f00832443a.png)

### Feature Description

When a receiving SORMAS instance rejects a shared entity listed under 'Shares', users would find it helpful to be able to attach a comment on the reason why it was rejected and send this back to the sending SORMAS instance.  This rejection message should then show up in the sending SORMAS instance's list.

![image](https://user-images.githubusercontent.com/65529128/125605500-7654202a-f854-467d-be42-5c103efda306.png)

### Additional Information

- [ ]  add a new column on the share info with the name responsecomment

The current Shares tab/Share requests directory keeps track of entities that are received by the current SORMAS instance, not sent.  This feature request may require the introduction of an 'outgoing' tab and 'incoming' tab to further distinguish between entities.

![image](https://user-images.githubusercontent.com/65529128/125607409-bafd5ea2-3cdd-4f53-b9ac-2600ba03fdd6.png)

**Comment by markusmann-vg** [comment]
- [ ] add a new column on the share info with the name responsecomment

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.65.0-SNAPSHOT from the development branch.
