### ISSUE TITLE
[Angular] Event profile : event participants (list section) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6135]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/4a2zPq3
- We need to implement the short ID links and be able to navigate to the correct destination (based on the work done by @sandorbanvitagroup )
- We should add the "Bulk" actions button (together with the options inside - without the action itself)
- We should add the checkbox "Contacts whose..." without the action itself
- If we don't have a case id, we should have a link to "Create new case" which would open the new case modal

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
