### ISSUE TITLE
[Angular][Backend][SPIKE] Investigate existence of endpoints for the following sections [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6136]
### Problem Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Proposed Solution

- Investigate if we have endpoints for: 
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/zxzMdoo  
and https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/eKpA3Y0 
and https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/4a2zPwA 
and https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/kad13zO 
and https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yP4dgO
(event group, subordinates events, share, document, document template, reporting tool, reports, pathogen tests, additional tests, actions)
- Please provide a list with the endpoints available and the ones missing so we know which need to be built.

### Possible Alternatives

-N/A

### Additional Information

-N/A

**Comment by marius2301** [comment]
eventGroup - **no endpoint** - I suppose we need one with criteria 
superordinate event - **no endpoint** -  but there is a reference to the superordinate in the eventDTo - It might be enough
document - **no endpoint** -
documentTemplate - **no endpoint** -
