### ISSUE TITLE
[Angular] Event profile : event actions [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6139]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yApaY3
- Filtering will be done on the FE (as we won't have many items)
- We need to add the document actions (upload / delete a document) - even if not integrated with the BE
- If we have documents retrieved from the BE we can display them
- The download action should be triggered by both clicking on the icon and the file text link
- The number of cards that fit on a row is defined by the screen resolution
- We have a "Show more" action at the bottom (if the cards don't fit in a single screen)
- All cards / sub-cards (the ones below the actual cards) should be of the same size (regardless of how many document or data they contain)

### Possible Alternatives

- N/A

### Additional Information

-N/A

**Comment by cristinacoza** [comment]
UI/UX review done - some styling issues need to be fixed: 
- "Action status" filter & "Create" Button - padding top 32p
- Created by - always at the bottom of the card
- Document section - border colour #B2E1E6 (primary alternative colours - A200)

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
