### ISSUE TITLE
[Angular][Backend] Event profile : event actions endpoint [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6140]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to implement an endpoint for the events actions section which should return all the required data as presented in the cards from: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yApaY3 (including the documents links)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by marius2301** [comment]
This is partially implemented and it is in review. In the current implementation the (name of) documents are not in the return DTO. I need to talk to Martin to see how we should do it.
