### ISSUE TITLE
Import module should not consider white spaces for infrastructure data names

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6144]
### Bug Description

Region name with white spaces after the name on import data are not mapped with the same region in the system.

### Steps to Reproduce

1. Create a region in the sytem
2. Import a hospital in the region, on import template, use region name with space at the end, eg "Berlin "
3. System does not map the region with the "Berlin" in the system

### Expected Behavior

- Delete white spaces before of after the name before matching
- I think we should not delete white spaces within the name, eg "New Berlin" should not be mapped with "NewBerlin"
- Character case should not also matter berlin == BerLin
### System Details

* Device:
* SORMAS version: 1.60.3
* Android version/Browser:
* Server URL: https://test-inhp-ci.sormas.netzlink.com/sormas-ui/#!about
* User Role:

**Comment by bernardsilenou** [comment]
@MateStrysewske  Please can you refine further?

**Comment by DavidBaldsiefen** [comment]
I think this has significant overlap with #6153
