### ISSUE TITLE
[Ediary Integration] Cases&Contacts > Follow-up view > `Symptom Journal Status` Unregistered not filtering correctly

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6146]
### Bug Description

For Cases & Contacts on the follow-up view, when filtering for users by `Symptom Journal Status` set to 'Unregistered' does not show correct values.

### Steps to Reproduce

1. Cases&Contacts > Follow-up view
2. Set `Symptom Journal Status` as 'Unregistered' > No results are displayed 

### Expected Behavior

As 'unregistered' entries are currently indicated with a blank (null) value, it would be helpful to display these values.  Otherwise, set the status to 'unregistered'.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/125925957-dff65740-e934-4b65-a0ef-72596ec0eb69.png)
![image](https://user-images.githubusercontent.com/65529128/125927288-eeac9110-6d83-451e-9855-7a5ab4d6a851.png)

### System Details

* Device: PC
* SORMAS version: 1.61.1
* Android version/Browser: Chrome
* Server URL: https://release-de.sormas.netzlink.com/
* User Role: admin, national user

### Additional Information

Not sure if it's a bug or rather a change request...

**Comment by FredrikSchaeferVitagroup** [comment]
Currently in SORMAS, there is a difference between `Symptom Journal Status` == UNREGISTERED and `Symptom Journal Status` == NULL. The first indicates that a person is not registered, the second indicates that there is no information about the symptom journal status.

It is probably correct that SORMAS can assume more often that a person is unregistered.

I propose to:
- [ ] set the `Symptom Journal Status` to UNREGISTERED whenever a new person is created (be it via UI or import)
- [ ] retrospecively do the same for all existing persons in the database with `Symptom Journal Status` == NULL

**Comment by FredrikSchaeferVitagroup** [comment]
I have implemented changes that should realise my proposal. 
To make sure that the changes can properly be tested, we should wait with merging until test systems are online again.
