### ISSUE TITLE
Check SMS and E-Mail notification functionality

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#615]
Doesn't seem to work on the symeda server right now.

**Comment by MartinWahnschaffeSymeda** [comment]
Email is working fine. SMS doesn't seem to work.

@hzi-braunschweig Is the NEXMO account still active and paid?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
- [ ] setup another NEXMO account for the nigerian system
- [ ] change the credentials on sormas.org.ng
- [ ] charge the NEXMO account for the sormas.hzi and sormas.symeda servers

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Any progress on this?

**Comment by MartinWahnschaffeSymeda** [comment]
Setting up Nexmo for the server is a bit more complicated because of payment issues.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Are SMS send now?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym  Yes I just loaded 10 euros into the nexmo account. and also changed the auth key details on the nigeria server. So it should work now.
