### ISSUE TITLE
Opening Events directory throws Exception

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#6154]
### Bug Description
Opening Events directory throws Exception

### Steps to Reproduce
1. Open events directory

### Expected Behavior

No Exception

### Stacktrace
```
Caused by: org.postgresql.util.PSQLException: ERROR: column event0_.diseasevariant does not exist
at ...
at de.symeda.sormas.backend.event.EventFacadeEjb.getIndexList(EventFacadeEjb.java:421)
```

### System Details

* SORMAS version: 1.62.0 - SNAPSHOT

### Additional Information
Also find out why tests did not catch this, and **write tests** that will prevent such problems in the future

**Comment by MateStrysewske** [comment]
@DavidBaldsiefen Please confirm that you have the following entry in your schema_version table: 'Add disease variant to event #5525', version number should be 383. I suspect that something went wrong with your database upgrades because of switching branches.

**Comment by DavidBaldsiefen** [comment]
@MateStrysewske you were correct, apparently something went wrong switching branches. Sorry for the wrong report!
