### ISSUE TITLE
APMIS form dropdown does not leave screen after a form is clicked on

### ISSUE THREAD

**Issue by tomabadaniel** [hzi-braunschweig/SORMAS-Project#6162]
### Steps to Reproduce

1. Open APMIS and go to campaigns. CLick on New form and select a form
2. The form opens but the form dropdown still remains.

### Screenshots

![image](https://user-images.githubusercontent.com/60390281/126200947-5db6f426-0de2-4218-88d1-02861b43ad36.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by DavidBaldsiefen** [comment]
Fix is probably similar to #4205
