### ISSUE TITLE
Visit symptoms set to "No" and "Unknown" are not transferred to the symptoms tab of cases

### ISSUE THREAD

**Issue by jkheise** [hzi-braunschweig/SORMAS-Project#6171]
### Bug Description
When cases document symptoms in SORMAS-SB, they are transferred to SORMAS and displayed in the follow-up view. The symptoms that have been answered with "no" in SORMAS-SB are not shown in the "Symptoms" page (see video attached).

### Steps to Reproduce

1. Answer the symptom questionnaire with a test case and click on submit
2. The answers are transferred in SORMAS and can be found can be found under the menu item Follow-up.
3. Clicking on the symptoms button should show the same symptoms here. 
4. But the symptoms that were answered with no in the symptom questionnaire SORMAS-SB are missing here. 

### System Details
* Device: Web
* SORMAS version: 1.61.1 and 1.62
* Android version/Browser: Google Chrome, Microsoft Edge 
* Server URL:  https://release-de.sormas.netzlink.com
* User Role: admin

https://user-images.githubusercontent.com/77160218/126339764-f72142e0-067f-412d-8247-a2b1a5f7ef5e.mp4

**Comment by jkheise** [comment]
@maxiheyner @jesseangelis Here is the ticket we just discussed.

**Comment by AndyBakcsy-she** [comment]
Reopening issue as the Values No and Unknown are not set under the Symptoms tab. 
Created new Case, registered it on Pia and completed the first questionnaire. After the synchronization, found the changes under the Follow-up tab but there is missing data under the Symptoms tab.

**Comment by AndyBakcsy-she** [comment]
![image](https://user-images.githubusercontent.com/70562142/127322067-883a9c73-cc99-4029-b02b-b85075fbe867.png)
and 
![image](https://user-images.githubusercontent.com/70562142/127322107-ded0cec9-825f-400b-8f7d-2ecf01d17445.png)

**Comment by Alexandru-Pirvu** [comment]
@AndyBakcsy-she The issue seems to be resolved. The reason it didn't work before is that the deploy failed.
