### ISSUE TITLE
Relaunching SORMAS <-> PIA integration

### ISSUE THREAD

**Issue by irinajanzen-hzi** [hzi-braunschweig/SORMAS-Project#6175]
### Situation Description
PIA will also implement keycloak. Before that, the interface between PIA and SORMAS must be relaunched. We would like to focus on the same implementation as Climedo in order to keep the effort low.
In one point, however, we do not consider the Climedo solution to be advisable for reasons of data protection. It's about how a GA-worker can find out the PIA pseudonym (username, is used for logging into PIA). This must be communicated by telephone. After our keycloak changeover (in late autumn), we want to enable self-registration so that the telephone call is no longer necessary. Until then we need a solution for the intermediate phase.
 
### Feature Description
The following two options are available for the intermediate phase:

**1. SORMAS saves the pseudonym and displays it directly (transferred by POST)**

**advantages:**
+ Better usability
+ Better security (no backend token in the frontend)

**disadvantages:**
- Must be implemented by SORMAS first: Would that be feasible for you?
- Pseudonym must be saved in SORMAS: Must be clarified with data protection. We don't think that's great.
 
**2. When you click on the "Open in symptom diary" button in SORMAS, a static page is opened where only pseudonyms (email, uuid, ...) are displayed, but you are not logged in and have no other options.**

**advantages:**
+ Possibility that the data synchronized in PIA can also be checked (e.g. email address)
+ Can be implemented by us
+ The pseudonym does not have to be saved in SORMAS

**disadvantages:**
- Jumping out of SORMAS necessary => Worse UX
- Inferior security (backend token in the frontend with current implementation): This is problematic from our point of view and should actually not be re-implemented. If we implement pure backend communication for this, SORMAS would need to be involved. Is that feasible for you? It would have high priority for us, as we now want to implement the stories quickly in order to be able to start with Keycloak (for data protection reasons we must finally implement Keycloak).

### Possible Alternatives

Option 2 with a frontend token.

### Additional Information
In the long term, the current implementation of the connection of symptom diaries to SORMAS should be revised again and implemented according to current standards (with regard to REST and OpenID Connect).

**Comment by irinajanzen-hzi** [comment]
cc @soja-hzi @jkheise

**Comment by maxiheyner** [comment]
@irinajanzen-hzi @kwa20 @JaquM before we can set it to the prio list we have to discuss and decide one option. Please organize a meeting with the corresponding team members.

**Comment by FredrikSchaeferVitagroup** [comment]
As mentioned before, there might be other options, such as creating a frontend token.

**Comment by FredrikSchaeferVitagroup** [comment]
Coming back to the title of this issue `Relaunching SORMAS <-> PIA integration`, there were two issues identified as necessary on SORMAS side to allow full interaction of PIA and SORMAS.
These are #6478 and #6480. Is there anything else necessary? If not, there's probably nothing left to do in this ticket.

**Comment by irinajanzen-hzi** [comment]
@FredrikSchaeferVitagroup you're right!
