### ISSUE TITLE
Identity comparison of dates

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#6177]
### Bug Description

In several places, e.g. in `CaseFacadeEjb`, dates are compared using `==`  or `!=` instead of e.g. `::equals`.
In `::updatePersonAndCaseByOutcome` this can at least lead to an 
updated changeDate for a person even though the person data did not have to be changed and maybe also has performance implications.
In this case it may even only be necessary to compare the date parts of the outcome dates and maybe also compare with the deathDate of the person before altering the deathDate of the person.

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

Regex identifying some candidates:
`(Date|Time|From|Until)(\(\))? *[!=]= *(?!\s|null)`

**Comment by StefanKock** [comment]
I removed the `performance` label since we usually tag tickets with this label that have severe performance impact, and I don't that here.
