### ISSUE TITLE
Sharing with external surveillance tool may not get documented 

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#6178]
### Bug Description

#5153 has introduced a timout of 60 seconds for the converter to create a transport, hand it over to the SurvNet webservice, and update external values in SORMAS.
Depending on the number of cases or events to be sent, this may not be sufficient.

When sending succeeds after the time has elapsed, the data reaches SurvNet without share infos being created.

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version: 61.1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by vidi42** [comment]
Possible after https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/209
