### ISSUE TITLE
[SORMAS2SORMAS] Shares > Share requests > Rejected items should delete preview data [1]

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6180]
### Feature Description

Delete preview data from rejected entities in the Shares queue (on the receiving SORMAS instance's side).

### Problem Description

An entity is sent from SORMAS instance A to SORMAS instance B.
SORMAS B gets a preview to view before accepting/rejecting the entity.
If SORMAS B rejects the entity, the preview data is still available, despite the rejection.

![image](https://user-images.githubusercontent.com/65529128/126487355-e258c0cd-8cbf-48b9-9d3c-6cfdf673b141.png)
![image](https://user-images.githubusercontent.com/65529128/126486897-1c38f2d8-2b2b-48cc-a7d4-17d9d05a6810.png)

### Proposed Change

Delete an item's preview data on the receiving entity when it is rejected by the receiving entity.

### Possible Alternatives

Changing visibility of the 'view' icon (i.e. hiding the icon upon rejection) may be a temporary workaround, but from a data minimization perspective may not be sufficient in the long run.

**Comment by markusmann-vg** [comment]
- We delete the preview details but we keep the transaction request.

**Comment by leventegal-she** [comment]
Additionally the rejected share requests are no longer displayed
