### ISSUE TITLE
[SORMAS2SORMAS] Share Entity > Popup window options rewording (English)

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6192]
### Feature Description

When sharing a SORMAS2SORMAS entity, a popup appears presenting the options of how to share the entity.

The captions "Pseudonymize personal data" and "Pseudonymize sensitive data" should be changed to "Exclude personal data" and "Exclude sensitive data" in the source code (German translation: "Persönliche Daten ausschließen" and "Sensitive Daten ausschließen").

### Problem Description

Translations for de-DE have been done in CrowdIn for de-DE language users.  The original English would still remain in the source code and should be updated.

### Proposed Change

1.
Current | New | de-DE
|--|--|--|
Pseudonymize personal data | Exclude personal data | Persönliche Daten ausschließen
Pseudonymize sensitive data | Exclude sensitive data | Sensitive Daten ausschließen

2.
Also, the word 'Orgainzation' should be replaced with 'Organization' (see image below), please.

![image](https://user-images.githubusercontent.com/65529128/126627461-4de64669-7424-4497-9354-e8938b74a2a3.png)

### Additional Information

For DE: Translations for de-DE done in CrowdIn on 22.07.2021

**Comment by ChristopherRiedel** [comment]
@Candice-Louw At the moment the term 'Orgainzation' only exists in 7 Crowdin translated files:
![Screenshot_022](https://user-images.githubusercontent.com/42139870/134167208-ae1cb4d0-b7c6-49a6-a7f9-cb32164eb867.png)
s.
