### ISSUE TITLE
Provide PERSON Exports (basic, detailed, custom) [3]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#6206]
### Situation Description

Users need export functionalities in the person directory to get information out of the system.

### Feature Description

Add a basic, detailed and custom export to the person directory, similar to exports in other directories.

The detailed export should contain all basic fields in the person entity, including/extended by the home address fields and the primary email address and primary phone number

### Additional Information

Finish #6188 before

**Comment by StefanKock** [comment]
I suggest to split out the basic export for persons because: Is mostly independent (except the UI menu), the backend already exists, can be tested and delivered earlier

**Comment by ChristopherRiedel** [comment]
@kwa20 What would you say, who shoulb eb able so export persons?

**Comment by kwa20** [comment]
@ChristopherRiedel Since person data is a sensitive topic, I would suggest to only allow admins, national users and admin surveillance supervisor to allow performing the export.

Only problem we might have are admins, which technically can not view person data as a single user role. However, combining admin with national user would work.

**Comment by ChristopherRiedel** [comment]
@kwa20 so then only national users and admin surveillance supervisors should be able to?

**Comment by kwa20** [comment]
@ChristopherRiedel Yes exactly. I think that should suffice for now

**Comment by AndyBakcsy-she** [comment]
Validated the ticket on the latest deployed SORMAS Version: 1.64.0-SNAPSHOT on test.sormas.netzlink.com
