### ISSUE TITLE
Authentication header is lost in LBDS communication

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#6207]
### Bug Description

In LBDS communication (#3522), authentication headers are lost, so a successful transfer of persons and cases is not possible.
LBDS expects headers to be of the non-standard form "<name>=<value>", while the standard form "<name>: <value>" is currently implemented in the SORMAS app.

The header separator should be adapted to "=" to allow the SORMAS app to work with LBDS service app and backend in the followinge versions:

- lbds-service-app-0.0.10.apk 
- lbds-backend-1.15.0.jar

### System Details

* Device:
* SORMAS version: 1.62.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by StefanKock** [comment]
Not a bug because it was an incomplete implementation of #3522 within the same sprint and version
