### ISSUE TITLE
Provision/Availability of the names of cases in the Cases directory for Lab users.

### ISSUE THREAD

**Issue by Ikemefule** [hzi-braunschweig/SORMAS-Project#6216]
### Feature Description

The Cases directory houses basic demographics 
### Problem Description

The Cases directory houses basic demographics but the First name and Last name
![Capture_LI](https://user-images.githubusercontent.com/36294145/126984108-ccf17d96-0e73-4e21-8e33-99ed1d484e2a.jpg)
 of these cases shows as "Confidential name" for lab users
### Possible Alternatives

Please ensure that the name of these cases are present and shown as it is. This will enable ease of case matching with respect to efforts that have been made in data transition.

### Additional Information

We can ensure that the names are not editable by those in the lab for data security.

**Comment by Ikemefule** [comment]
The Cases directory houses basic demographics but the First name and Last name of these cases shows as "Confidential name" for lab users.

**Comment by MateStrysewske** [comment]
@Ikemefule Hey! Version 1.61.0 introduces such a change - I suspect you're currently running an older version (which is totally fine given that 1.61.0 has not been officially approved yet)?

**Comment by Ikemefule** [comment]
Oh yes, we are currently running on SORMAS Version: 1.60.3.
We look forward to moving soon to the later updates

**Comment by MateStrysewske** [comment]
@Ikemefule I'll keep this issue open in case something's still not working as expected - would be great if you could give me a quick feedback after the upgrade to 1.61.0 (or later)!

**Comment by Ikemefule** [comment]
Sure thing Mate.
 Will do that
