### ISSUE TITLE
Filtering contacts record by disease and time

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#623]
I tried to sort contact of all lassa cases for the past 30 days but I could not do so besaus the  contact directory  filter contacts by disease of source case but not  by time. I suggest we add time to it just like the case directory such that it will be possible to see  all the contacts of cases of 2018 outbreak only in the future not a pool of all contacts for the last  "n" outbreaks. We can use date of last contact with case as first option and date of contact creatinon as second option.
Regards,
Bernard

**Comment by MateStrysewskeSym** [comment]
Done in #972
