### ISSUE TITLE
See events within the same facility filter results in error on the event directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6236]
### Bug Description

When filtering for events within the same facility, a result appears on the event directory.
### Steps to Reproduce

1. Open an event with a facility as the location
2. Press the "See events within the same facility" filter
3. Check directory

### Expected Behavior

The filter should display the events within the same facility on the directory
### Screenshots

<img width="638" alt="eventFacilityFilterError" src="https://user-images.githubusercontent.com/70317594/127484994-ea5f611b-3999-4166-88c4-697b9a969a45.PNG">

<img width="833" alt="eventFacilityFilterError2" src="https://user-images.githubusercontent.com/70317594/127484872-4d488d63-ea1f-43b9-a990-4be954ce5898.PNG">

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
@maxiheyner fyi

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.63.0-SNAPSHOT on test.sormas.netzlink.com
