### ISSUE TITLE
Documentation of "duplicate detection" in SORMAS

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#6240]
### Problem Description

As a lot of SORMAS users use the import functionality, that triggers the duplicate detection, they want to understand better, how the duplicate detection in SORMAS is working. 

### Proposed Solution

Markdown file where the functionality is described for the included fields and if applicable, 
how does the multilevel duplicate detection work from step a - z
 

### Additional Information

Old documentation approach:

* first & last name concatenated with whitespace. Similarity function with default threshold of 0.65D
uses postgres pg_trgm: https://www.postgresql.org/docs/9.6/pgtrgm.html
* same disease
* same region (optional)
* report date within 30 days of each other
* same sex OR same date of birth (when defined)
* same birth date (when fully defined)
* onset date within 30 days of each other (when defined)
 
Code:

https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
getCasesForDuplicateMerging

**Comment by MateStrysewske** [comment]
The guide has been added to the Wiki here: https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Duplicate-Detection-Mechanism
