### ISSUE TITLE
Provide script for updating of person details from csv file

### ISSUE THREAD

**Issue by stefan-ho** [hzi-braunschweig/SORMAS-Project#6243]
### Problem Description
In German health departments the situation may arise where existing COVID19 data is migrated from SurvNet to SORMAS without person details (only pseudonymized data available in SurvNet). In this case, COVID19 cases are imported to SORMAS with related persons but the person details are missing (e.g. first name, last name etc.). Additionally, person details are available from a separate csv file containing a shared ID (e.g. External Token).

The person details available from a csv file need to be imported to SORMAS and existing person details need to be updated with that data.

### Proposed Solution
When data migration from SurvNet is carried out in a helath department, the rollout team needs a script that imports the person details from a csv file to a SORMAS instance.

The csv import script should identify the according person in SORMAS for each csv record (row) by a shared ID (e.g. External Token) and set the fields from the csv file in the according field in the SORMAS database.

The csv file to be processed has following structure:
<img src="https://user-images.githubusercontent.com/78736541/127618361-ba6f96eb-187e-42f0-9972-58af7aaf9ba1.PNG" width="400" >

The script should provide the information (logging) for which csv records 
* the according case/person in SORMAS was found and person data was updated 
* the according case/person in SORMAS was not found

The script should provide following configurable parameters: 

- [ ] the field in SORMAS that is used for identification of the csv records (e.g. externalToken)

- [ ] option to deselect individual columns of the csv file in the import process

### Possible Alternatives
N/A

### Additional Information
N/A

**Comment by StefanKock** [comment]
Proposal by @HolgerReiseVSys: Include the person CSV files into the initial import by sormas-survnet-interface.

**Comment by vidi42** [comment]
> Proposal by @HolgerReiseVSys: Include the person CSV files into the initial import by sormas-survnet-interface.

https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/237
