### ISSUE TITLE
Data dictionary downloads are not tranlsated when getting them from import pop-ups

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6244]
### Bug Description

When downloading the data dictionary not from the info page but e.g. from import pop-ups, the data dctionary is not translated depending on the user language as implemented in https://github.com/hzi-braunschweig/SORMAS-Project/issues/4607.
### Steps to Reproduce

1. Set the user language to another language than english
2. Go to e.g. the case directory
3. Select detailed import
4. Download the data dictionary in the subsequent pop-up

### Expected Behavior

Independent of where the data dictionary is downloaded, it will be translated according to the user language setting.
### Screenshots

<img width="949" alt="datadictTranslation" src="https://user-images.githubusercontent.com/70317594/127634163-0081b975-079e-449f-89ef-380b3e11b548.PNG">

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest SORMAS Version: 1.63.0-SNAPSHOT on test.sormas.netzlink.com
