### ISSUE TITLE
[DEMIS2SORMAS] One case is proposed multiple times in the pickOrCreateEntry when processing a lab message

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#6246]
### Bug Description

The GA Trauenstein reported a bug.

### Steps to Reproduce

1. Start processing a lab message with similar entries already processed
2. Pick an existing person that already has a case
-> That case shows multiple times

### Expected Behavior

The case should show just once

### Screenshots

![image](https://user-images.githubusercontent.com/67001822/127640277-f7dafa04-4445-49c6-a069-4e796ddb3a5c.png)

### System Details

* Device:
* SORMAS version: SORMAS 1.61.2, SORMAS-DEMIS-adapter version 1.5.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

The bug does not seem to be reproduceable on https://test1402.sormas-oegd.de/, which should have the same versions of SORMAS and the SORMAS-DEMIS-adapter deployed.

**Comment by FlickyFlack** [comment]
Quick notice: test1402 currently does not have the correct values in the 'customizableenumvalues'-Table.
This means that 1402 and traunstein are currently not 100% comparable.
I dont think it does, but it possibly explains the non-reproducibility.

**Comment by FredrikSchaeferVitagroup** [comment]
One idea would be to find out which db queries are exectued for https://github.com/hzi-braunschweig/SORMAS-Project/blob/af32746a25f0561e7f4b43225ebf8e291d815574/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java#L173

look at them and maybe run them on the GAs database. This might at least show whether the problem is on the db level or not.

The GA already reported that the case shows just once in the case directory.

**Comment by FredrikSchaeferVitagroup** [comment]
It was just reported that the bug occurs for contacts as well. For event participants, it was not yet checked.

**Comment by FredrikSchaeferVitagroup** [comment]
It was just reported that the bug seems to only occur for specific users. There are two persons tested.
The bug occurs for one user with all of the following roles:
`Event Officer, Surveillance Supervisor, Clinician, Import User`
The bug does NOT occur for one user with all of the following roles:
`Admin, National User, Import User`

So far, I could not reproduce this either.

**Comment by StefanKock** [comment]
CaseFacadeEjb.getSimilarCases does not `distinct`the results. Cases can come several times now due to `caseService.createUserFilter` left joining on contacts. I assume `cq.distinct(true);` will resolve this.

**Comment by FredrikSchaeferVitagroup** [comment]
To verify this issue:

1. Create a user with the roles `Event Officer, Surveillance Supervisor, Clinician` and `Import User`.
With this user
2. Create a case with a person identical to one shown in an unprocessed lab message
3. Create two contacts (different person)
4. Set the case as source case for both contacts
5. Start processing a lab message, select the case person
-> the case should just show once in the pickOrCreateEntry
