### ISSUE TITLE
Make event participant person sex compulsory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6248]
### Feature Description

Event participant > Person > Sex
### Problem Description

Thus far, the sex field is compulsory for cases and contacts but not for event participants. Because of this inconsistency, some actions have lower usability like the creation of many contacts out of the event participant list (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4969#issuecomment-889834657).
### Proposed Change

Make the sex field also compulsory for event participants.
### Additional Information

NOTE: If event participants person sexes are missing after this change, this might lead to export features exporting empty files (cf. missing compulsory entries in previous hospitalizations). This should not happen after this change has been made.

**Comment by syntakker** [comment]
@MateStrysewske @kwa20

For cases and contacts, sex being required is only checked in the create forms where the respective field is set to be required. For existing cases and contacts, it is possible to clear out this field again. Furthermore, neither during creation in the Android app nor in import the sex field is validated, so it is still possible to have cases and contacts with sex null.

A possible solution would be to make sex mandatory at person level (which affects travel entries and immunizations, too) and check this in the respective edit forms and validations. It might be reasonable to have the import methods handle this gracefully, i.e., if sex is not present in import CSV files, it is set to `UNKNOWN` by default.

Making sex mandatory at person level would furthermore require to update existing person entries in the database (`null` => `UNKNOWN`).

**Comment by syntakker** [comment]
Making sex mandatory at person level is approved by @MateStrysewske and @kwa20.

**Comment by AndyBakcsy-she** [comment]
Validated on the latest  SORMAS Version: 1.63.0-SNAPSHOT on local environment
