### ISSUE TITLE
Place of stay "home" not set when creating cases in the Android app

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#6260]
### Bug Description
Place of stay "home" seems to be handled incorrectly in the Android app. The created case can neither be edited nor synced.

### Steps to Reproduce
In the Android app
1. Create a case, chose "home" for place of stay
2. Save the case
3. try to edit the created case => error
4. try to sync the case => error

The error occurs when setting field values in the case edit form:
```
 30915 30915 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'de.symeda.sormas.api.facility.FacilityTypeGroup de.symeda.sormas.api.facility.FacilityType.getFacilityTypeGroup()' on a null object reference
 30915 30915 E AndroidRuntime:        at de.symeda.sormas.app.caze.edit.CaseEditFragment.onAfterLayoutBinding(CaseEditFragment.java:721)
 30915 30915 E AndroidRuntime:        at de.symeda.sormas.app.caze.edit.CaseEditFragment.onAfterLayoutBinding(CaseEditFragment.java:87)
 30915 30915 E AndroidRuntime:        at de.symeda.sormas.app.BaseEditFragment$1$1.onBound(BaseEditFragment.java:141)
```
Debugging confirms that the case's health facility is null (should be `NO_FACILITY`).

Setting the facility is handled in `InfrastructureDaoHelper.initializeFacilityFields` l. 640ff.

### Expected Behavior
Place of stay "home" should be correctly set and saved when creating a case.

### System Details

* Device:
* SORMAS version: 1.63.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by DavidBaldsiefen** [comment]
Everything works fine for me. I tried creating a case with `placeofstay=home` and transferring existing cases to home. Syncing and further work with the case was no problem (SurvOff, 1.63.0-SNAPSHOT). Can you give more details?

**Comment by syntakker** [comment]
I observed the behaviour when creating a case "in one take", i.e., filling all the fields needed  and click on save.
If the case's validation fails and the case is not saved in the first attempt, but after correction, the bug does not manifest.
This however indicates that the bug is somewhere in or around the create form.

**Comment by AndyBakcsy-she** [comment]
Not able to validate this ticket because it depends on the attached ticket.
