### ISSUE TITLE
Deleted cases should not be considered in the dashboard epi curve

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6261]
### Bug Description

We got the update to 1.61.2 this night.

On the dashboard the Epidemiological Curve is not calculated correctly. In our office it shows 18 cases "Not yet classified", while we have only 6 of them in total.

### Steps to Reproduce

1.  Enter a case of any classification
2.  Check for it being displayed on the epi curve on the surveillance dashboard
3.  Delete that same case
4.  Check the epi curve again
5.  Check the database (via export) for deleted cases if necessary

### Expected Behavior

It should only show the right amount of these kind of cases.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/127957015-17db57fd-bcee-4f5d-be67-06a8998c1ef3.png)

![grafik](https://user-images.githubusercontent.com/74791118/127957072-b22f6246-f290-4fed-a720-889e604ff448.png)

In addition, I extended the time period in the curve to this year and downloaded an Excel spreadsheet via the burger menu. This shows 89 cases as "Not yet Classified":

![grafik](https://user-images.githubusercontent.com/74791118/127958378-5471d52d-aeab-47c6-bd15-fbad729a9162.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by Marko-ilmkreis** [comment]
I also exported all cases and double-checked if there are cases which are not shown in the case-directory correctly, but we stll have only 6 not yet classified cases:

![image](https://user-images.githubusercontent.com/74791118/127958818-cb42b3fe-33bd-4bc2-baaa-6f7a9cfb6226.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis Does changing the case reference date have any effect on the display of the epi curve? Are the other classifications correct or also differing?

**Comment by Marko-ilmkreis** [comment]
@kwa20 For the displayed last weeks in the dashboard the other classifications are correct.
The change of the case reference date brings only other miss-calculation. E.g. if I set on the symptom-onset-date it shows in the dashboard:
![grafik](https://user-images.githubusercontent.com/74791118/127970130-11e40bd0-9aad-4a40-babe-44cb313d0d8b.png)

It shows 3 not classified cases:

![grafik](https://user-images.githubusercontent.com/74791118/127969999-c79c9fae-0e58-4cc2-b3a5-99bfbd34886b.png)

While the case directory shows zero:

![grafik](https://user-images.githubusercontent.com/74791118/127969918-c7b486e2-e89e-4c76-97c1-82f9ad471783.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis I tested a bit further and it seems like the additional entries shown are deleted cases.

@MateStrysewske Is there a way for you to verify this? 

**Steps to reproduce:**
1. Enter a case of any classification
2. Check for it being displayed on the epi curve on the surveillance dashboard
3. Delete that same case
4. Check the epi curve again
5. Check the database (via export) for deleted cases if necessary

**Comment by Marko-ilmkreis** [comment]
@kwa20 I can confirm that these are the deleted cases which are shown wrongly.

**Comment by Candice-Louw** [comment]
Similar behaviour for duplicate detection (https://github.com/hzi-braunschweig/SORMAS-Project/issues/6267) where deleted entities are being considered.

**Comment by DavidBaldsiefen** [comment]
@kwa20 @MateStrysewske 

Should the dashboard also exclude archived cases in the epicurve?

**Comment by kwa20** [comment]
@DavidBaldsiefen archived cases should not be excluded

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20  @DavidBaldsiefen 
Since this kind of request happens repeatedly, would it not be nice to add this instruction to the document on how to contribute to SORMAS, so that all developers can consider in their coding, even if not specified in the story?
For all computation methods, always:
- check and drop deleted entities and
- Include archived entities

**Comment by DavidBaldsiefen** [comment]
> Since this kind of request happens repeatedly, would it not be nice to add this instruction to the document on how to contribute to SORMAS, so that all developers can consider in their coding, even if not specified in the story?

Haha, I just told Mate the same 1 Minute ago :D So yes I agree

**Comment by DavidBaldsiefen** [comment]
@kwa20 I have seen that several counters of the dashboard were affected (contacts, cases, events, ...). I have fixed (hopefully) all of them in this issue, so you do not need to create a new one
