### ISSUE TITLE
Person directory does not load after update to 1.61.2

### ISSUE THREAD

**Issue by ophcode** [hzi-braunschweig/SORMAS-Project#6262]
### Bug Description

After Update to 1.61.2:

When accessing the person directory on the webapp, it crashes (Eternal loading symbol).
On the browser used, any SORMAS page will not load anymore.
Clearing the cookies (sormas.bund.de) will resolve the problem, until the person directory is accessed again.
Trial and error have shown that the responsible cookie is "JSESSIONID".
Other SORMAS instances seem not to have the same problem and I am at loss how to resolve this.
The last version we used was 1.59, so we cannot pinpoint if this problem appeard in any version between 1.59 and 1.61.2

Changing the user role / region / district does not resolve the problem.

### Steps to Reproduce

1. Log into SORMAS
2. Click on "Persons" / "Personen"

### System Details

* SORMAS version: 1.61.2:
* Android version/Browser: Firefox / Edge / Safari
* Server URL: https://berlin-friedrichshain-kreuzberg.sormas.bund.de/

### Additional information

- Performance on persons directory is improved by #6170
- Further improvements currently under development by #6188

**Comment by MateStrysewske** [comment]
@ophcode Hey! This is probably exactly what we want to fix with #6188 in an upcoming minor release for 1.62. I'll put this issue here on hold for now because we need to see whether the changes in that issue will resolve the problems.

**Comment by ophcode** [comment]
Thank you Maté!

When will the hotfix be available / is there anything we can do to make the person directory usable until then?

**Comment by MateStrysewske** [comment]
@ophcode There's no concrete ETA right now, but hopefully at some point this week. Unfortunately I don't know whether there's a workaround - @StefanKock might provide a bit more insight here. In any case we would need to get more insight into which database operations are responsible for the performance problems (see https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/TROUBLESHOOTING.md -> Debugging Performance Problems).

**Comment by StefanKock** [comment]
Currently I suspect this ticket is a duplicate with already known flaws in person directory queries. If we get a long running query thats causing the issue we could check if it's addressed or new.

**Comment by markusmann-vg** [comment]
covered with:
- Performance on persons directory is improved by PersonFacade.count/getIndexList: Slow query #6170
- Further improvements currently under development by Avoid that cases with many contacts make the persons query conditions to grow exponentially [3] #6188
