### ISSUE TITLE
Flawed automatic and manually ordered calculation of case classification 

### ISSUE THREAD

**Issue by maxiheyner** [hzi-braunschweig/SORMAS-Project#6265]
### Bug Description
Cases with positive rapid tests and negative pcr test are calculated via button as class C - confirmed case and automatically as class E - confirmed case with unknown symptoms. 

### Steps to Reproduce

1. create a case with a positive rapid test
2. add a negative per test
3. check the case classification automatically C is calculated, after using the calculation button E is provided

### Expected Behavior
X- no case would be the expected result for both calculations for cases with positive rapid test and negative pcr test. 

### Screenshots

<img width="921" alt="image" src="https://user-images.githubusercontent.com/76884029/128019190-675f9841-fb0d-4331-9ad5-fd66fe50856b.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/76884029/128019309-a0c678ad-e9bd-482f-a87b-7d9c81a39b7b.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/76884029/128019361-a3021dc1-9614-4f2f-a2cd-e91c3be4e1ec.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/76884029/128019703-6ec7e18c-833f-49af-b496-124123ac1244.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/76884029/128019765-15fa78d8-7e79-479f-b169-e6d82e1cc81c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76884029/128019984-47df9b27-7b9f-4ecf-95b7-f26aab33bbac.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/76884029/128020072-1419de31-556d-45c9-bae5-cc07505db730.png">

### System Details

* Device: web
* SORMAS version: 1.62.1
* Android version/Browser: Chrome
* Server URL: test1401
* User Role: admin

**Comment by MateStrysewske** [comment]
For clarification and as far as I'm concerned, this is not a bug. The specification of the automatic classification of Covid-19 cases did not contain negative PCR tests. This is a new specification that will need to be added to the functionality.

**Comment by maxiheyner** [comment]
@MateStrysewske we decided for an internal workaround. thanks for your feedback, I'll close this issue.
