### ISSUE TITLE
Case Bulk Edit mode | Sharing to reporting tool of a case (marked with "don't share with reporting tool") will result in error 2

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6271]
### Bug Description

This is a follow-up issue to the previous bug #5750. This did not resolve the bug in 1.61.2. 

- Cases cannot be sent in bulk if at least one case has been marked as "Don't share with reporting tool'. 
- The marked case does not have to be selected in order for that to happen. 
- The error message also displays the wrong uuid. 
- The displayed uuid is from a deleted case.
- Deleted cases that have previously been marked will also contribute to the overall error.

### Steps to Reproduce

1. Mark at least one case as "Don't share with reporting tool'
2. Enter the bulk edit mode in the case directory
3. Select multiple cases (including and excluding the marked case)
4. Send to reporting tool
5. Check error message
6. Reset all cases to not be marked
7. chose one case, mark them as 'Don't send...'
8. Delete that case
9. Try sending other cases again via bulk action

### Expected Behavior

- Only the marked cases should not be able to be sent to the reporting tool.
- The correct uuid of the affected cases should be displayed. These would be the ones included in the selected cases.
- Error message should display all uuid's of all affected cases.
- Deleted cases should not be considered in the action

### Screenshots

<img width="870" alt="errorBulkReportingToolSend" src="https://user-images.githubusercontent.com/70317594/128038100-3d891b48-7c2c-4fad-ad5f-90ca79ff1a17.PNG">

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

### Additional Information

Since 1.62.1 is already released, this probably has to be fixed in a 1.62.x version

**Comment by DavidBaldsiefen** [comment]
This has already been fixed in #6152  two weeks ago. However, during that fix only the error message was reported as the problem, which is why it probably did not end up in the hotfix. The fix for #6152 should have fixed all of the issues mentioned above though. @MateStrysewske

**Comment by StefanKock** [comment]
As mentioned above, already fixed with 1.62.0 as a side effect.
