### ISSUE TITLE
Exclude cases marked as 'Don't share with reporting tool' from 'Only cases not yet shared/already shared/changed since last shared with reporting tool' filters

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6273]
### Feature Description

Case directory > Filters > Only cases not yet shared with reporting tool
### Problem Description

When filtering for cases not yet shared with the reporting tool, the select includes cases that were marked as 'Don't share with reporting tool'. When users now select all cases and try to send them, this inevitably runs into an error.

As a user, I would want to just filter for cases not yet shared to the reporting tool and bulk send them all at once without an error.
### Proposed Change

- Exclude cases marked as 'Don't send to the reporting tool' from the 'Only cases not yet shared with the reporting tool' filter.
- Exclude cases marked as 'Don't send to the reporting tool' from the 'Only cases already shared with the reporting tool' filter.
- Exclude cases marked as 'Don't send to the reporting tool' from the 'Only cases changed since last shared with the reporting tool' filter.

**Comment by JaquM** [comment]
Exclude them from filter "only cases changed since last shared with reporting tool" aswell

**Comment by kwa20** [comment]
@MateStrysewske @JaquM I've updated the description to include all other reporting tool filters because of consistency
