### ISSUE TITLE
Wrong case calculation with multiple PCR-tests

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6276]
### Bug Description

In 1.61 the new calculation of case classification was introduced. When having a confirmed case we do a second PCR-Test at the end of the isolation. They isolation only ends after a negative test.

The automatic calculation starts then to re-calculate the classification and changes the case from confirmed to probable.

The calculation should not run automatically and re-calculate without starting by the user (e.g. in our health office a positive rapid test is not a confirmed case until we get a positive PCR).

And the calculation cannot use only the last sample. It must include all samples for the case.

### Screenshots

![grafik](https://user-images.githubusercontent.com/74791118/128130417-9ad60b0a-949a-49c6-bd23-ad4ea7b87eee.png)

![grafik](https://user-images.githubusercontent.com/74791118/128130417-9ad60b0a-949a-49c6-bd23-ad4ea7b87eee.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by kwa20** [comment]
@Marko-ilmkreis I cannot reproduce this on either 1.61.2 or 1.62.1. Are there any other fields entered in your instance that could be relevant in your instance.

This is how it looks on my end:
<img width="542" alt="caseClassificationCalculation2" src="https://user-images.githubusercontent.com/70317594/128136154-24c27338-4134-463a-be0f-0683247fad3f.PNG">

**Comment by Marko-ilmkreis** [comment]
@kwa20 I cannot reproduce this on other cases. Maybe something is wrong with that case, but I dont see it.

What is the trigger to re-calculate the category for Sormas. I corrected the first name of a case in the person directory and the category was caculated:

![grafik](https://user-images.githubusercontent.com/74791118/128165456-eb23c795-aaca-4dc3-a688-e39f1cdf76fc.png)

The user must have it in hand if Sormas calculates or not.

**Comment by kwa20** [comment]
@Marko-ilmkreis There is a property in the server configurations called feature.automaticcaseclassification (default=t) which triggers the automatic calculation upon saving a case. Disabling it would result in the classification not automatically being calculated but the calculation could still be triggered by selecting the 'calculate' button.

**Comment by Marko-ilmkreis** [comment]
kwa20: Thanks. Then we can close this issue for the moment

**Comment by Marko-ilmkreis** [comment]
@kwa20 we are currently having a workshop regarding statistics/exports of Sormas with 200 persons. A lot of them complaint about the automatic calculation. Maybe its a good idea to set of to off by the support of netzlink?

**Comment by kwa20** [comment]
@Marko-ilmkreis Would be an option yes. Is the manual trigger also a problem? Additionally we could think about changing the default in the properties to false. @MateStrysewske What do you think?

**Comment by Marko-ilmkreis** [comment]
@kwa20 @MateStrysewske no, the manual trigger is very good and I think it will be used very often. The feature itself is very good. Thank you! But sormas should it not calculate automatically whenever you save the case. 

I talked with netzlink and they forwarded me to the normal support. They are considering to list the option to configure this feature in the available configurations (https://www.sormas-oegd.de/download/2976/) at ITZ Bund.

Sorry for disturbing you both with this.
