### ISSUE TITLE
Event identification source column is not sortable on directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6280]
### Bug Description

When trying to sort the event identification source column on the event directory, an error occurs.
### Steps to Reproduce

1. Open the event directory
2. Sort the event identification source column

### Expected Behavior

Column should sort alphabetically
### Screenshots

<img width="402" alt="evetnIdentificationSourceSort" src="https://user-images.githubusercontent.com/70317594/128155041-fc1301d6-28b5-40e3-8abb-2b43972142b7.PNG">

### System Details

* Device:
* SORMAS version: 1.62.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: surveillance supervisor, contact supervisor

**Comment by MateStrysewske** [comment]
@kwa20 Sorry, this was added to the wrong milestone. It's been fixed for 1.63.0, but not for 1.62.2.
