### ISSUE TITLE
Travel entry conversions to cases shows jurisdictional complications

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6283]
### Bug Description

When converting travel entries to cases, jurisdiction and place of stay contradictions arise. This seems to be due to place of stay or jurisdiction being applicable to facilities as well as points of entries.
### Steps to Reproduce

1. Convert a travel entry to a case (the travel entry should have a point of entry outside the jurisdiction)
2. Select Home or Facility as place of stay
3. Enter compulsory data and save

### Expected Behavior

When converting travel entries to cases, cases should be treated as being referred to a facility (which includes home). This way, place of stay fields for facilities and points of entries should not compete with one another.  
### Screenshots

<img width="353" alt="travelEntriesConvertError2" src="https://user-images.githubusercontent.com/70317594/128166151-7c219691-7a11-44a6-84c2-e37befa4a734.PNG">
<img width="355" alt="travelEntriesConvertError" src="https://user-images.githubusercontent.com/70317594/128166153-5e374c8a-61db-4328-8cc0-00e31821fa63.PNG">
<img width="349" alt="travelEntriesConvertError3" src="https://user-images.githubusercontent.com/70317594/128166155-0bc17151-f860-48f9-b5d7-62b7b0827405.PNG">

### System Details

* Device:
* SORMAS version: 1.62.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user, supervisors, officers

**Comment by DavidBaldsiefen** [comment]
Does this mean that the "Point of entry outside of jurisdiction" should be completely ignored when creating a new case, and that the "Responsible Jurisdiction" of the TravelEntry should soley be used to set the initial values of the case-create-form?

A Problem here is that if "Point of entry outside of jurisdiction" is checked, the available PoEs depend on those fields. However if I create a new case, I can only choose PoEs based on the responsible jurisdiction or placeofstay. Thus, it would need to be possible to adapt the "Point of entry outside of jurisdiction" fields to "place of stay outside of jurisdiction" in the case create form.


![image](https://user-images.githubusercontent.com/4655486/128676946-e10b799d-d8e3-4b8a-801c-9b587f7653fd.png)
![image](https://user-images.githubusercontent.com/4655486/128677123-ac716481-e8e5-495b-9415-a136deeaa560.png)

**Comment by kwa20** [comment]
@DavidBaldsiefen I think the difficulty here is that region and district do not have to match for facility/home and point of entry. For example, a person could enter the country at the airport in Bremen, be hospitalized in Hamburg but live in Berlin which is therefore the responsible jurisdiction.

We need to treat conversions to cases as if the case is currently still at the airport (usual process of creation would go through the case) or as if the case was referred to a facility.

Place of stay is point of entry
<img width="390" alt="refterToFacility1" src="https://user-images.githubusercontent.com/70317594/128679226-8f6344d7-914a-432c-b4cd-28945b29923c.PNG">
Refer to facility
<img width="398" alt="referToFacility" src="https://user-images.githubusercontent.com/70317594/128679228-bd4782ec-fb1a-487e-9718-97745d6e4547.PNG">
Pop-up
<img width="456" alt="refterToFacility2" src="https://user-images.githubusercontent.com/70317594/128679225-15ec00a9-9ecf-4e8a-8ec2-6942891ffa97.PNG">
Result on case information
<img width="410" alt="refterToFacility3" src="https://user-images.githubusercontent.com/70317594/128679224-155ee882-ca04-449e-83fa-220801f8d61e.PNG">

**Comment by DavidBaldsiefen** [comment]
It might be possible to circumvent this problem by automatically setting the PoE for cases created from TravelEntries, and making that field un-editable. In that case it needs to be assured that validations correctly handle this. Otherwise I agree that another checkbox would be needed: "Location of PoE differs from PlaceOfStay and responsible Jurisdiction"

**Comment by MateStrysewske** [comment]
* Add a new checkbox to the case creation form: "Point of entry jurisdiction differs from responsible/place of stay jurisdiction"
* Add two new custom fields (i.e. there's no DTO or entity entry for them): "Point of entry region" and "Point of entry district"; same logic as in the travel entry form, i.e. only show them when the checkbox is checked and add all the logic that is required to fill the point of entry dropdown based on the selected values
* When creating a case from a travel entry, don't take over the point of entry jurisdiction to the place of stay fields of the case; disable the point of entry fields (including the new custom fields); fill the point of entry jurisdiction fields with the point of entry jurisdiction of the travel entry; make sure that the fields are properly populated when they have been filled in for the travel entry

**Comment by kwa20** [comment]
@MateStrysewske I noticed this issue coming up after the merge:

When selecting "Place of stay of this case differs from its responsible jurisdiction", the following error occurs

<img width="670" alt="Screen Shot 2021-10-01 at 4 02 49 PM" src="https://user-images.githubusercontent.com/70317594/135633238-fed955e4-2ac2-4f8a-95bd-1e1f14fed9ee.png">

<img width="698" alt="Screen Shot 2021-10-01 at 3 58 07 PM" src="https://user-images.githubusercontent.com/70317594/135633070-5faf73b1-bba8-4318-be0c-1af1d81c3a67.png">

point of entry should not be reset when selecting this checkbox

**Comment by roxanamlendea** [comment]
I wanted to report this too. This error also happened to me.
