### ISSUE TITLE
Deleted cases do not get unlinked from travel entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6284]
### Bug Description

When resulting cases of travel entries get deleted, they do not become unlinked from existing travel entries.
### Steps to Reproduce

1. Create or open a travel entry and convert them to a case.
2. Delete the created resulting case.
3. Check the link to that case in the travel entry

### Expected Behavior

When deleting resulting cases, travel entries should get unlinked from these cases. 
### Screenshots

<img width="619" alt="travelEntriesDeleteLink" src="https://user-images.githubusercontent.com/70317594/128167279-d574d95f-05de-44f6-abe2-d08574ef4f1e.PNG">
<img width="603" alt="travelEntriesDeleteLink2" src="https://user-images.githubusercontent.com/70317594/128167281-94e0cef6-8cd8-4ddc-8373-8f9153c9d9ec.PNG">

### System Details

* Device:
* SORMAS version: 1.62.1
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user, supervisors, officers

**Comment by bernardsilenou** [comment]
@kwa20  @MateStrysewske 
I think we should hard delete the case_id on the travel entries table when
