### ISSUE TITLE
Adjust the COVID case classification calculation

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6286]
### Feature Description

CORONAVIRUS > automatic case classification calculation
### Problem Description

- classifications 'confirmed - no symptoms' and 'confirmed - unknown symptoms' do not get properly calculated either automatically nor via manual trigger.

    - if at least one symptom is set to either 'no' or 'unknown', the case classification is set to 'not yet classified'.

### Proposed Change

- If a positive test relevant for the Covid confirmation is given AND at least one symptom is set to `NO` AND the Covid confirmation relevant symptoms are anything but `YES`, set the case classification to **CONFIRMED_NO_SYMPTOMS**

- If a positive test relevant for the Covid confirmation is given AND at least one symptom is set to `UNKNOWN` OR null AND the Covid confirmation relevant symptoms are anything but `YES` OR `NO`, set the case classification to **CONFIRMED_UNKNOWN_SYMPTOMS**
### Additional Information

cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4770

**Comment by StefanKock** [comment]
was merged two days ago
