### ISSUE TITLE
Sorting of last contact in follow-up-visits not working properly

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6290]
### Bug Description

The sorting of the last contact date in follow-up-visits is not working properly. The date is not sorted by the date.

In the screenshot the sorting ist: 23.07.2021, **30.07.2021**, 24.07.2021, 29.07.2021, 30.07.2021, 01.08.2021, **29.07.2021** and so on.

![image](https://user-images.githubusercontent.com/74791118/128315222-46ac419e-fe73-402a-8bee-b0c8ea61d565.png)

### Steps to Reproduce

1. Go to follow up visits of contacts
2. sort the column of last contact by clicking on the header2.

### Expected Behavior

The date should sort properly

### Additional information
Was caused by #2942

**Comment by kwa20** [comment]
It seems as if clicking the 'date of last contact' header for sorting has the same effect as sorting for 'date of report'

<img width="116" alt="lastContactDate" src="https://user-images.githubusercontent.com/70317594/128340586-0e07e44d-d27b-40a7-9ae4-aeaf58b1de5e.PNG">

**Comment by Marko-ilmkreis** [comment]
@kwa20 I can confim this.
