### ISSUE TITLE
Community Officers have missing placeOfStay region and district fields

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6293]
### Bug Description

When community officers try to create cases with differing place of stay and jurisdiction, the region and district fields are missing.
### Steps to Reproduce

1. Log in as a community officer
2. Create a new case
3. Check the box "Place of stay of this case differs from its responsible jurisdiction"
4. Check subsequent place of stay fields

### Expected Behavior

Users should be able to enter region and district.
### Screenshots

<img width="368" alt="placOfStayRegionDistrictMissing" src="https://user-images.githubusercontent.com/70317594/128337709-3126560b-5193-4449-b801-d5d7006a6a63.PNG">
<img width="357" alt="placOfStayRegionDistrictMissing2" src="https://user-images.githubusercontent.com/70317594/128337712-a55eae60-e278-4b8c-9ef7-26cca97e7129.PNG">

### System Details

* Device:
* SORMAS version: 1.62.1
* Android version/Browser: firefox
* Server URL:test1401.sormas-oegd.de
* User Role: Community Officer

**Comment by DavidBaldsiefen** [comment]
Should the community officer be able to set the responsible region+district, or just community? I suppose the placeofstay-fields should all be editable, but I am not so sure about the region fields

**Comment by kwa20** [comment]
@DavidBaldsiefen yes please, all location fields, independent of whether it is responsible region/district or placeOfStay region/district should be editable. However, if the user has access restrictions, the responsible region/distrct fields are usually prefilled with the jurisdiction of the user. It would work the same way as for supervisors and officer roles. For community officers, responsible region, district and community would be prefilled.
