### ISSUE TITLE
Sormas API | Persons | Get Persons by uuid returns Postal Code truncated

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#6295]
### Steps to Reproduce
1. Create a Person on the UI
2. Edit that person so that there are all fields completed (phone, address, extra persons info) 
3. Use Postman for a Get Persons by UUID ( example: https://test-performance.sormas.netzlink.com/sormas-rest/persons/X5JGVD-MPHBUV-IIXFPY-KKSISI24 ) 
4. Check the response

### Expected Behavior
Postal Code gets truncated to the first 3 numbers.

### Expected Behavior
The fields should not get truncated

### System Details

* Device: Windows
* SORMAS version:chrome
* Android version/Browser: 
* Server URL: test-performance.sormas.netzlink
* User Role: NatUser

### Additional Information

[response.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/6938846/response.txt)

**Comment by MateStrysewske** [comment]
Just a remark that this is expected if the person is pseudonymized; the postal code should only be displayed completely if the user has also access to e.g. the first and last name

**Comment by leventegal-she** [comment]
In the response.txt linked to additional info is stated that the person is pseudonymized `"pseudonymized": true,` and also farsName and lasName fields are empty so it's ok that the postal code is truncated.

If the person should not be pseudonymized then more info is needed: 
- role, region and district of the user used in postman
- jurisdiction of the case/contact/event participant the person is linked to

**Comment by vidi42** [comment]
Works as expected
