### ISSUE TITLE
Change the default of automatic case classification to false

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6300]
### Feature Description

sormas.properties > feature.automaticcaseclassification
### Problem Description

Some users expressed rejection of the newly introduced automatic case classification feature. Rather than introducing this feature initially, we should maybe give the users the option to decide whether to add this automatic calculation or not.
### Proposed Change

Change the default of the feature.automaticcaseclassification to FALSE

**Comment by MateStrysewske** [comment]
@kwa20 The automatic case classification feature is not new, it's been in the system for a long time, but it was not functional on German servers because there were no rules for Covid-19. I personally disagree with setting it to FALSE by default because it's an essential feature that is extremely important for countries that use SORMAS for epidemiological surveillance.

**Comment by kwa20** [comment]
@MateStrysewske Since I don't have a good overview of how many users are against vs in favour of the automatic calculation, I've asked the support team to provide us with further feedback from the large user exchange meetings. I think if we leave the default at TRUE we just might have to make sure that the properties are also always available in the docker version. This will then be down by the provider I suppose.

**Comment by MateStrysewske** [comment]
@kwa20 Yes, that would be my suggestion. Since the property has been added a long time ago, it should ideally already be part of the Docker version anyway.

**Comment by kwa20** [comment]
@ophcode the reference definition is planned for implementation here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5594. This might resolve a lot of the confusion.

I think for this issue, we will make the feature toggle available through the properties in the Sormas docker version running on productive systems but leave the default to true. Users would then still be able to calculate the classification manually via the associated button if turned off.

Closing this issue because the default will remain TRUE.
