### ISSUE TITLE
Error when selecting facility during creation of new case

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#6303]
Tested in version 1.61.2

Summary:
When trying to create a new case it can happen that the user is unable to select a facility.

Steps to reproduce:
- Open the case directory
- Click on "New Case"
- Select Responsible Region and District (Doesn't matter which ones)
- Select "Facility" in Place of Stay
- Medical Facility and Hospital are preselected by the system
- Click on Facility --> You are able select a facility or "Other facility"
- Select any other facility type than "Hospital"
- Click on Facility --> The dropdown is empty

Workaround:
In order to make the dropdown contain any values you need to select a different region first and then the original region again. After that you are able to select a facility again. Every time you change the facility type you need to do the workaround again to be able to select a facility.

Screenshots:
When loading the overlay for the first time:

<img width="584" alt="2021-08-06_11h48_01" src="https://user-images.githubusercontent.com/6122778/128556427-55d3cb76-c5fd-49df-8611-83372dd65ecb.png">

After selecting a different facility type:

<img width="580" alt="2021-08-06_11h48_33" src="https://user-images.githubusercontent.com/6122778/128556452-3f7e9963-c0a0-405c-80f3-ce6d724c45f2.png">

After selecting another region and then the old region again:

<img width="585" alt="2021-08-06_11h48_48" src="https://user-images.githubusercontent.com/6122778/128556486-6c18171c-95b3-4ff1-b42a-fef86e637c0f.png">

**Comment by MateStrysewske** [comment]
@Jan-Boehme Hey! Could you please use our issue templates in the future? Thanks!
