### ISSUE TITLE
Community Officer can sometimes not create new travel entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6304]
### Bug Description

When there is no travel entry entity in the jurisdiction of a community officer, they cannot create new travel entries even if the initial import has already been performed.
### Steps to Reproduce

1. Make sure that no travel entry is in the jurisdiction of a community officer and the initial import has already been performed
2. Log in as a community officer and open the travel entry directory and check the creation button
3. Log in as an admin/national user and move one travel entry to the jurisdiction of the community officer
4. Log in as the community officer again and check for the creation button

### Expected Behavior

Community Officers should see the 'New Travel Entry' button even when their directory is empty
### Screenshots

<img width="864" alt="newTravelEntry" src="https://user-images.githubusercontent.com/70317594/128629501-9e830e72-137d-4f71-b4c9-8cf4782460d0.PNG">
<img width="869" alt="newTravelEntry2" src="https://user-images.githubusercontent.com/70317594/128629502-e05217b1-357f-451a-86be-33720a0dc065.PNG">

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: Community Officer

**Comment by MateStrysewske** [comment]
@AndyBakcsy-she Probably not, seems like a different issue

**Comment by AndyBakcsy-she** [comment]
I've tested also with Admin and NatUser
