### ISSUE TITLE
Import from DEA fails when creating new persons after duplicate detection

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6307]
@kwa20 @MateStrysewske 
### Bug Description

I tried to import an csv-file downloaded from DEA into the travel entries on https://test-de1.sormas.netzlink.com/, but it fails with the error that a first-name has to be entered.

This is a follow-up to #6031 

This zip-file contains the import-file and the error-log:

[DEA.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6952438/DEA.zip)
(unfortunately github does not alllow upload of csv).

### Screenshots

![image](https://user-images.githubusercontent.com/74791118/128666157-291cc8f5-2bc9-4091-8ed7-abddd45907ba.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis With the same file I actually get an error saying the dob date format is invalid even though the format would be the expected one considering the user language. Not sure why the errors diverge.

**Comment by Marko-ilmkreis** [comment]
@kwa20 thats strange.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis That file does not have valid CSV delimiters; I'm pretty sure that either "," or ";" is specified in the server properties on the test server. Please replace the tabs with a supported delimiter and check whether it works afterwards.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Thats right, but that is the format how it was downloaded directly from DEA. The idea was, that the end-user must not convert the file and can directly use it for the import.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis That won't be possible anyway because SORMAS requires at least information about the point of entry; unless the system is used by a user that has a point of entry set, they need to edit the file in any case.

There's currently no logic in place that allows users to select the delimiter used during the import.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Then I understood the #6031 wrong :-/. The normal is user is not able to convert the delimiter from tab to ; 

Then the #6031 is not a duplicate of #4019 and it must re-opened.

**Comment by kwa20** [comment]
@MateStrysewske I've tried adding the relevant fields for disease, point of entry etc. but there still seem to be errors connected to the person data. I can't however pinpoint them yet.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis There's an issue about letting users decide which delimiter they want to use: #5459 
@kwa20 Can you attach your updated file so I can have a look at it?

**Comment by kwa20** [comment]
@MateStrysewske Here some files. The second file seems to work while the first one results in a critical error.
[travelEntries_import.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/6953166/travelEntries_import.zip)

<img width="449" alt="criticalError" src="https://user-images.githubusercontent.com/70317594/128683035-6a917fdd-743c-425e-9cef-ccd705ca2b00.PNG">

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske The problem ist, that the user also do not know the point of entry as the traveller is never requested to enter them. The only solution would be to enter a fake-point of entry and to use it for all travellers

![image](https://user-images.githubusercontent.com/74791118/128686360-c2147c33-1bbc-4894-8784-5f7bee80f5d4.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis @MateStrysewske A proposed solution is specified in the mapping refinement here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6217. This might, however, need some further development.

**Comment by MateStrysewske** [comment]
@kwa20 I can import both files successfully as long as I set my user language to German (I believe because we've recently changed the behaviour here to parse dates according to the usual date format of the user language). I don't receive a critical error...

**Comment by kwa20** [comment]
@MateStrysewske Does the person duplicate detection get triggered and if so, are you selecting an existing person? If I do, the import is successful but if I create a new person, a critical error appears.

**Comment by MateStrysewske** [comment]
@kwa20 Ah, okay, thanks! I'll try to do that.

**Comment by MateStrysewske** [comment]
@kwa20 Found and fixed the bug :)
