### ISSUE TITLE
Race condition populating CustomizableEnum caches

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Project#6327]
### Bug Description

In `CustomizableEnumFacadeEjb` the values are cached in several static `HashMap`s.
They are cleared and populated in `CustomizableEnumFacadeEjb::loadData`.
The pool of `CustomizableEnumFacade`s is adjusted dynamically, especially when under load.
Spawning new instances may result in a 
`RuntimeException: Invalid enum value [...] for customizable enum type DISEASE_VARIANT`.

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

Please get rid of current violation of Java naming convention for variables when fixing this ticket.

**Comment by MateStrysewske** [comment]
@HolgerReiseVSys Can you more specifically outline a situation in which this could happen?

**Comment by HolgerReiseVSys** [comment]
@ MateStrysewske Just when the container decides that a new instance of the bean is needed while another instance is being used.
This should typically happen when the server is under load, as it was during a SurvNet import where the exception appeared.

**Comment by MartinWahnschaffe** [comment]
- [ ] cache should either not be static or thread-safe
- [ ] make sure resetting the cache can be done for all instances

**Comment by HolgerReiseVSys** [comment]
I could reproduce this with an asynchronous SurvNet import:
`RuntimeException: Enum value B.1.1.7_-_501Y.V1 for customizable enum type DISEASE_VARIANT is not unique`
at "de.symeda.sormas.backend.customizableenum.CustomizableEnumFacadeEjb.loadData(CustomizableEnumFacadeEjb.java:221)"
