### ISSUE TITLE
Using of keyboard-shortcuts in Sormas

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6338]
### Feature Description

As some users very often navigate by the keyboard it might be nice of Sormas grabs some keyboard-actions, maybe with Angular?

I have in mind these shortcuts, used in other applications:

Ctrl + S = Save the current data set (the user has currently scroll down and click save even if only one field on the top was edited.

List to be continued until the work on this issue starts.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske: As an alternative, is a floating save-button or a second save-button at the top possible?

**Comment by kwa20** [comment]
@Marko-ilmkreis https://github.com/hzi-braunschweig/SORMAS-Project/issues/3377 discussed your suggestion at some point but it was eventually decided against back than. I like the shortcut option very much though. We also didn't consider a configuration for this feature back then which might be an alternative.
From what I've seen of the UI so far, it also seems that the save/discard buttons will move after the implementation to the top of the form. Nothing set in stone as far as I can tell though.

**Comment by Marko-ilmkreis** [comment]
@kwa20 then I close this issue and hoping of a fast release auf Angular ;-)
