### ISSUE TITLE
[Angular] Header for event participant profile [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6343]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We must refactor the header for event participant profile : breadcrumb + hidden tabs + go back to participants btn
- We must adhere to the design changes made in the header

### Possible Alternatives

- N/A

### Additional Information

-N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
