### ISSUE TITLE
[Angular] Menu animation just like the submenu [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6344]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- The main menu navigation should behave as the sub-menus do
- We need to check if this is easily doable (if it's more complex, we can descope this task)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
