### ISSUE TITLE
[Angular] Dynamic form: Consistent spacing [1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6349]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to make sure that the spacing is consistent across the board
- We need to make sure we adhere to the latest design changes
- Please consult: 
![image](https://user-images.githubusercontent.com/77488672/129186917-5d0cd2e7-8cba-469d-8175-9ed856e37ba9.png)
- @cristinacoza please add a list where we might encounter this problem (where we have items on the right hand side of the container)
- List: 
[Dynamic form: Consistent spacing.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6975939/Dynamic.form.Consistent.spacing.pdf)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done, everything looks good
