### ISSUE TITLE
[Angular] User profile. Edit. (change from modal to dynamic form) [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6352]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/L01r5ld
- Please consult the current Sormas legacy implementation for the exact behaviours
- Reference: [User dependencies.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/6974996/User.dependencies.pdf)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
