### ISSUE TITLE
[Angular] Empty state / No data retrieved [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6354]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to make sure that we cover all the cases of "no data returned" or "call failed" and display a message that informs the user that no data has been retrieved
- Message to be used: "No {DATA TYPES} has/have been retrieved. Please try reloading the page." (this message should be displayed instead of the table) - only if there is an error
- - Message to be used: "There are no {DATA TYPES} to be displayed." (this message should be displayed instead of the table) - when no data is retrieved
- @cristinacoza please provide a mockup for this message
- Design here: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/9A97955E-B216-48FC-B10B-C1AD497F59B3
- We should at least cover all lists (tables) - across the entire project

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
