### ISSUE TITLE
Case line listing creates cases with missing region and district

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6360]
### Bug Description

When creating cases with the line listing, region and district are empty, yet compulsory.

Implementation of https://github.com/hzi-braunschweig/SORMAS-Project/issues/5873 might solve this problem
### Steps to Reproduce

1. Create a case via line listing
2. Check the case information upon creation

### Expected Behavior

region and district should either be filled or the place of stay cannot differ from the responsible jurisdiction when creating cases via line listing. Implementation of #5873 as a fix would be favourable
### Screenshots

<img width="777" alt="caseLineListResult2" src="https://user-images.githubusercontent.com/70317594/129225457-a2755ea1-f8e9-4c67-b1df-4c2e282f8b1d.PNG">
<img width="392" alt="caseLineListResult" src="https://user-images.githubusercontent.com/70317594/129225460-974a4853-ea9a-4b7f-8f63-180bcb66451e.PNG">

### System Details

* Device:
* SORMAS version: 1.62.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Can and should be fixed by turning the "community" field into "responsible community"
