### ISSUE TITLE
Optimize performance of saving a new person [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#6362]
### Feature Description
When a person is saved the system automatically updates related entities like cases and contacts.

### Problem Description
This is not necessary when the person is new anyway

### Proposed Change

- [ ] onPersonChanged looks for cases, contacts, event participants and then cases again, which does not make sense when there was no existing person before
- [ ] this happens again when updating the caseAge of associated cases - when existingPerson is null, this is unnecessary

Related to #5986

### Additional info
Pls. check, if we need this performance improvement as well for the immunization and travel entries part, we should create a follow-up tocket.

Pls. check and add tests together with @rdutu-vg and @StefanKock so, that we can have some kpi or numbers for improvements

**Comment by DavidBaldsiefen** [comment]
- I do not see the same issue with Immunizations or TravelEntries (yet)
- Performance can be tested and compared by looking at the "push person" task of the e2e-performance tests. #6534 made sure those are working so we have "before" numbers

**Comment by DavidBaldsiefen** [comment]
Comparison of Timings (ms) for pusing a person via rest before and after this change:

| Push Person | Samples | Avg | Min | Median | Max  |
|-------------|---------|-----|-----|--------|------|
| Before 1    | 17      | 261 | 70  | 75     | 3169 |
| Before 2    | 9       | 557 | 77  | 114    | 3981 |
| After 1     | 12      | 130 | 66  | 75     | 509  |
| After 2     | 10      | 150 | 72  | 113    | 584  |


Sadly the sample size is quite small, but this seems like there are no significant improvements here. Even though the Avg. was clearly smaller after the changes, it seems like that could be mainly attributed to the significantly reduced Max., which in turn can be considered an outlier and should thus probably be ignored. The Median stayed nearly the same throughout.
