### ISSUE TITLE
Date-range of follow-up-visits gets lost after opening contact/case

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6371]
### Bug Description

If  a date range is selected in the follow-up-visit view, the selection is reset to default after opening an contact and coming back to the follow-up-visits

![image](https://user-images.githubusercontent.com/74791118/129338202-c3d9475a-2e57-4f9a-a690-c3e4cc558ceb.png)

@ChristopherRiedel @Jan-Boehme

**Comment by roxanamlendea** [comment]
The bug is fixed, but I found out that this happens. I'm not sure if it's related to this bug or not. Basically if I open a contact and then I go back on the Contact directory, the "show more filters" is activated. I could only reproduce it when a date range of follow-up visits is selected.
![contact directory - follow up visits table](https://user-images.githubusercontent.com/89522688/134118655-c032cb39-9010-4774-b150-dd5b15763b9c.gif)

**Comment by MateStrysewske** [comment]
@roxanamlendea That means you haven't selected the date in the fourth row manually, but it was filled in automatically?

**Comment by roxanamlendea** [comment]
> @roxanamlendea That means you haven't selected the date in the fourth row manually, but it was filled in automatically?

Yes. These dates are set automatically when I click on "Follow up visits"

**Comment by MateStrysewske** [comment]
@roxanamlendea No, I don't mean those, I mean the date in the fourth line of the filters; did you set that date manually or was it set automatically when you re-entered the contacts directory?

**Comment by roxanamlendea** [comment]
You mean this, right? I didn't set in manually in the filters. I think that was set automatically up there when I selected the date range.
![image](https://user-images.githubusercontent.com/89522688/134140445-3477ff8d-0d82-42e7-9279-2759003563eb.png)

**Comment by MateStrysewske** [comment]
Okay, that seems like something we need to investigate then.

**Comment by MateStrysewske** [comment]
@sergiupacurariu Can you have another look at it and try to reproduce the problem?

**Comment by sergiupacurariu** [comment]
@MateStrysewske I will check it.

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT
