### ISSUE TITLE
[Angular] Contacts - "Contact" tab [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6374]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to implement the "Contact" tab form
- For this task we can ignore the buttons from the top right (Open / Change / Remove case). These will be handled in a another task.
- We need to consult the Sormas implementation to make sure we cover all of the form functionalities
- The quarantine section was already implemented on the case (it can be reused to some extent)
- We can ignore the "Under-follow up" section for now
- We can ignore the right hand side section (Cards) for now

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - there are some styling issues that will be resolved in a future task dedicated to dinamic form and table component styles update
