### ISSUE TITLE
[Angular] Contact - "Contact" tab - "Case details" buttons and modal [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6375]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/9PmnmJ0
- Modal Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/v81RK4d
- Open case - just redirect
- Chage case - modal
- Delete - we add the request (hardcoded to return 200 OK) (API constant @this_is_hardcoded)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
The design is updatet

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
