### ISSUE TITLE
[Angular][Backend] Delete end-points [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6379]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- The standard for the call should  be on "POST" -> "entity/delete"  (and in the body of the request we will have an array of ID's)
- The endpoint should be implemented for:
- The response (200) will be returned (i.e json -> Message, 200 OK), not an empty response

1. cases
2. tasks
3. events
4. samples
5. contacts
6. persons
7. users

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by marius2301** [comment]
I made a sample for cases to discuss it with mate before doing for all the other entities. I also need to discuss with the frontend team after. In the sample for delete cases - the delete endpoint accepts a list of uuids and returns a list of uuids of the cases that have been deleted (the cases that were not deleted for different reasons will not be in the return list).

**Comment by laurentiustanvitagroup** [comment]
The implementation was done only for the case. All other entities will be handled in a separate task.
Note: The response will return a list of deleted entities ID.
