### ISSUE TITLE
[Angular] Configuration base line structure [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6381]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Add the settings icon in the top menu (@cristinacoza, add the settings icon: active / inactive)
 Settings icon states: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/v8aP3w4
- Create the Configuration module
- Create all components for the Configuration tabs (empty)
- Create the routing for this module
- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ELR10g2 (just the tabs)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good
