### ISSUE TITLE
[Angular] Configuration - Communities [5] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6386]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- This task refers to the entire page (including the filter)
- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DPnRAWj
- obs: By default it shows all the communities from the country (Germany)
- obs: When you select a country, region and district  it will update with the new data and display the count for the items returned
- We will ignore the right hand side buttons (Add new countries, export...)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
