### ISSUE TITLE
[Angular][Backend] Configuration endpoints [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6387]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need  endpoints similar to what was done for countries / regions / district / communities
- The new end points should be consistent with the previously built ones
- In this task we should create the endpoints for

1. Continents
2. Sub-continents
3. Facilities
4. Points of entries
Note: outbreaks a new task has been created (@laurentiustanvitagroup)
  
### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by marius2301** [comment]
I made the endpoints for continents, subcontinents, facilities and points of entry. I would suggest to create a separate ticket for outbreaks - it seems to be a bit different.
