### ISSUE TITLE
Place of stay is set when selected and deselected during case creation

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6392]
### Bug Description

Leaving the optional place of stay empty results in a selected 'Home' value when creating point of entry cases.
### Steps to Reproduce

1. Create a case with origin point of entry
2. Leave the place of stay empty
3. Check the subsequently created case

### Expected Behavior

The entry made in the creation form should correctly be adopted in the created entity
### Screenshots

<img width="385" alt="pointOfEntryCaseBug" src="https://user-images.githubusercontent.com/70317594/129384026-c1224b96-1b97-4a95-942b-f802672f06dc.PNG">
<img width="391" alt="pointOfEntryCaseBug2" src="https://user-images.githubusercontent.com/70317594/129384033-c4590241-d163-484e-a0ef-9ebb221207e9.PNG">

### System Details

* Device:
* SORMAS version: 1.62.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 I can't reproduce this on 1.63.0 - can you check whether you are able to, please?

**Comment by kwa20** [comment]
@MateStrysewske I can still reproduce it if I initially select Home and then deselect it again before saving.
