### ISSUE TITLE
Continents, subcontinents and points of entry are missing in the data dictionary

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6397]
### Bug Description

There is no table in the data dictionary for points of entries.
### Steps to Reproduce

1. Download the data dictionary from Sormas
2. Check for a table covering points of entries

### Expected Behavior

All data should be covered by the data dictionary.
### System Details

* Device:
* SORMAS version: 1.62.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Just noticed that continents and subcontinents have also not been added to the data dictionary yet.
