### ISSUE TITLE
Semantics of existing case attributes changed in import-/export files

### ISSUE THREAD

**Issue by ClaudeMarksteinerCSI** [hzi-braunschweig/SORMAS-Project#6398]
### Bug Description
With the implementation of Issue #3254, the semantics of the existing case attributes _region, district_, and _community_ were changed (previously, the attributes denoted the responsible areas; now, the attributes denote the areas in which the person stayes, and the responsible areas now have the designation responsibleXXX). This leads to the fact that all 3rd party systems receive / fill the wrong data when exporting / importing these attributes.

### Steps to Reproduce
1. Export Case Date with old SORMAS version
2. Import the exportet Data with new SORMAS version

### Expected Behavior
The imported data should be filled into the same attributes as the exported data

### System Details
* Device: Web Client
* SORMAS version: **1.61.1**
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
Short term solution: The fields of all the import / export-files must have the original semantics back.

This means: In the first line (for simple export) / the second line (for all the other exports) of every import / export-file, the attributes must have designations according to the following table.

Attribute    | Import / Export Designation 
------------ | -------------
responsibleRegion   | region
responsibleDistrict   | district
responsibleCommunity   | community
region   | stayRegion
district   | stayDistrict
community   | stayCommunity

**Comment by MateStrysewske** [comment]
Just a note for clarification: The semantics did not change. The region, district, community and facility fields always were supposed to indicate the place of stay. Prior to the invention of the responsibleRegion, responsibleDistrict and responsibleCommunity fields, there was _no_ way to properly to indicate the responsible jurisdiction.

**Comment by bernardsilenou** [comment]
This issue has the same root cause as https://github.com/hzi-braunschweig/SORMAS-Project/issues/6249
Maybe we can address both with the same nomenclature

**Comment by ClaudeMarksteinerCSI** [comment]
> Just a note for clarification: The semantics did not change. The region, district, community and facility fields always were supposed to indicate the place of stay. Prior to the invention of the responsibleRegion, responsibleDistrict and responsibleCommunity fields, there was _no_ way to properly to indicate the responsible jurisdiction.

Well, at least the UI labels ('Responsible district' / 'Zuständiges Bundesland' / 'Zuständiger Kanton') suggested that it was the place of jurisdiction.

**Comment by Candice-Louw** [comment]
31.08.2021 CH Weekly - requested to be removed from sprint. Surrounding systems in CH will be adjusted.

Request for API documentation on updates to be documented (diffs) and communicated more clearly by system architects in future releases.
