### ISSUE TITLE
Pre-Conditions for entering travel entries

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6399]
As the release of 1.62.2 is coming soon, I started to write a small hand-out for the colleagues about the new travel entries.

I discovered that on test1401 the button "New Travel Enrtry" is available:
![image](https://user-images.githubusercontent.com/74791118/129512524-1caf6d5a-ebe7-4916-9630-f29d4c9e001b.png)

On test1402 it is not:
![image](https://user-images.githubusercontent.com/74791118/129512476-9b244449-b816-4ed7-9cef-d3ce990adb57.png)

At least one point of entry is availabe in 1402. The users having the same rights on both instances.

What are the pre-conditions to show the button in the health-offices?

**Comment by Marko-ilmkreis** [comment]
@kwa20 @bernardsilenou : Do you have any idea?

**Comment by kwa20** [comment]
@Marko-ilmkreis For this travel entry pre-version, the creation button will only appear when the initial import has been performed. You can find more on this in the guide deposited in the import pop-up. If the structure of subsequent imports changes, the deaContent will adjust the additional fields too

**Comment by Marko-ilmkreis** [comment]
@kwa20 I see, It was not very clear, that in import is mandatory for that.

One point to the Travel Entry Import Guide: There is written: SORMAS can read .csv files exported from DEA. Thats not the full truth. The files from DEA are coming with a tab as a separator while Sormas can only use ";" for now. So every file has to be edited by hand or through excel.
