### ISSUE TITLE
At the entry-form of travel entries it is not clear which field belongs to which area/country

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6400]
### Bug Description

While manual entry of entries should not be the rule. However, there will always be cases where the import fails, the connection to DEA is not yet fully implemented or does not make sense for other reasons.

Therefore, the entry form must be logically structured. At present, however, the fields are only listed one after the other without the user being able to clearly see which "risk class" field belongs to which previous field. This should be remedied as soon as possible and all input fields should be grouped accordingly.

![image](https://user-images.githubusercontent.com/74791118/129514725-18a1647e-b888-4bad-8176-93e861ada0c2.png)

**Comment by kwa20** [comment]
This is not actually a bug for the current implementation. The fields you see on this instance were just an example of what could be generated with the deaContent which is stored as JSON in a single database column. All unknown columns in the import could therefore generate several additional fields.

**Comment by MateStrysewske** [comment]
This will be done as soon as we have implemented the refactoring of the travel entries.
