### ISSUE TITLE
Generated documents result in an error when specific HTML characters are used

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6407]
### Bug Description

We are using this list for our cases:

[AA_Checkliste und Entlasszettel SORMAS (Stand 07.04.2021).docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6991087/AA_Checkliste.und.Entlasszettel.SORMAS.Stand.07.04.2021.docx)

It works very good, but when the vaccine Johnson&Johnson is selected in the case, it results in an error in word:

![image](https://user-images.githubusercontent.com/74791118/129540069-9863ff68-d0b1-4946-a4ac-8add7b18e34f.png)

![image](https://user-images.githubusercontent.com/74791118/129540119-c119ebf4-76c4-484e-8e4a-f1a3154a46dc.png)

Maybe the '&' causes the error?

### Steps to Reproduce

1. open a case
2. set the vaccine to Johnson & Johnson
2. the error occurs

### Expected Behavior

It should work with all vaccines.

### System Details

* Server URL: own instance and https://test1401.sormas-oegd.de/

### Additional Information

@syntakker

**Comment by kwa20** [comment]
Further findings:
- The Johnson & Johnson value can be generated when the user language is set to English but not if set to German
- Combination values also produce a parsing error
<img width="203" alt="documentGenerationParsingError2" src="https://user-images.githubusercontent.com/70317594/129545025-aec42fab-c303-4bc3-a73d-65faa92b61f6.PNG">
<img width="235" alt="documentGenerationParsingError" src="https://user-images.githubusercontent.com/70317594/129545049-51651af4-8b6d-473c-94cb-224da161735e.PNG">
- These values fail in both languages
