### ISSUE TITLE
Person contact details and home address don't get validated upon import

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6422]
### Bug Description

Person contact details don't get validated upon import and cannot be changed successfully afterwards.

The error message mentioning contact person contact details also seems to be the wrong reference here because these usually belong to facilities.
### Steps to Reproduce

1. Import persons (e.g. easily via event participants) with invalid contact person details
2. Try making changes or even adjust the contact details accordingly 

### Expected Behavior

Person contact details should get validated upon import and possible to be fixed via the UI.

It should also be possible to fix existing entries.
### Screenshots

<img width="326" alt="contactPersonError" src="https://user-images.githubusercontent.com/70317594/129690963-6ac2ee7c-fe57-4d1f-a6c6-1cdbfa96c90b.PNG">
<img width="453" alt="contactPersonError2" src="https://user-images.githubusercontent.com/70317594/129690957-48c5ae11-9af0-4446-b615-c7f6c1fabb16.PNG">
<img width="535" alt="contactPersonError3" src="https://user-images.githubusercontent.com/70317594/129690965-b8e511ec-a2a4-4fcc-93ea-3a9ca9c7a111.PNG">

### System Details

* Device:
* SORMAS version: 1.62.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
Tested further, the following methods cannot solve the problem via UI
- Changing `personContactDetailType` or `contactInformation`
- Deleting the entries from the table

Further: Importing `personContactDetail` crrectly also leads to this problem

**Comment by MateStrysewske** [comment]
@kwa20 I can't reproduce the problems you're experiencing, not even on test1401... can you try to reproduce them on a test instance running 1.63 please? I'll of course add the missing validation to the import in the meantime.

**Comment by kwa20** [comment]
@MateStrysewske Yes, it still occurs on 1.63. Sorry, maybe I wasn't explicit enough with the import. I tested on test-de1.sormas.netzlink.com and after importing the subsequent file, the error message occurs after trying to edit the person. Make sure to not select the existing person.

[test_import_personDetails.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7005585/test_import_personDetails.csv)

**Comment by MateStrysewske** [comment]
There was also validation missing for the region, district, community and facility fields of the person's home address.
