### ISSUE TITLE
String for reporting tool is reused for cases and events

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6443]
### Bug Description

The transmission confirmation window includes a string which is reused for cases and events. This leads to it being impossible to be translated in grammatically correct way for other languages than English. Therefore, this string should be split.  

This also includes the bulk edit plural versions.
### Steps to Reproduce

1. Send case and event data to the reporting tool
2. Check the confirmation message

### Expected Behavior

Strings should be separate and grammatically correct
### Screenshots

<img width="286" alt="separateStrings2" src="https://user-images.githubusercontent.com/70317594/130014439-2cfa6c54-bf22-4ff0-98df-e165ecc0f018.PNG">
<img width="315" alt="separateStrings" src="https://user-images.githubusercontent.com/70317594/130014441-6740297f-49a8-4427-bf1f-c723f7792a02.PNG">
<img width="321" alt="separateStrings3" src="https://user-images.githubusercontent.com/70317594/130014442-16eb8595-015b-4eb4-8773-d0275aa4f4a8.PNG">

### System Details

* Device:
* SORMAS version: 1.62.3
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
If German is selected, the sending confirmation is in English. ![image](https://user-images.githubusercontent.com/89522688/134309609-8c866b6d-823b-45b2-a6e5-f3724046db06.png)

**Comment by MateStrysewske** [comment]
@roxanamlendea That's because it hasn't been translated yet

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de1.sormas.netzlink.com
