### ISSUE TITLE
500 Internal Server Error when sharing an older case between test-de1 and test-de2

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#6447]
### Bug Description
Sharing an older case seems to produce a 500 Internal server error 

### Steps to Reproduce
1. Log in on Test-de1.sormas.netzlink.com
2. Select an older case and click on share 
3. Select test-de2 and don't check any checkboxes
4. Check what happens

### Expected Behavior
Sharing of cases between the 2 instances should work as expected

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/130046522-6dbd9ac7-3c17-463c-93c0-72ca5b939c5b.png)

### System Details

* Device: Windows
* SORMAS version: 1.63.0-Snapshoot
* Android version/Browser: Chrome
* Server URL: test-de1 
* User Role: NatUser

### Additional Information
this is the Case used to reproduce this issue:
https://test-de1.sormas.netzlink.com/sormas-ui/#!cases/data/QQMZ6X-CBOCHZ-OAZFVL-TWU5SCGA

**Comment by JonasCir** [comment]
The error shows up on the receiving side of the share
```
sormas_1             | [2021-08-19T11:47:48.696+0200] [Payara 5.2020] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=79 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1629366468696] [levelValue: 900] [[
sormas_1             |   StandardWrapperValve[de.symeda.sormas.rest.RestConfig]: Servlet.service() for servlet de.symeda.sormas.rest.RestConfig threw exception
sormas_1             | de.symeda.sormas.api.utils.ValidationRuntimeException: Content of cases could not be parsed to List<SormasToSormasCasePreview> - ID: 13600
sormas_1             | 	at de.symeda.sormas.backend.sormastosormas.sharerequest.SormasToSormasShareRequest.getCasesList(SormasToSormasShareRequest.java:149)
sormas_1             | 	at de.symeda.sormas.backend.sormastosormas.sharerequest.SormasToSormasShareRequestFacadeEJB.toDto(SormasToSormasShareRequestFacadeEJB.java:203)
sormas_1             | 	at de.symeda.sormas.backend.sormastosormas.sharerequest.SormasToSormasShareRequestFacadeEJB.saveShareRequest(SormasToSormasShareRequestFacadeEJB.java:74)
```

**Comment by leventegal-she** [comment]
Couldn't reproduce locally.

Should be checked by someone who has access to test-d2 to see the logs and maybe something could be found out from the DB.

**Comment by vidi42** [comment]
Cannot be reproduced on test-de1 and test-de2 atm as they are in an unstable state. Waiting for them to be stable again.

**Comment by vidi42** [comment]
The issue is caused by the updating of organizationIds in the config of the servers and affected all entities which already were already shared and `organizationId` values not being updated in `sormastosormasorigininfo` and `sormastosormasshareinfo`.

The fix is to manually update the `organizationId` in the database on test-de1 and test-de2.
