### ISSUE TITLE
[Climedo] Temperature is not transmitted from Climedo if "." is used as decimal

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6453]
### Bug Description

When a temperature value with a "." as the decimal is transmitted from Climedo to Sormas, the values is not entered.
### Steps to Reproduce

1. Register a contact or case in Climedo
2. Fill a questionnaire and enter a temperature value with "." as a decimal
3. Check the resulting visit in Sormas

### Expected Behavior

Temperature values should be entered
### Screenshots

<img width="472" alt="temperatureClimedo" src="https://user-images.githubusercontent.com/70317594/130192343-7c4f61aa-f2f4-44f0-a1b4-653fcfd6524f.PNG">

<img width="484" alt="temperatureClimedoNotTransmitted" src="https://user-images.githubusercontent.com/70317594/130108650-a26c2b20-44cb-472c-a32c-5f8ca7df3298.PNG">

### System Details

* Device:
* SORMAS version: 1.62.3
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
`POST .../sormas-rest/visits-external/` actually only accepts float values with "." as decimal separator. They can succesfully be transmitted and show in SORMAS (e.g. `"temperature": "37.1"` works).

That's why I suspect this is an issue on climedo side. @DraganMileski: Could you maybe have a look?

**Comment by ClimedoHealthCodingTests** [comment]
Hi there,

this issue could not be reproduced from both Chrome and Firefox browsers.

1/2 of temperatures from the screenshot below were transmitted via ',' and the other 1/2 with '.' Please try again and if it works fine close this issue.

ga1.sormas-oegd.de
Personen-ID SZ4R3G-VTROIA-GDOP5Z-C6PECENE

![image](https://user-images.githubusercontent.com/90610296/136956062-acdd581e-0e5f-49d8-a9be-13f321cfebcc.png)

**Comment by FredrikSchaeferVitagroup** [comment]
> @ClimedoHealthCodingTests Thank you, I'll test this issue again as soon as we start Release Candidate tests for 1.64. I'll discard this issue if I can verify the fix.

@kwa20 Can this issue be closed?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I could not exactly verify that because in Climedo, I was seemingly not able to enter a "," as a decimal. If this is intentional I think it should be fine though.
