### ISSUE TITLE
Spelling error in share request pop-up

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6454]
### Bug Description

Organization is misspelled in Share pop-up.
### Steps to Reproduce

1. Share a case with another health department
2. Check the Organization heading

### Expected Behavior

Should be Organization
### Screenshots

<img width="196" alt="spellingOrganization" src="https://user-images.githubusercontent.com/70317594/130132534-ac6aa7de-3cd0-49aa-b40b-10392a011960.PNG">

### System Details

* Device:
* SORMAS version: 1.63-SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de2.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

We should consider shortening the heading of the pop-up as well. 'Share' might suffice.

**Comment by Candice-Louw** [comment]
Part 2 of: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6192
