### ISSUE TITLE
Case fatality rate should exclude counts for "not a case"

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6457]
### Bug Description

The denominator/ sum used to compute case fatality rate included  cases with "not a case" classificaton.
### Steps to Reproduce

1.
2.

### Expected Behavior

Suggest to exclude counts for "not a case "
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/130160552-93923dc1-998b-4b0e-b3f5-2567c8eec50f.png)

### System Details

* Device:
* SORMAS version: 1.59.2
* Android version/Browser: web
* Server URL: https://sormas.edcd.gov.np/sormas-ui/#!dashboard
* User Role: national user + admin

**Comment by alexcaruntu-vita** [comment]
This was fixed in 1.60.0. @bernardsilenou is upgrade an option?

**Comment by bernardsilenou** [comment]
@alexcaruntu-vita Thanks for the infos, all is good.
