### ISSUE TITLE
Bulk edit mode options to edit case classification should match server instance

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6458]
### Bug Description

The case classification categories differ between server instances, eg DE has confirmed with known symptoms, while others do not. When editing cases by bulk action on the international instance, DE categories are suggested to the user.
### Steps to Reproduce

1. Do a bulk edit of case classification on international instance
2. Compare options suggested with those on the case form

### Expected Behavior

- Bulk edit mode should consider server instance and suggest  enums/ categories that matches the forms on server
### Screenshots

![image](https://user-images.githubusercontent.com/12996724/130161351-b1e7b7ac-863c-41d4-9932-8455f7225f28.png)

![image](https://user-images.githubusercontent.com/12996724/130161432-185ba358-3ef1-4a9d-9fd9-314db999b80b.png)

### System Details

* Device:
* SORMAS version:  1.62.3
* Android version/Browser: web
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: national user + admin

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.64.0-snapshot on test-de and test.sormas.netzlink.com environment
