### ISSUE TITLE
Visits documented as unavailable are marked as 'no' with symptomatic

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6466]
### Bug Description

Visits documented as unavailable are marked as 'no' for symptomatic. This should rather be null or at least 
### Steps to Reproduce

1. Enter a new visit as unavailable 
2. Check the symptomatic column

### Expected Behavior

Column value should be conform to the entered data in the visit. Therefore, it should be null
### Screenshots

<img width="860" alt="visitsSymptoms" src="https://user-images.githubusercontent.com/70317594/130216775-a855f284-d5ae-4231-ae13-4cff4d9dd62f.PNG">

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role:

**Comment by DavidBaldsiefen** [comment]
@kwa20 Should those visits with "Available, but uncooperative" also have "symptomatic" set to null?

**Comment by kwa20** [comment]
@DavidBaldsiefen yes please :)

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test.sormas.netzlink.com
