### ISSUE TITLE
Introduce a property to the SORMAS properties to disable manually editing of infrastructure data [1]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#6471]
### Situation Description
Right now, GAs are allowed to manually edit and tamper with their local data. 

### Feature Description
Introduce a server property which disables the manual editing of infrastructure data. While this is up to debate, I think that there should be at least three modes

1. Enabled
2. Archive-only: where old data can be archived 
3. Disabled: no access to what so ever, data cannot be de-archived and no manual edits

The affected data would include:
        - continents
        - subcontinents
        - countries
        - regions
        - districts
        - communities

Note: facilities and points of entries need to stay editable

- [x] When the manual editing of infrastructure data is disabled, also the import should be disabled.
- [x] Default value: Enabled

**Comment by vidi42** [comment]
New feature configuration for enabling/disabling the editing of infrastructure data `EDIT_INFRASTRUCTURE_DATA` (default enabled).
