### ISSUE TITLE
Form is not marked as dirty when changing the vaccination status of a contact / event participant

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#6474]
### Bug Description

When changing the value of the field "Vaccination status for this disease" on a contact SORMAS does not ask if changed values on the form should be saved when navigating away from the "Contact" or "Event Participant" form. (Cases are working fine)

### Steps to Reproduce

1. Open any contact or event participant
2. Change the value of the field "Vaccination status for this disease to another value than the current one (make sure this is the only value you change in the form)
3. Try to navigate to another page in SORMAS without clicking on "Save"

### Expected Behavior

A warning message should show up asking you if you want to save data that has been changed before exiting the page.

### Screenshots

<img width="458" alt="2021-08-20_15h01_34" src="https://user-images.githubusercontent.com/6122778/130237701-6bfec762-c516-4de8-9c87-25cecc7e9d3b.png">

### System Details

* Device: PC
* SORMAS version: reported in version1.61.2 but I was able to reproduce it in v. 1.62.3 as well
* Android version/Browser: Edge / Firefox / Chrome
* Server URL: n/a
* User Role: n/a

### Additional Information

Changed the description to also include event participants as commented by @kwa20

**Comment by kwa20** [comment]
This also applies for event participants

**Comment by MateStrysewske** [comment]
@kwa20 @Jan-Boehme Since the new immunization module will likely be finished within the current sprint, I'd consider this bug as wontfix because the field will not exist anymore.
