### ISSUE TITLE
Provide SQL script for semi-automatic import of Continents, Sub-Continents, Countries [2] 

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#6482]
### Problem Description

Currently this data can only be imported via csv in the frontend.
We have already provided a similar script for the import of facilities: #4728
and other data: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5251

- [x] Provide a script for Continents
- [x]  Provide a script for Sub-Continents
- [x]  Provide a script for countries
- [x]  Decide how to merge existing entries (e.g. name, external id)

### Additional Information

https://github.com/hzi-braunschweig/SORMAS-Project/pull/5329/files
csv files from https://confluence.sormas-tools.de/pages/viewpage.action?spaceKey=HZIOrga&title=Infrastructure+data should be usable as source

**Comment by vidi42** [comment]
To test the scripts the following CSVs can be used:

- [sormas_import_all_continents.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7099036/sormas_import_all_continents.csv)
- [sormas_import_all_subcontinents.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7099035/sormas_import_all_subcontinents.csv)
- [sormas_import_all_countries.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7099037/sormas_import_all_countries.csv)

The scripts are based on the import templates and are populated with the default data found in the [project resources](https://github.com/hzi-braunschweig/SORMAS-Project/tree/master/sormas-backend/src/main/resources).

**Comment by kwa20** [comment]
@vidi42 I think initially we used the ISO Code because we couldn't use the externalId since it was the subject that was supposed to be changed. I do however think that we can use it because the ISO Codes should be unique
