### ISSUE TITLE
Allow DEA travel entries to be imported without specifying a point of entry [1]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#6483]
### Feature Description

The DEA travel entry import requires a few changes made to the CSV file exported from DEA in order to be compatible with SORMAS. One change that can't be ommitted so far is that a point of entry needs to be specified.

### Problem Description

Changing the CSV file is not feasible for most users because they don't have the necessary knowledge to do so.

### Proposed Change

When a user on district level or below is performing the travel entry import and the respective information is missing, automatically fill the responsible region and district with the user's region and district and set the point of entry to OTHER_POE; set the point of entry details to "[System] Automatisch ausgefüllter Einreiseort". Only execute this part of the logic on German systems (in preparation of the upcoming refactoring that will make the travel entry import available for other countries as well).

**Comment by kwa20** [comment]
related to #6217

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
