### ISSUE TITLE
Case is empty if place of stay differs and user is contact supervisor

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6489]
### Bug Description

If the place of stay is set to another district then the responsible jurisdiction the case is shown empty for contact supervisor.

![image](https://user-images.githubusercontent.com/74791118/130562822-cd41017f-521d-4930-844d-15a18e56d361.png)

The case person and the other tabs are usable, but the case-tab isn't:

![image](https://user-images.githubusercontent.com/74791118/130562826-24db5977-baec-475f-a3d9-585ec9c07679.png)

![image](https://user-images.githubusercontent.com/74791118/130563152-d307840a-12bf-4188-8648-2aa2d38b8cf7.png)

### Steps to Reproduce

1. edit a case and set the place of stay to another place then the responsible jurisdiction
2. open the case with a user, which is only contact supervisor

### Expected Behavior

Should be shown for the contact supervisor

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser:
* Server URL:
* User Role:

**Comment by kwa20** [comment]
@Marko-ilmkreis Thank you for reporting this.

Further investigation revealed that this is also happening for:
- Case Officers
- Contact Officers
- Event Officers

All should have the CASE_EDIT user right

**Comment by roxanamlendea** [comment]
This ticket is related to ticket: #6595

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com with contact sup, case officer, contact officer, event officer.
