### ISSUE TITLE
Make import of DEA-files with [TAB]-separator possible

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6490]
### Feature Description

Enabling the tab as separator for importing DEA-files.

### Problem Description

The standard-files downloaded by the users from DEA are separated by tab, while the normal import files in sormas are using the semicolon.

To change the separator within the file is not possible for the normal user.

### Possible Alternatives

Providing a (power shell-) script for every user to change the separator.

**Comment by MateStrysewske** [comment]
This is currently in development in #5459
