### ISSUE TITLE
Improving the duplicate detection pop-up at the import

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6491]
### Feature Description

The fields of the imported person are cut-off at the end of the duplicate detection. For the desk officer it is not possible to check all possible fields.

Even though the fields should be in the same order at the imported person and the possible duplicates to make it easier for the health offices.

![image](https://user-images.githubusercontent.com/74791118/130615780-71f3b5cd-e02a-40e2-bda3-114f6092e16b.png)

**Comment by kwa20** [comment]
My suggestion: Make the display of the entered data horizontally scrollable.

**Comment by Marko-ilmkreis** [comment]
@kwa20 Good idea, but then the scrolling should be synchronised between the duplicate and the suggestion if possible. 
Other option: display the imported person in two or more lines to show all data. 
Another option: expanding the size of the pop-up depending of the resolution of the screen (the screenshot is from a 24" wide angle)

**Comment by kwa20** [comment]
@Marko-ilmkreis All sound like good options to me. For the pop-up expansion, we might need to consider accessibility so it would probably go alongside a scrolling option, I think.
@MateStrysewske I would leave the judgment of the most feasible option to you.

**Comment by MateStrysewske** [comment]
@kwa20 @Marko-ilmkreis I don't know whether synchronizing the scrolling is possible (I would guess not, or at least not easily), so I'd go with adding an additional line instead.
