### ISSUE TITLE
Travel entry directory does not reload after the creation of a new travel entry

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6492]
### Bug Description

After creating a new travel entry, the travel entry directory is not reloaded, which therefore does not display the new entry that was just created.
### Steps to Reproduce

1. Create a new travel entry
2. check for the new entry on the directory
3. Reload the directory

### Expected Behavior

The directory should reload and display the new entries to the user.
### System Details

* Device:
* SORMAS version: 1.62.3
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by alexcaruntu-vita** [comment]
Actually the right behaviour should be navigating to travel entry details instead of showing the list. This is what I fixed with the corresponding PR.
