### ISSUE TITLE
Persons cannot be newly created in the duplicate detection

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6495]
### Bug Description

When a duplicate is created where the place of stay differs from the responsible jurisdiction, the selection of creating a new person leads to an error when saving.
### Steps to Reproduce

1. Create a case where the responsible jurisdiction is the same as the place of stay
2. Create a duplicate case where the place of stay differs from the responsible jurisdiction and set the district to anything but the responsible district, save.
3. In the person duplicate pop-up, select 'Create new person', save > Error appears (Screenshot1)
4. Repeat and select the existing person
5. In the case duplicate pop-up, select 'Create new case', save > Error appears (Screenshot2)

### Expected Behavior

It should be possible to create a new person or a new case.
### Screenshots

<img width="510" alt="newPersonDuplicateDetectionError" src="https://user-images.githubusercontent.com/70317594/130761103-2f7aee20-282e-4dea-a9a6-56da5f58ad43.PNG">
<img width="637" alt="newPersonDuplicateDetectionError2" src="https://user-images.githubusercontent.com/70317594/130761105-45b2bb76-0316-4131-a99f-f287a675e58a.PNG">

### System Details

* Device:
* SORMAS version: 1.62.3
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by syntakker** [comment]
The bug that manifests here has the same cause as #6607 (incorrect update of `facilityOrHome`). Please refer to the more accurate description of how and in which order to set facilityOrHome / jurisdiction fields to reproduce the error.

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
