### ISSUE TITLE
Events > Bulk Actions > `Send to reporting tool` visible on non-DE systems

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6498]
### Bug Description

Events > Bulk Actions > `Send to reporting tool` visible on international servers despite SORMAS2SurvNet not being a config option. It may cause some confusion.

### Steps to Reproduce

1. Events > Events Directory > Bulk Actions
2. `Send to reporting tool` option visible in drop-down list
3. Click yes in "Confirm sending" dialog
4. Error message appears

### Expected Behavior

`Send to reporting tool` option not visible in drop-down list if external reporting tool (SurvNet) is not configured.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/130780355-7ae6d1fc-fd61-468f-946c-5ade058f0102.png)
![image](https://user-images.githubusercontent.com/65529128/130779646-ab633ad4-7df4-4f98-8224-ec0af2d64cda.png)

### System Details

* Device: PC
* SORMAS version: 1.62.3, 1.63
* Android version/Browser: Chrome
* Server URL: https://stable-release-ch.sormas.netzlink.com/, https://test.sormas.netzlink.com/
* User Role: admin, natuser

**Comment by AndyBakcsy-she** [comment]
Closing ticket as fixed after the latest version deployed on test.sormas.netzlink.com
![image](https://user-images.githubusercontent.com/70562142/132339714-955b8eb3-4c80-4891-8465-f8bba65ef88d.png)
