### ISSUE TITLE
Still error by setting geo coordinates via bulk action

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6506]
### Bug Description

@DavidBaldsiefen 
This is a follow-up vom #5992. The error still comes up when the geo-coordinates are set via the person person directory:

![image](https://user-images.githubusercontent.com/74791118/130899126-e3d91b5c-cb9a-4552-8ec0-e47bc5a6fb5c.png)

The error occurs after approx. 6 seconds of running the script.

### System Details

* SORMAS version: 1.62.3
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Can you please try to get server logs that include this error and forward them to us?

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske 

Here is the log-file:

[Ilm-Kreis-Logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7088199/Ilm-Kreis-Logs.txt)]

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske I corrected the entry for the case above and had a failure and generated a new log.

As far as I see it comes not to the point to hand-over the address to the geocoding-server:

[Ilm-Kreis-Logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7089390/Ilm-Kreis-Logs.txt)

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Thanks!

**Comment by leventegal-she** [comment]
The problem was that `JsonPath.read` sometimes returns Integer that can't be converted to double thus getting the coordinates fails with a ClassCastException exception

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
