### ISSUE TITLE
Reference definition is visible on the dashboard of international servers

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6510]
### Bug Description

On international servers, the German specific reference definition is visible.
### Steps to Reproduce

1. Open the surveillance dashboard
2. Check the Disease slides section for 'Case with reference definition fulfilled'

### Expected Behavior

This field should only be shown on German servers
### Screenshots

<img width="385" alt="referenceDefinitionInt" src="https://user-images.githubusercontent.com/70317594/130940991-82d4c960-c167-4991-ac4d-25e15eb7c598.PNG">

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: firefox
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test.sormas.netzlink.com
