### ISSUE TITLE
CI check sormas-app in our GitHub Actions CI

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#6514]
### Problem Description
The sormas-app is not CI checked for PRs.

### Proposed Solution
Build the Android App if changes to `sormas-app` or `sormas-api` folders are made.

### Possible Alternatives
Do nothing, but I feel uncomfortable every time I make changed to `sormas-api` and fear that I broke something.

**Comment by vidi42** [comment]
To be addressed with #6665
