### ISSUE TITLE
Detailed case export file is empty when cases with unknown previous hospitalization entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6521]
### Bug Description

When previous hospitalizations are entered where location data is unknown, detailed case exports produce an empty file.
### Steps to Reproduce

1. Create a case
2. Enter a previous hospitalization
3. Set region, district and hospital to unknown
4. Perform a detailed export where the created case is included
5. Check the exported file

### Expected Behavior

Values should be exported as unknown
### Screenshots

<img width="763" alt="prevHospExportError" src="https://user-images.githubusercontent.com/70317594/130964034-d4a1fb7c-56c7-456c-8c80-a1fb0cebad0b.PNG">

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test.sormas.netzlink.com and test-de.sormas.netzlink.com.
