### ISSUE TITLE
[DEMIS Interface] Table of content links reload Surveillance Dashboard

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6524]
### Bug Description

When a user selects the links in the table of contents in a lab message, the background behind the pop-up reloads the surveillance dashboard.
### Steps to Reproduce

1. Open a lab message in the lab messages directory
2. Click any link in the table of contents

### Expected Behavior

User should merely get navigated to the respective section of the lab message but stay on the lab message directory
### Screenshots

<img width="959" alt="labMessageDashboardReload" src="https://user-images.githubusercontent.com/70317594/130993672-1d005adb-04d2-440e-aa76-3c3b03922e4f.PNG">

### System Details

* Device:
* SORMAS version: 1.63.0 / 1.8
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
The solution for this bug is part of [#33](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/33) (see `1. Internal links are not removed`). That is why I think this can be closed as a duplicate.

**Comment by AndyBakcsy-she** [comment]
Tested the links on the latest SORMAS Version: 1.64.0-SNAPSHOT on test-de2.sormas.netzlink.com and the links are working correctly for Lab Messages.

**Comment by kwa20** [comment]
@AndyBakcsy-she I was still able to reproduce this issue on the same server (test-de2.sormas.netzlink.com)

<img width="810" alt="labMessageRedirect" src="https://user-images.githubusercontent.com/70317594/132227409-f90770dd-a911-4456-b5d0-6cb8e5e9e1ef.PNG">
