### ISSUE TITLE
e2e-performance-tests failing

### ISSUE THREAD

**Issue by DavidBaldsiefen** [hzi-braunschweig/SORMAS-Project#6534]
### Bug Description
Since a few days the e2e-performance tests are failing

### Steps to Reproduce

1. Try to execute the performance tests using jmeter and check the result

### Expected Behavior
All OK :)

### System Details

* Device:
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser:
* Server URL: locally and test-performance.sormas.netzlink.com
* User Role: Rest-User

**Comment by DavidBaldsiefen** [comment]
Reopen because more fixes were found-

**Comment by StefanKock** [comment]
It's not a bug of the delivered software, so changed to task
