### ISSUE TITLE
[Line Listing] Missing label & required field mark

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6542]
### Bug Description
On Line Listing, when selecting "other facility", the label above the new filed ("facility name") is missing, and also, it is not marked as mandatory.

### Steps to Reproduce

1. Go to Cases.
2. Click on Line Listing.
3. Fill in the fields and select "Facility": "other facility". 

### Actual Behavior
The facility name filed is not marked as mandatory. The label above the facility name field is missing.

### Expected Behavior
The facility name filed is marked as mandatory. The label above the facility name field is present.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/131342581-f6a74860-7ca0-42f6-9bef-03e0650b4b64.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com
* User Role: NatUser

**Comment by MateStrysewske** [comment]
@roxanamlendea The caption was removed on purpose because it's pretty long and messed with the layout
