### ISSUE TITLE
[Dashboard] Apply filters button is hidden because of missing horizontal scroll bar

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6543]
### Bug Description
When zoom is set on 100%, on Dashboard, user cannot see the Apply filters button because the horizontal scroll bar is missing.

### Steps to Reproduce

1. Set zoom to 100% on browser.
2. Go to Dashboard.

### Actual Behavior
The Apply Filters button is not visible and can only be reached if user sets the zoom to 90%.

### Expected Behavior
The Apply Filters button is visible or can be reached by scrolling to the right.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/131350739-7316727d-056b-4e6e-9251-c7a7b1eb86d5.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com/sormas-ui/#!dashboard
* User Role: NatUser

**Comment by MateStrysewske** [comment]
We should use the same logic as in the directories here, i.e. elements that don't fit horizontally get pushed to the next line.
