### ISSUE TITLE
Activity as case values do not show in table

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6545]
### Bug Description

When `OTHER` is selected in `activityAsCaseType` or `typeOfPlace` in activity as case, the table does not display the value in the epi data tab.
### Steps to Reproduce

1. Open or create a case
2. Enable activities as case and create an entry with `activityAsCaseType` = `OTHER` and `typeOfPlace` = `OTHER`, save
3. Check table after creation

### Expected Behavior

Any value should be properly displayed in the table

### Screenshots

<img width="482" alt="activityAsCaseTableBug2" src="https://user-images.githubusercontent.com/70317594/131367211-9fff157b-168b-45bc-8ad7-b3bbdb74a8a8.PNG">
<img width="408" alt="activityAsCaseTableBug" src="https://user-images.githubusercontent.com/70317594/131367219-d21253cb-88fa-464a-9a9a-fdcf75c180d1.PNG">

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by alexcaruntu-vita** [comment]
If we select `OTHER` the logic is to display what it is entered in `Type of activity details`. Same for `Type of place`. In case those are not filled we end up with a checkbox with no text (maybe we should display `Other` in this case). What should be the behaviour in this scenario?

**Comment by kwa20** [comment]
Yes, I'd suggest so:

If details fields are NULL, display the value in the superordinate fields which would be OTHER

**Comment by roxanamlendea** [comment]
When type of activity = other (and the detail field is filled in) and type of place = other (and the detail field is filled in), in the table the type of place is the same as the type of activity. ![activity as case 2](https://user-images.githubusercontent.com/89522688/132205255-04e382a2-528d-49de-9d10-21205957a0bd.png)
![activity as case 1](https://user-images.githubusercontent.com/89522688/132205259-24d5e047-b497-4024-9b21-ed663413b800.png)

**Comment by roxanamlendea** [comment]
When type of activity ≠ other (eg. travel) and type of place = other, in the table the type of place is not displayed.
![activity as case 3](https://user-images.githubusercontent.com/89522688/132206466-31d58af3-0cb9-4e28-98a7-d12f7fd88fc2.png)
![activity as case 4](https://user-images.githubusercontent.com/89522688/132206476-b3237302-7879-4203-9b00-edde25ef53d2.png)

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
