### ISSUE TITLE
[Case Directory] Error when selecting Follow-up on Case Directory

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6553]
### Bug Description
On Case Directory page, when user selects "Follow Up", the system crashes and user gets an error message.

### Steps to Reproduce

1. Go to Cases (Case Directory)
2. From the top of the page, select the "Follow-up" button.

### Actual Behavior
The system crashes, user gets an error message.

### Expected Behavior
The follow-ups of the cases appear listed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/131476745-afd88628-73a8-4853-8928-02b1f289657b.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE
* User Role: NatUser

**Comment by MateStrysewske** [comment]
Doesn't happen on my system, so probably has something to do with the data on the test instance. I've requested log files.

**Comment by roxanamlendea** [comment]
> Doesn't happen on my system, so probably has something to do with the data on the test instance. I've requested log files.

On test-de2 and test-de3 it's working fine, on test and test-de is the error.

**Comment by MateStrysewske** [comment]
[Logs Test-de.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7096875/Logs.Test-de.txt)

**Comment by roxanamlendea** [comment]
I found out that this also happens on Contacts directory page. If I select "Follow up visits", the system throws an error. 
![image](https://user-images.githubusercontent.com/89522688/132323621-aa3924e6-6085-476e-aa09-86bdc0ac086c.png)
