### ISSUE TITLE
[Case Directory] Information icon is not clickable

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6556]
### Bug Description
The blue information icon on Case directory page is not clickable, and if clicked, nothing happens.

### Steps to Reproduce

1. Go to Cases (Case Directory)
2. Click on Show more filters.
3. Click on the blue information icon.

### Actual Behavior
Information blue icon is not clickable and if clicked, nothing happens.

### Expected Behavior
Information blue icon is clickable.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/131493745-141a6382-7655-49a8-bd5d-ec76dafaa135.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE
* User Role: NatUser

**Comment by MateStrysewske** [comment]
@roxanamlendea These info icons aren't supposed to be clickable, they show a description popup when hovering over them :)

**Comment by roxanamlendea** [comment]
@MateStrysewske On hover, no pop up appears

**Comment by roxanamlendea** [comment]
> @roxanamlendea These info icons aren't supposed to be clickable, they show a description popup when hovering over them :)

@MateStrysewske On hover, no pop up appears

**Comment by kwa20** [comment]
@roxanamlendea Hey, nice to meet you! If you hover over it with your cursor you should be able to make additional information available. Maybe you can try again and verify? I was able to do it on firefox and chrome

**Comment by roxanamlendea** [comment]
@kwa20 Hi, nice to meet you too. Apparently now it works....It didn't when I found it. I also have a recording in which it didn't work.
![information icon](https://user-images.githubusercontent.com/89522688/131497704-ab84efda-f3ce-445f-ac02-f28b8b1ba301.gif)

**Comment by MateStrysewske** [comment]
@roxanamlendea There's a small delay before the popup appears in which you have to keep the mouse in one place
