### ISSUE TITLE
Cases & Contacts > Split single, re-used variable for translation in UI

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#6565]
### Feature Description

Introduce two separate strings to the UI:
1. Cases > Open Case > Under the "Samples" box > "Creating a new sample will discard all unsaved changes made to this case"
2. Contacts > Open Contact > Under the "Samples" box > "Creating a new sample will discard all unsaved changes made to this contact"

### Problem Description

The string "Creating a new sample will discard all unsaved changes made to this case", saved as `infoCreateNewSampleDiscardsChanges` , is reused for both Cases and Contacts.  This leads to inconsistent translations in the UI for all languages, and no way of fixing it through CrowdIn.

### Proposed Change

Split `infoCreateNewSampleDiscardsChanges` for Cases and Contacts.

### Additional Information

![image](https://user-images.githubusercontent.com/65529128/131576674-1aea6059-b61d-44f2-b2ac-70a5866a1ce1.png)
![image](https://user-images.githubusercontent.com/65529128/131576836-96d087da-22da-42bd-b885-951e992bef0f.png)

**Comment by kwa20** [comment]
This issue will become obsolete if #7350 gets implemented

**Comment by Candice-Louw** [comment]
Text is showing up correctly - closing issue.
Tested on: https://release-international.sormas.netzlink.com/

Verified split text on CrowdIn as:
infoCreateNewSampleDiscardsChangesCase: Creating a new sample will discard all unsaved changes made to this case
infoCreateNewSampleDiscardsChangesContact: Creating a new sample will discard all unsaved changes made to this contact
infoCreateNewSampleDiscardsChangesEventParticipant: Creating a new sample will discard all unsaved changes made to this event participant
