### ISSUE TITLE
[SORMAS2SURVNET] Mutation: fill detail field in Survnet with comment field in SORMAS

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#6567]
### Feature Description
The detail field in SURVNET you see in the labor informations should be fullfilled with the comment field from SORMAS, or there should be a new details field in SORMAS.
![image](https://user-images.githubusercontent.com/79255722/131626491-5a59a40c-97ea-481f-a13b-9146df6b49d1.png)

### Problem Description
We have a few new/othe mutations there are not listed in SORMAS and SURVNET and we have to report this information via SURVNET to our "State Administration Office". They told us to use the details field you see above.

### Possible Alternatives
* use comment field in SORMAS
* implement new details field in SORMAS

**Comment by kwa20** [comment]
@herrling-LRA-KYF Since there is this issue in place already https://github.com/hzi-braunschweig/SORMAS-Project/issues/5935 I would close this as a duplicate but please feel free to comment on the existing issue for feedback
