### ISSUE TITLE
Contact line listing duplicates person

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6572]
### Bug Description

The contact line listing does not properly allow the creation of multiple contacts at the same time and also goes through multiple duplicate detection pop-ups for seemingly the same contact persons and contacts.
### Steps to Reproduce

1. Enter the contact line listing either via contact directory or case contact tab
2. Enter names for the first contact before adding others
3. Enter at least 1 or 2 more contacts by adding lines
4. Adjust the duplicate names and save

Also try the following:
1. Enter the first contact with name details
2. Add the second and third line
3. Delete the second and third line
4. Delete the name details of the first contact
5. Re-add the second and third line
6. The copied name will still be there

### Expected Behavior

Multiple different contacts should be able to be created.
### Screenshots

<img width="783" alt="contactLineListingBug" src="https://user-images.githubusercontent.com/70317594/131654404-298b7ba5-c8aa-40ef-a1e2-33542b192f65.PNG">
<img width="773" alt="contactLineListingBug2" src="https://user-images.githubusercontent.com/70317594/131654403-be96375c-7822-4339-af09-a651ff95b7e3.PNG">

After replacing the duplicate names:
<img width="774" alt="contactLineListingBug3" src="https://user-images.githubusercontent.com/70317594/131654410-5aea62c9-36b1-4b5f-b7c7-9a3dc48e5452.PNG">
Result after creating multiple contacts is a reappearing duplicate detection for one of them only.
<img width="514" alt="contactLineListingBug4" src="https://user-images.githubusercontent.com/70317594/131654408-1a472f11-599f-488b-b8f9-3de55051d7a8.PNG">

### System Details

* Device:
* SORMAS version: 1.62.3 / 1.63.0
* Android version/Browser: firefox
* Server URL: int-sormas-x.sormas.netzlink.com / test1401.sormas-oegd.de
* User Role:admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test.sormas.netzlink.com.
