### ISSUE TITLE
[S2S] Event preview produces error when event does not have a disease

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6576]
### Bug Description

When event without a known event is shared, the share request preview in the receiving instance shows an error
### Steps to Reproduce

1. Create an event with disease NULL in Sormas A
2. Send event to Sormas B
3. Preview the share request in Sormas B
4. Add event in Sormas A and share with Sormas C
5. View Share request in Sormas C

### Expected Behavior

Events with disease NULL should be properly displayed
### Screenshots

<img width="488" alt="SharesEventsError" src="https://user-images.githubusercontent.com/70317594/131666398-7fcdc3dc-74da-4133-a10b-43603b747c68.PNG">
<img width="451" alt="SharesEventsError2" src="https://user-images.githubusercontent.com/70317594/131666397-4b2c5f46-e4ea-463f-b6f7-c200a2733245.PNG">

### System Details

* Device:
* SORMAS version: 1.64-SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de1/2/3.sormas.netzlink.com (3 instances)
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environments: test-de1.sormas.netzlink.com ,test-de2.sormas.netzlink.com and test-de3.sormas.netzlink.com
