### ISSUE TITLE
Additional tests cannot be deleted

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6579]
### Bug Description

Trying to delete additional tests does not work properly.
### Steps to Reproduce

1. Create or open an additional test in any sample
2. Try deleting the additional test
3. Confirm the deletion

### Expected Behavior

The additional test should get deleted
### Screenshots

<img width="563" alt="additionalTestDeleteBug" src="https://user-images.githubusercontent.com/70317594/131679209-10ba0f9a-3013-4bb0-bd5e-1adddfd18b9f.PNG">

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
