### ISSUE TITLE
Persistant Error HTTP 401 / SORMAS-Admin is failing  connect separate User with Rest-API-role

### ISSUE THREAD

**Issue by bel20git** [hzi-braunschweig/SORMAS-Project#6584]
The GA whishes to use the Rest-API  in the near future and already managed to unlock the it, as a result of requesting it at Netzlink.
The (Rest-API)-User in this example ist setup with the rest-API and Admin-role and saved without the input of an e-mail adress, so that a password was shown directly in the process.

Trying to loggin this rest-API-user,  is only producing aforementioned HTTP-401-Error.
What wrong with certain steps or is the requester missing soumething more fundamental?

 I would appreciate any possible solution,
kind regards,

bel20git

**Comment by MateStrysewske** [comment]
@bel20git If I'm not mistaken, the admin and ReST user roles alone won't allow the user to access any data - the ReST user role is necessary to access the ReST interface in the first place, but you need another user role that is allowed to see data. I'd suggest the National User role because it can access all data on the system.

**Comment by bel20git** [comment]
First of all, thank you, now I actually also remember having heard the fact before.
In addition, it would help me a lot for the conversation with the user to see the synthax for this first access via rest user + nat user as an example. (I think I once heard or read something about "HTTP Basic Auth"?).

**Comment by vidi42** [comment]
A curl sample to get you started @bel20git 
```
curl --request GET \
  --url  {server_url_here}/sormas-rest/info/version \
  --header 'Authorization: Basic dXNlcm5hbWVyOnBhc3N3b3Jk'
```
Note that the Authorization header is Base64(username + ":" + password)

You should be able to import this curl into postman and update it to match your instance.
