### ISSUE TITLE
CLUSTER EVENT: case linking is broken

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#6589]
### Bug Description
when creating a new Cluster event and use the tab "Eventparticipant" to add the relevant cases, you can see all this cases in this tab. But if you open the case, there is no event link to this cluster. Also if you send the cluster to SURVNET, there are no linking to the cases.

A workaround is to create the cluster and add the cluster directly in the case page for linking the cluster event. When all is fine

### Steps to Reproduce
1. create a new CLUSTER event
![image](https://user-images.githubusercontent.com/79255722/131850552-a508da5b-38d8-472c-9c9f-914319bd5f9a.png)
2. add eventparticipants
![Unbenannt](https://user-images.githubusercontent.com/79255722/131850956-69b83956-1f1d-4967-b5bd-3e00c702401e.png)
![Unbenannt1](https://user-images.githubusercontent.com/79255722/131852024-3d4d3d9a-2f63-4685-b29a-1a61eb7f26be.png)

3. open the case you added as an eventparticipant.
4. see the linked events
![image](https://user-images.githubusercontent.com/79255722/131851458-2ab54f5b-aa72-4a51-8e2f-8ffdfdd5258f.png)

BTW:
* If I look for the person, i see the linked event, but not for the case. 
* in prev. versions of sormas it was automatically linked to the case.
* I guess survnet needs the case, not the person.

### Expected Behavior
automatically linking the cluster to the case, when adding the cases via the eventparticipant tab out of the cluster

### System Details

* SORMAS version: 1.62.3

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske i added a few new information

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF What are the user roles of the user you tried it with?

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske national user and admin

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF Okay, are you sure that you linked the event participant to the case (e.g. by clicking the "Create" link in the "Fall-ID" column)? By adding an event participant to an event, you do NOT add a case to the event, you only add the person. If you want to link that person to a case, you either have to do it afterwards like described above, or you have to directly link the case to the event from the case view.

**Comment by herrling-LRA-KYF** [comment]
@MateStrysewske yes, you are right. I only added the person and created a new event participant. In previous  versions i think it was possible to add a case, not only the person. 
Now we have a few more work. Maybe you can discussthe possibility to add dirctly a case for cluster events.

**Comment by MateStrysewske** [comment]
@herrling-LRA-KYF If I'm not totally mistaken, it was never possible from this view - we definitely didn't remove any feature here. I think being able to directly add a case from the event participant list makes sense though. I've created a new issue for that: #6629
