### ISSUE TITLE
Change the German caption of the internal token field of events

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6600]
### Situation Description

Thus far for contacts and cases are internal token fields available, but not for events.

To have it more consistent it would be good to have it for events as well.

**Comment by kwa20** [comment]
@Marko-ilmkreis There actually is already an `interalToken` field in events. However, in German there was seemingly the need to translate it as "Herdkennung".

**Comment by Marko-ilmkreis** [comment]
@kwa20 But do you know why it is translated into Herkennung? I thought this might be a field which is filled/needed by SurvNet? Maybe we can discuss it today at the meeting

**Comment by JaquM** [comment]
@Marko-ilmkreis @kwa20 the field is necessary for transmission to SurvNet, therefore the field cannot be used as an internal token. If an additional field is needed, this should be accompanied by a renaming.

**Comment by Marko-ilmkreis** [comment]
@JaquM @kwa20 then the use of the fields is inconsistent. In cases we use external id and token for survnet. In my opinion that must be the same for events.

**Comment by JaquM** [comment]
@Marko-ilmkreis for events you need one more field, it is the title "Name im GA" in SurvNet, which is mapped to this internal Token field.

**Comment by kwa20** [comment]
@JaquM @Marko-ilmkreis We do use both fields in events because we merely map internalToken in events to "Name im GA" which would theoretically be what an internalToken is used for. It's freely usable for health departments and is just an additional information sent to SurvNet. In the case of internalToken, we're not really dependent on SurvNet meaning I suppose.

**Comment by Marko-ilmkreis** [comment]
@JaquM @kwa20 that's good to know. Maybe the wording in German is not very clear in that case. Can we change it to "Herdkennung(intern. Aktenzeichen)" or similar?

**Comment by kwa20** [comment]
@Marko-ilmkreis I thought about that too actually, would be fine with me.

**Comment by kwa20** [comment]
Changed on crowdin.
