### ISSUE TITLE
Providing a script for migrating the external token and external ID to internal token

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#6602]
Since implementing #5224 we have the field internal token. It would be good to migrate the details from external token and external id to these new field.

In my view a script might be as the following:

if internal token <> '' -> do nothing
if external id  and external token = '' -> do nothing
if external id = "" and external token <> '' -> move external token to internal token
if external id <> '' and external token = '' -> move external id to internal token
if external id and external token <> '' -> check if they contain the same text -> delete one and move the other, if the text is not the same linking both and move the text to internal token

**Comment by kwa20** [comment]
@Marko-ilmkreis I think this would be covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/6252?

**Comment by Marko-ilmkreis** [comment]
@kwa20 I had in mind that somewhere was the issue, but had not found it. shame on me.
