### ISSUE TITLE
[Angular] Edit icon for list items [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6606]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlDa3xn
- We need to add the edit icon and when pressing the icon we need to emit an event to the parent.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
