### ISSUE TITLE
Error message when place of stay was selected before the jurisdiction

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6607]
### Bug Description

When selecting the facility in place of stay before selecting the jurisdiction results in an error.
### Steps to Reproduce

1. Select create a case
2. Select facility or home before jurisdiction
3. enter other compulsory fields and save

### Expected Behavior

Entry should work fine and not produce an error
### Screenshots

<img width="664" alt="Screen Shot 2021-09-03 at 11 48 53 AM" src="https://user-images.githubusercontent.com/70317594/131986863-d0e2d6ed-8aaa-44a9-8533-4ddc74219216.png">

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
