### ISSUE TITLE
[Angular] Add / Edit Regions Modal [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6609]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/4a9oe3A
- This should be a single component that handles both add and edit Regions
- If an entity is supplied, than it's edit, if not, create.
-  We will implement the GET request for available information (if we have it, we use it)
- Obs: "Area" should be ignored (not implemented), @cristinacoza please investigate what and where is "Area" used and how it relates to "Country"
- - Note: If the backend is setup and the create call is available we need to implemented in Angular

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - there are some styling issues that will be resolved in a future task dedicated to dynamic form and table component styles update
