### ISSUE TITLE
[Angular] Add / Edit District Modal [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6610]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/eKolwVW
- This should be a single component that handles both add and edit District
- If an entity is supplied, than it's edit, if not, create.
- We will implement the GET request for available information (if we have it, we use it)
- - Note: If the backend is setup and the create call is available we need to implemented in Angular

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - there are some styling issues that will be resolved in a future task dedicated to dinamic form and table component styles update
