### ISSUE TITLE
[Angular] Add / Edit Community Modal [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6611]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm8oL35 (Region is also a dropdown not an input)
- This should be a single component that handles both add and edit Community
- If an entity is supplied, than it's edit, if not, create.
- We will implement the GET request for available information (if we have it, we use it)
- Note: If the backend is setup and the create call is available we need to implemented in Angular

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
