### ISSUE TITLE
[DEMIS] Lab messages can not be downloaded in a proper format

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6613]
### Bug Description

When downloading lab messages as PDF, users complain about some messages being downloaded as xml text.
### Steps to Reproduce

1. View a fetched message and verify that the html display works fine on the UI
2. Download the message
3. Check the content of the downloaded PDF

### Expected Behavior

Downloaded PDFs should be displayed in an easily readable format.
### Screenshots

<img width="586" alt="LabMessageDownloadDisplay" src="https://user-images.githubusercontent.com/70317594/131991979-1848f741-46ef-4d1f-9806-c48b0fa6ffca.PNG">
<img width="713" alt="LabMessageDownloadDisplay2" src="https://user-images.githubusercontent.com/70317594/131991987-172f6003-c398-4258-9f83-8cacef043a4d.PNG">

### System Details

* Device:
* SORMAS version: 1.62.3
* Android version/Browser: firefox
* Server URL: productive systems (unknown)
* User Role: unknown

### Additional Information

Users suspect disease variants to play a role in this. Specifically, the ones containing disease variants are displayed correctly and ones that don't incorrectly.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Thank you for the bug report. Unfortunately, I don't understand some part of it:

> Users suspect disease variants to play a role in this. Specifically, the ones containing disease variants are displayed correctly and ones that don't incorrectly.

Can you please explain this in a little more detail?

Without any further hint, it is hard to reproduce the error. Who can we reach out for to get a log excerpt?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Unfortunately, that's all I know so far. Apparently, lab messages are displayed correctly if there are disease variants contained in the message. I do however not know how exactly they were entered in the first place.

> Without any further hint, it is hard to reproduce the error. Who can we reach out for to get a log excerpt?
I'll ask the support to ask users to reproduce the problem and provide Netzlink with the time so they can hopefully provide us with logs.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup This has been provided by the support: 
[LogsGifhorn_labMessage_210907.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7119777/LogsGifhorn_labMessage_210907.txt)

**Comment by markusmann-vg** [comment]
Please provide an example (xml or pdf) where the problem occurs. 
Then we will validate the file and maybe implement escapes

**Comment by vidi42** [comment]
Probably some special character like `<`, `>`, `&` are not escaped

**Comment by kwa20** [comment]
@markusmann-vg Since I don't have a working Test environment for DEMIS, I'll try to somehow get a pseudonymized file from a health department and then upload it here.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @markusmann-vg This is an example we got from a health department: 
[sormas_lab_message_TSOEA7_2021-09-09.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/7141862/sormas_lab_message_TSOEA7_2021-09-09.pdf)

**Comment by maxiheyner** [comment]
Is this issue planned for the upcoming adapter version?

**Comment by FredrikSchaeferVitagroup** [comment]
@maxiheyner There is no official sprint commitment yet, but it will probably go into SORMAS-DEMIS-Adapter version 1.10.0, which will be for SORMAS 1.65.X.

**Comment by AdrianMichaelis** [comment]
For us this problem occurs only with some labs. 
In this example it was a missing quotation mark in the entry 'Patient':

![demis_xml_fehler](https://user-images.githubusercontent.com/71097393/134642515-0b060229-a092-4483-9d90-420df6f87d01.jpg)

**Comment by FredrikSchaeferVitagroup** [comment]
Thank you @AdrianMichaelis for your input. It is very helpful to get concrete examples, otherwise we are kind of groping in the dark.

Our ability to handle invalid input from DEMIS-notifications is, and will also in the future be, limited.  But we will add some mechanism to catch some flaws, probably also ones of the like you described.

**Comment by AdrianMichaelis** [comment]
@FredrikSchaeferVitagroup I hear you. Not ideal. 
Here's two more examples, from two different labs:
![fhir_example2](https://user-images.githubusercontent.com/71097393/134652497-d5eba933-a90e-4aeb-b9a8-142d26c957cf.jpg)

Seems to be the same issue each time, in line 98. AFAIK, it only happens with these two labs, but with those it happens consistently.

**Comment by AdrianMichaelis** [comment]
> Users suspect disease variants to play a role in this. Specifically, the ones containing disease variants are displayed correctly and ones that don't incorrectly.

Can't confirm this. We have lab messages with variants that don't convert to pdf properly.

### Possible workaround: 
* open lab message preview (eye icon)
* select entire message from top to bottom, preferably **using the mouse** (`ctrl + a` also selects all the text *behind* the lab message, ergo the visible list of lab messages) 
* copy and paste into word processor of choice; formatting should be retained

**Comment by FredrikSchaeferVitagroup** [comment]
I'll be off for a week, so I can't finish this in the next few days. 
Apart from fixing the problems related to what @AdrianMichaelis was kind to provide details of, we should consider sanitizing the generated html (or some part of it)  with [Jsoup.clean(...)](https://jsoup.org/cookbook/cleaning-html/safelist-sanitizer). I tried a little, but could not yet find a satisfying solution.

**Comment by kwa20** [comment]
This is an additional log file from a health department instanc
[Havelland_20210915_labMessage_pdf_logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7243367/Havelland_20210915_labMessage_pdf_logs.txt)

Additionally, we got the following information. Sometimes, specific values or information is not displayed in the html display of a lab message (e.g. CT value). However, these issues don't seem consistent and seem to be present in lab messages of specific laboratories. Potentially, these minor errors from the laboratories cause the subsequent erroneous download? Not sure if I'm going out on a limb here @FredrikSchaeferVitagroup

**Comment by vidi42** [comment]
To be addressed with https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/37
