### ISSUE TITLE
[Import] Error when importing file without selecting the value separator

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6615]
### Bug Description
When user uploads a file and leaves the value separator blank, when he clicks on Start data import, he gets an error.

### Steps to Reproduce

1. Log in with admin user.
2. Try to make an import by selecting the file, but leaving the value separator blank.
3. Click on Start data import.

### Actual Behavior
User gets an error.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/132007300-535f644a-9560-4ca2-8564-a546a752bcf1.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: Admin User

**Comment by roxanamlendea** [comment]
This ticket is related to ticket #5459

**Comment by MateStrysewske** [comment]
Closed because it's being taken care of in the linked issue
