### ISSUE TITLE
[DEMIS2SORMAS] Adjust surveillance reports to also represent laboratory reports

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6621]
### Feature Description

Cases > Surveillance reports

concept issue: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6430
### Problem Description

There is currently no clear association of lab messages to the surveillance reports present in cases.

After the initial implementation of reporting tool interfaces it has also become clear that pathogen tests and surveillance reports are semantically quite different. Therefore, the processing of a message should lead to the creation of a surveillance report based on the respective type to document in the case what has been reported to the health departments.
### Proposed Change

**Surveillance report form:**

- Reintroduce the value `LABORATORY` (Caption: "Laboratory") back into reportingType in Surveillance Reports
- Add an `externalId` (Caption: "External Id")field (non-editable because this should not be changed by a user)
- Rename 'Facility region' to 'Reporter facility region'
- Rename 'Facility district' to 'Reporter facility district'
- Rename 'Facility type' to 'Reporter facility type'
- Rename 'Facility' to 'Reporter Facility'
- Rename 'Facility details' to 'Reporter facility details'

### Additional Information

- via DEMIS for SurvNet mapping can be inferred depending on referenced messages

![Create new report](https://user-images.githubusercontent.com/70317594/176464626-4c9a6cd4-c6d2-4579-804c-99cd5bee9e2b.png)

![Edit report](https://user-images.githubusercontent.com/70317594/176464647-30b29f82-a040-4f96-9b88-b49176b91456.png)

![Report entry](https://user-images.githubusercontent.com/70317594/164256093-a4806e44-b487-413e-bde1-642ef4259c40.png)

Goes in conjunction with https://github.com/hzi-braunschweig/SORMAS-Project/issues/9680

**Out of scope:**

**External messages**
- Add an `externalId` column to the table
- Fill the `externalId` with the `NotificationBundleId` of the respective DEMIS notification
- Map the `NotificationBundleId` from the `externalMessages.externalId` to the `surveillanceReports.externalId` when processing a DEMIS notification

**Comment by kwa20** [comment]
The NotificationBundleId of DEMIS notifications needs to be covered in this issue as well

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.77.0-SNAPSHOT (5d603ac)
