### ISSUE TITLE
Disease variants prevent case merging

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6628]
### Bug Description

When trying to merge cases where one has a disease variant and the other one doesn't, an unexpected error occurs.
### Steps to Reproduce

1. Create duplicate cases where one has a disease variant and the other one doesn't
2. Merge the cases with the case not having the disease variant being the leading case

### Expected Behavior

Merging should work and the leading case should adopt the disease variant of the case that is being discarded.
### Screenshots

<img width="856" alt="mergeError" src="https://user-images.githubusercontent.com/70317594/132192250-eadb7c4a-d437-48d2-847c-38d6e862f610.PNG">

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: firefox
* Server URL: test1402-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.64.0-snapshot on local environment
