### ISSUE TITLE
[Angular] Stats Page (Filter section) [8]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6634]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/069D5414-8D37-4848-90A9-08162ECCAD3B
- This task will only handle the left hand side, filter section (adding new filters, deleting, adding tags, removing tags, etc)
- @cristinacoza , please include the "add filter" design of the expanded filters view
- This task need to be implemented by paying close attention to the current implementation in the Sormas Legacy

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
Design updated

**Comment by cristinacoza** [comment]
UI/UX review done - Everything looks good!
