### ISSUE TITLE
[Angular] Stats Page (base line structure) [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6635]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/1K4W7D5
- This task only refers to the baseline structure of the page, the stats page (module), the left hand container (for filters), the right hands container (map, graphs) - All components should be empty
- This task should also include the "Database export" sub-page (empty)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
