### ISSUE TITLE
[Angular] Stats Page (Database export sub-page) [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6636]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/C4CEBC12-C363-4437-AC43-068E326C6B56
- This task should also handle the selection actions (all, sormas, etc)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
Design updated

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
