### ISSUE TITLE
[S2S] Data is not pseudonymized in share request preview

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6640]
### Bug Description

When viewing pseudonymized data that was shared in the preview, personal data is not actually pseudonymized.
### Steps to Reproduce

1. Share data that includes personal data with another organization
2. Select the fields 'Pseudonymize personal and sensitive data'
3. In the receiving instance, open the preview in the share request

### Expected Behavior

Data should be pseudonymized
### Screenshots

<img width="187" alt="reSharePseudo" src="https://user-images.githubusercontent.com/70317594/132241958-cec47219-5636-430e-aece-4eaad51ca214.PNG">
<img width="458" alt="reSharePseudo2" src="https://user-images.githubusercontent.com/70317594/132241963-098bc1ba-454c-4307-8003-9b34a9b1b37b.PNG">

### System Details

* Device:
* SORMAS version: 1.64-SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de1.sormas.netzlink.com; test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de1.sormas.netzlink.com and test-de2.sormas.netzlink.com
