### ISSUE TITLE
[S2S] Editing entities with handed over ownership automatically returns them

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6643]
### Bug Description

When editing handed over data sets after they have already been accepted, they're automatically returned.
### Steps to Reproduce

1. Send a data set with Sormas A and hand over the ownership. Stay on the form.
2. Accept the data set with Sormas B
3. Edit the data set in Sormas A and save
4. Refresh data set in Sormas B

### Expected Behavior

When the data set has been accepted in Sormas B, the data set should no longer be editable in Sormas A and especially get not automatically returned.
### Screenshots

Sending in Sormas A:
<img width="177" alt="s2sHandingOver" src="https://user-images.githubusercontent.com/70317594/132249485-5a2593cf-70d3-404f-9598-ddc3268c8e5d.PNG">

Accepted in Sormas B:
<img width="598" alt="s2sHandingOver2" src="https://user-images.githubusercontent.com/70317594/132249488-5f7ecd0f-cd8b-4a67-8afa-6eb550b216c7.PNG">

Editing in Sormas A:
<img width="432" alt="s2sHandingOver3" src="https://user-images.githubusercontent.com/70317594/132249490-34b5495a-2edd-43f1-8e07-2330343fbd27.PNG">

Refreshing in Sormas B:
<img width="435" alt="s2sHandingOver4" src="https://user-images.githubusercontent.com/70317594/132249491-3ab7c53c-b940-400f-904b-f8da1733c453.PNG">

Refreshing in Sormas A:
<img width="413" alt="s2sHandingOver5" src="https://user-images.githubusercontent.com/70317594/132249496-391c1981-5fb9-44b3-a164-bb9ea306726b.PNG">

### System Details

* Device:
* SORMAS version: 1.64-SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de1.sormas.netzlink.com; test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de1.sormas.netzlink.com and test-de2.sormas.netzlink.com
