### ISSUE TITLE
Add the person ID in the case & contacts directories and in the contact tab of the case directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#6658]
### Situation Description

To date, the ID_person is only listed in the directory of event participants. This identifier is however essential for reading the viral transmission diagram developed in SORMAS-Stat.

### Feature Description

In order to allow users of the diagram to identify the people represented on the graph, it is essential to have this identifier in the following directories:
- Case directory + "contact" tab of a case file
- Contacts directory

### Additional Information
@ftavin @bernardsilenou @emond-fuseau

**Comment by kwa20** [comment]
I think when implementing this, we should allow navigation via the person Id. This is currently still missing for event participants https://github.com/hzi-braunschweig/SORMAS-Project/issues/4842

**Comment by bernardsilenou** [comment]
@carolinverset @kwa20 
Thats right, we can combine both as one ticket.
To do:
1.  Add person uuid (first 6 characters) as  the second column on the following directories for all view (default,  detailed, followup, ) 
   * case
   * contact
   * event participant (this exist already)
   * samples (only on sample view, not on labmessages)
   *  Entries
   * Immunization
  
2. when user click on uuid, navigate user to the general person form.
      2.1  Even it person tab is not activated on server, this should still navigate to the person form.
     2.2 While in person form, person tab is not activated and user click on "person list", show a popup message in forming user that this is not possible, eg "The person directory is not activated on your server, please contact your admin"
3. When mouse is placed on uuid on any directory, show the complete uuid ( this exist already)

**Comment by bernardsilenou** [comment]
@kwa20  Please have a look if i missed something
If entries and immunizations are not available on all instances before adding this issue in a sprint, then we may need to move them to another issue.

**Comment by bernardsilenou** [comment]
@MateStrysewske Is point 4 necessary or there is no risk of adding person uuid among the general search?

**Comment by Marko-ilmkreis** [comment]
>     1. Add person uuid (first 6 characters) as  the second column on the following directories for all view (default,  detailed, followup, )

The directories are having a lot very useful informations, but I see that the basic informations like Name, Firstname and dob are more and more switching to the right. On smaller screens (we do have colleagues with a 17" screen, digitalization you know :-) )In my opinion we should discuss which of the external token, external id and internal token are needed for every user?
Maybe it is for a new issue. The best solution would be that every user can hide unneeded rows, but that sounds like magic.

**Comment by MateStrysewske** [comment]
@bernardsilenou Please don't add additional features to this issue that don't really have anything to do with the original feature request; e.g. point 4 is a totally new feature that should have its separate issue. I'm not sure whether it's a better idea to add a new UI element or integrate it into the existing text filters, that would be an open point of discussion.

**Comment by bernardsilenou** [comment]
@MateStrysewske  
I thought the same before adding it here. The reason whey i  added it was because if users know that a person is a case (based on colour of node on network diagram), they may directly want to search for the case on case directory. If they go through the person form, then may still need to filter by disease in order to get to the right case as shown on network diagram, thus many steps. I would further discuss it with @carolinverset and @ftavin to decide if we create another issue

**Comment by bernardsilenou** [comment]
@Marko-ilmkreis  With the coming angula ui, users would have the option to hide and show only columns that they need. The limitation that i still see is that if the user shutdown their PC and connect another day, it gets back to normal. A second point is that they can not choose the order of the columns but just hide some of them.
I do not know how we can address this because the columns to show and order is not the same for all users. Adding a directory configuration for each users is also huge task to do.

**Comment by kwa20** [comment]
@bernardsilenou In Sormas, we display the case uuid on the diagram. Is there a reason why we use the person uuid in SormasStats instead?
<img width="332" alt="networkDiagramId2" src="https://user-images.githubusercontent.com/70317594/132684787-5ed74631-d9be-42a5-8734-5ef538201b40.PNG">
<img width="240" alt="networkDiagramId" src="https://user-images.githubusercontent.com/70317594/132684807-beb24152-9ad1-4e0f-be0a-edbb883e660e.PNG">

**Comment by bernardsilenou** [comment]
@kwa20  Sorry i did not add the context of the issue.
The updated script is based on person uuid and also included events and ep in the chain of disease transmission, this helps users to know who are the green people. the script is used in sormas-stats but we would soon migrate it to main sormas.

**Comment by bernardsilenou** [comment]
- Since all the points mentioned in this issue can not be implemented in one step, I would then create another issue for what would be done in the current sprint.
- In order to be consistent with other directories, we decided to keep the person uuid on the left and later design a feature to permit each user to define the column names to show and also their order.

**Comment by kwa20** [comment]
@MateStrysewske @carolinverset I tested on the nightly build servers and we noticed that when double clicking the row for cases and contacts on respective directories, the user gets navigated to the case person or contact person tab. This should not happen. I think these adjustments are still necessary please:

- double clicking on a row or pressing the case uuid/contact uuid should navigate the user to the case/contact tab
- Clicking the person uuid should do the following:
    - If `PERSON_MANAGEMENT` = t, navigate the user to the person entity that can be accessed through the person directory
    - If `PERSON_MANAGEMENT` = f, navigate the user to the case person/contact person form in the case/contact entity respectively

**Comment by bernardsilenou** [comment]
@kwa20 
- We decided not to implement the navigation based on person management, ie 'PERSON_MANAGEMENT = t'. I forgot to specify that we would not implement it in this  this issue.
- If this is absolutely needed, then we can create another issue for it please.

**Comment by kwa20** [comment]
@bernardsilenou Ok, we should however fix the double click problem, please.

**Comment by bernardsilenou** [comment]
@kwa20 
I do sigle/double clicked on case id and I was navigated to case form, same for contact on https://test.sormas.netzlink.com/sormas-ui/
Please can you test again?

**Comment by kwa20** [comment]
@bernardsilenou The ID is fine but the whole row if double clicked navigates to the case/contact person. Only the person Id should do so. If you double click the row in places without a link, it should navigate to the case/contact tab

**Comment by bernardsilenou** [comment]
@kwa20 How I could reproduce it. That is right, we can fix it in this ticket.
@aponcon-atolcd Please can you have a look at it?

**Comment by ftavin** [comment]
@bernardsilenou @kwa20 
@aponcon-atolcd will not be available to work on this change before next monday. Can someone in your team handle it ?
