### ISSUE TITLE
externalToken does not get regenerated if deleted

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#6663]
### Bug Description

Related to https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/235

> When the external Token is deleted (e.g. because a duplicate exists), sending the case to SurvNet again to generate a new one produces an error rather than generating a new token.

### Steps to Reproduce

1. Create a new case
2. Send the case to SurvNet
3. Check the generated Token
4. Delete the Token and save the case
5. Re-send the case to SurvNet

### Expected Behavior

Whenever the externalToken is null, a new Token should get generated upon sending and not produce an error.

### Screenshots

<img width="517" alt="externalTokenDeleteError" src="https://user-images.githubusercontent.com/70317594/131569333-665f23cb-6cfa-4852-a538-92d3d59231dc.PNG">
<img width="458" alt="externalTokenDeleteError2" src="https://user-images.githubusercontent.com/70317594/131569335-be28fae4-3649-412a-9ee8-a92eb3b09d9c.PNG">

### System Details

* Device:
* Version: 8.3.1 / 1.62.3; 1.63.0
* Server URL: int-sormas-x.sormas.netzlink.com / test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version deployed on test-de1.sormas.netzlink.com environment
