### ISSUE TITLE
follow-up date changing 

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#6671]
### Bug Description
only for Contacts:
When we set a  quarantine date, the followup-date will set automatically.
After change the quarantine-date to a previous date, we can't change (overwrite) the follow-up date (to the same previous date) and get the following message:
![image](https://user-images.githubusercontent.com/79255722/132641174-e4bb57ec-2b9f-4613-a73b-cac1dfcf6dc4.png)

I'm not sure it's a bug or something i not understand.

### System Details

* SORMAS version: 1.62.3
* User Role: Admin, national user

**Comment by MateStrysewske** [comment]
Does this message appear automatically or only when you manually try to set the follow-up date? In general this behaviour is intended because SORMAS does not allow the follow-up period to be shorter than the recommended follow-up period for the case disease (for epdemiological reasons).
