### ISSUE TITLE
It should not be possible to create a person without sex via ReST [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#6673]
### Bug Description
Based on #6248 sex is now consistently a required field in web app and mobile app.

Unfortunately it's still possible to push a person without sex into the system via ReST. We should either validate the dto properties based on their annotations or at least make the field also required in the database.

### Steps to Reproduce
1. Use a tool like postman to send a person with first and last name only, to the ReST interface.

### Expected Behavior
Should not work, because the sex is missing.

### System Details

* SORMAS version: 1.64.0-SNAPSHOT
* Server URL: .../sormas-rest/persons/push

**Comment by MateStrysewske** [comment]
We can and should also add backend validation to the `savePerson` method
