### ISSUE TITLE
[Angular][SPIKE] Investigate and map out all the remaining work needed for the BE [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6674]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Create a txt file which contains:
- 1. Implement endpoints (already done) (also mention if additional work / improvements are required) 
- 2. Pending implementation (still to be done)
- @laurentiustanvitagroup will handle formatting and updating the documentation on confluence.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by danielrus** [comment]
DASHBOARD

1. Surveillance
- get disease overview (per filters provided)
- get new cases
- get new events
- get test results
- provide data for epidemiological curve chart
- provide data for map

2. Contacts
- get contacts overview
- get under follow-up (same request with filter?)
- get stopped follow-up (same request with filter?)
- get visits overview
- provide data for summary (contacts per case, in qurantine, etc)
- provide data for epidemiological curve chart
- provide data for map
- provide data for disease transmission chain


TASKS
- export functionality (basic & detailed are generated download links; custom export is a form to pass desired configuration)
- archive (bulk action)


PERSONS
- export functionality
- set missing geo coordinates


CASES
- import cases (line listing / detailed import)
- export functionality
- line listing (?)
- merge duplicates functionality
- search specific case (i don't know how/if this differs then normal filtering)
- archive (bulk action and per case)
- share (bulk action and per case)
- create quarantine order documents (bulk action and per case)
- link case to event (bulk action and per case)
- calculate case classification (this could be frontend if rules are provided or backend)


mSERS
- get list of aggregate reporting (msers)
- create msers
- export functionality


CONTACTS
- export functionality
- line listing
- import contacts
- merge duplicates
- cancel follow-up (bulk action)
- set to lost to follow-up (bulk action)
- share (bulk action and per contact)
- create quarantine order documents (bulk action and per contact)
- link to event (bulk action and per contact)
- profile right sidebar -> get documents /add document / delete
- follow-up visits tab -> new visit, delete (bulk action), export


EVENTS
1 Events
- import functionality
- export functionality
- search specific event
- archive (bulk action and per event)
- profile right sidebar -> get documents /add document / delete
- subordinate event (?)

2. Event participants
- add participant
- create contacts (bulk action)
- delete (bulk action)
- create quarantine order docuemtns (bulk action)

3 Event actions
- get list and get documents for an action -> these were done i think, but we need details how it works and to integrate it with frontend
- add / edit / delete event action


SAMPLES
1. Samples
- export functionality

2. Lab messages
- get list
- get by id
- process lab message
- delete (bulk action and per lab message)
- mark as unclear & mark as forwarded fnctionalities


IMMUNIZATION
- get list
- get by id
- add / edit / delete immunization
- archive immunization


SHARES
- get list
- get by id
- accept & reject functionalities


REPORTS
- get list of reports
- get by id


STATISTICS
1. Statistics
- generate stats based on provided filters
- export functionality

2. Database exports
- export functionality (for selected data)


USERS
- sync users functionality
- enable / disable users (bulk action)
- create new password


CONFIGURATION
- import functionality (for all)
- import default for continents, subcontinents and countries
- export functionality (for all)
- archive (continents, subcontinents, countries, regions, districts, communities, facilities, points of entry -> bulk and per item)


ADDITIONAL
1. Provide an initial configuration object, with data specific to active instance (eg: German instance, international instance etc)
2. Retrieve / update profile for logged in user(to save customized views for directories - task #6957)


Note: some of the functionalities repeat themselves in multiple places, such as archive or import / export. I don't know if the BE needs to treat them separately or they go together.
