### ISSUE TITLE
[Angular] Events Grouping List + Filter [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6675]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference:  https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/3OPd9wa
- We will need to integrate the "View options" sections where the user can select the "Groups" view
- When clicking on "Groups" a redirect will be made to the Even Group section which will contain like the rest, list, filters, etc (similar to a new entity).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
