### ISSUE TITLE
[S2S] Introduce Sormas 2 Sormas user rights and role

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6679]
### Situation Description

Currently, there are no rights restricting the access to the S2S feature. This is problematic for users because not all users should have access to this feature and they would like to restrict it to specific users only. However, these rights should not be given to existing users but rather another user should be created for this to be added to other ones. in combination
### Feature Description

- Add a user role called Sormas to Sormas User - this role should be able to be combined with any role that has access to any datatype able to being shared
- Add the following rights and grand them to this user
    - `SORMAS_TO_SORMAS_VIEW` - Allows users to view but not edit, share or accept/reject any data; includes the share menu in general
    - `SORMAS_TO_SORMAS_ACCEPT_REJECT` - Allows users to accept or reject share requests

- Reassign `SORMAS_TO_SORMAS_SHARE` to the new user only

**Comment by bernardsilenou** [comment]
@kwa20  What about just adding this right to the current surveillance ( and admin surveillance)  supervisors and national users ?

**Comment by kwa20** [comment]
@bernardsilenou This wouldn't suffice because not all supervisors or other roles should have these rights.

**Comment by bernardsilenou** [comment]
@kwa20 Ok,
Whats the reason of preventing supervisors to have such a right?

**Comment by kwa20** [comment]
@bernardsilenou On localized systems (e.g. in Germany), many users have supervisor roles because they need the associated rights. Since this includes almost all users on the system, all would have access to this feature. This is highly undesired by users and therefore, decoupling these rights is very important. This will also be resolved by the user rights concept but this issue will likely proceed the full implementation. The rights are nevertheless needed.

**Comment by JonasCir** [comment]
There is already an S2S role AFAIK. Can you explain why it is not sufficient and what we would need to change?

**Comment by kwa20** [comment]
@JonasCir The current Sormas To Sormas Client user role is only used for interface configuration and does not affect actual content-related rights. These are still needed to manage access amongst users actually used by real persons.

**Comment by Jan-Boehme** [comment]
New rights are defined in the reworked description of S2S and will be part of another issue. This one can be discarded.
