### ISSUE TITLE
Increase SORMAS api library java version to 8 [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#6686]
### Feature Description
The SORMAS API library is currently using Java 7 instead of 8 in order to be usable by the Android project.

### Problem Description
As a result, we can't use the Java 8 API and language features. Most importantly function pointers and streams.

### Proposed Change
The Android Gradle Plugin version 4.0.0+ allows us to use most of the Java 8 API through desugaring: https://developer.android.com/studio/write/java8-support

This means we can:

- [x] increase the Java build version of SORMAS API to 1.8
- [ ] ~~Replace joda time by Java time~~ -> #6700

**Comment by MartinWahnschaffe** [comment]
When working on this use the existing branch https://github.com/hzi-braunschweig/SORMAS-Project/compare/change-6686-sormas-api-java-8

**Comment by StefanKock** [comment]
Discussed in Sprint Planning: split the replacement of `joda-time` out as a seperate ticket because it needs to be also removed in the `backend` and `vaadin-app`. Check within this ticket, that Android in the targeted base version allows to use java.time API.
