### ISSUE TITLE
Problem with the "responsible user" search filter in the events directory

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#6708]
### Bug Description
Entering a responsible user in the corresponding search filter does not result in the correct selection.
The system uses the name entered to search not in the "responsible user" field but in the "reporting user" field

**very penalizing because users can no longer find the events they have to investigate !!**

### Steps to Reproduce

1. add a responsible user in the research field "responsible user"
2. apply the filters
3. the filter is KO : the directory is filtered on the "reporting user" field and not "responsible user"

### Screenshots

![image](https://user-images.githubusercontent.com/65449450/133421058-469f91f8-0133-4e91-b055-c2b4401f8c0f.png)

### System Details

* Device:
* SORMAS version: 1.62.3
* Android version/Browser: chrome
* Server URL:
 https://sormas.bfc-sante.fr/
 but also 
 https://test1401.sormas-oegd.de/sormas-ui/#!users
* User Role: admin

### Additional Information
@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
@carolinverset  We would have a look at it, thanks

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com

**Comment by carolinverset** [comment]
@bernardsilenou @aponcon-atolcd @MateStrysewske @ftavin

I am sorry to return to this closed issue. 
I tested the big fix on the server https://test1401.sormas-oegd.de/sormas-ui/#!users and unfortunately the filter doesn't seem to work. I do not manage to reduce the directory of events to those for which I am in charge. Maybe I am making a mistake?

**This bug is really annoying for French users who mainly work on the events part. Is it possible to take a quick look?**

Thank you very much ! 

![image](https://user-images.githubusercontent.com/65449450/140293574-2815426f-ede1-48d4-94c1-f617cf06c027.png)

**Comment by MateStrysewske** [comment]
@carolinverset Hey! The filtering logic is a bit problematic here apparently. You have to expand the filters and select a region first before you can filter by responsible users. The filtering should work then, but the workflow is definitely not good. I've opened an issue for it: #7150
