### ISSUE TITLE
Fix failing AndroidTests

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#6714]
### Bug Description
A number of android tests fail
![androidTests2](https://user-images.githubusercontent.com/5616564/133510408-e03b0d1f-231c-4d23-a159-583ddef76ccb.png)
![androidTests1](https://user-images.githubusercontent.com/5616564/133510413-d7f694a5-c8c9-4eea-a33c-23fd806e9418.png)

Some of the tests do not reflect the current state of the implementation:
- `CaseBackendTest..shouldUpdateCaseAndAssociatedEntitiesOnMove()` manipulates `Case.district`. However, task reassignment is triggered by a change of `Case.responsibleDistrict` or - if `responsibleDistrict` is null, which is not the case here - by a change of `district`. Thus, neither assignment of a new `surveillanceOfficer` nor a reassignment of tasks occur in the course of the test. Equallly, hospitalizations are not updated as expected in the test.

Some of the tests fail depending of other tests run before:
- `CaseBackendTest.shouldCreateCase()` succeeds in the first run with no tests run before, but fails in a second run.

### Steps to Reproduce

Run android tests in android studio, either one by one or all together

### Expected Behavior
Android tests should succeed, test result should be independent of other tests run  before.
Database and other persistent states should be cleaned and prepared before each test.

### System Details

* Device:
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by vidi42** [comment]
Running the android tests from Android Studio one by one work, but when running them in bulk only the first one works and all the others
```
Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
at com.j256.ormlite.android.AndroidDatabaseConnection.update(AndroidDatabaseConnection.java:316)
... 38 more
```

Changing the `initTest` method of a class to be ran `@BeforeClass` does fix some issues, but introduces others.

Shouldn't this have been addressed with this issue?

**Comment by syntakker** [comment]
Annotating `initTest` with `@BeforeClass` instead of `@Before` makes tests in a class dependent on each other, since the database state is not cleared/reinitialized between these tests.
From the logs, the problem seems to be that writing to the database fails altogether.
What's the setup you're testing with?

My setup - for which the tests succeed - is:
- AndroidStudio
- running emulator, configured via AVD manager: 10.1"  WXGA (Tablet) API 28, Android 9.0 x86 (Pie)
- API and SDK versions from the current state of the `development` branch:
```
    compileSdkVersion 29
    // always use the latest
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "de.symeda.sormas.app"
        minSdkVersion 24
        targetSdkVersion 29
        versionCode buildVersionCode()
        versionName "$sormasVersion"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        setProperty("archivesBaseName", "sormas-$versionName")
        multiDexEnabled true
    }
```

Result:

```
Testing started at 2:56 PM ...

10/01 14:56:57: Launching 'Tests in 'de.symeda.sormas.app'' on 10.1  WXGA (Tablet) API 28.
App restart successful without re-installing the following APK(s): de.symeda.sormas.app.debug.test
Running tests

$ adb shell am instrument -w -m    -e package de.symeda.sormas.app -e debug false de.symeda.sormas.app.debug.test/androidx.test.runner.AndroidJUnitRunner
Connected to process 10976 on device '10.1_WXGA_Tablet_API_28 [emulator-5554]'.

Started running tests

Tests ran to completion.
```

**Comment by syntakker** [comment]
In case you're working on #6665: Might this be related to this commit:
https://github.com/hzi-braunschweig/SORMAS-Project/commit/b9011c602771bf5c63a41f95851e19b24ec18cf4
i.e., are you testing with API 24?
Second, the PR has only be merged yesterday, so have you updated your branch accordingly?

**Comment by vidi42** [comment]
@syntakker since the `minSdkVersion` supported is 24 I think this shouldn't be an issue. But I anyway tested locally with API 24 and 29 with the same results.
Also the PR which fixes the tests was merged into the testing branch.
