### ISSUE TITLE
Task reassignment in Android app differs from Vaadin app

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#6715]
### Bug Description
In the Vaadin app, task reassigment is triggered by a change of any infrastructure related to a case (see `CasefFacadeEjb.updateTasksOnCaseChanged`). In the Android app, however, tasks are reassigned only if a case's `responsibleDistrict` or `district` is changed (see `CaseDao.onCaseChanged`).

### Expected Behavior
Both implementations should behave consistently. Additionally, tests should reflect the intended behaviour (see also #6714)

Please make sure that the implemented behaviour is depicted by a meaningful test (see `CaseBackendTest.shouldUpdateCaseAndAssociatedEntitiesOnMove`).

### System Details

* Device:
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe I'm wondering whether we should do task reassignment in the mobile app in the first place, or only do it when the task is synchronised to the web app. I think we should discuss this.

**Comment by MateStrysewske** [comment]
@syntakker Clarified with Martin - task assignment is required in the mobile app and should be consistent with the web app (as you said).
