### ISSUE TITLE
link in lab message broken

### ISSUE THREAD

**Issue by herrling-LRA-KYF** [hzi-braunschweig/SORMAS-Project#6761]
### Bug Description
In the labour message the "jump to top" link just opens the dashboard in the background.

### Expected Behavior
When tap on the "jump to top" link, i want to jump to the top of the labour message.

### System Details
* SORMAS version: 1.63.1

**Comment by FredrikSchaeferVitagroup** [comment]
This bug is covered in [#33](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/33) (see 1.).
There has no solution been found to keep the links without reloading to the dashboard in the background, so the internal links will probably be removed completely.
