### ISSUE TITLE
[Events] Error when click on Events tab

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6763]
### Bug Description
The system gives an error when trying to open the Events tab.

### Steps to Reproduce

1. Click on Events

### Expected Behavior
The Events tab should open and the Events Directory should be displayed

### Actual Behavior
An error occurs.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/134311470-31a8384a-1b3a-45e1-9921-3440cb7bc848.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com , test-de.sormas.netzlink.com , test-de1.sormas.netzlink.com
* User Role: NatUser, Admin

**Comment by syntakker** [comment]
@roxanamlendea could not reproduce.
Tested on my local machine, on test.sormas.netzlink.com and on test-de.sormas.netzlink.com, each with NatUser and Admin.

**Comment by roxanamlendea** [comment]
This is weird, now it's working just fine. Yesterday I couldn't open the Events tab all day long on all the environments.

**Comment by AliciaRaber** [comment]
Please check if this issue can be marked as solved because actual vesion is 1.70.2

**Comment by roxanamlendea** [comment]
> Please check if this issue can be marked as solved because actual vesion is 1.70.2

The issue has been discarded because it wasn't reproducible anymore.
