### ISSUE TITLE
[Angular] Configuration - Facilities [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6766]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- This task refers to the entire page (including the filter)
- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/zxzMdPM
- We will ignore the right hand side buttons (Add new countries, export...)
- **NOTE:** We need to discuss with @marius2301 and see if we have some BE endpoint that returns info for "Facility category" and "Facility type". If it's already implemented on the BE we can use it in the FE.
- **NOTE 2**: We should also handle the left hand side filters (manage to populate the filters where we have the info supplied by the BE).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review Done - everything looks good
