### ISSUE TITLE
[Angular] About us Page [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6777]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/jgDramD
- We will implement the links considering that they would be external links (@cristinacoza please check for @MateStrysewske and report back what are the exact url's we need for the links).

![1x Map About page](https://user-images.githubusercontent.com/78347216/134636966-f1239140-3250-42cf-9795-a4c1054f18fb.png)
![2x Map About page](https://user-images.githubusercontent.com/78347216/134636979-6fd65f14-452b-462c-993a-4b035be52ff7.png)
![giz-logo copy 2](https://user-images.githubusercontent.com/78347216/134639840-f88f36de-2b05-45c6-b356-623af5cd36f4.png)
![hzi-logo copy 2](https://user-images.githubusercontent.com/78347216/134639841-463fe909-fcc7-41e8-b90b-aa660a241d14.png)
![symeda-logo copy 2](https://user-images.githubusercontent.com/78347216/134639878-9b8ed32e-81d8-4ae9-97ae-5c2487acd34f.png)
![sormas-logo-big-text copy](https://user-images.githubusercontent.com/78347216/134640045-de0654e8-45e5-4861-8d5a-15cf8f544748.png)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
