### ISSUE TITLE
Filtering statistics by age intervals is not possible when case count is selected

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#6790]
### Bug Description

Selecting "Case count" in the statistics and then filtering by age intervals other than 5 year intervals is not working right now. Instead, the error message "Case incidence proportion can only be generated..." is shown which should only happen when "Case incidence" has been selected as the data displayed.

### Steps to Reproduce

1.
2.

### Expected Behavior

Allow filtering for all age intervals when "Case count" is selected.

### System Details

* Device:
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.65.0-SNAPSHOT
