### ISSUE TITLE
Selecting a hyperlink while viewing DEMIS lab messages leads to opening/reopening the surveillance directory in the background

### ISSUE THREAD

**Issue by mbin7865** [hzi-braunschweig/SORMAS-Project#6798]
### Bug Description
When selecting any hyperlink in the content section or "--> back"-link of a lab message, the surveillance directory is opened or reopened, respectively, in the background. Upon closing the lab message, the back function of the browser is not available.
The problem was reported since the update to version 1.63.1

### Steps to Reproduce
1. open the lab messages directory and view a lab message via the eye icon
2. click on any hyperlink in the content section ("inhaltsverzeichnis") of the lab message 
    OR any of the links "--> nach oben" in the lab message
3. EACH TIME one of the above hyperlinks is selected, the surveillance directory in the background is opened / reopened
4. after closing the lab message, the back-button of the browser is not available

### Expected Behavior
While viewing the lab message, selecting links in the message should not change the directory in the background and not loose the back-button function

### System Details
* Device:
* SORMAS version: 1.63.1 / 8.3.1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by FredrikSchaeferVitagroup** [comment]
Was fixed with [#35](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/35). The links causing this behaviour were removed.
