### ISSUE TITLE
Error message do not suggest the cause of error

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#680]
When a surveillance officer  register a sample and ship without filing the name of the assigned lab,   the error message "sample could not be saved because of an internal  error" appears on the screen of the mobile app, This error message does not tell the user anything about the reason why the sample could not be saved, It will be good if the error message can suggest the reason/field  causing the sample not to be able to save. This   happens to other required field in different sections of the app.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou I expect this is in the 1.0 version of the app? 
These are unexpected errors - so it's basically impossible to show an error dialog to the user. These errors simpy have to be fixed.
