### ISSUE TITLE
Overwrite follow-up until date checkbox is still displayed if the follow-up is canceled

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#6803]
### Bug Description
Overwrite follow-up until date checkbox is still displayed if the follow-up is canceled

### Steps to Reproduce
1. Open Sormas app
2. Create a new Contact or edit any existent one
3. Make sure that Follow-Up Status is set to:  Canceled follow-up
4. Check **Overwrite follow-up until date checkbox**

### Expected Behavior
Overwrite follow-up until date checkbox should be disabled if the follow up status is canceled.

### Screenshots
![followUpdate](https://user-images.githubusercontent.com/83643843/134673053-abac600b-08af-4bb2-9a61-8399ff7d69b1.gif)

### System Details

* Device: Chrome
* SORMAS version: 1.64.0
* Android version/Browser: 93.0.45
* Server URL: https://test-performance.sormas.netzlink.com/sormas-ui/#!contacts/data/2d6e40fd-75d3-49c1-bb7a-1539421441ed
* User Role: National User

**Comment by rdutu-vg** [comment]
Relates to: 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/5634

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.65.0-SNAPSHOT on environment test-de.sormas.netzlink.com and test.sormas.netzlink.com
