### ISSUE TITLE
Create an automatic test that compares tables with their _history equivalent [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#6822]
### Proposed Change

This is a follow-up to #6121. @StefanKock had a quick try to create an automatic test here: https://github.com/hzi-braunschweig/SORMAS-Project/commit/d562850b9b2dafb7054ea358a949319b357d795f unfortunately with H2 this is very difficult (or maybe not possible at all). We should take the opportunity to set-up unit testing with testcontainers.org instead: https://www.testcontainers.org/modules/databases/postgres/

Todos:

- [ ] create an automatic test that executes the provided script and checks whether new/modified columns are missing in the history tables.
- [ ] set-up postgres instance with testcontainers.org
- [ ] This requires docker, so we have to make sure that this is also automatically provided or that tests are at least skipped on dev systems that don't have it. For the jenkins CI this should not be a problem.
- [ ] Make sure this also runs with github actions (should be possible, see https://stackoverflow.com/questions/66174071/github-actions-for-running-test-with-testcontainers-and-gradle)

**Comment by JonasCir** [comment]
I think @syntakker provided a test script this? :)

**Comment by syntakker** [comment]
@JonasCir yes, see `sormas-backend/utils/checkHistoryTables.sql`. The script checks missing columns and missing tables, both queries are combined in a union statement.
