### ISSUE TITLE
Event-Error on creation of persons involved in situation

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#683]
@MartinWahnschaffeSymeda 
@MateStrysewskeSym @Chinedar @foyiri 

Whenever an event is created and persons are added to the event by the surveillance officer, the app crashes.
Officer logged in: Jame Doe
Role: Surveillance officer
State: Ebonyi
LGA: Ebonyi
SORMAS version: 0.23.1
Please can you work on this

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
Are events currently created by the surveillance officer in the field?
If not we suggest to ignore this bug for the 0.23 version and only fix it for SORMAS 1.
What do you think?

**Comment by hzi-braunschweig** [comment]
Ok then. Lets make a note of it for SORMAS 1.0


Regards

Tom-Aba Daniel (B.Sc MPH)
Doktorand
PhD Epidemiology Programme, Hannover Medical School (MHH),
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by MartinWahnschaffeSymeda** [comment]
Fixed in the upcoming releease (1.1.0).
https://github.com/hzi-braunschweig/SORMAS-Project/commit/7686880edf57d5c5f5b3882d892eb32b959ff2f4
