### ISSUE TITLE
[Sormas2Sormas][Share] Organization dropdown is empty 

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6853]
### Bug Description
Cannot share cases, contacts, events between S2S because the organization dropdown is empty

### Steps to Reproduce

1. Open a case/contact/event
2. Click on Share
3. Inspect the Organization dropdown.

### Expected Behavior
The organizations should appear in the dropdown and user should be able to select them.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/135583066-308e5fbb-7c0d-4f4d-b651-62c3c24faa09.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de1.sormas.netzlink.com
* User Role: NatUser

### Additional Information
 This also happens on test-de2.sormas.netzlink.com and test-de3.sormas.netzlink.com

**Comment by JonasCir** [comment]
I take a look

**Comment by JonasCir** [comment]
@roxanamlendea Can you try if you can reproduce this?

**Comment by roxanamlendea** [comment]
@JonasCir Apparently this is not reproductible anymore. The dropdown is now populated, but the s2s share is still not working on the test instances. 
![image](https://user-images.githubusercontent.com/89522688/143836641-43507f8e-0c31-43b5-bf34-39a70ee958d8.png)

**Comment by JonasCir** [comment]
Hi @roxanamlendea 
I could not reproduce right now as the deployment is quite unstable right now w.r.t to S2S. Netzlink and I will soon finalize the complete S2S setup and will make sure it will work. I'll get back to the QA team as soon as we have a working environment.

**Comment by JonasCir** [comment]
QA: nothing really to do here, the S2S deployment/setup is actively worked on and I will tell you once it is finished.
