### ISSUE TITLE
Tasks can be assigned to users that do not have access to a case outside their jurisdiction

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6858]
### Bug Description

When assigning tasks of a case to users, the selection allows choosing users which are outside of the cases' jurisdiction.
### Steps to Reproduce

1. Create a case with an admin, national user  
2. Create a supervisor combination role of case supervisor, contact supervisor and clinician and set the jurisdiction to something other than the jurisdiction of the case
3. As the admin, national user, create a task and search for the user you've just create
4. Select the user as the assignee
5. Log in as the supervisor and check for the created task
6. Open the associated link

### Expected Behavior

Tasks should not be able to be assigned to users that don't have access to the respective case
### Screenshots

Admin, national user task creation
<img width="588" alt="tasksUsersOtherJurisdiction4" src="https://user-images.githubusercontent.com/70317594/135605944-bc05399e-0493-44a4-befc-d4c006dbfee8.PNG">

Supervisor configuration
<img width="392" alt="tasksUsersOtherJurisdiction3" src="https://user-images.githubusercontent.com/70317594/135605946-9f301e6f-0949-4d31-ad98-e07c5403d3d3.PNG">

Task Management for Supervisor
<img width="838" alt="tasksUsersOtherJurisdiction" src="https://user-images.githubusercontent.com/70317594/135605941-9ca4ccea-5236-42fe-9b31-174f228de63d.PNG">

Opened case through associated link
<img width="715" alt="tasksUsersOtherJurisdiction2" src="https://user-images.githubusercontent.com/70317594/135605947-7eb1882b-6ec6-4c83-b5a0-62d605be26c9.PNG">
### System Details

* Device:
* SORMAS version: 1.63.1
* Android version/Browser: firefox
* Server URL: schnischu.sormas.bund.de
* User Role: admin, national user; case supervisor, contact supervisor, clinician

**Comment by MartinWahnschaffe** [comment]
Will be fixed with #6867
