### ISSUE TITLE
Add a server property that allows to reduce the follow-up period below the usual threshold [2]

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#6862]
Please note that the development specifications differ from the original specification of this issue.

### Feature Description

Make "Overwrite follow-up until date"  remove the restriction for the minimum length of the follow up period.

### Problem Description

At the moment the local health department  in germany do not always use a 14 day quarantine period. for example if someone can provide a negative test result after five days or the quarantine itself is only scheduled for less than 14 days.

As the people entering the data and setting the quarantine dates are most of the time not the ones doing the follow-up calls they don't really know if the person scheduled for a call really needs to be called or if that person already finished quarantine. 
Due to this reason the people setting the quarantine dates tried to set the follow-up period to a shorter time than 14 days but even when using the "override follow-up until date" checkbox the field "follow-up until" does not allow for a persod shorter than the one configured for the disease server-side.

### Proposed Change

If the user activates the checkbox "override follow-up until date" the restriction on the length of the follow-up period should be deactivated. As the user actively clicks on the checkbox it is safe to assume that setting the period to a shorter time than it should theoretically be is an active decision by the user and not an error.

If the user sets a length that is shorter than the server config states the filed should become blue and a mouse over information should appear with the following text:
"The follow up period is shorter than expected for the selected disease."

Checks for dates in the past or invalid dates should stay in place.

### Additional Information

<img width="606" alt="2021-10-01_14h49_13" src="https://user-images.githubusercontent.com/6122778/135623367-9a613024-09b9-4b60-ab0d-23ffe4e45afc.png">

### Development Specifications
* Add a boolean feature type property called `ALLOW_FREE_FOLLOW_UP_OVERWRITE` and add it to the `CONTACT_TRACING` and `CASE_FOLLOWUP` features; default false
* When the new property == true, for the respective section (contact/case), when the user overwrites the follow-up period and sets a date that is before the default minimum follow-up date, instead of showing a hard error and preventing the user from saving the form, show a soft error (i.e. the light blue field outline and exclamation mark in the web app that is e.g. displayed when setting a temperature in the symptoms tab and not specifying the fever field) and change the text that is displayed to "The follow-up until date should at least be on the day the standard follow-up duration for the disease would end."

**Comment by Jan-Boehme** [comment]
@kwa20 @JaquM What's your opinion on this change request from the german helath departments?

**Comment by kwa20** [comment]
@Jan-Boehme From an epidemiological perspective, we need to encourage the follow-up of cases and contacts for a time after which it is safe to say whether a contact person will be infected or a case person ideally recovered or else. This is based on the incubation period and should stay independent of the quarantine period which is often based on the law and therefore might diverge.

However, I'd suggest to not just change this logic but rather to introduce a property called `freelyoverwritefollowup` which 
- if it is set to `TRUE`, allows to freely overwrite the follow-up but keeps the blue mouseover tip and 
- if it is set to `FALSE`, keeps the hard validation as it is implemented now

default should be `FALSE`
