### ISSUE TITLE
Assigned to user list of task should consider related entities jurisdiction

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#6867]
### Situation Description
Assigned to user list of task depends on some old logic based on district and region, this should be updated that it considers the jurisdiction of the related entity (case / contact / event).
Beside doing this on the UI this should also be validated upon save in the backend.
See bug report for cases : #6858

**Comment by JonasCir** [comment]
### Description
`PredicateJurisdictionValidator::isInJurisdiction` produces an NPE as currently `user.getJurisdictionLevel()`  returns null for `admin` user as the call to `isInJurisdictionByJurisdictionLevel`  is not null-safe.

### How to reproduce?
1. Pull latest `development`
2. Build and deploy
3. Login as `admin`
4. The dashboard will not load and throw an error

**Comment by MartinWahnschaffe** [comment]
There are two things missing:

- [ ] call setJurisdictionLevel(UserRole.getJurisdictionLevel(userRoles)); when creating default users in startupShutdown
- [ ] Add not null constraint to users jurisdiction level, to identify these problems in the first place
