### ISSUE TITLE
Discrepancy betweeen caseage and approximateage [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#688]
Some cases have approximateage but missing values for caseage. Others have applroximate age but 0 for caseage. The apprximate should be the applroximateage at date of  creation (caseage) + number of years since the creation date.

**Comment by MateStrysewskeSym** [comment]
@bernardsilenou We have added the reference date for the age of a person in #935. But it may be better to go with the idea suggested in #592.

**Comment by MartinWahnschaffeSymeda** [comment]
Question from Bernard related to this: 

> "I wish someone help me clarify the meaning of the following age variables that occurs in "case table" and also some in "person table"
> "approximateage" (Is this the approximate age of the person that changes with time ?) 
> "approximateagetype" ( take values 1/0)
> "caseage" (from case table, is this the fixed age of the case at creation time?)"

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou 

The approximate age type should actually have values like “DAYS”, “MONTHS”, “YEARS”. This seems to be a bug that will be fixed. I have created an issues for this: #1015

The approximate age is relative to the date in approximateagereferencedate column (this has been added lately).

The case age is calculated based on the persons age using the onset date as reference (with fallback to reception and report date). I suspect we should change this and only use the report date as reference for the calculation of the case age. What do you think?

**Comment by bernardsilenou** [comment]
I think we should use onset date and fall back to report date if onset date is missing. For attributes of a case it is better we always use onset date except otherwise

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make sure the case age is calculated the way Bernard has suggest.
