### ISSUE TITLE
Migrations do not correctly run anymore

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#6884]
### Bug Description
On my system, I observe that running SORMAS on a fresh DB does not create all necessary tables anymore. I tested with latest Docker release there all tables get created correctly. On latest development ( and a branch which is ca. 8 days old as of now) quite a lot tables are not correctly created/created at all.

### Steps to Reproduce
1. Run a SORMAS build from `development` against a fresh and empty postgresql DB
2. Connect to the DB and see that e.g., table `systemevent` is not present

### Expected Behavior
All necessary tables get created.

### Additional Information

![not_working](https://user-images.githubusercontent.com/20031875/136028420-fe385848-f4bf-4fe8-8900-d9c855b5c7fc.png)

**Comment by JonasCir** [comment]
QA: Maybe you can shortly try to run a build on development but I couldn't reproduce it

**Comment by JonasCir** [comment]
OK `@TransactionAttribute(TransactionAttributeType.REQUIRED)` did not work

**Comment by JonasCir** [comment]
Agreed, the previous comments are by no means a solution. I'm fine with any change as long as _after_ the call of `updateDatabase` the transaction of the migration is committed.

**Comment by StefanKock** [comment]
Currently this one causes deployment failures

**Comment by MartinWahnschaffe** [comment]
Problem is caused by the script using the entity manager of the wrong database for audit DB updated. We need to inject the two entity managers into the UpdateQueryTransactionWrapper and find a way to define which one to use.
