### ISSUE TITLE
Hospitalization refinements [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6889]
### Feature Description

Cases > Hospitalizations
### Problem Description

Users often struggle to understand how hospitalizations work and that they are associated to the place of stay of the case. Further, the infrastructure data change pop-up is not very clear to users. To make hospitalizations more user friendly, some changes should be implemented. 
### Proposed Change

- Move the field `admittedToHealthFacility` underneath the 'Current hospitalization' heading and above the 'Hospital name'
    - [x] Make this field permanently enabled; if `YES` is selected, enable all subsequent fields for the current hospitalization section 

- [x] Replace the 'Infrastructure data change' pop-up in the following way:
    - [x] When the place of stay is changed to a hospital, show a new prompt to the user upon saving
        - heading: 'Current hospitalization'
        - Display the Yes/No/Unknown field for `admittedToHealthFacility` and adopt the selection that the user enters to the corresponding field in the current hospitalization
        - Add the following text after the field: _"For adding more details about the hospitalization, go to the hospitalization tab."_
        - Add discard and save buttons as well as 
        - a "save and open hospitalization" button; upon clicking, save the entered data and navigate to the hospitalization tab

    - [x] When YES is selected for `admittedToHealthFacility`, show a new prompt to the user upon saving
        - heading: 'Place of stay in hospital'
        - Add the following text: _"Please select a hospital as the place of stay. If the case is not currently admitted to a hospital as an inpatient, please document hospitalizations under previous hospitalizations below."_
        - Display the jurisdiction of the case; disabled because it's merely for informative reasons
        - Add the checkbox 'Place of stay of this case differs from its responsible jurisdiction, if selected, region and district fields are enabled for the place of stay (cf. to how it already works on the case tab)
        - Add a field called 'Hospital' which only allows the selection of the facility type hospital from the enum. This is basically the facility drop-down field but works exactly as in previous hospitalizations. If 'Other facility' is selected, enable a subsequent free text field for specifying the facility
        - Upon saving, update the case place of stay with the entered data but let the user stay on the hospitalization tab.
### Additional Information

Adjusted Hospitalization form
<img width="438" alt="HospitalizationForm" src="https://user-images.githubusercontent.com/70317594/136084685-a23224fb-55a5-4753-8b9c-4f30a2bbbcac.PNG">

Changing the place of stay to hospital
<img width="561" alt="placeOfStayToHospitalization" src="https://user-images.githubusercontent.com/70317594/136084729-b51713cb-1975-4709-a67e-a5fd1e5148fa.PNG">

Setting admittedToHealthFacility to YES
<img width="606" alt="HospitalizationToPlaceOfStay" src="https://user-images.githubusercontent.com/70317594/136084739-1b40097d-6595-46cd-b5fb-4385bc483a1a.PNG">

**Comment by BarnaBartha** [comment]
@kwa20 Setting admittedToHealthFacility to YES and save of hospitalization form should we save the hospitalization data on the case or only save with the second save with the popup for place in stay in hospital?
Basically the question is should we have two separate saves or we want only one.
If we want one save what should happen when discarding the place of stay in hospital popup, should the hospitalization form changes also be reverted?
In my opinion the first save should save the form and the second handle only the changes for the hospital info, but please confirm if this is wanted.

**Comment by AndyBakcsy-she** [comment]
The Ticket has been validated based on the description (Functionality-wise).
However, reopening the ticket as the following Visual problem could be fixed fast:
![Current_hospitalization_allignment](https://user-images.githubusercontent.com/70562142/137734508-52e66b22-dc27-4403-bc2e-688d36d3c685.jpg)

**Comment by kwa20** [comment]
I encountered some further issues after testing on test-de.sormas.netzlink.com

1. When the place of stay of the case is 'Home' or any other facility but 'Hospital', it is displayed as an '(inactive)' value in the facility enum and the only selectable option. I can only change this by selecting that the place of stay differs from its responsible jurisdiction, which then enables Hospital facilities.
2. The 'infrastructure data change pop-up was not actually replaced but still appears.
3. The place of stay in hospital pop-up does also appear when the place of stay of the case is already in a hospital (I probably missed this in the initial description)
---

1.
<img width="411" alt="placeOfStayHospitalHome2" src="https://user-images.githubusercontent.com/70317594/137853426-9cb614b2-9cc6-477b-91b9-af9051b9d67b.PNG">

2.
<img width="259" alt="infrastructureChangePopUp" src="https://user-images.githubusercontent.com/70317594/137853601-8dff9b18-e696-45fd-a9f1-4d3f2ffb12fd.PNG">

**Comment by kwa20** [comment]
Some further refinements as discussed with @MateStrysewske and @JaquM (feel free to comment if I've missed something)

- make subsequent current hospitalization fields enabled if `admittedToHealthFacility` is not null instead of just `YES`. This is necessary to cover all needed use cases from a variety of users
- disable (read only) responsible region, responsible district and responsible community because they're just displayed for informational purposes
- If 'place of stay of this case differs from its responsible jurisdiction', display hospitals lying in the responsible jurisdiction and also the 'other facility' option
- make region, district, community (if enabled by checkbox) compulsory fields
- make Hospital (facility) compulsory

**Comment by rdutu-vg** [comment]
Found a small defect on this topic.

The Yes/No/Unknown option selected from **Was patient admitted at the facility as an inpatient?** doesn't remain selected after save.

![image](https://user-images.githubusercontent.com/83643843/139903904-87131c53-3be5-4739-bbc5-dc70cb3a54cc.png)

**Comment by rdutu-vg** [comment]
Investigated the issue and the problem might be from the automated tests, because data is generated random for this situation and the same option is selected twice, so this causes flakiness.

**Comment by kwa20** [comment]
The current hospitalization pop up does not hug the content when setting the user language to something other than English


<img width="315" alt="currentHospitalizationPopUpControl" src="https://user-images.githubusercontent.com/70317594/140401331-4d24364b-3d80-4454-b3ca-c31593659bb2.PNG">
<img width="386" alt="currentHospitalizationPopUp" src="https://user-images.githubusercontent.com/70317594/140401333-aa674168-0a13-4fff-a414-4bea4a70acdb.PNG">
