### ISSUE TITLE
[Angular][Backend][SPIKE] Bulk Edit endpoint for tasks [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6908]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need a new endpoint for edits for tasks (replicate how it's currently done on the current Sormas implementation)
- Note: We don't have an endpoint for bulk edit because it wasn't needed in Vaadin.
- Note: Based on the implementation we will do something similar for the rest of the bulk edits.
- After discussing with Marius, we can easily use the same endpoint for simple / bulk edit (as it's the same one). We just need to confirm if this functionality is needed.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by AliciaRaber** [comment]
Hello. I would suggest to implement all options for bulk edit (e.g. enter comment) in order to set a general comment for tasks and set them to status "completed".
I would also suggest to prioritzize this issue.

**Comment by laurentiustanvitagroup** [comment]
@laurentiustanvitagroup to confirm with @MateStrysewske if this should be done or not.

**Comment by MateStrysewske** [comment]
@AliciaRaber @laurentiustanvitagroup The current priority of the Angular team should be to replicate logic that is already part of the Vaadin app (and add comfort features where it makes sense); if there's a desire to enable users to change the task comment via bulk editing, there should be a change request unrelated to the Angular app for it.

This task right here should be limited to implementing the current state of Vaadin application.
