### ISSUE TITLE
Show-More-Filter view often overlapping with buttons

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#6919]
### Bug Description

If you open the "more filters" option, the interface is often dominated by overlapping fields, buttons and cluttered design.

This also happens with events in normal view.
### Steps to Reproduce

1. Open case/contact/event directory
2. Open "show more Filters"

### Expected Behavior

Buttons and Filters or Fields should not overlap.

### Screenshots

![Bug view events](https://user-images.githubusercontent.com/78568406/136771980-25917e03-53fd-42e5-bdf4-a57fb2f04102.PNG)

![Bug View Events overlapping](https://user-images.githubusercontent.com/78568406/136771982-7b80aa34-3b4a-4a6e-bfcb-91aac6d55310.PNG)

### System Details

* Device:
* SORMAS version: 1.64
* Android version/Browser: 
* Server URL:
* User Role:

**Comment by razvancornita** [comment]
This is fixed in the same PR for https://github.com/hzi-braunschweig/SORMAS-Project/issues/7128

**Comment by dragosb-vg** [comment]
Validated on **de1** vs. **release-de** on Version: 1.77.0-SNAPSHOT ([8d282da](https://github.com/hzi-braunschweig/SORMAS-Project/commits/8d282dab3d65d15f5c42a31857005a278879e3de)).

Checked display of 'Show more filters' display for Cases/Contacts/Events:
- collapsed/extended filters
- EN and DE languages
- All views (default, detailed custom per section)
- multiple viewport widths (desktop mode - over 1024px).

Before:
![image](https://user-images.githubusercontent.com/111864167/203814445-7392ef61-efce-4227-9f74-b6a3e2ac0eb4.png)

After:
![image](https://user-images.githubusercontent.com/111864167/203814515-06cf1611-1028-4a8a-bc56-6834d445cf94.png)
