### ISSUE TITLE
Create automated tests to check load time of main pages

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#6921]
In order to measure the performance of pages loading, create automated tests to check if the following pages are loaded in UI to the end user in less than 20 seconds:

- surveillance dashboard
- contact dashboard
- persons directory
-  cases directory
- contacts directory
- events directory
- travels directory
- immunizations directory
- samples directory 
- tasks directory

TO DO:

- [x] @rdutu-vg  to implement tests and reports
- [x] @StefanKock to implement jenkins job to run them
- [x] @rdutu-vg fix jenkins report

Addition by @MartinWahnschaffe:
Ideally we would include this in the JMeter performance tests, but it's not that easy to load the vaadin UI.
Using the existing approach to UI testing instead (and limiting the call to 20 seconds) is a workaround. 
The test reports need to reflect how long the actual call to open the view took, so that we can get an idea on how well the system currently performs.

**Comment by rdutu-vg** [comment]
Created tests and running execution script for them.

The tests are waiting maximum 20s for a page to load.

![allure_run](https://user-images.githubusercontent.com/83643843/137541892-0a948fe7-8d88-472b-a989-a74c9482220f.PNG)

![local_run](https://user-images.githubusercontent.com/83643843/137541905-6923488f-0427-4c0c-b5b2-73532e4d0908.PNG)

I would create a custom HTML report for this to reflect the measurements since they cannot be visible in existent reports.
In this way, we can have a jenkins job to check  the results with 2 reports:
- A report to check time results
- Allure report to check failures and screenshots

@markusmann-vg  @StefanKock  @MateStrysewske  @MartinWahnschaffe  @vidi42

**Comment by rdutu-vg** [comment]
@StefanKock , the publish report jenkins plugin to print the custom report path provided :D

**Comment by StefanKock** [comment]
I installed https://plugins.jenkins.io/htmlpublisher/ and the report is now published.

**Comment by rdutu-vg** [comment]
Looks like the custom report needs some fixes, the images are not displayed and in jenkins job is not showing all run/pages results.

**Comment by rdutu-vg** [comment]
Refactored the report html and building logic.
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7377

**Comment by rdutu-vg** [comment]
Refactored data storage for report building due to rights issue to create files on jenkins machine.
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7381

Report is correctly generated, but we're facing a small problem on Chrome, we can't see the css and images.
https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-RunE2eUiPerformanceTests/
Works on Firefox.

cc: @MartinWahnschaffe  @markusmann-vg  @StefanKock

**Comment by rdutu-vg** [comment]
aded meta fixes, removed commented line, added logger for results clean
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7387

**Comment by rdutu-vg** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7389

**Comment by rdutu-vg** [comment]
Due to jenkins machine limitation, refactored all javascript and  boostrap logic.
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7393

**Comment by rdutu-vg** [comment]
FIxed, data is visible in report, but the css/javascript were removed due to machine CSP settings.
