### ISSUE TITLE
[Angular][Backend][SPIKE] Add case (with the person issue) [1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6923]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- @marius2301 consult with @MartinWahnschaffe if we can have a single call to create the person when the case is created.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by marius2301** [comment]
When adding a new case, the person has to be selected from existing ones that matches the name or it should be created before the new case is saved.

**Comment by cristinacoza** [comment]
UI/UX review done- everything looks good
