### ISSUE TITLE
[Angular][SPIKE]  Test "Edit contact / person / event" and "Add event, travel entry" [1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6924]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- We need to consult the swagger API documentation to make sure what we can use the specific endpoints. @adriandumavitagroup , @danielrus , @sandorbanvitagroup and see if this actually works as it's currently implemented on the backend.

### QA Section

1. What should the QA look for (what was done)
- N/A
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by danielrus** [comment]
For edit:
- contact -> i didn't manage to successfully edit a contact, i always get ERROR
- person -> no luck, i got an error, TRANSACTION_ROLLED_BACK_EXCEPTION
- event -> i was able to edit an event

For add:
- event -> i was able to add event
- travel entry -> i can't create, always get TRANSACTION_ROLLED_BACK_EXCEPTION

The current error handling implementation is not very useful, as it doesn't provide meaningful information. Especially if the frontend doesn't send all the information the backend needs (or if the data sent doesn't match what the backend expects), in which case we get a Bad request message, leaving us with no clue about what's wrong.
At the very least, we need a list of possible error messages (ERROR, TRANSACTION_ROLLED_BACK_EXCEPTION etc) and their meaning.
