### ISSUE TITLE
[Angular][Backend] Disease + disease variant GET endpoints [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6931]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: 
- The disease variant is dependent on the disease
- @laurentiustanvitagroup  or @cristinacoza   to confirm with @MateStrysewske  / @MartinWahnschaffe where do the disease come from (list, config, setting, etc).
- @marius2301 please investigate if there is some way to get the disease variants and if not we will need to create a new endpoint that returns also the variants.
- The disease variants are supplied when a disease (Id or name) is provided. As such we need the call to accept a disease param.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup The list of diseases that are relevant for the server and their associated configurations can be retrieved via the `DiseaseConfigurationFacade`.

**Comment by laurentiustanvitagroup** [comment]
We also need to understand from where do we get the Disease Variants. Thanks!

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup Those are retrieved from the CustomizableEnumFacade

**Comment by laurentiustanvitagroup** [comment]
@marius2301 , please investigate if this is indeed usable as is.
