### ISSUE TITLE
Update automation framework to work on different environments

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#6934]
Currently the automation framework is working only on test-performance environment.
Since it's down, in order to continue fixing tests and creating new ones, also to have it available for other environments, the approach should be changed and enable the framework to use multiple environments and testing users.

1. - [ ] Agree if we'll change the approach of keeping the environments urls & users and passwords in the framework -> @markusmann-vg  @StefanKock @vidi42 @MartinWahnschaffe  @MateStrysewske 
2. - [ ] If we agree, where the data should be stored? 
3.  - [ ]  if we agree, who can help with this from devops side -> TO BE assigned
4.  - [ ]  if we agree, should we refactor or remove the tests where we test the login with each user?
5.  - [ ]  Refactor automation framework code -> @rdutu-vg 
6.  - [ ]   Agree which environments should be used to run the automated tests from Jenkins -> @StefanKock @AndyBakcsy-she @roxanamlendea @markusmann-vg @vidi42 @MateStrysewske @MartinWahnschaffe 
7.  - [ ]   Update Jenkins Job to trigger tests execution over different environments -> TO BE assigned

**Comment by rdutu-vg** [comment]
This topic needs to be addressed since is blocking Netzlink QA Automation team.
@StefanKock  @MateStrysewske @markusmann-vg

**Comment by StefanKock** [comment]
To be investigated:
- **Question**: How to manage test data for one or multiple intances in automated e2e tests?
- **Framework**: Selenium & Rest Assured
- **TEST instances**: Tests running against 24/7 running pre setup instances. 
- **Configurable data**:
  - user credentials for login
  - name/identifiers of objects to link to new data
  - ...

**Comment by JonasCir** [comment]
@rdutu-vg One question, once I have a SORMAS deployment running, how much setup is required to execute the tests?
Is it just running a script?

**Comment by rdutu-vg** [comment]
@JonasCir ,  is running right after, waiting a couple of minutes then is automatically triggered.
For now, we're running the whole testing suite across test-performance. So since there's nothing which can be varied there, the job is simple and runs right away.
