### ISSUE TITLE
[Angular] Configuration - Outbreaks table [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6935]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ELR10g2
- This task should only handle the table view
- When clicking on a cell this should be editable (it should act as a button that opens the modal).
- colour coding of the cell values: 
Font - Subtitle 3 - Roboto, Medium 14,
Status 0 - N400 - #8592A6 
Status Low - P600 - #409FFF , 1%-25% Affected districts
Status Medium - W600 - #FDBA1E , 25%-50% Affected districts
Status Medium high - W800 - #FD7600, 50%-75% Affected districts
Status High - A700 - #D90000, 75%-100% Affected districts

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
