### ISSUE TITLE
[Angular] Configuration - Outbreaks modal [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6936]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ELR10g2
- This task should only handle the modal window
- The user can select any number of districts affected by the outbreak and the total count should then be displayed on the table view upon closing the modal

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
