### ISSUE TITLE
Refactor Dialogs [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#694]
- [x] combine or rename both ConfirmationDialog classes
- [x] replace *OnClickListeners with generic callbacks
- [x] simplify BaseTeboAlertDialog
- [x] check other dialogs
- [x] dialogues that edit entities should only operate on clones (inject this clone into the dialog and then replace it in the list after saving)
- [x] add onCreateClick etc. methods to AbstractDialog (by default only call callbacks), child classes override this method and call super after doing their own stuff
- [x] replace hard-coded icons with config parameter
- [x] possibly get rid of create and cancel buttons
- [x] remove two button panel edge layout and replace all occurences
- [x] add headline separator to InfoDialog
- [x] change headline of move case dialog (-> transfer case)

**Comment by MartinWahnschaffeSymeda** [comment]
@Mate Maybe you can have a look at this one and see what is possible to do in the remaining time

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda 
- [ ] Check why epi data dialogues have bottom margin

**Comment by MartinWahnschaffeSymeda** [comment]
Layout Inspector was quite helpful to investigate on the height problem:
https://developer.android.com/studio/debug/layout-inspector

The additional margin is added by the AlertDialog layout hierarchie (not by our custom layouts). Within the hierarchy one FrameLayout has an additional 32px (burial dialog) or 16px (travel dialog) more height than it's child. There is no padding or margin that explains this. Even when minHeight is manually set to 0 and layout_height is set to WRAP_CONTENT for all components this happens.

Summed up: No idea why this happens. Probably not worth to invest lots of hours on this.

Besides this I found a small bug:
- [x] don't open keyboard or date popup when edit dialog is opened
