### ISSUE TITLE
Make database export consistent [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#6951]
### Feature Description
The database export allows admins to directly export data from the database. It allows the user to select which data to export and displays these options in a way that represents the hierarchy of the data.

![grafik](https://user-images.githubusercontent.com/23217632/149906271-d40e05e3-6757-4122-9e4f-d8eefdb029bd.png)

### Problem Description
Some entities are used as children of multiple other entities (e.g. epi data is used by cases and contacts). When exporting the symptoms of visits the system automatically only outputs the filtered symptoms. When doing the same for cases, it outputs all the symptom entries - also those for visits. 
Also the UI does not refelect the fact that epi data is also relevant for contacts - currently it's only shown below cases. The same applies for a lot of other entities.

### Proposed Change

Don't display entities that are used by multiple other entities as children of those. Instead show them as dedicated entries in the list and don't filter the data.

Implementation tasks

- [ ] Remove the DatabaseExportConfiguration, since it is no longer needed
- [ ] Replace CASE_SYMPTOMS, CLINICAL_VISIT_SYMPTOMS and VISIT_SYMPTOMS with a dedicated SYMPTOMS entry
- [ ] EPIDATA should no longer be a child of CASE

The export view should only display entites that are active on the SORMAS instance based on the feature configuration.

- [ ] Each DatabaseTable value should provide a Supplier that returns whether the database table is relevant based on the configuration of the SORMAS instance
- [ ] For most tables this will be decided based on one or multiple FeatureTypes and whether at least one of them is enabled
- [ ] Once exception is  EXTERNAL_SHARE_INFO, which is defined by ExternalSurveillanceToolGatewayFacade.isFeatureEnabled. Also using SormasToSormasFacade.isFeatureConfigured is probably a better approach then using the feature types directly.
 
Relevant features are: AGGREGATE_REPORTING, CAMPAIGNS, CASE_SURVEILANCE, CLINICAL_MANAGEMENT, CONTACT_TRACING, EVENT_SURVEILLANCE, SAMPLES_LAB, ADDITIONAL_TESTS, TASK_MANAGEMENT, SURVEILLANCE_REPORTS, DOCUMENTS, WEEKLY_REPORTING, IMMUNIZATION_MANAGEMENT, TRAVEL_ENTRIES, LAB_MESSAGES.
E.g. Symptoms would be associated to CASE_SURVEILANCE, CLINICAL_MANAGEMENT and CONTACT_TRACING

- [ ] Introduce a new EXTERNAL DatabaseTableType that groups the following entries: LAB_MESSAGES, TEST_REPORTS, SORMAS_TO_SORMAS_ORIGIN_INFO, SORMAS_TO_SORMAS_SHARE_INFO, SORMAS_TO_SORMAS_SHARE_REQUESTS, SHARE_REQUEST_INFO, EXTERNAL_SHARE_INFO

### Possible Alternatives
~~Make sure children that are used by multiple entities are correctly filtered by their parent. 
In addition we need to implement a solution to also do this for children of those children (e.g. exposures of epi data of cases).~~

**Comment by StefanKock** [comment]
Out of scope for the Sprint, so moved to Refinement board

**Comment by kwa20** [comment]
@MartinWahnschaffe I'm not sure if #7220 would be included in this issue?

**Comment by MartinWahnschaffe** [comment]
@kwa20 Would make sense to have both done by one person, but I'd keep them as separate issues.

**Comment by MartinWahnschaffe** [comment]
@kwa20 I have extended the descriptions, since there where some additional things missing. 
This will take a bit of work (2-5), so I'd like to make sure that this is really what we need.

Can you provide a use case to answer the question who is currently and in the future using the database export and why?

The simpler alternative to all of this is to "stupidly" export all database tables, without taking their relations into account.

**Comment by kwa20** [comment]
@MartinWahnschaffe The main reason is that people use the data to further work with it externally, especially for extensive statistical analyses which are currently not possible in SORMAS. 

> The simpler alternative to all of this is to "stupidly" export all database tables, without taking their relations into account.

This is actually already a request in https://github.com/hzi-braunschweig/SORMAS-Project/issues/6393. In my opinion, this may very well just be one simple button.

**Comment by bernardsilenou** [comment]
- There are users who do not have access to the sormas database backend but have an admin role, thus they wish to be able to export the database with attribute names and class exactly as in the database  #6393. This make sure that third party applications are not broken. Using the current database export that is prone to changes is not efficient.
- There are also user who need the current modified version of the database export whereby some of the tables have been merged.

**Comment by MartinWahnschaffe** [comment]
Ok. I'll refine the issue description and go with the approach of simply exporting all tables without any hierarchy. I'd suggest to keep the option to select which tables to export, though. From data protection point of view it's better to not force users to export everything if they just need two or three tables.

**Comment by kwa20** [comment]
@MartinWahnschaffe Sounds good, both options will be very useful. The entire export could be triggered via a button next to the header.

![entireDbExport](https://user-images.githubusercontent.com/70317594/144990543-ffa08fe6-ac32-4539-9820-be3a6727ed68.png)

**Comment by MartinWahnschaffe** [comment]
Ah, sorry - that was a bit misleading. I meant I would do only a plain export (e.g. without filtering to symptoms of cases), but still allow the user to select which tables should be exported. So you would simply click "select all" and then export.

The whole hierarchy thing is probably not worth the effort if we don't have a clear use case for it.

**Comment by MartinWahnschaffe** [comment]
I have refined the issue to flatten the hierarchy for entities that are used by multiple other entities (like symptoms).
The visible entities will now also be filtered based on the feature configuration of the server.

@kwa20 @MateStrysewske Please have a look at the description and let me know whether it's clear enough.

**Comment by kwa20** [comment]
@MartinWahnschaffe Looks fine to me overall. However, you mentioned a relevant point in the review last time, specifically how we deal with tables that were filled with data at some point because the feature was enabled but then become hidden if the feature is disabled again. Not sure how to handle this.

**Comment by FrankBouillon** [comment]
It's exactly like kwa20 and Bernard are explaning december 6 and 7.
And we defined the demand already in #6393.
And we said also with Mate that a simple - new - button will be OK.
No choice of the tables, no views, juste the tables as they are.
!! Without this damned first line in the files like the actual exports.
And without the 1:n-Relation-Fields of the master table in the "*_visits"-tables.
We try to get a CLEAN DB-export for nearly a year now.
Or give us access to our server instance!
Greeting from Enzkreis/Pforzheim
Frank

**Comment by bernardsilenou** [comment]
@FrankBouillon 
Sorry for the delay.
As you can see, we have this issue in our backlog for sprint 113 and would possibly implement it in this sprint.
Greetings

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.72.0-snapshot on local setup
