### ISSUE TITLE
[Angular] Person details: Add / Edit / Remove Contacts [5] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6959]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference:  https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ELKewZO
- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/bgMm35O
- The inputs refer to the current Contact 
- We need to implement the FE functionality for adding / opening (editing) / deleting a card (also include the modal)
- We will send an array of what was changed (and we will handle the rest upon integrating with the BE)
- The BE integration will be done when we will work on the save functionality

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good except the gray background that will be fixed in a future task that should fix all backgrounds in dynamic form/dynamic form modals
