### ISSUE TITLE
[Angular] Contact type / Risk relationship [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6961]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/7yDmKZw
- If the user changes the contact type then the risk needs to change as per the previous implementation
- After this automatic change, the user can overwrite the risk, by selecting a new value, and the type is not influenced. 

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
