### ISSUE TITLE
[Angular] Delete functionality with backend support [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6964]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- As we have already a lot of endpoints built for deleting, we should implement them on the front-end.
- Please consult @marius2301 and see what are the available end-points
- We need to check the "normal" deletes, the modal ones and bulk delete action.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
