### ISSUE TITLE
[Angular] Configuration - Line Listing [8]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#6965]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/CA843944-9CDD-42A7-8BB7-113F2AD7320A
- Line listing specifications: 
[Line Listing.pdf](https://github.com/hzi-braunschweig/SORMAS-Project/files/7363088/Line.Listing.pdf)

- Please consult the previous implementation for detailed functionality
- "Disable all line entries" removes everything
- The implementation will only focus on the FE and ignore the BE integration for now (maybe hardcode some region + districts)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/Ux review done
