### ISSUE TITLE
Display all data that is not mappable from SurvNet transport file in SORMAS [2]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#6989]
### Situation Description
In SurvNet there are different schema versions with different fields and corresponding values. 
There is the possibility of importing cases, which are created with the schema version 7.0
In the schema version 7 there are fields, that are no longer available in SORMAS - as SORMAS is currentyl mapping schema 8.

Depends on #7068 (backend implementation).

### Feature Description
With this issue we are aiming for a new section that shows also those fields and values which are not mapped in SORMAS.
This approach was already implemented when we imported the travel entries from DEA into SORMAS. 

In the corresponding entities we should add a tab with additional information when there are any, like in the cases details view there would be another tab next to - clinical course | contacts | "additional information"

When we take a look at the current schema publication from the RKI we can see that the fields:

- StandardAdditionalAttribute
- StatusPatientSetting
- GuidPatientSetting
- PatientSettingDetail
- P112InfCol
- StatusContact
- StatusExpo
- Expo0001
- Expo0002
- Expo0003
- Expo0005

were available in Schema 7 and no longer available in schema 8.
In this case, when importing one of the cases with this information, we should display "additional info" and the emlpoyee of the health department can access this information in readonly mode.

It's worth taking a look at the implementation where we imported DEA travel entries and display not mappable fields and values in a SORMAS form in the UI.

**Comment by kwa20** [comment]
@markusmann-vg Is there any way to test this or check the design of this impementation? I don't currently know how to get schema version 7 files since all of our SurvNet test systems have been running from schema 8 onwards
