### ISSUE TITLE
ReferredTo not working for samples in app [1]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#699]
Probably caused by the referring sample being synchronized before/already existing before the referred sample. Likely fixed by only storing the UUID to the referred sample in the app.

- [x] change data model: Replace entity with uuid
- [x] update script
- [x] re-integrate the referral sample to layouts

**Comment by MartinWahnschaffeSymeda** [comment]
Decide whether #494 should be done as well

**Comment by MateStrysewskeSym** [comment]
- [ ] mark referredTo as deprecated and remove getters and setters
- [ ] set referredToUuid to null in fromDto when referredTo is null

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] showing the sample uuid doesn't help,. Replace with sample code (if available) and probably a combination of person epid number and name
