### ISSUE TITLE
Custom exports do not reflect the current epiData / exposure data model

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7001]
### Feature Description

Cases / Contacts > epiData > exposures / activityAsCase
### Problem Description

The epiData sections for cases and contacts custom exports do nor reflect the current epiData and exposure data model

### Proposed Change

Adjust the custom export sections according to the current data model and allow the export of sub tables like exposure and activityAsCase
### Additional Information

<img width="423" alt="customExportWrong" src="https://user-images.githubusercontent.com/70317594/137878553-5fcf4c30-9d8f-41ba-bf76-587b3ad8726d.PNG">

**Comment by markusmann-vg** [comment]
will be covered with #5102
