### ISSUE TITLE
Observers of a task

### ISSUE THREAD

**Issue by ftavin** [hzi-braunschweig/SORMAS-Project#7021]
### Situation Description
Currently, notifications are sent to the user assigned to a task.

### Feature Description
We want to allow the addition of observers to the tasks. When sending task-related notifications, observers would also be recipients.

The list of observers could appear just before the "Comments on task" block.

**to be defined:** should there be any restrictions on adding users to this list regarding their roles/region (i.e. who can be added as observer to a given task?)

@carolinverset @bernardsilenou

**Comment by carolinverset** [comment]
For information, the French team will start development
Best regards to all
@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
@MateStrysewske
