### ISSUE TITLE
Add option to directly enter the home address of the case person on creation form [2]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7064]
### Situation Description

Currently, users have to first create the case and then enter the the home address of the case person. However, this is data that is usually collected as the minimal initial data. Therefore, users would like to be able to enter the home address directly
### Feature Description

- Add a check box to the bottom of the case creation form, caption: 'Enter the home address of the case person now'
    - upon selection, extend the form with the case person home address fields and visually divide them as seen for samples and directly entered pathogen tests.
### Additional Information

<img width="367" alt="homeAddressCaseCreation" src="https://user-images.githubusercontent.com/70317594/138946549-7ea32755-1b30-4cc7-8da8-f1d92c49606f.PNG">

Consult @FredrikSchaeferVitagroup how to do "form in form"

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.67.0-snapshot on local environment

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
