### ISSUE TITLE
Allow to store external data for a case [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7068]
### Situation Description
As described in #6989 we need to be able to display additional data provided by SurvNet and other external reporting systems.

### Feature Description
In order to display the information we need to be able to store them and push them via ReST first.

- [ ] Add externalData field to the case and dto - see below for details
- [ ] <del>Consider validation of the data - e.g. white listing allowed characters</del>
- [ ] When an existing case is updated via ReST (e.g. sync with mobile app) and does not include externalData (null instead of empty map), don't override existing data. This is needed so we don't have to implement the externalData field in the mobile app for now
- [ ] <del>Add unit test to store externalData</del>

#### externalData field
This is similar to what we are doing for the TravelEntry.deaContent, but I'd suggest to use a Map<String,String> (see https://vladmihalcea.com/java-map-json-jpa-hibernate/) as data type so that the stored JSON looks like this:

```
{
  "StatusPatientSetting": "...",
  "PatientSettingDetail": "..."
}
```

Instead of:

```
[{ 
  "caption": "StatusPatientSetting",
  "value": "..."
},
{ 
  "caption": "PatientSettingDetail",
  "value": "..."
}]
```

**Comment by StefanKock** [comment]
Changed the milestone because #6989 needs this
