### ISSUE TITLE
Test updated LBDS service app

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7069]
### Situation
The LBDS service app has been updated to address the following problems

- Data transfer only runs when the app is in the foreground (HSLB-213)
- Exceptions when creating objects in SORMAS (HSLB-214)

### Task

Test the following combination with the current SORMAS dev branch:

* lbds-backend 1.15.0
* lbds-service-app 0.1.3

### Update 6/12/2021:

The following has to be adapted SORMAS side to keep up with LBDS changes:

Android Manifest:
 ```
<receiver android:name=".LbdsRecevierComponent"  android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"/>
        <action android:name="android.intent.action.SEND" />
        <category android:name="android.intent.category.DEFAULT" />
    </intent-filter>
</receiver>
``` 
 
Component to implement:
 ```
public class LbdsRecevierComponent extends BroadcastReceiver {
…
@Override
public void onReceive(Context context, Intent intent) {
    final String intentType = intent.getStringExtra(Constants.INTENT_TYPE);
…
```
 
Send:
```
sendBroadcast(sendIntent); 
```
or
```
context.sendBroadcast(toSormasIntent);
```

**Comment by syntakker** [comment]
Status update:
- communication between apps (LBDS service app, SORMAS app) is refactored to use BroadcastReveivers
- Crowdcode provides a new version and a test app to test this communication
- LBDS components in the SORMAS app have to be adapted accordingly

**Comment by AndyBakcsy-she** [comment]
This ticket cannot be tested by QA.
Will keep in mind with future Android app tests to observe and report any LBDS related messages.
