### ISSUE TITLE
Make validation a first-class member of the S2S processing pipeline

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7070]
## Situation description
Right now we do validation of incoming data in the classes that extend `ReceivedDataProcessor` (more specifically the `processReceivedData` in these classes calls data validation logic of `Sormas2SormasDataValidator`. 

Validation happens by going through the received DTO _structure_ and checking the fields on by one for valid or reasonable values.

Since we plan to do this for _outgoing_ data as well in order to provide the user better error messages, we are now in a position where we (as we walk the structure of dto) need to access the same field twice, once while sending and another time while receiving it. However, we want to avoid code duplication. 

## How to resolve this
Ideally, we have have a set of acessor functions which can read a certain property of the DTO, which takes a validation function as second argument. By this, it is much simpler to realize incoming and outgoing checks.

## Implementation steps

- [x] #7071
- [x] #7132
- [ ] Split validation from field access in S2S validators
- [ ] Implement outgoing validation

**Comment by mario-kuehne** [comment]
Succesfully tested locally with commit hash df83656b45be59913465b7429b6d187453da1576 

1. EDIT_INFRASTRUCTURE_DATA = true in Sormas Instance A (featureconfiguration in database)
2. Login as user 'admin'
3. Create District 'FakeDistrictInBayern' in Region 'Bayern' in Sormas Instance A (district unknown to Instance B)
4. Create case C in District 'FakeDistrictInBayern' in Region 'Bayern' in Sormas  Instance A
5. Try to share case C with Sormas Instance B

Expected: error message occurs

Actual: error message occurs

![unknown-district-for-second-sormas-instance](https://user-images.githubusercontent.com/95228108/150744080-24acb35e-32fb-4fec-b296-29def5c56b3f.PNG)

**Comment by mario-kuehne** [comment]
Found Vaadin UI issue with commit hash df83656b45be59913465b7429b6d187453da1576: Multiple errors are not completely shown in UI with special screen resolution / zoom factor:

100% (Default) Zoom-Factor & 2560 x 1440 screen resolution hides some error details
![case-sharing-error-ui-does-not-show-every-detail-100-percent-zoom-factor](https://user-images.githubusercontent.com/95228108/150765842-bb22fefb-d698-447c-98fc-eb4e868d7214.PNG)

Quick-Fix: Manually resize to 80% Zoom-Factor & 2560 x 1440 screen resolution

![case-sharing-error-ui-does-not-show-every-detail-80-percent-zoom-factor](https://user-images.githubusercontent.com/95228108/150766087-91b25680-78b2-41ed-9bc0-d72c883807ca.PNG)

Clarified with @JonasCir to create a separate ticket for the special Vaadin UI bug

**Comment by mario-kuehne** [comment]
Further functional tests were succesful for 

- Bulk Action 'Share Cases' 
- Share Event

Bulk Action 'Share Cases' (Logged in as National User). Tried to share 6 cases (3 valid, 3 invalid) -> error message shown and 0 cases shared
![bulk-actions-share-cases](https://user-images.githubusercontent.com/95228108/150778032-c61d3c2b-f698-4d5b-8df6-8921fd7d7dfa.PNG)

Share Event (featureconfiguration `SORMAS_TO_SORMAS_SHARE_EVENTS` = true & Logged in as National User)
![share-event](https://user-images.githubusercontent.com/95228108/150778290-89e885ff-8c85-4632-a5ef-2c1247076522.PNG)
