### ISSUE TITLE
Immunizations > `List of Vaccination` missing in Data Dictionary

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#7100]
### Bug Description

About > Documents > Data Dictionary
on the `Immunizations` tab, a reference is made to `List of Vaccination`, however the entity does not appear in the data dictionary.

### Steps to Reproduce

1. About > Documents > Data Dictionary
2. View Immunization tab > Find field: vaccinations | List of Vaccination |   | Vaccinations
3. No `Vaccination` tab visible

### Expected Behavior

Vaccination tab should be visible with all fields.

### Screenshots

![image](https://user-images.githubusercontent.com/65529128/139537834-c977cfe5-804a-443f-bd98-4eec048dc077.png)

### System Details

* Device: Web
* SORMAS version: 1.64.1 + 1.65-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: 
CH: https://test-ch.sormas.netzlink.com/sormas-ui/#!dashboard/surveillance
DE: https://release-de.sormas.netzlink.com/sormas-ui/#!about, https://test-de.sormas.netzlink.com/sormas-ui/#!about
INT: https://test.sormas.netzlink.com/
* User Role: admin, national user

### Additional Information

Concept: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4081

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.65.0-SNAPSHOT.
