### ISSUE TITLE
Cases & Contacts > Not possible to import Immunization&Vaccination information

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#7101]
### Bug Description

Cases > Import > Detailed Import
The current fields in the import file are for CaseData.(vaccinationStatus | numberOfDoses | vaccinationInfoSource | firstVaccinationDate | lastVaccinationDate | vaccineName | otherVaccineName | vaccineManufacturer | otherVaccineManufacturer | vaccineInn | vaccineBatchNumber | vaccineUniiCode | vaccineAtcCode)

When filling out the values correctly in the import file, a successful import message is displayed, yet the values are not imported to the Case linked Immunization entry (or anywhere else). 

Similar for Contacts.

It is therefore not possible to import Immunization nor associated Vaccination information into the system.

### Steps to Reproduce

1. Cases/Contacts > Import > Detailed Import > Import file with values for Vaccination
2. Import success message
3. Values not visible anywhere

### Expected Behavior

New fields for Immunization and Vaccination introduced in import/export files for Cases & Contacts to allow import of new values through detailed import (.csv) for these entities.

### System Details

* Device: Web
* SORMAS version: 1.64.1, 1.65-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://release-de.sormas.netzlink.com/, https://stable-release-ch.sormas.netzlink.com/, 
* User Role: admin, natuser

### Additional Information

Alternative: introduce an import on the Immunizations tab? (https://github.com/hzi-braunschweig/SORMAS-Project/issues/4081)

Part 2 for exports: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7102

**Comment by MateStrysewske** [comment]
@Candice-Louw I'm pretty sure you've used an outdated import file. If you re-download the import template on these servers, you will notice that these columns are gone because the corresponding fields are not part of the cases anymore as well.

**Comment by Candice-Louw** [comment]
@MateStrysewske - thank you for the feedback. 

Could you confirm that the only information that can currently then be imported for immunizations/vaccinations is therefore:

CaseData
vaccinationStatus
Impfstatus
VACCINATED,UNVACCINATED,UNKNOWN

Or is it possible to import immunization information in another way that I am missing, please?

**Comment by MateStrysewske** [comment]
@Candice-Louw Exactly, that's currently the only information that can be imported. A proper import functionality for the immunizations module still needs to be defined and implemented.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
I wish to suggest that when implementing the solution , we should keep the option for user to be able to import/create cases + all vaccination information mentioned in this issue, no matter if the full  immunization module is activated or not.
