### ISSUE TITLE
change "PERMANENT RESIDENCE" to "PLACE OF RESIDENCE" 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#711]
This appears both in **cases-patient information** and in **contacts-person information**

Permanent residence, we have discovered makes the patients give their home address even though they might be living in school or temporarily in another city where they work (usually the place of concern and investigation).

**Comment by MartinWahnschaffeSymeda** [comment]
Realized that there are a lot of unused strings in the app. 

- [ ] remove unused strings and other unused resources of app
