### ISSUE TITLE
Add properties to feature configurations [2]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7111]
### Situation Description

In the course of #7105 we need to extend the feature configurations with additional properties that differ from configuration to configuration. Explicitely, the `IMMUNIZATIONS` feature type needs a `reduced` property that toggles the detail level of the immunization module.

### Feature Description

* Add a `properties` field to the `FeatureConfiguration` class (similar to the properties of CustomizableEnumValue)
* Add a `FeatureTypeProperty` enum that contains all supported properties of feature types
* Add a `properties` string array to the `FeatureType` class and add a varargs constructor parameter to fill it; add "reduced" as a parameter to the `IMMUNIZATIONS` definition
* Add a `getPropertyValue` method to `FeatureConfigurationFacadeEjb` that returns the value of a property of a given feature type after checking whether that feature type supports the given property; if it doesn't, throw an error

**Comment by StefanKock** [comment]
To refine:
1. Have type safety on getPropertyValue
2. How should default behaviour be implemented?

**Comment by MartinWahnschaffe** [comment]
@MateStrysewske The [wiki](https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Feature-Configuration-Options) for IMMUNIZATION_MANAGEMENT has to be updated. I guess we do this once the release is out?

The following SQL allows to set the property to a certain value without changing any other:
`UPDATE featureconfiguration SET properties = coalesce(properties, '{}')::jsonb || '{"REDUCED":true}' WHERE featuretype = 'IMMUNIZATION_MANAGEMENT';`
