### ISSUE TITLE
Epi curve control- Epi week not automatically changing

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#712]
@MartinWahnschaffeSymeda @MateStrysewskeSym @Chinedar @foyiri 
Whenever you load the page, the default grouping is epi week which is good. However, when you change from epi week to day or month it works well but when you change back to epi week, it does not load the graph to epi week. This only happens when you select this year time interval or last year. It works perfectly for this week or last week

![image](https://user-images.githubusercontent.com/19344651/43315827-8687695c-9197-11e8-9b79-5963c555670b.png)

**Comment by MateStrysewskeSym** [comment]
- [ ] write test and update comment
