### ISSUE TITLE
Performance issues when mobile app sync with server

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#7127]
### Feature Description

This is about documenting observations when synchronizing mobile app with server having many records.
### Problem Description

This issue is a collection of observations when synchronizing the mobile app on a server with about 200000 cases and  5000 contacts in one district.
### Proposed Change

1. After installing the app and entering user name and password, app begins to pull infrastructure data. After about 5 min, the app did not success pulling all infrastructure data. however, the page to enter pin was provided and the users could login the app. The most interesting part is that all the directories were empty.
(would continue late)

### Additional Information

App versiion

**Comment by MateStrysewske** [comment]
@bernardsilenou Please document your observations in the issue that already exists: #6064
