### ISSUE TITLE
Filters overlap on immunizations directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7128]
### Bug Description

When expanding the filters on the immunizations directory, buttons overlap.
### Steps to Reproduce

1. Open the immunizations directory
2. Press "Show more filters"
3. Check the button display

### Expected Behavior

Buttons should not overlap when expanded
### Screenshots

<img width="715" alt="immunizationDirectoryOverlap" src="https://user-images.githubusercontent.com/70317594/140020685-a98bb74c-adfd-468b-9dc6-4684a13041a9.PNG">
### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.77.0-SNAPSHOT (07a6e3a)
Validated on test.de2 with the version: 1.77.0-SNAPSHOT (8d282da)
