### ISSUE TITLE
Change error message "Database entry was not updated - likely it was changed in between" 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#713]
Can we change this error message to "database entry was not updated - update all required fields and save again" ?

![image](https://user-images.githubusercontent.com/35563508/43316732-1e47fcc6-9192-11e8-8a2d-1bd492b289de.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @Chinedar Yes I had this same problem. Once you save a record and still edit something on the same page without going back, you get this error. And even after you update the record, it still gives the error and wont save the updated record information

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] change message as stated above
- [ ] sync is currently done while editing. This needs to be fixed
- [ ] when error occurs reload activity
