### ISSUE TITLE
Fix flaky UI tests

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#7131]
Investigate failing/flaky tests from jenkins executions and fix as many as possible in order to increase the pass rate and make them stable.

**Comment by rdutu-vg** [comment]
#7141 -> fixes for samples and tasks tests + refactored again login with national user

**Comment by rdutu-vg** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7151
Added extra fixes for contacts broken flows

https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-RunE2eTests/269/allure/
Increased pass rate to ~78%

**Comment by rdutu-vg** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7161
Fixed test - Check Filters on Sample page work as expected

**Comment by rdutu-vg** [comment]
Add a Task from event and verify the fields  test - caught defect. Small fix added, but won't pass until fix.
https://github.com/hzi-braunschweig/SORMAS-Project/issues/7189

**Comment by rdutu-vg** [comment]
fixed Create a new Case and check details in Detailed view table and removed redundant test
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7170

**Comment by rdutu-vg** [comment]
fixed:
1 Check Cases on Sample page work as expected
2 Edit all fields from Hospitalization tab
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7198

**Comment by rdutu-vg** [comment]
1. Fixed test: Create and check a new task data
2. Corrected enum data usage
3. Implemented table scrolling
4. Linked defect on failing test

https://github.com/hzi-braunschweig/SORMAS-Project/pull/7224

**Comment by rdutu-vg** [comment]
fixed 

1. Create a new Case and check details in Detailed view table 
2. Edit all fields from Case Contacts tab
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7226

**Comment by rdutu-vg** [comment]
fixed flaky test : Edit existent person.
Mentions: sometimes some fields are populated and deleted after. To be checked in Jenkins after code is merged.
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7243

**Comment by rdutu-vg** [comment]
Added correction for method selecting from dropdowns.
Refactored it in the previous PR to avoid situations where selenium moves faster than application's performance in order to reduce the flaky steps.
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7274

**Comment by rdutu-vg** [comment]
Fixed Create Contact and check details in Detailed view table and changed assert for Edit a created contact to identify specific missmatches
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7275

**Comment by rdutu-vg** [comment]
1. Added logger to check jenkins failure reason for test: Check all fields from the created Task in the Task Management table
2. Added another fix for test:  Create and check a new task data
3. Fixed test: Edit a new Sample (changed also the logic which was out of scope)
4. Fixed test: Add a Pathogen test from Samples and verify the fields

https://github.com/hzi-braunschweig/SORMAS-Project/pull/7283

**Comment by rdutu-vg** [comment]
Added small fixes for: Source case selected for contact and Change the source case contact and then delete
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7285

**Comment by rdutu-vg** [comment]
1. Added a potentially fix for combobox select where values can be selected twice due to selenium speed.
2. Added logs to investigate Date parsing issue on jenkins
3. Updated Edit person test by changing UI navigation to edited Person with URL navigation, due to environment's performance issues
4. Added fix for Create a new event and change its status multiple times
5. Added logger to investigate time parsing issue for: Add a New action for an Event and verify the Action in EventActions table
6. Added a small fix to check in jenkins for table row data parsing for: Change the source case contact and then delete
7. Added some small fixes for: Edit all fields from Follow-up visits tab
8. Added small fix for Create cases using Line Listing feature and validate the entries to check if is stable in jenkins

https://github.com/hzi-braunschweig/SORMAS-Project/pull/7294

**Comment by rdutu-vg** [comment]
Added fix for: Check Cases on Sample page work as expected
Removed html loading ready logger
Added assert for message for WebElement instance
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7307

**Comment by rdutu-vg** [comment]
1. Updated wait for loading spinner to disappear in order to fix: Edit a new Sample
2. Added fixes for Create a new user (noticed flaky situations on local execution and jenkins)
3. Updated and fixed test with the latest changes: Add a participant to an event
4. Corrected jenkins failing assert for test Edit all fields from Follow-up visits tab in order to identify why it fails only during jenkins execution

https://github.com/hzi-braunschweig/SORMAS-Project/pull/7318

**Comment by rdutu-vg** [comment]
1. Added fix for: Add a New action for an Event and verify the Action in EventActions table
2. Added stale element handle to check it in jenkins for: Edit all fields from Follow-up visits tab
3. Added fix for: Create Contact and check details in Detailed view table
4. Added potentially fix for jenkins failure and moved test into corresponding category: Create cases using Line Listing feature and validate the entries.
5. Added fix for: Create a new Case and check details in Detailed view table
6. Added potentially fix in jenkins for: Check Cases on Sample page work as expected 

https://github.com/hzi-braunschweig/SORMAS-Project/pull/7339

**Comment by rdutu-vg** [comment]
1. Refactored and corrected line listing cases and contacts tests.
2. Fixed test:  Check all fields from the created Task in the Task Management table
3. Added a wait for loading spinner to disappear for user creation
https://github.com/hzi-braunschweig/SORMAS-Project/pull/7340

**Comment by rdutu-vg** [comment]
The stablest version of the tests:
https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-RunE2eTests/376/allure/

Those failing cannot be reproduce on locale, we will need deeper investigation of differences from test-performance machine in order to determine and fix those failures.
Will move this ticket into done, and will come back on this topic once we'll add some more tests and cover new/left functionalities.
@markusmann-vg  @StefanKock

**Comment by StefanKock** [comment]
@rdutu-vg please document a list which tests keep failing (here or in the follow up ticket).

**Comment by rdutu-vg** [comment]
@StefanKock  will cover in a follow up ticket and leave it backlog
