### ISSUE TITLE
Person without sex can be persisted

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7143]
### Bug Description
In the Android app, persons without sex can be created when adding an event participant.

### Steps to Reproduce

1. Select an event, create an event participant
2. The following form shows sex as an required input. Do not save, but click the back button. The created person is not shown in the list of event participants
3. Create another event participant with the same name
4. The "select person" dialog opens, offering the person created in the first attempt

### Expected Behavior
When creating a person, sex should be a mandatory input from the beginning, i.e., already in the "New person involved" form.

### Screenshots
![image](https://user-images.githubusercontent.com/5616564/140211702-c2e579bf-acda-40f9-b258-560eb6d9d307.png)

### System Details

* Device: Android Emulator
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Hospital Informant (TestUserInt1)

**Comment by roxanamlendea** [comment]
Verified ticket on the android app on personal phone (Android 11) connected to the server URL https://test-de1.sormas.netzlink.com/sormas-rest/
