### ISSUE TITLE
Provide backend logic for reduced immunization [5]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#7148]
### Situation Description

Split out from #7105

### Feature Description

* Add an additional `save` method to VaccinationFacade with the following additional parameters: disease, region reference, district reference, person
  * The implementation of this method has to create a new immunization with the passed details if there is no immunization for the disease/person combination in the system already
  * If there already is at least one immunization, append the new vaccination to the vaccination list of one of the immunizations according to this logic:
    * If there is an immunization with start date < vaccination date < end date, append it to that immunization (just pick the first one if there are multiple)
    * Otherwise, append it to the immunization with the lowest interval between vaccination date and start/end date
    * If there is no immunization with a start/end date, append it to the immunization with the lowest interval between vaccination date and immunization report date
* Add a `getImmunizationsByPersonAndDisease` method to ImmunizationService
* Add a `getAllVaccinations` method to VaccinationFacade with a person UUID and a disease as its parameters which returns all vaccinations of all immunizations that belong to that person/disease combination
* Add matching ReST endpoints for both new methods
* Add unit tests for both methods
* Adjust the logic that sets the vaccination status of cases, contacts and event participants to always set it to vaccinated if there is at least one vaccination with vaccination date < case/contact/ep start date or without a vaccination date
* Adjust person and immunization user filters (and other methods that are used to retrieve data) when the reduced module is used: retrieve all immunizations of all persons the user has access to; ignore immunizations when calculating which persons the user has access to

**Comment by MartinWahnschaffe** [comment]
When an immunization is saved, the updateVaccinationStatuses logic is currently not called.
It needs be called with the dates of the the oldest vaccination of the immunization.

**Comment by kwa20** [comment]
I tested adding a vaccination on test-de.sormas.netzlink.com and received an error when trying to save. This happens every time. Not sure if it belongs in this issue or is related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/7105

<img width="433" alt="VaccinationSaveError" src="https://user-images.githubusercontent.com/70317594/143021095-c82c349a-f1f3-42d7-aeb6-ac66be03dc9c.PNG">

**Comment by sergiupacurariu** [comment]
@kwa20 we need more information about this issue. On my local machine works adding vaccinations to cases, contacts and eventParticipants. Could you add more information about the entity you are trying to add the vaccination?

**Comment by kwa20** [comment]
@sergiupacurariu The server was updated to a new SNAPSHOT version in the meantime and I can't seem to reproduce the error anymore

**Comment by MartinWahnschaffe** [comment]
This is very likely what I experienced here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7105#issuecomment-975323352 and has been solved.

**Comment by HolgerReiseVSys** [comment]
It seems that when adding a vaccination to an exisiting immunization via `VaccinationFacadeEjb::createWithImmunization`, the `meansOfImunization` is not taken into account.
This means e.g. an immunization with `meansOfImunization==RECOVERY` can end up cointaining vaccinations.

**Comment by MateStrysewske** [comment]
@HolgerReiseVSys Can you have another look at the method you've mentioned? It calls `ImmunizationService::getByPersonAndDisease` with a parameter that toggles whether or not immunizations with `meansOfImmuinzation == RECOVERY` are taken into account or not. The behaviour should already be correct.

**Comment by HolgerReiseVSys** [comment]
@MateStrysewske I don't remember seeing this parameter, so it should be fine.
