### ISSUE TITLE
CORONAVIRUS vaccines can be selected for other diseases

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7149]
### Bug Description

When creating immunizations for other diseases, CORONAVIRUS vaccines can be selected in vaccinations
### Steps to Reproduce

1. Create an immunization and set the disease to anything but CORONAVIRUS
2. Set the means of immunization to either vaccination or vaccination/recovery
3. Enter a vaccination and open the vaccine name drop down

### Expected Behavior

- Covid specific vaccines should not be displayed for other diseases
- The options `UNKNOWN` and `OTHER` should be available everywhere
### Screenshots

<img width="463" alt="vaccinesDisease" src="https://user-images.githubusercontent.com/70317594/140294538-356d1652-a8ff-4bbe-80a9-a410c9464134.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Fixable by adding the `@Diseases` annotation with CORONAVIRUS as its only value to the respective vaccines.

**Comment by StefanKock** [comment]
What's with the android-app, will it be fixed like that too?

**Comment by syntakker** [comment]
@kwa20 @MateStrysewske is the filtering supposed to be applied to the vaccine names only or for the manufacturer, too?

**Comment by kwa20** [comment]
@syntakker since the manufacturer is dependend on the vaccine name, both please :)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.65.0-SNAPSHOT from the development branch.
