### ISSUE TITLE
In the sample directory the region and district are not used properly

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7152]
### Bug Description

In the sample directory the regions and districts are not used properly by the system. By selecting the region and districts even the cases/contacts are not shown which are having the right responsible region and district.

### Screenshots

Filtering by the sample-ID:

![image](https://user-images.githubusercontent.com/74791118/140317232-e877e448-6bd1-46b9-97b6-7ecc74a41215.png)

The same ID with the region Thüringen as second filter:

![image](https://user-images.githubusercontent.com/74791118/140317303-4ccca2ee-00f7-49b2-bff1-992fe0d6aa12.png)

The address and the responsible region are set to the right value:

![image](https://user-images.githubusercontent.com/74791118/140317396-7e9f2695-ea3f-409b-a3fc-fad5eb9c581e.png)

![image](https://user-images.githubusercontent.com/74791118/140317479-77db3070-bbfe-42ab-bb29-366644581ca2.png)

Even in the export are the district and region are not included properly:

![image](https://user-images.githubusercontent.com/74791118/140318345-5ac83075-930f-493c-8ca7-5c3d4efced6b.png)

![image](https://user-images.githubusercontent.com/74791118/140318406-861d65b0-0069-4282-8bbf-66707d757f40.png)

### System Details

* Device: Win10
* SORMAS version: 1.63
* Server URL:
* User Role: Admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.66.0-SNAPSHOT.
