### ISSUE TITLE
Place of stay fields partly disabled for hospital informant

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7156]
### Bug Description

As hospital informant, when creating a case and selecting "place of stay differs from responsible jurisdiction", disabling of place of stay fields is inconsistent:
- Responsible jurisdiction is preset and disabled
- Place of stay region and district can be selected
- facility or home, place of stay community and facility are disabled, community and facility fields are cleared

### Steps to Reproduce

As hospital informant:
1. Open create case form
2. Select "place of stay differs from responsible jurisdiction"

### Expected Behavior

Either the responsible jurisdiction or the place of stay (including facility or home, community and facility) should be free to chose.

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/140485395-4438a260-b946-4b0b-b8b0-0c3a236c0ddb.png)

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Hospital informant

**Comment by MateStrysewske** [comment]
@syntakker I think the place of stay region and district should actually not be editable, and hospital informants should also not be allowed to check the "Place of stay of this case differs from its responsible jurisdiction" in the first place. @bernardsilenou @kwa20 what do you think?

**Comment by kwa20** [comment]
@MateStrysewske Sounds logical. I also checked the web access for this role and the behaviour conforms to what you describe. I think the intention to have a hospital informant is that they merely report/create cases in the assinged hospital. Therefore, they should only be able to create cases that are currently located in their respective hospital.

@bernardsilenou Feel free to correct me if I get it wrong.

**Comment by syntakker** [comment]
@MateStrysewske I think this is how it's implemented in the Vaadin app: The "place of stay differs" checkbox is not available to the Hospital Informant.

**Comment by MateStrysewske** [comment]
@syntakker Okay, then we only need to make sure that the region and district are also disabled.

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server https://test-de1.sormas.netzlink.com/sormas-rest/
