### ISSUE TITLE
Missing validation for phone and email

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7157]
### Bug Description

Email addresses and phone numbers are not validated in the Android app.

### Steps to Reproduce

1. Create a case, navigate to person information
2. add implausible data for email and phone

### Expected Behavior

Email addresses and phone numbers should be validated

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/140488334-7165700b-df5c-49dc-80c2-8591819b1735.png)

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Hospital Informant

### Additional Information

It was not possible to sync the case with the server afterwards, which might indicate that validation is in place server side.

**Comment by MateStrysewske** [comment]
We need to use the same validation that we also use in the Vaadin app.

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the hotfix branch.

**Comment by roxanamlendea** [comment]
Currently the validation for the phone number only checks for alphabetical characters from A to Z. The validation will be improved in #7231
