### ISSUE TITLE
Immunization date fields missing / not initialized

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7158]
### Bug Description

In ImmunizationEditFragment: date field immunizationPositiveTestResultDate is not initialized
In ImmunizationReadFragment: date field immunizationRecoveryDate is not shown

### Steps to Reproduce

1. In immunization edit, try to edit immunizationPositiveTestResultDate
2. Enter immunizationRecoveryDate, save => immunizationRecoveryDate is not visible in read fragment

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role:

**Comment by syntakker** [comment]
This issue is overlapping with #7176. Both issues will be fixed together.

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the hotfix branch.
