### ISSUE TITLE
Person select inconsistent when creating an immunization

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7160]
### Bug Description

When creating a new immunization while editing a case, the person select behaviour is inconsistent. The case person is offered for selection, but selecting this person and clicking "select" results in an error.
However, not selecting a person and clicking "create" works.

### Steps to Reproduce

1. Navigate to a case, create a new immunization, save
2. The person select window pops up. Select the case person, click "select"

### Expected Behavior

When creating an immunization for an existing case, the person select window should not appear in the first pace, since the person in question is defined (the case's person).
If there are technical or other reasons not to skip the person select window, the case person should be selectable without errors.

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/140505584-73d5bb08-1dad-415e-ae0d-89b501138292.png)

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role:

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Based on the new specification of the reduced module of immunization, this functionally would be handled at the back end since only vaccinations would be created from ui, is it still necessary to make a change in this hotfix?

**Comment by syntakker** [comment]
@bernardsilenou this issue is about a faulty person selection in the UI, which cannot be handled in the backend only. When creating a new immunization from a case, the immunization's person is the case's person, so there is no need to select a person here.

**Comment by bernardsilenou** [comment]
@syntakker 
For the coming reduced module, there would be no need to create immunization for a case person on the ui, we only create vaccinations and the case person is selected as the associated person.

**Comment by syntakker** [comment]
@bernardsilenou @MateStrysewske vaccinations relate to a person, too. So if the reduced immunization module starts from existing code, the fix might also be relevant there.
See PR #7278

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the hotfix branch.
