### ISSUE TITLE
Filtering for contacts from other jurisdictions leads to endless loading

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7163]
### Bug Description

When searching the contact directory via the free text search field and subsequently filtering for contacts from other jurisdiction, the page loads endlessly
### Steps to Reproduce

1. Go to the contact directory
2. Seacrh for e.g. a name and apply filter
3. Expand more filters and filter for contacts from other jurisdictions

### Expected Behavior

Filtering should work in a reasonable amount of time

### Screenshots

<img width="953" alt="otherJurisdictionFilter" src="https://user-images.githubusercontent.com/70317594/140513446-17fbfc3f-d409-4b7b-b118-28cbc58abf0d.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance Superviros, Contact Supervisor

**Comment by MateStrysewske** [comment]
@kwa20 Is this reproducable on other systems as well? @alexcaruntu-vita can't reproduce it locally.

**Comment by kwa20** [comment]
@MateStrysewske @alexcaruntu-vita I tested again on test1402.sormas.netzlink.com and release-international.sormas.netzlink.com and could not reproduce the problem. I've requested logs from Netzlink for test1401.sormas-oegd.de

**Comment by kwa20** [comment]
@MateStrysewske @alexcaruntu-vita Here the logs. It includes this message: "ValidationRuntimeException: Could not find a database entry for the specified facility in the specified district"
[ValidationRunTimeException.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7562816/ValidationRunTimeException.txt)

**Comment by MateStrysewske** [comment]
That isn't related to this issue here - it's a message that appears when someone tries to save a case with missing details, likely via an import. The logs unfortunately don't contain any hint at why this problem appears.

**Comment by MateStrysewske** [comment]
My assumption is that this is caused by the `ContactFacadeEjb.count` method returning a different number than the size of the list retrieded by `ContactFacadeEjb.getIndexList`. The cause would be that the `getIndexList` is a distinct query while the `count` method does NOT do a countDistinct. I'd hope that fixing this (= making the count method do a countDistinct) will also fix this problem.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the hotfix branch 1.65.1-SNAPSHOT.
