### ISSUE TITLE
App crashes when trying to create immunizations for event participants

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7167]
### Bug Description

The Android app crashes when trying to create an immunization for an event participants.

### Steps to Reproduce

1. Select a participant of an event with no disease, navigate to immunizations
2. Click the edit icon => person edit fragment opens
3. navigate to immunizations again
4. Click the "+" icon to create an immunization => app crashes

alternatively:

1. Select a participant of an event with disease, navigate to immunizations
2. Click the "+" icon to create an immunization => app crashes

### Expected Behavior

The app should not crash.
For events with no disease, it should not be possible to create immunizations for event participants.

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Contact Officer & Surveillance Officer

**Comment by bernardsilenou** [comment]
Minor change in specoficatioin:
For events with no disease, 
1. It should not be possible to  create immunizations for the event participants if the event has no disease. How a similar message as when lconverting ep to a case "It is not possible to create vaccinations/ minimizations for an event participant if the disease of the event has not been set."
2. If the event has a disease, then it should be possible and the disease of the event should be enforced as disease of immunization.
3. It should not be possible to create immunizations for event participants person but  through the person tab, this works already.


![image](https://user-images.githubusercontent.com/12996724/140824923-a339fe6f-5b2b-4f19-acdb-18868a2e7ca1.png)

**Comment by syntakker** [comment]
@bernardsilenou Implementation is now as for the web app:
- if the event has no disease, the immunization tab (corresponding to the immunization side box in the web app) is not available in the menu for event participants
- if the event has a disease, this disease is selected and readonly when creating a new immunization
