### ISSUE TITLE
UUID not displayed in immunization fragments

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7168]
### Bug Description

The immunization's UUID is not displayed in the read / edit immunization fragments.

### Steps to Reproduce

1. navigate to immunizations of cases, contacts or event participants

### Expected Behavior

UUID should be displayed

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Contact Officer & Surveillance Officer

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the hotfix branch.
