### ISSUE TITLE
Add SORMAS logo to login page

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#717]
@MartinWahnschaffeSymeda @MateStrysewskeSym @foyiri @Chinedar 
![image](https://user-images.githubusercontent.com/19344651/43323264-709e8d36-91b1-11e8-9d4e-374030f2a319.png)

**Comment by MartinWahnschaffeSymeda** [comment]
See #593

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym I had a quick look at this and decided to move it to the left side component.
