### ISSUE TITLE
Date filter fields not initialized

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7171]
### Bug Description

In the immunizations overivew, the date filter fields "valid from" and "valid to" are not initialized, thus it is not possible to select a date.

### Steps to Reproduce

1. Navigate to immunizations
2. Open the filter (icon bottom right)
3. Try to fill "valid from" and "valid to"

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/140531374-d0692f1b-40fe-414f-a3bb-47a454f1f5b4.png)

### System Details

* Device: Android
* SORMAS version: 1.64.1
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Contact Officer & Surveillance Officer

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the hotfix branch.
