### ISSUE TITLE
Users can lose access to events that include participants in their jurisdiction

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7172]
### Bug Description

When a jurisdiction restricted user changes the jurisdiction of an event to outside their own jurisdiction, they can lose access to participants in their jurisdiction. The event cannot be found in the directory after it has been changed.
### Steps to Reproduce

1. Log in as a user with the jurisdiction region1/district1 (if officer)
2. Create an event in region1 and district1
3. Add an event participant and set the jurisdiction to region1 and district1
4. Go back to the event page and change the jurisdiction to region2 and district2
5. Go to the event directory and look for the event

### Expected Behavior

- All events should be visible to any user
- Only events in the users jurisdiction or without an assigned jurisdiction should be fully editable, others should be read only
- Event participants outside the users jurisdiction should be read only, the ones inside the users jurisdiction fully editable
- If an event participant does not have a jurisdition, fall back onto the jurisdiction of the event
- When changing the jurisdiction of an event participant or the event, the user should see a pop-up that informs them that they might lose access to the respective entities

### Screenshots

Event in the users jurisdiction:
<img width="811" alt="eventAccessLoss2" src="https://user-images.githubusercontent.com/70317594/140531857-ff57e354-b60b-4c09-b1ed-4ec3822c0223.PNG">

Jurisdiction change:
<img width="438" alt="eventAccessLoss" src="https://user-images.githubusercontent.com/70317594/140531853-64c9ced1-fbc7-4a23-b2d4-4f73d0e5d29d.PNG">

Event directory after jurisdiction change: The event still includes an event participant in the users jurisdiction
<img width="751" alt="eventAccessLoss3" src="https://user-images.githubusercontent.com/70317594/140531859-1ad88f95-13bb-41ea-bbd5-5ca2724508fe.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance/Contact Supervisor, Surveillance/Contact Officer

**Comment by bernardsilenou** [comment]
@kwa20 
Any idea if it is fine on the mobile app? Point one of your specification should be 
 - Only active events in the jurisdiction of the user should be visible to the user on mobile app

**Comment by kwa20** [comment]
@bernardsilenou I don't know because I don't have option to test the mobile app

**Comment by BarnaBartha** [comment]
@kwa20 All events to be visible to all users is not a good idea, we would be throwing out important filtering that was added with several requirements and is definitely needed for servers where there are a lot of events spread across a lot of regions / districts.
I did fix though that the event in step 2 is visible now at step 5. That is an event is visible even if it's location is outside the jurisdiction if at least one event participant is in the users jurisdiction or at least one event participants related case is in the users jurisdiction. (please confirm that is the way we want it)
The rest of the expected behaviour is ok and is working now as you requested.

**Comment by kwa20** [comment]
@BarnaBartha 

> That is an event is visible even if it's location is outside the jurisdiction if at least one event participant is in the users jurisdiction or at least one event participants related case is in the users jurisdiction. (please confirm that is the way we want it)

Looks good to me

**Comment by roxanamlendea** [comment]
@kwa20 Maybe you can help with your input. I logged in with a Surveillance Supervisor that is part of jurisdiction A. I created an Event where I chose jurisdiction B as location, and I added an Event Participant for which I also chose jurisdiction B. I was able to save initial form, but when I saved the second form (the edit form), I got this error. I made a short recording to see what I mean. 
![event particip](https://user-images.githubusercontent.com/89522688/143422868-ce4d67f0-c729-4aa1-90c5-4df9d4a3ace5.gif)

**Comment by kwa20** [comment]
@roxanamlendea It seems that the event participant is saved, meaning the juridiction change, before the person data is edited via the pop-up. At this point, the user would have already lost access to the event participant. I think therefore the error message appears. Either the time of saving needs to be adjusted or the jurisdiction warning I think.

**Comment by MateStrysewske** [comment]
@kwa20 I would suggest to skip the "Edit person" popup because we have a dedicated event participant edit page by now, and instead forward the user to that page. It's more in line with the behaviour in other parts of the app anyway, and it would get rid of this problem.
