### ISSUE TITLE
The outcome of case column disappears upon filtering

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7174]
### Bug Description

When filtering the outcome of case on the case directory (default and detailed view), the column disappears from the list
### Steps to Reproduce

1. Go to the case directory (default and detailed view)
2. Filter for the outcome of the case and check the list for the corresponding column

### Expected Behavior

The column should not disappear
### Screenshots

<img width="699" alt="outcomeOfCaseFilter" src="https://user-images.githubusercontent.com/70317594/140537926-6eabfb44-6600-4938-bb62-09b45b4c5701.PNG">
<img width="694" alt="outcomeOfCaseFilter2" src="https://user-images.githubusercontent.com/70317594/140537930-636142da-0697-4ee3-b225-f7f13d357988.PNG">
<img width="726" alt="outcomeOfCaseFilter3" src="https://user-images.githubusercontent.com/70317594/140537933-980f0529-130f-4282-86fa-898dc21b7af6.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance/Contact Officer, admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 Seems like this behaviour was requested at some point - at least there's code that explicitely hides the outcome column when the filter is set, likely to save some space. Do you still want us to change this?

**Comment by kwa20** [comment]
@MateStrysewske yes, please. I find this behaviour rather confusing and not self explanatory. Do we know if this happens for other columns as well by just looking at the code? Not sure if this is a quick search

**Comment by MateStrysewske** [comment]
@kwa20 I haven't seen anything at a first glance.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas1.66.0-snapshot on local environment
