### ISSUE TITLE
Date of burial is validated even of present condition was changed

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7175]
### Bug Description

When the date of burial is set in the future, the field is still validated even if the present condition was changed after, e.g. to 'Alive'
### Steps to Reproduce

1. Open any person form and set the present condition to burial
2. Enter a date in the future
3. Change the present condition to ALIVE
4. Save the person form

### Expected Behavior

The date of burial should be emptied when the field gets hidden again

### Screenshots

<img width="485" alt="dateOfBurialValidation" src="https://user-images.githubusercontent.com/70317594/140546167-2b48cbde-95a3-4d56-bbaa-87654cffaf04.PNG">
<img width="529" alt="dateOfBurialValidation2" src="https://user-images.githubusercontent.com/70317594/140546168-d7503158-b591-4c2c-9999-7fcbd865dbf3.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance/Contact Officer

**Comment by MateStrysewske** [comment]
We need to clean the death and burial related fields when the present condition is changed.
