### ISSUE TITLE
Missing fields in immunization fragments

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7176]
### Bug Description

- The field "date of previous infection" is missing in  the edit / read immunization fragments. The field should be visible when "previous infection" is set to "Yes"
- In the read fragment, only "date of first positive test result" is visible from the "recovery" section. Both "date of first positive test result" and "Date of recovery" should be visible when "Recovery" or "Vaccination/Recovery" is selected as means of immunization
- In the edit fragment, display and hiding do not work properly: Vaccination fields are shown on selection of "Vaccination" as means of recovery. Switching back to "Revcovery" does neither hide the vaccination fields nor display the recovery fields 

### Steps to Reproduce

1. Navigate to an immunization (read or edit)
2. Fields are missing in edit and read fragment
3. In the edit field, select first "Vaccination" as means of immunization, then "Recovery"

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/140549864-e7ba5716-6274-432e-9e69-1dec6f3da28c.png)

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment]
Verified ticket on Android Studio connected to the local server, on the hotfix branch.
