### ISSUE TITLE
Spelling error for 'Other protective measures' in exposures

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7177]
### Bug Description

Protective is missing an 'r' in exposures
### Steps to Reproduce

1. Go to cases and contacts and enter a new exposure in epi data
2. Check the exposure details for 'other protective measures'

### Screenshots

<img width="179" alt="otherProtectiveMeasuresSpellingError" src="https://user-images.githubusercontent.com/70317594/140582491-528338fc-a66f-445c-bd0f-501403cb99da.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.66.0-SNAPSHOT from the development branch.
