### ISSUE TITLE
Task and Sample position on web app [5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#718]
@Chinedar @foyiri @MartinWahnschaffeSymeda @MateStrysewskeSym
 I think its time to move the tasks and sample menus to the right of the case page. it has caused confusion in the past where users would not care to scroll down to see tasks or samples or even lab tests. Can we do this now?
![image](https://user-images.githubusercontent.com/19344651/43324343-25c6bbfa-91b4-11e8-8fcb-43b0743e69a1.png)

**Comment by Chinedar** [comment]
@Martin Wahnschaffe <m.wahnschaffe@symeda.de> @Ferdinand Oyiri
<skidomamu12@gmail.com> @Maté Strysewske <m.strysewske@symeda.de>
I agree with you Martin, we should move it now. Thanks!!!

**Comment by Chinedar** [comment]
@Tom-Aba, Daniel <Daniel.Tom-Aba@helmholtz-hzi.de> you raised this right? I
agree.

**Comment by hzi-braunschweig** [comment]
@Chinedar Its me creating this issue lol

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] create a new TaskList component that is basically a vertical layout with a component for each task (as in mockup)
- [ ] no need to filter here - instead display the create button (export not needed as well)
- [ ] same for SampeList
- [ ] make responsive (put lists under case information when screen too small
- [ ] same for tasks of contact (put list under case info on the right side - if responsive, both should go under the contact base data)
- [ ] same for tasks of event
- [ ] same for sample tests of sample (SampleTestList)

**Comment by MartinWahnschaffeSymeda** [comment]
Discuss: Do we need a filter for done tasks of a contact (for the contact visit tasks)?

**Comment by MartinWahnschaffeSymeda** [comment]
Limit the number of displayed entries:

- [ ] build a pagination control: A vertical layout that only shows one page (= a subset with a defineable count) of its children
- [ ] tasks ~5
- [ ] samples ~5
- [ ] sample tests ~10
