### ISSUE TITLE
Add reinfection details and status to cases [5]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7182]
### Situation Description

There are subdivisions to better capture the exactness and nature of a reinfection. The type of reinfection is calculated by selection. 
I think this should be German only, cause it is really specific.

#### Backend
- [x] Add a new `ReinfectionDetail` enum with the following values (for the captions, see the screenshot below):
  - `GENOME_SEQUENCE_PREVIOUS_INFECTION_KNOWN`
  - `GENOME_SEQUENCE_CURRENT_INFECTION_KNOWN`
  - `GENOME_SEQUENCES_NOT_MATCHING`
  - `GENOME_COPY_NUMBER_ABOVE_THRESHOLD`
  - `GENOME_COPY_NUMBER_BELOW_THRESHOLD`
  - `ACUTE_RESPIRATORY_ILLNESS_OVERCOME`
  - `PREVIOUS_ASYMPTOMATIC_INFECTION`
  - `TESTED_NEGATIVE_AFTER_PREVIOUS_INFECTION`
  - `LAST_PCR_DETECTION_NOT_RECENT`
- [x] Add a new `ReinfectionStatus` enum with the following values:
  - `CONFIRMED` - Confirmed reinfection
  - `PROBABLE` - Probable reinfection
  - `POSSIBLE` - Possible reinfection
- [x] Add a new `reinfectionDetails` field to cases which is a `Map<ReinfectionDetail, Boolean>` in the entity and a json column in the database (see Event.epidemiologicalEvidenceDetails as a reference); DE-only
- [x] Add a new `reinfectionStatus` field (of type `ReinfectionStatus`) to cases; DE-only
- [x] Add the new fields to the detailed and custom export
- [x] Ensure that the `reinfectionDetails` field is preserved during duplicate case merging; it's theoretically possible that Maps aren't properly handled yet
- [x] Add a method called `getMostRecentPreviousCase` that, based on the person, disease, and case start date, retrieves the most recent case with the same person and disease, but an earlier start date that is not deleted (if there is one)

#### UI
(All additions are exclusive to Covid-19 cases on German systems)
- [x] If Reinfection is set to `YES`, show the `reinfectionStatus` as a read-only field next to the reinfection.
- [x] If Reinfection is set to `YES`, show the form (the checkboxes + headings) that is depicted in the screenshot below which is based on the content of the new `reinfectionDetails` field; multiselect needs to be possible.
- [x] If Reinfection is set to `YES` AND there's a previous case (based on the backend method created above), show an eye icon next to the `reinfection` field (same as the eye icon in the address form); when hovering over it, show a description popup with the following information about the latest previous case:
  - reportDate
  - externalToken
  - diseaseVariant
  - onsetDate
- [x] Upon checking or unchecking the checkboxes, calculate the `reinfectionStatus` based on the rules below.
- [x] Add a filter for the `reinfectionStatus` to the case directory

#### Reinfection status calculation
Source/more information: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Reinfektion.html
Confirmed always has precedence over the other two values.

**Confirmed reinfection:**
`GENOME_SEQUENCE_PREVIOUS_INFECTION_KNOWN` AND `GENOME_SEQUENCE_CURRENT_INFECTION_KNOWN` AND `GENOME_SEQUENCES_NOT_MATCHING`

**Probable reinfection:**
(`GENOME_SEQUENCE_PREVIOUS_INFECTION_KNOWN` == unchecked OR `GENOME_SEQUENCE_CURRENT_INFECTION_KNOWN` == unchecked)
(`ACUTE_RESPIRATORY_ILLNESS_OVERCOME` OR `PREVIOUS_ASYMPTOMATIC_INFECTION`) AND (`TESTED_NEGATIVE_AFTER_PREVIOUS_INFECTION` OR `LAST_PCR_DETECTION_NOT_RECENT`) AND `GENOME_COPY_NUMBER_ABOVE_THRESHOLD`

**Possible reinfection:**
(`ACUTE_RESPIRATORY_ILLNESS_OVERCOME` OR `PREVIOUS_ASYMPTOMATIC_INFECTION`) AND (`TESTED_NEGATIVE_AFTER_PREVIOUS_INFECTION` OR `LAST_PCR_DETECTION_NOT_RECENT`) AND `GENOME_COPY_NUMBER_BELOW_THRESHOLD`

### Additional Information

![Reinfection 3](https://user-images.githubusercontent.com/78568406/140716093-e0b34003-360d-4f85-82db-1b213715d749.png)

Associated Survnet issue: https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/265

@kwa20 fyi

**Comment by MateStrysewske** [comment]
@JaquM I've updated the issue description, does this look fine for you? Also, can you please tell me whether "Prerequisite: no genome sequencing result is available or known for at least one of the two confirmed SARS-CoV-2 infections." for the probable reinfection status simply means that either `GENOME_SEQUENCE_PREVIOUS_INFECTION_KNOWN ` or `GENOME_SEQUENCE_CURRENT_INFECTION_KNOWN` are not checked, or is there some more sophisticated calculation needed here?

**Comment by MateStrysewske** [comment]
@JaquM What if both "genome sequence of previous infection is known" and "genome sequence of current infection is known" are both checked, but "genome sequences of viruses do not match" is unchecked? According to the current specifications, this would neither classify the case as a confirmed, nor as a probable reinfection, and potentially also not as a possible reinfection if the criteria for that is not met. In this case, the reinfection status would be empty. Is that fine or is there specification missing?

**Comment by MateStrysewske** [comment]
@TheresaBruell Should the reinfection status be explicitely set to a value with the caption "Unknown", or should it be left empty in these cases? According to the current specification, there are only three possible values (Confirmed, Probable, Possible), so unknown would equal to the field not having a value at all.

**Comment by TheresaBruell** [comment]
@MateStrysewske An extra value for unknown is not needed and can be left empty as currently specified.

**Comment by MateStrysewske** [comment]
@TheresaBruell Thanks for the clarifications!

**Comment by bernardsilenou** [comment]
@MateStrysewske 
1. It just came to mind that  reinfection can also happen for another disease than covid, so if we then wish to activate this issue to other instances that have multiple diseases, then  the form names (as in mockup)  may not be good since they contain disease name. 
2. The solutions I can think of is:
2.1 remove the word `SARS-CoV-2` form the caption names 
2.2 set this as a parameter and map it to the name of the disease 
2.3  replace `SARS-CoV-2` with `disease`

**Comment by bernardsilenou** [comment]
- Since this feature is not added to web app only, It would be good to  test that synch with the mobile app is not broken for DE instance and also for non DE instance with multiple diseases.
- I think for now, reinfection is only is disease == COVID. For other diseases, you can just hid this part on the UI. We may need to add this configuration to the disease configuration. Reinfection only apply to certain diseases.

**Comment by MateStrysewske** [comment]
@bernardsilenou The captions can simply be changed in the future if we enable this functionality for other diseases. Right now, there are some values in there that don't make sense for other diseases anyway, so I don't really see that using a parameter for the disease name really helps us right now.

This issue does not affect synchronization at all.

**Comment by roxanamlendea** [comment]
The order of the reinfection details is not the same as the screenshot in the Additional Information. ![image](https://user-images.githubusercontent.com/89522688/148233478-02930558-d8c5-483c-a309-1665f48819dc.png)

**Comment by MateStrysewske** [comment]
Additionally: Re-calculate the reinfection status on case save (because the details might come in via import/Survnet/case merging).

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.

**Comment by kwa20** [comment]
@MateStrysewske Sorry, this might be a little petty, but I noticed that the margins of the eye icon are a bit off. Do you think we could adjust them so they align a bit better with the rest of the fields?
<img width="471" alt="reinfectionEyeMargin" src="https://user-images.githubusercontent.com/70317594/148939525-0d71622b-623e-47b1-9e41-589f1d04c13b.PNG">
<img width="790" alt="reinfectionEyeMargin2" src="https://user-images.githubusercontent.com/70317594/148939527-c59368a4-87b7-4437-9910-77a74f89f3fd.PNG">
<img width="803" alt="reinfectionEyeMargin3" src="https://user-images.githubusercontent.com/70317594/148939530-fc473347-69a0-4528-9ad5-53400cb7656d.PNG">

**Comment by MateStrysewske** [comment]
@kwa20 I'll have a look at it :D

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
