### ISSUE TITLE
[Angular] Events Grouping Add & Link Modal [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7183]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/7y51mQZ
- We will have two modals, one for Link and one for Add new group
- After "Saving" the form, the modals close without any further action
- We need to add a search on the linking modal (which searches current available groups based on ID, title/name)
-  Even if we don't have the backend, we can hardcode a response just to have the FE implemented.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
