### ISSUE TITLE
[Angular] Events Grouping Group profile [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7184]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/nRJY3Ez
- As we have something similar on the card list implementation, maybe we can reuse it
- For the unlinking functionality, we will make use of the confirmation dialog (already in use in other sections of the site).
- On "Edit" event, a redirect will be performed (no modal!)
- We will also add the top right buttons (without any functionality) - except "Discard"

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
