### ISSUE TITLE
[Angular][Bug] Loading page elements that are not in focus [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7188]
### Steps to Reproduce

1. Go to "Configuration"
2. Go to "Communities"
3. Open "Add new community"
4. Filter in the modal
5. Notice that the background page (the one below the modal) updates as per the user selection in the modal

### Expected Behavior

- The loader should only apply to the page actually in the user's focus.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

- Fix the loader. Should trigger only related to a specific request. Right now when a request is being fired that is not related to the table, the table loader kicks in or when a modal is closed from the "X" button, the table loader kicks in. Test and make sure it is working fine all over the site.

NOTE: This fix should be applied across the board (all site), wherever it occurs.

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
