### ISSUE TITLE
New Task button not working when clicked inside an event

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7189]
### Steps to Reproduce

1. Open Events tab and select one Event
2. Click on the New Task button from the Event Page

### Expected Behavior
New Task should be created

### Actual Behavior
Server error message is displayed and logged.

### System Details

* Device: windows 10
* SORMAS version: 1.65.0-snapshot
* Android version/Browser: chrome
* Server URL: local environment or any environment 
* User Role: natuser

### Additional Information
[server_error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7497408/server_error.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.66.0-SNAPSHOT from the hotfix branch.

**Comment by kwa20** [comment]
Just noticed that in relation to this issue, the same happens when editing the task in the task directory 
![image](https://user-images.githubusercontent.com/70317594/141430013-73fb0d40-5199-47ec-971e-0cf5d82e5451.png)
 We should verify this as well

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.66.0-snapshot on localenvironment
