### ISSUE TITLE
Prefilled disease is disabled in contact line listing

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7190]
### Bug Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/5496 implemented a prefill of the disease field if there is only one disease active on the instance. However, this field becomes generally disabled in the contact line listing form contrary to the case line listing form. Since there would be oly one disease selectable anyway, this should likely not really have a negative effect.
### Steps to Reproduce

1. Enable only one disease on the server
2. Go to the contact directory
3. Press line listing and check the disease field

### Expected Behavior

Field should be prefilled but not disabled
### Screenshots

<img width="793" alt="diseaseDisabled" src="https://user-images.githubusercontent.com/70317594/140760331-98e28fdc-5ec8-4600-af89-b3e60ccf2a05.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user; community officer

**Comment by kwa20** [comment]
@MateStrysewske I think that this issue should not really have a negative effect because only one disease is active anyway. It might simply be confusing why it's different for cases compared to contacts. Maybe you can judge whether there could be any other potential negative effect?

**Comment by MateStrysewske** [comment]
@kwa20 I don't think so - and I actually believe that this behaviour is desired (because you can't change the value anyway). Maybe we should rather also implement it like that for the case line listing?

**Comment by kwa20** [comment]
@MateStrysewske would work for me as well. @JaquM @bernardsilenou Any opinion on what the preferred solution would be?

**Comment by bernardsilenou** [comment]
To me it is fine as it is.
