### ISSUE TITLE
Hibernate exception in CentralInfraSyncFacade::syncAll prevents login

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7191]
### Bug Description
In case we sync with central and e.g., a fetched district does not contain a valid reference to the region it is located in, an exception is thrown:

```
  ERROR: null value in column "region_id" violates not-null constraint
2021-11-08T14:21:44.890413262Z   Detail: Failing row contains (122, 2021-11-08 15:21:44.768, 2021-11-08 15:21:44.768782, SK Flensburg, b63bde91-099f-564f-a82f-b88406c6580a, null, FL, 0, f, 11001001).|#]
```
This correct and intended behavior and we actually catch the exception in `syncAll`.

If this happens in `StartupShoutdownService::startup()`, it somehow influences the deployment and prevents successful logins to the UI. This is odd as:

1. We catch and handle the exception properly
2. The deployment is sucessful
```
 Boot Command deploy returned with result SUCCESS : PlainTextActionReporterSUCCESSDescription: deploy AdminCommandApplication deployed with name sormas-ui.
2021-11-08T14:22:28.874397532Z     [name=sormas-ui
```

### Steps to Reproduce
1. Add an district with wrong region id to central
2. Start SORMAS
3. Try to login

### Expected Behavior
Login succeeds even with exception being logged.

**Comment by vidi42** [comment]
Cannot reproduce it anymore.
