### ISSUE TITLE
Unify list fragments and adapters [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#720]
Currently we have multiple versions of *TaskListFragments and *Adapters and the same for Contacts and Samples. This should be unified to a single fragment and adapter for each entity.

In order to do this it would be optimal to provide the entries to be shown from the outside (Activity). Thisway, the activity can query the entries and the fragment does not need to know more about the context.
Suggestions: Use the new Android ViewModel pattern.

**Comment by MartinWahnschaffeSymeda** [comment]
## ViewModel & LiveData

> The ViewModel class allows data to survive configuration changes such as screen rotations.
https://developer.android.com/topic/libraries/architecture/viewmodel

> * LiveData provides a lifecycle aware base class for encapsulating loading data
> * ViewModels are automatically retained across configuration changes
> 
> One significant advantage of this separation is that you can reuse the same LiveData in multiple ViewModels, compose multiple LiveData sources together through a MediatorLiveData, or use them in a Service, avoiding the effort of trying to munge a Loader into a scenario where you don’t have a LoaderManager.
https://medium.com/androiddevelopers/lifecycle-aware-data-loading-with-android-architecture-components-f95484159de4

## Paging

> The PagedList class works with a PagedListAdapter to load items into a RecyclerView
https://developer.android.com/topic/libraries/architecture/paging/

**Comment by MateStrysewskeSym** [comment]
- [ ] refactor cases list: introduce ViewModel to hold active filter and list of cases
- [ ] define how to change the generic classes for lists
- [ ] refactor all other lists
