### ISSUE TITLE
[Angular] Dashboard surveillance & contacts Baseline structure [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7203]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference overall: 
- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/08E60D4D-604F-4047-9EFE-B98D923A585A
- https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/37C4434C-B2BC-48CB-AFBD-1C9ADDA7559B

- Reference surveillance: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- We will need to include the following containers:
- Header component (With the View Options - Contacts & Surveillance)
- Filter component
- Disease overview component
- Difference in number cases component
- Disease menu / slideshow component
- New Cases component
- New Event component
- Test results component
- Epidemiological curve component
- Map component

When selecting the "Contacts" display, the following components need to disappear:
- Reference surveillance: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP041vq
- Disease overview component
- Difference in number cases component
- Disease menu / slideshow component
- New Cases component
- New Event component
- Test results component

And new components will show up:
- Number of Contacts component
- Number of follow up component
- Number of stop follow up component
- Number of visits component
- Contacts component
- Transmission change component (the bottom button).

Obs: All the components need to be present, but empty, with the title
Obs: We will have a module Dashboard, with two sub-components for Surveillance and one for Contacts, and they will use common sub-components (Map, Curve, etc).
Obs: Please pay attention to the width and responsiveness.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
