### ISSUE TITLE
[DEMIS2SORMAS] Handle New Profile: Allow to create sample referral when processing lab messages [2]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7204]
### Situation Description

Imagine the following scenario: A lab 1 receives a sample. It performs a preliminary test and the sends the sample to another lab 2, which performs additional tests.

In SORMAS, a user would first create a sample for lab 1. When the sample gets sent to lab 2, the user would open the sample, and create a referral for it. This would create another sample, which will be related to the first sample created. Both samples are similar, but the facilities differ -> The same physical sample has two sample entities in SORMAS.

### Feature Description

The scenario described above can also be communicated via DEMIS, once the new profiles are used.
When a user edits a sample while processing a lab message, it must be possible use the functionality of the `referOrLinkToOtherLabButton` or the [SampleController](https://github.com/hzi-braunschweig/SORMAS-Project/blob/fc8d3c07da4ccace1f6ed0c569357ba6d8ff3fac/sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleController.java#L300).

### Possible Alternatives

Another option might be to refactor the sample entity, so that it can have multiple facilities. This would probable require some more fields to exist multiple times, e.q. the `fieldSampleId` which might be different for each laboratory.

**Comment by kwa20** [comment]
To be determined: There are two main possible ways to handle the referencing of the same sample from two different laboratories.

1. Create another duplicate sample in Sormas and reference them as it would be done by manually referring a sample to another lab in Sormas.
    - downside: the sample would be duplicated

2. Merely change the facility (lab) of the sample that is being referenced
    - downside: the sample cannot have separate information regarding the processing of the sample, e.g. `receivedDate` or `labSampleID`

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup We should go with option 1 for now to keep it consistent with what is already implemented. If there will be changes in the future, these would then have to considered for samples overall.

**Comment by FredrikSchaeferVitagroup** [comment]
After discussion with @kwa20, it came out that it is better to not fill the duplicate sample with information from the lab message, but with data from the existing sample.

Also, the fields `fieldSampleId`, `specimenCondition`, `samplingReason`, `samplingReasonDetails` and `samplePurpose` should always be migrated.
