### ISSUE TITLE
Improve description of s2s property `central.location.sync`

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#7208]
### Problem Description
A new property was introduced with 1.65 which is described poorly
```
# Enable location data sync with central
#central.location.sync=
```

### Proposed Change
Update the description to include more information about the supported values and the default value and also a better description.
```
# If set to true, all infrastructure data from the central location will be synchronized into the local SORMAS database at startup and on a nightly basis.
# Default: false
# Possible Values: true, false
#central.location.sync=
```

**Comment by JonasCir** [comment]
@vidi42 
I think it would even make sense to pair this with the general property that switches s2s on. I don't know how viable it is to have s2s enabled without central sync as well.

**Comment by vidi42** [comment]
For now this ticket can be about just adjusting the documentation and probably your suggestion can be part of a bigger refactoring done in https://github.com/hzi-braunschweig/SORMAS-Project/issues/6034
