### ISSUE TITLE
[DEMIS2SORMAS] Map Disease Variants [2]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7209]
### Situation Description

The DEMIS profiles (old and new) allow to transmit disease variants. They should be transferred to SORMAS The user shall be supported with that by an automated mapping.

Disease variants are likely to change over time. As they are stored as a customizeable enum in SORMAS, they may also very from SORMAS-instance to SORMAS-instance.

### Feature Description

- [ ] Add the diseaseVariant and diseaseVariantDetails attributes to the TestReport dto and entity. Both should be of type String.
- [ ] When migrating attributes from a test report to a pathogen test, always try to migrate the disease variant according the the following procedure: 

> 1. When there is a customizable enum value equal to the testReport's diseaseVariant, set this in the pathogen test
> ~~2. When 1 did not succeed and there is an clearly identifyable cusomizeable enum value representing `OTHER`, set this in the pathogen test and put the testReport.diseaseVariant into the pathogenTest.diseaseVariantDetails~~
> 3. When 1 and 2 did not succeed, migrate testReport.diseaseVariant and testReport.diseaseVariantDetails to the `pathogenTest.testResultText`

- [ ] In case of 1. and 2., migrate the testReport.diseaseVariantDetails to pathogenTest.diseaseVariantDetails

**Comment by vidi42** [comment]
@FredrikSchaeferVitagroup please open a new ticket for the DEMIS adapter

**Comment by vidi42** [comment]
@kwa20 the solution in this ticket is based on the assumption that productive instances are all configured with an disease variant which stands for `OTHER` and has the `hasDetails` flag set to true.

Do you know if this assumption is correct and, even more important, is it enforced somewhere in the setup scripts for Disease Variants?

**Comment by kwa20** [comment]
@vidi42 There is not an explicit value called `OTHER` but there is a corresponding value named `ANDERE/SONSTIGE`. In hindsight, this might not be an ideal name for a value but this would be the corresponding value for `OTHER` on german servers. Since Netzlink is  administrating the diseaseVariants for germany according to HZI specification, this value should be present on all servers and yes, all should have `hasDetails` set to true

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT

**Comment by FredrikSchaeferVitagroup** [comment]
Best to be tested together with [#42](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/42) with a local DEMIS2SORMAS setup.
