### ISSUE TITLE
Person form cards don't hug lengthy content

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7213]
### Bug Description

Person form cards do not hug the content when it's lengthy
### Steps to Reproduce

1. Enter lengthy event title or point of entry details
2. Check the person form
3. Set the case classification to e.g. confirmed unknown symptoms and check the cases card
4. Toggling between languages let's lengthy translation overlap with the edges too

### Expected Behavior

Cards should hug their content
### Screenshots

<img width="381" alt="personFormCards2" src="https://user-images.githubusercontent.com/70317594/140986454-31e9fd82-fb5f-4b28-9bcb-ba1708acae2a.PNG">

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on test-de1.sormas.netzlink.com using the latest version of Sormas 1.66.0-SNAPSHOT.
