### ISSUE TITLE
Add missing entities to database tables to the data dictionary and the database export [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7220]
### Situation Description

Currently, data base tables related to lab messages are neither displayed in the data dictionary, nor availabe as an export.
### Feature Description

Add the following missing entities to the database export:

- [ ] SormasToSormasOriginInfo (root)
- [ ] SormasToSormasShareInfo (root) with ShareRequestInfo
- [ ] ExternalShareInfo (root)
- [ ] PortHealthInfo (Case)
- [ ] MaternalHistory (Case)
- [ ] LabMessage (root)
   - [ ]  Add the lab message related tables to the data dictionary
   - [ ]  Add the lab message related tables to the database export

Finally:

- [ ] Add a unit test that goes through all classes with an Entity annotation in sormas backend and checks whether they have an entry in DatabaseExportTable whose tableName matches Entity.name.

**Comment by markusmann-vg** [comment]
should be covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/6951

**Comment by JaquM** [comment]
@leventegal-she why is this not exportable?
LastVaccinationDate, LastVaccineType and FirstVaccinationDate would be very important for export.

**Comment by leventegal-she** [comment]
@JaquM LastVaccinationDate, LastVaccineType and FirstVaccinationDate are not database tables, they are used only for having these values displayed in the immunization directory

**Comment by kwa20** [comment]
@leventegal-she Wouldn't these variables be part of the vaccination table now?

**Comment by leventegal-she** [comment]
@kwa20 it's just a UI feature

The database export is used for downloading the data stored in the backend as you would go to the database and you would export it directly from the DB.

To have these values in a csv, you needuse the export on the Immunizations directory page.

**Comment by kwa20** [comment]
@leventegal-she Oh yes sorry, the `vaccinationdate` will be exported anyway because that's part of the new vaccination table now, got that confused, thanks.

**Comment by JaquM** [comment]
@leventegal-she are there any more open questions?

**Comment by leventegal-she** [comment]
@JaquM 

The following entities have representation in the database so those could be exported by the `database export`:

PopulationData, ManualMessageLog, SurveillanceReport, ExportConfiguration, FeatureConfiguration, Document, DiseaseConfiguration, SystemEvent, WeeklyReportEntry, AuditLogEntry, AggregateReport, WeeklyReport, UserRoleConfig

Which of these needs to be exported?

**Comment by MateStrysewske** [comment]
@leventegal-she @JaquM I'd exclude ExportConfiguration, Document, SystemEvent, and AuditLogEntry. It would make sense to export the other tables.

**Comment by MartinWahnschaffe** [comment]
Sorry for missing this. Rechecked this with Maté. @leventegal-she Please export:

- [ ] PopulationData,
- [ ] SurveillanceReport
- [ ] ExportConfiguration
- [ ] FeatureConfiguration
- [ ] Document
- [ ] DiseaseConfiguration
- [ ] WeeklyReportEntry
- [ ] AggregateReport
- [ ] WeeklyReport

Don't export

- ManualMessageLog
- SystemEvent
- AuditLogEntry
- UserRoleConfig (as this will be changed soon anyway and will likely be confusing users)
