### ISSUE TITLE
[Hospitalization] The description box on the Hospitalization tab is not disabled when the Current Hospitalization is empty

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7227]
### Bug Description
When the Current Hospitalization is empty, everything below the "Was patient admitted at the facility as an inpatient?" field and above "Current Hospitalization" should be greyed out. That includes the Description box, which can be edited and can be saved, but in fact it should be disabled.

### Steps to Reproduce

1. Open a case which has the place of stay set to "Home"
2. Go the the Hospitalization tab

### Expected Behavior
The Description box should be disabled.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/141290720-4592483d-badb-4226-9f46-16f676fce7a1.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.66.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: NatUser, Admin

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest build of sormas 1.66.0 on local environment
