### ISSUE TITLE
Setting disease variant to NULL results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7229]
### Bug Description

When setting the disease variant field back to NULL, an error occurs.
### Steps to Reproduce

1. Create a case and select a disease variant, save
2. Deselect the variant field

### Expected Behavior

No error should occur
### Screenshots

![nullVariantDiseaseVariantDetails](https://user-images.githubusercontent.com/70317594/141305942-73286155-afa2-4133-a229-84f779029f50.PNG)

### System Details

* Device:
* SORMAS version: 1.65.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 This bug also exists in the event edit form, the pathogen test form and the travel entry create and edit forms. Will be fixed for those as well.

**Comment by alexcaruntu-vita** [comment]
And I also fixed it for case create form.
