### ISSUE TITLE
Disease variant details field missing fro pathogen tests in sample creation form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7230]
### Bug Description

The disease variant details field is missing for pathogen tests that get directly entered with a sample.
### Steps to Reproduce

1. Open a case and create a sample
2. Check the box: "Create test result for this sample now"
3. enter a disease variant that enables the details field
4. Check if the details field appears

### Expected Behavior

The details field should also appear when pathogen tests are directly entered with samples
### Screenshots

![diseaseVariantsdetails](https://user-images.githubusercontent.com/70317594/141307355-173184d1-03ae-4cec-ae6b-397e8b229c47.PNG)
 
### System Details

* Device:
* SORMAS version: 1.65.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of Sormas 1.66.0-snapshot on localenvironment
