### ISSUE TITLE
[Disease variant] Disease variant details field is enabled when 'Unknown' is selected

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7233]
### Bug Description
The disease variant details free text field is enabled upon selecting 'Unknown' in the dropdown.

### Steps to Reproduce

1. Open a case which has Covid19 selected as disease.
2. Set the disease variant to unknown.

### Expected Behavior
The disease variant details free text field should not get enabled upon selecting 'Unknown'

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/141333845-d4d4f1d1-91f7-4210-ba60-ad5501fe6434.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0
* Android version/Browser: Chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: Admin

### Additional Information
This also happens on the Edit pathogen test results form.

**Comment by MateStrysewske** [comment]
@roxanamlendea Disease variants are customizable, i.e. there are no default values for it. Whether or not the disease variant details field appears when selecting a disease variant depends on the database configuration - in this case the server has been set up to display the details field for every single disease variant, including unknown. :)

**Comment by kwa20** [comment]
@roxanamlendea @MateStrysewske I just checked the values in the table on this instance and the script that was executed to enable/disable the field did not cover the "Unknown" value because they differed from the other instances values. So this was actually my fault.
