### ISSUE TITLE
Adjustments to the jurisdiction definition process of event participants [1]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7234]
### Feature Description

Event participants have a responsible region and district that are optional unless the associated event's location does not have a region and district.

### Problem Description

Event participants can still be created without a responsible region and district because the fields are not part of the creation form - they just can't be edited afterwards anymore without specifying these fields. Moreover, it is possible to create event participants without a responsible jurisdiction and then remove the region and district from the event which will lead to the event participants not having a clear jurisdiction anymore. This is problematic at least for the reduced immunization module because we have to rely on an event participant having some kind of jurisdiction to create the immunizations there, but potentially also messes with the visibilities in general.

### Proposed Change

* Add the responsible jurisdiction fields to the event participant creation forms (web and mobile). Make them mandatory when the associated event location does not have a region and district.
* In the event edit form, make the region and district fields of the event location mandatory and the country read-only if at least one of its event participants does not have a responsible jurisdiction. Write a new backend method in the EventFacade/EventDao that checks this and call it `hasAnyEventParticipantWithoutJurisdiction`. Add an info icon next to the country with a hint why it's not editable.

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.66.0-SNAPSHOT for the vaadin app and on Android 11 phone connected to the server https://test-de.sormas.netzlink.com/sormas-rest/ for the android app.
