### ISSUE TITLE
Add responsible jurisdiction fields to event participants in the mobile app [1]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7235]
### Feature Description

Event participants in the web app have responsible region and district fields.

### Problem Description

The fields are missing in the mobile app which makes it possible to create event participants without a responsible jurisdiction for an event without a region and district.

### Proposed Change

* Add `responsibleRegion` and `responsibleDistrict` to the event participant entity and datbase in the mobile app.
* Extend the `fillInnerFromDto` and `fillInnerFromAdo` methods accordingly
* Add the fields to the creation and edit fragments. Make them mandatory if the associated event location does not have a region and district.

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server https://test-de1.sormas.netzlink.com/sormas-rest/
