### ISSUE TITLE
[Angular] Line listing Backend integration [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7238]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/CA843944-9CDD-42A7-8BB7-113F2AD7320A
- Based on the work done under: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6965 and the updates done on the backend, we need to integrate the latest BE as to provide the required functionality.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
