### ISSUE TITLE
Display when an entity is going to be automatically deleted [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7240]
### Situation Description
#7008 adds automatic deletion for entities that is silently happening every night.

### Feature Description
User's should see when an entity is going to be deleted. This is mostly relevant for short-living entities, like travel entries (may have a deletion period as short as 14 days).

Should be displayed in a decent red, when the deletion is within the next 180 days or the user has the right to delete the entity. Otherwise it should be a light grey, so that it's barely visible. Do not show anything, if not automatic deletion is configured.

I suggest to display this at the bottom of the main form of the entity (case, contact, event, event participant, travel entry, immunization).
![grafik](https://user-images.githubusercontent.com/23217632/141449305-d4af408e-806d-45f3-90d8-54bad008aae4.png)

The user can click the information to open a popup or tooltip that displays the following information:

> Deletion scheduled for 10/11/2031
> ------------
> End of processing: 09/11/2021
> Deletion period: 10 years

### Implementation

- [x] Extend the CoreEntityFacade (introduced in #7008) to provide deletion information for the entity the user is viewing
  * deletionDate
  * deletionPeriod
  * deletionReference
  * deletionReferenceDate (actual date of the entity depending on the deletionReference)
- [x] Display the information at the bottom of the (first) entity form, as described above.
  * The deletion period should be displayed in the biggest time scale that makes sense (years, months, days)
    * multiple of 30 days = months
    * multiple of 365 days = years
    * something else: always days

### Additional Information

* The "end of processing" is currently simply the change date of the core entity. This will be changed in a follow-up issue
* The "date of origin" for the travel entry will be renamed to the more specific "date of arrival" once we have that field.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.68.0-snapshot on the local environment.
The notifications are present and color-coded.

**Comment by adinaflorea9** [comment]
For testing purposes, the configurations necessary to enable the 'Scheduled deletion date':

In the Data Base, 'deleteconfiguration' panel:
- - deletionreference - query tool - update deletionconfiguration set deletionreference='CREATION' where id<129;
- deletionperiod - query tool - update deletionconfiguration set deletionperiod=2 where id<129;

Note: '129' is the id value specific for my DB, when testing, this needs be changed based on the id value from that specific DB
