### ISSUE TITLE
[Person directory] When sorting the persons by region, district and community, if opening a result and then going back, the results are still filtered, but the filters are no longer selected

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7241]
### Bug Description
On the Person Directory page, when sorting the persons by region, district and community, if opening one of the results and then going back on the Person Directory, the results are still filtered, but the filters are no longer selected.

### Steps to Reproduce

1. Open the Person Directory
2. Filter by Region, District and Community
3. Open one of the results.
4. Go back on the Person Directory

### Expected Behavior
The filters should still remain selected.

### Screenshots
![person directory filters](https://user-images.githubusercontent.com/89522688/141453330-bc500667-6d54-4038-89bb-933494263c1e.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0
* Android version/Browser: Chrome
* Server URL: release-international.sormas.netzlink.com
* User Role:

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment on sormas 1.67.0-snapshot
