### ISSUE TITLE
[Task Management][Filters] 'Task status' filter is set to 'pending' by default

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7242]
### Bug Description
When opening the Task Management page, the 'Task status' filter is set to 'pending' by default.

### Steps to Reproduce

1. Open the Tasks tab
2. Inspect the filters

### Expected Behavior
The filter should be set to 'null' and the filter name should be displayed: 'Task status'.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/141462585-d2bf0726-07de-4978-ab65-8e8b761d0da1.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0
* Android version/Browser: Chrome
* Server URL: release-international.sormas.netzlink.com
* User Role:

**Comment by MateStrysewske** [comment]
@roxanamlendea This is done on purpose (because completed tasks aren't the main focus of users who enter this view). @kwa20 I suspect this is wrong in your test specifications?

**Comment by roxanamlendea** [comment]
I didn't know this was on purpose. I assumed it was a defect because it was the only filter where there was something set by default.
