### ISSUE TITLE
Add a box and a button allowing users to access SORMAS-STAT

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#7244]
### Situation Description

To date, no button allows users to access SORMAS-STAT from SORMAS.

### Feature Description

We propose to develop a button in the “STATISTICS” part. By clicking on this button, the user will be directed directly to the URL hosting SORMAS-STAT. This URL being different for each server, it is important to be able to configure the URL to which this link will point.

![image](https://user-images.githubusercontent.com/65449450/141480142-447e54cc-7b60-4f21-b8ca-cc144f35635c.png)

### Additional Information
@bernardsilenou @ftavin @emond-fuseau @olivierleuci

**Comment by kwa20** [comment]
@carolinverset what do you think of placing the button in the header? This might be more obvious and don't move with the form.

![Sormas Stats Button](https://user-images.githubusercontent.com/70317594/141481329-c10dafb5-0a85-40e4-a623-48501d2cd12a.png)

**Comment by carolinverset** [comment]
@kwa20 
Yes, good idea ! @ftavin, are you ok with this ? 

@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
@ftavin 
1. I think we can add it in the configuration file, 
`SORMAS-STATS_ENABLED=false` as default
2. Yes please, we should hide the button if the url has not been set.
@kwa20  @MateStrysewske  Is my response OK?

**Comment by MateStrysewske** [comment]
@bernardsilenou Probably makes sense to add a property, I'd call it `sormasStatsUrl` though.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- The plan is to add url now and later add an additional icon in the statistics section or dashboard. Can we use only one property for all? thus call it something like `sormasStatsModule`

**Comment by MateStrysewske** [comment]
@bernardsilenou The logic would be that if the URL is missing, the stats module elements wouldn't be shown because they couldn't connect to anywhere. The property is way more self-explanatory that way though :)

**Comment by bernardsilenou** [comment]
@MateStrysewske  Planned for 167

**Comment by mario-kuehne** [comment]
Sucessfully tested on local machine.

**Comment by bernardsilenou** [comment]
@mario-kuehne
1.  When I clicked on the icon 'open sormas stats', the current sormas tab is replaced by the sormas-stats tab.
2. The expected behaviour (non mentioned in the initial ticket) is to maintain the current sormas tab and open another tab for sormas-stats
Please can you let us know if you experienced 1. or 2. during testing.

@ftavin @MateStrysewske @fhauptmann   FYI
