### ISSUE TITLE
Pressing dicard in travel entry forms does not uncheck the differing point o entry jurisdiction

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7245]
### Bug Description

When discarding entries on the travel entry form, the point of entry jurisdiction difference checkbox does not get unchecked. 
### Steps to Reproduce

1. Create a new travel entry but leave the jurisdiction the same for the point of entry.
2. In the form, check the checkbox "Point of entry differs from responsible jurisdiction"
3. Press discard

### Expected Behavior

The checkbox becomes unchecked

### Screenshots

![discardTravelEntryForm](https://user-images.githubusercontent.com/70317594/141480485-bdb1e9b2-b8a5-4cec-a709-342ca24b5413.PNG)
![discardTravelEntryForm2](https://user-images.githubusercontent.com/70317594/141480478-5e0e417c-544c-4967-98d3-1a52f69b53db.PNG)

### System Details

* Device:
* SORMAS version: 1.65.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by syntakker** [comment]
The same problem exists in `CaseDataForm` with the checkbox for different place of stay jurisdiction.
![image](https://user-images.githubusercontent.com/5616564/146468059-7b5e1c5e-350e-4925-ab91-600c8e12917f.png)

**Comment by roxanamlendea** [comment]
I tested the ticket on test-de1.sormas.netzlink.com and when "Point of entry differs from responsible jurisdiction" is checked and I click on "discard", an "(inactive)" suffix appears after the Point of Entry. 
![image](https://user-images.githubusercontent.com/89522688/146753417-7e7d9dbe-4caf-4197-842f-0435b0258c53.png)

**Comment by adinaflorea9** [comment]
Verified ticket on test-de2.sormas.netzlink.com, using the latest version of Sormas 1.68.0-SNAPSHOT.
