### ISSUE TITLE
Refactor CoreAdo to include archiving [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7246]
### Feature Description
The CoreAdo class is used by several classes that need to be soft-deleted. In addition we have multiple classes that allow archiving. All of those classes implement this on their own. For all classes besides the infrastructure ones, there is currently no generic facade.

### Problem Description
Trigger for this issue is the new field "endOfProcessingDate" that is needed for all core entities (see #7247). The current CoreAdo class does not represent the actual core entity from the SORMAS domain perspective.
Also there is a lot of redundant code in the facades that should be replaced by an abstract implementation.

### Proposed Change
- [x] Rename CoreAdo to DeletableAdo (name is not ideal, but we didn't come up with something better yet)
- [x] Introduce new CoreAdo class that extends DeletableAdo. Should be extended by the following classes: Case, Contact, Event, EventParticipant, Immunization, TravelEntry, Campaign
  * Take the comment from the previous CoreAdo and adjust it as follows: The integral definition of core data is that it is the working representation of a real-world event that is archived once the work is complete.
 * relevant for external systems that share data with or use data from SORMAS.
- [x] Move the existing archived property of those classes to the CoreAdo
- [x] For contact and event Part make the archived property transient in the entities
- [x] Move the archive methods from AbstractBaseEjb to AbstractInfrastructureEjb
- [x] Create an AbstractCoreEjb that does for CoreAdo classes what AbstractInfrastructEjb is doing for InfrastructureAdo classes. Facades for Case, Contact, ... should use this

### Additional Information

* We could introduce an Archivable interface to enable sharing of code for CoreAdo and InfrastructureAdo

**Comment by JonasCir** [comment]
> We could introduce an Archivable interface to enable sharing of code for CoreAdo and InfrastructureAdo
I would really like to see something like this. This is the last missing piece to wire up e.g., Immunization with the abstract classes we have. By this, we can save a lot of code duplication, so I'm all in favor! :)

**Comment by adinaflorea9** [comment]
Today, @roxanamlendea  and I found that on our local testing machines and on the test instances (test-de1, test-de2, test-de3) various entities can not be opened:

- [ ] Cases
- [ ] Contacts
- [ ] Event Participants
- [ ] Samples 
- [ ] Tasks

Also, when trying to convert into a case an event participant that can not be opened, an error message is displayed - 'An error has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it.'

As agreed with @MateStrysewske we have reopened the ticket and attached the logs to this comment:

[Logs for opening a contact on the local machine.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8041910/Logs.for.opening.a.contact.on.the.local.machine.txt)

**Comment by JonasCir** [comment]
https://stackoverflow.com/questions/3154582/why-do-i-get-a-null-value-was-assigned-to-a-property-of-primitive-type-setter-o

**Comment by adinaflorea9** [comment]
Verified the issues reported in the comment from Feb 10, 2022, regarding various entities that could not be opened and event participants that could not be converted into cases, on local machine, using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.

**Comment by adinaflorea9** [comment]
Verified ticket on local environment (covered the following directories: tasks, persons, cases, contacts, events, samples, immunizations and users) using the latest version of SORMAS 1.69.0-SNAPSHOT from the development branch.
