### ISSUE TITLE
CoreAdo: Introduce "end of processing date" [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7247]
### Situation Description
The automatic deletion of entities #7008 is currently using the change date of the core entity. 

### Feature Description
We want users to be able to also retrospectively define **that** and **when** a case/contact/... is no longer processed. This will be the reference date for the "end of process" deletion type.

When a user decides to archive a case, the system shows a popup that shows the end of process date - pre-filled with the latest change date of the case and it's sub-entities ("aggregated change date). The user can edit it if needed. 

When a case is automatically archived, the end of process date is automatically set to the last aggregated change date

When a user de-archives a case, the endOfProcessDate is automatically cleared and the user has to enter a reason for de-archving.

### Implementation

Pre-requisite: #7246!

The changes below affect: Case, Contact, Event, Event Participant, Immunization, Travel Entry, Campaign

- [x] Add endOfProcessingDate to CoreAdo
- [x] Implement popup as described above (see #7240 for reference on which forms are affected). For now use the entity's change date. The aggregated change date will be provided by #7319 later on.
- [x] Add an archiveUndoneReason text field to the CoreAdo. When de-archiving core entities show a popup where the user has to enter a reason (single archive and bulk archive). The text field should be shown read-only in the entity

### Out of scope
* Migration: Add a script to calculate the endOfProcess date for entities that are already archived

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe What about batch archiving?

**Comment by kwa20** [comment]
@sergiupacurariu I tested this implementation on test-de2.sormas.netzlink.com (https://github.com/hzi-braunschweig/SORMAS-Project/commits/0b4ed18a707edc2cd49a5399942a645d153cd632) and noticed that the date format does not seem to respond to the country specific configuration:

e.g. german language setting
![endOfProcessingDate](https://user-images.githubusercontent.com/70317594/156187698-69fd3249-18a1-4e35-bf0d-4c21c3ec56c3.PNG)
