### ISSUE TITLE
Community officers cannot edit region and district fields on the travel entries form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7248]
### Bug Description

When a community officer edits the travel entry form and selects "Point of entry differs from responsible jurisdiction", they can not edit the region and district for the point of entry.
### Steps to Reproduce

1. Log in as a community officer
2. Create a travel entry where the point of entry location matches the responsible jurisdiction
3. In the creation from, select "Point of entry differs from responsible jurisdiction"
4. Deselect the checkbox again

### Expected Behavior

The user should be able to specify a differing region and district for the point of entry
### Screenshots

![CommunityOfficerTravelEntriesError2](https://user-images.githubusercontent.com/70317594/141485468-1743aeac-964b-40d1-bfa3-eaeca9cd5227.PNG)
![CommunityOfficerTravelEntriesError](https://user-images.githubusercontent.com/70317594/141485465-fc1956fa-f348-4869-afbe-5c40d454ea01.PNG)

### System Details

* Device:
* SORMAS version: 1.65.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Community Officer

### Development Specifications
* Prevent users with community level to edit the responsible region and district of points of entries
* Prevent users with facility level to edit the responsible jurisdiction of points of entries at all
* Allow all users with edit access to specify that the point of entry lies in a different jurisdiction, and allow all these users to see and edit the region and district fields below

**Comment by MateStrysewske** [comment]
@kwa20 The general pattern in SORMAS is that users on a relatively low level (i.e. especially communities and facilities or points of entry) aren't allowed to create data outside their jurisdiction, so in this case in other communities. I'd actually say that the bug here rather is that community officers are able to edit the responsible region and district in the first place. With the same reasoning, the "point of entry jurisdiction differs from responsible jurisdiction" checkbox should be disabled for them because they should also not be allowed to edit the place of stay region and district.

However, this is a point of discussion because it matches the overall pattern in SORMAS, but might not make sense in the context of travel entries. Can you re-evaluate this issue with this in mind?

**Comment by kwa20** [comment]
@MateStrysewske For the jurisdiction it would be fine but even a community officer that collects a travel entry in their juridiction needs to be able to specify the location of the point of entry if it differs from their jurisdiction. I assume that this is even the case most of the time.

**Comment by MateStrysewske** [comment]
@kwa20 True!

So the specifications would be like these:

* Prevent users with community level to edit the responsible region and district of points of entries
* Prevent users with facility level to edit the responsible jurisdiction of points of entries at all
* Allow all users with edit access to specify that the point of entry lies in a different jurisdiction, and allow all these users to see and edit the region and district fields below

**Comment by kwa20** [comment]
@MateStrysewske Sounds good to me

**Comment by ChristopherRiedel** [comment]
> @kwa20 True!
> 
> So the specifications would be like these:
> 
> * Prevent users with community level to edit the responsible region and district of points of entries
> * Prevent users with facility level to edit the responsible jurisdiction of points of entries at all
> * Allow all users with edit access to specify that the point of entry lies in a different jurisdiction, and allow all these users to see and edit the region and district fields below

@kwa20 To remain consistent, we will not implement the first point. So far, this is only the case in the Android app. If this is generally desired for the web app as well, please create a separate issue for it.

**Comment by kwa20** [comment]
@ChristopherRiedel Ok, is the jurisdiction disabled for all other limited user roles? e.g. officers?

**Comment by ChristopherRiedel** [comment]
@kwa20 The jurisdiction fields will be disabled for the JurisdictionLevel.HEALTH_FACILITY

**Comment by StefanKock** [comment]
No pull request, and not merged anywhere, so still open
