### ISSUE TITLE
Archived entities should always be read-only [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7249]
### Situation Description
Currently entities are either archived automatically or by an admin. Those archived entites are moved to another view in the directory, but can still be opened and edited by most users of the web application.

### Change Description
- [x] Archived entities should not be editable any more -> open as read-only
- [x] Add a check in the backend persistence methods
- [x] Adjust the German translation of archiving used for core entities (not infrastructure) to 
   * Archive (action) -> "Abschließen"
   * De-archive (action) -> "Wiederereröffnen"
   * archived (status) -> "abgeschlossen"
- [x] Add a feature configuration to disable "archived entities can be not be edited" 

### Additional information
- Remark: We also had "Sperren"("Lock") in mind, but I think this sounds too much like a functionality to temporarily lock the entity for editing by other users. 
- Out of scope: We might add a "prevent sync"-Functionality in the future.
- Defined as `change` on the "archive" feature, this ticket is not a new feature by itself.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
This is very similar to the need that lead to this issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/5743
1. If the user role has the right to de-archive the entity, then they would first need to de-archive before editing it, right?
 1.1 If yes, then all web users would ba able to later dearchive and further edit
2. The need for https://github.com/hzi-braunschweig/SORMAS-Project/issues/5743 was that if regional users archive/ close the entity, then no district or lower user would be able to edit it, no matter the archive status.

Since the goal is to prevent further editing, then what about the solution to instead add a new attribute for this ? Preventing archived entities from ever being edited may not be good since users can actively archived just to remove them from the mobile db.

**Comment by kwa20** [comment]
@MartinWahnschaffe @JaquM @bernardsilenou When we prevent editing of archived entities, this may become quite ugly when they can reach a state that hinders everyday work of users. With the new user role concept in mind, what about introducing an `EDIT_ARCHIVED_ENTITIES` user right which is given to the admin as default but could later then also be given to specific users.

Note for testing: we might want to check behaviours of actions where multiple entities are involved, e.g. conversion of (existing) entities

**Comment by MartinWahnschaffe** [comment]
Why would an every day user want to edit something that is already archived? The whole meaning of archiving is that the entity is no longer relevant and should not be worked on.

If we need a mechanism that excludes an entity from synchronisation to the mobile app, but still allows web users to work on it, we should seperate this from archiving.

**Comment by bernardsilenou** [comment]
@kwa20 
- If users want to continue working on the archived entity, then they can or ask a user with the right to archive to de-archive it.
- `EDIT_ARCHIVED_ENTITIES` would correspond to de-arciveing then entity, right?

**Comment by JaquM-HZI** [comment]
@MartinWahnschaffe I tested on https://test-de.sormas.netzlink.com/ and nearly all values were editable. 
![Archieve -  read only](https://user-images.githubusercontent.com/78568406/158810353-ada33e38-2b37-4aff-b140-c49bbbe65ad5.gif)

**Comment by MartinWahnschaffe** [comment]
@sergiupacurariu Please have a look at this.

**Comment by AndyBakcsy-she** [comment]
@JaquM-HZI  I have a question: 
Is the feature configuration enabled or disabled?  I am asking this as on my local setup this seems to be working correctly.
From the ticket's description:
- Add a feature configuration to disable "archived entities can be not be edited"

**Comment by sergiupacurariu** [comment]
@JaquM-HZI Most likely this is due to the feature configuration "EDIT_ARCHIVED_ENTITIES" which by default is "TRUE". If this feature configuration is set to FALSE readOnly will be triggered on Archived entities.

**Comment by AndyBakcsy-she** [comment]
Closing ticket as verified on the latest version of Sormas 1.70.0-snapshot on local environment.

**Comment by sergiupacurariu** [comment]
EDIT_ARCHIVED_ENTITIES
- Enables/disables the accessibility to archived core entities
- in case of disabling the feature
--all UI forms related to an archived entity will not be editable
-- prevents further changes to be saved on an archived entity

Entity types : CASE, CONTACT, EVENT, EVENT_PARTICIPANT, IMMUNIZATION, TRAVEL_ENTRY, CAMPAIGN

**Comment by MartinWahnschaffe** [comment]
@kwa20 This is the issue where we wanted to change the translations. We missed this, though, since we can't change it from development side - instead it has to be done in crowdin.

**Comment by kwa20** [comment]
@MartinWahnschaffe I was wondering if we are supposed to also re-translate everything that is neither core entity nor infrastructure data. This would include e.g. samples, tasks and event groups.
