### ISSUE TITLE
[Hospitalization] On the Previous Hospitalization form, the 'Start date' of the 'Stay in the intensive care unit' should be within the hospitalization period

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7250]
### Bug Description
When adding a previous hospitalization, on the form, the 'Start date' of the 'Stay in the intensive care unit' can be set after the discharge date.

### Steps to Reproduce

1. Open a Case
2. Go to Hospitalizations
3. Set Previous Hospitalization to 'Yes'
4. Create a new Previous Hospitalization
5. Set the 'Start date' of the 'Stay in the intensive care unit' to be > discharge date

### Expected Behavior
There should be a red exclamation mark and the user shouldn't be able to save the form until the start date is within the hospitalization period.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/141488338-68c264bc-e9bc-4076-9b9c-5dc671264d5a.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.65.0
* Android version/Browser: Chrome 
* Server URL: release-international.sormas.netzlink.com
* User Role:

### Additional Information
This only happens for the 'Start date', for the 'End date' there's red exclamation mark

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the web app, sormas 1.67.0-snapshot on local environment

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as on the mobile app the Stay in the intensive care unit End of stay field has no validation.
![image](https://user-images.githubusercontent.com/70562142/145220834-b729a647-d9ec-4f0c-bdd6-0f5765f04eaa.png)

I was able to set the Date of discharge or transfer before the end of stay in the intensive care unit
