### ISSUE TITLE
Create new case with point of entry fails for NatUser

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7252]
### Steps to Reproduce

1. Go to Case directory and click on New Case button
2. Select Point of Entry fo the case origin
3.  Fill in the required infomration
4. Check the chekbox : Point of entry of this case differs from its responsible /place of stay jurisdiction 
5. Add info of the point of entry and try to save

### Expected Behavior
 The case should be saved without the server crashing

### Actual Behavior
 The Server crashes in this scenario. Server log attached.

### System Details

* Device: Windows
* SORMAS version: 1.66.0-snapshot
* Android version/Browser: Chrome
* Server URL: localenvironment
* User Role: NatUser

### Additional Information

[server_error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7529174/server_error.txt)

**Comment by ChristopherRiedel** [comment]
The problem cannot be reproduced. "healthfacility_id" should not have a not-null-contraint. This is not the case in any of my databases. Also in sormas_schema.sql this does not occur, so the issue is closed.
