### ISSUE TITLE
Populate the performance test system with 50k cases and 100k related contacts in one district [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7266]
### Problem Description
Synchronising data to the mobile app is facing problems with the amount of data that is created during the pandemic.
Surveillance officers have access to the data on district level and are working with the mobile app. 

### Proposed Solution
Populate the system with at least 50k cases and 100k contacts using the approach taken for #5986.
Both cases and contacts need to have random data filled in (case data, symptoms, epi data). This is needed, to have a realistic amount of data synced to the mobile app (the system automatically strips empty fields from the synced data).

### Out of scope
For now we will not create visits for the contacts.

### Additional information
Besides making sure the data transfer is working correct we will also try to find solutions on how to reduce the actual amount of data synced to the device.

**Comment by bernardsilenou** [comment]
@BasilKaburi

**Comment by BasilKaburi** [comment]
@bernardsilenou 
Noted

**Comment by rdutu-vg** [comment]
Script is done.
Was set to create 100 cases with 2 linked Contacts per run.
Execution time on average takes 6-7min on my local machine.

**Comment by rdutu-vg** [comment]
Jenkins job created:
https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-CreateCasesWithLinkedContacts/
Works as expected, the system started getting populated with data.

**Comment by rdutu-vg** [comment]
Please note that the reference point for cases is ~10k, so we can consider that we reached the 50k once the counter will display at least 60k cases.

**Comment by rdutu-vg** [comment]
We managed to reach the requested number of entities.
Jenkins job has been stopped running automatically.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
Does this mean that we can now test  the mobile app in this district?
If yes, then @BasilKaburi would need access to the performance environment.

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou Two of the issues that are supposed to fix the problems are currently still being finalized (#7521 and #7303).
Razvan will test the current situation (see #7604). I will ask him to create an officer in the related district and send the credentials to you anyway.

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou Two of the issues that are supposed to fix the problems are currently still being finalized (#7521 and #7303).
Razvan will test the current situation (see #7604). ~~I will ask him to create an officer in the related district and send the credentials to you anyway, once he has tested it.~~ You will need to use the snapshot version of the mobile app to test this, so it probably doesn't make a lot of sense for you to do so.

**Comment by BasilKaburi** [comment]
@rdutu-vg 
@MartinWahnschaffe 
Please could you confirm if this is the correct test environment for testing the mobile app synchronisation?
https://support.netzlink.com/helplink/test-performance.sormas.netzlink.com

Currently, this link to the server is 404

**Comment by StefanKock** [comment]
> @rdutu-vg @MartinWahnschaffe Please could you confirm if this is the correct test environment for testing the mobile app synchronisation? https://support.netzlink.com/helplink/test-performance.sormas.netzlink.com
> 
> Currently, this link to the server is 404

It seems you are looking for this URL: https://test-performance.sormas.netzlink.com

**Comment by rdutu-vg** [comment]
@BasilKaburi , https://test-performance.sormas.netzlink.com was the environment populated with data

**Comment by BasilKaburi** [comment]
@rdutu-vg @StefanKock Great! Thanks!

**Comment by bernardsilenou** [comment]
@rdutu-vg @StefanKock 
Please can any of you create an admin user account on https://test-performance.sormas.netzlink.com and send the credentials to either Basil or me?
bernard.silenou@helmholtz-hzi.de
basilbenduri.kaburi@helmholtz-hzi.de

Thanks
