### ISSUE TITLE
Details field for Disease Variant Unknown should be hidden

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#7270]
### Bug Description

For Cases, PathogenTests and Events, the field "Disease Variant Details" should be hidden if the chosen Disease variant is "unknown".

### Steps to Reproduce

1. Got to the respective Case / PathogenTest / Event edit form
2. Chose a disease with variants, chose disease variant "unkown"

### Expected Behavior

"Disease Variant Details" should be hidden.

### Screenshots

![image](https://user-images.githubusercontent.com/5616564/141784866-4aca2fca-9dc3-4ff0-a72b-576686819884.png)
![image](https://user-images.githubusercontent.com/5616564/141784894-b90f4c7d-1488-4cb2-ac22-6aea523a0363.png)
![image](https://user-images.githubusercontent.com/5616564/141784910-527008e3-e1eb-4ae3-a1ea-b5350bf5d5dd.png)

### System Details

* Device: Android Emulator
* SORMAS version: 1.65.0
* Android version/Browser: API 24
* Server URL: https://release-international.sormas.netzlink.com
* User Role: Contact Officer & Surveillance Officer

**Comment by MateStrysewske** [comment]
@syntakker Disease variants are customizable enum values, i.e. there is no default behaviour. The data on the instance you've been working on has been wrongly inserted into the database. See #7233.

**Comment by MateStrysewske** [comment]
@kwa20 Yup.
