### ISSUE TITLE
Import of Contacts are not updating person details

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7276]
### Bug Description

When importing cases the details of the person (address, sex, salutation) are updated. If you import contacts the details are NOT updated.

I would expect that they are always updated by the imported details for cases, contacts and ep.

I will add screenshots during the next days.

**Comment by Marko-ilmkreis** [comment]
Here are two screenshot, one of the duplicate detection, where you can see which data should be updated for the person (sex, dob):

![image](https://user-images.githubusercontent.com/74791118/141977174-d9fcc8f5-fadb-42c5-8184-7823a0bbecc4.png)

and the person after the import:

![image](https://user-images.githubusercontent.com/74791118/141977303-5e5780de-0c7e-4992-a064-282037645c21.png)

**Comment by Marko-ilmkreis** [comment]
By importing a case, the details are updated:

![image](https://user-images.githubusercontent.com/74791118/141982123-5683953d-86f0-4cd1-bb18-b367a93b3e86.png)

![image](https://user-images.githubusercontent.com/74791118/141982155-0667a2e2-cdaf-458c-8ea0-67a6b8942325.png)

**Comment by vidi42** [comment]
There's already a PR started for this ticket, however, there are some issues when merging the contact information of persons.
