### ISSUE TITLE
[Angular][Bug] Make current location widget more generic [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7287]
### Bug Description

- The Validation for filters still doesn't work as intended
- The rendering should be handled by the current "hidden" drop downs above the widget (the main form)
- Remove the rendering inside the widget (as it should work with the one from the main form)
- In the widgetInfo: [{key:'region.uuid', depending:'country.uuid', service:'regionService'}]
- This should be able to function even if the data is nod fed by the Backend and only present from Angular (hardcoded). 

### Steps to Reproduce

1. N/a
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
