### ISSUE TITLE
[Angular] Dashboard: Filters [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7288]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/08E60D4D-604F-4047-9EFE-B98D923A585A
- Reference update for filter: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/paA4vQQ
- @cristinacoza please update the Filter design as to resemble what we discussed in the Refinement meeting
- This task will only focus on the Filters section (including the "Reset" functionality)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
