### ISSUE TITLE
[Angular] Empty value for select dropdowns [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7289]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/a
- We need an empty value for all dropdowns used across the board so the user is able to clear one of them (where it makes sense, if the field is required such an option shouldn't be present as it doesn't make sense).
- This is applicable for fields present in the dynamic form.
- Design here: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm9VkaO

<img width="151" alt="Screenshot 2021-12-08 at 11 21 01" src="https://user-images.githubusercontent.com/78347216/145182554-741196cd-2c2e-4573-8ada-526e62a9aaa1.png">

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
