### ISSUE TITLE
Section menu improvements [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#729]
eg if previous hospitalization is "yes",  The menu icon blocks the icon to create a previous hospitalization

- [x] Section menu icon blocks field in the app -> Add a blank footer, so users can always scroll down (fragment_root... layout)
- [x] Remove numbers and make section captions bigger when not icon is provided
- [x] Repair visual indicator which section is selected (right now, all sections are highlighted in blue when first entering a fragment, when first changing section, everything is changed to black)

**Comment by MateStrysewskeSym** [comment]
- [ ] use icons for all page menus

This is how it looks like without the navigation number:

![grafik](https://user-images.githubusercontent.com/23701005/44465250-55e2f600-a61d-11e8-9ed4-d479dbf0685c.png)

From our point of view, that doesn't look too good. It's probably better to find icons for the page menus that don't have one yet and use those instead.
