### ISSUE TITLE
[Angular] Dashboard: Slideshow Disease section [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7295]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- We will add the icon for slideshow (which currently doesn't do anything) @MateStrysewske to discuss with @cristinacoza and understand if the action actually needs to do something.
- When selecting a new disease from this section, everything below this section will be updated with data pertaining to the new disease
- This will be a event for the entire page which will send the params to the rest of the components

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
