### ISSUE TITLE
[DEMIS2SORMAS] Add filters and columns to the lab message directory

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7309]
### Situation Description

Currently, users have a hard time managing large numbers of incoming lab messages. They can't process them fast enough and they struggle to report cases to higher health institutions in time. Thus, they would like to filter the directory in order to distribute work and make processing more efficient.

concept issue: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7308
### Feature Description

- Add the following filters to the lab message directory
    - Search field (free text) - should filter for:
        - UUID
        - name (first name, last name)
        - postal code
        - lab name
        - lab postal code

- Add a 'Date of birth' column to the list next to the person last name
    - This column should display the persons date of birth according to the contents of the lab message
    - The column should be sortable by earliest to latest and vice versa

- Add date range filters consisting of
    - 'Lab message reference date' (drop-down)
        - Message date
        - Date of birth
    - 'Date from' (date field)
    - '... to' (date field)
    - The specified date should filter the range (including set dates) for the specified type in 'Lab message reference date'
        - The selection of just one of the date fields should filter for the set date

- Add buttons to 
    - 'Reset filters' - resets all selected filters upon clicking
    - 'Apply filters' - applies all the specified filters; filtering should not start unless this button is pressed
### Additional Information

![Lab messages Refinements_filters](https://user-images.githubusercontent.com/70317594/142231088-bb619383-86ce-41d3-a2bb-4d8d298043d9.png)

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT

**Comment by FredrikSchaeferVitagroup** [comment]
> Search field (free text) - should filter for:
> * UUID
> * name (first name, last name)
> * postal code
> * lab name
> * lab postal code

@kwa20 Thank you for the detailed specification! I have one small  question about the above. `lab name` and `lab postal code` exist multiple times. A lab message has those fields, but test reports related to the lab message also have them. I assume the search should just consider the fields in the lab message. Is this correct?

At the moment, those fields are always filled with identical values, but this might change in the future.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I reckon that the columns on the directory display the `lab name` and `lab postal code` from the lab message? Then yes, that's correct

**Comment by syntakker** [comment]
@kwa20 is there a specific reason to chose the reference date (message date or date of birth) in a dropdown instead of just having a pair of from...to date fields for each of these two criteria?

**Comment by kwa20** [comment]
@syntakker Main reason would be consisntency with other directories, even though this has been done differently already in e.g. the event actions directory for reasons I don't know exactly. One more reason might be that if more date ranges will be added, the filter section can get cluttered.

However, if separating the range filters enables us to use them simultaneously, I think that would actually be very advantageous and should be favoured if that is possible.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of the hotfix 1.66.1 branch on the local environment.
