### ISSUE TITLE
[DEMIS2SORMAS] Add the option to assign lab messages to users [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7310]
### Situation Description

Currently, users have a hard time managing large numbers of incoming lab message. They can't process them fast enough and they struggle to report cases to higher health institutions in time. Thus, they should be able to assign lab messages to users to manage and distribute work more efficiently.

concept issue: #7308
### Feature Description

- [x] Add a column to the lab message directory in between 'Status' and the 'Process' column
    - [x] Heading: 'Assignee'
    - [x] If there is no assignee set for a lab message, display the text 'Assign' in the respective cell
        - [ ] While hovering, indicate that this text is clickable by changing the colour slightly and underlining the text (cf. uuid's for reference)
        - [x] Upon clicking on 'Assign', open a pop-up
            - [x] Heading: 'Edit assignee'
            - [x] Add a drop-down field for the user selection; heading: 'Assignee'
            - [x] Add a clickable text: 'Assign to me'
                - [x] Upon clicking, automatically select the current user as the assignee
            - [x] Add 'Discard' and 'Save' buttons
                - [x] Pressing 'Discard' should discard the user selection and close the pop-up
                - [x] Pressing 'Save' should save the set user as the assigne and close the window
    - [x] When a user was selected as the assignee, display the username in the respective cell (username text not clickable anymore)
         - [x] In the same cell, display a 'More' icon that fills the cell but does not get overlayed by the username
             - [x] The icon must be present in the cell at all times and should not float out of the visible cell when adjusting the width
             - [ ] If the cell gets clinched, the icon must overlay the username text. When clinched, the username text should float out of the cell behind the icon but the icon should remain it's white background so it doen't overlap with the text.
             - [x] Upon clicking on the icon, open the 'Edit assignee' pop-up
            - [x] If there is an assignment in place the user should be able to unassign the user 

- [x] Add a drop-down filter next to the free text filter. Placeholder: 'Assignee'
    - [x] opening the drop-down should list the assigned users
    - [x] entering content in the field should also search for users in the list
    - [x] Upon selecting a user and applying filters, the list should get filtered to only display messages assigned to the filtered user
    - [x] The filter should include a value called 'Unassigned'
        - [x] Upon selection, the directory should filter for all lab messages that do not have an assignee yet

- [x] The users that are able to be assigned to lab messages should be any users having the `LAB_MESSAGES` user right
### Additional Information

Column and filter
![Lab messages Refinements_assignee](https://user-images.githubusercontent.com/70317594/142244028-12c5e47e-b056-403a-8070-78be2726684b.png)

Edit assignee pop-up
![Lab messages Refinements_editAssignee](https://user-images.githubusercontent.com/70317594/142244044-0c6b6a07-4061-424f-8e36-c4a3d003d775.png)

Clinched assignee cell
![Cell link_assignee](https://user-images.githubusercontent.com/70317594/142244076-708ff8eb-fc38-4d48-a1b8-ae60cd8de9a9.png)

**Comment by kwa20** [comment]
@MateStrysewske @syntakker added specifications on which users should be able to be assigned

**Comment by FredrikSchaeferVitagroup** [comment]
To verify this issue, a good starting point is to check whether the everything specified above shows and works. There are two unchecked marks: those two were not feasible to implement for technical reasons. The testing person could check whether the found alternative/approximation seems feasible.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @ChristopherRiedel I had a brief look on the test-de2.sormas.netzlink.com server and it looks very good! The first point you mention that is unchecked is not an issue for me, visual indication should suffice how it is.

Regarding the second unchecked mark: Clinching unfortunately hides the edit button

<img width="221" alt="assigneeLabMessages2" src="https://user-images.githubusercontent.com/70317594/148084276-c4970f35-d9dd-448b-a4d5-78fb6e83f968.PNG">

Maybe it could be an option to put them in another column without a header that remains short but only inlcudes the edit icons? This could align the buttons as well. If this is not feasible or pesky I'd be fine leaving it as it is.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Thank you for your feedback1
Regarding the clinching: we discussed this, too. The problem with this alternative approach is that, when one user name is long, the edit buttons would be far off from shorter names by default. So we thought it's better to keep the current approach.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Fair point. Let's stick with the current solution and see if this is even an issue in production at all.

**Comment by mario-kuehne** [comment]
**Issue:** Not possible to filter for specific lab message assignee in bulk edit mode 

**Reproduction:**
Login as User 'ad MIN'
Open 'Lab Message Directory'
Assignee filter should be empty (not set)
Click Button 'Enter Bulk Edit Mode'
Filter for assignee 'ad MIN' and click button 'Apply filters'

**Expected behaviour:**
Table should only show lab messages with assignee 'ad MIN'

**Current behaviour:**
Table shows all lab messages

**Environment**:
Tested on https://test-de2.sormas.netzlink.com/

![assignee-filter-bulk-edit-mode-lab-message-directory](https://user-images.githubusercontent.com/95228108/148932064-861e322f-3de3-42fb-8aba-d781485b6ce4.PNG)

Clarified with @FredrikSchaeferVitagroup to reopen the issue.

**Comment by mario-kuehne** [comment]
Retested on https://test-de2.sormas.netzlink.com/ (Version: 1.67.0-SNAPSHOT)

Applying filters in 'Bulk edit mode' successfully reduces amount of shown lab messages in the table to the expected ones.

But the the number in the 'All (140)' filter does not get reduced. Expected 'All (10)'. Hint: When clicking on 'All (140)' then it gets refreshed to 'All (10)'


![lab_message_directory_amount_of_all_filtered_lab_messages](https://user-images.githubusercontent.com/95228108/149172325-561eaa1a-7646-404c-914b-caa85fe8eb6f.PNG)

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT

**Comment by mario-kuehne** [comment]
**Description of found issue:** Not possible to unassign user when opening 'edit assignee' dialog via 'More' icon

**Reproduction:**

- Login as NationalUser
- Click 'Samples' in menu to open 'Sample Directory'
- Click 'Lab Messages' tab to open 'Lab Message Directory'
- Click on 'More' icon for any lab message that already has an assignee set
- Open drop-down component in 'Edit assignee' dialog and change from currently set assignee to <empty> assignee
- Click 'Save' button


**Actual Behaviour:**
Lab message retains old set assignee. Unassignment not possible.

**Expected Behaviour:**
Lab Message should show 'Assign'

**Hint:**
Occurs in 'Single Edit Mode' and in 'Bulk Edit Mode'

**Tested with**

- Browser: 
  - Chrome Version 97.0.4692.71 (Official Build) (64-bit)
  - Firefox 96.0 (64-Bit)
- SORMAS version: 1.67.0-SNAPSHOT
- Server URL: https://test-de2.sormas.netzlink.com/
- User Role: NationalUser

**Comment by mario-kuehne** [comment]
Successfully retested fix for 'single unassign' on https://test-de2.sormas.netzlink.com/ (Version: 1.67.0-SNAPSHOT) at about 2022-01-18 1:50 pm CET

**Comment by mario-kuehne** [comment]
Succesfully tested requirements mentioned in Feature Description, but the current behaviour has some differences like mentioned in comments. Implemented alternatives/approximations seem to be suitable from functional perspective.

**Summary of current differences**

_Requirement 1_
- Feature Description: "If there is no assignee set for a lab message, display the text 'Assign' in the respective cell" -> "While hovering, indicate that this text is clickable by changing the colour slightly and underlining the text (cf. uuid's for reference)"
- Actual Behaviour: 'Assign' is always underlined (with / without hovering) & color changes slightly when hovering

_Requirement 2_
- Feature Description: "In the same cell, display a 'More' icon that fills the cell but does not get overlayed by the username" -> "If the cell gets clinched, the icon must overlay the username text. When clinched, the username text should float out of the cell behind the icon but the icon should remain it's white background so it doen't overlap with the text."
- Actual Behaviour: 'More' icon can be hidden in some situations (e.g. long combination of first name & last name) like shown in the image of comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/7310#issuecomment-1004927033
- (possible) manual fix: manually resize assignee column in browser

_Requirement 3_

- Feature Description: "Add a drop-down filter next to the free text filter. Placeholder: 'Assignee'" -> "opening the drop-down should list the assigned users"
- Actual Behaviour: shows all users with the user right 'LAB_MESSAGES'
