### ISSUE TITLE
[DEMIS2SORMAS] Extend the bulk edit feature on the lab message directory [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7313]
### Situation Description

Currently, users have a hard time managing large numbers of incoming lab message. They can't process them fast enough and they struggle to report cases to higher health institutions in time. Thus, they should be able to assign lab messages to users to manage and distribute work more efficiently. #7310 will implement the overall assignment feature. However, it would be very useful to assign lab message in bulk because it saves time.

concept issue: #7308
### Feature Description

- Extend the bulk actions drop down on the lab message directory with the option 'Edit Assignee'
- When one or multiple lab messages have been selected and 'Assign' pressed, open the 'Edit assignee' pop-up.
    - After saving a selected assignee, set the assignee of all selected lab messages to the chosen assignee.
    - A selected assignee could also be "no assignee"? [first option]
- If the 'Assign' value is pressed but no lab messages was selected beforehand, display the following error message to the user: "_You have not selected any lab messages_"
### Additional Information

![Lab messages Refinements_bulkAction](https://user-images.githubusercontent.com/70317594/142370806-2a62f8e0-ee88-493b-898d-4d3ed5d9f888.png)

**Comment by mario-kuehne** [comment]
Tested on https://test-de2.sormas.netzlink.com/ (Version: 1.67.0-SNAPSHOT). 

Functional tests were successful.

**Comment by mario-kuehne** [comment]
Found an UI issue with Assignees that have long combination of first & last name.

![assignee-long-combination-first-and-lastname](https://user-images.githubusercontent.com/95228108/149173908-5eb167b9-5010-421a-b88f-c5606b799b3e.PNG)

**Comment by FredrikSchaeferVitagroup** [comment]
> Found an UI issue with Assignees that have long combination of first & last name.
> 
> ![assignee-long-combination-first-and-lastname](https://user-images.githubusercontent.com/95228108/149173908-5eb167b9-5010-421a-b88f-c5606b799b3e.PNG)

And what is that issue supposed to be? You should be able to scroll sideways.

**Comment by mario-kuehne** [comment]
> > Found an UI issue with Assignees that have long combination of first & last name.
> 
> And what is that issue supposed to be? You should be able to scroll sideways.

Horizontal scrollbar is not shown in some circumstances when facing the mentioned UI issue. 

- Chrome Version 97.0.4692.71 (Official Build) (64-bit)
- 100% Zoom-Factor and 110% Zoom-Factor
- Screen Resolution: 2560 x 1440

**Comment by FredrikSchaeferVitagroup** [comment]
Okay, but a not showing scroll bar really is out of scope of this issue. In't it?

**Comment by mario-kuehne** [comment]
> Okay, but a not showing scroll bar really is out of scope of this issue. In't it?

Yes, might be out of this scope of this ticket.

From functional perspective this ticket works like expected.

@kwa20 Do we want to create a separate ticket for the UI issue?

**Comment by kwa20** [comment]
@mario-kuehne @FredrikSchaeferVitagroup I think the actual issue here might not be the "missing" horizontal scroll bar but the overlapping column that hides the process button. You might be able to make the scroll bar appear by extending the column in which the process button resides until the list exceeds the screen.

We might want to check if it is possible for the process column to remain in a fixed width so that it never gets hidden. However, I'm not sure if this is even possible with vaadin. Users also start requesting additional columns so we might revise the current column structure too. 

All in all, we should handle these things in other issues indeed.

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT

**Comment by mario-kuehne** [comment]
> @mario-kuehne @FredrikSchaeferVitagroup I think the actual issue here might not be the "missing" horizontal scroll bar but the overlapping column that hides the process button. You might be able to make the scroll bar appear by extending the column in which the process button resides until the list exceeds the screen.
> 
> We might want to check if it is possible for the process column to remain in a fixed width so that it never gets hidden. However, I'm not sure if this is even possible with vaadin. Users also start requesting additional columns so we might revise the current column structure too.
> 
> All in all, we should handle these things in other issues indeed.

Created new issue: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7681
