### ISSUE TITLE
Missing user rights captions

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7322]
### Bug Description

The user role export includes user rights instead of descriptions for some rights in the description column.
### Steps to Reproduce

1. Go to the user management
2. Export user rights
3. Check the description column in the exported file

### Expected Behavior

All entries should be actual descriptions instead of user right duplicates
### Screenshots

<img width="363" alt="userRoleExportDescriptionError" src="https://user-images.githubusercontent.com/70317594/142454446-a4d8758b-9193-4bd5-ad9c-33a788d72160.PNG">

### System Details

* Device:
* SORMAS version: 1.65.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Entries in enum.properties are missing for these user rights.

**Comment by roxanamlendea** [comment]
All the user rights now have descriptions, but I noticed that the IMMUNIZATION_MANAGEMENT_ACCESS is now missing from the user role export table.

**Comment by MateStrysewske** [comment]
@roxanamlendea That's because I removed the user right since it was unused. :)

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.66.0-SNAPSHOT.
