### ISSUE TITLE
[Angular] Dashboard: Epidemiological curve [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7332]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- Full screen reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/g0gl3Oz
- Additional reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ygd2jEA
- We need to first hardcode the request (as the BE is not yet built). 
- i.e [{'10.11.2020':{ALL THE DATA SIMILAR TO THE NEW CASES}}]
- We should have the colouring done, the fullscreen functionality
- We should also add the bottom "filters" even if they aren't working right now (dummy)
- We should also implement the "Dead" functionality as per the design (which can also be fullscreen).
- We should use the libraries highlight and toggle on/off functionality 
- Library: https://echarts.apache.org

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
