### ISSUE TITLE
[Angular] Dashboard: Map section [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7333]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/nRJY3kd
- Reference fullscreen: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yP4dR7
- Reference layers: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/QbOgLlL
- Reference Map keys: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/nRJY3kd
- We will only add the map without any markers and additional functionality for now.
- We will need to have the possibility to make the map fullscreen.
- We will need to implement the buttons (without any attached functionality to them).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
