### ISSUE TITLE
[Angular][Backend][SPIKE] Investigate how the map is implemented / work from the BE perspective on Dashboard surveillance [2] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7334]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- We need to understand how the BE feeds data to the FE Vaadin  and if we can reuse this with Angular
- What changes might be required
- We need to have a call with @MateStrysewske or Alexandru V.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by marius2301** [comment]
We can define a new endpoint for retrieving the data for map having as input parameter the dashboardCriteria(region, district, disease, fromDate, toDate, showCurrentEpiSituation (flag to be added)). The result will be a list of MapCaseDto. 
The MapCaseDto  contains the geo coordinates (lat, long) of the facility, report and address for the case.
