### ISSUE TITLE
[Angular] Immunisation Filter + Table [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7335]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/AxEWJG5
- Reference full table: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/YGA5WEe
- We will need to implement both the filter and the table
- @cristinacoza please update the checkbox to be in a separate section
- Add the "Add new immunisation" button without any action attached to it
- We will have a new immunisation module
- 

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI & reference design updated

**Comment by cristinacoza** [comment]
UI/UX review done
