### ISSUE TITLE
[Angular] Pick a person functionality for immunisations [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7337]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/v8k0Jnd
- @cristinacoza please update the pick a person section with the new search functionality as per the current Sormas
- We can make use of the current BE 
- Please check the functionality already don in the current Sormas implementation

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI updated

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
