### ISSUE TITLE
Investigate automated tests failing only in Jenkins

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#7342]
After fixing all automated tests, I've discovered that some tests have a different behaviour when triggered via Jenkins.
Performed some quick checks on local, added some loggers to investigate failures but unable to identify the root cause.

The chunk of tests which need to be investigated:

Change the source case contact and then delete
Create Contact and check details in Detailed view table
Edit all fields from Follow-up visits tab
Source case selected for contact
Add a New action for an Event and verify the Action in EventActions table
Create and edit a new event
Check all fields from the created Task in the Task Management table

Observations:
1. Persons tests are flaky due to low performance of the component
2. Some tests are failing due to data parsing issue, read about this a bit, could be related to the java version that we have on the VM.
3. Noticed that some fields are not populated even if elements are identified

**Comment by StefanKock** [comment]
Was moved to done two days ago.
