### ISSUE TITLE
Sample info text jumps across creation form

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7349]
### Bug Description

When creating a sample and also a pathogen test in the same process, the info text of the sample regarding the reporting jumps across the form.
### Steps to Reproduce

1. Open a case or contact and create a sample and a pathogen test directly
2. scan the form for the reporting user info text

### Expected Behavior

the info text should be placed in the sample section
### Screenshots

<img width="452" alt="reportedTextSampleJumps" src="https://user-images.githubusercontent.com/70317594/142987121-eefb67a3-bef4-4b0b-925b-86841ced8ea8.PNG">
<img width="451" alt="reportedTextSampleJumps2" src="https://user-images.githubusercontent.com/70317594/142987294-325875e2-bb53-43f2-a9c5-93f3b73de45a.PNG">

### System Details

* Device:
* SORMAS version: 1.65.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by syntakker** [comment]
This has been fixed in #7204, where the report info has been moved to a fixed position at the top of the form:
![image](https://user-images.githubusercontent.com/5616564/144830903-1f6601a4-1030-4b42-a78c-494e21d5547e.png)
