### ISSUE TITLE
App crashes when trying to create immunizations for event participants

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7352]
### Bug Description
The Android app crashes when trying to create an immunization for an event participant even for events with a disease.

Relates to #7167 
### Steps to Reproduce
1. Create or select and event with a disease.
2. Navigate to immunizations
3. Click the edit icon => person edit fragment opens
4. Navigate to immunisations and try to create a new immunisation by clicking the "+" icon.
5.  App crashes

### Expected Behavior
The app should not crash.
### Screenshots

![image](https://user-images.githubusercontent.com/71414361/143143147-ab03b603-263e-4bdf-8bbd-cc5eb3806f74.png)### System Details

* Device: Android version 11
* SORMAS version: 1.65.1
* Android version/Browser:
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Surveillance officer & contact officer

**Comment by BasilKaburi** [comment]
@MateStrysewske 
Sure, I will test it again in 1.66.

**Comment by MateStrysewske** [comment]
@BasilKaburi Managed to reproduce this particular problem and already found its source. Will be fixed for 1.66!

**Comment by BasilKaburi** [comment]
@MateStrysewske Great!

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server https://test-de1.sormas.netzlink.com/sormas-rest/
