### ISSUE TITLE
Faulty validation of fields for  email addresses  and phone numbers

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7353]
### Bug Description
The field validations for email addresses on the android app is such that it rejects valid and active emails and accepts implausible emails.
The field validations for phone number on the android app is such that it rejects alphabets but accepts other implausible entries e.g.  punctuations, symbols.

Relates to #7157 
 ### Steps to Reproduce
1. Create a case
2. Navigate to person information
3. Enter a valid email address
4. Enter implausible phone number with including symbols and punctuation marks. 

### Expected Behavior
The email field should accept reasonable and/or valid email addresses.
The phone number field should not accept implausible data (aside alphabets).

### Screenshots

![image](https://user-images.githubusercontent.com/71414361/143146086-cc843bc1-d791-4159-b9e7-ac3af1f4941a.png)### System Details![image](https://user-images.githubusercontent.com/71414361/143146235-674b845a-cacc-436e-a439-5c98fb93fd4f.png)
* Device: Android
* SORMAS version: 1.65.1
* Android version/Browser: version 11 (knox 3.7, API level 33)
* Server URL: [
](https://release-international.sormas.netzlink.com/)* User Role:Surveillance officer & Contact officer

**Comment by MateStrysewske** [comment]
@BasilKaburi The email you've entered contains an invalid whitespace, which is probably why you're receiving the error. Concerning phone numbers, the validation is currently the same as in the web app; we've got a change request to improve this validation: #7231
