### ISSUE TITLE
Android app crashes erratically when creating new immunisations or navigating the immunisation directory.

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7354]
![image](https://user-images.githubusercontent.com/71414361/143148207-9ab87213-4b87-4e2e-b7b4-9f77b37b5bd5.png)### Bug Description
On frequent occasions, the  android app crashes when creating new immunisations or simply navigating the immunisation directory.

### Steps to Reproduce
1. Open the immunisation directory OR
2. Create a new immunisation for a case, or an event participant whose associated event has a disease OR
3. Open an immunisation and try to edit it.

### Expected Behavior
The app should not crash for any of these normal activities.

### System Details![image](https://user-images.githubusercontent.com/71414361/143148086-1696033a-2db4-492c-8e96-a09f15db0176.png)![image](https://user-images.githubusercontent.com/71414361/143148136-f4582db0-56f5-4083-910a-f8fe1cab28a7.png)* ![image](https://user-images.githubusercontent.com/71414361/143148207-9ab87213-4b87-4e2e-b7b4-9f77b37b5bd5.png)* 

* Device: Android 
* SORMAS version: 1.65.1
* Android version/Browser: Version 11 (knox 3.7, API level 33)
* Server URL: https://release-international.sormas.netzlink.com/)
* User Role: Surveillance officer & Contact officer

**Comment by MateStrysewske** [comment]
@BasilKaburi Do you have access to log files from your Android device for these crashes?

**Comment by MateStrysewske** [comment]
@BasilKaburi We can't reproduce this. Can you please try to reproduce it in an environment running 1.66.0 (so a test instance) and check whether it happens there for you as well?

**Comment by BasilKaburi** [comment]
@MateStrysewske 
Sure, I will test it again in 1.66

**Comment by StefanKock** [comment]
No feedback since months, so we discard this ticket.
