### ISSUE TITLE
Date of investigation is not hid when investigation status is set to Pending

### ISSUE THREAD

**Issue by alexcaruntu-vita** [hzi-braunschweig/SORMAS-Project#7355]
### Bug Description

The date of investigation is not hid when setting the investigation status to Pending

### Steps to Reproduce

1. Open a case and set the investigation status to Done.
2. Enter the date of investigation.
3. Set the investigation status to Pending. Date of classification turns read only.

### Expected Behavior

Date of classification should be hidden.

### Screenshots

<img width="876" alt="date of investigation" src="https://user-images.githubusercontent.com/76100512/143195265-fdcfb701-984c-4431-bc61-bda5db3eb245.png">

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.66.0-SNAPSHOT.

**Comment by bernardsilenou** [comment]
@roxanamlendea 
I happen to see thins change very late.
In addition, It would have been good to also hide  ` date of investigation` based on investigation status ==  `Investigation discarded`. 
Maybe we do it another issue

**Comment by bernardsilenou** [comment]
Ie hide the date of investigation if investigation status is not set to done
