### ISSUE TITLE
Set cleared to No at Pre-existing conditions

### ISSUE THREAD

**Issue by felix84-ed** [hzi-braunschweig/SORMAS-Project#7358]
### Situation Description
In the Tab Clinic course you have to select for each pre-existing conditions (Yes/No/Unknown).

### Feature Description
For saving time it should be possible to set clear all conditions to "No" or "Unknown" (like in the Tab Symptoms)

**Comment by KristinaBorch** [comment]
Will be implemented with the following issue: #8058
