### ISSUE TITLE
[Angular] Immunisation: Profile [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7360]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ZO0qqGZ
- Note: This task will focus on everything except the Vaccination / Recovery section (these will be handled in other tasks).
- For the region filters, leave them empty (they will be empty as they will be refactored in the same sprint in a different task).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done
