### ISSUE TITLE
[Angular] Immunisation: Recovery link [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7361]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ZO0qqGZ
- Reference modal: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnoMlYM
- The "Link case" button should open the modal, and the search should use the Case ID (fully typed, and without any autocomplete)
- We need to also get a confirmation from @marius2301 what is actually returned from the backend (GetByID)
- Create a new case (recovered) / Create a new immunisation with the same specifications as the previous case, and then recovery and link them together based on the FULL ID of the case.

- Exact Flow: 
Link case to immunization recovery

To link a case to an immunization some data must match in the case and immunization profiles 
- same disease
- outcome of case must be RECOVERED and Means of immunization RECOVERY
- Same person 

CREATE A NEW CASE - disease Covid-19
Set Outcome of case to RECOVERED
CREATE NEW IMMUNIZATION - disease Covid -19
Set MEANS OF IMMUNIZATION RECOVERY or VACCINATION/RECOVERY
Immunization person FIRST NAME, LAST NAME & SEX - as in the case created
PICK OR CREATE PERSON modal appear 
SELECT A MATCHING PERSON - select the same person as in the case created
The IMMUNIZATION page opens
In the RECOVERY section - LINK CASE button
After you pressed LINK CASE button - SEARCH SPECIFIC CASE modal appears 
In the Search field enter the FULL CASE ID (not only the short version) of the case you just created 
SEARCH CASE - A case if found and a CASE FOUND message appears only if the complete CASE ID is entered in the search field for the Search specific case modal.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done
