### ISSUE TITLE
[Angular] Immunisation: Vaccination Add / Edit [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7363]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/9P8omdM
- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Jnbqq19
- We will omit the current user section as we don't receive such info from the BE (Reporting user)
- When selecting Vaccination, the right hand sections shows all of the available vaccinations, and the user can add a new one by clicking "Add new" vaccination (check second reference design)
- In code we will have a modal (add/edit) based on the availability of existing data
- The vaccines will be hardcoded for now (as we don't have an endpoint for them right now)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done
