### ISSUE TITLE
[Angular] Immunisation: Person [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7364]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/bgMm35O
- @cristinacoza please confirm with @MateStrysewske if there is a real possibility that the "Person" section will be different of various locations across the site (case , immunisation, etc) - this will settle what we will choose on the dev side (copy/paste, share component)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done
