### ISSUE TITLE
The option for user logout from the android app when a device contains unsynchronised data is disabled. 

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7365]
### Bug Description
If a user attempts to logout of an android device that contains unsynchronised data, a warning alert pops up to suggest two options namely, to dismiss intended logout, or proceed to logout.
A user of the android app is not able to logout even if s/he opts not to synchronise data.

### Steps to Reproduce

1. On the start page of android app, open settings.
2. Tap 5 times (or more) on the SORMAS version (eg. SORMAS 1.65.1)
3. Tap on LOGOUT and proceed to enter "LOGOUT" into the text field per the suggestion on pop up warning.

### Expected Behavior
On entering LOGOUT as in step 3, the OK button should be enabled to allow selection and logging out.

### System Details![Screenshot_20211124-120047_APMIS](https://user-images.githubusercontent.com/71414361/143248708-37dea125-d1df-45d5-8bf3-5a273bc0af7b.jpg)
* Device: Android
* SORMAS version: 1.65.1
* Android version/Browser: Version 11 (knox 3.7, API level 33)
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Surveillance officer & contact officer

**Comment by MateStrysewske** [comment]
You've entered a whitespace after the LOGOUT keyword.
