### ISSUE TITLE
[Immunization] Vaccination migration leads to improper vaccination data

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7366]
### Feature Description

Immunizations > Vaccinations > Migration https://github.com/hzi-braunschweig/SORMAS-Project/issues/5909
### Problem Description

Some flaws in the immunization migration have been identified that lead to improper migration results for vaccinations. This will also have subsequent problems for interface mappings and vaccination display in the reduced immunization module.

One major point is that the `vaccinationDoses` in the previous fields is not equal to the `numberOfDoses` in immunizations because in immunizations it is the expected number of doses whereas in the previous fields it described the administered doses. The administered doses in immunizations are now reflected by the number of entries in the vacinations table.
### Proposed Change

- If `vaccinationDoses` are entered, create vaccinations equal to the number provided in the field.
    - If 1 is entered, use the `lastVaccinationDate` to set the `vaccinationDate`, if missing, use the `firstVaccinationDate` 
    - If 2 is entered, use both dates to set in the two respective vaccination entries
    - If the number is set to >2, create the respective number of vaccinations but only fill the first and last vaccination with the `lastVaccinationDate` and `firstVaccinationDate`
    - If the `vaccinationDoses` is missing, follow the specifications in #5909 

> - Create a new vaccination entity for the date of first vaccination, if available (if no date of vaccination is available, create a vaccination entity anyway, but leave the date empty); set the immunization_id, create a new health conditions entity and attach it to the vaccination; set the report date to the report date of the case/contact/ep; fill the remaining fields with the content of the VaccinationInfo entity of the contact/ep or the vaccination fields of the case; if the vaccine is ASTRA_ZENECA_COMIRNATY or ASTRA_ZENECA_MRNA_1273, set the vaccine of the new entity to OXFORD_ASTRA_ZENECA and the vaccine manufacturer to ASTRA_ZENECA
> - Create a new vaccination entity for the date of last vaccination, if available; same logic as for the first vaccination entity, except: Don't create this entity if NO vaccination date has been specified at all UNLESS the specified vaccine is ASTRA_ZENECA_COMIRNATY or ASTRA_ZENECA_MRNA_1273; in that case, create a new vaccination anyway and set the vaccine to COMIRNATY and the manufacturer to BIONTECH_PFIZER if the specified vaccine is ASTRA_ZENECA_COMIRNATY or the vaccine to MRNA_1273 and the manufacturer to MODERNA if the specified vaccine is ASTRA_ZENECA_MRNA_1273

- If the number is set to >2 and the vaccine is either `ASTRA_ZENECA_COMIRNATY` or `ASTRA_ZENECA_MRNA_1273`, create a first vaccination with `vaccineName` set to `OXFORD_ASTRA_ZENECA` including the `firstVaccinationDate` (if available) and all subsequent entries as either `COMIRNATY` or `MRNA_1273` respectively with one of them including the `lastVaccinationDate` (if available)

- If the person has multiple entities with available vaccination information, compare the `vaccinationDoses` and if earlier cases, contacts or participants have the same or a lower number of doses, set the report date of the number of created vaccinations (number dependent on the compared `vaccinationDoses`) according to the earliest available report date of associated entities.
    - Example:
A person has a case and a contact where the contact happened before they became a case. Let's say that while the person was a contact, they were vaccinated once already but when the case was docmented, they were vaccinated twice. Note that these entities could be independent, meaning the contact does not have to be converted.

|case report date|case vaccination doses|contact report date|contact vaccination doses|
|:-|:-|:-|:-|
|11/26/21|2|10/15/21|1|

Since in the general migration, we draw the information from the latest entity (the case in this example), the report date would be set to the report date of the case. However, the vaccination is also relevant to the contact and we need to fall back onto the report date if the vaccination date is missing. Therefore, the report date should be set to that of the contact.

If we e.g. find two COMIRNATY doses in the case, the first vaccination should have a report date of the contact.

### Additional Information

- The migration is done in 1.64.x, so every system that is already updated probably maybe cannot be changed/fixed. This most likely does not apply to PROD systems, but all stages/instances before.

**Comment by kwa20** [comment]
@HolgerReiseVSys 

> If the person has multiple entities with available vaccination information, compare the vaccinationDoses and if earlier cases, contacts or participants have the same or a lower number of doses, set the report date of the number of created vaccinations (number dependent on the compared vaccinationDoses) according to the earliest available report date of associated entities.

This is something we talked about yesterday in regards of how to determine relevance of vaccinations per entitiy. Would you mind having a look if this is comprehensible?

**Comment by HolgerReiseVSys** [comment]
@kwa20 
I think that determining `numberOfDoses` from `vaccine` is missing.
Also, I am not sure if if it gets clear that `vaccinationDoses` vaccination entries have to be created.
When determining if a vaccination has to be taken into account for e.g. a case, now the `reportDate` serves as a fallback for the `vaccinationDate`.
There must be `vaccinationDoses` entries with a `reportDate` on or before the date of the case.

**Comment by kwa20** [comment]
@HolgerReiseVSys 

> I think that determining numberOfDoses from vaccine is missing.

You mean the number set in `numberOfDoses` in immunizations depending on the entered vaccine? e.g. Comirnaty > 2? I would add a table then.

> Also, I am not sure if if it gets clear that vaccinationDoses vaccination entries have to be created.

Ok, I'll try to further explain and provide examples.

> When determining if a vaccination has to be taken into account for e.g. a case, now the reportDate serves as a fallback for the vaccinationDate.
There must be vaccinationDoses entries with a reportDate on or before the date of the case.

yes, for determining relevance we fall back onto the vaccines reportDtae if no vaccinationDate is given. I'll try to further explain and give an example

**Comment by BarnaBartha** [comment]
@kwa20 Adding a table to determine numberOfDoses that is to achieve immunization, what do you mean by this. Adding a table in the database, so that the values are update-able?
Or simply defining them same as we do the relation between vaccine and manufacturer (it is hard coded within the definition of the vaccines) - if this is what you mean, why do we need the the numberOfDoses altogether?

**Comment by kwa20** [comment]
@BarnaBartha Since the `vaccinationDoses` in the previous implementation is not the same as the `numberOfDoses` in immunizations the idea was to set the `numberOfDoses` according to the vaccine but we revised this internally again and we can discard this.

**Comment by BarnaBartha** [comment]
@kwa20 When you have the time please add the example related to the issue when multiple entities have vaccination info.

**Comment by kwa20** [comment]
@BarnaBartha I added this example in the description above:

<html>
<body>
<ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 0px;"><li style="box-sizing: border-box; margin-left: 0px;">Example:<br style="box-sizing: border-box;">A person has a case and a contact where the contact happened before they became a case. Let's say that while the person was a contact, they were vaccinated once already but when the case was docmented, they were vaccinated twice. Note that these entities could be independent, meaning the contact does not have to be converted.</li></ul></li></ul>

case report date | case vaccination doses | contact report date | contact vaccination doses
-- | -- | -- | --
11/26/21 | 2 | 10/15/21 | 1

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Since in the general migration, we draw the information from the latest entity (the case in this example), the report date would be set to the report date of the case. However, the vaccination is also relevant to the contact and we need to fall back onto the report date if the vaccination date is missing. Therefore, the report date should be set to that of the contact.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If we e.g. find two COMIRNATY doses in the case, the first vaccination should have a report date of the contact.</p>
</body>
</html>

**Comment by BarnaBartha** [comment]
@kwa20 The result of the example is two vaccinations, right ? Only that if the first vaccination date field is missing i am taking the report date of the contact because that is the earliest. 
In the current migration we have a 'relevance date' that considers not only the report date of the entities but also:
contact.lastcontactdate / events.startdate, events.enddate / symptoms.onsetdate, depending on the entity, and the most recent of this date is used. Shouldn't this be used but the earliest entry of it? @MateStrysewske please check this

**Comment by kwa20** [comment]
@BarnaBartha 

> @kwa20 The result of the example is two vaccinations, right ? Only that if the first vaccination date field is missing i am taking the report date of the contact because that is the earliest.

Yes exactly. But the point you're raising here is quite important:

> In the current migration we have a 'relevance date' that considers not only the report date of the entities but also:
contact.lastcontactdate / events.startdate, events.enddate / symptoms.onsetdate, depending on the entity, and the most recent of this date is used. Shouldn't this be used but the earliest entry of it?

I think you're totally right, we should use these dates and the earliest for the respective overlap of doses.

**Comment by kwa20** [comment]
@BarnaBartha 

> @kwa20 The result of the example is two vaccinations, right ? Only that if the first vaccination date field is missing i am taking the report date of the contact because that is the earliest.

Yes exactly. But the point you're raising here is quite important:

> In the current migration we have a 'relevance date' that considers not only the report date of the entities but also:
contact.lastcontactdate / events.startdate, events.enddate / symptoms.onsetdate, depending on the entity, and the most recent of this date is used. Shouldn't this be used but the earliest entry of it?

I think you're totally right, we should use these dates and the earliest for the respective overlap of doses.

**Comment by BarnaBartha** [comment]
To be able to test this use this db to setup sormas to a version (revision nr.: 9a88cce678) before migration script.
[sormas_dbs_schema_version_405.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/7616168/sormas_dbs_schema_version_405.zip)
