### ISSUE TITLE
Tasks can be created, but are not visible by a combination user: ReST User, Admin, Sormas to Sormas Client, National User, External Visits User

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7368]
### Bug Description
When logged with a combination user like this (ReST User, Admin, Sormas to Sormas Client, National User, External Visits User), the user can create new tasks but he cannot see them.

### Steps to Reproduce

1. Create a user: ReST User, Admin, Sormas to Sormas Client, National User, External Visits User
2. Log in with the user and open a case.
3. Create a task.

### System Details

* Device: Windows 10
* SORMAS version: 1.66.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: ReST User, Admin, Sormas to Sormas Client, National User, External Visits User

### Additional Information
I found this when I was testing ticket #7327

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of  SORMAS: 1.67.0-SNAPSHOT on test-de.sormas.netzlink.com environment
