### ISSUE TITLE
[Angular] Table view toggle (cards) [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7369]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference design - table: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/rbaRl4A
- Reference design - cards: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/rbGL3Oa
- We will need to add a toggle button that would switch the view from cards to a table
- We will only implement it (for now) for the Event Groups section
- There should be a new generic component for the tables (different from the one we are using now), as in the future we might need to implement this functionality across the board (in shared module).
- We will also need to update the card design (with the new date - multi date events). @cristinacoza please add the new card design.
- We will not send the service as a param to component, but rather an array of resources.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done- everything looks good exept some styling issue on hover for the table header that will be fixed in another ticket
