### ISSUE TITLE
Improve readability of the LabMessageController [5]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7375]
### Feature Description

The SORMAS-UI allows users to process lab messages. This has become more complex in the last time.

### Problem Description

This complexity reflects in the related code, the core of it being the [LabMessageController](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java). It currently is hard to work whith, which slows down implementation of new features, and increases the risk of bugs.

At the state of this writing, the LabMessageController is more than 1300 lines long. It contains several rather long and complex methods that are sometimes poorly documented. One example may be the [pickOrCreateEntry(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/30542cdb924517472175c47c310c0b18d079049d/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java#L304).

There are several other classes closely related to the lab message processing, for example 

- the [LabMessageUiHelper](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageUiHelper.java)
- the [RelatedLabMessageHandler](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/RelatedLabMessageHandler.java)

It is a little unclear which class has which responsibilities.

### Proposed Change

- [x] Refactor the LabMessageController. The refactoring should improve readability of the code (e.g. with shorter methods), and should make the workflow of lab message processing more visible. 
**TO BE DESCUSSED**: split the code into several smaller classes eg. **processing logic, UI, helpers/others** or **separate and independent class for each step in the processing flow** 
- [x] Make the flow testable and add tests to have high (90%+) code coverage
- [x] Add documentation to the LabMessageController and related classes specfying the scope of each class and explaining non obvious code parts.

### Additional Information

The [SOLID](https://en.wikipedia.org/wiki/SOLID) principles and [TDD](https://en.wikipedia.org/wiki/Test-driven_development#:~:text=Test%2Ddriven%20development%20(TDD),software%20against%20all%20test%20cases.) might be an orientation as well.

**Comment by FredrikSchaeferVitagroup** [comment]
There will soon be another type of DEMIS notification, leading to abother type of message (maybe doctor's report or something alike). If possible, the refactoring should take this into account, providing reusability and/or extendability.

**Comment by leventegal-she** [comment]
For QA: No functionality should be changed. All kind of create/select combinations should be tested  + handling related lab messages

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.72.0-SNAPSHOT (8404999)
