### ISSUE TITLE
Similar persons dialog: Fix description and add hint to create button [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#739]
- [x] switch first and last name and remove paddings
- [x] fix "pick person" hint - remove the create part
- [x] add "create" hint between list and create button. Something like "...if the person is not among the suggested persons". Make the "not among" part bold.

**Comment by MateStrysewskeSym** [comment]
- [ ] Adjust the hint to make clear that an already existing person should only be selected if the user is sure that it's a match
