### ISSUE TITLE
CrashLytics fails when building release

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#7398]
### Bug Description

Happened when trying to build the release 1.66.0:
```bash
    > Task :app:uploadCrashlyticsMappingFileRelease FAILED
    [INFO] Run tasks
    [INFO] Run build
    [INFO] Build
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:uploadCrashlyticsMappingFileRelease'.
    > java.io.IOException: Unknown error while sending file, check network [/srv/dockerdata/jenkins_new/workspace/sormas-Build/sormas-app/app/build/crashlytics/release/mappings/8e40a82a20e044e5bc0719aeaaf16a18.gz; response: 503 HTTP/1.1 503 Service Unavailable]
```

### Steps to Reproduce

1. Run release promotion on 1.66.0-SNAPSHOT

### System Details

* SORMAS version: 1.66.0-SNAPSHOT

### Additional Information

Trying Workaround: Not to push the `CrashLytics` (not invoke task `app:uploadCrashlyticsMappingFileRelease`).

**Comment by MateStrysewske** [comment]
Seems like we're still getting appropriate and complete crash reports, so I don't think there's anything we need to do here right now.
