### ISSUE TITLE
[DEMIS2SORMAS] Lab message directory quick filters don't filter properly

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7403]
### Bug Description

When filtering the lab messages directory for the status via the quick filters, all filters return incorrect results.
### Steps to Reproduce

1. Open the lab messages directory and make sure that thelist includes messages for all statuses
2. Filter all the possible options and check the results

### Expected Behavior

The quick filters should filter for the respective status and only display messages with the filtered status.
### Screenshots

<img width="842" alt="labMessagesFilterErrorUnprocessed" src="https://user-images.githubusercontent.com/70317594/144259159-af633acc-04a3-4c10-94bb-c1b7e59cdc5f.PNG">

<img width="862" alt="labMessagesFilterErrorProcessed" src="https://user-images.githubusercontent.com/70317594/144259534-6867b91b-e89e-4df0-a11e-7033a4ef8162.PNG">
<img width="854" alt="labMessagesFilterErrorUnclear" src="https://user-images.githubusercontent.com/70317594/144259136-51f65703-d703-4558-9bcc-c65f5d8bfbd5.PNG">

<img width="862" alt="labMessagesFilterErrorForward" src="https://user-images.githubusercontent.com/70317594/144259156-885a581f-fb0a-4bd9-a7ec-0555b828a627.PNG">

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup FYI

**Comment by FredrikSchaeferVitagroup** [comment]
Closely related to work of #7309 .

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment with the latest version of hotfix 1.66.1 branch
