### ISSUE TITLE
[Immunizations] Case edit page cannot be saved if Vaccination is created and then edited

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7404]
### Bug Description
If a Vaccination is created, and then edited, the Case edit page cannot be saved.

### Steps to Reproduce

1. Open a Case.
2. Create a Vaccination. 
3. Edit the Vaccination.
4. Save the Case Edit page.

### Actual Behavior
The user gets an error message.

### Expected Behavior
The Case Edit page should be successfully saved.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/144261033-66f7e8ae-dbd5-44f4-852e-41b919f9f28f.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.66.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
#7105

**Comment by kwa20** [comment]
I can also reproduce this issue on test1401.sormas.netzlink.com (1.66.0)

**Comment by kwa20** [comment]
I can also reproduce this error for contacts in the following way: (tested on test1401.sormas-oegd.de; 1.66.0; admin/national user)

1. Create a new contact
2. Edit the contact form
3. Press new vaccination
4. Save the vaccination > unsaved changes prompt should appear
5. Press save

<img width="399" alt="unsavedChangesErrorContactsVaccinations" src="https://user-images.githubusercontent.com/70317594/144408512-e990c66e-fe6e-4ce1-ad8e-54e22fe7cb0e.PNG">

**Comment by MateStrysewske** [comment]
Here's a video of the bug described by Kay; this should be fixed:

https://user-images.githubusercontent.com/23701005/144619361-bd6dc011-1367-468b-86c3-40657b6ea006.mp4

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.66.1 hotfix branch on local environment.
