### ISSUE TITLE
Editing the single event date does not trigger unsaved changes warning

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7409]
### Bug Description

When editing the event date and navigating to another page, the unsaved changes warning does not get triggered and the entry is automatically discarded.
### Steps to Reproduce

1. Open an event that does not have an event date and only leave the sigle event date enabled
2. Enter a date and without saving, navigate to another page

### Expected Behavior

The unsaved changes warning should be triggered
### Screenshots

<img width="304" alt="unsavedEventDate" src="https://user-images.githubusercontent.com/70317594/144406331-e5436a9e-432a-4839-86bb-dc3f55c87919.PNG">

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by alexcaruntu-vita** [comment]
Not reproducible with the latest build.

**Comment by AndyBakcsy-she** [comment]
Closing ticket as the saving pop-up is displayed.
