### ISSUE TITLE
Samples for event participants are not shown again

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7413]
### Bug Description

The same bug described here https://github.com/hzi-braunschweig/SORMAS-Project/issues/3965 is present again.

When a user has a disease limitation, the samples for event participants are neither shown in the card or sample directory.
### Steps to Reproduce

1. Set the limitation of a user (e.g. admin + national user) to COVID-19
2. open an event and add an event participant
3. Create a sample for this participant
4. Check the sample card and the sample directory for the created sample
5. Remove the limitation for the disease and try again

### Expected Behavior

The user should see the samples everywhere
### Screenshots

Limited user:

<img width="309" alt="adminNationalUserMissingSamples4" src="https://user-images.githubusercontent.com/70317594/144466554-12e5ceb9-e48e-42e9-b059-4405f507e052.PNG">

<img width="535" alt="adminNationalUserMissingSamples" src="https://user-images.githubusercontent.com/70317594/144466561-064c2755-cae2-464d-925e-9ddcc3dc4758.PNG">

<img width="591" alt="adminNationalUserMissingSamples5" src="https://user-images.githubusercontent.com/70317594/144466551-75b6bc67-fabf-48cf-bf4d-4d7643bcc517.PNG">

<img width="855" alt="adminNationalUserMissingSamples7" src="https://user-images.githubusercontent.com/70317594/144466565-6a689e0e-89a7-49fd-8b47-de62eed2cf85.PNG">

Unlimited user:

<img width="306" alt="adminNationalUserMissingSamples3" src="https://user-images.githubusercontent.com/70317594/144466556-282e0315-c052-49bc-951d-637c86ff9199.PNG">

<img width="587" alt="adminNationalUserMissingSamples2" src="https://user-images.githubusercontent.com/70317594/144466559-067c7522-c1ee-4352-9035-5ee6cc91a06a.PNG">

<img width="850" alt="adminNationalUserMissingSamples6" src="https://user-images.githubusercontent.com/70317594/144466548-dd6f19fb-65aa-4eaf-aaae-b0c7d7c09b4b.PNG">

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@kwa20 Can you send me the link to the event where this happens? Does that event have a disease set?

**Comment by kwa20** [comment]
@MateStrysewske The event Id on that instance is RPHASA-GZA65Z-NLVNZB-NLCICDMM and yes, the disease is set.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of the hotfix 1.66.1 branch.
Samples are only created once and displayed once per event participants
