### ISSUE TITLE
[Immunizations] List of vaccines not available at edit from Persons page

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#7415]
### Bug Description

As national user logged in having a case and at least one vaccine, when selecting the Persons page and choosing the person from the case, he doesn't has the list of vaccine names at edit vaccine

### Steps to Reproduce

1. Login as National user to an environment which has the reduce immunisation enabled
2. Create a case and add a vaccine
3. Go to Persons page and search the created person from the case above
4. Edit the vaccine
5. Select the dropdown fro Vaccine name

### Expected Behavior

The vaccine names should be the same ones as they are loaded at Cases page

### Actual Behavior

The Vaccine name dropdown contains only 2 values: Unknown and Other

### Screenshots

![Screenshot 2021-12-02 at 15 54 12](https://user-images.githubusercontent.com/91872179/144573448-0a7d202a-6dad-4d75-9fea-2b6f02785ef5.png)

### System Details

* Device: web
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: https://test-de.sormas.netzlink.com/
* User Role: national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest hotfix 1.66.1 branch version on local environment.
