### ISSUE TITLE
Vaccinations migration does not set everything as expected

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7423]
### Bug Description

- When two vaccine doses are entered but only the `lastVaccinationDate` was collected, the first vaccination has a date of vaccination entered even though it was never collected. This might also happen if the `vaccineDoses` > 1 and either `firstVaccinationDate` or `lastVaccinationDate` is missing
### Steps to Reproduce

1. Create entities as mentioned in the "created entities file" on version 1.63.1
2. Update from version 1.63.1 to version 1.66.0

### Expected Behavior

- The vaccination should not have a vaccination date after migration if it wasn't collected
### System Details

* Device:
* SORMAS version: 1.63.1 > 1.66.0
* Android version/Browser:  chrome
* Server URL: survnet-import-test.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

created entities (as custom export with relevant fields):
[vaccination_migration_test_211201 (1).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7650210/vaccination_migration_test_211201.1.csv)

failed tests and actual results:
[vaccination_migration_test_211202_findings.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7650204/vaccination_migration_test_211202_findings.csv)

vaccination db table:
[vaccination_migration_test_211202_findings_dbVaccinations.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7650223/vaccination_migration_test_211202_findings_dbVaccinations.csv)

### Development Specifications
What this means is that we have to remove the fallback to the relevance date from each piece of migration code where we use it to fill the vaccination date (e.g. every coalesce from first vaccination date OR last vaccination date to relevance date). This includes the new logic that updates the vaccination date of the first vaccination of a person (e.g. `sormas_schema.sql::8175` and its equivalent in the Android app). 

The fallback from last vaccination date to first vaccination date for vaccinations where number of doses == 1 can remain (because that makes sense).

**Make sure to test this, also for the Android app!** In the Android app, you'll need to set up a new backend database, check out version 1.63.1, start your server, connect your mobile app to it and log in; afterwards set your device to flight mode, create data that allows you to test these changes, THEN check out your branch where you did these changes again, restart your server, restart your mobile app (so that the database migration is executed), turn off flight mode, and synchronize with the server. The reason is that the Android app only migrates new data that hasn't been sent to the backend yet.

**Comment by BarnaBartha** [comment]
This new logic is in conflict of what was asked before, and the concept of the relevance date makes no sense any more.
Would like to point out a scenario with the requested changes:
|case report date|case vaccination doses|case first vac date|contact report date|contact vaccination doses|contact vac info first vac date|
|:-|:-|:-|:-|:-|:-|
|11/26/21|2|11/27/21|11/27/21|1|10/27/21|
In this scenario the contact was reported later but with a known first vaccination date before that of the case, but it is ignored. @MateStrysewske please check this

**Comment by kwa20** [comment]
@BarnaBartha I hope I can clarify your question: When we do have overlapping vaccination doses, we should fall back onto existing vaccination dates (`firstVaccinationDate` or `lastVaccinationDate`). So e.g. if a newest entity has a missing `firstVaccinationDate` but a previous entity with overlapping doses has a  `firstVaccinationDate` entered, we should take that one.

However, we should no longer fall back onto a report date for setting the` vaccinationDate` because it would produce data that was actually never collected.

**Comment by BarnaBartha** [comment]
@kwa20 sorry for being picky but to clarify a bit further
Given the examples:
Example 1:
|case report date|case vaccination doses|case first vac date|contact report date|contact vaccination doses|contact vac info first vac date|contact2 report date|contact2 vaccination doses|contact2 vac info first vac date|
|:-|:-|:-|:-|:-|:-|:-|:-|:-|
|11/26/21|2|11/27/21|11/27/21|1|10/27/21|11/01/2021|1|11/02/2021|

Example 2:
|case report date|case vaccination doses|case first vac date|contact report date|contact vaccination doses|contact vac info first vac date|contact2 report date|contact2 vaccination doses|contact2 vac info first vac date|
|:-|:-|:-|:-|:-|:-|:-|:-|:-|
|11/26/21|2|11/27/21|11/27/21|1|10/27/21|11/01/2021|1|null|

What will the resulting vaccinations - report/vaccination dates be?

**Comment by kwa20** [comment]
@BarnaBartha All good, we need to be picky here :)

Example 1:
|vaccination number|vaccination report date| vaccination date|
|:- |:- |:-|
|1|11/01/2021|10/27/2021|
|2|11/26/2021|null|

Example 2:
|vaccination number|vaccination report date| vaccination date|
|:- |:- |:-|
|1|11/01/2021|10/27/2021|
|2|11/26/2021|null|

I am assuming that the last vaccination date is empty in the case.

****

The results are the same because for the first vaccination date we would take the earliest of the available dates if te number of doses overlap.
The report date would be the date of the earliest entity that has overlapping doses. However, the vaccination dates are much more important, especially when we don't fall back onto the report date for relevance. @JaquM and me discussed with @MateStrysewske yesterday that it might not be a good idea to fall back onto the report date because that is not a reliable date

**Comment by BarnaBartha** [comment]
Summary of what was discussed with Kay on 04.12.2021 regarding some clarification for the vaccination migration when multiple entities of a person having vaccination info.

If the person has multiple entities, the dates of the vaccinations are extracted from the latest entity (the latest one should contain the most accurate information), with the following exceptions/rules:

- The report date would be the earliest available the report date of the persons entities that have overlapping doses

- The first vaccination date if not specified would be the non empty date of the earliest available first vaccination date of any of the persons entities that have overlapping doses

- The last vaccination date if not specified would be the non empty date of the latest available last vaccination date of any of the persons entities that have overlapping doses

We do not cover the scenario when a previous entity has more doses as the latest one, as that already means that the entered data is wrong (not up to date).

**Comment by kwa20** [comment]
As discussed with @MateStrysewske @JaquM @StefanKock and @markusmann-vg, there is the potential of losing data when vaccination data was not entered in the latest entity of the person but in previous ones. This can happen when users don't collect all the vaccination data in the latest entities due to a heavy workload. In this case, a previous entity could have more complete data than the latest.

To prevent data loss, we should additionally have a fallback for the following vaccination data if they are not available in the latest entity:
- `vaccineName`
- `otherVaccineName`
- `vaccineManufacturer`
- `otherVaccineManufacturer`
- `vaccineInn`
- `vaccineBatchNumber`
- `vaccineUniiCode`
- `vaccineAtcCode`

The fallback would work as already implemented for the vaccination dates.
