### ISSUE TITLE
Don't consider vaccinations without a vaccination date as relevant for cases/contacts/eps

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7424]
### Feature Description

When creating vaccinations, the vaccination status of cases, contacts, and event participants of the associated person might be updated depending on the vaccination date.

### Problem Description

Currently, vaccinations without a vaccination date update the vaccination status of ALL associated cases, contacts, and event participants to `VACCINATED`. However, that might lead to wrong data, which we have to avoid.

### Proposed Change

- [x] Never update the vaccination status of cases, contacts, and event participants when a vaccination without a vaccination date is saved (see `VaccinationFacadeEjb::updateVaccinationStatuses` and the three `VaccinationService::isVaccinationRelevant` methods)
- [x] Always display vaccinations without a vaccination date as irrelevant (i.e. greyed out) in the vaccination lists
- [x] Change the info icon description of vaccinations without a date to the following: "This vaccination is not relevant for this case/contact/event participant because it does not have a vaccination date." Also add a translation to strings_de-DE: "Diese Impfung ist für diesen Fall/Kontakt/Ereignisteilnehmer nicht relevant, weil sie kein Impfdatum hat."
- [x] Adjust the tests accordingly (`VaccinationFacadeEjbTest::testUpdateVaccinationStatuses`). If there's no test case for this scenario yet, add one.

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT for the vaadin app and on Android Studio connected to the server test-de.sormas.netzlink.com/sormas-rest/ for the android app.
