### ISSUE TITLE
[Contacts] Error when creating 'Contact with Source Case'

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7425]
### Bug Description
On the 'Epidemiological Data' tab, if a 'Contact with source case known' is set to yes and a 'New Contact' is added, right after the Contact is saved a pop up window appears that asks the user to save the changes. If the user selects 'Save changes', an error message appears. Even though the error appears, the Contact is created.

### Steps to Reproduce

1. Create a new Case.
2. Select the 'Epidemiological Data' tab.
3. Set 'Contacts with Source Case known' to 'YES'.
4. Click on 'New Contact' and fill in the mandatory fields. Save the form
5. On the Confirm Navigation pop-up that appears, click on 'Save changes'

### Actual Behavior
An error occurs saying that the data could not be saved because it has been changed in the meantime.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/144633682-567ad8e7-bf01-4d00-a641-40a0a8a5d60f.png)

![contact with source case error](https://user-images.githubusercontent.com/89522688/144632408-ec23905c-f2c2-499c-a56b-bf64e58f0e5e.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
If right after the Contact with source case known' is set to yes, the page is saved, and the 'New Contact' is added only after the save, then the error doesn't occur, because the Confirm Navigation pop-up doesn't appear anymore.

**Comment by syntakker** [comment]
Same problem occurs when creating samples for case, contacts or event participant when the edit form is in a modified state.
This is addressed in PR #7441, too.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment with the latest version of the hotfix 1.66.1 branch.
