### ISSUE TITLE
Creating a vaccination for a case crashes the mobile app.

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7427]
### Bug Description
The mobile app crashes when creating a vaccination for a case.

### Steps to Reproduce

1. Open a existing case or create a new case on the mobile app.
2. Navigate to the "CASE VACCINATIONS" tab and tap on it to create a vaccination for the case.

### Expected Behavior
The new vaccination form should open and allow you to complete it and save the vaccination.

### System Details![Creating-Case_Vaccinations_Crash](https://user-images.githubusercontent.com/71414361/144637226-3679c817-5459-4e2b-badd-9aa3838fda1e.jpg)
* Device: Android
* SORMAS version: 1.66.0
* Android version/Browser: Version 11 (knox 3.7, API level 33)
* Server URL: (https://release-international.sormas.netzlink.com/sormas-ui/login)
* User Role: Contact Officer and Surveillance Officer

**Comment by BasilKaburi** [comment]
@sergiupacurariu Hi Sergiu, Editing of main data of the case is possible.
Hospital was the type of facility for this case.
However, the app crashes irrespective of category of facility (Home or Medical Facility) or facility type (hospital, rehab, maternity etc.)

**Comment by sergiupacurariu** [comment]
@BasilKaburi Cannot reproduce it yet so I have a few more questions: 
- regarding the Immunization feature - what is the current setting: Reduced immunization or Full immunization feature (e.g. if the immunization menu is visible then you have the full feature)?
- is this crashing occur in every case you are trying to add vaccination to or just some of them?
- are you able to add vaccination to a Contact or EventParticipant?

**Comment by BasilKaburi** [comment]
@sergiupacurariu 

- The current setting is the Reduced Immunisation
- The app crashes with all case so far (I've test over 20 cases with multiple permutations of case data)
- With the other entities, the crashing is erratic but that is still related to issue **#7354** which Maté indicated he could not reproduce.
- With this reduced immunisation, there is no immunisation menu to navigate and reproduce it exactly as before. Hence, issue #7354 is a pending issue.
- Please, I will like to confirm if we are testing on the same servers.

**Comment by sergiupacurariu** [comment]
@BasilKaburi I was testing on my local machine. I will also test on the server you were logging on to.

**Comment by BasilKaburi** [comment]
@sergiupacurariu 
Great! That will enable us compare better.

**Comment by sergiupacurariu** [comment]
@BasilKaburi The testing of the server (https://release-international.sormas.netzlink.com/) mentioned in the Bug description was finalized. 
**User characteristics:** 
- USER ROLES selected: Case Officer, Contact Officer and Surveillance Officer; 
- User Region: "Ashanti"; 
- User District: "Adansi South"
**Tests:**
- active relevant features: Immunization REDUCED
- mobile virtual device used - API 29
- multiple diseases used
- added various configurations of vaccinations to multiple cases - everything worked without issues
- tested vaccination on contact and event participants - works well
- synchronization from server and back works without issues
So far I have not identified any issue related to the creation and synchronization of Vaccination both mobile and web. If there is anything I can look at please let us know.

**Comment by BasilKaburi** [comment]
@sergiupacurariu Please can specify the version you tested?

**Comment by MateStrysewske** [comment]
@BasilKaburi Have you verified this bug on a different device? Based on the other bug reports that you've opened, I'd like to eliminate the possibility that your device or the app on your device is in some kind of a weird state that causes this problem.

**Comment by BasilKaburi** [comment]
@MateStrysewske I use one device.  It's worth ruling out device related issues. I will have Benard cross check.
@bernardsilenou Kindly do a quick check on this.

**Comment by BasilKaburi** [comment]
@sergiupacurariu It may not matter now on which version you last tested this issue. I've tested severally on 1.66.1 and the problem persists. We will carry out @MateStrysewske recommendation above and share feedback.

**Comment by bernardsilenou** [comment]
- I did a test with surveillance officer  + contact officer role, all works fine as explained here https://github.com/hzi-braunschweig/SORMAS-Project/issues/7427#issuecomment-988982120
- The challenge that I faced was that the app did not download the apk from the server to auto update, so i did a fresh installation. 
- @BasilKaburi  I also think that your app may be corrupted, did you do a fresh installation ? Do a fresh installation and test again please.

**Comment by BasilKaburi** [comment]
@bernardsilenou @MateStrysewske @sergiupacurariu 
This is good news.
My device is the main suspect now because I did a fresh installation of 1.66.1.
Thanks.

**Comment by BasilKaburi** [comment]
On the basis of the findings as reported in issue #7499, the problem is not device related but still has to do with synchronisation and auto-update (outstanding issues which are being worked on).
I will close this issue therefore, so we focus now on the current issue.
Thanks!
