### ISSUE TITLE
[DEMIS2SORMAS] Disease variant field and details field are missing when processin lab messages

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7430]
### Bug Description

The disease variant field and the disease variant details fields are missing when processing lab messages.
### Steps to Reproduce

1. Upload and fetch a lab message
2. Process the lab message
3. The the pathogen tests for the disease variant and disease variant details fields

### Expected Behavior

disease variant and disease variant details fields should be available when processing lab messages
### Screenshots

<img width="502" alt="diseaseVariantFieldMissingDEMIS" src="https://user-images.githubusercontent.com/70317594/144650780-7d1cf7e5-d007-429d-bcac-33d39193f272.PNG">

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
This behaviour only showed when there was just one active disease or a default disease set on the server. #7439 should fix the problem.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the local environment.
After setting the default disease to covid and having disease variants enabled on the local environment, the Pathogen test area had the disease variant field enabled.
![image](https://user-images.githubusercontent.com/70562142/144742984-7b287fae-4b64-4055-b828-32d6782cfe07.png)
