### ISSUE TITLE
Sample cards content is shortened in a very unhelpful way

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7431]
### Bug Description

Sample cards have shortened content which makes certain rows basically useless because the actual data that should be displayed is hidden and users have to navigate anyway to see content
### Steps to Reproduce

1. Open e.g. a case and create a sample with a pathogen test
2. Go back to the case tab and check the sample card

### Expected Behavior

 All content should be visible but not exceed the cards borders or padding. If content gets lengthy, it should wrap to a new line.
### Screenshots

<img width="239" alt="cardCutOff" src="https://user-images.githubusercontent.com/70317594/144684012-ead59e0a-a284-4d77-9af4-fdca00f857e5.PNG">

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of the hotfix 1.66.1 branch on local environment
