### ISSUE TITLE
Hotfix branches are not CI checked

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7438]
### Feature Description
GitHub action CI

### Problem Description
The branch/PR targets of the actions does not trigger runs for `hotfix-*` branches

### Proposed Change
Include `hotfix-*` as PR and branch target

**Comment by AndyBakcsy-she** [comment]
Verified the ticket by looking through the commit. 
The hotfix branch name has been added to the CI Files
