### ISSUE TITLE
Contacts can be linked to deleted cases

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7449]
### Bug Description

When searching for cases in the source case pop-up for contacts, deleted cases can be found and selected.
### Steps to Reproduce

1. Create a case and delete it afterwards
2. Create a contact
3. Search for a source case and search the case you have previously deleted
4. Select the deleted case
5. Save the contact
6. Navigate to the case contact page and also check other tabs of the case

### Expected Behavior

It should not be possible to select deleted cases as source cases.
### Screenshots

<img width="660" alt="deletedCasesAsSourceCase" src="https://user-images.githubusercontent.com/70317594/144815168-8d91c49c-4cd6-445c-a4b1-1edd0e6e2355.PNG">
<img width="860" alt="caseContactsNavigation" src="https://user-images.githubusercontent.com/70317594/144815171-c0fca4d1-b011-467f-b6f5-ab1b027a88dc.PNG">
<img width="595" alt="caseContactsNavigation2" src="https://user-images.githubusercontent.com/70317594/144815174-ad4659d7-e181-4ba5-b001-4c8cc8eee1e9.PNG">

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.67.0-snapshot on the local environment
