### ISSUE TITLE
NullpointerException when saving visit

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7450]
### Bug Description

One german health department reported problems when saving a visit for a specific contact.

### Steps to Reproduce

1. Create a contact
2. Add a visit to the contact
-> clicking on save in the visit form throws the exception.

Those are the steps described by the health department. It could so far not be reproduced.

### Expected Behavior

The visit should be saved.

### System Details

* Device: probably windows pc
* SORMAS version: 1.63.1
* Android version/Browser: unknown
* Server URL: unknown
* User Role: unknown

### Additional Information

The SORMAS instance is connected to climedo.

Log excerpt: [saarbruecken_timestamp_2021-10-21_07_52.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7659496/saarbruecken_timestamp_2021-10-21_07_52.txt)

**Comment by leventegal-she** [comment]
I couldn't reproduce.

**Comment by FredrikSchaeferVitagroup** [comment]
Neither could I. I'm waiting for more information from the health department to be obtained by @af-rka .

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @leventegal-she Maybe this issue is related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/7434?

**Comment by vidi42** [comment]
@kwa20 is this issue still present now that #7434 was merged?

**Comment by FredrikSchaeferVitagroup** [comment]
As there was no feedback for about three months, I will discard this ticket. Please reopen in case of need.
