### ISSUE TITLE
[Immunization] Vaccination is not greyed out when the Vaccination Date is the same as the Report Date of the Contact

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7454]
### Bug Description
With the reduced immunization module enabled, when a Vaccination is created for a Contact, and the Vaccination Date is the same as the Report Date of the Contact, the vaccination is not greyed out and the icon saying that the vaccination is not relevant for this contact is not visible.

### Steps to Reproduce

1. Create a new Contact and choose the Report Date the current date. Leave the Date of Last Contact empty.
2. Create a Vaccination and choose the Vaccination Date the current date.

### Actual Behavior
Vaccination is displayed, but is not greyed out. The icon saying that the vaccination is not relevant for this contact is not visible.

### Expected Behavior
Vaccination is displayed and is greyed out. The icon saying that the vaccination is not relevant for this contact is visible.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/144865336-74e28702-f3f1-482f-9016-2c5944cbccfd.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
This happens also for the Event Participants.

**Comment by alexcaruntu-vita** [comment]
Not reproducible with the latest build for 1.67.0
