### ISSUE TITLE
infoCreateNewSampleDiscardsChanges is misaligned in the contact data view

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7460]
### Bug Description

The infoCreateNewSampleDiscardsChanges is closer to the immunizations list than to the samples list. This is irritating.
Also, in some languages other english, the info runs out of the layout (see second screenshot). This is not really a problem, but it just looks ugly.

### Steps to Reproduce

1. Open a contact

### Screenshots

![image](https://user-images.githubusercontent.com/67001822/145011865-3edc8379-ebc1-4b4b-9386-dafa43bd3109.png)

![image](https://user-images.githubusercontent.com/67001822/145012589-5711ce29-6726-40a1-8992-5fdd37541547.png)

### System Details

* Device: windows
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local dev system
* User Role: NatUser

**Comment by MateStrysewske** [comment]
#7350 will get rid of these warnings completely.
