### ISSUE TITLE
Event Overview has some overlapping UI problems

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7462]
### Bug Description

 The Event view is overlapping in many things.
### Steps to Reproduce

1. open event directory
2. have a look at the top
![Event overview](https://user-images.githubusercontent.com/78568406/145027171-3d9a86c4-c8d1-4eba-b069-d9d37db65909.JPG)

### System Details

* Device:
* SORMAS version:  1.66.1
* Android version/Browser: 
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
We probably have to introduce a "More" button here as well, similar to the one we already have in the case and contact directories.
