### ISSUE TITLE
[Android App] Hospitalization | Buttons are overlapping 

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7480]
### Steps to Reproduce

1. Open the android app ad select a case
2. Go to the hospitalization tab and create a new hospitalization
3. Observe the buttons at the bottom of the view

### Expected Behavior
Buttons should be clear to read and tab by the users on their phones. 
At the moment this is not as expected

### Note:
The screen size of the phone is 6.43 inches and the Resolution is 1800 x2400 pixels

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/145229722-738a7c99-92b0-4905-a57e-1b91bf77a77b.png)

### System Details

* Device: Oneplus Nord 2 (2021 model) 
* SORMAS version: 1.67.0-snapshot 
* Android version/Browser: Andrid 11
* Server URL: test-de.sormas.netzlink.com
* User Role: SurvOff

**Comment by MateStrysewske** [comment]
Proposed solution: Display the delete button as an icon-only button (I believe we already have that possibility in the mobile app).

**Comment by adinaflorea9** [comment]
I was able to observe the same overlapping of the 'Delete' and 'Dismiss' buttons on a device with the following system details:
Device: Huawei P20 lite (2019) -  5.84inches screen; 2280*1080 - resolution
SORMAS version: 1.68.0-snapshot
Android version: 9;  
Server URL: test-de.sormas.netzlink.com
User Role: SurvOff

The overlapping of the buttons could be observed in the directories: cases, contacts and events, for the following entries: person information (addresses/location; person contact details); hospitalization (previous hospitalization); epidemiological info (exposure).

![Screenshot_20220124_134530_de symeda sormas app debug](https://user-images.githubusercontent.com/96909231/150785913-f7a8b044-dab6-4509-a96f-4b6555c5d732.jpg)
![Screenshot_20220124_134414_de symeda sormas app debug](https://user-images.githubusercontent.com/96909231/150785948-43799d1b-c6c2-4db6-a2f8-4bbbcc5c6ef2.jpg)
![Screenshot_20220124_134506_de symeda sormas app debug](https://user-images.githubusercontent.com/96909231/150786004-cae687b5-9d46-4fba-9701-3635f8cc8c3f.jpg)

**Comment by sergiupacurariu** [comment]
The Android app is optimized for Tablet. Below you have a screenshot showing how it looks on a tablet with 600 x 1024 resolution. Due to this, the ticket will be closed.
![image](https://user-images.githubusercontent.com/62688603/151578600-d9d9625b-e930-48e3-bc71-533c0b1dd550.png)
