### ISSUE TITLE
General comment field is limited to 512 characters

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#7485]
### Bug Description

The general comment field is limited to 512 characters since September. It was supposed to be limited to 1.000.000 characters. 
So, when there is a documentation which exceeds the 512 characters (This is possible and stored in the db as it was possible to add more earlier), the health department employee is not able to save updates on the case (for example) without reducing the documentation.

### Steps to Reproduce

1.
2.

### Expected Behavior

The limit of the free text field should be 1.000.000 characters

### System Details

* Device:
![Bildschirmfoto 2021-12-09 um 09 29 58](https://user-images.githubusercontent.com/62540178/145363953-dfe7ea12-d16f-495e-bac7-74f7e166e0bf.png)

* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by StefanKock** [comment]
To be refined: Which fields in which entities are supposed to be changed?

**Comment by JaquM** [comment]
@StefanKock case general comment field

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment with the latest version of sormas 1.67.0-snapshot
