### ISSUE TITLE
Investigate how additional tests without an associated sample can be created

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#7489]
### Steps to Reproduce

1. Connect an app to https://test-de.sormas.netzlink.com/sormas-ui/
2. Create a case and sych 
3. result: Sync failed , please try again

### Expected Behavior

- App should sync with server
### System Details

* Device:
* SORMAS version: 1.67
* Android version/Browser:
* Server URL: https://test-de.sormas.netzlink.com/sormas-ui/#!about
* User Role: surveillanc + contact officer

### Additional Information

When connected to server with a mobile app having  1.66.2 version,  app detected that server in on a newer version but download failed. This is just additional information that may not be caused to the server.

### Development Specifications
The problem here is that there's at least one additional test without an associated sample_id on the server. When the mobile app tries to synchronize and insert this test into its database, the not null constraint on that field fails. The task here is to investigate how it's possible that additional tests without a sample are created (or whether it's possible at all and what other causes might be).

**Comment by roxanamlendea** [comment]
I attach the logs for the synchronization fail. [synchronization failed log files.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7693521/synchronization.failed.log.files.txt)

**Comment by bernardsilenou** [comment]
This may be the same cause for issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/7499
It may be good to have a look at both

**Comment by MateStrysewske** [comment]
@bernardsilenou The problem here again is that for some reason there's an additional test without a sample_id in the web database. I have absolutely no idea how that happens. So whoever picks up this issue, it's not about fixing synchronization problems, it's about investigating how additional tests without an associated sample can make their way into the system.

**Comment by alexcaruntu-vita** [comment]
After investigating this, without reproducing the problem, I think that the issue might be introduced at sync time, where samples and additional tests are pulled separately. In theory you could have a new sample with an additional test created between those two pulls, so at the time when we fetch the additional test, the corresponding sample is not in the mobile db. The web database seems to be fine, we have a not null constraint that should prevent this.

**Comment by MateStrysewske** [comment]
Possible follow-up issue: #7635
