### ISSUE TITLE
Prompt to update case disease variant is not shown when processing lab messages 2

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7496]
### Bug Description

This bug already occurred before in #5190

The pop-up that asks users to update the disease variant of a case when a positive pathogen test with a different disease variant is saved does not work when processing lab messages.

### Steps to Reproduce

1. Process a lab message
2. Enter a pathogen test with a different disease variant than the selected case and save

### Expected Behavior

The users should be asked to update the disease variant of the case
### Screenshots

Expected pop-up:
![caseDiseaseVariantUpdateCaseMissing](https://user-images.githubusercontent.com/70317594/145591201-5c176320-0fc3-47ca-9e06-9503037ca003.PNG)

![caseDiseaseVariantUpdateCaseMissing2](https://user-images.githubusercontent.com/70317594/145593972-f41ceb09-59a1-4669-a224-caa7e2666aa8.PNG)

### System Details

* Device:
* SORMAS version: 1.66.2
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Furthermore, several pathogen tests can now be added at once, which kind of messes up the current popup windows. Imagine adding several pathogen test with different results, or with different disease variants. This whole popup window functionality probably needs some refinement.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup The first pop-up was just there for reference because the disease variant change pop-up was displayed after the change pathogen test result pop-up.

> Furthermore, several pathogen tests can now be added at once, which kind of messes up the current popup windows. Imagine adding several pathogen test with different results, or with different disease variants. This whole popup window functionality probably needs some refinement.

Good point, do you think it is possible to keep triggering the existing pop-up if only one pathogen test that includes a differing disease variant is being added? I'd think about how to handle multiple entries and create a different issue for that.

**Comment by FredrikSchaeferVitagroup** [comment]
> Good point, do you think it is possible to keep triggering the existing pop-up if only one pathogen test that includes a differing disease variant is being added? I'd think about how to handle multiple entries and create a different issue for that.

That would be possible, but make the current implementation a little bulky.

How about adding a form showing the according pathogen test in the popup windows? This would allow users to better consider the decision.

Also, one could consider further validation, e.g. check for different disease variants in several pathogen test results.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Do you mean showing the disease variants of all associated pathogen tests to then let users decide which one to transfer to the case? I guess this would also only be necessary if users have to choose between different variants and be obsolete when they are the same

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Currently, the validation goes through each new or modified pathogen test, one after another. If relevant changes are detected in one of them, a popup is shown immediately, without considering other potentially changed pathogen tests,

What I am suggesting is to show just the currently checked pathogen test in the popup. When there are multiple pathogen triggering a popup, the popup would then show for each of those pathogen tests. Once a change was done, following popups proposing the same change should not show, though. This would probably be relatively simple to implement.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Ok, I think that sounds fine for now.

**Comment by FredrikSchaeferVitagroup** [comment]
To verify this issue, it probably is a good idea to check whether the behaviour specified in the comments above the `handleAssociatedCase(...)`, `handleAssociatedContact(...)` and `handleAssociatedEventParticipant(...)` of  the [PathogenTestController.java](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java) shows when creating a pathogen test for a sample without processing a lab message.

The same behaviour should also show when doing the same via processing lab messages, just the `Change pathogen test result` (see topmost screenshot) popup should never show here.
