### ISSUE TITLE
Tasks can be assigned to inactive users

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7514]
### Bug Description

Inactive users can be assigned to tasks.
### Steps to Reproduce

1. Create users and set some of them to inactive
2. create or open e.g. a case (or ther task contexts) that the inactive users have access to
3. Try assinging an inactive user

### Expected Behavior

Inactive users shoud not be assignable to tasks
### Screenshots

<img width="379" alt="tasksAssignableToArchivedUsers" src="https://user-images.githubusercontent.com/70317594/145994983-57a1c2bc-30ad-48c9-99cb-23959999f23d.PNG">
<img width="857" alt="tasksAssignableToArchivedUsers2" src="https://user-images.githubusercontent.com/70317594/145994987-963dd214-8d6e-4c1d-a409-84d601ea17b6.PNG">

### System Details

* Device:
* SORMAS version: 1.66.2/3
* Android version/Browser: chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com and test-de1.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.
