### ISSUE TITLE
Remove slf4j-log4j12 dependency in sormas-e2e-tests

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7515]
### Problem Description
sormas-e2e-tests has a dependency to slf4j-log4j12. In addition to that there is also a dependency to logback. We should get rid of the log4j12 dependency in favour of logback.

I have not identified what implication this change would have. From the code side it should have no implication since we are not directly using log4j12. It could affect to current configuration and output of log during tests, though.

### Proposed Change
Remove the dependency and make sure logback is handling the whole logging correctly.

**Comment by fhauptmann** [comment]
According to this post: https://www.slf4j.org/log4shell.html this shouldn't be affected by log4shell.

**Comment by fhauptmann** [comment]
But please check, you aren't using JMSAppender in the configuration.
