### ISSUE TITLE
Screen disturbances when filtering for unprocessed lab messages

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7518]
### Bug Description

We received a bug report from three german health departments.

> Problem ist bei der Befundbearbeitung der über DEMIS abgerufenen Labormeldungen aufgetreten:
> 
> Wenn nach „unverarbeitet“ gefiltert wird, treten beim Herunterscrollen Bildschirmstörungen auf, die ein Bearbeiten von Befunden unmöglich machen. Die blauen „verarbeiten“-Buttons flackern dann und lassen sich nicht mehr anklicken. Der Fehler war an verschiedenen Accounts und verschiedenen Workstations reproduzierbar.

This translates to:

A problem has occurred in the processing of laboratory reports retrieved via DEMIS:

When filtering for "unprocessed", screen disturbances occur when scrolling down, making it impossible to edit findings. The blue "process" buttons then flicker and can no longer be clicked. The error was reproducible on different accounts and different workstations.

### Steps to Reproduce

The behaviour was not yet reproducible.

### Expected Behavior

The aforementioned problems should not occur, filtering and process buttons should work as normal.

### System Details

* Device: ?
* SORMAS version: 1.66.2
* Android version/Browser: ?
* Server URL: ?
* User Role: ?

### Additional Information

As we could not yet reproduce this bug, input is very welcome here!

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Do we have the option to fill the lab messages directory artificially with throusands of messages to see if abundance of such makes a difference? Otherwise we might want to see if somehow we can further imitate the ITZ Bund environment.

**Comment by JaquM** [comment]
Feedback from user:

https://user-images.githubusercontent.com/78568406/146190435-298bd78f-6ec3-4ce4-8784-f626c7dedc3b.MOV

**Comment by FredrikSchaeferVitagroup** [comment]
Some additional information was just provided on this topic:

- for smaller amounts of filtered messages, this bug does not seem to occur. Therefore a workauround seems to be to reduce the number of listed lab messages via the filters. When the number reaches around 40-60, the buttons don't flicker and are clickable.
- one health department reported that the UNPROCESSED filter showed a total number of 75 (directly in the button), but no lab messages in the list.
- some reports seem to indicate that this bug started occuring after a lab message was deleted.

**Comment by FredrikSchaeferVitagroup** [comment]
I could now reproduce the bug locally. I guess it has to do with the number of lab messages in the system. I have about 130 unprocesed ones at the moment. 

It seems that somehow the [LabMessageGrid.buildDownloadButton(...)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/967f4f04337438fdc8fabd05e54f2460224821d8/sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageGrid.java#L168) is getting called over and over again once the flickering occurs.

**Comment by FredrikSchaeferVitagroup** [comment]
The problem is (most probably) that the [method to return the count of lab messages](https://github.com/hzi-braunschweig/SORMAS-Project/blob/ca716814fd6d2102c9302fabea982f66b751e315/sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java#L240) does not exclude deleted lab messages by default, but [the method to actually get lab messages (in form of LabMessageIndexDtos)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/ca716814fd6d2102c9302fabea982f66b751e315/sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java#L258) does.

A fix is uploaded [here](https://github.com/hzi-braunschweig/SORMAS-Project/commit/bccaceafbd9c11b30b0eddf8d6091b8c2f2bf40c). With this, the flickering does not occur on my system anymore. There is no pull request yet, as it is not yet totally clear whether this should go into a hotfix or not.

**Comment by FredrikSchaeferVitagroup** [comment]
@syntakker will take a look.

**Comment by AndyBakcsy-she** [comment]
On local setup I was not seeing any flickering with 50 lab messages.

**Comment by syntakker** [comment]
@AndyBakcsy-she the effect occured if at least one of the lab messages was deleted.
