### ISSUE TITLE
Pathogen test information not initially shown in sample card

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7519]
### Bug Description

When entering a sample directly with a pathogen test, the pathogen test information is not initially shown.
### Steps to Reproduce

1. Open e.g. a case (or contact, event participant) and press "new sample"
2. enter a sample and directly enter pathogen test information, save.
3. Check the information displayed in the sample card
4. Refresh the page and check the cards content again

### Expected Behavior

The pathogen test information should show immediately with other information in the card.

### Screenshots

<img width="371" alt="samplePathogenTestDisplayBug2" src="https://user-images.githubusercontent.com/70317594/146146913-1c5dcdb0-b988-462c-b3d1-bbccea9a292a.PNG">
<img width="273" alt="samplePathogenTestDisplayBug3" src="https://user-images.githubusercontent.com/70317594/146146930-66563099-f60e-4b6e-a1bf-c16426716ae0.PNG">

### System Details

* Device:
* SORMAS version: 1.66.3
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, naitonal user

**Comment by adinaflorea9** [comment]
Verified ticket on test-de1.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.
