### ISSUE TITLE
Error "could not authenticate. Please check username and password" appears on sync. When user logs out and logs back in, all cases created disappear (even cases already synched in the system disappear as well)

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#752]

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/43896752-2def8e6c-9bda-11e8-9982-9b8f63d4fcb3.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @ChristopherRiedelSymeda  URgent

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar 
Password of the user was changed this morning. That causes this problem.
You need to login with the correct username and password.

I will check the behaviour of the app when this happens and
- [ ] make sure it automatically goes to the login screen, so the user can login with the new password
- [ ] make sure login wil properly check username and password

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Works now after passwords were changed again and users relogged in. 

@Chinedar @foyiri No more erratic changing of passwords. Ferdinand. Please log into helmholtz srrver with the admin account i created for you. Do not use the admin account.
