### ISSUE TITLE
Conversion of multiple entities pop-up does not get triggered

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7529]
### Bug Description

When converting a contact into a case, the conversion of multiple entity pop-up is not triggered when the case person has other contacts or event participants in the incubation period.
### Steps to Reproduce

1. Create an event with disease COVID-19 and report date and event date 12/01/21
2. Create an event partcipant
3. Create contacts to this event participant, each having a report date and last contact date of 12/08/21
4. Set noth contacts to confirmed contacts
5. Take one of the contacts and convert it into a case, set the report date to 12/10/21

### Expected Behavior

A pop-up should appear asking the user if they want to additionaly convert further conatcts and event participants in the incubation period of the resulting case.

### Screenshots

<img width="399" alt="conversionMultipleMissingPopUp" src="https://user-images.githubusercontent.com/70317594/146216733-3684d187-5418-4b5c-bb2a-d2e369b062d7.PNG">

<img width="584" alt="conversionMultipleMissingPopUp2" src="https://user-images.githubusercontent.com/70317594/146216746-f4d82ef1-b3ba-49e2-86cc-f0633ac388bf.PNG">

<img width="481" alt="conversionMultipleMissingPopUp3" src="https://user-images.githubusercontent.com/70317594/146216753-8081df1c-6e54-4e38-852e-3d447c02ca9f.PNG">

### System Details

* Device:
* SORMAS version: 1.66.3
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com, test.sormas.netzlink.com
* User Role: admin, national user

**Comment by adinaflorea9** [comment]
Verified ticket on test-de1.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.
