### ISSUE TITLE
Fix vaccination migration issues related to event participants

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7531]
### Bug Description

The vaccination migration can lead to issues during the insertion of immunizations/vaccinations when event participants do not have a reporting user (because the reporting user of event participants does not have a not-null constraint).

### Steps to Reproduce

1.
2.

### Expected Behavior

* Once before executing the script and once in a new schema_version, fill the reportinguser_id of event participants without a reporting user with the reportinguser_id of its event
* Add a not null constraint to the reportinguser_id column of event participants
* Check where in the code an event participant without a reporting user might be created, and make sure that a reporting user is set there
* Add workaround scripts to the release notes for 1.66.3

SQL statement to fix the reportinguser_id:
`UPDATE eventparticipant SET reportinguser_id = (SELECT reportinguser_id FROM events WHERE events.id = eventparticipant.event_id) WHERE reportinguser_id IS NULL;`

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by fhauptmann** [comment]
This is also related to events where disease is null in the events table.
