### ISSUE TITLE
Add reduced vaccination module to imports and document creation [3]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7532]
### Situation Description

With the reduced vaccination https://github.com/hzi-braunschweig/SORMAS-Project/issues/7105 module, the import function of these data has been removed as well as the availability for creating documents.

### Feature Description

ONLY on systems where the reduced immunization module is active:

- [ ] Add the following vaccination information to the csv import for cases, contacts and ep - similar to how e.g. event participants in the event import or the samples in the case import are handled, allow users to import multiple vaccinations by copying & pasting the column headers into new columns
- [ ] Make the following information available for document creation form within cases, contacts and ep, similar to the handling of samples and pathogentests.
- report date
- vaccination date
- vaccine name 
- vaccine name details
- vaccine manufacturer
- vaccine type
- vaccine dose
- INN
- Batch number
- UNII code
- ATC code
- Vaccination info source

**Comment by MateStrysewske** [comment]
@JaquM Can you please add more specification to this issue? I.e. what does "all" information mean, and how should multiple vaccinations be handled? We didn't have those before.

**Comment by JaquM** [comment]
@MateStrysewske I updated the values. Is it enough with the comparison to samples?

**Comment by MateStrysewske** [comment]
@JaquM Updated the description a bit. If you're fine with that, you can remove the refine label.

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT

**Comment by leventegal-she** [comment]
@JaquM For bulk document generation can the latest vaccination be used?

For sample and pathogen test the latest positive one is used.

**Comment by JaquM** [comment]
@leventegal-she for vaccination use the last one as well. 
Last vaccination date > last report date

**Comment by markusmann-vg** [comment]
Agreed in Planning session:
The bulk action and the generation of the document will not be possible if there are multiple diseases selected.
