### ISSUE TITLE
PCR/RT-PCR Test Specification disappears in UI with saving

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7534]
### Bug Description

Any information in field PCR/RT-PCR Test Specification within a pathogen test seems to be stored but not shown in UI. It seems to be saved, cause sending to SurvNet gives the right information.

### Steps to Reproduce

1. create a sample
2. add an pathogen test with type of test: `PCR/RT-PCR` 
3. fill any information in upcoming field `PCR/RT-PCR Test Specification`
4. save
5. open the pathogen test again
6. PCR/RT-PCR Test Specification field is empty

### System Details

* Device:
* SORMAS version: 1.66.3 /9.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by kwa20** [comment]
The same happens for `typingId`, this should also be fixed! If users re-open the pathogen tests and save again, the previous data is lost.

**Comment by roxanamlendea** [comment]
The bug is still reproductible partially. The 'Typing ID' is shown in the UI when the pathogen test is reopened, but the PCR/RT-PCR Test Specifications still empty.  ![image](https://user-images.githubusercontent.com/89522688/148509175-085cd492-df9f-47ff-b2e6-206ed2378337.png)

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.
