### ISSUE TITLE
On statistic it still shows District and Region that need to be change to  state and LGA

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#754]

**Comment by hzi-braunschweig** [comment]
@foyiri Please just train these people that region =state and district = LGA. SORMAS is not only for Nigeria and so we need to keep alot of the processes and labels as generic as possible. Especially with the reports and statistics.

**Comment by MartinWahnschaffeSymeda** [comment]
Will be fixed by the new release
