### ISSUE TITLE
Bump logback to 1.2.9

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7547]
### Proposed change
Title says it all. Read [here](http://logback.qos.ch/news.html) for more information.

### Additional information
For already set up Payara domains, this configuration needs to be added manually to not lose the logging after undeployment of articfacts:
Manual change in `domain.xml`: `<jvm-options>-DlogbackDisableServletContainerInitializer=true</jvm-options>` in `server-config` paragraph.

**Comment by StefanKock** [comment]
Discussed with @markusmann-vg, we will take this ticket into the hotfix
