### ISSUE TITLE
Filtering facilities by address [2]

### ISSUE THREAD

**Issue by HendrikCK** [hzi-braunschweig/SORMAS-Project#7549]
### Situation Description

Issue [#3390](https://github.com/hzi-braunschweig/SORMAS-Project/issues/3390) was obviously closed as a duplicate and taken care of with issue [#4027](https://github.com/hzi-braunschweig/SORMAS-Project/issues/4027) instead. However, one of the key elements of issue #3390 got lost on that way, i.e. to "add address field additions as columns in the facilities configurations overview excluding area type".
Such a feature would simplify the search for a specific facility because you could also use its address. Currently some of our containment scouts / team leaders cannot find a facility in the list (e.g. schools) because it changed its name or it was initially created and stored in SORMAS with another name than the one they are searching for. At the moment, the only way to look it up is by searching for its address in an exported detailed facilities list which is an unnecessary "clicking detour".

### Feature Description

Apart from the existing columns for district / community / city there should also be one or two more for the actual address (street and house number) of the facility in the facilities configurations overview. Moreover, there should also be a corresponding filter function. 

### Possible Alternatives / optional additional feature

Whenever somebody enters the address of a person and wants to save it there should be a comparison of that address with those of the facilities catalogue. When it is within a certain similarity threshold, the user should be asked if the person might live in facility XYZ (with that specific/similar address). Of couse this might cause performance issues that need to be taken into account...

![image](https://user-images.githubusercontent.com/95846020/146772210-c1cd839e-f623-4f20-8808-6b83a60fcb4f.png)

**Comment by kathsievers** [comment]
ISSUE TRACKER COMMENT

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT

**Comment by markusmann-vg** [comment]
The optional additional feature will not be in scope for this ticket.

- [ ] Extend the search field to also search for the facility addresse and change the caption
- [ ] Add one column for the address caption (combine everything from the facility address) which is NOT sortable

**Comment by kwa20** [comment]
Navigating to the facility tab in configurations results in an error. 

<img width="818" alt="facilityFilter" src="https://user-images.githubusercontent.com/70317594/200529053-32dc22f3-398e-4923-8765-73ade3087392.PNG">

tested on test-de2.sormas.netzlink.com (1.77.0-SNAPSHOT (d975a9b))

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (4429d88).

**Comment by KristinaBorch** [comment]
The order of columns is inconsistent compared to other entities like case or contact of the detailed view in the directories. Thus, the city should be next to the postal code on the left side.

**Comment by roxanamlendea** [comment]
I'm reopening the ticket based on @KristinaBorch 's comment.
