### ISSUE TITLE
Age and Sex Column sort doesn't work in detailed contact view

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7565]
### Bug Description

Column sorting within detailed contacts doesn't work.
### Steps to Reproduce

1. open detailed contact view
2. try to sort columns for sex or age

### Expected Behavior

Columns should sort all contacts
### Screenshots

![Bug detailed contact view column](https://user-images.githubusercontent.com/78568406/147094832-cb400057-8313-471a-be62-a57a33abb578.JPG)
### System Details

* Device:
* SORMAS version: 1.66.4
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT. The sorting by age works as expected, but it doesn't take in consideration the unit (years / months / days). This is a separate issue though and there's already a ticket opened for it  #7239
