### ISSUE TITLE
Search for duplicate cases instead of persons [5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#757]
In Nigeria, millions of people are called "chinedu" for example. I immagine after using sormas in Nigeria for 5yrs and when a new case called chinedu is created, 10 suggested persons are presented to me by sormas, this is much work for me to choose the corresponding person. 

The current algrithm proposes similar persons based on "OR" operator. If a contact persons name is "Tom" for example, then all the persons with similar names in the system are suggested by sormas with
 (FIRST NAME | LAST NAME | NICKNAME | AGE | GENDER | PRESENT CONDITION | DISTRICT | COMMUNITY | CITY). Persons with missing values for age,gender, commmunity, etc are also suggested leading to a very long list of persons for the user to check each and decide if the person already existed in the system.

This is prone to errors and also create more work for the user.

I suggest we use an "AND" operator, based on (first name & last name & sex &  (age | date of birth) & region & district).  

If all these information are  provided by the user and they matches with a person in the system, only then will the person be suggested by sormas to the user to decise.

**Comment by MateStrysewskeSym** [comment]
Additionally, we need to check for already existing cases on case creation as well.

**Comment by MateStrysewskeSym** [comment]
Core idea: Use additional available data to get rid of false positives.

**Comment by MartinWahnschaffeSymeda** [comment]
In general we want to do the following:
When creating a new case we want to look for existing cases that are potential duplicates.
The existing mechanism to find similar persons is currently not needed (we should keep the logic and components alive, though).

Implementation backend & UI

- [ ] create a component to find case duplicates
- [ ] use the component when creating a new case in the web UI: Either create a new case or open the existing case
- [ ] replace the search algorithm with an SQL implementation (see #408).
- [ ] use the component during case import

**Comment by MateStrysewskeSym** [comment]
- [ ] Add CaseSimilarCriteria that has a CaseCriteria + the extra fields for similarity detection
- [ ] Add unit test for getSimilarCases method
- [ ] Remove old classes and methods for duplicate detection on person level
- [ ] Pre-select case when there is only one in the list
