### ISSUE TITLE
[Angular][Backend][SPIKE] Across the site: Facilities [1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7586]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to discuss with @MateStrysewske and understand from where we can get the facility category and facility types.
- Afterwards, this task will focus on updating / adding the facilities across the entire site.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup The facility type is usually saved in the same DTOs as the facility (e.g. the CaseDataDto has a `facilityType` field). The facility category is always calculated based on the facility type as each instance of the FacilityType enum has a `facilityTypeGroup` field (category == type group).

**Comment by laurentiustanvitagroup** [comment]
@marius2301 please confirm if the current endpoint can be used for the Angular component. Thank you!

**Comment by laurentiustanvitagroup** [comment]
Marius has checked this on the local machine and it works as expected.
