### ISSUE TITLE
Import of DEA fails when selecting a duplicate person

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7589]
### Bug Description

When importing a entry into dea and a duplicate person is selected, the import fails and the error file is not showing the reason for it.

![image](https://user-images.githubusercontent.com/74791118/148065063-2e0afec4-6229-45d5-b1c4-74f73396d2dc.png)
![image](https://user-images.githubusercontent.com/74791118/148065085-98f7d924-53c3-4bbe-84f2-485b368219d5.png)

[sormas_import_error_report (5).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7807799/sormas_import_error_report.5.csv)

When selecting "create a new person" the import is fine.

Import file:  [DEA Import.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7807824/DEA.Import.csv)

* Server URL:https://release-de.sormas.netzlink.com/ and own instance

**Comment by abrudanancuta** [comment]
Issue is fixed and validated on https://test-de1.sormas.netzlink.com/ with the version 1.68.0-SNAPSHOT
User type used was "surveilance officer"
