### ISSUE TITLE
Import of DEA fails if the dob is in January

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7591]
### Bug Description

When importing DEA-entries into Sormas the import fails if the person has a dob in January.

Error-file: [sormas_import_error_report (8).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7807893/sormas_import_error_report.8.csv)

import-file: [DEA Import.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7807892/DEA.Import.csv)

Sormas seems to subtract one month from each birth month, so the import for January must fail. I have also seen this happen with real data:

![image](https://user-images.githubusercontent.com/74791118/148067035-e3cd9e44-4948-4e41-9117-03c43e6f6a50.png)
(import-file)

Sormas:

![image](https://user-images.githubusercontent.com/74791118/148067088-15b8c7c1-1f79-44ab-90d9-b3809a3202c6.png)
 

### System Details

* Server URL:https://release-de.sormas.netzlink.com/ and own instance

**Comment by abrudanancuta** [comment]
Issue is fixed and validated on https://test-de1.sormas.netzlink.com/ with the version 1.68.0-SNAPSHOT
