### ISSUE TITLE
[Events] Superordinate/subordinate event list is incorrectly populated after refreshing/applying filters

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7599]
### Bug Description
When linking superordinate or subordinate events, the list is initially filtered according to this logic:
* When linking a superordinate event, only show events with an earlier event date
* When linking a subordinate event, only show events with a later event date

However, when applying or resetting filters, these filters are cleared (and the filters from the filter form are used instead). Those initial filters should always persist though because they make sure that no logically incorrect relations are created.

### Steps to Reproduce

1. Open or create an Event.
2. On the Subordinate Events card click on 'Link Event'
3. Check the contents of the list
4. Apply or reset the filters

### Expected Behavior
Preserve the initial filters that are described above:

* When linking superordinate events, don't allow users to set the "to" date filter to a later date than the event date of the current event (use `EventHelper.getStartOrEndDate`)
* When linking subordinate events, don't allow users to set the "from" date filter to an earlier date than the event date of the current event
* Set an error state to the respective date filter when the user enters an invalid date and disabe the apply filters button
* When the user resets the filters (or applies filters with empty dates), restore the initial filter condition from above (i.e. make sure that in any state, these conditions are in place)

### Screenshots
![subordinate events](https://user-images.githubusercontent.com/89522688/148235877-6edf9a7b-3419-440a-a087-2fd424825f68.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

**Comment by MateStrysewske** [comment]
@roxanamlendea The list being empty initially is probably correct because if you try to select a subordinate event, only events that have an event date LATER than the event you are currently looking at should appear there. The bug is rather that the list is populated after you hit apply or reset, because at that point, the initial filters that we apply are cleared, which shouldn't happen.

I'll rephrase this issue accordingly because I still consider this a bug.
