### ISSUE TITLE
Adding follow-up visit crashes

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#760]
When you authenticate and try to add a follow-up visit again, the same error loop happens.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig @Chinedar 
1. Which username on what server?
2. When is the last time the user able to synchronize with the server
3. When exactly did this happen?
4. Was the password of that user changed?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
1. I used SanaObas on the helmholtz server (Martin, all tests are done on the helmholtz server)
2. the user can synchronize but when he hits the plus button to create a visit, SORMAS crashes.
3. I just tested it and reproduced it several times (on my phone, it crashes and reopens to the pin page, on the tablet it goes back to the pin page without crashing)
4. I changed the password of SanaObas yesterday. 

Another issue is that the landing page for the contact officer is No follow ups. The default page should be ongoing (follow up) not any other. This is very important and it needs to work. The contact officer module

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
So the actual problem is the crash that happens when a visit is created; not a problem with autehntication.
Correct?

**Comment by hzi-braunschweig** [comment]
yes, once you hit the plus button for visits it crashes. when you synchronize it works well

![image](https://user-images.githubusercontent.com/19344651/44045473-e6f46864-9f28-11e8-8613-a33b3c8ac242.png)

**Comment by Chinedar** [comment]
@Maté Strysewske <m.strysewske@symeda.de> has this been fixed? We are still
experiencing the crash here in the field.

Please advice further. Thanks.
