### ISSUE TITLE
[Tasks] NatUser is unable to delete tasks

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7600]
### Bug Description
A NatUser is not able to delete tasks. On the 'Edit Task' form the 'Delete' button does not appear. According to the User Role spreadsheet a NatUser should be able to delete tasks.

### Steps to Reproduce

1. Open or Create a case.
2. Open a task (if one already exists) or create a new task.

### Actual Behavior
The 'Delete' button is not shown at the bottom of the form.

### Expected Behavior
The 'Delete' button should be shown at the bottom of the form.

### Screenshots
![image](https://user-images.githubusercontent.com/96909231/148239732-04494206-f200-4ed3-bd02-6d7cf31f8bbd.png)
![image](https://user-images.githubusercontent.com/96909231/148239973-afafd28b-f9b0-4d3b-9cf3-dcf95762abad.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
Tasks can not be deleted for all task contexts: Case, Contact, Event, General and Travel Entry.

**Comment by adinaflorea9** [comment]
I found out today that the issue can be reproduced for 'Pathogen Tests' as well. 
![image](https://user-images.githubusercontent.com/96909231/148386176-a3b91323-2648-4911-a639-e0bf23747d37.png)

**Comment by AndyBakcsy-she** [comment]
Validated ticket for both scenarios on test-de.sormas.netzlink.com environment.
