### ISSUE TITLE
Samples don't get adopted upon contact conversion into existing cases

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7606]
### Bug Description

When a contact is being converted into a new case, the sample usually gets duplicated and attached to the resulting case as well. However, if the case already exists and the contact is converted into the existing case, the sample does not get created for the resulting case.
### Steps to Reproduce

1. Create a case and a contact for the same person and make sure that they have now relation.
2. Create a positive sample and pathogen test for the contact.
2. Make sure that the report dates and other relevant dates trigger the case duplicate detection upon contact conversion.
3. Convert the contact to a case.
4. Select the existing case in the duplicate detection pop-up.
5. Check the resulting case for the sample of the contact.
6. As a control, convert a similar contact into a new case.

### Expected Behavior

Independent of how the contact gets converted into the resulting case, the sample should be adopted.
### System Details

* Device:
* SORMAS version: 1.66.1/4
* Android version/Browser: firefox
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.67.0-snapshot on local environment and test-de.sormas.netlink.com environment
