### ISSUE TITLE
Edit and create rights not initialised in task edit form

### ISSUE THREAD

**Issue by alexcaruntu-vita** [hzi-braunschweig/SORMAS-Project#7608]
### Bug Description

The edit and create rights are not properly initialised in the task edit form.

### Steps to Reproduce

1.
2.

### Expected Behavior

The variable should be set to TASK_CREATE or TASK_EDIT, depending on whether `create` is true or not.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
* Extend the `creator` calculation in `updateByCreatingAndAssignee` to set it true if the task does not have a creatorUser AND the current user is on a national level (=> allows at least those users to edit automatically generated tasks)
* Include the new task observers into the third `setReadOnly` call that only has `!creator` as its condition

**Comment by adinaflorea9** [comment]
Verified ticket on test-de2.sormas.netzlink.com using the latest version of Sormas 1.67.0-SNAPSHOT.
