### ISSUE TITLE
[Pathogen Tests] 'Specify Test Details' field is cleared when the disease is changed

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7619]
### Bug Description
When creating a Pathogen Test Result, if 'PCR / RT-PCR' is selected as 'Type of Test', the 'Specify Test Details' field opens. When the disease is selected, or changed, the field is cleared.

### Steps to Reproduce

1. Create a new Pathogen Test Result.
2. Set 'Type of test' to 'PCR/RT-PCR' -> the 'Specify Test Details' field opens.
3. Fill in the  'Specify Test Details' field with information
4. Select any disease.

### Actual Behavior
The 'Specify Test Details' shouldn't be cleared.

### Expected Behavior
The 'Specify Test Details' is cleared when the disease is changed.

### Screenshots
![specify test results field is cleared](https://user-images.githubusercontent.com/89522688/148545696-b89a175c-037b-4070-82c6-c803e0f2c5c1.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

**Comment by MateStrysewske** [comment]
@roxanamlendea Had a discussion with @alexcaruntu-vita and we agreed that changing this behaviour would be too much effort for the benefit. There's some automated logic applied when changing diseases that leads to this behaviour, but I believe that this will rarely happen to a user in a real application, so we can let it slide for now.
