### ISSUE TITLE
[Angular] Table content translation [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7621]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to use the translation provided for the different columns in tables (where applicable, like - disease, case classification, investigation, etc)
- Add a specific formatting for the table cell, by which to specify what enum we should use to map out the translation

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
