### ISSUE TITLE
[Cases] When trying to merge 2 cases, "A problem has occurred" message appears even if no changes were made to the duplicates

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7624]
### Bug Description
When merging 2 cases,  "A problem has occurred" message appears, saying that "The data could not be saved because it has been changed in the meantime", even if no changes were made to the duplicates.

### Steps to Reproduce

1. Create 2 duplicate cases.
2. Click on 'Merge duplicates'
3. Click on 'Confirm filters'
4. Click on 'Merge' without opening the case and without modifying data

### Actual Behavior
"A problem has occurred" message appears, saying that "The data could not be saved because it has been changed in the meantime"

### Expected Behavior
Case should get merged and no message should appear

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/148561330-8aad8c78-b975-4e9a-ab0b-0000a9ab6f5b.png)
![merging cases - message](https://user-images.githubusercontent.com/89522688/148561309-a2718e43-7cb7-4719-8011-a3841614d1f9.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: admin

### Additional Information
Found this when I was testing ticket #7182

**Comment by MateStrysewske** [comment]
Note: This doesn't happen all the time. I haven't figured out yet what exactly causes it, but it's not always reproducible. What is reproducible is that when the error occurs, clicking on "Confirm" again always seems to work.

**Comment by adinaflorea9** [comment]
I was able to reproduce the same error while testing ticket #7529.

Steps to reproduce:
1. Create an event with the disease COVID-19, with report date and event date of 12/1/2021.
2. Create an event participant or open an existing one.
3. Create at least 4 'confirmed' contacts for the event participant from step 2; the contacts should have the report date and last contact date of 12/8/2021.
4. Convert one of the contacts into a case with the report date of 12/10/2021.
5. From the first 'Conversion to case' pop-up select 'Yes, for some'; then pick only one contact from the list; click 'Confirm'.

6. Enter the page of the event participant from step 2.
7. Pick one of the contacts that have not been converted into a case yet; 
8. Start to convert the contact from step 7 into a case.
9. From the first 'Conversion to case' pop-up select 'Pick an existing case'; from the list below, pick the case created through steps 4 and 5; click 'Confirm'.
10. From the second pop-up select one or more of the contacts from the list; click 'Confirm'; observe the error message.

Included the list of steps to reproduce here, as I was able to reproduce the error each time only through this set of steps.

![ErrorMessageContacttoCase](https://user-images.githubusercontent.com/96909231/148923121-a9e2c397-86c1-4ff0-aba9-861e394f1df2.gif)

**Comment by roxanamlendea** [comment]
I tested this on test-de.sormas.netzlink.com and also on my local machine and I can still reproduce this bug when I follow Adina's steps from the comment above.

**Comment by roxanamlendea** [comment]
After a discussion with @sergiupacurariu , we concluded that this ticket should be closed because the issue described in the ticket (related to merging 2 duplicate cases) was fixed. @adinaflorea9 will open a new ticket for the issue described in her comment, because the issue that she found is related to conversion, not to merging.
