### ISSUE TITLE
S2S | Synchronizing between environments returns Unmatched region error

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7629]
### Steps to Reproduce
1.  Open Test-de2  environment and create a new case + add a lab message
2.  Make sure to use a Region and a District that is available also on the test-de1 environment
3.  Go to bulk edit mode in the Case directory and share this case with test-de1 env.
4.  Check the error message

### Expected Behavior 
The synchronization should work, especially when both environments have the same regions and districts

### Actual Behavior
The synchronization does not work because of this error message

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/148741347-badcc612-11e8-4b29-95fa-1b26853e6f96.png)

### System Details

* Device:
* SORMAS version: 1.67.0-SNAPSHOT
* Android version/Browser:Brave
* Server URL: test-de1 + test-de2
* User Role: NatUser

**Comment by kwa20** [comment]
@AndyBakcsy-she Did this error result in a "502 Bad Gateway" on this server? I can't access the system since roughly the time you posted the issue

**Comment by JonasCir** [comment]
@AndyBakcsy-she Netzlink has not set up the necessary infrastructure to support this. I cannot work right now, it's not a software issue :)

**Comment by vidi42** [comment]
@AndyBakcsy-she is this still reproducible? I did a quick check and it looks good

**Comment by AndyBakcsy-she** [comment]
Closing ticket as unreproducible anymore.
Synchronization between test-de2 and test-de3 works, was able to share lab messages and the error message was not present anymore.
