### ISSUE TITLE
Informant: can add contacts. Informant app should not allow contact listing.

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#763]

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Can you please look into this? From my understanding informants should be able to add contacts to a case, when they hear about them.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Sorry, this was probably misleading. I didn't want you to look at it "physically". My actual question is: From my understandingthe informant **should** be able to create contacts. I'm pretty sure we talked about this in one of our reviews. Why shouldn't he be allowed to do this? If he is creating a case and hears about a possible contact it makes total sense to allow him to enter this information.

**Comment by Chinedar** [comment]
I totally agree with Martin on this. It makes sense for the Informant to
already enter discovered contacts associated with cases. This saves time
especially in an outbreak situation.
