### ISSUE TITLE
Testbed is not working on M1 chips

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7632]
### Bug Description
While the Docker Testbed for SORMAS is working fine on x86, it does not work on M1. I was able to resolve most of the issues, however, we run into the following error
```
  Exception while deploying the app [sormas-ui] : Filesystem WatchService is unavailable



s2s-testbed-sormas_a-1  | java.io.IOException: Function not implemented



s2s-testbed-sormas_a-1  |     at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)



s2s-testbed-sormas_a-1  |     at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)



s2s-testbed-sormas_a-1  |     at com.sun.enterprise.loader.DirWatcher.<init>(DirWatcher.java:110)



s2s-testbed-sormas_a-1  |     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)



s2s-testbed-sormas_a-1  |     at com.sun.enterprise.loader.DirWatcher.forPath(DirWatcher.java:95)



s2s-testbed-sormas_a-1  |     at com.sun.enterprise.loader.DirWatcher.register(DirWatcher.java:87)



s2s-testbed-sormas_a-1  |     at com.sun.enterprise.loader.ASURLClassLoader$URLEntry.init(ASURLClassLoader.java:979)



s2s-testbed-sormas_a-1  |     at com.sun.enterprise.loader.ASURLClassLoader$URLEntry.<init>(ASURLClassLoader.java:964)



s2s-testbed-sormas_a-1  |     at com.sun.enterprise.loader.ASURLClassLoader.appendURL(ASURLClassLoader.java:270)



s2s-testbed-sormas_a-1  |     at com.sun.appserv.connectors.internal.api.ConnectorsClassLoaderUtil.createRARClassLoader(ConnectorsClassLoaderUtil.java:167)
```
There are some known [issues](https://docs.docker.com/desktop/mac/apple-silicon/) about `inotify`  and this error looks superficially related to that. 

### What to do about it?
I would wait for #4601 to land and try with a newre payara image, maybe they fixed the newer versions to work with M1. If not, there seems nothing we can do about it as the history of supporting `inotify` on Docker is pretty rough.

**Comment by JonasCir** [comment]
We cannot do anything about it. The payara docker container is not available for arm64 or multiarch. Without payara building it, we have to accept it.

**Comment by mario-kuehne** [comment]
Clarified with @JonasCir to close the ticket, because no published Payara docker images for M1 exists.
