### ISSUE TITLE
Investigate performance of reporting tool filter

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7656]
### Problem Description

Users report that filtering for "Only cases changed since last shared with reporting tool" takes a very long time.
### Proposed Solution

- [ ] Investigate performance implications for this filter when handling a large number of cases that fulfill the filter condition

### Additional Information

The filters are only active when the SurvNet Converter is configured on an instance.

**Comment by kwa20** [comment]
@mario-kuehne @rdutu-vg FYI

**Comment by rdutu-vg** [comment]
Hi @kwa20 
So this is related to development. I'll flag it to be checked, then we can see if we can also automate this in order to monitor its performance 👍

**Comment by rdutu-vg** [comment]
@kwa20 tried to reproduce the issue with a testing instance, but I was unable to see the problem (maybe because we don't have enough data)
Can you help us with some more details regarding the number of cases available in the systems where the issue was discovered?

**Comment by kwa20** [comment]
@rdutu-vg Apparently that happens when instances have more then roughly 20.000 cases

**Comment by markusmann-vg** [comment]
checklist for 2nd level support.
- steps to reproduce 
- logs
- What else? To be discussed during refinement

**Comment by vidi42** [comment]
@kwa20 on which env is this reproduceable?

**Comment by kwa20** [comment]
@vidi42 I was not able to reproduce it on a test environment so far, probabaly due to us not having as much data available as in production.

**Comment by rdutu-vg** [comment]
@kwa20  test-performance is the most "loaded" environment that we have right now, worth to check there as well :D and if needed, we can try create some scripts to populate the system. But this needs to be discussed more.

**Comment by kwa20** [comment]
@vidi42 @rdutu-vg The prerequisite that is needed, however, is a configured survnet converter since the filter will only appear when this condition is met.

**Comment by HolgerReiseVSys** [comment]
This seems to be due to a tablescan of `externalshareinfo` for each case.
An index on `externalshareinfo` improves the performance dramatically:
``` sql
CREATE INDEX externalshareinfo_caze_id_creationdate_idx ON externalshareinfo (caze_id, creationDate DESC);
```
