### ISSUE TITLE
Add a disease configuration entry to the wiki page

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7657]
### Problem Description

Currently, there is no guide on how to configure diseases or explanations for the respective database table columns. 
### Proposed Solution

- Add a wiki entry including explanations and guides on how to cirrectly configure diseases in the database via the diseaseconfiguration table. 
- Also include how to define age groups for aggregate reporting

### Additional Information

https://github.com/hzi-braunschweig/SORMAS-Project/wiki

@MateStrysewske FYI

**Comment by MartinWahnschaffe** [comment]
@kwa20 https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Disease-Configuration-Options
