### ISSUE TITLE
Refer to another Laboratory: "an error has occurred" comes up when you click on this, if you have received the sample.

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#766]
![image](https://user-images.githubusercontent.com/35563508/44095414-a6fd966a-9fd0-11e8-85f2-f09347254422.png)

Tried this with Lab manager login and admin as well.  

Is this an issue? or must the sample be received before you can refer to another laboratory?

**Comment by MartinWahnschaffeSymeda** [comment]
Can't reproduce this on our system. Can you go into more detail on what needs to be done?

@hzi-braunschweig 
Can you have a look at the error log from the server and provide the corresponding part, please?

**Comment by MartinWahnschaffeSymeda** [comment]
From the excel document: Error occurs when sample already has a test result.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig 
I still can't reproduce this bug, even for samples with sample tests. I'll release the hotfix today, please check whether it still appears for you afterwards.
