### ISSUE TITLE
[Angular] Travel entry profile - Create Case & update Create case across the board [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7668]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnQMRwM
- We will need to add the "Create case" page for the travel entry
- We will need to update the "Create case" form across the board, wherever it's used
- Please consult the current Sormas instance for details and behaviours

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
