### ISSUE TITLE
[Angular] Travel Entry add new Person [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7670]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlmgwym
- This tab consists of the same person tabs which are used elsewhere 
- Please review if the person tab is consistent with the current Sormas, and if not please update it the version from the design

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
