### ISSUE TITLE
[Angular] Add new mSERS [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7673]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/l1rRgyx
- The diseases present are from the current instance (the one used) - we will use the backend that supplies the diseases
- We will need to create a widget for the dynamic form for the disease iteration.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
