### ISSUE TITLE
Data Dictionary with Data Security Information [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7679]
### Situation Description
For data protection reasons the data dictionary has to be extended with non-functional data security information, which is described below.

The new information will be accesible as an extended data dictionary via the about section in the SORMAS UI.

### Feature Description

Pre-requisite: #7680

The input for this will be an xlsx document that contains all relevant data security information and follows the format of the data dictionary: 

- The first column needs to be the field id (dto name + field name, see #7680). 
- Sheets can be used to group the fields by entity
- If there are columns before the field id, those columns will be ignored
- All additional columns are custom

Preparation

- [ ] Create a new user right "export data protection data". Only the admin should have this right by default
- [ ] Button/download in about section called "Data Protection Dictionary"

The download triggers the generation of an extended data dictionary

- [ ] Read xlsx document desribed above from sormas/custom path in domain and create map of all field ids and the custom data provided
- [ ] For each field in the data dictionary check if custom data is defined. If so add the needed columns to the exported data dictionary and fill in the values provided in the input xlsx

Source, Original and Result can be found here:
https://github.com/hzi-braunschweig/SORMAS-Security/issues/31

### Additional Information
The corresponding Excel-Sheet can be found here: https://github.com/hzi-braunschweig/SORMAS-Security/issues/31

**Comment by leventegal-she** [comment]
Testing: 
* the file in the custom directory must be called `DataProtectionInfo.xlsx`, 
* the first column in the custom xls  should be the `field id`
* the columns starting with `K` will be appended to the data dictionary

Example generated Data protection dictionary
[sormas_data_protection_dictionary_2022-02-04_ (1).xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/8000914/sormas_data_protection_dictionary_2022-02-04_.1.xlsx)
