### ISSUE TITLE
Data dictionary should have a new column "fieldId" that is the combination of dto and field name [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7680]
### Feature Description
Currently the data dictionary has one sheet per entity that is using the caption of the dto and one column with the technial field name

### Problem Description
This makes it a bit difficult to read the data dictionary and map the provided information to the related field, as we would like to do in #7679. Also it would be good to allow users to put information together into one sheet (e.g. case data + symptoms of a case), but still have the ability the match each field technically.

### Proposed Change

- [x] Add a new first column called "fieldId" to the data dictionary.
- [x] The values are the combination of the DTO name (without the Dto post-fix) with the field name. E.g. CaseData.caseClassification
- [ ] If easily doable, the fieldId should be hidden by default

### Possible Alternatives

Discuss wether using the DTO name is the best approach here.

**Comment by AndyBakcsy-she** [comment]
Validated the implementation on my local environment using the latest Sormas version 1.68.0-snapshot.
The Field ID column is present on all sheets of the Data Dictionary document.
