### ISSUE TITLE
[Angular][SPIKE] Investigate and understand how we can populate the dashboard map with data [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7695]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: DASHBOARD MAP
- We need to investigate and understand how we can populate the dashboard map with data. Once this is understood, please add some dummy data for all data types on the dashboard so we can test it out.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
- The map only shows markers for entities with GPS coordinates.
- District colourisation only kicks in when there are district shapes for the country that is specified in the properties, and then the exact colourisation depends on quartiles.
