### ISSUE TITLE
Do not prevent bulk sending data to reporting tools if the selection contains uuids that can't be sent [2]

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#7704]
### Problem Description

Bulk sending data to reporting tool is blocked if the selection contains objects not owned(sent to other health department via s2s) or marked as not to be sent to reporting tool.

![image](https://user-images.githubusercontent.com/62599627/149938892-0f2e2f3c-05c2-48f8-be32-d3a47bcba1cd.png)

### Proposed Change

Change the error notification into a dialog with the list of UUIDs not owned and marked (Display the number) as not to be sent to reporting tool and actions to `Cancel` and `Send the data excluding with the number of cases the ones can't be shared`.

**Comment by JaquM** [comment]
@leventegal-she I think it is similar to #6860

**Comment by markusmann-vg** [comment]
@JaquM Yes, we discussed it and that's the first approach to solve the problems of 6860. Once we know more about the root cause of 6860, we can extend the functionality. However this might already help a lot

**Comment by mario-kuehne** [comment]
Test proposal:
test-de1 / test-de2 / test-de3 could be used for testing after deployment

Precondition for local testing:
-  `#survnet.url=` has to be configured in sormas.properties
- Sormas2Sormas has to be setup

**Comment by kwa20** [comment]
While translating on crowdin I noticed some minor text errors for the two following strings:

<img width="479" alt="bulkReportingSendError" src="https://user-images.githubusercontent.com/70317594/152304864-402f7ab2-a782-4747-8dbc-5e4f6061df82.PNG">

Suggestion: "(...)Please make sure that all of [%s] is owned and allowed to be shared with the external reporting tool. Then, re-try sending or only send the ones that can be sent."



<img width="477" alt="bulkReportingSendError2" src="https://user-images.githubusercontent.com/70317594/152304867-d71fb868-f890-4250-8f3e-3d23c5382e3b.PNG">

Suggestion: "(...)Please make sure that all of [%s] is owned. Then, re-try sending or only send the ones that can be sent."

**Comment by kwa20** [comment]
@vidi42 This issue is what I mentioned in the review. I think there, a list of failing case uuid's was implemented which allows copying of such easily. https://github.com/hzi-braunschweig/SORMAS-Project/issues/5703

**Comment by leventegal-she** [comment]
@kwa20 Would this be ok?
<img width="949" alt="image" src="https://user-images.githubusercontent.com/62599627/153170256-f6f57f8c-29a9-4999-8129-f2e68e49abaf.png">

Any suggestion regarding text changes are welcome.

**Comment by leventegal-she** [comment]
@JaquM It is possible to select and copy the IDs

**Comment by mario-kuehne** [comment]
### System Details

- SORMAS version: 1.69.0-SNAPSHOT 
- Browser: Chrome Version 98.0.4758.82
- Server URL: https://test-de1.sormas.netzlink.com/
- User Role: National User (used user also has role Import User)

### Testing details
**Test instance test-de1 only allows to reach the modular window (screenshot 1). It its not possible to send cases to the reporting tool in this test instance test-de1 (screenshot 2)**

screenshot 1
![try-to-send-to-reporting-tool-on-test-de1-01](https://user-images.githubusercontent.com/95228108/153842088-ec828f3c-9621-4229-b1b5-a3987b242ff5.PNG)
screenshot 2
![try-to-send-to-reporting-tool-on-test-de1-02](https://user-images.githubusercontent.com/95228108/153842202-8c0f6ace-9f2b-40fa-8c08-b6d717c10aff.PNG)

**Comment by mario-kuehne** [comment]
Local "mass data" test with Sormas 1.69.0-SNAPSHOT 1c05a245fb93e0f6889d8d113fe1d9db006a36e8


![send-to-reporting-tool](https://user-images.githubusercontent.com/95228108/155286604-6dee049c-51d2-46f8-97f7-ddcda6dc0e19.PNG)

- (vertical) scrollable UI component (text area)
- List of UUIDs can be copied by
  -  "single left click into text area" & "cmd + a" (select all) & "cmd + c" (copy)
  - "tripple left click into text area" & "cmd + c" (copy)
  
@kwa20 Can you provide information about "realistic amount of cases that are sent to reporting tool in bulk" & "realistic amount / percentage of cases that cannot be sent to reporting tool"?
