### ISSUE TITLE
Permanent deletion for TravelEntry entity and Immunization [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7712]
### Situation Description
Currently SORMAS only supports soft-deletion of entities (DeletableAdo). Soft-deletion currently set's the entity's "deleted" flag and removes references.

Is also permanently deletes some of the child entities (e.g. tasks, treatments) while other child entities are kept (e.g. visits), which is quite intransparent. 

### Feature Description
First, it should be possible to permanently delete an entity. We will keep the current process of soft-deleting an entity and extend it with a nightly job that goes through soft-deleted entities and actually deletes them.

Second, we need to clearly define at what point references are removed and children are permanently deleted in both deletion modes.

The scope of this issue is to get started by adding the generic parts and implementing it for the TravelEnry and Immunization.
Deletion of persons, documents and S2S infos will be handled by #7857 and #7854.

Basics:

- [x] split the delete method of BaseAdoService from the delete method of AbstractDeletableAdoService. The one in BaseAdoService should be called deletePermanent and acutally delete the entity. The other one will be called delete and set the deleted flag in the deletable entity. Make sure that for all services that extend AbstractDeletableAdoService deletePermanent is not called (this wil be added starting with this issue). 
- [x] Add DELETE_PERMANENT feature configuration

For travel entries tasks should no longer be deleted immediately when soft-delete is done. There are no other children that need to be taken care of. 

- [x] Move the logic that deletes tasks from the TravelEntryService delete method to the deletePermanent method
- [x] Extend the TaskService.buildActiveTasksFilter method to also check the DELETED flag for case, contact, event, travel entry (I'd use notEqual with true instead of checking both false and null).
- [x] In TravelEntryService.deletePermanent call markAsDeleted for all documents related to the travel entry

For immunizations the Vaccinations belonging to the Immunization will already by automatically deleted by OneToMany cascading.

- [x] In ImmunizationService.deletePermanent remove the Immunization from all SormasToSormasShareInfos that use it.
- [x] Don't cascade the deletion of the SormasToSormasOriginInfo - it can have other entities as-well

The permanent deletion should only be done by the backend in the context of nightly jobs:

- [x] Add an executePermanentDeletion method to the AbstractDeletableAdoService that queries all entities that are marked for deletion and calls the deletePermanent method for each of them
- [x] Add an executePermanentDeletion method to the CoreEntityDeletionService that is executed by the automatic deletion cron job, after executeAutomaticDeletion is done. For now only call executePermanentDeletion for the TravelEntryService and ImmunizationService.
- [x] **Discuss** We could run into a transaction timeout here when there are a lot of entities to be deleted. We may have to define a maximum number of entities to be deleted in one transaction and then execute the method calls in batches

**Comment by JonasCir** [comment]
Happy to see that SORMAS is now evolving from a `CRU` to an `CRUD` application :smile:

**Comment by MartinWahnschaffe** [comment]
Archiving and deleting are two completely separate thing. Archiving means that you no longer need to work on a case or similar, but you still have to keep the data, to be able to look into it later on and also to have things like dashboard analysis working - you wouldn't want to delete all your data after two months (in most countries you are not even allowed to do so), but you also wouldn't want to have all cases of the last 10 years in the case directory by default.

When it comes to soft-deletion, it's not clear yet, whether it will stay in the long term.
For now we just want to introduce permanent deletion as a new option, so soft-delete has to stay. In addtion we want to give users who manually delete data the security that it's at least possible for a short time (until midnight) to roll-back the deletion.

**Comment by JonasCir** [comment]
Alright thank you for the explanation :)

**Comment by bernardsilenou** [comment]
@JonasCir 
There are instances that only soft-delete is activated
