### ISSUE TITLE
Add new reason for hospitalization [0.5]

### ISSUE THREAD

**Issue by JaquM** [hzi-braunschweig/SORMAS-Project#7718]
### Situation Description

For German Health Departements we need another reason for hospitalization, called "for isolation".

### Feature Description

Add within `HospitalizationReasonType` the value `isolation`.

### Additional Information

This needs to be considered in the converter as well.

**Comment by bernardsilenou** [comment]
@syntakker  @JaquM 
Maybe already done, but can we make this addition DE specific?

**Comment by MateStrysewske** [comment]
@syntakker please check Bernard's comment

**Comment by adinaflorea9** [comment]
Verified ticket on test-de1.sormas.netzlink.com and test.sormas.netzlink.com, using the latest version of Sormas 1.68.0-SNAPSHOT.

**Comment by maxiheyner** [comment]
ISSUE TRACKER COMMENT
