### ISSUE TITLE
[Angular][Backend] Vaccination getById [2] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7723]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Jnbqq19
- We need to create the getById vaccination endpoint (included on immunisation, or a dedicated route for vaccines). 
- We need to retrieve all of the data for a vaccination.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by vidi42** [comment]
@marius2301 This seems to break the deployment of `sormas-rest` because in `de.symeda.sormas.rest.ImmunizationResource` there are now two methods adnotated with `@Path("/push")`: `post` and  `postVaccination`
