### ISSUE TITLE
[Angular][SPIKE] Understand how the customisation is made for each test-site [2] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7725]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to have a discussion with @MateStrysewske as to understand how the different sections from a test site (instance) are removed / displayed. What is the logic behind it, and how it is actually done (config files, hardcoded, variables, etc).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup There are basically two main places for customisations right now when it comes to enabling/disabling sections of the app: The major place is the `featureconfiguration` table in the database, the other place is the `sormas.properties` configuration file on the server. There are documentations for both in the Wiki:

https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Feature-Configuration-Options
https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Server-Configuration-Options

**Comment by laurentiustanvitagroup** [comment]
@MateStrysewske , Can we presume that we can use only the DB entries from the `featureconfiguration` table or we must always use both ? (If we use only the DB table, we will create a new endpoint to retrieve all the info - if not already available). If we need to use both, it would be a little bit of extra work as we will need to find the logic behind what should we choose as the point of truth (db or file).

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup Both sources contain different properties. The feature configuration table contains information about which features are enabled and which are disabled, and also some additional properties that control how specifically a feature is being used; the properties file contains more general information about how the server is supposed to be operated (e.g. the country it is used in, the default locale, and things like that). You'll definitely need both, but both are available through the API (the content of the properties file is accessed through the ConfigFacade), so you can create ReST endpoints for both.
