### ISSUE TITLE
[Angular] Dashboard Epi-curve Improvements [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7726]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- Tooltips should have matching colours to the category
- We need to add values for each category on the bar chart
- We need to figure out an algorithm by which to exclude empty days when there are too many entries
- We need to figure our how we can split the intervals based on the number of entries
- On the graph, the "Number of cases" title should be as per the design (distance form the graph itself)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
