### ISSUE TITLE
[Angular][Backend][SPIKE] How are the districts calculated ? [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7727]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- We need to discuss with @MateStrysewske as to understand how are the districts calculated on the dashboard map

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup If you're talking about the district shapes; the shapes themselves currently are shipped with the software (only for Nigeria, Ghana and Germany right now if I'm not mistaken) and are then applied to the map; the colourisation is based on the population of the respective district (i.e. the population needs to be uploaded to the system in the configurations). The exact calculation needs to be retrieved from the code.

**Comment by laurentiustanvitagroup** [comment]
@marius2301, please investigate how the district colorisation is calculated on the BE and if we have an end point already available.
