### ISSUE TITLE
[Angular] Dashboard "Slideshow" [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7728]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- If clicking on "play" the slideshow should move to the next disease. At a specific interval, we need to switch the disease, and populate the below section with the data from the newly selected disease
- The slideshow can be stopped, only by pressing the "STOP" button. It will not stop automatically.
- @cristinacoza please update the design for the slideshow, and include a loader and a drop-down for the slideshow timer (default it to 90s, and have additional options: 30s, 60s) (it was suggested that maybe the loader, and highlighted disease can use the same color coding as the disease in the above list).
- Slideshow update details here: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/R1x09bj
- We will focus on the second version from the design (the one with the backgrounds)
- We will need a list of default colors.

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
-AFP: Background #1646E0
Text #FFFFFF

-Anthrax: Background #A6D8FF
Text #2B323D

-Cholera: Background #FDA312
Text #FFFFFF

-Congenital rubella: Background #FF5959
Text #FFFFFF

-Cpvid 19: Background #00B32F
Text #FFFFFF

-Dengue fever: Background #B2E1E6
Text #2B323D

-Ebola: Background #E05600
Text #FFFFFF

-Guinea worm: Background #A1ADBF
Text #FFFFFF

-Human rabies: Background #4A148C
Text #FFFFFF

-Lassa: Background #FD7600
Text #FFFFFF

-Measles: Background #FFA6A6
Text #FFFFFF

-Meningitis: Background #CE93D8
Text #FFFFFF

-Monkeypox: Background #9C27B0
Text #FFFFFF

-New flu: Background #3281FA
Text #FFFFFF

-Not yet defined: Background #515B6B
Text #FFFFFF

-Other: Background #1B1F26
Text #FFFFFF

-Plague: Background #D90000
Text #FFFFFF

-Polio: Background #009CAC
Text #FFFFFF

-VHF: Background #B30000
Text #FFFFFF

-Yellow fever: Background #FDCA23
Text #2B323D

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by richardbartha** [comment]
All is fine!
Minor user experience related suggestions will be addressed in a later ticket.
