### ISSUE TITLE
[Angular] Weekly reports baseline structure [5]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7729]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/7ybvjLb
- Reference table: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/L09LV8l 
- Color logic for percentage column: 
0%-25% - #D90000 (Alert 700)
25% - 50% #FD7600 (Warning 800)
50% - 75% #FDBA1E (Warning 600)
75% - 100% #009928 (Success 700)

- We also need to include the tool tip.
- We will focus only on the main content (without the modals).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
