### ISSUE TITLE
Hidden fields are still present on creation forms

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7743]
### Bug Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/7476 hides specific person fields depending on the server locale. However, nationalHealthId and passportNumber are still visible on case and contact creation forms.
### Steps to Reproduce

1. Open the case directory and create a new case
2. Check person fields
3. Repeat for contacts
4. Convert a contact into a case
5. Process a lab message

### Expected Behavior

Fields should also be hidden on creation forms
### Screenshots

<img width="414" alt="hiddenDeFields" src="https://user-images.githubusercontent.com/70317594/150557597-b79be27e-31e7-4a4e-98a7-0e8f6f53ab67.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by syntakker** [comment]
Fixed for now. I advocate a refactoring as described in  #7935.

**Comment by AndyBakcsy-she** [comment]
Verified this issue with a FR local environment :
Case creation form:
![image](https://user-images.githubusercontent.com/70562142/153248956-f821d6df-9236-4b46-b53a-a98e59836f4d.png)


Contact creation form:
![image](https://user-images.githubusercontent.com/70562142/153249481-b2a5e6b3-e610-495b-ac4c-213d20eb7d96.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and test-de2.sormas.netzlink.com, using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.
