### ISSUE TITLE
Exporting database campaign form data is missing the first row

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7746]
### Bug Description

When exporting the campaign form data in the database export section, the first row in the generated file remains empty.
### Steps to Reproduce

1. Go to statistics and database export
2. Export campaign form data
3. Check the file

### Expected Behavior

File should contain entries in the first row
### Screenshots

<img width="743" alt="campaignFormDataFirstRow" src="https://user-images.githubusercontent.com/70317594/150582965-82191714-20e6-4be1-8b18-e66d04a5ca2c.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/7220

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.68.0-snapshot on local environment.
