### ISSUE TITLE
CI failure on development

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7752]
### Bug Description
See last [run](https://github.com/hzi-braunschweig/SORMAS-Project/runs/4899566809?check_suite_focus=true#step:7:882) on `development`.

**Comment by vidi42** [comment]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sormas-backend: Compilation failure
Error:  /home/runner/work/SORMAS-Project/SORMAS-Project/sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java:[475,62] incompatible types: cannot infer type arguments for java.util.ArrayList<>
Error:      reason: inference variable E has incompatible equality constraints javax.persistence.criteria.Selection<?>,java.lang.Object
Error:  -> [Help 1]
```

**Comment by JonasCir** [comment]
Funny thing is, I cannot reproduce it locally and in CI it's also non-deterministic :D

In my PR I replaced the offending site with more explicit types, let's see...

**Comment by mario-kuehne** [comment]
Last [run](https://github.com/hzi-braunschweig/SORMAS-Project/actions/runs/1744956589) was succesful on `development`
