### ISSUE TITLE
Access to the event directory filtered on the events of a group

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#7754]
### Feature Description
From the event file, the user can access the directory of events filtered on the events of a group.
This feature requires further development.

### Problem Description
When the user opens the event file from the event directory, the link works very well.
On the other hand, when the user opens the event file from the groups directory (accessible via the "Groups" view), this button returns to the groups view and not to the events view.

### Proposed Change
Force orientation to the "Events" view of the events directory to guarantee the expected operation of this button.

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch  - 1.70.0-SNAPSHOT(c6ff697).
