### ISSUE TITLE
Specify notification for observer of a task

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#7756]
### Feature Description
Since version 1.66, the notification sent when creating a task can be addressed to the user in charge of the task as well as to an observer user. It would be important to specify in the notification sent to observers that the notification is sent for information and not for action.

### Problem Description
In the absence of the mention "for information", there is a risk of confusion for users. The observer may indeed mistakenly think that he is in charge of the task when he has only received it for information.

### Proposed Change
We propose to add an additional line in the notification sent to observers stating “You are assigned as an observer to this task”

### Additional Information
@bernardsilenou @ftavin @emond-fuseau

**Comment by bernardsilenou** [comment]
@carolinverset 
Maybe it can happen that observer need to act on task  in another  instance?
What about keeping only the first part ie `You are assigned as an observer to this task` + message of the task
We can then tell the users not to act on any message starting with the text `You are assigned as an observer to this task`

**Comment by bernardsilenou** [comment]
@MateStrysewske  @kwa20  @JaquM 
This is planned for this week. Any further refinement pls?

**Comment by carolinverset** [comment]
> @carolinverset Maybe it can happen that observer need to act on task in another instance? What about keeping only the first part ie `You are assigned as an observer to this task` + message of the task We can then tell the users not to act on any message starting with the text `You are assigned as an observer to this task`

Ok for me !

**Comment by ftavin** [comment]
@carolinverset can you edit the description of the issue to match the last comments ?

**Comment by carolinverset** [comment]
> @carolinverset can you edit the description of the issue to match the last comments ?

done :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.68.0-snapshot on local environment.
Using a tool I was able to capture the email intent that should be sent to the user I have chosen as an observer for a task.
