### ISSUE TITLE
Info dialog does not show whole content

### ISSUE THREAD

**Issue by mario-kuehne** [hzi-braunschweig/SORMAS-Project#7757]
### Bug Description

Info dialog does not show whole content

### Steps to Reproduce

Example for Sormas2Sormas (S2S) by trying to share a case from Sormas Instance A to Sormas Instance B (B does not know infrastracture data of A)

1. EDIT_INFRASTRUCTURE_DATA = true in Sormas Instance A (featureconfiguration)
2. Login as user 'admin'
3. Create Region 'FakeRegionA'
4. Create District 'FakeDistrictA' in Region 'FakeRegionA' in Sormas Instance A
5. Create Community 'FakeCommunityA' in District 'FakeDistrictA'
6. Create case C in Region 'FakeRegionA'  & District 'FakeRegionA' & Community 'FakeCommunityA' in Sormas  Instance A
7. Try to share case C with Sormas Instance B

### Expected Behavior

Info dialog shows whole content. Info dialog UI component could/should be resizable to show whole content.

### Actual Behavior

Info dialog does not show whole content (content gets cut). Info dialog UI component not resizable.

### Screenshots

100% (Default) Zoom-Factor & 2560 x 1440 screen resolution hides some error details
![case-sharing-error-ui-does-not-show-every-detail-100-percent-zoom-factor](https://user-images.githubusercontent.com/95228108/150768681-58698df4-ef37-413f-877b-4acbe2fec91f.PNG)

Quick-Fix: Manually resize to 80% Zoom-Factor & 2560 x 1440 screen resolution
![case-sharing-error-ui-does-not-show-every-detail-80-percent-zoom-factor](https://user-images.githubusercontent.com/95228108/150768691-06a1970c-ed80-4691-bcce-3d955e7821cf.PNG)

### System Details

* Device:
* SORMAS version: 1.68.0-SNAPSHOT (commit hash df83656b45be59913465b7429b6d187453da1576)
* Android version/Browser: Firefox 96.0.2 (64-Bit) & Chrome Version 97.0.4692.99
* Server URL: localhost
* User Role: Admin

### Additional Information

Originally found issue here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7070#issuecomment-1019946670

But scope of the Vaadin UI issue could possibly affect more areas of the application. Please check.

**Comment by cazacmarin** [comment]
After playing with multiple options, by mixing 2 different component on the same Error window, they are not so good positioned, but IMHO it is reaching the scope and entire message can be read. It will look like in the next image:
![image](https://user-images.githubusercontent.com/6985315/153544083-7ac66c94-e18e-45ab-9782-ec299a0bfdb0.png)

**Comment by cazacmarin** [comment]
After adjusting all styles and sizes, final error message will look like into the next image: 
![image](https://user-images.githubusercontent.com/6985315/154002012-9df59583-d6cd-4549-a9b3-c9658a85f353.png)

**Comment by abrudanancuta** [comment]
Validated on local environment
