### ISSUE TITLE
Create automatic rule that checks mapping between EntityDto and the related entity class [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7760]
### Feature Description
The SORMAS API is defining EntityDto classes for almost any entity in the database. Most of these dtos are simply replications of the underlying entity, having the same fields and relations. One exception to this is the datbase id of the entity that is not published in the dto.

### Problem Description
The relation between dto and entity is sometimes a bit difficult to explain, since we don't have clear rules here that are enforced and validated against. One use case where this is needed is the situation where automatic deletion of fields is defined based on the EntityDto classes in the SORMAS API, but also requires us to delete the field values in the history table that is based on the entity. Thus we need a clean and validated mapping between both of them.

### Proposed Change

- [x] Make sure that every field in an EntityDto (not other DTOs) is matched by a field with the same name in an entity. Any field that is an exception to this rule, should have an annotation that reflects this (e.g. a computed field). 
- [x] Vice versa every field in an entity should be matched by a field in the dto having the same name. Exceptions to this rule should also be marked with annotations.
- [x] Fields should not use adjusted names for the database column. Again any exception to this rule needs to have an annotation that gives the "reason".

It may be possible to implement this based on ArchUnit. If not, we will have to manually implement a unit test that uses reflection to validate dto against entity and vice versa.

As a first step create the (arch) unit test and collect which fields are currenty exceptions to this rule. List them here so we can discuss how to deal with every field. The goal is to identify generic patterns.

### Additional Information

Out of scope: Refactoring attributes that currently don't match the pattern but should be: Create follow up ticket(s) for that.

**Comment by BarnaBartha** [comment]
List of fields not matching or missing:
```
org.opentest4j.AssertionFailedError: 

AggregateReport <-> AggregateReportDto
	Missing fields in entity:
	 - duplicate
	 - expiredAgeGroup

Case <-> CaseDataDto
	Missing fields in DTO:
	 - description
	 - systemCaseClassification
	 - caseAge
	 - duplicateOf
	 - completeness
	 - personId

Immunization <-> ImmunizationDto
	Missing fields in DTO:
	 - personId

SormasToSormasShareInfo <-> SormasToSormasShareInfoDto
	Missing fields in DTO:
	 - caze
	 - contact
	 - sample
	 - event
	 - eventParticipant
	 - immunization
	 - organizationId
	Missing fields in entity:
	 - targetDescriptor
	 - sender
	 - withAssociatedContacts
	 - withSamples
	 - withEvenParticipants
	 - withImmunizations
	 - pseudonymizedPersonalData
	 - pseudonymizedSensitiveData
	 - comment
	 - requestStatus
	 - responseComment

ExternalShareInfo <-> ExternalShareInfoDto
	Missing fields in DTO:
	 - caze
	 - event

PreviousHospitalization <-> PreviousHospitalizationDto
	Missing fields in DTO:
	 - hospitalization

ExternalMessage <-> ExternalMessageDto
	Missing fields in entity:
	 - reportingUser
	 - sormasToSormasOriginInfo

WeeklyReport <-> WeeklyReportDto
	Missing fields in DTO:
	 - changeDateOfEmbeddedLists

ActivityAsCase <-> ActivityAsCaseDto
	Missing fields in DTO:
	 - epiData

Contact <-> ContactDto
	Missing fields in DTO:
	 - completeness
	 - duplicateOf
	 - personId

Document <-> DocumentDto
	Missing fields in DTO:
	 - deleted
	 - storageReference

FeatureConfiguration <-> FeatureConfigurationDto
	Missing fields in DTO:
	 - entityType

Exposure <-> ExposureDto
	Missing fields in DTO:
	 - epiData

WeeklyReportEntry <-> WeeklyReportEntryDto
	Missing fields in DTO:
	 - weeklyReport

ClinicalCourse <-> ClinicalCourseDto
	Missing fields in DTO:
	 - caze

TravelEntry <-> TravelEntryDto
	Missing fields in DTO:
	 - personId
	 - resultingCaseId

ExportConfiguration <-> ExportConfigurationDto
	Missing fields in DTO:
	 - propertiesString

Visit <-> VisitDto
	Missing fields in DTO:
	 - caze

Person <-> PersonDto
	Missing fields in DTO:
	 - changeDateOfEmbeddedLists

SormasToSormasOriginInfo <-> SormasToSormasOriginInfoDto
	Missing fields in DTO:
	 - request

ShareRequestInfo <-> ShareRequestDetailsDto
	Missing fields in DTO:
	 - requestStatus
	 - sender
	 - withAssociatedContacts
	 - withSamples
	 - withEventParticipants
	 - withImmunizations
	 - pseudonymizedPersonalData
	 - pseudonymizedSensitiveData
	 - comment
	 - responseComment
	 - ownershipHandedOver
	Missing fields in entity:
	 - status

Hospitalization <-> HospitalizationDto
	Missing fields in DTO:
	 - changeDateOfEmbeddedLists

Sample <-> SampleDto
	Missing fields in DTO:
	 - pathogenTestResultChangeDate
	 - requestedPathogenTestsString
	 - requestedAdditionalTestsString

Location <-> LocationDto
	Missing fields in DTO:
	 - person

Therapy <-> TherapyDto
	Missing fields in DTO:
	 - caze
```

**Comment by BarnaBartha** [comment]
Follow-up ticket to address the non matching attributes: #11214
