### ISSUE TITLE
Missing "Facility Name" field name and mandatory sign from Case Line Listing popup

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#7766]
**Description:**
Facility name field exists in Case Line Listing popup, but there is no name for the field, only the input place holder, and the mandatory field sign lacks as well.

**Steps to reproduce:**
1. Open app
2. Login with NatUser
3. Open Cases directory
4. Click on line listing button
5. Fill all mandatory fields an for Facility select "Other facility" from dropdown options
6. Check following field

**Expected:**
Field should have a name above as the rest, and the mandatory field sign.

**Actual:**
The field name is not there and the mandatory sign.

_Issue discovered on Test-Performance environment.
Version: 1.68.0_

![missing field name and mandatory sign](https://user-images.githubusercontent.com/83643843/150952106-a6e332eb-bbd5-4411-af1e-54a61ade2da2.JPG)
![warning from it](https://user-images.githubusercontent.com/83643843/150952112-fb01fe61-7423-420a-a6d5-2c86da9299bf.JPG)

**Comment by MateStrysewske** [comment]
This has been done on purpose because displaying the name would mess up the form. It's not 100 % intuitive, but users using this form will most likely know that they need to specify a facility name if they use "Other facility".
