### ISSUE TITLE
Configuration for automatic archiving [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7775]
### Feature Description
Currently SORMAS comes with automatic archiving for cases and events. Those are archived when they were not modified for a certain number of days (90 days default). The configuration is currently done in sormas.properties.

### Problem Description
The configuration should be moved to the feature configuration in the database.
It should be extended to cover the configuration for all entites that will need automatic archiving.

### Proposed Change

Note: We will add the configuration for all core entity types, but not implement it's functionality in this issue.

- [x] Add an AUTOMATIC_ARCHIVING feature type
- [x] Add an new entityType field to the FeatureConfiguration class using the CoreEntityType enum. This enum might later become a more generic EntityType enum
- [x] Add a list of entity types to the FeatureType enum that allows to define valid options for AUTOMATIC_ARCHIVING: case, contact, event, event participant, immunization, travel entry. So in the end we would have multiple AUTOMATIC_ARCHIVING entries in the database, each for one entity type
- [x] All of them use a property to define the number of days for automatic archiving. If no property is given, default to 90 days.
- [x] The number of days defined for event participants has to be <= the number of days for events - output validation to log
- [x] The number of days defined for contacts has to be <= the number of days for cases - output validation to log
- ~~Automatic archiving for cases requires automatic archiving for contacts to be active @MartinWahnschaffe decide what to do~~
- [x] Use it to replace the configuration from sormas.properties
- [ ] Extend the feature configuration documentation accordingly

### Possible Alternatives
Use the deletion configuration instead of the feature configuration.

### Additional Information

Out of scope: Not needed for campaigns.

#7774 will be implement archiving for contacts

**Comment by bernardsilenou** [comment]
- The number of days defined for immunization has to be <= associated case for the immunization

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou What do you mean by "entries"?

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
- I meant `travel entry`
- Since `immunization` and `travel entry` can be linked to cases, I was thinking of an option to prevent archiving them while the linked case is active.

**Comment by StefanKock** [comment]
Discussed but not concluded how to implement the configuration hierarchy:

```
AUTOMATIC_ARCHIVING
   CASES
   EVENT_PARTIPIANTS


AUTOMATIC_ARCHIVING

CASE_SURVEILLANCE
  AUTOMATIC_ARCHIVING = [off/on/90d]  ?

EVENT_SURVEILLANCE
  EVENT_AUTOMATIC_ARCHIVING =
  EVENT_PARTICIPANT_AUTOMATIC_ARCHIVING =
```

Needs to be decided in smaller group.

**Comment by BarnaBartha** [comment]
Recent changes:

Added feature type AUTOMATIC_ARCHIVING and entityTypes field on FeatureConfiguration - we can now have a feature per entity based approach
Added property DAYS_FOR_AUTOMATIC_ARCHIVING with default value of 90

Feature modules

**`AUTOMATIC_ARCHIVING`**
Enables/disables the automatic archiving of core entities.
>**Supported Properties** 
>`DAYS_FOR_AUTOMATIC_ARCHIVING' : an int value specifying the number of days from last change date an entity gets archived

>**Entity types** : CASE, CONTACT, EVENT, EVENT_PARTICIPANT, IMMUNIZATION, TRAVEL_ENTRY

Add new section 
## Entity types
Some features can be defined as per entity type; to add such a feature type or extend an existing one you need to extend the FeatureType enum with the corresponding entity types resulting in an entry of that feature type in the database table for each entity type.

**Comment by richardbartha** [comment]
Verified ticket on local environment with version 1.70.0-snapshot
