### ISSUE TITLE
Pressing 'Discard' does not reset 'Place of stay' and facility related fields

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7783]
### Bug Description
When a user makes changes in the section 'Place of stay' of a case page and clicks 'Discard', not all of the fields where changes were made are reset.

### Steps to Reproduce
1. Create a new case with the 'Place of stay' set to 'Home', or open an existing one that has the 'Place of stay' set to 'Home';
2. Change the 'Place of stay' to 'Facility';
3. Fill in the fields that appear ('Facility category', 'Facility type', 'Facility', and depending on the selection form the 'Facility' dropdown, a field titled 'Facility name& description');
4. Click 'Discard' at the bottom of the page;
5. Observe the fields mentioned in step 2 and step 3.

### Actual Behavior
Not all fields have been reset/cleared - 'Place of stay' remains set to 'Facility'; 'Facility category' and 'Facility' remain filled in.

### Expected Behavior
All fields that were edited or changed during steps 2 and 3 are reset/cleared.

### Screenshots
GIF of the steps to reproduce and the behavior:
![Reset fields](https://user-images.githubusercontent.com/96909231/151185183-4d9087a9-3dd3-4e9f-96c0-71fe048071a8.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
Note 1: If the user refreshes the page after observing the behavior, all fields that were edited are reset/cleared.

Note 2: This issue has been observed while testing ticket #7245. After a discussion with @syntakker , it was decided that a separate new issue needed to be logged.

Note 3: In the 'Immunizations directory', on the 'Immunization' page, in the section 'Responsible Jurisdiction', the fields 'Facility Category' and 'Facility type' also do not get reset/cleared if the user edits them and clicks 'Discard'.

**Comment by roxanamlendea** [comment]
On the Case page this is also reproducible in the following flow:

1. Open a Case which has Facility selected as Place of Stay.
2. Edit the Case and select Home as Place of Stay.
3. Click on Discard.
-> Home is still selected as Place of Stay, even after Discard.
![facility field error](https://user-images.githubusercontent.com/89522688/153437441-fb04a146-9959-4653-b23b-f9a82b4c1898.gif)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.
