### ISSUE TITLE
Pressing 'Discard' on the 'Immunization' page does not reset the 'Overwrite immunization management status'

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7784]
### Bug Description
On an 'Immunization' page, if the user checks the check-box 'Overwrite immunization management status' and clicks 'Discard', the check-box does not get unchecked.

### Steps to Reproduce
1. Open an immunization from the 'Immunizations directory';
2. Check the check-box 'Overwrite immunization management status';
3. Check-box is checked and the 'Management Status' field becomes editable;
4. Click 'Discard' at the bottom of the page;
5. Observe the check-box from step 2 and the field mentioned in step 3.

### Actual Behavior
Check-box remains checked and the 'Management Status' field remains editable.

### Expected Behavior
Check-box is unchecked and the 'Management Status' field is read only.

### Screenshots
GIF of the steps to reproduce and the behavior:
![Immunization](https://user-images.githubusercontent.com/96909231/151191293-88d9b7e6-3734-47df-aa6c-288518980019.gif)

### System Details
* Device: windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
Note 1: If the user reloads the page after observing the behavior, the check-box is cleared and the 'Management Status' field is read only.

Note 2: Issue was observed while testing ticket #7245. After a discussion with @syntakker it was decided that a new ticket should be logged.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.
