### ISSUE TITLE
Add information about currently deployed Git commit in the About Page of test instances [2]

### ISSUE THREAD

**Issue by mario-kuehne** [hzi-braunschweig/SORMAS-Project#7786]
### Situation Description

During development phase different commits of the development branch get deployed on multiple test instances that all show the version with the template `<major>.<minor>.<patch>-SNAPSHOT` (see Sormas 'About' Page)

![image](https://user-images.githubusercontent.com/95228108/151191305-72bf09ff-7fa1-4bf9-95fb-fd9cbd60d215.png)

Issue: When trying to test implemented new features / bug fixes / change requests it is currently hard to find out if its already deployed on a specific test instance, because any commit of the same snapshot version could be deployed.

### Feature Description

Show detail information of the currently deployed Git commit (e.g. git commit hash) in the 'About' page and link to GitHub.

### Acceptance Criteria

- [ ] Sormas 'About' page shows Git commit hash
- [ ] Sormas 'About' page shows Link to specific commit on GitHub (link in tree to see history -> https://github.com/hzi-braunschweig/SORMAS-Project/commits/ `commit-id`)
- [ ] Only show on snapshot versions

### Additional Information

out of scope:
Hint: Further possible detail information we could think about (if suitable)
- Docker image version deployed
- Continuous Integration (CI)  build number / timestamp

library:
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/pom.xml

~Open Questions:~
~- Shall detail information only be shown on (specific) test instances? (on production-like or production instances specific release versions are deployed and the Git commit detail information is not necessary anymore)~

**Comment by StefanKock** [comment]
I set a link on the Version line that links directly to the history. Example:

![grafik](https://user-images.githubusercontent.com/24678567/154995800-445c8c8d-7f3e-4d87-8e80-6604dc5ea61c.png)
Link opens: https://github.com/hzi-braunschweig/SORMAS-Project/commits/eb4364e0cea411d90c772a7b0168eee732f8bc87

My current approach also refactors how the version is retrieved (originally done in #205)
