### ISSUE TITLE
Facility related fields from the 'Home address' section of a person page do not get cleared/reset when clicking 'Discard'

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7787]
### Bug Description
Fields related to 'Facility', from the 'Home address' section of entity person page, do not get cleared or reset after the user edits them and clicks 'Discard'.

This is reproducible across the directories: 
- 'Persons directory' - person page;
- 'Cases directory' - case person page;
- 'Contacts directory' - contact person page;
- 'Travel entries directory' - travel entry person page;
- 'Immunizations directory' - person page.

### Steps to Reproduce

1. Open an entity person page (from any directory mentioned in the 'Bug description' section);
2. In the section 'Home address' input data in the following fields: 
- country;
- region;
- district;
- facility category;
- facility type;
- facility;
- facility name& description (this field becomes visible depending on the selection from the previous 'facility' field);

3. Click 'Discard' at the bottom of the page;
4. Observe the fields mentioned in Step 2.

### Actual Behavior
The fields 'country', 'region', 'district', 'facility type', 'facility' have been cleared.

The field 'facility category' remains filled in.

### Expected Behavior
All fields mentioned in Step 2 are cleared/reset.

### Screenshots
GIF of the steps to reproduce:
![facility](https://user-images.githubusercontent.com/96909231/151198157-f3334f3a-a678-44ae-bf41-92895e10f3c3.gif)

### System Details
* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com and test.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
The behavior described does not reproduce for 'Event Participants' - when the user repeats the same steps described in the 'Steps to reproduce' and clicks 'Discard' all of the edited fields are cleared/reset.

Note: The behavior described in the ticket was observed while testing ticket #7245. After a discussion with @syntakker it was decided that a new ticket needed to be logged.

**Comment by roxanamlendea** [comment]
After the fix, the 'Facility Category' field gets cleared now upon 'Discard', so that's correct, but the 'Facility' field does not get cleared completely. It still has a blue exclamation point mark and the box is bolded and blue.

Before 'Discard':
![image](https://user-images.githubusercontent.com/89522688/153845789-096415c1-9d52-4629-b0a8-54d6715e9b9b.png)

After 'Discard':
![image](https://user-images.githubusercontent.com/89522688/153843100-2df19ca8-f396-43b3-945f-b49c54248c91.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.
