### ISSUE TITLE
Add a function to retrospectively classify all unclassified cases

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#779]
Since there are a lot of unclassified cases in the Nigerian system and the automatic classification can be disabled in the server properties, admins should be able to automatically classify all cases that are set to not yet classified.

- [ ] Add a "Classify all cases" button only visible to admins to the case grid
- [ ] Possibly add a warning message
- [ ] Write a method that goes over all unclassified cases and classifies them and that gets called when the button is pressed

**Comment by MartinWahnschaffeSymeda** [comment]
We should not do this until we have a clean scenario where this is needed.
