### ISSUE TITLE
Make tile server used for map configurable [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7792]
### Feature Description
We are using leaflet js to display maps in SORMAS. The used tile server url is currently hard coded in the leaflet-connector javascript.

### Problem Description
This approach does not allow to use different tile servers or to put a proxy in between.

### Proposed Change

- [ ] Add the configuration to sormas.properties
- [ ] Extend the leaflet map component to use the configured tile server

### Additional Information

Default the one that is currently hardcoded.
If there is no property defined, we don't show the tiles
Validate what happens if there is sth. defined which does not work (404)

Examples:
http://leaflet-extras.github.io/leaflet-providers/preview/index.html

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.69.0-snapshot on local environment
