### ISSUE TITLE
Add a configuration to deactivate dashboard [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#7811]
### Situation Description

Countries having many entities per week fall in  a situation that the dashbard takes a lot of server resources and break  SOMAS
### Feature Description

- Add a new  `DASHBOARD` feature type, enabled by default
- Exclude the dashboard view from the UI when the feature type is disabled (make sure that the user is redirected to another page upon login properly; should already work though)

### Additional Information
@markusmann-vg If the dashboard view is disabled, the user will be redirected to the "cases" directory

**Comment by bernardsilenou** [comment]
@vidi42  Your commit shows that you are implementing this issue,  Is there something else that need to be done by someone?
Thanks

**Comment by vidi42** [comment]
@bernardsilenou the changes have to be reviewed/tested and merged by someone in the team. Then the ticket can be closed

**Comment by vidi42** [comment]
> @markusmann-vg If the dashboard view is disabled, the user will be redirected to the "cases" directory

There is already a fallback functionality in case some of the views are not enabled, which goes trough all the menu items and picks the first one which is available.
So we don't need to redirect the user to the cases view, as that one can also be missing for some user rights, which means we will stick with the default logic that is already implemented

**Comment by carolinverset** [comment]
I sincerely thank you for your help in solving the total blockage of use of sormas in France!!

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment on Sormas 1.68.0-snapshot
