### ISSUE TITLE
[Hospitalization] User is able to save a 'Current Hospitalization' without adding a mandatory facility

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7812]
### Bug Description
A user is able to save a 'Current Hospitalization' without adding a mandatory facility.

### Steps to Reproduce
1. Create a new case or open an existing one ('Place of stay' needs to be set to 'Home' and there should be no hospitalization information);
2. Go to the 'Hospitalization' tab and add a 'Current Hospitalization' (select 'Yes' for the question 'Was the patient admitted at the facility as an inpatient');
3. Fields below become editable; input information in the fields ('Date of visit or admission', 'Date of discharge or transfer', 'Left against medical advice', 'Reason for hospitalization');
4. Click 'Save' at the bottom of the page;
5. Case is saved and a pop-up is triggered asking the user to select a mandatory facility for this hospitalization;
6. Click 'Discard' in the pop-up;
7. Click 'Save' at the bottom of the page again.

### Actual Behavior
User is able to successfully save the case and the hospitalization information. 

Pop-up asking the user to select a facility is not triggered on every attempt that the user makes to save the hospitalization.

### Expected Behavior
User is not able to save the case and the hospitalization information without adding a mandatory facility. 

Pop-up asking the user to select a facility should be triggered on every attempt that the user makes to save the hospitalization.

### Screenshots
Screenshot of the pop-up:
![Pop-up 1 for place of stay for hospitalization](https://user-images.githubusercontent.com/96909231/151769502-2435329d-5ce9-4964-b74f-3071564541fe.png)

GIF of the steps to reproduce:
![Hospitalization pop-up](https://user-images.githubusercontent.com/96909231/151770190-f928383c-a6b7-4607-a67b-8a0bac49b016.gif)

### System Details
* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de1.sormas.netzlink.com/
* User Role: Admin, NatUser

**Comment by kwa20** [comment]
I tested this and could also reproduce this behaviour on 1.67.0 (test1401.sormas-oegd.de)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS 1.69.0-SNAPSHOT from the development branch.
