### ISSUE TITLE
Investigate usage of `getCurrentUser` and how to attach the current user to the session to avoid BD round trips

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7813]
### Feature Description
`BaseFacade::getCurrentUser` and `CurrentUserService`.

### Problem Description
Right now, it seems that we have a lot of DB round trips to map the username in the session to the user ID.

### Proposed Change
Resolve the username once per active session.

**Comment by vidi42** [comment]
Blocked by https://github.com/hzi-braunschweig/SORMAS-Project/issues/7907
