### ISSUE TITLE
Cases in other jurisdictions are not displayed to clinicians with associated filter

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7814]
### Bug Description

When filtering for cases of one person, cases in jurisdictions outside of the clinicians jurisdiction are not displayed when selecting to include cases from other jurisdictions.
### Steps to Reproduce

1. Create 2 different case for one person and differing jurisdiction with user 1
2. Log in as user 2 (Clinician in the jurisdiction of one of the cases)
3. Open the person and press "See cases for this person"
4. Check the number of displayed cases and make sure that other jurisdictions are included

### Expected Behavior

Both cases should be displayed to the clinician
### Screenshots

<img width="841" alt="seeCasesOfThisPersonClinician" src="https://user-images.githubusercontent.com/70317594/151783362-e82a2649-7fdd-46c6-a026-c65b21f181b9.PNG">
<img width="594" alt="seeCasesOfThisPersonClinician2" src="https://user-images.githubusercontent.com/70317594/151783364-ffda43a6-e3a2-4052-ad48-69ed98801e7c.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas.netzlink.com
* User Role: Clinician

**Comment by MateStrysewske** [comment]
@kwa20 This is fine. Users can see all cases associated to persons in the person card, but they are not supposed to see these cases in the directory, even if they use the "Include cases from other jurisdictions" filter. In your example, the clinician (and you should be able to reproduce this behaviour with e.g. a surveillance supervisor as well) doesn't have any relation to the case in the other jurisdiction. If the case e.g. had a contact in the clinician's region, it would be shown.

The person does not have any influence in the decision which cases are visible to a user. This purely depends on jurisdiction or assignment.
