### ISSUE TITLE
Hide country specific fields in the 'Person search option' pop-up, in German and French systems [0.5]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7815]
### Feature Description
The 'Person search option' on creation forms, has a pop-up that contains a table where the results of the search are listed. Among the columns of the table 'Nickname', 'passportNumber', 'nationalHealthId'  is listed as well, on all systems.

Screenshot of the table:
![Nickname](https://user-images.githubusercontent.com/96909231/151791224-ab900d40-c7e8-414c-98c6-41093cac2f30.png)

### Problem Description
On German systems, the 'Nickname' , 'passportNumber', 'nationalHealthId' column is displayed in the table from the 'Person search option' pop-up.

### Proposed Change
On German systems, hide the 'Nickname' , 'passportNumber', 'nationalHealthId' column in the table from the 'Person search option' pop-up.

On French systems, hide the  'passportNumber' column in the table from the 'Person search option' pop-up.

### Additional Information
This proposed change is linked to the #7476 change request.

**Comment by JaquM** [comment]
Hide 
- passportNumber
- nationalHealthId
as well

**Comment by adinaflorea9** [comment]
Verified ticket on local environment using the latest version of SORMAS 1.69.0-SNAPSHOT from the development branch.
