### ISSUE TITLE
Selecting a duplicate person during event participant creation results in error

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7817]
### Bug Description

Selecting a duplicate person during the creation of an event participant results in error.
### Steps to Reproduce

1. Create an event and an event participant
2. Add another event participant which is a person duplicate of the first
3. Select the person in the "pick or create person" pop-up
4. Press save

### Expected Behavior

The user should be informed about the person already being a participant in the event and the pop-up should close without a duplicate being created.
### Screenshots

<img width="551" alt="pickExistingPersonError" src="https://user-images.githubusercontent.com/70317594/151804871-a9acb66e-9e8b-4b3f-a90b-7626d316840b.PNG">

### System Details

* Device:
* SORMAS version: 1.66.4/1.67.0
* Android version/Browser: chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user/ surveillance + contact supervisor

**Comment by StefanKock** [comment]
The error message already shows that the system acts as expected.
