### ISSUE TITLE
Follow-up comment field gets duplicated upon case conversion 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7818]
### Bug Description

When converting a contact into a case, the system duplicates the follow-up comment in front of the system information that the follow-up for the contact was canceled.
Furthermore, if the comment exceeds the limit due to the systems automatic entry, case creation and therefore conversion is prevented with a generic error message.
### Steps to Reproduce

1. Create a contact and enter a follow-up comment
2. Set the contact to confirmed and convert it to a case
3. Check the follow-up comment in the converted contact
4. Repeat the steps with the comment field filled to its limit

### Expected Behavior

The follow-up comment should not get duplicated by the systems automatic additional comment and the additional comment should not prevent the creation of a case.

### Screenshots

<img width="420" alt="followUpCommentDuplication" src="https://user-images.githubusercontent.com/70317594/151812653-e893d4e1-2dc0-4012-88eb-e6dc789f0e4b.PNG">
<img width="400" alt="contactConversionError2" src="https://user-images.githubusercontent.com/70317594/151813022-320425f6-f9e5-4c5c-8db2-775e9b81f69b.PNG">
<img width="382" alt="contactConversionError" src="https://user-images.githubusercontent.com/70317594/151813024-c3a21c77-5cf8-4cb1-8699-480304bcf908.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL:test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by kwa20** [comment]
What should be done in this issue for the hotfix:
- Prevent the duplication of the follow-up comment that gets created upon case conversion and automatic follow-up cancellation. This should mostly reduce the risk of entries exceeding the limit of the comment field when the [system] message is added.
- A separate bug report will be created to address the automatic system message exceeding the comment field limitation.

@MateStrysewske Please review if what I suggested is ok. @alexcaruntu-vita FYI

**Comment by MateStrysewske** [comment]
@kwa20 Yes, thanks!

**Comment by AndyBakcsy-she** [comment]
Validated this ticket on local environment with sormas version 1.68.0-snapshot after the hotfix branch was merged.
Converting the Contact to a Case works without duplicating the comment.

**Comment by AndyBakcsy-she** [comment]
@kwa20 I have added issue 7876 based on your comment + added a server log of the issue.
