### ISSUE TITLE
Update Keycloak to not depend on user roles anymore [3]

### ISSUE THREAD

**Issue by vidi42** [hzi-braunschweig/SORMAS-Project#7820]
### Feature Description
We want to replace the user role usage with permissions. 

### Problem Description
At the moment Keycloak is configured with a subset of user roles which are needed to access the REST API.
Removing the user roles from SORMAS requires that we also remove them from Keycloak, however since we are managing the permissions on the SORMAS side, we would like to be able to just rely on those instead of duplicating them in Keycloak as well.

### Proposed Change
- [x] Remove the user roles (`REST_USER`, `USER`, `REST_EXTERNAL_VISITS_USER`) from Keycloak SORMAS realm definition. [SORMAS.json](https://github.com/hzi-braunschweig/SORMAS-Project/blob/b32d7fc25baf9e12962347e11e969a907e926268/sormas-base/setup/keycloak/SORMAS.json)
- [x] Update `de.symeda.sormas.backend.user.KeycloakService` and remove role related updates
- [x] Optional: find a way to remove the existing roles from users in Keycloak. Probably trough an script which is ran at startup or a DB script which can be handed over to netzlink
- [x] Update any Keycloak documentation which refers to the roles

### Possible Alternatives
If removing the user roles is not working due to EJB RollesAllowed limitations, replace the user roles in Keycloak with permissions.

### Additional Information
This is a prerequisite for https://github.com/hzi-braunschweig/SORMAS-Project/issues/5056

**Comment by JonasCir** [comment]
So this will cause Keycloak to be only responsible for authentication now, authorization will now be completely moved to SORMAS?

**Comment by vidi42** [comment]
> So this will cause Keycloak to be only responsible for authentication now, authorization will now be completely moved to SORMAS?

Exactly. It was kind of like this before anyway, as once the user passed the initial role check, the full list of roles was retrieved from the DB anyway.

If we could deprecate the legacy login I think moving all this role management into Keycloak would be a good next step.

**Comment by JonasCir** [comment]
> If we could deprecate the legacy login I think moving all the rights management into Keycloak would be a good next step.

Awesome, thank you for the clarification!

**Comment by bernardsilenou** [comment]
@jwijffels  @fhauptmann 
This change may explain why we could not find user roles in keycloak

**Comment by jwijffels** [comment]
@bernardsilenou I think we were looking at the wrong tab in Keycloak when inspecting the roles. Once we do the test on the shiny-keycloak integration using the suggested changes I send by email, we can add in Keycloak the user details not to the authentication token but to the user information and the shiny-keycloak auth integration will work.
