### ISSUE TITLE
Pathogen test laboratory is required for inhouse tests

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7825]
### Bug Description

When entering a pathogen test for a sample with purpose in-house testing, the laboratory is required in the direct entry form.
### Steps to Reproduce

1. Create an in-house testing sample and directly enter a pathogen test
2. Check the laboratory field requirement
3. For comparison, create an in-house sample first and later add the pathogen test for the existing sample

### Expected Behavior

Laboratory should not be required for in-house testing samples.
### Screenshots

Direct entry
<img width="457" alt="InhouseSamplePathogenLab" src="https://user-images.githubusercontent.com/70317594/151827404-d753273f-4833-415e-8030-fc9c4ec4a8c7.PNG">

Entry for existing sample as control
<img width="605" alt="InhouseSamplePathogenLab2" src="https://user-images.githubusercontent.com/70317594/151827401-e7e5d8b8-ccd2-441f-adf4-de13ff032125.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by mario-kuehne** [comment]
Succesfully tested on https://test1401.sormas-oegd.de/ with user that has roles Admin & NationalUser with Chrome (Version 97.0.4692.99) and SORMAS Version `1.67.1`.
