### ISSUE TITLE
Day of birth filter does not get enabled for event participant list

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7826]
### Bug Description

On the event participant tab inside an event, the day of birth filter does not get enabled after selecting a year and month.
### Steps to Reproduce

1. Create and event and add an event participant
2. Add a birthday to the event participant person
3. Filter for the birthdate on the event participant tab
4. Check the day of birth filter

### Expected Behavior

The day of birth filter should become enabled when year and month were selected
### Screenshots

<img width="282" alt="dayOfBirthEmptyEp" src="https://user-images.githubusercontent.com/70317594/151832410-25bbe635-8abe-4d13-a401-8d07b56fe047.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.68.0-SNAPSHOT from the development branch.
