### ISSUE TITLE
Contact line listing contains type of contact values that are disabled on some servers

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7829]
### Bug Description

The contact line listing contains values in type of contact that should be disabled on certain servers
### Steps to Reproduce

1. Log in on a german configured server
2. Open contact line listing either via the contact directory or case contact tab
3. Check the type of contact drop-down

### Expected Behavior

type of contact values that are disabled on servers should not appear as options in the contact line listing
### Screenshots

![typeOfContactWrongSelection png](https://user-images.githubusercontent.com/70317594/151836488-f844a68e-5846-451f-8359-3c89f3a07563.jpg)

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.70.0-SNAPSHOT (34d07e3) from the development branch.
