### ISSUE TITLE
Display classification rules in app [3]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#783]
- [x] Create DiseaseClassificationCriteria class that stores a disease and the three criteria for this disease and a change date (can be a constant on the server for now)
- [x] Create rest interface that transfers a list of DiseaseClassificationCriteria for every disease
- [x] Save criteria in database (including server change date)
- [x] Build dialog that displays the rules
- [x] add ClassificationHtmlRenderer class to api, creates an HTML String with divs with CSS definitions
- [x] both UI and app use this renderer to create the HTML
- [x] Android app should use a WebView to render the HTML
- [x] don't use Vaadin CSS classes in ClassificationHtmlRenderer, but custom classes that style the elements accordingly
- [x] Main background color needs to be brighter

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] test if Column length for suspectCriteria etc. is really needed in app entity
