### ISSUE TITLE
Missing validation for phone and email for contact persons location addresses with known facility category and facility type

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7830]
### Bug Description
Data fields for  "contact person phone number"  and "contact person email address"  are not validated.### Steps to Reproduce

1. Create a new case 
2. Navigate to the person information form
3. Open a new address form
4.  Choose any address type 
5.  Complete the fields for "facility category" and "facility type"
6. Enter implausible data into the fields for "contact person phone number" and "contact person email address"
7. Save

### Expected Behavior
The fields should not accept implausible data; use the same validation as for person contact details.

### Screenshots
![Screenshot_20220125-153724_APMIS](https://user-images.githubusercontent.com/71414361/151846522-cc45c51d-e289-4f75-9118-4d3cc8e42154.jpg)
* Device: Android
* SORMAS version: 1.67.0
* Android version/Browser: version 11 (knox 3.7, API level 33)
* Server URL: (https://release-international.sormas.netzlink.com/)* 
* User Role: Hospital Informant

### Additional Information
Related issues # 7157, # 7353

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server https://test.sormas.netzlink.com/sormas-rest/ . The phone number validation will be improved in ticket #7231.

**Comment by BasilKaburi** [comment]
Great!
