### ISSUE TITLE
Allow users on national level or with no jurisdiction level to edit all tasks

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7831]
### Bug Description

Task editing is very inconsistent and some users are prohibited from editing tasks in unexpected situations.

- Admins and national users cannot edit their own tasks fully and e.g. reassign or edit the priority
    - They can also delete tasks but not edit them
    - If they are neither creator or assignee, they are fully prohibited from editing
- Supervisors can edit tasks that they have not created or are assigned to but cannot execute them
### Steps to Reproduce

1. Log in as an admin, national user
2. Assign tasks to a supervisor
2. Edit this task with a third user

### Expected Behavior

- Users with jurisdiction level "nation" or no jurisdiction level  should be able to edit or execute any task. 
~- Supervisors should be able to edit or execute any task in their jurisdiction. (as well as Admin Surveillance Supervisors)~
### Screenshots

Logged in/Assignee: admin, natUser; creator NatUser
<img width="457" alt="adminNatUserEditTask" src="https://user-images.githubusercontent.com/70317594/151852974-f5eac5da-c189-4bda-9363-647e3bb78907.PNG">

Logged in: admin, natUser; creator: surveillance supervisor
<img width="470" alt="adminNatUserEditTask2" src="https://user-images.githubusercontent.com/70317594/151853629-e0e66c2d-cdc1-48ca-9b30-f0b410213523.PNG">

Logged in: surveillance supervisor; assignee: admin, natUser; creator: NatUser
<img width="489" alt="survSupEditTask" src="https://user-images.githubusercontent.com/70317594/151852853-ba844579-2227-43c2-a870-0940e0814572.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

Likely related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/7608

**Comment by MateStrysewske** [comment]
@kwa20 The behaviour right now is actually what was specified in the past, but didn't work for quite a long time. Turned this issue into a change request accordingly.

**Comment by adinaflorea9** [comment]
Verified ticket on the latest version of Sormas 1.68.0-SNAPSHOT, on local environment.
