### ISSUE TITLE
Users that have a 'Limited disease' are able to see contacts and immunizations which have other diseases associated

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7836]
### Bug Description
Users that were created to have a limited disease, are able to see entities with other associated diseases, in the 'Contacts' and 'Immunizations' directory.

### Steps to Reproduce
1. Create a user (Admin, or National User, or Surveillance Supervisor, or Surveillance Officer) that has a limited disease ('cholera');
2. Log in with the credentials of the user from step 1;
3. Go through each directory and observe the the entities that are listed.

### Actual Behavior
I. A Surveillance Officer or a Surveillance Supervisor are able to see all contact and immunization entities in the respective directories, regardless of disease. In the persons, cases, events and samples directories the users are able to see only entities that have 'cholera' set as disease.

II. An Admin or National User are able to see all immunization entities in the respective directory, regardless of disease. In the persons, cases, contacts, events and samples directories the users are able to see only entities that have 'cholera' set as disease.

### Expected Behavior
Users that have a 'Limited disease' are able to see only entities that are associated with that disease, in every directory.

### Screenshots
![image](https://user-images.githubusercontent.com/96909231/151948348-03eece27-5a44-482b-a968-b408fbd9cd07.png)

![image](https://user-images.githubusercontent.com/96909231/151948382-11b808f4-fbec-4cf4-86e8-a7d21cb9cdb1.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com
* User Role: Admin, National User, Surveillance Supervisor, Surveillance Officer

### Additional Information
For all of the create new entity forms, the users are restricted to selecting only 'cholera' from the 'disease' drop-down.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT from the development branch.
