### ISSUE TITLE
Archived facilities do not get displayed in exposures, activityAsCase, person home address and person addresses

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7838]
### Bug Description

Archived facilities are not displayed in case and contact exposures as well as case activityAsCase. 
### Steps to Reproduce

1. Create an example facility (e.g. hospital)
2. Create a case and add an exposure and an activity as case entry which have the example facility referenced
3. Create a contact and do the same in exposures
4. Add person addresses and home address to the persons and reference the facility
4. Go to configurations and archive the facility
5. Check the respective entries for the facility being displayed as "inactive"

### Expected Behavior

The facility should be displayed as "facility name (Inactive)"

### Screenshots

<img width="528" alt="facilityReferenceInfrastructureInactiveDisplay" src="https://user-images.githubusercontent.com/70317594/151970708-b8f1a8f7-28d9-4ff1-86d5-cc26b8b9b5ca.PNG">

<img width="313" alt="facilityReferenceInfrastructureInactiveDisplay2" src="https://user-images.githubusercontent.com/70317594/151970719-ec61e68f-5281-4739-b062-5dc935b9fd7e.PNG">

<img width="494" alt="facilityReferenceInfrastructureInactiveDisplay3" src="https://user-images.githubusercontent.com/70317594/151970730-ab7f4988-9837-4b21-9bbd-fb456784d34d.PNG">

<img width="508" alt="facilityReferenceInfrastructureInactiveDisplay4" src="https://user-images.githubusercontent.com/70317594/151970744-8b59bb5b-0bd2-4ae2-8d95-80ea019351eb.PNG">

<img width="492" alt="facilityReferenceInfrastructureInactiveDisplay5" src="https://user-images.githubusercontent.com/70317594/151970768-6b65a3f7-d36c-4234-a6e3-7ca29863c3f1.PNG">

<img width="433" alt="PersonHomeAddresses" src="https://user-images.githubusercontent.com/70317594/151972209-72f71d68-a1bc-4819-bad3-7e0fd72bbfd8.PNG">

<img width="469" alt="PersonAddresses" src="https://user-images.githubusercontent.com/70317594/151972212-6ac7ada9-ba82-4910-a1d0-508437223c40.PNG">

Control for reference (expected behaviour):
<img width="307" alt="facilityReferenceInfrastructureInactiveDisplay6" src="https://user-images.githubusercontent.com/70317594/151970793-8bcef489-d4b0-4c92-9a93-5fbacad1eb70.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
@kwa20 What should happen is a user try to edit the facility data, should they be able to do it directly or the fancily need to first be de-archived ?

**Comment by adinaflorea9** [comment]
Tested the ticket on the local machine using the latest version of SORMAS from the development branch - 1.70.0-SNAPSHOT(2b5f96c).

As discussed with @MateStrysewske I am reopening the ticket as in the 'Immunizations' directory - 'Immunization' page - the facility associated with the immunization is not displayed as facilityname+(inactive), once the facility was archived.

**Comment by MateStrysewske** [comment]
@sergiupacurariu Can you have a look at this? Since this is now officially your ticket :D

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.70.0-SNAPSHOT(6684c7e);

As discussed with @sergiupacurariu I am re-opening the ticket as facilities are not displayed as 'FacilityName+(inactive)' after they are archived on the immunization page and the event page.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.70.0-SNAPSHOT(77d6ee6).
