### ISSUE TITLE
sormas-app DatabaseHelper does not sanitize SQL raw queries

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#7839]
### Bug Description
After mobile app gets upgraded from 1.42.3 to 1.60.3, the app crashes immediately when launched.
Investigating this crash reveals that a query is unable to handle apostrophes in data values.
Specifically, in `migratePersonContactDetails`, the value of `generalPractitionerDetails` contains an apostrophe which causes an SQL syntax error, crashing the app.

### Steps to Reproduce

1. Install android app version between 1.36.0 and 1.57.2
2. Under case person's information, scroll down to the "General Practitioner Name and Contact Details" text area.
3. Enter any name containing an apostrophe
4. Save
5. Close the app
6. Upgrade the app to version 1.58.0 or above
7. Launch the app
8. The app fails to launch, displaying "SORMAS has stopped. Open app again"

### Expected Behavior
The app should launch successfully after the upgrade.

### System Details

* Device: Samsung Galaxy Tab A (2016)
* SORMAS version: 1.60.3
* Android version/Browser: Android 8.1.0
* Server URL:
* User Role: Surveillance Officer

**Comment by faatihi** [comment]
I'm changing raw queries in the `DatabaseHelper` to use parameterized queries.
This should handle apostrophes and other nuanced scenarios.
It should also protect us from SQL injection.

**Comment by faatihi** [comment]
@MateStrysewske may I know the next scheduled release date

**Comment by MateStrysewske** [comment]
@faatihi The next scheduled main release is Wednesday next week; feature freeze is by the end of this week, but bugs aren't affected by that, so we would squeeze your fix in as long as it's ready before the release.

**Comment by faatihi** [comment]
Thank you @MateStrysewske
