### ISSUE TITLE
An error message appears when a user goes through different flows

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7840]
### Bug Description
An error message stating ‘An error has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it’ appears when the user goes through the following flows:

- create a case for a contact person;

- if a sample with a positive pathogen test result is added to a contact, a pop-up to create a resulting case is triggered; if the user selects 'Yes', the error message appears;

- create a case for an event participant;

-  if a sample with a positive pathogen test result is added to an event participant, a pop-up to create a resulting case is triggered; if the user selects 'Yes', the error message appears;

- create a case for a travel entry;

- send a case to the reporting tool.

### Actual Behavior
An error message stating ‘An error has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it’

### Expected Behavior
No error message appears when the user goes through the flows described above.

### Screenshots
![Create case from an event participant error message](https://user-images.githubusercontent.com/96909231/151991241-99461357-3300-461c-8cd9-640008c9901e.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de1.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
A similar error message was reproducible from the 'Immunizations' and 'Samples - Lab messages' directories, and this was logged as a comment on ticket #6599

**Comment by MateStrysewske** [comment]
@adinaflorea9 This is most likely also connected to #6599; the problem is that the new address form doesn't appear in these creation forms, but the code expects it to be there and therefore throws an error. Can you please document your findings here in the main issue as well? Thanks!
