### ISSUE TITLE
Case: Hide Reception dates of paper form (Swiss, French, German) [1]

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#7844]
### Feature Description

There are some more fields need to be hidden für data protection reasons.

### Problem Description

These fields are not relevant in Germany, Swiss and France and because of data security reasons the fields must be hidden.

### Proposed Change

For Swiss, French, German systems the following fields must be hidden everywhere (and corresponding subheadings in UI forms):
- Date received at district level
- Date received at region level
- Date received at national level

Consider import, export, data protection Dictionary, pop-ups.

**Comment by bernardsilenou** [comment]
@carolinVerset
- Should this be hidden for France also?
- @Candice-Louw what about CH ?
- These fields only make sense in countries that use paper case forms alongside with SORMAS

**Comment by carolinverset** [comment]
@bernardsilenou, I don't know these fields. Could you remind me in what context they are used? Thank you !

**Comment by bernardsilenou** [comment]
@carolinverset
They are at the end of the case form
![image](https://user-images.githubusercontent.com/12996724/152801227-23a28928-1bbf-4342-87fc-583d72302e60.png)

**Comment by carolinverset** [comment]
@bernardsilenou I don't think we use these fields in France but I nevertheless sent an email to the teams to be sure. I'll keep you informed

**Comment by carolinverset** [comment]
@bernardsilenou 
I just got confirmation that these fields can be hidden. Not used in France.

**Comment by bernardsilenou** [comment]
@ClaudeMarksteinerCSI any feedback?

**Comment by ClaudeMarksteinerCSI** [comment]
@bernardsilenou
The fields can be hidden in Switzerland.
