### ISSUE TITLE
Add dateOfArrival to travel entries and fill it when importing DEA information [3]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#7845]
**Please look at the [comment](https://github.com/hzi-braunschweig/SORMAS-Project/issues/7845#issuecomment-1068134559) by @ChristopherRiedel.**

### Situation Description

Travel entries currently don't have a dedicated arrival date field; instead, this date is part of the deaContent column.
The value is needed for automatic deletion (#7736).

### Feature Description

- [x] Add a `dateOfArrival` field to travel entries as a required field. Set it to the creationDate of the TravelEntry (SQL)
- [x] Migrate the existing data (via SQL if possible to avoid long running migration via Java) by setting the date of arrival based on the DeaContentEntry value with the caption (DEA field_id) "Einreisedatum". Keep the DEA value, so that users are able to manually compare the calculated value with the original one
- [x] Automatically fill dateOfArrival when importing CSV data. The DEA field_id for this is "Einreisedatum". Rows that don't have a proper value should be skipped
- [x] When an automatic deletion uses ORIGIN as reference for a travel entry, use the dateOfArrival field as reference.

### Additional Information

Example import file: https://github.com/hzi-braunschweig/SORMAS-Project/files/6747727/export_einreiseanmeldung_210414.2.txt

**Comment by roxanamlendea** [comment]
I tested on my local machine and I'm reopening the ticket because when uploading a DEA file, the Date of Arrival is displayed twice.

![image](https://user-images.githubusercontent.com/89522688/159696688-0044b735-713d-4952-a08b-617ad42c2a66.png)

**Comment by abrudanancuta** [comment]
Validated on test.de1 with this version 1.70.0-SNAPSHOT (6684c7e)
