### ISSUE TITLE
[Angular][Backend] FindPerson Endpoint using personSimilarityCriteria [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7850]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to create a new endpoint for findPerson using personSimilarityCriteria
- The endpoint should return the list of possible users which are matched by their firstname, lastname and email.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by FredrikSchaeferVitagroup** [comment]
Hey @marius2301 , would #7843 satisfy your needs?

**Comment by ClimedoHealthCodingTests** [comment]
@FredrikSchaeferVitagroup how about adding all elements of the existing logic: FirstName, LastName, Gender, Birthday

**Comment by FredrikSchaeferVitagroup** [comment]
@ClimedoHealthCodingTests The [PersonSimilarCriteria](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/java/de/symeda/sormas/api/person/PersonSimilarityCriteria.java) have those as attributes. Is that not sufficient?

**Comment by ClimedoHealthCodingTests** [comment]
@FredrikSchaeferVitagroup if so then perfect. My comment was based on the last bullet point of the requirements above: 

_The endpoint should return the list of possible users which are matched by their firstname, lastname and email._

Thus I thought that one would only be able to match based on firstname, lastname & email.

**Comment by mariusclimedo** [comment]
Hi @laurentiustanvitagroup . Given this is now closed was this implemented and will come out with the next release on 02/03/22? FYI - @ClimedoHealthCodingTests

**Comment by laurentiustanvitagroup** [comment]
Hi @mariusclimedo. Yes, this should already be merged. I will confirm today in the daily, and get back with a confirmation here.
