### ISSUE TITLE
Permanent deletion for Person [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7857]
### Situation Description
Big picture is permanent deletion of core entities as listed in epic #7736. 
#7712 is a pre-requisite to this and handles the permanent deletion of travel entries.

### Feature Description
When core entities (e.g. travel entries) are deleted, we also have to delete all related persons, if those are not used anymore by any other core entity (e.g. case):

- [x] Add an executePermanentDeletion method to the PersonService. It should query all persons that are no longer referenced by a Case, Contact, EventParticipant, TravelEntry or Immunization and call the PersonService.deletePermanet method for those. Make sure to unit test this.
- [x] The deletePermanent method needs to delete all ManualMessageLog entities. Location and PersonContactDetail should cascade
- [x] Add this call to the end of the executePermanentDeletion method in the CoreEntityDeletionService

Note: Person is also used by Visit, but all Visits will be deleted when the related Cases and Contacts are deleted, so this does not need to be taken care of here.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment with the latest 1.70.0-snapshot version.
In order for this to be fully tested following steps need to be made:

- Set the feature configuration DELETE_PERMANENT to true
- change the CronService# permanentDeleteEntities() to do the cleanup faster (every 2 minutes in the following example) :
  @Schedule(hour = "*", minute = "*/2", persistent = false)
          public void permanentDeleteEntities() {
           coreEntityDeletionService.executePermanentDeletion(); }
