### ISSUE TITLE
Database update script not properly working

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#786]
Daniel reported a problem with the database update shell script.
We need to reproduce and fix this.

**Comment by hzi-braunschweig** [comment]
I just sent you an email. @MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
> ./database-update.sh
> ./database-update.sh: line 4: $'\r': command not found
> ./database-update.sh: line 6: $'\r': command not found

The shell script does have windows line breaks that need to be removed.

**Comment by MartinWahnschaffeSymeda** [comment]
We need to fix line endings. I have created an issue on it's own for this: #800
