### ISSUE TITLE
[DEMIS2SORMAS] Lab name column is not sortable

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7861]
### Bug Description

The lab name column on the lab message directory is not sortable
### Steps to Reproduce

1. Open the lab message directory 
2. Sort the lab name column

### Expected Behavior

The lab name column sould be sortable
### Screenshots

<img width="540" alt="labNameSortError" src="https://user-images.githubusercontent.com/70317594/152193879-ad2f458b-5efc-412d-bb81-728ea75a91d7.PNG">

### System Details

* Device:
* SORMAS version: 1.67.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
This ticket should be testable on https://test-de2.sormas.netzlink.com/ (once deployed) or on a local DEMIS test setup.

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas 1.68.0-snapshot on local environment.
Sorting the Lab message name and Lab postal code works.

![image](https://user-images.githubusercontent.com/70562142/152685996-bbc44969-e0ee-4e4e-b1ac-499481c538e5.png)
