### ISSUE TITLE
[Tasks] Users can not see a task that is assigned to a Surveillance Officer, Surveillance Supervisor, or Admin Surveillance Supervisor

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7874]
### Bug Description
Users can not see a task (even if they created that specific task - i.e. if they have task_create user right; or they have create_entity user right and a task is created automatically with the entity) if the task is assigned to a Surveillance Officer, Surveillance Supervisor or Admin Surveillance Supervisor.

### Steps to Reproduce
1. Log in with one of the following users: Surveillance Officer, Case Officer, Hospital Informant, Community Officer, Community Informant, Contact Officer, Lab Officer;
2. Create a task for an entity (eg. 'Case investigation task' for a case; or create a new case and a 'Case investigation task' is created automatically);
3. In the task's 'Edit form' set the assignee to a Surveillance Officer, or Surveillance Supervisor, or Admin Surveillance Supervisor;
4. Save the task.

### Actual Behavior
Surveillance Officer, Case Officer: they can not see the task if it is assigned to a Surveillance Supervisor or Admin Surveillance Supervisor.

Hospital Informant, Community Officer, Community Informant, Contact Officer, Lab Officer: they can not see the task if it is assigned to a Surveillance Officer, Surveillance Supervisor or Admin Surveillance Supervisor.

### Expected Behavior
Users should be able to see the tasks that are related to their jurisdiction.

### Screenshots
GIF of the steps to reproduce and the behavior:
![TaskSurvOff](https://user-images.githubusercontent.com/96909231/152348223-c648b3c8-7343-4776-97d9-d2b07099487c.gif)

### System Details

* Device: Windows 10
* SORMAS version:  1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test.sormas.netzlink.com
* User Role: Surveillance Officer

**Comment by bernardsilenou** [comment]
I think this may also apply to community officers or hospital informants, in case they can create a task.
- Maybe the change can be that: the reporting user should always have full assess to the task associated to entities that they have full access to.

**Comment by adinaflorea9** [comment]
Starting from @bernardsilenou 's comment, I have verified the behavior described in the ticket for other users as well.

The ticket's description has been edited accordingly.

**Comment by StefanKock** [comment]
Needs to be checked, it might be a severe defect or some side effect.

**Comment by syntakker** [comment]
Comments in the code indicate that this is the intended behaviour.

**Comment by kwa20** [comment]
@syntakker Can you tell me what the comments in the code say? This behaviour might need to be reviewed and possibly changed
