### ISSUE TITLE
Missing phone and e-mail validation for 'Source of Information' details on Event page

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7877]
### Bug Description
On the Event page, on the 'Source of Information' section, if 'Hotline/Person' or 'Institutional Partner' is selected as a 'Source Type', the 'Source Telephone No' and 'Email' fields that appear have no validation.

### Steps to Reproduce

1. Open or create an Event.
2. Select 'Hotline/Person' or 'Institutional Partner' as a 'Source Type'.
3. Enter implausible data into the 'Source Telephone No' and 'Email' fields.

### Expected Behavior
The user can save the page

### Expected Behavior
The user shouldn't be able to save the page and a message informing him accordingly should be displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/152370327-e8614c05-c476-4d4b-8661-7de71ab57d7c.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test.sormas.netzlink.com/
* User Role: NatUser

### Additional Information
The issue is reproducible on the mobile app also.

**Comment by carina29** [comment]
I've discussed with @markusmann-vg about this ticket's milestone. I've set the milestone to 1.76.1 (hotfix).

**Comment by carina29** [comment]
The fix for this bug is on hotfix-1.76.1 branch.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.76.1 deployed locally

**Comment by zohaibhassan122** [comment]
@roxanamlendea, this fix is not implemented on the mobile app, I have created another issue #10991. Please consider it with the next release.
