### ISSUE TITLE
Unify server setup scripts [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#789]
- [x] shell script needs to support productive and development systems (setting on top of file)
- [x] remove batch script and add explanation on how to execute the shell script on windows systems
- [x] rename to server-setup.sh
- [x] check how to deal with line endings (windows vs linux)
- [x] increase sormas domain java heap size to 1024 (-Xmx1024) see #232

**Comment by MateStrysewskeSym** [comment]
collect-config ant script does not work anymore, which makes the Jenkins build fail.
- [ ] adjust path to glassfish-config in script
