### ISSUE TITLE
Handle person related fields and search button for travel entry and event participant forms [2]

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#7903]
Tested the ticket on test-de1.sormas.netzlink.com and after a discussion with @BarnaBartha it has been decided that a comment should be added to detail the behaviour observed.

1. Person search option should not be displayed in forms where the person related information is already filled in by the system:
- [x] 'Create new travel entry' form (that is accessed from the 'Persons' directory - 'Person' page - 'Travel Entries' card);
- [x] 'Create new travel entry' form (that is accessed from the 'Cases' directory - 'Epidemiological data' tab - 'Travel Entries' card);

2. Person search option needs to be added to:
- [x] the 'Add new event participant' form that is accessed from the 'Samples' directory - via 'Lab messages' - unprocessed lab message - 'Create new event participant';

_Originally posted by @adinaflorea9 in https://github.com/hzi-braunschweig/SORMAS-Project/issues/6599#issuecomment-1028756763_

- [x] search person should be possible also with only one name field (firstname or lastname)

**Comment by kwa20** [comment]
@BarnaBartha @adinaflorea9 I noticed that from the person form users can create travel entries for other persons since it includes person fields. Is this already covered by this issue? I won't create a duplicate then.

![travelEntryPerson](https://user-images.githubusercontent.com/70317594/153009917-7eddefac-28d2-49f2-9fee-d160e5b0886b.PNG)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and test-de2.sormas.netzlink.com, using the latest version of SORMAS 1.68.0-SNAPSHOT from the development branch.
