### ISSUE TITLE
Align username handling of Keycloak and legacy login

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#7907]
### Feature Description
SORMAS user management

### Problem Description
We want to handle usernames in an case insensitive manner just like Keycloak is doing it. (TBD)

### Proposed Change

- [ ] Finish https://github.com/hzi-braunschweig/S2S-Testbed/pull/11 such that we can test easier (Done but not merged as of now.)
- [ ] remove `AuthProvider.getProvider(configFacade).isUsernameCaseSensitive()`
- [ ] TBD

### Additional info

The following exception can occur if a username is now considered a duplicate and prevents the deployment (database migration fails):
```bash
ERROR: could not create unique index "idx_users_username_lower"
Detail: Key (lower(username::text))=(my_username) is duplicated.]]
```

Duplicates can be found with the following SQL. Rename or delete users to remove duplicates.
```sql
SELECT username, creationdate, id, uuid FROM users WHERE LOWER(username) IN (SELECT LOWER(username) FROM users GROUP BY LOWER(username) HAVING COUNT(*) > 1) ORDER BY username, creationdate;
```

**Comment by StefanKock** [comment]
Related to this issue, the deployment on at least one TEST instance fails because of duplicate user name.

**Comment by StefanKock** [comment]
duplicate username resolution documented in additional info

**Comment by abrudanancuta** [comment]
fixed was valided on test.de env with 1.69.0-snapshot version
