### ISSUE TITLE
Table headers in data dictionary are not properly displayed or translated

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7910]
### Bug Description

Some table names in the data dictionary are either not translated when exported or don't seem to have a proper caption displayed. Such tables are:
- PersonContactDetail
- ActivityAsCase
- Prescription
- Treatment
- Continent
- Subcontinent
- Country
- Region
- District
- Community
- Facility
- PointOfEntry
- TestResult (actually TestReport)

### Steps to Reproduce

1. Go to info
2. export the data dictionary in e.g. german language

### Expected Behavior

All tables should have a proper caption and be translated when exported in a different user language setting.
### Screenshots

![dataDictionaryCaptions2](https://user-images.githubusercontent.com/70317594/152805278-2b2f0ac1-6df2-43d2-89ae-97c6dd08b5d5.PNG)
![dataDictionaryCaptions3](https://user-images.githubusercontent.com/70317594/152805283-a58c231c-bc1a-43d1-b12a-807d15e17894.PNG)
![dataDictionaryCaptions4](https://user-images.githubusercontent.com/70317594/152805284-32852826-4e38-450c-ae42-9501b2fdafb3.PNG)
![dataDictionaryCaptions](https://user-images.githubusercontent.com/70317594/152805285-3ed9b66b-d60d-4342-a6b3-1f479093b456.PNG)

### System Details

* Device:
* SORMAS version: 1.67.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by adinaflorea9** [comment]
Verified ticket on local environment using the latest version of SORMAS 1.69.0-SNAPSHOT from the development branch.

Issues signaled in the ticket regarding spelling have been fixed and translations for the values mentioned in the ticket's description have been updated, on the English, German and German (Swiss) versions of the document.
