### ISSUE TITLE
Initial login failed for mobile app 

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#7911]
### Steps to Reproduce

1. Install 1.67.1 on mobile device
2. Connect to: https://release-international.sormas.netzlink.com/sormas-rest/
3. Log in with active hospital informant account
### Screenshots
![Screenshot_20220207-151626_APMIS](https://user-images.githubusercontent.com/71414361/152834270-0f00dbda-ff14-42ed-85dd-b0e0727bf3ab.jpg)

### System Details

* Device: Android 11
* SORMAS version: 1.67.1
* Android version/Browser:  Version 11 (knox 3.7, API level 33)
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Hospital informant

### Additional Information
[mobile_device_login_failure_logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8017153/mobile_device_login_failure_logs.txt)

**Comment by MateStrysewske** [comment]
@BasilKaburi Very likely a server configuration error. Please get in touch with Netzlink.

**Comment by BasilKaburi** [comment]
@MateStrysewske You are correct!  Netzlink has just detected permission restrictions and has allowed access. All is fine now.
