### ISSUE TITLE
Data Quality within SORMAS: Validate entered dates [2]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#792]
f I am not mistaken , there is no analysis yet on an important and easy computable evaluation indicator – Data quality 

e.g. onset date must be before death and after birth or other simple things like that.

It should be easy to demonstrate that cases fully and primarily assessed via SORMAS have high consistency in their data, whereas data submitted primarily via paper /EXCEL will have a certain proportion of inconsistent data.

Consistency must not only be related to calendar days. There are also les obvious issues:
-Symptoms and lab result match case definition
-lab material fits to disease
-other kind of outliers 

Use case 1
![image](https://user-images.githubusercontent.com/19344651/45618169-2507ac80-ba75-11e8-9704-90bfdb555f28.png)

![image](https://user-images.githubusercontent.com/19344651/45618298-86c81680-ba75-11e8-8b4d-50f3f754c3ea.png)

![image](https://user-images.githubusercontent.com/19344651/45618282-77e16400-ba75-11e8-8890-feb4a3fc25b3.png)

![image](https://user-images.githubusercontent.com/19344651/45618350-aeb77a00-ba75-11e8-8fa2-8ea3c493378a.png)

![image](https://user-images.githubusercontent.com/19344651/45618443-ec1c0780-ba75-11e8-808c-3d1b101718f9.png)

@MartinWahnschaffeSymeda @MateStrysewskeSym We need to discuss quiality issues in SORMAS including outliers, dates matching and required fields etc

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] We need a list of all fields that need to be validated with information on what validation should be done 
- [ ] display warnings in the UI and app for fields that are invalid, but still allow the user to save

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
List of fields
- [ ] Date of onset should not be after date of hospitalization
- [ ] Date of hospitalization should not be after date of sample collection, testing, shipping and received dates
- [ ] Date of sample collection should not be after date of shipment
- [ ] Date of sample collection should not be after date sample was recieved in the lab
- [ ] Date of sample collection should not be after date sample was tested
- [ ] Date of reception should not be after date of investigation

**Comment by MartinWahnschaffeSymeda** [comment]
Additions from #293 

- [ ] case admission & discharge
- [ ] previous hospitalization
- [ ] burial
- [ ] travel
- [ ] sample shipped & received
- [ ] task start & due

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym  Date formats should not be allowed to manually enter dates due to mistakes

![image](https://user-images.githubusercontent.com/19344651/47863800-6e7b4380-ddf8-11e8-8261-d0a7a4b48201.png)
 We have found alot of mistakes in the database with the dates. For instance, someone manually entered a date to be 0018/12/10 and the system allowed data to be saved in the database. 

We need to address this as well. Do not allow manual data entry but they should use the calender icon to select date or use a simpler calender popup function for non technical people

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] check what happens when one of the dates is missing
- [ ] fix the issue with only entering "18" as year
- [ ] write update script that changes all dates in year 18 to 2018

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add schema version
- [ ] add unit test for TemporalCalculator
- [ ] fix styling of date time field -> layout fails when field has error
- [ ] 00 results in 2001. Why?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] validate date of death, burial and birth
