### ISSUE TITLE
Adding a second positive test result of a different disease to a sample, creates 2 cases for the same disease

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7922]
### Bug Description
 For a contact and event participant, that have a sample with a positive test result for 1 disease, adding a second positive test result for a different disease, prompts the system to give the user the option to create 2 new cases for the second test result, and changes the initial resulting case that the contact or event participant entity had.

### Steps to Reproduce
1. Create a contact or event participant (with the disease set to COVID-19);
2. Add a sample with a positive pathogen test result (with the disease set to COVID-19);
3. Click 'Yes' in the pop-up to create a resulting case for the contact entity or event participant entity that is triggered - **'Create a case from contact/event participant with positive test result - You have just saved a positive laboratory result for the contact disease. Do you want to create a case for the contact person. The case will be set as the resulting case of this contact, and the final laboratory result of the sample will automatically be set to positive'**;
4. Fill in the 'Create new case' form with the mandatory data;
5. Go to the contact from step 1, and open the sample created on step 2;
6. Add a 'New positive test result' to the sample (with the disease set to Anthrax);
7. Click 'Yes' in the second pop-up to create a case that is triggered: **'Create a case for this contact person - You have just saved a positive laboratory result for a different disease than the contact disease. Do you want to create a case with this disease for this contact person? The case will not be set as the resulting case for this contact'**;
8. Fill in the 'Create new case' form with the mandatory data;
9. The new case gets created with the disease Anthrax, the user is redirected to the case page in the background, and a third pop-up appears - **'Generate new case for Anthrax? - You have just created a positive pathogen test result for a different disease. Do you want SORMAS to automatically generate a new case with this new disease? All information from this case will be copied to the new case';**
10.  Click 'Yes' in the pop-up.

### Actual Behavior
A second case gets created with the disease Anthrax.

The resulting case of the contact entity is changed from the initial resulting case for COVID-19 created at step 4, to the first case created for Anthrax; while the resulting case of the event participant entity is changed to the second case created for Anthrax.

### Expected Behavior
Only one case gets created with the disease Anthrax; 

The resulting case of the contact entity and event participant entity does not get changed from the initial resulting case for COVID-19.

Note: I discussed briefly the issue described above with @MateStrysewske and it has been suggested that one of these pop-ups should be skipped though (the one of the contact, i.e. case should always have prevalence).

### Screenshots
![Cases-samples-tests](https://user-images.githubusercontent.com/96909231/152975214-16fcce21-722e-42cc-99b5-937526dc333d.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome 
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information
The behavior was observed while testing ticket #7793.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT (0b8c595) from the development branch.
