### ISSUE TITLE
Permanent deletion for Contact and Visit [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7931]
### Situation Description
Big picture is permanent deletion of core entities as listed in epic https://github.com/hzi-braunschweig/SORMAS-Project/issues/7736.

### Feature Description

**Contact**

The soft-delete of all samples related to the contact should stay as is (ContactService .delete calls TaskService.delete)

- [x] Move the logic that deletes tasks from the ContactService delete method to the deletePermanent method
- [x] Duplicate the logic that deletes samples for ContactService.deletePermanent. So when a contact is permanently deleted all related samples are also permanently deleted
- [x] In deletePermanent call markAsDeleted for all documents related to the contact
- [x] In deletePermanent remove the Contact from any SormasToSormasShareInfo that is referencing it and delete it if no longer referenced by another entity
- [x] Don't cascade the deletion of the SormasToSormasOriginInfo - it can have other entities as-well
- [x] In deletePermanent **and** delete remove the Contact from any Exposure.contactToCase that is referencing it -> see how unlinking is done for the case (probably a separate method called from both delete and deletePermanent)
- [x] In deletePermanent remove the Contact from any Contact.duplicateOf that is referencing it
- [x] CoreEntityDeletionService: Call executePermanentDeletion for the ContactService

**Visit**

This is similar to what we are doing for persons in #7857: When no contact or case is referencing a visit anymore, it needs to be deleted.

- [x] Add an executePermanentDeletion method to the VisitService. It should query all persons that are no longer referenced by a Case, or Contact and call the VisitService.deletePermanet method for those. Make sure to unit test this.
- [x] Add this call to the end of the executePermanentDeletion method in the CoreEntityDeletionService. Only PersonService should be called afterwards

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine. I am re-opening it as an exception is thrown: Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "contact" violates foreign key constraint "fk_task_contact_id" on table "task"
  Detail: Key (id)=(15730) is still referenced from table "task".

**Comment by AndyBakcsy-she** [comment]
Testing this ticket on local setup 

Necessary configuration for testability:

https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Feature-Configuration-Options (see DELETE_PERMANENT and set to true)
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_CUSTOMIZATION.md#deletion-configuration (example: entitytype == CASE; deletionreference == CREATION; deletionperiod == 7)
(Optional) configuration for - more comfortable - (local) testability:

reconfigure method deleteExpiredEntities in CronService.java to schedule with high frequency (e.g. every 5 minutes @Schedule(hour = "*", minute = "*/5", persistent = false))

**Comment by AndyBakcsy-she** [comment]
Following scenarios have been verified and worked on local setup with the latest version of Sormas 1.71.0-snapshot logged on with NatUser and having the automatic deletion set for every 5 minutes:

1. contact that has no other associated entities (contact entity and the person entity)
2. contact that has no other associated entities, but has been manually archived
3. contact that has a resulting case, but has been archived (delete only the contact; only the contact has been archived)
4. contact that has no other associated entities, but has been manually deleted
5. contact + person + sample + task
6. contact + person + task
7. visit associated with a contact
8. visit associated with a case   -------- still testing:
9. visit that has been soft deleted from the UI
10. visit associated with a contact that has a resulting case
11. visits associated with an archived contact/case
12. visit that has symptoms (check that symptoms are all permanently deleted)
13. contact+resulting case that have a visit (delete only one of these 2 entities) - if the visit is still referenced by either of them, the visit should not be deleted
14. contact create via the event participant
15. contact created via processing a lab message
16. contact + person + exposure + visit + resulting case + source case + event + task + sample + immunization
17. contact + person + source case
18. contact + person + resulting case + source case
19. contact + person + immunization
20. contact + person + linked event
21. contact + person + exposure + visit - no symptoms
22.  contact + person + sample + pathogen test + additonal test
23. contact + person + sample + pathogen test + resulting case

No Exceptions have been thrown by the backend

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.71.0-[snapsoht](https://github.com/hzi-braunschweig/SORMAS-Project/commits/b900a16a5f5055abfa6ae4994193d2eda5a159f9) on local setup.
