### ISSUE TITLE
Permanent deletion for Sample and LabMessage [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#7932]
### Situation Description
Big picture is permanent deletion of core entities as listed in epic https://github.com/hzi-braunschweig/SORMAS-Project/issues/7736.
https://github.com/hzi-braunschweig/SORMAS-Project/issues/7712 is a pre-requisite to this.

### Feature Description

**Sample**

- [x] Move the logic that permanently deletes pathogen test and additional tests SampleService delete method to the deletePermanent method
- [x] In deletePermanent remove the Sample from any SormasToSormasShareInfo that is referencing it and delete it if no longer referenced by another entity (see CaseService.deletePermanent).
- [x] Don't cascade the deletion of the SormasToSormasOriginInfo - it can have other entities as-well
- [x] In deletePermanent **and** delete remove the Sample from any Sample.referredTo that is referencing it -> see how this is done for the case (probably a separate method called from both delete and deletePermanent)
- [x] In deletePermanent **and** delete remove the Sample from any LabMessage that is referencing it
- [x] Re-introduce permanent deletion of samples associated to cases that are permanently deleted (had to be changed to soft-deletion in #8605)

**LabMessage**

- [x] make sure delete and deletePermanent are correctly doing a soft / permanent deletion
- [x] TestReport should no longer extend DeletableAdo, so remove the deleted flag. In TestReportService check the related LabMessage for it's deleted flag instead.

Finally:

- [x] CoreEntityDeletionService: Call executePermanentDeletion for the SampleService and LabMessageService
- [x] In ImmunizationService.deletePermanent remove the Immunization from any SormasToSormasShareInfo that is referencing it and delete it if no longer referenced by another entity (see CaseService.deletePermanent). (the deletion part was not done by #7712).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(fee9521).

Configurations necessary for testing:
1. In IntelliJ - CronService.java: 
     @Schedule(hour = "*", minute = "*/5", persistent = false)
	public void deleteExpiredEntities() {
		System.out.print("------- Delete Expired Entities happened now -----");
		coreEntityDeletionService.executeAutomaticDeletion();

2. In the Data Base:
     2.1. featureconfiguration panel - featuretype DELETE_PERMANENT set to 'true'
     2.2. deleteconfiguration panel:
               - deletionreference - query tool - update deletionconfiguration set deletionreference='CREATION' where id<129;
               - deletionperiod - query tool - update deletionconfiguration set deletionperiod=2 where id<129;
               
    Note: '129' is the id value specific for my DB, when testing, this needs be changed based on the id value from that specific DB
 
 Section of the ticket that could not be covered while testing:
 
![image](https://user-images.githubusercontent.com/96909231/163388665-a49eb134-1dbb-4d06-8151-56ae4adec7c4.png)

Currently, Lab Messages are not permanently deleted (they are still visible in the DB); as discussed with @MateStrysewske Permanent deletion for Lab Messages will be covered by a PR in ticket #8295.
