### ISSUE TITLE
[Angular] Dashboard Contacts - "dashboard-under-follow-up" sub-section [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7949]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP041vq
- @cristinacoza please clarify if we need the "i" icon or not. If yes, what should we display in the tool-tip.
- Design with info: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKEzrn8

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by sandorbanvitagroup** [comment]
QA: 
Please test that:
- it is similar to the design
- the icons are ok with colors

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
