### ISSUE TITLE
Analyse daily regression run

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#7954]
Aim:
Check Allure report generated after automated tests execution.
Identify defects based on the results provided
Identify automation defects, and flag them to the automation team

The job is automatically triggered after sormas deploy to test job, but can be also manually triggered whenever needed in order to check if a new functionality has an impact across a specific component or others related.
Feel free to trigger the execution whenever needed to investigate the results.

**Comment by mario-kuehne** [comment]
> Regression analysis couldn't been executed today due deployment issues, so test-performance environment is not up to date.

The same applies today.

**Comment by rdutu-vg** [comment]
Please be aware that tests:

- Check the filter of tasks context
- Check the filter of tasks status
will fail during regression run due to: 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/8019

**Comment by StefanKock** [comment]
This ticket is closed and will be replaced by other processes.
