### ISSUE TITLE
[Custom Case Export] Hide 'Education' field in German systems 

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7957]
### Bug Description
'Education' checkbox is present in the 'Cases' directory, in the 'New Export Configuration' form.

Ticket #7476 includes 'Education' among the fields that should be hidden for German systems.

### Steps to Reproduce

1. Open the 'Cases' directory;
2. Click 'Export' and from the dropdown select 'Custom Case Export';
3. In the pop-up click 'New Export Configuration';
4. Observe the 'General Person Data' section.

### Actual Behavior

'Education' is listed among the checkboxes for the export.

### Expected Behavior

'Education' is not listed among the checkboxes for the export.

### Screenshots

![Education field on DE instances](https://user-images.githubusercontent.com/96909231/153437715-8b5c7669-8d1b-4bb3-86b9-06a2c1ea0da4.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin

### Additional Information

This was observed while testing ticket #7743.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas deployed on local environment:
![image](https://user-images.githubusercontent.com/70562142/153827151-730e2c76-3eb1-4011-abeb-4eab6f8d783e.png)
