### ISSUE TITLE
[Custom Export] Hide 'National Health ID' field in German systems

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7958]
### Bug Description

'National Health ID' checkbox is present in the 'Events' directory, on the 'Event Participants' page, in the 'New Export Configuration' form.

Ticket #7476  includes 'National Health ID' among the fields that should be hidden for German systems.

### Steps to Reproduce

1. Open an event and navigate to the 'Event Participants' page;
2. Click 'Export' and from the dropdown select 'Custom Export';
3. In the pop-up click 'New Export Configuration';
4. Observe the 'General Person Data' section.

### Actual  Behavior

'National Health ID' is listed among the checkboxes for the export.

### Expected Behavior

'National Health ID' is not listed among the checkboxes for the export.

### Screenshots

![National Health ID on Event participants custom export](https://user-images.githubusercontent.com/96909231/153440860-bdacc363-e0df-4456-9b19-40ab38d829fe.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin

### Additional Information

This was observed while testing ticket #7743.

**Comment by FredrikSchaeferVitagroup** [comment]
Should be testable on every test instance configured as a german server.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.69.0-snapshot on local environment.
