### ISSUE TITLE
Users cannot edit tasks and set the status [1]

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7960]
### Problem Description

Since 1.67.1 users are not able to set the status of tasks they are not assigned to. The fields are greyed out:

![image](https://user-images.githubusercontent.com/74791118/153547914-84d43973-445f-4423-bf79-8793af10f968.png)

The users having the roles  clinician, contact supervisor and surveillance supervisor.

If the user has admin rights it is still possible to edit the task

I tested also with the role national user and national clinician but they are not editable.

It is very important that users can edit the task of others as in many health offices are used "dummy" users for teams to assign task 

### Steps to Reproduce

1. create a task and assign it to user 1
2. Open the task with user 2 and try so set it to done, removed or so.

### Proposed change

Add a featuretype property called `ALLOW_FREE_EDITING`; default: false; associated with the feature module `TASK_MANAGEMENT`
- When enabled, do not set fields to read-only based on the user roles in the task edit form

### Additional Information

This problem in production was caused by this long lasting bug https://github.com/hzi-braunschweig/SORMAS-Project/issues/7608 which was regarded by many users as regular behaviour

**Comment by Marko-ilmkreis** [comment]
@kwa20 The workaround is to assign the task to themself, they can edit it then and then re-assign the "old" user and save it.

That workaround is possible, but time consuming.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis The system works as it's supposed to (the way it worked before was actually buggy); the only users that are allowed to edit tasks are the creator and the assignee (and national users/admins).

I totally understand the need to let other users change tasks as well, but that needs to go through a change request to add an according configuration, including details on which users should be allowed to change which tasks specifically.

**Comment by kwa20** [comment]
@Marko-ilmkreis @MateStrysewske will be specified here

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske we use the dummy-users since at least one year, so the bug was very long active. I hope for a fast solution. In my opinion it is not a problem if every user can edit every task if he/she has access to the entity the task belong to.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis It is a problem in other countries using SORMAS, which is why we need to find a solution here that works for all users.

**Comment by kwa20** [comment]
I added a proposed change for this problem in the initial description which should make it possible to edit task for any user that has access to it (i.e. see it according to their jurisdiction)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.69.0-snapshot on local environment.
Users with the same role can see and edit the tasks. 
Related to other users who are not able to see the tasks, there has been created a new ticket : #7874
