### ISSUE TITLE
Create an automatic test that checks if api-changes were made and the MinimumRequiredVersion for the android-app is set correctly

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#7965]
### Problem Description

We often stumble over the issue that the MinimumRequiredVersion in the InfoProvider class is not raised, although api-changes have been made. The procedure for this is actually sufficiently described in the development guide. However, we still have problems with the mobile app because of this.

### Proposed Solution

Create an automatic test that checks if api-changes were made in the pull request and if the MinimumRequiredVersion in InfoProvider is set correctly

**Comment by StefanKock** [comment]
There is currently no idea how to do such test of comparing to versions of the backend and inspect the android-app if changes are relevant.
Checking the MinimumRequiredVersion is already part of the release process.
