### ISSUE TITLE
Synchronization possibly not done on app start/when entering lists

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#797]
@MartinWahnschaffeSymeda Try to create a new case in the web app, start the app and see if the case appears without manually synchronizing. Same after editing a case, saving it and returning to the case list.

**Comment by MartinWahnschaffeSymeda** [comment]
This is actually by design. Sync is done in background every 10 minutes and manually whenever the user feels the need. Removing the initital sync speeds up the app startup.
