### ISSUE TITLE
[Persons] System crashes when Hospital Informant clicks on the 'Contact' tab in the 'Persons' directory

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#7975]
### Bug Description
The Hospital Informant doesn't have a 'Contacts' directory, so he shouldn't have a 'Contact' filter tab it the 'Persons' directory either. However, this is present and when the user click on 'Contact' the system crashes.

The system crashes and the error message appears also when the hospital informant user clicks on the 'All'
 filter or when the user clicks on the 'Persons' directory.

### Steps to Reproduce

1. Log in with a Hospital Informant user.
2. Open the 'Persons' directory
3. Click on the 'Contact' filter tab.

### Actual Behavior
The system crashes.

### Expected Behavior
The "Contact" filter should not be shown for users without the CONTACTS_VIEW user right.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/153625761-e3aacc90-9920-446f-b154-5837fc219d9f.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local server and test-de1.sormas.netzlink.com
* User Role: Hospital Informant

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS 1.70.0-SNAPSHOT(cc0c975).

The 'Contact' quick filter has been removed from the 'Persons' directory for users that do not have the user role of contact_view. The error message from the flow described in the 'steps to reproduce' no longer appears.

The error message is still reproducible when the user tries to filter via the 'All' quick filter, but a separate issue has already been logged for this #8288
