### ISSUE TITLE
Update dependencies (v1.69.0)

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#7978]
### Proposed Change

1. Update the following dependencies:
- bouncycastle
- commons-compress
- commons-io
- commons-lang3
- docx4j
- etcd-java
  - io.grpc*
  - io.netty*
- freemarker
- google-http-client
- google-http-client-gson
- google-oauth-client
- gt-shapefile
- guava
- hibernate-core
- hibernate-types-52
- httpcore
- joda-time
- json-path
- jsoup
- libphonenumber
- logback
- opencsv
- postgresql
- slf4j
- vaadin
- xdocreport 
  - velocity 1.x to 2.x

2. Update the following test dependencies:
- h2database
- ~hamcrest~ Split out
- junit
- mockito

3. Check dependencies if obsolete/removable:
- commons-lang
- freemarker (what for used)

### Possible Alternatives

Move dependency updates to dedicated tickets if significant code incompatibilies or breanking changes in behaviour show up.

### Additional Information

Automated reporting can be done with `mvn versions:display-dependency-updates` on `sormas-base`, but contains several false positives or major updates.

**Comment by JonasCir** [comment]
Can we add https://github.com/hzi-braunschweig/SORMAS-Project/issues/7872 to this? Then we can finally get rid of Jcenter

**Comment by StefanKock** [comment]
> Can we add #7872 to this? Then we can finally get rid of Jcenter
No, it will not be part of it (as other more complicated updates as well), and because it's a replacement it's good to keep it separate.

**Comment by StefanKock** [comment]
Current status: Three branches for dependency updates that I identified to be included in this ticket:

1. [test dependencies](https://github.com/hzi-braunschweig/SORMAS-Project/pull/7984)
    - Fails on my DEV instance, but not in Github
2. [several dependencies](https://github.com/hzi-braunschweig/SORMAS-Project/pull/7991)
    - templates for text based files fails (`xdocreport`, `velocity`)
3. [h2database](https://github.com/hzi-braunschweig/SORMAS-Project/tree/feature-7978-update-h2database)
    - Incompatibilities in tests to be fixed.

**Comment by syntakker** [comment]
@StefanKock `freemarker` is one of two template engines that can be used in `xdocreport`. Since we use the apache `velocity` template and `freemarker` is not used anywhere else, I assume the dependency can be removed (both in (`sormas-base/pom.xml` and `sormas-backend/pom.xml`)

I checked locally, build is successful with the dempendency removed.

**Comment by StefanKock** [comment]
I found that `org.apache.xmlgraphics` (used by `docx4j`) needs an update.
