### ISSUE TITLE
Clarify how to deal with empty values specified in sormas.properties

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#7981]
### Problem Description

Some server specific properties can be specified via the sormas.properties. It is possible to set default values in the code that are used when the property is not specified there. 

Some of those properties are boolean values. for which this all works fine. There is just one edge case that caused trouble in production environments recently. One can set the property to an empty value, which is interpreted as false. Is this the intended behaviour?

Example:

`#interface.patientdiary.acceptPhoneContact` results in default value (true)
`interface.patientdiary.acceptPhoneContact=true` is parsed as true 
`interface.patientdiary.acceptPhoneContact=false` is parsed as false
but
`interface.patientdiary.acceptPhoneContact` is parsed as false. Should it be like that?

### Proposed Solution

TBD

**Comment by fhauptmann** [comment]
I strongly support this issue. 
Empty values for properties should be treated as not existing rather then interpreting the empty string as another then the default value. 
Background: When automating the operations of SORMAS e.g. by passing values for properties as environment variables to a docker container, logic would have to test each environment paramter it it is empty or not and how to treat empty values. The easiest way to substitute values in the properties by an environment value is this: 
`echo -e "\ninterface.patientdiary.acceptPhoneContact=${PD_ACCEPTPHONECONTACT}" >>${DOMAIN_DIR}/sormas.properties`
When PD_ACCEPTPHONECONTACT is not set or empty this leads to this line in sormaas.properties: 
`interface.patientdiary.acceptPhoneContact=`
what is interpreted as 
`interface.patientdiary.acceptPhoneContact=false`
To overcome this behaviour we need this statement to set property in sormas.properties: 
`if [ ! -z "$PD_ACCEPTPHONECONTACT" ] && ([ "$PD_ACCEPTPHONECONTACT" == "true" ] || [ "$PD_ACCEPTPHONECONTACT" == "True" ]);then
echo -e "\ninterface.patientdiary.acceptPhoneContact=${PD_ACCEPTPHONECONTACT}" >>${DOMAIN_DIR}/sormas.properties
fi`

That would lead to reproduce the logic to set properties in scripting for every property. This duplication of logic makes the whole process very error prone.

**Comment by FredrikSchaeferVitagroup** [comment]
> I strongly support this issue. Empty values for properties should be treated as not existing rather then interpreting the empty string as another then the default value. 

There are also reasons against doing this. Parsing anything that does not fit `"true".equalsIgnoreCase(...)` as false is a widely used standard in java. This is defined in the so in the [Boolean](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#parseBoolean(java.lang.String)) class.

Furthermore, changing this behaviour will affect every SORMAS instance (not just the german ones rolled out by netzlink). While this can be beneficial for netzlink processes, it may be troublesome for others. Others may even rely upon empty values being interpreted as false. When we change this behaviour, such configurations will be broken without being changed. That should not happen.

**Comment by FredrikSchaeferVitagroup** [comment]
After an internal discussion, we decided not to change the behaviour of SORMAS here. In addition to the [reasons mentioned above](https://github.com/hzi-braunschweig/SORMAS-Project/issues/7981#issuecomment-1040016020), there are more speaking against it. For example, it may, for some properties, be desired to overwrite the default value with an empty value. If SORMAS always interprets empty values as default values, that would not be possible.

We will 
- [ ] add a warning comment in the sormas.properties file pointing out the behaviour of boolean properties parsing

and then close this issue.
