### ISSUE TITLE
[Custom Case Export] Duplicate 'Details' field in German systems

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#7985]
### Steps to Reproduce

1. Open the 'Cases' directory
2. Click 'Export' and from the dropdown select 'Custom Case Export'
3. In the pop-up click 'New Export Configuration'
4. Observe the 'General Person Data' section

### Expected Behavior
Details field should be displayed only once. If there are 2 details fields that need to be displayed, a differentiation between the two fields needs to be made. 

### Actual Behavior
Details is displayed twice and the user has no information about what the two fields refer to.

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/153857750-1ad469a8-792e-4604-bfc1-92e335af6cdb.png)

### System Details
* Device:
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser:
* Server URL: German Environment or test-de environments
* User Role: NatUser

**Comment by AndyBakcsy-she** [comment]
There is another duplicated field "Sequelae" displayed under Additional Data

**Comment by valentinmikleuvg** [comment]
There are no fields with the same name and I verified if the field with similar name in UI are saved differently in DB. The bug does not reproduce anymore.
