### ISSUE TITLE
['Create new sample' form] Hide specific enum values based on the related disease

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#7986]
### Bug Description

The following values should be hidden in the 'Create new sample' form, in the checkbox section of 'Request pathogen tests to be performed?', and when processing Lab Messages, in the 'Add Pathogen Test' section, from the 'Type of Test' dropdown, when the selected disease is COVID-19:

- [ ] Incubation time
- [ ] Indirect Fluorescent Antibody (IFA)
- [ ] Direct Fluorescent Antibody (FA)
- [ ] Microscopy
- [ ] Gram Stain
- [ ] Latex Agglutination

### Steps to Reproduce 

1. Create or open an existing entity that has the disease set as COVID-19;
2. Click 'New Sample' on the 'Samples' card;
3. Mark as checked the checkbox 'Request pathogen tests to be performed?';
4. Observe the values listed for the checkboxes that appear below.

Additional Steps to reproduce specific for processing Lab Messages:
1. Open an unprocessed Lab Message;
2. From the 'Pick or create person' form select 'Create new person';
3. From the 'Pick or create entry' form select any of 'Create new case', 'Create new contact', 'Create new event participant';
4. Fill in with the required data the 'Crete new entity' form that opens based on the selection from step 3 and click 'Save';
5. In the 'Add pathogen test' section, set the 'Tested Disease' as COVID-19;
6. Observe the values listed in the 'Type of Test' dropdown.
 
### Actual Behavior

Checkbox values for 'Incubation time', 'Indirect Fluorescent Antibody (IFA)', 'Direct Fluorescent Antibody (FA)', 'Microscopy', 'Gram Stain' and 'Latex Agglutination' are listed among the pathogen test types.

Values for 'Incubation time', 'Indirect Fluorescent Antibody (IFA)', 'Direct Fluorescent Antibody (FA)', 'Microscopy', 'Gram Stain' and 'Latex Agglutination' are listed in the 'Type of Test' dropdown.

### Expected Behavior

Only display checkboxes for the pathogen test types that are actually enabled for the sample's disease (both in create and edit forms).

Only display values for the pathogen test types in the 'Type of Test' dropdown that are actually enabled for the sample's disease (both in create and edit forms).

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/153866788-61b4f663-9a18-419d-a796-05bb3977d894.png)

![image](https://user-images.githubusercontent.com/96909231/154048685-e9205d7e-63e3-4efb-ac4d-ead2848b111e.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT, ..., 1.65.0
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

Note 1: These values were requested to be hidden for 'Pathogen Test Type' in ticket #6855.

Note 2: For the 'Type of test' dropdown when processing Lab Messages: 
- the values that should be hidden seem to appear only when processing lab messages that have the tested disease already determined as COVID-19 (if the user then goes and deselects COVID-19 and selects it again, the values are hidden);
- for lab messages that do not have the disease determined - the values do not appear;
- this happens on test de-2 where the only disease in the configuration is COVID-19.

**Comment by bernardsilenou** [comment]
Just to mention that this implementation and https://github.com/hzi-braunschweig/SORMAS-Project/issues/6855 can be added in the documentation for specifying a new disease in SORMAS.

**Comment by abrudanancuta** [comment]
Validated on local environment with the version 1.70.0-snapshot(https://github.com/hzi-braunschweig/SORMAS-Project/commit/20a2e7cf1e955fdd397b5541a1385c583e3e83f6)
