### ISSUE TITLE
Event participant duplicates can be created through lab message processing

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#7992]
### Bug Description

When selecting an existing person as an event participant to an event that they already ahve an event participant created for, a duplicate is created.
### Steps to Reproduce

1. Create an event and add a person as an event participant
2. Go to the lab message directory and process a lab message for an event participant
3. In the event selection pop-up, seect the previously created event
4. In the processing form, search the person that was previously created as the event participant person and select them
5. Process the lab message fully and open the event participant
6. Check the event participant list for a duplicate participant for the same person. Alternatively, check the person form and the linked events

### Expected Behavior

It should not be possible to create a duplicate event participant. If a person was selected that already has an event participant in the selected event, this participant should get the lab message processed.
### Screenshots

![epDuplicateLabMessage2](https://user-images.githubusercontent.com/70317594/153901073-657adc64-8b08-4e7a-ad58-4aa4f95aa05c.PNG)
![epDuplicateLabMessage](https://user-images.githubusercontent.com/70317594/153901078-dcfa2f2e-2508-43c8-aad1-af956ee16220.PNG)

### System Details

* Device:
* SORMAS version: 1.69.0-SNAPSHOT / 1.68.0
* Android version/Browser: chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by ChristopherRiedel** [comment]
Is covered by #8013
