### ISSUE TITLE
[Angular][SPIKE] Understand how the Epi-curve displays multiple dates [2] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#7999]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP041vq
- Reference 2: https://test-de2.sormas.netzlink.com/sormas-ui/#!dashboard/contacts
- Reference 3 (Charts): https://echarts.apache.org/examples/en/index.html
- We need to understand how multiple dates (large intervals) are displayed in the graph and we need to figure out the "algorithm" behind it. The investigation should be done on the https://test-de2.sormas.netzlink.com/ instance by selecting a large amount of data.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by constantincrismaruvitagroup** [comment]
I investigated how Echarts it's working, and how it's need to be configured to display Stacked Bars.
Based on a list of data on xAxis and on a list of Series, the chart it's automatically adjusts bar size and can handle multiple values.
I used also some mock data for this, everything it worked well.

**Comment by danielrus** [comment]
All the days are always displayed, regardless of the period the user selected. I tested this by starting with a period of 1 month (grouping by day) and went up to 2 years. More days to display means the bars in the histogram shrink to the level of being just a simple line, thus being hard to spot when crammed together.

Only the labels are shown based on the available space (e.g.: for 1 month all the labels are displayed, for 2 they skip a day.. for 2 years it's basically a day per month). For the default view it seems displayed labels are capped to 28 max, with the total doubling on the full view.

The count for each bar in the histogram are shown based on the available space, in the sense they are crammed together up to the point when they almost overlap; this is where some are no longer displayed. My best guess this is fully controlled by the chart library, so it's not an implemented logic per se.
