### ISSUE TITLE
[Angular] Dashboard Contacts - "dashboard-contact-graph" sub-section [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8001]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.
- We need to make use of the histogram display on the graph (remove spaces between bars)

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP041vq

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
