### ISSUE TITLE
[Angular] Cases: Detailed View baseline structure [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8006]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/jgjR3v7
- Reference 2: https://test-de2.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE&followUpVisitsInterval=14
- We need to include all of the columns from the current Sormas
- Note: Basically it is the same table as on the standard view, but with more columns.

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by richardbartha** [comment]
Missing columns:
COMPLETENESS, VACCINATION STATUS, SYMPTOM JURNAL STATUS etc,

**Comment by richardbartha** [comment]
all columns are fine now :)
