### ISSUE TITLE
[Angular] Cases - Follow-up baseline structure [8 + 2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8007]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/jgjR3v7
- https://test-de2.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE&followUpVisitsInterval=14
- Follow-up view design: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm7x5G5
- The table displays dates from a min 1 to a max 90 (dynamic)
- The legend section will be in the table footer, and sticky at the bottom of the page
- The date interval should be applied to the entire table and it can be changed for the previous / next interval, maintaining the same number of days (to a maximum of 90).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
