### ISSUE TITLE
[Angular] Contacts detailed view baseline structure [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8008]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/R1AZ7Mj
- Reference 2: https://test-de2.sormas.netzlink.com/sormas-ui/#!contacts/?includeContactsFromOtherJurisdictions=false&dateFilterOption=DATE
- Reference 3 (percentages): 
-- Color logic for percentage column:
0%-25% - #D90000 (Alert 700)
25% - 50% #FD7600 (Warning 800)
50% - 75% #FDBA1E (Warning 600)
75% - 100% #009928 (Success 700)

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
