### ISSUE TITLE
[Angular] Contacts follow-up view baseline structure [5 + 1] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8009]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/3OPd9Ya
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm7x5G5
- Dependent on https://github.com/hzi-braunschweig/SORMAS-Project/issues/8007 as most of the work would have already been done there.
- The table displays dates from a min 1 to a max 90 (dynamic)
- The legend section will be in the table footer, and sticky at the bottom of the page
- The date interval should be applied to the entire table and it can be changed for the previous / next interval, maintaining the same number of days (to a maximum of 90).

### QA Section

1. What should the QA look for (what was done)
- That the filters are present and working accordingly (The development team should fill in what filters should actually be tested upon moving the task to QA)
- Check that the table has the same columns as per the current Sormas
- Check that the date interval functionality works as expected (the date interval will be maintained whenever moving forward / backward)
2. What can the QA ignore (what was omitted)
- Please ignore the actions for for: Add new contact, Import contacts, More (the button should be present, but with no action attached to them).

### Possible Alternatives

- N/A

### Additional Information

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
