### ISSUE TITLE
Statistics: Chart series (Disease vs State/LGA for Zamfara) when generated for Cholera in the year 2018 excludes Tsafe and Zurmi LGAs 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#801]
![image](https://user-images.githubusercontent.com/35563508/46016548-fe78ef80-c0cc-11e8-92e7-a7a39bf9aaa0.png)

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Can you please add screenshots with higher resolution for the diagram and also for all applied filters?

**Comment by MateStrysewskeSym** [comment]
The source of this issue is that zero values to the left and right are cropped. This totally makes sense for dates (to avoid having a lot of empty years for example), but probably not for something like states, LGAs, diseases, etc.
