### ISSUE TITLE
[Lab messages] Duplicate detection does not get triggered when processing a lab message

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8012]
### Bug Description
When processing a lab message and filling in the information of a person that already exists, the duplicate detection is not triggered and instead, a new person is created.

This is reproducible for:
- event participants
- contacts
- cases

### Steps to Reproduce

1. Create a new Event and also create a new Event Participant.
2. Go to 'Lab Messages', pick one and click on 'Process'.
3. In the 'Pick or create person' form, select 'Create a new person'.
4. In the 'Pick or create entry' form, select 'Create a new event participant'.
5. In the 'Pick or create event' form, select the event you created in step 1.
6. In the 'Add new Event Participant' form, fill in the 'Person information' with the information used when the Event Participant in step 1 was created. 
7. Check the Person Directory and also the Event Participant page.

### Expected Behavior
A duplicate person detection should have been triggered.

### Actual Behavior
I executed the flow multiple times and each time a new person and event participant is created, because the duplicate detection is not triggered.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/154066134-a3cb8425-10c6-4dd9-a19b-c4ee5be23626.png)
![image](https://user-images.githubusercontent.com/89522688/154066978-8115879d-50de-4232-beea-a445e1c94dd0.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, National User

### Additional Information
This bug might be related to issue #8013

**Comment by FredrikSchaeferVitagroup** [comment]
On second thought, I am not so sure whether this is really a bug. 
I mean, when processing lab messages, the user goes through a person selection, and then through an entry selection, where every probable duplicate should be proposed already. So, when creating a new entry (case/contact/event participant), the user has already gone through some kind of duplicate detection. Should it really be retriggered when trying to save the entry?

Of course, it should not be possible to create two event participants for the same person and the same event. But from what I tried, SORMAS seems to prevent this as expected:
![image](https://user-images.githubusercontent.com/67001822/154412129-f23f40c7-3b0b-4cf9-9e66-e7e2232ba569.png)

So I think there may be a good reason to discard this ticket...

**Comment by FredrikSchaeferVitagroup** [comment]
We discussed this internally and concluded that the expected behaviour described above is not correct.

1. It was not specified.
2. It does not really make sense. See my [previous comment](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8012#issuecomment-1042593036). Another duplicate detection would be rather annoying here.
3. The bug report did not originate from a user, but from internal testing. The expected behaviour may not be desired.

Therefore, I am going to discard this bug report.
