### ISSUE TITLE
[Cases and Contacts] Error message 'A problem has occurred' appears when trying to merge two cases/contacts that have vaccinations

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8014]
### Bug Description

An error message 'A problem has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' appears when trying to merge 2 cases or contacts that have vaccinations associated.

### Steps to Reproduce

1. Create two new cases, with the exact same data for all the mandatory fields (when the person duplicate detection is triggered when the second case is created, select 'Create new person');
2. Add vaccinations to the 2 cases;
3. In the 'Cases' directory, click on the 'More' button and select 'Merge duplicates' from the dropdown;
4. Click 'Confirm' in the filters section on the 'Merge Duplicate Cases' page;
5. Click 'Merge' on one of the cases created at step 1;
6. In the 'Confirm Your Choice' pop-up click 'Confirm'.

### Actual Behavior

An error message appears stating: 'A problem has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' and the 2 cases are not merged.

### Expected Behavior

No error message appears and the 2 cases are merged.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/154091192-57163e02-1978-4d0e-a072-068265349877.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

If one of the cases or contacts does not have a vaccination, and the user clicks 'Merge' on it in the 'Merge Duplicate Cases'/'Merge Duplicate Contacts' page, the error message appears after they click 'Confirm' in the 'Confirm Your Choice' pop-up. 
However, if the user clicks 'Merge' on the case or contact that has the vaccination information, the merge is successful. 

Logs from reproducing the error message:
[logs for error when merging 2 cases with vaccinations.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8072309/logs.for.error.when.merging.2.cases.with.vaccinations.txt)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup using the latest version of Sormas 1.70.0-snapshot
