### ISSUE TITLE
Limited disease users can be associated to entities related to other diseases

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8017]
### Bug Description
A limited disease User (ex. Dengue Fever) can be associated to an entity with a different disease (ex. a task related to a Covid-19 Case).
This issue applies to:
- [ ] 'Assigned to' users (Tasks)
- [ ] 'Observed by' users (Tasks)
- [ ] Responsible users

### Steps to Reproduce

1. Create at least one limited disease User for a disease other than 'Covid-19'
2. Create a Case with 'Covid-19' set as 'Disease'.
3. Click on 'New Task'.
4. Inspect the 'Assigned to' dropdown in the Task form.
5. Inspect the 'Observed by' dropdown in the Task form.
6. Inspect the 'Responsible Surveillance Supervisor' dropdown on Case page.

### Actual Behavior
The limited disease users (Dengue Fever) are visible in the dropdown, even if the Case has Covid-19 as disease.

### Expected Behavior
The limited disease users should not be visible in the dropdown if they have other disease associated to them.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/154276731-e73d7eca-0cf2-44e4-83e7-16e20a5fa04c.png)

![image](https://user-images.githubusercontent.com/89522688/154231751-5cc72356-5885-4805-a154-fe5571fa22c2.png)

![image](https://user-images.githubusercontent.com/89522688/154274745-36b77d27-eecf-4471-b9a0-0a8c661c9f02.png)

![image](https://user-images.githubusercontent.com/89522688/154274973-7c7e9835-7527-4b3e-9943-41b0f069ac8a.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, National User

### Additional Information

**Comment by dinua** [comment]
@roxanamlendea , @MateStrysewske 
same behavior as here happens also in menus "Contacts, Events, Entries"

Should this be fix in this bug or should be created other bug ?

**Comment by roxanamlendea** [comment]
> @roxanamlendea , @MateStrysewske same behavior as here happens also in menus "Contacts, Events, Entries"
> 
> Should this be fix in this bug or should be created other bug ?

Yes, because the ticket also contains the labels regarding the Contacts, Events and Travel Entries.

**Comment by dinua** [comment]
when a user select an entity in bulk mode (eg cases) and there contains different diseases we can no longer do the user filtration after one disease
After a discussion with Mate and Roxana we decided :
- when the bulk contains the same disease (all of them) we display the users including the one with limited diseases for that disease
- when the bulk contains different diseases we don't display the users with limited diseases

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.70.0-SNAPSHOT(c6ff697).
