### ISSUE TITLE
Update Vaadin to version 8 (legacy mode) [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#802]
- [x] update version
- [x] solve conflicts
- [x] update add-ons
- [x] create issues to get rid of legacy components

Don't update form logic (data binding) for now.

**Comment by MartinWahnschaffeSymeda** [comment]
- no more osgi deployment
- mvn vaadin:upgrade8
- Tokenfield ​https://code.google.com/archive/p/tokenfield/source/default/source
- PopupButton: 2.6.0 -> 3.0.0 ​https://vaadin.com/directory/component/popupbutton 
- CommitDiscardWrapper: Component.setReadOnly -> <C extends Component & HasValue<?>>
- TokenField::setReadOnly : Button::setReadOnly is protected => setEnabled(!readOnly);
- Button, Embedded: setImmediate removed

**Comment by MartinWahnschaffeSymeda** [comment]
Additional things that needed to be done:

- [x] use V7 legacy fields and grid (for everything related to data binding)
- [x] make sure widgetset compiles
- [x] Replace FontAwesome with Vaadin icons
- [x] Fix horizontal/vertical layouting

For migration from Framework 7 the key references are the following sections:

- Editing Values in Fields and Binding Data to Forms, which cover the new data binding concepts that replace Property and FieldGroup.
- Showing Many Items in a Listing, which covers the new Container and Item replacement, the DataProvider, as well as the associated sorting and filtering APIs.
- And for the new selection APIs, Selecting Items.

**Comment by MartinWahnschaffeSymeda** [comment]
Issues to get rid of legacy components:

1. Lazy loading for directory views (Containers) #1012
2. Vaadin 8 data binding for forms #1026
3. Data binding for directory filters #1027

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Filters in statistics are not working correctly and have layout problems

**Comment by MateStrysewskeSym** [comment]
- [ ] Fix spacing problems in Sample form
