### ISSUE TITLE
reinfectionDetails values missing in the data dictionary 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8020]
### Bug Description

Recently, reinfection details were added to the case table https://github.com/hzi-braunschweig/SORMAS-Project/issues/7182. However, the respective values are not displayed in the data dictionary.
### Steps to Reproduce

1. Go to the info section and export the data dictionary
2. Check the case table for documentation of `reinfectionDetails` values

### Expected Behavior

Reinfection details values should be documented in the data dictionary

### System Details

* Device:
* SORMAS version: 1.67.2
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.69.0-snapshot on test-de.sormas.netzlink.com environment
