### ISSUE TITLE
[Audit|REST] Audit REST Interface and provide log of requests [5]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8021]
### Where is this specified?
Refer to section 5.3 in the logging concept document.

### Log line
A log line should contain (5.3.1):
1. HTTP verb (GET, POST, etc)
2. timestamp
3. actor: uuid and username
4. ID/Name of the called subsystem
5. Identification of the called REST resource  (path?)

### Log format
Use the same FHIR-based format/service established with #8029.

### What to log
- ~~Failed login attempts (5.3.2)~~ Will be done separately
- [x] Access to a REST resource

## Configuration
Use the log sink introduced with #8030

## Refinement Todos

- [x] Define exact mapping of log line above to FHIR AuditEvent
- [x] Define how the log is triggered (e.g. backend uses an interceptor): likely a container request filter with priority https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-rest/src/main/java/de/symeda/sormas/rest/security/oidc/S2SAuthFilter.java

**Comment by abrudanancuta** [comment]
validated on local env together with @JonasCir
