### ISSUE TITLE
[Audit|Backend] Implement FHIR AuditEvent logging service [3]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8029]
### Situation Description

For the general purpose of audit logging (#7904) we need to be able to log access to the SORMAS backend with details on what exactly has been accessed, without including sensitive data (e.g. names).

This issue is the first step. It defines how the logged data is represented and provides a service that allows to log audit events.

#### AuditEvent

For the logging output format, we are using the [FHIR R4 AuditEvent resource](https://www.hl7.org/fhir/auditevent.html#tabs-json), which is based on the IHE ATNA audit profile. FHIR is a well-known and established standard for exchange of medical related data. 

A `FHIR AuditEvent` resource has a specified [JSON representation](https://www.hl7.org/fhir/auditevent-example.json.html) which is compact and easy to digest by log processing systems like Loki or ELK.

An open source library (`hapifhir`) that provides the needed `AuditEvent` java classes is available here: [Github](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.r4) [Maven](https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/org.hl7.fhir.r4/5.6.35)

These are the most important fields in the AuditEvent class:

|Content|Description|Field in `AuditEvent` resource|
|-----|------|-------|
|Access type| Create/Read/Update/Delete/Execute| `action`
|timestamp| Timestamp of the event| `recorded`
|actor|Functional instance causing the event (e.g., user). Users should be identified with a human readable name besides using the UUID| `agent`
|Executing instance| Identifaction of the system(component) generating the audit event| `source.site`
|Executing class|Name of the executing class, including method name, parameters, and return values| `source.observer`
|Activity/Event| Description of the activity with unique reference(uuid) w.r.t. the accesses data| `entitiy`

Additional, there is the field `**type**`, which will be populated according to the following table.

| Code | System | Name | Description |
| ---- | ------ | ---- | ----------- |
| 110100 | http://dicom.nema.org/resources/ontology/DCM | Application Activity | Start, Stop |
| 110106 | http://dicom.nema.org/resources/ontology/DCM | Export | Database level export |
| 110112 | http://dicom.nema.org/resources/ontology/DCM | Query | A request for multiple entities |
| 110110 | http://dicom.nema.org/resources/ontology/DCM | Patient Record | Use for read/write/delete operations on patient related entities (case, contact, symptoms, samples, ...) |
| object | http://terminology.hl7.org/CodeSystem/audit-event-type | An Operation on other Objects | Use for read/write/delete operations on all other entities, most importantly users, infrastructure, configuration and tasks |

#### AuditLogger / Implementation

- [x] create an `AuditLogger` class following the Singleton pattern (may be changed later, e.g. provinding one logger per class, similar to what Logback does).
- [x] Use the `AuditEvent` class of `HapiFhir` [Github](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.r4) [Maven](https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/org.hl7.fhir.r4/5.6.35). Make sure to provide this as a domain library and exclude optional dependencies.
- [x] Add a private method that takes a FHIR `AuditEvent` class, serializes it to json and writes the json into the default log (using slf4j Logger, level INFO). Later this will be replaced with a different log sink mechanism (see  #8030)
- [x] Add a first `logApplicationStart` method that is called from `StartupShutdownService`. It creates an `AuditEvent` and fills the following fields:
  * `type, subtype` (110100 and 110120) - HAP FHIR does not seem to provide this, so we should create our own enums to provide the Coding
  * `action`: E
  * `recorded`: current timestamp
  * `agent`: **Discuss** Is this needed for application start? Probably not
  * `source.site:` URL of the server - **discuss* how to provide this
  * `source.type`: https://www.hl7.org/fhir/codesystem-audit-source-type.html#audit-source-type-4
- [x] Same for `logApplicationStop`

More methods for the other log types will be implemented in follow-up issues (see #8025 for complete list).

### Possible Alternatives

Use the IPF commons audit library that provided an AuditMessage and builders for the different message types: https://oehf.github.io/ipf-docs/docs/audit/

It also allows to provide a `serializationStrategy` to control how the audit event is represented. Using
the FHIR R4 JSON [serializer](https://github.com/oehf/ipf/blob/0b104be3cb4756956e2a8cb8d19d9f0f23a4792c/commons/ihe/fhir/r4/core/src/main/java/org/openehealth/ipf/commons/ihe/fhir/support/audit/marshal/FhirAuditJsonSerializationStrategy.java) from the `org.openehealth.ipf.commons.ihe.fhir.support.audit.marshal` package will provide us with the desired result.

Unfortunately the AudtiMessage does not seem to provide everything that is needed, e.g. the source data does allow us to provide the observer information needed to log the executing class and method details (https://github.com/oehf/ipf/blob/master/commons/audit/src/main/java/org/openehealth/ipf/commons/audit/model/AuditSourceIdentificationType.java).

### Additional Information

Example of a log message for type "Query":

<details>

```
{ 
  "id": "05939825-617c-4bef-b5be-eda37bc61518", 
  "type": { 
    "system": http://dicom.nema.org/resources/ontology/DCM, 
    "code": "110112", 
    "display": "Query" 
  }, 
  "action": "R", 
  "recorded": "2021-12-08T23:41:23Z", 
  "outcome": "0", 
  "agent": [ 
    { 
      "type": { 
        "coding": [ 
          { 
            "system": http://terminology.hl7.org/CodeSystem/extra-security-role-type, 
            "code": "humanuser", 
            "display": "human user" 
          } 
        ] 
      }, 
      "who": { 
        "identifier": { 
          "value": "OHALA5-VLODZTQ-GKQ7V3-FDSMINPM" 
        } 
      }, 
      "name": "Steff Surveillance", 
      "requestor": true 
    }, 
  ], 
  "source": { 
    "site": "musterstadt.sormas-oegd.de", 
    "observer": { 
      "identifier": { 
        "value": "de.symeda.sormas.api.caze.CaseFacade.getIndexList" 
      } 
    }, 
    "type": [ 
      { 
        "system": http://terminology.hl7.org/CodeSystem/security-source-type, 
        "code": "4", 
        "display": "Application Server" 
      } 
    ] 
  }, 
  "entity": [ 
    { 
      "query": "aHR0cDovL2ZoaXItZGV2LmhlYWx0aGludGVyc2VjdGlvbnMuY29tLmF1L29wZW4vRW5jb3VudGVyP3BhcnRpY2lwYW50PTEz" 
	}, 
    { 
      "what": { 

        "identifier": { 
            "value": "urn:de.sormas.symeda.api.caze.CaseIndexDto:XEWVWM-DZVFUF-KTHZII-G2EXSC3I" 
         } 
      } 
    }, 
    { 
      "what": { 
        "identifier": { 
            "value": "urn:de.sormas.symeda.api.caze.CaseIndexDto:SQF6TW-FP2RFM-4FPDS5-WZLSSI4I" 
         } 
      } 
    },    { 
      "what": { 
        "identifier": { 
            "value": "urn:de.sormas.symeda.api.caze.CaseIndexDto: RC7ITS-OEYALC-K7NV2X-CPSPKPJQ " 
         } 
      } 
    } 
  ] 
} 
```

</details>

**Comment by MartinWahnschaffe** [comment]
@JonasCir I have updated the issues. Please have a look.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup with Sormas  Version: 1.70.0-SNAPSHOT.
Windows machine -> changes into the sormas.properties file and /sormas-base/setup/audit-logback.xml file are needed. 
Correct Windows paths need to be given, for example: \\sormas-base\\setup\\audit-logback.xml
