### ISSUE TITLE
[Audit|Backend] Implement a suitable log sink for the audit log [5]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8030]
### Situation Description

#8029 implements a service for `AuditEvent` based logging. It currently logs into the default log. This needs to be separated so it can be configured individually (chapter 5.2.7) and a fallback mechanism can be used.

Logging mechanism will be based on `Logback`.

### Feature Description
Programmatically configure the `Logger` to [separate it from the existing logging mechanisms](http://logback.qos.ch/manual/loggingSeparation.html), to ideally parse a separate config file. This allows the different SORMAS users to configure the audit logging to their taste and needs.

A possible way (still needs to investigation though) is to make use of the technique described in this [post](https://dennis-xlc.gitbooks.io/the-logback-manual/content/en/chapter-3-configuration/configuration-in-logback/invoking-joranconfigurator-directly.html), where a logger instance is crated from a config file. The idea would be to create on instance of it (aka singleton), which then gets used for every call to the sink.

### Where do we write to
Netzlink requested us to only use a file based [appender](https://logback.qos.ch/manual/appenders.html). It is very likely that we need to provide a tuned version of the config file for production, therefore, it is very important to support configuration via config file.

**Comment by JonasCir** [comment]
@MartinWahnschaffe I think I found way which supports usage of a config file and prevents us from working with Java EE to much.

**Comment by mario-kuehne** [comment]
Tested locally in Docker container with Version: 1.70.0-SNAPSHOT ([37e1f64](https://github.com/hzi-braunschweig/SORMAS-Project/commits/37e1f646b27a381978cd90851ac9414cbd964bbf)) and tested together with [#8029](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8029) (`logApplicationStart `& `logApplicationStop`)

with Default Configuration:
`/opt/config/audit-logback.xml` points to file `/tmp/audit-log-sormas.log`
