### ISSUE TITLE
Travel Entries of the unpreserved case do not get merged into the preserved case after the Merge Duplicate Cases flow

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8033]
### Bug Description
The Travel Entries do no get merged into the preserved Case when the user merges two duplicate cases.
Also, after the merge, the Travel Entry of the unpreserved Case persists in the database and is visible in the Travel Entries directory and the Person (Travel Entry) directory.

### Steps to Reproduce

1. Create 2 duplicate cases.
2. Go to Epidemiological Data and create a Travel Entry for each Case.
3. Merge the Cases.
3. Go to Cases Directory -> Open the Case -> go to Epidemiological Data and inspect the Travel Entries card.
4. Go to the Travel Entries Directory and inspect the list.
5. Go to Persons Directory and inspect the Case filter tab and the Travel Entry filter tab.

### Expected Behavior
The Travel Entry of the unpreserved Case should be merged into the preserved Case.

### Actual Behavior
The Travel Entry of the unpreserved Case is not merged into the preserved Case.
After the merge, the unpreserved Case is deleted, but its associated Travel Entry remains.

### Screenshots

After the merging of the 2 cases:

![image](https://user-images.githubusercontent.com/89522688/154296884-840cd11c-8b16-4cb2-bc01-ce43a6dbfb4a.png)
![image](https://user-images.githubusercontent.com/89522688/154296935-d62e0ff1-a97c-4607-b040-9b765dee142d.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, National User

### Additional Information
The issue occurs also when Case 1 has a Travel Entry associated and it is merged into Case 2 (the preserved case) which doesn't have a Travel Entry.

**Comment by adinaflorea9** [comment]
Verified ticket on test-de3.sormas.netzlink.com, using the latest version of SORMAS 1.69.0-SNAPSHOT(11441f0). Am issue was observed while testing and it was logged in a new ticket #8229.
