### ISSUE TITLE
Converting multiple contacts or event participants suggests entries before the case incubation period

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8043]
### Bug Description

When converting either contacts or event participants to cases, the "convert multiple entities" pop-up suggests contacts and event participants before the incubation period of the case.
### Steps to Reproduce

1. Create a 2 contacts and 2 event partiipants (seperate events) for the same person
2. Set the report date ad last contact date of one contact to today and the other > two weeks in the past
3. For event participants, set the respective event report dates and event dates to today and > two weeks in the past for the other
4. Chose either the latest contact or event participant and convert them into a case
5. Check the suggested entities in the multiple conversion pop-up

### Expected Behavior

Only contacts and event participants in the incubations period of the resulting case should be suggested in the multiple conversion pop-up.

### Screenshots

Example for contacts:
Contact being converted
![ConvertMultipleWrongPeriod2](https://user-images.githubusercontent.com/70317594/154477670-cb763dc9-780a-4ab5-9b3a-cd803b899653.PNG)
Additional contact in the past
![ConvertMultipleWrongPeriod3](https://user-images.githubusercontent.com/70317594/154477683-db640474-b577-4e56-9f50-b016a452ec66.PNG)
Suggested additional conversion
![ConvertMultipleWrongPeriod](https://user-images.githubusercontent.com/70317594/154477677-ab6eb793-2ecd-401a-aab9-3b7b629e4428.PNG)

### System Details

* Device:
* SORMAS version: 1.68.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
@kwa20 
* how should the contacts and ep that fall in the IP be computed?
* Is this what you mean? Computing contact and ep that falls in the  incubation period (IP):

most relevant date of case - IP <= (earliest of (contact report date/ last contact date) <  most relevant date of case

**Comment by kwa20** [comment]
@bernardsilenou I checked the original specification in this issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/4321 and the dev specification mention a period of 30 days. I might've been confused about the incubation period which I believed to be 14 days. I'll re-test this issue.
Can you verify that 30 days is indeed the ideal period?

**Comment by bernardsilenou** [comment]
@kwa20 
I think the reason for using 30 days was because we did not want to programme the method to use the IP specified on the server instance which differ for each disease. Using 30 is a wise average value to cover all infectious diseases.
- To be more specific, then we would need to use the disease-specific IP as specified on the server
- To me, it's not worth the effort if the 30 days logic works fine. 
- When analysing the data, we can drop all conventions that are out of the IP. It is safer to linked more contact to cases than not identifying them in the first place

**Comment by MateStrysewske** [comment]
I think 30 days was used because we need to factor in unprecise dates, i.e. we need to be a bit more graceful here. In any case, this doesn't seem like a bug to me since it apparently works as expected; anything else would be subject to a change request. Gonna close this issue therefore.
