### ISSUE TITLE
[Data Protection Dictionary] - The DPD should only contain fields and entities that are used in the instance from where it's generated [3]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#8046]
### Situation Description
Currently the DPD contains the colums for "exclusive countries" and "ignored countries".
As the not used fields do not need to have a legal basis or a purpose of use, they do not have to be included in the data protection dictionary.

### Feature Description
When generating the data protection dictionary for every field we need to check  the "exclusive countries" and "ignored countries".

- [x] If the locale setting (value like "de") is set in "exclusive countries"  of this instance then it will be included in the data protection dictionary. 
- [x] If the locale setting is neither in "exclusive countries" nor in "ignored countries" then it should be included in the data protection dictionary. 
- [x] If the locale setting is set in "ignored countries" then it should be not included in the data protection dictionary. 
- [x] If the disease is not configured for the instance, the disease corresponding fields should not be shown. (i.e. values that are not linked to Covid-19 should be hidden for task type, sample material, exposure type, pathogen test type and symptoms
[like Symptoms.bloodInStool is not linked to Covid19]; the sheets of the DPD where the values should be hidden are: Samples, Pathogen test, Task, Exposures, Lab messages, Test report)
- [x] In the generated Excel the 2 colums "exclusive countries" and "ignored countries" can be removed.
- [x] Note that this also goes for the available values of enums, which also use the annotations.

**Comment by kwa20** [comment]
@markusmann-vg Could we discuss this again maybe? In a recent conversation with data security team members, the point of transparency was raised. Specifically, that anything in the datamodel might need to be available but it just needs to be clear under which conditions fields are either applicable for data protection or can be disregarded. I would lie to clarify this and see if we can potentially reduce the workload because of it

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local environment using the latest Sormas version 1.70.0-snapshot.

**Comment by dbe21** [comment]
The data protection feature seems to be deactivated on the current nightly builds test-de1/2/3. As we are testing right now, it would be nice if you could activate it.
