### ISSUE TITLE
When creating 2 Duplicate Cases / Contacts via Line Listing, only one is visible in the Case Directory, the other one becomes visible only after a refresh

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8051]
### Bug Description
When the user creates 2 Duplicate Cases / Contacts via Line Listing, after the Duplicate Detection pop-up, only one Case / Contact is visible in the directory. Both Cases / Contacts are actually created, but the second one is visible in the directory only after a refresh.

### Steps to Reproduce

1. Create 2 Duplicate Cases via Line Listing.
2. In the Duplicate Detection pop-up, choose 'Create a new person' and Save.
3. Observe the Case Directory.

### Actual Behavior
After Save, only one Case is visible in the Case Directory. The other one appears only after a refresh.

### Expected Behavior
Both Cases should be visible in the Case Directory right after the Save

### Screenshots
![line listing](https://user-images.githubusercontent.com/89522688/154651010-9452d2f7-a1e7-4374-b534-0c2bdbcfc99b.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, National User

### Additional Information
When creating 4 different cases (not duplicates) via Line Listing, everything works fine. The problem occurs only after the duplicate detection is triggered.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS 1.70.0-SNAPSHO(231d303) from the development branch.
