### ISSUE TITLE
'Death Place Type' field cannot get cleared by the user

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8054]
### Bug Description
On the 'Person Page', the 'Death Place Type' field is prefilled with the 'Other' value and it cannot get cleared by the user.

### Steps to Reproduce

1. Open a Person page.
2. Set the 'Present condition of person' to Buried'
3. Try to clear the 'Death place type' field.

### Actual Behavior
The user is not able to clear the value of the field.

### Expected Behavior
The user should be able to clear the value of the field. Don't automatically fill the death place type with "OTHER" if the present condition is dead or buried and the death place type field is empty.

### Screenshots
![death place type field](https://user-images.githubusercontent.com/89522688/154667291-2bef845e-c6d7-47cb-a8f9-4b6426d0e7c5.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Admin, National User

### Additional Information
Notes: 
1. On the mobile app, both 'Death place type' and 'Cause of death' fields are not prefilled with values.
2. After a discussion with @MateStrysewske it was decided that the fact that the 'Death Place Type' field is prefilled with the 'Other' value, needs to be discussed.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS 1.69.0-SNAPSHOT(6033101) from the development branch.
