### ISSUE TITLE
New release error display on configuration tab

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#806]
@MartinWahnschaffeSymeda when you click regions, districts, community and click on health facilities, there is the error below.
![image](https://user-images.githubusercontent.com/19344651/46081936-140a1a00-c19e-11e8-9d30-796b297e5a8a.png)

**Comment by hzi-braunschweig** [comment]
health facility and lab tabs do not work!

**Comment by MartinWahnschaffeSymeda** [comment]
In FacilitiesGrid the container is temporarily replaced with an empty container (to improve performance). This container does not have an edit column and thus crashes when used as admin, causing the error:

> SormasErrorHandler - Found at least one column in Grid that does not exist in the given container: edit with the header "Edit". Call removeAllColumns() before setContainerDataSource() if you want to reconfigure the columns based on the new container." to [support.sormas@helpdesk.symeda.de]

- [ ] don't replace container - just remove items and add new items
