### ISSUE TITLE
Page cannot be saved if 'Investigation Pending' is selected and a future date was previously selected for 'Discarded' or 'Done'

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8060]
### Bug Description
The user cannot save the page if the current 'Investigation Status' is set to 'Pending', and a future date was previously set for 'Done' or 'Discarded', although the date field is currently hidden.
The behaviour is reproducible for Cases and Events

### Steps to Reproduce

1. Open a Case.
2. Set the 'Investigation Status' to 'Done' or 'Discarded'.
3. Set a date in the future.
4. Set the 'Investigation Status' to 'Pending'

### Actual Behavior
The 'Date of Investigation' is hidden, but the user is not able to save the page and a warning message appears.

### Expected Behavior
The 'Date of Investigation' should be hidden and the user should be able to save the page.

### Screenshots
![investigation](https://user-images.githubusercontent.com/89522688/154706752-24d06f29-0016-4527-b229-57ebca36fade.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0
* Android version/Browser: Chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: Admin, National User

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS 1.69.0-SNAPSHOT from the development branch.
