### ISSUE TITLE
Version 1.5.0 release automatic classfication not working

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#807]
@MartinWahnschaffeSymeda @MateStrysewskeSym I have tried to take a case through a suspect scenario and it didnt change from not yet classified to suspect. i did this for Ebola. I followed the case rules and it didnt work. Also please know that date of investiagtion does not hold any data. Once you put a date, and save, it dissappears. I reproduced this several times. 

![image](https://user-images.githubusercontent.com/19344651/46086482-7831db80-c1a8-11e8-81fe-f41082c5ee72.png)

**Comment by hzi-braunschweig** [comment]
Ok for date of investigation, instead of returning a blank field when investigation status is still pending, please display an error pop up or validation screen. I just changed the status to investigation done and the date of investigation stayed.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig The case classification is working as intended, but the case you worked on hasn't met the criteria required to classify it as suspect.
