### ISSUE TITLE
Hide country specific fields in the 'Pick or create person' form of the duplicate detection pop-up, in German and French systems

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8079]
### Feature Description

The 'Pick or create person' form of the duplicate detection pop-up contains a list of values that are considered for the duplicate detection to be triggered. 

Among the values listed there are 'Nickname', 'Passport Number', 'National Health Id'.
![image](https://user-images.githubusercontent.com/96909231/154979695-8cbb2373-5d22-47f0-9b19-2b2d87f6146a.png)

### Problem Description

The values 'Nickname', 'Passport Number', 'National Health Id' are listed on 'Pick or create person' forms on German systems.

The value 'Passport Number' is listed on 'Pick or create person' forms on French systems.

### Proposed Change

For German systems, the values 'Nickname', 'Passport Number', 'National Health Id' should be hidden.

For French systems, the value 'Passport Number' should be hidden.

### Additional Information

This proposed change is linked to the #7476  change request and is similar to #7815.

**Comment by markusmann-vg** [comment]
It's a bug, because implementation did not consider that scenario. For the future we will have to implement a generic approach that allows us to use the annotation to hide fields everywhere where they are used.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS 1.69.0-SNAPSHOT(18880b1) from the development branch for the DE systems; and @AndyBakcsy-she for FR systems.
