### ISSUE TITLE
Geo coordinates in home address trigger unsaved changes prompt twice without having made changes

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8089]
### Bug Description

When geo coordinates are entered in the persons home address, the unsaved changes prompt gets triggered even though no changes have been made. It even gets triggered twice. It only seems to happen when a facility is referenced in the address
### Steps to Reproduce

1. Create e.g. a case and enter a home address for the person
2. Reference a facility and adopt the address in the additional fields
3. Generate geo coordinates for this address and save the person form
4. Try navigating out of the person form
5. As a control, remove the geo coordinates and save the form
6. Navigate out of the form again

### Expected Behavior

Navigation should happen immediately since no more changes have been made after the form has been saved.

### Screenshots

![saveChangesPrompt](https://user-images.githubusercontent.com/70317594/155104763-5ef273a3-e781-4eea-9d64-8c02ca7819f9.PNG)

### System Details

* Device:
* SORMAS version: 1.68.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

This happens in the person form as well as person tabs in entities.

The message also becomes immediately triggered when a user adds a participant to an event and selects an existing person with the respective data entered.

**Comment by kwa20** [comment]
while testing on test1402.sormas.netzlink.com (1.68.3) I also noticed that when a user opens a case that has a facility and geo cordinates antered in the home address, a double click will navigate to the person form in the background and trigger the unsaved changes prompt. Pressing discard or save will navigate to the case.

![unsavedChangesNavigation](https://user-images.githubusercontent.com/70317594/156643659-c944911d-62aa-4b53-8d94-a2079cba3e7f.gif)

Pressing Cancel navigation will leave the user on the person form.

![unsavedChangesPrompt2](https://user-images.githubusercontent.com/70317594/156643679-76457294-5fb8-499f-bb07-0ce11859fae0.gif)

None of this should happen. Instead, a double click on the case list row should merely open the case.

**Comment by sergiupacurariu** [comment]
@kwa20 Tested both with the browser language and Sormas system set to English or German in different combinations and none of them triggered the above-described situation. Could you retest this bug to see if it is still reproducible? Thanks.

**Comment by JaquM-HZI** [comment]
@kwa20 and @KernB is this still a bug?

**Comment by kwa20** [comment]
I tested this bug again on test1401.sormas.netzlink.com (1.75.4) and could not reproduce it. I will therefore discard this issue.
