### ISSUE TITLE
Update disease variant prompt navigates to case when only save was selected

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8090]
### Bug Description

When a user processes a lab message and selects `SAVE` at the end of creating the sample and pathogen test, they're asked to update the disease variant if it differs in the created pathogen test compared to the case. When the user selects an available option and gets redirected to the case. However, since they previously only selected `SAVE` but not `SAVE AND OPEN CASE`, they should stay in the lab messages directory.

This produces a lot more navigation efforts in order to keep processing messages and minimizes efficiency of users.
### Steps to Reproduce

1. Process a lab message for an existing case where the disease variant in the existing case differs from the tested disease variant in the pathogen test (e.g. through sequencing)
2. When finishing the processing, select SAVE in the last side by side view
3. Select any option in the update disease variant pop-up

### Expected Behavior

- When the user presses `SAVE`, they should get redirected to the lab messages directory independent of the update disease variant pop-up
- When the user presses `SAVE AND OPEN CASE`, they should get redirected to the respective case

### Screenshots

![labMessageProcessSaveCaseDiseaseVariantUpdate](https://user-images.githubusercontent.com/70317594/155131864-3d506896-b69f-4a56-a47a-706519c4cba0.PNG)

![labMessageProcessSaveCaseDiseaseVariantUpdate2](https://user-images.githubusercontent.com/70317594/155131815-0ec8baf8-6d30-46f8-961e-c22accc08cc1.PNG)

### System Details

* Device:
* SORMAS version: 1.68.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national ser

**Comment by abrudanancuta** [comment]
Validated on the local env with the version 1.69.0-snapshot(f42cb7c)
