### ISSUE TITLE
The logic of date chronology for "stay in intensive care unit" is reversed.

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#8094]
### Bug Description
The date for start of  stay in intensive care unit should be before or the same as date of end of stay.
Entering dates with this logic provokes an error alert and does not allow saving.

### Steps to Reproduce

1. Open a hospitalised case and set stay in intensive care unit to "yes"
2. Enter a date for start of stay in intensive care unit within the admission and discharge/transfer period
3. Enter a date for end of stay at least one day after start of stay in tensive care unit (but also within the admission and discharge/transfer period)
### Expected Behavior

An error alert will be provoked.
### Screenshots
![Screenshot_20220219-154821_APMIS](https://user-images.githubusercontent.com/71414361/155219174-313863eb-5b44-4088-ab24-f232c4b26a85.jpg)
### System Details

* Device: Android
* SORMAS version: 1.68.0 
* Android version/Browser: Version 11 (knox 3.7, API level 33)
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: Surveillance officer & Contact officer* Device:

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.69.0-snapshot (f42cb7c)
