### ISSUE TITLE
[Data Protection Dictionary] The Excel worksheets of the data protection Dictionary should show the technical entity names [0.5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#8097]
### Situation Description
Currently the names of the worksheet are translated, this means that for example the entity is casedata the worksheet is named case. For the data protection officers it would be helpful and less confusing when the worksheets and the technical entity name is equal

### Feature Description
When a data protection dictionary is exported, then all worksheets that contain information about the dto should have the entity name as shown in the attached picture.
<img width="911" alt="dpd" src="https://user-images.githubusercontent.com/62540178/155276532-acca8be1-0ee1-4faf-921a-c791f60a7e22.png">

**Comment by mario-kuehne** [comment]
Hint 1 for testability on (test-) instances: xlsx document has to be put in sormas/custom path in domain (see https://github.com/hzi-braunschweig/SORMAS-Project/issues/7679)

Without, it is not possible to download Data Protection Dictionary as User with Role Admin.

![image](https://user-images.githubusercontent.com/95228108/158948826-5dda8e09-f496-4e5c-ba0e-52acf320ea53.png)

Hint 2 for operations team: add automation for putting xlsx document into sormas/custom path in domain
