### ISSUE TITLE
Selecting existing persons during case creation results in errors

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8098]
### Bug Description

When selecting existing persons during the case creation process, errors occur due to entries in the home address. Additionally, the update location prompt is triggered (twice even) when a person with a home address in a facility is selected. The home address section in the case creation form gets filled incorrectly or not filled according to the persons home address which results in an error.
### Steps to Reproduce

1. Prepare by creating a person which has a home address in a facility
2. Go to the case directory and create a new case
3. In the creation form, search for the person that was prepared and select it
4. Select any option in the location pop-ups
5. Remove the person
6. Search the same person again and select it
7. Save the new case

### Expected Behavior

- The location update pop-up should not get triggered because selecting an existing person should make no chnages to the home address that was previously entered already
- The home address section should not produce an error when saving the case. The address field should be correctly displayed but merely for visual information since no person data is actually changed here when an existing person has been selected

### Screenshots

![personSearchCaseError](https://user-images.githubusercontent.com/70317594/155284883-d61e736a-77c9-4b0d-b98a-e5b8b9e2e59a.PNG)
![personSearchCaseError2](https://user-images.githubusercontent.com/70317594/155284891-7348454e-39d4-49c9-a6cb-2abfc3f6f156.PNG)

![personSearchCaseError3](https://user-images.githubusercontent.com/70317594/155284900-5dea6187-36cd-4e50-aa4d-193a9445ce76.PNG)

### System Details

* Device:
* SORMAS version: 1.68.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user, Supervisors, Officers

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and test-de2.sormas.netzlink.com, using the latest version of SORMAS 1.69.0-SNAPSHOT(https://github.com/hzi-braunschweig/SORMAS-Project/commit/7461f749eb410bf997f8e1255eab9230b984dd18) from the development branch.

The behavior was still observed for 'Lab messages' - Create new case; and this has been documented in a new bug report.
