### ISSUE TITLE
Users with jurisdiction restriction can search and select persons they should not have access to

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8102]
### Bug Description

Users with jurisdictional restrictions and search, read and select persons that they should not have access to. Subsequently, creating entities for them fails with an error.
### Steps to Reproduce

1. Log in with a restricted user (e.g. surveillance officer, contact officer, community officer)
2. Go to e.g. cases and create a new case
3. Search for a person in the form and specifically search a person outside of your jurisdiction
4. Select the person
5. Complete the form and try to save
6. Search the person that was previously selected also on the person directory

### Expected Behavior

The restricted user should not find the respective persons that they don't have access to in the search person option. This should prevent them from viewing and selecting them.

### Screenshots

![personSearchCommOff](https://user-images.githubusercontent.com/70317594/155307730-af8a478f-7696-4172-87a7-f89f655525b8.PNG)

![personSearchCommOff2](https://user-images.githubusercontent.com/70317594/155307740-42ebf5cb-64e3-468f-9d7f-485dc94b9c52.PNG)

![personSearchCommOff3](https://user-images.githubusercontent.com/70317594/155307749-2c785bc9-4ef0-48cd-b345-20070377f77f.PNG)

### System Details

* Device:
* SORMAS version: 1.68.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance Officer + Contact Officer, Community Officer

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS 1.69.0-SNAPSHOT(75eda6b) from the development branch.
