### ISSUE TITLE
[Cases - Symptoms Tab] Page can not be saved if a future date is set for 'Date of symptom onset'

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8111]
### Bug Description

In the 'Symptoms' tab, the page can not be saved, if there are no symptoms checked, but previously a future date was set for 'Date of symptom onset'.

### Steps to Reproduce

1. Navigate to the 'Symptoms' tab of a case;
2. Select 'Yes' for one of the symptoms;
3. From the 'First symptom' dropdown that became editable after step 2, select the visible symptom;
4. In the 'Date of symptom onset' field that became editable after step 2, select a date in the future;
5. Unselect the 'Yes' from step 2 (or select 'No/Unknown');
6. Click 'Save' at the bottom of the page.

### Actual Behavior

The 'First symptom' dropdown was cleared; the 'Date of symptom onset' field was not cleared and the user can not save the page.

### Expected Behavior

The 'Date of symptom onset' field should be cleared and the user should be able to save the page.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/155350989-3fafaf23-4a80-471c-9d57-6d0e16fec242.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by bernardsilenou** [comment]
`The 'First symptom' dropdown was cleared; the 'Date of symptom onset' field was not cleared and the user can not save the page.` this is because this data can also be collected on creation forms leading to many cases having onset date not all NULL for all symptoms. This is very common for linelisting cases.

**Comment by kwa20** [comment]
@bernardsilenou Is there any reason why we allow entering the symptom onset date without symptoms on creation forms but prevent entering this field on symptoms tabs without specifying a symptom as yes? The latter makes sense but makes it inconsitent and prevents easy corrections.

**Comment by bernardsilenou** [comment]
@kwa20 
`prevent entering this field on symptoms tabs without specifying a symptom as yes`
-  the current logic existed before onset date was added to the creation form
- This was just a specification that we did not consider when we added the onset date on the creation form. You are right,  it would be good to add this point you suggested,  to allow users to edit the onset date on the edit form without choosing a symptom.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.70.0-SNAPSHOT (48fad26) from the development branch.
