### ISSUE TITLE
[S2S] Responsible jurisdiction does not change when accepting a share request [2]

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#8113]
### Bug Description

When accepting a share request that changes the ownership of a case or contact the responsible jurisdiction (Responsible Region & Responsible District) stays the same as it was on the source system.
This leads to the newly created case not being visible to the user on the target system because they are only allowed to see cases and contacts that fall under their jurisdiction as well as not being able to send a case to SurvNet as the jurisdiction does not match the SurvNet user's region.

### Steps to Reproduce

1. Create a case on a S2S enabled test system, setting responsible region and responsible district to the one belonging to that system
2. Send it to another S2S enabled test system with "Hand over the ownership" set to true
3. Accept the share request on the target system
4. Observe the created case's values for "Responsible Region" and "Responsible Region"

### Expected Behavior

When accepting a share request for cases or contacts that are send as "Hand over the ownership" == true the Responsible Region and Responsible District should be automatically changed to the correct ones for the accepting system according to the server properties. The field for "Responsible Community" should be set to NULL as there is no way of finding that out automatically.
These changes also need to be synchronized back to the source system.

When accepting a case or contact with "Hand over the ownership" == false the fields should not be changed.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by leventegal-she** [comment]
This is not a bug. This behaviour was never specified and we don't have the server properties mentioned. (" changed to the correct ones for the accepting system according to the server properties")

**Comment by Jan-Boehme** [comment]
@leventegal-she
I was thinking about using "SORMAS_ORG_ID" and map that to a specific region but this would only work for germany.

To make it work internationally we probably need a new server property.

I propose introducing a property named "SORMAS2SORMAS_DISTRICT_EXTERNALID" which can be set to any string.
When a request with ownership is accepted SORMAS can use this string to read the correct district from the "districts" table and get the correct region from the foreign key saved in "districts.region_id".

**Comment by leventegal-she** [comment]
For testing locally with S2S-Testbed: 
* pull the latest changes and rebuild
* in sormas_a: `SK Flensburg` is configured
* in sormas_b: `SK Kiel` is configured
* change S2S_DISTRICT_EXTERNAL_ID in docker-compose.yml to use other districts

**Comment by mario-kuehne** [comment]
Tested locally with Version: 1.70.0-SNAPSHOT (c6ff6974430127d1976d898fc02ae351a60f186a)

- set `SORMAS_TO_SORMAS_ACCEPT_REJECT = true` for both instances A & B.
- in sormas_a: SK Flensburg is configured
- in sormas_b: SK Kiel is configured

1. A sends case with any Region/District/Community combination to B
2. B accepts the share and the case gets updated on A & B to the configured Region&District from target B (in this case `Region=Schlewig-Holstein` & `Responsible Community=SK Kiel`.
