### ISSUE TITLE
[Contacts] Date validations for 'Date of First Contact', 'Date of Last Contact' and 'Date of Report' are not triggered

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8122]
### Bug Description

Date validations for invalid date combinations between 'Date of First Contact', 'Date of Last Contact' and 'Date of Report' are not triggered when there is 1 day difference.

### Steps to Reproduce

1. Create a contact or open an existing one;
2. Set the 'Date of Report' to the 22nd of February;
3. Set the 'Date of First Contact' and 'Date of Last Contact' to the 23rd of February;
4. Save the contact.

### Actual Behavior

User is able to save the contact successfully.

### Expected Behavior

- User should not be able to save the contact successfully and a message should be displayed in a pop-up (as it happens currently for other invalid date combinations); 
- Date validations should be displayed - date fields should be highlighted in red; 
- When hovering over the date fields highlighted in red the user should see an informative note stating that 'Date of First and Last Contact have to be before or on the same day as Report date'.

### Screenshots

Screenshot of the contact saved with dates of first and last contact after the report date:
![image](https://user-images.githubusercontent.com/96909231/155525104-cbb1a8d0-bc77-4a13-9156-b04bc3632391.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

**Comment by roxanamlendea** [comment]
I verified the ticket on my local machine and I'm leaving my findings below:

- In the situation below, when hovering over the 'Date of first contact' field, the informative note is informing the user that 'Date of first contact has to be before or on the same date as Report Date', even though the 'Date of first contact' is the same as 'Report Date'.

- If the user sets the 'Date of last contact' two days after the current day (eg. 19 march), in the informative note, the 'Date of first contact has to be before or on the same date as Report Date' line gets duplicated.

- If the user sets the 'Report Date' to 17 march and the 'Date of last contact' to 18 march, the informative note informs the user only that the 'Date of last contact cannot be in the future', it doesn't also inform the user that the 'Date of first contact has to be before or on the same date as Report Date'

On 'Create new Contact' form or on the 'Line listing' form, the user can create Contacts that have the 'Date of first contact' and 'Date of last contact' set after the 'Date of Report'.

**Comment by roxanamlendea** [comment]
I verified the ticket on my local machine and I'm leaving my findings below:

- In the situation below, when hovering over the 'Date of first contact' field, the informative note is informing the user that 'Date of first contact has to be before or on the same date as Report Date', even though the 'Date of first contact' is the same as 'Report Date'.

![image](https://user-images.githubusercontent.com/89522688/158829200-2df15590-58b4-48b0-815c-03958f80b503.png)

- If the user sets the 'Date of last contact' two days after the current day (eg. 19 march), in the informative note, the 'Date of first contact has to be before or on the same date as Report Date' line gets duplicated.

![image](https://user-images.githubusercontent.com/89522688/158829035-6c648021-4eda-4568-ad78-96a1b8cef159.png)

- If the user sets the 'Report Date' to 17 march and the 'Date of last contact' to 18 march, the informative note informs the user only that the 'Date of last contact cannot be in the future', it doesn't also inform the user that the 'Date of first contact has to be before or on the same date as Report Date'

![image](https://user-images.githubusercontent.com/89522688/158829335-54048d1c-f676-49c6-b962-8bb551a8741d.png)

- On 'Create new Contact' form or on the 'Line listing' form, the user can create Contacts that have the 'Date of first contact' and 'Date of last contact' set after the 'Date of Report'.

![image](https://user-images.githubusercontent.com/89522688/158829816-bce12a2e-76b0-47ac-bedf-0c1ee1e36117.png)

**Comment by roxanamlendea** [comment]
I tested on local environment using the latest version of Sormas 1.70.0-SNAPSHOT (0063716) and I'm reopening it because on the 'Line listing' form, the user can create Contacts that have the 'Date of first contact' and 'Date of last contact' set after the 'Date of Report'.

![image](https://user-images.githubusercontent.com/89522688/159988226-f51cb52c-08cb-4c37-8b85-07752522e2be.png)

after save:
![image](https://user-images.githubusercontent.com/89522688/159988271-77068de9-a108-4004-94fb-fbf437089af4.png)

**Comment by StefanKock** [comment]
I suggest to split out the validation on the line listing feature to a separate ticket

**Comment by adinaflorea9** [comment]
The line  listing issue was reported initially in ticket #8309

**Comment by StefanKock** [comment]
@syntakker will continue to fix the line listing validation
