### ISSUE TITLE
[Events] Error message 'A problem has occurred' appears when trying to save changes made on an event

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8131]
### Bug Description

An error message 'A problem has occurred. The data could not be saved because it has been changed in the meantime' appears when trying to save the changes made on an event, via the 'Confirm navigation' pop-up.

### Steps to Reproduce

1. Open an existing event;
2. Edit some information form the event page and do not click 'Save' at the bottom of the page;
3. On the 'Event groups' card, click on 'Link new event group';
4. Select an event from the list in the form 'Pick or create event group' (or select 'New event group' and create one);
5. Click 'Save changes' in the pop-up to 'Confirm navigation' that gets triggered when saving the event group.

### Actual Behavior

An error message appears stating that 'A problem has occurred. The data could not be saved because it has been changed in the meantime'; the user is not able to save the changes made at step 2.

### Expected Behavior

No error message appears and the user is able to save the changes made at step 2 via the 'Confirm navigation pop-up'.

### Screenshots

GIF of the steps to reproduce:
![Event group](https://user-images.githubusercontent.com/96909231/155700647-f77f8e35-0c63-47ed-ac44-ab3a5374a158.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com/
* User Role: Admin, NatUser

### Additional Information

The 'Confirm navigation' pop-up could be triggered when the user clicks 'Link event group' so that the changed information from the event page gets saved before the linking the new event group.

**Comment by MateStrysewske** [comment]
Similar to #8078 (solution from there can probably also be applied here)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT (e32e36b) from the development branch.
