### ISSUE TITLE
[Angular][Backend] Create a person when creating another entity (Cases + Contacts) [3 + 2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8132]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/v8k0Jnd
- We need the BE to create a new person based on the info provided by the FE (First Name, Last Name, Sex, etc)
- The BE will handle the person creation automatically
- ! ! ! NOTE: As this might imply a structure change for a lot of DTO's, @marius2301 please discuss this aspect with @MateStrysewske or @MartinWahnschaffe  and see if this is doable (if we are allowed to make this change). See if we implement with the change of the DTO's, or the alternative being that the call for savePerson will return the ID to be used by the FE.
-! ! ! NOTE: `In the scenario where we will use the first solution (changing the DTO's this task will handle all such occurrences).
### QA Section

1. What should the QA look for (what was done)
- N/A
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by MateStrysewske** [comment]
We'll very likely need to introduce dedicated DTOs for this, because having all these details in e.g. the CaseDataDto that is also transferred to the mobile app is not a good idea in my eyes. @MartinWahnschaffe should also have a look at this though.

**Comment by MartinWahnschaffe** [comment]
Would be good to have an example use case and what this could look like. Creating a person first and then assigning the case sounds easier in the first place, but it sounds like you would prefer the other solution?

**Comment by MartinWahnschaffe** [comment]
My suggestion is as follows: For the core entities where this is currently needed (probably case and contact), go with the approach of adding a new DTO class. I'd implement this in a generic way: `CoreAndPersonDto<CaseDataDto>`

This will allow us to add a generic `save` method to the CoreFacadeEjb that takes the dto, takes care of saving the person and calling the generic save method for the core entity dto (e.g. the CaseDataDto).

In the Resource class I'd probably call it `post` and not limit it's use the creation.
