### ISSUE TITLE
[Travel entries] Error message 'A problem has occurred' appears when trying to save changes made on a travel entry

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8133]
### Bug Description

An error message 'A problem has occurred. The data could not be saved because it has been changed in the meantime' appears when trying to save the changes made on the travel entry page, via the 'Confirm navigation' pop-up.

### Steps to Reproduce

1. Open an existing travel entry that does not have a case yet;
2. Edit some information on the travel entry page and do not click 'Save' at the bottom of the page;
3. Click on 'Create case' ('Create new case' form is already populated with all the mandatory information) and click 'Save' in the form;
4. Click 'Save changes' in the pop-up to 'Confirm navigation' that gets triggered when saving the new case.

### Actual Behavior

An error message appears stating that 'A problem has occurred. The data could not be saved because it has been changed in the meantime'; the user is not able to save the changes made at step 2.

### Expected Behavior

No error message appears and the user is able to save the changes made at step 2 via the 'Confirm navigation pop-up'.

### Screenshots

GIF of the steps:
![Travel entry](https://user-images.githubusercontent.com/96909231/155702172-1a0587e4-c2c8-4322-837f-b40fcf263045.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

The 'Confirm navigation' pop-up could be triggered when the user clicks 'Create case' so that the changed information from the travel entry page gets saved before creating the new case.

**Comment by MateStrysewske** [comment]
Similar to https://github.com/hzi-braunschweig/SORMAS-Project/issues/8078 (solution from there can probably also be applied here)

**Comment by adinaflorea9** [comment]
Verified ticket on test-de2.sormas.netzlink.com, using the latest version of SORMAS 1.69.0-SNAPSHOT(18880b1).
