### ISSUE TITLE
[Angular][Backend] Cases and Contacts detailed views endpoints [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8134]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/R1AZ7Mj
- We need a dedicated endpoint which would bring all of the required data for the detailed view
- The original request that is currently used contain the extra details
- @marius2301 , please consult with @MateStrysewske or @MartinWahnschaffe and see if this is doable and it doesn't impact the current usage
- Note: This should be implemented for both Cases and Contacts (and it will also be used for the Custom-Views).

### QA Section

1. What should the QA look for (what was done)
- N/A
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by MateStrysewske** [comment]
There are dedicated DetailedIndex DTOs, so this shouldn't be a problem.
