### ISSUE TITLE
[Angular] Facilities across the board [8 + 2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8137]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://github.com/hzi-braunschweig/SORMAS-Project/issues/7586
- We will need to implement the facilities functionality across the board
- The normal flow is:
- 1. Select region (mandatory)
- 2. Select district (mandatory), dependent on region
- 3. Select responsible community (optional), dependent on district
- 4. Select Facility Category (mandatory)
- 5. Select Facility Type (mandatory), dependent on Category
- 6. Select Facility, dependent on type, district (mandatory), and community (optional)
- Note: Please check how the current implementation works as we need to replicate it.
- Note: We should try to use a "generalised" version so it can be reused.
- Note: We will have the category and type hardcoded and get the rest from the BE

### QA Section

1. What should the QA look for (what was done)
- Check that the current functionality works across the board (wherever it is used)
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- Create a specific widget for Facilities (and it should have as inputs, external of the widget, region, district, etc).

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
