### ISSUE TITLE
[Angular] 404 Page [3 + 0]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8138]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/OmrxYQR 
- We need to implement the 404 page that should be displayed for every page / route that isn't available

### QA Section

1. What should the QA look for (what was done)
- Check that the 404 page is displayed when trying to acces an invalid / corrupt route
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
