### ISSUE TITLE
Error message appears when the user clicks on the 'Search person' button

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8159]
### Bug Description

An error message stating: 'An error has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' when the user clicks on the 'Search person' button in creation forms.

This is reproducible in the following creation forms:
- [ ] Create new case;
- [ ] Create new contact;
- [ ] Create new event participant;
- [ ] Create new immunization.

### Steps to Reproduce

1. Navigate to one of the creation forms mentioned in the 'Bug description';
2. Click on the 'Search person' button that is next to the 'Last Name' field.

### Actual Behavior

An error message stating: 'An error has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' appears.

### Expected Behavior
 
No error message appears and the user is able to use the 'Search person' option.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/155994816-0fa312f6-6cbe-4b98-bdc1-2cc0c6c5dfdf.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.1 (was the version that appeared yesterday on my local machine) and 1.69.0-SNAPSHOT(f42cb7c)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Adnim, NatUser

**Comment by MateStrysewske** [comment]
@alexcaruntu-vita @adinaflorea9 This might have to be fixed in a second hotfix. Can you please check whether this also happens on the master branch? Thanks!

**Comment by adinaflorea9** [comment]
Logs of the error message:
[Logs for the error message.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8160048/Logs.for.the.error.message.txt)
