### ISSUE TITLE
Build server for automatic tests of pull requests [1]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#816]
- [x] test travis ci with forked repository (commits)
- [x] test travis ci with forked repository (pull request)
- [x] create guide/manual
- [x] add config to repository
- [x] create for SORMAS repository (Daniel)

**Comment by MartinWahnschaffeSymeda** [comment]
Pull request testing works as well. See https://github.com/MateStrysewskeSym/SORMAS-Open/pull/1

@MateStrysewskeSym I think you can add the travis config file to the main directory.

@hzi-braunschweig Can you activate travis ci for the SORMAS github repository, please?

Follow theses steps:

1. Go to Travis-ci.com and Sign up with GitHub (use the account that has full rights for the SORMAS repository)
2. Accept the Authorization of Travis CI. You’ll be redirected to GitHub.
3. Click the green Activate button, and select the repositories you want to use with Travis CI.

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda @hzi-braunschweig I've added the .travis.yml file.
