### ISSUE TITLE
Add reason for deletion to confirmation dialogue [3]

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#8162]
### Feature Description

For GDPR compliance reasons it is necessary to document why data was deleted by a user.
The confirmation popup when deleting needs to be extended to allow this.
(This applies for deleting a single entity as well as using the bulk edit mode to delete data)

### Proposed Change

Rework the popup that shows when a user is trying to delete data and add a possibility to select a reason or enter your own.

The dropdown contains the vollowing values:

|Index|de_DE|en_US|
|:-------------:|-------------|-------------|
|0|Löschen auf Anforderung der betroffenen Person nach DSGVO|Deletion request by affected person according to GDPR|
|1|Löschen auf Anforderung einer anderen Behörde|Deletion request by another authority|
|2|Entität ohne Rechtsgrund angelegt|Entity created without legal reason|
|3|Abgabe des Vorgangs wegen Nicht-Zuständigkeit|Responsibility transferred to another authority|
|4|Löschen von Doubletten|Deletion of duplicate entries|
|5|Anderer Grund|Other reason|

If the user selects "Other Reason" in the dropdown menu a new text field appears below the dropdown where a user can enter their own reason. Entering text in the field is mandatory to be able to confirm the deletion of the data.
The field counts as filled in when the length of the trimmed string is greater than 0.

If the user has not selected a value in the dropdown and tries to confirm by clicking the "Yes" button the following error message appears:
| Locale|Value|
| ------------- |-------------|
|de_DE|Bitte wählen Sie einen Grund aus.|
|en_US|Please select a reason.|

If the user has selected "Other Reason" but did not enter anything in the text field and tries to confirm by clicking the "Yes" button the following error message appears:
| Locale|Value|
| ------------- |-------------|
|de_DE|Bitte geben Sie einen Grund an.|
|en_US|Please specify the reason.|

Other localization:

| Locale|Value|
| ------------- |-------------|
|de_DE|Löschen bestätigen|
|en_US|Confirm deletion|

| Locale|Value|
| ------------- |-------------|
|de_DE|Sie sind im Begriff diese Daten löschen zu lassen.  Dieser Vorgang kann nicht rückgängig gemacht werden.|
|en_US|You are about to mark this data for deletion. This action is irreversible.|

| Locale|Value|
| ------------- |-------------|
|de_DE|Grund|
|en_US|Reason|

| Locale|Value|
| ------------- |-------------|
|de_DE|Anderer Grund|
|en_US|Other reason|

| Locale|Value|
| ------------- |-------------|
|de_DE|Möchten Sie die Daten wirklich löschen?|
|en_US|Are you sure you want to delete this data?|

| Locale|Value|
| ------------- |-------------|
|de_DE|Nein|
|en_US|No|

| Locale|Value|
| ------------- |-------------|
|de_DE|Ja|
|en_US|Yes|

- [x] Add the two new fields (enum and text) to the DeletableAdo

Additional things to do here:

- [x]  In the UI of a deleted entity, we need to display when the manually deleted entity will be automatically permanently deleted. For other deletion reference types this has already been implemented in https://github.com/hzi-braunschweig/SORMAS-Project/issues/7240
- [x]  In the UI of a deleted entity, we need to display the reason why it has been deleted (at bottom of the form)

### Additional Information

Mockup:
<img width="416" alt="2022-02-28_15h14_22" src="https://user-images.githubusercontent.com/6122778/155997875-b48a5a2b-bacc-4e0c-b887-058fac97c180.png">

**Comment by kwa20** [comment]
@Jan-Boehme @markusmann-vg Further things we should consider is how to handle the reason for bulk action deletion and deletions that are triggered manually yet differently via e.g. case merging.

For bulk actions I'd assume that we add the specified reason to all selected entities. For merging we might be able to just automatically set it as "Deletion of duplicate entries".

**Comment by MateStrysewske** [comment]
Additional things to do here:
- [ ] In the UI of a deleted entity, we need to display when the manually deleted entity will be automatically permanently deleted. For other deletion reference types this has already been implemented in #7240
- [ ] In the UI of a deleted entity, we need to display the reason why it has been deleted (at bottom of the form)

**Comment by roxanamlendea** [comment]
When 'Other reason' is selected, there's a new text field that appears below the dropdown where a user can enter their own reason. This text field is indeed mandatory, but the mandatory mark is not obvious at first glance.
I suggest that above the text field, should be a caption like 'Other reason details' or 'Details' and the mandatory mark should be moved right after the text.

Also, the text field width should match the dropdown. Currently, it is shorter.

![image](https://user-images.githubusercontent.com/89522688/168755533-673969d3-907a-4a8a-a22b-a0eb9c090413.png)

**Comment by MateStrysewske** [comment]
Follow-up refactoring issue: #9214

**Comment by roxanamlendea** [comment]
Also, if the user has not selected a value in the dropdown and tries to confirm by clicking the "Yes", the dropdown is red marked. Even after the user selects a reason, the dropdown color is not reset, it is still red. It shouldn't, because now there's a reason selected.

![image](https://user-images.githubusercontent.com/89522688/168760245-7d743505-ef38-4ddc-b8cf-b0911528f5ed.png)

**Comment by roxanamlendea** [comment]
I'm reopening the ticket again because I have found 3 other issues:

- Instead of 'Travel Entry' is just 'Travel':
![image](https://user-images.githubusercontent.com/89522688/168802758-b729f8be-557b-4f63-8f7f-08e6ef06f35c.png)

- When deleting Samples via Bulk Edit Mode, the pop-up doesn't ask the user to pick a Reason for Deletion:
![image](https://user-images.githubusercontent.com/89522688/168803145-ab7893b9-ba84-4ed2-9dd5-79475e793923.png)

- When deleting entities via Bulk Edit Mode, the 'This action can not be reversed' text is missing:
![image](https://user-images.githubusercontent.com/89522688/168803281-70cda975-c45b-4ab3-b2ad-a3186b75e26f.png)

**Comment by roxanamlendea** [comment]
Also, when selecting 'Other Reason' and filling in the text field with a >4096 character input, the deletion is done without letting the user know that the maximum length has been exceeded. 
However, in the UI of the deleted entity, there's a message that lets the user know the text is too long.
![image](https://user-images.githubusercontent.com/89522688/168817189-bb164d73-8f43-4d26-9a6d-39370b0a6dc2.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.73.0-SNAPSHOT from the development branch

**Comment by KernB** [comment]
Approved on RC 1.72.1 https://jira.sormas-tools.de/browse/SORDEV-11388
