### ISSUE TITLE
[Cases] Error message appears when trying to add a sample with a pathogen test result to a case

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8168]
### Bug Description

In the 'Cases' directory, an error message appears when trying to save a sample that has a pathogen test result.

### Steps to Reproduce

1. Open an existing case;
2. Create a new sample with a pathogen test result;
3. Click 'Save'.

### Actual Behavior

An error message appears and the sample can not be saved:
![image](https://user-images.githubusercontent.com/96909231/156137330-aabd46df-975b-4a86-8c67-31f31ec9666c.png)

### Expected Behavior

No error message appears and the user is able to save the sample.

### Screenshots

GIF of the steps to reproduce:
![Error message](https://user-images.githubusercontent.com/96909231/156137954-b178e940-b7fe-48b6-b6e5-89492cb31453.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT(f42cb7c)
* Android version/Browser:  Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

Logs:
[Logs for the report.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8160281/Logs.for.the.report.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT (ef41e6b) from the development branch.
