### ISSUE TITLE
Disease Variant is not updated from Pathogen test

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8170]
### Steps to Reproduce

1. Have setup at the lab message a disease variant for Covid-19
2. Fetch the new lab message with a National user role logged in
3.  Process the lab message and select Create case
4. At Disease variant dropdown below the Covid disease leave it empty
5. Press save case
6. At the screen of new sample complete the mandatory fields(Data sample collected)
7. Select "Save and Open case"
8. At the pop-up to Update case disease variant pick YES option
9. At confirm case pick NO
10. Check the Disease Variant dropdown
11. Try to make a save without touching any data or tab

### Actual Behavior
The Disease Variant dropdown is empty without having the option selected from the Pathogen test. At step 11 user gets an error that data was changed in meantime

### Expected Behavior
The Disease Variant dropdown should contain the same value from Pathogen test because the option made at step 8 was to update that value 

### Screenshots

<img width="917" alt="Screenshot 2022-03-01 at 11 26 18" src="https://user-images.githubusercontent.com/91872179/156152290-47e0e676-1df7-43f9-a386-d8c2b75cbc7c.png">

### System Details

* Device:
* SORMAS version: 1.69.0
* Android version/Browser:
* Server URL:
* User Role: National User

**Comment by FredrikSchaeferVitagroup** [comment]
The disease variant actually is getting updated, the case just is loaded to the UI before the change is available. You can check this by manually reloading the case after the steps to reporduce.

I therefore change the severity of this bug to minor.
