### ISSUE TITLE
[Create new case form] Enter home address fields not visible when the checkbox is checked

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8184]
### Bug Description

When using the 'Person search option' in the 'Create new case form', adding the person and removing them, leads to the fields from 'Enter home address of the case person now' to disappear, even if the checkbox is still checked.

### Steps to Reproduce

1. Navigate to the 'Cases' directory and open the 'Create new case form';
2. Enter the mandatory information;
3. Check the 'Enter home address for the case person now' checkbox;
4. For the person related fields use the 'Person search option' and select an existing person;
5. Remove the selected person from the 'Case create form'.

### Actual Behavior

The 'Enter home address of the case person now' checkbox remains checked but the fields that became visible at step 3 have disappeared.

### Expected Behavior

The 'Enter home address of the case person now' checkbox remains checked and the fields that became visible at step 3 remain visible (and their content that was related to the searched person from step 4 gets cleared).

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/156339290-1ee96847-2d9e-48b7-99c0-e1e6b62ac9dd.png)
![image](https://user-images.githubusercontent.com/96909231/156339323-000a5103-846f-41a5-b0cb-03c6f90b61d6.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT(7461f74)
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.69.0-SNAPSHOT (e32e36b) from the development branch.
