### ISSUE TITLE
Person search selection prompts location popup

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8186]
### Bug Description

When selecting existing persons during the case creation process, the update location prompt is triggered (twice even) when a person with a home address in a facility is selected.

### Steps to Reproduce

1.Prepare by creating a person which has a home address in a facility
2.Go to the case directory and create a new case
3.Select the previously created person in the person search

### Expected Behavior

The location update pop-up should not get triggered because selecting an existing person should make no changes to the home address that was previously entered already
### Screenshots

![locationPopUpError](https://user-images.githubusercontent.com/70317594/156368277-31a9f7a0-b540-412c-9c04-24c3dc30037c.PNG)
![locationPopUpError2](https://user-images.githubusercontent.com/70317594/156368292-9f5bc76a-26da-479b-997d-bc6e13165ce4.PNG)

### System Details

* Device:
* SORMAS version: 1.68.2
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

still open from this bug report: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8098

**Comment by AndyBakcsy-she** [comment]
Ticket was verified during a peer-to-peer session with the developer that worked on the ticket.
No issues were found and the fix has been seen working in all instances where the responsible code could be called.
