### ISSUE TITLE
SORMAS GHANA: Requirements Document (version 1.0)

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#819]
@MartinWahnschaffeSymeda @MateStrysewskeSym @Chinedar 
**Project: SURVEILLANCE OUTBREAK RESPONSE MANAGEMENT & ANALYSIS SYSTEM (SORMAS) GHANA IMPLEMENTATION
Date(s): 12.10.2018
Prepared by: DANIEL TOM-ABA
Document status:  Draft**  

**Introduction**
This document contains the system requirements for SORMAS-GHANA PROJECT. These requirements have been derived from several sources, including Disease framework, process models and user requirement from Ghana Health Services (GHS) and system requirements, design thinking adaptation changes from Helmholtz Centre for Infection Research (HZI), Adaptation implementation by Ghana Community Network Ltd (GCNET ltd).

**1.1 Purpose of This Document**
This document is intended to guide adaptation development of SORMAS-GHANA PROJECT. It will go through several stages during the course of the project:
1.	Draft: The first version, or draft version, is compiled after requirements have been discovered, recorded, classified, and prioritized.
2.	Proposed: The draft document is proposed as a potential requirements specification for the project. Several parties, who may comment on any requirements and any priorities, either to agree, to disagree, or to identify missing requirements, should review the proposed document. Readers include end-users, developers, project managers, and any other stakeholders. The document may be amended and reproofed several times before moving to the next stage.
3.	Validated: Once the various stakeholders have agreed to the requirements in the document, it is considered validated. 
4.	Approved: The validated document is accepted by representatives of each party of stakeholders as an appropriate statement of requirements for the project. The developers then use the requirements document as a guide to implementation and to check the progress of the project as it develops.

**1.2 How to Use This Document**
We expect that this document will be used by people with different skill sets. This section explains which parts of this document should be reviewed by various types of readers.

**Types of Reader**
Software engineers: The technical background, system requirement and functional characteristics sections are pertinent to you.
End-users: The product scope, perspective, use cases, and user characteristics sections are pertinent to you.
Project managers: Technical and user requirements, product timeline and framework, deliverables and product output sections at the end of project are pertinent to you.
 
**Technical Background Required**
The SORMAS® is being developed on state-of-the-art development tools such as Vaadin framework, JAVA EE Server, Payara and PostgreSQL Database. The SORMAS platform consists of two major components, namely, the mobile app (android) which interacts with the Payara Server via a REST-API and a Vaadin web client application. SORMAS® runs on android mobile smart devices, tablets and desktop PCs. Software lifecycle are being implemented via an agile project management cycle (SCRUM) based on multiple Design Thinking workshops with users, stakeholders, and field pilot evaluations in Nigeria and Ghana. Software source codes, backlogs and specifications are managed and documented open access under GitHub (https://github.com/hzi-braunschweig/SORMAS-Project/). An open web-version of SORMAS® with virtual data can be accessed openly for play purposes at https://sormasorg.helmholtz-hzi.de/sormas-demo.html.

**Overview Sections**
SORMAS® is a mobile eHealth System that organizes and facilitates disease control and outbreak management procedures in addition to disease surveillance and epidemiological analysis for all administrative levels of the public health system. SORMAS® is characterized by the following features: Digitalized notification at health facility level, Case based surveillance, Bi-directional information flow, Contact follow-up management, Outbreak detection algorithms, Interoperability with common systems, Open source, Mobile offline capability, Inclusion of all relevant actors e.g. laboratories and User centered design

**1.3 Scope of the Product**
The scope of this project is to deploy a server, web and mobile app version of SORMAS in Ghana. The first phase of action is the set-up of hardware and server framework for SORMAS-Ghana. The second phase of action will be to set up the current version of the SORMAS kernel with changed infrastructural data (districts, regions, laboratories, sub districts, population data sets) and deploy to the Ghana SORMAS server. Third phase would be to conduct a TOT user training and thereafter proceed to conduct a 5-day technical field pre-testing of the Ghana SORMAS system in atleast 3 districts. The fourth phase is to 

**1.4 Business Case for the Product**

SORMAS-Ghana system is required to be deployed in Ghana to enhance the e-surveillance framework within Ghana Health services and ensure efficient detection, validation and control of epidemic prone diseases. Several change requests have been made for SORMAS adaptations for Ghana from the current SORMAS kernel version. SORMAS needs to be completely adapted for use in Ghana due to the following reasons. Difference in nomenclature of infrastructural data, different workflow within the Ghana surveillance system and specific user rights. See table 1.

**1.5 Overview of the Requirements Document**
![image](https://user-images.githubusercontent.com/19344651/47096726-1527e780-d230-11e8-9bab-57721da6870d.png)

**2. General Description**

The Surveillance Outbreak Response Management and Analysis System (SORMAS®) is an open source mobile health (mHealth) and electronic health (eHealth) software for disease surveillance, disease control and outbreak procedures. The mission of SORMAS is to improve prevention and control of communicable diseases particularly in resource-poor settings. SORMAS is free of charge and adheres to the highest data protection standards, good scientific practice, and open access policy. SORMAS is characterized by the following features: Digitalized notification at health facility level, case based surveillance, bi-directional information flow, contact follow-up management, outbreak detection, mobile offline capability, inclusion of all relevant actors (e.g. laboratories), and user centered design. SORMAS includes disease specific process models for the following high priority epidemic prone diseases:  Ebola, Lassa fever, Monkeypox, Avian Influenza, Dengue fever, Yellow fever, Measles, Cerebrospinal Meningitis, Plague, Cholera and unforeseen “Emerging Disease X” for adhoc measures.

**2.1 Product Functions**
![image](https://user-images.githubusercontent.com/19344651/47096785-35f03d00-d230-11e8-82fa-d987f51b7825.png)
**3. Specific Requirements** 
This section of the document lists specific requirements for SORMAS Ghana Project. Requirements are divided into the following sections:
1.	User requirements. These are requirements written from the point of view of end users, usually expressed in narrative form.
2.	System requirements. These are detailed specifications describing the functions the system must be capable of doing.
3.	Interface requirements. These are requirements about the user interface, which may be expressed as a list, as a narrative, or as images of screen mock-ups.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Looking at this I think that it would be better to have one issue for each requirement that needs to be implemented.  That would be easier to understand - for example I don't get the difference between the points under 1.5 and 2.1. In addition you have probably some additional information that you could add to each issue.

**Comment by MartinWahnschaffeSymeda** [comment]
See #828 ... #835
