### ISSUE TITLE
New 'Follow-up until' date does not get updated when editing an existing positive sample with an earlier collection date

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8191]
### Bug Description
The new 'Follow-up until' date does not get updated when the user opens an existing positive Sample and edits the 'Collection Date' to a date prior to the 'Report Date'.

This issue is reproducible for:
- Cases
- Contacts

### Steps to Reproduce

1. Create a Case and set the 'Report Date' to the current date.
2. Add a positive Sample with a 'Collection Date' 1 day prior to the 'Report Date'.
3. Check the 'Follow-up until' date and 'Expected follow-up until' date.
-> both dates get updated accordingly.
4. Edit the Sample and set the 'Collection Date' 2 days prior to the 'Report Date'.

### Actual Behavior
Only the 'Expected follow up until' date gets modified, the 'Follow up until' doesn't.

### Expected Behavior
Both 'Follow-up until' date and 'Expected follow-up until' should get updated accordingly when the 'Collection Date' of the Sample gets changed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/156394011-d690f5c1-372c-4b4c-ba5f-1680cc7383fb.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT (ef41e6b)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information
- I found this bug while testing #7926, but I opened a new ticket because it is too close to the release and it won't get fixed in time.

**Comment by roxanamlendea** [comment]
I found another scenario related to this issue:

1. Create a Case and set the Report Date to today;
2. Add a 'positive' Sample with a Collection Date 1 day prior to the Report Date;
3. Check the Follow-up Until dates; 
-> both 'Follow up until' and 'Expected Follow up until' dates get updated (correct);
4. Edit the Sample and set result to 'Negative';
5. Check the Follow-up dates;

-> Only the 'Expected follow up until' date gets modified, the 'Follow up until' doesn't.

![image](https://user-images.githubusercontent.com/89522688/156542416-c212d12b-c45f-43da-b58b-c6dab9ba84be.png)
![image](https://user-images.githubusercontent.com/89522688/156542469-44250b9a-4e8f-4bec-be76-498511625eb1.png)

**Comment by roxanamlendea** [comment]
As discussed with @MateStrysewske , I'm adding this scenario to this issue so that it will be addressed together in the same ticket:

1. Create a Contact with COVID-19 as Disease;
2. Add a Sample with a Collection Date prior to the Report Date of the Case and with a 'positive' Pathogen Test with COVID-19 as Disease and Save;
3. Click 'Yes' in the following pop-up:
![image](https://user-images.githubusercontent.com/89522688/156768270-c60f6cbe-303f-4e85-943c-34c8a643b591.png)
4. Fill in the mandatory data in the Create Case form;
5. Inspect the Follow-up Dates in the new created Case;

![image](https://user-images.githubusercontent.com/89522688/156768341-29ab2068-ee55-433c-9c1e-794463751307.png)

-> Only the 'Expected Follow-up' Date is updated accordingly, the 'Follow-up Until' Date isn't.
Also, if I Save the page again, the 'Follow-up until' Date is updated accordingly as well...

![image](https://user-images.githubusercontent.com/89522688/156768429-97b729f2-5feb-4ce1-b71a-87bc651fd9bb.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the  test-de2.sormas.netzlink.com using the SORMAS version 1.70.0-SNAPSHOT(0587fdf).

The behavior described in the bug report is still reproducible through the following flows:

I: Contacts:
1. Create a contact and set the 'Report Date' to the current date;
2. Add a positive sample with the 'Collection Date' set to 1 day prior to the 'Report Date' of the contact;
3. Check the 'Follow-up until' and 'Expected follow-up until' dates; -> both dates get updated accordingly;
4. Edit the sample and set the 'Collection Date' 2 days prior to the 'Report Date' of the contact.
=> Only the 'Expected follow up until' date gets modified; the 'Follow up until' does not.

II: 
Cases: The flow described by @roxanamlendea in the comment of this ticket from the 3rd of March, 12.04pm that concerns deleting the sample.

Contacts: The flow described by @roxanamlendea in the comment of this ticket from the 3rd of March, 12.04pm that concerns both deleting the sample, or setting it's result to 'Negative'.


III: Contacts: The flow described by @roxanamlendea in the comment of this ticket from the 4th of March, 3.05pm.

**Comment by adinaflorea9** [comment]
Re-tested the ticket on test-de2.sormas.netzlink.com using SORMAS version 1.70.0-SNAPSHOT(c6adc50) - I am re-opening the ticket as the behavior from the bug report is reproducible in the following 2 flows:

- [ ] Contacts - deleting a positive sample that has a collection date prior to the report date of the contact;
- [ ] Contacts/Cases - creating a resulting case for a contact via a sample (with a positive pathogen test result) and a collection date prior to the report dates of the contact and of the resulting case.

**Comment by adinaflorea9** [comment]
Tested the ticket on  test-de2.sormas.netzlink.com using SORMAS version 1.70.0-SNAPSHOT(6a278e2) - I am re-opening the ticket as the following behavior is still reproducible:

- [ ] Contacts/Cases - creating a resulting case for a contact via a sample (with a positive pathogen test result) and a collection date prior to the report dates of the contact and of the resulting case.

**Comment by alexcaruntu-vita** [comment]
I am closing this. The last scenario will be address in a separate ticket (https://github.com/hzi-braunschweig/SORMAS-Project/issues/8550).

**Comment by adinaflorea9** [comment]
As @alexcaruntu-vita mentioned that the last scenario will be covered in #8550 I am moving the ticket from testing.

The other scenarios from the current ticket were verified on test-de2.sormas.netzlink.com using SORMAS version 1.70.0-SNAPSHOT(https://github.com/hzi-braunschweig/SORMAS-Project/commit/6a278e25a6278d1e81335c1ba1f9050f45f496e0)
