### ISSUE TITLE
Adding 2 positive Pathogen Test Result of different diseases to a Sample, duplicates the Sample

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8193]
### Bug Description
When the user adds 2 positive Pathogen Test Results (each for a different Disease), the Sample in the Contact's Sample Card gets duplicated.

This is reproducible for:
- Contacts
- Event Participants

### Steps to Reproduce

1. Create a Contact and set the Disease to 'COVID-19';
2. Add a Sample with a 'Positive' Pathogen Test Result (with the Disease set to COVID-19);
3. Click 'Yes' in first pop-up to create a Resulting Case for the Contact;
4. Fill in the 'Create new case' form with the mandatory data;
5. Go back to the Contact and open the Sample;
6. Add a 'New positive test result' to the Sample (with the Disease set to Anthrax);
7. Click 'Yes' in the second pop-up that asks the user to create a case for Anthrax;
8. Open the Contact again and observe the Sample card.

### Actual Behavior
There are 2 Samples. Basically the Sample gets duplicated. If the user opens them, each of the samples show the same 2 pathogen test results (the one for COVID19 and the one for Anthrax).

### Screenshots
![samples](https://user-images.githubusercontent.com/89522688/156405742-5c47562e-0f88-4aee-8bae-5d6cb7fd4fe7.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT (19c54c2)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information
- Found this issue while testing ticket #7922

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS 1.70.0-SNAPSHOT(62b7ad6) from the development branch.
