### ISSUE TITLE
1)	on the configuration menu of the web application, there is no way to filter the outbreaks by diseases and by periods and also how tell when the outbreak is over 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#820]

**Comment by MartinWahnschaffeSymeda** [comment]
@foyiri Outbreaks are currently only available for CSM so there is nothing we could filter.
The outbreaks can currently only be set to active or inactive. There is no way to set a specific time or something like that.
It that is needed we have to define all the specific details for it.
