### ISSUE TITLE
Select different person is loading all persons from the system when a search with empty fields is applied

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8207]
### Bug Description
The list with all persons is loaded at search with empty fields.

Preconditions:
Have this configuration PERSON_DUPLICATE_CUSTOM_SEARCH set to true

### Steps to Reproduce
1. Process a lab message with a National User logged in
2. Select the option "Select a different person"
3. Click on Reset button
4. Click on Search button with empty fields(First, last name, Id)
5. Select one of the other option: "Select a matching person" or "Create a new person"
6. Select back the option "Select a different person"
7. Look at the list of the users 

### Expected Behavior
The list with all persons from the system should not be displayed because this can add performance issues when having a large number of persons.
The expected result from step 11 should be the same behaviour like at step 4, empty list, because at least one of the fields should be completed to make a search

### Actual Behavior
The list with all persons from the system is loaded

### Screenshots
<img width="1104" alt="Screenshot 2022-03-03 at 13 00 03" src="https://user-images.githubusercontent.com/91872179/156560805-303087f0-e6b5-4731-88d9-77d6add0859a.png">

### System Details

* Device:
* SORMAS version: 1.69.0
* Android version/Browser:
* Server URL:
* User Role: National User

**Comment by adinaflorea9** [comment]
Verified ticket on test-de2.sormas.netzlink.com using the version of SORMAS 1.70.0-SNAPSHOT(d4e08c4).
