### ISSUE TITLE
The 'Disease Variant' field is hidden in the 'Create new case' form of a Travel Entry

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8210]
### Bug Description
When a Case is created for a Travel Entry, the 'Disease Variant' field is missing from the 'Create new case' form.

### Steps to Reproduce

1. Open or create a Travel Entry which has 'COVID-19' set as 'Disease' and also has a Disease Variant selected;
2. Create a Case for the Travel Entry;
3. Inspect the 'Create new case' form.

### Expected Behavior
Disease Variant field should be visible and populated according to the Travel Entry.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/156573598-44c138f7-1516-49d1-9a7d-3bad4f43bbc7.png)

### System Details

* Device: Window 10
* SORMAS version: 1.69.0-SNAPSHOT (f6fa042)
* Android version/Browser: Chrome
* Server URL: test-de1.sormas.netzlink.com, test-de2.sormas.netzlink.com, test-de3.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
- This issue is reproducible only on the testing instances; it's not reproducible on my local machine.
- I found this issue while testing #8105

**Comment by MateStrysewske** [comment]
@vidi42 Added this to the interactions backlog because @kwa20 suspects that this might be connected to Survnet.

**Comment by abrudanancuta** [comment]
Validated on test.de and test.de2 with this version 1.70.0-SNAPSHOT (0587fdf)
Validated on local environment with this version 1.70.0-SNAPSHOT (0587fdf)
