### ISSUE TITLE
[Angular] Header Menu (burger menu) [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8214]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/v8aP3w4
- We should make it to fit with width automatic ; detect from javascript and show burger menu if windows width is too small for menu
 
### QA Section

1. What should the QA look for (what was done)
- Check that the menu switches to the burger menu once the requirement is met (once confirmed by @cristinacoza).
 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!

**Comment by RobertoDascalu** [comment]
Testing done. All good !
