### ISSUE TITLE
[Angular] Case Directory: Detailed Export Modal [2 + 0]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8216]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/52YyZ2w

### QA Section

1. What should the QA look for (what was done)
- Check that the pop-up is shown and contains the same text as per the current Sormas implementation

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
