### ISSUE TITLE
[Angular] Case Directory: New Custom Export Configuration  [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8219]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP0WOOJ
- This should use dynamic forms

### QA Section

1. What should the QA look for (what was done)
- Check that the pop-up opens when clicking on "New export configuration"
- Check that the user has the same options to check as per the current Sormas implementation
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!
