### ISSUE TITLE
[Angular] Case Directory: Line Listing [5 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8220]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnvZjGM
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/v814ew1
- We will not implement it as a table (as it would probe too difficult)
- The development team should sync up before the actual development starts, as to fin the best approach

### QA Section

1. What should the QA look for (what was done)
- Check that the user can add / delete multiple lines
- Check that the same fields are mandatory as per the current Sormas implementation.

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
-date of report can not be later then today
-the user is not allowed to choose the date of birth without knowing the year
![image](https://user-images.githubusercontent.com/102517557/160427882-9571a32c-0b76-478e-9345-0fb7cb067c0a.png)
![image](https://user-images.githubusercontent.com/102517557/160428156-3329b0bf-b177-4e59-aeda-186ecc4eedc1.png)
