### ISSUE TITLE
[Angular] Case Directory: Merge Duplicates baseline structure [8 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8222]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKgGd3g
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/bgb1LKo
- Reference 3: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/25GQzKp
- This ticket will only handle the baseline structure (including the filters)
- We need to create a new component that makes use of infinite loading (and not as we have it now for the current table component). This should be a component that maybe can be re-used for other such cases. This will be reused also for Contacts.
- We should also implement the "Hide" functionality, that hides the current pair (only visually)
- We should also implement the "Hide" functionality for duplicated items (the left hand side one) which will hide the below row
- We should also implement an empty action (console.log) for the "Merge" and "Pick" action.
- We should also implement the page load pop-up with the notice (check Reference 3).

### QA Section

1. What should the QA look for (what was done)
- Check the baseline structure (filters, table)
- Check that the hide functionality works (left hand side & right hand side)
- Check that the pop-up is shown on every page refresh
2. What can the QA ignore (what was omitted)
- Actual pick, merge, check completeness functionalities
- The Merge guide

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done
-responsible district becomes mandatory ones you select the region
-creation date can not be later then today

**Comment by RobertoDascalu** [comment]
Testing done - all good
