### ISSUE TITLE
[Angular] Samples: Lab Messages [5 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8223]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/xryplnA
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnxawlG
- Reference 3: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP2v91k (assignee modal)
- @cristinacoza as it's to difficult to have an input field in the Assignee column, we need to do it in a pop-up as on the current Sormas
- The download action should only have a console.log and not the actual download of the file (as we don't have the BE implemented).
- The "Process" text should be a button with an action (console.log) - @cristinacoza please update the design to make it clear that it's a button / link.
- For the emitted event from the table it should be a single emitter to which we pass a type (string). (consult @danielrus for explanation :) - "row-action" ).
- We also need to include the filters and the  "View Options" action button (don't add the bulk edit action)

### QA Section

1. What should the QA look for (what was done)
- Just check that it looks as in the design
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
