### ISSUE TITLE
[Angular][Bug][DevOps] Routing problem for the test site  [5] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8224]
### Steps to Reproduce

1. Images are missing across the site (this might be an Angular problem). @adriandumavitagroup please investigate
2. When refreshing the page we get a 404

### Expected Behaviour

1. All images should be present and displayed (/assets).  
2. We shouldn't get a 404 when refreshing the page 

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RobertoDascalu** [comment]
Testing done - issue fixed ,everything looks fine
