### ISSUE TITLE
[Angular] Truncate table columns [3 + 2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8225]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to format correctly all the data displayed (i.e date)
- We need to keep all of the columns to the left
- We need to set a max width of 200 px per column (longer texts should slip on additional rows)

### QA Section

1. What should the QA look for (what was done)
- max width was changed to be specific for columns (not general): right now, max width is enforced for address columns (events list page, users list page), comment columns (tasks list page, shares list page) and task type (task list page)
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
