### ISSUE TITLE
[Angular] Documentation: Color guide (general) [8]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8227]
### Problem Description

- We need to document the logic behind the colours used across the site for diseases and disease-related entities

### Proposed Solution

- Create a Gdocs (for now) in which to start the documentation
- Once the Gdocs is done and reviewed by the team, we can move it to Confluence and make it public to all Sormas Confluence users.

### Possible Alternatives

- Create a local document, and then move it to Confluence.

**Comment by cristinacoza** [comment]
Color system document: 
https://docs.google.com/document/d/1iSA8ExH8V8NhS5KdOlWlgr9ZIdQ4nPc0WZBWhGR0YBs/edit?usp=sharing
