### ISSUE TITLE
The 'Travel Entry' of an unpreserved case is not associated with the person of the preserved case after the 'Merge Duplicate Cases' flow

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8229]
### Bug Description

When merging duplicate cases that have ‘Travel entries’ associated, the travel entry of the unpreserved case is not associated with the person of the preserved case after the merge.

### Steps to Reproduce

1. Create 2 duplicate cases;
2. From the ‘Epidemiological data’ tab of the cases, add 'Travel entries' to them;
3. Merge the 2 cases;
4. Navigate to the ‘Persons’ directory and observe the persons listed when filtering using the ‘Travel entries’ filter tab.

### Actual Behavior

The travel entry of the unpreserved case is not associated with the person of the preserved case.

The person associated with the travel entry that merged from the unpreserved case into the preserved case is still visible in the system.

### Expected Behavior

The travel entry of the unpreserved case is associated with the person of the preserved case.

The person associated with the travel entry that merged from the unpreserved case into the preserved case is no longer visible in the system.

### Screenshots

The 2 cases before the merge:
![image](https://user-images.githubusercontent.com/96909231/156732638-c293a371-5f43-41f0-8179-ff3afc970cb3.png)

The preserved case after the merge:
![image](https://user-images.githubusercontent.com/96909231/156732740-838fbd85-fc2e-40c1-883b-78dab618e274.png)

The 'Persons' directory after the merge:
![image](https://user-images.githubusercontent.com/96909231/156732795-80192a93-194a-4a32-bf1f-c3fb6cf663c5.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT(11441f0)
* Android version/Browser: Chrome
* Server URL:  test-de3.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.70.0-SNAPSHOT from the development branch (bb551be).
