### ISSUE TITLE
[Angular][Backend][SPIKE] Samples: Lab Messages getByID [1] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8237]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/yg5RMZz
- We need to see how the backend will return the actual lab message preview (already formatted ?)
- @marius2301 please investigate and add a comment with an example of the response so we can move forward with the FE implementation.

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by marius2301** [comment]
"labMessageDetails":"
<Bundle xmlns=\"http://hl7.org/fhir\">\n     
    <meta>\n        
        <lastUpdated value=\"2021-01-04T15:38:09+01:00\"/>\n
        <profile value=\"https://demis.rki.de/fhir/StructureDefinition/NotificationBundleLaboratory\"/>\n
        <tag>\n           
            <system value=\"https://demis.rki.de/fhir/CodeSystem/ResponsibleDepartment\"/>\n
            <code value=\"1.test-oegd08\"/>\n
        </tag>\n
        <tag>\n           
            <system value=\"https://demis.rki.de/fhir/CodeSystem/ResponsibleDepartmentSubmitter\"/>\n
            <code value=\"1.test-oegd08\"/>\n
        </tag>\n
        <tag>\n           
            <system value=\"https://demis.rki.de/fhir/CodeSystem/ResponsibleDepartmentNotifier\"/>\n
            <code value=\"1.test-oegd07\"/>\n
        </tag>\n
        <tag>\n           
            <system value=\"https://demis.rki.de/fhir/CodeSystem/ResponsibleDepartmentPrimaryAddress\"/>\n
            <code value=\"1.test-oegd08\"/>\n
        </tag>\n
    </meta>\n
    <identifier>\n        
        <system value=\"https://demis.rki.de/fhir/NamingSystem/NotificationBundleId\"/>\n
        <value value=\"ba01ff12-2cf7-4ffb-874e-5729aa3f80f7\"/>\n
    </identifier>\n
    <type value=\"document\"/>\n
    <timestamp value=\"2021-01-04T15:38:08+01:00\"/>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Composition/a20bb976-f83c-4b7b-ab37-b2fc4aea80d1\"/>\n
        <resource>\n           
            <Composition xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"a20bb976-f83c-4b7b-ab37-b2fc4aea80d1\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/NotificationLaboratorySARSCoV2\"/>\n
                </meta>\n
                <extension url=\"https://demis.rki.de/fhir/StructureDefinition/ReceptionTimeStampType\">\n                 
                    <valueDateTime value=\"2021-01-04T15:38:09+01:00\"/>\n
                </extension>\n
                <status value=\"final\"/>\n
                <type>\n                 
                    <coding>\n                    
                        <system value=\"http://loinc.org\"/>\n
                        <code value=\"34782-3\"/>\n
                        <display value=\"Infectious disease Note\"/>\n
                    </coding>\n
                </type>\n
                <category>\n                 
                    <coding>\n                    
                        <system value=\"http://loinc.org\"/>\n
                        <code value=\"11502-2\"/>\n
                        <display value=\"Laboratory report\"/>\n
                    </coding>\n
                </category>\n
                <subject>\n                 
                    <reference value=\"Patient/19dd38ad-9cb2-4fd0-97f0-eac97a598de5\"/>\n
                </subject>\n
                <date value=\"2021-01-04T15:38:08+01:00\"/>\n
                <author>\n                 
                    <reference value=\"PractitionerRole/a2bb1ab7-cc7f-450e-8c89-3cde90eae2f6\"/>\n
                </author>\n
                <title value=\"SARS-CoV-2 Labormeldung\"/>\n
                <section>\n                 
                    <code>\n                    
                        <coding>\n                       
                            <system value=\"http://loinc.org\"/>\n
                            <code value=\"29308-4\"/>\n
                            <display value=\"Diagnosis\"/>\n
                        </coding>\n
                    </code>\n
                    <entry>\n                    
                        <reference value=\"Condition/d46544a3-d419-43cc-b17c-a76549bcade4\"/>\n
                    </entry>\n
                </section>\n
                <section>\n                 
                    <code>\n                    
                        <coding>\n                       
                            <system value=\"http://loinc.org\"/>\n
                            <code value=\"18725-2\"/>\n
                            <display value=\"Microbiology studies (set)\"/>\n
                        </coding>\n
                    </code>\n
                    <entry>\n                    
                        <reference value=\"Observation/899252c2-99bc-411e-af71-150c76c98b59\"/>\n
                    </entry>\n
                </section>\n
            </Composition>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Patient/19dd38ad-9cb2-4fd0-97f0-eac97a598de5\"/>\n
        <resource>\n           
            <Patient xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"19dd38ad-9cb2-4fd0-97f0-eac97a598de5\"/>\n
                <meta>\n                 
                    <lastUpdated value=\"2021-01-04T15:38:09.122+01:00\"/>\n
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/NotifiedPerson\"/>\n
                </meta>\n
                <extension url=\"https://demis.rki.de/fhir/StructureDefinition/PseudonymRecordType\">\n                 
                    <valueBase64Binary value=\"eyJ0eXBlIjoiZGVtaXNQc2V1ZG9ueW0iLCJhY3RpdmVQc2V1ZG9ueW0iOnsiZmFtaWx5TmFtZSI6WyJNZ2dBQUFRRUVpS0FnZ0VBZ0FCQ1FJQ0FJQUNFRVFDQWdBQURBUUNCZ1FBSUNBaENBd0lBQ0NBQUFBSUFNQUFBRW9BSUFBaUFnQVFBQ0FBZ0JvZ2dBQmdEQUFBQW9LQWdBQUNBQU1JS2hBQkFBSUFBQ0lDQkFnQUFnRUJBQUFJQUFBQUFnQU5FQUFBQ2dnQWtBQUFBREFBQUJBSUFHQUFBQVFJSU1BQUFFZ0E9Il0sImZpcnN0TmFtZSI6WyJBQWdBQUFBQUFBQUFCZ0FBSUFBQUFBQUFBQUFBUUFBQUFDUUNnQUFBQUFBQUFBQUVBZ0lBQUFBQUFBQUFCQUFBQW9BUUFBSUFBQUFBQUFBZ0FBQUFBQUFDQUFBQUFBQUVBQUFCQUFvQUlBQVFCQUVRQUFFUUFna1FBQVVRQUFFQUFCQUFBQ0FBZ0FBQ0FBQUVBQUFBZ0FBQUFBSUFCQUFBQUFBQUFBQUFCZ1k9Il0sImRhdGVPZkJpcnRoIjoiREFFZ0FBUXhFQkFoQkFJRkF3WU1CQUZzQUJRUUJBQ2tjQ1J5NUFCS2hBUUlnYUJvZ0lncGhvQU9TQ0RFRUVvSUlRZ0FVQ2dFUVFJQ0FrTVNBaElBZ0E9PSIsImRpc2Vhc2VDb2RlIjoic2Fycy1jb3YtMiJ9LCJvdXRkYXRlZFBzZXVkb255bSI6eyJmYW1pbHlOYW1lIjpbIkFBQUVDQUFFQUFDQkFBTUJSQUFBQUNBUUFBNElFUUVIZ2tBRkFDQ0VRQUFFQkFDQUVBQUFCRVFBQUVJQUFBUUNRRUNRQXpBaUJnUWdBQUFBQUNBTWdBUkFBQUlRQVFCQ0JBSVFJZ0FBSmhFQUFBQUFBRVFDQ0FBQUFBQUVFUUVBQUFBQUlpVUJCVUlBQUFnRUFBQUFBQUNTUkJBRWlBSUFFQWdBQWtBSWdSST0iXSwiZmlyc3ROYW1lIjpbIkFHZ0FBQUFBQkFDQUFBQUFBQUFBUkFFQUFBQUlBRUFJQUFBQUFBQUFBQUFFQUFCQUFFUUFBQkFBQUVBQ0FBQUFBRUFBQUFBQUFFUUFJQkFCQUFBQUFBQVVBQUlBUUFBQUFBQkFBQUFBSUVBRUFBQUFBQUNnQUFCQUFJQUFBQUFBQUFBQUFBQVJBVUFBQUFBQUJVRUFBQUFRQUFBQUFnQUFBQUJBUUFBSUFnQT0iXSwiZGF0ZU9mQmlydGgiOiJBTGpCQ0lFR0VrQUFBWVlZWEFDZ0RDQUNpb0lLaUtvQ3dCQ0tCQWlnSUVDQVFBSkRCQUFLZ0lLQUFnZ0lBS05BZ0pBQWhnQXA5dzBFQUFCQWdKZ2lJQT09IiwiZGlzZWFzZUNvZGUiOiJzYXJzLWNvdi0yIn19\"/>\n
                </extension>\n
                <name>\n                 
                    <use value=\"official\"/>\n
                    <family value=\"Mustermann\"/>\n
                    <given value=\"Max\"/>\n
                </name>\n
                <telecom>\n                 
                    <system value=\"email\"/>\n
                    <value value=\"max@mustermann.de\"/>\n
                </telecom>\n
                <telecom>\n                 
                    <system value=\"phone\"/>\n
                    <value value=\"12345678\"/>\n
                </telecom>\n
                <gender value=\"male\"/>\n
                <birthDate value=\"2001-03-31\"/>\n
                <address>\n                 
                    <extension url=\"https://demis.rki.de/fhir/StructureDefinition/AddressUse\">\n                    
                        <valueCoding>\n                       
                            <system value=\"https://demis.rki.de/fhir/CodeSystem/addressUse\"/>\n
                            <code value=\"primary\"/>\n
                        </valueCoding>\n
                    </extension>\n
                    <line value=\"Musterstrasse\"/>\n
                    <city value=\"Kirchanschöring\"/>\n
                    <postalCode value=\"83417\"/>\n
                    <country value=\"20422\"/>\n
                </address>\n
            </Patient>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/PractitionerRole/a2bb1ab7-cc7f-450e-8c89-3cde90eae2f6\"/>\n
        <resource>\n           
            <PractitionerRole xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"a2bb1ab7-cc7f-450e-8c89-3cde90eae2f6\"/>\n
                <organization>\n                 
                    <reference value=\"Organization/79fc4d2a-3bd3-4fc9-a5f6-0bf10fe1ef4c\"/>\n
                </organization>\n
            </PractitionerRole>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Organization/79fc4d2a-3bd3-4fc9-a5f6-0bf10fe1ef4c\"/>\n
        <resource>\n           
            <Organization xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"79fc4d2a-3bd3-4fc9-a5f6-0bf10fe1ef4c\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/NotifierFacility\"/>\n
                </meta>\n
                <identifier>\n                 
                    <system value=\"https://fhir.kbv.de/NamingSystem/KBV_NS_Base_BSNR\"/>\n
                    <value value=\"647411500\"/>\n
                </identifier>\n
                <identifier>\n                 
                    <system value=\"https://demis.rki.de/fhir/NamingSystem/SendingServiceProvider\"/>\n
                    <value value=\"test-lab52\"/>\n
                </identifier>\n
                <type>\n                 
                    <coding>\n                    
                        <system value=\"https://demis.rki.de/fhir/CodeSystem/organizationType\"/>\n
                        <code value=\"laboratory\"/>\n
                        <display value=\"Erregerdiagnostische Untersuchungsstelle\"/>\n
                    </coding>\n
                </type>\n
                <name value=\"Untersuchendes Labor GmbH\"/>\n
                <telecom>\n                 
                    <system value=\"phone\"/>\n
                    <value value=\"+49 12345670\"/>\n
                    <use value=\"work\"/>\n
                </telecom>\n
                <telecom>\n                 
                    <system value=\"fax\"/>\n
                    <value value=\"+49 1234568\"/>\n
                    <use value=\"work\"/>\n
                </telecom>\n
                <telecom>\n                 
                    <system value=\"email\"/>\n
                    <value value=\"covid_labor.com\"/>\n
                    <use value=\"work\"/>\n
                </telecom>\n
                <telecom>\n                 
                    <system value=\"url\"/>\n
                    <value value=\"https://lifecodexx.com/\"/>\n
                    <use value=\"work\"/>\n
                </telecom>\n
                <address>\n                 
                    <line value=\"Line-Eid-Straße 3\"/>\n
                    <city value=\"Konstanz\"/>\n
                    <postalCode value=\"78467\"/>\n
                    <country value=\"20422\"/>\n
                </address>\n
            </Organization>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/PractitionerRole/ac0d0afd-42d8-4bac-ac76-9e2a102f95fb\"/>\n
        <resource>\n           
            <PractitionerRole xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"ac0d0afd-42d8-4bac-ac76-9e2a102f95fb\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/SubmittingRole\"/>\n
                </meta>\n
                <organization>\n                 
                    <reference value=\"Organization/7dfcdf28-3614-4e2c-8730-bba5b4a111b3\"/>\n
                </organization>\n
            </PractitionerRole>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Organization/7dfcdf28-3614-4e2c-8730-bba5b4a111b3\"/>\n
        <resource>\n           
            <Organization xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"7dfcdf28-3614-4e2c-8730-bba5b4a111b3\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/SubmittingFacility\"/>\n
                </meta>\n
                <name value=\"Traunstein_Kreis_83278\"/>\n
                <telecom>\n                 
                    <system value=\"email\"/>\n
                    <value value=\"n/a\"/>\n
                    <use value=\"work\"/>\n
                </telecom>\n
                <address>\n                 
                    <line value=\"Musterstraße 1\"/>\n
                    <city value=\"Musterstadt\"/>\n
                    <postalCode value=\"12345\"/>\n
                    <country value=\"20422\"/>\n
                </address>\n
            </Organization>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Condition/d46544a3-d419-43cc-b17c-a76549bcade4\"/>\n
        <resource>\n           
            <Condition xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"d46544a3-d419-43cc-b17c-a76549bcade4\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/DiagnoseSARSCoV2\"/>\n
                </meta>\n
                <code>\n                 
                    <coding>\n                    
                        <system value=\"http://fhir.de/CodeSystem/dimdi/icd-10-gm\"/>\n
                        <code value=\"U07.1!\"/>\n
                    </coding>\n
                </code>\n
                <subject>\n                 
                    <reference value=\"Patient/19dd38ad-9cb2-4fd0-97f0-eac97a598de5\"/>\n
                </subject>\n
            </Condition>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Observation/899252c2-99bc-411e-af71-150c76c98b59\"/>\n
        <resource>\n           
            <Observation xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"899252c2-99bc-411e-af71-150c76c98b59\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/PathogenDetectionSARSCoV2\"/>\n
                </meta>\n
                <status value=\"final\"/>\n
                <category>\n                 
                    <coding>\n                    
                        <system value=\"http://terminology.hl7.org/CodeSystem/observation-category\"/>\n
                        <code value=\"laboratory\"/>\n
                    </coding>\n
                </category>\n
                <code>\n                 
                    <coding>\n                    
                        <system value=\"http://loinc.org\"/>\n
                        <code value=\"94660-8\"/>\n
                        <display value=\"SARS-CoV-2 RNA NAA+probe Ql\"/>\n
                    </coding>\n
                </code>\n
                <subject>\n                 
                    <reference value=\"Patient/19dd38ad-9cb2-4fd0-97f0-eac97a598de5\"/>\n
                </subject>\n
                <valueString value=\"P O S I T I V\"/>\n
                <interpretation>\n                 
                    <coding>\n                    
                        <system value=\"http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation\"/>\n
                        <code value=\"POS\"/>\n
                    </coding>\n
                </interpretation>\n
                <note>\n                 
                    <text value=\"CT-Werte: E gene 32.52, N gene 22.13\"/>\n
                </note>\n
                <note>\n                 
                    <text value=\"Probennahmedatum: \"/>\n
                </note>\n
                <method>\n                 
                    <text value=\"Coronavirus SARS-CoV-2 (PCR)\"/>\n
                </method>\n
                <specimen>\n                 
                    <reference value=\"Specimen/5a2d4de1-1e11-4dd8-a800-cbbcd33d502c\"/>\n
                </specimen>\n
            </Observation>\n
        </resource>\n
    </entry>\n
    <entry>\n        
        <fullUrl value=\"https://demis.rki.de/fhir/Specimen/5a2d4de1-1e11-4dd8-a800-cbbcd33d502c\"/>\n
        <resource>\n           
            <Specimen xmlns=\"http://hl7.org/fhir\">\n              
                <id value=\"5a2d4de1-1e11-4dd8-a800-cbbcd33d502c\"/>\n
                <meta>\n                 
                    <profile value=\"https://demis.rki.de/fhir/StructureDefinition/SpecimenSARSCoV2\"/>\n
                </meta>\n
                <status value=\"available\"/>\n
                <type>\n                 
                    <text value=\"Tupferabstrich\"/>\n
                </type>\n
                <subject>\n                 
                    <reference value=\"Patient/19dd38ad-9cb2-4fd0-97f0-eac97a598de5\"/>\n
                </subject>\n
                <receivedTime value=\"2020-12-09T15:20:51+01:00\"/>\n
                <collection>\n                 
                    <collector>\n                    
                        <reference value=\"PractitionerRole/ac0d0afd-42d8-4bac-ac76-9e2a102f95fb\"/>\n
                    </collector>\n
                </collection>\n
            </Specimen>\n
        </resource>\n
    </entry>\n
</Bundle>","status":"UNPROCESSED"}

**Comment by marius2301** [comment]
see attached the response for the labmessage details
[labMessageDetails.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8323344/labMessageDetails.txt)
[labMessageJson.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8323345/labMessageJson.txt)

**Comment by laurentiustanvitagroup** [comment]
You can find the xml here: https://drive.google.com/file/d/1qtiIZ3U8qq_FdWb8uHJOqmbMEtPx04ts/view?usp=sharing
