### ISSUE TITLE
Error message appears on the 'Dashboard' page after selecting the 'Alive or Dead' filter

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8245]
### Bug Description

An error message appears on the 'Dashboard' page once the user clicks in the 'Epidemiological Curve' section on the filter 'Alive or Dead'. Afterwards, if the user attempts to use the other filters from the page, the error message appears again after clicking 'Apply Filters'.

### Steps to Reproduce

1. Navigate to the 'Dashboard' page;
2. In the 'Epidemiological Curve' section, click on the 'Alive or Dead' filter.

### Actual Behavior

An error message appears, stating: 'An error has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it'.

If the user then clicks on the other filters from the 'Dashboard' page (either from the top of the page or from the 'Grouping' dropdown) and then on 'Apply filters' the same error message is displayed.

### Expected Behavior

No error message appears and the user is able to successfully filter the results from the page based on their filter selection.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/156771693-4179f2d3-a1a4-4021-b747-3f51e3265875.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT(11441f0)
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

Logs from the testing environment:
[LogsDashboardErrorMessage.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8186207/LogsDashboardErrorMessage.txt)

**Comment by roxanamlendea** [comment]
As discussed with @adinaflorea9 , this bug was reproducible only for test-de2.sormas.netzlink.com . 
I verified the ticket on test-de2.sormas.netzlink.com using the latest version of Sormas 1.70.0-SNAPSHOT (d4e08c4) and is not reproducible anymore, and neither it is reproducible on other testing instances or on my local machine.
