### ISSUE TITLE
8)	under the “follow-up status” filter of the contact, we need to know the meaning of the following categories: “under follow-up” , “completed follow-up” , “cancelled follow-up” , “lost to follow-up”, “no follow-up

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#827]

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add description to field

**Comment by MateStrysewskeSym** [comment]
- [ ] add getDescription method to FollowUpStatus enum
- [ ] retrieve description from enum.properties file (FollowUpStatus.Desc.XXX)
- [ ] add getShortEnumCaption and getEnumDescription methods to I18nProperties, replace current getEnumCaption call with "Short" as addition with new method

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make follow-status description a bullet list
