### ISSUE TITLE
Translations missing in person pick or create pop-up

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8271]
### Bug Description

District and community are not being translated in the pick or create person form.
### Steps to Reproduce

1. Trigger a person duplicate or process a lab message
2. Check the section in the person pick or create form that displays the entered data

### Expected Behavior

All strings should be translated
### Screenshots

![personPopUpTranslation](https://user-images.githubusercontent.com/70317594/157074736-ed2139e5-3de1-4c39-8fb4-f6876e9e72ba.PNG)

### System Details

* Device:
* SORMAS version: 1.70-SNAPSHOT (907b652c030269ae6584639cafda9d44edf0c7f5)
* Android version/Browser: chrome
* Server URL: test-de2
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Waiting for the translations to be made. 
Will validate ticket afterwards
