### ISSUE TITLE
On the Event page, the red exclamation mark persists even after the user adjusts the date

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8272]
### Bug Description
On the Event page, when red exclamation mark appears and the user is informed that 'Date of Report has to be after or on the same date as Start Date', the behaviour persists even after the date has been adjusted. 

### Steps to Reproduce

1. Open an Event;
2. Set the 'Date of Event' to 28 feb 2022;
3. Set the 'Report Date' to 27 feb 2022;
-> the field is marked red and the exclamation mark appears;
4. Edit the 'Date of Event' and set it to 27 feb 2022;

### Actual Behavior

The field remains marked red and the exclamation mark persists. The user can still Save the page though.

### Expected Behavior
The field is not marked red anymore.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/157077942-9b6dbcfa-15cd-4d09-9c97-ad03903da4a6.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT (907b652)
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, Nat User

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS 1.70.0-SNAPSHOT(48fad26) from the development branch.
