### ISSUE TITLE
Initial UI support for physician's reports [2]

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#8276]
### Situation Description

The RKI built this [new set of DEMIS profiles](https://simplifier.net/DEMISArztmeldung/) allowing hospitals (and later also others, e.g. registered dorctors (niedergelassene Ärzte) to report hospitalizations of cases.

The RKI rolled out those profiles to production on March 16th.

As those profiles are also used for COVID-19, notifications using those profiles are also transmitted to SORMAS, where it has to be dealt with them.

As a first minimal step, there are some requirements to be fulfilled.

- Physicials reports must be distinguishable from lab messages in the SORMAS UI.
- It must not be possible to use them to create invalid states in the database (which currently includes processing them because they would currently be assigned to a sample, which is logically wrong)

### Feature Description

- [x] add a ExternalMessageType enum to the SORMAS API. It should have the values LAB_MESSAGE and PHYSICIANS_REPORT.
- [x] add a type atribute to the LabMessage dto and entity. It should be an ExternalMessageType.
- [x]  for all messages in the labmessage table of the sormas_db, set the type to LAB_MESSAGE. **EDIT**: Decided for a distinction instead, see [comment below](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8276#issuecomment-1092499813).
- [x] add another dropdown filter to lab message directory, which allows to filter for type
- [x] hide the process button for physician's reports
- [ ] add unit tests for the new functionalities as far as possible

### Possible Alternatives

[Input is welcome here]

### Additional Information

For end-to-end testing of this ticket, a tests environment and setup is necessary that supports physician's report. There currently is none.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa There will no migration be done for currently donwloaded physician's reports. They will show as lab messages and be processable (as they are now). Okay? Otherwise, it would not be so difficult to correctly set the type, but we would need a clear and easy way to identify them. Could we maybe search for a string that only occurs in all lab messages, but never in physicians reports? Then we could search the labMessageDetails for that and make the distinction there.

**Comment by FredrikSchaeferVitagroup** [comment]
> @kwa There will no migration be done for currently donwloaded physician's reports. They will show as lab messages and be processable (as they are now). Okay? Otherwise, it would not be so difficult to correctly set the type, but we would need a clear and easy way to identify them. Could we maybe search for a string that only occurs in all lab messages, but never in physicians reports? Then we could search the labMessageDetails for that and make the distinction there.

I now chose to search for `profile value="https://demis.rki.de/fhir/StructureDefinition/NotificationDiseaseCVDD"` in the lab message details. When this string exists there, the labmessage.type is set to PHYSICIANS_REPORT, otherwise to LAB_MESSAGE.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup It seems that for lab messages, `Composition.type.coding.code` is used (cf. https://simplifier.net/guide/ImplementierungsleitfadenfrDEMIS/Meldung?version=current) and always contains the value `34782-3`. In comparison, physician messages use `Composition.category.coding` instead (cf. https://simplifier.net/demisarztmeldung/notificationdisease). Might we be able to use that difference?

In the `Bundle.entry.resource`, they also differentiate the different profiles
- `NotificationLlaboratory` or `NotificationBundleLaboratory` (cf. https://simplifier.net/demis/NotificationBundleLaboratory/)
- `NotificationDisease` or `NotificationBundleDisease` (cf. https://simplifier.net/DEMISArztmeldung/NotificationBundleDisease/)

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 From what I can see in the links you provided, lab messages and physician's reports both set the `Composition.type.coding.code` to `34782-3`. So that seems not to be a good distinction.

My investigation also lead to deciding by the type of composition (your second suggestion). So I guess that's what we will do (for now).

**Comment by FredrikSchaeferVitagroup** [comment]
Should be tested together with [#56](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/56).
Should (soon) be testable on [test-de2](https://test-de2.sormas.netzlink.com/sormas-ui/) and locally.

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.71.0-SNAPSHOT (5a3dac2)
