### ISSUE TITLE
Add infrastructure data for Ghana

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#828]
Needed regional data:

- regions with population data, growth rate, epid code
- districts with population data, growth rate, epid code
- communities (in Ghana called sub-districts)
- region shapes
- district shapes
- health facilities (ideally with GPS)
- laboratories

### Implementation

General note: Administrative divisions (regions, districts, communities) are imported on server startup by the StartupShutdownService.startup() method. All data files are located in the sormas-backend project under srv/main/resources.  
The country used during import is defined by the sormas.properties file located in the folder of the sormas server domain.  
The easiest way to test the import is to TRUNCATE .. CASCADE the region and users table. This will also truncate all tables with references to those. Afterwards deploy the sormas-ear (which includes sormas-backend) to your server and StartupShutdownService.startup will automatically be called.

#### Administrative divisions:

- [x] add regions, districts and communities csv files for regions/ghana. This should follow the pattern of the existing files. Make sure to also include population and growth rate.

#### Facilities:

- [x] add health facility csv files for each region. Make sure that names of regions, districts and communities match the imported adminstratve division data.
- [ ] ~~add a Laboratories.csv file with all the laboratories~~

#### Shapes:

Region and district shapes are not stored in the database. Instead they are loaded when GeoShapeProviderEjb initializes and kept in memory for quick access.
See http://mapshaper.org/ for compression
Edit dbf files with https://sourceforge.net/projects/gtkdbfeditor/files/latest/download

- [x] add shape files for regions and districts. The dbf column can be called StateName or REGION. The import uses a very simple heuristic to find similar names that may get things wrong, so make sure names in the shapefiles match those of the actual adminstrative divisions. It would be good to have a more powerful import for this.

**Comment by MartinWahnschaffeSymeda** [comment]
[Health Facilities in Ghana.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2505967/Health.Facilities.in.Ghana.xlsx)
[Ghana Population.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2505968/Ghana.Population.xlsx)
[District population by age groups  2018.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2505969/District.population.by.age.groups.2018.xlsx)

**Comment by hzi-braunschweig** [comment]
[District population by sex age  groups 2018.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2533404/District.population.by.sex.age.groups.2018.xlsx)
@MartinWahnschaffeSymeda

**Comment by hzi-braunschweig** [comment]
https://mapcruzin.com/free-ghana-country-city-place-gis-shapefiles.htm

**Comment by faatihi** [comment]
Attached is csv files for regions, districts, communities, and facilities data from two regions; Volta and Brong Ahafo.

@MartinWahnschaffeSymeda, please go through them and give us feedback.

[ghana - regions & facilities of Volta, BAR.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/2576804/ghana.-.regions.facilities.of.Volta.BAR.zip)

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Looks perfect 👍

**Comment by faatihi** [comment]
> @faatihi Looks perfect 👍

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
[Ghana_216_districts.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/2686037/Ghana_216_districts.zip)
Shapefiles sent to me by David.

@faatihi I have had a quick look at the district shapefiles. As far as I can tell it should be possible to put them into the sormas-backend the same way this is done for nigeria.
Very important: Use mapshaper to simplify the shapes. You can use a setting of 3 to 5% of the original detail level. This should reduce the shapefile to a size of 500kb or less without causing a visible loss of detail.

@dta16 We currently only have district shapes. Do you have a tool that is able to create region shapes by connecting the provided district shapes?

**Comment by MartinWahnschaffeSymeda** [comment]
Region shapefiles: [gha_admbndp1_1m_gaul.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/2737033/gha_admbndp1_1m_gaul.zip)

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi 
I have compressed the shapfiles - this will improve load performance of the dashboard for national users

A few open points:

1. Looks like the shapefiles have a few entries that don't have a matching district: afadzatosouth, birimmunicipal, kma, afigyasekyere, mampongmunicipal, dormaamunicipal
2. No shape for districts found: Afadjato, Afigya-Kwabre, Afram Plains South, Agona East, Akatsi North, Akatsi South, Akwapim North, Akwapim South, Asante-Akim South, Asante-Mampong, Asikuma-Odoben-Brakwa, Atiwa, Atwima-Kwanwoma, Atwima-Wabiagya, Bawku West, Bekwai, Bia East, Bia West, Bibiani-Anhwiaso-Bekwai, Birim Central, Bosome-Freho, Bosomtwe, Central Tongu, Dormaa Central, East Akim, East Mamprusi, Fanteakwa, Ho West, Hohoe, Kassena-Nankana West, Ketu North, Ketu South, Kpandai, Krachi East, Krachi West, Kumasi, Kwabre East, Kwaebibirem, La-Nkwantanang-Madina, Mpohor, Nkoranza North, Nkoranza South, Nsawam-Adoagyiri, Obuasi, Offinso North, Sekyere-Kumawu, Sekyere South, South Tongu, Sunyani West, Tarkwa-Nsuaem, Techiman North, Twifu-Ati-Mokwa, Wa East, Wa West, Wassa-Amenfi Central, Wassa-Amenfi East, Wassa-Amenfi West, Wassa East, West Mamprusi 
3. Will you add laboratories for Ghana to the system or leave this aspect out?

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi We discussed this yesterday with Bernard. If we got it right there are only few laboratories so those can be added using the user interface.
It will likely not be possible to get the missing shapes, so we will leave it as is.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @faatihi But we need to add the health facilities data and population data to Ghana system
[Health Facilities in Ghana.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3117474/Health.Facilities.in.Ghana.xlsx)
[Ghana Population.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3117476/Ghana.Population.xlsx)

**Comment by faatihi** [comment]
The above pull request (#1107)  brings the missing districts down to one. The shapefiles is now missing only "Kwahu North" district.

**Comment by bernardsilenou** [comment]
I had a look at the cases on Ghana server and realized that  the infrastructure data in not correct. For example, there are many CSM cases created in Nadowli hospital but they appear in Accra. The coordinate for Nadowli hospital in SORMAS is 5.5705, -0.1887865 while on google map is 10.5584304,-2.9412188. We need to correct the infrastructure data for HFs

**Comment by MartinWahnschaffeSymeda** [comment]
Please create a new issue for this.
