### ISSUE TITLE
[Angular] Case Directory: Merge Duplicates - Merge guide [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8284]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ELxAKdA
- This pop-up will be loaded when clicking on the question mark near the page title

### QA Section

1. What should the QA look for (what was done)
- Check that the pop-up shows when clicking on the question mark
- Check that the content of the pop-up is similar to what we have on the current Sormas.

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done :
-"The Calculate Completeness button ..." paragraph is missing .

**Comment by RobertoDascalu** [comment]
Testing done - all good
