### ISSUE TITLE
Internationalization of SORMAS

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#829]
### Implementation

- [x] activate translation for SORMAS web app  
Properties fields in I18nProperties class in sormas-api probably need to be replaced by ResourceBundles. See https://docs.oracle.com/javase/tutorial/i18n/intro/steps.html  
Ideally the additional files would use "en_GH". A good candidate for testing is the CaseData.region entry.
- [x] ~~activate translation for SORMAS Android app~~
- [x] add actual translations for Ghana (will be provided by HZI)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Do you already have a list of all things in SORMAS that are supposed to have individual names for the Ghana version?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda As far as what we agreed in Ghana, We keep everything the same except for relabelling States LGAs and Wards to Regions, Districts and Sub-Districts. Based on the table below, we will use the generic labels for Ghana except for case supervisor which needs to be relabelled to Clinician

![image](https://user-images.githubusercontent.com/19344651/47290754-42461280-d601-11e8-98b9-c66c0f144ef3.png)

**Comment by MartinWahnschaffeSymeda** [comment]
We just realized that only the case supervisor was supposed to be renamed to clinician. All other user roles will keep there name (see HZI comment above).

- [ ] remove specific user role names
- [ ] rename case supervisor to clinician for all of SORMAS
- [ ] try to use full user role names instead of short ones
