### ISSUE TITLE
Automatic deletion should immediately do a permanent deletion [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8293]
### Feature Description
Currently the automatic deletion implemented by #7008 just does a soft-delete. Afterwards a dedicated job is run that deletes all soft-deleted entites, including the one that were manually deleted.

### Problem Description
Entities that were manually deleted should stay in the system for a period of time (e.g. 90 days for SORMAS in Germany), so a dedicated user can review the deletion and undo it if needed. In order to achieve this, we have to change the way automatic deletion and permanent deletion is done.

### Proposed Change

- [x] executeAutomaticDeletion (AbstractCoreFacade) should call deletePermanent instead of delete
- [x] automatic deletion should be done in batches, with each batch having a new transaction, to avoid timeouts
- [x] No longer call executePermanentDeletion in the CronService. We will probably no longer need this. There will be a separate issue that defines automatic deletion rules for manually deleted data.
- [x] Rename `executePermanentDeletion` in PersonService to `deleteUnreferencedPersons`
- [x] Don't call `executePermanentDeletion` for samples (because they're already deleted alongside their referenced entities) and lab messages

**Comment by mario-kuehne** [comment]
Testing with Version: 1.71.0-SNAPSHOT (9c0e90c)

Necessary configuration for testability:

- https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Feature-Configuration-Options (see `DELETE_PERMANENT`)
- https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_CUSTOMIZATION.md#deletion-configuration

**Comment by adinaflorea9** [comment]
@MateStrysewske Lab messages are permanently deleted only if they are unprocessed messages that have been first manually deleted from the UI (#8295)

Lab messages can not be permanently deleted via automatic deletion - both processed or unprocessed lab messages are not deleted when the 'Delete Expired Entities' job runs; for processed lab messages -> they are not permanently deleted even when all of the associated entities (including the person) are permanently deleted from the DB.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.72.0-SNAPSHOT(e6f0ecd).

Configurations necessary for testing:
1. In IntelliJ - CronService.java:
@schedule(hour = "", minute = "/5", persistent = false)
public void deleteExpiredEntities() {
System.out.print("------- Delete Expired Entities happened now -----");
coreEntityDeletionService.executeAutomaticDeletion();

2. In the Data Base: 'deleteconfiguration' folder:
- 'deletionreference' - CREATION for case, contact, event, event participant, immunization; - ORIGIN for travel entry;
- 'deletionperiod' - 2;
