### ISSUE TITLE
Automatic permanent deletion for manually deleted entities [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8295]
### Situation Description
So far automatic deletion just did a soft-delete and there was a separate process that permanently deletes all automatically AND manually soft-deleted entities once a night.
#8293 changes this, because we need to be able to handle manually deleted entities different then automatically deleted ones. Manually deleted entities should stay in the system for another 90 days (example for Germany), so that a user can review and undo the deletion.

### Feature Description
Introduce automatic permanent deletion of manually deleted entities using the existing system for automatic deletion introduced by #7008.

- [x] Extend the DeletionReference with a DELETION value
- [x] Extend the automatic deletion logic for the new deletion reference. The rule applies to all entities that were soft-deleted and should use their change date as reference date.
- [x] Remove the source code for executePermanentDeletion since it is no longer needed.
- [x] Turn lab messages into an ADO (i.e. remove the `deleted` field) and write a migration script that removes all deleted lab messages from the database
- [x] Remove no longer needed DELETE_PERMANENT feature type

**Comment by kwa20** [comment]
@MartinWahnschaffe Just a comprehension question: When `DELETE_PERMANENT` gets removed, how does someone prevent anything to be hard-deleted if it is not required for an instance?

**Comment by MateStrysewske** [comment]
@kwa20 Permanent deletion is only executed when the deletionconfiguration table is configured accordingly (i.e. there's a specified deletion period).

**Comment by MateStrysewske** [comment]
Reopening because we have exceptions when trying to access views in the web app with the new MANUAL_DELETION configurations not being set up (i.e. not having a deletion period).

**Comment by StefanKock** [comment]
Reported by @leventegal-she: f02d862 misses the removal of `DELETE_PERMANENT` in the android-app database:

```
de.symeda.sormas.app.rest.SynchronizeDataAsync$1: Error trying to synchronizing data in mode 'CompleteAndRepull'    de.symeda.sormas.app.backend.common.DaoException: Cannot get enum value of 'DELETE_PERMANENT' for field FieldType:name=featureType,class=FeatureConfiguration
        at de.symeda.sormas.app.backend.common.AbstractAdoDao.callBatchTasks(AbstractAdoDao.java:1311)
        at de.symeda.sormas.app.backend.common.AbstractAdoDao.deleteInvalid(AbstractAdoDao.java:1010)
        at de.symeda.sormas.app.rest.SynchronizeDataAsync.pullMissingAndDeleteInvalidInfrastructure(SynchronizeDataAsync.java:779)
        at de.symeda.sormas.app.rest.SynchronizeDataAsync.doInBackground(SynchronizeDataAsync.java:175)
        at de.symeda.sormas.app.rest.SynchronizeDataAsync$1.doInBackground(SynchronizeDataAsync.java:859)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
```

**Comment by AndyBakcsy-she** [comment]
Following scenarios have been tested:

1.Cases
1.1 Simple case
1.2 Case with Contact
1.3 Case with event
1.4 Case with immunization
1.5 Case with Travel entry
1.6 Case from contact

2.Contacts
2.1 Contact simple 
2.2 Contact with immunisation
2.3 Contact with task
2.4 Contact with sample
2.5 Contact with Event -gets the original changedate somehow
2.6 Contact with Source Case
2.7 Contact converted to case

3.Events  -Not ok needs discussions with Developers !!! 
3.1 Simple event deleted manually 
3.2 Simple event with different disease
3.3 Simple event with event participant( does not get deleted unless the event participant gets deleted)

**Comment by adinaflorea9** [comment]
**Lab messages**: 

I: Manually deleting an unprocessed lab message from the UI leads to the lab message being permanently deleted from the DB as well; but for a process lab message the permanent deletion does not happen (**processed lab messages can not be manually deleted from the UI**); 

II: When trying to delete a processed or unprocessed lab message from the DB, in PGAdmin a notification pops up and the lab message can not be deleted:
![image](https://user-images.githubusercontent.com/96909231/167407703-7529df77-8d56-40e1-b331-20325630045d.png)
