### ISSUE TITLE
Make user rights of user roles configurable [1+3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#830]
First step: Get the actual specifications from Ghana Health Services.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym  @bernardsilenou Ghana has sent us their user right based on the data dictionary doc i sent to them. We will need to make this a configurable engine so they can switch on and switch off rights for all users in the system. We should discuss this
[SORMAS Data Dictionary-reviewed GHANA.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2505883/SORMAS.Data.Dictionary-reviewed.GHANA.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
Please have a look at this:

- [ ] Create a sheet with the current user rights (rows) and user roles (columns) and how they are related
- [ ] Compare with the data from GHS and see where it differs

**Comment by MartinWahnschaffeSymeda** [comment]
This is the list of actual differences:

Create & edit case:
ConOff -> NO

Archive cases:
SurvSup, CaseSup, NatUser -> YES

Edit tasks:
Informants, SurvOff, ContOff, CaseOff, RumOff -> NO

View events:
LabMan -> YES

Create weekly reports:
Everyone -> YES

View weekly reports:
Everyone -> YES

Edit weekly reports (why?):
Everyone -> YES

Delete weekly reports (why?):
Admins

Create/Edit infrastructure:
SurvSup -> YES

View infrastructure:
Everyone -> YES

**Comment by MartinWahnschaffeSymeda** [comment]
We discussed this today with Daniel:

- [ ] add user role community informant (existing informant should be renamed to hospital informant). Needs to be assigned to a community. TODO: Define what this means for reports
- [ ] add user role for district observer
- [ ] add user interface to edit assigment of user rights to user roles
- [ ] implement backend for this -> transfer configruation to app
- [ ] default configuration

**Comment by MartinWahnschaffeSymeda** [comment]
```
/opt/payara-172/glassfish/bin/asadmin --port 6048 delete-auth-realm sormas-realm
/opt/payara-172/glassfish/bin/asadmin --port 6048 create-auth-realm --classname org.wamblee.glassfish.auth.FlexibleJdbcRealm --property "jaas.context=sormasRealm:sql.password=SELECT password FROM users WHERE username\=? AND aktiv\=true:sql.groups=SELECT userrole FROM users_userroles INNER JOIN users ON users_userroles.user_id\=users.id WHERE users.username\=?:sql.seed=SELECT seed FROM users WHERE username\=?:datasource.jndi=jdbc/sormasUsersDataPool:assign-groups=AUTHED_USER:password.digest=SHA-256:charset=UTF-8" sormas-realm
/opt/payara-172/glassfish/bin/asadmin --port 6048 set server-config.security-service.default-realm=sormas-realm

C:/srv/payara-172/glassfish/bin/asadmin --port 6048 delete-auth-realm sormas-realm
C:/srv/payara-172/glassfish/bin/asadmin --port 6048 create-auth-realm --classname org.wamblee.glassfish.auth.FlexibleJdbcRealm --property "jaas.context=sormasRealm:sql.password=SELECT password FROM users WHERE username\=? AND aktiv\=true:sql.groups=SELECT userrole FROM users_userroles INNER JOIN users ON users_userroles.user_id\=users.id WHERE users.username\=?:sql.seed=SELECT seed FROM users WHERE username\=?:datasource.jndi=jdbc/sormasUsersDataPool:assign-groups=AUTHED_USER:password.digest=SHA-256:charset=UTF-8" sormas-realm
C:/srv/payara-172/glassfish/bin/asadmin --port 6048 set server-config.security-service.default-realm=sormas-realm
```

**Comment by MartinWahnschaffeSymeda** [comment]
Two things left to consider:

- [ ] how to remove invalid user config from mobile device? We probably need to do a "complete" pull once a day
- [ ] user rights are not fully implemented in app, because it was not relevant for the existing default user rights.

**Comment by MateStrysewskeSym** [comment]
- [ ] add realm configuration change to server update notes
