### ISSUE TITLE
[Contacts] 'Follow-up status comment' content is duplicated when merging contacts that have resulting cases

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8312]
### Bug Description

The 'Follow-up status comment' content is duplicated in the preserved contact, when 2 duplicate contacts are merged, if one or both of them have a resulting case.

### Steps to Reproduce

1. Create 2 contacts with identical information ('Contact1' and 'Contact2') and set the same 'Source Case' for them;
2. Create a resulting case for 'Contact1';
3. Merge 'Contact 1' into 'Contact2';
4. Observe the 'Follow-up status comment' of the preserved contact ('Contact2').

### Actual Behavior

The 'Follow-up status comment' content is duplicated.

### Expected Behavior

The 'Follow-up status comment' content is not duplicated.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/157462456-ab31ec0d-2e24-45c8-9631-32792a437542.png)

GIF of the behavior:
![Follow-up comment contact](https://user-images.githubusercontent.com/96909231/157462313-dcd5485e-04ff-405d-a2b7-2c5147be2e06.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(83ee062)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT from the development branch (bddef5b).
