### ISSUE TITLE
Some fields do not get merged from the unpreserved Case / Contact into the preserved one

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8315]
### Bug Description
There are some fields from the Case / Contact page that do not get merged from the unpreserved Case / Contact into the preserved one:

Cases:
- [ ] 'Resulted from nosocomial outbreak' checkbox and 'Infection setting';
- [ ] 'Share this case with the whole country' checkbox;
- [ ] 'Quarantine ordered verbally' checkbox and 'Date of the verbal order';
- [ ] 'Quarantine ordered by official document' checkbox and 'Date of the official document order';
- [ ] 'Official quarantine order sent' checkbox and ' Date official quarantine order was sent';
- [ ] Case Person page: 'Facility Name & Description', 'Street', 'House Number', 'Additional information', 'Postal Code', 'City', 'Contact person first name', 'Contact person last name', 'Contact person phone number', 'Contact person email address';

Contacts:
- [ ] 'Quarantine ordered verbally' checkbox and 'Date of the verbal order';
- [ ] 'Quarantine ordered by official document' checkbox and 'Date of the official document order';
- [ ] 'Official quarantine order sent' checkbox and ' Date official quarantine order was sent'; '
- [ ] 'High priority contact' checkbox;

### Steps to Reproduce

1. Create 2 duplicate Cases or Contacts;
2. In one of the Cases / Contacts fill in the fields mentioned above (in the Bug Description);
3. In the other Case / Contact leave those fields empty;
4. Go to Cases / Contacts Directory and go to Merge Duplicates;
5. Merge the unpreserved Case / Contact (the one with the populated fields) into the preserved Case / Contact;
6. Open the preserved Case / Contact and inspect those fields;

### Actual Behavior
The fields mentioned in the Bug Description are not populated with the input from the unpreserved Case / Contact.

### Expected Behavior
The fields mentioned in the Bug Description should be populated with the input from the unpreserved Case / Contact.

### Screenshots

Unpreserved Case before merge:
![image](https://user-images.githubusercontent.com/89522688/157467756-ae29b83d-10ed-41df-8449-1bb442649cbe.png)
![image](https://user-images.githubusercontent.com/89522688/157669315-5bb9bc55-b5ee-450d-8312-de9b26efa71f.png)

Preserved Case after merge:
![image](https://user-images.githubusercontent.com/89522688/157467934-69d4ff15-57b7-47d5-8d00-6dc89c6c9305.png)
![image](https://user-images.githubusercontent.com/89522688/157669371-5af15995-7895-4003-8598-f1826bf4919d.png)

Unpreserved Contact before merge:
![image](https://user-images.githubusercontent.com/89522688/157468313-b9affe6b-6d6f-4c6a-9645-b3a34c7579ad.png)

Preserved Contact after merge:
![image](https://user-images.githubusercontent.com/89522688/157468497-d309b5be-eb7a-49f2-a0fd-34c40651f2c6.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.70.0-SNAPSHOT (bb551be)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Admin, NatUser

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.70.0-SNAPSHOT(231D303).
