### ISSUE TITLE
Entering a home address when processing lab messages nulls the address that would be mapped

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8319]
### Bug Description

When a user processes a lab message and checks the box "Enter home address of the case person now", the home address is not adopted from the message into the respective fields and even though these fields are usually mapped, enabling the fields in the case creation form nulls the entries and saving results in the person losing this information.
### Steps to Reproduce

1. Process a lab message
2. Create a new person
3. Create a new case
4. Check the box "Enter home address of the case person now"
5. Check fields but don't fill them
6. Save the case and finish processing
7. Check the resulting case person
8. As a control, repeat the steps with another message but do not check the box "Enter home address of the case person now"
9. Check the case persons home address again

### Expected Behavior

- The home address fields should be filled in the creation form and therefore not null the mapped data.

### Screenshots

![labMessageHomeAddressNull](https://user-images.githubusercontent.com/70317594/157620245-5becd35f-7bac-4c68-83dc-f34ea51f1c68.gif)

### System Details

* Device:
* SORMAS version: 1.68.3/1.69.0
* DEMIS Adapter: 1.13.0/1.14.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by vidi42** [comment]
@kwa20 looking over this issue, there are some things that should be clarified:

1. Was the behavior described as not working correctly described in a different ticket? I see that the Home address form was introduced in https://github.com/hzi-braunschweig/SORMAS-Project/issues/7064, but I cannot find any ticket related to how it should be adapted for the Lab messages so my assumption is that this was not working before either.

2. Saving a person when the `Enter home address of the case person now` is unchecked will result in either saving the person's address from the lab message if the person is new or keeping the person's address if an existing person is selected. 
My assumption is that we also want to keep this behavior as the "bug" mostly refers to the first point.

Given these points, I can provide a fix for the first part, which will pre-fill the Home address fields with data from the lab message whenever a new person is created from processing a lab message. The behavior for point 2 will stay the same.

If something more has to be done, we have to look at the original ticket which describes this flow or open a new change request with more details.

**Comment by JaquM-HZI** [comment]
@vidi42 
I can't find the issue to the previous behavior. Until now the address was simply taken over, no input or correction was possible under the case creation form. Now the address is not taken over as soon as the checkbox is selected. It is correct that the feature was newly added and no change was described to take over the address from the Lab Messages within the new address checkbox. The overwriting with null is the existing bug, what should be implemented in this framework in addition, as already named by you, is the takeover of the address, if the checkbox was selected for input in the case creation form.

**Comment by vidi42** [comment]
@JaquM-HZI A correction to the 2nd point is that now for new persons if the `Enter home address of the case person now` is unchecked the address will be empty as it gets cleared when the form is hidden. For existing persons it will always be unchecked and disabled, but the person's address will be kept.

We tested it together with @abrudanancuta and this behavior seems natural now

**Comment by vidi42** [comment]
I will change this to a change request since by the looks of the code this was not implemented before
