### ISSUE TITLE
The task assignee can be set to null via bulk edit mode

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8326]
### Bug Description

The task assignee can be set to null via the bulk edit mode.
### Steps to Reproduce

1. Create a case and create any task for that case
2. Set any assignee
3. Navigate to the task management and enter the bulk edit mode
4. Select the created task
5. in the bulk action, change the task assignee
6. Leave the task assignee empty and save

### Expected Behavior

The task assignee should not be nullable via bulk actions since it contradicts the validation in the task create/edit form.

### Screenshots

![TaskAssigneeNull](https://user-images.githubusercontent.com/70317594/157656114-9d33582b-ef6a-4ca6-81e5-d94911c3c924.gif)

### System Details

* Device:
* SORMAS version: 1.68.3/1.69.0
* Android version/Browser: chrome
* Server URL: int-sormas-x.sormas.netzlink.com/test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.70.0-SNAPSHOT (077981e) from the development branch.
