### ISSUE TITLE
New disease: Anthrax

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#833]
Details still need to be specified.

**Comment by hzi-braunschweig** [comment]
[Anthrax-ProcessModel_Ghana_gek_181011_dta.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2491464/Anthrax-ProcessModel_Ghana_gek_181011_dta.xlsx)

**Comment by faatihi** [comment]
Is this issue ready for implementation?

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi @opatajoshua FYI: Bernard plans to finish the definition of Anthrax tomorrow evening.

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou What about the Anthrax definition?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Reminder..

**Comment by hzi-braunschweig** [comment]
[SORMAS_Data_Dictionary_Anthrax_dta_191022.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3762493/SORMAS_Data_Dictionary_Anthrax_dta_191022.xlsx)
See attached first review. I have sent it to my colleagues, and will get some feedback from then soon. I have told them its urgent.

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi 
I have updated the data dictionary with a column for Anthrax in the symptoms and epi data sheets.
This makes it a bit easier to find the relevant fields: 
[SORMAS_Data_Dictionary_Anthrax_dta_191022.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3790289/SORMAS_Data_Dictionary_Anthrax_dta_191022.xlsx)



Field | Type | Caption
-- | -- | --
abdominalPain | SymptomState | Abdominal pain
bloodInStool | SymptomState | Blood in stool
bloodPressureDiastolic | number | Blood pressure (diastolic)
bloodPressureSystolic | number | Blood pressure (systolic)
bloodUrine | SymptomState | Blood in urine (hematuria)
chestPain | SymptomState | Chest pain
chillsSweats | SymptomState | Chills or sweats
fatigueWeakness | SymptomState | Fatigue/general weakness
fever | SymptomState | Fever
headache | SymptomState | Headache
injectionSiteBleeding | SymptomState | Bleeding from injection site
lesions | SymptomState | Vesiculopustular rash
lesionsAllOverBody | true, false | All over the body
lesionsArms | true, false | Arms
lesionsDeepProfound | SymptomState | Rash lesions deep and profound?
lesionsOnsetDate | date | Date of rash onset
lesionsThatItch | SymptomState | Rash that itches
lossSkinTurgor | SymptomState | Loss of skin turgor
musclePain | SymptomState | Muscle pain
nausea | SymptomState | Nausea
shock | SymptomState | Shock (Systolic bp <90)
sidePain | SymptomState | Side pain
skinBruising | SymptomState | Bruising of the skin (petechiae/ecchymosis)
skinRash | SymptomState | Maculopapular rash
unexplainedBleeding | SymptomState | Bleeding or bruising
vomiting | SymptomState | Vomiting


Field | Type | Caption
-- | -- | --
gatheringAttended | YesNoUnknown | Visited a social event
traveled | YesNoUnknown | Traveled
gatherings |   | Social events
processingSuspectedCaseSampleUnsafe | YesNoUnknown | Handling samples (animal or human) suspected of containing the   virus without adequate personal protection
areaInfectedAnimals | YesNoUnknown | Exposure (e.g. handling, butchering) to animals (or their   remains) in an area where infected animals have been confirmed in the past   month
sickDeadAnimals | YesNoUnknown | Exposure to sick/unxeplainedly dead animals
sickDeadAnimalsDetails | text | Specify dead animal exposure
sickDeadAnimalsDate | date | Date of dead animal exposure
sickDeadAnimalsLocation | text | Place of dead animal exposure
eatingRawAnimalsInInfectedArea | YesNoUnknown | Eating raw or undercooked animal products in an area where   infected animals have been confirmed
eatingRawAnimals | YesNoUnknown | Eating raw or undercooked animal products
eatingRawAnimalsDetails | text | Specify eaten animal product
rodents | YesNoUnknown | Rodents or their excreta
bats | YesNoUnknown | Bats or their excreta
primates | YesNoUnknown | Primates (monkeys)
swine | YesNoUnknown | Swine
birds | YesNoUnknown | Poultry or wild birds
cattle | YesNoUnknown | Cattle
otherAnimals | YesNoUnknown | Other animals
otherAnimalsDetails | text | Specify other animals
waterSource | WaterSource | Source of drinking water
waterSourceOther | text | Specify
waterBody | YesNoUnknown | Contact with body of water
waterBodyDetails | text | Name and location of water
dateOfLastExposure | date | Date of last exposure
placeOfLastExposure | text | Place of last exposure
animalCondition | AnimalCondition | Condition of animal last exposed to

**Comment by bernardsilenou** [comment]
@ Everybody
I have updated the previous excel file uploaded by  Martin on 30/10/2019. 
@faatihi  Please use this version to add Anthrax in SORMAS. Some fields have been deleted and others added from the previous data dictionary. You will easily identify the needed fields because they have a red background.
The case definition, definition of sub-types, type of lab tests and response measures will follow latter, so we will not have automatic case classification for now.
[SORMAS_Data_Dictionary_Anthrax_dta_191022_bsi.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3808345/SORMAS_Data_Dictionary_Anthrax_dta_191022_bsi.xlsx)
