### ISSUE TITLE
Vaccinations are duplicated when merging cases or contacts

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#8333]
### Bug Description
When two cases (both cases have an added vaccination) are merged, the result of the merge should contain 2 vaccinations but besides the two vaccinations also a new ( third ) vaccination will be added to the vaccinations' list.

### Steps to Reproduce

The problem appears in the following scenarios:

1)Merge of the cases
Merge of 2 cases (both case have one vaccinations)
Merge of one case without vaccination with another case with vaccination ( The merge will be clicked on the case without vaccination)

2)Merge of the contacts
- the same as the description for Merge of the cases

Steps for recreating the bug in case of merging two cases (both cases will have one vaccination)
**1. Create a new case with all the mandatory fields filled out.**
Example screenshot:
![creation](https://user-images.githubusercontent.com/47103965/157707485-5fcccd9f-ca36-4ff4-8e2a-401e0390c598.PNG)
Add a vaccination to the created case.

Example of the created case and added vaccination:  
Created case: VCNMTG
Added vaccinations to VCNMTG case: REZPI5 (vaccination date 3/1/2022)

**2. Similarly create a new case with all the mandatory fields filled out.**
Add a new vaccination to the case.

Example of the created case and added vaccination:  
Created case: UU335O
Added vaccinations to UU335Ocase: T724JZ(vaccination date 3/2/2022)

**3) Merge the 2 cases ( click the merge next to the first case  VCNMTG)**
   Instead of 2 vaccinations, 3 vaccinations will appear.
 
![image](https://user-images.githubusercontent.com/47103965/157708923-9d3ccde2-a2ab-48d7-b8ef-68963d04823d.png)

### Expected Behavior
  The outcome of the vaccinations' list should be : REZPI5 , T724JZ but a new vaccination will also appear ( in the example is RFQ4I5 which will have the same date as T724JZ)

### System Details  locally

* Device:
* SORMAS version:   1.69.0-SNAPSHOT
* Android version/Browser:  Chrome
* Server URL:  
* User Role:  admin

### Additional Information
The problem appears in case of merging the contacts too : the merged contact's vaccination list will contain also some vaccinations which should not be part of the list.

**Comment by MateStrysewske** [comment]
See #8096

**Comment by MateStrysewske** [comment]
See #8498 as well

**Comment by AndyBakcsy-she** [comment]
Started verifying the ticket on local environment using the latest 1.70.0-snapshot version of sormas.
The CASES part of this issue is fixed and I was able to validate it.
The Contacts part of this ticket on the other hand, I was not able to get Sormas to recognize 2 similar Contacts as possible duplicates.
