### ISSUE TITLE
Type of contact gets deleted after saving contacts on mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#8336]
### Steps to Reproduce

1.  create a contact and set type pf contact to touch fluid + save + move to person tab
2. return back to contact tab, type of contact has disappeared on ui

### Expected Behavior

-  Type of contact should persis  after the contact form is saved
### System Details

* Device: Samsung galaxy Tab A 11
* SORMAS version: 1.69
* Android version/Browser: 11
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: Surveillance officer + limited disease right

**Comment by AndyBakcsy-she** [comment]
Validated ticket on android studio using the latest version of Sormas Version: 1.70.0-SNAPSHOT ([6a278e2]https://github.com/hzi-braunschweig/SORMAS-Project/commits/6a278e25a6278d1e81335c1ba1f9050f45f496e0)
