### ISSUE TITLE
Do not suggest the same person as duplicate when converting event participant to case: mobile app

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#8338]
### Steps to Reproduce

1. create an event participant, use a name that is so distinct from all other persons to be sure that the person is unique in the db
2. convert the ep to case
3. system suggest the same person as a duplicate to you

### Expected Behavior

-  when suggesting duplicated persons, exclude the person  linked to the entity in question OR do not suggest  persons with the same uuid as the person of the ep
### System Details

* Device: Samsung galaxy
* SORMAS version: 1.69
* Android version/Browser: 11
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: surveillance officer  + limited disease ==  ebola

**Comment by bernardsilenou** [comment]
This is not severe because even if the user chose to create a new person, the system does not create a new person. But it would be good not to even ask the user in the first place.

**Comment by adinaflorea9** [comment]
Verified ticket on test.sormas.netzlink.com (as this environment is configured similar to the one logged in the ticket), using SORMAS version 1.71.0-SNAPSHOT.

APK download: https://test.sormas.netzlink.com/downloads/debug/

Server URL: https://test.sormas.netzlink.com/sormas-rest/
