### ISSUE TITLE
Mobile app crashes when event participant linked to an event without a disease is converted to case 

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#8339]
### Steps to Reproduce

1. create an event without a disease + ep
2. convert ep to case 
3. app closes

### Expected Behavior

If the event does not have a disease and the user click on "create a case for this event person", do not check for duplicate person but show a warning message   "It is not possible to create a case for an event participant if the disease to the event has not been set"
### System Details

* Device: Samsung galaxy
* SORMAS version:  1.69
* Android version/Browser: 11
* Server URL: https://release-international.sormas.netzlink.com/
* User Role: surveillance officer + limited disease == ebola

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server https://test-de1.sormas.netzlink.com/sormas-rest/ using the version Sormas 1.71.0-SNAPSHOT (98dcdef).
