### ISSUE TITLE
New disease: Human rabies

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#834]
Details still need to be specified.

**Comment by hzi-braunschweig** [comment]
[Rabies-ProcessModel_Ghana_gek_181011.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2491460/Rabies-ProcessModel_Ghana_gek_181011.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig This (and Anthrax) needs a more detailed implementation plan. 

1. We need to clearly define which fields have to be added to the system and which existing fields we use (see https://github.com/hzi-braunschweig/SORMAS-Project/raw/development/sormas-base/doc/SormasDictionary.xlsx).
2. Is there anything that needs to be implemented for the process? E.g. new task types, automatic generated tasks, etc.?

**Comment by faatihi** [comment]
Is this issue ready for implementation?

**Comment by hzi-braunschweig** [comment]
[Anthrax_Rabies_Table_jdo_190116_DTA_adk.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3426766/Anthrax_Rabies_Table_jdo_190116_DTA_adk.xlsx)
@faatihi You can start taking a look at this document. @MartinWahnschaffeSymeda Will the case classification be handled by GCNET or this is separate from the actual development of the new diseases?

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig This should be part of adding a new disease.

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/62534585-064f0780-b839-11e9-9c00-5a0351ed824e.png)

This link is broken. Is it no longer relevant?

**Comment by MartinWahnschaffeSymeda** [comment]
Sorry, the document was moved. Still very (!) relevant:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_Data_Dictionary.xlsx?raw=true

**Comment by faatihi** [comment]
thanks

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/64181267-ab1f2d80-ce55-11e9-8197-8d3f10842f89.png)

The "Which vaccine", I guess its a new field to be added

**Comment by faatihi** [comment]
I figured there's currently no easy way to exclude individual enum items (or, from a user's perspective, dropdown items) for a disease.

For example, under SampleMaterial, the following are not needed in Rabies cases; Stool, Nasal swab, Nasopharyngeal swab, Crust.

Because of that, I haven't worked on these sections for Rabies; Case Classification, Contact tracing, Sample Material, Sample Test type.

I would like to know how to go about this.

**Comment by MateStrysewskeSym** [comment]
* We currently don't restrict the Sample Material or Pathogen Test Type based on the disease; this will be changed in the future. If a new Sample Material or Pathogen Test Type is needed for Rabies, just go ahead and add it.
* We use (and will continue to use) the same Case Classification for all diseases (because this is very important to have a unified process in SORMAS)
* I'm not sure what you would have to add concerning contact tracing? What's your issue with that topic?

**Comment by faatihi** [comment]
I think I'm now OK on Contact Tracing. It's already available for all diseases, so there's nothing I need to do.

One other thing. In the excel, we have various institutions (RKI, NCDC, Ghana, CDC, WHO) deciding whether a feature should be included in a new disease. I decided to include a feature when at least one institution ticks Yes, and only exclude a feature when all say No. Is that OK?

**Comment by MateStrysewskeSym** [comment]
That's not for me to decide - @hzi-braunschweig please elaborate

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/64270024-65806480-cf2a-11e9-99a3-a77a8801a090.png)

I'm adding a new data, KindOfExposure, as enum. It'll be a field in EpiData. But I'm getting a second feeling that it should just be YesNoUnknown fields in EpiData

**Comment by MateStrysewskeSym** [comment]
Lists are pretty complicated to display in the UI though - so if the kind of exposure is not exclusive, I'd prefer to have multiple YesNoUnknown fields as you pointed out.

**Comment by faatihi** [comment]
OK

**Comment by faatihi** [comment]
There's an entry:
Post-exposure prophylaxis. Comments: Rabies vaccine + tetanus vaccination if no current status, before symptom onset.

Question: How are we going to capture this one? It looks like a type of vaccination. If so, we'll need an enum of VaccinationType. Right?

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Can you elaborate? I don't really understand the description in the first place. Should this be part of the epi data or of the vaccination information of the case? How exactly should this field look like?

**Comment by faatihi** [comment]
Hi @hzi-braunschweig , @MateStrysewskeSym . How far with the clarifications

**Comment by hzi-braunschweig** [comment]
@bernardsilenou Please answer these questions accordingly so they can finish up the rabies development. @MateStrysewskeSym  Please confirm if there has been any pull requests for Anthrax 

Thank you

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig No, there haven't been any pull requests (since the Ghana developers still wait for the specifications as far as I know)

**Comment by bernardsilenou** [comment]
@faatihi  
I have attached a new column called "combined". Generally all was fine, I have few comments only on cells that might need changes.

**Comment by faatihi** [comment]
Thanks

**Comment by faatihi** [comment]
...and as discussed on Post-exposure prophylaxis, I'll do the ff:
1. Use YesNoUnknown for Post-exposure prophylaxis
2. Only show this field when person has contact with infected animal
3. Show date of prophylaxis when Yes is selected.

**Comment by faatihi** [comment]
> @faatihi
> I have attached a new column called "combined". Generally all was fine, I have few comments only on cells that might need changes.

@bernardsilenou Kindly send me link to the excel file

**Comment by bernardsilenou** [comment]
So sorry I forgot to attache
[Anthrax_Rabies_Table_jdo_190116_DTA_adk_bsi.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/3700010/Anthrax_Rabies_Table_jdo_190116_DTA_adk_bsi.xlsx)

**Comment by faatihi** [comment]
Thanks

**Comment by faatihi** [comment]
![image](https://user-images.githubusercontent.com/1176692/66410062-00b0a200-e9e1-11e9-9890-77241ebbf696.png)

In the Anthrax_Rabies_Table/Rabies, RKI jotted "Organ Transplantation" under EpiData.
Where do I put it. I'm thinking, the list under "Kind of Exposure"

![image](https://user-images.githubusercontent.com/1176692/66410310-6f8dfb00-e9e1-11e9-9b8e-a8b255527fb7.png)

**Comment by MateStrysewskeSym** [comment]
@faatihi I think "Kind of Exposure" is more suited towards contact with animals. @hzi-braunschweig Please make a suggestion

**Comment by bernardsilenou** [comment]
@faatihi:  Mate is right, "Kind of Exposure" ismore about animals, environment, etc
Organ transplantation here refers to  situation where the case person might have gotten an organ from a donor who was infected.
Please drop this variable "Organ transplantation" for now

**Comment by faatihi** [comment]
Thanks. We ignore "Organ transplantation" for now

**Comment by MateStrysewskeSym** [comment]
- [ ] add comment to app FieldHelper.iteratePropertyFields method and explain the attributes
