### ISSUE TITLE
Region-District-Community filters should take into account both the ‘Responsible jurisdiction’ and the ‘Place of stay’ of a case

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8347]
### Bug Description

When trying to filter tasks, cases and samples based on ‘region’ and ‘district’ the results are based on the values for ‘region’ and ‘district’ that are associated with the ‘Place of stay’ only.

Therefore, when a case has a different address for the ‘Place of stay’ than the responsible jurisdiction, the user can only filter results based on the values associated with the ‘Place of stay’.

### Steps to Reproduce

1. Open the ‘Create new case’ form;
2. Set the ‘Responsible jurisdiction’ (‘Region’ - Baden-Württemberg; ‘District’ - LK Alb-Donau-Kreis);
3. Check the checkbox for ‘Place of stay of this case differs from its responsible jurisdiction’;
4. Set the ‘Place of stay’ (‘Place of stay’ – ‘Home’; ‘Region’ – Bayern; ‘District’ - LK Aichach-Friedberg);
5. Fill in the rest of the mandatory data and save the case.
6. In the ‘Cases’ directory, for the ‘Region’ and ‘District’ filters select the values that were inputted at step 2;
7. Click ‘Apply Filters’.

### Actual Behavior

The case created through the steps to reproduce is not displayed among the list of results, based on the filters selected at step 6.

### Expected Behavior

Results should be displayed when the user filters both by the values from 'Responsible Jurisdiction' and those from the 'Place of stay'.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/157849330-71a8d48e-fdc0-43aa-8d82-1afffd990f64.png)

![image](https://user-images.githubusercontent.com/96909231/157849465-dff500ea-2cb1-48b0-9b1a-11197919bdfc.png)

![image](https://user-images.githubusercontent.com/96909231/157849559-309ad54c-9894-4726-b223-39f2600f9c8f.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(1bf192a)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

The same behavior can be observed in the 'Tasks' and 'Samples' directories.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch – 1.71.0-SNAPSHOT(1dc6c47).

As discussed with @MateStrysewske I am reopening the ticket due to the following flows:

I: Contacts directory
1. Create a case whose ‘Responsible jurisdiction’ and ‘Place of stay’ differ (different values for region-district-community);
2. Create a contact with no responsible jurisdiction, but with a source case (the case created at step 1);
3. In the ‘Contacts’ directory, search for the contact from step 2 by using the region-district-community filters and the values of the responsible jurisdiction of the source case.
=> the contact is not listed among the results; the filters only take into account the region-district-community of the ‘place of stay’ of the source case.

Expected behavior: In the ‘Contacts’ directory, the filters for region-district-community should take into account both the responsible jurisdiction and the place of stay of the source case of a contact.

II: Samples directory
1. Create a case whose ‘Responsible jurisdiction’ and ‘Place of stay’ differ (different values for region-district-community);
2. Create a contact with no responsible jurisdiction, but with a source case (the case created at step 1);
3. Add a sample to the contact created at step 2;
4. Navigate to the ‘Samples directory’; 
5. Search for the sample by using the region-district filters and the values of the responsible jurisdiction of the source case.
=> the sample is not listed among the results; the filters for region-district only take into account the values of the ‘place of stay’ of the source case.

Expected behavior: in the ‘Samples’ directory, the filters for region-district should take into account both the responsible jurisdiction and the place of stay of a source case, associated with a contact that has a sample.

III: Samples directory
1. Create a contact that has its own responsible jurisdiction;
2. Add a sample with a positive pathogen test result to the contact created at step 1;
3. Select ‘Yes’ in the pop-up that is triggered after saving the sample;
4. In the ‘Create new case’ form fill in the mandatory information and set different values for the ‘Responsible jurisdiction’ and ‘Place of stay’ of the resulting case;
5. Navigate to the ‘Samples’ directory;
6. Search for the sample from step 2 by using the region-district filters and the values of the responsible jurisdiction of the contact from step 1.
=> the sample is not listed among the results; the filters for region-district only take into account the responsible jurisdiction and place of stay of the resulting case.

Expected behavior: in the ‘Samples’ directory, the filters for region-district should take into account the responsible jurisdiction of the contact associated with the respective sample, the responsible jurisdiction and the place of stay of the resulting case.

**Comment by BarnaBartha** [comment]
@adinaflorea9 @MateStrysewske Point III should also be extended to contact and task directory (that is consider the region / responsible Region of the contacts resulting case) ?

**Comment by MateStrysewske** [comment]
@BarnaBartha For the task directory I'd say so; for the contact directory I'm not sure, as it could be confusing for the users to see contacts there that DO have a responsible region and district which is different from the specified ones, but are still showing up because of their source cases. I would say there we should only take the case jurisdiction into account if the contact does not have one.

**Comment by BarnaBartha** [comment]
@MateStrysewske but it doesn't make sense if based on a contact i see the sample/task but don't actually see that contact when searching for it in the contact directory

**Comment by MateStrysewske** [comment]
@BarnaBartha Yeah, good point. Let's do it consistently then and display them in the contact directory as well.

**Comment by BarnaBartha** [comment]
New clarification parts of issue have been moved to #8911

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS  from the development branch - 1.71.0-SNAPSHOT(78596ba). Ticket #8911 covers the flows reported when the current ticket was reopened.

**Comment by AliciaRaber** [comment]
Tested on test1401.sormas-oegd.de V172.1. If case person is displayed via search for jurisdiction you can also find the person when place of stay is entered in case and search fields are entered properly.

Search for entered jurisdiction data:
![image](https://user-images.githubusercontent.com/91321821/172863397-e08d22ab-2a00-4d67-a675-0c6f61c62c01.png)

Search for place of stay data:
![image](https://user-images.githubusercontent.com/91321821/172863598-942e0782-3be5-48b6-a412-5a8793e1c1f7.png)
