### ISSUE TITLE
Dashboard changes for Ghana SORMAS version

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#835]
We need to discuss this. 
![our-proposed-dashboard-for-non-technical-stakeholders](https://user-images.githubusercontent.com/19344651/47151596-760bfa00-d2da-11e8-8f34-8d94429dae59.jpg)
[Ghana_District_Codes (1).xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2491659/Ghana_District_Codes.1.xlsx)
@MartinWahnschaffeSymeda @MateStrysewskeSym @SeriousMartin

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym @bernardsilenou 
We had a discussion at HZI about the dashboard for SORMAS and below is a workable mockup to give you an idea of what Gerard understands from the ghana dashboard for NON-TECHNICAL STAKEHOLDERS. We are still discussing this but I felt you should all know the progress and see what you can integrate based on this idea. 

Please note, the current dashboard remains but should only be for a filtered disease. The dashboard below is only for an unfiltered view when no disease is selected. Which means an overview of the current situation at any point in time. Let me know if you have any questions and so I can relay it back to the team. 

![sormas ghana dashboard](https://user-images.githubusercontent.com/19344651/47356606-de851d80-d6c4-11e8-86e5-7266e92cffd5.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym . So i made some changes to the dashbaord attached. We can discuss details tommorow. 
![image](https://user-images.githubusercontent.com/19344651/47659295-f19c5f80-db94-11e8-9f96-fc1a081a069e.png)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Thanks for the mockups. One very important thing to consider: The dashboard needs to be responsive. This basically means that the used elements should have similar widths so they can be displayed vertically on small screens.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Yes, we should adapt it to its responsiveness. The mockup is just to give us an idea. I will explain more tommorow.

**Comment by MartinWahnschaffeSymeda** [comment]
Note from last sprint review:
@hzi-braunschweig will discuss the proposal with GHS and the users in Nigeria, so we can have a unified version of it.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig What about these two points from #597:

- add table to show case count and incidence by age group
- add table to show case count and incidence by gender

Should this also be added to the dashboard? Maybe for the disease-specific view. If so, please include this in your moqups.

**Comment by MartinWahnschaffeSymeda** [comment]
![dashboardoverviewfinal](https://user-images.githubusercontent.com/23217632/50091751-7a865d80-020c-11e9-8077-7acc00338cf6.jpg)

== Disease Burden Information
- [ ] create DiseaseBurdenDto in sormas-api with fields: Disease, case count, previous case count, event count, caseFatalityRate
- [ ] create backend method that contains the needed information for each disease filtered by time and region/district
- [ ] Extend DashboardDataProvider to provide DiseaseBurdenDto for all diseases
- [ ] create DiseaseBurdenGrid to display the disease burden information. Hide diseases that have no count at all.
- [ ] disease column allows to drill-down to disease specific dashboard

== Disease Difference Bars
- [ ] create a highchart component that uses the DiseaseBurdenDto as data source
- [ ] 50% screen width (disease burden uses other 50%)

== Disease Carousel
- [ ] Header lists all diseases (could use SubNavigationMenu component)
- [ ] Checkbox to activate slide show
- [ ] Slide show through all diseases - update every 2 minutes (see #862 for polling)
- [ ] Filter all data to the active disease
- [ ] Display "New Cases" elements as in DashboardSurveillanceStatisticsComponent (25% width)
- [ ] Display EpiCurveSurveillanceComponent (25% width)
- [ ] Display DashboardMapComponent (50% width)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig I wonder wether we really need the "new cases" component in the bottom left. It basically displays the same information we already have in the disease burden table and the epi curve.
Instead we could use the area to make the epi curve bigger and then display the information New cases, new events, etc. we currently have on the dashboard below the epi curve and case map.
Let's discuss this tomorrow.

**Comment by MartinWahnschaffeSymeda** [comment]
Mockup needs to be updated again:

- [ ] Put map on the second slot (25% width)
- [ ] Put Epi Curve right (50% width)
- [ ] Unite New cases, new events and test results in the first slot
- [ ] Case classification, CFR, event type mixed with status, test results
- [ ] See if we can add report stats to the dashboard

**Comment by MartinWahnschaffeSymeda** [comment]
![dashboardfinal](https://user-images.githubusercontent.com/23217632/50209159-5b561000-0373-11e9-9408-a5f8470611d4.png)

@hzi-braunschweig Please have a look at this. It contains all changes as discussed yesterday. Two things I'm not sure about:

1. I think we should not show the event type (rumour, outbreak) in the dashboard. I'm not even sure how the event type "outbreak" is supposed to be used. How can an an event (taking place at a certain point in time) be an outbreak (something that is active for a certain period in time)? Maybe this needs a different name to clarify what it really is?
2. I suggest we display the number of districts that had an outbreak within the filtered time period. This is date that is already available.

**Comment by MartinWahnschaffeSymeda** [comment]
Final Mockup: 
![grafik](https://user-images.githubusercontent.com/23217632/50336518-a35d6a00-050e-11e9-93cc-1addf8e80244.png)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] filter disease burden by new cases
- [ ] switch x/y of case difference diagram and show all diseases

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Notes from Review:

- [ ] filter disease burden by new cases
- [ ] case differences diagram: show all diseases that have or had cases (not only the ones in the collapsed disease burden table)
- [ ] give epi curve 50% width and put case numbers, etc. above (see picture)

![grafik](https://user-images.githubusercontent.com/23217632/52273482-48f75c00-294a-11e9-9086-6a1afc804380.png)

**Comment by faatihi** [comment]
Hi everybody. GCNet had a meeting with GHS and a few suggestions were made:
1. Disease Burden Information grid should show Number of Deaths (in addition to the CFR column)
2. The initial dashboard for non-technical stakeholders is still needed along with the final view we have designed. see the initial dashboard at https://user-images.githubusercontent.com/19344651/47151596-760bfa00-d2da-11e8-8f34-8d94429dae59.jpg

@MartinWahnschaffeSymeda I'll go ahead and implement suggestion 1. For item 2, we might need to create a new issue. Your thoughts.

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Here are updated mockups that address the missing information (as far as I understand).

I have attached screenshots that show the tiles version of the disease burden and the grid version.
My idea is that we could show the tiles version to national users and observers and the grid version to supervisors by default. In addition both user groups are allowed to switch to the other view.

It may also make sense to colorize the differences bar chart with the same colors as used in the tiles.

The last mockup shows what it would look like on a small screen, where you can either scroll down or hide the overview when only the details of a specific disease are relevant.
I’m not sure, but it’s probably better to have the epi curve and the case status map in the same row (instead of below each other, as in the mockup).

![dashboardtiles](https://user-images.githubusercontent.com/23217632/52637178-d4cf3200-2ece-11e9-80c0-38db3a9cbd59.jpg)

![dashboardgrid](https://user-images.githubusercontent.com/23217632/52637182-d7ca2280-2ece-11e9-8a4a-358f0a418eba.jpg)

![dashboardtilessmall](https://user-images.githubusercontent.com/23217632/52637187-da2c7c80-2ece-11e9-98ed-04f36ff71246.jpg)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] round CFR to 2 decimal places
- [ ] button to hide top part
- [ ] diagram: center 0
- [ ] diagram show 10-12 diseases in small view
- [ ] hide legend
- [ ] reduce space above and below "show all diseases"
- [ ] remove the disease name from "New cases (...)"
- [ ] emphasize active disease menu point: 16-20px and background

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] maximize for map and epi curve in view instead of window. User should be able to use the filters

**Comment by bernardsilenou** [comment]
Let us discuss what should be added to the current dashboard with GHS in the next sprint if possible.
