### ISSUE TITLE
No document creation in bulk mode possible when "sample" or "pathogentest" fields are used in a template

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#8356]
### Bug Description

When trying to create documents in bulk mode an error accures when the choosen template got fields from "sample" or "pathogentest".

Same error for cases, contacts and event patricipants.

Document creation without bulk mode works with these templates.
### Steps to Reproduce

1.enter bulk mode
2.choose at least 1 case/contact/patricipant
3.click on "create quarantine order documents"
4.choose a template with at least "sample" or "pathogentest" fields"
5.error should pop up (Screenshot)

### Expected Behavior

Document creation should work fine and documents are downloaded.
### Screenshots

![image](https://user-images.githubusercontent.com/96547924/157881417-9706c426-cd22-4bce-8ec9-e5cf62e4e54e.png)

### System Details

* Device:
* SORMAS version: 1.69.0
* Android version/Browser:
* Server URL: test1401.sormas-oegd.de
* User Role: admin

**Comment by syntakker** [comment]
A person may be associated to multiple samples and multiple pathogen tests for each of those. When generating a single document, both are chosen from list of available samples / pathogen tests. In bulk mode, it is impractical to chose samples / pathogen tests for individual documents.

@MateStrysewske do we have a definition for which sample / pathogen test form the existing ones?

Same question arises for vaccinations, too (see #7532, #8099).

In any case, this should not be an error, but an option would be to show a warning and leave these fields empty.

**Comment by JaquM-HZI** [comment]
@syntakker  we discussed this in the original issue #3575 and the answer ist given here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/3575#issuecomment-816484588
