### ISSUE TITLE
Detailed performance analysis of getAllAfter and getIndexList methods [5]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8357]
### Problem Description

Retrieving data via ReST during the mobile app synchronisation process can take a lot of time (with as few as 1000 cases taking several minutes to synchronize). We've also received reports (and witnessed) the web app directories taking more than a few seconds to load on systems with a lot of data (e.g. more than 500,000 entries in a directory).

### Proposed Solution

In preparation of potential refactorings and code improvements, analyse the performance of the getAllAfter and getIndexList methods of the following entities:

* Case
* Contact
* Sample
* Person

This should include all EJBs called in the process, and also especially include the pseudonymisation logic because this was already identified as a huge bottleneck at least for the synchronisation process.

Step 1: Activate `PerformanceLoggingInterceptor` on TRACE level to analyse call hierarchy and where time is spent. Document execution times.
Step 2: Dive deeper into hotspot method to find costly transformations (probably in `toDto`/`pseudonymize` methods).

### Additional Information

A potential follow-up issue to improve the pseudonymisation process could include the following action points:
- Skip pseudonymisation completely for entites that we know will not be pseudonymised based on the user's user rights (e.g. an entity inside the user's jurisdiction does not need to be checked for pseudonymisation if the user has both the SEE_PERSONAL_DATA_IN_JURISDICTION and SEE_SENSITIVE_DATA_IN_JURISDICTION user rights)
- Create a cache per entity of all fields that need to be considered during pseudonymisation in order to reduce the usage of reflection

Since the toDto logic also takes some time, another possible change could be to directly select into DTOs, even though that would potentially introduce a significantly increased maintenance effort.

As database where we want to reproduce  the perf. issues and measure the improvements we are using the pseudonymized data from France.

### Deliverables
Confirm that pseudonymization is one cause 
Explore what else causes performance issues
Document KPI (Key performance indicators) and preconditions to be able to measure the improvement
Create follow-up tickets that are obvious

==>
- pseudonymization can be ruled out as a relevant impact on performance
- long runtimes are mainly caused by long running SQL queries with massive joins
- follow-up issues: #8938 for `getIndexList` methods, #8946 for `getAll` methods in the REST API

**Comment by syntakker** [comment]
Analysis of `getAllAfter` and `getIndexList` see follow up issues #8946 and #8938.

**Comment by MartinWahnschaffe** [comment]
We looked into the results for #8946 and decided that we need more details on which exact calls are responsible for the long execution.
