### ISSUE TITLE
Missing german descriptions in user roles export table

### ISSUE THREAD

**Issue by kathsievers** [hzi-braunschweig/SORMAS-Project#8374]
### Bug Description

The user roles export is missing german descriptions for three user rights (see screenshots).

### Steps to Reproduce

1. Open user roles UI
2. Export user roles table

### Expected Behavior

All user roles should have a german description.

### Screenshots

![8a1adce8-3601-4d2e-b3b8-1be970764e11](https://user-images.githubusercontent.com/97029882/158173371-2115e334-26eb-4761-9f44-80e155adb5b7.jpg)

![bb514d81-0f77-4509-9e8c-0157b5ce0c5f](https://user-images.githubusercontent.com/97029882/158173192-96c266fc-7015-44d6-b74e-4ba208f966e0.jpg)

### System Details

* Device: 
* SORMAS version: 1.69.0
* Android version/Browser: Edge
* Server URL: https://test1401.sormas-oegd.de/sormas-ui/
* User Role: admin

**Comment by roxanamlendea** [comment]
![image](https://user-images.githubusercontent.com/89522688/159002002-33e1abc6-9ec6-4b91-a404-dc27cecf88ea.png)

**Comment by roxanamlendea** [comment]
Verified ticket on local machine using the latest version of Sormas 1.70.0-SNAPSHOT (f122a0d).
The user rights have according descriptions, but the German translations still have to be pulled from Crowdin though (I don't know how long it takes).

![image](https://user-images.githubusercontent.com/89522688/159002145-660d8273-ab22-4b2c-abff-c6cc7ce3d80d.png)

![image](https://user-images.githubusercontent.com/89522688/159003216-5cf0271e-d8bb-4bfe-a3bc-714b8da9f07f.png)

**Comment by roxanamlendea** [comment]
Waiting for the translations to be made. I'll validate the ticket afterwards.

**Comment by SahaLinaPrueger** [comment]
Translation on nightly builds not available. Can not yet be approved.

**Comment by adinaflorea9** [comment]
Verified the ticket using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(6684c7e). The German translations for the User Roles Export Table are not yet complete. Can not validate the ticket now - will verify the ticket once the translations are available.


![image](https://user-images.githubusercontent.com/96909231/160544228-e2a7c274-9d02-45b5-af84-b372a0a7b517.png)


![image](https://user-images.githubusercontent.com/96909231/160544243-a9b35ac1-818e-4219-b704-d3f21857848c.png)

**Comment by MateStrysewske** [comment]
@adinaflorea9 Those three user rights were not part of the initial issue description, I suppose they came in during the sprint. Can you please open a new issue for them?

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(1dc6c47). The missing translations from the current ticket are now present, therefore, I am validating this ticket.

The additional missing translations were reported in a separate issue #8593.
