### ISSUE TITLE
Person search does not find persons with double name/surname when only one name is entered

### ISSUE THREAD

**Issue by kathsievers** [hzi-braunschweig/SORMAS-Project#8384]
### Bug Description

The person search does not find persons with double names when you search for only one first/last name (e.g. Hans Peter Lustig cannot be found by searching for just "Hans" OR "Peter", only if you search "Hans Peter" or "Hans Lustig"). This leads to potential person duplicates.
### Steps to Reproduce

1.Create entity (e.g. case) with double name
2.Create second entity (e.g. case) and use the person search button
3. Search for only one of the first/last names
4. Person from step one is not found.

### Expected Behavior

To limit the generation of person duplicates the person search should find persons also when you just enter one first/last name of the double name. 

### Screenshots

![image](https://user-images.githubusercontent.com/97029882/158335220-c494415c-07f4-4707-85be-3300c14c6348.png)
![image](https://user-images.githubusercontent.com/97029882/158335518-ccbe7048-3002-40fc-94c8-21d9cc6e5216.png)
![image](https://user-images.githubusercontent.com/97029882/158335597-e1d3a0ff-b854-4de5-b35e-e12df8c3ff30.png)
![image](https://user-images.githubusercontent.com/97029882/158335351-e090f674-d06d-4656-a500-a212622e7ef8.png)

### System Details

* Device: Web
* SORMAS version: 1.69
* Android version/Browser: Edge
* Server URL: https://test1401.sormas-oegd.de/sormas-ui
* User Role: admin

**Comment by adinaflorea9** [comment]
The 'Person Search' was improved and extended with SORMAS version 1.77.0 with ticket #8485. As the current ticket was logged and the behavior was reported on SORMAS version 1.69.0 I will be closing it as a duplicate.

I have checked the behavior of the 'Person Search' for persons with double names, tripe names or even multiple values both for the first and last names and the search option used rendered the expected results - namely, the persons can be searched by either values that have been inputted in the first or last name fields. 

Behavior was checked on my local machine with SORMAS version 1.84.0-SNAPSHOT(e4ab722) and on https://test-de2.sormas.netzlink.com/ with SORMAS version 1.83.0-SNAPSHOT(6645d18).
