### ISSUE TITLE
The fields associated with the 'Select a different person' checkbox do not get reset once they are highlighted in red

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8388]
### Bug Description

In the 'Pick or create person' form that is triggered when processing a lab message, once the name and ID/External ID fields associated with the checkbox 'Select a different person' get highlighted in red, the field validation is not cleared when the user clicks the 'Reset' button or switches between the other 2 checkbox options - 'Select a matching person' and 'Create a new person'.

### Steps to Reproduce

There are 2 flows in which this can be reproduced:
I:
1. Navigate to the 'Samples' directory - 'Lab messages' page;
2. Click to process a lab message;
3. In the 'Pick or create person' form that get triggered after step 2, check the 'Select a different person' checkbox;
4. Clear the name that is prefilled in the name fields and click 'Search';
5. Click 'Reset' or switch to one of the other 2 checkboxes - 'Select a matching person' and 'Create a new person'.

II:
1. Navigate to the 'Samples' directory - 'Lab messages' page;
2. Click to process a lab message;
3. In the 'Pick or create person' form that get triggered after step 2, check the 'Select a different person' checkbox;
4. Clear the name that is prefilled in the name fields;
5. Switch to one of the other 2 checkboxes - 'Select a matching person' and 'Create a new person'.

### Actual Behavior

After step 5 of each of the flows described in the steps to reproduce, the 3 fields associated with the 'Select a different person' checkbox remain highlighted in red.

### Expected Behavior

The 3 fields associated with the 'Select a different person' checkbox are not highlighted in red.

### Screenshots

![Fields validation](https://user-images.githubusercontent.com/96909231/158359685-b79e8fa9-db9a-40f7-8eb3-4c0a305dd4ed.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(d4e08c4)
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

The behavior is reproducible as well when triggering the 'Pick or create person' form when the duplicate detection is triggered in the other directories.

**Comment by FredrikSchaeferVitagroup** [comment]
Even though the current behavior obviously is not correct, the expected behavior was never specified and therefore leaves room for discussion.

In my opinion, the reset buttons should reset the validation errors. That fits the bug description.

But switching to another option (step 5) leaves the search as is. Therefore, also the validation errors should remain. Instead, they should be hidden.

That's what I implemented, which by the way also fixes #8390.

**Comment by abrudanancuta** [comment]
Validated on local environment with version 1.70.0-snapshot(https://github.com/hzi-braunschweig/SORMAS-Project/commit/20a2e7cf1e955fdd397b5541a1385c583e3e83f6)
