### ISSUE TITLE
Cq/ct value shows wrong number

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#8389]
### Bug Description

Entering a value for cq/ct value, it shows always the value with ".0" and not the correct one Also it changes the entered number.

### Steps to Reproduce

1. create sample with cq/ct value
2. enter for example "30.32"
3. save
4. have a look at the pathogen test 
5. it shows "3032.0"
6. open pathogen test again
7. value has changed to "3032.0

### Expected Behavior

The given cq/ct value should be shown.

### Screenshots

![Cq CT Value](https://user-images.githubusercontent.com/78568406/158366689-7093509c-1e44-49a2-b5f2-127c164d863d.gif)

### System Details

* Device: 1.68.3 / 1.69
* SORMAS version: 1.68.3 / 1.69
* Android version/Browser:
* Server URL:
* User Role: admin

**Comment by MateStrysewske** [comment]
@JaquM-HZI I suspect that you're trying to use . as a separator with a user that uses German as their language? If that's the case, it's expected that's not supposed to work since Germany is using , as a separator. Can you please tell me which server you were using?

**Comment by felix84-ed** [comment]
@MateStrysewske Yes, that's right. In Germany you have to use , as a separator.

But when I run a database export for pathogen.test, there are wrong numbers in the cq value-column. For example: 
cqvalue
22.019.999

**Comment by JaquM-HZI** [comment]
@MateStrysewske you're right, I testet on https://test1401.sormas-oegd.de/ , it works with "," instead of "."

**Comment by MateStrysewske** [comment]
@felix84-ed Hmm, okay, that's something we might have to look into then.
