### ISSUE TITLE
The fields associated with the 'Select a different person' checkbox remain visible when the user checks the 'Create a new person' checkbox

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8390]
### Bug Description

When processing lab messages, in the 'Pick or create person' form, the fields associated with the 'Select a different person' checkbox remain visible when the user selects the 'Create new person' checkbox.

### Steps to Reproduce

1. Navigate to the 'Samples' directory - 'Lab messages' page;
2. Click to process a lab message;
3. In the 'Pick or create person' form, select the 'Select a different person' checkbox;
4. Then select the 'Create a new person' checkbox.

### Actual Behavior

The fields associated with the 'Select a different person' checkbox remain visible.

### Expected Behavior

The fields associated with the 'Select a different person' checkbox are no longer visible.

### Screenshots

Fields when selecting the 'Select a different person checkbox':
![image](https://user-images.githubusercontent.com/96909231/158372377-be5edbd6-393f-4b29-9b1e-3e3c996c58de.png)

Fields when selecting the 'Create new person' checkbox:
![image](https://user-images.githubusercontent.com/96909231/158372499-ef072280-9bc7-4a51-8ca6-731a29b7218d.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(d4e08c4)
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

If after step 3 of the steps to reproduce, the user selects the 'Select a matching person' checkbox, the fields associated with the 'Select a different person' checkbox are no longer visible.
 
![image](https://user-images.githubusercontent.com/96909231/158372664-b9ebdae7-1057-4f9e-a2d3-19c36f2e401a.png)

The behavior is reproducible as well when triggering the 'Pick or create person' form when the duplicate detection is triggered in the other directories.

**Comment by abrudanancuta** [comment]
Validated on local environment with https://github.com/hzi-braunschweig/SORMAS-Project/commits/20a2e7cf1e955fdd397b5541a1385c583e3e83f6
