### ISSUE TITLE
On the Sample Card, in the 'Date and time of result' section, the 'Time' is not displayed even though it was set in the 'Pathogen Test Result'

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8404]
### Bug Description
On the Sample Card, in the 'Date and time of result' section (under the 'Latest Pathogen Test'), only the 'Date' is displayed, but the 'Time' isn't, even though it was set in the 'Pathogen Test Result'.

### Steps to Reproduce

1. Open a Case / Contact / Event Participant;
2. Add a Sample;
3. Then add a Pathogen Test Result and set the 'Date and Time of result';
4. Inspect the 'Samples' card;

### Actual Behavior
On the Sample Card, the 'Time' is not displayed in the 'Date and time of result' section (under the 'Latest Pathogen Test').

### Expected Behavior
On the Sample Card, both 'Date' and 'Time' should be displayed in the 'Date and time of result' section (under the 'Latest Pathogen Test').

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/158575715-3c47827b-ac64-4d72-aed5-e821d1717ce8.png)
![image](https://user-images.githubusercontent.com/89522688/158575804-a35976c7-9a3a-43f9-9ffe-89c730bceb92.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.70.0-SNAPSHOT (0ef0b17)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information
In the 'Pathogen Tests' card, both 'Date' and 'Time' are displayed:
![image](https://user-images.githubusercontent.com/89522688/158575757-4fb0d3a4-2804-495d-ac0b-17a0d8dd8d7e.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS 1.70.0-SNAPSHOT(030b1ed) from the development branch.
