### ISSUE TITLE
[Persons] 'Contacts' card is displayed for users that do not have the CONTACT_VIEW user right

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8407]
### Bug Description

Users that do not have the CONTACT_VIEW user right should not see the 'Contacts' card displayed in the 'Persons' directory, on the person page.

### Steps to Reproduce

1. Log in with a user that does not have CONTACT_VIEW rights (hospital informant, community informant, case officer);
2. Navigate to the 'Persons' directory;
3. Click on a person's ID to open the person's page;
4. Observe the cards listed.

### Actual Behavior

'Contacts' card is displayed.

If a contact is associated with that person, the user is able to see the UUID of the contact, the disease, contact status, contact classification and the 'View contacts for this person' button.

### Expected Behavior

'Contacts' card is not displayed.

### Screenshots

![Screenshot 2022-03-15 170409](https://user-images.githubusercontent.com/96909231/158600318-772ae47d-1914-455e-8350-0089647d1eea.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(48fad26)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Hospital Informant; Community Informant; Case Officer

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.70.0-SNAPSHOT (9d06a5b) from the development branch.
