### ISSUE TITLE
[Events] Date validations on the event page are not consistently displayed

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8416]
### Bug Description

The date validation between 'Date of Report', 'Date of Event' or 'Start Date' and 'End Date' are not triggered consistently, and are not cleared consistently.

### Steps to Reproduce

I:
1. Open an event that has a report date but no event date;
2. Change the report date (9th of March);
3. Add the date of event (10th of March);
Actual Behavior: => date validation is not triggered until the user saves the page; the date fields are not highlighted (even after the user saves the page and the date validation warning message appears).
![image](https://user-images.githubusercontent.com/96909231/158757629-195021cc-9b86-40e5-898a-2e5dae809246.png)

II:
1. Open an event that has a report date (10th of March) but no event date;
2. Check the 'multi day event' checkbox;
3. Input first the end of event date (9th of March), then the start of event date (11th of March);
Actual Behavior: => date validation is not triggered until the user saves the page; the date fields are not highlighted  (even after the user saves the page and the date validation warning message appears).
![image](https://user-images.githubusercontent.com/96909231/158615560-35ed5064-6e4e-4e5a-a444-877a81ea1c31.png)

III:
1. Open an event that has a report date but no event date;
2. Check the 'multi day event' checkbox;
3. Input an invalid date combination between the fields ('Start Date' - 9th of March / 'End Date' - 8th of March)
      => 'End Date' is highlighted in red;
4. Set the 'Start Date' - 7th of March. 
Actual Behavior: => 'End Date' field remains highlighted.  
![image](https://user-images.githubusercontent.com/96909231/158626986-0532abaf-e76d-4485-8b1e-95efc5facc34.png)

IV:
1. Open an event that has a report date but no event date;
2. Change the 'Date of report' to the 9th of March and save the page;
3. Check the 'multi day event' checkbox;
4. Input first the 'End Date' (8th of March), then the 'Start Date' (10th of March);
Actual Behavior: =>  date validation is not triggered until the user saves the page; the date fields are not highlighted  (even after the user saves the page and the date validation warning message appears).
![image](https://user-images.githubusercontent.com/96909231/158628069-976847dc-1cce-462b-b9b2-89f1031c602a.png)

V:
1. Open an event that has a report date but no event date;
2. Set the 'Date of event' to a future date;
Actual behavior: => date validation is not triggered until the user saves the page; the date fields are not highlighted  (even after the user saves the page and the date validation warning message appears).
![image](https://user-images.githubusercontent.com/96909231/158631154-3cf99422-ffef-4bc1-8d2c-bf0684005b33.png)

VI:
1. Open an event that has a report date but no event date;
2. Set the ‘Date of report’ to today’s date and save the page;
3. Set the 'Date of event' to today's date;
4. Set the 'Date of report' to a future date;
Actual behavior: => date validation is not triggered until the user saves the page; the date fields are not highlighted  (even after the user saves the page and the date validation warning message appears).
![image](https://user-images.githubusercontent.com/96909231/158630946-b3ce2418-294b-473e-9356-0969623750d4.png)

### Expected Behavior

The date validation is triggered right when an invalid date combination is inputted in the date fields, and when the user tries to save the page.

The date fields are highlighted in red; a red exclamation mark is displayed next to the fields; upon hovering over the fields a warning note is displayed.

Once the invalid date combination is fixed by updating the date from one of the fields, the date validation should be cleared (the fields are no longer highlighted in red).

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(5f58f7d) and 1.70.0-SNAPSHOT(2b5f96c)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

The behavior was reproducible on the test-de2 testing environment after the deploy-to-test from 9.09pm from the 16th of March; and on the local machine after the latest updates were pulled from the development branch.

**Comment by dinua** [comment]
fix for this task was implemented in #8438

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.78.0-SNAPSHOT.
