### ISSUE TITLE
[Angular] Contact Directory: Line Listing [5 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8423]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/kaRmqqD
- This task is dependent on: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8220
- We will reuse the widget already implemented for "Choose Case"

### QA Section

1. What should the QA look for (what was done)
- Check that the user can add / delete multiple lines
- Check that the same fields are mandatory as per the current Sormas implementation.
- Check that the user is able to select a case / remove the selected case

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
-Not saving contact
-"Disease" and "Region" labels with 2 mandatory field stars
![image](https://user-images.githubusercontent.com/102517557/160575121-326078f1-921f-49c5-93d4-74e4ef0622f5.png)
