### ISSUE TITLE
Archiving of cases & events [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#843]
- [x] add property to backend entities (NOT to dtos): case, event, contact, sample, task (only case and event can actively be archived)
- [x] add parameter to query criterias
- [x] add ui element to dictionaries to switch between normal and archived (sub-lists should not have this element, but instead always show all entries)
- [x] add (de)archive button to case view
- [x] add (de)archive button to event view
- [x] add user rights: can archive, see archived (both for cases and events)
- [x] define which user roles can do this
- [x] bulk (de)archive
- [x] write tests
- [x] change directory heading to "Case Archive" (etc.) when archived entries are viewed

### app
- [x] don't transfer archived entries to app
- [x] add methods to check for entries archived since (returns uuids)
- [x] during sync call this method if not done so during the last 24 hours or when full sync is done
- [x] changes to entries that have been archived meanwhile will be lost (add to sync conflict log)
- [x] write tests and test functionality

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Which users should be able to see archived cases/events and which should be able to archive/de-archive them?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] rename SEE user rights to VIEW
- [ ] archived database columns needs null constraint and default value "false". This makes null checks in queries unnecessary
- [ ] i18n (e.g. Button)

**Comment by MartinWahnschaffeSymeda** [comment]
Didn't find a clear way on how to define an activity that is only used for androidTest in the manifest. There doesn't seem to be a way to add a manifest for androidTest.
