### ISSUE TITLE
On the 'Create new task' form, the red exclamation mark persists even after the user adjusts the date

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8438]
### Bug Description
On the 'Create new task' form, after the user fills in the date fields with incorrect input, and the fields are marked red when the user tries to save the form, after the user adjusts the 'Suggested start' date, the red exclamation mark persists on the 'Due date' field.

The issue is also reproducible for Immunizations and for Events.

### Steps to Reproduce

1. Open a Case;
2. Click on 'New Task';
3. In the 'Create new task' form, set the 'Suggested start' date to 18 march and 'Due date' to 15 march, fill in the mandatory data and Save.
-> The user is not able to Save the form and the date fields are marked red;
![image](https://user-images.githubusercontent.com/89522688/158984753-1a1c2163-09e2-45ee-b44e-0324bc74a265.png)
4. Adjust the 'Suggested start' date and set it to 13 march;

### Actual Behavior
The 'Suggested start' date field is not marked red anymore, but the 'Due date' field is still marked red, even though the inputs are not correct. 
The user can still Save the form though, so that's correct.

### Expected Behavior
Both 'Suggested start' date and 'Due date' should not be marked red anymore.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/158985813-c0a72689-34d7-4bf0-8fad-7034f4eb1f1c.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.70.0-SNAPSHOT (f122a0d)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Admin, NatUser

**Comment by dinua** [comment]
I implemented it to behave the same way as in new Contacts
![image](https://user-images.githubusercontent.com/4202109/205667017-84f73949-5294-4ea7-88bd-47ece280405f.png)

**Comment by roxanamlendea** [comment]
The issue is also reproducible for Immunizations and for Events.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.78.0-SNAPSHOT.
The issue is no longer reproducible for Tasks, Immunizations and Events (multi-date event)
