### ISSUE TITLE
Use "Last changed" timestamp of the whole case for the filter "Only cases changed since last shared with reporting tool" instead of scanning every field for changes.

### ISSUE THREAD

**Issue by kathsievers** [hzi-braunschweig/SORMAS-Project#8443]
### Feature Description

The filter "Only cases changed since last shared with reporting tool" is used to display the cases that have been edited since they last been shared with the reporting tool, which is essential for updating the information that is reported from the reporting tool. 

### Problem Description

The filter "Only cases changed since last shared with reporting tool" is causing performance issues including timeouts for the health departments. Reason for the long processing time is that the filter searches the last change timestamp for each field in the case and compares it to the timepoint when the case was last shared with the reporting tool. 

### Proposed Change

To optimize the processing time for the filter and by that improving the performance of SORMAS the filter should compare the overall last change date of the case with the last shared timestamp.

**Comment by markusmann-vg** [comment]
@kathsievers 
Can this be marked as duplicate because it's covered by https://github.com/hzi-braunschweig/SORMAS-Project/issues/7656 ?

**Comment by kathsievers** [comment]
@markusmann-vg Yes!
