### ISSUE TITLE
Default username and password for SORMAS on first login [0.5]

### ISSUE THREAD

**Issue by chlarsen** [hzi-braunschweig/SORMAS-Project#846]
Dear All,
A seriously stupid question, but I cannot find any hints:
What are the username and password for the SORMAS initial login screen? During the deployment procedure with server-setup.sh, the user admin was created without password, as is the default.
Thank you,
Chris

**Comment by MartinWahnschaffeSymeda** [comment]
Hi Chris,
this user used in the frontend is different from the admin user created for the server domain.
We still have to add this to the documentation.

The default users are:

### admin
name: admin
pw: sadmin

### surveillance supervisor
name: SunkSesa
pw: Sunkanmi

### surveillance officer (mobile app)
name: SanaObas
pw: Sanaa

**Comment by chlarsen** [comment]
Great, Martin, thanks a lot for that! I hope I will get that far soon, once the .ear issue has been solved.
