### ISSUE TITLE
[Cases Directory] System error when user clears the 'Responsible Surveillance Officer' field via Bulk Edit Mode

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8461]
### Bug Description
When the user accesses the Bulk Edit Mode -> Bulk Actions -> Edit of the Cases Directory and clears the 'Responsible Surveillance Officer' field, he receives a system error when saving.

### Steps to Reproduce

1. Open the Cases Directory and access the Bulk Edit mode;
2. Click on Bulk Actions -> Edit;
3. Check the 'Change Surveillance Officer' checkbox;
3. Leave the field cleared and Save;

### Actual Behavior
User gets a system error.

### Screenshots
![bulk edit mode error](https://user-images.githubusercontent.com/89522688/159244290-8590b942-917b-450f-81f1-d5406ba2025c.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT (077981e)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information
Logs from my local machine for this bug: 
[logs server error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8314722/logs.server.error.txt)

**Comment by mario-kuehne** [comment]
Tested locally on Version: 1.70.0-SNAPSHOT ([c6ff697](https://github.com/hzi-braunschweig/SORMAS-Project/commits/c6ff6974430127d1976d898fc02ae351a60f186a))

- Configured local test instance B with `Region=Niedersachen` and `District=SK Wolfsburg`
- Created a user with Role 'Surveillance Officer' for `Region=Niedersachen` and `District=SK Wolfsburg`
- Entered Bulk Mode in Case Directory
- Selected any case (minimum 1 case)
- Bulk-Actions -> Edit
- Checked Checkbox 'Change surveillance office'
- Left Dropdown Component empty
- Clicked Save

Expected:
- No Server Error shown

Actual:
- No Server Error shown

**Comment by mario-kuehne** [comment]
Also tested on https://test-de2.sormas.netzlink.com/ on Version: 1.70.0-SNAPSHOT [(6684c7e)](https://github.com/hzi-braunschweig/SORMAS-Project/commits/6684c7e40b6b9aad4516847d45291a4ab704a788)

_Scenario 1_: Case with SurveillanceOfficer S1
- Created a case C1 with SurveillanceOfficer S1 attached
- Opened Bulk Edit Mode for this specific case C1
- Checked checkbox 'Change surveillance officer' & left combobox empty & saved

Actual behaviour:

- No error message shown
- **SurveillanceOfficer S1 is shown in case C1** <- intended behaviour?

_Scenario 2_: Case with switch from SurveillanceOfficer S1 to SurveillanceOfficer S2
- Created a case C2 with SurveillanceOfficer S1 attached
- Opened Bulk Edit Mode for this specific case C2
- Checked checkbox 'Change surveillance officer' & selected SurveillanceOfficer S2 in combobox & saved

Actual: 

- No error message shown
- SurveillanceOfficer S2 is shown in case C2
