### ISSUE TITLE
Display soft-deleted entities to users that have the right to delete [8]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8465]
### Situation Description
It must be possible to review which entities were manually deleted and to revert the deletion.

This belongs to epic #7736 which describes the automatic deletion and re-works how (manual) soft-deletion works. 

### Change Proposal
The following goes for the directory views of cases, contacts, events, event participants, samples, travel entries and immunizations.

- [x] Besides being able to view active and archived entities it should also be able to view deleted entities
- [x] "all ..." should be renamed to "active and archived ..."
- [x] Add another column to display the reason for deletion (combine enum + free text)
- [x] But only when the user has the corresponding ..._DELETE user right
- [x] For event participants this filter is currently missing completely and needs to be added

The user should be able to open the entity and undo it's deletion (see #8990).

### Additional Information
Out of scope: Soft-deleted entities will sometimes be removed from related entities (e.g. a contact from it's source case). When reverting the deletion, this information will not be re-created. If needed the user can manually re-assign the entity.

**Comment by roxanamlendea** [comment]
Another finding is that the Prescriptions are no longer editable:

1. Log in with an Admin + National User;
2. Open a Case and navigate to the Therapy tab;
3. Create a Prescription;
4. Then open the Prescription from step 3;
-> the Prescription is read-only, but it should be editable;

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(58ddec9).
