### ISSUE TITLE
S2S_automatic update in the share-box [1]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#8471]
### Feature Description

The "share-box" shows the current status of the sharing in the source system. "This case is not shared" is shown at the beginning. After initiate a share on the source system (you have to click "share" on a pop up-window) the "share-box" changes and shows "Shared with [target system] by [user] on [date] Status [] and Comment [text]."

### Problem Description

After initiate a share on the source system by clicking on "share" the pop-up-window closes but the share-box still shows "This case is not shared", sometimes. This is not good, because a user could think, that the share did not happend and will share twice or just be frustrated. (The more advanced user surely will solve the problem by refreshing the website, because then the share-box is updated, but we have to think for all users).

### Proposed Change

The share-box has the information to update itself automatically when the share has been started.

### Possible Alternatives

If technically not possible the whole website should update itself automatically when the share has been started.

### Additional Information

![image](https://user-images.githubusercontent.com/100844689/159293711-b1258ca7-7644-46ba-86f8-85a3a461856c.png)
![S2S_no update](https://user-images.githubusercontent.com/100844689/184441739-dd7efe3e-42bf-45d2-863f-265268634189.gif)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by StefanKock** [comment]
Will not be finishable for 1.77.0

**Comment by dragosb-vg** [comment]
The issue is still replicating after the fixes. 
After sharing the case/contact (no matter the share type and data), the share box is stuck on "Loading shares.."
![image](https://user-images.githubusercontent.com/111864167/207071333-785dd2f1-1582-4c39-b140-c9dc1c093ecb.png)

Also, probably due to an older issue recently found (#11161 ) repeating cycles of sharing-revoking the entity from source system share box without refreshing, results in  multiple 'Shared with' text fields (see image below)
![image](https://user-images.githubusercontent.com/111864167/207073132-ae5457bb-411e-4171-8519-0e743a165ba2.png)

**Comment by dragosb-vg** [comment]
Validated on **test-de1** <-> **test-de3** on Version: 1.76.0-SNAPSHOT ([c9f486a](https://github.com/hzi-braunschweig/SORMAS-Project/commits/c9f486a2e4f83c103d436b46fcbfc419156ce455))

Share box updates with the correct information after sharing the entity (case, contact, events)
- the text box is refreshed correctly
- textbox contains the updated info: shared with, shared user, shared date, status and comment;
- revoke button is visible and usable
- multiple series of share/revoke can be performed without issues.

![doubleText](https://user-images.githubusercontent.com/111864167/208440697-fda77a09-03dd-4816-ae7e-69cea522b727.gif)

Please note that the duplication of the 'Shared with:' text element (issue reported in  #11161 , currently in review) is still occurring.
