### ISSUE TITLE
Vaccine Dose value is not exported

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#8474]
### Bug Description

Exporting a case with a given value for `vaccine dose` it is empty.

### Steps to Reproduce

1. Create a case 
2. Add a vaccination 
3. fill in a value for vaccine dose
4. save
5. export the case including the vaccinations

### Expected Behavior

The given value for vaccination dose should be exported but it is empty.

### System Details

* Device:
* SORMAS version: 1.69.1 
* Android version/Browser:
* Server URL:
* User Role: admin / national user

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.71.0-SNAPSHOT (1b0e181)
Cases checked:

A. System has reduced immunisation enable
    1. Case has 2 vaccines not relevant but both of vaccines having the field of "Vaccine dose" completed with a number
    Export detailed report about cases => at this point  none of the vaccines made are not relevant, then the dose number is not present in the export

    2. Case has 2 vaccines not relevant and one vaccine relevant, all vaccines having the field of "Vaccine dose" completed with a number
    Export detailed report about cases => at this point  only one vaccine is relevant, then the dose number is present in the export, the one from the relevant vaccine

B. System has full immunisation
    Case has one immunisation created, the number of doses is completed
    Immunisation has al least one vaccine relevant, the vaccine dose is also completed
    Export detailed report about cases => at this point the number of vaccines is taken from the immunisation module

**Comment by abrudanancuta** [comment]
Discovered a bug while testing the ticket
https://github.com/hzi-braunschweig/SORMAS-Project/issues/8626
