### ISSUE TITLE
Localisation of SORMAS

### ISSUE THREAD

**Issue by chlarsen** [hzi-braunschweig/SORMAS-Project#848]
Greetings from Uganda,
As I learned from #845, the current configurations are tailored for Nigeria and Madagascar. Is it possible to remove the Nigerian configuration data (taken on board in my specific installation), and feed the system with country-specific data? It should be reasonably easy, if there is either a .csv import/export facility for any such configuration data, or if I can do so via .sql at the database level.
Before I break anything, some information on the best way would be highly appreciated.
Thank you!

**Comment by hzi-braunschweig** [comment]
@chlarsen Thanks for your collaboration efforts. I am sure @MartinWahnschaffeSymeda  will explain it to you. Please can you make available on github your sormas project version? Also it would be nice to know what project you are using it for in Uganda or do you want to set it up for the ministry of health, surveillance unit or personal use and if we can help in any way. It would be great to know more about your SORMAS project in Uganda. 

Regards

**Comment by chlarsen** [comment]
Greetings from Kampala,
Thank you so much for your encouraging words! Presently, I aim to explore SORMAS' potential for use within the Ugandan context and would like to see, whether it will meet any open requirements, ideally with minimal duplication. There is, of course, DHIS2 in place, and it is used for outbreaks and emergency responses, but there are a few issues that I feel could be addressed. For now, I am trying to set up the system within the academic environment of the Infectious Diseases Institute, without any official mandate, and certainly no governmental endorsement. In any case, it looks like a most interesting journey! Of course, any Ugandan configuration data will be given back to the Community!
Warmest regards and thanks.

**Comment by MartinWahnschaffeSymeda** [comment]
@chlarsen There is currently no pre-defined way to do this.
One thing you could do is the following: 

- Let the server set up as a nigeria or madagascar system
- Truncate the regions table cascading (this will also truncate districts, communities, facilities and alls users except the admin). Make sure not to restart/redeploy the server afterwards - this would just recreate all entries.
- Log in using the admin (this should most likely work). Use the configuration interface to create a few regions, districts, communities, health facilities and laboratories. 
- If you want to create a much bigger list you can try to directly create them in the database. In the mid-term we plan to add an import function in the interface.

**Comment by chlarsen** [comment]
Dear Martin,
This sounds like a plan. The system has already been set up the Nigerian way. 
I will do the next few steps, as soon as I get a minute (am currently swamped). I could not see any way to edit any records in the configuration menu, but will figure it out.
More soonest, and a big thank you!
