### ISSUE TITLE
Change Search Options in Person Search [2]

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#8485]
### Problem Description

The current search options could be more useful if it would be just one search field like it is in directories and it should be extended with a search option for year/month/day of birth. Sometimes first and last name are mistakenly changed or the official first name is written and second time the call name. The current search does not allow the user to find these persons. 

### Proposed Change

- [x] Replace the search for first and last name, ID, Person ID, case ID, External ID (if there are other search options currently included in the third search field, allow them aswell) to a general search field. It should be possible to search for the whole and just part of something.
- [x] Add Filter option for year/month/day of birth separated

#### Mockup:
![Person Search](https://user-images.githubusercontent.com/78568406/159479615-873e8199-7390-4b91-96bd-acc17aec965c.jpg)

### Acceptance Criteria

- [x] The month in the select is written out (not as numbers) in all such forms and directory filters.

### Implementation Details

- Person search (`PersonSelectionFilterForm` and `PersonSimilarityCriteria`) is used within different workflows, should be changed in all of them.
- Have reasonable width for year/month/day fields (as in directory filters).

**Comment by JaquM-HZI** [comment]
@BarnaBartha I am trying to clear up the confusion. I want the Search Option be changed for example in this situation:
![Archieve -  read only](https://user-images.githubusercontent.com/78568406/195787872-0e94734d-229a-47d8-84cb-a2f7f051e8dd.gif)
The idea is, that the user knows there is this Person already in the system, but for example first and last name are changed, so if I would enter the correct last name in the current search field, I would not get the person I want. Or I know the persons last name is something like the german "meyer/mayer/maier/meier" but I know the year and month of birth, with the new field I could search for "Me" and with Birthdates and "Ma" and would possibly find my result. 
1. It should not remove the similiarity option, but replace it in the select option in the first gif and in this one: 
![image](https://user-images.githubusercontent.com/78568406/195789345-d7cf8cce-4179-4929-b85b-d1f6252e5abc.png)
The idea is to be more flexible.
2. If possible, yes, case, ep, contact and person ID would be awesome, but if this is more complex, I can deal with not having this in this search option.
3. You can move out the acceptance criteria, if you want.

**Comment by adinaflorea9** [comment]
Birthdate related heading from creation forms (case, contact, travel entry, immunization) is overlapped:
![image](https://user-images.githubusercontent.com/96909231/196669885-fedfcfae-fb62-485e-85e6-d71eaee8f888.png)

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following: in the search field, the first name and last name are misspelled:
![image](https://user-images.githubusercontent.com/96909231/196901337-ab13220b-b19e-4cac-8597-8d487c772f18.png)

**Comment by adinaflorea9** [comment]
I am reopening the ticket as year, month and day filter fields for a person's birth date have been removed from the 'Cases' directory.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(5eb3cdf).

**Comment by kathsievers** [comment]
ISSUE TRACKER COMMENT
<!-- ### Issuetracker-Description-DE[Anpassung der Suchoptionen in der Personensuche] Diese Funktion erweitert die Personensuche um die Suchmöglichkeit, eine Person auch über Jahr/Monat/Tag der Geburt zu filtern. Es kann nach dem Ganzen oder nur nach Teilinformationen der Person gesucht werden.
 
![personsearch_issuetracker](https://user-images.githubusercontent.com/97029882/199400330-6b1a0e21-c83d-416b-a752-b5b63494ae69.jpg)

[GitHub Issue (#8485)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8485) ### End-Description-DE →

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT
