### ISSUE TITLE
Duplicate merging of cases via bulk action

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#8486]
### Situation Description

Sometimes the duplicate detection of cases is not triggered even if the relevant dates (names, dob) are the same. Or there are more then one duplicate. 

### Feature Description

Make the merging available through the bulk action. 

A pop-up should open to select the leading case.

**Comment by kwa20** [comment]
@Marko-ilmkreis I've update the original description of #5606 which is basically describing what is mentioned here. I would therefore close this issue as a duplicate.
