### ISSUE TITLE
District field is populated and has the 'inactive' suffix in the Cases Bulk Edit Mode -> Edit, when 2 Cases that have the same Region and District are selected

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8493]
### Bug Description
District field is populated and has the 'inactive' suffix in the Cases Bulk Edit Mode -> Edit, when 2 Cases that have the same Region and District are selected

### Steps to Reproduce

1. Open Cases Directory and access Bulk Edit Mode;
2. Select 1 Case and click on Bulk Actions -> Edit;
3. Inspect the Region and District fields.
-> They are populated accordingly
![image](https://user-images.githubusercontent.com/89522688/159557954-be525f25-33af-41bc-845a-0c444969f1b2.png)
4. Select at least 2 Cases that have the same Region and District, and then click on Bulk Actions -> Edit;
5. Inspect the Region and District fields.

### Actual Behavior
The Region field is cleared;
The District field is populated with the District name and it is has an 'inactive' suffix;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/159558066-ffee7ccf-1f6f-4dbd-8934-3fa4533d4863.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT (9d06a5b)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

**Comment by MateStrysewske** [comment]
Quick information: This is probably caused by a bug in the code that compares the region dropdown value with the districts of the selected cases (which of course can't ever work) as long as more than one case is selected.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.71.0 -snapshot on local environment
