### ISSUE TITLE
[Cases] Duplicate detection is not triggered in line listing

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8499]
### Bug Description

The duplicate detection is not triggered if a specific set of steps is reproduced when creating cases via line listing, or via the 'Create new case' form.

### Steps to Reproduce

Steps to reproduce via 'Line listing':
1. Navigate to the 'Cases' directory and click on 'Line listing';
2. Select values for the mandatory fields from the section 'Shared information';
3. In the section 'List of new cases', input the report date and select a facility;
4. Click to add a new line and add at least 1 line in the form;
5. Input the first and last name in all lines of the form (first and last name have to be very similar - first name: AD-BBB; last name: BBB);
6. Select the same gender for each line;
7. To each first name add 1 differentiating value (AD-BBB1; AD-BBB2);
8. Click 'Save'.

Steps to reproduce via 'Create new case' form:
1. Navigate to the 'Cases' directory and click on 'New case';
2. Select information for the mandatory fields;
3. Input the first and last name (first and last name have to be very similar - first name: AD-DDD1; last name: DDD);
4. Click 'Save';
5. Open the 'Create new case' form again and input the same information in the mandatory fields as for the case created at step 4;
6. Input the first and last name (first and last name have to be very similar - first name: AD-DDD2; last name: DDD);
7. Click 'Save'.

### Actual Behavior

Duplicate detection is not triggered - all the cases listed are created and there is a new person for each one.

### Expected Behavior
 
Duplicate detection is triggered - 'Pick or create person' form is triggered for each entity that has a match in the system.

### Screenshots

GIF of the steps to reproduce via 'Line listing':
![Steps - duplicate detection not triggered](https://user-images.githubusercontent.com/96909231/159668059-732b014c-cd00-4d88-b1c1-269fbbc4ead9.gif)

GIF of steps to reproduce via 'Create new case' form:
![Steps - duplicate detection not triggered for create new case](https://user-images.githubusercontent.com/96909231/159670904-e6d41547-d20a-4fa9-b032-15e1a67a042e.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(d8dfa6d)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by alexcaruntu-vita** [comment]
The similarity score for the examples in this ticket is below 0.65 (the one that we use to determine if two names are similar), therefore the functionality is as expected. If other outcome is desired, one can set a different threshold value in sormas.properties file.
