### ISSUE TITLE
Validate all URLs we have as properties

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8500]
### Feature Description
URL validation in config facade

### Problem Description
Not all URLs present in a properties file are validated

### Proposed Change
Validate all URLs

### Additional Information
Spawned from https://github.com/hzi-braunschweig/SORMAS-Security/issues/36

**Comment by leventegal-she** [comment]
My system doesn't start up because of a valid configuration for maps:
```
map.tiles.url=https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}
```
