### ISSUE TITLE
Refactor clearing completeness in onCaseChanged [2]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8502]
### Problem Description

We always set the completeness of a case to null when executing `onCaseChanged` in order to trigger the cron job that updates the completeness of all relevant cases. However, this results in a user-initiated change of the case, which also updates the change date and sets the current user as the change user (as introduced by #7323), even though the user might not have done any manual changes on that case at all (e.g. when they've updated an associated contact).

### Proposed Change

Add a new `clearCompleteness` method to CaseService that executes an update query which sets the completeness to null; by bypassing the JPA layer, we avoid updating the change date and change user. Add the `@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)` annotation to this method (and probably `@RolesAllowed(UserRight._SYSTEM)`, not sure whether that'll work though). Replace the `setCompleteness(null)` call in onCaseChanged with this new method.

Make sure that this actually works as expected; if it doesn't, we need to find a different solution.

**Comment by StefanKock** [comment]
See #10425: The architecture causes a apperently a transaction lock.

In general, I don't get why one changed attribute is a problem since `CaseFacadeEjb.onCaseChanged` changes multiple other attributes.

**Comment by MateStrysewske** [comment]
@adinaflorea9 Fixed the cause of the endless loading; please verify :)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS  from the development branch - 1.76.0-SNAPSHOT(40b7f83) - cases and entities related to cases can be created, edited and saved.
