### ISSUE TITLE
Add backend checks for contact, visit and missing case-related user rights [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8508]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. #5057 and #445 have done this for the CaseFacade and PersonFacade and partly also for the ContactFacade.

Depdends on #8352.

### Proposed Change

Make sure all user rights for the facades listed below are checked. 
For most of the facades there is a corresponding _VIEW user right that should be used as a class anotation, so it's not necessary to annotation every singler getter. 
Most of the user rights can simply be annotation to the methods (RolesAllowed).
For some user rights you may have to do the check within the method instead of using an annotation.

- [x] ContactFacadeEjb
- [x] VisitFacadeEjb
- [x] BAGExportFacadeEjb-> just BAG_EXPORT for the facade
- [x] CaseImportFacadeEjb -> just CASE_IMPORT for the facade
- [x] ExternalJournalFacadeEjb -> just MANAGE_EXTERNAL_SYMPTOM_JOURNAL for the facade
- [x] PrescriptionFacadeEjb
- [x] TreatmentFacadeEjb
- [x] SurveillanceReportFacadeEjb -> use CASE_... rights
- [x] ClinicalVisitFacadeEjb
- [x] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RolesAllowed including UserRight._SYSTEM.
- [x] Introduce an ArchUnit test that makes sure that all methods of the Facade interface implemented by the FacadeEjb either are annotated with RolesAllowed or start with "get, count, is, does, has, validate. Execute this test for CaseFacade, ContactFacade, VisitFacade and the other facades mentioned here.

**Comment by leventegal-she** [comment]
@MartinWahnschaffe 

CONTACT_ASSIGN, CONTACT_CLASSIFY are not used, **do we delete them?**

CONTACT_CONVERT is handled in UI code(in CaseController::createFromContact) using a simple case save and changing also other possible contacts and event participants in different transactions, so checking the right in case creation  or contact save could still introduce  corrupt data so it needs to be refactored and moved to the backend so there could use @RolesAllowed to authorise this action, or we could just keep it as a UI only right.

**Refactoring is out of scope for this ticket. A new ticket is should be created if needed.**

CLINICAL_COURSE rights seem to be redundant, could be a combination of TREATMENT and PRESCRIPTION rights.
**Getting rid of  CLINICAL_COURSE rights is out of scope for this ticket.  A new ticket is should be created if needed.**

**Comment by MartinWahnschaffe** [comment]
CONTACT_ASSIGN/CLASSIFY: I have extended #5058
CONTACT_CONVERT: Let's leave as-is. #5058 takes care of making sure the user case CONTACT_EDIT and CASE_CREATE.
CLINICAL_COUSE: No, actually it's correct the way it is. Clinical course is about a list of clinical visits. Treatments and presecriptions belong to the therapy part of clinical management.
