### ISSUE TITLE
"Responsible disease" dropdown missing from Case person and Person

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8509]
### Bug Description
When a Case is created with other disease than Covid, and condition of the person is selected to be Buried, then at edit Case person and Person the dropdown for "Responsible disease" is not present

### Steps to Reproduce
1. As NatUser create a Case with disease different than Covid
2. At the area for present condition of the person, choose Buried
3. Save the new case
4. Edit the Case
5. Look at the Case person tab and check for the existence of the dropdown "Responsible disease"
6. Change the present condition to Dead and then back to Buried
7. Exit the edit mode without saving and check the same dropdown("Responsible disease") at the Person page for the person above

### Expected Behavior
The "Responsible disease" dropdown should be present when having the step 5 and 7

### Actual Behavior
The "Responsible disease" dropdown is missing at the step 5 and 7 and appears at the step 6

### Screenshots

<img width="1376" alt="Screenshot 2022-03-23 at 14 25 03" src="https://user-images.githubusercontent.com/91872179/159712132-fe80a5f3-b32c-4331-9532-9e9af9619c81.png">

### System Details

* Device:
* SORMAS version: 1.70.0-snapshot(20a2e7c)
* Android version/Browser:
* Server URL: local environment
* User Role: NatUser

**Comment by abrudanancuta** [comment]
The dropdown "Responsible disease" appears when the Epidemic disease from "Cause of Death" is selected.
If Cause of death is left empty then the Responsible disease dropdown is not present.

The "Cause of death" dropdown has automatically selected the first option if Buried or Death is chosen at edit mode.
When creating a new Case this dropdown of Cause of death is not present and then the value that is saved for it, is the empty one, this is the reason why the Responsible disease dropdown is not present.

Maybe the same should happen at edit mode that when choosing Buried or Death, the Cause of death should not take automatically the first option(Epidemic disease) and let it empty until user decides to select one of those 2 options.

**Comment by MateStrysewske** [comment]
@abrudanancuta That's basically a shortcut because if a user enters a person through a case and sets the present condition to dead or buried there, it is very likely that the case disease has caused the death. :)

As far as I can see, everything works as expected, so I'm closing this issue.
