### ISSUE TITLE
"Present Condition" remains empty and visible the fields connected to Buried option if at Event is added later Covid as disease

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8510]
### Bug Description
"Present Condition" remains empty when Event is created without a disease, but the present condition of the Event Participant is Buried, and later at edit mode the Event has as disease Covid

### Steps to Reproduce
1. As NatUser create an Event without disease
2. Add an Event participant with "Present Condition" set up Buried
3. Go to edit mode for the Event above and add Covid as disease
4. Check the Event Participant "Present Condition" dropdown

### Expected Behavior
Hide the fields connected to the Buried option

### Actual Behavior
"Present Condition" is empty and the fields related to Buried option are visible

### Screenshots

<img width="1037" alt="Screenshot 2022-03-23 at 14 53 04" src="https://user-images.githubusercontent.com/91872179/159715708-c9811d9f-f531-4e1b-98c7-7401c9d21d6d.png">

### System Details

* Device:
* SORMAS version: 1.70.0-snapshot(https://github.com/hzi-braunschweig/SORMAS-Project/commit/20a2e7cf1e955fdd397b5541a1385c583e3e83f6)
* Android version/Browser:
* Server URL: local env
* User Role: NatUser

**Comment by MateStrysewske** [comment]
@abrudanancuta This is very likely related to #8072, can you please add your findings as a comment there?

**Comment by abrudanancuta** [comment]
Test case added in the comment for the issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/8072
