### ISSUE TITLE
[Angular] User Settings: Change Language functionality [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8520]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/72E1AD53-5809-4819-BB86-83FE0DDED751
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/PGdkg7v 
- We will focus on the "Personal information section" and leave the rest empty
-  @cristinacoza please add the flags as .png to this task for the team to use.
- The language selection for the user should be locally stored without any BE call 

### QA Section

1. What should the QA look for (what was done)
- Check that we have all of the available languages
- Check that when we change the language, said translations are used across the site
  
2. What can the QA ignore (what was omitted)
- The "Description" and "User rights" sections are ignored.
- Make sure that the language is memorised in the local storage. 
- Ignore the "Role" and "Juristiction" as it won't be implemented. 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good !
