### ISSUE TITLE
[Angular] Serialisers: Refactoring [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8521]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to remove all of the serialisers and replace them with only one such serialiser 

### QA Section

1. What should the QA look for (what was done)
- N/A
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by sandorbanvitagroup** [comment]
@RobertoDascalu Please check here that the pages are working and the calls are retrieving the necessary info. Nothing visual should be changed as it was a refactor only.
