### ISSUE TITLE
[Angular] Dashboard: Surveillance refactoring [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8522]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Gm43r4D
- We need to refactor the Surveillance dashboard layout to use Grid template as per the Contacts dashboard 
- It needs to be responsive 

### QA Section

1. What should the QA look for (what was done)
- Recheck the Surveillance dashboard
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done. All good !
