### ISSUE TITLE
[Angular] Event Actions [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8523]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yP4dZO
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/g0gl3wJ
- This should be a new module
- We will also implement the filters section 
- Note: Please check the icons on Contact Classification - Contact table

### QA Section

1. What should the QA look for (what was done)
- Check that the implementation resembles the design
- Check that the same fields are show as per the current Sormas implementation
- Check that the columns are sortable

2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
