### ISSUE TITLE
Add backend checks for event, event participant & action user rights [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8527]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. 

Depends on #8352.

### Proposed Change

Make sure all user rights for the facades listed below are checked. 
For most of the facades there is a corresponding _VIEW user right that should be used as a class anotation, so it's not necessary to annotation every singler getter. 
Most of the user rights can simply be annotation to the methods (RolesAllowed).
For some user rights you may have to do the check within the method instead of using an annotation.

- [x] EventFacadeEjb
- [x] EventParticipantFacadeEjb
- [x] ActionFacadeEjb
- [x] EventGroupFacadeEjb
- [x] EventImportFacadeEjb
- [x] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RolesAllowed including UserRight._SYSTEM.
- [x] Extend the archunit test implemented by #8508

### Additional Information
See #8508 for a similar issue.

**Comment by abrudanancuta** [comment]
Surveillance Supervisor at selecting "Enter bulk edit mode" from Events will display more Events that are not from his region.
Steps to reproduce:
1. Have some events that are not assigned to any region
2. Have some events assigned to the region belonging to the Surveillance Supervisor
3. Login as Surveillance Supervisor and go to Events page
4. Look at the overview of the Events
5. Select "Enter bulk edit mode"
=> at this point more Events are appearing, also the ones having no region

**Comment by abrudanancuta** [comment]
for the comment above I created a separate bug https://github.com/hzi-braunschweig/SORMAS-Project/issues/8899

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.71.0-SNAPSHOT (53cae66)
