### ISSUE TITLE
UnsupportedOperationException: "Dto is older than existing entity"

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#853]
On 1.4.0, this e.g. happened 42 times for user QCE3IV-NNL7EG-3TV4F6-56EPCI5E and 24 times for QMOVTE-TTSTC6-MP7CYJ-ORD2CJQY. We need to make sure that these aren't bugs we need to fix.

Also, this exception is currently wrapped as a ServerCommunicationException which maybe doesn't make much sense; also, the exception body is a HTML string, we should probably re-format it to only include the text without all the tags.

**Comment by MartinWahnschaffeSymeda** [comment]
Good chance this is solved by the other bugfixes. We will keep an eye on this.

**Comment by MartinWahnschaffeSymeda** [comment]
Also related to #963
