### ISSUE TITLE
Add backend checks for sample, immunization, travel entry & task user rights [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8531]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. 

Depends on #8352.

### Proposed Change

Make sure all user rights for the facades listed below are checked. 
For most of the facades there is a corresponding _VIEW user right that should be used as a class anotation, so it's not necessary to annotation every singler getter. 
Most of the user rights can simply be annotation to the methods (RolesAllowed).
For some user rights you may have to do the check within the method instead of using an annotation.

- [ ] SampleFacadeEjb
- [ ] LabMessageFacadeEjb, TestReportFacadeEjb: LAB_MESSAGES user right check for the whole class
- [ ] ImmunizationFacadeEjb
- [ ] VaccinationFacadeEjb
- [ ] TravelEntryFacadeEjb
- [ ] TaskFacadeEjb
- [ ] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RolesAllowed including UserRight._SYSTEM.
- [ ] Extend the archunit test implemented by #8508

**Comment by abrudanancuta** [comment]
validated on local environment with the version 1.71.0-SNAPSHOT (fa93e16)
