### ISSUE TITLE
Add backend checks for dashboard, report, outbreak & campaign user rights [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8539]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. 

### Proposed Change

Make sure all user rights for the facades listed below are checked. 
For most of the facades there is a corresponding _VIEW user right that should be used as a class anotation, so it's not necessary to annotation every singler getter. 
Most of the user rights can simply be annotation to the methods (RolesAllowed).
For some user rights you may have to do the check within the method instead of using an annotation.

- [x] DashboardFacadeEjb
- [x] WeeklyReportFacadeEjb
- [x] AggregateReportFacadeEjb
- [x] OutbreakFacadeEjb
- [x] CampaignFacadeEjb
- [x] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RolesAllowed including UserRight._SYSTEM.
- [x] Extend the archunit test implemented by #8508

**Comment by mario-kuehne** [comment]
Tested locally with 1.71.0-SNAPSHOT (b900a16a5f5055abfa6ae4994193d2eda5a159f9)

Campaign-Test

1) Set CAMPAIGNS = true in database table featureconfiguration
2) Create at least 1 campaign as user with role Admin
3) Check that other roles cannot create / edit campaigns
4) Check that specific other roles can only view campaigns
5) Check that only Admin can delete campaigns

Tested with following combinations:

|UserRight|Single Role|Allowed
|--|--|--|
|CAMPAIGN_VIEW|ADMIN|YES|
|CAMPAIGN_VIEW|NATIONAL_USER|YES|
|CAMPAIGN_VIEW|SURVEILLANCE_OFFICER|YES|
|CAMPAIGN_VIEW|CASE_OFFICER|YES|
|CAMPAIGN_VIEW|CONTACT_SUPERVISOR|YES|
|CAMPAIGN_VIEW|CONTACT_OFFICER|YES|
|CAMPAIGN_VIEW|EVENT_OFFICER|YES|
|CAMPAIGN_EDIT|ADMIN|YES|
|CAMPAIGN_DELETE|ADMIN|YES|
|CAMPAIGN_EDIT|NATIONAL_USER|NO|
|CAMPAIGN_DELETE|NATIONAL_USER|NO|
