### ISSUE TITLE
LastContactDate may not be after ReportDate

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#854]
Add validation to contact edit form to make sure that last contact date can not be set to a later date than report date.

  | ServerCommunicationException  - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException:  "lastContactDate has to be before reportDateTime" - Stack trace:  de.symeda.sormas.app.rest.RetroProvider:throwException:549 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pushEntities:171 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pullAndPushEntities:60  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:synchronizeChangedData:170  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:82  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:374  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:255 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Root cause stack trace:  de.symeda.sormas.app.rest.RetroProvider:throwException:549 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pushEntities:171 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pullAndPushEntities:60  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:synchronizeChangedData:170  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:82  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:374  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:255 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - User: QEPUCP-EZLZ3E-YJOYTT-5LEHKDFQ - System:  https://sormas.org.ng/sormas-rest/
-- | --

**Comment by MartinWahnschaffeSymeda** [comment]
see #792

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] validate last contact date in app
- [ ] fix old data in app database
