### ISSUE TITLE
Add backend checks for Sormas2Sormas [5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8540]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. 

### Proposed Change
We need to check user rights need to access the facade below and their methods. 

The following facades are very closely related and need to check whether the user has the S2S_SHARE user right and the EDIT user right for the respective entity (overrride the share method to add the needed RightsAllowed annotation).
Within the share method check whether other entities are included and whether the user has the needed user right for those.

- [x] AbstractSormasToSormasInterface
- [x] SormasToSormasCaseFacadeEjb
- [x] SormasToSormasContactFacadeEjb
- [x] SormasToSormasEventFacadeEjb
- [x] SormasToSormasLabMessageFacadeEjb

This also needs to be checked in the user interface for the sharing of

- [x] case(s)
- [x] contact(s)
- [x] event(s)
- [x] external message(s)

Furthermore:

- [x] SormasToSormasShareInfoFacadeEjb, SormasToSormasShareRequestFacadeEjb, SormasToSormasOriginInfoFacadeEjb: check S2S_SHARE and S2S_CLIENT user rights when creating/editing share meta objects. We don't have a dedicated user right to right share meta data and probably also don't need it.
- [x] SormasToSormasFacadeEjb: Add checks for S2S_SHARE and S2S_CLIENT
- [x] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RightsAllowed including UserRight._SYSTEM.
- [x] Extend the archunit test implemented by #8508

**Comment by abrudanancuta** [comment]
I have this case that returns a pop-up error with 500 Internal server error
1. From test.de1 share a case with selecting the checkbox "Exclude personal data" to test.de2
2. From test.de2 go to Share directory and try to accept the case

Actual result: A pop-up with an error appear
Expected result: The case should be accepted

Observation: On release environments the case is not reproducible

@leventegal-she  let me know if I need to create another ticket for it or it is enough to reopen the ticket

<img width="1440" alt="Screenshot 2022-08-26 at 19 29 19" src="https://user-images.githubusercontent.com/91872179/186960222-41af8fba-fe1e-42c0-b23e-5a50caeac15a.png">

**Comment by leventegal-she** [comment]
Created  https://github.com/hzi-braunschweig/SORMAS-Project/issues/10225 bug ticket for the issue found by @abrudanancuta

**Comment by abrudanancuta** [comment]
Validated on test.de1. test.de2 having the version: 1.76.0-SNAPSHOT (46772f5)
