### ISSUE TITLE
Add backend checks for infrastructure & user related user rights [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8541]
### Problem Description
We are missing checks for many of the user rights related to accessing the backend. 

### Proposed Change

Make sure all user rights for the facades listed below are checked. 
For most of the facades there is a corresponding _VIEW user right that should be used as a class anotation, so it's not necessary to annotation every singler getter. 
Most of the user rights can simply be annotation to the methods (RolesAllowed).
For some user rights you may have to do the check within the method instead of using an annotation.
All infrastructure related facades need to be annotated with the INFRASTRUCTURE... user rights.

- [x] Discuss: Should we rename USER_VIEW? It is ony relevant to decide whether the user should see the users directory in the UI. In general users need to be able to load user data, e.g. to sync all users to the mobile app or to provide users for a drop-down
- [x] UserFacadeEjb -> don't use USER_VIEW
- [x] UserRoleFacadeEjb (introduced by #4461) -> re-use USER_CREATE & USER_EDIT
- [x] Continent/Subcontinent/CountryFacadeEjb 
- [x] Area/Region/District/CommunityFacadeEjb
- [x] FacilityFacadeEjb
- [x] PointOfEntryFacacadeEjb
- [x] Check usage of these facades in the StartupShutdownService and CronService and make sure called facade methods are annotated with RolesAllowed including UserRight._SYSTEM.
- [x] Extend the archunit test implemented by #8508

**Comment by vidi42** [comment]
We should rename `USER_VIEW` to `USER_DIRECTORY_VIEW` to emphasize it just refers to view on the UI

**Comment by StefanKock** [comment]
> We should rename `USER_VIEW` to `USER_DIRECTORY_VIEW` to emphasize it just refers to view on the UI

I discussed with @leventegal-she about the suggested refactoring. I have two objections against it:
1. It breaks the pattern to other `UserRight` names without a real reason. Pointing out that some methods are only for directory view (what many other `ENTITY_VIEW` user rights are also) could be done by an additional permission. And what the use case of the existing `UserRight` is should be documented in code, manual etc. if it is not intuitive.
2. Adding `@PermitAll` to other endpoints concerning users also does not restrict to a logged in user.

**Comment by vidi42** [comment]
@leventegal-she what is needed for this issue to be picked up again?

**Comment by StefanKock** [comment]
Needs to wait for #4461 and resolve discussion points

**Comment by MartinWahnschaffe** [comment]
Discussed with @leventegal-she again and we came to the conclusion that 

1. PermitAll is fine in this situation. Access to the backend currently has to go through rest or ui which both require an authenticated user. If we come up with another use case we can extend the backend to require a user.
2. We will keep USER_VIEW. Yes, it's different from CASE_VIEW, because users still need to access all users, so they can assign them to other data, but on the other hand they should not be able to open a view that shows all the details of the user.

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.76.0-SNAPSHOT (9f50300)

**Comment by MateStrysewske** [comment]
I have to reopen this issue again because it breaks read-only (case) forms. There's an AccessDeniedException associated with retrieving the "NO_FACILITY" facility via the `getByUuid` method, I guess because FacilityFacade and FacilityFacadeEjb don't have a dedicated method for this and the call gets instead redirected to AbstractBaseEjb which does not have `@PermitAll` annotations

**Comment by abrudanancuta** [comment]
> I have to reopen this issue again because it breaks read-only (case) forms for users that don't have the INFRASTRUCTURE_VIEW user right (e.g. Surveillance Officer). There's an AccessDeniedException associated with retrieving the "NO_FACILITY" facility via the `getByUuid` method, I guess because FacilityFacade and FacilityFacadeEjb don't have a dedicated method for this and the call gets instead redirected to AbstractBaseEjb which does not have `@PermitAll` annotations

The issue specified by @MateStrysewske can be reproduced by opening a case that has Home set as Place of stay with a Surveilance Officer

**Comment by abrudanancuta** [comment]
Validated the fix #10347 on local environment with the version: 1.76.0-SNAPSHOT (1bafc02)
