### ISSUE TITLE
SQLException: Database entry was not updated

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#855]
There are multiple exceptions like this in 1.4.0:

`DaoException - Root cause: java.sql.SQLException: Database entry was not updated - update all entered fields and save again. - Stack trace: de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:339 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshotWithCast:249 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:308 -> de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:165 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15 -> android.os.AsyncTask$2:call:316 -> java.util.concurrent.FutureTask:run:237 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:776 - Root cause stack trace: de.symeda.sormas.app.backend.common.AbstractAdoDao:update:1061 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:328 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshotWithCast:249 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:308 -> de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:165 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15 -> android.os.AsyncTask$2:call:316 -> java.util.concurrent.FutureTask:run:237 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:776 - Entity: Case: UUL57T-3HO5VP-V245PH-UX5M2KNY - User: UBTPZ2-HF5HBU-55JRWG-BF57SOKU - System: https://sormas.org.ng/sormas-rest/`

. | DaoException  - Root cause: java.sql.SQLException: Database entry was not updated -  update all entered fields and save again. Location - Stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:339  ->  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshotWithCast:249  ->  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:308  ->  de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:165  ->
-- | --

  | DaoException  - Root cause: java.sql.SQLException: Database entry was not updated -  update all entered fields and save again. Epidemiological data - Stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:339  -> de.symeda.sormas.app.backend.epidata.EpiDataDao:saveAndSnapshot:74  ->  de.symeda.sormas.app.backend.epidata.EpiDataDao:saveAndSnapshot:18 ->   de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshotWithCast:249  ->  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:308  -> de.symeda.sormas.app.backend.caze.CaseDao:saveAndSnapshot:345  ->  de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:155
-- | --

**Comment by MartinWahnschaffeSymeda** [comment]
It was possible to call save multiple times in parallel which caused a multitude of possible crashes and very likely also this one.
