### ISSUE TITLE
New "Follow-up until"  date does not get updated when converting to case a contact with an existing positive sample with an earlier collection date

### ISSUE THREAD

**Issue by alexcaruntu-vita** [hzi-braunschweig/SORMAS-Project#8550]
1. Create a Contact with COVID-19 as Disease;
2. Add a Sample with a Collection Date prior to the Report Date of the Case and with a 'positive' Pathogen Test with COVID-19 as Disease and Save;
3. Click 'Yes' in the following pop-up:
![image](https://user-images.githubusercontent.com/89522688/156768270-c60f6cbe-303f-4e85-943c-34c8a643b591.png)
4. Fill in the mandatory data in the Create Case form;
5. Inspect the Follow-up Dates in the new created Case;

![image](https://user-images.githubusercontent.com/89522688/156768341-29ab2068-ee55-433c-9c1e-794463751307.png)

-> Only the 'Expected Follow-up' Date is updated accordingly, the 'Follow-up Until' Date isn't.
Also, if I Save the page again, the 'Follow-up until' Date is updated accordingly as well...

![image](https://user-images.githubusercontent.com/89522688/156768429-97b729f2-5feb-4ce1-b71a-87bc651fd9bb.png)

_Originally posted by @roxanamlendea in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8191#issuecomment-1059145251_

**Comment by adinaflorea9** [comment]
Verified ticket on test-de2.sormas.netzlink.com using SORMAS version 1.71.0-SNAPSHOT(https://github.com/hzi-braunschweig/SORMAS-Project/commit/42ae389667fd12dab1682a3ecbff26e12f99e56a).
