### ISSUE TITLE
[Angular][Bug] Cases: Export - Issues [] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8557]
### Steps to Reproduce

- Go to Case directory
- Click on More button
- Notice the Export section is expanded (by default): https://prnt.sc/ohVO4yBmcWp6
- Either click outside to close it or select on item from the list
- Now open again the menu by clicking More button
- Notice the Export section appears closed (it really isn't, if you click on it it doesn't expand, it actually closes and only on a second click it expands again): https://prnt.sc/0OpqPcamv0LA

### Expected Behavior

- The Export section should expand correctly
 
### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by cristinacoza** [comment]
Design for a simpler dropdown for More options here:
https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/ZOvzraJ
