### ISSUE TITLE
[S2S] Avoiding simultaneous work of two health departments - preventing sharing twice to the same target system as long as the target system has not yet accepted or rejected [2]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#8576]
### Problem Description

Currently a source system can send a case multiple times to a target system with different parameters. This allows two health departments to work together on one case. 

Steps to reproduce:
1. source system: share a case with hand over the ownership (parameters: hand over the ownership = true, comment = "With")
2. source system: share **the same** case **without** hand over the ownership (parameters: hand over the ownership = false, comment = "without")
3. target system: first accept the last request sent (Comment: "Without")
4. target system: then accept the request you sent first (Comment: "With")
5. change the year of birth in the source system and in the target system
6. check the "share-box" (tab: case, on the right, between "vaccination-box" and "reporting-tool-box") in the source system and in the target system
7. check the sync in both directions by changing year of birth in source system and target system

Expected result: 
6.1 the share box in the source system shows the comment "without" (so the source system thinks it shared without hand over the ownership, because this was the last executed)
6.2 the share box in the target system shows the comment "with" (so the target system thinks it accepted with hand over the ownership, because this was the last executed accepted request)
7.1 the sync works in both direction

That is a big problem for example because of automatic reporting system in the background.
(This scenario can occur if one employee share a case by mistake with hand over the ownership, then realises that she/he made a mistake and then shares again without hand over the ownership. Because the last send request is the highest in the target system the employee from target system will accept the last send request first. 

### Proposed Change

A source system should only be able to send a case once as long as the target system has not yet accepted or rejected. If a case  has been sent by mistake, the case must be taken back (revoke), first. Then the case can be shared again. 
Perhaps technically feasible by target system checking whether there is an open request for the GUID already. If so, an error message is displayed in the source system. 
-> must be implemented for contacts to.

=> For Events and external messages this should be done as well

### Additional Information

source system: release-sormas-x
target system: release-de
1.69.1
Edge

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by AndyBakcsy-she** [comment]
Validated ticket during a peer testing session with Levi.

**Comment by SahaLinaPrueger** [comment]
Thanks a lot for implementing this sentence at this place and the whole behaviour around it (greyed out 'share' button and so on.) Really nice!
![Like](https://user-images.githubusercontent.com/100844689/178997572-9c655024-34b1-4b41-8939-f54077ef2176.png)
