### ISSUE TITLE
Fields related to the present condition of person 'Buried' are always displayed on the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8578]
### Bug Description

The fields 'Date of burial', 'Burial conductor' and 'Burial place description' are always displayed on the person page, on the android app, regardless of the present condition of person selected, when any other disease than COVID-19 is set for the entity associated with the respective person.

### Steps to Reproduce

1. Open the android app from the server URL:  https://test.sormas.netzlink.com/sormas-rest/;
2. Create a new entity (case, contact or event participant) and set the disease to any value other than COVID-19;
3. Navigate to the person page of the entity created at step 2;
4. Observe the fields displayed under the 'Present condition of person' dropdown; set the present condition of person to any other value than 'Buried'.

### Actual Behavior

The fields 'Date of burial', 'Burial conductor' and 'Burial place description' are always displayed. If information is inputted into the fields it is not cleared regardless of the 'Present condition of person' selected.

### Expected Behavior

The fields 'Date of burial', 'Burial conductor' and 'Burial place description' should only be displayed when the 'Present condition of person' is set to 'Buried'.

### Screenshots

![InkedMicrosoftTeams-image_LI](https://user-images.githubusercontent.com/96909231/160378386-d3cc3eab-78fd-4216-84b8-1e3828167d8c.jpg)

### System Details

* Device: Pixel 2
* SORMAS version: 1.70.0
* Android version/Browser: Android 10 - SORMAS app
* Server URL: APK download: https://test.sormas.netzlink.com/downloads/release/ + Server URL: https://test.sormas.netzlink.com/sormas-rest/
* User Role: Admin, NatUser

**Comment by dinua** [comment]
i mange to reproduce the bug with dieses ebola

**Comment by adinaflorea9** [comment]
Verified ticket using the latest version of SORMAS 1.71.0-SNAPSHOT on the mobile app: 
APK download: https://test.sormas.netzlink.com/downloads/release/
Server URL: https://test.sormas.netzlink.com/sormas-rest/
