### ISSUE TITLE
SQLiteConstraintException: UNIQUE constraint failed

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#858]
`DaoException - Root cause: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: cases.snapshot, cases.uuid (Sqlite code 2067), (OS error - 2:No such file or directory) - Stack trace: de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:339 -> de.symeda.sormas.app.backend.caze.CaseDao:saveAndSnapshot:357 -> de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:166 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15 -> android.os.AsyncTask$2:call:316 -> java.util.concurrent.FutureTask:run:237 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:776 - Root cause stack trace: android.database.sqlite.SQLiteConnection:nativeExecuteForLastInsertedRowId:-2 -> android.database.sqlite.SQLiteConnection:executeForLastInsertedRowId:818 -> android.database.sqlite.SQLiteSession:executeForLastInsertedRowId:803 -> android.database.sqlite.SQLiteStatement:executeInsert:86 -> com.j256.ormlite.android.AndroidDatabaseConnection:insert:173 -> com.j256.ormlite.stmt.mapped.MappedCreate:insert:91 -> com.j256.ormlite.stmt.StatementExecutor:create:458 -> com.j256.ormlite.dao.BaseDaoImpl:create:329 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:create:1045 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:332 -> de.symeda.sormas.app.backend.caze.CaseDao:saveAndSnapshot:357 -> de.symeda.sormas.app.caze.edit.CaseEditActivity$2:doInBackground:166 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 -> de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15 -> android.os.AsyncTask$2:call:316 -> java.util.concurrent.FutureTask:run:237 -> java.util.concurrent.ThreadPoolExecutor:runWorker:1133 -> java.util.concurrent.ThreadPoolExecutor$Worker:run:607 -> java.lang.Thread:run:776 - Entity: Case: R7EPME-35BF5H-WIUVRL-Z7XFCADI - User: QMOVTE-TTSTC6-MP7CYJ-ORD2CJQY - System: https://sormas.org.ng/sormas-rest/`

**Comment by MartinWahnschaffeSymeda** [comment]
This is only related to 0.23.1 and was likely fixed by 3d2e5353ae9e668f75296a31543b13731a8583b8 for SORMAS 1.X
