### ISSUE TITLE
[Contacts] Date validations do not get cleared and an incorrect warning message is displayed in the line listing form

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8581]
### Bug Description

In the 'Contacts' directory, on the 'Create new contact form', 'Line listing form' and on the 'Contact' page, the date validations between the 'Report Date' - 'Date of First Contact' and 'Date of Last Contact' do not get cleared when only one of the fields is updated so that the date combination is valid.

In the 'Line listing form', the warning message displayed when the user tries to save the form after inputting an invalid date combination is not correct.

### Steps to Reproduce

I: 
1. Open a contact that has only the 'Report date' set;
2. Set the 'Date of last contact' to a date after the 'Report date';
=> date validation appears for the 'Date of last contact' field
3. Change the 'Report date' to the same date as 'Date of last contact'.
Actual behavior: date validation for 'Date of last contact' does not get cleared.

Note1: the same behavior can be observed when both the 'Date of first contact' and ''Date of last contact' are displayed.
Note2: the behavior can be observed on the 'Contact' page, 'Create new contact' form, and 'Line listing' form.
![image](https://user-images.githubusercontent.com/96909231/160387048-8722aa91-1113-4b6e-a216-d79b6960b378.png)

II: 
1. Open a contact and check the 'Multi-day contact' checkbox;
2. Set the 'Date of first contact' (10th) - set the 'Date of last contact' (9th)
=> date validation appears for the 'Date of last contact' field
3. Change the 'Date of first contact' (9th)
Actual behavior: date validation for 'Date of last contact' does not get cleared.

Note1: the same behavior can be observed if the date validation is triggered for the 'Date of first contact' and the 'Date of last contact' is the one updated.
Note2: the behavior can be observed on the 'Contact' page, 'Create new contact' form, and 'Line listing' form. 
![image](https://user-images.githubusercontent.com/96909231/160387261-0f46b922-dd6b-4c6b-b571-af9027c369b8.png)

III:
1. In the 'Contacts' directory, open the ''Line listing' form;
2. Fill in the mandatory fields with valid information;
3. For the 'Report date' and 'Date of last contact' set an invalid date combination
4. Click 'Save'.
Actual behavior: The warning message that appears is not related to the invalid date combination from the form.
![Incorrect error message](https://user-images.githubusercontent.com/96909231/160387499-8c695805-cc51-4112-81fc-570c74fcfa3d.png)

### Expected Behavior

Date validation should get cleared once either one of the date fields is updated so that the date combination is now valid.

The warning message displayed when the user tries to save the line listing form with an invalid date combination should be specific for the fields involved.

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(b45f35c)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin,, NatUser

### Additional Information

The behavior described in the ticket was observed while testing #8122. As discussed with @MateStrysewske this ticket was logged to include all the behavior observed.

**Comment by roxanamlendea** [comment]
The translation has been updated from Crowdin.
![image](https://user-images.githubusercontent.com/89522688/163551646-bc692ec2-4c23-4932-bb58-42af25c7d6c1.png)
