### ISSUE TITLE
[S2S] share requests directory - automatic zoom neglects what does not appear directly on the screen

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#8589]
### Bug Description

If the table in the "share request directory" does not show "accept" or "reject" at the beginning, the 100%-zoom-factor does not include the column for "accept" and "reject". If you scroll down, then you can not see the "reject" button anymore because it is cut off. 

### Steps to Reproduce

1. Go to the share request directory
2. Make sure that the entries to be seen do not contain any open share requests
3. Make sure that older entries, which can not be seen at first sight include open share requests
4. Go to the share request directory
5. Scroll down to an open share request
6. Try to reject the case ("reject" button is next to the "accept" button)

### Expected Behavior

It should be possible to see the "reject" button.
The zoom setting should be related to the entire directory, not only to the first visible table.

### Screenshots

![Adapted zoom Faktor](https://user-images.githubusercontent.com/100844689/160450483-b19daf1a-85df-47fc-aea5-7623072e4f3e.gif)

* Device: Windows 10
* SORMAS version: 1.70.0
* Android version/Browser: Edge
* Server URL: 
* User Role: admin

**Comment by JonasCir** [comment]
@SahaLinaPrueger I think I got confused with labels. Does HZI expect this to be in the hotfix or not?
Thanks for clarification.
CC @MateStrysewske @StefanKock

**Comment by SahaLinaPrueger** [comment]
Yes, we want this in the hotfix. @JaquM-HZI

**Comment by JonasCir** [comment]
![s2s](https://user-images.githubusercontent.com/20031875/160795907-1c9d4c00-1332-47c9-b8ff-c5046177aad9.png)

Unfortunately, I cannot reproduce, I get a horizontal scroll bar in all cases which allows me to go further to the right if one line is to long. Works for me on both on Firefox and Chromium (which should be close to Edge AFAIK)

**Comment by JonasCir** [comment]
This was done locally will try the release instance you used now

**Comment by SahaLinaPrueger** [comment]
Please note step 2: Make sure that the entries to be seen do not contain any open share requests

**Comment by JonasCir** [comment]
I can try add more accepted entries in front of the one to be accepted but I don't think this will make a difference.

**Comment by JonasCir** [comment]
the scroll bar is already there as the browse decided that one entry is to long, adding more entries to the panel wont change this verdict. What strikes me odd that apparently what the release returns triggers a completely different behavior.

**Comment by MateStrysewske** [comment]
@JonasCir I believe that adding more entries CAN change the verdict because we have lazy loading, i.e. if none of the initially loaded entries has these buttons, the grid will probably not be initialised like it is initialised for you right now (i.e. with the horizontal scrollbar).

**Comment by JonasCir** [comment]
Ah so everything thats not rendered will fetched, there are batch requests like to get the first 50 unconditionally?

**Comment by JonasCir** [comment]
FOR QA: Reproduction is tricky so see these screenshots:

Bad:
![bad](https://user-images.githubusercontent.com/20031875/160821698-cf22aea2-2f92-49a9-a645-007c63681320.png)
Good:
![good](https://user-images.githubusercontent.com/20031875/160821700-6b611202-ac35-4ae5-b566-1395c24457f4.png)

Bad example from the same server as the initial report, other screen shot locally, we can see that buttons are not pushed out anymore

**Comment by adinaflorea9** [comment]
Verified ticket in peer to peer testing with @JonasCir on his local machine on the hotfix branch. Behavior from the bug report is no longer reproducible. If the user zooms in to more than 100% a horizontal scroll bar allows them to see both the 'Accept' and 'Reject' buttons.
