### ISSUE TITLE
IllegalArgumentException: Can't save a snapshot

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#859]
`IllegalArgumentException  - Root cause: java.lang.IllegalArgumentException: Can't save a snapshot  - Stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:260  ->  de.symeda.sormas.app.contact.edit.ContactNewActivity$1$1:doInBackground:157  ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Root cause stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:260  ->  de.symeda.sormas.app.contact.edit.ContactNewActivity$1$1:doInBackground:157  ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:47 ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:15  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Entity: Contact:  TX6IBK-ALWFMR-YEGTM2-DVGJSDLI - User: S3VVBA-VLSEYZ-DZQMC5-G4OCKGOI -  System: https://sormas.org.ng/sormas-rest/`

**Comment by MartinWahnschaffeSymeda** [comment]
This bug is related to another bug that we already fixed #791.
The user tried to create a new contact using a snapshot person that should not have been selectable in the first place.
