### ISSUE TITLE
Edit Archived Entities doesn't work correctly

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#8590]
### Bug Description

If the feature config EDIT_ARCHIVED_ENTITIES false is, there for any other user than Admin, there should everything from archived entity be read only. This doesn't work correctly for all user roles.

### Steps to Reproduce

1. create a case
2. archive case
3. open the archived case as case officer
4. some values are read only, others not

### Expected Behavior

The whole entity should be read only.

### Screenshots

![Archieve -  read only](https://user-images.githubusercontent.com/78568406/160427607-24946b05-9310-4909-92dd-d08537663bc8.gif)

### System Details

* Device:
* SORMAS version: 1.70.0
* Android version/Browser: 
* Server URL:
* User Role: case officer

**Comment by syntakker** [comment]
@JaquM-HZI could not reproduce.

The described behaviour is reproducible having `EDIT_ARCHIVED_ENTITIE` set to true. After setting this to false, the case is not editable any more.
![image](https://user-images.githubusercontent.com/5616564/160595605-6c23128f-d13f-4c51-a122-5105c8d732e5.png)

Inspecting the code, I did not find anything hinting otherwise:

`CaseDataView`, l.202ff:
```java
		EditPermissionType caseEditAllowed = FacadeProvider.getCaseFacade().isCaseEditAllowed(caze.getUuid());

		if (caseEditAllowed.equals(EditPermissionType.ARCHIVING_STATUS_ONLY)) {
			layout.disable(ArchivingController.ARCHIVE_DEARCHIVE_BUTTON_ID);
		} else if (caseEditAllowed.equals(EditPermissionType.REFUSED)) {
			layout.disable();
		}
```
So the form is disabled entirely except for the Dearchiving button if `caseEditAllowed` is `ARCHIVING_STATUS_ONLY`.

`EditPermissionType caseEditAllowed` is determined as follows: 

`CasefacadeEjb`, l.3745ff:
```java
	public EditPermissionType isCaseEditAllowed(String caseUuid) {
		Case caze = service.getByUuid(caseUuid);

		return service.getEditPermissionType(caze);
	}
```

`CaseService`, l.1367ff:
```java
	@Override
	public EditPermissionType getEditPermissionType(Case caze) {

		if (caze.getSormasToSormasOriginInfo() != null && !caze.getSormasToSormasOriginInfo().isOwnershipHandedOver()) {
			return EditPermissionType.REFUSED;
		}

		if (!inJurisdictionOrOwned(caze) || sormasToSormasShareInfoService.isCaseOwnershipHandedOver(caze)) {
			return EditPermissionType.REFUSED;
		}

		return super.getEditPermissionType(caze);

	}
```

`AbsractCorAdoService`, l.147ff:
```java
	public EditPermissionType getEditPermissionType(ADO entity) {
		if (entity.isArchived()) {
			return featureConfigurationFacade.isFeatureEnabled(FeatureType.EDIT_ARCHIVED_ENTITIES)
				? EditPermissionType.ALLOWED
				: EditPermissionType.ARCHIVING_STATUS_ONLY;
		}

		return EditPermissionType.ALLOWED;
	}
```
That is, if an entiy is archived, the `getEditPermissionType` evaluates to `ARCHIVING_STATUS_ONLY` unless feature `EDIT_ARCHIVED_ENTITIES` is enabled.

**Comment by JaquM-HZI** [comment]
@syntakker the point is, that the feature config is set correctly and with other user roles and for example contacts, it works fine.

**Comment by JaquM-HZI** [comment]
@syntakker one more point. The behavior differs between two test instances. So ob 1401 everything works as expected, on 1402 there is the described behavior. Maybe the interesting point is, that something ist read only, if it is archived others not. Would you say this is expected behavior?

**Comment by syntakker** [comment]
@JaquM-HZI I tried again, but still cannot reproduce the error locally.

Steps:
- create case (both as Case Officer and as National User)
- archive case (as National User)
- view archived case with various users (Case officer, National User, Surveillance Supervisor, Admin)
None of these users was able to edit an archived case.
This result is supported by the code above: the user role is not used to determine whether or not the case form is disabled and thus not editable.

Can you add the URL of the test system you tested on?

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup where setting the EDIT_ARCHIVED_ENTITIES  to false will gray out any fields from archived cases
