### ISSUE TITLE
[User rights export table] Missing translations on the German version

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8593]
### Bug Description

The 'User Roles Export Table' is missing translations of some user roles descriptions in the German version.

### Steps to Reproduce

1. Click the 'User Settings' button and in the pop-up set the language to German/Deutsch;
2. Navigate to the 'Users' directory and download the 'User Rights Export Table' from the 'Export User Roles/Benutzerrollen Exportieren' button;
3. In the downloaded document, observe the 'Description/Beschreibung' section.

### Actual Behavior

Not all the user rights/roles descriptions are translated into German.

### Expected Behavior

All user rights/roles descriptions are translated into German.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/160559783-d4474fcd-719c-4390-b083-39683e7dca3f.png)

![image](https://user-images.githubusercontent.com/96909231/160559803-fa2c6de1-0b3e-4746-a9ae-e52a34d54e52.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(1dc6c47)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

#8374

**Comment by Marko-ilmkreis** [comment]
Here are a few more:

![image](https://user-images.githubusercontent.com/74791118/160602981-98354e8b-1dbf-4ab9-b90b-b564c438e1d4.png)

**Comment by adinaflorea9** [comment]
@Marko-ilmkreis those values have been covered by ticket #8374 that I mentioned in the 'Additional information' section of the current ticket. 

Those values have been translated in the latest version of the user roles document, that was downloaded from the SORMAS version 1.71.0-SNAPSHOT(https://github.com/hzi-braunschweig/SORMAS-Project/commit/1dc6c47d0e463aa6c2452ac0b2c6e26ed95134a0)

![image](https://user-images.githubusercontent.com/96909231/160604035-243439cc-86a2-4586-8558-c4f02665b024.png)

**Comment by Marko-ilmkreis** [comment]
Sorry. I havn't seen this.

**Comment by adinaflorea9** [comment]
Verified ticket on test-de3.sormas.netzlink.com using SORMAS version 1.71.0-SNAPSHOT(4828894). Translations are now present in the 'User Rights/Roles Export Table' for the values reported in the ticket.

![image](https://user-images.githubusercontent.com/96909231/161257680-5715607a-5235-4aaf-a878-7a06f6bcac4a.png)

![image](https://user-images.githubusercontent.com/96909231/161257701-350d91ed-9f85-409a-854a-587704ae4595.png)

I am reopening the ticket as for the following values there are no proper descriptions (and translations) in the EN and DE version of the 'User Rights/Roles Export Table':

![image](https://user-images.githubusercontent.com/96909231/161259601-7fd1df5b-dfa2-42db-a322-46c4fba4ddda.png)
![image](https://user-images.githubusercontent.com/96909231/161259620-41ae3ff7-3711-4c52-84f1-fa9087236d16.png)

**Comment by FredrikSchaeferVitagroup** [comment]
English text representation should now be present. The german translation requires a crowdin update.

**Comment by adinaflorea9** [comment]
Tried to verify the ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(bfaf3d6) - the English descriptions are present - the German translations have not yet been updated from Crowdin. Keeping the ticket in testing and will check it again on Monday.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(4f6e61b) - German translations have been updated.
