### ISSUE TITLE
IllegalstateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#860]
Happened multiple times on 1.4.0:

`IllegalStateException  - Root cause: java.lang.IllegalStateException: Can not perform this  action after onSaveInstanceState - Stack trace:  android.support.v4.app.FragmentManagerImpl:checkStateLoss:2053 ->  android.support.v4.app.FragmentManagerImpl:enqueueAction:2079 ->  android.support.v4.app.BackStackRecord:commitInternal:678 ->  android.support.v4.app.BackStackRecord:commit:632 ->  de.symeda.sormas.app.BaseLandingActivity:replaceFragment:53 ->  de.symeda.sormas.app.BaseLandingActivity:onResume:36 ->  de.symeda.sormas.app.BaseActivity$6:call:592 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:381 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:376  -> android.os.AsyncTask:finish:660 ->  android.os.AsyncTask:-wrap1:-1 ->  android.os.AsyncTask$InternalHandler:handleMessage:677 ->  android.os.Handler:dispatchMessage:110 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6251 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - Root cause stack trace:  android.support.v4.app.FragmentManagerImpl:checkStateLoss:2053 ->  android.support.v4.app.FragmentManagerImpl:enqueueAction:2079 ->  android.support.v4.app.BackStackRecord:commitInternal:678 ->  android.support.v4.app.BackStackRecord:commit:632 ->  de.symeda.sormas.app.BaseLandingActivity:replaceFragment:53 ->  de.symeda.sormas.app.BaseLandingActivity:onResume:36 ->  de.symeda.sormas.app.BaseActivity$6:call:592 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:381 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:376  -> android.os.AsyncTask:finish:660 ->  android.os.AsyncTask:-wrap1:-1 ->  android.os.AsyncTask$InternalHandler:handleMessage:677 ->  android.os.Handler:dispatchMessage:110 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6251 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - User:  SZTSAX-YN33FJ-JRSYUQ-JDULKOP4 - System:  https://sormas.org.ng/sormas-rest/`

**Comment by MateStrysewskeSym** [comment]
Very useful blog entry on why this exception happens:
https://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html

The best solution probably is to call replaceFragment in BaseLandingActivity in onResumeFragments instead of onResume.

**Comment by MateStrysewskeSym** [comment]
- [ ] Possibly replace this in all activities (test)

**Comment by MartinWahnschaffeSymeda** [comment]
This has lead to other issues:

- [ ] when reopening a app from background BaseListActivity.updateSubHeadingTitle gets a NullPointer
- [ ] ContactNewActivity has an initialization state where the new button is still visible and can be clicked which results in an error as well
