### ISSUE TITLE
Detailed Export for a large amount of cases does not work [5]

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#8609]
### Feature Description
As we are offering the detailed export of cases and do not have a limit for the number of cases that can be exported, the expectation should be fulfilled that the export works. 

### Problem Description
We have currently at least 2 health departments that complain that the detailed export of cases does not work. 
~~The query logs are available [here](https://wiki.vitagroup.ag/display/SORMAS/Performance+Taskforce+2022)~~ Just a stack trace given that the request takes too long, no insight what's really going wrong.

**Comment by BarnaBartha** [comment]
The refactoring to reduce the number of separate queries and select minimal DTO's needed has brought about ~15% improvement in performance for the case export.
[exportCasesPerformance.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/8618752/exportCasesPerformance.zip)
@StefanKock @MartinWahnschaffe the actual getExportList is called 2 times, do we have an idea why is that ? (i couldn't find it yet why it works like that)

**Comment by BarnaBartha** [comment]
### Before:
https://explain.dalibo.com/plan/KgQ
![Screenshot 2022-05-05 at 14 57 26](https://user-images.githubusercontent.com/8166805/166918597-6cdd3d5a-d89f-464f-9edd-246ea08f68a7.png)

### After:
https://explain.dalibo.com/plan/q3G
![Screenshot 2022-05-05 at 14 57 04](https://user-images.githubusercontent.com/8166805/166918483-2b118eb2-83bb-4dd1-8609-06b8d061697c.png)

**Comment by BarnaBartha** [comment]
Latest comparison for same amount of cases but with custom export all fields

### Before:
![image](https://user-images.githubusercontent.com/8166805/168280212-b4ba0bcb-111b-4563-8d66-6cbab0a79d36.png)

### After:
![image](https://user-images.githubusercontent.com/8166805/168280129-ee198b51-aff0-467d-a000-3589f1a1a5d5.png)

**Comment by AndyBakcsy-she** [comment]
Tested this issue on the latest version of Sormas 1.72.0-snapshot on test-performance.sormas.netzlink.com environment
