### ISSUE TITLE
[PERFORMANCE] Merging of duplicates takes too long and sometimes leads to a Server Connection Lost

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#8615]
### Feature Description
One of the use cases that health departments encounter often is the merging of duplicates. For this use case the performance is essential to be productive. 

### Problem Description
Even limiting the search in terms of time does not lead to any improvement. 
After the health department has to merge several hundred duplicates, they need better performance of the system here.
The duration of merging duplicates takes in some cases 10 to 15 minutes and often even leads to a Server Connection Lost.

The Logs can be found [here](https://wiki.vitagroup.ag/display/SORMAS/Performance+Taskforce+2022)

**Comment by StefanKock** [comment]
Unclear: Is the merge view not loading does the save action not finish in reasonable time?

**Comment by MartinWahnschaffe** [comment]
Could be related to #8697 and will be analysed there.

**Comment by MartinWahnschaffe** [comment]
Also improved by #11465 and #11469
