### ISSUE TITLE
[Angular] Facilities: "Other" option [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8619]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: N/A
- We need to add an "Other" option to the facilities fields (append it to the end of the list). By selecting this option a new filed should be displayed "Facility Name and Description" -> This should be applied wherever the Facility field is displayed (exception: filters).
- The feature should be implemented in such a way that it could be used in other cases in the future

### QA Section

1. What should the QA look for (what was done)
- Check that we have the "Other" option for the Facility field.
- Check that the  "Facility Name and Description" field is displayed.
 
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done
-translation issue : events->new event-"captions.facility" instead of "facility"
-Contacts->Contact person->Add new address-user is able to choose "Facility category" and "Facility type" only after selecting the district(screenshot)
![image](https://user-images.githubusercontent.com/102517557/168279729-8eb9c33f-3cf3-4cb7-a2c6-17d7a8a2cff4.png)

**Comment by RobertoDascalu** [comment]
Testing done :
-events-add event-user should not be able to choose facility without choosing a district
-events-event-user should not be able to choose facility without choosing a district
-persons-home address-user should not be able to choose facility without choosing a district

**Comment by RobertoDascalu** [comment]
Testing done:
Immunization directory ,add new immunization and imunization case : 
-facility name and description field should be visible only after chosing other facility 
-facility name and description should be mandatory field
-Facility field should contain  "Other facility"  in dropdown after selecting a district

**Comment by RobertoDascalu** [comment]
Testing done - all good
