### ISSUE TITLE
Archiving info text does not line up with fields

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8628]
### Bug Description

The automatic archiving info text does not line up correctly in events and travel entries compared to other directories
### Steps to Reproduce

1. Open the event directory and filter for archived events
2. Open the travel entry directory and filter for archived travel entries

### Expected Behavior

Text should line up with other fields 
### Screenshots

<img width="319" alt="infoArchivingPosition2" src="https://user-images.githubusercontent.com/70317594/160837705-701fd230-6d0d-4b30-b885-6bc96f29ea14.PNG">
<img width="309" alt="infoArchivingPosition" src="https://user-images.githubusercontent.com/70317594/160837706-f9faa0c4-6448-4ca1-a8d3-1791bbb21a59.PNG">

### System Details

* Device:
* SORMAS version: 1.71-SNAPSHOT (1b0e18150214023461f760dfe22c0bc20627c225)
* Android version/Browser: chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.78.0-SNAPSHOT(4651358).
