### ISSUE TITLE
ValidationRuntimeException: You have to specify a valid health facility

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#863]
`ServerCommunicationException  - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException:  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html  xmlns="http://www.w3.org/1999/xhtml"><head><title>Payara  Server  4.1.2.172 #badassfish - Error report</title><style  type="text/css"><!--H1  {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;}  H2  {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;}  H3  {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;}  BODY  {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;}  B  {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;}  P  {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A  {color : black;}HR {color : #525D76;}--></style>  </head><body><h1>HTTP Status 500 - Internal Server  Error</h1><hr/><p><b>type</b> Exception  report</p><p><b>message</b>Internal Server  Error</p><p><b>description</b>The server  encountered an internal error that prevented it from fulfilling this  request.</p><p><b>exception</b>  <pre>javax.servlet.ServletException:  de.symeda.sormas.api.utils.ValidationRuntimeException: You have to  specify a valid health  facility</pre></p><p><b>root cause</b>  <pre>de.symeda.sormas.api.utils.ValidationRuntimeException: You  have to specify a valid health  facility</pre></p><p><b>note</b>  <u>The full stack traces of the exception and its root causes are  available in the Payara Server  4.1.2.172 #badassfish  logs.</u></p><hr/><h3>Payara Server  4.1.2.172  #badassfish</h3></body></html> - Stack trace:  de.symeda.sormas.app.rest.RetroProvider:throwException:549 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pushEntities:171 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pullAndPushEntities:60  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:synchronizeChangedData:168  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:82  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:376  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:255 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Root cause stack trace:  de.symeda.sormas.app.rest.RetroProvider:throwException:549 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pushEntities:171 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:pullAndPushEntities:60  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:synchronizeChangedData:168  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:82  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:114  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:376  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:255 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - User: U2NBLL-WXS4PE-CHV5OV-YUYDCC24 - System:  https://sormas.org.ng/sormas-rest/`

**Comment by MateStrysewskeSym** [comment]
This has already been fixed by calling the transfer case dialog with a clone. However, it also already caused a problem with case RIEDGQ-BCA3LZ-DOSTVD-363PKLGM on the Nigerian server which has no health facility (caused by this bug in version 1.3.1/1.4.0). This, in theory, could also be the reason for the data loss reported by the user who reported this case (see #818).

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Please make sure that case RIEDGQ-BCA3LZ-DOSTVD-363PKLGM has a health facility set in the database because this will continue to lead to problems. Tell us once this is done so we can close this issue.

**Comment by MateStrysewskeSym** [comment]
This should normally be prevented by backend validation (i.e. the health facility should not be deleted from the server database). The expected exception also was thrown, but apparently no rollback was done and the changes have been committed anyway. We need to check this.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Again, this is very important:
I have now assigned "other health facility" to case RIEDGQ-BCA3LZ-DOSTVD-363PKLGM to avoid any further problems for users of that region & districts. Please make sure this data is checked by the user who knows the exact health facility.
