### ISSUE TITLE
Some External Journal API Endpoints can not be used by REST_EXTERNAL_VISITS_USER

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#8638]
### Bug Description

The refactoring of user roles and rights has left interface in a broken state because the REST_EXTERNAL_VISITS_USER role does not seem to have sufficient rights anymore. Three relevant endpoints  of the ExternalVisitsResource seem to be broken

Call
  Response [explanation]

POST /person/{personUuid}/status
  false [Should be true, needs to be fixed. SORMAS logs show "Client not authorized for this invocation"]

GET /person/{personUuid}/isValid
  Access to the specified resource has been forbidden. [Should return a boolean value. Unclear whether this endpoint is in use. Depends on whether PIA still needs this endpoint or not.]

 
GET /followUpEndDates/{since}
  Access to the specified resource has been forbidden. [Should return a List of PersonFollowUpEndDtos. Unclear whether this endpoint is in use. Depends on whether PIA still needs this endpoint or not.]

### System Details

* SORMAS version: 1.70.1
* Server URL: local system
* User Role: REST_EXTERNAL_VISITS_USER 

### Additional Information

A solution could be adding the RolesAllowed(_EXTERNAL_VISITS) annotation to the related facade methods.

**Comment by leventegal-she** [comment]
Fixed using local configuration:
```
interface.symptomjournal.url=http://climedo.local.de/
interface.symptomjournal.authurl=http://climedo.local.de/auth
interface.symptomjournal.clientid=sormasclimedo
interface.symptomjournal.secret=secret
interface.symptomjournal.defaultuser.username=climedo
interface.symptomjournal.defaultuser.password=climedo
```
> url-s are not real ones

And using the api calls:
```
### external visit status
POST http://localhost:6080/sormas-rest/visits-external/person/T5LENU-Z66B6Y-TMAOQW-TMKWCP2Q/status
Authorization: Basic Y2xpbWVkbzpjbGltZWRv
content-type: application/json

{
  "status": "ACCEPTED"
}

###
GET http://localhost:6080/sormas-rest/visits-external/person/T5LENU-Z66B6Y-TMAOQW-TMKWCP2Q/isValid
Authorization: Basic Y2xpbWVkbzpjbGltZWRv
content-type: application/json

###
GET http://localhost:6080/sormas-rest/visits-external/followUpEndDates/0
Authorization: Basic Y2xpbWVkbzpjbGltZWRv
content-type: application/json

```

**Comment by vidi42** [comment]
Tested it locally using Levi's suggestions
