### ISSUE TITLE
location fields are not translated in several entities

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#8647]
### Bug Description

When you create a case and want to enter a home adress the first two boxes "country" and "region" are not translated. tested with different languages (germand and french)
### Steps to Reproduce

1. open Cases
2. create a new case
3. check "enter home adress of the case person now"
4. "country" and "region" are not translated

### Expected Behavior

"country" and "region" should be translated in the user language
### Screenshots

![image](https://user-images.githubusercontent.com/96547924/161033434-062da5ad-e0f6-4e7b-b026-35a2aa988268.png)

### System Details

* Device:
* SORMAS version: 1.70.0
* Android version/Browser:
* Server URL: test1402
* User Role: admin

### Additional Information

Tested with german and french translation

**Comment by kwa20** [comment]
This is also true for previous hospitalizations

![previousHospitalizationsTranslationMissing](https://user-images.githubusercontent.com/70317594/162016795-874974e3-1a62-420c-9146-620048a48250.PNG)

**Comment by adinaflorea9** [comment]
Tried to verify the ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(c946d77),  and test-de2.sormas.netzlink.com - 1.71.0-SANPSHOT(d49c3be) .

The missing translations have not been updated from Crowdin yet. Will keep the ticket in testing.

**Comment by adinaflorea9** [comment]
Tried to verify the ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(3880db9) and test-de3.sormas.netzlink.com - 1.71.0-SNAPSHOT(fee9521).

The missing translations have not been updated from Crowdin yet. Keeping the ticket in testing.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(f974e6f).

For the French version, the translations seem to not have been updated from Crowdin yet as all of the reported ones are still missing.

For the German version, the translations have been updated from Crowdin for certain parts of the UI, but in others they are still missing, for the same values, so I am re-opening the ticket:

DE:
- [ ] cases - hospitalization tab - previous hospitalization form;
- [ ] cases - epidemiological data tab - exposures - new entry form;
- [ ] cases - epidemiological data tab - activity as case - new entry form;

**Comment by adinaflorea9** [comment]
Tried to verify the ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(9512317) and on test-de2.sormas.netzlink.com - 1.71.0-SNAPSHOT(fee9521).

The missing translations have not been updated from Crowdin yet. Keeping the ticket in testing.

**Comment by adinaflorea9** [comment]
Tried to verify the ticket on the local machine using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(9239f6c) and on test.sormas.netzlink.com - 1.71.0-SNAPSHOT(4a0e87b).

The missing translations have not yet been updated from Crowdin. Keeping the ticket in testing.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(bfaf3d6) - the German translations reported in this ticket have been updated from Crowdin; the French translations have not yet been updated - keeping the ticket in testing until Monday to check the French translations again.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(4f6e61b) - the German translations have been updated; the French translations are not yet updated.
