### ISSUE TITLE
Arrival date is missing in the travel entries import guide

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8660]
### Bug Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/7845 recently added the `dateOfArrival` as a compulsory field in travel entries. However, it is not mentioned in the import guide which likely will lead to imports failing.
### Steps to Reproduce

1. Open the travel entries import guide
2. Try performing an import according to the provided instructions

### Expected Behavior

The `dateOfArrival` should be mentioned as a necessary field in the import guide.
### Screenshots

<img width="415" alt="arrivalDateGuide" src="https://user-images.githubusercontent.com/70317594/161226489-4a26aaf3-8ea3-4f79-b2d8-c85957d90eeb.PNG">
<img width="522" alt="arrivalDateGuide2" src="https://user-images.githubusercontent.com/70317594/161226493-3f7df15b-1b16-4f31-a712-07529178f979.PNG">

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT from the development branch (f974e6f).

![image](https://user-images.githubusercontent.com/89522688/163549246-cfe94644-8e42-4326-9c51-96e179ca4ae9.png)
![image](https://user-images.githubusercontent.com/89522688/163549257-a3489971-b47c-4025-b0d4-5580fbda8abb.png)
