### ISSUE TITLE
Person can be shared via S2S that cannot be updated afterwards 

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8674]
### Bug Description
This case https://release-sormas-x.sormas.netzlink.com/sormas-ui/#!cases/data/SPUZDY-CDXBOO-XDKHIO-2C6V2A3M
was successfully shared, however, updating it (e.g., changing the birthday) won't be synchronized to the other release instance as the server will receive a bad request from the remote.

The reported error in the receiver side (i.e., which returns the 400 status code), we see thanks to #8548 the following log:

```
Formatting the human readable message failed. I18nTag: sormasToSormasSaveException, arguments: [Sie müssen mindestens eine Einrichtungsart für die Adresse angeben, für die Sie die Ansprechpartner Kontaktdaten angegeben haben.] ([de.symeda.sormas.api.sormastosormas.SormasToSormasI18nMessageError.java:50](http://de.symeda.sormas.api.sormastosormas.sormastosormasi18nmessageerror.java:50/))
```

There are two bugs here:
1. `sormasToSormasSaveException` is used in `ValidationHelper.handleValidationError` however, it contains two `%s` format strings in the German version (I did not check the others), however, only the one argument is provided which causes the formatting to fail.
2. The failed validation string is `importPersonContactDetailsWithoutFacilityType` which is used [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java#L628) in `PersonFacadeEjb`. Somehow it is possible to share a case successfully with another instance via S2S, however, when we sync changes, the validation kicks in when the remote tries to call back the sharer wants to get back with us.
See this log: [log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8398487/log.txt)

Probably this can be fixed by mirroring the validation logic in S2S validation before sending? But duplication is in general a bad idea, so maybe there is away to reuse it. 

### Steps to Reproduce
This is the exported case causing the problem [spudzy_repro.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8398422/spudzy_repro.csv). Share it  with excluding personal data and observe that updating it (e.g., changing the birthday) won't be synchronized to the other release instance as the server will receive a bad request from the remote.

### Expected Behavior
Error formatting works correct and synchronization works/invalid cases are prevented from being shared in the first place

### System Details
* SORMAS version: 1.70.1
*  Release test environment

**Comment by AliciaRaber** [comment]
Hello Jonas. I was invited to test S2S functionality. I tested in same instance and found that data in case person was updated in both system (source --> target) accordingly. Actually the https://release-sormas-x.sormas.netzlink.com admin can not be accessed. Otherwise look for case SQHRW6-UHOQPQ-223XNG-AAW22C74 or let me know if you need further support.

**Comment by JonasCir** [comment]
Ok maybe somebody adjusted the case's address which caused the issue. I would really like to keep this ticket open as I'm quite certain neither of the two issues have been fixed so far :)

**Comment by JonasCir** [comment]
The issue persists. 
1. we only include the error message, not an identifier so this should be added to satisfy the two `%s`
2. The problem is that sharing with excluding personal data causes the contact person data to be anonymized, but still to be included as string ("Vertraulich" in German). Facility type, however, will be set to `null` what causes the exception to be thrown.

**Comment by SahaLinaPrueger** [comment]
Can we please label this bug as 'major'? It is very important that the parameter "exclude personal data = true" can also be used in the context of facilities. This should also work for data protection reasons.

**Comment by JonasCir** [comment]
There two other smaller and related problems here:
* It should not be possible to send an entity for which the standard validation fails. We should never rely on the roundtrip to the remote instance but catch the wrong entity as early as possible before sending it
* we need to adjust the einrichtungstyp

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup of Jonas during a peer testing session. 
The Case was shared successfully and the changes from system B were synchronized to system A without any errors
