### ISSUE TITLE
"see event cases" at an archieved event shows no cases

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#8676]
### Bug Description

When you open an archieved event and you click "see event cases" all the cases linked to the event should be filtered.

Filter is not working as long the event is archieved.

when you de-archive and then try to fetch the event cases it works.

it doesn't matter if the cases are also archieved or active.

### Steps to Reproduce

1.go to an archieved event
2.make sure it got cases connected
3.click "see event cases"
4.no cases are shown

### Expected Behavior

The cases should be displayed whether they are archived or not
### Screenshots

![archived events](https://user-images.githubusercontent.com/96547924/161509311-3c56c24a-188a-4493-aec5-643b2b8db875.gif)

### System Details

* Device:
* SORMAS version:1.70.1
* Android version/Browser:
* Server URL:test1402
* User Role:admin

**Comment by dinua** [comment]
@MateStrysewske  should this also be fix for "see  event contacts " button ? iti is the same there

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(7b8ebd5).

Configured the EDIT_ARCHIVED_ENTITIES feature to be set to 'true' so that archived entities would be editable.
