### ISSUE TITLE
IllegalArgumentException in onResume

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#868]
`IllegalArgumentException  - Root cause: java.lang.IllegalArgumentException - Stack trace:  android.os.Parcel:readException:1687 ->  android.os.Parcel:readException:1636 ->  android.app.ActivityManagerProxy:isTopOfTask:5577 ->  android.app.Activity:isTopOfTask:6043 ->  android.app.Activity:onResume:1278 ->  android.support.v4.app.FragmentActivity:onResume:485 ->  de.symeda.sormas.app.BaseActivity:onResume:207 ->  de.symeda.sormas.app.BaseLandingActivity:onResume:35 ->  de.symeda.sormas.app.BaseActivity$6:call:599 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:379 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:374  -> android.os.AsyncTask:finish:660 ->  android.os.AsyncTask:-wrap1:-1 ->  android.os.AsyncTask$InternalHandler:handleMessage:677 ->  android.os.Handler:dispatchMessage:110 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6251 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - Root cause stack trace:  android.os.Parcel:readException:1687 ->  android.os.Parcel:readException:1636 ->  android.app.ActivityManagerProxy:isTopOfTask:5577 ->  android.app.Activity:isTopOfTask:6043 ->  android.app.Activity:onResume:1278 ->  android.support.v4.app.FragmentActivity:onResume:485 ->  de.symeda.sormas.app.BaseActivity:onResume:207 ->  de.symeda.sormas.app.BaseLandingActivity:onResume:35 ->  de.symeda.sormas.app.BaseActivity$6:call:599 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:379 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:onPostExecute:374  -> android.os.AsyncTask:finish:660 ->  android.os.AsyncTask:-wrap1:-1 ->  android.os.AsyncTask$InternalHandler:handleMessage:677 ->  android.os.Handler:dispatchMessage:110 -> android.os.Looper:loop:203  -> android.app.ActivityThread:main:6251 ->  java.lang.reflect.Method:invoke:-2 ->  com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1063 ->  com.android.internal.os.ZygoteInit:main:924 - User:  XDPRCG-ILEIGX-VXUN7I-4IDU2LLQ - System:  https://sormas.org.ng/sormas-rest/`

**Comment by MateStrysewskeSym** [comment]
This looks like a random bug that we possibly don't really have influence on. It only happened twice for a single user. We probably should ignore it?

**Comment by hendrawd** [comment]
Maybe because of https://issuetracker.google.com/issues/66849632
