### ISSUE TITLE
lab messages can not be assigned to other users

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#8681]
### Bug Description

lab messages can not be assigned to other users
only the "assign to me" button works
### Steps to Reproduce

1.open the lab message directory
2.try to assign a lab message

### Expected Behavior

a list of all active useres should be avaliable
### Screenshots

![lab messages](https://user-images.githubusercontent.com/96547924/161537179-579059d6-2342-46d9-82a9-665dc63f30a1.gif)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser:
* Server URL:test1402
* User Role:admin

### Additional Information

same problem in bulk mode
also the filter is not working (even if it is assigned to myself, i cannot choose the current user)

**Comment by FredrikSchaeferVitagroup** [comment]
@cmeyerhzi Are you sure about the expected behaviour you describe? 
From what I know, a list of all active users with the LAB_MESSAGES user right and in the same region as the current user should be available.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @cmeyerhzi Available users should be users that have the user right LAB_MESSAGES. This has so far only been given to National Users and Surveillance Supervisors. I think the jurisdiction did not play a role in displaying the available users.

https://github.com/hzi-braunschweig/SORMAS-Project/issues/2804 or related issues might have had an impact on the previous behaviour.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 The jurisdiction did play a role, at least for assigning. For the sake of this ticket, I propose to keep that. If you want the jurisdiction to not play are role, I think it would be appropriate to create a change request.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I didn't see the jurisdiction mentioned here https://github.com/hzi-braunschweig/SORMAS-Project/issues/7310 but it should be fine as long as it doesn't cause the issue now. For the example here, the current user technically has a national jurisdiction, I think it should see any available active user then

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 It looks like the filter for regions was there right from the beginning (at least in the edit assigne form). This was not specified, but implied by general jurisdiction rules.
This sprint, a related backend method has changed its behaviour from returning all matching users when not region is provided, to returning no users. That's probably why there is a problem now. National User, for example, don't have a region, but should be allowed to see all.
When you say that filtering for jurisdiction is not required here, the easiest solution is to just remove it.

**Comment by FredrikSchaeferVitagroup** [comment]
> @kwa20 It looks like the filter for regions was there right from the beginning (at least in the edit assigne form). This was not specified, but implied by general jurisdiction rules. This sprint, a related backend method has changed its behaviour from returning all matching users when not region is provided, to returning no users. That's probably why there is a problem now. National User, for example, don't have a region, but should be allowed to see all. When you say that filtering for jurisdiction is not required here, the easiest solution is to just remove it. So: no change request needed :)

After an internal discussion it was decided to just restore the previous behaviour, so it is still filtered by jurisdiction.
Reason is that not filtering by jurisdiction really does not make sense for countries other that germany, and lab messages still are an international feature.
So in contrast to what I stated earlier, you do need to create a change request if you want this changed. I'm sorry for the back-and-forth, that was how the battle went.

**Comment by abrudanancuta** [comment]
Validated together with @FredrikSchaeferVitagroup at his local environment having the hotfix branch
