### ISSUE TITLE
[Angular] Contacts: Custom Configuration Export [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8692]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1Ox22g
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP0WOOJ

### QA Section

1. What should the QA look for (what was done)
- Check that the current options are per the same as the current Sormas implementation
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - certain fields are not selected/deselected when you click on Select all/Deselect all
![image](https://user-images.githubusercontent.com/102517557/162939527-2683263c-5881-43d0-8414-52a75c854285.png)
![image](https://user-images.githubusercontent.com/102517557/162939595-107bfa12-a101-47fd-8f35-edee5d65a816.png)

**Comment by RobertoDascalu** [comment]
Testing done.All good !
