### ISSUE TITLE
[Angular] Events. Event Participants (events & actions): Basic, Detailed & Custom export Configuration [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8695]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference 1: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/52YyZ2w
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1Ox22g
- Reference 3: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP0WOOJ
- We will implement all three exports  

### QA Section

1. What should the QA look for (what was done)
- Check that the same texts are used as per the current Sormas implementation. 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done:
-custom export: select all/deselect all not working

**Comment by RobertoDascalu** [comment]
Testing done - all good !
