### ISSUE TITLE
[Angular] Cases, Contact tab: Basic, Detailed & Custom Export Configuration [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8696]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference 1: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/52YyZ2w
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1Ox22g
- Reference 3: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP0WOOJ
- Reference 4: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/7399F0EC-2476-4ED9-891A-FBA1E8ACBBA6
- We will implement all three exports  

### QA Section

1. What should the QA look for (what was done)
- Check that the same texts are used as per the current Sormas implementation. 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done :
-same request URL for all exports : (http://localhost:4201/sormas-rest/contacts/export)
-Modal texts not well centered(screenshots)
-not same checkboxes as on vaadin app
![image](https://user-images.githubusercontent.com/102517557/168804490-3edf3922-d28e-4eb5-9c8a-18351eff3734.png)
![image](https://user-images.githubusercontent.com/102517557/168804582-c387fe39-a4e9-4930-a891-7d307b7c1a07.png)

**Comment by RobertoDascalu** [comment]
Testing done - 
-Select all/Deselect all does not work properly for some "sensitive person data" checkboxes
-Texts not well centered (screenshots)
![168804582-c387fe39-a4e9-4930-a891-7d307b7c1a07](https://user-images.githubusercontent.com/102517557/169266460-5ffa92de-71ee-423e-bb30-0b6eb7a7bf66.png)
![168804490-3edf3922-d28e-4eb5-9c8a-18351eff3734](https://user-images.githubusercontent.com/102517557/169266612-ce84854e-6af6-4359-a0bc-bf763b7a4bd3.png)

**Comment by RobertoDascalu** [comment]
Testing done - all good
