### ISSUE TITLE
Analyse slow system behaviour when creating an event participant / trying a case merge [2]

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Project#8697]
### Bug Description
Since version 1.66 or 1.67, when you want to create an event-participant from the events directory, a request is launched and runs for very long minutes. 
Being the only user in the test environment (with a dump of the production database), the request was completed after 23 seconds. In the production environment (with many users in parallel), the connection to the server is interrupted, forcing us to restart the server. On another test environment with very few observations, no difficulties were observed. 
We will install glowroot to identify the request in question

### Steps to Reproduce
1. Use the provided dump (ask @MartinWahnschaffe)
2. Set PerformanceLoggingInterceptor to TRACE
3. Open the reported function: 
    - Scenario 1: Create an event participant
    - Scenario 2: try to apply the filters on the case merge view
5. Use PerformanceLogAnalysisGenerator to analyse the logfile
6. Deliverable: Point out hotspots where a lot of time is lost

### Expected Behavior
less resource-intensive request

### System Details

* Device:
* SORMAS version: 1.67
* Android version/Browser: chrome
* Server URL: 
* User Role: admin + national user OR  contact supervisor+surveillance supervisor

### Additional Information
@olivierleuci @bernardsilenou @MateStrysewske @MartinWahnschaffe

**Comment by MartinWahnschaffe** [comment]
We have access to pseudonymized data that allows to reproduce the very long creating times for an event participant.
Next step is to take this data and identify the probematic queries & logic.

**Comment by BarnaBartha** [comment]
Case merge screen fails with SQL error (Postgres in Docker with 8Gb of RAM):
[caseMerge.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/8539680/caseMerge.log)

**Comment by BarnaBartha** [comment]
For the creation of the event participant the biggest bottleneck is the fetching of similar persons, as can be seen in the generated report:
[eventParticipantCreate.html.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/8540735/eventParticipantCreate.html.zip)
The changes in #8688 do not have any measurable impact on this.

**Comment by StefanKock** [comment]
Next steps:
- Ticket for Rewriting `getSimilarPersonDtos`, use `PersonIndexDto` with higher prio to work on. -> @StefanKock 
- Investigate Location query (finding 4), maybe follow-up to lazy load referenced entities -> @BarnaBartha 
- Ticket to limit `getXXXForDuplicateMerging` to 100 entries. Workaround: narrow down filtering in the UI. -> @StefanKock
