### ISSUE TITLE
[Angular] Contacts, Contact Follow-up visits tab: Basic Export [2 + 1] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8700]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/52YyZ2w

### QA Section

1. What should the QA look for (what was done)
- Check that the pop-ups are shown and contain the same texts as per the current Sormas implementation

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done -  everything looks good
