### ISSUE TITLE
Forwarding prompt considers deleted lab messages

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8709]
### Bug Description

When a user starts processing a lab messages that has the same `reportId` as a forwarded message, a prompt appears and gives them the option to cancel or continue anyways. However, this prompt also appears when the forwarded lab message is deleted.
### Steps to Reproduce

1. Upload two messages with the same `reportId` to the demis system and fetch them
2. Set one of the messages to FORWARDED
3. Delete the forwarded message
4. Go back to the second message and start processing

### Expected Behavior

The check for forwarded messages should only consider messages that are not deleted.

### Screenshots

![forwardedLabMessagesDeleted](https://user-images.githubusercontent.com/70317594/161774630-83d976b6-d60e-4464-a3b2-b623087f7c61.PNG)
![forwardedLabMessagesDeleted2](https://user-images.githubusercontent.com/70317594/161774637-4be79922-5c41-4f23-89fa-e40d1813f6fb.PNG)
![forwardedLabMessagesDeleted3](https://user-images.githubusercontent.com/70317594/161774638-220ec9cc-2fbb-4cdd-868d-b31424ad65d8.PNG)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Please explain why this is a bug. It was implemented like that on purpose. Actually, that is one of the few reasons for the current soft deletion of lab messages. Can you provide a specification that defines otherwise?

By the way, this will change once lab messages get permanently deleted (e.g. touched by https://github.com/hzi-braunschweig/SORMAS-Project/issues/7932).

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I created this as a bug because the action itself is incomprehensible to users due to them not having access to deleted entities. In https://github.com/hzi-braunschweig/SORMAS-Project/issues/5729 it says that lab messages no longer get completely deleted (not sure if that refers to the soft-delete or an actual hard-delete) but archived instead. However, we don't have the option to archive them yet. For archived messages, I think this behaviour would be totally fine and expected. For deleted entities, I think they should generally not be considered independent of them being soft or hard-deleted.

Archiving lab messages might be useful in general and consistent with other entities but that would be a different change or feature request I think

**Comment by FredrikSchaeferVitagroup** [comment]
[This PR](https://github.com/hzi-braunschweig/SORMAS-Project/pull/8782) will remove the soft deletion of lab message, and instead provide a direct permanent deletion. 
The problem described in this issue should be resolved by that.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Will it depend on the featureconfiguration `DELETE_PERMANENT` whether messages are hard or soft deleted?

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 That feature also gets removed by the same PR, so: no.
