### ISSUE TITLE
Dashboard page is crashing with a pop-up error for https://ga1.sormas-oegd.de/ 

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8712]
### Bug Description
A pop-up error appears when accessing Dashboard page with any role(ex: Admin, NatUser) at this test env: https://ga1.sormas-oegd.de/ 

### System Details

* Device:
* SORMAS version: 1.71.0-SNAPSHOT (9766659
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

[DashboardError.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8425405/DashboardError.txt)

**Comment by MateStrysewske** [comment]
@abrudanancuta Please request and attach server logs - we can't really do anything without those.

**Comment by abrudanancuta** [comment]
I added the file with the log

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.71.0-snapshot on ga1 environment
