### ISSUE TITLE
Do not display archived cases in the 'Select Source Case' pop-up [1]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8716]
### Problem Description

Archived cases are currently visible and selectable as source cases for new or existing contacts. This leads to changes being saved on an archived entity -> a new contact is saved to an archived case.

### Proposed Change

Do not display archived cases in the results list when a user searches for a 'Source Case' for a contact.

### Additional Information

A possible workaround would be for the user to first de-archive the case and then add it as source case to a contact.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (945656c).
