### ISSUE TITLE
Samples associated only with archived entities should be 'read only' [2]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8722]
### Problem Description

Currently, the behavior in what concerns samples associated only with archived entities is not consistent.

1. Samples associated with an archived case:
 -> are moved to the 'Archived samples' list, in the 'Samples' directory;
 -> are editable;
 
2. Samples associated with an archived contact: 
-> remain in the 'Active samples' list, in the 'Samples' directory;
-> are editable;
-> the user is able to create a resulting case for the archived contact, by adding a positive pathogen test to the sample;

3. Samples associated with archived event participants:
-> remain in the 'Active samples' list, in the 'Samples' directory;
-> are editable;
-> the user is able to create a resulting case for the archived event participant, by adding a positive pathogen test to the sample;

Note:
When the user makes changes on the sample page of a sample that is associated only with archived entities and then triggers the 'Confirm navigation' pop-up, after clicking 'Save changes', a warning message appears. If the user reloads the page, the changes made are saved.

The same warning message appears when the user attempts to save the resulting case for an archived contact or event participant, an unclear warning message appears:
![image](https://user-images.githubusercontent.com/96909231/161957226-c5ab6fda-f9fd-463c-9498-eec46e199037.png)
-> as the archived contact should not be editable, it is unclear why the user would be directed to reload the page and see the latest changes (if the user reloads the page, the changes made are saved).

### Proposed Change

Samples associated only with archived entities should be read only and displayed in the 'Archived samples' list in the 'Samples' directory.

### Additional Information

When a samples is associated with both active and archived entities (an archived case + an active contact), it should remain editable and in the 'Active Samples' list, in the 'Samples' directory.

**Comment by adinaflorea9** [comment]
In order to test and observe the behavior for archived entities: set feature EDIT_ARCHIVED_ENTITIES to 'false' in ''featureconfiguration.''

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because of the following problem:
When EDIT_ARCHIVED_ENTITIES = true, the Samples associated with archived entities are not editable.

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (e2d4dac).
