### ISSUE TITLE
Set 'All Event Participants' as the default value of the 'active/archived/all event participants' filter, when an event is archived [0.5]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8723]
### Problem Description

When an event is archived (and by default its event participants are archived as well), the 'Event Participants' list remains filtered to 'Active event participants' and the user is not able to see the associated event participants of the archived event.

Event Participants list before archiving the event:
![image](https://user-images.githubusercontent.com/96909231/161963623-f02f9bd8-1d60-4fd9-a27c-d684dbdfa6e2.png)

Event Participants list after archiving the event:
![image](https://user-images.githubusercontent.com/96909231/161963584-98937103-1354-4d4a-a566-badb9f7ecde4.png)

### Proposed Change

When the event is archived, set the value 'All Event Participants' as the default value for the filter 'active/archived/all event participants', on the 'Event Participants' page.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.75.0-snapshot (6d2b6ce) on local env.
