### ISSUE TITLE
Related entity uuid in sample heading is not displayed in parentheses 

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8725]
### Bug Description

The uuid of related entities in the sample headings are not displayed in parentheses
### Steps to Reproduce

1. Open a sample
2. Check the heading

### Expected Behavior

The uuid's should be displayed in parentheses as seen in other entities

### Screenshots

![sampleHeading](https://user-images.githubusercontent.com/70317594/161964199-0ba07043-5c7b-4e90-afbe-7e4d671de003.PNG)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(8c3edae).
