### ISSUE TITLE
Tasks associated with archived entities should be 'read only' [2]

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8727]
### Problem Description

The behavior in what concerns tasks associated with archived entities is not consistent.

1. Tasks associated with an archived case:
-> are moved to the 'Archived tasks' list, in the 'Tasks' directory;
-> are editable;

2. Tasks associated with an archived contact:
->remain in the 'Active tasks' list, in the 'Tasks' directory;
-> are editable;

3. Tasks associated with an active contact that has an archived source case:
-> are moved to the 'Archived tasks' list, in the 'Tasks' directory;
-> are editable;
=> the logic seems to be set for the task to be dependent on the source case, instead of the contact entity.

4. Tasks associated with an archived event:
-> are moved to the 'Archived tasks' list, in the 'Tasks' directory;
-> are editable;

5. Tasks associated with an archived travel entry:
->are moved to the 'Archived tasks' list, in the 'Tasks' directory;
-> are editable;

### Proposed Change

- [ ] Tasks that are either archived themselves or based on the associated entity should be read-only when the EDIT_ARCHIVED_ENTITIES feature is disabled.
- [ ] Tasks of archived contacts should be listed in the "Archived tasks" list instead of the "Active tasks" (instead of checking the archived status of the case related to the contact).

### Acceptance Criteria

* Tasks associated with archived entities should be 'read only' and displayed in the 'Archived tasks' list, in the 'Tasks' directory.

### Additional Information

`Task.archived` came with #3430, also in discussion in #4060

**Comment by MartinWahnschaffe** [comment]
I have updated the proposed change.

**Comment by razvancornita** [comment]
talked with @sergiupacurariu, this ticket most likely clashes with #8463, where it says that tasks should be editable. @SahaLinaPrueger, can you confirm that this ticket is needed, as a special case, or is it redundant?

**Comment by SahaLinaPrueger** [comment]
Tasks should be still editable after sharing a case/contact with ownership (especially if a health department uses CISS). This is a conflict. 
Can you implement different behavior for cases/contacts "to view" and "archived"?

**Comment by SahaLinaPrueger** [comment]
Procedure is: Tasks remain editable if the entity is available for viewing due to S2S. Tasks are not editable if the entity is available for viewing due to archiving.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine and https://test-de1.sormas.netzlink.com/ + https://test-de2.sormas.netzlink.com/ (for the S2S part of the ticket), using the latest version of SORMAS - 1.79.0-SNAPSHOT(0c06465).
