### ISSUE TITLE
Created Sample can not be saved

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#8731]
### Steps to Reproduce

1. Open an already created case
2. Click New Sample and fill the mandatory fields
3. Click Save

### Expected Behavior

The sample should be saved.

### Screenshots
![image](https://user-images.githubusercontent.com/47103965/161981253-49d3de6c-5eed-4d4a-b025-17ed55b3bba3.png)

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser: Chrome Browser
* Server URL: localhost
* User Role: NatUser, admin

**Comment by carina29** [comment]
[serverLogFromDevelopment.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8443392/serverLogFromDevelopment.txt)

**Comment by vidi42** [comment]
Was caused by a deployment issue. Not reproducible
