### ISSUE TITLE
New visit button is centered for officer roles in converted contacts follow-up tab

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8734]
### Bug Description

When a contact has been converted into a case, the follow-up tab displays the "new visit" button in the center of the page instead of right aligned next to the info icon. Other users like national user and supervisor see this button normally displayed. However, they also see the export button to the left of it which is not visible for officer roles.
### Steps to Reproduce

1. Log in as an officer (e.g. contact or community officer)
2. Open or create a contact
3. Convert the contact into a case
4. Open the contacts follow-up tab
5. Check the buttons displayed above the list

### Expected Behavior

The "new visit" button should be properly right aligned with the info icon.

### Screenshots

![newVisitConvertedContact](https://user-images.githubusercontent.com/70317594/161998430-d9916103-23d7-40b4-a944-683711037596.PNG)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by ChristopherRiedel** [comment]
I'm not able to reproduce this. For me everything seems to look as it should be.
Tested with Contact Officer on local system (1.70.3).

**Comment by ChristopherRiedel** [comment]
Also not reproducible on test-de1.

**Comment by kwa20** [comment]
This is still reproducible on 1.71.0 (1.71.0 test1401) and 1.72-SNAPSHOT (test-de1)

Tested with Community Officer. Note that it is the contacts follow-up tab
![newVisitButton](https://user-images.githubusercontent.com/70317594/168294826-eccace3f-63e8-4954-b37e-9469467e9cf5.PNG)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(1b59607).

Users that have the right to create follow-up visits covered while testing:
Community Officer, Contact Officer, + a configured user based on the configurable user roles and rights (used the default surveillance officer role + added all rights related to visits).
