### ISSUE TITLE
Paper form heading is missing on internationally configured servers

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8735]
### Bug Description

The implementation of https://github.com/hzi-braunschweig/SORMAS-Project/issues/7844 hides the paper form fields from german, swiss and french server. These fields should still be visible on the international configuration. However, the heading for these fields is also hidden there.
### Steps to Reproduce

1. Create a case
2. Check the paper form fields in the case tab as well as the heading

### Expected Behavior

The heading should be displayed on international servers.
### Screenshots

![paperFormHeadingMissing](https://user-images.githubusercontent.com/70317594/162005767-3b80fd50-044e-4b56-a9a5-cae3fcf4d907.PNG)

### System Details

* Device:
* SORMAS version: 1.70.1
* Android version/Browser: chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.71.0-snapshot on local setup
