### ISSUE TITLE
Contact UUID is not displayed in the 'Samples' directory list of samples

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8750]
### Bug Description

The UUID of associated contacts of samples is not displayed in the list of samples, on the main page of the 'Samples' directory.

### Steps to Reproduce

1. Navigate to the 'Samples' directory;
2. Observe the list of samples.

### Actual Behavior

The UUID is displayed in parentheses for associated cases and event participants, but it is not displayed for associated contacts.

### Expected Behavior

The UUID is displayed for associated contacts as well.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/162192432-c135125d-f38f-41c5-9756-9a7cc3e9dbf7.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(8c3dae)
* Android version/Browser: Chrome
* Server URL: local machine and test.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT from the development branch (3880db9).
