### ISSUE TITLE
Cannot edit contact, blank page appears

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8751]
### Bug Description
When a natUser wants to edit a contact, the details of it are not displayed

### Steps to Reproduce
1. As NatUser choose a contact and edit it

### Expected Behavior
Contact details should be loaded

### System Details

* Device:
* SORMAS version: https://wiki.vitagroup.ag/display/SORMAS/Quality+Assurance
* Android version/Browser:
* Server URL: local env
<img width="1440" alt="Screenshot 2022-04-07 at 14 40 37" src="https://user-images.githubusercontent.com/91872179/162200835-0c669c4c-0bc8-407d-b267-5b747c920e76.png">

* User Role:

### Additional Information

[ErrorLog.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8442873/ErrorLog.txt)

**Comment by dinua** [comment]
can not reproduce it

**Comment by roxanamlendea** [comment]
The bug is not reproducible anymore on the testing instances and on local environment.
