### ISSUE TITLE
Create zero report function for DSNO

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#876]
In order to evalute the use of SORMAS in Nigeria, it is **urgent and imprtant** to have the  zero reports functionality for DSNO's.

**Comment by foyiri** [comment]
please when can we have this i think it critical for the performance indicator we are looking at for the 8 state we have deployed so far

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda We should also discuss this at 15:00 even for Ghana it is important

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Duplicate of #610
