### ISSUE TITLE
[Tasks] Tasks associated with contacts are displayed for users that do not have 'CONTACT_VIEW' or 'CONTACT_EDIT' rights

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8768]
### Bug Description

In the 'Tasks' directory, tasks associated with contacts are displayed for users that do not have 'CONTACT_VIEW' or 'CONTACT_EDIT' rights, if the tasks are associated with contacts from within the users' responsible jurisdiction.

### Steps to Reproduce

1. Log in with an 'Admin+NatUser' user; 
2. Create a 'Case Officer' user and a 'Community Informant' user;
3. Create a contact and set its 'Responsible jurisdiction' within the jurisdiction of the users created at step 2;
4. Create a task for the contact from step 3;
5. Log in with the 'Case Officer' user and then with the 'Community Informant' user, and observe the list of tasks in the 'Tasks' directory.

### Actual Behavior

Tasks associated with contacts are displayed in the 'Tasks' directory for users that do not have the 'CONTACT_VIEW' or 'CONTACT_EDIT' rights.

### Expected Behavior

Tasks associated with contacts should not be displayed in the 'Tasks' directory for users that do not have the 'CONTACT_VIEW' or 'CONTACT_EDIT' rights, unless those users have already been assigned to the tasks.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/162416368-54ab3796-9e07-491a-8777-dbdfdf93f5b0.png)

### System Details

* Device: Windows 10 
* SORMAS version: 1.71.0-SNAPSHOT(edacd95)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser; Community Informant; Case Officer

### Additional Information

Note regarding the expected behavior: the assignation of tasks associated with contacts to users that do not have 'CONTACT_VIEW' OR 'CONTACT_EDIT' rights will be addressed in a change request.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT (9c0e90c) from the development branch.
