### ISSUE TITLE
Extend detailed case export (yellow fever) [2]

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#878]
The IM have requested that all this variable show when you carry out a detail export for yellow fever cases

**Comment by foyiri** [comment]
[yellow fever export.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2580721/yellow.fever.export.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Looks like you need to have a look at this.

**Comment by hzi-braunschweig** [comment]
@foyiri @MartinWahnschaffeSymeda @MateStrysewskeSym 
The variables below are for detailed export added for yellow fever. Can we add these new columns to the detailed export. 
EPID No.
State
LGA
Ward
Settlement
Surname
First Name
Date of Birth
AgeInYears
Age Group
Sex
Date of Onset
Yr
Month
Week
Case Detected where
Case Seen at Health Facility (Y/N)
Name of Treatment Facility
Date seen at Health Facility
Fever
Jaundice
Other Symptoms
Received YF Vaccine Y/N
Vaccine Card Seen Y/N
Last date of YF vaccination
Year of last YF Vaccination (verbal   report only)
Sample Taken Y/N
Date Lab Specimen Collected
Date Blood Sent to Lab
Name of Lab in Nigeria

**Comment by foyiri** [comment]
Yes please

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please remember to compare the new fields to the existing ones and clearly define which fields we should use for the import and if there is a need to add new fields to the system.

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/50827915-24ef2d80-1340-11e9-9bff-fb8e9c7bfd26.png)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] age group: export 5-year intervals
- [ ] case detected where -> "place of initital detection": health facility or first previous hospitalization
- [ ] Inpatient: Change "patient was admitted at health facility" to "... for at least one night"
- [ ] vaccination: year column is not needed. Use general vaccination info
