### ISSUE TITLE
[Contacts] Restricted users saving a sample with a positive pathogen test result leads to an error message

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8786]
### Bug Description

Adding a sample with a positive pathogen test result for a different disease to a Covid-19 contact generates an error message and a case that is not associated with the sample.

### Steps to Reproduce

1. Log in with a 'Clinician'/ or 'National Clinician'/ or 'Event Officer' user and open a contact (disease - Covid-19);
2. Add a sample with a positive pathogen test result (disease - Cholera) to the contact from step1;
=> 'Create case for this contact person' pop-up is triggered
![image](https://user-images.githubusercontent.com/96909231/162735203-088ecfd4-f13d-46e9-9ac2-315bac1b4463.png)

3. Click 'Yes' in the pop-up;
=> 'Create new case' form is triggered
4. Fill in the mandatory fields with valid information and click 'Save';
=> A warning message is displayed:
![image](https://user-images.githubusercontent.com/96909231/162735029-b39f5104-59f9-4790-9417-2f10a236691a.png)

5. Refresh the page.

### Actual Behavior

- On the 'Contact' page - the sample is saved;
- In the 'Cases' directory - the new case is saved; the case has the person information of the contact from step 1; the sample created at step2 is not associated with the new case;

### Expected Behavior

Pop-up to create a case should not be triggered when the users mentioned at step 1 save a sample with a positive pathogen test result to a contact.

### System Details

* Device: Winnows 10
* SORMAS version: 1.70.2 and 1.71.0
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Clinician, National Clinician, Event Officer

### Additional Information

The expected behavior is based on the behavior reproducible after ticket #8738,  where the pop-up to create resulting cases for contacts via a sample with a positive pathogen test result is no longer triggered, when the sample is saved by a 'Clinician', or 'National clinician', or 'Event Officer'.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup using latest version of sormas 1.71.0-snapshot
