### ISSUE TITLE
We need a separate mechanism for failed logins, as this is handled before any backend or rest activity [2]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8790]
### Description
Failed logins and login activity in general cannot be handled easily as part of backend or REST logging, therefore, we need to provide a separate logger for it. 

### How to implement 

- [ ] Add method to `AuditLogger`
- [ ] Define log format
- [ ] Identify where to put the logger, likely the multi auth mechanism

Split into:
- [ ] #8815
- [ ] #8816

**Comment by vidi42** [comment]
Discarded as it was split in 2 other tickets
