### ISSUE TITLE
Only NationalUser and Surveillance Supervisor can create samples

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8797]
### Bug Description
Only these roles can create samples for a case: NationalUser and Surveillance Supervisor. The roles that should be allowed to created samples for a case should be: NATIONAL_CLINICIAN, ADMIN_SUPERVISOR, SURVEILLANCE_OFFICER, CASE_SUPERVISOR, CASE_OFFICER, EVENT_OFFICER, HOSPITAL_INFORMANT, COMMUNITY_INFORMANT, LAB_USER, COMMUNITY_OFFICER, plus the 2 roles NationalUser and Surveillance Supervisor that are already working

### Steps to Reproduce
1. As one of the roles stated above which should have right to create sample Login
2. Create a case
3. Add to the case created a sample and save it
4. Edit a case
5. Look for the button to add a sample

### Actual Behavior
At step 3 after saving the sample an error message appears and the case has no longer the button to create samples
At step 5 no button to create a sample is in the form

### Expected Behavior
The roles stated above should be allowed to create samples

### System Details

* Device:
* SORMAS version: 1.71.0-SNAPSHOT (52ca13d)
* Android version/Browser:
* Server URL: local env, test.sormas.netzlink.com
* User Role:

**Comment by carina29** [comment]
Related to this bug, another bug was fixed:
External Lab Officer could not view the Samples due to some missing user Rights
![ExternalLabOfficerBug](https://user-images.githubusercontent.com/47103965/164175942-9ca743c5-d461-424b-8934-d2a74cdf3778.PNG)

**Comment by carina29** [comment]
The Sample creation problem can not be reproduced anymore. Probably the fixes for similar bugs, solved this issue too.
Related to the Samples which could not be opened by an External Lab Officer, another bug was opened and problem was solved.

A **new bug** was found during investigating this bug: A NatClin user can not edit the samples created by him/her.

**Comment by abrudanancuta** [comment]
The new bug about National Clinician mentioned by @carina29 is https://github.com/hzi-braunschweig/SORMAS-Project/issues/8918
