### ISSUE TITLE
Merge Duplicate Cases/Contacts - automatic zoom does not show the fields 'pick' and 'hide'

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#8805]
### Bug Description

If you want to merge cases, the table in the "merge duplicate cases directory" does not show "pick" or "hide" with 100%-zoom-factor. You have to set zoom factor to 90% and afterwards to 100%.

### Steps to Reproduce

1. Go on release-de or release-sormas-x (on 1402 not reproducible, maybe because there are a lot of possible duplicates?)
2. Try to merge two cases and watch if view shows field 'pick' and field 'hide'

### Expected Behavior

All fields should be clickable.

### Screenshots

![Merge Duplicate Cases](https://user-images.githubusercontent.com/100844689/162975753-945cb989-76dd-4828-b637-f5dc58076eb4.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.70.2
* Android version/Browser: edge, chrome, firefox
* Server URL: release-de or release-sormas-x
* User Role: admin

### Additional Information

Even if the topic is different, maybe the solution can be similar to https://github.com/hzi-braunschweig/SORMAS-Project/issues/8589

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by MateStrysewske** [comment]
I suspect the same problem could occur in the contact directory, so we should already fix it there as well; and I agree that we should use the same fix as in #8589.

**Comment by SahaLinaPrueger** [comment]
I don't know why, but in the contact directory i didn't have the problem. But you are absolutely right, better croos-check

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT from the development branch (a81974e).
The issue described in the comment is fixed, but I tested further and I opened ticket #8831.
