### ISSUE TITLE
User Rights | Case Superviser & Contact Supervisor & EventOff & LabOff & SurvOff & CommOff cannot open cases although they can open the cases directory

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#8814]
### Steps to Reproduce

1. Log in as any of the users from the title of the issue and navigate to the Cases Directory
2. Click on the UUID of one of the Cases

### Expected Behavior
The case should be opened

### Actual Behavior
The case page is displayed blank

### Screenshots
![image](https://user-images.githubusercontent.com/70562142/163191441-83e63efd-18c4-4368-9e0c-ff644a20a82e.png)

### System Details

* Device:
* SORMAS version: 1.71.0-snapshot
* Android version/Browser: Chrome
* Server URL: localhost + test-de
* User Role:  Case Superviser; Contact Supervisor; EventOff; LabOff; SurvOff & CommOff

### Additional Information
This ticket should be fixed before #8797

**Comment by AndyBakcsy-she** [comment]
Tested this with 1.70.2 version from the master branch and it is not reproducible. This issue was introduced in 1.71.0

**Comment by roxanamlendea** [comment]
The issue in reproducible also for the following users: Hospital Informant, District Observer.

**Comment by carina29** [comment]
@roxanamlendea The fix should work for the users you've mentioned (Hospital Informant, District Observer, National Observer, Contact Officer) and the users described in the bug title too.

**Comment by roxanamlendea** [comment]
Tested this ticket with all users that have CASE_VIEW rights on the latest version of Sormas 1.71.0-SNAPSHOT (fb72863) from the development branch.
From the users mentioned in my comment, it is still reproducible with **District Observer** and **National Observer**.
And I also found out that is also reproducible with **Region Observer**.

**Comment by roxanamlendea** [comment]
Verified ticket with all users that have CASE_VIEW rights using the latest version of Sormas 1.71.0-SNAPSHOT (98dcdef) from the development branch.
