### ISSUE TITLE
Community Officer cannot create Immunization directly from Case/Contact/EventParticipant

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8821]
### Bug Description
Community officer cannot create Immunization if opening in edit mode a Case/Contact(created from a processed lab message)/EventParticipant. He can Create immunization from Persons and from Immunization page

### Preconditions
Have the immunization module enable. Reduced immunization is set to false
Have a Contact created from a Lab message that was processed

### Steps to Reproduce
1. Login as Community Officer
2. Open in edit mode a Case/Contact/Event Participant
3. Try to create an Immunization from the edit view opened in the steps above

### Expected Behavior
Community Officer should be able to create Immunizations from Case/Contact/Event Participant

### Actual Behavior
Coomunity Officer has no button to create Immunization from Case or Contact or EventParticipant

### System Details

* Device:
* SORMAS version: 1.71.0-SNAPSHOT (fa93e16)
* Android version/Browser:
* Server URL: local env
* User Role:

**Comment by AndyBakcsy-she** [comment]
validated ticket on the latest version of Sormas 1.71.0-snapshot on local setup
