### ISSUE TITLE
Missing button for creating vaccination for "person involved"  in an event [mobile app].

### ISSUE THREAD

**Issue by BasilKaburi** [hzi-braunschweig/SORMAS-Project#8825]
### Bug Description
It is not possible to create a vaccination for a person involved in an event (event participant) because the button for creating a vaccination is missing.

### Steps to Reproduce

1. Create a new event.
2. Add a person involved to the this event.
3. Open the person involved to create a vaccination
### Expected Behavior
A button should be available for creating a vaccination for an event participant.

### Screenshots
![Missing_Person_Vaccination](https://user-images.githubusercontent.com/71414361/163229415-0f94f1c0-f4ec-4df5-b5a0-ac91895dc30e.jpg)

### System Details

*Device: Android
SORMAS version: 1.70.2
Android version/Browser: Version 11 (knox 3.7, API level 33)
Server URL: https://release-international.sormas.netzlink.com/
User Role: Surveillance officer & Contact officer### Additional Information

**Comment by MateStrysewske** [comment]
@BasilKaburi Does the event have a disease?

**Comment by BasilKaburi** [comment]
@MateStrysewske Good question! I just saw the disease was omitted. It works fine with the disease as expected. I will close the issue therefore. Thanks.
