### ISSUE TITLE
In various directories the text is not clipped when it exceeds a certain width and the entire table gets hard to read

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8831]
### Bug Description
In the 'Merge Contacts Directory' the text is not clipped and when certain inputs (eg. Source Case, First Name, Last Name, District) are too long. the columns get too wide and the entire table is hard to read and the user is not able to see the Merge, Pick and Hide buttons, unless he uses the scrollbar.

### Steps to Reproduce

1. Create 2 duplicate Contacts that have long text as input.
2. Open the Merge Contacts Directory and inspect the table.

### Expected Behavior
Long text should be clipped when the input exceeds a certain width (like in the Merge Cases Directory).

### Screenshots
![merge contacts directory](https://user-images.githubusercontent.com/89522688/163376509-f0f0c651-e289-48f3-8d87-2f22a4e98bf5.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT (a81974e)
* Android version/Browser: Chrome
* Server URL: local setup
* User Role: Admin, NatUser

### Additional Information
The issue is not reproducible on the Merge Cases Directory.
Here, the text is clipped when the input exceeds a certain width.

![image](https://user-images.githubusercontent.com/89522688/163376649-f3790764-8759-4297-9061-88e94c0c8d8d.png)

**Comment by roxanamlendea** [comment]
The issue is reproducible also on: Tasks Directory, Persons Directory, Cases Directory, Case Contacts tab, Contacts Directory, Events Directory, Event Participants tab, Samples Directory, Immunizations Directory, Travel Entries Directory.

@MateStrysewske Do we want them all fixed in this ticket?

**Comment by MateStrysewske** [comment]
@roxanamlendea Would make sense, yes
