### ISSUE TITLE
Permanent deletion of source cases can leave contacts without a jurisdiction

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8832]
### Bug Description

We've recently introduced #7942 which can be set up to happen automatically. However, when automatically deleting source cases of contacts that don't have their own jurisdiction (because they're adapting the jurisdiction of the source case), permanently deleting this source case leaves the contacts without a jurisdiction, essentially hiding it from most users and also leading to a functionally invalid state.

### Steps to Reproduce

1. Create a case
2. Create at least one contact for that case; leave the jurisdiction empty
3. Let the case be permanently deleted

### Expected Behavior

When permanently deleting a case, check the contacts of the case; for any contact with an empty jurisdiction (i.e. no region and district), set the jurisdiction to the responsible jurisdiction of the case.

### System Details

* Device:
* SORMAS version: 1.70.2 or 1.71.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
The issue can also be reproduced via soft deletion in the UI.

1. Create a Case.
2. Create a Contact and choose the Case from step 1 as Source Case.
3. Delete the Case from step 1.
4. Choose 'No' in the following pop-up:
![image](https://user-images.githubusercontent.com/89522688/163386562-03cf14cc-097c-46ff-984b-663f6d90566c.png)
5. Open the Contact created in step 2.

=> The 'Responsible Region' and 'Responsible District' fields are empty, even though they are mandatory.
However, the disease has been adopted from the Case.

![image](https://user-images.githubusercontent.com/89522688/163386649-d3c78f09-5c1d-45bb-8c52-1d4df868f968.png)
![image](https://user-images.githubusercontent.com/89522688/163386699-cab60319-dc45-48b9-a9d0-4305e8bfa4bb.png)

Also, when the user refreshes the page, an the system crashes:

![image](https://user-images.githubusercontent.com/89522688/163401391-a25675d2-97aa-46a9-a8a3-9794155019e2.png)

**Comment by mario-kuehne** [comment]
**Reproduction**
Reproduction with branch 'master' locally (8db7b707b3b076c6eafee877802d5ded3292d91a) via soft deletion in the ui: 

- reproducible: 'responsible region' & 'responsible district' are empty in the remaining contact (after deletion of the corresponding case)
- not reproducible: no server error shown when refreshing the contact details page

**Bugfix Test**
Sucessfully tested on https://test-de1.sormas.netzlink.com/ with Version: 1.71.0-SNAPSHOT (20b3763) via soft deletion in the ui: 


1. Create a Case (responsible region: `Baden-Württemberg`; responsible district: `LK Alb-Donau-Kreis`; responsible community: `Allmendingen`).
2. Create a Contact and choose the Case from step 1 as Source Case. And leave fields empty for responsible region & district & community for this contact
3. Delete the Case from step 1.
4. Choose 'No' in the "Delete contacts" pop-up:
5. Open the Contact created in step 2 -> Contact now shows responsible region: `Baden-Württemberg`; responsible district: `LK Alb-Donau-Kreis`; responsible community: `Allmendingen`
