### ISSUE TITLE
Vaccine name is showing 'â' characters instead of '-'

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8837]
### Bug Description
Some Vaccine Names are malformed and showing 'â' characters instead of '-'

### Steps to Reproduce

1. Open or create a Vaccination;
2. Inspect the Vaccine Name dropdown;

### Actual Behavior
Vaccine name is showing 'â' characters instead of '-'

### Expected Behavior
Vaccine names are correctly displayed;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/163561865-9736226e-775f-49d5-b468-344ceedf8d51.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT 
* Android version/Browser: Chrome
* Server URL: local server, test-de1.sormas.netzlink.com
* User Role: Admin, NatUser

**Comment by carina29** [comment]
The above mentioned problems should be fixed in all of the exports too.
![image](https://user-images.githubusercontent.com/47103965/165303567-a80c46e1-a092-409a-88ff-d050082235ce.png)
