### ISSUE TITLE
Values not translated in German across directories

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8838]
### Bug Description

Values related to location fields, age, birthdate, language, point of entry are not translated consistently across the DE version of the UI.

### Steps to Reproduce

The following translations are missing:

- [x] 'birthdate'/ 'age and birthdate':

a.in 'Cases': 
- 'line listing' form;
- 'merge duplicate cases' page;

b.in 'Contacts':
- 'line listing' form;
- 'merge duplicate contacts' page;
- search for 'source case' form;

- [x] 'completeness' - in 'Contacts' - main page of the directory - last column;
- [ ] 'continent' and 'subcontinent' - in 'Contacts' - 'Epidemiological data' tab - 'Exposures' - new entry form;
- [x] 'region' / 'district' / 'community':
a.in 'Events' - main page - among the columns;
b.in 'Samples' - main page - among the columns;
c.in 'Immunizations' - main page - among the columns;
d.in 'Reports' - main page;
e.in 'Users' - main page - among the columns; and 'Create new user' form;
f.in 'Tasks' - main page - among the columns and the filters; 
g. in 'Configurations' - 'Districts' tab (main page; and 'Create new district' form); 'Communities' tab (main page; filters; 'Create new community' form); 'Point of entry' tab (main page; filters; 'Create new point of entry' form);

- [x] 'point of entry' - in EN - the value is not spelled correctly; 
- [x] 'point of entry' - not translated in 'Entries' - 'Create new travel entry' form; on a travel entry's page;                                              

### Expected Behavior

The same values should be consistently translated across the UI.

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(f974e6f)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

**Comment by ChristopherRiedel** [comment]
This one is already translated correctly:
>  'continent' and 'subcontinent' - in 'Contacts' - 'Epidemiological data' tab - 'Exposures' - new entry form;

**Comment by AliciaRaber** [comment]
Tested on test1401.sormas-oegd.de V1.72.1.

Line listing:
![image](https://user-images.githubusercontent.com/91321821/171835140-338ace48-be3f-4d88-b86b-78b55f8a03fa.png)


Merge duplicate page:
![image](https://user-images.githubusercontent.com/91321821/171835072-462b5ba9-9c34-4609-91ae-76b4722c881c.png)


Completeness:
![image](https://user-images.githubusercontent.com/91321821/171835451-e8781216-f957-401e-8096-764b72bfffa4.png)
