### ISSUE TITLE
A warning message is displayed when a Surveillance Officer/ or Contact Officer converts a contact into a case

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8840]
### Bug Description

A warning message is displayed when a Surveillance Officer user converts a contact into a case.

### Steps to Reproduce

1. Log in with a Surveillance Officer user;
2. Open an existing contact that has not yet been converted into case;
3. Set the 'Contact Classification' to 'Confirmed' and save the page;
4. Click the 'Create a case for this contact person' button;
=> 'Create new case form' is triggered;
5. Fill in the mandatory information and click 'Save'

### Actual Behavior

A warning message is displayed: 
![image](https://user-images.githubusercontent.com/96909231/163575518-f19bb88f-61d9-48d1-8a11-1217d28587a3.png)
 
If the user refreshes the page, it is visible that the case was created and linked to the contact. The Surveillance Officer can not open the case (this specific behavior is addressed by ticket #8814).

Afterwards, when the user hovers anywhere in the app, a warning label appears:
![image](https://user-images.githubusercontent.com/96909231/163577273-c87acf62-cae0-4b83-9f8a-218fe6f44a7b.png)

### Expected Behavior

A Surveillance Officer user is able to convert a contact into case successfully and no warning message should be displayed.

### Screenshots

GIF - of the steps to reproduce:
![Convert](https://user-images.githubusercontent.com/96909231/163576530-635f8955-4743-4f0e-b489-e816a1779985.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(f974e6f)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Surveillance Officer, Contact Officer

### Additional Information

The Surveillance Officer and the Contact Officer both have user rights for CONTACT_CREATE, CONTACT_VIEW, CONTACT_EDIT, CONTACT_CONVERT and CASE_CREATE.

**Comment by dinua** [comment]
To convert a contact to case a user needs OUTBREAK_VIEW rights , (AbstractCaseView #117 #118).
Should users Surveillance Officer and Contact Officer have OUTBREAK_VIEW right ?

**Comment by MateStrysewske** [comment]
@dinua I don't think that's necessary. Outbreaks are currently not even used on any system. Pretty sure this has something to do with the changed user role logic in the backend, please consult @leventegal-she if you need assistance.

**Comment by dinua** [comment]
this bug is no longer reproducible, it was fix whit an other task
