### ISSUE TITLE
[User rights] An External Lab Officer cannot open samples

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8841]
### Bug Description

An External Lab Officer cannot open and view samples.

### Steps to Reproduce

1. Log in with an External Lab Officer user;
2. Navigate to the 'Samples' directory and open an existing sample.

### Actual Behavior

The Sample page displayed is blank.

### Expected Behavior

The Sample page is displayed and it contains the sample's information, fields, cards.

### Screenshots

External Lab Officer's view of the 'Samples' directory:
![image](https://user-images.githubusercontent.com/96909231/163578617-4743ab5b-c313-4805-bb27-840f6ba6da8f.png)

External Lab Officer's view of a sample:
![image](https://user-images.githubusercontent.com/96909231/163578670-e1ffb9da-3dd7-49fa-861f-c6ca6cf927f9.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(f974e6f)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: External Lab Officer

### Additional Information

An External Lab Officer has rights for SAMPLE_VIEW and SAMPLE_EDIT.

**Comment by roxanamlendea** [comment]
I tested the ticket on my local machine and I'm reopening the ticket because the user can now open the Sample, but he cannot Edit it, even though it has SAMPLE_EDIT rights.

![image](https://user-images.githubusercontent.com/89522688/164254955-81df4911-85bf-424a-8908-9c6d2776a8b8.png)

**Comment by abrudanancuta** [comment]
there is already a ticket for this case: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8892, I would suggest to close this issue

**Comment by vidi42** [comment]
The sample editing is not blocked by the UserRight, but by the jurisdiction of the user. So I will close this ticket now

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT (d16a724) from the development branch.
Now all users with SAMPLE_VIEW rights can open Samples.
