### ISSUE TITLE
[Event Participants] Confirmation message displayed when saving a new event participant is incorrect

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8845]
### Bug Description

When adding a new event participant to an event, the confirmation message that appears refers to a case person, even though the event, or the event participant, or the newly created person are NOT associated with a case entity.

### Steps to Reproduce

1. Create or open an existing event;
2. Navigate to the 'Event Participants' tab and click 'Add Participant';
3. Fill in the mandatory fields with valid information;
4. Click 'Save' and observe the confirmation message.

### Actual Behavior

The confirmation message is the following:
![image](https://user-images.githubusercontent.com/96909231/163783333-808b5e00-faf6-4c8d-9897-0dde661fde96.png)

The event participant added (the new person created, and the event) are not associated with any case entity, therefore the message should not mention a 'case person'.

### Expected Behavior

The confirmation message refers to the event participant created and saved ('New Event Participant Saved' or 'New Event Participant created' similar to the confirmation messages from the other directories when new entities are created).

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(9512317)
* Android version/Browser: Chrome
* Server URL: local machine 1.71.0-SNAPSHOT(9512317); test1402.sormas.netzlink.com - 1.70.2
* User Role: Admin, NatUser

**Comment by carina29** [comment]
@adinaflorea9 How should I proceed with the translation of the message to different languages? 
Should I translate them or do we have a table or list with translations?
For CZ, CH, DE, es-CU, es-EC, ur-PK we have translation messages. 

Thank you :)

**Comment by adinaflorea9** [comment]
@carina29 I am not really sure; from what I know, translations are updated from something called Crowdin. Perhaps one of the developers can help explain how this works exactly
