### ISSUE TITLE
[User Rights] Certain users get a warning message when creating new Cases

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8848]
### Bug Description
There are certain users that get a warning message when creating new Cases.
However, even though there's a warning message, the Case has been created. When the user opens the Case, the page is empty, though, due to #8814.

The user gets the warning message, when the Cases are created via:
- Create new Case;
- Convert a Contact into a Case;
- Open a Case for a Travel Entry;
- Create Case for an Event Participant;

When creating a Case via Line Listing, the Case is created without receiving the warning message.

### Steps to Reproduce

1. Log in with any of the users noted below and go to the Cases Directory;
2. Create a new Case and Save;

### Expected Behavior
The Case should be created and the user should not receive any warning message.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/163813440-5bd527ba-febe-47b6-b6df-4f72c96bd31e.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT (9239f6c)
* Android version/Browser: Chrome
* Server URL: local env
* User Role: Surveillance Officer; Hospital Informant; Community Officer; Community Informant; Clinician; Case Officer; Contact Supervisor; Contact Officer; Event Officer; Lab Officer; POE Supervisor; POE National User;

**Comment by vidi42** [comment]
Probably similar to https://github.com/hzi-braunschweig/SORMAS-Project/issues/8820
