### ISSUE TITLE
[User rights] Contact Supervisor cannot create new Event Group

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8850]
### Steps to Reproduce

1. Log in with a Contact Supervisor user;
2. Navigate to the Events Directory and open an Event;
3. Click on the 'Link Event Group' button';
-> 'Create new Event Group' pop-up opens;
4. Fill in the 'Group name' field and Save;

### Expected Behavior
The users receives an error message and the Event Group is not created;

### Expected Behavior
The Event Group should be created and user shouldn't receive an error message;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/163818641-56edf416-dc8e-474e-a220-de5385091ee4.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT (9239f6c)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Contact Supervisor

**Comment by kwa20** [comment]
I can also reproduce this behaviour on test1401.sormas-oegd.de (1.70.2)

<img width="511" alt="eventGroupCreateError" src="https://user-images.githubusercontent.com/70317594/163949292-bf1c8150-2a59-42ba-917f-7747a291f711.PNG">

I also noticed that a Contact Supervisor does not seem to have the EVENTGROUP_EDIT right:

<img width="869" alt="eventGroupCreateError2" src="https://user-images.githubusercontent.com/70317594/163949379-fb09e2e8-1e80-43d6-94f0-18ffb2ba62e4.PNG">

I don't quite understand the reason for this and think it could potentially be the reason that causes this error. @bernardsilenou  Do you know if in the original specifications for event groups, this right should not be given to Contact Supervisors?

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.71.0-SNAPSHOT (0302732) from the development branch.
