### ISSUE TITLE
[Angular] Person Directory: Set missing Geo-coordinates [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8863]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/g0gl3xJ
- We will focus only on the modal and confirmation message.
- No integration with the backend.

### QA Section

1. What should the QA look for (what was done)
- Check that the modal opens and contains the same texts as per the current Sormas implementation.
- Check for the confirmation modal after clicking "Continue".

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done:
-"t" is missing from "existing"
![image](https://user-images.githubusercontent.com/102517557/165743919-726d91ed-c6a0-48ce-944d-1b0249ab6f81.png)

**Comment by RobertoDascalu** [comment]
Testing done - all good !
