### ISSUE TITLE
[Angular] Address map leaflet integration - EYE [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8866]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKgWZ50\
- Person page: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/8yP4dgO
- Add new address: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/PGEpOEd
- We will not implement the functionality that the leaflet closes once we leave the map window (we can exit the map by either hitting "Esc" or clicking on the "close" sign).
- This feature will be integrated across the board (persons, facilities, etc)

### QA Section

1. What should the QA look for (what was done)
- Check that the leaflet is opened when clicking on the crosshair 
- Check that the leaflet can only be opened once we have filled in both LAT and LONG
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done 
-leaflet can only be opened once we have filled in both LAT and LONG and meters
-not responsive menu after making the map fullscreen in imunziation person form.

**Comment by RobertoDascalu** [comment]
Testing done - all good
