### ISSUE TITLE
[User Rights] System fails when Lab Officer creates a Task for an Event

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8868]
### Bug Description
When a Lab Officer creates a Task for an Event, he gets an error message and the Task is not created.
According to the User Roles Export, the Lab Officer user has TASK_CREATE rights, but doesn't have EVENT_EDIT rights. 

### Steps to Reproduce

1. Log in with a Lab Officer user;
2. Open an existing Event;
3. Click on 'New Task', fill in the mandatory fields and Save.

### Actual Behavior
The system throws an error message and the task is not created.

### Expected Behavior
Users without the EVENT_EDIT user right should not be allowed to create tasks for events.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/163981617-73200944-d925-4fcd-8952-fc1008a812a9.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: Lab Officer

**Comment by dinua** [comment]
if the user do not have EVENT_EDIT rights , the panel in right should be disable
![image](https://user-images.githubusercontent.com/4202109/164439730-0e0e11d3-feb6-4351-8a3a-f8bf178943e7.png)

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.71.0-snapshot on local setup.
LabOfficer does not have EVENT_EDIT right. Tested with a different user. 
No error was displayed and the task was created successfully
