### ISSUE TITLE
[Angular]  Get geolocation for address - PIN [2 + 1] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8869]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/WKgWZ50
- @MateStrysewske , we need to know what geolocation service can we use (are we restricted  to a specific client, pricing, etc ?)
- We are considering using something like: https://positionstack.com/product

### QA Section

1. What should the QA look for (what was done)
- Check that once an address is included and the user clicks on the pin icon, the lat and long are set.
- The pin icon should be disabled if the address is not fully typed in (city and street are mandatory, at least)

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by laurentiustanvitagroup** [comment]
@MateStrysewske , can you please look into this and give us some advice ? Thanks!

**Comment by MateStrysewske** [comment]
@laurentiustanvitagroup The geolocation service must be free of charge, I guess that's the main point. Ideally you'd use the same service that we're already using in the Vaadin app, don't know which one that is though, could be leaflet-geosearch. @vidi42, @HolgerReiseVSys or @JonasCir can probably tell you more.

**Comment by HolgerReiseVSys** [comment]
Please bear in mind the privacy aspect. This is probably the main reason why the provider can be configured in the backend.

**Comment by RobertoDascalu** [comment]
Testing done - all good
