### ISSUE TITLE
[Angular] Cases: Search specific case [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8870]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnoMlYM
- @marius2301 please confirm what endpoint is the "Specific Case search" uses and if it is different from the general cases one

### QA Section

1. What should the QA look for (what was done)
- Check that the modal opens when clicking the "Search specific case" button, contains the same texts as per the original implementation and displays a modal error when no case is found.
- Check that if the case is found the user is redirected to the case page (pending confirmation from @marius2301 in which endpoint to use).
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
