### ISSUE TITLE
Message 'An error has occurred' is triggered when a field validation is triggered and the user tries to archive the entity

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8871]
### Bug Description

When a field validation is triggered on an entity page, and then the user tries to archive the entity, the application crashes and an error message is displayed:
![image](https://user-images.githubusercontent.com/96909231/164003959-a947a715-0f02-4463-ba0a-24e513ba759a.png)

### Steps to Reproduce

1. Navigate to an entity page (case, contact, event, event participant, travel entry or immunization);
2. Trigger a validation for a field (set the report date to a date in the future);
3. At the bottom of the page, click 'Archive'.

### Actual Behavior

The application crashes and an error message is displayed: 

### Expected Behavior

- no 'An error has occurred' message is displayed; 
- the 'Confirm navigation' pop-up is triggered (as there are unsaved changes on the page); 
- depending on the user's choice in that pop-up the changes are either saved or discarded; 
- a message is displayed informing the user that the 'Date of report' can not be set in the future;

### Screenshots

![error message](https://user-images.githubusercontent.com/96909231/164005903-ec7090fc-8dd3-4b1b-9de8-8e1261675a54.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(9c0e90c)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information

Logs from the local machine: 
[Logsarchive.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8513008/Logsarchive.txt)

**Comment by StefanKock** [comment]
This behaviour should be prevented, but it's no a supported flow to change data, don't save but archive the entity.

**Comment by adinaflorea9** [comment]
Discussed the expected behavior with @carina29 - it's not necessary for the 'Confirm navigation' pop-up to be triggered in this situation as the user does not navigate to another page of the app. 

Revised expected behavior: a message is displayed informing the user that the 'Date of report' can not be set in the future.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.71.0-SNAPSHOT (f48c389)
