### ISSUE TITLE
Special characters are displayed as question mark

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8880]
### Bug Description

Translated strings display special characters as question marks 
### Steps to Reproduce

1. Login with any user
2. Check translations and special characters

### Expected Behavior

Special characters should be properly displayed

### Screenshots

<img width="726" alt="specialCharacters" src="https://user-images.githubusercontent.com/70317594/164183008-7ba613a7-adb7-4c64-835e-f150d687358c.PNG">

### System Details

* Device:
* SORMAS version: 1.71-SNAPSHOT d2984d1078fd21ccd71510c23cdb2a1a36daae44
* Android version/Browser:
* Server URL: test-de.sormas.netzlink.com
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Is it possible that it is related to ticket #8837 ?

**Comment by MateStrysewske** [comment]
@roxanamlendea I don't think so, no; this right here is very likely connected to encoding, the vaccination name issue is only present in a few vaccine names (as you can see, there are others where the hyphons are displayed, so it's not a general issue).

**Comment by MateStrysewske** [comment]
@kwa20 This was caused by a major hiccup by Crowdin which for some reason messed up the encodings of quite a lot of files.

**Comment by mario-kuehne** [comment]
BugfixTests
Sucessfully tested on https://test-de1.sormas.netzlink.com/ with Version: 1.71.0-SNAPSHOT (353c344)

User Role: admin, national user

![Special-Characters-correctly-shown](https://user-images.githubusercontent.com/95228108/165231804-375f9c9c-322a-44ee-9ec2-2b475f9e657f.PNG)

**Comment by adinaflorea9** [comment]
I am reopening the ticket as the issue is still reproducible on French, Spanish, Italian, German(Swiss),..., any language that has letters that are specific to their alphabet (special characters) on the local machine, using the latest version of SORMAS from the development branch 1.71.0-SNAPSHOT(0edc1be).

![image](https://user-images.githubusercontent.com/96909231/165268847-6b0b3906-5680-4530-be5c-707bbf52559c.png)

**Comment by carina29** [comment]
The exported files should also be checked and fixed ( if the question mark character is present).
