### ISSUE TITLE
Platelets fills and updates prothrombinTime in additional tests

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8882]
### Bug Description

When filling or changing the `platelets` in additional tests, `prothrombinTime` also gets filled or overwritten.
### Steps to Reproduce

1. Open a sample and create an additional test
2. Enter platelets without entering prothombrinTime and save
3. Check the created entry
4. Open the entry and change the platelets value, save
5. Check the entry 

### Expected Behavior

platelets should not update or overwrite prothombrinTime
### Screenshots

![PlateletsProthrombin](https://user-images.githubusercontent.com/70317594/164184883-8224bc72-cfea-48ce-a0e6-0601da2fead1.gif)

### System Details

* Device:
* SORMAS version: 1.70.2
* Android version/Browser: chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user

**Comment by StefanKock** [comment]
Maybe to/fromDto methods are flawed
