### ISSUE TITLE
Tasks can be assigned to users via bulk edit mode that don't have access to related entities

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8888]
### Bug Description

When selecting tasks associated to entities in different jurisdictions, users can be assigned via bulk edit mode that don't actually have the right to see the related entity
### Steps to Reproduce

1. Log in as an admin, national user
2. Create e.g. two cases in different jurisdicitons
3. Create tasks for each case
4. Open tasks and enter the bulk edit mode
5. Select the two created tasks and edit them in bulk
6. In the assignee drop-down, select a user (e.g. Supervisor or Officer) that should only have access to one of the tasks and related entities
7. Log in as the assigned user and check the associated entities to the tasks

### Expected Behavior

Only show users in the list that are assignable to all selected tasks:

- When the user clicks on the "Change assignee" checkbox, check the lowest jurisdiction that all of them have in common and filter the list by users with this jurisdiction level or above and this exact jurisdiction (e.g. when the entities have different districts, but the same region, filter the list by all users with jurisdiction level region or nation that either have no region or the same region as the one of the entities).
- When the lowest identical jurisdiction is not HEALTH_FACILITY or POINT_OF_ENTRY, show an info below the checkbox and above the dropdown (only if the checkbox is selected): "You have selected tasks with different [facilities/points of entry/communities/districts/regions]. Only users on [community/district/region/national] level or above will be selectable as assignees."
- Use an identical style as for the hint that appears in the task edit form when a user without an associated email address and phone number is selected (i.e. black text, small info icon to the left).

### Screenshots

![taskAssigneeNoAccess](https://user-images.githubusercontent.com/70317594/164196970-053e8716-9fcd-4abd-83c6-97014bf60062.gif)

### System Details

* Device:
* SORMAS version: 1.70.2
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Note: I agree that this is a bug, but it won't be easy to fix because it probably requires new code and/or relatively extensive re-writing of existing code.

**Comment by MateStrysewske** [comment]
#8994 should also be considered here: Tasks can apparently not be assigned to users above district level in bulk assignment. Since we need to update the logic in this issue here anyway, we should fix that problem here as well.

**Comment by MateStrysewske** [comment]
@kwa20 @JaquM-HZI Description updated, please decide upon the priority of this issue. :)

**Comment by markusmann-vg** [comment]
As discussed with hzi, it should be considered and bug and should be done in the sprint for 1.73

**Comment by kwa20** [comment]
@MateStrysewske Something that came to mind is that if e.g. a case has a place of stay that differs from its jurisdiction, the place f stay region and district should also count as the lowest jurisdictional level.

For example:
Case 1:
- `responsibleRegion`: Berlin
- `responsibleDistrict`: SK Berlin Mitte
- `region`: null
- `district`: null

Case 2:
- `responsibleRegion`: Berlin
- `responsibleDistrict`: SK Berlin Lichtenberg
- `region`: Berlin
- `district`: SK Berlin Mitte

Result: lowest jurisdiction == SK Berlin Mitte

**Comment by adinaflorea9** [comment]
As discussed with @MateStrysewske, I am reopening the ticket due to the following behavior:

Steps:
1. Create two cases that have the same region but different districts;
2. Navigate to the 'Task' directory and search for the 2 tasks associated with the case from step 1;
3. Through bulk editing, click to change the assignee of the 2 tasks.

Actual behavior:
Lab Officer and External Lab Officer can be assigned to the tasks, even though their lowest jurisdiction is their assigned laboratory.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(edcc878).
