### ISSUE TITLE
[Audit] Provide local Keycloak logger config for login attempts

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#8891]
### Description
Followup to #8815 and #8816: Both tickets covered failed login attempts, however, we also want to cover valid logins for the local Keycloak. 

### Implementation details

Create a Keycloak configuration file which logs the Keycloak events.

**Comment by vidi42** [comment]
Probably the [SORMAS.json](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-base/setup/keycloak/SORMAS.json) file needs to be updated to include the events config.
As well as a script which can be used for running instances to update the events config. Something like this https://github.com/hzi-braunschweig/SORMAS-Project/issues/7820#issuecomment-1057038897

**Comment by JonasCir** [comment]
Thanskf or the pointers Alex.
I found a quite simple way where only a normal restart of Keycloak is required :)

**Comment by abrudanancuta** [comment]
validated on local env together with @JonasCir
