### ISSUE TITLE
[DEMIS2SORMAS] Create a dedicated menu for messages [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8895]
### Feature Description

Samples > Lab Messages / DEMIS interface
### Problem Description

Thus far, external messages in regards to case surveillance, especially in association with the DEMIS interface, have been managed in the lab messages directory. Recently, more message types have been introduced to DEMIS which requires users in SORMAS to not only receive and process lab messages but also other kinds of messages, e.g. physician reports.
In order to make the management of external messages more generic and clear, the lab messages directory should become its own menu item and serve as a general location to process any type of message that report cases to users.

### Proposed Change

- [x] Move the lab messages directory out of the sample menu and create a separate menu item called 'Messages'. Place this menu item in between Tasks and Persons. Use the notepad icon as seen elsewhere.
    - [x] Rename the directory title to 'Message Directory'
    - [x] Rename 'Fetch lab messages' to 'Fetch messages'
    - [x] Rename 'Lab name' to 'Reporter name' (included in search field placeholder)
    - [x] Rename 'Lab postal code' to 'Reporter postal code' (included in search field placeholder)
    - [x] Rename the pop-up header 'Lab message' to 'Message' (visible when viewing the message details)

- [x] Rename some further strings associated with general messages by replacing 'lab message(s)' with just 'message(s)' in the following contexts:
    - [x] labMessageLabMessagesList
    - [x] confirmationDeleteLabMessages
    - [x] confirmationUnclearLabMessage
    - [x] confirmationManuallyForwardedLabMessage
    - [x] confirmationFetchLabMessages
    - [x] confirmationSinceLabMessages
    - [x] headingLabMessageDownload
    - [x] headingNoLabMessagesSelected
    - [x] headingLabMessagesDeleteProcessed
    - [x] headingLabMessagesDeleted
    - [x] headingFetchLabMessages
    - [x] messageLabMessagesAssigned
    - [x] messageForwardedLabMessageFound
    - [x] messageNoLabMessagesSelected
    - [x] messageLabMessagesDeleteProcessed
    - [x] messageLabMessagesDeleted
    - [x] labMessageAlreadyProcessedError
    - [x] labMessagePdfConversionError

- [x] Rename the feature configurations `LAB_MESSAGES` to `EXTERNAL_MESSAGES` and adjust related descriptions
- [x] Change the `LAB_MESSAGES` user right to become generic MESSAGES rights
    - [x] Introduce the user right `EXTERNAL_MESSAGES_VIEW` - users with this right should be able to view the Messages directory, message details of the contained messages and download messages
    - [x] Introduce the user right `EXTERNAL_MESSAGE_PROCESS` - users with this right should be able to fetch messages, edit the assignee and status of a message as well as process them
    - [x] Introduce the user right `EXTERNAL_MESSAGE_DELETE` user right - users with this right should be able to delete messages
    - [x] Only users should be able to be set as assignees that also have the `EXTERNAL_MESSAGE_PROCESS`

### Additional Information

![Message menu](https://user-images.githubusercontent.com/70317594/164263618-6c425d93-1b98-4628-8477-56980dd4ee26.png)

![Message Directory](https://user-images.githubusercontent.com/70317594/164257948-82461d1a-70fc-42bc-85d1-51fc24622905.png)

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Should users with the `MESSAGES_VIEW` right not also be able to download messages? Semantically, donwloading lab messages better fits to viewing than to editing...

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 What user roles should have which of those rights as default? It looks like you are already having something in mind.

**Comment by kwa20** [comment]
> @kwa20 Should users with the `MESSAGES_VIEW` right not also be able to download messages? Semantically, donwloading lab messages better fits to viewing than to editing...

@FredrikSchaeferVitagroup Yes makes sense, I've updated the original description of the issue accordingly

**Comment by kwa20** [comment]
I've added some strings (contexts from crowdin) to also rename to make them more generic and fit different message types.

**Comment by kwa20** [comment]
As discussed with @ChristopherRiedel , miscellaneous labMessages mentions in the code will also be adjusted to be more generic. Excluded are only such that relate specifically to lab messages.

**Comment by kwa20** [comment]
This issue seems to break the build in Jenkins:

Error Message
invalid versioning trigger externalmessage  DELETE 
Stacktrace
java.lang.AssertionError: 

invalid versioning trigger externalmessage  DELETE 
	at de.symeda.sormas.backend.common.StartupShutdownServiceTest.testHistoryTablesMatch(StartupShutdownServiceTest.java:147)

**Comment by ChristopherRiedel** [comment]
> This issue seems to break the build in [Jenkins](https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-Build/1191/de.symeda.sormas$sormas-backend/testReport/de.symeda.sormas.backend.common/StartupShutdownServiceTest/testHistoryTablesMatch/):
> 
> Error Message invalid versioning trigger externalmessage DELETE Stacktrace java.lang.AssertionError:
> 
> invalid versioning trigger externalmessage DELETE at de.symeda.sormas.backend.common.StartupShutdownServiceTest.testHistoryTablesMatch(StartupShutdownServiceTest.java:147)

Already known. Will be fixed with https://github.com/hzi-braunschweig/SORMAS-Project/pull/9408

**Comment by kwa20** [comment]
@ChristopherRiedel Oh perfect, I'll close this issue again :)

**Comment by vidi42** [comment]
After the update the EXTERNAL_MESSAGES feature config is disabled by default.
A migration might be needed to make sure we don't disable it on systems which had LAB_MESSAGES enabled.

**Comment by ChristopherRiedel** [comment]
> After the update the EXTERNAL_MESSAGES feature config is disabled by default. A migration might be needed to make sure we don't disable it on systems which had LAB_MESSAGES enabled.

There is already a migration:
UPDATE featureconfiguration SET featuretype = 'EXTERNAL_MESSAGES' WHERE featuretype = 'LAB_MESSAGES';
https://github.com/hzi-braunschweig/SORMAS-Project/commit/2125a6fb00ebdee871ae9998a327ff3856bbc4d2#
It worked on my dev system.

**Comment by kwa20** [comment]
@ChristopherRiedel I noticed that the assignee filter has multiple null options. Tested on test-de2.sormas.netzlink.com, 1.73.0-SNAPSHOT (3f0d4cea40)

![messagesAssigneeFilterNullOptions](https://user-images.githubusercontent.com/70317594/173304778-26b63933-dfbc-4ba0-b5f7-7028cd609ccd.gif)

**Comment by ChristopherRiedel** [comment]
> @ChristopherRiedel I noticed that the assignee filter has multiple null options.

@kwa20 I took a look. The first empty option is simply the classic null option. The second is the unassigned option, which unfortunately lacks the caption. The third one is actually no option, as you can see in your GIF, you can't select it at all, there is simply the end of the list of options.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.74.0-SNAPSHOT (edcc878)
