### ISSUE TITLE
Surveillance Supervisor at selecting "Enter bulk edit mode" from Events will display more Events that are not from his region

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8899]
### Bug Description
Surveillance Supervisor at selecting "Enter bulk edit mode" from Events will display more Events that are not from his region.

### Steps to Reproduce

1. Have some events that are not assigned to any region
2. Have some events assigned to the region belonging to the Surveillance Supervisor
3. Login as Surveillance Supervisor and go to Events page
4. Look at the overview of the Events
5. Select "Enter bulk edit mode"

### Actual Behavior
=> at this point more Events are appearing, also the ones having no region

### Expected Behavior
The events appearing in bulk edit mode should be identical to those that appear when not in bulk edit mode.

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL:
* User Role: Surveillance Supervisor

**Comment by AliciaRaber** [comment]
Tested on test1402.sormas.netzlink.com V1.72.1
User role applied. Created some events in other regions/districts. In bulk edit mode only events for the applied district (Baden-Württemberg) was displayed.
![image](https://user-images.githubusercontent.com/91321821/171856622-21784d20-c6c4-4be9-97da-8d41b16d92d6.png)
