### ISSUE TITLE
Cases | ERROR: null value in column "healthfacility_id" violates not-null constraint

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#8903]
### Bug Description
The Health facility is not displayed as mandatory anymore once "Point of entry" is selected as the Case Origin.
This leads to a DB violation 

### Steps to Reproduce
1. Start creating a Case with NatUser
2. Under Case Origin select "Point of Entry"
3. Fill in all the data except the Place of Stay (Facility/Home)
4. Save and check the log file

### Expected Behavior
The user should be able to create the case

### Screenshots
![Healthfaciity-Id](https://user-images.githubusercontent.com/70562142/164256080-8fd74742-438d-4a2b-b1cb-66cd785f6c9e.gif)

### System Details

* Device: local setup
* SORMAS version:  1.71.0-SNAPSHOT (213d20c)
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: NatUser

### Additional Infor
Server Log:
[server error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8522402/server.error.txt)
mation

DB Backup:
Change the ending of the file from .txt to .sql 
[Backup_04_20.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8522416/Backup_04_20.txt)

**Comment by MateStrysewske** [comment]
There's no not null constraint applied to the healthfacility_id column anywhere in the code; looks like some misconfiguration specific to this local instance.
