### ISSUE TITLE
Not all buttons are shown in Merge Duplicates

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#8908]
### Bug Description

When merging duplicates, not all buttons are displayed initially. The user must manually adjust the width of all columns to see and use the merge buttons in the last column.

This happens repeatedly, even if the contents of the other columns are very short.

![image](https://user-images.githubusercontent.com/74791118/164374053-c7028b4e-8016-46d0-af8e-8bc74f185295.png)

### Steps to Reproduce

1. open case directory
2. open merge duplicates
3. search

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis What's your proposed solution/expected behaviour? As far as I can see, there's no minimum width connected to these columns. A possibility could be to move the buttons to the left (directly next to the ID) to ensure they're always visible.

**Comment by JaquM-HZI** [comment]
@MateStrysewske @Marko-ilmkreis 
Maybe it is the same like in #8805 ?

**Comment by Marko-ilmkreis** [comment]
@JaquM-HZI Thanks. That migh be the same. So this issue can be closed. I will check again after the upgrade to 1.70.3 if the problem still exists.

**Comment by kwa20** [comment]
> @JaquM-HZI Thanks. That migh be the same. So this issue can be closed. I will check again after the upgrade to 1.70.3 if the problem still exists.

Just a heads up, you would probably still see the problem in 1.70 since https://github.com/hzi-braunschweig/SORMAS-Project/issues/8805 was closed in the milestone of 1.71.0
