### ISSUE TITLE
Broken Lab Messages Directory

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#8909]
### Bug Description

Opening the Lab Messages Directory throws and exception and does not load

### Steps to Reproduce

1. Navigate to Samples -> Lab Messages
-> Exception gets thrown and lab messages don't load

### Expected Behavior

Directory opens without exception and loads messages (if any).

### Screenshots

![image](https://user-images.githubusercontent.com/67001822/164386847-e1372ec6-cf21-4b2a-8369-7873efca2721.png)

### System Details

* Device: Windows
* SORMAS version: 1.71.0-SNAPSHOT (latest state of development)
* Android version/Browser: Chrome
* Server URL: local system (as I could again not find any working test system with lab messages active)
* User Role: National User

### Additional Information

[log-excerpt.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8527798/log-excerpt.txt)

**Comment by FredrikSchaeferVitagroup** [comment]
@abrudanancuta just reported that the exception does not occur when filtering by type (of lab message).

**Comment by FredrikSchaeferVitagroup** [comment]
Also when filtering for UUID or status, the exception does not get thrown.

**Comment by FredrikSchaeferVitagroup** [comment]
The problem probably was introduced by [this commit](https://github.com/hzi-braunschweig/SORMAS-Project/commit/f02d862c17502787ef3c47febaea45c6e461dd1d). With the removal of the default value for the deleted attribute, the [whereFilter in the LabMessageFacadeEjb](https://github.com/hzi-braunschweig/SORMAS-Project/blob/dbd76521f3679300fbe898df1d426161cae26318/sormas-backend/src/main/java/de/symeda/sormas/backend/labmessage/LabMessageFacadeEjb.java#L316) could be (and stay) null, which seems to lead to the exception.

**Comment by FredrikSchaeferVitagroup** [comment]
Should be testable on any instance with the lab messages feature activated. Best options probably are a local setup or test-de2.

**Comment by abrudanancuta** [comment]
The issue appears when filtering by Assigned is changed to the value Unassigned

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.71.0-SNAPSHOT (2372c23)
