### ISSUE TITLE
No longer use reception date as relevant date for dashboard statistics [0]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#891]
Once the date of report is editable (see #890) the reception date is no longer relevant for dashboard statistics.

**Comment by MartinWahnschaffeSymeda** [comment]
Had a look into this. Since there are currently many cases that were created when the date of report was not editabl those cases still rely on the reception date. Therefor we should wait at least und April 2019.
