### ISSUE TITLE
Show userroles in user captions again

### ISSUE THREAD

**Issue by ChristopherRiedel** [hzi-braunschweig/SORMAS-Project#8910]
### Problem Description

With #4461 userroles were removed from user captions due to performance problems.

### Proposed Change

Bring the userroles back to user captions (e.g. Adam Smith - Admin, National User) without harming performance badly.
Add a feature configuration for showing the userroles in the caption.

### Implementation Details

Therefore change `UserReferenceDto.buildCaption` and the first constructor of `UserReferenceDto`.

**Comment by MartinWahnschaffe** [comment]
Providing the user roles in the caption will always harm performance, so we should not do this in general for the UserReferenceDto.
Instead we have to identify where exactly users have to be displayed including their roles. One example of this could be when picking an assignee for a task, but I'm not even sure whether it's still needed there.

@bernardsilenou Can you clarify where we would have to show the user roles next to the user name?

**Comment by MartinWahnschaffe** [comment]
Ok, then I'll discard this one. I have added the other point you mentioned and another comment to #1091.
