### ISSUE TITLE
Filters should take into account responsible and place of stay jurisdictions

### ISSUE THREAD

**Issue by BarnaBartha** [hzi-braunschweig/SORMAS-Project#8911]
Verified ticket on the local machine using the latest version of SORMAS from the development branch – 1.71.0-SNAPSHOT(1dc6c47).

As discussed with @MateStrysewske I am reopening the ticket due to the following flows:

I: Contacts directory
1. Create a case whose ‘Responsible jurisdiction’ and ‘Place of stay’ differ (different values for region-district-community);
2. Create a contact with no responsible jurisdiction, but with a source case (the case created at step 1);
3. In the ‘Contacts’ directory, search for the contact from step 2 by using the region-district-community filters and the values of the responsible jurisdiction of the source case.
=> the contact is not listed among the results; the filters only take into account the region-district-community of the ‘place of stay’ of the source case.

Expected behavior: In the ‘Contacts’ directory, the filters for region-district-community should take into account both the responsible jurisdiction and the place of stay of the source case of a contact.

II: Samples directory
1. Create a case whose ‘Responsible jurisdiction’ and ‘Place of stay’ differ (different values for region-district-community);
2. Create a contact with no responsible jurisdiction, but with a source case (the case created at step 1);
3. Add a sample to the contact created at step 2;
4. Navigate to the ‘Samples directory’; 
5. Search for the sample by using the region-district filters and the values of the responsible jurisdiction of the source case.
=> the sample is not listed among the results; the filters for region-district only take into account the values of the ‘place of stay’ of the source case.

Expected behavior: in the ‘Samples’ directory, the filters for region-district should take into account both the responsible jurisdiction and the place of stay of a source case, associated with a contact that has a sample.

III: Samples directory
1. Create a contact that has its own responsible jurisdiction;
2. Add a sample with a positive pathogen test result to the contact created at step 1;
3. Select ‘Yes’ in the pop-up that is triggered after saving the sample;
4. In the ‘Create new case’ form fill in the mandatory information and set different values for the ‘Responsible jurisdiction’ and ‘Place of stay’ of the resulting case;
5. Navigate to the ‘Samples’ directory;
6. Search for the sample from step 2 by using the region-district filters and the values of the responsible jurisdiction of the contact from step 1.
=> the sample is not listed among the results; the filters for region-district only take into account the responsible jurisdiction and place of stay of the resulting case.

Expected behavior: in the ‘Samples’ directory, the filters for region-district should take into account the responsible jurisdiction of the contact associated with the respective sample, the responsible jurisdiction and the place of stay of the resulting case.

_Originally posted by @adinaflorea9 in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8347#issuecomment-1081753418_

Issue started on branch https://github.com/hzi-braunschweig/SORMAS-Project/tree/bugfix-8347-CaseDependentJurisdictionFilters

**Comment by roxanamlendea** [comment]
Yesterday I tested the ticket using the version of Sormas 1.72.0-SNAPSHOT from the development branch (b33192b) and the Community filter from the Contacts Directory didn't show any results.
I addressed the issue to @BarnaBartha and he took care of it. I will continue testing after the commit with the fix.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.72.0-SNAPSHOT from the development branch (0fa6307).
