### ISSUE TITLE
Temporarily disable the deletion of event groups

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8915]
### Problem Description

Deleting event groups currently leads to the user session idling and the database transaction not executing (#8851). Unfortunately, this is not easily fixable. In order to not let users run into this problem, we need to temporarily disable the deletion of event groups until we have found a proper fix for the issue.

### Proposed Change

Hide the "Delete" button from the event group form.

**Comment by mario-kuehne** [comment]
Verified 'delete' button disablement (delete button is not shown in the UI) of Event Groups on https://test1401.sormas-oegd.de/ with Version 1.70.3

Role: Admin, National User
