### ISSUE TITLE
Backend user right checks should distinguish between EDIT and CREATE user rights [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8920]
### Problem Description
Most entity facades have a save method that currently checks whether the user has either the CREATE oder EDIT user right for that entity.
Effectively this means that in the backend a user that does not have the right to create and entity can still do so. Some goes for editing.

### Proposed Change
- [x] Within the save method of each backend facade to the following: After getting the existing entity do a hasUserRight check for either the CREATE (entity does not exist yet) or EDIT (entity exists) user right. 

### Implementation Details

* Use AccessDeniedException - see RightsAllowedInterceptor

**Comment by abrudanancuta** [comment]
Validated on local environment with the API endpoints, version: 1.75.0-SNAPSHOT (f246ac5)
The endpoint remained unchanged: if a role have no access to create/edit  an entity then he will get the status code 200 but Error as response message. The server log will have more details why the error appeared for that specific endpoint
