### ISSUE TITLE
Add user rights for external surveillance [2]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8926]
### Problem Description

The functionality to send and delete cases & events to/from external surveillance tools is currently available for anyone who can access the respective entity. This should be more restrictive.

### Proposed Change

- [x] Introduce an EXTERNAL_SURVEILLANCE_SHARE and EXTERNAL_SURVEILLANCE_DELETE user right
- [x] External sharing and deleting of a case should only be allowed via ExternalSurveillanceToolGatewayFacadeEjb when the user has the respective right and in addition to the the CASE_EDIT user right.
- [x] Same for event (EVENT_EDIT)
- [x] Add checks for this in the frontend of case
- [x] And in the frontend of event

**Comment by leventegal-she** [comment]
There are 2 methods called only by the survnet converter:
```
	void createEventShareInfo(List<String> eventUuids);
	void deleteCases(List<CaseDataDto> cases) throws ExternalSurveillanceToolException;
```

For what rights should these be allowed?
Which default roles should have the new rights?

@MartinWahnschaffe @HolgerReiseVSys

**Comment by SORMAS-SahaLinaPrueger** [comment]
None of the default user roles should be allowed to share and delete to external surveillance tools just as none of the default user roles gets the S2S rights. see: #10084

Procedure for the health departments is the same as for S2S: The health department creates a role called "SurvNet" or something similar, assigns this role the rights described in this issue and assigns the role to the users, who work with SurvNet. 

It is very important to communicate this procedure to the health departments before the rollout, so they are prepared. 

It is also important, that the box for the surveillance tool is still visible for all users who can see the case/event, although they do not have the right to send or delete (_send_ and _delete_ button not visible). So all users with the related VIEW_right can see, if this case/event was send to SurvNet, at what time and so on.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:
For a user with no 'Edit existing cases' right, but with EXTERNAL_SURVEILLANCE_SHARE and EXTERNAL_SURVEILLANCE_DELETE user right - on the case page, the tab for 'Reporting tool' is editable and the buttons are clickable. The actions can not be completed as an error message appears.

The card should be read only as it is on events when the logged in user does not have 'Edit existing events' right.

**Comment by leventegal-she** [comment]
Created change request https://github.com/hzi-braunschweig/SORMAS-Project/issues/11578 for the edit right issue because we need a better way of handling user right for this and similar cases and this aspect was not in the scope of this issue

**Comment by adinaflorea9** [comment]
Verified ticket on https://test-de2.sormas.netzlink.com/ using SORMAS version - 1.81.0-SNAPSHOT(883464d).
