### ISSUE TITLE
add sormas-stats Keycloak client to put SORMAS-Stats-next-gen behind the Sormas Keycloak authentication

### ISSUE THREAD

**Issue by jwijffels** [hzi-braunschweig/SORMAS-Project#8927]
Hello

In order to integrate [SORMAS-Stats-next-gen](https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen) behind the Keycloak authentication, I suggest we have an extra Keycloak client called `sormas-stats`
In that way we can put the Shiny app of SORMAS-Stats-next-gen behind the Sormas Keycloak setup.
I see that you have this [code](https://github.com/hzi-braunschweig/SORMAS-Project/blob/master/sormas-base/setup/keycloak/keycloak-setup.sh#L174:L181)
Can we have similar code in order to have a new Keycloak client: `sormas-stats`

**I've set this up at https://infra-sormas-stats.sormas.netzlink.com/sormas-stats-shinyapp/ which I presume you have admin access to**

In order to test putting the shiny app behind Keycloak, 

- I've manually created [here](https://infra-sormas-stats.sormas.netzlink.com/keycloak) this [client](https://infra-sormas-stats.sormas.netzlink.com/keycloak/auth/admin/master/console/#/realms/SORMAS/clients/53613ca6-aecd-403d-b152-9e4e6f86ebab) which is dumped in json below, 
- and changed the Apache configuration to put sormas-stats-shinyapp behind Keycloak by using https://github.com/hzi-braunschweig/SORMAS-Docker/tree/development using [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc)

```
OIDCProviderMetadataURL https://infra-sormas-stats.sormas.netzlink.com/keycloak/auth/realms/SORMAS/.well-known/openid-configuration
OIDCRedirectURI https://infra-sormas-stats.sormas.netzlink.com/sormas-stats-shinyapp/secure
OIDCClientSecret this-is-secret
OIDCCryptoPassphrase and-another-secret
OIDCClientID sormas-stats
<Location /sormas-stats-shinyapp>
      AuthType openid-connect
      Require valid-user
      LogLevel debug
</Location>
```

```
{
      "id": "53613ca6-aecd-403d-b152-9e4e6f86ebab",
      "clientId": "sormas-stats",
      "rootUrl": "",
      "surrogateAuthRequired": false,
      "enabled": true,
      "alwaysDisplayInConsole": false,
      "clientAuthenticatorType": "client-secret",
      "redirectUris": [
        "https://infra-sormas-stats.sormas.netzlink.com/sormas-stats-shinyapp/*"
      ],
      "webOrigins": [],
      "notBefore": 0,
      "bearerOnly": false,
      "consentRequired": false,
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": false,
      "publicClient": true,
      "frontchannelLogout": false,
      "protocol": "openid-connect",
      "attributes": {
        "saml.assertion.signature": "false",
        "id.token.as.detached.signature": "false",
        "saml.multivalued.roles": "false",
        "saml.force.post.binding": "false",
        "saml.encrypt": "false",
        "login_theme": "sormas",
        "oauth2.device.authorization.grant.enabled": "false",
        "backchannel.logout.revoke.offline.tokens": "false",
        "saml.server.signature": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "use.refresh.tokens": "true",
        "exclude.session.state.from.auth.response": "false",
        "oidc.ciba.grant.enabled": "false",
        "saml.artifact.binding": "false",
        "backchannel.logout.session.required": "true",
        "client_credentials.use_refresh_token": "false",
        "saml_force_name_id_format": "false",
        "saml.client.signature": "false",
        "tls.client.certificate.bound.access.tokens": "false",
        "require.pushed.authorization.requests": "false",
        "saml.authnstatement": "false",
        "display.on.consent.screen": "false",
        "saml.onetimeuse.condition": "false"
      },
      "authenticationFlowBindingOverrides": {},
      "fullScopeAllowed": true,
      "nodeReRegistrationTimeout": -1,
      "defaultClientScopes": [
        "web-origins",
        "roles",
        "profile",
        "email"
      ],
      "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
      ]
    }
```

Adding @fhauptmann @bernardsilenou

**Comment by fhauptmann** [comment]
Every occurence of "infra-sormas-stats.sormas.netzlink.com" needs to be replaced by current server url

**Comment by JonasCir** [comment]
@jwijffels @bernardsilenou  Hey there, are there any issues you encountered while using this setup? If not, I would simply include the client which you shared with us above and make sure that it is available in our local Keycloak setup. The client id/secret can the be consumed by any compatible solution, either in apache or the the app directly.

**Comment by JonasCir** [comment]
Also @jwijffels @bernardsilenou Please notice that this ticket here is only for SORMAS related changes, the small Apache2 adjustments have to go in SORMAS Docker, so maybe @jwijffels you can draft a PR?

**Comment by jwijffels** [comment]
> @jwijffels Can you point me to the repository and/or a docker setup of sormas stats which I can execute?

The docker setup is at https://github.com/hzi-braunschweig/SORMAS-Docker
The Apache configuration is at https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/apache2/vhost.conf.sh

**Comment by jwijffels** [comment]
sormas-stats is at https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen

**Comment by bernardsilenou** [comment]
Just seeing your discussion
@JonasCir  You can also pull the image from docker-hub
https://hub.docker.com/r/hzibraunschweig/sormas-stats

**Comment by JonasCir** [comment]
Thx

**Comment by bernardsilenou** [comment]
@vidi42 @JonasCir @fhauptmann 
How can we test this issue before the print ends pls? 
Deploy sormas-stats on the nightly build or use https://dev-sormas-stats.sormas.netzlink.com/ ?
