### ISSUE TITLE
Hospital Informant: S3Q5Z5 cannot synchronize with SORMAS server

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#894]
@MartinWahnschaffeSymeda Please can you check google analytics for user id S3Q5Z5. He cannot synchronize cases. I am with the hospital informant and I have trouble shot the system but it still wont synchronize. Error message when you drag down is "could not connect ot SORMAS server. Try again later" I have connected to wifi and same message. Please help out.

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Below are the two types of errors that have been reported. Both are related to the device not being able to connect to the server. sormas.org.ng/sormas-rest is working fine and all ssl certificates seem to be right.

From my understanding there seems to be a problem with the device itself. 

Have you tried to restart the whole device? 

Can you try to open https://sormas.org.ng/sormas-rest/info/version in the browser on the device?

> ServerCommunicationException - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException: Unable to resolve host "sormas.org.ng": No address associated with hostname
> User: S3Q5Z5-MESG4H-6SGLNX-PRNJCCP4 - System: https://sormas.org.ng/sormas-rest/
> 
> ServerCommunicationException - Root cause: de.symeda.sormas.app.rest.ServerCommunicationException: SSL handshake aborted: ssl=0x9606e640: I/O error during system call, Software caused connection abort

**Comment by MartinWahnschaffeSymeda** [comment]
User didn't have anymore data on his mobile contract.
