### ISSUE TITLE
de-archiving contacts contains string for cases

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#8943]
### Bug Description

When de-archiving contacts, the message mentions a case instead of the contact.
### Steps to Reproduce

1. Open a de-archived contact
2. De-archive the contact and check the message

### Expected Behavior

The message should mention contact instead of case
### Screenshots

<img width="475" alt="deArchiveContacts" src="https://user-images.githubusercontent.com/70317594/165106254-6b8c1216-8784-4e7b-afca-1599418832dc.PNG">

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by carina29** [comment]
We have duplicate tickets for this bug. The other ticket is this one: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9001
@adinaflorea9 can we close 9001 and fix the bug in this ticket ( 8943) since this was earlier opened?
Thank you :)
