### ISSUE TITLE
S2S_Processed lab messages should be transferred [3]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#8950]
### Feature Description

Currently it is possible to process a lab message. Afterwards the lab message is added to a case. If you share a case with S2S with hand over the ownership and with the sample -> the lab message is not transferred.
Furthermore the lab message can not be opened on source system after the share because the case can only be read (no right anymore to edit or open files) 
### Problem Description

This is a problem, because the target system needs the lab message to start with the investigation of the case. 
If a health department wants to use S2S right know they have to send the lab message by fax afterwards. 
This should be avoided with S2S and means double the work. 
### Proposed Change

**Processed** lab messages will be shared if the parameter 'sample' is set on true.
### Additional Information

source system after share (fields are greyed out because you only have the permission to read) :
![image](https://user-images.githubusercontent.com/100844689/165267366-9f4d4df6-6e53-4dcf-a8d9-43576d461abd.png)

target system after share (no lab message):
![image](https://user-images.githubusercontent.com/100844689/165267484-fc1269fe-595c-40d8-9c51-13d1d2426d43.png)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI @kwa20

**Comment by markusmann-vg** [comment]
So, with labmessages disabled to be shared (configuration), a case with labmessages, that is shared is expected to be shared together with the labmessages

Status of the lab message after the share
Source System: forwarded / Labmessage should still be readable from the sample
Target System: processed

**Comment by SahaLinaPrueger** [comment]
@markusmann-vg as discussed, we have tested whether an already processed lab message is sent along with the activation of the feature configuration SORMAS_TO_SORMAS_SHARE_EXTERNAL_MESSAGES. Unfortunately, this does not happen and we have to implement this issue. The feature configuration SORMAS_TO_SORMAS_SHARE_EXTERNAL_MESSAGES only deals with unprocessed lab messages. The issue must therefore be implemented independently of this feature configuration. 

An important addition to the issue: In the source system, the lab message should not only be readable after the transfer, but also downloadable. Many thanks in advance!

**Comment by JonasCir** [comment]
QA: I couldn't test this during the code review as my DEMIS setup is broken, can you be extra careful about this?

**Comment by SahaLinaPrueger** [comment]
I cannot test this on the nightlies hence the question: Did you implement this for lab messages and physicians reports? 
In April it was not yet possible to process physicians reports, that's why I didn't mention it.

**Comment by leventegal-she** [comment]
For physicians reports is not done because it was not requested until now.

BTW currently it is not possible to see the physicians report linked to a case on the UI

**Comment by SahaLinaPrueger** [comment]
I cannot test this on the nightlies hence the question: Can you open the lab message in the source system after the case was shared with the hand over the ownership?

**Comment by leventegal-she** [comment]
> @leventegal-she I cannot test this on the nightlies hence the question:
> 
> 1. Can you open the lab message in the source system after the case was shared with hand over the ownership?
The labmessage is kept in the source system with status FORWARDED and can be seen in the messages directory
> 2. Can the lab message be found in the message directory in the target system if you share with hand over the ownership?
Yes
> 3. Is it only implemented for shares with hand over the ownership or also for shares with no hand over the ownership?
Only for shares with ownership handed over
