### ISSUE TITLE
When viewing the custom case export, the "Sequelae" option is listed twice. 

### ISSUE THREAD

**Issue by OleWienke** [hzi-braunschweig/SORMAS-Project#8955]
### Bug Description
When viewing the custom case export, the "Sequelae" option is listed twice. 

### Steps to Reproduce
1. Open the Custom Case Export
2. Create a new Export Configuration
3. Scroll to "Additional Data"

### Expected Behavior
Sequelae should be listed only once. 

### Screenshots
![Sequelae](https://user-images.githubusercontent.com/94985767/165285459-344307b3-8f65-4069-a7ae-1cfb7cfffbeb.PNG)

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser: Firefox
* Server URL: https://test1402.sormas.netzlink.com/
* User Role: admin

**Comment by kwa20** [comment]
The second sequelae selection option should be `sequelaeDetails`. The export itself seems to produce the correct content in the file. However, I noticed an additional odd behaviour which makes it impossible to export the fields seperately by deselecting one or the other.

![sequelaeExport](https://user-images.githubusercontent.com/70317594/165288880-57cf0cf1-986f-4b82-bd44-4db46997b951.gif)

**Comment by AliciaRaber** [comment]
Tested on test1401.sormas-oegd.de V1.72.1
Entry is changed to "Sequeale Description"

![image](https://user-images.githubusercontent.com/91321821/171625879-420ff790-7bdc-4f94-ad63-68cb3155c058.png)

Issue can be changed.
