### ISSUE TITLE
CONTACT_CLASSIFY and CONTACT_ASSIGN user rights are not used anywhere

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8959]
### Bug Description
Contact classification can be changed by Lab user, Surveillance Supervisor, Surveillance Officer and Admin Supervisor

### Steps to Reproduce
1. As one of the user described above login
2. Choose a contact and try to change the classification 
3. Save the change 

### Expected Behavior
Remove both user rights as they are not required anymore.

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL: local env
* User Role:

### Additional Information

See #9002 for CONTACT_ASSIGN

**Comment by MateStrysewske** [comment]
@bernardsilenou @Chinedar We're currently not using both these user rights anywhere in the code; do you know whether they SHOULD be used or whether we can get rid of them?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
I vote for getting rid of them.

**Comment by Chinedar** [comment]
Yes, we can get rid of them.

**Comment by JaquM-HZI** [comment]
@abrudanancuta I think they are removed with the new user roles. Can you please check and close if I'm right? Thanks

**Comment by abrudanancuta** [comment]
The user rights Contact_Classify and Contact_Assign are no more present in the new structure of the User Rights and Roles
Checked on the local environment with the version: 1.77.0-SNAPSHOT (8c31891)
