### ISSUE TITLE
During Case merging address is deleted

### ISSUE THREAD

**Issue by AliciaRaber** [hzi-braunschweig/SORMAS-Project#8961]
### Bug Description
According to the new merging tests (SORMAS only) we tested also to merge adress fields in SORMAS (adress fields). Test scenario was that Case 1 and Case 2 contains the same address data. After the merge of the cases the address section is empty.

![image](https://user-images.githubusercontent.com/91321821/165465027-2dbd56c0-053e-4e37-bc68-b1d4792942f1.png)
![image](https://user-images.githubusercontent.com/91321821/165465116-640f9e80-aeb6-44b8-9b18-71a5ea96d811.png)

If I enter two different adresses the data also get deleted

![image](https://user-images.githubusercontent.com/91321821/165466294-ef08e02c-bb0b-4d5d-8df2-49d0df4f1617.png)
![image](https://user-images.githubusercontent.com/91321821/165466330-670df16a-41bd-4acf-841b-b966102fa978.png)

### Steps to Reproduce

1. Open case directory
2. Click on More --> Merge duplicate cases
3. Define date setting for filter
4. Apply filter
5. Search for cases in description (Donald Duck, Fairy Godmother), alternatively double entered cases
6. Click on each case --> Case will automatically open in new tab
7. Go to Case Person
8. Enter Data in Case Person in Adress section
9. Data can be the same for both cases or different. It is also possible to enter two different adresses for Case 1 and one adress for Case 2
10. Choose one case to be merged --> Click on merge
11. After merging refresh the cases --> Adresses in merged case is deleted in adress section

### Expected Behavior
Entered address data should be merged (when adress data is equal in both cases) or consolidated​ when different. Alternatively it is also possible to list both adresses even when data is equal.

### Screenshots
Gif created
![Merge_Adress_Deletion](https://user-images.githubusercontent.com/91321821/165471933-f81949a8-1596-44fe-ba4c-4c13d4e1419c.gif)

### System Details

* Device: Laptop Windows 10
* SORMAS version: 1.70.3
* Android version/Browser: Edge 
* Server URL: survnet-import-test.sormas.netzlink.com
* User Role: Admin

**Comment by MateStrysewske** [comment]
@AliciaRaber Looks to me like you didn't save the persons after creating the addresses. Can you please try the same workflow again, but saving the persons before attempting to merge them?

**Comment by AliciaRaber** [comment]
@MateStrysewske Right. Adress is displayed two times. I close this issue. No further steps needed.
