### ISSUE TITLE
[Angular] Users: Sync users [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8966]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/41A5EEB1-2DA8-489C-839E-F8D777662B36
- When clicking "Sync" a request will be made to the backend and based on the response we will enable the "Download error export" button (provided we receive it from the backend). Please confirm with @marius2301.

### QA Section

1. What should the QA look for (what was done)
- When clicking the "Sync users" button a modal opens and contains the same text as per the current Sormas implementation
- In the modal the correct count of the users is displayed
- When clicking "Sync" a new modal opens with the progress bar (fake progress for now, pending later confirmation)
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
