### ISSUE TITLE
[Angular] Users: Bulk actions [3 +1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8971]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/09vbLEG
- Whoever will handle this task, please sync with @marius2301 and see how we will integrate it with the BE.

### QA Section

1. What should the QA look for (what was done)
- Check that the "Bulk actions" is present
- Check that we have the same actions available (Enable / Disable)

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
testing done - all good
