### ISSUE TITLE
[Angular] Configuration: Archive / De-archive [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#8976]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: 
- We will need to implement the current logic used 
-- When filtering for all: No bulk action (we just disable the "Bulk action" dropdown).
-- When filtering for archived: De-archive bulk action
-- When filtering for active: Archive bulk action
- Whoever will implement this task will need to confirm with @marius2301 the exact way in which it will be integrated with the BE (https://github.com/hzi-braunschweig/SORMAS-Project/issues/8975)

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done :
-"Points of entry" archive/de-archive modal translation issue
![image](https://user-images.githubusercontent.com/102517557/166919410-726000dc-e674-4a00-b263-c250fc447c89.png)
![image](https://user-images.githubusercontent.com/102517557/166919688-053f8aba-b06e-48b2-bc98-514c2862ab1d.png)

**Comment by RobertoDascalu** [comment]
Testing done - all good
