### ISSUE TITLE
NATIONAL_CLINICIAN,  CASE_SUPERVISOR and CASE_OFFICER cannot link treatment to prescription

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#8977]
### Bug Description
After having a prescription created for a Case, the create treatment button directly from the prescription is not present

### Steps to Reproduce
1. Login as one of the roles specified in the title
2. Edit/create a Case
3. Go to Therapy tab
4. Create a Prescription
5. Look for the Create Treatment from the Prescription

### Actual Behavior
The button to link a treatment to a prescription is not present

### Expected Behavior
A button to create a treatment from a prescription should be available

### Screenshots

<img width="1440" alt="Screenshot 2022-04-27 at 16 10 32" src="https://user-images.githubusercontent.com/91872179/165538305-c7a31f8b-0a5c-47b7-abdf-efe6d638c438.png">

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL:
* User Role: NATIONAL_CLINICIAN,  CASE_SUPERVISOR and CASE_OFFICER

**Comment by MateStrysewske** [comment]
Problem probably is this code fragment here:

```
if (isPseudonymized) {
			getColumn(DOCUMENT_TREATMENT_BTN_ID).setRenderer(new GridButtonRenderer());
			getColumn(DOCUMENT_TREATMENT_BTN_ID).setHeaderCaption("");
		} else {
			getColumn(DOCUMENT_TREATMENT_BTN_ID).setHidden(true);
		}
```

Pretty sure it should be `if (!isPseudonymized)`.

**Comment by carina29** [comment]
With the fix, the Create Treatment button will appear for NATIONAL_CLINICIAN,  CASE_SUPERVISOR and CASE_OFFICER.

For admin users ( which has only admin rights) the button will not appear.
@MateStrysewske agreed that is ok in this way since the Admin right is usually combined with other rights ( ex. NatUser).

**Comment by abrudanancuta** [comment]
Validated on local env with this version: 1.71.0-SNAPSHOT (4f6e61b)
