### ISSUE TITLE
Health conditions are not marked as required in CaseDataDto

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#8979]
### Bug Description

Health conditions are required for cases (since they're a child entity) since moving them from the clinical course tab, but they are not marked as required in the DTO.

### Expected Behavior

Add the `@Required` annotation to the `CaseDataDto.healthConditions` field.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by abrudanancuta** [comment]
validated on local env with the version: 1.71.0-SNAPSHOT (4f6e61b)
