### ISSUE TITLE
Permanent Deletion | Immunization | healthconditions_id violates not-null constraint error

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#8983]
### Bug Description
Automatic deletion of Contacts with Immunization + Vaccination  can cause the healthcontisions_id not-null constraint error

### Steps to Reproduce
Prerequisites :  Make sure the Automatic deletion of expired entities happens every 5 minutes.

1. Make sure to have in the DB a Person with 2 immunizations attached. (use the attached DB)
2. Enable the Permanent deletion for Immunization (use: Creation and 1 day)
3. Wait until the Chron Job is executed 
4. Check the server error log

### Expected Behavior
No Constraint error should be displayed in the log 

### System Details

* Device: local setup 
* SORMAS version: 1.71.0-snapshot
* Android version/Browser: chrome
* Server URL: localhost
* User Role: NatUser

### Server Log : 
[server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/8572967/server.log)

### DB after the error
[DB_Backup.zip](https://github.com/hzi-braunschweig/SORMAS-Project/files/8589569/DB_Backup.zip)

**Comment by sergiupacurariu** [comment]
The reason for the above behavior is the fact that multiple vaccinations are linked to the same healthcondition. Below you have a query to check if this situation exists in the checked database:

select count(*)
from healthconditions hc
where hc.id in (select distinct v.healthconditions_id
                from vaccination v
                         join (select vc.healthconditions_id
                               from vaccination vc
                               group by healthconditions_id
                               HAVING count(*) > 1) b
                              on v.healthconditions_id = b.healthconditions_id);

**Comment by AndyBakcsy-she** [comment]
Verified on local setup using the same DB that produced the initial error, using Sormas 1.71.0-snapshot version
There are no more errors like the one found by this issue. 
Closing ticket as verified and fixed.
