### ISSUE TITLE
Sync to android-app only for allowed data endpoints

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8989]
### Bug Description

On the mobile app, when logged in with a Surveillance Officer or a Community Officer, the synchronization with the APMIS server does not work. An error message is displayed stating that the user does not have permission 'You do not have needed permissions. Please contact the support'.

### Steps to Reproduce

1. Log in with a Community Informant or a Surveillance Officer
2. Trigger the synchronization with the APMIS server.

### Actual Behavior

An error message appears: 'You do not have needed permissions. Please contact the support'.

### Expected Behavior

No error message should appear; the synchronization should be successful.

### Screenshots

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/96909231/165717653-75123ec8-6fad-495b-b452-86f4a32ec4e8.png)

### System Details

* Device: Huawei P20 lite
* SORMAS version: 1.71.0
* Android version/Browser: 9
* Server URL: test.sormas.netzlink.com
* User Role: Community Officer, Surveillance Officer

### Additional Information

This has been reproducible on the mobile app downloaded from:
APK download: https://test.sormas.netzlink.com/downloads/release/
Server URL: https://test.sormas.netzlink.com/sormas-rest/
Username & Password: AD-CommOff / BpDH859yu9Bf and AD-SurvOff / YjziLyHtWCFr

Caused by #8508

**Comment by MartinWahnschaffe** [comment]
@MateStrysewske @syntakker I have a guess what is happening here:
The mobile app tries to synchronize all entities - regardless of whether the user has the related ..._VIEW user right. So when the user does not have access to contacts in general, but the app tries to synchronize them, the ReST interface will return this error.

I'd propose to do the following now:

- [ ] catch this exception for every entity type (can probably be put into a generic method) and ignore it for now. Instead go on with the next entity type

Maybe in a separate issue that can go into the next sprint:

1. Don't pull entity types the user cannot VIEW
2. Don't push entity types the user cannot EDIT

**Comment by StefanKock** [comment]
I redefined this ticket as needed `change` that was overlooked when defining the epic #898.

**Comment by MartinWahnschaffe** [comment]
Frank decided to directly do the user right checks instead of catching exceptions.

One special case is the view right for visits, which is now handled with CASE_VIEW. I have extend #5058 to introduce a dependency between CASE_VIEW and CONTACT_VIEW to address this.

**Comment by MartinWahnschaffe** [comment]
@ QA

The changes made here make sure the mobile app sync is working again. To fully test it, you have to make sure that pulling date form the server and pushing data to the server works for the data that is displayed and edited on the mobile device - so a case with all sub entities, etc.

I'd suggest to limit this to hospital informant, community informant and surveillance officer at max.

Known issue: #9076 - this can be ignored here.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS  from the development branch - 1.72.0-SNAPSHOT(da2e4fdd) - the mobile app part was tested using the Android Studio connected to my local machine server.

The entities are synced between the andorid-app and the vaadin-app, and vice-versa. Findings from testing were logged in #9175 and #9216.
