### ISSUE TITLE
A Surveillance Officer can not generate a new case with a different disease

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#8992]
### Bug Description

A Surveillance Officer can not generate a new case of a different disease if a sample has a pathogen test result of one disease (Covid-19), and it is associated with a case (Covid-19).

The behavior is also reproducible is the user adds a whole new sample with a positive pathogen test result of a different disease (Anthrax) than the disease of the case (Covid-19).

### Steps to Reproduce

1. Log in with a Surveillance Officer;
2. Create a new case (Covid-19) and add a sample with a positive pathogen test result to it (Covid-19);
3. Navigate to the 'Samples' directory and open the sample from step 2;
4. Add a new positive pathogen test result to the sample (use a different disease than Covid-19);
=> Pop-up to generate a new case for the different disease is triggered;
5. Click 'Yes' in the pop-up.

### Actual Behavior

An error message appears: 'A problem has occurred. You have no rights for changing Disease. Please reload the page to see the latest changes'.

The new pathogen test is added to the sample; the new case is not generated.

### Expected Behavior

The user should be able to generate a new case for the different disease of the second pathogen test.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/165736212-0d4fefc4-45be-4df6-9c6c-7421d98f4e00.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(af0201e)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Surveillance Officer

### Additional Information

A Surveillance officer user does not have rights for CASE_CHANGE_DISEASE; but in the steps described above, the user would not be changing the disease of an existing case, or the disease of a sample or pathogen test.

If the same steps are reproduced but for a sample that is associated with a contact or event participant, the Surveillance Officer can add the new pathogen test of a different disease and generate a new case for that disease successfully.

- This defect was apperently introduced by #445 with backend check of `UserRight.CASE_CHANGE_DISEASE`.
- Follow up for cleaner code: #9066

**Comment by roxanamlendea** [comment]
This is also reproducible with Case Officer:
![image](https://user-images.githubusercontent.com/89522688/165950352-df0e46b1-4dca-44b5-97d7-dfd01649e72a.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(d0b4148).
