### ISSUE TITLE
Inconsistent assignment options for tasks in bulk mode.

### ISSUE THREAD

**Issue by OleWienke** [hzi-braunschweig/SORMAS-Project#8994]
### Bug Description
Available users in the bulk edit mode for tasks are inconsitently displayed compared to task creation and edit forms. Users with jurisdictions above district level do not seem to be displayed when changing the task assignee via the bulk action.

### Steps to Reproduce
1. Create a task in an event.
2. Navigate to the Tasks tab
3. Enter Bulk Editing Mode in the task tab
4. Select the recently created task and and open the edit mode via Bulk Actions
5. Open the edit mode, select the edit assignee checkbox and open the dropdown menu "Task Assignee"
6. Users with responsibilities above the district level do not seem to be displayed.

### Expected Behavior
All users who are allowed to view and edit the events should be displayed. 

### Screenshots
![Animation](https://user-images.githubusercontent.com/94985767/165744285-04f74888-228b-4fa2-8e59-88b10a1be15a.gif)

### System Details

* Device:
* SORMAS version: Version: 1.70.3
* Android version/Browser: Firefox
* Server URL: https://test1402.sormas.netzlink.com
* User Role: Admin

### Additional Information
When creating the task and in single edit mode, the choices are identical. When editing tasks via the Bulk Mode, the selection options of the " assigned to" differ.

**Comment by MateStrysewske** [comment]
@OleWienke I'll add a comment to #8888 and close this issue here.
