### ISSUE TITLE
Automatic deletion based on end of process date instead of change date [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#8996]
### Problem Description
Automatic deletion rules can be defined using the deletion reference END, which currently uses the changeDate as reference date, but should instead use the endOfProcessDate.

### Proposed Change
In order to change it, first of all we need to add migration to set the endOfProcessDate for entities that were archived before the new field and related mechanics were introduced.
Luckily we can simply rely on the change date of the archived entity to do this, since setting the archived flag, will have updated the change date at that point.

- [x] Add SQL migration to set the endOfProcessDate to the changeDate for all entities that are archived: Case, Contact, Event, EventParticipant, Immunization, TravelEntry. Only do this if the endOfProcessDate of the entity is not set yet.

Finally:

- [x] In the automatic deletion logic use the endOfProcessDate instead of the changeDate for deletion reference END

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.77.0-SNAPSHOT (d975a9b)
