### ISSUE TITLE
Make SORMAS app and webapp translateable [3+0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#900]
- [x] rename property files to captions, descriptions and validations.properties
- [x] integrate fragments into captions
- [x] move captions from texts to captions
- [x] add comment to each property file to describe what it's used for
- [x] all property files should be sorted alphabetically
- [x] move all hardcoded texts to the translation files
- [x] move all android translations to strings.xml (except strings_format). Sort and clean up
- [x] research: is there a Java code generator that makes the texts directly accesible?

**Comment by MateStrysewskeSym** [comment]
- [ ] Double-check infrastructure captions/strings
- [ ] Add new infrastructure captions/strings to ghana language files

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] reenable fallback captions for districts, etc. without prefix. Maybe we use something like ".district"

**Comment by MateStrysewskeSym** [comment]
- [ ] Repair broken strings (e.g. colum names, case section names, ...)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Fallback captions currently don't work in android app, because ControlPropertyField does not use the getPrefixCaption method of property field.
