### ISSUE TITLE
[User Rights] Certain Users with CONTACT_ASSIGN = NO, are able to assign Contacts to Officers

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9002]
### Bug Description
Certain users that don't have the rights to assign Contacts to Officers (CONTACT_ASSIGN = NO), are able to select a Responsible Contact Officer.

This is reproducible for:
- Surveillance Supervisor;
- Admin Surveillance Supervisor;
- Contact Officer;

### Steps to Reproduce

1. Log in a Surveillance Supervisor;
2. Navigate to the Contacts Directory and open a Contact that was report by a different user;
3. Scroll down to the 'Responsible Contact Officer' and inspect the dropdown;

### Actual Behavior
The user can select a Contact Officer and he can also Save the selection.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/165777478-2d1b0c25-88ca-4d48-abda-a369afd77dfe.png)
![image](https://user-images.githubusercontent.com/89522688/165777232-99543887-96eb-45c1-9904-550a04d52627.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (f883c3f)
* Android version/Browser: Chrome
* Server URL: local setup
* User Role: Surveillance Supervisor; Admin Surveillance Supervisor; Contact Officer;

**Comment by MateStrysewske** [comment]
Moved this to #8959
