### ISSUE TITLE
User is not able to de-archive on his first attempt the Event Participant when he changes the 'Present condition of person' before archiving the entity

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9006]
### Bug Description
When the user changes the 'Present condition of person' right before archiving the Event Participant, he is not able to de-archive the entity anymore and he receives 'An problem has occurred' message; 
However, if he closes the messages and tries again to de-archive the Event Participant, the second time he succeeds.

Logs: 
[logs for Event Participant de-archive.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8588808/logs.for.Event.Participant.de-archive.txt)

### Steps to Reproduce

1. Open an Event Participant.
2. Select a value from the 'Present condition of person' dropdown and Save;
3. Archive the Event Participant;
4. De-archive the Event Participant;

### Expected Behavior
The user should be able to successfully de-archive the Event Participant;

### Actual Behavior
The user receives 'An problem has occurred' message. However, if he closes the messages and tries again to de-archive the Event Participant, the second time he succeeds.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/165898135-9d237662-dff6-4794-b31e-b22f9824ce0a.png)
![event participant de-archive](https://user-images.githubusercontent.com/89522688/165898349-0b6aa3fe-3df4-49ba-bf94-bfd96581dacc.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT (2fee74e)
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: Admin, National User

**Comment by MateStrysewske** [comment]
#8871 will likely fix this as well.
