### ISSUE TITLE
Multiple issues related to the 'Refer Case from a Point of Entry' action

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9017]
### Bug Description
When the user create a Case (Point of Entry) and he clicks on the 'Refer Case to a Facility' button, there are some issues.
As discussed with @MateStrysewske , these will be included in the same issue.

1) The button from the bottom of the page is named 'Refer case to a facility', but it might be confusing to the user because in the 'Refer case from point of entry' form, the user can also select 'Home' as a 'Place of Stay'. 
-> 'Refer case to a facility' should be renamed 'Refer case from point of entry'.

![image](https://user-images.githubusercontent.com/89522688/165945696-27f7437f-061b-4ab7-bf0d-f5983c7e0b07.png)

2) If the user first selects the Region/District and then 'Home' as 'Place of Stay', the 'Place Description field' appears,

![image](https://user-images.githubusercontent.com/89522688/165946088-01bc3b85-6979-46f9-b4ff-d83cbc72d255.png)

but if the user first selects 'Home' as 'Place of Stay' (-> the 'Place Description field' appears) and then selects the Region/District, right when he selects the District, the 'Place Description field' disappears.

![image](https://user-images.githubusercontent.com/89522688/165946154-1db75d04-0fc5-4d38-8152-f5a6330bdf9a.png)

3) If the user leaves the 'Place Description' field empty and tries to Save the form, the message that appears is incorrect because it says that 'Facility name & description' should be checked, not the 'Place Description' field.

![image](https://user-images.githubusercontent.com/89522688/165946378-09a9fc5e-6f14-4b84-ae71-5cad18326e63.png)

4) The 'Place Description' field is mandatory in this form, but it shouldn't, because it is not mandatory elsewhere.

![image](https://user-images.githubusercontent.com/89522688/165946591-47d243da-8551-42e1-80bf-905a12535a33.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT (f2ec80b)
* Android version/Browser: Chrome
* Server URL: local environment
* User Role: Admin, National User

**Comment by MateStrysewske** [comment]
@abrudanancuta This issue has already been released, please open a new issue for your findings.

**Comment by abrudanancuta** [comment]
The new created issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/9118
