### ISSUE TITLE
[User Rights] External Lab Officer cannot Edit and Create Pathogen Tests even though PATHOGEN_TEST_CREATE = YES and PATHOGEN_TEST_EDIT = YES

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9021]
### Bug Description
In the User Roles Export table, the External Lab Officer has PATHOGEN_TEST_CREATE and PATHOGEN_TEST_EDIT user rights.
However, in the UI, the user is not able to perform these actions because the 'Pathogen Tests' card is read-only.

### Steps to Reproduce

1. Log in with an External Lab Officer user;
2. Navigate to the Samples Directory and open a Sample;
3. Inspect the 'Pathogen Tests' card;

### Expected Behavior
External Lab Officer should be able to Edit and Create Pathogen Tests.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/165968411-3d089530-9db2-467b-8d0a-e0c00dcb0010.png)

![image](https://user-images.githubusercontent.com/89522688/165968509-2f455d02-5b6b-461e-8afa-0326f73a14a7.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (f2ec80b)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: External Lab Officer

**Comment by bernardsilenou** [comment]
If the sample is assigned to the same lab as the lab of the external lab use, then they should have full access, if no read nor edit view.

**Comment by bernardsilenou** [comment]
@roxanamlendea  is the sample assigned to the lab of the external user?

**Comment by roxanamlendea** [comment]
The External Lab Officer cannot be assigned to a certain Laboratory. 
![image](https://user-images.githubusercontent.com/89522688/166198759-7d50194c-1469-4784-a910-8732c9418273.png)

**Comment by abrudanancuta** [comment]
This ticket seems to be the same as this one https://github.com/hzi-braunschweig/SORMAS-Project/issues/8892
I would suggest to close this one as duplicate
