### ISSUE TITLE
A Hospital Informant can not see 'Immunizations' and persons associated with them if they have been created by other users

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9022]
### Bug Description

If a user creates an immunization that is within a Hospital Informant's jurisdiction (and has no other entity associated), the Hospital Informant can not see either the immunization or the person associated with it.

If the immunization is associated with a case (for example), the Hospital Informant can see the immunization as 'read only' and no information is displayed in the sections 'Facility Category', 'Facility type' and 'Facility', even though those fields had been filled in. 

### Steps to Reproduce

1. Log in with an Admin + National User and create a Hospital Informant;
2. Create an immunization and set the 'Responsible Region', 'Responsible district', 'Facility Category', 'Facility type' and 'Facility' to values that are within the jurisdiction of a Hospital Informant (for the immunization person - set the home address within the same jurisdiction);
3. Log in with the Hospital Informant created at step 1 and observe the list of entities in the 'Immunizations' directory, and the list of persons in the 'Persons' directory;
=> the immunization and person created at step 2 are not visible;
4. Log in with the admin+national user and create a case for the person created at step2 (set the 'Place of stay' within the Hospital Informant's jurisdiction);
5. Log in with the Hospital Informant user, open the case created at step 4, from the case page navigate to the associated immunization, and observe the facility related fields.

### Actual Behavior

The Hospital Informant can not see the immunization and the associated person even though they are within their jurisdiction.

The values from the facility related fields on the Immunization page are not visible.
### Expected Behavior

The Hospital Informant should be able to see the immunization and the associated person that are within their jurisdiction.

The values from the facility related fields on the Immunization page should also be visible.

### Screenshots

User:
![image](https://user-images.githubusercontent.com/96909231/165971350-964d97fd-20a0-4fb6-9c12-945267987bb1.png)

Immunization when logged in with the Admin+NatUser that created it:
![image](https://user-images.githubusercontent.com/96909231/165971514-d3202fe8-04b6-4467-b95d-09be939215ed.png)

Immunization when logged in with the Hospital Informant (view after step 5):
![image](https://user-images.githubusercontent.com/96909231/165971546-5f1feb3b-c95b-436a-9b03-5c3ae167b2f6.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(bfaf3d6)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Hospital Informant

### Additional Information

The Hospital Informant does have IMMUNIZATION_VIEW rights.

**Comment by MateStrysewske** [comment]
@adinaflorea9 I think this is fine. Hospital informants are meant to be only see data associated to cases in their hospital, i.e. immunizations that aren't connected to cases aren't of interest for them. The facility fields being empty is due to the pseudonymization.
