### ISSUE TITLE
Message type filter contains an additional blank option

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9025]
### Bug Description

In the message type filter on the lab messages directory, the enum contains an additional blank selection option.
### Steps to Reproduce

1. Open the lab messages directory
2. Open the type filter
3. Select the blank option

### Expected Behavior

There should only be lab messages an physician's report as selection options. Otherwise the filter would be unselected.
### Screenshots

![MessageTypeFilter](https://user-images.githubusercontent.com/70317594/166207813-5d765dbc-9e8b-49e4-8a99-a5be3c632395.gif)

### System Details

* Device:
* SORMAS version: 1.71.0-SNAPSHOT (4f6e61b)
* Android version/Browser: chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
Should be testable locally, or on test-de2.sormas.netzlink.com.

**Comment by abrudanancuta** [comment]
Validated on 

- local env with the version: 1.72.0-SNAPSHOT (d18330d)
- test-de2 with the version: 1.72.0-SNAPSHOT (638befd)

**Comment by AliciaRaber** [comment]
Tested on test1402.sormas.netzlink.com V1.72.1

No more blank option in drop-down-field.
![image](https://user-images.githubusercontent.com/91321821/171647924-6ef51572-9cad-439e-9a3f-7ee878252761.png)
