### ISSUE TITLE
[Angular] Add Select all per section in the custom export configuration [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9026]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1Ox22g
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP0WOOJ
- We need to add a "Select All"  /  "Deselect" option for each of the sub-sections of the custom export configurations (across the board).
- @cristinacoza please provide the different states for "Select all" (selected or unselected)

### QA Section

1. What should the QA look for (what was done)
- Check that the user can select and de-select all options for each category
- Check that this functionality works together with the "master"  select and de-select all functionality previously implemented.

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
testing done - all good
