### ISSUE TITLE
[Angular] Line listing: Move the delete button to the front column [1 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9027]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/JnvZjGM
- We need to move the delete button to the front the table.
- Also, implement the sticky option for the delete column when scrolling horizontally. 

### QA Section

1. What should the QA look for (what was done)
- Check that the button is at the front the table
- Check that the button is sticky
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
