### ISSUE TITLE
[Angular][Bug] Select items in the tables doesn't show up once the user scrolls away [3 +1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9029]
### Steps to Reproduce

1. Go to any page that has a table list
2. Select a few items
3. Scroll away (down / up) 
4. Notice that the selections made don't show up (even though they are actually selected)
5. The selection / de-selection should work as on the current Sormas implementation 

### Expected Behavior

- The selections should be persistent regardless of the actions the users make

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RobertoDascalu** [comment]
Testing done - all good
