### ISSUE TITLE
[Angular][SPIKE] Investigate what is still needed to complete the base-line structure [2] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9030]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference:
- We need to investigate all of the entities / actions / pages across the entire site (comparison between the angular component and the existing Sormas implementation).
- The outcome of this task should be in a doc / comment so we can use it as a support for upcoming plannings 

### QA Section

1. What should the QA look for (what was done)
- N/A
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by sandorbanvitagroup** [comment]
As the result of the investigation I ended up with the list below:

1.) Dashboard - contact - transmission chain

2.) Persons Basic, detailed, custom export

3.) Person detail: (right side) New travel entry,  New vaccination

4.) Cases: Line listing import

5.) Case detail: (right side) New vaccination, Share, New report, New document, Create document template

6.) Case detail: info button with case classification rules

7.) Case detail: calculate case classification button

8.) Case detail: register in climedo ediary button

9.) Case detail: hospitalization: Previous hospitalizations

10.) Case detail: epidemiological data: New travel entry

11.) Case detail: follow-up: New visit button

12.) Case detail: clinical course: new clinical assessment button

13.) Case detail: contacts: import case contacts

14.) Case detail: contacts: add line listing, add new contact

15.) Contacts: import contacts

16.) Contact detail: New vaccination, share, new document, create document template buttons

17.) Contact detail: case contacts back button

18.) Contact detail: follow-up visits: new visit button

19.) Evenets: import events

20.) Event detail: New action, New document, Create document template, Link superordinate or subordinate event, Link event group, share, see event cases, see event contacts.

21.) Event detail: Event participants: Import event participant button

22.) Samples: Lab messages: Lab message detail modal does not exist.

23.) Sample detail: (right side) Share

24.) Sample detail: contact back button

25.) Entries: import entries

26.) Travel entry detail: (right side) Create case, New document, Create document template, New task buttons

27.) Travel entry person: Contact information section : new entry button.

28.) Travel entry person: General comment section is not there.

29.) User detail: Create new password button

30.) Configuration: Facilities: Import facilities

31.) Configuration: Points of entry: Import
