### ISSUE TITLE
[Angular] Statistics: Baseline structure [5 +1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9031]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/Vrdbgp8
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/bgo9olJ
- We will implement only the right hand section (above the results)
- The user should be able to add filters, select the display, etc
- We won't implement the map / graphs, only the components with the component switch logic (with a basic message like "it works")
- We need to have the same behaviours as on the current implementation
- NOTE: Please also update the translations for the filters

### QA Section

1. What should the QA look for (what was done)
- Check that we have all of the sections and functionalities for the aformentioned sections.
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - all good
