### ISSUE TITLE
[User Rights] System crash error occurs when certain users perform the Basic Export action for Event Participants

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9035]
### Bug Description
When certain users want to download a Basic Export for the Event Participants, they receive a system crash error.

The issue can be reproduced with the following users:
- National User;
- Admin Surveillance Supervisor;
- Surveillance Officer;
- Hospital Informant;
- Community Officer;
- Community Informant;
- Clinician;
- Case Officer;
- Contact Officer; 
- Event Officer;
- Lab Officer;
- National Observer;
- Region Observer;
- District Observer;
- National Clinician;
- POE Supervisor;

The only users that can perform this action successfully are: Admin; Surveillance Supervisor and Contact Supervisor;

I attach the logs for this bug:
[logs for event participants basic export error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8602360/logs.for.event.participants.basic.export.error.txt)

### Steps to Reproduce

1. Log in with one of the users from above:
2. Navigate to the Events Directory;
3. Open an Event and navigate to the 'Event Participants' tab;
4. Click on 'Export' -> 'Basic Export'

### Expected Behavior
The export should get downloaded and no error should appear when the user closes the pop-up;

### Screenshots
![export error](https://user-images.githubusercontent.com/89522688/166222828-67f3a48c-1eab-4806-9c5a-3e6f436e6dff.gif)

### System Details

* Device: Window 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (4f6e61b)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: users from the bug description

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.72.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/fb823c8984e62b4e67b55e3b7b94a07d5abfd091)
