### ISSUE TITLE
[User Rights] POE National User has EVENT_EXPORT = YES and EVENTPARTICIPANT_VIEW = YES, even though he has EVENT_VIEW = NO

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9037]
### Bug Description
The POE National User has EVENT_EXPORT = YES and EVENTPARTICIPANT_VIEW = YES in the Export User Role table and in the UserRight.java , even though he has EVENT_VIEW = NO;

### Steps to Reproduce

1. Log in with an Admin, navigate to the Users Directory, and open the Export User Roles table;
2. Check the EVENT_VIEW, EVENT_EXPORT and EVENTPARTICIPANT_VIEW user rights for the POE National User;
3. Repeat this for UserRight.java (in IntelliJ)

### Expected Behavior
EVENT_EXPORT and EVENTPARTICIPANT_VIEW should be set to NO;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/166229021-541ad755-3bb9-48f4-bae0-d878e0240c4d.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (4f6e61b)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: POE National User

**Comment by MateStrysewske** [comment]
@bernardsilenou @kwa20 @JaquM-HZI Can you make a decision concerning which user rights the POE National User should have here?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
The challenge here is that we do not have POE type for all entities but only for cases.
Would suggest setting all the rights to NO for entity type  `EVENT_`

**Comment by MateStrysewske** [comment]
The event view user right has been added to the POE National User by now, so this issue can be closed.
