### ISSUE TITLE
Add new language (Urdu-Pk) in SORMAS [1]

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#9042]
### Feature Description

Hi Team,
Can we add the Urdu language in SORMAS? The translation is completed 100% on crowdin.com.

@MateStrysewske: Maybe you can help me out here. 

Thanks in advance. 

### Implementation Details

- Enum value name: ?
- `locale`: ?
- `dateTimeFormat`: ?

**Comment by MateStrysewske** [comment]
@kwa20 @JaquM-HZI Please make sure to prioritise this if possible.

**Comment by MartinWahnschaffe** [comment]
Language code: ur
Country code: pk
Flag: https://github.com/gosquared/flags/blob/master/flags/flags-iso/shiny/64/PK.png

See https://github.com/hzi-braunschweig/SORMAS-Project/pull/4759/files for an example.

@zohaibhassan122 Two questions:

1. What name should the language have? Normally we use the name of the language in the language itself. Or maybe "language (country)".
2. What time and date format should be used? We need formats for date, date + time and day+month. E.g. "dd/MM/yyyy", "dd/MM/yyyy HH:mm", "dd/MM"

**Comment by zohaibhassan122** [comment]
Hi @MartinWahnschaffe,

1. The name of the language is "Urdu".
2.  For Date and time, "dd/MM/yyyy", "dd/MM/yyyy HH:mm", "dd/MM" is fine as you have mentioned.
