### ISSUE TITLE
SORMAS returns 403 for requests to endpoints of the ExternalVisitsResource

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#9044]
### Bug Description

This bug breaks external journal functionalities.

### Steps to Reproduce

1. Make any valid call to a related endpoint, e.g. `curl --location --request GET '[server-url]/sormas-rest/visits-external/person/R2I5VY-WQD7GO-XBCJL6-YQ4QCIGI' --header 'Content-Type: application/json; charset=UTF-8' --header 'Authorization: Basic [valid credentials]' --data-raw '`'. Authenticate with a user having the default `REST_EXTERNAL_VISITS_USER` role.
-> 403.

### Expected Behavior

Valid response (e.g. no content when a person with the specified UUID does not exist on the system).

### System Details

* SORMAS version: 1.70.3 and 1.71.0-SNAPSHOT
* Server URL: test and prod systems (it seems that Keycloak authentication needs to be in place). E.g. https://ga1.sormas-oegd.de/.
* User Role: Default `REST_EXTERNAL_VISITS_USER`.

### Additional Information

The bug seems to often appear and disappear when the server gets restarted.

**Comment by FredrikSchaeferVitagroup** [comment]
Changes for this ticket touch the authorization mechanism of sormas-rest. I did some testing already. QA is welcome to reach out to me for clarification.

**Comment by StefanKock** [comment]
Was merged into 1.70.4
