### ISSUE TITLE
[User Rights] Certain users cannot create a new Case for Contact or an Event Participant that has a previous Case created for it by adding a positive Pathogen Test with a different disease

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9045]
### Bug Description
When a Case is created for a Contact or for an Event Participant, by adding a positive Pathogen Test with a Disease different than the Contact's Disease, then, if a certain user (eg. Contact Supervisor) wants to 'Create a Case for this Contact person' or Create a Case for an Event Participant, the system displays a fail error.

- This issue might be related to #8998
- It cannot be reproduced with all users. So far I've identified that it can be reproduced with Contact Supervisor; Contact Officer; Lab Officer (via positive Pathogen Test Result); Case Officer; POE Supervisor;

### Steps to Reproduce

Scenario 1:

1. Log in with a Admin, National User and create a Contact with 'COVID-19' selected as Disease;
2. Create a Sample and add a positive Pathogen Test Result for a different disease (eg. Anthrax) and Save;
3. In the following pop-up choose 'Yes';
![image](https://user-images.githubusercontent.com/89522688/166421672-15fd2aad-d92d-4dc0-8b75-8bf16281a720.png)
4. Fill in the mandatory fields in the 'Create new Case' form and Save;
5. Log out and log in with a Contact Supervisor;
6. Navigate to the Contacts Directory and open the Contact created in step 1;
7. Click on 'Create a Case for this Contact person'
8. Fill in the mandatory data in the 'Create new case' form and Save;

Scenario 2:

1. Log in with a Admin, National User and create a Event with 'COVID-19' selected as Disease;
2. Create an Event Participant for the Event created in step 1;
3. Create a Sample and add a positive Pathogen Test Result for a different disease (eg. Anthrax) and Save;
4. In the following pop-up choose 'Yes';
![image](https://user-images.githubusercontent.com/89522688/166681810-462dfc3e-e9c2-417f-8b4e-d09a8ff7248b.png)
5. Fill in the mandatory fields in the 'Create new Case' form and Save;
6. Log out and log in with a Contact Supervisor;
7. Navigate to the Events Directory, open the Event created in step 1 and open the Event Participants tab;
8. Click on the 'Create' button for the Event Participant created in step 2;
9. Fill in the mandatory data in the 'Create new case' form and Save;

### Actual Behavior
An error message is displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/166423271-618d01d5-51f1-4aad-9615-232f4b2bb32d.png)

### System Details

* Device: Windows 10 
* SORMAS version: Sormas 1.71.0-SNAPSHOT (78596ba)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: Contact Supervisor; Contact Officer; Lab Officer (via positive Pathogen Test Result); Case Officer; POE Supervisor;

**Comment by roxanamlendea** [comment]
I attach the stacktrace:
[scenario 1.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8638440/scenario.1.txt)
[scenario 2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8638441/scenario.2.txt)

**Comment by carina29** [comment]
@roxanamlendea I've merged yesterday the fix for https://github.com/hzi-braunschweig/SORMAS-Project/issues/9345.
The fix for that bug solves this bug too. I've tested with the mentioned users the case creation from Event Participants and from Contacts too. 
Could you please also retest on your side? :) Thank you :)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.73.0-SNAPSHOT (21bd3b8) from the development branch.
