### ISSUE TITLE
DataHelperTest.testParseDateTime tests fail locally

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#9046]
### Problem Description

I've had this issue for some time now. Recently, I got to know that others have it, too. It's not a big thing, but an annoying obstacle:

Whenever I run the sormas-backend tests locally and via maven, I get two failing tests.

```
[ERROR] Tests run: 9, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.231 s <<< FAILURE! - in de.symeda.sormas.api.utils.DataHelperTest
[ERROR] testParseDateTimeWithExceptionForDeFormat(de.symeda.sormas.api.utils.DataHelperTest)  Time elapsed: 0.032 s  <<< ERROR!
java.text.ParseException: Unable to parse date [21.4.2021 1:30 pm]
	at de.symeda.sormas.api.utils.DataHelperTest.testParseDateTimeWithExceptionForDeFormat(DataHelperTest.java:162)

[ERROR] testParseDateTimeWithExceptionForEnFormat(de.symeda.sormas.api.utils.DataHelperTest)  Time elapsed: 0.006 s  <<< ERROR!
java.text.ParseException: Unable to parse date [4.21.2021 1:30 pm]
	at de.symeda.sormas.api.utils.DataHelperTest.testParseDateTimeWithExceptionForEnFormat(DataHelperTest.java:142)
```

### Proposed Solution

- Tests should be moved to `DateHelper` because the logic resides there.
- The tests should work also on german concfigured hosts.

### Additional Information

- It may have to do with the system locale. It seems that mostly/only german devs are affected.
- Maybe #6700 should be prioritized.
- I extracted the failing pattern that should have worked. Invoking the `DateTimeFormatter` with `Locale.ENGLISH` works, but not with `Locale.GERMAN`.
```java
	@Test
	public void test() {

		Date date = DateHelper.parseDate("4/21/2021 13:30", new SimpleDateFormat("M/dd/yyy HH:mm"));

		DateTimeFormatter formatter = DateTimeFormat.forPattern("M.d.yyyy h:mm a").withLocale(Locale.ENGLISH);
		Date result = DateTime.parse("4.21.2021 1:30 pm", formatter).toDate();
		assertNotNull(result);
		assertEquals(date, result);
	}
```

**Comment by StefanKock** [comment]
Tests were moved and adjusted in #6700
