### ISSUE TITLE
selectable users differ in bulk mode and in regular edit task mode

### ISSUE THREAD

**Issue by cmeyerhzi** [hzi-braunschweig/SORMAS-Project#9048]
### Bug Description

If tasks are to be assigned to other users, the selection options differ between the bulk mode and the classic mode (gif animation).

In bulk mode I can choose between 12 users. In normal mode only between 10.

The two missing users have the role "Rest user", but there is also a user with Rest user that is displayed in bulk mode. this user also has the role "external visits user". 

the problem exists with all task types (case, contact, events)
### Steps to Reproduce

1. create a task
2. try to edit the "assigned to" box 
3.  compare to possibilities in bulk edit mode

### Expected Behavior

possibilities should be the same.
technical user should not be selectable
technical users should be defined @JaquM-HZI 
### Screenshots

regular mode:

![edittask_case](https://user-images.githubusercontent.com/96547924/166433681-77e3272f-cda2-48d3-bf00-d8a0f137eb24.gif)

bulk mode:

![edittask_bulk_case](https://user-images.githubusercontent.com/96547924/166433685-fe1a8296-78d9-4a15-86e1-418ed1a7d6c3.gif)

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser:
* Server URL: test1402
* User Role: admin

**Comment by cmeyerhzi** [comment]
maybe linked to #8888

**Comment by MateStrysewske** [comment]
Yes, it's basically a duplicate.
