### ISSUE TITLE
Contact tab is not editable when cases are archived

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9049]
### Bug Description

When the EDIT_ARCHIVED_ENTITIES = t and a case is archived, the contact tab is no longer editable.
### Steps to Reproduce

1. Open a case
2. Archive the case
3. Navigate to the contact tab

### Expected Behavior

Whe EDIT_ARCHIVED_ENTITIES = t, the contact tab should remain editable.

### Screenshots

![caseArchivedContactsTab](https://user-images.githubusercontent.com/70317594/166440282-f4604d7f-c2e8-404e-bf40-3c1abf3fdcef.gif)

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.72.0-SNAPSHOT(c630592).

Necessary configurations:
- in the DB -> 'featureconfiguration' ->set EDIT_ARCHIVED_ENTITIES = true -> 'Contacts' tab is editable;
- in the DB -> 'featureconfiguration' ->set EDIT_ARCHIVED_ENTITIES = false -> 'Contacts' tab is read only.
