### ISSUE TITLE
Allow surveillance officer to create aggregate reports (mSERS) and view reports of their district (only web UI) [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9052]
### Problem Description
For surveillance officers aggregated case reporting is currently not usable.

1. They are not able to create reports - neither in mobile nor web app
2. They are not able to view reports of other users in the district (e.g. hospital informants) - neither in mobile nor web app

### Proposed Change

- [x] give surveillance officers the user right AGGREGATE_REPORT_EDIT and also AGGREGATE_REPORT_EXPORT
- [x] extend the createUserFilter for aggregate reports to give district users access to reports in the district
- [x] do the same for users on facility and poe jurisdiction level, so they can see reports created for their facility/poe
- [x] In the web app the report region/district/facility/poe should be pre-filled based on the user. Users cannot change this for their jurisdiction level and higher (e.g. a district user cannot report for another district, but can report for any health facility within that district).
- [x] Same for the filters in the aggregation view
- [x] Check whether creating a report in the mobile app is working for the surveillance officer
- [x] Migrate user rights for user roles in the database
  Proposal: User roles that have the user right AGGREGATE_REPORT_VIEW and CASE_EDIT should receive AGGREGATE_REPORT_EDIT
  User roles that have the user right AGGREGATE_REPORT_VIEW and CASE_EXPORT should receive AGGREGATE_REPORT_EXPORT

In the mobile app the created report will automatically be assigned to the jurisdiction of the user - this is already implemented.

### Out of scope

* Giving surveillance officers a view to see the reports of other users in the mobile app will be done in a separate issue. #9073
* Changing the way reports are aggregated to prevent duplicate numbers will be done in a separate issue. #9068

### Additional Information

@bernardsilenou The AGGREGATE_REPORT_EDIT user right is currently given to the following default user roles. Are there any changes we should make here? Should the CASE_OFFICER and CONTACT_OFFICER user roles also have the right?

			ADMIN, NATIONAL_USER, NATIONAL_CLINICIAN, NATIONAL_OBSERVER, POE_NATIONAL_USER,
			STATE_OBSERVER, DISTRICT_OBSERVER, SURVEILLANCE_SUPERVISOR,
			ADMIN_SUPERVISOR, CASE_SUPERVISOR, CONTACT_SUPERVISOR,
			POE_SUPERVISOR, POE_INFORMANT, HOSPITAL_INFORMANT

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
In order to prevent duplicate reports per jurisdiction, It would be good to give both `AGGREGATE_REPORT_CREAT`  and `AGGREGATE_REPORT_EDIT ` to only one user role per jurisdictional level. 
level: user role
facility: only informants (hospital informants and POR informants)
community: None since this is optional infrastructure
district: surveillance officer 
region: surveillance supervisor
country: national user
What do you think?

**Comment by MartinWahnschaffe** [comment]
Sounds very reasonable to me. 
Can you double check this with the the countries where this is currently used (guess Nigeria and Ghana)?

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(551f50b).

Surveillance Officers are not able to export aggregate reports - logged in a separate issue #9747.

Surveillance Officers are not yet able to edit reports - when #9119 will be merged, the Surveillance Officer should be able to edit reports in the vaadin-app as well.
