### ISSUE TITLE
[DEMIS2SORMAS] The overall test result is not set for old profile messages

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9059]
### Bug Description

When a message in the old profile is sent to DEMIS and fetched by SORMAS, the sampleOverallTestResult is not set according to the interpretation of the test result.
### Steps to Reproduce

1. Upload a demis notification containing the old profile for lab messages
2. fetch message in SORMAS
3. Check the overall test result column

### Expected Behavior

Since the old profile messages do not have a `DiagnosticReport.conclusionCode`, the `labMessage.sampleOverallTestResult` should keep getting determined by the `Observation.interpretation.coding.code`
### Screenshots

<img width="847" alt="overallTestResultMissing" src="https://user-images.githubusercontent.com/70317594/166475287-010fd179-dad9-4d9d-9e69-32611854cd55.PNG">

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

example file:
[sampleOverallTestResultMissing.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8611277/sampleOverallTestResultMissing.txt)

**Comment by FredrikSchaeferVitagroup** [comment]
This ticket actually does not require any changes in SORMAS, but only in the sormas-demis-adapter. That's why I moved this ticket into its repo ([#60](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/60)).
Furthermore, I changed it to a feature request, as this behaviour was not specified before.
