### ISSUE TITLE
Cases created by officer are not synchronized

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#906]
User W6KC3X-443G3O-KC6URU-RZLYSPWM has created many cases that are not synchronized.

Error message is:

> Dto is older than existing entity: QL5MIN-TUXAO2-ENH4TH-YR7A2N4E

The following happens:

1. Sync No1: 
  Person is transferred; 
  Case is not pulled due to some other problem (likely a previously fixed bug)
2. Person is changed by user
3. Sync No 2:
  Person is not pulled, because case is not there and there is no other relation to the user (person does not have an address)
  Pushing person fails, because it does not have the latest server version
  -> complete sync fails; case is never pushed and person never pulled

**Comment by MartinWahnschaffeSymeda** [comment]
Solution to the problem:

- [ ] push returns a list of all changedates instead of the number of pushed entities
- [ ] errors are caught for each entity (e.g. too old, related entity not found, ...). They are not thrown to the mobile device - instead return null for the entities changedate
- [ ] app puts changedates into entities and accepts them. When null is passed the entity remains unsynchronized
- [ ] app counts number of unsynchronized entities

**Comment by Chinedar** [comment]
Same challenge with ISTH_INFO informant's device. Unable to synchronize cases. They have tried to synchronize the cases individually with no result.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Any update on this topic? I'd like to close the issue if everything's working now.

**Comment by Chinedar** [comment]
@Mate Yes please you can close this. Thanks.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Thanks! Make sure to tag me with my correct user name though ;D

**Comment by Chinedar** [comment]
hahahaha sure @Maté Strysewske <m.strysewske@symeda.de> lol
