### ISSUE TITLE
Error when deleting persons related to unassociated visits

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9061]
### Bug Description
An exception thrown stops the permanent deletion.

Logs for this issue: 
[fk_visit logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8611418/fk_visit.logs.txt)

### Steps to Reproduce

1. Create a Contact in the UI with COVID-19 set as Disease;
2. Create a Follow-up Visit;
3. Change the Contact's Disease to Anthrax;
4. In the DataBase, modify the 'CreationDate' of the Contact to more than 6 days ago (eg. April 15);
5. In the DataBase, in the 'deletionconfiguration' for 'CONTACTS' set the 'deletionreference' to 'CREATION' and the 'deletionperiod' to 6 (or the preferred amount of days);
6. Update the CronService.java - 'deleteExpiredEntities' - to be executed every 3 minutes (or the preferred amount of minutes);
7. Wait for the 'deleteExpiredEntities' to run;
8. Check the logs.

Note: The issue can also be reproduced with Cases;

### Actual Behavior
ERROR: update or delete on table "person" violates foreign key constraint "fk_visit_person_id" on table "visit" is displayed in the logs.
The Contact is deleted from the UI and from the DB, but the Visit is still present in the DB.

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (f48c389)
* Android version/Browser: Chrome 
* Server URL: local server
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Additional information: The step to change the disease of the contact/case is crucial because this will lead to visits that are still associated with the person, but not with any case or contact. They will therefore not be deleted alongside cases or contacts related to the person, and still exist in the database when the person is supposed to be deleted because every entity associated to the person has been deleted.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.72.0-SNAPSHOT from the development branch (88a0534).
