### ISSUE TITLE
Error when trying to merge cases with default mail-addresses

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#9064]
### Bug Description

When merging cases, an error occurs if the duplicate case had a primary email address. If the check mark for "primary email address" is removed, merging is possible without any problems.

### Steps to Reproduce

1. Create two duplicate cases
2. In only one of the cases, enter a primary email address
3. Merge the two cases and select the case without the email address as the leading case
4. As a control, repeat the steps but do not label the email address as primary

### Expected Behavior

Cases should get merged and the email of the discarded case should get adopted as the primary email address of the remaining case since it did not have a primary email address previously.

### Screenshots

<img width="374" alt="emailAddressAdoption" src="https://user-images.githubusercontent.com/70317594/166674299-95d9c512-f396-4d41-b2ab-5eef7582969c.PNG">

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by Marko-ilmkreis** [comment]
After few tests I discovered, that the error only comes up if the duplicate case has a primary email-adresse and the origin case not.

Here are the screenshots:

email-address in the duplicate case:

![grafik](https://user-images.githubusercontent.com/74791118/166659030-146c7bc8-8b21-48e3-8ad8-4b6b2d633acf.png)

contact details of the origin-case:

![grafik](https://user-images.githubusercontent.com/74791118/166659119-466787d0-043a-4d5c-96cc-9a54372dd3ab.png)


error message:

![grafik](https://user-images.githubusercontent.com/74791118/166658883-f68c41b0-95f7-4d1f-9a08-a1b1ceab6fac.png)

**Comment by kwa20** [comment]
@Marko-ilmkreis A few questions:
- Which case are you selecting as leading?
- Does the same problem occur for phone numbers?

**Comment by Marko-ilmkreis** [comment]
> @Marko-ilmkreis A few questions:
> 
>     * Which case are you selecting as leading?
The case without the mailaddress was the leading case.

>     * Does the same problem occur for phone numbers?

No, havn't had that so far for phone numbers

**Comment by kwa20** [comment]
@Marko-ilmkreis Thank you! I've updated the initial description with further information

**Comment by JanWey91** [comment]
@Marko-ilmkreis The problem only addresses duplicates of cases with separate person entities. To reproduce the error message, you need to create 2 identical persons and cases, which then is displayed in the merging list of SORMAS. 2 identical cases of the same person would always have the same (primary) contact details, as they are linked to the person entity.

**Comment by AliciaRaber** [comment]
I tested issue on /test1401.sormas-oegd.de V1.72
I got the result that mail adress merging is duplicated and one mail-address is marked as primary.


![image](https://user-images.githubusercontent.com/91321821/171607687-6138d607-8afb-4981-b64c-fd83eead1c3e.png)
