### ISSUE TITLE
Add a view to list aggregate report data and to highlight duplicates [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9073]
### Feature Description

Currently the mSERS module for aggregated case reporting only provides a view that aggregates the data for a certain jurisdiction. There is currently no way to display, edit and delete the underlying reports and also no way of detecting duplicates in the web app.

### Proposed Change

- [x] Add a new view to the Aggregate Reporting (mSERS) section in SORMAS. The existing view should be called "Aggregated Reporting" and the new view "Report Data"
- [x] The grid will list AggregateReportDto based on the filters and the user filter of the current user (use existing logic). E.g. a surveillance officer will only see aggregate reports of the own district and below.
- [x] Use the same filters available in the existing view, but without the grouping
- [x] The grid should support sorting
- [x] Entries in the grid that are duplicates of others should by displayed with a light red background. Duplicates are aggregate reports that exist multiple times for the exact same jurisdiction, disease and epi week. The goal is to highlight entries that will be ignored to calculate the aggregation totals (#9068), this means the youngest duplicate entry should not be displayed red.
- [x] Add a filter to only display all those duplicates.

### Additional Information

Out of scope:
* Lazy loading is not needed at this point, since the grid will always filter the current epi week by default
* editing & deletion will by handled by #9119

**Comment by MartinWahnschaffe** [comment]
@sergiupacurariu Looks like the not used AggregateReportViewConfiguration and AggregateReportViewType need to be removed.

**Comment by adinaflorea9** [comment]
As discussed with @sergiupacurariu, I am reopening the ticket due to the following: jurisdiction filter fields are editable for the following users:

- [ ] hospital informant - can edit 'District' and 'Facility' filter fields in the 'Aggregate reporting' and 'Report data' tabs;
- [ ] surveillance officer - can edit 'District' filter field in the 'Aggregate reporting' and 'Report data' tabs;
- [ ] district observer - can edit 'District' filter field in the 'Aggregate reporting' and 'Report data' tabs.

**Comment by sergiupacurariu** [comment]
@adinaflorea9 - your findings have been fixed with this ticket #9571 
@MartinWahnschaffe - the classes will be removed with another mSERS ticket #9119

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(5e5b8ae).

**Comment by MartinWahnschaffe** [comment]
Found an issue: 

- [ ] When configuring a primary disease as non-cases-based, it does not show, because a filter to exclude primary diseases is applied here, which should not be the case. Same in the mobile app.

@sergiupacurariu I'll take care of this.
