### ISSUE TITLE
[User Rights] Add right for Stats view

### ISSUE THREAD

**Issue by Jan-Boehme** [hzi-braunschweig/SORMAS-Project#9075]
### Feature Description

Based on https://github.com/hzi-braunschweig/SORMAS-Project/issues/830

All web users have access to the statistics module. We want only certain users to access the statistics module because of issues such as low server performance when many users are performing complex filters or fitting models at the same time.

### Proposed Change

Add a new right to SORMAS that can be attached to any role.
The right's name should be "STATISTICS_VIEW"

It should be set to false for all default roles except the following ones:
- Admin
- National User
- Surveillance Supervisor
- Admin Surveillance Supervisor
- Contact Supervisor
- National Observer

### Additional Information

@bernardsilenou FYI

**Comment by bernardsilenou** [comment]
@MateStrysewske @kwa20 
Does this right exist already?

**Comment by kwa20** [comment]
@bernardsilenou It seems to be handled by `STATISTICS_ACCESS` already, although the distribution of this right across userroles does not seem to make sense all the time, e.g. Community Officers have access while Surveillance Officers don't.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
Thanks for this information. 
The secondary use of this issue is to allow only users with the `STATISTICS_ACCESS` right to access sormas-stats. sormas-stats may contain specific stats that may not benefit all users.
We thought of adding this information in Keycloack
@JaquM-HZI  FYI
