### ISSUE TITLE
S2S_missing update from the website after share was accepted and wrong error message afterwards

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9078]
### Bug Description

After accept a sharing on target system the "accept-button" does not disappear.
If a user clicks on the "accept" button again because she/he thinks that the acceptance progress has failed the error message "error while sharing with another health department- The request can not be accepted because it is already rejected or revoked." occurs. 
If the user close the error-message-window and clicks the accept- button again the error message occurs again. This process is repeated until the user refreshes the website. Then the "accept" and "reject" buttons disappear and the case/contact is in the target system.

As figured out by @JonasCir this is not a backend error (error does not appear in the logs)
### Steps to Reproduce

1. 
2.

### Expected Behavior

1. The buttons "accept" and "reject" disappear after the accept button has been clicked. -> Page have to reload itself after a share has been accepted.
2. If an error message occurs, the error message have to be correct. "The request is already accepted, please refresh the browser."
### System Details

* Device: Windows 11
* SORMAS version: 1.70.3
* Android version/Browser: Edge
* Server URL: source system: s2s-giessen.sormas.netzlink.com target system: release-de.sormas.netzlink.com
* User Role: admin

### Additional Information

![image](https://user-images.githubusercontent.com/100844689/166714866-de6d5865-445e-4caa-b9d6-5d631fed260c.png)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by leventegal-she** [comment]
Could not reproduce "After accept a sharing on target system the "accept-button" does not disappear." It's probably caused  by a vaadin issue that sometimes it does not update the list after doing accept/reject depending on how fast the backend responds.

Adjusted the error message to "The request is already processed. Please reload the page to see the latest changes."

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup of Sormas 1.73.0-snapshot
