### ISSUE TITLE
Opening Weekly Reports page with Admin raises NullPointerException

### ISSUE THREAD

**Issue by mario-kuehne** [hzi-braunschweig/SORMAS-Project#9080]
### Bug Description

When opening Weekly Reports with user that has only Admin as user role then a Server error is shown (NullPointerExpection)

### Steps to Reproduce

1. Login with user with role Admin only.
2. Click on Reports in the menu.

### Actual Behavior
Server Error is shown (NPE)

### Expected Behavior

Admin has WEEKLYREPORT_VIEW right [(SORMAS_User_Rights.xlsx)](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-api/src/main/resources/doc/SORMAS_User_Rights.xlsx) and should be able open the Weekly Report page without errors.

### Screenshots

![WeeklyReports-Admin-NPE](https://user-images.githubusercontent.com/95228108/166883850-3479f957-9cab-45c1-bd56-4b9dd5f45e8e.PNG)

### System Details

* Device: 
* SORMAS version: 
  * Local: Version: 1.71.0-SNAPSHOT (b900a16)
  * test.sormas.netzlink.com: Version: 1.71.0-SNAPSHOT (ac57983)
* Android version/Browser: Chrome 
* Server URL:
  * Local
  * test.sormas.netzlink.com
* User Role: Admin

### Additional Information

ServerLogs (local):
[WeeklyReports-Admin-NPE.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/8629549/WeeklyReports-Admin-NPE.log)
```
	at de.symeda.sormas.api.report.__WeeklyReportFacade_Remote_DynamicStub.getSummariesPerOfficer(de/symeda/sormas/api/report/__WeeklyReportFacade_Remote_DynamicStub.java)
	at de.symeda.sormas.api.report._WeeklyReportFacade_Wrapper.getSummariesPerOfficer(de/symeda/sormas/api/report/_WeeklyReportFacade_Wrapper.java)
	at de.symeda.sormas.ui.reports.WeeklyReportOfficersGrid.reload(WeeklyReportOfficersGrid.java:173)
	at de.symeda.sormas.ui.reports.ReportsView.reloadGrid(ReportsView.java:160)
	at de.symeda.sormas.ui.reports.ReportsView.enter(ReportsView.java:152)
...
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.report.WeeklyReportFacadeEjb.getSummariesPerOfficer(WeeklyReportFacadeEjb.java:217)
```

`WeeklyReportFacadeEjb.getSummariesPerOfficer` runs into an NPE because of missing `Region`. It seems that `ReportsView.java:63` decides that the user is not on national level and therefore the following backend logic expects a region that the user apperently does not have. I guess the user also another jurisdiction level by roles which results in a lower jurisdiction level role to win `UserRole.getJurisdictionLevel.java:426`

**Comment by carina29** [comment]
@all: What should be the correct workflow here?
Since the admin has null as region in this case for which region should be the Weekly Report calculated? ( the whole process of calculation relies on the region from which the officers and the summary Dtos are calculated)
Thank you! :)

**Comment by MateStrysewske** [comment]
@carina29 The behaviour should be the same as for users on a national level (i.e. the WeeklyReportRegionsGrid should be opened). I guess the necessary change is simply to update ReportsView:63 to also include jurisdiction level NONE.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.72.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/fb823c8984e62b4e67b55e3b7b94a07d5abfd091)
