### ISSUE TITLE
 The content overlap issue on contacts dashboard 

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#9086]
### Bug Description

When you click on the contacts dashboard, the text(content) is overlapping.
### Steps to Reproduce

1. Login in SORMAS
2. Click on "Dashboard" from the Left panel side
3. Click on "CONTACTS" on top right corner
4. Then click on "Show ALL DISEASES"

### Screenshots

![image](https://user-images.githubusercontent.com/8872102/166929013-b0b658ab-6a4d-4c13-a5a7-36366757d9c0.png)

### System Details

* Device: Windows PC
* SORMAS version: 1.72.1
* Browser: Chrome 102.0.5005.63
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/
* User Role: National User

**Comment by MateStrysewske** [comment]
@zohaibhassan122 Please use the issue templates we have provided for this repository. That makes it a lot easier for us to properly handle requests.

**Comment by zohaibhassan122** [comment]
Hi @MateStrysewske,
Thanks for your feedback, I will take care next time.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of  Sormas 1.75.0-snapshot on local setup
