### ISSUE TITLE
CAPITAL ß instead of SS

### ISSUE THREAD

**Issue by SormasTheGreek** [hzi-braunschweig/SORMAS-Project#9088]
### Feature Description
Since 2008 German got an capital ß, as variant to not substitute ß to SS (like in STRASSE). 
See https://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F

### Problem Description
As I copy a persons name to my clipboard to use as template/data for the email-address (just to exclude typos with complicated names), I tend to copy substituted ß to ss. 
Just to know for sure, I have to switch to the person tab.

### Proposed Change
Just replace the substition to the new character

### Additional Information
https://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F

**Comment by StefanKock** [comment]
Duplicates #8649
