### ISSUE TITLE
Additions to sample laboratory data

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#909]
[Laboratory Variables - FINAL Review.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2675262/Laboratory.Variables.-.FINAL.Review.xlsx)

**Comment by foyiri** [comment]
This is the final variable given to us by NCDC Data team for Lassa fever

**Comment by Chinedar** [comment]
This needs to be explained better. These are variables that the Lab would like to see for Lassa fever. 

@foyiri you might need to tease out the variables that need to be included in the Lab section from the entire table.

**Comment by foyiri** [comment]
This variable are to be added to the lassa fever laboratory module of SORMAS

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig I wont find the time to work on this now. Any chance you have a look at all variables and identify what is missing and how we should add it?

**Comment by foyiri** [comment]
[on sormas and not on sormas.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2926057/on.sormas.and.not.on.sormas.xlsx)
See what i have attached with what we have when you export laboratory data and what we need to add

**Comment by MartinWahnschaffeSymeda** [comment]
First insights:

- [ ] add a field for "shipment courier" and "shipment ID" (maybe also weight)

**Comment by foyiri** [comment]
I just spoke t the lab team i was made to the following 
CT Value   qRT-PCR I Target(**two decimal places** )
CT Value   qRT-PCR II Target(**two decimal places** )
Weight   of the Package Containing the Sample in Kilogram (if YES to Q.21)
(**two decimal places** )
For Tranex it should come with a drop down list that include eg Tranex,DHL,RedStar and others
--



--



--

**Comment by MartinWahnschaffeSymeda** [comment]
See #989

**Comment by MartinWahnschaffeSymeda** [comment]
For missing requirements see #1009 and #1010
