### ISSUE TITLE
Detailed export of cases containes deleted samples

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#9092]
### Bug Description

When making a detailed export it containes deleted samples.

[samples.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8637864/samples.csv)
[sormas_fälle_2022-05-06.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8637865/sormas_falle_2022-05-06_.1.csv)

### Steps to Reproduce

1. creating case
2. delete the sample
3. make detailed export
4. the deleted sample is included

### Expected Behavior

In the detailed export should be only not deleted samples.

### System Details

* Device:
* SORMAS version: 1.70.3
* Android version/Browser:
* Server URL:
* User Role:

**Comment by StefanKock** [comment]
@carina29 #8609 is merged (d4628fe3470af8704000b8f88c1abcf5ff0fea04), you can follow with the bugfix.

**Comment by carina29** [comment]
@StefanKock ok, thank you :)

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.72.0-SNAPSHOT (fb823c8)
