### ISSUE TITLE
Permanent deletion violates foreign key constraint "fk_task_caze_id" on table "task"

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9094]
### Bug Description

Trying to delete an immunization that has a case linked, leads to an exception.

### Steps to Reproduce

1. Create an immunization via recovery and link a case to it;
2. In the DB, edit only the creation date of the immunization (try to permanently delete only the immunization).

### Actual Behavior

An exception is thrown and the deletion does not take place.

### Expected Behavior

No exception is thrown; permanent deletion is successful.

### System Details

* Device: Windows 10
* SORMAS version: 1.71.0-SNAPSHOT(c69ead0)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin,NatUser

### Additional Information

Logs:
[deletion.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8638535/deletion.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.73.0-SNAPSHOT (ec8ae73) from the development branch.
