### ISSUE TITLE
Prescription can not be deleted

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#9108]
### Bug Description

The prescription from which a treatment was created can not be deleted.
In the backend server log an exception will be thrown but the user will not receive any message and the selected prescription/prescriptions will not be deleted.

### Steps to Reproduce

1.  Create a new prescription
2.  Create a treatment from the earlier created prescription
3. Select only the prescription from which the treatment was created/select a number of prescriptions but at least one from the selections should be a prescription from which a treatment was created
4. From Bulk actions click delete

=> Nothing will happen, the prescriptions will not be deleted

![image](https://user-images.githubusercontent.com/47103965/167402736-03c9b7a4-f457-42f8-9617-6ffaca1c1f98.png)

### Expected Behavior
Delete the prescription or show a message with the reason why the prescription can not be deleted.

### System Details

* Device: Chrome browser
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL:  Local environment
* User Role: Admin + NatUser

### Additional Information
[Logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8651487/Logs.txt)

**Comment by carina29** [comment]
I will close this ticket since it's a duplicate bug of https://github.com/hzi-braunschweig/SORMAS-Project/issues/8978

**Comment by dinua** [comment]
this bug I am going to fix it in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8978 , it affects that branch too
