### ISSUE TITLE
The field "Facility name & description" is transformed into mandatory after saving the pop-up of "Refer case from point of entry"

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#9118]
### Bug Description
The field "Facility name & description" is transformed into mandatory after saving the pop-up of "Refer case from point of entry"

### Steps to Reproduce

1. As NatUser create a Case having "Point of entry" selected as Case origin
2. Don't complete the part of "Place of stay", have the mandatory fields completed
3. After saving the case open the pop-up from the button "Refer case from point of entry"
4. Choose "Facility" as place of stay
5. Complete the mandatory fields and look at the field "Facility name & description" => at this point the field is not mandatory
6. Save the pop-up
7. Look after the field "Facility name & description" => at this point the field is transformed to mandatory

### Expected Behavior
The field should have the same status in both views, either mandatory either not mandatory

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.72.0-SNAPSHOT (d18330d)

**Comment by AliciaRaber** [comment]
Test done. Facility name and description are now always mandatory.
