### ISSUE TITLE
Allow editing and deletion of aggregate report data [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9119]
### Feature Description

Currently the mSERS module for aggregated case reporting only provides a view that aggregates the data for a certain jurisdiction. There is currently no way to edit and delete the underlying reports.

#9073 introduces a view to list the actual data that was reported and to detect duplicates.

### Proposed Change

- [x] Add a column to edit aggregate reports
- [x] Important to understand: When creating a report, every row in the creation form is an AggregateReportDto (disease, age group, jurisdiction, numbers). So in theory when the user would click edit for one row in the table, it would only show a small popup that allows to edit or delete the one row of the original creation form.
- [x] Instead of doing it like that, when a user tries to edit one aggregate report entry in the grid, we should show the edit form with all aggregate report entries the reporting user of that entry has created for the same epi week and jurisdiction entity.
- [x] Thisway the user has the same experience as when creating a new report
- [x] When there are multiple entries created by the same user for the same epi week, etc. use the youngest one in the edit form
- [x] Within the edit form allow deletion of all aggregate reports shown in the form (not the grid). There is no dedicated user right for this, because editing and setting the values to 0 would also result in a deletion of the entity in the backend.
- [x] Add a delete column that provides the option to delete a row, but only for duplicates

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because of the following issue:

1. Navigate to the mSERS Directory;
2. Open the 'New Aggregate Report' form;
3. Click on 'Delete'
-> an error message is thrown:

![image](https://user-images.githubusercontent.com/89522688/177971032-836fa6e6-17dd-45f1-84d4-7991187ced12.png)

**Comment by StefanKock** [comment]
Sync flaw

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.74.0-SNAPSHOT from the development branch.
