### ISSUE TITLE
Users can use options from dropdowns when opening import windows

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#9133]
### Bug Description

When clicking on import and selecting "Line Listing" or "Detailed Import" the window for the import method remains executable allowing the user to open multiple windows. 
### Steps to Reproduce

1. Go to the case directory 
2. Click on import and select "Line Listing" or "Detailed Import" as import method 
3. Click again on "Line Listing" or "Detailed Import" again

### Actual Behavior

The window to the select the import method only dissapears when the user actively click on the import window
### Expected Behavior

The window for selecting the import method should dissapear after the user selected the import method 
### Screenshots

![Cases_Import_MultipleWindows](https://user-images.githubusercontent.com/83459190/167851215-d71c62e8-0161-4618-b051-888d76550e94.gif)

### System Details

* Device:
* SORMAS version: 1.70.4 & 1.72.0 (0866879) Snapshot 
* Android version/Browser: Chrome 
* Server URL: https://test1401.sormas-oegd.de/;  https://test-de2.sormas.netzlink.com/
* User Role: Admin National User

**Comment by MateStrysewske** [comment]
Same happens for contacts, and also allows users to switch to bulk edit mode (see #9137)

**Comment by AndyBakcsy-she** [comment]
Reopening ticket as the Contacts Directory, import and Bulk edit mode issues are still present. 
Please see Mate's comment : https://github.com/hzi-braunschweig/SORMAS-Project/issues/9133#issuecomment-1124602677

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas deployed on test-de.sormas.netzlink.com environment and also on local setup.
