### ISSUE TITLE
Case creation form gets triggered before pick or create form when converting event participants

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9135]
### Bug Description

When converting an event participant into a case, the case creation form is triggered before the pick or create case window. This leads to the user having to go through the creation form before being able to select the existing case for the respective person and also does not lead to the trigger of the "convert to case" window to select multiple additional entities (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4321).
### Steps to Reproduce

1. Create a case, confirmed contact and event participant for the same person
2. Make sure that the last contact date and event date are before the case report date or symptom onset date
3. Go to the event participant list and convert the participant into a case

### Expected Behavior

- The pick or create case window should be shown before the case creation form and suggest the already existing case in the select case list. Only if the user selects "create a new case", the creation form should open.
- Creating a case for that person should also trigger other relevant entities to be suggested for conversion (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/4321)

### Screenshots

![convertEp](https://user-images.githubusercontent.com/70317594/167852776-cd0a76e4-04f8-4f8f-8eba-caa975e52dcc.gif)

### System Details

* Device:
* SORMAS version: 1.70.4
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

Convert a contact into an existing case for reference

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.73.0-SNAPSHOT from the development branch (c045b5e).

**Comment by VincentSie** [comment]
Bug still exists. 
Tested on: 
- release-international.sormas.netzlink.com Version 1.72.1
- test1401.sormas-oegd.de Version 1.72.1
