### ISSUE TITLE
[Contacts/Import] User can open multiple import windows and switch between 'Bulk Edit Mode' and 'Merge Duplicates'

### ISSUE THREAD

**Issue by dbe21** [hzi-braunschweig/SORMAS-Project#9137]
### Bug Description

When "Import" is selected, the window where you can select between "Import", Bulk Edit and Merging stays open allowing the user to open multiple windows. The user can also swtich between the 'Bulk Edit Mode' and 'Merge Duplicates'
### Steps to Reproduce

Open multiple import windows: 
1. Go to the contact directory 
2. Click on "More" and select "Import"
3. Click again on "Import" 

Go in to *Bulk Edit Mode' or 'Merge Duplicates':
1. Go to the contact directory 
2. Click on "More" and select "Import"
3. Click on "Bulk Edit Mode" and "Merge Duplicates" 

### Actual .Behavior

The "More "selection window only dissapears when the user actively click on the import window 
### Expected Behavior

"More" selection window should dissapear after the user selected "Import" 
### Screenshots

Open multiple import windows: 
![Contacts_Import_MultipleWindows](https://user-images.githubusercontent.com/83459190/167856089-97c28262-b4fe-4111-9e46-968977bc877b.gif)

Go in to *Bulk Edit Mode' or 'Merge Duplicates':
![Contact_Import_Bulk_Merge](https://user-images.githubusercontent.com/83459190/167856213-befc3018-cd50-4a68-8245-d606852b7c72.gif)

### System Details

* Device:
* SORMAS version: 1.70.4 & 1.72.0 (0866879) Snapshot 
* Android version/Browser: Chrome 
* Server URL: https://test1401.sormas-oegd.de/; https://test-de2.sormas.netzlink.com/
* User Role: Admin National User

**Comment by MateStrysewske** [comment]
Closed because it's the same issue as #9133 and will be handled there.
