### ISSUE TITLE
[Events] Surveillance Supervisor cannot open Event Participant's page which is in his jurisdiction if the Event is not in his jurisdiction

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9139]
### Bug Description
The Surveillance Supervisor user cannot open an Event Participant's page that is in his jurisdiction if the Event is not in his jurisdiction.

This is not limited to Surveillance Supervisor user.

### Steps to Reproduce

1. Make sure you have an Event without Region and District set, but has at least one Event Participant which is in the user's jurisdiction;
2. Log in with the Surveillance Supervisor user;
3. Navigate to the Events Directory;
4. Open the Event from step 1 (is read only);
5. Click on the Event Participants tab;
6. Try to open the Event Participant that is in the user's jurisdiction;

### Expected Behavior
The user should be able to open the Event Participant's page and also edit it because he has EVENTPARTICIPANT_EDIT rights; i.e. the event participant page should not be read-only even if the user has read-only access to the event.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/167876218-9b10a3fd-6719-4dc6-9754-13d39a8a044b.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.72.0-SNAPSHOT (491840c)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: SurvSup

### Additional Information
The expected behavior here needs to be discussed because we don't have the pattern to only make certain items in a grid accessible.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.73.0-SNAPSHOT(d0284c9).
