### ISSUE TITLE
S2S_deactivate share parameter 'share associated contacts' (for cases) [2]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9146]
### Feature Description

At the moment it is possible to share cases with associated contacts.
### Problem Description

This feature is currently not suitable. If the share was successful and the user in source system adds new contacts to the case then these contacts will not be synchronised. The user in source and target system must be informed about this.
### Proposed Change

We should deactivate feature share parameter 'share associated contacts' for cases and see whether feature is requested by the health departments. If so we have to develop before activate.

For example: It is better if the user in source system has the option to select which contacts he wants to sent (otherwise there is a risk that the function will be abused due to laziness or lack of time). The user in source and target system must be informed about not existing synchronisation and in source system it must be visible in the tab 'contacts' of the case which contacts have been sent. Even better the synchronisation must be developed and then the user in source system has the option to select if added contacts in the future should be synchronised or not and target system must be informed of the decision taken. Also the target system must has the option to accept individually because this prevents that a whole share request has to be sent back because of one or a few contacts. It is also necessary that the user on source system can select to send a case without hand over the ownership with a contact with hand over the ownership.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by markusmann-vg** [comment]
If the functionality "Sharing associated contacts" is disabled the user sees "associated contacts are not shared" (in the same place where, when enabled, you could check "share associated contacts"

**Comment by leventegal-she** [comment]
Split `SORMAS_TO_SORMAS_SHARE_CASES_WITH_CONTACTS_AND_SAMPLES` feature into `SORMAS_TO_SORMAS_SHARE_CASES` and `SORMAS_TO_SORMAS_SHARE_CONTACTS` and disable contact sharing by default

**Comment by leventegal-she** [comment]
Missing database migration for the mobile app

**Comment by SahaLinaPrueger** [comment]
@markusmann-vg , @leventegal-she i spoke with Jan. 
It would be nice if you can delete the text "associated contacts are not shared" in the "share window" and in the "share request details" window. 
(I mentioned in the problem description, that the user in source and target system must be informed about the not continuously sync contacts. but this was related to the old solution, where sharing of contacts was still possible. Probably this was the misunderstanding.)

If possible the "share request details" window should **not** show the contact-section if there are no contacts and should **not** show the case-section if there are no cases. 
But if i remember correctly, this has already been implemented. Thank you very much!
![image](https://user-images.githubusercontent.com/100844689/183671453-626ba594-95bf-48f6-92a2-aa5dc03d153b.png)
