### ISSUE TITLE
ATBU_INFO and SHB_INFO informants in Bauchi not able to add new cases

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#915]

**Comment by Chinedar** [comment]
ATBU_INFO is still not able to add a case. when the "+" is selected, it returns a blank page. This is happening on the latest version 1.10.2

**Comment by Chinedar** [comment]
same challenge observed for SHB_INFO.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Oh, I understood that both have cases that cannot be synchronized. 
So for both users all data is syncrhonized? If that's the case please try to re-sycnhronize data. Important: If those uses have any unsynchronized data it will be lost when doing a re-sync.

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda we do not have data yet to be synched on both devices. I've just discovered that for the two hospitals, we have the HFs created twice, so I've set one for each as "delete" if you can search to see. But the problem persists, they hit on the plus button and get a blank page.

**Comment by MartinWahnschaffeSymeda** [comment]
Found the problem and think I also found a workarround. Please synchronize the devices and see if it works.

**Comment by MartinWahnschaffeSymeda** [comment]
> ConcurrentModificationException  - Root cause: java.util.ConcurrentModificationException - Stack trace:  java.util.ArrayList$Itr:next:831 ->  de.symeda.sormas.app.backend.facility.FacilityDao:getHealthFacilitiesByCommunity:116  -> de.symeda.sormas.app.util.InfrastructureHelper:loadFacilities:62  ->  de.symeda.sormas.app.caze.edit.CaseNewFragment:prepareFragmentData:86  -> de.symeda.sormas.app.BaseEditFragment$2:doInBackground:161 ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:65 ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:33  -> android.os.AsyncTask$2:call:304 ->  java.util.concurrent.FutureTask:run:237 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:761 - Root cause stack trace:  java.util.ArrayList$Itr:next:831 ->  de.symeda.sormas.app.backend.facility.FacilityDao:getHealthFacilitiesByCommunity:116  -> de.symeda.sormas.app.util.InfrastructureHelper:loadFacilities:62  ->  de.symeda.sormas.app.caze.edit.CaseNewFragment:prepareFragmentData:86  -> de.symeda.sormas.app.BaseEditFragment$2:doInBackground:161 ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:65 ->  de.symeda.sormas.app.core.async.DefaultAsyncTask:doInBackground:33  -> android.os.AsyncTask$2:call:304 ->  java.util.concurrent.FutureTask:run:237 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:761 - User: QTDKPR-O2ODYB-YF6TD3-DGRVKLOQ - System:  https://sormas.org.ng/sormas-rest/

**Comment by Chinedar** [comment]
Ok Martin, will do and revert ASAP. Thanks.

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda Devices synchronized, still not able to add a case. Returns a blank page.

**Comment by Chinedar** [comment]
@MartinWahnschaffeSymeda this works now. Thanks.
