### ISSUE TITLE
[Angular] Handle all request errors in an interceptor [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9152]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: across the board
- We need to implement a general solution for error handling across the board. Basically we need an interceptor to handle all such errors.

### QA Section

1. What should the QA look for (what was done)
- Basic smoke test across the board as to check that nothing that was already working is now broken
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
