### ISSUE TITLE
[Angular][BUG] Table view issues when moving (dragging) columns [3]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9155]
### Steps to Reproduce

1. Go to any table view
2. Click on a column
3. Drag the column and notice that the functionality doesn't work as expected (it moves randomly)
4. Also, notice that the checkbox / first ID (where applicable) doesn't remain fixed (sticky)   

### Expected Behavior

1. Column moving should work as expected
2. Checkbox and first ID should remain sticky 

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RobertoDascalu** [comment]
Testing done - all good
