### ISSUE TITLE
detailed case export: latestEvent details are not shown when a linked event is archived. 

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#9156]
### Bug Description

If an event is archived and a detailed case export is done, the export does not contain any entries for the column latestEvent details. 

### Steps to Reproduce

1.	Create a case
2.	Create an event and link it to the created case in Step 1
3.	Archive the linked event
4.	Do a detailed case export of the case
5.	Watch the columns eventCount, latestEventId, latestEventStatus, latestEventTitle

The same behavior can be observed when the case is archived, too. 

### Expected Behavior

The detailed case export contains the information of the latest event even when the event is archived. This also applies when the case is archived, too. 

### System Details

* Device:
* SORMAS version: 1.50.0
* Android version/Browser:
* Server URL:
* User Role:

**Comment by StefanKock** [comment]
It was implemented in #2908 that `eventCount` only takes not archived events into account (`CaseListCriteriaBuilder.buildIndexCriteria`, `CaseFacadeEjb.getExportList`), delivered with version 1.50. I'm not really sure if this is to be considered as bug or a change request.

**Comment by FredrikSchaeferVitagroup** [comment]
In my opinion, there is an inconsistent behaviour that could be considered a bug:

- archived events show in the event list of a case (screenshot), but they do not show in the detailed export
![image](https://user-images.githubusercontent.com/67001822/168550853-991551ba-c0e1-4e44-ae0b-9ff2dcfaa1b7.png)

However, I am also not sure about the expected behaviour described above. As @StefanKock pointed out, archvied events seem to be purposely excluded...

**Comment by Haberstroh-LKRastatt** [comment]
Perhaps @xavier-calland can pitch in here, since they wrote the code back in 2020. I'm with @FredrikSchaeferVitagroup here: Archived events are displayed on the case detail page, so should be contained in any exports unless otherwise specified.

**Comment by KristinaBorch** [comment]
@StefanKock in the issue https://github.com/hzi-braunschweig/SORMAS-Project/issues/2908 I cannot find any explanation why only not archived events are shown in the detailed export. As described by @FredrikSchaeferVitagroup the archived event is shown in the event list of a case, so it seems to be a bug.

**Comment by FredrikSchaeferVitagroup** [comment]
This means event counts should generally include archived events? Event counts are used for other purposes, too. For example in dashboards ([via REST](https://github.com/hzi-braunschweig/SORMAS-Project/blob/74721c731a4f4adeaf71cf3c2748ecd82aecbf50/sormas-rest/src/main/java/de/symeda/sormas/rest/DashboardResource.java#L56) and [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/74721c731a4f4adeaf71cf3c2748ecd82aecbf50/sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/DashboardService.java#L399)), and in the contact export.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup That's correct. Generally we consider all archived entities for statistics and therefore also dashboards since they are as relevant as active entities. In contrast to active entities, they're usually just no longer being wokred on and therefore sorted by archiving them.

**Comment by FredrikSchaeferVitagroup** [comment]
> @FredrikSchaeferVitagroup That's correct. Generally we consider all archived entities for statistics and therefore also dashboards since they are as relevant as active entities. In contrast to active entities, they're usually just no longer being wokred on and therefore sorted by archiving them.

Okay.  This will also affect the detailed view of cases. Currently, archived events are not shown there.
