### ISSUE TITLE
[Angular][BUG] Searching entities doesn't work as intended [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9157]
### Bug Description

- When search for an entity, inserting at least 3 chars won't trigger the search.

### Steps to Reproduce

1. Go to line listing 
2. Search for a "Case source"
3. Notice that the search isn't triggered (when inserting min 3 chars).
NOTE: On Event Group (in a group) when linking an event, notice that the search works as intended. Please look into this as this might help you out.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RobertoDascalu** [comment]
Testing done - all good
