### ISSUE TITLE
[Angular][BUG] Issues with the menu highlight when decreasing the window size [3 + 1] 

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9160]
### Bug Description

- When having a menu item selected, make the browser window smaller (as to have the burger menu) and then make it full size again. Notice that the menu highlight is now stretched across all of the other menu items.

### Steps to Reproduce

1. Select a menu item
2. Decrease the window size (as to have the burger menu)
3. Make the window full size again 
4. The menu highlight is now stretched across all of the other menu items.
### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
