### ISSUE TITLE
[Angular] Map accuracy in meters [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9161]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: Everywhere the map is used (i.e cases)
- When the accuracy in meters is set to 0 or not specified we will set a marker
- When the accuracy is > 0 we will set circle with the radiu of the value inputted (i.e "accuracy in meters" = 1 => circle with a radius of 1)
- The circle will be visible on the map when the radius is >=  30m

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - all good
