### ISSUE TITLE
[Angular] Local storage: Implement for each table [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9165]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: across the board
- We need to implement a local storage for each existing table than allows the user to drag / change column order (including normal / detailed view)
- This task is related to: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9155

### QA Section

1. What should the QA look for (what was done)
- Make changes to any table (drag column around)
- Close / re-open the browser
- Go to the same table section
- Check that the changes you made before are stil present

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done

**Comment by RobertoDascalu** [comment]
Testing done - all good
