### ISSUE TITLE
[Angular] Dashboard: Disease transmission chain [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9166]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/0D52C6FB-EB92-459B-BA00-08D5155AD11F
- We need to add the maximise option
- We need to add the "Legend"
- We need to add some dummy graph as supplied by the library (https://echarts.apache.org/examples/en/editor.html?c=graph-webkit-dep)
NOTE: No backend data will be used.

### QA Section

1. What should the QA look for (what was done)
- Check that we have the new section in the dashboard
- Check that we can maximise it
- Check that we can drag the dummy data around 

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/Ux review done - everything looks good
