### ISSUE TITLE
[Angular] Archive / De-archive option across the board [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9167]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: across the board (where applicable)
- As implemented already (@ Configuration, @danielrus), we need to replicate the archive / de-archive option for all table views (cases, events, etc).
- Note: Please check the current Sormas implementation to see where this is used.

### QA Section

1. What should the QA look for (what was done)
- Check that the archive / de-archive option is displayed correctly 

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
