### ISSUE TITLE
[Angular] Cases: Shares modal [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9168]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/wLw5mql
- We need to add the "Shares" modal 
- We need to add the same dependencies between checkboxes as per the current implementation
- We also need to implement another modal when submitting with an error
- NOTE: No backend integration yet

### QA Section

1. What should the QA look for (what was done)
- Check that we have the "Shares" modal
- Check that we have the same dependencies
- Check that we have the error modal

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
