### ISSUE TITLE
Not all data is saved when creating new entities on the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9175]
### Bug Description

When creating a new case on the mobile app, not all data from the 'Person Information' page is saved.

The information from the following fields and sections is not saved:
- [ ] salutation;
- [ ] present condition of person (and the related fields that are associated with present condition of person 'dead' or 'buried');
- [ ] new entries in the 'Addresses' section;
- [ ] type of occupation;
- [ ] staff of armed forces;
- [ ] country of birth;
- [ ] citizenship;
- [ ] new entries in the 'Person contact details' section.

### Steps to Reproduce

1. Log into the mobile app;
2. Navigate to the 'Cases' directory and open the create new case form;
3. Add information to the case in all of the fields and sections visible (including new entries for sections that have this option; current and previous hospitalization; exposures and activities as case; sample with a pathogen test; linking an event; creating a contact for the case; creating an immunization).
4. Save the case;
5. Navigate to the 'Person Information' page of the case.

### Actual Behavior

Multiple data inputted at the time of the creation of the case is missing (the data listed in the 'Bug Description').
 
### Expected Behavior

All data introduced at the time of the creation of the case is saved and displayed on the 'Person Information' page.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/168096469-2145c923-f44f-45d5-99ac-93e1d4a0faaa.png)

![image](https://user-images.githubusercontent.com/96909231/168096499-c174b718-d39d-4d0b-a8fd-128185eeaae2.png)

### System Details

* Device: Android Studio Emulator - Pixel C 
* SORMAS version: 1.72.0-SNAPSHOT
* Android version/Browser: Android 11
* Server URL: local machine
* User Role: Surveillance Officer

### Additional Information

I was only able to reproduce this behavior when creating a case on the mobile app and adding all of the possible data to the case at the time of the creation.

The behavior is also reproducible when creating contacts and event participants in the mobile app.

**Comment by adinaflorea9** [comment]
Updated the ticket's description and labels as I observed today that the behavior is reproducible when creating contacts as well.

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone connected to the server test-de.sormas.netzlink.com/sormas-rest/ on Sormas 1.72.0-SNAPSHOT (073d126)
