### ISSUE TITLE
Add user role "External Lab User"

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#918]
Should only be allowed to see samples assigned to the user's lab. No cases or any other data.

Needed for Dakar lab - see #878

**Comment by MateStrysewskeSym** [comment]
For users without the CASE_VIEW right:

- [ ] remove link to Case from Sample view
- [ ] remove "Associated case" column from samples directory
- [ ] remove everything except Case ID and Disease from case info layout

Additionally:

- [ ] Make sure that external lab users can create sample tests
