### ISSUE TITLE
Country & Region I18n sometimes not used

### ISSUE THREAD

**Issue by Candice-Louw** [hzi-braunschweig/SORMAS-Project#9181]
### Bug Description

Possibly related to: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6068

When switching to a non-de-DE language, on a non-DE configured server, the Country & Region texts for addresses are often displayed in English, and not the translated language, despite the values being translated in CrowdIn.  This does not seem to happen on DE configured servers for these languages, though.

### Steps to Reproduce

1. Case > Case Person > Home Address

INT server (fr-FR):
<img width="440" alt="image" src="https://user-images.githubusercontent.com/65529128/168138018-0ea1634a-daec-482b-b300-f6e13c211dd4.png">

CH server (de-CH):
<img width="477" alt="image" src="https://user-images.githubusercontent.com/65529128/168138782-01be19bc-de8a-492b-86d0-7b335d3ec925.png">

2. Case > Case Person > New Address

INT server (fr-FR):
<img width="373" alt="image" src="https://user-images.githubusercontent.com/65529128/168139812-726abbdc-b55e-4219-a88f-78e3ebcb07e8.png">
CH server (de-CH):
<img width="361" alt="image" src="https://user-images.githubusercontent.com/65529128/168140669-d0b400a3-ceae-46e8-a00d-a6f060f89117.png">

### Expected Behavior

Chosen language text is displayed.

### System Details

* Device: PC
* SORMAS version: 1.71.0
* Android version/Browser: Chrome
* Server URL:
https://release-international.sormas.netzlink.com/sormas-ui/#!cases/person/TVA2SN-4RFGIT-MUTVD7-F5K32HC4
https://stable-release-ch.sormas.netzlink.com/sormas-ui/#!cases/person/WKFA3R-YC55AX-EB3KPL-YIAPKA5E
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
@Candice-Louw These translations have only been added very recently because they were missing before, I suspect that the reason why they're not properly translated for other languages could be that they're simply not translated yet?

I've just merged some new translations e.g. for French and Czech, those should be available after the next deploy on the test instances.
