### ISSUE TITLE
[S2S] Synced infrastructure data breaks imports

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9189]
### Bug Description

When trying to import cases into an instance that has synced s2s infrastructure data, the import fails due to the responsibleRegion not being recognized as a region inside the server country. This makes imports impossible for desired jurisdictions and is likely not limited to cases.
### Steps to Reproduce

1. Make sure to set up the respective system in the following way: 
1.1 country.name=germany
1.2 country.locale=de-DE
1.3 german default infrastructure data
1.4 sync the infrastructure data with the central s2s infrastructure data
3. Perform an import referencing a german region and district as responsible jurisdiction
4. As a control, perform the import on an instance not configured with S2S

### Expected Behavior

Synced S2S infrastructure data should be associated as jurisdictions of the server country.

### Screenshots

![s2sBreaksImports](https://user-images.githubusercontent.com/70317594/168279446-e13b61ae-ee2c-4df6-9c84-f372c867d6aa.PNG)

### System Details

* Device:
* SORMAS version: 1.70.4/1.71.0
* Android version/Browser: chrome
* Server URL: test-de2.sormas.netzlink.com, release-de.sormas.netzlink.com; control: test1401.sormas.netzlink.com
* User Role: Admin, National User; Admin, Surveillance Supervisor

### Additional Information

Changing `EDIT_INFRASTRUCTURE_DATA` did not have an effect

Example file:
[sormas_import_case_test.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8686894/sormas_import_case_test.csv)

**Comment by Jan-Boehme** [comment]
I tried to check if I could find the reason and did a database export on release-de.sormas.netzlink.com but the data looks fine to me.

Regions table:
All regions are linked to country ID 2825

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/6122778/168286752-d1d9ba29-bffb-4863-a916-99f36eedfbf5.png">

Country table:
Germany has ID 2825

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/6122778/168287218-cdb1d9fb-6868-4bbf-8b10-afd917e004a9.png">

**Comment by Jan-Boehme** [comment]
The easiest way imho is to use "Germany" in the central data as well for now. This is how it is currently and we know that it does not have any side effects.

The question is how much work would it be to change this?

Is it enough to change "Deutschland" to "Germany" in these two files?
https://github.com/hzi-braunschweig/SORMAS-central-data/blob/main/out/germany/country.csv
https://github.com/hzi-braunschweig/SORMAS-central-data/blob/main/out/germany/country.json

**Comment by kwa20** [comment]
I think it generally would be a good idea to handle everything consistently in English and let translations be only translations. Even if it would be a bit of work it might be worth it.

**Comment by Jan-Boehme** [comment]
After talking to @MateStrysewske the desired state is to have "defaultName" in english for all countries.
Which means we need to follow the suggestion of @kwa20

**Comment by JonasCir** [comment]
@Jan-Boehme 
Just FYI Netzlink hat `germany` in their config, not `Germany` so this needs a new templating run with Ansible anyways.

**Comment by JonasCir** [comment]
But yeah we can patch the generation script to emit `Germany` and then upload it to central. From there it should be picked up by all instances.

**Comment by JonasCir** [comment]
So https://github.com/hzi-braunschweig/SORMAS-central-data should now contain the patched data, we wait for it to land in `etcd` and then test.

**Comment by JonasCir** [comment]
@Jan-Boehme @kwa20 Can you test this again and close it if the data we provided fix the problem?

**Comment by kwa20** [comment]
I've tested the import linked in the original description on the test instances test1402.sormas.netzlink.com, release-de.sormas.netzlink.com and release-sormas-x.sormas.netzlink.com. All have S2S configured and the import worked on all instances. I'll therefore close this issue.

@JonasCir Maybe you can add the relevant milestone and backlog transition :)

**Comment by JonasCir** [comment]
Delegating to @vidi42 : can you please  take care of the sprint related stuff, not certain what should be applied here :)
