### ISSUE TITLE
Declare overall pathogen test result for sample [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#919]
~~Add a checkbox to sample tests that allows the user to mark a final test result.
When this is set for the test of a sample it will be cleared for all other tests of that sample.~~
The final test result is display in the samples directory and used in exports.

**Comment by MartinWahnschaffeSymeda** [comment]
Change based on yesterdays meeting:

- [ ] "result verified by lab supervisor" -> make requiered yes/no field
- [ ] add "laboratory result" field to sample (use sample result type)
- [ ] whenever a test is created or edited (and the result changed) show a popup and ask the user to update the laboratory result. Don't do this when not verified
- [ ] show this in the samples list
- [ ] update the automatic classification to use this

**Comment by MateStrysewskeSym** [comment]
- [ ] check whether saveCallback is actually needed or save notification can simply be shown anyway
