### ISSUE TITLE
Detailed exports is slowed down by `getRelevantSortedVaccinations` pattern [3]

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#9193]
### Problem Description

Detailed export of cases and contacts is slow for large numbers of cases and contacts. To reproduce go to case respectively contact directory and start detailed export. May be reproducible with a sufficient number of immunizations in the database only. This may be relevant for German health departments.

**Note:** this has been tested after the merge of PR #9065 for issue #8609.

<details>
<summary>Detailed analysis</summary>
In this analysis, the export has been started once for each entity from the UI, resulting in several calls to the actual FacadeEjb method.

![image](https://user-images.githubusercontent.com/5616564/168328488-2a5b32b7-4635-41bc-a27c-c5f8389b93d0.png)

The following methods call `getByUuid` methods for individual entities, accounting for a relevant part of the runtime. A suitable replacement by a bulk fetch should help.

`CaseFacadeEjb`, l.1274ff:
```
	private List<Vaccination> getRelevantSortedVaccinations(String caseUuid, List<Vaccination> vaccinations) {
		Case caze = caseService.getByUuid(caseUuid);

		return vaccinations.stream()
			.filter(v -> vaccinationService.isVaccinationRelevant(caze, v))
			.sorted(Comparator.comparing(ImmunizationEntityHelper::getVaccinationDateForComparison))
			.collect(Collectors.toList());
	}
```

`ContactFacadeEjb`, l2253ff:
```
	private List<Vaccination> getRelevantSortedVaccinations(String caseUuid, List<Vaccination> vaccinations) {
		Contact contact = contactService.getByUuid(caseUuid);

		return vaccinations.stream()
			.filter(v -> vaccinationService.isVaccinationRelevant(contact, v))
			.sorted(Comparator.comparing(ImmunizationEntityHelper::getVaccinationDateForComparison))
			.collect(Collectors.toList());
	}
```
(parameter `caseUuid` actually is a contact Uuid)

Same pattern in `EventParticipantFacadeEjb.getRelevantSortedVaccinations` too.

</details>

### Proposed Change

A speedup may be obtained by reducing avoidable database queries for individual JPA entities and replacing them by a suitable query to fetch the according data in bulk.

1. Do not fetch `Case`/`Contact`/`Event`, but use the attribute already fetched in the main query. Missing attibutes: `Case.symptoms.onsetDate` (if merged picked directly would cause another JOIN), `Event.reportDate`
2. Unify the `getRelevantSortedVaccinations?` from several facades to one method in `VaccinationService.getRelevantSortedVaccinations(Vaccinaction entity, Date... relevanceFilterDates)` and `VaccinationService.isVaccinationRelevant(Vaccinaction entity, Date... relevanceFilterDates)`

- Always fetch `Case.symptoms` to get `Case.symptoms.onsetDate` but only export symptoms them if requested for export?

### Acceptance Criteria

- [x] Have a before/after performance analysis that shows the improvement.

### Additional Information

The proposed refactoring has been implemented in PR #9843. Measuring the performance of the detailed export before and after the refactoring meets the expected performance gain for cases and contacts export:

- 85262 cases:  >11 min  (676 sec) before --> 4.5 min (272 sec) after, runtime reduced by 60%
- 114394 contacts: 3.5 min (211 sec) before --> 1 min (60 sec) after, runtime reduced by 72%

The dataset used in this test did not provide enough data for event participants to allow for a solid measurement. However it is reasonable to assume a performance gain at a similar scale for larger datasets.

<details>
<summary> Performance before and after refactoring</summary>

Before:
![image](https://user-images.githubusercontent.com/5616564/178914413-2a623bce-f016-462e-aab6-8e87af9e1afb.png)
After:
![image](https://user-images.githubusercontent.com/5616564/178915871-febdb1aa-72ac-492e-9275-9eec19d66350.png)
</details>

To be noted is that there is still a considerable amount of data which is read for each result set entry one by one. It might be worth investigating if these database calls can be either integrated in the initial fetch or be read in a single collective database call for all entries (as implemented for symptoms in `CaseFacadeEjb.getExportList`, l. 889ff).

**Comment by AndyBakcsy-she** [comment]
Validated ticket on local setup. 
Tested that the Detailed export does not lose any data.
Used for testing the Sormas Version 1.75.0-snapshot (c5c40bf)

**Comment by StefanKock** [comment]
> Used for testing the Sormas Version 1.75.0-snapshot ([c5c40bf](https://github.com/hzi-braunschweig/SORMAS-Project/commit/c5c40bf3d3e4169d91017c6a574f6f5aee112deb))

The changes should not have been on development yet, but unfortunately #9929 sneakly injected the changes of this ticket already. This brings likely painful merge conflicts for hotfix finish of 1.74.1
