### ISSUE TITLE
[DEMIS2SORMAS] Simultaneous fetching warning appears even for just one user

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9204]
### Bug Description

When messages are fetched for the first time in the lab messages directory, a warning for simultaneous fetching appears even when only one user tries to fetch the messages.
### Steps to Reproduce

1. Start with an empty lab messages directory or restore the database to a state where this is the case
2. Press "fetch lab messages" to initially fetch the messages - make sure only one user presses the button 
3. Check the window that appears

### Expected Behavior

The warning should not appear when only one user fetches messages for the first time.
### Screenshots

<img width="750" alt="fetchAnotherUser" src="https://user-images.githubusercontent.com/70317594/168577281-103b5f7b-745a-4d24-97a6-55b070e78e8f.PNG">

### System Details

* Device:
* SORMAS version: 1.71.0
* DEMIS Adapter: 1.16.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by FredrikSchaeferVitagroup** [comment]
The bug description indicates a misunderstanding of how SORMAS tries to detect simultaneous fetching of lab messages. SORMAS does not check existing lab messages for that. Deleting all lab messages has no effect on this detection mechanism.

Instead, it is checked for system events indicating unfinished fetching attempts. Those may come up when a user (also the same one) previously tried to fetch lab messages, but an uncaught error occured or the system crashed. Those system events stay unfinished, until they get manually cancelled.

@kwa20 This is what you most likely experienced. Can you try to verify that? You could either delete all entries from the systemevent table in the database, or click on `YES` in the popup. This will kind of cancel the unfinished system event. The popup should then not show up anymore.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup After pressing `YES`, I was able to then procede with the fetching and subsequent fetches did not show this pop-up, i.e. it only appeared when initially trying to fetch messages. However, this happened after restoring the database to a previous state that includes specific test data which has no entries in the messages directory. Maybe the point of the backup leads to this behaviour? This is just a suspicion though.

**Comment by FredrikSchaeferVitagroup** [comment]
Probably. As I said, the message directory has no effect on this warning. It is the systemevent table in the database, that has no place in the UI.
If you want to be really certain, we need to check this table on test-1402. Otherwise, I would just discard this ticket...

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup The systemevent table indeed showed unfinished fetches. The only thing that is a bit odd is the start date of the attempts because these were not executed by a user. If this is nothing to worry about, these would at least explain the behaviour mentioned in the issue.

![Clipboard - May 30, 2022 12_45 PM](https://user-images.githubusercontent.com/70317594/170977179-6577c01c-5783-4b93-8793-9e1346173898.png)

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 There is a cronjob fetching messages at 1:35 every day. I find it a little weird that there are two events, but I also find it's not really something to worry about. So, I will discard ths ticket now.
