### ISSUE TITLE
[DEMIS2SORMAS] First time fetching pop-up does not close after the fetching process has finished

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9205]
### Bug Description

When lab messages are being fetched for the first time, users are asked whether they want to specifiy a specific start date. After the fetching has been finished, this window remains opened.
### Steps to Reproduce

1. Fetch messages for the first time
2. In the pop-up, select any option besides CANCEL and wait until the process has finished
3. Check the display afterwards

### Expected Behavior

The window should close after starting the fetching process.

### Screenshots

<img width="817" alt="fetchWindowDoesNotClose" src="https://user-images.githubusercontent.com/70317594/168578073-77ece836-948e-41da-a986-ce19f3ee28e1.PNG">

### System Details

* Device:
* SORMAS version: 1.71.0
* DEMIS Adapter: 1.16.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.72.0-SNAPSHOT (https://github.com/hzi-braunschweig/SORMAS-Project/commit/fb823c8984e62b4e67b55e3b7b94a07d5abfd091)
