### ISSUE TITLE
CREATION and ORIGIN are not correctly displayed for automatic deletion configurations

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9207]
### Bug Description

When either `ORIGIN` or `CREATION` are configured as `deletionreference`, end of processing is stilled displayed when hovering over the scheduled deletion info (cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/7240)
### Steps to Reproduce

1. Configure the deletionconfigurations with the references CREATION and ORIGIN (travel entries) separately
2. Check the respective UI display per associated entity

### Expected Behavior

- When `CREATION` is configured, the creation date should be displayed as reference in the info display
- When `ORIGIN` is configured, the date of arrival should be displayed as reference in the info display

### Screenshots

<img width="395" alt="wrongDeletionReferenceDisplay" src="https://user-images.githubusercontent.com/70317594/168623488-6a603586-57f1-4ea9-9251-c2e89c857887.PNG">
<img width="396" alt="wrongDeletionReferenceDisplay2" src="https://user-images.githubusercontent.com/70317594/168623504-0dc80058-b974-430e-b4f8-8fa4948d3900.PNG">

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Additional Information

database exports of deletionconfiguration table:
[deletionconfig_referenceDisplay_origin.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8701185/deletionconfig_referenceDisplay_origin.csv)
[deletionconfig_referenceDisplay_creation.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8701186/deletionconfig_referenceDisplay_creation.csv)

**Comment by roxanamlendea** [comment]
Reopening the ticket because only the date is changed accordingly to the CREATION / ORIGIN. The caption should also be changed accordingly.
![image](https://user-images.githubusercontent.com/89522688/177530409-4c27c724-0038-4e1e-9267-016deaa42436.png)

**Comment by MartinWahnschaffe** [comment]
Needed implementation changes:

- [ ] Rename AbstractCoreFacadeEjb.getDeletionData to getDeletionReferenceDate and only return the reference date (not always the change date).
- [ ] Rename DeletionInfoDto.endOfProcessing to referenceDate
- [ ] Add changeDate = "Date of last change" to the captions.properties
- [ ] Add deletionReferenceField string to DeletionInfoDto. Use it in the UI to display the caption of the field used as deletion reference in combination with the I18n prefix of the entity: 
  E.g. CaseDataDto.I18N_PREFIX together with the deletionReferenceField name (e.g. changeDate). This is important so the dateOfArrival caption is correctly displayed for travel entries.

Note: This means currently it will not say "end of processing" anymore here, until  #8996 is implemented.

Note: For "END" deletion the system still uses the change date, so currently the caption
