### ISSUE TITLE
Add paging to Android list views [3+X]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#921]
Relevant for all lists. Investigate on how to best implement the following aspects

- [x] make queries lazy: query x entries starting at y. Add count query. 
- [x] ViewModel/DataProvider to provide the data for a view/adapter
- [x] When user scrolls load additional entries
- [x] do for cases

Remaining lists will be done in #945

**Comment by MateStrysewskeSym** [comment]
## Paging

> The PagedList class works with a PagedListAdapter to load items into a RecyclerView
https://developer.android.com/topic/libraries/architecture/paging/

**Comment by MateStrysewskeSym** [comment]
- [ ] rename BindingPagedListAdapterAdapter
- [ ] fix log message in AbstractAdoDao.countOfEq
