### ISSUE TITLE
Make android-app update on TEST instances working [?]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9213]
### Problem Description

The `android-app` update does not work with the deployed apks on TEST instances.

### Proposed Solution

It appears to be related to some infrastructure configuration that interacts with the update mechanism of Android OS.

First step: Debug/Watch if file transfer does by network log protocols.

### Additional Information

- The file can be directly downloaded by URL call, but not by Android OS (without giving any helpful insight).
- It might be that download itself does work, but the software replacement on Android device does fail due to some local state.

**Comment by mario-kuehne** [comment]
> Found the issue. In the server-start script of SORMAS Docker, a semicolon was appended to the app URL which lead to a 404 error when trying to access the .apk file.

https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/sormas/start-server.sh#L244

**Comment by mario-kuehne** [comment]
Tested with following combinations
* Installed `sormas-1.70.0-release.apk` on Emulator (`7  WSVGA (Tablet) API 24.`)
* Connected `https://release-international.sormas.netzlink.com/sormas-rest` in settings of Mobile App (currently 1.72.1 is deployed)
* Logged in with Hospital Informant
* Accepted Prompt for Downloading the newer Mobile App Version
* Accepted Prompts for Installing the newer Mobile App Version
* Checked version 1.72.1 in settings of Mobile App (as soon initial synchronization finished and initial setup workflow in Mobile App has been done)

**Comment by mario-kuehne** [comment]
retested B) test.sormas

* Installed `sormas-1.70.0-release.apk` on Emulator (`7  WSVGA (Tablet) API 24.`)
* Connected `https://test.sormas.netzlink.com/sormas-rest` in settings of Mobile App (currently 1.73.0-SNAPSHOT with commit hash [3d0b731](https://github.com/hzi-braunschweig/SORMAS-Project/commits/3d0b731fefec0f3f5a2401d34918eb132a3758a4) is deployed)
* Logged in with Hospital Informant
* Accepted Prompt for Downloading the newer Mobile App Version
* Accepted Prompts for Installing the newer Mobile App Version
* Reopen Mobile App
* Login with Hospital Informant and synchronization worked
* Checked version 1.73.0-SNAPSHOT in settings of Mobile App
