### ISSUE TITLE
Encode filters in URL [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#922]
Especially for directories, but also for filters on dashboard.

Implementation notes:

- [x] central object for this should be the existing Case/Contact/...Criteria. Add toUrl and fromUrl methods to serialize it
- [x] in views (e.g. directory) create criteria from url and update filter components
- [x] when going into case keep the criteria in the vaadin session cache
- [x] add reset button
- [x] do this for cases directory
- [x] contacts directory
- [x] events directory
- [x] samples directory
- [x] tasks directory
- [x] ~implement url for task type list filter~
- [x] infrastructure directories (fix parameters being reused in different views)
- [x] exclude text filters (possible leak of data to url) - probably per annotiation
- [x] check conflict between view mode parameter and other parameters
- [x] fix archived items always being shown, even when only active items should be displayed (reason: service does not add an archived filter when archived in criteria is null)

**Comment by MateStrysewskeSym** [comment]
- [ ] Fix case subsections not working anymore
