### ISSUE TITLE
Tasks linked to a deleted case are still visable in the task directory

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#9222]
### Bug Description

If a case with an existing task is deleted, the task can still be found and opened via the task directory when the filter is set to "All Tasks". 

### Steps to Reproduce

1. Create a case and a task for this case
2. Delete the case
3. Go to the task directory and make sure that the filter is set to "All Tasks"
4. Go through the list and look for the task with the deleted case
5. Open the case

### Expected Behavior

The task should be deleted together with the deleted case. 

### Screenshots

Step 1. 
![image](https://user-images.githubusercontent.com/98821699/168797240-6174cd01-3252-4bfc-873a-2a232ced8227.png)

Step 3/4. ![image](https://user-images.githubusercontent.com/98821699/168797409-ccca2bfe-38e7-4481-9197-74cb7d79fbfb.png)

Step 5. ![image](https://user-images.githubusercontent.com/98821699/168797475-5073190c-8ea3-481b-980d-28921dcf0b8a.png)

### System Details

* Device: 
* SORMAS version: 1.71 (test1401) ; 1.72 (test-de1)
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AliciaRaber** [comment]
I performed the test again. I can confirm that tasks associated to deleted case can not be found anymore.
