### ISSUE TITLE
`Vaccination.vaccineBatchNumber` not synced to android-app

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9230]
### Bug Description

Split from #9216: `Vaccination.vaccineBatchNumber` is not synced to android-app when set in vaadin-app.
### Steps to Reproduce

1. Create a contact form the vaadin app
2. Add an immunization with at least one vaccine to the contact from step 1 (fill in all fields from the forms);
3. Save the contact and do a sync in the mobile app;
4. Observe the vaccine's card.

### Expected Behavior

Data is synced back and forth between android-app, backend and vaadin-app.

### System Details

* SORMAS version: 1.71.x, ..., 1.63.0 

### Additional Information

Caused by #4763: I checked that only `Vaccination.vaccineBatchNumber` mapping is missing for in `VaccinationDtoHelper` in #4763.

**Comment by roxanamlendea** [comment]
Verified ticket on Android 11 phone emulator connected to the server https://test.sormas.netzlink.com/sormas-rest/ and https://test-de.sormas.netzlink.com/sormas-rest/
