### ISSUE TITLE
Perfomance - Open Directorys

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9233]
### Bug Description
Directories or entries are only displayed after a 5-10 second delay. Loading and leaving the Contact Directory can take longer then expected. For the loading times between approx. 30 seconds and 3 minutes were observed. The problem seems to be user dependent.

Netzlink already checks this with the "[Ticket 2022136395] Your request: Performance Check"
Interim result: 
* Infrastructure is OK
* Database queries are currently being examined more closely.

### Steps to Reproduce
Click on the button "Contacts"

### Expected Behavior
Performant opening of the lists.

### System Details

* Device:  Laptop
* SORMAS version: 1.71.0
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/
* User Role: Admin , Admin + National User

**Comment by MateStrysewske** [comment]
We're currently working on this in #8938.
