### ISSUE TITLE
[Angular][Bug] "Add new address" issues and improvements [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9238]
### Steps to Reproduce

1. From a case, open the "Add new address" modal
2. Make a change in the form
3. Close the form 
4. Notice that u can't select another link and the site become usable only after a refresh. 

Note: The modals should have the same texts and actions as the current implementation. (Cancel, Discard & Save)
Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/VrvEOpq 

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by RobertoDascalu** [comment]
Testing done - all good
