### ISSUE TITLE
[Angular] Merge duplicates: Re-styling [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9239]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/bgb1LKo

### QA Section

1. What should the QA look for (what was done)
- Check that the user can better differentiate between base and duplicate case
- The Merge actions will remain on the right hand side of the table.

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
Reference design added 
The Merge actions will remain on the right side of the table.

**Comment by RobertoDascalu** [comment]
Testing done - all good
