### ISSUE TITLE
[Angular] All fields from the "Statistics" page should be of the same width [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9240]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/3OQ7mGr#Version
- We need to make all fields from the "Statistics" page should be of the same width 

### QA Section

1. What should the QA look for (what was done)
- Check that all of the fields are of the same width

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/Ux review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done :
-selecting case incidence,user should not be able to see incidence divisor field
-selecting Chart/Pie ,user should not be able to se X-axis field

**Comment by RobertoDascalu** [comment]
Testing done - all good

**Comment by RobertoDascalu** [comment]
Testing done - all good
