### ISSUE TITLE
[Angular][UI/UX] Investigate and create an improvement to the Statistics filters [2]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9241]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: 
- Based on the feedback received in the Sprint Review (115) we need to find a way to group the filters in a better way, as to add another higher level for the filters (i.e Filters-> Case- > etc)

### QA Section

1. What should the QA look for (what was done)
- N/A
2. What can the QA ignore (what was omitted)
- N/A

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
On the Statistics filters section the user will first select the filters categories.
Each category will have specific filters that user can add to filter specific/desired data.
Design reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/1K4W7D5#Version
