### ISSUE TITLE
Install of new app version is not triggered when the app is compatible

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#925]
Tried this when updating my device from 1.10.0 to 1.10.2.
The download is triggered and done, but when I restart the app afterwards the install dialog does not pop up.

**Comment by MartinWahnschaffeSymeda** [comment]
I also could not reproduce the part with the install dialog not appearing.

**Comment by MateStrysewskeSym** [comment]
- [ ] also close progress dialog when app update fails
