### ISSUE TITLE
Resulting cases do not get linked to their contact

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9254]
### Bug Description

Resulting cases are not linked to their respective contact, both when they are created manually from the 'Contact page' - 'Create a case for this contact person' button, or via a sample with a positive pathogen test result.

### Steps to Reproduce

1. Create a contact (set disease as Covid-19);
2. Add a sample with a positive pathogen test result (of Covid-19);
3. Pop-up to create a resulting case for the contact person appears;
4. 'Create new case' form appears; 
5. Fill in the form and save the resulting case;
6. Observe the 'Epidemiological data' tab of the new case and the 'Contact' page.

### Actual Behavior
 
In the case's 'Epidemiological data' tab, the contact from step 1 is not linked in the section 'Contacts with source case'.

On the 'Contact' page of the contact from step 1, the 'Create a case for this contact person' button is still visible, it can be clicked, and the user can add multiple other cases to the same contact.

The contact's status is 'Dropped' instead of 'Converted to case'.
### Expected Behavior

In the case's 'Epidemiological data' tab, in the section 'Contacts with source case' section, the contact from step 1 is linked.

On the case page, the 'Create a case for this contact person' button is replaced by 'Open case of this contact person'; when clicked, the button redirects the user to the case from step 5.

The contact's status is 'Converted to case'.

### Screenshots

GIF of the behavior:
![Resulting case](https://user-images.githubusercontent.com/96909231/169242355-a97225bd-a706-4c22-b6fc-aadff1fb5705.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.73.0-SNAPSHOT(92d0095)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information

Issue was observed while testing #8998.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of Sormas 1.73.0-snapshot on local setup
