### ISSUE TITLE
Follow up end date is not changing in Climedo when converting a Contact to a Case

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#9261]
### Bug Description
Follow up end date is not changing in Climedo when converting a Contact to a Case

### Steps to Reproduce

1. Open a REGISTERED Contact in Climedo and note it's follow up end date from there.
2. Make sure the contact person has no other contacts and/or cases in SORMAS.
3. In SORMAS, covert the contact to a Case.
4. Open the case in Climedo and check if the follow-up until date change is reflected on the Climedo side.

### Actual Behavior
The follow-up until date is not changing, it remains from the Contact follow up end date

### Expected Behavior
The follow-up until date change should be available also on the Climedo side. It should be set to the case follow up until date (instead of the converted contact's follow up until date).

### System Details

* Device: 
* Version: 1.71.0-SNAPSHOT (f48c389)
* Server URL: https://ga1.sormas-oegd.de/
* User Role: NatUser

**Comment by FredrikSchaeferVitagroup** [comment]
It happened with this [person](https://ga1.sormas-oegd.de/sormas-ui/#!persons/data/UXY5K7-T5NUVV-JHB4K2-KZXUSMBU).
When fetching the person data via `{environmentUrl}/sormas-rest/visits-external/person/UXY5K7-T5NUVV-JHB4K2-KZXUSMBU`, the correct follow up end date gets returned.

**Comment by FredrikSchaeferVitagroup** [comment]
This does not seem to be reproducible. We tried several times, also on [ga1](https://ga1.sormas-oegd.de/). It always worked flawlessly. Related log entries could be found, neither on SORMAS, nor on climedo side.
After having changed the follow up end date of the [affected person](https://ga1.sormas-oegd.de/sormas-ui/#!persons/data/UXY5K7-T5NUVV-JHB4K2-KZXUSMBU) manually, the synchronization also worked.
It think it not reasonable to further investigate here, probably there was a temporary connection problem.
