### ISSUE TITLE
Clinical / Epidemiological / Laboratory Diagnostic Confirmation fields appear empty in 'Edit Case' mode

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9280]
### Bug Description
After a user selects Yes, No or Unknown for the 'Clinical Confirmation', 'Epidemiological Confirmation' and 'Laboratory Diagnostic Confirmation' fields, after Save, the selected input appears in 'Read Case' mode, but in 'Edit Case' mode, those fields appear empty;

### Steps to Reproduce

1. Open the mobile app and open a Case;
2. Select 'Yes'. 'No' or 'Unknown' for the following: 'Clinical Confirmation', 'Epidemiological Confirmation' and 'Laboratory Diagnostic Confirmation' and Save;
3. Verify the fields in 'Read Case' mode and in 'Edit Case' mode;

### Expected Behavior
The selection made previously should be present in both 'Read Case' mode and 'Edit Case' mode;

### Actual Behavior
The selected input appears in 'Read Case' mode, but in 'Edit Case' mode, those fields appear empty;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/169512154-40a1b1a9-cf20-4f5b-acf7-0fcb4198d20d.png)
![image](https://user-images.githubusercontent.com/89522688/169512173-5327649d-f236-4f27-83ae-9b5d6d97f1b7.png)

### System Details

* Device: Pixel 4 Emulator
* SORMAS version: Sormas 1.72.0-SNAPSHOT (073d126)
* Android version/Browser: Android 11
* Server URL: [https://test-de.sormas.netzlink.com/sormas-rest/](https://test-de1.sormas.netzlink.com/sormas-rest/)
* User Role: SurvOff

**Comment by syntakker** [comment]
Visibilities and updates diverged in the mobile app diverged from the Vaadin app. Both were introduced in #4218.
The mobile app has been fixed to show the same behaviour as the Vaadin app in  #9475.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(edcc878).
