### ISSUE TITLE
Remove the PERSON_CONTACT_DETAILS_DELETE user right

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9287]
### Bug Description
Various roles can delete contact details, although it is forbidden according to the permissions table.

additionally: deletion does not happen in the table itself but requires saving of the overall person form. Since the deletion of respective entries needs to be confirmed in a separate window, it should also take place upon confirmation.

### Steps to Reproduce
Open a Case -> Case Person -> Contact information
create or open an entry

### Expected Behavior
Remove the `PERSON_CONTACT_DETAILS_DELETE` user right.

### Screenshots
![image](https://user-images.githubusercontent.com/101708230/169545724-1aed5f20-1142-47f1-bc2b-eee3c2eaacf0.png)

### System Details

* Device:  Laptop
* SORMAS version: 1.71.0
* Android version/Browser: Chrome
* Server URL: https://release-international.sormas.netzlink.com/sormas-ui/login
* User Role: Contact Supervisor, Surveillance Supervisor, Surveillance Officer

**Comment by MateStrysewske** [comment]
@KernB I think the user right that you're referring to is actually redundant and should be removed. I don't see a reason to prohibit users from deleting person contact details. @kwa20 @JaquM-HZI How do you see this?

Concerning the other point you've raised - there's no easy way to save this information separately from the rest of the person form - if something like that is desired, that would require a separate change request.

**Comment by adinaflorea9** [comment]
https://github.com/hzi-braunschweig/SORMAS-Project/issues/7855 @MateStrysewske a similar ticket was logged by me earlier this year; should I discard it?

**Comment by MateStrysewske** [comment]
@adinaflorea9 No, we'll close this one :)
