### ISSUE TITLE
DEMIS and Infra sync dates are mixed up

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#9304]
### Bug Description

For synchronizing lab messages and  infrastructure data, we rely on the  `SystemEventFacadeEjb`. However, `getLatestSuccessByType` does ignore the type which causes the query to return an arbitrarily typed sync event, causing lab message and infra sync to clash.

### Steps to Reproduce

Checkout the current S2S Testbed and test DEMIS sync with `sormas_b`

### Expected Behavior

`getLatestSuccessByType` honers the type of the system event in the query.

**Comment by JonasCir** [comment]
I'll have a PR up shortly...

**Comment by StefanKock** [comment]
@JonasCir could you please look for the causing ticket so that we also knows which versions are affected?

**Comment by JonasCir** [comment]
@StefanKock See screenshot
![git-blame](https://user-images.githubusercontent.com/20031875/170003037-65cbffa5-8059-4d1f-b406-a31d34574b0a.png)

It's been a while...

**Comment by JonasCir** [comment]
`Sprint 98 - 1.54.0` was the milestone for #3927
