### ISSUE TITLE
Automatic scheduled deletion is not displayed for manually deleted entities

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9305]
### Bug Description

When entities are manually deleted, the scheduled deletion with the manual deletion as its reference is supposed to be displayed in the deleted entity as specified in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8162#issuecomment-1092594143. However, this information is not displayed.
### Steps to Reproduce

1. Configure automatic deletion for manual deletion (e.g. for cases like [deletion_configurations.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8754704/deletion_configurations.csv))
2. Create a new case and copy its URL
3. Delete the case
4. Open the deleted case via its URL and check the bottom of the page for the display of the scheduled deletion
5. Check for other core entities

### Expected Behavior

The scheduled deletion should be displayed for manually deleted entities.

### Screenshots

<img width="400" alt="manualDeletionDisplayMissing" src="https://user-images.githubusercontent.com/70317594/169825985-acb56c02-594f-48e2-b0ad-88050db83d01.PNG">

### System Details

* Device:
* SORMAS version: 1.73.0-SNAPSHOT (ec47690)
* Android version/Browser: chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: admin, national user

**Comment by kwa20** [comment]
@roxanamlendea I only configured 

|entitytype|deletionreference|deletionperiod|
|:-|:-|:-
|CASE|MANUAL_DELETION|90|

Do you maybe have other references configured that lead to this display?

**Comment by roxanamlendea** [comment]
I also have configured:

<html>
<body>


entitytype | deletionreference | deletionperiod
-- | -- | --
CASE | CREATION | 365


</body>
</html>


![image](https://user-images.githubusercontent.com/89522688/170007850-ef0e7886-64fc-4456-9b9a-e98388d53447.png)

**Comment by dinua** [comment]
@kwa20 can you please give us more details how to reproduce this bug ? Everything seems to work properly , and the info text is displayed

**Comment by kwa20** [comment]
@dinua To reproduce this problem you need to make sure that only the `MANUAL_DELETION` is configured but not any other deletion references. In the attached csv file in the original description you can see an example of how I configured the entire deletionconfiguration table

**Comment by StefanKock** [comment]
@markusmann-vg will clarify the removal of milestone with @kwa20
