### ISSUE TITLE
No such table:  diseaseClassificationCriteria

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#931]
> DaoException  - Root cause: android.database.sqlite.SQLiteException: no such table:  diseaseClassificationCriteria (code 1): , while compiling: SELECT  MAX(changeDate) FROM diseaseClassificationCriteria - Stack trace:  de.symeda.sormas.app.backend.common.AdoDtoHelper:pullEntities:104 ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:pullInfrastructure:271  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:111  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:153  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:153  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:440  -> android.os.AsyncTask$2:call:304 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:243 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->

This goes back to a bug introduced after version 1.7.0. See d354df63a7c9e578f30158a4232b5ac92edce9fb

**Comment by MartinWahnschaffeSymeda** [comment]
Best guess:

- [ ] drop diseaseclassification and diseaseClassificationCriteria and create a new diseaseClassificationCriteria table (make sure to include the lastOpenedDate column)
- [ ] collect usernames of all affected users from analytics

**Comment by MateStrysewskeSym** [comment]
Affected users:

Q6TKYT-6W22FE-ZBYU22-SQH52I7A
QGIFEU-O6TW2N-AIYUTB-O3AFSOOQ
QMVYPM-P3JYTT-Q4BHNA-FMZMSOK4
QWSFV5-CCRBAL-UNA6SY-DGMF2BG4
R2L3J7-R4WUMW-ZBMPHJ-EYAS2GT4
RM3WVX-2QPCH6-7DMFH7-IKUX2JI4
RNIHZA-7O7FRN-XHJ4E5-DSIFKKMU
TNZC2A-NF7KMG-6OZ6LW-XKTFKL44
TOAHLW-6A2KH3-QTQ4OM-RWKHKP64
TXPFGO-HYVG3D-S3HL7Z-DXWISCVI
U22OLN-U3FKIM-KU54WX-TM53CC2A
VABT62-CDVOGC-P2J3AK-7F542AXI
VSVHGJ-R6IJIU-QM5G4N-YYKJ2PHM
W5HMX2-QTBYLP-GZIGE6-5UP6KI2Y
WADKZB-EBPNQ5-Q3KMJM-WTORKAOE
WHHKMZ-U36ZIK-KWEQLE-7RWY2AJI
XDBFRI-OBSTUX-HBSFYX-RLZ4KEDE
XTG5XX-BVLPQJ-VJ3VMB-4ZTE2ECQ
XUPAKB-KNKD24-2TJLSX-72V72DHY

**Comment by MartinWahnschaffeSymeda** [comment]
See #939
