### ISSUE TITLE
Case management variables for Lassa fever- Patient management interface

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#932]
[Case Management Variables for SORMAS_14-Jan-2019-vFinal.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2779420/Case.Management.Variables.for.SORMAS_14-Jan-2019-vFinal.docx)
@MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
See #936 #937 #938
