### ISSUE TITLE
Cannot change language 

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#9322]
### Bug Description

User cannot change language
### Steps to Reproduce

1. Log in with any user
2. Change language

### Expected Behavior

You should be able to change language
### Screenshots

![image](https://user-images.githubusercontent.com/83635257/170047358-db0aa7e1-aca4-4d28-a72c-608007a23d81.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.73.0-SNAPSHOT (3721438)
* Android version/Browser: Chrome
* Server URL: localhost
* User Role: any

### Additional Information

[languagechangelog.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8763003/languagechangelog.txt)

**Comment by MateStrysewske** [comment]
Very very likely the same problem as in #9319 - I suspect that we run into this problem whenever a user tries to update themselves.
