### ISSUE TITLE
[Angular] Persons: Basic, Detail and custom export [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9331]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference 1: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/52YyZ2w
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/m1Ox22g
- Reference 3: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/DP0WOOJ
- Reference 4: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/7399F0EC-2476-4ED9-891A-FBA1E8ACBBA6
- We will implement all three exports  

### QA Section

1. What should the QA look for (what was done)
- Check that the same texts are used as per the current Sormas implementation. 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - all good
