### ISSUE TITLE
[Angular] Cases: Line listing import [ 2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9333]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/R1dyvke#Version
- As per the other imports (similar to how the exports have been created), we will need the "Import" button to be a dropdown, with the following options: "Detailed import", "Line listing import"
- We need to consult @marius2301 before starting this task as we need to understand if the import functionality works similar to what we have for the export.

### QA Section

1. What should the QA look for (what was done)
- Check that the form is similar to what we currently have on the Sormas implementation
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/Ux review done - everything looks good
