### ISSUE TITLE
[Angular] Case: "Info" section for COVID [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9335]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/eK8Vxma#Version
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/wLvPRVj#Version
- We need to talk with @marius2301 and see if somehow we receive the info from the backend or if it is static
- Note: We will hardcode the text and design for now only for the COVID disease.

### QA Section

1. What should the QA look for (what was done)
- Check that the texts are the same as per the current Sormas implementation
- Check that the implementation is similar to the provided design.

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good
