### ISSUE TITLE
[Angular] Case: "Calculate Case Classification" [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9336]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/wLvPRVj#Version
- We need add the button that will automatically set the case classification
- We need to discuss with @marius2301 if the backend call already exists or if it needs to be created
- We need to change the "Classification" filed from radio buttons to a dropdown

### QA Section

1. What should the QA look for (what was done)
- Check that we have the button
- Check that the radio buttons are now options in a drop-down

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done
