### ISSUE TITLE
[Angular] Cases: Previous hospitalisation cards [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9337]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/dlDa3Pm#Version
- Referenece2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/OmOEwpm#Version

### QA Section

1. What should the QA look for (what was done)
- Check that the cards look as per the design
2. What can the QA ignore (what was omitted)
- Ignore the "+" and the associated functionality (add previous hospitalisation)
- Ignore the "edit" functionality (only the icon will show with no additional functionality attached).

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good!

**Comment by RobertoDascalu** [comment]
Testing done - all good
