### ISSUE TITLE
[Angular] Cases: Follow-up: Add new visit [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9338]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/09xAZQV#Version
- Reference 2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/E088364C-5030-483F-BBD6-B500F41FF9F6#Version
- We will implement the form with the current fields and options as per the current Sormas implementation

### QA Section

1. What should the QA look for (what was done)
- Check that the fields are the same as per the current implementation
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done
-availability-should be mandatory
-date&time-shoulld be mandatory
-clear all clears availability as well
-other complications field appears on "other" section

**Comment by RobertoDascalu** [comment]
Testing done - all good
