### ISSUE TITLE
[Angular] Cases: Add new Clinical Course [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9339]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/p/1D09B516-D195-4B64-BBE3-98B59BB56E02#Version

### QA Section

1. What should the QA look for (what was done)
- Check that we have the same fields as per the current Sormas implementation
- Check that we followed the design

2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by cristinacoza** [comment]
UI/UX review done - everything looks good

**Comment by RobertoDascalu** [comment]
Testing done - all good
