### ISSUE TITLE
Introduce additional Case and Hospitalization fields [1]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#935]
Add additional fields to Case:
- [x] "Sequelae/No sequelae" - either as dropdown or checkbox, only visible when Outcome is "Recovered"; Choosing "Sequelae" will show a "Specify" text field
- [x] ~~"Comorbidities" - text field, visible for all outcomes except "No Outcome"~~

Add additional fields to Hospitalization:
- [x] "Type of bed patient has been admitted to", possible values "Ward" and "ICU"
- [x] Checkbox "Left against medical advice" next to discharge date

Needs to be added in app and web ui.

**Comment by MartinWahnschaffeSymeda** [comment]
From #940 

- [ ] Education: Nursery, Primary, Secondary, Tertiary, Others (please specify).
- [ ] Age: add days as unit type
- [ ] add date field "Date of age entry"

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] app is missing

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] sequalae caption
- [ ] age unit is not automatically updated

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] limit max age reference date to death date
