### ISSUE TITLE
Admin Surveillance Supervisor and Surveillance Supervisor can not be assigned as CASE_RESPONSIBLE

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9350]
### Bug Description

Admin Surveillance Supervisor has the CASE_RESPONSIBLE user right = Yes; however, they can not assign themselves or be assigned by other users as 'Responsible Surveillance Officer'.

The Admin Surveillance Supervisor can only be automatically assigned by the system when they create a new case, but if the 'Responsible Surveillance Officer' dropdown is opened and another selection is made, the Admin Surveillance Supervisor is no longer selectable as responsible for the case.

### Steps to Reproduce

I:
1. Log in with an Admin and create a case;
2. Observe the 'Responsible Surveillance Officer' field and its dropdown.
->**Actual Behavior:** The Admin Surveillance Supervisor is not visible in the dropdown.

II:
1. Log in with an Admin Surveillance Supervisor and create a case;
2. Observe the 'Responsible Surveillance Officer' field and its dropdown.
->**Actual behavior:** The Admin Surveillance Supervisor is listed in the field 'Responsible Surveillance Officer'; if the dropdown is opened, or another selection is made, the Admin Surveillance Supervisor is not visible in the list.

### Expected Behavior

The Admin Surveillance Supervisor can be selected as the 'Responsible Surveillance Officer' for cases that are within their jurisdiction.

### System Details

* Device: Windows 10
* SORMAS version: 1.73.0-SNAPSHOT(7bff1b7) and 1.72.1.
* Android version/Browser: Chrome
* Server URL: local machine and release-international.sormas.netzlink.com
* User Role: Admin Surveillance Supervisor

### Additional Information

Reproducible for Surveillance Supervisor as well.

**Comment by roxanamlendea** [comment]
I'm reopening the ticket because now the Admin Surveillance Supervisor and Surveillance Supervisor are visible in the dropdown, but when the user makes the selection and then saves the page, the selection is not displayed in the UI.
![responsible officer](https://user-images.githubusercontent.com/89522688/176371090-1dceee67-da14-4d98-83ab-2707c902fd57.gif)

**Comment by dinua** [comment]
the users with region jurisdiction such as "Admin Surveillance Supervisor" and "Surveillance Supervisor" should also be possible to be selected as Responsible Surveillance Officer regardless of the settings configuration in database

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.74.0-SNAPSHOT (fdc98e9) from the development branch.
