### ISSUE TITLE
MInimum requirement for persons/push

### ISSUE THREAD

**Issue by ditaoctavia** [hzi-braunschweig/SORMAS-Project#9357]
Hi,

I have setup SORMAS on the company server, for testing purposes. I have been testing it with 1.68.3 up until last Thursday (26 May 2022), and it was all working fine. But ever since I updated to 1.71.0, I have an issue with persons/push, which always resulted in 200 OK, with "ERROR".

Below is my JSON script example, that was working for 1.68.3:
```
[
    {
        "creationDate": "2021-11-01T07:42:19+00:00",
        "changeDate": "2021-11-01T07:42:19+00:00",
        "uuid": "b318eeed-9ef4-4a73-a335-e51259c91b86",
        "pseudonymized": false,
        "firstName": "Alpha_2",
        "lastName": "Octavia",
        "sex": "FEMALE",
        "birthdateDD": 23,
        "birthdateMM": 9,
        "birthdateYYYY": 1967,
        "address": {
            "uuid": "dc2ba104-9334-4980-b6ba-da69ed2fb36f",
            "pseudonymized": false,
            "addressType": "HOME",
            "street": "Gassackerweg",
            "houseNumber": "4a",
            "postalCode": "2545",
            "city": "Solothurn",
            "region": {
                "uuid": "UMP5AO-JUS4ZM-ILUUZ4-5BYQSNBU"
            },
            "district": {
                "uuid": "RHWK6S-7YSJ27-SIZGJK-NGD7CO2A"
            },
            "facilityType": "ASSOCIATION",
            "contactPersonEmail": "joe.yee@cumuluspro.com",
            "contactPersonPhone": "123456789"
        },
        "addresses": [
            {
                "uuid": "5fb18476-3500-4161-bf42-9d93961eeef3",
                "pseudonymized": false,
                "addressType": "PLACE_OF_WORK",
                "street": "Gassackerweg",
                "houseNumber": "4a",
                "postalCode": "2545",
                "city": "Solothurn",
                "details": "Office",
                "facilityType": "BUSINESS",
                "region": {
                    "uuid": "UMP5AO-JUS4ZM-ILUUZ4-5BYQSNBU"
                },
                "district": {
                    "uuid": "RHWK6S-7YSJ27-SIZGJK-NGD7CO2A"
                }
            },
            {
                "pseudonymized": false,
                "addressType": "PLACE_OF_ISOLATION",
                "facilityType": "OTHER_RESIDENCE",
                "region": {
                    "uuid": "UMP5AO-JUS4ZM-ILUUZ4-5BYQSNBU"
                },
                "district": {
                    "uuid": "RHWK6S-7YSJ27-SIZGJK-NGD7CO2A"
                }
            }
        ],
        "personContactDetails": [
            {
                "uuid": "dc2ba104-9334-4980-b6ba-da69ed2fb36f",
                "pseudonymized": false,
                "primaryContact": true,
                "personContactDetailType": "PHONE",
                "phoneNumberType": "MOBILE",
                "contactInformation": "123456789"
            },
            {
                "uuid": "5fb18476-3500-4161-bf42-9d93961eeef3",
                "pseudonymized": false,
                "primaryContact": true,
                "personContactDetailType": "EMAIL",
                "contactInformation": "dita@cumuluspro.com"
            }
        ]
    }
]
```

And I have been stripping it down, for example removing addresses, personContactDetails, etc. Nothing seems to work. For the Region and District UUID I have double checked that I am using the correct UUIDs. Am I missing something on the script? What is the common issue of 200 OK Error?

**Comment by MateStrysewske** [comment]
@ditaoctavia My first guess would be that there's the UUID missing for the second element in the addresses array. Can you add one there and check whether it works?

**Comment by ditaoctavia** [comment]
@MateStrysewske it doesn't work. I already tried to remove that second element too, and even tried to remove the whole addresses array, both doesn't work.

**Comment by ditaoctavia** [comment]
@MateStrysewske we figured out the issue. Its the user right, we need to add "National User".

**Comment by ditaoctavia** [comment]
On this note, which user rights should i turn on, to do:
1. persons/push
2. cases/push
3. contacts/push
4. immunizations/push

I manage to push Person by turning on "National User" and "Rest API". But, then i was stuck with same 200OK Error, when I continued with push Case. Is there any documentation I can read on this?

**Comment by MateStrysewske** [comment]
@ditaoctavia National User should definitely suffice for this, combined with any user role that can use the ReST API (such as the ReST user). The only documentation I can refer to is the user rights document that lists which users have which permissions (you'll see there that the ReST user alone for example doesn't have the rights to create any data in the system). If cases/push doesn't work with a combination of National User and ReST User, I suspect that there's a different problem there.

**Comment by ditaoctavia** [comment]
Hi @MateStrysewske, I found the issue that a new field "HealthConditions" is a requirement in this version. I will close this issue, thank you.
