### ISSUE TITLE
Admin, National Clinician - Port Health Tab missing - The tab is missing when admin creates a case with origin as point of entry

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#9360]
### Bug Description
The tab Port Health is missing when Admin, National Clinician creates a Case with origin as point of entry

### Steps to Reproduce
1. As user having the assigned role only Admin or National Clinician, create a Case with origin: Point of entry
2. Complete only the mandatory fields
3. Save the new Case
4. Look for the Port Health tab

### Actual Behavior
Admin cannot see the Port health tab in the Case edit form

### Expected Behavior
Admin, National Clinician has the right to View and Edit Port health and should be able to see the Port Health tab in the Case edit form
PORT_HEALTH_INFO_VIEW = Yes
PORT_HEALTH_INFO_EDIT = Yes

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser:
* Server URL:
* User Role:

**Comment by roxanamlendea** [comment]
This is also reproducible in the following scenario:

1. Log in with a Region Observer;
2. Navigate to the Cases Directory and select 'Point of Entry' in the 'Case Origin' filter;
3. Open one of the resulting Cases and inspect the tabs;

**Comment by abrudanancuta** [comment]
Port Health is also not visible for National Observer. If the case has the origin as Point of entry, then the Port Health tab is missing

**Comment by MateStrysewske** [comment]
@dinua I guess that means that in order to determine whether the tab shows up or not, IF the value in the pointOfEntry field is null, we have to do an additional database query to check whether this is a port health case or not. If the pointOfEntry field is filled in the first place, we of course don't need that query. Whether or not the tab shows up or not should then depend on the result of these two operations.

**Comment by StefanKock** [comment]
Too many open questions concerning pseudonymisation, cannot be fixed today for 1.78.0

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(36dfdcd).
