### ISSUE TITLE
Add clinical course to case [5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Project#938]
This still needs to be properly specified.

- Add missing "Signs" for Lassa Fever, probably merge them with existing Symptoms (verify this!)
- Introduce "Comorbid conditions", only visible for case management -> #952 
- Probably introduce a list of in-hospital visits that basically work like follow-up visits and allow clinicians to create these, allowing users to view a history of symptoms
- Make sure that the initial symptoms are always displayed in the list so the user can easily switch between the most recent and the initial symptoms
- Introduce additional fields that allow the surveillance of the patient's health, e.g. heart rate, blood pressure, etc. (these need to be defined)

Later:

- Add visualizations to display this information over time to the user in a fancy way

Idea to address the space problem in symptoms form: Maybe introduce a "Only show present symptoms and signs" checkbox that by default hides every symptom and sign that is not set to "Yes"

**Comment by MateStrysewskeSym** [comment]
First mockup draft: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a975cc6bf

**Comment by MartinWahnschaffeSymeda** [comment]
Meeting notes:

* Keep case symptoms
* Add clinical course where you can add clinical visits
* Clinical visits also use temperature, blood pressure, heart rate
* After saving a visit the case symptoms are updated. This is done by adding new symptoms and increasing the temperature to the max value
* Comorbid conditions -> "Other health conditions". Probably below the clinical course. Also list pregnancy

**Comment by MateStrysewskeSym** [comment]
New mockups:

https://app.moqups.com/symeda/3NUENEwuOE/view/page/a975cc6bf
https://app.moqups.com/symeda/3NUENEwuOE/view/page/ac39b986b

**Comment by MartinWahnschaffeSymeda** [comment]
* create an issue to create initial symptoms when investigation is done

**Comment by MartinWahnschaffeSymeda** [comment]
### Backend

- [ ] Add entities for clinical course and visits. Visit has a symptoms entity and additionally visitDateTime, visitRemarks
- [ ] Extend symptoms with heart rate and blood pressure. 
- [ ] Extend symptoms with missing signs (see form)
- [ ] Make sure new fields aren't overriden with null values from old app data
- [ ] Enable missing fields for Lassa
- [ ] After saving a visit the case symptoms are updated. This is done by adding new symptoms and increasing the temperature to the max value

### UI

- [ ] Add clinical course view
- [ ] Add grid for clinical visits
- [ ] Add form for clinical visit. Use symptoms form with all fields required (see contact visits)
- [ ] Show heart rate and blood pressure only for clinical visits
- [ ] In symptoms main form rename "Current body temperature" to "Maximum body temperature"
- [ ] Description of symptoms needs to be updated (during this illness)

### Questions

* should the clinical visit have a user or a text field "visiting staff member"

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
Should the clinical visit have a an automatically filled user or a drop down or a text field "visiting clinician"? The prupose of this would be to know who did the clinical visit. Is this going to be the same user that also documents the clinical visit in SORMAS?

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig
Any update on the question above?

Also, can you please go through the following list, check whether we already have any of these symptoms/signs in the system under a different name (or whether we have a similar symptom that might render one of those listed here obsolete) and comment here with your result as soon as possible?

- Pharyngeal erythema
- Pharyngeal exudate
- Oedema of face/neck
- Loss of skin turgor
- Palpable liver
- Palpable spleen
- Enlarged lymph nodes
- Lower extremity oedema

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig 
Additional question: Are onset date and onset symptom of any necessity for clinical visits? Since clinical visits are more about tracking the current health state of the patient, I'd believe we could take them out there.

**Comment by MartinWahnschaffeSymeda** [comment]
Use a textfield "visiting clinician"

**Comment by MateStrysewskeSym** [comment]
- [ ] Remove clinical visits from ClinicalCourseDto
- [ ] Add clinical visits as list to ClinicalCourseDto and ClinicalCourse
- [ ] Adjust methods in FacadeEjb accordingly
- [ ] Do the same for Therapy

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig @dta16 
Concerning user rights: Chinedu wrote in his e-mail that National Users and Surveillance Supervisors should have read access to the Case Management components. Are you sure about this? From my point of view, Surveillance Supervisors are not associated with the internal processes in a hospital at all and, concerning data privacy, should probably not even be able to see this data. Same potentially goes for National Users and Observers since those are meant to exclusively observe/oversee the Case Surveillance process if I'm not mistaken.

What's your take on this matter?

**Comment by hzi-braunschweig** [comment]
You are absolutely right. Please do not give them user access at all to it except the case supervisor and case officer. In reality, if a particular surveillance supervisor is also a clinician, then we would assign that role to him as well.

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add unit test for SymptomsHelper.updateSymptoms
- [ ] CaseController: Save case instead of therapy. Remove save method from ClinicalCourseFacade
