### ISSUE TITLE
'Place of Stay' shouldn't be mandatory in the Case Creation form for the POE NatUser

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9382]
### Bug Description
The 'Place of Stay' field is mandatory in the Case Creation form for the POE National User, even though it shouldn't be.
For other users, this section is not mandatory.

### Steps to Reproduce

1. Log in with POE National User.
2. Navigate to the Cases Directory and click on the 'New Case' button.
3. Inspect the 'Place of Stay' section.

### Expected Behavior
The 'Place of Stay' field shouldn't be mandatory.

### Screenshots
POE NatUser
![image](https://user-images.githubusercontent.com/89522688/171396143-8e08108d-527d-41c5-9bbf-d5b471123fc2.png)

Other users (eg. NatUser, Admin etc.)
![image](https://user-images.githubusercontent.com/89522688/171395993-5a27b2d5-33b6-4993-b6c9-670c53c66bae.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.72.1
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and local machine
* User Role: POE National User

### Additional Information

The user role dependent behaviour is defined here: `CaseCreateForm:391ff` It's mostly dependent on the user not to be a "portHealth" user and `CaseOrigin.IN_COUNTRY`.

**Comment by syntakker** [comment]
Please check if this behaviour is consistent with issue #9445.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.74.0-SNAPSHOT (7e4e9eb) from the development branch.
