### ISSUE TITLE
Areas are not synchronized properly after enabling the feature configuration

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9385]
### Bug Description

Information from the 'Campaign data form' is not synced from the vaadin-app to the android-app and a Surveillance Officer can not save changes on the 'Campaign data form' as a result.

### Steps to Reproduce

1. In the vaadin-app, logged in with an Admin+NatUser, create a campaign with a 'Campaign data form'; 
2. In the mobile app, logged in with a Surveillance Officer, trigger an synchronization with the server;
3. Navigate to the 'Campaigns' directory and open the campaign data from from step 1; 
4. Observe the fields 'Area', 'Region', 'District', and 'Community';
=> Actual behavior: the field 'Area' is empty;
5. Click to edit the campaign data form;
6. Observe the same fields from step 4;
7. Click to add a community or edit any other information on the form, and click save.
=> Actual behavior:  the fields 'Area', 'Region', 'District', and 'Community' are empty; 'Community' field is editable but there are no communities displayed in the dropdown.

### Expected Behavior

The information from the fields 'Area', 'Region', 'District' and 'Community' that was inputted in the vaadin-app is also displayed in the android-app after the synchronization with the server, both when the user only reads the form and when they try to edit it.

### Screenshots

Campaign data form in the vaadin-app:
![image](https://user-images.githubusercontent.com/96909231/171402661-bcece0cb-93d8-43ec-86e2-ffa15f64e229.png)

Campaign data form in the android-app:
- when the user only reads the form:
![image](https://user-images.githubusercontent.com/96909231/171402736-92a1f3d2-c81c-4f23-a515-11313bd99601.png)

-when the user clicks to edit the form:
![image](https://user-images.githubusercontent.com/96909231/171402832-31304bf0-74c0-4e96-bc8b-baadf8dc2a5a.png)

![image](https://user-images.githubusercontent.com/96909231/171402854-cf02fa36-03d8-4e58-a07a-5b9e6d79dfd9.png)

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(8dc17df)
* Android version/Browser: Chrome (vaadin-app); Android 11 (android-app)
* Server URL: local machine
* User Role: Admin+NatUser (vaadin-app); Surveillance Officer (android app)

### Additional Information

Note: the Surveillance Officer is not affected by the behavior reported in comment: https://github.com/hzi-braunschweig/SORMAS-Project/issues/4461#issuecomment-1141027558

**Comment by MateStrysewske** [comment]
@adinaflorea9 The issue here is not with campaing form data, but with areas not being properly synced during the first synchronisation after enabling the INFRASTRUCTURE_TYPE_AREAS feature configuration. This leads to regions not having their areas connected to them, which then in turn leads to these errors you were facing.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(d312652).
