### ISSUE TITLE
[User Rights] POE National User gets and error message when he downloads Sample Export from the Cases Directory

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9386]
### Bug Description
When the POE National user tries to download the Sample Export table from the Cases Directory, he gets an error message. 
Possibly because he doesn't have a Sample Directory and Sample related user rights.

Stacktrace: 
[stacktrace sample export.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8814103/stacktrace.sample.export.txt)

### Steps to Reproduce

1. Log in with a POE National User.
2. Navigate to the Cases Directory and download the 'Sample Export' table.

### Actual Behavior
The user gets an error message.

### Expected Behaviour
The Export button should not be visible in the first place for users that don't have Sample view rights.

### Screenshots
![sample export POE NAT USER](https://user-images.githubusercontent.com/89522688/171405175-de86ff6d-05ee-443d-a0ae-eacaae26be0f.gif)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.72.1
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and local machine
* User Role: POE National User

**Comment by cazacmarin** [comment]
@roxanamlendea - can you please provide `Expected Behavior` for this ticket? Thanks!

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.73.0-SNAPSHOT (3d0fd59)
