### ISSUE TITLE
[DEMIS2SORMAS] Save and open case button redirects to the messages directory from existing samples

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9394]
### Bug Description

When selecting an existing sample after selecting an existing person and contacts or event participants, the sample edit form shows the button "Save and open case". 

In all scenarios, including selected existing cases, the button redirects to the message list instead of the respective entity. This does not happen if e.g. a new sample is created.
### Steps to Reproduce

1. Process initial lab messages for case, contact and event participant
2. Process another lab message for the same person and select the existing case/contact/event participant respectively
3. Select the previously created sample
4. Check the "Save and open *" button at the bottom of the form

### Expected Behavior

- The button should be named "Save and open contact" for contacts and "Save open event participant" for event participants.
- No matter where, the button should open the respective associated entity

### Screenshots

![saveAndOpenCase](https://user-images.githubusercontent.com/70317594/171452725-79b45b20-6683-45fe-bc97-a6afceeda90f.gif)

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.74.0-SNAPSHOT (b11af09)
