### ISSUE TITLE
Addtional fields for case export (needed for Lassa) [2]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#940]
[Lassa fever SORMAS Sections B and D - Surveillance.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/2792133/Lassa.fever.SORMAS.Sections.B.and.D.-.Surveillance.xlsx)

Detailed export for Lassa fever should contain the variables in the attached form.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Please can you give details on why each column is needed and how it's going to be used? Ideally with an example of a user and how he would use it.

**Comment by Chinedar** [comment]
Each column is needed because the Director General of the NCDC has mandated that the table of export come out this way (and variables on the table that we do not have in SORMAS, should be added e.g **serial number** of each case as it comes into the system).

The columns in yellow will come from the case management section just recently being added. 

An example of a user would be the national user within the NCDC data management team who will need the table for analysis or reporting outside SORMAS.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar @hzi-braunschweig 

I went through all the fields and grouped them into the following three sections. Please look at section I and II and make sure this is correct. 
Then answer the questions of section III.

## I. Fields that are already part of the export and don't need to be changed

* SN: We don't have a serial number in SORMAS. Instead we export the UUID
* epid number
* Disease or Condition
* Health Facility (State), Health Facility (LGA), Health Facility (Ward),Health Facility (Name of Facility)
* Date onset of disease
* Date seen at health facility
* Out-patient OR In-patient -> "Was patient admitted at the health facility as an inpatient?"
* Surname, Other Names -> Full name
* Sex
* Phone Number, Owner of Phone Number
* Outcome
* History of travel in the past 3 weeks (Yes/No), If YES, where (Describe in details)? -> "Travel history" is either empty or has the needed details
* Direct contact (hunt, touch, eat) with rodent or rodent feces/urine (Yes/No/Unknown)-> "Contact with rodent?"

## II. Fields that need to be added

- [ ] Date of birth: At least the parts that are available (e.g. only year)
- [ ] Occupation should not be exported as "null"
- [ ] Case  Management Discharge Details (Discharged/Transferred/DAMA/Death)
- [ ] Date of discharge details
- [ ] Did the patient participate in burial (carry or touch corpse) in the last 3 weeks before sickness? (Yes/No) 

## III. Unclear fields

- [ ] Age (years), Age (months), Age (days): We only have one age column that will either have the age in years (eg. "27") or months (e.g "3 Months"). Is there a need to change that? If so, can you give a use case where the age in days would be used?
- [ ] Address of Residence (State), Address of Residence (LGA), Address of Residence (Ward), Address of Residence (Settlement/Village/Town), Address of Residence (Street Name): This is currently exported in a single column. Is that ok?
- [ ] Education: We don't have that information in SORMAS. Should this be added? If so, who will enter this information? Should this be text or a set of values?
- [ ] Mode of Burial (Safe or Unsafe): What does safe or unsafe mean? I think we need a more precise definition here, so users know what to enter
- [ ] Case  Management Discharge Details (Discharged/Transferred/DAMA/Death), Date of Discharge Details: I'm not sure how this should be filled based on the existing fields. In addition I don't see how this maps to the new fields (see #935)
- [ ] Is the case from probable case contact tracing list (Yes/No/Not Applicable): Does this mean the case is created for a person that had contact for another probable case? When is this not applicable? In the epi data section we do have the question "Direct contact with a probable or confirmed case?" - should this also be exported?
- [ ] Had contact with a known or suspect Lassa fever case: What does "known" mean?
- [ ] Has a contact tracing list been opened for the case? (Yes/No): There is no direct question for this in SORMAS. How should be determine it? It could be yes, when at least one contact was created for the case

**Comment by Chinedar** [comment]
- SN: We don't have a serial number in SORMAS. Instead we export the UUID - _can we add this into the system for ease of analysis? Let every case (disease specific) assume a serial number based on order of entry via date of report._ 

- Age (years), Age (months), Age (days): We only have one age column that will either have the age in years (eg. "27") or months (e.g "3 Months"). Is there a need to change that? If so, can you give a use case where the age in days would be used? - _The data team has requested that they have "days" added for children less than 1 month._ 

- Address of Residence (State), Address of Residence (LGA), Address of Residence (Ward), Address of Residence (Settlement/Village/Town), Address of Residence (Street Name): This is currently exported in a single column. Is that ok? - _This is fine._

-  Education: We don't have that information in SORMAS. Should this be added? If so, who will enter this information? Should this be text or a set of values? - _Yes, this should be added. This can be entered by Informant, Surveillance Officer and Contact Officer. Let's have the following values (Nursery, Primary, Secondary, Tertiary, Others (please specify)._ 

- Mode of Burial (Safe or Unsafe): What does safe or unsafe mean? I think we need a more precise definition here, so users know what to enter. - _We can only have this pop up if outcome is dead. Health care workers here understand what is meant by safe or unsafe burial. There are set out procedures for carrying out safe burials of dead lassa fever cases. If the procedures are not followed, then it is tagged as unsafe burial._ 

- Case Management Discharge Details (Discharged/Transferred/DAMA/Death), Date of Discharge Details: I'm not sure how this should be filled based on the existing fields. In addition I don't see how this maps to the new fields (see #935) - _I think we can leave this off for now until we have the case management section fully activated._ 

-  Is the case from probable case contact tracing list (Yes/No/Not Applicable): Does this mean the case is created for a person that had contact for another probable case? When is this not applicable? In the epi data section we do have the question "Direct contact with a probable or confirmed case?" - should this also be exported? - _Please let's export what we have already "Direct contact with a probable or confirmed case?" and ignore the rephrase from them._  

- Had contact with a known or suspect Lassa fever case: What does "known" mean? - _I believe they are referring to "confirmed"._ 

- Has a contact tracing list been opened for the case? (Yes/No): There is no direct question for this in SORMAS. How should be determine it? It could be yes, when at least one contact was created for the case - _Exactly! It should be yes when at least one contact is listed for the case._

Is it possible to have the second sheet "SORMAS Section D - CIF (+ve)" export only for positive cases? 

Thanks thanks thanks!

**Comment by MartinWahnschaffeSymeda** [comment]
Age:

- [ ] update unit of age
- [ ] add days as unit type
- [ ] export case age going down to days
