### ISSUE TITLE
'About' page on test-de3 can not be opened and an error message is displayed

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9425]
### Bug Description

On the testing instance test-de3.sormas.netzlink.com the 'About' page can not be opened as an error message is displayed.

### Steps to Reproduce

1. Log in with any active user on the test instance test-de3.sormas.netzlink.com;
2. Click on the 'About' entry from the list of directories.

### Actual Behavior

An error message is displayed and the user is not redirected to the 'About' page:
![image](https://user-images.githubusercontent.com/96909231/172130861-aa148139-159d-4813-a52c-d4dffa04549c.png)

### Expected Behavior

The user is redirected to the 'About' page.
### System Details

* Device: Windows 10
* SORMAS version: not visible as this is displayed on the 'About' page; 
* Android version/Browser: Chrome
* Server URL: test-de3.sormas.netzlink.com
* User Role: Admin+NatUser, Surveillance Officer

**Comment by MateStrysewske** [comment]
Likely caused by some external system that is not reachable. Should be caught and handled properly.

**Comment by StefanKock** [comment]
Maybe this code snippet is flawed, does not really catch exceptions:
```java
ExternalMessageFacadeEjb

	@Override
	@PermitAll
	public String getExternalMessagesAdapterVersion() throws NamingException {
		ExternalMessageAdapterFacade labResultsFacade = getExternalLabResultsFacade();
		String version = I18nProperties.getCaption(Captions.versionIsMissing);
		try {
			version = labResultsFacade.getVersion();
		} finally {
			return version;
		}
	}
```

I was maybe fixed before but reverted lately?

**Comment by leventegal-she** [comment]
> Maybe this code snippet is flawed, does not really catch exceptions:
> 
> ```java
> ExternalMessageFacadeEjb
> 
> 	@Override
> 	@PermitAll
> 	public String getExternalMessagesAdapterVersion() throws NamingException {
> 		ExternalMessageAdapterFacade labResultsFacade = getExternalLabResultsFacade();
> 		String version = I18nProperties.getCaption(Captions.versionIsMissing);
> 		try {
> 			version = labResultsFacade.getVersion();
> 		} finally {
> 			return version;
> 		}
> 	}
> ```
> 
> I was maybe fixed before but reverted lately?

That code fixes the case when the DEMIS adapter doesn't work. But it's not a good solution because the exception is important for the UI so it could display "service not available" and not a "version is missing" message

The issue right now is that the SurvNet converter is not working.
