### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by hzi-old** [hzi-braunschweig/SORMAS-Project#943]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Good idea from my colleague for gamification, we need to be able to track the time it takes from case creation to when they save it.  We need to discuss if we can use session handlers while they are logged in or per tab when they hit save. 

Please lets add this to the backlog. More lists for gamification later.

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda Not really, there are a combination of parameters which would give the user a high or low score. For instance, someone who gets the second price for typing 200 words in 1 minute with an accuracy of 55% compared to someone with the first position who types 200 words in 1 minute with an accuracy of 95%. The attributable score for the first position is the combination factor of speed and accuracy. So for SORMAS we have completeness, timeliness, data quality parameters to give an overall score on the leaderboard. Just to give you an idea. So we track the time it takes to create a case from first tab to the last tab per disease. We can discuss this later
