### ISSUE TITLE
'New Vaccination' button is visible on the Person page and if it's clicked, an error is displayed

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9464]
### Bug Description
When the Reduced Immunization module is enabled, on the Person page, Vaccinations can only be seen, not created, because a Vaccination is created for an entity's disease. However, on the Person page, the 'New Vaccination' button is displayed.

### Steps to Reproduce

1. Make sure that the Reduced Immunization module is enabled on the instance you're testing on;
2. Open a Case and create a Vaccination;
3. Navigate to the Persons Directory and open the Person entity from step 2;
4. Inspect the Vaccination Card and click on the 'New Vaccination' button;

### Expected Behavior
The 'New Vaccination Button' should not be displayed in the first place;

### Actual Behavior
The 'New Vaccination Button' is displayed and an error message is thrown when the user clicks it.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/173071943-ccb84b41-4a0c-4b12-bb0c-3bf6131a8ebe.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.72.1 and after
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and local machine
* User Role: Admin, NatUser

### Additional Information
Probably related to #9463

**Comment by kwa20** [comment]
@roxanamlendea My bad, didn't read thoroughly enough. Sorry :)

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.74.0-SNAPSHOT (3087773
