### ISSUE TITLE
Deletion period can be below 7 days

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9471]
### Bug Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/7008 specified that the lowest possible deletionperiod should be 7 days. However, setting a deletion period below 7 does not get validated and can be set in the database.
### Steps to Reproduce

1. Configure the deletionperiod to be 6 days for e.g. entitytype = CASE and deletionreference = END
2. Check the deletionconfiguration table or alternatively the UI display of the entity

### Expected Behavior

The deletionperiod should not be able to be configured below 7 days
### Screenshots

<img width="394" alt="deletionDaysValidate" src="https://user-images.githubusercontent.com/70317594/173335352-94ccaa80-894c-4348-83cc-fb2415a9242a.PNG">

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.75.0-SNAPSHOT from the development branch.
