### ISSUE TITLE
[Angular] Entries: Import [2 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9488]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/R1dyvke
- We need to implement the import form (without any actual functionality).

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - all good
