### ISSUE TITLE
[Angular] Contacts: Add right hand side section [5 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9490]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/7y2Vp0p
- Reference2: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/wLvPRVj
- Reference3: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/QbjDJlm
- Reference4: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/OmOEwpm
- We will implement the right hand section in it's entirety (buttons, forms, cards)

### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - all good
