### ISSUE TITLE
[Angular] Contacts: Add new visit [3 + 1]

### ISSUE THREAD

**Issue by laurentiustanvitagroup** [hzi-braunschweig/SORMAS-Project#9493]
### Situation Description

- In view of the future replacement of the current FE with the Angular component, the Angular team will focus on the required changes.

### Feature Description

- Reference: https://www.sketch.com/s/fd061796-65a3-4991-886a-c8a172667c91/a/09xAZQV
- Note: The "First symptom" dropdown needs to be populated with the above selected items (in the order the user selects them).
- Note: This functionality needs to also be implemented in: Symptoms / Follow-up (or anywhere else it might be implemented incompletely).
- Note: On the contact, if we somehow have a flag that determines if the contact has been converted to a case, we need to display an info with the correct text (please check on the Sormas legacy instance) or try this contact: https://ga1.sormas-oegd.de/sormas-ui/#!contacts/visits/UAL56O-AJBA5B-HZNYT4-NPZFSJQE
 
### QA Section

1. What should the QA look for (what was done)
- 
2. What can the QA ignore (what was omitted)
- 

### Possible Alternatives

- N/A

**Comment by RobertoDascalu** [comment]
Testing done - all good
