### ISSUE TITLE
Subcontinent filter leads to internal error when scrolling

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9494]
### Bug Description

When a subcontinent is selected in the country configuration, and the content in the drop-down scrolled, an internal error appears.
### Steps to Reproduce

1. Open the country tab in configurations and select any subcontinent in the filter section
2. Open the drop-down filter and scroll through the values

### Expected Behavior

Scrolling should work without error

### Screenshots

![subcontinentFilter](https://user-images.githubusercontent.com/70317594/173555987-e5bb5dd1-9dc8-4771-b429-d7e2f448a40b.gif)

### System Details

* Device:
* SORMAS version: 1.72.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by dinua** [comment]
can not reproduce it , it works fine be me

**Comment by roxanamlendea** [comment]
It is also reproducible on my machine. 
In order for the bug to be reproduced, the feature configuration EDIT_INFRASTRUCTURE_DATA needs to be set to false.
