### ISSUE TITLE
Monitor performance of automation deletion job for testing environments

### ISSUE THREAD

**Issue by rdutu-vg** [hzi-braunschweig/SORMAS-Project#9509]
Based on the last discussion from performance meetings, we agreed to start using automation deletion job over testing environments and monitor its performance to check if the job has any impact in terms of performance over VM hosting environment.

Activity will be done with Kay Watty and the steps that we need to follow:

- Create backup
- Enable the automatic deletion
- Monitor the process (time & deleted entities)
- Restore

**Comment by rdutu-vg** [comment]
We have a backup and triggered the execution of automatic deletion job.

Machine load was 25% during job execution and it took 15h

![automatic deletion](https://user-images.githubusercontent.com/83643843/174352156-49cf9c40-5ddd-42f7-ba80-020e62167ce5.JPG)

Monday we'll compare the data base with collected one to check the results.

Discussed with Sergiu, and there is no parallel execution so each entity type is taken one by one and deleted. We'll need to compare results and provide a total of deleted to determine the deletion speed (performance).

A risk with this job for testing environments: it might be stopped by automatic deployment job if they overlap.

@markusmann-vg

**Comment by rdutu-vg** [comment]
Update from Kay, this task will be set on hold and will require re-prioritisation.

**Comment by StefanKock** [comment]
Monitoring something is a permanent activity, I therefore dismiss this ticket
