### ISSUE TITLE
[DEMIS2SORMAS] Extend the Person.presentCondition mapping by considering isDead in physician reports

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9511]
### Situation Description

The mapping for the persons present condition was implemented for lab messages via https://github.com/hzi-braunschweig/SORMAS-Project/issues/6692. For physician reports, another attribute is used in the `QuestionnaireResponse` ressource and can be found [here](https://simplifier.net/guide/Implementierungsleitfaden%20f%C3%BCr%20DEMIS%20Arztmeldung/Home/resources/questionnaires/guide-diseasequestionscommon.md?version=current). The attribute is called isDead and holds enum values determined by the code system combination [yesOrNoOrNoInformation](https://simplifier.net/demisarztmeldung/yesornoornoinformation) consisting of the code systems [yesOrNoAnswer](https://simplifier.net/demisarztmeldung/yesornoanswer) and [v3.NullFlavor](https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/83517).
### Feature description

- [ ] For physician reports, map `isDead` to `Person.presentCondition` in the following way

    DEMIS name | DEMIS value | SORMAS value
    -- | -- | --
    Ja | yes | DEAD
    Nein | no | ALIVE
    nicht ermittelbar | ASKU | UNKNOWN
    nicht erhoben | NASK | null
    Kein Bezug zur BW | noReferenceToBundeswehr | NO_RELATION

### Acceptance Criteria

- The present condition is correctly adopted from the content of the physician report

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 The mapping of the Person.presentCondition was implemented for both , lab message and physician's report in #6692 .
Now you propose another mapping for physician's reports. Shall the current mapping for physician's reports not be done anymore? Otherwise, what it case of both values being present? Should one be preferred over the over?

**Comment by kwa20** [comment]
> Hinweis: Im Rahmen der Profilerstellung wurde intensiv diskutiert, ob die Angaben zum Tod der betroffenen Person nicht besser an der NotifiedPerson (Patient-Ressource) selbst dokumentiert werden sollten, zumal dort bereits zum Zeitpunkt der Profilierung der Errergernachweismeldung entsprechende Angaben als 'mustSupport' gekennzeichnet wurden. Folgende Gründe haben im Endeffekt zur Präferierung der hier beschriebenen Abbildung geführt:

> - Die von HL7 FHIR in der Patient-Ressource vorgesehene Darstellung erfolgt entweder über Patient.deceasedBoolean oder Patient.deceasedDateTime. In diesem Modell lassen sich die - bezogen auf ihre Semantik - doch sehr unterschiedlichen NullFlavors 'Nicht erhoben' und 'Nicht ermittelbar' nicht unterscheiden. In den Fachverfahren im Gesundheitsamt wird diese Unterscheidung jedoch vorgenommen und ist u.a. auch für Datenauswertungen von Interesse.

> - Sollen zukünftig konkretisierende Angaben zum Tod der betroffenen Person erhoben werden, wird ein "Ort" benötigt, an dem diese abgebildet werden können. Konkrete Diskussionen wurden hier beispielsweise in Bezug auf folgende weiterführende Frage geführt: "Steht der Tod in einem direkten Zusammenhang mit der gemeldeten Erkrankung?" Eine Bündelung entsprechender Angaben an einer Stelle ist dann entsprechend zielführender.

> Vor dem Hintergrund dieser Diskussion gilt somit die folgende zusätzliche Festlegung: Angaben zum Tod der betroffenen Person sollen ausschließlich über den hier dargestellten Fragebogen bzw. dessen ausgefülltes Pendant erfolgen. Erfolgt aus zwingenden technischen Gründen dennoch eine Darstellung an beiden Stellen, so dürfen sich die Angaben nicht widersprechen. Fachverfahren im Gesundheitsamt müssen die in der QuestionnaireResponse gemachten Angaben in die eigene Datenhaltung übernehmen.

@FredrikSchaeferVitagroup [This](https://simplifier.net/guide/Implementierungsleitfaden%20f%C3%BCr%20DEMIS%20Arztmeldung/Home/resources/questionnaires/guide-diseasequestionscommon.md?version=current) is what I found in the DEMIS documentation. However, it is not clear to me, whether reporters are actually prevented from setting this information in both resources. Honestly, I don't believe that this is actually the case, judging from the previous quality of notifications. Thus, let's handle them in the following way.

- Both options should be considered since they are potentially filled
- If both resources are filled, consider `isDead` over `Patient.deceasedBoolean`

**Comment by FredrikSchaeferVitagroup** [comment]
There is nothing to do for this on SORMAS side, only in the SORMAS-DEMIS adapter. That's why I created [#69](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/69) and will discard this ticket.
