### ISSUE TITLE
Cannot create sample with internal inhouse testing purpose

### ISSUE THREAD

**Issue by richardbartha** [hzi-braunschweig/SORMAS-Project#9517]
### Bug Description

Creating a new sample with internal inhouse purpose is not possible because laboratory field is required.
### Steps to Reproduce

1. Click on creating a sample 
2. Select internal inhouse testing at the purpose of the sample
3. Save the sample

### Expected Behavior

You should be able to save the sample as when the internal/inhouse sample purpose is selected the laboratory field is not required any more. 
### Screenshots

![image](https://user-images.githubusercontent.com/83635257/173831460-99cd0d6a-8051-4891-aef6-5e8a910f9d9b.png)
![image](https://user-images.githubusercontent.com/83635257/173831649-8f7c0599-e4cd-4f47-a924-0fd328ccfbd8.png)

### System Details

* Device: Windows
* SORMAS version: 1.73.0 - SNAPSHOOT
* Android version/Browser: Chrome
* Server URL: test-auto.sormas.netzlink.com
* User Role: NatUser

### Additional Information

This bug does not occur on https://release-de.sormas.netzlink.com with version 1.72.1

**Comment by roxanamlendea** [comment]
This bug is also reproducible on my local machine

**Comment by MateStrysewske** [comment]
Caused by #9276
