### ISSUE TITLE
Case Classification file missing from About section

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9519]
### Bug Description

The Case Classification file is missing from About section
![image](https://user-images.githubusercontent.com/101708230/173856292-45933fbd-e39d-48bb-b5f3-d2491514bb95.png)

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:  1.73.0-SNAPSHOT (962af5e)
* Android version/Browser:
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role:

**Comment by MateStrysewske** [comment]
@KernB I suspect that the automatic case classification feature is turned off on that system. If that's the case, the link to the document is not shown.
