### ISSUE TITLE
"Action last modified by" entries are missing 

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9520]
### Bug Description

At Events - Action Directory the entries in the column ACTION LAST MODIFIED BY are missing. 
![image](https://user-images.githubusercontent.com/101708230/173872842-13c41d17-0e16-46c1-9258-354ffbb9d4d5.png)

 

### Steps to Reproduce

1.
2.

### Expected Behavior

We expect the entries as in SORMAS Version: 1.72.1:
![image](https://user-images.githubusercontent.com/101708230/173872110-592892d7-d973-47d5-9225-7ee1b09585e2.png)

### System Details

* Device:
* SORMAS version:  1.73.0-SNAPSHOT (c0b0648)
* Android version/Browser:
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: admin

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(fdc98e9).

'Action last modified by' column is filled in and updated with the user that last made a change on the respective action:
![image](https://user-images.githubusercontent.com/96909231/178249831-1427444a-38ac-4220-bf03-78f3342834e7.png)
