### ISSUE TITLE
Error message 'Could not communicate with the server' is triggered when trying to do a synchronization in the mobile app with specific users

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9526]
### Bug Description

When trying to do a synchronization of the mobile app with the SORMAS Server, an error message is triggered in the app, and an error is displayed in the logs.

I was only able to reproduce this with the following specific users: Lab Officer, Community Officer, Community Informant and Hospital Informant.

### Steps to Reproduce

1. Log into the mobile app with one of the users mentioned in the bug's description;
2. Trigger a synchronization.

### Actual Behavior

An error message is displayed in the mobile app, and an error is also displayed in the logs.

### Expected Behavior

Synchronization of the mobile app is successful.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/174050148-aefb535c-9550-4c1e-9ad8-2a108f53f328.png)

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(0fc81d1)
* Android version/Browser: Chrome; Android 11
* Server URL: local machine
* User Role: Lab Officer, Community Officer, Community Informant, Hospital Informant

### Additional Information

As discussed with @MateStrysewske, I am logging a separate ticket so that the behavior can be investigated, as this was not reproducible on Mate's machine, only on mine. Behavior was observed while doing regression testing for #4461.

Logs from the local machine:
1. Logs from Android Studio:
[logs Android Studio.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8918019/logs.Android.Studio.txt)

2. Logs from IntelliJ machine:
[logs IntellyJ.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8918021/logs.IntellyJ.txt)

**Comment by MateStrysewske** [comment]
Note: Lab officers aren't supposed to use the mobile app, so we can ignore them.

**Comment by adinaflorea9** [comment]
@MartinWahnschaffe Yes, I am using Docker for the local machine set-up. The android-app URL that I use is the following: http://10.0.2.2:6080/sormas-rest as Android Studio is connected to my local machine.

@AndyBakcsy-she mentioned today that when he was logged in with a Lab Officer, the behavior was reproducible for him as well (although, as Mate mentioned, the Lab Officer is not expected to use the mobile app). 

For me this has been consistently reproducible with the users mentioned in the ticket since June 16th, when I logged the ticket.

**Comment by dinua** [comment]
this bug is no longer reproducible

**Comment by adinaflorea9** [comment]
Tried to reproduce the behavior on the local machine using the latest version of SORMAS from the development branch - 1.77.0-SNAPSHOT(8c31891) - the behavior is no longer reproducible with the users that are supposed to be able to use the mobile app. Therefore, I will discard the ticket.
