### ISSUE TITLE
Contact dashboard takes long to load and may break connection to the server

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#9528]
### Bug Description

The contact dashboard takes a long to load and often breaks the connection to the server when the database has many entities. This can be tested on the performance servers only. We have increased the RAM but this did not help. The code that loads the contact dashboard may have a performance issue.

### Steps to Reproduce

1. Connect to https://test-fr-perf-02.sormas.netzlink.com/sormas-ui/ using google chrome
2. Click on the surveillance dashboard
3. Navigate to the contact dashboard and monitor how long it takes to open, monitor is you get the message "Server connection lost ..."
4. Even though there are just 110 contacts in the current week, the dashboard still takes a long time to load

### Expected Behavior

- There should be no "server connection lost" message when opening the contact dashboard
- Dashboard should load within 5 seconds, just as the surveillance dashboard
### System Details

* Device:
* SORMAS version: 1.70.4
* Android version/Browser:
* Server URL: https://test-fr-perf-02.sormas.netzlink.com/sormas-ui/
* User Role: national user + admin

### Additional Information

The components of the dashboard can be loaded independently, eg first load the info boxes  and indicators, while dashboard in shown to the user, then load the graphs (epi curve) and lastly the map

**Comment by bernardsilenou** [comment]
Netlink would provide logs

**Comment by bernardsilenou** [comment]
@T-Hundt  FYI

**Comment by MateStrysewske** [comment]
Closing this issue in favour of #10381 since it was reported on a newer version, provides logs and reports the same problem.
