### ISSUE TITLE
Strange Refresh @task/comments

### ISSUE THREAD

**Issue by SormasTheGreek** [hzi-braunschweig/SORMAS-Project#9535]
### Bug Description

A strange refresh after editing "Kommentare zur Ausführung" and then changinging "Zugewiesen an" fetches comments before edit.

### Steps to Reproduce

1. have some comments in "Kommentare zur Ausführung"
2. edit task
3. edit these comments
4. edit "zugewiesen an"
5. now the comments have change to the state before editing

### Expected Behavior
"Kommentare zur Ausführung" staying unchanged

### System Details

* Device:
* SORMAS version: 1.70.4
* Android version/Browser: Chrome Version 102.0.5005.115 (Offizieller Build) (64-Bit)
* Server URL:
* User Role:

**Comment by MateStrysewske** [comment]
@SormasTheGreek Can't reproduce this on 1.73.0-SNAPSHOT. The field is set to read-only when I change the assignee, but the updated value is retained.

**Comment by SormasTheGreek** [comment]
I tried on my ipad last evening on Safari - same result. Maybe my descriptions lacks some info: The case should already contain "Kommentare zur Ausführung". When entering the dialog again and editing the comments-field, switching the assigned user reverts to the values when entering the case-dialog. Which is odd.

**Comment by SormasTheGreek** [comment]
<img width="568" alt="s1" src="https://user-images.githubusercontent.com/104991688/174651488-9e13d4cb-b1e2-4786-9bbd-15eab71c0af4.png">
I enter the dialog already having some comments.

<img width="568" alt="s2" src="https://user-images.githubusercontent.com/104991688/174651499-2b4047f3-8690-4856-939f-d7571a38d37f.png">
You see, i edited some comments.

<img width="566" alt="s3" src="https://user-images.githubusercontent.com/104991688/174651506-30133e7f-b1ec-4e3c-ad1c-55d935240552.png">
As you see from the length of the string that i changed the assigment, and magically get the old comments back below, and I lose my changed data.

**Comment by dinua** [comment]
I have tried multiple scenarios and I still could not reproduce it , the comment was always updated.

**Comment by kwa20** [comment]
@dinua @MateStrysewske Have you tried to set the feature property `ALLOW_FREE_EDITING` for `TASK_MANAGEMENT` to TRUE? I couldn't explain why this is relevant but it's at least a potential difference which could be present when trying to reproduce this issue.

**Comment by MateStrysewske** [comment]
@dinua Please try again taking the suggestion from @kwa20 into account; @adinaflorea9 if you could try to reproduce it on your system, that would be very helpful as well! :)

**Comment by adinaflorea9** [comment]
Yes, this is what I am currently trying. something is unclear though, the reporter of the ticket stated that they are doing this on a tablet (i.e. they are using the android app), but the tag of the ticket is for vaadin-app. 

I'll try on my Android Studio and on the web-app and I'll leave a comment here with my findings.

**Comment by MateStrysewske** [comment]
@adinaflorea9 They said that they were using their iPad, but they were still accessing the browser version, so the web app :)

**Comment by adinaflorea9** [comment]
Behavior is reproducible on my local machine (SORMAS version 1.75.0-SNAPSHOT(B8D12C9) ) if the feature property ALLOW FREE EDITING for TASK MANAGEMENT  is set to TRUE in the DB.

**Comment by adinaflorea9** [comment]
Steps to reproduce:
1. Logged in with an Admin+NatUser, create a case and a task for the case (assign the task to the logged in user and add a comment to the section "Kommentare zur Ausführung");
2. Navigate to the 'Tasks' directory and open to edit the task created at step 1;
3. Change the information from the section "Kommentare zur Ausführung";
4. Change the assignee of the task.
=> comment from the section "Kommentare zur Ausführung" reverts to the data that was inputted at step 1.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(d312652).

Behavior is no longer reproducible if the feature property ALLOW FREE EDITING for TASK MANAGEMENT is set to either TRUE or FALSE in the DB.
