### ISSUE TITLE
POE Informant can create Event Participants and edit existing ones, in the android-app

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9537]
### Bug Description

The user POE Informant has the EVENT_PARTICIPANT_CREATE  right set to NO; in the mobile app they are able to create new event participants and save them. When triggering a synchronization afterwards, errors are displayed in the logs and in the app.

After deleting the whole event from the vaadin-app, and triggering another synchronization in the mobile app, the sync was successful and the errors were not displayed again.

### Steps to Reproduce

1. Log into the mobile app with a POE Informant user;
2. Navigate to the 'Events' tab and create a new Event Participant;
3. Trigger a synchronization with the server.

### Actual Behavior

The new Event Participant is not synchronized to the web app and errors are displayed in the mobile app and in the server logs.

### Expected Behavior

The POE Informant should not be permitted to create new event participants as their EVENT_PARTICIPANT_CREATE right is set to NO.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/174255375-5d3f7e82-fb47-4015-8a7b-4d2b385e8da2.png)

### System Details

* Device:  Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(f6f7026)
* Android version/Browser: Chrome; Android 11
* Server URL: local machine
* User Role: POE Informant

### Additional Information

I attempted to reproduce the steps twice and the errors displayed in the logs seem to be different:
[POE Informant Error 1.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8925720/POE.Informant.Error.1.txt)
[POE Informant Error 2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8925724/POE.Informant.Error.2.txt)

The behavior is also reproducible when the POE Informant edits an existing event participant; they also have the EVENT_PARTICIPANT_EDIT user right = NO.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas app ( Sormas 1.75.0-snapshot) using test.sormas.netzlink.com env + android app.
![image](https://user-images.githubusercontent.com/70562142/179973709-a3e00d42-8fbb-4381-b0eb-3798db67fd4c.png)
Poe Informant is not able to edit the Event
