### ISSUE TITLE
POE Informant is able to change a case's disease in the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9539]
### Bug Description

POE Informant has the CASE_CHANGE_DISEASE user right set to NO; however, in the mobile app they are able to successfully change a case's disease and save it.

In the 'Create new case' form, the disease filed is not displayed for this user, but the 'Disease variant' field is.

After saving the edited case, if a synchronization is triggered, it fails and errors are displayed in the mobile app and in the server's logs.
After deleting the edited case (from the vaadin-app), the synchronization with the server of the mobile app was successful.

### Steps to Reproduce

1. Log into the mobile app with a POE Informant user;
2. Open the 'Create new case' form and fill in the mandatory information and save the new case;
-> the 'Disease variant' field is displayed in the form even though the 'Disease' field is not;
3. On the new case's 'Case page' navigate to the 'Disease' field and select any disease from the dropdown;
4. Save the changes.

### Actual Behavior

The POE Informant can save the case after changing the disease.

If a synchronization with the server is triggered afterwards, it fails and errors are displayed both in the mobile app and in the server's logs.

### Expected Behavior

The POE Informant is not able to edit a case's disease - the disease field is read only on the case page and it contains the value 'Not yet defined' (in order for the behavior to be consistent with the one for other POE users that have the same CASE_CHANGE_DISEASE right set to NO).

In the 'Create new case' form, the 'Disease variant' field is not displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/174261617-441bbd08-98fe-4349-862f-d478ea880694.png)

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(f6f7026)
* Android version/Browser: Chrome, Android 11
* Server URL: local machine
* User Role: POE Informant

### Additional Information

Logs from the local machine:
[Logs error case change disease POE Informant 1.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8926080/Logs.error.case.change.disease.POE.Informant.1.txt)
[Logs error case change disease POE Informant 2.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8926083/Logs.error.case.change.disease.POE.Informant.2.txt)

**Comment by bernardsilenou** [comment]
I think we can also check if the user is the `reporting user of the entity`,  if this is true, then the rule CASE_CHANGE_DISEASE ==NO does not apply.
If the POE informant is the reporting user, then they should be able to change the disease
Users often make errors when reporting entities and they should have the option to correct them.
This is similar to the situation when a surveillance officer in district 1 creates a case in district 2. the reporting user can edit the case but other surveillance officers in district 1 can not edit nor view the case.

**Comment by adinaflorea9** [comment]
@bernardsilenou The user POE Informant was able to edit the disease of any case, regardless of who created it, as long as the case was a Point of Entry case within the user's jurisdiction.

**Comment by roxanamlendea** [comment]
Currently, when a POE Informant / POE National User / Poe Supervisor creates a new Case, doesn't have the disease field in the case creation form, and the Case's disease is automatically set to 'Not yet defined'.

**Comment by roxanamlendea** [comment]
@bernardsilenou just to make sure that I understand correctly, what do you mean by maintain the feature as specified? like in the Expected Behavior of the ticket or like in your comment?

**Comment by bernardsilenou** [comment]
like in the Expected Behavior of the ticket, please.
Thanks

**Comment by MartinWahnschaffe** [comment]
> like in the Expected Behavior of the ticket, please. Thanks

But the expected behaviour says that the disease variant field should be hidden (and the disease field in the creation form will stay hidden, too).
I guess that's not what you meant, right?

I also don't see why POE users should not be able to define a disease when creating a new case. It seems to be like that for quite some time now, so I'm wondering how this is used in the field? Are they not using POE users in the field at all?

@bernardsilenou I'd suggest to create a change request to make sure that whenever a POE (or any other) user creates a new case the user is able to define the disease. If you agree, @roxanamlendea will take care of creating the issue.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
I did not want to add all the changes to this issue, but ist nice to create another issue:
I also think all users who have the right to create a case should also have the right to assign disease + variant if applicable. In addition, the reporting user (no matter their role) should always have the right to change the disease also.

It can happen that a reporting user accidentally chooses the wrong disease and after saving the creation form, they would need to correct it.

**Comment by roxanamlendea** [comment]
@bernardsilenou I'll open a change request with the requests specified in your comment.

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.75.0-SNAPSHOT (9332459) on Android 11 phone connected to the server test-de.sormas.netzlink.com/sormas-rest/.
