### ISSUE TITLE
Contact Officer and Case Officer are able to change a case's disease in the mobile app

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9540]
### Bug Description

The Contact Officer and the Case Officer have the user right CASE_CHANGE_DISEASE set to NO; however, in the mobile app they are able to edit the disease of existing cases, regardless of who reported them.

When triggering a synchronization with the server afterwards, a warning message appears informing the user that '
Some entries could not be synchronized. Please try again later'.

### Steps to Reproduce

1. Log into the mobile app with a Contact Officer user or a Case Officer;
2. Open an existing case and change it's disease;
3. Save the case and trigger a synchronization with the server.

### Actual Behavior

The changes made on the case (the disease being changed) are saved.

### Expected Behavior

The Contact Officer and Case Officer are not able to edit the case disease - the disease field is read only on the case page (behavior that would be consistent with the one from the vaadin-app where the 'Disease' field is read only for these users).

### Screenshots

Message that appears if the user triggers the synchronization after editing the disease of an existing case:
![image](https://user-images.githubusercontent.com/96909231/174304489-8cf4109c-3b20-4574-ae1d-69214560baa5.png)

### System Details

* Device: Windows 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.73.0-SNAPSHOT(f6f7026)
* Android version/Browser: Android 11
* Server URL: local machine
* User Role: Contact Officer, Case Officer

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.75.0-SNAPSHOT (6c28468) for the vaadin app and on Android 11 phone connected to the server test-de.sormas.netzlink.com/sormas-rest/ for the android app.
