### ISSUE TITLE
A Contact Officer is able to create new samples and edit existing ones

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9548]
### Bug Description

A Contact Officer has the user rights SAMPLE_CREATE, SAMPLE_EDIT, and SAMPLE_EDIT_NOT_OWNED set to NO; however, in the mobile app, they are able to create new samples and edit some fields on existing samples that were not created by the user ('Reason for Sampling/Testing'; 'Field Sample ID'; 'Comment' and 'Final Laboratory Result').

### Steps to Reproduce

I:
1. Log into the mobile app with a Contact Officer user;
2. Navigate to the 'Samples' directory;
3. Open and edit an existing sample.

II:
1. Log into the mobile app with a Contact Officer user;
2. Navigate to the 'Cases' directory and open an existing case;
3. Navigate to the 'Case Samples' tab, enter edit mode and create a new sample.

### Actual Behavior

The Contact Officer is able to create new samples and edit existing ones.

If the user triggers a synchronization with the Server after creating a new sample or editing one, an error message is displayed letting the user know that some entries could not be synchronized.

### Expected Behavior

The Contact Officer is not able to create new samples or edit existing ones.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/174559074-e33a9433-ce21-4985-94b4-4be8a463a4f3.png)

### System Details

* Device: 10 (vaadin-app); Android Studio Emulator - Pixel C (android-app)
* SORMAS version: 1.74.0-SNAPSHOT(edcc878)
* Android version/Browser: Android 11
* Server URL: local machine
* User Role: Contact Officer

### Additional Information

Expected behavior is described to match the behavior from the vaadin-app where the Contact Officer is not able to create new samples or edit any field on existing samples.

**Comment by zohaibhassan122** [comment]
@adinaflorea9,
Can we have a detailed error displayed? like if we can see exactly which entries were not able to sync. Maybe at least the case ID. Otherwise, we are blank and don't know what is not being synced as a user.

**Comment by zohaibhassan122** [comment]
@adinaflorea9, I have created another issue in the past, which is more about a detailed progress bar/page when we are doing synchronization. Maybe, this thing can be covered with that issue and you can add that in some coming sprint. 

[https://github.com/hzi-braunschweig/SORMAS-Project/issues/9437](url)

**Comment by roxanamlendea** [comment]
Verified ticket on test-de.sormas.netzlink.com using the latest version of Sormas 1.75.0-SNAPSHOT (9332459) on Android 11 phone connected to the server test-de.sormas.netzlink.com/sormas-rest/.
