### ISSUE TITLE
'An error has occurred' message is triggered when trying to bulk edit the assignee of tasks that have the 'Task context' = General

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9554]
### Bug Description

An error message is displayed when a user tries to edit the assignee of tasks that have the task context = 'General' from bulk edit mode in the 'Tasks' directory.

### Steps to Reproduce

1. Navigate to the 'Tasks' directory and filter the tasks based on 'Task context' - 'General';
2. Enter bulk edit mode and from bulk actions select 'Edit';
3. In the 'Edit task' form, check the 'Change assignee' checkbox.

### Actual Behavior

An error message is displayed:
![image](https://user-images.githubusercontent.com/96909231/174590795-50b87edf-4fac-43b0-920b-e734672eb021.png)

### Expected Behavior

User should be able to successfully change the assignee of the tasks.

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(edcc878)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Issue was observed today while testing for ticket #8888.

Logs from the local machine:
[Error tasks assign - general .txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8940151/Error.tasks.assign.-.general.txt)

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.74.0-SNAPSHOT (311e3d2) from the development branch.
