### ISSUE TITLE
External Lab Officers can be assigned as 'Task assignee', via bulk edit mode in the 'Tasks' directory

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9556]
### Bug Description

External Lab Officer is visible among the list of users that can be selected as 'Task Assignee' for tasks associated with cases from differing jurisdictions (when users of district/regional/national level can be selected as assignees).

### Steps to Reproduce

1. Create 2 cases that have a different responsible jurisdictions;
2. Navigate to the 'Tasks' directory and enter the bulk edit mode;
3. From the list of tasks, select the 2 tasks associated with the cases from step 1;
4. From bulk actions select 'Edit' and in the 'Edit task' form check the 'Change assignee' checkbox;
5. Observe the 'Task assignee' dropdown.

### Actual Behavior

External Lab Officer is visible and selectable in the dropdown.

### Expected Behavior

External Lab Officer is not visible in the dropdown.

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(edcc878)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Behavior observed while testing for ticket #8888.

**Comment by MateStrysewske** [comment]
No longer an issue when external lab users are assigned a laboratory, i.e. fixed by #8892.
