### ISSUE TITLE
The icon lab message is missing for the user roles Clinican, Event Officer and Contact Supervisor

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#9566]
### Bug Description

With the user roles Clinican, Event Officer and Contact Supervisor, the icon "Lab Messages" to view the message in the samples card of a case is missing. 

### Steps to Reproduce

1. Process Lab message and Save 
2. Login with the user role Clinican, Event Officer or Contact Supervisor
3. Go to the processed case from Step 1
4. Observe the sample card on the right
5. Do the same with another user role e.g. Surveillance Supervisor

### Expected Behavior

The Lab Message Icon is visable for the user roles Clinican, Event Officer and Contact Supervisor. With the icon the processed lab message can be viewed. Every user role who can see entities pathogenes and samples should be able to view lab message. 

### Screenshots

User role: Clinician
![image](https://user-images.githubusercontent.com/98821699/174807043-d25f6a1d-173f-477a-b84c-1874a97d751b.png)

User role: Surveillance Supervisor
![image](https://user-images.githubusercontent.com/98821699/174806449-d04f2de0-23e7-4d4b-b9b3-54298efb637f.png)

### System Details

* Device:
* SORMAS version: 1.74-Snapshot (3316ffeb3f)
* Android version/Browser:
* Server URL: test-de1
* User Role:

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup This is also already present on 1.72.1 which does not seem to be explained by the rights change, at least the refactoring did not happen there yet.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup The question may be why this was different in e.g. 1.70.4? Users were able to see the messages previously and are now confused why some users can't see the message anymore without a change in userroles. They were also never able to work on them themselves I think. If this can be explained, I would think about what the desired use case is and if we need to adjust something

**Comment by FredrikSchaeferVitagroup** [comment]
This was changed [here](https://github.com/hzi-braunschweig/SORMAS-Project/pull/8791). Maybe @vidi42 can provide some insights?

**Comment by vidi42** [comment]
> This was changed [here](https://github.com/hzi-braunschweig/SORMAS-Project/pull/8791). Maybe @vidi42 can provide some insights?

From what I remember [this](https://github.com/hzi-braunschweig/SORMAS-Project/pull/8791) was done right after a big user right refactoring 1.70 https://github.com/hzi-braunschweig/SORMAS-Project/issues/445
And the purpose of it was to restrict users who don't have access to the LabMessage functionality from being able to see lab messages or buttons associated to that functionality.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Yes, but those users would then also see the external messages directory.
