### ISSUE TITLE
POE National User and POE Supervisor can no longer access the mSERS directory

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9571]
### Bug Description

An error message is displayed when a POE National User or a POE Supervisor try to filter aggregate reports based on region/district.
Behavior was observed while testing for ticket #8974.

### Steps to Reproduce

I:
1. Log into the vaadin-app with a POE National User and navigate to the 'mSERS' directory;
2. From the 'All regions' filter dropdown, pick any region.

II:
1. Log into the vaadin-app with a POE Supervisor and navigate to the 'mSERS' directory;
2. From the 'All districts' filter dropdown, pick any district.

### Actual Behavior

An error message 'A problem has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' is displayed and the users are not able to filter reports based on region/district.

### Expected Behavior

The POE National User and POE Supervisor are able to filter reports based on region/district.

### Screenshots

![image](https://user-images.githubusercontent.com/96909231/174968332-3187f3c4-dfa8-46a3-89aa-8162447a3672.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(3316ffe)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: POE National User and POE Supervisor

### Additional Information

Logs from the local machine:
[POE Supervisor logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8955309/POE.Supervisor.logs.txt)
[POE National User logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8955310/POE.National.User.logs.txt)

**Comment by adinaflorea9** [comment]
Update on the behavior reported: the users POE National User and POE Supervisor can no longer access the mSERS directory at all.

An error message is displayed in the UI and an error is also visible in the server logs:
[poe supervisor.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9008649/poe.supervisor.txt)
[poe national user.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9008651/poe.national.user.txt)

**Comment by roxanamlendea** [comment]
POE National User and POE Supervisor can now access the mSERS and can now filter the aggregate reports (from both Aggregate Reporting tab and Report Data tab) based on all filters. 
There is an issue (POE National User is prevented from seeing nation wide aggregated reports) that will be fixed in #9703.
