### ISSUE TITLE
Entries in the case directory are sometimes not displayed

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9575]
### Bug Description

The case directory is empty, although cases exist in the database
![image](https://user-images.githubusercontent.com/101708230/175004512-177f74ea-9a3d-4449-ae7b-009df1cb4e4a.png)
 
This behavior was observed on June 20th and June 22nd. When trying again, the cases were displayed. Since the cause of the disappearance and reappearance of the cases is not apparent, we ask for a review.

### Steps to Reproduce

Login with user automation_admin  (Roles: Admin AND NatUser)
Click Cases

### Expected Behavior
See all cases

### System Details

* Device:
* SORMAS version: 1.74.0 Snampshot 331ffe  
* Android version/Browser: 
* Server URL:  https://test-de.sormas.netzlink.com/ and https://test-auto.sormas.netzlink.com/
* User Role: automation_admin (Roles: Admin AND NatUser)

**Comment by kwa20** [comment]
Reproduced this issue on test-auto.sormas.netzlink.com (Admin, National User), 1.74-SNAPSHOT
![emptyDirectories](https://user-images.githubusercontent.com/70317594/175255247-da4edc3f-8167-4121-8080-6c8814275de7.gif)

and test.sormas.netzlink.com (Admin, National User), 1.74-SNAPSHOT
![emptyDirectories2](https://user-images.githubusercontent.com/70317594/175255472-32281fe4-779e-4637-90cf-4b44a4d5da2f.gif)

**Comment by KernB** [comment]
During the automatic tests tonight (User: automation test on teste-auto) fresh data were created via the API. In the UI, this data was invisible.

In addition, several people carried out various manual tests. The behavior was observed several times. However, no reproducible regularity could be determined. After a user switch the unfiltered list was sometimes displayed with and sometimes without entries. 
Once during the tests, the page (empty list) was reloaded in the browser after a waiting period. After the reload the list was filled.

**Comment by MateStrysewske** [comment]
As discovered by @StefanKock: The user in question had jurisdiction level NONE, which means that they don't see any data when the `includeCasesFromOtherJurisdictions` filter is set to false (which is the default).

@KernB Did you add this user via the UI or did you create it with an SQL script?
