### ISSUE TITLE
Cannot Save Symptoms Form If Lesions (Vesiculopustular rash) is set to YES (Backport of #9592)

### ISSUE THREAD

**Issue by obinna-h-n** [hzi-braunschweig/SORMAS-Project#9576]
### Bug Description

Backport for 1.72.2 of #9592

**Comment by MateStrysewske** [comment]
@kwa20 @JaquM-HZI I'd heavily suggest to fix this in 1.72.2 (since we're already building that hotfix anyway) because of relevance.

**Comment by kwa20** [comment]
@MateStrysewske This seems to be related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/9390

**Comment by MateStrysewske** [comment]
@kwa20 Ah yeah, same issue, missed that one. Will close it in favour of this one here.

**Comment by obinna-h-n** [comment]
@MateStrysewske could you also confirm from your end if the monkeypox images are showing. We had to comment required field validation for all monkeypoxImageFieldIds. While adding the annotation displays them also, the images are not showing, so the questions look somehow as there is no image for user to see. The images are in the theme classpath though but are not displaying on screen.

**Comment by obinna-h-n** [comment]
Alright @MateStrysewske , thanks.

**Comment by adinaflorea9** [comment]
Verified ticket in peer to peer testing session with @sergiupacurariu in a call, on his local machine - hotfix branch 1.72.2.

'Happy flow' of saving symptoms on the 'Symptoms' tab of cases, new visits with symptoms on the 'Follow-up' tab of cases and contacts was covered. 

Further testing will be done and ticket will be marked as verified by QA once the changes are merged into the current development branch and SORMAS version 1.74.0-SNAPSHOT.

**Comment by kwa20** [comment]
@MateStrysewske @adinaflorea9 I noticed that when Vesiculopustular rash = YES is selected, the quick selection options show an error. I am not sure if there might be other subsequent selection options that might produce the same issue.

Let me know if this issue should be reopened because of 1.74 or if this should be a separate bug report due to this one being merged with 1.72.2 already.

![monkeypoxSymptomsError](https://user-images.githubusercontent.com/70317594/175528545-f2fd3b43-2322-45df-a08a-e35a51848c92.gif)

**Comment by kwa20** [comment]
@adinaflorea9 Thanks for adding the logs! I also only discovered it later

**Comment by MateStrysewske** [comment]
@adinaflorea9 Yes, we definitely need a new ticket for that because this one has already been released in 1.72.2. Can you take care of it? :)

**Comment by adinaflorea9** [comment]
@MateStrysewske Thank you! Yes, I'll log the ticket now

**Comment by adinaflorea9** [comment]
Additional behavior observed while testing was logged in a separate ticket (#9622). Behavior originally reported in this ticket has been fixed - tested on release-international.sormas.netzlink.com where SORMAS version is 1.72.2.
