### ISSUE TITLE
Replace @RolesAllowed by own @RightsAllowed annotation

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9577]
### Problem Description

Proven performance problem (#9559) when checking `javax.annotation.security.@RolesAllowed`

### Proposed Change

Replace `@RolesAllowed` by own `@RightsAllowed` annotation and check with interceptor.

### Acceptance Criteria

- [x] `@PermitAll` and `@DenyAll` is also considered.
- [x] UserRight._SYSTEM is also considered (e.g. completeness calculation of case is working)
- [x] Add archUnit test to make sure `@RolesAllowed` is not used in backend (in sormas-rest it's fine)

**Comment by vidi42** [comment]
Could we also have an ArchUnitTest which checks that the right annotation is used?

**Comment by AndyBakcsy-she** [comment]
Improvements observed and reported by the client. Moving ticket to the Done Lane
