### ISSUE TITLE
Mobile App v1.72.1 crashes when opened (Backport of #9558)

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#9595]
### Bug Description

Backport of #9558

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by AndyBakcsy-she** [comment]
Validated that the application can be installed on a Android 12 phone and also in an Emulator the application will start.
