### ISSUE TITLE
Hide citizenship and country of birth [1]

### ISSUE THREAD

**Issue by JaquM-HZI** [hzi-braunschweig/SORMAS-Project#9598]
### Problem Description

It is not legally permissible for Covid to collect data for citizenship and country of birth. For this reason, these fields must be hidden for Germany. In addition, these fields must be cleared after hiding so that there is no more data for them on German instances.

### Proposed Change

- [x] hide `citizenship` and `country of birth` for Germany and France
- [x] Clean up these fields afterwards by an SQL-Script / Provide a script

### Acceptance Criteria

- [x] check that the fields are no longer shown/exported in the data protection dictionary

### Implementation Details

* Use `@HideForCountriesExcept` with an empty list

### Additional Information

- What about france and swiss? @Candice-Louw @bernardsilenou @carolinverset @ClaudeMarksteinerCSI
- Fields were introduced in #3412

**Comment by bernardsilenou** [comment]
These fields were requested by DE users, I am not sure if any other instance has been using them. Hiding them on DE instance may just add more logic to the system.
What about just removing them from the UI?  and add another issue to remember to delete them from the db in future.

**Comment by carolinverset** [comment]
In France, these variables are not used and can be hidden/deleted. Best regards !

**Comment by BarnaBartha** [comment]
Script to cleanup citizenship and birthCountry columns in needed databases:
`UPDATE person SET citizenship_id = NULL WHERE citizenship_id IS NOT NULL;
UPDATE person SET birthcountry_id = NULL WHERE birthcountry_id IS NOT NULL;`

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following: on a DE server, in the Android-app the values 'Citizenship' and 'Country of Birth' are still visible on:

- Contact person page;
- Event Participant person page;
- Immunization person page.

I am assuming that since they are present on the DE server, it would also apply for a FR server + Android-app as well.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(d312652).
