### ISSUE TITLE
Add new diseases to aggregate reporting (mSERS) [0.5]

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#9605]
### Feature Description

More diseases/syndroms/aspects are needed for surveillance and are missing in the current mSERS module.

### Proposed Change

- Add the following diseases as non-primary, non-case based diseases:
  - ARI (Acute Respiratory Infections)
  - Chikungunya
  - Post-immunization adverse events mild
  - Post-immunization adverse events severe
  - FHA (Functional Hypothalamic Amenorrhea)
- Rename column description for "new cases" to "suspected cases"

### Acceptance Criteria

- It should be possible to create, edit and view aggregate reports for these diseases
- It should be possible to create, edit and view aggregate reports by varied age groups for these diseases

**Comment by MartinWahnschaffe** [comment]
Merged into hotfix branch.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(81bdbe6).

#10026 to cover the places where 'New Cases' is still displayed.
