### ISSUE TITLE
Login fails intermittently

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9610]
### Bug Description

The login was tested several times manually and automatically in the last few days. The login fails intermittently. The credentials were not changed during the tests. Here are two examples of failed logins. Subsequent logins were successful again. Nevertheless, it would be important to know the causes of these dropouts.

https://test-de.sormas.netzlink.com/   
(env_de)
![image](https://user-images.githubusercontent.com/101708230/175526627-777d7e63-9c8f-4ed3-8756-03a4632d3a80.png)

https://test-auto.sormas.netzlink.com/ 
(env_main)
![image](https://user-images.githubusercontent.com/101708230/175526429-427e15d7-b22c-44ba-a5b3-a9b3164b61aa.png)

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:  1.74.0
* Android version/Browser:
* Server URL: https://test-de.sormas.netzlink.com/, https://test-auto.sormas.netzlink.com/ 
* User Role: Automation Admin, Cont Sup, Lab Off, Nat LanUser, Nat User, Poe Sup, Rest Auto, Surv Offi, Survellance Supervisor

**Comment by KernB** [comment]
Maybe some more example will be handy. ContSup, NatLanUser and RestAuto actually can not access https://test-auto.sormas.netzlink.com/

**Comment by MateStrysewske** [comment]
@KernB I'm pretty sure that no developer has experienced this on a local instance so far, but we'll have a look at it.

**Comment by StefanKock** [comment]
Duplicate to #9726
