### ISSUE TITLE
Calculate numberOfVisits/numberOfMissedVisits in backend [2]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9611]
### Problem Description

- For cases and contacts directories there is currently 1+n pattern that does a lookup to call `DiseaseConfigurationFacade.hasFollowUp(caze.getDisease())` per entry.
- There is currently a data calculation present in the vaadin-app that needs to be moved to the angular-app somehow.

### Proposed Change

1. Add `CaseIndexDto.numberOfVisits:Int`, `CaseIndexDto.numberOfMissedVisits:Int` and for `ContactIndexDto` respectivly.
2. Set these attributes within the corresponding `getIndexList` methods.
3. Use that new attribute to configure that formatted column

### Acceptance Criteria

 - [x] No 1+n pattern for backend calls anymore.
 - [x] Calculation is done in the backend.

### Implementation Details

Discuss: Move the whole calculation of visit numbers to the backend:
```java
			if (FacadeProvider.getDiseaseConfigurationFacade().hasFollowUp(entry.getDisease())) {
				int numberOfVisits = entry.getVisitCount();
				int numberOfRequiredVisits = FollowUpLogic.getNumberOfRequiredVisitsSoFar(entry.getReportDateTime(), entry.getFollowUpUntil());
				int numberOfMissedVisits = numberOfRequiredVisits - numberOfVisits;
				// Set number of missed visits to 0 when more visits than expected have been done
				if (numberOfMissedVisits < 0) {
					numberOfMissedVisits = 0;
				}
				return String.format(I18nProperties.getCaption(Captions.formatNumberOfVisitsFormat), numberOfVisits, numberOfMissedVisits);
			} else {
				return "-";
			}
```

**Comment by roxanamlendea** [comment]
Verified ticket on local setup using the latest version of Sormas 1.78.0-SNAPSHOT.
