### ISSUE TITLE
Conversion of age groups should not throw exception [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9623]
### Problem Description
Currently loading the disease configuration during startup the server does not start when there is an invalid age group defined for a disease, because the used converted validates the age group which throws an exception.

### Proposed Change

- [x] The converter should still validate each age group, but should catch the exception, log a warning and ignore the invalid age group

This will also make sure that the mSers module in the UI and app does not throw exceptions, but instead just doesn't show invalid age groups.

**Comment by adinaflorea9** [comment]
Mobile app closes when users attempt to open the mSERS directory. @MateStrysewske suggested that the issue might be connected to this ticket.

Logs from the local machine:
[logs mobile app.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9038889/logs.mobile.app.txt)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(08db1fc).

Age Groups were configured based on the information from this page: https://github.com/hzi-braunschweig/SORMAS-Project/wiki/Disease-Configuration-Options.

No exceptions were thrown; warnings were displayed in the server logs for each age group with an invalid format; age groups with an invalid format were not displayed in the UI (both in the vaadin-app and the android-app).
