### ISSUE TITLE
[DEMIS2SORMAS] Create Surveillance reports for processed external messages

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9624]
### Situation Description

The external messages interface allows the processing of such messages and the creation of cases. The surveillance reports which reference cases document incoming reports in health departments associated to such cases. When an external message is processed, a surveillance report should be created automatically and reference the processed message.
### Feature Description

TO DO
### Additional Information

- 0-1...0-1 Surveillance Reports <> External Messages
- Samples will still reference messages as before
    - `labMessages` will have `sampleReports` which can reference samples
- Currently, physician reports reference a case. Later, they should reference surveillance reports

Open questions:
- Do surveillance reports represent "Meldevorgänge" or "Meldungen" in DEMIS?
    - `NotificantionBundleId` vs `NotificationId`

**Comment by FredrikSchaeferVitagroup** [comment]
Isn't this feature fully covered with https://github.com/hzi-braunschweig/SORMAS-Project/issues/9680 and https://github.com/hzi-braunschweig/SORMAS-Project/issues/9681?
