### ISSUE TITLE
Allow diseases to be used case-based and aggregated at the same time [2]

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#9629]
### Problem Description

Diseases have to be usable both for case-based surveillance and aggregate reporting in case that countries are using both approaches simultaneously.

### Proposed Change

Allow diseases to be used for both features by replacing the `caseBased` property of disease configurations.

### Implementation Details

- [x] Rename the `caseBased` property of disease configurations to `caseSurveillanceEnabled`
- [x] Add a new property called `aggregateReportingEnabled`; write an SQL migration script that sets it to the opposite value of `caseSurveillanceEnabled`
- [x] Rename the `caseBasedDiseases` and `aggregateDiseases` lists in DiseaseConfigurationFacadeEjb to `caseSurveillanceDiseases` and `aggregateReportingDiseases` and update the code that builds them based on the new properties
- [x] Update the `getAllDiseases` method by adding a new parameter called `aggregateReporting` (and change the `caseBased` parameter to `caseSurveillance`). Update the code to return all diseases based on the value of these properties; make sure that the final list doesn't contain any diseases twice
- [x] Update usages of the `getAllDiseases` method if necessary; in most places, you won't need to change anything, so I recommend to add an overloaded `getAllDiseases` method without the `aggregateReporting` parameter and call the other `getAllDiseases` method with false
- [x] Make sure that code that retrieves diseases for aggregate reporting calls the `getAllDiseases` method with `caseSurveillance == false`
- [x] Apply the same changes to the mobile app

### Additional Information

Data between case surveillance and aggregate reports are not supposed to match/link, the features stay separate.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(fdf5447).
