### ISSUE TITLE
Tag "Inactive" is displayed at active entries

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9647]
### Bug Description

When you create a new case and the responsible jurisdiction differs from the jurisdiction of the place of stay the point of entry is marked wrongly as "(Inactive)".

### Steps to Reproduce

1. Create a Case
![image](https://user-images.githubusercontent.com/101708230/176134963-95437ddd-b1d5-48ea-92d6-88e368a27ddc.png)

2. Check the Case
![image](https://user-images.githubusercontent.com/101708230/176136797-632b877c-f8a6-4879-b1a9-4e082bff328b.png)

### System Details

* Device: Laptop
* SORMAS version: 1.74.0 (a22b569)
* Android version/Browser: Chrom
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Admin

### Additional Information

Maybe there is a connection to the ticket: https://github.com/hzi-braunschweig/SORMAS-Project/issues/9224

**Comment by dinua** [comment]
After a discussion with @MateStrysewske , for this situation when the POE is not in the list of POEs for that jurisdiction,
we will no longer display the "Inactive" tag

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.74.0-SNAPSHOT (a3a5719) from the development branch.
