### ISSUE TITLE
When using the German language, Hide field is not displayed during merge

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9648]
### Bug Description

When using the German language, 'hide' field is not displayed during merge
Also the 'pick' field should be displayed completely
### Steps to Reproduce

1. Make sure that only 2 cases in the system are duplicates
2. Try to merge the two cases by using the German language

### Expected Behavior

'hide' field should also be visible, 'pick' field should not be cut off
### Screenshots

![MergeGerman](https://user-images.githubusercontent.com/100844689/176135390-7721d018-0e42-4b67-9a70-5ebe2708d718.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.72.2 / 1.74.0
* Android version/Browser: Edge
* Server URL: https://release-de.sormas.netzlink.com (1.72.2)/ https://test-de2.sormas.netzlink.com (1.74.0)
* User Role: admin

### Additional Information

Please note step 1. If you have many duplicates everything works.
![image](https://user-images.githubusercontent.com/100844689/176140839-d9f544ee-f194-41b1-a906-6eaa1a1e0bea.png)

Similar to https://github.com/hzi-braunschweig/SORMAS-Project/issues/8805 
Please cross-check for contacts.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(9f15ff4). 

'Hide' button is visible in both 'Cases' and 'Contacts' directories - 'Merge duplicates'. Checked for English, German and French.
