### ISSUE TITLE
'Reason for deletion details' text on the deleted Event's / Event Participant's page is displayed in German when English is selected

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9655]
### Bug Description
When an Event or an Event Participant is automatically deleted, the entity isn't permanently deleted and 'Other reason' is automatically selected as 'Reason for deletion'. However, the 'Reason for deletion details' text is in German, even if the English is selected as user language.

### Steps to Reproduce

1. Select English as user language;
2. Create an Event and edit the Creation Date from the DB in order to be automatically deleted; 
3. Wait for the cronjob to run;
4. Refresh the page of the Event;
5. Inspect the Reason for deletion fields;

### Expected Behavior
The 'Reason for deletion details' text should be displayed in the user's language (English);

### Actual Behavior
The 'Reason for deletion details' text in displayed in German.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/176177265-6b002a01-932c-4b62-a04d-68f2ad23decd.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.74.0-SNAPSHOT (c92114e)
* Android version/Browser: Chrome
* Server URL: local env
* User Role: Admin, NatUser

**Comment by MateStrysewske** [comment]
@roxanamlendea This is expected right now because the text is written into the database based on either the user language or the system language (not quite sure right now), and there's no translation afterwards since we're not translating database contents.
