### ISSUE TITLE
Test results on the dashboard don't add up

### ISSUE THREAD

**Issue by hschanze** [hzi-braunschweig/SORMAS-Project#9658]
### Bug Description
The number of tests for different diseases doesn't add up.
In the uploaded test data each case has a test, but the dashboard e.g. shows 44 cases of measles and 0 tests. This also changes for different time intervals, e.g. for the epiweek of the 28.06.2022 it shows 6 tests, but if you chose a wider interval the number of tests drops to zero.
### Steps to Reproduce
1. Connect to this server and open this sample of a measles case https://test-fr-perf-02.sormas.netzlink.com/sormas-ui/#!samples/data/QUTO5C-AO4O3R-C7AJMP-5HJLSE2A
2. Open the dashboard and filter measles cases created on week 27-2022, there are 19 as at today. The test results show 6 meanwhile more than 6 results were imported.
3. Maintain the disease and change the time filter to this year. In total there are 44 measles cases but  the number of test results is 0

### Expected Behavior
The test results on the surveillance dashboard should be the sum of the test result (irrespective of the date of the pathogen test) among the samples linked to the cases returned by the filter. The date filter applies to the parent entity (cases in the case of the surveillance dashboard). 
For cases with multiple samples or with multiple pathogen tests, then it is possible that end up with more pathogen tests than the sum of cases. When summing the pathogen test, we should only consider the ones that have the same disease as the case, ie if the disease-specific dashboard is on the tab for COVID-19,  then a positive test result for measles that is linked to the sample of the covid-19 case does not contribute to the count.
### System Details

* Device: Windows 10
* SORMAS version: 1.72.1
* Android version/Browser: Firefox
* Server URL:https://test-fr-perf-02.sormas.netzlink.com/sormas-ui/#!cases/?includeCasesFromOtherJurisdictions=false&dateFilterOption=DATE

* User Role:Admin, National User

### Additional Information
@bernardsilenou

**Comment by bernardsilenou** [comment]
@kwa20 @JaquM-HZI

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the local setup with the latest version of sormas 1.74.0-snapshot
