### ISSUE TITLE
[DEMIS2SORMAS] Adjust the processing of external messages to create surveillance reports [3]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9680]
### Problem Description

There is currently no clear association of external messages to the surveillance reports present in cases.

After the initial implementation of reporting tool interfaces it has also become clear that pathogen tests and surveillance reports are semantically quite different. Therefore, the processing of a message should lead to the creation of a surveillance report based on the respective type to document in the case what has been reported to the health departments.

https://github.com/hzi-braunschweig/SORMAS-Project/issues/6621 is a pre-requisite for this issue.
### Proposed Change

- [x] Automatically create a surveillance report entry when a message is processed for a case. 
    - Set the required `SurveillanceReport.reportDate` according to the `Bundle.meta.lastUpdated` from the DEMIS notification
    - For lab messages, set `LABORATORY` as the `SurveillanceReport.reportingType`. For physician's reports, set it to `DOCTOR`.
Set the SurveillanceReport.facility via Organization.identifier.value based on Organization.identifier.bsnr or Organization.identifier.demisLaboratoryId the same way as described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8949. When no facility can be identified that way, take OTHER-FACILITY
    - Determine the 'Reporter facility region' and 'Reporter facility district' from the identified facility. When no facility could be identified, fill in the case's region and disctrict.

- [x] Create a message link
    - Add a button with the caption _View Message_ (+ eye icon) to the edit form that allows the user to view the linked message in another pop-up as seen in the messages directory
        - this pop-up should not have any action buttons but merely display the message details
    - Add a _notepad icon_ to the card entry that also opens the message details in the same way

    - ~~When a user deletes a surveillance report entry that is linked to a message, ask the user whether they also want to delete the message or revert them back into an unprocessed state ('Delete message' or 'Revert to unprocessed')~~
        - ~~When the user selects 'Delete message', the linked message will be deleted alongside the surveillance report; navigate back to the refreshed case tab~~
            - ~~When the user does not have the `MESSAGE_DELETE` user right, they should not be able to delete surveillance reports linked to messages~~
        - ~~When the user selects 'Revert to unprocessed' the Surveillance report should be deleted while the status of the message is set to `UNPROCESSED` for it to be re-processable from the message directory; navigate back to the refreshed case tab~~
        - When a user deletes a surveillance report, remove the reference in the related external message (if any).

### Acceptance Criteria

- [x] validation when saving lab messages: whenever a lab message with reference to a surveillance report gets saved, it is to be validated that it only refers (via its sample reports and the surveillance report) to one case (no other cases, contacts, or event participants).

### Implementation Details

The ExternalMessage currently has a reference to a case. This reference is so far used only for physician's reports (the separation of lab [messages and physician's reports](https://github.com/hzi-braunschweig/SORMAS-Project/issues/9646) is not yet done).

Whith this ticket, or #9681 (depending on which one is done first), this relation has to be changed and used for both, physician's reports and lab messages. Processed external messages (lab messages and physician's reports), when related to a case, shall always have a relation to a surveillance report. The surveillance report shall always have a relation to a case.
Migration of relations currently existing in the SORMAS db has to be done. Processed physician's reports should currently always hold a reference to a case. Sample Reports of processed lab messages should always hold references to samples, and all those samples should always relate to one and the same cse/contact/event participant.

### Additional Information

![Create new report](https://user-images.githubusercontent.com/70317594/176464626-4c9a6cd4-c6d2-4579-804c-99cd5bee9e2b.png)

![Edit report](https://user-images.githubusercontent.com/70317594/176464647-30b29f82-a040-4f96-9b88-b49176b91456.png)

![Report entry](https://user-images.githubusercontent.com/70317594/164256093-a4806e44-b487-413e-bde1-642ef4259c40.png)

It is currently assumed, that Surveillance reports will represent a DEMIS NotificationBundle (Meldevorgang). Feedback is still expected from the RKI.
- Feedback from RKI > each Notification, i.e. external Message should result in one entry for Surveillance reports (this will also be conform to how it would ideally work if external messages are used in other contexts and do not have a specific lifecycle management)

**Comment by FredrikSchaeferVitagroup** [comment]
Currently, lab messages just hold a reference to a sample. For this feature, a reference to a surveillance report is necessary in addition.

Also, this issue faces the same problem as discussed [here](https://github.com/hzi-braunschweig/SORMAS-Project/issues/9681#issuecomment-1171015754) (and the comments below).

**Comment by FredrikSchaeferVitagroup** [comment]
@JaquM-HZI @kwa20 in the planning we decided to move the deletion popup described above out of this ticket.
There's a more conceptual discussion necessary about when messages have to be deleted automatically/via popups.
One related problem: When deleting external messages via a popup when deleting surveillance reports, also the relation of attached sample reports to samples would get lost.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Ok, I think that's fine. What exactly happens though when the reference of the related message is removed? Would the message stay processed or become unprocessed again? In the case of lab messages, would the references to the samples remain?

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 It would stay processed. 
In case of lab messages, the reference to the sample would remain.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 @JaquM-HZI @SahaLinaPrueger The data migration turns out to be quite complex. Would it be acceptable if all currently existing external messages just get a surveillance without facility set? That would keep the effort relatively small.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup If it's too complex I don't think it's that much of a problem, considering that the facility is mentioned in the respective external message. The external message should then be linked to the created surveillance report.

**Comment by FredrikSchaefer** [comment]
I have pushed some changes, but won't be able to continue work on this.

**Comment by kwa20** [comment]
ISSUE TRACKER COMMENT

**Comment by abrudanancuta** [comment]
Final tests finalised on local env with the version: 1.78.0-SNAPSHOT (e5b3129)
