### ISSUE TITLE
[DEMIS2SORMAS] Automatically create Surveillance reports for processed physician reports and reference messages

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9681]
### Problem Description

Currently, physician report have a case reference, but there is no clear association from the message to the case. This should be established via the Surveillance reports.
### Proposed Change

- [ ] Automatically create a surveillance report entry when a physician report type message is processed for a case. 
    - Set the required `SurveillanceReport.reportDate` according to the `Bundle.meta.lastUpdated` from the DEMIS notification
    - For physician reports, set `DOCTOR` as the `SurveillanceReport.reportingType`
    - Set the `SurveillanceReport.facility` via `Organization.identifier.value` based on `Organization.identifier.bsnr` or `Organization.identifier.demisLaboratoryId` the same way as described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/8949. When no facility can be identified that way, take `OTHER-FACILITY`
    - Determine the 'Reporter facility region' and 'Reporter facility district' from the identified facility. When no facility could be identified, fill in the case's region and disctrict.

- [ ] Create the message link as described in https://github.com/hzi-braunschweig/SORMAS-Project/issues/9680
### Implementation Details

Whith this ticket, or #9680 (depending on which one is done first), this relation has to be changed and used for both, physician's reports and lab messages. Processed external messages (lab messages and physician's reports), when related to a case, shall always have a relation to a surveillance report. The surveillance report shall always have a relation to a case.
Migration of relations currently existing in the SORMAS db has to be done. Processed physician's reports should currently always hold a reference to a case. Sample Reports of processed lab messages should always hold references to samples, and all those samples should always relate to one and the same cse/contact/event participant.

### Additional Information

Each notification represents one entry in surveillance reports.

**Comment by FredrikSchaeferVitagroup** [comment]
The creation of the surveillance report should be done at the end of processing a physician's report, instead of saving a case reference to it. The physician's report needs to get a reference to the surveillance report instead, and the surveillance report needs to refer to the case. 

Shall the creation of the surveillance report happen automatically (without the processing user seeing it)? If so, what if the facaility can not automatically be determined from the `Organization.identifier.bsnr` or `Organization.identifier.demisLaboratoryId`? Should it be left null then?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup It can be created automatically without the user seeing it. If the facility cannot exactly be determined, it can be set in the facilityDetails field. I assume category and type also need to be determined per message type then?

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup I think mapping the reporter region and district will be very pesky because it is not exactly provided via the DEMIS notification. However, it might be possible to infer them through the `postalCode`. Since this is quite extensive, I'd do that separately.
For the `facilityType`, I'll provide a mapping of [OrganizationType](https://simplifier.net/demis/organizationtype) which will be also beneficial elsewhere. The category is then determined by the `facilityType` in SORMAS.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup 

> I think mapping the reporter region and district for unknown facilities will be very pesky because it is not exactly provided via the DEMIS notification. However, it might be possible to infer them through the postalCode. Since this is quite extensive, I'd do that separately.

I  noticed that it is necessary to select a region and district to be able to select the option for "Other facility". This might be a problem based on the quoted comment above.

I am not sure how to solve this gracefully without having to map all postal codes to a region and district. Maybe it would be possible to provide the "Other facility" selection option even if the region and district fields remain empty?

**Comment by FredrikSchaeferVitagroup** [comment]
This ticket was decided to be included into #9680. The content of both ticket is very similar and the changes should be done together. The description of #9680 was updated accordingly. This ticket will be discarded.
