### ISSUE TITLE
Filter commands not responsive (see screen dump)

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#970]
![image](https://user-images.githubusercontent.com/35563508/52849653-d2a8e580-3111-11e9-9a6d-c8356412aa1c.png)

The filter command for the set priorities freezes out. Using Helmholtz to reference, same error applies to the Nigerian server.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar What do you mean by "freezes out"? When I tried to filter by date it just did nothing (which seems to be a bug). The other filters (disease, region) work. 

On the whole this view is still quite slow which will be addressed after we have done #802 

- [ ] The filter just does not work. Check why and fix
- [ ] The field for the date reference needs to be entered as well

**Comment by Chinedar** [comment]
Oh yes @MartinWahnschaffeSymeda it just doesn't work.
