### ISSUE TITLE
Cleanup reporting user validation

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#9701]
### Bug Description
We discovered  in #9696 that reporting user validation is probably inconsistent and is only triggered for Contacts.
Citing @leventegal-she 
> Please create a ticket to cleanup the reporting user validation. It's strange that only contact validation fails if it has no reporting user.

Behavior should be consistent for all entities.

~Please also adjust the tests (e.g., `testShareContact()`) accordingly~ Test works

---

Found:
- `EventFacade`
- `EventParticipateFacade`
- `ImmunizationFacade`
- `CaseFacadeEjb`

**Comment by abrudanancuta** [comment]
Reopened because the sharing of the cases on s2s is broken

**Comment by JonasCir** [comment]
I have a fix ready in a second

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.75.0-SNAPSHOT (a2d6ab9)
