### ISSUE TITLE
[AUDIT] Important, type-specific information does not show up in the audit log [2]

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#9710]
### Problem Description
For example, if we change the user name, the action gets log through the auditor, however, the name is not included in the log line. This shows that we need a mechanism which allows us two tweak the representation in the audit log.

### Proposed Change
~Introduce an interface which extends `HasUuid` and let all DTOs implement it. The default implementation should return only the UUID, but in case we need more information a more specific representation should be returned.~

Introduce an annotation which can be put onto fields and methods to build the representation in the log 

### Acceptance Criteria
* No `toString` based representation, for the most important types
* Adjustable representation
* Do it for the user name
* Architecture test

### out of scope
* No `Object@JVM-Address` style strings in log

### Split tickets
- [x] #10335
- [x] #10364
- [x] #10377
- [x] #10403
- [x] #10369 is discarded ~necessary or introduced architecture test fails~

**Comment by JonasCir** [comment]
@MartinWahnschaffe FYI :)

**Comment by AndyBakcsy-she** [comment]
Validated ticket during a peer testing session with Jonas
