### ISSUE TITLE
Sometimes editing logged in user results in infinite loop on the server

### ISSUE THREAD

**Issue by leventegal-she** [hzi-braunschweig/SORMAS-Project#9711]
### Steps to Reproduce

1. Login with NatUser
2. Edit the user NatUser: add a new role and change the address
3. Save 
=> The server runs into an infinit loop. See Additional Information for stack trace
### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

[stacktrace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9029642/stacktrace.txt)

**Comment by ChristopherRiedel** [comment]
The problem occurs when getByUserName is called in UserService when saving.

**Comment by JonasCir** [comment]
One way around this is probably to populate the cache before the save in `getUserEditComponent` before the saveUser in the else block. However, I do remember we flush the current user cache when updating the users, so this might be related to that as well.

**Comment by JonasCir** [comment]
I understand what's causing the issue but I have currently no idea how to fix it... I encountered the issue earlier while developing the change user feature and actively countered it back then, I have no idea why the issue shows up under this circumstances again

**Comment by JonasCir** [comment]
Cannot reproduce anymore.

Duplicate of #10104 and #9999.
