### ISSUE TITLE
Immunization information is not updated when the disease if a case is changed in the 'Process message' form

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9722]
### Bug Description

When processing a 'Physician's report' and changing the disease of the case, the information from the 'Immunizations' tab is not updated according to the disease - namely, the types of vaccines that should be visible in the 'Vaccine name' dropdown, and the types of vaccine manufacturers that should be visible in the 'Vaccine manufacturer' dropdown.

### Steps to Reproduce

1. Navigate to the 'Messages' directory and click to process a 'Physician's report' that has no associated disease (or any other disease than Covid-19);
2. In the 'Create new case' form set the disease to any other value than Covid-19 (or leave it as it is if the disease was other than Covid-19 to begin with);
3. Fill in the other mandatory information and click 'Save';
4. In the 'Process message' form, navigate to the 'Immunizations' tab, click 'Add Vaccine' and observe the dropdowns 'Vaccine name' and 'Vaccine manufacturer'
-> dropdowns are populated with the values 'Unknown' and 'Other' as there are no vaccines configured in the system for any other disease than Covid-19.
5. Navigate to the 'Case' tab, change the disease to Covid-19 and click 'Next'
-> pop-up message 'Case saved' appears, confirming that the changes were saved.
6. Navigate to the 'Immunizations' tab, click 'Add Vaccine' and observe the dropdowns 'Vaccine name' and 'Vaccine manufacturer'.

### Actual Behavior

The dropdowns for 'Vaccine name' and 'Vaccine manufacturer' are not populated with the vaccines and vaccine manufactures associated with Covid-19.

### Expected Behavior

The dropdowns 'Vaccine name' and 'Vaccine manufacturer' should be populated based on the disease of the associated case when processing a 'Physician's report'.

### Screenshots

GIF of the steps to reproduce:
![Vaccines](https://user-images.githubusercontent.com/96909231/177155926-ad912679-a4c3-4d85-b2dd-206603690a70.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(f27f906)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Similar behavior is reproducible when the disease of the case is first set to Covid-19, and then updated to any other value -> the 'Vaccine name' and 'Vaccine manufacturer' dropdowns remained populated with the values associated with Covid-19.

**Comment by FredrikSchaeferVitagroup** [comment]
I'm not sure about the expected behaviour described above. Think of the following scenario: As a processing user, you select a COVID-19 case, and add a vaccination with a COVID-19-specific vaccine name. After that you change the disease of the case. What shall happen with the vaccination created? The only options I see inculde removing data without that being properly visible to the user. Also, this might become rather complex.

I suggest to just disable the disease field when editing the case while processing physician's reports. The disease can be set when creating the case. This would have the downside that you can not select a case with a different disease and then change it while processing physician's reports. But I think that is a very rare use case.

@kwa20 What do you think?

**Comment by adinaflorea9** [comment]
@FredrikSchaeferVitagroup Thank you for taking a look over the ticket and the behavior!

I can see that you have mentioned in your comment the creation of vaccines at the actual time of the processing of the message, but in the steps to reproduce from the ticket, I did not mention that a vaccine would need to be created or saved, before changing the disease of the case. Therefore, no vaccines for other diseases would need to be removed.

However, if the real life user flow is more likely to be that the user would actually create a vaccine and then update the case disease, then please proceed as you and @kwa20 think is best for this scenario.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup @adinaflorea9 I think what happens here is that the disease set in the immunization which is related to the vaccinations depends on the disease which is initially chosen when creating the case. The selection options for vaccine related fields depend on the disease in the immunization. Theoretically it will always also have to change if we edit the disease of the case which seems a bit pesky and might result in additional immunizations and vaccinations being saved even if it's unlikely.

I think the suggestion to make the disease field non-editable while processing further is a good solution.

**Comment by FredrikSchaeferVitagroup** [comment]
Should be testable on a local SORMAS-DEMIS setup, or on test-de2 (once the changes are deployed there).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.74.0-SNAPSHOT(862fbe4). 

Expected behavior has been met - 'Disease' filed on the 'Case page' is no longer editable when processing a 'Physician's report', once the disease has been set, the user clicked 'Save' and proceeded to the 'Process message' form.
