### ISSUE TITLE
[DEMIS2SORMAS] Adjust the mapping for the disease in external messages [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9733]
### Problem Description

Currently, when physician reports are fetched, the `testedDisease` column is empty and the users gets prompted with a message that the disease could not be determined. Since physician reports do not contain information about the tested disease but rather a diagnosis, the column does not quite fit what is needed here. At the same time, differentiating between a tested and diagnosed disease might clutter the directory and might not be necessary.
### Proposed Change

- [x] Rename the testedDisease column in external messages (DB and UI) to disease in the database and the UI
- [x] Map [Condition.code.coding.code](https://simplifier.net/guide/Implementierungsleitfaden%20f%C3%BCr%20DEMIS%20Arztmeldung/Home/resources/structuredefinitions/disease/guide-diseasecvdd.guide.md?version=current) from physician reports to `disease`
    - `cvdd` > `CORONAVIRUS` => https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/72

### Acceptance Criteria

- The column and strings are correctly renamed to "Disease"
- The disease of the physician report is displayed in the messages directory list when given
- The disease is mapped to the `CaseData.disease`
### Additional Information

Consider this ticket in regards to changes in https://github.com/hzi-braunschweig/SORMAS-Project/issues/9646 and https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/64

**Comment by abrudanancuta** [comment]
Validated on local environment with the version: 1.77.0-SNAPSHOT (1b4633c)
