### ISSUE TITLE
Add userroles table to database export [1]

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9734]
### Problem Description

When exporting userroles in the database export in SORMAS, only the assigned users to the userroles is exported.
#### Steps to Reproduce:

1. Open the database export tab
2. Check userroles
3. Export the table
4. Check the content

### Proposed Change

Add the missing tables concerning users (at least `userroles` and `userroles_userrights` are missing).

### Acceptance Criteria

- [x] The userrole table should be contained in the database export.
- [x] Any other additional database table concerning users should not be missing from the database export

### Implementation Details

The following tables are currently not covered:
- userroles
- userroles_emailnotificationtypes
- userroles_smsnotificationtypes
- userroles_userrights

### Additional Information

* SORMAS version: 1.73.1
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user 
* #4461 refactored the userroles but did not specify to cover the database export.

**Comment by StefanKock** [comment]
Actually, the database export does what is expected: It exports the association of users to user roles.
But the export of the actual userrole table is currently missing. I'm converting this ticket to cover that.

**Comment by FredrikSchaeferVitagroup** [comment]
It is not yet really clear to me what is expected here.
Is it:
- The export view in the UI shall not change. When a user checks the `User roles` to be exported, then the `userroles` table shall automatically be included in the export (in addition to the currently exported `users_userroles`?

Or 
-  Additional user roles related tables (e.g. `userroles` and `userroles_userrights`) shall be visible and selectable in the export view?

Or something else?

**Comment by kwa20** [comment]
@StefanKock @FredrikSchaeferVitagroup The general requirement of the database export is to export the database tables according to how they exist in the database. When selecting "User roles", I would expect to export the database table for userroles but not the association between users and userroles.

I guess that the error here now is that `User roles` checkbox exports the `users_useroles` table.

Additionally, tables that were either added or changed via #4461 are missing. I'm not exactly sure what changed but judging by the comment above these are:
- `users_userroles`
- `userroles_userrights`

Since these are separate tables, they would need independent options for the export

**Comment by FredrikSchaeferVitagroup** [comment]
The `userroles_userrights` table was added 2018 through #830 . The `users_userroles` as well. So these tables are really not something new. 
Anyway, when the export view shall provide options matching the database structure, I agree that all those tables `users`, `users_userroles`, `userroles_userrights` should be downloadable and named appropriately.

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas 1.74.0-snapshot on local setup
