### ISSUE TITLE
Finalize LBDS testing

### ISSUE THREAD

**Issue by syntakker** [hzi-braunschweig/SORMAS-Project#9739]
### Problem Description

Test LBDS demo.

A final issue has been identified in the missing transmission of the server response from the LBDS service app to the SORMAS app after LBDS synchronization of cases or persons.

### Proposed Solution

A new version lbds-service-app-0.1.10.apk has been supplied by crowdcode. The test has to be repeated with this new version (test system: https://lbds.sormas.netzlink.com)

**Comment by StefanKock** [comment]
As dicussed in the daily: This ticket is not mandatory for 1.74.0

**Comment by syntakker** [comment]
When testing withe newer Android versions (11.0 / API level 30), the SORMAS app was unable to detect whether the LBDS app is installed on the device. This is due to a limitation to query packages from other apps introduced with Android 11, a solution is described here:
https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9

Thus, the SORMAS app's manifest has to be extended to explicitly list LBDS as an app to interact with.
