### ISSUE TITLE
[User Rights] Users without EVENT_VIEW rights are able to see, open and edit Event-related Tasks

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9748]
### Bug Description

The users without EVENT_VIEW user rights are able to see, open and edit Event-related Tasks, even if they have no connection to the Task (the task is not 'assigned to' or 'observed by' that user);
This is also reproducible for:
- CONTACT_VIEW
- CASE_VIEW

### Steps to Reproduce

1. Make sure that you have created some Event-related Tasks that are not assigned to or observed by a user that has no Event View rights (ex. POE NatUser);
2. Log in with a POE National User;
3. Navigate to the Tasks Directory and inspect the Tasks entries; open a task that has 'Event' as Task Context;
4. Edit the Task and Save;

### Expected Behavior
The user shouldn't be able to see the tasks in the first place;

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/177542268-8b0a9f72-4c1c-43c8-b3c7-adb862724b2f.png)
![image](https://user-images.githubusercontent.com/89522688/177544230-53d8b7f4-c6ce-4943-9dfc-dbfaec68254b.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.74.0-SNAPSHOT (5812ecd)
* Android version/Browser: Chrome
* Server URL: local environment
* User Role:

**Comment by roxanamlendea** [comment]
Reopening the ticket because now the user can no longer see the event-related tasks that are assigned to him.
After a discussion with @MateStrysewske , we decided that the user should be able to see and edit the tasks that are assigned to them (or observed by).

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(59b6b90).
