### ISSUE TITLE
Move functional information from toString to getCaption methods II [5]

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9759]
### Problem Description

Follow-up to #8314: Not all DTOs were covered.

### Proposed Change

- [x] 1. Check and document which classes need to be handled. Refine before to know the effort beforehand.
```
  - DashboardEventDto
  - SystemEventDto - should this be edited ?
  - ContactReferenceDto.PersonName
  - EventIndexDto.EventIndexLocation
  - JournalPersonDto
  - MapContactDto
  - SimilarPersonDto

  - android sync log - should it remain as it was or use the new toString - class + uuid only ?
```

- [x] 2. Adjust `toString` to the usual class + uuid pattern.
- [x] 3. Adjust now not properly formatted values in the vaadin-app (grid columns, selects, maybe labels)
- [x] 4. Adjust now not properly formatted values in the android-app?

### Acceptance Criteria

- [ ] No JPA entity class and no DTO exposes sensitive data in `toString`

### Implementation Details

List of (super-) classes that need to be changed:
1. `ReferenceDto`
2. In the android-app all subclasses of AbstractDomainObject need to be checked (for example `Person`).

Idea: Introduce Interface `HasCaption` for formatting `EntityDto` and `ReferenceDto` classes to ease the use of `CaptionRenderer`.

**Comment by StefanKock** [comment]
Decided in the Planning this ticket might accidently break anywhere in the UIs, so we will move it to 1.79: Merge early and do a lot of UI reviews.

**Comment by leventegal-she** [comment]
Reponening because the component columns are not rendered correctly
![image](https://user-images.githubusercontent.com/62599627/211824140-e6d942d0-71cd-47d0-92b4-fdd0eeaa0b30.png)

**Comment by adinaflorea9** [comment]
I think that the user roles might have been affected by this ticket as well, as their user role names that we had predefined before (such as National User, Admin, etc) are no longer visible but instead we have some uuids:
![image](https://user-images.githubusercontent.com/96909231/212026565-4dfbddf5-2e20-4fe5-ae77-9a4f829e3be5.png)

**Comment by adinaflorea9** [comment]
Observed with @abrudanancuta that the Shares directory was affected as well:
![image](https://user-images.githubusercontent.com/96909231/212272095-4f409e78-0e25-4834-90f1-c595053a0e83.png)

**Comment by abrudanancuta** [comment]
The problem for directories Shares and Messages was fixed

**Comment by abrudanancuta** [comment]
The same problem appears for Configuration directory, for the tabs:

-**Subcontinents**: The column name of the **Continent** is malformed
-**Countries**: The column name of the **SubContinent** is malformed
- **Regions**: The column name of the **Country** is malformed
- **District**: The column name of the **Region** is malformed
- **Communities**: The column name of the **Region** and **District** is malformed
- **Facility**: The column name of the **Region, District, Community** is malformed
- **Points of entry**: The column name of the **Region** and **District** is malformed

**Comment by adinaflorea9** [comment]
Later edit - the same happens for community as well, in the same place mentioned in comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/9759#issuecomment-1383761614

**Comment by abrudanancuta** [comment]
At detailed export file for Case, Contact the column Reporting UserRole is malformed.
[sormas_kontakte_2023-01-18_.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/10444579/sormas_kontakte_2023-01-18_.csv)
[sormas_fälle_2023-01-18_.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/10444598/sormas_falle_2023-01-18_.csv)

I will reopen the ticket

**Comment by abrudanancuta** [comment]
Validated on test.sormas with the version: 1.79.0-SNAPSHOT (ef8ee0a)
