### ISSUE TITLE
Pop-up Window "Discard Unsaved Changes" appears always and is cut in German language

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9773]
### Bug Description

Headline of pop-up Window "Discard Unsaved Changes" is cut in German Language. 
Pop-up-window is also visible if no change has been done.

That is a problem, because the user has no chance to choose a source case without bad feeling.
That is also a problem, because the user will not take the pop-up-window seriously in the future. 

### Steps to Reproduce

1. Create a new contact
2. Click **directly** on "choose source case"
3. Pop- up- window "Discard Unsaved Changes" appears
4. Click on "no"
5. Scroll down and **save** contact.
6. Click again on "Discard Unsaved Changes"
7. Pop- up- window "Discard Unsaved Changes" appears
8. Change the language to german language
9. Headline of pop-up-window is cut

### Expected Behavior

Pop-up window should only appear if there are really unsaved changes.
### Screenshots

english:
![image](https://user-images.githubusercontent.com/100844689/177800924-38214e5b-9816-49f8-9c68-8580e0436e70.png)

german:
![image](https://user-images.githubusercontent.com/100844689/177801099-490252be-94ac-41ab-ba86-922349326a7d.png)

### System Details

* Device: Windows 11
* SORMAS version: 1.73.1
* Android version/Browser: Edge
* Server URL: release-sormas-x
* User Role: admin

### Additional Information

With https://github.com/hzi-braunschweig/SORMAS-Project/issues/9125 this field will be used more than it is used now

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(cfb7eb0).
