### ISSUE TITLE
Disease change saving via the 'Unsaved Changes' pop-up is not taken into account for vaccinations

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9777]
### Bug Description

When changing a case's disease and then using the 'Unsaved changes' pop-up to save the changes, the 'Vaccine name' and 'Vaccine manufacturer' are not updated on the 'Vaccination' form.

### Steps to Reproduce

1. Open an existing case that has the disease set to any other value than Covid-19;
2. Change the disease to Covid-19;
-> 'Change case disease' pop-up is triggered;
3. Click 'Really change case disease?' button;
4. Click the 'New vaccination' button;
-> 'Unsaved changes' pop-up is triggered;
5. Click 'Save changes';
6. Observe the 'Vaccine name' and 'Vaccine manufacturer' dropdowns.

### Actual Behavior

'Vaccine name' and 'Vaccine manufacturer' dropdowns are not populated with values associated with vaccine for Covid-19.

### Expected Behavior

'Vaccine name' and 'Vaccine manufacturer' dropdowns should be populated with values associated with the disease of the case.

### Screenshots

GIF of the steps to reproduce:
![Case change disease](https://user-images.githubusercontent.com/96909231/177951900-ec552455-abe1-4923-a485-d22d6bb4a713.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.74.0-SNAPSHOT(a3a5719)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Reduced immunization module needs to be enabled on the environment for this to be reproducible.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.75.0-SNAPSHOT (57eaaf2)
