### ISSUE TITLE
Avoid circular Eventparticipant join

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9779]
### Problem Description

In #9753 we see still slow performing sample directory queries. The reason is a userFilter join `Eventparticipant -> Event -> EventParticipant`, basically building a circle over all event participants.

Copied from https://github.com/hzi-braunschweig/SORMAS-Project/issues/9753#issuecomment-1178796850:
<details>
<summary>In-depth analysis</summary>

We received an analysis that shows a cartesic explosion from ~8_000 lines to ~8_000_000 lines because of duplicate join to event participants: https://explain.dalibo.com/plan/U6t#plan/node/6

```sql
LEFT OUTER JOIN EventParticipant eventparti11_ ON sample0_.associatedEventParticipant_id=eventparti11_.id
LEFT OUTER JOIN EventParticipant eventperso15_ ON event12_.id=eventperso15_.event_id  -- additional
LEFT OUTER JOIN cases case16_ ON eventperso15_.resultingCase_id=case16_.id  -- additional
LEFT OUTER JOIN contact contacts17_ ON case16_.id=contacts17_.caze_id  -- additional
```

```bash
# Problem
EventParticipant -> Event -> EventParticipant -> Case -> Contact
11                  12       15                  16      17

# Probable Solution
EventParticipant -> Event
11                  12   
EventParticipant -> Case -> Contact
11                  16      17
```

</details>

### Proposed Change

Make sure that joins from `Eventparticipant -> Event -> Eventparticipant` reuse `Eventparticipant` to avoid circle.

### Acceptance Criteria

 - [x] circle join of event participants is removed.
 - [x] Performance of queries is proven to be faster

### Implementation Details

Probably a one liner in EventParticipantJoins:

```java
	public EventJoins getEventJoins() {
// bad		return getOrCreate(eventJoins, () -> new EventJoins(getEvent()), this::setEventJoins);
		return getOrCreate(eventJoins, () -> new EventJoins(getRoot(), getEvent()), this::setEventJoins);
	}
```

### Additional Information

- In #8747 we attempted to get catch all not reused joins, but this one was not found.
- Ths problem affects definitely the sample directory, but likely event related exports and search for matching event participants and similar persons.
- Needs probably be hotfixed, but we need to decide on which versions to backport.

**Comment by StefanKock** [comment]
I checked the SQL with extended `SampleFacadeEjbTest.testGetIndexList`.

<details>
<summary>Comparison of SQL before/after</summary>

```sql
-- Before
LEFT OUTER JOIN EventParticipant eventparti11_ ON sample0_.associatedEventParticipant_id=eventparti11_.id
LEFT OUTER JOIN EVENTS event12_ ON eventparti11_.event_id=event12_.id
LEFT OUTER JOIN LOCATION location13_ ON event12_.eventLocation_id=location13_.id
LEFT OUTER JOIN District district14_ ON location13_.district_id=district14_.id
LEFT OUTER JOIN EventParticipant eventperso15_ ON event12_.id=eventperso15_.event_id
LEFT OUTER JOIN cases case16_ ON eventperso15_.resultingCase_id=case16_.id
LEFT OUTER JOIN contact contacts17_ ON case16_.id=contacts17_.caze_id
LEFT OUTER JOIN Person person18_ ON eventparti11_.person_id=person18_.id
```

`eventperso15_`  is removed.
```sql
-- After
LEFT OUTER JOIN EventParticipant eventparti11_ ON sample0_.associatedEventParticipant_id=eventparti11_.id
LEFT OUTER JOIN EVENTS event12_ ON eventparti11_.event_id=event12_.id
LEFT OUTER JOIN LOCATION location13_ ON event12_.eventLocation_id=location13_.id
LEFT OUTER JOIN District district14_ ON location13_.district_id=district14_.id
LEFT OUTER JOIN Person person15_ ON eventparti11_.person_id=person15_.id
LEFT OUTER JOIN cases case16_ ON eventparti11_.resultingCase_id=case16_.id
LEFT OUTER JOIN contact contacts17_ ON case16_.id=contacts17_.caze_id
```

</details>

**Comment by StefanKock** [comment]
Update: Improvement proven: https://explain.dalibo.com/plan/bCca
- Execution time: 250ms
- Planning time: 24,3ms

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(225dd5c).
