### ISSUE TITLE
Infrastructure export cannot be re-imported on another (clean) instance as DB ids are not stable

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#9786]
### Bug Description

While working on #9740, I wanted to setup my local system to reflect the infra structure data of Traunstein. Although I received their exported CSVs, I was not able to prepare a local test environment. The problem here is that e.g., the districts export reference the region by database ID. However, these IDs are not stable and while importing a region, SORMAS will pick its own IDs from the sequence which do not correctly match the ID exported in the `region_id` column of the district CSV. This results in crashed imports and might introduce wrong references if the crash does not happen on first item and ids coincidentally match.

Second minor issue is that the first line of the exported files always have to be removed manually before importing, we should just not emit this header in the first place.

### Steps to Reproduce
1. Import standard continents and subcontinets
2. Import countries and regions from the attached CSVs
3. Import district: This will fail
4. Check the logs and see that the `region_id` of the failing district does not match the ID of the correct entry in the DB

### Expected Behavior
Exported infra CSV files can be imported without problems in a fresh system.

### Additional Information

Exposing DB identifiers is considered bad for exactly the reason highlighted in this issue. We should rely on UUIDs as they uniquely identify an item and do not incorporate internal state of a system. The export/import mechanism should be refactored such that it references are UUID based.

**Comment by JonasCir** [comment]
@Jan-Boehme and @JaquM-HZI : This makes debugging S2S preparations much harder and time consuming.

**Comment by MateStrysewske** [comment]
@JonasCir Are you talking about the import and export in SORMAS itself? Because if yes, we don't include IDs in the CSV there and when importing e.g. districts, they get matched with the region by name, not by ID.

If you're talking about import via central or anything like that, the issue description and title don't really make that clear.

**Comment by JonasCir** [comment]
@MateStrysewske I checked the export and you are right! Apparently, I received a DB dump as spreadsheet or the DB export which included the DB IDs without me being aware that it was a not a normal export. Apologies, this can be closed then.
