### ISSUE TITLE
Sample edit right 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Project#979]
We notice that once a sample is added to the platform even as admin you are not able to edit the sample

**Comment by MateStrysewskeSym** [comment]
@foyiri @dta16 This is true for fields like shipment date that can only be edited by the user who has created the sample. I'm currently working at the extended Laboratory functionality for the case management component and have already allowed Admins to edit all fields of samples, no matter who created them (this is not live yet, only on my development system). Are there other user roles that should always be able to edit these fields, e.g. Surveillance Supervisors?

**Comment by foyiri** [comment]
i think we should also allow the surveillance supervisor to Edith the sample part because the oversee everything in the platform

**Comment by MateStrysewskeSym** [comment]
This has been done in the latest development build and will be fixed with the next release.
