### ISSUE TITLE
S2S_Documents should be visible, downloadable and deletable after share [5]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9804]
### Problem Description

After a case/contact has been shared with hand over the ownership the source system can not download or delete their documents. That is a problem, because the health departments still need access to their documents. 
### Proposed Change

After a share with hand over the ownership the source system still can see, download and delete their documents.
### Additional Information

Upload of the documents should not be possible for the sending instance anymore.
~~Deleting the documents should not be possible for the sending instance anymore.~~

Refactoring is needed in order to disable the page but let the documents side component accessible.
Instead of making the whole View disabled we should disable it's child components (form + side components)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by dragosb-vg** [comment]
Validated on test.de1. <-> test.de2 (sharing cases in both directions) for multiple user roles on Version: 1.776.0-SNAPSHOT ([f72f48a](url:https://github.com/hzi-braunschweig/SORMAS-Project/commits/f72f48a33abeb92664567b5b62e770c05b40fd11))
