### ISSUE TITLE
S2S_Case ID/Contact ID should be clickable and open case/contact afterwards [2]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9807]
### Problem Description

Currently it is not possible for a user to open a case or contact by clicking on the case ID /contact ID in the 'share request details' pop-up window. That is a problem because the user is accustomed to this behaviour. Furthermore this is the only option for the user to open a case/contact after accepting a share (if he/she does not want to search for it manually in the case/contact directory).
 
### Proposed Change

**_After_** successful acceptance of the share, the case/ contact can be opened by clicking on the case/contact ID.

### Implementation Details

- It can only be clicked and navigate to the page, when the case/contact exists in the system.
- If the case/contact does not exist, you get a popup that says that you have to accept the share request first

### Additional Information

![image](https://user-images.githubusercontent.com/100844689/178289374-793e9b26-4d61-4dd8-9887-d61cee2af94a.png)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by AndyBakcsy-she** [comment]
Validated ticket on the latest version of sormas deployed on S2S test instances test-de1 and test-de2
