### ISSUE TITLE
TravelEntryDataForm: DirtyCheckPopup is triggered twice

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9811]
### Bug Description

When leaving a travel entry form without saving changes, the `DirtyCheckPopup` is triggered twice.

### Steps to Reproduce

1. Got to travel entries directory and open an existing travel entry.
2. Change a value in form, don't save.
3. Click on travel entries directory in the menu (or any other function that triggers leaving that form).
4. Discard the appearing `DirtyCheckPopup` once (expected).
5. A **second** `DirtyCheckPopup` appears. Discarding that lets you leave the form.

### Expected Behavior

Only one  `DirtyCheckPopup` appears.

### System Details

* SORMAS version: 1.73.1, 1.74.0-SNAPSHOT
* Android version/Browser: Firefox
* Server URL: https://release-de.sormas.netzlink.com , https://test-de2.sormas.netzlink.com
* User Role: National User

### Additional Information

- I did not find this behaviour on travel entry person form or sample data form, did not check more forms.
- Found by https://github.com/hzi-braunschweig/SORMAS-Project/issues/9435#issuecomment-1175880462

**Comment by adinaflorea9** [comment]
From the same comment from ticket #9435 (from where the beahvior described in this current ticket was moved from) regarding travel entries, please also check that the behavior from the following flow is covered:

1. open an existing travel entry;
2. make a change on the travel entry page;
3. click 'Delete';
4. click 'Save Changes' in the 'Confirm navigation' pop-up;
=>error message appears:
![image](https://user-images.githubusercontent.com/96909231/178508575-8714bbca-1bdd-4797-b074-e6039696be3c.png)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.79.0-SNAPSHOT(7a9ba5b).
