### ISSUE TITLE
Insufficient fields and options to capture Meningitis (CSM) cases

### ISSUE THREAD

**Issue by faatihi** [hzi-braunschweig/SORMAS-Project#982]
While entering line list data for CSM in Ghana, we came across these fields and options that are not available in the application.

Missing Fields:
- [ ] Serogroup/Serotype

Missing Options:
- [ ] Test Types: 
   - [ ] Gram Stain
   - [ ] Latex Agglutination
   - [ ] CQ Value Detection
- [ ] Test results for test type PCR
   - [ ] Pneumoniae
- [ ] Symptoms
   - [ ] Neckpain

@hzi-braunschweig @MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
@faatihi Results from HZI

For neckpain pelase use the symptom called "stiff neck".

- [ ] Add serotype as a new text field to the pathogen test. It should only be visible for positive tests in CSM cases
- [ ] Add new test type "Gram stain"
- [ ] For the pathogen test we should split the existing test type to test type and test disease. The test disease is a combination of all the sormas diseases and additional diseases like west nile, pneumoniae and malaria.

To be defined by HZI

- [ ] What about Latex Agglutination?
- [ ] How to document CQ value (new field?)

See also https://github.com/hzi-braunschweig/SORMAS-Project/issues/909#issuecomment-469248156

**Comment by bernardsilenou** [comment]
CQ as well as CT are attributes of the machine that tell us the number of cycle at which fluorescence ie  "light signal" of the nucleotide/ piece of DNA strand could be detected by the machine. We decided not to create a separate field for the CQ values but added the field called "specify test details" for user to fill in all machine specific attribute of the test.

For Latex Agglutination, I suggest that we add it among the test type. It is also a method to detect antibodies or antigens.

**Comment by hzi-braunschweig** [comment]
@bernardsilenou Thanks Bernard

**Comment by hzi-braunschweig** [comment]
From Dr Franklin
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Dear Daniel,
Reference to tour mail on the above subject  kindly find below the information
         What about Latex Agglutination?
 
 How to document CQ value (new field

1. On the Latex Agglutination test : It is the rapid test for Bacterial Meningitis or An assay used clinically in the identification and typing of bacterial meningitis
2. CQ value is the threshold value for each bacteria pathogen in a multiplex PCR assay

Please Note:
The CQ value is not routinely reported, however the Latex Agglutination test is very commonly performed using Pastoex or Wellcogen.

Thanks.

Franklin

**Comment by faatihi** [comment]
> @faatihi Results from HZI
> 
> For neckpain pelase use the symptom called "stiff neck".
> 
> * [ ]  Add serotype as a new text field to the pathogen test. It should only be visible for positive tests in CSM cases
> * [ ]  Add new test type "Gram stain", "Latex Agglutination", "CQ Value Detection"
> * [ ]  Add new field "CQ Value", only visible for CQ Value Detection tests
> * [ ]   Add "Pneumoniae" as a new secondary disease
> 
> See also [#909 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/909#issuecomment-469248156)

In the first task (adding serotype), I'm not clear about what the "CSM cases" refer to. 
Is it when a case is a CSM case (that's my understanding):

![image](https://user-images.githubusercontent.com/1176692/64105231-5dc39300-cd65-11e9-83d4-144ed1c2c0b6.png)

Or when CSM is selected as the Tested Disease on the "Create new pathogen test result" form:

![image](https://user-images.githubusercontent.com/1176692/64105283-73d15380-cd65-11e9-9bdb-97bfed5b4057.png)

**Comment by MateStrysewskeSym** [comment]
Your second assumption is correct, I wrote that down incorrectly. The tested disease should always be the one taken into account for this. I'll change the comment above accordingly.

**Comment by faatihi** [comment]
Thanks

**Comment by faatihi** [comment]
After Dr. Franklin's response, is there anything to add or subtract from our initial proposed implementation? 
I'm displaying CQ Value only for CQ Value Detection tests, but Dr. mentioned some other diseases when explaining the CQ Value field.

> @faatihi Results from HZI
> 
> For neckpain pelase use the symptom called "stiff neck".
> 
> * [ ]  Add serotype as a new text field to the pathogen test. It should only be visible for positive tests with CSM as the tested disease
> * [ ]  Add new test type "Gram stain", "Latex Agglutination", "CQ Value Detection"
> * [ ]  Add new field "CQ Value", only visible for CQ Value Detection tests
> * [ ]   Add "Pneumoniae" as a new secondary disease
> 
> See also [#909 (comment)](https://github.com/hzi-braunschweig/SORMAS-Project/issues/909#issuecomment-469248156)

**Comment by MateStrysewskeSym** [comment]
@faatihi Since we currently don't restrict test types by disease, users will essentially be able to do CQ value tests for all diseases anyway. We will definitely refine this system later on, but for now, this should not be an issue.

**Comment by faatihi** [comment]
OK

**Comment by faatihi** [comment]
Oh, pardon me. I meant Dr. mentioned some other **test types**. But the system limits the CQ Value only to "CQ Value Detection". But as you said, we can refine that when the need arises.

**Comment by faatihi** [comment]
May I know what I'm supposed to do with (or pick from) issue #909 ? It is referenced in the implementation guide

**Comment by MateStrysewskeSym** [comment]
@faatihi You don't have to do anything since that issue is closed. It's only for reference because some things that made it into this issue were discussed there.
