### ISSUE TITLE
Prevent submission of future aggregate  reports [1]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#9822]
### Problem Description

mSERS module permits users to notify aggregate case counts. A user can mistakenly chose a future week and notify a report.
### Proposed Change
 
~~Show a warning message and prevent users from reporting future reports if the report week is in the future of the current calendar week~~

=> Show only EPI-weeks from the past where you can select the "from" epi-week

**Comment by adinaflorea9** [comment]
Verified ticket on https://test.sormas.netzlink.com where SORMAS version is 1.75.0-SNAPSHOT(ad3cd54).
