### ISSUE TITLE
GPS could not determine the address in Mobile app

### ISSUE THREAD

**Issue by zohaibhassan122** [hzi-braunschweig/SORMAS-Project#9833]
### Bug Description

Whenever you try to fill out  address using GPS coordinates, it gives an error, even GPS in enabled in mobile device and app has access to GPS. 
### Steps to Reproduce

1. Go to the case directory and select any case.
2. Open the person information tab
3. Tap on ✏️ icon to open form
4. In the "Home Address" section, tap on "+ NEW"
5. Tap on "pick current GPS for address"
6. Confirm your current location following the confirmation alert pop-up 

### Expected Behavior

You will see an error on top "No GPS coordinates could be found"

### Screenshots

![Screenshot_20220601-095937_APMIS (1)](https://user-images.githubusercontent.com/8872102/178732187-8b661ee8-0b4b-450a-b41b-6d63762bd517.jpg)

### System Details

* Device: SAMSUMG Glaxy TAB A8
* SORMAS version: 1.73.2
* Android version: 1.73.2
* Android Version: 11
* User Role: Hospital Informant
* URL: https://release-international.sormas.netzlink.com/

### Additional Information

Error log from Mobile Device

07-13 11:10:24.068  1064  1084 E WindowManager: win=Window{736da7f u0 de.symeda.sormas.app/de.symeda.sormas.app.caze.edit.CaseEditActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5713 com.android.server.wm.ActivityRecord.destroySurfaces:5694 com.android.server.wm.WindowState.onExitAnimationDone:5706 com.android.server.wm.WindowStateAnimator.onAnimationFinished:335 com.android.server.wm.WindowState.onAnimationFinished:6179 com.android.server.wm.-$$Lambda$dwJG8BAnLlvKNGuDY9U3-haNY4M.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:112

**Comment by zohaibhassan122** [comment]
FYI: @MateStrysewske
Please have a look on it and if you are also able to reproduce, then I will try to add this issue to next sprint. 
Thanks in advance.

**Comment by MateStrysewske** [comment]
@zohaibhassan122 I suppose the location of your phone doesn't match the country that is retrieved from the locale of the server you're connected to. If the locale is e.g. set to de-DE, you need to physically be in Germany in order to be able to pick GPS coordinates; if the locale is e.g. set to en, you won't be able to pick GPS coordinates at all because there's no clear country associated with the locale en.
