### ISSUE TITLE
S2S_tab 'contacts' is no longer editable when case is in the system for viewing

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9838]
### Bug Description

If the case is in the system for viewing you can not edit the tab 'contacts' anymore, you can not scroll to the right to see all information, you can not open the contacts by clicking on the contact ID. 
### Steps to Reproduce

1. Create a case_1 with a contact_1 on source system
2. Share the case_1 **with** hand over the ownership to the target system
3. Create a second case (case_2) with a contact (contact_2) on source system
4. Share case_2 **without** hand over the ownership to the target system, but include contact
5. Accept both cases on target system
6. Check for case_1 in the source system if the tab 'contact' is editable
7. Check for case_1 in the source system if you can scroll to the right on the tab 'contact' 
8. Check for case_1 in the source system if you can open contact_1 by clicking on the contact ID
9. Check for case_2 in the target system if the tab 'contact' is editable
7. Check for case_2 in the target system if you can scroll to the right on the tab 'contact' 
8. Check for case_2 in the target system if you can open contact_2 by clicking on the contact ID

### Expected Behavior

If the case is in the system for viewing you still can edit the tab 'contacts' (for example click: import, export, + line listing, + new contact).
If the case is in the system for viewing you still can scroll to the right on the tab 'contacts' and see all table columns.
If the case is in the system for viewing and have attached contacts you can still open the contacts by clicking on the contact ID if you have opened the tab 'contacts'.
### Screenshots

![S2S_tab contacts](https://user-images.githubusercontent.com/100844689/178789890-e75f80df-cdab-4da4-8a4a-6a195d97fbc3.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.73.2
* Android version/Browser: Edge
* Server URL: release-de and release-sormas-x
* User Role: admin

### Additional Information

I tested this on Version 1.70. Prove me wrong, but I am pretty sure it was possible back then to edit the tab 'contacts', because my documentation says so. Please check what has changed since then.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by JonasCir** [comment]
QA: Since this is a regression, can we get an automated UI test for this?

**Comment by AndyBakcsy-she** [comment]
Verified ticket on the latest version of sormas during a peer testing session with Levi
