### ISSUE TITLE
Lab Officer not able to see case a he/she enters

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#984]
1. The lab officers have cases coming in from states where we have not deployed yet.
2. when they enter a case, it goes into the database but without the lab linkage
3. searching the system from their log-in access does not bring up that case because sample details have not been entered yet. Only when a sample is created for the case does the case get linked and visible to the lab officer. 
4. Is it possible for the user-right access to see the instance of a case entered by them to enable them link it to the lab?

**Comment by Chinedar** [comment]
This is fine now. All they need to do is link the case to their lab by going to case tab and inputting sample details.

**Comment by MartinWahnschaffeSymeda** [comment]
Actually the exact user that created the case should be able to see it - even when it's a lab user and now sample has been added. We will have a look into this.

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar Found the problem :-)
