### ISSUE TITLE
[mSERS] Age Groups are not displayed correctly in Edit mode of the Aggregate Reports

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9845]
### Bug Description
When Age Groups are configured for a disease, they are not displayed correctly in Edit mode of the Aggregated Reports.

### Steps to Reproduce

Scenario A:

1. Use the following ageGroupsString: 0D_28D,29D_2M,3M_12M,1Y_4Y,5Y_15Y,16Y to configure the Age Groups for Diphteria disease;
2. Navigate to the mSERS Directory, select the Report Data tab and click on New Aggregate Report;
3. Insert a value for '0-28 days' and Save the form;
4. Open the Aggregate Report and inspect the entries.

Actual Behavior:
-> only the '0-28 days' Age Group is displayed;

Expected Behavior:
-> all the Age Groups configured in the DB should be displayed.

Create new Aggregate Report form:
![image](https://user-images.githubusercontent.com/89522688/178929113-f2a4f8e4-bdf9-4054-bf6a-0cdbb8fca5de.png)

Edit Aggregated Report form:
![image](https://user-images.githubusercontent.com/89522688/178929374-62925d97-381d-4b31-9e77-21c8191c9973.png)

Scenario B:
1. Use the following ageGroupsString: 0D_28D,29D_2M,3M_12M,1Y_4Y,5Y_15Y,16Y to configure the Age Groups for Diphteria disease;
2. Navigate to the mSERS Directory, select the Report Data tab and click on New Aggregate Report;
3. Insert a value for the last age group (16+ years) and Save the form; (the issue is reproducible with values for the last age group)

Actual Behavior:
-> the name of the disease (Diphteria) is not displayed;

Expected Behavior:
-> the name of the disease (Diphteria) should also be displayed;

![image](https://user-images.githubusercontent.com/89522688/178933374-44e9cf31-08ea-47c6-af34-8935c6c43f9e.png)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.74.0-SNAPSHOT (7e4e9eb)
* Android version/Browser: Chrome
* Server URL: local env
* User Role: Admin, NatUser

### Additional Information
This bug was observed while testing ticket #9119, but is probably related to ticket #8967.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(4394d4b).
