### ISSUE TITLE
Make region and district required for aggregate reports [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9847]
## Problem description

Aggregate reports created without a district or even a region are useless.

## Proposed Solution

- [x] Make region and district required for aggregate reports.
- [x] Delete existing aggregate reports that don't have region or district. -> point this out in the release notes!
        (Deletion will be done via DB-Update-Script)

## Additional Information

_Originally posted by @bernardsilenou in https://github.com/hzi-braunschweig/SORMAS-Project/issues/9068#issuecomment-1183833896_

Following https://github.com/hzi-braunschweig/SORMAS-Project/issues/9068#issuecomment-1182988376
I have not tested all the steps but one issue that I see is that an aggregate report can be created without a region or district by a national user for example.
1. Just as cases must have a region and a district, an aggregate report must also have both, no matter the user who created it. we can prevent users from creating such data. because they are useless.
2. The issue that arises when filtering by region would not apply since all reports would have a region and a district.
3. Since the main users who create such reports are SO (having no facility) and informant (having a facility), then we can make facility optional for a report. When grouping by facility, then report with Missing facility would not show up

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(b464ebb).

**Comment by MartinWahnschaffe** [comment]
@sergiupacurariu @MateStrysewske I just realized that we also have to delete those aggregate reports in the mobile app, otherwise we will run into synchronization issue for those.

**Comment by sergiupacurariu** [comment]
@MartinWahnschaffe @MateStrysewske I just tested the whole change starting both web and Android on 1.74.0 adding aggregate reports without regions and / or districts. Moved to develop and redo all the checks.
Situation: 
- from the aggregate reports without regions and/ or districts only those created by the Android user were synchronized to Android
- the synchronization works fine using develop branch, the above aggregate reports are simply not considered anywhere
- a re-synchronization from Settings in the Android app also removes the aggregate reports with missing regions and / or districts
Question:
- considering all above do we still need to proceed to remove them from the Android app using a query?

**Comment by MateStrysewske** [comment]
@MartinWahnschaffe I tend to agree here; the reports without regions/districts would not be shown in the Android app in the first place, hence they would never change, and would therefore also never be synced to the web app again.

**Comment by MartinWahnschaffe** [comment]
You are right. I didn't consider that it's not possible to create reports without district/region in the android app.

**Comment by adinaflorea9** [comment]
As no changes have been made after the ticket was reopened, I am moving it back into the done column. (https://github.com/hzi-braunschweig/SORMAS-Project/issues/9847#issuecomment-1200802164)

**Comment by dbe21** [comment]
@JaquM-HZI @MartinWahnschaffe FYI
I found the following issue: 
Aggregated reports can be saved without selecting a region or district. The report itself is not displayed in the report data table, but the error message, that the user has to enter a valid region and district, only appears, when a value for a disease has been entered. 

![AggregatedReports_NoJurisdiction](https://user-images.githubusercontent.com/83459190/185072069-00a47aa4-760b-4e25-952c-ad5a7906b30e.gif)

**Comment by adinaflorea9** [comment]
@dbe21 The report is not actually created as there are 0 values for all diseases. If the Data Base is checked, it will be visible that no report with that specific data is created. 

When no disease values are entered, the 'Save' button on the form does not save it, as 0 value reports are already 'existing' in  SORMAS (this can be checked from the 'Aggregate reporting' tab - check the 'Show 0 values checkbox' and you should see all the 'reports' that were actually never created but they have 0 values).

**Comment by bernardsilenou** [comment]
@adinaflorea9 
- If region and district are required, then it would be good to activate the save button only after values are provided for region and district.
- It would be good to also add a red asterisk to region and district + show warning message when save icon is clicked withoup providing values for them. Same logic as on the case creation from.
