### ISSUE TITLE
Port Health Module (POE)

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#985]
The Nigerian team had a meeting with the Port Health Services over the activation of the Port Health module of SORMAS. These  are the main points from the meeting for us to  activate  this module in SORMAS:
Point of Entry Meeting – 2.26.2019
User roles to be created
POE Informant same app as Hospital Informant. User-right will be restricted to data coming in from this particular POE (Point of Entry).
POE Supervisor as Surveillance Supervisor. Will be in charge of POE informants working at border posts within the state. User-right restricted to POE data within the state.
POE National as National User. Data from POEs only should be visible to this user. The user can only see cases coming in from points of entry.
Variable requests
CASE INFORMATION
EPID NUMBER: This is valid and will be updated by the Surveillance Officer of the LGA in which the POE is located
CASE CLASSIFICATION: same as above
OUTCOME: same as obtained in Hospital Informant’s app
DATE OF REPORT: same as obtained in HI’s app
DISEASE: the diseases on SORMAS are retained
STATE: same
LGA: same
WARD: to be replaced with “POE TYPE”  (the database will be provided)
HEALTH FACILITY: to be replaced with “POE NAME” (the database will be provided, a cascade of POE type)
PERSON INFORMATION
FIRST NAME, LAST NAME, AGE, GENDER, PRESENT CONDITION to be retained.
The POE team will provide other important variables needed here. What will be displayed is dependent on the POE TYPE selected. E.g. Ground crossing – means of transport (car, bus, motor bike, etc)
Airport – name of airline, flight number, seat number/free seating, departure and arrival time, date of travel, transit information (if any), etc.
Seaport – Vessel name, type of vessel, terminal of departure, terminal or arrival, date of travel, etc.
SYMPTOM INFORMATION
request for this to come before Hospitalization Info which now changes to Referral Information
CURRENT BODY TEMPERATURE: remains the same
SOURCE OF BODY TEMPERATURE: the drop down should give options such as non-contact, digital focal, etc. (the list will be provided).
SYMPTOMS: this changes to SIGNS AND SYMPTOMS (the responses for SIGNS will be provided)
REFERRAL INFORMATION (change hospitalization info to referral info)
The variables here would be “health facility patient is referred to”, “date of reference”, etc. The comprehensive list will be provided.
EPIDEMIOLOGICAL INFO
This is fine the way it is now.
CASE CONTACTS
The POEs only carry out contact listing. Other contact tracing activities are carried out by the DSNO (surveillance officer).
Type of contact “5-was in the same room or house with source case” can be changed to “was in the same conveyance with the source case”
CASE SAMPLES
This is not needed as they do not collect samples
CASE TASKS
This should be retained. POE supervisor and POE national should be able to assign tasks and manage POE informant.

**Comment by Chinedar** [comment]
**More Points from further review with POE team...**

1.      The dropdown for selection of states should be limited to only states that have ports of entry.

2.      Under POE types, only ground crossing, seaport and airport should be captured, waterfront, terminals and vaccination centers shouldn’t be captured.

3.      Places that are not manned by PHS (Port health services) should have their user accounts inactive.

4.      Ground crossing should have a variable for type of conveyance.

      4b. The “type of conveyance” variable should have a selection dropdown with options of “car, bus, motorbike and others”. “Others” because another means of movement other than car, bus and motorbikes could be a means of transport in future.

      4c. Ground crossing should have a variable “coming from” to indicate where the person is coming from.

      4d. Ground crossing should have a variable “final destination” to indicate the location the person plans to settle.

Ground crossing ­→ type of conveyance (car, bus, motorbike and others) → Coming from → Final destination

5.      Airport should have variables “Arrival”, “Name of Airline” → “Flight number” → “Free seating” → “Date and time of departure” → ‘’Date and Time of arrival” →“Departure aerodrome” → “Number of Transit stop”.

     5b. For the “free seating” variable, a selection option of “yes or no” should appear, if “yes” the seat number should be skipped but if “no”, a text where details of the seat number should be provided, should pop up.

    5c. For number of transit stops, a selection dropdown from 0 to 5 should appear. If zero is chosen, there should be no response field but if 1 to 5 are chosen, a response field of “transit stop 1” or ………..”transit stop 5” respectively (depending on the number chosen from 1 to 5) asking for the details of the transit stop should pop up.

 

6.      Seaport should have variables “Vessel name” → “Port of departure” → “date and time of departure” → “date and time of arrival”.

      6b. The variable “Vessel name” should have a dropdown for supplying details of the vessel.

      6c. Last port of call should have a help text or information icon giving an example of how the information should be supplied (Mr. Laolu would supply details on the help text/information icon).

7.      There are still deliberations on the need to remove, change or retain the question on source of body temperature.

8.      The list of symptoms should be retained as it is on SORMAS.

9.      The referral info should be used the way hospitalization info is on SORMAS.

**Comment by bernardsilenou** [comment]
We need to include this as priority in the next sprint

**Comment by MateStrysewskeSym** [comment]
Mockup of "Point of Entry" area:
https://app.moqups.com/3NUENEwuOE/view/page/af5fb407c

Mockups of "New case" popup:
https://app.moqups.com/3NUENEwuOE/view/page/ad4d74e83
https://app.moqups.com/3NUENEwuOE/view/page/a447e9b11

New mockup of "Case information" area (with basic POE information):
https://app.moqups.com/3NUENEwuOE/view/page/afc481082

**Comment by MateStrysewskeSym** [comment]
New user roles:
- [ ] POE Informant (identical to Hospital Informant, only sees cases created from POE assigned to them)
- [ ] POE Supervisor (identical to Surveillance Supervisor, only sees cases created from POEs in their region)
- [ ] POE National User (identical to National User, only sees cases from POEs)

Case changes:
- [ ] Add "Case Origin" field: In-Country, Point of Entry; users who can create both normal and POE cases will see this when creating a case; required
- [ ] Add "POE Type": Airport, Seaport, Ground Crossing
- [ ] Add "POE Name": Either a free text field or a dropdown with an additional details field
- [ ] For POE cases, Community and Health Facility as well as the samples list and the Hospitalization, Therapy and Clinical Course tabs are hidden
- [ ] Add a "Refer POE Case to Health Facility" button to the Case Data area that opens a popup that looks similar to the "Transfer Case" popup and allows the user to set a Community and Health Facility for the case; add a "POE Referred" flag to the database that is set to TRUE when this is done; show all previously hidden data when the POE case has been transfered and still show the POE data
- [ ] Remove requirement from Health Facility (UI and backend, check functions in backend that rely on this field)

**Comment by MateStrysewskeSym** [comment]
Suggestions:
- [ ] Remove "Point of Entry Type", add this as a field to the actual Point of Entry; this would imply to have three "Other" options (one for every POE type)

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig @bernardsilenou We'll need a list of all Point of Entries, ideally for both Nigeria and Ghana, before we can really start to implement this.

**Comment by MateStrysewskeSym** [comment]
@danieltomaba Please define which fields should be hidden from POE users (e.g. case classification, ...)

**Comment by MateStrysewskeSym** [comment]
- [ ] POE Informants should not see the "Disease" field when creating a case; this should automatically be "Not yet defined"

**Comment by hzi-braunschweig** [comment]
> @danieltomaba Please define which fields should be hidden from POE users (e.g. case classification, ...)

@Chinedar Please kindly define these fields that the POE should not see based on the case information. Talk to the POE supervisors and let us know what case information they are allowed to see, else we will shut down the whole case information area to them and only leave POE information
Thanks

**Comment by Chinedar** [comment]
The POE supervisors should only see details of the case as provided by the POE informant. However, if other details cannot be blocked, they should not have edit right to them. 
Thanks.

**Comment by hzi-braunschweig** [comment]
@Chinedar We will need a list. So we can be sure this issue wont arise when they start using it. My suggestion is to talk to the POE folks and ask them for the forms they are currently using and what case information is in it.

**Comment by Chinedar** [comment]
ok

**Comment by MateStrysewskeSym** [comment]
@Chinedar Could you elaborate on what the "Arrival" variable for Airports means? I had a quick phone call with Daniel and he suggested that it's used for asking whether the person was arriving in or departing from the POE, but the absence of a "Destination airport" variable makes me question that a bit. Do you know what exactly should be entered in this field?

**Comment by Chinedar** [comment]
@MateStrysewskeSym I think the only place "arrival" would come up as a variable is "departure and arrival time". I don't think "arrival" would stand alone as a variable. So we would have the "name of the airport" and "departure and arrival time" with departure time seeking to know when the airline left it's last destination and arrival time seeking to know when the symptomatic person came into the POE.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Thanks!

**Comment by MateStrysewskeSym** [comment]
- [ ] Rename all remaining occurrences of "Refer to health facility" to "Refer from point of entry"
- [ ] Remove import code from StartupShutdownService and .csv file from project files -> probably remove poe list in district
- [ ] Move code to set disease to Undefined and case origin to Point of Entry when port health users create a case to build method in CaseDataDto (or just remove it because it's already set in the Controller)
- [ ] Rename "isPortHealthCase" in CaseDataDto to "isUnreferedPortHealthCase"
- [ ] Remove "saveAndReferCase" method and set admission date in Controller
- [ ] Rename DataHelper.getIntegerValues to buildIntegerList
- [ ] Change logic to get user filter for POE National Users (integrate them into the logic used for all other user roles)
- [ ] Retrieve info whether case is transfered or refered based on the status of the case, not based on parameters

Questions:
1. Do POE informants have an assigned officer?
2. Remove "Pending tasks" column?
3. Should POE users see events?
4. What exactly is the process of getting POE cases into the system? Do we need new tasks that are generated for them?

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Please define exactly which fields should not be visible and which fields should not be editable by Port Health users.

**Comment by bernardsilenou** [comment]
This is about sensitive fields that should not be seen by state observers and and  I hope it words also for POE informants:
