### ISSUE TITLE
DashboardService.getCasesCountByClassification: Duplicate CaseClassification.CONFIRMED

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9850]
### Bug Description

If you click on the Contacts button, the following error message appears after a long loading time.

Extract from StackTrace:
```bash
	at de.symeda.sormas.backend.dashboard.DashboardFacadeEjb.getCasesCountByClassification(DashboardFacadeEjb.java:111)
	at de.symeda.sormas.backend.dashboard.__EJB31_Generated__DashboardService__Intf____Bean__.getCasesCountByClassification(Unknown Source)
	at com.sun.proxy.$Proxy640.getCasesCountByClassification(Unknown Source)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)	
...
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.IllegalStateException: Duplicate key Confirmed case (attempted merging values 1494 and 1132)
```

![image](https://user-images.githubusercontent.com/101708230/178939960-7d516d07-5ca6-4769-ba50-a24ce919f992.png)

### Steps to Reproduce

1.
2.

### Screenshots

![Bildschirmfoto 2022-07-14 um 09 53 55](https://user-images.githubusercontent.com/101708230/178939826-105bd90b-c19b-4d8a-90bc-6ae624c78979.png)
![Bildschirmfoto 2022-07-14 um 09 53 14](https://user-images.githubusercontent.com/101708230/178939770-59fd4753-4825-45a9-8426-d7d01b420e7e.png)
![Bildschirmfoto 2022-07-14 um 09 04 09](https://user-images.githubusercontent.com/101708230/178939788-12aa0946-d904-45ab-bf04-0db0933a178a.png)

### System Details

* Device: Laptol / automated Tests
* SORMAS version:  1.74.0 (3087773)
* Android version/Browser:
* Server URL:  https://test-auto.sormas.netzlink.com/
* User Role:  for example admin

### Additional Information

- On https://test-de.sormas.netzlink.com/ the Contacts Dashboard is available. 
- Log: [test-auto.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/9110133/test-auto.log)
- Caused by #9659

**Comment by StefanKock** [comment]
If my analysis is correct #9659 caused this problem and that ticket never could have worked, because it duplicates the map key.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(81bdbe6).
