### ISSUE TITLE
Case, Hospitalization: show "Facility Name & Description"

### ISSUE THREAD

**Issue by KernB** [hzi-braunschweig/SORMAS-Project#9854]
### Bug Description

If "Other Facility" is selected in the Case, Case tab
![image](https://user-images.githubusercontent.com/101708230/178986450-c0e825ce-2cea-47fb-a461-a0293b71e347.png)

in the "Hospitalization tab "Other facility" is displayed only. 
Here also the "Facility Name & Description" should be visible. 
![image](https://user-images.githubusercontent.com/101708230/178986378-9c5989e7-a78b-4fcc-be2c-a99d08f9bccc.png)

### Steps to Reproduce

1.
2.

### System Details

* Device: Laptop
* SORMAS version: 1.73.2
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/ , https://release-international.sormas.netzlink.com/
* User Role: Admin (for example)

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SOMRAS from the development branch - 1.75.0-SNAPSHOT(cfb7eb0).
