### ISSUE TITLE
S2S_Translation for #9125 and #8576 missing

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9856]
### Bug Description

 - [ ] 1. Translation to other languages for the following messages missing:
-You can not share this contact because you need a source case. Please link the contact to a case
-If you want to share this contact, you have to sent the associated case first to the same target system. Please note that you can sent the case and exclude personal data
-The contact X cannot be accepted, because it belongs to case not yet accepted. Please accept the linked case first. It is shared within the request X.
-This contact was sent without a case. That's why you can not accept the contact. Please reject the contact and ask the source system to send the linked case first.

- [ ] 2. Translation to other languages for the following message is missing:
-There is already a pending request to the same organization. Please revoke it before sending a new one.

### Steps to Reproduce

1. See https://github.com/hzi-braunschweig/SORMAS-Project/issues/9125 
2. See https://github.com/hzi-braunschweig/SORMAS-Project/issues/8576

### Expected Behavior

Automatic translation into the language that is set as the User Setting Language.
### System Details

* Device: Windows 11
* SORMAS version: 1.73.2
* Android version/Browser: Edge
* Server URL: release-de and release-sormas-x
* User Role: admin

### Additional Information

examples:
![image](https://user-images.githubusercontent.com/100844689/179000659-75d86727-02fd-4b66-8251-7099fff46efc.png)

![image](https://user-images.githubusercontent.com/100844689/179000045-d3778b0f-66f5-47c7-b241-0b612253462f.png)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by FredrikSchaeferVitagroup** [comment]
I don't see what is to be done here. The i18n strings seem to be present in the translation files of 1.74.0, there already exist german translations.

**Comment by StefanKock** [comment]
> I don't see what is to be done here. The i18n strings seem to be present in the translation files of 1.74.0, there already exist german translations.

Adjusted the ticket type and milestone accordingly.
