### ISSUE TITLE
User name from the 'Visit Origin' column is missing when exporting visits

### ISSUE THREAD

**Issue by adinaflorea9** [hzi-braunschweig/SORMAS-Project#9857]
### Bug Description

When generating an export file of case follow-up visits or contact follow-up visits, the 'Visit Origin' column is showing only the 'Created by user' information but not the actual user as well, as it is displayed in the UI.

### Steps to Reproduce

1. Open a case or a contact and create a follow-up visit for it;
2. Generate an export excel file from the 'Follow-up visits' tab of the case or contact;
3. Observe the 'Visit origin' column of the excel file.

### Actual Behavior

The name of the user that created the visit is not visible in the export file.

### Expected Behavior

The name of the user that created the visit should be visible in the export file.

### Screenshots

Follow-up visits list in the web-app:
![image](https://user-images.githubusercontent.com/96909231/178993399-ac9ac2cf-bee3-4d4f-b949-b6a11a70b48c.png)

Follow-up export excel file:
![image](https://user-images.githubusercontent.com/96909231/178993505-434613a1-886b-4e57-bb36-c76124a2a236.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(7e4e9eb)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

**Comment by ChristopherRiedel** [comment]
Export of the visitUser was never specified, so this is a change not ab bug.

**Comment by adinaflorea9** [comment]
@ChristopherRiedel thank you for letting me know and changing the issue's category.

**Comment by abrudanancuta** [comment]
Validated on local env with the version: 1.75.0-SNAPSHOT (57eaaf2)
