### ISSUE TITLE
[DEMIS2SORMAS] Editing vaccinations while processing physician reports leads to error when saving or discard entries

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9858]
### Bug Description

When vaccinations are edited in the physician processing window, editing causes errors when trying to navigate and saving changes in the unsaved changes prompt. Moreover, the same error appears when pressing "Save and open case". However, when pressing "Save" the case is saved but the edited vaccination discarded.
### Steps to Reproduce

1. Upload and fetch a physician report
2. Process the physician report and create a case
3. In the side by side view, open the immunizations tab
4. Add a vaccination and press done 
5. Edit the same vaccination by opening it via the edit icon
6. Make changes and press done
7. Press the epi data tab > unsaved changes prompt triggers
8. Press save > error appears
9. Cancel the action
10. Press "Save and open case" > error appears
11. Press "Save"
12. Open the saved case and check the vaccinations > The edited vaccination is missing 

### Expected Behavior

Editing the vaccinations in the processing window should work without error.

### Screenshots

![physReportVaccEdit](https://user-images.githubusercontent.com/70317594/178997965-111405a6-1d67-4186-b2e6-42c1c108fa00.gif)
![physReportVaccEditSave](https://user-images.githubusercontent.com/70317594/178997992-102fd802-24fd-4312-8e5b-fda507d60480.gif)

### System Details

* Device:
* SORMAS version: 1.73.2
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

**Comment by abrudanancuta** [comment]
Validated together with @leventegal-she on his local environment
