### ISSUE TITLE
Review of case management module and changes to be made

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#986]
Case management Github logs
-	Bug at text filter under therapy (cant fully type) >- #987 
-	All laboratory components on the case management form should be available to the clinicians
-	Change “visiting clinician” to “attending clinician”
-	"Visiting remarks" to be changed to "admission/physician remarks"
-	Discharge details, laboratory and complications not yet in view for review
-	User role access for clinicians…how does this work at the moment?  
Clinician/user feedback 
-	Regimen date for the first 4 regimen options should be fixed for 10 days (like we do for contact follow-up until). Extended regimen should also come as an additional option
-	Frequency as a drop down; PRN, OD, BD, TD, QDS, Nocte, TDS, 3 TIMES DAILY, OTHERS
-	Change Clinical visits to “admission” and new clinical visit to “new admission” (add variables; respiratory rate, o2 saturation room air (%), capillary refill >3secs?, Mental status, mid-upper arm circumference (MUAC))

**Comment by bernardsilenou** [comment]
Change Clinical visits to “admission”: I think an admission can have many clinical visits, if this is true then it will be confusing to change Clinical visits to “admission”. Admission is defined as "staying over night in a hospital" in other sections of the app. 
The same argument holds for : "Visiting remarks" to be changed to "admission/physician remarks"

**Comment by MartinWahnschaffeSymeda** [comment]
See #989

**Comment by Chinedar** [comment]
@MateStrysewskeSym @MartinWahnschaffeSymeda make case management visible to "national user" accounts. Please this is urgent for tomorrow's lassa fever EOC meeting at 9am. Thanks.

**Comment by MateStrysewskeSym** [comment]
@Chinedar Please just give the users you use for this meeting the necessary user role (i.e. Admin or Case Supervisor/Clinician).

**Comment by Chinedar** [comment]
Ok noted. Thanks.

**Comment by MateStrysewskeSym** [comment]
- [ ] go through all points in this ticket and the word document and create issues and specific questions
