### ISSUE TITLE
Write scheduled ejb calls (CronService) to audit log [1]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9881]
### Problem Description
Scheduled calls that are automatically executed by the backend are currently not written to the audig log (e.g. CronService.archiveCases).

### Proposed Change

- [ ] Extend `AuditLoggerInterceptor` with a method using the `@AroundTimeout` annotation to call auditLogger.logBackendCall in a similar way logAudit does.

If @AroundTimeout works (not sure, never used it, did not find an example that fits our use case), it might work to add the annotation to the existing logAudit method. If it does not work, then a direct invocation should be implemented after https://github.com/hzi-braunschweig/SORMAS-Project/issues/8884 is done.

### Acceptance Criteria

- [ ] All automatic calls of methods in the CronService class appear in the audit log

**Comment by StefanKock** [comment]
If `@AroundTimeout` works (not sure, never used it, did not find an example that fits our use case), it might work to add the annotation to the existing `logAudit` method. If it does not work, then a direct invocation should be implemented after #8884 is done.
