### ISSUE TITLE
contactCategory is not correctly documented in data dictionary

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9883]
### Bug Description

Based on https://github.com/hzi-braunschweig/SORMAS-Project/issues/1635, the `contactCategory` field is hidden on non-de servers and only applicable for COVID-19. This is not correctly documented in the data dictionary.
### Steps to Reproduce

1. Create a new contact
2. Select COVID-19
3. Check for the contact category field
4. Download the data dictionary and check `contactCategory`

### Expected Behavior

- The data dictionary documentation should depict that this field is exclusive or ignored on some instances and specific for COVID-19
### Screenshots

<img width="380" alt="contactCategoryInt2" src="https://user-images.githubusercontent.com/70317594/179489194-c4010b54-fdd1-4c8a-9293-645846c7b62e.PNG">
<img width="891" alt="contactCategoryInt" src="https://user-images.githubusercontent.com/70317594/179489195-5895a0f2-4e5f-4d1e-a707-2783151226d6.PNG">

### System Details

* Device:
* SORMAS version: 1.73.2
* Android version/Browser: chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following behavior:

Steps to reproduce:
1. Make sure that you are logged into a DE specific server;
2. Open the 'Create new contact form';
3. Select any 'Disease of Source Case' that is not COVID-19;
4. Observe the form.
=> 'Contact Category' section appears after actioning step 3.

Expected behavior: 'Contact Category' should appear only if COVID-19 is selected at step 3.

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to the following:

1. Open the 'Create new contact' form;
2. Select 'Covid-19' as the 'Disease of Source Case';
-> 'Contact Category is displayed';
3. Change the 'Disease of Source Case' to any other value;
=> 'Contact Category' should no longer be displayed.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(2c84947).
