### ISSUE TITLE
Duplicate summarization of aggregated reports by each juristiction level

### ISSUE THREAD

**Issue by sergiupacurariu** [hzi-braunschweig/SORMAS-Project#9885]
### Bug Description
The summarization of the aggregated reports is done by each jurisdiction level. Let's say the grouping is "Region". In the database there are the following aggregate reports:
- reports of District1 from the Region1 
- reports of Health Facilities and Point of Entries from District1 under that Region1
For District1 the aggregate report grid will show:
1) one row containing the last report made for District1
2) another row containing the summarization of the aggregate reports made from all Health Facilities and Point of Entries under the District1

The expected behavior is:
- in case an aggregate report for District1 exists show only the row described at point 1) 
- in case there is no aggregate report for District1 show only the row described at point 2)

### Steps to Reproduce

1. Create an aggregate report for District1
2. Create multiple aggregate reports for Health facilities of Point of Entries all under District1
3. Check "Aggregate reporting" grid
4. There will be 2 rows one with the report from point 1 and one row with the summarization of data from point 1

### Expected Behavior

Only one row should be displayed: only point 1 in case exists otherwise only point 2.
### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

#9068

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(81bdbe6).
