### ISSUE TITLE
User management - error appears when Edit or New user created

### ISSUE THREAD

**Issue by abrudanancuta** [hzi-braunschweig/SORMAS-Project#9900]
### Bug Description
As admin when trying to update an existing user or creating a new user, appears a pop-up error message

### Steps to Reproduce
**Case to Edit User**
1. As admin logged in go to Users page
2. Choose a user and open it in Edit mode
3. Don't change anything just make a simple save

**Case to create New User**
1. As admin logged in go to Users page
2. Create a new user
3. Try to save the new user created

### Expected Behavior
Edit and Create user should not throw any error

### Screenshots

<img width="1440" alt="Screenshot 2022-07-19 at 13 34 44" src="https://user-images.githubusercontent.com/91872179/179740803-52267afa-3790-4e3c-b754-bd6f62476a72.png">

### System Details

* Device:
* SORMAS version: 1.75.0 - snapshot
* Android version/Browser:
* Server URL: local
* User Role: Admin

**Comment by abrudanancuta** [comment]
> Is this reproducable on released version?

no

**Comment by StefanKock** [comment]
Then it's not a bug, please discard this ticket and reopen the causing ticket of the active sprint
