### ISSUE TITLE
Surveillance officer should be able to edit visits

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#9901]
### Problem Description
Based on the bugfix #9432 surveillance officer are now no longer able to edit visits in the mobile app. They need to be able to do so, though, since also cases can have visits. (see comment by @bernardsilenou in https://github.com/hzi-braunschweig/SORMAS-Project/issues/9432#issuecomment-1152070944_)

### Proposed Change
- [ ] Surveillance officer default user role should have VISIT_CREATE and VISIT_EDIT user rights
- [ ] For migration there is unfortunately no combination of user rights this can be bound to, so we have to do migration based on the user role caption (except #9645 is done)

**Comment by MartinWahnschaffe** [comment]
@bernardsilenou Actually cases don't have visits in the mobile app, so it's probably not urgent to implement this.

Are you sure that surveillance officers should still receive this right? What about case officer and surveillance supervisor? They currently also don't have this user right.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffe 
Yes, no need to give SO  the followup right.
Since we always give SO and CO user roles to users
