### ISSUE TITLE
 [DEMIS2SORMAS] Editing vaccinations while processing physician reports leads to error when saving or discard entries (Backport of #9858)

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9910]
### Bug Description

Backport of #9858

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by abrudanancuta** [comment]
Validated together with @leventegal-she on his local environment
