### ISSUE TITLE
 [DEMIS2SORMAS] Converting contacts while processing physician reports can disable source cases in epiData (Backport of #9817)

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#9911]
### Bug Description

Backport of #9817

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by abrudanancuta** [comment]
Validated together with @leventegal-she on his local environment
