### ISSUE TITLE
Converting a contact into a case takes over canceled follow up system message

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9914]
### Bug Description

When a contact is converted into a case, the automatic system message gets added to the cases follow up message. This does not make sense because this message is just meant for the contact. Thus, only the comment itself but not the system message should be taken over into the case.
### Steps to Reproduce

1. Create a confirmed contact
2. Add a follow-up comment
3. Convert the contact into a case
4. Check the cases follow-up comment

### Expected Behavior

- Only the followup comment but not the system message should be taken over into the case
### Screenshots

<img width="404" alt="systemFollowUpMessageConvert" src="https://user-images.githubusercontent.com/70317594/180160909-e813ce2f-3ca1-4fba-82c3-faac72292d7f.PNG">

### System Details

* Device:
* SORMAS version: 1.73.2
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
Easiest solution is probably to only add the system message AFTER the follow-up comment has been copied to the case.

**Comment by roxanamlendea** [comment]
Verified ticket on local environment using the latest version of Sormas 1.75.0-SNAPSHOT from the development branch (68389ec).
