### ISSUE TITLE
Event participant directory_clicking on Person ID fails

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9921]
### Bug Description

Clicking on the _Person ID_ in the _event participant directory_ causes the event participant to be opened.

### Steps to Reproduce

1. Create an event with an event participant
2. Open the event participant directory
2. Click on the _Person ID_

### Expected Behavior

Clicking on the PersonID-Link should not open the event participant but the person's detail page
### Screenshots

![event participants 1 73 2](https://user-images.githubusercontent.com/100844689/180225960-d1385a95-00f1-45e6-9a41-7db9ad8efcbe.gif)

### System Details

* Device: Windows 11
* SORMAS version: 1.73.2
* Android version/Browser: Edge
* Server URL: test1402.sormas.netzlink.com
* User Role: admin

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by adinaflorea9** [comment]
The same behavior can be observed in the 'Immunizations' directory (when the full immunization module is enabled) on SORMAS version 1,75,0-SNAPSHOT(F843194):
![Immunizations  - personID](https://user-images.githubusercontent.com/96909231/180711993-6428b3d5-ba9b-4422-96e6-20a51ba98c03.gif)
