### ISSUE TITLE
Error when POE Informant triggers the synchronization after he changes the values for Clinical Confirmation / Epidemiological Confirmation / Laboratory Diagnostic Confirmation of a Case

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#9932]
### Bug Description
When a POE Informant user changes the values for Clinical Confirmation / Epidemiological Confirmation / Laboratory Diagnostic Confirmation of a Case, when he triggers the synchronization he gets an error that 'Some entries could not be synchronized. Please try again later'.

This is also reproducible for: POE Supervisor and POE National User

Might be caused because the user has CASE_CLASSIFY = NO ?

Logs: 
[logs android POE.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9167185/logs.android.POE.txt)

### Steps to Reproduce

1. Log in the mobile app with a POE Informant user;
2. Trigger the synchronization to make sure it works;
3. Open a Case in Edit mode and set values for the following fields: Clinical Confirmation / Epidemiological Confirmation / Laboratory Diagnostic Confirmation; Save.
4. Navigate back to the Cases Directory and trigger the synchronization again.

### Expected Behavior
Needs to be discussed.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/180409599-b63bae66-d9fb-44c7-ad3b-bd01bd35064f.png)

### System Details

* Device:
* SORMAS version: 1.75.0-SNAPSHOT (9332459)
* Android version/Browser: Android 11
* Server URL: https://test-de.sormas.netzlink.com/sormas-rest/
* User Role: POE Informant, POE Supervisor, POE National User

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.75.0-SNAPSHOT(59b6b90).
