### ISSUE TITLE
Language settings are broken

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#9937]
### Bug Description

Admins receive an error when editing the language setting of users in the user management. Users without a language set also receive an error when trying to change the language in the user settings.
### Steps to Reproduce

1. Log in as an admin
2. Edit a user
3. Change the language and save
4. Log in as a user without a pre set language
5. Change the language in the user settings

### Expected Behavior

- The admin should be able to edit the language of a user
- The user should be able to change the user language
### Screenshots

![languageSettingError](https://user-images.githubusercontent.com/70317594/180453873-8a7b542b-cad0-462a-8b43-c0e30132f3b3.gif)

### System Details

* Device:
* SORMAS version: 1.75.0-SNAPSHOT (9332459)
* Android version/Browser: chrome
* Server URL: test-auto.sormas.netzlink.com
* User Role: admin; national user; surveillance supervisor

**Comment by dinua** [comment]
@kwa20 I can no longer reproduce this bug, is it still the the case ?

**Comment by kwa20** [comment]
@dinua tested again on test-auto.sormas.netzlink.com 1.75.0-SNAPSHOT (be232d6). I cannot seem to reproduce it either.

**Comment by adinaflorea9** [comment]
Tested on the local machine using SORMAS version 1.75.0-SNAPSHOT(b464ebb) - behavior described could not be reproduced either, therefore, I will discard the ticket.

(I think that the behavior was fixed with #4462 - check Ancuta's comment https://github.com/hzi-braunschweig/SORMAS-Project/issues/4462#issuecomment-1190072029 that reported the fact that admins could not make changes to existing users or create new users).

**Comment by adinaflorea9** [comment]
I am reopening the ticket as part of the behavior is now reproducible again: any user (except those that have a user role of 'admin') can not change the language from the 'User Settings' - regardless of whether the user had a language set when they were created or the default empty value was used.

Logs from the local machine: 
[user language.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9252969/user.language.txt)


Note: I am not sure if this could be connected to #4462 as at one point it seemed to have been solved by a fix applied to that ticket. Perhaps a developer could investigate this.

**Comment by dinua** [comment]
I discuss with @leventegal-she and this bug will be solved also when ticked https://github.com/hzi-braunschweig/SORMAS-Project/issues/5058 is done

**Comment by adinaflorea9** [comment]
@dinua thank you for letting us know! In that case I will close this ticket and add the ticket's description in a comment to #5058.
