### ISSUE TITLE
[DEMIS2SORMAS] External Messages with very long values permanently block fetching

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#9938]
### Bug Description

We experienced this with one health department in production.

### Steps to Reproduce

1. Upload a DEMIS notification which produces a very long value (>255 chars) for a field that is set to varchar(255) in the SORMAS DB in the lab message table
2. Fetch all notifications via the `FETCH MESSAGES` button in the messages directory.
-> The troublesome message produces an exception

### Expected Behavior

All messages should successfully be fetched.

### System Details

* SORMAS version: 1.72.2

### Additional Information

The relevant error message probably is:
`{"Timestamp":"2022-07-22T13:42:55.058+0200","Level":"ERROR","Version":"Payara 5.2021.10","LoggerName":"org.hibernate.engine.jdbc.spi.SqlExceptionHelper","ThreadID":"595","ThreadName":"http-thread-pool::http-listener-1(9)","TimeMillis":"1658490175058","LevelValue":"1000","LogMessage":"ERROR: value too long for type character varying(255)"}`

[server-log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9168232/fehler_abruf_2207.txt)

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Do we know which columns in the database have the varchar(255) and which one caused the specific problem in the health department? It would be interesting to know which resource in the DEMIS notification this was caused by.

**Comment by markusmann-vg** [comment]
Workaround:
Change manually the synchronization date to a time AFTER the message with the wrong value, so that at least the messages beyond can be fetched.

The fix is planned for 1.74.1

**Comment by FredrikSchaeferVitagroup** [comment]
> @FredrikSchaeferVitagroup Do we know which columns in the database have the varchar(255) and which one caused the specific problem in the health department? It would be interesting to know which resource in the DEMIS notification this was caused by.

Yes, we do know which database columns are of type varchar(255). Those are:

> In the externalmessage table
> 
> - samplematerial (I see no issue here, as this column is only filled with predefined enum values)
> - reportername
> - reporterpostalcode
> - reportercity
> - specimencondition (I see no issue here, as this column is only filled with predefined enum values)
> - testeddisease (I see no issue here, as this column is only filled with predefined enum values)
> - personfirstname
> - personlastname
> - personsex (I see no issue here, as this column is only filled with predefined enum values)
> - personpostalcode
> - personcity
> - personstreet
> - personhousenumber
> - personphone
> - personemail
> - status (PROCESSED/UNPROCESSED... should also not cause a problem)
> - samplematerialtext
> - sampleoveralltestresult (I see no issue here, as this column is only filled with predefined enum values)
> - type (PHYSICIANS_REPORT/LAB_MESSAGE, no problem here)
> 
> Furthermore, there is the reportid column of type varchar(512), which could make the save fail, but I guess this is rather unlikely. And there is reporterexternalids of type character varying [] (255), which could be a problem.

> In the testreport table, which could theoretically also cause this kind of bug, there are the following columns of type varchar(255)
> 
> - testtype (I see no issue here, as this column is only filled with predefined enum values)
> - testresult (I see no issue here, as this column is only filled with predefined enum values)
> - testeddiseasevariant (I see no issue here, as this column is only filled with predefined enum values)
> - testeddiseasevariantdetails (I currently don't see where this is set at all)
> - testpcrtestspecification (I see no issue here, as this column is only filled with predefined enum values)
>
> Furthermore, there are the columns externalid and externalorderid of type varchar(512) which could make the save fail, but I guess this is rather unlikely. And there is testlabexternalids of type character varying [] (255), which could be a problem.

No, we don't know which of the columns caused the problem.

**Comment by FredrikSchaeferVitagroup** [comment]
I suggest the following:

Generally, in the SORMAS-DEMIS-adapter, set the according value to `null` when the string is longer than the SORMAS database allows. I personally think that is better that cutting off the values when they are too long, because this could lead to unnoticed saving of incumomplete and therefore corrupt information.

Introduce a fallback save in SORMAS: when saving a specific external message fails, don't crash, but try to save a minimal version of that message (only containing values for the `uuid`, `externalmessagedetails` and `status` columns). Like this, nothing would be prefilled, but the message would be processable, not be lost and not block the external message feature completely.
One could consider keeping more fields which are not expexted to cause any trouble (e.g. also migrate the `messagedatetime` value from the full to the minimal message), but this would increase the likelyhood of something going wrong when saving the minimal message. The fallback save could also create a log entry.

Additionally, or alternatively, one could change the column types of all or some affected columns to something more tolerant (e.g. varchar(512) or text).

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup 

> Generally, in the SORMAS-DEMIS-adapter, set the according value to null when the string is longer than the SORMAS database allows. I personally think that is better that cutting off the values when they are too long, because this could lead to unnoticed saving of incomplete and therefore corrupt information.

I think this could be a good solution. If we can determine the variable that doesn't conform to the required limitation and is therefore set to `null`, do you think it would be possible to provide the user with a meaningful error message about what happened and which messages are affected? I'm not sure how feasible that is.

**Comment by FredrikSchaeferVitagroup** [comment]
@kwa20 Thank you for the feedback. What you suggest makes sense and seems feasible. But it's more like a feature.
In an internal refinement, we thought about splitting this issue into three

1. The minimal save functionality in SORMAS
2. The replacement of too lang values with null in the SORMAS-DEMIS-adapter
3. Providing meaningful error messages for too lang values to the user at the start of processing a message (this would result in a SORMAS and a SORMAS DEMIS adapter ticket).

In order to quickly provide something for the hotfix, I suggest to do only 1. now (in the scope of this ticket). This would be quickly doable and already resolve the issue. The rest is more complex and can the be done later, it is more comfort feature like.

**Comment by FredrikSchaeferVitagroup** [comment]
I just noticed that the `type` attribute also needs to be migrated to the minimal message (described [here](https://github.com/hzi-braunschweig/SORMAS-Project/issues/9938#issuecomment-1195052522)), in order for the message to be processable.

**Comment by FredrikSchaeferVitagroup** [comment]
This issue is best verified locally. If you don't know how to do it, please reach out to me.

**Comment by abrudanancuta** [comment]
Validated together with @FredrikSchaeferVitagroup on his local environment
