### ISSUE TITLE
Zero/weekly report calculation error (for Ebonyi State)

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Project#994]
![image](https://user-images.githubusercontent.com/35563508/54134193-c9145400-4417-11e9-9053-dda12c996be0.png)

**Comment by MateStrysewskeSym** [comment]
@Chinedar Can you please provide this picture in a higher resolution?

**Comment by Chinedar** [comment]
@SeriousMartin @MateStrysewskeSym when you click on "confirmed report" it does not register in "reports" on the web app for the supervisor to observe. AFIKPO_N_SO affected user.

**Comment by Chinedar** [comment]
![image](https://user-images.githubusercontent.com/35563508/54343815-e7f52f00-463f-11e9-80fb-6b46dc9b1a8d.png)

**Comment by MateStrysewskeSym** [comment]
@Chinedar I'll look into these strange percentage values. Are you 100 % sure the affected SO did a successful sync after submitting the report?

**Comment by Chinedar** [comment]
Yes @MateStrysewskeSym, also observed the same strange % calculation for epi-week 10

![image](https://user-images.githubusercontent.com/35563508/54344698-b54c3600-4641-11e9-92f2-7f462c8c5d30.png)

**Comment by MateStrysewskeSym** [comment]
The reason for the weird percentage values is that users currently can submit their weekly report multiple times until the next sync is done.

- [ ] Fix this problem
- [ ] Remove duplicate reports from the Nigerian server

**Comment by MateStrysewskeSym** [comment]
@Chinedar I've seen three error reports from the user you specified that are associated with a missing internet connection on the 13th of March, but nothing else that would explain why their reports aren't transfered to the server. I would need some more details to be able to identify the problem: Does the user get any error messages when they tried to synchronize? Did they actually click on the Synchronize icon on the top bar in the weekly report form? Do they get a notification that the data was successfully synchronized? Were the cases they reported transfered to the server?

**Comment by Chinedar** [comment]
@MateStrysewskeSym so the user has confirmed that they synchronized successfully and did not get any errors. The web app/supervisor is not able to see the reports. 
Affected users: ODIGBO_SO, AKURE_N,_SO, ILE_OLUJI_SO

**Comment by MateStrysewskeSym** [comment]
@Chinedar Is this still a problem? I've checked the database and saw that there are reports from all three affected users (not for the latest epi week, but multiple reports for each of them). Can you check whether they still have an issue?

**Comment by Chinedar** [comment]
@Maté Strysewske <m.strysewske@symeda.de> This works perfectly now.
Thanks!!!

**Comment by MateStrysewskeSym** [comment]
@Chinedar good to hear!
