### ISSUE TITLE
Inconsistency -When a vaccination is deleted the vaccination status remains VACCINATED [2]

### ISSUE THREAD

**Issue by carina29** [hzi-braunschweig/SORMAS-Project#9943]
### Problem Description

When a vaccination is deleted, in the description of the case the vaccination status will remain VACCINATED however when a case
is created and has no added vaccination, the status is empty,

New case without vaccinations:
![image](https://user-images.githubusercontent.com/47103965/180739932-104d9110-2a6e-4663-8dfc-b8cbda96cc80.png)                                                                
![image](https://user-images.githubusercontent.com/47103965/180740001-5c97a57d-9dfb-43c8-a282-07507f860cc1.png)

Add a vaccination to the same case and delete the vaccination:
![image](https://user-images.githubusercontent.com/47103965/180740504-2826b52d-0886-4a54-9b9c-fdfa9fa02b20.png)
![image](https://user-images.githubusercontent.com/47103965/180740560-73d5a04f-9fc3-49bf-a693-9f731848bca5.png)

**Important:** This is an inconsistency in Sormas project which created an inconsistency in Survnet project too:
When the above mentioned case is sent to the Reporting Tool, vaccination status will be mapped differently and after a deleted vaccination the case will have VACCINATED status.

### Proposed Change

~~Add the same vaccination status(empty) to the cases without vaccination ( even if the case had a vaccination and it was deleted or the case never had a vaccination)~~

**For the reduced immunization module:**
When a vaccination is deleted (and there is no other vaccination for the corresponding immunization) the user should get asked, wether the vaccination status should be updated (deleted) or should be kept. Depending on what he clicks the vaccination status is updated or not.

**Comment by kwa20** [comment]
I noticed that the same happens when the relevant dates of a vaccination, either `reportDate` or `vaccinationDate`, are changed so that no existing vaccination for this person is still relevant for the respective entity (e.g. case). Therefore, the status "Vaccinated" would also no longer be applicable.

**Comment by carina29** [comment]
A bugfix ticket was created for this task which should be parte of 1.75.1 HOTFIX release. 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/10193

**Comment by AndyBakcsy-she** [comment]
Verified ticket on local setup and on test-de.sormas.netzlink.com test environment.
Validated multiple scenarios around the following two main scenarios: 

1. Add one valid vaccination, the case has no other vaccinations, Status is changed. Delete the vaccine and the pop-up is displayed for the confirmation of the change of the status. If confirmed, the status of the case will be changed to empty. If it is not confirmed, the case will still have the vaccinated state. 
2. Add one vaccination that Is irrelevant, case has no other relevant vaccinations, delete the vaccine and nothing happens. The pop-up should not be displayed.

Further tests will be done once the bug #10193 will be fixed and merged
