### ISSUE TITLE
S2S_ make comment fields mandatory [1]

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9946]
### Problem Description

Currently the comment field is not mandatory. Should be mandatory because of data protection and comprehensibility of the share request. 
### Proposed Change

Comment field should be mandatory because of data protection and comprehensibility of the share request. 

Without text filled in it is not possible to share, accept or reject. Clicking 'share' or 'accept' or 'reject' while the field is empty leads to an error message: _Please check the input data Comment_ (like all other error messages you have to press X to close the error message). Try to press again the buttons without data filled in leads to the same error message (until text is filled in). 
If text is filled in and then the text will be deleted by the user completely the error message also appears by clicking on the buttons. 
### Acceptance Criteria

- [ ] Should be mandatory in the "share" window marked with an * (unfortunately you can not see this on the picture) :

![image](https://user-images.githubusercontent.com/100844689/180797840-c11e1341-4798-42ae-8f78-3fceccf18f3a.png)

- [ ] In bulk share the comment is also mandatory

### Implementation Details

- [ ] By hovering over the Textfield the message: _All comments entered must comply with GDPR rules as described during connection_ appears. -> This is the most important thing about this Issue because of data protection reasons.
- [ ] Make the field in `vaadin-app` and `backend` mandatory, but keep it optional in the database.

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by StefanKock** [comment]
UX question: Shouldn't we better ask the user for a reason and what are (usual) reasons to share data or what users are expected to writer there?

**Comment by SahaLinaPrueger** [comment]
@StefanKock It's a good idea, which we also discussed, but we don't want to make S2S too Germany-specific and there will be many more reasons to share in other countries. That's why we decided to leave it as a free text field. In addition, health departments have more freedom and, for example, the possibility to state "urgent" if, for example, an infection of particular severity is involved.

**Comment by SahaLinaPrueger** [comment]
@StefanKock 
- We stay with the word "comment"
- Minimum entry is one letter
- You can implement that the message _All comments entered must comply with GDPR rules as described during connection_ also appears greyed out in the text field at the beginning and disappears if text is added, **but nevertheless** the message must also appear if text is already entered and you swipe/hover over the field.

**Comment by dragosb-vg** [comment]
Validated on de1<->de2 live test instances on Version: 1.76.0-SNAPSHOT [(0c95d19)](https://github.com/hzi-braunschweig/SORMAS-Project/commits/0c95d195ae9d6f264a892c33cbaab9edaeb80f95)

**Case/contact/event cannot be shared without entering at least 1 character in the Share dialog's "Comment" field.**

- Mandatory mark (*) is present for the Comment field
- Tooltip is displayed correctly, with the specified text
- Error message is present and has correct behavior (even for cumulative errors)

![image](https://user-images.githubusercontent.com/111864167/192760479-225daa20-1d05-4929-bc94-acb431922162.png)
![image](https://user-images.githubusercontent.com/111864167/192760574-28fd7c89-e1fa-4b4d-8e75-a148eecbb438.png)
![image](https://user-images.githubusercontent.com/111864167/192761446-c86bd8cf-ec44-4b74-98aa-0b59a99dfe20.png)
