### ISSUE TITLE
[S2S] Simultaneous work possible

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#9967]
Split from #9836

### Bug Description

If we encounter an exception during the back-sharing of a case, we do not abort the operation but leave the system in an inconsistent state where both sides can edit a case. I can confirm that without the exception, everything works fine. 

From @SahaLinaPrueger  initial comment: 

> This occurs if you add an external ID AND/OR external token and internal token and general comment to the case. I did not tested if this is also possible it you only add an internal token or external token or general comment. It is certain that without fill in this fields everything works correctly.

I would argue that this works independently of the set tokens and the root cause is the exception interfering with the operation, but I need to check this separately. Also I think this is likely independent from the survnet exception and that any other exception could lead to the same state, but this needs to be confirmed as well.

### Steps to Reproduce
1. SORMAS B: set `survnet.url=http://localhost` and do not run a converter such that this throws an error.
1. SORMAS A: Create a case on SORMAS A and add an external ID, external token, internal token and general comment + external ID of pathogen result 
1. SORMAS A: Send the case to SORMAS B with hand over the ownership
1. SORMAS B: Open the case on SORMAS B and check if external ID, external token, internal token and general comment + external ID of pathogen result are visible 
1. SORMAS B: Change the external token, internal token and general comment on SORMAS B 
1. SORMAS B: Save the case 
1. SORMAS A: Open the case on SORMAS A and check if fields are greyed out because SORMAS A has no longer the hand over the ownership and if the sync is correct.
1. SORMAS B: Open the case on SORMAS B and send the case back to SORMAS A with hand over the ownership 
1. SORMAS A: Open the case on SORMAS A and check if external ID, external token, internal token and general comment + external ID of pathogen result are visible (result: they are visible, + external ID of the case is editable)
1. SORMAS A: Open the case and check if responsible jurisdiction had changed (result: did not)
1. SORMAS B: Open the case on SORMAS B and check if fields are greyed out because SORMAS B has no longer the hand over the ownership (result: fields are not greyed out)
1. Try to edit data in SORMAS A and SORMAS B and see if they sync correctly (result: they sync correctly) 

### Expected Behavior

In the end, the case should not be editable on SORMAS B anymore. Fields have to be greyed out. Seems like the hand over the ownership still belongs to SORMAS B, that would explain why the jurisdiction does not change.

### Additional Information

Properties for BOTH systems:

sormas2sormas.ignoreProperty.additionalDetails=false
sormas2sormas.ignoreProperty.externalId=false
sormas2sormas.ignoreProperty.externalToken=false
sormas2sormas.ignoreProperty.internalToken=false

**Comment by JonasCir** [comment]
@SahaLinaPrueger I cannot reproduce the issue unfortunately. SORMAS B is grayed out as it should be, but I do another run.

I have one additional question about responsible jurisdiction: This value is to the best of my knowledge user provided and not set automatically by the instance. I'm not aware of a server property which records where an instance is located. Therefore, I expect the value to remain the same completely independently from how often and with whom you share the case.

**Comment by JonasCir** [comment]
I have somehow the feeling this happened due to the Survnet deletion error, which left the system in an inconsistent state.

**Comment by JonasCir** [comment]
Haha can reproduce now @SahaLinaPrueger I'm going to update the description :D It's indeed a fallout from the SurvNet error. Which means that when we encounter an error during the share, we share anyway and leave both systems in an inconsistent state which his quite bad.

**Comment by SahaLinaPrueger** [comment]
I hope i can answer your first question, but i am not sure if this is the answer you are searching for: To make the responsible jurisdiction change you have to set this value on the instance: SORMAS2SORMAS_DISTRICT_EXTERNALID: 11008425 
The number of the external ID changes depending on the district of the instance.

**Comment by JonasCir** [comment]
@SahaLinaPrueger Thank you this should help :) This is a separate issue then which I'm going to file when I have time.

**Comment by JonasCir** [comment]
I started a couple of attempts to reproduce this again on the latest version of the hotfix branch and I'm quite certain now, that we coincidentally fixed this in one of the other tickets which were split from https://github.com/hzi-braunschweig/SORMAS-Project/issues/9836 .

**Comment by AndyBakcsy-she** [comment]
This issue has been tested during other sessions of sormas to sormas tests. 
One note: Once there is an error message S2S communication does not continue so, if the expectation was that after the 500 Server error the entities are still getting synced, this is not the case.

**Comment by AliciaRaber** [comment]
Test performed.

Created case
Source system: release-sormas-x.sormas.netzlink.com
Target system: test1402.sormas.netzlink.com
Case after sending to target system
Case ID source system: XQ6YUA-F6M5XT-IYSO5T-BBTICHHM
External token, internal token and notes in case not transferred to target system
External ID of pathogen result not transferred

After sharing back the case from
source system: test1402.sormas.netzlink.com
to target system: release-sormas-x.sormas.netzlink.com
External token, internal token and notes in case were in system
External ID of pathogen result has been transferred

Changing results
Changing of district and entries in fields internal token, external token and ID in pathogen result were not synced with source system.

**Comment by SahaLinaPrueger** [comment]
The properties on release-de and release-x are currently on 'true'.
I tested this with the correct properties, everything is okay here :)
