### ISSUE TITLE
S2S_ implement a warning message when data can be edited although they do not belong to me

### ISSUE THREAD

**Issue by SahaLinaPrueger** [hzi-braunschweig/SORMAS-Project#9986]
### Feature Description

Currently it is possible that two instances can simultaneously work on a case/contact/ person.

Follow the steps to reproduce:

_First scenario_
1. share the case/contact with ownership (with hand over the ownership) 
2. accept the case/contact in target system 
3. open the case/contact in source system -> you can not edit anything. Everything is greyed out.
4. open the person of the case/contact in the source system -> you can edit something 
5. add something
6. look in target system if sync is correct (sync works)

_Second scenario_
1. make sure there exist at least two cases OR one case and one contact OR two contacts for/on/at the same person in the source system.
2. repeat the steps of the first scenario and then continue with the following steps:
7. open the case/contact you have not shared (case/ contact is still editable)
8. go to the tab _case/contact person_ and try to add something -> you can add/edit something

_Third scenario_
1. share a case/contact for viewing / to view / with no hand over the ownership
2. Accept the case/contact on target system 
3. open the case /contact in target system -> everything is greyed out
4. open the person in target system -> everything is greyed out
5. add a new case/contact with the same data so the duplicate detection for person show up
6. add the new case/contact to the existing person
7. try to edit data in the new case/ contact _tab case/contact person_ 
8. see if sync to source system works -> works

### Proposed Change

- Add a warning message 
_Please note: The person is shared with another organization. Please check if you are responsible for this person. If you change something on this person, the person will also be changed immediately at the other organisation.  If you are not responsible, it will lead to confusion_
- AND add a big red _!_ in a triangle - and by hovering over it the warning message appears. 

Add both on the following places:
- First scenario:  
**_step 4_:** 
- [ ] Add the pop-up warning message if the user opens the person. The pop-up warning message can be closed and the user sees the person. 
- [ ] Add a big red _!_ in a triangle in the following place and by hovering over it the warning message (see above) appears: 
![image](https://user-images.githubusercontent.com/100844689/189398588-16e67254-cc98-4ff2-b284-d13673da9feb.png)

- Second scenario
**_step 8_:**
- [ ]  Add the pop-up warning message if the user opens the tab _case person_/ tab _contact person_ . The pop-up warning message can be closed and the user sees the tab _case person_/ tab _contact person_ 
- [ ] Add a big red _!_ in a triangle in the following place and by hovering over it the warning message (see above) appears: 
![image](https://user-images.githubusercontent.com/100844689/189398740-e6f46f9a-a3c2-4982-9297-8a1b62e140e0.png)

- Third scenario
**_step 7_:**
- [ ] Add the pop-up warning message if the user opens the tab _case person_/ tab _contact person_ . The pop-up warning message can be closed and the user sees the tab _case person_/ tab _contact person_
- [ ] And add a big red _!_ in a triangle in the following place and by hovering over it the warning message (see above) appears: 
![image](https://user-images.githubusercontent.com/100844689/189398775-3dc4c816-30e7-4f45-af2a-99dfc16de955.png)

**Comment by SahaLinaPrueger** [comment]
@JaquM-HZI

**Comment by StefanKock** [comment]
Open question: Does keeping persons in-sync between instances makes sense?

**Comment by SahaLinaPrueger** [comment]
@StefanKock Yes. Especially people's names or dates of birth can be misspelled or mixed up.

**Comment by bernardsilenou** [comment]
I think It is fine if multiple instances or jurisdictions can edit a person, condition that the person is linked to the entities in the instances or jurisdictions. However, only one instances/ jurisdiction should have full access to entities of a person at a point in time.

For scenario 3, when I add a new entity to the existing person with read access only, then I should automatically have full access to the person and the entity that I added, but read access to the other entities shared with me.

**Comment by SahaLinaPrueger** [comment]
@StefanKock 
- We stay with the decision, that we want the persons to be synced. 
- I know that we do not share persons, but i thought this would be the easiest way to make this understandable to the user. Do you have a better suggestion? I can imagine that it is difficult as a developer to tell half-truths. 
Would this be better: _Please note: A case or contact of this person is shared with another organization. Please check if you are responsible for this person. If you change something on this person, the person will also be changed immediately at the other organization. If you are not responsible, this will lead to confusion_
- @bernardsilenou I also thought about this but then I thought that might get too complicated, but you are absolutely right. If I have a case or a contact in my system that is owned by me, I should be able to edit the person. Then we have to implement the warning message at this place, too. @StefanKock would you see this as a bug or a change?
The bug/ change would be step 9 + step 10: 
1. share a case/contact for viewing / to view / with no hand over the ownership
2. Accept the case/contact on target system
3. open the case /contact in target system -> everything is greyed out
4. open the person in target system -> everything is greyed out
5. add a new case/contact with the same data so the duplicate detection for person show up
6. add the new case/contact to the existing person
7. try to edit data in the new case/ contact tab case/contact person
8. see if sync to source system works -> works
9. open the person on target system -> warning message appears + triangle -> you can edit something
10. open the case/ contact which was shared with no hand over the ownership -> still NOT editable and tab case person / tab contact person still NOT editable, too.

**Comment by SahaLinaPrueger** [comment]
@StefanKock I forgot the following scenario:
Can you please implement step 5, too?

1. Source system: A case/contact with an attached event is shared with hand over the ownership
2. Target system accepts the case/ contact
3. Source system: Open the event of the shared case/contact with ownership
4. Source system: open the tab "event participants" and click on the "event participant ID"
5. Source system: warning message appears + triangle on the following place:
![image](https://user-images.githubusercontent.com/100844689/190983905-1bbc98b2-3252-40d5-870f-46d00528d64d.png)
